### ISSUE TITLE
Make Class's annotation cache more resilient across redefines

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse-openj9/openj9#10026]
There is a window in the code between when the annotations are fetched from the `J9Class` and when they are processed during which the class can be redefined.  This can lead to `Wrong type at constant pool index` errors.

Problematic code is:
https://github.com/eclipse/openj9/blob/1e504101295ed6f569a29741466546bb9cdcfa3a/jcl/src/java.base/share/classes/java/lang/Class.java#L2940-L2948

We need to change the code to ensure that the J9Class matching the annotation date is used to process the constantpool indexes.

Currently, we can specify the `J9Class` to be used in `getConstantPool` by converting the `J9Class` pointer with `public Object createInternalRamClass(long addr);` to create something we can pass to ConstantPool.

Some options for addressing this
* Hack getDeclaredAnnotationsData to include the j9class pointer in the byte array in some way so we have the matching j9class for the data.  Appending it would be the simplest if we can lie about the size of the data.
* look up the j9class just prior to calling getDeclaredAnnotationsData() and have a smaller window for inconsistent data
* something else?

Example stacktrace:
```
java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:78)
        at java.base/java.lang.Class.getAnnotationCache(Class.java:2789)
        at java.base/java.lang.Class.getAnnotation(Class.java:2437)
        at ....
Caused by: java.lang.IllegalArgumentException: Wrong type at constant pool index
        at java.base/jdk.internal.reflect.ConstantPool.getUTF8At0(Native Method)
        at java.base/jdk.internal.reflect.ConstantPool.getUTF8At(ConstantPool.java:65)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:280)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
        ... 34 more

**Comment by yaohwu** [comment]
This problem happened to my project after redefined or retransformed the class using bytebuddy.

**Comment by yaohwu** [comment]
It happened accidentally even after reset the retransformation using bytebuddy

**Comment by yaohwu** [comment]
Well, the origin link https://www.ibm.com/support/pages/apar/IV43462 said it had been fixed in 2013.
Actually, the defect still exists.

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@EricYangIBM Start with this approach
> Hack getDeclaredAnnotationsData to include the j9class pointer in the byte array in some way so we have the matching j9class for the data. Appending it would be the simplest if we can lie about the size of the data.

**Comment by EricYangIBM** [comment]
To clarify, the byte array should be allocated with more space to store the current class pointer and returned, then in `getAnnotationCache()` we get the pointer from the array and pass the `annotationsData` (without the pointer), `getConstantPool(class)`, and the class to `parseAnnotations`?

**Comment by tajila** [comment]
This is the byte array that needs to return annotation data + j9class pointer `private native byte[] getDeclaredAnnotationsData();` 

In `getAnnotationCache()` we get the pointer from the array and use it to fetch the correct `constantPool`, the `constantPool` is passed into `parseAnnotations`

**Comment by pshipton** [comment]
Reopening as the fix was reverted.

**Comment by pshipton** [comment]
Reopening since https://github.com/eclipse-openj9/openj9/pull/13836 was reverted.

**Comment by bvsvas** [comment]
I get the same error AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index It comes while hitting REST Endpoint in Spring Boot application deployed in WebSphere Liberty. It only comes when call was made after class retransformation by java agent. This error doesn't come if endpoint hits before class retransformation.

**JDK used:**
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 8.0.8.0 - pxa6480sr8-20230314_01(SR8))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230313_47323 (JIT enabled, AOT enabled)
OpenJ9 - 4d03a8c
OMR - 49526cb
IBM - 7187a01

**Error stack trace:**

```
Caused by: java.lang.IllegalArgumentException: Wrong type at constant pool index
	at sun.reflect.ConstantPool.getClassAt0(Native Method)
	at sun.reflect.ConstantPool.getClassAt(ConstantPool.java:49)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:256)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:238)
	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations2(AnnotationParser.java:196)
	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations(AnnotationParser.java:173)
Caused by: java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations(AnnotationParser.java:179)
	at java.lang.reflect.Executable.parseParameterAnnotations(Executable.java:91)
	at java.lang.reflect.Executable.sharedGetParameterAnnotations(Executable.java:566)
	at java.lang.reflect.Method.getParameterAnnotations(Method.java:660)
	at org.springframework.core.MethodParameter.getParameterAnnotations(MethodParameter.java:635)
	at org.springframework.web.method.HandlerMethod$HandlerMethodParameter.getParameterAnnotations(HandlerMethod.java:541)
	at org.springframework.core.MethodParameter.getParameterAnnotation(MethodParameter.java:668)
	at org.springframework.core.MethodParameter.hasParameterAnnotation(MethodParameter.java:683)
	at org.springframework.web.method.annotation.ModelFactory.findSessionAttributeArguments(ModelFactory.java:182)
	at org.springframework.web.method.annotation.ModelFactory.initModel(ModelFactory.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:872)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
```
