### ISSUE TITLE
AArch64: Intermittent failures in running javac

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#10126]
There are intermittent failures in running javac with recent AArch64 XL builds as shown below.  Not seen with CR builds.  They are NullPointerExceptions in most cases, but SEGVs in some other cases.

Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/149/consoleText
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/150/consoleText

Optional info
-------------

- intermittent failure: yes
- regression or new test: regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) : N/A

Failure output (captured from console output)
---------------------------------------------

NPE case:
```
[2020-07-06T00:55:58.121Z] An exception has occurred in the compiler (11.0.8). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
[2020-07-06T00:55:58.121Z] java.lang.NullPointerException
[2020-07-06T00:55:58.121Z] 	at jdk.compiler/com.sun.tools.javac.comp.Infer$GraphSolver.solve(Infer.java:1670)
[2020-07-06T00:55:58.121Z] 	at jdk.compiler/com.sun.tools.javac.comp.InferenceContext.solve(InferenceContext.java:475)
[2020-07-06T00:55:58.121Z] 	at jdk.compiler/com.sun.tools.javac.comp.InferenceContext.solve(InferenceContext.java:482)
[2020-07-06T00:55:58.121Z] 	at jdk.compiler/com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:218)
[2020-07-06T00:55:58.121Z] 	at jdk.compiler/com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:605)
```

SEGV in compiled code:
```
[2020-07-08T00:42:25.975Z] stderr:
[2020-07-08T00:42:25.975Z] Unhandled exception
[2020-07-08T00:42:25.975Z] Type=Segmentation error vmState=0x00000000
[2020-07-08T00:42:25.975Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2020-07-08T00:42:25.975Z] Handler1=0000FFFF95C90934 Handler2=0000FFFF95B6D300 InaccessibleAddress=0000000099669888
[2020-07-08T00:42:25.975Z] R0=0000FFFF9080E600 R1=0000000000000000 R2=0000000000000000 R3=0000000000000001
[2020-07-08T00:42:25.975Z] R4=0000000000000003 R5=0000000000000000 R6=0000FFFF8FE5DF98 R7=0000FFFF70C3B458
[2020-07-08T00:42:25.975Z] R8=0000FFFF9071B700 R9=FFFFFFFFFFFFFF88 R10=0000FFFF8FE5EBC0 R11=0000FFFF8FE5EBE8
[2020-07-08T00:42:25.975Z] R12=0000000000000030 R13=0000FFFF8FE4D4D0 R14=0000000000000010 R15=0000000000000001
[2020-07-08T00:42:25.975Z] R16=0000FFFF950DC4E4 R17=0000FFFF96751180 R18=0000FFFF9080E600 R19=0000FFFF901FA800
[2020-07-08T00:42:25.975Z] R20=0000FFFF90D21040 R21=0000FFFF70372710 R22=0000FFFF8FE5DB30 R23=0000FFFF8FE5DF98
[2020-07-08T00:42:25.975Z] R24=0000000099669900 R25=0000FFFF8FE4D448 R26=0000FFFF8FE4D448 R27=0000FFFF8F9D8EF0
[2020-07-08T00:42:25.975Z] R28=0000FFFF8FE5EB20 R29=FCFCFE00FF000000 R30=0000FFFF58667798 R31=0000FFFF965E2240
[2020-07-08T00:42:25.975Z] PC=0000FFFF586662B8 SP=0000FFFF965E2240 PSTATE=0000000060000000
[2020-07-08T00:42:25.975Z] V0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V1 000000003f400000 (f: 1061158912.000000, d: 5.242822e-315)
[2020-07-08T00:42:25.975Z] V2 0000000041800000 (f: 1098907648.000000, d: 5.429325e-315)
[2020-07-08T00:42:25.975Z] V3 bfe01d84c73bc741 (f: 3342583552.000000, d: -5.036034e-01)
[2020-07-08T00:42:25.975Z] V4 bfd00ea348b88334 (f: 1220051712.000000, d: -2.508934e-01)
[2020-07-08T00:42:25.975Z] V5 3fd5575b0be00b6a (f: 199232368.000000, d: 3.334568e-01)
[2020-07-08T00:42:25.975Z] V6 bfdffffef20a4123 (f: 4060758272.000000, d: -4.999997e-01)
[2020-07-08T00:42:25.975Z] V7 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
[2020-07-08T00:42:25.975Z] V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V16 bff0000000000000 (f: 0.000000, d: -1.000000e+00)
[2020-07-08T00:42:25.975Z] V17 c037154748bef6c8 (f: 1220474624.000000, d: -2.308312e+01)
[2020-07-08T00:42:25.975Z] V18 401e840b4ac4e4d2 (f: 1254417664.000000, d: 7.628949e+00)
[2020-07-08T00:42:25.975Z] V19 0000ffff94bc8be8 (f: 2495384576.000000, d: 1.390662e-309)
[2020-07-08T00:42:25.975Z] V20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2020-07-08T00:42:25.975Z] V31 000000003f400000 (f: 1061158912.000000, d: 5.242822e-315)
[2020-07-08T00:42:25.975Z] 
[2020-07-08T00:42:25.975Z] Compiled_method=com/sun/tools/javac/comp/Infer$GraphSolver.solve(Lcom/sun/tools/javac/comp/Infer$GraphStrategy;)V
```

**Comment by knn-k** [comment]
A similar failure is found with a CR build:
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/196/consoleText

```
[2020-07-08T12:06:44.874Z] An exception has occurred in the compiler (11.0.8). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
[2020-07-08T12:06:44.875Z] java.lang.ClassCastException: com.sun.tools.javac.code.Type$TypeVar incompatible with com.sun.tools.javac.code.Type$UndetVar
[2020-07-08T12:06:44.875Z] 	at jdk.compiler/com.sun.tools.javac.comp.Infer.instantiateAsUninferredVars(Infer.java:522)
[2020-07-08T12:06:44.875Z] 	at jdk.compiler/com.sun.tools.javac.comp.Infer$GraphSolver.solve(Infer.java:1682)
[2020-07-08T12:06:44.875Z] 	at jdk.compiler/com.sun.tools.javac.comp.InferenceContext.solve(InferenceContext.java:475)
[2020-07-08T12:06:44.875Z] 	at jdk.compiler/com.sun.tools.javac.comp.InferenceContext.solve(InferenceContext.java:482)
[2020-07-08T12:06:44.875Z] 	at jdk.compiler/com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:218)
[2020-07-08T12:06:44.875Z] 	at jdk.compiler/com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:605)
```

**Comment by knn-k** [comment]
The same NPEs and SEGVs are seen in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/155/consoleText

**Comment by knn-k** [comment]
New kind of javac failures only in an XL build:
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/162/consoleText
```
[2020-07-21T00:25:23.269Z] /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/condy/BootstrapMethodJumboArgsTest.java:35: error: package org.testng does not exist
[2020-07-21T00:25:23.269Z] import org.testng.Assert;
[2020-07-21T00:25:23.269Z]                  ^
[2020-07-21T00:25:23.269Z] /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/condy/BootstrapMethodJumboArgsTest.java:36: error: package org.testng.annotations does not exist
[2020-07-21T00:25:23.269Z] import org.testng.annotations.Test;
[2020-07-21T00:25:23.269Z]                              ^
[2020-07-21T00:25:23.269Z] /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/condy/BootstrapMethodJumboArgsTest.java:95: error: cannot find symbol
[2020-07-21T00:25:23.269Z]     @Test
[2020-07-21T00:25:23.269Z]      ^
[2020-07-21T00:25:23.269Z]   symbol:   class Test
[2020-07-21T00:25:23.269Z]   location: class BootstrapMethodJumboArgsTest
[2020-07-21T00:25:23.269Z] /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/condy/BootstrapMethodJumboArgsTest.java:130: error: cannot find symbol
[2020-07-21T00:25:23.269Z]     @Test
[2020-07-21T00:25:23.269Z]      ^
[2020-07-21T00:25:23.269Z]   symbol:   class Test
[2020-07-21T00:25:23.269Z]   location: class BootstrapMethodJumboArgsTest
[2020-07-21T00:25:23.269Z] /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/condy/BootstrapMethodJumboArgsTest.java:106: error: cannot find symbol
[2020-07-21T00:25:23.269Z]             Assert.assertEquals(actual, expected);
[2020-07-21T00:25:23.269Z]             ^
[2020-07-21T00:25:23.269Z]   symbol:   variable Assert
[2020-07-21T00:25:23.269Z]   location: class BootstrapMethodJumboArgsTest
```

**Comment by knn-k** [comment]
9 failures (8 NPEs + 1 SEGV) with `Infer$GraphSolver.solve()` in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/164/consoleText

**Comment by adamfarley** [comment]
Still occurs: https://trss.adoptopenjdk.net/output/test?id=5f28df4e0bec7975ae099de4

**Comment by knn-k** [comment]
#10413 is an issue with JDK 8 AArch64.
That one may be also related to javac.  It crashes in an interface call from `com/sun/tools/javac/comp/Infer$InferenceContext::notifyChange()`.

**Comment by knn-k** [comment]
The same failure in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/230/consoleText
It is a rare example of this failure with a compressed refs build.

**Comment by knn-k** [comment]
The failure with CompletableFuture/Basic in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/193/consoleText:
```
[2020-09-01T00:48:46.334Z] Unhandled exception
[2020-09-01T00:48:46.334Z] Type=Segmentation error vmState=0x00000000
[2020-09-01T00:48:46.334Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2020-09-01T00:48:46.334Z] Handler1=0000FFFFAA1A93E0 Handler2=0000FFFFAA0E9098 InaccessibleAddress=0000000099669888
[2020-09-01T00:48:46.334Z] R0=0000FFFFA4826E00 R1=0000000000000000 R2=0000000000000000 R3=0000000000000001
[2020-09-01T00:48:46.334Z] R4=0000000000000003 R5=0000000000000000 R6=0000FFFFA36F92A8 R7=0000FFFF84A75BB8
[2020-09-01T00:48:46.334Z] R8=0000FFFFA472A900 R9=FFFFFFFFFFFFFF88 R10=0000FFFFA36F9F68 R11=0000FFFFA36F9F90
[2020-09-01T00:48:46.334Z] R12=0000000000000040 R13=0000FFFFA36F6480 R14=0000000000000010 R15=0000000000000001
[2020-09-01T00:48:46.334Z] R16=0000FFFFA95F38A0 R17=0000FFFFAAE96180 R18=0000FFFFA4826E00 R19=0000FFFFA420F500
[2020-09-01T00:48:46.334Z] R20=0000FFFFA4D64DE0 R21=0000FFFF843D3708 R22=0000FFFFA36F8E40 R23=0000FFFFA36F92A8
[2020-09-01T00:48:46.334Z] R24=0000000099669900 R25=0000FFFFA36F63F8 R26=0000FFFFA36F63F8 R27=0000FFFF846C9810
[2020-09-01T00:48:46.334Z] R28=0000FFFFA36F9EC8 R29=0000FFFFA46E5400 R30=0000FFFF6C94AA04 R31=0000FFFFAADDFE60
[2020-09-01T00:48:46.334Z] PC=0000FFFF6C949CA0 SP=0000FFFFAADDFE60 PSTATE=0000000060000000
```

The caller instructions are as follows.  It seems to call a virtual method `com/sun/tools/javac/comp/Infer.doIncorporation()`:
```
   0xffff6c949c70:      cbz     w18, 0xffff6c949d4c
   0xffff6c949c74:      mov     x21, x0
   0xffff6c949c78:      mov     x22, x1
   0xffff6c949c7c:      mov     x23, x6
   0xffff6c949c80:      ldr     x18, [x21, #32] // x21 should point to an Infer$GraphSolver object
   0xffff6c949c84:      cbz     x18, 0xffff6c95105c
   0xffff6c949c88:      mov     x0, x18 // x18 should point to an Infer object
   0xffff6c949c8c:      ldr     x1, [x21, #16]
   0xffff6c949c90:      ldr     x2, [x21, #24]
   0xffff6c949c94:      ldr     x24, [x18]
   0xffff6c949c98:      and     x24, x24, #0xffffffffffffff00
   0xffff6c949c9c:      mov     x9, #0xffffffffffffff88         // #-120
   0xffff6c949ca0:      ldr     x9, [x24, x9] <= crash here with x24 = 0x99669900
   0xffff6c949ca4:      blr     x9
   0xffff6c949ca8:      mov     x6, x23
   0xffff6c949cac:      mov     x1, x22
   0xffff6c949cb0:      mov     x0, x21
```

**Comment by knn-k** [comment]
`jdmpview` command says `x18` and `x21` are pointing to unexpected objects in the case above, as shown below.

```
> whatis 0x0FFFFA4826E00 // x18
        heap #1 - name: Generational@ffffa41ddb20
                0xffffa4826e00 is not within this heap.
        0xffffa4826e00 is the address of the java/lang/Class object for com/sun/tools/javac/code/Symbol$Completer$1
    (should be a com/sun/tools/javac/comp/Infer object)

> whatis 0x0FFFF843D3708 // x21
        heap #1 - name: Generational@ffffa41ddb20
                0xffff843d3708 is within heap segment: ffff84000000 -- ffff852d0000
                0xffff843d3708 is the start of an object of type com/sun/tools/javac/util/List$1
    (should be a com/sun/tools/javac/comp/Infer$GraphSolver object)
```

**Comment by knn-k** [comment]
Another example of javac failure with JDK 8 in https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/114/consoleText

```
[2020-11-17T17:55:36.177Z] An exception has occurred in the compiler (1.8.0_275-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
[2020-11-17T17:55:36.177Z] java.lang.ClassCastException: com.sun.tools.javac.util.List$1 incompatible with com.sun.tools.javac.code.Type
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.code.Types$Subst.subst(Types.java:3010)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.code.Types.subst(Types.java:2984)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Infer$InferenceContext.asInstType(Infer.java:2090)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Check$2.typesInferred(Check.java:538)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Infer$InferenceContext.notifyChange(Infer.java:2122)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:212)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:567)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1446)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1633)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1704)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1677)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve$9.doLookup(Resolve.java:2436)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3097)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3348)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2433)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2427)
[2020-11-17T17:55:36.177Z] 	at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3396)
```

**Comment by knn-k** [comment]
This failure has not been observed recently. Closing.
