### ISSUE TITLE
JDK16 TEST: java/lang/invoke/MethodHandles/publicLookup/Driver.java - AssertionError: unexpected result

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#10648]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_s390x_linux_xl_Nightly/167`:
```
22:24:00  openjdk version "16-internal" 2021-03-16
22:24:00  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxxlNightly)
22:24:00  Eclipse OpenJ9 VM (build master-149dd6186ef, JRE 16 Linux s390x-64-Bit 20200917_189 (JIT enabled, AOT enabled)
22:24:00  OpenJ9   - 149dd6186ef
22:24:00  OMR      - 25e93bed006
22:24:00  JCL      - 2e50335fca8 based on jdk-16+15)
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:19:03  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=s390x_linux_xl&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:31:08  TEST: java/lang/invoke/MethodHandles/publicLookup/Driver.java
22:31:08  TEST JDK: /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_s390x_linux_xl_Nightly/openjdkbinary/j2sdk-image
22:31:08  

22:31:08  STDERR:
22:31:08  CL1: verify access for [java.lang.Object/publicLookup, q.EndPoint/publicLookup, q.EndPoint/publicLookup]
22:31:08  java.lang.AssertionError: unexpected result
22:31:08  	at m1/p.Main.assertTrue(Main.java:104)
22:31:08  	at m1/p.Main.checkTypeConsistency(Main.java:98)
22:31:08  	at m1/p.Main$Test.verifyAccess(Main.java:66)
22:31:08  	at m1/p.Main.main(Main.java:89)
22:31:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:31:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:31:08  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:31:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:31:08  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:31:08  	at java.base/java.lang.Thread.run(Thread.java:845)
22:31:08  
22:31:08  JavaTest Message: Test threw exception: java.lang.AssertionError: unexpected result
22:31:08  JavaTest Message: shutting down test
22:31:08  
22:31:08  STATUS:Failed.`main' threw exception: java.lang.AssertionError: unexpected result
```

**Comment by babsingh** [comment]
**Note:** This failure does not fix once OJDK MHs are enabled in OpenJ9. In other word, this failure is seen with both OpenJ9 and OJDK MHs.

**Comment by JasonFengJ9** [comment]
The failure is reproduced against recent JDK16 at `Test_grinder/job/Grinder/17533`
```
09:10:10  openjdk version "16.0.2-internal" 2021-07-20
09:10:10  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16s390xlinuxPersonal)
09:10:10  Eclipse OpenJ9 VM (build master-b49892b0b23, JRE 16 Linux s390x-64-Bit Compressed References 20210813_50 (JIT enabled, AOT enabled)
09:10:10  OpenJ9   - b49892b0b23
09:10:10  OMR      - ac3ab4821a5
09:10:10  JCL      - 44316ee515b based on jdk-16.0.2+7)

09:12:27  --------------------------------------------------
09:12:27  TEST: java/lang/invoke/MethodHandles/publicLookup/Driver.java

09:12:27  STDERR:
09:12:27  CL1: verify access for [java.lang.Object/publicLookup, q.EndPoint/publicLookup, q.EndPoint/publicLookup]
09:12:27  java.lang.AssertionError: unexpected result
09:12:27  	at m1/p.Main.assertTrue(Main.java:104)
09:12:27  	at m1/p.Main.checkTypeConsistency(Main.java:98)
09:12:27  	at m1/p.Main$Test.verifyAccess(Main.java:66)
09:12:27  	at m1/p.Main.main(Main.java:89)
09:12:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:12:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
09:12:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:12:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
09:12:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:12:27  	at java.base/java.lang.Thread.run(Thread.java:883)
09:12:27  
09:12:27  JavaTest Message: Test threw exception: java.lang.AssertionError: unexpected result
09:12:27  JavaTest Message: shutting down test
09:12:27  
09:12:27  STATUS:Failed.`main' threw exception: java.lang.AssertionError: unexpected result
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=openjdk&PLATFORM=s390x_linux&CUSTOM_TARGET=java/lang/invoke/MethodHandles/publicLookup/Driver.java&TARGET=jdk_custom_0)

This is reproduced with 0.27 release (w/o OJDK MH) at `Test_grinder/job/Grinder/17534`
```
09:16:34  openjdk version "16.0.2" 2021-07-20
09:16:34  IBM Semeru Runtime Open Edition 16.0.2.0 (build 16.0.2+7)
09:16:34  Eclipse OpenJ9 VM 16.0.2.0 (build openj9-0.27.0, JRE 16 Linux s390x-64-Bit Compressed References 20210728_65 (JIT enabled, AOT enabled)
09:16:34  OpenJ9   - 1851b0074
09:16:34  OMR      - 9db1c870d
09:16:34  JCL      - 34df42439f3 based on jdk-16.0.2+7)

09:19:02  STDERR:
09:19:02  CL1: verify access for [java.lang.Object/publicLookup, q.EndPoint/publicLookup, q.EndPoint/publicLookup]
09:19:02  java.lang.AssertionError: unexpected result
09:19:02  	at m1/p.Main.assertTrue(Main.java:104)
09:19:02  	at m1/p.Main.checkTypeConsistency(Main.java:98)
09:19:02  	at m1/p.Main$Test.verifyAccess(Main.java:66)
09:19:02  	at m1/p.Main.main(Main.java:89)
09:19:02  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:19:02  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
09:19:02  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:19:02  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
09:19:02  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:19:02  	at java.base/java.lang.Thread.run(Thread.java:883)
09:19:02  
09:19:02  JavaTest Message: Test threw exception: java.lang.AssertionError: unexpected result
09:19:02  JavaTest Message: shutting down test
09:19:02  
09:19:02  STATUS:Failed.`main' threw exception: java.lang.AssertionError: unexpected result
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=ibm&BUILD_LIST=openjdk&PLATFORM=s390x_linux&CUSTOM_TARGET=java/lang/invoke/MethodHandles/publicLookup/Driver.java&TARGET=jdk_custom_0)

So this is not OJDK MH specific.

Note: RI passed at `Test_grinder/job/Grinder/17535`.

**Comment by pshipton** [comment]
The test is still excluded on jdk16, which is out of support, but not on more recent versions.
