### ISSUE TITLE
JDK11 java/lang/ProcessBuilder/Basic.java#id1 - AssertionError: Some tests failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#10921]
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/526`
```
22:27:00  openjdk version "11.0.9-internal" 2020-10-20
22:27:00  OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.jenkins.BuildJDK11ppc64lelinuxNightly)
22:27:00  Eclipse OpenJ9 VM (build master-e5e0324a0f5, JRE 11 Linux ppc64le-64-Bit Compressed References 20201017_598 (JIT enabled, AOT enabled)
22:27:00  OpenJ9   - e5e0324a0f5
22:27:00  OMR      - d2cc022b7d9
22:27:00  JCL      - 5e617ab0c87 based on jdk-11.0.9+10)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
22:59:23  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64le_linux&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:32:54  --------------------------------------------------
22:32:54  TEST: java/lang/ProcessBuilder/Basic.java#id1
22:32:54  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image
22:32:54  
22:32:54  STDERR:
22:32:54  java.lang.Throwable
22:32:54  	at java.base/java.lang.Thread.dumpStack(Thread.java:510)
22:32:54  	at Basic.fail(Basic.java:2747)
22:32:54  	at Basic.check(Basic.java:2750)
22:32:54  	at Basic.realMain(Basic.java:1794)
22:32:54  	at Basic.main(Basic.java:2757)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:32:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:32:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:32:54  	at java.base/java.lang.Thread.run(Thread.java:835)
22:32:54  java.lang.Throwable
22:32:54  	at java.base/java.lang.Thread.dumpStack(Thread.java:510)
22:32:54  	at Basic.fail(Basic.java:2747)
22:32:54  	at Basic.check(Basic.java:2750)
22:32:54  	at Basic.realMain(Basic.java:1795)
22:32:54  	at Basic.main(Basic.java:2757)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:32:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:32:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:32:54  	at java.base/java.lang.Thread.run(Thread.java:835)
22:32:54  java.lang.Throwable
22:32:54  	at java.base/java.lang.Thread.dumpStack(Thread.java:510)
22:32:54  	at Basic.fail(Basic.java:2747)
22:32:54  	at Basic.check(Basic.java:2750)
22:32:54  	at Basic.realMain(Basic.java:1796)
22:32:54  	at Basic.main(Basic.java:2757)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:32:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:32:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:32:54  	at java.base/java.lang.Thread.run(Thread.java:835)
22:32:54  >'0'< not equal to '1'
22:32:54  java.lang.Throwable
22:32:54  	at java.base/java.lang.Thread.dumpStack(Thread.java:510)
22:32:54  	at Basic.fail(Basic.java:2747)
22:32:54  	at Basic.fail(Basic.java:2748)
22:32:54  	at Basic.equal(Basic.java:2754)
22:32:54  	at Basic.realMain(Basic.java:1797)
22:32:54  	at Basic.main(Basic.java:2757)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:32:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:32:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:32:54  	at java.base/java.lang.Thread.run(Thread.java:835)
22:32:54  java.lang.AssertionError: Some tests failed
22:32:54  	at Basic.main(Basic.java:2759)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:32:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:32:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:32:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:32:54  	at java.base/java.lang.Thread.run(Thread.java:835)
22:32:54  
22:32:54  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed

22:40:29  jdk_lang_j9_0_FAILED
```

**Comment by pshipton** [comment]
This looks like the failures we were seeing on Windows when the machines didn't have enough memory / swap space.

**Comment by llxia** [comment]
java/lang/ProcessBuilder/Basic.java passed on JDK11 in the recent runs. We will re-include the test.

https://github.com/adoptium/aqa-tests/pull/5940
https://github.com/adoptium/aqa-tests/pull/5941
https://github.com/adoptium/aqa-tests/pull/5903

**Comment by llxia** [comment]
Close this issue as the test is re-enabled.
