### ISSUE TITLE
JDK11 JIT Server StreamBuilderTest.java - Segmentation error vmState=0x00000000 at libj9jit29.so

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#11185]
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/232`:
```
22:29:26  openjdk version "11.0.10-internal" 2021-01-19
22:29:26  OpenJDK Runtime Environment (build 11.0.10-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxjitNightly)
22:29:26  Eclipse OpenJ9 VM (build master-7cf2cc92535, JRE 11 Linux amd64-64-Bit Compressed References 20201112_240 (JIT enabled, AOT enabled)
22:29:26  OpenJ9   - 7cf2cc92535
22:29:26  OMR      - 89d6d5aaadc
22:29:26  JCL      - 6513c6a9c01 based on jdk-11.0.10+2)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:19:25  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&TARGET=jdk_util_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:10:13  --------------------------------------------------
23:10:13  TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/StreamBuilderTest.java
23:10:13  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image
23:10:13  
23:10:13  STDERR:
23:10:13  JITServer is currently a technology preview. Its use is not yet supported
23:10:13  Unhandled exception
23:10:13  Type=Segmentation error vmState=0x00000000
23:10:13  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
23:10:13  Handler1=00007F0CBC4E9C00 Handler2=00007F0CBC24F990 InaccessibleAddress=0000000000000318
23:10:13  RDI=00007F0C96D0ADDB RSI=00007F0C96D0ADE0 RAX=00000000000000A0 RBX=00000000FFA40290
23:10:13  RCX=0000000000000100 RDX=00007F0C96D0ADE0 R8=0000000000000001 R9=00000000FFA401C0
23:10:13  R10=0000000000000001 R11=0000000000000000 R12=00000000E00CC888 R13=0000000000000004
23:10:13  R14=00000000FF43A328 R15=00000000FF43A338
23:10:13  RIP=00007F0CB066CDBA GS=0000 FS=0000 RSP=000000000020EDA0
23:10:13  EFlags=0000000000010207 CS=0033 RBP=00000000001BED00 ERR=0000000000000004
23:10:13  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000318
23:10:13  xmm0 000000000028e678 (f: 2680440.000000, d: 1.324313e-317)
23:10:13  xmm1 61636f766e492f74 (f: 1850290048.000000, d: 1.366222e+161)
23:10:13  xmm2 00007f0c9463d7b0 (f: 2489571328.000000, d: 6.901702e-310)
23:10:13  xmm3 000000003a20fe05 (f: 975240704.000000, d: 4.818329e-315)
23:10:13  xmm4 00000000be213350 (f: 3189846784.000000, d: 1.575994e-314)
23:10:13  xmm5 74752f6139477542 (f: 960984384.000000, d: 9.707478e+252)
23:10:13  xmm6 00000000be93dcbf (f: 3197361408.000000, d: 1.579706e-314)
23:10:13  xmm7 6a5f31316b646a6e (f: 1801742976.000000, d: 2.444908e+204)
23:10:13  xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:10:13  xmm9 000000003e17cee7 (f: 1041747712.000000, d: 5.146917e-315)
23:10:13  xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:10:13  xmm11 0000ff0000000000 (f: 0.000000, d: 1.385239e-309)
23:10:13  xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:10:13  xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:10:13  xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:10:13  xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:10:13  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so
23:10:13  Module_base_address=00007F0CB01CB000
23:10:13  Target=2_90_20201112_240 (Linux 3.10.0-1160.2.2.el7.x86_64)
23:10:13  CPU=amd64 (4 logical CPUs) (0x1e8d10000 RAM)
23:10:13  ----------- Stack Backtrace -----------
23:10:13  (0x00007F0CBC24C3C2 [libj9prt29.so+0x263c2])
23:10:13  (0x00007F0CBC2506F3 [libj9prt29.so+0x2a6f3])
23:10:13  (0x00007F0CBC24C43E [libj9prt29.so+0x2643e])
23:10:13  (0x00007F0CBC24C534 [libj9prt29.so+0x26534])
23:10:13  (0x00007F0CBC2506F3 [libj9prt29.so+0x2a6f3])
23:10:13  (0x00007F0CBC24C29B [libj9prt29.so+0x2629b])
23:10:13  (0x00007F0CBC4E9744 [libj9vm29.so+0x37744])
23:10:13  (0x00007F0CBC2506F3 [libj9prt29.so+0x2a6f3])
23:10:13  (0x00007F0CBC4E99B5 [libj9vm29.so+0x379b5])
23:10:13  (0x00007F0CBC588E95 [libj9vm29.so+0xd6e95])
23:10:13  ---------------------------------------
23:10:13  JVMDUMP039I Processing dump event "gpf", detail "" at 2020/11/12 20:10:04 - please wait.
23:10:13  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_1605238328650/jdk_util_j9_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/StreamBuilderTest/core.20201112.201004.24295.0001.dmp' in response to an event
23:10:13  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_1605238328650/jdk_util_j9_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/StreamBuilderTest/core.20201112.201004.24295.0001.dmp
23:10:13  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_1605238328650/jdk_util_j9_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/StreamBuilderTest/javacore.20201112.201004.24295.0002.txt' in response to an event
```

**Comment by pshipton** [comment]
@mpirvu

**Comment by dmitry-ten** [comment]
`_j9` tests have been consolidated with non-j9 tests, so there is `jdk_util_0` test now.
I reran the test in [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/15251/) and the crashes still happen, although the vmState is different from the original crash. 
```
[2021-05-04T16:06:45.941Z] Type=Segmentation error vmState=0x00020011
[2021-05-04T16:06:45.941Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2021-05-04T16:06:45.942Z] Handler1=00007FB4309D75B0 Handler2=00007FB430736A70 InaccessibleAddress=0000000000000010
[2021-05-04T16:06:45.942Z] RDI=0000000000000020 RSI=0000000000000001 RAX=0000000000000000 RBX=00007FB3E91F95D0
[2021-05-04T16:06:45.942Z] RCX=00007FB42C05F060 RDX=0000000000000000 R8=0000000000000001 R9=0000000000000000
[2021-05-04T16:06:45.942Z] R10=0000000000000008 R11=0000000000000000 R12=0000000000000001 R13=0000000000000000
[2021-05-04T16:06:45.942Z] R14=0000000000000000 R15=00007FB42C0162C8
[2021-05-04T16:06:45.942Z] RIP=00007FB424A46685 GS=0000 FS=0000 RSP=00007FB3E958AA20
[2021-05-04T16:06:45.942Z] EFlags=0000000000010246 CS=0033 RBP=00007FB3E8FA12B8 ERR=0000000000000004
[2021-05-04T16:06:45.942Z] TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000010
[2021-05-04T16:06:45.942Z] xmm0 00000000ffff0000 (f: 4294901760.000000, d: 2.121963e-314)
[2021-05-04T16:06:45.942Z] xmm1 5754494a00005e60 (f: 24160.000000, d: 4.878664e+112)
[2021-05-04T16:06:45.942Z] xmm2 ffffffff00000000 (f: 0.000000, d: -nan)
[2021-05-04T16:06:45.942Z] xmm3 4a5f646c6975422f (f: 1769292288.000000, d: 1.835195e+50)
[2021-05-04T16:06:45.942Z] xmm4 756e696c5f34362d (f: 1597257216.000000, d: 4.566343e+257)
[2021-05-04T16:06:45.942Z] xmm5 6f2f6c616e6f7372 (f: 1852797824.000000, d: 3.722026e+227)
[2021-05-04T16:06:45.942Z] xmm6 706f2f6c616e6f73 (f: 1634627456.000000, d: 3.873253e+233)
[2021-05-04T16:06:45.942Z] xmm7 0000000042c408ae (f: 1120143488.000000, d: 5.534244e-315)
[2021-05-04T16:06:45.942Z] xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-05-04T16:06:45.942Z] xmm9 000000003e17cee7 (f: 1041747712.000000, d: 5.146917e-315)
[2021-05-04T16:06:45.942Z] xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-05-04T16:06:45.942Z] xmm11 0000ff0000000000 (f: 0.000000, d: 1.385239e-309)
[2021-05-04T16:06:45.942Z] xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-05-04T16:06:45.942Z] xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-05-04T16:06:45.942Z] xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-05-04T16:06:45.942Z] xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-05-04T16:06:45.942Z] Module=/home/jenkins/workspace/Grinder_iteration_9/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so
[2021-05-04T16:06:45.942Z] Module_base_address=00007FB42460C000
[2021-05-04T16:06:45.942Z] Target=2_90_20210504_708 (Linux 3.10.0-1160.21.1.el7.x86_64)
[2021-05-04T16:06:45.942Z] CPU=amd64 (4 logical CPUs) (0x1e8d0b000 RAM)
[2021-05-04T16:06:45.942Z] ----------- Stack Backtrace -----------
[2021-05-04T16:06:45.942Z] (0x00007FB424A46685 [libj9jit29.so+0x43a685])
[2021-05-04T16:06:45.942Z] (0x00007FB424A4CBBE [libj9jit29.so+0x440bbe])
[2021-05-04T16:06:45.942Z] (0x00007FB424A4CCE4 [libj9jit29.so+0x440ce4])
[2021-05-04T16:06:45.942Z] (0x00007FB42478C60B [libj9jit29.so+0x18060b])
[2021-05-04T16:06:45.942Z] (0x00007FB4302ED3BE [libj9hookable29.so+0x13be])
[2021-05-04T16:06:45.942Z] (0x00007FB4309EB8A6 [libj9vm29.so+0x528a6])
[2021-05-04T16:06:45.942Z] (0x00007FB424330964 [libj9gc29.so+0x208964])
[2021-05-04T16:06:45.942Z] (0x00007FB4242D52F3 [libj9gc29.so+0x1ad2f3])
[2021-05-04T16:06:45.942Z] (0x00007FB4242D545E [libj9gc29.so+0x1ad45e])
[2021-05-04T16:06:45.942Z] (0x00007FB42427231B [libj9gc29.so+0x14a31b])
[2021-05-04T16:06:45.942Z] (0x00007FB42430AD56 [libj9gc29.so+0x1e2d56])
[2021-05-04T16:06:45.942Z] (0x00007FB424239856 [libj9gc29.so+0x111856])
[2021-05-04T16:06:45.942Z] (0x00007FB42431D8F9 [libj9gc29.so+0x1f58f9])
[2021-05-04T16:06:45.942Z] (0x00007FB4242FC79B [libj9gc29.so+0x1d479b])
[2021-05-04T16:06:45.942Z] (0x00007FB42425CDA6 [libj9gc29.so+0x134da6])
[2021-05-04T16:06:45.942Z] (0x00007FB42426281B [libj9gc29.so+0x13a81b])
[2021-05-04T16:06:45.942Z] (0x00007FB42416F1A9 [libj9gc29.so+0x471a9])
[2021-05-04T16:06:45.942Z] (0x00007FB4241660EC [libj9gc29.so+0x3e0ec])
[2021-05-04T16:06:45.942Z] (0x00007FB430A09A93 [libj9vm29.so+0x70a93])
[2021-05-04T16:06:45.942Z] (0x00007FB430A42AEE [libj9vm29.so+0xa9aee])
[2021-05-04T16:06:45.942Z] (0x00007FB430A285F5 [libj9vm29.so+0x8f5f5])
[2021-05-04T16:06:45.942Z] (0x00007FB430AD39B2 [libj9vm29.so+0x13a9b2])
[2021-05-04T16:06:45.942Z] ---------------------------------------
[2021-05-04T16:06:45.942Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2021/05/04 08:45:28 - please wait.
[2021-05-04T16:06:45.942Z] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder_iteration_9/openjdk-tests/TKG/output_16201419225320/jdk_util_0/work/scratch/0/core.20210504.084528.1781.0001.dmp' in response to an event
[2021-05-04T16:06:45.942Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Grinder_iteration_9/openjdk-tests/TKG/output_16201419225320/jdk_util_0/work/scratch/0/core.20210504.084528.1781.0001.dmp
[2021-05-04T16:06:45.942Z] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder_iteration_9/openjdk-tests/TKG/output_16201419225320/jdk_util_0/work/scratch/0/javacore.20210504.084528.1781.0002.txt' in response to an event
[2021-05-04T16:06:45.942Z] JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder_iteration_9/openjdk-tests/TKG/output_16201419225320/jdk_util_0/work/scratch/0/javacore.20210504.084528.1781.0002.txt
[2021-05-04T16:06:45.942Z] JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Grinder_iteration_9/openjdk-tests/TKG/output_16201419225320/jdk_util_0/work/scratch/0/Snap.20210504.084528.1781.0003.trc' in response to an event
[2021-05-04T16:06:45.942Z] JVMDUMP010I Snap dump written to /home/jenkins/workspace/Grinder_iteration_9/openjdk-tests/TKG/output_16201419225320/jdk_util_0/work/scratch/0/Snap.20210504.084528.1781.0003.trc
[2021-05-04T16:06:45.942Z] JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Grinder_iteration_9/openjdk-tests/TKG/output_16201419225320/jdk_util_0/work/scratch/0/jitdump.20210504.084528.1781.0004.dmp' in response to an event
[2021-05-04T16:06:45.942Z] JVMDUMP051I JIT dump occurred in 'AgentVMThread' thread 0x0000000000334600
[2021-05-04T16:06:45.942Z] JVMDUMP053I JIT dump is recompiling sun/util/resources/OpenListResourceBundle.loadLookup()V
```

**Comment by dmitry-ten** [comment]
I was able to reproduce locally.
Here is the stack trace of the crash (which happens on the client):
```
#12 <signal handler called>
#13 0x00007f999f6265c5 in TR_RuntimeAssumptionTable::markAssumptionsAndDetach (this=0x7f99a00c9d10, md=md@entry=0x7f994869e778,
    reclaimPrePrologueAssumptions=<optimized out>) at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/compiler/runtime/ClassUnloadAssumption.cpp:487
#14 0x00007f999f62cb6e in (anonymous namespace)::markAssumptionsAndDetach (reclaimPrePrologueAssumptions=true, metaData=0x7f994869e778,
    jitConfig=0x7f99a00c66f0) at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/compiler/runtime/HookHelpers.cpp:122
#15 jitReleaseCodeCollectMetaData (jitConfig=0x7f99a00c66f0, vmThread=vmThread@entry=0x1ac600, metaData=0x7f994869e778,
    faintCacheBlock=faintCacheBlock@entry=0x0) at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/compiler/runtime/HookHelpers.cpp:299
#16 0x00007f999f62cc94 in jitRemoveAllMetaDataForClassLoader (vmThread=vmThread@entry=0x1ac600, classLoader=classLoader@entry=0x7f99a0681148)
    at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/compiler/runtime/HookHelpers.cpp:414
#17 0x00007f999f369edb in jitHookClassLoaderUnload (hookInterface=hookInterface@entry=0x7f99a0013d58, eventNum=eventNum@entry=68,
---Type <return> to continue, or q <return> to quit---
    eventData=eventData@entry=0x7f9981c41080, userData=userData@entry=0x0)
    at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/compiler/control/HookedByTheJit.cpp:2137
#18 0x00007f99a5d5736e in J9HookDispatch (hookInterface=0x7f99a0013d58, taggedEventNum=<optimized out>, eventData=0x7f9981c41080)
    at /root/src-11/openj9-openjdk-jdk11/omr/util/hookable/hookable.cpp:235
#19 0x00007f99a61c9556 in cleanUpClassLoader (vmThread=0x1ac600, classLoader=0x7f99a0681148)
    at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/vm/jvmfree.c:363
#20 0x00007f99a429ff44 in MM_ClassLoaderManager::cleanUpClassLoaders (this=0x7f99a004d350, env=env@entry=0x7f9938001cc8,
    classLoadersUnloadedList=0x7f99a0681048, classLoadersUnloadedList@entry=0x7f99a009b008, reclaimedSegments=reclaimedSegments@entry=0x7f9981c41158,
    unloadLink=unloadLink@entry=0x7f9981c41150, finalizationRequired=finalizationRequired@entry=0x7f99a0049478)
    at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/gc_base/ClassLoaderManager.cpp:593
#21 0x00007f99a42443e3 in MM_GlobalCollectorDelegate::unloadDeadClassLoaders (this=this@entry=0x7f99a0049450, env=env@entry=0x7f9938001cc8)
    at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/gc_glue_java/GlobalCollectorDelegate.cpp:466
#22 0x00007f99a424454e in MM_GlobalCollectorDelegate::postMarkProcessing (this=this@entry=0x7f99a0049450, env=env@entry=0x7f9938001cc8)
    at /root/src-11/openj9-openjdk-jdk11/openj9/runtime/gc_glue_java/GlobalCollectorDelegate.cpp:256
#23 0x00007f99a41e128b in MM_ParallelGlobalGC::mainThreadGarbageCollect (this=0x7f99a0049410, env=0x7f9938001cc8, allocDescription=0x0,
    initMarkMap=<optimized out>, rebuildMarkBits=<optimized out>) at /root/src-11/openj9-openjdk-jdk11/omr/gc/base/standard/ParallelGlobalGC.cpp:463
#24 0x00007f99a4279f86 in MM_ConcurrentGC::internalGarbageCollect (this=<optimized out>, env=0x7f9938001cc8, subSpace=<optimized out>,
    allocDescription=<optimized out>) at /root/src-11/openj9-openjdk-jdk11/omr/gc/base/standard/ConcurrentGC.cpp:3151
#25 0x00007f99a41a87a6 in MM_Collector::garbageCollect (this=0x7f99a0049410, env=0x7f9938001cc8, callingSubSpace=0x7f99a0094480,
    allocateDescription=0x0, gcCode=<optimized out>, objectAllocationInterface=0x0, baseSubSpace=0x0, context=0x0)
    at /root/src-11/openj9-openjdk-jdk11/omr/gc/base/Collector.cpp:500
#26 0x00007f99a42803aa in MM_ConcurrentGC::concurrentFinalCollection (this=0x7f99a0049410, env=0x7f9938001cc8, subSpace=0x7f99a0094480)
    at /root/src-11/openj9-openjdk-jdk11/omr/gc/base/standard/ConcurrentGC.cpp:2793
#27 0x00007f99a4282417 in MM_ConcurrentGC::concurrentMark (this=this@entry=0x7f99a0049410, env=env@entry=0x7f9938001cc8,
    subspace=subspace@entry=0x7f99a0094480, allocDescription=allocDescription@entry=0x7f9981c414f8)
    at /root/src-11/openj9-openjdk-jdk11/omr/gc/base/standard/ConcurrentGC.cpp:2176
-----------
```

So the issues is triggered by a class loader unload event, with the crash happening when runtime assumptions are being detached from their list. The assumptions are received by the client at the end of the remote compilation, deserialized and added to the list. Need to look for potential issues there.

**Comment by mpirvu** [comment]
@dmitry-ten I vaguely recall that recently we had a fix for a problem related to runtime assumptions. Would that fix address this issue as well?

**Comment by dmitry-ten** [comment]
#12966 and #12840 fixed runtime assumption bugs, however they didn't fix the original crash.
Over the last couple of days I grinded this test with #13209 applied, after 300 iterations, I saw no failures.
I'm running another 100 iterations today, if they pass, I say this issue should be considered resolved.

**Comment by dmitry-ten** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/17063/ - the Grinder passed, which brings us to 400 iterations without failures.
@mpirvu I think you can close this one.

**Comment by mpirvu** [comment]
Closing based on the comment above
