### ISSUE TITLE
JDK16 InternalError: Compile stub invoked! at java.base/java.lang.invoke.VarHandle.withInvokeBehavior(VarHandle.java:1675)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#11256]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/278`:
```
23:15:12  openjdk version "16-internal" 2021-03-16
23:15:12  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextppc64aixNightly)
23:15:12  Eclipse OpenJ9 VM (build master-a3c957cf411, JRE 16 AIX ppc64-64-Bit Compressed References 20201123_394 (JIT enabled, AOT enabled)
23:15:12  OpenJ9   - a3c957cf411
23:15:12  OMR      - f7190801d16
23:15:12  JCL      - 30a060cd4a7 based on jdk-16+25)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
00:54:12  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
23:31:52  STDOUT:
23:31:52  [TestNG] Running:
23:31:52    java/lang/invoke/VarHandles/VarHandleTestExact.java
23:31:52  
23:31:52  test VarHandleTestExact.testExactArraySet(class [Ljava.lang.Object;, "abcd", VarHandleTestExact$$Lambda$25/0x000000002282bb88@1045bd75): failure
23:31:52  java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
23:31:52  	at java.base/java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(OpenJDKCompileStub.java:38)
23:31:52  	at java.base/java.lang.invoke.VarHandle.withInvokeBehavior(VarHandle.java:1675)
23:31:52  	at VarHandleTestExact.doTest(VarHandleTestExact.java:185)
23:31:52  	at VarHandleTestExact.testExactArraySet(VarHandleTestExact.java:153)
23:31:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:31:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
23:31:52  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:31:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
23:31:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
23:31:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
23:31:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
23:31:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
23:31:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
23:31:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
23:31:52  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
23:31:52  	at org.testng.TestRunner.run(TestRunner.java:623)
23:31:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
23:31:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
23:31:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
23:31:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
23:31:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
23:31:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
23:31:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
23:31:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
23:31:52  	at org.testng.TestNG.run(TestNG.java:1018)
23:31:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
23:31:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
23:31:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:31:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
23:31:52  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:31:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
23:31:52  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:31:52  	at java.base/java.lang.Thread.run(Thread.java:853)

23:31:52  ===============================================
23:31:52  java/lang/invoke/VarHandles/VarHandleTestExact.java
23:31:52  Total tests run: 122, Failures: 98, Skips: 24
23:31:52  ===============================================
```

**Comment by DanHeidinga** [comment]
fyi @babsingh

**Comment by babsingh** [comment]
This is a JDK16 failure. We plan to enable OpenJDK VarHandles for JDK16. Planning to address this issue by transitioning to OpenJDK VarHandles.

**Comment by babsingh** [comment]
This issue should be tracked with the `project:MH` tag.

**Comment by JasonFengJ9** [comment]
This test `java/lang/invoke/VarHandles/VarHandleTestExact.java` has been excluded via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2088.

**Comment by babsingh** [comment]
Confirming that the reported failure is fixed once OJDK MHs are enabled in OpenJ9. Once OJDK MHs are officially enabled in OpenJ9, `VarHandleTestExact.java` should be enabled by removing the following lines:
- https://github.com/AdoptOpenJDK/openjdk-tests/blob/b3664d86df56cdcf3760d3b40613e7abc2a36152/openjdk/ProblemList_openjdk16-openj9.txt#L156
- https://github.com/AdoptOpenJDK/openjdk-tests/blob/b3664d86df56cdcf3760d3b40613e7abc2a36152/openjdk/ProblemList_openjdk17-openj9.txt#L162

**Comment by JasonFengJ9** [comment]
Verified that this test passes w/ a recent JDK16 build at `Test_grinder/job/Grinder/17536`
```
09:10:10  openjdk version "16.0.2-internal" 2021-07-20
09:10:10  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16s390xlinuxPersonal)
09:10:10  Eclipse OpenJ9 VM (build master-b49892b0b23, JRE 16 Linux s390x-64-Bit Compressed References 20210813_50 (JIT enabled, AOT enabled)
09:10:10  OpenJ9   - b49892b0b23
09:10:10  OMR      - ac3ab4821a5
09:10:10  JCL      - 44316ee515b based on jdk-16.0.2+7)
```

Created a PR (https://github.com/adoptium/aqa-tests/pull/2819) to re-enable the test.

closing..
