### ISSUE TITLE
jvmnativestest_0 nanotime is not similar to millitime

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#11293]
Machine problem?

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly/560
jvmnativestest_0
ub18-390-2
```
===============================================
Running test jvmnativestest_0 ...
===============================================
jvmnativestest_0 Start Time: Fri Nov 27 02:06:25 2020 Epoch Time (ms): 1606460785717
variation: NoOptions
JVM_OPTIONS:  
..F.......
Time: 0.031
There was 1 failure:
1) test_EnsureWallClockTime(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)junit.framework.AssertionFailedError: nanotime is not similar to millitime
	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_EnsureWallClockTime(GetNanoTimeAdjustment.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)

FAILURES!!!
Tests run: 9,  Failures: 1,  Errors: 0
```

**Comment by keithc-ca** [comment]
I saw another instance of this failure in https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Personal/44/ - I think the problem is with the test. It's possible that 
```
SupportJVM.GetNanoTimeAdjustment(0)
System.currentTimeMillis()
```
happen before and after the minutes change.

**Comment by keithc-ca** [comment]
To confirm my theory, I used this code:
```
    public static void main(String[] args) {
        long start = System.currentTimeMillis();

        for (;;) {
            String nanoTime = Long.toString(SupportJVM.GetNanoTimeAdjustment(0));
            String millisTime = Long.toString(System.currentTimeMillis());
            String seconds = millisTime.substring(0, millisTime.length() - 3);
            long elapsed = System.currentTimeMillis() - start;

            if (!nanoTime.contains(seconds)) {
                System.out.format("after %d: nanotime(%s) is not similar to millitime (%s)%n", //
                        elapsed, nanoTime, millisTime);
                System.exit(1);

                // nanotime(1636558930.999999731) is not similar to millitime (1636558931)
            } else if (elapsed > 120_000) {
                // quit after two minutes
                break;
            }
        }
    }
```
You don't need to wait long for failures:
```
after 239: nanotime(1636559151999999932) is not similar to millitime (1636559152000)
after 1492: nanotime(1636559255999999955) is not similar to millitime (1636559256000)
after 954: nanotime(1636559269999999853) is not similar to millitime (1636559270000)
```

**Comment by pshipton** [comment]
Reopen since https://github.com/eclipse-openj9/openj9/pull/13896 was reverted.

**Comment by keithc-ca** [comment]
The failure on zlinux suggests a VM problem:
```
1) test_EnsureWallClockTime(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)junit.framework.AssertionFailedError: nanotime(1636591271095538473) is not similar to millitime(1636591271094..1636591271094)
```
nanoseconds are 1.5 milliseconds ahead.

**Comment by pshipton** [comment]
We might need some synchronization or memory barrier in the test to ensure the processor can't reorder the operations.
