### ISSUE TITLE
TestJps_SE80_0 testComposedArguments Missing argument: foo

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#11509]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_0/195
TestJps_SE80_0
win2012-x86-6
```
[2020-12-17T05:35:44.643Z] PASSED: testApplicationArguments
[2020-12-17T05:35:44.643Z] PASSED: testJpsIdOnly
[2020-12-17T05:35:44.643Z] PASSED: testJpsPackageName
[2020-12-17T05:35:44.643Z] PASSED: testJpsSanity
[2020-12-17T05:35:44.643Z] PASSED: testJvmArguments
[2020-12-17T05:35:44.643Z] FAILED: testComposedArguments
[2020-12-17T05:35:44.643Z] java.lang.AssertionError: Missing argument: foo
[2020-12-17T05:35:44.643Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2020-12-17T05:35:44.643Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2020-12-17T05:35:44.643Z] 	at org.openj9.test.attachAPI.TestJps.testComposedArguments(TestJps.java:134)
[2020-12-17T05:35:44.643Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-12-17T05:35:44.643Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-12-17T05:35:44.643Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-12-17T05:35:44.643Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-12-17T05:35:44.643Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2020-12-17T05:35:44.643Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2020-12-17T05:35:44.643Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2020-12-17T05:35:44.643Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2020-12-17T05:35:44.643Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2020-12-17T05:35:44.643Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2020-12-17T05:35:44.643Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2020-12-17T05:35:44.643Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2020-12-17T05:35:44.643Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2020-12-17T05:35:44.643Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2020-12-17T05:35:44.643Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2020-12-17T05:35:44.643Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2020-12-17T05:35:44.643Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2020-12-17T05:35:44.643Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2020-12-17T05:35:44.643Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2020-12-17T05:35:44.643Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2020-12-17T05:35:44.644Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2020-12-17T05:35:44.644Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2020-12-17T05:35:44.644Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2020-12-17T05:35:44.644Z] 	at org.testng.TestNG.main(TestNG.java:1323)

```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/583
TestJps_0
```
FAILED: testComposedArguments
java.lang.AssertionError: Missing argument: foo
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.attachAPI.TestJps.testComposedArguments(TestJps.java:134)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_1/219
TestJps_SE80_0
win2012-x86-6
```
[2021-01-12T04:37:08.290Z] FAILED: testJvmArguments
[2021-01-12T04:37:08.290Z] java.lang.AssertionError: Missing argument: -Dfoo=bar
[2021-01-12T04:37:08.290Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2021-01-12T04:37:08.290Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2021-01-12T04:37:08.290Z] 	at org.openj9.test.attachAPI.TestJps.testJvmArguments(TestJps.java:120)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.functional_x86-64_linux_Release/1
TestJps_0
```
FAILED: testComposedArguments
java.lang.AssertionError: Missing argument: foo
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.attachAPI.TestJps.testComposedArguments(TestJps.java:134)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_0/253
TestJps_SE80_0
```
[2021-02-18T05:20:28.016Z] FAILED: testComposedArguments
[2021-02-18T05:20:28.016Z] java.lang.AssertionError: Missing argument: foo
[2021-02-18T05:20:28.016Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2021-02-18T05:20:28.016Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2021-02-18T05:20:28.016Z] 	at org.openj9.test.attachAPI.TestJps.testComposedArguments(TestJps.java:134)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/29
TestJps_0
```
22:29:23  FAILED: testComposedArguments
22:29:23  java.lang.AssertionError: Missing argument: foo
22:29:23  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
22:29:23  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
22:29:23  	at org.openj9.test.attachAPI.TestJps.testComposedArguments(TestJps.java:134)
```

**Comment by JasonFengJ9** [comment]
Observed at `job/Test_openjdk11_j9_extended.functional_x86-64_windows_testList_0/84/testReport/`
```
[2021-10-14T23:34:00.851Z] Running test TestJps_0 ...
[2021-10-14T23:34:00.851Z] ===============================================
[2021-10-14T23:34:00.851Z] TestJps_0 Start Time: Thu Oct 14 16:34:00 2021 Epoch Time (ms): 1634254440556
[2021-10-14T23:34:00.851Z] "C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_windows_testList_0/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_windows_testList_0/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-10-14T23:34:02.617Z] JVMSHRC005I No shared class caches available
[2021-10-14T23:34:02.617Z] JVMSHRC005I No shared class caches available
[2021-10-14T23:34:02.617Z] cache cleanup done
[2021-10-14T23:34:02.617Z] variation: NoOptions
[2021-10-14T23:34:04.320Z] JVM_OPTIONS:  

[2021-10-14T23:34:40.467Z] FAILED: testComposedArguments
[2021-10-14T23:34:40.467Z] java.lang.AssertionError: Missing argument: foo
[2021-10-14T23:34:40.467Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2021-10-14T23:34:40.467Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2021-10-14T23:34:40.467Z] 	at org.openj9.test.attachAPI.TestJps.testComposedArguments(TestJps.java:134)
[2021-10-14T23:34:40.467Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-14T23:34:40.467Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-10-14T23:34:40.467Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-14T23:34:40.467Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-10-14T23:34:40.467Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2021-10-14T23:34:40.467Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2021-10-14T23:34:40.467Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2021-10-14T23:34:40.467Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2021-10-14T23:34:40.467Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-10-14T23:34:40.467Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2021-10-14T23:34:40.467Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2021-10-14T23:34:40.467Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2021-10-14T23:34:40.467Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2021-10-14T23:34:40.467Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2021-10-14T23:34:40.467Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-10-14T23:34:40.467Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2021-10-14T23:34:40.467Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2021-10-14T23:34:40.468Z] 
[2021-10-14T23:34:40.468Z] 
[2021-10-14T23:34:40.468Z] ===============================================
[2021-10-14T23:34:40.468Z]     TestJps
[2021-10-14T23:34:40.468Z]     Tests run: 6, Failures: 1, Skips: 0
[2021-10-14T23:34:40.468Z] ===============================================
[2021-10-14T23:34:40.468Z] 
[2021-10-14T23:34:40.468Z] 
[2021-10-14T23:34:40.468Z] TestJps_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_windows_aot_Personal_testList_0/19
TestJps_0 ITER_1 `-Xshareclasses:name=TestJps_0 -Xscmx400M -Xscmaxaot256m`
```
08:19:58  FAILED: testApplicationArguments
08:19:58  java.lang.AssertionError: Missing argument: foo
08:19:58  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
08:19:58  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
08:19:58  	at org.openj9.test.attachAPI.TestJps.testApplicationArguments(TestJps.java:106)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Release_testList_1/27
TestJps_SE80_0
```
FAILED: testComposedArguments
java.lang.AssertionError: Missing argument: foo
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.attachAPI.TestJps.testComposedArguments(TestJps.java:134)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_s390x_linux_Nightly_testList_0/41
TestJps_0 
```
FAILED: testApplicationArguments
java.lang.AssertionError: Missing argument: foo
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.attachAPI.TestJps.testApplicationArguments(TestJps.java:106)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly_testList_1/435/
TestJps_0
```
[2023-02-02T07:14:01.017Z] FAILED: testApplicationArguments
[2023-02-02T07:14:01.017Z] java.lang.AssertionError: Missing argument: foo
[2023-02-02T07:14:01.017Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2023-02-02T07:14:01.017Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2023-02-02T07:14:01.017Z] 	at org.openj9.test.attachAPI.TestJps.testApplicationArguments(TestJps.java:106)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_1/450
TestJps_SE80_0 
```
01:12:44  FAILED: testApplicationArguments
01:12:44  java.lang.AssertionError: Missing argument: foo
01:12:44  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
01:12:44  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
01:12:44  	at org.openj9.test.attachAPI.TestJps.testApplicationArguments(TestJps.java:106)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/426
TestJps_0
```
21:21:15  FAILED: testApplicationArguments
21:21:15  java.lang.AssertionError: Missing argument: foo
21:21:15  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
21:21:15  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
21:21:15  	at org.openj9.test.attachAPI.TestJps.testApplicationArguments(TestJps.java:106)
```

**Comment by JasonFengJ9** [comment]
```
21:18:58  [TargetManager] [INFO] TargetVM output: pid=560

21:19:24  [AttachApiTest] [INFO] 3560 Jps -m
21:19:24  3828 TestNG -d C:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/aqa-tests/\TKG\output_16771152846302\TestJps_0 C:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/aqa-tests///..//jvmtest\functional\Java8andUp\testng.xml -testnames TestJps -groups level.extended -excludegroups d.*.win_x86-64,d.*.arch.x86,d.*.os.win,d.*.bits.64,d.*.generic-all
21:19:24  560 TargetVM foo bar
```

`3560` was found before `560`.
