### ISSUE TITLE
Can not load Minecraft Cardbaord mod

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#11671]
Java -version output
--------------------
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Windows 7 amd64-64-Bit Compre
sed References 20201022_871 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10)
```

Summary of problem
------------------
[Cardbaord](https://github.com/CardboardPowered/cardboard) is a fabric mod that can load bukkit plugins at fabric server.  When I try running this mod on openj9 ,the server was crash and print log like this:   
```
[00:33:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:147) ~[?:1.8.0
_272]
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.jav
a:136) ~[?:1.8.0_272]
        at org.bukkit.craftbukkit.util.CraftMagicNumbers.test(CraftMagicNumbers.
java:183) ~[CardboardMod-1.16.4.jar:?]
        at com.javazilla.bukkitfabric.MakeMaterial.make(MakeMaterial.java:97) ~[
CardboardMod-1.16.4.jar:?]
        at net.minecraft.class_3176.handler$zzh000$init(class_3176.java:721) ~[i
ntermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:155) ~[intermedi
ary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.jav
a:645) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.jav
a:257) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer$$Lambda$3434/000000000000000000.
run(Unknown Source) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: enum
ConstantDirectory
        at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:95) ~[Cardb
oardMod-1.16.4.jar:?]
        ... 8 more
Caused by: java.lang.NoSuchFieldException: enumConstantDirectory
        at java.lang.Class.getDeclaredField(Class.java:825) ~[?:1.8.0_272]
        at io.izzel.arclight.api.EnumHelper.<clinit>(EnumHelper.java:90) ~[Cardb
oardMod-1.16.4.jar:?]
        ... 8 more
```
but it can running on hotspot.

Diagnostic files
----------------

[latest.log.gz](https://github.com/eclipse/openj9/files/5824764/latest.log.gz)
[crash-2021-01-17_00.33.26-server.txt.gz](https://github.com/eclipse/openj9/files/5824773/crash-2021-01-17_00.33.26-server.txt.gz)

**Comment by pshipton** [comment]
That's because it's using reflection to reach into implementation details. The code could be updated to understand the OpenJ9 implementation details as well.
