### ISSUE TITLE
Timeout failure in java/util/concurrent/forkjoin/FJExceptionTableLeak

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#11805]
Threads are waiting at `sun.misc.Unsafe.park(Native Method)`.

Failure link
------------

The latest JDK 8 sanity.openjdk test on aarch64
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/170/

Optional info
-------------

- intermittent failure: yes
- regression or new test: regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) : unknown

Failure output (captured from console output)
---------------------------------------------

```
[2021-01-27T19:07:42.287Z] messages:
[2021-01-27T19:07:42.287Z] command: main -Xmx32m FJExceptionTableLeak
[2021-01-27T19:07:42.287Z] reason: User specified action: run main/othervm -Xmx32m FJExceptionTableLeak 
[2021-01-27T19:07:42.287Z] Mode: othervm [/othervm specified]
[2021-01-27T19:07:42.287Z] Timeout information:
[2021-01-27T19:07:42.287Z] Running jcmd on process 41510
[2021-01-27T19:07:42.287Z] Dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/output_16117724382057/jdk_util_0/work/scratch/14/core.20210127.190717.41510.0001.dmp
[2021-01-27T19:07:42.287Z] Running jstack on process 41510
[2021-01-27T19:07:42.287Z] 2021-01-27T19:07:25.735
[2021-01-27T19:07:42.287Z] Virtual machine: 41510 JVM information:
[2021-01-27T19:07:42.287Z] JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20210127_200 (JIT enabled, AOT enabled)
[2021-01-27T19:07:42.287Z] OpenJ9   - 8935eedfd
[2021-01-27T19:07:42.287Z] OMR      - 5ad82738f
[2021-01-27T19:07:42.287Z] JCL      - 122910008b based on jdk8u282-b08
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "main" Id=1 WAITING
[2021-01-27T19:07:42.287Z] 	at java.lang.Object.wait(Native Method)
[2021-01-27T19:07:42.287Z] 	at java.lang.Object.wait(Object.java:218)
[2021-01-27T19:07:42.287Z] 	at java.lang.Thread.join(Thread.java:703)
[2021-01-27T19:07:42.287Z] 	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Compilation Thread-000" Id=2 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Compilation Thread-001 Suspended" Id=3 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Compilation Thread-002 Suspended" Id=4 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Compilation Thread-003 Suspended" Id=5 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Compilation Thread-004 Suspended" Id=6 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Compilation Thread-005 Suspended" Id=7 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Compilation Thread-006 Suspended" Id=8 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT Diagnostic Compilation Thread-007 Suspended" Id=9 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "JIT-SamplerThread" Id=10 TIMED_WAITING
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "IProfiler" Id=11 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "VM Runtime State Listener" Id=12 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "Concurrent Mark Helper" Id=13 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "GC Worker" Id=14 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.287Z] "GC Worker" Id=15 RUNNABLE
[2021-01-27T19:07:42.287Z] 
[2021-01-27T19:07:42.288Z] "GC Worker" Id=16 RUNNABLE
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "GC Worker" Id=17 RUNNABLE
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "GC Worker" Id=18 RUNNABLE
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "GC Worker" Id=19 RUNNABLE
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "GC Worker" Id=20 RUNNABLE
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "Attach API wait loop" Id=23 RUNNABLE
[2021-01-27T19:07:42.288Z] 	at openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
[2021-01-27T19:07:42.288Z] 	at openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:259)
[2021-01-27T19:07:42.288Z] 	at openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
[2021-01-27T19:07:42.288Z] 	at openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "MainThread" Id=25 WAITING
[2021-01-27T19:07:42.288Z] 	at sun.misc.Unsafe.park(Native Method)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:569)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
[2021-01-27T19:07:42.288Z] 	at FJExceptionTableLeak.main(FJExceptionTableLeak.java:67)
[2021-01-27T19:07:42.288Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-01-27T19:07:42.288Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-01-27T19:07:42.288Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-01-27T19:07:42.288Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-01-27T19:07:42.288Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-01-27T19:07:42.288Z] 	at java.lang.Thread.run(Thread.java:823)
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "ForkJoinPool-1-worker-1" Id=26 RUNNABLE
[2021-01-27T19:07:42.288Z] 	at sun.misc.Unsafe.park(Native Method)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.recordExceptionalCompletion(ForkJoinTask.java:464)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.setExceptionalCompletion(ForkJoinTask.java:491)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:291)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "ForkJoinPool-1-worker-2" Id=27 RUNNABLE
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.recordExceptionalCompletion(ForkJoinTask.java:469)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.setExceptionalCompletion(ForkJoinTask.java:491)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:291)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "ForkJoinPool-1-worker-0" Id=29 RUNNABLE
[2021-01-27T19:07:42.288Z] 	at sun.misc.Unsafe.park(Native Method)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "Finalizer thread" Id=30 RUNNABLE
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "ForkJoinPool-1-worker-3" Id=31 WAITING
[2021-01-27T19:07:42.288Z] 	at sun.misc.Unsafe.park(Native Method)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
[2021-01-27T19:07:42.288Z] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "file lock watchdog" Id=33 TIMED_WAITING
[2021-01-27T19:07:42.288Z] 	at java.lang.Object.wait(Native Method)
[2021-01-27T19:07:42.288Z] 	at java.lang.Object.wait(Object.java:218)
[2021-01-27T19:07:42.288Z] 	at java.util.TimerThread.mainLoop(Timer.java:552)
[2021-01-27T19:07:42.288Z] 	at java.util.TimerThread.run(Timer.java:505)
[2021-01-27T19:07:42.288Z] 
[2021-01-27T19:07:42.288Z] "Attachment 37317" Id=34 RUNNABLE
[2021-01-27T19:07:42.288Z] 	at openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
[2021-01-27T19:07:42.289Z] 	at openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
[2021-01-27T19:07:42.289Z] 	at openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$4/0x000000003006e9f0.apply(Unknown Source)
[2021-01-27T19:07:42.289Z] 	at openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
[2021-01-27T19:07:42.289Z] 	at openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:239)
[2021-01-27T19:07:42.289Z] 	at openj9.internal.tools.attach.target.Attachment.run(Attachment.java:150)
```

**Comment by knn-k** [comment]
There is a similar timeout in java/util/jar/JarFile/jarVerification/MultiProviderTest in JDK 11 sanity.openjdk, with many threads waiting at `jdk.internal.misc.Unsafe.park(Native Method)`.
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/374/

```
[2021-01-26T23:41:05.942Z] "Attach API wait loop" prio=10 Id=80 TIMED_WAITING
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.Thread.sleep(Native Method)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.Thread.sleep(Thread.java:966)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/openj9.internal.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:140)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
[2021-01-26T23:41:05.942Z] 
[2021-01-26T23:41:05.942Z] "pool-1-thread-1" prio=5 Id=81 TIMED_WAITING
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.Thread.run(Thread.java:836)
[2021-01-26T23:41:05.942Z] 
[2021-01-26T23:41:05.942Z] "ClassCache Reaper" prio=5 Id=84 WAITING
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.Object.wait(Native Method)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.Object.wait(Object.java:221)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:110)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.io.ClassCache$Reaper.run(ClassCache.java:234)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.lang.Thread.run(Thread.java:836)
[2021-01-26T23:41:05.942Z] 
[2021-01-26T23:41:05.942Z] "ForkJoinPool.commonPool-worker-115" prio=5 Id=120 WAITING
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[2021-01-26T23:41:05.942Z] 
[2021-01-26T23:41:05.942Z] "ForkJoinPool.commonPool-worker-229" prio=5 Id=121 WAITING
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
[2021-01-26T23:41:05.942Z] 	at java.base@11.0.10/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by knn-k** [comment]
Similar timeout in Unsafe.park() in October 2020: #10842

**Comment by knn-k** [comment]
The same timeout happens in https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/172/consoleText .
Build 171 was successful.

**Comment by Akira1Saitoh** [comment]
Looked into a core dump.
`ForkJoinPool-1-worker-2` is waiting to be notified.
> waiting to be notified on: "Thread public flags mutex" with ID 0xffffb83c6e38 owner name: <unowned>

```
> info thread 41816
 process id: 41510
  
 no native threads found with specified id
  
Java threads not associated with known native threads:
  
    name:          ForkJoinPool-1-worker-2
    id:            41816
    Thread object: java/util/concurrent/ForkJoinWorkerThread @ 0xfe022038
    Native info:   !j9vmthread 0x128300  !stack 0x128300
    Daemon:        true
    ID:            27 (0x1b)
    Priority:      5
    Thread.State:  WAITING
    JVMTI state:   ALIVE WAITING WAITING_INDEFINITELY IN_OBJECT_WAIT
      waiting to be notified on: "Thread public flags mutex" with ID 0xffffb83c6e38 owner name: <unowned>
    Java stack frames:
     bp: 0x0000000000128008  method: int java/util/concurrent/ForkJoinTask.recordExceptionalCompletion(Throwable)  sourc
e: ForkJoinTask.java:469
      objects: 0xffb3ec98 0xffb0ce80 0xfe01dc10 0xfe0278e8 0xfe01db80 0xfe01dc10 0xffa2bd10 0xfe0278e8 0xffb3ec98 0xffb0
ce80
     bp: 0x0000000000128038  method: int java/util/concurrent/ForkJoinTask.setExceptionalCompletion(Throwable)  source: 
ForkJoinTask.java:491
      objects: 0xffb3ec98 0xffb0ce80
     bp: 0x0000000000000000  method: int java/util/concurrent/ForkJoinTask.doExec()  source: ForkJoinTask.java:291
      objects: <no objects in this frame>
     bp: 0x00000000001280f8  method: void java/util/concurrent/ForkJoinPool$WorkQueue.runTask(java.util.concurrent.ForkJ
oinTask)  source: ForkJoinPool.java:1056
      objects: 0xffb0ce80 0xfe0220d8 0xffb3ec98 0xffb3ec98 0xffb0ce80
     bp: 0x0000000000128138  method: void java/util/concurrent/ForkJoinPool.runWorker(java.util.concurrent.ForkJoinPool$
WorkQueue)  source: ForkJoinPool.java:1692
      objects: 0xfe0220d8 0xfe0278f8 0xffb0ce80
     bp: 0x0000000000128198  method: void java/util/concurrent/ForkJoinWorkerThread.run()  source: ForkJoinWorkerThread.
java:175
      objects: 0xfe022038

```

`ForkJoinPool-1-worker-1` is waiting for a lock ForkJoinPool-1-worker-2 has.

```
> info thread 41815
 process id: 41510

 no native threads found with specified id

Java threads not associated with known native threads:

    name:          ForkJoinPool-1-worker-1
    id:            41815
    Thread object: java/util/concurrent/ForkJoinWorkerThread @ 0xfe021f18
    Native info:   !j9vmthread 0x125e00  !stack 0x125e00
    Daemon:        true
    ID:            26 (0x1a)
    Priority:      5
    Thread.State:  WAITING 
    JVMTI state:   ALIVE WAITING WAITING_INDEFINITELY PARKED 
      parked on: java/util/concurrent/locks/ReentrantLock$NonfairSync@0xfe0278c8 owner name: "ForkJoinPool-1-worker-2" owner id: 41816
    Java stack frames: 
     bp: 0x0000000000125870  method: void sun/misc/Unsafe.park(boolean, long)  (Native Method)
      objects: <no objects in this frame>
     bp: 0x0000000000000000  method: void java/util/concurrent/locks/LockSupport.park(Object)  source: LockSupport.java:175
      objects: <no objects in this frame>
     bp: 0x0000000000000000  method: boolean java/util/concurrent/locks/AbstractQueuedSynchronizer.parkAndCheckInterrupt()  source: AbstractQueuedSynchronizer.java:836
      objects: <no objects in this frame>
     bp: 0x0000000000000000  method: boolean java/util/concurrent/locks/AbstractQueuedSynchronizer.acquireQueued(java.util.concurrent.locks.AbstractQueuedSynchronizer$Node, int)  source: AbstractQueuedSynchronizer.java:870
      objects: <no objects in this frame>
     bp: 0x0000000000000000  method: void java/util/concurrent/locks/AbstractQueuedSynchronizer.acquire(int)  source: AbstractQueuedSynchronizer.java:1199
      objects: <no objects in this frame>
     bp: 0x0000000000000000  method: void java/util/concurrent/locks/ReentrantLock$NonfairSync.lock()  source: ReentrantLock.java:209
      objects: <no objects in this frame>
     bp: 0x0000000000000000  method: void java/util/concurrent/locks/ReentrantLock.lock()  source: ReentrantLock.java:285 
      objects: <no objects in this frame>
     bp: 0x0000000000125bb8  method: int java/util/concurrent/ForkJoinTask.recordExceptionalCompletion(Throwable)  source: ForkJoinTask.java:461
      objects: 0xffada468 0xffb094f0 0xfe021f18 0xfe01b9d8 0xfe0278c8 0xffada4b0 0xffb0d240 0xfe0278e8 0xfe021f18 0xffada4b0 0xfe0278c8 0xfe01b9d8
     bp: 0x0000000000125be8  method: int java/util/concurrent/ForkJoinTask.setExceptionalCompletion(Throwable)  source: ForkJoinTask.java:491
      objects: 0xffada468 0xffb094f0
     bp: 0x0000000000000000  method: int java/util/concurrent/ForkJoinTask.doExec()  source: ForkJoinTask.java:291
      objects: <no objects in this frame>
     bp: 0x0000000000125ca8  method: void java/util/concurrent/ForkJoinPool$WorkQueue.runTask(java.util.concurrent.ForkJoinTask)  source: ForkJoinPool.java:1056
      objects: 0xffb094f0 0xfe021fb8 0xffada468 0xffada468 0xffb094f0
     bp: 0x0000000000125ce8  method: void java/util/concurrent/ForkJoinPool.runWorker(java.util.concurrent.ForkJoinPool$WorkQueue)  source: ForkJoinPool.java:1692
      objects: 0xfe021fb8 0xfe0278f8 0xffb094f0
     bp: 0x0000000000125d48  method: void java/util/concurrent/ForkJoinWorkerThread.run()  source: ForkJoinWorkerThread.java:175
      objects: 0xfe021f18
```

**Comment by knn-k** [comment]
This failure has not been observed recently.  Closing.
