### ISSUE TITLE
JDK16 : ClassDataTest.java : Incorrect Lookup Access Modes for Hidden Classes

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11817]
### Dependencies to reproduce the error

#11815 and #11816 need to be merged before this error is seen.

### Test source code: ClassDataTest.illegalAccess

https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/aee3e45015987017ba3e0e4aaac41fd3eb8027c8/test/jdk/java/lang/invoke/MethodHandles/classData/ClassDataTest.java#L79-L99

### First failure
```
test ClassDataTest.illegalAccess(java.lang.invoke.MethodHandles$Lookup@2f61e1c0, 31): failure
java.lang.AssertionError: expected [31] but found [15]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at ClassDataTest.illegalAccess(ClassDataTest.java:97)
```

### Second failure
```
test ClassDataTest.illegalAccess(java.lang.invoke.MethodHandles$Lookup@c48b6873, 25): failure
java.lang.AssertionError: expected [25] but found [9]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at ClassDataTest.illegalAccess(ClassDataTest.java:97)
```

### Notes

1. `MethodHandles.privateLookupIn` and `Lookup.in` incorrectly set access modes for hidden classes. For `privateLookupIn`, `targetClassModule` and `accessClassModule` should be the same. But, they are different in case of OpenJ9. The issue with `Lookup.in` still needs to be investigated.
2. The reported errors are fixed when OJDK MHs are enabled in OpenJ9. So, these failures do not need to be fixed for the JDK16 0.25 release.
3. Re-enable `ClassDataTest.java` after enabling OJDK MHs in OpenJ9. So, https://github.com/AdoptOpenJDK/openjdk-tests/blob/b50b19e3edc76b951805b42ca364e178a826dafe/openjdk/ProblemList_openjdk16-openj9.txt#L109 should be removed to re-enable `ClassDataTest.java`.

**Comment by babsingh** [comment]
This issue should be tagged with the `project:MH` label since the failure is fixed by enabling OJDK MHs in OpenJ9.

**Comment by JasonFengJ9** [comment]
Note this error is reproduced against a recent JDK16 build at `Test_grinder/job/Grinder/17544`
```
10:52:19  openjdk version "16.0.2-internal" 2021-07-20
10:52:19  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16x86-64linuxPersonal)
10:52:19  Eclipse OpenJ9 VM (build master-b49892b0b23, JRE 16 Linux amd64-64-Bit Compressed References 20210813_281 (JIT enabled, AOT enabled)
10:52:19  OpenJ9   - b49892b0b23
10:52:19  OMR      - ac3ab4821a5
10:52:19  JCL      - 44316ee515b based on jdk-16.0.2+7)

10:54:20  --------------------------------------------------
10:54:20  TEST: java/lang/invoke/MethodHandles/classData/ClassDataTest.java

10:54:20  STDOUT:
10:54:20  [TestNG] Running:
10:54:20    java/lang/invoke/MethodHandles/classData/ClassDataTest.java
10:54:20  
10:54:20  test ClassDataTest.arrayClassData(): success
10:54:20  test ClassDataTest.arrayListClassData(): success
10:54:20  test ClassDataTest.classClassData(): success
10:54:20  test ClassDataTest.classDataMap(): success
10:54:20  test ClassDataTest.condyInvokedFromVirtualMethod(): success
10:54:20  test ClassDataTest.floatClassData(): success
10:54:20  test ClassDataTest.illegalAccess(java.lang.invoke.MethodHandles$Lookup@791e3416, 31): failure
10:54:20  java.lang.AssertionError: expected [31] but found [15]
10:54:20  	at org.testng.Assert.fail(Assert.java:94)
10:54:20  	at org.testng.Assert.failNotEquals(Assert.java:496)
10:54:20  	at org.testng.Assert.assertEquals(Assert.java:125)
10:54:20  	at org.testng.Assert.assertEquals(Assert.java:372)
10:54:20  	at org.testng.Assert.assertEquals(Assert.java:382)
10:54:20  	at ClassDataTest.illegalAccess(ClassDataTest.java:97)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
10:54:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:54:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
10:54:20  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
10:54:20  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
10:54:20  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
10:54:20  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
10:54:20  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
10:54:20  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
10:54:20  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
10:54:20  	at org.testng.TestRunner.run(TestRunner.java:623)
10:54:20  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
10:54:20  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
10:54:20  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
10:54:20  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
10:54:20  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
10:54:20  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
10:54:20  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
10:54:20  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
10:54:20  	at org.testng.TestNG.run(TestNG.java:1018)
10:54:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
10:54:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
10:54:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:54:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
10:54:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:54:20  	at java.base/java.lang.Thread.run(Thread.java:883)
10:54:20  test ClassDataTest.illegalAccess(java.lang.invoke.MethodHandles$Lookup@fb7aae51, 25): failure
10:54:20  java.lang.AssertionError: expected [25] but found [1]
10:54:20  	at org.testng.Assert.fail(Assert.java:94)
10:54:20  	at org.testng.Assert.failNotEquals(Assert.java:496)
10:54:20  	at org.testng.Assert.assertEquals(Assert.java:125)
10:54:20  	at org.testng.Assert.assertEquals(Assert.java:372)
10:54:20  	at org.testng.Assert.assertEquals(Assert.java:382)
10:54:20  	at ClassDataTest.illegalAccess(ClassDataTest.java:97)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
10:54:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:54:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
10:54:20  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
10:54:20  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
10:54:20  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
10:54:20  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
10:54:20  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
10:54:20  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
10:54:20  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
10:54:20  	at org.testng.TestRunner.run(TestRunner.java:623)
10:54:20  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
10:54:20  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
10:54:20  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
10:54:20  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
10:54:20  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
10:54:20  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
10:54:20  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
10:54:20  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
10:54:20  	at org.testng.TestNG.run(TestNG.java:1018)
10:54:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
10:54:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
10:54:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:54:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
10:54:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:54:20  	at java.base/java.lang.Thread.run(Thread.java:883)
10:54:20  test ClassDataTest.illegalAccess(HC/0x0000000000000000/package, 25): success
10:54:20  test ClassDataTest.immutableListClassData(): success
10:54:20  test ClassDataTest.incorrectType(): success
10:54:20  test ClassDataTest.intClassData(): success
10:54:20  test ClassDataTest.invalidIndex(): success
10:54:20  test ClassDataTest.listClassData(): success
10:54:20  test ClassDataTest.mutableListClassData(): success
10:54:20  test ClassDataTest.noClassData(): success
10:54:20  test ClassDataTest.nonDefaultName(): success
10:54:20  test ClassDataTest.nullElement(): success
10:54:20  test ClassDataTest.testOriginalAccess(): success
10:54:20  test ClassDataTest.unboxNull(): success
10:54:20  
10:54:20  ===============================================
10:54:20  java/lang/invoke/MethodHandles/classData/ClassDataTest.java
10:54:20  Total tests run: 20, Failures: 2, Skips: 0
10:54:20  ===============================================
10:54:20  
10:54:20  STDERR:
10:54:20  java.lang.Exception: failures: 2
10:54:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
10:54:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:54:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
10:54:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:54:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
10:54:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:54:20  	at java.base/java.lang.Thread.run(Thread.java:883)
10:54:20  
10:54:20  JavaTest Message: Test threw exception: java.lang.Exception: failures: 2
10:54:20  JavaTest Message: shutting down test
10:54:20  
10:54:20  STATUS:Failed.`main' threw exception: java.lang.Exception: failures: 2
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&CUSTOM_TARGET=java/lang/invoke/MethodHandles/classData/ClassDataTest.java&TARGET=jdk_custom_0)

This is also reproduced at JDK17 `Test_grinder/job/Grinder/17543`.
```
10:51:58  openjdk version "17-internal" 2021-09-14
10:51:58  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
10:51:58  Eclipse OpenJ9 VM (build master-b49892b0b23, JRE 17 Linux amd64-64-Bit Compressed References 20210813_41 (JIT enabled, AOT enabled)
10:51:58  OpenJ9   - b49892b0b23
10:51:58  OMR      - ac3ab4821a5
10:51:58  JCL      - b40e984c3a1 based on jdk-17+35)
```

**Comment by JasonFengJ9** [comment]
Passed w/ a recent JDK17 (`openj9-staging`) build at `Test_grinder/job/Grinder/17599`
```
09:22:22  openjdk version "17-internal" 2021-09-14
09:22:22  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
09:22:22  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 17 Linux amd64-64-Bit Compressed References 20210819_45 (JIT enabled, AOT enabled)
09:22:22  OpenJ9   - cd8db74f1d4
09:22:22  OMR      - ac3ab4821a5
09:22:22  JCL      - b40e984c3a1 based on jdk-17+35)
```

Also passed w/ a recent JDK16 build at `Test_grinder/job/Grinder/17600`
```
09:44:37  openjdk version "16.0.2-internal" 2021-07-20
09:44:37  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16x86-64linuxPersonal)
09:44:37  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 16 Linux amd64-64-Bit Compressed References 20210819_284 (JIT enabled, AOT enabled)
09:44:37  OpenJ9   - cd8db74f1d4
09:44:37  OMR      - ac3ab4821a5
09:44:37  JCL      - 44316ee515b based on jdk-16.0.2+7)
```

closing..
