### ISSUE TITLE
openjdk java/util/concurrent/Executors/AutoShutdown.java 2 not equal to 3

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#11899]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly/294
java/util/concurrent/Executors/AutoShutdown.java
```
23:34:57  STDOUT:
23:34:57  2 not equal to 3
23:34:57  
23:34:57  Passed = 0, failed = 1
23:34:57  
23:34:57  STDERR:
23:34:57  java.lang.Throwable
23:34:57  	at java.lang.Thread.dumpStack(Thread.java:498)
23:34:57  	at AutoShutdown.fail(AutoShutdown.java:81)
23:34:57  	at AutoShutdown.fail(AutoShutdown.java:82)
23:34:57  	at AutoShutdown.equal(AutoShutdown.java:86)
23:34:57  	at AutoShutdown.realMain(AutoShutdown.java:66)
23:34:57  	at AutoShutdown.main(AutoShutdown.java:88)
23:34:57  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:34:57  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:34:57  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:34:57  	at java.lang.reflect.Method.invoke(Method.java:498)
23:34:57  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:34:57  	at java.lang.Thread.run(Thread.java:823)
23:34:57  java.lang.AssertionError: Some tests failed
23:34:57  	at AutoShutdown.main(AutoShutdown.java:90)
23:34:57  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:34:57  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:34:57  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:34:57  	at java.lang.reflect.Method.invoke(Method.java:498)
23:34:57  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:34:57  	at java.lang.Thread.run(Thread.java:823)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/14

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Personal/11
```
14:20:48  STDOUT:
14:20:48  1 not equal to 3
14:20:48  
14:20:48  Passed = 0, failed = 1
14:20:48  
14:20:48  STDERR:
14:20:48  java.lang.Throwable
14:20:48  	at java.lang.Thread.dumpStack(Thread.java:498)
14:20:48  	at AutoShutdown.fail(AutoShutdown.java:81)
14:20:48  	at AutoShutdown.fail(AutoShutdown.java:82)
14:20:48  	at AutoShutdown.equal(AutoShutdown.java:86)
14:20:48  	at AutoShutdown.realMain(AutoShutdown.java:66)
14:20:48  	at AutoShutdown.main(AutoShutdown.java:88)
14:20:48  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:20:48  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:20:48  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:20:48  	at java.lang.reflect.Method.invoke(Method.java:498)
14:20:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
14:20:48  	at java.lang.Thread.run(Thread.java:823)
14:20:48  java.lang.AssertionError: Some tests failed
14:20:48  	at AutoShutdown.main(AutoShutdown.java:90)
14:20:48  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:20:48  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:20:48  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:20:48  	at java.lang.reflect.Method.invoke(Method.java:498)
14:20:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
14:20:48  	at java.lang.Thread.run(Thread.java:823)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_mixed_Nightly/14

**Comment by pshipton** [comment]
@0xdaryl a number of recent failures, but it's not a new test. The test is related to finalization.

**Comment by pshipton** [comment]
There is an old failure report https://github.com/eclipse/openj9/issues/10048 which I'm closing as a dup of this.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/16/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/21/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_OpenJDK8/33

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/313/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/315
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/316

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/302/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/317/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_OpenJDK8/34

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/320

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/322/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/323

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/325

**Comment by 0xdaryl** [comment]
@hzongaro : I know you already have a couple of other potential finalization-related defects on your plate but could you triage this one as well?  It seems to be failing relatively frequently of late.  Thank you.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/312/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/330/

These continue to occur, I'm not going to keep recording them all. Ask me if you want the latest failure links.

**Comment by hzongaro** [comment]
> These continue to occur, I'm not going to keep recording them all. Ask me if you want the latest failure links.

Sounds good.  I'm just starting to look at one of the recent failures. . . .

**Comment by hzongaro** [comment]
I'm not sure whether issue #10048 really is a duplicate of this issue.  The failure in 10048 occurs in `tryWaitForFinalizersToRun`, while this failure occurs earlier in the set up before calling `tryWaitForFinalizersToRun`.

I am able to reproduce this failure in grinder runs, though it seems not as frequently.  Continuing to investigate.

**Comment by 0xdaryl** [comment]
This won't be fixed for 0.26.  Moving to 0.27.

**Comment by lumpfish** [comment]
Seen on openj9-0.26.0-m2 builds - see https://github.com/AdoptOpenJDK/openjdk-tests/issues/2469

**Comment by hzongaro** [comment]
In subsequent grinder runs with `-Xjit:enableAggressiveLiveness`, the problem disappeared.  I still will try to pin down where things are going wrong to be sure there's nothing wrong with what the JIT is doing.

**Comment by hzongaro** [comment]
Although I reported that the problem disappeared with `-Xjit:enableAggressiveLiveness`, I'm now unsure whether that might just be a coincidence as the problem seems to disappear with almost any options specified, like `-Xjit:verbose`

**Comment by hzongaro** [comment]
I can reproduce the failure in grinder runs with `-Xjit:limit={java/util/concurrent/ConcurrentHashMap.spread*}`, but not with a limit setting that will result in nothing being compiled, such as `-Xjit:limit={java/util/concurrent/ConcurrentHashMap.xyzzy*}`.

`ConcurrentHashMap.spread` is a rather trivial one-line static method, which is called indirectly through several layers in the call stack from the `Phaser` static init method, constructor, etc. which are in turn used in the `AutoShutdown` test.  From `jdb`:

```
main[1] where
  [1] java.util.concurrent.ConcurrentHashMap.spread (ConcurrentHashMap.java:685)
  [2] java.util.concurrent.ConcurrentHashMap.putVal (ConcurrentHashMap.java:1,012)
  [3] java.util.concurrent.ConcurrentHashMap.putIfAbsent (ConcurrentHashMap.java:1,535)
  [4] java.lang.Class$ReflectCache.insertIfAbsent (Class.java:3,832)
  [5] java.lang.Class.cacheField (Class.java:3,995)
  [6] java.lang.Class.getDeclaredFieldInternal (Class.java:844)
  [7] java.lang.Class.getDeclaredField (Class.java:811)
  [8] java.util.concurrent.Phaser.<clinit> (Phaser.java:1,156)
  [9] AutoShutdown.realMain (AutoShutdown.java:54)
  [10] AutoShutdown.main (AutoShutdown.java:97)
```

and

```
main[1] where
  [1] java.util.concurrent.ConcurrentHashMap.spread (ConcurrentHashMap.java:685)
  [2] java.util.concurrent.ConcurrentHashMap.putVal (ConcurrentHashMap.java:1,012)
  [3] java.util.concurrent.ConcurrentHashMap.putIfAbsent (ConcurrentHashMap.java:1,535)
  [4] java.lang.Class$ReflectCache.insertIfAbsent (Class.java:3,832)
  [5] java.lang.Class.cacheField (Class.java:3,995)
  [6] java.lang.Class.getDeclaredFieldInternal (Class.java:844)
  [7] java.lang.Class.getDeclaredField (Class.java:811)
  [8] java.util.concurrent.atomic.AtomicReference.<clinit> (AtomicReference.java:58)
  [9] java.util.concurrent.Phaser.<init> (Phaser.java:566)
  [10] java.util.concurrent.Phaser.<init> (Phaser.java:527)
  [11] AutoShutdown.realMain (AutoShutdown.java:54)
  [12] AutoShutdown.main (AutoShutdown.java:97)
```

I'm still trying to figure out how compiling that method could cause things to go awry.

**Comment by pshipton** [comment]
I haven't seen this failure in a while.

**Comment by hzongaro** [comment]
I haven't been able to make time to progress this recently.  It won't be resolved for 0.27.0, so I'll move it to 0.28.0.

**Comment by pshipton** [comment]
Not seen in some time, closing.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/329
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/352
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/363

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_sanity.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/1228/)
```
[2026-03-21T00:54:45.795Z] Running test jdk_concurrent_1 ...
[2026-03-21T00:54:45.795Z] ===============================================
[2026-03-21T00:54:45.795Z] jdk_concurrent_1 Start Time: Fri Mar 20 20:54:43 2026 Epoch Time (ms): 1774054483916
[2026-03-21T00:54:45.795Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2026-03-21T00:54:45.795Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2026-03-21T00:59:09.530Z] TEST: java/util/concurrent/Executors/AutoShutdown.java

[2026-03-21T00:59:09.530Z] STDOUT:
[2026-03-21T00:59:09.530Z] 2 not equal to 3
[2026-03-21T00:59:09.530Z] 
[2026-03-21T00:59:09.530Z] Passed = 0, failed = 1
[2026-03-21T00:59:09.530Z] 
[2026-03-21T00:59:09.530Z] STDERR:
[2026-03-21T00:59:09.530Z] java.lang.Throwable
[2026-03-21T00:59:09.530Z] 	at java.lang.Thread.dumpStack(Thread.java:497)
[2026-03-21T00:59:09.530Z] 	at AutoShutdown.fail(AutoShutdown.java:81)
[2026-03-21T00:59:09.530Z] 	at AutoShutdown.fail(AutoShutdown.java:82)
[2026-03-21T00:59:09.530Z] 	at AutoShutdown.equal(AutoShutdown.java:86)
[2026-03-21T00:59:09.530Z] 	at AutoShutdown.realMain(AutoShutdown.java:66)
[2026-03-21T00:59:09.530Z] 	at AutoShutdown.main(AutoShutdown.java:88)

[2026-03-21T00:59:09.530Z] java.lang.AssertionError: Some tests failed
[2026-03-21T00:59:09.530Z] 	at AutoShutdown.main(AutoShutdown.java:90)

```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/383
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/395

**Comment by 0xdaryl** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/432

**Comment by 0xdaryl** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/456
