### ISSUE TITLE
OJDK MH: IllegalAccessException: no such method: ...

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11924]
### Errors
Unexpected `IllegalAccessException` (caused by `IncompatibleClassChangeError`) thrown when OJDK MHs are enabled in OpenJ9.

```
java.lang.IllegalAccessException: no such method: org.openj9.test.jsr335.defendersupersends.asm.K.m()char/invokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:974)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3651)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:2997)

Caused by: java.lang.IncompatibleClassChangeError: conflicting default methods for 'm()C' in org/openj9/test/jsr335/defendersupersends/asm/K from classes [org/openj9/test/jsr335/defendersupersends/asm/A, org/openj9/test/jsr335/defendersupersends/asm/B]
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1087)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1116)
```

### Failing Test Targets

1. `jsr335tests_*` (multiple variants with different JVM arguments) [sanity.functional] 
     - `test335DefenderSupersendsAsmAsMethodHandles`
     - `testConflictingDefinitionsInSuperInterface`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
`IncompatibleClassChangeError` from `MethodHandleNatives.resolve` is not expected by `MemberName.makeAccessException`. Fix is related to error handling within `MethodHandleNatives.resolve`.

This should be tagged with the `project:MH` label.

fyi @fengxue-IS

**Comment by fengxue-IS** [comment]
I wiil look into this

**Comment by babsingh** [comment]
For `test335DefenderSupersendsAsmAsMethodHandles`,
- RI throws an `VerifyError`.
- OpenJ9 with OJDK MHs enabled throws `IllegalAccessException` (caused by `IncompatibleClassChangeError`) as shown in the above description.
- OpenJ9 with OJ9 MHs passes.

### TODOs
- Verify if `test335DefenderSupersendsAsmAsMethodHandles` is valid and checking for correct behaviour.

### RI output for test335DefenderSupersendsAsmAsMethodHandles
```
openjdk 16-ea 2021-03-16
OpenJDK Runtime Environment (build 16-ea+33-2205)
OpenJDK 64-Bit Server VM (build 16-ea+33-2205, mixed mode, sharing)

FAILED: test335DefenderSupersendsAsmAsMethodHandles
java.lang.AssertionError:
Test U
	Unexpected exception - class java.lang.VerifyError: Bad invokespecial instruction: interface method reference is in an indirect superinterface.
Exception Details:
  Location:
    org/openj9/test/jsr335/defendersupersends/asm/U.m()C @1: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2ab7 001b ac

	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.jsr335.defendersupersends.asm.TestDefenderMethodLookupAsm.test335DefenderSupersendsAsmAsMethodHandles(TestDefenderMethodLookupAsm.java:164)
```

**Comment by babsingh** [comment]
For `testConflictingDefinitionsInSuperInterface`,
- RI and OpenJ9 with OJ9 MHs pass.
- OpenJ9 with OJDK MHs throws `IllegalAccessException` (caused by `IncompatibleClassChangeError`).

**Comment by tajila** [comment]
@JasonFengJ9 can you please look at the `test335DefenderSupersendsAsmAsMethodHandles` test failure?

**Comment by JasonFengJ9** [comment]
Sure, will look into it.

**Comment by fengxue-IS** [comment]
Closing this as #12668 should fix and re-enable these tests
