### ISSUE TITLE
OJDK MH: testJITServer failures

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11923]
### Errors

```
FAILED: testServer
java.lang.AssertionError: Expected an exit value of 0 or 143, got 1 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServer(JITServerTest.java:209)

FAILED: testServerComesUpAfterClient
java.lang.AssertionError: Expected an exit value of 0 or 143, got 1 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServerComesUpAfterClient(JITServerTest.java:340)

FAILED: testServerGoesDown
java.lang.AssertionError: Expected an exit value of 0 or 143, got 1 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServerGoesDown(JITServerTest.java:228)

FAILED: testServerGoesDownAnotherComesUp
java.lang.AssertionError: Expected an exit value of 0 or 143, got 1 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServerGoesDownAnotherComesUp(JITServerTest.java:256)

FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: Expected an exit value of 0 or 143, got 1 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:309)
```

### Failing Test Targets

1. `testJITServer_0` [sanity.functional] 
2. `testJITServer_1` [sanity.functional] 

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
Standalone issue to track JIT server failures with OJDK MHs.

This should be tagged with the `project:MH` label.

fyi @dmitry-ten

**Comment by mpirvu** [comment]
@dmitry-ten Will changes from #11933 make these tests pass?

**Comment by dmitry-ten** [comment]
I ran this test a couple of times with that change and it passed.
However, I then tried to run without it and it still passed, so I need to do more testing.

**Comment by dmitry-ten** [comment]
The test currently fails due to #12162 not supporting JITServer.
Currently working on a fix.

**Comment by dmitry-ten** [comment]
#12525 should enable this test to pass.

**Comment by dmitry-ten** [comment]
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/15171/) of OJDK292 build with #12525 included.
80 iterations passed (the rest failed due to infra issues).

**Comment by mpirvu** [comment]
Closing as fixed. Please open a new issue if seen again.
