### ISSUE TITLE
OJDK MH: MethodHandles.collectArguments Issues

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11922]
### Errors

`MethodHandles.collectArguments` issues that are seen when OJDK MHs are enabled in OpenJ9.

```
java.lang.IndexOutOfBoundsException: bad index: 3
	at java.base/java.lang.invoke.MethodType.newIndexOutOfBoundsException(MethodType.java:233) from jrt:/java.base
	at java.base/java.lang.invoke.MethodType.insertParameterTypes(MethodType.java:438) from jrt:/java.base
	at java.base/java.lang.invoke.MethodType.insertParameterTypes(MethodType.java:479) from jrt:/java.base
	at java.base/java.lang.invoke.MethodHandles.collectArgumentsChecks(MethodHandles.java:5752) from jrt:/java.base
	at java.base/java.lang.invoke.MethodHandles.collectArguments(MethodHandles.java:5732) from jrt:/java.base
```

```
java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.lang.invoke.MethodType.parameterType(MethodType.java:775) from jrt:/java.base
	at java.base/java.lang.invoke.MethodHandles.collectArgumentsChecks(MethodHandles.java:5754) from jrt:/java.base
	at java.base/java.lang.invoke.MethodHandles.collectArguments(MethodHandles.java:5732) from jrt:/java.base
```

### Failing Test Targets

1. `JCL_Test_*` [sanity.functional] 
    - `test_CollectArgumentsNegative`
    - `test_VoidCollectArgumentsNegative`

Repetitions of the above error are seen because the test target is run with different JVM arguments.

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
OpenJDK bug: https://bugs.openjdk.java.net/browse/JDK-8259922

Fix: https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ab6b9c35c7541ea628b028cb1357b904a72de5d9

Only available in JDK-next. Needs to be back-ported to JDK8, JDK11 and JDK16.

This should be tagged with the `project:MH` label.

**Comment by fengxue-IS** [comment]
Still needs to be back-ported to JDK8, JDK11 in the future once we are ready to enable OJDK MH for these versions.
As this is fixed for Java17+, marking this low priority

**Comment by babsingh** [comment]
Backported to JDK8 and JDK11:
- https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/560
- https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/502
