### ISSUE TITLE
Valhalla: Value type abstract super classes

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#12039]
There is an interface called IndentityObject (currently named `IdentityInterface` - needs renaming) which is implicitly implemented by all stateful types, that is:
1) Is concrete (non-abstract/interface - j.l.Object exculded) or,
2) Declares an instance field or,
3) Declares an instance initializer or,
4) Has constructor with a non-empty body (something other than 'super();') or,
5) Must have access to extend the super class (supers <init> must be visible)
6) Declares a synchronized method
//Note: Most importantly, an abstract class can also implement IdentityInterface explicitly or implicitly if it has any of the properties above

A value-type (primitive class) has the following requirements:
1) Cannot subclass any type that implements `IdentityInterface` either directly or indirectly.
2) Cannot be abstract
3) Must not declare synchronized methods
4) Must have access to extend the super class (supers <init> must be visible)

Currently, we only inject the IdentityObject interface for types that are concrete, https://github.com/eclipse/openj9/blob/master/runtime/bcutil/ROMClassBuilder.cpp#L254. This needs to be updated with the new requirements above.

Implementation plan:
------------------------
1) Detect abstract classes that have no fields, have empty constructors and do not implement `IdentityInterface` either directly or indirectly. We can refer to these as "light" abstract classes, all other abstract classes are considered "heavy"
2) Ensure that all "heavy" abstract classes implement `IdentityInterface`, may inject it if needed. Note "light" abstract classes may optionally implement `IdentityInterface` if user chooses so.
3) Ensure the the super type for Valuetypes is type that doesnt implement `IdentityInterface`, throw a VerificationError otherwise (the exact type of error is TBD but we can use the verify error for the time being)

Test plan
--------------
1) Ensure that primitive class can not subclass concrete type or "heavy" abstract type
2) Ensure that primitive class can subclass "light" abstract type and j.l.Object
3) Ensure that primitive class can not subtype IndentityObject
4) Ensure that primitive class can not subclass any type that implements IdentityObject (even if light abstract type) either directly or indirectly
5) Ensure primitive class can not be abstract or interface
6) Ensure primitive class can not have synchronized methods
//Note: some of the existing tests in `openj9/test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java` may need to be modified with the new requirements.

**Comment by tajila** [comment]
@hangshao0 can you please take a look at this

**Comment by hangshao0** [comment]
Yes.

**Comment by hangshao0** [comment]
I notice after my change to fix this issue, `org.openj9.test.annotationPackage.Test_PackageAnnotation` and `org.openj9.test.annotationPackage.Test_PackageAnnotation2` will fail in `x86-64_linux_vt_standard` build.

```
java.lang.annotation.AnnotationFormatError: Attempt to create proxy for a non-annotation type: javax.xml.bind.annotation.XmlSchema
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.<init>(AnnotationInvocationHandler.java:56) from jrt:/java.base
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:307) from jrt:/java.base
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:304) from jrt:/java.base
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682) from jrt:/java.base
	at java.base/sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:304) from jrt:/java.base
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:294) from jrt:/java.base
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121) from jrt:/java.base
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73) from jrt:/java.base
	at java.base/java.lang.Class.getAnnotationCache(Class.java:3115) from jrt:/java.base
	at java.base/java.lang.Class.getAnnotation(Class.java:2700) from jrt:/java.base
	at java.base/java.lang.Package.getAnnotation(Package.java:457) from jrt:/java.base
	at java.base/java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:292) from jrt:/java.base
	at java.base/java.lang.Package.isAnnotationPresent(Package.java:467) from jrt:/java.base
	at org.openj9.test.annotationPackage.Test_PackageAnnotation.checkPackage(Test_PackageAnnotation.java:88) from jdk.internal.loader.ClassLoaders$AppClassLoader@c71c7174(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.annotationPackage.Test_PackageAnnotation.test_elementFormDefault(Test_PackageAnnotation.java:55) from jdk.internal.loader.ClassLoaders$AppClassLoader@c71c7174(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

This is because in the current JCL code, `AnnotationInvocationHandler` enforces annotation type to have `java.lang.annotation.Annotation.class` as its only super interface. This is not true anymore after this change. 

I believe OpenJDK will change the JCL code in the future. For the time being, we need to exclude these tests.
