### ISSUE TITLE
renaissance-als_0_FAILED - LoginException: No LoginModule found for com.ibm.security.auth.module.LinuxLoginModule - Unable to find JAAS classes:com.ibm.security.auth.UsernamePrincipal

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12151]
Failure link
------------

From an internal build `Test_openjdk11_j9_extended.perf_ppc64le_linux/3`:
```
03:45:11  java version "11.0.11" 2021-04-20
03:45:11  Java(TM) SE Runtime Environment 11.0.10.0-IBM (build 11.0.11+9)
03:45:11  Eclipse OpenJ9 VM 11.0.10.0-IBM (build master-b227feba2, JRE 11 Linux ppc64le-64-Bit Compressed References 20210305_2 (JIT enabled, AOT enabled)
03:45:11  OpenJ9   - b227feba2
03:45:11  OMR      - 4665e2f72
03:45:11  JCL      - 153c429994 based on jdk-11.0.11+5)
```
rebuild the failed tests in one link:
04:31:07  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&JDK_VENDOR=ibm&BUILD_LIST=perf&PLATFORM=ppc64le_linux_mixed&TARGET=testList%20TESTLIST=renaissance-als_0,renaissance-chi-square_0,renaissance-dec-tree_0,renaissance-gauss-mix_0,renaissance-log-regression_0,renaissance-movie-lens_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test renaissance-als_0 ...
===============================================
renaissance-als_0 Start Time: Sat Mar  6 01:14:53 2021 Epoch Time (ms): 1615022093416
variation: NoOptions
JVM_OPTIONS:  
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/03/06 01:15:00 INFO SparkContext: Running Spark version 2.0.0
21/03/06 01:15:01 ERROR UserGroupInformation: Unable to find JAAS classes:com.ibm.security.auth.UsernamePrincipal
21/03/06 01:15:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Benchmark 'als' failed with exception:
java.io.IOException: failure to login
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:700)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:571)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2245)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2245)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2245)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:297)
	at org.renaissance.apache.spark.SparkUtil$class.setUpSparkContext(SparkUtil.scala:33)
	at org.renaissance.apache.spark.Als.setUpSparkContext(Als.scala:34)
	at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:86)
	at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:44)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1(RenaissanceSuite.scala:118)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1$adapted(RenaissanceSuite.scala:113)
	at org.renaissance.harness.RenaissanceSuite$$$Lambda$152/0x0000000000000000.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:113)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:94)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:37)
	at org.renaissance.core.Launcher.main(Launcher.java:25)
Caused by: javax.security.auth.login.LoginException: No LoginModule found for com.ibm.security.auth.module.LinuxLoginModule
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:710)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:675)
	... 25 more
The following benchmarks failed: als

renaissance-als_0_FAILED
```
This appears a test setup issue.

**Comment by llxia** [comment]
renaissance-* test runs the same in hyc and Adopt. No `Unable to find JAAS classes:com.ibm.security.auth.UsernamePrincipal issue`. I suspect this is machine related issue.
https://ci.adoptopenjdk.net/job/Grinder/469/
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.perf_x86-64_linux/
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.perf_ppc64le_linux/

**Comment by JasonFengJ9** [comment]
This appears an internal IBM build issue (`infrastructure/issues/5444`).

Closing..

**Comment by avermeer** [comment]
Also if you mean that the issue would come that some deprecated IBM classes have been removed between OpenJ9 January 2022 version versus April 2022 version, then it means that what's considered as a security patch update of Java 11 is actually removing code, something that would be understandable if switching from Java 8 to Java 11, but not on a patch release...

**Comment by pshipton** [comment]
No IBM classes were removed from OpenJ9 builds, they were never there. I think what's going on is that 3rd party code looks at the java.vendor system property and when it's "IBM Corporation" they expect IBM Java 8 which does have com.ibm.security classes. When IBM started creating Semeru builds, the java.vendor should have been "IBM Corporation" but was set for Java 8 & 11 temporarily to "International Business Machines Corporation". Java 17 has always used "IBM Corporation" from the initial release. In the 0.32 release Java 8 & 11 are changing back to "IBM Corporation".

3rd party code needs to recognize the difference between IBM Java 8 and Semeru 8/11 by looking at more than just the java.vendor property. For a workaround to change the java.vendor property, see https://github.com/eclipse-openj9/openj9/issues/14950#issuecomment-1105797810
