### ISSUE TITLE
JDK17 jdk_other_0_FAILED - AssertionError: Should have GCd a class loader by now

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12481]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.openjdk_aarch64_linux/2/`
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment AdoptOpenJDK-17+18 (build 17+18)
Eclipse OpenJ9 VM AdoptOpenJDK-17+18 (build master-22fc51137, JRE 17 Linux aarch64-64-Bit Compressed References 20210417_33 (JIT enabled, AOT enabled)
OpenJ9   - 22fc51137
OMR      - 0f967b721
JCL      - 380dc812b6 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_other_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=aarch64_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F33%2FOpenJDK-testimage_aarch64_linux_openj9_2021-04-17-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F33%2FOpenJDK-debugimage_aarch64_linux_openj9_2021-04-17-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F33%2FOpenJDK-jdk_aarch64_linux_openj9_2021-04-17-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F33%2FOpenJDK-jre_aarch64_linux_openj9_2021-04-17-14-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=17&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-04-17T17:20:44.915Z] STDERR:
[2021-04-17T17:20:44.915Z] java.lang.AssertionError: Should have GCd a class loader by now
[2021-04-17T17:20:44.915Z] 	at TypeConverterFactoryRetentionTests.testFromOneClassToClassLoader(TypeConverterFactoryRetentionTests.java:183)
[2021-04-17T17:20:44.915Z] 	at TypeConverterFactoryRetentionTests.testSystemLoaderToOtherLoader(TypeConverterFactoryRetentionTests.java:149)
[2021-04-17T17:20:44.915Z] 	at TypeConverterFactoryRetentionTests.main(TypeConverterFactoryRetentionTests.java:131)
[2021-04-17T17:20:44.915Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-17T17:20:44.915Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-17T17:20:44.915Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-17T17:20:44.915Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-17T17:20:44.915Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-04-17T17:20:44.915Z] 	at java.base/java.lang.Thread.run(Thread.java:878)
[2021-04-17T17:20:44.915Z] 
[2021-04-17T17:20:44.916Z] JavaTest Message: Test threw exception: java.lang.AssertionError: Should have GCd a class loader by now
[2021-04-17T17:20:44.916Z] JavaTest Message: shutting down test

[2021-04-17T17:20:44.916Z] --------------------------------------------------
[2021-04-17T17:21:24.754Z] Test results: passed: 262; failed: 5; error: 5
[2021-04-17T17:21:54.307Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2021-04-17T17:21:54.307Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/openjdk-tests/TKG/output_1618679423419/jdk_other_0/work
[2021-04-17T17:21:54.307Z] Error: Some tests failed or other problems occurred.
[2021-04-17T17:21:54.307Z] 
[2021-04-17T17:21:54.307Z] jdk_other_0_FAILED
```

This appears re-occurrence of https://github.com/eclipse/openj9/issues/12080

fyi @dmitripivkine

**Comment by JasonFengJ9** [comment]
Observed at `job/Test_openjdk17_j9_extended.openjdk_x86-64_mac/3/`

```
[2021-04-25T04:09:04.828Z] Running test jdk_other_0 ...
[2021-04-25T04:09:04.828Z] ===============================================
[2021-04-25T04:09:04.829Z] jdk_other_0 Start Time: Sun Apr 25 00:09:04 2021 Epoch Time (ms): 1619323744331
[2021-04-25T04:09:04.829Z] "/Users/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-04-25T04:09:04.829Z] JVMSHRC005I No shared class caches available
[2021-04-25T04:09:04.829Z] JVMSHRC005I No shared class caches available
[2021-04-25T04:09:04.829Z] cache cleanup done
[2021-04-25T04:09:04.829Z] variation: Mode150
[2021-04-25T04:09:04.829Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

...

[2021-04-25T04:09:58.593Z] --------------------------------------------------
[2021-04-25T04:09:58.593Z] TEST: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java#with_G1GC
[2021-04-25T04:09:58.593Z] 
[2021-04-25T04:09:58.593Z] TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.G1'
[2021-04-25T04:09:58.593Z] --------------------------------------------------
[2021-04-25T04:09:58.593Z] TEST: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java#with_ParallelGC
[2021-04-25T04:09:58.593Z] 
[2021-04-25T04:09:58.593Z] TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.Parallel'
[2021-04-25T04:09:58.593Z] --------------------------------------------------
[2021-04-25T04:09:58.593Z] TEST: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java#with_SerialGC
[2021-04-25T04:09:58.593Z] 
[2021-04-25T04:09:58.593Z] TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.Serial'
[2021-04-25T04:09:58.593Z] --------------------------------------------------
[2021-04-25T04:09:58.593Z] TEST: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java#with_ShenandoahGC
[2021-04-25T04:09:58.593Z] 
[2021-04-25T04:09:58.593Z] TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.Shenandoah'
[2021-04-25T04:09:58.593Z] --------------------------------------------------
[2021-04-25T04:09:58.593Z] TEST: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java#with_ZGC
[2021-04-25T04:09:58.593Z] 
[2021-04-25T04:09:58.593Z] TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.Z'

...

[2021-04-25T04:10:04.629Z] STDERR:
[2021-04-25T04:10:04.629Z] java.lang.AssertionError: Should have GCd a class loader by now
[2021-04-25T04:10:04.629Z] 	at TypeConverterFactoryRetentionTests.testFromOneClassToClassLoader(TypeConverterFactoryRetentionTests.java:183)
[2021-04-25T04:10:04.629Z] 	at TypeConverterFactoryRetentionTests.testSystemLoaderToOtherLoader(TypeConverterFactoryRetentionTests.java:149)
[2021-04-25T04:10:04.629Z] 	at TypeConverterFactoryRetentionTests.main(TypeConverterFactoryRetentionTests.java:131)
[2021-04-25T04:10:04.629Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-25T04:10:04.629Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-25T04:10:04.629Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-25T04:10:04.629Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-25T04:10:04.629Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-04-25T04:10:04.629Z] 	at java.base/java.lang.Thread.run(Thread.java:878)
```

**Comment by dmitripivkine** [comment]
I don't see how it might be GC related. If it is not pure test issue VM (or JIT) should take a look to it. I assuming this is not new test existed (or adopted) for Java 17 only

**Comment by llxia** [comment]
The same test passed on hotspot: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/26/tapResults/

```
00:01:59.397  openjdk version "17" 2021-09-14
00:01:59.397  OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
00:01:59.397  OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
```
```
00:43:57.447  ===============================================
00:43:57.447  Running test jdk_other_0 ...
00:43:57.447  ===============================================
00:43:57.447  jdk_other_0 Start Time: Tue Sep 14 23:09:52 2021 Epoch Time (ms): 1631660992562
00:43:57.447  Nothing to be done for setup.
00:43:57.447  variation: Mode150
00:43:57.447  JVM_OPTIONS:  -XX:+UseCompressedOops 
00:43:57.447  { itercnt=1; \
00:43:57.447  mkdir -p "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../TKG/output_16316585861140/jdk_other_0"; \
00:43:57.447  cd "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../TKG/output_16316585861140/jdk_other_0"; \
00:43:57.447  "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xmx512m -jar "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
00:43:57.447  -agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:4 -nativepath:"/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/openjdkbinary/openjdk-test-image/jdk/jtreg/native" -vmoptions:"-Xmx512m  -XX:+UseCompressedOops " \
00:43:57.447  -w ""/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../TKG/output_16316585861140/jdk_other_0"/work" \
00:43:57.447  -r "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../../jvmtest/openjdk/report" \
00:43:57.447  -jdk:"/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image" \
00:43:57.447  -exclude:"/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../openjdk/openjdk-jdk/test/jdk/ProblemList.txt" \
00:43:57.447  -exclude:"/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../../jvmtest/openjdk/excludes/ProblemList_openjdk17.txt" \
00:43:57.447  "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../openjdk/openjdk-jdk/test/jdk:jdk_other"; \
00:43:57.447  if [ $? -eq 0 ] ; then echo ""; echo "jdk_other_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/..;  else echo ""; echo "jdk_other_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../TKG/output_16316585861140/TestTargetResult";
00:43:58.076  Directory "/home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/../TKG/output_16316585861140/jdk_other_0/work" not found: creating
00:44:05.153  XML output with verification to /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16316585861140/jdk_other_0/work
00:47:07.505  Test results: passed: 272
00:47:18.311  Report written to /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
00:47:18.311  Results written to /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16316585861140/jdk_other_0/work
00:47:18.311  
00:47:18.311  jdk_other_0_PASSED
00:47:18.311  
00:47:18.311  Nothing to be done for teardown.
00:47:18.311  jdk_other_0 Finish Time: Tue Sep 14 23:13:13 2021 Epoch Time (ms): 1631661193260
```

**Comment by dmitripivkine** [comment]
Can we try this with `-Xjit:enableAggressiveLiveness` ?

**Comment by llxia** [comment]
I do not see jdk_other failure in the[ last several tests builds](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux). 

Ran jdk_other in [Grinder x20]( https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/18581/)
