### ISSUE TITLE
java/nio/channels/FileChannel/directio/DirectIOTest.java - BufferOverflowException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12480]
Failure link
------------

From an internal build `job/Test_openjdk16_j9_extended.openjdk_ppc64le_linux/5/`
sles15le-rt1-2
```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK-16+36 (build 16+36)
Eclipse OpenJ9 VM AdoptOpenJDK-16+36 (build master-22fc51137, JRE 16 Linux ppc64le-64-Bit Compressed References 20210417_18 (JIT enabled, AOT enabled)
OpenJ9   - 22fc51137
OMR      - 0f967b721
JCL      - 073accb86d based on jdk-16+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_nio_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=ppc64le_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-ppc64le-openj9%2F18%2FOpenJDK16U-testimage_ppc64le_linux_openj9_2021-04-17-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-ppc64le-openj9%2F18%2FOpenJDK16U-debugimage_ppc64le_linux_openj9_2021-04-17-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-ppc64le-openj9%2F18%2FOpenJDK16U-jre_ppc64le_linux_openj9_2021-04-17-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-ppc64le-openj9%2F18%2FOpenJDK16U-jdk_ppc64le_linux_openj9_2021-04-17-13-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=16&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk16&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-04-17T16:04:03.092Z] STDERR:
[2021-04-17T16:04:03.092Z] java.nio.BufferOverflowException
[2021-04-17T16:04:03.092Z] 	at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:721)
[2021-04-17T16:04:03.092Z] 	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:398)
[2021-04-17T16:04:03.092Z] 	at DirectIOTest.testWrite(DirectIOTest.java:59)
[2021-04-17T16:04:03.092Z] 	at DirectIOTest.main(DirectIOTest.java:103)
[2021-04-17T16:04:03.092Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-17T16:04:03.092Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-17T16:04:03.092Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-17T16:04:03.092Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2021-04-17T16:04:03.092Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-04-17T16:04:03.092Z] 	at java.base/java.lang.Thread.run(Thread.java:878)
[2021-04-17T16:04:03.092Z] 
[2021-04-17T16:04:03.092Z] JavaTest Message: Test threw exception: java.nio.BufferOverflowException
[2021-04-17T16:04:03.092Z] JavaTest Message: shutting down test
[2021-04-17T16:04:03.092Z] 
[2021-04-17T16:04:03.092Z] 
[2021-04-17T16:04:03.092Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.nio.BufferOverflowException
[2021-04-17T16:04:03.092Z] --------------------------------------------------
[2021-04-17T16:16:35.109Z] Test results: passed: 436; failed: 1
[2021-04-17T16:16:44.476Z] Report written to /home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_ppc64le_linux/jvmtest/openjdk/report/html/report.html
[2021-04-17T16:16:44.476Z] Results written to /home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_ppc64le_linux/openjdk-tests/TKG/output_16186673795166/jdk_nio_0/work
[2021-04-17T16:16:44.476Z] Error: Some tests failed or other problems occurred.
[2021-04-17T16:16:44.476Z] 
[2021-04-17T16:16:44.476Z] jdk_nio_0_FAILED
```

**Comment by pshipton** [comment]
Pls grind and get a failure rate.

**Comment by JasonFengJ9** [comment]
> Pls grind and get a failure rate.

10x grinder (Test_grinder/job/Grinder/14868/) all passed.

**Comment by pshipton** [comment]
Another one on Java 11.
job/Test_openjdk11_j9_extended.openjdk_ppc64le_linux/10
sles12le-rt1-1

I wonder if the failure is specific to certain machines.

**Comment by JasonFengJ9** [comment]
> I wonder if the failure is specific to certain machines.

3x grinder at `sles15le-rt1-2` all failed (`Test_grinder/job/Grinder/14942`).

**Comment by pshipton** [comment]
That suggests it's either a machine problem, or a sles problem.

**Comment by JasonFengJ9** [comment]
Seen in JDK11 `Test_openjdk11_j9_extended.openjdk_ppc64le_linux/12/` (`sles12le-rt1-4`)
```
java version "11.0.11" 2021-04-20
Java(TM) SE Runtime Environment 11.0.10.0-IBM (build 11.0.11+9)
Eclipse OpenJ9 VM 11.0.10.0-IBM (build master-194f7f30f, JRE 11 Linux ppc64le-64-Bit Compressed References 20210430_78 (JIT enabled, AOT enabled)
OpenJ9   - 194f7f30f
OMR      - c4ef57d3f
JCL      - f7ecaa2df9 based on jdk-11.0.11+9)

[2021-05-01T03:40:47.966Z] Running test jdk_nio_0 ...
[2021-05-01T03:40:47.966Z] ===============================================
[2021-05-01T03:40:47.966Z] jdk_nio_0 Start Time: Fri Apr 30 20:40:46 2021 Epoch Time (ms): 1619840446799
[2021-05-01T03:40:47.966Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_ppc64le_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_ppc64le_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-01T03:40:47.966Z] JVMSHRC005I No shared class caches available
[2021-05-01T03:40:47.966Z] JVMSHRC005I No shared class caches available
[2021-05-01T03:40:47.966Z] cache cleanup done
[2021-05-01T03:40:47.966Z] variation: Mode150
[2021-05-01T03:40:47.966Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-05-01T03:44:55.305Z] STDERR:
[2021-05-01T03:44:55.305Z] java.nio.BufferOverflowException
[2021-05-01T03:44:55.305Z] 	at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:666)
[2021-05-01T03:44:55.306Z] 	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:336)
[2021-05-01T03:44:55.306Z] 	at DirectIOTest.testWrite(DirectIOTest.java:60)
[2021-05-01T03:44:55.306Z] 	at DirectIOTest.main(DirectIOTest.java:114)
[2021-05-01T03:44:55.306Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-01T03:44:55.306Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-01T03:44:55.306Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-01T03:44:55.306Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-01T03:44:55.306Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-05-01T03:44:55.306Z] 	at java.base/java.lang.Thread.run(Thread.java:861)
[2021-05-01T03:44:55.306Z] 
[2021-05-01T03:44:55.306Z] JavaTest Message: Test threw exception: java.nio.BufferOverflowException
[2021-05-01T03:44:55.306Z] JavaTest Message: shutting down test
[2021-05-01T03:44:55.306Z] 
[2021-05-01T03:44:55.306Z] 
[2021-05-01T03:44:55.306Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.nio.BufferOverflowException
[2021-05-01T03:44:55.306Z] --------------------------------------------------
[2021-05-01T03:56:40.340Z] Test results: passed: 388; failed: 1
```

**Comment by pshipton** [comment]
Pls try a grinder on a some rhel7, 8 machines, and a ub18 machine. So far this seems specific to sles.

**Comment by JasonFengJ9** [comment]
Launched a 3x grinder at 10 different machines via `Grinder/15188`:
Passed : `rhel7lert-1-6` `rhel7lert-1-1` `rhel7le-rt1-5` `ub20lert-1-7` `rhel7lert-1-4` `rhel7le-rt1-4` `rhel7lert-1-9` `ubu20le-rt1-3` `ubu18le-rt1-5` 
Failed: `sles12le-rt1-3` 
It does appear sles OS specific.

**Comment by pshipton** [comment]
Seems a test issue fixed upstream https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/8b2827b9b4
The test is passing now. view/Test_grinder/job/Grinder/16436/
