### ISSUE TITLE
OJDK MH: NoSuchMethodError: VarHandle.get(...)

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#12539]
### Error

`NoSuchMethodError` thrown from `MethodHandleResolver.getCPMethodHandleAt`.

```
test TestNative.testNativeAccess(TestNative$$Lambda$108/0x00000000e1e70ee0@9414ac56, TestNative$$Lambda$101/0x00000000e1e70460@15d3e380, [100:b8]): failure
java.lang.NoSuchMethodError: java/lang/invoke/VarHandle.get(Ljdk/incubator/foreign/MemorySegment;Ljava/lang/Long;)Ljava/lang/Object; (loaded from jrt:/java.base by <Bootstrap Loader>) called from class TestNative (loaded from file:/.../openjdk-tests/TKG/output_16171331559140/jdk_custom_0/work/classes/0/java/foreign/TestNative.d/ by jdk.internal.loader.ClassLoaders$AppClassLoader@3144ebb).
	at java.base/java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
	at java.base/java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:382)
	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:181)
	at TestNative.lambda$nativeAccessOps$17(TestNative.java:243)
	at TestNative$$Lambda$108/0x00000000e1e70ee0.accept(Unknown Source)
	at TestNative.testNativeAccess(TestNative.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

### Initial Investigation

`VarHandle.get` is a `VarHandle MH/VH polymorphic method`. The above stack suggests that `invokedynamic` is invoked on `VarHandle.get`, which should never happen. For MH/VH `polymorphic` methods, the correct bytecode is `invokevirtual` which gets rewritten to `invokehandle`. Here, a `Lambda` is also involved. For `Lambdas`, OJDK code dynamically generates the bytecodes. Below, `invokedynamic` on `VarHandle.get` is called from `Lambda generated bytecodes`. We will need to investigate why `Lambda` generated bytecodes are calling `invokedynamic` on `VarHandle.get`.

`Lambda bytecode generation`: https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/openj9/src/java.base/share/classes/java/lang/invoke/InnerClassLambdaMetafactory.java

### Run Failing Test: TestNative.java

```
# Execute from JDK16 or JDKnext extensions repo
make test TEST="java/foreign/TestNative.java"
```

### Resources
- JDK16 extensions repo: https://github.com/ibmruntimes/openj9-openjdk-jdk16
- JDKnext extensions repo: https://github.com/ibmruntimes/openj9-openjdk-jdk
- JTreg-5.1: https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg/lastSuccessfulBuild/artifact/

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by fengxue-IS** [comment]
Latest openj9-staging branch with:
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.root.openj9-openjdk-jdk17)
Eclipse OpenJ9 VM (build master-cd8db74f1, JRE 17 Linux amd64-64-Bit Compressed References 20210818_000000 (JIT enabled, AOT enabled)
OpenJ9   - cd8db74f1
OMR      - ac3ab4821
JCL      - b40e984c3a1 based on jdk-17+35)
```
result seem to be unrelated original issue described, stacktrace points to `jdk/internal/foreign/abi/ProgrammableInvoker.registerNatives()V`
```
test TestNative.testBadResize(): success
test TestNative.testDefaultAccessModes(): failure
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: jdk/internal/foreign/abi/ProgrammableInvoker.registerNatives()V
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:471)
	at jdk.incubator.foreign/jdk.incubator.foreign.CLinker.allocateMemory(CLinker.java:402)
	at TestNative.allocate(TestNative.java:148)
	at TestNative.testDefaultAccessModes(TestNative.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner$$Lambda$97/0x00000000e00eab10.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:883)
Caused by: java.lang.UnsatisfiedLinkError: jdk/internal/foreign/abi/ProgrammableInvoker.registerNatives()V
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<clinit>(ProgrammableInvoker.java:361)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:127)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:44)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils$AllocHolder.<clinit>(SharedUtils.java:442)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:469)
	... 37 more
test TestNative.testDefaultAccessModesEverthing(): success
test TestNative.testEverythingSegment(): failure
java.lang.RuntimeException: java.lang.NoClassDefFoundError: jdk.internal.foreign.abi.SharedUtils$AllocHolder (initialization failure)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:471)
	at jdk.incubator.foreign/jdk.incubator.foreign.CLinker.allocateMemory(CLinker.java:402)
	at TestNative.allocate(TestNative.java:148)
	at TestNative.testEverythingSegment(TestNative.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner$$Lambda$97/0x00000000e00eab10.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:883)
Caused by: java.lang.NoClassDefFoundError: jdk.internal.foreign.abi.SharedUtils$AllocHolder (initialization failure)
	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:134)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:469)
	... 37 more
Caused by: java.lang.UnsatisfiedLinkError: jdk/internal/foreign/abi/ProgrammableInvoker.registerNatives()V
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<clinit>(ProgrammableInvoker.java:361)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:127)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:44)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils$AllocHolder.<clinit>(SharedUtils.java:442)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:469)
	at jdk.incubator.foreign/jdk.incubator.foreign.CLinker.allocateMemory(CLinker.java:402)
	at TestNative.allocate(TestNative.java:148)
	at TestNative.testDefaultAccessModes(TestNative.java:179)
	... 34 more
test TestNative.testMallocSegment(): failure
java.lang.RuntimeException: java.lang.NoClassDefFoundError: jdk.internal.foreign.abi.SharedUtils$AllocHolder (initialization failure)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:471)
	at jdk.incubator.foreign/jdk.incubator.foreign.CLinker.allocateMemory(CLinker.java:402)
	at TestNative.allocate(TestNative.java:148)
	at TestNative.testMallocSegment(TestNative.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner$$Lambda$97/0x00000000e00eab10.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:883)
Caused by: java.lang.NoClassDefFoundError: jdk.internal.foreign.abi.SharedUtils$AllocHolder (initialization failure)
	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:134)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:469)
	... 37 more
Caused by: java.lang.UnsatisfiedLinkError: jdk/internal/foreign/abi/ProgrammableInvoker.registerNatives()V
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<clinit>(ProgrammableInvoker.java:361)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:127)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:44)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils$AllocHolder.<clinit>(SharedUtils.java:442)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.allocateMemoryInternal(SharedUtils.java:469)
	at jdk.incubator.foreign/jdk.incubator.foreign.CLinker.allocateMemory(CLinker.java:402)
	at TestNative.allocate(TestNative.java:148)
	at TestNative.testDefaultAccessModes(TestNative.java:179)
	... 34 more
test TestNative.testNativeAccess(TestNative$$Lambda$136/0x00000000e0119b88@53dd0f3b, TestNative$$Lambda$129/0x00000000e01190f8@9ccb58e7, [100:b8]): success
test TestNative.testNativeAccess(TestNative$$Lambda$137/0x00000000e0119d08@f5739a58, TestNative$$Lambda$130/0x00000000e0119288@268af8b9, [100:b16]): success
test TestNative.testNativeAccess(TestNative$$Lambda$138/0x00000000e0119e88@d8f05a81, TestNative$$Lambda$131/0x00000000e0119408@43e6f6, [100:b16]): success
test TestNative.testNativeAccess(TestNative$$Lambda$139/0x00000000e011a008@e0409e65, TestNative$$Lambda$132/0x00000000e0119588@9c84b1ad, [100:b32]): success
test TestNative.testNativeAccess(TestNative$$Lambda$140/0x00000000e011a188@3a31c81c, TestNative$$Lambda$133/0x00000000e0119708@828ac27, [100:b32]): success
test TestNative.testNativeAccess(TestNative$$Lambda$141/0x00000000e011a308@575240c8, TestNative$$Lambda$134/0x00000000e0119888@7d5a8558, [100:b64]): success
test TestNative.testNativeAccess(TestNative$$Lambda$142/0x00000000e011a488@4d5c7630, TestNative$$Lambda$135/0x00000000e0119a08@11f0adde, [100:b64]): success
test TestNative.testNativeCapacity(TestNative$$Lambda$180/0x00000000e011f108@415859a2, 1): success
test TestNative.testNativeCapacity(TestNative$$Lambda$181/0x00000000e011f2b0@65c2e528, 2): success
test TestNative.testNativeCapacity(TestNative$$Lambda$182/0x00000000e011f410@ec146ec6, 2): success
test TestNative.testNativeCapacity(TestNative$$Lambda$183/0x00000000e011f570@8f52029, 4): success
test TestNative.testNativeCapacity(TestNative$$Lambda$184/0x00000000e011f6d0@14fe0d3d, 4): success
test TestNative.testNativeCapacity(TestNative$$Lambda$185/0x00000000e011f830@746dabc9, 8): success
test TestNative.testNativeCapacity(TestNative$$Lambda$186/0x00000000e011f990@336080a1, 8): success

===============================================
java/foreign/TestNative.java
Total tests run: 19, Passes: 16, Failures: 3, Skips: 0
===============================================
```

**Comment by fengxue-IS** [comment]
Closing this as the failures are due to JVM native implementation of `ProgrammableInvoker`, not part of OJDK MH issue.
Currently this test has already been excluded. Will re-evaluate when `foreign.CLinker` changes have been merged.
