### ISSUE TITLE
[OJDK MH] ClassCastException: ConcurrentLinkedQueue$Node incompatible with VarHandleReferences$FieldInstanceReadWrite

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#12544]
### Error

Test TAP Results: https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_ppc64le_linux_OpenJDK/367/tapResults/

The above build was run last night (22 Apr 21).

```
Exception in thread "main" java.lang.ClassCastException: java.util.concurrent.ConcurrentLinkedQueue$Node incompatible with java.lang.invoke.VarHandleReferences$FieldInstanceReadWrite
	at java.base/java.lang.invoke.VarHandleReferences$FieldInstanceReadWrite.set(VarHandleReferences.java:147)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$VH/0x0000000000000000.invoke_MT(LambdaForm$VH)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:361)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:283)
	at org.testng.ClassMethodMap.<init>(ClassMethodMap.java:42)
	at org.testng.TestRunner.initMethods(TestRunner.java:444)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

### Failing Test Targets

1. `jit_jitt_0` [sanity.functional] 
2. `jit_jitt_1` [sanity.functional] 
3. `jit_jitt_2` [sanity.functional] 
4. `jit_jitt_3` [sanity.functional] 

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
@nbhuiyan This failure looks identical to https://github.com/eclipse/openj9/issues/12427. 
fyi @liqunl @jdmpapin

**Comment by nbhuiyan** [comment]
Looking into it

**Comment by babsingh** [comment]
Also seen in 
- https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK_testList_0/182/consoleFull
- https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK_testList_1/182/consoleFull

for test targets:
- `JCL_Test_JITHelpers_0`
- `JCL_Test_JITHelpers_1`

**Comment by babsingh** [comment]
As per @nbhuiyan, this failure cannot be reproduced. Thus, I am closing this issue. This issue can be reopened if the failure reoccurs.
