### ISSUE TITLE
OJDK MH: jsr292Test_* failures

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#12571]
### Error

This issue documents the `jsr292Test_*` failures seen after resolution of the seg fault in https://github.com/eclipse/openj9/issues/11936. The below failures are seen with JDK16+.

`testBindTo` passes in RI but fails in OJ9 with OJDK MHs enabled.

**OJ9 with OJDK MHs enabled:**
```
FAILED: testBindTo
FAILED: testAll
FAILED: testPermuteArguments
FAILED: testIfVirtualHandleTestIsJitted
FAILED: testIfConstructorHandleIsJitted
FAILED: testIfRecieverBoundHandleTestIsJitted
FAILED: testIfInterfaceHandleIsJitted
FAILED: testIfDirectHandleTestIsJitted
```

**Reference Implementation (RI):**
```
FAILED: testAll
FAILED: testPermuteArguments
FAILED: testIfVirtualHandleTestIsJitted
FAILED: testIfConstructorHandleIsJitted
FAILED: testIfRecieverBoundHandleTestIsJitted
FAILED: testIfInterfaceHandleIsJitted
FAILED: testIfDirectHandleTestIsJitted
```

### Failing Test Targets

1. `jsr292Test_0` [extended.functional]
2. `jsr292Test_1` [extended.functional]
3. `jsr292Test_JitCount0_0` [extended.functional]

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
**Reference Implementation (RI):**
```
FAILED: testAll
    java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
        at com.ibm.j9.jsr292.AsTypeTest.testAll(AsTypeTest.java:102)

FAILED: testPermuteArguments
    java.lang.NullPointerException: Cannot invoke "java.lang.invoke.LambdaForm$Name.isParam()" because "name" is null
        at java.base/java.lang.invoke.LambdaFormBuffer.endEdit(LambdaFormBuffer.java:304)
        at java.base/java.lang.invoke.LambdaFormEditor.dupArgumentForm(LambdaFormEditor.java:585)
        at java.base/java.lang.invoke.MethodHandles.permuteArguments(MethodHandles.java:4868)
        at com.ibm.j9.jsr292.PermuteTest.testPermuteArguments(PermuteTest.java:966)

FAILED: testIfVirtualHandleTestIsJitted
    java.lang.ExceptionInInitializerError
        at com.ibm.j9.jsr292.VirtualHandleTest.testIfVirtualHandleTestIsJitted(VirtualHandleTest.java:42)
        ...
    Caused by: java.lang.RuntimeException
        at com.ibm.j9.jsr292.TestClass_VH.<clinit>(VirtualHandleTest.java:220)
        ... 25 more

FAILED: testIfConstructorHandleIsJitted
    java.lang.ExceptionInInitializerError
        at com.ibm.j9.jsr292.ConstructorHandleTest.testIfConstructorHandleIsJitted(ConstructorHandleTest.java:39)
        ...
    Caused by: java.lang.RuntimeException
        at com.ibm.j9.jsr292.TestClass.<clinit>(ConstructorHandleTest.java:69)
        ... 25 more

FAILED: testIfRecieverBoundHandleTestIsJitted
    java.lang.ExceptionInInitializerError
        at com.ibm.j9.jsr292.ReceiverBoundHandleTest.testIfRecieverBoundHandleTestIsJitted(ReceiverBoundHandleTest.java:39)
        ...
    Caused by: java.lang.RuntimeException
        at com.ibm.j9.jsr292.TestClass_RBH.<clinit>(ReceiverBoundHandleTest.java:68)
        ... 25 more

FAILED: testIfInterfaceHandleIsJitted
    java.lang.ExceptionInInitializerError
        at com.ibm.j9.jsr292.InterfaceHandleTest.testIfInterfaceHandleIsJitted(InterfaceHandleTest.java:47)
        ...
    Caused by: java.lang.RuntimeException
        at com.ibm.j9.jsr292.TestClass_IH.<clinit>(InterfaceHandleTest.java:242)
        ... 25 more

FAILED: testIfDirectHandleTestIsJitted
    java.lang.ExceptionInInitializerError
        at com.ibm.j9.jsr292.DirectHandleTest.testIfDirectHandleTestIsJitted(DirectHandleTest.java:39)
        ...
    Caused by: java.lang.RuntimeException
        at com.ibm.j9.jsr292.TestClass_DH.<clinit>(DirectHandleTest.java:68)
        ... 25 more
```

**Comment by babsingh** [comment]
**OJ9 with OJDK MHs enabled:**
```
FAILED: testBindTo
    Caused by: java.lang.AssertionError: The test case failed to throw an NullPointerException in the case of null objects
        at org.testng.Assert.fail(Assert.java:96)
        at com.ibm.j9.jsr292.MethodHandleTest.testBindTo(MethodHandleTest.java:1400)

FAILED: testAll
    java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
        at com.ibm.j9.jsr292.AsTypeTest.testAll(AsTypeTest.java:102)

FAILED: testPermuteArguments
    java.lang.NullPointerException
        at java.base/java.lang.invoke.LambdaFormBuffer.endEdit(LambdaFormBuffer.java:304)
        at java.base/java.lang.invoke.LambdaFormEditor.dupArgumentForm(LambdaFormEditor.java:585)
        at java.base/java.lang.invoke.MethodHandles.permuteArguments(MethodHandles.java:4877)
        at com.ibm.j9.jsr292.PermuteTest.testPermuteArguments(PermuteTest.java:966)

FAILED: testIfVirtualHandleTestIsJitted
    java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
        at com.ibm.j9.jsr292.VirtualHandleTest.testIfVirtualHandleTestIsJitted(VirtualHandleTest.java:44)

FAILED: testIfConstructorHandleIsJitted
    java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
        at com.ibm.j9.jsr292.ConstructorHandleTest.testIfConstructorHandleIsJitted(ConstructorHandleTest.java:41)

FAILED: testIfRecieverBoundHandleTestIsJitted
    java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
        at com.ibm.j9.jsr292.ReceiverBoundHandleTest.testIfRecieverBoundHandleTestIsJitted(ReceiverBoundHandleTest.java:41)

FAILED: testIfInterfaceHandleIsJitted
    java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
        at com.ibm.j9.jsr292.InterfaceHandleTest.testIfInterfaceHandleIsJitted(InterfaceHandleTest.java:49)

FAILED: testIfDirectHandleTestIsJitted
    java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
        at com.ibm.j9.jsr292.DirectHandleTest.testIfDirectHandleTestIsJitted(DirectHandleTest.java:41)
```

**Comment by babsingh** [comment]
### Summary

- `testBindTo` passes in `RI` but fails in `OJ9 with OJDK MHs enabled`. `NullPointerException` is not thrown with `OJ9 with OJDK MHs enabled`.


- `OJ9 with OJDK MHs enabled` matches `RI` for the following test cases:
```
-- testAll
-- testPermuteArguments
```

- For the below test cases, `RI` throws an `ExceptionInInitializerError` caused by a `RuntimeException` whereas `OJ9 with OJDK MHs enabled` throws an `AssertionError`:
```
-- testIfVirtualHandleTestIsJitted
-- testIfConstructorHandleIsJitted
-- testIfRecieverBoundHandleTestIsJitted
-- testIfInterfaceHandleIsJitted
-- testIfDirectHandleTestIsJitted
```

**Comment by fengxue-IS** [comment]
`testBindTo` failed in OpenJ9 with OJDK MH because we are not checking for null receiver during `linkToStaticSpecial` INL when the method dispatch is an `invokeSpecial`, will create new PR to address this issue.

```
testIfVirtualHandleTestIsJitted
testIfConstructorHandleIsJitted
testIfRecieverBoundHandleTestIsJitted
testIfInterfaceHandleIsJitted
testIfDirectHandleTestIsJitted
```
failed in OpenJDK because the test is relying on internal parameter `Throwable.walkback`.
OpenJ9 w/ OJDK MH have different class names for the MH subclasses (ie. DirectMethodHandle instead of DirectHandle)

I think these tests should be excluded for OpenJ9 with OJDK MH

**Comment by DanHeidinga** [comment]
I agree - the `testIfXisJitted` tests are very OpenJ9-specific as they also rely on the walkback field holding PCs that change when a method is jitted.  

> I think these tests should be excluded for OpenJ9 with OJDK MH

+1
