### ISSUE TITLE
JDK17 : java/lang/ProcessBuilder/Basic.java#id0 - JVMJ9VM007W Command-line option unrecognised: -Xlog:all=warning:stdout

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12580]
Failure link
------------

From an internal build `Test_openjdk17_j9_sanity.openjdk_s390x_linux/17/`
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment AdoptOpenJDK-17+18-202104280416 (build 17+18-202104280416)
Eclipse OpenJ9 VM AdoptOpenJDK-17+18-202104280416 (build master-8ce509b6e, JRE 17 Linux s390x-64-Bit Compressed References 20210427_43 (JIT enabled, AOT enabled)
OpenJ9   - 8ce509b6e
OMR      - 746acf8b5
JCL      - 1dc21088e3 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_lang_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=s390x_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-s390x-openj9%2F43%2FOpenJDK-debugimage_s390x_linux_openj9_2021-04-28-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-s390x-openj9%2F43%2FOpenJDK-testimage_s390x_linux_openj9_2021-04-28-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-s390x-openj9%2F43%2FOpenJDK-jdk_s390x_linux_openj9_2021-04-28-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-s390x-openj9%2F43%2FOpenJDK-jre_s390x_linux_openj9_2021-04-28-03-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=17&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-04-28T05:12:01.632Z] Running test jdk_lang_0 ...
[2021-04-28T05:12:01.632Z] ===============================================
[2021-04-28T05:12:01.632Z] jdk_lang_0 Start Time: Tue Apr 27 22:12:00 2021 Epoch Time (ms): 1619586720196
[2021-04-28T05:12:01.632Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-04-28T05:12:01.632Z] 
[2021-04-28T05:12:01.632Z] Attempting to destroy all caches in cacheDir /home/jenkins/javasharedresources/
[2021-04-28T05:12:01.632Z] 
[2021-04-28T05:12:01.632Z] JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
[2021-04-28T05:12:01.632Z] JVMSHRC807I Non-compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xcompressedrefs if you want to destroy a compressed references cache.
[2021-04-28T05:12:01.632Z] JVMSHRC005I No shared class caches available
[2021-04-28T05:12:01.632Z] cache cleanup done
[2021-04-28T05:12:01.632Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2021-04-28T05:12:01.632Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

[2021-04-28T05:28:28.381Z] --------------------------------------------------
[2021-04-28T05:38:31.167Z] TEST: java/lang/ProcessBuilder/Basic.java#id0
[2021-04-28T05:38:31.167Z] TEST JDK: /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux/openjdkbinary/j2sdk-image

[2021-04-28T05:38:31.169Z] END Child output.
[2021-04-28T05:38:31.169Z] Unexpected child output:
[2021-04-28T05:38:31.169Z] JVMJ9VM007W Command-line option unrecognised: -Xlog:all=warning:stdout

[2021-04-28T05:38:31.170Z] Passed = 9009, failed = 1
[2021-04-28T05:38:31.170Z] 
[2021-04-28T05:38:31.170Z] STDERR:
[2021-04-28T05:38:31.170Z] JVMJ9VM007W Command-line option unrecognised: -Xlog:all=warning:stderr

[2021-04-28T05:38:31.171Z] java.lang.AssertionError: Some tests failed
[2021-04-28T05:38:31.171Z] 	at Basic.main(Basic.java:2826)
[2021-04-28T05:38:31.171Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-28T05:38:31.171Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-28T05:38:31.171Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-28T05:38:31.171Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-28T05:38:31.171Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-04-28T05:38:31.171Z] 	at java.base/java.lang.Thread.run(Thread.java:878)
[2021-04-28T05:38:31.171Z] 
[2021-04-28T05:38:31.171Z] JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
[2021-04-28T05:38:31.171Z] JavaTest Message: shutting down test
[2021-04-28T05:38:31.171Z] 
[2021-04-28T05:38:31.171Z] STATUS:Failed.`main' threw exception: java.lang.AssertionError: Some tests failed
```

**Comment by pshipton** [comment]
We'll have to decide if we want to exclude the sub-test, or implement what it needs to pass.

**Comment by JasonFengJ9** [comment]
Also noted by https://github.com/eclipse-openj9/openj9/issues/13148, the unrecognised warning message doesn't seem cause the failure.
From an internal build `Test_openjdk17_j9_sanity.openjdk_s390x_linux/40/`
```
openjdk version "17-beta" 2021-09-14
OpenJDK Runtime Environment Temurin-17+18-202107070511 (build 17-beta+18-202107070511)
Eclipse OpenJ9 VM Temurin-17+18-202107070511 (build master-738370398, JRE 17 Linux s390x-64-Bit Compressed References 20210706_11 (JIT enabled, AOT enabled)
OpenJ9   - 738370398
OMR      - 42d7f6246
JCL      - e681712e93 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_lang_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-s390x-openj9%2F11%2FSemeru-debugimage_s390x_linux_JDK17_2021-07-07-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-s390x-openj9%2F11%2FSemeru-jre_s390x_linux_JDK17_2021-07-07-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-s390x-openj9%2F11%2FSemeru-testimage_s390x_linux_JDK17_2021-07-07-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-s390x-openj9%2F11%2FSemeru-jdk_s390x_linux_JDK17_2021-07-07-03-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)
```
02:27:14  --------------------------------------------------
02:27:43  TEST: java/lang/ProcessBuilder/Basic.java#id0

02:27:43  >'-1'< not equal to '10'
02:27:43  java.lang.Throwable
02:27:43  	at java.base/java.lang.Thread.dumpStack(Thread.java:554)
02:27:43  	at Basic.fail(Basic.java:2814)
02:27:43  	at Basic.fail(Basic.java:2815)
02:27:43  	at Basic.equal(Basic.java:2821)
02:27:43  	at Basic$12.run(Basic.java:2214)
02:27:43  java.lang.AssertionError: Some tests failed
02:27:43  	at Basic.main(Basic.java:2826)
02:27:43  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:27:43  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
02:27:43  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:27:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
02:27:43  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
02:27:43  	at java.base/java.lang.Thread.run(Thread.java:883)
02:27:43  
02:27:43  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed

03:04:56  --------------------------------------------------
03:05:08  TEST: java/lang/ProcessBuilder/Basic.java#id1

03:05:08  >'-1'< not equal to '74'
03:05:08  java.lang.Throwable
03:05:08  	at java.base/java.lang.Thread.dumpStack(Thread.java:554)
03:05:08  	at Basic.fail(Basic.java:2814)
03:05:08  	at Basic.fail(Basic.java:2815)
03:05:08  	at Basic.equal(Basic.java:2821)
03:05:08  	at Basic$12.run(Basic.java:2214)
```

**Comment by pshipton** [comment]
Resolved by https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/12 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/343
