### ISSUE TITLE
JDK17 (aarch64_linux) : java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java - StackOverflowError at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12605]
Failure link
------------

From an internal build `Test_openjdk17_j9_sanity.openjdk_aarch64_linux/13/`:
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment AdoptOpenJDK-17+18-202104300408 (build 17+18-202104300408)
Eclipse OpenJ9 VM AdoptOpenJDK-17+18-202104300408 (build master-cc51e1af9, JRE 17 Linux aarch64-64-Bit Compressed References 20210430_37 (JIT enabled, AOT enabled)
OpenJ9   - cc51e1af9
OMR      - bb9ac28f7
JCL      - 1dc21088e3 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_util_1&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=aarch64_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F37%2FOpenJDK-jre_aarch64_linux_openj9_2021-04-30-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F37%2FOpenJDK-debugimage_aarch64_linux_openj9_2021-04-30-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F37%2FOpenJDK-jdk_aarch64_linux_openj9_2021-04-30-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9%2F37%2FOpenJDK-testimage_aarch64_linux_openj9_2021-04-30-03-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=17&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-04-30T05:57:26.740Z] Running test jdk_util_1 ...
[2021-04-30T05:57:26.740Z] ===============================================
[2021-04-30T05:57:26.740Z] jdk_util_1 Start Time: Fri Apr 30 01:57:25 2021 Epoch Time (ms): 1619762245633
[2021-04-30T05:57:26.740Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-04-30T05:57:26.740Z] JVMSHRC005I No shared class caches available
[2021-04-30T05:57:26.740Z] JVMSHRC005I No shared class caches available
[2021-04-30T05:57:26.740Z] cache cleanup done
[2021-04-30T05:57:26.740Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2021-04-30T05:57:26.741Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2021-04-30T06:14:55.500Z] --------------------------------------------------
[2021-04-30T06:14:55.500Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java

[2021-04-30T06:14:55.508Z] java.lang.StackOverflowError
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-04-30T06:14:55.508Z] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2021-04-30T06:14:55.508Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:238)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.StreamTestScenario$17.run(StreamTestScenario.java:208)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.StreamTestScenario.run(StreamTestScenario.java:272)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:404)
[2021-04-30T06:14:55.508Z] 	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-30T06:14:55.508Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-30T06:14:55.508Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-04-30T06:14:55.508Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-04-30T06:14:55.508Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-04-30T06:14:55.508Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-04-30T06:14:55.508Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-04-30T06:14:55.508Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-04-30T06:14:55.508Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-04-30T06:14:55.508Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-04-30T06:14:55.508Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-04-30T06:14:55.508Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-04-30T06:14:55.508Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-04-30T06:14:55.508Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-04-30T06:14:55.508Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-04-30T06:14:55.508Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-04-30T06:14:55.508Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-04-30T06:14:55.508Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-04-30T06:14:55.508Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-04-30T06:14:55.508Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-04-30T06:14:55.508Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-30T06:14:55.508Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-30T06:14:55.508Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-30T06:14:55.508Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-04-30T06:14:55.508Z] 	at java.base/java.lang.Thread.run(Thread.java:878)
[2021-04-30T06:14:55.508Z] Caused by: java.lang.StackOverflowError
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2021-04-30T06:14:55.508Z] 	at java.base/java.util.stream.Referenc

[2021-04-30T06:14:55.528Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 79
[2021-04-30T06:14:55.528Z] --------------------------------------------------
[2021-04-30T06:19:54.638Z] Test results: passed: 884; failed: 1
[2021-04-30T06:20:08.473Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2021-04-30T06:20:08.473Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/output_16197582042316/jdk_util_1/work
[2021-04-30T06:20:08.473Z] Error: Some tests failed or other problems occurred.
[2021-04-30T06:20:08.473Z] 
[2021-04-30T06:20:08.473Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
@knn-k fyi

**Comment by knn-k** [comment]
I don't think I have seen this failure before in https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/ .

**Comment by knn-k** [comment]
It seems I don't have the permission for running the test in Grinder.

**Comment by smlambert** [comment]
You should be able to replace the first part of a Rerun in Grinder link and swap it to any Jenkins server that has a Grinder job:

So replacing:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?...

can be swapped to:
https://ci.eclipse.org/openj9/job/Grinder/parambuild/?...

**Comment by JasonFengJ9** [comment]
@knn-k an internal sample grinder link for this failure is at `Grinder/15173/` (passed).

**Comment by knn-k** [comment]
@smlambert @JasonFengJ9 Sorry for my late response.  I was on vacation.

**Comment by JasonFengJ9** [comment]
It is observed at `Test_openjdk17_j9_sanity.openjdk_aarch64_linux/39/` (`ub18-aarch64-3`)
```
00:51:13  openjdk version "17-beta" 2021-09-14
00:51:13  OpenJDK Runtime Environment Temurin-17+35-202108250407 (build 17-beta+35-202108250407)
00:51:13  Eclipse OpenJ9 VM Temurin-17+35-202108250407 (build master-14a7e4268, JRE 17 Linux aarch64-64-Bit Compressed References 20210825_16 (JIT enabled, AOT enabled)
00:51:13  OpenJ9   - 14a7e4268
00:51:13  OMR      - ab7034261
00:51:13  JCL      - a3ace8a9b6 based on jdk-17+35)

[2021-08-25T06:15:42.230Z] Running test jdk_util_1 ...
[2021-08-25T06:15:42.230Z] ===============================================
[2021-08-25T06:15:42.230Z] jdk_util_1 Start Time: Wed Aug 25 02:15:39 2021 Epoch Time (ms): 1629872139740
[2021-08-25T06:15:42.230Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-08-25T06:15:42.230Z] JVMSHRC005I No shared class caches available
[2021-08-25T06:15:42.230Z] JVMSHRC005I No shared class caches available
[2021-08-25T06:15:42.230Z] cache cleanup done
[2021-08-25T06:15:42.230Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2021-08-25T06:15:42.230Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2021-08-25T06:41:23.008Z] --------------------------------------------------
[2021-08-25T06:41:23.008Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java

[2021-08-25T06:41:23.024Z] test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("ArrayList.asList:0..1000", java.util.stream.TestData$AbstractTestData$RefTestData@68a5778b): failure
[2021-08-25T06:41:23.024Z] java.lang.AssertionError: 1 failure(s) for test data: RefTestData[ArrayList.asList:0..1000]
[2021-08-25T06:41:23.024Z] 1: java.lang.Error: PAR_STREAM_SPLITERATOR_STREAM_TO_ARRAY: java.lang.StackOverflowError
[2021-08-25T06:41:23.024Z] java.lang.StackOverflowError
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-08-25T06:41:23.024Z] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2021-08-25T06:41:23.024Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.Nodes.collect(Nodes.java:325)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:111)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:583)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.StreamTestScenario$13.run(StreamTestScenario.java:163)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.StreamTestScenario.run(StreamTestScenario.java:272)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:404)
[2021-08-25T06:41:23.024Z] 	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-08-25T06:41:23.024Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-08-25T06:41:23.024Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-08-25T06:41:23.024Z] 	at org.testng.TestRunner$$Lambda$100/0x0000000000000000.accept(Unknown Source)
[2021-08-25T06:41:23.024Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-08-25T06:41:23.024Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-08-25T06:41:23.024Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-08-25T06:41:23.024Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-08-25T06:41:23.024Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-08-25T06:41:23.024Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-08-25T06:41:23.024Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-08-25T06:41:23.024Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-08-25T06:41:23.024Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-08-25T06:41:23.024Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-08-25T06:41:23.024Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-08-25T06:41:23.024Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-08-25T06:41:23.024Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-08-25T06:41:23.024Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-08-25T06:41:23.024Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-08-25T06:41:23.024Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-08-25T06:41:23.024Z] 	at java.base/java.lang.
[2021-08-25T06:41:23.024Z] 
[2021-08-25T06:41:23.024Z] ...
[2021-08-25T06:41:23.024Z] Output overflow:

[2021-08-25T06:41:23.057Z] ===============================================
[2021-08-25T06:41:23.057Z] java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
[2021-08-25T06:41:23.057Z] Total tests run: 180, Passes: 179, Failures: 1, Skips: 0
[2021-08-25T06:41:23.057Z] ===============================================
[2021-08-25T06:41:23.057Z] 
[2021-08-25T06:41:23.057Z] STDERR:
[2021-08-25T06:41:23.057Z] WARNING: Using incubator modules: jdk.incubator.foreign
[2021-08-25T06:41:23.057Z] java.lang.Exception: failures: 1
[2021-08-25T06:41:23.057Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2021-08-25T06:41:23.057Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-08-25T06:41:23.057Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-08-25T06:41:23.063Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-08-25T06:41:23.063Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-08-25T06:41:23.063Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-08-25T06:41:23.063Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-08-25T06:41:23.063Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-08-25T06:41:23.063Z] 
[2021-08-25T06:41:23.063Z] JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
[2021-08-25T06:41:23.063Z] JavaTest Message: shutting down test
[2021-08-25T06:41:23.063Z] 
[2021-08-25T06:41:23.063Z] STATUS:Failed.`main' threw exception: java.lang.Exception: failures: 1

[2021-08-25T06:41:23.063Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2021-08-25T06:41:23.063Z] --------------------------------------------------
[2021-08-25T06:45:15.846Z] Test results: passed: 885; failed: 1
[2021-08-25T06:45:38.605Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2021-08-25T06:45:38.605Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/aqa-tests/TKG/output_16298673518946/jdk_util_1/work
[2021-08-25T06:45:38.605Z] Error: Some tests failed or other problems occurred.
[2021-08-25T06:45:38.605Z] 
[2021-08-25T06:45:38.605Z] jdk_util_1_FAILED
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=ibm&BUILD_LIST=openjdk&PLATFORM=aarch64_linux&TARGET=jdk_util_1)

**Comment by 0xdaryl** [comment]
Not reproduced and the failure that was observed is already fixed.  Closing.
