### ISSUE TITLE
JDK8 MacOS J9vmTest_3/4_FAILED - *** Test FAILED *** (j9vm.test.invalidclasspath.SetClasspathTest)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12628]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/27/` (`mac11x64rt01`):
```
openjdk version "1.8.0_292-internal"
OpenJDK Runtime Environment (build 1.8.0_292-internal-202105050232-b10)
Eclipse OpenJ9 VM (build master-8a6e1df5c, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210504_121 (JIT enabled, AOT enabled)
OpenJ9   - 8a6e1df5c
OMR      - 79c52c726
JCL      - 53fb2c16 based on jdk8u292-b10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=J9vmTest_3&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_sanity.functional_x86-64_mac&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=functional&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-64_mac&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F121%2FOpenJDK8U-testimage_x64_mac_openj9_2021-05-05-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F121%2FOpenJDK8U-jre_x64_mac_openj9_2021-05-05-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F121%2FOpenJDK8U-jdk_x64_mac_openj9_2021-05-05-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F121%2FOpenJDK8U-debugimage_x64_mac_openj9_2021-05-05-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=50&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-05-05T04:07:52.105Z] Running test J9vmTest_3 ...
[2021-05-05T04:07:52.105Z] ===============================================
[2021-05-05T04:07:52.105Z] J9vmTest_3 Start Time: Wed May  5 00:07:47 2021 Epoch Time (ms): 1620187667859
[2021-05-05T04:07:52.105Z] "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-05T04:07:52.105Z] 
[2021-05-05T04:07:52.105Z] Attempting to destroy all caches in cacheDir /Users/jenkins/javasharedresources/
[2021-05-05T04:07:52.105Z] 
[2021-05-05T04:07:52.105Z] JVMSHRC806I Compressed references persistent shared cache "Foo" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
[2021-05-05T04:07:52.105Z] JVMSHRC005I No shared class caches available
[2021-05-05T04:07:52.105Z] cache cleanup done
[2021-05-05T04:07:52.105Z] variation: Mode501
[2021-05-05T04:07:52.106Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 

[2021-05-05T04:10:15.388Z] command: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m -Xshareclasses:name=setclasspathtest,printAllStats=orphan+romclass   -Xbootclasspath:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/jre/lib/default/jclSC180/vm.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/jre/lib/se-service.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/jre/lib/rt.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/jre/lib/resources.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/jre/lib/jsse.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/jre/lib/charsets.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/jre/lib/jce.jar -classpath /Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdk-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_testList_1/openjdk-tests/TKG/../TKG/lib/asm-all.jar  j9vm.test.invalidclasspath.SetClasspathTest 
[2021-05-05T04:10:15.388Z] 
[2021-05-05T04:10:15.388Z] JVMSHRC023E Cache does not exist
[2021-05-05T04:10:15.388Z] no-zero exit value: 1
[2021-05-05T04:10:15.388Z] 
[2021-05-05T04:10:15.388Z] 
[2021-05-05T04:10:15.388Z] Error:: Did not find ROMClass entry for TestA1 in shared cache
[2021-05-05T04:10:15.388Z] Error:: Did not find ROMClass entry for TestB3 in shared cache
[2021-05-05T04:10:15.388Z] Error:: Did not find ROMClass entry for TestA4 in shared cache
[2021-05-05T04:10:15.388Z] Error:: Did not find Orphan entry for TestA2 in shared cache
[2021-05-05T04:10:15.388Z] Error:: Did not find Orphan entry for TestB1 in shared cache
[2021-05-05T04:10:15.388Z] Error:: Did not find Orphan entry for TestB2 in shared cache
[2021-05-05T04:10:15.388Z] Error:: Did not find Orphan entry for TestC1 in shared cache
[2021-05-05T04:10:15.388Z] Error:: Did not find Orphan entry for TestA3 in shared cache
[2021-05-05T04:10:15.388Z] *** Test FAILED *** (j9vm.test.invalidclasspath.SetClasspathTest)

[2021-05-05T04:12:10.771Z] 70 passed / 1 failed
[2021-05-05T04:12:10.771Z] 
[2021-05-05T04:12:10.771Z] J9vmTest_3_FAILED
[2021-05-05T04:12:10.771Z] 
```

fyi @hangshao0

**Comment by JasonFengJ9** [comment]
Another slightly different failure at JDK11 MacOS `Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/26/` (`mac11x64rt07`)
```
[2021-05-05T02:22:14.460Z] Running test cmdLineTester_SCCommandLineOptionTests_0 ...
[2021-05-05T02:22:14.460Z] ===============================================
[2021-05-05T02:22:14.460Z] cmdLineTester_SCCommandLineOptionTests_0 Start Time: Tue May  4 22:22:13 2021 Epoch Time (ms): 1620181333218
[2021-05-05T02:22:14.460Z] "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-05T02:22:14.460Z] JVMSHRC005I No shared class caches available
[2021-05-05T02:22:14.460Z] JVMSHRC005I No shared class caches available
[2021-05-05T02:22:14.460Z] cache cleanup done
[2021-05-05T02:22:14.460Z] variation: Mode110
[2021-05-05T02:22:14.460Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

[2021-05-05T02:22:18.311Z] Testing: nameOption3
[2021-05-05T02:22:18.311Z] Test start time: 2021/05/04 22:22:18 Eastern Standard Time
[2021-05-05T02:22:18.311Z] Running command: sh nameOption3.sh /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin
[2021-05-05T02:22:18.311Z] Time spent starting: 13 milliseconds
[2021-05-05T02:22:19.285Z] Time spent executing: 894 milliseconds
[2021-05-05T02:22:19.285Z] Test result: FAILED
[2021-05-05T02:22:19.285Z]  [OUT] Hello, world!
[2021-05-05T02:22:19.285Z]  [OUT] TEST PASSED
[2021-05-05T02:22:19.285Z]  [OUT] nameOption3: TEST FAILED
[2021-05-05T02:22:19.285Z]  [OUT] nameOption3: Expected to find the cache name
[2021-05-05T02:22:19.285Z]  [OUT] TEST PASSED
[2021-05-05T02:22:19.285Z]  [ERR] JVMSHRC023E Cache does not exist
[2021-05-05T02:22:19.285Z] >> Success condition was found: [Output match: TEST PASSED]
[2021-05-05T02:22:19.285Z] >> Failure condition was found: [Output match: TEST FAILED]
[2021-05-05T02:22:19.285Z] >> Failure condition was not found: [Output match: Error:]
[2021-05-05T02:22:19.285Z] >> Failure condition was not found: [Output match: Unhandled Exception]
[2021-05-05T02:22:19.285Z] >> Failure condition was not found: [Output match: Exception:]
```

**Comment by JasonFengJ9** [comment]
Adding another JDK11 MacOS SCC related failure here until investigation shows otherwise.
From an internal build `Test_openjdk11_j9_extended.functional_x86-64_mac_testList_2/27/` (`mac11x64rt04 `)
```
[2021-05-05T02:07:53.393Z] Running test testSCCacheManagement_0 ...
[2021-05-05T02:07:53.393Z] ===============================================
[2021-05-05T02:07:53.393Z] testSCCacheManagement_0 Start Time: Tue May  4 22:07:52 2021 Epoch Time (ms): 1620180472698
[2021-05-05T02:07:53.393Z] "/Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_mac_testList_2/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_mac_testList_2/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-05T02:07:53.393Z] 
[2021-05-05T02:07:53.393Z] Attempting to destroy all caches in cacheDir /Users/jenkins/javasharedresources/
[2021-05-05T02:07:53.393Z] 
[2021-05-05T02:07:53.393Z] JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
[2021-05-05T02:07:53.393Z] JVMSHRC005I No shared class caches available
[2021-05-05T02:07:53.393Z] cache cleanup done
[2021-05-05T02:07:53.393Z] variation: NoOptions
[2021-05-05T02:07:53.393Z] JVM_OPTIONS:  

[2021-05-05T02:25:26.449Z] There were 7 errors:
[2021-05-05T02:25:26.449Z] 1) testCreationAndCompatibility(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: Non-Persistent cache 'Bar' was not found to be compatible
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.checkOutputForCompatibleCache(TestUtils.java:1024)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.checkOutputForCompatibleNonPersistentCache(TestUtils.java:965)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestCreationAndCompatibility.main(TestCreationAndCompatibility.java:54)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testCreationAndCompatibility(TestOptionsBase.java:71)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-05T02:25:26.449Z] 2) testSharedCacheJvmtiAPI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: iterateSharedCacheFunction ffailed, Invalid number of cache found	expected: 5	found: 6
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheJvmtiAPI.main(TestSharedCacheJvmtiAPI.java:111)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJvmtiAPI(TestOptionsBase.java:119)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-05T02:25:26.449Z] 3) testSharedCacheJavaAPI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: SharedClassUtilities.getSharedCacheInfo failed: Invalid number of cache found	expected: 7	found: 8
[2021-05-05T02:25:26.449Z]  oldCacheCount is 0
[2021-05-05T02:25:26.449Z]  persistentGroupAccessCount is 1
[2021-05-05T02:25:26.449Z]  nonpersistentGroupAccessCount is 1
[2021-05-05T02:25:26.449Z]  persistentCount is 3
[2021-05-05T02:25:26.449Z]  nonpersistentCount is 1
[2021-05-05T02:25:26.449Z]  snapshotCount is 1
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheJavaAPI.main(TestSharedCacheJavaAPI.java:208)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJavaAPI(TestOptionsBase.java:120)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-05T02:25:26.449Z] 4) testExpireDestroyOnCorruptCache(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: No file found at '/Users/jenkins/javasharedresources/C290M11F1A64P_Foo_G41L00'
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestExpireDestroyOnCorruptCache.main(TestExpireDestroyOnCorruptCache.java:60)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testExpireDestroyOnCorruptCache(TestOptionsBase.java:122)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-05T02:25:26.449Z] 5) testSharedCacheEnableBCI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: No file found at '/Users/jenkins/javasharedresources/C290M11F1A64P_testSharedCacheEnableBCI_G41L00'
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheEnableBCI.runTest1(TestSharedCacheEnableBCI.java:92)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheEnableBCI.main(TestSharedCacheEnableBCI.java:61)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheEnableBCI(TestOptionsBase.java:132)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-05T02:25:26.449Z] 6) testSharedCacheEnableBCI(tests.sharedclasses.options.junit.TestOptionsControlDir)tests.sharedclasses.TestFailedException: Mismatch in number of ROMClasses. Without enableBCI, # ROMClasses: 766With enableBCI, # ROMClasses: 791.
[2021-05-05T02:25:26.449Z] Maximum allowed difference is 10
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheEnableBCI.runTest1(TestSharedCacheEnableBCI.java:146)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheEnableBCI.main(TestSharedCacheEnableBCI.java:61)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheEnableBCI(TestOptionsBase.java:132)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-05T02:25:26.449Z] 7) testSharedCacheEnableBCI(tests.sharedclasses.options.junit.TestOptionsCacheDir)tests.sharedclasses.TestFailedException: Mismatch in number of ROMClasses. Without enableBCI, # ROMClasses: 766With enableBCI, # ROMClasses: 791.
[2021-05-05T02:25:26.449Z] Maximum allowed difference is 10
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheEnableBCI.runTest1(TestSharedCacheEnableBCI.java:189)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.TestSharedCacheEnableBCI.main(TestSharedCacheEnableBCI.java:61)
[2021-05-05T02:25:26.449Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheEnableBCI(TestOptionsBase.java:132)
[2021-05-05T02:25:26.449Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-05T02:25:26.450Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-05T02:25:26.450Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-05T02:25:26.450Z] 
[2021-05-05T02:25:26.450Z] FAILURES!!!
[2021-05-05T02:25:26.450Z] Tests run: 168,  Failures: 0,  Errors: 7
[2021-05-05T02:25:26.450Z] 
[2021-05-05T02:25:27.634Z] 
[2021-05-05T02:25:27.634Z] testSCCacheManagement_0_FAILED
```

**Comment by hangshao0** [comment]
> [2021-05-05T02:22:19.285Z]  [OUT] nameOption3: TEST FAILED
> [2021-05-05T02:22:19.285Z]  [OUT] nameOption3: Expected to find the cache name
> [2021-05-05T02:22:19.285Z]  [OUT] TEST PASSED
> [2021-05-05T02:22:19.285Z]  [ERR] JVMSHRC023E Cache does not exist

GROUP_NAME is not there:
https://github.com/eclipse-openj9/openj9/blob/8a6e1df5c0cc2200c3f07efc04cc62946c9cdac1/test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/nameOption3.sh#L41-L44

It is set by 
https://github.com/eclipse-openj9/openj9/blob/8a6e1df5c0cc2200c3f07efc04cc62946c9cdac1/test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/nameOption3.sh#L32

https://github.com/eclipse-openj9/openj9/blob/8a6e1df5c0cc2200c3f07efc04cc62946c9cdac1/test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/cmdlineConfig.sh#L33

It is a setup issue.

**Comment by hangshao0** [comment]
About the SetClasspathTest failure, it is checking the status of an existing cache, but the cache is deleted somehow:

```
[2021-05-05T04:10:15.388Z] ... -Xshareclasses:name=setclasspathtest,printAllStats=orphan+romclass ...
[2021-05-05T04:10:15.388Z] 
[2021-05-05T04:10:15.388Z] JVMSHRC023E Cache does not exist
```

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin fyi https://github.com/eclipse-openj9/openj9/issues/12628#issuecomment-832772730

FYI these problems are showing up because we got some "new" macs added to jenkins.

**Comment by jdekonin** [comment]
The new Mac10 systems used the same setup scripts and they work fine.  Is it possible that MacOS 11 doesn't work in the same manner?  It could be that the setup/configuration isn't the same for Mac11, so I'll definitely review.

As for GROUP_NAME being blank, that cmdln appears to boil down to 
`id | awk '{print $2}' | awk '{print $1}' | cut -f 2 -d '(' | cut -f 1 -d ')'`  when I run that on either a mac10 or mac11 system I get the same answer `staff`.

**Comment by hangshao0** [comment]
About the GROUP_NAME issue on `cmdLineTester_SCCommandLineOptionTests_0`,  the failure reported here is 
`Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/26/` running on `mac11x64rt07`

It passed on the previous build `Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/25` on a different machine `mac11x64rt08`. 

Things must be different for these 2 machines.

**Comment by pshipton** [comment]
@JasonFengJ9 is this still a problem?

**Comment by JasonFengJ9** [comment]
No, no occurrence in recent builds.

Closing..
