### ISSUE TITLE
testOSMXBeanLocal win2012-x86-5 getTotalSwapSpaceSize() API returned -1, test failed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12621]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_0/313/
testOSMXBeanLocal_0
win2012-x86-5
```
[2021-05-04T06:24:01.896Z] FAILED: runTestOSMXBean
[2021-05-04T06:24:01.896Z] java.lang.AssertionError: Error: getTotalSwapSpaceSize() API returned -1, test failed
[2021-05-04T06:24:01.896Z] 	at org.testng.Assert.fail(Assert.java:96)
[2021-05-04T06:24:01.896Z] 	at org.openj9.test.management.TestOperatingSystemMXBean.test_SwapSpaceSizeAPIs(TestOperatingSystemMXBean.java:267)
[2021-05-04T06:24:01.896Z] 	at org.openj9.test.management.TestOperatingSystemMXBean.runTestOSMXBean(TestOperatingSystemMXBean.java:211)
[2021-05-04T06:24:01.896Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-04T06:24:01.896Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-04T06:24:01.896Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-04T06:24:01.896Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-05-04T06:24:01.896Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2021-05-04T06:24:01.896Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2021-05-04T06:24:01.896Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2021-05-04T06:24:01.896Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2021-05-04T06:24:01.896Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-05-04T06:24:01.896Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2021-05-04T06:24:01.896Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2021-05-04T06:24:01.896Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2021-05-04T06:24:01.896Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2021-05-04T06:24:01.896Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2021-05-04T06:24:01.896Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-05-04T06:24:01.896Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2021-05-04T06:24:01.896Z] 	at org.testng.TestNG.main(TestNG.java:1323)
```

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_1/312/
win2012-x86-5
testOSMXBeanLocal_0
testOSMXBeanLocal_1

@AdamBrousseau @jdekonin pls check the machine for swap space problems. Maybe a reboot is all that is required.

**Comment by jdekonin** [comment]
I marked the system offline as its currently running a job.  I'll login and see what processes are still running, although a cleanup job might have fixed this already.

**Comment by jdekonin** [comment]
System looked fine, and it had successfully passed the test pipeline that was running.  I rebooted for good measure and its back online in jenkins and ready for work.

**Comment by pshipton** [comment]
This is still happening on the same machine. @jdekonin did you check the Windows paging file? Maybe it needs to be recreated.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly_testList_1/295/
win2012-x86-5

**Comment by pshipton** [comment]
More
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_1/315/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_0/314/

**Comment by jdekonin** [comment]
Performance monitor cannot read the pagefile counters, so possibly a good indication its corrupted.

I attempted to recreate the paging files both of them.  There is a dedicated partition D for paging that is ~8G which at one point was determined not enough, so the additional 2G was added to C for paging for a total of ~10G.  But it seems that it doesn't matter which one (or both) I recreate Perfmon cannot read the pagefile counters.  Also attempted to locate a 10G pagefile on F (100G partition for jenkins user content), no luck there as well.

At this point, I think it easiest/quickest to just nuke the system and reclone from an existing functional one.  @rajdeepsingh1 can you manage that please.

**Comment by pshipton** [comment]
machines 1-3 and 6 seem stable. We often have issues with 4 and 5, so don't clone 4 to recreate 5.

**Comment by pshipton** [comment]
I'm going to keep the machine online until we're ready to re-clone it. I'd rather have this failure than not enough machines to run testing.

**Comment by pshipton** [comment]
Well, that said, there is nothing waiting this morning any more. I'll keep it offline today, but if it's not re-cloned I will enable it for the weekend.

**Comment by pshipton** [comment]
Great, thanks. I'll close this assuming fixed.

**Comment by pshipton** [comment]
@rajdeepsingh1 is there a difference on win2012-x86-5 from other machines with the amount of memory available? Some tests are failing on this machine because there isn't enough java heap allocated, which by default is 25% of the memory available.

I see the same failure on win2012-x86-10 as well, so the new machines may have the same problem.

**Comment by pshipton** [comment]
java/util/StringJoiner/StringJoinerTest.java is still failing on win2012-x86-5 due to OutOfMemoryError Java heap space

**Comment by pshipton** [comment]
I disabled win2012-x86-5 for now.

**Comment by rajdeepsingh1** [comment]
@pshipton 

win2012-x86-5 - D: virtual memory / paging space was set to "System Managed Size" which is the reason it was not utilizing the full space allocation. Corrected this and the page space is now statically set to 14180MB from 3244MB.

If all checks out, I will apply this to the new machines as well 

https://github.com/eclipse-openj9/openj9/issues/12664

**Comment by pshipton** [comment]
Testing win2012-x86-5 via grinder

testOSMXBeanLocal_0: https://openj9-jenkins.osuosl.org/job/Grinder/43 - passed
sanity.openjdk: https://openj9-jenkins.osuosl.org/job/Grinder/44

**Comment by pshipton** [comment]
Rajdeep said: the virtual memory is not statically assigned on some of the new machines so the allocation keeps changing instead of being fixed.

The machines are updated now. I'll close this assuming fixed and reopen if the problem is still seen in the nightly builds.
