### ISSUE TITLE
JDK11 jdk_util_0_FAILED - various test failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12647]
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.openjdk_x86-64_linux/59/`:
```
java version "11.0.11" 2021-04-20
Java(TM) SE Runtime Environment 11.0.10.0-IBM (build 11.0.11+9-202105070105)
Eclipse OpenJ9 VM 11.0.10.0-IBM (build master-295e06e0d, JRE 11 Linux amd64-64-Bit Compressed References 20210507_73 (JIT enabled, AOT enabled)
OpenJ9   - 295e06e0d
OMR      - d96f2b34f
JCL      - da466bb02c based on jdk-11.0.11+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_util_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-64_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F73%2FOpenJDK11U-jre_x64_linux_openj9_IBM_2021-05-07-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F73%2FOpenJDK11U-debugimage_x64_linux_openj9_IBM_2021-05-07-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F73%2FOpenJDK11U-jdk_x64_linux_openj9_IBM_2021-05-07-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F73%2FOpenJDK11U-testimage_x64_linux_openj9_IBM_2021-05-07-01-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-05-07T02:46:29.108Z] Running test jdk_util_0 ...
[2021-05-07T02:46:29.108Z] ===============================================
[2021-05-07T02:46:29.108Z] jdk_util_0 Start Time: Thu May  6 19:46:27 2021 Epoch Time (ms): 1620355587220
[2021-05-07T02:46:29.108Z] "/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-07T02:46:29.108Z] JVMSHRC005I No shared class caches available
[2021-05-07T02:46:29.108Z] JVMSHRC005I No shared class caches available
[2021-05-07T02:46:29.108Z] cache cleanup done
[2021-05-07T02:46:29.108Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2021-05-07T02:46:29.108Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2021-05-07T02:53:58.390Z] --------------------------------------------------
[2021-05-07T02:53:58.390Z] TEST: java/util/Locale/Bug7069824.java
...
[2021-05-07T02:53:58.392Z] java.lang.AssertionError:     LR.parse(Accept-Language: hak-CN;q=0.8, no-bok-NO;q=0.9, no-nyn, cmn-CN;q=0.1) test failed.: lists don't have the same size expected [11] but found [10]
[2021-05-07T02:53:58.392Z] 	at org.testng.Assert.fail(Assert.java:94)
[2021-05-07T02:53:58.392Z] 	at org.testng.Assert.failNotEquals(Assert.java:496)
[2021-05-07T02:53:58.392Z] 	at org.testng.Assert.assertEquals(Assert.java:125)
[2021-05-07T02:53:58.392Z] 	at org.testng.Assert.assertEquals(Assert.java:372)
[2021-05-07T02:53:58.392Z] 	at org.testng.Assert.assertEquals(Assert.java:539)
[2021-05-07T02:53:58.392Z] 	at Bug7069824.testLRParse(Bug7069824.java:316)
[2021-05-07T02:53:58.392Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T02:53:58.392Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T02:53:58.392Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T02:53:58.392Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T02:53:58.392Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-05-07T02:53:58.392Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-05-07T02:53:58.392Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-05-07T02:53:58.392Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-05-07T02:53:58.392Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-05-07T02:53:58.392Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-05-07T02:53:58.392Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-05-07T02:53:58.392Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-05-07T02:53:58.392Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-05-07T02:53:58.392Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-05-07T02:53:58.392Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-05-07T02:53:58.392Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-05-07T02:53:58.392Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-05-07T02:53:58.392Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-05-07T02:53:58.392Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-05-07T02:53:58.392Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-05-07T02:53:58.392Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-05-07T02:53:58.392Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-05-07T02:53:58.392Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-05-07T02:53:58.392Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T02:53:58.392Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T02:53:58.392Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T02:53:58.392Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T02:53:58.392Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-05-07T02:53:58.392Z] 	at java.base/java.lang.Thread.run(Thread.java:861)
[2021-05-07T02:53:58.392Z] test Bug7069824.testLRParse("Accept-Language: rki;q=0.4, no-bok-NO;q=0.9, ccq;q=0.5", java.util.ImmutableCollections$ListN@6459f3c8): success
[2021-05-07T02:53:58.392Z] test Bug7069824.testLRParseIAE(""): success
[2021-05-07T02:53:58.392Z] test Bug7069824.testLRParseIAE("ja;q=3"): success
[2021-05-07T02:53:58.392Z] test Bug7069824.testLRParseNPE(): success

[2021-05-07T02:53:58.393Z] --------------------------------------------------
[2021-05-07T02:53:58.393Z] TEST: java/util/Locale/Bug8040211.java
...
[2021-05-07T02:53:58.396Z] java.lang.RuntimeException: Failed.
[2021-05-07T02:53:58.396Z] 	at Bug8040211.main(Bug8040211.java:147)
[2021-05-07T02:53:58.396Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T02:53:58.396Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T02:53:58.396Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T02:53:58.396Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T02:53:58.396Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-05-07T02:53:58.396Z] 	at java.base/java.lang.Thread.run(Thread.java:861)

[2021-05-07T02:53:58.396Z] --------------------------------------------------
[2021-05-07T02:54:05.601Z] TEST: java/util/Locale/LocaleEnhanceTest.java
...
[2021-05-07T02:54:05.603Z] java.lang.IllegalArgumentException: encountered 6 errors
[2021-05-07T02:54:05.603Z] 	at IntlTest.run(IntlTest.java:148)
[2021-05-07T02:54:05.603Z] 	at LocaleEnhanceTest.main(LocaleEnhanceTest.java:60)
[2021-05-07T02:54:05.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T02:54:05.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T02:54:05.603Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T02:54:05.603Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T02:54:05.603Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-05-07T02:54:05.603Z] 	at java.base/java.lang.Thread.run(Thread.java:861)

[2021-05-07T02:54:05.604Z] --------------------------------------------------
[2021-05-07T02:54:14.421Z] TEST: java/util/Locale/LocaleTest.java
...
[2021-05-07T02:54:14.422Z] java.lang.RuntimeException: Uncaught exception thrown in test method TestSimpleDisplayNames
[2021-05-07T02:54:14.422Z] 	at IntlTest.errImpl(IntlTest.java:198)
[2021-05-07T02:54:14.422Z] 	at IntlTest.errln(IntlTest.java:185)
[2021-05-07T02:54:14.422Z] 	at IntlTest.run(IntlTest.java:126)
[2021-05-07T02:54:14.422Z] 	at LocaleTest.main(LocaleTest.java:191)
[2021-05-07T02:54:14.422Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T02:54:14.422Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T02:54:14.422Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T02:54:14.422Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T02:54:14.422Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-05-07T02:54:14.422Z] 	at java.base/java.lang.Thread.run(Thread.java:861)

[2021-05-07T02:54:14.423Z] --------------------------------------------------
[2021-05-07T02:54:14.423Z] TEST: java/util/Locale/LSRDataTest.java
...
[2021-05-07T02:54:14.424Z] java.lang.RuntimeException: [FAILED: Ranges at index 7 do not match Expected: range=sgn-gse, weight=1.0, Actual: range=bjn, weight=1.0]
[2021-05-07T02:54:14.424Z] 	at LSRDataTest.checkEquality(LSRDataTest.java:373)
[2021-05-07T02:54:14.424Z] 	at LSRDataTest.main(LSRDataTest.java:77)
[2021-05-07T02:54:14.424Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T02:54:14.424Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T02:54:14.424Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T02:54:14.424Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T02:54:14.424Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-05-07T02:54:14.424Z] 	at java.base/java.lang.Thread.run(Thread.java:861)

[2021-05-07T02:54:14.425Z] --------------------------------------------------
[2021-05-07T03:12:56.734Z] TEST: sun/util/calendar/zi/Beyond2037.java
...
[2021-05-07T03:12:56.736Z] java.lang.AssertionError: expected [2038/03/14 03:00:00:000] but found [2038/03/14 02:00:00:000]
[2021-05-07T03:12:56.736Z] 	at org.testng.Assert.fail(Assert.java:94)
[2021-05-07T03:12:56.736Z] 	at org.testng.Assert.failNotEquals(Assert.java:496)
[2021-05-07T03:12:56.736Z] 	at org.testng.Assert.assertEquals(Assert.java:125)
[2021-05-07T03:12:56.736Z] 	at org.testng.Assert.assertEquals(Assert.java:178)
[2021-05-07T03:12:56.736Z] 	at org.testng.Assert.assertEquals(Assert.java:188)
[2021-05-07T03:12:56.736Z] 	at Beyond2037.testDstTransition(Beyond2037.java:62)
[2021-05-07T03:12:56.736Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T03:12:56.736Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T03:12:56.736Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T03:12:56.736Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T03:12:56.736Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-05-07T03:12:56.736Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-05-07T03:12:56.736Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-05-07T03:12:56.736Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-05-07T03:12:56.736Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-05-07T03:12:56.736Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-05-07T03:12:56.736Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-05-07T03:12:56.736Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-05-07T03:12:56.736Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-05-07T03:12:56.736Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-05-07T03:12:56.736Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-05-07T03:12:56.736Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-05-07T03:12:56.736Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-05-07T03:12:56.736Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-05-07T03:12:56.736Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-05-07T03:12:56.736Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-05-07T03:12:56.736Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-05-07T03:12:56.736Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-05-07T03:12:56.736Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-07T03:12:56.736Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-07T03:12:56.736Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-07T03:12:56.736Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-05-07T03:12:56.737Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-05-07T03:12:56.737Z] 	at java.base/java.lang.Thread.run(Thread.java:861)

[2021-05-07T03:14:12.820Z] jdk_util_0_FAILED
```

This appears a regression across platforms, not seen in JDK8, JDK17 (no JDK16 run last night).
Note: this is JDK11 IBM internal build.

**Comment by pshipton** [comment]
This ran before I backed out https://github.com/eclipse-openj9/openj9/pull/12609. The open tests last night, which ran later and have the change backed out, didn't have this problem. It would be worth trying again with the latest to see if this is resolved now.

The open testing isn't all completed yet, but most likely the openjdk testing is complete across all platforms, and no failures reported. Some platforms are completed already.
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK11_s390x_linux/3022/
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK11_ppc64_aix/2802/

**Comment by pshipton** [comment]
I know what this is.The other possibility, which seems more likely from what failed, is the internal testing is not consistent. @AdamBrousseau
Yesterday the extensions (which contain the tests) were updated to 11.0.12+1
