### ISSUE TITLE
java/lang/ProcessBuilder/Basic.java failing on new machines

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12664]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/346/
win2012-x86-10
java/lang/ProcessBuilder/Basic.java
```
23:15:20  STDOUT:
23:15:20  This appears to be a Windows system.
23:15:20  This appears to be a Unicode-based OS.
23:15:20  Testing ASCII environment values
23:15:20  Testing Latin1 environment values
23:15:20  Testing directory .
23:15:20  Testing directory ..
23:15:20  Testing directory \
23:15:20  Testing directory C:
23:15:20  Testing directory c:
23:15:20  Testing directory C:\
23:15:20  Testing directory c:\
23:15:20  Testing directory \
23:15:20  Testing directory c:\windows  
23:15:20  Testing directory c:\Program Files
23:15:20  Testing directory c:\Program Files
23:15:20  Testing Unicode directory:.\ProcessBuilderDir??
23:15:20  Running case insensitve variable tests
23:15:20  cmdp
23:15:20  cmdp 0: F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java
23:15:20  cmdp 1: -XX:+DisplayVMOutputToStderr
23:15:20  cmdp 2: -classpath
23:15:20  cmdp 3: F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\output_16207019969801\jdk_lang_1\work\classes\2\java\lang\ProcessBuilder\Basic_id0.d;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\ProcessBuilder;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\javatest.jar;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\jtreg.jar
23:15:20  cmdp 4: Basic$JavaChild
23:15:20  cmdp 5: System.getenv()
23:15:20  envp
23:15:20  envp 0: SystemRoot=C:\Windows
23:15:20  envp 1: LC_ALL=C
23:15:20  envp 2: FO=BR
23:15:20   waitFor process: delta: 121376
23:15:20  
23:15:20  Passed = 9217, failed = 3
23:15:20  
23:15:20  STDERR:
23:15:20  >'1'< not equal to '0'
23:15:20  java.lang.Throwable
23:15:20  	at java.base/java.lang.Thread.dumpStack(Thread.java:536)
23:15:20  	at Basic.fail(Basic.java:2774)
23:15:20  	at Basic.fail(Basic.java:2775)
23:15:20  	at Basic.equal(Basic.java:2781)
23:15:20  	at Basic.commandOutput(Basic.java:111)
23:15:20  	at Basic.commandOutput(Basic.java:122)
23:15:20  	at Basic.javaChildOutput(Basic.java:567)
23:15:20  	at Basic.pwdInChild(Basic.java:583)
23:15:20  	at Basic.realMain(Basic.java:1749)
23:15:20  	at Basic.main(Basic.java:2784)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:15:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:15:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:15:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:15:20  	at java.base/java.lang.Thread.run(Thread.java:861)
23:15:20  >'1'< not equal to '0'
23:15:20  java.lang.Throwable
23:15:20  	at java.base/java.lang.Thread.dumpStack(Thread.java:536)
23:15:20  	at Basic.fail(Basic.java:2774)
23:15:20  	at Basic.fail(Basic.java:2775)
23:15:20  	at Basic.equal(Basic.java:2781)
23:15:20  	at Basic.commandOutput(Basic.java:112)
23:15:20  	at Basic.commandOutput(Basic.java:122)
23:15:20  	at Basic.javaChildOutput(Basic.java:567)
23:15:20  	at Basic.pwdInChild(Basic.java:583)
23:15:20  	at Basic.realMain(Basic.java:1749)
23:15:20  	at Basic.main(Basic.java:2784)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:15:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:15:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:15:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:15:20  	at java.base/java.lang.Thread.run(Thread.java:861)
23:15:20  >''< not equal to 'F:\'
23:15:20  java.lang.Throwable
23:15:20  	at java.base/java.lang.Thread.dumpStack(Thread.java:536)
23:15:20  	at Basic.fail(Basic.java:2774)
23:15:20  	at Basic.fail(Basic.java:2775)
23:15:20  	at Basic.equal(Basic.java:2781)
23:15:20  	at Basic.realMain(Basic.java:1749)
23:15:20  	at Basic.main(Basic.java:2784)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:15:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:15:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:15:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:15:20  	at java.base/java.lang.Thread.run(Thread.java:861)
23:15:20  java.lang.AssertionError: Some tests failed
23:15:20  	at Basic.main(Basic.java:2786)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:15:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:15:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:15:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:15:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:15:20  	at java.base/java.lang.Thread.run(Thread.java:861)
```

**Comment by pshipton** [comment]
Another segfault in TreeTest.java on win2012-x86-9 https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/347/
This one contains the message `The paging file is too small for this operation to complete`
@jdekonin @AdamBrousseau The new Windows machines, including win2012-x86-5, need to be checked for proper paging files. See also https://github.com/eclipse-openj9/openj9/issues/12621#issuecomment-836685485

```
00:45:11  test TreeTest.test5(): failure
00:45:11  java.lang.AssertionError: Timeout waiting for processes to start expected [true] but found [false]
00:45:11  	at org.testng.Assert.fail(Assert.java:94)
00:45:11  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:45:11  	at org.testng.Assert.assertTrue(Assert.java:42)
00:45:11  	at TreeTest.test5(TreeTest.java:431)
00:45:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:45:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:45:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:45:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:45:11  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:45:11  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:45:11  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:45:11  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:45:11  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:45:11  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:45:11  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:45:11  	at org.testng.TestRunner.run(TestRunner.java:623)
00:45:11  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:45:11  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:45:11  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:45:11  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:45:11  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:45:11  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:45:11  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:45:11  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:45:11  	at org.testng.TestNG.run(TestNG.java:1018)
00:45:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:45:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:45:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:45:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:45:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:45:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:45:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:45:11  	at java.base/java.lang.Thread.run(Thread.java:861)
00:45:11  
00:45:11  ===============================================
00:45:11  java/lang/ProcessHandle/TreeTest.java
00:45:11  Total tests run: 5, Failures: 1, Skips: 0
00:45:11  ===============================================
00:45:11  
00:45:11  STDERR:
00:45:11  JVMJ9GC070E Failed to startup the Garbage Collector
00:45:11  Error: Could not create the Java Virtual Machine.
00:45:11  Error: A fatal exception has occurred. Program will exit.
00:45:11  JVMJ9VM011W Unable to load jclse29: The paging file is too small for this operation to complete. 
00:45:11  Error: Could not create the Java Virtual Machine.
00:45:11  Error: A fatal exception has occurred. Program will exit.
00:45:11  Unhandled exception
00:45:11  Type=Segmentation error vmState=0x00000000
00:45:11  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFBDD3E6978 ContextFlags=0010005f
00:45:11  Handler1=00007FFBDD4CF180 Handler2=00007FFBDD37AAF0 InaccessibleReadAddress=FFFFFFFFFFFFFFFF
00:45:11  RDI=00000000000001E6 RSI=00000026F4C29990 RAX=00000026F4B50420 RBX=006873396A286C6F
00:45:11  RCX=00000026F4B50420 RDX=006873396A286C6F R8=0000000000000000 R9=0000000000000000
00:45:11  R10=00000000000000C8 R11=00000000000000D0 R12=00000026FFCDF798 R13=00007FFBDD4CF180
00:45:11  R14=000000000001E600 R15=00000026F4B63570
00:45:11  RIP=00007FFBDD3E6978 RSP=00000026FFCDF3C0 RBP=00000026F4C29990 EFLAGS=0000000000010206
00:45:11  FS=0053 ES=002B DS=002B
00:45:11  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  Module=F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\default\j9thr29.dll
00:45:11  Module_base_address=00007FFBDD3E0000 Offset_in_DLL=0000000000006978
00:45:11  Target=2_90_20210511_710 (Windows Server 2012 R2 6.3 build 9600)
00:45:11  CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
00:45:11  ----------- Stack Backtrace -----------
00:45:11  omrthread_get_category+0x2f28 (0x00007FFBDD3E6978 [j9thr29+0x6978])
00:45:11  omrthread_monitor_wait+0x43 (0x00007FFBDD3E2B13 [j9thr29+0x2b13])
00:45:11  (0x00007FFBDC2A3E75 [j9jit29+0x63e75])
00:45:11  (0x00007FFBDC2ACB67 [j9jit29+0x6cb67])
00:45:11  j9port_isCompatible+0x1a1bf (0x00007FFBDD37CCEF [j9prt29+0x1ccef])
00:45:11  (0x00007FFBDC2AC7AD [j9jit29+0x6c7ad])
00:45:11  omrthread_get_category+0xa42 (0x00007FFBDD3E4492 [j9thr29+0x4492])
00:45:11  _o_strcat_s+0x5e (0x00007FFBDD77C1AE [ucrtbase+0x1c1ae])
00:45:11  BaseThreadInitThunk+0x22 (0x00007FFBEED713F2 [KERNEL32+0x13f2])
00:45:11  RtlUserThreadStart+0x34 (0x00007FFBEFEC54F4 [ntdll+0x154f4])
00:45:11  ---------------------------------------
00:45:11  JVMDUMP039I Processing dump event "gpf", detail "" at 2021/05/11 23:40:52 - please wait.
00:45:11  JVMDUMP032I JVM requested System dump using 'F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\output_16207934999823\jdk_lang_1\work\java\lang\ProcessHandle\TreeTest\core.20210511.234052.1812.0001.dmp' in response to an event
00:45:11  Unhandled exception
00:45:11  Type=Segmentation error vmState=0x00000000
00:45:11  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFBDC2ACB41 ContextFlags=0010005f
00:45:11  Handler1=00007FFBDD4CF180 Handler2=00007FFBDD37AAF0 InaccessibleReadAddress=FFFFFFFFFFFFFFFF
00:45:11  Unhandled exception
00:45:11  Type=Segmentation error vmState=0x00000000
00:45:11  RDI=000000003201E600 RSI=0000001D2E830B80 RAX=8000026D9113447B RBX=0000001D2EC42070
00:45:11  RCX=0000000000000000 RDX=0000001D2577A658 R8=0000000000000001 R9=0000001D2577DE10
00:45:11  R10=00000000000000C8 R11=00000000000000D0 R12=0000001D34C3F7B8 R13=00007FFBDD4CF180
00:45:11  R14=000000003201E600 R15=0000001D24E55170
00:45:11  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFBDD3E6978 ContextFlags=0010005f
00:45:11  Handler1=00007FFBDD4CF180 Handler2=00007FFBDD37AAF0 InaccessibleReadAddress=FFFFFFFFFFFFFFFF
00:45:11  RIP=00007FFBDC2ACB41 RSP=0000001D34C3F520 RBP=0000001D2E830B80 EFLAGS=0000000000010202
00:45:11  FS=0053 ES=002B DS=002B
00:45:11  RDI=00000000003201E6 RSI=000000AD50831850 RAX=000000AD46D00420 RBX=006873396A286C6F
00:45:11  RCX=000000AD46D00420 RDX=006873396A286C6F R8=0000000000000000 R9=0000000000000000
00:45:11  R10=00000000000000C8 R11=00000000000000D0 R12=000000AD5598F988 R13=00007FFBDD4CF180
00:45:11  R14=000000003201E600 R15=000000AD46D13570
00:45:11  RIP=00007FFBDD3E6978 RSP=000000AD5598F5B0 RBP=000000AD50831850 EFLAGS=0000000000010202
00:45:11  FS=0053 ES=002B DS=002B
00:45:11  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:45:11  Module=F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\default\j9thr29.dll
00:45:11  Module_base_address=00007FFBDD3E0000 Offset_in_DLL=0000000000006978
00:45:11  Target=2_90_20210511_710 (Windows Server 2012 R2 6.3 build 9600)
00:45:11  CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
00:45:11  ----------- Stack Backtrace -----------
00:45:11  Module=F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\default\j9jit29.dll
00:45:11  Module_base_address=00007FFBDC240000 Offset_in_DLL=000000000006cb41
00:45:11  Target=2_90_20210511_710 (Windows Server 2012 R2 6.3 build 9600)
00:45:11  CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
00:45:11  ----------- Stack Backtrace -----------
00:45:11  (0x00007FFBDC2ACB41 [j9jit29+0x6cb41])
00:45:11  j9port_isCompatible+0x1a1bf (0x00007FFBDD37CCEF [j9prt29+0x1ccef])
00:45:11  (0x00007FFBDC2AC7AD [j9jit29+0x6c7ad])
00:45:11  omrthread_get_category+0xa42 (0x00007FFBDD3E4492 [j9thr29+0x4492])
00:45:11  _o_strcat_s+0x5e (0x00007FFBDD77C1AE [ucrtbase+0x1c1ae])
00:45:11  BaseThreadInitThunk+0x22 (0x00007FFBEED713F2 [KERNEL32+0x13f2])
00:45:11  RtlUserThreadStart+0x34 (0x00007FFBEFEC54F4 [ntdll+0x154f4])
00:45:11  ---------------------------------------
00:45:11  JVMDUMP039I Processing dump event "gpf", detail "" at 2021/05/11 23:40:52 - please wait.
00:45:11  omrthread_get_category+0x2f28 (0x00007FFBDD3E6978 [j9thr29+0x6978])
00:45:11  omrthread_monitor_wait+0x43 (0x00007FFBDD3E2B13 [j9thr29+0x2b13])
00:45:11  (0x00007FFBDC2A3E75 [j9jit29+0x63e75])
00:45:11  (0x00007FFBDC2ACB67 [j9jit29+0x6cb67])
00:45:11  j9port_isCompatible+0x1a1bf (0x00007FFBDD37CCEF [j9prt29+0x1ccef])
00:45:11  (0x00007FFBDC2AC7AD [j9jit29+0x6c7ad])
00:45:11  omrthread_get_category+0xa42 (0x00007FFBDD3E4492 [j9thr29+0x4492])
00:45:11  _o_strcat_s+0x5e (0x00007FFBDD77C1AE [ucrtbase+0x1c1ae])
00:45:11  BaseThreadInitThunk+0x22 (0x00007FFBEED713F2 [KERNEL32+0x13f2])
00:45:11  RtlUserThreadStart+0x34 (0x00007FFBEFEC54F4 [ntdll+0x154f4])
00:45:11  ---------------------------------------
```

**Comment by pshipton** [comment]
There are a number of tests failing on the new machines, related to memory.

https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/86/
win2012-x86-9
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/lang/ProcessHandle/TreeTest.java.TreeTest
    java/lang/ProcessHandle/TreeTest.java.TreeTest
    java/lang/StringBuffer/HugeCapacity.java.HugeCapacity
    java/util/StringJoiner/StringJoinerTest.java.StringJoinerTest
    java/util/StringJoiner/StringJoinerTest.java.StringJoinerTest

https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/87/
win2012-x86-7
    java/lang/ProcessHandle/OnExitTest.java.OnExitTest
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/util/StringJoiner/StringJoinerTest.java.StringJoinerTest
    java/util/StringJoiner/StringJoinerTest.java.StringJoinerTest

**Comment by jdekonin** [comment]
@rajdeepsingh1, the page file configuration isn't working on these new systems.  By the looks of it the answer will likely be for 1 contiguous pagefile and not 2 on 2 different drives which windows doesn't appear to be handling correctly anyways via this offering. This might require an increase in hard drive size on C from 100 -> 150??  added cost, but maybe we can do away with the added (50 or 100G) drive and just have a larger primary drive?

**Comment by rajdeepsingh1** [comment]
Virtual memory / page file issues fixed on win2012-x86-6 to -11

The additional drive with the page space was not being fully allocated due to dynamic allocation of space - set this value to be static therefore the size would not differ.

**Comment by AdamBrousseau** [comment]
Is this resolved?

**Comment by pshipton** [comment]
Yes its good now.
