### ISSUE TITLE
Problems with Update-Reference-Repos job, timing out

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12697]
I found that AIX machines were timing out trying to clone repos, I've updated the cache on all the machines manually, removing the remotes for jdk14 and jdk15.

The Update-Reference-Repos job has been failing. It seems to be getting killed by the sanitize job at night. This may be related to the (AIX, OSX, Windows) machines being busy during the day running special.system testing.

One idea is to break it up, and do fetching and optimizing in different jobs so at least the fetching can stay up to date. Not sure how much pruning we need. Not much should become obsolete. Even when repos like jdk15 are removed, most of this content is in the jdk16 repo.

https://ci.eclipse.org/openj9/view/Infrastructure/job/Update-Reference-Repos/601/
```
17:49:49  Running on aix71-p8-3 in /home/jenkins/workspace/Update-Reference-Repos
[Pipeline] {
[Pipeline] stage
[Pipeline] { (aix71-p8-3 - Update Reference Repo)
[Pipeline] dir
17:49:49  Running in /home/jenkins/openjdk_cache
[Pipeline] {
[Pipeline] stage
[Pipeline] { (aix71-p8-3 - Config)
[Pipeline] sh
17:49:51  + git init --bare
17:49:51  Reinitialized existing Git repository in /home/jenkins/openjdk_cache/
[Pipeline] sh
17:49:53  + git config remote.jdk8.url https://github.com/ibmruntimes/openj9-openjdk-jdk8.git
[Pipeline] sh
17:49:55  + git config remote.jdk8.fetch +refs/heads/*:refs/remotes/jdk8/*
[Pipeline] sh
17:49:57  + git config remote.jdk11.url https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
[Pipeline] sh
17:49:59  + git config remote.jdk11.fetch +refs/heads/*:refs/remotes/jdk11/*
[Pipeline] sh
17:50:01  + git config remote.jdk16.url https://github.com/ibmruntimes/openj9-openjdk-jdk16.git
[Pipeline] sh
17:50:03  + git config remote.jdk16.fetch +refs/heads/*:refs/remotes/jdk16/*
[Pipeline] sh
17:50:05  + git config remote.jdknext.url https://github.com/ibmruntimes/openj9-openjdk-jdk.git
[Pipeline] sh
17:50:07  + git config remote.jdknext.fetch +refs/heads/*:refs/remotes/jdknext/*
[Pipeline] sh
17:50:09  + git config remote.openj9.url https://github.com/eclipse-openj9/openj9.git
[Pipeline] sh
17:50:11  + git config remote.openj9.fetch +refs/heads/*:refs/remotes/openj9/*
[Pipeline] sh
17:50:13  + git config remote.omr.url https://github.com/eclipse/omr.git
[Pipeline] sh
17:50:16  + git config remote.omr.fetch +refs/heads/*:refs/remotes/omr/*
[Pipeline] sh
17:50:18  + git config remote.adoptopenjdk.url https://github.com/AdoptOpenJDK/openjdk-tests.git
[Pipeline] sh
17:50:20  + git config remote.adoptopenjdk.fetch +refs/heads/*:refs/remotes/adoptopenjdk/*
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (aix71-p8-3 - Fetch)
[Pipeline] sh
17:50:22  + git fetch --all
17:50:22  Fetching jdk8
17:50:29  From https://github.com/ibmruntimes/openj9-openjdk-jdk8
17:50:29     cc8d9d33471..d9f8d65fa88  master         -> jdk8/master
17:50:29     2c626feefcf..e0e56cb2b61  openj9         -> jdk8/openj9
17:50:29     2c626feefcf..e0e56cb2b61  openj9-staging -> jdk8/openj9-staging
17:50:29   * [new tag]                 jdk8u302-b00   -> jdk8u302-b00
17:50:29   * [new tag]                 jdk8u302-b01   -> jdk8u302-b01
17:50:29  Fetching jdk11
17:50:32  From https://github.com/ibmruntimes/openj9-openjdk-jdk11
17:50:32     a74ff36375e..64a787c7ad7  master         -> jdk11/master
17:50:32     1d9ada7a382..975429a04a0  openj9         -> jdk11/openj9
17:50:32     1d9ada7a382..376b14b921f  openj9-staging -> jdk11/openj9-staging
17:50:32   * [new tag]                 jdk-11.0.12+0  -> jdk-11.0.12+0
17:50:32   * [new tag]                 jdk-11.0.12+1  -> jdk-11.0.12+1
17:50:32  Fetching jdk14
17:50:33  Fetching jdknext
17:50:35  From https://github.com/ibmruntimes/openj9-openjdk-jdk
17:50:35     113934f7676..693456e78ce  master         -> jdknext/master
17:50:35     1dc21088e3d..780fa63b0bb  openj9         -> jdknext/openj9
17:50:35     c9c596cfc27..d3cebffddd3  openj9-staging -> jdknext/openj9-staging
17:50:35   * [new tag]                 jdk-17+21      -> jdk-17+21
17:50:35  Fetching adoptopenjdk
17:50:36  From https://github.com/AdoptOpenJDK/openjdk-tests
17:50:36     c58a9bb5086..a0d913f7d61  master     -> adoptopenjdk/master
17:50:36  Fetching jdk15
17:50:36  Fetching openj9
17:50:39  From https://github.com/eclipse-openj9/openj9
17:50:39     343644acf13..1e923583577  master     -> openj9/master
17:50:39  Fetching omr
17:50:40  From https://github.com/eclipse/omr
17:50:40     79c52c7268b..cd2fd54f0bf  master     -> omr/master
17:50:40  Fetching jdk16
17:50:42  From https://github.com/ibmruntimes/openj9-openjdk-jdk16
17:50:42     5086e9ffa1b..bb693ab4900  master     -> jdk16/master
17:50:42     09a24338131..7a506c70257  openj9     -> jdk16/openj9
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (aix71-p8-3 - GC Repo)
[Pipeline] sh
17:50:44  + git gc --aggressive --prune=all
17:53:28  Running on aix71-p8-8 in /home/jenkins/workspace/Update-Reference-Repos
[Pipeline] {
[Pipeline] stage
[Pipeline] { (aix71-p8-8 - Update Reference Repo)
[Pipeline] dir
17:53:28  Running in /home/jenkins/openjdk_cache
[Pipeline] {
[Pipeline] stage
[Pipeline] { (aix71-p8-8 - Config)
[Pipeline] sh
17:53:30  + git init --bare
17:53:30  Reinitialized existing Git repository in /home/jenkins/openjdk_cache/
[Pipeline] sh
17:53:32  + git config remote.jdk8.url https://github.com/ibmruntimes/openj9-openjdk-jdk8.git
[Pipeline] sh
17:53:34  + git config remote.jdk8.fetch +refs/heads/*:refs/remotes/jdk8/*
[Pipeline] sh
17:53:37  + git config remote.jdk11.url https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
[Pipeline] sh
17:53:39  + git config remote.jdk11.fetch +refs/heads/*:refs/remotes/jdk11/*
[Pipeline] sh
17:53:41  + git config remote.jdk16.url https://github.com/ibmruntimes/openj9-openjdk-jdk16.git
[Pipeline] sh
17:53:43  + git config remote.jdk16.fetch +refs/heads/*:refs/remotes/jdk16/*
[Pipeline] sh
17:53:46  + git config remote.jdknext.url https://github.com/ibmruntimes/openj9-openjdk-jdk.git
[Pipeline] sh
17:53:48  + git config remote.jdknext.fetch +refs/heads/*:refs/remotes/jdknext/*
[Pipeline] sh
17:53:50  + git config remote.openj9.url https://github.com/eclipse-openj9/openj9.git
[Pipeline] sh
17:53:53  + git config remote.openj9.fetch +refs/heads/*:refs/remotes/openj9/*
[Pipeline] sh
17:53:55  + git config remote.omr.url https://github.com/eclipse/omr.git
[Pipeline] sh
17:53:57  + git config remote.omr.fetch +refs/heads/*:refs/remotes/omr/*
[Pipeline] sh
17:53:59  + git config remote.adoptopenjdk.url https://github.com/AdoptOpenJDK/openjdk-tests.git
[Pipeline] sh
17:54:02  + git config remote.adoptopenjdk.fetch +refs/heads/*:refs/remotes/adoptopenjdk/*
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (aix71-p8-8 - Fetch)
[Pipeline] sh
17:54:04  + git fetch --all
17:54:04  Fetching jdk8
17:54:11  From https://github.com/ibmruntimes/openj9-openjdk-jdk8
17:54:11     cc8d9d33471..d9f8d65fa88  master         -> jdk8/master
17:54:11     2c626feefcf..e0e56cb2b61  openj9         -> jdk8/openj9
17:54:11     2c626feefcf..e0e56cb2b61  openj9-staging -> jdk8/openj9-staging
17:54:11   * [new tag]                 jdk8u302-b00   -> jdk8u302-b00
17:54:11   * [new tag]                 jdk8u302-b01   -> jdk8u302-b01
17:54:11  Fetching jdk11
17:54:14  From https://github.com/ibmruntimes/openj9-openjdk-jdk11
17:54:14     a74ff36375e..64a787c7ad7  master         -> jdk11/master
17:54:14     1d9ada7a382..975429a04a0  openj9         -> jdk11/openj9
17:54:14     1d9ada7a382..376b14b921f  openj9-staging -> jdk11/openj9-staging
17:54:15   * [new tag]                 jdk-11.0.12+0  -> jdk-11.0.12+0
17:54:15   * [new tag]                 jdk-11.0.12+1  -> jdk-11.0.12+1
17:54:15  Fetching jdk14
17:54:15  Fetching jdknext
17:54:18  From https://github.com/ibmruntimes/openj9-openjdk-jdk
17:54:18     113934f7676..693456e78ce  master         -> jdknext/master
17:54:18     1dc21088e3d..780fa63b0bb  openj9         -> jdknext/openj9
17:54:18     c9c596cfc27..d3cebffddd3  openj9-staging -> jdknext/openj9-staging
17:54:18   * [new tag]                 jdk-17+21      -> jdk-17+21
17:54:18  Fetching adoptopenjdk
17:54:20  From https://github.com/AdoptOpenJDK/openjdk-tests
17:54:20     c58a9bb5086..a0d913f7d61  master     -> adoptopenjdk/master
17:54:20  Fetching jdk15
17:54:20  Fetching openj9
17:54:21  From https://github.com/eclipse-openj9/openj9
17:54:21     343644acf13..1e923583577  master     -> openj9/master
17:54:21  Fetching omr
17:54:23  From https://github.com/eclipse/omr
17:54:23     79c52c7268b..cd2fd54f0bf  master     -> omr/master
17:54:23  Fetching jdk16
17:54:25  From https://github.com/ibmruntimes/openj9-openjdk-jdk16
17:54:25     5086e9ffa1b..bb693ab4900  master     -> jdk16/master
17:54:25     09a24338131..7a506c70257  openj9     -> jdk16/openj9
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (aix71-p8-8 - GC Repo)
[Pipeline] sh
17:54:28  + git gc --aggressive --prune=all
17:54:37  Running on osx1013-x86-4 in /Users/jenkins/workspace/Update-Reference-Repos
[Pipeline] {
[Pipeline] stage
[Pipeline] { (osx1013-x86-4 - Update Reference Repo)
[Pipeline] dir
17:54:37  Running in /Users/jenkins/openjdk_cache
[Pipeline] {
[Pipeline] stage
[Pipeline] { (osx1013-x86-4 - Config)
[Pipeline] sh
17:54:40  + git init --bare
17:54:40  Reinitialized existing Git repository in /Users/jenkins/openjdk_cache/
[Pipeline] sh
17:54:44  + git config remote.jdk8.url https://github.com/ibmruntimes/openj9-openjdk-jdk8.git
[Pipeline] sh
17:54:48  + git config remote.jdk8.fetch '+refs/heads/*:refs/remotes/jdk8/*'
[Pipeline] sh
17:54:51  + git config remote.jdk11.url https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
[Pipeline] sh
17:54:58  + git config remote.jdk11.fetch '+refs/heads/*:refs/remotes/jdk11/*'
[Pipeline] sh
17:55:02  + git config remote.jdk16.url https://github.com/ibmruntimes/openj9-openjdk-jdk16.git
[Pipeline] sh
17:55:06  + git config remote.jdk16.fetch '+refs/heads/*:refs/remotes/jdk16/*'
[Pipeline] sh
17:55:10  + git config remote.jdknext.url https://github.com/ibmruntimes/openj9-openjdk-jdk.git
[Pipeline] sh
17:55:14  + git config remote.jdknext.fetch '+refs/heads/*:refs/remotes/jdknext/*'
[Pipeline] sh
17:55:18  + git config remote.openj9.url https://github.com/eclipse-openj9/openj9.git
[Pipeline] sh
17:55:22  + git config remote.openj9.fetch '+refs/heads/*:refs/remotes/openj9/*'
[Pipeline] sh
17:55:26  + git config remote.omr.url https://github.com/eclipse/omr.git
[Pipeline] sh
17:55:29  + git config remote.omr.fetch '+refs/heads/*:refs/remotes/omr/*'
[Pipeline] sh
17:55:33  + git config remote.adoptopenjdk.url https://github.com/AdoptOpenJDK/openjdk-tests.git
[Pipeline] sh
17:55:37  + git config remote.adoptopenjdk.fetch '+refs/heads/*:refs/remotes/adoptopenjdk/*'
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (osx1013-x86-4 - Fetch)
[Pipeline] sh
17:55:41  + git fetch --all
17:55:41  Fetching jdk8
17:55:44  From https://github.com/ibmruntimes/openj9-openjdk-jdk8
17:55:44     cc8d9d33471..d9f8d65fa88  master         -> jdk8/master
17:55:44     2c626feefcf..e0e56cb2b61  openj9         -> jdk8/openj9
17:55:44     2c626feefcf..e0e56cb2b61  openj9-staging -> jdk8/openj9-staging
17:55:44   * [new tag]                 jdk8u302-b00   -> jdk8u302-b00
17:55:44   * [new tag]                 jdk8u302-b01   -> jdk8u302-b01
17:55:44  Fetching jdk11
17:55:56  From https://github.com/ibmruntimes/openj9-openjdk-jdk11
17:55:56     a74ff36375e..64a787c7ad7  master         -> jdk11/master
17:55:56     1d9ada7a382..975429a04a0  openj9         -> jdk11/openj9
17:55:56     1d9ada7a382..376b14b921f  openj9-staging -> jdk11/openj9-staging
17:55:56   * [new tag]                 jdk-11.0.12+0  -> jdk-11.0.12+0
17:55:56   * [new tag]                 jdk-11.0.12+1  -> jdk-11.0.12+1
17:55:56  Fetching jdk14
17:55:56  Fetching jdknext
17:56:01  From https://github.com/ibmruntimes/openj9-openjdk-jdk
17:56:01     113934f7676..693456e78ce  master         -> jdknext/master
17:56:01     1dc21088e3d..780fa63b0bb  openj9         -> jdknext/openj9
17:56:01     c9c596cfc27..d3cebffddd3  openj9-staging -> jdknext/openj9-staging
17:56:01   * [new tag]                 jdk-17+21      -> jdk-17+21
17:56:01  Fetching adoptopenjdk
17:56:03  From https://github.com/AdoptOpenJDK/openjdk-tests
17:56:03     c58a9bb5086..a0d913f7d61  master     -> adoptopenjdk/master
17:56:03  Fetching jdk15
17:56:04  Fetching openj9
17:56:10  From https://github.com/eclipse-openj9/openj9
17:56:10     343644acf13..1e923583577  master     -> openj9/master
17:56:10  Fetching omr
17:56:13  From https://github.com/eclipse/omr
17:56:13     79c52c7268b..cd2fd54f0bf  master     -> omr/master
17:56:13  Fetching jdk16
17:56:16  From https://github.com/ibmruntimes/openj9-openjdk-jdk16
17:56:16     5086e9ffa1b..bb693ab4900  master     -> jdk16/master
17:56:16     09a24338131..7a506c70257  openj9     -> jdk16/openj9
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (osx1013-x86-4 - GC Repo)
[Pipeline] sh
17:56:20  + git gc --aggressive --prune=all
Cancelling nested steps due to timeout
18:00:02  Sending interrupt signal to process
18:00:02  Sending interrupt signal to process
18:00:03  Sending interrupt signal to process
18:00:03  Sending interrupt signal to process
18:00:03  Sending interrupt signal to process
18:00:03  Sending interrupt signal to process
18:00:03  Sending interrupt signal to process
18:00:04  Sending interrupt signal to process
[Pipeline] // node
[Pipeline] // node
[Pipeline] // node
[Pipeline] // node
18:00:05  Sending interrupt signal to process
18:00:05  Sending interrupt signal to process
18:00:05  Sending interrupt signal to process
18:00:06  Sending interrupt signal to process
18:00:06  Sending interrupt signal to process
18:00:06  Sending interrupt signal to process
18:00:06  Sending interrupt signal to process
18:00:07  Sending interrupt signal to process
[Pipeline] }
18:00:07  Failed in branch master
[Pipeline] }
18:00:07  Failed in branch aix71-p8-9
[Pipeline] }
18:00:07  Failed in branch aix71-p8-2
[Pipeline] }
18:00:07  Failed in branch aix71-p8-1
18:00:09  error: repack died of signal 15
18:00:09  error: failed to run repack
18:00:09  script returned exit code 255
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:09  Failed in branch aix71-p8-8
18:00:13  error: pack-objects died of signal 15
18:00:13  error: failed to run repack
18:00:14  script returned exit code 255
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:14  Failed in branch osx1013-x86-4
18:00:17  error: repack died of signal 15
18:00:17  error: failed to run repack
18:00:17  script returned exit code 255
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:17  Failed in branch aix71-p8-3
18:00:22  After 20s process did not stop
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:22  Failed in branch win2012-x86-4
18:00:23  After 20s process did not stop
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:23  Failed in branch win2012-x86-5
18:00:23  After 20s process did not stop
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:23  Failed in branch win2012-x86-8
18:00:23  After 20s process did not stop
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:23  Failed in branch win2012-x86-10
18:00:23  After 20s process did not stop
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
18:00:23  Failed in branch win2012-x86-11
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Tue Apr 27 21:54:56 EDT 2021 by Thread[Running CpsFlowExecution[Owner[Sanitize-Nodes/712:Sanitize-Nodes #712]],5,main] [id=19148]
		at hudson.model.Computer.recordTermination(Computer.java:229)
		at hudson.model.Computer.disconnect(Computer.java:495)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:759)
		at jdk.internal.reflect.GeneratedMethodAccessor3056.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at <unknown class>.<unknown method>(Unknown Source)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
		at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
		at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
		at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
		at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
		at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
		at jdk.internal.reflect.GeneratedMethodAccessor198.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at <unknown class>.<unknown method>(Unknown Source)
		at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
		at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
<many more Termination requested like this>
```

**Comment by pshipton** [comment]
@AdamBrousseau fyi
