### ISSUE TITLE
aarch64_linux jdk_util_0_FAILED : Error: STREAM_TO_ARRAY: java.lang.NullPointerException & OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12733]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.openjdk_aarch64_linux/43/` (`cent7-aarch64-3`):
```
openjdk version "1.8.0_302-internal"
OpenJDK Runtime Environment (build 1.8.0_302-internal-202105200233-b02)
Eclipse OpenJ9 VM (build master-1549b5a8d, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20210520_119 (JIT enabled, AOT enabled)
OpenJ9   - 1549b5a8d
OMR      - 91436845b
JCL      - 8a9e812c based on jdk8u302-b02)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_util_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=aarch64_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-debugimage_aarch64_linux_openj9_2021-05-20-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-jre_aarch64_linux_openj9_2021-05-20-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-testimage_aarch64_linux_openj9_2021-05-20-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-jdk_aarch64_linux_openj9_2021-05-20-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-05-20T03:21:56.421Z] Running test jdk_util_0 ...
[2021-05-20T03:21:56.421Z] ===============================================
[2021-05-20T03:21:56.421Z] jdk_util_0 Start Time: Wed May 19 23:21:55 2021 Epoch Time (ms): 1621480915309
[2021-05-20T03:21:56.421Z] "/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-20T03:21:56.421Z] JVMSHRC005I No shared class caches available
[2021-05-20T03:21:56.421Z] JVMSHRC005I No shared class caches available
[2021-05-20T03:21:56.421Z] cache cleanup done
[2021-05-20T03:21:56.421Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2021-05-20T03:21:56.421Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 
...
[2021-05-20T03:30:55.331Z] --------------------------------------------------
[2021-05-20T03:30:55.331Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/IntUniqOpTest.java
[2021-05-20T03:30:55.331Z] config java.util.stream.LoggingTestCase.before(): success
[2021-05-20T03:30:55.331Z] test org.openjdk.tests.java.util.stream.IntUniqOpTest.testOp("array:0..1000", IntTestData[array:0..1000]): failure
[2021-05-20T03:30:55.331Z] java.lang.AssertionError: 1 failure(s) for test data: IntTestData[array:0..1000]
[2021-05-20T03:30:55.331Z] 1: java.lang.Error: STREAM_TO_ARRAY: java.lang.NullPointerException
[2021-05-20T03:30:55.331Z] java.lang.NullPointerException
[2021-05-20T03:30:55.331Z] 	at java.util.stream.SpinedBuffer.accept(SpinedBuffer.java:263)
[2021-05-20T03:30:55.331Z] 	at java.util.stream.Nodes$SpinedNodeBuilder.accept(Nodes.java:1277)
[2021-05-20T03:30:55.331Z] 	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:257)
[2021-05-20T03:30:55.331Z] 	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
[2021-05-20T03:30:55.331Z] 	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
[2021-05-20T03:30:55.331Z] 	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:257)
[2021-05-20T03:30:55.331Z] 	at java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1032)
[2021-05-20T03:30:55.331Z] 	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
[2021-05-20T03:30:55.331Z] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:561)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:267)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:511)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.StreamTestScenario$3._run(StreamTestScenario.java:71)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.StreamTestScenario.run(StreamTestScenario.java:264)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:395)
[2021-05-20T03:30:55.332Z] 	at java.util.stream.OpTestCase.exerciseOps(OpTestCase.java:103)
[2021-05-20T03:30:55.332Z] 	at org.openjdk.tests.java.util.stream.IntUniqOpTest.testOp(IntUniqOpTest.java:49)
[2021-05-20T03:30:55.332Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-20T03:30:55.332Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-20T03:30:55.332Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-20T03:30:55.332Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-05-20T03:30:55.332Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-05-20T03:30:55.332Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-05-20T03:30:55.332Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-05-20T03:30:55.332Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-05-20T03:30:55.332Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-05-20T03:30:55.332Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-05-20T03:30:55.332Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-05-20T03:30:55.332Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-05-20T03:30:55.332Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-05-20T03:30:55.332Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-05-20T03:30:55.332Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-05-20T03:30:55.332Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-05-20T03:30:55.332Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-05-20T03:30:55.332Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-05-20T03:30:55.332Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-05-20T03:30:55.332Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-05-20T03:30:55.332Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-05-20T03:30:55.332Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-05-20T03:30:55.332Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-05-20T03:30:55.332Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-20T03:30:55.332Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-20T03:30:55.332Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-20T03:30:55.332Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-05-20T03:30:55.332Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-05-20T03:30:55.332Z] 	at java.lang.Thread.run(Thread.java:821)
...
[2021-05-20T03:30:55.336Z] ===============================================
[2021-05-20T03:30:55.336Z] java/util/stream/test/org/openjdk/tests/java/util/stream/IntUniqOpTest.java
[2021-05-20T03:30:55.336Z] Total tests run: 73, Failures: 1, Skips: 0
[2021-05-20T03:30:55.336Z] ===============================================
...
[2021-05-20T03:30:55.337Z] --------------------------------------------------
[2021-05-20T03:35:15.516Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest.java
...
[2021-05-20T03:35:15.518Z] 1: java.lang.Error: PAR_STREAM_TO_ARRAY_CLEAR_SIZED: java.lang.OutOfMemoryError
...
[2021-05-20T03:35:15.521Z] ===============================================
[2021-05-20T03:35:15.521Z] java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest.java
[2021-05-20T03:35:15.521Z] Total tests run: 40, Failures: 1, Skips: 0
[2021-05-20T03:35:15.521Z] ===============================================
```

**Comment by JasonFengJ9** [comment]
Adding an IndexOutOfBoundsException from an internal build `Test_openjdk16_j9_special.system_aarch64_linux_testList_4/20/` (`ub18-aarch64-5`):
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Temurin-16.0.1+9-202105200404 (build 16.0.1+9-202105200404)
Eclipse OpenJ9 VM Temurin-16.0.1+9-202105200404 (build master-1549b5a8d, JRE 16 Linux aarch64-64-Bit Compressed References 20210520_35 (JIT enabled, AOT enabled)
OpenJ9   - 1549b5a8d
OMR      - 91436845b
JCL      - 50270bfb84 based on jdk-16.0.1+9)

[2021-05-20T07:54:06.767Z] Running test DaaLoadTest_daa2_special_5m_0 ...
[2021-05-20T07:54:06.768Z] ===============================================
[2021-05-20T07:54:06.768Z] DaaLoadTest_daa2_special_5m_0 Start Time: Thu May 20 03:54:05 2021 Epoch Time (ms): 1621497245978
[2021-05-20T07:54:06.768Z] "/home/jenkins/workspace/Test_openjdk16_j9_special.system_aarch64_linux_testList_4/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk16_j9_special.system_aarch64_linux_testList_4/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-20T07:54:06.768Z] JVMSHRC005I No shared class caches available
[2021-05-20T07:54:06.768Z] JVMSHRC005I No shared class caches available
[2021-05-20T07:54:06.768Z] cache cleanup done
[2021-05-20T07:54:06.768Z] variation: Mode101
[2021-05-20T07:54:06.768Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs 

[2021-05-20T07:54:33.255Z] DLT 03:54:31.791 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
[2021-05-20T07:54:33.255Z] DLT 03:54:31.798 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa2.xml
[2021-05-20T07:54:33.255Z] DLT 03:54:31.799 - suite.isCreateDump() : false
[2021-05-20T07:54:33.255Z] DLT 03:54:31.814 - Test failed
[2021-05-20T07:54:33.255Z] DLT   Failure num.  = 1
[2021-05-20T07:54:33.255Z] DLT   Test number   = 21
[2021-05-20T07:54:33.255Z] DLT   Test details  = 'JUnit[net.openj9.test.decimals.TestED2PD]'
[2021-05-20T07:54:33.255Z] DLT   Suite number  = 0
[2021-05-20T07:54:33.255Z] DLT   Thread number = 2
[2021-05-20T07:54:33.255Z] DLT >>> Captured test output >>>
[2021-05-20T07:54:33.255Z] DLT testStarted : testValidSignsEmbeddedTrailing(net.openj9.test.decimals.TestED2PD)
[2021-05-20T07:54:33.255Z] DLT testFinished: testValidSignsEmbeddedTrailing(net.openj9.test.decimals.TestED2PD)
[2021-05-20T07:54:33.255Z] DLT testStarted : testZeros(net.openj9.test.decimals.TestED2PD)
[2021-05-20T07:54:33.255Z] DLT testFinished: testZeros(net.openj9.test.decimals.TestED2PD)
[2021-05-20T07:54:33.255Z] DLT testStarted : testValidSignsSeparateLeadingOffsetSize17(net.openj9.test.decimals.TestED2PD)
[2021-05-20T07:54:33.255Z] DLT testFinished: testValidSignsSeparateLeadingOffsetSize17(net.openj9.test.decimals.TestED2PD)
[2021-05-20T07:54:33.255Z] DLT testStarted : testValidSignsSeparateLeadingOffsetSize31(net.openj9.test.decimals.TestED2PD)
[2021-05-20T07:54:33.255Z] DLT testFailure: testValidSignsSeparateLeadingOffsetSize31(net.openj9.test.decimals.TestED2PD): start 0, end 128321350, length 63
[2021-05-20T07:54:33.255Z] DLT java.lang.IndexOutOfBoundsException: start 0, end 128321350, length 63
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1802)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:680)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:214)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.math.BigInteger.smallToString(BigInteger.java:4044)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.math.BigInteger.toString(BigInteger.java:4073)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.math.BigInteger.toString(BigInteger.java:3968)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.math.BigInteger.toString(BigInteger.java:4142)
[2021-05-20T07:54:33.255Z] DLT 	at net.openj9.test.decimals.DecimalTestBase.constructED(DecimalTestBase.java:122)
[2021-05-20T07:54:33.255Z] DLT 	at net.openj9.test.decimals.DecimalTestBase.constructRandomED(DecimalTestBase.java:89)
[2021-05-20T07:54:33.255Z] DLT 	at net.openj9.test.decimals.TestED2PD.testValidSignsSeparateLeadingOffsetSize31(TestED2PD.java:416)
[2021-05-20T07:54:33.255Z] DLT 	at jdk.internal.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-20T07:54:33.255Z] DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2021-05-20T07:54:33.255Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2021-05-20T07:54:33.256Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2021-05-20T07:54:33.256Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2021-05-20T07:54:33.256Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2021-05-20T07:54:33.256Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[2021-05-20T07:54:33.256Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[2021-05-20T07:54:33.256Z] DLT 	at java.base/java.lang.Thread.run(Thread.java:878)

[2021-05-20T07:54:33.260Z] DaaLoadTest_daa2_special_5m_0_FAILED
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=DaaLoadTest_daa2_special_5m_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk16_j9_special.system_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=aarch64_linux&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-aarch64-openj9%2F35%2FOpenJDK16U-jdk_aarch64_linux_openj9_2021-05-20-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-aarch64-openj9%2F35%2FOpenJDK16U-testimage_aarch64_linux_openj9_2021-05-20-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-aarch64-openj9%2F35%2FOpenJDK16U-jre_aarch64_linux_openj9_2021-05-20-03-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-aarch64-openj9%2F35%2FOpenJDK16U-debugimage_aarch64_linux_openj9_2021-05-20-03-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=16&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk16&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=20&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by pshipton** [comment]
@knn-k fyi

**Comment by knn-k** [comment]
https://github.com/eclipse/omr/pull/6025 will fix this.

**Comment by knn-k** [comment]
After the fix from eclipse/omr#6025, the latest JDK8 sanity.openjdk is OK https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/226/

**Comment by knn-k** [comment]
eclipse/omr#6025 has fixed this issue. I think this issue can be closed now.

**Comment by JasonFengJ9** [comment]
Closing as per comment above.
