### ISSUE TITLE
aarch64_linux JCL_FVTest_SE80_Internal_0_FAILED AssertionError: FAILED :!!!, should=00000010FE at d7701.java:374

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12736]
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.functional_aarch64_linux/35/` (`ub18-aarch64-10`):
```
openjdk version "1.8.0_302-internal"
OpenJDK Runtime Environment (build 1.8.0_302-internal-202105200233-b02)
Eclipse OpenJ9 VM (build master-1549b5a8d, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20210520_119 (JIT enabled, AOT enabled)
OpenJ9   - 1549b5a8d
OMR      - 91436845b
JCL      - 8a9e812c based on jdk8u302-b02)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=JCL_FVTest_SE80_Internal_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=functional&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=aarch64_linux&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-debugimage_aarch64_linux_openj9_2021-05-20-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-jre_aarch64_linux_openj9_2021-05-20-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-testimage_aarch64_linux_openj9_2021-05-20-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F119%2FOpenJDK8U-jdk_aarch64_linux_openj9_2021-05-20-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-05-20T04:35:38.117Z] Running test JCL_FVTest_SE80_Internal_0 ...
[2021-05-20T04:35:38.117Z] ===============================================
[2021-05-20T04:35:38.117Z] JCL_FVTest_SE80_Internal_0 Start Time: Thu May 20 00:35:37 2021 Epoch Time (ms): 1621485337685
[2021-05-20T04:35:38.118Z] "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-20T04:35:38.118Z] JVMSHRC005I No shared class caches available
[2021-05-20T04:35:38.118Z] JVMSHRC005I No shared class caches available
[2021-05-20T04:35:38.118Z] cache cleanup done
[2021-05-20T04:35:38.118Z] variation: NoOptions
[2021-05-20T04:35:38.118Z] JVM_OPTIONS:  

[2021-05-20T04:38:45.991Z] FAILED: testMain
[2021-05-20T04:38:45.991Z] java.lang.AssertionError: FAILED :!!!, should=00000010FE010166393939393939393900000010FE0201660E3484B24A7333C40000000CFE0301662E8BF70500000049FE04016600891AE4042793CC1E266AE032B1F4BEA5472A339AD998BF313CAFD89CDBD8B8E06F315323C36B58A2143FDBB60C822840C8B33DAE37F27CDAE2073BDA412B2B79
[2021-05-20T04:38:45.991Z] 	at org.testng.Assert.fail(Assert.java:96)
[2021-05-20T04:38:45.991Z] 	at tests.com.ibm.jtc.lang.d7701.d7701.dec(d7701.java:374)
[2021-05-20T04:38:45.991Z] 	at tests.com.ibm.jtc.lang.d7701.d7701.testMain(d7701.java:390)
[2021-05-20T04:38:45.991Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-05-20T04:38:45.991Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-05-20T04:38:45.991Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-05-20T04:38:45.991Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-05-20T04:38:45.991Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2021-05-20T04:38:45.991Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2021-05-20T04:38:45.991Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2021-05-20T04:38:45.991Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2021-05-20T04:38:45.991Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-05-20T04:38:45.991Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2021-05-20T04:38:45.991Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2021-05-20T04:38:45.991Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2021-05-20T04:38:45.991Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2021-05-20T04:38:45.991Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2021-05-20T04:38:45.991Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-05-20T04:38:45.991Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2021-05-20T04:38:45.991Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2021-05-20T04:38:45.991Z] 
[2021-05-20T04:38:45.991Z] 
[2021-05-20T04:38:45.992Z] ===============================================
[2021-05-20T04:38:45.992Z]     JCL_FVTest
[2021-05-20T04:38:45.992Z]     Tests run: 688, Failures: 1, Skips: 0
[2021-05-20T04:38:45.992Z] ===============================================

[2021-05-20T04:38:45.992Z] JCL_FVTest_SE80_Internal_0_FAILED
```

**Comment by pshipton** [comment]
@knn-k fyi

**Comment by knn-k** [comment]
https://github.com/eclipse/omr/pull/6025 will fix this.

**Comment by knn-k** [comment]
eclipse/omr#6025 should have fixed this issue. I think this issue can be closed now.
