### ISSUE TITLE
jtreg java/util/zip/DeInflate.java inflate failures, length mismatch

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12740]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/40/
java/util/zip/DeInflate.java
Fails on Ubunut 20 machines ub20-390-1 and 2 (Eclipse jenkins ub16-390-1 and 2), passed on a ub18 machine. The failure is not related to the new OpenJDK level.
```
06:20:19  m=525312, n=498076, len=524288, eq=false
06:20:19  STDERR:
06:20:19  java.lang.RuntimeException: De/inflater failed:java.util.zip.Deflater@4b610026
06:20:19  	at DeInflate.check(DeInflate.java:141)
06:20:19  	at DeInflate.main(DeInflate.java:290)

06:31:28  m=525312, n=498093, len=524288, eq=false
06:31:28  STDERR:
06:31:28  java.lang.RuntimeException: De/inflater failed:java.util.zip.Deflater@5c1f2389
06:31:28  	at DeInflate.check(DeInflate.java:141)
06:31:28  	at DeInflate.main(DeInflate.java:290)

```

**Comment by pshipton** [comment]
@jdekonin is there any update for libz.so on the zlinux ub20 machines?

**Comment by keithc-ca** [comment]
Closed via above PRs.
