### ISSUE TITLE
JEP 411 Deprecate the Security Manager for Removal

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12760]
See https://openjdk.java.net/jeps/411

**Comment by pshipton** [comment]
@tajila fyi

**Comment by DanHeidinga** [comment]
Note in particular this bit of text which highlights the use of the `allow` & `disable` values for the SecurityManager `-D` property.  These were introduced in 12 but I don't recall seeing them before.  They may require extra attention from us or project stakeholders:

> If the Security Manager is not enabled on the command line then take the value of the system property java.security.manager to be "disallow" rather than null.
> 
> With "disallow" as the default value for this system property, the deprecated method java.lang.System::setSecurityManager will always throw an UnsupportedOperationException. Thus the Security Manager cannot be set dynamically by libraries or applications when the Security Manager is not enabled on the command line. To set the Security Manager dynamically, you must first enable it on the command line via java -Djava.security.manager=allow — which will produce a warning.

**Comment by JasonFengJ9** [comment]
Will followup this JEP.

**Comment by JasonFengJ9** [comment]
> Note in particular this bit of text which highlights the use of the allow & disable values for the SecurityManager -D property. These were introduced in 12 but I don't recall seeing them before. 

The PR in question was _JDK12 setSecurityManager according to java.security.manager special tokens_ https://github.com/eclipse-openj9/openj9/pull/4738

**Comment by tajila** [comment]
@JasonFengJ9 

We are seeing the following failure in jdk17 tests, https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/1/consoleFull

```
13:13:51  /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System/SecurityManagerWarnings.java:75: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
13:13:51                  System.setSecurityManager(new SecurityManager());
13:13:51                                                ^
13:13:51  1 warning
13:13:51  
13:13:51  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'WARNING: A terminally deprecated method in java.lang.System has been called' missing from stderr
13:13:51  REASON: Assumed action based on file name: run main SecurityManagerWarnings 
13:13:51  TIME:   0.612 seconds
13:13:51  messages:
13:13:51  command: main SecurityManagerWarnings
13:13:51  reason: Assumed action based on file name: run main SecurityManagerWarnings 
13:13:51  Mode: agentvm
13:13:51  Agent id: 13
13:13:51  elapsed time (seconds): 0.612
13:13:51  configuration:
```

**Comment by tajila** [comment]
Here is a description from the JEP

```
Deprecate APIs for removal

The Security Manager consists of the class java.lang.SecurityManager and a number of closely related APIs in the java.lang and java.security packages. We will terminally deprecate the following eight classes and two methods, by annotating them with @Deprecated(forRemoval=true):

    java.lang.SecurityManager — The primary API for the Security Manager.

    java.lang.System::{setSecurityManager, getSecurityManager} — Methods for setting and getting the Security Manager.

    java.security.{Policy, PolicySpi, Policy.Parameters} — The primary APIs for policy, which are used to determine if code running under the Security Manager has been granted permission to perform specific privileged operations.

    java.security.{AccessController, AccessControlContext, AccessControlException, DomainCombiner} — The primary APIs for the access controller, which is the default implementation to which the Security Manager delegates permission checks. These APIs do not have value without the Security Manager, since certain operations will not work without both a policy implementation and access-control context support in the VM.

We will also terminally deprecate the following two classes and eight methods which depend strongly on the Security Manager:

    java.lang.Thread::checkAccess, java.lang.ThreadGroup::checkAccess, and java.util.logging.LogManager::checkAccess — These three methods are anomalous because they allow ordinary Java code to check whether it would be trusted to perform certain operations without actually performing them. They serve no purpose without the Security Manager.

    java.util.concurrent.Executors::{privilegedCallable, privilegedCallableUsingCurrentClassLoader, privilegedThreadFactory} — These utility methods are only useful when the Security Manager is enabled.

    java.rmi.RMISecurityManager — RMI’s Security Manager class. This class is obsolete and was deprecated in Java 8.

    javax.security.auth.SubjectDomainCombiner and javax.security.auth.Subject::{doAsPrivileged, getSubject} — APIs for user-based authorization that are dependent on Security Manager APIs such as AccessControlContext and DomainCombiner. We plan to provide a replacement API for Subject::getSubject since it is commonly used for use cases that do not require the Security Manager, and to continue to support use cases involving Subject::doAs (see below).
```

**Comment by JasonFengJ9** [comment]
> 13:13:51  /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System/SecurityManagerWarnings.java:75: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
13:13:51                  System.setSecurityManager(new SecurityManager());
13:13:51                                                ^
13:13:51  1 warning
13:13:51  
13:13:51  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'WARNING: A terminally deprecated method in java.lang.System has been called' missing from stderr

I am wondering if this is because `openj9-staging` content hasn't been promoted yet.
Will have a closer look.

**Comment by JasonFengJ9** [comment]
> 13:13:51 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'WARNING: A terminally deprecated method in java.lang.System has been called' missing from stderr

Code change required for this.

**Comment by tajila** [comment]
@JasonFengJ9 We are seeing more failures:
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_OpenJDK17/3/testReport/junit/java_lang_System_SecurityManagerWarnings/java/SecurityManagerWarnings/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_OpenJDK17/3/testReport/junit/java_lang_System_SecurityManagerWarnings/java/SecurityManagerWarnings_2/

```
Stacktrace

Execution failed: `main' threw exception: java.lang.RuntimeException: 'WARNING: System::setSecurityManager has been called by A (file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_OpenJDK17/aqa-tests/TKG/output_16262704986844/jdk_lang_0/work/classes/2/java/lang/System/SecurityManagerWarnings.d/)' missing from stderr    

Standard Output

[2021-07-14T14:59:29.913392614Z] Gathering output for process 16771
[2021-07-14T14:59:31.844803067Z] Waiting for completion for process 16771
[2021-07-14T14:59:31.845226489Z] Waiting for completion finished for process 16771
Output and diagnostic info for process 16771 was saved into 'pid-16771-output.log'
[2021-07-14T14:59:32.225550562Z] Waiting for completion for process 16771
[2021-07-14T14:59:32.225851437Z] Waiting for completion finished for process 16771
    

Standard Error

 stdout: [SM is enabled: false
];
 stderr: [WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by B (file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_OpenJDK17/aqa-tests/TKG/output_16262704986844/jdk_lang_0/work/classes/2/java/lang/System/SecurityManagerWarnings.d/)
WARNING: Please consider reporting this to the maintainers of B
WARNING: System::setSecurityManager will be removed in a future release
]
 exitValue = 0

java.lang.RuntimeException: 'WARNING: System::setSecurityManager has been called by A (file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_OpenJDK17/aqa-tests/TKG/output_16262704986844/jdk_lang_0/work/classes/2/java/lang/System/SecurityManagerWarnings.d/)' missing from stderr 

	at jdk.test.lib.process.OutputAnalyzer.stderrShouldContain(OutputAnalyzer.java:251)
	at SecurityManagerWarnings.checkInstallMessage(SecurityManagerWarnings.java:123)
	at SecurityManagerWarnings.allowTest(SecurityManagerWarnings.java:93)
	at SecurityManagerWarnings.main(SecurityManagerWarnings.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.base/java.lang.Thread.run(Thread.java:883)

JavaTest Message: Test threw exception: java.lang.RuntimeException
```

**Comment by JasonFengJ9** [comment]
> We are seeing more failures:

My local test setup gave false pass, re-creating the workspace reproduced the failures above. Sorry.
Investigating ..

**Comment by JasonFengJ9** [comment]
`TEST: java/lang/System/SecurityManagerWarnings.java` failed at https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OpenJDK17/4/consoleFull

Looking..

**Comment by JasonFengJ9** [comment]
> TEST: java/lang/System/SecurityManagerWarnings.java failed at https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OpenJDK17/4/consoleFull

```
18:51:19  openjdk version "17-internal" 2021-09-14
18:51:19  OpenJDK Runtime Environment (build 17-internal+0-adhoc.****.BuildJDK17x86-64linuxOpenJDK17)
18:51:19  Eclipse OpenJ9 VM (build master-8393a7277cb, JRE 17 Linux amd64-64-Bit Compressed References 20210721_9 (JIT enabled, AOT enabled)
18:51:19  OpenJ9   - 8393a7277cb
18:51:19  OMR      - c1cfe33edbb
18:51:19  JCL      - 73df431af63 based on jdk-17+31)
```
This VM was built one commit earlier than https://github.com/eclipse-openj9/openj9/pull/13200

```
... newer...
98bd7c67734e51bbeb10b8a8c5797f56e5874ace (origin/rmsm2, rmsm2) JDK17+ show setSecurityManager message once for each caller class
8393a7277cbd664acc8c9477d66b2dc9a9d6f412 Merge pull request #13183 from tajila/doc
... earlier ...
```
Next build should include the PR in question and pass the test.

**Comment by tajila** [comment]
Latests run shows tests are passing

**Comment by pshipton** [comment]
Can this be closed then?

**Comment by tajila** [comment]
Yes
