### ISSUE TITLE
JDK11 Windows jdk_imageio_0_FAILED : some classloaders weren't destroyed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12796]
Failure link
------------

From an internal build `Test_openjdk11_j9_extended.openjdk_x86-64_windows/13/` (`win16x64cudart1 `):
```
java version "11.0.12" 2021-07-20
Java(TM) SE Runtime Environment 11.0.12.0-IBM (build 11.0.12+4)
Eclipse OpenJ9 VM 11.0.12.0-IBM (build master-262b10ca7, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20210529_86 (JIT enabled, AOT enabled)
OpenJ9   - 262b10ca7
OMR      - e358cd0e5
JCL      - 34925c161a based on jdk-11.0.12+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_imageio_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-64_windows&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F86%2FOpenJDK11U-jre_x64_windows_openj9_IBM_2021-05-29-01-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F86%2FOpenJDK11U-jdk_x64_windows_openj9_IBM_2021-05-29-01-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F86%2FOpenJDK11U-testimage_x64_windows_openj9_IBM_2021-05-29-01-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F86%2FOpenJDK11U-debugimage_x64_windows_openj9_IBM_2021-05-29-01-00.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-05-29T13:16:13.878Z] Running test jdk_imageio_0 ...
[2021-05-29T13:16:13.878Z] ===============================================
[2021-05-29T13:16:13.878Z] jdk_imageio_0 Start Time: Sat May 29 09:16:12 2021 Epoch Time (ms): 1622294172805
[2021-05-29T13:16:14.563Z] "C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-29T13:16:14.563Z] 
[2021-05-29T13:16:14.563Z] Attempting to destroy all caches in cacheDir C:\Users\jenkins\AppData\Local\javasharedresources\
[2021-05-29T13:16:14.563Z] 
[2021-05-29T13:16:14.563Z] JVMSHRC241E Error: unable to delete shared class cache file
[2021-05-29T13:16:14.563Z] JVMSHRC336E Port layer error code = -100
[2021-05-29T13:16:14.563Z] JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
[2021-05-29T13:16:14.563Z] JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_jenkins"
[2021-05-29T13:16:14.563Z] 
[2021-05-29T13:16:14.563Z] Attempting to destroy all caches in cacheDir C:\Users\jenkins\AppData\Local\javasharedresources\
[2021-05-29T13:16:14.563Z] 
[2021-05-29T13:16:14.563Z] JVMSHRC241E Error: unable to delete shared class cache file
[2021-05-29T13:16:14.563Z] JVMSHRC336E Port layer error code = -100
[2021-05-29T13:16:14.563Z] JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
[2021-05-29T13:16:14.563Z] JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_jenkins"
[2021-05-29T13:16:15.248Z] cache cleanup done
[2021-05-29T13:16:15.248Z] variation: Mode150
[2021-05-29T13:16:15.248Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-05-29T13:27:23.550Z] The test failed :-(
[2021-05-29T13:27:23.550Z] exit status was 1
[2021-05-29T13:27:23.550Z] STDERR:
[2021-05-29T13:27:23.550Z] C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 125: cd: /Temp: No such file or directory
[2021-05-29T13:27:23.550Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2021-05-29T13:27:23.550Z] 	at test.Main.main(Main.java:162)
[2021-05-29T13:27:23.550Z] Test FAILED: some classloaders weren't destroyed.

[2021-05-29T13:27:23.550Z] TEST RESULT: Failed. Execution failed: exit code 1
[2021-05-29T13:27:23.550Z] --------------------------------------------------
[2021-05-29T13:28:55.593Z] Test results: passed: 191; failed: 1
[2021-05-29T13:29:16.636Z] Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
[2021-05-29T13:29:16.636Z] Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\openjdk-tests\TKG\output_16222729139555\jdk_imageio_0\work
[2021-05-29T13:29:16.636Z] Error: Some tests failed or other problems occurred.
[2021-05-29T13:29:17.323Z] 
[2021-05-29T13:29:17.323Z] jdk_imageio_0_FAILED
```

**Comment by pshipton** [comment]
This test is depending on GC behavior. Looks like it waits for 10 sec, doing a GC every second. 
Does it consistently or intermittently fail?

jdk_imageio_0 is -XX:+UseCompressedOops 
```
09:27:23  STDOUT:
09:27:23  JDK under test is: C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_windows/openjdkbinary/j2sdk-image
09:27:23  Create TestApp.jar...
09:27:23  added manifest
09:27:23  adding: testapp/(in = 0) (out= 0)(stored 0%)
09:27:23  adding: testapp/Main$MyImageInputStream.class(in = 1282) (out= 653)(deflated 49%)
09:27:23  adding: testapp/Main.class(in = 2016) (out= 1007)(deflated 50%)
09:27:23  adding: testapp/Test.class(in = 902) (out= 516)(deflated 42%)
09:27:23  Create Test.jar...
09:27:23  added manifest
09:27:23  adding: test/(in = 0) (out= 0)(stored 0%)
09:27:23  adding: test/Main$1.class(in = 777) (out= 510)(deflated 34%)
09:27:23  adding: test/Main$2.class(in = 2345) (out= 1219)(deflated 48%)
09:27:23  adding: test/Main$MyClassLoader.class(in = 1665) (out= 853)(deflated 48%)
09:27:23  adding: test/Main.class(in = 6323) (out= 3337)(deflated 47%)
09:27:23  Current context class loader: jdk.internal.loader.ClassLoaders$AppClassLoader@e2f7fd5e
09:27:23  testapp/Uniq0: launch the app
09:27:23  testapp/Uniq1: launch the app
09:27:23  testapp/Uniq2: launch the app
09:27:23  testapp/Uniq3: launch the app
09:27:23  testapp/Uniq4: launch the app
09:27:23  testapp/Uniq5: launch the app
09:27:23  testapp/Uniq6: launch the app
09:27:23  testapp/Uniq7: launch the app
09:27:23  testapp/Uniq8: launch the app
09:27:23  testapp/Uniq9: launch the app
09:27:23  testapp/Uniq10: launch the app
09:27:23  testapp/Uniq1: current context class loader: MyClassLoader(testapp/Uniq1)
09:27:23  testapp/Uniq3: current context class loader: MyClassLoader(testapp/Uniq3)
09:27:23  testapp/Uniq11: launch the app
09:27:23  testapp/Uniq0: current context class loader: MyClassLoader(testapp/Uniq0)
09:27:23  testapp/Uniq12: launch the app
09:27:23  testapp/Uniq13: launch the app
09:27:23  testapp/Uniq14: launch the app
09:27:23  testapp/Uniq4: current context class loader: MyClassLoader(testapp/Uniq4)
09:27:23  testapp/Uniq15: launch the app
09:27:23  testapp/Uniq6: current context class loader: MyClassLoader(testapp/Uniq6)
09:27:23  testapp/Uniq5: current context class loader: MyClassLoader(testapp/Uniq5)
09:27:23  testapp/Uniq9: current context class loader: MyClassLoader(testapp/Uniq9)
09:27:23  testapp/Uniq16: launch the app
09:27:23  testapp/Uniq2: current context class loader: MyClassLoader(testapp/Uniq2)
09:27:23  testapp/Uniq17: launch the app
09:27:23  testapp/Uniq18: launch the app
09:27:23  testapp/Uniq14: current context class loader: MyClassLoader(testapp/Uniq14)
09:27:23  testapp/Uniq15: current context class loader: MyClassLoader(testapp/Uniq15)
09:27:23  testapp/Uniq19: launch the app
09:27:23  testapp/Uniq10: current context class loader: MyClassLoader(testapp/Uniq10)
09:27:23  Wait for apps completion....
09:27:23  testapp/Uniq12: current context class loader: MyClassLoader(testapp/Uniq12)
09:27:23  testapp/Uniq7: current context class loader: MyClassLoader(testapp/Uniq7)
09:27:23  testapp/Uniq13: current context class loader: MyClassLoader(testapp/Uniq13)
09:27:23  testapp/Uniq16: current context class loader: MyClassLoader(testapp/Uniq16)
09:27:23  testapp/Uniq19: current context class loader: MyClassLoader(testapp/Uniq19)
09:27:23  testapp/Uniq18: current context class loader: MyClassLoader(testapp/Uniq18)
09:27:23  testapp/Uniq8: current context class loader: MyClassLoader(testapp/Uniq8)
09:27:23  testapp/Uniq11: current context class loader: MyClassLoader(testapp/Uniq11)
09:27:23  testapp/Uniq17: current context class loader: MyClassLoader(testapp/Uniq17)
09:27:23  All apps finished.
09:27:23  Enumerate strong refs:
09:27:23  =======================
09:27:23  Wait testapp/Uniq17: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq17: test is done!
09:27:23  testapp/Uniq4: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq4: test is done!
09:27:23  testapp/Uniq14: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq14: test is done!
09:27:23  testapp/Uniq3: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq3: test is done!
09:27:23  testapp/Uniq2: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq2: test is done!
09:27:23  testapp/Uniq6: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq6: test is done!
09:27:23  testapp/Uniq7: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq7: test is done!
09:27:23  testapp/Uniq15: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq15: test is done!
09:27:23  testapp/Uniq10: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq10: test is done!
09:27:23  testapp/Uniq16: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq16: test is done!
09:27:23  testapp/Uniq8: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq8: test is done!
09:27:23  testapp/Uniq9: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq9: test is done!
09:27:23  testapp/Uniq11: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq11: test is done!
09:27:23  testapp/Uniq13: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq13: test is done!
09:27:23  testapp/Uniq19: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq19: test is done!
09:27:23  testapp/Uniq5: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq5: test is done!
09:27:23  testapp/Uniq1: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq1: test is done!
09:27:23  testapp/Uniq18: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq18: test is done!
09:27:23  testapp/Uniq12: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq12: test is done!
09:27:23  testapp/Uniq0: Current thread: Thread[Finalizer thread,5,system]
09:27:23  testapp/Uniq0: test is done!
09:27:23  .+..+..+..
09:27:23  Wait for workaround completion...
09:27:23  Wait .+..+..+..
09:27:23  Classloaders still alive:
09:27:23  ->testapp/Uniq15
09:27:23  The test failed :-(
09:27:23  exit status was 1
```

**Comment by JasonFengJ9** [comment]
> Does it consistently or intermittently fail?

It is intermittent but was able to reproduce once at `Grinder/15781`.

**Comment by pshipton** [comment]
As I understand it then, it fails consistently on the win16x64cudart1 machine. 

@dmitripivkine fyi, not sure if this is a real issue on this machine, or a bad test.

**Comment by dmitripivkine** [comment]
> As I understand it then, it fails consistently on the win16x64cudart1 machine.
> 
> @dmitripivkine fyi, not sure if this is a real issue on this machine, or a bad test.

Is there source code for this test around? I believe I looked to this (or similar) test before. There is no guarantee Global GC is going to perform class unloading in Dynamic Class Unloading mode (default). If test is looking for real class unloading (not some bogus criteria) running with `-Xalwaysclassgc` might help. Dynamic Class Unloading taking to consideration number of classes loaded **since last Global GC**, so it might depend from machine configuration indirectly. For example if `-Xmx` is not provided default heap size is 25% or RAM (vary machine to machine). GC frequency depends on heap size obviously and might create unfortunate time pattern for this test

**Comment by pshipton** [comment]
The test source is here https://github.com/ibmruntimes/openj9-openjdk-jdk11/tree/openj9/test/jdk/javax/imageio/stream/StreamCloserLeak

**Comment by JasonFengJ9** [comment]
Appeared at a JDK11 `0.30.0` release build `job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/46/`(`win16x64cudart1`)
```
java version "11.0.14" 2022-01-18
IBM Semeru Runtime Certified Edition 11.0.14.0 (build 11.0.14+9)
Eclipse OpenJ9 VM 11.0.14.0 (build openj9-0.30.0, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20220131_240 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 00ad19e9d5 based on jdk-11.0.14+9)

[2022-01-31T23:24:40.771Z] STDERR:
[2022-01-31T23:24:40.771Z] C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\test\jdk\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 125: cd: /Temp: No such file or directory
[2022-01-31T23:24:40.771Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2022-01-31T23:24:40.771Z] 	at test.Main.main(Main.java:162)
[2022-01-31T23:24:40.771Z] Test FAILED: some classloaders weren't destroyed.
```

**Comment by JasonFengJ9** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/76/)(`win10x64vs6`)
```
[2022-09-01T12:05:31.495Z] variation: Mode150
[2022-09-01T12:05:31.885Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-09-01T12:09:33.036Z] TEST: javax/imageio/stream/StreamCloserLeak/run_test.sh

[2022-09-01T12:09:33.039Z] STDERR:
[2022-09-01T12:09:33.040Z] C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\test\jdk\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 125: cd: /Temp: No such file or directory
[2022-09-01T12:09:33.040Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2022-09-01T12:09:33.040Z] 	at test.Main.main(Main.java:162)
[2022-09-01T12:09:33.040Z] Test FAILED: some classloaders weren't destroyed.

[2022-09-01T12:09:33.041Z] TEST RESULT: Failed. Execution failed: exit code 1
[2022-09-01T12:09:33.041Z] --------------------------------------------------
[2022-09-01T12:09:33.041Z] Test results: passed: 195; failed: 1
[2022-09-01T12:09:52.941Z] Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16620211595350\jdk_imageio_0\report\html\report.html
[2022-09-01T12:09:52.941Z] Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16620211595350\jdk_imageio_0\work
[2022-09-01T12:09:52.941Z] Error: Some tests failed or other problems occurred.
[2022-09-01T12:09:52.941Z] 
[2022-09-01T12:09:52.941Z] jdk_imageio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK8 0.35 rc1 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/74/)(`win10x64vs6`)
```
[2022-10-21T02:10:48.163Z] variation: Mode150
[2022-10-21T02:10:48.163Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-10-21T02:12:52.171Z] TEST: javax/imageio/stream/StreamCloserLeak/run_test.sh

[2022-10-21T02:12:52.172Z] STDERR:
[2022-10-21T02:12:52.173Z] C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 124: cd: /Temp: No such file or directory
[2022-10-21T02:12:52.173Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2022-10-21T02:12:52.173Z] 	at test.Main.main(Main.java:162)
[2022-10-21T02:12:52.173Z] Test FAILED: some classloaders weren't destroyed.

[2022-10-21T02:12:52.173Z] TEST RESULT: Failed. Execution failed: exit code 1
[2022-10-21T02:12:52.173Z] --------------------------------------------------
[2022-10-21T02:12:52.173Z] Test results: passed: 143; failed: 1
[2022-10-21T02:13:03.569Z] Report written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_1666314366347\jdk_imageio_0\report\html\report.html
[2022-10-21T02:13:03.569Z] Results written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_1666314366347\jdk_imageio_0\work
[2022-10-21T02:13:03.569Z] Error: Some tests failed or other problems occurred.
[2022-10-21T02:13:03.569Z] 
[2022-10-21T02:13:03.569Z] jdk_imageio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK8 0.36.0 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/84/)(`win10x64vs6`)
```
[2023-01-14T18:30:40.891Z] variation: Mode150
[2023-01-14T18:30:41.267Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-01-14T18:32:47.078Z] TEST: javax/imageio/stream/StreamCloserLeak/run_test.sh

[2023-01-14T18:32:47.080Z] STDERR:
[2023-01-14T18:32:47.080Z] C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 124: cd: /Temp: No such file or directory
[2023-01-14T18:32:47.080Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2023-01-14T18:32:47.080Z] 	at test.Main.main(Main.java:162)
[2023-01-14T18:32:47.080Z] Test FAILED: some classloaders weren't destroyed.

[2023-01-14T18:32:58.672Z] jdk_imageio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK11 x86-64_windows rc1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/124/)
```
[2023-07-20T09:01:41.275Z] variation: Mode650
[2023-07-20T09:01:41.275Z] JVM_OPTIONS:  -XX:-UseCompressedOops

[2023-07-20T09:26:10.617Z] TEST: javax/imageio/stream/StreamCloserLeak/run_test.sh

[2023-07-20T09:26:10.619Z] STDERR:
[2023-07-20T09:26:10.619Z] C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\test\jdk\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 125: cd: /Temp: No such file or directory
[2023-07-20T09:26:10.619Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2023-07-20T09:26:10.619Z] 	at test.Main.main(Main.java:162)
[2023-07-20T09:26:10.619Z] Test FAILED: some classloaders weren't destroyed.

[2023-07-20T09:30:34.600Z] jdk_imageio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK11 s390x_linux 0.41 milestone 1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_s390x_linux/158/)(`rhel7s390x-3-6`)
```
[2023-09-06T06:52:43.397Z] variation: Mode150
[2023-09-06T06:52:43.397Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-09-06T06:56:39.821Z] TEST: javax/imageio/stream/StreamCloserLeak/run_test.sh

[2023-09-06T06:56:39.822Z] .Test FAILED!
[2023-09-06T06:56:39.822Z] java.io.IOException: Stream Closed
[2023-09-06T06:56:39.822Z] 	at java.base/java.io.RandomAccessFile.read0(Native Method)
[2023-09-06T06:56:39.822Z] 	at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:366)
[2023-09-06T06:56:39.822Z] 	at java.desktop/javax.imageio.stream.FileCacheImageInputStream.read(FileCacheImageInputStream.java:166)
[2023-09-06T06:56:39.822Z] 	at <unknown class>.<unknown method>(Unknown Source)
[2023-09-06T06:56:39.822Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-09-06T06:56:39.823Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-09-06T06:56:39.823Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-09-06T06:56:39.823Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-09-06T06:56:39.823Z] 	at test.Main$2.run(Main.java:232)
[2023-09-06T06:56:39.823Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-09-06T06:56:39.823Z] The test failed :-(
[2023-09-06T06:56:39.823Z] exit status was 1
[2023-09-06T06:56:39.823Z] STDERR:
[2023-09-06T06:56:39.823Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED
[2023-09-06T06:56:39.823Z] 	at test.Main.checkErrors(Main.java:199)
[2023-09-06T06:56:39.823Z] 	at test.Main.waitAndGC(Main.java:186)
[2023-09-06T06:56:39.823Z] 	at test.Main.main(Main.java:116)
[2023-09-06T06:56:39.823Z] Test FAILED: some classloaders weren't destroyed.

[2023-09-06T06:56:39.823Z] TEST RESULT: Failed. Execution failed: exit code 1
[2023-09-06T06:56:39.823Z] --------------------------------------------------
[2023-09-06T06:57:30.597Z] Test results: passed: 196; failed: 1
[2023-09-06T06:57:31.119Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16939741947739/jdk_imageio_0/report/html/report.html
[2023-09-06T06:57:31.119Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16939741947739/jdk_imageio_0/work
[2023-09-06T06:57:31.119Z] Error: Some tests failed or other problems occurred.
[2023-09-06T06:57:31.119Z] -----------------------------------
[2023-09-06T06:57:31.119Z] jdk_imageio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK8 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/118/)(`win19x86-svl-rt3-1`)
```
openjdk version "1.8.0_392"
IBM Semeru Runtime Open Edition (build 1.8.0_392-b08)
Eclipse OpenJ9 VM (build v0.41.0-release-9c5799b80, JRE 1.8.0 Windows Server 2019 amd64-64-Bit Compressed References 20231018_794 (JIT enabled, AOT enabled)
OpenJ9   - 9c5799b80
OMR      - fa7b6ddc7
JCL      - b73cbdd342 based on jdk8u392-b08)

[2023-10-19T01:39:35.389Z] variation: Mode150
[2023-10-19T01:39:35.389Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-10-19T01:51:58.016Z] STDERR:
[2023-10-19T01:51:58.016Z] C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 124: cd: /Temp: No such file or directory
[2023-10-19T01:51:58.016Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2023-10-19T01:51:58.016Z] 	at test.Main.main(Main.java:162)
[2023-10-19T01:51:58.016Z] Test FAILED: some classloaders weren't destroyed.

[2023-10-19T01:51:58.017Z] TEST RESULT: Failed. Execution failed: exit code 1
[2023-10-19T01:51:58.017Z] --------------------------------------------------
[2023-10-19T01:55:10.119Z] Test results: passed: 143; failed: 1
[2023-10-19T01:55:30.329Z] Report written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16976676245304\jdk_imageio_0\report\html\report.html
[2023-10-19T01:55:30.329Z] Results written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16976676245304\jdk_imageio_0\work
[2023-10-19T01:55:30.329Z] Error: Some tests failed or other problems occurred.
[2023-10-19T01:55:31.303Z] -----------------------------------
[2023-10-19T01:55:31.303Z] jdk_imageio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_extended.openjdk_x86-32_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-32_windows_testList_1/211/)
```
[2025-05-02T01:30:31.432Z] variation: Mode1000
[2025-05-02T01:30:31.838Z] JVM_OPTIONS:  -Xverbosegclog 

[2025-05-02T01:40:04.700Z] TEST: javax/imageio/stream/StreamCloserLeak/run_test.sh

[2025-05-02T01:40:04.705Z] STDERR:
[2025-05-02T01:40:04.705Z] C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows_testList_1\aqa-tests\openjdk\openjdk-jdk\jdk\test\javax\imageio\stream\StreamCloserLeak\run_test.sh: line 124: cd: /Temp: No such file or directory
[2025-05-02T01:40:04.705Z] Exception in thread "main" java.lang.RuntimeException: Test FAILED: exta class loader is detected! 
[2025-05-02T01:40:04.705Z] 	at test.Main.main(Main.java:162)
[2025-05-02T01:40:04.705Z] Test FAILED: some classloaders weren't destroyed.

[2025-05-02T01:42:34.978Z] jdk_imageio_2_FAILED
```
