### ISSUE TITLE
testDDRExtJunit_FindExtThread_0 and testDDRExtJunit_StackMap_0 failing

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12814]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/13/
testDDRExtJunit_FindExtThread_0 
```
     [java] [AutoRun] [INFO] Starting testLocalmap(j9vm.test.ddrext.junit.TestThread)
     [java] [AutoRun] [INFO] Finished testLocalmap(j9vm.test.ddrext.junit.TestThread)
     [java] 
     [java] [AutoRun] [INFO] ================Test Result for /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/openjdk-tests/TKG/../TKG/output_1622598050840/testDDRExtJunit_FindExtThread_0/DDREXT.J9CORE.DMP==================
     [java] [AutoRun] [INFO] Errors:   1 out of 13 test cases.
     [java] [AutoRun] [INFO] Failures: 0 out of 13 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 1
     [java] java.lang.NullPointerException: Cannot invoke "java.lang.String.split(java.lang.String)" because "results" is null
     [java] 	at j9vm.test.ddrext.junit.TestThread.getStackSlotsValues(TestThread.java:234)
     [java] 	at j9vm.test.ddrext.junit.TestThread.testLocalmap(TestThread.java:196)
```
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_1/13/
testDDRExtJunit_StackMap_0
```
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!stackmap  0x000003FF926B5E32'
     [java] [AutoRun] [INFO] Finished testStackMap(j9vm.test.ddrext.junit.TestStackMap)
     [java] 
     [java] [AutoRun] [INFO] ================Test Result for /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_1/openjdk-tests/TKG/../TKG/output_16225980202002/testDDRExtJunit_StackMap_0/DDREXT.J9CORE.DMP==================
     [java] [AutoRun] [INFO] Errors:   0 out of 1 test cases.
     [java] [AutoRun] [INFO] Failures: 1 out of 1 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 1
     [java] [DDRExtTesterBase] [ERROR] '!stackmap  0x000003FF926B5E32' output does not contain success key : Found method
     [java] [DDRExtTesterBase] [ERROR] '!stackmap  0x000003FF926B5E32' output :Searching for PC=4396208053810 in VM=0x000003FFAC028AC0...
     [java] Not found
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestStackMap.testStackMap(TestStackMap.java:163)
```

Changes:
https://github.com/eclipse-openj9/openj9/compare/0baea3a...0c5a581
https://github.com/eclipse-openj9/openj9-omr/compare/39f680a...c086f16

I'll narrow it down tomorrow.

**Comment by JasonFengJ9** [comment]
Also seen in last night internal build `Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_2/51/`
```
openjdk version "1.8.0_302-internal"
OpenJDK Runtime Environment (build 1.8.0_302-internal-202106020233-b04)
Eclipse OpenJ9 VM (build master-4d607679e, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20210601_126 (JIT enabled, AOT enabled)
OpenJ9   - 4d607679e
OMR      - c086f1671
JCL      - 82bd60f0 based on jdk8u302-b04)

[2021-06-02T04:34:10.797Z] Running test testDDRExtJunit_StackMap_0 ...
[2021-06-02T04:34:10.797Z] ===============================================
[2021-06-02T04:34:10.797Z] testDDRExtJunit_StackMap_0 Start Time: Tue Jun  1 21:34:10 2021 Epoch Time (ms): 1622608450143
[2021-06-02T04:34:10.797Z] "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-06-02T04:34:10.797Z] JVMSHRC005I No shared class caches available
[2021-06-02T04:34:10.797Z] JVMSHRC005I No shared class caches available
[2021-06-02T04:34:10.797Z] cache cleanup done
[2021-06-02T04:34:10.797Z] variation: NoOptions
[2021-06-02T04:34:10.797Z] JVM_OPTIONS:  

[2021-06-02T04:34:28.809Z]      [java] junit.framework.AssertionFailedError
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.Assert.fail(Assert.java:48)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
[2021-06-02T04:34:28.809Z]      [java] 	at j9vm.test.ddrext.junit.TestStackMap.testStackMap(TestStackMap.java:163)
[2021-06-02T04:34:28.809Z]      [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-02T04:34:28.809Z]      [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-06-02T04:34:28.809Z]      [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-02T04:34:28.809Z]      [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.TestResult.run(TestResult.java:113)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.TestCase.run(TestCase.java:124)
[2021-06-02T04:34:28.809Z]      [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
[2021-06-02T04:34:28.809Z]      [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
[2021-06-02T04:34:28.809Z]      [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
[2021-06-02T04:34:28.809Z]      [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
[2021-06-02T04:34:28.809Z]      [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
[2021-06-02T04:34:28.809Z]      [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
[2021-06-02T04:34:28.809Z]      [java] [AutoRun] [ERROR] testStackMap(j9vm.test.ddrext.junit.TestStackMap)
[2021-06-02T04:34:28.809Z] 
[2021-06-02T04:34:28.809Z] BUILD FAILED
[2021-06-02T04:34:28.809Z] /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_2/jvmtest/functional/DDR_Test/tck_ddrext.xml:152: The following error occurred while executing this line:
[2021-06-02T04:34:28.809Z] /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_2/jvmtest/functional/DDR_Test/tck_ddrext.xml:124: Java returned: 254
[2021-06-02T04:34:28.809Z] 
[2021-06-02T04:34:28.809Z] Total time: 17 seconds
[2021-06-02T04:34:28.809Z] 
[2021-06-02T04:34:28.809Z] testDDRExtJunit_StackMap_0_FAILED
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=testDDRExtJunit_StackMap_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_extended.functional_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=functional&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=ppc64le_linux&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F126%2FOpenJDK8U-jre_ppc64le_linux_openj9_2021-06-02-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F126%2FOpenJDK8U-debugimage_ppc64le_linux_openj9_2021-06-02-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F126%2FOpenJDK8U-jdk_ppc64le_linux_openj9_2021-06-02-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F126%2FOpenJDK8U-testimage_ppc64le_linux_openj9_2021-06-02-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=78&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by pshipton** [comment]
I've reverted https://github.com/eclipse-openj9/openj9/pull/12793 to resolve this.
