### ISSUE TITLE
Invalid class accepted by J9 but rejected by hotspot

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#12828]
### Summary
We inserted the code segment of the main function in the Obj class into the test case VE1. When the newly generated class was executed, hotspot threw a VerifyError, as shown below, but J9 accepted the class normally.  The simplified test case can be found in the attachment. 
```
public class Obj {

    public static void main(String[] args) throws CloneNotSupportedException {

        Obj p1= new Obj();
        p1.clone();
    }
}
```

```
public class VE1 {

    public static void main(String[] args) {
        //do nothing
    }

    private static void m1() {
        //insert here
    }
}
```

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    VE1.m1()V @9: invokevirtual
  Reason:
    Type 'Obj' (current frame, stack[0]) is not assignable to 'VE1'
  Current Frame:
    bci: @9
    flags: { }
    locals: { 'Obj' }
    stack: { 'Obj' }
  Bytecode:
    0x0000000: bb00 0459 b700 034b 2ab6 0002 b1       

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
```

### How to reproduce?
[VE1.zip](https://github.com/eclipse-openj9/openj9/files/6591263/VE1.zip)

Follow the commands in readme.

### Affected versions
macOS:
```
macOS Big Sur
Version 11.2.3 (20D91)
Processor 2.3 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3
```

Java -version output under macOS
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201022_737 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10)
```

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210120_897 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
```

Windows 10:
```
Microsoft Windows 10 Professional
10.0.16299 Build 16299
Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz 2.90 GHz
Memory 8 GB
```

Java -version output under Windows 10
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Windows 10 x86-32-Bit 20201112_759 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - b52d2ff7ee based on jdk8u275-b01)
```

**Comment by pshipton** [comment]
@tajila @ChengJin01 fyi

**Comment by ChengJin01** [comment]
Looking at the test code:
```
public class VE1 {

    public static void main(String[] args) {
        //do nothing
    }

    private static void m1() {
       Obj p1= new Obj();
        p1.clone();
    }
}
```
which fails in compilation as expected according to the definition of `protected` in the Java Language Spec because `VE1` is only able to call its' clone() derived from `Object` rather than `p1.clone()` when`VE1` and `Object` are not in the same package.
```
Javac  VE1.java
VE1.java:9: error: clone() has protected access in Object
        p1.clone();
          ^
```
Thus, the error should also be captured from VM perspective. I will need to check the verifier to see what we can do to deal with the error.

**Comment by ChengJin01** [comment]
Looking at the bytecode snippet of VE1:
```
  private static void m1();
    descriptor: ()V
    flags: (0x000a) ACC_PRIVATE, ACC_STATIC
    Code:
      stack=2, locals=1, args_size=0
         0: new           #4                  // class Obj
         3: dup
         4: invokespecial #3                  // Method Obj."<init>":()V
         7: astore_0
         8: aload_0
         9: invokevirtual #2   // Method java/lang/Object.clone:()Ljava/lang/Object; <--- verification error should be captured here
        12: return
```
against our code at /runtime/bcverify/rtverify.c
```
static IDATA 
verifyBytecodes (J9BytecodeVerificationData * verifyData)
{
...
 case JBinvokevirtual:
 rc = isProtectedAccessPermitted (verifyData, J9ROMSTRINGREF_UTF8DATA(classRef), type,
				 J9ROMMETHODREF_NAMEANDSIGNATURE((J9ROMMethodRef *) info), FALSE, &reasonCode);
...
```
and the code of `isProtectedAccessPermitted ` at /runtime/bcverify/vrfyhelp.c
```
UDATA 
isProtectedAccessPermitted(J9BytecodeVerificationData *verifyData, J9UTF8* declaringClassName, UDATA targetClass, void* member, UDATA isField, IDATA *reasonCode )
{
...
	/* for performance reasons, don't do protection checks unless -Xfuture or -Xverify:doProtectedAccessCheck is specified */
	if ((0 == (verifyData->vmStruct->javaVM->runtimeFlags & J9RuntimeFlagXfuture)) 
	&& (0 == (verifyData->verificationFlags & J9_VERIFY_DO_PROTECTED_ACCESS_CHECK))
	) {
		return TRUE;
	}
...
		/* Determine if the defining class is the same class or a super class of current class */
		if (isSameOrSuperClassOf(definingRamClass, currentRamClass)) {
			U_8 * targetClassName = NULL;
			UDATA targetClassLength = 0;
			J9Class * targetRamClass = NULL;

			/* NULL is compatible */
			if (targetClass != BCV_BASE_TYPE_NULL) {
				/* Get the targetRamClass */
				getNameAndLengthFromClassNameList(verifyData, J9CLASS_INDEX_FROM_CLASS_ENTRY(targetClass), &targetClassName, &targetClassLength);
				targetRamClass = j9rtv_verifierGetRAMClass(verifyData, verifyData->classLoader, targetClassName, targetClassLength, reasonCode);
				...
								} else {
					if (!isSameOrSuperClassOf(currentRamClass, targetRamClass)) {
						/* fail */
						return FALSE; <--------- captured here
					}
...
```
It means that  the verification error is catpured by our code with `-Xfuture` or `-Xverify:doProtectedAccessCheck` specified but not by default (confirmed with the latest JDK11 nightly build as the code is independent of the java version)
```
./jdk11_openj9_nightly/bin/java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.12+1-202105061821 (build 11.0.12+1-202105061821)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.12+1-202105061821 (build master-0991541a7, JRE 11 Linux amd64-64-Bit Compressed References 20210506_982 (JIT enabled, AOT enabled)
OpenJ9   - 0991541a7
OMR      - d96f2b34f
JCL      - 376b14b921 based on jdk-11.0.12+1)

../jdk11_openj9_nightly/bin/java   -Xfuture  VE1
Error: Unable to initialize main class VE1
Caused by: java.lang.VerifyError: JVMVRFY025 bad access to protected data; class=VE1, method=m1()V, pc=9
Exception Details:
  Location:
    VE1.m1()V @9: JBinvokevirtual
  Reason:
    Access to the protected member is not permitted.

../jdk11_openj9_nightly/bin/java   -Xverify:doProtectedAccessCheck  VE1
Error: Unable to initialize main class VE1
Caused by: java.lang.VerifyError: JVMVRFY025 bad access to protected data; class=VE1, method=m1()V, pc=9
Exception Details:
  Location:
    VE1.m1()V @9: JBinvokevirtual
  Reason:
    Access to the protected member is not permitted.
```

**Comment by ChengJin01** [comment]
Hi @JavaTailor,  please specify `-Xfuture` or `-Xverify:doProtectedAccessCheck` to do the protected check on the test class given the check is not enabled by default in OpenJ9 and there is no code change to be expected at this point.

**Comment by JavaTailor** [comment]
@ChengJin01 
Thanks for your quick reply.
We have verified it, and it works. This seems to be the same issue as  #12804 . We did the same on the test case in #12804 , and indeed the corresponding exception was thrown. But why is this check not set as the default?

In addition, in #12804 , if we replace the called clone function with other functions such as hashcode or any other undefined function. Still no exception will be thrown. Is this something missing in the verification process? Could you please check it  out?

```
Replace:
invokevirtual	Method java/lang/Object.clone:”()Ljava/lang/Object;”;
With:
invokevirtual	Method java/lang/Object.hashCode:”()I”;
Or
invokevirtual	Method java/lang/Object.hashCodexxxx:”()I”;
```
[demo2.zip](https://github.com/eclipse-openj9/openj9/files/6595897/demo2.zip)

**Comment by ChengJin01** [comment]
Hi @JavaTailor,

> But why is this check not set as the default?

The options are disabled by default due to performance related concerns at runtime based on the existing implementation.

> if we replace the called clone function with other functions such as hashcode or any other undefined function. Still no exception will be thrown. Is this something missing in the verification process? 

Please note the check only applies to the access check on the protected method such as `protected Object.clone()` while both `Object.hashCode()` and `Object.hashCodexxxx` (doesn't exist in Object but treated as public) are public methods, which should be skipped in the check according to the Java language/JVM Spec. So hotspot and OpenJ9 end up with the same results at this point:

OpenJDK/Hotspot
```
jdk11_hotspot_nightly/bin/java  -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.12+1-202105061820 (build 11.0.12+1-202105061820)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.12+1-202105061820 (build 11.0.12+1-202105061820, mixed mode)

jdk11_hotspot_nightly/bin/java   -cp . src1.Outer
Outer

jdk11_hotspot_nightly/bin/java   -cp . src2.Outer
Outer
```
OpenJ9
```
jdk11_openj9_nightly/bin/java   -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.12+1-202105061821 (build 11.0.12+1-202105061821)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.12+1-202105061821 (build master-0991541a7, JRE 11 Linux amd64-64-Bit Compressed References 20210506_982 (JIT enabled, AOT enabled)
OpenJ9   - 0991541a7
OMR      - d96f2b34f
JCL      - 376b14b921 based on jdk-11.0.12+1)


jdk11_openj9_nightly/bin/java   -Xverify:doProtectedAccessCheck  -cp . src1.Outer
Outer

jdk11_openj9_nightly/bin/java   -Xverify:doProtectedAccessCheck  -cp . src2.Outer
Outer

```
