### ISSUE TITLE
NoSuchMethodException: java.lang.invoke.MethodHandles.foldArgumentsWithCombiner(java.lang.invoke.MethodHandle, int, java.lang.invoke.MethodHandle, [I)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12980]
Failure link
------------

From an internal build `Test_openjdk11_j9_extended.functional_x86-64_linux_testList_0/54/`:
```
java version "11.0.12-beta" 2021-07-20
Java(TM) SE Runtime Environment 11.0.12.0-IBM (build 11.0.12-beta+5-202106160106)
Eclipse OpenJ9 VM 11.0.12.0-IBM (build master-5216b16f1, JRE 11 Linux amd64-64-Bit Compressed References 20210616_104 (JIT enabled, AOT enabled)
OpenJ9   - 5216b16f1
OMR      - 04c2abf32
JCL      - 877d68cf02 based on jdk-11.0.12+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jsr292_MethodHandleAPI_Test_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F104%2FOpenJDK11U-jre_x64_linux_openj9_IBM_2021-06-16-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F104%2FOpenJDK11U-testimage_x64_linux_openj9_IBM_2021-06-16-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F104%2FOpenJDK11U-debugimage_x64_linux_openj9_IBM_2021-06-16-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F104%2FOpenJDK11U-jdk_x64_linux_openj9_IBM_2021-06-16-01-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=79&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-06-16T02:41:18.887Z] FAILED: test_foldArguments_ArgIndices_CombinerHandle_IntReturnType_IntParam_FoldAtEnd
[2021-06-16T02:41:18.887Z] java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles.foldArgumentsWithCombiner(java.lang.invoke.MethodHandle, int, java.lang.invoke.MethodHandle, [I)
[2021-06-16T02:41:18.887Z] 	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:640)
[2021-06-16T02:41:18.887Z] 	at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1403)
[2021-06-16T02:41:18.887Z] 	at java.base/java.lang.Class.getMethodHelper(Class.java:1489)
[2021-06-16T02:41:18.887Z] 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:1112)
[2021-06-16T02:41:18.887Z] 	at com.ibm.j9.jsr292.api.MethodHandleAPI_foldArguments.test_foldArguments_ArgIndices_CombinerHandle_IntReturnType_IntParam_FoldAtEnd(MethodHandleAPI_foldArguments.java:331)
[2021-06-16T02:41:18.887Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-16T02:41:18.887Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-06-16T02:41:18.887Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-16T02:41:18.887Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-06-16T02:41:18.887Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2021-06-16T02:41:18.887Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2021-06-16T02:41:18.887Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2021-06-16T02:41:18.887Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2021-06-16T02:41:18.887Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-06-16T02:41:18.887Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2021-06-16T02:41:18.887Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2021-06-16T02:41:18.887Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2021-06-16T02:41:18.887Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2021-06-16T02:41:18.887Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2021-06-16T02:41:18.887Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-06-16T02:41:18.887Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2021-06-16T02:41:18.887Z] 	at org.testng.TestNG.main(TestNG.java:1323)
```

This is a regression. It appears caused by https://github.com/eclipse-openj9/openj9/pull/12941
The method in question is not in pre-Java16 levels.

fyi @ChengJin01 @tajila

**Comment by pshipton** [comment]
Failing in the open build as well. This needs to be fixed today or backed out.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/27/

**Comment by tajila** [comment]
@ChengJin01 Please take a look

**Comment by ChengJin01** [comment]
It turns out `foldArgumentsWithCombiner` is only enabled when java version >= 12 in OpenJ9 at https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
```
/*[IF JAVA_SPEC_VERSION >= 12]*/
...
static MethodHandle foldArgumentsWithCombiner(MethodHandle handle, int foldPosition, MethodHandle preprocessor, int... argumentIndices) throws NullPointerException, IllegalArgumentException {
		return foldArguments(handle, foldPosition, preprocessor, argumentIndices);
	}
/*[ENDIF] JAVA_SPEC_VERSION >= 12 */
```
In which we need to check the java version in this test to choose the required internal method for `foldArguments`.

I already created a fix in the test at https://github.com/ChengJin01/openj9/commit/60f8f7b9fb70c010aa6480748a23abe9f79da2aa which is verified in nightly builds on Java 11, 12 and 16.
