### ISSUE TITLE
jtreg java/lang/ProcessBuilder/DestroyTest.java Process terminated prematurely

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12991]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/27
java/lang/ProcessBuilder/DestroyTest.java
jdk_lang_0
JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops

I don't see any diagnostics for this test.
```
23:11:27  STDERR:
23:11:27  java.lang.RuntimeException: Process terminated prematurely.
23:11:27  	at UnixTest.runTest(DestroyTest.java:104)
23:11:27  	at DestroyTest.main(DestroyTest.java:169)
23:11:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:11:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:11:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:11:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:11:27  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
23:11:27  	at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/556/
