### ISSUE TITLE
JDK16 zLinux : java/nio/channels/AsynchronousFileChannel/Lock.java - IOException: Resource deadlock avoided

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13018]
Failure link
------------

From an internal build `Test_openjdk16_j9_extended.openjdk_s390x_linux/15/` (`ub18s390xrt-1-2`):
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Temurin-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM Temurin-16.0.1+9 (build master-0be9a6f3f, JRE 16 Linux s390x-64-Bit Compressed References 20210619_47 (JIT enabled, AOT enabled)
OpenJ9   - 0be9a6f3f
OMR      - b7eb96336
JCL      - 831f892085 based on jdk-16.0.1+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_nio_1&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=s390x_linux&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-s390x-openj9%2F47%2FOpenJDK16U-jre_s390x_linux_openj9_2021-06-19-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-s390x-openj9%2F47%2FOpenJDK16U-debugimage_s390x_linux_openj9_2021-06-19-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-s390x-openj9%2F47%2FOpenJDK16U-jdk_s390x_linux_openj9_2021-06-19-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-linux-s390x-openj9%2F47%2FOpenJDK16U-testimage_s390x_linux_openj9_2021-06-19-13-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=16&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk16&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-06-19T16:56:34.539Z] Running test jdk_nio_1 ...
[2021-06-19T16:56:34.539Z] ===============================================
[2021-06-19T16:56:34.539Z] jdk_nio_1 Start Time: Sat Jun 19 09:56:33 2021 Epoch Time (ms): 1624121793642
[2021-06-19T16:56:34.539Z] "/home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_s390x_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_s390x_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-06-19T16:56:34.539Z] JVMSHRC005I No shared class caches available
[2021-06-19T16:56:34.539Z] JVMSHRC005I No shared class caches available
[2021-06-19T16:56:34.539Z] cache cleanup done
[2021-06-19T16:56:34.539Z] variation: Mode650
[2021-06-19T16:56:34.539Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-06-19T16:57:27.735Z] --------------------------------------------------
[2021-06-19T16:57:27.735Z] TEST: java/nio/channels/AsynchronousFileChannel/Lock.java

[2021-06-19T16:57:27.884Z] STDERR:
[2021-06-19T16:57:27.884Z] java.util.concurrent.ExecutionException: java.io.IOException: Resource deadlock avoided
[2021-06-19T16:57:27.884Z] 	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:200)
[2021-06-19T16:57:27.884Z] 	at Lock.testAsyncClose(Lock.java:125)
[2021-06-19T16:57:27.884Z] 	at Lock.main(Lock.java:63)
[2021-06-19T16:57:27.884Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-19T16:57:27.884Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-06-19T16:57:27.884Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-19T16:57:27.884Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2021-06-19T16:57:27.884Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-06-19T16:57:27.884Z] 	at java.base/java.lang.Thread.run(Thread.java:883)
[2021-06-19T16:57:27.884Z] Caused by: java.io.IOException: Resource deadlock avoided
[2021-06-19T16:57:27.884Z] 	at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
[2021-06-19T16:57:27.884Z] 	at java.base/sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:96)
[2021-06-19T16:57:27.884Z] 	at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$1.run(SimpleAsynchronousFileChannelImpl.java:206)
[2021-06-19T16:57:27.884Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[2021-06-19T16:57:27.884Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[2021-06-19T16:57:27.884Z] 	at java.base/java.lang.Thread.run(Thread.java:883)
[2021-06-19T16:57:27.884Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
[2021-06-19T16:57:27.884Z] 
[2021-06-19T16:57:27.884Z] JavaTest Message: Test threw exception: java.util.concurrent.ExecutionException
[2021-06-19T16:57:27.884Z] JavaTest Message: shutting down test
[2021-06-19T16:57:27.884Z] 
[2021-06-19T16:57:27.884Z] 
[2021-06-19T16:57:27.884Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.util.concurrent.ExecutionException: java.io.IOException: Resource deadlock avoided
[2021-06-19T16:57:27.884Z] --------------------------------------------------
[2021-06-19T17:12:14.507Z] Test results: passed: 434; failed: 1
[2021-06-19T17:12:41.592Z] Report written to /home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_s390x_linux/jvmtest/openjdk/report/html/report.html
[2021-06-19T17:12:41.592Z] Results written to /home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16241105881284/jdk_nio_1/work
[2021-06-19T17:12:41.592Z] Error: Some tests failed or other problems occurred.
[2021-06-19T17:12:41.592Z] 
[2021-06-19T17:12:41.592Z] jdk_nio_1_FAILED
```

10x grinder at 3 machines (`Grinder/16419/`), 3x grinder at same machine (`Grinder/16420/`).

**Comment by pshipton** [comment]
Running all extended.openjdk is overkill. this suite takes a long time, running jdk_nio_1 is more appropriate.

**Comment by pshipton** [comment]
This problem wasn't repeated. java/nio/channels/DatagramChannel/AdaptorMulticasting.java.AdaptorMulticasting and  java/nio/channels/DatagramChannel/Loopback.java.Loopback failed on rhel7s390x-4-3
, but not on ub18s390xrt-1-3 or ub18s390xrt-1-9.

**Comment by JasonFengJ9** [comment]
[JDK17 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_s390x_linux_testList_1/20/)(`rhel9s390x-svl-rt2-1`)
```
[2024-03-30T15:41:52.482Z] variation: Mode150
[2024-03-30T15:41:52.482Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-30T15:43:14.113Z] TEST: java/nio/channels/AsynchronousFileChannel/Lock.java

[2024-03-30T15:43:14.114Z] STDERR:
[2024-03-30T15:43:14.114Z] java.util.concurrent.ExecutionException: java.io.IOException: Resource deadlock avoided
[2024-03-30T15:43:14.114Z] 	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:200)
[2024-03-30T15:43:14.114Z] 	at Lock.testAsyncClose(Lock.java:125)
[2024-03-30T15:43:14.114Z] 	at Lock.main(Lock.java:63)
[2024-03-30T15:43:14.114Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-03-30T15:43:14.114Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-03-30T15:43:14.114Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-03-30T15:43:14.114Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
[2024-03-30T15:43:14.114Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-03-30T15:43:14.114Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2024-03-30T15:43:14.114Z] Caused by: java.io.IOException: Resource deadlock avoided
[2024-03-30T15:43:14.114Z] 	at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
[2024-03-30T15:43:14.114Z] 	at java.base/sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:96)
[2024-03-30T15:43:14.114Z] 	at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$1.run(SimpleAsynchronousFileChannelImpl.java:206)
[2024-03-30T15:43:14.114Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-03-30T15:43:14.114Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-03-30T15:43:14.114Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2024-03-30T15:43:14.114Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
[2024-03-30T15:43:14.114Z] 
[2024-03-30T15:43:14.114Z] JavaTest Message: Test threw exception: java.util.concurrent.ExecutionException
[2024-03-30T15:43:14.114Z] JavaTest Message: shutting down test
[2024-03-30T15:43:14.114Z] 
[2024-03-30T15:43:14.114Z] 
[2024-03-30T15:43:14.114Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.util.concurrent.ExecutionException: java.io.IOException: Resource deadlock avoided
[2024-03-30T15:43:14.114Z] --------------------------------------------------
[2024-03-30T15:54:16.963Z] Test results: passed: 439; failed: 1
[2024-03-30T15:54:48.673Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_s390x_linux_testList_1/aqa-tests/TKG/output_17118132969089/jdk_nio_0/report/html/report.html
[2024-03-30T15:54:48.673Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_s390x_linux_testList_1/aqa-tests/TKG/output_17118132969089/jdk_nio_0/work
[2024-03-30T15:54:48.673Z] Error: Some tests failed or other problems occurred.
[2024-03-30T15:54:48.673Z] -----------------------------------
[2024-03-30T15:54:48.673Z] jdk_nio_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39410/)

**Comment by pshipton** [comment]
Grinder passed on rhel8s390x-svl-rt1-1, sles15s390x-svl-rt6-1, rhel7s390x-svl-rt10-1, sles15s390x-svl-rt2-1
Failed 10/10 on ubu22s390x-rt-2 but in java/nio/channels/FileChannel/Transfer2GPlus.java because "No space left on device".
In other words, the failure in java/nio/channels/AsynchronousFileChannel/Lock.java wasn't repeated in the 50x grinder on jdk_nio_0.

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_extended.openjdk_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_extended.openjdk_aarch64_mac/60/)
```
[2025-05-27T02:49:31.597Z] variation: Mode650
[2025-05-27T02:49:31.597Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-05-27T02:49:51.238Z] TEST: java/nio/channels/AsynchronousFileChannel/Lock.java

[2025-05-27T02:49:51.240Z] STDERR:
[2025-05-27T02:49:51.240Z] java.util.concurrent.ExecutionException: java.io.IOException: Resource deadlock avoided
[2025-05-27T02:49:51.240Z] 	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:200)
[2025-05-27T02:49:51.240Z] 	at Lock.testAsyncClose(Lock.java:125)
[2025-05-27T02:49:51.240Z] 	at Lock.main(Lock.java:63)
[2025-05-27T02:49:51.240Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-05-27T02:49:51.240Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-05-27T02:49:51.240Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2025-05-27T02:49:51.240Z] 	at java.base/java.lang.Thread.run(Thread.java:1458)
[2025-05-27T02:49:51.240Z] Caused by: java.io.IOException: Resource deadlock avoided
[2025-05-27T02:49:51.240Z] 	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
[2025-05-27T02:49:51.240Z] 	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:107)
[2025-05-27T02:49:51.240Z] 	at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$1.run(SimpleAsynchronousFileChannelImpl.java:224)
[2025-05-27T02:49:51.240Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
[2025-05-27T02:49:51.240Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
[2025-05-27T02:49:51.240Z] 	... 1 more
[2025-05-27T02:49:51.240Z] 
[2025-05-27T02:49:51.241Z] JavaTest Message: Test threw exception: java.util.concurrent.ExecutionException
[2025-05-27T02:49:51.241Z] JavaTest Message: shutting down test
[2025-05-27T02:49:51.241Z] 
[2025-05-27T02:49:51.242Z] 
[2025-05-27T02:49:51.242Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.util.concurrent.ExecutionException: java.io.IOException: Resource deadlock avoided
[2025-05-27T02:49:51.242Z] --------------------------------------------------
[2025-05-27T02:53:34.766Z] Test results: passed: 411; failed: 1

[2025-05-27T02:53:34.767Z] jdk_nio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_extended.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_extended.openjdk_aarch64_linux_testList_2/12/)
```
[2025-09-09T09:02:37.189Z] Running test jdk_nio_0 ...
[2025-09-09T09:02:37.189Z] ===============================================
[2025-09-09T09:02:37.189Z] jdk_nio_0 Start Time: Tue Sep  9 09:02:36 2025 Epoch Time (ms): 1757408556242
[2025-09-09T09:02:37.189Z] variation: Mode150
[2025-09-09T09:02:37.189Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-09-09T09:03:36.475Z] TEST: java/nio/channels/AsynchronousFileChannel/Lock.java

[2025-09-09T09:03:36.477Z] STDERR:
[2025-09-09T09:03:36.477Z] java.util.concurrent.ExecutionException: java.io.IOException: Resource deadlock avoided
[2025-09-09T09:03:36.477Z] 	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:200)
[2025-09-09T09:03:36.477Z] 	at Lock.testAsyncClose(Lock.java:125)
[2025-09-09T09:03:36.477Z] 	at Lock.main(Lock.java:63)
[2025-09-09T09:03:36.477Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-09-09T09:03:36.477Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-09-09T09:03:36.477Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:335)
[2025-09-09T09:03:36.477Z] 	at java.base/java.lang.Thread.run(Thread.java:1485)
[2025-09-09T09:03:36.477Z] Caused by: java.io.IOException: Resource deadlock avoided
[2025-09-09T09:03:36.477Z] 	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
[2025-09-09T09:03:36.477Z] 	at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:107)
[2025-09-09T09:03:36.477Z] 	at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$1.run(SimpleAsynchronousFileChannelImpl.java:224)
[2025-09-09T09:03:36.477Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[2025-09-09T09:03:36.477Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[2025-09-09T09:03:36.477Z] 	at java.base/java.lang.Thread.run(Thread.java:1485)
[2025-09-09T09:03:36.477Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:148)
```
