### ISSUE TITLE
JDK17 java/io/Writer/NullWriter.java - Expected exception of type class java.io.IOException but got java.lang.NullPointerException: Cannot invoke "java.io.Writer.write(java.lang.String, int, int)" because "NullWriter.closedWriter" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13021]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.openjdk_x86-64_linux/12/`:
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+18 (build 17+18)
Eclipse OpenJ9 VM Temurin-17+18 (build master-0be9a6f3f, JRE 17 Linux amd64-64-Bit Compressed References 20210619_4 (JIT enabled, AOT enabled)
OpenJ9   - 0be9a6f3f
OMR      - b7eb96336
JCL      - b3c19a5960 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_io_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-jdk_x64_linux_openj9_2021-06-19-14-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-debugimage_x64_linux_openj9_2021-06-19-14-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-testimage_x64_linux_openj9_2021-06-19-14-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-jre_x64_linux_openj9_2021-06-19-14-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-06-19T14:57:09.558Z] Running test jdk_io_0 ...
[2021-06-19T14:57:09.558Z] ===============================================
[2021-06-19T14:57:09.558Z] jdk_io_0 Start Time: Sat Jun 19 07:57:09 2021 Epoch Time (ms): 1624114629157
[2021-06-19T14:57:09.558Z] "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-06-19T14:57:09.558Z] JVMSHRC005I No shared class caches available
[2021-06-19T14:57:09.558Z] JVMSHRC005I No shared class caches available
[2021-06-19T14:57:09.558Z] cache cleanup done
[2021-06-19T14:57:09.558Z] variation: Mode150
[2021-06-19T14:57:09.558Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-06-19T14:59:31.074Z] test NullWriter.testWriteStringIIClosed(): failure
[2021-06-19T14:59:31.074Z] org.testng.TestException: 
[2021-06-19T14:59:31.074Z] Expected exception of type class java.io.IOException but got java.lang.NullPointerException: Cannot invoke "java.io.Writer.write(java.lang.String, int, int)" because "NullWriter.closedWriter" is null
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:737)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-06-19T14:59:31.074Z] 	at org.testng.TestRunner$$Lambda$135/0x00000000740e0858.accept(Unknown Source)
[2021-06-19T14:59:31.074Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-06-19T14:59:31.074Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-06-19T14:59:31.074Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-06-19T14:59:31.074Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-06-19T14:59:31.074Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-06-19T14:59:31.074Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-06-19T14:59:31.074Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-06-19T14:59:31.074Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-06-19T14:59:31.074Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-06-19T14:59:31.074Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-06-19T14:59:31.074Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-06-19T14:59:31.074Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-06-19T14:59:31.074Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-06-19T14:59:31.074Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-06-19T14:59:31.074Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-19T14:59:31.074Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-06-19T14:59:31.074Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-19T14:59:31.074Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-06-19T14:59:31.074Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-06-19T14:59:31.074Z] 	at java.base/java.lang.Thread.run(Thread.java:883)
[2021-06-19T14:59:31.074Z] Caused by: java.lang.NullPointerException: Cannot invoke "java.io.Writer.write(java.lang.String, int, int)" because "NullWriter.closedWriter" is null
[2021-06-19T14:59:31.074Z] 	at NullWriter.testWriteStringIIClosed(NullWriter.java:160)
[2021-06-19T14:59:31.074Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-19T14:59:31.074Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-06-19T14:59:31.074Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-19T14:59:31.074Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-06-19T14:59:31.074Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-06-19T14:59:31.074Z] 	... 27 more
[2021-06-19T14:59:31.074Z] 
[2021-06-19T14:59:31.074Z] ===============================================
[2021-06-19T14:59:31.074Z] java/io/Writer/NullWriter.java
[2021-06-19T14:59:31.074Z] Total tests run: 21, Passes: 0, Failures: 21, Skips: 0
[2021-06-19T14:59:31.075Z] ===============================================
[2021-06-19T14:59:31.075Z] 
[2021-06-19T14:59:31.075Z] STDERR:
[2021-06-19T14:59:31.075Z] java.lang.Exception: failures: 21
[2021-06-19T14:59:31.075Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2021-06-19T14:59:31.075Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-19T14:59:31.075Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-06-19T14:59:31.075Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-19T14:59:31.075Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-06-19T14:59:31.075Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-06-19T14:59:31.075Z] 	at java.base/java.lang.Thread.run(Thread.java:883)
[2021-06-19T14:59:31.075Z] 
[2021-06-19T14:59:31.075Z] JavaTest Message: Test threw exception: java.lang.Exception
[2021-06-19T14:59:31.075Z] JavaTest Message: shutting down test
[2021-06-19T14:59:31.075Z] 
[2021-06-19T14:59:31.075Z] 
[2021-06-19T14:59:31.075Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 21
[2021-06-19T14:59:31.075Z] --------------------------------------------------
[2021-06-19T14:59:33.054Z] Test results: passed: 374; failed: 4
[2021-06-19T14:59:46.434Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2021-06-19T14:59:46.434Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_1624114467105/jdk_io_0/work
[2021-06-19T14:59:46.434Z] Error: Some tests failed or other problems occurred.
[2021-06-19T14:59:46.434Z] 
[2021-06-19T14:59:46.434Z] jdk_io_0_FAILED
```

**Comment by llxia** [comment]
internal TRSS/http://trss1.fyre.ibm.com/allTestsInfo?buildId=60cf2285541aa8b9171bac0f&limit=5&hasChildren=false

![image](https://user-images.githubusercontent.com/19273206/123003022-98eee600-d380-11eb-8703-009639350b99.png)

This is a new failure.

**Git Diff of first seen failure and last success**
https://github.com/eclipse-openj9/openj9/compare/6bbaac6e5...0be9a6f3f
https://github.com/eclipse/omr/compare/bb369d1aa...b7eb96336
https://github.com/ibmruntimes/openj9-openjdk-jdk17/compare/95b5dccc67...b3c19a5960

**Comment by JasonFengJ9** [comment]
Similar reason as https://github.com/eclipse-openj9/openj9/issues/13020#issuecomment-866360938, last pass build was `Build # 60 6/5/2021, 10:30:27 AM`.

**Comment by tajila** [comment]
Confirmed that these failure are caused by:
https://github.com/eclipse-openj9/openj9/pull/12558
https://github.com/eclipse-openj9/openj9/pull/12880

**Comment by tajila** [comment]
Its unclear whether these will be fixed by enabling the ojdk_mh

**Comment by JasonFengJ9** [comment]
The failure is reproduced w/ latest JDK17 (ojdk_mh enabled) build at `Test_grinder/job/Grinder/17557`
```
16:33:48  openjdk version "17-internal" 2021-09-14
16:33:48  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
16:33:48  Eclipse OpenJ9 VM (build master-df51c203a8b, JRE 17 Linux amd64-64-Bit Compressed References 20210816_42 (JIT enabled, AOT enabled)
16:33:48  OpenJ9   - df51c203a8b
16:33:48  OMR      - ac3ab4821a5
16:33:48  JCL      - b40e984c3a1 based on jdk-17+35)

16:36:14  --------------------------------------------------
16:36:14  TEST: java/io/InputStream/NullInputStream.java

16:35:48  STDOUT:
16:35:48  test NullInputStream.testAvailable(): failure
16:35:48  java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "NullInputStream.openStream" is null
16:35:48  	at NullInputStream.testAvailable(NullInputStream.java:75)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:35:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:35:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:35:48  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
16:35:48  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
16:35:48  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
16:35:48  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
16:35:48  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
16:35:48  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
16:35:48  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
16:35:48  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
16:35:48  	at org.testng.TestRunner$$Lambda$128/0x00000000f40cb540.accept(Unknown Source)
16:35:48  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
16:35:48  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
16:35:48  	at org.testng.TestRunner.run(TestRunner.java:585)
16:35:48  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
16:35:48  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
16:35:48  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
16:35:48  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
16:35:48  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
16:35:48  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
16:35:48  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
16:35:48  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
16:35:48  	at org.testng.TestNG.runSuites(TestNG.java:1069)
16:35:48  	at org.testng.TestNG.run(TestNG.java:1037)
16:35:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:35:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:35:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:35:48  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
16:35:48  	at java.base/java.lang.Thread.run(Thread.java:883)

6:35:48  ===============================================
16:35:48  java/io/InputStream/NullInputStream.java
16:35:48  Total tests run: 20, Passes: 0, Failures: 20, Skips: 0
16:35:48  ===============================================
16:35:48  
16:35:48  STDERR:
16:35:48  java.lang.Exception: failures: 20
16:35:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:35:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:35:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:35:48  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
16:35:48  	at java.base/java.lang.Thread.run(Thread.java:883)
16:35:48  
16:35:48  JavaTest Message: Test threw exception: java.lang.Exception
16:35:48  JavaTest Message: shutting down test
16:35:48  
16:35:48  
16:35:48  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 20
16:35:48  --------------------------------------------------
16:35:48  Test results: failed: 1
```

**Comment by fengxue-IS** [comment]
local test passed with latest Java 17 build
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.root.openj9-openjdk-jdk17)
Eclipse OpenJ9 VM (build master-cd8db74f1, JRE 17 Linux amd64-64-Bit Compressed References 20210818_000000 (JIT enabled, AOT enabled)
OpenJ9   - cd8db74f1
OMR      - ac3ab4821
JCL      - b40e984c3a1 based on jdk-17+35)
Test selection 'java/io/Writer/NullWriter.java', will run:
* jtreg:test/jdk/java/io/Writer/NullWriter.java

Running test 'jtreg:test/jdk/java/io/Writer/NullWriter.java'
Passed: java/io/Writer/NullWriter.java
Test results: passed: 1
Report written to /root/292/openj9-openjdk-jdk17/build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_io_Writer_NullWriter_java/html/report.html
Results written to /root/292/openj9-openjdk-jdk17/build/linux-x86_64-server-release/test-support/jtreg_test_jdk_java_io_Writer_NullWriter_java
Finished running test 'jtreg:test/jdk/java/io/Writer/NullWriter.java'
Test report is stored in build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_io_Writer_NullWriter_java

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/io/Writer/NullWriter.java         1     1     0     0   
==============================
TEST SUCCESS
```

**Comment by JasonFengJ9** [comment]
Passed w/ a recent JDK17 build at `Test_grinder/job/Grinder/17598`
```
08:41:25  openjdk version "17-internal" 2021-09-14
08:41:25  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
08:41:25  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 17 Linux amd64-64-Bit Compressed References 20210819_45 (JIT enabled, AOT enabled)
08:41:25  OpenJ9   - cd8db74f1d4
08:41:25  OMR      - ac3ab4821a5
08:41:25  JCL      - b40e984c3a1 based on jdk-17+35)
```

closing..

**Comment by tajila** [comment]
@JasonFengJ9 Does this fail with ojdk_mh ?

**Comment by JasonFengJ9** [comment]
> Does this fail with ojdk_mh ?

Yes, the JDK17 in question https://github.com/eclipse-openj9/openj9/issues/13021#issuecomment-902686676 was built from `openj9-staging` branch which has `ojdk_mh` enabled.
```
12:51:45  openjdk version "17-internal" 2021-09-14
12:51:45  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
12:51:45  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 17 Linux amd64-64-Bit Compressed References 20210819_45 (JIT enabled, AOT enabled)
12:51:45  OpenJ9   - cd8db74f1d4
12:51:45  OMR      - ac3ab4821a5
12:51:45  JCL      - b40e984c3a1 based on jdk-17+35)
```
The test passed in Jack's local machine https://github.com/eclipse-openj9/openj9/issues/13021#issuecomment-901422324 probably was due to `-g -O0` specified in local build as per https://github.com/eclipse-openj9/openj9/issues/13022#issuecomment-902016484.

**Comment by fengxue-IS** [comment]
After investigation, this failure is due to Grinder hardcoding the openj9 branch from extension repo which is different from openj9-staging. test has been patched to work with jtreg 6 (https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/7c832996fff52e5ebb7bfc5499bc9ddd3cd6ae9e)
@JasonFengJ9 can you please re-try this.

**Comment by JasonFengJ9** [comment]
> After investigation, this failure is due to Grinder hardcoding the openj9 branch from extension repo which is different from openj9-staging. test has been patched to work with jtreg 6 (ibmruntimes/openj9-openjdk-jdk17@7c83299)

Similar with https://github.com/eclipse-openj9/openj9/issues/13022#issuecomment-903910981, the grinder hardcoded extension repo branch to `openj9` hence missed the test change in question. Raised an internal issue `backlog/issues/572`.

Just created an `adoptium/aqa-tests` folk branch and clone JDK17 extension repo `openj9-staging` branch, the test passes at `Grinder/17630` w/ a recent JDK17 build.
```
11:51:02  openjdk version "17-internal" 2021-09-14
11:51:02  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
11:51:02  Eclipse OpenJ9 VM (build master-2ba48511f18, JRE 17 Linux amd64-64-Bit Compressed References 20210822_50 (JIT enabled, AOT enabled)
11:51:02  OpenJ9   - 2ba48511f18
11:51:02  OMR      - 6eec759cd2d
11:51:02  JCL      - b40e984c3a1 based on jdk-17+35)
```

closing..

[1] https://github.com/JasonFengJ9/openjdk-tests/tree/jdk17teststaging
