### ISSUE TITLE
JDK17 java/text/Collator/RuleBasedCollatorTest.java - java.text.ParseException: missing char (=,;<&) : null@

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13022]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.openjdk_x86-64_linux/12/`:
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+18 (build 17+18)
Eclipse OpenJ9 VM Temurin-17+18 (build master-0be9a6f3f, JRE 17 Linux amd64-64-Bit Compressed References 20210619_4 (JIT enabled, AOT enabled)
OpenJ9   - 0be9a6f3f
OMR      - b7eb96336
JCL      - b3c19a5960 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_text_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-jdk_x64_linux_openj9_2021-06-19-14-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-debugimage_x64_linux_openj9_2021-06-19-14-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-testimage_x64_linux_openj9_2021-06-19-14-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F4%2FOpenJDK17-jre_x64_linux_openj9_2021-06-19-14-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-06-19T18:59:04.851Z] Running test jdk_text_0 ...
[2021-06-19T18:59:04.851Z] ===============================================
[2021-06-19T18:59:04.851Z] jdk_text_0 Start Time: Sat Jun 19 11:59:04 2021 Epoch Time (ms): 1624129144553
[2021-06-19T18:59:04.851Z] "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-06-19T18:59:04.851Z] JVMSHRC005I No shared class caches available
[2021-06-19T18:59:04.851Z] JVMSHRC005I No shared class caches available
[2021-06-19T18:59:04.851Z] cache cleanup done
[2021-06-19T18:59:04.851Z] variation: Mode150
[2021-06-19T18:59:04.851Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-06-19T18:59:33.761Z] --------------------------------------------------
[2021-06-19T18:59:33.761Z] TEST: java/text/Collator/RuleBasedCollatorTest.java

[2021-06-19T18:59:33.762Z] test RuleBasedCollatorTest.testFrenchSecondarySort("aáa", "áaa", 1): failure
[2021-06-19T18:59:33.762Z] java.text.ParseException: missing char (=,;<&) : null@
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.PatternEntry$Parser.next(PatternEntry.java:254)
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.MergeCollation.addPattern(MergeCollation.java:180)
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.MergeCollation.setPattern(MergeCollation.java:166)
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.MergeCollation.<init>(MergeCollation.java:73)
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.RBTableBuilder.build(RBTableBuilder.java:113)
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.RBCollationTables.<init>(RBCollationTables.java:83)
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.RuleBasedCollator.<init>(RuleBasedCollator.java:301)
[2021-06-19T18:59:33.762Z] 	at java.base/java.text.RuleBasedCollator.<init>(RuleBasedCollator.java:282)
[2021-06-19T18:59:33.762Z] 	at RuleBasedCollatorTest.testFrenchSecondarySort(RuleBasedCollatorTest.java:119)
[2021-06-19T18:59:33.762Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-19T18:59:33.762Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-06-19T18:59:33.762Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-19T18:59:33.762Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-06-19T18:59:33.762Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-06-19T18:59:33.762Z] 	at org.testng.TestRunner$$Lambda$72/0x00000000dc0e69d0.accept(Unknown Source)
[2021-06-19T18:59:33.762Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-06-19T18:59:33.762Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-06-19T18:59:33.762Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-06-19T18:59:33.762Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-06-19T18:59:33.762Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-06-19T18:59:33.762Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-06-19T18:59:33.762Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-06-19T18:59:33.762Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-06-19T18:59:33.762Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-06-19T18:59:33.762Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-06-19T18:59:33.762Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-06-19T18:59:33.762Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-06-19T18:59:33.762Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-06-19T18:59:33.763Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-06-19T18:59:33.763Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-06-19T18:59:33.763Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-06-19T18:59:33.763Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-06-19T18:59:33.763Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-19T18:59:33.763Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-06-19T18:59:33.763Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-06-19T18:59:33.763Z] 	at java.base/java.lang.Thread.run(Thread.java:883)

[2021-06-19T18:59:33.782Z] ===============================================
[2021-06-19T18:59:33.782Z] java/text/Collator/RuleBasedCollatorTest.java
[2021-06-19T18:59:33.782Z] Total tests run: 24, Passes: 10, Failures: 14, Skips: 0
[2021-06-19T18:59:33.782Z] ===============================================

[2021-06-19T18:59:33.783Z] --------------------------------------------------
[2021-06-19T19:02:12.864Z] Test results: passed: 182; failed: 1
[2021-06-19T19:02:22.376Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2021-06-19T19:02:22.376Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_1624114467105/jdk_text_0/work
[2021-06-19T19:02:22.376Z] Error: Some tests failed or other problems occurred.
[2021-06-19T19:02:22.376Z] 
[2021-06-19T19:02:22.376Z] jdk_text_0_FAILED
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by llxia** [comment]
http://trss1.fyre.ibm.com/allTestsInfo?buildId=60cf2285541aa8b9171bac0f&limit=5&hasChildren=false

**Comment by tajila** [comment]
Confirmed that these failure are caused by:
https://github.com/eclipse-openj9/openj9/pull/12558
https://github.com/eclipse-openj9/openj9/pull/12880

**Comment by fengxue-IS** [comment]
local testing passed with latest Java 17 build
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.root.openj9-openjdk-jdk17)
Eclipse OpenJ9 VM (build master-cd8db74f1, JRE 17 Linux amd64-64-Bit Compressed References 20210818_000000 (JIT enabled, AOT enabled)
OpenJ9   - cd8db74f1
OMR      - ac3ab4821
JCL      - b40e984c3a1 based on jdk-17+35)
Test selection 'java/text/Collator/RuleBasedCollatorTest.java', will run:
* jtreg:test/jdk/java/text/Collator/RuleBasedCollatorTest.java

Running test 'jtreg:test/jdk/java/text/Collator/RuleBasedCollatorTest.java'
Passed: java/text/Collator/RuleBasedCollatorTest.java
Test results: passed: 1
Report written to /root/292/openj9-openjdk-jdk17/build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_text_Collator_RuleBasedCollatorTest_java/html/report.html
Results written to /root/292/openj9-openjdk-jdk17/build/linux-x86_64-server-release/test-support/jtreg_test_jdk_java_text_Collator_RuleBasedCollatorTest_java
Finished running test 'jtreg:test/jdk/java/text/Collator/RuleBasedCollatorTest.java'
Test report is stored in build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_text_Collator_RuleBasedCollatorTest_java

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/text/Collator/RuleBasedCollatorTest.java
                                                         1     1     0     0   
==============================
TEST SUCCESS
```
@JasonFengJ9 FYI

**Comment by JasonFengJ9** [comment]
This is reproduced at `Test_grinder/job/Grinder/17591/`
```
19:07:22  openjdk version "17-internal" 2021-09-14
19:07:22  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
19:07:22  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 17 Linux amd64-64-Bit Compressed References 20210818_44 (JIT enabled, AOT enabled)
19:07:22  OpenJ9   - cd8db74f1d4
19:07:22  OMR      - ac3ab4821a5
19:07:22  JCL      - b40e984c3a1 based on jdk-17+35)

19:07:32  --------------------------------------------------
19:07:32  TEST: java/text/Collator/RuleBasedCollatorTest.java

19:07:32  STDOUT:
19:07:32  test RuleBasedCollatorTest.testBasicParsingOrder(): success
19:07:32  test RuleBasedCollatorTest.testEquality(): success
19:07:32  test RuleBasedCollatorTest.testFrenchSecondarySort("aáa", "áaa", 1): failure
19:07:32  java.text.ParseException: missing char (=,;<&) : null@
19:07:32  	at java.base/java.text.PatternEntry$Parser.next(PatternEntry.java:258)
19:07:32  	at java.base/java.text.MergeCollation.addPattern(MergeCollation.java:180)
19:07:32  	at java.base/java.text.MergeCollation.setPattern(MergeCollation.java:166)
19:07:32  	at java.base/java.text.MergeCollation.<init>(MergeCollation.java:73)
19:07:32  	at java.base/java.text.RBTableBuilder.build(RBTableBuilder.java:113)
19:07:32  	at java.base/java.text.RBCollationTables.<init>(RBCollationTables.java:83)
19:07:32  	at java.base/java.text.RuleBasedCollator.<init>(RuleBasedCollator.java:301)
19:07:32  	at java.base/java.text.RuleBasedCollator.<init>(RuleBasedCollator.java:282)
19:07:32  	at RuleBasedCollatorTest.testFrenchSecondarySort(RuleBasedCollatorTest.java:119)
19:07:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:07:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19:07:32  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:07:32  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:07:32  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
19:07:32  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
19:07:32  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
19:07:32  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
19:07:32  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
19:07:32  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
19:07:32  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
19:07:32  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
19:07:32  	at org.testng.TestRunner$$Lambda$72/0x00000000540f6b20.accept(Unknown Source)
19:07:32  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
19:07:32  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
19:07:32  	at org.testng.TestRunner.run(TestRunner.java:585)
19:07:32  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
19:07:32  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
19:07:32  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
19:07:32  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
19:07:32  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
19:07:32  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
19:07:32  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
19:07:32  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
19:07:32  	at org.testng.TestNG.runSuites(TestNG.java:1069)
19:07:32  	at org.testng.TestNG.run(TestNG.java:1037)
19:07:32  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
19:07:32  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
19:07:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:07:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19:07:32  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:07:32  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:07:32  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:07:32  	at java.base/java.lang.Thread.run(Thread.java:883)
19:07:32  test RuleBasedCollatorTest.testFrenchSecondarySort("Ạa", "ẢA", -1): failure
...
19:07:32  ===============================================
19:07:32  java/text/Collator/RuleBasedCollatorTest.java
19:07:32  Total tests run: 24, Passes: 10, Failures: 14, Skips: 0
19:07:32  ===============================================
19:07:32  
19:07:32  STDERR:
19:07:32  java.lang.Exception: failures: 14
19:07:32  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
19:07:32  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
19:07:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:07:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19:07:32  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:07:32  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:07:32  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:07:32  	at java.base/java.lang.Thread.run(Thread.java:883)
19:07:32  
19:07:32  JavaTest Message: Test threw exception: java.lang.Exception: failures: 14
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&CUSTOM_TARGET=java/text/Collator/RuleBasedCollatorTest.java&TARGET=jdk_custom_0)

Note: The VM in question has same SHAs as https://github.com/eclipse-openj9/openj9/issues/13022#issuecomment-901420586

**Comment by fengxue-IS** [comment]
interesting, I think the only difference is that my local build have `-g -O0`. maybe due to optimization skipping default value initialization in this case causing the problem? I will review the code Tobi pointed out (#12558 #12880) to see if there may be such cases

**Comment by tajila** [comment]
@JasonFengJ9 Likewise, does this fail with ojdk_mh

**Comment by JasonFengJ9** [comment]
> Likewise, does this fail with ojdk_mh

Similar with https://github.com/eclipse-openj9/openj9/issues/13021#issuecomment-902989637, yes, the JDK17 in question https://github.com/eclipse-openj9/openj9/issues/13022#issuecomment-901489434 was built from `openj9-staging` branch which has `ojdk_mh` enabled.
```
19:07:22  openjdk version "17-internal" 2021-09-14
19:07:22  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
19:07:22  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 17 Linux amd64-64-Bit Compressed References 20210818_44 (JIT enabled, AOT enabled)
19:07:22  OpenJ9   - cd8db74f1d4
19:07:22  OMR      - ac3ab4821a5
19:07:22  JCL      - b40e984c3a1 based on jdk-17+35)
```
which has same SHAs as Jack's local build https://github.com/eclipse-openj9/openj9/issues/13022#issuecomment-901420586 which specified `-g -O0` though as per https://github.com/eclipse-openj9/openj9/issues/13022#issuecomment-902016484.

**Comment by JasonFengJ9** [comment]
> After investigation, this failure is due to Grinder hardcoding the openj9 branch from extension repo which is different from openj9-staging. test has been patched to work with jtreg 6 (ibmruntimes/openj9-openjdk-jdk17@f4f498a)

Yeah, the grinder hardcoded extension repo branch to `openj9` hence missed the test change in question. Raised an internal issue `backlog/issues/572`.

Just created an `adoptium/aqa-tests` folk branch and clone JDK17 extension repo `openj9-staging` branch, the test passes at `Grinder/17629` w/ a recent JDK17 build.
```
11:51:02  openjdk version "17-internal" 2021-09-14
11:51:02  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
11:51:02  Eclipse OpenJ9 VM (build master-2ba48511f18, JRE 17 Linux amd64-64-Bit Compressed References 20210822_50 (JIT enabled, AOT enabled)
11:51:02  OpenJ9   - 2ba48511f18
11:51:02  OMR      - 6eec759cd2d
11:51:02  JCL      - b40e984c3a1 based on jdk-17+35)
```

closing..

[1] https://github.com/JasonFengJ9/openjdk-tests/tree/jdk17teststaging
