### ISSUE TITLE
OTT: 80 VM_DDRExt_Junit_MultiCore.aix64_testDDRExtJunit : testWhatis(j9vm.test.ddrext.junit.TestDDRExtensionGeneral) - AssertionFailedError 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13038]
Failure link
------------

From an internal build `job_output.php?id=8389651`:
```
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pap6480sr7-20210518_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20210622_7816 (JIT enabled, AOT enabled)
OpenJ9   - 1af61ee
OMR      - e5338e7
IBM      - f051cd3)
JCL - 20210517_01 based on Oracle jdk8u301-b03
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[java] 20210623 01:12:34- Starting testWhatis(j9vm.test.ddrext.junit.TestDDRExtensionGeneral)
     [java] junit.framework.AssertionFailedError
     [java]     at junit.framework.Assert.fail(Assert.java:47)
     [java]     at junit.framework.Assert.assertTrue(Assert.java:20)
     [java]     at junit.framework.Assert.assertTrue(Assert.java:27)
     [java]     at j9vm.test.ddrext.junit.TestDDRExtensionGeneral.testWhatis(TestDDRExtensionGeneral.java:99)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
     [java]     at java.lang.reflect.Method.invoke(Method.java:508)
     [java]     at junit.framework.TestCase.runTest(TestCase.java:154)
     [java]     at junit.framework.TestCase.runBare(TestCase.java:127)
     [java]     at junit.framework.TestResult$1.protect(TestResult.java:106)
     [java]     at junit.framework.TestResult.runProtected(TestResult.java:124)
     [java]     at junit.framework.TestResult.run(TestResult.java:109)
     [java]     at junit.framework.TestCase.run(TestCase.java:118)
     [java]     at junit.framework.TestSuite.runTest(TestSuite.java:208)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:62)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:57)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:43)
     [java]     at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:262)
     [java]     at j9vm.test.ddrext.AutoRun.main(AutoRun.java:97)
     [java] 20210623 01:12:34- Validation started for : '!whatis  0x000000000003C900'
     [java] 20210623 01:12:34- '!whatis  0x000000000003C900' output does not contain success key : !j9class
     [java] 20210623 01:12:34- '!whatis  0x000000000003C900' output :Found 0x000000000003C900 as UDATA(0x000000000003C900): !j9vmthread 0x302500->linkPrevious->currentOSStackFree
     [java] Match found
     [java] Searched 4396 fields to a depth of 2 in 928 ms
```

This appears a regression between ibuild `7342` and `7444`.

**Comment by pshipton** [comment]
The changes between these builds are https://github.com/eclipse-openj9/openj9/compare/1ceaea8eb8...d15b0aade

@tajila @hangshao0 it seems https://github.com/eclipse-openj9/openj9/pull/12879 must have caused this.

**Comment by tajila** [comment]
@hangshao0 Can you please take a look at this

**Comment by hangshao0** [comment]
All the code in #12879 except flags `J9AccClassHasIdentity` and `J9AccClassHasIdentity` are inside 
`if defined(J9VM_OPT_VALHALLA_VALUE_TYPES)`. I will try putting `J9AccClassHasIdentity` and `J9AccClassHasIdentity` inside the ifdef as well.

**Comment by pshipton** [comment]
I'm not 1000% sure it's this change, it just seemed most likely.

**Comment by hangshao0** [comment]
Failed the same way with #12879 backed out:

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=8489303

```
[java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:47)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestDDRExtensionGeneral.testWhatis(TestDDRExtensionGeneral.java:99)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:508)
```

**Comment by pshipton** [comment]
Looking at linux_x4.core.b7816.80_29.dmp from ibuild 7816, it finds !j9method instead of !j9class
```
!j9class 0x000000000003C900 named java/lang/Object
Found 1 class(es) named java/lang/Object
> !whatis 0x000000000003C900
Found 0x000000000003C900 as !j9method 0x3c900: !j9javavm 0x7fe578013c40->shortArrayClass->subclassTraversalReverseLink->arrayClass->subclassTraversalReverseLink->ramMethods
```

whereas for another class it works
```
!j9class 0x0000000000048F00 named java/lang/String
Found 1 class(es) named java/lang/String
> !whatis 0x0000000000048F00
Found 0x0000000000048F00 as !j9class 0x48f00: !j9javavm 0x7fe578013c40->shortArrayClass->subclassTraversalReverseLink->subclassTraversalReverseLink->subclassTraversalReverseLink->subclassTraversalReverseLink->subclassTraversalReverseLink
```

**Comment by pshipton** [comment]
Tried backing out https://github.com/eclipse-openj9/openj9/pull/12914 but it still fails.

**Comment by pshipton** [comment]
I'm not convinced it was working properly in build 7342 or earlier. When I get build 7342, generate a core, and try the same commands I get.
```
!whatis 0x000000000003C900
Unexpected type walked: java.lang.Long
Unexpected type walked: java.lang.Long
Unexpected type walked: java.lang.Long
Unexpected type walked: java.lang.Long
Found 0x000000000003C900 as !j9method 0x3c900: !j9class 0x14cd00->subclassTraversalReverseLink->nextClassInSegment->nextClassInSegment->subclassTraversalLink->ramMethods
Match found
```

**Comment by pshipton** [comment]
@mpirvu any idea why https://github.com/eclipse-openj9/openj9/pull/12914 is causing this test to fail?

**Comment by mpirvu** [comment]
On the surface I cannot find a link between #12914 and this issue. Tomorrow I'll do a more thorough analysis.

**Comment by mpirvu** [comment]
I looked at the code for #12914 and for non-linux, non-jitserver the only effective change is some reordering of fields in RuntimeAssumptions.hpp: one unused field was deleted, one field was extended and two fields were swapped order to allow better packing. I don't see how this can affect DDR. I am going to try to reproduce this and undo the changes bit by bit until the problem goes away.

**Comment by gacholio** [comment]
I suspect this may be caused by a class with no methods falling immediately before the class in question. If the class is simple enough, ramMethods may point to the next class.

If this is the case, we could fix it by not initializing pointers to empty blocks in the class.
