### ISSUE TITLE
java.lang.module.FindException: Module openj9.criu not found

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13061]
Failure link
------------

From an internal build `build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-openj9/192/console`:

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
21:31:16  Error: Module openj9.criu not found
21:31:16  java.lang.module.FindException: Module openj9.criu not found
21:31:16  	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
21:31:16  	at java.base/java.lang.module.Resolver.resolve(Resolver.java:128)
21:31:16  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
21:31:16  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
21:31:16  	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:220)
21:31:16  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:486)
21:31:16  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:396)
21:31:16  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:272)
21:31:16  	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:54)
21:31:16  	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
21:31:16  Images.gmk:104: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-openj9/workspace/build/src/build/linux-ppc64le-normal-server-release/images/jre/bin/java' failed
21:31:16  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-openj9/workspace/build/src/build/linux-ppc64le-normal-server-release/images/jre/bin/java] Error 1
21:31:16  make/Main.gmk:393: recipe for target 'legacy-jre-image' failed
21:31:16  gmake[2]: *** [legacy-jre-image] Error 1
21:31:16  gmake[2]: *** Waiting for unfinished jobs....
21:31:25  
21:31:25  ERROR: Build failed for targets 'product-images legacy-jre-image test-image debug-image' in configuration 'linux-ppc64le-normal-server-release' (exit code 2) 
21:31:25  Stopping sjavac server
21:31:25  
21:31:25  === Output from failing command(s) repeated here ===
21:31:25  * For target support_images_jre:
21:31:25  Error: Module openj9.criu not found
21:31:25  java.lang.module.FindException: Module openj9.criu not found
21:31:25  	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
21:31:25  	at java.base/java.lang.module.Resolver.resolve(Resolver.java:128)
21:31:25  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
21:31:25  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
21:31:25  	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:220)
21:31:25  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:486)
21:31:25  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:396)
21:31:25  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:272)
21:31:25  	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:54)
21:31:25  	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
21:31:25  
21:31:25  * All command lines available in /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-openj9/workspace/build/src/build/linux-ppc64le-normal-server-release/make-support/failure-logs.
21:31:25  === End of repeated output ===
```
OpenJ9 build seems good though.

fyi @tajila @keithc-ca

**Comment by keithc-ca** [comment]
Fixed via pull requests referenced above.
