### ISSUE TITLE
J9(1.8.0_292) and hotspot(8u275b01)  runs normally;J9(11.0.11) threw IllegalAccessException; hotspot(10.0.2 ,11.0.10) threw NoSuchMethodException

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#13082]
### Summary
Given a test case, we found that the execution results of this test case on different JVMs and different versions are quite different, the simplified test case can be found in the attachment. In summary, J9(1.8.0_292) and hotspot(8u275b01) are executed normally, while others threw different exceptions. The output is as follows:

J9(11.0.11):
```
Exception in thread "main" java.lang.Error: unexpected exception
	at AbstractTest.exceptionThrown(AbstractTest.java:10)
	at java.desktop/java.beans.Encoder.getValue(Unknown Source)
	at java.desktop/java.beans.Encoder.get(Unknown Source)
	at java.desktop/java.beans.PersistenceDelegate.writeObject(Unknown Source)
	at java.desktop/java.beans.Encoder.writeObject(Unknown Source)
	at java.desktop/java.beans.XMLEncoder.writeObject(Unknown Source)
	at java.desktop/java.beans.Encoder.writeExpression(Unknown Source)
	at java.desktop/java.beans.XMLEncoder.writeExpression(Unknown Source)
	at java.desktop/java.beans.PersistenceDelegate.writeObject(Unknown Source)
	at java.desktop/java.beans.Encoder.writeObject(Unknown Source)
	at java.desktop/java.beans.XMLEncoder.writeObject(Unknown Source)
	at java.desktop/java.beans.Encoder.writeObject1(Unknown Source)
	at java.desktop/java.beans.Encoder.cloneStatement(Unknown Source)
	at java.desktop/java.beans.Encoder.writeStatement(Unknown Source)
	at java.desktop/java.beans.XMLEncoder.writeStatement(Unknown Source)
	at java.desktop/java.beans.XMLEncoder.writeObject(Unknown Source)
	at AbstractTest.writeObject(AbstractTest.java:45)
	at AbstractTest.testObject(AbstractTest.java:36)
	at AbstractTest.test(AbstractTest.java:30)
	at JTest1.main(JTest1.java:8)
Caused by: java.lang.IllegalAccessException: Class sun/reflect/misc/Trampoline illegally accessing "package private" class java/util/Collections$CheckedRandomAccessList 
	at java.base/java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.reflect.misc.MethodUtil.invoke(Unknown Source)
	at java.desktop/java.beans.Statement.invokeInternal(Unknown Source)
	at java.desktop/java.beans.Statement$2.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.beans.Statement.invoke(Unknown Source)
	at java.desktop/java.beans.Expression.getValue(Unknown Source)
	... 19 more
```

hotspot(10.0.2 ,11.0.10):
```
Exception in thread "main" java.lang.Error: unexpected exception
	at AbstractTest.exceptionThrown(AbstractTest.java:10)
	at java.desktop/java.beans.Encoder.getValue(Encoder.java:108)
	at java.desktop/java.beans.Encoder.get(Encoder.java:252)
	at java.desktop/java.beans.PersistenceDelegate.writeObject(PersistenceDelegate.java:112)
	at java.desktop/java.beans.Encoder.writeObject(Encoder.java:74)
	at java.desktop/java.beans.XMLEncoder.writeObject(XMLEncoder.java:326)
	at java.desktop/java.beans.Encoder.writeExpression(Encoder.java:330)
	at java.desktop/java.beans.XMLEncoder.writeExpression(XMLEncoder.java:454)
	at java.desktop/java.beans.PersistenceDelegate.writeObject(PersistenceDelegate.java:115)
	at java.desktop/java.beans.Encoder.writeObject(Encoder.java:74)
	at java.desktop/java.beans.XMLEncoder.writeObject(XMLEncoder.java:326)
	at java.desktop/java.beans.Encoder.writeObject1(Encoder.java:258)
	at java.desktop/java.beans.Encoder.cloneStatement(Encoder.java:271)
	at java.desktop/java.beans.Encoder.writeStatement(Encoder.java:301)
	at java.desktop/java.beans.XMLEncoder.writeStatement(XMLEncoder.java:399)
	at java.desktop/java.beans.XMLEncoder.writeObject(XMLEncoder.java:329)
	at AbstractTest.writeObject(AbstractTest.java:45)
	at AbstractTest.testObject(AbstractTest.java:36)
	at AbstractTest.test(AbstractTest.java:30)
	at JTest1.main(JTest1.java:8)
Caused by: java.lang.InstantiationException: java.util.Collections$CheckedRandomAccessList
	at java.base/java.lang.Class.newInstance(Class.java:547)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.desktop/java.beans.Statement.invokeInternal(Statement.java:304)
	at java.desktop/java.beans.Statement.access$000(Statement.java:60)
	at java.desktop/java.beans.Statement$2.run(Statement.java:187)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.beans.Statement.invoke(Statement.java:184)
	at java.desktop/java.beans.Expression.getValue(Expression.java:155)
	at java.desktop/java.beans.Encoder.getValue(Encoder.java:105)
	... 18 more
Caused by: java.lang.NoSuchMethodException: java.util.Collections$CheckedRandomAccessList.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3302)
	at java.base/java.lang.Class.newInstance(Class.java:532)
	... 35 more
```

### How to reproduce?
[JTest1.zip](https://github.com/eclipse-openj9/openj9/files/6730362/JTest1.zip)
Follow the commands in readme.

### Affected versions
macOS:
```
macOS Big Sur
Version 11.2.3 (20D91)
Processor 2.3 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3
```

Java -version output under macOS
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210421_909 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)
```

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210421_957 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)
```

**Comment by DanHeidinga** [comment]
fyi @tajila

**Comment by tajila** [comment]
@ChengJin01 Can you please take a look at this

**Comment by ChengJin01** [comment]
1)  Debugging shows the exception in OpenJDK11/OpenJ9 was captured in the native code at https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/lookupmethod.c as follows:
```
Thread 2 "main" hit Breakpoint 1, illegalAccessMessage (currentThread=0x16700, badMemberModifier=-1, senderClass=0x169d00, targetClass=0x18b900, errorType=0) at lookupmethod.c:1218
1218				errorMsg = j9nls_lookup_message(..., J9NLS_VM_ILLEGAL_ACCESS_CLASS <-------
(gdb) bt
#0  illegalAccessMessage (currentThread=0x16700, badMemberModifier=-1, senderClass=0x169d00, targetClass=0x18b900, errorType=0) at lookupmethod.c:1218
#1  0x00007ffff7299c82 in VM_BytecodeInterpreterCompressed::inlInternalsNewInstanceImpl (this=0x7ffff7d45f00, _sp=@0x7ffff7d45e70: 0x10bde0, _pc=@0x7ffff7d45e78: 0x3 <error: Cannot access memory at address 0x3>) at BytecodeInterpreter.hpp:3151
#2  0x00007ffff72ac655 in VM_BytecodeInterpreterCompressed::run (this=0x7ffff7d45f00, vmThread=0x16700) at BytecodeInterpreter.hpp:9746
#3  0x00007ffff7288135 in bytecodeLoopCompressed (currentThread=0x16700) at BytecodeInterpreter.inc:112
#4  0x00007ffff73d3702 in c_cInterpreter () at xcinterp.s:158
#5  0x00007ffff7351ebd in sidecarInvokeReflectMethodImpl (currentThread=0x16700, methodRef=0x10bee0, recevierRef=0x10bed8, argsRef=0x10bed0) at callin.cpp:1189
#6  0x00007ffff73527ae in sidecarInvokeReflectMethod (currentThread=0x16700, methodRef=0x10bee0, recevierRef=0x10bed8, argsRef=0x10bed0) at callin.cpp:1333
#7  0x00007ffff57b414f in JVM_InvokeMethod_Impl (env=0x16700, method=0x10bee0, obj=0x10bed8, args=0x10bed0) at sunvmi.c:354
#8  0x00007ffff7513dc8 in JVM_InvokeMethod (env=0x16700, method=0x10bee0, obj=0x10bed8, args=0x10bed0) at vmi.c:98
#9  0x00007ffff7d4ebec in JVM_InvokeMethod (env=0x16700, method=0x10bee0, obj=0x10bed8, args=0x10bed0) at generated.c:2252
#10 0x00007fffce52cb09 in Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0 (env=0x16700, unused=0x160c30, m=0x10bee0, obj=0x10bed8, args=0x10bed0) at /.../openj9-openjdk-jdk11/src/java.base/share/native/libjava/NativeAccessors.c:33

https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/lookupmethod.c
char *
illegalAccessMessage(J9VMThread *currentThread, IDATA badMemberModifier, J9Class *senderClass, J9Class *targetClass, IDATA errorType)
{
...
		/* illegal non-module access */
		if (badMemberModifier == -1) { /* visibility failed from Class level */
			errorMsg = j9nls_lookup_message(J9NLS_DO_NOT_PRINT_MESSAGE_TAG | J9NLS_DO_NOT_APPEND_NEWLINE,
					J9NLS_VM_ILLEGAL_ACCESS_CLASS, <-------
                                         NULL);

https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/BytecodeInterpreter.hpp
	VMINLINE VM_BytecodeAction
	inlInternalsNewInstanceImpl(REGISTER_ARGS_LIST)
	{
...
			senderClass = J9VM_J9CLASS_FROM_HEAPCLASS(_currentThread, walkState->userData2);
			/* See if the class is visible to the sender */
			if (NULL != senderClass) {
 ----> IDATA checkResult = checkVisibility(_currentThread, senderClass, j9clazz, j9clazz->romClass->modifiers, J9_LOOK_REFLECT_CALL);
				VMStructHasBeenUpdated(REGISTER_ARGS);
				if (checkResult < J9_VISIBILITY_ALLOWED) {
					if (immediateAsyncPending()) {
						rc = GOTO_ASYNC_CHECK;
						goto done;
					} else if (VM_VMHelpers::exceptionPending(_currentThread)) {
						rc = GOTO_THROW_CURRENT_EXCEPTION;
						goto done;
					}
---->	char *nlsStr = illegalAccessMessage(_currentThread, -1, senderClass, j9clazz, checkResult); <------
https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/visible.c
```
in that `checkVisibility()` between `sun/reflect/misc/Trampoline` and ` java/util/Collections$CheckedRandomAccessList` failed at `runtime/vm/visible.c`
```
IDATA
checkVisibility(J9VMThread *currentThread, J9Class* sourceClass, J9Class* destClass, UDATA modifiers, UDATA lookupOptions)
{
...
	Trc_VM_checkVisibility_Entry(currentThread, sourceClass, destClass, modifiers);
	sourceClass = J9_CURRENT_CLASS(sourceClass);
	destClass = J9_CURRENT_CLASS(destClass);
#ifdef DEBUG
	printf("checkModVis: [%*s] [%*s]\n",
				J9UTF8_LENGTH(J9ROMCLASS_CLASSNAME(sourceClass->romClass)), J9UTF8_DATA(J9ROMCLASS_CLASSNAME(sourceClass->romClass)),
				J9UTF8_LENGTH(J9ROMCLASS_CLASSNAME(destClass->romClass)), J9UTF8_DATA(J9ROMCLASS_CLASSNAME(destClass->romClass)));
#endif
...
	if (!J9CLASS_IS_EXEMPT_FROM_VALIDATION(sourceClass)) {
		if ( modifiers & J9AccPublic ) {
...
		} else {
			/* Default (package access) */
			if (sourceClass->packageID != destClass->packageID) {
----> result = J9_VISIBILITY_NON_MODULE_ACCESS_ERROR;
			}
		}
```
Apparently, the check result is correct given ` java/util/Collections$CheckedRandomAccessList` has no modifier and holds `package-private` by default, which is inaccessible to `sun/reflect/misc/Trampoline` from different packages.

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/java/util/Collections.java
```
static class CheckedRandomAccessList<E> extends CheckedList<E>
                                            implements RandomAccess
    {
        private static final long serialVersionUID = 1638200125423088369L;

        CheckedRandomAccessList(List<E> list, Class<E> type) {
            super(list, type);
        }

        public List<E> subList(int fromIndex, int toIndex) {
            return new CheckedRandomAccessList<>(
                    list.subList(fromIndex, toIndex), type);
        }
    }
```

2) The reason why it passed on Java 8 is that `inlInternalsNewInstanceImpl` was never triggered by `sun/reflect/misc/Trampoline` according to the debug info enabled in `checkVisibility()` on OpenJDK8/OpenJ9 and OpenJDK11/OpenJ9.
```
$ ../jdk8_openj9_v1/bin/java -version
openjdk version "1.8.0_302-internal-debug"
OpenJDK Runtime Environment (build 1.8.0_302-internal-debug-jincheng_2021_07_23_00_20-b00)
Eclipse OpenJ9 VM (build...-ea40a01e9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210723_000000 (JIT enabled, AOT enabled)
OpenJ9   - ea40a01e9
OMR      - 88427d642
JCL      - c0b29ca593 based on jdk8u302-b07)

$ ../jdk8_openj9_v1/bin/java -cp  .   JTest1
$ (no debug info)

$ ../jdk11_openj9_v1/bin/java -version
openjdk version "11.0.12-internal" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12-internal+0-adhoc.jincheng.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build ...-ea40a01e9, JRE 11 Linux amd64-64-Bit Compressed References 20210723_000000 (JIT enabled, AOT enabled)
OpenJ9   - ea40a01e9
OMR      - 88427d642
JCL      - 6e6a5a8e63 based on jdk-11.0.12+7)

$ ../jdk11_openj9_v1/bin/java -cp  .   JTest1
inlInternalsNewInstanceImpl: senderClass = 0x169d00, destClassName: [java/util/Collections$CheckedRandomAccessList]
inlInternalsNewInstanceImpl: checkModVis: [sun/reflect/misc/Trampoline] [java/util/Collections$CheckedRandomAccessList]
checkModVis: [sun/reflect/misc/Trampoline] [java/util/Collections$CheckedRandomAccessList] <------
Exception in thread "main" java.lang.Error: unexpected exception
...
$ ../jdk8_openj9_v1/bin/java -version
openjdk version "1.8.0_302-internal-debug"
OpenJDK Runtime Environment (build 1.8.0_302-internal-debug-jincheng_2021_07_23_00_20-b00)
Eclipse OpenJ9 VM (build visibility_check_NewInstanceImpl-ea40a01e9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210723_000000 (JIT enabled, AOT enabled)
OpenJ9   - ea40a01e9
OMR      - 88427d642
JCL      - c0b29ca593 based on jdk8u302-b07)

$ ../jdk8_openj9_v1/bin/java -cp  .   JTest1
$ (no debug info)

$ ../jdk11_openj9_v1/bin/java -version
openjdk version "11.0.12-internal" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12-internal+0-adhoc.jincheng.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build visibility_check_NewInstanceImpl-ea40a01e9, JRE 11 Linux amd64-64-Bit Compressed References 20210723_000000 (JIT enabled, AOT enabled)
OpenJ9   - ea40a01e9
OMR      - 88427d642
JCL      - 6e6a5a8e63 based on jdk-11.0.12+7)

$ ../jdk11_openj9_v1/bin/java -cp  .   JTest1
inlInternalsNewInstanceImpl: senderClass = 0x169d00, destClassName: [java/util/Collections$CheckedRandomAccessList]
inlInternalsNewInstanceImpl: checkModVis: [sun/reflect/misc/Trampoline] [java/util/Collections$CheckedRandomAccessList]
checkModVis: [sun/reflect/misc/Trampoline] [java/util/Collections$CheckedRandomAccessList] <------
Exception in thread "main" java.lang.Error: unexpected exception
...
```

3) Debugging in the java code in OpenJDK8/OpenJ9 as comared to OpenJDK11/OpenJ9 also confirmed that `sun/reflect/misc/Trampoline` never invoked `Class.newInstance()` on `java/util/Collections$CheckedRandomAccessList` in OpenJDK8/OpenJ9
![image](https://user-images.githubusercontent.com/18036229/126809361-9f336fac-362b-43ec-9a4c-ea4bb10a35b2.png)
against the debugging in OpenJDK11/OpenJ9
![image](https://user-images.githubusercontent.com/18036229/126809914-cfeaa3bb-24b8-423c-a9e0-27004d3ec763.png)
which means the source & implementation in OpenJDK8 and OpenJDK11 is totally different at this point.

4) Technically , there is no big difference between the exceptions triggered by OpenJDK11/OpenJ9 and Hotspot given the problem with java/util/Collections$CheckedRandomAccessList` was captured on both JDKs. The only difference of how the exeception  was triggered comes from the implementation in `Class.newInstance` in OpenJ9 at https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/Class.java
```
public T newInstance() throws IllegalAccessException, InstantiationException {
...
/*[IF JAVA_SPEC_VERSION >= 12]*/
	Class<?> callerClazz = getStackClass(1);
	if (callerClazz.classLoader == ClassLoader.bootstrapClassLoader) {
		/* newInstanceImpl() is required for all bootstrap classes to avoid an infinite loop
		 * when calling copyConstructor.invoke() in cacheConstructor() at the bootstrap stage
		 * as the constructors of bootstrap classes are not yet cached for use at that time.
		 */
		return (T)J9VMInternals.newInstanceImpl(this);
	} else {
		try {
			Constructor<?> ctr = getDeclaredConstructor();
			if (reflectionFactory == null) {
				reflectionFactory = AccessController.doPrivileged(new ReflectionFactory.GetReflectionFactoryAction());
			}
			return (T)reflectionFactory.newInstance(ctr, null, callerClazz); <-------- invoked in OpenJDK
		} catch (NoSuchMethodException  e) {
			InstantiationException instantiationEx = new InstantiationException();
			throw (InstantiationException)instantiationEx.initCause(e);
		} catch (InvocationTargetException e) {
			getUnsafe().throwException(e.getCause());
			return null;  //unreachable but required in compilation
		}
	}
/*[ELSE] JAVA_SPEC_VERSION >= 12*/
	return (T)J9VMInternals.newInstanceImpl(this); <-------- invoked in OpenJ9
/*[ENDIF] JAVA_SPEC_VERSION >= 12*/
}
```
For non-bootstrapped classes, 
[1] if  java version < 12 , `J9VMInternals.newInstanceImpl`(native code in OpenJ9) is invoked
[2] if  java version >= 12, `reflectionFactory.newInstance` (the implemenation in OpenJDK) is invoked.
e.g.  OpenJDK16/OpenJ9 ends up with the same exception as Hotspot as it picks up `reflectionFactory.newInstance`
```
../jdk16_openj9/bin/java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Semeru-16.0.1.0-m1 (build 16.0.1+9)
Eclipse OpenJ9 VM Semeru-16.0.1.0-m1 (build v0.27.0-release-642e6b68d, JRE 16 Linux amd64-64-Bit Compressed References 20210708_59 (JIT enabled, AOT enabled)
OpenJ9   - 642e6b68d
OMR      - 9db1c870d
JCL      - 3eb9c85d119 based on jdk-16.0.1+9)

$../jdk16_openj9/bin/java -cp  .   JTest1
Exception in thread "main" java.lang.Error: unexpected exception
	at AbstractTest.exceptionThrown(AbstractTest.java:10)
	at java.desktop/java.beans.Encoder.getValue(Encoder.java:113)
	at java.desktop/java.beans.Encoder.get(Encoder.java:257)
	at java.desktop/java.beans.PersistenceDelegate.writeObject(PersistenceDelegate.java:117)
	at java.desktop/java.beans.Encoder.writeObject(Encoder.java:79)
	at java.desktop/java.beans.XMLEncoder.writeObject(XMLEncoder.java:326)
	at java.desktop/java.beans.Encoder.writeExpression(Encoder.java:335)
	at java.desktop/java.beans.XMLEncoder.writeExpression(XMLEncoder.java:454)
	at java.desktop/java.beans.PersistenceDelegate.writeObject(PersistenceDelegate.java:120)
	at java.desktop/java.beans.Encoder.writeObject(Encoder.java:79)
	at java.desktop/java.beans.XMLEncoder.writeObject(XMLEncoder.java:326)
	at java.desktop/java.beans.Encoder.writeObject1(Encoder.java:263)
	at java.desktop/java.beans.Encoder.cloneStatement(Encoder.java:276)
	at java.desktop/java.beans.Encoder.writeStatement(Encoder.java:306)
	at java.desktop/java.beans.XMLEncoder.writeStatement(XMLEncoder.java:399)
	at java.desktop/java.beans.XMLEncoder.writeObject(XMLEncoder.java:329)
	at AbstractTest.writeObject(AbstractTest.java:38)
	at AbstractTest.testObject(AbstractTest.java:30)
	at AbstractTest.test(AbstractTest.java:24)
	at JTest1.main(JTest1.java:8)
Caused by: java.lang.InstantiationException
	at java.base/java.lang.Class.newInstance(Class.java:2318)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.desktop/java.beans.Statement.invokeInternal(Statement.java:304)
	at java.desktop/java.beans.Statement$2.run(Statement.java:187)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
	at java.desktop/java.beans.Statement.invoke(Statement.java:184)
	at java.desktop/java.beans.Expression.getValue(Expression.java:155)
	at java.desktop/java.beans.Encoder.getValue(Encoder.java:110)
	... 18 more
Caused by: java.lang.NoSuchMethodException: java.util.Collections$CheckedRandomAccessList.<init>()
	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:653)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:829)
	at java.base/java.lang.Class.newInstance(Class.java:2312)
	... 34 more

```

**Comment by ChengJin01** [comment]
Hi @JavaTailor, based on the investigation above, the exception was literally triggered on OpenJDK side. So please contact OpenJDK guys or Oracle for help as to how & why the exception occurred in OpenJDK11 and beyond as compared to OpenJDK8  given OpenJDK is not part of OpenJ9.

**Comment by JavaTailor** [comment]
Hi @ChengJin01 , thanks for your detailed and professional reply! We will report this to OpenJDK to find out what the problem is.
