### ISSUE TITLE
RuntimeAnnotationTests failing to parse some versions like "17-internal"

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13108]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_OpenJDK17/3
RuntimeAnnotationTests_0
```
Caused by: java.lang.NumberFormatException: For input string: "17-internal"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.openj9.test.annotation.ContainsRuntimeAnnotationTest.<init>(ContainsRuntimeAnnotationTest.java:84)
	... 28 more
```

New test https://github.com/eclipse-openj9/openj9/pull/13002

**Comment by pshipton** [comment]
@eric98zhang @llxia can we get a quick fix today pls, or we can revert until the fix is ready.

**Comment by llxia** [comment]
auto exclude test RuntimeAnnotationTests ver=17

**Comment by tajila** [comment]
> @eric98zhang @llxia can we get a quick fix today pls, or we can revert until the fix is ready.

@pshipton I think you meant @EricYangIBM
