### ISSUE TITLE
JDK8 aarch64_linux java/rmi/activation/rmidViaInheritedChannel/RmidViaInheritedChannel.java - NPE at RmidViaInheritedChannel.main(RmidViaInheritedChannel.java:122)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13122]
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.openjdk_aarch64_linux/14/` (`ub18-aarch64-8`):
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b07)
Eclipse OpenJ9 VM (build master-5d3e13320, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20210705_153 (JIT enabled, AOT enabled)
OpenJ9   - 5d3e13320
OMR      - 45201fd39
JCL      - b75b2819 based on jdk8u302-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_rmi_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F153%2FSemeru-debugimage_aarch64_linux_2021-07-05-14-10.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F153%2FSemeru-jre_aarch64_linux_2021-07-05-14-10.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F153%2FSemeru-testimage_aarch64_linux_2021-07-05-14-10.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F153%2FSemeru-jdk_aarch64_linux_2021-07-05-14-10.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-05T19:37:03.891Z] Running test jdk_rmi_1 ...
[2021-07-05T19:37:03.891Z] ===============================================
[2021-07-05T19:37:03.891Z] jdk_rmi_1 Start Time: Mon Jul  5 15:37:01 2021 Epoch Time (ms): 1625513821724
[2021-07-05T19:37:03.891Z] "/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-07-05T19:37:03.891Z] JVMSHRC005I No shared class caches available
[2021-07-05T19:37:03.891Z] JVMSHRC005I No shared class caches available
[2021-07-05T19:37:03.891Z] cache cleanup done
[2021-07-05T19:37:03.891Z] variation: Mode650
[2021-07-05T19:37:03.891Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-07-05T19:38:04.646Z] --------------------------------------------------
[2021-07-05T19:38:04.646Z] TEST: java/rmi/activation/rmidViaInheritedChannel/RmidViaInheritedChannel.java

[2021-07-05T19:38:04.647Z] export callback object and bind in registry
[2021-07-05T19:38:04.647Z] java.lang.NullPointerException
[2021-07-05T19:38:04.647Z] 	at RmidViaInheritedChannel.main(RmidViaInheritedChannel.java:122)
[2021-07-05T19:38:04.647Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-05T19:38:04.647Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-07-05T19:38:04.647Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-05T19:38:04.647Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-07-05T19:38:04.647Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-07-05T19:38:04.647Z] 	at java.lang.Thread.run(Thread.java:826)
[2021-07-05T19:38:04.647Z] 
[2021-07-05T19:38:04.647Z] JavaTest Message: Test threw exception: java.lang.NullPointerException
[2021-07-05T19:38:04.647Z] JavaTest Message: shutting down test

[2021-07-05T19:38:04.648Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.NullPointerException
[2021-07-05T19:38:04.648Z] --------------------------------------------------
[2021-07-05T19:41:36.397Z] Test results: passed: 121; failed: 1
[2021-07-05T19:41:44.934Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2021-07-05T19:41:44.934Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16255103144201/jdk_rmi_1/work
[2021-07-05T19:41:44.934Z] Error: Some tests failed or other problems occurred.
[2021-07-05T19:41:44.934Z] 
[2021-07-05T19:41:44.934Z] jdk_rmi_1_FAILED
```

30x grinder at `Grinder/16793`.

**Comment by knn-k** [comment]
No failures in 30x grinder above.
