### ISSUE TITLE
testvmcheck failures

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13120]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/44/
extended.functional testvmcheck failing on what looks like all modes and platforms, for Java 11 and 16.

Example:
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/43
testvmcheck_1
```
variation: Mode110
JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 
[IncludeExcludeTestAnnotationTransformer] [INFO] EXCLUDE_FILE environment variable: /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../TestConfig/resources/excludes/latest_exclude_11.txt
[IncludeExcludeTestAnnotationTransformer] [INFO] Processing exclude file: /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../TestConfig/resources/excludes/latest_exclude_11.txt
...
... TestNG 6.14.2 by C?dric Beust (cedric@beust.com)
...

[TestLoadingClassesFromJarfile] [WARN] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources are not end with .jar
Exception in thread "Thread-24" java.lang.AssertionError: TEST_STATUS=TEST_FAILED : org.openj9.test.annotation.ContainsRuntimeAnnotationTest
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile$StreamDumper.run(TestLoadingClassesFromJarfile.java:253)
FAILED: testLoadingClasses
java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:205)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:115)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

good
OpenJ9: e4043c9
OMR: 45201fd
OpenJDK11: d403e94
https://github.com/adoptium/aqa-tests.git 971950832563dc27d5e26e82fa894b0c5853b4df
https://github.com/adoptium/TKG.git 7af3fa1ac1a86750bc51c11c842cd537b2d39655

bad
OpenJ9: b06a90b
OMR: 45201fd
OpenJDK11: 6bf6ea3
https://github.com/adoptium/aqa-tests.git 98392343c32ef02bf8edaa532ed54a7cf14a17c5
https://github.com/adoptium/TKG.git 79ed3448a6e93c01bf7208ff4a3efb8b7e30b759

Changes
https://github.com/eclipse-openj9/openj9/compare/e4043c9...b06a90b
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/d403e94...6bf6ea3 - cmake for z/OS, unrelated
https://github.com/adoptium/aqa-tests/compare/971950832...98392343c32
https://github.com/adoptium/TKG/compare/7af3fa1ac1...79ed3448

Cause https://github.com/eclipse-openj9/openj9/pull/13002

**Comment by pshipton** [comment]
@EricYangIBM pls take a look
@tajila fyi

**Comment by tajila** [comment]
@EricYangIBM You need to add the new test to the excluded package list

```
 */
	@SuppressWarnings("nls")
	private static final HashSet<String> excludedPackages = 
	new HashSet<String>(Arrays.asList(new String[] {
			"com.apple.eawt",
			"com.apple.laf",
			"com.sun.beans.editors",
			"com.sun.imageio.plugins",
			"com.sun.java.swing",
			"com.sun.naming.internal",
			"com.sun.xml.internal",
			"java.applet",
			"java.awt",
			"java.lang.invoke",
			"java.util.PropertyPermission",
			"javax.imageio.ImageIO",
			"javax.swing",
			"org.openj9.test.classRelationshipVerifier.TestClassRelationshipVerifier",
			"sun.applet",
			"sun.awt",
			"sun.font",
			"sun.java2d",
			"sun.lwawt",
			"sun.print",
			"sun.reflect.misc.Trampoline",
			"sun.security.tools.policytool",
			"sun.swing",
			"com.oracle.net"
```

in `/openj9/test/functional/Java8andUp/src/org/openj9/test/vmcheck/TestLoadingClassesFromJarfile.java`
