### ISSUE TITLE
JDK17 java/io/InputStream/NullInputStream.java - NullPointerException: Cannot invoke "java.io.InputStream.available()" because "NullInputStream.openStream" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13125]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.openjdk_aarch64_linux/10/` (`cent7-aarch64-2`):
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+18 (build 17+18)
Eclipse OpenJ9 VM Temurin-17+18 (build master-5d3e13320, JRE 17 Linux aarch64-64-Bit Compressed References 20210705_10 (JIT enabled, AOT enabled)
OpenJ9   - 5d3e13320
OMR      - 45201fd39
JCL      - e681712e93 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_io_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F10%2FSemeru-testimage_aarch64_linux_2021-07-05-14-11.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F10%2FSemeru-jre_aarch64_linux_2021-07-05-14-11.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F10%2FSemeru-jdk_aarch64_linux_2021-07-05-14-11.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F10%2FSemeru-debugimage_aarch64_linux_2021-07-05-14-11.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-05T19:41:15.931Z] Running test jdk_io_1 ...
[2021-07-05T19:41:15.931Z] ===============================================
[2021-07-05T19:41:15.931Z] jdk_io_1 Start Time: Mon Jul  5 15:41:11 2021 Epoch Time (ms): 1625514071919
[2021-07-05T19:41:15.931Z] "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-07-05T19:41:15.931Z] JVMSHRC005I No shared class caches available
[2021-07-05T19:41:15.931Z] JVMSHRC005I No shared class caches available
[2021-07-05T19:41:15.931Z] cache cleanup done
[2021-07-05T19:41:15.931Z] variation: Mode650
[2021-07-05T19:41:15.931Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-07-05T19:41:53.853Z] --------------------------------------------------
[2021-07-05T19:41:53.853Z] TEST: java/io/InputStream/NullInputStream.java

[2021-07-05T19:41:53.854Z] STDOUT:
[2021-07-05T19:41:53.854Z] test NullInputStream.testAvailable(): failure
[2021-07-05T19:41:53.854Z] java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "NullInputStream.openStream" is null
[2021-07-05T19:41:53.854Z] 	at NullInputStream.testAvailable(NullInputStream.java:75)
[2021-07-05T19:41:53.854Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-05T19:41:53.854Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-07-05T19:41:53.855Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-05T19:41:53.855Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-07-05T19:41:53.855Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-07-05T19:41:53.855Z] 	at org.testng.TestRunner$$Lambda$125/0x00000000e40b0330.accept(Unknown Source)
[2021-07-05T19:41:53.855Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-07-05T19:41:53.855Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-07-05T19:41:53.855Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-07-05T19:41:53.855Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-07-05T19:41:53.855Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-07-05T19:41:53.855Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-07-05T19:41:53.855Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-07-05T19:41:53.855Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-07-05T19:41:53.855Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-07-05T19:41:53.855Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-07-05T19:41:53.855Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-07-05T19:41:53.855Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-07-05T19:41:53.855Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-07-05T19:41:53.855Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-07-05T19:41:53.855Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-05T19:41:53.855Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-07-05T19:41:53.855Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-05T19:41:53.855Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-07-05T19:41:53.855Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-07-05T19:41:53.855Z] 	at java.base/java.lang.Thread.run(Thread.java:883)

[2021-07-05T19:46:55.280Z] Test results: passed: 378; failed: 4
[2021-07-05T19:47:12.020Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2021-07-05T19:47:12.020Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_1625513488995/jdk_io_1/work
[2021-07-05T19:47:12.020Z] Error: Some tests failed or other problems occurred.
[2021-07-05T19:47:12.020Z] 
[2021-07-05T19:47:12.020Z] jdk_io_1_FAILED
```

30x grinder `Grinder/16798`

fyi @knn-k

**Comment by knn-k** [comment]
This is not an AArch64-specific issue.
ppc64 has the same failure in view/Test_openjdk/job/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/13/

**Comment by JasonFengJ9** [comment]
Reproduced w/ latest JDK17 `x86-64_linux` build at `Test_grinder/job/Grinder/17557`
```
16:33:48  openjdk version "17-internal" 2021-09-14
16:33:48  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
16:33:48  Eclipse OpenJ9 VM (build master-df51c203a8b, JRE 17 Linux amd64-64-Bit Compressed References 20210816_42 (JIT enabled, AOT enabled)
16:33:48  OpenJ9   - df51c203a8b
16:33:48  OMR      - ac3ab4821a5
16:33:48  JCL      - b40e984c3a1 based on jdk-17+35)

16:35:48  --------------------------------------------------
16:35:48  TEST: java/io/InputStream/NullInputStream.java

16:35:48  STDOUT:
16:35:48  test NullInputStream.testAvailable(): failure
16:35:48  java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "NullInputStream.openStream" is null
16:35:48  	at NullInputStream.testAvailable(NullInputStream.java:75)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:35:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:35:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:35:48  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
16:35:48  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
16:35:48  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
16:35:48  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
16:35:48  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
16:35:48  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
16:35:48  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
16:35:48  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
16:35:48  	at org.testng.TestRunner$$Lambda$128/0x00000000f40cb540.accept(Unknown Source)
16:35:48  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
16:35:48  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
16:35:48  	at org.testng.TestRunner.run(TestRunner.java:585)
16:35:48  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
16:35:48  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
16:35:48  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
16:35:48  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
16:35:48  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
16:35:48  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
16:35:48  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
16:35:48  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
16:35:48  	at org.testng.TestNG.runSuites(TestNG.java:1069)
16:35:48  	at org.testng.TestNG.run(TestNG.java:1037)
16:35:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:35:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:35:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:35:48  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
16:35:48  	at java.base/java.lang.Thread.run(Thread.java:883)

16:35:48  ===============================================
16:35:48  java/io/InputStream/NullInputStream.java
16:35:48  Total tests run: 20, Passes: 0, Failures: 20, Skips: 0
16:35:48  ===============================================
16:35:48  
16:35:48  STDERR:
16:35:48  java.lang.Exception: failures: 20
16:35:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:35:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:35:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:35:48  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
16:35:48  	at java.base/java.lang.Thread.run(Thread.java:883)
16:35:48  
16:35:48  JavaTest Message: Test threw exception: java.lang.Exception
16:35:48  JavaTest Message: shutting down test
16:35:48  
16:35:48  
16:35:48  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 20
16:35:48  --------------------------------------------------
16:35:48  Test results: failed: 1
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&CUSTOM_TARGET=java/io/InputStream/NullInputStream.java&TARGET=jdk_custom_0)

**Comment by JasonFengJ9** [comment]
Passed in a recent JDK17 (`openj9-staging`) build at `Test_grinder/job/Grinder/17601`
```
10:23:13  openjdk version "17-internal" 2021-09-14
10:23:13  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
10:23:13  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 17 Linux amd64-64-Bit Compressed References 20210819_45 (JIT enabled, AOT enabled)
10:23:13  OpenJ9   - cd8db74f1d4
10:23:13  OMR      - ac3ab4821a5
10:23:13  JCL      - b40e984c3a1 based on jdk-17+35)
```
Also passed in a recent JDK16 build at `Test_grinder/job/Grinder/17602`
```
10:22:33  openjdk version "16.0.2-internal" 2021-07-20
10:22:33  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16x86-64linuxPersonal)
10:22:33  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 16 Linux amd64-64-Bit Compressed References 20210819_284 (JIT enabled, AOT enabled)
10:22:33  OpenJ9   - cd8db74f1d4
10:22:33  OMR      - ac3ab4821a5
10:22:33  JCL      - 44316ee515b based on jdk-16.0.2+7)
```
closing..

**Comment by JasonFengJ9** [comment]
Similar with https://github.com/eclipse-openj9/openj9/issues/13022#issuecomment-903910981, the test passes at `Grinder/17636` w/ a recent JDK17 build against `adoptium/aqa-tests` folk branch [1] to use JDK17 extension repo `openj9-staging` branch.
```
11:51:02  openjdk version "17-internal" 2021-09-14
11:51:02  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
11:51:02  Eclipse OpenJ9 VM (build master-2ba48511f18, JRE 17 Linux amd64-64-Bit Compressed References 20210822_50 (JIT enabled, AOT enabled)
11:51:02  OpenJ9   - 2ba48511f18
11:51:02  OMR      - 6eec759cd2d
11:51:02  JCL      - b40e984c3a1 based on jdk-17+35)
```

closing..

[1] https://github.com/JasonFengJ9/openjdk-tests/tree/jdk17teststaging
