### ISSUE TITLE
comiling sanity.functional with OJDK MH enabled, ClassCastException: java.util.HashMap$Node incompatible with java.util.LinkedHashMap$Entry

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13128]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.functional_x86-64_mac_Nightly_testList_1/41
```
03:28:39      [javac] Compiling 25 source files to /Users/****/workspace/Test_openjdk16_j9_sanity.functional_x86-64_mac_Nightly_testList_1/aqa-tests/functional/cmdLineTests/shareClassTests/testClasses/build/Animals
03:28:42      [javac] Note: Some input files use or override a deprecated API.
03:28:42      [javac] Note: Recompile with -Xlint:deprecation for details.
03:28:42      [javac] Note: Some input files use unchecked or unsafe operations.
03:28:42      [javac] Note: Recompile with -Xlint:unchecked for details.
03:28:42      [javac] /Users/****/workspace/Test_openjdk16_j9_sanity.functional_x86-64_mac_Nightly_testList_1/aqa-tests/functional/cmdLineTests/shareClassTests/testClasses/build.xml:226: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
03:28:42      [javac] Compiling 20 source files to /Users/****/workspace/Test_openjdk16_j9_sanity.functional_x86-64_mac_Nightly_testList_1/aqa-tests/functional/cmdLineTests/shareClassTests/testClasses/build/AnimalsJar
03:28:45      [javac] java.lang.ClassCastException: java.util.HashMap$Node incompatible with java.util.LinkedHashMap$Entry
```

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this

**Comment by JasonFengJ9** [comment]
Sure.

**Comment by JasonFengJ9** [comment]
This compilation failure wasn't observed at `JDK16 OJDK MH` enabled internal builds.

From the test history [1], it only occurred once on July 5th, there was no diagnosis file so not much to investigate. 

Closing.. (can re-open if it becomes reproducible) 

[1] https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.functional_x86-64_mac_Nightly/

**Comment by JasonFengJ9** [comment]
Console output from https://github.com/eclipse-openj9/openj9/issues/13128#issuecomment-933628631 :
```
01:41:32      [javac] Compiling 1 source file to /home/****/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/aqa-tests/functional/VM_Test/data/bin/JarFileUpdateTestRunnerResource2
01:41:32      [javac] java.lang.ClassCastException: java.util.HashMap$Node incompatible with java.util.LinkedHashMap$Entry
01:41:32  
01:41:32  BUILD FAILED
01:41:32  /home/****/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/scripts/build_test.xml:82: The following error occurred while executing this line:
01:41:32  /home/****/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/aqa-tests/functional/build.xml:52: The following error occurred while executing this line:
01:41:32  /home/****/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/aqa-tests/functional/VM_Test/build.xml:218: The following error occurred while executing this line:
01:41:32  /home/****/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/aqa-tests/functional/VM_Test/build.xml:80: Compile failed; see the compiler error output for details.
01:41:32  
01:41:32  Total time: 1 minute 42 seconds
01:41:32  1
01:41:32  compile.mk:39: recipe for target 'compile' failed
```
The `ant` `javac` task failed
https://github.com/eclipse-openj9/openj9/blob/ca3da66257b846691a8cc9d7e23125065be7e780/test/functional/VM_Test/build.xml#L80

The source code being compiled
 https://github.com/eclipse-openj9/openj9/blob/ca3da66257b846691a8cc9d7e23125065be7e780/test/functional/VM_Test/data/JarFileUpdateTestRunnerResource2/Sample.java#L22-L26

Apparently the `ClassCastException` is not related to the test code being compiled, and it was thrown from `javac`  itself, however there was no stacktrace for further analysis. Considering this is the second occurrence so far, the exception is highly intermittent.

Moving to `0.29` release for now.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_OMR_testList_1/105
```
15:48:20      [javac] Compiling 18 source files to F:\Users\****\workspace\Test_openjdk11_j9_sanity.functional_x86-64_windows_OMR_testList_1\aqa-tests\functional\cmdLineTests\shareClassTests\TokenHelperTests\bin
15:48:21      [javac] An exception has occurred in the compiler (11.0.13-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
15:48:21      [javac] java.lang.ClassCastException: [Ljava.lang.Object; incompatible with [Lcom.sun.tools.javac.code.Symbol$OperatorSymbol;
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$OperatorHelper.initOperators(Operators.java:300)
15:48:21      [javac] 	at <unknown class>.get(Unknown Source)
15:48:21      [javac] 	at java.base/java.util.Optional.orElseGet(Optional.java:369)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$OperatorHelper.doLookup(Operators.java:287)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryOperatorHelper.doLookup(Operators.java:359)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryEqualityOperator.resolve(Operators.java:626)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators.lambda$resolveBinary$4(Operators.java:164)
15:48:21      [javac] 	at <unknown class>.apply(Unknown Source)
15:48:21      [javac] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
15:48:21      [javac] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
15:48:21      [javac] 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
15:48:21      [javac] 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
15:48:21      [javac] 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
15:48:21      [javac] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
15:48:21      [javac] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
15:48:21      [javac] 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
15:48:21      [javac] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
15:48:21      [javac] 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolve(Operators.java:178)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolveBinary(Operators.java:161)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:3388)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1993)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitParens(Attr.java:3325)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1851)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:702)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:3385)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1993)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitParens(Attr.java:3325)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1851)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:695)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitIf(Attr.java:1761)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1421)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:743)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1294)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1020)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1098)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4685)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4576)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4505)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:4450)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1341)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
15:48:21      [javac] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

@tajila @gacholio any idea why the stack trace contains `<unknown class>`? Liberty also recently saw this running testing on jdk17.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Release_testList_1/14
```
12:33:38      [javac] Compiling 18 source files to /home/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Release_testList_1/aqa-tests/functional/cmdLineTests/shareClassTests/TokenHelperTests/bin
12:33:41      [javac] An exception has occurred in the compiler (11.0.14-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
12:33:41      [javac] java.lang.ClassCastException: [Ljava.lang.Object; incompatible with [Lcom.sun.tools.javac.code.Symbol$OperatorSymbol;
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$OperatorHelper.initOperators(Operators.java:300)
12:33:41      [javac] 	at com.sun.tools.javac.comp.Operators$OperatorHelper$$Lambda$170/0x0000000000000000.get(Unknown Source)
12:33:41      [javac] 	at java.base/java.util.Optional.orElseGet(Optional.java:369)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$OperatorHelper.doLookup(Operators.java:287)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryOperatorHelper.doLookup(Operators.java:359)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryBooleanOperator.resolve(Operators.java:513)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators.lambda$resolveBinary$4(Operators.java:164)
12:33:41      [javac] 	at com.sun.tools.javac.comp.Operators$$Lambda$167/0x0000000000000000.apply(Unknown Source)
12:33:41      [javac] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
12:33:41      [javac] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
12:33:41      [javac] 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
12:33:41      [javac] 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
12:33:41      [javac] 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
12:33:41      [javac] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
12:33:41      [javac] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
12:33:41      [javac] 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
12:33:41      [javac] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
12:33:41      [javac] 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolve(Operators.java:178)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolveBinary(Operators.java:161)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:3388)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1993)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitParens(Attr.java:3325)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1851)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:695)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitIf(Attr.java:1761)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1421)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:743)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1294)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1020)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1098)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:655)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:724)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4685)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4576)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4505)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:4450)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1341)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
12:33:41      [javac] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
12:33:41  
12:33:41  BUILD FAILED
````
