### ISSUE TITLE
STF framework failed to recognize new product name - Semeru

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13154]
Failure link
------------

From an internal build `Test_openjdk8_j9_special.system_s390x_linux_testList_3/81/`:
```
semeru version "1.8.0_302-internal"
Semeru Runtime Environment (build 1.8.0_302-internal-202107090234-b07)
Eclipse OpenJ9 VM (build master-e56cf3054, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20210708_152 (JIT enabled, AOT enabled)
OpenJ9   - e56cf3054
OMR      - bdee22f4b
JCL      - 4b45aeb5 based on jdk8u302-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=MauveSingleInvocLoad_special_5m_3&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_s390x_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F152%2FSemeru-debugimage_s390x_linux_2021-07-09-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F152%2FSemeru-jdk_s390x_linux_2021-07-09-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F152%2FSemeru-testimage_s390x_linux_2021-07-09-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F152%2FSemeru-jre_s390x_linux_2021-07-09-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=fyre&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=89&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-09T03:48:21.097Z] GEN 20:48:19.864 - Found test. Project: 'openjdk.test.load' class: 'MauveSingleInvocLoad.class' Dir: '/home/jenkins/workspace/Test_openjdk8_j9_special.system_s390x_linux_testList_3/jvmtest/system/aqa-systemtest/openjdk.test.load/bin'
[2021-07-09T03:48:21.097Z] GEN 20:48:19.888 - Found test. Project: 'openjdk.test.load' class: 'net.adoptopenjdk.stf.MauveSingleInvocLoad'
[2021-07-09T03:48:21.097Z] GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: 'Java -version' output does not start with 'java version'. Actual output was: semeru version "1.8.0_302-internal"
[2021-07-09T03:48:21.097Z] GEN stderr Semeru Runtime Environment (build 1.8.0_302-internal-202107090234-b07)
[2021-07-09T03:48:21.097Z] GEN stderr Eclipse OpenJ9 VM (build master-e56cf3054, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20210708_152 (JIT enabled, AOT enabled)
[2021-07-09T03:48:21.097Z] GEN stderr OpenJ9   - e56cf3054
[2021-07-09T03:48:21.097Z] GEN stderr OMR      - bdee22f4b
[2021-07-09T03:48:21.097Z] GEN stderr JCL      - 4b45aeb5 based on jdk8u302-b07)
[2021-07-09T03:48:21.097Z] GEN stderr 
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.<init>(JavaVersion.java:102)
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getInstance(JavaVersion.java:116)
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.primaryJvm(StfEnvironmentCore.java:499)
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:228)
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:196)
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.configureClassLoader(ClassPathConfigurator.java:75)
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:195)
[2021-07-09T03:48:21.097Z] GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
[2021-07-09T03:48:21.097Z] Generation failed
[2021-07-09T03:48:21.097Z] 
[2021-07-09T03:48:21.097Z] MauveSingleInvocLoad_special_5m_3_FAILED
```

fyi @Mesbah-Alam

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
@Mesbah-Alam re https://github.com/adoptium/STF/pull/113#issuecomment-825011341, let's remove the java version checks in STF. java version already gets checked in TKG and we have other smoke tests and functional tests that check for java version.

**Comment by Mesbah-Alam** [comment]
@llxia - yah.. I'll get a PR ready for this.

**Comment by Mesbah-Alam** [comment]
https://github.com/adoptium/STF/pull/118 - should fix the issue.

**Comment by llxia** [comment]
Close this issue as it is fixed.
