### ISSUE TITLE
JDK16 Windows jdk_nio_0_FAILED - SocketException: Invalid argument: no further information

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13163]
Failure link
------------

From an internal build `Test_openjdk16_j9_extended.openjdk_x86-64_windows/16/`:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Temurin-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM Temurin-16.0.1+9 (build master-d5a8afc9d, JRE 16 Windows Server 2016 amd64-64-Bit Compressed References 20210710_54 (JIT enabled, AOT enabled)
OpenJ9   - d5a8afc9d
OMR      - bdee22f4b
JCL      - 3c4bffefe5 based on jdk-16.0.1+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_nio_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-64_windows&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-windows-x64-openj9%2F54%2FSemeru-debugimage_x64_windows_JDK16U_2021-07-10-13-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-windows-x64-openj9%2F54%2FSemeru-testimage_x64_windows_JDK16U_2021-07-10-13-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-windows-x64-openj9%2F54%2FSemeru-jre_x64_windows_JDK16U_2021-07-10-13-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-windows-x64-openj9%2F54%2FSemeru-jdk_x64_windows_JDK16U_2021-07-10-13-00.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=16&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk16&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-10T17:07:31.316Z] ===============================================
[2021-07-10T17:07:31.316Z] jdk_nio_0 Start Time: Sat Jul 10 10:07:27 2021 Epoch Time (ms): 1625936847733
[2021-07-10T17:07:31.316Z] "C:/Users/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-07-10T17:07:33.859Z] JVMSHRC005I No shared class caches available
[2021-07-10T17:07:33.859Z] JVMSHRC005I No shared class caches available
[2021-07-10T17:07:33.859Z] cache cleanup done
[2021-07-10T17:07:33.859Z] variation: Mode150
[2021-07-10T17:07:33.859Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-07-10T17:10:51.695Z] STDERR:
[2021-07-10T17:10:51.695Z] java.net.SocketException: Invalid argument: no further information
[2021-07-10T17:10:51.695Z] 	at java.base/sun.nio.ch.Net.setInterface6(Native Method)
[2021-07-10T17:10:51.695Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364)
[2021-07-10T17:10:51.695Z] 	at Loopback.test(Loopback.java:112)
[2021-07-10T17:10:51.695Z] 	at Loopback.main(Loopback.java:73)
[2021-07-10T17:10:51.695Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-10T17:10:51.695Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-07-10T17:10:51.695Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-10T17:10:51.695Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2021-07-10T17:10:51.695Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-07-10T17:10:51.695Z] 	at java.base/java.lang.Thread.run(Thread.java:883)
[2021-07-10T17:10:51.695Z] 
[2021-07-10T17:10:51.695Z] JavaTest Message: Test threw exception: java.net.SocketException
[2021-07-10T17:10:51.695Z] JavaTest Message: shutting down test
[2021-07-10T17:10:51.695Z] 
[2021-07-10T17:10:51.695Z] 
[2021-07-10T17:10:51.695Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.net.SocketException: Invalid argument: no further information
[2021-07-10T17:10:51.695Z] --------------------------------------------------
[2021-07-10T17:24:46.803Z] Test results: passed: 427; failed: 2
[2021-07-10T17:25:14.264Z] Report written to C:\Users\jenkins\workspace\Test_openjdk16_j9_extended.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
[2021-07-10T17:25:14.264Z] Results written to C:\Users\jenkins\workspace\Test_openjdk16_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16259284654673\jdk_nio_0\work
[2021-07-10T17:25:14.264Z] Error: Some tests failed or other problems occurred.
[2021-07-10T17:25:14.264Z] 
[2021-07-10T17:25:14.264Z] jdk_nio_0_FAILED
```

**Comment by pshipton** [comment]
Seems like a machine issue related to IPv6.

**Comment by JasonFengJ9** [comment]
Closing as dup of https://github.com/eclipse-openj9/openj9/issues/12082
