### ISSUE TITLE
JDK16 (OJDK MH) NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, int, java.lang.invoke.MemberName)" because "<parameter1>" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13166]
Failure link
------------

From an internal build `Test_openjdk16_j9_extended.openjdk_x86-64_mac/17/`:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Temurin-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM Temurin-16.0.1+9 (build master-d5a8afc9d, JRE 16 Mac OS X amd64-64-Bit Compressed References 20210710_57 (JIT enabled, AOT enabled)
OpenJ9   - d5a8afc9d
OMR      - bdee22f4b
JCL      - 3c4bffefe5 based on jdk-16.0.1+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_nio_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-64_mac&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-mac-x64-openj9%2F57%2FSemeru-jdk_x64_mac_JDK16U_2021-07-10-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-mac-x64-openj9%2F57%2FSemeru-jre_x64_mac_JDK16U_2021-07-10-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-mac-x64-openj9%2F57%2FSemeru-testimage_x64_mac_JDK16U_2021-07-10-13-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk16u%2Fjdk16u-mac-x64-openj9%2F57%2FSemeru-debugimage_x64_mac_JDK16U_2021-07-10-13-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=16&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk16&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-10T14:37:09.524Z] Running test jdk_nio_0 ...
[2021-07-10T14:37:09.524Z] ===============================================
[2021-07-10T14:37:09.524Z] jdk_nio_0 Start Time: Sat Jul 10 10:37:07 2021 Epoch Time (ms): 1625927827527
[2021-07-10T14:37:09.524Z] "/Users/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-07-10T14:37:09.524Z] JVMSHRC005I No shared class caches available
[2021-07-10T14:37:09.524Z] JVMSHRC005I No shared class caches available
[2021-07-10T14:37:09.524Z] cache cleanup done
[2021-07-10T14:37:09.524Z] variation: Mode150
[2021-07-10T14:37:09.524Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-07-10T14:39:40.557Z] [TestNG] Running:
[2021-07-10T14:39:40.557Z]   java/nio/Buffer/EqualsCompareTest.java
[2021-07-10T14:39:40.557Z] 
[2021-07-10T14:39:40.557Z] test EqualsCompareTest.testBuffers(java.nio.ByteBuffer HEAP): failure
[2021-07-10T14:39:40.557Z] java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, int, java.lang.invoke.MemberName)" because "<parameter1>" is null
[2021-07-10T14:39:40.557Z] 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
[2021-07-10T14:39:40.557Z] 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
[2021-07-10T14:39:40.557Z] 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
[2021-07-10T14:39:40.557Z] 	at EqualsCompareTest$BufferType.get(EqualsCompareTest.java:133)
[2021-07-10T14:39:40.557Z] 	at EqualsCompareTest$BufferType.pairWiseEquals(EqualsCompareTest.java:186)
[2021-07-10T14:39:40.557Z] 	at EqualsCompareTest.testBufferType(EqualsCompareTest.java:645)
[2021-07-10T14:39:40.557Z] 	at EqualsCompareTest.testBuffers(EqualsCompareTest.java:534)
[2021-07-10T14:39:40.557Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-10T14:39:40.557Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-07-10T14:39:40.557Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-10T14:39:40.557Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2021-07-10T14:39:40.557Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-07-10T14:39:40.558Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-07-10T14:39:40.558Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-07-10T14:39:40.558Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-07-10T14:39:40.558Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-07-10T14:39:40.558Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-07-10T14:39:40.558Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-07-10T14:39:40.558Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-07-10T14:39:40.558Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-07-10T14:39:40.558Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-07-10T14:39:40.558Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-07-10T14:39:40.558Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-07-10T14:39:40.558Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-07-10T14:39:40.558Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-07-10T14:39:40.558Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-07-10T14:39:40.558Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-07-10T14:39:40.558Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-07-10T14:39:40.558Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-07-10T14:39:40.558Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-10T14:39:40.558Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-07-10T14:39:40.558Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-10T14:39:40.558Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2021-07-10T14:39:40.558Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-07-10T14:39:40.558Z] 	at java.base/java.lang.Thread.run(Thread.java:883)
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.ByteBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.CharBuffer HEAP): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.CharBuffer HEAP_VIEW): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.CharBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.ShortBuffer HEAP): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.ShortBuffer HEAP_VIEW): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.ShortBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.IntBuffer HEAP): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.IntBuffer HEAP_VIEW): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.IntBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.FloatBuffer HEAP): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.FloatBuffer HEAP_VIEW): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.FloatBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.LongBuffer HEAP): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.LongBuffer HEAP_VIEW): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.LongBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.DoubleBuffer HEAP): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(EqualsCompareTest$BufferType$Doubles@e3f55eb2): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testBuffers(java.nio.DoubleBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testCharBuffers(java.nio.CharBuffer HEAP): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testCharBuffers(java.nio.CharBuffer HEAP_VIEW): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testCharBuffers(java.nio.CharBuffer DIRECT): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.FloatBuffer HEAP, 2143289344, 2139095041, EqualsCompareTest$$Lambda$100/0x000000009404d040@88829deb): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.FloatBuffer HEAP_VIEW, 2143289344, 2139095041, EqualsCompareTest$$Lambda$100/0x000000009404d040@88829deb): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.FloatBuffer DIRECT, 2143289344, 2139095041, EqualsCompareTest$$Lambda$100/0x000000009404d040@88829deb): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.DoubleBuffer HEAP, 9221120237041090560, 9218868437227405313, EqualsCompareTest$$Lambda$101/0x000000009404d1a8@e4fae65b): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(EqualsCompareTest$BufferType$Doubles@87abe775, 9221120237041090560, 9218868437227405313, EqualsCompareTest$$Lambda$101/0x000000009404d1a8@e4fae65b): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.DoubleBuffer DIRECT, 9221120237041090560, 9218868437227405313, EqualsCompareTest$$Lambda$101/0x000000009404d1a8@e4fae65b): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.FloatBuffer HEAP, 0, 2147483648, EqualsCompareTest$$Lambda$100/0x000000009404d040@88829deb): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.FloatBuffer HEAP_VIEW, 0, 2147483648, EqualsCompareTest$$Lambda$100/0x000000009404d040@88829deb): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.FloatBuffer DIRECT, 0, 2147483648, EqualsCompareTest$$Lambda$100/0x000000009404d040@88829deb): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.DoubleBuffer HEAP, 0, -9223372036854775808, EqualsCompareTest$$Lambda$101/0x000000009404d1a8@e4fae65b): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(EqualsCompareTest$BufferType$Doubles@84efaf9b, 0, -9223372036854775808, EqualsCompareTest$$Lambda$101/0x000000009404d1a8@e4fae65b): success
[2021-07-10T14:39:40.558Z] test EqualsCompareTest.testFloatBuffers(java.nio.DoubleBuffer DIRECT, 0, -9223372036854775808, EqualsCompareTest$$Lambda$101/0x000000009404d1a8@e4fae65b): success
[2021-07-10T14:39:40.558Z] 
[2021-07-10T14:39:40.558Z] ===============================================
[2021-07-10T14:39:40.558Z] java/nio/Buffer/EqualsCompareTest.java
[2021-07-10T14:39:40.558Z] Total tests run: 35, Failures: 1, Skips: 0
[2021-07-10T14:39:40.558Z] ===============================================
[2021-07-10T14:39:40.558Z] 
[2021-07-10T14:39:40.558Z] STDERR:
[2021-07-10T14:39:40.558Z] java.lang.Exception: failures: 1
[2021-07-10T14:39:40.558Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2021-07-10T14:39:40.558Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-10T14:39:40.558Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-07-10T14:39:40.558Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-10T14:39:40.558Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2021-07-10T14:39:40.558Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-07-10T14:39:40.558Z] 	at java.base/java.lang.Thread.run(Thread.java:883)
[2021-07-10T14:39:40.558Z] 
[2021-07-10T14:39:40.558Z] JavaTest Message: Test threw exception: java.lang.Exception
[2021-07-10T14:39:40.558Z] JavaTest Message: shutting down test
[2021-07-10T14:39:40.559Z] 
[2021-07-10T14:39:40.559Z] 
[2021-07-10T14:39:40.559Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2021-07-10T14:39:40.559Z] --------------------------------------------------
[2021-07-10T14:43:31.927Z] Test results: passed: 428; failed: 1
[2021-07-10T14:43:31.927Z] Report written to /Users/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_x86-64_mac/jvmtest/openjdk/report/html/report.html
[2021-07-10T14:43:31.927Z] Results written to /Users/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16259250981024/jdk_nio_0/work
[2021-07-10T14:43:31.927Z] Error: Some tests failed or other problems occurred.
[2021-07-10T14:43:31.927Z] 
[2021-07-10T14:43:31.927Z] jdk_nio_0_FAILED
```

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/13129
