### ISSUE TITLE
JDK16 (OJDK MH) NullPointerException: Cannot read field "member" because "mh" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13164]
Failure link
------------

From an internal build `Test_openjdk16_j9_special.system_x86-64_windows_testList_0/49/`:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Temurin-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM Temurin-16.0.1+9 (build master-d5a8afc9d, JRE 16 Windows Server 2016 amd64-64-Bit Compressed References 20210710_54 (JIT enabled, AOT enabled)
OpenJ9   - d5a8afc9d
OMR      - bdee22f4b
JCL      - 3c4bffefe5 based on jdk-16.0.1+9)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-10T18:31:25.458Z] Running test MathLoadTest_all_special_5m_14 ...
[2021-07-10T18:31:25.458Z] ===============================================
[2021-07-10T18:31:26.786Z] MathLoadTest_all_special_5m_14 Start Time: Sat Jul 10 11:31:00 2021 Epoch Time (ms): 1625941860002
[2021-07-10T18:31:26.786Z] "C:/Users/jenkins/workspace/Test_openjdk16_j9_special.system_x86-64_windows_testList_0/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk16_j9_special.system_x86-64_windows_testList_0/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-07-10T18:31:27.895Z] JVMSHRC005I No shared class caches available
[2021-07-10T18:31:27.895Z] JVMSHRC005I No shared class caches available
[2021-07-10T18:31:27.895Z] cache cleanup done
[2021-07-10T18:31:29.020Z] variation: Mode553
[2021-07-10T18:31:29.020Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:count=0 

[2021-07-10T18:32:24.690Z] MLT java.lang.NullPointerException: Cannot read field "member" because "mh" is null
[2021-07-10T18:32:24.690Z] MLT 	at java.lang.invoke.DirectMethodHandle.internalMemberName(DirectMethodHandle.java:330) ~[?:?]
[2021-07-10T18:32:24.690Z] MLT 	at java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH) ~[?:?]
[2021-07-10T18:32:24.690Z] MLT 	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH) ~[?:?]
[2021-07-10T18:32:24.691Z] MLT 	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH) ~[?:?]
[2021-07-10T18:32:24.691Z] MLT 	at net.adoptopenjdk.stf.environment.DirectoryRef.childFile(DirectoryRef.java:112) ~[bin/:?]
[2021-07-10T18:32:24.691Z] MLT 	at net.adoptopenjdk.loadTest.InventoryData.readInventoryFile(InventoryData.java:135) ~[bin/:?]
[2021-07-10T18:32:24.691Z] MLT 	at net.adoptopenjdk.loadTest.InventoryData.<init>(InventoryData.java:96) ~[bin/:?]
[2021-07-10T18:32:24.691Z] MLT 	at net.adoptopenjdk.loadTest.LoadTest.createSuite(LoadTest.java:478) ~[bin/:?]
[2021-07-10T18:32:24.691Z] MLT 	at net.adoptopenjdk.loadTest.LoadTest.<init>(LoadTest.java:329) ~[bin/:?]
[2021-07-10T18:32:24.691Z] MLT 	at net.adoptopenjdk.loadTest.LoadTest.main(LoadTest.java:106) [bin/:?]

[2021-07-10T18:32:24.691Z] STF 11:31:55.703 - =====================   R E S U L T S   =====================
[2021-07-10T18:32:24.691Z] STF 11:31:55.703 - Stage results:
[2021-07-10T18:32:24.691Z] STF 11:31:55.703 -   setUp:     pass
[2021-07-10T18:32:24.691Z] STF 11:31:55.703 -   execute:  *fail*
[2021-07-10T18:32:24.691Z] STF 11:31:55.703 -   teardown:  pass
[2021-07-10T18:32:24.691Z] STF 11:31:55.703 - 
[2021-07-10T18:32:24.691Z] STF 11:31:55.703 - Overall result: **FAILED**
[2021-07-10T18:32:24.691Z] 
[2021-07-10T18:32:24.691Z] MathLoadTest_all_special_5m_14_FAILED
```

This is `JDK16` head stream enabled with `OJDK MH`.

fyi @tajila @fengxue-IS

**Comment by JasonFengJ9** [comment]
Also seen at https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_special.system_s390x_linux_Personal/8/tapResults/
```
===============================================
Running test LambdaLoadTest_special_J9_5m_14 ...
===============================================
LambdaLoadTest_special_J9_5m_14 Start Time: Sat Jul 10 09:49:01 2021 Epoch Time (ms): 1625924941256
variation: Mode553
JVM_OPTIONS:  -XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:count=0 

LT  09:49:26.836 - Failed to initialise LoadTest
LT  java.lang.NullPointerException: null
LT  	at java.lang.invoke.DirectMethodHandle.internalMemberName(DirectMethodHandle.java:330) ~[?:?]
LT  	at java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH) ~[?:?]
LT  	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH) ~[?:?]
LT  	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH) ~[?:?]
LT  	at net.adoptopenjdk.stf.environment.DirectoryRef.childFile(DirectoryRef.java:112) ~[bin/:?]
LT  	at net.adoptopenjdk.loadTest.InventoryData.readInventoryFile(InventoryData.java:135) ~[bin/:?]
LT  	at net.adoptopenjdk.loadTest.InventoryData.<init>(InventoryData.java:96) ~[bin/:?]
LT  	at net.adoptopenjdk.loadTest.LoadTest.createSuite(LoadTest.java:478) ~[bin/:?]
LT  	at net.adoptopenjdk.loadTest.LoadTest.<init>(LoadTest.java:329) ~[bin/:?]
LT  	at net.adoptopenjdk.loadTest.LoadTest.main(LoadTest.java:106) [bin/:?]
STF 09:49:27.668 - **FAILED** Process LT  ended with exit code (2) and not the expected exit code/s (0)

STF 09:49:27.732 - =====================   R E S U L T S   =====================
STF 09:49:27.732 - Stage results:
STF 09:49:27.732 -   setUp:     pass
STF 09:49:27.732 -   execute:  *fail*
STF 09:49:27.732 -   teardown:  pass
STF 09:49:27.732 - 
STF 09:49:27.732 - Overall result: **FAILED**

LambdaLoadTest_special_J9_5m_14_FAILED
```

**Comment by fengxue-IS** [comment]
**LambdaLoadTest_special_J9_5m_14** : 20/20 passed on s390_linux `Test_grinder/job/Grinder/17983/`
** MathLoadTest_all_special_5m_14**: 20/20 passed on x86-64_windows `Test_grinder/job/Grinder/17982/`

Closing issue as failure not reproducible in current JDK 17 build. (Reopen if seen again)
