### ISSUE TITLE
JDK8 aarch64 cmdLineTester_shrcdbgddrext_1 !shrc jitpstats - Exception in thread "main" java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13226]
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.functional_aarch64_linux_testList_2/26/` `ub18-aarch64-8`:
```
semeru version "1.8.0_302-beta"
Semeru Runtime Environment (build 1.8.0_302-beta-202107210233-b07)
Eclipse OpenJ9 VM (build master-4d6750e23, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20210721_165 (JIT enabled, AOT enabled)
OpenJ9   - 4d6750e23
OMR      - 88427d642
JCL      - 4b45aeb5 based on jdk8u302-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=cmdLineTester_shrcdbgddrext_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_extended.functional_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F165%2FSemeru-debugimage_aarch64_linux_JDK8U_2021-07-21-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F165%2FSemeru-testimage_aarch64_linux_JDK8U_2021-07-21-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F165%2FSemeru-jre_aarch64_linux_JDK8U_2021-07-21-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F165%2FSemeru-jdk_aarch64_linux_JDK8U_2021-07-21-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=74&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-21T03:31:41.978Z] Running test cmdLineTester_shrcdbgddrext_1 ...
[2021-07-21T03:31:41.978Z] ===============================================
[2021-07-21T03:31:41.978Z] cmdLineTester_shrcdbgddrext_1 Start Time: Tue Jul 20 23:31:41 2021 Epoch Time (ms): 1626838301666
[2021-07-21T03:31:41.978Z] "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_aarch64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_aarch64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-07-21T03:31:41.978Z] JVMSHRC005I No shared class caches available
[2021-07-21T03:31:41.978Z] JVMSHRC005I No shared class caches available
[2021-07-21T03:31:41.978Z] cache cleanup done
[2021-07-21T03:31:41.978Z] variation: Mode610
[2021-07-21T03:31:41.978Z] JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 

[2021-07-21T03:32:45.243Z] Testing: Run !shrc jitpstats
[2021-07-21T03:32:45.243Z] Test start time: 2021/07/20 23:32:44 Eastern Standard Time
[2021-07-21T03:32:45.243Z] Running command: /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_aarch64_linux_testList_2/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core2.dmp
[2021-07-21T03:32:45.243Z] Time spent starting: 1 milliseconds
[2021-07-21T03:32:46.269Z] Time spent executing: 1639 milliseconds
[2021-07-21T03:32:46.269Z] Test result: FAILED
[2021-07-21T03:32:46.269Z] Output from test:
[2021-07-21T03:32:46.269Z]  [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
[2021-07-21T03:32:46.270Z]  [OUT] Loading image from DTFJ...
[2021-07-21T03:32:46.270Z]  [OUT] 
[2021-07-21T03:32:46.270Z]  [ERR] Exception in thread "main" java.lang.IncompatibleClassChangeError
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.lang.StringBuilder.append(StringBuilder.java:2237)
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.lang.StringBuilder.append(StringBuilder.java:56)
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.util.Formatter$FixedString.print(Formatter.java:2595)
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.util.Formatter.format(Formatter.java:2508)
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.util.Formatter.format(Formatter.java:2455)
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.lang.String.format(String.java:4243)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.PointerHelper.beginAnnotatedMethod(BytecodeGenerator.java:420)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.PointerHelper.doSimpleTypeMethod(BytecodeGenerator.java:1405)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.PointerHelper.doAccessorMethods(BytecodeGenerator.java:520)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.PointerHelper.generate(BytecodeGenerator.java:1661)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.PointerHelper.getClassBytes(BytecodeGenerator.java:321)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.BytecodeGenerator.getPointerClassBytes(BytecodeGenerator.java:108)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.StructureReader.getPointerClassBytes(StructureReader.java:1125)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.J9DDRClassLoader.getPointerClass(J9DDRClassLoader.java:227)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.J9DDRClassLoader.findClass(J9DDRClassLoader.java:129)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.J9DDRClassLoader.loadClass(J9DDRClassLoader.java:206)
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.vm29.pointer.AbstractPointer.initializeCache(AbstractPointer.java:565)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.vm29.pointer.AbstractPointer.<clinit>(AbstractPointer.java:56)
[2021-07-21T03:32:46.270Z]  [ERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-21T03:32:46.270Z]  [ERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-07-21T03:32:46.270Z]  [ERR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-21T03:32:46.270Z]  [ERR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.VMDataFactory.getVMData(VMDataFactory.java:224)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.VMDataFactory.getAllVMData(VMDataFactory.java:143)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.VMDataFactory.getVMData(VMDataFactory.java:106)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9RASImageDataFactory.getRasData(J9RASImageDataFactory.java:106)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9RASImageDataFactory.getProcessData(J9RASImageDataFactory.java:53)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImageProcess.checkFailureInfo(J9DDRImageProcess.java:167)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImageProcess.getEnvironment(J9DDRImageProcess.java:246)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImageProcess.getCommandLine(J9DDRImageProcess.java:150)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImageProcess.getExecutablePath(J9DDRImageProcess.java:315)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImage.passBackExecutablePath(J9DDRImage.java:92)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImage.<init>(J9DDRImage.java:72)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImageFactory.getImage(J9DDRImageFactory.java:132)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.dtfj.image.j9.ImageFactory.foundImage(ImageFactory.java:378)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.dtfj.image.j9.ImageFactory.getImage(ImageFactory.java:208)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.commands.OpenCommand.imagesFromCommandLine(OpenCommand.java:115)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.commands.OpenCommand.run(OpenCommand.java:83)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.java.diagnostics.utils.Context.tryCommand(Context.java:141)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.java.diagnostics.utils.Context.execute(Context.java:97)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:173)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:157)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.Session.imageFromCommandLine(Session.java:610)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.Session.sessionInit(Session.java:226)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.Session.<init>(Session.java:175)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.Session.getInstance(Session.java:171)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:51)
[2021-07-21T03:32:46.270Z]  [ERR] 	at com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
[2021-07-21T03:32:46.270Z] >> Success condition was not found: [Output match: JITPROFILE data !]
[2021-07-21T03:32:46.270Z] >> Required condition was not found: [Output match: JITPROFILE data length]
[2021-07-21T03:32:46.270Z] >> Failure condition was not found: [Output match: no shared cache]
[2021-07-21T03:32:46.270Z] >> Failure condition was not found: [Output match: unable to read]
[2021-07-21T03:32:46.270Z] >> Failure condition was not found: [Output match: could not read]
[2021-07-21T03:32:46.270Z] >> Failure condition was not found: [Output match: dump event]
[2021-07-21T03:32:46.270Z] >> Failure condition was not found: [Output match: DDRInteractiveCommandException]
[2021-07-21T03:32:46.270Z] 
[2021-07-21T03:32:46.270Z] 
[2021-07-21T03:32:46.270Z] ---TEST RESULTS---
[2021-07-21T03:32:46.270Z] Number of PASSED tests: 27 out of 28
[2021-07-21T03:32:46.270Z] Number of FAILED tests: 1 out of 28
[2021-07-21T03:32:46.270Z] 
[2021-07-21T03:32:46.270Z] ---SUMMARY OF FAILED TESTS---
[2021-07-21T03:32:46.270Z] Run !shrc jitpstats
[2021-07-21T03:32:46.270Z] -----------------------------
[2021-07-21T03:32:46.270Z] 
[2021-07-21T03:32:46.270Z] 
[2021-07-21T03:32:46.270Z] cmdLineTester_shrcdbgddrext_1_FAILED
```

fyi @knn-k

**Comment by knn-k** [comment]
No failure in 20x Grinder.  /job/Grinder/17593/
