### ISSUE TITLE
JDK8 java/util/logging/FileHandlerAccessTest.java - AssertionError at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13223]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/57/console
```
22:24:33  openjdk version "1.8.0_302-internal"
22:24:33  OpenJDK Runtime Environment (build 1.8.0_302-internal-****_2021_07_19_22_12-b00)
22:24:33  Eclipse OpenJ9 VM (build master-88dbf3b34f4, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20210719_56 (JIT enabled, AOT enabled)
22:24:33  OpenJ9   - 88dbf3b34f4
22:24:33  OMR      - 88427d6420f
22:24:33  JCL      - 4b45aeb5fab based on jdk8u302-b07)
```
[Re-run in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Nightly&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK8_ppc64le_linux_Nightly%2F56%2FOpenJ9-JDK8-ppc64le_linux-20210719-221238.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK8_ppc64le_linux_Nightly%2F56%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=ci-eclipse-openj9&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=88dbf3b34f4796f0d9fc4d749dc234178ef7cb33&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
22:48:49  --------------------------------------------------
22:48:49  TEST: java/util/logging/FileHandlerAccessTest.java

22:48:49  STDERR:
22:48:49  STATUS:Passed.
22:48:49  java.lang.AssertionError
22:48:49  	at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)
22:48:49  	at sun.nio.ch.SharedFileLockTable.removeAll(FileLockTable.java:222)
22:48:49  	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:119)
22:48:49  	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
22:48:49  	at java.util.logging.FileHandler.close(FileHandler.java:751)
22:48:49  	at FileHandlerAccessTest.access(FileHandlerAccessTest.java:50)
22:48:49  	at FileHandlerAccessTest$$Lambda$1/0x0000000000000000.run(Unknown Source)
22:48:49  	at java.lang.Thread.run(Thread.java:826)
22:48:49  STATUS:Failed.`main' threw exception: java.lang.AssertionError

22:48:49  --------------------------------------------------
22:54:28  Test results: passed: 650; failed: 1
22:54:28  Report written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/report/html/report.html
22:54:28  Results written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16267484876022/jdk_util_0/work
22:54:28  Error: Some tests failed or other problems occurred.
22:54:28  
22:54:28  jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/177
jdk_util_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops`
java/util/logging/FileHandlerAccessTest.java
```
01:59:23  STDOUT:
01:59:23  Testing with 20 threads
01:59:23  STDERR:
01:59:23  STATUS:Passed.
01:59:23  java.lang.AssertionError
01:59:23  	at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)
01:59:23  	at sun.nio.ch.SharedFileLockTable.removeAll(FileLockTable.java:222)
01:59:23  	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:119)
01:59:23  	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
01:59:23  	at java.util.logging.FileHandler.close(FileHandler.java:751)
01:59:23  	at FileHandlerAccessTest.access(FileHandlerAccessTest.java:50)
01:59:23  	at FileHandlerAccessTest$$Lambda$1/0x0000000000000000.run(Unknown Source)
01:59:23  	at java.lang.Thread.run(Thread.java:827)
01:59:23  STATUS:Failed.`main' threw exception: java.lang.AssertionError
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/224 - [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3)
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/logging/FileHandlerAccessTest.java

```
02:59:13  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError
02:59:13  REASON: User specified action: run main/othervm FileHandlerAccessTest 20 
02:59:13  TIME:   0.159 seconds
02:59:13  messages:
02:59:13  command: main FileHandlerAccessTest 20
02:59:13  reason: User specified action: run main/othervm FileHandlerAccessTest 20 
02:59:13  Mode: othervm [/othervm specified]
02:59:13  elapsed time (seconds): 0.159
02:59:13  configuration:
02:59:13  STDOUT:
02:59:13  Testing with 20 threads
02:59:13  STDERR:
02:59:13  STATUS:Passed.
02:59:13  java.lang.AssertionError
02:59:13  	at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)
02:59:13  	at sun.nio.ch.SharedFileLockTable.removeAll(FileLockTable.java:222)
02:59:13  	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:119)
02:59:13  	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
02:59:13  	at java.util.logging.FileHandler.close(FileHandler.java:751)
02:59:13  	at FileHandlerAccessTest.access(FileHandlerAccessTest.java:50)
02:59:13  	at java.lang.Thread.run(Thread.java:832)
02:59:13  STATUS:Failed.`main' threw exception: java.lang.AssertionError
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/321
jdk_util_0 
java/util/logging/FileHandlerAccessTest.java
```
22:58:46  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError
22:58:46  REASON: User specified action: run main/othervm FileHandlerAccessTest 20 
22:58:46  TIME:   0.193 seconds
22:58:46  messages:
22:58:46  command: main FileHandlerAccessTest 20
22:58:46  reason: User specified action: run main/othervm FileHandlerAccessTest 20 
22:58:46  Mode: othervm [/othervm specified]
22:58:46  elapsed time (seconds): 0.193
22:58:46  configuration:
22:58:46  STDOUT:
22:58:46  Testing with 20 threads
22:58:46  STDERR:
22:58:46  STATUS:Passed.
22:58:46  java.lang.AssertionError
22:58:46  	at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)
22:58:46  	at sun.nio.ch.SharedFileLockTable.removeAll(FileLockTable.java:222)
22:58:46  	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:119)
22:58:46  	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
22:58:46  	at java.util.logging.FileHandler.close(FileHandler.java:751)
22:58:46  	at FileHandlerAccessTest.access(FileHandlerAccessTest.java:50)
22:58:46  	at java.lang.Thread.run(Thread.java:831)
22:58:46  STATUS:Failed.`main' threw exception: java.lang.AssertionError
22:58:46  rerun:
22:58:46  cd /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16571618102372/jdk_util_0/work/scratch/1 && \
22:58:46  DISPLAY=:0 \
22:58:46  HOME=/home/jenkins \
22:58:46  LANG=en_US.UTF-8 \
22:58:46  PATH=/bin:/usr/bin:/usr/sbin \
22:58:46  CLASSPATH=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16571618102372/jdk_util_0/work/classes/0/java/util/logging:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/util/logging:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
22:58:46      /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
22:58:46          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
22:58:46          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
22:58:46          -Dtest.compiler.opts= \
22:58:46          -Dtest.java.opts= \
22:58:46          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image \
22:58:46          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image \
22:58:46          -Dtest.timeout.factor=8.0 \
22:58:46          -Dtest.root=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/jdk/test \
22:58:46          -Dtest.name=java/util/logging/FileHandlerAccessTest.java \
22:58:46          -Dtest.file=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/util/logging/FileHandlerAccessTest.java \
22:58:46          -Dtest.src=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/util/logging \
22:58:46          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/util/logging \
22:58:46          -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16571618102372/jdk_util_0/work/classes/0/java/util/logging \
22:58:46          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16571618102372/jdk_util_0/work/classes/0/java/util/logging \
22:58:46          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16571618102372/jdk_util_0/work/classes/0/java/util/logging:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/jdk/test/java/util/logging \
22:58:46          -ea \
22:58:46          -esa \
22:58:46          -Xmx1540m \
22:58:46          -Xdump:system:none \
22:58:46          -Xdump:heap:none \
22:58:46          -Xdump:system:events=gpf+abort+traceassert+corruptcache \
22:58:46          -XX:+UseCompressedOops \
22:58:46          com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16571618102372/jdk_util_0/work/java/util/logging/FileHandlerAccessTest.d/main.0.jta 20
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/374
jdk_util_0, jdk_util_1
java/util/logging/FileHandlerAccessTest.java
```
22:16:56  STDOUT:
22:16:56  Testing with 20 threads
22:16:56  STDERR:
22:16:56  STATUS:Passed.
22:16:56  java.lang.AssertionError
22:16:56  	at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)
22:16:56  	at sun.nio.ch.SharedFileLockTable.removeAll(FileLockTable.java:222)
22:16:56  	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:119)
22:16:56  	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
22:16:56  	at java.util.logging.FileHandler.close(FileHandler.java:751)
22:16:56  	at FileHandlerAccessTest.access(FileHandlerAccessTest.java:50)
22:16:56  	at java.lang.Thread.run(Thread.java:826)
22:16:56  STATUS:Failed.`main' threw exception: java.lang.AssertionError
```

**Comment by JasonFengJ9** [comment]
[JDK8 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_testList_0/619/)(`rhel8s390x-svl-rt10-1`)
```
[2024-05-31T03:20:36.267Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2024-05-31T03:20:36.267Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2024-05-31T03:28:07.716Z] TEST: java/util/logging/FileHandlerAccessTest.java

[2024-05-31T03:28:07.716Z] STDERR:
[2024-05-31T03:28:07.716Z] STATUS:Passed.
[2024-05-31T03:28:07.716Z] java.lang.AssertionError
[2024-05-31T03:28:07.716Z] 	at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)
[2024-05-31T03:28:07.716Z] 	at sun.nio.ch.SharedFileLockTable.removeAll(FileLockTable.java:222)
[2024-05-31T03:28:07.716Z] 	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:119)
[2024-05-31T03:28:07.716Z] 	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
[2024-05-31T03:28:07.716Z] 	at java.util.logging.FileHandler.close(FileHandler.java:751)
[2024-05-31T03:28:07.716Z] 	at FileHandlerAccessTest.access(FileHandlerAccessTest.java:50)
[2024-05-31T03:28:07.716Z] 	at java.lang.Thread.run(Thread.java:826)
[2024-05-31T03:28:07.716Z] STATUS:Failed.`main' threw exception: java.lang.AssertionError

[2024-05-31T03:28:07.716Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.AssertionError
[2024-05-31T03:28:07.716Z] --------------------------------------------------
[2024-05-31T03:39:06.249Z] Test results: passed: 656; failed: 1
[2024-05-31T03:39:12.677Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_17171234894383/jdk_util_0/report/html/report.html
[2024-05-31T03:39:12.677Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_17171234894383/jdk_util_0/work
[2024-05-31T03:39:12.677Z] Error: Some tests failed or other problems occurred.
[2024-05-31T03:39:12.677Z] -----------------------------------
[2024-05-31T03:39:12.677Z] jdk_util_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41052/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/339

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/348

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_OMR_testList_1/205

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_OMR_testList_1/306
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/564/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/576
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8_testList_2/51
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8_testList_2/51

**Comment by pshipton** [comment]
I wonder if this is related to https://github.com/eclipse-openj9/openj9/issues/10169

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_sanity.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/1234/)
```
[2026-04-11T02:11:02.369Z] Running test jdk_util_other_0 ...
[2026-04-11T02:11:02.369Z] ===============================================
[2026-04-11T02:11:02.369Z] jdk_util_other_0 Start Time: Fri Apr 10 19:09:25 2026 Epoch Time (ms): 1775873365439
[2026-04-11T02:11:02.369Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2026-04-11T02:11:02.369Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2026-04-11T02:14:13.313Z] TEST: java/util/logging/FileHandlerAccessTest.java

[2026-04-11T02:14:13.313Z] java.lang.AssertionError
[2026-04-11T02:14:13.313Z] 	at sun.nio.ch.SharedFileLockTable.removeKeyIfEmpty(FileLockTable.java:167)
[2026-04-11T02:14:13.313Z] 	at sun.nio.ch.SharedFileLockTable.removeAll(FileLockTable.java:222)
[2026-04-11T02:14:13.313Z] 	at sun.nio.ch.FileChannelImpl.implCloseChannel(FileChannelImpl.java:119)
[2026-04-11T02:14:13.313Z] 	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
[2026-04-11T02:14:13.313Z] 	at java.util.logging.FileHandler.close(FileHandler.java:751)
[2026-04-11T02:14:13.313Z] 	at FileHandlerAccessTest.access(FileHandlerAccessTest.java:50)
[2026-04-11T02:14:13.313Z] 	at java.lang.Thread.run(Thread.java:823)
[2026-04-11T02:14:13.313Z] STATUS:Failed.`main' threw exception: java.lang.AssertionError
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly_testList_2/573
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/600
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/802
