### ISSUE TITLE
JDK8 Mac testvmcheck_0_FAILED - FAILED: testLoadingClasses AssertionError: Child exited with non-zero stats expected:<0> but was:<1>

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13233]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Release/6/tapResults/
```
10:03:46  openjdk version "1.8.0_302-internal"
10:03:46  OpenJDK Runtime Environment (build 1.8.0_302-internal-****_2021_07_21_10_44-b00)
10:03:46  Eclipse OpenJ9 VM (build openj9-0.27.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210721_8 (JIT enabled, AOT enabled)
10:03:46  OpenJ9   - 1851b0074f8
10:03:46  OMR      - 9db1c870dfb
10:03:46  JCL      - 96acb976bc8 based on jdk8u302-b08)
```
[Re-run in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Release&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK8_x86-64_mac_Release%2F8%2FOpenJ9-JDK8-x86-64_mac-20210721-104413.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK8_x86-64_mac_Release%2F8%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=ci-eclipse-openj9&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=v0.27.0-release&OPENJ9_SHA=1851b0074f87e20c0007c6190c745dab9760eabe&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.27.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=Dynamic)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test testvmcheck_0 ...
===============================================
testvmcheck_0 Start Time: Wed Jul 21 15:14:58 2021 Epoch Time (ms): 1626894898345
variation: NoOptions
JVM_OPTIONS:  

FAILED: testLoadingClasses
java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:205)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:115)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    testvmcheck
    Tests run: 1, Failures: 1, Skips: 0
===============================================

testvmcheck_0_FAILED
```
This is not seen in internal tests.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_mac_Nightly_testList_0/73 - osx1013-x86-3
testvmcheck_6 `-XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced`
```
[TestLoadingClassesFromJarfile] [WARN] /Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources are not end with .jar
FAILED: testLoadingClasses
java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:206)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:115)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:80)
```
