### ISSUE TITLE
Extended.openjdk jdk_other javax/rmi/ssl/SSLSocketParametersTest failed with NoSuchObjectException

### ISSUE THREAD

**Issue by LongyuZhang** [eclipse-openj9/openj9#13251]
Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows_testList_0/8/testReport/
Internal_Jenkins/job/Test_openjdk8_j9_extended.openjdk_ppc64_aix/20/testReport/
- test category: extended.openjdk
- test target name: jdk_other_0
- OS/architecture: aix, windows
- JDK version: 8

Failure output (captured from console output)
---------------------------------------------
```
12:39:44  Launching test for SSLSocketParametersTest
12:39:44  -------------------------------------------------------------
12:39:44  KeyStore = /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/openjdk/openjdk-jdk/jdk/test/javax/rmi/ssl/keystore
12:39:44  TrustStore = /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/openjdk/openjdk-jdk/jdk/test/javax/rmi/ssl/truststore
12:39:44  Running SSLSocketParametersTest [1]
12:39:44  ServerFactory::Calling createServerSocket(0)
12:39:44  Inside HelloImpl::runServer
12:39:44  Stub = Proxy[SSLSocketParametersTest$Hello,RemoteObjectInvocationHandler[UnicastRef2 [liveRef: [endpoint:[9.114.84.50:39163,SSLSocketParametersTest$ServerFactory@20e67cd5,SSLSocketParametersTest$ClientFactory@5814339d](local),objID:[-3e00731f:17ac9efe833:-7fff, -1146024531321967598]]]]]
12:39:44  Inside HelloClient::runClient
12:39:44  ClientFactory::Calling createSocket(9.114.84.50,39163)
12:39:44  SSLSocketParametersTest [1] FAILED! Exception: java.rmi.NoSuchObjectException: no such object in table
12:39:44  java.rmi.NoSuchObjectException: no such object in table
12:39:44  	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
12:39:44  	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
12:39:44  	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
12:39:44  	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
12:39:44  	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
12:39:44  	at com.sun.proxy.$Proxy0.sayHello(Unknown Source)
12:39:44  	at SSLSocketParametersTest$HelloClient.runClient(SSLSocketParametersTest.java:75)
12:39:44  	at SSLSocketParametersTest.runTest(SSLSocketParametersTest.java:137)
12:39:44  	at SSLSocketParametersTest.main(SSLSocketParametersTest.java:286)
```

Optional info
-------------
- passed for hotspot: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_extended.openjdk_ppc64_aix_testList_0/6/testReport/javax_rmi_ssl_SSLSocketParametersTest/

**Comment by pshipton** [comment]
I think this is a dup of https://github.com/eclipse-openj9/openj9/issues/12168#issuecomment-877455441 and a problem with the test case.

**Comment by LongyuZhang** [comment]
> I think this is a dup of [#12168 (comment)](https://github.com/eclipse-openj9/openj9/issues/12168#issuecomment-877455441) and a problem with the test case.

Yes, thanks for pointing out. Sorry I searched jdk_other but did not show that issue.
