### ISSUE TITLE
jtreg jdk_rmi java/rmi/registry/readTest/readTest.sh failure with ConnectException

### ISSUE THREAD

**Issue by LongyuZhang** [eclipse-openj9/openj9#13259]
Failure link
------------

Internal_Jenkins/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/15/testReport/java_rmi_registry_readTest_readTest/sh/readTest/
- test category: extended.openjdk
- test target name: jdk_rmi
- OS/architecture: windows
- JDK version: 8

Failure output (captured from console output)
---------------------------------------------
```
21:17:55  Test output : 
21:17:55  Server exception: java.rmi.ConnectException: Connection refused to host: 9.30.223.99; nested exception is: 
21:17:55  	java.net.ConnectException: Connection refused: connect
21:17:55  java.rmi.ConnectException: Connection refused to host: 9.30.223.99; nested exception is: 
21:17:55  	java.net.ConnectException: Connection refused: connect
21:17:55  	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
21:17:55  	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
21:17:55  	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
21:17:55  	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
21:17:55  	at sun.rmi.registry.RegistryImpl_Stub.bind(RegistryImpl_Stub.java:65)
21:17:55  	at readTest.main(readTest.java:38)
21:17:55  Caused by: java.net.ConnectException: Connection refused: connect
21:17:55  	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
21:17:55  	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
21:17:55  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
21:17:55  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
21:17:55  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
21:17:55  	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
21:17:55  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
21:17:55  	at java.net.Socket.connect(Socket.java:607)
21:17:55  	at java.net.Socket.connect(Socket.java:556)
21:17:55  	at java.net.Socket.<init>(Socket.java:452)
21:17:55  	at java.net.Socket.<init>(Socket.java:229)
21:17:55  	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
21:17:55  	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
21:17:55  	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
21:17:55  	... 5 more
21:17:55  ==============
21:17:55  rmiregistry output  : 
21:17:55  ==============
21:17:55  Failed
21:17:55  STDERR:
21:17:55  C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\rmi\registry\readTest\readTest.sh: line 58: [: 3.1.6(0.340/5/3): integer expression expected
21:17:55  C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\rmi\registry\readTest\readTest.sh: line 103: 22933 Killed                  ${TESTJAVA}${FS}bin${FS}rmiregistry ${REGARGS} -J-Djava.rmi.server.useCodebaseOnly=false ${TESTTOOLVMOPTS} 60005 > ..${FS}${RMIREG_OUT} 2>&1  (wd: /cygdrive/c/Users/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_windows/aqa-tests/TKG/output_16270814942878/jdk_rmi_0/work/java/rmi/registry/readTest/readTest/rmi_tmp)
21:17:55  C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\rmi\registry\readTest\readTest.sh: line 103: 22939 Killed                  ${TESTJAVA}${FS}bin${FS}java ${TESTVMOPTS} -cp $TEST_CLASSPATH ${ARGS} -Djava.rmi.server.codebase=${FILEURL}$CODEBASE/ readTest > OUT.TXT 2>&1
```

Optional info
-------------
- passed for hotspot: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_0/12/testReport/java_rmi_registry_readTest_readTest/

**Comment by LongyuZhang** [comment]
Similar failure for jdk_rmi sun/rmi/transport/tcp/DeadCachedConnection.java
```
21:23:37  java.rmi.ConnectException: Connection refused to host: 9.30.223.99; nested exception is: 
21:23:37  	java.net.ConnectException: Connection refused: connect
21:23:37  	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
21:23:37  	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
21:23:37  	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
21:23:37  	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
21:23:37  	at sun.rmi.registry.RegistryImpl_Stub.list(RegistryImpl_Stub.java:90)
21:23:37  	at DeadCachedConnection.main(DeadCachedConnection.java:88)
21:23:37  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:23:37  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:23:37  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:23:37  	at java.lang.reflect.Method.invoke(Method.java:498)
21:23:37  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:23:37  	at java.lang.Thread.run(Thread.java:826)
21:23:37  Caused by: java.net.ConnectException: Connection refused: connect
21:23:37  	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
21:23:37  	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
21:23:37  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
21:23:37  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
21:23:37  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
21:23:37  	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
21:23:37  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
21:23:37  	at java.net.Socket.connect(Socket.java:607)
21:23:37  	at java.net.Socket.connect(Socket.java:556)
21:23:37  	at java.net.Socket.<init>(Socket.java:452)
21:23:37  	at java.net.Socket.<init>(Socket.java:229)
21:23:37  	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
21:23:37  	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
21:23:37  	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
21:23:37  	... 11 more
21:23:37  
21:23:37  JavaTest Message: Test threw exception: java.rmi.ConnectException: Connection refused to host: 9.30.223.99; nested exception is: 
21:23:37  	java.net.ConnectException: Connection refused: connect
```

**Comment by LongyuZhang** [comment]
Similar failure for jdk 11 aix with jdk_rmi java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.java
```
TEST FAILED: 
Test failed with: Connection refused to host: 9.42.124.20; nested exception is: 
	java.net.ConnectException: A remote host refused an attempted connect operation. (Connection refused)
java.rmi.ConnectException: Connection refused to host: 9.42.124.20; nested exception is: 
	java.net.ConnectException: A remote host refused an attempted connect operation. (Connection refused)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
	at EchoImpl_Stub.echoNot(EchoImpl_Stub.java:56)
	at UseCustomSocketFactory.main(UseCustomSocketFactory.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: java.net.ConnectException: A remote host refused an attempted connect operation. (Connection refused)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/java.net.Socket.<init>(Socket.java:454)
	at java.base/java.net.Socket.<init>(Socket.java:231)
	at MultiSocketFactory$CompressSocket.<init>(MultiSocketFactory.java:102)
	at MultiSocketFactory$ClientFactory.createSocket(MultiSocketFactory.java:84)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
	... 11 more
```
