### ISSUE TITLE
Segmentation Fault when  'shareROMClasses' option is enabled on ppc64le

### ISSUE THREAD

**Issue by EmanElsaban** [eclipse-openj9/openj9#13275]
Similar to issue: #13210. The server crashes when enabling the ``shareROMClasses`` option on build 2021-07-28 JRE image, java 8 on power machine (ppc64le).

```
root@cit926:/home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin# ./jitserver '-Xjit:verbose={compilePerformance|JITserver},shareROMClasses'
JITServer is currently a technology preview. Its use is not yet supported.
#JITServer: JITServer version: 1.26.0
#JITServer: JITServer Server Mode. Port: 38400. Connection Timeout 30000ms
#JITServer: Built against (OpenSSL 1.0.2k-fips  26 Jan 2017); Loaded with (OpenSSL 1.1.1  11 Sep 2018)

#INFO:  _______________________________________
#INFO:  Version Information:
#INFO:       JIT Level  - j9jit_20210728_1518_jenkins
#INFO:       JVM Level  - 20210728_167
#INFO:       GC Level   - 1851b0074
#INFO:
#INFO:  Processor Information:
#INFO:       Platform Info:PPCp8
#INFO:       Supports HardwareSQRT:1
#INFO:       Supports HardwareRound:1
#INFO:       Supports HardwareCopySign:1
#INFO:       Supports FPU:1
#INFO:       Supports DFP:1
#INFO:       Supports VMX:1
#INFO:       Supports VSX:1
#INFO:       Supports AES:1
#INFO:       Supports  TM:1
#INFO:       Vendor:Unknown
#INFO:       numProc=192
#INFO:
#INFO:  _______________________________________
#INFO:  AOT
#INFO:  options specified:
#INFO:       samplingFrequency=2
#INFO:
#INFO:  options in effect:
#INFO:       samplingFrequency=2
#INFO:       shareROMClasses
#INFO:       verbose={options|compilePerformance|JITServer}

#INFO:       compressedRefs shiftAmount=0
#INFO:  _______________________________________
#INFO:  JIT
#INFO:  options specified:
#INFO:       verbose={compilePerformance|JITserver},shareROMClasses
#INFO:
#INFO:  options in effect:
#INFO:       samplingFrequency=2
#INFO:       shareROMClasses
#INFO:       verbose={options|compilePerformance|JITServer}

#INFO:       compressedRefs shiftAmount=0
#JITServer: Started JITServer listener thread: 000000000017E400

JITServer is ready to accept incoming requests
#JITServer: Server received request for stream 000020012B990020
#JITServer: Server allocated data for a new clientUID 10216649330784115467
#JITServer: compThreadID=0 created clientSessionData=000020012BDC0010 for clientUID=10216649330784115467 seqNo=1 (isCritical=1) (criticalSeqNo=0 lastProcessedCriticalReq=0)
#JITServer: compThreadID=0 will ask for address ranges of unloaded classes and CHTable for clientUID 10216649330784115467
#JITServer: compThreadID=0 will initialize CHTable for clientUID 10216649330784115467 size=2352
#0: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0xab34c0) [0x200001d534c0]
#1: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0xac465c) [0x200001d6465c]
#2: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x17a8b0) [0x20000141a8b0]
#3: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so(+0x3c560) [0x200000a4c560]
#4: function __kernel_sigtramp_rt64+0 [0x2000000604d8]
#5: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9thr29.so(+0x55a4) [0x200000ae55a4]
#6: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x33dc8c) [0x2000015ddc8c]
#7: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x5a2b0c) [0x200001842b0c]
#8: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x5a2ee4) [0x200001842ee4]
#9: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x20ff00) [0x2000014aff00]
#10: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x21847c) [0x2000014b847c]
#11: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x2cad0c) [0x20000156ad0c]
#12: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x588a30) [0x200001828a30]
#13: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x159e90) [0x2000013f9e90]
#14: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x195d64) [0x200001435d64]
#15: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so(+0x3d708) [0x200000a4d708]
#16: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x191afc) [0x200001431afc]
#17: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x203ee0) [0x2000014a3ee0]
#18: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x190724) [0x200001430724]
#19: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x190e70) [0x200001430e70]
#20: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x190f78) [0x200001430f78]
#21: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so(+0x3d708) [0x200000a4d708]
#22: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so(+0x19156c) [0x20000143156c]
#23: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9thr29.so(+0x113e8) [0x200000af13e8]
#24: /lib/powerpc64le-linux-gnu/libpthread.so.0(+0x885c) [0x2000000d885c]
#25: function clone+0x98 [0x200000278d58]
Unhandled exception
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00002000007F39E0 Handler2=0000200000A4C300
R0=0000000000000060 R1=0000200012A59640 R2=0000200000B17E00 R3=0000000000000000
R4=0000000000000000 R5=0000000000000000 R6=0000200014009BC0 R7=0000000000000000
R8=000020012B630078 R9=0000000000000000 R10=0000000000000000 R11=000000000000013F
R12=00002000000DE620 R13=0000200012A668E0 R14=0000000000000000 R15=0000200012A5BA30
R16=0000000000000001 R17=0000000000000000 R18=0000200012A6D170 R19=0000200012A5A7D8
R20=0000200014008D70 R21=0000000000000000 R22=0000200012A59C00 R23=0000200012A59CF0
R24=0000200012A59CD0 R25=0000000000000020 R26=000001003C881D70 R27=000001003C881DA0
R28=000020012B6300B8 R29=0000000000000000 R30=000020012B630038 R31=000001003C881900
NIP=0000200000AE55A4 MSR=900000010280F033 ORIG_GPR3=0000200000AE56BC CTR=00002000000DE620
LINK=0000200000AE5498 XER=0000000020000000 CCR=0000000024422882 SOFTE=0000000000000001
TRAP=0000000000000300 DAR=0000000000000008 dsisr=0000000040000000 RESULT=0000000000000000
FPR0 9b05688c510e527f (f: 1359893120.000000, d: -1.650960e-178)
FPR1 4008000000000000 (f: 0.000000, d: 3.000000e+00)
FPR2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR5 7fffffff7fffffff (f: 2147483648.000000, d: nan)
FPR6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR10 7ff0000000000000 (f: 0.000000, d: inf)
FPR11 00000000000ec300 (f: 967424.000000, d: 4.779710e-318)
FPR12 bb67ae856a09e667 (f: 1779033728.000000, d: -1.567125e-22)
FPR13 00002000011693d0 (f: 18256848.000000, d: 1.738340e-310)
FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9thr29.so
Module_base_address=0000200000AE0000

Unhandled exception in signal handler. Protected function: writeCrashDataToConsole (0x0)

----------- Stack Backtrace -----------
(0x0000200000AE55A4 [libj9thr29.so+0x55a4])
(0x00002000015DDC8C [libj9jit29.so+0x33dc8c])
(0x0000200001842B0C [libj9jit29.so+0x5a2b0c])
(0x0000200001842EE4 [libj9jit29.so+0x5a2ee4])
(0x00002000014AFF00 [libj9jit29.so+0x20ff00])
(0x00002000014B847C [libj9jit29.so+0x21847c])
(0x000020000156AD0C [libj9jit29.so+0x2cad0c])
(0x0000200001828A30 [libj9jit29.so+0x588a30])
(0x00002000013F9E90 [libj9jit29.so+0x159e90])
(0x0000200001435D64 [libj9jit29.so+0x195d64])
(0x0000200000A4D708 [libj9prt29.so+0x3d708])
(0x0000200001431AFC [libj9jit29.so+0x191afc])
(0x00002000014A3EE0 [libj9jit29.so+0x203ee0])
(0x0000200001430724 [libj9jit29.so+0x190724])
(0x0000200001430E70 [libj9jit29.so+0x190e70])
(0x0000200001430F78 [libj9jit29.so+0x190f78])
(0x0000200000A4D708 [libj9prt29.so+0x3d708])
(0x000020000143156C [libj9jit29.so+0x19156c])
(0x0000200000AF13E8 [libj9thr29.so+0x113e8])
(0x00002000000D885C [libpthread.so.0+0x885c])
clone+0x98 (0x0000200000278D58 [libc.so.6+0x158d58])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2021/08/04 16:32:59 - please wait.
JVMDUMP032I JVM requested System dump using '/home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/core.20210804.163259.95888.0001.dmp' in response to an event
#JITServer: Server received request for stream 000020012B998240
#JITServer: compThreadID=1 found clientSessionData=000020012BDC0010 for clientUID=10216649330784115467 seqNo=2 (isCritical=1) (criticalSeqNo=1 lastProcessedCriticalReq=1)
#JITServer: compThreadID=1 will process a list of 3 classes with illegal final field modification for clientUID 10216649330784115467
#JITServer: Server received request for stream 00002000028D5C30
#JITServer: compThreadID=2 found clientSessionData=000020012BDC0010 for clientUID=10216649330784115467 seqNo=3 (isCritical=0) (criticalSeqNo=2 lastProcessedCriticalReq=1)
#JITServer: compThreadID=2 out-of-sequence msg=3 detected for clientUID=10216649330784115467 criticalSeqNo=2 > lastCriticalSeqNo=1. Parking this thread (entry=0000200134007FB0)
#JITServer: compThreadID=2 (entry=0000200134007FB0) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: Server received request for stream 00002000028D5CD8
#JITServer: compThreadID=3 found clientSessionData=000020012BDC0010 for clientUID=10216649330784115467 seqNo=4 (isCritical=0) (criticalSeqNo=2 lastProcessedCriticalReq=1)
#JITServer: compThreadID=3 out-of-sequence msg=4 detected for clientUID=10216649330784115467 criticalSeqNo=2 > lastCriticalSeqNo=1. Parking this thread (entry=0000200134008120)
#JITServer: compThreadID=3 (entry=0000200134008120) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: Server received request for stream 00002000028D5D80
#JITServer: Server received request for stream 00002000028D5E28
#JITServer: compThreadID=5 found clientSessionData=000020012BDC0010 for clientUID=10216649330784115467 seqNo=5 (isCritical=0) (criticalSeqNo=2 lastProcessedCriticalReq=1)
#JITServer: compThreadID=5 out-of-sequence msg=5 detected for clientUID=10216649330784115467 criticalSeqNo=2 > lastCriticalSeqNo=1. Parking this thread (entry=0000200134008400)
#JITServer: compThreadID=5 (entry=0000200134008400) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: compThreadID=4 found clientSessionData=000020012BDC0010 for clientUID=10216649330784115467 seqNo=6 (isCritical=0) (criticalSeqNo=2 lastProcessedCriticalReq=1)
#JITServer: compThreadID=4 out-of-sequence msg=6 detected for clientUID=10216649330784115467 criticalSeqNo=2 > lastCriticalSeqNo=1. Parking this thread (entry=0000200134008290)
#JITServer: compThreadID=4 (entry=0000200134008290) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: Server received request for stream 00002000028D5ED0
#JITServer: compThreadID=6 found clientSessionData=000020012BDC0010 for clientUID=10216649330784115467 seqNo=7 (isCritical=0) (criticalSeqNo=2 lastProcessedCriticalReq=1)
#JITServer: compThreadID=6 out-of-sequence msg=7 detected for clientUID=10216649330784115467 criticalSeqNo=2 > lastCriticalSeqNo=1. Parking this thread (entry=0000200134008570)
#JITServer: compThreadID=6 (entry=0000200134008570) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: compThreadID=2 (entry=0000200134007FB0) timed-out while waiting for seqNo=2
#JITServer: compThreadID=2 which previously timed-out will go to sleep again. Possible reasons numActiveThreads=2 waitToBeNotified=0
#JITServer: compThreadID=2 (entry=0000200134007FB0) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: compThreadID=3 (entry=0000200134008120) timed-out while waiting for seqNo=2
#JITServer: compThreadID=3 which previously timed-out will go to sleep again. Possible reasons numActiveThreads=2 waitToBeNotified=0
#JITServer: compThreadID=3 (entry=0000200134008120) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: compThreadID=5 (entry=0000200134008400) timed-out while waiting for seqNo=2
#JITServer: compThreadID=4 (entry=0000200134008290) timed-out while waiting for seqNo=2
#JITServer: compThreadID=5 which previously timed-out will go to sleep again. Possible reasons numActiveThreads=2 waitToBeNotified=0
#JITServer: compThreadID=4 which previously timed-out will go to sleep again. Possible reasons numActiveThreads=2 waitToBeNotified=0
#JITServer: compThreadID=5 (entry=0000200134008400) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: compThreadID=4 (entry=0000200134008290) doing a timed wait for 1000 ms (waiting for seqNo=2)
#JITServer: compThreadID=6 (entry=0000200134008570) timed-out while waiting for seqNo=2
#JITServer: compThreadID=6 which previously timed-out will go to sleep again. Possible reasons numActiveThreads=2 waitToBeNotified=0
#JITServer: compThreadID=6 (entry=0000200134008570) doing a timed wait for 1000 ms (waiting for seqNo=2)
JVMDUMP010I System dump written to /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/core.20210804.163259.95888.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/javacore.20210804.163259.95888.0002.txt' in response to an event
JVMDUMP012E Error in Java dump: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/javacore.20210804.163259.95888.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/Snap.20210804.163259.95888.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/Snap.20210804.163259.95888.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/jitdump.20210804.163259.95888.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'JIT Compilation Thread-000' thread 0x0000000000015100
JVMDUMP049I JIT dump notified all waiting threads of the current method to be compiled
JVMDUMP012E Error in JIT dump: Could not locate the compilation object
JVMDUMP012E Error in JIT dump: /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/jitdump.20210804.163259.95888.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".
```

**Comment by EmanElsaban** [comment]
stack:
```
root@cit926:/home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin# gdb $JAVA_BIN/jitserver core.20210804.163259.95888.0001.dmp
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc64le-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/bin/jitserver...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 96167]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/powerpc64le-linux-gnu/libthread_db.so.1".
Core was generated by `./jitserver -Xjit:verbose={compilePerformance|JITserver},shareROMClasses '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00002000000e4894 in __pthread_kill (threadid=<optimized out>, signo=<optimized out>) at ../sysdeps/unix/sysv/linux/pthread_kill.c:55
55      ../sysdeps/unix/sysv/linux/pthread_kill.c: No such file or directory.
(gdb)
(gdb) bt
#0  0x00002000000e4894 in __pthread_kill (threadid=<optimized out>, signo=<optimized out>) at ../sysdeps/unix/sysv/linux/pthread_kill.c:55
#1  0x0000200000a49e80 in omrdump_create () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so
#2  0x00002000010dc234 in doSystemDump () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9dmp29.so
#3  0x00002000010d4f80 in protectedDumpFunction () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9dmp29.so
#4  0x0000200000a4d708 in omrsig_protect () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so
#5  0x00002000010db180 in runDumpFunction () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9dmp29.so
#6  0x00002000010db380 in runDumpAgent () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9dmp29.so
#7  0x00002000010fdf3c in triggerDumpAgents () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9dmp29.so
#8  0x00002000007f3794 in generateDiagnosticFiles () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9vm29.so
#9  0x0000200000a4d708 in omrsig_protect () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so
#10 0x00002000007f3b94 in structuredSignalHandler () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9vm29.so
#11 0x0000200000a4c560 in mainSynchSignalHandler () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so
#12 <signal handler called>
#13 0x0000200000ae55a4 in monitor_enter_three_tier.constprop () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9thr29.so
#14 0x00002000015ddc8c in J9::Monitor::enter() () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#15 0x0000200001842b0c in JITServerSharedROMClassCache::Partition::getOrCreate(J9ROMClass const*, JITServerROMClassHash const&) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#16 0x0000200001842ee4 in JITServerSharedROMClassCache::getOrCreate(J9ROMClass const*) () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#17 0x00002000014aff00 in JITServerHelpers::romClassFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, TR_PersistentMemory*) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#18 0x00002000014b847c in JITServerHelpers::getAndCacheRAMClassInfo(J9Class*, ClientSessionData*, JITServer::ServerStream*, JITServerHelpers::ClassInfoDataType, void*) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#19 0x000020000156ad0c in TR_J9ServerVM::getComponentClassFromArrayClass(TR_OpaqueClassBlock*) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#20 0x0000200001828a30 in TR::SymbolValidationManager::SymbolValidationManager(TR::Region&, TR_ResolvedMethod*) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#21 0x00002000013f9e90 in J9::Compilation::Compilation(int, J9VMThread*, TR_FrontEnd*, TR_ResolvedMethod*, TR::IlGenRequest&, TR::Options&, TR::Region&, TR_Memory*, TR_OptimizationPlan*, TR_RelocationRuntime*, TR::Environment*) () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#22 0x0000200001435d64 in TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#23 0x0000200000a4d708 in omrsig_protect () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so
#24 0x0000200001431afc in TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR_MethodToBeCompiled*, J9::J9SegmentProvider&) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#25 0x00002000014a3ee0 in TR::CompilationInfoPerThreadRemote::processEntry(TR_MethodToBeCompiled&, J9::J9SegmentProvider&) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#26 0x0000200001430724 in TR::CompilationInfoPerThread::processEntries() () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#27 0x0000200001430e70 in TR::CompilationInfoPerThread::run() () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#28 0x0000200001430f78 in protectedCompilationThreadProc(J9PortLibrary*, TR::CompilationInfoPerThread*) ()
   from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#29 0x0000200000a4d708 in omrsig_protect () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9prt29.so
---Type <return> to continue, or q <return> to quit---
#30 0x000020000143156c in compilationThreadProc(void*) () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9jit29.so
#31 0x0000200000af13e8 in thread_wrapper () from /home/user1/eelsabban/jitserver-dockerfiles/j2sdk-image/lib/ppc64le/default/libj9thr29.so
#32 0x00002000000d885c in start_thread (arg=0x0) at pthread_create.c:463
#33 0x0000200000278d58 in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:82
(gdb)
```

**Comment by EmanElsaban** [comment]
Will wait until next nightly image since this nightly image contains the source from 
```
SOURCE="OpenJDK:de702c3174 OpenJ9:1851b0074 OMR:9db1c870d"
```

**Comment by mpirvu** [comment]
Does the build that crashed include PR #13216 ?

**Comment by EmanElsaban** [comment]
No, I closed it for this reason until I try the nightly image that contains this pr.
