### ISSUE TITLE
Jtreg jdk_net MulticastSocket multiple tests failure for JDK16 windows

### ISSUE THREAD

**Issue by LongyuZhang** [eclipse-openj9/openj9#13309]
Failure link
------------

Internal_Jenkins/job/Test_openjdk16_j9_extended.openjdk_x86-64_windows/16/testReport/

Failed tests:
java/net/MulticastSocket/IPMulticastIF.java
java/net/MulticastSocket/JoinLeave.java
java/net/MulticastSocket/NoSetNetworkInterface.java

- test category: extended.openjdk
- test target name: jdk_net
- OS/architecture: windows
- JDK version: 16
- Failed tests:

Failure output (captured from console output)
---------------------------------------------
java/net/MulticastSocket/IPMulticastIF.java
```
12:03:37  STDERR:
12:03:37  java.lang.Exception: failures: 8
12:03:37  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
12:03:37  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:03:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
12:03:37  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
12:03:37  	at java.base/java.lang.Thread.run(Thread.java:883)
12:03:37  --- testSetGetOptionUnbound nif=[name:eth1 (Red Hat VirtIO Ethernet Adapter #2)]
12:03:37  test IPMulticastIF.testSetGetOptionUnbound(localhost/127.0.0.1:0, java.net.NetworkInterface@6d38a305): failure
12:03:37  java.net.SocketException: Invalid argument: no further information
12:03:37  	at java.base/sun.nio.ch.Net.setInterface6(Native Method)
12:03:37  	at java.base/sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364)
12:03:37  	at java.base/sun.nio.ch.DatagramSocketAdaptor.setOption(DatagramSocketAdaptor.java:418)
12:03:37  	at java.base/java.net.DatagramSocket.setOption(DatagramSocket.java:995)
12:03:37  	at IPMulticastIF.testSetGetOptionUnbound(IPMulticastIF.java:115)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
12:03:37  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:03:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
12:03:37  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
12:03:37  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
12:03:37  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
12:03:37  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
12:03:37  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
12:03:37  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
12:03:37  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
12:03:37  	at org.testng.TestRunner.run(TestRunner.java:623)
12:03:37  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
12:03:37  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
12:03:37  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
12:03:37  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
12:03:37  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
12:03:37  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
12:03:37  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
12:03:37  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
12:03:37  	at org.testng.TestNG.run(TestNG.java:1018)
12:03:37  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
12:03:37  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:03:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
12:03:37  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
12:03:37  	at java.base/java.lang.Thread.run(Thread.java:883)
```

java/net/MulticastSocket/JoinLeave.java
```
12:03:37  STDERR:
12:03:37  java.io.UncheckedIOException: java.net.SocketException: Invalid argument: no further information
12:03:37  	at JoinLeave.joinLeave(JoinLeave.java:62)
12:03:37  	at JoinLeave.lambda$main$0(JoinLeave.java:51)
12:03:37  	at JoinLeave$$Lambda$93/0x000000001c43ec18.accept(Unknown Source)
12:03:37  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
12:03:37  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
12:03:37  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
12:03:37  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
12:03:37  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
12:03:37  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
12:03:37  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
12:03:37  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
12:03:37  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
12:03:37  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
12:03:37  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
12:03:37  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
12:03:37  	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
12:03:37  	at JoinLeave.main(JoinLeave.java:51)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:03:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
12:03:37  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:03:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
12:03:37  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
12:03:37  	at java.base/java.lang.Thread.run(Thread.java:883)
12:03:37  Caused by: java.net.SocketException: Invalid argument: no further information
12:03:37  	at java.base/sun.nio.ch.Net.setInterface6(Native Method)
12:03:37  	at java.base/sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364)
12:03:37  	at java.base/sun.nio.ch.DatagramSocketAdaptor.setOption(DatagramSocketAdaptor.java:418)
12:03:37  	at java.base/sun.nio.ch.DatagramSocketAdaptor.setNetworkInterface(DatagramSocketAdaptor.java:600)
12:03:37  	at java.base/java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:466)
12:03:37  	at JoinLeave.joinLeave(JoinLeave.java:58)
12:03:37  	... 22 more
12:03:37  
12:03:37  JavaTest Message: Test threw exception: java.io.UncheckedIOException
12:03:37  JavaTest Message: shutting down test
```

java/net/MulticastSocket/NoSetNetworkInterface.java
```
12:03:44  STDERR:
12:03:44  java.io.UncheckedIOException: java.net.SocketException: Invalid argument: no further information
12:03:44  	at NoSetNetworkInterface.checkSetInterface(NoSetNetworkInterface.java:74)
12:03:44  	at NoSetNetworkInterface.lambda$main$0(NoSetNetworkInterface.java:55)
12:03:44  	at NoSetNetworkInterface$$Lambda$18/0x00000000b0c54b40.accept(Unknown Source)
12:03:44  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
12:03:44  	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
12:03:44  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$115/0x0000000000000000.accept(Unknown Source)
12:03:44  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
12:03:44  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
12:03:44  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
12:03:44  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
12:03:44  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
12:03:44  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
12:03:44  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
12:03:44  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
12:03:44  	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:739)
12:03:44  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
12:03:44  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
12:03:44  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
12:03:44  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
12:03:44  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
12:03:44  	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
12:03:44  	at NoSetNetworkInterface.main(NoSetNetworkInterface.java:54)
12:03:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:03:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
12:03:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:03:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
12:03:44  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:03:44  	at java.base/java.lang.Thread.run(Thread.java:883)
12:03:44  Caused by: java.net.SocketException: Invalid argument: no further information
12:03:44  	at java.base/sun.nio.ch.Net.setInterface6(Native Method)
12:03:44  	at java.base/sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364)
12:03:44  	at java.base/sun.nio.ch.DatagramSocketAdaptor.setOption(DatagramSocketAdaptor.java:418)
12:03:44  	at java.base/sun.nio.ch.DatagramSocketAdaptor.setNetworkInterface(DatagramSocketAdaptor.java:600)
12:03:44  	at java.base/sun.nio.ch.DatagramSocketAdaptor.setInterface(DatagramSocketAdaptor.java:565)
12:03:44  	at java.base/java.net.MulticastSocket.setInterface(MulticastSocket.java:431)
12:03:44  	at NoSetNetworkInterface.checkSetInterface(NoSetNetworkInterface.java:70)
12:03:44  	... 27 more
12:03:44  
12:03:44  JavaTest Message: Test threw exception: java.io.UncheckedIOException: java.net.SocketException: Invalid argument: no further information
12:03:44  JavaTest Message: shutting down test
```

Optional info
-------------
Passed for hotspot: 
- IPMulticastIF: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk16_j9_extended.openjdk_x86-64_windows_testList_1/7/testReport/java_net_MulticastSocket_IPMulticastIF/
- JoinLeave: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk16_j9_extended.openjdk_x86-64_windows_testList_1/7/testReport/java_net_MulticastSocket_JoinLeave/
- NoSetNetworkInterface: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk16_j9_extended.openjdk_x86-64_windows_testList_1/7/testReport/java_net_MulticastSocket_NoSetNetworkInterface/

**Comment by LongyuZhang** [comment]
NoSetNetworkInterface and IPMulticastIF failures are also mentioned in https://github.com/eclipse-openj9/openj9/issues/12082 for JDK17
