### ISSUE TITLE
JDK16 StackWalkerTest_1_FAILED - NullPointerException: Cannot invoke "java.lang.Class.getName()" because "instanceClass" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13319]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.functional_ppc64_aix_Nightly_testList_1/70/consoleFull
```
23:56:14  openjdk version "16.0.2-internal" 2021-07-20
23:56:14  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16ppc64aixNightly)
23:56:14  Eclipse OpenJ9 VM (build master-2156b546d1c, JRE 16 AIX ppc64-64-Bit Compressed References 20210811_71 (JIT enabled, AOT enabled)
23:56:14  OpenJ9   - 2156b546d1c
23:56:14  OMR      - ac3ab4821a5
23:56:14  JCL      - ee030f1f047 based on jdk-16.0.2+7)
```
To rebuild the failed tests in <Jenkins URL>=https://openj9-jenkins.osuosl.org/job/Grinder, use the following links:
01:21:00  https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=StackWalkerTest_1

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
00:27:52  ===============================================
00:27:52  Running test StackWalkerTest_1 ...
00:27:52  ===============================================
00:27:52  StackWalkerTest_1 Start Time: Thu Aug 12 00:27:51 2021 Epoch Time (ms): 1628742471923
00:27:52  "/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_ppc64_aix_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_ppc64_aix_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
00:27:52  JVMSHRC005I No shared class caches available
00:27:52  JVMSHRC005I No shared class caches available
00:27:52  cache cleanup done
00:27:52  variation: -Xjit:count=0
00:27:52  JVM_OPTIONS:  -Xjit:count=0 

00:28:15  FAILED: testSanity
00:28:15  java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "instanceClass" is null
00:28:15  	at java.base/java.lang.ClassCastException.<init>(ClassCastException.java:71)
00:28:15  	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberName(DirectMethodHandle.java:330)
00:28:15  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
00:28:15  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
00:28:15  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH)
00:28:15  	at org.openj9.test.stackWalker.StackWalkerTest.getFullMethodNameFromElement(StackWalkerTest.java:308)
00:28:15  	at org.openj9.test.stackWalker.StackWalkerTest.sanityTest(StackWalkerTest.java:107)
00:28:15  	at org.openj9.test.stackWalker.StackWalkerTest.testSanity(StackWalkerTest.java:58)
00:28:15  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:28:15  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
00:28:15  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:28:15  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
00:28:15  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
00:28:15  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
00:28:15  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
00:28:15  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
00:28:15  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:28:15  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
00:28:15  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
00:28:15  	at org.testng.TestRunner.run(TestRunner.java:505)
00:28:15  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
00:28:15  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
00:28:15  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
00:28:15  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
00:28:15  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:28:15  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
00:28:15  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
00:28:15  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
00:28:15  	at org.testng.TestNG.runSuites(TestNG.java:1049)
00:28:15  	at org.testng.TestNG.run(TestNG.java:1017)
00:28:15  	at org.testng.TestNG.privateMain(TestNG.java:1354)
00:28:15  	at org.testng.TestNG.main(TestNG.java:1323)
00:28:15  
00:28:15  
00:28:15  ===============================================
00:28:15      StackWalkerTest
00:28:15      Tests run: 14, Failures: 1, Skips: 0
00:28:15  ===============================================
```

This might be related some other NPE issues such as https://github.com/eclipse-openj9/openj9/issues/13164, https://github.com/eclipse-openj9/openj9/issues/13129.

**Comment by JasonFengJ9** [comment]
A few similar NPEs at https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_special.system_ppc64_aix_Personal/14/tapResults/
```
===============================================
Running test MathLoadTest_all_special_5m_14 ...
===============================================
MathLoadTest_all_special_5m_14 Start Time: Tue Aug 17 09:28:21 2021 Epoch Time (ms): 1629206901809
variation: Mode553
JVM_OPTIONS:  -XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:count=0 

openjdk version "16.0.2-internal" 2021-07-20
OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16ppc64aixPersonal)
Eclipse OpenJ9 VM (build master-df51c203a8b, JRE 16 AIX ppc64-64-Bit Compressed References 20210817_24 (JIT enabled, AOT enabled)
OpenJ9   - df51c203a8b
OMR      - ac3ab4821a5
JCL      - 44316ee515b based on jdk-16.0.2+7)

MLT 09:29:02.229 - Failed to initialise LoadTest
MLT java.lang.NullPointerException: null
MLT 	at java.lang.ClassCastException.<init>(ClassCastException.java:71) ~[?:?]
MLT 	at java.lang.invoke.DirectMethodHandle.internalMemberName(DirectMethodHandle.java:330) ~[?:?]
MLT 	at java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH) ~[?:?]
MLT 	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH) ~[?:?]
MLT 	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH) ~[?:?]
MLT 	at net.adoptopenjdk.stf.environment.DirectoryRef.childFile(DirectoryRef.java:112) ~[bin/:?]
MLT 	at net.adoptopenjdk.loadTest.InventoryData.readInventoryFile(InventoryData.java:135) ~[bin/:?]
MLT 	at net.adoptopenjdk.loadTest.InventoryData.<init>(InventoryData.java:96) ~[bin/:?]
MLT 	at net.adoptopenjdk.loadTest.LoadTest.createSuite(LoadTest.java:478) ~[bin/:?]
MLT 	at net.adoptopenjdk.loadTest.LoadTest.<init>(LoadTest.java:329) ~[bin/:?]
MLT 	at net.adoptopenjdk.loadTest.LoadTest.main(LoadTest.java:106) [bin/:?]
STF 09:29:03.210 - **FAILED** Process MLT ended with exit code (2) and not the expected exit code/s (0)

MathLoadTest_all_special_5m_14_FAILED
```

**Comment by JasonFengJ9** [comment]
A few similar NPEs w/ a recent JDK17 (`openj9-staging`) at Test_openjdk17_j9_special.system_s390x_linux_Personal/3/tapResults/
```
18:12:42  openjdk version "17-internal" 2021-09-14
18:12:42  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17s390xlinuxPersonal)
18:12:42  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 17 Linux s390x-64-Bit Compressed References 20210818_5 (JIT enabled, AOT enabled)
18:12:42  OpenJ9   - cd8db74f1d4
18:12:42  OMR      - ac3ab4821a5
18:12:42  JCL      - b40e984c3a1 based on jdk-17+35)

===============================================
Running test DaaLoadTest_daa1_special_5m_14 ...
===============================================
DaaLoadTest_daa1_special_5m_14 Start Time: Wed Aug 18 15:36:51 2021 Epoch Time (ms): 1629326211828
variation: Mode553
JVM_OPTIONS:  -XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:count=0 

DLT 15:37:21.893 - Failed to initialise LoadTest
DLT java.lang.NullPointerException: null
DLT 	at java.lang.invoke.DirectMethodHandle.internalMemberName(DirectMethodHandle.java:329) ~[?:?]
DLT 	at java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH) ~[?:?]
DLT 	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH) ~[?:?]
DLT 	at java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH) ~[?:?]
DLT 	at net.adoptopenjdk.stf.environment.DirectoryRef.childFile(DirectoryRef.java:112) ~[bin/:?]
DLT 	at net.adoptopenjdk.loadTest.InventoryData.readInventoryFile(InventoryData.java:135) ~[bin/:?]
DLT 	at net.adoptopenjdk.loadTest.InventoryData.<init>(InventoryData.java:96) ~[bin/:?]
DLT 	at net.adoptopenjdk.loadTest.LoadTest.createSuite(LoadTest.java:478) ~[bin/:?]
DLT 	at net.adoptopenjdk.loadTest.LoadTest.<init>(LoadTest.java:329) ~[bin/:?]
DLT 	at net.adoptopenjdk.loadTest.LoadTest.main(LoadTest.java:106) [bin/:?]
STF 15:37:22.857 - **FAILED** Process DLT ended with exit code (2) and not the expected exit code/s (0)

DaaLoadTest_daa1_special_5m_14_FAILED
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=system&PLATFORM=s390x_linux&TARGET=DaaLoadTest_daa1_special_5m_14)

**Comment by fengxue-IS** [comment]
**StackWalkerTest_1**: 20/20 passed on ppc_aix `Test_grinder/job/Grinder/17981/`
**DaaLoadTest_daa1_special_5m_14**: 20/20 passed on s390_linux `Test_grinder/job/Grinder/17962/`

failure not observed on latest JDK 17. 
Closing issue, reopen if failure seen again in testing
