### ISSUE TITLE
AArch64: Test failures with java/lang/ProcessHandle/InfoTest.java

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#13329]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Personal/2/

Failure output (captured from console output)
---------------------------------------------

```
[2021-08-17T01:28:02.433Z]  info: [user: Optional[jenkins], cmd: /usr/bin/coreutils, args: [--coreutils-prog-shebang=sleep, /bin/sleep, 240], startTime: Optional[2021-08-17T01:27:50.880Z], totalTime: Optional[PT0S]]
[2021-08-17T01:28:02.433Z] destroyProcessTree destroyForcibly
[2021-08-17T01:28:02.433Z] pid 203404, alive: true; parent: Optional[201176], [user: Optional[jenkins], cmd: /usr/bin/coreutils, args: [--coreutils-prog-shebang=sleep, /bin/sleep, 240], startTime: Optional[2021-08-17T01:27:50.880Z], totalTime: Optional[PT0S]]
[2021-08-17T01:28:02.433Z] test InfoTest.test3(): failure
[2021-08-17T01:28:02.433Z] java.lang.AssertionError: Command: expected: 'sleep', actual: /usr/bin/coreutils expected [true] but found [false]
[2021-08-17T01:28:02.433Z] 	at org.testng.Assert.fail(Assert.java:94)
[2021-08-17T01:28:02.433Z] 	at org.testng.Assert.failNotEquals(Assert.java:496)
[2021-08-17T01:28:02.433Z] 	at org.testng.Assert.assertTrue(Assert.java:42)
[2021-08-17T01:28:02.433Z] 	at InfoTest.test3(InfoTest.java:302)
[2021-08-17T01:28:02.433Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by knn-k** [comment]
I believe this is an infrastructural issue.
The testcase expects the name of the process to be "sleep", but it is "/usr/bin/coreutils" on cent8-aarch64-1.

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/9f1a72e0b3a675ae703fd578dfb1a42d0efa85b1/test/jdk/java/lang/ProcessHandle/InfoTest.java#L301

fyi.  @rajdeepsingh1

**Comment by jdekonin** [comment]
I've installed reinstalled coreutils as a different version was installed with docker.

Respin of entire job
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Personal/3/console

**Comment by jdekonin** [comment]
100% success now.
