### ISSUE TITLE
JDK17 - java.lang.ClassNotFoundException: java.rmi.activation.Activatable

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13325]
Failure link
------------

From an internal grinder build `Test_openjdk17_j9_special.system_x86-64_linux_Personal/2/tapResults/`
```
08:38:12  openjdk version "17-internal" 2021-09-14
08:38:12  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
08:38:12  Eclipse OpenJ9 VM (build master-5b7c2720b5b, JRE 17 Linux amd64-64-Bit Compressed References 20210812_40 (JIT enabled, AOT enabled)
08:38:12  OpenJ9   - 5b7c2720b5b
08:38:12  OMR      - ac3ab4821a5
08:38:12  JCL      - b40e984c3a1 based on jdk-17+35)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test ClassLoadingTest_special_5m_0 ...
===============================================
ClassLoadingTest_special_5m_0 Start Time: Thu Aug 12 10:11:55 2021 Epoch Time (ms): 1628788315998
variation: Mode101
JVM_OPTIONS:  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs 

CLT Loaded Class: java.rmi.AccessException
CLT Test failed:
CLT java.lang.ClassNotFoundException: Failed to find Class: java.rmi.activation.Activatablejava.lang.ClassNotFoundException: java.rmi.activation.Activatable
CLT 	at net.adoptopenjdk.test.classloading.ClassHog.run(ClassHog.java:80)
CLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
CLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
CLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
CLT 	at java.base/java.lang.Thread.run(Thread.java:883)
CLT <<<
CLT 
CLT 10:12:02.384 - Test failed. Details recorded in execution log.
CLT 10:12:02.386 - Number of test failures has reached 'AbortAtFailureLimit' (10). Terminating load test

STF 10:12:02.674 - =====================   R E S U L T S   =====================
STF 10:12:02.674 - Stage results:
STF 10:12:02.674 -   setUp:     pass
STF 10:12:02.674 -   execute:  *fail*
STF 10:12:02.674 -   teardown:  pass
STF 10:12:02.674 - 
STF 10:12:02.674 - Overall result: **FAILED**

ClassLoadingTest_special_5m_0_FAILED
```

This is because JDK17 removed `java.rmi.activation.Activatable`. The test has to be modified for JDK17+.
Considering the number of failures due to this exception (and might block other runs after early exit), I am adding it to 0.28 release.

fyi @llxia

**Comment by llxia** [comment]
@Mesbah-Alam could you take a look? Thanks

**Comment by pshipton** [comment]
Set as a blocker, it's failing consistently in every build so needs to be fixed (or excluded).

**Comment by Mesbah-Alam** [comment]
This should resolve the issue : https://github.com/adoptium/aqa-systemtest/pull/452.

**Comment by pshipton** [comment]
I think it's working, I'll go ahead and close.
