### ISSUE TITLE
JDK16 AIX testFailure: net.openj9.test.arithmetics.TestValidityChecking: Storage is not completely initialized, 30 bytes left

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13358]
Failure link
------------

From an internal build `Test_openjdk16_j9_special.system_ppc64_aix_Personal/5/tapResults/` (`paix826`):
```
22:17:52  openjdk version "16.0.2-internal" 2021-07-20
22:17:52  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16ppc64aixPersonal)
22:17:52  Eclipse OpenJ9 VM (build master-2ba48511f18, JRE 16 AIX ppc64-64-Bit Compressed References 20210822_37 (JIT enabled, AOT enabled)
22:17:52  OpenJ9   - 2ba48511f18
22:17:52  OMR      - 6eec759cd2d
22:17:52  JCL      - 44316ee515b based on jdk-16.0.2+7)
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=system&PLATFORM=ppc64_aix&TARGET=DaaLoadTest_daa1_special_5m_14)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:30:04  ===============================================
22:30:04  Running test DaaLoadTest_daa1_special_5m_14 ...
22:30:04  ===============================================
22:30:04  DaaLoadTest_daa1_special_5m_14 Start Time: Sun Aug 22 22:43:52 2021 Epoch Time (ms): 1629690232980
22:30:04  "/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64_aix_Personal_testList_4/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64_aix_Personal_testList_4/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
22:30:04  JVMSHRC005I No shared class caches available
22:30:04  JVMSHRC005I No shared class caches available
22:30:04  cache cleanup done
22:30:04  variation: Mode553
22:30:04  JVM_OPTIONS:  -XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:count=0 

22:30:50  DLT 21:44:38.123 - Thread completed. Suite=0 thread=11
22:30:50  DLT 21:44:38.295 - Test failed
22:30:50  DLT   Failure num.  = 1
22:30:50  DLT   Test number   = 9
22:30:50  DLT   Test details  = 'JUnit[net.openj9.test.arithmetics.TestValidityChecking]'
22:30:50  DLT   Suite number  = 0
22:30:50  DLT   Thread number = 2
22:30:50  DLT >>> Captured test output >>>
22:30:50  DLT testStarted : testOverwriteEvenNibble(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testFinished: testOverwriteEvenNibble(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testStarted : testIgnoreEvenNibble(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testFinished: testIgnoreEvenNibble(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testStarted : testInvalidDigitsAndSignDigit(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testFinished: testInvalidDigitsAndSignDigit(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testStarted : testCheckPackedWithOffset(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testFinished: testCheckPackedWithOffset(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testStarted : testOptions(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testFinished: testOptions(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testStarted : testCheckPackedDecimalDifferentSignValues(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testFinished: testCheckPackedDecimalDifferentSignValues(net.openj9.test.arithmetics.TestValidityChecking)
22:30:50  DLT testFailure: net.openj9.test.arithmetics.TestValidityChecking: Storage is not completely initialized, 30 bytes left
22:30:50  DLT java.lang.InternalError: Storage is not completely initialized, 30 bytes left
22:30:50  DLT 	at java.base/java.lang.StringConcatHelper.newString(StringConcatHelper.java:391)
22:30:50  DLT 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
22:30:50  DLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
22:30:50  DLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
22:30:50  DLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH)
22:30:50  DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor$1.addResult(JUnitAdaptor.java:120)
22:30:50  DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor$1.testFinished(JUnitAdaptor.java:80)
22:30:50  DLT 	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
22:30:50  DLT 	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
22:30:50  DLT 	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
22:30:50  DLT 	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
22:30:50  DLT 	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
22:30:50  DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
22:30:50  DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
22:30:50  DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
22:30:50  DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
22:30:50  DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
22:30:50  DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
22:30:50  DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
22:30:50  DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
22:30:50  DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
22:30:50  DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
22:30:50  DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
22:30:50  DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
22:30:50  DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
22:30:50  DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
22:30:50  DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
22:30:50  DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
22:30:50  DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
22:30:50  DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
22:30:50  DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
22:30:50  DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
22:30:50  DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
22:30:50  DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
22:30:50  DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
22:30:50  DLT 	at java.base/java.lang.Thread.run(Thread.java:883)
22:30:50  DLT 
22:30:50  DLT JUnit Test Results for: net.openj9.test.arithmetics.TestValidityChecking
22:30:50  DLT   Ran    : 6
22:30:50  DLT   Passed : 5
22:30:50  DLT   Failed : 1
22:30:50  DLT   Ignored: 0
22:30:50  DLT   Result : FAILED
22:30:50  DLT <<<
22:30:50  DLT 
22:30:50  DLT 21:44:38.369 - Thread completed. Suite=0 thread=2
22:30:53  DLT 21:44:41.229 - Thread completed. Suite=0 thread=6
22:30:53  DLT 21:44:41.232 - Thread completed. Suite=0 thread=12
22:30:53  DLT 21:44:41.244 - Thread completed. Suite=0 thread=1
22:30:53  DLT 21:44:41.893 - Test failed. Details recorded in execution log.
22:30:53  DLT 21:44:41.893 - Thread completed. Suite=0 thread=8
22:30:53  DLT 21:44:41.895 - Load test completed
22:30:53  DLT 21:44:41.895 -   Ran     : 27
22:30:53  DLT 21:44:41.895 -   Passed  : 9
22:30:53  DLT 21:44:41.895 -   Failed  : 18
22:30:53  DLT 21:44:41.896 -   Result  : FAILED
22:30:53  DLT 21:44:41.896 - Note that only the first 1 failures have been reported
22:30:53  STF 22:44:42.347 - **FAILED** Process DLT ended with exit code (1) and not the expected exit code/s (0)
22:30:55  STF 22:44:42.347 - Monitoring Report Summary:
22:30:55  STF 22:44:42.347 -   o Process DLT ended with exit code (1) and not the expected exit code/s (0)
22:30:55  STF 22:44:42.347 - Killing processes: DLT
22:30:55  STF 22:44:42.347 -   o Process DLT pid 20709720 is not running
22:30:55  **FAILED** at step 1 (Run daa load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64_aix_Personal_testList_4/aqa-tests/TKG/../TKG/output_16296898618770/DaaLoadTest_daa1_special_5m_14/20210822-224353-DaaLoadTest/execute.pl line 95.
22:30:55  STF 22:44:42.811 - **FAILED** execute script failed. Expected return value=0 Actual=1
22:30:55  STF 22:44:42.811 - 
22:30:55  STF 22:44:42.811 - ====================   T E A R D O W N   ====================
22:30:55  STF 22:44:42.811 - Running teardown: perl /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64_aix_Personal_testList_4/aqa-tests/TKG/../TKG/output_16296898618770/DaaLoadTest_daa1_special_5m_14/20210822-224353-DaaLoadTest/tearDown.pl
22:30:55  STF 22:44:42.900 - TEARDOWN stage completed
22:30:55  STF 22:44:42.910 - 
22:30:55  STF 22:44:42.910 - =====================   R E S U L T S   =====================
22:30:55  STF 22:44:42.910 - Stage results:
22:30:55  STF 22:44:42.910 -   setUp:     pass
22:30:55  STF 22:44:42.910 -   execute:  *fail*
22:30:55  STF 22:44:42.910 -   teardown:  pass
22:30:55  STF 22:44:42.910 - 
22:30:55  STF 22:44:42.910 - Overall result: **FAILED**
22:30:55  
22:30:55  DaaLoadTest_daa1_special_5m_14_FAILED
```

**Comment by JasonFengJ9** [comment]
Not observed in recent JDK17 runs.

Closing. (can re-open if it occurs again)
