### ISSUE TITLE
JDK17 jdk_util_1_FAILED - java/util/Random/RandomTestMoments.java 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13370]
Failure link
------------

From an internal build `Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/7/consoleFull`:
```
13:38:10  openjdk version "17-internal" 2021-09-14
13:38:10  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17s390xlinuxPersonal)
13:38:10  Eclipse OpenJ9 VM (build master-5d2495e99a7, JRE 17 Linux s390x-64-Bit Compressed References 20210823_10 (JIT enabled, AOT enabled)
13:38:10  OpenJ9   - 5d2495e99a7
13:38:10  OMR      - 6eec759cd2d
13:38:10  JCL      - b40e984c3a1 based on jdk-17+35)
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=openjdk&PLATFORM=s390x_linux&TARGET=jdk_util_1)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:36:25  ===============================================
15:36:25  Running test jdk_util_1 ...
15:36:25  ===============================================
15:36:25  jdk_util_1 Start Time: Mon Aug 23 12:36:24 2021 Epoch Time (ms): 1629747385000
15:36:25  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
15:36:25  JVMSHRC005I No shared class caches available
15:36:25  JVMSHRC005I No shared class caches available
15:36:25  cache cleanup done
15:36:25  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
15:36:25  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

15:47:34  --------------------------------------------------
15:47:34  TEST: java/util/Random/RandomTestMoments.java

15:47:34  STDERR:
15:47:34  SecureRandom
15:47:34    Gaussian fail: actual=46.069144, expected=38.298500, basis=38.298500, tolerance=0.200000
15:47:34  java.lang.RuntimeException: 1 fails detected
15:47:34  	at RandomTestMoments.exceptionOnFail(RandomTestMoments.java:56)
15:47:34  	at RandomTestMoments.main(RandomTestMoments.java:202)
15:47:34  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:47:34  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
15:47:34  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:47:34  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
15:47:34  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
15:47:34  	at java.base/java.lang.Thread.run(Thread.java:883)
15:47:34  
15:47:34  JavaTest Message: Test threw exception: java.lang.RuntimeException
15:47:34  JavaTest Message: shutting down test
15:47:34  
15:47:34  
15:47:34  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 1 fails detected
15:47:34  --------------------------------------------------
15:56:42  Test results: passed: 885; failed: 1
15:56:42  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/jvmtest/openjdk/report/html/report.html
15:56:42  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/aqa-tests/TKG/output_16297412204292/jdk_util_1/work
15:56:42  Error: Some tests failed or other problems occurred.
15:56:42  
15:56:42  jdk_util_1_FAILED
15:56:42  
```

**Comment by 0xdaryl** [comment]
@fjeremic : could you assign for triage on Z please?

**Comment by fjeremic** [comment]
```
12:28:30  STDERR:
12:28:30  java.lang.RuntimeException: japanese_roll.cts:443: Unexpected exception
12:28:30  	at CalendarTestEngine.run(CalendarTestEngine.java:99)
12:28:30  	at CalendarTestEngine.main(CalendarTestEngine.java:52)
12:28:30  	at JapaneseTests.main(JapaneseTests.java:81)
12:28:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:28:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
12:28:30  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:28:30  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
12:28:30  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:28:30  	at java.base/java.lang.Thread.run(Thread.java:878)
12:28:30  Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -1
12:28:30  	at java.base/java.util.JapaneseImperialCalendar.actualMonthLength(JapaneseImperialCalendar.java:2243)
12:28:30  	at java.base/java.util.JapaneseImperialCalendar.roll(JapaneseImperialCalendar.java:860)
12:28:30  	at CalendarAdapter.roll(CalendarAdapter.java:100)
12:28:30  	at CalendarTestEngine.run(CalendarTestEngine.java:362)
12:28:30  	... 8 more
12:28:30  
```

Looks like we have different exceptions here. But failures none the less. @VermaSh could you take a look at this one?

**Comment by fjeremic** [comment]
Any progress on this one?

**Comment by VermaSh** [comment]
I am just getting to it. I'll post an update in next few days.

**Comment by 0xdaryl** [comment]
Tagging with the JIT component so this shows up on the JIT list.

**Comment by VermaSh** [comment]
I haven't been able to reproduce the failure locally. Have launched a grinder https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/18189/ to get a log and failure rate. Hoping to use the log from a failure run to help reproduce it locally.

**Comment by VermaSh** [comment]
Launched another grinder https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/18211/ as previous grinder didn't have any failures

**Comment by 0xdaryl** [comment]
Looks like 1 failure in your last set of grinders.  Not sure if that is a manifestation of the original problem or an infra issue.  If infra, can you launch one final set of at least 30 so that we can make a final determination on whether to keep this open or not please?

**Comment by VermaSh** [comment]
Last grinder had test failures in`BasicCancelTest.java.BasicCancelTest` and `ZeroCoreThreads.java.ZeroCoreThreads`. Both of which seem to be due to infra issues. Here's another grinder of 50 iterations https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/18249/

**Comment by VermaSh** [comment]
No failures on z14 and z15 either. So far all 150 iterations of `jdk_util_1` have passed. I think we can close this issue.

**Comment by pshipton** [comment]
> I think we can close this issue.

@JasonFengJ9 I'll leave this to you.

**Comment by JasonFengJ9** [comment]
The grinder https://github.com/eclipse-openj9/openj9/issues/13370#issuecomment-923098111 was run w/ an aged build [1]. Earlier grinder results have been purged so not sure what JDKs were used.
Started another grinder w/ a recent `0.28` release build at `view/Test_grinder/job/Grinder/18319/`

On the other hand, the failure reported initially wasn't observed in recent JDK17 runs.
Will close this issue if no such failure in the grinder above.

[1] https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_s390x_linux_OpenJDK17/13/OpenJ9-JDK17-s390x_linux-20210823-125259.tar.gz

**Comment by JasonFengJ9** [comment]
There were two failures from the grinder run https://github.com/eclipse-openj9/openj9/issues/13370#issuecomment-924914526
`job/Grinder_testList_0/437/consoleFull`
```
15:42:08  STDERR:
15:42:08  java.lang.BootstrapMethodError: bootstrap method initialization exception
15:42:08  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
15:42:08  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
15:42:08  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
15:42:08  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
15:42:08  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:194)
15:42:08  	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:199)
15:42:08  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
15:42:08  	at org.testng.TestRunner$$Lambda$100/0x0000000000000000.accept(Unknown Source)
15:42:08  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
15:42:08  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
15:42:08  	at org.testng.TestRunner.run(TestRunner.java:585)
15:42:08  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
15:42:08  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
15:42:08  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
15:42:08  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
15:42:08  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
15:42:08  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
15:42:08  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
15:42:08  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
15:42:08  	at org.testng.TestNG.runSuites(TestNG.java:1069)
15:42:08  	at org.testng.TestNG.run(TestNG.java:1037)
15:42:08  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
15:42:08  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
15:42:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:42:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
15:42:08  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:42:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
15:42:08  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:42:08  	at java.base/java.lang.Thread.run(Thread.java:884)
15:42:08  Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandleImpl$IntrinsicMethodHandle.<init>(java.lang.invoke.MethodHandle, java.lang.invoke.MethodHandleImpl$Intrinsic)"
15:42:08  	at java.base/java.lang.invoke.MethodHandleImpl.makeIntrinsic(MethodHandleImpl.java:1310)
15:42:08  	at java.base/java.lang.invoke.MethodHandles.makeIdentity(MethodHandles.java:5105)
15:42:08  	at java.base/java.lang.invoke.MethodHandles.identity(MethodHandles.java:5052)
15:42:08  	at java.base/java.lang.invoke.MethodHandles.constant(MethodHandles.java:5030)
15:42:08  	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:262)
15:42:08  	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:341)
15:42:08  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
15:42:08  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invokeExact_MT(LambdaForm$MH)
15:42:08  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
15:42:08  	... 28 more
15:42:08  
15:42:08  JavaTest Message: Test threw exception: java.lang.BootstrapMethodError: bootstrap method initialization exception
15:42:08  JavaTest Message: shutting down test
15:42:08  
15:42:08  STATUS:Failed.`main' threw exception: java.lang.BootstrapMethodError: bootstrap method initialization exception
```
This is a known issue https://github.com/eclipse-openj9/openj9/issues/13162

```
Cancelling nested steps due to timeout
20:10:48  Sending interrupt signal to process
20:11:02  --------------------------------------------------
20:11:02  TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/FindFirstOpTest.java
20:11:02  TEST JDK: /home/jenkins/workspace/Grinder_testList_0/openjdkbinary/j2sdk-image

20:11:02  TEST RESULT: Failed. Unexpected exit from test [exit code: 143]
20:11:02  --------------------------------------------------
20:11:02  
20:11:02  jdk_util_1_FAILED
```
This appears another manifestation of https://github.com/eclipse-openj9/openj9/issues/13488

No failure initially reported in this issue was observed.
Closing.
