### ISSUE TITLE
J9 failed to throw IncompatibleClassChangeError on JDK 1.8.0

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#13433]
### Summary of problem
Given the same test program, J9 behaves inconsistently between J9(1.8.0_282-b08),  J9(11.0.11) and J9(16.0.2). The simplified test program can be found in the attachment. In particular,  J9(11.0.11) and J9(16.0.2) throw IncompatibleClassChangeError, while J9(1.8.0_282-b08) executes normally. 

### How to reproduce?
[Test.zip](https://github.com/eclipse-openj9/openj9/files/7099150/Test.zip)
Follow the commands in readme.

### Affected versions

Windows 10:
```
Microsoft Windows 10
10.0.19042 N/A Build 19042
Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
Memory 8.00 GB 
```

Java -version output under Windows 10
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
Eclipse OpenJ9 VM (build openj9-0.24.0, JRE 1.8.0 Windows 8.1 amd64-64-Bit 20210120_560 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08)
```

**Comment by ChengJin01** [comment]
Looking at the bytecode of the test above:
```
public class Test implements A  <-------
  minor version: 0
  major version: 52
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #27                         // Test
  super_class: #20                        // java/lang/Object
  interfaces: 1, fields: 0, methods: 2, attributes: 1
Constant pool:
   #1 = String             #22            // Failure
   #2 = Methodref          #9.#19         // A.get:()Ljava/lang/String;  <------------

interface A
  minor version: 0
  major version: 52
  flags: (0x0600) ACC_INTERFACE, ACC_ABSTRACT
  this_class: #2                          // A
  super_class: #3                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 1, attributes: 1
Constant pool:
   #1 = String             #10            // Hello from A.get()
   #2 = Class              #11            // A
   #3 = Class              #12            // java/lang/Object
   #4 = Utf8               get
   #5 = Utf8               ()Ljava/lang/String;
   #6 = Utf8               Code
   #7 = Utf8               LineNumberTable
   #8 = Utf8               SourceFile
   #9 = Utf8               Test.java
  #10 = Utf8               Hello from A.get()
  #11 = Utf8               A
  #12 = Utf8               java/lang/Object
{
  public static java.lang.String get();  <----------------
    descriptor: ()Ljava/lang/String;
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: ldc           #1                  // String Hello from A.get()
         2: areturn
      LineNumberTable:
        line 9: 0
}
```
against on Java8, 11, 16 (OpenJ9 & Hotspot) as follows:
[1] **OpenJ9**
```
$ jdk8_openj9_nightly/bin/java  -cp  .  Test
Failure
$ 
$ jdk11_openj9_nightly/bin/java  -cp  .  Test
Exception in thread "main" java.lang.IncompatibleClassChangeError
	at Test.main(Test.jasm)

$ jdk16_openj9_nightly/bin/java  -cp  .  Test
Exception in thread "main" java.lang.IncompatibleClassChangeError
	at Test.main(Test.jasm)
```
[2] **Hotspot**
$ /jdk1.8.0_271_hotspot/bin/java  -cp  .  Test
Failure

$ jdk11.0.9_hotspot/bin/java  -cp  .  Test
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
Method A.get()Ljava/lang/String; must be InterfaceMethodref constant
	at Test.main(Test.jasm)

$ jdk16_hotspot/bin/java  -cp  .  Test
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
Method 'java.lang.String A.get()' must be InterfaceMethodref constant
	at Test.main(Test.jasm)
```
which means OpenJ9 does things correctly to match the RI's behaviour on Java 8, 11 & 16 so as to only capture the error with `A.get()` (it should be `InterfaceMethodref` in the constant pool rather than `Methodref`) on Java 11 & 16.

I will double-check the code to see whether there is any restriction on Java 8 to avoid capturing such error against the VM Spec.

**Comment by ChengJin01** [comment]
Hi @JavaTailor,  please contact Oracle to see whether it is reasonable/required to capture the error on Java 8 against the VM Spec given OpenJ9 ends up with the same test results as Hotspot in which case I don't think there is anything abnormal at this point.

**Comment by ChengJin01** [comment]
Debugging shows the error was captured in resolveStaticMethodRefInto on Java 11 as follows
```
[Switching to Thread 0x7ffff7d45700 (LWP 246985)]
Thread 2 "main" hit Breakpoint 1, resolveStaticMethodRefInto (vmStruct=0x16700, ramCP=0x1837c0, cpIndex=2, resolveFlags=32, ramCPEntry=0x167f8)
    at resolvesupport.cpp:534
534							goto incompat;
(gdb) list
529					if (isResolvedClassAnInterface) {
530						if ((J9CPTYPE_INTERFACE_STATIC_METHOD != cpType)
531						&& (J9CPTYPE_INTERFACE_INSTANCE_METHOD != cpType)
532						&& (J9CPTYPE_INTERFACE_METHOD != cpType)
533						) {
534							goto incompat; <--------
535						}
536					} else {
537						if ((J9CPTYPE_INTERFACE_STATIC_METHOD == cpType)
538						|| (J9CPTYPE_INTERFACE_INSTANCE_METHOD == cpType)
(gdb) bt
#0  resolveStaticMethodRefInto (vmStruct=0x16700, ramCP=0x1837c0, cpIndex=2, resolveFlags=32, ramCPEntry=0x167f8) at resolvesupport.cpp:534
#1  0x00007ffff73b1999 in resolveStaticMethodRef (vmStruct=0x16700, ramCP=0x1837c0, cpIndex=2, resolveFlags=32) at resolvesupport.cpp:642
#2  0x00007ffff72940c4 in VM_BytecodeInterpreterCompressed::initialStaticMethod (this=0x7ffff7d44760, _sp=@0x7ffff7d446d0: 0x10c6d0, 
    _pc=@0x7ffff7d446d8: 0x1 <error: Cannot access memory at address 0x1>) at BytecodeInterpreter.hpp:1935
#3  0x00007ffff72a890b in VM_BytecodeInterpreterCompressed::run (this=0x7ffff7d44760, vmThread=0x16700) at BytecodeInterpreter.hpp:9722
#4  0x00007ffff7286135 in bytecodeLoopCompressed (currentThread=0x16700) at BytecodeInterpreter.inc:112
#5  0x00007ffff73d2072 in c_cInterpreter () at xcinterp.s:158
#6  0x00007ffff734f8c0 in runCallInMethod (env=0x16700, receiver=0x0, clazz=0x10c750, methodID=0x7ffff021d308, args=0x7ffff7d44d48) at callin.cpp:1123
#7  0x00007ffff7379858 in gpProtectedRunCallInMethod (entryArg=0x7ffff7d44ce0) at jnicsup.cpp:300
#8  0x00007ffff73e35d2 in signalProtectAndRunGlue (portLibrary=0x7ffff7541e80 <j9portLibrary>, userData=0x7ffff7d44c90) at jniprotect.c:45
#9  0x00007ffff708bdac in omrsig_protect (portLibrary=0x7ffff7541e80 <j9portLibrary>, fn=0x7ffff73e35a2 <signalProtectAndRunGlue>, fn_arg=0x7ffff7d44c90, 
    handler=0x7ffff7371e0c <structuredSignalHandler>, handler_arg=0x16700, flags=506, result=0x7ffff7d44c78) at ../../omr/port/unix/omrsignal.c:425
#10 0x00007ffff73e373b in gpProtectAndRun (function=0x7ffff73797f7 <gpProtectedRunCallInMethod(void*)>, env=0x16700, args=0x7ffff7d44ce0) at jniprotect.c:78
#11 0x00007ffff7379dff in gpCheckCallin (env=0x16700, receiver=0x0, cls=0x10c750, methodID=0x7ffff021d308, args=0x7ffff7d44d48) at jnicsup.cpp:488
#12 0x00007ffff7378b4c in callStaticVoidMethod (env=0x16700, cls=0x10c750, methodID=0x7ffff021d308) at jnicgen.c:384
#13 0x00007ffff7fb8016 in JavaMain (_args=0x7fffffffab50)
    at /home/jincheng/X86_64_OPENJ9/Triage_check/openj9-openjdk-jdk11/src/java.base/share/native/libjli/java.c:549
#14 0x00007ffff7fbf1cb in ThreadJavaMain (args=0x7fffffffab50)
    at /home/jincheng/X86_64_OPENJ9/Triage_check/openj9-openjdk-jdk11/src/java.base/unix/native/libjli/java_md_solinux.c:759
#15 0x00007ffff7d6f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007ffff7ecd293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
against the code involved is in resolveStaticMethodRefInto at /runtime/vm/resolvesupport.cpp
```
J9Method *   
resolveStaticMethodRefInto(J9VMThread *vmStruct, J9ConstantPool *ramCP, UDATA cpIndex, UDATA resolveFlags, J9RAMStaticMethodRef *ramCPEntry)
{
...
		if (J2SE_VERSION(vmStruct->javaVM) >= J2SE_V11) { <--------
			/* This check is only required in Java9 and there have been applications that
			 * fail when this check is enabled on Java8.
			 */
			if ((cpClass != NULL) && (cpClass->romClass != NULL)) {
				UDATA cpType = J9_CP_TYPE(J9ROMCLASS_CPSHAPEDESCRIPTION(cpClass->romClass), cpIndex);
				if (isResolvedClassAnInterface) {
					if ((J9CPTYPE_INTERFACE_STATIC_METHOD != cpType)
					&& (J9CPTYPE_INTERFACE_INSTANCE_METHOD != cpType)
					&& (J9CPTYPE_INTERFACE_METHOD != cpType)
					) {
						goto incompat;
					}
```
So the code above (introduced via #1167 to support CFR_CONSTANT_Methodref and CFR_CONSTANT_InterfaceMethodref in the constantpool since Java 9) was disabled intentionally on Java 8 via #1752 to avoid breaking Java 8 applications for historical reasons and there is no plan to enable it for the moment.

FYI: @DanHeidinga

**Comment by DanHeidinga** [comment]
Cheng's analysis looks correct to me.  The JVM spec didn't change until later to require this behaviour so we shouldn't change it for Java 8 as that has been in production use for many years.

Closing as I believe openj9 has the correct behaviour here.
