### ISSUE TITLE
OpenJ9 core dump gathered with exclusive access shows J9DDRCorruptData inspecting class fields

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#13467]
Java -version output
--------------------

Not sure how to get the equivalent of `java -version` from `jdmpview` but the `context` reports:

```
*0 : PID: 21516 : JRE 1.8.0 Windows 10 amd64-64 (build 1.8.0_292-b10)
```

Summary of problem
------------------

Inspecting some class fields shows `J9DDRCorruptData`:

```
> x/j 0x6845409f8
         heap #1 - name: Generational@1b11705d8a0

          java/lang/Class @ 0x6845409f8
           declared fields:
            private transient long vmRef = 3498764144 (0xd08ae770)
            private transient ClassLoader classLoader = null
            private transient java.security.ProtectionDomain protectionDomain = Problem running command:
com.ibm.j9ddr.view.dtfj.image.J9DDRCorruptData incompatible with com.ibm.dtfj.java.JavaField
```

The dump is supposed to have been taken with `exclusive+prepwalk` although my technique of verifying that using `!findcallsite` on `dmpagent.c` allocations and casting the last one to `J9RASdumpAgent` no longer seems to work as that's pointing to a Snap agent which is wrong, so I'm not sure how to verify that.

The dump is in an exclusive access state:

```
> !j9javavm 0x1b11707d010 | grep exclusiveAccessState
        0x1ae0: U64 exclusiveAccessState = 0x0000000000000002 (2)
```

Diagnostic files
----------------

`S:\sf\TS006\232\TS006232802\2021-09-03\ojdk8_defaultServer.zip_unpack\defaultServer\core.20210903.095600.21516.0001.dmp`

**Comment by kgibm** [comment]
Running on a newer version of OpenJ9 `jdmpview` doesn't show the same error:

```
openjdk version "1.8.0_302"
IBM Semeru Runtime Open Edition (build 1.8.0_302-b08)
Eclipse OpenJ9 VM (build openj9-0.27.0, JRE 1.8.0 Windows Server 2016 amd64-64-Bit Compressed References 20210730_192 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - de702c3174 based on jdk8u302-b08)
```

`jdmpview`:

```
> x/j 0x6845409f8
         heap #1 - name: Generational@1b11705d8a0

          java/lang/Class @ 0x6845409f8
           declared fields:
            private transient long vmRef = 317440 (0x4d800)
            private transient ClassLoader classLoader = <object> @ 0x684573b80
            private transient java.security.ProtectionDomain protectionDomain = null
            private transient String classNameString = "java.lang.String" @ 0x68454ea58
            private transient String fileNameString = null
            private transient Class$AnnotationVars annotationVars = null
            transient ClassValue$ClassValueMap classValueMap = null
            private transient Class$EnumVars enumVars = null
            transient J9VMInternals$ClassInitializationLock initializationLock = null
            private transient Object methodHandleCache = null
            private transient Class$ClassRepositoryHolder classRepoHolder = <object> @ 0x6874ae7d8
            private transient Class$AnnotationCache annotationCache = <object> @ 0x687290c98
            private transient Class$MetadataCache metadataCache = null
            private transient Class[] cachedInterfaces = <object> @ 0x6874ae7e8
            private transient Class cachedDeclaringClass = <object> @ 0x6845dfab8
            private transient Class cachedEnclosingClass = <object> @ 0x6845dfab8
            private transient Class$ReflectCache reflectCache = <object> @ 0x686275288

            references:
              0x684573b80 0x68454ea58 0x6874ae7d8 0x687290c98 0x6874ae7e8 0x6845dfab8 0x6845dfab8 0x686275288 0x4d800
```

However, using the same `dtfj.jar` and `j9ddr.jar` patched in MAT still gives `J9DDRCorruptData`, so double checking the MAT code...

**Comment by kgibm** [comment]
Here's another issue running with the latest OpenJ9 `jdmpview` (also seen in MAT):

```
> x/j 0x684540db0
         heap #1 - name: Generational@1b11705d8a0

          [C @ 0x684540db0
           <cannot determine if above object is array (<corrupt data encountered>); we will assume it is not an array>

            references: <none>
```

Full details of the corrupt data exception from MAT:

```
com.ibm.j9ddr.view.dtfj.DTFJCorruptDataException: J9DDRCorruptData [as=minidump : 0 Message: Internal runtime exception was encountered]
        at com.ibm.j9ddr.view.dtfj.J9DDRDTFJUtils.handleAsCorruptDataException(J9DDRDTFJUtils.java:228)
        at com.ibm.j9ddr.vm29.view.dtfj.java.DTFJJavaObject.fetchDeferredData(DTFJJavaObject.java:610)
        at com.ibm.j9ddr.vm29.view.dtfj.java.DTFJJavaObject.getSize(DTFJJavaObject.java:577)
        at org.eclipse.mat.dtfj.DTFJIndexBuilder.getObjectSize(DTFJIndexBuilder.java:4775)
        at org.eclipse.mat.dtfj.DTFJIndexBuilder.processHeapObject(DTFJIndexBuilder.java:3627)
        at org.eclipse.mat.dtfj.DTFJIndexBuilder.fill(DTFJIndexBuilder.java:2143)
        at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.parse(SnapshotFactoryImpl.java:331)
        at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.openSnapshot(SnapshotFactoryImpl.java:202)
        at org.eclipse.mat.snapshot.SnapshotFactory.openSnapshot(SnapshotFactory.java:149)
        at org.eclipse.mat.ui.snapshot.ParseHeapDumpJob.run(ParseHeapDumpJob.java:97)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.j9ddr.InvalidDataTypeException: U64 contains value larger than Long.MAX_VALUE
        at com.ibm.j9ddr.vm29.types.U64.longValue(U64.java:115)
        at com.ibm.j9ddr.vm29.types.UDATA.mult(UDATA.java:233)
        at com.ibm.j9ddr.vm29.j9.gc.GCArrayletObjectModelBase.externalArrayletsSize(GCArrayletObjectModelBase.java:439)
        at com.ibm.j9ddr.vm29.j9.gc.GCArrayletObjectModel_V2.getTotalFootprintInBytesWithHeader(GCArrayletObjectModel_V2.java:66)
        at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.getTotalFootprintInBytesWithHeader(GCObjectModel_V1.java:176)
        at com.ibm.j9ddr.vm29.j9.ObjectModel.getTotalFootprintInBytesWithHeader(ObjectModel.java:205)
        at com.ibm.j9ddr.vm29.view.dtfj.java.DTFJJavaObject.fetchDeferredData(DTFJJavaObject.java:608)
        ... 9 more
```

**Comment by dmitripivkine** [comment]
I curious can this be related with changed object header for contiguous indexable object? Can it be place somewhere does not inherit new header format? There is no problem to read this object using `jdmpview`:
```
0x684540DB0 :  00049300 0000000e 84540dc0 00000006 [ ..........T..... ] <--- class(0x49300)/size(0xe)/pointer to data(0x684540DC0)
0x684540DC0 :  00690066 006c0065 00460064 006c0069 [ f.i.e.l.d.F.i.l. ]
0x684540DD0 :  00650074 004d0072 00700061 00000000 [ t.e.r.M.a.p..... ]

> !j9object 0x684540DB0
!J9IndexableObject 0x0000000684540DB0 {
    struct J9Class* clazz = !j9arrayclass 0x49300   // [C
    Object flags = 0x00000000;
    U_32 size = 0x0000000E;
	[0] =   102, 0x0066, 'f'
	[1] =   105, 0x0069, 'i'
	[2] =   101, 0x0065, 'e'
	[3] =   108, 0x006c, 'l'
	[4] =   100, 0x0064, 'd'
	[5] =    70, 0x0046, 'F'
	[6] =   105, 0x0069, 'i'
	[7] =   108, 0x006c, 'l'
	[8] =   116, 0x0074, 't'
	[9] =   101, 0x0065, 'e'
	[10] =   114, 0x0072, 'r'
	[11] =    77, 0x004d, 'M'
	[12] =    97, 0x0061, 'a'
	[13] =   112, 0x0070, 'p'
}
```

**Comment by dmitripivkine** [comment]
Ah, I see... gccheck seems experiencing the same problem:
```
Problem running command:
U64 contains value larger than Long.MAX_VALUE
```

**Comment by keithc-ca** [comment]
This is likely specific to Windows, where the compiler erases the distinction between `UDATA` and `U64`.
Generating a dump on Windows for `events=vmstart` exhibits the problem described here.
