### ISSUE TITLE
LambdaLoadTest_CS_5m_0_FAILED testLambdasWithMultipleThreads ArrayIndexOutOfBoundsException & Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13469]
Similar `LambdaLoadTest` failure is observed at JDK11 `Test_openjdk11_j9_sanity.system_aarch64_linux_testList_0/23/tapResults/`
```
===============================================
Running test LambdaLoadTest_CS_5m_0 ...
===============================================
LambdaLoadTest_CS_5m_0 Start Time: Tue Sep  7 02:10:14 2021 Epoch Time (ms): 1630980614887
variation: -Xgcpolicy:gencon -Xgc:concurrentScavenge
JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:concurrentScavenge 

openjdk version "11.0.13-ea" 2021-10-19
IBM Semeru Runtime Open Edition 11.0.12.0 (build 11.0.13-ea+3)
Eclipse OpenJ9 VM 11.0.12.0 (build master-b4f9d6e99, JRE 11 Linux aarch64-64-Bit Compressed References 20210907_195 (JIT enabled, AOT enabled)
OpenJ9   - b4f9d6e99
OMR      - f747fcbe3
JCL      - 1f7fcff07d based on jdk-11.0.13+3)

LT  02:10:20.670 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
LT  02:10:20.720 - suite.getInventory().getInventoryFileRef(): openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
LT  02:10:20.721 - suite.isCreateDump() : false
LT  02:10:20.721 - Test failed
LT    Failure num.  = 1
LT    Test number   = 8
LT    Test details  = 'JUnit[net.adoptopenjdk.test.lambda.TestLambdaMultithreaded]'
LT    Suite number  = 0
LT    Thread number = 2
LT  >>> Captured test output >>>
LT  testStarted : testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
LT  load-2 MT running with 25 threads
LT  testFailure: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded): null
LT  java.lang.ArrayIndexOutOfBoundsException
LT  	at java.base/java.util.Vector.add(Vector.java:814)
LT  	at java.base/java.util.Vector.addElement(Vector.java:648)
LT  	at java.base/java.util.Stack.push(Stack.java:67)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.lambda$new$0(TestLambdaMultithreaded.java:130)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded$$Lambda$83/0x0000000000000000.execute(Unknown Source)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.runNumberCounter(TestLambdaMultithreaded.java:397)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:236)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded$$Lambda$126/0x0000000000000000.run(Unknown Source)
LT  	at java.base/java.lang.Thread.run(Thread.java:866)
LT  testFinished: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
LT  
LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaMultithreaded
LT    Ran    : 1
LT    Passed : 0
LT    Failed : 1
LT    Ignored: 0
LT    Result : FAILED
LT  <<<
LT  
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=0000FFFF836DAF98 Handler2=0000FFFF83651660 InaccessibleAddress=00000000000000D8
LT  stderr java: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
LT  stderr R0=0000000000000000 R1=0000000000000001 R2=0000FFFF837035D8 R3=0000FFFF7C027930
LT  stderr R4=0000000000000004 R5=0000000000000008 R6=0000000000000000 R7=0000FFFEF1C775B0
LT  stderr R8=0000000000000281 R9=00000000F2C02100 R10=0000000000000001 R11=0000000000000000
LT  stderr R12=0000FFFF7C17CDA4 R13=0000FFFF7C17CDA8 R14=0000000000000001 R15=0000FFFEF1C774E0
LT  stderr R16=0000FFFF82F91F0C R17=0000FFFF83FACD80 R18=0000FFFF7C17CDC8 R19=0000FFFF83869188
LT  stderr R20=0000000000744FE0 R21=000000006ED12110 R22=0000FFFF83865000 R23=00000000F2C02100
LT  stderr R24=00000000F2C02110 R25=0000FFFF7C17CDC8 R26=00000000F2A7D718 R27=00000000000002FC
LT  stderr R28=0000000000657000 R29=0000FFFEF1C77230 R30=0000FFFF82F98CA4 R31=0000FFFEF1C77230
LT  stderr PC=0000FFFF83703668 SP=0000FFFEF1C77230 PSTATE=0000000020001000
LT  stderr V0 00000000000001d4 (f: 468.000000, d: 2.312227e-321)
LT  stderr V1 0000000000000001 (f: 1.000000, d: 4.940656e-324)
LT  stderr V2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V3 403280a4d5d61c98 (f: 3587579136.000000, d: 1.850252e+01)
LT  stderr V4 bfd00ea348b88334 (f: 1220051712.000000, d: -2.508934e-01)
LT  stderr V5 3fd5575b0be00b6a (f: 199232368.000000, d: 3.334568e-01)
LT  stderr V6 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
LT  stderr V7 ffffffffffffffff (f: 4294967296.000000, d: -nan)
LT  stderr V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V14 00000000004f4800 (f: 5195776.000000, d: 2.567054e-317)
LT  stderr V15 0000000000504708 (f: 5261064.000000, d: 2.599311e-317)
LT  stderr V16 fffffffcfffffffc (f: 4294967296.000000, d: -nan)
LT  stderr V17 0000ffff605043c0 (f: 1615873024.000000, d: 1.390658e-309)
LT  stderr V18 0000ffff605043b0 (f: 1615872896.000000, d: 1.390658e-309)
LT  stderr V19 0000ffff605043a0 (f: 1615872896.000000, d: 1.390658e-309)
LT  stderr V20 0000ffff60504390 (f: 1615872896.000000, d: 1.390658e-309)
LT  stderr V21 0000ffff60504380 (f: 1615872896.000000, d: 1.390658e-309)
LT  stderr V22 0000ffff60504370 (f: 1615872896.000000, d: 1.390658e-309)
LT  stderr V23 00000000000000f0 (f: 240.000000, d: 1.185758e-321)
LT  stderr V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V31 000000003f400000 (f: 1061158912.000000, d: 5.242822e-315)
LT  stderr Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.system_aarch64_linux_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so
LT  stderr Module_base_address=0000FFFF836A6000
LT  stderr Target=2_90_20210907_195 (Linux 5.4.0-81-generic)
LT  stderr CPU=aarch64 (8 logical CPUs) (0x1f047a000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr (0x0000FFFF8364E2B8 [libj9prt29.so+0x262b8])
LT  stderr ---------------------------------------
LT  stderr JVMDUMP039I Processing dump event "abort", detail "" at 2021/09/07 02:10:24 - please wait.

LambdaLoadTest_CS_5m_0_FAILED
```

_Originally posted by @JasonFengJ9 in https://github.com/eclipse-openj9/openj9/issues/13181#issuecomment-914347826_

**Comment by 0xdaryl** [comment]
@tajila : since this is a crash in the VM .so I'd appreciate it if you could find someone to triage this first.  Thank you.

**Comment by knn-k** [comment]
Not reproduced in a 10x Grinder job (job/Grinder/18414/).

**Comment by knn-k** [comment]
Not reproduced in a 30x Grinder job (job/Grinder/18439/).

**Comment by knn-k** [comment]
I cannot reproduce this failure in my local environment, either.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_1/6 - ub20-aarch64-2
LambdaLoadTest_CS_5m_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_1/6/system_test_output.tar.gz
```
LT  03:06:37.687 - Completed 46.7%. Number of tests started=13281 (+1925)
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr java: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=0000FFFFAE8B4828 Handler2=0000FFFFAE82A660 InaccessibleAddress=00000000000000D8
LT  stderr R0=0000000000000000 R1=0000000000000001 R2=0000FFFFAE8DC888 R3=0000FFFFA8024A90
LT  stderr R4=0000000000000004 R5=0000000000000008 R6=0000000000000000 R7=0000FFFF6EF165B0
LT  stderr R8=0000000000000141 R9=00000000FF4C56B0 R10=0000000000000001 R11=0000000000000000
LT  stderr R12=0000FFFFA817F264 R13=0000FFFFA817F268 R14=0000000000000001 R15=0000FFFF6EF164E0
LT  stderr R16=0000FFFFADAE0F94 R17=0000FFFFAF185D80 R18=0000FFFFA817F288 R19=0000FFFFAEA421B8
LT  stderr R20=00000000006C9750 R21=000000007B5D56C0 R22=0000FFFFAEA3E000 R23=00000000FF4C56B0
LT  stderr R24=00000000FF4C56C0 R25=0000FFFFA817F288 R26=00000000FC7CDAC0 R27=00000000000001B3
LT  stderr R28=000000000077CF00 R29=0000FFFF6EF16230 R30=0000FFFFADAE7D3C R31=0000FFFF6EF16230
LT  stderr PC=0000FFFFAE8DC918 SP=0000FFFF6EF16230 PSTATE=0000000020001000
LT  stderr V0 00000000000000ae (f: 174.000000, d: 8.596742e-322)
LT  stderr V1 0000000000000001 (f: 1.000000, d: 4.940656e-324)
LT  stderr V2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V3 40301b8df2321b5a (f: 4063369984.000000, d: 1.610763e+01)
LT  stderr V4 bfd00ea348b88334 (f: 1220051712.000000, d: -2.508934e-01)
LT  stderr V5 3fd5575b0be00b6a (f: 199232368.000000, d: 3.334568e-01)
LT  stderr V6 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
LT  stderr V7 ffffffffffffffff (f: 4294967296.000000, d: -nan)
LT  stderr V8 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
LT  stderr V9 401fff480604a506 (f: 100967688.000000, d: 7.999298e+00)
LT  stderr V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V14 000000000055dd00 (f: 5627136.000000, d: 2.780175e-317)
LT  stderr V15 00000000005715e8 (f: 5707240.000000, d: 2.819751e-317)
LT  stderr V16 fffffffcfffffffc (f: 4294967296.000000, d: -nan)
LT  stderr V17 0000ffff8d4e03c0 (f: 2370700288.000000, d: 1.390662e-309)
LT  stderr V18 0000ffff8d4e03b0 (f: 2370700288.000000, d: 1.390662e-309)
LT  stderr V19 0000ffff8d4e03a0 (f: 2370700288.000000, d: 1.390662e-309)
LT  stderr V20 0000ffff8d4e0390 (f: 2370700288.000000, d: 1.390662e-309)
LT  stderr V21 0000ffff8d4e0380 (f: 2370700288.000000, d: 1.390662e-309)
LT  stderr V22 0000ffff8d4e0370 (f: 2370700032.000000, d: 1.390662e-309)
LT  stderr V23 00000000000000f0 (f: 240.000000, d: 1.185758e-321)
LT  stderr V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V25 4010000000000000 (f: 0.000000, d: 4.000000e+00)
LT  stderr V26 4010000000000000 (f: 0.000000, d: 4.000000e+00)
LT  stderr V27 4014000000000000 (f: 0.000000, d: 5.000000e+00)
LT  stderr V28 4014000000000000 (f: 0.000000, d: 5.000000e+00)
LT  stderr V29 4010000000000000 (f: 0.000000, d: 4.000000e+00)
LT  stderr V30 4014000000000000 (f: 0.000000, d: 5.000000e+00)
LT  stderr V31 4014000000000000 (f: 0.000000, d: 5.000000e+00)
LT  stderr Module=/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so
LT  stderr Module_base_address=0000FFFFAE87F000
LT  stderr Target=2_90_20211003_16 (Linux 5.4.0-88-generic)
LT  stderr CPU=aarch64 (8 logical CPUs) (0x1f047a000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr (0x0000FFFFAE8272B8 [libj9prt29.so+0x262b8])
LT  stderr ---------------------------------------
```

**Comment by pshipton** [comment]
@tajila fyi https://github.com/eclipse-openj9/openj9/issues/13469#issuecomment-916014799
I've tagged as vm.

**Comment by pshipton** [comment]
This one is on jdk11.
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_aarch64_linux_Release_testList_1/1 - ub20-aarch64-1

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.system_aarch64_linux_Release_testList_1/1/system_test_output.tar.gz
```
LT  22:46:21.748 - Completed 86.7%. Number of tests started=26529 (+1997)
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr java: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=0000FFFFB0C87068 Handler2=0000FFFFB0BFD660 InaccessibleAddress=00000000000000D8
LT  stderr R0=0000000000000000 R1=0000000000000001 R2=0000FFFFB0CAF740 R3=0000FFFFAC024D80
LT  stderr R4=0000000000000004 R5=0000000000000008 R6=0000000000000000 R7=0000FFFF8F7C55B0
LT  stderr R8=0000000000000281 R9=0000000000000000 R10=00000000F095AA60 R11=0000000000000000
LT  stderr R12=0000FFFFAC17FC94 R13=00000000F095AA60 R14=0000000000000001 R15=0000FFFF8F7C54E0
LT  stderr R16=0000FFFFABD93DFC R17=0000FFFFB1568D80 R18=0000FFFFAC17FCB8 R19=0000FFFFB0E25188
LT  stderr R20=000000000089C450 R21=000000006CA6AA60 R22=0000FFFFB0E21000 R23=00000000F095AA60
LT  stderr R24=0000000000000281 R25=0000FFFFAC17FCB8 R26=00000000F07F7A48 R27=00000000F07F1778
LT  stderr R28=00000000005F2900 R29=0000FFFF8F7C5230 R30=0000FFFFABD9AB94 R31=0000FFFF8F7C5230
LT  stderr PC=0000FFFFB0CAF7D0 SP=0000FFFF8F7C5230 PSTATE=0000000020001000
LT  stderr V0 000000000000016b (f: 363.000000, d: 1.793458e-321)
LT  stderr V1 0000000000000001 (f: 1.000000, d: 4.940656e-324)
LT  stderr V2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V3 40335f5124fe822b (f: 620659264.000000, d: 1.937233e+01)
LT  stderr V4 bfd00ea348b88334 (f: 1220051712.000000, d: -2.508934e-01)
LT  stderr V5 3fd5575b0be00b6a (f: 199232368.000000, d: 3.334568e-01)
LT  stderr V6 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
LT  stderr V7 ffffffffffffffff (f: 4294967296.000000, d: -nan)
LT  stderr V8 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
LT  stderr V9 406ffc0410d8c187 (f: 282640768.000000, d: 2.558755e+02)
LT  stderr V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V14 00000000004e7200 (f: 5140992.000000, d: 2.539988e-317)
LT  stderr V15 00000000004f3278 (f: 5190264.000000, d: 2.564331e-317)
LT  stderr V16 fffffffcfffffffc (f: 4294967296.000000, d: -nan)
LT  stderr V17 0000ffff8fc533c0 (f: 2412065792.000000, d: 1.390662e-309)
LT  stderr V18 0000ffff8fc533b0 (f: 2412065792.000000, d: 1.390662e-309)
LT  stderr V19 0000ffff8fc533a0 (f: 2412065792.000000, d: 1.390662e-309)
LT  stderr V20 0000ffff8fc53390 (f: 2412065792.000000, d: 1.390662e-309)
LT  stderr V21 0000ffff8fc53380 (f: 2412065792.000000, d: 1.390662e-309)
LT  stderr V22 0000ffff8fc53370 (f: 2412065536.000000, d: 1.390662e-309)
LT  stderr V23 00000000000000f0 (f: 240.000000, d: 1.185758e-321)
LT  stderr V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr V25 4010000000000000 (f: 0.000000, d: 4.000000e+00)
LT  stderr V26 4010000000000000 (f: 0.000000, d: 4.000000e+00)
LT  stderr V27 4014000000000000 (f: 0.000000, d: 5.000000e+00)
LT  stderr V28 4014000000000000 (f: 0.000000, d: 5.000000e+00)
LT  stderr V29 408b000000000000 (f: 0.000000, d: 8.640000e+02)
LT  stderr V30 0000000041040000 (f: 1090781184.000000, d: 5.389175e-315)
LT  stderr V31 00000000430f4000 (f: 1125072896.000000, d: 5.558599e-315)
LT  stderr Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.system_aarch64_linux_Release_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so
LT  stderr Module_base_address=0000FFFFB0C52000
LT  stderr Target=2_90_20211011_3 (Linux 5.4.0-88-generic)
LT  stderr CPU=aarch64 (8 logical CPUs) (0x1f047a000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr (0x0000FFFFB0BFA2B8 [libj9prt29.so+0x262b8])
LT  stderr ---------------------------------------
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_1/12 - ub20-aarch64-2
LambdaLoadTest_CS_5m_0 -Xgcpolicy:gencon -Xgc:concurrentScavenge 
```
LT  testStarted : testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
LT  load-2 MT running with 25 threads
LT  testFailure: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded): null
LT  java.lang.ArrayIndexOutOfBoundsException
LT  	at java.base/java.util.Vector.add(Vector.java:783)
LT  	at java.base/java.util.Vector.addElement(Vector.java:617)
LT  	at java.base/java.util.Stack.push(Stack.java:66)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.lambda$new$0(TestLambdaMultithreaded.java:130)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded$$Lambda$196/0x00000000f002d9f0.execute(Unknown Source)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.runNumberCounter(TestLambdaMultithreaded.java:397)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:236)
LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded$$Lambda$230/0x00000000f0031cc8.run(Unknown Source)
LT  	at java.base/java.lang.Thread.run(Thread.java:884)
LT  testFinished: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
```
