### ISSUE TITLE
JDK11 aarch64_linux : java/util/zip/FlaterTest.java - NPE at java.base/java.util.zip.Inflater.inflate(Inflater.java:509)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13486]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/81/`:
```
openjdk version "11.0.13-ea" 2021-10-19
IBM Semeru Runtime Open Edition 11.0.12.0 (build 11.0.13-ea+5)
Eclipse OpenJ9 VM 11.0.12.0 (build master-a2a4729e4, JRE 11 Linux aarch64-64-Bit Compressed References 20210910_198 (JIT enabled, AOT enabled)
OpenJ9   - a2a4729e4
OMR      - 680b68120
JCL      - ddc29ca760 based on jdk-11.0.13+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_util_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F198%2Fibm-semeru-open-debugimage_aarch64_linux_JDK11U_2021-09-10-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F198%2Fibm-semeru-open-jdk_aarch64_linux_JDK11U_2021-09-10-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F198%2Fibm-semeru-open-jre_aarch64_linux_JDK11U_2021-09-10-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F198%2Fibm-semeru-open-testimage_aarch64_linux_JDK11U_2021-09-10-01-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-09-10T01:46:19.195Z] Running test jdk_util_0 ...
[2021-09-10T01:46:19.195Z] ===============================================

[2021-09-10T01:46:19.195Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2021-09-10T01:46:19.195Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2021-09-10T01:58:30.814Z] --------------------------------------------------
[2021-09-10T01:58:30.814Z] TEST: java/util/zip/FlaterTest.java

[2021-09-10T01:58:30.816Z] STDERR:
[2021-09-10T01:58:30.816Z] JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
[2021-09-10T01:58:30.816Z] java.lang.NullPointerException
[2021-09-10T01:58:30.816Z] 	at java.base/java.util.zip.Inflater.inflate(Inflater.java:509)
[2021-09-10T01:58:30.816Z] 	at FlaterTest$Flater.InflateData(FlaterTest.java:201)
[2021-09-10T01:58:30.816Z] 	at FlaterTest$Flater.run(FlaterTest.java:140)

[2021-09-10T01:58:30.817Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
[2021-09-10T01:58:30.817Z] --------------------------------------------------
[2021-09-10T01:58:55.883Z] Test results: passed: 839; failed: 1
[2021-09-10T01:59:05.235Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2021-09-10T01:59:05.235Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/aqa-tests/TKG/output_16312373625899/jdk_util_0/work
[2021-09-10T01:59:05.235Z] Error: Some tests failed or other problems occurred.
[2021-09-10T01:59:05.235Z] 
[2021-09-10T01:59:05.235Z] jdk_util_0_FAILED
```

fyi @knn-k

**Comment by Akira1Saitoh** [comment]
Launching 10x Grinder. `job/Grinder/18063/`
