### ISSUE TITLE
JDK17 aarch64_linux 0.28 release - UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost, NestMembers, Record, or PermittedSubclasses attribute

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13503]
Failure link
------------

From an internal build `/job/Test_openjdk17_j9_extended.system_aarch64_linux_Personal/13/tapResults/`:
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17aarch64linuxPersonal)
Eclipse OpenJ9 VM (build v0.28.0-release-4b4e3ba6907, JRE 17 Linux aarch64-64-Bit Compressed References 20210913_45 (JIT enabled, AOT enabled)
OpenJ9   - 4b4e3ba6907
OMR      - 407eef0153b
JCL      - b6c1a570c77 based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_aarch64_linux_Personal%2F45%2FOpenJ9-JDK17-aarch64_linux-20210913-101329.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_aarch64_linux_Personal%2F45%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=v0.28.0-release&OPENJ9_SHA=4b4e3ba690708a5122ea8ab86c1876e48024230e&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=83285587d3e8588e6b013ff8de3418e45d31c945&JDK_BRANCH=v0.28.0-release&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=3&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=Dynamic)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test HCRLateAttachWorkload_previewEnabled_0 ...
===============================================
HCRLateAttachWorkload_previewEnabled_0 Start Time: Mon Sep 13 11:08:22 2021 Epoch Time (ms): 1631545702344
variation: Mode150
JVM_OPTIONS:  -XX:+UseCompressedOops 

LT  11:08:28.060 - Starting thread. Suite=0 thread=2
LT  Exception seen while transforming String.

LT  Thread 8 failed to retransform String.
LT  java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost, NestMembers, Record, or PermittedSubclasses attribute
LT  Exception seen while transforming String.

LT  stderr Exception in thread "Attachment 40731" java.lang.reflect.InvocationTargetException
LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
LT  stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:513)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:356)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:334)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:200)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.NullPointerException
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:130)
LT  stderr 	... 11 more
LT  stderr Caused by: java.lang.Error: java.lang.NullPointerException
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
LT  stderr 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
LT  stderr 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.TransformerMakerThread.run(TransformerMakerThread.java:68)
LT  stderr Caused by: java.lang.NullPointerException
LT  stderr 	at java.base/jdk.internal.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java)
LT  stderr 	at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:513)
LT  stderr 	at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:432)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:76)
LT  stderr 	... 6 more
LT  stderr Agent failed to start!
LT  stderr JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:375)
AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(OpenJ9VirtualMachine.java:268)
AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
STF 11:08:39.897 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)

HCRLateAttachWorkload_previewEnabled_0_FAILED
```

It is not clear if this is due to the NPE like https://github.com/eclipse-openj9/openj9/issues/13502

fyi @Akira1Saitoh

**Comment by Akira1Saitoh** [comment]
The problematic method is `jdk/internal/org/objectweb/asm/ClassReader.accept(Ljdk/internal/org/objectweb/asm/ClassVisitor;[Ljdk/internal/org/objectweb/asm/Attribute;I)V`.

In the trace below, the register dependency added to the `cbnz` instruction contains `w25`, but `w25` is spilled and assigned to the source register of that instruction. As a result, value in the w25 is destroyed.

```
    0xffff87be0d80 00000b8c [    0xfffede018de0] f900d299 438   strimmx         w25, [w20, 416]         # SymRef  <#SPIL
L8_707     0xfffedfffcb70>[#707  Auto +416] [flags 0x80000000 0x0 ]
    0xffff87be0d84 00000b90 [    0xfffede018d00] f940be99 438   ldrimmx         w25, [w20, 376]         ; spilled for ic
all             # SymRef  <#SPILL8_701     0xfffedfffc0f0>[#701  Auto +376] [flags 0x80000000 0x0 ]

 \\ jdk/internal/org/objectweb/asm/ClassReader.accept(Ljdk/internal/org/objectweb/asm/ClassVisitor;[Ljdk/internal/org/objectweb/asm/Attribute;I)V
 \\  441 JBifeq 482

    0xffff87be0d88 00000b94 [    0xfffedfd4eff0] 350067b9 441   cbnzw   w25, Label L0032
 PRE: [GPR_    0xfffedfd0d680 : x15] [GPR_    0xfffedfd0d6f0 : x13] [&GPR_    0xfffedfd0d760 : x12] [GPR_    0xfffedfd142e0 : x11] [&GPR_    0xfffedfd0d7d0 : x10] [GPR_    0xfffedfd0d840 : x9] [GPR_    0xfffedfd0d8b0 : x8] [GPR_    0xfffedf
d0d920 : x18] [&GPR_    0xfffedfd0da00 : x27] [GPR_    0xfffedfd0da70 : x26] [&GPR_    0xfffedfd0dae0 : x25] [&GPR_    0
xfffedfd0db50 : x24] [GPR_    0xfffedfd0dbc0 : x23] [GPR_    0xfffedfd0dc30 : x22] [GPR_    0xfffedfd0dca0 : x21] [&GPR_
    0xfffedfd0dd10 : x7] [GPR_    0xfffedfd0dd80 : x6] [GPR_    0xfffedfd0ddf0 : x5] [GPR_    0xfffedfd0de60 : x4] [GPR_
    0xfffedfd0ded0 : x3] [&GPR_    0xfffedfd0df40 : x2] [GPR_    0xfffedfd0dfb0 : x1] [&GPR_    0xfffedfd0e020 : x0]
POST: [GPR_    0xfffedfd0d680 : x15] [GPR_    0xfffedfd0d6f0 : x13] [&GPR_    0xfffedfd0d760 : x12] [GPR_    0xfffedfd14
2e0 : x11] [&GPR_    0xfffedfd0d7d0 : x10] [GPR_    0xfffedfd0d840 : x9] [GPR_    0xfffedfd0d8b0 : x8] [GPR_    0xfffedf
d0d920 : x18] [&GPR_    0xfffedfd0da00 : x27] [GPR_    0xfffedfd0da70 : x26] [&GPR_    0xfffedfd0dae0 : x25] [&GPR_    0
xfffedfd0db50 : x24] [GPR_    0xfffedfd0dbc0 : x23] [GPR_    0xfffedfd0dc30 : x22] [GPR_    0xfffedfd0dca0 : x21] [&GPR_    0xfffedfd0dd10 : x7] [GPR_    0xfffedfd0dd80 : x6] [GPR_    0xfffedfd0ddf0 : x5] [GPR_    0xfffedfd0de60 : x4] [GPR_
    0xfffedfd0ded0 : x3] [&GPR_    0xfffedfd0df40 : x2] [GPR_    0xfffedfd0dfb0 : x1] [&GPR_    0xfffedfd0e020 : x0]
    0xffff87be0d8c 00000b98 [    0xfffede018c20] f940d299 441   ldrimmx         w25, [w20, 416]         ; spilled for if
icmpne          # SymRef  <#SPILL8_707     0xfffedfffcb70>[#707  Auto +416] [flags 0x80000000 0x0 ]
```

**Comment by 0xdaryl** [comment]
Fixed
