### ISSUE TITLE
JDK17 aarch64_linux 0.28 release - jsr292Test_JitCount0_0_FAILED test_invokeWithArguments_variable_input NPE at sun.invoke.util.ValueConversions.unboxInteger

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13502]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.functional_aarch64_linux_Personal/23/tapResults/`:
```
10:36:19  openjdk version "17-internal" 2021-09-14
10:36:19  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17aarch64linuxPersonal)
10:36:19  Eclipse OpenJ9 VM (build v0.28.0-release-4b4e3ba6907, JRE 17 Linux aarch64-64-Bit Compressed References 20210913_45 (JIT enabled, AOT enabled)
10:36:19  OpenJ9   - 4b4e3ba6907
10:36:19  OMR      - 407eef0153b
10:36:19  JCL      - b6c1a570c77 based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_aarch64_linux_Personal%2F45%2FOpenJ9-JDK17-aarch64_linux-20210913-101329.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_aarch64_linux_Personal%2F45%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=v0.28.0-release&OPENJ9_SHA=4b4e3ba690708a5122ea8ab86c1876e48024230e&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=83285587d3e8588e6b013ff8de3418e45d31c945&JDK_BRANCH=v0.28.0-release&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=Dynamic)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test jsr292Test_JitCount0_0 ...
===============================================
jsr292Test_JitCount0_0 Start Time: Mon Sep 13 11:43:11 2021 Epoch Time (ms): 1631547791526
variation: -Xjit:count=0
JVM_OPTIONS:  -Xjit:count=0 

FAILED: test_invokeWithArguments_variable_input
java.lang.NullPointerException
	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
	at com.ibm.j9.jsr292.FilterArgumentsTest.test_filterArguments_Character(FilterArgumentsTest.java:321)
	at com.ibm.j9.jsr292.FilterArgumentsTest.test_filterArguments_Character(FilterArgumentsTest.java:354)
	at com.ibm.j9.jsr292.FilterArgumentsTest.test_filterArguments_Character(FilterArgumentsTest.java:330)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invokeExact_MT(LambdaForm$MH)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments(MethodHandleImpl.java:535)
	at com.ibm.j9.jsr292.MethodHandleTest.test_invokeWithArguments_variable_input(MethodHandleTest.java:1468)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
===============================================
    jsr292Test
    Tests run: 233, Failures: 1, Skips: 0
===============================================

jsr292Test_JitCount0_0_FAILED
```

fyi @Akira1Saitoh

**Comment by Akira1Saitoh** [comment]
This issue is similar to https://github.com/eclipse-openj9/openj9/issues/13503, but slightly different.
When a method `java/lang/invoke/LambdaForm$MH/0x0000000000000000.invoke_MT(Ljava/lang/Object;JFJDIIIIDDJIIJJIJFJDIIIIDD
JIIJJIJFJDIIIIDDJIIJJIJFJDIIIIDDJIIJJIJFJDIIIIDDJIIJJIJFJDIIIIDDJIIJJIJFJDIIIIDDJIIJJIJFJDIIIIDDJIIJJIJFJDIIIIDDJIIJJIJF
JDIIIIDDJIIJJIJFJDIIIIDLjava/lang/Object;)Ljava/lang/Object;` is compiled, the generated IL has `ificmpne` node with extremely many global registers.

```
 n1218n   (  0)  ificmpne --> block_20 BBStart at n1403n ()                                           [    0xffff64e51c7
0] bci=[-1,357,-] rc=0 vc=10 vn=- li=13 udi=- nc=3 flg=0x20
 n1417n   (  0)    iand (in GPR_0384)                                                                 [    0xffff64e55aa
0] bci=[-1,357,-] rc=0 vc=10 vn=- li=13 udi=28384 nc=2
 n1416n   (  0)      l2i (in GPR_0384)                                                                [    0xffff64e55a5
0] bci=[-1,357,-] rc=0 vc=10 vn=- li=13 udi=28384 nc=1
 n1212n   (  2)        ==>lloadi (in GPR_0334) (cannotOverflow )
 n1414n   (  0)      iconst 1                                                                         [    0xffff64e559b
0] bci=[-1,357,-] rc=0 vc=10 vn=- li=13 udi=- nc=0
 n1415n   (  0)    iconst 0                                                                           [    0xffff64e55a0
0] bci=[-1,357,-] rc=0 vc=10 vn=- li=13 udi=- nc=0
 n1539n   (  0)    GlRegDeps ()                                                                       [    0xffff64e580c
0] bci=[-1,357,-] rc=0 vc=10 vn=- li=13 udi=- nc=57 flg=0x20
 n1424n   (  1)      ==>aRegLoad (in &GPR_0208) (X!=0 X>=0 SeenRealReference sharedMemory )
 n1483n   (  0)      PassThrough x14                                                                  [    0xffff64e56f4
0] bci=[-1,353,-] rc=0 vc=10 vn=- li=13 udi=47008 nc=1
 n188n    (  1)        ==>iload (in GPR_0331) (cannotOverflow )
 n1484n   (  0)      PassThrough x13                                                                  [    0xffff64e56f9
0] bci=[-1,351,-] rc=0 vc=10 vn=- li=13 udi=46144 nc=1
 n187n    (  1)        ==>iload (in GPR_0330) (cannotOverflow )
 n1485n   (  0)      PassThrough x12                                                                  [    0xffff64e56fe
0] bci=[-1,349,-] rc=0 vc=10 vn=- li=13 udi=45280 nc=1
 n186n    (  1)        ==>iload (in GPR_0329) (cannotOverflow )
 n1486n   (  0)      PassThrough x11                                                                  [    0xffff64e5703
0] bci=[-1,347,-] rc=0 vc=10 vn=- li=13 udi=44384 nc=1
 n185n    (  1)        ==>iload (in GPR_0328) (cannotOverflow )
 n1487n   (  0)      PassThrough x10                                                                  [    0xffff64e5708
0] bci=[-1,343,-] rc=0 vc=10 vn=- li=13 udi=42720 nc=1
 n183n    (  1)        ==>lload (in GPR_0326) (cannotOverflow )
 n1488n   (  0)      PassThrough x9                                                                   [    0xffff64e570d
0] bci=[-1,339,-] rc=0 vc=10 vn=- li=13 udi=41056 nc=1
 n181n    (  1)        ==>lload (in GPR_0324) (cannotOverflow )
 n1489n   (  0)      PassThrough x8                                                                   [    0xffff64e57120] bci=[-1,337,-] rc=0 vc=10 vn=- li=13 udi=24704 nc=1
 n180n    (  1)        ==>iload (in GPR_0383) (cannotOverflow )
 n1490n   (  0)      PassThrough x18                                                                  [    0xffff64e57170] bci=[-1,335,-] rc=0 vc=10 vn=- li=13 udi=23840 nc=1
 n179n    (  1)        ==>lload (in GPR_0382) (cannotOverflow )
 n1491n   (  0)      PassThrough x28                                                                  [    0xffff64e571c0] bci=[-1,333,-] rc=0 vc=10 vn=- li=13 udi=22976 nc=1
 n178n    (  1)        ==>lload (in GPR_0381) (cannotOverflow )
 n1492n   (  0)      PassThrough x27                                                                  [    0xffff64e57210] bci=[-1,331,-] rc=0 vc=10 vn=- li=13 udi=22112 nc=1
 n177n    (  1)        ==>iload (in GPR_0380) (cannotOverflow )
 n1493n   (  0)      PassThrough x26                                                                  [    0xffff64e57260] bci=[-1,329,-] rc=0 vc=10 vn=- li=13 udi=21248 nc=1
 n176n    (  1)        ==>iload (in GPR_0379) (cannotOverflow )
 n1494n   (  0)      PassThrough x25                                                                  [    0xffff64e572b0] bci=[-1,327,-] rc=0 vc=10 vn=- li=13 udi=20384 nc=1
 n175n    (  1)        ==>lload (in GPR_0378) (cannotOverflow )
 n1495n   (  0)      PassThrough x24                                                                  [    0xffff64e57300] bci=[-1,321,-] rc=0 vc=10 vn=- li=13 udi=17792 nc=1
 n172n    (  1)        ==>iload (in GPR_0375) (cannotOverflow )
 n1496n   (  0)      PassThrough x23                                                                  [    0xffff64e57350] bci=[-1,319,-] rc=0 vc=10 vn=- li=13 udi=16928 nc=1
 n171n    (  1)        ==>iload (in GPR_0374) (cannotOverflow )
 n1497n   (  0)      PassThrough x22                                                                  [    0xffff64e573a
0] bci=[-1,317,-] rc=0 vc=10 vn=- li=13 udi=16064 nc=1
 n170n    (  1)        ==>iload (in GPR_0373) (cannotOverflow )
 n1498n   (  0)      PassThrough x21                                                                  [    0xffff64e573f0] bci=[-1,315,-] rc=0 vc=10 vn=- li=13 udi=15200 nc=1
 n169n    (  1)        ==>iload (in GPR_0372) (cannotOverflow )
 n1499n   (  0)      PassThrough x7                                                                   [    0xffff64e57440] bci=[-1,41,-] rc=0 vc=10 vn=- li=13 udi=60896 nc=1
 n32n     (  1)        ==>iload (in GPR_0348) (cannotOverflow )
 n1500n   (  0)      PassThrough x6                                                                   [    0xffff64e57490] bci=[-1,39,-] rc=0 vc=10 vn=- li=13 udi=60032 nc=1
 n31n     (  1)        ==>lload (in GPR_0347) (cannotOverflow )
 n1501n   (  0)      PassThrough x5                                                                   [    0xffff64e574e0] bci=[-1,33,-] rc=0 vc=10 vn=- li=13 udi=57568 nc=1
 n28n     (  1)        ==>iload (in GPR_0344) (cannotOverflow )
 n1502n   (  0)      PassThrough x4                                                                   [    0xffff64e57530] bci=[-1,31,-] rc=0 vc=10 vn=- li=13 udi=56704 nc=1
 n27n     (  1)        ==>iload (in GPR_0343) (cannotOverflow )
 n1503n   (  0)      PassThrough x3                                                                   [    0xffff64e57580] bci=[-1,29,-] rc=0 vc=10 vn=- li=13 udi=55840 nc=1
 n26n     (  1)        ==>iload (in GPR_0342) (cannotOverflow )
 n1504n   (  0)      PassThrough x2                                                                   [    0xffff64e575d0] bci=[-1,27,-] rc=0 vc=10 vn=- li=13 udi=55040 nc=1
 n25n     (  1)        ==>iload (in GPR_0341) (cannotOverflow )
 n1505n   (  0)      PassThrough x1                                                                   [    0xffff64e57620] bci=[-1,23,-] rc=0 vc=10 vn=- li=13 udi=53440 nc=1
 n23n     (  1)        ==>lload (in GPR_0339) (cannotOverflow )
 n1506n   (  0)      PassThrough x0                                                                   [    0xffff64e57670] bci=[-1,21,-] rc=0 vc=10 vn=- li=13 udi=51840 nc=1
 n21n     (  1)        ==>lload (in GPR_0337) (cannotOverflow )
 n1507n   (  0)      PassThrough d31                                                                  [    0xffff64e576c0] bci=[-1,355,-] rc=0 vc=10 vn=- li=13 udi=47872 nc=1
 n189n    (  1)        ==>dload (in FPR_0332)
 n1508n   (  0)      PassThrough d30                                                                  [    0xffff64e57710] bci=[-1,345,-] rc=0 vc=10 vn=- li=13 udi=43584 nc=1
 n184n    (  1)        ==>dload (in FPR_0327)
 n1509n   (  0)      PassThrough d29                                                                  [    0xffff64e57760] bci=[-1,341,-] rc=0 vc=10 vn=- li=13 udi=41920 nc=1
 n182n    (  1)        ==>fload (in FPR_0325)
 n1510n   (  0)      PassThrough d28                                                                  [    0xffff64e577b0] bci=[-1,325,-] rc=0 vc=10 vn=- li=13 udi=19520 nc=1
 n174n    (  1)        ==>dload (in FPR_0377)
 n1511n   (  0)      PassThrough d27                                                                  [    0xffff64e57800] bci=[-1,323,-] rc=0 vc=10 vn=- li=13 udi=18656 nc=1
 n173n    (  1)        ==>dload (in FPR_0376)
 n1512n   (  0)      PassThrough d26                                                                  [    0xffff64e57850] bci=[-1,313,-] rc=0 vc=10 vn=- li=13 udi=14336 nc=1
 n168n    (  1)        ==>dload (in FPR_0371)
 n1513n   (  0)      PassThrough d25                                                                  [    0xffff64e578a0] bci=[-1,309,-] rc=0 vc=10 vn=- li=13 udi=13472 nc=1
 n166n    (  1)        ==>fload (in FPR_0370)
 n1514n   (  0)      PassThrough d24                                                                  [    0xffff64e578f0] bci=[-1,293,-] rc=0 vc=10 vn=- li=13 udi=12608 nc=1
 n158n    (  1)        ==>dload (in FPR_0369)
 n1515n   (  0)      PassThrough d23                                                                  [    0xffff64e57940] bci=[-1,291,-] rc=0 vc=10 vn=- li=13 udi=11744 nc=1
 n157n    (  1)        ==>dload (in FPR_0368)
 n1516n   (  0)      PassThrough d22                                                                  [    0xffff64e57990] bci=[-1,281,-] rc=0 vc=10 vn=- li=13 udi=10880 nc=1
 n152n    (  1)        ==>dload (in FPR_0367)
 n1517n   (  0)      PassThrough d21                                                                  [    0xffff64e579e0] bci=[-1,277,-] rc=0 vc=10 vn=- li=13 udi=10016 nc=1
 n150n    (  1)        ==>fload (in FPR_0366)
 n1518n   (  0)      PassThrough d20                                                                  [    0xffff64e57a30] bci=[-1,261,-] rc=0 vc=10 vn=- li=13 udi=9152 nc=1
 n142n    (  1)        ==>dload (in FPR_0365)
 n1519n   (  0)      PassThrough d19                                                                  [    0xffff64e57a80] bci=[-1,259,-] rc=0 vc=10 vn=- li=13 udi=8288 nc=1
 n141n    (  1)        ==>dload (in FPR_0364)
 n1520n   (  0)      PassThrough d18                                                                  [    0xffff64e57ad0] bci=[-1,249,-] rc=0 vc=10 vn=- li=13 udi=7424 nc=1
 n136n    (  1)        ==>dload (in FPR_0363)
 n1521n   (  0)      PassThrough d17                                                                  [    0xffff64e57b20] bci=[-1,245,-] rc=0 vc=10 vn=- li=13 udi=6624 nc=1
 n134n    (  1)        ==>fload (in FPR_0362)
 n1522n   (  0)      PassThrough d16                                                                  [    0xffff64e57b70] bci=[-1,229,-] rc=0 vc=10 vn=- li=13 udi=5824 nc=1
 n126n    (  1)        ==>dload (in FPR_0361)
 n1523n   (  0)      PassThrough d15                                                                  [    0xffff64e57bc0] bci=[-1,227,-] rc=0 vc=10 vn=- li=13 udi=5024 nc=1
 n125n    (  1)        ==>dload (in FPR_0360)
 n1524n   (  0)      PassThrough d14                                                                  [    0xffff64e57c10] bci=[-1,217,-] rc=0 vc=10 vn=- li=13 udi=4224 nc=1
 n120n    (  1)        ==>dload (in FPR_0359)
 n1525n   (  0)      PassThrough d13                                                                  [    0xffff64e57c60] bci=[-1,213,-] rc=0 vc=10 vn=- li=13 udi=3424 nc=1
 n118n    (  1)        ==>fload (in FPR_0358)
 n1526n   (  0)      PassThrough d12                                                                  [    0xffff64e57cb0] bci=[-1,197,-] rc=0 vc=10 vn=- li=13 udi=2624 nc=1
 n110n    (  1)        ==>dload (in FPR_0357)
 n1527n   (  0)      PassThrough d11                                                                  [    0xffff64e57d00] bci=[-1,195,-] rc=0 vc=10 vn=- li=13 udi=1824 nc=1
 n109n    (  1)        ==>dload (in FPR_0356)
 n1528n   (  0)      PassThrough d10                                                                  [    0xffff64e57d50] bci=[-1,185,-] rc=0 vc=10 vn=- li=13 udi=1024 nc=1
 n104n    (  1)        ==>dload (in FPR_0355)
 n1529n   (  0)      PassThrough d9                                                                   [    0xffff64e57da0] bci=[-1,181,-] rc=0 vc=10 vn=- li=13 udi=224 nc=1
 n102n    (  1)        ==>fload (in FPR_0354)
 n1530n   (  0)      PassThrough d8                                                                   [    0xffff64e57df0] bci=[-1,85,-] rc=0 vc=10 vn=- li=13 udi=64960 nc=1
 n54n     (  1)        ==>fload (in FPR_0353)
 n1531n   (  0)      PassThrough d7                                                                   [    0xffff64e57e40] bci=[-1,69,-] rc=0 vc=10 vn=- li=13 udi=64160 nc=1
 n46n     (  1)        ==>dload (in FPR_0352)
 n1532n   (  0)      PassThrough d6                                                                   [    0xffff64e57e90] bci=[-1,67,-] rc=0 vc=10 vn=- li=13 udi=63360 nc=1
 n45n     (  1)        ==>dload (in FPR_0351)
 n1533n   (  0)      PassThrough d5                                                                   [    0xffff64e57ee0] bci=[-1,57,-] rc=0 vc=10 vn=- li=13 udi=62560 nc=1
 n40n     (  1)        ==>dload (in FPR_0350)
 n1534n   (  0)      PassThrough d4                                                                   [    0xffff64e57f30] bci=[-1,53,-] rc=0 vc=10 vn=- li=13 udi=61760 nc=1
 n38n     (  1)        ==>fload (in FPR_0349)
 n1535n   (  0)      PassThrough d3                                                                   [    0xffff64e57f80] bci=[-1,37,-] rc=0 vc=10 vn=- li=13 udi=59232 nc=1
 n30n     (  1)        ==>dload (in FPR_0346)
 n1536n   (  0)      PassThrough d2                                                                   [    0xffff64e57fd0] bci=[-1,35,-] rc=0 vc=10 vn=- li=13 udi=58432 nc=1
 n29n     (  1)        ==>dload (in FPR_0345)
 n1537n   (  0)      PassThrough d1                                                                   [    0xffff64e58020] bci=[-1,25,-] rc=0 vc=10 vn=- li=13 udi=54240 nc=1
 n24n     (  1)        ==>dload (in FPR_0340)
 n1538n   (  0)      PassThrough d0                                                                   [    0xffff64e58070] bci=[-1,22,-] rc=0 vc=10 vn=- li=13 udi=52640 nc=1
 n22n     (  1)        ==>fload (in FPR_0338)
------------------------------

 [    0xffff64ec6f90]   357     movx    GPR_0384, GPR_0334
 [    0xffff64ec7020]   357     andimmw         GPR_0384, GPR_0384, 0x1
 [    0xffff64ec8610]   357     assocreg[&GPR_0208 : x15] 
 [    0xffff64ec7f20]   357     cbnzw   GPR_0384, Label L0002   
 PRE: [&GPR_0208 : x15] [GPR_0331 : x14] [GPR_0330 : x13] [GPR_0329 : x12] [GPR_0328 : x11] [GPR_0326 : x10] [GPR_0324 : x9] [GPR_0383 : x8] [GPR_0382 : x18] [GPR_0381 : x28] [GPR_0380 : x27] [GPR_0379 : x26] [GPR_0378 : x25] [GPR_0375 : x24] [GPR_0374 : x23] [GPR_0373 : x22] [GPR_0372 : x21] [GPR_0348 : x7] [GPR_0347 : x6] [GPR_0344 : x5] [GPR_0343 : x4] [GPR_0342 : x3] [GPR_0341 : x2] [GPR_0339 : x1] [GPR_0337 : x0] [FPR_0332 : d31] [FPR_0327 : d30] [FPR_0325 : d29] [FPR_0377 : d28] [FPR_0376 : d27] [FPR_0371 : d26] [FPR_0370 : d25] [FPR_0369 : d24] [FPR_0368 : d23] [FPR_0367 : d22] [FPR_0366 : d21] [FPR_0365 : d20] [FPR_0364 : d19] [FPR_0363 : d18] [FPR_0362 : d17] [FPR_0361 : d16] [FPR_0360 : d15] [FPR_0359 : d14] [FPR_0358 : d13] [FPR_0357 : d12] [FPR_0356 : d11] [FPR_0355 : d10] [FPR_0354 : d9] [FPR_0353 : d8] [FPR_0352 : d7] [FPR_0351 : d6] [FPR_0350 : d5] [FPR_0349 : d4] [FPR_0346 : d3] [FPR_0345 : d2] [FPR_0340 : d1] [FPR_0338 : d0] 
POST: [&GPR_0208 : x15] [GPR_0331 : x14] [GPR_0330 : x13] [GPR_0329 : x12] [GPR_0328 : x11] [GPR_0326 : x10] [GPR_0324 : x9] [GPR_0383 : x8] [GPR_0382 : x18] [GPR_0381 : x28] [GPR_0380 : x27] [GPR_0379 : x26] [GPR_0378 : x25] [GPR_0375 : x24] [GPR_0374 : x23] [GPR_0373 : x22] [GPR_0372 : x21] [GPR_0348 : x7] [GPR_0347 : x6] [GPR_0344 : x5] [GPR_0343 : x4] [GPR_0342 : x3] [GPR_0341 : x2] [GPR_0339 : x1] [GPR_0337 : x0] [FPR_0332 : d31] [FPR_0327 : d30] [FPR_0325 : d29] [FPR_0377 : d28] [FPR_0376 : d27] [FPR_0371 : d26] [FPR_0370 : d25] [FPR_0369 : d24] [FPR_0368 : d23] [FPR_0367 : d22] [FPR_0366 : d21] [FPR_0365 : d20] [FPR_0364 : d19] [FPR_0363 : d18] [FPR_0362 : d17] [FPR_0361 : d16] [FPR_0360 : d15] [FPR_0359 : d14] [FPR_0358 : d13] [FPR_0357 : d12] [FPR_0356 : d11] [FPR_0355 : d10] [FPR_0354 : d9] [FPR_0353 : d8] [FPR_0352 : d7] [FPR_0351 : d6] [FPR_0350 : d5] [FPR_0349 : d4] [FPR_0346 : d3] [FPR_0345 : d2] [FPR_0340 : d1] [FPR_0338 : d0] 
```

Then, because all integer registers are used up for assigning registers in reg deps created for global registers, one of the global register are spilled when assigining the source register of `cbnz` instruction. In the example below, w9 is spilled.
```
    0xffff6660ea4c 00000798 [    0xffff64fe9750] f907aa89 357   strimmx         w9, [w20, 3920]         # SymRef  <#SPIL
L8_1441     0xffff64fd8c40>[#1441  Auto +3920] [flags 0x80000000 0x0 ]  
    0xffff6660ea50 0000079c [    0xffff64fe9670] f946ae89 357   ldrimmx         w9, [w20, 3416]         ; spilled for ia
nd              # SymRef  <#SPILL8_1467     0xffff64fe9540>[#1467  Auto +3416] [flags 0x80000000 0x0 ]  
    0xffff6660ea54 000007a0 [    0xffff64ec7f20] 35002809 357   cbnzw   w9, Label L0002 
 PRE: [&GPR_0208 : x15] [GPR_0331 : x14] [GPR_0330 : x13] [GPR_0329 : x12] [GPR_0328 : x11] [GPR_0326 : x10] [GPR_0324 :
 x9] [GPR_0383 : x8] [GPR_0382 : x18] [GPR_0381 : x28] [GPR_0380 : x27] [GPR_0379 : x26] [GPR_0378 : x25] [GPR_0375 : x2
4] [GPR_0374 : x23] [GPR_0373 : x22] [GPR_0372 : x21] [GPR_0348 : x7] [GPR_0347 : x6] [GPR_0344 : x5] [GPR_0343 : x4] [G
PR_0342 : x3] [GPR_0341 : x2] [GPR_0339 : x1] [GPR_0337 : x0] [FPR_0332 : d31] [FPR_0327 : d30] [FPR_0325 : d29] [FPR_03
77 : d28] [FPR_0376 : d27] [FPR_0371 : d26] [FPR_0370 : d25] [FPR_0369 : d24] [FPR_0368 : d23] [FPR_0367 : d22] [FPR_036
6 : d21] [FPR_0365 : d20] [FPR_0364 : d19] [FPR_0363 : d18] [FPR_0362 : d17] [FPR_0361 : d16] [FPR_0360 : d15] [FPR_0359
 : d14] [FPR_0358 : d13] [FPR_0357 : d12] [FPR_0356 : d11] [FPR_0355 : d10] [FPR_0354 : d9] [FPR_0353 : d8] [FPR_0352 : 
d7] [FPR_0351 : d6] [FPR_0350 : d5] [FPR_0349 : d4] [FPR_0346 : d3] [FPR_0345 : d2] [FPR_0340 : d1] [FPR_0338 : d0] 
POST: [&GPR_0208 : x15] [GPR_0331 : x14] [GPR_0330 : x13] [GPR_0329 : x12] [GPR_0328 : x11] [GPR_0326 : x10] [GPR_0324 :
 x9] [GPR_0383 : x8] [GPR_0382 : x18] [GPR_0381 : x28] [GPR_0380 : x27] [GPR_0379 : x26] [GPR_0378 : x25] [GPR_0375 : x2
4] [GPR_0374 : x23] [GPR_0373 : x22] [GPR_0372 : x21] [GPR_0348 : x7] [GPR_0347 : x6] [GPR_0344 : x5] [GPR_0343 : x4] [G
PR_0342 : x3] [GPR_0341 : x2] [GPR_0339 : x1] [GPR_0337 : x0] [FPR_0332 : d31] [FPR_0327 : d30] [FPR_0325 : d29] [FPR_03
77 : d28] [FPR_0376 : d27] [FPR_0371 : d26] [FPR_0370 : d25] [FPR_0369 : d24] [FPR_0368 : d23] [FPR_0367 : d22] [FPR_036
6 : d21] [FPR_0365 : d20] [FPR_0364 : d19] [FPR_0363 : d18] [FPR_0362 : d17] [FPR_0361 : d16] [FPR_0360 : d15] [FPR_0359
 : d14] [FPR_0358 : d13] [FPR_0357 : d12] [FPR_0356 : d11] [FPR_0355 : d10] [FPR_0354 : d9] [FPR_0353 : d8] [FPR_0352 : 
d7] [FPR_0351 : d6] [FPR_0350 : d5] [FPR_0349 : d4] [FPR_0346 : d3] [FPR_0345 : d2] [FPR_0340 : d1] [FPR_0338 : d0] 
    0xffff6660ea58 000007a4 [    0xffff64fe94b0] f947aa89 357   ldrimmx         w9, [w20, 3920]         ; spilled for if
icmpne          # SymRef  <#SPILL8_1441     0xffff64fd8c40>[#1441  Auto +3920] [flags 0x80000000 0x0 ]  
```

`ificmpHelper` checks if `GlRegDeps` node has too many registers, but it does not consider that `GlRegDeps` node has floating point registers.
https://github.com/eclipse/omr/blob/c818b04c631882b84760c759e9e85fa97ea7c106/compiler/aarch64/codegen/ControlFlowEvaluator.cpp#L146

**Comment by Akira1Saitoh** [comment]
10x Grinder passed with https://github.com/eclipse/omr/pull/6179. ` job/Grinder/18177/`

**Comment by 0xdaryl** [comment]
Fixed.
