### ISSUE TITLE
JDK17 aarch64_linux 0.28 release : DefaultStaticInvokeTest.java - InternalError: SIGBUS

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13508]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/45/`:
```
openjdk version "17-beta" 2021-09-14
IBM Semeru Runtime Open Edition 17.0.0.0-m1 (build 17-beta+35-202109140222)
Eclipse OpenJ9 VM 17.0.0.0-m1 (build openj9-0.28.0-m1, JRE 17 Linux aarch64-64-Bit Compressed References 20210914_31 (JIT enabled, AOT enabled)
OpenJ9   - 5eef84fb1
OMR      - 0bf455f83
JCL      - b6c1a570c77 based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_lang_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F31%2Fibm-semeru-open-testimage_aarch64_linux_JDK17_2021-09-14-02-17.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F31%2Fibm-semeru-open-jre_aarch64_linux_JDK17_2021-09-14-02-17.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F31%2Fibm-semeru-open-debugimage_aarch64_linux_JDK17_2021-09-14-02-17.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-aarch64-openj9%2F31%2Fibm-semeru-open-jdk_aarch64_linux_JDK17_2021-09-14-02-17.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=v0.28.0-release&amp;OPENJ9_BRANCH=v0.28.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.28.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-09-14T03:00:12.385Z] Running test jdk_lang_0 ...
[2021-09-14T03:00:12.385Z] ===============================================
[2021-09-14T03:00:12.385Z] jdk_lang_0 Start Time: Tue Sep 14 04:00:10 2021 Epoch Time (ms): 1631588410618
[2021-09-14T03:00:12.385Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-09-14T03:00:12.385Z] 
[2021-09-14T03:00:12.385Z] Attempting to destroy all caches in cacheDir /home/jenkins/javasharedresources/
[2021-09-14T03:00:12.385Z] 
[2021-09-14T03:00:12.385Z] JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
[2021-09-14T03:00:12.385Z] JVMSHRC005I No shared class caches available
[2021-09-14T03:00:12.385Z] cache cleanup done
[2021-09-14T03:00:12.385Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2021-09-14T03:00:12.385Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

[2021-09-14T03:19:16.385Z] --------------------------------------------------
[2021-09-14T03:19:16.385Z] TEST: java/lang/reflect/DefaultStaticTest/DefaultStaticInvokeTest.java

[2021-09-14T03:19:16.390Z] test DefaultStaticInvokeTest.testMethodHandleInvoke("TestClass7", "TestIF7.TestClass7"): failure
[2021-09-14T03:19:16.390Z] java.lang.InternalError: SIGBUS
[2021-09-14T03:19:16.390Z] 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
[2021-09-14T03:19:16.390Z] 	at java.lang.invoke.LambdaForm$MH/0x0000000004057060.invoke(LambdaForm$MH)
[2021-09-14T03:19:16.390Z] 	at java.lang.invoke.LambdaForm$MH/0x0000000004056070.invoke_MT(LambdaForm$MH)
[2021-09-14T03:19:16.390Z] 	at DefaultStaticInvokeTest.testMethodHandleInvoke(DefaultStaticInvokeTest.java:169)
[2021-09-14T03:19:16.390Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-14T03:19:16.390Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-14T03:19:16.390Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-14T03:19:16.390Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-09-14T03:19:16.390Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-09-14T03:19:16.390Z] 	at org.testng.TestRunner$$Lambda$138/0x0000000010e10a68.accept(Unknown Source)
[2021-09-14T03:19:16.390Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-09-14T03:19:16.390Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-09-14T03:19:16.390Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-09-14T03:19:16.390Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-09-14T03:19:16.390Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-09-14T03:19:16.390Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-09-14T03:19:16.390Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-09-14T03:19:16.390Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-09-14T03:19:16.390Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-09-14T03:19:16.390Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-09-14T03:19:16.390Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-09-14T03:19:16.390Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-09-14T03:19:16.390Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-09-14T03:19:16.390Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-09-14T03:19:16.390Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-14T03:19:16.390Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-14T03:19:16.390Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-14T03:19:16.390Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-14T03:19:16.390Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-09-14T03:19:16.390Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-09-14T03:19:16.390Z] test DefaultStaticInvokeTest.testMethodHandleInvoke("TestClass8", "TestIF8.TestClass8"): failure
[2021-09-14T03:19:16.390Z] java.lang.InternalError: SIGBUS
[2021-09-14T03:19:16.391Z] 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
[2021-09-14T03:19:16.391Z] 	at java.lang.invoke.LambdaForm$MH/0x0000000004057060.invoke(LambdaForm$MH)
[2021-09-14T03:19:16.391Z] 	at java.lang.invoke.LambdaForm$MH/0x0000000004056070.invoke_MT(LambdaForm$MH)
[2021-09-14T03:19:16.391Z] 	at DefaultStaticInvokeTest.testMethodHandleInvoke(DefaultStaticInvokeTest.java:169)
[2021-09-14T03:19:16.391Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-14T03:19:16.391Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-14T03:19:16.391Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-14T03:19:16.391Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-09-14T03:19:16.391Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-09-14T03:19:16.391Z] 	at org.testng.TestRunner$$Lambda$138/0x0000000010e10a68.accept(Unknown Source)
[2021-09-14T03:19:16.391Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-09-14T03:19:16.391Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-09-14T03:19:16.391Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-09-14T03:19:16.391Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-09-14T03:19:16.391Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-09-14T03:19:16.391Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-09-14T03:19:16.391Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-09-14T03:19:16.391Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-09-14T03:19:16.391Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-09-14T03:19:16.391Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-09-14T03:19:16.391Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-09-14T03:19:16.391Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-09-14T03:19:16.391Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-09-14T03:19:16.391Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-09-14T03:19:16.391Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-14T03:19:16.391Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-14T03:19:16.391Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-14T03:19:16.391Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-14T03:19:16.391Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-09-14T03:19:16.391Z] 	at java.base/java.lang.Thread.run(Thread.java:884)

[2021-09-14T03:19:16.392Z] ===============================================
[2021-09-14T03:19:16.392Z] java/lang/reflect/DefaultStaticTest/DefaultStaticInvokeTest.java
[2021-09-14T03:19:16.392Z] Total tests run: 276, Passes: 274, Failures: 2, Skips: 0
[2021-09-14T03:19:16.392Z] ===============================================
[2021-09-14T03:19:16.392Z] 
[2021-09-14T03:19:16.392Z] STDERR:
[2021-09-14T03:19:16.392Z] java.lang.Exception: failures: 2
[2021-09-14T03:19:16.392Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2021-09-14T03:19:16.392Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-14T03:19:16.392Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-14T03:19:16.392Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-14T03:19:16.392Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-14T03:19:16.392Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-09-14T03:19:16.392Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-09-14T03:19:16.392Z] 
[2021-09-14T03:19:16.392Z] JavaTest Message: Test threw exception: java.lang.Exception
[2021-09-14T03:19:16.392Z] JavaTest Message: shutting down test
[2021-09-14T03:19:16.392Z] 
[2021-09-14T03:19:16.392Z] 
[2021-09-14T03:19:16.392Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
[2021-09-14T03:19:16.392Z] --------------------------------------------------
[2021-09-14T03:23:25.233Z] Test results: passed: 805; failed: 1
[2021-09-14T03:23:47.716Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2021-09-14T03:23:47.716Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/aqa-tests/TKG/output_16315884102204/jdk_lang_0/work
[2021-09-14T03:23:47.716Z] Error: Some tests failed or other problems occurred.
[2021-09-14T03:23:47.716Z] 
[2021-09-14T03:23:47.716Z] jdk_lang_0_FAILED
```

This can be closed as dup of https://github.com/eclipse-openj9/openj9/issues/13472 if the investigation determines they were due to same underneath cause.

fyi @Akira1Saitoh

**Comment by JasonFengJ9** [comment]
Observed at `job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/51/` (`ub18-aarch64-9`)
```
openjdk version "17-beta" 2021-09-14
IBM Semeru Runtime Open Edition 17.0.0.0-m1 (build 17-beta+35-202109210406)
Eclipse OpenJ9 VM 17.0.0.0-m1 (build master-8d9ca8d9d, JRE 17 Linux aarch64-64-Bit Compressed References 20210921_40 (JIT enabled, AOT enabled)
OpenJ9   - 8d9ca8d9d
OMR      - e66945e01
JCL      - 23999d8072 based on jdk-17+35)

[2021-09-21T06:23:30.429Z] Running test jdk_lang_0 ...
[2021-09-21T06:23:30.429Z] ===============================================
[2021-09-21T06:23:30.429Z] jdk_lang_0 Start Time: Tue Sep 21 02:23:28 2021 Epoch Time (ms): 1632205408693
[2021-09-21T06:23:30.429Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-09-21T06:23:30.429Z] 
[2021-09-21T06:23:30.429Z] Attempting to destroy all caches in cacheDir /home/jenkins/javasharedresources/
[2021-09-21T06:23:30.429Z] 
[2021-09-21T06:23:30.429Z] JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
[2021-09-21T06:23:30.429Z] JVMSHRC005I No shared class caches available
[2021-09-21T06:23:30.429Z] cache cleanup done
[2021-09-21T06:23:30.429Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2021-09-21T06:23:30.429Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

[2021-09-21T06:38:21.989Z] --------------------------------------------------
[2021-09-21T06:38:21.989Z] TEST: java/lang/reflect/DefaultStaticTest/DefaultStaticInvokeTest.java

[2021-09-21T06:38:21.995Z] test DefaultStaticInvokeTest.testMethodHandleInvoke("TestClass8", "TestIF8.TestClass8"): failure
[2021-09-21T06:38:21.995Z] java.lang.InternalError: SIGBUS
[2021-09-21T06:38:21.995Z] 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
[2021-09-21T06:38:21.995Z] 	at <unknown class>.invoke(LambdaForm$MH)
[2021-09-21T06:38:21.995Z] 	at <unknown class>.invoke_MT(LambdaForm$MH)
[2021-09-21T06:38:21.995Z] 	at DefaultStaticInvokeTest.testMethodHandleInvoke(DefaultStaticInvokeTest.java:169)
[2021-09-21T06:38:21.995Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-21T06:38:21.995Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-21T06:38:21.995Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-21T06:38:21.995Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-09-21T06:38:21.995Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-09-21T06:38:21.995Z] 	at <unknown class>.accept(Unknown Source)
[2021-09-21T06:38:21.995Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-09-21T06:38:21.995Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-09-21T06:38:21.995Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-09-21T06:38:21.995Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-09-21T06:38:21.995Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-09-21T06:38:21.995Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-09-21T06:38:21.995Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-09-21T06:38:21.995Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-09-21T06:38:21.995Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-09-21T06:38:21.995Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-09-21T06:38:21.995Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-09-21T06:38:21.995Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-09-21T06:38:21.995Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-09-21T06:38:21.995Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-09-21T06:38:21.995Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-09-21T06:38:21.995Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-09-21T06:38:21.995Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-21T06:38:21.995Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-09-21T06:38:21.995Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-09-21T06:38:21.995Z] 	at java.base/java.lang.Thread.run(Thread.java:884)

[2021-09-21T06:38:21.996Z] ===============================================
[2021-09-21T06:38:21.996Z] java/lang/reflect/DefaultStaticTest/DefaultStaticInvokeTest.java
[2021-09-21T06:38:21.996Z] Total tests run: 276, Passes: 274, Failures: 2, Skips: 0
[2021-09-21T06:38:21.996Z] ===============================================

[2021-09-21T06:41:43.256Z] jdk_lang_0_FAILED
```

**Comment by 0xdaryl** [comment]
I'm closing this as a dup of #13472.
