### ISSUE TITLE
SharedClassesAPI_0 OutOfMemoryError 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13515]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/99 - win2012-x86-8
SharedClassesAPI_0 

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/99/system_test_output.tar.gz

68.WL4.stderr
```
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2021/09/15 00:35:15 - please wait.
```
```
STF 00:29:23.386 - +------ Step 69 - DefaultLocUtilitiesJVMTI: Monitor workload processes
STF 00:29:23.386 - | Wait for processes to meet expectations
STF 00:29:23.386 - |   Processes: [WL1, WL2, WL3, WL4]
STF 00:29:23.386 - |
STF 00:29:23.386 - Monitoring processes: WL1 WL2 WL3 WL4
STF 00:33:33.441 - Heartbeat: Process WL4 is still running
STF 00:35:27.941 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16316808228642\SharedClassesAPI_0\20210915-002829-SharedClassesAPI\results\core.20210915.003515.1564.0001.dmp
STF 00:35:42.276 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16316808228642\SharedClassesAPI_0\20210915-002829-SharedClassesAPI\results\heapdump.20210915.003515.1564.0002.phd
STF 00:36:00.035 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16316808228642\SharedClassesAPI_0\20210915-002829-SharedClassesAPI\results\javacore.20210915.003515.1564.0003.txt
STF 00:36:00.550 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16316808228642\SharedClassesAPI_0\20210915-002829-SharedClassesAPI\results\heapdump.20210915.003600.1564.0004.phd
STF 00:36:00.551 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16316808228642\SharedClassesAPI_0\20210915-002829-SharedClassesAPI\results\Snap.20210915.003515.1564.0005.trc
STF 00:36:18.222 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16316808228642\SharedClassesAPI_0\20210915-002829-SharedClassesAPI\results\javacore.20210915.003600.1564.0006.txt
STF 00:36:23.740 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16316808228642\SharedClassesAPI_0\20210915-002829-SharedClassesAPI\results\Snap.20210915.003600.1564.0007.trc
STF 00:36:29.146 - **FAILED** Process WL4 ended with exit code (1) and not the expected exit code/s (0)
STF 00:36:29.146 - Monitoring Report Summary:
STF 00:36:29.146 -   o Process WL1 ended with the expected exit code (0)
STF 00:36:29.146 -   o Process WL2 ended with the expected exit code (0)
STF 00:36:29.146 -   o Process WL3 ended with the expected exit code (0)
STF 00:36:29.146 -   o Process WL4 has crashed unexpectedly
STF 00:36:29.148 - Killing processes: WL1 WL2 WL3 WL4
STF 00:36:29.148 -   o Process WL1 pid 7096 is not running
STF 00:36:29.148 -   o Process WL4 pid 1564 is not running
STF 00:36:29.148 -   o Process WL3 pid 4452 is not running
STF 00:36:29.148 -   o Process WL2 pid 3812 is not running
**FAILED** at step 69 (DefaultLocUtilitiesJVMTI: Monitor workload processes). Expected return value=0 Actual=1 at F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/aqa-tests/\TKG\output_16316808228642\SharedClassesAPI_0/20210915-002829-SharedClassesAPI/execute.pl line 2386.
STF 00:36:29.269 - **FAILED** execute script failed. Expected return value=0 Actual=1
```
```
1STHEAPTYPE    Object Memory
NULL           id                 start              end                size               space/region
1STHEAPSPACE   0x00000027DDF5E050         --                 --                 --         Generational
1STHEAPREGION  0x00000027DDF393C0 0x00007FF6F73F0000 0x00007FF76F6D0000 0x00000000782E0000 Generational/Tenured Region
1STHEAPREGION  0x00000027DDF39C80 0x00007FF76F6D0000 0x00007FF7734D0000 0x0000000003E00000 Generational/Nursery Region
1STHEAPREGION  0x00000027DDF39BA0 0x00007FF7734D0000 0x00007FF7772D0000 0x0000000003E00000 Generational/Nursery Region
NULL
1STHEAPTOTAL   Total memory:                  2146304000 (0x000000007FEE0000)
1STHEAPINUSE   Total memory in use:           2124626216 (0x000000007EA33928)
1STHEAPFREE    Total memory free:               21677784 (0x00000000014AC6D8)
```
```
1STGCHTYPE     GC History
3STHSTTYPE     05:35:15:136799699 GMT j9mm.101 -   J9AllocateIndexableObject() returning NULL! 96 bytes requested for object of class 00000027F2E66600 from memory space 'Generational' id=00000027DDF5E050
3STHSTTYPE     05:35:15:136791219 GMT j9mm.84 -   Forcing J9AllocateIndexableObject() to fail due to excessive GC
3STHSTTYPE     05:35:15:136749220 GMT j9mm.134 -   Allocation failure end: newspace=4528/130023424 oldspace=21678128/2016280576 loa=20163584/20163584
3STHSTTYPE     05:35:15:136735060 GMT j9mm.69 -   Concurrent kickoff, tracesizetarget=2003129856 kickoffthreshold=260552144 remainingfree=4528
3STHSTTYPE     05:35:15:136699364 GMT j9mm.470 -   Allocation failure cycle end: newspace=4624/130023424 oldspace=21678128/2016280576 loa=20163584/20163584
3STHSTTYPE     05:35:15:136690676 GMT j9mm.82 -   Excessive GC raised!
3STHSTTYPE     05:35:15:136579110 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21682752/2146304000
3STHSTTYPE     05:35:15:136516967 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:35:15:136235852 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     05:35:10:910652549 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:35:10:910632885 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:35:10:892761347 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:35:10:892740676 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     05:35:10:892695572 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     05:35:10:892685189 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:35:08:789300555 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:35:08:789212508 GMT j9mm.474 -   GlobalGC start: globalcount=82
3STHSTTYPE     05:35:08:789187580 GMT j9mm.70 -   Concurrent aborted
3STHSTTYPE     05:35:08:789133581 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.139 meanexclusiveaccessms=0.080 threads=2 lastthreadtid=0x00000027DE30D900 beatenbyotherthread=0
3STHSTTYPE     05:35:08:789124846 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/130023424 oldspace=21678128/2016280576 loa=20163584/20163584 requestedbytes=96
3STHSTTYPE     05:35:08:789115614 GMT j9mm.133 -   Allocation failure start: newspace=0/130023424 oldspace=21678128/2016280576 loa=20163584/20163584 requestedbytes=96
3STHSTTYPE     05:35:08:788791139 GMT j9mm.134 -   Allocation failure end: newspace=4688/130023424 oldspace=21678128/2016280576 loa=20163584/20163584
3STHSTTYPE     05:35:08:788773923 GMT j9mm.69 -   Concurrent kickoff, tracesizetarget=2003129856 kickoffthreshold=260552144 remainingfree=4688
3STHSTTYPE     05:35:08:788739748 GMT j9mm.470 -   Allocation failure cycle end: newspace=4752/130023424 oldspace=21678128/2016280576 loa=20163584/20163584
3STHSTTYPE     05:35:08:788730788 GMT j9mm.82 -   Excessive GC raised!
3STHSTTYPE     05:35:08:788614086 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21682880/2146304000
3STHSTTYPE     05:35:08:788546615 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:35:08:788255851 GMT j9mm.137 -   Compact end: bytesmoved=24
3STHSTTYPE     05:35:04:656654389 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:35:04:656634133 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:35:04:639363706 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:35:04:639342810 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     05:35:04:639297707 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     05:35:04:639290171 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:35:02:635008047 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:35:02:634928369 GMT j9mm.474 -   GlobalGC start: globalcount=81
3STHSTTYPE     05:35:02:634903777 GMT j9mm.70 -   Concurrent aborted
3STHSTTYPE     05:35:02:634847522 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.071 meanexclusiveaccessms=0.048 threads=1 lastthreadtid=0x00000027DE30D900 beatenbyotherthread=0
3STHSTTYPE     05:35:02:634838386 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/130023424 oldspace=21678128/2016280576 loa=20163584/20163584 requestedbytes=64
3STHSTTYPE     05:35:02:634831010 GMT j9mm.133 -   Allocation failure start: newspace=0/130023424 oldspace=21678128/2016280576 loa=20163584/20163584 requestedbytes=64
3STHSTTYPE     05:35:02:634655557 GMT j9mm.101 -   J9AllocateIndexableObject() returning NULL! 104 bytes requested for object of class 00000027F2E66200 from memory space 'Generational' id=00000027DDF5E050
3STHSTTYPE     05:35:02:634630581 GMT j9mm.84 -   Forcing J9AllocateIndexableObject() to fail due to excessive GC
3STHSTTYPE     05:35:02:634585190 GMT j9mm.134 -   Allocation failure end: newspace=4672/130023424 oldspace=21678128/2016280576 loa=20163584/20163584
3STHSTTYPE     05:35:02:634569430 GMT j9mm.69 -   Concurrent kickoff, tracesizetarget=2003129856 kickoffthreshold=260552144 remainingfree=4672
3STHSTTYPE     05:35:02:634534599 GMT j9mm.470 -   Allocation failure cycle end: newspace=4776/130023424 oldspace=21678128/2016280576 loa=20163584/20163584
3STHSTTYPE     05:35:02:634524615 GMT j9mm.82 -   Excessive GC raised!
3STHSTTYPE     05:35:02:634411993 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21682904/2146304000
3STHSTTYPE     05:35:02:634358922 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:35:02:633999056 GMT j9mm.137 -   Compact end: bytesmoved=2054194392
3STHSTTYPE     05:34:26:068974240 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:34:26:068953472 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:34:26:052046703 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:34:26:052028735 GMT j9mm.94 -   Class unloading end: classloadersunloaded=4 classesunloaded=4
3STHSTTYPE     05:34:26:051193564 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     05:34:26:051185389 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:34:24:105736756 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:34:24:105631589 GMT j9mm.474 -   GlobalGC start: globalcount=80
3STHSTTYPE     05:34:24:105563302 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.090 meanexclusiveaccessms=0.055 threads=1 lastthreadtid=0x00000027F31A8700 beatenbyotherthread=0
3STHSTTYPE     05:34:24:105554439 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/130023424 oldspace=21557864/2016280576 loa=20163584/20163584 requestedbytes=104
3STHSTTYPE     05:34:24:105545335 GMT j9mm.133 -   Allocation failure start: newspace=0/130023424 oldspace=21557864/2016280576 loa=20163584/20163584 requestedbytes=104
3STHSTTYPE     05:34:24:105352954 GMT j9mm.134 -   Allocation failure end: newspace=0/130023424 oldspace=21557864/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:24:105321034 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/130023424 oldspace=21557864/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:24:105312107 GMT j9mm.82 -   Excessive GC raised!
3STHSTTYPE     05:34:24:105153757 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21557888/2146304000
3STHSTTYPE     05:34:24:105098734 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:34:24:104797523 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     05:34:23:400538391 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:34:23:400516311 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:34:23:383538983 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:34:23:383531495 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:34:21:480444456 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:34:21:480362394 GMT j9mm.474 -   GlobalGC start: globalcount=79
3STHSTTYPE     05:34:21:480301131 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.072 meanexclusiveaccessms=0.072 threads=0 lastthreadtid=0x00000027F31A8700 beatenbyotherthread=0
3STHSTTYPE     05:34:21:480293739 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/130023424 oldspace=21557888/2016280576 loa=20163584/20163584 requestedbytes=24
3STHSTTYPE     05:34:21:480245900 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/130023424 oldspace=21557888/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:21:480132781 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21557888/2146304000
3STHSTTYPE     05:34:21:480076446 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:34:21:479780979 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     05:34:20:754182669 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:34:20:754161629 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:34:20:737033023 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:34:20:737025423 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:34:18:809437129 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:34:18:809328330 GMT j9mm.474 -   GlobalGC start: globalcount=78
3STHSTTYPE     05:34:18:809258011 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.072 meanexclusiveaccessms=0.072 threads=0 lastthreadtid=0x00000027F31A8700 beatenbyotherthread=0
3STHSTTYPE     05:34:18:809250619 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/130023424 oldspace=21557888/2016280576 loa=20163584/20163584 requestedbytes=24
3STHSTTYPE     05:34:18:809242236 GMT j9mm.133 -   Allocation failure start: newspace=0/130023424 oldspace=21557888/2016280576 loa=20163584/20163584 requestedbytes=24
3STHSTTYPE     05:34:18:809078606 GMT j9mm.134 -   Allocation failure end: newspace=0/130023424 oldspace=21557888/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:18:809046719 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/130023424 oldspace=21557888/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:18:808873794 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21558712/2146304000
3STHSTTYPE     05:34:18:808818066 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:34:18:808522295 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     05:34:18:080169901 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:34:18:080149645 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:34:18:063108510 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:34:18:063099758 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:34:16:121725204 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:34:16:121640485 GMT j9mm.474 -   GlobalGC start: globalcount=77
3STHSTTYPE     05:34:16:121575590 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.040 meanexclusiveaccessms=0.040 threads=0 lastthreadtid=0x00000027DE21FA00 beatenbyotherthread=0
3STHSTTYPE     05:34:16:121568246 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/130023424 oldspace=21558712/2016280576 loa=20163584/20163584 requestedbytes=96
3STHSTTYPE     05:34:16:121519687 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/130023424 oldspace=21558712/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:16:121407321 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21558712/2146304000
3STHSTTYPE     05:34:16:121343914 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:34:16:120978112 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     05:34:15:384861666 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:34:15:384842226 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:34:15:367743380 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:34:15:367735684 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:34:13:460061183 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:34:13:459980576 GMT j9mm.474 -   GlobalGC start: globalcount=76
3STHSTTYPE     05:34:13:459920625 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.040 meanexclusiveaccessms=0.040 threads=0 lastthreadtid=0x00000027DE21FA00 beatenbyotherthread=0
3STHSTTYPE     05:34:13:459912001 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/130023424 oldspace=21558712/2016280576 loa=20163584/20163584 requestedbytes=96
3STHSTTYPE     05:34:13:459903713 GMT j9mm.133 -   Allocation failure start: newspace=0/130023424 oldspace=21558712/2016280576 loa=20163584/20163584 requestedbytes=96
3STHSTTYPE     05:34:13:459731940 GMT j9mm.134 -   Allocation failure end: newspace=0/130023424 oldspace=21558712/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:13:459700276 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/130023424 oldspace=21558712/2016280576 loa=20163584/20163584
3STHSTTYPE     05:34:13:459538791 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=21558744/2146304000
3STHSTTYPE     05:34:13:459486056 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     05:34:13:459194316 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     05:34:12:758804211 GMT j9mm.136 -   Compact start: reason=low free space (less than 4%)
3STHSTTYPE     05:34:12:758783939 GMT j9mm.57 -   Sweep end
3STHSTTYPE     05:34:12:741870626 GMT j9mm.56 -   Sweep start
3STHSTTYPE     05:34:12:741861762 GMT j9mm.55 -   Mark end
3STHSTTYPE     05:34:10:855907537 GMT j9mm.54 -   Mark start
3STHSTTYPE     05:34:10:855824946 GMT j9mm.474 -   GlobalGC start: globalcount=75
```

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by dmitripivkine** [comment]
This is a case GC throws OOM heap due excessive GC. Looks like this expected behaviour - GC struggles to collect something:
```
05:35:15.142376880 *0x0 j9mm.134             Event       Allocation failure end: newspace=4528/130023424 oldspace=21678128/2016280576 loa=20163584/20163584
05:35:15.142381488 *0x27DE21F000 j9vm.372             Entry      >Releasing exclusive VM Access
05:35:15.142385360  0x27DE21F000 j9vm.375             Event       Exclusive VM Access queue is empty, resetting exclusive access state and notifying all halted threads. Changing exclusiveAccessState to J9_XACCESS_NONE.
05:35:15.142409440  0x27DE21F000 j9vm.376             Exit       <Released exclusive VM Access
05:35:15.142415024  0x27DE21F000 j9mm.84              Event       Forcing J9AllocateIndexableObject() to fail due to excessive GC
05:35:15.142418880 *0x0 j9mm.84              Event       Forcing J9AllocateIndexableObject() to fail due to excessive GC
05:35:15.142422912 *0x27DE21F000 j9mm.101             Event       J9AllocateIndexableObject() returning NULL! 96 bytes requested for object of class 0x27f2e66600 from memory space 'Generational' id=0x27ddf5e050
```
This test does not specify `-Xmx` explicitly, so 25% of ~8g RAM is used. From ~2g of heap space available there is very little can be collected.

This is top of heap occupation report:
```
	 Total size of objects: 2057798672
	 Total number of objects: 55122753

        36716615           881198760  java/lang/Integer
        18358459          1174941376  java/util/TreeMap$Entry
```
so waste majority of the heap filled by `java/util/TreeMap$Entry` and `java/lang/Integer` objects

this is top of java stack for thread running test:
```
3XMTHREADINFO      "load-1" J9VMThread:0x00000027F31A7D00, omrthread_t:0x00000027F3298950, java/lang/Thread:0x00007FF6F76F3420, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1B, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x1220, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000001)
3XMCPUTIME               CPU usage total: 243.984375000 secs, user: 241.484375000 secs, system: 2.500000000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=280 (0x118)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/util/TreeMap.put(TreeMap.java:577(Compiled Code))
4XESTACKTRACE                at java/util/Collections$SynchronizedMap.put(Collections.java:2590(Compiled Code))
5XESTACKTRACE                   (entered lock: java/util/Collections$SynchronizedSortedMap@0x00007FF6F777D108, entry count: 1)
4XESTACKTRACE                at net/adoptopenjdk/test/util/treemap/TreeMapFactory.populateTree(TreeMapFactory.java:90(Compiled Code))
4XESTACKTRACE                at net/adoptopenjdk/test/util/treemap/TreeMapFactory.<clinit>(TreeMapFactory.java:59)
4XESTACKTRACE                at net/adoptopenjdk/test/util/treemap/TreeMapTest.testLocalTreeMap(TreeMapTest.java:37)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
4XESTACKTRACE                at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:498(Compiled Code))
4XESTACKTRACE                at junit/framework/TestCase.runTest(TestCase.java:176)
4XESTACKTRACE                at junit/framework/TestCase.runBare(TestCase.java:141)
4XESTACKTRACE                at junit/framework/TestResult$1.protect(TestResult.java:122)
4XESTACKTRACE                at junit/framework/TestResult.runProtected(TestResult.java:142)
4XESTACKTRACE                at junit/framework/TestResult.run(TestResult.java:125)
4XESTACKTRACE                at junit/framework/TestCase.run(TestCase.java:129)
```
so it is running `net/adoptopenjdk/test/util/treemap/TreeMapTest.testLocalTreeMap(TreeMapTest.java:37)`

I guess next step should be what test suppose to do? I guess it is building tree(s), so how heap memory limit is set? If test expects GC to clean dead objects continuously during test execution what prevents it? It may be extended liveness of the objects similar to https://github.com/eclipse-openj9/openj9/issues/9969 - so we can try `-Xjit:enableAggressiveLiveness` to verify it.

@pshipton I am not sure where to move from this point. We have very similar issue already https://github.com/eclipse-openj9/openj9/issues/9972, I think this is might be a duplicate. 
There is test source https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.test.util/src/test.util/net/adoptopenjdk/test/util/treemap/TreeMapTest.java

**Comment by pshipton** [comment]
If it's the same as #9972, it doesn't fail very often, I'm happy just to keep an eye on it, as long as it's not a regression from a recent change.
