### ISSUE TITLE
JDK17 aarch64_linux 0.28 release : jdk_util_0_FAILED - Segmentation error vmState=0x0005ff06

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13522]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/28/consoleFull`:
```
20:50:41  openjdk version "17-internal" 2021-09-14
20:50:41  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17aarch64linuxPersonal)
20:50:41  Eclipse OpenJ9 VM (build v0.28.0-release-1b582d44560, JRE 17 Linux aarch64-64-Bit Compressed References 20210915_57 (JIT enabled, AOT enabled)
20:50:41  OpenJ9   - 1b582d44560
20:50:41  OMR      - 73f36beab99
20:50:41  JCL      - 41171df43e2 based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_aarch64_linux_Personal%2F57%2FOpenJ9-JDK17-aarch64_linux-20210915-202810.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_aarch64_linux_Personal%2F57%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=v0.28.0-release&OPENJ9_SHA=1b582d44560424064eee17e6dc59d8bb142d9717&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=83285587d3e8588e6b013ff8de3418e45d31c945&JDK_BRANCH=v0.28.0-release&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
21:37:15  ===============================================
21:37:15  Running test jdk_util_0 ...
21:37:15  ===============================================
21:37:15  jdk_util_0 Start Time: Wed Sep 15 21:37:13 2021 Epoch Time (ms): 1631756233232
21:37:15  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
21:37:15  JVMSHRC005I No shared class caches available
21:37:15  JVMSHRC005I No shared class caches available
21:37:15  cache cleanup done
21:37:15  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
21:37:15  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

22:15:04  --------------------------------------------------
22:15:04  TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest.java

22:15:04  Unhandled exception
22:15:04  Type=Segmentation error vmState=0x0005ff06
22:15:04  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
22:15:04  Handler1=0000FFFFB9169368 Handler2=0000FFFFB90DF660 InaccessibleAddress=0000000000000020
22:15:04  R0=0000FFFF60405860 R1=0000000000000020 R2=0000FFFF604066B0 R3=0000FFFF60408110
22:15:04  R4=0000000000000004 R5=0000FFFF60407FF0 R6=000000000FE4CBFF R7=0000000000000001
22:15:04  R8=0000FFFF98E06250 R9=0000000000000080 R10=0000000A00000009 R11=0000F83200000001
22:15:04  R12=000000141FE40000 R13=0000001E00000015 R14=0000000000000000 R15=0000000000000000
22:15:04  R16=0000FFFFB3FCB010 R17=0000FFFFB9EEAF90 R18=0000FFFFB9FBBA70 R19=0000000000000001
22:15:04  R20=0000000000000000 R21=0000FFFF604065A0 R22=000000000000001F R23=0000FFFF60405860
22:15:04  R24=0000000000000000 R25=0000FFFF60816060 R26=0000FFFF60750050 R27=0000000000000001
22:15:04  R28=0000000000000000 R29=0000FFFF98E08FA0 R30=0000FFFFB3D78410 R31=0000FFFF98E061D0
22:15:04  PC=0000FFFFB3D7864C SP=0000FFFF98E061D0 PSTATE=0000000080000000
22:15:04  V0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V1 b963209800000000 (f: 0.000000, d: -2.947030e-32)
22:15:04  V2 0000ffffb9632098 (f: 3110281472.000000, d: 1.390665e-309)
22:15:04  V3 0000000200000001 (f: 1.000000, d: 4.243992e-314)
22:15:04  V4 0000000000000016 (f: 22.000000, d: 1.086944e-322)
22:15:04  V5 0000000400000004 (f: 4.000000, d: 8.487983e-314)
22:15:04  V6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V16 4010040140100401 (f: 1074791424.000000, d: 4.003911e+00)
22:15:04  V17 0000000488000880 (f: 2281703424.000000, d: 9.615295e-314)
22:15:04  V18 0000000000000400 (f: 1024.000000, d: 5.059232e-321)
22:15:04  V19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  V31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:15:04  Module=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so
22:15:04  Module_base_address=0000FFFFB364B000
22:15:04  
22:15:04  Method_being_compiled=jdk/internal/reflect/GeneratedMethodAccessor8.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
22:15:04  Target=2_90_20210915_57 (Linux 4.15.0-112-generic)
22:15:04  CPU=aarch64 (8 logical CPUs) (0x1f2618000 RAM)
22:15:04  ----------- Stack Backtrace -----------
22:15:04  (0x0000FFFFB90DC2B8 [libj9prt29.so+0x262b8])
22:15:04  ---------------------------------------
22:15:04  JVMDUMP039I Processing dump event "gpf", detail "" at 2021/09/15 21:58:40 - please wait.
22:15:04  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest/core.20210915.215840.12685.0001.dmp' in response to an event
22:15:04  JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.12729.
22:15:04  
22:15:04  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest/core.20210915.215840.12685.0001.dmp
22:15:04  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest/javacore.20210915.215840.12685.0002.txt' in response to an event
22:15:04  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest/javacore.20210915.215840.12685.0002.txt
22:15:04  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest/Snap.20210915.215840.12685.0003.trc' in response to an event
22:15:04  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest/Snap.20210915.215840.12685.0003.trc
22:15:04  JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest/jitdump.20210915.215840.12685.0004.dmp' in response to an event
22:15:04  JVMDUMP051I JIT dump occurred in 'JIT Compilation Thread-000' thread 0x0000000000013700
22:15:04  JVMDUMP049I JIT dump notified all waiting threads of the current method to be compiled
22:15:04  JVMDUMP054I JIT dump is tracing the IL of the method on the crashed compilation thread
22:15:04  JVMDUMP052I JIT dump recursive crash occurred on diagnostic thread
22:15:04  JVMDUMP048I JIT dump method being compiled is an ordinary method
22:15:04  JVMDUMP053I JIT dump is recompiling jdk/internal/reflect/GeneratedMethodAccessor8.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
22:15:04  *** stack smashing detected ***: <unknown> terminated
22:15:04  JVMDUMP039I Processing dump event "abort", detail "" at 2021/09/15 21:58:45 - please wait.

22:15:04  TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 977253ms).
22:15:04  --------------------------------------------------
22:21:48  Test results: passed: 885; error: 1
22:22:10  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/jvmtest/openjdk/report/html/report.html
22:22:10  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16317536095695/jdk_util_0/work
22:22:10  Error: Some tests failed or other problems occurred.
22:22:10  
22:22:10  jdk_util_0_FAILED
```

fyi @Akira1Saitoh

**Comment by Akira1Saitoh** [comment]
This issue is same as https://github.com/eclipse-openj9/openj9/issues/13502
https://github.com/eclipse/omr/pull/6179 will fix this.

The crash occurs at `OMR::ARM64::Machine::freeBestRegister` and the reason is that there are no available registers to free.

```
#13 OMR::ARM64::Machine::freeBestRegister (this=this@entry=0xffff604065a0,                                              
    currentInstruction=currentInstruction@entry=0xffff60816060, virtualRegister=virtualRegister@entry=0xffff60811730,   
    forced=forced@entry=0x0)                                                                                            
    at /home/jenkins/workspace/Build_JDK17_aarch64_linux_Personal/omr/compiler/aarch64/codegen/OMRMachine.cpp:314       
#14 0x0000ffffb3d7a948 in OMR::ARM64::Machine::assignOneRegister (this=this@entry=0xffff604065a0,                       
    currentInstruction=currentInstruction@entry=0xffff60816060, virtualRegister=virtualRegister@entry=0xffff60811730)   
    at /home/jenkins/workspace/Build_JDK17_aarch64_linux_Personal/omr/compiler/aarch64/codegen/OMRMachine.cpp:632       
#15 0x0000ffffb3d55640 in TR::ARM64CompareBranchInstruction::assignRegisters (this=0xffff60816060,                      
    kindToBeAssigned=TR_GPR)                                                                                            
    at /home/jenkins/workspace/Build_JDK17_aarch64_linux_Personal/omr/compiler/aarch64/codegen/ARM64Instruction.cpp:746 

(gdb) up 13                                                                                                             
#13 OMR::ARM64::Machine::freeBestRegister (this=this@entry=0xffff604065a0,                                              
    currentInstruction=currentInstruction@entry=0xffff60816060, virtualRegister=virtualRegister@entry=0xffff60811730,   
    forced=forced@entry=0x0)                                                                                            
    at /home/jenkins/workspace/Build_JDK17_aarch64_linux_Personal/omr/compiler/aarch64/codegen/OMRMachine.cpp:314                                              
(gdb) p candidates[0]                                                                                                   
$1 = (TR::Register *) 0x0 
```

The register dependency of the instruction has 25 integer register entries which means there are no more available integer registers.
Because https://github.com/eclipse/omr/pull/6178 changed `TR::ARM64CompareBranchInstruction::assignRegisters` to block virtual regs in register dependency before assigning source1Register,
it now crashes when the register dependency has too many registers. Previously, the register assigned to the register dependency was spilled and incorrect code was generated (as in https://github.com/eclipse-openj9/openj9/issues/13502).
https://github.com/eclipse/omr/pull/6179 prevents too many registers are added to the register dependency for compare branch instructions.

```
(gdb) up                                                                                                                
#15 0x0000ffffb3d55640 in TR::ARM64CompareBranchInstruction::assignRegisters (this=0xffff60816060,                      
    kindToBeAssigned=TR_GPR)                                                                                            
    at /home/jenkins/workspace/Build_JDK17_aarch64_linux_Personal/omr/compiler/aarch64/codegen/ARM64Instruction.cpp:746
746     /home/jenkins/workspace/Build_JDK17_aarch64_linux_Personal/omr/compiler/aarch64/codegen/ARM64Instruction.cpp: N$
 such file or directory.
(gdb) p this
$2 = (TR::ARM64CompareBranchInstruction * const) 0xffff60816060

(gdb) p *this->_conditions
$5 = {<OMR::ARM64::RegisterDependencyConditions> = {<OMR::RegisterDependencyConditions> = {<No data fields>},
    _preConditions = 0xffff608155a0, _postConditions = 0xffff60815840, _numPreConditions = 28, _addCursorForPre = 28,
    _numPostConditions = 28, _addCursorForPost = 28}, <No data fields>}

(gdb) p this->_conditions->_postConditions->_dependencies[0]                                                            
$7 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080de10,                                
    _realRegister = OMR::RealRegister::x15}, <No data fields>}                                                          
(gdb) p this->_conditions->_postConditions->_dependencies[1]                                                            
$8 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080dc50,                                
    _realRegister = OMR::RealRegister::x14}, <No data fields>}                                                          
(gdb) p this->_conditions->_postConditions->_dependencies[2]                                                            
$9 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff60815b00,                                
    _realRegister = OMR::RealRegister::x13}, <No data fields>}                                                          
(gdb) p this->_conditions->_postConditions->_dependencies[3]                                                            
$10 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff60815c00,                               
    _realRegister = OMR::RealRegister::x12}, <No data fields>}                                                          
(gdb) p this->_conditions->_postConditions->_dependencies[4]                                                            
$11 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff60810ed0,
    _realRegister = OMR::RealRegister::x11}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[5]
$12 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff60815d10,
    _realRegister = OMR::RealRegister::x10}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[6]
$13 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080dcc0,
    _realRegister = OMR::RealRegister::x9}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[7]
$14 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080dd30,
    _realRegister = OMR::RealRegister::x8}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[8]
$15 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080dda0,
    _realRegister = OMR::RealRegister::x18}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[9]
$16 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff60815e40,
    _realRegister = OMR::RealRegister::x28}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[10]
$17 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080de80,
    _realRegister = OMR::RealRegister::x27}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[11]
$18 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080def0,
    _realRegister = OMR::RealRegister::x26}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[12]
$19 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080df60,
    _realRegister = OMR::RealRegister::x25}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[13]
$20 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080dfd0,
    _realRegister = OMR::RealRegister::x24}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[14
A syntax error in expression, near `'.
(gdb) p this->_conditions->_postConditions->_dependencies[14]
$21 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e040,
    _realRegister = OMR::RealRegister::x23}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[15]
$22 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e0b0,
    _realRegister = OMR::RealRegister::x22}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[16]
$23 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e120,
    _realRegister = OMR::RealRegister::x21}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[17]
$24 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e190,
    _realRegister = OMR::RealRegister::x7}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[18]
$25 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e200,
    _realRegister = OMR::RealRegister::x6}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[19]
$26 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e270,
    _realRegister = OMR::RealRegister::x5}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[20]
$27 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e2e0,
    _realRegister = OMR::RealRegister::x4}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[21]
$28 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e350,
    _realRegister = OMR::RealRegister::x3}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[22]
$29 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e3c0,
    _realRegister = OMR::RealRegister::x2}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[23]
$30 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e430,
    _realRegister = OMR::RealRegister::x1}, <No data fields>}
(gdb) p this->_conditions->_postConditions->_dependencies[24]
$31 = {<OMR::RegisterDependency> = {_flags = 3 '\003', _virtualRegister = 0xffff6080e4a0,
    _realRegister = OMR::RealRegister::x0}, <No data fields>}
```

The corresponding IL  in jitdump seems to be 
```
 n2510n   (  0)  ificmpeq --> block_208 BBStart at n2519n ()                                          [    0xffff91272050] bci=[18,25,3545
] rc=0 vc=5277 vn=- li=85 udi=- nc=3 flg=0x20
 n2508n   (  0)    instanceof  jitInstanceOf[#87  helper Method] [flags 0x400 0x0 ] (in GPR_    0xffff917c1a20)  [    0xffff91021fa0] bci=
[18,25,3545] rc=0 vc=5277 vn=- li=85 udi=6688 nc=2
 n2911n   (  3)      ==>aRegLoad (in &GPR_    0xffff917bb8e0) (X!=0 SeenRealReference sharedMemory )
 n2507n   (  0)      aloadi  <vft-symbol>[#250  Shadow] [flags 0x18607 0x0 ] (in GPR_    0xffff917c1c60) (X!=0 sharedMemory )  [    0xffff
91021f50] bci=[18,27,3545] rc=0 vc=5277 vn=- li=85 udi=7264 nc=1 flg=0x4
 n2907n   (  6)        ==>aRegLoad (in &GPR_    0xffff917bb720) (X!=0 X>=0 SeenRealReference sharedMemory )
 n1429n   (  1)    ==>iconst 0 (X==0 X>=0 X<=0 )
 n2945n   (  0)    GlRegDeps ()                                                                       [    0xffff9127a840] bci=[18,25,3545
] rc=0 vc=5277 vn=- li=85 udi=- nc=28 flg=0x20
 n2939n   (  0)      PassThrough x15                                                                  [    0xffff9127a660] bci=[18,29,3545
] rc=0 vc=5277 vn=- li=85 udi=47328 nc=1
 n2911n   (  3)        ==>aRegLoad (in &GPR_    0xffff917bb8e0) (X!=0 SeenRealReference sharedMemory )
 n2940n   (  0)      PassThrough x14                                                                  [    0xffff9127a6b0] bci=[18,10,3543
] rc=0 vc=5277 vn=- li=85 udi=46880 nc=1
 n2907n   (  6)        ==>aRegLoad (in &GPR_    0xffff917bb720) (X!=0 X>=0 SeenRealReference sharedMemory )
 n2941n   (  0)      PassThrough x13                                                                  [    0xffff9127a700] bci=[18,29,3545
] rc=0 vc=5277 vn=- li=85 udi=47328 nc=1
 n2911n   (  3)        ==>aRegLoad (in &GPR_    0xffff917bb8e0) (X!=0 SeenRealReference sharedMemory )
 n2942n   (  0)      PassThrough x12                                                                  [    0xffff9127a750] bci=[18,10,3543
] rc=0 vc=5277 vn=- li=85 udi=46880 nc=1
 n2907n   (  6)        ==>aRegLoad (in &GPR_    0xffff917bb720) (X!=0 X>=0 SeenRealReference sharedMemory )
 n2943n   (  0)      PassThrough x11                                                                  [    0xffff9127a7a0] bci=[18,32,3546
] rc=0 vc=5277 vn=- li=85 udi=1360 nc=1
 n2438n   (  1)        ==>lshl (in GPR_    0xffff917c0550) (X>=0 cannotOverflow )
 n2944n   (  0)      PassThrough x10                                                                  [    0xffff9127a7f0] bci=[18,10,3543
] rc=0 vc=5277 vn=- li=85 udi=46880 nc=1
 n2907n   (  6)        ==>aRegLoad (in &GPR_    0xffff917bb720) (X!=0 X>=0 SeenRealReference sharedMemory )
 n2908n   (  1)      ==>iRegLoad (in GPR_    0xffff917bb790) (X>=0 cannotOverflow SeenRealReference )
 n2909n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bb800)
 n2910n   (  2)      ==>aRegLoad (in &GPR_    0xffff917bb870) (X!=0 X>=0 SeenRealReference sharedMemory )
 n2911n   (  3)      ==>aRegLoad (in &GPR_    0xffff917bb8e0) (X!=0 SeenRealReference sharedMemory )
 n2912n   (  1)      ==>iRegLoad (in GPR_    0xffff917bb950)
 n2913n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bb9c0)
 n2914n   (  1)      ==>iRegLoad (in GPR_    0xffff917bba30)
 n2915n   (  2)      ==>aRegLoad (in &GPR_    0xffff917bbaa0)
 n2916n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbb10)
 n2917n   (  2)      ==>aRegLoad (in &GPR_    0xffff917bbb80)
 n2918n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbbf0)
 n2919n   (  2)      ==>iRegLoad (in GPR_    0xffff917bbc60)
 n2920n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbcd0)
 n2921n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbd40)
 n2922n   (  1)      ==>lRegLoad (in GPR_    0xffff917bbdb0)
 n2923n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbe20)
 n2924n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbe90)
 n2925n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbf00)
 n2926n   (  1)      ==>aRegLoad (in &GPR_    0xffff917bbf70)
 n2927n   (  1)      ==>dRegLoad (in FPR_    0xffff917bbfe0)
 n2928n   (  1)      ==>dRegLoad (in FPR_    0xffff917bc050)
 n2929n   (  1)      ==>dRegLoad (in FPR_    0xffff917bc0c0)
```

**Comment by 0xdaryl** [comment]
Closing as dup of 13502.
