### ISSUE TITLE
JDK17 TestIBMJlmRemoteClassNoAuth_0_FAILED - NullPointerException: Cannot invoke "javax.management.MBeanServerConnection.isInstanceOf(javax.management.ObjectName, java.lang.String)" because "connection" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13523]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.system_x86-64_linux_testList_2/53/`:
```
openjdk version "17-beta" 2021-09-14
IBM Semeru Runtime Open Edition 17.0.0.0-m1 (build 17-beta+35-202109160425)
Eclipse OpenJ9 VM 17.0.0.0-m1 (build master-3b519ed3e, JRE 17 Linux amd64-64-Bit Compressed References 20210916_36 (JIT enabled, AOT enabled)
OpenJ9   - 3b519ed3e
OMR      - c818b04c6
JCL      - 23999d8072 based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=TestIBMJlmRemoteClassNoAuth_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.system_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F36%2Fibm-semeru-open-jdk_x64_linux_JDK17_2021-09-16-04-19.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F36%2Fibm-semeru-open-jre_x64_linux_JDK17_2021-09-16-04-19.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F36%2Fibm-semeru-open-debugimage_x64_linux_JDK17_2021-09-16-04-19.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17%2Fjdk17-linux-x64-openj9%2F36%2Fibm-semeru-open-testimage_x64_linux_JDK17_2021-09-16-04-19.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=54&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) 

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-09-16T06:35:05.756Z] Running test TestIBMJlmRemoteClassNoAuth_0 ...
[2021-09-16T06:35:05.756Z] ===============================================
[2021-09-16T06:35:05.756Z] TestIBMJlmRemoteClassNoAuth_0 Start Time: Thu Sep 16 02:35:02 2021 Epoch Time (ms): 1631774102132
[2021-09-16T06:35:05.756Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_x86-64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_x86-64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-09-16T06:35:05.756Z] JVMSHRC005I No shared class caches available
[2021-09-16T06:35:05.756Z] JVMSHRC005I No shared class caches available
[2021-09-16T06:35:05.756Z] cache cleanup done
[2021-09-16T06:35:05.756Z] variation: Mode110
[2021-09-16T06:35:05.756Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

[2021-09-16T06:37:36.089Z] CL1 j> 2021/09/16 02:37:32.885 Failed to connect to Monitored VM after 30 attempts in 147 seconds - giving up.  Connection Exception received is below:
[2021-09-16T06:37:36.089Z] CL1 stderr java.rmi.ConnectException: Connection refused to host: 9.24.248.182; nested exception is: 
[2021-09-16T06:37:36.089Z] CL1 stderr 	java.net.ConnectException: Connection refused
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:626)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:133)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2107)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.doConnect(ServerConnector.java:276)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.getServerConnection(ServerConnector.java:101)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.<init>(ServerConnector.java:63)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.<init>(ClassProfiler.java:59)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:87)
[2021-09-16T06:37:36.089Z] CL1 stderr Caused by: java.net.ConnectException: Connection refused
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/java.net.Socket.connect(Socket.java:633)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/java.net.Socket.connect(Socket.java:583)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/java.net.Socket.<init>(Socket.java:507)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.base/java.net.Socket.<init>(Socket.java:287)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:620)
[2021-09-16T06:37:36.089Z] CL1 stderr 	... 13 more
[2021-09-16T06:37:36.089Z] CL1 stderr Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.management.MBeanServerConnection.isInstanceOf(javax.management.ObjectName, java.lang.String)" because "connection" is null
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:652)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:612)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:110)
[2021-09-16T06:37:36.089Z] CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:97)
[2021-09-16T06:37:36.089Z] STF 02:37:33.258 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
[2021-09-16T06:37:36.089Z] STF 02:37:33.258 - Monitoring Report Summary:
[2021-09-16T06:37:36.089Z] STF 02:37:33.258 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
[2021-09-16T06:37:36.089Z] STF 02:37:33.258 -   o Process LT1 is still running as expected
[2021-09-16T06:37:36.089Z] STF 02:37:33.258 - Killing processes: CL1 LT1
[2021-09-16T06:37:36.089Z] STF 02:37:33.258 -   o Process LT1 pid 12443 stop()
[2021-09-16T06:37:45.678Z] STF 02:37:43.295 -   o Process LT1 pid 12443 terminate()
[2021-09-16T06:37:45.678Z] STF 02:37:44.296 -   o Process LT1 pid 12443 killed
[2021-09-16T06:37:45.678Z] STF 02:37:44.296 -   o Process CL1 pid 12444 is not running
[2021-09-16T06:37:45.678Z] **FAILED** at step 3 (Wait for processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk17_j9_sanity.system_x86-64_linux_testList_2/aqa-tests/TKG/../TKG/output_16317714742261/TestIBMJlmRemoteClassNoAuth_0/20210916-023502-TestIBMJlmRemoteClassNoAuth/execute.pl line 163.
[2021-09-16T06:37:45.678Z] STF 02:37:44.393 - **FAILED** execute script failed. Expected return value=0 Actual=1
[2021-09-16T06:37:45.678Z] STF 02:37:44.393 - 
[2021-09-16T06:37:45.678Z] STF 02:37:44.393 - ====================   T E A R D O W N   ====================
[2021-09-16T06:37:45.678Z] STF 02:37:44.393 - Running teardown: perl /home/jenkins/workspace/Test_openjdk17_j9_sanity.system_x86-64_linux_testList_2/aqa-tests/TKG/../TKG/output_16317714742261/TestIBMJlmRemoteClassNoAuth_0/20210916-023502-TestIBMJlmRemoteClassNoAuth/tearDown.pl
[2021-09-16T06:37:45.678Z] STF 02:37:44.433 - TEARDOWN stage completed
[2021-09-16T06:37:45.678Z] STF 02:37:44.437 - 
[2021-09-16T06:37:45.678Z] STF 02:37:44.438 - =====================   R E S U L T S   =====================
[2021-09-16T06:37:45.678Z] STF 02:37:44.438 - Stage results:
[2021-09-16T06:37:45.678Z] STF 02:37:44.438 -   setUp:     pass
[2021-09-16T06:37:45.678Z] STF 02:37:44.438 -   execute:  *fail*
[2021-09-16T06:37:45.678Z] STF 02:37:44.438 -   teardown:  pass
[2021-09-16T06:37:45.678Z] STF 02:37:44.438 - 
[2021-09-16T06:37:45.678Z] STF 02:37:44.438 - Overall result: **FAILED**
[2021-09-16T06:37:45.678Z] 
[2021-09-16T06:37:45.678Z] TestIBMJlmRemoteClassNoAuth_0_FAILED
```

Similar NPEs observed at `TestJlmRemoteClassAuth_1`, `TestJlmRemoteMemoryNoAuth_1`, and a few others.

The failure could be dup of known NPEs being investigated: https://github.com/eclipse-openj9/openj9/issues/13167, https://github.com/eclipse-openj9/openj9/issues/13162, or https://github.com/eclipse-openj9/openj9/issues/13485.
Creating this issue to track those test suites w/ slightly different NPE stack-traces.

**Edit**: it might be a legitimate NPE due to machine/network setup issue.

**Comment by pshipton** [comment]
> it might be a legitimate NPE due to machine/network setup issue

Ya, it seems like a network issue.

**Comment by JasonFengJ9** [comment]
Observed at JDK11 as well `job/Test_openjdk11_j9_sanity.system_x86-64_linux_testList_2/85/`

Moving out current milestone plan.

**Comment by JasonFengJ9** [comment]
It only occurred at `rhel7x64cudart1`, created `infrastructure/issues/5948`.
