### ISSUE TITLE
Classload failure when replacing defineAnonClass with defineHidden class

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13529]
An issue occurs with the following test

```
protected static NodeInterface getAnonInvoker() throws IllegalAccessException, IOException, InstantiationException {
		String resource = NodeClass.class.getName().replace('.', '/') + ".class";
		InputStream classFile = j9vm.test.invoker.NodeClass.class.getClassLoader().getResourceAsStream(resource);
		byte[] classFileBytes = new byte[classFile.available()];
		classFile.read(classFileBytes);
		
		Unsafe unsafe = getUnsafeInstance();
		NodeInterface anonInvoker = (NodeInterface)unsafe.defineAnonymousClass(NodeInterface.class, classFileBytes, null).newInstance();
		return anonInvoker;
	}
```

NodeClass is defined as:

```
class j9vm/test/invoker/NodeClass
	implements j9vm/test/invoker/NodeInterface
	version 52:0
{

public Method <init>:"()V"
	stack 1 locals 2
{
	aload_0;
	invokespecial Method java/lang/Object."<init>":"()V";
	return;
}

public Method callRootIdentity:"(Ljava/lang/Object;)Ljava/lang/Boolean;" 
	stack 2 locals 3
{
	/* aload_0 replaced with aload_1 change receiver */
	aload 1;
	invokespecial InterfaceMethod j9vm/test/invoker/Root.identity:"()Ljava/lang/Boolean;";
	areturn;
}

}
```

When one attempts to replace defineAnonClass with defineHidden class.

The failure is:
```
java.lang.NoClassDefFoundError: j9vm.test.invoker.NodeClass.0x0000000000000000
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:529)
	at java.base/java.lang.Access.defineClass(Access.java:336)
	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2445)
	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClassAsLookup(MethodHandles.java:2426)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineHiddenClass(MethodHandles.java:2133)
	at org.openj9.test.access.UnsafeClasses.defineAnonOrHiddenClass(UnsafeClasses.java:47)
	at j9vm.test.invoker.InvokeSpecialInsideInterface.getAnonInvoker(InvokeSpecialInsideInterface.java:132)
	at j9vm.test.invoker.InvokeSpecialInsideInterface.invokeSpecialInsideInterface(InvokeSpecialInsideInterface.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.ClassNotFoundException: j9vm.test.invoker.NodeClass.0x0000000000000000
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:827)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1113)
	at java.base/java.lang.ClassLoader.defineClassImpl1(Native Method)
	... 32 more
```

The VM is looking for a class named `j9vm.test.invoker.NodeClass.0x0000000000000000` but it should really be looking for `j9vm.test.invoker.NodeClass/0x0000000000000000`

So there is an issue with the self reference in the constantPool. I recommend starting the investigation by looking at https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/classsupport.c#L383

We need to patch all self references in the constantPool because the class (hidden/anon) are not searchable.

**Comment by tajila** [comment]
@hangshao0 Please take a look at this. It is blocking https://github.com/eclipse-openj9/openj9/pull/13426

**Comment by hangshao0** [comment]
I am in the middle of https://github.com/eclipse-openj9/openj9/issues/13414, will look at this issue after that.

**Comment by keithc-ca** [comment]
Once this is is resolved, the test for jdk17+ in https://github.com/eclipse-openj9/openj9/blob/master/test/functional/Java8andUp/src/j9vm/test/invoker/InvokeSpecialInsideInterface.java#L71 can be removed.

**Comment by hangshao0** [comment]
I've added some printf around https://github.com/eclipse-openj9/openj9/blob/48cba43acd80cb831e81264788520f6c045b6b16/runtime/vm/classsupport.c#L387
It seems that the issue is not caused by the `/` vs `.` in the class name.

One difference between unsafe anon classes and hidden classes is verification. We will verify hidden classes, but not unsafe anon classes. In java 17 and up, an exception is set by `performVerification()` here: https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/ClassInitialization.cpp#L488, which triggered `NoClassDefFoundError` and make `defineHiddenClass()` to fail. 

Tried on RI, `NodeClass` won't pass verification there either, `defineHiddenClass()` also failed, but RI throws a `VerfiyError`. 

So we may need to look at whether the test still applies to Java 17 and up. If yes, this test needs to find another way (if possible) to define `NodeClass` class. This class is not able to be defined via `defineHiddenClass()`.

**Comment by tajila** [comment]
Can you please post the cause of the verification failure? What is wrong with the class file that is causing it to fail.

**Comment by hangshao0** [comment]
Here it is:

```
java.lang.VerifyError: Bad invokespecial instruction: interface method reference is in an indirect superinterface.
Exception Details:
  Location:
    j9vm/test/invoker/NodeClass+0x0000000800cac400.callRootIdentity(Ljava/lang/Object;)Ljava/lang/Boolean; @2: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 1901 b700 02b0

        at java.base/java.lang.ClassLoader.defineClass0(Native Method)
        at java.base/java.lang.System$2.defineClass(System.java:2307)
        at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2439)
        at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClassAsLookup(MethodHandles.java:2420)
        at java.base/java.lang.invoke.MethodHandles$Lookup.defineHiddenClass(MethodHandles.java:2127)
        at org.openj9.test.access.UnsafeClasses.defineAnonOrHiddenClass(UnsafeClasses.java:47)
        at j9vm.test.invoker.InvokeSpecialInsideInterface.getAnonInvoker(InvokeSpecialInsideInterface.java:131)
        at j9vm.test.invoker.InvokeSpecialInsideInterface.invokeSpecialInsideInterface(InvokeSpecialInsideInterface.java:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        ...
```
