### ISSUE TITLE
ValueTypes: Valhalla functional tests fail due to java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by a7ehuo** [eclipse-openj9/openj9#13547]
Valhalla functional tests fail due to  `java.lang.NoSuchMethodException`. 

To reproduce the failures, https://github.com/eclipse-openj9/openj9/commit/5ec05b264432095ccda668129c3900b55671b89b is required to bypass Valhalla build failure tracked in #13540

```
===========================
OpenJ9 - d7ee310a3cd697b329a0246715a563b07dc9c641
OMR    - 9494694dc394aa5dce88fb4d101a9a7ed17ca38b
JCL    - 39cfb7b62bc based on jdk-18+15
===========================
```

```
===============================================
Running test ValueTypeTests_0 ...
===============================================
ValueTypeTests_0 Start Time: Wed Sep 22 10:57:45 2021 Epoch Time (ms): 1632333465308
"/root/home/ahuo/src/openj9-openjdk-jdk/build/linux-x86_64-server-release/images/jdk/bin/java" -Xshareclasses:destroyAll; "/root/home/ahuo/src/openj9-openjdk-jdk/build/linux-x86_64-server-release/images/jdk/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";

Attempting to destroy all caches in cacheDir /root/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_root" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC806I Compressed references persistent shared cache "sharedcc_root" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC005I No shared class caches available
cache cleanup done
variation: -Xgcpolicy:optthruput
JVM_OPTIONS:  -Xgcpolicy:optthruput  -Xrs 
{ itercnt=1; \
mkdir -p "/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TKG/output_16323334643752/ValueTypeTests_0"; \
cd "/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TKG/output_16323334643752/ValueTypeTests_0"; \
"/root/home/ahuo/src/openj9-openjdk-jdk/build/linux-x86_64-server-release/images/jdk/bin/java"  -Xgcpolicy:optthruput  -Xrs  \
	-Xverify:none \
	-Xint \
	--add-opens java.base/jdk.internal.misc=ALL-UNNAMED \
	-cp "/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TKG/lib/asm.jar:/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../../jvmtest/TestConfig/resources:/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TKG/lib/testng.jar:/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TKG/lib/jcommander.jar:/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../../jvmtest/functional/Valhalla/ValhallaTests.jar" \
	org.testng.TestNG -d "/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TKG/output_16323334643752/ValueTypeTests_0" "/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../../jvmtest/functional/Valhalla/testng.xml" -testnames ValueTypeTests \
	-groups level.sanity \
	-excludegroups d.*.linux_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
	if [ $? -eq 0 ] ; then echo ""; echo "ValueTypeTests_0""_PASSED"; echo ""; cd /root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/..;  else echo ""; echo "ValueTypeTests_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TKG/output_16323334643752/TestTargetResult";
JVMJ9VM193W Since Java 13 -Xverify:none and -noverify were deprecated for removal and may not be accepted options in the future.
[IncludeExcludeTestAnnotationTransformer] [INFO] EXCLUDE_FILE environment variable: /root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TestConfig/resources/excludes/latest_exclude_Valhalla.txt,/root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TestConfig/resources/excludes/feature_ojdkmh_exclude.txt
[IncludeExcludeTestAnnotationTransformer] [INFO] Unable to open file /root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TestConfig/resources/excludes/latest_exclude_Valhalla.txt, changed to read /root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TestConfig/resources/excludes/latest_exclude_base.txt
[IncludeExcludeTestAnnotationTransformer] [INFO] Processing exclude file: /root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TestConfig/resources/excludes/latest_exclude_base.txt
[IncludeExcludeTestAnnotationTransformer] [INFO] Processing exclude file: /root/home/ahuo/src/openj9-openjdk-jdk/openj9/test/TKG/../TestConfig/resources/excludes/feature_ojdkmh_exclude.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

java.lang.NoSuchMethodException: no such method: Point2D.withx(int)Point2D/invokeVirtual
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3657)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2683)
	at org.openj9.test.lworld.ValueTypeTests.generateWither(ValueTypeTests.java:3266)
	at org.openj9.test.lworld.ValueTypeTests.testCreatePoint2D(ValueTypeTests.java:301)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
...
...
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DISABLED test targets:
   ValueTypeTestsJIT_0
  
FAILED test targets:
   ValueTypeTests_0
   ValueTypeTests_1
   ValueTypeTests_2
   ValueTypeTests_3
   ValueTypeTests_4
   ValueTypeTests_5
   ValueTypeTests_6
   ValueTypeTests_7
   ValueTypeTestsJIT_1
   ValueTypeTestsJIT_2
   ValueTypeTestsJIT_3
  
TOTAL: 12   EXECUTED: 11   PASSED: 0   FAILED: 11   DISABLED: 1   SKIPPED: 0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by a7ehuo** [comment]
@tajila Is this related to #12183? Will it be implemented soon? It looks like all Valhalla functional tests fail. Thanks! 
@hzongaro fyi

**Comment by tajila** [comment]
@a7ehuo We have updated the tests, should work now.

**Comment by a7ehuo** [comment]
Thanks @tajila!
