### ISSUE TITLE
Eden size over maxium size (nightly build)

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#13558]
Java -version output
--------------------
```

openjdk version "11.0.13-internal" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13-internal+0-adhoc.jenkins.BuildJDK11x86-64windowsNightly)
Eclipse OpenJ9 VM (build master-7f3e8d7edfa, JRE 11 Windows 7 amd64-64-Bit Compressed References 20210922_106 (JIT enabled, AOT enabled)
OpenJ9   - 7f3e8d7edfa
OMR      - 12f1e39
JCL      - ddc29ca7606 based on jdk-11.0.13+5)
```
Summary of problem
------------------
Jconsole can not get eden pool size when eden size over maximum new space size.
Eden size increase bigger than maximum new space size, It cause "MemoryMXBean notification dispatcher" thread thrown a error.
Use "-verbose:sizes" option getted maximum new space size(max eden size).

Diagnostic files
----------------
Size information (-verbose:sizes):
```
E:\MinecraftServerPack\1.16.4andf>"D:\Program Files\jdk11-j9\bin\java" -Xmx1024M
 -Xms1024M -Xgc:targetPauseTime=200 -Xverbosegclog -verbose:gc -verbose:sizes -X
gcpolicy:balanced -jar fabric-server-launch.jar
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns256M       initial new space size
  -Xmnx256M       maximum new space size
  -Xms1G          initial memory size
  -Xmos1G         initial old space size
  -Xmox1G         maximum old space size
  -Xmx1G          memory maximum
  -Xlp:objectheap:pagesize=4K    large page size
                  available large page sizes:
                  4K
                  2M
  -Xlp:codecache:pagesize=4K     large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
                  2M
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
  -XX:SharedCacheHardLimit=300M shared class cache size
  -Xscmx64M       shared class cache soft max size
  -Xscdmx24544K   reserved shared class cache space for class debug attributes
  -Xscminaot0K    min reserved shared class cache space for AOT
  -Xscmaxaot282300K max allowed shared class cache space for AOT
  -Xscminjitdata0K min reserved shared class cache space for JIT data
  -Xscmaxjitdata282300K max allowed shared class cache space for JIT data
```
printed log:
```
Exception in thread "MemoryMXBean notification dispatcher" java.lang.IllegalArgu
mentException: committed value cannot be larger than the max value
        at java.management/java.lang.management.MemoryUsage.<init>(MemoryUsage.j
ava:118)
        at jdk.management/com.ibm.lang.management.internal.ExtendedGarbageCollec
torMXBeanImpl.buildGcInfo(ExtendedGarbageCollectorMXBeanImpl.java:92)
        at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThr
ead.dispatchGCNotificationHelper(MemoryNotificationThread.java:95)
        at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThr
ead.processNotificationLoop(Native Method)
        at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThr
ead.run(MemoryNotificationThread.java:183)
        at java.base/java.lang.Thread.run(Thread.java:866)
```
[verbosegc.20210924.000125.7548.zip](https://github.com/eclipse-openj9/openj9/files/7219300/verbosegc.20210924.000125.7548.zip)

Eden size less than 0 value.

https://github.com/eclipse-openj9/openj9/blob/7f3e8d7edfac9c74bdd8f107cdbbbbd4a78f4266/runtime/gc_vlhgc/SchedulingDelegate.cpp#L139

```
Exception in thread "MemoryMXBean notification dispatcher" java.lang.IllegalArgumentException: committed argument cannot be less than 0
	at java.management/java.lang.management.MemoryUsage.<init>(MemoryUsage.java:108)
	at jdk.management/com.ibm.lang.management.internal.ExtendedGarbageCollectorMXBeanImpl.buildGcInfo(ExtendedGarbageCollectorMXBeanImpl.java:93)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.dispatchGCNotificationHelper(MemoryNotificationThread.java:95)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.processNotificationLoop(Native Method)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.run(MemoryNotificationThread.java:183)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by 1a2s3d4f1** [comment]
Minimum EdenSize have a problem. It might be less than 0.
https://github.com/eclipse-openj9/openj9/blob/7f3e8d7edfac9c74bdd8f107cdbbbbd4a78f4266/runtime/gc_vlhgc/SchedulingDelegate.cpp#L139
```
Exception in thread "MemoryMXBean notification dispatcher" java.lang.IllegalArgumentException: committed argument cannot be less than 0
	at java.management/java.lang.management.MemoryUsage.<init>(MemoryUsage.java:108)
	at jdk.management/com.ibm.lang.management.internal.ExtendedGarbageCollectorMXBeanImpl.buildGcInfo(ExtendedGarbageCollectorMXBeanImpl.java:93)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.dispatchGCNotificationHelper(MemoryNotificationThread.java:95)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.processNotificationLoop(Native Method)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.run(MemoryNotificationThread.java:183)
	at java.base/java.lang.Thread.run(Thread.java:866)

```

**Comment by LinHu2016** [comment]
Thanks @1a2s3d4f1 for the information, I will investigate the case eden size = 0 or less than 0.

**Comment by LinHu2016** [comment]
@1a2s3d4f1 
I did realize that the initial eden size (user specified, -Xmns20M) is bigger than initial heap size(default, <attribute name="initialHeapSize" value="0x800000" />) in  your test case, it might be reason trigger the reporting issue.

```
<exclusive-start id="2" timestamp="2021-09-25T18:19:09.193" intervalms="229.580">
  <response-info timems="0.007" idlems="0.007" threads="0" lastid="00000000029A6F00" lastname="main" />
</exclusive-start>
<af-start id="3" threadId="00000000029A7900" totalBytesRequested="8208" timestamp="2021-09-25T18:19:09.193" intervalms="229.633" />
<cycle-start id="4" type="global garbage collect" contextid="0" timestamp="2021-09-25T18:19:09.193" intervalms="229.671" />
<gc-start id="5" type="global garbage collect" contextid="4" timestamp="2021-09-25T18:19:09.193">
  <mem-info id="6" free="0" total="8388608" percent="0">
    <mem type="eden" free="12582912" total="20971520" percent="60" />
    <remembered-set count="0" freebytes="335360" totalbytes="335360" percent="100" regionsoverflowed="0" regionsstable="0" regionsrebuilding="0"/>
  </mem-info>
</gc-start>

```

**Comment by 1a2s3d4f1** [comment]
Set -Xmns400M still cause problem. But set -Xms400M and -Xmns400M can solve this problem.
Test java version:
```
openjdk version "11.0.13-internal" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13-internal+0-adhoc.jenkins.BuildJDK11x86-64windowsNightly)
Eclipse OpenJ9 VM (build master-f5a09cb37f5, JRE 11 Windows 7 amd64-64-Bit Compressed References 20210930_113 (JIT enabled, AOT enabled)
OpenJ9   - f5a09cb37f5
OMR      - 52099bb
JCL      - af3e6fe9fa0 based on jdk-11.0.13+7)
```
Part size information:
```
  -Xmns400M       initial new space size
  -Xmnx1536M      maximum new space size
  -Xms400M        initial memory size
  -Xmos8M         initial old space size
  -Xmox2G         maximum old space size
  -Xmx2G          memory maximum
```
Throwed error:
```
Exception in thread "MemoryMXBean notification dispatcher" java.lang.IllegalArgumentException: init argument cannot be less than -1
	at java.management/java.lang.management.MemoryUsage.<init>(MemoryUsage.java:93)
	at jdk.management/com.ibm.lang.management.internal.ExtendedGarbageCollectorMXBeanImpl.buildGcInfo(ExtendedGarbageCollectorMXBeanImpl.java:92)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.dispatchGCNotificationHelper(MemoryNotificationThread.java:95)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.processNotificationLoop(Native Method)
	at jdk.management/com.ibm.lang.management.internal.MemoryNotificationThread.run(MemoryNotificationThread.java:183)
	at java.base/java.lang.Thread.run(Thread.java:866)
```
[verbosegc.20211001.232343.9988.zip](https://github.com/eclipse-openj9/openj9/files/7268301/verbosegc.20211001.232343.9988.zip)

**Comment by 1a2s3d4f1** [comment]
Thank you, is not happen any issue with this this thread.
