### ISSUE TITLE
java/lang/invoke/MethodHandlesAsCollectorTest.java testAsCollector null AssertionError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13572]
https://github.com/eclipse-openj9/openj9/issues/13457
jdk_lang_0
-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops
java/lang/invoke/MethodHandlesAsCollectorTest.java
```
23:03:21  JavaTest Message: JUnit Failure: testAsCollector(test.java.lang.invoke.MethodHandlesAsCollectorTest): null
23:03:21  java.lang.AssertionError
23:03:21  	at java.base/java.lang.invoke.LambdaFormBuffer.insertExpression(LambdaFormBuffer.java:388)
23:03:21  	at java.base/java.lang.invoke.LambdaFormEditor.spreadArgumentsForm(LambdaFormEditor.java:624)
23:03:21  	at java.base/java.lang.invoke.MethodHandle.asSpreader(MethodHandle.java:1028)
23:03:21  	at java.base/java.lang.invoke.MethodHandle.asSpreader(MethodHandle.java:982)
23:03:21  	at java.base/java.lang.invoke.Invokers.spreadInvoker(Invokers.java:225)
23:03:21  	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
23:03:21  	at test.java.lang.invoke.MethodHandlesAsCollectorTest.testAsCollector(MethodHandlesAsCollectorTest.java:88)
23:03:21  	at test.java.lang.invoke.MethodHandlesAsCollectorTest.testAsCollector0(MethodHandlesAsCollectorTest.java:65)
23:03:21  	at test.java.lang.invoke.MethodHandlesAsCollectorTest$$Lambda$25/0x000000002308c650.run(Unknown Source)
23:03:21  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor$$Lambda$26/0x000000002308d028.run(Unknown Source)
23:03:21  	at jdk.test.lib.Utils.filterException(Utils.java:624)
23:03:21  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor.runMHTest(CodeCacheOverflowProcessor.java:71)
23:03:21  	at test.java.lang.invoke.MethodHandlesAsCollectorTest.testAsCollector(MethodHandlesAsCollectorTest.java:49)

**Comment by pshipton** [comment]
Perhaps related to https://github.com/eclipse-openj9/openj9/issues/13457

**Comment by babsingh** [comment]
@pshipton Is there a link the core files? I would like to see if it is similar to https://github.com/eclipse-openj9/openj9/issues/13457#issuecomment-925858820.

**Comment by pshipton** [comment]
@babsingh fixed the link in the description and added the link to the artifacts

**Comment by pshipton** [comment]
I don't think there is any core file for an AssertionError.

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/34/openjdk_test_output.tar.gz
