### ISSUE TITLE
 renaissance test failure : StackOverflowError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13575]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_extended.perf_ppc64_aix/31/` (`paix823`):
```
java version "11.0.13" 2021-10-19
IBM Semeru Runtime Certified Edition 11.0.13.0-m1 (build 11.0.13+6)
Eclipse OpenJ9 VM 11.0.13.0-m1 (build master-d6256c10f, JRE 11 AIX ppc64-64-Bit Compressed References 20210924_149 (JIT enabled, AOT enabled)
OpenJ9   - d6256c10f
OMR      - 82faf49a1
JCL      - b0a5529a02 based on jdk-11.0.13+6)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=extended.perf&SDK_RESOURCE=upstream&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&EXTRA_DOCKER_ARGS=&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&PLATFORM=ppc64_aix&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F149%2Fibm-semeru-certified-debugimage_ppc64_aix_11.0.13_5_openj9-0.29.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F149%2Fibm-semeru-certified-jre_ppc64_aix_11.0.13_5_openj9-0.29.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F149%2Fibm-semeru-certified-testimage_ppc64_aix_11.0.13_5_openj9-0.29.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F149%2Fibm-semeru-certified-jdk_ppc64_aix_11.0.13_5_openj9-0.29.0-m1.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&JDK_VERSION=11&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&RELEASE_TAG=v0.29.0-release&OPENJ9_BRANCH=v0.29.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.29.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&TKG_SHA=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&NUM_MACHINES=&OPENJDK_SHA=&BUILD_LIST=perf&UPSTREAM_JOB_NUMBER=&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-09-24T18:58:52.424Z] Running test renaissance-als_0 ...
[2021-09-24T18:58:52.424Z] ===============================================
[2021-09-24T18:58:52.424Z] renaissance-als_0 Start Time: Fri Sep 24 15:07:21 2021 Epoch Time (ms): 1632514041638
[2021-09-24T18:58:52.424Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.perf_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.perf_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-09-24T18:58:52.424Z] JVMSHRC005I No shared class caches available
[2021-09-24T18:58:52.424Z] JVMSHRC005I No shared class caches available
[2021-09-24T18:58:52.424Z] cache cleanup done
[2021-09-24T18:58:52.424Z] variation: NoOptions
[2021-09-24T18:58:52.424Z] JVM_OPTIONS:  

[2021-09-24T18:59:27.703Z] ====== als (apache-spark), iteration 1 started ======
[2021-09-24T18:59:38.803Z] 21/09/24 14:08:05 ERROR Executor: Exception in task 1.0 in stage 134.0 (TID 783)
[2021-09-24T18:59:38.803Z] java.lang.StackOverflowError
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.redirectedReadObject(ObjectInputStream.java:507)
[2021-09-24T18:59:38.803Z] 	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
[2021-09-24T18:59:38.803Z] 	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
[2021-09-24T18:59:38.803Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-24T18:59:38.803Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2452)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:577)
[2021-09-24T18:59:38.803Z] 	at java.base/java.io.ObjectInputStream.redirectedReadObject(ObjectInputStream.java:507)

[2021-09-24T18:59:39.772Z] 	at java.base/java.io.ObjectInputStream.redirectedReadObject(ObjectInputStream.java:507)
[2021-09-24T18:59:39.772Z] 	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
[2021-09-24T18:59:39.772Z] 	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
[2021-09-24T18:59:39.772Z] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
[2021-09-24T18:59:39.772Z] 	at org.apache.spark.scheduler.Task.run(Task.scala:85)
[2021-09-24T18:59:39.772Z] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
[2021-09-24T18:59:39.773Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-09-24T18:59:39.773Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-09-24T18:59:39.773Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2021-09-24T18:59:39.773Z] 21/09/24 14:08:05 ERROR TaskSetManager: Task 1 in stage 134.0 failed 1 times; aborting job
[2021-09-24T18:59:39.773Z] The following benchmarks failed: als
[2021-09-24T18:59:41.855Z] 
[2021-09-24T18:59:41.855Z] renaissance-als_0_FAILED
```

```
[2021-09-24T19:16:24.034Z] Running test renaissance-movie-lens_0 ...
[2021-09-24T19:16:24.034Z] ===============================================
[2021-09-24T19:16:24.034Z] renaissance-movie-lens_0 Start Time: Fri Sep 24 15:24:53 2021 Epoch Time (ms): 1632515093282
[2021-09-24T19:16:24.034Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.perf_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.perf_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-09-24T19:16:24.034Z] JVMSHRC005I No shared class caches available
[2021-09-24T19:16:24.034Z] JVMSHRC005I No shared class caches available
[2021-09-24T19:16:24.034Z] cache cleanup done
[2021-09-24T19:16:24.034Z] variation: NoOptions
[2021-09-24T19:16:24.034Z] JVM_OPTIONS:  

[2021-09-24T19:17:17.732Z] java.lang.StackOverflowError
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readInt(ObjectInputStream.java:3520)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readHandle(ObjectInputStream.java:1915)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1976)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2291)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:577)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.redirectedReadObject(ObjectInputStream.java:507)
[2021-09-24T19:17:17.732Z] 	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
[2021-09-24T19:17:17.732Z] 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[2021-09-24T19:17:17.732Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-09-24T19:17:17.732Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2452)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2593)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2485)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2318)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:577)
[2021-09-24T19:17:17.732Z] 	at java.base/java.io.ObjectInputStream.redirectedReadObject(ObjectInputStream.java:507)
[2021-09-24T19:17:17.732Z] 	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
[2021-09-24T19:17:17.733Z] 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[2021-09-24T19:17:17.733Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-09-24T19:17:19.092Z] 	at java.base/java.io.ObjectInputStream.redirectedReadObject(ObjectInputStream.java:507)
[2021-09-24T19:17:19.092Z] 	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
[2021-09-24T19:17:19.092Z] 	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
[2021-09-24T19:17:19.092Z] 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:71)
[2021-09-24T19:17:19.092Z] 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
[2021-09-24T19:17:19.092Z] 	at org.apache.spark.scheduler.Task.run(Task.scala:85)
[2021-09-24T19:17:19.092Z] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
[2021-09-24T19:17:19.092Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-09-24T19:17:19.092Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-09-24T19:17:19.092Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2021-09-24T19:17:19.093Z] The following benchmarks failed: movie-lens
[2021-09-24T19:17:20.592Z] 
[2021-09-24T19:17:20.592Z] renaissance-movie-lens_0_FAILED
```

Also observed at JDK11 ppc64le_linux `job/Test_openjdk11_j9_extended.perf_ppc64le_linux/35/`, and JDK8 Windows `job/Test_openjdk8_j9_extended.perf_x86-32_windows/16/`

**Comment by pshipton** [comment]
Is this a recent regression then, or a recent test addition?

**Comment by JasonFengJ9** [comment]
It hasn't been reproduced w/ same JDK yet at a 50x grinder `job/Grinder_testList_0/444/consoleFull`.

**Comment by pshipton** [comment]
Pls try the test with `-Dcom.ibm.enableClassCaching=false`

**Comment by JasonFengJ9** [comment]
> -Dcom.ibm.enableClassCaching=false

No, it doesn't help.
