### ISSUE TITLE
-Xgcpolicy:balanced AllocationTest  OOM

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13584]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/110
cmdLineTester_verbosetest_6
variation: Mode551
JVM_OPTIONS:  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced 
Testing: -verbose:gc,class -verbose:none -verbose:class

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/110/functional_test_output.tar.gz
```
Testing: -verbose:gc,class -verbose:none -verbose:class
Test start time: 2021/09/28 00:55:06 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java"  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -verbose:gc,class -verbose:none -verbose:class -cp "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../TKG/output_16328025398680/cmdLineTester_verbosetest_6" "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml" -testnames AllocationTest -groups level.extended
Time spent starting: 1 milliseconds
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2021/09/28 00:55:06 - please wait.
```

**Comment by pshipton** [comment]
@dmitripivkine

**Comment by pshipton** [comment]
```
1STHEAPTYPE    Object Memory
NULL           id                 start              end                size               space
1STHEAPSPACE   0x000003FF9C0D19D0 0x0000000030300000 0x0000000033E00000 0x0000000003B00000 Flat
NULL
1STHEAPTOTAL   Total memory:                    61865984 (0x0000000003B00000)
1STHEAPINUSE   Total memory in use:             37752832 (0x0000000002401000)
1STHEAPFREE    Total memory free:               24113152 (0x00000000016FF000)
```
```
1STGCHTYPE     GC History
3STHSTTYPE     04:55:06:243598179 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=24113152/61865984 loa=0/0
3STHSTTYPE     04:55:06:243596285 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=24113152/61865984 loa=0/0
3STHSTTYPE     04:55:06:243464100 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 24117248
3STHSTTYPE     04:55:06:243453657 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=24117248/61865984
3STHSTTYPE     04:55:06:243243981 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:06:243233673 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     04:55:06:240473241 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:06:240436393 GMT j9mm.740 -   Sweep end. Duration 164 us
3STHSTTYPE     04:55:06:240271548 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:06:240218688 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:06:240218005 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:06:240217746 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:06:238805253 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:06:238768422 GMT j9mm.474 -   GlobalGC start: globalcount=88
3STHSTTYPE     04:55:06:238768122 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:238758465 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.001 meanexclusiveaccessms=0.001 threads=0 lastthreadtid=0x000000000023D448 beatenbyotherthread=0
3STHSTTYPE     04:55:06:238758162 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=0/37748736 loa=0/0 requestedbytes=32
3STHSTTYPE     04:55:06:238757888 GMT j9mm.133 -   Allocation failure start: newspace=0/0 oldspace=0/37748736 loa=0/0 requestedbytes=32
3STHSTTYPE     04:55:06:238745520 GMT j9mm.101 -   J9AllocateIndexableObject() returning NULL! 56 bytes requested for object of class 0000000000099B00 from memory space 'Flat' id=000003FF9C0D19D0
3STHSTTYPE     04:55:06:238738914 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=0/37748736 loa=0/0
3STHSTTYPE     04:55:06:238737030 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=0/37748736 loa=0/0
3STHSTTYPE     04:55:06:238676928 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:238665864 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=0/37748736
3STHSTTYPE     04:55:06:238613242 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:06:238603578 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     04:55:06:235907178 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:06:235869034 GMT j9mm.740 -   Sweep end. Duration 161 us
3STHSTTYPE     04:55:06:235707278 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:06:235659906 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:06:235659339 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:06:235659150 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:06:234273861 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:06:234239817 GMT j9mm.474 -   GlobalGC start: globalcount=87
3STHSTTYPE     04:55:06:234239505 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:234210371 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:234197747 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=0/37748736
3STHSTTYPE     04:55:06:234140914 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:06:234132678 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     04:55:06:231581602 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:06:231544510 GMT j9mm.740 -   Sweep end. Duration 149 us
3STHSTTYPE     04:55:06:231395357 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:06:231344589 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:06:231344044 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:06:231343814 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:06:230037698 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:06:230005694 GMT j9mm.474 -   GlobalGC start: globalcount=86
3STHSTTYPE     04:55:06:230005526 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:229994714 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.002 meanexclusiveaccessms=0.002 threads=0 lastthreadtid=0x000000000023D448 beatenbyotherthread=0
3STHSTTYPE     04:55:06:229994457 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=0/37748736 loa=0/0 requestedbytes=56
3STHSTTYPE     04:55:06:229989404 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=0/37748736 loa=0/0
3STHSTTYPE     04:55:06:229982781 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:229972312 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=0/37748736
3STHSTTYPE     04:55:06:229914471 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:06:229904738 GMT j9mm.137 -   Compact end: bytesmoved=1048256
3STHSTTYPE     04:55:06:226318537 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:06:226275516 GMT j9mm.740 -   Sweep end. Duration 149 us
3STHSTTYPE     04:55:06:226125769 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:06:226075629 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:06:226075048 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:06:226074866 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:06:224724615 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:06:224692695 GMT j9mm.474 -   GlobalGC start: globalcount=85
3STHSTTYPE     04:55:06:224692528 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:224676321 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:224665385 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=0/37748736
3STHSTTYPE     04:55:06:224574794 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:06:224565662 GMT j9mm.137 -   Compact end: bytesmoved=302200
3STHSTTYPE     04:55:06:221969892 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:06:221931921 GMT j9mm.740 -   Sweep end. Duration 153 us
3STHSTTYPE     04:55:06:221777901 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:06:221725381 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:06:221724728 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:06:221724511 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:06:220384670 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:06:220341560 GMT j9mm.474 -   GlobalGC start: globalcount=84
3STHSTTYPE     04:55:06:220341321 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:220324898 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.002 meanexclusiveaccessms=0.002 threads=0 lastthreadtid=0x000000000023D448 beatenbyotherthread=0
3STHSTTYPE     04:55:06:220324621 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=0/38797312 loa=0/0 requestedbytes=56
3STHSTTYPE     04:55:06:220324289 GMT j9mm.133 -   Allocation failure start: newspace=0/0 oldspace=0/38797312 loa=0/0 requestedbytes=56
3STHSTTYPE     04:55:06:214483417 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=1003520/38797312 loa=0/0
3STHSTTYPE     04:55:06:214480406 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=1003520/38797312 loa=0/0
3STHSTTYPE     04:55:06:214468695 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 1048576
3STHSTTYPE     04:55:06:214421969 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=1048576/38797312
3STHSTTYPE     04:55:06:214313747 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:06:214303615 GMT j9mm.137 -   Compact end: bytesmoved=2109536
3STHSTTYPE     04:55:06:210749110 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:06:210704052 GMT j9mm.740 -   Sweep end. Duration 218 us
3STHSTTYPE     04:55:06:210485118 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:06:210398710 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:06:210395108 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:06:210394294 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:06:208391526 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:06:208118038 GMT j9mm.474 -   GlobalGC start: globalcount=83
3STHSTTYPE     04:55:06:208117514 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:06:208090489 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.004 meanexclusiveaccessms=0.004 threads=0 lastthreadtid=0x000000000023D448 beatenbyotherthread=0
3STHSTTYPE     04:55:06:208089877 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=0/39845888 loa=0/0 requestedbytes=16
3STHSTTYPE     04:55:06:208089514 GMT j9mm.133 -   Allocation failure start: newspace=0/0 oldspace=0/39845888 loa=0/0 requestedbytes=16
3STHSTTYPE     04:55:03:731838356 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=2060288/39845888 loa=0/0
3STHSTTYPE     04:55:03:731834385 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=2060288/39845888 loa=0/0
3STHSTTYPE     04:55:03:731787127 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 2097152
3STHSTTYPE     04:55:03:731728647 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=2097152/39845888
3STHSTTYPE     04:55:03:731681829 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:03:731668738 GMT j9mm.137 -   Compact end: bytesmoved=1459400
3STHSTTYPE     04:55:03:729746424 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:03:729703247 GMT j9mm.740 -   Sweep end. Duration 188 us
3STHSTTYPE     04:55:03:729514617 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:03:729430014 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:03:729427716 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:03:729427337 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:03:727881782 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:03:727628450 GMT j9mm.474 -   GlobalGC start: globalcount=82
3STHSTTYPE     04:55:03:727627778 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:03:727602631 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.006 meanexclusiveaccessms=0.006 threads=0 lastthreadtid=0x0000000000069248 beatenbyotherthread=0
3STHSTTYPE     04:55:03:727601764 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=0/39845888 loa=0/0 requestedbytes=1664
3STHSTTYPE     04:55:03:727601401 GMT j9mm.133 -   Allocation failure start: newspace=0/0 oldspace=0/39845888 loa=0/0 requestedbytes=1664
3STHSTTYPE     04:55:02:080358048 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=3141632/39845888 loa=0/0
3STHSTTYPE     04:55:02:080347243 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=3141632/39845888 loa=0/0
3STHSTTYPE     04:55:02:080330833 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 3145728
3STHSTTYPE     04:55:02:080314371 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=3145728/39845888
3STHSTTYPE     04:55:02:080270311 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:02:080259109 GMT j9mm.137 -   Compact end: bytesmoved=925936
3STHSTTYPE     04:55:02:071849850 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:02:071811787 GMT j9mm.740 -   Sweep end. Duration 156 us
3STHSTTYPE     04:55:02:071655464 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:02:071602224 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:02:071601100 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:02:071600772 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:02:070240998 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:02:070204454 GMT j9mm.474 -   GlobalGC start: globalcount=81
3STHSTTYPE     04:55:02:070204241 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:02:070189444 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.424 meanexclusiveaccessms=0.214 threads=1 lastthreadtid=0x000000000023D448 beatenbyotherthread=0
3STHSTTYPE     04:55:02:070189118 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=0/39845888 loa=0/0 requestedbytes=24
3STHSTTYPE     04:55:02:070188776 GMT j9mm.133 -   Allocation failure start: newspace=0/0 oldspace=0/39845888 loa=0/0 requestedbytes=24
3STHSTTYPE     04:55:02:068825946 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=0/39845888 loa=0/0
3STHSTTYPE     04:55:02:068623551 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=2097152/39845888 loa=0/0
3STHSTTYPE     04:55:02:068600671 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 3145728
3STHSTTYPE     04:55:02:068584021 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=3145728/39845888
3STHSTTYPE     04:55:02:068485614 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:02:068473015 GMT j9mm.137 -   Compact end: bytesmoved=1869376
3STHSTTYPE     04:55:02:066033470 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:02:065988467 GMT j9mm.740 -   Sweep end. Duration 206 us
3STHSTTYPE     04:55:02:065781976 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:02:065702318 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:02:065700325 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:02:065699991 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:02:064167665 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:02:063936789 GMT j9mm.474 -   GlobalGC start: globalcount=80
3STHSTTYPE     04:55:02:063936110 GMT j9mm.467 -   Cycle Start: type 5 approximateFreeMemorySize 1048528
3STHSTTYPE     04:55:02:063909676 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.009 meanexclusiveaccessms=0.009 threads=0 lastthreadtid=0x000000000023D448 beatenbyotherthread=0
3STHSTTYPE     04:55:02:063908937 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=1048528/40894464 loa=0/0 requestedbytes=5111856
3STHSTTYPE     04:55:02:063908411 GMT j9mm.133 -   Allocation failure start: newspace=0/0 oldspace=1048528/40894464 loa=0/0 requestedbytes=5111856
3STHSTTYPE     04:55:01:401858930 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=5177344/40894464 loa=0/0
3STHSTTYPE     04:55:01:401853604 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=5177344/40894464 loa=0/0
3STHSTTYPE     04:55:01:401838002 GMT j9mm.468 -   Cycle End: type 5 approximateFreeMemorySize 5242880
3STHSTTYPE     04:55:01:401822430 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=5242880/40894464
3STHSTTYPE     04:55:01:401755188 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:55:01:401743391 GMT j9mm.137 -   Compact end: bytesmoved=1980592
3STHSTTYPE     04:55:01:400058092 GMT j9mm.136 -   Compact start: reason=no compaction
3STHSTTYPE     04:55:01:400014175 GMT j9mm.740 -   Sweep end. Duration 208 us
3STHSTTYPE     04:55:01:399805691 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:55:01:399720709 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     04:55:01:399719759 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:55:01:399719474 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:55:01:398371900 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:55:01:398343391 GMT j9mm.474 -   GlobalGC start: globalcount=79
3STHSTTYPE     04:55:01:398343227 GMT j9mm.492 -   Cycle Continue: from type 4 to type 5 approximateFreeMemorySize 0
3STHSTTYPE     04:55:01:398342852 GMT j9mm.464 -   Global Mark Phase cycle end
3STHSTTYPE     04:55:01:398273469 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.007 meanexclusiveaccessms=0.007 threads=0 lastthreadtid=0x000000000023D448 beatenbyotherthread=0
3STHSTTYPE     04:55:01:398272720 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/0 oldspace=0/38797312 loa=0/0 requestedbytes=48
3STHSTTYPE     04:55:01:398272397 GMT j9mm.133 -   Allocation failure start: newspace=0/0 oldspace=0/38797312 loa=0/0 requestedbytes=48
```

**Comment by pshipton** [comment]
Another one.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/112/
cmdLineTester_verbosetest_1
variation: Mode501
JVM_OPTIONS:  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/112/functional_test_output.tar.gz
```
Testing: -verbose:noclass,class
Test start time: 2021/10/01 23:53:48 Pacific Standard Time
Running command: "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xdump -verbose:noclass,class -cp "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/aqa-tests/TKG/../TKG/lib/testng.jar:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/aqa-tests/TKG/../TKG/lib/jcommander.jar:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/aqa-tests/TKG/../TKG/output_16331568057725/cmdLineTester_verbosetest_1" "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml" -testnames AllocationTest -groups level.extended
Time spent starting: 4 milliseconds
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2021/10/01 23:53:48 - please wait.
...
Exception in thread "Thread-147" java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringBuilder.ensureCapacityImpl(StringBuilder.java:802)
	at java.lang.StringBuilder.append(StringBuilder.java:588)
	at Test$StreamMatcher.run(Test.java:488)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_0/108
cmdLineTester_verbosetest_6
variation: Mode551
JVM_OPTIONS:  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced 
Testing: -verbose:jni -verbose:gc,class 

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_0/108/functional_test_output.tar.gz

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/114/
cmdLineTester_verbosetest_1
variation: Mode501
JVM_OPTIONS:  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 
Testing: -verbose:gc -verbose:class -verbose:noclass -verbose:class

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/114/functional_test_output.tar.gz

**Comment by dmitripivkine** [comment]
I noticed I never commented on this. We have a theory and working.
