### ISSUE TITLE
Crash in VM running FibBench with -Xlockword:mode=minimizeFootprint

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13587]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_windows_Release_testList_1/6
cmdLineTest_J9test_common_0 (NoOptions)

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.functional_x86-64_windows_Release_testList_1/6/functional_test_output.tar.gz
```
Testing: -Xlockword minimizeFootprint mode
Test start time: 2021/09/26 01:07:02 Central Standard Time
Running command: "F:/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_windows_Release_testList_1/openjdkbinary/j2sdk-image\\bin\\java"   -Xdump -cp "F:/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_windows_Release_testList_1/aqa-tests///..//jvmtest\functional\cmdLineTests\utils\utils.jar" -Xlockword:mode=minimizeFootprint VMBench.FibBench
Time spent starting: 0 milliseconds
Time spent executing: 4781 milliseconds
Test result: FAILED
Output from test:
 [OUT] Fibonacci: iterations = 10000
 [OUT] fibonacci(12) = 144
 [ERR] Unhandled exception
 [ERR] Type=Segmentation error vmState=0x00000000
 [ERR] Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFAE1F8C923 ContextFlags=0010005f
 [ERR] Handler1=00007FFAE2044F80 Handler2=00007FFAE451A8F0 InaccessibleReadAddress=0000000000000024
 [ERR] RDI=000000BB956AECB8 RSI=FFFFFFFFFFFFFFFF RAX=0000000000000004 RBX=0000000000000000
 [ERR] RCX=000000000001AA00 RDX=000000000001AA00 R8=0000000000054200 R9=0000000000000012
 [ERR] R10=000000BB956AECC0 R11=000000BB956AE870 R12=000000BBA0B6CD67 R13=00000000001185F0
 [ERR] R14=000000BB94F8CFA0 R15=00000000FFEB3550
 [ERR] RIP=00007FFAE1F8C923 RSP=000000BB956AE9B0 RBP=0000000000000000 EFLAGS=0000000000010202
 [ERR] FS=0053 ES=002B DS=002B
 [ERR] XMM0 000000bba0b6cd67 (f: 2696334592.000000, d: 3.981454e-312)
 [ERR] XMM1 0000000000118608 (f: 1148424.000000, d: 5.673968e-318)
 [ERR] XMM2 0000000000092500 (f: 599296.000000, d: 2.960916e-318)
 [ERR] XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM6 00000000001185f0 (f: 1148400.000000, d: 5.673850e-318)
 [ERR] XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] Module=F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.functional_x86-64_windows_Release_testList_1\openjdkbinary\j2sdk-image\bin\default\j9vm29.dll
 [ERR] Module_base_address=00007FFAE1F80000 Offset_in_DLL=000000000000c923
 [ERR] Target=2_90_20210925_6 (Windows Server 2012 R2 6.3 build 9600)
 [ERR] CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
 [ERR] ----------- Stack Backtrace -----------
 [ERR] (0x00007FFAE1F8C923 [j9vm29+0xc923])
 [ERR] ---------------------------------------
```

**Comment by pshipton** [comment]
@tajila fyi. Happened in the last weekend 0.28 testing. Might be worth taking a look before moving this out of the milestone.

**Comment by gacholio** [comment]
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "main" J9VMThread:0x000000000001AA00, omrthread_t:0x000000BB94F7ADF0, java/lang/Thread:0x00000000FFE03628, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0xC24, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMCPUTIME               CPU usage total: 0.421875000 secs, user: 0.281250000 secs, system: 0.140625000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=359664 (0x57CF0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/misc/Unsafe.putInt(Native Method)
4XESTACKTRACE                at com/ibm/jit/JITHelpers.putIntInObject(JITHelpers.java:286)
4XESTACKTRACE                at com/ibm/jit/JITHelpers.unsafeObjectShallowCopy64(JITHelpers.java:807)
4XESTACKTRACE                at java/lang/invoke/MemberName.clone(MemberName.java:752(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/MemberName$Factory.resolve(MemberName.java:1067)
4XESTACKTRACE                at java/lang/invoke/MemberName$Factory.resolveOrFail(MemberName.java:1114)
4XESTACKTRACE                at java/lang/invoke/InvokerBytecodeGenerator.resolveInvokerMember(InvokerBytecodeGenerator.java:327)
4XESTACKTRACE                at java/lang/invoke/InvokerBytecodeGenerator.loadMethod(InvokerBytecodeGenerator.java:321)
4XESTACKTRACE                at java/lang/invoke/InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:751)
4XESTACKTRACE                at java/lang/invoke/LambdaForm.compileToBytecode(LambdaForm.java:854)
4XESTACKTRACE                at java/lang/invoke/LambdaForm.prepare(LambdaForm.java:812)
4XESTACKTRACE                at java/lang/invoke/MethodHandle.<init>(MethodHandle.java:481)
4XESTACKTRACE                at java/lang/invoke/BoundMethodHandle.<init>(BoundMethodHandle.java:56)
4XESTACKTRACE                at java/lang/invoke/BoundMethodHandle$Species_L.<init>(BoundMethodHandle.java:222)
4XESTACKTRACE                at java/lang/invoke/BoundMethodHandle$Species_L.copyWith(BoundMethodHandle.java:242)
4XESTACKTRACE                at java/lang/invoke/MethodHandles.dropArguments0(MethodHandles.java:5275)
4XESTACKTRACE                at java/lang/invoke/MethodHandles.dropArguments(MethodHandles.java:5338)
4XESTACKTRACE                at java/lang/invoke/StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:519)
4XESTACKTRACE                at java/lang/invoke/StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:363)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x0000000000000000.delegate(LambdaForm$MH)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x0000000000000000.invokeExact_MT(LambdaForm$MH)
4XESTACKTRACE                at java/lang/invoke/BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
4XESTACKTRACE                at java/lang/invoke/CallSite.makeSite(CallSite.java:315)
4XESTACKTRACE                at java/lang/invoke/MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
4XESTACKTRACE                at java/lang/invoke/MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
4XESTACKTRACE                at java/lang/invoke/MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:194)
4XESTACKTRACE                at VMBench/FibBench.main(FibBench.java:47)
```

**Comment by tajila** [comment]
Based on the stack trace above seems like the issue arises from compiled code.

Im tagging this as JIT

**Comment by tajila** [comment]
```
4XESTACKTRACE                at jdk/internal/misc/Unsafe.putInt(Native Method)
4XESTACKTRACE                at com/ibm/jit/JITHelpers.putIntInObject(JITHelpers.java:286)
4XESTACKTRACE                at com/ibm/jit/JITHelpers.unsafeObjectShallowCopy64(JITHelpers.java:807)
4XESTACKTRACE                at java/lang/invoke/MemberName.clone(MemberName.java:752(Compiled Code))
```
This part is a little confusing to me, `unsafeObjectShallowCopy64` doesnt actually appear in the source code, is this an optimization? 

@0xdaryl @jdmpapin

**Comment by gacholio** [comment]
https://github.com/eclipse-openj9/openj9/blob/4f07bf38f6192cb8b2d155447b4e5fa9f10cd5e8/jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java#L793

**Comment by gacholio** [comment]
```
<1aa00> INL native method frame: bp = 0x00000000001185E8, sp = 0x00000000001185C8, pc = 0x0000000000000003, cp = 0x0000000000000000, arg0EA = 0x0000000000118610, flags = 0x0000000000000000
<1aa00> 	Method: jdk/internal/misc/Unsafe.putInt(Ljava/lang/Object;JI)V !j9method 0x0000000000054CA0
<1aa00> 	Using signature mapper
<1aa00> 	Arguments starting at 0x0000000000118610 for UDATA(0x0000000000000005) slots
<1aa00> 		O-Slot: a0[0x0000000000118610] = 0x00000000FFDF0128
<1aa00> 		O-Slot: a1[0x0000000000118608] = 0x00000000FFEB3550
<1aa00> 		I-Slot: a2[0x0000000000118600] = 0x0000000000000000
<1aa00> 		I-Slot: a3[0x00000000001185F8] = 0xFFFFFFFFFFFFFFFF
<1aa00> 		I-Slot: a4[0x00000000001185F0] = 0x0000000000000000
```
The object at a1 is an instance of `MemberName` - offset is -1, stored value is 0.

**Comment by gacholio** [comment]
This is a dup of #13577

**Comment by jdmpapin** [comment]
To answer @tajila's question: VP can translate an `Object.clone()` call into [a sequence involving a call to `unsafeObjectShallowCopy64()`](https://github.com/eclipse/omr/blob/52099bb355a055fbfd3a517b37f7cfc64c4546fe/compiler/optimizer/ValuePropagationCommon.cpp#L3407-L3427)

The transformation message is "Inlining object clone call [%p] as new object and JITHelpers object copy"
