### ISSUE TITLE
LambdaLoadTest_special_J9_5m StringIndexOutOfBoundsException from String.getBytes()

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13589]
0.28 branch build. First added to https://github.com/eclipse-openj9/openj9/issues/2209#issuecomment-929389414 but opened a new Issue due to the StringIndexOutOfBoundsException

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_s390x_linux_Release_testList_4/6
LambdaLoadTest_special_J9_5m_17
-Xcompressedrefs -Xgcpolicy:balanced -Xquickstart -Xjit

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_special.system_s390x_linux_Release_testList_4/6/system_test_output.tar.gz
```
LT  07:01:31.480 -   12 JUnit[net.adoptopenjdk.test.streams.TestStreamOperations]  Weighting=1 
LT  stderr WARNING: A terminally deprecated method in java.lang.System has been called
LT  stderr WARNING: System::setSecurityManager has been called by net.adoptopenjdk.loadTest.LoadTest (file:/home/jenkins/workspace/Test_openjdk17_j9_special.system_s390x_linux_Release_testList_4/jvmtest/system/stf/stf.load/bin/)
LT  stderr WARNING: Please consider reporting this to the maintainers of net.adoptopenjdk.loadTest.LoadTest
LT  stderr WARNING: System::setSecurityManager will be removed in a future release
LT  07:01:31.519 - Starting thread. Suite=0 thread=0
LT  07:01:31.519 - Starting thread. Suite=0 thread=1
LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2021/09/26 07:01:34 - please wait.
```

```
07:02:26  LT  testFailure: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded): offset 471217168, count 14, length 235608587
07:02:26  LT  java.lang.StringIndexOutOfBoundsException: offset 471217168, count 14, length 235608587
07:02:26  LT  	at java.base/java.lang.String.checkBoundsOffCount(String.java:5346)
07:02:26  LT  	at java.base/java.lang.StringUTF16.checkBoundsOffCount(StringUTF16.java:1636)
07:02:26  LT  	at java.base/java.lang.StringUTF16.inflate(StringUTF16.java:1462)
07:02:26  LT  	at java.base/java.lang.StringLatin1.inflate(StringLatin1.java:788)
07:02:26  LT  	at java.base/java.lang.String.getBytes(String.java:5216)
07:02:26  LT  	at java.base/java.lang.StringConcatHelper.newArrayWithSuffix(StringConcatHelper.java:477)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.assertStack(TestLambdaMultithreaded.java:443)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.runAllOpcodes(TestLambdaMultithreaded.java:271)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:235)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded$$Lambda$317/0x00000000000a11b0.run(Unknown Source)
07:02:26  LT  	at java.base/java.lang.Thread.run(Thread.java:884)
07:02:26  LT  testFinished: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
07:02:26  LT  
07:02:26  LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaMultithreaded
07:02:26  LT    Ran    : 1
07:02:26  LT    Passed : 0
07:02:26  LT    Failed : 1
07:02:26  LT    Ignored: 0
07:02:26  LT    Result : FAILED
```

**Comment by pshipton** [comment]
@0xdaryl fyi, Will keep an eye out for more of these.

**Comment by dmitripivkine** [comment]
Vast majority of ~2g heap occupied by discontinues arrays (arraylet leaves):
```
> !dumpallregions stats
 	FREE: 2
 	ARRAYLET_LEAF: 1957
 	ADDRESS_ORDERED: 1
 	ADDRESS_ORDERED_MARKED: 8
 	++++ TOTAL: 1968
```

**Comment by dmitripivkine** [comment]
I believe there are two questions (potential problems) in this case:
- why it goes to OOM state?
- why we have `java.lang.StringIndexOutOfBoundsException` thrown?

For first question it is obvious memory is taken by live large arrays. I looked to one of them `!j9indexableobject 0x1E886148 0 471217175` it has 449 leaves and referenced directly from JIT frame:
```
<61af00> JIT frame: bp = 0x000000000069D268, pc = 0x000003FF620FF03C, unwindSP = 0x000000000069D240, cp = 0x00000000000E8D40, arg0EA = 0x000000000069D280, jitInfo = 0x000003FF43B719B8
<61af00> 	Method: java/lang/StringUTF16.checkBoundsOffCount(II[B)V !j9method 0x00000000000E8D00
<61af00> 	Bytecode index = 6, inlineDepth = 0, PC offset = 0x000000000000004A
<61af00> 	stackMap=0x000003FF43B71AC2, slots=I16(0x0003) parmBaseOffset=I16(0x0008), parmSlots=U16(0x0001), localBaseOffset=I16(0x0000)
<61af00> 	Described JIT args starting at 0x000000000069D270 for U16(0x0001) slots
<61af00> 		O-Slot: : a0[0x000000000069D270] = 0x000000001E886148 <----
<61af00> 	Described JIT temps starting at 0x000000000069D268 for IDATA(0x0000000000000000) slots
<61af00> 	JIT-RegisterMap = UDATA(0x0000000000000000)
<61af00> 	JIT-Frame-RegisterMap[0x000000000069D210] = UDATA(0x000000001C163410) (jit_r6)
<61af00> 	JIT-Frame-RegisterMap[0x000000000069D218] = UDATA(0x0000000000416200) (jit_r7)
<61af00> 	JIT-Frame-RegisterMap[0x000000000069D220] = UDATA(0x0000000000416200) (jit_r8)
<61af00> 	JIT-Frame-RegisterMap[0x000000000069D1B0] = UDATA(0x000000000008B700) (jit_r9)
<61af00> 	JIT-Frame-RegisterMap[0x000003FF61B2B6C8] = UDATA(0x00089E0000000004) (jit_r10)
<61af00> 	JIT-Frame-RegisterMap[0x000003FF61B2B6D0] = UDATA(0x000000001EEC8740) (jit_r11)
<61af00> 	JIT-Frame-RegisterMap[0x000003FF61B2B6D8] = UDATA(0x000003FECC000A20) (jit_r12)
```
If it is useful I can attribute each leaf in the heap to objects (and to it roots) but it is a lot of manual labor. I expect all leaves can be attributed to live arrays (otherwise GC would be able to collect them. I did general sanity check (Arraylet structure is correct, GC cycle looks right etc.)  Please let me know if we need to do this ('!stackslots` command works partially in this core unfortunately).

For second question I guess it might be just reaction (not accurate handling) to array allocation failure (NULL has been returned on attempt to allocate another array 471219008 bytes long).  I think it most likely relate with handling of OOM situation.

**Comment by dmitripivkine** [comment]
For this core triggered at OOM event there are many "Worker" threads are in the process of allocating byte arrays size 471217175 elements. With region size 1m it required (in Discontiguous form) 449 leaf regions plus remainder in the array spine. With heap size  1968m (or 1968 regions total) the OOM is unavoidable, there is an attempt to allocate significantly larger amount of data than heap can take. This example of java stack:
```
3XMTHREADINFO      "Worker-0" J9VMThread:0x000000000058B700, omrthread_t:0x000003FF000C09D0, java/lang/Thread:0x000000001E880998, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x4A, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x1060, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00001020)
3XMTHREADINFO2            (native stack address range from:0x000003FF617E1000, to:0x000003FF61821000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.119708352 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/misc/Unsafe.allocateUninitializedArray0(Unsafe.java:6208(Compiled Code))
4XESTACKTRACE                at jdk/internal/misc/Unsafe.allocateUninitializedArray(Unsafe.java:1618(Compiled Code))
4XESTACKTRACE                at java/lang/StringConcatHelper.newArray(StringConcatHelper.java:494(Compiled Code))
4XESTACKTRACE                at java/lang/StringConcatHelper.newArrayWithSuffix(StringConcatHelper.java:475(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH(Compiled Code))
4XESTACKTRACE                at net/adoptopenjdk/test/lambda/TestLambdaMultithreaded.assertStack(TestLambdaMultithreaded.java:443(Compiled Code))
4XESTACKTRACE                at net/adoptopenjdk/test/lambda/TestLambdaMultithreaded.runAllOpcodes(TestLambdaMultithreaded.java:271(Compiled Code))
4XESTACKTRACE                at net/adoptopenjdk/test/lambda/TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:235)
4XESTACKTRACE                at net/adoptopenjdk/test/lambda/TestLambdaMultithreaded$$Lambda$317/0x00000000000a11b0.run(Bytecode PC:12)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:884)
```
All allocation requests seems came almost simultaneously but Arraylet spine population by Leaf regions is sequential there are number of Discontiguous arrays with different stage of population. There is how many leaves are populated at the moment (initialization in progress):
```
!j9indexableobject 0x000000001F0001D8	1
!j9indexableobject 0x000000001BC05228	3
!j9indexableobject 0x000000001C19C380	435
!j9indexableobject 0x000000001D000000	78
!j9indexableobject 0x000000001EA001A8	449
!j9indexableobject 0x000000001F09B280	91
!j9indexableobject 0x000000001D096388	449
!j9indexableobject 0x000000001E886148	449
```
(there is 1955 in this list but 1957 leaves total - so I missed two somewhere but it is not relevant for the picture)

All this objects have strong roots from O-slots so can not be collected.

There is obvious potential minor improvement in GC behaviour - There are more objects in initialization stage than heap can take - GC should not even start allocation of so many objects. However because of race between these allocations we got exhaustion of free regions list on this stage.

So returning back to original questions:
- why it goes to OOM state?
   It still be opened. I think it make sense to investigate (I guess looking to test source code vs. behaviour we have in JIT/VM)

- why we have java.lang.StringIndexOutOfBoundsException thrown?
  I guess it might be because we have number of arrays in partially initialized state with OOM condition race between threads a partially initialized array triggered this exception later on.

@pshipton Would you please coordinate actions on this item? The OOM might happen (for example) because extended object life due aggressive liveness or something is not handled properly for Lambda handling. I am not sure what else I can do here from GC point of view.
