### ISSUE TITLE
Crash when specifying log name in both -Xjit and -Xaot

### ISSUE THREAD

**Issue by a7ehuo** [eclipse-openj9/openj9#13607]
When trying to collect trace log using the following options to both `-Xjit` and `-Xaot` [1], I ran into a crash in `TR_Debug::findLogFile`. The `prev->_options->_logFileName` is invalid [2].  I found that what happened is when `jitLatePostProcess` calls _`debug->findLogFile`, it doesn't differentiate whether or not it is for AOT or JIT [3]. It calls both both when it's only parsing for AOT options[4].  

One fix I'd propose is to add a default argument `isAOT` to `jitLatePostProcess`. The default value is `false`. In `jitLatePostProcess`, we could call `findLogFile` based on which option it is [5]. 

[1]
```
export TR_Options="verbose,vlog=vlog,{*WrappingSpliterator.lambda*initPartialTraversalState*,*ArrayListSpliterator.tryAdvance*,*ReferencePipeline*.accept*}(traceFull,traceILGen,traceCG,traceRelocatableDataCG,traceRelocatableDataDetailsCG,log=logjit)"

export TR_OptionsAOT="aotrtDebugLevel=30,rtLog=rtLog,{*WrappingSpliterator.lambda*initPartialTraversalState*,*ArrayListSpliterator.tryAdvance*,*ReferencePipeline*.accept*}(traceFull,traceILGen,traceCG,traceRelocatableDataCG,traceRelocatableDataDetailsCG,log=logaot)"
```

[2]
```
(gdb) bt
#0  0x00007ffff795bf9b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffefa9e8a0 in TR_Debug::findLogFile (this=<optimized out>, cmdLineOptions=<optimized out>, 
    optSet=0x7fffe2f30ef0, logFileName=0x7fffe2faba10 "logaot")
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/ras/OptionsDebug.cpp:86
#2  0x00007fffef727fa4 in OMR::Options::jitLatePostProcess (this=0x7fffe2fab5c0, optionSet=optionSet@entry=0x7fffe2f30ef0, 
    jitConfig=jitConfig@entry=0x7ffff00b7940, isAOT=isAOT@entry=true)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/control/OMROptions.cpp:2321
#3  0x00007fffef728e76 in OMR::Options::latePostProcess (options=0x7fffe2f301c0, jitConfig=jitConfig@entry=0x7ffff00b7940, 
    isAOT=isAOT@entry=true) at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/control/OMROptions.cpp:1956
#4  0x00007fffef728ff0 in OMR::Options::latePostProcessAOT (jitConfig=jitConfig@entry=0x7ffff00b7940)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/control/OMROptions.cpp:1917
#5  0x00007fffef374dfd in aboutToBootstrap (javaVM=javaVM@entry=0x7ffff000f710, jitConfig=0x7ffff00b7940)
    at /root/home/ahuo/src/openj9-openjdk-jdk/openj9/runtime/compiler/control/rossa.cpp:1880
#6  0x00007fffef35b3eb in J9VMDllMain (vm=0x7ffff000f710, stage=<optimized out>, reserved=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk/openj9/runtime/compiler/control/DLLMain.cpp:419
#7  0x00007ffff5f6f4c1 in runJ9VMDllMain (dllLoadInfo=0x7ffff001e228, userDataTemp=0x7ffff6f785b0)
    at /root/home/ahuo/src/openj9-openjdk-jdk/openj9/runtime/vm/jvminit.c:3771

(gdb) fr 1
#1  0x00007fffefa9e8a0 in TR_Debug::findLogFile (this=<optimized out>, cmdLineOptions=<optimized out>, 
    optSet=0x7fffe2f30ef0, logFileName=0x7fffe2faba10 "logaot")
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/ras/OptionsDebug.cpp:86
86	         if (fileName && !STRICMP(logFileName, fileName))

(gdb) print prev->_options->_logFileName
$3 = 0x4000007fffefb879 <error: Cannot access memory at address 0x4000007fffefb879>
```

[3]
https://github.com/eclipse/omr/blob/1ec11640d4974dc68384c032b7118329bd379d7f/compiler/control/OMROptions.cpp#L2306
```c++
            _logFile = _debug->findLogFile(TR::Options::getAOTCmdLineOptions(), TR::Options::getJITCmdLineOptions(), optionSet, _logFileName);
```

[4]
```
findLogFile: call findLogFile for aotCmdLineOptions logFileName logaot
TR_Debug::findLogFile: cmdLineOptions 0x7fffe2f301c0 optSet 0x7fffe2f30ef0, logFileName logaot
TR_Debug::findLogFile: fileName 
findLogFile: call findLogFile for jitCmdLineOptions logFileName logaot
TR_Debug::findLogFile: cmdLineOptions 0x7fffe2f30f30 optSet 0x7fffe2f30ef0, logFileName logaot
TR_Debug::findLogFile: fileName 
TR_Debug::findLogFile: prev 0x7fffe2f31b80 fileName 0x4000007fffefb879
```

[5]
```
OMR::Options::jitLatePostProcess(TR::OptionSet *optionSet, void * jitConfig, bool isAOT)
...
            if (isAOT)
               {
               _logFile = _debug->findLogFile(TR::Options::getAOTCmdLineOptions(), NULL, optionSet, _logFileName);
               }
            else
               {
               _logFile = _debug->findLogFile(NULL, TR::Options::getJITCmdLineOptions(), optionSet, _logFileName);
               }
```

**Comment by a7ehuo** [comment]
This is an OMR issue. I'lll reopen it in https://github.com/eclipse/omr

**Comment by a7ehuo** [comment]
https://github.com/eclipse/omr/issues/6189
