### ISSUE TITLE
ParallelStreamsLoadTest_CS testRanContainLetter IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13636]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_aarch64_linux_Nightly_testList_1/1
ParallelStreamsLoadTest_CS_0
-Xgcpolicy:gencon -Xgc:concurrentScavenge 
```
LT  testStarted : testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFailure: testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations): Comparison method violates its general contract!
LT  java.lang.IllegalArgumentException: Comparison method violates its general contract!
LT  	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
LT  	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
LT  	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
LT  	at java.base/java.util.TimSort.sort(TimSort.java:254)
LT  	at java.base/java.util.Arrays.sort(Arrays.java:1546)
LT  	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
LT  	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
LT  	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
LT  	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
LT  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:498)
LT  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
LT  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
LT  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
LT  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.lambda$testRanContainLetter$20(TestParallelStreamOperations.java:230)
LT  	at <unknown class>.run(Unknown Source)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.runTest(TestParallelStreamOperations.java:343)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.testRanContainLetter(TestParallelStreamOperations.java:203)
```
@knn-k fyi

**Comment by knn-k** [comment]
3 failures in a 20x Grinder job.  https://openj9-jenkins.osuosl.org/job/Grinder/260/tapResults/

**Comment by pshipton** [comment]
3/20 qualifies as a blocker.

**Comment by knn-k** [comment]
No failures in 30x Grinder run: https://openj9-jenkins.osuosl.org/job/Grinder/270/
The Grinder run disables the new entry points of arraycopy helper added by eclipse/omr#6188.

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/6200 as a temporary fix.
It does not apply to v.0.29.

**Comment by knn-k** [comment]
I also opened #13674 for v.0.29.0.
