### ISSUE TITLE
JDK17 head : NPE at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:352)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13648]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_special.system_x86-64_linux_testList_0/67/tapResults/`:
```
openjdk version "17-beta" 2021-09-14
IBM Semeru Runtime Open Edition 17+35-202110060425 (build 17-beta+35-202110060425)
Eclipse OpenJ9 VM 17+35-202110060425 (build master-71af7ab90, JRE 17 Linux amd64-64-Bit Compressed References 20211006_9 (JIT enabled, AOT enabled)
OpenJ9   - 71af7ab90
OMR      - e34d64c29
JCL      - 480d595b54 based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_special.system_x86-64_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9%2F9%2Fibm-semeru-open-testimage_x64_linux_JDK17U_2021-10-06-04-06.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9%2F9%2Fibm-semeru-open-debugimage_x64_linux_JDK17U_2021-10-06-04-06.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9%2F9%2Fibm-semeru-open-jdk_x64_linux_JDK17U_2021-10-06-04-06.tar.gz&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=69&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test ClassLoadingTest_special_5m_29 ...
===============================================
ClassLoadingTest_special_5m_29 Start Time: Wed Oct  6 07:51:51 2021 Epoch Time (ms): 1633531911875
variation: -Xgcpolicy:gencon -Xgc:dynamicBreadthFirstScanOrdering
JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:dynamicBreadthFirstScanOrdering 

CLT 07:51:55.987 - Starting thread. Suite=0 thread=9
CLT 07:52:13.726 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
CLT 07:52:13.749 - Test failed. Details recorded in execution log.
CLT 07:52:13.756 - Test failed
CLT   Failure num.  = 1
CLT   Test number   = 0
CLT   Test details  = 'ArbitraryJava[net.adoptopenjdk.test.classloading.deadlock.DeadlockTest runTest]'
CLT   Suite number  = 0
CLT   Thread number = 2
CLT >>> Captured test output >>>
CLT Test failed:
CLT java.lang.NullPointerException
CLT 	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:352)
CLT 	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:374)
CLT 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
CLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
CLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
CLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH)
CLT 	at net.adoptopenjdk.test.classloading.deadlock.DeadlockTest.main(DeadlockTest.java:81)
CLT 	at net.adoptopenjdk.test.classloading.deadlock.DeadlockTest.runTest(DeadlockTest.java:59)
CLT 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
CLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
CLT 	at java.base/java.lang.Thread.run(Thread.java:884)
CLT <<<

CLT 07:52:13.979 - Load test completed
CLT 07:52:13.980 -   Ran     : 2995
CLT 07:52:13.980 -   Passed  : 2985
CLT 07:52:13.980 -   Failed  : 10
CLT 07:52:13.981 -   Result  : FAILED
CLT 07:52:13.981 - Note that only the first 1 failures have been reported
STF 07:52:14.179 - **FAILED** Process CLT ended with exit code (1) and not the expected exit code/s (0)
STF 07:52:14.179 - Monitoring Report Summary:
STF 07:52:14.179 -   o Process CLT ended with exit code (1) and not the expected exit code/s (0)
STF 07:52:14.179 - Killing processes: CLT
STF 07:52:14.179 -   o Process CLT pid 24405 is not running
**FAILED** at step 1 (Run classloading tests). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk17_j9_special.system_x86-64_linux_testList_0/aqa-tests/TKG/../TKG/output_16335147717819/ClassLoadingTest_special_5m_29/20211006-075152-ClassloadingLoadTest/execute.pl line 97.
STF 07:52:14.211 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 07:52:14.211 - 
STF 07:52:14.211 - ====================   T E A R D O W N   ====================
STF 07:52:14.211 - Running teardown: perl /home/jenkins/workspace/Test_openjdk17_j9_special.system_x86-64_linux_testList_0/aqa-tests/TKG/../TKG/output_16335147717819/ClassLoadingTest_special_5m_29/20211006-075152-ClassloadingLoadTest/tearDown.pl
STF 07:52:14.254 - TEARDOWN stage completed
STF 07:52:14.260 - 
STF 07:52:14.261 - =====================   R E S U L T S   =====================
STF 07:52:14.261 - Stage results:
STF 07:52:14.261 -   setUp:     pass
STF 07:52:14.261 -   execute:  *fail*
STF 07:52:14.261 -   teardown:  pass
STF 07:52:14.261 - 
STF 07:52:14.261 - Overall result: **FAILED**

ClassLoadingTest_special_5m_29_FAILED
```

**Comment by JasonFengJ9** [comment]
Not seen in recent builds.

Closing (re-open if occurs again)
