### ISSUE TITLE
JDK17 aarch64_linux - StreamLinkTest.java - StackOverflowError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13652]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/56/consoleFull` (`fuji`):
```
04:01:06  =JAVA VERSION OUTPUT BEGIN=
04:01:06  openjdk version "17-beta" 2021-09-14
04:01:06  IBM Semeru Runtime Open Edition 17+35-202110060419 (build 17-beta+35-202110060419)
04:01:06  Eclipse OpenJ9 VM 17+35-202110060419 (build master-71af7ab90, JRE 17 Linux aarch64-64-Bit Compressed References 20211006_9 (JIT enabled, AOT enabled)
04:01:06  OpenJ9   - 71af7ab90
04:01:06  OMR      - e34d64c29
04:01:06  JCL      - 480d595b54 based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F9%2Fibm-semeru-open-debugimage_aarch64_linux_JDK17U_2021-10-06-04-07.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F9%2Fibm-semeru-open-testimage_aarch64_linux_JDK17U_2021-10-06-04-07.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F9%2Fibm-semeru-open-jdk_aarch64_linux_JDK17U_2021-10-06-04-07.tar.gz&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
05:08:41  ===============================================
05:08:41  Running test jdk_util_1 ...
05:08:41  ===============================================

05:31:58  --------------------------------------------------
05:31:58  TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java

05:31:58  test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("ArrayList.asList:0..1000", java.util.stream.TestData$AbstractTestData$RefTestData@e72138b): failure
05:31:58  java.lang.AssertionError: 1 failure(s) for test data: RefTestData[ArrayList.asList:0..1000]
05:31:58  1: java.lang.Error: STREAM_SPLITERATOR: java.lang.StackOverflowError
05:31:58  java.lang.StackOverflowError
05:31:58  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
05:31:58  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

05:31:58  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
05:31:58  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
05:31:58  	at java.base/java.util.stream.SpinedBuffer$1Splitr.tryAdvance(SpinedBuffer.java:332)
05:31:58  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
05:31:58  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$104/0x0000000000000000.getAsBoolean(Unknown Source)
05:31:58  	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
05:31:58  	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
05:31:58  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
05:31:58  	at java.base/java.util.stream.StreamTestScenario$5.run(StreamTestScenario.java:90)
05:31:58  	at java.base/java.util.stream.StreamTestScenario.run(StreamTestScenario.java:272)
05:31:58  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:404)
05:31:58  	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
05:31:58  	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
05:31:58  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:31:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
05:31:58  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
05:31:58  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
05:31:58  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
05:31:58  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
05:31:58  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
05:31:58  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
05:31:58  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
05:31:58  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
05:31:58  	at <unknown class>.accept(Unknown Source)
05:31:58  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
05:31:58  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
05:31:58  	at org.testng.TestRunner.run(TestRunner.java:585)
05:31:58  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
05:31:58  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
05:31:58  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
05:31:58  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
05:31:58  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
05:31:58  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
05:31:58  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
05:31:58  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
05:31:58  	at org.testng.TestNG.runSuites(TestNG.java:1069)
05:31:58  	at org.testng.TestNG.run(TestNG.java:1037)
05:31:58  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
05:31:58  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
05:31:58  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:31:58  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
05:31:58  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:31:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
05:31:58  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
05:31:58  	at java.base/java.lang.Thread.run(Thread.java:884)
05:31:58  --
05:31:58  	at org.testng.Assert.fail(Assert.java:99)
05:31:58  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:444)
05:31:58  	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
05:31:58  	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
05:31:58  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:31:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
05:31:58  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
05:31:58  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
05:31:58  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
05:31:58  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
05:31:58  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
05:31:58  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
05:31:58  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
05:31:58  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
05:31:58  	at <unknown class>.accept(Unknown Source)
05:31:58  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
05:31:58  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
05:31:58  	at org.testng.TestRunner.run(TestRunner.java:585)
05:31:58  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
05:31:58  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
05:31:58  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
05:31:58  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
05:31:58  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
05:31:58  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
05:31:58  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
05:31:58  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
05:31:58  	at org.testng.TestNG.runSuites(TestNG.java:1069)
05:31:58  	at org.testng.TestNG.run(TestNG.java:1037)
05:31:58  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
05:31:58  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
05:31:58  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:31:58  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
05:31:58  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:31:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
05:31:58  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
05:31:58  	at java.base/java.lang.Thread.run(Thread.java:884)
05:31:58  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@7711e7c): success
05:31:58  
05:31:58  ===============================================
05:31:58  java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
05:31:58  Total tests run: 180, Passes: 102, Failures: 78, Skips: 0
05:31:58  ===============================================

05:31:58  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 78
05:31:58  --------------------------------------------------
05:35:58  Test results: passed: 886; failed: 1
05:36:03  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
05:36:03  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux/aqa-tests/TKG/output_16335073873783/jdk_util_1/work
05:36:03  Error: Some tests failed or other problems occurred.
05:36:03  
05:36:03  jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/64/ - ub20-aarch64-2
jdk_util_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops`
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java

```
22:25:14  test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("ArrayList.asList:0..1000", java.util.stream.TestData$AbstractTestData$RefTestData@71137326): failure
22:25:14  java.lang.AssertionError: 11 failure(s) for test data: RefTestData[ArrayList.asList:0..1000]
22:25:14  1: java.lang.Error: PAR_STREAM_SPLITERATOR_FOREACH: java.lang.StackOverflowError
22:25:14  java.lang.StackOverflowError
22:25:14  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
22:25:14  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
22:25:14  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
...
22:25:14  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
22:25:14  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
22:25:14  	at java.base/java.util.stream.SpinedBuffer$1Splitr.tryAdvance(SpinedBuffer.java:332)
22:25:14  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
22:25:14  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$153/0x0000000000000000.getAsBoolean(Unknown Source)
22:25:14  	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
22:25:14  	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
22:25:14  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
22:25:14  	at java.base/java.util.SpliteratorTestHelper.mixedTraverseAndSplit(SpliteratorTestHelper.java:660)
22:25:14  	at java.base/java.util.stream.StreamTestScenario$6.run(StreamTestScenario.java:99)
22:25:14  	at java.base/java.util.stream.StreamTestScenario.run(StreamTestScenario.java:272)
22:25:14  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:404)
22:25:14  	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
22:25:14  	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
22:25:14  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:25:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:25:14  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:25:14  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:25:14  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:25:14  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:25:14  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:25:14  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:25:14  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:25:14  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:25:14  	at org.testng.TestRunner$$Lambda$100/0x0000000000000000.accept(Unknown Source)
22:25:14  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
22:25:14  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
22:25:14  	at org.testng.TestRunner.run(TestRunner.java:585)
22:25:14  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:25:14  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:25:14  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:25:14  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:25:14  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:25:14  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:25:14  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:25:14  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:25:14  	at org.testng.TestNG.runSuites(TestNG.java:1069)
22:25:14  	at org.testng.TestNG.run(TestNG.java:1037)
22:25:14  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:25:14  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:25:14  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:25:14  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:25:14  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:25:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:25:14  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:25:14  	at java.base/java.lang.Thread.run(Thread.java:884)
22:25:14  --
22:25:14  	at org.testng.Assert.fail(Assert.java:99)
22:25:14  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:444)
22:25:14  	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
22:25:14  	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
22:25:14  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:25:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:25:14  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:25:14  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:25:14  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:25:14  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:25:14  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:25:14  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:25:14  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:25:14  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:25:14  	at org.testng.TestRunner$$Lambda$100/0x0000000000000000.accept(Unknown Source)
22:25:14  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
22:25:14  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
22:25:14  	at org.testng.TestRunner.run(TestRunner.java:585)
22:25:14  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:25:14  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:25:14  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:25:14  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:25:14  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:25:14  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:25:14  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:25:14  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:25:14  	at org.testng.TestNG.runSuites(TestNG.java:1069)
22:25:14  	at org.testng.TestNG.run(TestNG.java:1037)
22:25:14  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:25:14  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:25:14  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:25:14  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:25:14  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:25:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:25:14  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:25:14  	at java.base/java.lang.Thread.run(Thread.java:884)
22:25:14  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@39b1337d): success
```

**Comment by pshipton** [comment]
I'm not sure what the grinder was testing, but you may need to run all `jdk_util_1` to reproduce it.

**Comment by pshipton** [comment]
See also https://github.com/eclipse-openj9/openj9/issues/14031
There is an internal 50x grinder which repeated the failure once.

**Comment by knn-k** [comment]
I reproduced the failure locally, 1 out of 50 runs.
I repeatedly ran StreamLinkTest only, as follows:
```
$ JDK_CUSTOM_TARGET=java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java make _jdk_custom_0
```

**Comment by knn-k** [comment]
I ran java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java with JDK 17 on AArch64 Linux 40 times, and got no failures.
https://openj9-jenkins.osuosl.org/job/Grinder/1315/
