### ISSUE TITLE
ClassLoadingTest_special_5m NullPointerException net.adoptopenjdk.test.classloading.ClassMapHog.addClass

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13677]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_special.system_x86-64_windows_Personal_testList_2/40
ClassLoadingTest_special_5m_8
-Xgcpolicy:gencon -Xshareclasses -Xjit -Xnocompressedrefs

```
CLT 10:19:08.580 - Completed 26.7%. Number of tests started=14804 (+3578)
CLT 10:19:19.580 - First failure detected by thread: load-5. Not creating dumps as no dump generation is requested for this load test
CLT 10:19:19.580 - Test failed
CLT   Failure num.  = 1
CLT   Test number   = 1
CLT   Test details  = 'ArbitraryJava[net.adoptopenjdk.test.classloading.ClassMapHog run]'
CLT   Suite number  = 0
CLT   Thread number = 5
CLT >>> Captured test output >>>
CLT Loaded Class: java.applet.AudioClip
CLT Loaded Class: java.beans.AppletInitializer
CLT Test failed:
CLT java.lang.NullPointerException
CLT 	at net.adoptopenjdk.test.classloading.ClassMapHog.addClass(ClassMapHog.java:226)
CLT 	at net.adoptopenjdk.test.classloading.ClassMapHog.run(ClassMapHog.java:126)
CLT 	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
CLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
CLT 	at java.base/java.lang.Thread.run(Thread.java:866)
```

Seen in the past https://github.com/eclipse-openj9/openj9/issues/8707

**Comment by pshipton** [comment]
Started 6x x 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/273/

**Comment by hzongaro** [comment]
Encountered an instance of this in a personal build internally:  https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.system_x86-64_linux_Personal_testList_1/423/
