### ISSUE TITLE
CriticalRegionTest testAcquireAndSleep_Threads1: not all threads completed before the timeout (0/1)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13684]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/11/ - cent6-x64-7
J9vmTest_3 -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 
```
+++ j9vm.test.jni.CriticalRegionTest: +++
command: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/bin/java  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m   -Xbootclasspath:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/jre/lib/amd64/default/jclSC180/vm.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/jre/lib/se-service.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/jre/lib/rt.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/jre/lib/resources.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/jre/lib/jsse.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/jre/lib/charsets.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/openjdkbinary/j2sdk-image/jre/lib/jce.jar -classpath /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Release_testList_1/aqa-tests/TKG/../TKG/lib/asm-all.jar  j9vm.test.jni.CriticalRegionTest 

Exception in thread "main" java.lang.RuntimeException: testAcquireAndSleep_Threads1: not all threads completed before the timeout (0/1)
	at j9vm.test.jni.CriticalRegionTest.reportError(CriticalRegionTest.java:154)
	at j9vm.test.jni.CriticalRegionTest.testAcquireAndSleep(CriticalRegionTest.java:786)
	at j9vm.test.jni.CriticalRegionTest.runBlockingTests(CriticalRegionTest.java:732)
	at j9vm.test.jni.CriticalRegionTest.main(CriticalRegionTest.java:191)
no-zero exit value: 1
*** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Nightly_testList_1/42
J9vmTest_4
```
+++ j9vm.test.jni.CriticalRegionTest: +++
command: /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xms64m -Xmx64m    -classpath /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../TKG/lib/asm-all.jar  j9vm.test.jni.CriticalRegionTest 

Exception in thread "main" java.lang.RuntimeException: testAcquireAndGC_Sleepers1_GCers1: not all threads completed before the timeout (1/2)
	at j9vm.test.jni.CriticalRegionTest.reportError(CriticalRegionTest.java:154)
	at j9vm.test.jni.CriticalRegionTest.testAcquireAndGC(CriticalRegionTest.java:879)
	at j9vm.test.jni.CriticalRegionTest.runNonBlockingTests(CriticalRegionTest.java:742)
	at j9vm.test.jni.CriticalRegionTest.main(CriticalRegionTest.java:198)
no-zero exit value: 1
*** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_0/88
J9vmTest_0
```
02:29:22  +++ j9vm.test.jni.CriticalRegionTest: +++
02:29:22  command: /home/jenkins/workspace/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m -classpath /home/jenkins/workspace/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_0/../../testDependency/lib/asm-all.jar j9vm.test.jni.CriticalRegionTest 
02:29:22  
02:29:22  WARNING: A restricted method in java.lang.System has been called
02:29:22  WARNING: java.lang.System::loadLibrary has been called by j9vm.test.jni.CriticalRegionTest in an unnamed module (file:/home/jenkins/workspace/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_0/jvmtest/functional/VM_Test/VM_Test.jar)
02:29:22  WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
02:29:22  WARNING: Restricted methods will be blocked in a future release unless native access is enabled
02:29:22  
02:29:34  Exception in thread "main" java.lang.RuntimeException: testAcquireAndSleep_Threads8: not all threads completed before the timeout (7/8)
02:29:34  	at j9vm.test.jni.CriticalRegionTest.reportError(CriticalRegionTest.java:152)
02:29:34  	at j9vm.test.jni.CriticalRegionTest.testAcquireAndSleep(CriticalRegionTest.java:784)
02:29:34  	at j9vm.test.jni.CriticalRegionTest.runBlockingTests(CriticalRegionTest.java:732)
02:29:34  	at j9vm.test.jni.CriticalRegionTest.main(CriticalRegionTest.java:189)
02:29:34  non-zero exit value: 1
02:29:34  *** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_sanity.functional_x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/1015/)(`macx64rt22`)
```
[2026-01-23T15:55:48.339Z] Running test J9vmTest_7 ...
[2026-01-23T15:55:48.339Z] ===============================================
[2026-01-23T15:55:48.339Z] J9vmTest_7 Start Time: Fri Jan 23 07:55:35 2026 Epoch Time (ms): 1769183735403
[2026-01-23T15:55:48.339Z] variation: Mode610
[2026-01-23T15:55:48.339Z] JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 

[2026-01-23T15:57:14.470Z] +++ j9vm.test.jni.CriticalRegionTest: +++
[2026-01-23T15:57:14.470Z] command: /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/jdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump -Xms64m -Xmx64m -classpath /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_testList_1/../../externalDependency/lib/asm-all.jar j9vm.test.jni.CriticalRegionTest 
[2026-01-23T15:57:14.470Z] 
[2026-01-23T15:57:37.322Z] Exception in thread "main" java.lang.RuntimeException: testAcquireAndSleep_Threads8: not all threads completed before the timeout (0/8)
[2026-01-23T15:57:37.323Z] 	at j9vm.test.jni.CriticalRegionTest.reportError(CriticalRegionTest.java:152)
[2026-01-23T15:57:37.323Z] 	at j9vm.test.jni.CriticalRegionTest.testAcquireAndSleep(CriticalRegionTest.java:784)
[2026-01-23T15:57:37.323Z] 	at j9vm.test.jni.CriticalRegionTest.runBlockingTests(CriticalRegionTest.java:732)
[2026-01-23T15:57:37.323Z] 	at j9vm.test.jni.CriticalRegionTest.main(CriticalRegionTest.java:189)
[2026-01-23T15:57:37.323Z] non-zero exit value: 1
[2026-01-23T15:57:37.323Z] *** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/57774/) - 40 passed, others are infra errors.

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.functional_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.functional_aarch64_mac/167/)
```
[2026-03-22T10:20:04.625Z] Running test J9vmTest_5 ...
[2026-03-22T10:20:04.625Z] ===============================================
[2026-03-22T10:20:04.625Z] J9vmTest_5 Start Time: Sun Mar 22 03:20:04 2026 Epoch Time (ms): 1774174804315
[2026-03-22T10:20:04.625Z] variation: Mode501 -XXgc:disableVirtualLargeObjectHeap
[2026-03-22T10:20:04.625Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -XXgc:disableVirtualLargeObjectHeap 

[2026-03-22T10:21:30.607Z] +++ j9vm.test.jni.CriticalRegionTest: +++
[2026-03-22T10:21:30.607Z] command: /Users/jenkins/workspace/Test_openjdk25_j9_sanity.functional_aarch64_mac/jdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -XXgc:disableVirtualLargeObjectHeap  -Xdump -Xms64m -Xmx64m -classpath /Users/jenkins/workspace/Test_openjdk25_j9_sanity.functional_aarch64_mac/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/Users/jenkins/workspace/Test_openjdk25_j9_sanity.functional_aarch64_mac/../../externalDependency/lib/asm-all.jar j9vm.test.jni.CriticalRegionTest 
[2026-03-22T10:21:30.607Z] 
[2026-03-22T10:21:39.374Z] Exception in thread "main" java.lang.RuntimeException: testAcquireAndSleep_Threads1: not all threads completed before the timeout (0/1)
[2026-03-22T10:21:39.374Z] 	at j9vm.test.jni.CriticalRegionTest.reportError(CriticalRegionTest.java:152)
[2026-03-22T10:21:39.374Z] 	at j9vm.test.jni.CriticalRegionTest.testAcquireAndSleep(CriticalRegionTest.java:784)
[2026-03-22T10:21:39.374Z] 	at j9vm.test.jni.CriticalRegionTest.runBlockingTests(CriticalRegionTest.java:730)
[2026-03-22T10:21:39.374Z] 	at j9vm.test.jni.CriticalRegionTest.main(CriticalRegionTest.java:189)
[2026-03-22T10:21:39.374Z] non-zero exit value: 1
[2026-03-22T10:21:39.374Z] *** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```
