### ISSUE TITLE
MauveMultiThrdLoad_5m_1 IncompatibleClassChangeError AcuniaAbstractMapTest.test_equals

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13701]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly_testList_1/122
MauveMultiThrdLoad_5m_1 -XX:-UseCompressedOops
```
LT  Test failed:
LT  java.lang.IncompatibleClassChangeError
LT  	at java.base/java.util.AbstractMap.equals(AbstractMap.java:482)
LT  	at gnu.testlet.java.util.AbstractMap.AcuniaAbstractMapTest.test_equals(AcuniaAbstractMapTest.java:322)
LT  	at gnu.testlet.java.util.AbstractMap.AcuniaAbstractMapTest.test(AcuniaAbstractMapTest.java:56)
LT  	at jdk.internal.reflect.GeneratedMethodAccessor2650.invoke(Unknown Source)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
LT  	at java.base/java.lang.Thread.run(Thread.java:866)
LT  <<<
```

Possibly exposed by https://github.com/eclipse-openj9/openj9/issues/13561

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_ppc64le_linux_Release/63/tapResults/
```
openjdk version "1.8.0_382-internal"
OpenJDK Runtime Environment (build 1.8.0_382-internal-jenkins_2023_07_15_20_02-b00)
Eclipse OpenJ9 VM (build v0.40.0-release-b681a676a47, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20230715_73 (JIT enabled, AOT enabled)
OpenJ9   - b681a676a47
OMR      - e80bff83b7f
JCL      - 347f96b63ac based on jdk8u382-b04)

variation: Mode650
JVM_OPTIONS:  -XX:-UseCompressedOops 

LT  01:52:47.343 - Starting thread. Suite=0 thread=2
LT  01:53:05.250 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
LT  01:53:05.250 - Test failed
LT    Failure num.  = 1
LT    Test number   = 15
LT    Test details  = 'Mauve[gnu.testlet.java.beans.PropertyDescriptor.constructorTest1]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.java.beans.PropertyDescriptor.constructorTest1 (number 0)
LT  PASS: gnu.testlet.java.beans.PropertyDescriptor.constructorTest1 (number 1)
LT  Test failed:
LT  java.lang.IncompatibleClassChangeError
LT  	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:175)
LT  	at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:81)
LT  	at java.beans.FeatureDescriptor.getReturnType(FeatureDescriptor.java:370)
LT  	at java.beans.PropertyDescriptor.findPropertyType(PropertyDescriptor.java:648)
LT  	at java.beans.PropertyDescriptor.setReadMethod(PropertyDescriptor.java:257)
LT  	at java.beans.PropertyDescriptor.getReadMethod(PropertyDescriptor.java:235)
LT  	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:106)
LT  	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:71)
LT  	at gnu.testlet.java.beans.PropertyDescriptor.constructorTest1.test(constructorTest1.java:83)
LT  	at sun.reflect.GeneratedMethodAccessor1879.invoke(Unknown Source)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:826)
LT  <<<
```
