### ISSUE TITLE
JVMTI VMStart callback is not called?

### ISSUE THREAD

**Issue by AntonKatilin** [eclipse-openj9/openj9#13708]
We started experiencing strange exceptions or even JVM crashes while testing the OpenJ9 Java 17 milestone 2 with YourKit Java Profiler agent (we're working on adding official support of OpenJ9 Java 17).

The JVM is:

openjdk version "17" 2021-09-14
IBM Semeru Runtime Open Edition 17.0.0.0-m1 (build 17+35)
Eclipse OpenJ9 VM 17.0.0.0-m1 (build openj9-0.28.0-m2, JRE 17 Windows 10 amd64-64-Bit Compressed References 20210916_31 (JIT enabled, AOT enabled)
OpenJ9   - 12ac773fe
OMR      - 377314cb0
JCL      - 41171df43e2 based on jdk-17+35)
)

When tracing starts, java.lang.UnsatisfiedLinkError with message like "attempt to recursively bind a native method" for the profiler callbacks is thrown. There is no problem with older OpenJ9 versions (Java 8, java 11, Java 16) with the same agent and options.

As we discovered from the agent logs, the problem happens likely due to the fact that VMStart is not called, and the call to jni->RegisterNatives(...) which the agent performs in VMStart does not run.

**Comment by AntonKatilin** [comment]
Update: the situation is even more interesting.

Java 8 (0.27.0) does issue VMStart, but Java 11 (same) and newer do not.

However, it seems that Java 11 and Java 16 are able to implicitly bind natives even when jni->RegisterNatives(...) is not performed, but since Java 17 the implicit binding no longer works for some reason.

So we have 2 questions:

1. Why Java 11+ does not call VMStart?
2. Why Java 17 cannot implicitly bind natives anymore?

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this

**Comment by gacholio** [comment]
Do you get the event on hotspot if you don't specify can_generate_early_vmstart?

**Comment by pshipton** [comment]
Does the implicit binding work on Java 17 Hotspot? I don't expect we should be looking at that aspect unless it does.

**Comment by AntonKatilin** [comment]
Maybe I'm doing something wrong, but the download does not work for me. I tried both a web browser and wget in console.

```
$ wget https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_x86-64_windows_Nightly/52/OpenJ9-JDK17-x86-64_windows-20211013-201035.tar.gz
--2021-10-15 13:30:27--  https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_x86-64_windows_Nightly/52/OpenJ9-JDK17-x86-64_windows-20211013-201035.tar.gz
Resolving openj9-artifactory.osuosl.org (openj9-artifactory.osuosl.org)... 140.211.168.230
Connecting to openj9-artifactory.osuosl.org (openj9-artifactory.osuosl.org)|140.211.168.230|:443... failed: Connection timed out.
Retrying.
```

Is it expected to work without a login?

**Comment by pshipton** [comment]
No login is required. It's been working for months, but we started experiencing a problem with the artifactory server last night, the machine is no longer responding. I hope it will be fixed later today. https://openj9.slack.com/archives/CDS7QE9HB/p1634265828025100

**Comment by AntonKatilin** [comment]
The latest build

> openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.buildjdk17x86-64windowsnightly)
Eclipse OpenJ9 VM (build v0.29.0-release-f884985e101, JRE 17 Windows 10 amd64-64-Bit Compressed References 20211013_52 (JIT enabled, AOT enabled)
OpenJ9   - f884985e101
OMR      - 299b6a2
JCL      - 23999d8072a based on jdk-17+35)

crashes:

> $ java -agentlib:yjpagent=_no_java_version_check,tracing -jar SwingSet2.jar
[YourKit Java Profiler 2021.3-b233] Log file: C:\Users\anton\.yjp\log\SwingSet2-3512.log
Unhandled exception
Type=Segmentation error vmState=0x00070000
Windows_ExceptionCode=c00000fd J9Generic_Signal=00000004 ExceptionAddress=00007FFA288B5675 ContextFlags=0010005f
Handler1=00007FFA2D1D6470 Handler2=00007FFA34ADA8F0
RDI=00000223CAF364D0 RSI=0000000000256E00 RAX=0000000000257808 RBX=00000223B55AFE08
RCX=00000223B55AFE08 RDX=000000000003D100 R8=0000000000000000 R9=00000223CAF364D0
R10=00007FFA28C41000 R11=00000223CAF3655F R12=0000000000000000 R13=00000223B55AFDC8
R14=0000000000000000 R15=000000000003D100
RIP=00007FFA288B5675 RSP=000000794DD03FE0 RBP=000000794DD040E0 EFLAGS=0000000000010202
FS=0053 ES=002B DS=002B

**Comment by ChengJin01** [comment]
Given verifier specific code is platform independent, I tried to the following command on Linux with the build generated locally (the YourKit Java Profiler agent was downloaded from https://download.yourkit.com/yjp/2020.9/YourKit-JavaProfiler-2020.9-b424.zip)
```
java -agentpath:.../YourKit-JavaProfiler-2021.3/bin/linux-x86-64/libyjpagent.so=_no_java_version_check,tracing -jar SwingSet2.jar
```
which crashed as follows but it has nothing to do with verifier but something else in binding the native method:
```
Thread 22 "YJPAgent-Teleme" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffef51a700 (LWP 196097)]
0x00007ffff5ec0ee0 in omrstr_vprintf (portLibrary=0x7ffff79e9340 <j9portLibrary>, buf=0x0, bufLen=0, 
    format=0x7fff6805cad0 "attempt to recursively bind native method %2$.*1$s.%4$.*3$s%6$.*5$s", args=0x7fffef4db138)
    at /.../openj9-openjdk-jdk17/omr/port/common/omrstr.c:418
418	{
(gdb) bt
#0  0x00007ffff5ec0ee0 in omrstr_vprintf (portLibrary=0x7ffff79e9340 <j9portLibrary>, buf=0x0, bufLen=0, 
    format=0x7fff6805cad0 "attempt to recursively bind native method %2$.*1$s.%4$.*3$s%6$.*5$s", args=0x7fffef4db138)
    at /.../openj9-openjdk-jdk17/omr/port/common/omrstr.c:418
#1  0x00007ffff5ebfee2 in omrstr_printf (portLibrary=<optimized out>, buf=<optimized out>, bufLen=<optimized out>, format=<optimized out>)
    at /.../openj9-openjdk-jdk17/omr/port/common/omrstr.c:198
#2  0x00007ffff5f371d0 in nlsMessageForMethod (currentThread=currentThread@entry=0x25e000, method=<optimized out>, message_num=message_num@entry=71, 
    module_name=1245271629) at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:1063
#3  0x00007ffff5f38a16 in setRecursiveBindError (currentThread=0x25e000, method=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:1093
#4  0x00007ffff5faab5b in VM_BytecodeInterpreterCompressed::resolveNativeAddressWithErrorHandling (this=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2033
#5  VM_BytecodeInterpreterCompressed::bindNative (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2052
#6  VM_BytecodeInterpreterCompressed::run (this=0x7fffef4db5f0, vmThread=0x0)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:10100
#7  0x00007ffff5f95429 in bytecodeLoopCompressed (currentThread=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.inc:112
#8  0x00007ffff6035572 in c_cInterpreter ()
    at /.../openj9-openjdk-jdk17/build/linux-x86_64-server-release/vm/runtime/vm/xcinterp.s:158
#9  0x00007ffff5f20c1a in internalSendExceptionConstructor (currentThread=currentThread@entry=0x25e000, exceptionClass=0x2a0000, exception=0x7fffb2dd8, 
    detailMessage=<optimized out>, detailMessage@entry=0x7fffb2cf8, constructorIndex=<optimized out>, constructorIndex@entry=0)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/callin.cpp:605
#10 0x00007ffff5f379ef in internalSetCurrentExceptionWithCause (currentThread=0x25e000, exceptionNumber=<optimized out>, detailMessage=0x7fffb2cf8, 
    utfMessage=<optimized out>, cause=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:725
#11 0x00007ffff5f37f37 in setCurrentExceptionWithUtfCause (currentThread=<optimized out>, exceptionNumber=<optimized out>, 
    detailMessage=<optimized out>, utfMessage=<optimized out>, cause=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:807
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x00007ffff5f380a6 in setCurrentExceptionUTF (vmThread=0x25e000, exceptionNumber=9, 
    detailUTF=0x7fff68026430 "attempt to recursively bind native method com/yourkit/runtime/Callback.yjpMethodEntry0(I)J")
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:65
#13 0x00007ffff5f38a31 in setRecursiveBindError (currentThread=0x25e000, method=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:1096
#14 0x00007ffff5faab5b in VM_BytecodeInterpreterCompressed::resolveNativeAddressWithErrorHandling (this=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2033
#15 VM_BytecodeInterpreterCompressed::bindNative (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2052
#16 VM_BytecodeInterpreterCompressed::run (this=0x7fffef4dbd70, vmThread=0x0)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:10100
#17 0x00007ffff5f95429 in bytecodeLoopCompressed (currentThread=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.inc:112
#18 0x00007ffff6035572 in c_cInterpreter ()
    at /.../openj9-openjdk-jdk17/build/linux-x86_64-server-release/vm/runtime/vm/xcinterp.s:158
#19 0x00007ffff5f20c1a in internalSendExceptionConstructor (currentThread=currentThread@entry=0x25e000, exceptionClass=0x2a0000, exception=0x7fffb2cd8, 
    detailMessage=<optimized out>, detailMessage@entry=0x7fffb2bf8, constructorIndex=<optimized out>, constructorIndex@entry=0)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/callin.cpp:605
#20 0x00007ffff5f379ef in internalSetCurrentExceptionWithCause (currentThread=0x25e000, exceptionNumber=<optimized out>, detailMessage=0x7fffb2bf8, 
    utfMessage=<optimized out>, cause=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:725
#21 0x00007ffff5f37f37 in setCurrentExceptionWithUtfCause (currentThread=<optimized out>, exceptionNumber=<optimized out>, 
    detailMessage=<optimized out>, utfMessage=<optimized out>, cause=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:807
#22 0x00007ffff5f380a6 in setCurrentExceptionUTF (vmThread=0x25e000, exceptionNumber=9, 
    detailUTF=0x7fff68026380 "attempt to recursively bind native method com/yourkit/runtime/Callback.yjpMethodEntry0(I)J")
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:65
#23 0x00007ffff5f38a31 in setRecursiveBindError (currentThread=0x25e000, method=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:1096
#24 0x00007ffff5faab5b in VM_BytecodeInterpreterCompressed::resolveNativeAddressWithErrorHandling (this=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2033
#25 VM_BytecodeInterpreterCompressed::bindNative (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2052
#26 VM_BytecodeInterpreterCompressed::run (this=0x7fffef4dc4f0, vmThread=0x0)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:10100
#27 0x00007ffff5f95429 in bytecodeLoopCompressed (currentThread=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.inc:112
#28 0x00007ffff6035572 in c_cInterpreter ()
    at /.../openj9-openjdk-jdk17/build/linux-x86_64-server-release/vm/runtime/vm/xcinterp.s:158
#29 0x00007ffff5f20c1a in internalSendExceptionConstructor (currentThread=currentThread@entry=0x25e000, exceptionClass=0x2a0000, exception=0x7fffb2bd8, 
    detailMessage=<optimized out>, detailMessage@entry=0x7fffb2af8, constructorIndex=<optimized out>, constructorIndex@entry=0)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/callin.cpp:605
#30 0x00007ffff5f379ef in internalSetCurrentExceptionWithCause (currentThread=0x25e000, exceptionNumber=<optimized out>, detailMessage=0x7fffb2af8, 
    utfMessage=<optimized out>, cause=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:725
#31 0x00007ffff5f37f37 in setCurrentExceptionWithUtfCause (currentThread=<optimized out>, exceptionNumber=<optimized out>, 
    detailMessage=<optimized out>, utfMessage=<optimized out>, cause=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:807
#32 0x00007ffff5f380a6 in setCurrentExceptionUTF (vmThread=0x25e000, exceptionNumber=9, 
    detailUTF=0x7fff680399b0 "attempt to recursively bind native method com/yourkit/runtime/Callback.yjpMethodEntry0(I)J")
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:65
#33 0x00007ffff5f38a31 in setRecursiveBindError (currentThread=0x25e000, method=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:1096
#34 0x00007ffff5faab5b in VM_BytecodeInterpreterCompressed::resolveNativeAddressWithErrorHandling (this=<optimized out>)
    at /.../openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2033
#35 VM_BytecodeInterpreterCompressed::bindNative (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging-- 
```
with the following stacktrace recursively occurred:
```
#17 0x00007ffff5f38a31 in setRecursiveBindError (currentThread=0x25e000, method=<optimized out>)
    at /home/jincheng/X86_64_OPENJ9/Panama_FFI_support_2021/openj9-openjdk-jdk17/openj9/runtime/vm/exceptionsupport.c:1096
#18 0x00007ffff5faab5b in VM_BytecodeInterpreterCompressed::resolveNativeAddressWithErrorHandling (this=<optimized out>)
    at /home/jincheng/X86_64_OPENJ9/Panama_FFI_support_2021/openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2033
#19 VM_BytecodeInterpreterCompressed::bindNative (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /home/jincheng/X86_64_OPENJ9/Panama_FFI_support_2021/openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:2052
#20 VM_BytecodeInterpreterCompressed::run (this=0x7fffafaa3cb0, vmThread=0x7fffe8089218)
    at /home/jincheng/X86_64_OPENJ9/Panama_FFI_support_2021/openj9-openjdk-jdk17/openj9/runtime/vm/BytecodeInterpreter.hpp:10100
```
which indicates it always ended up with `J9_NATIVE_METHOD_BIND_RECURSIVE` in `resolveNativeAddress` at /runtime/vm/bindnatv.cpp
```
 *  J9_NATIVE_METHOD_BIND_RECURSIVE if another thread is binding the method.
 * 	J9_NATIVE_METHOD_BIND_OUT_OF_MEMORY if scratch space cannot be allocated.
 */
UDATA   
resolveNativeAddress(J9VMThread *currentThread, J9Method *nativeMethod, UDATA runtimeBind)
{
	J9JavaVM * vm = currentThread->javaVM;
	UDATA rc = J9_NATIVE_METHOD_BIND_SUCCESS;
	UDATA bindJNINative = TRUE;
...
	/* Release VM access before acquiring the monitor to prevent deadlock situations */
	internalReleaseVMAccess(currentThread);
	omrthread_monitor_enter(vm->bindNativeMutex);

	/* If the method is already bound, we're done */

	if (!J9_NATIVE_METHOD_IS_BOUND(nativeMethod)) {
		J9NativeMethodBindEntry exemplar;
		J9NativeMethodBindEntry * entry;

		/* See if a table entry exists for this method */
		exemplar.nativeMethod = nativeMethod;
-------> entry = (J9NativeMethodBindEntry*)hashTableFind(vm->nativeMethodBindTable, &exemplar); 
		if (entry != NULL) {
			/* Entry exists, see if a bind is in progress */

			if (entry->state == NATIVE_METHOD_BINDING) {
				/* If the current thread is the one binding, fail out, otherwise wait for the bind to complete */
				if (currentThread == entry->bindThread) {
					rc = J9_NATIVE_METHOD_BIND_RECURSIVE;
				} else {
					++entry->count;
					do {
						omrthread_monitor_wait(vm->bindNativeMutex);
					} while (entry->state == NATIVE_METHOD_BINDING);
					--entry->count;
				}
			}
		} else {
```

**Comment by JasonFengJ9** [comment]
Same observation as https://github.com/eclipse-openj9/openj9/issues/13708#issuecomment-944659635.

**Comment by pshipton** [comment]
@AntonKatilin can you pls confirm a build containing the fix resolves your issues? 
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK17/59/
