### ISSUE TITLE
OpenJDK ImplicitStringConcatManyLongs StackOverflowError BruteArgumentMoverHandle.invokeExact_thunkArchetype_X

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13721]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release/11 - aix71-p8-4
jdk_lang_0 -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage
java/lang/String/concat/ImplicitStringConcatManyLongs.java
```
13:58:28  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.StackOverflowError
13:58:28  REASON: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.cache=true ImplicitStringConcatManyLongs 
13:58:28  TIME:   8.804 seconds
13:58:28  messages:
13:58:28  command: main -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.cache=true ImplicitStringConcatManyLongs
13:58:28  reason: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.cache=true ImplicitStringConcatManyLongs 
13:58:28  Mode: othervm [/othervm specified]
13:58:28  elapsed time (seconds): 8.804
13:58:28  configuration:
13:58:28  STDOUT:
13:58:28  STDERR:
13:58:28  java.lang.StackOverflowError
13:58:28  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
13:58:28  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
13:58:28  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
13:58:28  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
13:58:28  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
13:58:28  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
13:58:28  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
13:58:28  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
...
13:58:28  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
13:58:28  	at ImplicitStringConcatManyLongs.main(ImplicitStringConcatManyLongs.java:147)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release/12
jdk_lang_0 -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage
java/lang/String/concat/ImplicitStringConcatManyLongs.java
```
02:42:26  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.StackOverflowError
02:42:26  REASON: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs 
02:42:26  TIME:   9.634 seconds
02:42:26  messages:
02:42:26  command: main -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs
02:42:26  reason: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs 
02:42:26  Mode: othervm [/othervm specified]
02:42:26  elapsed time (seconds): 9.634
02:42:26  configuration:
02:42:26  STDOUT:
02:42:26  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String
02:42:26  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String
02:42:26  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String
02:42:26  STDERR:
02:42:26  java.lang.StackOverflowError
02:42:26  	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_I(DirectHandle.java:189)
02:42:26  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:123)
02:42:26  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
02:42:26  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
02:42:26  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
02:42:26  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
02:42:26  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
02:42:26  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
...
02:42:26  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
02:42:26  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
02:42:26  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
02:42:26  	at ImplicitStringConcatManyLongs.main(ImplicitStringConcatManyLongs.java:147)

```

**Comment by pshipton** [comment]
Changes from the previous build where it didn't fail, although if it's intermittent this means nothing.

https://github.com/eclipse-openj9/openj9/compare/0aad37c0775...6169ba555b2
https://github.com/eclipse-openj9/openj9-omr/compare/9ebb79cec4b...299b6a2d28c

@0xdaryl @zl-wang @tajila fyi this failure in 0.29.0 release testing first seen this past weekend, and also occurred in the release testing last night. Could this be a regression introduced by changes for Java 17?

**Comment by pshipton** [comment]
Note I did run a grinder in https://github.com/eclipse-openj9/openj9/issues/13721#issuecomment-945717255 without reproducing it, you may need to run all `java_lang_0` rather than the specific test. Also, I haven't seen this problem reported from internal testing yet, maybe something to do with timing on the open machines, which seem very slow lately.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/120/ - aix71-p8-4
jdk_lang_0 -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage
java/lang/String/concat/ImplicitStringConcatManyLongs.java
```
04:50:51  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.StackOverflowError
04:50:51  REASON: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs 
04:50:51  TIME:   10.158 seconds
04:50:51  messages:
04:50:51  command: main -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs
04:50:51  reason: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs 
04:50:51  Mode: othervm [/othervm specified]
04:50:51  elapsed time (seconds): 10.158
04:50:51  configuration:
04:50:51  STDOUT:
04:50:51  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String
04:50:51  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String
04:50:51  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String
04:50:51  STDERR:
04:50:51  java.lang.StackOverflowError
04:50:51  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
04:50:51  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/130 - aix71-p8-3
jdk_lang_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops `
java/lang/String/concat/ImplicitStringConcatManyLongs.java
```
08:18:58  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.StackOverflowError
08:18:58  REASON: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs 
08:18:58  TIME:   8.228 seconds
08:18:58  messages:
08:18:58  command: main -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs
08:18:58  reason: User specified action: run main/othervm -Xverify:all -Djava.lang.invoke.stringConcat=MH_INLINE_SIZED_EXACT -Djava.lang.invoke.stringConcat.debug=true ImplicitStringConcatManyLongs 
08:18:58  Mode: othervm [/othervm specified]
08:18:58  elapsed time (seconds): 8.228
08:18:58  configuration:
08:18:58  STDOUT:
08:18:58  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String, {}, []
08:18:58  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String, {}, []
08:18:58  StringConcatFactory MH_INLINE_SIZED_EXACT is here for (long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long)String, {}, []
08:18:58  STDERR:
08:18:58  java.lang.StackOverflowError
08:18:58  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
08:18:58  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
08:18:58  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
08:18:58  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
08:18:58  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
08:18:58  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/132

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/137

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/141/consoleFull
```
03:34:41  ===============================================
03:34:41  Running test jdk_lang_1 ...
03:34:41  ===============================================
03:34:41  jdk_lang_1 Start Time: Tue Nov 16 03:34:36 2021 Epoch Time (ms): 1637051676363
03:34:41  "/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
03:34:41  JVMSHRC005I No shared class caches available
03:34:41  JVMSHRC005I No shared class caches available
03:34:41  cache cleanup done
03:34:41  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
03:34:41  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

04:58:30  STDERR:
04:58:30  java.lang.StackOverflowError
04:58:30  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
04:58:30  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
04:58:30  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
04:58:30  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)

04:58:30  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
04:58:30  	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
04:58:30  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
04:58:30  	at ImplicitStringConcatManyLongs.main(ImplicitStringConcatManyLongs.java:147)
04:58:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:58:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:58:30  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:58:30  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
04:58:30  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
04:58:30  	at java.base/java.lang.Thread.run(Thread.java:866)
04:58:30  
04:58:30  JavaTest Message: Test threw exception: java.lang.StackOverflowError

04:58:30  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.StackOverflowError
04:58:30  --------------------------------------------------
05:37:56  Test results: passed: 723; failed: 1
05:38:40  Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/report/html/report.html
05:38:40  Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16370441958740/jdk_lang_1/work
05:38:40  Error: Some tests failed or other problems occurred.
05:38:40  
05:38:40  jdk_lang_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/146/

@0xdaryl can somebody look at this one?

**Comment by pshipton** [comment]
@zl-wang fyi as well. This is not failing all the time, but it is failing regularly.

**Comment by hzongaro** [comment]
@pshipton I will take a look again

**Comment by hzongaro** [comment]
I still haven't been able to reproduce this failure in Grinder runs.  I've tried runs with make target `sanity.openjdk`, `jdk_lang_0` and `jdk_custom` with `CUSTOM_TARGET=java/lang/String/concat/ImplicitStringConcatManyLongs.java` - no luck so far.

**Comment by pshipton** [comment]
Trying an open grinder 
https://openj9-jenkins.osuosl.org/job/Grinder/409/

**Comment by pshipton** [comment]
It recreated in the open grinder so you could try to track it down on the open machines.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/152/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/154/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release/13

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release/14/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/171

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release/17/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/181/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/139/

**Comment by pshipton** [comment]
This hasn't been seen for some time, closing.
