### ISSUE TITLE
openjdk java/util/logging/ParentLoggersTest.java failed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13764]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_mac_Nightly/56 - osx1014-x86-1
jdk_util_0 -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops
java/util/logging/ParentLoggersTest.java
```
22:07:11  ACTION: build -- Passed. All files up to date
22:07:11  REASON: Named class compiled on demand
22:07:11  TIME:   0.0 seconds
22:07:11  messages:
22:07:11  command: build ParentLoggersTest
22:07:11  reason: Named class compiled on demand
22:07:11  elapsed time (seconds): 0.0
22:07:11  
22:07:11  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Exception: ParentLoggersTest: failed
22:07:11  REASON: User specified action: run main/othervm ParentLoggersTest 
22:07:11  TIME:   0.42 seconds
22:07:11  messages:
22:07:11  command: main ParentLoggersTest
22:07:11  reason: User specified action: run main/othervm ParentLoggersTest 
22:07:11  Mode: othervm [/othervm specified]
22:07:11  Additional options from @modules: --add-modules java.logging
22:07:11  elapsed time (seconds): 0.42
22:07:11  configuration:
22:07:11  Boot Layer
22:07:11    add modules: java.logging
22:07:11  
22:07:11  STDOUT:
22:07:11  
22:07:11  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
22:07:11  
22:07:11  # checkLoggers: getLoggerNames() returned unexpected loggers
22:07:11  # expected logger names (6):
22:07:11   expNames[0] = 
22:07:11   expNames[1] = global
22:07:11   expNames[2] = myParentLogger
22:07:11   expNames[3] = myParentLogger.myLogger
22:07:11   expNames[4] = abc.xyz.foo
22:07:11   expNames[5] = abc.xyz.foo.myBar.myLogger
22:07:11  # returned logger names (5):
22:07:11    retNames[0] = 
22:07:11    retNames[1] = abc.xyz.foo
22:07:11    retNames[2] = global
22:07:11    retNames[3] = myParentLogger.myLogger
22:07:11    retNames[4] = abc.xyz.foo.myBar.myLogger
22:07:11  ParentLoggersTest: failed
22:07:11  STDERR:
22:07:11  java.lang.Exception: ParentLoggersTest: failed
22:07:11  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
22:07:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:07:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:07:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:07:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:07:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:07:11  	at java.base/java.lang.Thread.run(Thread.java:884)
22:07:11  
22:07:11  JavaTest Message: Test threw exception: java.lang.Exception: ParentLoggersTest: failed
22:07:11  JavaTest Message: shutting down test
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_Nightly/7
java/util/logging/ParentLoggersTest.java
```
21:47:22  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Exception: ParentLoggersTest: failed
21:47:22  REASON: User specified action: run main/othervm ParentLoggersTest 
21:47:22  TIME:   0.293 seconds
21:47:22  messages:
21:47:22  command: main ParentLoggersTest
21:47:22  reason: User specified action: run main/othervm ParentLoggersTest 
21:47:22  Mode: othervm [/othervm specified]
21:47:22  Additional options from @modules: --add-modules java.logging
21:47:22  elapsed time (seconds): 0.293
21:47:22  configuration:
21:47:22  Boot Layer
21:47:22    add modules: java.logging
21:47:22  
21:47:22  STDOUT:
21:47:22  
21:47:22  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
21:47:22  
21:47:22  # checkLoggers: getLoggerNames() returned unexpected loggers
21:47:22  # expected logger names (6):
21:47:22   expNames[0] = 
21:47:22   expNames[1] = global
21:47:22   expNames[2] = myParentLogger
21:47:22   expNames[3] = myParentLogger.myLogger
21:47:22   expNames[4] = abc.xyz.foo
21:47:22   expNames[5] = abc.xyz.foo.myBar.myLogger
21:47:22  # returned logger names (5):
21:47:22    retNames[0] = 
21:47:22    retNames[1] = abc.xyz.foo
21:47:22    retNames[2] = global
21:47:22    retNames[3] = myParentLogger.myLogger
21:47:22    retNames[4] = abc.xyz.foo.myBar.myLogger
21:47:22  ParentLoggersTest: failed
21:47:22  STDERR:
21:47:22  java.lang.Exception: ParentLoggersTest: failed
21:47:22  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/276
jdk_util_0 
java/util/logging/ParentLoggersTest.java
```
02:44:05  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
02:44:05  
02:44:05  # checkLoggers: getLoggerNames() returned unexpected loggers
02:44:05  # expected logger names (6):
02:44:05   expNames[0] = 
02:44:05   expNames[1] = global
02:44:05   expNames[2] = myParentLogger
02:44:05   expNames[3] = myParentLogger.myLogger
02:44:05   expNames[4] = abc.xyz.foo
02:44:05   expNames[5] = abc.xyz.foo.myBar.myLogger
02:44:05  # returned logger names (5):
02:44:05    retNames[0] = 
02:44:05    retNames[1] = abc.xyz.foo
02:44:05    retNames[2] = global
02:44:05    retNames[3] = myParentLogger.myLogger
02:44:05    retNames[4] = abc.xyz.foo.myBar.myLogger
02:44:05  ParentLoggersTest: failed
02:44:05  STDERR:
02:44:05  java.lang.Exception: ParentLoggersTest: failed
02:44:05  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/292/
jdk_util_0
java/util/logging/ParentLoggersTest.java
```
23:38:05  # checkLoggers: getLoggerNames() returned unexpected loggers
23:38:05  # expected logger names (6):
23:38:05   expNames[0] = 
23:38:05   expNames[1] = global
23:38:05   expNames[2] = myParentLogger
23:38:05   expNames[3] = myParentLogger.myLogger
23:38:05   expNames[4] = abc.xyz.foo
23:38:05   expNames[5] = abc.xyz.foo.myBar.myLogger
23:38:05  # returned logger names (5):
23:38:05    retNames[0] = 
23:38:05    retNames[1] = abc.xyz.foo
23:38:05    retNames[2] = global
23:38:05    retNames[3] = myParentLogger.myLogger
23:38:05    retNames[4] = abc.xyz.foo.myBar.myLogger
23:38:05  ParentLoggersTest: failed
23:38:05  STDERR:
23:38:05  java.lang.Exception: ParentLoggersTest: failed
23:38:05  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/358/
jdk_util_0
java/util/logging/ParentLoggersTest.java
```
23:00:04  STDOUT:
23:00:04  
23:00:04  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
23:00:04  
23:00:04  # checkLoggers: getLoggerNames() returned unexpected loggers
23:00:04  # expected logger names (6):
23:00:04   expNames[0] = 
23:00:04   expNames[1] = global
23:00:04   expNames[2] = myParentLogger
23:00:04   expNames[3] = myParentLogger.myLogger
23:00:04   expNames[4] = abc.xyz.foo
23:00:04   expNames[5] = abc.xyz.foo.myBar.myLogger
23:00:04  # returned logger names (5):
23:00:04    retNames[0] = 
23:00:04    retNames[1] = abc.xyz.foo
23:00:04    retNames[2] = global
23:00:04    retNames[3] = myParentLogger.myLogger
23:00:04    retNames[4] = abc.xyz.foo.myBar.myLogger
23:00:04  ParentLoggersTest: failed
23:00:04  STDERR:
23:00:04  java.lang.Exception: ParentLoggersTest: failed
23:00:04  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by JasonFengJ9** [comment]
[An internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_testList_1/31/)(`ub20x64rt4-8`)
```
openjdk version "19-beta" 2022-09-20
IBM Semeru Runtime Open Edition 19+36-202209200534 (build 19-beta+36-202209200534)
Eclipse OpenJ9 VM 19+36-202209200534 (build master-2184d058b, JRE 19 Linux amd64-64-Bit Compressed References 20220920_43 (JIT enabled, AOT enabled)
OpenJ9   - 2184d058b
OMR      - b1be89cf5
JCL      - b56bf70733 based on jdk-19+36)
```

```
[2022-09-20T06:23:02.970Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-09-20T06:23:02.970Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-09-20T06:33:40.097Z] TEST: java/util/logging/ParentLoggersTest.java

[2022-09-20T06:33:40.099Z] STDERR:
[2022-09-20T06:33:40.099Z] java.lang.Exception: ParentLoggersTest: failed
[2022-09-20T06:33:40.099Z] 	at ParentLoggersTest.main(ParentLoggersTest.java:92)
[2022-09-20T06:33:40.099Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-09-20T06:33:40.099Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-09-20T06:33:40.099Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-20T06:33:40.099Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)

[2022-09-20T06:50:10.236Z] Test results: passed: 903; failed: 1
[2022-09-20T06:50:46.197Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_16636532596051/jdk_util_1/report/html/report.html
[2022-09-20T06:50:46.197Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_16636532596051/jdk_util_1/work
[2022-09-20T06:50:46.197Z] Error: Some tests failed or other problems occurred.
[2022-09-20T06:50:46.197Z] 
[2022-09-20T06:50:46.197Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
@JasonFengJ9 the failure details are in the STDOUT section, which wasn't included in the previous comment. I've seen some other issues where this is missing as well.

**Comment by JasonFengJ9** [comment]
Added `STDOUT` output.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_OpenJDK11/50
```
11:10:54  STDOUT:
11:10:54  
11:10:54  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
11:10:54  
11:10:54  # checkLoggers: getLoggerNames() returned unexpected loggers
11:10:54  # expected logger names (6):
11:10:54   expNames[0] = 
11:10:54   expNames[1] = global
11:10:54   expNames[2] = myParentLogger
11:10:54   expNames[3] = myParentLogger.myLogger
11:10:54   expNames[4] = abc.xyz.foo
11:10:54   expNames[5] = abc.xyz.foo.myBar.myLogger
11:10:54  # returned logger names (5):
11:10:54    retNames[0] = 
11:10:54    retNames[1] = abc.xyz.foo
11:10:54    retNames[2] = global
11:10:54    retNames[3] = myParentLogger.myLogger
11:10:54    retNames[4] = abc.xyz.foo.myBar.myLogger
11:10:54  ParentLoggersTest: failed
11:10:54  STDERR:
11:10:54  java.lang.Exception: ParentLoggersTest: failed
11:10:54  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/38
jdk_util_0
java/util/logging/ParentLoggersTest.java
```
05:15:15  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
05:15:15  
05:15:15  # checkLoggers: getLoggerNames() returned unexpected loggers
05:15:15  # expected logger names (6):
05:15:15   expNames[0] = 
05:15:15   expNames[1] = global
05:15:15   expNames[2] = myParentLogger
05:15:15   expNames[3] = myParentLogger.myLogger
05:15:15   expNames[4] = abc.xyz.foo
05:15:15   expNames[5] = abc.xyz.foo.myBar.myLogger
05:15:15  # returned logger names (5):
05:15:15    retNames[0] = 
05:15:15    retNames[1] = abc.xyz.foo
05:15:15    retNames[2] = global
05:15:15    retNames[3] = myParentLogger.myLogger
05:15:15    retNames[4] = abc.xyz.foo.myBar.myLogger
05:15:15  ParentLoggersTest: failed
05:15:15  STDERR:
05:15:15  java.lang.Exception: ParentLoggersTest: failed
05:15:15  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/104
jdk_util_1
java/util/logging/ParentLoggersTest.java
```
21:57:53  STDOUT:
21:57:53  
21:57:53  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
21:57:53  
21:57:53  # checkLoggers: getLoggerNames() returned unexpected loggers
21:57:53  # expected logger names (6):
21:57:53   expNames[0] = 
21:57:53   expNames[1] = global
21:57:53   expNames[2] = myParentLogger
21:57:53   expNames[3] = myParentLogger.myLogger
21:57:53   expNames[4] = abc.xyz.foo
21:57:53   expNames[5] = abc.xyz.foo.myBar.myLogger
21:57:53  # returned logger names (5):
21:57:53    retNames[0] = 
21:57:53    retNames[1] = abc.xyz.foo
21:57:53    retNames[2] = global
21:57:53    retNames[3] = myParentLogger.myLogger
21:57:53    retNames[4] = abc.xyz.foo.myBar.myLogger
21:57:53  ParentLoggersTest: failed
21:57:53  STDERR:
21:57:53  java.lang.Exception: ParentLoggersTest: failed
21:57:53  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/465/
jdk_util_0
java/util/logging/ParentLoggersTest.java
```
23:42:04  STDOUT:
23:42:04  
23:42:04  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
23:42:04  
23:42:04  # checkLoggers: getLoggerNames() returned unexpected loggers
23:42:04  # expected logger names (6):
23:42:04   expNames[0] = 
23:42:04   expNames[1] = global
23:42:04   expNames[2] = myParentLogger
23:42:04   expNames[3] = myParentLogger.myLogger
23:42:04   expNames[4] = abc.xyz.foo
23:42:04   expNames[5] = abc.xyz.foo.myBar.myLogger
23:42:04  # returned logger names (5):
23:42:04    retNames[0] = 
23:42:04    retNames[1] = abc.xyz.foo
23:42:04    retNames[2] = global
23:42:04    retNames[3] = myParentLogger.myLogger
23:42:04    retNames[4] = abc.xyz.foo.myBar.myLogger
23:42:04  ParentLoggersTest: failed
23:42:04  STDERR:
23:42:04  java.lang.Exception: ParentLoggersTest: failed
23:42:04  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/395/
jdk_util_1
java/util/logging/ParentLoggersTest.java
```
20:24:06  STDOUT:
20:24:06  
20:24:06  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
20:24:06  
20:24:06  # checkLoggers: getLoggerNames() returned unexpected loggers
20:24:06  # expected logger names (6):
20:24:06   expNames[0] = 
20:24:06   expNames[1] = global
20:24:06   expNames[2] = myParentLogger
20:24:06   expNames[3] = myParentLogger.myLogger
20:24:06   expNames[4] = abc.xyz.foo
20:24:06   expNames[5] = abc.xyz.foo.myBar.myLogger
20:24:06  # returned logger names (5):
20:24:06    retNames[0] = 
20:24:06    retNames[1] = abc.xyz.foo
20:24:06    retNames[2] = global
20:24:06    retNames[3] = myParentLogger.myLogger
20:24:06    retNames[4] = abc.xyz.foo.myBar.myLogger
20:24:06  ParentLoggersTest: failed
20:24:06  STDERR:
20:24:06  java.lang.Exception: ParentLoggersTest: failed
20:24:06  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/31/
jdk_util_1
java/util/logging/ParentLoggersTest.java
```
00:13:58  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
00:13:58  
00:13:58  # checkLoggers: getLoggerNames() returned unexpected loggers
00:13:58  # expected logger names (6):
00:13:58   expNames[0] = 
00:13:58   expNames[1] = global
00:13:58   expNames[2] = myParentLogger
00:13:58   expNames[3] = myParentLogger.myLogger
00:13:58   expNames[4] = abc.xyz.foo
00:13:58   expNames[5] = abc.xyz.foo.myBar.myLogger
00:13:58  # returned logger names (5):
00:13:58    retNames[0] = 
00:13:58    retNames[1] = abc.xyz.foo
00:13:58    retNames[2] = global
00:13:58    retNames[3] = myParentLogger.myLogger
00:13:58    retNames[4] = abc.xyz.foo.myBar.myLogger
00:13:58  ParentLoggersTest: failed
00:13:58  STDERR:
00:13:58  java.lang.Exception: ParentLoggersTest: failed
00:13:58  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/51
jdk_util_0
java/util/logging/ParentLoggersTest.java

```
22:56:39  [, abc.xyz.foo, global, myParentLogger.myLogger, abc.xyz.foo.myBar.myLogger]
22:56:39  
22:56:39  # checkLoggers: getLoggerNames() returned unexpected loggers
22:56:39  # expected logger names (6):
22:56:39   expNames[0] = 
22:56:39   expNames[1] = global
22:56:39   expNames[2] = myParentLogger
22:56:39   expNames[3] = myParentLogger.myLogger
22:56:39   expNames[4] = abc.xyz.foo
22:56:39   expNames[5] = abc.xyz.foo.myBar.myLogger
22:56:39  # returned logger names (5):
22:56:39    retNames[0] = 
22:56:39    retNames[1] = abc.xyz.foo
22:56:39    retNames[2] = global
22:56:39    retNames[3] = myParentLogger.myLogger
22:56:39    retNames[4] = abc.xyz.foo.myBar.myLogger
22:56:39  ParentLoggersTest: failed
22:56:39  STDERR:
22:56:39  java.lang.Exception: ParentLoggersTest: failed
22:56:39  	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OMR_testList_0/58/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_aarch64_mac_Release_testList_0/2

**Comment by JasonFengJ9** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_testList_1/477/
```
[2024-05-17T17:39:33.137Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2024-05-17T17:39:33.137Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2024-05-17T17:41:16.562Z] TEST: java/util/logging/ParentLoggersTest.java

[2024-05-17T17:41:16.563Z] STDERR:
[2024-05-17T17:41:16.563Z] java.lang.Exception: ParentLoggersTest: failed
[2024-05-17T17:41:16.563Z] 	at ParentLoggersTest.main(ParentLoggersTest.java:92)
[2024-05-17T17:41:16.563Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-17T17:41:16.563Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-05-17T17:41:16.563Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-17T17:41:16.563Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-05-17T17:41:16.563Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-05-17T17:41:16.563Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-05-17T17:41:16.563Z] 
[2024-05-17T17:41:16.563Z] JavaTest Message: Test threw exception: java.lang.Exception: ParentLoggersTest: failed

[2024-05-17T17:45:42.619Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/17

**Comment by cjjdespres** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_jit_Personal/1038/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly_testList_0/197/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_OMR_testList_1/104

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_OMR_testList_0/153/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/159/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/271
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/332
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_OMR_testList_0/111/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/321
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/183/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Release_testList_1/47/ - 0.51
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/224/
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_aarch64_mac_Nightly_testList_2/76
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/456
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_0/323

**Comment by tajila** [comment]
[https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_aarch64_mac_Nightl[…]a_util_logging_ParentLoggersTest/java/ParentLoggersTest/](https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_aarch64_mac_Nightly_testList_2/76/testReport/junit/java_util_logging_ParentLoggersTest/java/ParentLoggersTest/)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_sanity.openjdk_x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/1091/)
```
[2025-10-24T12:16:46.087Z] Running test jdk_util_0 ...
[2025-10-24T12:16:46.088Z] ===============================================
[2025-10-24T12:16:46.088Z] jdk_util_0 Start Time: Fri Oct 24 08:16:45 2025 Epoch Time (ms): 1761308205443
[2025-10-24T12:16:46.088Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2025-10-24T12:16:46.088Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2025-10-24T12:20:25.773Z] java.lang.Exception: ParentLoggersTest: failed
[2025-10-24T12:20:25.773Z] 	at ParentLoggersTest.main(ParentLoggersTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/312/

**Comment by 0xdaryl** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_OMR_testList_3/56/consoleText
