### ISSUE TITLE
ValueTypes: crash in ObjectMethods jtreg test

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13789]
Test in ~/openj9-openjdk-jdk.valuetypes/test/hotspot/jtreg/runtime/valhalla/inlinetypes/ObjectMethods.java

```
Type=Segmentation error vmState=0x0002000f
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F3C3BC29960 Handler2=00007F3C3B1DD1D0 InaccessibleAddress=00000007007252C0
RDI=00007F3BE4844390 RSI=00000000FFF02320 RAX=00000007007252C0 RBX=00007F3BE4844490
RCX=0000000000000010 RDX=0000000000000000 R8=0000000000000002 R9=0000000000000000
R10=000000000000001C R11=0000000000000000 R12=0000000000000010 R13=0000000000000000
R14=0000000000000020 R15=00007F3C3C042560
RIP=00007F3C3911DBC9 GS=0000 FS=0000 RSP=00007F3BE4844380
EFlags=0000000000010246 CS=0033 RBP=00000000FFF02340 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000007007252C0
xmm0 0000000000000244 (f: 580.000000, d: 2.865581e-321)
xmm1 00000000fff0517c (f: 4293939456.000000, d: 2.121488e-314)
xmm2 0000000000000243 (f: 579.000000, d: 2.860640e-321)
xmm3 00000000ffec9368 (f: 4293694208.000000, d: 2.121367e-314)
xmm4 0000000500000000 (f: 0.000000, d: 1.060998e-313)
xmm5 0000000100000000 (f: 0.000000, d: 2.121996e-314)
xmm6 0000003b00000010 (f: 16.000000, d: 1.251978e-312)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 115b06111a1d0110 (f: 438108416.000000, d: 4.562974e-225)
xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/images/jdk/lib/default/libj9gc29.so
Module_base_address=00007F3C38F65000
Target=2_90_20211025_000000 (Linux 4.15.0-159-generic)
CPU=amd64 (8 logical CPUs) (0x3ea77f000 RAM)
----------- Stack Backtrace -----------
(0x00007F3C3911DBC9 [libj9gc29.so+0x1b8bc9])
(0x00007F3C390DED05 [libj9gc29.so+0x179d05])
(0x00007F3C390DFB16 [libj9gc29.so+0x17ab16])
(0x00007F3C390E01A1 [libj9gc29.so+0x17b1a1])
(0x00007F3C3909472E [libj9gc29.so+0x12f72e])
(0x00007F3C390CA5AD [libj9gc29.so+0x1655ad])
(0x00007F3C390D8735 [libj9gc29.so+0x173735])
(0x00007F3C390D9870 [libj9gc29.so+0x174870])
(0x00007F3C39071EF6 [libj9gc29.so+0x10cef6])
(0x00007F3C3913D1BD [libj9gc29.so+0x1d81bd])
(0x00007F3C3911CCE8 [libj9gc29.so+0x1b7ce8])
(0x00007F3C3909B7A5 [libj9gc29.so+0x1367a5])
(0x00007F3C3909B976 [libj9gc29.so+0x136976])
(0x00007F3C3909AAC5 [libj9gc29.so+0x135ac5])
(0x00007F3C390A048A [libj9gc29.so+0x13b48a])
(0x00007F3C38FAE28F [libj9gc29.so+0x4928f])
(0x00007F3C39C5579A [libj9jit29.so+0x82a79a])
(0x00007F3C39C694D1 [libj9jit29.so+0x83e4d1])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2021/10/26 08:19:54 - please wait.
JVMDUMP032I JVM requested System dump using '/home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/test-support/jtreg_test_hotspot_jtreg_hotspot_valhalla_runtime/runtime/valhalla/inlinetypes/ObjectMethods/core.20211026.081954.3347.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.3394.

JVMDUMP010I System dump written to /home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/test-support/jtreg_test_hotspot_jtreg_hotspot_valhalla_runtime/runtime/valhalla/inlinetypes/ObjectMethods/core.20211026.081954.3347.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/test-support/jtreg_test_hotspot_jtreg_hotspot_valhalla_runtime/runtime/valhalla/inlinetypes/ObjectMethods/javacore.20211026.081954.3347.0002.txt' in response to an event
JVMDUMP012E Error in Java dump: /home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/test-support/jtreg_test_hotspot_jtreg_hotspot_valhalla_runtime/runtime/valhalla/inlinetypes/ObjectMethods/javacore.20211026.081954.3347.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/test-support/jtreg_test_hotspot_jtreg_hotspot_valhalla_runtime/runtime/valhalla/inlinetypes/ObjectMethods/Snap.20211026.081954.3347.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/test-support/jtreg_test_hotspot_jtreg_hotspot_valhalla_runtime/runtime/valhalla/inlinetypes/ObjectMethods/Snap.20211026.081954.3347.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/tobi/openj9-openjdk-jdk.valuetypes/build/linux-x86_64-server-release/test-support/jtreg_test_hotspot_jtreg_hotspot_valhalla_runtime/runtime/valhalla/inlinetypes/ObjectMethods/jitdump.20211026.081954.3347.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'MainThread' thread 0x000000000018E600
JVMDUMP053I JIT dump is recompiling jdk/internal/org/objectweb/asm/ByteVector.enlarge(I)V
rerun:
```

**Comment by theresa-m** [comment]
The latest error for this test is:
```
java.lang.RuntimeException: Identity hash code mismatch value: 2029082731 expected: -1699253838
	at runtime.valhalla.inlinetypes.ObjectMethods.checkHashCodes(ObjectMethods.java:96)
	at runtime.valhalla.inlinetypes.ObjectMethods.testObjectMethods(ObjectMethods.java:61)
	at runtime.valhalla.inlinetypes.ObjectMethods.main(ObjectMethods.java:43)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:579)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1587)
```

**Comment by hangshao0** [comment]
This is already fixed by https://github.com/eclipse-openj9/openj9/pull/20549.
