### ISSUE TITLE
ValueTypes: NPE in TestInheritedInlineTypeFields test

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13794]
TEST: runtime/valhalla/inlinetypes/TestInheritedInlineTypeFields.java

```
STDERR:
java.lang.NullPointerException: Cannot read field "x" because "<local0>.p" is null
	at runtime/valhalla/inlinetypes/TestInheritedInlineTypeFields.run(TestInheritedInlineTypeFields.java:74)
	at runtime/valhalla/inlinetypes/TestInheritedInlineTypeFields.main(TestInheritedInlineTypeFields.java:68)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
	at java.base/jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:51)
	at java.base/java/lang/reflect/Method.invoke(Method.java:570)
	at com/sun/javatest/regtest/agent/MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java/lang/Thread.run(Thread.java:884)

JavaTest Message: Test threw exception: java.lang.NullPointerException: Cannot read field "x" because "<local0>.p" is null
JavaTest Message: shutting down test
```

**Comment by theresa-m** [comment]
`runtime/valhalla/inlinetypes/QuickeningTest.java` fails with a similar error

**Comment by theresa-m** [comment]
These tests were failing due to a configuration issue, and possibly something else that was since resolved from 2021. They are passing now with https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/14.
