### ISSUE TITLE
ValueTypes: CFE in StaticFieldsTest

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13797]
TEST: runtime/valhalla/inlinetypes/StaticFieldsTest.java

```
STDERR:
java.lang.ClassFormatError: JVMCFRE000 JVMCFRE000 %1$s; class=%3$.*2$s, method=%5$.*4$s%7$.*6$s, pc=%8$u; class=runtime/valhalla/inlinetypes/StaticFieldsTest$ClassD, method=<clinit>()V, pc=0
Exception Details:
  Location:
    runtime/valhalla/inlinetypes/StaticFieldsTest$ClassD.<clinit>()V @0: JBgetstatic
  Reason:
    Error exists in the bytecode.
	at java.base/java/lang/ClassLoader.defineClassImpl(Native Method)
	at java.base/java/lang/ClassLoader.defineClassInternal(ClassLoader.java:492)
	at java.base/java/lang/ClassLoader.defineClass(ClassLoader.java:453)
	at java.base/java/security/SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk/internal/loader/BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
	at java.base/jdk/internal/loader/BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
	at java.base/jdk/internal/loader/BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
	at java.base/jdk/internal/loader/BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
	at java.base/jdk/internal/loader/ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java/lang/ClassLoader.loadClass(ClassLoader.java:1112)
	at runtime/valhalla/inlinetypes/StaticFieldsTest.main(StaticFieldsTest.java:137)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
	at java.base/jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:51)
	at java.base/java/lang/reflect/Method.invoke(Method.java:570)
	at com/sun/javatest/regtest/agent/MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java/lang/Thread.run(Thread.java:884)

JavaTest Message: Test threw exception: java.lang.ClassFormatError: JVMCFRE000 JVMCFRE000 %1$s; class=%3$.*2$s, method=%5$.*4$s%7$.*6$s, pc=%8$u; class=runtime/valhalla/inlinetypes/StaticFieldsTest$ClassD, method=<clinit>()V, pc=0
Exception Details:
  Location:
    runtime/valhalla/inlinetypes/StaticFieldsTest$ClassD.<clinit>()V @0: JBgetstatic
  Reason:
    Error exists in the bytecode.
```

**Comment by theresa-m** [comment]
The latest error for this test failure is:
```
java.lang.ClassCircularityError
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:470)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:431)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1099)
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:470)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:431)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1099)
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:470)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:431)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1099)
	at runtime.valhalla.inlinetypes.StaticFieldsTest.main(StaticFieldsTest.java:160)
```

**Comment by theresa-m** [comment]
I reran OpenJDK tests before closing https://github.com/eclipse-openj9/openj9/issues/20386 and this is no longer failing.

I suspect it was resolved by https://github.com/eclipse-openj9/openj9/pull/20652
