### ISSUE TITLE
ValueTypes: test failure in TestFieldTypeMismatch

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13795]
TEST: runtime/valhalla/inlinetypes/TestFieldTypeMismatch.java

```
STDERR:
java.lang.RuntimeException: assertEquals: expected bad class runtime/valhalla/inlinetypes/MyValue: Qtype instance field is not a value type to equal Class runtime/valhalla/inlinetypes/TestFieldTypeMismatchHelper expects class runtime.valhalla.inlinetypes.MyValue to be an inline type, but it is not
	at jdk/test/lib/Asserts.fail(Asserts.java:594)
	at jdk/test/lib/Asserts.assertEquals(Asserts.java:205)
	at jdk/test/lib/Asserts.assertEquals(Asserts.java:189)
	at runtime/valhalla/inlinetypes/TestFieldTypeMismatch.main(TestFieldTypeMismatch.java:48)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
	at java.base/jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:51)
	at java.base/java/lang/reflect/Method.invoke(Method.java:570)
	at com/sun/javatest/regtest/agent/MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java/lang/Thread.run(Thread.java:884)
```

**Comment by theresa-m** [comment]
This test no longer exists.
