### ISSUE TITLE
ValueTypes: CFE in VarArgsArray test

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13792]
test runtime.valhalla.inlinetypes.VarArgsArray

```
STDERR:
java.lang.ClassFormatError: JVMCFRE068 class name is invalid; class=runtime/valhalla/inlinetypes/VarArgsArray, offset=0
	at java.base/java/lang/ClassLoader.defineClassInternal(ClassLoader.java:492)
	at java.base/java/lang/ClassLoader.defineClass(ClassLoader.java:453)
	at java.base/java/security/SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk/internal/loader/BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
	at java.base/jdk/internal/loader/BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
	at java.base/jdk/internal/loader/BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
	at java.base/jdk/internal/loader/BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
	at java.base/jdk/internal/loader/ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java/lang/ClassLoader.loadClass(ClassLoader.java:1112)
	at java.base/java/lang/Class.forNameImpl(Native Method)
	at java.base/java/lang/Class.forName(Class.java:422)
	at com/sun/javatest/regtest/agent/MainWrapper$MainThread.run(MainWrapper.java:125)
	at java.base/java/lang/Thread.run(Thread.java:884)
```

**Comment by theresa-m** [comment]
This test is passing in the latest run https://github.com/eclipse-openj9/openj9/issues/13182#issuecomment-2414876297
