### ISSUE TITLE
ValueTypes: CFE in VWithFieldTest

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13791]
~/openj9-openjdk-jdk.valuetypes/test/hotspot/jtreg/runtime/valhalla/inlinetypes/WithFieldAccessorTest.java

```
STDERR:
java.lang.ClassFormatError: JVMCFRE000 JVMCFRE000 %1$s; class=%3$.*2$s, method=%5$.*4$s%7$.*6$s, pc=%8$u; class=runtime/valhalla/inlinetypes/VWithFieldTest$TestValue, method=<clinit>()V, pc=0
Exception Details:
  Location:
    runtime/valhalla/inlinetypes/VWithFieldTest$TestValue.<clinit>()V @0: JBiconst3
  Reason:
    Error exists in the bytecode.
	at java.base/java/lang/ClassLoader.defineClassImpl(Native Method)
	at java.base/java/lang/ClassLoader.defineClassInternal(ClassLoader.java:492)
	at java.base/java/lang/ClassLoader.defineClass(ClassLoader.java:453)
	at java.base/java/security/SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk/internal/loader/BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
	at java.base/jdk/internal/loader/BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
	at java.base/jdk/internal/loader/BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
	at java.base/jdk/internal/loader/BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
	at java.base/jdk/internal/loader/ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java/lang/ClassLoader.loadClass(ClassLoader.java:1112)
	at runtime/valhalla/inlinetypes/VWithFieldTest.main(VWithFieldTest.java:210)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
	at java.base/jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:51)
	at java.base/java/lang/reflect/Method.invoke(Method.java:570)
	at com/sun/javatest/regtest/agent/MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java/lang/Thread.run(Thread.java:884)
```

**Comment by theresa-m** [comment]
This test no longer exists.
