### ISSUE TITLE
TestIBMJlmRemoteMemoryAuth & a few similar failures - jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 1234

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13813]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.system_aarch64_linux_testList_1/50/tapResults/`:
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Open Edition 17.0.1.0-m1 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1.0-m1 (build openj9-0.29.1-m1, JRE 17 Linux aarch64-64-Bit Compressed References 20211027_24 (JIT enabled, AOT enabled)
OpenJ9   - 855de83f9
OMR      - 3f2734d26
JCL      - f84d83f2c66 based on jdk-17.0.1+12)
```
[Rerun in Grinder]() - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
`aqa-tests/TKG/output_1635361702117/TestIBMJlmRemoteMemoryAuth_0/20211027-152552-TestIBMJlmRemoteMemoryAuth/results/3.LT1.stderr`
```
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 1234; nested exception is:
        java.net.BindException: Address already in use
jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 1234; nested exception is:
        java.net.BindException: Address already in use
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:492)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
        at java.base/java.lang.System.startSNMPAgent(Native Method)
        at java.base/java.lang.Thread.completeInitialization(Thread.java:187)
        at java.base/java.lang.J9VMInternals.completeInitialization(J9VMInternals.java:73)
Caused by: java.rmi.server.ExportException: Port already in use: 1234; nested exception is:
        java.net.BindException: Address already in use
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:415)
        at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
        at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:235)
        at java.rmi/sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:223)
        at java.rmi/sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:182)
        at jdk.management.agent/sun.management.jmxremote.SingleEntryRegistry.<init>(SingleEntryRegistry.java:49)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:859)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:480)
        ... 5 more
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.Net.bind(Net.java:544)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:167)
        at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createServerSocket(TCPDirectSocketFactory.java:45)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:673)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
        ... 14 more
Exception in thread "main" java/lang/RuntimeException: jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 1234; nested exception is: 
        java.net.BindException: Address already in use
        at jdk/internal/agent/Agent.error (jdk.management.agent@17.0.1/Agent.java:669)
        at jdk/internal/agent/Agent.startAgent (jdk.management.agent@17.0.1/Agent.java:454)
        at jdk/internal/agent/Agent.startAgent (jdk.management.agent@17.0.1/Agent.java:599)
        at java/lang/System.startSNMPAgent (java.base@17.0.1/NativeMethod:4294967295)
        at java/lang/Thread.completeInitialization (java.base@17.0.1/Thread.java:187)
        at java/lang/J9VMInternals.completeInitialization (java.base@17.0.1/J9VMInternals.java:73)
```

This seems related to hardcoded port 1234.

**Comment by JasonFengJ9** [comment]
Appeared in a JDK11 `0.30.0` release build `job/Test_openjdk11_j9_sanity.system_aarch64_linux_testList_1/49/`(`cent7-aarch64-5`).
```
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 1234; nested exception is:
        java.net.BindException: Address already in use (Bind failed)
jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 1234; nested exception is:
        java.net.BindException: Address already in use (Bind failed)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:491)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
        at java.base/java.lang.System.startSNMPAgent(Native Method)
        at java.base/java.lang.Thread.completeInitialization(Thread.java:173)
        at java.base/java.lang.J9VMInternals.completeInitialization(J9VMInternals.java:73)
Caused by: java.rmi.server.ExportException: Port already in use: 1234; nested exception is:
        java.net.BindException: Address already in use (Bind failed)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
        at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
        at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:234)
        at java.rmi/sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:220)
        at java.rmi/sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:180)
        at jdk.management.agent/sun.management.jmxremote.SingleEntryRegistry.<init>(SingleEntryRegistry.java:49)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:836)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:479)
        ... 5 more
Caused by: java.net.BindException: Address already in use (Bind failed)
        at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:452)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:149)
        at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createServerSocket(TCPDirectSocketFactory.java:45)
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:670)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:324)
        ... 14 more
Exception in thread "main" java/lang/RuntimeException: jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 1234; nested exception is:
        java.net.BindException: Address already in use (Bind failed)
        at jdk/internal/agent/Agent.error (jdk.management.agent@11.0.14/Agent.java:673)
        at jdk/internal/agent/Agent.startAgent (jdk.management.agent@11.0.14/Agent.java:454)
        at jdk/internal/agent/Agent.startAgent (jdk.management.agent@11.0.14/Agent.java:599)
        at java/lang/System.startSNMPAgent (java.base@11.0.14/NativeMethod:4294967295)
        at java/lang/Thread.completeInitialization (java.base@11.0.14/Thread.java:173)
        at java/lang/J9VMInternals.completeInitialization (java.base@11.0.14/J9VMInternals.java:73)
```
