### ISSUE TITLE
jdk_other_0_FAILED : com/sun/jndi/dns/ConfigTests/PortUnreachable.java - RuntimeException: Failed: call took 8084 ms, expected less than 3000 ms

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13818]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/21/console`(`win16x64cudart1`):
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Open Edition 17.0.1.0-m1 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1.0-m1 (build openj9-0.29.1-m1, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20211027_24 (JIT enabled, AOT enabled)
OpenJ9   - 855de83f9
OMR      - 3f2734d26
JCL      - f84d83f2c66 based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F24%2Fibm-semeru-open-testimage_x64_windows_17.0.1_12_openj9-0.29.1-m1.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F24%2Fibm-semeru-open-jdk_x64_windows_17.0.1_12_openj9-0.29.1-m1.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F24%2Fibm-semeru-open-debugimage_x64_windows_17.0.1_12_openj9-0.29.1-m1.zip&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=v0.29.1-release&OPENJ9_BRANCH=v0.29.1-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.29.1-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-10-27T19:50:23.946Z] Running test jdk_other_0 ...
[2021-10-27T19:50:23.946Z] ===============================================

[2021-10-27T19:51:16.054Z] --------------------------------------------------
[2021-10-27T19:51:16.054Z] TEST: com/sun/jndi/dns/ConfigTests/PortUnreachable.java

[2021-10-27T19:51:16.059Z] STDERR:
[2021-10-27T19:51:16.059Z] java.lang.RuntimeException: Failed: call took 8084 ms, expected less than 3000 ms
[2021-10-27T19:51:16.059Z] 	at PortUnreachable.handleException(PortUnreachable.java:101)
[2021-10-27T19:51:16.059Z] 	at TestBase.launch(TestBase.java:84)
[2021-10-27T19:51:16.059Z] 	at TestBase.run(TestBase.java:50)
[2021-10-27T19:51:16.059Z] 	at PortUnreachable.main(PortUnreachable.java:60)
[2021-10-27T19:51:16.059Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-27T19:51:16.059Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-10-27T19:51:16.061Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-27T19:51:16.061Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-10-27T19:51:16.061Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-27T19:51:16.061Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-10-27T19:51:16.061Z] 
[2021-10-27T19:51:16.061Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Failed: call took 8084 ms, expected less than 3000 ms
[2021-10-27T19:51:16.061Z] JavaTest Message: shutting down test
[2021-10-27T19:51:16.061Z] 
[2021-10-27T19:51:16.061Z] STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Failed: call took 8084 ms, expected less than 3000 ms

[2021-10-27T19:51:16.065Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed: call took 8084 ms, expected less than 3000 ms
[2021-10-27T19:51:16.065Z] --------------------------------------------------
[2021-10-27T20:03:51.834Z] Test results: passed: 261; failed: 1
[2021-10-27T20:04:08.170Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
[2021-10-27T20:04:08.170Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16353627989799\jdk_other_0\work
[2021-10-27T20:04:08.170Z] Error: Some tests failed or other problems occurred.
[2021-10-27T20:04:08.170Z] 
[2021-10-27T20:04:08.170Z] jdk_other_0_FAILED
```

This also occurred at `win16x64cudart1` like https://github.com/eclipse-openj9/openj9/issues/13817

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk18_j9_extended.openjdk_x86-64_windows/18/` (`win10x64vs6`)
```
[2022-04-16T18:03:46.726Z] STDERR:
[2022-04-16T18:03:46.726Z] java.lang.RuntimeException: Failed: call took 8214 ms, expected less than 3000 ms
[2022-04-16T18:03:46.726Z] 	at PortUnreachable.handleException(PortUnreachable.java:101)
[2022-04-16T18:03:46.726Z] 	at TestBase.launch(TestBase.java:84)
[2022-04-16T18:03:46.726Z] 	at TestBase.run(TestBase.java:50)
[2022-04-16T18:03:46.726Z] 	at PortUnreachable.main(PortUnreachable.java:60)
[2022-04-16T18:03:46.726Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-04-16T18:03:46.726Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-04-16T18:03:46.726Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-04-16T18:03:46.726Z] 	at java.base/java.lang.Thread.run(Thread.java:852)
[2022-04-16T18:03:46.726Z] 
[2022-04-16T18:03:46.726Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Failed: call took 8214 ms, expected less than 3000 ms
```

**Comment by JasonFengJ9** [comment]
[JDK17 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_3/3/)(`win22x86-svl-rt4-1`)
```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0-m1 (build 17.0.10+5)
Eclipse OpenJ9 VM 17.0.10.0-m1 (build v0.43.0-release-9b2a42f8f, JRE 17 Windows Server 2022 amd64-64-Bit Compressed References 20240116_576 (JIT enabled, AOT enabled)
OpenJ9   - 9b2a42f8f
OMR      - d810fcb98
JCL      - 10ccdceee3c based on jdk-17.0.10+5)

[2023-12-02T23:40:12.522Z] variation: Mode650
[2023-12-02T23:40:12.981Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2023-12-02T23:44:56.691Z] TEST: com/sun/jndi/dns/ConfigTests/PortUnreachable.java

[2023-12-02T23:44:56.693Z] STDERR:
[2023-12-02T23:44:56.693Z] java.lang.RuntimeException: Failed: call took 16187 ms, expected less than 3000 ms
[2023-12-02T23:44:56.693Z] 	at PortUnreachable.handleException(PortUnreachable.java:101)
[2023-12-02T23:44:56.693Z] 	at TestBase.launch(TestBase.java:84)
[2023-12-02T23:44:56.693Z] 	at TestBase.run(TestBase.java:50)
[2023-12-02T23:44:56.693Z] 	at PortUnreachable.main(PortUnreachable.java:60)

[2023-12-02T23:45:46.198Z] TEST: com/sun/jndi/dns/ConfigTests/Timeout.java

[2023-12-02T23:45:46.201Z] STDERR:
[2023-12-02T23:45:46.201Z] java.lang.RuntimeException: Failed: timeout in 23953 ms, expected7750ms
[2023-12-02T23:45:46.201Z] 	at Timeout.handleException(Timeout.java:108)
[2023-12-02T23:45:46.201Z] 	at TestBase.launch(TestBase.java:84)
[2023-12-02T23:45:46.201Z] 	at TestBase.run(TestBase.java:50)
[2023-12-02T23:45:46.201Z] 	at Timeout.main(Timeout.java:61)

[2023-12-03T00:43:15.539Z] Test results: passed: 263; failed: 2
[2023-12-03T00:43:39.382Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_3\aqa-tests\TKG\output_1701555440100\jdk_other_1\report\html\report.html
[2023-12-03T00:43:39.382Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_3\aqa-tests\TKG\output_1701555440100\jdk_other_1\work
[2023-12-03T00:43:39.382Z] Error: Some tests failed or other problems occurred.
[2023-12-03T00:43:39.382Z] -----------------------------------
[2023-12-03T00:43:39.382Z] jdk_other_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK11 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0/9/)(`win22x86-svl-rt3-1`)
```
openjdk version "11.0.23" 2024-04-16
IBM Semeru Runtime Open Edition 11.0.23.0-m1 (build 11.0.23+6)
Eclipse OpenJ9 VM 11.0.23.0-m1 (build v0.44.0-release-747f86c91, JRE 11 Windows Server 2022 amd64-64-Bit Compressed References 20240319_865 (JIT enabled, AOT enabled)
OpenJ9   - 747f86c91
OMR      - 254af5a04
JCL      - b59f8e52b5 based on jdk-11.0.23+6)

[2024-03-20T20:29:51.965Z] TEST: com/sun/jndi/dns/ConfigTests/PortUnreachable.java

[2024-03-20T20:29:51.966Z] STDERR:
[2024-03-20T20:29:51.966Z] java.lang.RuntimeException: Failed: call took 17047 ms, expected less than 3000 ms
[2024-03-20T20:29:51.966Z] 	at PortUnreachable.handleException(PortUnreachable.java:101)
[2024-03-20T20:29:51.966Z] 	at TestBase.launch(TestBase.java:84)
[2024-03-20T20:29:51.966Z] 	at TestBase.run(TestBase.java:50)
[2024-03-20T20:29:51.966Z] 	at PortUnreachable.main(PortUnreachable.java:60)

[2024-03-20T20:29:55.898Z] TEST: com/sun/jndi/dns/ConfigTests/Timeout.java

[2024-03-20T20:29:55.899Z] STDERR:
[2024-03-20T20:29:55.899Z] java.lang.RuntimeException: Failed: timeout in 24859 ms, expected7750ms
[2024-03-20T20:29:55.899Z] 	at Timeout.handleException(Timeout.java:108)
[2024-03-20T20:29:55.899Z] 	at TestBase.launch(TestBase.java:84)
[2024-03-20T20:29:55.899Z] 	at TestBase.run(TestBase.java:50)
[2024-03-20T20:29:55.899Z] 	at Timeout.main(Timeout.java:61)

[2024-03-20T21:07:24.598Z] Test results: passed: 260; failed: 2
[2024-03-20T21:07:31.779Z] Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0\aqa-tests\TKG\output_17109663165083\jdk_other_0\report\html\report.html
[2024-03-20T21:07:31.779Z] Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0\aqa-tests\TKG\output_17109663165083\jdk_other_0\work
[2024-03-20T21:07:31.779Z] Error: Some tests failed or other problems occurred.
[2024-03-20T21:07:31.779Z] -----------------------------------
[2024-03-20T21:07:31.779Z] jdk_other_0_FAILED
```

@llxia @annaibm could you help exclude these two tests for all Java versions on `x86-64_windows`?
