### ISSUE TITLE
jdk_io_FAILED : java/io/FileDescriptor/Sharing.java - RuntimeException: OpenClose thread tests failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13817]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/21/testReport/`(`win16x64cudart1 `):
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Open Edition 17.0.1.0-m1 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1.0-m1 (build openj9-0.29.1-m1, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20211027_24 (JIT enabled, AOT enabled)
OpenJ9   - 855de83f9
OMR      - 3f2734d26
JCL      - f84d83f2c66 based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F24%2Fibm-semeru-open-testimage_x64_windows_17.0.1_12_openj9-0.29.1-m1.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F24%2Fibm-semeru-open-jdk_x64_windows_17.0.1_12_openj9-0.29.1-m1.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F24%2Fibm-semeru-open-debugimage_x64_windows_17.0.1_12_openj9-0.29.1-m1.zip&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=v0.29.1-release&OPENJ9_BRANCH=v0.29.1-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.29.1-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-10-27T19:37:22.973Z] Running test jdk_io_0 ...
[2021-10-27T19:37:22.973Z] ===============================================

[2021-10-27T19:37:23.961Z] variation: Mode150
[2021-10-27T19:37:23.961Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-10-27T19:38:43.622Z] --------------------------------------------------
[2021-10-27T19:38:43.622Z] TEST: java/io/FileDescriptor/Sharing.java

[2021-10-27T19:38:43.623Z] STDERR:
[2021-10-27T19:38:43.623Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2021-10-27T19:38:43.623Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2021-10-27T19:38:43.623Z] 	at Sharing.main(Sharing.java:45)
[2021-10-27T19:38:43.623Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-27T19:38:43.623Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-10-27T19:38:43.623Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-27T19:38:43.623Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-10-27T19:38:43.623Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-10-27T19:38:43.623Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-10-27T19:38:43.623Z] 
[2021-10-27T19:38:43.623Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: OpenClose thread tests failed.
[2021-10-27T19:38:43.623Z] JavaTest Message: shutting down test
[2021-10-27T19:38:43.623Z] 
[2021-10-27T19:38:43.623Z] STATUS:Failed.`main' threw exception: java.lang.RuntimeException: OpenClose thread tests failed.

[2021-10-27T19:38:43.624Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: OpenClose thread tests failed.
[2021-10-27T19:38:43.624Z] --------------------------------------------------
[2021-10-27T19:43:09.575Z] Test results: passed: 389; failed: 1
[2021-10-27T19:43:24.680Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
[2021-10-27T19:43:24.680Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16353627989799\jdk_io_0\work
[2021-10-27T19:43:24.680Z] Error: Some tests failed or other problems occurred.
[2021-10-27T19:43:24.680Z] 
[2021-10-27T19:43:24.680Z] jdk_io_0_FAILED
```

This might be machine/network related, there are quite a few other failures in this `win16x64cudart1`

**Comment by JasonFengJ9** [comment]
Observed at JDK17 head build - `job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/39/`(`fuji`)
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1+12 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1+12 (build master-df9cb7be9, JRE 17 Linux aarch64-64-Bit Compressed References 20220108_77 (JIT enabled, AOT enabled)
OpenJ9   - df9cb7be9
OMR      - 05dd27061
JCL      - 97874233392 based on jdk-17.0.1+12)

[2022-01-08T16:00:31.390Z] variation: Mode150
[2022-01-08T16:00:31.390Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-01-08T16:01:17.433Z] --------------------------------------------------
[2022-01-08T16:01:17.433Z] TEST: java/io/FileDescriptor/Sharing.java

[2022-01-08T16:01:17.434Z] STDOUT:
[2022-01-08T16:01:17.434Z] ....................................................................................................................................................................................................................OpenClose: FileDescriptor shouldn't be valid
[2022-01-08T16:01:17.434Z] STDERR:
[2022-01-08T16:01:17.434Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2022-01-08T16:01:17.434Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2022-01-08T16:01:17.434Z] 	at Sharing.main(Sharing.java:45)
[2022-01-08T16:01:17.434Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-08T16:01:17.434Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-01-08T16:01:17.434Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-08T16:01:17.434Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-01-08T16:01:17.434Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-01-08T16:01:17.434Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2022-01-08T16:01:17.434Z] 
[2022-01-08T16:01:17.434Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: OpenClose thread tests failed.
[2022-01-08T16:01:17.434Z] JavaTest Message: shutting down test

[2022-01-08T16:02:54.570Z] jdk_io_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK22 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_ppc64_aix_testList_0/4/)(`paix823`)
```
[2024-03-07T07:53:27.834Z] variation: Mode150
[2024-03-07T07:53:27.834Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-07T07:56:03.412Z] TEST: java/io/FileDescriptor/Sharing.java

[2024-03-07T07:56:03.412Z] STDERR:
[2024-03-07T07:56:03.412Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2024-03-07T07:56:03.412Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2024-03-07T07:56:03.412Z] 	at Sharing.main(Sharing.java:45)
[2024-03-07T07:56:03.412Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-07T07:56:03.412Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-07T07:56:03.412Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-03-07T07:56:03.412Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-03-07T07:56:03.412Z] 
[2024-03-07T07:56:03.412Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: OpenClose thread tests failed.

[2024-03-07T08:01:35.631Z] jdk_io_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38525/)

**Comment by JasonFengJ9** [comment]
[JDK17 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64_aix_testList_0/73/)(`paix821`)
```
[2024-06-08T16:06:27.864Z] variation: Mode150
[2024-06-08T16:06:27.864Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-06-08T16:08:33.332Z] TEST: java/io/FileDescriptor/Sharing.java

[2024-06-08T16:08:33.334Z] STDERR:
[2024-06-08T16:08:33.334Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2024-06-08T16:08:33.334Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2024-06-08T16:08:33.334Z] 	at Sharing.main(Sharing.java:45)
[2024-06-08T16:08:33.334Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-06-08T16:08:33.334Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-06-08T16:08:33.334Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-06-08T16:08:33.334Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2024-06-08T16:08:33.334Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-06-08T16:08:33.334Z] 	at java.base/java.lang.Thread.run(Thread.java:857)

[2024-06-08T16:13:33.180Z] jdk_io_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_extended.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_s390x_linux/352/)
```
[2024-12-07T05:24:35.344Z] variation: Mode650
[2024-12-07T05:24:35.344Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-12-07T05:25:01.948Z] TEST: java/io/FileDescriptor/Sharing.java

[2024-12-07T05:25:01.949Z] STDOUT:
[2024-12-07T05:25:01.949Z] ....................................................................................................................................................................................................................OpenClose: FileDescriptor shouldn't be valid
[2024-12-07T05:25:01.949Z] STDERR:
[2024-12-07T05:25:01.949Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2024-12-07T05:25:01.949Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2024-12-07T05:25:01.949Z] 	at Sharing.main(Sharing.java:45)
[2024-12-07T05:25:01.949Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-12-07T05:25:01.949Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-12-07T05:25:01.949Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-12-07T05:25:01.949Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-12-07T05:25:01.949Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-12-07T05:25:01.949Z] 	at java.lang.Thread.run(Thread.java:822)
[2024-12-07T05:25:01.949Z] 

[2024-12-07T05:26:04.868Z] jdk_io_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_extended.openjdk_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_mac/367/)
```
[2025-03-05T01:19:58.814Z] variation: Mode650
[2025-03-05T01:19:58.814Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-03-05T01:20:04.592Z] TEST: java/io/FileDescriptor/Sharing.java

[2025-03-05T01:20:04.593Z] STDOUT:
[2025-03-05T01:20:04.593Z] ....................................................................................................................................................................................................................OpenClose: FileDescriptor shouldn't be valid
[2025-03-05T01:20:04.593Z] STDERR:
[2025-03-05T01:20:04.593Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2025-03-05T01:20:04.593Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2025-03-05T01:20:04.593Z] 	at Sharing.main(Sharing.java:45)

[2025-03-05T01:20:27.216Z] jdk_io_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_extended.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_4/152/)
```
[2025-11-19T16:37:20.125Z] Running test jdk_io_1 ...
[2025-11-19T16:37:20.125Z] ===============================================
[2025-11-19T16:37:20.125Z] jdk_io_1 Start Time: Wed Nov 19 08:37:19 2025 Epoch Time (ms): 1763570239902
[2025-11-19T16:37:22.184Z] variation: Mode650
[2025-11-19T16:37:22.184Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-11-19T16:51:34.131Z] TEST: java/io/FileDescriptor/Sharing.java

[2025-11-19T16:51:34.136Z] STDERR:
[2025-11-19T16:51:34.136Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2025-11-19T16:51:34.136Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2025-11-19T16:51:34.136Z] 	at Sharing.main(Sharing.java:45)
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_extended.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64_aix_testList_2/518/)
```
[2026-04-07T00:02:10.712Z] Running test jdk_io_1 ...
[2026-04-07T00:02:10.712Z] ===============================================
[2026-04-07T00:02:10.712Z] jdk_io_1 Start Time: Mon Apr  6 20:02:08 2026 Epoch Time (ms): 1775520128675
[2026-04-07T00:02:10.712Z] variation: Mode650
[2026-04-07T00:02:10.712Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2026-04-07T00:04:27.582Z] TEST: java/io/FileDescriptor/Sharing.java

[2026-04-07T00:04:27.582Z] STDERR:
[2026-04-07T00:04:27.582Z] java.lang.RuntimeException: OpenClose thread tests failed.
[2026-04-07T00:04:27.582Z] 	at Sharing.MultiThreadedFD(Sharing.java:275)
[2026-04-07T00:04:27.582Z] 	at Sharing.main(Sharing.java:45)
[2026-04-07T00:04:27.582Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2026-04-07T00:04:27.582Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2026-04-07T00:04:27.582Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2026-04-07T00:04:27.582Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2026-04-07T00:04:27.582Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2026-04-07T00:04:27.582Z] 	at java.base/java.lang.Thread.run(Thread.java:854)
[2026-04-07T00:04:27.582Z] 
[2026-04-07T00:04:27.582Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: OpenClose thread tests failed.
```
