### ISSUE TITLE
OpenJDK TestLogConfigurationDeadLockWithConf Found 2 deadlocked threads

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13823]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/136
jdk_util_1 -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops
java/util/logging/TestLogConfigurationDeadLockWithConf.java
```
22:56:55  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Found 2 deadlocked threads
22:56:55  REASON: User specified action: run main/othervm TestLogConfigurationDeadLockWithConf 
22:56:55  TIME:   3.396 seconds
22:56:55  messages:
22:56:55  command: main TestLogConfigurationDeadLockWithConf
22:56:55  reason: User specified action: run main/othervm TestLogConfigurationDeadLockWithConf 
22:56:55  Mode: othervm [/othervm specified]
22:56:55  elapsed time (seconds): 3.396
22:56:55  configuration:
22:56:55  STDOUT:
22:56:55  No security
22:56:55  3101 ms elapsed (4000 requested)
22:56:55  STDERR:
22:56:55  Oct 28, 2021 10:56:40 PM TestLogConfigurationDeadLockWithConf$Stopper run
22:56:55  INFO: 2992ms remaining...
22:56:55  Oct 28, 2021 10:56:41 PM TestLogConfigurationDeadLockWithConf$Stopper run
22:56:55  INFO: 1913ms remaining...
22:56:55  Found 2 deadlocked threads: 
22:56:55  "Thread-4" Id=33 TIMED_WAITING
22:56:55  	at java.lang.Thread.sleep(Native Method)
22:56:55  	at java.lang.Thread.sleep(Thread.java:957)
22:56:55  	at TestLogConfigurationDeadLockWithConf$ReadConf.run(TestLogConfigurationDeadLockWithConf.java:229)
22:56:55  
22:56:55  "Finalizer thread" Id=40 RUNNABLE
22:56:55  
22:56:55  java.lang.RuntimeException: Found 2 deadlocked threads
22:56:55  	at TestLogConfigurationDeadLockWithConf$DeadlockDetector.run(TestLogConfigurationDeadLockWithConf.java:287)
22:56:55  Waiting for Stopper: Thread[Thread-10,5,MainThreadGroup]
22:56:55  Skipping deadlocked thread ReadConf: Thread[Thread-4,5,]
22:56:55  All threads joined.
22:56:55  FAILED: 5097 loggers created by 2 Thread(s),
22:56:55  	 LogManager.readConfiguration() called 4167 times by 2 Thread(s).
22:56:55  	 ThreadMXBean.findDeadlockedThreads called 31 times by 1 Thread.
22:56:55  	 Error is: Found 2 deadlocked threads
22:56:55  java.lang.RuntimeException: Found 2 deadlocked threads
22:56:55  	at TestLogConfigurationDeadLockWithConf$DeadlockDetector.run(TestLogConfigurationDeadLockWithConf.java:287)
22:56:55  
22:56:55  JavaTest Message: Test threw exception: java.lang.RuntimeException: Found 2 deadlocked threads
22:56:55  JavaTest Message: shutting down test
22:56:55  
22:56:55  STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Found 2 deadlocked threads
```

**Comment by JasonFengJ9** [comment]
[JDK8 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_testList_0/606/)(`sles12le-svl-rt2-1`)
```
[2024-05-11T04:03:35.191Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2024-05-11T04:03:35.191Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2024-05-11T04:09:21.768Z] TEST: java/util/logging/TestLogConfigurationDeadLock.java

[2024-05-11T04:09:21.769Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Found 2 deadlocked threads
[2024-05-11T04:09:21.769Z] JavaTest Message: shutting down test
[2024-05-11T04:09:21.769Z] 
[2024-05-11T04:09:21.769Z] STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Found 2 deadlocked threads

[2024-05-11T04:09:21.769Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Found 2 deadlocked threads
[2024-05-11T04:09:21.769Z] --------------------------------------------------
[2024-05-11T04:17:31.662Z] Test results: passed: 655; failed: 1
[2024-05-11T04:17:35.844Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_1715397905151/jdk_util_0/report/html/report.html
[2024-05-11T04:17:35.844Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_1715397905151/jdk_util_0/work
[2024-05-11T04:17:35.844Z] Error: Some tests failed or other problems occurred.
[2024-05-11T04:17:35.844Z] -----------------------------------
[2024-05-11T04:17:35.844Z] jdk_util_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40549/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OMR_testList_2/81/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/114
jdk_util_0
java/util/logging/TestLogConfigurationDeadLock.java
```
20:55:13  Found 2 deadlocked threads: 
20:55:13  "Finalizer thread" Id=29 BLOCKED on java.lang.ref.ReferenceQueue@49d657dd owned by "Thread-11" Id=33
20:55:13  	at java.lang.ref.ReferenceQueue.enqueue(ReferenceQueue.java:179)
20:55:13  	at java.lang.ref.Reference.enqueueImpl(Reference.java:147)
20:55:13  
20:55:13  "Thread-11" Id=33 BLOCKED on java.util.logging.LogManager$LoggerWeakRef@596d6465 owned by "Finalizer thread" Id=29
20:55:13  	at java.lang.ref.Reference.dequeue(Reference.java:195)
20:55:13  	at java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:85)
20:55:13  	at java.util.logging.LogManager.drainLoggerRefQueueBounded(LogManager.java:1130)
20:55:13  	at java.util.logging.LogManager.addLogger(LogManager.java:1160)
20:55:13  	at java.util.logging.LogManager.demandLogger(LogManager.java:556)
20:55:13  	at java.util.logging.Logger.demandLogger(Logger.java:455)
20:55:13  	at java.util.logging.Logger.getLogger(Logger.java:502)
20:55:13  	at TestLogConfigurationDeadLock$AddLogger.run(TestLogConfigurationDeadLock.java:175)
```

**Comment by pshipton** [comment]
@dmitripivkine not sure if this is worth looking at? We'd have to modify the test to create a system dump when the failure occurs.

**Comment by dmitripivkine** [comment]
> @dmitripivkine not sure if this is worth looking at? We'd have to modify the test to create a system dump when the failure occurs.

I don't know. If deadlock is between `java.lang.ref.ReferenceQueue.enqueue(ReferenceQueue.java:179)` and `java.lang.ref.Reference.dequeue(Reference.java:195)` we should see logical problem there, should be?

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/214/
jdk_util_0
java/util/logging/TestLogConfigurationDeadLockWithConf.java
```
22:41:52  Found 4 deadlocked threads: 
22:41:52  "Thread-1" prio=5 Id=27 WAITING
22:41:52  	at java.base@11.0.27-internal/jdk.internal.misc.Unsafe.park(Native Method)
22:41:52  	at java.base@11.0.27-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
22:41:52  	at java.base@11.0.27-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
22:41:52  	at java.base@11.0.27-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
22:41:52  	at java.base@11.0.27-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
22:41:52  	at java.base@11.0.27-internal/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1561)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1378)
22:41:52  	at app//TestLogConfigurationDeadLockWithConf$ReadConf.run(TestLogConfigurationDeadLockWithConf.java:229)
22:41:52  
22:41:52  "Thread-2" prio=5 Id=28 RUNNABLE
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager$LoggerWeakRef.dispose(LogManager.java:1095)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager$LoggerContext.findLogger(LogManager.java:697)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.resetLoggerContext(LogManager.java:1458)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.reset(LogManager.java:1445)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1575)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1378)
22:41:52  	at app//TestLogConfigurationDeadLockWithConf$ReadConf.run(TestLogConfigurationDeadLockWithConf.java:229)
22:41:52  
22:41:52  "Thread-3" prio=5 Id=29 BLOCKED on java.util.logging.LogManager$LoggerContext@1cea9eb6 owned by "Thread-2" Id=28
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager$LoggerWeakRef.dispose(LogManager.java:1092)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.drainLoggerRefQueueBounded(LogManager.java:1169)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.addLogger(LogManager.java:1194)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.demandLogger(LogManager.java:525)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.demandLogger(LogManager.java:515)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.Logger.demandLogger(Logger.java:654)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.Logger.getLogger(Logger.java:717)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.Logger.getLogger(Logger.java:701)
22:41:52  	at app//TestLogConfigurationDeadLockWithConf$AddLogger.run(TestLogConfigurationDeadLockWithConf.java:247)
22:41:52  
22:41:52  "Thread-4" prio=5 Id=30 BLOCKED on java.util.logging.LogManager$LoggerContext@1cea9eb6 owned by "Thread-2" Id=28
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager$LoggerWeakRef.dispose(LogManager.java:1092)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.drainLoggerRefQueueBounded(LogManager.java:1169)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.addLogger(LogManager.java:1194)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.demandLogger(LogManager.java:525)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.LogManager.demandLogger(LogManager.java:515)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.Logger.demandLogger(Logger.java:654)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.Logger.getLogger(Logger.java:717)
22:41:52  	at java.logging@11.0.27-internal/java.util.logging.Logger.getLogger(Logger.java:701)
22:41:52  	at app//TestLogConfigurationDeadLockWithConf$AddLogger.run(TestLogConfigurationDeadLockWithConf.java:247)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/405

**Comment by pshipton** [comment]
keywords: TestLogConfigurationDeadLock

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_OMR_testList_2/317
jdk_util_other_0
java/util/logging/TestLogConfigurationDeadLock.java
```
05:56:58  Found 4 deadlocked threads: 
05:56:58  "Thread-1" prio=5 Id=28 WAITING
05:56:58  	at java.base@21.0.11-internal/jdk.internal.misc.Unsafe.park(Native Method)
05:56:58  	at java.base@21.0.11-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
05:56:58  	at java.base@21.0.11-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:788)
05:56:58  	at java.base@21.0.11-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1024)
05:56:58  	at java.base@21.0.11-internal/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
05:56:58  	at java.base@21.0.11-internal/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1567)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1384)
05:56:58  	at app//TestLogConfigurationDeadLock$ReadConf.run(TestLogConfigurationDeadLock.java:158)
05:56:58  
05:56:58  "Thread-2" prio=5 Id=29 RUNNABLE
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.resetLoggerContext(LogManager.java:1468)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.reset(LogManager.java:1451)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1581)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.readConfiguration(LogManager.java:1384)
05:56:58  	at app//TestLogConfigurationDeadLock$ReadConf.run(TestLogConfigurationDeadLock.java:158)
05:56:58  
05:56:58  "Thread-3" prio=5 Id=30 RUNNABLE
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager$LoggerWeakRef.dispose(LogManager.java:1097)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.drainLoggerRefQueueBounded(LogManager.java:1174)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.addLogger(LogManager.java:1199)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.demandLogger(LogManager.java:527)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.demandLogger(LogManager.java:517)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.Logger.demandLogger(Logger.java:656)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.Logger.getLogger(Logger.java:720)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.Logger.getLogger(Logger.java:703)
05:56:58  	at app//TestLogConfigurationDeadLock$AddLogger.run(TestLogConfigurationDeadLock.java:177)
05:56:58  
05:56:58  "Thread-4" prio=5 Id=31 BLOCKED on java.util.logging.LogManager$LoggerContext@b41204e6 owned by "Thread-3" Id=30
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager$LoggerWeakRef.dispose(LogManager.java:1097)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.drainLoggerRefQueueBounded(LogManager.java:1174)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.addLogger(LogManager.java:1199)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.demandLogger(LogManager.java:527)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.LogManager.demandLogger(LogManager.java:517)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.Logger.demandLogger(Logger.java:656)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.Logger.getLogger(Logger.java:720)
05:56:58  	at java.logging@21.0.11-internal/java.util.logging.Logger.getLogger(Logger.java:703)
05:56:58  	at app//TestLogConfigurationDeadLock$AddLogger.run(TestLogConfigurationDeadLock.java:177)
```
