### ISSUE TITLE
JDK18 compilation failure - bootstrap error, system property access before init

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13828]
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_mac_OpenJDK/139/consoleFull
```
02:48:50  Exception in thread "(unnamed thread)" java/lang/Error: bootstrap error, system property access before init: os.version
02:48:50  	at java/lang/System.getProperty (java.base@18/System.java:583)
02:48:50  	at java/lang/System.getProperty (java.base@18/System.java:553)
02:48:50  	at sun/security/action/GetPropertyAction.privilegedGetProperty (java.base@18/GetPropertyAction.java:106)
02:48:50  	at jdk/internal/loader/ClassLoaderHelper.<clinit> (java.base@18/ClassLoaderHelper.java:35)
02:48:50  	at jdk/internal/loader/NativeLibraries.<clinit> (java.base@18/NativeLibraries.java:58)
```

**Comment by JasonFengJ9** [comment]
There were lots of OpenJDK update such as [8271820: Implementation of JEP 416: Reimplement Core Reflection with Method Handle](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ed8f09d38f1f29b69a17a3778325143d40d76d11)

https://github.com/eclipse-openj9/openj9/pull/13849 addresses `bootstrap error, system property access before init: os.version`, afterwards the build hits `StackOverflowError`
```
java.lang.StackOverflowError
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3528)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectGetter(MethodHandles.java:3479)
	at java.base/java.lang.invoke.MethodHandleImpl$1.unreflectField(MethodHandleImpl.java:1637)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:144)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1184)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1153)
	at java.base/java.lang.reflect.Field.get(Field.java:428)
	at java.base/java.lang.Class.getParameterTypes(Class.java:4062)
	at java.base/java.lang.Class.checkParameterTypes(Class.java:4549)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:827)
	at java.base/java.lang.invoke.ClassSpecializer.reflectConstructor(ClassSpecializer.java:137)
	at java.base/java.lang.invoke.ClassSpecializer$SpeciesData.deriveSuperClass(ClassSpecializer.java:435)
	at java.base/java.lang.invoke.ClassSpecializer$Factory.generateConcreteSpeciesCodeFile(ClassSpecializer.java:620)
	at java.base/java.lang.invoke.ClassSpecializer$Factory.generateConcreteSpeciesCode(ClassSpecializer.java:571)
	at java.base/java.lang.invoke.ClassSpecializer$Factory.loadSpecies(ClassSpecializer.java:491)
	at java.base/java.lang.invoke.ClassSpecializer.findSpecies(ClassSpecializer.java:195)
	at java.base/java.lang.invoke.BoundMethodHandle$SpeciesData.extendWith(BoundMethodHandle.java:370)
	at java.base/java.lang.invoke.LambdaFormEditor.newSpeciesData(LambdaFormEditor.java:466)
	at java.base/java.lang.invoke.LambdaFormEditor.bindArgumentForm(LambdaFormEditor.java:529)
	at java.base/java.lang.invoke.LambdaFormEditor.bindArgumentL(LambdaFormEditor.java:473)
	at java.base/java.lang.invoke.BoundMethodHandle.bindArgumentL(BoundMethodHandle.java:92)
	at java.base/java.lang.invoke.MethodHandle.bindArgumentL(MethodHandle.java:1701)
	at java.base/java.lang.invoke.MethodHandle.bindTo(MethodHandle.java:1617)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:311)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:266)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:383)
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:903)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:868)
	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.fieldAccessor(MethodHandleObjectFieldAccessorImpl.java:42)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:164)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1184)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1153)
	at java.base/java.lang.reflect.Field.get(Field.java:428)
	at java.base/java.lang.Class.getParameterTypes(Class.java:4062)
```

Workaround the `StackOverflowError` temporally, an `InternalError` occurred.
```
Exception in thread "main" java.lang.InternalError: java.lang.reflect.Method::parameterTypes cannot be accessed reflectively before java.lang.invoke is initialized
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:133)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1184)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1153)
	at java.base/java.lang.reflect.Field.get(Field.java:428)
	at java.base/java.lang.Class.getParameterTypes(Class.java:4077)
``` 

More changes are still required.

**Comment by tajila** [comment]
Use `-Djdk.reflect.useDirectMethodHandle=false` to disable MH support

**Comment by JasonFengJ9** [comment]
> Use -Djdk.reflect.useDirectMethodHandle=false to disable MH support

This fixed `InternalError: java.lang.reflect.Method::parameterTypes cannot be accessed reflectively before java.lang.invoke is initialized`.

**Comment by JasonFengJ9** [comment]
This issue is addressed via [JDK18+ returns os.version before System.systemProperties is initialized](https://github.com/eclipse-openj9/openj9/pull/13849).

Other `JDK18` build issues are being tracked via https://github.com/eclipse-openj9/openj9/issues/13852 &  https://github.com/eclipse-openj9/openj9/issues/13844.
