### ISSUE TITLE
testDDRExtJunit_FindExtThread_0 [ERROR] '!findstackvalue  0x<value>' output is null or empty

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13868]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_aarch64_linux_Nightly_testList_1/36 - cent8-aarch64-3
testDDRExtJunit_FindExtThread_0 `NoOptions`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_extended.functional_aarch64_linux_Nightly_testList_1/36/functional_test_output.tar.gz

See also https://github.com/eclipse-openj9/openj9/issues/11546

```
...
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!setvm  18446744073709551615'
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output does not contain success key : is larger than the max available memory address: 0xFFFFFFFF[DDRExtTesterBase] [INFO] Validation started for : '!findmethodfrompc  281471980446289'
...
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x0000000000068C00' output is null or empty
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_linux_Nightly_testList_1/48
testDDRExtJunit_FindExtThread_0 `NoOptions`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.functional_aarch64_linux_Nightly_testList_1/48/functional_test_output.tar.gz
```
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output does not contain success key : is larger than the max available memory address: 0xFFFFFFFF
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output :Error: Specified value (=-1) is not a javaVM or vmThread pointer, VM not set
```
```
     [java] [AutoRun] [INFO] Starting testFindstackvalue(j9vm.test.ddrext.junit.TestFindExt)
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x00000000000515E8' output is null or empty
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_aarch64_linux_Nightly_testList_0/82
testDDRExtJunit_FindExtThread_0

```
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output does not contain success key : is larger than the max available memory address: 0xFFFFFFFF
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output :Error: Specified value (=-1) is not a javaVM or vmThread pointer, VM not set
```
```
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x0000000000040B88' output is null or empty
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
 ```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly_testList_1/237/ - [win2012-x86-5](https://openj9-jenkins.osuosl.org/computer/win2012-x86-5)
testDDRExtJunit_FindExtThread_0 `NoOptions`
```
    [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output does not contain success key : is larger than the max available memory address: 0xFFFFFFFF
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!findmethodfrompc  876890054013'
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output :Error: Specified value (=-1) is not a javaVM or vmThread pointer, VM not set
     [java] 
```
```
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x0000000000061918' output :
     [java] !j9vmthread 1c6d00
     [java] 	Found at 1c6ad8
     [java] !j9vmthread 18b00
     [java] 	Found at 2059c8
     [java] Problem running command:
     [java] U64 contains value larger than Long.MAX_VALUE
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
```

@keithc-ca fyi the `U64 contains value larger than Long.MAX_VALUE`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_aarch64_linux_Nightly_testList_0/177
testDDRExtJunit_FindExtThread_0

```
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!setvm  18446744073709551615'
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output does not contain success key : is larger than the max available memory address: 0xFFFFFFFF
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output :Error: Specified value (=-1) is not a javaVM or vmThread pointer, VM not set
```
```
     [java] [AutoRun] [INFO] Starting testFindstackvalue(j9vm.test.ddrext.junit.TestFindExt)
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x000000000004ADD0' output is null or empty
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/241
testDDRExtJunit_FindExtThread_0
```
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output does not contain success key : is larger than the max available memory address: 0xFFFFFFFF
     [java] [DDRExtTesterBase] [ERROR] '!setvm  18446744073709551615' output :Error: Specified value (=-1) is not a javaVM or vmThread pointer, VM not set
```
```
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x00000000000B9050' output is null or empty
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
```

**Comment by JasonFengJ9** [comment]
`job/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal/10/tapResults/`
```
11:58:45  openjdk version "19-internal" 2022-09-20
11:58:45  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextppc64aixPersonal)
11:58:45  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 AIX ppc64-64-Bit Compressed References 20220607_85 (JIT enabled, AOT enabled)
11:58:45  OpenJ9   - 52f04efbff5
11:58:45  OMR      - c60867497c6
11:58:45  JCL      - 5ccf02de16a based on jdk-19+25)

===============================================
Running test testDDRExtJunit_FindExtThread_0 ...
===============================================
testDDRExtJunit_FindExtThread_0 Start Time: Tue Jun  7 12:38:41 2022 Epoch Time (ms): 1654623521581
variation: NoOptions
JVM_OPTIONS:  

[java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x0000000030060A40' output is null or empty
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
     [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)

     [java] [AutoRun] [INFO] Errors:   0 out of 13 test cases.
     [java] [AutoRun] [INFO] Failures: 1 out of 13 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 1
     [java] [AutoRun] [ERROR] testFindstackvalue(j9vm.test.ddrext.junit.TestFindExt)

BUILD FAILED
/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/aqa-tests/TKG/output_16546232901864/testDDRExtJunit_FindExtThread_0/tck_ddrext.xml:152: The following error occurred while executing this line:
/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/aqa-tests/TKG/output_16546232901864/testDDRExtJunit_FindExtThread_0/tck_ddrext.xml:140: Java returned: 254

Total time: 23 seconds

testDDRExtJunit_FindExtThread_0_FAILED
```
