### ISSUE TITLE
OpenJDK java/lang/ProcessBuilder/Basic.java failures blocking OpenJDK11 promotion

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13865]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_OpenJDK11/13/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_OpenJDK11/13/

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/13
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/lang/ProcessBuilder/Basic.java#id1.Basic_id1
    java/lang/ProcessBuilder/Basic.java#id1.Basic_id1

Guessing the problem is related to the test change https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/87d3be4e45cca1618958412224031e58f4e998f9 which added `-Xlog:all=warning:stderr` which isn't supported by OpenJ9 and causes `JVMJ9VM007W Command-line option unrecognised: -Xlog:all=warning:stderr` and also enables the verbose gc log due to the `-Xlog:all` part, which it shouldn't.

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/13/openjdk_test_output.tar.gz
```
10:51:54  ACTION: main -- Error. Program `/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 2400000ms, elapsed time including timeout handling was 2417620ms).
10:51:54  REASON: User specified action: run main/othervm/timeout=300 Basic 
10:51:54  TIME:   2417.62 seconds
10:51:54  messages:
10:51:54  command: main Basic
10:51:54  reason: User specified action: run main/othervm/timeout=300 Basic 
10:51:54  Mode: othervm [/othervm specified]
10:51:54  Additional options from @modules: --add-modules java.base --add-opens java.base/java.lang=ALL-UNNAMED
10:51:54  Timeout information:
10:51:54  Running jcmd on process 61666
10:51:54  Dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_16360348544265/jdk_lang_0/work/scratch/0/core.20211104.105122.61666.0001.dmp
10:51:54  Running jstack on process 61666
10:51:54  2021-11-04T10:51:36.350541028
10:51:54  Virtual machine: 61666 JVM information:
10:51:54  JRE 11 Linux s390x-64-Bit Compressed References 20211104_14 (JIT enabled, AOT enabled)
10:51:54  OpenJ9   - 0b3d2322056
10:51:54  OMR      - 79e5193c139
10:51:54  JCL      - 6437400a73d based on jdk-11.0.14+1
10:51:54  
10:51:54  "main" prio=5 Id=1 WAITING
10:51:54  	at java.base@11.0.14-internal/java.lang.Object.wait(Native Method)
10:51:54  	at java.base@11.0.14-internal/java.lang.Object.wait(Object.java:221)
10:51:54  	at java.base@11.0.14-internal/java.lang.Thread.join(Thread.java:746)
10:51:54  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
10:51:54  
10:51:54  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
10:51:54  
10:51:54  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
10:51:54  
10:51:54  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
10:51:54  
10:51:54  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
10:51:54  
10:51:54  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
10:51:54  
10:51:54  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
10:51:54  
10:51:54  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
10:51:54  
10:51:54  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
10:51:54  
10:51:54  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
10:51:54  
10:51:54  "IProfiler" prio=5 Id=12 RUNNABLE
10:51:54  
10:51:54  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
10:51:54  	at java.base@11.0.14-internal/java.lang.Object.wait(Native Method)
10:51:54  	at java.base@11.0.14-internal/java.lang.Object.wait(Object.java:221)
10:51:54  	at java.base@11.0.14-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
10:51:54  	at java.base@11.0.14-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
10:51:54  	at java.base@11.0.14-internal/java.lang.Thread.run(Thread.java:866)
10:51:54  	at java.base@11.0.14-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
10:51:54  
10:51:54  "Concurrent Mark Helper" prio=1 Id=13 RUNNABLE
10:51:54  
10:51:54  "Finalizer thread" prio=5 Id=14 RUNNABLE
10:51:54  
10:51:54  "GC Worker" prio=5 Id=15 RUNNABLE
10:51:54  
10:51:54  "GC Worker" prio=5 Id=16 RUNNABLE
10:51:54  
10:51:54  "GC Worker" prio=5 Id=17 RUNNABLE
10:51:54  
10:51:54  "Attach API wait loop" prio=10 Id=20 RUNNABLE
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
10:51:54  
10:51:54  "MainThread" prio=5 Id=22 TIMED_WAITING
10:51:54  	at java.base@11.0.14-internal/java.lang.Thread.sleep(Native Method)
10:51:54  	at java.base@11.0.14-internal/java.lang.Thread.sleep(Thread.java:997)
10:51:54  	at app//Basic.realMain(Basic.java:2195)
10:51:54  	at app//Basic.main(Basic.java:2786)
10:51:54  	at java.base@11.0.14-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:51:54  	at java.base@11.0.14-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:51:54  	at java.base@11.0.14-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:51:54  	at java.base@11.0.14-internal/java.lang.reflect.Method.invoke(Method.java:566)
10:51:54  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:51:54  	at java.base@11.0.14-internal/java.lang.Thread.run(Thread.java:866)
10:51:54  
10:51:54  "file lock watchdog" prio=10 Id=23967 TIMED_WAITING
10:51:54  	at java.base@11.0.14-internal/java.lang.Object.wait(Native Method)
10:51:54  	at java.base@11.0.14-internal/java.lang.Object.wait(Object.java:221)
10:51:54  	at java.base@11.0.14-internal/java.util.TimerThread.mainLoop(Timer.java:553)
10:51:54  	at java.base@11.0.14-internal/java.util.TimerThread.run(Timer.java:506)
10:51:54  
10:51:54  "Attachment 39038" prio=10 Id=23998 RUNNABLE
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
10:51:54  	at java.base@11.0.14-internal/openj9/internal/tools/attach/target/DiagnosticUtils$$Lambda$5/0x0000000000000000.apply(Unknown Source)
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
10:51:54  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
10:51:54  
10:51:54  
10:51:54  --- Timeout information end.
10:51:54  elapsed time (seconds): 2417.62
10:51:54  configuration:
10:51:54  Boot Layer
10:51:54    add modules: java.base           
10:51:54    add opens:   java.base/java.lang ALL-UNNAMED
10:51:54  
10:51:54  STDOUT:
10:51:54  This appears to be a Unix system.
10:51:54  Testing ASCII environment values
10:51:54  Testing Latin1 environment values
10:51:54  Testing Unicode environment values
10:51:54  Testing directory .
10:51:54  Testing directory ..
10:51:54  Testing directory /
10:51:54  Testing directory /bin
10:51:54  cmdp
10:51:54  cmdp 0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkbinary/j2sdk-image/bin/java
10:51:54  cmdp 1: -XX:+DisplayVMOutputToStderr
10:51:54  cmdp 2: -classpath
10:51:54  cmdp 3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_16360348544265/jdk_lang_0/work/classes/0/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/jvmtest/openjdk/jtreg/lib/jtreg.jar
10:51:54  cmdp 4: Basic$JavaChild
10:51:54  cmdp 5: System.getenv()
10:51:54  envp
10:51:54  envp 0: LC_ALL=C
10:51:54  envp 1: FO=BR
10:51:54  Timeout refired 2400 times
10:51:54  STDERR:
10:51:54  JVMJ9VM007W Command-line option unrecognised: -Xlog:all=warning:stderr
10:51:54  
10:51:54  <?xml version="1.0" ?>
10:51:54  
10:51:54  <verbosegc xmlns="http://www.ibm.com/j9/verbosegc" version="79e5193c139_CMPRSS">
10:51:54  
10:51:54  <initialized id="1" timestamp="2021-11-04T10:11:27.860">
10:51:54    <attribute name="gcPolicy" value="-Xgcpolicy:gencon" />
10:51:54    <attribute name="maxHeapSize" value="0x7b060000" />
10:51:54    <attribute name="initialHeapSize" value="0x800000" />
10:51:54    <attribute name="compressedRefs" value="true" />
10:51:54    <attribute name="compressedRefsDisplacement" value="0x0" />
10:51:54    <attribute name="compressedRefsShift" value="0x0" />
10:51:54    <attribute name="pageSize" value="0x1000" />
10:51:54    <attribute name="pageType" value="not used" />
10:51:54    <attribute name="requestedPageSize" value="0x1000" />
10:51:54    <attribute name="requestedPageType" value="not used" />
10:51:54    <attribute name="gcthreads" value="4" />
10:51:54    <attribute name="gcthreads Concurrent Mark" value="1" />
10:51:54    <attribute name="packetListSplit" value="1" />
10:51:54    <attribute name="cacheListSplit" value="1" />
10:51:54    <attribute name="splitFreeListSplitAmount" value="1" />
10:51:54    <attribute name="numaNodes" value="0" />
10:51:54    <system>
10:51:54      <attribute name="physicalMemory" value="8256180224" />
10:51:54      <attribute name="numCPUs" value="4" />
10:51:54      <attribute name="architecture" value="s390x" />
10:51:54      <attribute name="os" value="Linux" />
10:51:54      <attribute name="osVersion" value="3.10.0-1160.25.1.el7.s390x" />
10:51:54    </system>
10:51:54    <vmargs>
10:51:54      <vmarg name="-Xoptionsfile=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkbinary/j2sdk-image/lib/opti..." />
10:51:54      <vmarg name="-Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword..." />
10:51:54      <vmarg name="-Xjcl:jclse29" />
10:51:54      <vmarg name="-Dcom.ibm.oti.vm.bootstrap.library.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkb..." />
10:51:54      <vmarg name="-Dsun.boot.library.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkbinary/j2sdk-imag..." />
10:51:54      <vmarg name="-Djava.library.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkbinary/j2sdk-image/li..." />
10:51:54      <vmarg name="-Djava.home=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkbinary/j2sdk-image" />
10:51:54      <vmarg name="-Duser.dir=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_16360348544265/j..." />
10:51:54      <vmarg name="-Djava.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_163603485..." />
10:51:54      <vmarg name="-XX:+DisplayVMOutputToStderr" />
10:51:54      <vmarg name="-Xlog:all=warning:stderr" />
10:51:54      <vmarg name="-Djava.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_163603485..." />
10:51:54      <vmarg name="-Dsun.java.command=Basic$JavaChild sleep" />
10:51:54      <vmarg name="-Dsun.java.launcher=SUN_STANDARD" />
10:51:54      <vmarg name="-Dsun.java.launcher.pid=64445" />
10:51:54    </vmargs>
10:51:54  </initialized>
10:51:54  
10:51:54  >'-1'< not equal to '74'
10:51:54  java.lang.Throwable
10:51:54  	at java.base/java.lang.Thread.dumpStack(Thread.java:539)
10:51:54  	at Basic.fail(Basic.java:2776)
10:51:54  	at Basic.fail(Basic.java:2777)
10:51:54  	at Basic.equal(Basic.java:2783)
10:51:54  	at Basic$12.run(Basic.java:2160)
10:51:54  JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_16360348544265/jdk_lang_0/work/scratch/0/core.20211104.105122.61666.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
10:51:54  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_16360348544265/jdk_lang_0/work/scratch/0/core.20211104.105122.61666.0001.dmp
```

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/pull/13866 to fix `-Xlog:all=warning`, but it doesn't fix the failures.
