### ISSUE TITLE
OAuthTest_0 ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13892]
OAuthTest_0 which is a new test

Looks like every platform for jdk17 failed, although differently than on jdk8 and 11.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK17/79/

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly_testList_1/144
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_mac_Nightly_testList_2/137
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_mac_Nightly_testList_2/145
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly_testList_1/138/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_aarch64_linux_Nightly_testList_2/23
```
STF 07:06:03.408 - +------ Step 4 - Wait for clients to complete
STF 07:06:03.408 - | Wait for processes to meet expectations
STF 07:06:03.408 - |   Processes: [CLI]
STF 07:06:03.408 - |
STF 07:06:03.408 - Monitoring processes: CLI
CLI stderr Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
CLI stderr 	at java.net.PlainSocketImpl.socketConnect(Native Method)
CLI stderr 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
CLI stderr 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
CLI stderr 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
CLI stderr 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
CLI stderr 	at java.net.Socket.connect(Socket.java:607)
CLI stderr 	at java.net.Socket.connect(Socket.java:556)
CLI stderr 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
CLI stderr 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
CLI stderr 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
CLI stderr 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
CLI stderr 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
CLI stderr 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
CLI stderr 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1223)
CLI stderr 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
CLI stderr 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
CLI stderr 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
CLI stderr 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1567)
CLI stderr 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
CLI stderr 	at net.adoptopenjdk.test.auth.Client.main(Client.java:23)
```

Example jdk17 failure.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly_testList_2/77
```
22:56:53  STF 21:56:49.812 - +------ Step 4 - Wait for clients to complete
22:56:53  STF 21:56:49.812 - | Wait for processes to meet expectations
22:56:53  STF 21:56:49.812 - |   Processes: [CLI]
22:56:53  STF 21:56:49.812 - |
22:56:53  STF 21:56:49.812 - Monitoring processes: CLI
22:56:54  CLI log in YES!
22:56:54  CLI 8889
22:56:56  CLI stderr Exception in thread "main" java.lang.RuntimeException: unexpected result
22:56:56  CLI stderr 	at net.adoptopenjdk.test.auth.Client.main(Client.java:66)
22:56:56  STF 21:56:52.707 - **FAILED** Process CLI ended with exit code (1) and not the expected exit code/s (0)
22:56:56  STF 21:56:52.708 - Monitoring Report Summary:
22:56:56  STF 21:56:52.708 -   o Process CLI ended with exit code (1) and not the expected exit code/s (0)
22:56:56  STF 21:56:52.708 - Killing processes: AUTH CLI SER
22:56:56  STF 21:56:52.708 -   o Process AUTH pid 5824 stop()
22:56:56  STF 21:56:52.709 -   o Process AUTH pid 5824 killed
22:56:56  AUTH stderr java.io.IOException: headers already sent
22:56:56  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.ExchangeImpl.sendResponseHeaders(ExchangeImpl.java:206)
22:56:56  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.HttpExchangeImpl.sendResponseHeaders(HttpExchangeImpl.java:85)
22:56:56  AUTH stderr 	at net.adoptopenjdk.test.auth.AuthCenter$ProtectedResourceHandler.handle(AuthCenter.java:133)
22:56:56  AUTH stderr 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
22:56:56  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
22:56:56  AUTH stderr 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
22:56:56  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:728)
22:56:56  AUTH stderr 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
22:56:56  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:695)
22:56:56  AUTH stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
22:56:56  AUTH stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
22:56:56  AUTH stderr 	at java.base/java.lang.Thread.run(Thread.java:884)
```

**Comment by pshipton** [comment]
@Mesbah-Alam @llxia can we exclude this new test pls until it works.

**Comment by llxia** [comment]
This test is added via
https://github.com/adoptium/aqa-tests/pull/2970
https://github.com/adoptium/aqa-systemtest/pull/457

@joeyleeeeeee97 do we need special machine configuration for this test?
