### ISSUE TITLE
JDK11 java.lang.ClassCastException: java.util.Collections$SynchronizedMap incompatible with java.lang.invoke.MethodHandle

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13895]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_1/7/` (`win16x64rt3-6`):
```
23:08:53  java version "11.0.14-beta" 2022-01-18
23:08:53  IBM Semeru Runtime Certified Edition 11.0.14+1-202111090209 (build 11.0.14-beta+1-202111090209)
23:08:53  Eclipse OpenJ9 VM 11.0.14+1-202111090209 (build master-3f6696680, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20211109_183 (JIT enabled, AOT enabled)
23:08:53  OpenJ9   - 3f6696680
23:08:53  OMR      - ec51e647d
23:08:53  JCL      - fbf8b890f0 based on jdk-11.0.14+1)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.openjdk_x86-64_windows&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F183%2Fibm-semeru-certified-jdk_x64_windows_JDK11U_2021-11-09-02-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F183%2Fibm-semeru-certified-jre_x64_windows_JDK11U_2021-11-09-02-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F183%2Fibm-semeru-certified-debugimage_x64_windows_JDK11U_2021-11-09-02-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F183%2Fibm-semeru-certified-testimage_x64_windows_JDK11U_2021-11-09-02-00.zip&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=119&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-11-09T05:00:29.027Z] Running test jdk_util_1 ...
[2021-11-09T05:00:29.027Z] ===============================================
[2021-11-09T05:00:29.027Z] jdk_util_1 Start Time: Mon Nov  8 21:00:27 2021 Epoch Time (ms): 1636434027183
[2021-11-09T05:00:29.027Z] "C:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_1/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_1/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-11-09T05:00:29.027Z] JVMSHRC005I No shared class caches available
[2021-11-09T05:00:32.129Z] JVMSHRC005I No shared class caches available
[2021-11-09T05:00:32.129Z] cache cleanup done
[2021-11-09T05:00:32.129Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2021-11-09T05:00:32.129Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2021-11-09T05:27:38.817Z] --------------------------------------------------
[2021-11-09T05:27:38.817Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/PrimitiveSumTest.java

[2021-11-09T05:27:38.817Z] config java.util.stream.LoggingTestCase.before(): success
[2021-11-09T05:27:38.817Z] test org.openjdk.tests.java.util.stream.PrimitiveSumTest.testOps(): failure
[2021-11-09T05:27:38.817Z] java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
[2021-11-09T05:27:38.817Z] 	at java.base/java.util.stream.TestData$AbstractTestData.toString(TestData.java:242)
[2021-11-09T05:27:38.817Z] 	at java.base/java.lang.String.valueOf(String.java:2997)
[2021-11-09T05:27:38.817Z] 	at com.sun.javatest.regtest.agent.TestNGRunner$RegressionListener.formatParam(TestNGRunner.java:211)
[2021-11-09T05:27:38.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner$RegressionListener.formatParams(TestNGRunner.java:198)
[2021-11-09T05:27:38.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner$RegressionListener.report(TestNGRunner.java:187)
[2021-11-09T05:27:38.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner$RegressionListener.onTestSuccess(TestNGRunner.java:113)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1703)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-11-09T05:27:38.818Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-11-09T05:27:38.818Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-11-09T05:27:38.818Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-11-09T05:27:38.818Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-11-09T05:27:38.818Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-11-09T05:27:38.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-09T05:27:38.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-11-09T05:27:38.818Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-09T05:27:38.818Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-09T05:27:38.818Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-09T05:27:38.818Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2021-11-09T05:27:38.818Z] Caused by: java.lang.invoke.StringConcatException: Generator failed
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.MethodHandleResolver.invokeBsm(MethodHandleResolver.java:176)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:238)
[2021-11-09T05:27:38.818Z] 	... 32 more
[2021-11-09T05:27:38.818Z] Caused by: java.lang.ClassCastException: java.util.Collections$SynchronizedMap incompatible with java.lang.invoke.MethodHandle
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.StringConcatFactory$Stringifiers.forMost(StringConcatFactory.java:1766)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1512)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
[2021-11-09T05:27:38.818Z] 	... 36 more
[2021-11-09T05:27:38.818Z] test org.openjdk.tests.java.util.stream.PrimitiveSumTest.testOps(): skip
[2021-11-09T05:27:38.818Z] java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
[2021-11-09T05:27:38.818Z] 	at java.base/java.util.stream.IntStreamTestDataProvider.<clinit>(IntStreamTestDataProvider.java:101)
[2021-11-09T05:27:38.818Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-09T05:27:38.818Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-09T05:27:38.818Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-09T05:27:38.818Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.handleParameters(Invoker.java:1277)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.createParameters(Invoker.java:992)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1082)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-11-09T05:27:38.818Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-11-09T05:27:38.818Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-11-09T05:27:38.818Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-11-09T05:27:38.818Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-11-09T05:27:38.819Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-11-09T05:27:38.819Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-09T05:27:38.819Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-11-09T05:27:38.819Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-09T05:27:38.819Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-09T05:27:38.819Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-09T05:27:38.819Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2021-11-09T05:27:38.819Z] Caused by: java.lang.invoke.StringConcatException: Generator failed
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.MethodHandleResolver.invokeBsm(MethodHandleResolver.java:176)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:238)
[2021-11-09T05:27:38.819Z] 	... 32 more
[2021-11-09T05:27:38.819Z] Caused by: java.lang.ClassCastException: java.util.Collections$SynchronizedMap incompatible with java.lang.invoke.MethodHandle
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.StringConcatFactory$Stringifiers.forMost(StringConcatFactory.java:1766)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1512)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
[2021-11-09T05:27:38.819Z] 	... 36 more
[2021-11-09T05:27:38.819Z] test org.openjdk.tests.java.util.stream.PrimitiveSumTest.testOps(): skip
[2021-11-09T05:27:38.819Z] java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
[2021-11-09T05:27:38.819Z] 	at java.base/java.util.stream.LongStreamTestDataProvider.<clinit>(LongStreamTestDataProvider.java:101)
[2021-11-09T05:27:38.819Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-09T05:27:38.819Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-09T05:27:38.819Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-09T05:27:38.819Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.Invoker.handleParameters(Invoker.java:1277)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.Invoker.createParameters(Invoker.java:992)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1082)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-11-09T05:27:38.819Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2021-11-09T05:27:38.819Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2021-11-09T05:27:38.819Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2021-11-09T05:27:38.819Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2021-11-09T05:27:38.819Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2021-11-09T05:27:38.819Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-11-09T05:27:38.819Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2021-11-09T05:27:38.819Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2021-11-09T05:27:38.819Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-09T05:27:38.819Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-11-09T05:27:38.820Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-09T05:27:38.820Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-09T05:27:38.820Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-11-09T05:27:38.820Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2021-11-09T05:27:38.820Z] Caused by: java.lang.invoke.StringConcatException: Generator failed
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.MethodHandleResolver.invokeBsm(MethodHandleResolver.java:176)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:238)
[2021-11-09T05:27:38.820Z] 	... 32 more
[2021-11-09T05:27:38.820Z] Caused by: java.lang.ClassCastException: java.util.Collections$SynchronizedMap incompatible with java.lang.invoke.MethodHandle
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.StringConcatFactory$Stringifiers.forMost(StringConcatFactory.java:1766)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1512)
[2021-11-09T05:27:38.820Z] 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
[2021-11-09T05:27:38.820Z] 	... 36 more
[2021-11-09T05:27:38.820Z] 
[2021-11-09T05:27:38.820Z] ===============================================
[2021-11-09T05:27:38.820Z] java/util/stream/test/org/openjdk/tests/java/util/stream/PrimitiveSumTest.java
[2021-11-09T05:27:38.820Z] Total tests run: 3, Failures: 1, Skips: 2
[2021-11-09T05:27:38.820Z] ===============================================

[2021-11-09T05:37:53.279Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
Is it repeatable in a grinder?

**Comment by JasonFengJ9** [comment]
Not reproduced in a 100x grinder at `view/Test_grinder/job/Grinder/19397/`.
Moving out of `0.30.0`.

**Comment by JasonFengJ9** [comment]
[An internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_special.system_ppc64le_linux_testList_0/233/)(`ubu22ppclert-3`)
```
java version "17.0.4" 2022-07-19
IBM Semeru Runtime Certified Edition 17.0.4.0 (build 17.0.4+8)
Eclipse OpenJ9 VM 17.0.4.0 (build openj9-0.33.0, JRE 17 Linux ppc64le-64-Bit Compressed References 20220718_199 (JIT enabled, AOT enabled)
OpenJ9   - 04a55b45b
OMR      - b58aa2708
JCL      - 7fe2fc9e0bd based on jdk-17.0.4+8)
```

```
[2022-08-04T21:45:00.955Z] variation: Mode101
[2022-08-04T21:45:00.955Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs 

[2022-08-04T21:45:24.842Z] DLT 21:45:21.211 - First failure detected by thread: load-11. Not creating dumps as no dump generation is requested for this load test
[2022-08-04T21:45:24.842Z] DLT 21:45:21.216 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa1.xml
[2022-08-04T21:45:24.842Z] DLT 21:45:21.218 - suite.isCreateDump() : false
[2022-08-04T21:45:24.842Z] DLT 21:45:21.273 - Test failed
[2022-08-04T21:45:24.842Z] DLT   Failure num.  = 1
[2022-08-04T21:45:24.842Z] DLT   Test number   = 15
[2022-08-04T21:45:24.842Z] DLT   Test details  = 'JUnit[net.openj9.test.PD2Primitive.TestPD2Primitives2PD]'
[2022-08-04T21:45:24.842Z] DLT   Suite number  = 0
[2022-08-04T21:45:24.842Z] DLT   Thread number = 11
[2022-08-04T21:45:24.842Z] DLT >>> Captured test output >>>
[2022-08-04T21:45:24.842Z] DLT testStarted : intLeadingZeros(net.openj9.test.PD2Primitive.TestPD2Primitives2PD)
[2022-08-04T21:45:24.842Z] DLT testFailure: intLeadingZeros(net.openj9.test.PD2Primitive.TestPD2Primitives2PD): net.openj9.test.PD2Primitive.TestPD2Primitives2PD incompatible with java.lang.invoke.MethodHandle
[2022-08-04T21:45:24.842Z] DLT java.lang.ClassCastException: net.openj9.test.PD2Primitive.TestPD2Primitives2PD incompatible with java.lang.invoke.MethodHandle
[2022-08-04T21:45:24.842Z] DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-08-04T21:45:24.842Z] DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-08-04T21:45:24.842Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-08-04T21:45:24.843Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-08-04T21:45:24.843Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2022-08-04T21:45:24.843Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-08-04T21:45:24.843Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2022-08-04T21:45:24.843Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2022-08-04T21:45:24.843Z] DLT 	at java.base/java.lang.Thread.run(Thread.java:858)

[2022-08-04T21:45:24.844Z] DaaLoadTest_daa1_special_5m_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26551/)
