### ISSUE TITLE
osx1013-x86-3 SSL_ERROR_SYSCALL in connection to github.com

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13904]
Disabled [osx1013-x86-3](https://openj9-jenkins.osuosl.org/computer/osx1013-x86-3/)

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_x86-64_mac_Nightly/76/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_mac_Nightly_testList_1/146/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_mac_Nightly_testList_2/146/console
```
Fetching upstream changes from https://github.com/adoptium/aqa-tests.git
 > git --version # timeout=10
 > git --version # 'git version 2.19.2'
 > git fetch --tags --progress -- https://github.com/adoptium/aqa-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/adoptium/aqa-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/adoptium/aqa-tests.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2681)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2102)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:624)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:853)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:160)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:153)
```

@AdamBrousseau

**Comment by pshipton** [comment]
The 3 failures all occurred around 9:50pm and I didn't find any other failures. Presumably the machine was used to run other jobs through the night. I've reconnected the machine and will assume it was a temporary network problem which was resolved.
