### ISSUE TITLE
JDK18 NPE message generation need accommodate JEP416 MH change

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13901]
`jdk.reflect.useDirectMethodHandle` re-enabled w/ https://github.com/eclipse-openj9/openj9/pull/13899, 
```
FAILED: test_creation
java.lang.AssertionError: expected [null] but found [Cannot invoke "java.lang.invoke.MethodHandle.linkToSpecial(java.lang.Object, java.lang.invoke.MemberName)" because "<parameter1>" is null]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotSame(Assert.java:772)
	at org.testng.Assert.assertNull(Assert.java:708)
	at org.testng.Assert.assertNull(Assert.java:697)
	at org.openj9.test.jep358.NPEMessageTests.test_creation(NPEMessageTests.java:1023)
	at java/lang/invoke/LambdaForm$DMH/0x0000000000408160.invokeVirtual(LambdaForm$DMH)
	at java/lang/invoke/LambdaForm$MH/0x000000000040aa30.invoke(LambdaForm$MH)
	at java/lang/invoke/LambdaForm$MH/0x0000000000269230.invokeExact_MT(LambdaForm$MH)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

===============================================
    JEP358NPEMessageTests
    Tests run: 118, Failures: 1, Skips: 0
===============================================

JEP358NPEMessageTests_0_FAILED
```

NPE message generation has to adopt JEP 416 MH stackframes.

**Comment by pshipton** [comment]
@JasonFengJ9 is this still an issue or resolved by https://github.com/eclipse-openj9/openj9/pull/13952 ?

**Comment by JasonFengJ9** [comment]
Closing via https://github.com/eclipse-openj9/openj9/pull/13952
