### ISSUE TITLE
JDK17 head cmdLineTester_lockWordAlignment_Object_d_0_FAILED : java.lang.InternalError at java.base/sun.invoke.util.Wrapper.forPrimitiveType(Wrapper.java:274)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13936]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Nightly/81/tapResults/ (`aix71-p8-3`)
```
05:02:57  openjdk version "17.0.1-internal" 2021-10-19
05:02:57  OpenJDK Runtime Environment (build 17.0.1-internal+0-adhoc.****.BuildJDK17ppc64aixNightly)
05:02:57  Eclipse OpenJ9 VM (build master-7ce2fd86691, JRE 17 AIX ppc64-64-Bit Compressed References 20211116_83 (JIT enabled, AOT enabled)
05:02:57  OpenJ9   - 7ce2fd86691
05:02:57  OMR      - b95fd53e283
05:02:57  JCL      - 8acff7a8b92 based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Nightly&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_ppc64_aix_Nightly%2F83%2FOpenJ9-JDK17-ppc64_aix-20211116-001318.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_ppc64_aix_Nightly%2F83%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=ci-eclipse-openj9&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=7ce2fd866910cb44eee94d00c72ea06c835dd12a&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test cmdLineTester_lockWordAlignment_Object_d_0 ...
===============================================
cmdLineTester_lockWordAlignment_Object_d_0 Start Time: Tue Nov 16 11:08:46 2021 Epoch Time (ms): 1637078926584
variation: NoOptions
JVM_OPTIONS:  

---TEST RESULTS---
Exception in thread "main" java.lang.InternalError
	at java.base/sun.invoke.util.Wrapper.forPrimitiveType(Wrapper.java:274)
	at java.base/sun.invoke.util.Wrapper.forBasicType(Wrapper.java:348)
	at java.base/sun.invoke.util.BytecodeDescriptor.unparseSig(BytecodeDescriptor.java:149)
	at java.base/sun.invoke.util.BytecodeDescriptor.unparseMethod(BytecodeDescriptor.java:144)
	at java.base/java.lang.invoke.MethodType.toMethodDescriptorString(MethodType.java:1190)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.generateConstructor(InnerClassLambdaMetafactory.java:449)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:357)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:315)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:228)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:341)
	at java.lang.invoke.LambdaForm$DMH/0x00000000231b2c50.invokeStatic(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000022f928d0.invokeExact_MT(LambdaForm$MH)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:196)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.open(SystemModuleFinders.java:467)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:488)
	at java.base/jdk.internal.loader.BootLoader.findResourceAsStream(BootLoader.java:174)
	at java.base/java.lang.Module.getResourceAsStream(Module.java:1671)
	at java.base/com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:185)
	at java.base/com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:683)
	at java.base/com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:874)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:868)
	at java.base/java.lang.Thread.uncaughtException(Thread.java:1396)

cmdLineTester_lockWordAlignment_Object_d_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Nightly_testList_1/82

@tajila I just switched to test the head stream instead of the 17.0.1 stream and this problem has occurred in the first/last two builds. After running all the cmdline tests, this occurs at the end, an uncaughtException which results in the InternalError. Can somebody take a look?

**Comment by pshipton** [comment]
Grinder https://openj9-jenkins.osuosl.org/job/Grinder/403/ - aix71-p8-5
