### ISSUE TITLE
OpenJDK acceptance failing to promote

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13943]
I'm not sure why the OpenJDK acceptance build is failing to automatically promote. It's been happening for a little while now.

https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/156/console
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 19
	at java.base/java.lang.String.substring(String.java:2691)
	at jdk.internal.reflect.GeneratedMethodAccessor255.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:485)
	at ___cps.transform___(Native Method)
```

@AdamBrousseau

**Comment by pshipton** [comment]
Last build that promoted automatically https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/141/

**Comment by AdamBrousseau** [comment]
Guessing head is now at 19? I'll take a look.

**Comment by pshipton** [comment]
Guessing head is now at 19? 

No, the code split for Java 18 doesn't occur until Dec 9

**Comment by pshipton** [comment]
Adam said: the issue is OPENJ9_REPO doesn't have the .git suffix so some parsing in the promote fails.

**Comment by AdamBrousseau** [comment]
This line if we ever want to fix it to be more robust
https://github.com/eclipse-openj9/openj9/blob/4a7c1cd0b6d8b47f21287d993da7742367a52c73/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy#L485
