### ISSUE TITLE
OpenJ9 supports -XX:[+|-]ShowHiddenFrames?

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13951]
## OpenJDK (RI) behaviours

RI has a command line option `-XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames` to hide hidden frames (by default) and show those frames when requested.

For a test code snippet using `Lambda`:
```
Consumer<String> con = TestNPE::testFunc;
con.accept("Hi ");
public static void testFunc(String str) {
	new Throwable("Got: " + str).printStackTrace();
}
```

By default, RI hides the `Lambda` frames:
```
java.lang.Throwable: Got: Hi 
	at a.se.npe.TestNPE.testFunc(TestNPE.java:55)
	at a.se.npe.TestNPE.testAll(TestNPE.java:46)
```
W/ `-XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames`:
```
java.lang.Throwable: Got: Hi 
	at a.se.npe.TestNPE.testFunc(TestNPE.java:55)
	at a.se.npe.TestNPE$$Lambda$1/0x0000000800c00a18.accept(Unknown Source)
	at a.se.npe.TestNPE.testAll(TestNPE.java:46)
```

For a test code snippet using `JEP416` `MH`:
```
	NullPointerException.class.getDeclaredConstructor().newInstance().printStackTrace();
```

By default, RI hides the MH frames:
```
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at a.se.npe.TestNPE.testAll(TestNPE.java:25)
```
W/ `-XX:+UnlockDiagnosticVMOptions -XX:+ShowHiddenFrames`:
```
java.lang.NullPointerException
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.invokeImpl(DirectConstructorHandleAccessor.java:91)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at a.se.npe.TestNPE.testAll(TestNPE.java:25)
```

## OpenJ9 behaviours
OpenJ9 output for first test case:
```
java.lang.Throwable: Got: Hi 
	at a.se.npe.TestNPE.testFunc(TestNPE.java:55)
	at a.se.npe.TestNPE$$Lambda$1/0x00000000154c42c0.accept(Unknown Source)
	at a.se.npe.TestNPE.testAll(TestNPE.java:46)
```

OpenJ9 output for second test case:
```
java.lang.NullPointerException
	at java.lang.invoke.LambdaForm$DMH/0x00000000d7819e20.newInvokeSpecial(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x00000000d903fa20.invokeExact_MT(LambdaForm$MH)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.invokeImpl(DirectConstructorHandleAccessor.java:91)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at a.se.npe.TestNPE.testAll(TestNPE.java:25)
```

Ideally OpenJ9 can hide those `Lambda`/`LambdaForm`MH frames by default to match RI behaviours, which also might simplify `FrameIterator` checking for `J9AccMethodFrameIteratorSkip`.

**Comment by gacholio** [comment]
This isn't as simple as setting the skip bit or not - the bit is still required for security checks, etc.

**Comment by tajila** [comment]
@JasonFengJ9 Does `-XX:[+|-]ShowHiddenFrames` only affect exception stacktraces?

**Comment by JasonFengJ9** [comment]
> Does -XX:[+|-]ShowHiddenFrames only affect exception stacktraces?

@tajila It also affects stacktraces retrieved via `StackWalker` as well. 

## OpenJDK (RI) JDK18 behaviours

`testStackWalkerFunc` retrieving stacktraces via  `StackWalker`:
```
public static void testStackWalkerFunc(String str) {
	List<StackWalker.StackFrame> stack = StackWalker.getInstance().walk(s -> s.collect(Collectors.toList()));
	for (StackWalker.StackFrame sf : stack) {
		System.out.println(sf.getClassName() + "::" + sf.getMethodName() + ":" + sf.getLineNumber());
	}
}
```

Invoke `testStackWalkerFunc` w/ Lambda:
```
	Consumer<String> con = TestNPE::testStackWalkerFunc;
	con.accept("Hi ");
```

By default, RI hides the `Lambda` frames:
```
a.se.npe.TestNPE::testStackWalkerFunc:78
a.se.npe.TestNPE::testAll:60
a.se.npe.TestNPE::main:21
```
W/ `-XX:+UnlockDiagnosticVMOptions` `-XX:+ShowHiddenFrames`:
```
a.se.npe.TestNPE::testStackWalkerFunc:78
a.se.npe.TestNPE$$Lambda$1/0x0000000800c00a00::accept:-1
a.se.npe.TestNPE::testAll:60
a.se.npe.TestNPE::main:21
```

Invoke `testStackWalkerFunc` w/ JEP 416
```
	Method methodSWF = this.getClass().getDeclaredMethod("testStackWalkerFunc", String.class);
	methodSWF.invoke(this, "hi");
```

By default, RI hides the `MH` frames:
```
a.se.npe.TestNPE::testStackWalkerFunc:78
a.se.npe.TestNPE::testAll:68
a.se.npe.TestNPE::main:21
```
W/ `-XX:+UnlockDiagnosticVMOptions` `-XX:+ShowHiddenFrames`:
```
a.se.npe.TestNPE::testStackWalkerFunc:78
java.lang.invoke.Invokers$Holder::invokeExact_MT:-1
a.se.npe.TestNPE::testAll:68
a.se.npe.TestNPE::main:21
```

## OpenJ9 behaviours

OpenJ9 JDK18 doesn't show `Lambda` & `MH` frames:
```
a.se.npe.TestNPE::testStackWalkerFunc:78
a.se.npe.TestNPE::testAll:60
a.se.npe.TestNPE::main:21
```

```
a.se.npe.TestNPE::testStackWalkerFunc:78
a.se.npe.TestNPE::testAll:68
a.se.npe.TestNPE::main:21
```

**Comment by tajila** [comment]
See https://github.com/eclipse-openj9/openj9/pull/3627

**Comment by fengxue-IS** [comment]
Closing as #3627 and #14688 has been merged
