### ISSUE TITLE
JDK17 Head jdk_net_1_FAILED : test ServerPushWithDiffTypes.test(): failure

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13984]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_x86-64_linux/29/` (`cent7x64-1-7`):
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1+12 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1+12 (build master-0f828acf4, JRE 17 Linux amd64-64-Bit Compressed References 20211120_41 (JIT enabled, AOT enabled)
OpenJ9   - 0f828acf4
OMR      - 83214375c
JCL      - df273956de9 based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_net_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9-IBM%2F41%2Fibm-semeru-certified-jdk_x64_linux_JDK17U_2021-11-20-15-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9-IBM%2F41%2Fibm-semeru-certified-testimage_x64_linux_JDK17U_2021-11-20-15-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9-IBM%2F41%2Fibm-semeru-certified-debugimage_x64_linux_JDK17U_2021-11-20-15-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28centos6%7C%7Crhel6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-11-20T16:51:17.982Z] Running test jdk_net_1 ...
[2021-11-20T16:51:17.982Z] ===============================================
[2021-11-20T16:51:17.982Z] jdk_net_1 Start Time: Sat Nov 20 08:51:13 2021 Epoch Time (ms): 1637427073630
[2021-11-20T16:51:17.982Z] "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-11-20T16:51:17.982Z] JVMSHRC005I No shared class caches available
[2021-11-20T16:51:17.982Z] JVMSHRC005I No shared class caches available
[2021-11-20T16:51:17.983Z] cache cleanup done
[2021-11-20T16:51:17.983Z] variation: Mode650
[2021-11-20T16:51:17.983Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-11-20T16:57:46.013Z] --------------------------------------------------
[2021-11-20T16:57:46.013Z] TEST: java/net/httpclient/http2/ServerPushWithDiffTypes.java

[2021-11-20T16:57:46.022Z] STDOUT:
[2021-11-20T16:57:46.022Z] test ServerPushWithDiffTypes.test(): failure
[2021-11-20T16:57:46.022Z] java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$UniWhenComplete@e0c034a0 rejected from java.util.concurrent.ThreadPoolExecutor@2210844b[Shutting down, pool size = 4, active threads = 3, queued tasks = 0, completed tasks = 25]
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[2021-11-20T16:57:46.022Z] 	at ServerPushWithDiffTypes.test(ServerPushWithDiffTypes.java:101)
[2021-11-20T16:57:46.022Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-20T16:57:46.022Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-20T16:57:46.022Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-20T16:57:46.022Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-11-20T16:57:46.022Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-11-20T16:57:46.022Z] 	at org.testng.TestRunner$$Lambda$79/0x00000000c81bf410.accept(Unknown Source)
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-11-20T16:57:46.022Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-11-20T16:57:46.022Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2021-11-20T16:57:46.022Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-11-20T16:57:46.022Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-11-20T16:57:46.022Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-11-20T16:57:46.022Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-11-20T16:57:46.022Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-11-20T16:57:46.022Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-11-20T16:57:46.022Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-11-20T16:57:46.022Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-11-20T16:57:46.022Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-11-20T16:57:46.022Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2021-11-20T16:57:46.022Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-20T16:57:46.022Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2021-11-20T16:57:46.022Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-20T16:57:46.022Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-20T16:57:46.022Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-20T16:57:46.022Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-20T16:57:46.022Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-20T16:57:46.022Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-20T16:57:46.022Z] Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$UniWhenComplete@e0c034a0 rejected from java.util.concurrent.ThreadPoolExecutor@2210844b[Shutting down, pool size = 4, active threads = 3, queued tasks = 0, completed tasks = 25]
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
[2021-11-20T16:57:46.022Z] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:854)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.Stream.lambda$incoming_pushPromise$3(Stream.java:638)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.Stream$$Lambda$296/0x00000000b80add00.accept(Unknown Source)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.Stream$PushedStream.lambda$completeResponse$6(Stream.java:1365)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.Stream$PushedStream$$Lambda$307/0x00000000b80afd38.accept(Unknown Source)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.ResponseSubscribers.lambda$getBodyAsync$2(ResponseSubscribers.java:1154)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.ResponseSubscribers$$Lambda$251/0x00000000b40a2f28.accept(Unknown Source)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:144)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.ResponseSubscribers.lambda$getBodyAsync$3(ResponseSubscribers.java:1150)
[2021-11-20T16:57:46.023Z] 	at java.net.http/jdk.internal.net.http.ResponseSubscribers$$Lambda$250/0x00000000b40a2d38.run(Unknown Source)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2021-11-20T16:57:46.023Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2021-11-20T16:57:46.023Z] 	... 1 more

[2021-11-20T16:57:46.153Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2021-11-20T16:57:46.153Z] --------------------------------------------------
[2021-11-20T17:30:47.586Z] Test results: passed: 802; failed: 1
[2021-11-20T17:30:47.586Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2021-11-20T17:30:47.586Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16374238157347/jdk_net_1/work
[2021-11-20T17:30:47.586Z] Error: Some tests failed or other problems occurred.
[2021-11-20T17:30:47.586Z] 
[2021-11-20T17:30:47.586Z] jdk_net_1_FAILED
```

**Comment by pshipton** [comment]
Is this a new test, regression, highly intermittent, or what?
