### ISSUE TITLE
JDK17 Head : javax/xml/crypto/dsig/LogParameters.java - RuntimeException: Unexpected log output: 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13981]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_ppc64_aix/30/` (`paix824 `):
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1+12 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1+12 (build master-0f828acf4, JRE 17 AIX ppc64-64-Bit Compressed References 20211120_38 (JIT enabled, AOT enabled)
OpenJ9   - 0f828acf4
OMR      - 83214375c
JCL      - df273956de9 based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security2_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F38%2Fibm-semeru-certified-testimage_ppc64_aix_JDK17U_2021-11-20-15-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F38%2Fibm-semeru-certified-debugimage_ppc64_aix_JDK17U_2021-11-20-15-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F38%2Fibm-semeru-certified-jdk_ppc64_aix_JDK17U_2021-11-20-15-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-11-21T02:27:34.548Z] Running test jdk_security2_0 ...
[2021-11-21T02:27:34.548Z] ===============================================
[2021-11-21T02:27:34.548Z] jdk_security2_0 Start Time: Sat Nov 20 21:45:00 2021 Epoch Time (ms): 1637466300575
[2021-11-21T02:27:34.548Z] "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-11-21T02:27:34.548Z] JVMSHRC005I No shared class caches available
[2021-11-21T02:27:34.548Z] JVMSHRC005I No shared class caches available
[2021-11-21T02:27:34.548Z] cache cleanup done
[2021-11-21T02:27:34.548Z] variation: Mode150
[2021-11-21T02:27:34.548Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-11-21T02:33:40.414Z] --------------------------------------------------
[2021-11-21T02:33:40.414Z] TEST: javax/xml/crypto/dsig/LogParameters.java

[2021-11-21T02:33:40.561Z] STDERR:
[2021-11-21T02:33:40.561Z] java.lang.RuntimeException: Unexpected log output: 
[2021-11-21T02:33:40.561Z] 	at LogParameters.main(LogParameters.java:55)
[2021-11-21T02:33:40.561Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-21T02:33:40.561Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-21T02:33:40.561Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-21T02:33:40.561Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-21T02:33:40.561Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-21T02:33:40.561Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-21T02:33:40.561Z] 
[2021-11-21T02:33:40.561Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2021-11-21T02:33:40.561Z] JavaTest Message: shutting down test
[2021-11-21T02:33:40.561Z] 
[2021-11-21T02:33:40.561Z] 
[2021-11-21T02:33:40.561Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected log output:
[2021-11-21T02:33:40.561Z] --------------------------------------------------
[2021-11-21T02:33:41.273Z] Test results: passed: 209; failed: 1
[2021-11-21T02:33:51.493Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/report/html/report.html
[2021-11-21T02:33:51.493Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_16374369179803/jdk_security2_0/work
[2021-11-21T02:33:51.493Z] Error: Some tests failed or other problems occurred.
[2021-11-21T02:33:51.493Z] 
[2021-11-21T02:33:51.493Z] jdk_security2_0_FAILED
```

**Comment by pshipton** [comment]
Is this a new test, regression, highly intermittent, or what?

**Comment by JasonFengJ9** [comment]
Observed at JDK17 `0.30.0-m1` `job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/29/`
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Open Edition 17.0.1.0-m1 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1.0-m1 (build openj9-0.30.0-m1a, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20211202_50 (JIT enabled, AOT enabled)
OpenJ9   - 8158af43b
OMR      - 8d10f065c
JCL      - 52863698c35 based on jdk-17.0.1+12)

[2021-12-03T05:39:55.676Z] variation: Mode650
[2021-12-03T05:39:55.676Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-12-03T05:45:47.253Z] --------------------------------------------------
[2021-12-03T05:45:47.253Z] TEST: javax/xml/crypto/dsig/LogParameters.java

[2021-12-03T05:45:47.256Z] STDERR:
[2021-12-03T05:45:47.256Z] java.lang.RuntimeException: Unexpected log output: 
[2021-12-03T05:45:47.256Z] 	at LogParameters.main(LogParameters.java:55)
[2021-12-03T05:45:47.256Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-12-03T05:45:47.256Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-12-03T05:45:47.256Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-03T05:45:47.256Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-12-03T05:45:47.256Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-12-03T05:45:47.256Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-12-03T05:45:47.256Z] 
[2021-12-03T05:45:47.256Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2021-12-03T05:45:47.256Z] JavaTest Message: shutting down test
[2021-12-03T05:45:47.256Z] 
[2021-12-03T05:45:47.256Z] 
[2021-12-03T05:45:47.256Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected log output:
[2021-12-03T05:45:47.256Z] --------------------------------------------------
[2021-12-03T05:47:34.130Z] Test results: passed: 208; failed: 1
[2021-12-03T05:48:05.539Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
[2021-12-03T05:48:05.539Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16384948645738\jdk_security2_1\work
[2021-12-03T05:48:05.539Z] Error: Some tests failed or other problems occurred.
[2021-12-03T05:48:05.539Z] 
[2021-12-03T05:48:05.539Z] jdk_security2_1_FAILED
```

**Comment by JasonFengJ9** [comment]
Observed at `job/Test_openjdk17_j9_extended.openjdk_x86-64_linux/38/`(`ub20x64rt3-7`)
```
java version "17.0.1" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1.0 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1.0 (build openj9-0.29.1, JRE 17 Linux amd64-64-Bit Compressed References 20211220_64 (JIT enabled, AOT enabled)
OpenJ9   - 7d055dfcb
OMR      - e30892e2b
JCL      - 233aee461cd based on jdk-17.0.1+12)

[2021-12-20T20:10:55.047Z] variation: Mode650
[2021-12-20T20:10:55.047Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-12-20T20:16:00.234Z] --------------------------------------------------
[2021-12-20T20:16:00.234Z] TEST: javax/xml/crypto/dsig/LogParameters.java

[2021-12-20T20:16:00.235Z] STDERR:
[2021-12-20T20:16:00.235Z] java.lang.RuntimeException: Unexpected log output: 
[2021-12-20T20:16:00.235Z] 	at LogParameters.main(LogParameters.java:55)
[2021-12-20T20:16:00.235Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-12-20T20:16:00.235Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-12-20T20:16:00.235Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-20T20:16:00.235Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-12-20T20:16:00.235Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-12-20T20:16:00.235Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-12-20T20:16:00.235Z] 
[2021-12-20T20:16:00.235Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2021-12-20T20:16:00.235Z] JavaTest Message: shutting down test
[2021-12-20T20:16:00.235Z] 
[2021-12-20T20:16:00.235Z] 
[2021-12-20T20:16:00.235Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected log output:
[2021-12-20T20:16:00.235Z] --------------------------------------------------
[2021-12-20T20:16:00.235Z] Test results: passed: 209; failed: 1
[2021-12-20T20:16:14.338Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2021-12-20T20:16:14.338Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16400175669790/jdk_security2_1/work
[2021-12-20T20:16:14.338Z] Error: Some tests failed or other problems occurred.
[2021-12-20T20:16:14.338Z] 
[2021-12-20T20:16:14.338Z] jdk_security2_1_FAILED
```

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk17_j9_extended.openjdk_ppc64_aix/58/`(`pll011`)
```
java version "17.0.3" 2022-04-19
IBM Semeru Runtime Certified Edition 17.0.3.0-rc1 (build 17.0.3+7)
Eclipse OpenJ9 VM 17.0.3.0-rc1 (build openj9-0.32.0-rc1, JRE 17 AIX ppc64-64-Bit Compressed References 20220420_129 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0e919023eb9 based on jdk-17.0.3+7)

[2022-04-21T10:58:58.421Z] java.lang.RuntimeException: Unexpected log output: 
[2022-04-21T10:58:58.421Z] 	at LogParameters.main(LogParameters.java:55)
[2022-04-21T10:58:58.421Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-04-21T10:58:58.421Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-04-21T10:58:58.421Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-04-21T10:58:58.421Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-04-21T10:58:58.421Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-04-21T10:58:58.421Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-04-21T10:58:58.421Z] 
[2022-04-21T10:58:58.421Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
```

**Comment by pshipton** [comment]
The problem seems to be the logger is getting gc'ed before the data is logged. The log level is set to ALL, and if the logger is gc'ed before this logger is used, then a new logger is created which doesn't have the log level set to ALL, and nothing is logged. The test can be fixed by keeping the original logger alive until after the data is logged.

**Comment by JasonFengJ9** [comment]
Seen on [JDK11 0.35 rc1 internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/82/)(`win16x64rt2-8`)
```
openjdk version "11.0.17" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0-rc1 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0-rc1 (build openj9-0.35.0-rc1, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20221020_478 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8)

[2022-10-20T05:51:11.981Z] variation: Mode650
[2022-10-20T05:51:12.422Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-10-20T05:56:33.711Z] TEST: javax/xml/crypto/dsig/LogParameters.java

[2022-10-20T05:56:33.713Z] STDERR:
[2022-10-20T05:56:33.713Z] java.lang.RuntimeException: Unexpected log output: 
[2022-10-20T05:56:33.713Z] 	at LogParameters.main(LogParameters.java:60)
[2022-10-20T05:56:33.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-10-20T05:56:33.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-10-20T05:56:33.713Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-10-20T05:56:33.713Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-10-20T05:56:33.713Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-10-20T05:56:33.713Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2022-10-20T05:56:33.713Z] 
[2022-10-20T05:56:33.713Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-10-20T05:56:33.713Z] JavaTest Message: shutting down test
[2022-10-20T05:56:33.713Z] 
[2022-10-20T05:56:33.713Z] 
[2022-10-20T05:56:33.713Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected log output:
[2022-10-20T05:56:33.713Z] --------------------------------------------------
[2022-10-20T05:58:00.305Z] Test results: passed: 209; failed: 1
[2022-10-20T05:58:31.285Z] Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16662370908054\jdk_security2_1\report\html\report.html
[2022-10-20T05:58:31.285Z] Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16662370908054\jdk_security2_1\work
[2022-10-20T05:58:31.285Z] Error: Some tests failed or other problems occurred.
[2022-10-20T05:58:31.285Z] 
[2022-10-20T05:58:31.285Z] jdk_security2_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_8/24/)
```
[2025-12-12T18:09:47.574Z] Running test jdk_security2_0 ...
[2025-12-12T18:09:47.574Z] ===============================================
[2025-12-12T18:09:49.405Z] jdk_security2_0 Start Time: Fri Dec 12 10:09:47 2025 Epoch Time (ms): 1765562987514
[2025-12-12T18:09:49.405Z] variation: Mode150
[2025-12-12T18:09:49.405Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-12-12T19:03:18.803Z] TEST: javax/xml/crypto/dsig/LogParameters.java

[2025-12-12T19:03:18.812Z] STDERR:
[2025-12-12T19:03:18.812Z] java.lang.RuntimeException: Unexpected log output: 12�� 12, 2025 11:03:06 ���� LogParameters main
[2025-12-12T19:03:18.812Z] ��ϸ: I have 10 apples.
[2025-12-12T19:03:18.812Z] 
[2025-12-12T19:03:18.812Z] 	at LogParameters.main(LogParameters.java:65)
```
