### ISSUE TITLE
[JDK18] Unsupported tests in TestAsyncStackWalk and TestStackWalk

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#13993]
### OpenJDK Tests

The following JDK18 tests are not supported by OpenJ9 because OpenJ9 does support the `sun.hotspot.WhiteBox` dependency:
```
TEST: java/foreign/stackwalk/TestAsyncStackWalk.java#default_gc
TEST: java/foreign/stackwalk/TestAsyncStackWalk.java#shenandoah
TEST: java/foreign/stackwalk/TestAsyncStackWalk.java#zgc
TEST: java/foreign/stackwalk/TestStackWalk.java#default_gc
TEST: java/foreign/stackwalk/TestStackWalk.java#shenandoah
TEST: java/foreign/stackwalk/TestStackWalk.java#zgc
```

The above tests will be excluded.

### Error

```
[2021-11-17T19:28:49.428Z] java.lang.UnsatisfiedLinkError: sun/hotspot/WhiteBox.registerNatives()V
[2021-11-17T19:28:49.428Z]      at sun.hotspot.WhiteBox.<clinit>(WhiteBox.java:68)
[2021-11-17T19:28:49.428Z]      at TestAsyncStackWalk.<clinit>(TestAsyncStackWalk.java:123)
[2021-11-17T19:28:49.428Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T19:28:49.428Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T19:28:49.428Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T19:28:49.428Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T19:28:49.428Z]      at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-17T19:28:49.428Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: https://github.com/eclipse-openj9/openj9/issues/13946

**Comment by babsingh** [comment]
Closing this issue ... OpenJ9 does not support `sun/hotspot/WhiteBox`. So, the above tests should be permanently excluded since they cannot be run with OpenJ9. These tests were excluded by https://github.com/adoptium/aqa-tests/pull/3150.

fyi @pshipton

**Comment by babsingh** [comment]
@pshipton Should the `test excluded` label be retained since the tests are permanently excluded?

**Comment by pshipton** [comment]
No, a closed issue with a `test excluded` label means the problem is resolved and the test can be re-included. I'll create a `perm excluded` label and use it here.

**Comment by pshipton** [comment]
> No, a closed issue with a test excluded label means the problem is resolved and the test can be re-included.

There was talk about automated that at some point.
