### ISSUE TITLE
java/nio/channels/FileChannel/TempDirectBuffersReclamation.java - AssertionError: Direct BufferPool not same before thread activity and after thread exit.

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14008]
Failure link
------------

From an internal build `job/Test_openjdk8_j9_extended.openjdk_aarch64_linux/31/` (`ub18-aarch64-6`):
```
openjdk version "1.8.0_322"
IBM Semeru Runtime Open Edition (build 1.8.0_322-b03)
Eclipse OpenJ9 VM (build master-0f828acf4, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20211120_232 (JIT enabled, AOT enabled)
OpenJ9   - 0f828acf4
OMR      - 83214375c
JCL      - 3fcd9886 based on jdk8u322-b03)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F232%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2021-11-20-03-32.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F232%2Fibm-semeru-open-jre_aarch64_linux_JDK8U_2021-11-20-03-32.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F232%2Fibm-semeru-open-testimage_aarch64_linux_JDK8U_2021-11-20-03-32.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F232%2Fibm-semeru-open-debugimage_aarch64_linux_JDK8U_2021-11-20-03-32.tar.gz&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:34:08  variation: Mode150
23:34:08  JVM_OPTIONS:  -XX:+UseCompressedOops 

23:35:56  --------------------------------------------------
23:35:56  TEST: java/nio/channels/FileChannel/TempDirectBuffersReclamation.java

23:35:56  java.lang.AssertionError: Direct BufferPool not same before thread activity and after thread exit.
23:35:56  Before: # of buffers: 6, memory used: 48
23:35:56   After: # of buffers: 7, memory used: 53
23:35:56  
23:35:56  	at TempDirectBuffersReclamation.main(TempDirectBuffersReclamation.java:71)
23:35:56  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:35:56  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:35:56  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:35:56  	at java.lang.reflect.Method.invoke(Method.java:498)
23:35:56  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:35:56  	at java.lang.Thread.run(Thread.java:826)
23:35:56  
23:35:56  JavaTest Message: Test threw exception: java.lang.AssertionError: Direct BufferPool not same before thread activity and after thread exit.
23:35:56  Before: # of buffers: 6, memory used: 48
23:35:56   After: # of buffers: 7, memory used: 53

23:35:56  --------------------------------------------------
23:39:35  Test results: passed: 327; failed: 1
23:39:35  Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
23:39:35  Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16373813627762/jdk_nio_0/work
23:39:35  Error: Some tests failed or other problems occurred.
23:39:35  
23:39:35  jdk_nio_0_FAILED
```

From test history at `job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/`, this appears a regression between 
Passed at `job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/31/consoleFull`
```
01:07:08  IBM Semeru Runtime Open Edition (build 1.8.0_312-b07)
01:07:08  Eclipse OpenJ9 VM (build master-239de6af1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20211111_248 (JIT enabled, AOT enabled)
01:07:08  OpenJ9   - 239de6af1
01:07:08  OMR      - 3e22bee4a
01:07:08  JCL      - 9ba2987b based on jdk8u312-b07)
```
Failed at `job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/32/consoleFull`
```
23:25:21  openjdk version "1.8.0_322"
23:25:21  IBM Semeru Runtime Open Edition (build 1.8.0_322-b01)
23:25:21  Eclipse OpenJ9 VM (build master-d13611eb2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20211113_250 (JIT enabled, AOT enabled)
23:25:21  OpenJ9   - d13611eb2
23:25:21  OMR      - b95fd53e2
23:25:21  JCL      - 7fa1c036 based on jdk8u322-b01)
```
OpenJ9 diff - https://github.com/eclipse-openj9/openj9/compare/239de6af1...d13611eb2
OMR diff - https://github.com/eclipse-openj9/openj9-omr/compare/3e22bee4a...b95fd53e2
JCL diff - https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/9ba2987b...7fa1c036
This requires triage.

**Comment by JasonFengJ9** [comment]
RI failed this test at `jdk8u312-b07`
```
openjdk version "1.8.0_312-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-beta-202111101816-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
```
`jdk8u322-b01` passed.
```
openjdk version "1.8.0_322-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-beta-202111121811-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b01, mixed mode)
```

Need further triage to identify what was the fix and why `OpenJ9` didn't get it.
