### ISSUE TITLE
java/net/MulticastSocket/JoinLeave.java - UncheckedIOException: java.net.SocketException: The socket name is not available on this system. (Error setting socket option)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14009]
Failure link
------------

From an internal build `job/Test_openjdk8_j9_extended.openjdk_ppc64_aix/35/` (`paix905 `):
```
openjdk version "1.8.0_322"
IBM Semeru Runtime Open Edition (build 1.8.0_322-b03)
Eclipse OpenJ9 VM (build master-0f828acf4, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20211119_243 (JIT enabled, AOT enabled)
OpenJ9   - 0f828acf4
OMR      - 83214375c
JCL      - 3fcd9886 based on jdk8u322-b03)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_net_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F243%2Fibm-semeru-open-testimage_ppc64_aix_JDK8U_2021-11-20-03-32.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F243%2Fibm-semeru-open-jdk_ppc64_aix_JDK8U_2021-11-20-03-32.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F243%2Fibm-semeru-open-debugimage_ppc64_aix_JDK8U_2021-11-20-03-32.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F243%2Fibm-semeru-open-jre_ppc64_aix_JDK8U_2021-11-20-03-32.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-11-20T06:58:31.458Z] variation: Mode650
[2021-11-20T06:58:31.458Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-11-20T07:07:19.680Z] --------------------------------------------------
[2021-11-20T07:07:19.680Z] TEST: java/net/MulticastSocket/JoinLeave.java

[2021-11-20T07:07:19.683Z] STDERR:
[2021-11-20T07:07:19.683Z] java.io.UncheckedIOException: java.net.SocketException: The socket name is not available on this system. (Error setting socket option)
[2021-11-20T07:07:19.683Z] 	at JoinLeave.joinLeave(JoinLeave.java:59)
[2021-11-20T07:07:19.683Z] 	at JoinLeave.lambda$main$0(JoinLeave.java:47)
[2021-11-20T07:07:19.683Z] 	at JoinLeave$$Lambda$39/0x0000000000000000.accept(Unknown Source)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[2021-11-20T07:07:19.683Z] 	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
[2021-11-20T07:07:19.683Z] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[2021-11-20T07:07:19.683Z] 	at JoinLeave.main(JoinLeave.java:47)
[2021-11-20T07:07:19.683Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-20T07:07:19.683Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-20T07:07:19.683Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-20T07:07:19.683Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-11-20T07:07:19.683Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-11-20T07:07:19.683Z] 	at java.lang.Thread.run(Thread.java:826)
[2021-11-20T07:07:19.683Z] Caused by: java.net.SocketException: The socket name is not available on this system. (Error setting socket option)
[2021-11-20T07:07:19.683Z] 	at java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:74)
[2021-11-20T07:07:19.683Z] 	at java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:309)
[2021-11-20T07:07:19.683Z] 	at java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:554)
[2021-11-20T07:07:19.683Z] 	at JoinLeave.joinLeave(JoinLeave.java:55)
[2021-11-20T07:07:19.683Z] 	... 20 more
[2021-11-20T07:07:19.683Z] 
[2021-11-20T07:07:19.683Z] JavaTest Message: Test threw exception: java.io.UncheckedIOException
[2021-11-20T07:07:19.683Z] JavaTest Message: shutting down test
[2021-11-20T07:07:19.683Z] 
[2021-11-20T07:07:19.683Z] STDOUT:
[2021-11-20T07:07:19.683Z] Joining:/224.80.80.80 on name:en0 (en0)
[2021-11-20T07:07:19.683Z] 
[2021-11-20T07:07:19.683Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.io.UncheckedIOException: java.net.SocketException: The socket name is not available on this system. (Error setting socket option)
[2021-11-20T07:07:19.683Z] --------------------------------------------------
[2021-11-20T07:20:12.900Z] Test results: passed: 447; failed: 1
[2021-11-20T07:20:16.085Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/report/html/report.html
[2021-11-20T07:20:16.085Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_16373884824288/jdk_net_1/work
[2021-11-20T07:20:16.085Z] Error: Some tests failed or other problems occurred.
[2021-11-20T07:20:16.085Z] 
[2021-11-20T07:20:16.085Z] jdk_net_1_FAILED
```

This appears a machine/setup issue.

**Comment by pshipton** [comment]
If it's an internal machine issue then it needs to be reported internally to get it fixed.

**Comment by JasonFengJ9** [comment]
`SocketException: The socket name is not available on this system. (Error setting socket option)` can be caused by wrong name resolution (DNS) pointing to another IP address different to the 127.0.0.1 for localhost.
Track the issue at `runtimes/infrastructure/issues/6252`.
