### ISSUE TITLE
[JDK18] IllegalArgumentException in ProgrammableInvoker.checkIfValidLayoutAndType

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14000]
### Tests

```
TEST: java/foreign/TestDowncall.java
```

### Error

```
test TestDowncall.testDowncall(153, "f0_V_IS_DDI", VOID, [INT, STRUCT], [DOUBLE, DOUBLE, INT]): failure
[2021-11-17T19:28:08.387Z] java.lang.IllegalArgumentException: The passed-in argument type at index 0 is neither primitive nor MemoryAddress
[2021-11-17T19:28:08.387Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.checkIfValidLayoutAndType(ProgrammableInvoker.java:423)
[2021-11-17T19:28:08.387Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<init>(ProgrammableInvoker.java:229)
[2021-11-17T19:28:08.387Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:294)
[2021-11-17T19:28:08.388Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.CallArranger.arrangeDowncall(CallArranger.java:136)
[2021-11-17T19:28:08.388Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.linux.LinuxAArch64Linker.downcallHandle(LinuxAArch64Linker.java:80)
[2021-11-17T19:28:08.388Z]      at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:50)
[2021-11-17T19:28:08.388Z]      at TestDowncall.doCall(TestDowncall.java:113)
[2021-11-17T19:28:08.388Z]      at TestDowncall.testDowncall(TestDowncall.java:71)

test TestDowncall.testDowncallNoScope(11900, "f19_S_SSD_DIP", NON_VOID, [STRUCT, STRUCT, DOUBLE], [DOUBLE, INT, POINTER]): failure
[2021-11-17T19:28:08.392Z] java.lang.IllegalArgumentException: The return type must be primitive/void or MemoryAddress: retType = interface jdk.incubator.foreign.MemorySegment
[2021-11-17T19:28:08.392Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.checkIfValidLayoutAndType(ProgrammableInvoker.java:403)
[2021-11-17T19:28:08.392Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<init>(ProgrammableInvoker.java:229)
[2021-11-17T19:28:08.392Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:294)
[2021-11-17T19:28:08.392Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.CallArranger.arrangeDowncall(CallArranger.java:136)
[2021-11-17T19:28:08.392Z]      at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.linux.LinuxAArch64Linker.downcallHandle(LinuxAArch64Linker.java:80)
[2021-11-17T19:28:08.392Z]      at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:50)
[2021-11-17T19:28:08.392Z]      at TestDowncall.doCall(TestDowncall.java:113)
[2021-11-17T19:28:08.392Z]      at TestDowncall.testDowncallNoScope(TestDowncall.java:97)
```

Related: https://github.com/eclipse-openj9/openj9/issues/13946

**Comment by ChengJin01** [comment]
@babsingh,  You don't have to created the FFI related issues related to downcall (already created at https://github.com/eclipse-openj9/openj9/issues/13994)  as these failures were addressed in code at https://github.com/eclipse-openj9/openj9/pull/13315 and associated with https://github.com/eclipse-openj9/openj9/issues/13994 in https://github.com/adoptium/aqa-tests/pull/3150.
