### ISSUE TITLE
[JDK18] AssertionError in TestIllegalLink.testTypeMismatch

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14002]
### OpenJDK Test

```
TEST: java/foreign/TestIllegalLink.java
```

### Error
```
[2021-11-17T19:30:22.991Z] test TestIllegalLink.testTypeMismatch(()void, (b32[abi/kind=INT])v, "Arity mismatch"): failure
[2021-11-17T19:30:22.991Z] java.lang.AssertionError: expected [true] but found [false]
[2021-11-17T19:30:22.991Z]      at org.testng.Assert.fail(Assert.java:99)
[2021-11-17T19:30:22.991Z]      at org.testng.Assert.failNotEquals(Assert.java:1037)
[2021-11-17T19:30:22.991Z]      at org.testng.Assert.assertTrue(Assert.java:45)
[2021-11-17T19:30:22.991Z]      at org.testng.Assert.assertTrue(Assert.java:55)
[2021-11-17T19:30:22.991Z]      at TestIllegalLink.testTypeMismatch(TestIllegalLink.java:57)
```
Multiple failures with different type mismatches.

Related: https://github.com/eclipse-openj9/openj9/issues/13946

**Comment by ChengJin01** [comment]
We don't need to this test suite as the error messages specific to Hotspot and we already have the expected exception addressed in our code.
