### ISSUE TITLE
JDK17 head jdk_net_0_FAILED - RuntimeException: expected: class java.lang.IllegalArgumentException, actual: java.lang.RuntimeException: Exception not thrown & a few other errors

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14030]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/29/` (`rhel7lert-11`):
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1+12 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1+12 (build master-ea06f7479, JRE 17 Linux ppc64le-64-Bit Compressed References 20211127_44 (JIT enabled, AOT enabled)
OpenJ9   - ea06f7479
OMR      - eb9cf8525
JCL      - a60fb4eda99 based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_net_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F44%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK17U_2021-11-27-15-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F44%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK17U_2021-11-27-15-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F44%2Fibm-semeru-certified-debugimage_ppc64le_linux_JDK17U_2021-11-27-15-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=3&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-11-27T17:58:58.077Z] variation: Mode150
[2021-11-27T17:58:58.077Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-11-27T18:05:19.413Z] --------------------------------------------------
[2021-11-27T18:05:19.413Z] TEST: java/net/DatagramSocket/DatagramSocketMulticasting.java

[2021-11-27T18:05:19.415Z] STDERR:
[2021-11-27T18:05:19.415Z] java.lang.RuntimeException: expected: class java.lang.IllegalArgumentException, actual: java.lang.RuntimeException: Exception not thrown
[2021-11-27T18:05:19.415Z] 	at DatagramSocketMulticasting.assertThrows(DatagramSocketMulticasting.java:375)
[2021-11-27T18:05:19.415Z] 	at DatagramSocketMulticasting.testJoinGroup2(DatagramSocketMulticasting.java:211)
[2021-11-27T18:05:19.415Z] 	at DatagramSocketMulticasting.test(DatagramSocketMulticasting.java:100)
[2021-11-27T18:05:19.415Z] 	at DatagramSocketMulticasting.main(DatagramSocketMulticasting.java:80)
[2021-11-27T18:05:19.415Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-27T18:05:19.415Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-27T18:05:19.415Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-27T18:05:19.415Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-27T18:05:19.415Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-27T18:05:19.415Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-27T18:05:19.415Z] 
[2021-11-27T18:05:19.415Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: expected: class java.lang.IllegalArgumentException, actual: java.lang.RuntimeException: Exception not thrown

[2021-11-27T18:05:19.416Z] --------------------------------------------------
[2021-11-27T18:43:20.446Z] TEST: java/net/Inet6Address/PreferIPv6AddressesTest.java

[2021-11-27T18:43:20.464Z] STDERR:
[2021-11-27T18:43:20.464Z] java.lang.RuntimeException: Expected class java.net.Inet6Address, got class java.net.Inet4Address
[2021-11-27T18:43:20.464Z] 	at PreferIPv6AddressesTest.assertLoopbackAddress(PreferIPv6AddressesTest.java:115)
[2021-11-27T18:43:20.464Z] 	at PreferIPv6AddressesTest.main(PreferIPv6AddressesTest.java:77)
[2021-11-27T18:43:20.464Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-27T18:43:20.464Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-27T18:43:20.464Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-27T18:43:20.464Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-27T18:43:20.464Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-27T18:43:20.464Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-27T18:43:20.464Z] 
[2021-11-27T18:43:20.464Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected class java.net.Inet6Address, got class java.net.Inet4Address

[2021-11-27T18:43:20.661Z] --------------------------------------------------
[2021-11-27T18:58:40.543Z] TEST: java/net/Inet6Address/B6558853.java

[2021-11-27T18:58:40.642Z] TEST RESULT: Error. Agent error: java.lang.Exception: Agent 15 timed out with a timeout of 960 seconds; check console log for any additional details

[2021-11-27T18:59:23.925Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 961574ms).


[2021-11-27T18:59:23.925Z] --------------------------------------------------
[2021-11-27T18:59:46.309Z] TEST: java/net/ipv6tests/TcpTest.java
[2021-11-27T18:58:40.642Z] --------------------------------------------------
[2021-11-27T18:59:23.920Z] TEST: java/net/Inet6Address/Scoping.java

[2021-11-27T18:59:46.311Z] STDERR:
[2021-11-27T18:59:46.313Z] java.net.SocketException: Network is unreachable
[2021-11-27T18:59:46.313Z] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-11-27T18:59:46.313Z] 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
[2021-11-27T18:59:46.313Z] 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
[2021-11-27T18:59:46.313Z] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-11-27T18:59:46.313Z] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[2021-11-27T18:59:46.313Z] 	at java.base/java.net.Socket.connect(Socket.java:633)
[2021-11-27T18:59:46.313Z] 	at java.base/java.net.Socket.connect(Socket.java:583)
[2021-11-27T18:59:46.313Z] 	at java.base/java.net.Socket.<init>(Socket.java:507)
[2021-11-27T18:59:46.313Z] 	at java.base/java.net.Socket.<init>(Socket.java:287)
[2021-11-27T18:59:46.313Z] 	at TcpTest.test1(TcpTest.java:87)
[2021-11-27T18:59:46.313Z] 	at TcpTest.main(TcpTest.java:75)
[2021-11-27T18:59:46.313Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-27T18:59:46.313Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-27T18:59:46.313Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-27T18:59:46.313Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-27T18:59:46.313Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-27T18:59:46.313Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-27T18:59:46.314Z] 
[2021-11-27T18:59:46.314Z] JavaTest Message: Test threw exception: java.net.SocketException

[2021-11-27T18:59:46.314Z] --------------------------------------------------
[2021-11-27T19:00:52.300Z] TEST: java/net/InetAddress/CheckJNI.java

[2021-11-27T19:00:52.328Z] STDERR:
[2021-11-27T19:00:52.328Z] JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
[2021-11-27T19:00:52.328Z] java.net.ConnectException: Connection timed out
[2021-11-27T19:00:52.328Z] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-11-27T19:00:52.328Z] 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
[2021-11-27T19:00:52.328Z] 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
[2021-11-27T19:00:52.328Z] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-11-27T19:00:52.328Z] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[2021-11-27T19:00:52.328Z] 	at java.base/java.net.Socket.connect(Socket.java:633)
[2021-11-27T19:00:52.328Z] 	at java.base/java.net.Socket.connect(Socket.java:583)
[2021-11-27T19:00:52.328Z] 	at java.base/java.net.Socket.<init>(Socket.java:507)
[2021-11-27T19:00:52.328Z] 	at java.base/java.net.Socket.<init>(Socket.java:319)
[2021-11-27T19:00:52.328Z] 	at CheckJNI.testSocket(CheckJNI.java:78)
[2021-11-27T19:00:52.328Z] 	at CheckJNI.main(CheckJNI.java:68)
[2021-11-27T19:00:52.328Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-27T19:00:52.328Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-27T19:00:52.328Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-27T19:00:52.328Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-27T19:00:52.328Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-27T19:00:52.328Z] 	at java.base/java.lang.Thread.run(Thread.java:884)

[2021-11-27T19:00:52.341Z] --------------------------------------------------
[2021-11-27T19:08:41.049Z] TEST: java/net/Socket/LinkLocal.java

[2021-11-27T19:08:41.149Z] STDERR:
[2021-11-27T19:08:41.149Z] java.net.SocketTimeoutException: Receive timed out
[2021-11-27T19:08:41.149Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:703)
[2021-11-27T19:08:41.149Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:633)
[2021-11-27T19:08:41.149Z] 	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
[2021-11-27T19:08:41.149Z] 	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:700)
[2021-11-27T19:08:41.149Z] 	at LinkLocal.UdpTest(LinkLocal.java:108)
[2021-11-27T19:08:41.149Z] 	at LinkLocal.TestAddress(LinkLocal.java:121)
[2021-11-27T19:08:41.149Z] 	at LinkLocal.main(LinkLocal.java:156)
[2021-11-27T19:08:41.149Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-27T19:08:41.149Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-11-27T19:08:41.150Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-27T19:08:41.150Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-11-27T19:08:41.150Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-27T19:08:41.150Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-27T19:08:41.150Z] 
[2021-11-27T19:08:41.150Z] JavaTest Message: Test threw exception: java.net.SocketTimeoutException

[2021-11-27T19:08:41.150Z] --------------------------------------------------
[2021-11-27T19:15:56.847Z] TEST: java/net/ipv6tests/UdpTest.java

[2021-11-27T19:15:56.874Z] TEST RESULT: Error. Agent error: java.lang.Exception: Agent 18 timed out with a timeout of 960 seconds; check console log for any additional details
[2021-11-27T19:15:56.874Z] --------------------------------------------------
[2021-11-27T19:20:24.620Z] Test results: passed: 795; failed: 5; error: 3
[2021-11-27T19:20:35.045Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/jvmtest/openjdk/report/html/report.html
[2021-11-27T19:20:35.045Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16380344352847/jdk_net_0/work
[2021-11-27T19:20:35.045Z] Error: Some tests failed or other problems occurred.
[2021-11-27T19:20:35.045Z] 
[2021-11-27T19:20:35.045Z] jdk_net_0_FAILED
```

This could be a machine/network issue.

**Comment by JasonFengJ9** [comment]
[JDK17 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_linux_fips140_2_testList_1/2/)(`cent9x86-rtp-rt4-1`)
```
[2023-10-06T21:31:39.254Z] variation: Mode150
[2023-10-06T21:31:39.254Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-10-06T21:40:09.422Z] TEST: java/nio/channels/etc/ProtocolFamilies.java

[2023-10-06T21:40:09.423Z] test ProtocolFamilies.dcOpenBind(null, INET6, java.lang.Class@2a1dd189): failure
[2023-10-06T21:40:09.423Z] java.lang.AssertionError: Expected UnsupportedAddressTypeException to be thrown, but nothing was thrown
[2023-10-06T21:40:09.423Z] 	at org.testng.Assert.expectThrows(Assert.java:1730)
[2023-10-06T21:40:09.423Z] 	at org.testng.Assert.assertThrows(Assert.java:1695)
[2023-10-06T21:40:09.423Z] 	at ProtocolFamilies.dcOpenBind(ProtocolFamilies.java:227)
[2023-10-06T21:40:09.423Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-06T21:40:09.423Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-10-06T21:40:09.423Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-06T21:40:09.423Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2023-10-06T21:40:09.423Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2023-10-06T21:40:09.423Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2023-10-06T21:40:09.423Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2023-10-06T21:40:09.423Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2023-10-06T21:40:09.423Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2023-10-06T21:40:09.423Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2023-10-06T21:40:09.423Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2023-10-06T21:40:09.423Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2023-10-06T21:40:09.423Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2023-10-06T21:40:09.423Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2023-10-06T21:40:09.423Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2023-10-06T21:40:09.423Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2023-10-06T21:40:09.423Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2023-10-06T21:40:09.423Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2023-10-06T21:40:09.423Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2023-10-06T21:40:09.423Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-06T21:40:09.423Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-10-06T21:40:09.423Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-06T21:40:09.423Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-10-06T21:40:09.423Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-10-06T21:40:09.423Z] 	at java.base/java.lang.Thread.run(Thread.java:857)

[2023-10-06T21:40:09.424Z] java/nio/channels/etc/ProtocolFamilies.java
[2023-10-06T21:40:09.424Z] Total tests run: 30, Passes: 25, Failures: 5, Skips: 0

[2023-10-06T22:11:51.808Z] jdk_nio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK17 x86-64_linux jdk_nio_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_linux/181/)(`cent9x86-rtp-rt5-1`)
