### ISSUE TITLE
ConcurrentHashMap/ToArray IncompatibleClassChangeError java.util.stream.IntPipeline$4$1.accept

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14058]
Looks similar to https://github.com/eclipse-openj9/openj9/issues/13478

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly/163
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/concurrent/ConcurrentHashMap/ToArray.java
```
00:09:45  rerun:
00:09:45  cd 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16384209802296\jdk_util_0\work\scratch\1' && \
00:09:45  PATH='C:\cygwin64\bin;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\apache-ant\apache-ant-1.10.3\bin;C:\Program Files\Java\jdk8u202-b08\bin;C:\Strawberry\perl\bin;C:\Program Files\Microsoft Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\OpenSSL-1.1.1-x86_32\bin;C:\OpenSSL-1.1.1-x86_64\bin;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0' \
00:09:45  SystemDrive=C: \
00:09:45  SystemRoot='C:\Windows' \
00:09:45  TEMP='C:\temp' \
00:09:45  windir='C:\Windows' \
00:09:45      'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java' \
00:09:45          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
00:09:45          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
00:09:45          -Dtest.compiler.opts= \
00:09:45          -Dtest.java.opts= \
00:09:45          -Dtest.jdk='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
00:09:45          -Dcompile.jdk='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
00:09:45          -Dtest.timeout.factor=8.0 \
00:09:45          -Dtest.root='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test' \
00:09:45          -Dtest.name=java/util/concurrent/ConcurrentHashMap/ToArray.java \
00:09:45          -Dtest.file='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap\ToArray.java' \
00:09:45          -Dtest.src='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap' \
00:09:45          -Dtest.src.path='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap' \
00:09:45          -Dtest.classes='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16384209802296\jdk_util_0\work\classes\2\java\util\concurrent\ConcurrentHashMap' \
00:09:45          -Dtest.class.path='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16384209802296\jdk_util_0\work\classes\2\java\util\concurrent\ConcurrentHashMap' \
00:09:45          -Dtest.class.path.prefix='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16384209802296\jdk_util_0\work\classes\2\java\util\concurrent\ConcurrentHashMap;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap' \
00:09:45          -classpath 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16384209802296\jdk_util_0\work\classes\2\java\util\concurrent\ConcurrentHashMap;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\lib\tools.jar;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\javatest.jar;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\jtreg.jar' \
00:09:45          ToArray
00:09:45  STDERR:
00:09:45  java.lang.IncompatibleClassChangeError
00:09:45  	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:257)
00:09:45  	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:117)
00:09:45  	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
00:09:45  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
00:09:45  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
00:09:45  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:561)
00:09:45  	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:267)
00:09:45  	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
00:09:45  	at ToArray.executeTest(ToArray.java:96)
00:09:45  	at ToArray.main(ToArray.java:41)
00:09:45  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:09:45  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:09:45  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:09:45  	at java.lang.reflect.Method.invoke(Method.java:498)
00:09:45  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:09:45  	at java.lang.Thread.run(Thread.java:826)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_OMR_testList_2/28
jdk_util_0
java/util/concurrent/ConcurrentHashMap/ToArray.java
```
10:37:08  java.lang.IncompatibleClassChangeError
10:37:08  	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:185)
10:37:08  	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:109)
10:37:08  	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
10:37:08  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
10:37:08  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
10:37:08  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
10:37:08  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
10:37:08  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
10:37:08  	at ToArray.executeTest(ToArray.java:95)
10:37:08  	at ToArray.main(ToArray.java:44)
```
