### ISSUE TITLE
z/OS Java 8 FileChannelLockingTest NullPointerException java.util.jar.Manifest$FastInputStream.fill

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14053]
Maybe just some file system or network hiccup, but recording it.

/job_output.php?id=21626898
[zOS S390 64bit] 80 Load_Level_2.harmony.5mins.Mode112.5
fyrec203
```
j> 10:36:25 20211201 10:36:25 Result Summary ERROR: Primary|SimpleDriver|org.apache.harmony.nio.tests.java.nio.channels.FileChannelLockingTest|263908|Default Invocant reported failed with message: java.lang.NullPointerException
j> 10:36:25 	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:497)
j> 10:36:25 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:431)
j> 10:36:25 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:465)
j> 10:36:25 	at java.util.jar.Attributes.read(Attributes.java:387)
j> 10:36:25 	at java.util.jar.Manifest.read(Manifest.java:246)
j> 10:36:25 	at java.util.jar.Manifest.<init>(Manifest.java:93)
j> 10:36:25 	at java.util.jar.Manifest.<init>(Manifest.java:85)
j> 10:36:25 	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:221)
j> 10:36:25 	at java.util.jar.JarFile.getManifest(JarFile.java:193)
j> 10:36:25 	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:1122)
j> 10:36:25 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:689)
j> 10:36:25 	at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
j> 10:36:25 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1187)
j> 10:36:25 	at java.security.AccessController.doPrivileged(AccessController.java:774)
j> 10:36:25 	at java.net.URLClassLoader.findClass(URLClassLoader.java:605)
j> 10:36:25 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:945)
j> 10:36:25 	at java.lang.ClassLoader.loadClass(ClassLoader.java:890)
j> 10:36:25 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
j> 10:36:25 	at java.lang.ClassLoader.loadClass(ClassLoader.java:873)
j> 10:36:25 	at junit.framework.TestResult.addError(TestResult.java:36)
j> 10:36:25 	at junit.framework.TestResult.runProtected(TestResult.java:137)
j> 10:36:25 	at junit.framework.TestResult.run(TestResult.java:113)
j> 10:36:25 	at junit.framework.TestCase.run(TestCase.java:124)
j> 10:36:25 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
j> 10:36:25 	at junit.framework.TestSuite.run(TestSuite.java:238)
```

60x grinder - passed

**Comment by JasonFengJ9** [comment]
[[zOS S390 64bit] 80 Load_Level_2.harmony.5mins.Mode187.5](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=69183518)(`fyrec803`)
```
/j9vm/ebcdic/javatest/HEAD_382595/test/tools/gmake/zos_390-64/make -f "/j9vm/ebcdic/javatest/HEAD_382595/test/SVT/stress/makefile" SITE=ottawa STREAM=default PLATFORM=zos_390-64 JAVA_LANG_LEVEL=80 JVM_VERSION=29 JAVA_VERSION=80 BUILD_ID=58560 JOB_ID=69183518 PLAYLIST_ROOT='/j9vm/ebcdic/javatest/HEAD_382595/test/playlists' JVM_TEST_ROOT='/j9vm/ebcdic/builds/bld_58560/jvmtest' MODULARITY_TEST= JAVASVT_ROOT=/j9vm/ebcdic/javatest/HEAD_382595/javasvt JAVASVT_PREREQS_ROOT=/j9vm/ebcdic/javatest/HEAD_382595/javasvt_prereqs VARIATION=Mode187 _harmony.5mins

j> 03:30:31 20230922 03:30:31 PooledRunnable-Thread 583 ERROR: Pooled thread 'Pooled Thread #583 running org.apache.harmony.nio.tests.java.nio.channels.FileChannelLockingTest' terminated with unexpected exception
j> 03:30:31 Throwable trace:
j> 03:30:31 java.lang.NullPointerException
j> 03:30:31 	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:497)
j> 03:30:31 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:431)
j> 03:30:31 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:465)
j> 03:30:31 	at java.util.jar.Attributes.read(Attributes.java:388)
j> 03:30:31 	at java.util.jar.Manifest.read(Manifest.java:246)
j> 03:30:31 	at java.util.jar.Manifest.<init>(Manifest.java:93)
j> 03:30:31 	at java.util.jar.Manifest.<init>(Manifest.java:85)
j> 03:30:31 	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:222)
j> 03:30:31 	at java.util.jar.JarFile.getManifest(JarFile.java:194)
j> 03:30:31 	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:1122)
j> 03:30:31 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:689)
j> 03:30:31 	at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
j> 03:30:31 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1187)
j> 03:30:31 	at java.security.AccessController.doPrivileged(AccessController.java:782)
j> 03:30:31 	at java.net.URLClassLoader.findClass(URLClassLoader.java:605)
j> 03:30:31 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:948)
j> 03:30:31 	at java.lang.ClassLoader.loadClass(ClassLoader.java:893)
j> 03:30:31 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:353)
j> 03:30:31 	at java.lang.ClassLoader.loadClass(ClassLoader.java:876)
j> 03:30:31 	at com.ibm.jtc.test.jltf.threads.WorkUnitRunner.run(WorkUnitRunner.java:119)
j> 03:30:31 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.runWork(PooledRunnable.java:170)
j> 03:30:31 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:136)
j> 03:30:31 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 03:30:31 	at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
```
[100x grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=58564) - passed
