### ISSUE TITLE
DaaLoadTest_daa3_special_5m_16_FAILED : JUnit[net.openj9.test.arithmetics.TestArithmeticOperations] IllegalAccessError: invokeinterface of non-public method 'hasNext()Z' in java/util/ArrayList$Itr

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14065]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_special.system_ppc64_aix_testList_2/96/`(`paix821 `):
```
openjdk version "17.0.1-beta" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1+12-202112020514 (build 17.0.1-beta+12-202112020514)
Eclipse OpenJ9 VM 17.0.1+12-202112020514 (build master-8b18a989f, JRE 17 AIX ppc64-64-Bit Compressed References 20211202_46 (JIT enabled, AOT enabled)
OpenJ9   - 8b18a989f
OMR      - 8d10f065c
JCL      - a60fb4eda99 based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=DaaLoadTest_daa3_special_5m_16&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_special.system_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F46%2Fibm-semeru-certified-debugimage_ppc64_aix_JDK17U_2021-12-02-05-06.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F46%2Fibm-semeru-certified-jdk_ppc64_aix_JDK17U_2021-12-02-05-06.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F46%2Fibm-semeru-certified-testimage_ppc64_aix_JDK17U_2021-12-02-05-06.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=106&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-12-02T11:01:35.033Z] variation: Mode555
[2021-12-02T11:01:35.033Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:counts=- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000,gcOnResolve,rtResolve,sampleInterval=2,scorchingSampleThreshold=10000,quickProfile -Xcheck:gc:vmthreads:all:quiet 

[2021-12-02T11:01:40.685Z] DLT 06:01:40.468 - Starting thread. Suite=0 thread=5
[2021-12-02T11:01:44.660Z] DLT 06:01:43.086 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa3.xml
[2021-12-02T11:01:44.660Z] DLT 06:01:43.088 - suite.isCreateDump() : false
[2021-12-02T11:01:44.660Z] DLT 06:01:43.088 - First failure detected by thread: load-4. Not creating dumps as no dump generation is requested for this load test
[2021-12-02T11:01:44.660Z] DLT 06:01:43.170 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa3.xml
[2021-12-02T11:01:44.660Z] DLT 06:01:43.171 - suite.isCreateDump() : false
[2021-12-02T11:01:44.660Z] DLT 06:01:43.171 - Test failed. Details recorded in execution log.
[2021-12-02T11:01:44.660Z] DLT 06:01:43.183 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa3.xml
[2021-12-02T11:01:44.660Z] DLT 06:01:43.183 - suite.isCreateDump() : false
[2021-12-02T11:01:44.660Z] DLT 06:01:43.183 - Test failed. Details recorded in execution log.
[2021-12-02T11:01:44.660Z] DLT 06:01:43.268 - Test failed
[2021-12-02T11:01:44.660Z] DLT   Failure num.  = 1
[2021-12-02T11:01:44.660Z] DLT   Test number   = 0
[2021-12-02T11:01:44.660Z] DLT   Test details  = 'JUnit[net.openj9.test.arithmetics.TestArithmeticOperations]'
[2021-12-02T11:01:44.660Z] DLT   Suite number  = 0
[2021-12-02T11:01:44.660Z] DLT   Thread number = 4
[2021-12-02T11:01:44.660Z] DLT >>> Captured test output >>>

[2021-12-02T11:06:41.717Z] DaaLoadTest_daa3_special_5m_16_FAILED
```

No further diagnosis info in the result file. Tagging as test component for now.

**Comment by JasonFengJ9** [comment]
[JDK8 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_aarch64_linux_testList_2/466/)(`ub22-aarch64-4`)
```
openjdk version "1.8.0_382-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_382-beta-202306262319-b03)
Eclipse OpenJ9 VM (build master-bd4a51cd9, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20230626_667 (JIT enabled, AOT enabled)
OpenJ9   - bd4a51cd9
OMR      - 2d5ac63fb
JCL      - 5fb693341 based on jdk8u382-b03)

[2023-06-27T03:00:00.742Z] variation: Mode615
[2023-06-27T03:00:00.742Z] JVM_OPTIONS:  -Xcompressedrefs -Xgcpolicy:gencon -Xquickstart -Xjit 

[2023-06-27T03:00:05.557Z] DLT 03:00:05.414 - Test failed
[2023-06-27T03:00:05.557Z] DLT   Failure num.  = 1
[2023-06-27T03:00:05.557Z] DLT   Test number   = 0
[2023-06-27T03:00:05.557Z] DLT   Test details  = 'JUnit[net.openj9.test.arithmetics.TestArithmeticOperations]'
[2023-06-27T03:00:05.557Z] DLT   Suite number  = 0
[2023-06-27T03:00:05.557Z] DLT   Thread number = 4
[2023-06-27T03:00:05.557Z] DLT >>> Captured test output >>>
[2023-06-27T03:00:05.557Z] DLT testStarted : initializationError(net.openj9.test.arithmetics.TestArithmeticOperations)
[2023-06-27T03:00:05.557Z] DLT testFailure: initializationError(net.openj9.test.arithmetics.TestArithmeticOperations): invokeinterface of non-public method 'hasNext()Z' in java/util/ArrayList$Itr
[2023-06-27T03:00:05.557Z] DLT java.lang.IllegalAccessError: invokeinterface of non-public method 'hasNext()Z' in java/util/ArrayList$Itr
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.FrameworkMember.isShadowedBy(FrameworkMember.java:16)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.TestClass.addToAnnotationLists(TestClass.java:87)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:66)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runner.Computer.getRunner(Computer.java:40)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runners.Suite.<init>(Suite.java:81)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runner.Computer.getSuite(Computer.java:28)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runner.Request.classes(Request.java:75)
[2023-06-27T03:00:05.557Z] DLT 	at org.junit.runner.Request.classes(Request.java:91)
[2023-06-27T03:00:05.557Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
[2023-06-27T03:00:05.557Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2023-06-27T03:00:05.557Z] DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-06-27T03:00:05.557Z] DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-06-27T03:00:05.557Z] DLT 	at java.lang.Thread.run(Thread.java:826)
[2023-06-27T03:00:05.557Z] DLT testFinished: initializationError(net.openj9.test.arithmetics.TestArithmeticOperations)
[2023-06-27T03:00:05.557Z] DLT 
[2023-06-27T03:00:05.557Z] DLT JUnit Test Results for: net.openj9.test.arithmetics.TestArithmeticOperations
[2023-06-27T03:00:05.557Z] DLT   Ran    : 1
[2023-06-27T03:00:05.557Z] DLT   Passed : 0
[2023-06-27T03:00:05.557Z] DLT   Failed : 1
[2023-06-27T03:00:05.557Z] DLT   Ignored: 0
[2023-06-27T03:00:05.557Z] DLT   Result : FAILED
[2023-06-27T03:00:05.557Z] DLT <<<
[2023-06-27T03:00:05.557Z] DLT 
[2023-06-27T03:00:26.386Z] DLT 03:00:25.276 - Completed 6.7%. Number of tests started=1065 (with 1 failure(s))

[2023-06-27T03:05:05.955Z] DaaLoadTest_daa3_special_5m_21_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33689/)

**Comment by JasonFengJ9** [comment]
Closing as dup of 
* https://github.com/eclipse-openj9/openj9/issues/18001
