### ISSUE TITLE
[JDK18] j.l.Error: TESTBUG: unsupported vm variant

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14079]
### OpenJDK Tests

```
TEST: java/lang/reflect/exeCallerAccessTest/CallerAccessTest.java
```

### Error

```
[2021-11-17T18:49:53.434Z] java.lang.Error: TESTBUG: unsupported vm variant
[2021-11-17T18:49:53.434Z]      at jdk.test.lib.Platform.variant(Platform.java:370)
[2021-11-17T18:49:53.434Z]      at jdk.test.lib.Platform.jvmLibDir(Platform.java:357)
[2021-11-17T18:49:53.434Z]      at CallerAccessTest.main(CallerAccessTest.java:53)
[2021-11-17T18:49:53.434Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:49:53.434Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:49:53.434Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:49:53.434Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:49:53.434Z]      at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-17T18:49:53.434Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: https://github.com/eclipse-openj9/openj9/issues/13946

**Comment by babsingh** [comment]
`exeCallerAccessTest/CallerAccessTest` has already been excluded due to https://github.com/adoptium/temurin-build/issues/248.

Test exclusion in aqa-tests: https://github.com/adoptium/aqa-tests/blob/253c7bf6fb188ca14c46bc13b2cc5426e13a12ea/openjdk/excludes/ProblemList_openjdk18-openj9.txt#L134

In https://github.com/adoptium/temurin-build/issues/248, I did not find an explicit reason for excluding this test.

@llxia @sophia-guo @smlambert why was `exeCallerAccessTest/CallerAccessTest` excluded in https://github.com/adoptium/temurin-build/issues/248? Is this test not compatible with OpenJ9 -- `Error: TESTBUG: unsupported vm variant`?

**Comment by llxia** [comment]
adoptium/temurin-build#248 is about lacking openjdk test image for JDK11+. This test image issue was closed in Sep 2019, so ideally all exclusions that are due to adoptium/temurin-build#248 should be reenabled. I guess we forget to reenable them? @sophia-guo could you please confirm?

**Comment by sophia-guo** [comment]
Yes, tests excluded by issue https://github.com/adoptium/temurin-build/issues/248 should be re-enabled as testImage is available and corresponding option -nativepath has also been added. 

@babsingh Originally `java/lang/reflect/exeCallerAccessTest/CallerAccessTest.java` was excluded because testImage was not created and -nativepath option couldn't be added . The error `java.lang.Error: TESTBUG: unsupported vm variant` is different, which may be specific to openj9.

**Comment by pshipton** [comment]
@babsingh are you able to remove labels? The "test excluded" label should be removed now that it's not excluded any more.

**Comment by babsingh** [comment]
> are you able to remove labels? The "test excluded" label should be removed now that it's not excluded any more.

Yes. The `test excluded` label has been removed.
