### ISSUE TITLE
[JDK18] ChainedLookupTest.methodInvokeViaMethodHandle failure

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14086]
### OpenJDK Tests
```
TEST: java/lang/invoke/lookup/ChainedLookupTest.java
```

### Errors
```
[2021-11-17T18:25:43.984Z] test ChainedLookupTest.methodInvokeViaMethodHandle(): failure
[2021-11-17T18:25:43.984Z] java.lang.AssertionError: expected [true] but found [false]
[2021-11-17T18:25:43.984Z]      at org.testng.Assert.fail(Assert.java:99)
[2021-11-17T18:25:43.984Z]      at org.testng.Assert.failNotEquals(Assert.java:1037)
[2021-11-17T18:25:43.984Z]      at org.testng.Assert.assertTrue(Assert.java:45)
[2021-11-17T18:25:43.984Z]      at org.testng.Assert.assertTrue(Assert.java:55)
[2021-11-17T18:25:43.984Z]      at ChainedLookupTest.test(ChainedLookupTest.java:126)
[2021-11-17T18:25:43.984Z]      at ChainedLookupTest.methodInvokeViaMethodHandle(ChainedLookupTest.java:74)
```

Related: #13946

**Comment by babsingh** [comment]
In a recent run, `ChainedLookupTest` passes. Recent changes to support and enable JEP416 should have fixed this failure. These changes are linked to the uber issue: https://github.com/eclipse-openj9/openj9/issues/13852.
