### ISSUE TITLE
[JDK18] jdk.test.MethodInvokeTest$Caller1 should be a hidden class

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14088]
### OpenJDK Tests
```
TEST: java/lang/invoke/callerSensitive/Main.java
```

### Errors
```
[2021-11-17T18:42:56.152Z] java.lang.RuntimeException: class jdk.test.MethodInvokeTest$Caller1 should be a hidden class
[2021-11-17T18:42:56.152Z]      at csm/jdk.test.MethodInvokeTest.assertTrue(MethodInvokeTest.java:208)
[2021-11-17T18:42:56.152Z]      at csm/jdk.test.MethodInvokeTest.checkInjectedInvoker(MethodInvokeTest.java:187)
[2021-11-17T18:42:56.152Z]      at csm/jdk.test.MethodInvokeTest.reflectMethodCall(MethodInvokeTest.java:99)
[2021-11-17T18:42:56.152Z]      at csm/jdk.test.MethodInvokeTest.main(MethodInvokeTest.java:64)
[2021-11-17T18:42:56.152Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:42:56.152Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:42:56.152Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:42:56.152Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:42:56.152Z]      at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-17T18:42:56.152Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: #13946

**Comment by babsingh** [comment]
This failure no longer occurs. Recent changes for OJDK MHs or JEP416 may have fixed this failure.
