### ISSUE TITLE
[JDK18] ClassForNameTest failure 

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14089]
### OpenJDK Tests

```
TEST: java/lang/invoke/7196190/ClassForNameTest.java
```

### Errors

```
[2021-11-17T18:25:19.002Z] java.lang.reflect.InvocationTargetException
[2021-11-17T18:25:19.002Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:25:19.002Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:25:19.002Z]      at java.base/jdk.internal.reflect.MethodAccessorImpl.invoke(MethodAccessorImpl.java:51)
[2021-11-17T18:25:19.002Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:59)
[2021-11-17T18:25:19.002Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:604)
[2021-11-17T18:25:19.002Z]      at java.lang.invoke.LambdaForm$DMH/0x000000001003a3b0.invokeVirtual(LambdaForm$DMH)
[2021-11-17T18:25:19.002Z]      at java.lang.invoke.LambdaForm$MH/0x000000001004c980.invoke(LambdaForm$MH)
[2021-11-17T18:25:19.002Z]      at java.lang.invoke.LambdaForm$MH/0x0000000010035ac0.invoke_MT(LambdaForm$MH)
[2021-11-17T18:25:19.002Z]      at ClassForNameTest.main(ClassForNameTest.java:63)
[2021-11-17T18:25:19.002Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:25:19.002Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:25:19.002Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:25:19.002Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:25:19.002Z]      at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-17T18:25:19.002Z]      at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-17T18:25:19.002Z] Caused by: java.lang.ClassNotFoundException: ClassForNameTest
[2021-11-17T18:25:19.002Z]      at java.base/java.lang.Class.forNameImpl(Native Method)
[2021-11-17T18:25:19.002Z]      at java.base/java.lang.Class.forName(Class.java:351)
[2021-11-17T18:25:19.002Z]      ... 15 more
```

Related: #13946

**Comment by babsingh** [comment]
This failure no longer occurs. Recent changes for OJDK MHs or JEP416 may have fixed this failure.
