### ISSUE TITLE
[JDK18] ProxyTest.runDefaultMethodsTest() failure

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14082]
### OpenJDK Tests
```
TEST: java/lang/reflect/Proxy/ProxyTest.java
```

### Error
```
[2021-11-17T18:32:22.147Z] test ProxyTest.runDefaultMethodsTest(): failure
[2021-11-17T18:32:22.147Z] java.lang.AssertionError: expected [true] but found [false]
[2021-11-17T18:32:22.147Z]      at org.testng.Assert.fail(Assert.java:99)
[2021-11-17T18:32:22.147Z]      at org.testng.Assert.failNotEquals(Assert.java:1037)
[2021-11-17T18:32:22.147Z]      at org.testng.Assert.assertTrue(Assert.java:45)
[2021-11-17T18:32:22.147Z]      at org.testng.Assert.assertTrue(Assert.java:55)
[2021-11-17T18:32:22.147Z]      at ProxyTest.runDefaultMethodsTest(ProxyTest.java:98)
[2021-11-17T18:32:22.147Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:32:22.147Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:32:22.147Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:32:22.147Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:32:22.147Z]      at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-11-17T18:32:22.147Z]      at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-11-17T18:32:22.147Z]      at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-11-17T18:32:22.147Z]      at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-11-17T18:32:22.147Z]      at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-11-17T18:32:22.147Z]      at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-11-17T18:32:22.147Z]      at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-11-17T18:32:22.148Z]      at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-11-17T18:32:22.148Z]      at org.testng.TestRunner$$Lambda$121/0x00000000180ade58.accept(Unknown Source)
[2021-11-17T18:32:22.148Z]      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-11-17T18:32:22.148Z]      at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-11-17T18:32:22.148Z]      at org.testng.TestRunner.run(TestRunner.java:585)
[2021-11-17T18:32:22.148Z]      at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-11-17T18:32:22.148Z]      at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-11-17T18:32:22.148Z]      at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-11-17T18:32:22.148Z]      at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-11-17T18:32:22.148Z]      at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-11-17T18:32:22.148Z]      at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-11-17T18:32:22.148Z]      at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-11-17T18:32:22.148Z]      at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-11-17T18:32:22.148Z]      at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-11-17T18:32:22.148Z]      at org.testng.TestNG.run(TestNG.java:1037)
[2021-11-17T18:32:22.148Z]      at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-17T18:32:22.148Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:32:22.148Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:32:22.148Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:32:22.148Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:32:22.148Z]      at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-17T18:32:22.148Z]      at java.base/java.lang.Thread.run(Thread.java:884)

```

Related #13946

**Comment by babsingh** [comment]
In a recent run, this test passes. The error reported above most likely happens as a side effect of the error reported in https://github.com/eclipse-openj9/openj9/issues/13995. https://github.com/eclipse-openj9/openj9/issues/13995 has been fixed via https://github.com/eclipse-openj9/openj9/pull/14044, which has indirectly fixed the above error.
