### ISSUE TITLE
[JDK18] UncaughtExceptionsTest failure

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14095]
### OpenJDK Tests
```
TEST: java/lang/Thread/UncaughtExceptionsTest.java
```

### Errors
```
[2021-11-17T18:34:44.374Z] test UncaughtExceptionsTest.test("ThreadIsDeadAfterJoin", 0, "OK", "Exception in thread "Thread-0".*simulateUncaughtExitEvent"): failure
[2021-11-17T18:34:44.374Z] java.lang.RuntimeException: 'Exception in thread "Thread-0".*simulateUncaughtExitEvent' missing from stderr
[2021-11-17T18:34:44.374Z]
[2021-11-17T18:34:44.374Z]      at jdk.test.lib.process.OutputAnalyzer.stderrShouldMatch(OutputAnalyzer.java:376)
[2021-11-17T18:34:44.374Z]      at UncaughtExceptionsTest.test(UncaughtExceptionsTest.java:71)
[2021-11-17T18:34:44.374Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:34:44.374Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:34:44.374Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.374Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.374Z]      at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-11-17T18:34:44.374Z]      at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-11-17T18:34:44.374Z]      at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-11-17T18:34:44.374Z]      at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-11-17T18:34:44.374Z]      at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-11-17T18:34:44.375Z]      at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-11-17T18:34:44.375Z]      at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-11-17T18:34:44.375Z]      at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-11-17T18:34:44.375Z]      at org.testng.TestRunner$$Lambda$121/0x00000000080af848.accept(Unknown Source)
[2021-11-17T18:34:44.375Z]      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-11-17T18:34:44.375Z]      at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-11-17T18:34:44.375Z]      at org.testng.TestRunner.run(TestRunner.java:585)
[2021-11-17T18:34:44.375Z]      at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-11-17T18:34:44.375Z]      at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-11-17T18:34:44.375Z]      at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-11-17T18:34:44.375Z]      at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-11-17T18:34:44.375Z]      at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-11-17T18:34:44.375Z]      at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-11-17T18:34:44.375Z]      at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-11-17T18:34:44.375Z]      at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-11-17T18:34:44.375Z]      at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-11-17T18:34:44.375Z]      at org.testng.TestNG.run(TestNG.java:1037)
[2021-11-17T18:34:44.375Z]      at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-17T18:34:44.375Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:34:44.375Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:34:44.375Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.375Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.375Z]      at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-17T18:34:44.375Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: #13946

**Comment by babsingh** [comment]
Closing issue since it is a duplicate of https://github.com/eclipse-openj9/openj9/issues/11930.

As per https://github.com/eclipse-openj9/openj9/issues/11930#issuecomment-776136544:
> Seems the test is expecting Thread-0 but OpenJ9 created Thread-3. We should check why that is and see if the difference in behavior can be resolved.
