### ISSUE TITLE
[JDK18] FileEncodingTest.testFileEncodingToDefault failures

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14093]
### OpenJDK Tests
```
TEST: java/lang/System/FileEncodingTest.java
```

### Errors
```
==== Error 1 ====
[2021-11-17T18:34:44.365Z] test FileEncodingTest.testFileEncodingToDefault("", "UTF-8"): failure
[2021-11-17T18:34:44.365Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2021-11-17T18:34:44.365Z]
[2021-11-17T18:34:44.365Z]      at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
[2021-11-17T18:34:44.365Z]      at FileEncodingTest.testFileEncodingToDefault(FileEncodingTest.java:81)
[2021-11-17T18:34:44.365Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:34:44.365Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:34:44.365Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.365Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-11-17T18:34:44.365Z]      at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-11-17T18:34:44.365Z]      at org.testng.TestRunner$$Lambda$121/0x00000000200b6bb0.accept(Unknown Source)
[2021-11-17T18:34:44.365Z]      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-11-17T18:34:44.365Z]      at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-11-17T18:34:44.365Z]      at org.testng.TestRunner.run(TestRunner.java:585)
[2021-11-17T18:34:44.365Z]      at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-11-17T18:34:44.365Z]      at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-11-17T18:34:44.365Z]      at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-11-17T18:34:44.365Z]      at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-11-17T18:34:44.365Z]      at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-11-17T18:34:44.365Z]      at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-11-17T18:34:44.365Z]      at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-11-17T18:34:44.365Z]      at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-11-17T18:34:44.365Z]      at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-11-17T18:34:44.366Z]      at org.testng.TestNG.run(TestNG.java:1037)
[2021-11-17T18:34:44.366Z]      at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-17T18:34:44.366Z]      at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
[2021-11-17T18:34:44.366Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.366Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.366Z]      at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-17T18:34:44.366Z]      at java.base/java.lang.Thread.run(Thread.java:884)

==== Error 2 ====
[2021-11-17T18:34:44.366Z] test FileEncodingTest.testFileEncodingToDefault("COMPAT", "<should_be_replaced>"): failure
[2021-11-17T18:34:44.366Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2021-11-17T18:34:44.366Z]
[2021-11-17T18:34:44.366Z]      at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
[2021-11-17T18:34:44.366Z]      at FileEncodingTest.testFileEncodingToDefault(FileEncodingTest.java:81)
[2021-11-17T18:34:44.366Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:34:44.366Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:34:44.367Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.367Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2021-11-17T18:34:44.367Z]      at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2021-11-17T18:34:44.367Z]      at org.testng.TestRunner$$Lambda$121/0x00000000200b6bb0.accept(Unknown Source)
[2021-11-17T18:34:44.367Z]      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2021-11-17T18:34:44.367Z]      at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2021-11-17T18:34:44.367Z]      at org.testng.TestRunner.run(TestRunner.java:585)
[2021-11-17T18:34:44.367Z]      at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2021-11-17T18:34:44.367Z]      at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2021-11-17T18:34:44.367Z]      at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2021-11-17T18:34:44.367Z]      at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2021-11-17T18:34:44.367Z]      at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2021-11-17T18:34:44.367Z]      at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2021-11-17T18:34:44.367Z]      at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2021-11-17T18:34:44.367Z]      at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2021-11-17T18:34:44.367Z]      at org.testng.TestNG.runSuites(TestNG.java:1069)
[2021-11-17T18:34:44.367Z]      at org.testng.TestNG.run(TestNG.java:1037)
[2021-11-17T18:34:44.367Z]      at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2021-11-17T18:34:44.367Z]      at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
[2021-11-17T18:34:44.367Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.367Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.367Z]      at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-17T18:34:44.367Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: #13946

**Comment by JasonFengJ9** [comment]
Closing as dup of https://github.com/eclipse-openj9/openj9/issues/14233 which specified two failures:
```
15:15:22  TEST: java/lang/System/MacEncoding/MacJNUEncoding.java
15:15:22  TEST: java/lang/System/MacEncoding/TestFileEncoding.java
```
Their share same underneath cause.
