### ISSUE TITLE
[JDK18] System.setSecurityManager didn't throw UnsupportedOperationException

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14092]
### OpenJDK Tests

```
TEST: java/lang/System/AllowSecurityManager.java
```

### Errors

```
[2021-11-17T18:34:44.360Z] WARNING: A terminally deprecated method in java.lang.System has been called
[2021-11-17T18:34:44.360Z] WARNING: System::setSecurityManager has been called by AllowSecurityManager (file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_OpenJDK/aqa-tests/TKG/output_16371734171260/jdk_lan
g_0/work/classes/0/java/lang/System/AllowSecurityManager.d/)
[2021-11-17T18:34:44.360Z] WARNING: Please consider reporting this to the maintainers of AllowSecurityManager
[2021-11-17T18:34:44.360Z] WARNING: System::setSecurityManager will be removed in a future release
[2021-11-17T18:34:44.360Z] java.lang.Exception: System.setSecurityManager did not throw UnsupportedOperationException
[2021-11-17T18:34:44.360Z]      at AllowSecurityManager.main(AllowSecurityManager.java:42)
[2021-11-17T18:34:44.360Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:34:44.360Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:34:44.360Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.360Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.360Z]      at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-17T18:34:44.360Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: #13946

**Comment by babsingh** [comment]
Test re-enabled via https://github.com/adoptium/aqa-tests/pull/3318.
