### ISSUE TITLE
[JDK18] SecurityManagerWarnings failure

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14094]
### OpenJDK Tests
```
TEST: java/lang/System/SecurityManagerWarnings.java
```

### Errors
```
[2021-11-17T18:34:44.370Z] STDERR:
[2021-11-17T18:34:44.370Z]  stdout: [SM is enabled: false
[2021-11-17T18:34:44.370Z] ];
[2021-11-17T18:34:44.370Z]  stderr: [WARNING: A terminally deprecated method in java.lang.System has been called
[2021-11-17T18:34:44.370Z] WARNING: System::setSecurityManager has been called by A (file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_OpenJDK/aqa-tests/TKG/output_16371734171260/jdk_lang_0/work/classes/0/
java/lang/System/SecurityManagerWarnings.d/)
[2021-11-17T18:34:44.370Z] WARNING: Please consider reporting this to the maintainers of A
[2021-11-17T18:34:44.370Z] WARNING: System::setSecurityManager will be removed in a future release
[2021-11-17T18:34:44.370Z] WARNING: A terminally deprecated method in java.lang.System has been called
[2021-11-17T18:34:44.370Z] WARNING: System::setSecurityManager has been called by B (file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_OpenJDK/aqa-tests/TKG/output_16371734171260/jdk_lang_0/work/classes/0/
java/lang/System/SecurityManagerWarnings.d/)
[2021-11-17T18:34:44.370Z] WARNING: Please consider reporting this to the maintainers of B
[2021-11-17T18:34:44.370Z] WARNING: System::setSecurityManager will be removed in a future release
[2021-11-17T18:34:44.370Z] ]
[2021-11-17T18:34:44.371Z]  exitValue = 0
[2021-11-17T18:34:44.371Z]
[2021-11-17T18:34:44.371Z] java.lang.RuntimeException: Unexpected to get exit value of [0]
[2021-11-17T18:34:44.371Z]
[2021-11-17T18:34:44.371Z]      at jdk.test.lib.process.OutputAnalyzer.shouldNotHaveExitValue(OutputAnalyzer.java:504)
[2021-11-17T18:34:44.371Z]      at SecurityManagerWarnings.disallowTest(SecurityManagerWarnings.java:102)
[2021-11-17T18:34:44.371Z]      at SecurityManagerWarnings.main(SecurityManagerWarnings.java:56)
[2021-11-17T18:34:44.371Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:34:44.371Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:34:44.371Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:34:44.371Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:34:44.371Z]      at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-17T18:34:44.371Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: #13946

**Comment by babsingh** [comment]
Test re-enabled via https://github.com/adoptium/aqa-tests/pull/3318.
