### ISSUE TITLE
OpenJDK java/util/logging/LoggingDeadlock2 timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14100]
FYI previous problems with this test 
https://github.com/eclipse-openj9/openj9/issues/10685
https://github.com/eclipse-openj9/openj9/issues/10993
https://github.com/eclipse-openj9/openj9/issues/12594

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/166
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/logging/LoggingDeadlock2.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/166/openjdk_test_output.tar.gz
```
00:02:19  ACTION: main -- Error. Agent error: java.lang.Exception: Agent 6 timed out with a timeout of 960 seconds; check console log for any additional details
00:02:19  REASON: User specified action: run main LoggingDeadlock2 
00:02:19  TIME:   964.946 seconds
00:02:19  messages:
00:02:19  command: main LoggingDeadlock2
00:02:19  reason: User specified action: run main LoggingDeadlock2 
00:02:19  Mode: agentvm
00:02:19  Agent id: 6
00:02:19  Timeout refired 960 times
00:02:19  Timeout information:
00:02:19  Running jcmd on process 3154126
00:02:19  Dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/scratch/0/core.20211207.050208.3154126.0001.dmp
00:02:19  Running jstack on process 3154126
00:02:19  2021-12-07T05:02:10.007792021
00:02:19  Virtual machine: 3154126 JVM information:
00:02:19  JRE 11 Linux s390x-64-Bit Compressed References 20211206_167 (JIT enabled, AOT enabled)
00:02:19  OpenJ9   - 30224204f34
00:02:19  OMR      - 5e9418dcfde
00:02:19  JCL      - 40dd8d80417 based on jdk-11.0.14+5
00:02:19  
00:02:19  "main" prio=5 Id=1 WAITING
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Object.java:221)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.join(Thread.java:746)
00:02:19  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:184)
00:02:19  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:301)
00:02:19  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:232)
00:02:19  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
00:02:19  
00:02:19  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
00:02:19  
00:02:19  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
00:02:19  
00:02:19  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
00:02:19  
00:02:19  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
00:02:19  
00:02:19  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
00:02:19  
00:02:19  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
00:02:19  
00:02:19  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
00:02:19  
00:02:19  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
00:02:19  
00:02:19  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
00:02:19  
00:02:19  "IProfiler" prio=5 Id=12 RUNNABLE
00:02:19  
00:02:19  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Object.java:221)
00:02:19  	at java.base@11.0.14-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
00:02:19  	at java.base@11.0.14-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.run(Thread.java:866)
00:02:19  	at java.base@11.0.14-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
00:02:19  
00:02:19  "Concurrent Mark Helper" prio=1 Id=13 RUNNABLE
00:02:19  
00:02:19  "Finalizer thread" prio=5 Id=14 RUNNABLE
00:02:19  
00:02:19  "GC Worker" prio=5 Id=15 RUNNABLE
00:02:19  
00:02:19  "GC Worker" prio=5 Id=16 RUNNABLE
00:02:19  
00:02:19  "GC Worker" prio=5 Id=17 RUNNABLE
00:02:19  
00:02:19  "Attach API wait loop" prio=10 Id=20 TIMED_WAITING
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.sleep(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.sleep(Thread.java:997)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:142)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
00:02:19  
00:02:19  "pool-1-thread-1" prio=5 Id=21 TIMED_WAITING
00:02:19  	at java.base@11.0.14-internal/jdk.internal.misc.Unsafe.park(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.run(Thread.java:866)
00:02:19  
00:02:19  "process reaper" prio=10 Id=23 RUNNABLE
00:02:19  	at java.base@11.0.14-internal/java.lang.ProcessHandleImpl.waitForProcessExit0(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:138)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.run(Thread.java:866)
00:02:19  
00:02:19  "AgentVMThread" prio=5 Id=35 WAITING
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Object.java:192)
00:02:19  	at java.base@11.0.14-internal/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
00:02:19  	at LoggingDeadlock2.run(LoggingDeadlock2.java:306)
00:02:19  	at LoggingDeadlock2.realMain(LoggingDeadlock2.java:78)
00:02:19  	at LoggingDeadlock2.main(LoggingDeadlock2.java:333)
00:02:19  	at java.base@11.0.14-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:02:19  	at java.base@11.0.14-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:02:19  	at java.base@11.0.14-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:02:19  	at java.base@11.0.14-internal/java.lang.reflect.Method.invoke(Method.java:566)
00:02:19  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.run(Thread.java:866)
00:02:19  
00:02:19  "Thread-9" prio=5 Id=36 RUNNABLE
00:02:19  	at java.base@11.0.14-internal/java.io.FileInputStream.readBytes(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.io.FileInputStream.read(FileInputStream.java:279)
00:02:19  	at java.base@11.0.14-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
00:02:19  	at java.base@11.0.14-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
00:02:19  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@fec41e2b
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
00:02:19  	- locked java.io.InputStreamReader@88a8e9fa
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
00:02:19  	- locked java.io.InputStreamReader@88a8e9fa
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
00:02:19  	at java.base@11.0.14-internal/java.io.InputStreamReader.read(InputStreamReader.java:164)
00:02:19  	at LoggingDeadlock2$StreamAccumulator.run(LoggingDeadlock2.java:219)
00:02:19  
00:02:19  "Thread-10" prio=5 Id=37 RUNNABLE
00:02:19  	at java.base@11.0.14-internal/java.io.FileInputStream.readBytes(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.io.FileInputStream.read(FileInputStream.java:279)
00:02:19  	at java.base@11.0.14-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
00:02:19  	at java.base@11.0.14-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
00:02:19  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@6c3a60ec
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
00:02:19  	- locked java.io.InputStreamReader@39aaa04d
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
00:02:19  	- locked java.io.InputStreamReader@39aaa04d
00:02:19  	at java.base@11.0.14-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
00:02:19  	at java.base@11.0.14-internal/java.io.InputStreamReader.read(InputStreamReader.java:164)
00:02:19  	at LoggingDeadlock2$StreamAccumulator.run(LoggingDeadlock2.java:219)
00:02:19  
00:02:19  "TimeoutThread" prio=5 Id=38 TIMED_WAITING
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.sleep(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.sleep(Thread.java:997)
00:02:19  	at LoggingDeadlock2$TimeoutThread.run(LoggingDeadlock2.java:263)
00:02:19  
00:02:19  "file lock watchdog" prio=10 Id=55 TIMED_WAITING
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.lang.Object.wait(Object.java:221)
00:02:19  	at java.base@11.0.14-internal/java.util.TimerThread.mainLoop(Timer.java:553)
00:02:19  	at java.base@11.0.14-internal/java.util.TimerThread.run(Timer.java:506)
00:02:19  
00:02:19  "process reaper" prio=10 Id=56 TIMED_WAITING
00:02:19  	at java.base@11.0.14-internal/jdk.internal.misc.Unsafe.park(Native Method)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
00:02:19  	at java.base@11.0.14-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:02:19  	at java.base@11.0.14-internal/java.lang.Thread.run(Thread.java:866)
00:02:19  
00:02:19  "Attachment 42395" prio=10 Id=57 RUNNABLE
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$5/0x0000000000000000.apply(Unknown Source)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
00:02:19  	at java.base@11.0.14-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
00:02:19  
00:02:19  
00:02:19  --- Timeout information end.
00:02:19  elapsed time (seconds): 964.946
00:02:19  configuration:
00:02:19  Boot Layer
00:02:19    class path: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar 
00:02:19                /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar 
00:02:19                /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar 
00:02:19                /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar 
00:02:19                /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar 
00:02:19    patch:      java.base /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/patches/java.base
00:02:19  
00:02:19  Test Layer
00:02:19    class path: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/classes/0/java/util/logging/LoggingDeadlock2.d
00:02:19                /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging
00:02:19  
00:02:19  rerun:
00:02:19  cd /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/scratch/0 && \
00:02:19  DISPLAY=:0 \
00:02:19  HOME=/home/jenkins \
00:02:19  LANG=en_US.UTF-8 \
00:02:19  PATH=/bin:/usr/bin:/usr/sbin \
00:02:19      /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
00:02:19          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
00:02:19          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
00:02:19          -Dtest.compiler.opts= \
00:02:19          -Dtest.java.opts= \
00:02:19          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image \
00:02:19          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image \
00:02:19          -Dtest.timeout.factor=8.0 \
00:02:19          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
00:02:19          -Dtest.root=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
00:02:19          -Dtest.name=java/util/logging/LoggingDeadlock2.java \
00:02:19          -Dtest.file=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging/LoggingDeadlock2.java \
00:02:19          -Dtest.src=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging \
00:02:19          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging \
00:02:19          -Dtest.classes=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/classes/0/java/util/logging/LoggingDeadlock2.d \
00:02:19          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/classes/0/java/util/logging/LoggingDeadlock2.d \
00:02:19          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/classes/0/java/util/logging/LoggingDeadlock2.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging \
00:02:19          -Dtest.modules=java.logging \
00:02:19          -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/classes/0/java/util/logging/LoggingDeadlock2.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
00:02:19          LoggingDeadlock2
00:02:19  STDOUT:
00:02:19  [/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/bin/java, -classpath, /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/classes/0/java/util/logging/LoggingDeadlock2.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar, LoggingDeadlostdout:
00:02:19  2021-12-07T04:47:07.641355484
00:02:19  2021-12-07T04:48:07.828562388
00:02:19  2021-12-07T04:49:08.040719625
00:02:19  2021-12-07T04:50:08.228283509
00:02:19  2021-12-07T04:51:08.525165715
00:02:19  2021-12-07T04:52:08.744963800
00:02:19  2021-12-07T04:53:08.930767345
00:02:19  2021-12-07T04:54:09.145583889
00:02:19  2021-12-07T04:55:09.359311505
00:02:19  2021-12-07T04:56:09.577907782
00:02:19  2021-12-07T04:57:09.765157567
00:02:19  2021-12-07T04:58:10.003300266
00:02:19  2021-12-07T04:59:10.205606796
00:02:19  2021-12-07T05:00:10.502325052
00:02:19  2021-12-07T05:01:10.715166858
00:02:19  2021-12-07T05:02:10.928840752
00:02:19  stderr:
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/scratch/0/core.20211207.050208.3154126.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
00:02:19  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16388504453533/jdk_util_0/work/scratch/0/core.20211207.050208.3154126.0001.dmp
00:02:19  Error getting data from 3154792: Exception connecting to 3154792
00:02:19  
00:02:19  TEST RESULT: Error. Agent error: java.lang.Exception: Agent 6 timed out with a timeout of 960 seconds; check console log for any additional details
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/322
jdk_util_1
java/util/logging/LoggingDeadlock2.java
```
20:32:12  "main" prio=5 Id=2 RUNNABLE
20:32:12  	at java.base@21.0.7-internal/java.util.HashMap.putVal(HashMap.java:648)
20:32:12  	at java.base@21.0.7-internal/java.util.HashMap.put(HashMap.java:618)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.PoolWriter.makeBootstrapEntry(PoolWriter.java:249)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.PoolWriter$WriteablePoolHelper.writeConstant(PoolWriter.java:463)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.PoolWriter$WriteablePoolHelper.writeIfNeeded(PoolWriter.java:358)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.PoolWriter.putDynamic(PoolWriter.java:133)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Code.emitInvokedynamic(Code.java:498)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Items$DynamicItem.invoke(Items.java:490)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.StringConcat$IndyConstants.doCall(StringConcat.java:504)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.StringConcat$IndyConstants.emit(StringConcat.java:449)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.StringConcat$Indy.makeConcat(StringConcat.java:257)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.visitBinary(Gen.java:2209)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:885)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genArgs(Gen.java:910)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.visitNewClass(Gen.java:2029)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1871)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:885)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.visitThrow(Gen.java:1919)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.tree.JCTree$JCThrow.accept(JCTree.java:1753)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:614)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:649)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:635)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genStats(Gen.java:686)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.doVisitBlock(Gen.java:1128)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.visitBlock(Gen.java:1121)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1092)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:614)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genStat(Gen.java:649)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genMethod(Gen.java:975)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.visitMethodDef(Gen.java:938)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:916)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genDef(Gen.java:614)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2482)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:769)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1710)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1678)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:976)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.main.Main.compile(Main.java:319)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.main.Main.compile(Main.java:178)
20:32:12  	at app/jdk.compiler@21.0.7-internal/com.sun.tools.javac.Main.compile(Main.java:82)
20:32:12  	at java.base@21.0.7-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:32:12  	at java.base@21.0.7-internal/java.lang.reflect.Method.invoke(Method.java:586)
20:32:12  	at app//com.sun.javatest.regtest.agent.RegressionCompileCommand.run(RegressionCompileCommand.java:189)
20:32:12  	at app//com.sun.javatest.regtest.agent.CompileActionHelper.runCompile(CompileActionHelper.java:92)
20:32:12  	at app//com.sun.javatest.regtest.agent.AgentServer.doCompile(AgentServer.java:272)
20:32:12  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:239)
20:32:12  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:71)
```
