### ISSUE TITLE
JDK8 aarch64_linux java.lang.InternalError: SIGBUS

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14122]
Failure link
------------

From an internal build `job/Test_openjdk8_j9_special.system_aarch64_linux_testList_4/118/`(`ub18-aarch64-1`):
```
openjdk version "1.8.0_322-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_322-beta-202112080334-b04)
Eclipse OpenJ9 VM (build master-f5069c6c9, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20211208_245 (JIT enabled, AOT enabled)
OpenJ9   - f5069c6c9
OMR      - 11cbde10d
JCL      - 854c9aec based on jdk8u322-b04)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=MauveSingleInvocLoad_special_5m_22&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F245%2Fibm-semeru-open-testimage_aarch64_linux_JDK8U_2021-12-08-03-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F245%2Fibm-semeru-open-jre_aarch64_linux_JDK8U_2021-12-08-03-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F245%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2021-12-08-03-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F245%2Fibm-semeru-open-debugimage_aarch64_linux_JDK8U_2021-12-08-03-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;USE_JRE=false&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=142&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-12-08T08:54:57.329Z] variation: Mode688
[2021-12-08T08:54:57.329Z] JVM_OPTIONS:  -Xcompressedrefs -Xjit:count=0 -Xgcpolicy:gencon -Xaggressive -Xconcurrentlevel0 

[2021-12-08T08:56:11.800Z] LT  Test failed:
[2021-12-08T08:56:11.800Z] LT  java.lang.InternalError: SIGBUS
[2021-12-08T08:56:11.800Z] LT  	at gnu.testlet.java.util.LinkedHashMap.LinkedHashMapTest$1ChangeMap.removeEldestEntry(LinkedHashMapTest.java:531)
[2021-12-08T08:56:11.800Z] LT  	at java.util.LinkedHashMap.afterNodeInsertion(LinkedHashMap.java:299)
[2021-12-08T08:56:11.800Z] LT  	at java.util.HashMap.putVal(HashMap.java:665)
[2021-12-08T08:56:11.800Z] LT  	at java.util.HashMap.put(HashMap.java:613)
[2021-12-08T08:56:11.800Z] LT  	at gnu.testlet.java.util.LinkedHashMap.LinkedHashMapTest.test_removeEldestEntry(LinkedHashMapTest.java:546)
[2021-12-08T08:56:11.800Z] LT  	at gnu.testlet.java.util.LinkedHashMap.LinkedHashMapTest.test(LinkedHashMapTest.java:63)
[2021-12-08T08:56:11.800Z] LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-12-08T08:56:11.800Z] LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-12-08T08:56:11.800Z] LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-08T08:56:11.800Z] LT  	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-12-08T08:56:11.800Z] LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
[2021-12-08T08:56:11.800Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2021-12-08T08:56:11.800Z] LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-12-08T08:56:11.800Z] LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2021-12-08T08:56:11.800Z] LT  	at java.lang.Thread.run(Thread.java:827)
[2021-12-08T08:56:11.800Z] LT  <<<

[2021-12-08T09:00:34.087Z] MauveSingleInvocLoad_special_5m_22_FAILED
```

**Comment by AdamBrousseau** [comment]
ub18-aarch64-1.svl.ibm.com is pretty full on swap. Rebooted. Looks better now.

**Comment by JasonFengJ9** [comment]
Closing based on analysis/fix above.
