### ISSUE TITLE
jdk_security4_1_FAILED : `main' threw exception: java.lang.Exception

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14153]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_extended.openjdk_s390x_linux/46/`(`ub18s390xrt-1-4`):
```
openjdk version "11.0.14" 2022-01-18
IBM Semeru Runtime Open Edition 11.0.14.0-m2 (build 11.0.14+6)
Eclipse OpenJ9 VM 11.0.14.0-m2 (build openj9-0.30.0-m2, JRE 11 Linux s390x-64-Bit Compressed References 20211213_270 (JIT enabled, AOT enabled)
OpenJ9   - ebcfd68c8
OMR      - dac962a28
JCL      - 830da4a5e1 based on jdk-11.0.14+6)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security4_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9%2F270%2Fibm-semeru-open-testimage_s390x_linux_11.0.14_6_openj9-0.30.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9%2F270%2Fibm-semeru-open-debugimage_s390x_linux_11.0.14_6_openj9-0.30.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9%2F270%2Fibm-semeru-open-jre_s390x_linux_11.0.14_6_openj9-0.30.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9%2F270%2Fibm-semeru-open-jdk_s390x_linux_11.0.14_6_openj9-0.30.0-m2.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=v0.30.0-release&amp;OPENJ9_BRANCH=v0.30.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.30.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=3&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-12-14T17:24:09.096Z] STDERR:
[2021-12-14T17:24:09.096Z] Nsanity started
[2021-12-14T17:24:09.096Z] Na started
[2021-12-14T17:24:09.096Z] Nb started
[2021-12-14T17:24:09.096Z] java.lang.Exception
[2021-12-14T17:24:09.096Z] 	at ReplayCacheTestProc.main0(ReplayCacheTestProc.java:279)
[2021-12-14T17:24:09.096Z] 	at ReplayCacheTestProc.main(ReplayCacheTestProc.java:326)
[2021-12-14T17:24:09.096Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-12-14T17:24:09.096Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-12-14T17:24:09.096Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-14T17:24:09.096Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-12-14T17:24:09.096Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-12-14T17:24:09.096Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2021-12-14T17:24:09.096Z] java.lang.Exception
[2021-12-14T17:24:09.097Z] 	at ReplayCacheTestProc.main0(ReplayCacheTestProc.java:279)
[2021-12-14T17:24:09.097Z] 	at ReplayCacheTestProc.main(ReplayCacheTestProc.java:326)
[2021-12-14T17:24:09.097Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-12-14T17:24:09.097Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-12-14T17:24:09.100Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-14T17:24:09.100Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-12-14T17:24:09.100Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-12-14T17:24:09.100Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2021-12-14T17:24:09.100Z] 
[2021-12-14T17:24:09.100Z] JavaTest Message: Test threw exception: java.lang.Exception
[2021-12-14T17:24:09.100Z] JavaTest Message: shutting down test
[2021-12-14T17:24:09.100Z] 
[2021-12-14T17:24:09.100Z] STATUS:Failed.`main' threw exception: java.lang.Exception

[2021-12-14T17:24:09.100Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception
[2021-12-14T17:24:09.100Z] --------------------------------------------------
[2021-12-14T17:25:52.624Z] Test results: passed: 136; failed: 1
[2021-12-14T17:25:55.038Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux/jvmtest/openjdk/report/html/report.html
[2021-12-14T17:25:55.038Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16394897177783/jdk_security4_1/work
[2021-12-14T17:25:55.038Z] Error: Some tests failed or other problems occurred.
[2021-12-14T17:25:55.038Z] 
[2021-12-14T17:25:55.038Z] jdk_security4_1_FAILED
```

It smells like a machine/network issue.
30x grinder at `job/Grinder/20014/`.

**Comment by JasonFengJ9** [comment]
Dup of https://github.com/eclipse-openj9/openj9/issues/13756
