### ISSUE TITLE
Windows Failed to instantiate heap

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14165]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/171 - win2012-x86-7
MiniMix_aot_5m_0
```
LT  stderr JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  2G requested
```

This would be caused by leftover processes, or incorrectly configured swap space. I thought we already fixed the swap space on all the Windows machines. @AdamBrousseau

**Comment by pshipton** [comment]
More problems on another machines, in this case it shows `The paging file is too small for this operation to complete`

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_OpenJDK11/20 - win2012-x86-1

```
04:27:30  jvm.dll preloadLibrary: LoadLibrary(F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_OpenJDK11\openjdkbinary\j2sdk-image\bin\default\j9prt29.dll) error: 5af
04:27:30  jvm.dll failed to load: j9prt29 entrypoints not found
04:27:30  Error: Could not create the Java Virtual Machine.
04:27:30  Error: A fatal exception has occurred. Program will exit.
04:27:30  java.io.IOException: Cannot run program "F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_OpenJDK11\openjdkbinary\j2sdk-image\bin\java": CreateProcess error=1455, The paging file is too small for this operation to complete
04:27:30  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
04:27:30  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
04:27:30  	at JavaChild.<init>(JavaChild.java:74)
04:27:30  	at JavaChild.spawnJavaChild(JavaChild.java:196)
04:27:30  	at JavaChild.interpretCommands(JavaChild.java:388)
04:27:30  	at JavaChild.interpretCommands(JavaChild.java:322)
04:27:30  	at JavaChild.main(JavaChild.java:268)
04:27:30  Caused by: java.io.IOException: CreateProcess error=1455, The paging file is too small for this operation to complete
04:27:30  	at java.base/java.lang.ProcessImpl.create(Native Method)
04:27:30  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
04:27:30  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
04:27:30  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
04:27:30  	... 6 more
04:27:30  JVMJ9VM015W Initialization error for library j9jit29(11): cannot initialize JIT
```

**Comment by pshipton** [comment]
I expect https://github.com/eclipse-openj9/openj9/issues/14146 is related as well.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/172 - win2012-x86-10
MiniMix_aot_5m_0
```
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  2G requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/173/ - win2012-x86-11
MiniMix_aot_5m_0
```
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  2G requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Release_testList_0/16 - win2012-x86-10
MiniMix_aot_5m_0
```
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  2G requested
```

**Comment by pshipton** [comment]
Suspect the follow may be related if processes are left running.

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1/18/ - win2012-x86-2
cmdLineTester_classesdbgddrext_1 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1/18/functional_test_output.tar.gz
```
Testing: Run !dumpallromclasslinear 10
Test start time: 2021/12/19 03:27:20 Central Standard Time
Running command: F:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1/openjdkbinary/j2sdk-image\bin\jdmpview.exe -core j9core.dmp
Time spent starting: 0 milliseconds
***[TEST INFO 2021/12/19 03:47:20] ProcessKiller detected a timeout after 1200000 milliseconds!***
INFO: The current OS is 'Windows Server 2012 R2'. 'Debug on timeout' is currently only supported on Linux.
***[TEST INFO 2021/12/19 03:47:20] executing kill -ABRT 8256***
***[TEST INFO 2021/12/19 03:47:20] kill -ABRT signal sent***
***[TEST INFO 2021/12/19 03:52:20] ABRT timed out***
***[TEST INFO 2021/12/19 03:52:20] executing kill -9 8256***
***[TEST INFO 2021/12/19 03:52:20] kill -9 signal sent***
***[TEST INFO 2021/12/19 03:52:20] ProcessKiller destroy test process after timeout***
***[TEST INFO 2021/12/19 03:52:20] stdout timed out***
Time spent executing: 1500204 milliseconds
Test result: FAILED



Testing: Run !dumpallramclasslinear 10
Test start time: 2021/12/19 03:52:20 Central Standard Time
Running command: F:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1/openjdkbinary/j2sdk-image\bin\jdmpview.exe -core j9core.dmp
Time spent starting: 0 milliseconds
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2021/12/19 03:52:50 - please wait.
JVMDUMP032I JVM requested System dump using 'F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\core.20211219.035250.6764.0001.dmp' in response to an event
JVMDUMP010I System dump written to F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\core.20211219.035250.6764.0001.dmp
JVMDUMP032I JVM requested Heap dump using 'F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\heapdump.20211219.035250.6764.0002.phd' in response to an event
JVMDUMP010I Heap dump written to F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\heapdump.20211219.035250.6764.0002.phd
JVMDUMP032I JVM requested Java dump using 'F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\javacore.20211219.035250.6764.0003.txt' in response to an event
JVMDUMP010I Java dump written to F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\javacore.20211219.035250.6764.0003.txt
JVMDUMP032I JVM requested Snap dump using 'F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\Snap.20211219.035250.6764.0004.trc' in response to an event
JVMDUMP010I Snap dump written to F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Release_testList_1\aqa-tests\TKG\output_16399059777391\cmdLineTester_classesdbgddrext_1\Snap.20211219.035250.6764.0004.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
Exception in thread "Thread-20" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3568)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:228)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:582)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:175)
	at Test$StreamMatcher.run(Test.java:488)
***[TEST INFO 2021/12/19 03:53:30] stderr timed out***
***[TEST INFO 2021/12/19 03:54:00] destroy test process after timeout***
Time spent executing: 99531 milliseconds
Test result: PASSED
```

**Comment by JasonFengJ9** [comment]
Observed at `job/Test_openjdk8_j9_extended.system_x86-32_windows_testList_1/34/`(`win16x64rt3-10`)
```
openjdk version "1.8.0_322"
IBM Semeru Runtime Open Edition (build 1.8.0_322-b04)
Eclipse OpenJ9 VM (build master-ca2a78c3b, JRE 1.8.0 Windows Server 2016 x86-32-Bit 20211218_261 (JIT enabled, AOT enabled)
OpenJ9   - ca2a78c3b
OMR      - 7589ce438
JCL      - c74851c6 based on jdk8u322-b04)

[2021-12-18T06:00:04.785Z] variation: NoOptions
[2021-12-18T06:00:06.727Z] JVM_OPTIONS:  

[2021-12-18T06:00:15.604Z] STF 01:00:14.446 - Monitoring processes: LT 
[2021-12-18T06:00:15.604Z] LT  stderr JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  2G requested
[2021-12-18T06:00:15.604Z] LT  stderr Error: Could not create the Java Virtual Machine.
[2021-12-18T06:00:15.604Z] LT  stderr Error: A fatal exception has occurred. Program will exit.
[2021-12-18T06:00:15.604Z] STF 01:00:14.645 - **FAILED** Process LT  ended with exit code (1) and not the expected exit code/s (0)

[2021-12-18T06:00:15.604Z] MiniMix_aot_5m_0_FAILED
```

**Comment by pshipton** [comment]
@Mesbah-Alam have there been any recent changes to the MiniMix_aot_5m test?

**Comment by Mesbah-Alam** [comment]
MiniMix_aot_5m is a new test, [added last week](https://github.com/adoptium/aqa-tests/pull/3178). 

FYI @llxia.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/174/

**Comment by Mesbah-Alam** [comment]
```
STF 00:08:15.568 - ==================   G E N E R A T I O N   ==================
STF 00:08:15.571 - Checking JVM: F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/openjdkbinary/j2sdk-image
STF 00:08:15.571 - Starting process to generate scripts: F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java -Xmx3g -Xms3g -Dlog4j.skipJansi=true -Djava.system.class.loader=net.adoptopenjdk.stf.runner.StfClassLoader -classpath F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/aqa-tests///..//jvmtest\system\otherLoadTest/../\systemtest_prereqs/log4j/log4j-api.jar;F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/aqa-tests///..//jvmtest\system\otherLoadTest/../\systemtest_prereqs/log4j/log4j-core.jar;F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/jvmtest/system/STF/stf.core/scripts/../bin net.adoptopenjdk.stf.runner.StfRunner -properties "F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/aqa-tests/\TKG\output_16400668861943\MiniMix_aot_5m_0/20211221-000815-MixedLoadTest/stf_parameters.properties, , F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/jvmtest/system/STF/stf.core/config/stf.properties" -testDir "F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_0/aqa-tests/\TKG\output_16400668861943\MiniMix_aot_5m_0/20211221-000815-MixedLoadTest"
GEN stderr JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  3G requested
GEN stderr Error: Could not create the Java Virtual Machine.
GEN stderr Error: A fatal exception has occurred. Program will exit.
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly/178/tapResults/


The problem seems to occur only on JDK 8 x86-32 bit Windows. The test works fine on x64 on [8](https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly/179/tapResults/), [11](https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/178/tapResults/), [17](https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly/121/tapResults/).

**Comment by pshipton** [comment]
The MiniMix_aot_5m_0 failure occurs all the time so I'm not going to keep reporting the individual failures.

**Comment by Mesbah-Alam** [comment]
> The MiniMix_aot_5m_0 failure occurs all the time ..

The failure is not seen on x64 bit Windows builds : 

1) 8 : https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly/182
2) 11 : https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/181
3) 17 : https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly/124

The only place it is occurring is x86-32 bit Windows, e.g., https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly/181, with : 

```
stderr JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  2G requested
```

Does this indicate a real issue? 

https://github.com/adoptium/aqa-tests/pull/3193 - this PR will disable the test on Windows 32 bit.

**Comment by pshipton** [comment]
> Does this indicate a real issue?

It indicates a problem with the test. The test is trying to use a bigger object heap than is available on the 32-bit systems.
