### ISSUE TITLE
Jep389Tests_testClinkerFfi_0 Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.HashMap.get(java.lang.Object)" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14169]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_OMR_testList_1/23
Jep389Tests_testClinkerFfi_0
```
FAILED: test_addShortAndShortFromPointer_1
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.HashMap.get(java.lang.Object)" is null
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.generateAdapter(ProgrammableInvoker.java:291)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<init>(ProgrammableInvoker.java:261)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:332)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:133)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:44)
	at org.openj9.test.jep389.downcall.PrimitiveTypeTests1.test_addShortAndShortFromPointer_1(PrimitiveTypeTests1.java:201)

FAILED: test_generateNewCharFromPointer_2
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.HashMap.get(java.lang.Object)" is null
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.generateAdapter(ProgrammableInvoker.java:291)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<init>(ProgrammableInvoker.java:261)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:332)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:133)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:50)
	at org.openj9.test.jep389.downcall.PrimitiveTypeTests2.test_generateNewCharFromPointer_2(PrimitiveTypeTests2.java:114)

FAILED: test_addShortAndShortFromPointer_3
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.HashMap.get(java.lang.Object)" is null
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.generateAdapter(ProgrammableInvoker.java:291)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<init>(ProgrammableInvoker.java:261)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:332)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:133)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at org.openj9.test.jep389.downcall.PrimitiveTypeTests3.test_addShortAndShortFromPointer_3(PrimitiveTypeTests3.java:202)

FAILED: test_generateNewCharFromPointer_3
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.HashMap.get(java.lang.Object)" is null
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.generateAdapter(ProgrammableInvoker.java:291)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.<init>(ProgrammableInvoker.java:261)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:332)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:133)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at org.openj9.test.jep389.downcall.PrimitiveTypeTests3.test_generateNewCharFromPointer_3(PrimitiveTypeTests3.java:114)
```

**Comment by ChengJin01** [comment]
It looks like the problem came from from the hashtable for the function descriptor we used as a transit solution for code in phase 1 (primitive support) which will be totally replaced with the hash of the simplified signature string (struct support: phase 2 &3) via https://github.com/eclipse-openj9/openj9/pull/13315. Need to check to see what we can do to work around if the issue still exists.

**Comment by ChengJin01** [comment]
It turns out the problem never happens on my local machine (Ubuntu/x86_64) and Aarch64. Will try the failing machine to see how it goes.

**Comment by pshipton** [comment]
Yes, it's intermittent. Didn't occur in the nightly builds, just seen once so far in the OMR build (but unrelated to OMR change).

**Comment by pshipton** [comment]
It's the intermittent nature that makes me think this is a JIT issue.

**Comment by ChengJin01** [comment]
We do have a temp fix (directly use the code for JDK18)  at /jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java
```
	private void generateAdapter() {

			/*[IF JAVA_SPEC_VERSION >= 18]*/
			int funcSigHash = funcMethodType.hashCode();
			int argTypesHash = argTypes.hashCode();
			/*[ELSE] JAVA_SPEC_VERSION >= 18 */
			int funcSigHash = funcDescriptor.hashCode();
			int argTypesHash = argLayouts.hashCode(); <---- can replaced with argTypes.hashCode() in JDK17
			/*[ENDIF] JAVA_SPEC_VERSION >= 18 */
```
But if we confirm the test always passes with JIT off, then JIT need to look at what happens in there because the existing code is correct in terms of logic.

**Comment by ChengJin01** [comment]
I tried many times by manually running test suite on the failing machine at https://openj9-jenkins.osuosl.org/computer/cent7-x64-4/ but it always passed with JIT on/off.   Also I didn't find any thing incorrect in the existing code in hashing the arguments in cache (if the cif address is non-null, . So it is likely that the hash calculation based on the MemoryLayout is unpredictable as compared to that of MethodType due to some reason (e.g. JIT).

We can temporarily replaced with the code used in JDK18 as above given the code there will be totally replaced with a complete solution with struct support via https://github.com/eclipse-openj9/openj9/pull/13315.
