### ISSUE TITLE
DaaLoadTest_all_special_5m_0_FAILED : testFailure: testRandomLongSixteenHexDigits(net.openj9.test.binaryData.TestLong2ByteArray): java.lang.ClassCastException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14175]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_special.system_ppc64le_linux_testList_0/167/`(`p10rhel053 `):
```
java version "11.0.14-beta" 2022-01-18
IBM Semeru Runtime Certified Edition 11.0.14+6-202112160206 (build 11.0.14-beta+6-202112160206)
Eclipse OpenJ9 VM 11.0.14+6-202112160206 (build master-31c72bd4c, JRE 11 Linux ppc64le-64-Bit Compressed References 20211215_233 (JIT enabled, AOT enabled)
OpenJ9   - 31c72bd4c
OMR      - 5a958d708
JCL      - b54baa6907 based on jdk-11.0.14+6)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=DaaLoadTest_all_special_5m_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_special.system_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F233%2Fibm-semeru-certified-debugimage_ppc64le_linux_JDK11U_2021-12-16-02-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F233%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK11U_2021-12-16-02-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F233%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK11U_2021-12-16-02-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F233%2Fibm-semeru-certified-jre_ppc64le_linux_JDK11U_2021-12-16-02-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=176&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-12-16T03:34:32.247Z] variation: Mode101
[2021-12-16T03:34:32.247Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs 

[2021-12-16T03:35:00.471Z] DLT 22:34:59.076 - Test failed
[2021-12-16T03:35:00.471Z] DLT   Failure num.  = 1
[2021-12-16T03:35:00.471Z] DLT   Test number   = 36
[2021-12-16T03:35:00.471Z] DLT   Test details  = 'JUnit[net.openj9.test.binaryData.TestLong2ByteArray]'
[2021-12-16T03:35:00.471Z] DLT   Suite number  = 0
[2021-12-16T03:35:00.471Z] DLT   Thread number = 10
[2021-12-16T03:35:00.471Z] DLT >>> Captured test output >>>

[2021-12-16T03:35:00.472Z] DLT testFailure: testRandomLongSixteenHexDigits(net.openj9.test.binaryData.TestLong2ByteArray): java.lang.ClassCastException@9709c0af
[2021-12-16T03:35:00.472Z] DLT java.lang.IllegalArgumentException: java.lang.ClassCastException@9709c0af
[2021-12-16T03:35:00.472Z] DLT 	at jdk.internal.reflect.GeneratedMethodAccessor1858.invoke(Unknown Source)
[2021-12-16T03:35:00.472Z] DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-16T03:35:00.472Z] DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2021-12-16T03:35:00.472Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2021-12-16T03:35:00.472Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2021-12-16T03:35:00.472Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2021-12-16T03:35:00.472Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-16T03:35:00.472Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-16T03:35:00.472Z] DLT 	at java.base/java.lang.Thread.run(Thread.java:866)
```

**Comment by knn-k** [comment]
I ran DaaLoadTest_all_special_5m_0 on ppc64le_linux 100 times in total (internal Grinder jobs 36688 and 36730), and got no failures.
I was trying to know if #15578 is a dup of this issue or not.

**Comment by knn-k** [comment]
https://github.com/eclipse-openj9/openj9/issues/15578#issuecomment-2145976460 is another example of "IllegalArgumentException: object is not an instance of declaring class" on ppc64le Linux.
