### ISSUE TITLE
cmdLineTest_gpTest_0 Testing: abort  timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14187]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Release_testList_1/15 - ub16-ppcle-1
cmdLineTest_gpTest_0 `NoOptions`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Release_testList_1/15/functional_test_output.tar.gz
```
Testing: abort  
Test start time: 2021/12/19 10:06:40 Coordinated Universal Time
Running command: "/home/jenkins/jenkins-agent/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Release_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xdump:system:none -cp "/home/jenkins/jenkins-agent/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Release_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest   abort
Time spent starting: 13 milliseconds
***[TEST INFO 2021/12/19 10:11:40] ProcessKiller detected a timeout after 300000 milliseconds!***
INFO: Cannot find '/usr/bin/gdb' using 'gdb' from the path.
***[TEST INFO 2021/12/19 10:11:40] executing gdb -batch -x /tmp/debugger12332377266386398869.txt /home/jenkins/jenkins-agent/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Release_testList_1/openjdkbinary/j2sdk-image/bin/java 16676***
java.io.IOException: Cannot run program "gdb": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:697)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:646)
	at Test$ProcessKiller.run(Test.java:596)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 6 more
***[TEST INFO 2021/12/19 10:11:40] executing kill -ABRT 16676***
***[TEST INFO 2021/12/19 10:11:40] kill -ABRT signal sent***
***[TEST INFO 2021/12/19 10:16:40] ABRT timed out***
***[TEST INFO 2021/12/19 10:16:40] executing kill -9 16676***
***[TEST INFO 2021/12/19 10:16:40] kill -9 signal sent***
***[TEST INFO 2021/12/19 10:16:40] ProcessKiller destroy test process after timeout***
Output from test:
 [OUT] Invoking abort!
 [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2021/12/19 10:06:40 - please wait.
 [ERR] JVMDUMP032I JVM requested Java dump using '/home/jenkins/jenkins-agent/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Release_testList_1/aqa-tests/TKG/output_16399028828390/cmdLineTest_gpTest_0/javacore.20211219.100640.16676.0001.txt' in response to an event
Time spent executing: 1094177 milliseconds
Test result: FAILED
Output from test:
```

**Comment by pshipton** [comment]
[internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=55793689)
[aix_ppc-64] SE80_GIT cmdLineTest_gpTest_0
aix72p9-02
```
Testing: abort thread
Test start time: 2023/03/15 13:12:59 Eastern Standard Time
Running command: "bld_47408/sdk/ap6480/bin/java"   -Xdump:system:none -cp "/bluebird/builds/bld_47408/jvmtest/test/SE80/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest thread abort
Time spent starting: 20 milliseconds
***[TEST INFO 2023/03/15 13:17:59] ProcessKiller detected a timeout after 300000 milliseconds!***
INFO: The current OS is 'AIX'. 'Debug on timeout' is currently only supported on Linux.
***[TEST INFO 2023/03/15 13:17:59] executing kill -ABRT 17629456***
***[TEST INFO 2023/03/15 13:17:59] kill -ABRT signal sent***
Time spent executing: 304831 milliseconds
Test result: FAILED
Output from test:
 [OUT] Invoking abort!
 [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2023/03/15 13:12:59 - please wait.
 [ERR] JVMDUMP032I JVM requested Java dump using '/tmp/bld_47408/cmdLineTest_gpTest_0/javacore.20230315.131259.17629456.0001.txt' in response to an event
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_0/525
cmdLineTest_gpTest_0
```
Testing: abort  
Test start time: 2023/08/11 03:24:40 Coordinated Universal Time
Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java"   -Xdump:system:none -cp "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest   abort
Time spent starting: 7 milliseconds
Time spent executing: 419 milliseconds
Test result: FAILED
Output from test:
 [OUT] Invoking abort!
 [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2023/08/11 03:24:40 - please wait.
 [ERR] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16917207284359/cmdLineTest_gpTest_0/javacore.20230811.032440.27066852.0001.txt' in response to an event
 [ERR] 
 [ERR] 
 [ERR] *** Invalid JIT return address 00000000300BA968 in 00000100100948E0
 [ERR] 
>> Success condition was found: [Output match: Processing dump event "abort"]
>> Required condition was not found: [Output match: Processed dump event "abort"]
```
