### ISSUE TITLE
HCRLateAttachWorkload_0 testGlobalTreeMap OutOfMemoryError: Array capacity exceeded

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14202]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_1/182 - rh7-390-2
HCRLateAttachWorkload_0 `-XX:+UseCompressedOops`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_1/182/system_test_output.tar.gz
```
LT  testStarted : testGlobalTreeMap(net.adoptopenjdk.test.util.treemap.TreeMapTest)
LT  testFailure: testGlobalTreeMap(net.adoptopenjdk.test.util.treemap.TreeMapTest): Array capacity exceeded
LT  java.lang.OutOfMemoryError: Array capacity exceeded
LT  	at java.lang.StringBuilder.append(StringBuilder.java:559)
LT  	at net.adoptopenjdk.test.util.treemap.TreeMapTest.checkOrdered(TreeMapTest.java:137)
LT  	at net.adoptopenjdk.test.util.treemap.TreeMapTest.testGlobalTreeMap(TreeMapTest.java:70)
```

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by pshipton** [comment]
This seems familiar but I don't find any issue which duplicates this.

**Comment by pshipton** [comment]
Seems it has nothing to do with GC.

**Comment by dmitripivkine** [comment]
Also there is this error:
```
cat ./aqa-tests/TKG/output_16403159565749/HCRLateAttachWorkload_0/20211223-230035-HCRLateAttachWorkload/results/2.AG.stderr
Exception in thread "main" java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:134)
	at openj9.internal.tools.attach.target.AttachmentConnection.streamSend(AttachmentConnection.java:105)
	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.detach(OpenJ9VirtualMachine.java:200)
	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:85)
```
