### ISSUE TITLE
JDK18 java/util/Properties/PropertiesStoreTest.java & StoreReproducibilityTest.java failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14226]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_sanity.openjdk_aarch64_linux_Personal/1/consoleFull`(`ub18-aarch64-5`):
```
14:53:38  openjdk version "18-internal" 2022-03-22
14:53:38  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDK18aarch64linuxPersonal)
14:53:38  Eclipse OpenJ9 VM (build master-3cf0509e7e0, JRE 18 Linux aarch64-64-Bit Compressed References 20220105_1 (JIT enabled, AOT enabled)
14:53:38  OpenJ9   - 3cf0509e7e0
14:53:38  OMR      - b5643d01920
14:53:38  JCL      - 03a0ab353e1 based on jdk-18+29)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_aarch64_linux_Personal%2F1%2FOpenJ9-JDK18-aarch64_linux-20220105-143040.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_aarch64_linux_Personal%2F1%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=18&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk18.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=3cf0509e7e001405e2caaa8126282833b542ff40&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:25:26  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
15:25:26  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

15:32:54  --------------------------------------------------
15:32:54  TEST: java/util/Properties/PropertiesStoreTest.java

15:32:54  test PropertiesStoreTest.testStoreOutputStreamDateComment(): failure
15:32:54  java.lang.AssertionError: Unexpected date comment: Wed Jan 05 15:32:41 EST 2022
15:32:54  	at org.testng.Assert.fail(Assert.java:87)
15:32:54  	at PropertiesStoreTest.testDateComment(PropertiesStoreTest.java:204)
15:32:54  	at PropertiesStoreTest.testStoreOutputStreamDateComment(PropertiesStoreTest.java:178)
15:32:54  	at java.lang.invoke.LambdaForm$DMH/0x0000000098066cf0.invokeVirtual(LambdaForm$DMH)
15:32:54  	at java.lang.invoke.LambdaForm$MH/0x0000000008107a30.invoke(LambdaForm$MH)
15:32:54  	at java.base/java.lang.invoke.LambdaForm$MH/0x00000000981ea3b0.invokeExact_MT(LambdaForm$MH)
15:32:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
15:32:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
15:32:54  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
15:32:54  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
15:32:54  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
15:32:54  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
15:32:54  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
15:32:54  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
15:32:54  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
15:32:54  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
15:32:54  	at org.testng.TestRunner$$Lambda$129/0x00000000080d16e8.accept(Unknown Source)
15:32:54  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
15:32:54  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
15:32:54  	at org.testng.TestRunner.run(TestRunner.java:585)
15:32:54  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
15:32:54  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
15:32:54  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
15:32:54  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
15:32:54  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
15:32:54  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
15:32:54  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
15:32:54  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
15:32:54  	at org.testng.TestNG.runSuites(TestNG.java:1069)
15:32:54  	at org.testng.TestNG.run(TestNG.java:1037)
15:32:54  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
15:32:54  	at java.lang.invoke.LambdaForm$DMH/0x0000000008016640.invokeStatic(LambdaForm$DMH)
15:32:54  	at java.lang.invoke.LambdaForm$MH/0x00000000080190d0.invoke(LambdaForm$MH)
15:32:54  	at java.lang.invoke.LambdaForm$MH/0x000000000801b4a0.invokeExact_MT(LambdaForm$MH)
15:32:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:156)
15:32:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
15:32:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
15:32:54  	at java.base/java.lang.Thread.run(Thread.java:884)
15:32:54  Caused by: java.time.format.DateTimeParseException: Text 'Wed Jan 05 15:32:41 EST 2022' could not be parsed at index 0
15:32:54  	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2056)
15:32:54  	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1884)
15:32:54  	at PropertiesStoreTest.testDateComment(PropertiesStoreTest.java:202)
15:32:54  	... 38 more

15:32:54  --------------------------------------------------
15:32:54  TEST: java/util/Properties/StoreReproducibilityTest.java

15:32:54  java.lang.RuntimeException: Unexpected date Wed Jan 05 15:32:53 EST 2022 in stored properties /tmp/823164012958550475994893907.props
15:32:54  	at StoreReproducibilityTest.assertCurrentDate(StoreReproducibilityTest.java:431)
15:32:54  	at StoreReproducibilityTest.testEmptySysPropValue(StoreReproducibilityTest.java:256)
15:32:54  	at StoreReproducibilityTest.main(StoreReproducibilityTest.java:71)
15:32:54  	at java.lang.invoke.LambdaForm$DMH/0x000000008426d610.invokeStatic(LambdaForm$DMH)
15:32:54  	at java.lang.invoke.LambdaForm$MH/0x00000000ec0115e0.invoke(LambdaForm$MH)
15:32:54  	at java.lang.invoke.LambdaForm$MH/0x00000000ec011b00.invokeExact_MT(LambdaForm$MH)
15:32:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
15:32:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:32:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
15:32:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
15:32:54  	at java.base/java.lang.Thread.run(Thread.java:884)
15:32:54  
15:32:54  JavaTest Message: Test threw exception: java.lang.RuntimeException

15:46:14  Test results: passed: 894; failed: 2
15:46:25  
15:46:25  jdk_util_0_FAILED
```

**Comment by tajila** [comment]
This passes with the changes here, https://github.com/eclipse-openj9/openj9/pull/14357. Not sure if that PR actually fixes it, or if it was fixed before

**Comment by tajila** [comment]
@JasonFengJ9 These tests pass with the latest changes, can you please close

**Comment by tajila** [comment]
Also, if tests were excluded please unexclude

**Comment by JasonFengJ9** [comment]
Thanks for triage & fix, these tests weren't excluded.

Closing..

**Comment by JasonFengJ9** [comment]
The failures are seen in an internal build `job/Test_openjdk18_j9_sanity.openjdk_aarch64_linux_testList_1/4/`(`ub18-aarch64-8`)
```
openjdk version "18-ea" 2022-03-22
IBM Semeru Runtime Open Edition 18.0.0.0 (build 18-ea+32)
Eclipse OpenJ9 VM 18.0.0.0 (build master-5e9bd4ea0, JRE 18 Linux aarch64-64-Bit Compressed References 20220127_21 (JIT enabled, AOT enabled)
OpenJ9   - 5e9bd4ea0
OMR      - 4a009d2fe
JCL      - 0764ffcb69 based on jdk-18+32)
```

```
[2022-01-27T03:59:46.858Z] STDOUT:
[2022-01-27T03:59:46.858Z] test PropertiesStoreTest.testStoreOutputStreamDateComment(): failure
[2022-01-27T03:59:46.858Z] java.lang.AssertionError: Unexpected date comment: Wed Jan 26 22:59:42 EST 2022
[2022-01-27T03:59:46.858Z] 	at org.testng.Assert.fail(Assert.java:87)
[2022-01-27T03:59:46.858Z] 	at PropertiesStoreTest.testDateComment(PropertiesStoreTest.java:204)
[2022-01-27T03:59:46.858Z] 	at PropertiesStoreTest.testStoreOutputStreamDateComment(PropertiesStoreTest.java:178)
[2022-01-27T03:59:46.858Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-01-27T03:59:46.858Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-01-27T03:59:46.858Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-01-27T03:59:46.858Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-01-27T03:59:46.858Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-01-27T03:59:46.858Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-01-27T03:59:46.858Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-01-27T03:59:46.858Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-01-27T03:59:46.858Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-01-27T03:59:46.858Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-01-27T03:59:46.858Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-01-27T03:59:46.858Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-01-27T03:59:46.858Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-01-27T03:59:46.858Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-01-27T03:59:46.858Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-01-27T03:59:46.858Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-01-27T03:59:46.858Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-01-27T03:59:46.858Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-01-27T03:59:46.858Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-01-27T03:59:46.858Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-01-27T03:59:46.858Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2022-01-27T03:59:46.858Z] Caused by: java.time.format.DateTimeParseException: Text 'Wed Jan 26 22:59:42 EST 2022' could not be parsed at index 0
[2022-01-27T03:59:46.858Z] 	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2056)
[2022-01-27T03:59:46.858Z] 	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1884)
[2022-01-27T03:59:46.858Z] 	at PropertiesStoreTest.testDateComment(PropertiesStoreTest.java:202)
[2022-01-27T03:59:46.858Z] 	... 29 more

[2022-01-27T03:59:52.684Z] java.lang.RuntimeException: Unexpected date Wed Jan 26 22:59:51 EST 2022 in stored properties /tmp/823164015211185369302880833.props
[2022-01-27T03:59:52.684Z] 	at StoreReproducibilityTest.assertCurrentDate(StoreReproducibilityTest.java:431)
[2022-01-27T03:59:52.684Z] 	at StoreReproducibilityTest.testEmptySysPropValue(StoreReproducibilityTest.java:256)
[2022-01-27T03:59:52.684Z] 	at StoreReproducibilityTest.main(StoreReproducibilityTest.java:71)
[2022-01-27T03:59:52.684Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-01-27T03:59:52.684Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-01-27T03:59:52.684Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-01-27T03:59:52.684Z] 	at java.base/java.lang.Thread.run(Thread.java:884)
[2022-01-27T03:59:52.684Z] 
[2022-01-27T03:59:52.684Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
```

`OpenJ9 -5e9bd4ea0` seems contain https://github.com/eclipse-openj9/openj9/pull/14357 specified at https://github.com/eclipse-openj9/openj9/issues/14226#issuecomment-1021573266

Re-open for further investigation.

**Comment by tajila** [comment]
@mikezhang1234567890 Can you please take a look at this

**Comment by mikezhang1234567890** [comment]
Also fails on the early access reference jdk18 implementation I tried.

The test uses the format string `private static final String DATE_FORMAT_PATTERN = "EEE MMM dd HH:mm:ss zzz uuuu"` and checks if the data format in the properties file matches that format.

But if you do something like:
```Java
ZonedDateTime t = ZonedDateTime.now();
String t_str = t.format(DateTimeFormatter.ofPattern(DATE_FORMAT_PATTERN));
System.out.println("formatted time: " + t_str);
```
The output for both OpenJ9 and reference implementation is `Tue. Feb. 01 13:55:58 EST 2022` with periods after short form of the day and month names. I think `DateTimeFormatter` expects those periods to be there while the date comment in the properties file doesn't have it. Exception is:
`java.time.format.DateTimeParseException: Text 'Tue Feb 01 13:55:58 EST 2022' could not be parsed at index 0`

The [docs](https://download.java.net/java/early_access/jdk18/docs/api/java.base/java/time/format/DateTimeFormatter.html) don't seem to mention periods though.

I think we should exclude this test until this issue is resolved upstream.

**Comment by mikezhang1234567890** [comment]
Rather than platform it looks like the difference is from the locale. The test fails when when locale is `en_CA` rather than `en_US` and the formatting of the date string is slightly different as mentioned above.

In this case it looks like the test run is inheriting the `en_CA` locale and thus failing. If we set locale manually with JVM args that would fix the test.

**Comment by pshipton** [comment]
> In this case it looks like the test run is inheriting the en_CA locale

Meaning the machine(s) are setup to use en_CA by default? We should request the machines be modified rather than changing the OpenJDK test. You can create an internal infra issue.

**Comment by JasonFengJ9** [comment]
Assuming this is an infra issue, moving out of milestone plan.

**Comment by pshipton** [comment]
It is a test issue. I'm seeing it pop up on the open machines as well. First I'll collect some info about which machines. Maybe it's better to update/patch the OpenJDK test than to find and update all the machines.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_Release/1 - ub16p8j94

**Comment by pshipton** [comment]
@mikezhang1234567890 pls check what's involved to update the test to add the command line option(s). I assume `-Duser.language=en -Duser.country=US` is the fix, and hopefully just needs to be added to the `@run` line, i.e. `@run testng -Duser.language=en -Duser.country=US PropertiesStoreTest`.

**Comment by mikezhang1234567890** [comment]
For `PropertiesStoreTest.java` it looks like we can just add the options to the `@run` tag. For `StoreReproducibilityTest.java` it doesn't look like we can since `@run driver` doesn't seem to support adding VM opts per https://openjdk.java.net/jtreg/tag-spec.html. However, there's only 1 location where it's trying to parse the date, so I believe we can just set the correct locale for the  DateTimeFormatter used there.

**Comment by mikezhang1234567890** [comment]
Should I also create the PR for jdknext? @pshipton
