### ISSUE TITLE
JDK18 MacOS java/lang/System/MacEncoding/MacJNUEncoding.java - RuntimeException: Expected to get exit value of [0]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14233]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_sanity.openjdk_x86-64_mac_Personal/1/consoleFull`:
```
14:57:53  openjdk version "18-internal" 2022-03-22
14:57:53  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDK18x86-64macPersonal)
14:57:53  Eclipse OpenJ9 VM (build master-3cf0509e7e0, JRE 18 Mac OS X amd64-64-Bit Compressed References 20220105_1 (JIT enabled, AOT enabled)
14:57:53  OpenJ9   - 3cf0509e7e0
14:57:53  OMR      - b5643d01920
14:57:53  JCL      - 03a0ab353e1 based on jdk-18+29)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_x86-64_mac_Personal%2F1%2FOpenJ9-JDK18-x86-64_mac-20220105-142943.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_x86-64_mac_Personal%2F1%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=18&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk18.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=3cf0509e7e001405e2caaa8126282833b542ff40&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:14:24  --------------------------------------------------
15:15:22  TEST: java/lang/System/MacEncoding/MacJNUEncoding.java

15:15:22  java.lang.RuntimeException: Expected to get exit value of [0]
15:15:22  
15:15:22  	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
15:15:22  	at MacJNUEncoding.main(MacJNUEncoding.java:65)
15:15:22  	at java.lang.invoke.LambdaForm$DMH/0x0000000023039420.invokeStatic(LambdaForm$DMH)
15:15:22  	at java.lang.invoke.LambdaForm$MH/0x00000000230f0820.invoke(LambdaForm$MH)
15:15:22  	at java.base/java.lang.invoke.LambdaForm$MH/0x00000000230e3620.invokeExact_MT(LambdaForm$MH)
15:15:22  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
15:15:22  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:15:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
15:15:22  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
15:15:22  	at java.base/java.lang.Thread.run(Thread.java:884)
15:15:22  
15:15:22  JavaTest Message: Test threw exception: java.lang.RuntimeException
15:15:22  JavaTest Message: shutting down test
15:15:22  
15:15:22  
15:15:22  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
```

```
15:15:22  --------------------------------------------------
15:15:22  TEST: java/lang/System/MacEncoding/TestFileEncoding.java

15:15:22  STDERR:
15:15:22  java.lang.RuntimeException: TEST FAILED: !tr.isOK()
15:15:22  	at TestFileEncoding.checkResult(TestFileEncoding.java:151)
15:15:22  	at TestFileEncoding.run(TestFileEncoding.java:126)
15:15:22  	at TestFileEncoding.main(TestFileEncoding.java:170)
15:15:22  	at java.lang.invoke.LambdaForm$DMH/0x0000000053061020.invokeStatic(LambdaForm$DMH)
15:15:22  	at java.lang.invoke.LambdaForm$MH/0x000000004e090c20.invoke(LambdaForm$MH)
15:15:22  	at java.lang.invoke.LambdaForm$MH/0x000000004e0a9e20.invokeExact_MT(LambdaForm$MH)
15:15:22  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
15:15:22  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:15:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
15:15:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:15:22  	at java.base/java.lang.Thread.run(Thread.java:884)
15:15:22  
15:15:22  JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: !tr.isOK()
```

`15:16:29  jdk_lang_1_FAILED`

This seems related to https://github.com/eclipse-openj9/openj9/issues/13470.

**Comment by JasonFengJ9** [comment]
`java/lang/System/FileEncodingTest.java` need to be re-included after https://github.com/eclipse-openj9/openj9/pull/14285 merging.
