### ISSUE TITLE
ClassLoader/nativeLibrary/NativeLibraryTest.java re-enabled failing: should fail to load the native library by another class loader

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14351]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/197/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly/78/
all platforms
jdk_lang
java/lang/ClassLoader/nativeLibrary/NativeLibraryTest.java

Test was re-enable by https://github.com/adoptium/aqa-tests/pull/3255 so it's now running an failing on all platforms.

```
02:16:45  REASON: User specified action: run main/othervm/native -Xcheck:jni NativeLibraryTest 
02:16:45  TIME:   0.181 seconds
02:16:45  messages:
02:16:45  command: main -Xcheck:jni NativeLibraryTest
02:16:45  reason: User specified action: run main/othervm/native -Xcheck:jni NativeLibraryTest 
02:16:45  Mode: othervm [/othervm specified]
02:16:45  elapsed time (seconds): 0.181
02:16:45  configuration:
02:16:45  STDOUT:
02:16:45  STDERR:
02:16:45  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
02:16:45  java.lang.RuntimeException: should fail to load the native library by another class loader
02:16:45  	at NativeLibraryTest.runTest(NativeLibraryTest.java:91)
02:16:45  	at NativeLibraryTest.main(NativeLibraryTest.java:57)
02:16:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:16:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:16:45  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:16:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:16:45  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
02:16:45  	at java.base/java.lang.Thread.run(Thread.java:866)
```

@JasonFengJ9 can you pls take a look. This either needs to be fixed quickly or we'll need to re-exclude the test since it's now failing on all platforms.

**Comment by JasonFengJ9** [comment]
As per the test comment [1], this is a GC specific test.
```
  /*
     * Loads p.Test class with a new class loader and its static initializer
     * will load a native library.
     *
     * The class loader becomes unreachable when this method returns and
     * the native library should be unloaded at some point after the class
     * loader is garbage collected.
     */
```
I think it should be excluded until further triage finds otherwise.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/52406d9b07bdae60d9b622ff8d80067ecdee5764/test/jdk/java/lang/ClassLoader/nativeLibrary/NativeLibraryTest.java#L71-L78

**Comment by pshipton** [comment]
I don't have a problem excluding it (today so we can get green builds again). However I notice the test calls System.gc() only once, this may not be sufficient. I'll try updating the test to call System.gc() more times and see if that is a quick fix for the problem.
@dmitripivkine fyi

**Comment by pshipton** [comment]
Tried the following but it didn't help https://github.com/pshipton/openj9-openjdk-jdk11/commit/ae706604

https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/543/

**Comment by pshipton** [comment]
Not sure this is a GC issue, the error `should fail to load the native library by another class loader` seems to indicate a VM issue.

**Comment by pshipton** [comment]
Created exclude https://github.com/adoptium/aqa-tests/pull/3280

**Comment by JasonFengJ9** [comment]
> Not sure this is a GC issue, the error should fail to load the native library by another class loader seems to indicate a VM issue.

Didn't think it a gc problem, probably a test issue (to be triaged).
