### ISSUE TITLE
Adopt_J9_FeatureTests_0_FAILED - vmPropertiesPointToVendor & freetypeOnlyBundledOnCertainPlatforms

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14379]
Failure link
------------

From an internal build `job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9_SmokeTests/29/console`(`mac11x64rt12`):
```
00:02:22  openjdk version "1.8.0_322"
00:02:22  IBM Semeru Runtime Open Edition (build 1.8.0_322-b06)
00:02:22  Eclipse OpenJ9 VM (build openj9-0.30.0-rc1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20220125_305 (JIT enabled, AOT enabled)
00:02:22  OpenJ9   - f441547b8
00:02:22  OMR      - dac962a28
00:02:22  JCL      - 3273d1d5e1 based on jdk8u322-b06)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=%2Ftest%2Ffunctional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&JDK_VERSION=8&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Ftemurin-build&JDK_REPO=&RELEASE_TAG=v0.30.0-release&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=ibm&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&TRSS_URL=&BUILD_LIST=functional%2FbuildAndPackage&UPSTREAM_JOB_NUMBER=305&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
00:02:23  ===============================================
00:02:23  Running test Adopt_J9_FeatureTests_0 ...
00:02:23  ===============================================
00:02:23  variation: NoOptions
00:02:23  JVM_OPTIONS:  

00:02:24  FAILED: vmPropertiesPointToVendor
00:02:24  java.lang.AssertionError: expected [https://github.com/ibmruntimes/Semeru-Runtimes/issues] but found [null]
00:02:24  	at org.testng.Assert.fail(Assert.java:96)
00:02:24  	at org.testng.Assert.failNotEquals(Assert.java:776)
00:02:24  	at org.testng.Assert.assertEqualsImpl(Assert.java:132)
00:02:24  	at org.testng.Assert.assertEquals(Assert.java:118)
00:02:24  	at org.testng.Assert.assertEquals(Assert.java:453)
00:02:24  	at org.testng.Assert.assertEquals(Assert.java:463)
00:02:24  	at net.adoptium.test.VendorPropertiesTest$SemeruPropertiesChecks.javaVendorUrlBug(VendorPropertiesTest.java:244)
00:02:24  	at net.adoptium.test.VendorPropertiesTest.vmPropertiesPointToVendor(VendorPropertiesTest.java:105)
00:02:24  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:02:24  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:02:24  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:02:24  	at java.lang.reflect.Method.invoke(Method.java:498)
00:02:24  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
00:02:24  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
00:02:24  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
00:02:24  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
00:02:24  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:02:24  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
00:02:24  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
00:02:24  	at org.testng.TestRunner.run(TestRunner.java:505)
00:02:24  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
00:02:24  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
00:02:24  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
00:02:24  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
00:02:24  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:02:24  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
00:02:24  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
00:02:24  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
00:02:24  	at org.testng.TestNG.runSuites(TestNG.java:1049)
00:02:24  	at org.testng.TestNG.run(TestNG.java:1017)
00:02:24  	at org.testng.TestNG.privateMain(TestNG.java:1354)
00:02:24  	at org.testng.TestNG.main(TestNG.java:1323)
00:02:24  
00:02:24  FAILED: freetypeOnlyBundledOnCertainPlatforms
00:02:24  java.lang.AssertionError: Expected libfreetype.dylib to be bundled but it is not. expected [true] but found [false]
00:02:24  	at org.testng.Assert.fail(Assert.java:96)
00:02:24  	at org.testng.Assert.failNotEquals(Assert.java:776)
00:02:24  	at org.testng.Assert.assertTrue(Assert.java:44)
00:02:24  	at net.adoptium.test.BundledFreetypeTest.freetypeOnlyBundledOnCertainPlatforms(BundledFreetypeTest.java:77)
00:02:24  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:02:24  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:02:24  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:02:24  	at java.lang.reflect.Method.invoke(Method.java:498)
00:02:24  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
00:02:24  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
00:02:24  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
00:02:24  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
00:02:24  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:02:24  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
00:02:24  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
00:02:24  	at org.testng.TestRunner.run(TestRunner.java:505)
00:02:24  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
00:02:24  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
00:02:24  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
00:02:24  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
00:02:24  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:02:24  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
00:02:24  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
00:02:24  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
00:02:24  	at org.testng.TestNG.runSuites(TestNG.java:1049)
00:02:24  	at org.testng.TestNG.run(TestNG.java:1017)
00:02:24  	at org.testng.TestNG.privateMain(TestNG.java:1354)
00:02:24  	at org.testng.TestNG.main(TestNG.java:1323)
00:02:24  
00:02:24  
00:02:24  ===============================================
00:02:24      CommonFeatureTests
00:02:24      Tests run: 3, Failures: 2, Skips: 0
00:02:24  ===============================================

00:02:24  Adopt_J9_FeatureTests_0_FAILED
```

This is one of SmokeTests. 
fyi @llxia

**Comment by llxia** [comment]
For 0.30.0, the smoke tests for JDK11 and JDK17 are fine. We only see the issue with JDK8. For example:
job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9_SmokeTests/31/
job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9_SmokeTests/31/

internal issue for the overview: infrastructure/issues/6431

**Comment by JasonFengJ9** [comment]
`vmPropertiesPointToVendor` passed.
Tracking `freetypeOnlyBundledOnCertainPlatforms` failure at `backlog/issues/766`.
