### ISSUE TITLE
testRASAPI_0_FAILED OutOfMemoryError: Java heap space at java.lang.StringCoding.decodeUTF8_0(StringCoding.java:733)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14380]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_0/164/`(`paix820 `):
```
openjdk version "11.0.14" 2022-01-18
IBM Semeru Runtime Open Edition 11.0.14.0-rc1 (build 11.0.14+9)
Eclipse OpenJ9 VM 11.0.14.0-rc1 (build openj9-0.30.0-m3a, JRE 11 AIX ppc64-64-Bit Compressed References 20220125_305 (JIT enabled, AOT enabled)
OpenJ9   - bebfe6842
OMR      - dac962a28
JCL      - 3e0def07d2 based on jdk-11.0.14+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_ppc64_aix&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9%2F305%2Fibm-semeru-open-jre_ppc64_aix_11.0.14_9_openj9-0.30.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9%2F305%2Fibm-semeru-open-debugimage_ppc64_aix_11.0.14_9_openj9-0.30.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9%2F305%2Fibm-semeru-open-testimage_ppc64_aix_11.0.14_9_openj9-0.30.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9%2F305%2Fibm-semeru-open-jdk_ppc64_aix_11.0.14_9_openj9-0.30.0-rc1.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&USE_JRE=false&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&RELEASE_TAG=v0.30.0-release&OPENJ9_BRANCH=v0.30.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.30.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=201&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TKG_SHA=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=functional&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-01-26T16:10:52.629Z] Running test testRASAPI_0 ...
[2022-01-26T16:10:52.629Z] ===============================================

[2022-01-26T16:10:52.629Z] variation: NoOptions
[2022-01-26T16:10:52.629Z] JVM_OPTIONS:  

[2022-01-26T16:12:23.012Z]      [test]     [junit] Testcase: testSystemDumpNullFile took 56.126 sec
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	Caused an ERROR
[2022-01-26T16:12:23.012Z]      [test]     [junit] Java heap space
[2022-01-26T16:12:23.012Z]      [test]     [junit] java.lang.OutOfMemoryError: Java heap space
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:733)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at java.base/java.lang.StringCoding.decodeUTF8(StringCoding.java:725)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at java.base/java.lang.StringCoding.decode(StringCoding.java:237)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at java.base/java.lang.String.<init>(String.java:602)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.XCOFFReader._stringFromArray(XCOFFReader.java:162)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.XCOFFReader.getSymbols(XCOFFReader.java:303)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.AIXDumpReader.loadModule(AIXDumpReader.java:602)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.AIXDumpReader.readModules(AIXDumpReader.java:513)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.AIXDumpReader.readCore(AIXDumpReader.java:225)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.AIX64DumpReader.<init>(AIX64DumpReader.java:57)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.AIXDumpReader.getReaderForFile(AIXDumpReader.java:922)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.aix.AIXDumpReaderFactory.processDump(AIXDumpReaderFactory.java:44)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.corereaders.CoreReader.readCoreFile(CoreReader.java:108)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.j9ddr.view.dtfj.image.J9DDRImageFactory.getImage(J9DDRImageFactory.java:126)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.dtfj.image.j9.ImageFactory.foundImage(ImageFactory.java:418)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at openj9.dtfj/com.ibm.dtfj.image.j9.ImageFactory.getImage(ImageFactory.java:248)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPISuite.getContentType(DumpAPISuite.java:194)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPIBasicTests.testSystemDumpNullFile(DumpAPIBasicTests.java:929)
[2022-01-26T16:12:23.012Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-26T16:12:23.013Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-01-26T16:12:23.013Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-26T16:12:23.013Z]      [test]     [junit] 
[2022-01-26T16:12:23.013Z]      [test]     [junit] Testcase: testSystemDumpToDashFile took 0.504 sec
[2022-01-26T16:12:23.013Z]      [test]     [junit] Testcase: testSystemDumpWithSameFile took 8.929 sec
[2022-01-26T16:12:23.013Z]      [test] 
[2022-01-26T16:12:23.013Z]      [test] BUILD FAILED
[2022-01-26T16:12:23.013Z]      [test] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_0/jvmtest/functional/RasapiTest/test.xml:67: Test com.ibm.jvm.ras.tests.DumpAPIBasicTests failed
[2022-01-26T16:12:23.013Z]      [test] 
[2022-01-26T16:12:23.013Z]      [test] Total time: 1 minute 28 seconds
[2022-01-26T16:12:23.013Z] 
[2022-01-26T16:12:23.013Z] BUILD FAILED
[2022-01-26T16:12:23.013Z] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_0/jvmtest/functional/RasapiTest/test.xml:52: Java returned: 1
[2022-01-26T16:12:23.013Z] 
[2022-01-26T16:12:23.013Z] Total time: 1 minute 29 seconds
[2022-01-26T16:12:23.360Z] 
[2022-01-26T16:12:23.360Z] testRASAPI_0_FAILED
```

50x grinder - `job/Grinder/20440`

**Comment by pshipton** [comment]
This is a dup of https://github.com/eclipse-openj9/openj9/issues/14193 which fails every day on jdk11 and is under active investigation. Feel free to ignore the failures.
