### ISSUE TITLE
JITServer testServerComesUpAfterClientAndGoesDownAgain Failed to properly start server, it terminated prematurely with exit value: 1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14407]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/150 - cent7-x64-6
testJITServer_0 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/150/functional_test_output.tar.gz
```
[JITServerTest] [INFO] running testServerUnreachableForAWhile: INFO and above level logging enabled
[JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=45113, set JITServerTest_SERVER_PORT in your env to override.
[JITServerTest] [INFO] Starting server with command line:
/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/openjdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=45113
[JITServerTest] [INFO] With stdout/stderr redirected to:
/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/output_164371646467/testJITServer_0/testServerUnreachableForAWhile.server.out
[JITServerTest] [INFO] Starting client with command line:
/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/openjdkbinary/j2sdk-image/bin/java -XX:JITServerPort=45113 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../TKG/output_164371646467/testJITServer_0/client /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_x86-64,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all
[JITServerTest] [INFO] With stdout/stderr redirected to:
/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/output_164371646467/testJITServer_0/testServerUnreachableForAWhile.client.out
[JITServerTest] [INFO] Waiting for 45000 millis.
[JITServerTest] [INFO] Pausing server for 10000 millis.
[JITServerTest] [INFO] Resuming server...
[JITServerTest] [INFO] Waiting for 45000 millis.
[JITServerTest] [INFO] Stopping server...
[JITServerTest] [INFO] Waiting for 45000 millis.
[JITServerTest] [INFO] Stopping client...
PASSED: testServer
PASSED: testServerComesUpAfterClient
PASSED: testServerGoesDown
PASSED: testServerGoesDownAnotherComesUp
PASSED: testServerUnreachableForAWhile
FAILED: testServerComesUpAfterClientAndGoesDownAgain
java.lang.AssertionError: Failed to properly start server, it terminated prematurely with exit value: 1
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.startProcess(JITServerTest.java:217)
	at jit.test.jitserver.JITServerTest.testServerComesUpAfterClientAndGoesDownAgain(JITServerTest.java:423)
```

@mpirvu

**Comment by mpirvu** [comment]
Attn: @cjjdespres

**Comment by mpirvu** [comment]
@pshipton is this issue blocking omr acceptance by any chance?  I am seeing this: "Started by upstream project Pipeline-OMR-Acceptance"

**Comment by pshipton** [comment]
No it didn't block the acceptance. The only OMR change was AArch64 specific and these builds passed, so I manually promoted the OMR level.

**Comment by pshipton** [comment]
Another one here https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_OMR_testList_1/50
This stopped the OMR build from promoting automatically, but I'll manually promote.

**Comment by mpirvu** [comment]
Looking at the messages from the original failure:
```
[JITServerTest] [INFO] running testServerComesUpAfterClientAndGoesDownAgain: INFO and above level logging enabled
[JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=38064
[JITServerTest] [INFO] Starting client with command line:
/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/openjdkbinary/j2sdk-image/bin/java -XX:JITServerPort=38064 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../TKG/output_164371646467/testJITServer_0/client /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_x86-64,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all
[JITServerTest] [INFO] Waiting for 45000 millis.
[JITServerTest] [INFO] Starting server with command line:
/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/openjdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=38064
Failed to properly start server, it terminated prematurely with exit value: 1
Dumping the contents of log file: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR_testList_0/aqa-tests/TKG/output_164371646467/testJITServer_0/testServerComesUpAfterClientAndGoesDownAgain.server.out
////////////////////////////////////////////////////////////////////////
//// can't bind server address: Address already in use
////////////////////////////////////////////////////////////////////////
```
The test wants to start the JITServer with port==38064 but fails because the port is already used by somebody else. The port is chosen randomly, so while it is possible to have a port clash with an existing process, it is unlikely.

**Comment by mpirvu** [comment]
We hit similar issues before, and, while we didn't get to the bottom of them, the thought was that one of JITServer instances does not finish properly and still holds the port that was chosen at the beginning of the tests.
@dmitry-ten changed the test in https://github.com/eclipse-openj9/openj9/pull/13821 so that each new invocation of JITServer would get a random port. It's (remotely) possible that failing JITServer instances still exist on the machine (and accumulate) so that with time we get a higher probability of choosing a port that is in use. 
Maybe we should change the test so that, programmatically determine whether a port is in use and if is, pick another port, but also determine the process it belongs to.

**Comment by cjjdespres** [comment]
That would make sense, since it's been difficult to reproduce the failure.

**Comment by cjjdespres** [comment]
Why would we want to determine what process it belongs to? To kill the failed JITServer instance, if it is one?

**Comment by pshipton** [comment]
Agree it would be useful to figure out why the port isn't available, as that may help determine if there is a jitserver or test problem that needs to be fixed. Seems to me there is a delay if a port isn't shut down properly. The port will be released but it needs to time out first.

I looked at the machine for the last failure and don't see any `jitserver` processes. We do have a sanitize job that runs before the nightly builds, which should be killing anything left running.
https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy#L302

If we get another failure we could look on the machine before the sanitize runs.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/137/

Happened in Friday night builds, didn't get a chance to look at the machine.
