### ISSUE TITLE
OpenJDK ProcessBuilder/Basic.java ArrayIndexOutOfBoundsException CharacterDataLatin1.getProperties

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14405]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly/203
jdk_lang_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops`
java/lang/ProcessBuilder/Basic.java
```
00:57:40  java.lang.ArrayIndexOutOfBoundsException
00:57:40  	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
00:57:40  	at java.lang.CharacterDataLatin1.toUpperCase(CharacterDataLatin1.java:146)
00:57:40  	at java.lang.Character.toUpperCase(Character.java:6433)
00:57:40  	at java.lang.Character.toUpperCase(Character.java:6404)
00:57:40  	at java.lang.ProcessEnvironment$NameComparator.compare(ProcessEnvironment.java:210)
00:57:40  	at java.lang.ProcessEnvironment$EntryComparator.compare(ProcessEnvironment.java:224)
00:57:40  	at java.lang.ProcessEnvironment$EntryComparator.compare(ProcessEnvironment.java:220)
00:57:40  	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
00:57:40  	at java.util.TimSort.sort(TimSort.java:220)
00:57:40  	at java.util.Arrays.sort(Arrays.java:1512)
00:57:40  	at java.util.ArrayList.sort(ArrayList.java:1464)
00:57:40  	at java.util.Collections.sort(Collections.java:177)
00:57:40  	at java.lang.ProcessEnvironment.toEnvironmentBlock(ProcessEnvironment.java:304)
00:57:40  	at java.lang.ProcessEnvironment.toEnvironmentBlock(ProcessEnvironment.java:349)
00:57:40  	at java.lang.ProcessImpl.start(ProcessImpl.java:96)
00:57:40  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
00:57:40  	at Basic.commandOutput(Basic.java:106)
00:57:40  	at Basic.javaChildOutput(Basic.java:560)
00:57:40  	at Basic.getenvInChild1234(Basic.java:568)
00:57:40  	at Basic.realMain(Basic.java:1695)
00:57:40  	at Basic.main(Basic.java:2598)
```

Similar to https://github.com/eclipse-openj9/openj9/issues/11799

**Comment by JasonFengJ9** [comment]
A similar AIOOBE appeared at a JDK11 `0.30.0` release build `job/Test_openjdk11_j9_extended.openjdk_x86-64_linux/52/`(`ub20x64rt3-2`)
```
java version "11.0.14" 2022-01-18
IBM Semeru Runtime Certified Edition 11.0.14.0 (build 11.0.14+9)
Eclipse OpenJ9 VM 11.0.14.0 (build openj9-0.30.0, JRE 11 Linux amd64-64-Bit Compressed References 20220131_285 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 00ad19e9d5 based on jdk-11.0.14+9)

[2022-01-31T18:03:42.527Z] variation: Mode150
[2022-01-31T18:03:42.527Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-01-31T18:34:46.691Z] TEST: sun/nio/cs/TestIBMBugs.java

[2022-01-31T18:34:46.692Z] STDERR:
[2022-01-31T18:34:46.692Z] java.lang.ArrayIndexOutOfBoundsException
[2022-01-31T18:34:46.692Z] 	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
[2022-01-31T18:34:46.692Z] 	at java.base/java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:122)
[2022-01-31T18:34:46.692Z] 	at java.base/java.lang.Character.getType(Character.java:10351)
[2022-01-31T18:34:46.692Z] 	at java.base/java.lang.Character.isDefined(Character.java:9122)
[2022-01-31T18:34:46.692Z] 	at java.base/java.lang.Character.isDefined(Character.java:9098)
[2022-01-31T18:34:46.692Z] 	at TestIBMBugs.bug6577466(TestIBMBugs.java:173)
[2022-01-31T18:34:46.692Z] 	at TestIBMBugs.main(TestIBMBugs.java:386)
[2022-01-31T18:34:46.692Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-31T18:34:46.692Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-01-31T18:34:46.692Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-31T18:34:46.692Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-01-31T18:34:46.692Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-01-31T18:34:46.692Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2022-01-31T18:34:46.692Z] 
[2022-01-31T18:34:46.692Z] JavaTest Message: Test threw exception: java.lang.ArrayIndexOutOfBoundsException
[2022-01-31T18:34:46.692Z] JavaTest Message: shutting down test
[2022-01-31T18:34:46.692Z] 
[2022-01-31T18:34:46.692Z] 
[2022-01-31T18:34:46.692Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.ArrayIndexOutOfBoundsException
[2022-01-31T18:34:46.692Z] --------------------------------------------------
[2022-01-31T18:35:36.538Z] Test results: passed: 390; failed: 1
[2022-01-31T18:36:05.691Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2022-01-31T18:36:05.691Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16436510112482/jdk_nio_0/work
[2022-01-31T18:36:05.691Z] Error: Some tests failed or other problems occurred.
[2022-01-31T18:36:05.691Z] 
[2022-01-31T18:36:05.691Z] jdk_nio_0_FAILED
```

50x grinder - `job/Grinder/20588/`.
