### ISSUE TITLE
OpenJ9 JDK8 : AIX P10 : Exception in thread "main" java.lang.NoClassDefFoundError: jnurlcldr.shared.findstore.J_Dummy  

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse-openj9/openj9#14418]
Following failure is seen in multiple variants of `SCURLClassLoaderTests` (only JDK 8 specific test) while run on [the AIX p10 machine](https://hyc-runtimes-jenkins.swg-devops.com/label/p10aix009.rtp.raleigh.ibm.com): 

```
01T20:33:28.541Z]  [ERR] Exception in thread "main" java.lang.NoClassDefFoundError: jnurlcldr.shared.findstore.J_Dummy
[2022-02-01T20:33:28.541Z]  [ERR] 	at jnurlcldr.shared.findstore.I_Main$Data.getInt(I_Main.java:31)
[2022-02-01T20:33:28.541Z]  [ERR] 	at jnurlcldr.shared.findstore.I_Main.main(I_Main.java:36)
[2022-02-01T20:33:28.541Z]  [ERR] Caused by: java.lang.ClassNotFoundException: jnurlcldr.shared.findstore.J_Dummy
[2022-02-01T20:33:28.541Z]  [ERR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
[2022-02-01T20:33:28.541Z]  [ERR] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:954)
[2022-02-01T20:33:28.541Z]  [ERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:899)
[2022-02-01T20:33:28.541Z]  [ERR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[2022-02-01T20:33:28.541Z]  [ERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
[2022-02-01T20:33:28.541Z]  [ERR] 	... 2 more
```

Jenkins Link: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/20568/consoleText

Note, the same issue is not reproducible while running on a different, non-p10 AIX machine : https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/20636. 

Somewhat similar older issue: https://github.com/eclipse-openj9/openj9/issues/2653

FYI @JasonFengJ9 @llxia

**Comment by pshipton** [comment]
Assuming this is a test issue until we determine otherwise.

**Comment by Mesbah-Alam** [comment]
Similar issue seen on JDK 17 too, on the same AIX p10 machine: 

```
[2022-02-08T17:14:34.558Z] Test result: FAILED
[2022-02-08T17:14:34.558Z]  [ERR] Error: Could not find or load main class jnurlcldr.shared.findstore.E_Main
[2022-02-08T17:14:34.558Z]  [ERR] Caused by: java.lang.ClassNotFoundException: jnurlcldr.shared.findstore.E_Main
[2022-02-08T17:14:34.558Z] >> Success condition was not found: [Output match: Result=3]
[2022-02-08T17:14:34.558Z] >> Failure condition was not found: [Output match: LOCAL]
[2022-02-08T17:14:34.558Z] >> Failure condition was not found: [Output match: Unhandled Exception]
[2022-02-08T17:14:34.558Z] >> Failure condition was found: [Output match: Exception:]
[2022-02-08T17:14:34.558Z] >> Failure condition was found: [Output match: Error:]
```

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/20804

Most likely machine issue as these tests work fine on regular AIX machines.
