### ISSUE TITLE
JDK18 jdk/internal/reflect/Reflection/GetCallerClassTest.java mismatched caller: class GetCallerClassTest

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14414]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_sanity.openjdk_aarch64_linux_testList_0/6/`(`ub18-aarch64-1`):
```
openjdk version "18-ea" 2022-03-22
IBM Semeru Runtime Open Edition 18.0.0.0 (build 18-ea+33)
Eclipse OpenJ9 VM 18.0.0.0 (build master-739de03a5, JRE 18 Linux aarch64-64-Bit Compressed References 20220201_23 (JIT enabled, AOT enabled)
OpenJ9   - 739de03a5
OMR      - 88caea393
JCL      - 1a8263c989 based on jdk-18+33)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_lang_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk18_j9_sanity.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-aarch64-openj9%2F23%2Fibm-semeru-open-debugimage_aarch64_linux_JDK18_2022-02-01-20-48.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-aarch64-openj9%2F23%2Fibm-semeru-open-testimage_aarch64_linux_JDK18_2022-02-01-20-48.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-aarch64-openj9%2F23%2Fibm-semeru-open-jdk_aarch64_linux_JDK18_2022-02-01-20-48.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk18&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=16&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-02-01T21:22:12.810Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2022-02-01T21:22:12.810Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

[2022-02-01T21:33:14.295Z] TEST: jdk/internal/reflect/Reflection/GetCallerClassTest.java#id2

[2022-02-01T21:33:14.297Z] STDERR:
[2022-02-01T21:33:14.297Z] java.lang.RuntimeException: mismatched caller: class GetCallerClassTest
[2022-02-01T21:33:14.297Z] 	at GetCallerClassTest.testCallerSensitiveMethodsUsingMethodHandlesAndReflection(GetCallerClassTest.java:257)
[2022-02-01T21:33:14.297Z] 	at GetCallerClassTest.main(GetCallerClassTest.java:105)
[2022-02-01T21:33:14.297Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-02-01T21:33:14.297Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2022-02-01T21:33:14.297Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2022-02-01T21:33:14.297Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-02-01T21:33:14.297Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-02-01T21:33:14.297Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-02-01T21:33:14.297Z] 
[2022-02-01T21:33:14.297Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: mismatched caller: class GetCallerClassTest

[2022-02-01T21:34:04.660Z] jdk_lang_1_FAILED
```

It appears related to https://github.com/eclipse-openj9/openj9/issues/13852
fyi @babsingh @tajila

**Comment by tajila** [comment]
This is a known issue jdk/internal/reflect/Reflection/GetCallerClassTest.java#id2 & id3 will not pass, since our directMethodHandle=false behaviour differs from the RI. We are not planning on fixing this. I made a mistake and excluded the wrong tests in https://github.com/adoptium/aqa-tests/pull/3287

**Comment by babsingh** [comment]
Is the failure related to your note in https://github.com/eclipse-openj9/openj9/issues/14097#issuecomment-1023332009?

> We have a difference in the original reflection implementation which means we can not re-enable all the tests. This difference exists as far back as JDK11. However, the segfaults have been fixed.

**Comment by tajila** [comment]
https://github.com/adoptium/aqa-tests/pull/3311

**Comment by JasonFengJ9** [comment]
Moving out the iteration plan as per comment https://github.com/eclipse-openj9/openj9/issues/14414#issuecomment-1028045431 https://github.com/eclipse-openj9/openj9/issues/14414#issuecomment-1028046002
