### ISSUE TITLE
OpenJDK java/lang/ClassLoader/nativeLibrary/NativeLibraryTest Expected count = 1 but got 2

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14441]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/144
jdk_lang_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops`
java/lang/ClassLoader/nativeLibrary/NativeLibraryTest.java

```
22:19:38  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected count = 1 but got 2
22:19:38  REASON: User specified action: run main/othervm/native -Xcheck:jni NativeLibraryTest 
22:19:38  TIME:   2.236 seconds
22:19:38  messages:
22:19:38  command: main -Xcheck:jni NativeLibraryTest
22:19:38  reason: User specified action: run main/othervm/native -Xcheck:jni NativeLibraryTest 
22:19:38  Mode: othervm [/othervm specified]
22:19:38  elapsed time (seconds): 2.236
22:19:38  configuration:
22:19:38  STDOUT:
22:19:38  count: 1
22:19:38  doit() iter: 0, gc 0
22:19:38  count: 2
22:19:38  STDERR:
22:19:38  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
22:19:38  java.lang.RuntimeException: Expected count = 1 but got 2
22:19:38  	at testloader//p.Test.run(Test.java:34)
22:19:38  	at NativeLibraryTest.runTest(NativeLibraryTest.java:89)
22:19:38  	at NativeLibraryTest.main(NativeLibraryTest.java:65)
```

**Comment by pshipton** [comment]
@tajila this is failing in every build now, can someone take a look.

**Comment by pshipton** [comment]
Tentatively added it to the 0.31 milestone plan assuming it also affects jdk18. We can move it to 0.32 if not.

**Comment by tajila** [comment]
@JasonFengJ9 Is this only seen on AIX?

**Comment by pshipton** [comment]
It only shows up in the open builds on AIX.

**Comment by JasonFengJ9** [comment]
> Is this only seen on AIX?

Only appeared on Internal AIX as well.

**Comment by JasonFengJ9** [comment]
It passed last run `job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_0/63/consoleFull`
```
02:46:51  java version "17.0.2-beta" 2022-01-18
02:46:51  IBM Semeru Runtime Certified Edition 17.0.2+8-202202020503 (build 17.0.2-beta+8-202202020503)
02:46:51  Eclipse OpenJ9 VM 17.0.2+8-202202020503 (build master-739de03a5, JRE 17 AIX ppc64-64-Bit Compressed References 20220202_88 (JIT enabled, AOT enabled)
02:46:51  OpenJ9   - 739de03a5
02:46:51  OMR      - 88caea393
02:46:51  JCL      - 444dc0bda based on jdk-17.0.2+8)
```

**Comment by pshipton** [comment]
That "last run" is dated 20220202 which is before the failure started showing up on Feb 4

**Comment by JasonFengJ9** [comment]
Clarification: last **internal** run.

**Comment by pshipton** [comment]
There are aqa-tests changes as well.
https://github.com/adoptium/aqa-tests/compare/37f2a4f898ae...58a0ea5a88bf
https://github.com/adoptium/aqa-tests/pull/3315

**Comment by JasonFengJ9** [comment]
Removed `blocker` label since the test has been excluded for AIX.

**Comment by JasonFengJ9** [comment]
**Update:**

The test in question verifies that the native library associated w/ a classloader invokes its `JNI_OnLoad()` just once according to a `static jint count`,  after forced GC the classloader becomes unreachable , its native library is unloaded, `JNI_OnUnload` is called, and a new classloader along w/ its native library should start over.
This procedure is to be repeated five times.

At first time, the native library `JNI_OnLoad()` was invoked once, and the `count` is `1` as expected. After GC, `JNI_OnUnload` is called as well. So GC behaviour is as expected.

At second time, `JNI_OnLoad()` is invoked, but `count` is `2` which is expected to be `1` since this is a new instance after previous native library unloading. This leads to the `RuntimeException: Expected count = 1 but got 2`.

Enabled trace log and also added a printf at https://github.com/eclipse-openj9/openj9/blob/c0f57714201dc862805689cea5925e5f42b4d7d6/runtime/j9vm/j7vmi.c#L2332 
```
	retCode = dlclose(handle);
	printf("JVM_UnloadLibrary:dlclose retCode = %d \n", retCode);
```

Got following log messages:
```
count: 1
14:25:18.850 0x30010700          j9scar.113      > JVM_LoadLibrary(name=/home/jenkins/aixlib/jdk/lib/libjimage.so)
14:25:18.850 0x30010700          j9scar.230      - JVM_LoadLibrary(name=/home/jenkins/aixlib/jdk/lib/libjimage.so) j9sl_open_shared_library
14:25:18.850 0x30010700          j9scar.232      < JVM_LoadLibrary -- return 0x23
14:25:18.916 0x30010700          j9scar.113      > JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so)
14:25:18.916 0x30010700          j9scar.230      - JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so) j9sl_open_shared_library
14:25:18.916 0x30010700          j9scar.232      < JVM_LoadLibrary -- return 0x24
14:25:18.966*0x30120700          j9scar.228      > JVM_UnloadLibrary(handle=0000000000000024)
JVM_UnloadLibrary:dlclose retCode = 0 
doit() iter: 0, gc 0
count: 2
14:25:21.421*0x30010700          j9scar.113      > JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so)
14:25:21.421 0x30010700          j9scar.230      - JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so) j9sl_open_shared_library
14:25:21.421 0x30010700          j9scar.232      < JVM_LoadLibrary -- return 0x24
Exception in thread "main" java.lang.RuntimeException: Expected count = 1 but got 2
        at testloader//p.Test.run(Test.java:34)
        at NativeLibraryTest.runTest(NativeLibraryTest.java:89)
        at NativeLibraryTest.main(NativeLibraryTest.java:65)
```

It appears AIX `dlclose(handle)` didn't unload the native library like other platforms.

**Comment by tajila** [comment]
@JasonFengJ9 Do you know how many times `dlopen()` is called on it? that may help us track any other modules that may require it.

**Comment by JasonFengJ9** [comment]
> Do you know how many times dlopen() is called on it?

```
17:14:10.962 0x30010700          j9scar.113      > JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so)
17:14:10.962 0x30010700         omrport.475      > omrsl_open_shared_library name=/home/jenkins/aixlib/libnativeLibraryTest.so, flags=2
17:14:10.962 0x30010700         omrport.476      - omrsl_open_shared_library using mangledName /home/jenkins/aixlib/libnativeLibraryTest.so
17:14:10.962 0x30010700         omrport.477      < omrsl_open_shared_library handle=0000000000000024
17:14:10.962 0x30010700          j9scar.230      - JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so) j9sl_open_shared_library
17:14:10.962 0x30010700          j9scar.232      < JVM_LoadLibrary -- return 0x24
17:14:11.020*0x30120700          j9scar.228      > JVM_UnloadLibrary(handle=0000000000000024)


17:14:13.451*0x30010700          j9scar.113      > JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so)
17:14:13.451 0x30010700         omrport.475      > omrsl_open_shared_library name=/home/jenkins/aixlib/libnativeLibraryTest.so, flags=2
17:14:13.452 0x30010700         omrport.476      - omrsl_open_shared_library using mangledName /home/jenkins/aixlib/libnativeLibraryTest.so
17:14:13.452 0x30010700         omrport.477      < omrsl_open_shared_library handle=0000000000000024
17:14:13.452 0x30010700          j9scar.230      - JVM_LoadLibrary(name=/home/jenkins/aixlib/libnativeLibraryTest.so) j9sl_open_shared_library
17:14:13.452 0x30010700          j9scar.232      < JVM_LoadLibrary -- return 0x24

```
There are only two `JVM_LoadLibrary()/omrsl_open_shared_library()` on `libnativeLibraryTest.so`.
Note: `JVM_UnloadLibrary()` calls `dlclose()` directly instead OMR version `omrsl_close_shared_library()` which is just a wrapper of `dlclose()`.

**Comment by JasonFengJ9** [comment]
According this post [1], this is a known feature of AIX.
_By default shared libraries are loaded into a segment that is shared by all processes, and they "stick" there._

`genkld` shows `9000000072b1000      92c /home/jenkins/aixlib/libnativeLibraryTest.so` even after Java exits.

I build a simple C program and verified this behaviour.
```
  void *handle = dlopen("/home/jenkins/aixlib/testlibunload/libnativeLibraryTest.so", RTLD_NOW);
  printf("dlopen handle = %p \n", handle);
  if (NULL != handle) {
    int ret = dlclose(handle);
    if (0 != ret) {
      printError();
    }
  } else {
    printError();
  }
```
After exiting this small problem, `genkld` shows
`90000000662e000      92c /home/jenkins/aixlib/testlibunload/libnativeLibraryTest.so`

I think this test doesn't apply to AIX, not sure the implication of Java new native library loading approach though.

[1] http://www.verycomputer.com/176_b0c593a44d3e7667_1.htm

**Comment by JasonFengJ9** [comment]
Okay, I think I found the problem (also correction for earlier comments)

Though `JVM_LoadLibrary()`(`omrsl_open_shared_library()`) are correctly paired w/ `JVM_UnloadLibrary()`(`dlclose()`), there is an additional `loadAndInit()` within `aix/omrsl.c:omrsl_open_shared_library()` before `dlopen()`. 
`loadAndInit()` also registered a reference to the loaded native library but w/o matching `terminateAndUnload()`, it prevented the library unloading even after `dlclose()` which removed the module access created by `dlopen()`.

It appears adding a `terminateAndUnload()` [1] after `dlopen()` fixed this test failure. Will run some sanity tests before submitting a PR.

Note: `genkld` still shows the library after the process exit but its states (variables) are refreshed when it is unloaded successfully.

[1] https://github.com/JasonFengJ9/omr/tree/aixnativlib

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_testList_0/8/`(`ub20lert-1-4`)
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+29 (build 19+29)
Eclipse OpenJ9 VM 19+29 (build master-6b4a2db09, JRE 19 Linux ppc64le-64-Bit Compressed References 20220919_13 (JIT enabled, AOT enabled)
OpenJ9   - 6b4a2db09
OMR      - ff6a49823
JCL      - 403c2088e2 based on jdk-19+29)

[2022-07-09T16:48:31.059Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2022-07-09T16:48:31.059Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

[2022-07-09T16:52:44.134Z] TEST: java/lang/ClassLoader/loadLibraryUnload/LoadLibraryUnloadTest.java

[2022-07-09T16:52:44.135Z] STDERR:
[2022-07-09T16:52:44.135Z] JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
[2022-07-09T16:52:44.135Z] java.lang.RuntimeException: Failed to unload native library: expected true, was false
[2022-07-09T16:52:44.135Z] 	at jdk.test.lib.Asserts.fail(Asserts.java:594)
[2022-07-09T16:52:44.135Z] 	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
[2022-07-09T16:52:44.135Z] 	at LoadLibraryUnloadTest.main(LoadLibraryUnloadTest.java:102)
[2022-07-09T16:52:44.135Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-09T16:52:44.135Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-07-09T16:52:44.135Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-07-09T16:52:44.135Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-07-09T16:52:44.135Z] 
[2022-07-09T16:52:44.135Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Failed to unload native library: expected true, was false

[2022-07-09T16:52:44.136Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed to unload native library: expected true, was false
[2022-07-09T16:52:44.136Z] --------------------------------------------------
[2022-07-09T17:17:44.553Z] Test results: passed: 813; failed: 1
[2022-07-09T17:18:09.526Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_testList_0/jvmtest/openjdk/report/html/report.html
[2022-07-09T17:18:09.526Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_16573853091097/jdk_lang_0/work
[2022-07-09T17:18:09.526Z] Error: Some tests failed or other problems occurred.
[2022-07-09T17:18:09.526Z] 
[2022-07-09T17:18:09.526Z] jdk_lang_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_s390x_linux_testList_0/55/)(`rhel7s390x-3-6`)
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-f6c7bee4b, JRE 19 Linux s390x-64-Bit Compressed References 20221018_71 (JIT enabled, AOT enabled)
OpenJ9   - f6c7bee4b
OMR      - 357df2f80
JCL      - 110e1e7808 based on jdk-19.0.1+10)

[2022-11-05T17:07:53.140Z] TEST: java/lang/ClassLoader/loadLibraryUnload/LoadLibraryUnloadTest.java

[2022-11-05T17:07:53.141Z] STDERR:
[2022-11-05T17:07:53.141Z] JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
[2022-11-05T17:07:53.141Z] java.lang.RuntimeException: Failed to unload native library: expected true, was false
[2022-11-05T17:07:53.141Z] 	at jdk.test.lib.Asserts.fail(Asserts.java:594)
[2022-11-05T17:07:53.141Z] 	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
[2022-11-05T17:07:53.141Z] 	at LoadLibraryUnloadTest.main(LoadLibraryUnloadTest.java:102)
[2022-11-05T17:07:53.141Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-11-05T17:07:53.141Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-11-05T17:07:53.141Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-11-05T17:07:53.141Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-05T17:07:53.141Z] 
[2022-11-05T17:07:53.141Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Failed to unload native library: expected true, was false

[2022-11-05T17:07:53.142Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed to unload native library: expected true, was false
[2022-11-05T17:07:53.142Z] --------------------------------------------------
[2022-11-05T17:36:33.472Z] Test results: passed: 846; failed: 1
[2022-11-05T17:36:36.489Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_16676677896928/jdk_lang_0/report/html/report.html
[2022-11-05T17:36:36.489Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_16676677896928/jdk_lang_0/work
[2022-11-05T17:36:36.489Z] Error: Some tests failed or other problems occurred.
[2022-11-05T17:36:36.489Z] 
[2022-11-05T17:36:36.489Z] jdk_lang_0_FAILED
```
