### ISSUE TITLE
jit_tr_0 testNOPing expected:<?> but was:<B>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14469]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1 - [p8-java1-ibm06](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm06)
jit_tr_0 `-Xjit:noJitUntilMain -Xdump:java`

```
03:01:47  FAILED: testNOPing
03:01:47  java.lang.AssertionError: expected:<?> but was:<B>
03:01:47  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
03:01:47  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
03:01:47  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
03:01:47  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:215)
03:01:47  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:222)
03:01:47  	at jit.test.tr.chtable.VirtualGuardTest.testNOPing(VirtualGuardTest.java:109)
03:01:47  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:01:47  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:01:47  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:01:47  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:01:47  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
03:01:47  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
03:01:47  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
03:01:47  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
03:01:47  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
03:01:47  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
03:01:47  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
03:01:47  	at org.testng.TestRunner.run(TestRunner.java:505)
03:01:47  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
03:01:47  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
03:01:47  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
03:01:47  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
03:01:47  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
03:01:47  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
03:01:47  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
03:01:47  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
03:01:47  	at org.testng.TestNG.runSuites(TestNG.java:1049)
03:01:47  	at org.testng.TestNG.run(TestNG.java:1017)
03:01:47  	at org.testng.TestNG.privateMain(TestNG.java:1354)
03:01:47  	at org.testng.TestNG.main(TestNG.java:1323)
03:01:47  
03:01:47  
03:01:47  ===============================================
03:01:47      chtableTest
03:01:47      Tests run: 7, Failures: 1, Skips: 0
03:01:47  ===============================================
```
@0xdaryl

**Comment by 0xdaryl** [comment]
@zl-wang : could you have someone triage this AIX failure please?

**Comment by zl-wang** [comment]
@IBMJimmyk help this investigation please

**Comment by IBMJimmyk** [comment]
The failing line in the failing test looks to be here:
https://github.com/eclipse-openj9/openj9/blob/c462b8b9d0cee99dce36715fd95ad7de210307d2/test/functional/JIT_Test/src/jit/test/tr/chtable/VirtualGuardTest.java#L109

It seems like the problem is with checking the result. From the test output:
```
java.lang.AssertionError: expected:<?> but was:<B>
```
From the test source, the expected result is "B" and this actually matches the produced result. But, the "expected" result listed in the test is "?".

**Comment by IBMJimmyk** [comment]
The original failure didn't have any corefiles to work with so I tried to reproduce the problem. I did 200 runs via grinder and they all passed:

job/Grinder/20966/tapResults/
Passed 100/100

job/Grinder/20988/tapResults/
Passed 100/100

So there's not much I can do with this unless the problem shows up again.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_Nightly_testList_1/241 - [p8-java1-ibm05](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm05)
jit_tr_0 `-Xjit:noJitUntilMain -Xdump:java`

```
00:26:26  FAILED: testNOPing
00:26:26  java.lang.AssertionError: expected:<?> but was:<B>
00:26:26  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
00:26:26  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
00:26:26  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
00:26:26  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:215)
00:26:26  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:222)
00:26:26  	at jit.test.tr.chtable.VirtualGuardTest.testNOPing(VirtualGuardTest.java:109)
```

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk18_j9_sanity.functional_aarch64_mac_testList_2/16/`(`macaarch64rt2`)
```
openjdk version "18-ea" 2022-03-22
IBM Semeru Runtime Open Edition 18.0.0.0-rc1a (build 18-ea+37)
Eclipse OpenJ9 VM 18.0.0.0-rc1a (build openj9-0.31.0-rc1a, JRE 18 Mac OS X aarch64-64-Bit 20220405_35 (JIT enabled, AOT enabled)
OpenJ9   - f9bde1a3b
OMR      - 582866494
JCL      - b4cac4a4ce4 based on jdk-18+37)

[2022-04-05T09:12:54.337Z] variation: -Xjit:noJitUntilMain -Xdump:java
[2022-04-05T09:12:54.337Z] JVM_OPTIONS:  -Xjit:noJitUntilMain -Xdump:java 

[2022-04-05T09:13:40.529Z] FAILED: testNOPing
[2022-04-05T09:13:40.529Z] java.lang.AssertionError: expected:<?> but was:<B>
[2022-04-05T09:13:40.529Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2022-04-05T09:13:40.529Z] 	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
[2022-04-05T09:13:40.529Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
[2022-04-05T09:13:40.529Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:215)
[2022-04-05T09:13:40.529Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:222)
[2022-04-05T09:13:40.529Z] 	at jit.test.tr.chtable.VirtualGuardTest.testNOPing(VirtualGuardTest.java:109)

[2022-04-05T09:14:16.855Z] ===============================================
[2022-04-05T09:14:16.855Z] JIT_Test suite
[2022-04-05T09:14:16.855Z] Total tests run: 16450, Failures: 1, Skips: 0
[2022-04-05T09:14:16.855Z] ===============================================
[2022-04-05T09:14:16.855Z] 
[2022-04-05T09:14:20.182Z] 
[2022-04-05T09:14:20.182Z] jit_tr_0_FAILED
```

**Comment by pshipton** [comment]
@zl-wang @IBMJimmyk the problem seems to be occurring quite frequently lately. Note the latest failure is on amac and not AIX like the original ones.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_ppc64_aix_OMR_testList_1/18
jit_tr_0
```
07:10:41  FAILED: testNOPing
07:10:41  java.lang.AssertionError: expected:<?> but was:<B>
07:10:41  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
07:10:41  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
07:10:41  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
07:10:41  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:215)
07:10:41  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:222)
07:10:41  	at jit.test.tr.chtable.VirtualGuardTest.testNOPing(VirtualGuardTest.java:109)
```

**Comment by zl-wang** [comment]
@bhavanisn please take a look

**Comment by pshipton** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_0/69)
jit_tr_0 OMR acceptance
```
FAILED: testNOPing
java.lang.AssertionError: expected:<?> but was:<B>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:215)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:222)
	at jit.test.tr.chtable.VirtualGuardTest.testNOPing(VirtualGuardTest.java:109)
```

**Comment by bhavanisn** [comment]
Looks like the failure is not limited to ppc64_aix but could happen on other platforms too. 

I tried to reproduce with Grinder runs, but is not reproducible. 

The result calculated is `?` whereas expected is `B`.

I analyzed the scenario where this can happen: 
1. For the final result to be `?` is very narrow as it has to be the last statement executed and the test case exited after that ie., `keepOnGoing=false`. 
2. The possibility of `state=?`  can happen only during the transition from class `A` to `B`. The assert in the `default` case verifies this intermediate result and sets `state` to `?`.  This is correct in normal scenarios as `state=‘B’` in next iteration.
https://github.com/eclipse-openj9/openj9/blob/master/test/functional/JIT_Test/src/jit/test/tr/chtable/VirtualGuardTest.java#L72-L90
```
default:
   AssertJUnit.assertTrue("switching to ?", state == 'A' && result > 4*'A' && result < 4*'B');
   state = '?';
```
3. Class `B` is loaded after 6 secs and test case finishes at 10 secs when final task is executed. Unless there is a possibility that both `task B` and `task FIN` executed at same time, `state=?` cannot happen. In that case the question is why would `task B` start delayed by 4 secs.
```
// load B after 6 seconds			
timer.schedule(new NotifyTask(TASK_LOAD_B, this), SECONDS_6);
// schedule to be woken up after 10 seconds
timer.schedule(new NotifyTask(TASK_FIN, this), SECONDS_10);
```


As this failure is not reproducible, I would suggest if we can add some debug code in the test case so we can have more info to debug if it happens again.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_0/734
jit_tr_0
```
11:39:25  FAILED: testNOPing
11:39:25  java.lang.AssertionError: expected:<A> but was:<B>
11:39:25  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
11:39:25  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
11:39:25  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
11:39:25  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:215)
11:39:25  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:222)
11:39:25  	at jit.test.tr.chtable.VirtualGuardTest.testNOPing(VirtualGuardTest.java:113)
```
