### ISSUE TITLE
OpenJDK AIX FileEncodingTest testFileEncodingToDefault Default Charset: ISO-8859-1, expected: US-ASCII

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14472]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/2 - [p8-java1-ibm06](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm06)
jdk_lang_0, jdk_lang_1
java/lang/System/FileEncodingTest.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/2/openjdk_test_output.tar.gz
```
18:43:01  rerun:
18:43:01  cd /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/scratch && \
18:43:01  DISPLAY=unix:0 \
18:43:01  HOME=/home/jenkins \
18:43:01  LANG=C \
18:43:01  PATH=/bin:/usr/bin:/usr/sbin \
18:43:01  TZ=CUT0 \
18:43:01      /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java \
18:43:01          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops' \
18:43:01          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-XX:+UseCompressedOops' \
18:43:01          -Dtest.compiler.opts= \
18:43:01          -Dtest.java.opts= \
18:43:01          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image \
18:43:01          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image \
18:43:01          -Dtest.timeout.factor=8.0 \
18:43:01          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
18:43:01          -Dtest.root=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
18:43:01          -Dtest.name=java/lang/System/FileEncodingTest.java \
18:43:01          -Dtest.file=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System/FileEncodingTest.java \
18:43:01          -Dtest.src=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System \
18:43:01          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib \
18:43:01          -Dtest.classes=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d \
18:43:01          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib \
18:43:01          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib \
18:43:01          -classpath /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
18:43:01          com.sun.javatest.regtest.agent.TestNGRunner java/lang/System/FileEncodingTest.java false FileEncodingTest
18:43:01  STDOUT:
18:43:01  Command line: [/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -cp /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/hamcrest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar -ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Dfile.encoding=UTF-8 FileEncodingTest UTF-8 ]
18:43:01  [2022-02-08T23:41:39.953822Z] Gathering output for process 15466564
18:43:01  [2022-02-08T23:41:40.243555Z] Waiting for completion for process 15466564
18:43:01  [2022-02-08T23:41:40.243759Z] Waiting for completion finished for process 15466564
18:43:01  Output and diagnostic info for process 15466564 was saved into 'pid-15466564-output.log'
18:43:01  Default Charset: UTF-8, expected: UTF-8
18:43:01  
18:43:01  [2022-02-08T23:41:40.249507Z] Waiting for completion for process 15466564
18:43:01  [2022-02-08T23:41:40.249639Z] Waiting for completion finished for process 15466564
18:43:01  test FileEncodingTest.testFileEncodingToDefault("UTF-8", "UTF-8"): success
18:43:01  Command line: [/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -cp /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/hamcrest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar -ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Dfile.encoding=ISO-8859-1 FileEncodingTest ISO-8859-1 ]
18:43:01  [2022-02-08T23:41:40.265454Z] Gathering output for process 15925344
18:43:01  [2022-02-08T23:41:40.672801Z] Waiting for completion for process 15925344
18:43:01  [2022-02-08T23:41:40.672894Z] Waiting for completion finished for process 15925344
18:43:01  Output and diagnostic info for process 15925344 was saved into 'pid-15925344-output.log'
18:43:01  Default Charset: ISO-8859-1, expected: ISO-8859-1
18:43:01  
18:43:01  [2022-02-08T23:41:40.673464Z] Waiting for completion for process 15925344
18:43:01  [2022-02-08T23:41:40.673672Z] Waiting for completion finished for process 15925344
18:43:01  test FileEncodingTest.testFileEncodingToDefault("ISO-8859-1", "ISO-8859-1"): success
18:43:01  Command line: [/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -cp /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/hamcrest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar -ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops FileEncodingTest UTF-8 ]
18:43:01  [2022-02-08T23:41:40.685295Z] Gathering output for process 15925346
18:43:01  [2022-02-08T23:41:41.090659Z] Waiting for completion for process 15925346
18:43:01  [2022-02-08T23:41:41.090749Z] Waiting for completion finished for process 15925346
18:43:01  Output and diagnostic info for process 15925346 was saved into 'pid-15925346-output.log'
18:43:01  Default Charset: UTF-8, expected: UTF-8
18:43:01  
18:43:01  [2022-02-08T23:41:41.091181Z] Waiting for completion for process 15925346
18:43:01  [2022-02-08T23:41:41.091328Z] Waiting for completion finished for process 15925346
18:43:01  test FileEncodingTest.testFileEncodingToDefault("", "UTF-8"): success
18:43:01  Command line: [/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -cp /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/hamcrest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar -ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Dfile.encoding=dummy FileEncodingTest UTF-8 ]
18:43:01  [2022-02-08T23:41:41.102684Z] Gathering output for process 15466566
18:43:01  [2022-02-08T23:41:41.601433Z] Waiting for completion for process 15466566
18:43:01  [2022-02-08T23:41:41.601663Z] Waiting for completion finished for process 15466566
18:43:01  Output and diagnostic info for process 15466566 was saved into 'pid-15466566-output.log'
18:43:01  Default Charset: UTF-8, expected: UTF-8
18:43:01  
18:43:01  [2022-02-08T23:41:41.602118Z] Waiting for completion for process 15466566
18:43:01  [2022-02-08T23:41:41.602183Z] Waiting for completion finished for process 15466566
18:43:01  test FileEncodingTest.testFileEncodingToDefault("dummy", "UTF-8"): success
18:43:01  Command line: [/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -cp /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/System/FileEncodingTest.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/System:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/hamcrest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar -ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Dfile.encoding=COMPAT FileEncodingTest US-ASCII ]
18:43:01  [2022-02-08T23:41:41.612796Z] Gathering output for process 15925348
18:43:01  [2022-02-08T23:41:42.039542Z] Waiting for completion for process 15925348
18:43:01  [2022-02-08T23:41:42.039647Z] Waiting for completion finished for process 15925348
18:43:02  Output and diagnostic info for process 15925348 was saved into 'pid-15925348-output.log'
18:43:02  Default Charset: ISO-8859-1, expected: US-ASCII
18:43:02  
18:43:02  [2022-02-08T23:41:42.040155Z] Waiting for completion for process 15925348
18:43:02  [2022-02-08T23:41:42.040240Z] Waiting for completion finished for process 15925348
18:43:02  [2022-02-08T23:41:42.040294Z] Waiting for completion for process 15925348
18:43:02  [2022-02-08T23:41:42.040344Z] Waiting for completion finished for process 15925348
18:43:02  test FileEncodingTest.testFileEncodingToDefault("COMPAT", "<should_be_replaced>"): failure
18:43:02  java.lang.RuntimeException: Expected to get exit value of [0]
18:43:02  
18:43:02  	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
18:43:02  	at FileEncodingTest.testFileEncodingToDefault(FileEncodingTest.java:81)
18:43:02  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:43:02  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
18:43:02  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
18:43:02  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
18:43:02  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
18:43:02  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
18:43:02  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
18:43:02  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
18:43:02  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
18:43:02  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
18:43:02  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
18:43:02  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
18:43:02  	at org.testng.TestRunner.run(TestRunner.java:585)
18:43:02  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
18:43:02  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
18:43:02  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
18:43:02  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
18:43:02  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
18:43:02  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
18:43:02  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
18:43:02  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
18:43:02  	at org.testng.TestNG.runSuites(TestNG.java:1069)
18:43:02  	at org.testng.TestNG.run(TestNG.java:1037)
18:43:02  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
18:43:02  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:43:02  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
18:43:02  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
18:43:02  	at java.base/java.lang.Thread.run(Thread.java:889)
```

**Comment by pshipton** [comment]
@tajila still a jdk18 file encoding issue on AIX

**Comment by pshipton** [comment]
Might be worth testing an Adoptium build to see if it's the same.

**Comment by JasonFengJ9** [comment]
Similar w/ https://github.com/eclipse-openj9/openj9/issues/14227, will investigate them together.

**Comment by tajila** [comment]
@JasonFengJ9 can you add https://github.com/eclipse-openj9/openj9/issues/14473 to that list as well

**Comment by pshipton** [comment]
Not sure how similar it is to https://github.com/eclipse-openj9/openj9/issues/14227. In https://github.com/eclipse-openj9/openj9/issues/14227 the test is making wrong assumptions because of the change to use UTF8 by default. This one is an OpenJDK test, which should be correct, and I didn't see it failing on any other platform. There could be an issue with AIX itself, I'm not sure how well maintained this platforms is at OpenJDK any more.

**Comment by JasonFengJ9** [comment]
https://github.com/eclipse-openj9/openj9/issues/14227 is a test issue as per https://github.com/eclipse-openj9/openj9/issues/14227#issuecomment-1022182333, also I noticed that the non-ascii command line option (tested via `cmdLineTester_SystemPropertiesTest_aix`) wasn't converted properly, hence was using that issue to continue the encoding investigation.
`java/lang/System/FileEncodingTest.java` in this issue checks VM behaviours via a command line option `-Dfile.encoding`.
`java/lang/ProcessBuilder/Basic.java#id0` in #14473 had problem to handle the envstrings containing NULLs.
These three issues all occurred at AIX, and there is a chance to share same encoding problem underneath.
I think it is ok to group them together for now.

**Comment by pshipton** [comment]
I'm concerned about there being a real problem here, you can exclude it but we shouldn't ignore it. My understanding is that AIX isn't maintained at OpenJDK any more the same way it was in the past, and may need fixes to support jdk18 properly.

**Comment by JasonFengJ9** [comment]
> I'm concerned about there being a real problem here

Yes, that was the reason to keep the investigation at https://github.com/eclipse-openj9/openj9/issues/14227
#14227 #14472 #144473 appears same issue underneath.

**Comment by pshipton** [comment]
@pushkarnk this test fails on jdk18 Temurin builds from Adoptium, as well as OpenJ9. It may be related to https://openjdk.java.net/jeps/400. Note the JDK18 release schedule, we are running out of time to resolve problems for the initial release. http://openjdk.java.net/projects/jdk/18/

**Comment by pshipton** [comment]
@JasonFengJ9 I believe https://github.com/eclipse-openj9/openj9/issues/14227 to be a problem with the OpenJ9 test itself, which I suspect is different from this problem.

**Comment by JasonFengJ9** [comment]
> I believe https://github.com/eclipse-openj9/openj9/issues/14227 to be a problem with the OpenJ9 test itself

That's correct, the test makes assumption not applying to Java 18 w/ JEP 400 implemented.
While working on that issue, I noticed non-ascii characters in command line option weren't converted properly (more digging required), hence use that issue for a place holder for further investigation.  
I think the common problem is the command line option encoding at AIX, at least that's the first issue to be addressed.

**Comment by pushkarnk** [comment]
I was able to reproduce this JTREG failure with Temurin on AIX:
```
jtreg -jdk:/home/jenkins/pushkar/jdk-18+35/  -v1 jdk18u/test/jdk/java/lang/System/FileEncodingTest.java
FAILED: java/lang/System/FileEncodingTest.java
Test results: failed: 1
```

**Comment by backwaterred** [comment]
Hello :wave:, I just wanted to give you a head's up that I am working on this failure on the OpenJDK side. My initial assessment is that there is a testbug related to the LIBPATH variable on AIX. The OpenJDK issue is created [here](https://bugs.openjdk.java.net/browse/JDK-8282239), and I expect to have a PR for it shortly.

**Comment by pshipton** [comment]
@backwaterred can you please also create a PR with the fix against https://github.com/ibmruntimes/openj9-openjdk-jdk18. Unless you expect your OpenJDK fix is going to get into a jdk18 release build for the jdk18 initial release. Even if it does, there is no harm in delivering the same fix directly to https://github.com/ibmruntimes/openj9-openjdk-jdk18, the official fix will just be a no-op when merged.

**Comment by pshipton** [comment]
Did you request the fix to be backported to jdk18?

**Comment by backwaterred** [comment]
@pshipton I suspect it's too late for the change to be included in jdk18, as the codebase has entered the Initial Release phase. Unfortunately, it might also be too early for the change to be backported as it will GA 2022/03/22.

I have opened a PR for FileEncodingTest that mirrors the changes to the OpenJDK repo.

**Comment by pshipton** [comment]
@backwaterred thanks. We'd still like to have the OpenJDK change backported to jdk18 at the appropriate time.

**Comment by backwaterred** [comment]
> @backwaterred thanks. We'd still like to have the OpenJDK change backported to jdk18 at the appropriate time.

You're welcome. I am making a note to submit a backport after GA.

**Comment by pshipton** [comment]
Unexcluded the test https://github.com/adoptium/aqa-tests/pull/3367

**Comment by pshipton** [comment]
Awesome, thanks. We can remove our patch once the official change gets merged.
