### ISSUE TITLE
OpenJDK AIX java/lang/ProcessBuilder/Basic.java#id0 Incorrect handling of envstrings containing NULs

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14473]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/2 - [p8-java1-ibm06](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm06)
jdk_lang_0, jdk_lang_1
java/lang/ProcessBuilder/Basic.java#id0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/2/openjdk_test_output.tar.gz
```
18:30:54  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
18:30:54  REASON: User specified action: run main/othervm/native/timeout=300 -Djava.security.manager=allow Basic 
18:30:54  TIME:   27.53 seconds
18:30:54  messages:
18:30:54  command: main -Djava.security.manager=allow Basic
18:30:54  reason: User specified action: run main/othervm/native/timeout=300 -Djava.security.manager=allow Basic 
18:30:54  Mode: othervm [/othervm specified]
18:30:54  Additional options from @modules: --add-modules java.base --add-opens java.base/java.lang=ALL-UNNAMED
18:30:54  elapsed time (seconds): 27.53
18:30:54  configuration:
18:30:54  Boot Layer
18:30:54    add modules: java.base           
18:30:54    add opens:   java.base/java.lang ALL-UNNAMED
18:30:54  
18:30:54  STDOUT:
18:30:54  This appears to be a Unix system.
18:30:54  Testing ASCII environment values
18:30:54  Testing Latin1 environment values
18:30:54  Testing Unicode environment values
18:30:54  Testing directory .
18:30:54  Testing directory ..
18:30:54  Testing directory /
18:30:54  Testing directory /bin
18:30:54  cmdp
18:30:54  cmdp 0: /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java
18:30:54  cmdp 1: -XX:+DisplayVMOutputToStderr
18:30:54  cmdp 2: -classpath
18:30:54  cmdp 3: /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar
18:30:54  cmdp 4: Basic$JavaChild
18:30:54  cmdp 5: System.getenv()
18:30:54  envp
18:30:54  envp 0: LC_ALL=C
18:30:54  envp 1: FO=BR
18:30:54   waitFor process: delta: 95582
18:30:54  
18:30:54  Passed = 9135, failed = 2
18:30:54  
18:30:54  STDERR:
18:30:54  WARNING: A terminally deprecated method in java.lang.System has been called
18:30:54  WARNING: System::setSecurityManager has been called by Basic (file:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16443617443768/jdk_lang_0/work/classes/java/lang/ProcessBuilder/Basic_id0.d/)
18:30:54  WARNING: Please consider reporting this to the maintainers of Basic
18:30:54  WARNING: System::setSecurityManager will be removed in a future release
18:30:54  >'=C:=\,LIBPATH=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/../lib:/usr/lib,'< not equal to '=C:=\,LIBPATH=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/../lib:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native:/usr/lib,'
18:30:54  java.lang.Throwable
18:30:54  	at java.base/java.lang.Thread.dumpStack(Thread.java:560)
18:30:54  	at Basic.fail(Basic.java:2841)
18:30:54  	at Basic.fail(Basic.java:2842)
18:30:54  	at Basic.equal(Basic.java:2848)
18:30:54  	at Basic.realMain(Basic.java:1902)
18:30:54  	at Basic.main(Basic.java:2851)
18:30:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:30:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
18:30:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
18:30:54  	at java.base/java.lang.Thread.run(Thread.java:889)
18:30:54  Incorrect handling of envstrings containing NULs
18:30:54  java.lang.Throwable
18:30:54  	at java.base/java.lang.Thread.dumpStack(Thread.java:560)
18:30:54  	at Basic.fail(Basic.java:2841)
18:30:54  	at Basic.fail(Basic.java:2842)
18:30:54  	at Basic.check(Basic.java:2845)
18:30:54  	at Basic.realMain(Basic.java:1956)
18:30:54  	at Basic.main(Basic.java:2851)
18:30:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:30:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
18:30:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
18:30:54  	at java.base/java.lang.Thread.run(Thread.java:889)
```

**Comment by pshipton** [comment]
@tajila fyi

Might be worth testing an Adoptium build to see if it's the same.

**Comment by JasonFengJ9** [comment]
AIX encoding related issue, will investigate along w/ https://github.com/eclipse-openj9/openj9/issues/14227 https://github.com/eclipse-openj9/openj9/issues/14472

**Comment by JasonFengJ9** [comment]
It has been excluded for RI.
```
java/lang/ProcessBuilder/Basic.java https://github.com/adoptium/aqa-tests/issues/1920   aix-ppc64
java/lang/System/FileEncodingTest.java  https://github.com/adoptium/aqa-tests/issues/1267   aix-ppc64
```

**Comment by cjjdespres** [comment]
I think this may be similar to what I've seen in some failing test suites for JITServer [here](https://github.com/eclipse-openj9/openj9/issues/14538#issuecomment-1043050057) and [here](https://github.com/eclipse-openj9/openj9/issues/14538#issuecomment-1043052939). Does that seem right? None of them are AIX or JDK18, though.

**Comment by pshipton** [comment]
Merging to 0.31 and 0.32 releases via 
https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/27
https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/28
