### ISSUE TITLE
threadMXBeanTimedParkTest Blocked time is lower than expected

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14470]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_1/200 - [p8-java1-ibm04](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm04)
threadMXBeanTimedParkTest_0 `-Xjit -Xgcpolicy:gencon -Xnocompressedrefs -Xthr:minimizeUserCPU`

```
04:17:55  [TimedParkTest] [ERROR] ERROR: Blocked time is lower than expected
04:17:55  [TimedParkTest] [ERROR]   actual: 4426 expected: 5000 tolerance: 500
04:17:55  FAILED: testTimedParkTest
04:17:55  java.lang.AssertionError: The following asserts failed:
04:17:55  	expected [PASS] but found [FAIL]
04:17:55  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
04:17:55  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by pshipton** [comment]
There was an occurrence Mar 16 https://github.com/eclipse-openj9/openj9/issues/14728#issue-1170941745

**Comment by pshipton** [comment]
@tajila could there be an actual problem here? This only started occurring recently, and I was assuming a machine problem, but the actual times are lower not higher. All the failures are on AIX with `-Xthr:minimizeUserCPU`.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.functional_ppc64_aix_Nightly_testList_1/26/ - [p8-java1-ibm07](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm07)
threadMXBeanTimedParkTest_2 `-Xgcpolicy:metronome -Xcompressedrefs -Xthr:minimizeUserCPU`
```
03:16:08  [TimedParkTest] [ERROR] ERROR: Blocked time is higher than expected
03:16:08  [TimedParkTest] [ERROR]   actual: 8851 expected: 5000 tolerance: 2000
03:16:08  FAILED: testTimedParkTest
03:16:08  java.lang.AssertionError: The following asserts failed:
03:16:08  	expected [PASS] but found [FAIL]
03:16:08  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
03:16:08  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by tajila** [comment]
@mikezhang1234567890 Can you please take a look at this

**Comment by mikezhang1234567890** [comment]
Looking into this, but haven't been able to reproduce the issue yet.

**Comment by pshipton** [comment]
It was hot for a few day, but I haven't seen it since. It it can't be reproduced we can close it until it's seen again.

**Comment by pshipton** [comment]
@mikezhang1234567890 do you see anything about the test that would explain why the actual could be lower than the expected?

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Nightly_testList_1/208
threadMXBeanTimedParkTest_1
```
23:44:50  [TimedParkTest] [ERROR] ERROR: Blocked time is higher than expected
23:44:50  [TimedParkTest] [ERROR]   actual: 9083 expected: 5000 tolerance: 2000
23:44:54  FAILED: testTimedParkTest
23:44:54  java.lang.AssertionError: The following asserts failed:
23:44:54  	expected [PASS] but found [FAIL]
23:44:54  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
23:44:54  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.functional_ppc64_aix_Nightly_testList_1/57
```
04:31:49  [TimedParkTest] [ERROR] ERROR: Blocked time is lower than expected
04:31:49  [TimedParkTest] [ERROR]   actual: 4407 expected: 5000 tolerance: 500
04:31:49  FAILED: testTimedParkTest
04:31:49  java.lang.AssertionError: The following asserts failed:
04:31:49  	expected [PASS] but found [FAIL]
04:31:49  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
04:31:49  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by tajila** [comment]
@mikezhang1234567890 You can ask @AdamBrousseau to give you access to the external machines, seems to fail pretty frequently there

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.functional_ppc64_aix_Nightly_testList_0/72/
```
03:10:12  [TimedParkTest] [ERROR] ERROR: Blocked time is lower than expected
03:10:12  [TimedParkTest] [ERROR]   actual: 4060 expected: 5000 tolerance: 500
03:10:12  FAILED: testTimedParkTest
03:10:12  java.lang.AssertionError: The following asserts failed:
03:10:12  	expected [PASS] but found [FAIL]
03:10:12  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
03:10:12  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by tajila** [comment]
@mikezhang1234567890 were you able to make any progress on this?

**Comment by mikezhang1234567890** [comment]
No, haven't managed to reproduce manually on the external machine https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm09/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Nightly_testList_1/239
threadMXBeanTimedParkTest_1
```
23:50:48  [TimedParkTest] [ERROR] ERROR: Blocked time is lower than expected
23:50:48  [TimedParkTest] [ERROR]   actual: 3493 expected: 5000 tolerance: 500
23:50:48  FAILED: testTimedParkTest
23:50:48  java.lang.AssertionError: The following asserts failed:
23:50:48  	expected [PASS] but found [FAIL]
23:50:48  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
23:50:48  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by pshipton** [comment]
We're not making much progress to resolve this, although it does occur every couple of weeks in the builds. Perhaps we can add some diagnostics into the VM so that when it does occur we get more information. In the meantime, I'm moving it to the Backlog.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Release_testList_0/30
```
17:49:58  [TimedParkTest] [ERROR]   actual: 4303 expected: 5000 tolerance: 500
17:49:59  FAILED: testTimedParkTest
17:49:59  java.lang.AssertionError: The following asserts failed:
17:49:59  	expected [PASS] but found [FAIL]
17:49:59  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
17:49:59  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Nightly_testList_0/283
```
21:55:21  [TimedParkTest] [ERROR] ERROR: Blocked time is lower than expected
21:55:21  [TimedParkTest] [ERROR]   actual: 3944 expected: 5000 tolerance: 500
21:55:21  FAILED: testTimedParkTest
21:55:21  java.lang.AssertionError: The following asserts failed:
21:55:21  	expected [PASS] but found [FAIL]
21:55:21  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
21:55:21  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/60
```
06:25:21  [TimedParkTest] [ERROR] ERROR: Blocked time is lower than expected
06:25:21  [TimedParkTest] [ERROR]   actual: 4125 expected: 5000 tolerance: 500
06:25:21  FAILED: testTimedParkTest
06:25:21  java.lang.AssertionError: The following asserts failed:
06:25:21  	expected [PASS] but found [FAIL]
06:25:21  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
06:25:21  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_1/119/consoleFull
```
02:39:31  ===============================================
02:39:31  Running test threadMXBeanTimedParkTest_0 ...
02:39:31  ===============================================
02:39:31  threadMXBeanTimedParkTest_0 Start Time: Fri Mar 10 07:35:31 2023 Epoch Time (ms): 1678433731692
02:39:31  variation: Mode110 -Xthr:minimizeUserCPU
02:39:31  JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs -Xthr:minimizeUserCPU 

02:40:19  [TimedParkTest] [ERROR] ERROR: Blocked time is higher than expected
02:40:19  [TimedParkTest] [ERROR]   actual: 9014 expected: 5000 tolerance: 2000
02:40:19  FAILED: testTimedParkTest
02:40:19  java.lang.AssertionError: The following asserts failed:
02:40:19  	expected [PASS] but found [FAIL]
02:40:19  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
02:40:19  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
02:40:19  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
02:40:19  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
02:40:19  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
02:40:19  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
02:40:19  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
02:40:19  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
02:40:19  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:40:19  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
02:40:19  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
02:40:19  	at org.testng.TestRunner.run(TestRunner.java:505)
02:40:19  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
02:40:19  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
02:40:19  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
02:40:19  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
02:40:19  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
02:40:19  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
02:40:19  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
02:40:19  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
02:40:19  	at org.testng.TestNG.runSuites(TestNG.java:1049)
02:40:19  	at org.testng.TestNG.run(TestNG.java:1017)
02:40:19  	at org.testng.TestNG.privateMain(TestNG.java:1354)
02:40:19  	at org.testng.TestNG.main(TestNG.java:1323)
02:40:19  
02:40:19  
02:40:19  ===============================================
02:40:19      threadMXBeanTimedParkTest
02:40:19      Tests run: 1, Failures: 1, Skips: 0
```

**Comment by JasonFengJ9** [comment]
[openjdk26_j9_extended.functional_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk26_j9_extended.functional_aarch64_mac_testList_0/6/)
```
[2026-06-29T14:37:40.699Z] Running test threadMXBeanTimedParkTest_0 ...
[2026-06-29T14:37:40.700Z] ===============================================
[2026-06-29T14:37:40.700Z] threadMXBeanTimedParkTest_0 Start Time: Mon Jun 29 07:37:40 2026 Epoch Time (ms): 1782743860423
[2026-06-29T14:37:40.700Z] variation: Mode110 -Xthr:minimizeUserCPU
[2026-06-29T14:37:40.700Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs -Xthr:minimizeUserCPU 

[2026-06-29T14:38:24.118Z] [TimedParkTest] [ERROR] ERROR: Blocked time is higher than expected
[2026-06-29T14:38:24.118Z] [TimedParkTest] [ERROR]   actual: 7268 expected: 5000 tolerance: 2000
[2026-06-29T14:38:24.118Z] FAILED: testTimedParkTest
[2026-06-29T14:38:24.118Z] java.lang.AssertionError: The following asserts failed:
[2026-06-29T14:38:24.118Z] 	expected [PASS] but found [FAIL]
[2026-06-29T14:38:24.118Z] 	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
[2026-06-29T14:38:24.118Z] 	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```
