### ISSUE TITLE
Jep389Tests_testClinkerFfi_DownCall test_aot NoSuchMethodError: java/lang/invoke/MethodHandle.invokeBasic

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14483]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_aot_Personal_testList_1/4/ - [cent7-x64-4](https://openj9-jenkins.osuosl.org/computer/cent7-x64-4)
Jep389Tests_testClinkerFfi_DownCall_0
`-Xshareclasses:name=test_aot -Xscmx400M -Xscmaxaot256m  --enable-preview`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.functional_x86-64_linux_aot_Personal_testList_1/4/functional_test_output.tar.gz
```
FAILED: test_multiThreadsWithMixedFuncDescriptors
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodError: java/lang/invoke/MethodHandle.invokeBasic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (loaded from jrt:/java.base by <Bootstrap Loader>) called from class java.lang.invoke.BoundMethodHandle$Species_LLLL (loaded from <Unknown> by <Bootstrap Loader>).
	at org.openj9.test.jep389.downcall.MultiThreadingTests4.test_multiThreadsWithMixedFuncDescriptors(MultiThreadingTests4.java:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: java/lang/invoke/MethodHandle.invokeBasic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (loaded from jrt:/java.base by <Bootstrap Loader>) called from class java.lang.invoke.BoundMethodHandle$Species_LLLL (loaded from <Unknown> by <Bootstrap Loader>).
	at org.openj9.test.jep389.downcall.MultiThreadingTests4$3.run(MultiThreadingTests4.java:99)
Caused by: java.lang.NoSuchMethodError: java/lang/invoke/MethodHandle.invokeBasic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (loaded from jrt:/java.base by <Bootstrap Loader>) called from class java.lang.invoke.BoundMethodHandle$Species_LLLL (loaded from <Unknown> by <Bootstrap Loader>).
	at java.lang.invoke.BoundMethodHandle$Species_LLLL.copyWithExtendL(java/lang/invoke/BoundMethodHandle$Species_LLLL)
	at java.base/java.lang.invoke.MethodHandles.filterReturnValue(MethodHandles.java:5851)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.permuteMH(ProgrammableInvoker.java:401)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:376)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:133)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:44)
	at org.openj9.test.jep389.downcall.MultiThreadingTests4$3.run(MultiThreadingTests4.java:95)

FAILED: test_addLongAndLongFromPointer_1
java.lang.NoSuchMethodError: java/lang/invoke/MethodHandle.invokeBasic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (loaded from jrt:/java.base by <Bootstrap Loader>) called from class java.lang.invoke.BoundMethodHandle$Species_LLLL (loaded from <Unknown> by <Bootstrap Loader>).
	at java.lang.invoke.BoundMethodHandle$Species_LLLL.copyWithExtendL(java/lang/invoke/BoundMethodHandle$Species_LLLL)
	at java.base/java.lang.invoke.MethodHandles.filterReturnValue(MethodHandles.java:5851)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.permuteMH(ProgrammableInvoker.java:401)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:376)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:133)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.downcallHandle(SysVx64Linker.java:90)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:44)
	at org.openj9.test.jep389.downcall.PrimitiveTypeTests1.test_addLongAndLongFromPointer_1(PrimitiveTypeTests1.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

and many more similar failures...
```
@dsouzai

**Comment by dsouzai** [comment]
I _think_ this is related to https://github.com/eclipse-openj9/openj9/issues/14135. Maybe this test needs to also be excluded?

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_aot_Personal/5

**Comment by pshipton** [comment]
> Maybe this test needs to also be excluded?

Seems like it's going to fail in every build.

**Comment by dsouzai** [comment]
auto exclude test Jep389Tests_testClinkerFfi_DownCall_0 testflag=aot

**Comment by ChengJin01** [comment]
Close this issue as the problem was resolved at https://github.com/eclipse-openj9/openj9/pull/16556.
