### ISSUE TITLE
Docker based CRIU testing

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#14486]
This issue is for docker based CRIU testing scenarios:

- Scenario 1: same host machine
 1. start container
 2. run tests and create CRIU checkpoints 
 3. restore
 4. push the generated image into dockerhub (may need a flag for this, so user can turn on or off)

- Scenario 2: different host machine (same os)
 1. pull docker imager from dockerhub
 2. restore

- Scenario 3: different host machines (different os) - TBD

ubuntu 20 is required (no machine atm) - FYI @AdamBrousseau

**Comment by llxia** [comment]
@tajila could you provide CRIU commands (checkpoints/restore) for running hello world? Thanks

**Comment by tajila** [comment]
1) build openj9 with `enable-criu-support`
2) Create application

```
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

import org.eclipse.openj9.criu.CRIUSupport;

public class Demo {

	public static void main(String args[]) {
                /* JVM startup */
		//checkPointJVM();

		/* perform application init */
		int numberOfPrimes = sieveOfEratosthenes(10000000).size();

		checkPointJVM();

		/* Application ready */
		System.out.println("Number of primes between 0 and 10,000,000: " + numberOfPrimes);

	}

	public static void checkPointJVM() {
		if (CRIUSupport.isCRIUSupportEnabled()) {

                       	       new CRIUSupport(Paths.get("cpData"))
                                                        .setLeaveRunning(false)
                                                        .setShellJob(true)
                                                        .checkpointJVM();
                 } else {
			System.err.println("CRIU is not enabled");
                 }
	}

	public static List<Integer> sieveOfEratosthenes(int n) {
		boolean prime[] = new boolean[n + 1];
		Arrays.fill(prime, true);
		for (int p = 2; p * p <= n; p++) {
			if (prime[p]) {
				for (int i = p * 2; i <= n; i += p) {
					prime[i] = false;
				}
			}
		}
		List<Integer> primeNumbers = new LinkedList<>();
		for (int i = 2; i <= n; i++) {
			if (prime[i]) {
				primeNumbers.add(i);
			}
		}
		return primeNumbers;
	}

}
```

3) Create the checkpoint image with `sudo  java -XX:+EnableCRIUSupport -cp . Demo`

4) Restore image with `sudo criu restore -D ./cpData --shell-job`

To run without sudo see https://github.com/eclipse-openj9/openj9/issues/14265

**Comment by llxia** [comment]
Thanks @tajila for the details.

FYI @renfeiw @LongyuZhang

**Comment by llxia** [comment]
@tajila In Scenario 2: different host machine (same os), possibly Scenario 3 as well, do we need to consider testing with different JDK versions? For example, create a checkpoint using JDK8 and restore using JDK11.

**Comment by tajila** [comment]
You dont need a JDK to restore, the JVM is baked into the container image. So you only need the JVM to create the checkpoint.

**Comment by LongyuZhang** [comment]
Tested docker criu testing on `ub20x64rt1-3 with criu 3.12`, using [open-liberty-criu-docker](https://github.ibm.com/tjwatson/open-liberty-criu-docker) repo, and criu sdk. The SCC got generated successfully, but running test got the error:
```
root@5668e9691867:/deleteMeCriu# java -XX:+EnableCRIUSupport Demo
Can't exec criu swrk: Operation not permitted
Can't read request: Connection reset by peer
Can't receive response: Connection reset by peer
Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processs, err=-70
	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:515)
	at Demo.checkPointJVM(Demo.java:30)
	at Demo.main(Demo.java:17)
```
Tried `ciur -V` also got the same error `bash: /usr/sbin/criu: Operation not permitted`
In docker, running as `root root`, and the criu permission is -rwxr-xr-x 1 root root   5752968 Mar 18 00:15 criu`

**Comment by tajila** [comment]
@LongyuZhang can you describe how you ran the docker test?

**Comment by LongyuZhang** [comment]
The steps I tried with docker criu testing are:
- transfer `jdk` and repo `open-liberty-criu-docker` to machine `ub20x64rt1-3`
- run `/openj9-build.sh -b ~/deleteMe/jdk` get the result `SCC generation phase completed`
- use docker container to run this image, and then inside the container, create [`Demo.java`](https://github.ibm.com/runtimes/infrastructure/issues/6547#issuecomment-40648002)
- use javac to complie it, and then run `- java -XX:+EnableCRIUSupport Demo`, got the above error `Operation not permitted`.
- Also I tested existing docker image on `ub20x64rt1-1`, got the same error.
Thanks.

> @LongyuZhang can you describe how you ran the docker test?

**Comment by tajila** [comment]
if you are using a docker container you can install any version of criu in the image. Can you try something newer? We only experimented with 3.15+

**Comment by LongyuZhang** [comment]
Just for note here, Criu test in docker has the errors and warning about `kdat cache`, which does not affect the checkpoint and restore, and can be solved by start the docker container with `--tmpfs /run` based on [this comment](https://github.com/checkpoint-restore/criu/issues/1663#issuecomment-978906223), so added this option in `criu_docker_test` playlist to avoid corresponding output.
```
13:33:47  Error (criu/util.c:635): exited, status=1
13:33:47  Error (criu/util.c:635): exited, status=1
13:33:47  Warn  (criu/kerndat.c:869): Can't keep kdat cache on non-tempfs
13:33:47  Pre-checkpoint
13:33:47  Post-checkpoint
```
