### ISSUE TITLE
OpenJDK java/lang/ProcessBuilder/Basic.java#id0 Windows timeout FileInputStream.readBytes

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14490]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/156/ - [win2012-x86-11](https://openj9-jenkins.osuosl.org/computer/win2012-x86-11)
java/lang/ProcessBuilder/Basic.java#id0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/156/openjdk_test_output.tar.gz
```
22:56:20  rerun:
22:56:20  cd 'F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\scratch\2' && \
22:56:20  PATH='C:\cygwin64\bin;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\apache-ant\apache-ant-1.10.3\bin;C:\Program Files\Java\jdk8u202-b08\bin;C:\Strawberry\perl\bin;C:\Program Files\Microsoft Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\OpenSSL-1.1.1-x86_32\bin;C:\OpenSSL-1.1.1-x86_64\bin;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0' \
22:56:20  SystemDrive=C: \
22:56:20  SystemRoot='C:\Windows' \
22:56:20  TEMP='C:\temp' \
22:56:20  windir='C:\Windows' \
22:56:20  CLASSPATH='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\classes\2\java\lang\ProcessBuilder\Basic_id0.d;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\jdk\java\lang\ProcessBuilder;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\classes\2\test\lib;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\lib;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\javatest.jar;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\jtreg.jar' \
22:56:20      'F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java' \
22:56:20          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops' \
22:56:20          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-XX:+UseCompressedOops' \
22:56:20          -Dtest.compiler.opts= \
22:56:20          -Dtest.java.opts= \
22:56:20          -Dtest.jdk='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
22:56:20          -Dcompile.jdk='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
22:56:20          -Dtest.timeout.factor=8.0 \
22:56:20          -Dtest.nativepath='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
22:56:20          -Dtest.root='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\jdk' \
22:56:20          -Dtest.name=java/lang/ProcessBuilder/Basic.java#id0 \
22:56:20          -Dtest.file='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\jdk\java\lang\ProcessBuilder\Basic.java' \
22:56:20          -Dtest.src='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\jdk\java\lang\ProcessBuilder' \
22:56:20          -Dtest.src.path='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\jdk\java\lang\ProcessBuilder;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\lib' \
22:56:20          -Dtest.classes='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\classes\2\java\lang\ProcessBuilder\Basic_id0.d' \
22:56:20          -Dtest.class.path='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\classes\2\java\lang\ProcessBuilder\Basic_id0.d;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\classes\2\test\lib' \
22:56:20          -Dtest.class.path.prefix='F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\classes\2\java\lang\ProcessBuilder\Basic_id0.d;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\test\jdk\java\lang\ProcessBuilder;F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\classes\2\test\lib' \
22:56:20          -Dtest.modules=java.base/java.lang:open \
22:56:20          --add-modules java.base \
22:56:20          --add-opens java.base/java.lang=ALL-UNNAMED \
22:56:20          -ea \
22:56:20          -esa \
22:56:20          -Xmx512m \
22:56:20          -Xdump:system:none \
22:56:20          -Xdump:heap:none \
22:56:20          -Xdump:system:events=gpf+abort+traceassert+corruptcache \
22:56:20          -XX:-JITServerTechPreviewMessage \
22:56:20          -XX:+UseCompressedOops \
22:56:20          '-Djava.library.path=F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
22:56:20          -Djava.security.manager=allow \
22:56:20          com.sun.javatest.regtest.agent.MainWrapper 'F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\java\lang\ProcessBuilder\Basic_id0.d\main.0.jta'
22:56:20  
22:56:20  ACTION: build -- Passed. All files up to date
22:56:20  REASON: Named class compiled on demand
22:56:20  TIME:   0.0 seconds
22:56:20  messages:
22:56:20  command: build Basic
22:56:20  reason: Named class compiled on demand
22:56:20  elapsed time (seconds): 0.0
22:56:20  
22:56:20  ACTION: main -- Error. Program `F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java' timed out (timeout set to 2400000ms, elapsed time including timeout handling was 2408095ms).
22:56:20  REASON: User specified action: run main/othervm/timeout=300 -Djava.security.manager=allow -Djdk.lang.Process.launchMechanism=fork Basic 
22:56:20  TIME:   2408.095 seconds
22:56:20  messages:
22:56:20  command: main -Djava.security.manager=allow -Djdk.lang.Process.launchMechanism=fork Basic
22:56:20  reason: User specified action: run main/othervm/timeout=300 -Djava.security.manager=allow -Djdk.lang.Process.launchMechanism=fork Basic 
22:56:20  Mode: othervm [/othervm specified]
22:56:20  Additional options from @modules: --add-modules java.base --add-opens java.base/java.lang=ALL-UNNAMED
22:56:20  Timeout information:
22:56:20  Running jcmd on process 4604
22:56:20  Dump written to F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16445490221696\jdk_lang_0\work\scratch\2\core.20220210.215559.4604.0001.dmp
22:56:20  Running jstack on process 4604
22:56:20  2022-02-10T21:56:04.702686600
22:56:20  Virtual machine: 4604 JVM information:
22:56:20  JRE 17 Windows Server 2012 R2 amd64-64-Bit Compressed References 20220210_160 (JIT enabled, AOT enabled)
22:56:20  OpenJ9   - 0fee70b8098
22:56:20  OMR      - e6d7abf
22:56:20  JCL      - 32e63c50bc0 based on jdk-17.0.3+1
22:56:20  
22:56:20  "main" prio=5 Id=1 WAITING
22:56:20  	at java.base@17.0.3-internal/java.lang.Object.wait(Native Method)
22:56:20  	at java.base@17.0.3-internal/java.lang.Object.wait(Object.java:219)
22:56:20  	at java.base@17.0.3-internal/java.lang.Thread.join(Thread.java:769)
22:56:20  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
22:56:20  
22:56:20  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
22:56:20  
22:56:20  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
22:56:20  
22:56:20  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
22:56:20  
22:56:20  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
22:56:20  
22:56:20  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
22:56:20  
22:56:20  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
22:56:20  
22:56:20  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
22:56:20  
22:56:20  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
22:56:20  
22:56:20  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
22:56:20  
22:56:20  "IProfiler" prio=5 Id=12 RUNNABLE
22:56:20  
22:56:20  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
22:56:20  	at java.base@17.0.3-internal/java.lang.Object.wait(Native Method)
22:56:20  	at java.base@17.0.3-internal/java.lang.Object.wait(Object.java:219)
22:56:20  	at java.base@17.0.3-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
22:56:20  	at java.base@17.0.3-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
22:56:20  	at java.base@17.0.3-internal/java.lang.Thread.run(Thread.java:889)
22:56:20  	at java.base@17.0.3-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
22:56:20  
22:56:20  "Finalizer thread" prio=5 Id=13 RUNNABLE
22:56:20  
22:56:20  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
22:56:20  
22:56:20  "GC Worker" prio=5 Id=15 RUNNABLE
22:56:20  
22:56:20  "GC Worker" prio=5 Id=16 RUNNABLE
22:56:20  
22:56:20  "GC Worker" prio=5 Id=17 RUNNABLE
22:56:20  
22:56:20  "GC Worker" prio=5 Id=18 RUNNABLE
22:56:20  
22:56:20  "GC Worker" prio=5 Id=19 RUNNABLE
22:56:20  
22:56:20  "GC Worker" prio=5 Id=20 RUNNABLE
22:56:20  
22:56:20  "GC Worker" prio=5 Id=21 RUNNABLE
22:56:20  
22:56:20  "Attach API wait loop" prio=10 Id=24 RUNNABLE
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
22:56:20  
22:56:20  "MainThread" prio=5 Id=26 RUNNABLE
22:56:20  	at java.base@17.0.3-internal/java.lang.ProcessImpl.waitForInterruptibly(Native Method)
22:56:20  	at java.base@17.0.3-internal/java.lang.ProcessImpl.waitFor(ProcessImpl.java:561)
22:56:20  	at app//Basic.run(Basic.java:2765)
22:56:20  	at app//Basic.run(Basic.java:2746)
22:56:20  	at app//Basic.realMain(Basic.java:1839)
22:56:20  	at app//Basic.main(Basic.java:2827)
22:56:20  	at java.base@17.0.3-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:56:20  	at java.base@17.0.3-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:56:20  	at java.base@17.0.3-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:56:20  	at java.base@17.0.3-internal/java.lang.reflect.Method.invoke(Method.java:568)
22:56:20  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:56:20  	at java.base@17.0.3-internal/java.lang.Thread.run(Thread.java:889)
22:56:20  
22:56:20  "Thread-32" prio=5 Id=55 RUNNABLE
22:56:20  	at java.base@17.0.3-internal/java.io.FileInputStream.readBytes(Native Method)
22:56:20  	at java.base@17.0.3-internal/java.io.FileInputStream.read(FileInputStream.java:276)
22:56:20  	at java.base@17.0.3-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
22:56:20  	at java.base@17.0.3-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
22:56:20  	- locked java.io.BufferedInputStream@a62020f2
22:56:20  	at java.base@17.0.3-internal/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
22:56:20  	at java.base@17.0.3-internal/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
22:56:20  	at java.base@17.0.3-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
22:56:20  	- locked java.io.InputStreamReader@96f24914
22:56:20  	at java.base@17.0.3-internal/java.io.InputStreamReader.read(InputStreamReader.java:177)
22:56:20  	at java.base@17.0.3-internal/java.io.Reader.read(Reader.java:250)
22:56:20  	at app//Basic$StreamAccumulator.run(Basic.java:2732)
22:56:20  
22:56:20  "Thread-33" prio=5 Id=56 RUNNABLE
22:56:20  	at java.base@17.0.3-internal/java.io.FileInputStream.readBytes(Native Method)
22:56:20  	at java.base@17.0.3-internal/java.io.FileInputStream.read(FileInputStream.java:276)
22:56:20  	at java.base@17.0.3-internal/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
22:56:20  	at java.base@17.0.3-internal/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
22:56:20  	at java.base@17.0.3-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
22:56:20  	- locked java.io.InputStreamReader@1ba21cb1
22:56:20  	at java.base@17.0.3-internal/java.io.InputStreamReader.read(InputStreamReader.java:177)
22:56:20  	at java.base@17.0.3-internal/java.io.Reader.read(Reader.java:250)
22:56:20  	at app//Basic$StreamAccumulator.run(Basic.java:2732)
22:56:20  
22:56:20  "file lock watchdog" prio=10 Id=58 TIMED_WAITING
22:56:20  	at java.base@17.0.3-internal/java.lang.Object.wait(Native Method)
22:56:20  	at java.base@17.0.3-internal/java.lang.Object.wait(Object.java:219)
22:56:20  	at java.base@17.0.3-internal/java.util.TimerThread.mainLoop(Timer.java:563)
22:56:20  	at java.base@17.0.3-internal/java.util.TimerThread.run(Timer.java:516)
22:56:20  
22:56:20  "Attachment 53552" prio=10 Id=59 RUNNABLE
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$104/0x000000007f312a80.apply(Unknown Source)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
22:56:20  	at java.base@17.0.3-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
22:56:20  
22:56:20  
22:56:20  --- Timeout information end.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/499/
java/lang/ProcessBuilder/Basic.java#id0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/499/openjdk_test_output.tar.gz
```
00:09:52  ACTION: main -- Error. Program `C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java' timed out (timeout set to 2400000ms, elapsed time including timeout handling was 2416953ms).
00:09:52  REASON: User specified action: run main/othervm/timeout=300 Basic 
00:09:52  TIME:   2416.969 seconds
00:09:52  messages:
00:09:52  command: main Basic
00:09:52  reason: User specified action: run main/othervm/timeout=300 Basic 
00:09:52  Mode: othervm [/othervm specified]
00:09:52  Additional options from @modules: --add-modules java.base --add-opens java.base/java.lang=ALL-UNNAMED
00:09:52  Timeout information:
00:09:52  Running jcmd on process 2196
00:09:52  Dump written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_1679366443135\jdk_lang_1\work\scratch\0_1\core.20230321.000922.2196.0001.dmp
00:09:52  Dump written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_1679366443135\jdk_lang_1\work\scratch\0_1\javacore.20230321.000936.2196.0002.txt
00:09:52  Running jstack on process 2196
00:09:52  2023-03-21T00:09:37.742190600
00:09:52  Virtual machine: 2196 JVM information:
00:09:52  JRE 11 Windows Server 2019 amd64-64-Bit 20230320_524 (JIT enabled, AOT enabled)
00:09:52  OpenJ9   - c03c76e5071
00:09:52  OMR      - 1a20c5d2b24
00:09:52  JCL      - bd949902500 based on jdk-11.0.19+5
00:09:52  
00:09:52  "main" prio=5 Id=1 WAITING
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.waitImpl(Native Method)
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:251)
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:219)
00:09:52  	at java.base@11.0.19-internal/java.lang.Thread.join(Thread.java:766)
00:09:52  	at java.base@11.0.19-internal/java.lang.Thread.join(Thread.java:721)
00:09:52  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
00:09:52  
00:09:52  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
00:09:52  
00:09:52  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
00:09:52  
00:09:52  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
00:09:52  
00:09:52  "JIT Diagnostic Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
00:09:52  
00:09:52  "JIT-SamplerThread" prio=10 Id=7 TIMED_WAITING
00:09:52  
00:09:52  "IProfiler" prio=5 Id=8 RUNNABLE
00:09:52  
00:09:52  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.waitImpl(Native Method)
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:251)
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:219)
00:09:52  	at java.base@11.0.19-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
00:09:52  	at java.base@11.0.19-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
00:09:52  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
00:09:52  	at java.base@11.0.19-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
00:09:52  
00:09:52  "Finalizer thread" prio=5 Id=9 RUNNABLE
00:09:52  
00:09:52  "Concurrent Mark Helper" prio=1 Id=10 RUNNABLE
00:09:52  
00:09:52  "GC Worker" prio=5 Id=11 RUNNABLE
00:09:52  
00:09:52  "GC Worker" prio=5 Id=12 RUNNABLE
00:09:52  
00:09:52  "GC Worker" prio=5 Id=13 RUNNABLE
00:09:52  
00:09:52  "Attach API wait loop" prio=10 Id=16 RUNNABLE
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
00:09:52  
00:09:52  "MainThread" prio=5 Id=18 RUNNABLE
00:09:52  	at java.base@11.0.19-internal/java.lang.ProcessImpl.waitForInterruptibly(Native Method)
00:09:52  	at java.base@11.0.19-internal/java.lang.ProcessImpl.waitFor(ProcessImpl.java:559)
00:09:52  	at app//Basic.run(Basic.java:2770)
00:09:52  	at app//Basic.run(Basic.java:2751)
00:09:52  	at app//Basic.realMain(Basic.java:1839)
00:09:52  	at app//Basic.main(Basic.java:2832)
00:09:52  	at java.base@11.0.19-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:09:52  	at java.base@11.0.19-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:09:52  	at java.base@11.0.19-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:09:52  	at java.base@11.0.19-internal/java.lang.reflect.Method.invoke(Method.java:566)
00:09:52  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:09:52  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
00:09:52  
00:09:52  "Thread-29" prio=5 Id=47 RUNNABLE
00:09:52  	at java.base@11.0.19-internal/java.io.FileInputStream.readBytes(Native Method)
00:09:52  	at java.base@11.0.19-internal/java.io.FileInputStream.read(FileInputStream.java:279)
00:09:52  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
00:09:52  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
00:09:52  	- locked java.io.BufferedInputStream@73e72dac
00:09:52  	at java.base@11.0.19-internal/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
00:09:52  	at java.base@11.0.19-internal/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
00:09:52  	at java.base@11.0.19-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
00:09:52  	- locked java.io.InputStreamReader@8789d01f
00:09:52  	at java.base@11.0.19-internal/java.io.InputStreamReader.read(InputStreamReader.java:181)
00:09:52  	at java.base@11.0.19-internal/java.io.Reader.read(Reader.java:229)
00:09:52  	at app//Basic$StreamAccumulator.run(Basic.java:2737)
00:09:52  
00:09:52  "Thread-30" prio=5 Id=48 RUNNABLE
00:09:52  	at java.base@11.0.19-internal/java.io.FileInputStream.readBytes(Native Method)
00:09:52  	at java.base@11.0.19-internal/java.io.FileInputStream.read(FileInputStream.java:279)
00:09:52  	at java.base@11.0.19-internal/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
00:09:52  	at java.base@11.0.19-internal/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
00:09:52  	at java.base@11.0.19-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
00:09:52  	- locked java.io.InputStreamReader@876efc41
00:09:52  	at java.base@11.0.19-internal/java.io.InputStreamReader.read(InputStreamReader.java:181)
00:09:52  	at java.base@11.0.19-internal/java.io.Reader.read(Reader.java:229)
00:09:52  	at app//Basic$StreamAccumulator.run(Basic.java:2737)
00:09:52  
00:09:52  "file lock watchdog" prio=10 Id=50 TIMED_WAITING
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.waitImpl(Native Method)
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:251)
00:09:52  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:219)
00:09:52  	at java.base@11.0.19-internal/java.util.TimerThread.mainLoop(Timer.java:559)
00:09:52  	at java.base@11.0.19-internal/java.util.TimerThread.run(Timer.java:512)
00:09:52  
00:09:52  "Attachment portNumber: 54819" prio=10 Id=52 RUNNABLE
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
00:09:52  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
00:09:52  
00:09:52  
00:09:52  --- Timeout information end.
00:09:52  elapsed time (seconds): 2416.969
00:09:52  configuration:
00:09:52  Boot Layer
00:09:52    add modules: java.base           
00:09:52    add opens:   java.base/java.lang ALL-UNNAMED
00:09:52  
00:09:52  STDOUT:
00:09:52  This appears to be a Windows system.
00:09:52  This appears to be a Unicode-based OS.
00:09:52  Testing ASCII environment values
00:09:52  Testing Latin1 environment values
00:09:52  Testing directory .
00:09:52  Testing directory ..
00:09:52  Testing directory \
00:09:52  Testing directory C:
00:09:52  Testing directory c:
00:09:52  Testing directory C:\
00:09:52  Testing directory c:\
00:09:52  Testing directory \
00:09:52  Testing directory c:\windows  
00:09:52  Testing directory c:\Program Files
00:09:52  Testing directory c:\Program Files
00:09:52  Testing Unicode directory:.\ProcessBuilderDir??
00:09:52  Timeout refired 2400 times
```
