### ISSUE TITLE
JDK18 jdk_security4_FAILED Server returned HTTP response code: 401 for URL - RuntimeException: Failed to login as subject

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14499]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_extended.openjdk_x86-64_linux/6/`:
```
openjdk version "18" 2022-03-22
IBM Semeru Runtime Open Edition 18.0.0.0-m1 (build 18+35)
Eclipse OpenJ9 VM 18.0.0.0-m1 (build openj9-0.31.0-m1, JRE 18 Linux amd64-64-Bit Compressed References 20220211_28 (JIT enabled, AOT enabled)
OpenJ9   - 700cde7b8
OMR      - bb5d44b8c
JCL      - cdd4205c649 based on jdk-18+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security4_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F28%2Fibm-semeru-open-jre_x64_linux_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F28%2Fibm-semeru-open-testimage_x64_linux_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F28%2Fibm-semeru-open-jdk_x64_linux_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F28%2Fibm-semeru-open-debugimage_x64_linux_18_35_openj9-0.31.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk18&amp;RELEASE_TAG=v0.31.0-release&amp;OPENJ9_BRANCH=v0.31.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.31.0-release&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-02-11T07:38:42.542Z] variation: Mode150
[2022-02-11T07:38:42.542Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-02-11T07:40:47.341Z] TEST: sun/security/krb5/auto/BasicProc.java

[2022-02-11T07:41:59.361Z] TEST: sun/security/krb5/auto/HttpNegotiateServer.java

[2022-02-11T07:41:59.367Z] Failure unexpected when executing with the the logged in subject.
[2022-02-11T07:41:59.367Z] java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 401 for URL: http://host.web.domain:32805/a/b/c
[2022-02-11T07:41:59.367Z] 	at java.base/javax.security.auth.Subject.callAs(Subject.java:425)
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer.test8077155(HttpNegotiateServer.java:392)
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer.main(HttpNegotiateServer.java:239)
[2022-02-11T07:41:59.367Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-02-11T07:41:59.367Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-02-11T07:41:59.367Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-02-11T07:41:59.367Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-02-11T07:41:59.367Z] Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 401 for URL: http://host.web.domain:32805/a/b/c
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer.testConnect(HttpNegotiateServer.java:304)
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer$3.call(HttpNegotiateServer.java:383)
[2022-02-11T07:41:59.367Z] 	at java.base/javax.security.auth.Subject.lambda$callAs$0(Subject.java:418)
[2022-02-11T07:41:59.367Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:775)
[2022-02-11T07:41:59.367Z] 	at java.base/javax.security.auth.Subject.doAs(Subject.java:565)
[2022-02-11T07:41:59.367Z] 	at java.base/javax.security.auth.Subject.callAs(Subject.java:420)
[2022-02-11T07:41:59.367Z] 	... 6 more
[2022-02-11T07:41:59.367Z] Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: http://host.web.domain:32805/a/b/c
[2022-02-11T07:41:59.367Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
[2022-02-11T07:41:59.367Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1581)
[2022-02-11T07:41:59.367Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1579)
[2022-02-11T07:41:59.367Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:947)
[2022-02-11T07:41:59.367Z] 	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:989)
[2022-02-11T07:41:59.367Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1578)
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer.testConnect(HttpNegotiateServer.java:295)
[2022-02-11T07:41:59.367Z] 	... 11 more
[2022-02-11T07:41:59.367Z] java.lang.RuntimeException: Failed to login as subject
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer.test8077155(HttpNegotiateServer.java:399)
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer.main(HttpNegotiateServer.java:239)
[2022-02-11T07:41:59.367Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-02-11T07:41:59.367Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-02-11T07:41:59.367Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-02-11T07:41:59.367Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-02-11T07:41:59.367Z] java.lang.RuntimeException: Test error
[2022-02-11T07:41:59.367Z] 	at HttpNegotiateServer.main(HttpNegotiateServer.java:246)
[2022-02-11T07:41:59.367Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-02-11T07:41:59.367Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-02-11T07:41:59.367Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-02-11T07:41:59.367Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-02-11T07:41:59.367Z] 
[2022-02-11T07:41:59.367Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Test error

[2022-02-11T07:48:29.355Z] jdk_security4_0_FAILED
```

This is a failure cross platforms, appears re-occurrence of https://github.com/eclipse-openj9/openj9/issues/11268 at JDK18.

**Comment by tajila** [comment]
@mikezhang1234567890 can you please take a look at this

**Comment by mikezhang1234567890** [comment]
Looking into this.

**Comment by tajila** [comment]
@mikezhang1234567890 do you have an update on this

**Comment by mikezhang1234567890** [comment]
I've looked into the state of the AccessControlContext object during the exception, and it looks like the `domainCombiner` field is once again being set to null despite https://github.com/eclipse-openj9/openj9/pull/11664

Looking into why the fix is no longer working now.

**Comment by tajila** [comment]
Thanks for the update @mikezhang1234567890 

FYI @JasonFengJ9

**Comment by JasonFengJ9** [comment]
> I've looked into the state of the AccessControlContext object during the exception, and it looks like the domainCombiner field is once again being set to null despite the fix for https://github.com/eclipse-openj9/openj9/issues/11268

Just wondering if recent stack frame related changes such as `-XX:[+|-]ShowHiddenFrames` confused `getAccSnapshot()`.

**Comment by tajila** [comment]
Can you try it with `-XX:-ShowHiddenFrames` @mikezhang1234567890

**Comment by mikezhang1234567890** [comment]
Both `-XX:[+|-]ShowHiddenFrames` options fail.

**Comment by mikezhang1234567890** [comment]
Looks like `doPrivilegedWithCombiner(PrivilegedExceptionAction<T> action, AccessControlContext context, Permission... perms)` at https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/java/security/AccessController.java#L1004 is the method being called in this case, and with a null AccessControlContext.

Looking at stackslots output:
```
<1d7400> Bytecode frame: bp = 0x000000000022FAA8, sp = 0x000000000022FA98, pc = 0x00007FEA1D4D8ADC, cp = 0x00000000000844D0, arg0EA = 0x000000000022FAD0, flags = 0x0000000000000000
<1d7400> 	Method: java/security/AccessController.doPrivilegedWithCombiner(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;[Ljava/security/Permission;)Ljava/lang/Object; !j9method 0x0000000000084F50
<1d7400> 	Bytecode index = 44
<1d7400> 	Using local mapper
<1d7400> 	Locals starting at 0x000000000022FAD0 for 0x0000000000000005 slots
<1d7400> 		I-Slot: a0[0x000000000022FAD0] = 0x00000000FFE6B280  // PrivilegedExceptionAction sun/net/www/protocol/http/HttpURLConnection$9
<1d7400> 		I-Slot: a1[0x000000000022FAC8] = 0x0000000000000000  // AccessControlContext seems to be null
<1d7400> 		I-Slot: a2[0x000000000022FAC0] = 0x00000000FFE6B290  // Permission objects array, contains java/net/SocketPermission
<1d7400> 		I-Slot: t3[0x000000000022FAB8] = 0x0000000000000000
<1d7400> 		I-Slot: t4[0x000000000022FAB0] = 0x0000000000000000
```

I think we may need to create a context with `getContextHelper` if the context is null here.

**Comment by JasonFengJ9** [comment]
There are four `doPrivilegedWithCombiner` variants, two of them use `getContextHelper()` which was fixed by https://github.com/eclipse-openj9/openj9/pull/11664. The API https://github.com/eclipse-openj9/openj9/issues/14499#issuecomment-1048253180 will need a similar fix as well as https://github.com/eclipse-openj9/openj9/blob/a245e34090b3049f0339db03002a7a4a1c3b3460/jcl/src/java.base/share/classes/java/security/AccessController.java#L928

**Comment by pshipton** [comment]
@mikezhang1234567890 what is the outlook for the fix?

**Comment by mikezhang1234567890** [comment]
Ran into another issue where the `getAccSnapshot` call in `getContextHelper()` is returning null for the ProtectionDomain arrays it's supposed to return. Working through that at the moment.

**Comment by pshipton** [comment]
@mikezhang1234567890 now that https://github.com/eclipse-openj9/openj9/pull/14688 is merged, does it help with the problems?
