### ISSUE TITLE
OpenJDK FinalizationOption Test failed FinalizationOption.java:126

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14491]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Release/1 - [rh7-390-2](https://openj9-jenkins.osuosl.org/computer/rh7-390-2)
jdk_lang_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops`
java/lang/Object/FinalizationOption.java

I expect this is intermittent since (a) it only failed in 1/2 modes in the build and (b) it didn't fail in the internal M1 build.
Seems it didn't find the finalizer thread.

```
17:34:17  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Test failed.
17:34:17  REASON: User specified action: run main/othervm --finalization=enabled FinalizationOption yes 
17:34:17  TIME:   0.118 seconds
17:34:17  messages:
17:34:17  command: main --finalization=enabled FinalizationOption yes
17:34:17  reason: User specified action: run main/othervm --finalization=enabled FinalizationOption yes 
17:34:17  Mode: othervm [/othervm specified]
17:34:17  elapsed time (seconds): 0.118
17:34:17  configuration:
17:34:17  STDOUT:
17:34:17  Finalizer thread.    Expected: true   Actual: (none)   FAILED!
17:34:17  Call to finalize().  Expected: true   Actual: true   Passed.
17:34:17  STDERR:
17:34:17  java.lang.AssertionError: Test failed.
17:34:17  	at FinalizationOption.main(FinalizationOption.java:126)
17:34:17  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
17:34:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
17:34:17  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
17:34:17  	at java.base/java.lang.Thread.run(Thread.java:889)
```

**Comment by pshipton** [comment]
@tajila @JasonFengJ9 fyi

**Comment by pshipton** [comment]
Failed 1/10 in grinder https://openj9-jenkins.osuosl.org/job/Grinder/615
This seems like a test issue to me, like it's checking for the thread too early. It might fix it to reverse the order of the checks.
