### ISSUE TITLE
AIX javax/imageio/ReadAbortTest(WriteAbortTest).java - NPE: Cannot invoke "java.io.File.toPath()" because "this.file" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14505]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_extended.openjdk_ppc64_aix/3/`(`paix907`):
```
openjdk version "18" 2022-03-22
IBM Semeru Runtime Open Edition 18.0.0.0-m1 (build 18+35)
Eclipse OpenJ9 VM 18.0.0.0-m1 (build openj9-0.31.0-m1, JRE 18 AIX ppc64-64-Bit Compressed References 20220210_28 (JIT enabled, AOT enabled)
OpenJ9   - 700cde7b8
OMR      - bb5d44b8c
JCL      - cdd4205c649 based on jdk-18+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_imageio_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-jdk_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-jre_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-debugimage_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-testimage_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk18&amp;RELEASE_TAG=v0.31.0-release&amp;OPENJ9_BRANCH=v0.31.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.31.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-02-11T11:19:10.173Z] variation: Mode150
[2022-02-11T11:19:10.173Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-02-11T11:34:22.422Z] TEST: javax/imageio/ReadAbortTest.java

[2022-02-11T11:34:22.423Z] STDOUT:
[2022-02-11T11:34:22.423Z] Test for format bmp
[2022-02-11T11:34:22.423Z] STDERR:
[2022-02-11T11:34:22.423Z] java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "this.file" is null
[2022-02-11T11:34:22.423Z] 	at ReadAbortTest.<init>(ReadAbortTest.java:106)
[2022-02-11T11:34:22.423Z] 	at ReadAbortTest.main(ReadAbortTest.java:149)
[2022-02-11T11:34:22.423Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-02-11T11:34:22.423Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-02-11T11:34:22.423Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-02-11T11:34:22.423Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-02-11T11:34:22.423Z] 
[2022-02-11T11:34:22.423Z] JavaTest Message: Test threw exception: java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "this.file" is null

[2022-02-11T11:34:33.784Z] TEST: javax/imageio/WriteAbortTest.java

[2022-02-11T11:34:33.785Z] STDERR:
[2022-02-11T11:34:33.785Z] java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "this.file" is null
[2022-02-11T11:34:33.785Z] 	at WriteAbortTest.<init>(WriteAbortTest.java:101)
[2022-02-11T11:34:33.785Z] 	at WriteAbortTest.main(WriteAbortTest.java:144)
[2022-02-11T11:34:33.785Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-02-11T11:34:33.785Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-02-11T11:34:33.785Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-02-11T11:34:33.785Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-02-11T11:34:33.785Z] 
[2022-02-11T11:34:33.785Z] JavaTest Message: Test threw exception: java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "this.file" is null

[2022-02-11T11:34:58.671Z] jdk_imageio_0_FAILED
```

**Comment by pshipton** [comment]
Seems a machine/network problem or intermittent, as these tests passed when I ran them. Removing from milestone.

**Comment by JasonFengJ9** [comment]
Also observed at JDK17 - `job/Test_openjdk17_j9_extended.openjdk_ppc64_aix/47/` (`paix907`)

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk11_j9_extended.openjdk_ppc64_aix/65/`(`paix905`)
```
java version "11.0.15" 2022-04-19
IBM Semeru Runtime Certified Edition 11.0.15.0-rc1 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0-rc1 (build openj9-0.32.0-rc1, JRE 11 AIX ppc64-64-Bit Compressed References 20220419_278 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - da9a227f69 based on jdk-11.0.15+10)

[2022-04-20T08:04:48.973Z] java.lang.NullPointerException
[2022-04-20T08:04:48.973Z] 	at WriteAbortTest.<init>(WriteAbortTest.java:101)
[2022-04-20T08:04:48.973Z] 	at WriteAbortTest.main(WriteAbortTest.java:144)
[2022-04-20T08:04:48.973Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-04-20T08:04:48.973Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-04-20T08:04:48.973Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-04-20T08:04:48.973Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-04-20T08:04:48.973Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-04-20T08:04:48.973Z] 	at java.base/java.lang.Thread.run(Thread.java:871)
```

**Comment by pshipton** [comment]
Test failure output shows
```
Test for format bmp
```
Exception is at
```
        } finally {
            Files.delete(file.toPath());      <- line 101
        }
```
The testing is doing the following before it creates the file. I tried running this on the machine but it works. We'll have to modify the test to get more information about the failure.
```
            System.out.println("Test for format " + format);
            bimg = new BufferedImage(width, heght,
                    BufferedImage.TYPE_INT_RGB);

            Graphics2D g = bimg.createGraphics();
            g.setColor(srccolor);
            g.fillRect(0, 0, width, heght);
            g.dispose();

            file = File.createTempFile("src_", "." + format, new File("."));
```

**Comment by JasonFengJ9** [comment]
`AWTError ` appeared at `javax/imageio/MultiReadTest.java`.
NPE occurred at `javax/imageio/ReadAbortTest.java`.
50x grinder for `ReadAbortTest` only - `job/Grinder/22969/`

**Comment by pshipton** [comment]
It failed 82/100. Spread across 10 machines, they all had failures.
paix816, paix817, paix819, paix821 x 2, paix823, paix824, paix910
pll011 x 2

**Comment by pshipton** [comment]
Try a grinder with an update to the test /job/Grinder/22989/

**Comment by pshipton** [comment]
With the modified test you can see the following
```
20:19:47  java.awt.AWTError: Can't connect to X11 window server using 'unix:0' as the value of the DISPLAY variable.
20:19:47  	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
20:19:47  	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
20:19:47  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
20:19:47  	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
20:19:47  	at java.base/java.lang.Class.forNameImpl(Native Method)
20:19:47  	at java.base/java.lang.Class.forName(Class.java:346)
20:19:47  	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
20:19:47  	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
20:19:47  	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
20:19:47  	at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
20:19:47  	at ReadAbortTest.<init>(ReadAbortTest.java:64)
20:19:47  	at ReadAbortTest.main(ReadAbortTest.java:149)
```

**Comment by JasonFengJ9** [comment]
Tracking w/ `runtimes/infrastructure/issues/6155`
closing..
