### ISSUE TITLE
JDK18 AIX java/nio/channels/FileChannel/Transfer2GPlus.java - RuntimeException: Transfer too small: 1043881984

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14504]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_extended.openjdk_ppc64_aix/3/`(`paix907`):
```
openjdk version "18" 2022-03-22
IBM Semeru Runtime Open Edition 18.0.0.0-m1 (build 18+35)
Eclipse OpenJ9 VM 18.0.0.0-m1 (build openj9-0.31.0-m1, JRE 18 AIX ppc64-64-Bit Compressed References 20220210_28 (JIT enabled, AOT enabled)
OpenJ9   - 700cde7b8
OMR      - bb5d44b8c
JCL      - cdd4205c649 based on jdk-18+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_nio_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-jdk_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-jre_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-debugimage_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-aix-ppc64-openj9%2F28%2Fibm-semeru-open-testimage_ppc64_aix_18_35_openj9-0.31.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk18&amp;RELEASE_TAG=v0.31.0-release&amp;OPENJ9_BRANCH=v0.31.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.31.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-02-11T07:42:13.549Z] variation: Mode150
[2022-02-11T07:42:13.549Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-02-11T08:08:44.384Z] TEST: java/nio/channels/FileChannel/Transfer2GPlus.java

[2022-02-11T08:08:44.385Z] STDERR:
[2022-02-11T08:08:44.385Z] java.lang.RuntimeException: Transfer too small: 1043881984
[2022-02-11T08:08:44.385Z] 	at Transfer2GPlus.testToFileChannel(Transfer2GPlus.java:87)
[2022-02-11T08:08:44.385Z] 	at Transfer2GPlus.main(Transfer2GPlus.java:58)
[2022-02-11T08:08:44.385Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-02-11T08:08:44.385Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-02-11T08:08:44.385Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-02-11T08:08:44.385Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-02-11T08:08:44.385Z] 
[2022-02-11T08:08:44.385Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Transfer too small: 1043881984
[2022-02-11T08:08:44.385Z] JavaTest Message: shutting down test
[2022-02-11T08:08:44.385Z] 
[2022-02-11T08:08:44.385Z] STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Transfer too small: 1043881984

[2022-02-11T08:41:53.822Z] jdk_nio_0_FAILED
```

**Comment by pshipton** [comment]
Repeated the failure in https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/634
```
12:55:24  java.lang.RuntimeException: Transfer too small: 2133209088
12:55:24  	at Transfer2GPlus.testToFileChannel(Transfer2GPlus.java:87)
12:55:24  	at Transfer2GPlus.main(Transfer2GPlus.java:58)
```

**Comment by pshipton** [comment]
Looks like a test issue, I'll try adding an exception for AIX.
```
                    if (!Platform.isLinux())
                        throw new RuntimeException("Transfer too small: " + total);

                    // If this point is reached we're on Linux which cannot
                    // transfer all LENGTH bytes in one call to sendfile(2),
                    // so loop to get the rest.
```

**Comment by pshipton** [comment]
Updating the test resulted in 
```
13:27:12  java.io.IOException: No space left on device
13:27:12  	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
13:27:12  	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
13:27:12  	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137)
13:27:12  	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:81)
13:27:12  	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:72)
13:27:12  	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
13:27:12  	at java.base/sun.nio.ch.FileChannelImpl.transferToTrustedChannel(FileChannelImpl.java:605)
13:27:12  	at java.base/sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:699)
13:27:12  	at Transfer2GPlus.testToFileChannel(Transfer2GPlus.java:93)
13:27:12  	at Transfer2GPlus.main(Transfer2GPlus.java:58)
```

**Comment by pshipton** [comment]
@pushkarnk the problem is specific to certain machines. It fails on Termurin 18 if specific machines are used. The problem is with the test, it needs to be modified for AIX the same as it's modified for Linux. Similarly to Linux , this is due to the implementation using send_file() on AIX which may not transfer the entire contents in a single call. Can we pls fix the test at OpenJDK for AIX with backports to jdk17 and 18.

```
14:38:03  openjdk version "18-beta" 2022-03-22
14:38:03  OpenJDK Runtime Environment Temurin-18+35-202202142340 (build 18-beta+35-202202142340)
14:38:03  OpenJDK 64-Bit Server VM Temurin-18+35-202202142340 (build 18-beta+35-202202142340, mixed mode)

...

14:40:23  java.lang.RuntimeException: Transfer too small: 1043742720
14:40:23  	at Transfer2GPlus.testToFileChannel(Transfer2GPlus.java:87)
14:40:23  	at Transfer2GPlus.main(Transfer2GPlus.java:58)
```

The problem is not specific to jdk18 it occurs on jdk17 as well. Fixing the labels and removing from the Java 18 milestone plan.

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_extended.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix_testList_3/89/)(`paix824`)
```
[2025-01-04T20:36:07.756Z] variation: Mode150
[2025-01-04T20:36:07.756Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-01-04T20:42:32.180Z] TEST: java/nio/channels/FileChannel/Transfer2GPlus.java

[2025-01-04T20:42:32.183Z] STDERR:
[2025-01-04T20:42:32.183Z] java.lang.RuntimeException: Transfer too small: 1550614528
[2025-01-04T20:42:32.183Z] 	at Transfer2GPlus.testToFileChannel(Transfer2GPlus.java:116)
[2025-01-04T20:42:32.183Z] 	at Transfer2GPlus.main(Transfer2GPlus.java:77)
[2025-01-04T20:42:32.183Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2025-01-04T20:42:32.183Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2025-01-04T20:42:32.183Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2025-01-04T20:42:32.183Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)

[2025-01-04T21:01:01.842Z] jdk_nio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_extended.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix_testList_2/206/)(`paix822`)
```
[2025-03-11T15:57:42.967Z] variation: Mode650
[2025-03-11T15:57:42.967Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-03-11T16:04:56.251Z] TEST: java/nio/channels/FileChannel/Transfer2GPlus.java

[2025-03-11T16:04:56.277Z] STDERR:
[2025-03-11T16:04:56.277Z] java.lang.RuntimeException: Transfer too small: 1237053440
[2025-03-11T16:04:56.277Z] 	at Transfer2GPlus.testToFileChannel(Transfer2GPlus.java:116)
[2025-03-11T16:04:56.277Z] 	at Transfer2GPlus.main(Transfer2GPlus.java:77)
[2025-03-11T16:04:56.277Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2025-03-11T16:04:56.277Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2025-03-11T16:04:56.277Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2025-03-11T16:04:56.277Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)

[2025-03-11T16:23:28.662Z] jdk_nio_1_FAILED
```
