### ISSUE TITLE
Failure in value types ValueTypeUnsafeTests_2 test testPutValueOnVTWithLongFields on s390x_linux

### ISSUE THREAD

**Issue by hzongaro** [eclipse-openj9/openj9#14529]
Failure running functional/Valhalla test `ValueTypeUnsafeTests_2` in `testPutValueOnVTWithLongFields` on s390x_linux in .  Failure can be found in [internal server Pipeline-Build-Test-Personal build #11816](https://<internal-server-name>/job/Pipeline-Build-Test-Personal/11816/).  Test fails running with `-Xint`.

[Grinder run](https://<internal-server-name>>/job/Grinder/21031/) failed 10/10.

Assertion failure reported:

```
FAILED: testPutValueOnVTWithLongFields
java.lang.AssertionError: expected [23427] but found [0]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:547)
	at org.testng.Assert.assertEquals(Assert.java:557)
	at org.openj9.test.lworld.ValueTypeUnsafeTests.testPutValueOnVTWithLongFields(ValueTypeUnsafeTests.java:449)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by hzongaro** [comment]
@tajila - FYI

**Comment by hzongaro** [comment]
Sorry - I should have included a [link for starting a grinder run.](https://server/job/Grinder/parambuild/?TARGET=ValueTypeUnsafeTests_2&SDK_RESOURCE=upstream&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdkValhalla_j9_sanity.functional_s390x_linux_valhalla_Personal&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&EXTRA_DOCKER_ARGS=&VENDOR_TEST_DIRS=functional&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_s390x_linux_valhalla_Personal%2F9%2FOpenJ9-JDKnext-s390x_linux_valhalla-20220211-101243.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_s390x_linux_valhalla_Personal%2F9%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=Valhalla&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&ITERATIONS=10&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JCK_GIT_BRANCH=master&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.valuetypes.git&OPENJ9_BRANCH=master&OPENJ9_SHA=48aad48d28b523ec3b05554886ca8292008ec270&JCK_GIT_REPO=&RELEASE_TAG=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=true&CODE_COVERAGE=false&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&UPSTREAM_TEST_JOB_NUMBER=6&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=false&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=functional%2FValhalla%2Cfunctional%2Fcmdline_options_tester%2Cfunctional%2FcmdLineTests%2Fvaluetypeddrtests&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None)

**Comment by tajila** [comment]
@hangshao0

**Comment by hangshao0** [comment]
@ehrenjulzert, it is a test recently added by you, can you look into this ?

**Comment by ehrenjulzert** [comment]
okay, looking into this now
