### ISSUE TITLE
[JDK11 OJDK-MH] *IndexOutOfBoundsException from MethodHandles.collectArguments

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14547]
The below failure(s) is(are) only seen when OJDK MHs are enabled in OpenJ9.

### Errors

```
[2022-02-10T17:19:40.271Z] FAILED: test_CollectArgumentsNegative
[2022-02-10T17:19:40.271Z] java.lang.ArrayIndexOutOfBoundsException
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodType.parameterType(MethodType.java:727) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodHandles.collectArgumentsChecks(MethodHandles.java:4041) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodHandles.collectArguments(MethodHandles.java:4019) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at org.openj9.test.java.lang.invoke.Test_AdaptorTests.test_CollectArgumentsNegative(Test_AdaptorTests.java:88) from jdk.internal.loader.ClassLoaders$AppClassLoader@4eadd99d(file
:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

```
[2022-02-10T17:19:40.271Z] FAILED: test_VoidCollectArgumentsNegative
[2022-02-10T17:19:40.271Z] java.lang.IndexOutOfBoundsException: bad index: 3
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodType.newIndexOutOfBoundsException(MethodType.java:184) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodType.insertParameterTypes(MethodType.java:397) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodType.insertParameterTypes(MethodType.java:438) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodHandles.collectArgumentsChecks(MethodHandles.java:4039) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at java.base/java.lang.invoke.MethodHandles.collectArguments(MethodHandles.java:4019) from jrt:/java.base
[2022-02-10T17:19:40.271Z]      at org.openj9.test.java.lang.invoke.Test_AdaptorTests.test_VoidCollectArgumentsNegative(Test_AdaptorTests.java:204) from jdk.internal.loader.ClassLoaders$AppClassLoader@4eadd99d
(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

### Failing Test Targets

- `BUILD_LIST=functional`
    - `JCL_Test_none_SCC_0`
    - `JCL_Test_0`
    - `JCL_Test_2`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK11 with OJDK MHs enabled

Refer to https://github.com/eclipse-openj9/openj9/issues/14540.

**Comment by babsingh** [comment]
OpenJDK bug: https://bugs.openjdk.java.net/browse/JDK-8259922

Fix: https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ab6b9c35c7541ea628b028cb1357b904a72de5d9

Only available in JDK17+. Needs to be back-ported to JDK8 and JDK11 extension repos.

**Comment by babsingh** [comment]
Related: https://github.com/eclipse-openj9/openj9/issues/11922

**Comment by babsingh** [comment]
This is fixed by
- https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/502.
