### ISSUE TITLE
JCL_Test_1 test_join3 Joined thread is not alive

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14586]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR_testList_0/58 - [p8-java1-ibm05](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm05)
JCL_Test_1 `-XX:RecreateClassfileOnload`

```
11:57:25  FAILED: test_join3
11:57:25  java.lang.AssertionError: Joined thread is not alive
11:57:25  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@58b52b25(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR_testList_0/aqa-tests/TKG/lib/testng.jar)
11:57:25  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@58b52b25(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR_testList_0/aqa-tests/TKG/lib/testng.jar)
11:57:25  	at org.openj9.test.java.lang.Test_Thread.test_join3(Test_Thread.java:875) from jdk.internal.loader.ClassLoaders$AppClassLoader@58b52b25(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```
This occurred in an OMR acceptance build containing the change https://github.com/eclipse/omr/pull/6363
@jdmpapin we haven't seen this failure before, could it be related to your change?

**Comment by pshipton** [comment]
@JasonFengJ9 @keithc-ca if it's not the OMR change, I wonder if it's related to https://github.com/eclipse-openj9/openj9/pull/14355

**Comment by jdmpapin** [comment]
I won't say it's impossible but I would pretty surprised if that failure is related to my change

**Comment by pshipton** [comment]
10x x 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/677/

**Comment by keithc-ca** [comment]
I think the test is somewhat fragile. There's no guarantee that the thread running the test will not be delayed beyond the 3 seconds that the `SimpleThread` takes to complete.

**Comment by JasonFengJ9** [comment]
It doesn't seem #14355 caused this kind of failure.
It could be an AIX machine problem unless the failure can be reproduced at a reasonable rate for further investigation.

**Comment by pshipton** [comment]
The 50x grinder didn't repeat it. I'm willing to ignore the failure based on Keith's analysis of the test case, and promote the OMR build.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK_testList_0/82 - [p8-java1-ibm04](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm04)
JCL_Test_1 `-XX:RecreateClassfileOnload`
```
07:50:35  FAILED: test_join3
07:50:35  java.lang.AssertionError: Joined thread is not alive
07:50:35  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@870bf882(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK_testList_0/aqa-tests/TKG/lib/testng.jar)
07:50:35  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@870bf882(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK_testList_0/aqa-tests/TKG/lib/testng.jar)
07:50:35  	at org.openj9.test.java.lang.Test_Thread.test_join3(Test_Thread.java:695) from jdk.internal.loader.ClassLoaders$AppClassLoader@870bf882(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR_testList_1/85 - [p8-java1-ibm06](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm06)
JCL_Test_2 `-XX:+CompactStrings`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_OpenJDK17_testList_0/21
JCL_Test_0 `NoOptions`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR_testList_1/143
JCL_Test_1 `-XX:RecreateClassfileOnload`
