### ISSUE TITLE
OpenJDK ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest Didn't get the expected IllegalCallerException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14599]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/1/
java/lang/ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest.java
```
15:25:21  rerun:
15:25:21  cd /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/scratch/1 && \
15:25:21  DISPLAY=:0 \
15:25:21  HOME=/home/jenkins \
15:25:21  LANG=en_US.UTF-8 \
15:25:21  PATH=/bin:/usr/bin:/usr/sbin \
15:25:21      /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
15:25:21          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops' \
15:25:21          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-XX:+UseCompressedOops' \
15:25:21          -Dtest.compiler.opts= \
15:25:21          -Dtest.java.opts= \
15:25:21          -Dtest.jdk=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
15:25:21          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
15:25:21          -Dtest.timeout.factor=8.0 \
15:25:21          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
15:25:21          -Dtest.root=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
15:25:21          -Dtest.name=java/lang/ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest.java \
15:25:21          -Dtest.file=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest.java \
15:25:21          -Dtest.src=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ClassLoader/exeNullCallerClassLoaderTest \
15:25:21          -Dtest.src.path=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ClassLoader/exeNullCallerClassLoaderTest:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib \
15:25:21          -Dtest.classes=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest.d \
15:25:21          -Dtest.class.path=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest.d:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/test/lib \
15:25:21          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest.d:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ClassLoader/exeNullCallerClassLoaderTest:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/test/lib \
15:25:21          -classpath /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/ClassLoader/exeNullCallerClassLoaderTest/NullCallerClassLoaderTest.d:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ClassLoader/exeNullCallerClassLoaderTest:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/test/lib:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
15:25:21          NullCallerClassLoaderTest
15:25:21  STDOUT:
15:25:21  Launching: /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native/NullCallerClassLoaderTest shared library path: /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image/lib/server
15:25:21  [2022-02-24T20:25:20.645996321Z] Gathering output for process 2720979
15:25:21  ERROR: Didn't get the expected IllegalCallerException.
15:25:21  
15:25:21  [2022-02-24T20:25:20.732185397Z] Waiting for completion for process 2720979
15:25:21  [2022-02-24T20:25:20.732286278Z] Waiting for completion finished for process 2720979
15:25:21  [2022-02-24T20:25:20.732328358Z] Waiting for completion for process 2720979
15:25:21  [2022-02-24T20:25:20.732364838Z] Waiting for completion finished for process 2720979
15:25:21  STDERR:
15:25:21  
15:25:21   stdout: [ERROR: Didn't get the expected IllegalCallerException.
15:25:21  ];
15:25:21   stderr: []
15:25:21   exitValue = 255
15:25:21  
15:25:21  java.lang.RuntimeException: Expected to get exit value of [0]
15:25:21  
15:25:21  	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
15:25:21  	at NullCallerClassLoaderTest.main(NullCallerClassLoaderTest.java:68)
```

@tajila

**Comment by pshipton** [comment]
This test was removed/replaced in https://github.com/ibmruntimes/openj9-openjdk-jdk19/commit/0a3b8abd2bb
I find a new issue for the replacement jni/nullCaller/NullCallerTest.java https://github.com/eclipse-openj9/openj9/issues/15168

I'm removing the `test excluded` label and closing this issue. The obsolete test can be removed from the exclude list when 15168 is resolved.
