### ISSUE TITLE
OpenJDK Class/ArrayType IllegalArgumentException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14598]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/1/
java/lang/Class/ArrayType.java
```
15:25:20  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.IllegalArgumentException
15:25:20  REASON: Assumed action based on file name: run main ArrayType 
15:25:20  TIME:   0.063 seconds
15:25:20  messages:
15:25:20  command: main ArrayType
15:25:20  reason: Assumed action based on file name: run main ArrayType 
15:25:20  Mode: agentvm
15:25:20  Agent id: 5
15:25:20  elapsed time (seconds): 0.063
15:25:20  configuration:
15:25:20  Boot Layer
15:25:20    class path: /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar 
15:25:20                /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar 
15:25:20                /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar 
15:25:20                /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/hamcrest.jar 
15:25:20                /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar 
15:25:20                /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar 
15:25:20                /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar 
15:25:20    patch:      java.base /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/patches/java.base
15:25:20  
15:25:20  Test Layer
15:25:20    class path: /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/Class/ArrayType.d
15:25:20                /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Class
15:25:20  
15:25:20  rerun:
15:25:20  cd /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/scratch/1 && \
15:25:20  DISPLAY=:0 \
15:25:20  HOME=/home/jenkins \
15:25:20  LANG=en_US.UTF-8 \
15:25:20  PATH=/bin:/usr/bin:/usr/sbin \
15:25:20      /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
15:25:20          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops' \
15:25:20          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-XX:+UseCompressedOops' \
15:25:20          -Dtest.compiler.opts= \
15:25:20          -Dtest.java.opts= \
15:25:20          -Dtest.jdk=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
15:25:20          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
15:25:20          -Dtest.timeout.factor=8.0 \
15:25:20          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
15:25:20          -Dtest.root=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
15:25:20          -Dtest.name=java/lang/Class/ArrayType.java \
15:25:20          -Dtest.file=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Class/ArrayType.java \
15:25:20          -Dtest.src=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Class \
15:25:20          -Dtest.src.path=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Class \
15:25:20          -Dtest.classes=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/Class/ArrayType.d \
15:25:20          -Dtest.class.path=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/Class/ArrayType.d \
15:25:20          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/Class/ArrayType.d:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Class \
15:25:20          -classpath /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16457342788103/jdk_lang_0/work/classes/0/java/lang/Class/ArrayType.d:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Class:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
15:25:20          ArrayType
15:25:20  STDERR:
15:25:20  java.lang.IllegalArgumentException
15:25:20  	at java.base/java.lang.Class.arrayType(Class.java:4782)
15:25:20  	at ArrayType.expectException(ArrayType.java:42)
15:25:20  	at ArrayType.main(ArrayType.java:35)
```

@tajila

**Comment by pshipton** [comment]
Fixed via https://github.com/eclipse-openj9/openj9/pull/15298 and un-excluded via https://github.com/adoptium/aqa-tests/pull/3754
