### ISSUE TITLE
OpenJDK Cipher/AES/TestCopySafe Error in Native CipherBlockChaining

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14597]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly/1/
com/sun/crypto/provider/Cipher/AES/TestCopySafe.java
```
16:15:50  java.security.ProviderException: Error in Native CipherBlockChaining
16:15:50  	at java.base/com.sun.crypto.provider.NativeCipherBlockChaining.encrypt(NativeCipherBlockChaining.java:269)
16:15:50  	at java.base/com.sun.crypto.provider.NativeCipherBlockChaining.decrypt(NativeCipherBlockChaining.java:301)
16:15:50  	at java.base/com.sun.crypto.provider.FeedbackCipher.decryptFinal(FeedbackCipher.java:203)
16:15:50  	at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1021)
16:15:50  	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:970)
16:15:50  	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:857)
16:15:50  	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:478)
16:15:50  	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2418)
16:15:50  	at TestCopySafe.test(TestCopySafe.java:165)
16:15:50  	at TestCopySafe.main(TestCopySafe.java:77)
16:15:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
16:15:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
16:15:50  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
16:15:50  	at java.base/java.lang.Thread.run(Thread.java:889)
```
```
        int ret;
        synchronized (this) {
            ret = nativeCrypto.CBCUpdate(nativeContext, plain, plainOffset,
                                            plainLen, cipher, cipherOffset);
        }
        if (ret == -1) {
            throw new ProviderException("Error in Native CipherBlockChaining");       <------------ 269
        }
```

@ashbm5 this is in the head stream, the future jdk19

**Comment by ashbm5** [comment]
This is due to EVP_EncryptUpdate/EVP_DecryptUpdate not supporting partially overlapping buffers.

**Comment by ashbm5** [comment]
code fix merged for jdk19

**Comment by vij-singh** [comment]
Has this one been resolved now?

**Comment by pshipton** [comment]
I see https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/550 for jdk8, and 11, 17, 18, head and addressed above. Closing.
