### ISSUE TITLE
testOpenJ9DiagnosticsMXBean_0 NullPointerException: Cannot read the array length because "<local8>" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14604]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Nightly_testList_0/161
testOpenJ9DiagnosticsMXBean_0
```
23:56:52  Feb 25, 2022 4:50:24 AM com.sun.jmx.remote.internal.ClientCommunicatorAdmin restart
23:56:52  WARNING: Failed to restart: java.rmi.NoSuchObjectException: no such object in table
23:56:52  Feb 25, 2022 4:50:24 AM com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker run
23:56:52  WARNING: Failed to check connection: java.rmi.NoSuchObjectException: no such object in table
23:56:52  Feb 25, 2022 4:50:24 AM com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker run
23:56:52  WARNING: stopping
23:56:53  FAILED CONFIGURATION: @AfterClass tearDown
23:56:53  java.lang.NullPointerException: Cannot read the array length because "<local8>" is null
23:56:53  	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.tearDown(TestOpenJ9DiagnosticsMXBean.java:196)
23:56:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:56:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
23:56:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:56:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
23:56:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
23:56:53  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
23:56:53  	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
23:56:53  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
23:56:53  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
23:56:53  	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
23:56:53  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
23:56:53  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
23:56:53  	at org.testng.TestRunner.run(TestRunner.java:505)
23:56:53  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
23:56:53  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
23:56:53  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
23:56:53  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
```
```
			File fdir = new File("." + File.separator + directory);
			File[] files = fdir.listFiles();
			for (File file : files) {             <- 196
```

**Comment by pshipton** [comment]
Seems like a network problem.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_0/210
testOpenJ9DiagnosticsMXBean_0
```
java.lang.NullPointerException
	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.tearDown(TestOpenJ9DiagnosticsMXBean.java:196)
```

The javadoc for listFiles() states "If this abstract pathname does not denote a directory, then this method returns null." so it seems one of the expected directories doesn't exist.

Earlier in the output the following is seen.
```
WARNING: The server has decided to close this client connection.
JVMDUMP034I User requested Snap dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/output_16460262602097/testOpenJ9DiagnosticsMXBean_0/Snap.20220228.035315.20533.0006.trc' through com.ibm.jvm.Dump.SnapDump
Feb 28, 2022 3:53:15 AM ClientCommunicatorAdmin Checker-run
WARNING: Failed to check connection: java.net.SocketException: Connection reset
Feb 28, 2022 3:53:15 AM ClientCommunicatorAdmin Checker-run
WARNING: stopping
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/6
```
00:53:36  [TestOpenJ9DiagnosticsMXBean] [INFO] Starting Remote Server to Monitor!
00:53:36  [TestOpenJ9DiagnosticsMXBean] [INFO] [/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java, -Xdump:dynamic, -classpath, /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar, -Dcom.sun.management.jmxremote.port=9999, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Djava.lock.file=/tmp/tmp5504949718708273215.lock, org.openj9.test.java.lang.management.RemoteProcess]
00:53:37  [RemoteProcess] [INFO] =========RemoteProcess Starts!=========
00:53:37  [JvmCpuMonitorMXBeanTest] [INFO] child started
00:53:37  [TestOpenJ9DiagnosticsMXBean] [INFO] Staring remote server finished
00:53:38  JVMDUMP039I Processing dump event "allocation", detail "5264 bytes, type byte[]" at 2022/09/24 04:53:29 - please wait.
00:53:38  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local/javacore_alloc.txt' in response to an event
00:53:38  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local/javacore_alloc.txt
00:53:38  JVMDUMP013I Processed dump event "allocation", detail "5264 bytes, type byte[]".
00:53:38  JVMDUMP039I Processing dump event "catch", detail "java/io/UnsupportedEncodingException" at 2022/09/24 04:53:29 - please wait.
00:53:38  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local/javacore_unsupported.txt' in response to an event
00:53:38  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local/javacore_unsupported.txt
00:53:38  JVMDUMP013I Processed dump event "catch", detail "java/io/UnsupportedEncodingException".
00:53:38  JVMDUMP007I JVM Requesting Heap dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/heapdump.20220924.045329.16187726.0003.txt'
00:53:39  JVMDUMP010I Heap dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/heapdump.20220924.045329.16187726.0003.txt
00:53:39  JVMDUMP034I User requested Java dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/javacore.20220924.045331.16187726.0004.txt' through com.ibm.jvm.Dump.JavaDump
00:53:39  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/javacore.20220924.045331.16187726.0004.txt
00:53:39  JVMDUMP034I User requested Heap dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/heapdump.20220924.045331.16187726.0005.phd' through com.ibm.jvm.Dump.HeapDump
00:53:39  JVMDUMP010I Heap dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/heapdump.20220924.045331.16187726.0005.phd
00:53:39  JVMDUMP034I User requested Snap dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/Snap.20220924.045331.16187726.0006.trc' through com.ibm.jvm.Dump.SnapDump
00:53:39  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/Snap.20220924.045331.16187726.0006.trc
00:53:39  JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/core.20220924.045331.16187726.0007.dmp' through com.ibm.jvm.Dump.SystemDump
00:58:01  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/core.20220924.045331.16187726.0007.dmp
00:58:01  JVMDUMP034I User requested Java dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/javacore.20220924.045751' through com.ibm.jvm.Dump.javaDumpToFile
00:58:01  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/javacore.20220924.045751
00:58:01  JVMDUMP034I User requested Heap dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/heapdump.045752' through com.ibm.jvm.Dump.heapDumpToFile
00:58:01  JVMDUMP010I Heap dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/heapdump.045752
00:58:01  JVMDUMP034I User requested Snap dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/Snap.16187726.trc' through com.ibm.jvm.Dump.snapDumpToFile
00:58:01  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/Snap.16187726.trc
00:58:01  JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/core.16187726.dmp' through com.ibm.jvm.Dump.systemDumpToFile
01:04:08  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/output_16639920103166/testOpenJ9DiagnosticsMXBean_0/./local_dumps/core.16187726.dmp
01:04:08  Sep 24, 2022 5:03:56 AM com.sun.jmx.remote.internal.ClientCommunicatorAdmin restart
01:04:08  WARNING: Failed to restart: java.rmi.NoSuchObjectException: no such object in table
01:04:08  Sep 24, 2022 5:03:57 AM com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker run
01:04:08  WARNING: Failed to check connection: java.rmi.NoSuchObjectException: no such object in table
01:04:08  Sep 24, 2022 5:03:57 AM com.sun.jmx.remote.internal.ClientCommunicatorAdmin$Checker run
01:04:08  WARNING: stopping
01:04:08  FAILED CONFIGURATION: @AfterClass tearDown
01:04:08  java.lang.NullPointerException: Cannot read the array length because "<local8>" is null
01:04:08  	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.tearDown(TestOpenJ9DiagnosticsMXBean.java:196)
```
