### ISSUE TITLE
OpenJDK util/stream/IterateTest IncompatibleClassChangeError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14625]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/217
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/stream/test/org/openjdk/tests/java/util/stream/IterateTest.java

```
02:18:30  ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 0
02:18:30  REASON: Assumed action based on file name: run testng org.openjdk.tests.java.util.stream.IterateTest 
02:18:30  TIME:   1.119 seconds
02:18:30  messages:
02:18:30  command: testng org.openjdk.tests.java.util.stream.IterateTest
02:18:30  reason: Assumed action based on file name: run testng org.openjdk.tests.java.util.stream.IterateTest 
02:18:30  Mode: othervm [test or library overrides a system module]
02:18:30  elapsed time (seconds): 1.119
02:18:30  configuration:
02:18:30  Boot Layer
02:18:30    add reads: java.base ALL-UNNAMED
02:18:30    patch:     java.base /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16461980929195/jdk_util_0/work/classes/lib/testlibrary/bootlib/java.base
02:18:30  
02:18:30  STDOUT:
02:18:30  [TestNG] Running:
02:18:30    java/util/stream/test/org/openjdk/tests/java/util/stream/IterateTest.java
02:18:30  
02:18:30  config java.util.stream.LoggingTestCase.before(): success
02:18:30  test org.openjdk.tests.java.util.stream.IterateTest.testIterate([], RefTestData[ref.empty]): success
02:18:30  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@9be48e60): success
02:18:30  config java.util.stream.LoggingTestCase.before(): success
02:18:30  test org.openjdk.tests.java.util.stream.IterateTest.testIterate([1], RefTestData[ref.one]): success
02:18:30  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@3d3c06a0): success
02:18:30  config java.util.stream.LoggingTestCase.before(): success
02:18:30  test org.openjdk.tests.java.util.stream.IterateTest.testIterate(java.util.ImmutableCollections$ListN@f2b6b670, RefTestData[ref.ten]): success
02:18:30  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@7590f1c3): success
02:18:30  config java.util.stream.LoggingTestCase.before(): success
02:18:30  test org.openjdk.tests.java.util.stream.IterateTest.testIterate(java.util.ImmutableCollections$ListN@a56245da, RefTestData[ref.nullCheck]): success
02:18:30  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@494f0a9d): success
02:18:30  config java.util.stream.LoggingTestCase.before(): success
02:18:30  test org.openjdk.tests.java.util.stream.IterateTest.testIterate([], IntTestData[int.empty]): success
02:18:30  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@6b758a6): success
02:18:30  config java.util.stream.LoggingTestCase.before(): success
02:18:30  test org.openjdk.tests.java.util.stream.IterateTest.testIterate([1], IntTestData[int.one]): success
02:18:30  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@f646e183): failure
02:18:30  java.lang.IncompatibleClassChangeError
02:18:30  	at org.testng.internal.Invoker.runConfigurationListeners(Invoker.java:1662)
02:18:30  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:209)
02:18:30  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:708)
02:18:30  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
02:18:30  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
02:18:30  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:18:30  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
02:18:30  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
02:18:30  	at org.testng.TestRunner.run(TestRunner.java:623)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Release/39
```
10:00:44  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@250169e9): failure
10:00:44  java.lang.IncompatibleClassChangeError
10:00:44  	at org.testng.internal.Invoker.runConfigurationListeners(Invoker.java:1662)
10:00:44  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:209)
10:00:44  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:708)
10:00:44  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
10:00:44  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
10:00:44  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
10:00:44  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
10:00:44  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
10:00:44  	at org.testng.TestRunner.run(TestRunner.java:623)
10:00:44  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
10:00:44  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
10:00:44  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
10:00:44  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
10:00:44  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
10:00:44  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
10:00:44  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
10:00:44  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
10:00:44  	at org.testng.TestNG.run(TestNG.java:1018)
10:00:44  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
10:00:44  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
10:00:44  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:00:44  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:00:44  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:00:44  	at java.lang.reflect.Method.invoke(Method.java:498)
10:00:44  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:00:44  	at java.lang.Thread.run(Thread.java:826)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/546
jdk_util_0
java/util/stream/test/org/openjdk/tests/java/util/stream/CountTest.java
```
23:37:10  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@a8b64a9c): failure
23:37:10  java.lang.IncompatibleClassChangeError
23:37:10  	at org.testng.internal.Invoker.runConfigurationListeners(Invoker.java:1662)
23:37:10  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:209)
23:37:10  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:708)
23:37:10  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
23:37:10  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
23:37:10  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
23:37:10  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
23:37:10  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
23:37:10  	at org.testng.TestRunner.run(TestRunner.java:623)
23:37:10  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
23:37:10  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
23:37:10  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
23:37:10  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
23:37:10  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
23:37:10  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
23:37:10  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
23:37:10  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
23:37:10  	at org.testng.TestNG.run(TestNG.java:1018)
23:37:10  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
23:37:10  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
23:37:10  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:37:10  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:37:10  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:37:10  	at java.lang.reflect.Method.invoke(Method.java:498)
23:37:10  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:37:10  	at java.lang.Thread.run(Thread.java:826)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly_testList_2/90
jdk_util_1
java/util/stream/test/org/openjdk/tests/java/util/stream/CountTest.java
```
03:36:15  test org.openjdk.tests.java.util.stream.CountTest.testOps("SpinedList:0..1000", java.util.stream.TestData$AbstractTestData$IntTestData@e2acd456): failure
03:36:15  java.lang.ClassCastException: [I incompatible with [D
03:36:15  	at java.util.stream.SpinedBuffer$OfDouble.arrayLength(SpinedBuffer.java:950)
03:36:15  	at java.util.stream.SpinedBuffer$OfPrimitive$BaseSpliterator.trySplit(SpinedBuffer.java:696)
03:36:15  	at java.util.stream.SpinedBuffer$OfPrimitive$BaseSpliterator.trySplit(SpinedBuffer.java:596)
03:36:15  	at java.util.stream.AbstractTask.compute(AbstractTask.java:308)
03:36:15  	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
03:36:15  	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
03:36:15  	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
03:36:15  	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
03:36:15  	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
03:36:15  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:240)
03:36:15  	at java.util.stream.LongPipeline.reduce(LongPipeline.java:461)
03:36:15  	at java.util.stream.LongPipeline.sum(LongPipeline.java:419)
03:36:15  	at java.util.stream.IntPipeline.count(IntPipeline.java:482)
03:36:15  	at java.util.stream.OpTestCase$BaseTerminalTestScenario.run(OpTestCase.java:450)
03:36:15  	at java.util.stream.OpTestCase$ExerciseDataTerminalBuilder.exercise(OpTestCase.java:574)
03:36:15  	at org.openjdk.tests.java.util.stream.CountTest.testOps(CountTest.java:67)
```
