### ISSUE TITLE
OpenJDK util/stream/WhileOpStatefulTest testCountTakeWithCount RuntimeException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14639]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/224
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java

```
01:34:00  test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithCount(): failure
01:34:00  java.lang.RuntimeException: java.lang.RuntimeException
01:34:00  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
01:34:00  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
01:34:00  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
01:34:00  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
01:34:00  	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
01:34:00  	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
01:34:00  	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
01:34:00  	at java.base/java.util.stream.WhileOps$3.opEvaluateParallel(WhileOps.java:197)
01:34:00  	at java.base/java.util.stream.WhileOps$3.opEvaluateParallelLazy(WhileOps.java:183)
01:34:00  	at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:447)
01:34:00  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:238)
01:34:00  	at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:474)
01:34:00  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testCountTakeWithCount$20(WhileOpStatefulTest.java:108)
01:34:00  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$69(WhileOpStatefulTest.java:277)
01:34:00  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testWhileMulti(WhileOpStatefulTest.java:295)
01:34:00  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testTakeWhileMulti(WhileOpStatefulTest.java:224)
01:34:00  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithCount(WhileOpStatefulTest.java:92)
01:34:00  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:34:00  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:34:00  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:34:00  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:34:00  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
01:34:00  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
01:34:00  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
01:34:00  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
01:34:00  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:34:00  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
01:34:00  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
01:34:00  	at org.testng.TestRunner.run(TestRunner.java:623)
01:34:00  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
01:34:00  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
01:34:00  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
01:34:00  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
01:34:00  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:34:00  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
01:34:00  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
01:34:00  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
01:34:00  	at org.testng.TestNG.run(TestNG.java:1018)
01:34:00  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
01:34:00  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
01:34:00  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:34:00  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:34:00  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:34:00  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:34:00  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:34:00  	at java.base/java.lang.Thread.run(Thread.java:871)
01:34:00  Caused by: java.lang.RuntimeException
01:34:00  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$62(WhileOpStatefulTest.java:259)
01:34:00  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest$$Lambda$61/0x0000000000000000.accept(Unknown Source)
01:34:00  	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
01:34:00  	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
01:34:00  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
01:34:00  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
01:34:00  	at java.base/java.util.stream.WhileOps$TakeWhileTask.doLeaf(WhileOps.java:1208)
01:34:00  	at java.base/java.util.stream.WhileOps$TakeWhileTask.doLeaf(WhileOps.java:1164)
01:34:00  	at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
01:34:00  	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
01:34:00  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
01:34:00  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
01:34:00  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
01:34:00  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
01:34:00  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/248
jdk_util_0
java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java

```
01:28:53  ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
01:28:53  REASON: Assumed action based on file name: run testng org.openjdk.tests.java.util.stream.WhileOpStatefulTest 
01:28:53  TIME:   36.031 seconds
01:28:53  messages:
01:28:53  command: testng org.openjdk.tests.java.util.stream.WhileOpStatefulTest
01:28:53  reason: Assumed action based on file name: run testng org.openjdk.tests.java.util.stream.WhileOpStatefulTest 
01:28:53  Mode: othervm [test or library overrides a system module]
01:28:53  elapsed time (seconds): 36.031
01:28:53  configuration:
01:28:53  Boot Layer
01:28:53    add reads: java.base ALL-UNNAMED
01:28:53    patch:     java.base /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/TKG/output_16487814132258/jdk_util_0/work/classes/lib/testlibrary/bootlib/java.base
01:28:53  
01:28:53  STDOUT:
01:28:53  [TestNG] Running:
01:28:53    java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java
01:28:53  
01:28:53  config java.util.stream.LoggingTestCase.before(): success
01:28:53  test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountDropWithCount(): success
01:28:53  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@cad983dc): success
01:28:53  config java.util.stream.LoggingTestCase.before(): success
01:28:53  test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountDropWithToArray(): success
01:28:53  config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@fc3f75d1): success
01:28:53  config java.util.stream.LoggingTestCase.before(): success
01:28:53  test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithCount(): failure
01:28:53  java.lang.RuntimeException
01:28:53  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$62(WhileOpStatefulTest.java:259)
01:28:53  	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
01:28:53  	at java.base/java.util.stream.Stream$1.tryAdvance(Stream.java:1231)
01:28:53  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
01:28:53  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
01:28:53  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
01:28:53  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
01:28:53  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
01:28:53  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
01:28:53  	at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:474)
01:28:53  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testCountTakeWithCount$20(WhileOpStatefulTest.java:108)
01:28:53  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$69(WhileOpStatefulTest.java:277)
01:28:53  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testWhileMulti(WhileOpStatefulTest.java:295)
01:28:53  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testTakeWhileMulti(WhileOpStatefulTest.java:224)
01:28:53  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithCount(WhileOpStatefulTest.java:92)
```

**Comment by pshipton** [comment]
6x by 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/748/

**Comment by JasonFengJ9** [comment]
Observed at JDK18 milestone 2 build - `job/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_testList_0/26/`(`macaarch64rt2`)
```
[2022-04-07T02:32:32.804Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-04-07T02:32:32.804Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-04-07T02:41:14.791Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java

[2022-04-07T02:41:14.791Z] STDOUT:
[2022-04-07T02:41:14.791Z] config java.util.stream.LoggingTestCase.before(): success
[2022-04-07T02:41:14.791Z] test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountDropWithCount(): success
[2022-04-07T02:41:14.791Z] config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@85caa376): success
[2022-04-07T02:41:14.791Z] config java.util.stream.LoggingTestCase.before(): success
[2022-04-07T02:41:14.791Z] test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountDropWithToArray(): failure
[2022-04-07T02:41:14.791Z] java.lang.RuntimeException: java.lang.RuntimeException
[2022-04-07T02:41:14.791Z] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[2022-04-07T02:41:14.791Z] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2022-04-07T02:41:14.791Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.WhileOps$3Op.opEvaluateParallel(WhileOps.java:507)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:262)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.LongPipeline.toArray(LongPipeline.java:545)
[2022-04-07T02:41:14.791Z] 	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testCountDropWithToArray$49(WhileOpStatefulTest.java:202)
[2022-04-07T02:41:14.791Z] 	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$69(WhileOpStatefulTest.java:277)
[2022-04-07T02:41:14.791Z] 	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testWhileMulti(WhileOpStatefulTest.java:295)
[2022-04-07T02:41:14.791Z] 	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testDropWhileMulti(WhileOpStatefulTest.java:245)
[2022-04-07T02:41:14.791Z] 	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountDropWithToArray(WhileOpStatefulTest.java:184)
[2022-04-07T02:41:14.791Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-04-07T02:41:14.791Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-04-07T02:41:14.791Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-04-07T02:41:14.791Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-04-07T02:41:14.791Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-04-07T02:41:14.791Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-04-07T02:41:14.791Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-04-07T02:41:14.791Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-04-07T02:41:14.791Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-04-07T02:41:14.791Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-04-07T02:41:14.791Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-04-07T02:41:14.791Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-04-07T02:41:14.791Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-04-07T02:41:14.791Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-04-07T02:41:14.791Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-04-07T02:41:14.791Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-04-07T02:41:14.791Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-04-07T02:41:14.791Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-04-07T02:41:14.791Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-04-07T02:41:14.791Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-04-07T02:41:14.791Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-04-07T02:41:14.791Z] Caused by: java.lang.RuntimeException
[2022-04-07T02:41:14.791Z] 	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$64(WhileOpStatefulTest.java:269)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.WhileOps$DropWhileTask.doLeaf(WhileOps.java:1343)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.WhileOps$DropWhileTask.doLeaf(WhileOps.java:1294)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2022-04-07T02:41:14.791Z] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2022-04-07T02:41:14.791Z] config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@301b87cf): success
[2022-04-07T02:41:14.792Z] config java.util.stream.LoggingTestCase.before(): success
[2022-04-07T02:41:14.792Z] test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithCount(): success
[2022-04-07T02:41:14.792Z] config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@b2258787): success
[2022-04-07T02:41:14.792Z] config java.util.stream.LoggingTestCase.before(): success
[2022-04-07T02:41:14.792Z] test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithToArray(): success
[2022-04-07T02:41:14.792Z] config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@668a3a22): success
[2022-04-07T02:41:14.792Z] config java.util.stream.LoggingTestCase.before(): success
[2022-04-07T02:41:14.792Z] test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testTimedTakeWithCount(): success
[2022-04-07T02:41:14.792Z] config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@8030e746): success
[2022-04-07T02:41:14.792Z] 
[2022-04-07T02:41:14.792Z] ===============================================
[2022-04-07T02:41:14.792Z] java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java
[2022-04-07T02:41:14.792Z] Total tests run: 5, Passes: 4, Failures: 1, Skips: 0
[2022-04-07T02:41:14.792Z] ===============================================

[2022-04-07T02:47:58.428Z] jdk_util_1_FAILED
```
50x grinder - `job/Grinder/22462/`

**Comment by pshipton** [comment]
Failed 2/50, adding to the backlog.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_Nightly/345
jdk_util_1
java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java
```
22:52:54  STDOUT:
22:52:54  config java.util.stream.LoggingTestCase.before(): success
22:52:54  test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountDropWithCount(): failure
22:52:54  java.lang.RuntimeException
22:52:54  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$62(WhileOpStatefulTest.java:259)
22:52:54  	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540)
22:52:54  	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
22:52:54  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
22:52:54  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
22:52:54  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
22:52:54  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
22:52:54  	at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:498)
22:52:54  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testCountDropWithCount$37(WhileOpStatefulTest.java:162)
22:52:54  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$67(WhileOpStatefulTest.java:276)
22:52:54  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testWhileMulti(WhileOpStatefulTest.java:295)
22:52:54  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testDropWhileMulti(WhileOpStatefulTest.java:245)
22:52:54  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountDropWithCount(WhileOpStatefulTest.java:151)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/513/
jdk_util_1
java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java
```
00:13:11  test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithCount(): failure
00:13:11  java.lang.RuntimeException
00:13:11  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$62(WhileOpStatefulTest.java:259)
00:13:11  	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
00:13:11  	at java.base/java.util.stream.Stream$1.tryAdvance(Stream.java:1231)
00:13:11  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
00:13:11  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
00:13:11  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
00:13:11  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
00:13:11  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
00:13:11  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
00:13:11  	at java.base/java.util.stream.LongPipeline.reduce(LongPipeline.java:474)
00:13:11  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testCountTakeWithCount$14(WhileOpStatefulTest.java:96)
00:13:11  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testWhileMulti(WhileOpStatefulTest.java:295)
00:13:11  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testTakeWhileMulti(WhileOpStatefulTest.java:224)
00:13:11  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testCountTakeWithCount(WhileOpStatefulTest.java:92)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/153
jdk_util_1
java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/83/consoleFull
```
04:01:17  ===============================================
04:01:17  Running test jdk_util_0 ...
04:01:17  ===============================================
04:01:17  jdk_util_0 Start Time: Wed Aug  7 04:01:14 2024 Epoch Time (ms): 1723017674558
04:01:17  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
04:01:17  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

04:09:14  TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java

04:09:14  Caused by: java.lang.RuntimeException
04:09:14  	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$64(WhileOpStatefulTest.java:269)
04:09:14  	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
04:09:14  	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
04:09:14  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
04:09:14  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
04:09:14  	at java.base/java.util.stream.WhileOps$TakeWhileTask.doLeaf(WhileOps.java:1208)
04:09:14  	at java.base/java.util.stream.WhileOps$TakeWhileTask.doLeaf(WhileOps.java:1164)
04:09:14  	at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
04:09:14  	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
04:09:14  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
04:09:14  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
04:09:14  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
04:09:14  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
04:09:14  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

04:10:13  jdk_util_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_sanity.openjdk_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_aarch64_mac/648/)
```
[2026-03-27T17:14:36.298Z] Running test jdk_stream_1 ...
[2026-03-27T17:14:36.298Z] ===============================================
[2026-03-27T17:14:36.298Z] jdk_stream_1 Start Time: Fri Mar 27 10:14:14 2026 Epoch Time (ms): 1774631654815
[2026-03-27T17:14:36.298Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2026-03-27T17:14:36.298Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2026-03-27T17:16:46.258Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/WhileOpStatefulTest.java

[2026-03-27T17:16:46.260Z] test org.openjdk.tests.java.util.stream.WhileOpStatefulTest.testTimedTakeWithCount(): failure [1093ms]
[2026-03-27T17:16:46.260Z] java.lang.RuntimeException
[2026-03-27T17:16:46.260Z] 	at org.openjdk.tests.java.util.stream.WhileOpStatefulTest.lambda$testWhileMulti$62(WhileOpStatefulTest.java:259)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_Nightly_testList_3/52
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_3/58
