### ISSUE TITLE
OpenJDK java/lang/String/StringRepeat.java#id1 OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14674]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly/14/ - [win2012-x86-2](https://openj9-jenkins.osuosl.org/computer/win2012-x86-2)
jdk_lang_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops`
java/lang/String/StringRepeat.java#id1

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly/14/openjdk_test_output.tar.gz
```
23:01:25  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Java heap space
23:01:25  REASON: User specified action: run main/othervm -Xmx2g StringRepeat 16777216 
23:01:25  TIME:   8.078 seconds
23:01:25  messages:
23:01:25  command: main -Xmx2g StringRepeat 16777216
23:01:25  reason: User specified action: run main/othervm -Xmx2g StringRepeat 16777216 
23:01:25  Mode: othervm [/othervm specified]
23:01:25  elapsed time (seconds): 8.078
23:01:25  configuration:
23:01:25  STDOUT:
23:01:25  STDERR:
23:01:25  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/03/07 22:01:09 - please wait.
23:01:25  JVMDUMP032I JVM requested Java dump using 'F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16467116059204\jdk_lang_0\work\scratch\0\javacore.20220307.220109.4764.0001.txt' in response to an event
23:01:25  JVMDUMP010I Java dump written to F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16467116059204\jdk_lang_0\work\scratch\0\javacore.20220307.220109.4764.0001.txt
23:01:25  JVMDUMP032I JVM requested Snap dump using 'F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16467116059204\jdk_lang_0\work\scratch\0\Snap.20220307.220109.4764.0002.trc' in response to an event
23:01:25  JVMDUMP010I Snap dump written to F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16467116059204\jdk_lang_0\work\scratch\0\Snap.20220307.220109.4764.0002.trc
23:01:25  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
23:01:25  java.lang.OutOfMemoryError: Java heap space
23:01:25  	at java.base/java.lang.String.repeat(String.java:5188)
23:01:25  	at StringRepeat.test1(StringRepeat.java:80)
23:01:25  	at StringRepeat.main(StringRepeat.java:47)
23:01:25  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
23:01:25  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
23:01:25  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:01:25  	at java.base/java.lang.Thread.run(Thread.java:889)
```

**Comment by pshipton** [comment]
With the default parameters there is no system dump created.

**Comment by pshipton** [comment]
javacore info
```
1STHEAPTYPE    Object Memory
NULL           id                 start              end                size               space/region
1STHEAPSPACE   0x000000301DC95A20         --                 --                 --         Generational
1STHEAPREGION  0x000000301E7AF8C0 0x000000007FFF0000 0x000000009AA90000 0x000000001AAA0000 Generational/Tenured Region
1STHEAPREGION  0x000000301E7AF700 0x00000000FFDB0000 0x00000000FFDF0000 0x0000000000040000 Generational/Nursery Region
1STHEAPREGION  0x000000301E7B0260 0x00000000FFDF0000 0x00000000FFFF0000 0x0000000000200000 Generational/Nursery Region
NULL
1STHEAPTOTAL   Total memory:                   449708032 (0x000000001ACE0000)
1STHEAPINUSE   Total memory in use:              1262320 (0x00000000001342F0)
1STHEAPFREE    Total memory free:              448445712 (0x000000001ABABD10)
```
```
1STGCHTYPE     GC History
3STHSTTYPE     04:01:09:078949796 GMT j9mm.101 -   J9AllocateIndexableObject() returning NULL! 1476395024 bytes requested for object of class 000000000004B100 from memory space 'Generational' id=000000301DC95A20
3STHSTTYPE     04:01:09:078881319 GMT j9mm.134 -   Allocation failure end: newspace=2097152/2359296 oldspace=446356752/447348736 loa=4473856/4473856
3STHSTTYPE     04:01:09:078818661 GMT j9mm.470 -   Allocation failure cycle end: newspace=2097152/2359296 oldspace=446356752/447348736 loa=4473856/4473856
3STHSTTYPE     04:01:09:078670642 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=448453904/449708032
3STHSTTYPE     04:01:09:078467399 GMT j9mm.506 - * Failed to commit memory: address=000000009AA90000, size=1663238144
3STHSTTYPE     04:01:09:078311274 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:01:09:078018786 GMT j9mm.137 -   Compact end: bytesmoved=739920
3STHSTTYPE     04:01:09:068540977 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     04:01:09:068511351 GMT j9mm.57 -   Sweep end
3STHSTTYPE     04:01:09:066936958 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:01:09:066898330 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=8
3STHSTTYPE     04:01:09:065370687 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     04:01:09:065353675 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:01:09:059630607 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:01:09:059469414 GMT j9mm.474 -   GlobalGC start: globalcount=10
3STHSTTYPE     04:01:09:059295542 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=448446272/449708032
3STHSTTYPE     04:01:09:059113228 GMT j9mm.506 - * Failed to commit memory: address=000000009AA90000, size=1663238144
3STHSTTYPE     04:01:09:058958110 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:01:09:058640168 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     04:01:09:053703929 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     04:01:09:053671090 GMT j9mm.57 -   Sweep end
3STHSTTYPE     04:01:09:052240319 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:01:09:052223691 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:01:09:047844882 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:01:09:047653023 GMT j9mm.474 -   GlobalGC start: globalcount=9
3STHSTTYPE     04:01:09:047580884 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.055 meanexclusiveaccessms=0.055 threads=0 lastthreadtid=0x000000000020EA20 beatenbyotherthread=0
3STHSTTYPE     04:01:09:047564192 GMT j9mm.469 -   Allocation failure cycle start: newspace=2097152/2359296 oldspace=278576944/447348736 loa=62628864/62628864 requestedbytes=1476395024
3STHSTTYPE     04:01:09:047445176 GMT j9mm.470 -   Allocation failure cycle end: newspace=2097152/2359296 oldspace=278576944/447348736 loa=62628864/62628864
3STHSTTYPE     04:01:09:047295238 GMT j9mm.468 -   Cycle End: type 2 approximateFreeMemorySize 280674096
3STHSTTYPE     04:01:09:046778850 GMT j9mm.560 -   LocalGC end: rememberedsetoverflow=0 causedrememberedsetoverflow=0 scancacheoverflow=0 failedflipcount=0 failedflipbytes=0 failedtenurecount=0 failedtenurebytes=0 flipcount=0 flipbytes=0 newspace=2097152/2359296 oldspace=278576944/447348736 loa=62628864/62628864 tenureage=0
3STHSTTYPE     04:01:09:046371774 GMT j9mm.140 -   Tilt ratio: 86
3STHSTTYPE     04:01:09:045687014 GMT j9mm.64 -   LocalGC start: globalcount=9 scavengecount=12 weakrefs=0 soft=0 phantom=0 finalizers=0
3STHSTTYPE     04:01:09:045640472 GMT j9mm.467 -   Cycle Start: type 2 approximateFreeMemorySize 280604464
3STHSTTYPE     04:01:09:045529050 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.055 meanexclusiveaccessms=0.055 threads=0 lastthreadtid=0x000000000020EA20 beatenbyotherthread=0
3STHSTTYPE     04:01:09:045513510 GMT j9mm.469 -   Allocation failure cycle start: newspace=2027520/2359296 oldspace=278576944/447348736 loa=62628864/62628864 requestedbytes=1476395024
3STHSTTYPE     04:01:09:045494436 GMT j9mm.133 -   Allocation failure start: newspace=2027520/2359296 oldspace=278576944/447348736 loa=62628864/62628864 requestedbytes=1476395024
3STHSTTYPE     04:01:08:249075544 GMT j9mm.134 -   Allocation failure end: newspace=2031616/2359296 oldspace=278576944/447348736 loa=62628864/62628864
3STHSTTYPE     04:01:08:210423096 GMT j9mm.470 -   Allocation failure cycle end: newspace=2031616/2359296 oldspace=278576944/447348736 loa=62628864/62628864
3STHSTTYPE     04:01:08:210279969 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=280608560/449708032
3STHSTTYPE     04:01:08:209043088 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:01:08:208703466 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     04:01:08:205337975 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     04:01:08:205298276 GMT j9mm.57 -   Sweep end
3STHSTTYPE     04:01:08:203476673 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:01:08:203445592 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:01:08:192903399 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:01:08:192732165 GMT j9mm.474 -   GlobalGC start: globalcount=8
3STHSTTYPE     04:01:08:192660937 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.057 meanexclusiveaccessms=0.057 threads=0 lastthreadtid=0x000000000020EA20 beatenbyotherthread=0
3STHSTTYPE     04:01:08:192646931 GMT j9mm.469 -   Allocation failure cycle start: newspace=2031616/2359296 oldspace=144293680/279511040 loa=36336640/36336640 requestedbytes=167772176
3STHSTTYPE     04:01:08:192531049 GMT j9mm.470 -   Allocation failure cycle end: newspace=2031616/2359296 oldspace=144293680/279511040 loa=36336640/36336640
3STHSTTYPE     04:01:08:192390752 GMT j9mm.468 -   Cycle End: type 2 approximateFreeMemorySize 146325296
3STHSTTYPE     04:01:08:192288459 GMT j9mm.560 -   LocalGC end: rememberedsetoverflow=0 causedrememberedsetoverflow=0 scancacheoverflow=0 failedflipcount=0 failedflipbytes=0 failedtenurecount=0 failedtenurebytes=0 flipcount=0 flipbytes=0 newspace=2031616/2359296 oldspace=144293680/279511040 loa=36336640/36336640 tenureage=0
3STHSTTYPE     04:01:08:191972148 GMT j9mm.140 -   Tilt ratio: 80
3STHSTTYPE     04:01:08:189798708 GMT j9mm.64 -   LocalGC start: globalcount=8 scavengecount=11 weakrefs=0 soft=0 phantom=0 finalizers=0
3STHSTTYPE     04:01:08:189751734 GMT j9mm.467 -   Cycle Start: type 2 approximateFreeMemorySize 146186032
3STHSTTYPE     04:01:08:189613884 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.057 meanexclusiveaccessms=0.057 threads=0 lastthreadtid=0x000000000020EA20 beatenbyotherthread=0
3STHSTTYPE     04:01:08:189598231 GMT j9mm.469 -   Allocation failure cycle start: newspace=1892352/2359296 oldspace=144293680/279511040 loa=36336640/36336640 requestedbytes=167772176
3STHSTTYPE     04:01:08:189585137 GMT j9mm.133 -   Allocation failure start: newspace=1892352/2359296 oldspace=144293680/279511040 loa=36336640/36336640 requestedbytes=167772176
3STHSTTYPE     04:01:07:385263709 GMT j9mm.134 -   Allocation failure end: newspace=1900544/2359296 oldspace=144293680/279511040 loa=36336640/36336640
3STHSTTYPE     04:01:07:315833898 GMT j9mm.470 -   Allocation failure cycle end: newspace=1900544/2359296 oldspace=144293680/279511040 loa=36336640/36336640
3STHSTTYPE     04:01:07:315707942 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=146194224/281870336
3STHSTTYPE     04:01:07:314715777 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     04:01:07:314478927 GMT j9mm.137 -   Compact end: bytesmoved=336
3STHSTTYPE     04:01:07:310546701 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     04:01:07:310511511 GMT j9mm.57 -   Sweep end
3STHSTTYPE     04:01:07:309634684 GMT j9mm.56 -   Sweep start
3STHSTTYPE     04:01:07:309618840 GMT j9mm.55 -   Mark end
3STHSTTYPE     04:01:07:306056166 GMT j9mm.54 -   Mark start
3STHSTTYPE     04:01:07:305890048 GMT j9mm.474 -   GlobalGC start: globalcount=7
3STHSTTYPE     04:01:07:305821315 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.053 meanexclusiveaccessms=0.053 threads=0 lastthreadtid=0x000000000020EA20 beatenbyotherthread=0
3STHSTTYPE     04:01:07:305807022 GMT j9mm.469 -   Allocation failure cycle start: newspace=1900544/2359296 oldspace=43524304/145227776 loa=17427456/17427456 requestedbytes=134217744
3STHSTTYPE     04:01:07:305694784 GMT j9mm.470 -   Allocation failure cycle end: newspace=1900544/2359296 oldspace=43524304/145227776 loa=17427456/17427456
3STHSTTYPE     04:01:07:305550938 GMT j9mm.468 -   Cycle End: type 2 approximateFreeMemorySize 45424848
3STHSTTYPE     04:01:07:305389089 GMT j9mm.560 -   LocalGC end: rememberedsetoverflow=0 causedrememberedsetoverflow=0 scancacheoverflow=0 failedflipcount=0 failedflipbytes=0 failedtenurecount=0 failedtenurebytes=0 flipcount=0 flipbytes=0 newspace=1900544/2359296 oldspace=43524304/145227776 loa=17427456/17427456 tenureage=0
3STHSTTYPE     04:01:07:305209078 GMT j9mm.140 -   Tilt ratio: 77
3STHSTTYPE     04:01:07:304060179 GMT j9mm.64 -   LocalGC start: globalcount=7 scavengecount=10 weakrefs=0 soft=0 phantom=0 finalizers=0
3STHSTTYPE     04:01:07:304016883 GMT j9mm.467 -   Cycle Start: type 2 approximateFreeMemorySize 45395760
3STHSTTYPE     04:01:07:303908691 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.053 meanexclusiveaccessms=0.053 threads=0 lastthreadtid=0x000000000020EA20 beatenbyotherthread=0
3STHSTTYPE     04:01:07:303879864 GMT j9mm.469 -   Allocation failure cycle start: newspace=1823840/2359296 oldspace=43571920/145227776 loa=17427456/17427456 requestedbytes=134217744
3STHSTTYPE     04:01:07:303863412 GMT j9mm.133 -   Allocation failure start: newspace=1823840/2359296 oldspace=43571920/145227776 loa=17427456/17427456 requestedbytes=134217744
3STHSTTYPE     04:01:06:549057685 GMT j9mm.134 -   Allocation failure end: newspace=1827936/2359296 oldspace=43571920/145227776 loa=17427456/17427456
3STHSTTYPE     04:01:06:519249224 GMT j9mm.470 -   Allocation failure cycle end: newspace=1827936/2359296 oldspace=43571920/145227776 loa=17427456/17427456
```

**Comment by pshipton** [comment]
I see `Failed to commit memory`, looks like a machine problem. Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/13803
