### ISSUE TITLE
DBBLoadTest_5m_0 OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14681]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_0/223 - [p8-java1-ibm06](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm06)
DBBLoadTest_5m_0 `-XX:+UseCompressedOops `

```
DBLT 11:03:40.008 - Completed 13.4%. Number of tests started=178 (+52)
DBLT 11:03:41.652 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
DBLT 11:03:41.658 - Test failed
DBLT   Failure num.  = 1
DBLT   Test number   = 15
DBLT   Test details  = 'JUnit[net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest]'
DBLT   Suite number  = 0
DBLT   Thread number = 2
DBLT >>> Captured test output >>>
DBLT testStarted : testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest)
DBLT Total memory is: 56688640
DBLT Initial free memory: 33758648
DBLT Iteration: 0 Total memory is: 56688640Initial free memory: 33758648
DBLT Iteration: 1 Total memory is: 56688640Initial free memory: 34012160
DBLT Iteration: 2 Total memory is: 56688640Initial free memory: 33995096
DBLT Iteration: 3 Total memory is: 56688640Initial free memory: 34057448
DBLT Iteration: 4 Total memory is: 56688640Initial free memory: 34050936
DBLT Iteration: 5 Total memory is: 56688640Initial free memory: 34050936
DBLT Iteration: 6 Total memory is: 56688640Initial free memory: 34056712
DBLT Iteration: 7 Total memory is: 56688640Initial free memory: 34052280
DBLT Iteration: 8 Total memory is: 56688640Initial free memory: 33835136
DBLT Iteration: 9 Total memory is: 56688640Initial free memory: 33835136
DBLT Iteration: 10 Total memory is: 56688640Initial free memory: 33835136
DBLT Iteration: 11 Total memory is: 56688640Initial free memory: 34065256
DBLT Iteration: 12 Total memory is: 56688640Initial free memory: 34052816
DBLT Iteration: 13 Total memory is: 56688640Initial free memory: 34040528
DBLT Iteration: 14 Total memory is: 56688640Initial free memory: 34064248
DBLT Iteration: 15 Total memory is: 56688640Initial free memory: 34069440
DBLT Iteration: 16 Total memory is: 56688640Initial free memory: 34015168
DBLT Iteration: 17 Total memory is: 56688640Initial free memory: 33998784
DBLT Iteration: 18 Total memory is: 56688640Initial free memory: 34019552
DBLT Iteration: 19 Total memory is: 56688640Initial free memory: 34007376
DBLT Iteration: 20 Total memory is: 56688640Initial free memory: 34014368
DBLT Iteration: 21 Total memory is: 56688640Initial free memory: 34081824
DBLT Iteration: 22 Total memory is: 56688640Initial free memory: 34078544
DBLT Iteration: 23 Total memory is: 56688640Initial free memory: 34078544
DBLT Iteration: 24 Total memory is: 56688640Initial free memory: 34078544
DBLT Iteration: 25 Total memory is: 56688640Initial free memory: 34057760
DBLT Iteration: 26 Total memory is: 56688640Initial free memory: 34029512
DBLT Iteration: 27 Total memory is: 56688640Initial free memory: 34083208
DBLT Iteration: 28 Total memory is: 56688640Initial free memory: 34067056
DBLT Iteration: 29 Total memory is: 56688640Initial free memory: 34066360
DBLT Iteration: 30 Total memory is: 56688640Initial free memory: 34066608
DBLT Iteration: 31 Total memory is: 56688640Initial free memory: 33994976
DBLT Iteration: 32 Total memory is: 56688640Initial free memory: 33999712
DBLT Iteration: 33 Total memory is: 56688640Initial free memory: 34004168
DBLT Iteration: 34 Total memory is: 56688640Initial free memory: 33989680
DBLT Iteration: 35 Total memory is: 56688640Initial free memory: 33936808
DBLT Iteration: 36 Total memory is: 56688640Initial free memory: 34043712
DBLT Iteration: 37 Total memory is: 56688640Initial free memory: 34007880
DBLT Iteration: 38 Total memory is: 56688640Initial free memory: 34015032
DBLT Iteration: 39 Total memory is: 56688640Initial free memory: 33998576
DBLT Iteration: 40 Total memory is: 56688640Initial free memory: 33991688
DBLT Iteration: 41 Total memory is: 56688640Initial free memory: 34023776
DBLT Iteration: 42 Total memory is: 56688640Initial free memory: 34013464
DBLT Iteration: 43 Total memory is: 56688640Initial free memory: 34005200
DBLT Iteration: 44 Total memory is: 56688640Initial free memory: 34005200
DBLT Iteration: 45 Total memory is: 56688640Initial free memory: 33952040
DBLT Iteration: 46 Total memory is: 56688640Initial free memory: 34074688
DBLT Iteration: 47 Total memory is: 56688640Initial free memory: 34066176
DBLT Iteration: 48 Total memory is: 56688640Initial free memory: 34066016
DBLT Iteration: 49 Total memory is: 56688640Initial free memory: 34054296
DBLT Iteration: 50 Total memory is: 56688640Initial free memory: 34047712
DBLT Iteration: 51 Total memory is: 56688640Initial free memory: 29390176
DBLT Iteration: 52 Total memory is: 56688640Initial free memory: 33988592
DBLT Iteration: 53 Total memory is: 56688640Initial free memory: 34029672
DBLT Iteration: 54 Total memory is: 56688640Initial free memory: 34017384
DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Direct buffer memory
DBLT java.lang.OutOfMemoryError: Direct buffer memory
DBLT 	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
DBLT 	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
DBLT 	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40)
DBLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DBLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
DBLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DBLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
DBLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
DBLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
DBLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
DBLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
DBLT 	at junit.framework.TestResult.run(TestResult.java:125)
DBLT 	at junit.framework.TestCase.run(TestCase.java:129)
DBLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
DBLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
DBLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
DBLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
DBLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
DBLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DBLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DBLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DBLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DBLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DBLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
DBLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
DBLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
DBLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
DBLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
DBLT 	at java.base/java.lang.Thread.run(Thread.java:871)
DBLT testFinished: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest)
DBLT 
DBLT JUnit Test Results for: net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest
DBLT   Ran    : 1
DBLT   Passed : 0
DBLT   Failed : 1
DBLT   Ignored: 0
DBLT   Result : FAILED
DBLT Test failed:
DBLT java.lang.OutOfMemoryError: Direct buffer memory
DBLT 	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
DBLT 	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
DBLT 	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40)
DBLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DBLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
DBLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DBLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
DBLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
DBLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
DBLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
DBLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
DBLT 	at junit.framework.TestResult.run(TestResult.java:125)
DBLT 	at junit.framework.TestCase.run(TestCase.java:129)
DBLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
DBLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
DBLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
DBLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
DBLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
DBLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DBLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DBLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DBLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DBLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DBLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
DBLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
DBLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
DBLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
DBLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
DBLT 	at java.base/java.lang.Thread.run(Thread.java:871)
DBLT <<<
DBLT 
DBLT 11:03:41.663 - Out of memory exception. Aborting test run
DBLT java.lang.OutOfMemoryError: Direct buffer memory
DBLT 	at java.nio.Bits.reserveMemory(Bits.java:175) ~[?:?]
DBLT 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[?:?]
DBLT 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317) ~[?:?]
DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40) ~[bin/:?]
DBLT 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
DBLT 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
DBLT 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
DBLT 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
DBLT 	at junit.framework.TestCase.runTest(TestCase.java:176) ~[junit.jar:4.12]
DBLT 	at junit.framework.TestCase.runBare(TestCase.java:141) ~[junit.jar:4.12]
DBLT 	at junit.framework.TestResult$1.protect(TestResult.java:122) ~[junit.jar:4.12]
DBLT 	at junit.framework.TestResult.runProtected(TestResult.java:142) ~[junit.jar:4.12]
DBLT 	at junit.framework.TestResult.run(TestResult.java:125) ~[junit.jar:4.12]
DBLT 	at junit.framework.TestCase.run(TestCase.java:129) ~[junit.jar:4.12]
DBLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252) ~[junit.jar:4.12]
DBLT 	at junit.framework.TestSuite.run(TestSuite.java:247) ~[junit.jar:4.12]
DBLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.Suite.runChild(Suite.java:128) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.Suite.runChild(Suite.java:27) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) ~[junit.jar:4.12]
DBLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) ~[junit.jar:4.12]
DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) ~[junit.jar:4.12]
DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115) ~[junit.jar:4.12]
DBLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130) ~[bin/:?]
DBLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182) [bin/:?]
DBLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
DBLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
DBLT 	at java.lang.Thread.run(Thread.java:871) [?:?]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_2/379 - [win2012-x86-6](https://openj9-jenkins.osuosl.org/computer/win2012-x86-6)
DBBLoadTest_5m_2

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_2/379/system_test_output.tar.gz
```
DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Direct buffer memory
DBLT java.lang.OutOfMemoryError: Direct buffer memory
DBLT 	at java.nio.Bits.reserveMemory(Bits.java:704)
DBLT 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:128)
DBLT 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_2/401 - [win2012-x86-6](https://openj9-jenkins.osuosl.org/computer/win2012-x86-6)
DBBLoadTest_5m_2 

```
DBLT testStarted : testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest)
DBLT Total memory is: 21889024
DBLT Initial free memory: 16515848
DBLT Iteration: 0 Total memory is: 21889024Initial free memory: 16515848
DBLT Iteration: 1 Total memory is: 21889024Initial free memory: 16798952
DBLT Iteration: 2 Total memory is: 21889024Initial free memory: 16804776
DBLT Iteration: 3 Total memory is: 21889024Initial free memory: 16793592
DBLT Iteration: 4 Total memory is: 21889024Initial free memory: 16823544
DBLT Iteration: 5 Total memory is: 21889024Initial free memory: 16640632
DBLT Iteration: 6 Total memory is: 21889024Initial free memory: 16831040
DBLT Iteration: 7 Total memory is: 21889024Initial free memory: 16823352
DBLT Iteration: 8 Total memory is: 21889024Initial free memory: 16794680
DBLT Iteration: 9 Total memory is: 21889024Initial free memory: 16849688
DBLT Iteration: 10 Total memory is: 21889024Initial free memory: 16850176
DBLT Iteration: 11 Total memory is: 21889024Initial free memory: 16846960
DBLT Iteration: 12 Total memory is: 21889024Initial free memory: 16805064
DBLT Iteration: 13 Total memory is: 21889024Initial free memory: 16818592
DBLT Iteration: 14 Total memory is: 21889024Initial free memory: 16813208
DBLT Iteration: 15 Total memory is: 21889024Initial free memory: 16821640
DBLT Iteration: 16 Total memory is: 21889024Initial free memory: 16796184
DBLT Iteration: 17 Total memory is: 21889024Initial free memory: 16806824
DBLT Iteration: 18 Total memory is: 21889024Initial free memory: 16821912
DBLT Iteration: 19 Total memory is: 21889024Initial free memory: 16817856
DBLT Iteration: 20 Total memory is: 21889024Initial free memory: 16816984
DBLT Iteration: 21 Total memory is: 21889024Initial free memory: 16858656
DBLT Iteration: 22 Total memory is: 21889024Initial free memory: 16858392
DBLT Iteration: 23 Total memory is: 21889024Initial free memory: 16861832
DBLT Iteration: 24 Total memory is: 21889024Initial free memory: 16863208
DBLT Iteration: 25 Total memory is: 21889024Initial free memory: 16864552
DBLT Iteration: 26 Total memory is: 21889024Initial free memory: 16847208
DBLT Iteration: 27 Total memory is: 21889024Initial free memory: 15514656
DBLT Iteration: 28 Total memory is: 21889024Initial free memory: 16839528
DBLT Iteration: 29 Total memory is: 21889024Initial free memory: 16850624
DBLT Iteration: 30 Total memory is: 21889024Initial free memory: 16855960
DBLT Iteration: 31 Total memory is: 21889024Initial free memory: 16846216
DBLT Iteration: 32 Total memory is: 21889024Initial free memory: 16843392
DBLT Iteration: 33 Total memory is: 21889024Initial free memory: 16376384
DBLT Iteration: 34 Total memory is: 21889024Initial free memory: 16802216
DBLT Iteration: 35 Total memory is: 21889024Initial free memory: 16832400
DBLT Iteration: 36 Total memory is: 21889024Initial free memory: 16826992
DBLT Iteration: 37 Total memory is: 21889024Initial free memory: 16834384
DBLT Iteration: 38 Total memory is: 21889024Initial free memory: 16846240
DBLT Iteration: 39 Total memory is: 21889024Initial free memory: 16838048
DBLT Iteration: 40 Total memory is: 21889024Initial free memory: 16870984
DBLT Iteration: 41 Total memory is: 21889024Initial free memory: 16862288
DBLT Iteration: 42 Total memory is: 21889024Initial free memory: 16886656
DBLT Iteration: 43 Total memory is: 21889024Initial free memory: 16882056
DBLT Iteration: 44 Total memory is: 21889024Initial free memory: 16877864
DBLT Iteration: 45 Total memory is: 21889024Initial free memory: 16885920
DBLT Iteration: 46 Total memory is: 21889024Initial free memory: 16881272
DBLT Iteration: 47 Total memory is: 21889024Initial free memory: 16889440
DBLT Iteration: 48 Total memory is: 21889024Initial free memory: 16860920
DBLT Iteration: 49 Total memory is: 21889024Initial free memory: 16864816
DBLT Iteration: 50 Total memory is: 21889024Initial free memory: 16860232
DBLT Iteration: 51 Total memory is: 21889024Initial free memory: 16868800
DBLT Iteration: 52 Total memory is: 21889024Initial free memory: 16893280
DBLT Iteration: 53 Total memory is: 21889024Initial free memory: 16883720
DBLT Iteration: 54 Total memory is: 21889024Initial free memory: 16868640
DBLT Iteration: 55 Total memory is: 21889024Initial free memory: 16846832
DBLT Iteration: 56 Total memory is: 21889024Initial free memory: 16870072
DBLT Iteration: 57 Total memory is: 21889024Initial free memory: 16863272
DBLT Iteration: 58 Total memory is: 21889024Initial free memory: 16854624
DBLT Iteration: 59 Total memory is: 21889024Initial free memory: 16894232
DBLT Iteration: 60 Total memory is: 21889024Initial free memory: 16891848
DBLT Iteration: 61 Total memory is: 21889024Initial free memory: 16863264
DBLT Iteration: 62 Total memory is: 21889024Initial free memory: 16866968
DBLT Iteration: 63 Total memory is: 21889024Initial free memory: 16854280
DBLT Iteration: 64 Total memory is: 21889024Initial free memory: 16863432
DBLT Iteration: 65 Total memory is: 21889024Initial free memory: 16883528
DBLT Iteration: 66 Total memory is: 21889024Initial free memory: 16857008
DBLT Iteration: 67 Total memory is: 21889024Initial free memory: 16858192
DBLT Iteration: 68 Total memory is: 21889024Initial free memory: 16866176
DBLT Iteration: 69 Total memory is: 21889024Initial free memory: 16864800
DBLT Iteration: 70 Total memory is: 21889024Initial free memory: 16864816
DBLT Iteration: 71 Total memory is: 21889024Initial free memory: 16872464
DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Direct buffer memory
DBLT java.lang.OutOfMemoryError: Direct buffer memory
DBLT 	at java.nio.Bits.reserveMemory(Bits.java:704)
DBLT 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:128)
DBLT 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_2/469 - [win2019-x64-2](https://openj9-jenkins.osuosl.org/computer/win2019-x64-2)
DBBLoadTest_5m_2

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_2/469/system_test_output.tar.gz
```
01:00:33  DBLT testStarted : testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest)
01:00:33  DBLT Total memory is: 19791872
01:00:33  DBLT Initial free memory: 14757104
01:00:33  DBLT Iteration: 0 Total memory is: 19791872Initial free memory: 14757104
01:00:33  DBLT Iteration: 1 Total memory is: 19791872Initial free memory: 14880560
01:00:33  DBLT Iteration: 2 Total memory is: 19791872Initial free memory: 14880208
01:00:33  DBLT Iteration: 3 Total memory is: 19791872Initial free memory: 14884768
01:00:33  DBLT Iteration: 4 Total memory is: 19791872Initial free memory: 14884336
01:00:33  DBLT Iteration: 5 Total memory is: 19791872Initial free memory: 14880240
01:00:33  DBLT Iteration: 6 Total memory is: 19791872Initial free memory: 14914288
01:00:33  DBLT Iteration: 7 Total memory is: 19791872Initial free memory: 14859704
01:00:33  DBLT Iteration: 8 Total memory is: 19791872Initial free memory: 14898200
01:00:33  DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Direct buffer memory
01:00:33  DBLT java.lang.OutOfMemoryError: Direct buffer memory
01:00:33  DBLT 	at java.nio.Bits.reserveMemory(Bits.java:704)
01:00:33  DBLT 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:128)
01:00:33  DBLT 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
01:00:33  DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_2/507/ - [win2019-x64-1](https://openj9-jenkins.osuosl.org/computer/win2019-x64-1)
DBBLoadTest_5m_2 

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly_testList_2/507/system_test_output.tar.gz
```
23:54:56  DBLT Iteration: 67 Total memory is: 28049408Initial free memory: 22190808
23:54:56  DBLT Iteration: 68 Total memory is: 28049408Initial free memory: 22135216
23:54:56  DBLT Iteration: 69 Total memory is: 28049408Initial free memory: 22080992
23:54:56  DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Direct buffer memory
23:54:56  DBLT java.lang.OutOfMemoryError: Direct buffer memory
23:54:56  DBLT 	at java.nio.Bits.reserveMemory(Bits.java:704)
23:54:56  DBLT 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:128)
23:54:56  DBLT 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
23:54:56  DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_0/604/
DBBLoadTest_5m_1

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_0/604/system_test_output.tar.gz
```
DBLT Iteration: 36 Total memory is: 72155136Initial free memory: 37424104
DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Direct buffer memory
DBLT java.lang.OutOfMemoryError: Direct buffer memory
DBLT 	at java.nio.Bits.reserveMemory(Bits.java:704)
DBLT 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:128)
DBLT 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:40)
```
