### ISSUE TITLE
OpenJDK util/DoubleStreamSums/CompensatedSums expected [true] but found [false]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14695]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/15 - [p8-java1-ibm11](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm11)
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/DoubleStreamSums/CompensatedSums.java
```
01:55:29  rerun:
01:55:29  cd /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16468893071227/jdk_util_0/work/scratch && \
01:55:29  DISPLAY=unix:0 \
01:55:29  HOME=/home/jenkins \
01:55:29  LANG=C \
01:55:29  PATH=/bin:/usr/bin:/usr/sbin \
01:55:29  TZ=CUT0 \
01:55:29      /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java \
01:55:29          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
01:55:29          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
01:55:29          -Dtest.compiler.opts= \
01:55:29          -Dtest.java.opts= \
01:55:29          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image \
01:55:29          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image \
01:55:29          -Dtest.timeout.factor=8.0 \
01:55:29          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
01:55:29          -Dtest.root=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
01:55:29          -Dtest.name=java/util/DoubleStreamSums/CompensatedSums.java \
01:55:29          -Dtest.file=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums/CompensatedSums.java \
01:55:29          -Dtest.src=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums \
01:55:29          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums \
01:55:29          -Dtest.classes=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16468893071227/jdk_util_0/work/classes/java/util/DoubleStreamSums/CompensatedSums.d \
01:55:29          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16468893071227/jdk_util_0/work/classes/java/util/DoubleStreamSums/CompensatedSums.d \
01:55:29          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16468893071227/jdk_util_0/work/classes/java/util/DoubleStreamSums/CompensatedSums.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums \
01:55:29          -classpath /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/TKG/output_16468893071227/jdk_util_0/work/classes/java/util/DoubleStreamSums/CompensatedSums.d:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
01:55:29          com.sun.javatest.regtest.agent.TestNGRunner java/util/DoubleStreamSums/CompensatedSums.java false CompensatedSums
01:55:29  STDOUT:
01:55:29  test CompensatedSums.testCompensatedSums(): failure
01:55:29  java.lang.AssertionError: expected [true] but found [false]
01:55:29  	at org.testng.Assert.fail(Assert.java:99)
01:55:29  	at org.testng.Assert.failNotEquals(Assert.java:1037)
01:55:29  	at org.testng.Assert.assertTrue(Assert.java:45)
01:55:29  	at org.testng.Assert.assertTrue(Assert.java:55)
01:55:29  	at CompensatedSums.testCompensatedSums(CompensatedSums.java:88)
```

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_testList_0/21/`(`macaarch64rt7`)
```
openjdk version "18-ea" 2022-03-22
IBM Semeru Runtime Open Edition 18+37 (build 18-ea+37)
Eclipse OpenJ9 VM 18+37 (build master-a6a0c1c55, JRE 18 Mac OS X aarch64-64-Bit 20220326_31 (JIT enabled, AOT enabled)
OpenJ9   - a6a0c1c55
OMR      - 1c51597c3
JCL      - 5d4882cb8b based on jdk-18+37)

[2022-03-26T15:25:04.396Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-03-26T15:25:04.396Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-03-26T15:26:28.700Z] TEST: java/util/DoubleStreamSums/CompensatedSums.java

[2022-03-26T15:26:28.701Z] STDOUT:
[2022-03-26T15:26:28.701Z] test CompensatedSums.testCompensatedSums(): failure
[2022-03-26T15:26:28.701Z] java.lang.AssertionError: expected [true] but found [false]
[2022-03-26T15:26:28.701Z] 	at org.testng.Assert.fail(Assert.java:99)
[2022-03-26T15:26:28.701Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2022-03-26T15:26:28.701Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2022-03-26T15:26:28.701Z] 	at org.testng.Assert.assertTrue(Assert.java:55)
[2022-03-26T15:26:28.701Z] 	at CompensatedSums.testCompensatedSums(CompensatedSums.java:88)
[2022-03-26T15:26:28.701Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-03-26T15:26:28.701Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-03-26T15:26:28.701Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-03-26T15:26:28.701Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-03-26T15:26:28.701Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-03-26T15:26:28.701Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-03-26T15:26:28.701Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-03-26T15:26:28.701Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-03-26T15:26:28.701Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-03-26T15:26:28.701Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-03-26T15:26:28.701Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-03-26T15:26:28.701Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-03-26T15:26:28.701Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-03-26T15:26:28.701Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-03-26T15:26:28.701Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-03-26T15:26:28.701Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-03-26T15:26:28.701Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-03-26T15:26:28.701Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-03-26T15:26:28.701Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-03-26T15:26:28.701Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-03-26T15:26:28.701Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-03-26T15:26:28.701Z] 
[2022-03-26T15:26:28.701Z] ===============================================
[2022-03-26T15:26:28.701Z] java/util/DoubleStreamSums/CompensatedSums.java
[2022-03-26T15:26:28.701Z] Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
[2022-03-26T15:26:28.701Z] ===============================================
[2022-03-26T15:26:28.701Z] 
[2022-03-26T15:26:28.701Z] STDERR:
[2022-03-26T15:26:28.701Z] java.lang.Exception: failures: 1
[2022-03-26T15:26:28.701Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2022-03-26T15:26:28.701Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-03-26T15:26:28.701Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-03-26T15:26:28.701Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-03-26T15:26:28.701Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-03-26T15:26:28.701Z] 
[2022-03-26T15:26:28.701Z] JavaTest Message: Test threw exception: java.lang.Exception
[2022-03-26T15:26:28.701Z] JavaTest Message: shutting down test
[2022-03-26T15:26:28.701Z] 
[2022-03-26T15:26:28.701Z] 
[2022-03-26T15:26:28.701Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2022-03-26T15:26:28.701Z] --------------------------------------------------
[2022-03-26T15:32:54.933Z] Test results: passed: 897; failed: 1
[2022-03-26T15:32:54.933Z] Report written to /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_testList_0/jvmtest/openjdk/report/html/report.html
[2022-03-26T15:32:54.933Z] Results written to /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_testList_0/aqa-tests/TKG/output_16483080648523/jdk_util_1/work
[2022-03-26T15:32:54.933Z] Error: Some tests failed or other problems occurred.
[2022-03-26T15:32:54.933Z] 
[2022-03-26T15:32:54.933Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
@JasonFengJ9 is it repeatable in a grinder, either the test alone or the entire jdk_util_0 or jdk_util_1?

**Comment by JasonFengJ9** [comment]
50x grinder - `job/Grinder/22085/`

**Comment by pshipton** [comment]
@JasonFengJ9 pls try jdk_util_0 or jdk_util_1

**Comment by JasonFengJ9** [comment]
This failure is not reproduced at 50x grinder w/ `jdk_util` - `job/Grinder/22145`.
There is a unrelated failure `Invalid JIT return address` after all tests passed, which seems https://github.com/eclipse-openj9/openj9/issues/14717

**Comment by pshipton** [comment]
Ok, we'll continue to monitor how often this occurs in the builds.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Nightly/55
jdk_util_1 
java/util/DoubleStreamSums/CompensatedSums.java
```
00:41:09  test CompensatedSums.testCompensatedSums(): failure
00:41:09  java.lang.AssertionError: expected [true] but found [false]
00:41:09  	at org.testng.Assert.fail(Assert.java:99)
00:41:09  	at org.testng.Assert.failNotEquals(Assert.java:1037)
00:41:09  	at org.testng.Assert.assertTrue(Assert.java:45)
00:41:09  	at org.testng.Assert.assertTrue(Assert.java:55)
00:41:09  	at CompensatedSums.testCompensatedSums(CompensatedSums.java:88)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_Nightly/232/
jdk_util_1 
java/util/DoubleStreamSums/CompensatedSums.java
```
23:03:51  test CompensatedSums.testCompensatedSums(): failure
23:03:51  java.lang.AssertionError: expected [true] but found [false]
23:03:51  	at org.testng.Assert.fail(Assert.java:99)
23:03:51  	at org.testng.Assert.failNotEquals(Assert.java:1037)
23:03:51  	at org.testng.Assert.assertTrue(Assert.java:45)
23:03:51  	at org.testng.Assert.assertTrue(Assert.java:55)
23:03:51  	at CompensatedSums.testCompensatedSums(CompensatedSums.java:88)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/232
jdk_util_0 
java/util/DoubleStreamSums/CompensatedSums.java
```
20:17:17  rerun:
20:17:17  cd /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16575828916074/jdk_util_0/work/scratch/0 && \
20:17:17  DISPLAY=:0 \
20:17:17  HOME=/home/jenkins \
20:17:17  LANG=en_US.UTF-8 \
20:17:17  PATH=/bin:/usr/bin:/usr/sbin \
20:17:17      /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
20:17:17          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
20:17:17          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
20:17:17          -Dtest.compiler.opts= \
20:17:17          -Dtest.java.opts= \
20:17:17          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
20:17:17          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
20:17:17          -Dtest.timeout.factor=8.0 \
20:17:17          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
20:17:17          -Dtest.root=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
20:17:17          -Dtest.name=java/util/DoubleStreamSums/CompensatedSums.java \
20:17:17          -Dtest.file=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums/CompensatedSums.java \
20:17:17          -Dtest.src=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums \
20:17:17          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums \
20:17:17          -Dtest.classes=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16575828916074/jdk_util_0/work/classes/2/java/util/DoubleStreamSums/CompensatedSums.d \
20:17:17          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16575828916074/jdk_util_0/work/classes/2/java/util/DoubleStreamSums/CompensatedSums.d \
20:17:17          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16575828916074/jdk_util_0/work/classes/2/java/util/DoubleStreamSums/CompensatedSums.d:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums \
20:17:17          -classpath /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16575828916074/jdk_util_0/work/classes/2/java/util/DoubleStreamSums/CompensatedSums.d:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/DoubleStreamSums:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
20:17:17          com.sun.javatest.regtest.agent.TestNGRunner java/util/DoubleStreamSums/CompensatedSums.java false CompensatedSums
20:17:17  STDOUT:
20:17:17  test CompensatedSums.testCompensatedSums(): failure
20:17:17  java.lang.AssertionError: expected [true] but found [false]
20:17:17  	at org.testng.Assert.fail(Assert.java:99)
20:17:17  	at org.testng.Assert.failNotEquals(Assert.java:1037)
20:17:17  	at org.testng.Assert.assertTrue(Assert.java:45)
20:17:17  	at org.testng.Assert.assertTrue(Assert.java:55)
20:17:17  	at CompensatedSums.testCompensatedSums(CompensatedSums.java:88)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/345
jdk_util_0
java/util/DoubleStreamSums/CompensatedSums.java
```
22:25:33  Seed from RandomFactory = -3310927400359998017L
22:25:33  test CompensatedSums.testCompensatedSums(): failure
22:25:33  java.lang.AssertionError: expected [true] but found [false]
22:25:33  	at org.testng.Assert.fail(Assert.java:99)
22:25:33  	at org.testng.Assert.failNotEquals(Assert.java:1037)
22:25:33  	at org.testng.Assert.assertTrue(Assert.java:45)
22:25:33  	at org.testng.Assert.assertTrue(Assert.java:55)
22:25:33  	at CompensatedSums.testCompensatedSums(CompensatedSums.java:94)
```
