### ISSUE TITLE
80 VM_Promotion.external_jtregTests_general.NoOptions Exception: Failed 10 tests at WithParameters.main(WithParameters.java:229)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14703]
Failure link
------------

From an internal build `job_output.php?id=29167528`:
```
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 8.0.8.0 - pxp6480sr8-20220308_01(SR8))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64-64-Bit Compressed References 20220311_24446 (JIT enabled, AOT enabled)
OpenJ9   - 2bd1771
OMR      - 9e8071e
IBM      - 1b0232b)
JCL - 20220222_02 based on Oracle jdk8u331-b05
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
 [jtreg] TEST: jep118/WithParameters.java

[jtreg] STDERR:
    [jtreg] Inspecting method getClass
    [jtreg] Inspecting method wait
    [jtreg] Inspecting method wait
    [jtreg] Inspecting method wait
    [jtreg] Inspecting method qux
    [jtreg] Wrong parameter name for int arg0
    [jtreg] Wrong parameter name for WithParameters$Foo arg1
    [jtreg] Wrong parameter name for java.util.List<?> arg2
    [jtreg] Wrong parameter name for java.util.List<WithParameters$Foo> arg3
    [jtreg] Wrong parameter name for java.util.List<? extends WithParameters$Foo> arg4
    [jtreg] Wrong parameter name for java.lang.String... arg5
    [jtreg] quux is not final
    [jtreg] toString for quuux is wrong
    [jtreg] toString for l is wrong
    [jtreg] toString for l is wrong
    [jtreg] Inspecting method hashCode
    [jtreg] Inspecting method equals
    [jtreg] Inspecting method notifyAll
    [jtreg] Inspecting method toString
    [jtreg] Inspecting method notify
    [jtreg] java.lang.Exception: Failed 10 tests
    [jtreg] 	at WithParameters.main(WithParameters.java:229)
    [jtreg] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [jtreg] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
    [jtreg] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
    [jtreg] 	at java.lang.reflect.Method.invoke(Method.java:508)
    [jtreg] 	at com.sun.javatest.regtest.MainWrapper$MainThread.run(MainWrapper.java:94)
    [jtreg] 	at java.lang.Thread.run(Thread.java:830)
    [jtreg] 
    [jtreg] JavaTest Message: Test threw exception: java.lang.Exception: Failed 10 tests
```
3/10 failed at a grinder - `build_info.php?build_id=24584`

**Comment by pshipton** [comment]
First failure I see in history is /job_output.php?id=28530797 from March 3.

**Comment by pshipton** [comment]
It appears all the failures are on prhel* machines.

**Comment by pshipton** [comment]
Tested non-cr with builds 16084 (Nov 4), 16203 (Nov 6), which had previous passes, they fail now on all 35, 36, 37. Seems the failure isn't caused by a JVM code change. Failures seem related to the machines themselves. Checked the tests haven't changed since Nov 2020.

**Comment by pshipton** [comment]
This seems an internal problem, I've created runtimes/backlog/issues/753
