### ISSUE TITLE
TestJlmRemoteThreadAuth_1 ArrayIndexOutOfBoundsException ThreadMXBeanImpl.getThreadInfoCommon

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14718]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly_testList_0/231 - [cent7-ppcle-5](https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-5)
TestJlmRemoteThreadAuth_1 `-XX:-UseCompressedOops`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly_testList_0/231/system_test_output.tar.gz

```
STF 07:06:01.686 - +------ Step 9 - Wait for processes to complete
STF 07:06:01.686 - | Wait for processes to meet expectations
STF 07:06:01.686 - |   Processes: [LT2, CL2]
STF 07:06:01.686 - |
STF 07:06:01.686 - Monitoring processes: CL2 LT2
CL2 j> 2022/03/15 07:06:02.381 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
CL2 j> 2022/03/15 07:06:02.636 Attempting to connect
CL2 j> 2022/03/15 07:06:03.210 Monitored VM not ready at Mar 15, 2022, 7:06:03 AM (attempt 1, elapsed 523ms).
CL2 j> 2022/03/15 07:06:03.211 Waiting 5 secs and trying again...
CL2 j> 2022/03/15 07:06:08.212 Attempting to connect
CL2 j> 2022/03/15 07:06:15.478 Connection established!
CL2 j> 2022/03/15 07:06:27.534 Writing report data ...
CL2 j> 2022/03/15 07:06:49.120  done.
CL2 j> 2022/03/15 07:06:59.330 Writing report data ...
CL2 j> 2022/03/15 07:07:11.430  done.
CL2 j> 2022/03/15 07:07:21.592 Writing report data ...
CL2 j> 2022/03/15 07:07:26.571  done.
CL2 j> 2022/03/15 07:07:36.695 Writing report data ...
CL2 j> 2022/03/15 07:07:40.871  done.
CL2 j> 2022/03/15 07:07:50.993 Writing report data ...
CL2 j> 2022/03/15 07:07:55.299  done.
CL2 j> 2022/03/15 07:08:05.451 Writing report data ...
CL2 j> 2022/03/15 07:08:09.643  done.
CL2 j> 2022/03/15 07:08:19.762 Writing report data ...
CL2 j> 2022/03/15 07:08:23.843  done.
CL2 j> 2022/03/15 07:08:33.915 Writing report data ...
CL2 j> 2022/03/15 07:08:37.374  done.
CL2 j> 2022/03/15 07:08:47.503 Writing report data ...
STF 07:08:49.474 - Heartbeat: Process CL2 is still running
CL2 j> 2022/03/15 07:08:50.752  done.
CL2 j> 2022/03/15 07:09:00.882 Writing report data ...
CL2 j> 2022/03/15 07:09:04.922  done.
CL2 j> 2022/03/15 07:09:14.992 Writing report data ...
CL2 j> 2022/03/15 07:09:18.598  done.
CL2 j> 2022/03/15 07:09:28.668 Writing report data ...
CL2 j> 2022/03/15 07:09:32.511  done.
CL2 j> 2022/03/15 07:09:42.692 Writing report data ...
CL2 j> 2022/03/15 07:09:46.313  done.
CL2 j> 2022/03/15 07:09:56.432 Writing report data ...
CL2 j> 2022/03/15 07:10:00.134  done.
CL2 j> 2022/03/15 07:10:10.225 Writing report data ...
CL2 j> 2022/03/15 07:10:13.464  done.
CL2 j> 2022/03/15 07:10:23.655 Writing report data ...
CL2 j> 2022/03/15 07:10:27.174  done.
CL2 j> 2022/03/15 07:10:37.274 Writing report data ...
CL2 j> 2022/03/15 07:10:40.973  done.
CL2 j> 2022/03/15 07:10:51.102 Writing report data ...
CL2 j> 2022/03/15 07:10:54.758  done.
CL2 j> 2022/03/15 07:11:04.862 Writing report data ...
CL2 j> 2022/03/15 07:11:08.458  done.
CL2 j> 2022/03/15 07:11:18.672 Writing report data ...
CL2 j> 2022/03/15 07:11:22.204  done.
CL2 j> 2022/03/15 07:11:32.320 Writing report data ...
CL2 j> 2022/03/15 07:11:35.523  done.
CL2 j> 2022/03/15 07:11:45.644 Writing report data ...
CL2 j> 2022/03/15 07:11:49.571  done.
CL2 j> 2022/03/15 07:11:59.672 Writing report data ...
CL2 j> 2022/03/15 07:12:02.769  done.
CL2 j> 2022/03/15 07:12:12.912 Writing report data ...
CL2 j> 2022/03/15 07:12:16.214  done.
CL2 j> 2022/03/15 07:12:26.352 Writing report data ...
CL2 stderr Exception in thread "main" javax.management.RuntimeMBeanException: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 35
CL2 stderr 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:829)
CL2 stderr 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:842)
CL2 stderr 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:811)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
CL2 stderr 	at java.management/com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
CL2 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1406)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
CL2 stderr 	at jdk.internal.reflect.GeneratedMethodAccessor188.invoke(Unknown Source)
CL2 stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CL2 stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CL2 stderr 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
CL2 stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
CL2 stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
CL2 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
CL2 stderr 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
CL2 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
CL2 stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
CL2 stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
CL2 stderr 	at java.base/java.lang.Thread.run(Thread.java:871)
CL2 stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
CL2 stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
CL2 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
CL2 stderr 	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1021)
CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ThreadData.writeData(ThreadData.java:592)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:199)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
CL2 stderr Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 35
CL2 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfoCommon(ThreadMXBeanImpl.java:348)
CL2 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfo(ThreadMXBeanImpl.java:308)
CL2 stderr 	at jdk.internal.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
CL2 stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CL2 stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CL2 stderr 	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
CL2 stderr 	at jdk.internal.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
CL2 stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CL2 stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CL2 stderr 	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
CL2 stderr 	at java.management/javax.management.StandardMBean.invoke(StandardMBean.java:405)
CL2 stderr 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
CL2 stderr 	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
CL2 stderr 	at java.management/com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
CL2 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1406)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
CL2 stderr 	at jdk.internal.reflect.GeneratedMethodAccessor188.invoke(Unknown Source)
CL2 stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CL2 stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CL2 stderr 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
CL2 stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
CL2 stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
CL2 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
CL2 stderr 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
CL2 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
CL2 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
CL2 stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
CL2 stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
CL2 stderr 	at java.base/java.lang.Thread.run(Thread.java:871)
STF 07:12:28.535 - **FAILED** Process CL2 ended with exit code (1) and not the expected exit code/s (0)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly_testList_2/232/
TestJlmRemoteThreadNoAuth_0
```
CL2 stderr Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 34
CL2 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfoCommon(ThreadMXBeanImpl.java:348)
CL2 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfo(ThreadMXBeanImpl.java:308)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly_testList_1/232/
TestJlmRemoteThreadAuth_0
```
CL1 stderr Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 38
CL1 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfoCommon(ThreadMXBeanImpl.java:348)
CL1 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfo(ThreadMXBeanImpl.java:308)
```

**Comment by pshipton** [comment]
@tajila this seems like a regression, somebody should take a look asap.

**Comment by pshipton** [comment]
Changes in the first build where this was seen.
https://github.com/eclipse-openj9/openj9/compare/0575fb08d33...ec37a756277

It's probably caused by https://github.com/eclipse-openj9/openj9/pull/14701

**Comment by pshipton** [comment]
@ChengJin01

**Comment by ChengJin01** [comment]
will revert the changes at https://github.com/eclipse-openj9/openj9/pull/14701 to see how it goes in this test.

**Comment by ChengJin01** [comment]
I've tried with both the reverted build and the master build without any changes (including JDK8, 11, 17, 18 and `nextJDK`) and `TestJlmRemoteThreadAuth` (including `TestJlmRemoteThreadAuth_0` and `TestJlmRemoteThreadAuth_1`) passed on JDK8, 11, 17, 18 and `nextJDK` without any issue, which means the exception occurs intermittently and there is no strong evidence indicating that it was directly related to https://github.com/eclipse-openj9/openj9/pull/14701 given theoretically it should always end up with the failure if anything wrong in the FFI native call.

In the meanwhile, two 10x Grinders (from this failing job above) were launched at https://openj9-jenkins.osuosl.org/job/Grinder/715/ on the same failing machine and https://openj9-jenkins.osuosl.org/job/Grinder/714/ on other ppc64le machines to see whether the exception can be reproduced.

**Comment by pshipton** [comment]
Actually this is more likely caused by https://github.com/eclipse-openj9/openj9/pull/14688, there is another known problem https://github.com/eclipse-openj9/openj9/issues/14738 with this change.

**Comment by pshipton** [comment]
@fengxue-IS @babsingh fyi

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly_testList_2/231
TestJlmRemoteThreadNoAuth_0 `-XX:+UseCompressedOops`
```
STF 10:47:26.142 - +------ Step 3 - Wait for processes to complete
STF 10:47:26.142 - | Wait for processes to meet expectations
STF 10:47:26.142 - |   Processes: [LT1, CL1]
STF 10:47:26.142 - |
STF 10:47:26.142 - Monitoring processes: CL1 LT1
CL1 j> 2022/03/17 10:47:26.530 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
CL1 j> 2022/03/17 10:47:26.696 Attempting to connect
CL1 j> 2022/03/17 10:47:27.013 Monitored VM not ready at Mar 17, 2022, 10:47:27 AM (attempt 1, elapsed 293ms).
CL1 j> 2022/03/17 10:47:27.013 Waiting 5 secs and trying again...
CL1 j> 2022/03/17 10:47:32.013 Attempting to connect
CL1 j> 2022/03/17 10:47:32.654 Connection established!
CL1 j> 2022/03/17 10:47:33.191 Starting to write data
CL1 stderr Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 38
CL1 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfoCommon(ThreadMXBeanImpl.java:348)
CL1 stderr 	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfo(ThreadMXBeanImpl.java:308)
CL1 stderr 	at jdk.internal.reflect.GeneratedMethodAccessor222.invoke(Unknown Source)
CL1 stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CL1 stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CL1 stderr 	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
CL1 stderr 	at jdk.internal.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
CL1 stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CL1 stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CL1 stderr 	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
CL1 stderr 	at java.management/javax.management.StandardMBean.invoke(StandardMBean.java:405)
CL1 stderr 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
CL1 stderr 	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
CL1 stderr 	at jdk.internal.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
CL1 stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CL1 stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CL1 stderr 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
CL1 stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
CL1 stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
CL1 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
CL1 stderr 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
CL1 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
CL1 stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
CL1 stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
CL1 stderr 	at java.base/java.lang.Thread.run(Thread.java:871)
```

**Comment by pshipton** [comment]
@ChengJin01 we got one on Mac so that definitely rules out the ffi change.

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_x86-64_linux_Nightly_testList_2/226
TestJlmRemoteThreadNoAuth_0

**Comment by tajila** [comment]
@fengxue-IS can you see if reverting your change fixes this?

**Comment by fengxue-IS** [comment]
> @fengxue-IS can you see if reverting your change fixes this?

launched personal build to verify if reverting fixes this change

**Comment by fengxue-IS** [comment]
Test `TestJlmRemoteThreadNoAuth_0` 20/20 passed on linux after reverting #14688, the failure rate I got while trying to reproduce this issue is about 1/10 so likely failure due to the change

**Comment by fengxue-IS** [comment]
after some hacking into the place that can generate an `ArrayIndexOutOfBoundsException` with https://github.com/eclipse-openj9/openj9/commit/39ffd098fe1987e4654a3adba568ad9268413360

The source of the AIOB seem to come from `getObjectArrayElement` which is used by `createLockedMonitors` in the following callstack:
```
Java_com_ibm_java_lang_management_internal_ThreadMXBeanImpl_getMultiThreadInfoImpl
 -> createThreadInfoArray
     -> createThreadInfo
         -> createLockedMonitors
             -> GetObjectArrayElement
```
The stack index used is:
```c++
depth = (jint)(tinfo->lockedMonitors.arr_safe[i].depth - 1);
frame = (*env)->GetObjectArrayElement(env, tinfo->stackTrace, depth);
```
which comes from:
```
Java_com_ibm_java_lang_management_internal_ThreadMXBeanImpl_getMultiThreadInfoImpl
    getArrayOfThreadInfo
        getThreadInfo
            getMonitors
                getOwnedObjectMonitors
                    walkStackFrames
                        getOwnedObjectMonitorsIterator
```

This issue is rather difficult to get a simple fix as the monitor depth is based on stackwalk frames from `Throwable.walkback` and the actual stack trace array has been filtered after stackwalk. To fix this mismatch, we need to modify stackwalk to include the unfolding of inlined frames (`iterateStackTrace` functionality) or redesign `getThreadInfo` to work with current code.

I've launched a grinder with `-XX:+ShowHiddenFrames` to verify if not filtering the stacktrace fixes the problem

**Comment by fengxue-IS** [comment]
@tajila @gacholio do you see any other options to fix this issue?

**Comment by fengxue-IS** [comment]
Adding `-XX:+ShowHiddenFrames` passed 10/10 on xlinux

**Comment by gacholio** [comment]
Is the problem perhaps that there's a monitor locked in a hidden frame?

**Comment by fengxue-IS** [comment]
Is when creating the Java `MonitorInfo` object in `createLockedMonitors` API, it tries to get the matching `StackTraceElement` from the stacktrace array for each monitor via depth field (index into `Throwable.walkback`, which included the hidden frames in the count)

**Comment by gacholio** [comment]
Would using the `SKIP_HIDDEN` stackwalk flag in the `getOwnedObjectMonitors` fix this? The stackwalk flag should be equivalent to the `iterateStackTrace` logic.

**Comment by gacholio** [comment]
No, I suppose not since it's already skipping inlines. We may need to add the hidden frame logic to `jitGetOwnedObjectMonitors` and `walkFrameMonitorEnterRecords`.

**Comment by gacholio** [comment]
For the record, is there any Oracle documentation about the interaction of hidden frames, the command-line option and this API? Have you tried this test with Oracle with the option in both states?

**Comment by fengxue-IS** [comment]
Documentation on ThreadInfo Object returned by API doesn't specify any requirements on hidden frames, only mentioned that JVM implementation is allowed to omit some/all frames.

Have not tried running this test against RI, will try that in a grinder

**Comment by fengxue-IS** [comment]
Discussed with Gac offline, working on adding skip hidden frame logic to `jitGetOwnedObjectMonitors` and `walkFrameMonitorEnterRecords`

**Comment by gacholio** [comment]
Definitely time to move the hidden frame logic into a macro. We already have too many copies in the source.

**Comment by pshipton** [comment]
I'll reopen this until the fix is in the release stream(s).

**Comment by pshipton** [comment]
It's added to 0.31 https://github.com/eclipse-openj9/openj9/pull/14849 and 0.32 https://github.com/eclipse-openj9/openj9/pull/14850
