### ISSUE TITLE
threadMXBeanTimedParkTest_3 testTimedParkTest expected [PASS] but found [FAIL]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14728]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64_aix_Nightly_testList_0/176
threadMXBeanTimedParkTest_3 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xthr:minimizeUserCPU`
```
00:35:47  [TimedParkTest] [ERROR] ERROR: Blocked time is lower than expected
00:35:47  [TimedParkTest] [ERROR]   actual: 4306 expected: 5000 tolerance: 500
00:35:47  FAILED: testTimedParkTest
00:35:47  java.lang.AssertionError: The following asserts failed:
00:35:47  	expected [PASS] but found [FAIL]
00:35:47  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
00:35:47  	at org.openj9.test.java.lang.management.ThreadMXBean.TimedParkTest.testTimedParkTest(TimedParkTest.java:200)
```

**Comment by pshipton** [comment]
This is a dup of https://github.com/eclipse-openj9/openj9/issues/14470
