### ISSUE TITLE
JDK17 HeapHogLoadTest_5m_1_FAILED testFailure: test(net.adoptopenjdk.test.math.MathAPITest): Method "test" not found

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14732]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.system_aarch64_linux_testList_0/44/`(`ub18-aarch64-2`):
```
openjdk version "17.0.3" 2022-04-19
IBM Semeru Runtime Open Edition 17.0.3.0-m1a (build 17.0.3+4)
Eclipse OpenJ9 VM 17.0.3.0-m1a (build openj9-0.32.0-m1a, JRE 17 Linux aarch64-64-Bit Compressed References 20220316_127 (JIT enabled, AOT enabled)
OpenJ9   - 6dbe50f27
OMR      - c7a356355
JCL      - db1a51b8bdc based on jdk-17.0.3+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=HeapHogLoadTest_5m_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_extended.system_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-testimage_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-jre_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-debugimage_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-jdk_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;USE_JRE=false&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=v0.32.0-release&amp;OPENJ9_BRANCH=v0.32.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.32.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=49&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;TKG_SHA=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-03-16T05:04:16.634Z] variation: Mode610
[2022-03-16T05:04:16.634Z] JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 

[2022-03-16T05:08:14.693Z] HHLT 01:08:12.882 - Test failed. Details recorded in execution log.
[2022-03-16T05:08:14.693Z] HHLT 01:08:12.882 - Test failed
[2022-03-16T05:08:14.693Z] HHLT   Failure num.  = 1
[2022-03-16T05:08:14.693Z] HHLT   Test number   = 33
[2022-03-16T05:08:14.693Z] HHLT   Test details  = 'JUnit[net.adoptopenjdk.test.util.lilac.TestArrays]'
[2022-03-16T05:08:14.693Z] HHLT   Suite number  = 0
[2022-03-16T05:08:14.693Z] HHLT   Thread number = 5
[2022-03-16T05:08:14.693Z] HHLT >>> Captured test output >>>
[2022-03-16T05:08:14.693Z] HHLT testStarted : test(net.adoptopenjdk.test.math.MathAPITest)
[2022-03-16T05:08:14.693Z] HHLT testFailure: test(net.adoptopenjdk.test.math.MathAPITest): Method "test" not found
[2022-03-16T05:08:14.693Z] HHLT junit.framework.AssertionFailedError: Method "test" not found
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.Assert.fail(Assert.java:57)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestCase.fail(TestCase.java:227)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestCase.runTest(TestCase.java:169)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestResult.run(TestResult.java:125)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestCase.run(TestCase.java:129)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2022-03-16T05:08:14.693Z] HHLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-03-16T05:08:14.693Z] HHLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-03-16T05:08:14.693Z] HHLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2022-03-16T05:08:14.693Z] HHLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-03-16T05:08:14.693Z] HHLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2022-03-16T05:08:14.693Z] HHLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2022-03-16T05:08:14.693Z] HHLT 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-03-16T05:08:14.693Z] HHLT testFinished: test(net.adoptopenjdk.test.math.MathAPITest)
[2022-03-16T05:08:14.693Z] HHLT 
[2022-03-16T05:08:14.693Z] HHLT JUnit Test Results for: net.adoptopenjdk.test.util.lilac.TestArrays
[2022-03-16T05:08:14.693Z] HHLT   Ran    : 1
[2022-03-16T05:08:14.693Z] HHLT   Passed : 0
[2022-03-16T05:08:14.693Z] HHLT   Failed : 1
[2022-03-16T05:08:14.693Z] HHLT   Ignored: 0
[2022-03-16T05:08:14.693Z] HHLT   Result : FAILED
[2022-03-16T05:08:14.693Z] HHLT <<<

[2022-03-16T05:08:14.694Z] HeapHogLoadTest_5m_1_FAILED
```

50x grinder - `job/Grinder/21751/` - all passed

**Comment by knn-k** [comment]
No failures in the grinder job above.

**Comment by pshipton** [comment]
Maybe related to https://github.com/eclipse-openj9/openj9/issues/14713

**Comment by knn-k** [comment]
Not reproduced in a 20x Grinder job, using the build from https://github.com/eclipse-openj9/openj9/issues/14713#issuecomment-1088629414 : job/Grinder/765

**Comment by knn-k** [comment]
I ran HeapHogLoadTest_5m_1 with JDK 17 40 times on AArch64 Linux, and got no failures.
https://openj9-jenkins.osuosl.org/job/Grinder/1308/

See also #15750 (AssertionFailedError in HeapHogLoadTest_5m_1).
