### ISSUE TITLE
JDK17 0.32.0 jdk_nio_0_FAILED NullPointerException: Cannot load from byte/boolean array because "ba" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14743]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_x86-64_mac/50/consoleFull`(`[mac11x64rt06.rtp.raleigh.ibm.com](mac11x64rt06`):
```
19:22:21  openjdk version "17.0.3" 2022-04-19
19:22:21  IBM Semeru Runtime Open Edition 17.0.3.0-m1a (build 17.0.3+4)
19:22:21  Eclipse OpenJ9 VM 17.0.3.0-m1a (build openj9-0.32.0-m1a, JRE 17 Mac OS X amd64-64-Bit Compressed References 20220315_127 (JIT enabled, AOT enabled)
19:22:21  OpenJ9   - 6dbe50f27
19:22:21  OMR      - c7a356355
19:22:21  JCL      - db1a51b8bdc based on jdk-17.0.3+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-x64-openj9%2F127%2Fibm-semeru-open-jdk_x64_mac_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-x64-openj9%2F127%2Fibm-semeru-open-testimage_x64_mac_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-x64-openj9%2F127%2Fibm-semeru-open-jre_x64_mac_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-x64-openj9%2F127%2Fibm-semeru-open-debugimage_x64_mac_17.0.3_4_openj9-0.32.0-m1a.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&OPENJ9_BRANCH=v0.32.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&RELEASE_TAG=v0.32.0-release&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.32.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&TKG_SHA=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&OPENJDK_SHA=&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
19:36:23  variation: Mode150
19:36:23  JVM_OPTIONS:  -XX:+UseCompressedOops 

19:42:11  TEST: sun/nio/cs/FindASCIICodingBugs.java

19:42:11  STDERR:
19:42:11  java.nio.charset.CoderMalfunctionError: java.lang.NullPointerException: Cannot load from byte/boolean array because "ba" is null
19:42:11  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:587)
19:42:11  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:806)
19:42:11  	at FindASCIICodingBugs.main(FindASCIICodingBugs.java:79)
19:42:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:42:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19:42:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:42:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:42:11  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
19:42:11  	at java.base/java.lang.Thread.run(Thread.java:889)
19:42:11  Caused by: java.lang.NullPointerException: Cannot load from byte/boolean array because "ba" is null
19:42:11  	at java.base/java.lang.StringCoding.hasNegatives(StringCoding.java:40)
19:42:11  	at java.base/java.lang.String.decodeASCII(String.java:1202)
19:42:11  	at java.base/java.lang.Access.decodeASCII(Access.java:375)
19:42:11  	at java.base/sun.nio.cs.DoubleByte$Decoder.decodeArrayLoop(DoubleByte.java:173)
19:42:11  	at java.base/sun.nio.cs.DoubleByte$Decoder.decodeLoop(DoubleByte.java:233)
19:42:11  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:585)
19:42:11  	... 8 more

19:43:10  TEST: sun/nio/cs/TestStringCoding.java

19:43:10  STDERR:
19:43:10  java.nio.charset.CoderMalfunctionError: java.lang.NullPointerException: Cannot load from byte/boolean array because "ba" is null
19:43:10  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:587)
19:43:10  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:806)
19:43:10  	at TestStringCoding.testNewString(TestStringCoding.java:180)
19:43:10  	at TestStringCoding.main(TestStringCoding.java:67)
19:43:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:43:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19:43:10  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:43:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:43:10  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:43:10  	at java.base/java.lang.Thread.run(Thread.java:889)
19:43:10  Caused by: java.lang.NullPointerException: Cannot load from byte/boolean array because "ba" is null
19:43:10  	at java.base/java.lang.StringCoding.hasNegatives(StringCoding.java:40)
19:43:10  	at java.base/java.lang.String.decodeASCII(String.java:1202)
19:43:10  	at java.base/java.lang.Access.decodeASCII(Access.java:375)
19:43:10  	at java.base/sun.nio.cs.DoubleByte$Decoder.decodeArrayLoop(DoubleByte.java:173)
19:43:10  	at java.base/sun.nio.cs.DoubleByte$Decoder.decodeLoop(DoubleByte.java:233)
19:43:10  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:585)
19:43:10  	... 9 more

19:43:10  TEST: sun/nio/cs/FindDecoderBugs.java

19:43:10  STDERR:
19:43:10  java.nio.charset.CoderMalfunctionError: java.lang.NullPointerException: Cannot load from byte/boolean array because "ba" is null
19:43:10  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:587)
19:43:10  	at FindDecoderBugs$CharsetTester.recode(FindDecoderBugs.java:206)
19:43:10  	at FindDecoderBugs$CharsetTester.recode2(FindDecoderBugs.java:256)
19:43:10  	at FindDecoderBugs$CharsetTester.test(FindDecoderBugs.java:268)
19:43:10  	at FindDecoderBugs$CharsetTester.testPrefix(FindDecoderBugs.java:316)
19:43:10  	at FindDecoderBugs.testCharset(FindDecoderBugs.java:399)
19:43:10  	at FindDecoderBugs.realMain(FindDecoderBugs.java:420)
19:43:10  	at FindDecoderBugs.main(FindDecoderBugs.java:446)
19:43:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:43:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19:43:10  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:43:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:43:10  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
19:43:10  	at java.base/java.lang.Thread.run(Thread.java:889)
19:43:10  Caused by: java.lang.NullPointerException: Cannot load from byte/boolean array because "ba" is null
19:43:10  	at java.base/java.lang.StringCoding.hasNegatives(StringCoding.java:40)
19:43:10  	at java.base/java.lang.String.decodeASCII(String.java:1202)
19:43:10  	at java.base/java.lang.Access.decodeASCII(Access.java:375)
19:43:10  	at java.base/sun.nio.cs.DoubleByte$Decoder.decodeArrayLoop(DoubleByte.java:173)
19:43:10  	at java.base/sun.nio.cs.DoubleByte$Decoder.decodeLoop(DoubleByte.java:233)
19:43:10  	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:585)
19:43:10  	... 13 more

19:43:10  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
19:43:10  --------------------------------------------------
19:48:36  Test results: passed: 433; failed: 3
19:48:36  Report written to /Users/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_mac/jvmtest/openjdk/report/html/report.html
19:48:36  Results written to /Users/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16474730174593/jdk_nio_0/work
19:48:36  Error: Some tests failed or other problems occurred.
19:48:36  
19:48:36  jdk_nio_0_FAILED
```
50x grinder - `job/Grinder/21860/`

**Comment by JasonFengJ9** [comment]
JDK18 - `job/Test_openjdk18_j9_extended.openjdk_x86-64_windows/12/`
```
openjdk version "18" 2022-03-22
IBM Semeru Runtime Open Edition 18+37 (build 18+37)
Eclipse OpenJ9 VM 18+37 (build master-1621137e3, JRE 18 Windows Server 2016 amd64-64-Bit Compressed References 20220319_45 (JIT enabled, AOT enabled)
OpenJ9   - 1621137e3
OMR      - 644b9078b
JCL      - 155d7b8e1c based on jdk-18+37)
```

```
[2022-03-19T19:30:11.921Z] variation: Mode650
[2022-03-19T19:30:11.921Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-03-19T19:32:14.204Z] TEST: java/text/Collator/Regression.java

[2022-03-19T19:32:14.207Z] stderr:
[2022-03-19T19:32:14.207Z] Exception in thread "main" java/nio/charset/CoderMalfunctionError: java.lang.NullPointerException: Cannot invoke "java.nio.Buffer.arrayOffset()" because "dst" is null
[2022-03-19T19:32:14.207Z] 	at java/nio/charset/CharsetDecoder.decode (java.base@18/CharsetDecoder.java:587)
[2022-03-19T19:32:14.207Z] 	at com/sun/javatest/regtest/agent/AgentServer$3.decode (AgentServer.java:495)
[2022-03-19T19:32:14.207Z] 	at com/sun/javatest/regtest/agent/AgentServer$3.write (AgentServer.java:459)
[2022-03-19T19:32:14.207Z] 	at java/io/PrintStream.write (java.base@18/PrintStream.java:574)
[2022-03-19T19:32:14.207Z] 	at sun/nio/cs/StreamEncoder.writeBytes (java.base@18/StreamEncoder.java:234)
[2022-03-19T19:32:14.207Z] 	at sun/nio/cs/StreamEncoder.implFlushBuffer (java.base@18/StreamEncoder.java:313)
[2022-03-19T19:32:14.207Z] 	at sun/nio/cs/StreamEncoder.flushBuffer (java.base@18/StreamEncoder.java:111)
[2022-03-19T19:32:14.207Z] 	at java/io/OutputStreamWriter.flushBuffer (java.base@18/OutputStreamWriter.java:180)
[2022-03-19T19:32:14.207Z] 	at java/io/PrintStream.write (java.base@18/PrintStream.java:703)
[2022-03-19T19:32:14.207Z] 	at java/io/PrintStream.print (java.base@18/PrintStream.java:875)
[2022-03-19T19:32:14.207Z] 	at java/lang/ThreadGroup.uncaughtException (java.base@18/ThreadGroup.java:874)
[2022-03-19T19:32:14.207Z] 	at java/lang/ThreadGroup.uncaughtException (java.base@18/ThreadGroup.java:868)
[2022-03-19T19:32:14.207Z] 	at java/lang/Thread.uncaughtException (java.base@18/Thread.java:1403)

[2022-03-19T19:33:53.876Z] TEST: java/text/Format/DateFormat/DateFormatSymbolsSerializationTest.java

[2022-03-19T19:33:53.877Z] stderr:
[2022-03-19T19:33:53.877Z] Exception in thread "main" java/nio/charset/CoderMalfunctionError: java.lang.NullPointerException: Cannot invoke "java.nio.Buffer.arrayOffset()" because "dst" is null
[2022-03-19T19:33:53.877Z] 	at java/nio/charset/CharsetDecoder.decode (java.base@18/CharsetDecoder.java:587)
[2022-03-19T19:33:53.877Z] 	at com/sun/javatest/regtest/agent/AgentServer$3.decode (AgentServer.java:495)
[2022-03-19T19:33:53.877Z] 	at com/sun/javatest/regtest/agent/AgentServer$3.write (AgentServer.java:459)
[2022-03-19T19:33:53.877Z] 	at java/io/PrintStream.write (java.base@18/PrintStream.java:574)
[2022-03-19T19:33:53.877Z] 	at sun/nio/cs/StreamEncoder.writeBytes (java.base@18/StreamEncoder.java:234)
[2022-03-19T19:33:53.877Z] 	at sun/nio/cs/StreamEncoder.implFlushBuffer (java.base@18/StreamEncoder.java:313)
[2022-03-19T19:33:53.877Z] 	at sun/nio/cs/StreamEncoder.flushBuffer (java.base@18/StreamEncoder.java:111)
[2022-03-19T19:33:53.877Z] 	at java/io/OutputStreamWriter.flushBuffer (java.base@18/OutputStreamWriter.java:180)
[2022-03-19T19:33:53.877Z] 	at java/io/PrintStream.write (java.base@18/PrintStream.java:703)
[2022-03-19T19:33:53.877Z] 	at java/io/PrintStream.print (java.base@18/PrintStream.java:875)
[2022-03-19T19:33:53.877Z] 	at java/lang/ThreadGroup.uncaughtException (java.base@18/ThreadGroup.java:874)
[2022-03-19T19:33:53.877Z] 	at java/lang/ThreadGroup.uncaughtException (java.base@18/ThreadGroup.java:868)
[2022-03-19T19:33:53.877Z] 	at java/lang/Thread.uncaughtException (java.base@18/Thread.java:1403)

[2022-03-19T19:34:43.207Z] TEST: java/text/Format/MessageFormat/MessageRegression.java

[2022-03-19T19:34:59.909Z] TEST: java/text/Format/NumberFormat/Bug6278616.java

[2022-03-19T19:36:44.288Z] jdk_text_1_FAILED
```

**Comment by pshipton** [comment]
Looking at the grinder (job/Grinder/21860/), it failed 11/50, which is enough for a blocker label.

**Comment by pshipton** [comment]
@dchopra001 could this be related to https://github.com/eclipse-openj9/openj9/pull/14679 aka https://github.com/eclipse-openj9/openj9/pull/14671 ?

**Comment by dchopra001** [comment]
Taking a look at this now.

**Comment by dchopra001** [comment]
The issue in https://github.com/eclipse-openj9/openj9/issues/14743#issuecomment-1075133481 looks to be the same one as here https://github.com/eclipse-openj9/openj9/issues/14654. This doesn't look related to my changes as #14671 wasn't merged at the time that this issue was reported.

**Comment by pshipton** [comment]
I took a closer look at the grinder results. Some of the results are gone already, and in the remaining results the failure isn't the original one shown here.

**Comment by pshipton** [comment]
Both this issue and https://github.com/eclipse-openj9/openj9/issues/14654 cover multiple different failures, which may or may not be the same. The original issue here is also reported in https://github.com/eclipse-openj9/openj9/issues/14654 so I'm going to close this as a dup.
