### ISSUE TITLE
gpf crash with InaccessibleAddress

### ISSUE THREAD

**Issue by anlong465** [eclipse-openj9/openj9#14747]
Java -version output
--------------------

Output from `java -version`.
openjdk version "1.8.0_322"
IBM Semeru Runtime Open Edition (build 1.8.0_322-b06)
Eclipse OpenJ9 VM (build openj9-0.30.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220128_306 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - c1d9a7af7c based on jdk8u322-b06)

We could re-produce such issue with jdk8u312-b07 alsoL
openjdk version "1.8.0_312"
IBM Semeru Runtime Open Edition (build 1.8.0_312-b07)
Eclipse OpenJ9 VM (build openj9-0.29.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20211022_234 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 8860d39588 based on jdk8u312-b07)
 

Summary of problem
------------------

Our application (big data analysis, running upon JDK1.8 with HotSpot) have been on-production many years, but it is heavy memory-consumed. Sometime, when too many concurrent incoming requests or too big data searching, our application would meet OOM error along with restarting.

Given OpenJ9's amazing memory management, we try to leverage with OpenJ9 JVM to reduce such OOM possibility. Such journey begins very well when we verify OpenJ9 JVM in our internal testing environment: our application keep running well without any issue for weeks. But, when we verify OpenJ9 JVM in customer environment, our application would crash with gpf event sometime. 

After some testing, we could easily re-produce such issue in customer UAT environment when customer's production environment metadata was imported into customer UAT environment. However, so far, we had never reproduced such gpf crash in our internal environment with OpenJ9 JVM.

So, who causes such issue? Our application? Customer metadata? or OpenJ9 JVM?

1) is it caused by our application?
well, it looks like so. After all, every time when such gpf happens, we would have the same "Java callstack" of "Current thread" from javacore file.

1XMCURTHDINFO  Current thread
3XMTHREADINFO      "http-nio-7070-exec-11" J9VMThread:0x000000000312F400, omrthread_t:0x00007F449516E3B8, java/lang/Thread:0x0000000FFE0E5A80, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x11B, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x31E6, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007F43B4E05000, to:0x00007F43B4E45000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.684972502 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=118768368 (0x71442F0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at io/kyligence/au.a(SourceFile:337)
4XESTACKTRACE                at io/kyligence/au.c(SourceFile:155)
4XESTACKTRACE                at io/kyligence/au.a(SourceFile:247)
4XESTACKTRACE                at io/kyligence/au.a(SourceFile:182)
4XESTACKTRACE                at io/kyligence/au.<init>(SourceFile:63)
4XESTACKTRACE                at io/kyligence/kap/cube/cuboid/KapCuboidScheduler.<init>(SourceFile:48)
4XESTACKTRACE                at sun/reflect/GeneratedConstructorAccessor749.newInstance(Bytecode PC:28)
4XESTACKTRACE                at sun/reflect/DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Constructor.newInstance(Constructor.java:423(Compiled Code))
4XESTACKTRACE                at org/apache/kylin/cube/cuboid/CuboidScheduler.getInstance(CuboidScheduler.java:45)
4XESTACKTRACE                at org/apache/kylin/cube/model/CubeDesc.getInitialCuboidScheduler(CubeDesc.java:775)
5XESTACKTRACE                   (entered lock: org/apache/kylin/cube/model/CubeDesc@0x0000000B66BC63D0, entry count: 1)
4XESTACKTRACE                at org/apache/kylin/cube/model/AggregationGroup.calculateCuboidCombination$original$7aBQitQM(AggregationGroup.java:313)
4XESTACKTRACE                at org/apache/kylin/cube/model/AggregationGroup.calculateCuboidCombination$original$7aBQitQM$accessor$AmmNx5h3(AggregationGroup.java)
4XESTACKTRACE                at org/apache/kylin/cube/model/AggregationGroup$auxiliary$9c1cvkqx.call(Bytecode PC:4)
4XESTACKTRACE                at org/sunrise/api/span/agent/interceptor/MethodSpanInterceptor.intercept(MethodSpanInterceptor.java:39)
4XESTACKTRACE                at org/apache/kylin/cube/model/AggregationGroup.calculateCuboidCombination(AggregationGroup.java)
4XESTACKTRACE                at org/apache/kylin/cube/model/CubeDesc.validateAggregationGroupsCombination(CubeDesc.java:790)
4XESTACKTRACE                at org/apache/kylin/cube/model/CubeDesc.init$original$6OdbtVH2(CubeDesc.java:696)
4XESTACKTRACE                at org/apache/kylin/cube/model/CubeDesc.init$original$6OdbtVH2$accessor$r8cOOLAU(CubeDesc.java)
4XESTACKTRACE                at org/apache/kylin/cube/model/CubeDesc$auxiliary$9X2krWEN.call(Bytecode PC:8)
4XESTACKTRACE                at org/sunrise/api/span/agent/interceptor/MethodSpanInterceptor.intercept(MethodSpanInterceptor.java:39)
4XESTACKTRACE                at org/apache/kylin/cube/model/CubeDesc.init(CubeDesc.java)

For the top callstack "io/kyligence/au.a(SourceFile:337)", its corresponding source code is as belows 
    337:        for (Long normal : agg.getNormalDims()) {
    338:            fillBit(tmpChild, normal, parentCandidate);
    339:        }

And the below lines just shows the related function in line of 337
    public List<Long> getNormalDims() {
        return normalDims;
    }

So, the related source code are so simple, how could it cause such gpf event? Furthurmore, such code keeps running well upon HotSpot JVM! Our application development team reject to analysis such issue any more.

2) then, is it caused by the customer metadata? After all, such issue happens only upon customer environment. So, it is possible.

Given that we could easily reproduce such gpf issue in customer UAT environment, for method org/apache/kylin/cube/model/CubeDesc.init(CubeDesc.java), we leverage byte-buddy to do some enhancement for such method: before entering such method, we print out the CubeDesc name; and afer exiting such method, we print out its name again. When such gpf issue happens, we will check such log to identify which CubeDesc is been handling; after that, we will remove such CubeDesc from metadata database and re-test. Every time we could identify one different "bad" CubeDesc and remove it. Hopefully we could identify and remove all bad metadata, and then everything would be fine.

After keep doing such testing 10+ times, we analysis our log once again. Now we find out that: the "bad" CubeDesc that we just identify in the last test had successfully passed the previous tests.

So, for the same metadata, upon with the same OpenJ9 JVM, the same application will run into such gpf crash some time! So, we could not say it is caused by metadata.

3) now, we have to focus on OpenJ9 JVM: is OpenJ9 JVM wrong configured?
Actually, we had try many different JVM configuration. Such as java reflection (-Dsun.reflect.noInflation=true), and jit (we had JIT excluded for io/kyligence/au.a ), but such gpf issue keep happens in customer environment.

So, I have to ask for help from this community. How to diagnoise/analysis such issues? Any hint would be highly appreciated!

Diagnostic files
----------------
 
[OpenJ9 gpf crash.zip](https://github.com/eclipse-openj9/openj9/files/8301174/OpenJ9.gpf.crash.zip)

Sorry, the onsite team forget to package the core file. If it is necessary, I will file one request to ask for the whole log from customer once again.

**Comment by pshipton** [comment]
We can't diagnose anything without the core file. First please try the latest JVM if possible. We don't yet have a Semeru milestone build available for the next release (0.32), but I've created an OpenJ9 project build of the latest 0.32 content (see below). It's possible the problem is already fixed in the newer build, and if not this version should give us a proper stack trace in the crash output that may help narrow down where the problem is. Although we'll still need the core.

In order to diagnose a core file we need the system libraries from the system where the crash occurred. You can use `jpackcore` to create what is needed https://www.eclipse.org/openj9/docs/tool_jextract/

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_x86-64_linux_Release/25/OpenJ9-JDK8-x86-64_linux-20220318-152401.tar.gz
```
12:33:19  openjdk version "1.8.0_332-internal"
12:33:19  OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_03_18_15_24-b00)
12:33:19  Eclipse OpenJ9 VM (build v0.32.0-release-c2ebb24, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220318_25 (JIT enabled, AOT enabled)
12:33:19  OpenJ9   - c2ebb24
12:33:19  OMR      - 648fb63
12:33:19  JCL      - ed00c08 based on jdk8u332-b04)
```
