### ISSUE TITLE
jdmpview's info thread * on an AIX core dump shows potentially excessive ObjectMonitor_V2 memory usage/OOM

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#14796]
Java -version output
--------------------

Output from `java -version`:

* core dump: `JRE 1.8.0 AIX ppc64-64 (build 8.0.6.35 - pap6480sr6fp35-20210714_01(SR6 FP35))`
* jdmpview:
  ```
  java version "1.8.0_321"
  Java(TM) SE Runtime Environment (build 8.0.7.5 - pxa6480sr7fp5-20220208_01(SR7 FP5))
  IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220104_19630 (JIT enabled, AOT enabled)
  OpenJ9   - 2d4c7d9
  OMR      - 59845b7
  IBM      - 3c151c1)
  JCL - 20220120_01 based on Oracle jdk8u321-b07
  ```

Summary of problem
------------------

In the following example, `jdmpview` is started with `-Xmx5G` and the resulting OOM heapdump shows 4.4GB retained by `com.ibm.j9ddr.vm29.j9.walkers.HeapWalker`:

```
$ /ecurep/sf/TS008/229/TS008229108/support_files/ibm-java-sdk-8.0-7.5-linux-x86_64.tgz_unpack/ibm-java-x86_64-80/bin/jdmpview -J-Xmx5g -core /ecurep/sf/TS008/229/TS008229108/2022-03-24/core.20220324.130424.24117626.0001.dmp
DTFJView version 4.29.5, using DTFJ version 1.12.29003
[...]
Source : file:///ecurep/sf/TS008/229/TS008229108/2022-03-24/core.20220324.130424.24117626.0001.dmp
	*0 : PID: 0 : JRE 1.8.0 AIX ppc64-64 (build 8.0.6.35 - pap6480sr6fp35-20210714_01(SR6 FP35))

> info thread * > threads.txt
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/03/28 16:18:54 - please wait.
[...]
JVMDUMP032I JVM requested Heap dump using '/ecurep/sf/TS008/229/TS008229108/2022-03-24/heapdump.20220328.161854.929593.0002.phd' in response to an event
```

The resulting `heapdump.20220328.161854.929593.0002.phd` of `jdmpview` shows the class `com.ibm.j9ddr.vm29.j9.walkers.HeapWalker` retaining 4.4GB of heap and two fields of types `java.util.HashMap` and `java.util.TreeSet` retaining about 31 million instances of `com.ibm.j9ddr.vm29.j9.ObjectMonitor_V2`:

```
Class Name                                                         |    Objects | Shallow Heap
-----------------------------------------------------------------------------------------------
com.ibm.j9ddr.vm29.j9.ObjectMonitor_V2                             | 31,111,519 |      1.62 GB
java.util.TreeMap$Entry                                            | 31,111,519 |    949.45 MB
java.util.HashMap$Node                                             | 31,111,219 |    712.08 MB
com.ibm.j9ddr.vm29.pointer.generated.J9ObjectPointer               | 31,111,510 |    474.72 MB
com.ibm.j9ddr.vm29.pointer.generated.J9ObjectMonitorPointer        | 31,100,510 |    474.56 MB
java.util.HashMap$Node[]                                           |         95 |    241.35 MB
java.util.HashMap$TreeNode                                         |        405 |     22.15 KB
com.ibm.j9ddr.vm29.types.UDATA                                     |        210 |      4.92 KB
com.ibm.j9ddr.vm29.j9.gc.GCHeapRegionDescriptor_V1                 |        105 |      4.92 KB
java.util.HashMap                                                  |        106 |      4.14 KB
com.ibm.j9ddr.vm29.pointer.VoidPointer                             |        210 |      3.28 KB
com.ibm.j9ddr.vm29.pointer.generated.MM_MemorySubSpacePointer      |        105 |      1.64 KB
com.ibm.j9ddr.vm29.pointer.generated.MM_MemoryPoolPointer          |        105 |      1.64 KB
com.ibm.j9ddr.vm29.pointer.generated.MM_HeapRegionDescriptorPointer|        105 |      1.64 KB
java.util.HashMap$KeySet                                           |        105 |      1.64 KB
java.util.HashSet                                                  |        105 |      1.64 KB
char[]                                                             |          1 |         96 B
java.lang.Class                                                    |          1 |         88 B
java.util.TreeMap                                                  |          1 |         48 B
java.util.TreeSet                                                  |          1 |         16 B
java.lang.String                                                   |          1 |         16 B
-----------------------------------------------------------------------------------------------
```

The OOM stack trace is:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.ibm.j9ddr.vm29.j9.ObjectHash.inlineConvertValueToHash(ObjectHash.java:127)
	at com.ibm.j9ddr.vm29.j9.ObjectHash.convertObjectAddressToHash(ObjectHash.java:149)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.getObjectHashCode(GCObjectModel_V1.java:315)
	at com.ibm.j9ddr.vm29.j9.ObjectModel.getObjectHashCode(ObjectModel.java:338)
	at com.ibm.j9ddr.vm29.j9.MonitorTableList.peek(MonitorTableList.java:89)
	at com.ibm.j9ddr.vm29.j9.ObjectMonitor_V2.<init>(ObjectMonitor_V2.java:65)
	at com.ibm.j9ddr.vm29.j9.ObjectMonitor.fromJ9Object(ObjectMonitor.java:55)
	at com.ibm.j9ddr.vm29.j9.gc.MMObjectAccessBarrier_V1.getMonitor(MMObjectAccessBarrier_V1.java:145)
	at com.ibm.j9ddr.vm29.j9.ObjectAccessBarrier.getMonitor(ObjectAccessBarrier.java:117)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.processFlatMonitor(HeapWalker.java:218)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.doState(HeapWalker.java:183)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.walk(HeapWalker.java:119)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.runFlatLockMonitorRegionWalk(HeapWalker.java:270)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.initializeFlatLockedMonitors(HeapWalker.java:255)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.getFlatLockedMonitors(HeapWalker.java:237)
	at com.ibm.j9ddr.vm29.j9.walkers.MonitorIterator.<init>(MonitorIterator.java:75)
	at com.ibm.j9ddr.vm29.view.dtfj.java.j9.DTFJMonitorIterator.<init>(DTFJMonitorIterator.java:42)
	at com.ibm.j9ddr.vm29.view.dtfj.java.DTFJJavaRuntime.getMonitors(DTFJJavaRuntime.java:737)
	at com.ibm.jvm.dtfjview.commands.infocommands.InfoThreadCommand.getMonitors(InfoThreadCommand.java:424)
	at com.ibm.jvm.dtfjview.commands.infocommands.InfoThreadCommand.run(InfoThreadCommand.java:97)
	at com.ibm.java.diagnostics.utils.Context.tryCommand(Context.java:141)
	at com.ibm.java.diagnostics.utils.Context.execute(Context.java:97)
	at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:173)
	at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:111)
	at com.ibm.jvm.dtfjview.commands.SimpleRedirectorCommand.run(SimpleRedirectorCommand.java:66)
	at com.ibm.java.diagnostics.utils.Context.tryCommand(Context.java:141)
	at com.ibm.java.diagnostics.utils.Context.execute(Context.java:97)
	at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:173)
	at com.ibm.jvm.dtfjview.Session.execute(Session.java:811)
	at com.ibm.jvm.dtfjview.Session.execute(Session.java:765)
	at com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
	at com.ibm.jvm.dtfjview.tools.ToolsRegistry.process(ToolsRegistry.java:155)
	at com.ibm.jvm.dtfjview.tools.impl.OutFileTool.process(OutFileTool.java:90)
	at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:103)
	at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
	at com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
	at com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:739)
	at com.ibm.jvm.dtfjview.Session.run(Session.java:663)
	at com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
	at com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
```

Similar symptoms are experienced when running MAT with `-Xmx64g` and the OOM stack is also related to processing monitors:

```
java.lang.OutOfMemoryError: Java heap space
        at com.ibm.j9ddr.vm29.pointer.AbstractPointer.getUDATAAtOffset(AbstractPointer.java:412)
        at com.ibm.j9ddr.vm29.pointer.generated.J9IdentityHashDataPointer.hashSaltPolicy(J9IdentityHashDataPointer.java:199)
        at com.ibm.j9ddr.vm29.j9.ObjectHash.getSalt(ObjectHash.java:43)
        at com.ibm.j9ddr.vm29.j9.ObjectHash.inlineConvertValueToHash(ObjectHash.java:120)
        at com.ibm.j9ddr.vm29.j9.ObjectHash.convertObjectAddressToHash(ObjectHash.java:149)
        at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.getObjectHashCode(GCObjectModel_V1.java:315)
        at com.ibm.j9ddr.vm29.j9.ObjectModel.getObjectHashCode(ObjectModel.java:338)
        at com.ibm.j9ddr.vm29.j9.MonitorTableList.peek(MonitorTableList.java:89)
        at com.ibm.j9ddr.vm29.j9.ObjectMonitor_V2.<init>(ObjectMonitor_V2.java:65)
        at com.ibm.j9ddr.vm29.j9.ObjectMonitor.fromJ9Object(ObjectMonitor.java:55)
        at com.ibm.j9ddr.vm29.j9.gc.MMObjectAccessBarrier_V1.getMonitor(MMObjectAccessBarrier_V1.java:145)
        at com.ibm.j9ddr.vm29.j9.ObjectAccessBarrier.getMonitor(ObjectAccessBarrier.java:117)
        at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.processFlatMonitor(HeapWalker.java:218)
        at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.doState(HeapWalker.java:183)
        at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.walk(HeapWalker.java:119)
        at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.runFlatLockMonitorRegionWalk(HeapWalker.java:270)
        at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.initializeFlatLockedMonitors(HeapWalker.java:255)
        at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.getFlatLockedMonitors(HeapWalker.java:237)
        at com.ibm.j9ddr.vm29.j9.walkers.MonitorIterator.<init>(MonitorIterator.java:75)
        at com.ibm.j9ddr.vm29.view.dtfj.java.j9.DTFJMonitorIterator.<init>(DTFJMonitorIterator.java:42)
        at com.ibm.j9ddr.vm29.view.dtfj.java.DTFJJavaRuntime.getMonitors(DTFJJavaRuntime.java:737)
```

Diagnostic files
----------------

`/ecurep/sf/TS008/229/TS008229108/2022-03-24/core.20220324.130424.24117626.0001.dmp`

@keithc-ca FYI

**Comment by georgejxu** [comment]
also, when first open, the pid was not found.

**Comment by kgibm** [comment]
Same OutOfMemoryError after doubling the heap with `jdmpview -J-Xmx10g` and the resulting heapdump shows additional growth in the same places:

```
Class Name                                                         |     Objects | Shallow Heap
------------------------------------------------------------------------------------------------
com.ibm.j9ddr.vm29.j9.ObjectMonitor_V2                             |  64,032,267 |      3.34 GB
java.util.TreeMap$Entry                                            |  64,032,267 |      1.91 GB
java.util.HashMap$Node                                             |  64,032,903 |      1.43 GB
com.ibm.j9ddr.vm29.pointer.generated.J9ObjectPointer               |  64,032,267 |    977.05 MB
com.ibm.j9ddr.vm29.pointer.generated.J9ObjectMonitorPointer        |  63,959,070 |    975.94 MB
java.util.HashMap$Node[]                                           |         248 |    495.76 MB
com.ibm.j9ddr.vm29.j9.gc.GCHeapRegionDescriptor_V1                 |         658 |     30.84 KB
com.ibm.j9ddr.vm29.types.UDATA                                     |       1,316 |     30.84 KB
java.util.HashMap                                                  |         659 |     25.74 KB
com.ibm.j9ddr.vm29.pointer.VoidPointer                             |       1,316 |     20.56 KB
java.util.HashMap$KeySet                                           |         658 |     10.28 KB
com.ibm.j9ddr.vm29.pointer.generated.MM_MemorySubSpacePointer      |         658 |     10.28 KB
com.ibm.j9ddr.vm29.pointer.generated.MM_HeapRegionDescriptorPointer|         658 |     10.28 KB
java.util.HashSet                                                  |         658 |     10.28 KB
com.ibm.j9ddr.vm29.pointer.generated.MM_MemoryPoolPointer          |         658 |     10.28 KB
java.util.HashMap$TreeNode                                         |          22 |      1.20 KB
char[]                                                             |           1 |         96 B
java.lang.Class                                                    |           1 |         88 B
java.util.TreeMap                                                  |           1 |         48 B
java.lang.String                                                   |           1 |         16 B
java.util.TreeSet                                                  |           1 |         16 B
Total: 21 entries                                                  | 320,096,288 |      9.07 GB
------------------------------------------------------------------------------------------------
```

**Comment by keithc-ca** [comment]
I tried to write a test program to cause a large number of 'FlatLock' monitors to be created. Unless the objects remain locked, the monitors seem to disappear (as part of the garbage collector's behavior (?)).

This leads me to my belief that the heap is somehow corrupted such that one or more objects have zero (or negative) sizes while simultaneously being locked. The non-positive size means traversing the heap stalls, adding the same monitors repeatedly (without bound).

I plan to add checking for reasonable object sizes to the heap traversal code.
