### ISSUE TITLE
JDK18 jdk_security4_0_FAILED sun/security/krb5/auto/BasicProc.java Exception: Proc abnormal end

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14803]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_extended.openjdk_x86-64_linux/13/`:
```
openjdk version "18" 2022-03-22
IBM Semeru Runtime Open Edition 18+37 (build 18+37)
Eclipse OpenJ9 VM 18+37 (build master-a6a0c1c55, JRE 18 Linux amd64-64-Bit Compressed References 20220326_48 (JIT enabled, AOT enabled)
OpenJ9   - a6a0c1c55
OMR      - 1c51597c3
JCL      - 5d4882cb8b based on jdk-18+37)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security4_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F48%2Fibm-semeru-open-jre_x64_linux_JDK18_2022-03-26-14-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F48%2Fibm-semeru-open-testimage_x64_linux_JDK18_2022-03-26-14-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F48%2Fibm-semeru-open-debugimage_x64_linux_JDK18_2022-03-26-14-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F48%2Fibm-semeru-open-jdk_x64_linux_JDK18_2022-03-26-14-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk18&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-03-26T18:17:46.299Z] variation: Mode150
[2022-03-26T18:17:46.299Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-03-26T18:18:27.791Z] TEST: sun/security/krb5/auto/BasicProc.java

[2022-03-26T18:18:27.794Z] STDERR:
[2022-03-26T18:18:27.794Z] java.net.SocketException: Socket closed
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252)
[2022-03-26T18:18:27.794Z] 	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:701)
[2022-03-26T18:18:27.794Z] 	at KDC$1.run(KDC.java:1553)
[2022-03-26T18:18:27.794Z] Caused by: java.nio.channels.AsynchronousCloseException
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:523)
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:677)
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:635)
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
[2022-03-26T18:18:27.794Z] 	... 2 more
[2022-03-26T18:18:27.794Z] java.net.SocketException: Socket closed
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252)
[2022-03-26T18:18:27.794Z] 	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:701)
[2022-03-26T18:18:27.794Z] 	at KDC$1.run(KDC.java:1553)
[2022-03-26T18:18:27.794Z] Caused by: java.nio.channels.ClosedChannelException
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.ensureOpen(DatagramChannelImpl.java:267)
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:624)
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
[2022-03-26T18:18:27.794Z] 	... 2 more
[2022-03-26T18:18:27.794Z] java.net.SocketException: Socket closed
[2022-03-26T18:18:27.794Z] 	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252)
[2022-03-26T18:18:27.794Z] 	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:701)
[2022-03-26T18:18:27.794Z] 	at KDC$1.run(KDC.java:1553)

[2022-03-26T18:18:27.795Z] java.lang.Exception: Proc abnormal end
[2022-03-26T18:18:27.795Z] 	at jdk.test.lib.process.Proc.readData(Proc.java:373)
[2022-03-26T18:18:27.795Z] 	at BasicProc.once(BasicProc.java:275)
[2022-03-26T18:18:27.795Z] 	at BasicProc.main(BasicProc.java:146)
[2022-03-26T18:18:27.795Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-03-26T18:18:27.795Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-03-26T18:18:27.795Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-03-26T18:18:27.795Z] 	at java.base/java.lang.Thread.run(Thread.java:889)

[2022-03-26T18:22:07.793Z] jdk_security4_0_FAILED
```
This appears a machine/network issue however the failure is across platform.
Note: this is a different test in same test suite as [JDK18 jdk_security4_FAILED Server returned HTTP response code: 401 for URL - RuntimeException: Failed to login as subject ](https://github.com/eclipse-openj9/openj9/issues/14499)
50x grinder - job/Grinder/22086/

**Comment by pshipton** [comment]
@JasonFengJ9 the grinder failed consistently. I assume the test used to pass. Does it still pass on the older build, can we find a good/bad build?

**Comment by JasonFengJ9** [comment]
It has been failed since earliest test history Feb. 1st `job/Test_openjdk18_j9_extended.openjdk_x86-64_linux/4/consoleFull`, was just marked by [JDK18 jdk_security4_FAILED Server returned HTTP response code: 401 for URL - RuntimeException: Failed to login as subject ](https://github.com/eclipse-openj9/openj9/issues/14499)
I think JDK18 probably never passed it.

**Comment by pshipton** [comment]
Java 11, 17 have a test with the same name, what is the status on those versions?

**Comment by JasonFengJ9** [comment]
JDK 11/17 `jdk_security4` passed, and there is no test exclusion for `sun/security/krb5/auto/BasicProc.java`.

**Comment by pshipton** [comment]
@tajila this needs investigation. I've added it to the 0.31 milestone plan.

**Comment by JasonFengJ9** [comment]
15x grinder w/ RI - `job/Grinder/22098/`

**Comment by tajila** [comment]
@JasonFengJ9 is this related to `domainCombiner` ?

**Comment by JasonFengJ9** [comment]
> is this related to domainCombiner ?

This failure wasn't seen in pre-JDK18 like [jdk_security4 test failed with credential exception because server returned HTTP response code 401](https://github.com/eclipse-openj9/openj9/issues/11268) which was due to a `null` `domainCombiner`.
I think this one is not related to that.

This is to test interop between Java GSS and native GSS, and `native.kdc.path` with a native KDC, maybe something missing there.

**Comment by tajila** [comment]
So far Ive been able to narrow it down to https://github.com/ibmruntimes/openj9-openjdk-jdk18/blob/742164f41ccbae087b64a8f282ff98d610ab3f14/src/java.base/unix/native/libnio/ch/DatagramChannelImpl.c#L101

It is failing with `EINTR`

**Comment by tajila** [comment]
Docs:

```
EINTR

The receive was interrupted by delivery of a [signal](https://linux.die.net/man/7/signal) before any data were available; see signal(7).
```

**Comment by tajila** [comment]
Not sure what would be sending a signal, and why it occurs consistently.

@JasonFengJ9 any ideas?

**Comment by JasonFengJ9** [comment]
> Not sure what would be sending a signal, and why it occurs consistently.

It is unlikely due to random machine issue considering this error is consistent and across platforms.
My guess is from test itself when a failure occurred earlier and it is going to exit.

**Comment by JasonFengJ9** [comment]
This is a `SecurityManager` related test failure, one of `checkPermission` failure occurred at [1]. Commenting out that line can run test further however still failed probably at another `checkPermission` (to be determined).
Setting current `SecurityManager` to null (disable all permission check) can make `jdk_security4` pass.

Next step is to investigate why the code (bootstrap w/ all permissions) doesn't have `AuthPermission("getSubject")`, my guess is `doPrivileged` stackwalk doesn't work properly.

Since `SecurityManager` is being deprecated for removal, I think this is not a Java 18 blocker.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk18/blob/5d4882cb8b448748b865664fb47ff6a3fb539ba9/src/java.base/share/classes/javax/security/auth/Subject.java#L303

**Comment by pshipton** [comment]
> Since SecurityManager is being deprecated for removal, I think this is not a Java 18 blocker.

Although it's deprecated for removal, it's still supported and usable in jdk18.

**Comment by tajila** [comment]
> Next step is to investigate why the code (bootstrap w/ all permissions) doesn't have AuthPermission("getSubject"), my guess is doPrivileged stackwalk doesn't work properly.

This still fails with `-XX:+ShowHiddenFrames` turned on so Im not sure its related to the stack walker code

**Comment by JasonFengJ9** [comment]
> This still fails with -XX:+ShowHiddenFrames turned on so Im not sure its related to the stack walker code

I verified that as well (`-XX:+ShowHiddenFrames` has no impact). Just to clarify, I was referring if stackwalking has stopped at the caller of `doPrivileged` correctly.
After some digging, it appears a similar problem at `AccessController.doPrivilegedWithCombiner` though this is a different manifestation w/ `SecurityManager.checkPermission`. I have a change to fix this test failure but failed another test suite, investigating...

**Comment by pshipton** [comment]
Moving to 0.32 while the investigation continues.

**Comment by pshipton** [comment]
Moving to 0.33 while the investigation continues.

**Comment by JasonFengJ9** [comment]
Just to clarify, this OpenJ9 failure is due to an unexpected hotspot behaviour being tracked at an internal RTC workitem 147318, currently awaiting for Oracle response.
