### ISSUE TITLE
jdk_nio_0_FAILED java/nio/channels/DatagramChannel/Promiscuous.java RuntimeException: Expected message not received

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14804]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_extended.openjdk_s390x_linux/61/`(`rhel7s390x-3-10`):
```
java version "11.0.15" 2022-04-19
IBM Semeru Runtime Certified Edition 11.0.15+7 (build 11.0.15+7)
Eclipse OpenJ9 VM 11.0.15+7 (build master-a6a0c1c55, JRE 11 Linux s390x-64-Bit Compressed References 20220325_268 (JIT enabled, AOT enabled)
OpenJ9   - a6a0c1c55
OMR      - 1c51597c3
JCL      - 2c3bc636ec based on jdk-11.0.15+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_nio_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F268%2Fibm-semeru-certified-testimage_s390x_linux_JDK11U_2022-03-26-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F268%2Fibm-semeru-certified-debugimage_s390x_linux_JDK11U_2022-03-26-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F268%2Fibm-semeru-certified-jdk_s390x_linux_JDK11U_2022-03-26-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F268%2Fibm-semeru-certified-jre_s390x_linux_JDK11U_2022-03-26-01-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-03-26T02:37:29.879Z] variation: Mode150
[2022-03-26T02:37:29.879Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-03-26T02:39:54.066Z] TEST: java/nio/channels/DatagramChannel/Promiscuous.java

[2022-03-26T02:39:54.068Z] STDERR:
[2022-03-26T02:39:54.068Z] java.lang.RuntimeException: Expected message not received
[2022-03-26T02:39:54.068Z] 	at Promiscuous.receiveDatagram(Promiscuous.java:106)
[2022-03-26T02:39:54.068Z] 	at Promiscuous.test(Promiscuous.java:180)
[2022-03-26T02:39:54.068Z] 	at Promiscuous.main(Promiscuous.java:220)
[2022-03-26T02:39:54.068Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-03-26T02:39:54.068Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-03-26T02:39:54.068Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-03-26T02:39:54.068Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-03-26T02:39:54.068Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-03-26T02:39:54.068Z] 	at java.base/java.lang.Thread.run(Thread.java:871)
[2022-03-26T02:39:54.068Z] 
[2022-03-26T02:39:54.068Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-03-26T02:39:54.068Z] JavaTest Message: shutting down test
[2022-03-26T02:39:54.068Z] 
[2022-03-26T02:39:54.068Z] 
[2022-03-26T02:39:54.068Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected message not received
[2022-03-26T02:39:54.068Z] --------------------------------------------------
[2022-03-26T02:56:50.945Z] Test results: passed: 390; failed: 1
[2022-03-26T02:56:52.560Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux/jvmtest/openjdk/report/html/report.html
[2022-03-26T02:56:52.560Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16482605706515/jdk_nio_0/work
[2022-03-26T02:56:52.560Z] Error: Some tests failed or other problems occurred.
[2022-03-26T02:56:52.560Z] 
[2022-03-26T02:56:52.560Z] jdk_nio_0_FAILED
```

50x grinder - `job/Grinder/22087/` - all failed (10x grinder each at 5 machines)

**Comment by pshipton** [comment]
The grinders all failed, but is this a machine setup problem?

**Comment by JasonFengJ9** [comment]
From test history, it appears machine specific (some passed), launched 60x grinder - `view/Test_grinder/job/Grinder/22096/` (distributed to 20 machines)

**Comment by pshipton** [comment]
All the tests in the grinder failed.

**Comment by pshipton** [comment]
@JasonFengJ9 is there any machine information available for where the test has previously passed?
These are all the machines where the grinder ran, everything is rhel7, machines are repeated in the 20x distribution.
rhel7s390x-3-3
rhel7s390x-3-7
rhel7s390x-3-8
rhel7s390x-4-2
rhel7s390x-4-5
rhel7s390x-4-10

**Comment by JasonFengJ9** [comment]
It appears all passed machine are `ub18`
```
ub18s390xrt-1-5
ub18s390xrt-1-2
ub18s390xrt-1-4
```

**Comment by pshipton** [comment]
I think this should be opened internally, as it seems a machine issue.
