### ISSUE TITLE
OpenJDK zip/ZipFile/ManyEntries zip/TestExtraTime unexpected times 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14841]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/7 - [mac11-aarch64-1](https://openj9-jenkins.osuosl.org/computer/mac11-aarch64-1)
jdk_util_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops`
java/util/zip/ZipFile/ManyEntries.java
```
12:02:32  rerun:
12:02:32  cd /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/scratch/2 && \
12:02:32  HOME=/Users/jenkins \
12:02:32  PATH=/bin:/usr/bin:/usr/sbin \
12:02:32      /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image/bin/java \
12:02:32          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops' \
12:02:32          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-UseCompressedOops' \
12:02:32          -Dtest.compiler.opts= \
12:02:32          -Dtest.java.opts= \
12:02:32          -Dtest.jdk=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image \
12:02:32          -Dcompile.jdk=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image \
12:02:32          -Dtest.timeout.factor=8.0 \
12:02:32          -Dtest.nativepath=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
12:02:32          -Dtest.root=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk \
12:02:32          -Dtest.name=java/util/zip/ZipFile/ManyEntries.java \
12:02:32          -Dtest.file=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/ZipFile/ManyEntries.java \
12:02:32          -Dtest.src=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/ZipFile \
12:02:32          -Dtest.src.path=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/ZipFile \
12:02:32          -Dtest.classes=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/2/java/util/zip/ZipFile/ManyEntries.d \
12:02:32          -Dtest.class.path=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/2/java/util/zip/ZipFile/ManyEntries.d \
12:02:32          -Dtest.class.path.prefix=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/2/java/util/zip/ZipFile/ManyEntries.d:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/ZipFile \
12:02:32          -classpath /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/2/java/util/zip/ZipFile/ManyEntries.d:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/ZipFile:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/javatest.jar:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/jtreg.jar \
12:02:32          ManyEntries
12:02:32  STDOUT:
12:02:32  N=1, method=0
12:02:32  STDERR:
12:02:32  java.lang.Exception: getTime=1648911744000, time=1648915344000
12:02:32  	at ManyEntries.test(ManyEntries.java:97)
12:02:32  	at ManyEntries.main(ManyEntries.java:45)
```

java/util/zip/TestExtraTime.java
```
12:02:51  rerun:
12:02:51  cd /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/scratch/0 && \
12:02:51  HOME=/Users/jenkins \
12:02:51  PATH=/bin:/usr/bin:/usr/sbin \
12:02:51      /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image/bin/javac \
12:02:51          -J-ea \
12:02:51          -J-esa \
12:02:51          -J-Xmx1540m \
12:02:51          -J-Xdump:system:none \
12:02:51          -J-Xdump:heap:none \
12:02:51          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
12:02:51          -J-XX:-UseCompressedOops \
12:02:51          -J-Djava.library.path=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
12:02:51          -J-Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops' \
12:02:51          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-UseCompressedOops' \
12:02:51          -J-Dtest.compiler.opts= \
12:02:51          -J-Dtest.java.opts= \
12:02:51          -J-Dtest.jdk=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image \
12:02:51          -J-Dcompile.jdk=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image \
12:02:51          -J-Dtest.timeout.factor=8.0 \
12:02:51          -J-Dtest.nativepath=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
12:02:51          -J-Dtest.root=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk \
12:02:51          -J-Dtest.name=java/util/zip/TestExtraTime.java \
12:02:51          -J-Dtest.file=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/TestExtraTime.java \
12:02:51          -J-Dtest.src=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip \
12:02:51          -J-Dtest.src.path=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip \
12:02:51          -J-Dtest.classes=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d \
12:02:51          -J-Dtest.class.path=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d \
12:02:51          -J-Dtest.class.path.prefix=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip \
12:02:51          -d /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d \
12:02:51          -sourcepath /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip \
12:02:51          -classpath /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/TestExtraTime.java
12:02:51  
12:02:51  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: setTime should make getLastModifiedTime return the specified instant: 1648915370953 got: 1648911770953
12:02:51  REASON: Assumed action based on file name: run main TestExtraTime 
12:02:51  TIME:   0.039 seconds
12:02:51  messages:
12:02:51  command: main TestExtraTime
12:02:51  reason: Assumed action based on file name: run main TestExtraTime 
12:02:51  Mode: agentvm
12:02:51  Agent id: 12
12:02:51  elapsed time (seconds): 0.039
12:02:51  configuration:
12:02:51  Boot Layer
12:02:51    class path: /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/javatest.jar 
12:02:51                /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/jtreg.jar 
12:02:51                /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/junit.jar 
12:02:51                /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/hamcrest.jar 
12:02:51                /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/testng.jar 
12:02:51                /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/jcommander.jar 
12:02:51                /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/guice.jar 
12:02:51    patch:      java.base /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/patches/java.base
12:02:51  
12:02:51  Test Layer
12:02:51    class path: /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d
12:02:51                /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip
12:02:51  
12:02:51  rerun:
12:02:51  cd /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/scratch/0 && \
12:02:51  HOME=/Users/jenkins \
12:02:51  PATH=/bin:/usr/bin:/usr/sbin \
12:02:51      /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image/bin/java \
12:02:51          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops' \
12:02:51          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-UseCompressedOops' \
12:02:51          -Dtest.compiler.opts= \
12:02:51          -Dtest.java.opts= \
12:02:51          -Dtest.jdk=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image \
12:02:51          -Dcompile.jdk=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image \
12:02:51          -Dtest.timeout.factor=8.0 \
12:02:51          -Dtest.nativepath=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
12:02:51          -Dtest.root=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk \
12:02:51          -Dtest.name=java/util/zip/TestExtraTime.java \
12:02:51          -Dtest.file=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip/TestExtraTime.java \
12:02:51          -Dtest.src=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip \
12:02:51          -Dtest.src.path=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip \
12:02:51          -Dtest.classes=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d \
12:02:51          -Dtest.class.path=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d \
12:02:51          -Dtest.class.path.prefix=/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip \
12:02:51          -classpath /Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/TKG/output_16489147597960/jdk_util_1/work/classes/1/java/util/zip/TestExtraTime.d:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/zip:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/javatest.jar:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_aarch64_mac_Release/jvmtest/openjdk/jtreg/lib/jtreg.jar \
12:02:51          TestExtraTime
12:02:51  STDOUT:
12:02:51  --------------------
12:02:51  Testing: [1970-01-01T00:00:00.01Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [1969-09-23T00:00:00Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[2022-04-02T16:07:50.932Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[null]/[2022-04-02T15:57:50.932Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[2022-04-02T16:07:50.932Z]/[2022-04-02T15:57:50.932Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[2022-04-02T16:07:50.932Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[null]/[2022-04-02T15:57:50.932Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.932Z]/[2022-04-02T16:07:50.932Z]/[2022-04-02T15:57:50.932Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[2038-01-19T11:34:07Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[2038-01-19T11:34:07Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[2038-01-19T11:34:07Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[2038-01-19T11:34:07Z]
12:02:51  --------------------
12:02:51  Testing: [1970-01-01T00:00:00.01Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [1969-09-23T00:00:00Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[null]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T15:52:27.592Z]/[2022-04-02T15:57:27.592Z]/[2022-04-02T15:47:27.592Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[2022-04-02T16:07:50.944Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[null]/[2022-04-02T15:57:50.944Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[2022-04-02T16:07:50.944Z]/[2022-04-02T15:57:50.944Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[2022-04-02T16:07:50.944Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[null]/[2022-04-02T15:57:50.944Z]
12:02:51  --------------------
12:02:51  Testing: [2022-04-02T16:02:50.944Z]/[2022-04-02T16:07:50.944Z]/[2022-04-02T15:57:50.944Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[null]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]/[2038-01-19T03:14:08Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[2038-01-19T11:34:07Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[2038-01-19T11:34:07Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[null]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[null]/[2038-01-19T11:34:07Z]
12:02:51  --------------------
12:02:51  Testing: [2038-01-19T03:14:07Z]/[2038-01-19T11:34:07Z]/[2038-01-19T11:34:07Z]
12:02:51  STDERR:
12:02:51  java.lang.RuntimeException: setTime should make getLastModifiedTime return the specified instant: 1648915370953 got: 1648911770953
12:02:51  	at TestExtraTime.testTimeConversions(TestExtraTime.java:266)
12:02:51  	at TestExtraTime.testTimeConversions(TestExtraTime.java:255)
12:02:51  	at TestExtraTime.main(TestExtraTime.java:99)
```

@knn-k

**Comment by knn-k** [comment]
Not reproduced in a 10x Grinder job: job/Grinder/22300

**Comment by pshipton** [comment]
Note the failure occurred in the 0.31 build.

**Comment by knn-k** [comment]
Yes, I used a 0.31 build in my Grinder job.  I needed #14854 for building the 0.31 binary.

**Comment by knn-k** [comment]
Not reproduced in a 20x Grinder job: job/Grinder/22342

**Comment by knn-k** [comment]
This failure was originally reported for JDK 18.
I ran the test on AArch64 macOS with JDK 19 40 times, and got no failures.
https://openj9-jenkins.osuosl.org/job/Grinder/1307/
