### ISSUE TITLE
TestJlmRemoteThreadNoAuth_1 CL2 hang? on aarch64 mac

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14840]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_aarch64_mac_Release_testList_0/7 - [mac11-aarch64-6](https://openj9-jenkins.osuosl.org/computer/mac11-aarch64-6)
TestJlmRemoteThreadNoAuth_1 `-XX:-UseCompressedOops`

Core and javacores's collected:
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.system_aarch64_mac_Release_testList_0/7/system_test_output.tar.gz
```
STF 02:59:17.793 - +------ Step 7 - Wait for processes to complete
STF 02:59:17.793 - | Wait for processes to meet expectations
STF 02:59:17.793 - |   Processes: [LT2, CL2]
STF 02:59:17.793 - |
STF 02:59:17.793 - Monitoring processes: CL2 LT2
CL2 j> 2022/04/03 02:59:18.101 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
CL2 j> 2022/04/03 02:59:18.150 Attempting to connect
CL2 j> 2022/04/03 02:59:18.286 Connection established!
CL2 j> 2022/04/03 02:59:28.611 Writing report data ...
CL2 j> 2022/04/03 02:59:31.426  done.
CL2 j> 2022/04/03 02:59:41.517 Writing report data ...
CL2 j> 2022/04/03 02:59:43.368  done.
CL2 j> 2022/04/03 02:59:53.481 Writing report data ...
CL2 j> 2022/04/03 02:59:55.025  done.
STF 03:00:00.352 - **FAILED** Process CL2 has timed out
STF 03:00:00.352 - Collecting dumps for: CL2
```
CL2.stderr,CL2.stdout - nothing of interest

I don't see much of interest in the first javacore, maybe this
```
3XMTHREADINFO      "JMX client heartbeat 2" J9VMThread:0x00000001210A0700, omrthread_t:0x000000012109A358, java/lang/Thread:0x00000001067BC4A8, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1E, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x2C5C621, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000481)
3XMTHREADINFO2            (native stack address range from:0x00000001782FC000, to:0x000000017833F000, size:0x43000)
3XMCPUTIME               CPU usage total: 0.000025000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.sleep(Native Method)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:1020)
4XESTACKTRACE                at com/sun/jmx/remote/internal/ClientCommunicatorAdmin$Checker.run(ClientCommunicatorAdmin.java:180)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:889)
```

@knn-k fyi

**Comment by pshipton** [comment]
Note the failure occurred on the 0.31 build.

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk18_j9_sanity.system_aarch64_mac_testList_2/30/` (`macaarch64rt2`)
```
[2022-05-09T18:48:39.218Z] STF 14:31:27.045 - +------ Step 9 - Wait for processes to complete
[2022-05-09T18:48:39.219Z] STF 14:31:27.045 - | Wait for processes to meet expectations
[2022-05-09T18:48:39.219Z] STF 14:31:27.045 - |   Processes: [LT2, CL2]
[2022-05-09T18:48:39.219Z] STF 14:31:27.045 - |
[2022-05-09T18:48:39.219Z] STF 14:31:27.045 - Monitoring processes: CL2 LT2
[2022-05-09T18:48:39.219Z] CL2 j> 2022/05/09 14:31:27.405 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
[2022-05-09T18:48:39.219Z] CL2 j> 2022/05/09 14:31:27.449 Attempting to connect
[2022-05-09T18:48:39.219Z] CL2 j> 2022/05/09 14:31:27.522 Monitored VM not ready at May 9, 2022, 2:31:27 PM (attempt 1, elapsed 62ms).
[2022-05-09T18:48:39.219Z] CL2 j> 2022/05/09 14:31:27.523 Waiting 5 secs and trying again...
[2022-05-09T18:48:39.219Z] CL2 j> 2022/05/09 14:31:32.529 Attempting to connect
[2022-05-09T18:48:39.219Z] STF 14:47:19.390 - Heartbeat: Process LT2 is still running
[2022-05-09T18:48:39.219Z] STF 14:47:19.391 - **FAILED** Process CL2 has timed out
[2022-05-09T18:48:39.219Z] STF 14:47:19.392 - Collecting dumps for: CL2
[2022-05-09T18:48:39.219Z] STF 14:47:19.392 - Sending SIG 3 to the java process to generate a javacore
[2022-05-09T18:48:39.219Z] STF 14:47:19.392 - Running command: kill -3 40987
[2022-05-09T18:48:39.219Z] STF 14:47:19.392 - Redirecting stderr to /Users/jenkins/workspace/Test_openjdk18_j9_sanity.system_aarch64_mac_testList_2/aqa-tests/TKG/output_16521167945584/TestIBMJlmRemoteClassAuth_0/20220509-143109-TestIBMJlmRemoteClassAuth/results/8.CL2.kill_3.stderr
[2022-05-09T18:48:39.219Z] STF 14:47:19.392 - Redirecting stdout to /Users/jenkins/workspace/Test_openjdk18_j9_sanity.system_aarch64_mac_testList_2/aqa-tests/TKG/output_16521167945584/TestIBMJlmRemoteClassAuth_0/20220509-143109-TestIBMJlmRemoteClassAuth/results/8.CL2.kill_3.stdout
[2022-05-09T18:48:39.219Z] STF 14:47:19.518 - Pausing for 30 seconds
[2022-05-09T18:48:39.219Z] STF 14:47:49.527 - Process CL2 (pid 40987) is no longer running. Abandoning dump collection.
[2022-05-09T18:48:39.219Z] CL2 j> 2022/05/09 14:47:19.619 Connection established!
[2022-05-09T18:48:39.219Z] CL2 stderr JVMDUMP039I Processing dump event "user", detail "" at 2022/05/09 14:47:19 - please wait.
[2022-05-09T18:48:39.219Z] CL2 stderr JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk18_j9_sanity.system_aarch64_mac_testList_2/aqa-tests/TKG/output_16521167945584/TestIBMJlmRemoteClassAuth_0/20220509-143109-TestIBMJlmRemoteClassAuth/results/javacore.20220509.144719.40987.0001.txt' in response to an event
[2022-05-09T18:48:39.219Z] CL2 stderr JVMDUMP010I Java dump written to /Users/jenkins/workspace/Test_openjdk18_j9_sanity.system_aarch64_mac_testList_2/aqa-tests/TKG/output_16521167945584/TestIBMJlmRemoteClassAuth_0/20220509-143109-TestIBMJlmRemoteClassAuth/results/javacore.20220509.144719.40987.0001.txt
[2022-05-09T18:48:39.219Z] CL2 stderr JVMDUMP013I Processed dump event "user", detail "".
[2022-05-09T18:48:39.219Z] STF 14:47:49.527 - Monitoring Report Summary:
[2022-05-09T18:48:39.219Z] STF 14:47:49.527 -   o Process CL2 has timed out
[2022-05-09T18:48:39.219Z] STF 14:47:49.527 -   o Process LT2 is still running as expected
[2022-05-09T18:48:39.219Z] STF 14:47:49.528 - Killing processes: CL2 LT2
[2022-05-09T18:48:39.219Z] STF 14:47:49.528 -   o Process CL2 pid 40987 is not running
[2022-05-09T18:48:39.219Z] STF 14:47:49.528 -   o Process LT2 pid 40986 stop()
[2022-05-09T18:48:39.219Z] STF 14:47:50.538 -   o Process LT2 pid 40986 killed
[2022-05-09T18:48:39.219Z] **FAILED** at step 9 (Wait for processes to complete). Expected return value=0 Actual=1 at /Users/jenkins/workspace/Test_openjdk18_j9_sanity.system_aarch64_mac_testList_2/aqa-tests/TKG/../TKG/output_16521167945584/TestIBMJlmRemoteClassAuth_0/20220509-143109-TestIBMJlmRemoteClassAuth/execute.pl line 332.
[2022-05-09T18:48:39.220Z] STF 14:47:50.886 - **FAILED** execute script failed. Expected return value=0 Actual=1
[2022-05-09T18:48:39.220Z] STF 14:47:50.886 - 
[2022-05-09T18:48:39.220Z] STF 14:47:50.886 - ====================   T E A R D O W N   ====================
[2022-05-09T18:48:39.220Z] STF 14:47:50.886 - Running teardown: perl /Users/jenkins/workspace/Test_openjdk18_j9_sanity.system_aarch64_mac_testList_2/aqa-tests/TKG/../TKG/output_16521167945584/TestIBMJlmRemoteClassAuth_0/20220509-143109-TestIBMJlmRemoteClassAuth/tearDown.pl
[2022-05-09T18:48:39.220Z] STF 14:47:50.961 - TEARDOWN stage completed
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 - 
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 - =====================   R E S U L T S   =====================
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 - Stage results:
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 -   setUp:     pass
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 -   execute:  *fail*
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 -   teardown:  pass
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 - 
[2022-05-09T18:48:39.220Z] STF 14:47:50.970 - Overall result: **FAILED**
[2022-05-09T18:48:39.220Z] 
[2022-05-09T18:48:39.220Z] TestIBMJlmRemoteClassAuth_0_FAILED
```

**Comment by knn-k** [comment]
I ran TestJlmRemoteThreadNoAuth_1 and TestJlmRemoteClassNoAuth_1 with JDK 19 on AArch64 macOS 40 times each, and got no failures.
- https://openj9-jenkins.osuosl.org/job/Grinder/1303/
- https://openj9-jenkins.osuosl.org/job/Grinder/1304/
