### ISSUE TITLE
jdk_util_0_FAILED java/util/Locale/Bug8154797.java ClassCastException: java.lang.InterruptedException incompatible with java.util.spi.ResourceBundleProvider

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14890]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_testList_1/93/`(`ub18-aarch64-1`):
```
openjdk version "17.0.3" 2022-04-19
IBM Semeru Runtime Open Edition 17.0.3.0-m2 (build 17.0.3+5)
Eclipse OpenJ9 VM 17.0.3.0-m2 (build openj9-0.32.0-m2, JRE 17 Linux aarch64-64-Bit Compressed References 20220407_149 (JIT enabled, AOT enabled)
OpenJ9   - 959fc5030
OMR      - ab24b6666
JCL      - d87211e3dbd based on jdk-17.0.3+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_util_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F149%2Fibm-semeru-open-testimage_aarch64_linux_17.0.3_5_openj9-0.32.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F149%2Fibm-semeru-open-jdk_aarch64_linux_17.0.3_5_openj9-0.32.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F149%2Fibm-semeru-open-debugimage_aarch64_linux_17.0.3_5_openj9-0.32.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F149%2Fibm-semeru-open-jre_aarch64_linux_17.0.3_5_openj9-0.32.0-m2.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;USE_JRE=false&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=v0.32.0-release&amp;OPENJ9_BRANCH=v0.32.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.32.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=166&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;TKG_SHA=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-04-07T19:15:44.001Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2022-04-07T19:15:44.001Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2022-04-07T19:20:25.310Z] TEST: java/util/Locale/Bug8154797.java

[2022-04-07T19:20:25.311Z] STDERR:
[2022-04-07T19:20:25.311Z] java.lang.ClassCastException: java.lang.InterruptedException incompatible with java.util.spi.ResourceBundleProvider
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.Bundles$2.run(Bundles.java:269)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.Bundles$2.run(Bundles.java:265)
[2022-04-07T19:20:25.311Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.Bundles.loadBundleFromProviders(Bundles.java:264)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.Bundles.findBundleOf(Bundles.java:201)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.Bundles.of(Bundles.java:106)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.LocaleData$1.run(LocaleData.java:186)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.LocaleData$1.run(LocaleData.java:183)
[2022-04-07T19:20:25.311Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.LocaleData.getBundle(LocaleData.java:183)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.resources.LocaleData.getDateFormatData(LocaleData.java:146)
[2022-04-07T19:20:25.311Z] 	at java.base/sun.util.locale.provider.LocaleResources.getJavaTimeFormatData(LocaleResources.java:527)
[2022-04-07T19:20:25.311Z] 	at Bug8154797.compareResources(Bug8154797.java:66)
[2022-04-07T19:20:25.311Z] 	at Bug8154797.main(Bug8154797.java:94)
[2022-04-07T19:20:25.311Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-04-07T19:20:25.311Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-04-07T19:20:25.311Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-04-07T19:20:25.311Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-04-07T19:20:25.311Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-04-07T19:20:25.311Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-04-07T19:20:25.311Z] 
[2022-04-07T19:20:25.311Z] JavaTest Message: Test threw exception: java.lang.ClassCastException
[2022-04-07T19:20:25.311Z] JavaTest Message: shutting down test
[2022-04-07T19:20:25.312Z] 
[2022-04-07T19:20:25.312Z] 
[2022-04-07T19:20:25.312Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.ClassCastException: java.lang.InterruptedException incompatible with java.util.spi.ResourceBundleProvider
[2022-04-07T19:20:25.312Z] --------------------------------------------------
[2022-04-07T19:37:51.335Z] Test results: passed: 889; failed: 1
[2022-04-07T19:37:59.879Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_testList_1/jvmtest/openjdk/report/html/report.html
[2022-04-07T19:37:59.879Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_16493577145969/jdk_util_0/work
[2022-04-07T19:37:59.879Z] Error: Some tests failed or other problems occurred.
[2022-04-07T19:37:59.879Z] 
[2022-04-07T19:37:59.879Z] jdk_util_0_FAILED
```
50x grinder - `job/Grinder/22474/`

**Comment by pshipton** [comment]
@knn-k fyi

**Comment by pshipton** [comment]
The grinder passed.

**Comment by knn-k** [comment]
We haven't seen this failure for a while.
I ran this test 40 times on AArch64 Linux with JDK 17, and got no failures. https://openj9-jenkins.osuosl.org/job/Grinder/1302/
