### ISSUE TITLE
jdk_nio_1_FAILED java/nio/file/Files/probeContentType/Basic.java got content type: text/plain; expected: [text/javascript, application/javascript]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14958]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/55/`(`win16x64rt3-9`):
```
java version "17.0.3" 2022-04-19
IBM Semeru Runtime Certified Edition 17.0.3.0-rc1 (build 17.0.3+7)
Eclipse OpenJ9 VM 17.0.3.0-rc1 (build openj9-0.32.0-rc1, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20220422_130 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0e919023eb9 based on jdk-17.0.3+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_nio_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F130%2Fibm-semeru-certified-jre_x64_windows_17.0.3.0-rc1.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F130%2Fibm-semeru-certified-jdk_x64_windows_17.0.3.0-rc1.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F130%2Fibm-semeru-certified-debugimage_x64_windows_17.0.3.0-rc1.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F130%2Fibm-semeru-certified-testimage_x64_windows_17.0.3.0-rc1.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=v0.32.0-release&amp;OPENJ9_BRANCH=v0.32.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.32.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-04-22T06:44:14.662Z] variation: Mode650
[2022-04-22T06:44:15.057Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-04-22T06:55:09.607Z] TEST: java/nio/file/Files/probeContentType/Basic.java

[2022-04-22T06:55:09.608Z] STDERR:
[2022-04-22T06:55:09.608Z] For extension js we got content type: text/plain; expected: [text/javascript, application/javascript]
[2022-04-22T06:55:09.608Z] java.lang.RuntimeException: Test failed!
[2022-04-22T06:55:09.608Z] 	at Basic.main(Basic.java:192)
[2022-04-22T06:55:09.608Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-04-22T06:55:09.608Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-04-22T06:55:09.609Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-04-22T06:55:09.609Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-04-22T06:55:09.609Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-04-22T06:55:09.609Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-04-22T06:55:09.609Z] 
[2022-04-22T06:55:09.609Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed!

[2022-04-22T07:13:55.102Z] jdk_nio_1_FAILED
```
50x grinder - job/Grinder/23044/

**Comment by JasonFengJ9** [comment]
> 50x grinder - job/Grinder/23044/

all failed

**Comment by pshipton** [comment]
@JasonFengJ9 did this test used to pass?

**Comment by JasonFengJ9** [comment]
> did this test used to pass?

it is a regression between `job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/54` (April 21st) and `job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/55` (April 22nd). 
Note `jdk_nio_1` only passed twice, another pass was `job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/53` (April 16th), before that, it usually failed w/ `SocketException: Invalid argument: no further information`.

**Comment by pshipton** [comment]
It's weird we could get a test difference between builds when none of the SHAs changed. @llxia any ideas?

Build 54 shas:
```
  Fetch URL: https://github.com/adoptium/aqa-tests.git
sha: 8c684378d73d20d1a2d746ebd68294d42eb633a7
================================================
  Fetch URL: https://github.com/adoptium/TKG.git
sha: 90e11f674f0e6be78e1497a06e36d1a69340e776
================================================
  Fetch URL: https://github.com/eclipse-openj9/openj9.git
sha: 9a84ec34ed321967cdbe67b29ddcd732b591d051
================================================
  Fetch URL: https://github.com/ibmruntimes/openj9-openjdk-jdk17.git
sha: dc07fd49b926c28c33b17053b11ad3121429239f
```
Build 55 shas:
```
  Fetch URL: https://github.com/adoptium/aqa-tests.git
sha: 8c684378d73d20d1a2d746ebd68294d42eb633a7
================================================
  Fetch URL: https://github.com/adoptium/TKG.git
sha: 90e11f674f0e6be78e1497a06e36d1a69340e776
================================================
  Fetch URL: https://github.com/eclipse-openj9/openj9.git
sha: 9a84ec34ed321967cdbe67b29ddcd732b591d051
================================================
  Fetch URL: https://github.com/ibmruntimes/openj9-openjdk-jdk17.git
sha: dc07fd49b926c28c33b17053b11ad3121429239f
```

Seems grinders don't have a SHA.txt, but Grinder/23118 shas:
```
09:45:19    Fetch URL: https://github.com/adoptium/aqa-tests.git
09:45:19  sha: 26bb43d5084286ee4822aa218c92a0879d6de44d
09:45:20  ================================================
09:45:20    Fetch URL: https://github.com/adoptium/TKG.git
09:45:20  sha: 90e11f674f0e6be78e1497a06e36d1a69340e776
09:46:21  ================================================
09:46:21    Fetch URL: https://github.com/eclipse-openj9/openj9.git
09:46:21  sha: 9a84ec34ed321967cdbe67b29ddcd732b591d051
09:57:46       [exec] ================================================
09:57:46       [exec]   Fetch URL: https://github.com/ibmruntimes/openj9-openjdk-jdk17.git
09:57:46       [exec] sha: dc07fd49b926c28c33b17053b11ad3121429239f
```

**Comment by pshipton** [comment]
build 54 - win16x64rt-1-6
build 55 - win16x64rt3-9
Grinder/23118: win16x64rt-1-5, win16x64rt-1-9, win16x64rt2-8, win16x64rt3-3, win16x64rt3-10

**Comment by pshipton** [comment]
It's excluded for 18. If we are excluding for 11 then 17 should also be excluded.
@llxia will you take care of this, or should Jason or I or create a PR?
