### ISSUE TITLE
Adopt_J9_FeatureTests_0_FAILED vmPropertiesPointToVendor - AssertionError: expected [https://github.com/ibmruntimes/Semeru-Runtimes/issues] but found [null]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14952]
Failure link
------------

From an internal build `job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9_SmokeTests/82/`:
```
openjdk version "1.8.0_332"
IBM Semeru Runtime Open Edition (build 1.8.0_332-b09)
Eclipse OpenJ9 VM (build openj9-0.32.0-rc1, JRE 1.8.0 Windows Server 2016 amd64-64-Bit Compressed References 20220421_374 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0b8b8af39a based on jdk8u332-b09)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=Adopt_J9_FeatureTests_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=%2Ftest%2Ffunctional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Ftemurin-build&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=ibm&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x64-openj9&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;BUILD_LIST=functional%2FbuildAndPackage&amp;UPSTREAM_JOB_NUMBER=374&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-04-21T04:45:28.342Z] FAILED: vmPropertiesPointToVendor
[2022-04-21T04:45:28.342Z] java.lang.AssertionError: expected [https://github.com/ibmruntimes/Semeru-Runtimes/issues] but found [null]
[2022-04-21T04:45:28.342Z] 	at org.testng.Assert.fail(Assert.java:96)
[2022-04-21T04:45:28.342Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2022-04-21T04:45:28.342Z] 	at org.testng.Assert.assertEqualsImpl(Assert.java:132)
[2022-04-21T04:45:28.342Z] 	at org.testng.Assert.assertEquals(Assert.java:118)
[2022-04-21T04:45:28.342Z] 	at org.testng.Assert.assertEquals(Assert.java:453)
[2022-04-21T04:45:28.342Z] 	at org.testng.Assert.assertEquals(Assert.java:463)
[2022-04-21T04:45:28.342Z] 	at net.adoptium.test.VendorPropertiesTest$SemeruPropertiesChecks.javaVendorUrlBug(VendorPropertiesTest.java:244)
[2022-04-21T04:45:28.342Z] 	at net.adoptium.test.VendorPropertiesTest.vmPropertiesPointToVendor(VendorPropertiesTest.java:105)
[2022-04-21T04:45:28.342Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-04-21T04:45:28.342Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-04-21T04:45:28.342Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-04-21T04:45:28.342Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-04-21T04:45:28.342Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2022-04-21T04:45:28.342Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2022-04-21T04:45:28.342Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2022-04-21T04:45:28.342Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2022-04-21T04:45:28.342Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2022-04-21T04:45:28.342Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2022-04-21T04:45:28.342Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2022-04-21T04:45:28.342Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2022-04-21T04:45:28.342Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2022-04-21T04:45:28.342Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2022-04-21T04:45:28.342Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2022-04-21T04:45:28.342Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2022-04-21T04:45:28.342Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2022-04-21T04:45:28.342Z] 
[2022-04-21T04:45:28.342Z] 
[2022-04-21T04:45:28.342Z] ===============================================
[2022-04-21T04:45:28.342Z]     CommonFeatureTests
[2022-04-21T04:45:28.342Z]     Tests run: 3, Failures: 1, Skips: 0
[2022-04-21T04:45:28.342Z] ===============================================

[2022-04-21T04:45:28.342Z] Adopt_J9_FeatureTests_0_FAILED
```

**Comment by pshipton** [comment]
I see Hotspot sets java.vendor.url.bug in jdk8 native code but OpenJ9 doesn't have any code to set it. This is nothing new.

**Comment by LongyuZhang** [comment]
Smoke tests have passed, I think we can close this issue, thanks.
http://trss1.fyre.ibm.com/resultSummary?parentId=62ad3b86eff02dba81fc9141
http://trss1.fyre.ibm.com/resultSummary?parentId=62ad25c5eff02dba81fc54ff
http://trss1.fyre.ibm.com/resultSummary?parentId=62ade335eff02dba81ffde85
