### ISSUE TITLE
openj9-0.32.0-m2 Linux x64 regression: No LoginModule found for com.ibm.security.auth.module.LinuxLoginModule

### ISSUE THREAD

**Issue by avermeer** [eclipse-openj9/openj9#14950]
Hello,

I just found that using milestone 2 build of IBM Semeru openj9-0.32.0-m2 Linux x64, I have a probe testing Hadoop connectity always failing with the following stack trace:

```
2022-04-21 09:43:46,761 [main] ERROR c.d.i.m.c.s.g.HadoopAccessProbe - Hadoop Connection failed
java.io.IOException: failure to login
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:824)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:761)
        at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:634)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2828)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2818)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2684)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at com.acme.infra.monitoring.cloud.storm.generic.HadoopAccessProbe.pull(HadoopAccessProbe.java:94)
        at com.acme.infra.monitoring.proxy.MonitoringPullSourceUnplugger.main(MonitoringPullSourceUnplugger.java:641)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.acme.enosysteminfra.enosysjarstarter.JarStarter.<init>(JarStarter.java:167)
        at com.acme.enosysteminfra.enosysjarstarter.JarStarter.main(JarStarter.java:23)
Caused by: javax.security.auth.login.LoginException: No LoginModule found for com.ibm.security.auth.module.LinuxLoginModule
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:731)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:783)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:799)
        ... 14 common frames omitted
```
        
     
I made a quick search and found that similar [issue#12151](https://github.com/eclipse-openj9/openj9/issues/12151) on January 2022 release, which was closed as being an "internal build issue"

I'm afraid it's a showstopper, don't you think?

Thanks,
Alex

**Comment by DanHeidinga** [comment]
>  milestone 2 build of IBM Semeru openj9-0.32.0-m2 Linux x64

@avermeer  Is that Java 8, 11 or 17?  Full `java -version` output would help here.

There appears to be some some Hadoop changes in 2020 that may be related:
https://issues.apache.org/jira/browse/HADOOP-16590
https://github.com/apache/hadoop/pull/1484

I'll defer to the IBMers as this appears to be in IBM-specific security providers?  fyi @pshipton @mstoodle

**Comment by avermeer** [comment]
@DanHeidinga here's the  java -version output for this case:

```
$ ./jdk-11.0.15+8/bin/java -version
openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0-m2 (build 11.0.15+8)
Eclipse OpenJ9 VM 11.0.15.0-m2 (build openj9-0.32.0-m2, JRE 11 Linux amd64-64-Bit Compressed References 20220405_414 (JIT enabled, AOT enabled)
OpenJ9   - 959fc5030
OMR      - ab24b6666
JCL      - f84454d938 based on jdk-11.0.15+8)
```

**Comment by pshipton** [comment]
@avermeer can you try this workaround pls.

`-javaagent:setvendor.zip`

[setvendor.zip](https://github.com/eclipse-openj9/openj9/files/8535309/setvendor.zip)

**Comment by avermeer** [comment]
Hello @pshipton 

Your proposed workaround works.
Is there a way we could "patch" a IBM Semeru installation to make the agent "loaded by default", i.e., so that we wouldn't have to tweak all startup shells of Java commands that need this tweak ?

Kind regards,
Alex

**Comment by pshipton** [comment]
You can set the option via the OPENJ9_JAVA_OPTIONS environment variable, or add it to the lib/options.default file in the JVM.
https://www.eclipse.org/openj9/docs/env_var/

**Comment by avermeer** [comment]
@pshipton thank you very much. I tested the solution based on OPENJ9_JAVA_OPTIONS environment variable (it works well), but since my preferred one was to modify <jdk install path>/lib/options.default file it took me a a while to realize that instead of inserting -javaagent:<path>/setvendor.zip inside the existing quoted option (which failed) I had to append a line with:
 -javaagent:<path>/setvendor.zip into that file.
 
 This modification of lib/options.default is definitely the best fit for me, since it avoid chasing countless of startup shells where the vendor issue can occur.
 
  Of course long term fix for me is to get upgrade Hadoop dependencies (or remove Hadoop dependencies, but that's another story)

I think this ticket can be closed.

**Comment by KWierchomska** [comment]
What is the proper way to set vendor through OPENJ9_JAVA_OPTIONS in dockerfile?

**Comment by guizsantos** [comment]
> @avermeer can you try this workaround pls.
> 
> `-javaagent:setvendor.zip`
> 
> [setvendor.zip](https://github.com/eclipse-openj9/openj9/files/8535309/setvendor.zip)

@pshipton Can you provide details on how to compile this ZIP file? I am trying this workaround with Java 8 but I am facing this exception: 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 55.0 of class=SetVendor, the maximum supported major version is 52.0; offset=6
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
        at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
        at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
        at java.security.AccessController.doPrivileged(AccessController.java:782)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:902)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:885)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:319)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:416)

Fatal error: processing of -javaagent failed
```
 which sounds right to me considering you compiled that for Java 11.

**Comment by pshipton** [comment]
@guizsantos I've recompiled for Java 8.

[setvendor8.zip](https://github.com/eclipse-openj9/openj9/files/12215185/setvendor8.zip)
