### ISSUE TITLE
OpenJDK util/stream/CollectorToUnmodListTest.java javac NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14964]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/46
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorToUnmodListTest.java

```
01:03:51  rerun:
01:03:51  cd /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/TKG/output_16506861618573/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorToUnmodListTest && \
01:03:51  DISPLAY=:0 \
01:03:51  HOME=/home/jenkins \
01:03:51  LANG=en_US.UTF-8 \
01:03:51  PATH=/bin:/usr/bin:/usr/sbin \
01:03:51      /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/bin/javac \
01:03:51          -J-ea \
01:03:51          -J-esa \
01:03:51          -J-Xmx1540m \
01:03:51          -J-Xdump:system:none \
01:03:51          -J-Xdump:heap:none \
01:03:51          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
01:03:51          -J-XX:+UseCompressedOops \
01:03:51          -J-Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
01:03:51          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
01:03:51          -J-Dtest.compiler.opts= \
01:03:51          -J-Dtest.java.opts= \
01:03:51          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/j2sdk-image \
01:03:51          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/j2sdk-image \
01:03:51          -J-Dtest.timeout.factor=8.0 \
01:03:51          -J-Dtest.nativepath=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
01:03:51          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
01:03:51          -J-Dtest.name=java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorToUnmodListTest.java \
01:03:51          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorToUnmodListTest.java \
01:03:51          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/stream/test \
01:03:51          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/stream/test \
01:03:51          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/TKG/output_16506861618573/jdk_util_0/work/classes/1/java/util/stream/test \
01:03:51          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/TKG/output_16506861618573/jdk_util_0/work/classes/1/java/util/stream/test \
01:03:51          -J-Dtest.modules=jdk.incubator.foreign \
01:03:51          -J-Dtest.patch.path=/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/TKG/output_16506861618573/jdk_util_0/work/classes/1/lib/testlibrary/bootlib \
01:03:51          @/home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/TKG/output_16506861618573/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorToUnmodListTest.d/compile.0.jta
01:03:51  STDOUT:
01:03:51  STDERR:
01:03:51  warning: using incubating module(s): jdk.incubator.foreign
01:03:51  Note: /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorsTest.java uses or overrides a deprecated API.
01:03:51  Note: Recompile with -Xlint:deprecation for details.
01:03:51  Note: /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorsTest.java uses unchecked or unsafe operations.
01:03:51  Note: Recompile with -Xlint:unchecked for details.
01:03:51  1 warning
01:03:51  An exception has occurred in the compiler (18.0.1-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com/) after checking the Bug Database (http://bugs.java.com/) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
01:03:51  java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1458)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1797)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitExec(TreeScanner.java:219)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1584)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitBlock(Flow.java:1207)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitMethodDef(Flow.java:1173)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:921)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitClassDef(Flow.java:1136)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:819)
01:03:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1551)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1541)
01:03:51  	at jdk.compiler/com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:222)
01:03:51  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1377)
01:03:51  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1351)
01:03:51  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
01:03:51  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
01:03:51  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
01:03:51  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
01:03:51  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
01:03:51  printing javac parameters to: /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_x86-64_linux_Nightly/aqa-tests/TKG/output_16506861618573/jdk_util_0/work/java/util/stream/test/org/openjdk/tests/java/util/stream/CollectorToUnmodListTest/javac.20220423_010349.args
01:03:51  
01:03:51  TEST RESULT: Error. compiler crashed (exit code 4)
01:03:51  --------------------------------------------------
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/429
jdk_stream_1 
java/util/stream/test/org/openjdk/tests/java/lang/invoke/DeserializeMethodTest.java
```
15:22:33  java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1439)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1797)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitExec(TreeScanner.java:219)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1584)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitBlock(Flow.java:1188)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitMethodDef(Flow.java:1154)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:921)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitClassDef(Flow.java:1117)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:819)
15:22:33  	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1532)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1522)
15:22:33  	at jdk.compiler/com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:222)
15:22:33  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1380)
15:22:33  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1354)
15:22:33  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
15:22:33  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
15:22:33  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
15:22:33  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
15:22:33  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```
