### ISSUE TITLE
[JDK8 OJDK-MH] MHIllegalAccess failures

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14986]
The below failure(s) is(are) only seen when OJDK MHs are enabled in OpenJ9.

### Errors

```
01:06:16  FAIL: Exception from MethodHandle invocation not wrapped in BootstrapMethodError java.lang.IllegalAccessError: Class Invoker illegally accessing "private" member of class MethodSupplier
01:06:16  java.lang.reflect.InvocationTargetException
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at InvokeSeveralWays.test(InvokeSeveralWays.java:36)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at MHIllegalAccess.testOneError(MHIllegalAccess.java:113)
01:06:16  	at MHIllegalAccess.main(MHIllegalAccess.java:81)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:06:16  	at java.lang.Thread.run(Thread.java:821)
01:06:16  Caused by: java.lang.IllegalAccessError: Class Invoker illegally accessing "private" member of class MethodSupplier
01:06:16  	at java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
01:06:16  	at java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:291)
01:06:16  	at java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:119)
01:06:16  	at Invoker.invoke(Invoker.java:31)
01:06:16  	... 17 more
01:06:16  
01:06:16  EXPECTED: java.lang.IllegalAccessError, java.lang.IllegalAccessError: Class Invoker illegally accessing "private" member of class MethodSupplier
01:06:16  
01:06:16  FAIL: Exception from MethodHandle invocation not wrapped in BootstrapMethodError java.lang.IllegalAccessError: Class Invoker illegally accessing "private" member of class MethodSupplier
01:06:16  java.lang.IllegalAccessError: Class Invoker illegally accessing "private" member of class MethodSupplier
01:06:16  	at java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
01:06:16  	at java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:291)
01:06:16  	at java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:119)
01:06:16  	at Invoker.invoke(Invoker.java:31)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at InvokeSeveralWays.test(InvokeSeveralWays.java:36)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at MHIllegalAccess.testOneError(MHIllegalAccess.java:113)
01:06:16  	at MHIllegalAccess.main(MHIllegalAccess.java:81)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:06:16  	at java.lang.Thread.run(Thread.java:821)
01:06:16  
01:06:16  EXPECTED: java.lang.IllegalAccessError, java.lang.IllegalAccessError: Class Invoker illegally accessing "private" member of class MethodSupplier
01:06:16  
01:06:16  Saw 2 failures
01:06:16  FAIL: Exception from MethodHandle invocation not wrapped in BootstrapMethodError java.lang.NoSuchMethodError: MethodSupplier.m()V (loaded from <Unknown> by BogoLoader@b14c28f2) called from class Invoker (loaded from <Unknown> by BogoLoader@b14c28f2).
01:06:16  java.lang.reflect.InvocationTargetException
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at InvokeSeveralWays.test(InvokeSeveralWays.java:36)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at MHIllegalAccess.testOneError(MHIllegalAccess.java:113)
01:06:16  	at MHIllegalAccess.main(MHIllegalAccess.java:82)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:06:16  	at java.lang.Thread.run(Thread.java:821)
01:06:16  Caused by: java.lang.NoSuchMethodError: MethodSupplier.m()V (loaded from <Unknown> by BogoLoader@b14c28f2) called from class Invoker (loaded from <Unknown> by BogoLoader@b14c28f2).
01:06:16  	at java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
01:06:16  	at java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:291)
01:06:16  	at java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:119)
01:06:16  	at Invoker.invoke(Invoker.java:31)
01:06:16  	... 17 more
01:06:16  
01:06:16  EXPECTED: java.lang.NoSuchMethodError, java.lang.NoSuchMethodError: MethodSupplier.m()V (loaded from <Unknown> by BogoLoader@b14c28f2) called from class Invoker (loaded from <Unknown> by BogoLoader@b14c28f2).
01:06:16  
01:06:16  FAIL: Exception from MethodHandle invocation not wrapped in BootstrapMethodError java.lang.NoSuchMethodError: MethodSupplier.m()V (loaded from <Unknown> by BogoLoader@b14c28f2) called from class Invoker (loaded from <Unknown> by BogoLoader@b14c28f2).
01:06:16  java.lang.NoSuchMethodError: MethodSupplier.m()V (loaded from <Unknown> by BogoLoader@b14c28f2) called from class Invoker (loaded from <Unknown> by BogoLoader@b14c28f2).
01:06:16  	at java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
01:06:16  	at java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:291)
01:06:16  	at java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:119)
01:06:16  	at Invoker.invoke(Invoker.java:31)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at InvokeSeveralWays.test(InvokeSeveralWays.java:36)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at MHIllegalAccess.testOneError(MHIllegalAccess.java:113)
01:06:16  	at MHIllegalAccess.main(MHIllegalAccess.java:82)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:06:16  	at java.lang.Thread.run(Thread.java:821)
01:06:16  
01:06:16  EXPECTED: java.lang.NoSuchMethodError, java.lang.NoSuchMethodError: MethodSupplier.m()V (loaded from <Unknown> by BogoLoader@b14c28f2) called from class Invoker (loaded from <Unknown> by BogoLoader@b14c28f2).
01:06:16  
01:06:16  Saw 2 failures
01:06:16  Saw 4 failures, see standard out for details
01:06:16  STDERR:
01:06:16  java.lang.Error: FAIL test
01:06:16  	at MHIllegalAccess.main(MHIllegalAccess.java:85)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:06:16  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:06:16  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:06:16  	at java.lang.reflect.Method.invoke(Method.java:498)
01:06:16  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:06:16  	at java.lang.Thread.run(Thread.java:821)
```

### Failing Test Targets

- `BUILD_LIST=openjdk`
    - [java/lang/invoke/8022701/MHIllegalAccess.java](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/test/java/lang/invoke/8022701/MHIllegalAccess.java)

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK8 with OJDK MHs enabled

Refer to https://github.com/eclipse-openj9/openj9/issues/14541.

**Comment by babsingh** [comment]
In the above failures, the exception is being thrown during resolution. These exceptions need to be wrapped with `BootstrapMethodError` and thrown during invoke not resolve.

In OpenJ9 MHs, we do the following to achieve the above:
https://github.com/eclipse-openj9/openj9/blob/0bb7ce2d462d2e2eef102cfeda33ebc774048ec5/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandleResolver.java#L348-L358

In OJDK MHs, we defer the default conflict exception until MH.invoke: https://github.com/eclipse-openj9/openj9/pull/12668. This needs to be expanded to other exceptions.
