### ISSUE TITLE
[JDK8 OJDK-MH] test_CallSiteNullErrorRethrown fails

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14990]
The below failure(s) is(are) only seen when OJDK MHs are enabled in OpenJ9.

### Errors

```
FAILED: test_CallSiteNullErrorRethrown
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at com.ibm.j9.jsr292.indyn.IndyTest.test_CallSiteNullErrorRethrown(IndyTest.java:389)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

### Failing Test Targets

- `BUILD_LIST=functional`
    - `jsr292_InDynTest_0`
    - `jsr292_InDynTest_1`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK8 with OJDK MHs enabled

Refer to https://github.com/eclipse-openj9/openj9/issues/14541.

**Comment by babsingh** [comment]
**TODO:** Check RI behaviour for the failing test. The test may not be checking the correct behaviour.

**Comment by ThanHenderson** [comment]
Here is the test case:
```
	// test that if resolved CallSite is null, the same error is rethrown
	public void test_CallSiteNullErrorRethrown () {
		/* The bootstrap method associated with the indy call in test_CallSiteNullErrorRethrown
		 * will return null the first time its called, and a valid CallSite for all repeat calls.
		 */

		// Java 8: NullPointerException is expected on the first run
		// Java 11: BootstrapMethodError is expected on the first run
		try {
			com.ibm.j9.jsr292.indyn.GenIndyn.test_CallSiteNullErrorRethrown();
			Assert.fail("BootstrapMethodError or NullPointerException should be thrown.");
		} catch(BootstrapMethodError e) {
			Assert.assertTrue(VersionCheck.major() >= 11);
		} catch (NullPointerException e) {
			Assert.assertTrue(VersionCheck.major() == 8); <------------------------ Marker 1
		}

		// Java 8: CallSite resolution is expected to succeed
		// Java 11: The same BSME is expected on the second run
		try {
			com.ibm.j9.jsr292.indyn.GenIndyn.test_CallSiteNullErrorRethrown();
			Assert.assertTrue(VersionCheck.major() == 8); <------------------------ Marker 2
		} catch ( java.lang.BootstrapMethodError e ) {
			Assert.assertTrue(VersionCheck.major() >= 11); <----------------------- Marker 3	
		}
	}
```

Marker 1: `NullPointerException` is not thrown for the RI nor in the current OJDK MHs support for JDK 8, hence the failure.

Marker 2: If we disable Marker 1, the RI passes by hitting Marker 2.

Marker 3: If we disable Marker 1, the current OJDK MHs support for JDK 8 behaves exactly like JDK 11+ and throws another `BootstrapMethodError`. It is unclear exactly what we are to expect here.
