### ISSUE TITLE
[JDK8 OJDK-MH] test_indyn_invalid_bootstrap_method fails

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14991]
The below failure(s) is(are) only seen when OJDK MHs are enabled in OpenJ9.

### Errors

```
FAILED: test_indyn_invalid_bootstrap_method
java.lang.AssertionError: [Java 8] BootstrapMethodError not thrown when invalid bootstrap method is used 
	at org.testng.Assert.fail(Assert.java:85)
	at com.ibm.j9.jsr292.indyn.IndyTest.test_indyn_invalid_bootstrap_method(IndyTest.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.NoSuchMethodError: com/ibm/j9/jsr292/indyn/BootstrapMethods.method_must_not_exist(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (loaded from file:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/jvmtest/functional/Jsr292/jsr292test.jar by sun.misc.Launcher$AppClassLoader@d8a42ecb) called from class com.ibm.j9.jsr292.indyn.GenIndyn (loaded from file:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/jvmtest/functional/Jsr292/jsr292test.jar by sun.misc.Launcher$AppClassLoader@d8a42ecb).
	at java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
	at java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:109)
	at com.ibm.j9.jsr292.indyn.GenIndyn.invalid_bootstrap(Unknown Source)
	at com.ibm.j9.jsr292.indyn.IndyTest.test_indyn_invalid_bootstrap_method(IndyTest.java:217)
	... 24 more
```

### Failing Test Targets

- `BUILD_LIST=functional`
    - `jsr292_InDynTest_0`
    - `jsr292_InDynTest_1`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK8 with OJDK MHs enabled

Refer to https://github.com/eclipse-openj9/openj9/issues/14541.

**Comment by babsingh** [comment]
**TBC:** This failure looks identical to the failures reported in https://github.com/eclipse-openj9/openj9/issues/14986. If identical, the potential solution will be https://github.com/eclipse-openj9/openj9/issues/14986#issuecomment-1115016094.

**Comment by ThanHenderson** [comment]
> TBC: This failure looks identical to the failures reported in https://github.com/eclipse-openj9/openj9/issues/14986. If identical, the potential solution will be https://github.com/eclipse-openj9/openj9/issues/14986#issuecomment-1115016094.

I'm not sure if this is the case; the test also fails on the RI. So the test itself may not be correct.

**Comment by babsingh** [comment]
Fixed by https://github.com/eclipse-openj9/openj9/pull/18445.
