### ISSUE TITLE
jdk_util_1_FAILED java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java RuntimeException: getBundle("UnreadableRB") doesn't throw class java.io.IOException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15005]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_1/107/`(`win10x64vs6`):
```
java version "17.0.3-beta" 2022-04-19
IBM Semeru Runtime Certified Edition 17.0.3+7-202205040406 (build 17.0.3-beta+7-202205040406)
Eclipse OpenJ9 VM 17.0.3+7-202205040406 (build master-3549e2444, JRE 17 Windows 10 amd64-64-Bit Compressed References 20220504_141 (JIT enabled, AOT enabled)
OpenJ9   - 3549e2444
OMR      - 81b79405d
JCL      - 793514473 based on jdk-17.0.3+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_util_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_x86-64_windows&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F141%2Fibm-semeru-certified-jdk_x64_windows_JDK17U_2022-05-04-03-59.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F141%2Fibm-semeru-certified-jre_x64_windows_JDK17U_2022-05-04-03-59.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F141%2Fibm-semeru-certified-testimage_x64_windows_JDK17U_2022-05-04-03-59.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F141%2Fibm-semeru-certified-debugimage_x64_windows_JDK17U_2022-05-04-03-59.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=177&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-05-04T06:12:57.071Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-05-04T06:12:57.071Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-05-04T06:18:32.847Z] TEST: java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java

[2022-05-04T06:18:32.853Z] Exception in thread "main" java.lang.RuntimeException: getBundle("UnreadableRB") doesn't throw class java.io.IOException
[2022-05-04T06:18:32.853Z] 	at MissingResourceCauseTest.callGetBundle(MissingResourceCauseTest.java:51)
[2022-05-04T06:18:32.853Z] 	at MissingResourceCauseTest.callGetBundle(MissingResourceCauseTest.java:43)
[2022-05-04T06:18:32.853Z] 	at MissingResourceCauseTest.main(MissingResourceCauseTest.java:37)

[2022-05-04T06:18:32.853Z] STDERR:
[2022-05-04T06:18:32.853Z] java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
[2022-05-04T06:18:32.853Z] 	at MissingResourceCauseTestRun.runCmd(MissingResourceCauseTestRun.java:97)
[2022-05-04T06:18:32.853Z] 	at MissingResourceCauseTestRun.main(MissingResourceCauseTestRun.java:60)
[2022-05-04T06:18:32.853Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-04T06:18:32.853Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-05-04T06:18:32.853Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-04T06:18:32.853Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-05-04T06:18:32.853Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-05-04T06:18:32.853Z] 	at java.base/java.lang.Thread.run(Thread.java:853)
[2022-05-04T06:18:32.853Z] 
[2022-05-04T06:18:32.853Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

[2022-05-04T06:18:32.853Z] --------------------------------------------------
[2022-05-04T06:23:19.260Z] Test results: passed: 892; failed: 1
[2022-05-04T06:23:37.347Z] 
[2022-05-04T06:23:37.347Z] jdk_util_1_FAILED
```
50x grinder - `job/Grinder/23472/`

**Comment by JasonFengJ9** [comment]
[An internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_testList_1/74/)(`win10x64vs6`)
```
openjdk version "18.0.2" 2022-07-19
IBM Semeru Runtime Open Edition 18.0.2.0 (build 18.0.2+9)
Eclipse OpenJ9 VM 18.0.2.0 (build openj9-0.33.0, JRE 18 Windows 10 amd64-64-Bit Compressed References 20220804_32 (JIT enabled, AOT enabled)
OpenJ9   - 04a55b45b
OMR      - b58aa2708
JCL      - dff9c97e1c7 based on jdk-18.0.2+9)

[2022-08-04T22:04:54.641Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2022-08-04T22:04:54.641Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2022-08-04T22:11:01.838Z] TEST: java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java

[2022-08-04T22:11:01.843Z] STDERR:
[2022-08-04T22:11:01.843Z] java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
[2022-08-04T22:11:01.843Z] 	at MissingResourceCauseTestRun.runCmd(MissingResourceCauseTestRun.java:97)
[2022-08-04T22:11:01.843Z] 	at MissingResourceCauseTestRun.main(MissingResourceCauseTestRun.java:60)
[2022-08-04T22:11:01.843Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-08-04T22:11:01.843Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-08-04T22:11:01.843Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-08-04T22:11:01.843Z] 	at java.base/java.lang.Thread.run(Thread.java:858)
[2022-08-04T22:11:01.843Z] 
[2022-08-04T22:11:01.843Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-08-04T22:11:01.843Z] JavaTest Message: shutting down test
[2022-08-04T22:11:01.843Z] 
[2022-08-04T22:11:01.843Z] 
[2022-08-04T22:11:01.843Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
[2022-08-04T22:11:01.843Z] --------------------------------------------------
[2022-08-04T22:15:58.491Z] Test results: passed: 901; failed: 1
[2022-08-04T22:16:06.756Z] Report written to C:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_testList_1\jvmtest\openjdk\report\html\report.html
[2022-08-04T22:16:06.756Z] Results written to C:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_testList_1\aqa-tests\TKG\output_1659649630513\jdk_util_0\work
[2022-08-04T22:16:06.756Z] Error: Some tests failed or other problems occurred.
[2022-08-04T22:16:06.756Z] 
[2022-08-04T22:16:06.756Z] jdk_util_0_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26554/)

**Comment by pshipton** [comment]
The grinder is failing every time on [win10x64vs6.rtp.raleigh.ibm.com](https://hyc-runtimes-jenkins.swg-devops.com/computer/win10x64vs6.rtp.raleigh.ibm.com)
and hasn't found any other machines to run on yet. This is the same machine that failed previously, which suggests it's a machine problem.

**Comment by pshipton** [comment]
Passed on the other machines used: win16x64rt-1-8, win16x64rt2-3, win16x64cudart1

**Comment by pshipton** [comment]
[Another one](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_1/166/) same failure on the same machine, win10x64vs6. Seems this is the only Windows 10 machine. 

```
23:17:59  Command line: [chmod 000 UnreadableRB.properties]
23:17:59  [2022-08-18T03:17:46.914147100Z] Gathering output for process 3748
23:17:59  [2022-08-18T03:17:46.992277500Z] Waiting for completion for process 3748
23:17:59  [2022-08-18T03:17:46.992277500Z] Waiting for completion finished for process 3748
23:17:59  Output and diagnostic info for process 3748 was saved into 'pid-3748-output.log'
23:17:59  
23:17:59  
23:17:59  
23:17:59  [2022-08-18T03:17:46.992277500Z] Waiting for completion for process 3748
23:17:59  [2022-08-18T03:17:46.992277500Z] Waiting for completion finished for process 3748
23:17:59  Command line: [C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_1\openjdkbinary\j2sdk-image\bin\java.exe -ea -esa -cp C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_1\aqa-tests\TKG\output_16607909222095\jdk_util_0\work\classes\1\java\util\ResourceBundle\Control\MissingResourceCauseTestRun.d;C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_1\aqa-tests\openjdk\openjdk-jdk\test\jdk\java\util\ResourceBundle\Control;. MissingResourceCauseTest]
23:17:59  [2022-08-18T03:17:47.039147300Z] Gathering output for process 10540
23:17:59  [2022-08-18T03:17:48.195426100Z] Waiting for completion for process 10540
23:17:59  [2022-08-18T03:17:48.195426100Z] Waiting for completion finished for process 10540
23:17:59  Output and diagnostic info for process 10540 was saved into 'pid-10540-output.log'
23:17:59  Exception in thread "main" java.lang.RuntimeException: getBundle("UnreadableRB") doesn't throw class java.io.IOException
23:17:59  	at MissingResourceCauseTest.callGetBundle(MissingResourceCauseTest.java:51)
23:17:59  	at MissingResourceCauseTest.callGetBundle(MissingResourceCauseTest.java:43)
23:17:59  	at MissingResourceCauseTest.main(MissingResourceCauseTest.java:37)
```

The test does `chmod 000 UnreadableRB.properties` and then expects reading the file/resource bundle to throw IOException.

I tried a simple test on the machine, setting a file to permissions `000`, but although `ls -l` shows no permission, the file is still readable. 

The test also fails with Hotspot in the same way. Maybe a limitation of Windows 10, opened infrastructure/issues/7183
