### ISSUE TITLE
JEP 424: Foreign Function & Memory API (Preview)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15035]
See https://openjdk.java.net/jeps/424

@tajila @ChengJin01

**Comment by ChengJin01** [comment]
@babsingh, please take a look at the new JEP to see whether anything new related to the Foreign Memory API needs to be updated/modified in OpenJ9 given the Foreign Function API is built on top of that.

**Comment by ChengJin01** [comment]
There might be not too many changes as compared to https://openjdk.java.net/jeps/419 (Second Incubator) except the following APIs:

```
Linker linker = Linker.nativeLinker(); <----   systemCLinker() is replaced with nativeLinker()

interface Linker {
    MethodHandle downcallHandle(Addressable func,
                                FunctionDescriptor function);
    MemorySegment upcallStub(MethodHandle target, <----- NativeSymbol is replaced with MemorySegment
                          FunctionDescriptor function,
                          MemorySession session);
}
```
But we need to wait to see how these work as the new API specific changes have not yet been merged to either 
https://github.com/ibmruntimes/openj9-openjdk-jdk/tree/openj9-staging/src/jdk.incubator.foreign or https://github.com/ibmruntimes/openj9-openjdk-jdk/tree/openj9/src/jdk.incubator.foreign

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/15035#issuecomment-1122534348:

> please take a look at the new JEP to see whether anything new related to the Foreign Memory API needs to be updated/modified in OpenJ9 given the Foreign Function API is built on top of that.

I have read through JEP424 and ran the `jdk_foreign` test suite. As of now, there are no new requirements, in terms of OpenJ9 support, for the Foreign Memory API in JEP424. Referring to the below information, all current failures are due to missing `upcall` support.

### jdk_foreign test suite cmd

```
make test TEST=jdk_foreign
```

### jdk_foreign test suite output

**LOG:** [jdk_foreign_13May22.log](https://github.com/eclipse-openj9/openj9/files/8689188/jdk_foreign_13May22.log)

### Summary

```
   TEST                                              TOTAL  PASS  FAIL ERROR
>> jtreg:test/jdk:jdk_foreign                           79    63    14     2 <<
```

### Failing Tests

Two unique failures:
- `InternalError: arrangeUpcall is not yet implemented`
- `AssertionError: Did not find 'Testing upcall exceptions' in stderr expected [true] but found [false]`

```
# grep -A2 ": failure$" jdk_foreign_13May22.log

test SafeFunctionAccessTest.testClosedStructCallback(): failure
java.lang.AssertionError: java.lang.InternalError: arrangeUpcall is not yet implemented
	at SafeFunctionAccessTest.scopeChecker(SafeFunctionAccessTest.java:185)
--
test SafeFunctionAccessTest.testClosedUpcall(): failure
org.testng.TestException:
Expected exception of type class java.lang.IllegalStateException but got java.lang.InternalError: arrangeUpcall is not yet implemented
--
test SafeFunctionAccessTest.testClosedUpcallCallback(): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test SafeFunctionAccessTest.testClosedVaListCallback(): failure
java.lang.AssertionError: java.lang.InternalError: arrangeUpcall is not yet implemented
	at SafeFunctionAccessTest.scopeChecker(SafeFunctionAccessTest.java:185)
--
config TestUpcall.setup(): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
config TestUpcall.setup(): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
config TestUpcall.setup(): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test TestUpcallException.testExceptionInterpreted(): failure
java.lang.AssertionError: Did not find 'Testing upcall exceptions' in stderr expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
--
test TestUpcallException.testExceptionSpecialized(): failure
java.lang.AssertionError: Did not find 'Testing upcall exceptions' in stderr expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
--
test TestUpcallStructScope.testUpcall(): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test TestUpcallHighArity.testUpcall(java.lang.invoke.BoundMethodHandle$Species_LLLLL@9e33c0cf, java.lang.invoke.MethodType@4283ee8f, jdk.incubator.foreign.FunctionDescriptor@882b7a93): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@4db4ca4c): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@b9f1585e): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@5351e2b1): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@a93cf0fb): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@baec6a6a): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@41d84447): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@b946911e): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@bd34f0f9): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@2506baac): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@6f98eb27): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@c563aad9): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
--
test VaListTest.testUpcall(MethodHandle(Addressable)void, java.lang.invoke.BoundMethodHandle$Species_LLL@76de5c88): failure
java.lang.InternalError: arrangeUpcall is not yet implemented
	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:138)
```

**Comment by babsingh** [comment]
For Foreign Function API, we will need to add an implementation of `MethodHandle.linkToNative` in [BytecodeInterpreter.hpp](https://github.com/eclipse-openj9/openj9/blob/3c82c45fd6053436c6f957015b909b39f0687b38/runtime/vm/BytecodeInterpreter.hpp#L8750). It is used by `NativeMethodHandle`. I do not see its implementation in OpenJ9 yet. @ChengJin01 Do we plan to use `MethodHandle.linkToNative` in OpenJ9 or do we have an alternate approach?

### References
1. [MethodHandle.linkToNative](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/81562b2e0132ea4093e50902791dc97f78e8de36/src/java.base/share/classes/java/lang/invoke/MethodHandle.java#L608-L610)
2. [NativeMethodHandle](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/81562b2e0132ea4093e50902791dc97f78e8de36/src/java.base/share/classes/java/lang/invoke/NativeMethodHandle.java#L36-L41)

**Comment by tajila** [comment]
> It is used by [NativeMethodHandle](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/81562b2e0132ea4093e50902791dc97f78e8de36/src/java.base/share/classes/java/lang/invoke/NativeMethodHandle.java#L36-L41). I do not see its implementation in OpenJ9 yet.

NativeMethodHandle is an optimization. It only makes sense to use it if we have JIT support for downcalls which we currently dont have. So for the time being `linkToNative` is not needed.

**Comment by ChengJin01** [comment]
Close the issue as we already implemented everything related to upcall in JEP424 via https://github.com/eclipse-openj9/openj9/issues/15068.
