### ISSUE TITLE
JDK18 jdk_nio_1_FAILED java/nio/channels/Channels/TransferTo.java OOM

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15040]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_extended.openjdk_x86-64_linux/21/`(`ub18x64rt1-1`):
```
openjdk version "18.0.1.1" 2022-04-22
IBM Semeru Runtime Open Edition 18.0.1.1 (build 18.0.1.1+2)
Eclipse OpenJ9 VM 18.0.1.1 (build openj9-0.32.0, JRE 18 Linux amd64-64-Bit Compressed References 20220509_70 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 8d05779b116 based on jdk-18.0.1.1+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_nio_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F70%2Fibm-semeru-open-testimage_x64_linux_18.0.1.1_2_openj9-0.32.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F70%2Fibm-semeru-open-debugimage_x64_linux_18.0.1.1_2_openj9-0.32.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F70%2Fibm-semeru-open-jdk_x64_linux_18.0.1.1_2_openj9-0.32.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18%2Fjdk18-linux-x64-openj9%2F70%2Fibm-semeru-open-jre_x64_linux_18.0.1.1_2_openj9-0.32.0.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk18&amp;RELEASE_TAG=v0.32.0-release-18.0.1.1&amp;OPENJ9_BRANCH=v0.32.0-release-18.0.1.1&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.32.0-release-18.0.1.1&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
openjdk version "18.0.1.1" 2022-04-22
IBM Semeru Runtime Open Edition 18.0.1.1 (build 18.0.1.1+2)
Eclipse OpenJ9 VM 18.0.1.1 (build openj9-0.32.0, JRE 18 Linux amd64-64-Bit Compressed References 20220509_70 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 8d05779b116 based on jdk-18.0.1.1+2)

[2022-05-09T17:35:18.739Z] variation: Mode650
[2022-05-09T17:35:18.739Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-05-09T17:37:38.636Z] TEST: java/nio/channels/Channels/TransferTo.java

[2022-05-09T17:37:38.636Z] test TransferTo.testStreamContents(TransferTo$2@17a3d440, TransferTo$6@6f536a3b): failure
[2022-05-09T17:37:38.636Z] java.lang.OutOfMemoryError: Java heap space
[2022-05-09T17:37:38.636Z] 	at java.base/java.util.Arrays.copyOf(Arrays.java:3568)
[2022-05-09T17:37:38.636Z] 	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
[2022-05-09T17:37:38.636Z] 	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
[2022-05-09T17:37:38.636Z] 	at java.base/java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:394)
[2022-05-09T17:37:38.636Z] 	at java.base/sun.nio.ch.FileChannelImpl.transferToArbitraryChannel(FileChannelImpl.java:655)
[2022-05-09T17:37:38.636Z] 	at java.base/sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:703)
[2022-05-09T17:37:38.636Z] 	at java.base/sun.nio.ch.ChannelInputStream.transfer(ChannelInputStream.java:268)
[2022-05-09T17:37:38.636Z] 	at java.base/sun.nio.ch.ChannelInputStream.transferTo(ChannelInputStream.java:257)
[2022-05-09T17:37:38.636Z] 	at TransferTo.checkTransferredContents(TransferTo.java:283)
[2022-05-09T17:37:38.636Z] 	at TransferTo.testStreamContents(TransferTo.java:148)
[2022-05-09T17:37:38.636Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-05-09T17:37:38.636Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-05-09T17:37:38.636Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-05-09T17:37:38.636Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-05-09T17:37:38.636Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-05-09T17:37:38.636Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-05-09T17:37:38.636Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-05-09T17:37:38.636Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-05-09T17:37:38.636Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-05-09T17:37:38.636Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-05-09T17:37:38.636Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-05-09T17:37:38.636Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-05-09T17:37:38.636Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-05-09T17:37:38.636Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-05-09T17:37:38.636Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-05-09T17:37:38.636Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-05-09T17:37:38.636Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-05-09T17:37:38.636Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-05-09T17:37:38.636Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-05-09T17:37:38.636Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-05-09T17:37:38.636Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-05-09T17:37:38.636Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-05-09T17:37:38.636Z] test TransferTo.testStreamContents(TransferTo$3@fe1dc587, TransferTo$1@8e901dec): success
[2022-05-09T17:37:38.636Z] 
[2022-05-09T17:37:38.636Z] ===============================================
[2022-05-09T17:37:38.636Z] java/nio/channels/Channels/TransferTo.java
[2022-05-09T17:37:38.636Z] Total tests run: 10, Passes: 9, Failures: 1, Skips: 0
[2022-05-09T17:37:38.636Z] ===============================================
[2022-05-09T17:37:38.636Z] 
[2022-05-09T17:37:38.636Z] STDERR:
[2022-05-09T17:37:38.636Z] JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/05/09 13:37:20 - please wait.

[2022-05-09T17:37:38.637Z] JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[2022-05-09T17:37:38.637Z] java.lang.Exception: failures: 1
[2022-05-09T17:37:38.637Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2022-05-09T17:37:38.637Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-05-09T17:37:38.637Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-05-09T17:37:38.637Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-05-09T17:37:38.637Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-05-09T17:37:38.637Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-05-09T17:37:38.637Z] 
[2022-05-09T17:37:38.637Z] JavaTest Message: Test threw exception: java.lang.Exception: failures: 1

[2022-05-09T17:37:38.685Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2022-05-09T17:37:38.685Z] --------------------------------------------------
[2022-05-09T18:03:45.634Z] Test results: passed: 388; failed: 1
[2022-05-09T18:04:16.083Z] 
[2022-05-09T18:04:16.083Z] jdk_nio_1_FAILED
```
50x grinder - `job/Grinder/23697`

**Comment by dmitripivkine** [comment]
There is scenario for failure:

- allocation of 110739480 bytes object requested
- Local GC is performed, with newspace=71591680/134217728 at the end, does not help obviously
- Global GC with Compact with memory=336218600/536870912 at the end
- Tenure is fragmented and still be no space to allocate 110739480 bytes, so we perform second Global under the same Exclusive
- Second Global does Class Unloading but not Compact (?), with oldspace=256156600/394199040 loa=3942400/3942400 at the end
- Tenure still be fragmented, there are four free chunks 5418824, 44110216, 95872536, 106812624 bytes, so object still does not fit

I think the decision to not perform Compact second (Aggressive) Global GC is not correct. We are going to investigate.
