### ISSUE TITLE
OpenJDK ConcurrentHashMap/ToArray.java NoClassDefFoundError: java.lang.Integer

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15055]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly/267
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/concurrent/ConcurrentHashMap/ToArray.java
```
22:36:54  rerun:
22:36:54  cd 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16523219865470\jdk_util_0\work\scratch\2' && \
22:36:54  PATH='C:\cygwin64\bin;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\apache-ant\apache-ant-1.10.3\bin;C:\Program Files\Java\jdk8u202-b08\bin;C:\Strawberry\perl\bin;C:\Program Files\Microsoft Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\OpenSSL-1.1.1-x86_32\bin;C:\OpenSSL-1.1.1-x86_64\bin;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0' \
22:36:54  SystemDrive=C: \
22:36:54  SystemRoot='C:\Windows' \
22:36:54  TEMP='C:\temp' \
22:36:54  windir='C:\Windows' \
22:36:54      'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java' \
22:36:54          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops' \
22:36:54          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops' \
22:36:54          -Dtest.compiler.opts= \
22:36:54          -Dtest.java.opts= \
22:36:54          -Dtest.jdk='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
22:36:54          -Dcompile.jdk='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
22:36:54          -Dtest.timeout.factor=8.0 \
22:36:54          -Dtest.root='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test' \
22:36:54          -Dtest.name=java/util/concurrent/ConcurrentHashMap/ToArray.java \
22:36:54          -Dtest.file='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap\ToArray.java' \
22:36:54          -Dtest.src='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap' \
22:36:54          -Dtest.src.path='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap' \
22:36:54          -Dtest.classes='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16523219865470\jdk_util_0\work\classes\1\java\util\concurrent\ConcurrentHashMap' \
22:36:54          -Dtest.class.path='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16523219865470\jdk_util_0\work\classes\1\java\util\concurrent\ConcurrentHashMap' \
22:36:54          -Dtest.class.path.prefix='F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16523219865470\jdk_util_0\work\classes\1\java\util\concurrent\ConcurrentHashMap;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap' \
22:36:54          -classpath 'F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16523219865470\jdk_util_0\work\classes\1\java\util\concurrent\ConcurrentHashMap;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\util\concurrent\ConcurrentHashMap;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\lib\tools.jar;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\javatest.jar;F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\jtreg.jar' \
22:36:54          ToArray
22:36:54  STDERR:
22:36:54  java.lang.NoClassDefFoundError: java.lang.Integer
22:36:54  	at ToArray$1.run(ToArray.java:75)
22:36:54  	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
22:36:54  	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
22:36:54  	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
22:36:54  	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
22:36:54  	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
22:36:54  	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by pshipton** [comment]
Perhaps related to https://github.com/eclipse-openj9/openj9/issues/14777
