### ISSUE TITLE
Compile failure on Mac x86 with Xcode 12.4

### ISSUE THREAD

**Issue by jdekonin** [eclipse-openj9/openj9#15085]
Failure in openj9.dtfj-gensrc-src when compiling with xcode 12.4 which is the desired version for JDK17.

```
09:37:45  Exception in thread "main" java.lang.RuntimeException: Unexpected SRP reference type: -1 from J9SRP(J9SimplePool)
09:37:45  	at com.ibm.j9ddr.tools.PointerGenerator.writeSRPMethod(PointerGenerator.java:1152)
09:37:45  	at com.ibm.j9ddr.tools.PointerGenerator.generateImplementationMethods(PointerGenerator.java:592)
09:37:45  	at com.ibm.j9ddr.tools.PointerGenerator.generateClass(PointerGenerator.java:349)
09:37:45  	at com.ibm.j9ddr.tools.PointerGenerator.generateClasses(PointerGenerator.java:175)
09:37:45  	at com.ibm.j9ddr.tools.PointerGenerator.main(PointerGenerator.java:122)
09:37:45  make[4]: *** [/Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/support/ddr/gensrc-pointers.done] Error 1
09:37:45  Structure stub generation complete
09:37:45  make[3]: *** [all] Error 2
09:37:45  make[2]: *** [openj9.dtfj-gensrc-src] Error 2
```

**Comment by keithc-ca** [comment]
Earlier in the build log I see this:
```
09:01:43  [100%] Generating /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/runtime/j9ddr.dat, /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/superset.dat
09:01:44  sh: line 1:  8436 Abort trap: 6           /Applications/Xcode-12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/runtime/libj9gc29.dylib.dSYM/Contents/Resources/DWARF/libj9gc29.dylib 2>&1
09:02:13  sh: line 1:  8510 Abort trap: 6           /Applications/Xcode-12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/runtime/libj9shr29.dylib.dSYM/Contents/Resources/DWARF/libj9shr29.dylib 2>&1
09:02:13  sh: line 1:  8518 Abort trap: 6           /Applications/Xcode-12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/runtime/libj9vrb29.dylib.dSYM/Contents/Resources/DWARF/libj9vrb29.dylib 2>&1
09:02:13  sh: line 1:  8522 Abort trap: 6           /Applications/Xcode-12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/runtime/libj9vm29.dylib.dSYM/Contents/Resources/DWARF/libj9vm29.dylib 2>&1
09:02:13  Blob written to file: /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/runtime/j9ddr.dat
09:02:13  Superset written to file: /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-openj9-IBM/workspace/build/src/build/macosx-x86_64-server-release/vm/superset.dat
```
I expect that https://github.com/eclipse/omr/pull/5800 will fix this because it will avoid using the failing `dwarfdump-classic`.

**Comment by jdekonin** [comment]
I'll keep an eye on that PR and retest once its merged.  Thanks @keithc-ca!
