### ISSUE TITLE
JDK11 jdk_security3_0_FAILED Unexpected exception: sun.security.validator.ValidatorException: No trusted certificate found

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15106]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_extended.openjdk_aarch64_linux/46/`:
```
java version "11.0.16" 2022-07-19
IBM Semeru Runtime Certified Edition 11.0.16+3 (build 11.0.16+3)
Eclipse OpenJ9 VM 11.0.16+3 (build master-00bc246e2, JRE 11 Linux aarch64-64-Bit Compressed References 20220521_60 (JIT enabled, AOT enabled)
OpenJ9   - 00bc246e2
OMR      - 42677ec34
JCL      - dbbf417306 based on jdk-11.0.16+3)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F60%2Fibm-semeru-certified-jdk_aarch64_linux_JDK11U_2022-05-21-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F60%2Fibm-semeru-certified-debugimage_aarch64_linux_JDK11U_2022-05-21-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F60%2Fibm-semeru-certified-jre_aarch64_linux_JDK11U_2022-05-21-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F60%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2022-05-21-01-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-05-21T03:02:24.352Z] variation: Mode150
[2022-05-21T03:02:24.352Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-05-21T03:09:07.667Z] TEST: sun/security/lib/cacerts/VerifyCACerts.java

[2022-05-21T03:09:07.670Z] java.lang.Exception: At least one cacert test failed
[2022-05-21T03:09:07.670Z] 	at VerifyCACerts.main(VerifyCACerts.java:356)
[2022-05-21T03:09:07.670Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T03:09:07.670Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T03:09:07.670Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T03:09:07.670Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T03:09:07.670Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-05-21T03:09:07.670Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T03:09:07.670Z] 
[2022-05-21T03:09:07.670Z] JavaTest Message: Test threw exception: java.lang.Exception

[2022-05-21T03:20:46.384Z] TEST: sun/security/ssl/X509TrustManagerImpl/Symantec/Distrust.java

[2022-05-21T03:20:46.387Z] STDERR:
[2022-05-21T03:20:46.387Z] Testing geotrustglobalca
[2022-05-21T03:20:46.387Z] java.lang.Exception: Unexpected exception: sun.security.validator.ValidatorException: No trusted certificate found
[2022-05-21T03:20:46.387Z] 	at Distrust.testTM(Distrust.java:190)
[2022-05-21T03:20:46.387Z] 	at Distrust.main(Distrust.java:114)
[2022-05-21T03:20:46.387Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T03:20:46.387Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T03:20:46.387Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T03:20:46.387Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T03:20:46.387Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-05-21T03:20:46.387Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T03:20:46.387Z] 
[2022-05-21T03:20:46.387Z] JavaTest Message: Test threw exception: java.lang.Exception: Unexpected exception: sun.security.validator.ValidatorException: No trusted certificate found

[2022-05-21T03:39:25.702Z] jdk_security3_0_FAILED
```

This is a recent enabled test.

fyi @llxia

**Comment by pshipton** [comment]
Is this failing across platform or just on this one?

**Comment by pshipton** [comment]
@LongyuZhang fyi. Does this fail on Temurin as well?

**Comment by LongyuZhang** [comment]
@pshipton  Yes, these two tests are failing on all platforms for Tenurin ([Issue here](https://github.com/adoptium/aqa-tests/issues/2123#issue-769213757)), but I did not see them fail before when testing with Openj9. I have created PR to exclude these two tests.
