### ISSUE TITLE
JDK11 jdk_util_1_FAILED fips related failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15108]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/1/`(`rhel8x64-fips4-1`):
```
java version "11.0.16" 2022-07-19
IBM Semeru Runtime Certified Edition 11.0.16+3 (build 11.0.16+3)
Eclipse OpenJ9 VM 11.0.16+3 (build master-00bc246e2, JRE 11 Linux amd64-64-Bit Compressed References 20220521_349 (JIT enabled, AOT enabled)
OpenJ9   - 00bc246e2
OMR      - 42677ec34
JCL      - dbbf417306 based on jdk-11.0.16+3)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_util_1&amp;TEST_FLAG=FIPS&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=-Dsemeru.fips%3Dtrue&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-jdk_x64_linux_JDK11U_2022-05-21-01-02.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-jre_x64_linux_JDK11U_2022-05-21-01-02.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-testimage_x64_linux_JDK11U_2022-05-21-01-02.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-debugimage_x64_linux_JDK11U_2022-05-21-01-02.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=3&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-05-21T02:32:24.129Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-05-21T02:32:24.129Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Dsemeru.fips=true

[2022-05-21T02:35:31.466Z] TEST: java/util/jar/JarFile/mrjar/MultiReleaseJarAPI.java

[2022-05-21T02:35:31.639Z] Caused by: java.security.NoSuchAlgorithmException: PBE AlgorithmParameters not available
[2022-05-21T02:35:31.639Z] 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
[2022-05-21T02:35:31.639Z] 	at java.base/java.security.Security.getImpl(Security.java:719)
[2022-05-21T02:35:31.639Z] 	at java.base/java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:158)
[2022-05-21T02:35:31.639Z] 	at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:833)
[2022-05-21T02:35:31.639Z] 	... 35 more

[2022-05-21T02:35:49.627Z] TEST: java/util/jar/JarFile/mrjar/MultiReleaseJarSecurity.java

[2022-05-21T02:35:49.639Z] Caused by: java.security.NoSuchAlgorithmException: PBE AlgorithmParameters not available
[2022-05-21T02:35:49.639Z] 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
[2022-05-21T02:35:49.639Z] 	at java.base/java.security.Security.getImpl(Security.java:719)
[2022-05-21T02:35:49.639Z] 	at java.base/java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:158)
[2022-05-21T02:35:49.639Z] 	at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:833)

[2022-05-21T02:35:51.819Z] TEST: java/util/jar/JarFile/ScanSignedJar.java

[2022-05-21T02:35:51.824Z] java.lang.Exception: Failed to detect that the JAR file is signed
[2022-05-21T02:35:51.824Z] 	at ScanSignedJar.main(ScanSignedJar.java:63)
[2022-05-21T02:35:51.824Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T02:35:51.824Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T02:35:51.824Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T02:35:51.824Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T02:35:51.824Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-05-21T02:35:51.824Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T02:35:51.824Z] 
[2022-05-21T02:35:51.824Z] JavaTest Message: Test threw exception: java.lang.Exception

[2022-05-21T02:35:51.824Z] TEST: java/util/jar/JarFile/TurkCert.java
[2022-05-21T02:35:51.834Z] java.lang.Exception: Null certificate for test.class.
[2022-05-21T02:35:51.834Z] 	at TurkCert.main(TurkCert.java:50)
[2022-05-21T02:35:51.834Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T02:35:51.834Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T02:35:51.834Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T02:35:51.834Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T02:35:51.834Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-05-21T02:35:51.834Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T02:35:51.834Z] 
[2022-05-21T02:35:51.834Z] JavaTest Message: Test threw exception: java.lang.Exception

[2022-05-21T02:35:52.437Z] TEST: java/util/jar/JarInputStream/ExtraFileInMetaInf.java
[2022-05-21T02:35:52.459Z] java.lang.SecurityException: System.exit() forbidden by JT Harness
[2022-05-21T02:35:52.459Z] 	at com.sun.javatest.regtest.agent.JavaTestSecurityManager.checkExit(JavaTestSecurityManager.java:116)
[2022-05-21T02:35:52.459Z] 	at java.base/java.lang.Runtime.exit(Runtime.java:114)
[2022-05-21T02:35:52.459Z] 	at java.base/java.lang.System.exit(System.java:473)
[2022-05-21T02:35:52.459Z] 	at java.base/sun.security.tools.keytool.Main.run(Main.java:420)
[2022-05-21T02:35:52.459Z] 	at java.base/sun.security.tools.keytool.Main.main(Main.java:405)
[2022-05-21T02:35:52.459Z] 	at ExtraFileInMetaInf.main(ExtraFileInMetaInf.java:52)
[2022-05-21T02:35:52.459Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T02:35:52.463Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T02:35:52.464Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T02:35:52.464Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T02:35:52.464Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-05-21T02:35:52.464Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T02:35:52.464Z] 
[2022-05-21T02:35:52.464Z] JavaTest Message: Test threw exception: java.lang.SecurityException

[2022-05-21T02:35:52.464Z] TEST: java/util/jar/JarInputStream/ScanSignedJar.java
[2022-05-21T02:35:52.558Z] java.lang.Exception: Count.class should be signed
[2022-05-21T02:35:52.558Z] 	at ScanSignedJar.main(ScanSignedJar.java:74)
[2022-05-21T02:35:52.558Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T02:35:52.558Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T02:35:52.558Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T02:35:52.558Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T02:35:52.558Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-05-21T02:35:52.558Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T02:35:52.558Z] 
[2022-05-21T02:35:52.558Z] JavaTest Message: Test threw exception: java.lang.Exception

[2022-05-21T02:35:52.558Z] TEST: java/util/jar/JarInputStream/TestIndexedJarWithBadSignature.java
[2022-05-21T02:35:52.577Z] java.lang.RuntimeException: Test Failed:Security Exception not being thrown
[2022-05-21T02:35:52.577Z] 	at TestIndexedJarWithBadSignature.main(TestIndexedJarWithBadSignature.java:49)
[2022-05-21T02:35:52.577Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T02:35:52.577Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T02:35:52.577Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T02:35:52.577Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T02:35:52.578Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-05-21T02:35:52.578Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T02:35:52.578Z] 
[2022-05-21T02:35:52.578Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

[2022-05-21T02:35:52.578Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Test Failed:Security Exception not being thrown
[2022-05-21T02:35:52.578Z] --------------------------------------------------
[2022-05-21T02:47:15.192Z] Test results: passed: 836; failed: 7
[2022-05-21T02:47:27.491Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/jvmtest/openjdk/report/html/report.html
[2022-05-21T02:47:27.491Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/aqa-tests/TKG/output_1653099598932/jdk_util_1/work
[2022-05-21T02:47:27.491Z] Error: Some tests failed or other problems occurred.
[2022-05-21T02:47:27.491Z] 
[2022-05-21T02:47:27.491Z] jdk_util_1_FAILED

```

**Comment by pshipton** [comment]
This is related to https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/520

**Comment by taoliult** [comment]
@pshipton @keithc-ca @alon-sh 
Those failures above from sanity.openjdk tests, due to some tests hard coded to use the provider SunJCE which is not enabled in the FIPS mode, or due to we removed the non-FIPS compliance algorithms from providers Sun and SunEC, or due to the FIPS mode only support the PKCS11 keys. So we will add the above tests into the ProblemList-fips.txt, so that these tests will not be run in the FIPS mode.

**Comment by vij-singh** [comment]
@alon-sh @taoliult - Any update on this one?

**Comment by vij-singh** [comment]
@taoliult  Could you update this with current status?
