### ISSUE TITLE
cmdLineTester_libpathTestRtfChild_0 fails against headless platforms

### ISSUE THREAD

**Issue by smlambert** [eclipse-openj9/openj9#15119]
Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.functional_x86-64_alpine-linux_testList_0/2/
https://trss.adoptium.net/output/test?id=628e442372761a4c5c55ae49

The test tries to load a library that won't be present for a headless build.

Optional info
-------------

- intermittent failure (yes|no): no
- regression or new test:  not a regression, always failed

Failure output (captured from console output)
---------------------------------------------

```
[2022-05-25T14:33:26.753Z]  [OUT] fontmanger LIB: libfontmanager.so
[2022-05-25T14:33:26.753Z]  [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /home/jenkins/workspace/Test_openjdk17_hs_sanity.functional_x86-64_alpine-linux_testList_0/openjdkbinary/j2sdk-image/lib/libawt_xawt.so
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/java.lang.System.load(System.java:1953)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:1989)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/java.awt.EventQueue.isDispatchThread(EventQueue.java:1087)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1493)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.reclaim(StyleContext.java:473)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.addAttribute(StyleContext.java:330)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext$NamedStyle.addAttribute(StyleContext.java:1558)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext$NamedStyle.setName(StyleContext.java:1368)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext$NamedStyle.<init>(StyleContext.java:1315)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.addStyle(StyleContext.java:125)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.StyleContext.<init>(StyleContext.java:105)
[2022-05-25T14:33:26.753Z]  [ERR] 	at java.desktop/javax.swing.text.DefaultStyledDocument.<init>(DefaultStyledDocument.java:109)
[2022-05-25T14:33:26.753Z]  [ERR] 	at org.openj9.test.libpath.RtfChild.convert(RtfChild.java:41)
[2022-05-25T14:33:26.753Z]  [ERR] 	at org.openj9.test.libpath.RtfChild.main(RtfChild.java:60)
```

**Comment by pshipton** [comment]
What is expected here? Are we going to create a new test bucket like sanity.headless that don't include this test?

**Comment by smlambert** [comment]
No, we do not need a new test bucket.  We need a way to filter out headless builds, and then tag in the playlist (possibly similar to how we do test type as either [regular | native].  I will look to see how much work this implies.

Alternatively, I could change the playlist to exclude x86-64_alpine-linux platform for now, since it is the only headless platform that is being tested.

**Comment by smlambert** [comment]
We can exclude it for the alpine-linux platform under https://bugs.openjdk.org/browse/JDK-8242559

FYI @sophia-guo
