### ISSUE TITLE
OpenJDK util/stream/ReduceTest crash vmState=0x00000000

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15114]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly/62
jdk_util_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops`
java/util/stream/test/org/openjdk/tests/java/util/stream/ReduceTest.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly/62/openjdk_test_output.tar.gz
```
22:20:01  STDOUT:
22:20:01  [TestNG] Running:
22:20:01    java/util/stream/test/org/openjdk/tests/java/util/stream/ReduceTest.java
22:20:01  
22:20:01  config java.util.stream.LoggingTestCase.before(): success
22:20:01  STDERR:
22:20:01  Unhandled exception
22:20:01  Type=Segmentation error vmState=0x00000000
22:20:01  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
22:20:01  Handler1=0000000104CBF11C Handler2=0000000104E76DFC InaccessibleAddress=0000000000000020
22:20:01  x0=000000012603BF00 x1=0000000170062800 x2=0000000170062800 x3=0000000000000038
22:20:01  x4=000000016C2468E8 x5=000000016C2468E8 x6=0000000000000001 x7=0000000000000001
22:20:01  x8=000000012B014C20 x9=0000000000000018 x10=0000000000000000 x11=0000000000000001
22:20:01  x12=00000001383B5984 x13=0000000000000001 x14=000000000000004C x15=0000000000000001
22:20:01  x16=00000000FFFFFFFF x17=000000012B27FBC0 x18=000000016C246C10 x19=000000016C2468C0
22:20:01  x20=0000000000000000 x21=000000012603BF00 x22=0000000131194340 x23=000000016C2468F0
22:20:01  x24=00000001383B3369 x25=000000016C246920 x26=0000000104D21A60 x27=000000016C2468D0
22:20:01  x28=000000016C2468C8 x29(FP)=000000016C2468B0 x30(LR)=0000000104D1B0BC x31(SP)=000000016C246630
22:20:01  PC=0000000104D1709C SP=000000016C246630
22:20:01  v0 0000000170056de0 (f: 1879404032.000000, d: 3.050545e-314)
22:20:01  v1 000000012b27fb91 (f: 724040576.000000, d: 2.479719e-314)
22:20:01  v2 0706050403020100 (f: 50462976.000000, d: 7.949929e-275)
22:20:01  v3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v4 40d1f55c4b70c8ee (f: 1265682688.000000, d: 1.838944e+04)
22:20:01  v5 3ea19aa65b05731b (f: 1527083776.000000, d: 5.246431e-07)
22:20:01  v6 40c0000000000000 (f: 0.000000, d: 8.192000e+03)
22:20:01  v7 c0c0000000000000 (f: 0.000000, d: -8.192000e+03)
22:20:01  v8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v16 bfd0000000000000 (f: 0.000000, d: -2.500000e-01)
22:20:01  v17 3fd55880ca175555 (f: 3390526720.000000, d: 3.335268e-01)
22:20:01  v18 bf495e296c387133 (f: 1815638272.000000, d: -7.741644e-04)
22:20:01  v19 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
22:20:01  v20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  v31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:20:01  Module=/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly/openjdkbinary/j2sdk-image/lib/default/libj9vm29.dylib
22:20:01  Module_base_address=0000000104C9C000 Symbol=_ZN26VM_BytecodeInterpreterFull3runEP10J9VMThread
22:20:01  Symbol_address=0000000104D037A4
22:20:01  Target=2_90_20220525_64 (Mac OS X 11.5.2)
22:20:01  CPU=aarch64 (8 logical CPUs) (0x400000000 RAM)
22:20:01  ----------- Stack Backtrace -----------
22:20:01  ---------------------------------------
```

Maybe related to https://github.com/eclipse-openj9/openj9/issues/12556
@knn-k fyi

**Comment by knn-k** [comment]
I ran a 30x Grinder job.  No failures.  https://openj9-jenkins.osuosl.org/job/Grinder/874/

**Comment by knn-k** [comment]
I tried to read the core file with jdmpview, but it failed with the following exception:

```
Could not load dump file and/or could not load XML file: Could not create a valid ImageFactory
java.io.IOException: Could not create a valid ImageFactory
        at openj9.dtfj/com.ibm.dtfj.image.j9.ImageFactory.propagateIOException(ImageFactory.java:402)
        at openj9.dtfj/com.ibm.dtfj.image.j9.ImageFactory.getImage(ImageFactory.java:262)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.commands.OpenCommand.imagesFromCommandLine(OpenCommand.java:115)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.commands.OpenCommand.run(OpenCommand.java:83)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.Context.tryCommand(Context.java:141)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.Context.execute(Context.java:97)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:173)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:157)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.imageFromCommandLine(Session.java:610)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.sessionInit(Session.java:226)
```

**Comment by pshipton** [comment]
@keithc-ca fyi the dtfj failure to read the core.

**Comment by keithc-ca** [comment]
I don't see any core files available as artifacts attached to that grinder job.
@knn-k Can you share a core file with those symptoms (or a URL of one)?

**Comment by pshipton** [comment]
@keithc-ca I expect the core is from the original failure
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly/62/openjdk_test_output.tar.gz

**Comment by knn-k** [comment]
Right.
PR #14420 was merged on May 27, and the test failure is from the May 24 nightly job.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly/83 - [mac11-aarch64-2](https://openj9-jenkins.osuosl.org/computer/mac11-aarch64-2)
jdk_util_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops`
java/util/stream/test/org/openjdk/tests/java/util/stream/ReduceTest.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly/83/openjdk_test_output.tar.gz

```
21:07:52  STDOUT:
21:07:52  [TestNG] Running:
21:07:52    java/util/stream/test/org/openjdk/tests/java/util/stream/ReduceTest.java
21:07:52  
21:07:52  config java.util.stream.LoggingTestCase.before(): success
21:07:52  STDERR:
21:07:52  Unhandled exception
21:07:52  Type=Segmentation error vmState=0x00000000
21:07:52  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
21:07:52  Handler1=000000010702299C Handler2=0000000102F3AE14 InaccessibleAddress=0000000000000020
21:07:52  x0=000000011C839100 x1=0000000158078928 x2=0000000158078030 x3=0000000000000013
21:07:52  x4=000000011C838AB8 x5=000000016DFC28E8 x6=000000028004CBF8 x7=0000000000000005
21:07:52  x8=0000000120811A20 x9=0000000000000018 x10=0000000000000000 x11=0000000000000002
21:07:52  x12=0000000139BDAC30 x13=0000000000000004 x14=0000000000000014 x15=0000000000000000
21:07:52  x16=0000000000000004 x17=000000011C838A88 x18=000000016DFC2C10 x19=000000016DFC28C0
21:07:52  x20=0000000000000000 x21=000000011C839100 x22=000000010923C280 x23=000000016DFC28F0
21:07:52  x24=0000000139BDA165 x25=000000016DFC2920 x26=0000000107085394 x27=000000016DFC28D0
21:07:52  x28=000000016DFC28C8 x29(FP)=000000016DFC28B0 x30(LR)=00000001070672B0 x31(SP)=000000016DFC2630
21:07:52  PC=000000010707A9D0 SP=000000016DFC2630
21:07:52  v0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v1 408f400000000000 (f: 0.000000, d: 1.000000e+03)
21:07:52  v2 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
21:07:52  v3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v4 40d1f55c4b70c8ee (f: 1265682688.000000, d: 1.838944e+04)
21:07:52  v5 3ea19aa65b05731b (f: 1527083776.000000, d: 5.246431e-07)
21:07:52  v6 40c0000000000000 (f: 0.000000, d: 8.192000e+03)
21:07:52  v7 c0c0000000000000 (f: 0.000000, d: -8.192000e+03)
21:07:52  v8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v16 bfd0000000000000 (f: 0.000000, d: -2.500000e-01)
21:07:52  v17 3fd55cf5dfc75555 (f: 3754382592.000000, d: 3.337989e-01)
21:07:52  v18 bf5e8971a05ca5f1 (f: 2690426368.000000, d: -1.863824e-03)
21:07:52  v19 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
21:07:52  v20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  v31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:07:52  Module=/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Nightly/openjdkbinary/j2sdk-image/lib/default/libj9vm29.dylib
21:07:52  Module_base_address=0000000107000000 Symbol=_ZN26VM_BytecodeInterpreterFull3runEP10J9VMThread
21:07:52  Symbol_address=00000001070670D8
21:07:52  Target=2_90_20220622_85 (Mac OS X 11.4)
21:07:52  CPU=aarch64 (8 logical CPUs) (0x400000000 RAM)
21:07:52  ----------- Stack Backtrace -----------
21:07:52  ---------------------------------------
```

**Comment by knn-k** [comment]
This time I can read the core file with jdmpview.

`x8` is JavaVM, and `x21` is J9VMThread.

```
> !whatis 0x0120811A20
Found 0x0000000120811A20 as !j9javavm 0x120811a20
> !whatis 0x011C839100
Found 0x000000011C839100 as !j9vmthread 0x11c839100: !j9javavm 0x120811a20->j9ras->crashInfo->failingThread
```

**Comment by knn-k** [comment]
PC register points to somewhere in `runMethodHandle` in the bytecode interpreter.
Call stack of the failing thread looks like this.

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "ForkJoinPool.commonPool-worker-5" J9VMThread:0x000000011C839100, omrthread_t:0x000000011B822060, java/lang/Thread:0x00000002E016ADF8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1C, isDaemon:true)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x000000028004E4D8)
3XMTHREADINFO1            (native thread ID:0x9B5C626, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x000000016DF80000, to:0x000000016DFC3000, size:0x43000)
3XMCPUTIME               CPU usage total: 0.018823000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=69656 (0x11018)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/invoke/ArrayVarHandle$ArrayVarHandleOperations$OpObject.setRelease(ArrayVarHandle.java:194)
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool$WorkQueue.push(ForkJoinPool.java:847)
4XESTACKTRACE                at java/util/concurrent/ForkJoinTask.fork(ForkJoinTask.java:702)
4XESTACKTRACE                at java/util/stream/AbstractTask.compute(AbstractTask.java:324)
4XESTACKTRACE                at java/util/concurrent/CountedCompleter.exec(CountedCompleter.java:746)
4XESTACKTRACE                at java/util/concurrent/ForkJoinTask.doExec(ForkJoinTask.java:290)
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool.scan(ForkJoinPool.java:1656)
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool.runWorker(ForkJoinPool.java:1594)
4XESTACKTRACE                at java/util/concurrent/ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
3XMTHREADINFO3           No native callstack available for this thread
```

**Comment by knn-k** [comment]
We haven't seen this failure for a while.
I ran this test 40 times on AArch64 macOS with JDK 11, and got no failures.  https://openj9-jenkins.osuosl.org/job/Grinder/1293/
