### ISSUE TITLE
JDK19 java/util/logging/LogManager/Configuration/updateConfiguration/UpdateConfigurationTest.java - RuntimeException: Expected 'barRef' to be cleared

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15190]
Failure link
------------

From an internal build `view/Test_grinder/job/Grinder/24384/console`(`cent7-aarch64-5`):
```
12:44:45  openjdk version "19-internal" 2022-09-20
12:44:45  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
12:44:45  Eclipse OpenJ9 VM (build loom_patch-5264b46c002, JRE 19 Linux aarch64-64-Bit Compressed References 20220531_29 (JIT enabled, AOT enabled)
12:44:45  OpenJ9   - 5264b46c002
12:44:45  OMR      - e8fbaa89d50
12:44:45  JCL      - a66f9edf71a based on jdk-19+24)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=sanity&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F29%2FOpenJ9-JDKnext-aarch64_linux-20220531-212225.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F29%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=loomexcludes&ARTIFACTORY_NUM_ARTIFACTS=60&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=next&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
13:28:20  ===============================================
13:28:20  Running test jdk_util_0 ...
13:28:20  ===============================================
13:28:20  jdk_util_0 Start Time: Wed Jun  1 13:28:19 2022 Epoch Time (ms): 1654104499998
13:28:20  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
13:28:20  JVMSHRC005I No shared class caches available
13:28:20  JVMSHRC005I No shared class caches available
13:28:20  cache cleanup done
13:28:20  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
13:28:20  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

13:33:53  TEST: java/util/logging/LogManager/Configuration/updateConfiguration/UpdateConfigurationTest.java

13:33:53  java.lang.RuntimeException: java.lang.RuntimeException: Expected 'barRef' to be cleared
13:33:53  	at UpdateConfigurationTest.test(UpdateConfigurationTest.java:308)
13:33:53  	at UpdateConfigurationTest.test(UpdateConfigurationTest.java:545)
13:33:53  	at UpdateConfigurationTest$TestCase.run(UpdateConfigurationTest.java:85)
13:33:53  	at UpdateConfigurationTest.main(UpdateConfigurationTest.java:393)
13:33:53  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
13:33:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
13:33:53  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:33:53  	at java.base/java.lang.Thread.run(Thread.java:1555)
13:33:53  Caused by: java.lang.RuntimeException: Expected 'barRef' to be cleared
13:33:53  	at UpdateConfigurationTest.test(UpdateConfigurationTest.java:234)
13:33:53  	... 7 more
13:33:53  
13:33:53  JavaTest Message: Test threw exception: java.lang.RuntimeException: java.lang.RuntimeException: Expected 'barRef' to be cleared

13:40:53  jdk_util_0_FAILED
```
This is an intermittent failure, rely on GC behaviours, seems a test issue.

**Comment by pshipton** [comment]
Passing on a later build. I will un-exclude.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1001

**Comment by pshipton** [comment]
Actually just noticed it's intermittent, will run more iterations.

**Comment by pshipton** [comment]
78 tests passed (no failures) in https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1003
Running more testing in 
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1004
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1005

**Comment by pshipton** [comment]
All the grinders passed, re-including the test.
https://github.com/adoptium/aqa-tests/pull/3784

**Comment by JasonFengJ9** [comment]
[JDK19 x86-64_windows internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_1/92/)(`win11x86-rt3-1`)
```
[2023-04-08T20:57:02.578Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2023-04-08T20:57:02.578Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2023-04-08T21:39:52.779Z] TEST: java/util/logging/LogManager/Configuration/updateConfiguration/UpdateConfigurationTest.java

[2023-04-08T21:39:52.780Z] java.lang.RuntimeException: java.lang.RuntimeException: Expected 'barRef' to be cleared
[2023-04-08T21:39:52.780Z] 	at UpdateConfigurationTest.test(UpdateConfigurationTest.java:308)
[2023-04-08T21:39:52.780Z] 	at UpdateConfigurationTest.test(UpdateConfigurationTest.java:545)
[2023-04-08T21:39:52.780Z] 	at UpdateConfigurationTest$TestCase.run(UpdateConfigurationTest.java:85)
[2023-04-08T21:39:52.780Z] 	at UpdateConfigurationTest.main(UpdateConfigurationTest.java:393)
[2023-04-08T21:39:52.780Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-08T21:39:52.780Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-08T21:39:52.780Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-04-08T21:39:52.780Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2023-04-08T21:39:52.780Z] Caused by: java.lang.RuntimeException: Expected 'barRef' to be cleared
[2023-04-08T21:39:52.780Z] 	at UpdateConfigurationTest.test(UpdateConfigurationTest.java:234)
[2023-04-08T21:39:52.780Z] 	... 7 more
[2023-04-08T21:39:52.780Z] 
[2023-04-08T21:39:52.780Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: java.lang.RuntimeException: Expected 'barRef' to be cleared

[2023-04-08T21:39:52.780Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: java.lang.RuntimeException: Expected 'barRef' to be cleared
[2023-04-08T21:39:52.780Z] --------------------------------------------------
[2023-04-08T22:40:12.219Z] Test results: passed: 914; failed: 1
[2023-04-08T22:41:11.722Z] Report written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_1\aqa-tests\TKG\output_1680976237304\jdk_util_0\report\html\report.html
[2023-04-08T22:41:11.722Z] Results written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_1\aqa-tests\TKG\output_1680976237304\jdk_util_0\work
[2023-04-08T22:41:11.722Z] Error: Some tests failed or other problems occurred.
[2023-04-08T22:41:11.722Z] -----------------------------------
[2023-04-08T22:41:11.722Z] jdk_util_0_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32227/)

**Comment by pshipton** [comment]
The grinder passed.
