### ISSUE TITLE
LambdaLoadTest_J9_5m_1 Method "testRecursiveLambda" "testIndirectlyRecursive" not found

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15197]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_aarch64_linux_Nightly_testList_2/173 - [ub20-aarch64-osu-6](https://openj9-jenkins.osuosl.org/computer/ub20-aarch64-osu-6)
LambdaLoadTest_J9_5m_1 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`

```
LT  testStarted : testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaRecursive)
LT  testFinished: testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaRecursive)
LT  testStarted : testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
LT  testFailure: testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces): Method "testRecursiveLambda" not found
LT  junit.framework.AssertionFailedError: Method "testRecursiveLambda" not found
LT  	at junit.framework.Assert.fail(Assert.java:57)
LT  	at junit.framework.TestCase.fail(TestCase.java:227)
LT  	at junit.framework.TestCase.runTest(TestCase.java:169)
LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
LT  	at junit.framework.TestResult.run(TestResult.java:125)
LT  	at junit.framework.TestCase.run(TestCase.java:129)
LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:827)
LT  testFinished: testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
LT  testStarted : testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
LT  testFailure: testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces): Method "testIndirectlyRecursive" not found
LT  junit.framework.AssertionFailedError: Method "testIndirectlyRecursive" not found
LT  	at junit.framework.Assert.fail(Assert.java:57)
LT  	at junit.framework.TestCase.fail(TestCase.java:227)
LT  	at junit.framework.TestCase.runTest(TestCase.java:169)
LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
LT  	at junit.framework.TestResult.run(TestResult.java:125)
LT  	at junit.framework.TestCase.run(TestCase.java:129)
LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:827)
LT  testFinished: testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
```

Maybe related to the new alinux machines just installed.

**Comment by JasonFengJ9** [comment]
[An internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/291/)(`ubu22ppclert-3`)
```
penjdk version "1.8.0_342"
IBM Semeru Runtime Open Edition (build 1.8.0_342-b06)
Eclipse OpenJ9 VM (build master-e70b78378, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20220722_411 (JIT enabled, AOT enabled)
OpenJ9   - e70b78378
OMR      - 6061e7ce4
JCL      - 4cb47cd7a based on jdk8u342-b06)

[2022-07-23T07:30:05.697Z] variation: Mode501
[2022-07-23T07:30:05.697Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 

[2022-07-23T07:31:11.446Z] LT  07:31:07.853 - Completed 20.0%. Number of tests started=3266 (+1180)
[2022-07-23T07:31:11.446Z] LT  07:31:08.372 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
[2022-07-23T07:31:11.446Z] LT  07:31:08.418 - suite.getInventory().getInventoryFileRef(): openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
[2022-07-23T07:31:11.446Z] LT  07:31:08.419 - suite.isCreateDump() : false
[2022-07-23T07:31:11.446Z] LT  07:31:08.419 - Test failed
[2022-07-23T07:31:11.446Z] LT    Failure num.  = 1
[2022-07-23T07:31:11.446Z] LT    Test number   = 10
[2022-07-23T07:31:11.446Z] LT    Test details  = 'JUnit[net.adoptopenjdk.test.lambda.TestLambdaRecursive]'
[2022-07-23T07:31:11.446Z] LT    Suite number  = 0
[2022-07-23T07:31:11.446Z] LT    Thread number = 0
[2022-07-23T07:31:11.446Z] LT  >>> Captured test output >>>
[2022-07-23T07:31:11.446Z] LT  testStarted : testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2022-07-23T07:31:11.446Z] LT  testFailure: testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testDeepRecursiveLambda" not found
[2022-07-23T07:31:11.446Z] LT  junit.framework.AssertionFailedError: Method "testDeepRecursiveLambda" not found
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.Assert.fail(Assert.java:57)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.fail(TestCase.java:227)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.runTest(TestCase.java:169)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestResult.run(TestResult.java:125)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.run(TestCase.java:129)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-07-23T07:31:11.446Z] LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2022-07-23T07:31:11.446Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-07-23T07:31:11.446Z] LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-07-23T07:31:11.446Z] LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-07-23T07:31:11.446Z] LT  	at java.lang.Thread.run(Thread.java:826)
[2022-07-23T07:31:11.446Z] LT  testFinished: testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2022-07-23T07:31:11.446Z] LT  testStarted : testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2022-07-23T07:31:11.446Z] LT  testFailure: testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testRecursiveLambda" not found
[2022-07-23T07:31:11.446Z] LT  junit.framework.AssertionFailedError: Method "testRecursiveLambda" not found
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.Assert.fail(Assert.java:57)

[2022-07-23T07:31:11.446Z] LT  testStarted : testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2022-07-23T07:31:11.446Z] LT  testFailure: testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testIndirectlyRecursive" not found
[2022-07-23T07:31:11.446Z] LT  junit.framework.AssertionFailedError: Method "testIndirectlyRecursive" not found
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.Assert.fail(Assert.java:57)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.fail(TestCase.java:227)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.runTest(TestCase.java:169)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestResult.run(TestResult.java:125)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestCase.run(TestCase.java:129)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2022-07-23T07:31:11.446Z] LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
[2022-07-23T07:31:11.446Z] LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-07-23T07:31:11.447Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-07-23T07:31:11.447Z] LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2022-07-23T07:31:11.447Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-07-23T07:31:11.447Z] LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-07-23T07:31:11.447Z] LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-07-23T07:31:11.447Z] LT  	at java.lang.Thread.run(Thread.java:826)
[2022-07-23T07:31:11.447Z] LT  testFinished: testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2022-07-23T07:31:11.447Z] LT  
[2022-07-23T07:31:11.447Z] LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaRecursive
[2022-07-23T07:31:11.447Z] LT    Ran    : 3
[2022-07-23T07:31:11.447Z] LT    Passed : 0
[2022-07-23T07:31:11.447Z] LT    Failed : 3
[2022-07-23T07:31:11.447Z] LT    Ignored: 0
[2022-07-23T07:31:11.447Z] LT    Result : FAILED
[2022-07-23T07:31:11.447Z] LT  <<<

[2022-07-23T07:32:27.118Z] LambdaLoadTest_special_J9_5m_12_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK8 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.system_aarch64_linux_testList_0/488/)(`ubu22-aarch64-5`)
```
openjdk version "1.8.0_392-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_392-beta-202310280236-b08)
Eclipse OpenJ9 VM (build master-7498dc04c, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20231028_761 (JIT enabled, AOT enabled)
OpenJ9   - 7498dc04c
OMR      - 386a7080f
JCL      - 98ed2db7d based on jdk8u392-b08)

[2023-10-28T04:42:50.104Z] variation: -Xgcpolicy:gencon -Xgc:concurrentScavenge
[2023-10-28T04:42:50.104Z] JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:concurrentScavenge 

[2023-10-28T04:42:57.382Z] LT  04:42:56.867 - Starting thread. Suite=0 thread=5
[2023-10-28T04:43:05.211Z] LT  04:43:03.928 - First failure detected by thread: load-3. Not creating dumps as no dump generation is requested for this load test
[2023-10-28T04:43:05.211Z] LT  04:43:04.018 - suite.getInventory().getInventoryFileRef(): openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
[2023-10-28T04:43:05.211Z] LT  04:43:04.018 - suite.isCreateDump() : false
[2023-10-28T04:43:05.211Z] LT  04:43:04.018 - Test failed
[2023-10-28T04:43:05.211Z] LT    Failure num.  = 1
[2023-10-28T04:43:05.211Z] LT    Test number   = 10
[2023-10-28T04:43:05.211Z] LT    Test details  = 'JUnit[net.adoptopenjdk.test.lambda.TestLambdaRecursive]'
[2023-10-28T04:43:05.211Z] LT    Suite number  = 0
[2023-10-28T04:43:05.211Z] LT    Thread number = 3
[2023-10-28T04:43:05.211Z] LT  >>> Captured test output >>>
[2023-10-28T04:43:05.211Z] LT  testStarted : testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaRecursive)
[2023-10-28T04:43:05.211Z] LT  testFinished: testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaRecursive)
[2023-10-28T04:43:05.211Z] LT  testStarted : testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2023-10-28T04:43:05.211Z] LT  testFailure: testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testRecursiveLambda" not found
[2023-10-28T04:43:05.211Z] LT  junit.framework.AssertionFailedError: Method "testRecursiveLambda" not found
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.Assert.fail(Assert.java:57)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestCase.fail(TestCase.java:227)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestCase.runTest(TestCase.java:169)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestResult.run(TestResult.java:125)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestCase.run(TestCase.java:129)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2023-10-28T04:43:05.211Z] LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2023-10-28T04:43:05.211Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2023-10-28T04:43:05.212Z] LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2023-10-28T04:43:05.212Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2023-10-28T04:43:05.212Z] LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-10-28T04:43:05.212Z] LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-10-28T04:43:05.212Z] LT  	at java.lang.Thread.run(Thread.java:826)
[2023-10-28T04:43:05.212Z] LT  testFinished: testRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2023-10-28T04:43:05.212Z] LT  testStarted : testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2023-10-28T04:43:05.212Z] LT  testFailure: testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testIndirectlyRecursive" not found
[2023-10-28T04:43:05.212Z] LT  junit.framework.AssertionFailedError: Method "testIndirectlyRecursive" not found
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.Assert.fail(Assert.java:57)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestCase.fail(TestCase.java:227)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestCase.runTest(TestCase.java:169)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestResult.run(TestResult.java:125)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestCase.run(TestCase.java:129)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2023-10-28T04:43:05.212Z] LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2023-10-28T04:43:05.212Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2023-10-28T04:43:05.212Z] LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2023-10-28T04:43:05.212Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2023-10-28T04:43:05.212Z] LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-10-28T04:43:05.212Z] LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-10-28T04:43:05.212Z] LT  	at java.lang.Thread.run(Thread.java:826)
[2023-10-28T04:43:05.212Z] LT  testFinished: testIndirectlyRecursive(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2023-10-28T04:43:05.212Z] LT  
[2023-10-28T04:43:05.212Z] LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaRecursive
[2023-10-28T04:43:05.212Z] LT    Ran    : 3
[2023-10-28T04:43:05.212Z] LT    Passed : 1
[2023-10-28T04:43:05.212Z] LT    Failed : 2
[2023-10-28T04:43:05.212Z] LT    Ignored: 0
[2023-10-28T04:43:05.212Z] LT    Result : FAILED
[2023-10-28T04:43:05.212Z] LT  <<<

[2023-10-28T04:43:12.155Z] LambdaLoadTest_CS_5m_0_FAILED
```

**Comment by knn-k** [comment]
I ran a 30x Grinder job for LambdaLoadTest_CS_5m_0, and got no failures: job/Grinder/35731/
