### ISSUE TITLE
jdk_security3_1_FAILED sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java java timed out 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15203]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/59/`(`ub18-aarch64-6`):
```
openjdk version "17.0.4" 2022-07-19
IBM Semeru Runtime Open Edition 17.0.4.0-m1 (build 17.0.4+3)
Eclipse OpenJ9 VM 17.0.4.0-m1 (build v0.33.0-release-c9a377390, JRE 17 Linux aarch64-64-Bit Compressed References 20220601_180 (JIT enabled, AOT enabled)
OpenJ9   - c9a377390
OMR      - 942daf672
JCL      - 02c2140051b based on jdk-17.0.4+3)
```
[Rerun in Grinder]([Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F180%2Fibm-semeru-open-debugimage_aarch64_linux_17.0.4_3_openj9-0.33.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F180%2Fibm-semeru-open-jdk_aarch64_linux_17.0.4_3_openj9-0.33.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F180%2Fibm-semeru-open-jre_aarch64_linux_17.0.4_3_openj9-0.33.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F180%2Fibm-semeru-open-testimage_aarch64_linux_17.0.4_3_openj9-0.33.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=v0.33.0-release&amp;OPENJ9_BRANCH=v0.33.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.33.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None)) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-06-01T18:00:19.146Z] variation: Mode150
[2022-06-01T18:00:19.146Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-06-01T18:27:35.880Z] TEST: sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java

[2022-06-01T18:27:35.882Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 961196ms).
[2022-06-01T18:27:35.882Z] --------------------------------------------------
[2022-06-01T18:28:11.849Z] TEST: sun/security/provider/SecureRandom/StrongSecureRandom.java

[2022-06-01T18:28:11.851Z] TEST RESULT: Error. Agent error: java.lang.Exception: Agent 16 timed out with a timeout of 960 seconds; check console log for any additional details
[2022-06-01T18:28:11.851Z] --------------------------------------------------
[2022-06-01T18:43:57.696Z] Test results: passed: 825; error: 2
[2022-06-01T18:44:10.413Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/jvmtest/openjdk/report/html/report.html
[2022-06-01T18:44:10.413Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16541021307551/jdk_security3_0/work
[2022-06-01T18:44:10.413Z] Error: Some tests failed or other problems occurred.
[2022-06-01T18:44:10.413Z] 
[2022-06-01T18:44:10.413Z] jdk_security3_0_FAILED
```
50x grinder w/ `sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java` - `job/Grinder/24476/` - 18/100 failed
50x grinder w/ `sun/security/provider/SecureRandom/StrongSecureRandom.java` - `job/Grinder/24478/` - all passed
This might be related to https://github.com/eclipse-openj9/openj9/issues/15164

**Comment by JasonFengJ9** [comment]
The timed out occurred at a different test on `x86-64_linux`
```
openjdk version "17.0.4" 2022-07-19
IBM Semeru Runtime Open Edition 17.0.4.0-m1 (build 17.0.4+3)
Eclipse OpenJ9 VM 17.0.4.0-m1 (build v0.33.0-release-c9a377390, JRE 17 Linux amd64-64-Bit Compressed References 20220601_207 (JIT enabled, AOT enabled)
OpenJ9   - c9a377390
OMR      - 942daf672
JCL      - 02c2140051b based on jdk-17.0.4+3)
```

`job/Test_openjdk17_j9_extended.openjdk_x86-64_linux/62/`(`ub18x64rt1-4`)
```
[2022-06-01T19:36:46.879Z] Running test jdk_security3_1 ...
[2022-06-01T19:36:46.879Z] ===============================================
[2022-06-01T19:36:46.879Z] variation: Mode650
[2022-06-01T19:36:46.879Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-06-01T20:02:07.412Z] TEST: javax/net/ssl/SSLEngine/LargePacket.java

[2022-06-01T20:02:07.414Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960809ms).
[2022-06-01T20:02:07.414Z] --------------------------------------------------
[2022-06-01T21:03:17.333Z] Test results: passed: 826; error: 1
[2022-06-01T21:03:52.022Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2022-06-01T21:03:52.022Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_1654100499432/jdk_security3_1/work
[2022-06-01T21:03:52.022Z] Error: Some tests failed or other problems occurred.
[2022-06-01T21:03:52.022Z] 
[2022-06-01T21:03:52.022Z] jdk_security3_1_FAILED
```
50x grinder - `job/Grinder/24482/`

**Comment by pshipton** [comment]
Re sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java
The grinder only failed on one machine ub18-aarch64-9, on the others ub18-aarch64-3, cent7-aarch64-3, cent7-aarch64-2 it passed.

Test duration on the passing machines is less than 2 min for 20 iterations.

The test seems to hang reading a file
```
21:26:55  "MainThread" prio=5 Id=26 RUNNABLE
21:26:55  	at java.base@17.0.4/java.io.FileInputStream.readBytes(Native Method)
21:26:55  	at java.base@17.0.4/java.io.FileInputStream.read(FileInputStream.java:276)
21:26:55  	at java.base@17.0.4/java.io.FilterInputStream.read(FilterInputStream.java:132)
21:26:55  	at java.base@17.0.4/sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:544)
21:26:55  	at java.base@17.0.4/sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
21:26:55  	at java.base@17.0.4/sun.security.provider.AbstractDrbg.lambda$static$0(AbstractDrbg.java:524)
21:26:55  	at java.base@17.0.4/sun.security.provider.AbstractDrbg.getEntropyInput(AbstractDrbg.java:507)
21:26:55  	at java.base@17.0.4/sun.security.provider.AbstractDrbg.getEntropyInput(AbstractDrbg.java:494)
21:26:55  	at java.base@17.0.4/sun.security.provider.AbstractDrbg.engineNextBytes(AbstractDrbg.java:386)
21:26:55  	- locked sun.security.provider.S$Impl3@30363bb3
21:26:55  	at java.base@17.0.4/sun.security.provider.S.engineNextBytes(S.java:138)
21:26:55  	at java.base@17.0.4/java.security.SecureRandom.nextBytes(SecureRandom.java:789)
21:26:55  	- locked java.security.SecureRandom@e43d7458
21:26:55  	at app//SpecTest.main(SpecTest.java:120)
```

Check if it's still recreatable on this machine /job/Grinder/24528/

**Comment by pshipton** [comment]
The security random source is configured as follows, this appears to be a machine issue.
`securerandom.source=file:/dev/random`

A simple test is `cat /dev/random` which should print a bunch of garbage, and not hang.
We've identified two machines with problems so far, but there could be more: ub18-aarch64-6, ub18-aarch64-9
@AdamBrousseau

**Comment by pshipton** [comment]
Closing in favour of runtimes/infrastructure/issues/6957
