### ISSUE TITLE
J9 crashed under latest JDK8 and JDK11

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#15212]
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Windows 10:

```
Microsoft Windows 10 Professional
10.0.19044 Build 19044
AMD Ryzen 5 5600G with Radeon Graphics 3.90 GHz
Memory 32 GB
```

Java -version output under Windows 10

```
openjdk version "1.8.0_332-internal"
OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_05_01_00_39-b00)
Eclipse OpenJ9 VM (build master-d5f1557, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220501_000000 (JIT enabled, AOT enabled)
OpenJ9   - d5f1557
OMR      - 81b7940
JCL      - 16aeb67 based on jdk8u332-b09)
```

```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-56fe4ec, JRE 11 Linux amd64-64-Bit Compressed References 20220424_000000 (JIT enabled, AOT enabled)
OpenJ9   - 56fe4ec
OMR      - db8e957
JCL      - 3a97e78 based on jdk-11.0.15+10)
```

```
openjdk version "1.8.0_342-internal"
OpenJDK Runtime Environment (build 1.8.0_342-internal-_2022_06_03_02_50-b00)
Eclipse OpenJ9 VM (build master-6335127, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220603_000000 (JIT enabled, AOT enabled)
OpenJ9   - 6335127
OMR      - ca03f92
JCL      - bd90446 based on jdk8u342-b04)
```

## Problem summary

This test case is a modification on the #15196 issue. We found that the test case submitted by #15196 could not be triggered in the JDK8U332 version, so we changed the number of loops for the #15196 test case. And running the test case with JDK8U332 and JDK-11.0.15 +10 produces the following report. In addition, in order to verify whether it has been fixed by the latest version, we also use JDK8U342 to test it, and crash will also occur.

```java
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/06/03 11:07:09 - please wait.
JVMDUMP032I JVM requested System dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/core.20220603.110709.90489.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.90531.

JVMDUMP010I System dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/core.20220603.110709.90489.0001.dmp
JVMDUMP032I JVM requested Heap dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/heapdump.20220603.110709.90489.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/heapdump.20220603.110709.90489.0002.phd
JVMDUMP032I JVM requested Java dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/javacore.20220603.110709.90489.0003.txt' in response to an event
JVMDUMP010I Java dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/javacore.20220603.110709.90489.0003.txt
JVMDUMP032I JVM requested Snap dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/Snap.20220603.110709.90489.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/Snap.20220603.110709.90489.0004.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:267)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
	at java.util.ArrayList.add(ArrayList.java:464)
	at TestMarkChecker.getMarker(JDK_8043354.TestMarkChecker_0302@1654093117273.jasm)
	at TestMarkChecker.visit(JDK_8043354.TestMarkChecker_0302@1654093117273.jasm
```
## Attachment
[test.zip](https://github.com/eclipse-openj9/openj9/files/8829720/test.zip)

**Comment by pshipton** [comment]
I expect the OOM is normal, Hotspot has the same behaviour. I don't see anything to investigate, is there something I'm missing?

**Comment by JavaTailor** [comment]
> I expect the OOM is normal, Hotspot has the same behaviour. I don't see anything to investigate, is there something I'm missing?

When we tested the test cases, although J9 had the same behavior as Hotspot, we found that J9 generated crash files, which we thought might represent a relatively serious defect.

**Comment by pshipton** [comment]
If you are talking about the following, this is normal for an OOM so the OOM can be investigated. They could be turned off via command line options for any user that doesn't desire this default behavior.

```
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/06/03 11:07:09 - please wait.
JVMDUMP032I JVM requested System dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/core.20220603.110709.90489.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.90531.

JVMDUMP010I System dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/core.20220603.110709.90489.0001.dmp
JVMDUMP032I JVM requested Heap dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/heapdump.20220603.110709.90489.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/heapdump.20220603.110709.90489.0002.phd
JVMDUMP032I JVM requested Java dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/javacore.20220603.110709.90489.0003.txt' in response to an event
JVMDUMP010I Java dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/javacore.20220603.110709.90489.0003.txt
JVMDUMP032I JVM requested Snap dump using '/home/ningmo/Fasttailor/class_valid/TestCase/test/Snap.20220603.110709.90489.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /home/ningmo/Fasttailor/class_valid/TestCase/test/Snap.20220603.110709.90489.0004.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
```

**Comment by JavaTailor** [comment]
Thank you very much for your reply. We will pay attention to this behavior in the future.
