### ISSUE TITLE
jdk_security3_0_FAILED InvalidKeyException: Key must not be null & KeyStoreException: Cannot store non-PrivateKeys

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15221]
Failure link
------------

From an internal build `job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/64/`(`ub20x64rt1-3`):
```
openjdk version "1.8.0_342"
IBM Semeru Runtime Open Edition (build 1.8.0_342-b03)
Eclipse OpenJ9 VM (build v0.33.0-release-bf978d503, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220602_396 (JIT enabled, AOT enabled)
OpenJ9   - bf978d503
OMR      - e7d85499b
JCL      - b43a04972a based on jdk8u342-b03)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F396%2Fibm-semeru-open-jre_x64_linux_8u342b03_openj9-0.33.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F396%2Fibm-semeru-open-jdk_x64_linux_8u342b03_openj9-0.33.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F396%2Fibm-semeru-open-testimage_x64_linux_8u342b03_openj9-0.33.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F396%2Fibm-semeru-open-debugimage_x64_linux_8u342b03_openj9-0.33.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=v0.33.0-release&amp;OPENJ9_BRANCH=v0.33.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.33.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-06-02T20:13:58.406Z] Running test jdk_security3_0 ...
[2022-06-02T20:13:58.406Z] ===============================================
[2022-06-02T20:13:58.406Z] jdk_security3_0 Start Time: Thu Jun  2 13:13:58 2022 Epoch Time (ms): 1654200838176

[2022-06-02T20:13:58.406Z] variation: Mode150
[2022-06-02T20:13:58.406Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-06-02T20:22:59.925Z] TEST: sun/security/pkcs11/Secmod/GetPrivateKey.java

[2022-06-02T20:22:59.926Z] STDERR:
[2022-06-02T20:22:59.926Z] java.security.InvalidKeyException: Key must not be null
[2022-06-02T20:22:59.926Z] 	at sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:119)
[2022-06-02T20:22:59.926Z] 	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:111)
[2022-06-02T20:22:59.926Z] 	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:103)
[2022-06-02T20:22:59.926Z] 	at java.security.Signature$Delegate.tryOperation(Signature.java:1286)
[2022-06-02T20:22:59.926Z] 	at java.security.Signature$Delegate.chooseProvider(Signature.java:1234)
[2022-06-02T20:22:59.926Z] 	at java.security.Signature$Delegate.engineInitSign(Signature.java:1332)
[2022-06-02T20:22:59.926Z] 	at java.security.Signature.initSign(Signature.java:621)
[2022-06-02T20:22:59.926Z] 	at GetPrivateKey.main(GetPrivateKey.java:79)
[2022-06-02T20:22:59.926Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-06-02T20:22:59.926Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-06-02T20:22:59.926Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-06-02T20:22:59.926Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-06-02T20:22:59.926Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-06-02T20:22:59.926Z] 	at java.lang.Thread.run(Thread.java:827)
[2022-06-02T20:22:59.926Z] 
[2022-06-02T20:22:59.926Z] JavaTest Message: Test threw exception: java.security.InvalidKeyException: Key must not be null

[2022-06-02T20:22:59.926Z] TEST: sun/security/pkcs11/Secmod/JksSetPrivateKey.java

[2022-06-02T20:22:59.927Z] STDERR:
[2022-06-02T20:22:59.927Z] java.security.KeyStoreException: Cannot store non-PrivateKeys
[2022-06-02T20:22:59.927Z] java.lang.IllegalArgumentException: Private key must be accompanied by certificate chain
[2022-06-02T20:22:59.927Z] 	at java.security.KeyStore.setKeyEntry(KeyStore.java:1136)
[2022-06-02T20:22:59.927Z] 	at JksSetPrivateKey.main(JksSetPrivateKey.java:86)
[2022-06-02T20:22:59.927Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-06-02T20:22:59.927Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-06-02T20:22:59.927Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-06-02T20:22:59.927Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-06-02T20:22:59.927Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-06-02T20:22:59.927Z] 	at java.lang.Thread.run(Thread.java:827)
[2022-06-02T20:22:59.927Z] 
[2022-06-02T20:22:59.927Z] JavaTest Message: Test threw exception: java.lang.IllegalArgumentException: Private key must be accompanied by certificate chain

[2022-06-02T21:07:52.131Z] Test results: passed: 603; failed: 2
[2022-06-02T21:07:52.131Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2022-06-02T21:07:52.131Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16541956331725/jdk_security3_0/work
[2022-06-02T21:07:52.131Z] Error: Some tests failed or other problems occurred.
[2022-06-02T21:07:52.131Z] 
[2022-06-02T21:07:52.131Z] jdk_security3_0_FAILED
```
50x grinder - `job/Grinder/24536/` & `job/Grinder/24537/`

**Comment by pshipton** [comment]
These failures are occurring in the 0.33 M2 build, in both jdk_security3_0 and jdk_security3_1, on the same machine ub20x64rt1-3.
/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/70/

Trying a single re-run of jdk_security3_0 in a grinder /job/Grinder/25726

**Comment by pshipton** [comment]
@alon-sh any ideas about these failures? They only seem to fail when the entire group jdk_security3 is run.

**Comment by JasonFengJ9** [comment]
[sun/security/pkcs11/KeyStore/SecretKeysBasic.sh failed with "PKCS11Exception: CKR_ATTRIBUTE_SENSITIVE"](https://bugs.openjdk.org/browse/JDK-8209398)
This test has been excluded for RI JDK8 - https://github.com/adoptium/aqa-tests/blob/55ffc854ffd54cd3ecca6b838a6d4ba3aea0440e/openjdk/excludes/ProblemList_openjdk8.txt#L295

RI JDK8 failed `sun/security/pkcs11/Secmod/GetPrivateKey.java` & `sun/security/pkcs11/Secmod/JksSetPrivateKey.java` as well - `job/Grinder/25733/console`

Will create exclude PR.

**Comment by pshipton** [comment]
Created https://github.ibm.com/runtimes/infrastructure/issues/7098
