### ISSUE TITLE
JDK19: Address threadgroup jvmti failures

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15244]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/113/consoleFull

```
03:53:05  Testing: gtgc001
03:53:05  Test start time: 2022/06/06 04:53:04 Atlantic Standard Time
03:53:05  Running command: "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xshareclasses:name=bcienabled,enableBCI -Xnocompressedrefs  -Xdump    -agentlib:jvmtitest=test:gtgc001 -cp "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
03:53:05  Time spent starting: 4 milliseconds
03:53:05  Time spent executing: 567 milliseconds
03:53:05  Test result: FAILED
03:53:05  Output from test:
03:53:05   [OUT] *** Testing [1/1]:	testThreadGroupAssignment
03:53:05   [OUT] *** Test took 7 milliseconds
03:53:05   [OUT] FAILED
03:53:05   [OUT] 
03:53:05   [ERR] exception thrown: 
03:53:05   [ERR] type: 2	Error: 11  JVMTI_ERROR_INVALID_THREAD_GROUP
03:53:05   [ERR] 		Failed to GetThreadGroupChildren
03:53:05   [ERR] 		Location: /home/jenkins/workspace/Build_JDKnext_x86-64_linux_OpenJDK/openj9/runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/getThreadGroupChildren/gtgc001.c -> [Java_com_ibm_jvmti_tests_getThreadGroupChildren_gtgc001_checkAssignment():66]
03:53:05   [ERR] 
03:53:05   [ERR] com.ibm.jvmti.tests.util.AgentHardException: 
03:53:05   [ERR] type: 2	Error: 11  JVMTI_ERROR_INVALID_THREAD_GROUP
03:53:05   [ERR] 		Failed to GetThreadGroupChildren
03:53:05   [ERR] 		Location: /home/jenkins/workspace/Build_JDKnext_x86-64_linux_OpenJDK/openj9/runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/getThreadGroupChildren/gtgc001.c -> [Java_com_ibm_jvmti_tests_getThreadGroupChildren_gtgc001_checkAssignment():66]
03:53:05   [ERR] 
03:53:05   [ERR] 	at com.ibm.jvmti.tests.util.ErrorControl.checkErrors(ErrorControl.java:71)
03:53:05   [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:87)
03:53:05   [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
03:53:05  >> Success condition was not found: [Return code: 0]
```

**Comment by tajila** [comment]
@babsingh Can you please take a look at this as well

**Comment by tajila** [comment]
It is possible that the test is invalid for JDK19 but we should confirm that

**Comment by babsingh** [comment]
Removing the `test excluded` label since `gtgc001` has been re-enabled.
