### ISSUE TITLE
Linux PPC FVT_Serviceability.jvmti.xdump_catch Test should have finished by now, killing it

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15243]
Internal PT /problem.php?cmd=update&problem_id=19571&build_id=30242
Example failure /job_output.php?id=35868711

Started failing in ibuild /build_info.php?build_id=30201 where https://github.com/eclipse-openj9/openj9/pull/15227 was the only change.

Failing output:
```
>> 2022 Mon Jun 6 22:38:04 Reference Test Starting
>> 2022 Mon Jun 6 22:38:04 Setting JAVA_DUMP_OPTS to ONERROR(ALL) ONEXCEPTION(ALL) ONDUMP(JAVADUMP)
>> 2022 Mon Jun 6 22:38:04 Starting process (java -classpath '/bluebird/javatest/HEAD_382595/test/SVT/ras/tools' -Xnocompressedrefs -agentpath:'/bluebird/javatest/HEAD_382595/test/SVT/ras/tools/native/bin/80/linux_ppc-64'/libxdump_event_generator.so -agentpath:'/bluebird/builds/bld_30242/jvmtest/VM/ras/jvmti/scripts/../native/bin/linux_ppc-64'/libxdump_events_test.so=0 -Xdump:console:events=catch,range=1..1 -Xdump:heap:events=catch,range=1..1,file=/tmp/bld_30242/jvmti.xdump_catch/35868711/rhel7p7vm11-jvmti_xdump-m121-20220606-223744/catch_Reference/expected_dumps/heapdump.%seq.%Y%m%d.%H%M%S.%pid.phd -Xdump:java:events=catch,range=1..1,file=/tmp/bld_30242/jvmti.xdump_catch/35868711/rhel7p7vm11-jvmti_xdump-m121-20220606-223744/catch_Reference/expected_dumps/javacore.%seq.%Y%m%d.%H%M%S.%pid.txt -Xdump:system:events=catch,range=1..1,file=/tmp/bld_30242/jvmti.xdump_catch/35868711/rhel7p7vm11-jvmti_xdump-m121-20220606-223744/catch_Reference/expected_dumps/core.%seq.%Y%m%d.%H%M%S.%pid.dmp -Xdump:snap:events=catch,range=1..1,file=/tmp/bld_30242/jvmti.xdump_catch/35868711/rhel7p7vm11-jvmti_xdump-m121-20220606-223744/catch_Reference/expected_dumps/Snap.%seq.%Y%m%d.%H%M%S.%pid.trc tests.com.ibm.jtc.ras.util.XDumpEventGenerator catch)
>> 2022 Mon Jun 6 22:38:04 Started process
>> 2022 Mon Jun 6 22:53:05 /tmp/bld_30242/jvmti.xdump_catch/35868711/rhel7p7vm11-jvmti_xdump-m121-20220606-223744/results.log
>> 2022 Mon Jun 6 22:53:05 Test should have finished by now, killing it (runtime set to 0 mins, exittime set to 15 mins)
```

Output from successful run:
```
>> 2012 Tue Oct 2 19:27:52 Reference Test Starting
>> 2012 Tue Oct 2 19:27:52 Setting JAVA_DUMP_OPTS to ONERROR(ALL) ONEXCEPTION(ALL) ONDUMP(JAVADUMP)
>> 2012 Tue Oct 2 19:27:52 Starting process (java -classpath '/bluebird/javatest/HEAD_382595/test/SVT/ras/tools' -Xnocompressedrefs -agentpath:'/bluebird/javatest/HEAD_382595/test/SVT/ras/tools/native/bin/80/linux_ppc-64'/libxdump_event_generator.so -agentpath:'/bluebird/builds/bld_30242/jvmtest/VM/ras/jvmti/scripts/../native/bin/linux_ppc-64'/libxdump_events_test.so=0 -Xdump:console:events=catch,range=1..1 -Xdump:heap:events=catch,range=1..1,file=/tmp/bld_30276/jvmti.xdump_catch/35910434/prhel035-jvmti_xdump-m121-20121002-192732/catch_Reference/expected_dumps/heapdump.%seq.%Y%m%d.%H%M%S.%pid.phd -Xdump:java:events=catch,range=1..1,file=/tmp/bld_30276/jvmti.xdump_catch/35910434/prhel035-jvmti_xdump-m121-20121002-192732/catch_Reference/expected_dumps/javacore.%seq.%Y%m%d.%H%M%S.%pid.txt -Xdump:system:events=catch,range=1..1,file=/tmp/bld_30276/jvmti.xdump_catch/35910434/prhel035-jvmti_xdump-m121-20121002-192732/catch_Reference/expected_dumps/core.%seq.%Y%m%d.%H%M%S.%pid.dmp -Xdump:snap:events=catch,range=1..1,file=/tmp/bld_30276/jvmti.xdump_catch/35910434/prhel035-jvmti_xdump-m121-20121002-192732/catch_Reference/expected_dumps/Snap.%seq.%Y%m%d.%H%M%S.%pid.trc tests.com.ibm.jtc.ras.util.XDumpEventGenerator catch)
>> 2012 Tue Oct 2 19:27:52 Started process

>> 2012 Tue Oct 2 19:29:02 check for undetected javacore files. Looking in the logdir
>> 2012 Tue Oct 2 19:29:02 check for undetected javacore files. Looking in the coredir
>> 2012 Tue Oct 2 19:29:02 check for undetected core files
>> 2012 Tue Oct 2 19:29:02 check for undetected heap files
>> 2012 Tue Oct 2 19:29:02 Archiving Trace
>> 2012 Tue Oct 2 19:29:02 archiveTraceFiles: logdir is /tmp/bld_30276/jvmti.xdump_catch/35910434/prhel035-jvmti_xdump-m121-20121002-192732/catch_Reference
>> 2012 Tue Oct 2 19:29:02 archiveTraceFiles: tracedir is /tmp/bld_30276/jvmti.xdump_catch/35910434/prhel035-jvmti_xdump-m121-20121002-192732/catch_Reference/trace-121002-192732
>> 2012 Tue Oct 2 19:29:02   Console Output Detected
>> 2012 Tue Oct 2 19:29:02   Heapdump File Detected
>> 2012 Tue Oct 2 19:29:02   Javacore File Detected
>> 2012 Tue Oct 2 19:29:02   Core File Detected
```

@gacholio @amicic
@tajila @keithc-ca fyi

**Comment by amicic** [comment]
Relatively simple scenario (no HCR/safepoint involved). T9 just completed GC for RAS dump, and is blocked likely to be inspected, while T3 is (unexpectedly) blocked to inspect T9

```
Thread 9 (Thread 0x3fff8a07f1b0 (LWP 11186)):
#0  0x00003fff8a4c285c in .pthread_cond_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff894f2bf4 in .IPRA.$monitor_wait_original () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#2  0x00003fff894f1510 in .omrthread_monitor_wait () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#3  0x00003fff895eb208 in internalAcquireVMAccessNoMutexWithMask (vmThread=0x0, haltMask=70365687119912) at VMAccess.cpp:386
#4  0x00003fff895ef538 in internalAcquireVMAccessNoMutex (vmThread=0x3fff88c8fe98 <._ZN7MM_Heap20systemGarbageCollectEP18MM_EnvironmentBasej+24>) at VMAccess.cpp:407
#5  0x00003fff895eaca4 in internalAcquireVMAccess (currentThread=0x1) at ../oti/VMAccess.hpp:128
#6  0x00003fff88b27814 in j9gc_modron_global_collect_with_overrides (vmThread=0x3fff8a07c7e0, gcCode=16383) at modronapi.cpp:95
#7  0x00003fff8921444c in prepareForDump (vm=0x3fff89865900 <_$STATIC_BSS+2784>, agent=0x3fff8925b230 <protectedDumpFunction>, context=0x3fff8a07c988, state=70366750023224) at trigger.c:675
#8  0x00003fff891e98b8 in runDumpAgent (vm=0x3fff89198a18 <javaTrace>, agent=0xffffc00082d551a4, context=0x1174b7880d6a2e, state=0x2700000027, detail=0x3fff8923989c <.const_dr+1068> "catch", timeNow=32) at dmpagent.c:2728
#9  0x00003fff89215360 in triggerDumpAgents (vm=0x3fff8a07d370, self=0x3fff84059748, eventFlags=70366764979072, eventData=0x3fff7d70b630) at trigger.c:1012
#10 0x00003fff892160a0 in rasDumpHookExceptionCatch (hookInterface=0x100000000000001, eventNum=70366553749040, eventData=0x61, userData=0x1003c18) at trigger.c:1283
#11 0x00003fff894c204c in ._Z14J9HookDispatchPP15J9HookInterfacemPv () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9hookable29.so
#12 0x00003fff7d1444c8 in c_jitReportExceptionCatch (currentThread=0x3fff8a07d600) at decomp.cpp:2524
#13 0x00003fff7d16e0a8 in .jitReportExceptionCatch () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#14 0x00003fff895faa88 in runCallInMethod (env=0x0, receiver=0x3fff88f2a8a8, clazz=0x0, methodID=0x0, args=0x0) at callin.cpp:1151
#15 0x00003fff896299cc in gpProtectedRunCallInMethod (entryArg=0x3fff88b39eb0 <J9AllocateIndexableObject+1392>) at jnicsup.cpp:305
#16 0x00003fff8969822c in signalProtectAndRunGlue (portLibrary=0x0, userData=0x0) at jniprotect.c:43
#17 0x00003fff8942c7c8 in .omrsig_protect () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9prt29.so
#18 0x00003fff8969838c in gpProtectAndRun (function=0x3fff8a4a0868 <jextractFatalExceptionClass>, env=0x3fff84431ef8, args=0x1) at jniprotect.c:77
#19 0x00003fff8962994c in gpCheckCallin (env=0x3fff84309ec0, receiver=0x0, cls=0x3fff897b5e28 <callStaticObjectMethod>, methodID=0x3fff89628d60 <callStaticObjectMethod>, args=0x1) at jnicsup.cpp:493
#20 0x00003fff89628db8 in callStaticObjectMethod (env=0x3fff8a21a3e0, cls=0x0, methodID=0x3fff84431ef8) at jnicgen.c:413
#21 0x00003fff8a474d1c in .JavaMain () from /team/amicic_j9build/jvmxp6480.30242/jre/bin/../lib/ppc64/jli/libjli.so
#22 0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#23 0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 8 (Thread 0x3fff8935f1b0 (LWP 11187)):
#0  0x00003fff8a4c5d08 in .do_futex_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff8a4c5ddc in .__new_sem_wait_slow.constprop.0 () from /usr/lib64/libpthread.so.0
#2  0x00003fff8942facc in .asynchSignalReporter () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9prt29.so
#3  0x00003fff894eccc4 in .thread_wrapper () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#4  0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#5  0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 7 (Thread 0x3fff882df1b0 (LWP 11188)):
#0  0x00003fff8a4c285c in .pthread_cond_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff894f2bf4 in .IPRA.$monitor_wait_original () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#2  0x00003fff894f1510 in .omrthread_monitor_wait () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#3  0x00003fff7c216bd4 in ._ZN2J97Monitor4waitEv () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#4  0x00003fff7c0e1a78 in ._Z30protectedCompilationThreadProcP13J9PortLibraryPN2TR24CompilationInfoPerThreadE () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#5  0x00003fff8942c7c8 in .omrsig_protect () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9prt29.so
#6  0x00003fff7c0df524 in ._Z21compilationThreadProcPv () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#7  0x00003fff894eccc4 in .thread_wrapper () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#8  0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#9  0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 6 (Thread 0x3fff881cf1b0 (LWP 11189)):
#0  0x00003fff8a4c285c in .pthread_cond_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff894f2bf4 in .IPRA.$monitor_wait_original () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#2  0x00003fff894f1510 in .omrthread_monitor_wait () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#3  0x00003fff7c216bd4 in ._ZN2J97Monitor4waitEv () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#4  0x00003fff7c0e19f0 in ._Z30protectedCompilationThreadProcP13J9PortLibraryPN2TR24CompilationInfoPerThreadE () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#5  0x00003fff8942c7c8 in .omrsig_protect () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9prt29.so
#6  0x00003fff7c0df524 in ._Z21compilationThreadProcPv () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#7  0x00003fff894eccc4 in .thread_wrapper () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#8  0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#9  0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 5 (Thread 0x3fff49eaf1b0 (LWP 11190)):
#0  0x00003fff8a4c285c in .pthread_cond_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff894f03d4 in .monitor_enter_three_tier () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#2  0x00003fff894ef1d4 in .omrthread_monitor_enter () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#3  0x00003fff7c1046f4 in ._Z17samplerThreadProcPv () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#4  0x00003fff894eccc4 in .thread_wrapper () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#5  0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#6  0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 4 (Thread 0x3fff49c2f1b0 (LWP 11192)):
#0  0x00003fff8a4c285c in .pthread_cond_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff894f2bf4 in .IPRA.$monitor_wait_original () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#2  0x00003fff894f1510 in .omrthread_monitor_wait () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#3  0x00003fff88b05fbc in FinalizeMainRunFinalization (vm=0x0, indirectWorkerThreadHandle=0x0, indirectWorkerData=0x3fff49c2f900, finalizeCycleLimit=589824, mode=70365686711376) at FinalizerSupport.cpp:743
#4  0x00003fff88b05144 in FinalizeMainThread (javaVM=0x0) at FinalizerSupport.cpp:274
#5  0x00003fff894eccc4 in .thread_wrapper () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#6  0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#7  0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x3fff49b9f1b0 (LWP 11193)):
#0  0x00003fff8a4c285c in .pthread_cond_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff894f2bf4 in .IPRA.$monitor_wait_original () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#2  0x00003fff894f1510 in .omrthread_monitor_wait () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#3  0x00003fff895eb208 in internalAcquireVMAccessNoMutexWithMask (vmThread=0x3fff5bb797c0, haltMask=70366663830872) at VMAccess.cpp:386
#4  0x00003fff895ee96c in haltThreadForInspection (currentThread=0x3fff8445f400, vmThread=0x3fff8403d0a0) at VMAccess.cpp:1296
#5  0x00003fff8965ada0 in cancelLockReservation (vmStruct=0x3fff88b26548 <j9gc_objaccess_storeObjectToInternalVMSlot+72>) at monhelpers.c:320
#6  0x00003fff895e59b4 in objectMonitorEnterBlocking (currentThread=0x3fff7d140588 <fast_jitMethodMonitorExit+136>) at ObjectMonitor.cpp:150
#7  0x00003fff7d12e37c in old_slow_jitMonitorEntry (currentThread=0x20a8) at cnathelp.cpp:1754
#8  0x00003fff7d154994 in .jitMonitorEntry () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9jit29.so
#9  0x00003fff4b376450 in ?? ()
#10 0x00003fff895fc738 in runJavaThread (currentThread=0x0) at callin.cpp:664
#11 0x00003fff8967efa4 in javaProtectedThreadProc (portLibrary=0x0, entryarg=0x0) at vmthread.cpp:2081
#12 0x00003fff8942c7c8 in .omrsig_protect () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9prt29.so
#13 0x00003fff8967edf4 in javaThreadProc (entryarg=0x0) at vmthread.cpp:360
#14 0x00003fff894eccc4 in .thread_wrapper () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#15 0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#16 0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x3fff4b35f1b0 (LWP 11196)):
#0  0x00003fff8a4c285c in .pthread_cond_wait () from /usr/lib64/libpthread.so.0
#1  0x00003fff894f03d4 in .monitor_enter_three_tier () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#2  0x00003fff894ef1d4 in .omrthread_monitor_enter () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#3  0x00003fff8967e3fc in allocateVMThread (vm=0x0, osThread=0x0, privateFlags=0, memorySpace=0x0, threadObject=0x0) at vmthread.cpp:108
#4  0x00003fff89637e70 in protectedInternalAttachCurrentThread (portLibrary=0x0, userData=0x0) at jniinv.c:681
#5  0x00003fff8942c7c8 in .omrsig_protect () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9prt29.so
#6  0x00003fff89638494 in attachSystemDaemonThread (vm=0x0, p_env=0x0, threadName=0x0) at jniinv.c:745
#7  0x00003fff88b05558 in FinalizeWorkerThread (arg=0x0) at FinalizerSupport.cpp:490
#8  0x00003fff8942c7c8 in .omrsig_protect () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9prt29.so
#9  0x00003fff88b0616c in gpProtectedFinalizeWorkerThread (entryArg=0x0) at FinalizerSupport.cpp:817
#10 0x00003fff894eccc4 in .thread_wrapper () from /team/amicic_j9build/jvmxp6480.30242/jre/lib/ppc64/default/libj9thr29.so
#11 0x00003fff8a4bcafc in .start_thread () from /usr/lib64/libpthread.so.0
#12 0x00003fff8a35704c in .__clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x3fff8a574ef0 (LWP 11185)):
#0  0x00003fff8a4be110 in .pthread_join () from /usr/lib64/libpthread.so.0
#1  0x00003fff8a477c9c in .ContinueInNewThread0 () from /team/amicic_j9build/jvmxp6480.30242/jre/bin/../lib/ppc64/jli/libjli.so
#2  0x00003fff8a4754e0 in .ContinueInNewThread () from /team/amicic_j9build/jvmxp6480.30242/jre/bin/../lib/ppc64/jli/libjli.so
#3  0x00003fff8a477dd0 in .JVMInit () from /team/amicic_j9build/jvmxp6480.30242/jre/bin/../lib/ppc64/jli/libjli.so
#4  0x00003fff8a472244 in .JLI_Launch () from /team/amicic_j9build/jvmxp6480.30242/jre/bin/../lib/ppc64/jli/libjli.so
```

**Comment by gacholio** [comment]
```
> !threads flags
Attached Threads List. For more options, run !threads help

    !j9vmthread 0x3fffb00a2500 publicFlags=48000 privateFlags=1008 inNative=0 // main
    !j9vmthread 0x3fff70002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Compilation Thread-000
    !j9vmthread 0x3fff68002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Compilation Thread-001 Suspended
    !j9vmthread 0x3fff6c002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Compilation Thread-002 Suspended
    !j9vmthread 0x3fff60002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Compilation Thread-003 Suspended
    !j9vmthread 0x3fff64002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Compilation Thread-004 Suspended
    !j9vmthread 0x3fff58002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Compilation Thread-005 Suspended
    !j9vmthread 0x3fff5c002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Compilation Thread-006 Suspended
    !j9vmthread 0x3fff50002200 publicFlags=81 privateFlags=101a inNative=0 // JIT Diagnostic Compilation Thread-007 Suspended
    !j9vmthread 0x3fff54002200 publicFlags=81 privateFlags=101a inNative=0 // JIT-SamplerThread
    !j9vmthread 0x3fff48002200 publicFlags=81 privateFlags=1a inNative=0 // Concurrent Mark Helper
    !j9vmthread 0x3fff4c002200 publicFlags=81 privateFlags=1a inNative=0 // GC Worker
    !j9vmthread 0x3fff40002200 publicFlags=81 privateFlags=1a inNative=0 // GC Worker
    !j9vmthread 0x3fff44002200 publicFlags=81 privateFlags=1a inNative=0 // GC Worker
    !j9vmthread 0x3fff38002200 publicFlags=81 privateFlags=1a inNative=0 // GC Worker
    !j9vmthread 0x3fff3c002200 publicFlags=81 privateFlags=1a inNative=0 // GC Worker
    !j9vmthread 0x3fff30002200 publicFlags=81 privateFlags=1a inNative=0 // GC Worker
    !j9vmthread 0x3fff34002200 publicFlags=81 privateFlags=1a inNative=0 // GC Worker
    !j9vmthread 0x3fffb0481e00 publicFlags=1081 privateFlags=2 inNative=0 // Attach API initializer
```
It looks like the main thread still holds exclusive, which explains why the attach API thread isn't waking up to perform the inspection.

**Comment by gacholio** [comment]
```
	0x16b0: UDATA exclusiveAccessState = 0x0000000000000002 (2)

#define J9_XACCESS_EXCLUSIVE 2
```

**Comment by gacholio** [comment]
I suspect the problem here is that the RAS code is acquiring exclusive before calling the expilcit GC, which is fundamentally invalid.

**Comment by gacholio** [comment]
@keithc-ca I believe we'll need to update the RAS handling of exclusive so that the GC call falls outside the exclusive region.

**Comment by gacholio** [comment]
I suspect the right answer there is to delete the comment and change the flag check to true.

**Comment by amicic** [comment]
following up on earlier private discussion for benefit of others...

```
Aleksandar Micic
if inspectee already holds exclusive, hence blocking anybody else including inspector to proceed, then inspectee should not block. inspection can wait till RAS completes the dump and releases exclusive. it's how it worked before.
I'm generally not in favor of additional workaround (the patch has already grown much), but just wondering if we can make a temporary and quick compromise. (edited) 


Graham Chapman  
if we do as aleks suggests, we may open back up the window where the thread runs while its supposedly halted
```

if know that inspectee is the one that holds exclusive, and if under that condition we skip the new HALT_ANY check, once it releases exclusive obtained by the caller of system GC, it will still hold VM access, preventing inspector to proceed
since exclusive was obtained directly (not via GC API), the inspectee never went through release/reacquire critical, so the inspector was never mislead that inspectee is supposedly halted

there is a path in GC that expects exclusive to be already obtained, that will do no  VM access work
```
MM_EnvironmentBase::acquireExclusiveVMAccessForGC(MM_Collector *collector, bool failIfNotFirst, bool flushCaches)
{
	MM_GCExtensionsBase *extensions = getExtensions();
	uintptr_t collectorAccessCount = collector->getExclusiveAccessCount();

	/* Does the current thread have exclusive vm access? */
	if (_omrVMThread->exclusiveCount > 0) {
		/* Did the current thread get exclusive vm access via (or already come through this code) the
		 * GC exclusive vm access APIs.
		 */
		if (_omrVMThread != extensions->gcExclusiveAccessThreadId) {
			/* The current thread did not get exclusive vm access via the GC exclusive vm access API */
			/* If another thread has started to get exclusive vm access for a GC cache that value so it
			 * can be restored later. It is possible for a thread to win setting itself as the thread
			 * requesting exclusive vm access for a GC but not actually be the next thread to perform
			 * a GC.  It can happen if a system gc is requested while holding exclusive.
			 */
			_cachedGCExclusiveAccessThreadId = (OMR_VMThread *)extensions->gcExclusiveAccessThreadId;
			/* Current thread has exclusive VM access so there is no reason to grab the mutex! */
			extensions->gcExclusiveAccessThreadId = _omrVMThread;
		}
	} else {
.... 
path that may release/reacquire critical
```

**Comment by amicic** [comment]
I basically already mentioned it, but the idea is to skip our new halt check if we know that the very same thread holds exclusive VM access (I guess, it's not possible to for this thread to hold safe point or by any other means block globally).
