### ISSUE TITLE
JDK19: JVMTI decompilation test failure

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15245]
```
04:20:35  Testing: decomp002
04:20:35  Test start time: 2022/06/06 05:20:32 Atlantic Standard Time
04:20:35  Running command: "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xgcpolicy:gencon -Xjit:enableOSR,count=0  -Xdump -Xgcthreads1  -Xdump:system:events=abort  -agentlib:jvmtitest=test:decomp002 -cp "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
04:20:35  Time spent starting: 10 milliseconds
04:25:47  ***[TEST INFO 2022/06/06 05:25:33] ProcessKiller detected a timeout after 300000 milliseconds!***
04:25:47  INFO: Cannot find '/usr/bin/gdb' using 'gdb' from the path.
04:25:47  ***[TEST INFO 2022/06/06 05:25:36] executing gdb -batch -x /tmp/debugger11075582014288556020.txt /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/openjdkbinary/j2sdk-image/bin/java 10343***
04:25:47  java.io.IOException: Cannot run program "gdb": error=2, No such file or directory
04:25:47  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
04:25:47  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
04:25:47  	at java.base/java.lang.Runtime.exec(Runtime.java:615)
04:25:47  	at java.base/java.lang.Runtime.exec(Runtime.java:474)
04:25:47  	at Test$ProcessKiller.captureCoreForProcess(Test.java:697)
04:25:47  	at Test$ProcessKiller.captureCoreForProcess(Test.java:646)
04:25:47  	at Test$ProcessKiller.run(Test.java:596)
04:25:47  Caused by: java.io.IOException: error=2, No such file or directory
04:25:47  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
04:25:47  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
04:25:47  	... 6 more
04:25:47  ***[TEST INFO 2022/06/06 05:25:36] executing kill -ABRT 10343***
04:25:47  ***[TEST INFO 2022/06/06 05:25:36] kill -ABRT signal sent***
04:25:51  Time spent executing: 317466 milliseconds
04:25:51  ***[TEST INFO 2022/06/06 05:25:50] ABRT completed***
04:25:51  Test result: FAILED
04:25:51  Output from test:
04:25:51   [OUT] *** Testing [1/1]:	testStepping
04:25:51   [OUT] 	Step 10000000 times
04:25:51   [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2022/06/06 05:25:41 - please wait.
04:25:51   [ERR] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/aqa-tests/TKG/output_16544977725873/cmdLineTester_decompilationTests_1/core.20220606.052541.10343.0001.dmp' in response to an event
04:25:51   [ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.10592.
04:25:51   [ERR] 
04:25:51   [ERR] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/aqa-tests/TKG/output_16544977725873/cmdLineTester_decompilationTests_1/core.20220606.052541.10343.0001.dmp
04:25:51   [ERR] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/aqa-tests/TKG/output_16544977725873/cmdLineTester_decompilationTests_1/javacore.20220606.052541.10343.0002.txt' in response to an event
04:25:51   [ERR] JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdknext_j9_sanit
```

```
04:25:51  Testing: decomp002-OSRFV
04:25:51  Test start time: 2022/06/06 05:25:50 Atlantic Standard Time
04:25:51  Running command: "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xgcpolicy:gencon -Xjit:enableOSR,count=0  -Xdump -Xgcthreads1  -XX:+OSRSafePointFV -Xdump:system:events=abort  -agentlib:jvmtitest=test:decomp002 -cp "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
04:25:51  Time spent starting: 35 milliseconds
04:31:04  ***[TEST INFO 2022/06/06 05:30:50] ProcessKiller detected a timeout after 300000 milliseconds!***
04:31:04  INFO: Cannot find '/usr/bin/gdb' using 'gdb' from the path.
04:31:04  ***[TEST INFO 2022/06/06 05:30:50] executing gdb -batch -x /tmp/debugger18129469123897292797.txt /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/openjdkbinary/j2sdk-image/bin/java 10602***
04:31:04  java.io.IOException: Cannot run program "gdb": error=2, No such file or directory
04:31:04  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
04:31:04  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
04:31:04  	at java.base/java.lang.Runtime.exec(Runtime.java:615)
04:31:04  	at java.base/java.lang.Runtime.exec(Runtime.java:474)
04:31:04  	at Test$ProcessKiller.captureCoreForProcess(Test.java:697)
04:31:04  	at Test$ProcessKiller.captureCoreForProcess(Test.java:646)
04:31:04  	at Test$ProcessKiller.run(Test.java:596)
04:31:04  Caused by: java.io.IOException: error=2, No such file or directory
04:31:04  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
04:31:04  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
04:31:04  	... 6 more
04:31:04  ***[TEST INFO 2022/06/06 05:30:50] executing kill -ABRT 10602***
04:31:04  ***[TEST INFO 2022/06/06 05:30:50] kill -ABRT signal sent***
04:31:04  ***[TEST INFO 2022/06/06 05:31:03] ABRT completed***
04:31:04  Output from test:
04:31:04   [OUT] *** Testing [1/1]:	testStepping
04:31:04   [OUT] *** Test took 285475 milliseconds
04:31:04   [OUT] OK
04:31:04   [OUT] 
04:31:04   [OUT] 	Step 10000000 times
04:31:04   [OUT] 	Decompile cycles: 2335
04:31:04   [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2022/06/06 05:30:57 - please wait.
04:31:04   [ERR] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_0/aqa-tests/TKG/output_16544977725873/cmdLineTester_decompilationTests_1/core.20220606.053057.10602.0001.dmp' in response to an event
04:31:05  Time spent executing: 314175 milliseconds
04:31:05  Test result: FAILED
04:31:05  Output from test:
```

**Comment by tajila** [comment]
@babsingh Here is another jvmti related failure, can you take a look at this as well

**Comment by babsingh** [comment]
There are no functional deficiencies. The tests just timeout. If the timeout is removed, the tests should pass. Current timeout is 300 seconds. Max. runtime noticed is 340 seconds. There is also a note for `decomp002`:
https://github.com/eclipse-openj9/openj9/blob/816c5f8c7022b4ce189e917b00d8990aca5af368/test/functional/cmdLineTests/jvmtitests/decompilationtests.xml#L27

We can temporarily increase the timeout. Not sure if it is an actual perf issue. But, we can open a Loom related PERF issue and document this slowdown over there. This can be investigated from a perf perspective once we are fully functional.

**Comment by babsingh** [comment]
Closing. https://github.com/eclipse-openj9/openj9/pull/15256 has been merged to resolve the reported failures. This issue can be re-opened if the reported failures re-occur.

**Comment by babsingh** [comment]
Removing the `test excluded` label since this test was never excluded.
