### ISSUE TITLE
JDK19 Error evaluating expression: invalid boolean value: null for expression vm.continuations

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15247]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Nightly/1/consoleFull

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
10:36:59  TEST: java/lang/Thread/virtual/ThreadAPI.java#id1
10:36:59  
10:36:59  TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.continuations'
10:36:59  --------------------------------------------------
10:37:22  TEST: jdk/internal/vm/Continuation/Fuzz.java
10:37:22  
10:37:22  TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `(vm.continuations)'
```
This is a test issue requiring extension repo change.

FYI @llxia

**Comment by pshipton** [comment]
Fixing this is already in progress at https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/453/files, assuming `true` is the correct value for OpenJ9.

**Comment by LongyuZhang** [comment]
Test `java/lang/Thread/virtual/ThreadAPI.java` test hits the error of `org.testng.SkipException: Requires continuations support` after set `vm.continuations` value ([grinder_false](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24693), [grinder_true](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24695)) as attached. 

Should we set `vm.continuations` to `false`, and exclude this test, and then after `ContinuationSupport` is ready, change it to `true` then enable the test?
```
18:49:45  org.testng.SkipException: Requires continuations support
18:49:45  	at ThreadAPI.testGetStackTrace2(ThreadAPI.java:1873)
18:49:45  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:49:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
18:49:45  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
18:49:45  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
18:49:45  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
18:49:45  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
18:49:45  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
18:49:45  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
18:49:45  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
18:49:45  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
18:49:45  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
18:49:45  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
18:49:45  	at org.testng.TestRunner.run(TestRunner.java:585)
18:49:45  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
18:49:45  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
18:49:45  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
18:49:45  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
18:49:45  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
18:49:45  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
18:49:45  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
18:49:45  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
18:49:45  	at org.testng.TestNG.runSuites(TestNG.java:1069)
18:49:45  	at org.testng.TestNG.run(TestNG.java:1037)
18:49:45  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
18:49:45  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
18:49:45  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:49:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
18:49:45  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
18:49:45  	at java.base/java.lang.Thread.run(Thread.java:1566)
```

**Comment by JasonFengJ9** [comment]
> Should we set vm.continuations to false, and exclude this test, and then after ContinuationSupport is ready, change it to true then enable the test?

Sounds good.

fyi @tajila @fengxue-IS

**Comment by tajila** [comment]
@LongyuZhang can you please re-enable this

**Comment by LongyuZhang** [comment]
Test enabling `java/lang/Thread/virtual/ThreadAPI.java#id1` with `vm.continuations=true`, test with xlinux JDK 19, failed in [hyc_grinder 28708](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/28708), with [rerun link](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/28708/rebuild/parameterized):
```
12:34:13  test ThreadAPI.testGetAllStackTraces2(): failure
12:34:13  java.lang.AssertionError: expected [true] but found [false]
12:34:13  	at org.testng.Assert.fail(Assert.java:99)
12:34:13  	at org.testng.Assert.failNotEquals(Assert.java:1037)
12:34:13  	at org.testng.Assert.assertTrue(Assert.java:45)
12:34:13  	at org.testng.Assert.assertTrue(Assert.java:55)
12:34:13  	at ThreadAPI.testGetAllStackTraces2(ThreadAPI.java:2075)
12:34:13  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
12:34:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
12:34:13  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
12:34:13  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
12:34:13  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
12:34:13  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
12:34:13  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
12:34:13  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
12:34:13  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
12:34:13  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
12:34:13  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
12:34:13  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
12:34:13  	at org.testng.TestRunner.run(TestRunner.java:585)
12:34:13  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
12:34:13  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
12:34:13  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
12:34:13  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
12:34:13  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
12:34:13  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
12:34:13  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
12:34:13  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
12:34:13  	at org.testng.TestNG.runSuites(TestNG.java:1069)
12:34:13  	at org.testng.TestNG.run(TestNG.java:1037)
12:34:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
12:34:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
12:34:13  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
12:34:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
12:34:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:34:13  	at java.base/java.lang.Thread.run(Thread.java:1573)

12:34:13  test ThreadAPI.testGetStackTrace4(): failure
12:34:13  java.lang.AssertionError: expected [true] but found [false]
12:34:13  	at org.testng.Assert.fail(Assert.java:99)
12:34:13  	at org.testng.Assert.failNotEquals(Assert.java:1037)
12:34:13  	at org.testng.Assert.assertTrue(Assert.java:45)
12:34:13  	at org.testng.Assert.assertTrue(Assert.java:55)
12:34:13  	at ThreadAPI.testGetStackTrace4(ThreadAPI.java:1976)
12:34:13  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
12:34:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
12:34:13  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
12:34:13  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
12:34:13  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
12:34:13  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
12:34:13  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
12:34:13  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
12:34:13  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
12:34:13  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
12:34:13  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
12:34:13  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
12:34:13  	at org.testng.TestRunner.run(TestRunner.java:585)
12:34:13  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
12:34:13  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
12:34:13  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
12:34:13  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
12:34:13  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
12:34:13  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
12:34:13  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
12:34:13  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
12:34:13  	at org.testng.TestNG.runSuites(TestNG.java:1069)
12:34:13  	at org.testng.TestNG.run(TestNG.java:1037)
12:34:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
12:34:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
12:34:13  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
12:34:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
12:34:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:34:13  	at java.base/java.lang.Thread.run(Thread.java:1573)
```

**Comment by tajila** [comment]
@fengxue-IS please take a look

**Comment by fengxue-IS** [comment]
Local testing on xlinux passed with fix PR
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal-adhoc.root.openj9-openjdk-jdk19)
Eclipse OpenJ9 VM (build cont_carrierstack-339cb8e96, JRE 19 Linux amd64-64-Bit Compressed References 20220720_000000 (JIT enabled, AOT enabled)
OpenJ9   - eb83b9200
OMR      - d5d4a5383
JCL      - fddc34c2848 based on jdk-19+36)
Test selection 'java/lang/Thread/virtual/ThreadAPI.java', will run:
* jtreg:test/jdk/java/lang/Thread/virtual/ThreadAPI.java

Running test 'jtreg:test/jdk/java/lang/Thread/virtual/ThreadAPI.java'
Passed: java/lang/Thread/virtual/ThreadAPI.java#id1
Passed: java/lang/Thread/virtual/ThreadAPI.java#id0
Test results: passed: 2
Report written to /root/openj9-openjdk-jdk19/build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_lang_Thread_virtual_ThreadAPI_java/html/report.html
Results written to /root/openj9-openjdk-jdk19/build/linux-x86_64-server-release/test-support/jtreg_test_jdk_java_lang_Thread_virtual_ThreadAPI_java
Finished running test 'jtreg:test/jdk/java/lang/Thread/virtual/ThreadAPI.java'
Test report is stored in build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_lang_Thread_virtual_ThreadAPI_java

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/lang/Thread/virtual/ThreadAPI.java
                                                         2     2     0     0   
==============================
TEST SUCCESS
```
**jdk/internal/vm/Continuation/Fuzz.java** requires additional configure which see to be testing JIT specifics. I think this should remain excluded
```
 * @requires vm.flavor == "server" & (vm.opt.TieredStopAtLevel == null | vm.opt.TieredStopAtLevel == 4)
 * @requires vm.opt.TieredCompilation == null | vm.opt.TieredCompilation == true
```

**Comment by babsingh** [comment]
ThreadAPI is still disabled for JDK20: https://github.com/adoptium/aqa-tests/blob/a74405ca1262c4e50ea0a88e9cb27ade2dd60179/openjdk/excludes/ProblemList_openjdk20-openj9.txt#L158.

@fengxue-IS Can you please re-enable ThreadAPI? Afterwards, the `test excluded` label should be re-enabled.

Also, the `perm excluded` label should be used for Continuation/Fuzz if it is unsupported.

**Comment by fengxue-IS** [comment]
ThreadAPI test re-enable for JDK 20 will be handled in #15503, adding `perm exclude` on this issue for Fuzz.

**Comment by pshipton** [comment]
@fengxue-IS we don't want any `test excluded` label on a closed issue. Can we move it to https://github.com/eclipse-openj9/openj9/issues/15503 for the jdk20 exclude and remove it from this one?

**Comment by fengxue-IS** [comment]
> @fengxue-IS we don't want any `test excluded` label on a closed issue. Can we move it to #15503 for the jdk20 exclude and remove it from this one?

done
