### ISSUE TITLE
AIX 32-bit testDDRExtJunit_FindExtThread failure

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15246]
Internal failure /job_output.php?id=35866527
Started failing in ibuild /build_info.php?build_id=30242 
Relevant hanges:
https://github.com/eclipse/omr/pull/6548
https://github.com/eclipse-openj9/openj9/pull/15216

The test can intermittently fail on older builds, but fails 100% from ibuild 20242
/build_info.php?build_id=30279

Failing output
```
     [java] [AutoRun] [INFO] Starting testFindstackvalue(j9vm.test.ddrext.junit.TestFindExt)
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue  0x324D64A8' output is null or empty
     [java] junit.framework.AssertionFailedError
     [java]     at junit.framework.Assert.fail(Assert.java:48)
     [java]     at junit.framework.Assert.assertTrue(Assert.java:20)
     [java]     at junit.framework.Assert.assertTrue(Assert.java:27)
     [java]     at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
     [java]     at java.lang.reflect.Method.invoke(Method.java:508)
     [java]     at junit.framework.TestCase.runTest(TestCase.java:168)
     [java]     at junit.framework.TestCase.runBare(TestCase.java:134)
     [java]     at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java]     at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java]     at junit.framework.TestResult.run(TestResult.java:113)
     [java]     at junit.framework.TestCase.run(TestCase.java:124)
     [java]     at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java]     at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java]     at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!findstackvalue  0x324D64A8'
     [java] [AutoRun] [INFO] Finished testFindstackvalue(j9vm.test.ddrext.junit.TestFindExt)
```

@gacholio @amicic 
@tajila @keithc-ca fyi

**Comment by pshipton** [comment]
Sorry, we got unlucky with a small grinder and I made some assumptions (updated previous comment). I don't think there is any problem here.
