### ISSUE TITLE
JDK19 jdk_util_0_FAILED java/util/TimeZone/Bug5097350.java NullPointerException: Cannot invoke "java.util.function.Predicate.test(java.lang.Object)" because "this.this$1.val$predicate" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15269]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_sanity.openjdk_x86-64_mac_Personal/5/consoleFull`(`mac11x64rt07`):
```
11:26:18  openjdk version "19-internal" 2022-09-20
11:26:18  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextx86-64macPersonal)
11:26:18  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220607_71 (JIT enabled, AOT enabled)
11:26:18  OpenJ9   - 52f04efbff5
11:26:18  OMR      - c60867497c6
11:26:18  JCL      - 5ccf02de16a based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_mac_Personal%2F71%2FOpenJ9-JDKnext-x86-64_mac-20220607-104941.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_mac_Personal%2F71%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=exclude19&OPENJ9_SHA=52f04efbff5d2f4613971cdd550c6802117f0fd7&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.is.osx.10_11%26%26%21sw.os.mac.10_11&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
13:14:15  ===============================================
13:14:15  Running test jdk_util_0 ...
13:14:15  ===============================================
13:14:15  jdk_util_0 Start Time: Tue Jun  7 13:14:14 2022 Epoch Time (ms): 1654622054757
13:14:15  "/Users/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_x86-64_mac_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_x86-64_mac_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
13:14:15  JVMSHRC005I No shared class caches available
13:14:15  JVMSHRC005I No shared class caches available
13:14:15  cache cleanup done
13:14:15  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
13:14:15  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

13:24:00  TEST: java/util/TimeZone/Bug5097350.java

13:24:00  stderr:
13:24:00  java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(java.lang.Object)" because "this.this$1.val$predicate" is null
13:24:00  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
13:24:00  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
13:24:00  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
13:24:00  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
13:24:00  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
13:24:00  	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
13:24:00  	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
13:24:00  	at java.base/java.lang.Thread.getAllThreads(Thread.java:2698)
13:24:00  	at java.base/java.lang.ThreadGroup.activeCount(ThreadGroup.java:377)
13:24:00  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.liveThreads(MainActionHelper.java:422)
13:24:00  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.cleanup(MainActionHelper.java:380)
13:24:00  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.access$000(MainActionHelper.java:345)
13:24:00  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:214)
13:24:00  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
13:24:00  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
13:24:00  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
13:24:00  
13:24:00  TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details
13:24:00  --------------------------------------------------
13:25:11  Test results: passed: 902; error: 2
13:25:25  Report written to /Users/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_x86-64_mac_Personal/jvmtest/openjdk/report/html/report.html
13:25:25  Results written to /Users/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_x86-64_mac_Personal/aqa-tests/TKG/output_16546157201881/jdk_util_0/work
13:25:25  Error: Some tests failed or other problems occurred.
13:25:25  
13:25:25  jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_OpenJDK19/2
jdk_util_0
java/util/Calendar/CalendarRegression.java

```
19:42:45  java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(java.lang.Object)" because "this.this$1.val$predicate" is null
19:42:45  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
19:42:45  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
19:42:45  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
19:42:45  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
19:42:45  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
19:42:45  	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
19:42:45  	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
19:42:45  	at java.base/java.lang.Thread.getAllThreads(Thread.java:2704)
19:42:45  	at java.base/java.lang.ThreadGroup.activeCount(ThreadGroup.java:377)
19:42:45  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.liveThreads(MainActionHelper.java:422)
19:42:45  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.cleanup(MainActionHelper.java:380)
19:42:45  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.access$000(MainActionHelper.java:345)
19:42:45  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:214)
19:42:45  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
19:42:45  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
19:42:45  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
```

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Personal/2/consoleFull`
```
01:39:25  openjdk version "19-internal" 2022-09-20
01:39:25  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.buildjdk19x86-64windowspersonal)
01:39:25  Eclipse OpenJ9 VM (build master-ac82c9067c5, JRE 19 Windows Server 2016 amd64-64-Bit Compressed References 20220622_4 (JIT enabled, AOT enabled)
01:39:25  OpenJ9   - ac82c9067c5
01:39:25  OMR      - 342963cee6d
01:39:25  JCL      - abd1f9e6083 based on jdk-19+27)

02:23:10  ===============================================
02:23:11  Running test jdk_lang_1 ...
02:23:11  ===============================================
02:23:11  jdk_lang_1 Start Time: Thu Jun 23 02:23:07 2022 Epoch Time (ms): 1655965386996
02:23:11  "C:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Personal/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Personal/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
02:23:12  JVMSHRC005I No shared class caches available
02:23:13  JVMSHRC005I No shared class caches available
02:23:14  cache cleanup done
02:23:14  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
02:23:14  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

02:53:07  TEST: sun/reflect/ReflectionFactory/ReflectionFactoryTest.java

02:53:07  stderr:
02:53:07  java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(java.lang.Object)" because "this" is null
02:53:07  	at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
02:53:07  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
02:53:07  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
02:53:07  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
02:53:07  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
02:53:07  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
02:53:07  	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
02:53:07  	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
02:53:07  	at java.base/java.lang.Thread.getAllThreads(Thread.java:2704)
02:53:07  	at java.base/java.lang.ThreadGroup.activeCount(ThreadGroup.java:377)
02:53:07  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.liveThreads(MainActionHelper.java:422)
02:53:07  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.cleanup(MainActionHelper.java:380)
02:53:07  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.access$000(MainActionHelper.java:345)
02:53:07  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:214)
02:53:07  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
02:53:07  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
02:53:07  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
02:53:07  
02:53:07  TEST RESULT: Error. Agent communication error: java.net.SocketException: Connection reset; check console log for any additional details
02:53:07  --------------------------------------------------
02:53:49  Test results: passed: 817; error: 1
02:54:14  Report written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Personal\jvmtest\openjdk\report\html\report.html
02:54:14  Results written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Personal\aqa-tests\TKG\output_16559635015775\jdk_lang_1\work
02:54:14  Error: Some tests failed or other problems occurred.
02:54:14  
02:54:14  jdk_lang_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_OpenJDK19/4
jdk_util_0 
java/util/concurrent/tck/JSR166TestCase.java
```
15:09:45  ACTION: junit -- Failed. Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure
15:09:45  REASON: User specified action: run junit/othervm/timeout=1000 --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Djsr166.testImplementationDetails=true JSR166TestCase 
15:09:45  TIME:   12.051 seconds
15:09:45  messages:
15:09:45  command: junit --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Djsr166.testImplementationDetails=true JSR166TestCase
15:09:45  reason: User specified action: run junit/othervm/timeout=1000 --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Djsr166.testImplementationDetails=true JSR166TestCase 
15:09:45  Mode: othervm [/othervm specified]
15:09:45  Additional options from @modules: --add-modules java.management
15:09:45  elapsed time (seconds): 12.051
15:09:45  configuration:
15:09:45  Boot Layer
15:09:45    add modules: java.management                
15:09:45    add opens:   java.base/java.lang            ALL-UNNAMED
15:09:45                 java.base/java.util.concurrent ALL-UNNAMED
15:09:45  
15:09:45  STDOUT:
15:09:45  STDERR:
15:09:45  JavaTest Message: JUnit Failure: testDescendingRemove2(ConcurrentSkipListSubMapTest): Cannot invoke "java.util.function.Predicate.test(java.lang.Object)" because "this.this$1.val$predicate" is null
15:09:45  java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(java.lang.Object)" because "this.this$1.val$predicate" is null
15:09:45  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
15:09:45  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
15:09:45  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
15:09:45  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
15:09:45  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
15:09:45  	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
15:09:45  	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
15:09:45  	at java.base/java.lang.Thread.getAllThreads(Thread.java:2705)
15:09:45  	at java.base/java.lang.ThreadGroup.enumerate(ThreadGroup.java:448)
15:09:45  	at java.base/java.lang.ThreadGroup.enumerate(ThreadGroup.java:409)
15:09:45  	at java.base/java.lang.Thread.enumerate(Thread.java:2079)
15:09:45  	at JSR166TestCase.checkForkJoinPoolThreadLeaks(JSR166TestCase.java:873)
15:09:45  	at JSR166TestCase.tearDown(JSR166TestCase.java:865)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_OpenJDK19/5

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_OpenJDK19/8
java/lang/reflect/Proxy/ProxyClassAccessTest.java
```
08:23:13  java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(java.lang.Object)" because "this.this$1.val$predicate" is null
08:23:13  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
08:23:13  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
```

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/15355
