### ISSUE TITLE
JDK19 java/nio/channels/vthread/BlockingChannelOps.java#id0 executeOnCarrierThread UnsupportedOperationException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15265]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/1/consoleFull`(`ub18-aarch64-7`):
```
11:36:29  openjdk version "19-internal" 2022-09-20
11:36:29  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
11:36:29  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 Linux aarch64-64-Bit Compressed References 20220607_35 (JIT enabled, AOT enabled)
11:36:29  OpenJ9   - 52f04efbff5
11:36:29  OMR      - c60867497c6
11:36:29  JCL      - 5ccf02de16a based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F35%2FOpenJ9-JDKnext-aarch64_linux-20220607-105822.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F35%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=exclude19&OPENJ9_SHA=52f04efbff5d2f4613971cdd550c6802117f0fd7&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
11:56:03  ===============================================
11:56:03  Running test jdk_nio_0 ...
11:56:03  ===============================================
11:56:03  jdk_nio_0 Start Time: Tue Jun  7 11:56:01 2022 Epoch Time (ms): 1654617361957
11:56:03  "/home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
11:56:03  JVMSHRC005I No shared class caches available
11:56:03  JVMSHRC005I No shared class caches available
11:56:03  cache cleanup done
11:56:03  variation: Mode150
11:56:03  JVM_OPTIONS:  -XX:+UseCompressedOops 

11:59:56  TEST: java/nio/channels/vthread/BlockingChannelOps.java#id0

11:59:56  test BlockingChannelOps.testSocketChannelWriteInterrupt(): failure
11:59:56  java.lang.RuntimeException: java.lang.NoClassDefFoundError: sun.nio.ch.Poller (initialization failure)
11:59:56  	at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:77)
11:59:56  	at java.base/java.lang.ThreadBuilders$BoundVirtualThread.run(ThreadBuilders.java:412)
11:59:56  Caused by: java.lang.NoClassDefFoundError: sun.nio.ch.Poller (initialization failure)
11:59:56  	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:142)
11:59:56  	at java.base/sun.nio.ch.SelChImpl.park(SelChImpl.java:86)
11:59:56  	at java.base/sun.nio.ch.SelChImpl.park(SelChImpl.java:109)
11:59:56  	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:545)
11:59:56  	at BlockingChannelOps.lambda$testSocketChannelWriteInterrupt$6(BlockingChannelOps.java:207)
11:59:56  	at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:75)
11:59:56  	... 1 more
11:59:56  Caused by: java.lang.InternalError: java.lang.UnsupportedOperationException
11:59:56  	at java.base/sun.nio.ch.Poller.startThread(Poller.java:260)
11:59:56  	at java.base/sun.nio.ch.Poller.start(Poller.java:242)
11:59:56  	at java.base/sun.nio.ch.Poller.createReadPollers(Poller.java:411)
11:59:56  	at java.base/sun.nio.ch.Poller.<clinit>(Poller.java:392)
11:59:56  	at java.base/sun.nio.ch.DatagramChannelImpl.park(DatagramChannelImpl.java:486)
11:59:56  	at java.base/sun.nio.ch.SelChImpl.park(SelChImpl.java:109)
11:59:56  	at java.base/sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:576)
11:59:56  	at BlockingChannelOps.lambda$testDatagramChannelReceiveAsyncClose$15(BlockingChannelOps.java:425)
11:59:56  	... 2 more
11:59:56  Caused by: java.lang.UnsupportedOperationException
11:59:56  	at java.base/java.lang.Access.executeOnCarrierThread(Access.java:435)
11:59:56  	at java.base/sun.nio.ch.Poller.startThread(Poller.java:254)
11:59:56  	... 9 more
11:59:56  
11:59:56  ===============================================
11:59:56  java/nio/channels/vthread/BlockingChannelOps.java#id0
11:59:56  Total tests run: 32, Passes: 3, Failures: 29, Skips: 0
11:59:56  ===============================================
11:59:56  
11:59:56  STDERR:
11:59:56  java.lang.Exception: failures: 29
11:59:56  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
11:59:56  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
11:59:56  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
11:59:56  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
11:59:56  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:59:56  	at java.base/java.lang.Thread.run(Thread.java:1566)
11:59:56  
11:59:56  JavaTest Message: Test threw exception: java.lang.Exception: failures: 29

12:03:56  jdk_nio_0_FAILED
```

**Comment by tajila** [comment]
@fengxue-IS please take a look at this

**Comment by fengxue-IS** [comment]
Local testing passed on xlinux, will run a grinder on all platform before re-enabling this.
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal-adhoc.root.openj9-openjdk-jdk19)
Eclipse OpenJ9 VM (build cont_carrierstack-eeb7f7ed4, JRE 19 Linux amd64-64-Bit Compressed References 20220720_000000 (JIT enabled, AOT enabled)
OpenJ9   - eb83b9200
OMR      - d5d4a5383
JCL      - fddc34c2848 based on jdk-19+36)
Test selection 'java/nio/channels/vthread/BlockingChannelOps.java', will run:
* jtreg:test/jdk/java/nio/channels/vthread/BlockingChannelOps.java

Running test 'jtreg:test/jdk/java/nio/channels/vthread/BlockingChannelOps.java'
Passed: java/nio/channels/vthread/BlockingChannelOps.java#id1
Passed: java/nio/channels/vthread/BlockingChannelOps.java#id0
Test results: passed: 2
Report written to /root/openj9-openjdk-jdk19/build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_nio_channels_vthread_BlockingChannelOps_java/html/report.html
Results written to /root/openj9-openjdk-jdk19/build/linux-x86_64-server-release/test-support/jtreg_test_jdk_java_nio_channels_vthread_BlockingChannelOps_java
Finished running test 'jtreg:test/jdk/java/nio/channels/vthread/BlockingChannelOps.java'
Test report is stored in build/linux-x86_64-server-release/test-results/jtreg_test_jdk_java_nio_channels_vthread_BlockingChannelOps_java

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/nio/channels/vthread/BlockingChannelOps.java
                                                         2     2     0     0   
==============================
TEST SUCCESS
```

**Comment by tajila** [comment]
@fengxue-IS Were you able to get results?

**Comment by fengxue-IS** [comment]
Have not seen failure in Grinder on plinux and aarch64. un-excluding this as part of https://github.com/adoptium/aqa-tests/pull/4060

**Comment by babsingh** [comment]
Removing the `test excluded` label since the test has been re-enabled.
