### ISSUE TITLE
JDK19 langtools_custom_0_FAILED Exception while calling user-specified class: requires.VMProps

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15264]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/1/consoleFull`(`ub18-aarch64-7`):
```
11:36:29  openjdk version "19-internal" 2022-09-20
11:36:29  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
11:36:29  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 Linux aarch64-64-Bit Compressed References 20220607_35 (JIT enabled, AOT enabled)
11:36:29  OpenJ9   - 52f04efbff5
11:36:29  OMR      - c60867497c6
11:36:29  JCL      - 5ccf02de16a based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F35%2FOpenJ9-JDKnext-aarch64_linux-20220607-105822.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F35%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=exclude19&OPENJ9_SHA=52f04efbff5d2f4613971cdd550c6802117f0fd7&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
11:42:34  ===============================================
11:42:34  Running test langtools_custom_0 ...
11:42:34  ===============================================
11:42:34  langtools_custom_0 Start Time: Tue Jun  7 11:42:33 2022 Epoch Time (ms): 1654616553740
11:42:34  "/home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
11:42:34  JVMSHRC005I No shared class caches available
11:42:34  JVMSHRC005I No shared class caches available
11:42:34  cache cleanup done
11:42:34  variation: Mode150
11:42:34  JVM_OPTIONS:  -XX:+UseCompressedOops 

11:42:46  Exception while calling user-specified class: requires.VMProps
11:42:46  java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V
11:42:46  	at jdk.test.whitebox.WhiteBox.<clinit>(WhiteBox.java:67)
11:42:46  	at requires.VMProps.<clinit>(VMProps.java:64)
11:42:46  	at java.base/java.lang.Class.forNameImpl(Native Method)
11:42:46  	at java.base/java.lang.Class.forName(Class.java:369)
11:42:46  	at java.base/java.lang.Class.forName(Class.java:349)
11:42:46  	at com.sun.javatest.regtest.agent.GetJDKProperties.run(GetJDKProperties.java:78)
11:42:46  	at com.sun.javatest.regtest.agent.GetJDKProperties.main(GetJDKProperties.java:54)
11:42:46  failed to get JDK properties for /home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java -ea -esa -Xmx512m -XX:+UseCompressedOops -Djava.library.path=/home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/openjdk-test-image/jdk/jtreg/native; exit code 1
11:42:46  Error: failed to get JDK properties for /home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/j2sdk-image/bin/java -ea -esa -Xmx512m -XX:+UseCompressedOops -Djava.library.path=/home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/openjdkbinary/openjdk-test-image/jdk/jtreg/native; exit code 1
11:42:46  
11:42:46  langtools_custom_0_FAILED
```
This appears a test issue.

**Comment by pshipton** [comment]
If it needs whitebox (Hotspot) natives we'll have to exclude it.
