### ISSUE TITLE
TestJcmd_0_FAILED testDumpsWithOptions AssertionError: Expected string not found in jcmd output: Dump written to myJavaDump expected [true] but found [false]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15276]
Failure link
------------

From an internal build `job/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/8/consoleFull`(`paix824`):
```
01:35:52  openjdk version "19-internal" 2022-09-20
01:35:52  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextppc64aixPersonal)
01:35:52  Eclipse OpenJ9 VM (build jdk19excludes-756813a526f, JRE 19 AIX ppc64-64-Bit Compressed References 20220608_89 (JIT enabled, AOT enabled)
01:35:52  OpenJ9   - 756813a526f
01:35:52  OMR      - cf8ddbd1adc
01:35:52  JCL      - 4cb748300c8 based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_ppc64_aix_Personal%2F89%2FOpenJ9-JDKnext-ppc64_aix-20220608-230451.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_ppc64_aix_Personal%2F89%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=jdk19excludes&OPENJ9_SHA=756813a526f11fe5786cfa2d580bc896693672fb&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=13&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
02:06:22  ===============================================
02:06:22  Running test TestJcmd_0 ...
02:06:22  ===============================================
02:06:22  TestJcmd_0 Start Time: Thu Jun  9 02:31:25 2022 Epoch Time (ms): 1654759885353
02:06:22  "/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
02:06:22  JVMSHRC005I No shared class caches available
02:06:22  JVMSHRC005I No shared class caches available
02:06:22  cache cleanup done
02:06:22  variation: NoOptions
02:06:22  JVM_OPTIONS:  

02:07:50  FAILED: testDumpsWithOptions
02:07:50  java.lang.AssertionError: Expected string not found in jcmd output: Dump written to /home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/aqa-tests/TKG/output_16547584812075/TestJcmd_0/myJavaDump expected [true] but found [false]
02:07:50  	at org.testng.Assert.fail(Assert.java:96)
02:07:50  	at org.testng.Assert.failNotEquals(Assert.java:776)
02:07:50  	at org.testng.Assert.assertTrue(Assert.java:44)
02:07:50  	at org.openj9.test.attachAPI.TestJcmd.testDumpsWithOptions(TestJcmd.java:285)
02:07:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
02:07:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
02:07:50  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
02:07:50  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
02:07:50  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
02:07:50  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
02:07:50  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:07:50  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
02:07:50  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
02:07:50  	at org.testng.TestRunner.run(TestRunner.java:505)
02:07:50  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
02:07:50  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
02:07:50  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
02:07:50  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
02:07:50  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
02:07:50  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
02:07:50  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
02:07:50  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
02:07:50  	at org.testng.TestNG.runSuites(TestNG.java:1049)
02:07:50  	at org.testng.TestNG.run(TestNG.java:1017)
02:07:50  	at org.testng.TestNG.privateMain(TestNG.java:1354)
02:07:50  	at org.testng.TestNG.main(TestNG.java:1323)
02:07:50  
02:07:50  
02:07:50  ===============================================
02:07:50      TestJcmd
02:07:50      Tests run: 10, Failures: 1, Skips: 0
02:07:50  ===============================================

02:07:50  TestJcmd_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/670
TestJcmd_0
```
00:01:10  FAILED: testDumpsDefaultSettings
00:01:10  java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND core.20240228 expected [true] but found [false]
00:01:10  	at org.testng.Assert.fail(Assert.java:96)
00:01:10  	at org.testng.Assert.failNotEquals(Assert.java:776)
00:01:10  	at org.testng.Assert.assertTrue(Assert.java:44)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/201
```
20:01:05  FAILED: testDumpsDefaultSettings
20:01:05  java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND core.20240406 expected [true] but found [false]
20:01:05  	at org.testng.Assert.fail(Assert.java:96)
20:01:05  	at org.testng.Assert.failNotEquals(Assert.java:776)
20:01:05  	at org.testng.Assert.assertTrue(Assert.java:44)
20:01:05  	at org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings(TestJcmd.java:338)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/222
```
20:00:56  FAILED: testDumpsDefaultSettings
20:00:56  java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND core.20240507 expected [true] but found [false]
20:00:56  	at org.testng.Assert.fail(Assert.java:96)
20:00:56  	at org.testng.Assert.failNotEquals(Assert.java:776)
20:00:56  	at org.testng.Assert.assertTrue(Assert.java:44)
20:00:56  	at org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings(TestJcmd.java:338)
```

**Comment by JasonFengJ9** [comment]
[JDK8 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.functional_s390x_linux_testList_2/694/)(`rtj-ubu24s390x-svl-test-6lslg-1`)
```
[2024-05-04T04:49:45.647Z] variation: NoOptions
[2024-05-04T04:49:45.647Z] JVM_OPTIONS:  

[2024-05-04T04:50:29.302Z] FAILED: testDumpsDefaultSettings
[2024-05-04T04:50:29.302Z] java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND heapdump.20240504 expected [true] but found [false]
[2024-05-04T04:50:29.302Z] 	at org.testng.Assert.fail(Assert.java:96)
[2024-05-04T04:50:29.302Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2024-05-04T04:50:29.302Z] 	at org.testng.Assert.assertTrue(Assert.java:44)
[2024-05-04T04:50:29.302Z] 	at org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings(TestJcmd.java:338)
[2024-05-04T04:50:29.302Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-04T04:50:29.302Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-05-04T04:50:29.302Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-04T04:50:29.302Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-05-04T04:50:29.302Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2024-05-04T04:50:29.302Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2024-05-04T04:50:29.302Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2024-05-04T04:50:29.302Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2024-05-04T04:50:29.302Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2024-05-04T04:50:29.302Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2024-05-04T04:50:29.302Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2024-05-04T04:50:29.302Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2024-05-04T04:50:29.302Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2024-05-04T04:50:29.302Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2024-05-04T04:50:29.302Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2024-05-04T04:50:29.302Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2024-05-04T04:50:29.302Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2024-05-04T04:50:29.302Z] 
[2024-05-04T04:50:29.302Z] 
[2024-05-04T04:50:29.302Z] ===============================================
[2024-05-04T04:50:29.302Z]     TestJcmd
[2024-05-04T04:50:29.302Z]     Tests run: 13, Failures: 1, Skips: 0
[2024-05-04T04:50:29.302Z] ===============================================
[2024-05-04T04:50:29.302Z] 
[2024-05-04T04:50:29.302Z] 
[2024-05-04T04:50:29.302Z] ===============================================
[2024-05-04T04:50:29.302Z] GeneralTest suite
[2024-05-04T04:50:29.302Z] Total tests run: 13, Failures: 1, Skips: 0
[2024-05-04T04:50:29.302Z] ===============================================
[2024-05-04T04:50:29.302Z] 
[2024-05-04T04:50:29.747Z] -----------------------------------
[2024-05-04T04:50:29.747Z] TestJcmd_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40376/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_0/725
