### ISSUE TITLE
JDK19 jdk_nio_0_FAILED Method ReadWriteString.testMalformedWrite(java.nio.file.Path, java.lang.String, java.nio.charset.Charset)[pri:0, instance:ReadWriteString@d662caa0] should have thrown an exception of type class java.nio.charset.UnmappableCharacterException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15289]
Failure link
------------

From an internal build `view/Test_grinder/job/Grinder/24783/consoleFull`(`rhel7s390x-3-5`):
```
09:45:30  openjdk version "19-internal" 2022-09-20
09:45:30  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnexts390xlinuxPersonal)
09:45:30  Eclipse OpenJ9 VM (build jdk19excludes-5cba1cdc4d8, JRE 19 Linux s390x-64-Bit Compressed References 20220608_96 (JIT enabled, AOT enabled)
09:45:30  OpenJ9   - 5cba1cdc4d8
09:45:30  OMR      - cf8ddbd1adc
09:45:30  JCL      - 4cb748300c8 based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=extended.openjdk&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_s390x_linux_Personal%2F96%2FOpenJ9-JDKnext-s390x_linux-20220608-150638.tar.gz&ADOPTOPENJDK_BRANCH=jdk19for&ARTIFACTORY_NUM_ARTIFACTS=200&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=next&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=jdk19excludes&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
10:11:51  ===============================================
10:11:51  Running test jdk_nio_0 ...
10:11:51  ===============================================
10:11:51  jdk_nio_0 Start Time: Thu Jun  9 07:11:49 2022 Epoch Time (ms): 1654783909913
10:11:51  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
10:11:51  JVMSHRC005I No shared class caches available
10:11:51  JVMSHRC005I No shared class caches available
10:11:51  cache cleanup done
10:11:51  variation: Mode150
10:11:51  JVM_OPTIONS:  -XX:+UseCompressedOops 

10:16:35  TEST: java/nio/file/Files/ReadWriteString.java

10:16:35  STDOUT:
10:16:35  config ReadWriteString.setup(): success
10:16:35  test ReadWriteString.testMalformedRead(sun.nio.fs.UnixPath@181401a5, [B@e42fe2b6, ISO-8859-1, null): success
10:16:35  test ReadWriteString.testMalformedRead(sun.nio.fs.UnixPath@181401a5, [B@e42fe2b6, ISO-8859-1, UTF-8): success
10:16:35  test ReadWriteString.testMalformedWrite(sun.nio.fs.UnixPath@273d1910, "?", null): success
10:16:35  test ReadWriteString.testMalformedWrite(sun.nio.fs.UnixPath@273d1910, " ¡", US-ASCII): success
10:16:35  test ReadWriteString.testMalformedWrite(sun.nio.fs.UnixPath@273d1910, "?", UTF-8): success
10:16:35  test ReadWriteString.testMalformedWrite(sun.nio.fs.UnixPath@273d1910, "日本語文字列", ISO-8859-1): success
10:16:35  test ReadWriteString.testMalformedWrite(sun.nio.fs.UnixPath@273d1910, "О", windows-1252): failure
10:16:35  org.testng.TestException: 
10:16:35  Method ReadWriteString.testMalformedWrite(java.nio.file.Path, java.lang.String, java.nio.charset.Charset)[pri:0, instance:ReadWriteString@d662caa0] should have thrown an exception of type class java.nio.charset.UnmappableCharacterException
10:16:35  	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
10:16:35  	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:747)
10:16:35  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)
10:16:35  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
10:16:35  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
10:16:35  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
10:16:35  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
10:16:35  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
10:16:35  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
10:16:35  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
10:16:35  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
10:16:35  	at org.testng.TestRunner.run(TestRunner.java:585)
10:16:35  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
10:16:35  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
10:16:35  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
10:16:35  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
10:16:35  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
10:16:35  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
10:16:35  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
10:16:35  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
10:16:35  	at org.testng.TestNG.runSuites(TestNG.java:1069)
10:16:35  	at org.testng.TestNG.run(TestNG.java:1037)
10:16:35  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
10:16:35  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:16:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
10:16:35  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:16:35  	at java.base/java.lang.Thread.run(Thread.java:1566)
10:16:35  test ReadWriteString.testMalformedWrite(sun.nio.fs.UnixPath@273d1910, "ज", windows-31j): failure
10:16:35  org.testng.TestException: 
10:16:35  Method ReadWriteString.testMalformedWrite(java.nio.file.Path, java.lang.String, java.nio.charset.Charset)[pri:0, instance:ReadWriteString@d662caa0] should have thrown an exception of type class java.nio.charset.UnmappableCharacterException
10:16:35  	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
10:16:35  	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:747)
10:16:35  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)
10:16:35  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
10:16:35  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
10:16:35  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
10:16:35  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
10:16:35  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
10:16:35  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
10:16:35  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
10:16:35  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
10:16:35  	at org.testng.TestRunner.run(TestRunner.java:585)
10:16:35  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
10:16:35  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
10:16:35  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
10:16:35  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
10:16:35  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
10:16:35  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
10:16:35  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
10:16:35  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
10:16:35  	at org.testng.TestNG.runSuites(TestNG.java:1069)
10:16:35  	at org.testng.TestNG.run(TestNG.java:1037)
10:16:35  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
10:16:35  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:16:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
10:16:35  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:16:35  	at java.base/java.lang.Thread.run(Thread.java:1566)
10:16:35  test ReadWriteString.testNulls(): success
10:16:35  test ReadWriteString.testReadString(sun.nio.fs.UnixPath@3376f4ef, "ABCDEFGHIJKLMNOPQRSTUVWXYZ
10:16:35   abcdefghijklmnopqrstuvwxyz
10:16:35   1234567890
10:16:35  ", US-ASCII, US-ASCII): success
10:16:35  test ReadWriteString.testReadString(sun.nio.fs.UnixPath@3376f4ef, "ABCDEFGHIJKLMNOPQRSTUVWXYZ
10:16:35   abcdefghijklmnopqrstuvwxyz
10:16:35   1234567890
10:16:35  ", US-ASCII, UTF-8): success
10:16:35  test ReadWriteString.testReadString(sun.nio.fs.UnixPath@3376f4ef, "“Hello”", UTF-8, null): success
10:16:35  test ReadWriteString.testReadString(sun.nio.fs.UnixPath@3376f4ef, "“Hello”", UTF-8, UTF-8): success
10:16:35  test ReadWriteString.testReadWrite(): success
10:16:35  test ReadWriteString.testWriteString(sun.nio.fs.UnixPath@3376f4ef, sun.nio.fs.UnixPath@e30aad06, "ABCDEFGHIJKLMNOPQRSTUVWXYZ
10:16:35   abcdefghijklmnopqrstuvwxyz
10:16:35   1234567890
10:16:35  ", US-ASCII, null): success
10:16:35  test ReadWriteString.testWriteString(sun.nio.fs.UnixPath@3376f4ef, sun.nio.fs.UnixPath@e30aad06, "ABCDEFGHIJKLMNOPQRSTUVWXYZ
10:16:35   abcdefghijklmnopqrstuvwxyz
10:16:35   1234567890
10:16:35  ", US-ASCII, US-ASCII): success
10:16:35  test ReadWriteString.testWriteString(sun.nio.fs.UnixPath@3376f4ef, sun.nio.fs.UnixPath@e30aad06, "“Hello”", UTF-8, null): success
10:16:35  test ReadWriteString.testWriteString(sun.nio.fs.UnixPath@3376f4ef, sun.nio.fs.UnixPath@e30aad06, "“Hello”", UTF-8, UTF-8): success
10:16:35  config ReadWriteString.cleanup(): success
10:16:35  
10:16:35  ===============================================
10:16:35  java/nio/file/Files/ReadWriteString.java
10:16:35  Total tests run: 18, Passes: 16, Failures: 2, Skips: 0
10:16:35  ===============================================
10:16:35  
10:16:35  STDERR:
10:16:35  java.lang.Exception: failures: 2
10:16:35  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
10:16:35  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:16:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
10:16:35  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:16:35  	at java.base/java.lang.Thread.run(Thread.java:1566)
10:16:35  
10:16:35  JavaTest Message: Test threw exception: java.lang.Exception
10:16:35  JavaTest Message: shutting down test
10:16:35  
10:16:35  
10:16:35  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
10:16:35  --------------------------------------------------
10:21:50  Test results: passed: 388; failed: 1
10:21:50  Report written to /home/jenkins/workspace/Grinder/jvmtest/openjdk/report/html/report.html
10:21:50  Results written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16547824717081/jdk_nio_0/work
10:21:50  Error: Some tests failed or other problems occurred.
10:21:50  
10:21:50  jdk_nio_0_FAILED
```

**Comment by pshipton** [comment]
Passing on a later build https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1009

**Comment by pshipton** [comment]
Un-exclude via https://github.com/adoptium/aqa-tests/pull/3786
