### ISSUE TITLE
AArch64 Linux testSoftMxDisclaimMemory_1: OutOfMemoryError

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#15316]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_aarch64_linux_Nightly/213/

```
===============================================
Running test testSoftMxDisclaimMemory_1 ...
===============================================
testSoftMxDisclaimMemory_1 Start Time: Tue Jun 14 00:57:55 2022 Epoch Time (ms): 1655182675932
variation: Mode119
JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit -Xnocompressedrefs
(... lines omitted ...)
[SoftmxAdvanceTest] [ERROR] 	FAIL: Heap can't shrink to the reset max heap size within 5 minutes!
[SoftmxAdvanceTest] [ERROR] 	FAIL: Memory didn't release back to OS! Post memory size 3344498688 is less than or equal to previous memory size 3346071552
(... lines omitted ...)
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
FAILED: testDisclaimMemoryEffects(5)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap$Values.spliterator(HashMap.java:1046)
	at java.base/java.util.Collection.stream(Collection.java:743)
	at java.management/java.lang.management.ManagementFactory$PlatformMBeanFinder.findSingleton(ManagementFactory.java:990)
	at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:685)
	at java.management/java.lang.management.ManagementFactory.getRuntimeMXBean(ManagementFactory.java:365)
	at j9vm.test.softmx.SoftmxAdvanceTest.runTestDisclaimMemoryEffects(SoftmxAdvanceTest.java:114)
	at j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects(SoftmxAdvanceTest.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by knn-k** [comment]
20x Grinder job finished successfully: https://openj9-jenkins.osuosl.org/job/Grinder/898/

**Comment by dmitripivkine** [comment]
<img width="460" alt="Screen Shot 2022-06-14 at 11 36 44 AM" src="https://user-images.githubusercontent.com/18148831/173618470-4fee1ae5-9191-4bee-945b-6a6adf4a2c3d.png">

**Comment by dmitripivkine** [comment]
Object heap has been contracted as expected. I believe an activity after 300s related to test failure handling.

**Comment by JasonFengJ9** [comment]
[JDK19 aarch64_linux m1 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.functional_aarch64_linux_testList_2/10/)(`ub18-aarch64-1`)
```
[2023-03-22T14:13:23.699Z] variation: Mode601
[2023-03-22T14:13:23.699Z] JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:optthruput 

[2023-03-22T14:14:11.238Z] JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[2023-03-22T14:14:11.239Z] FAILED: testDisclaimMemoryEffects(5)
[2023-03-22T14:14:11.239Z] java.lang.OutOfMemoryError: Java heap space
[2023-03-22T14:14:11.239Z] 	at java.base/java.util.HashMap$Values.spliterator(HashMap.java:1054)
[2023-03-22T14:14:11.239Z] 	at java.base/java.util.Collection.stream(Collection.java:743)
[2023-03-22T14:14:11.239Z] 	at java.management/java.lang.management.ManagementFactory$PlatformMBeanFinder.findSingleton(ManagementFactory.java:994)
[2023-03-22T14:14:11.239Z] 	at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:688)
[2023-03-22T14:14:11.239Z] 	at java.management/java.lang.management.ManagementFactory.getRuntimeMXBean(ManagementFactory.java:366)
[2023-03-22T14:14:11.239Z] 	at j9vm.test.softmx.SoftmxAdvanceTest.runTestDisclaimMemoryEffects(SoftmxAdvanceTest.java:114)
[2023-03-22T14:14:11.239Z] 	at j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects(SoftmxAdvanceTest.java:64)

[2023-03-22T14:14:11.239Z]     testSoftMxDisclaimMemory
[2023-03-22T14:14:11.239Z]     Tests run: 1, Failures: 1, Skips: 0
[2023-03-22T14:14:12.003Z] -----------------------------------
[2023-03-22T14:14:12.003Z] testSoftMxDisclaimMemory_LP4k_2_FAILED
```
