### ISSUE TITLE
jdk19 openjdk java/lang/ClassLoader/Assert.java crash in child process vmstate=0x00040000

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15327]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_OpenJDK19/1/
jdk_lang_1
java/lang/ClassLoader/Assert.java

The failure presents as a timeout, but that's because there was a gpf in the child process.

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_OpenJDK19/1/openjdk_test_output.tar.gz
```
1XHEXCPCODE    J9Generic_Signal_Number: 00000018
1XHEXCPCODE    Signal_Number: 0000000B
1XHEXCPCODE    Error_Value: 00000000
1XHEXCPCODE    Signal_Code: 00000001
1XHEXCPCODE    Handler1: 00007FBEBB2AE880
1XHEXCPCODE    Handler2: 00007FBEBC8325C0
1XHEXCPCODE    InaccessibleAddress: 00000000000004B0
NULL
1XHEXCPMODULE  Module: /lib/x86_64-linux-gnu/libpthread.so.0
1XHEXCPMODULE  Module_base_address: 00007FBEBC342000
1XHEXCPMODULE  Symbol: pthread_mutex_lock
1XHEXCPMODULE  Symbol_address: 00007FBEBC34BD40
NULL
1XHREGISTERS   Registers:
2XHREGISTER      RDI: 00000000000004A0
2XHREGISTER      RSI: 0000000000000000
2XHREGISTER      RAX: 0000000000000000
2XHREGISTER      RBX: 0000000000000000
2XHREGISTER      RCX: 0000000000000000
2XHREGISTER      RDX: 0000000000000000
2XHREGISTER      R8: 00007FBEBC807AF0
2XHREGISTER      R9: 00007FBEBC8DE3E0
2XHREGISTER      R10: 0000000000000000
2XHREGISTER      R11: 00007FBEB9258090
2XHREGISTER      R12: 00007FBEBC807500
2XHREGISTER      R13: 00000000000004A0
2XHREGISTER      R14: 00007FBEBB43B11C
2XHREGISTER      R15: 00007FBE96815070
2XHREGISTER      xmm0: 0000000000000000
2XHREGISTER      xmm1: 0000000000000000
2XHREGISTER      xmm2: 00007FBEBB43B090
2XHREGISTER      xmm3: 0000000000006574
2XHREGISTER      xmm4: 706D497470757272
2XHREGISTER      xmm5: 614A005F5F6C706D
2XHREGISTER      xmm6: 6E695F6461657268
2XHREGISTER      xmm7: 0000000000000007
2XHREGISTER      xmm8: 0000000000000000
2XHREGISTER      xmm9: 00610073005F0039
2XHREGISTER      xmm10: 000000003E8C05E2
2XHREGISTER      xmm11: 000000003C075284
2XHREGISTER      xmm12: 0000000040400000
2XHREGISTER      xmm13: 0000000000000000
2XHREGISTER      xmm14: 0000000000000000
2XHREGISTER      xmm15: 0000000000000000
2XHREGISTER      RIP: 00007FBEBC34BD44
2XHREGISTER      GS: 0000
2XHREGISTER      FS: 0000
2XHREGISTER      RSP: 00007FBE96814D80
2XHREGISTER      EFlags: 0000000000010202
2XHREGISTER      CS: 0033
2XHREGISTER      RBP: 00007FBEB4248588
2XHREGISTER      ERR: 0000000000000004
2XHREGISTER      TRAPNO: 000000000000000E
2XHREGISTER      OLDMASK: 0000000000000000
2XHREGISTER      CR2: 00000000000004B0
NULL
1XHFLAGS       VM flags:0000000000040000

...

1XMCURTHDINFO  Current thread
3XMTHREADINFO      "Attach API teardown" J9VMThread:0x0000000000114B00, omrthread_t:0x00007FBEB4248588, java/lang/Thread:0x00000007FFF9CB88, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x17, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x00000007FFF1C778)
3XMTHREADINFO1            (native thread ID:0x3E98, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007FBE96798000, to:0x00007FBE96819000, size:0x81000)
3XMCPUTIME               CPU usage total: 0.279989271 secs, current category="System-JVM"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=4288 (0x10C0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.interruptImpl(Native Method)
4XESTACKTRACE                at java/lang/Thread.interrupt0(Thread.java:3148)
4XESTACKTRACE                at java/lang/Thread.interrupt(Thread.java:1761)
4XESTACKTRACE                at openj9/internal/tools/attach/target/AttachHandler.terminate(AttachHandler.java:380)
4XESTACKTRACE                at openj9/internal/tools/attach/target/AttachHandler$teardownHook.run(AttachHandler.java:519)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               protectedBacktrace+0x12 (0x00007FBEBC82ECA2 [libj9prt29.so+0x25ca2])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FBEBC8332F1 [libj9prt29.so+0x2a2f1])
4XENATIVESTACK               omrintrospect_backtrace_thread_raw+0xc0 (0x00007FBEBC82F190 [libj9prt29.so+0x26190])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FBEBC8332F1 [libj9prt29.so+0x2a2f1])
4XENATIVESTACK               omrintrospect_backtrace_thread+0x73 (0x00007FBEBC82EB63 [libj9prt29.so+0x25b63])
4XENATIVESTACK               setup_native_thread+0x1e3 (0x00007FBEBC82FF43 [libj9prt29.so+0x26f43])
4XENATIVESTACK               omrintrospect_threads_startDo_with_signal+0x437 (0x00007FBEBC830B77 [libj9prt29.so+0x27b77])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FBEBC8332F1 [libj9prt29.so+0x2a2f1])
4XENATIVESTACK               _ZN18JavaCoreDumpWriter28writeThreadsWithNativeStacksEv+0x400 (0x00007FBEBAC358B0 [libj9dmp29.so+0x198b0])
4XENATIVESTACK               protectedWriteThreadsWithNativeStacks+0xd (0x00007FBEBAC3607D [libj9dmp29.so+0x1a07d])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FBEBC8332F1 [libj9prt29.so+0x2a2f1])
4XENATIVESTACK               _ZN18JavaCoreDumpWriter18writeThreadSectionEv+0x151 (0x00007FBEBAC326B1 [libj9dmp29.so+0x166b1])
4XENATIVESTACK               protectedWriteSection+0x1d (0x00007FBEBAC2D7DD [libj9dmp29.so+0x117dd])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FBEBC8332F1 [libj9prt29.so+0x2a2f1])
4XENATIVESTACK               _ZN18JavaCoreDumpWriterC2EPKcP16J9RASdumpContextP14J9RASdumpAgent+0x3f5 (0x00007FBEBAC2EBB5 [libj9dmp29.so+0x12bb5])
4XENATIVESTACK               runJavadump+0x1c (0x00007FBEBAC38BBC [libj9dmp29.so+0x1cbbc])
4XENATIVESTACK               doJavaDump+0x3f (0x00007FBEBAC2116F [libj9dmp29.so+0x516f])
4XENATIVESTACK               protectedDumpFunction+0x15 (0x00007FBEBAC207C5 [libj9dmp29.so+0x47c5])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FBEBC8332F1 [libj9prt29.so+0x2a2f1])
4XENATIVESTACK               runDumpFunction+0x60 (0x00007FBEBAC23F40 [libj9dmp29.so+0x7f40])
4XENATIVESTACK               runDumpAgent+0x15d (0x00007FBEBAC240BD [libj9dmp29.so+0x80bd])
4XENATIVESTACK               triggerDumpAgents+0x372 (0x00007FBEBAC3B0E2 [libj9dmp29.so+0x1f0e2])
4XENATIVESTACK               generateDiagnosticFiles+0x162 (0x00007FBEBB2AE482 [libj9vm29.so+0x3d482])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FBEBC8332F1 [libj9prt29.so+0x2a2f1])
4XENATIVESTACK               vmSignalHandler+0x17f (0x00007FBEBB2AE60F [libj9vm29.so+0x3d60f])
4XENATIVESTACK               mainSynchSignalHandler+0x225 (0x00007FBEBC8327E5 [libj9prt29.so+0x297e5])
4XENATIVESTACK                (0x00007FBEBC353390 [libpthread.so.0+0x11390])
4XENATIVESTACK               pthread_mutex_lock+0x4 (0x00007FBEBC34BD44 [libpthread.so.0+0x9d44])
4XENATIVESTACK               omrthread_interrupt+0x51 (0x00007FBEBC7FC031 [libj9thr29.so+0xc031])
4XENATIVESTACK               Java_java_lang_Thread_interruptImpl+0x7e (0x00007FBEB925810E [libjclse29.so+0x4b10e])
4XENATIVESTACK               ffi_call_unix64+0x52 (0x00007FBEBB413ECA [libj9vm29.so+0x1a2eca])
4XENATIVESTACK               ffi_call_int+0x1a2 (0x00007FBEBB413062 [libj9vm29.so+0x1a2062])
4XENATIVESTACK               _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0xfb88 (0x00007FBEBB310EE8 [libj9vm29.so+0x9fee8])
4XENATIVESTACK               bytecodeLoopCompressed+0xad (0x00007FBEBB30134D [libj9vm29.so+0x9034d])
4XENATIVESTACK                (0x00007FBEBB3A2492 [libj9vm29.so+0x131492])
```

**Comment by hangshao0** [comment]
RDI is `0x00000000000004A0`

```
1XHREGISTERS   Registers:
2XHREGISTER      RDI: 00000000000004A0
```

The offset of `J9Thread->mutex` is also `0x00000000000004A0`
```
!J9Thread 0x000000000
J9Thread at 0x0 {
  Fields for J9Thread:
        0x0: struct J9ThreadLibrary* library = <FAULT>
       ...
       ...
        0x470: pthread_cond_t condition = !pthread_cond_t 0x0000000000000470
        0x4a0: pthread_mutex_t mutex = !pthread_mutex_t 0x00000000000004A0
```

Might be a NULL `J9Thread` being used here.

**Comment by hangshao0** [comment]
@fengxue-IS If there a NULL check missing here on `targetThread->osThread` in Java 19 and up ?
https://github.com/eclipse-openj9/openj9/blob/b28092a380bc55418fd8b1816c25dcf8ab13cb00/runtime/oti/VMHelpers.hpp#L2040

**Comment by fengxue-IS** [comment]
> @fengxue-IS If there a NULL check missing here on `targetThread->osThread` in Java 19 and up ?
> 
> https://github.com/eclipse-openj9/openj9/blob/b28092a380bc55418fd8b1816c25dcf8ab13cb00/runtime/oti/VMHelpers.hpp#L2040

Virtual Thread have its own [`interrupt()`](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/java/lang/VirtualThread.java#L763) impl, which doesn't call into `interruptImpl` with the VirtualThread object.
I don't see any other caller other than CRIU which isn't part of the stacktrace.
Add a null check here would be a extra guard but I don't think that is what caused the problem

**Comment by hangshao0** [comment]
The first line of `pthread_mutex_lock()` is to load data at `(pthread_mutex)->__data.__kind`
```
!pthread_mutex_t 0x00000000000004A0
pthread_mutex_t at 0x4a0 {
  Fields for pthread_mutex_t:
        0x0: struct __pthread_mutex_s __data = !__pthread_mutex_s 0x00000000000004A0
        0x0: U8[] __size = !j9x 0x00000000000004A0
        0x0: I64 __align = <FAULT>
}
> !__pthread_mutex_s 0x00000000000004A0
__pthread_mutex_s at 0x4a0 {
  Fields for __pthread_mutex_s:
        0x0: I32 __lock = <FAULT>
        0x4: U32 __count = <FAULT>
        0x8: I32 __owner = <FAULT>
        0xc: U32 __nusers = <FAULT>
        0x10: I32 __kind = <FAULT>
```

__kind is at offset `0x10`. 

Notice in the description
`1XHEXCPCODE    InaccessibleAddress: 00000000000004B0`
`2XHREGISTER      RDI: 00000000000004A0`

`0x4A0 + 0x10 = 0x4B0`
So RDI + __kind offset happens to be the inaccessible address.
