### ISSUE TITLE
jdk19 Windows JCL_Test test_runFinalization Failed to run finalization

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15336]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/1 - [win2012-x86-6](https://openj9-jenkins.osuosl.org/computer/win2012-x86-6)
JCL_Test_0
JCL_Test_2
JCL_Test_none_SCC_0
```
19:54:36  FAILED: test_runFinalization
19:54:36  java.lang.AssertionError: Failed to run finalization
19:54:36  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.openj9.test.java.lang.Test_System.test_runFinalization(Test_System.java:264) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
19:54:36  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) from jrt:/java.base
19:54:36  	at java.base/java.lang.reflect.Method.invoke(Method.java:578) from jrt:/java.base
19:54:36  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
19:54:36  	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@60a1b2d9(file:/F:/Users/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_0/aqa-tests/TKG/lib/testng.jar)
```

**Comment by pshipton** [comment]
Re-running the failed tests in a grinder https://openj9-jenkins.osuosl.org/job/Grinder/910/

**Comment by pshipton** [comment]
This is resolved by https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/9
