### ISSUE TITLE
win2019-x64-2 testing issues

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15333]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.functional_x86-64_windows_Nightly_testList_1/89
[win2019-x64-2](https://openj9-jenkins.osuosl.org/computer/win2019-x64-2) - this is a new machine

@vsebe 2 problems:

The build has no TAP results. It shows green although there was a test failure. The parent job has the TAP results.
```
01:15:25  java.io.IOException: Failed to copy F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.functional_x86-64_windows_Nightly_testList_1\aqa-tests\TKG\output_16552615346451\Test_openjdk18_j9_sanity.functional_x86-64_windows_Nightly_testList_1.tap to F:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.functional_x86-64_windows_Nightly_testList_1/aqa-tests/TKG/output_16552615346451/Test_openjdk18_j9_sanity.functional_x86-64_windows_Nightly_testList_1.tap
01:15:25  	at hudson.FilePath.copyTo(FilePath.java:2443)
01:15:25  	at org.tap4j.plugin.TapPublisher.saveReports(TapPublisher.java:599)
01:15:25  	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:436)
01:15:25  	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:403)
01:15:25  	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
01:15:25  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
01:15:25  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
01:15:25  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
01:15:25  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$558/0x0000000000000000.run(Unknown Source)
01:15:25  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
01:15:25  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
01:15:25  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
01:15:25  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
01:15:25  	at java.base/java.lang.Thread.run(Thread.java:836)
01:15:25  Caused by: java.nio.file.AccessDeniedException: /F:
01:15:25  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
01:15:25  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
01:15:25  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
01:15:25  	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
01:15:25  	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
01:15:25  	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
01:15:25  	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
01:15:25  	at hudson.FilePath.mkdirs(FilePath.java:3549)
01:15:25  	at hudson.FilePath.write(FilePath.java:2314)
01:15:25  	at hudson.FilePath.copyTo(FilePath.java:2439)
01:15:25  	... 13 more
01:15:25  Failed to save TAP reports
```

cmdLineTester_getPid_0
```
23:43:45   [ERR] Description = Access denied
23:43:45   [ERR] 
23:43:45   [ERR] Argument "" isn't numeric in numeric eq (==) at F:/Users/jenkins/workspace/Test_openjdk18_j9_sanity.functional_x86-64_windows_Nightly_testList_1/aqa-tests///..//jvmtest/functional/cmdLineTests/runtimemxbeanTests/getPidTest.pl line 75, <GEN1> line 1.
```

**Comment by vsebe** [comment]
Granted remote access to WMI to Jenkins user. `cmdLineTester_getPid_0` passed in [Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/918/console).
