### ISSUE TITLE
jdmpview reports truncated dump and DTFJJavaObject.getJavaClass reports EOFException even though dump appears good

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#15340]
Java -version output
--------------------

Java version of the core dump from `jdmpview` (very old JRE from **2016**!):

```
        *0 : PID: 0 : JRE 1.8.0 AIX ppc64-64 build  (pap6480sr3-20160428_01(SR3) )
[...]
> !coreinfo
[...]
JRE 1.8.0 IBM J9 2.8 AIX ppc64-64 Compressed References 20160427_301573 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160427_1620_B301573
JIT  - tr.r14.java.green_20160329_114288
GC   - R28_Java8_SR3_20160427_1620_B301573_CMPRSS
```

Summary of problem
------------------

AIX core dump produced due to OutOfMemoryError shows the core dump was written without error (translated from Japanese so some artifacts from translation):

```
JVMDUMP013I Handled dump event "systhrow", detail "java / lang / OutOfMemoryError".
JVMDUMP032I The JVM has requested a System dump (using'/core.20220328.092010.15663428.0004.dmp') in response to the event.
JVMDUMP010I System dump was written to /core.20220328.092010.15663428.0004.dmp
```

Loading the dump in `dbx` does not show any truncation warnings:

```
$ cd /ecurep/sf/TS008/716/TS008716589/2022-06-04/TS008716589_20220603.zip_unpack/TS008716589_20220603/snapcore_7340356.pax.Z_unpack/snapcore_7340356.pax_unpack
$ dbx -p /=./ ./usr/IBM/WebSphere/V9.0/AppServer/java/8.0/bin/java core.20220328.092010.15663428.0004.dmp
Type 'help' for help.
[using memory image in core.20220328.092010.15663428.0004.dmp]
reading symbolic information ...warning: no source compiled with -g

Signal 0 in genSystemCoreUsingGencore at 0x900000002034678 ($t59)
0x900000002034678 (genSystemCoreUsingGencore+0x78) e8410028             ld   r2,0x28(r1)
(dbx) 
```

However, loading the dump in IBM Java 8.0.7.0 `jdmpview` **does** show a truncation warning:

```
$ /ecurep/sf/TS008/716/TS008716589/support_files/j864redist.tar.gz_unpack/sdk/bin/jdmpview -core /ecurep/sf/TS008/716/TS008716589/2022-06-04/TS008716589_20220603.zip_unpack/TS008716589_20220603/snapcore_7340356.pax.Z_unpack/snapcore_7340356.pax_unpack/core.20220328.092010.15663428.0004.dmp
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

Warning: dump file is truncated. Extracted information may be incomplete.
```

The size of the dump is 928,250,407 bytes.

Eclipse MAT analysis throws hundreds of exceptions and results in very strange output (e.g. a negative number for heap usage). The first exception in MAT is an EOFException while iterating through `JavaRuntime.getJavaClassLoaders` and calling `getJavaClass` on some classloaders and this is reproduced with a standalone program:

```
import java.io.File;
import java.util.Iterator;
import com.ibm.dtfj.image.Image;
import com.ibm.dtfj.image.ImageAddressSpace;
import com.ibm.dtfj.image.ImageProcess;
import com.ibm.dtfj.image.j9.ImageFactory;
import com.ibm.dtfj.java.JavaClass;
import com.ibm.dtfj.java.JavaClassLoader;
import com.ibm.dtfj.java.JavaObject;
import com.ibm.dtfj.java.JavaRuntime;

public class DTFJAnalyzerClassLoaderInfo {
  @SuppressWarnings("unused")
  public static void main(String[] args) throws Throwable {
    String file = args[0];
    Image image = new ImageFactory().getImage(new File(file));
    Iterator<?> asIt = image.getAddressSpaces();
    while (asIt.hasNext()) {
      ImageAddressSpace as = (ImageAddressSpace) asIt.next();
      Iterator<?> prIt = as.getProcesses();
      while (prIt.hasNext()) {
        ImageProcess process = (ImageProcess) prIt.next();
        Iterator<?> runTimesIt = process.getRuntimes();
        while (runTimesIt.hasNext()) {
          JavaRuntime javaRT = (JavaRuntime) runTimesIt.next();
          Iterator<?> classloadersIt = javaRT.getJavaClassLoaders();
          while (classloadersIt.hasNext()) {
            JavaClassLoader classloader = (JavaClassLoader) classloadersIt.next();
            JavaObject classloaderObject = classloader.getObject();
            JavaClass classloaderObjectClass = classloaderObject.getJavaClass();
          }
        }
      }
    }
  }
}
```

Executed on AIX using IBM Java 8.0.7.0:

```
$ /ecurep/sf/TS008/716/TS008716589/support_files/j864redist.tar.gz_unpack/sdk/bin/java -showversion DTFJAnalyzerObjectClassInfo /ecurep/sf/TS008/716/TS008716589/2022-06-04/TS008716589_20220603.zip_unpack/TS008716589_20220603/snapcore_7340356.pax.Z_unpack/snapcore_7340356.pax_unpack/core.20220328.092010.15663428.0004.dmp
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 8.0.7.10 - pap6480sr7fp10-20220505_01(SR7 FP10))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20220427_27745 (JIT enabled, AOT enabled)
OpenJ9   - b15041a
OMR      - 3671a9f
IBM      - 1b0232b)
JCL - 20220504_01 based on Oracle jdk8u331-b09

Exception in thread "main" com.ibm.j9ddr.view.dtfj.DTFJCorruptDataException: J9DDRCorruptData [as=xcoff : 0 Message: Memory Fault reading 0xD2164F00  Address: 0xd2164f00]
        at com.ibm.j9ddr.view.dtfj.J9DDRDTFJUtils.newCorruptDataException(J9DDRDTFJUtils.java:105)
        at com.ibm.j9ddr.view.dtfj.J9DDRDTFJUtils.handleAsCorruptDataException(J9DDRDTFJUtils.java:225)
        at com.ibm.j9ddr.vm28.view.dtfj.java.DTFJJavaObject.getJavaClass(DTFJJavaObject.java:213)
        at DTFJAnalyzerObjectClassInfo.main(DTFJAnalyzerObjectClassInfo.java:35)
Caused by: com.ibm.j9ddr.corereaders.memory.MemoryFault: Memory Fault reading 0xD2164F00 
        at com.ibm.j9ddr.corereaders.memory.AbstractMemory$CachingMemorySource.loadBlock(AbstractMemory.java:497)
        at com.ibm.j9ddr.corereaders.memory.AbstractMemory$CachingMemorySource.getBytes(AbstractMemory.java:457)
        at com.ibm.j9ddr.corereaders.memory.AbstractMemory.getBytesAt(AbstractMemory.java:192)
        at com.ibm.j9ddr.corereaders.memory.AbstractMemory.getBytesAt(AbstractMemory.java:177)
        at com.ibm.j9ddr.corereaders.memory.AbstractMemory.getIntAt(AbstractMemory.java:227)
        at com.ibm.j9ddr.vm28.pointer.AbstractPointer.getObjectClassAtOffset(AbstractPointer.java:498)
        at com.ibm.j9ddr.vm28.pointer.generated.J9ObjectPointer.clazz(J9ObjectPointer.java:155)
        at com.ibm.j9ddr.vm28.pointer.helper.J9ObjectHelper.clazz(J9ObjectHelper.java:90)
        at com.ibm.j9ddr.vm28.view.dtfj.java.DTFJJavaObject.getJavaClass(DTFJJavaObject.java:210)
        ... 1 more
Caused by: com.ibm.j9ddr.corereaders.memory.MemoryFault: Memory Fault reading 0xD2164C00 
        at com.ibm.j9ddr.corereaders.memory.DumpMemorySource.getBytes(DumpMemorySource.java:113)
        at com.ibm.j9ddr.corereaders.memory.AbstractMemory$CachingMemorySource.loadBlock(AbstractMemory.java:495)
        ... 9 more
Caused by: java.io.EOFException
        at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:364)
        at com.ibm.j9ddr.corereaders.AbstractCoreReader.readFully(AbstractCoreReader.java:135)
        at com.ibm.j9ddr.corereaders.memory.DumpMemorySource.getBytes(DumpMemorySource.java:111)
        ... 10 more
```

Interestingly, loading the dump in 8.0.3.0 `jdmpview` does **not** show a truncation warning:

```
$ /ecurep/sf/TS008/716/TS008716589/support_files/j803064redist.tar.gz_unpack/sdk/bin/jdmpview -core /ecurep/sf/TS008/716/TS008716589/2022-06-04/TS008716589_20220603.zip_unpack/TS008716589_20220603/snapcore_7340356.pax.Z_unpack/snapcore_7340356.pax_unpack/core.20220328.092010.15663428.0004.dmp
DTFJView version 4.28.9, using DTFJ version 1.12.28009
Loading image from DTFJ...

For a list of commands, type "help"; for how to use "help", type "help help"
Available contexts (* = currently selected context) : 

Source : file:///ecurep/sf/TS008/716/TS008716589/2022-06-04/TS008716589_20220603.zip_unpack/TS008716589_20220603/snapcore_7340356.pax.Z_unpack/snapcore_7340356.pax_unpack/core.20220328.092010.15663428.0004.dmp
        *0 : PID: 0 : JRE 1.8.0 AIX ppc64-64 build  (pap6480sr3-20160428_01(SR3) )
```

However, running the DTFJAnalyzerClassLoaderInfo with IBM Java 8.0.3.0 shows the same EOFException and a custom build of MAT with the DTFJ from IBM Java 8.0.3.0 shows the same issues.

I'm not sure if this is correct or relevant, but I also created a program to find all memory regions and dump the highest one:

```
import java.io.File;
import java.util.Iterator;
import com.ibm.dtfj.image.Image;
import com.ibm.dtfj.image.ImageAddressSpace;
import com.ibm.dtfj.image.ImageProcess;
import com.ibm.dtfj.image.j9.ImageFactory;
import com.ibm.dtfj.java.JavaRuntime;
import com.ibm.dtfj.java.JavaRuntimeMemorySection;

public class DTFJAnalyzerMemoryRegions {
  @SuppressWarnings("unused")
  public static void main(String[] args) throws Throwable {
    String file = args[0];
    Image image = new ImageFactory().getImage(new File(file));
    Iterator<?> asIt = image.getAddressSpaces();
    while (asIt.hasNext()) {
      ImageAddressSpace as = (ImageAddressSpace) asIt.next();
      Iterator<?> prIt = as.getProcesses();
      while (prIt.hasNext()) {
        ImageProcess process = (ImageProcess) prIt.next();
        Iterator<?> runTimesIt = process.getRuntimes();
        while (runTimesIt.hasNext()) {
          JavaRuntime javaRT = (JavaRuntime) runTimesIt.next();
          Iterator<?> classloadersIt = javaRT.getJavaClassLoaders();
          Iterator<?> memorySectionsIt = javaRT.getMemorySections(true);
          long largestStart = -1;
          long largestEnd = -1;
          while (memorySectionsIt.hasNext()) {
            JavaRuntimeMemorySection memorySection = (JavaRuntimeMemorySection) memorySectionsIt.next();
            long start = memorySection.getBaseAddress().getAddress();
            long end = start + memorySection.getSize();
            if (start > largestStart) {
              largestStart = start;
            }
            if (end > largestEnd) {
              largestEnd = end;
            }
          }
          System.out.println("Largest start = 0x" + Long.toString(largestStart, 16));
          System.out.println("Largest end = 0x" + Long.toString(largestEnd, 16));
        }
      }
    }
  }
}
```

This shows:

```
Largest start = 0x100316be770
Largest end = 0x100316c0780
```

And dumping memory in `dbx` from right before the largest end address doesn't show any obvious issues:

```
(dbx) 0x100316c0770/1X
0x00000100316c0770:  642e9645
```

Diagnostic files
----------------

Internal case TS008716589

* Dump: `/ecurep/sf/TS008/716/TS008716589/2022-06-04/TS008716589_20220603.zip_unpack/TS008716589_20220603/snapcore_7340356.pax.Z_unpack/core.20220328.092010.15663428.0004.dmp`

CC @keithc-ca @SwathiKalahastri

**Comment by pshipton** [comment]
> Interestingly, loading the dump in 8.0.3.0 jdmpview does not show a truncation warning:

The truncation warning is a newer feature.

**Comment by keithc-ca** [comment]
Detection of truncated core files from AIX has been around for a long time, but as Peter says, reporting that is new.

Core files from AIX reported as truncated either:
* have the 'truncated' flag in the second byte of the file; see [AIXDumpReader.java](https://github.com/eclipse-openj9/openj9/blob/master/debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/aix/AIXDumpReader.java#L170)
* describe a region of virtual memory that is not included within the core dump; see [AIXDumpReader.java](https://github.com/eclipse-openj9/openj9/blob/master/debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/aix/AIXDumpReader.java#L227)
