### ISSUE TITLE
jdk19 java.util.function.Predicate.lambda$negate$1 NullPointerException: Cannot invoke "java.lang.Class.getName()" because "instanceClass" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15355]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_OpenJDK19/2
jdk11_tier1_cipher_1 `-XX:-UseCompressedOops`
com/sun/crypto/provider/Cipher/AES/CTR.java

```
17:50:40  stderr:
17:50:40  java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "instanceClass" is null
17:50:40  	at java.base/java.lang.ClassCastException.<init>(ClassCastException.java:71)
17:50:40  	at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
17:50:40  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
17:50:40  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
17:50:40  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
17:50:40  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
17:50:40  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
17:50:40  	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
17:50:40  	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
17:50:40  	at java.base/java.lang.Thread.getAllThreads(Thread.java:2704)
17:50:40  	at java.base/java.lang.ThreadGroup.activeCount(ThreadGroup.java:377)
17:50:40  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.liveThreads(MainActionHelper.java:422)
17:50:40  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.cleanup(MainActionHelper.java:380)
17:50:40  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.access$000(MainActionHelper.java:345)
17:50:40  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:214)
17:50:40  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
17:50:40  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
17:50:40  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
```

FYI https://github.com/eclipse-openj9/openj9/issues/15324

**Comment by pshipton** [comment]
Set high priority since this is blocking sanity.openjdk testing from running green.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_OpenJDK19/6
java/lang/RuntimeTests/exec/ExitValue.java

**Comment by pshipton** [comment]
https://github.com/eclipse-openj9/openj9/issues/15519 has a stack with a completed ClassCastException rather than a NPE.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_OpenJDK19/6
java/util/Map/MapFactories.java

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_OpenJDK19/8
java/lang/System/SecurityManagerWarnings.java
```
04:28:34  java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "instanceClass" is null
04:28:34  	at java.base/java.lang.ClassCastException.<init>(ClassCastException.java:71)
04:28:34  	at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_OpenJDK19/8/
java/lang/System/i18nEnvArg.java
```
00:04:09  java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "instanceClass" is null
00:04:09  	at java.base/java.lang.ClassCastException.<init>(ClassCastException.java:71)
00:04:09  	at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_OpenJDK19/8
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_OpenJDK19/8
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_OpenJDK19/8

**Comment by pshipton** [comment]
Closed https://github.com/eclipse-openj9/openj9/issues/15269 as a dup of this.

**Comment by pshipton** [comment]
Closing, assuming this is a dup of https://github.com/eclipse-openj9/openj9/issues/15321
