### ISSUE TITLE
java.lang.NoClassDefFoundError: ejv (initialization failure)

### ISSUE THREAD

**Issue by ConaII** [eclipse-openj9/openj9#15360]
There's this issue when trying to use OpenJ9 JDK 17 and joining a server (sometimes).
This doesn't happen in OpenJ9 JDK 16 or other distributions.

It seems there's a class missing that is trying to be called.
https://pastebin.com/h10PtA7p

**Comment by pshipton** [comment]
It's not a missing class, it's a NullPointerException. On what version of the JVM does this occur, does it still occur with the latest 17.0.3? 
```
Cliente> [15:28:09] [Render thread/INFO]: Connecting to 26.77.128.193, 25567
Cliente> [15:28:09] [Server Connector #1/ERROR]: Caught previously unhandled exception :
Cliente> java.lang.NoClassDefFoundError: ejv (initialization failure)
Cliente>    at java.lang.J9VMInternals.initializationAlreadyFailed(Unknown Source) ~[?:?]
Cliente>    at dzq$1.run(SourceFile:65) ~[dzq$1.class:?]
Cliente> Caused by: java.nio.charset.CoderMalfunctionError: java.lang.NullPointerException
Cliente>    at java.nio.charset.CharsetDecoder.decode(Unknown Source) ~[?:?]
Cliente>    at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:?]
Cliente>    at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:?]
Cliente>    at java.io.InputStreamReader.read(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader.fill(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader.readLine(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader.readLine(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader$1.hasNext(Unknown Source) ~[?:?]
Cliente>    at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
Cliente>    at com.mojang.patchy.MojangBlockListSupplier.createBlockList(MojangBlockListSupplier.java:25) ~[MojangBlockListSupplier.class:?]
Cliente>    at ejr$$Lambda$4094/0x00000000ffc08fc8.apply(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
Cliente>    at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
Cliente>    at ejr.a(SourceFile:20) ~[ejr.class:?]
Cliente>    at ejv.<clinit>(SourceFile:8) ~[ejv.class:?]
Cliente>    at ejp.a(SourceFile:60) ~[ejp.class:?]
Cliente>    at ede$d.e(SourceFile:249) ~[ede$d.class:?]
Cliente>    at ede$d$$Lambda$4063/0x00000000ff467f90.run(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
Cliente>    at java.lang.Thread.run(Unknown Source) [?:?]
Cliente> Caused by: java.lang.NullPointerException
Cliente>    at sun.nio.cs.ISO_8859_1$Decoder.decodeArrayLoop(Unknown Source) ~[?:?]
Cliente>    at sun.nio.cs.ISO_8859_1$Decoder.decodeLoop(Unknown Source) ~[?:?]
Cliente>    at java.nio.charset.CharsetDecoder.decode(Unknown Source) ~[?:?]
Cliente>    at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:?]
Cliente>    at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:?]
Cliente>    at java.io.InputStreamReader.read(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader.fill(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader.readLine(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader.readLine(Unknown Source) ~[?:?]
Cliente>    at java.io.BufferedReader$1.hasNext(Unknown Source) ~[?:?]
Cliente>    at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
Cliente>    at com.mojang.patchy.MojangBlockListSupplier.createBlockList(MojangBlockListSupplier.java:25) ~[MojangBlockListSupplier.class:?]
Cliente>    at ejr$$Lambda$4094/0x00000000ffc08fc8.apply(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
Cliente>    at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
Cliente>    at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
Cliente>    at ejr.a(SourceFile:20) ~[ejr.class:?]
Cliente>    at ejv.<clinit>(SourceFile:8) ~[ejv.class:?]
Cliente>    at ejp.a(SourceFile:60) ~[ejp.class:?]
Cliente>    at ede$d.e(SourceFile:249) ~[ede$d.class:?]
Cliente>    at ede$d$$Lambda$4063/0x00000000ff467f90.run(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
Cliente>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
Cliente>    at java.lang.Thread.run(Unknown Source) ~[?:?]
```
