### ISSUE TITLE
JCL_Test test_join2 Joined thread is still alive

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15379]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_1/293
JCL_Test_1 `-XX:RecreateClassfileOnload`
```
20:19:02  FAILED: test_join2
20:19:02  java.lang.AssertionError: Joined thread is still alive
20:19:02  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@1421cef5(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_1/aqa-tests/TKG/lib/testng.jar)
20:19:02  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@1421cef5(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_1/aqa-tests/TKG/lib/testng.jar)
20:19:02  	at org.openj9.test.java.lang.Test_Thread.test_join2(Test_Thread.java:646) from jdk.internal.loader.ClassLoaders$AppClassLoader@1421cef5(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Nightly_testList_1/441

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_1/691

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_Release_testList_1/128/consoleFull
```
22:14:09  Running test JCL_Test_SE80_1 ...
22:14:09  ===============================================
22:14:09  JCL_Test_SE80_1 Start Time: Sun Jun 15 01:51:00 2025 Epoch Time (ms): 1749952260967
22:14:09  variation: -XX:RecreateClassfileOnload
22:14:09  JVM_OPTIONS:  -XX:RecreateClassfileOnload 

22:15:00  FAILED: test_join2
22:15:00  java.lang.AssertionError: Joined thread is still alive
22:15:00  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.openj9.test.java.lang.Test_Thread.test_join2(Test_Thread.java:620) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_Release_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
22:15:00  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_Release_testList_1/jdkbinary/j2sdk-image/jre/lib/rt.jar
22:15:00  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_Release_testList_1/jdkbinary/j2sdk-image/jre/lib/rt.jar
22:15:00  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_Release_testList_1/jdkbinary/j2sdk-image/jre/lib/rt.jar
22:15:00  	at java.lang.reflect.Method.invoke(Method.java:503) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_Release_testList_1/jdkbinary/j2sdk-image/jre/lib/rt.jar
22:15:00  	at <unknown class>.<unknown method>(Unknown Source)
22:15:00  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestRunner.privateRun(TestRunner.java:648) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestRunner.run(TestRunner.java:505) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestNG.runSuites(TestNG.java:1049) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestNG.run(TestNG.java:1017) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestNG.privateMain(TestNG.java:1354) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  	at org.testng.TestNG.main(TestNG.java:1323) from sun.misc.Launcher$AppClassLoader@41d54e9e(file:/home/jenkins/testDependency/lib/testng.jar)
22:15:00  
22:15:00  
22:15:00  ===============================================
22:15:00      JCL_TEST_Java-Lang
22:15:00      Tests run: 356, Failures: 1, Skips: 0
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_0/746
