### ISSUE TITLE
JDK 18/19 sun/security/ec/ECDSAPrvGreaterThanOrder.java - RuntimeException: Expected exception for ECDH/secp256r1 not thrown

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15413]
Failure link
------------

From an internal build `job/Test_openjdk19_j9_extended.openjdk_x86-64_mac_Personal/2/`(`mac11x64rt01`):
```
23:51:25  openjdk version "19-internal" 2022-09-20
23:51:25  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDK19x86-64macPersonal)
23:51:25  Eclipse OpenJ9 VM (build master-ac82c9067c5, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220622_4 (JIT enabled, AOT enabled)
23:51:25  OpenJ9   - ac82c9067c5
23:51:25  OMR      - 342963cee6d
23:51:25  JCL      - abd1f9e6083 based on jdk-19+27)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK19_x86-64_mac_Personal%2F4%2FOpenJ9-JDK19-x86-64_mac-20220622-232019.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK19_x86-64_mac_Personal%2F4%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk19.git&OPENJ9_BRANCH=master&OPENJ9_SHA=ac82c9067c5a4983407b1d2996b98f8f5714968c&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.is.osx.10_11%26%26%21sw.os.mac.10_11&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
01:04:37  ===============================================
01:04:37  Running test jdk_security3_1 ...
01:04:37  ===============================================
01:04:37  jdk_security3_1 Start Time: Thu Jun 23 01:04:36 2022 Epoch Time (ms): 1655960676176
01:04:37  "/Users/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_mac_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_mac_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
01:04:37  JVMSHRC005I No shared class caches available
01:04:37  JVMSHRC005I No shared class caches available
01:04:37  cache cleanup done
01:04:37  variation: Mode650
01:04:37  JVM_OPTIONS:  -XX:-UseCompressedOops 

01:09:54  TEST: sun/security/ec/ECDSAPrvGreaterThanOrder.java

01:09:54  STDOUT:
01:09:54  Creating private key for curve secp256r1
01:09:54  Order is: 115792089210356248762697446949407573529996955224135760342422259061068512044369
01:09:54  Modified d Value is: 115792089210356248762697446949407573529996955224135760342422259061068512044371
01:09:54  Caught expected exception for ECDSA/SHA256withECDSA/secp256r1: java.security.InvalidKeyException: The private key must be within the range [1, n - 1]
01:09:54  STDERR:
01:09:54  java.lang.RuntimeException: Expected exception for ECDH/secp256r1 not thrown.
01:09:54  	at ECDSAPrvGreaterThanOrder.main(ECDSAPrvGreaterThanOrder.java:71)
01:09:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
01:09:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
01:09:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
01:09:54  	at java.base/java.lang.Thread.run(Thread.java:1572)
01:09:54  
01:09:54  JavaTest Message: Test threw exception: java.lang.RuntimeException
01:09:54  JavaTest Message: shutting down test
01:09:54  
01:09:54  
01:09:54  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected exception for ECDH/secp256r1 not thrown.
01:09:54  --------------------------------------------------
01:32:43  Test results: passed: 864; failed: 1
01:32:47  Report written to /Users/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_mac_Personal/jvmtest/openjdk/report/html/report.html
01:32:47  Results written to /Users/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_mac_Personal/aqa-tests/TKG/output_16559564093084/jdk_security3_1/work
01:32:47  Error: Some tests failed or other problems occurred.
01:32:47  
01:32:47  jdk_security3_1_FAILED
```

**Comment by JasonFengJ9** [comment]
Observed at JDK18 as well - `job/Test_openjdk18_j9_extended.openjdk_x86-64_linux/27/`(`ub20x64rt3-8`)
```
openjdk version "18.0.1.1" 2022-04-22
IBM Semeru Runtime Open Edition 18.0.1.1+2 (build 18.0.1.1+2)
Eclipse OpenJ9 VM 18.0.1.1+2 (build master-79f0b73fa, JRE 18 Linux amd64-64-Bit Compressed References 20220702_15 (JIT enabled, AOT enabled)
OpenJ9   - 79f0b73fa
OMR      - d018241d7
JCL      - 8c019e1aa5 based on jdk-18.0.1.1+2)

[2022-07-02T18:54:45.677Z] STDERR:
[2022-07-02T18:54:45.677Z] java.lang.RuntimeException: Expected exception for ECDH/secp256r1 not thrown.
[2022-07-02T18:54:45.677Z] 	at ECDSAPrvGreaterThanOrder.main(ECDSAPrvGreaterThanOrder.java:71)
[2022-07-02T18:54:45.677Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-02T18:54:45.677Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-07-02T18:54:45.677Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-07-02T18:54:45.677Z] 	at java.base/java.lang.Thread.run(Thread.java:862)
[2022-07-02T18:54:45.677Z] 
[2022-07-02T18:54:45.677Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-07-02T18:54:45.677Z] JavaTest Message: shutting down test
[2022-07-02T18:54:45.677Z] 
[2022-07-02T18:54:45.678Z] 
[2022-07-02T18:54:45.678Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected exception for ECDH/secp256r1 not thrown.
[2022-07-02T18:54:45.678Z] --------------------------------------------------
[2022-07-02T19:38:23.676Z] Test results: passed: 840; failed: 1
[2022-07-02T19:38:23.676Z] Report written to /home/jenkins/workspace/Test_openjdk18_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2022-07-02T19:38:23.676Z] Results written to /home/jenkins/workspace/Test_openjdk18_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16567767049234/jdk_security3_1/work
[2022-07-02T19:38:23.676Z] Error: Some tests failed or other problems occurred.
[2022-07-02T19:38:23.676Z] 
[2022-07-02T19:38:23.676Z] jdk_security3_1_FAILED
```

**Comment by keithc-ca** [comment]
FYI @zainabf92
