### ISSUE TITLE
JDK19 VmArgumentTests_0_FAILED FAILED: testMemoryLeaks - AssertionError: -Xcheck:memory failed: stderr = WARNING: 4559 unfreed blocks remaining at shutdown!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15415]
Failure link
------------

From an internal build `job/Test_openjdk19_j9_extended.functional_x86-64_mac_Personal/2/tapResults/`(`osxrt3`):
```
23:52:01  openjdk version "19-internal" 2022-09-20
23:52:01  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDK19x86-64macPersonal)
23:52:01  Eclipse OpenJ9 VM (build master-ac82c9067c5, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220622_4 (JIT enabled, AOT enabled)
23:52:01  OpenJ9   - ac82c9067c5
23:52:01  OMR      - 342963cee6d
23:52:01  JCL      - abd1f9e6083 based on jdk-19+27)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK19_x86-64_mac_Personal%2F4%2FOpenJ9-JDK19-x86-64_mac-20220622-232019.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK19_x86-64_mac_Personal%2F4%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk19.git&OPENJ9_BRANCH=master&OPENJ9_SHA=ac82c9067c5a4983407b1d2996b98f8f5714968c&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.is.osx.10_11%26%26%21sw.os.mac.10_11&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test VmArgumentTests_0 ...
===============================================
VmArgumentTests_0 Start Time: Thu Jun 23 00:22:09 2022 Epoch Time (ms): 1655958129240
variation: NoOptions
JVM_OPTIONS:  

FAILED: testMemoryLeaks
java.lang.AssertionError: -Xcheck:memory failed: stderr = WARNING: 4559 unfreed blocks remaining at shutdown!

4559 allocated blocks totaling 25790249 bytes were not freed before shutdown!

	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.vmArguments.VmArgumentTests.testMemoryLeaks(VmArgumentTests.java:1299)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    VmArgumentTests
    Tests run: 54, Failures: 1, Skips: 0
===============================================


===============================================
GeneralTest suite
Total tests run: 54, Failures: 1, Skips: 0
===============================================


VmArgumentTests_0_FAILED
```

**Comment by tajila** [comment]
@JasonFengJ9 Does this still fail?

**Comment by JasonFengJ9** [comment]
> Does this still fail?

It passes in [latest run](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.functional_x86-64_mac_testList_0/44/tapResults)
Closing
