### ISSUE TITLE
JDK19 Windows Segmentation error ntdll.dll

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15504]
Failure link
------------

From an internal build `job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_0/6/`(`win10x64vs6 `):
```
openjdk version "19-beta" 2022-09-20
IBM Semeru Runtime Open Edition 19+28-202207050540 (build 19-beta+28-202207050540)
Eclipse OpenJ9 VM 19+28-202207050540 (build master-0e480f25e, JRE 19 Windows 10 amd64-64-Bit Compressed References 20220705_11 (JIT enabled, AOT enabled)
OpenJ9   - 0e480f25e
OMR      - d018241d7
JCL      - 28e60ccf5a based on jdk-19+28)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_sanity.openjdk_x86-64_windows&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F11%2Fibm-semeru-open-jre_x64_windows_JDK19U_2022-07-05-05-31.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F11%2Fibm-semeru-open-jdk_x64_windows_JDK19U_2022-07-05-05-31.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F11%2Fibm-semeru-open-debugimage_x64_windows_JDK19U_2022-07-05-05-31.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F11%2Fibm-semeru-open-testimage_x64_windows_JDK19U_2022-07-05-05-31.zip&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=6&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-05T08:03:12.090Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-07-05T08:03:12.090Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-07-05T08:06:44.254Z] TEST: java/util/Locale/bcp47u/SystemPropertyTests.java

[2022-07-05T08:06:44.255Z] Output and diagnostic info for process 9436 was saved into 'pid-9436-output.log'
[2022-07-05T08:06:44.255Z] 
[2022-07-05T08:06:44.255Z] Unhandled exception
[2022-07-05T08:06:44.255Z] Type=Segmentation error vmState=0x00040000
[2022-07-05T08:06:44.255Z] Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FF9EBD3FAAD ContextFlags=0010005f
[2022-07-05T08:06:44.255Z] Handler1=00007FF9CFF571D0 Handler2=00007FF9D343A960 InaccessibleWriteAddress=0000000000000480
[2022-07-05T08:06:44.255Z] RDI=000002085E18B990 RSI=0000000000000478 RAX=00000033C4B24000 RBX=0000000000000000
[2022-07-05T08:06:44.255Z] RCX=0000000000000478 RDX=0000000000000004 R8=00000033C717ED68 R9=00007FF9D34DAC10
[2022-07-05T08:06:44.255Z] R10=0000000000000000 R11=0000000000000246 R12=00000033C717F000 R13=00000033C717F000
[2022-07-05T08:06:44.255Z] R14=00000033C717EFD8 R15=00007FF9D0C32550
[2022-07-05T08:06:44.255Z] RIP=00007FF9EBD3FAAD RSP=00000033C717ECF0 RBP=0000000000000004 EFLAGS=0000000000010206
[2022-07-05T08:06:44.255Z] FS=0053 ES=002B DS=002B
[2022-07-05T08:06:44.255Z] XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-07-05T08:06:44.255Z] Module=C:\WINDOWS\SYSTEM32\ntdll.dll
[2022-07-05T08:06:44.255Z] Module_base_address=00007FF9EBD10000 Offset_in_DLL=000000000002faad
[2022-07-05T08:06:44.255Z] Target=2_90_20220705_11 (Windows 10 10.0 build 19042)
[2022-07-05T08:06:44.255Z] CPU=amd64 (16 logical CPUs) (0x3fff06000 RAM)
[2022-07-05T08:06:44.255Z] ----------- Stack Backtrace -----------
[2022-07-05T08:06:44.255Z] RtlEnterCriticalSection+0xd (0x00007FF9EBD3FAAD [ntdll+0x2faad])
[2022-07-05T08:06:44.255Z] omrthread_get_category+0x47c6 (0x00007FF9E4C87FB6 [j9thr29+0x7fb6])
[2022-07-05T08:06:44.255Z] omrthread_interrupt+0x5d (0x00007FF9E4C81C9D [j9thr29+0x1c9d])
[2022-07-05T08:06:44.255Z] Java_java_lang_Thread_interruptImpl+0x9e (0x00007FF9D0C325EE [jclse29+0x425ee])
[2022-07-05T08:06:44.255Z] ffi_call_go+0x3d1 (0x00007FF9D0024241 [j9vm29+0x194241])
[2022-07-05T08:06:44.255Z] ffi_call_go+0x20d (0x00007FF9D002407D [j9vm29+0x19407d])
[2022-07-05T08:06:44.255Z] ffi_call_go+0x22 (0x00007FF9D0023E92 [j9vm29+0x193e92])
[2022-07-05T08:06:44.255Z] (0x00007FF9CFECB886 [j9vm29+0x3b886])
[2022-07-05T08:06:44.255Z] (0x00000033C717F190)
[2022-07-05T08:06:44.255Z] (0x00000033C717F1B0)
[2022-07-05T08:06:44.255Z] (0x00000033C717F1A0)
[2022-07-05T08:06:44.255Z] (0x00000033C717F190)
[2022-07-05T08:06:44.255Z] (0x00000033C717EF40)
[2022-07-05T08:06:44.255Z] ---------------------------------------
[2022-07-05T08:06:44.255Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2022/07/05 04:06:28 - please wait.

[2022-07-05T08:22:02.985Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure
[2022-07-05T08:22:02.985Z] --------------------------------------------------
[2022-07-05T08:22:02.985Z] Test results: passed: 909; failed: 3
[2022-07-05T08:22:18.092Z] Report written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_0\jvmtest\openjdk\report\html\report.html
[2022-07-05T08:22:18.092Z] Results written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_0\aqa-tests\TKG\output_1657007103650\jdk_util_1\work
[2022-07-05T08:22:18.092Z] Error: Some tests failed or other problems occurred.
[2022-07-05T08:22:18.092Z] 
[2022-07-05T08:22:18.092Z] jdk_util_1_FAILED
```

50x grinder - `job/Grinder/25569/` - passed

**Comment by pshipton** [comment]
@tajila fyi

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Personal/3
jdk_util_0
java/util/concurrent/forkjoin/AsyncShutdownNow.java
```
10:30:19  Unhandled exception
10:30:19  Type=Segmentation error vmState=0x00000000
10:30:19  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFFB9FBE4EB ContextFlags=0010005f
10:30:19  Handler1=00007FFF91E79D90 Handler2=00007FFF959AA960 InaccessibleWriteAddress=0000000000000024
10:30:19  RDI=0000000000000000 RSI=0000000000000000 RAX=FFFFFFFFFFFFFFFF RBX=000001A97B453570
10:30:19  RCX=0000000000000000 RDX=FFFFFFFFFFFFFFFF R8=00000000FFFFFFFA R9=0000003286945300
10:30:19  R10=0000000000000000 R11=000000328897F4A0 R12=0000000000000000 R13=FFFFFFFFFFFFFFFF
10:30:19  R14=0000003286888000 R15=0000000000000000
10:30:19  RIP=00007FFFB9FBE4EB RSP=000000328897F4C0 RBP=0000000000000001 EFLAGS=0000000000010213
10:30:19  FS=0053 ES=002B DS=002B
10:30:19  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM8 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
10:30:19  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:30:19  Module=C:\Windows\SYSTEM32\ntdll.dll
10:30:19  Module_base_address=00007FFFB9F60000 Offset_in_DLL=000000000005e4eb
10:30:19  Target=2_90_20220728_21 (Windows Server 2019 10.0 build 17763)
10:30:19  CPU=amd64 (8 logical CPUs) (0x3ffb9c000 RAM)
10:30:19  ----------- Stack Backtrace -----------
10:30:19  RtlDllShutdownInProgress+0x9b (0x00007FFFB9FBE4EB [ntdll+0x5e4eb])
10:30:19  RtlEnterCriticalSection+0x12c (0x00007FFFB9F7449C [ntdll+0x1449c])
10:30:19  RtlEnterCriticalSection+0x40 (0x00007FFFB9F743B0 [ntdll+0x143b0])
10:30:19  omrthread_get_category+0x47c6 (0x00007FFF9D3F7FB6 [j9thr29+0x7fb6])
10:30:19  omrthread_interrupt+0x5d (0x00007FFF9D3F1C9D [j9thr29+0x1c9d])
10:30:19  Java_java_lang_Thread_interruptImpl+0x9e (0x00007FFF9334261E [jclse29+0x4261e])
10:30:19  (0x00007FFF7C8E6740)
10:30:19  (0x0000000000080200)
10:30:19  (0x000000328897F9C0)
10:30:19  (0x0000000000137B00)
10:30:19  (0x0000000000335300)
10:30:19  (0x000000009FC61B30)
10:30:19  (0x0000000000427100)
10:30:19  (0x000000009FF2E208)
10:30:19  (0x00000000FFBBD848)
10:30:19  ---------------------------------------
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly/7
jdk_lang_1
java/lang/ProcessBuilder/Basic.java#id0

```
23:01:51  Passed = 9256, failed = 2
23:01:51  
23:01:51  STDERR:
23:01:51  >'9'< not equal to '0'
23:01:51  java.lang.Exception: Stack trace
23:01:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:2277)
23:01:51  	at Basic.fail(Basic.java:2860)
23:01:51  	at Basic.fail(Basic.java:2861)
23:01:51  	at Basic.equal(Basic.java:2867)
23:01:51  	at Basic.testIORedirection(Basic.java:1226)
23:01:51  	at Basic.realMain(Basic.java:1339)
23:01:51  	at Basic.main(Basic.java:2870)
23:01:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
23:01:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
23:01:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:01:51  	at java.base/java.lang.Thread.run(Thread.java:1573)
23:01:51  >'standard errorUnhandled exception
23:01:51  Type=Segmentation error vmState=0x00040000
23:01:51  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFF3569B289 ContextFlags=0010005f
23:01:51  Handler1=00007FFF234EB000 Handler2=00007FFF233CAA10 InaccessibleWriteAddress=0000000000000480
23:01:51  RDI=000000FDB6A726A0 RSI=0000000000000478 RAX=00007FF639596000 RBX=0000000000000000
23:01:51  RCX=0000000000000478 RDX=0000000000000004 R8=000000FDD6AAEDD8 R9=00007FFF2368C9D0
23:01:51  R10=0000000000000000 R11=0000000000000246 R12=000000FDD6AAF090 R13=000000FDD6AAF110
23:01:51  R14=000000FDD6AAF068 R15=00007FFF219F25F0
23:01:51  RIP=00007FFF3569B289 RSP=000000FDD6AAED88 RBP=0000000000000004 EFLAGS=0000000000010246
23:01:51  FS=0053 ES=002B DS=002B
23:01:51  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:01:51  Module=C:\Windows\SYSTEM32\ntdll.dll
23:01:51  Module_base_address=00007FFF35660000 Offset_in_DLL=000000000003b289
23:01:51  Target=2_90_20220914_72 (Windows Server 2012 R2 6.3 build 9600)
23:01:51  CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
23:01:51  ----------- Stack Backtrace -----------
23:01:51  RtlEnterCriticalSection+0x9 (0x00007FFF3569B289 [ntdll+0x3b289])
23:01:51  omrthread_get_category+0x47c6 (0x00007FFF255D7FB6 [j9thr29+0x7fb6])
23:01:51  omrthread_interrupt+0x5d (0x00007FFF255D1C9D [j9thr29+0x1c9d])
23:01:51  Java_java_lang_Thread_interruptImpl+0xa1 (0x00007FFF219F2691 [jclse29+0x42691])
23:01:51  ffi_call_go+0x3d1 (0x00007FFF235BB051 [j9vm29+0x19b051])
23:01:51  ffi_call_go+0x20d (0x00007FFF235BAE8D [j9vm29+0x19ae8d])
23:01:51  ffi_call_go+0x22 (0x00007FFF235BACA2 [j9vm29+0x19aca2])
23:01:51  (0x00007FFF2343A2A8 [j9vm29+0x1a2a8])
23:01:51  (0x000000FDD6AAF220)
23:01:51  (0x000000FDD6AAF240)
23:01:51  (0x000000FDD6AAF230)
23:01:51  (0x000000FDC254B5C1)
23:01:51  (0x000000FDD6AAEFD0)
23:01:51  ---------------------------------------
```

**Comment by pshipton** [comment]
Another one https://github.com/eclipse-openj9/openj9/issues/16030

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly/25
jdk_util_0
java/util/concurrent/forkjoin/AsyncShutdownNow.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly/25/openjdk_test_output.tar.gz
```
23:02:09  stderr:
23:02:09  Unhandled exception
23:02:09  Type=Segmentation error vmState=0x00000000
23:02:09  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFB92D9E4EB ContextFlags=0010005f
23:02:09  Handler1=00007FFB77F8C230 Handler2=00007FFB7889AA10 InaccessibleWriteAddress=0000000000000024
23:02:09  RDI=0000000000000000 RSI=0000000000000000 RAX=FFFFFFFFFFFFFFFF RBX=000002C73A5D09E0
23:02:09  RCX=0000000000000000 RDX=FFFFFFFFFFFFFFFF R8=00000000FFFFFFFA R9=000000FDEC89D300
23:02:09  R10=0000000000000000 R11=000000FDECDFF420 R12=0000000000000000 R13=FFFFFFFFFFFFFFFF
23:02:09  R14=000000FDEC83C000 R15=0000000000000000
23:02:09  RIP=00007FFB92D9E4EB RSP=000000FDECDFF440 RBP=0000000000000001 EFLAGS=0000000000010213
23:02:09  FS=0053 ES=002B DS=002B
23:02:09  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM8 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
23:02:09  XMM9 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
23:02:09  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:02:09  Module=C:\Windows\SYSTEM32\ntdll.dll
23:02:09  Module_base_address=00007FFB92D40000 Offset_in_DLL=000000000005e4eb
23:02:09  Target=2_90_20221010_105 (Windows Server 2019 10.0 build 17763)
23:02:09  CPU=amd64 (8 logical CPUs) (0x3ffb9c000 RAM)
23:02:09  ----------- Stack Backtrace -----------
23:02:09  RtlDllShutdownInProgress+0x9b (0x00007FFB92D9E4EB [ntdll+0x5e4eb])
23:02:09  RtlEnterCriticalSection+0x12c (0x00007FFB92D5449C [ntdll+0x1449c])
23:02:09  RtlEnterCriticalSection+0x40 (0x00007FFB92D543B0 [ntdll+0x143b0])
23:02:09  omrthread_get_category+0x47c6 (0x00007FFB788F7FB6 [j9thr29+0x7fb6])
23:02:09  omrthread_interrupt+0x5d (0x00007FFB788F1C9D [j9thr29+0x1c9d])
23:02:09  Java_java_lang_Thread_interruptImpl+0xa1 (0x00007FFB772A2751 [jclse29+0x42751])
23:02:09  (0x00007FFB62AB8B08)
23:02:09  (0x00000000004B6000)
23:02:09  (0x000000FDECDFF7F0)
23:02:09  (0x000000000013A200)
23:02:09  (0x0000000000339200)
23:02:09  (0x00000000A03DAB80)
23:02:09  (0x00000000006F6400)
23:02:09  (0x000000000008D700)
23:02:09  (0x00000000FFED39E8)
23:02:09  ---------------------------------------
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly/33/
jdk_lang_1
java/lang/ProcessBuilder/Basic.java#id0


https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly/33/openjdk_test_output.tar.gz
```
00:05:22  >'standard errorUnhandled exception
00:05:22  Type=Segmentation error vmState=0x00040000
00:05:22  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFAC6AD437D ContextFlags=0010005f
00:05:22  Handler1=00007FFAADF0C240 Handler2=00007FFAADDEAA50 InaccessibleWriteAddress=0000000000000480
00:05:22  RDI=000001E2E4C075F0 RSI=0000000000000478 RAX=000000A1FE523000 RBX=0000000000000000
00:05:22  RCX=0000000000000478 RDX=0000000000000004 R8=000000A1801FF1F8 R9=00007FFAAE0AC9D0
00:05:22  R10=0000000000000000 R11=0000000000000246 R12=000000A1801FF4B0 R13=000000A1801FF530
00:05:22  R14=000000A1801FF488 R15=00007FFAAD1826F0
00:05:22  RIP=00007FFAC6AD437D RSP=000000A1801FF180 RBP=0000000000000004 EFLAGS=0000000000010202
00:05:22  FS=0053 ES=002B DS=002B
00:05:22  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:05:22  Module=C:\Windows\SYSTEM32\ntdll.dll
00:05:22  Module_base_address=00007FFAC6AC0000 Offset_in_DLL=000000000001437d
00:05:22  Target=2_90_20221020_114 (Windows Server 2019 10.0 build 17763)
00:05:22  CPU=amd64 (8 logical CPUs) (0x3ffb9c000 RAM)
00:05:22  ----------- Stack Backtrace -----------
00:05:22  RtlEnterCriticalSection+0xd (0x00007FFAC6AD437D [ntdll+0x1437d])
00:05:22  omrthread_get_category+0x47c6 (0x00007FFAB2327FB6 [j9thr29+0x7fb6])
00:05:22  omrthread_interrupt+0x5d (0x00007FFAB2321C9D [j9thr29+0x1c9d])
00:05:22  Java_java_lang_Thread_interruptImpl+0xa1 (0x00007FFAAD182791 [jclse29+0x42791])
00:05:22  ffi_call_go+0x3d1 (0x00007FFAADFDF031 [j9vm29+0x19f031])
00:05:22  ffi_call_go+0x20d (0x00007FFAADFDEE6D [j9vm29+0x19ee6d])
00:05:22  ffi_call_go+0x22 (0x00007FFAADFDEC82 [j9vm29+0x19ec82])
00:05:22  (0x00007FFAADE5A588 [j9vm29+0x1a588])
00:05:22  (0x000000A1801FF640)
00:05:22  (0x000000A1801FF660)
00:05:22  (0x000000A1801FF650)
00:05:22  (0x000001E2800BB599)
00:05:22  (0x000000A1801FF3F0)
00:05:22  ---------------------------------------
```

**Comment by tajila** [comment]
This has been resolved
