### ISSUE TITLE
JDK19 SecurityTests_0_FAILED : testDefaultTls failed - Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15502]
Failure link
------------

From an internal build `job/Test_openjdk19_j9_extended.functional_x86-64_linux_testList_1/6/`(`cent7x64-1-2`):
```
openjdk version "19-beta" 2022-09-20
IBM Semeru Runtime Open Edition 19+28-202207050538 (build 19-beta+28-202207050538)
Eclipse OpenJ9 VM 19+28-202207050538 (build master-0e480f25e, JRE 19 Linux amd64-64-Bit Compressed References 20220705_11 (JIT enabled, AOT enabled)
OpenJ9   - 0e480f25e
OMR      - d018241d7
JCL      - 28e60ccf5a based on jdk-19+28)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_extended.functional_x86-64_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-07-05-05-30.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=6&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-05T06:41:29.534Z] Running test SecurityTests_0 ...
[2022-07-05T06:41:29.534Z] ===============================================
[2022-07-05T06:41:29.534Z] SecurityTests_0 Start Time: Mon Jul  4 23:41:23 2022 Epoch Time (ms): 1657003283215
[2022-07-05T06:41:29.534Z] "/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_x86-64_linux_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk19_j9_extended.functional_x86-64_linux_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2022-07-05T06:41:29.534Z] JVMSHRC005I No shared class caches available
[2022-07-05T06:41:29.534Z] JVMSHRC005I No shared class caches available
[2022-07-05T06:41:29.534Z] cache cleanup done
[2022-07-05T06:41:29.534Z] variation: NoOptions
[2022-07-05T06:41:29.534Z] JVM_OPTIONS:  

[2022-07-05T06:41:29.536Z] FAILED: testDefaultTls
[2022-07-05T06:41:29.536Z] javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.CertificateStatus$CertificateStatusConsumer.consume(CertificateStatus.java:293)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:578)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
[2022-07-05T06:41:29.536Z] 	at net.adoptopenjdk.test.DefaultTlsFunctionalTest.testDefaultTls(DefaultTlsFunctionalTest.java:72)
[2022-07-05T06:41:29.536Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-05T06:41:29.536Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-07-05T06:41:29.536Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2022-07-05T06:41:29.536Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2022-07-05T06:41:29.536Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2022-07-05T06:41:29.536Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2022-07-05T06:41:29.536Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2022-07-05T06:41:29.536Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2022-07-05T06:41:29.536Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2022-07-05T06:41:29.536Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2022-07-05T06:41:29.536Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2022-07-05T06:41:29.536Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2022-07-05T06:41:29.536Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2022-07-05T06:41:29.536Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2022-07-05T06:41:29.536Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2022-07-05T06:41:29.536Z] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.validator.Validator.validate(Validator.java:256)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
[2022-07-05T06:41:29.536Z] 	... 36 more
[2022-07-05T06:41:29.536Z] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[2022-07-05T06:41:29.536Z] 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[2022-07-05T06:41:29.536Z] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
[2022-07-05T06:41:29.536Z] 	... 41 more
[2022-07-05T06:41:29.536Z] 
[2022-07-05T06:41:29.536Z] 
[2022-07-05T06:41:29.536Z] ===============================================
[2022-07-05T06:41:29.536Z]     SecurityTests
[2022-07-05T06:41:29.536Z]     Tests run: 2, Failures: 1, Skips: 0
[2022-07-05T06:41:29.536Z] ===============================================
[2022-07-05T06:41:29.536Z] 
[2022-07-05T06:41:29.536Z] 
[2022-07-05T06:41:29.536Z] ===============================================
[2022-07-05T06:41:29.536Z] Security Tests
[2022-07-05T06:41:29.536Z] Total tests run: 2, Failures: 1, Skips: 0
[2022-07-05T06:41:29.536Z] ===============================================
[2022-07-05T06:41:29.536Z] 
[2022-07-05T06:41:29.536Z] 
[2022-07-05T06:41:29.536Z] SecurityTests_0_FAILED
```
50x grinder - `job/Grinder/25565/`

**Comment by tajila** [comment]
@JasonFengJ9 does this still fail?

**Comment by JasonFengJ9** [comment]
Passed in [latest run](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.functional_x86-64_linux_testList_0/49/tapResults/), `extended.functional` has been green for a while.
Closing
