### ISSUE TITLE
JDK19 java/lang/Thread/virtual/ThreadAPI.java#id0 - Requires continuations support

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15503]
Failure link
------------

From an internal build `job/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_testList_1/6/`:
```
openjdk version "19-beta" 2022-09-20
IBM Semeru Runtime Open Edition 19+28-202207050535 (build 19-beta+28-202207050535)
Eclipse OpenJ9 VM 19+28-202207050535 (build master-0e480f25e, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220705_18 (JIT enabled, AOT enabled)
OpenJ9   - 0e480f25e
OMR      - d018241d7
JCL      - 28e60ccf5a based on jdk-19+28)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_sanity.openjdk_x86-64_mac&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F18%2Fibm-semeru-open-jdk_x64_mac_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F18%2Fibm-semeru-open-debugimage_x64_mac_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F18%2Fibm-semeru-open-jre_x64_mac_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F18%2Fibm-semeru-open-testimage_x64_mac_JDK19U_2022-07-05-05-30.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=%21sw.os.osx.10_11&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=6&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-05T07:13:12.171Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2022-07-05T07:13:12.171Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

[2022-07-05T07:21:41.817Z] TEST: java/lang/Thread/virtual/ThreadAPI.java#id0

[2022-07-05T07:21:41.818Z] test ThreadAPI.testGetAllStackTraces1(): failure
[2022-07-05T07:21:41.818Z] java.lang.NullPointerException
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.Thread.getAllThreads(Thread.java:2705)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.ThreadGroup.activeCount(ThreadGroup.java:377)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.Thread.getAllStackTraces(Thread.java:2626)
[2022-07-05T07:21:41.818Z] 	at ThreadAPI.lambda$testGetAllStackTraces1$131(ThreadAPI.java:2023)
[2022-07-05T07:21:41.818Z] 	at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:75)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.ThreadBuilders$BoundVirtualThread.run(ThreadBuilders.java:412)
[2022-07-05T07:21:41.818Z] test ThreadAPI.testGetAllStackTraces2(): skip
[2022-07-05T07:21:41.818Z] org.testng.SkipException: No support for custom schedulers
[2022-07-05T07:21:41.818Z] 	at ThreadAPI.testGetAllStackTraces2(ThreadAPI.java:2034)
[2022-07-05T07:21:41.818Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-07-05T07:21:41.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-07-05T07:21:41.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-07-05T07:21:41.818Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-07-05T07:21:41.818Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-07-05T07:21:41.818Z] test ThreadAPI.testGetStackTrace1(): success
[2022-07-05T07:21:41.818Z] test ThreadAPI.testGetStackTrace2(): skip
[2022-07-05T07:21:41.818Z] org.testng.SkipException: Requires continuations support
[2022-07-05T07:21:41.818Z] 	at ThreadAPI.testGetStackTrace2(ThreadAPI.java:1873)
[2022-07-05T07:21:41.818Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-07-05T07:21:41.818Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-07-05T07:21:41.818Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-07-05T07:21:41.818Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-07-05T07:21:41.818Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-07-05T07:21:41.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-07-05T07:21:41.818Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-07-05T07:21:41.818Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-07-05T07:21:41.818Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-07-05T07:21:41.818Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)

[2022-07-05T07:22:31.688Z] Test results: passed: 811; failed: 3
[2022-07-05T07:22:37.929Z] Report written to /Users/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_testList_1/jvmtest/openjdk/report/html/report.html
[2022-07-05T07:22:37.929Z] Results written to /Users/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_testList_1/aqa-tests/TKG/output_16570051913727/jdk_lang_1/work
[2022-07-05T07:22:37.929Z] Error: Some tests failed or other problems occurred.
[2022-07-05T07:22:37.929Z] 
[2022-07-05T07:22:37.929Z] jdk_lang_1_FAILED
```

The loom continuations support is being implemented, will exclude the test.

**Comment by thallium** [comment]
Only testGetAllStackTraces2 and testGetStackTrace4 are failing on the current master branch build.

**Comment by tajila** [comment]
@thallium are those tests still failing?

**Comment by thallium** [comment]
> @thallium are those tests still failing?

Passing now

**Comment by fengxue-IS** [comment]
This has been re-enabled as part of https://github.com/adoptium/aqa-tests/pull/4060, closing issue

**Comment by babsingh** [comment]
ThreadAPI#id0 is still disabled for JDK20: https://github.com/adoptium/aqa-tests/blob/a74405ca1262c4e50ea0a88e9cb27ade2dd60179/openjdk/excludes/ProblemList_openjdk20-openj9.txt#L157.

@fengxue-IS Can you please re-enable ThreadAPI#id0? Afterwards, the `test excluded` label should be re-enabled.

**Comment by fengxue-IS** [comment]
Moving this to JDK 20 target, will verify test passes on JDK 20 and create PR to re-enable test

**Comment by fengxue-IS** [comment]
Test re-enabled, closing issue.
