### ISSUE TITLE
JDK19 jdk/internal/misc/Unsafe/CopySwap.java - RuntimeException: testBufferPair

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15501]
Failure link
------------

From an internal build `job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_testList_1/6/`(`cent7x64-1-3`):
```
openjdk version "19-beta" 2022-09-20
IBM Semeru Runtime Open Edition 19+28-202207050538 (build 19-beta+28-202207050538)
Eclipse OpenJ9 VM 19+28-202207050538 (build master-0e480f25e, JRE 19 Linux amd64-64-Bit Compressed References 20220705_11 (JIT enabled, AOT enabled)
OpenJ9   - 0e480f25e
OMR      - d018241d7
JCL      - 28e60ccf5a based on jdk-19+28)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_sanity.openjdk_x86-64_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-07-05-05-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F11%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-07-05-05-30.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=6&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-05T06:28:32.844Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2022-07-05T06:28:32.844Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

[2022-07-05T06:40:14.080Z] TEST: jdk/internal/misc/Unsafe/CopySwap.java

[2022-07-05T06:40:14.081Z] STDERR:
[2022-07-05T06:40:14.081Z] java.lang.RuntimeException: testBufferPair: src=GenericPointer(o={null}, offset=0x7f02fc004d20) dst=GenericPointer(o={null}, offset=0x7f02fc003cb0) elemSize=0x2 copyBytes=0x2 srcOffset=0x2 dstOffset=0x10 swap=true
[2022-07-05T06:40:14.081Z] 	at CopyCommon.testBufferPair(CopyCommon.java:431)
[2022-07-05T06:40:14.081Z] 	at CopyCommon.testPermuteBuffers(CopyCommon.java:453)
[2022-07-05T06:40:14.081Z] 	at CopyCommon.testElemSize(CopyCommon.java:484)
[2022-07-05T06:40:14.081Z] 	at CopyCommon.testSmallCopy(CopyCommon.java:505)
[2022-07-05T06:40:14.081Z] 	at CopySwap.testPositive(CopySwap.java:41)
[2022-07-05T06:40:14.081Z] 	at CopySwap.test(CopySwap.java:141)
[2022-07-05T06:40:14.081Z] 	at CopySwap.main(CopySwap.java:147)
[2022-07-05T06:40:14.081Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-05T06:40:14.081Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-07-05T06:40:14.081Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-07-05T06:40:14.081Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-07-05T06:40:14.081Z] Caused by: java.lang.IllegalArgumentException
[2022-07-05T06:40:14.081Z] 	at java.base/jdk.internal.misc.Unsafe.invalidInput(Unsafe.java:5861)
[2022-07-05T06:40:14.081Z] 	at java.base/jdk.internal.misc.Unsafe.copySwapMemoryChecks(Unsafe.java:6184)
[2022-07-05T06:40:14.081Z] 	at java.base/jdk.internal.misc.Unsafe.copySwapMemory(Unsafe.java:1403)
[2022-07-05T06:40:14.081Z] 	at CopyCommon.testCopyGeneric(CopyCommon.java:357)
[2022-07-05T06:40:14.081Z] 	at CopyCommon.testBufferPair(CopyCommon.java:422)
[2022-07-05T06:40:14.081Z] 	... 10 more
[2022-07-05T06:40:14.081Z] 
[2022-07-05T06:40:14.081Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-07-05T06:40:14.081Z] JavaTest Message: shutting down test
[2022-07-05T06:40:14.081Z] 
[2022-07-05T06:40:14.081Z] STDOUT:
[2022-07-05T06:40:14.081Z] testPermuteBuffers(buffers, 32, 2, true)
[2022-07-05T06:40:14.081Z] 
[2022-07-05T06:40:14.081Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: testBufferPair: src=GenericPointer(o={null}, offset=0x7f02fc004d20) dst=GenericPointer(o={null}, offset=0x7f02fc003cb0) elemSize=0x2 copyBytes=0x2 srcOffset=0x2 dstOffset=0x10 swap=true
[2022-07-05T06:40:14.081Z] --------------------------------------------------
[2022-07-05T06:40:49.362Z] Test results: passed: 815; failed: 2
[2022-07-05T06:40:56.104Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_testList_1/jvmtest/openjdk/report/html/report.html
[2022-07-05T06:40:56.104Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_16570025117470/jdk_lang_0/work
[2022-07-05T06:40:56.104Z] Error: Some tests failed or other problems occurred.
[2022-07-05T06:40:56.104Z] 
[2022-07-05T06:40:56.104Z] jdk_lang_0_FAILED
```
50x grinder - job/Grinder/25564/ - passed

**Comment by tajila** [comment]
@mikezhang1234567890 Can you please take a look at this

**Comment by mikezhang1234567890** [comment]
Ran the test through grinder internally.

100x grinder passed on x86 Linux [here](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28403/).

200x grinder passed on x86 Linux [here](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28409/).

Could not reproduce the error, though our `Unsafe.java` hasn't changed since the OpenJ9 commit used in the failing build.

**Comment by JasonFengJ9** [comment]
Note the initial 50x grinder also passed.
I would close this unless it occurs again.
