### ISSUE TITLE
JDK19 Test complete - ClassCastException: incompatible with java.lang.Thread

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15519]
Failure link
------------

From an internal build `job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_1/8/`(`win16x64rt2-6`):
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+29 (build 19+29)
Eclipse OpenJ9 VM 19+29 (build master-6b4a2db09, JRE 19 Windows Server 2016 amd64-64-Bit Compressed References 20220920_13 (JIT enabled, AOT enabled)
OpenJ9   - 6b4a2db09
OMR      - ff6a49823
JCL      - 403c2088e2 based on jdk-19+29)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_sanity.openjdk_x86-64_windows&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F13%2Fibm-semeru-open-jdk_x64_windows_JDK19U_2022-07-09-16-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F13%2Fibm-semeru-open-jre_x64_windows_JDK19U_2022-07-09-16-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F13%2Fibm-semeru-open-debugimage_x64_windows_JDK19U_2022-07-09-16-00.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F13%2Fibm-semeru-open-testimage_x64_windows_JDK19U_2022-07-09-16-00.zip&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=8&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-09T20:32:41.755Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-07-09T20:32:42.159Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-07-09T20:38:15.788Z] TEST: java/util/concurrent/ConcurrentHashMap/ConcurrentContainsKeyTest.java

[2022-07-09T20:38:15.789Z] ===============================================
[2022-07-09T20:38:15.789Z] java/util/concurrent/ConcurrentHashMap/ConcurrentContainsKeyTest.java
[2022-07-09T20:38:15.789Z] Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
[2022-07-09T20:38:15.789Z] ===============================================
[2022-07-09T20:38:15.789Z] 
[2022-07-09T20:38:15.789Z] STDERR:
[2022-07-09T20:38:15.789Z] 
[2022-07-09T20:38:15.789Z] JavaTest Message: Test complete.
[2022-07-09T20:38:15.789Z] 
[2022-07-09T20:38:15.789Z] stderr:
[2022-07-09T20:38:15.789Z] java.lang.ClassCastException: [Ljava.lang.Package;@258d4acb incompatible with java.lang.Thread
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
[2022-07-09T20:38:15.789Z] 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[2022-07-09T20:38:15.789Z] 	at java.base/java.lang.Thread.getAllThreads(Thread.java:2705)
[2022-07-09T20:38:15.789Z] 	at java.base/java.lang.ThreadGroup.activeCount(ThreadGroup.java:377)
[2022-07-09T20:38:15.789Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.liveThreads(MainActionHelper.java:422)
[2022-07-09T20:38:15.789Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.cleanup(MainActionHelper.java:380)
[2022-07-09T20:38:15.789Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.access$000(MainActionHelper.java:345)
[2022-07-09T20:38:15.789Z] 	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:214)
[2022-07-09T20:38:15.789Z] 	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
[2022-07-09T20:38:15.789Z] 	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
[2022-07-09T20:38:15.789Z] 	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
[2022-07-09T20:38:15.789Z] 
[2022-07-09T20:38:15.789Z] TEST RESULT: Error. Agent communication error: java.net.SocketException: Connection reset; check console log for any additional details
[2022-07-09T20:38:15.789Z] --------------------------------------------------
[2022-07-09T21:06:40.518Z] Test results: passed: 910; error: 1
[2022-07-09T21:07:00.399Z] Report written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_1\jvmtest\openjdk\report\html\report.html
[2022-07-09T21:07:00.399Z] Results written to C:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_testList_1\aqa-tests\TKG\output_16573961738397\jdk_util_1\work
[2022-07-09T21:07:00.399Z] Error: Some tests failed or other problems occurred.
[2022-07-09T21:07:00.399Z] 
[2022-07-09T21:07:00.399Z] jdk_util_1_FAILED
```
50x grinder - `/job/Grinder/25612/`

**Comment by pshipton** [comment]
BTW it can happen in any?/many? of the tests, not sure the test itself is important.

**Comment by JasonFengJ9** [comment]
> BTW it can happen in any?/many? of the tests, not sure the test itself is important.

Yeah, it occurred after Test complete successfully.

`job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_testList_0/8/`
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+29 (build 19+29)
Eclipse OpenJ9 VM 19+29 (build master-6b4a2db09, JRE 19 Linux ppc64le-64-Bit Compressed References 20220919_13 (JIT enabled, AOT enabled)
OpenJ9   - 6b4a2db09
OMR      - ff6a49823
JCL      - 403c2088e2 based on jdk-19+29)
```

```
[2022-07-09T17:27:31.054Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2022-07-09T17:27:31.054Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2022-07-09T17:41:38.560Z] TEST: java/util/prefs/CheckUserPrefsStorage.java

[2022-07-09T17:41:38.562Z] JavaTest Message: Test complete.
[2022-07-09T17:41:38.562Z] 
[2022-07-09T17:41:38.562Z] stderr:
[2022-07-09T17:41:38.562Z] java.lang.ClassCastException: java.nio.channels.SelectableChannel incompatible with java.lang.Thread
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:588)
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
[2022-07-09T17:41:38.562Z] 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[2022-07-09T17:41:38.562Z] 	at java.base/java.lang.Thread.getAllThreads(Thread.java:2705)
[2022-07-09T17:41:38.562Z] 	at java.base/java.lang.ThreadGroup.activeCount(ThreadGroup.java:377)
[2022-07-09T17:41:38.562Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.liveThreads(MainActionHelper.java:422)
[2022-07-09T17:41:38.562Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.cleanup(MainActionHelper.java:380)
[2022-07-09T17:41:38.562Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMThreadGroup.access$000(MainActionHelper.java:345)
[2022-07-09T17:41:38.562Z] 	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:214)
[2022-07-09T17:41:38.562Z] 	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
[2022-07-09T17:41:38.562Z] 	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
[2022-07-09T17:41:38.562Z] 	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
[2022-07-09T17:41:38.562Z] 
[2022-07-09T17:41:38.562Z] TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details
[2022-07-09T17:41:38.562Z] --------------------------------------------------
[2022-07-09T18:03:06.140Z] Test results: passed: 906; error: 1
[2022-07-09T18:03:23.682Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_testList_0/jvmtest/openjdk/report/html/report.html
[2022-07-09T18:03:23.682Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_16573853091097/jdk_util_0/work
[2022-07-09T18:03:23.682Z] Error: Some tests failed or other problems occurred.
[2022-07-09T18:03:23.682Z] 
[2022-07-09T18:03:23.682Z] jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
Close this as a dup of https://github.com/eclipse-openj9/openj9/issues/15355
