### ISSUE TITLE
JDK17 aarch64_mac SC_Softmx_Increase_0_FAILED - net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15548]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.system_aarch64_mac_testList_0/3/)(`macaarch64rt3`):
```
openjdk version "17.0.4-ea" 2022-07-19
IBM Semeru Runtime Open Edition 17.0.4.0-m2 (build 17.0.4-ea+7)
Eclipse OpenJ9 VM 17.0.4.0-m2 (build openj9-0.33.0-m2, JRE 17 Mac OS X aarch64-64-Bit 20220718_88 (JIT enabled, AOT enabled)
OpenJ9   - e7fc0d2f1
OMR      - e25299388
JCL      - 05652b1ac23 based on jdk-17.0.4+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_extended.system_aarch64_mac&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9%2F88%2Fibm-semeru-open-testimage_aarch64_mac_17.0.4_7_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9%2F88%2Fibm-semeru-open-jre_aarch64_mac_17.0.4_7_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9%2F88%2Fibm-semeru-open-debugimage_aarch64_mac_17.0.4_7_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9%2F88%2Fibm-semeru-open-jdk_aarch64_mac_17.0.4_7_openj9-0.33.0-m2.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&RELEASE_TAG=v0.33.0-release&OPENJ9_BRANCH=v0.33.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.33.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=3&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
9.Jvm2.stdout

23:13:45.136 - Starting thread. Suite=0 thread=6
23:13:46.345 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
23:13:46.380 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/mix/sharedclasses-mix.xml
23:13:46.380 - suite.isCreateDump() : false
23:13:46.409 - Test failed
  Failure num.  = 1
  Test number   = 88
  Test details  = 'JUnit[net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest]'
  Suite number  = 0
  Thread number = 0
>>> Captured test output >>>
testStarted : testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testFailure: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
junit.framework.AssertionFailedError: Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:401)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testAllFileSystemsAreRegistered(FileSystemsTest.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:858)
testFinished: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testStarted : testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testFailure: testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to find intial provider 'memory0'
junit.framework.AssertionFailedError: Unable to find intial provider 'memory0'
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testFileSystemIsRegistered(FileSystemsTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:858)
testFinished: testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)

JUnit Test Results for: net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest
  Ran    : 2
  Passed : 0
  Failed : 2
  Ignored: 0
  Result : FAILED
<<<

23:13:46.667 - Test failed. Details recorded in execution log.
```

**Comment by knn-k** [comment]
We haven't seen this failure for a while.
I ran SC_Softmx_Increase_0 on macOS 30 times, and got no failures.  https://openj9-jenkins.osuosl.org/job/Grinder/1286/
