### ISSUE TITLE
Performance gap of 3-layer nested loops compared to Hotspot

### ISSUE THREAD

**Issue by YuanWangC** [eclipse-openj9/openj9#15544]
##### Description:

When I execute the following test case (Testcase1) containing 3 layers of nested for loops, OpenJ9 takes more than 15 seconds to execute it (using the Linux command `time` to time the program multiple times), which is almost 7 times longer than HotSpot's execution time and ends up with the same Exception as HotSpot. By the way，Executing the program with the option `-Xjit:count=0` for Openj9 did not improve its performance.
But if I comment out one layer of the loop (Testcase2), OpenJ9 takes almost the same execution time as HotSpot.
Could you please tell me if such a three-level nested loop is not optimized by JIT? Or is this issue caused by something else?

##### Environment：

```
Ubuntu 18.04 x86_64
```

###### jdk8:

```
openjdk version "1.8.0_332-internal"
OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_02_17_10_23-b00)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 301202f49f based on jdk8u332-b02)
```

###### jdk11:

```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 11 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 24e7209ed4 based on jdk-11.0.15+1)
```

##### Testcase1:

```java
public class MyJVMTest {
    void startCalculateSuccess() {
        double[] xx = {1.10,1.30,4.01,10.0,5.0,13.0,19.0,20.0,16.04,17.0,18.0,14.0};
        double[] zz = {82.0,22.01,25.0,27.10,26.0,24.0,2.60,52.0,2.0,72.0,82.0};
        double x_max = 1;
        int N = 357799514;
        for (int i = 1; i < N; i++) {
                for (int k = 1; k < N; k++) {
                    for (int n = 1; n < N; n++) {
                        zz[k] = 0.5 * (xx[k - 1] + xx[k + 1]);
                        x_max = Math.max(x_max, xx[i]);
                    }
            }
        }
    }

    public static void main(String[] args) throws Exception {
        new MyJVMTest().startCalculateSuccess();
    }
}
```

##### Testcase2:

```java
public class MyJVMTest {
    void startCalculateSuccess() {
        double[] xx = {1.10,1.30,4.01,10.0,5.0,13.0,19.0,20.0,16.04,17.0,18.0,14.0};
        double[] zz = {82.0,22.01,25.0,27.10,26.0,24.0,2.60,52.0,2.0,72.0,82.0};
        double x_max = 1;
        int N = 357799514;
        for (int i = 1; i < N; i++) {
                for (int k = 1; k < N; k++) {
                   // for (int n = 1; n < N; n++) {
                        zz[k] = 0.5 * (xx[k - 1] + xx[k + 1]);
                        x_max = Math.max(x_max, xx[i]);
                   // }
            }
        }
    }

    public static void main(String[] args) throws Exception {
        new MyJVMTest().startCalculateSuccess();
    }
}
```
##### output:

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at MyJVMTest.startCalculateSuccess(MyJVMTest.java:10)
	at MyJVMTest.main(MyJVMTest.java:18)
```

**Comment by gacholio** [comment]
FYI, `-Xjit:count=0` is strictly a debugging option - it will always produce worse code than the default options.

**Comment by vijaysun-omr** [comment]
@YuanWangC I will try this test case out and post my findings in the next few days. 

If you want, you could try `-Xtune:throoughput` to see if that command line option makes any difference. It may be preferable to try this option with a more recent OpenJ9 build (nightly or release) than what you showed since there were some changes made to it in the last couple of months that would be better to have in the build when you try that option.

**Comment by pshipton** [comment]
Links to the latest 0.33 pre-release builds.

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_x86-64_linux_Release/36/OpenJ9-JDK8-x86-64_linux-20220716-090456.tar.gz

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_linux_Release/43/OpenJ9-JDK11-x86-64_linux-20220716-090643.tar.gz

Or the little older (likely doesn't matter) Semeru 0.33 Milestone 1 builds.

https://github.com/ibmruntimes/semeru8-binaries/releases/download/jdk8u342-b03_openj9-0.33.0-m1/ibm-semeru-open-jdk_x64_linux_8u342b03_openj9-0.33.0-m1.tar.gz

https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.16%2B4_openj9-0.33.0-m1/ibm-semeru-open-jdk_x64_linux_11.0.16_4_openj9-0.33.0-m1.tar.gz

**Comment by YuanWangC** [comment]
And I also have installed the latest version of openj9 for jdk8, which did not help improve performance. OpenJ9 takes more than 18 seconds to execute it.
```
openjdk version "1.8.0_342-internal"
OpenJDK Runtime Environment (build 1.8.0_342-internal-root_2022_07_20_13_52-b00)
Eclipse OpenJ9 VM (build master-1a92d6852, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220720_000000 (JIT enabled, AOT enabled)
OpenJ9   - 1a92d6852
OMR      - edf2ae503
JCL      - 0516090d26 based on jdk8u342-b06)
```

**Comment by vijaysun-omr** [comment]
There appears to be a bug in the JIT where the `Math.max(DD)D` method is not getting inlined on some platforms (X86 being one of them). This seems to be due to some confusion around whether there is going to be special casing in order to generate better platform-specific code sequences for some of these kinds of `Math` methods in the back end code generators (e.g. on X86). While we may be able to generate a better sequence for `Math.max` in the X86 code generator, the fact that we do not do that presently, and nor do we inline the Java method leads to other issues such as being unable to hoist invariant computations out of the innermost loops (since there appears to be a call inside the loop that aliases the array accesses in there) causing in large part the performance issue that we see.

I hacked the supplied benchmark to essentially take the code/logic in `Math.max(DD)D` and add it to an alternate method in the `MyJVMTest` class and when I ran with this hack, it ran much faster (still about 2x slower than HotSpot but no longer 7x slower). The remaining 2x slowdown may well have at least in part to do with the fact that a better sequence can be generated for `Math.max(DD)D` on X86 and we may need to pursue doing the development work for that (though I cannot say the priority that this would take). 

I do think that fixing the bug with not inlining `Math.max(DD)D` is a high priority performance bug to fix; we feel this bug was an unintentional side-effect of some refactoring done over a year ago. We will likely deliver a fix for this in the coming days and post a comment here at that time. fyi @0xdaryl since I had mentioned this earlier today.

**Comment by 0dvictor** [comment]
Sorry to jump in. I cannot resist myself after reading this issue as I remember being involved in the same discussion years ago.

By inspecting the trees after inlining `Math.max(DD)D`, I feel that the way it handles negative zeros (`-0.0`) causes troubles. JCL's approach seems explicitly checking for negative zero (`-0.0`) by comparing a parameter against a constant stored as a field. This is unnecessary and inefficient.

So the most straightforward improvement is to rewrite the JCL code or translate the recognized call to the equivalent of:
```
static double max(double x, double y)
{
    if (x == 0.0 && y == 0.0)
        return Double.longBitsToDouble(Double.doubleToRawLongBits(x) & Double.doubleToRawLongBits(y));
    if (x != x)
        return x;
    return (x >= y) ? x : y;
}
```

To allow further optimization, we could also implement OMR's `TR::dmax`; however, its semantics are not very clear.

For OMR's `TR::dmax`, the behavior isn't quite clear. For the [Simplifier's code ](https://github.com/eclipse/omr/blob/212b496a195af0cd89e3cb132e72307ecec4f941/compiler/optimizer/OMRSimplifierHandlers.cpp#L17232): it looks equivalent to:
```
static double max(double x, double y)
{
    if (x != x)
        return x;
    return (x >= y) ? x : y;
}
```

Note that the behavior of comparing negative zero (`-0.0`) and positive zero (`+0.0`) are different from `Math.max(DD)D`: it always returns the second parameter. i.e. `TR::dmax(-0.0, +0.0)` is `+0.0` but `TR::dmax(+0.0, -0.0)` is `-0.0`.

Since there is little usage of `TR::dmax` or similar, can we (re-)define its semantics to match Java's?
The behavior is recommended in IEEE 754-2019 §9.6, and LLVM has an [intrinsic](https://llvm.org/docs/LangRef.html#llvm-maximum-intrinsic) matching this.
