### ISSUE TITLE
JDK11 MacOS aarch64 sun/security/ssl/SSLSocketImpl/SSLSocketLeak.java RuntimeException: Too many open file descriptors

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15558]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_mac/5/)(`macaarch64rt8`):
```
openjdk version "11.0.16-ea" 2022-07-19
IBM Semeru Runtime Open Edition 11.0.16.0-m2a (build 11.0.16-ea+7)
Eclipse OpenJ9 VM 11.0.16.0-m2a (build openj9-0.33.0-m2a, JRE 11 Mac OS X aarch64-64-Bit 20220717_97 (JIT enabled, AOT enabled)
OpenJ9   - 124430efb
OMR      - b58aa2708
JCL      - a30303e8b3 based on jdk-11.0.16+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-mac-aarch64-openj9%2F97%2Fibm-semeru-open-jdk_aarch64_mac_11.0.16_7_openj9-0.33.0-m2a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-mac-aarch64-openj9%2F97%2Fibm-semeru-open-jre_aarch64_mac_11.0.16_7_openj9-0.33.0-m2a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-mac-aarch64-openj9%2F97%2Fibm-semeru-open-debugimage_aarch64_mac_11.0.16_7_openj9-0.33.0-m2a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-mac-aarch64-openj9%2F97%2Fibm-semeru-open-testimage_aarch64_mac_11.0.16_7_openj9-0.33.0-m2a.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&RELEASE_TAG=v0.33.0-release&OPENJ9_BRANCH=v0.33.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.33.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-18T03:52:57.004Z] variation: Mode650
[2022-07-18T03:52:57.004Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-07-18T03:58:25.596Z] TEST: sun/security/ssl/SSLSocketImpl/SSLSocketLeak.java

[2022-07-18T03:58:25.597Z] STDERR:
[2022-07-18T03:58:25.597Z] java.lang.RuntimeException: Too many open file descriptors. Looks leaky.
[2022-07-18T03:58:25.597Z] 	at SSLSocketLeak.main(SSLSocketLeak.java:61)
[2022-07-18T03:58:25.597Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-07-18T03:58:25.597Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-07-18T03:58:25.597Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-07-18T03:58:25.597Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-07-18T03:58:25.597Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-07-18T03:58:25.597Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-07-18T03:58:25.597Z] 
[2022-07-18T03:58:25.597Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Too many open file descriptors. Looks leaky.

[2022-07-18T04:03:06.289Z] jdk_security3_1_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/25830/)

**Comment by JasonFengJ9** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_mac/13/)(`macaarch64rt6`)
```
openjdk version "11.0.17-ea" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0-m1 (build 11.0.17-ea+4)
Eclipse OpenJ9 VM 11.0.17.0-m1 (build openj9-0.35.0-m1, JRE 11 Mac OS X aarch64-64-Bit 20220901_129 (JIT enabled, AOT enabled)
OpenJ9   - f8c5cbdeb
OMR      - 938f0686f
JCL      - 4e2342f3c4 based on jdk-11.0.17+4)

[2022-09-01T07:29:38.469Z] STDERR:
[2022-09-01T07:29:38.469Z] java.lang.RuntimeException: Too many open file descriptors. Looks leaky.
[2022-09-01T07:29:38.469Z] 	at SSLSocketLeak.main(SSLSocketLeak.java:61)
[2022-09-01T07:29:38.469Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-09-01T07:29:38.469Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-09-01T07:29:38.469Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-09-01T07:29:38.469Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-09-01T07:29:38.469Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-01T07:29:38.469Z] 	at java.base/java.lang.Thread.run(Thread.java:839)

[2022-09-01T07:35:11.746Z] jdk_security3_1_FAILED
```

**Comment by pshipton** [comment]
Tentatively tagging as a blocker for amac being removed from EA.

**Comment by pshipton** [comment]
(20x x 10 grinder)(https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27803/)
There were only 4 distinct machines used.
There was 1 failure on macaarch64rt1.
```
FDs at the beginning: 4
FDs in the end: 63
```

Running the test manually, I often get results of
```
FDs at the beginning: 5
FDs in the end: 9

FDs at the beginning: 5
FDs in the end: 7
```
also these results
```
FDs at the beginning: 19
FDs in the end: 7

FDs at the beginning: 12
FDs in the end: 7

FDs at the beginning: 5
FDs in the end: 213

FDs at the beginning: 204
FDs in the end: 7

FDs at the beginning: 5
FDs in the end: 21
```

The results vary quite a bit. There doesn't seem to be a problem with SSLSockets. If anything, there may be a problem with UnixOperatingSystemMXBean.getOpenFileDescriptorCount().

Temurin seems to always return
```
FDs at the beginning: 4
FDs in the end: 8
```

Tagging as VM and setting to the next milestone to investigate getOpenFileDescriptorCount().

**Comment by knn-k** [comment]
I ran sun/security/ssl/SSLSocketImpl/SSLSocketLeak.java with JDK 11 manually 100 times in my local amac environment, and got no failures.

**Comment by JasonFengJ9** [comment]
[JDK17 m1 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/1966/consoleFull)
```
01:10:27  =JAVA VERSION OUTPUT BEGIN=
01:10:29  openjdk version "17.0.7" 2023-04-18
01:10:29  IBM Semeru Runtime Open Edition 17.0.7.0-m1 (build 17.0.7+2)
01:10:29  Eclipse OpenJ9 VM 17.0.7.0-m1 (build v0.38.0-release-25af2a240, JRE 17 Mac OS X aarch64-64-Bit 20230418_277 (JIT enabled, AOT enabled)
01:10:29  OpenJ9   - 25af2a240
01:10:29  OMR      - 008f97b5c
01:10:29  JCL      - 354bacdb9e2 based on jdk-17.0.7+2)

01:32:59  variation: Mode650
01:32:59  JVM_OPTIONS:  -XX:-UseCompressedOops 

02:01:31  TEST: sun/security/ssl/SSLSocketImpl/SSLSocketLeak.java

02:01:31  STDERR:
02:01:31  java.lang.RuntimeException: Too many open file descriptors. Looks leaky.
02:01:31  	at SSLSocketLeak.main(SSLSocketLeak.java:61)
02:01:31  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:01:31  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
02:01:31  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:01:31  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
02:01:31  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
02:01:31  	at java.base/java.lang.Thread.run(Thread.java:857)
02:01:31  
02:01:31  JavaTest Message: Test threw exception: java.lang.RuntimeException: Too many open file descriptors. Looks leaky.
```

**Comment by JasonFengJ9** [comment]
[JDK11 aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_mac_testList_0/16/)(`macaarch64rt1`)
```
[2024-03-26T16:59:34.773Z] variation: Mode650
[2024-03-26T16:59:34.773Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-26T17:04:49.591Z] TEST: sun/security/ssl/SSLSocketImpl/SSLSocketLeak.java

[2024-03-26T17:04:49.591Z] STDERR:
[2024-03-26T17:04:49.591Z] java.lang.RuntimeException: Too many open file descriptors. Looks leaky.
[2024-03-26T17:04:49.591Z] 	at SSLSocketLeak.main(SSLSocketLeak.java:61)

[2024-03-26T17:09:15.698Z] jdk_security3_1_FAILED
```
