### ISSUE TITLE
MathLoadTest_bigdecimal_special_5m test.bigdecimal IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15553]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_special.system_aarch64_linux_Release_testList_4/14
MathLoadTest_bigdecimal_special_5m_4 `-Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs`

```
MLT testFailure: testItem_0512(net.adoptopenjdk.test.bigdecimal.TestSuite004): argument type mismatch
MLT java.lang.IllegalArgumentException: argument type mismatch
MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
MLT 	at junit.framework.TestResult.run(TestResult.java:125)
MLT 	at junit.framework.TestCase.run(TestCase.java:129)
MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
...
MLT testFailure: testItem_0514(net.adoptopenjdk.test.bigdecimal.TestSuite004): argument type mismatch
MLT java.lang.IllegalArgumentException: argument type mismatch
MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
MLT 	at junit.framework.TestResult.run(TestResult.java:125)
MLT 	at junit.framework.TestCase.run(TestCase.java:129)
MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
...
many more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_special.system_aarch64_linux_Personal_testList_1/31
MathLoadTest_bigdecimal_special_5m_1 `-Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedref`
```
11:19:34  MLT testFailure: testItem_0377(net.adoptopenjdk.test.bigdecimal.TestSuite056): argument type mismatch
11:19:34  MLT java.lang.IllegalArgumentException: argument type mismatch
11:19:34  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
11:19:34  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
11:19:34  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_special.system_aarch64_linux_Release_testList_3/3
MathLoadTest_bigdecimal_special_5m_6 `-Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs`
```
10:30:28  MLT testFailure: testItem_0516(net.adoptopenjdk.test.bigdecimal.TestSuite053): argument type mismatch
10:30:28  MLT java.lang.IllegalArgumentException: argument type mismatch
10:30:28  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
10:30:28  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
10:30:28  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
10:30:28  MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
```

**Comment by pshipton** [comment]
@hzongaro fyi

**Comment by pshipton** [comment]
@knn-k fyi

**Comment by knn-k** [comment]
Issue #16989 looks similar.

**Comment by knn-k** [comment]
The `IllegalArgumentException` is thrown here:
https://github.com/ibmruntimes/openj9-openjdk-jdk22/blob/7b1ea2cb934f79f8546b450e3da7ff8b443a3418/src/java.base/share/classes/jdk/internal/reflect/DirectMethodHandleAccessor.java#L107

30x Grinder job for MathLoadTest_all_special_5m_4 did not fail.
https://openj9-jenkins.osuosl.org/job/Grinder/3566

**Comment by knn-k** [comment]
I ran two more 30x Grinder jobs (40329, 40379) on internal servers, and they finished successfully.

**Comment by knn-k** [comment]
I ran two more 30x Grinder jobs (40383, 40384) on internal servers.  No failures.

**Comment by knn-k** [comment]
Yet another Grinder job (40550, 50x) did not fail, either.  200 runs in total.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_special.system_aarch64_linux_Release_testList_1/13
MathLoadTest_all_special_5m_6 `-Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs`

**Comment by knn-k** [comment]
There are 582 failures in a single test.
```
[2024-06-02T13:49:36.593Z] MLT JUnit Test Results for: net.adoptopenjdk.test.bigdecimal.TestSuite058
[2024-06-02T13:49:36.593Z] MLT   Ran    : 934
[2024-06-02T13:49:36.593Z] MLT   Passed : 352
[2024-06-02T13:49:36.593Z] MLT   Failed : 582
[2024-06-02T13:49:36.593Z] MLT   Ignored: 0
[2024-06-02T13:49:36.593Z] MLT   Result : FAILED
```

testItem_0000 to testItem_0239 are all successful.  testItem_0240 is the first failure, but some testitems after that, such as testItem_0242, passed.

```
[2024-06-02T13:49:36.055Z] MLT testStarted : testItem_0239(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testFinished: testItem_0239(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testStarted : testItem_0240(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testFailure: testItem_0240(net.adoptopenjdk.test.bigdecimal.TestSuite058): argument type mismatch
[2024-06-02T13:49:36.055Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2024-06-02T13:49:36.055Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
(... snip ...)
[2024-06-02T13:49:36.055Z] MLT testFinished: testItem_0240(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testStarted : testItem_0241(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testFailure: testItem_0241(net.adoptopenjdk.test.bigdecimal.TestSuite058): argument type mismatch
[2024-06-02T13:49:36.055Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2024-06-02T13:49:36.055Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
(... snip ...)
[2024-06-02T13:49:36.055Z] MLT testFinished: testItem_0241(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testStarted : testItem_0242(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testFinished: testItem_0242(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testStarted : testItem_0243(net.adoptopenjdk.test.bigdecimal.TestSuite058)
[2024-06-02T13:49:36.055Z] MLT testFailure: testItem_0243(net.adoptopenjdk.test.bigdecimal.TestSuite058): argument type mismatch
[2024-06-02T13:49:36.055Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2024-06-02T13:49:36.055Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
(... snip ...)
[2024-06-02T13:49:36.055Z] MLT testFinished: testItem_0243(net.adoptopenjdk.test.bigdecimal.TestSuite058)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_special.system_aarch64_mac_Personal_testList_2/13/
MathLoadTest_bigdecimal_special_5m_1 `-Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs`
```
23:52:22  MLT testFailure: testItem_0000(net.adoptopenjdk.test.bigdecimal.TestSuite054): argument type mismatch
23:52:22  MLT java.lang.IllegalArgumentException: argument type mismatch
23:52:22  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
23:52:22  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
23:52:22  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_special.system_aarch64_mac_Release_testList_4/1
MathLoadTest_all_special_5m_4 `-Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs`
```
21:57:07  MLT testFailure: testIEEEremainder(net.adoptopenjdk.test.math.MathAPITest): argument type mismatch
21:57:07  MLT java.lang.IllegalArgumentException: argument type mismatch
21:57:07  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
21:57:07  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
21:57:07  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
21:57:07  MLT testFailure: testAbs_float(net.adoptopenjdk.test.math.MathAPITest): argument type mismatch
21:57:07  MLT java.lang.IllegalArgumentException: argument type mismatch
21:57:07  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
21:57:07  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
21:57:07  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
21:57:07  MLT testFailure: testUlp_float(net.adoptopenjdk.test.math.MathAPITest): argument type mismatch
21:57:07  MLT java.lang.IllegalArgumentException: argument type mismatch
21:57:07  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
21:57:07  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
21:57:07  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
... many more
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_special.system_aarch64_mac_testList_1/7/)
```
[2025-08-25T21:34:48.750Z] Running test MathLoadTest_all_special_5m_6 ...
[2025-08-25T21:34:48.750Z] ===============================================
[2025-08-25T21:34:48.750Z] MathLoadTest_all_special_5m_6 Start Time: Mon Aug 25 14:34:48 2025 Epoch Time (ms): 1756157688078
[2025-08-25T21:34:48.750Z] variation: Mode121
[2025-08-25T21:34:48.750Z] JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs 

[2025-08-25T21:37:14.555Z] MLT testFailure: testItem_0472(net.adoptopenjdk.test.bigdecimal.TestSuite032): argument type mismatch
[2025-08-25T21:37:14.555Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2025-08-25T21:37:14.555Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
[2025-08-25T21:37:14.555Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestResult.run(TestResult.java:125)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestCase.run(TestCase.java:129)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2025-08-25T21:37:14.555Z] MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
[2025-08-25T21:37:14.555Z] MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2025-08-25T21:37:14.555Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2025-08-25T21:37:14.556Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2025-08-25T21:37:14.556Z] MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2025-08-25T21:37:14.556Z] MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2025-08-25T21:37:14.556Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[2025-08-25T21:37:14.556Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[2025-08-25T21:37:14.556Z] MLT 	at java.base/java.lang.Thread.run(Thread.java:1485)
```

**Comment by knn-k** [comment]
I assume Issue #16989 is a dup of this one.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_special.system_aarch64_mac_Personal_testList_2/69 - [mac15-aarch64-4](https://openj9-jenkins.osuosl.org/computer/mac15-aarch64-4)
MathLoadTest_all_special_5m_4 `-Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs`
```
13:41:52  MLT testFailure: testItem_0493(net.adoptopenjdk.test.bigdecimal.TestSuite018): argument type mismatch
13:41:52  MLT java.lang.IllegalArgumentException: argument type mismatch
13:41:52  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_special.system_aarch64_mac_testList_9/137/)
```
[2026-05-03T22:26:56.941Z] Running test MathLoadTest_bigdecimal_special_5m_1 ...
[2026-05-03T22:26:56.941Z] ===============================================
[2026-05-03T22:26:56.941Z] MathLoadTest_bigdecimal_special_5m_1 Start Time: Sun May  3 15:26:56 2026 Epoch Time (ms): 1777847216792
[2026-05-03T22:26:56.941Z] variation: Mode103
[2026-05-03T22:26:56.941Z] JVM_OPTIONS:  -Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs 

[2026-05-03T22:29:32.154Z] MLT testStarted : testItem_0041(net.adoptopenjdk.test.bigdecimal.TestSuite015)
[2026-05-03T22:29:32.154Z] MLT testFailure: testItem_0041(net.adoptopenjdk.test.bigdecimal.TestSuite015): argument type mismatch
[2026-05-03T22:29:32.154Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2026-05-03T22:29:32.154Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
[2026-05-03T22:29:32.154Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2026-05-03T22:29:32.154Z] MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
```

**Comment by JasonFengJ9** [comment]
[openjdk27_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk27_j9_special.system_aarch64_mac_testList_2/10/)
```
[2026-08-09T20:45:17.562Z] Running test MathLoadTest_all_special_5m_6 ...
[2026-08-09T20:45:17.562Z] ===============================================
[2026-08-09T20:45:17.562Z] MathLoadTest_all_special_5m_6 Start Time: Sun Aug  9 13:45:13 2026 Epoch Time (ms): 1786308313347
[2026-08-09T20:45:17.562Z] variation: Mode121
[2026-08-09T20:45:17.562Z] JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs 

[2026-08-09T20:47:51.840Z] MLT 13:47:46.427 - Test failed
[2026-08-09T20:47:51.840Z] MLT   Failure num.  = 1
[2026-08-09T20:47:51.840Z] MLT   Test number   = 31
[2026-08-09T20:47:51.840Z] MLT   Test details  = 'JUnit[net.adoptopenjdk.test.bigdecimal.TestSuite031]'
[2026-08-09T20:47:51.840Z] MLT   Suite number  = 0
[2026-08-09T20:47:51.840Z] MLT   Thread number = 4
[2026-08-09T20:47:51.840Z] MLT >>> Captured test output >>>
[2026-08-09T20:47:51.840Z] MLT testStarted : testItem_0000(net.adoptopenjdk.test.bigdecimal.TestSuite031)
[2026-08-09T20:47:51.840Z] MLT testFailure: testItem_0000(net.adoptopenjdk.test.bigdecimal.TestSuite031): argument type mismatch
[2026-08-09T20:47:51.840Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2026-08-09T20:47:51.840Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
[2026-08-09T20:47:51.840Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:589)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestResult.run(TestResult.java:125)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestCase.run(TestCase.java:129)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2026-08-09T20:47:51.840Z] MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2026-08-09T20:47:51.840Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2026-08-09T20:47:51.840Z] MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2026-08-09T20:47:51.840Z] MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2026-08-09T20:47:51.840Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[2026-08-09T20:47:51.840Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[2026-08-09T20:47:51.840Z] MLT 	at java.base/java.lang.Thread.run(Thread.java:1538)
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/61927/) - 1/50 failed

**Comment by hzongaro** [comment]
@nbhuiyan, may I ask you to take a look at this?  It's been occurring sporadically for quite a while.  I assume it's related to method handles support.  As @knn-k [mentioned](issuecomment-3231655459), #16989 might be a duplicate.

**Comment by hzongaro** [comment]
As this is a long-standing issue, we'll move it out to the 0.64.
