### ISSUE TITLE
JDK17 AIX cmdLineTester_jvmtitests_2_FAILED (cma001) - NPE Cannot invoke "java.lang.Class.newInstance()" because "originalClass" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15560]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_1/200/)(`p10aix009`):
```
openjdk version "17.0.4" 2022-07-19
IBM Semeru Runtime Open Edition 17.0.4.0-m2 (build 17.0.4+7)
Eclipse OpenJ9 VM 17.0.4.0-m2 (build openj9-0.33.0-m2a, JRE 17 AIX ppc64-64-Bit Compressed References 20220718_212 (JIT enabled, AOT enabled)
OpenJ9   - 124430efb
OMR      - b58aa2708
JCL      - c9b767d97c2 based on jdk-17.0.4+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.functional_ppc64_aix&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9%2F212%2Fibm-semeru-open-jdk_ppc64_aix_17.0.4_7_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9%2F212%2Fibm-semeru-open-jre_ppc64_aix_17.0.4_7_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9%2F212%2Fibm-semeru-open-debugimage_ppc64_aix_17.0.4_7_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9%2F212%2Fibm-semeru-open-testimage_ppc64_aix_17.0.4_7_openj9-0.33.0-m2.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&RELEASE_TAG=v0.33.0-release&OPENJ9_BRANCH=v0.33.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.33.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=226&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-14T16:26:44.496Z] variation: Mode149
[2022-07-14T16:26:44.496Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xshareclasses:cacheRetransformed,name=retransformenabled -Xnocompressedrefs 

[2022-07-14T16:27:42.029Z] Testing: cma001
[2022-07-14T16:27:42.029Z] Test start time: 2022/07/14 12:27:41 Eastern Standard Time
[2022-07-14T16:27:42.029Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xshareclasses:cacheRetransformed,name=retransformenabled -Xnocompressedrefs  -Xdump    -XX:ForceClassfileAsIntermediateData -agentlib:jvmtitest=test:ria001,args:V3 -agentlib:jvmtitest=test:rca001,args:V4 -agentlib:jvmtitest=test:cma001 -cp "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
[2022-07-14T16:27:42.029Z] Time spent starting: 12 milliseconds
[2022-07-14T16:27:42.371Z] Time spent executing: 448 milliseconds
[2022-07-14T16:27:42.371Z] Test result: FAILED
[2022-07-14T16:27:42.371Z] Output from test:
[2022-07-14T16:27:42.371Z]  [OUT] *** Testing [1/1]:	testClassModification
[2022-07-14T16:27:42.371Z]  [OUT] *** Test took 18 milliseconds
[2022-07-14T16:27:42.371Z]  [OUT] FAILED
[2022-07-14T16:27:42.371Z]  [OUT] 
[2022-07-14T16:27:42.371Z]  [ERR] java.io.EOFException: Unexpected end of ZLIB input stream
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:446)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.CustomClassLoader.findClass(CustomClassLoader.java:100)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1196)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1111)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.classModificationAgent.cma001.testClassModification(cma001.java:152)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestCase.run(TestCase.java:215)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:68)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:79)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
[2022-07-14T16:27:42.371Z]  [ERR] java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because "originalClass" is null
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.classModificationAgent.cma001.testClassModification(cma001.java:153)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-07-14T16:27:42.371Z]  [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestCase.run(TestCase.java:215)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:68)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:79)
[2022-07-14T16:27:42.371Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
[2022-07-14T16:27:42.371Z] >> Success condition was not found: [Return code: 0]

[2022-07-14T16:27:43.787Z] ---TEST RESULTS---
[2022-07-14T16:27:43.787Z] Number of PASSED tests: 59 out of 60
[2022-07-14T16:27:43.787Z] Number of FAILED tests: 1 out of 60
[2022-07-14T16:27:43.787Z] 
[2022-07-14T16:27:43.787Z] ---SUMMARY OF FAILED TESTS---
[2022-07-14T16:27:43.787Z] cma001
[2022-07-14T16:27:43.787Z] -----------------------------
[2022-07-14T16:27:43.787Z] 
[2022-07-14T16:27:43.787Z] 
[2022-07-14T16:27:43.787Z] cmdLineTester_jvmtitests_2_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/25831/)

**Comment by JasonFengJ9** [comment]
```
[2022-07-14T16:27:44.150Z] variation: Mode351
[2022-07-14T16:27:44.150Z] JVM_OPTIONS:  -Xgcpolicy:metronome -Xcompressedrefs 

[2022-07-14T16:29:42.110Z] Testing: cma001
[2022-07-14T16:29:42.110Z] Test start time: 2022/07/14 12:29:42 Eastern Standard Time
[2022-07-14T16:29:42.110Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/bin/java"  -Xgcpolicy:metronome -Xcompressedrefs  -Xdump    -XX:ForceClassfileAsIntermediateData -agentlib:jvmtitest=test:ria001,args:V3 -agentlib:jvmtitest=test:rca001,args:V4 -agentlib:jvmtitest=test:cma001 -cp "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
[2022-07-14T16:29:42.447Z] Time spent starting: 38 milliseconds
[2022-07-14T16:29:43.175Z] Time spent executing: 902 milliseconds
[2022-07-14T16:29:43.175Z] Test result: FAILED
[2022-07-14T16:29:43.175Z] Output from test:
[2022-07-14T16:29:43.175Z]  [OUT] *** Testing [1/1]:	testClassModification
[2022-07-14T16:29:43.175Z]  [OUT] *** Test took 24 milliseconds
[2022-07-14T16:29:43.175Z]  [OUT] FAILED
[2022-07-14T16:29:43.175Z]  [OUT] 
[2022-07-14T16:29:43.175Z]  [ERR] java.io.EOFException: Unexpected end of ZLIB input stream
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:446)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.util.Util.getClassBytes(Util.java:149)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.classModificationAgent.cma001.getClassBytes(cma001.java:68)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.classModificationAgent.cma001.getClassBytesForVersion(cma001.java:75)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:471)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:432)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:384)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.util.CustomClassLoader.findClass(CustomClassLoader.java:115)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1196)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1111)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.classModificationAgent.cma001.testClassModification(cma001.java:152)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-07-14T16:29:43.175Z]  [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestCase.run(TestCase.java:215)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:68)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:79)
[2022-07-14T16:29:43.175Z]  [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
[2022-07-14T16:29:43.175Z]  [ERR] ria001: Failed to get class bytes for expected class version 1
[2022-07-14T16:29:43.175Z]  [ERR] rca001: Class byte do not match
[2022-07-14T16:29:43.175Z]  [ERR] classFileLoadHookCallback failed
[2022-07-14T16:29:43.175Z] >> Success condition was not found: [Return code: 0]

[2022-07-14T16:29:46.665Z] ---TEST RESULTS---
[2022-07-14T16:29:46.665Z] Number of PASSED tests: 59 out of 60
[2022-07-14T16:29:46.665Z] Number of FAILED tests: 1 out of 60
[2022-07-14T16:29:46.665Z] 
[2022-07-14T16:29:46.665Z] ---SUMMARY OF FAILED TESTS---
[2022-07-14T16:29:46.665Z] cma001
[2022-07-14T16:29:46.665Z] -----------------------------
[2022-07-14T16:29:46.665Z] 
[2022-07-14T16:29:46.665Z] 
[2022-07-14T16:29:46.665Z] cmdLineTester_jvmtitests_5_FAILED
```
