### ISSUE TITLE
CRIU: JDK17 criu support

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15568]
https://openj9-jenkins.osuosl.org/view/Test_Functional_Personal/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal/6/tapResults/

Address failures on JDK17

```
Testing: Create and Restore Criu Checkpoint Image once - TestSingleThreadModeRestoreException
Test start time: 2022/07/13 16:04:02 Atlantic Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xint -XX:+CRIURestoreNonPortableMode " org.openj9.criu.TestSingleThreadModeRestoreException SingleCheckpoint
Time spent starting: 5 milliseconds
Time spent executing: 2591 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] Pre-checkpoint
 [OUT] PreSnapshotHook() before synchronized on java.lang.Object@929d0180: org.openj9.criu.TestSingleThreadModeRestoreException@455eb37 name: main
 [OUT] PreSnapshotHook() within synchronized on java.lang.Object@929d0180: org.openj9.criu.TestSingleThreadModeRestoreException@455eb37 name: main
 [OUT] PreSnapshotHook() after synchronized on java.lang.Object@929d0180: org.openj9.criu.TestSingleThreadModeRestoreException@455eb37 name: main
 [OUT] newThreadOwnMonitor() before synchronized on java.lang.Object@929d0180: org.openj9.criu.TestSingleThreadModeRestoreException@455eb37 name: Thread-3
 [OUT] newThreadOwnMonitor() before Thread.sleep(): org.openj9.criu.TestSingleThreadModeRestoreException@455eb37 name: Thread-3
 [OUT] newThreadOwnMonitor() interrupted: org.openj9.criu.TestSingleThreadModeRestoreException@455eb37 name: Thread-3
 [OUT] newThreadOwnMonitor() after synchronized on java.lang.Object@929d0180: org.openj9.criu.TestSingleThreadModeRestoreException@455eb37 name: Thread-3
 [OUT] finished script
 [ERR] /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 26: 15965 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 > testOutput 2>&1
>> Success condition was not found: [Output match: org.eclipse.openj9.criu.RestoreException: Exception thrown when running user post-restore]
>> Required condition was found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Failure condition was not found: [Output match: ERR]
```

```
Testing: Create and Restore Criu Checkpoint Image once - TestSingleThreadModeRestoreException
Test start time: 2022/07/13 16:13:13 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 -XX:+CRIURestoreNonPortableMode " org.openj9.criu.TestSingleThreadModeRestoreException SingleCheckpoint
Time spent starting: 3 milliseconds
Time spent executing: 5384 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] Pre-checkpoint
 [OUT] PreSnapshotHook() before synchronized on java.lang.Object@f5557207: org.openj9.criu.TestSingleThreadModeRestoreException@7784e57e name: main
 [OUT] PreSnapshotHook() within synchronized on java.lang.Object@f5557207: org.openj9.criu.TestSingleThreadModeRestoreException@7784e57e name: main
 [OUT] PreSnapshotHook() after synchronized on java.lang.Object@f5557207: org.openj9.criu.TestSingleThreadModeRestoreException@7784e57e name: main
 [OUT] newThreadOwnMonitor() before synchronized on java.lang.Object@f5557207: org.openj9.criu.TestSingleThreadModeRestoreException@7784e57e name: Thread-3
 [OUT] newThreadOwnMonitor() before Thread.sleep(): org.openj9.criu.TestSingleThreadModeRestoreException@7784e57e name: Thread-3
 [OUT] newThreadOwnMonitor() interrupted: org.openj9.criu.TestSingleThreadModeRestoreException@7784e57e name: Thread-3
 [OUT] newThreadOwnMonitor() after synchronized on java.lang.Object@f5557207: org.openj9.criu.TestSingleThreadModeRestoreException@7784e57e name: Thread-3
 [OUT] finished script
 [ERR] /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 26: 20948 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 > testOutput 2>&1
>> Success condition was not found: [Output match: org.eclipse.openj9.criu.RestoreException: Exception thrown when running user post-restore]
>> Required condition was found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Failure condition was not found: [Output match: ERR]
```

```
Testing: Create Criu Checkpoint Image once and no restore - TestSingleThreadModeCheckpointException
Test start time: 2022/07/13 16:13:10 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 -XX:+CRIURestoreNonPortableMode " org.openj9.criu.TestSingleThreadModeCheckpointException OnlyCheckpoint
Time spent starting: 4 milliseconds
Time spent executing: 3183 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] Pre-checkpoint
 [OUT] PreSnapshotHook() before synchronized on java.lang.Object@efb14920: org.openj9.criu.TestSingleThreadModeCheckpointException@3a618ad8 name: main
 [OUT] PreSnapshotHook() within synchronized on java.lang.Object@efb14920: org.openj9.criu.TestSingleThreadModeCheckpointException@3a618ad8 name: main
 [OUT] PreSnapshotHook() after synchronized on java.lang.Object@efb14920: org.openj9.criu.TestSingleThreadModeCheckpointException@3a618ad8 name: main
 [OUT] finished script
 [ERR] /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 26: 20911 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 > testOutput 2>&1
>> Success condition was not found: [Output match: TestSingleThreadModeCheckpointException: PASSED]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Failure condition was not found: [Output match: TestSingleThreadModeCheckpointException: FAILED]
>> Failure condition was found: [Output match: Killed]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Failure condition was not found: [Output match: ERR]
```

**Comment by tajila** [comment]
Okay, there might be a way to fix this with the https://github.com/eclipse-openj9/openj9/pull/15540 PR

**Comment by JasonFengJ9** [comment]
> Do you know which thread is holding on to the lock in ClassSpecializer.findSpecies

It is another test thread doing similar string concatenation.
```
3XMTHREADINFO      "Thread-3" J9VMThread:0x0000000000140700, omrthread_t:0x00007F7B142131E0, java/lang/Thread:0x00000007FFE090E0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0xE, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x00000007FFE00E90)
3XMTHREADINFO1            (native thread ID:0x8F498, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00200081)
3XMTHREADINFO2            (native stack address range from:0x00007F7B19237000, to:0x00007F7B192B7000, size:0x80000)
3XMCPUTIME               CPU usage total: 0.153352016 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=289944 (0x46C98)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/util/Arrays.copyOfRange(Arrays.java:3853)
4XESTACKTRACE                at java/lang/StringUTF16.newString(StringUTF16.java:1179)
4XESTACKTRACE                at java/lang/StringBuilder.toString(StringBuilder.java:454)
4XESTACKTRACE                at java/lang/invoke/ClassSpecializer.classSig(ClassSpecializer.java:1032)
4XESTACKTRACE                at java/lang/invoke/ClassSpecializer.classSig(ClassSpecializer.java:1026)
4XESTACKTRACE                at java/lang/invoke/ClassSpecializer$Factory$1Var.<init>(ClassSpecializer.java:655)
4XESTACKTRACE                at java/lang/invoke/ClassSpecializer$Factory.generateConcreteSpeciesCodeFile(ClassSpecializer.java:764)
4XESTACKTRACE                at java/lang/invoke/ClassSpecializer$Factory.generateConcreteSpeciesCode(ClassSpecializer.java:571)
4XESTACKTRACE                at java/lang/invoke/ClassSpecializer$Factory.loadSpecies(ClassSpecializer.java:491)
4XESTACKTRACE                at java/lang/invoke/ClassSpecializer.findSpecies(ClassSpecializer.java:195)  <-- this holds the lock in question
5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000007FFEE7D28, entry count: 1)
4XESTACKTRACE                at java/lang/invoke/BoundMethodHandle$SpeciesData.extendWith(BoundMethodHandle.java:370)
4XESTACKTRACE                at java/lang/invoke/LambdaFormEditor.newSpeciesData(LambdaFormEditor.java:466)
4XESTACKTRACE                at java/lang/invoke/LambdaFormEditor.makeArgumentCombinationForm(LambdaFormEditor.java:838)
4XESTACKTRACE                at java/lang/invoke/LambdaFormEditor.filterArgumentsForm(LambdaFormEditor.java:1023)
4XESTACKTRACE                at java/lang/invoke/MethodHandles.argumentsWithCombiner(MethodHandles.java:6149)
4XESTACKTRACE                at java/lang/invoke/MethodHandles.filterArgumentsWithCombiner(MethodHandles.java:6114)
4XESTACKTRACE                at java/lang/invoke/StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:541)
4XESTACKTRACE                at java/lang/invoke/StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:358)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$DMH/0x00000000c8018cb0.invokeStatic(LambdaForm$DMH)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x00000000c801b800.delegate(LambdaForm$MH)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x00000000c801bd60.invokeExact_MT(LambdaForm$MH)
4XESTACKTRACE                at java/lang/invoke/BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
4XESTACKTRACE                at java/lang/invoke/CallSite.makeSite(CallSite.java:315)
4XESTACKTRACE                at java/lang/invoke/MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
4XESTACKTRACE                at java/lang/invoke/MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
4XESTACKTRACE                at java/lang/invoke/MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:197)
4XESTACKTRACE                at org/openj9/criu/TestSingleThreadModeCheckpointException.log(TestSingleThreadModeCheckpointException.java:41)
4XESTACKTRACE                at org/openj9/criu/TestSingleThreadModeCheckpointException$1.run(TestSingleThreadModeCheckpointException.java:47)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:857)
```

**Comment by JasonFengJ9** [comment]
>  I think adding the @NotCheckpointSafe annotation to ClassSpecializer.findSpecies might be the solution

It reduces dramatically the occurrences of `org.eclipse.openj9.criu.JVMCheckpointException: Blocking operation is not allowed in CRIU single thread mode`, from ~50% to 5%.
Increasing `checkpointState.maxRetryForNotCheckpointSafe` to `1000` seems no impact.

**Comment by tajila** [comment]
What are the other cases of ` Blocking operation is not allowed in CRIU single thread mode`? there might be other places where we need to add the annotation

> Increasing checkpointState.maxRetryForNotCheckpointSafe to 1000 seems no impact.

maxRetryForNotCheckpointSafe isnt intended to solve this problem, its just there so we dont wait indefinitely trying to take a checkpoint. If we are able to take a checkpoint and still see the blocking exception, it means there is another place we need to address

**Comment by JasonFengJ9** [comment]
> there might be other places where we need to add the annotation

You are right, it was `java.util.concurrent.ConcurrentHashMap.computeIfAbsent()`.
Annotating that method w/ `@NotCheckpointSafe` passed 500 runs w/ the testcase `org.openj9.criu.TestSingleThreadModeCheckpointException 1 true`.
Will open a PR for jdk17 extension.

**Comment by tajila** [comment]
okay, please open for jdk11 and jdknext as well

**Comment by tajila** [comment]
do you have the full stacktrace for `java.util.concurrent.ConcurrentHashMap.computeIfAbsent().`

**Comment by JasonFengJ9** [comment]
> do you have the full stacktrace for java.util.concurrent.ConcurrentHashMap.computeIfAbsent().

```
Exception in thread "Thread-3" java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:197)
	at org.openj9.criu.TestSingleThreadModeCheckpointException.log(TestSingleThreadModeCheckpointException.java:41)
	at org.openj9.criu.TestSingleThreadModeCheckpointException$2.run(TestSingleThreadModeCheckpointException.java:76)
	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.lambda$registerPreSnapshotHook$3(CRIUSupport.java:472)
	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI$J9InternalCheckpointHook.runHook(J9InternalCheckpointHookAPI.java:116)
	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI.runHooks(J9InternalCheckpointHookAPI.java:80)
	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI.runPreCheckpointHooks(J9InternalCheckpointHookAPI.java:89)
	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:590)
	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:76)
	at org.openj9.criu.TestSingleThreadModeCheckpointException.testSingleThreadModeCheckpointException(TestSingleThreadModeCheckpointException.java:86)
	at org.openj9.criu.TestSingleThreadModeCheckpointException.main(TestSingleThreadModeCheckpointException.java:37)
Caused by: java.lang.invoke.StringConcatException: Generator failed
	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:364)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
	... 15 more
Caused by: org.eclipse.openj9.criu.JVMCheckpointException: Blocking operation is not allowed in CRIU single thread mode.
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1729)
	at java.base/java.lang.invoke.StringConcatFactory.prepender(StringConcatFactory.java:632)
	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:543)
	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:358)
	... 16 more
```

**Comment by tajila** [comment]
Another deadlock, https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/127#issuecomment-1191505909

**Comment by keithc-ca** [comment]
Is there a description somewhere that explains the plan behind the annotation `NotCheckpointSafe`?
It's not looking very scalable or practical to me; e.g. https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/556, https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/128.

**Comment by tajila** [comment]
@keithc-ca See https://github.com/eclipse-openj9/openj9/issues/15367
