### ISSUE TITLE
JDK18 java/lang/invoke/lambda/LambdaFileEncodingSerialization.java error while writing bad filename

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15563]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/66/)(`ubu22lert-1`):
```
openjdk version "18.0.1.1" 2022-04-22
IBM Semeru Runtime Open Edition 18.0.2.0-m2 (build 18.0.1.1+2)
Eclipse OpenJ9 VM 18.0.2.0-m2 (build master-8ead00aa6, JRE 18 Linux ppc64le-64-Bit Compressed References 20220714_19 (JIT enabled, AOT enabled)
OpenJ9   - 8ead00aa6
OMR      - 29756eb80
JCL      - c0b6f04919 based on jdk-18.0.1.1+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk18_j9_sanity.openjdk_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-linux-ppc64le-openj9%2F19%2Fibm-semeru-open-jre_ppc64le_linux_18.0.1.1_2_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-linux-ppc64le-openj9%2F19%2Fibm-semeru-open-testimage_ppc64le_linux_18.0.1.1_2_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-linux-ppc64le-openj9%2F19%2Fibm-semeru-open-jdk_ppc64le_linux_18.0.1.1_2_openj9-0.33.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-linux-ppc64le-openj9%2F19%2Fibm-semeru-open-debugimage_ppc64le_linux_18.0.1.1_2_openj9-0.33.0-m2.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=18&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk18&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=71&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-14T20:51:01.936Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2022-07-14T20:51:01.936Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 


[2022-07-14T21:03:34.599Z] TEST: java/lang/invoke/lambda/LambdaFileEncodingSerialization.java

[2022-07-14T21:03:34.600Z] Output and diagnostic info for process 2652740 was saved into 'pid-2652740-output.log'
[2022-07-14T21:03:34.600Z] /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java:38: error: error while writing ABC???: bad filename RelativeFile[TestLambdaFileEncodingSerialization$ABC???.class]
[2022-07-14T21:03:34.600Z]         public static class ABC???? implements Serializable {
[2022-07-14T21:03:34.600Z]                       ^
[2022-07-14T21:03:34.600Z] Note: /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java uses unchecked or unsafe operations.
[2022-07-14T21:03:34.600Z] Note: Recompile with -Xlint:unchecked for details.
[2022-07-14T21:03:34.600Z] 1 error
[2022-07-14T21:03:34.600Z] 
[2022-07-14T21:03:34.600Z] 
[2022-07-14T21:03:34.600Z] [2022-07-14T21:03:30.598948290Z] Waiting for completion for process 2652740
[2022-07-14T21:03:34.600Z] [2022-07-14T21:03:30.599399090Z] Waiting for completion finished for process 2652740
[2022-07-14T21:03:34.600Z] test LambdaFileEncodingSerialization.testDeserializeLambdaEncoding(): failure
[2022-07-14T21:03:34.600Z] java.lang.AssertionError: Command /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/bin/javac -J-Dfile.encoding=ISO-8859-1 -cp . -d . /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java , failed exitCode = 1 expected [true] but found [false]
[2022-07-14T21:03:34.600Z] 	at org.testng.Assert.fail(Assert.java:99)
[2022-07-14T21:03:34.600Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2022-07-14T21:03:34.600Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2022-07-14T21:03:34.600Z] 	at LambdaFileEncodingSerialization.testDeserializeLambdaEncoding(LambdaFileEncodingSerialization.java:64)
[2022-07-14T21:03:34.600Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-14T21:03:34.600Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-07-14T21:03:34.600Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-07-14T21:03:34.600Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-07-14T21:03:34.600Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-07-14T21:03:34.601Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-07-14T21:03:34.601Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-07-14T21:03:34.601Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-07-14T21:03:34.601Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-07-14T21:03:34.601Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-07-14T21:03:34.601Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-07-14T21:03:34.601Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-07-14T21:03:34.601Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-07-14T21:03:34.601Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-07-14T21:03:34.601Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-07-14T21:03:34.601Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-07-14T21:03:34.601Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-07-14T21:03:34.601Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-07-14T21:03:34.601Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-07-14T21:03:34.601Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-07-14T21:03:34.601Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-07-14T21:03:34.601Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-07-14T21:03:34.601Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-07-14T21:03:34.601Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-07-14T21:03:34.601Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-14T21:03:34.601Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-07-14T21:03:34.601Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-07-14T21:03:34.601Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2022-07-14T21:03:34.601Z] 
[2022-07-14T21:03:34.601Z] ===============================================
[2022-07-14T21:03:34.601Z] java/lang/invoke/lambda/LambdaFileEncodingSerialization.java
[2022-07-14T21:03:34.601Z] Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
[2022-07-14T21:03:34.601Z] ===============================================
[2022-07-14T21:03:34.601Z] 
[2022-07-14T21:03:34.601Z] STDERR:
[2022-07-14T21:03:34.601Z] /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java:38: error: error while writing ABC???: bad filename RelativeFile[TestLambdaFileEncodingSerialization$ABC???.class]
[2022-07-14T21:03:34.601Z]         public static class ABC???? implements Serializable {
[2022-07-14T21:03:34.601Z]                       ^
[2022-07-14T21:03:34.601Z] Note: /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java uses unchecked or unsafe operations.
[2022-07-14T21:03:34.601Z] Note: Recompile with -Xlint:unchecked for details.
[2022-07-14T21:03:34.601Z] 1 error
[2022-07-14T21:03:34.601Z] 
[2022-07-14T21:03:34.601Z] java.lang.Exception: failures: 1
[2022-07-14T21:03:34.601Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2022-07-14T21:03:34.601Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-14T21:03:34.601Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-07-14T21:03:34.601Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-07-14T21:03:34.601Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2022-07-14T21:03:34.601Z] 
[2022-07-14T21:03:34.601Z] JavaTest Message: Test threw exception: java.lang.Exception
[2022-07-14T21:03:34.601Z] JavaTest Message: shutting down test
[2022-07-14T21:03:34.601Z] 
[2022-07-14T21:03:34.601Z] 
[2022-07-14T21:03:34.601Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2022-07-14T21:03:34.601Z] --------------------------------------------------
[2022-07-14T21:46:07.406Z] Test results: passed: 814; failed: 1
[2022-07-14T21:46:20.697Z] Report written to /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/report/html/report.html
[2022-07-14T21:46:20.697Z] Results written to /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_16578318603208/jdk_lang_0/work
[2022-07-14T21:46:20.697Z] Error: Some tests failed or other problems occurred.
[2022-07-14T21:46:20.697Z] 
[2022-07-14T21:46:20.697Z] jdk_lang_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/25840/) - passed

**Comment by pshipton** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_testList_0/80/ ubu22lert-2

**Comment by pshipton** [comment]
Created infrastructure/issues/7188

**Comment by pshipton** [comment]
The machines are updated to the en_US locale, which fixes the failure.
