### ISSUE TITLE
OpenJDK javax/net/ssl/sanity/interop/ClientJSSEServerJSSE.java javax.net.ssl.SSLException: Could not derive key

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15598]
Internal [failure](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/1301/consoleFull)
javax/net/ssl/sanity/interop/ClientJSSEServerJSSE.java (ub20x64rt4-1)
```
21:39:10  ** Failed TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 in TLSv1.2 mode with RSA client authentication**
21:39:10  STDERR:
21:39:10  javax.net.ssl.SSLException: Could not derive key
21:39:10  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
21:39:10  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
21:39:10  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
21:39:10  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1689)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:471)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:921)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1291)
21:39:10  	at java.base/java.io.OutputStream.write(OutputStream.java:122)
21:39:10  	at CipherTest$Client.sendRequest(CipherTest.java:262)javax.net.ssl.SSLException: Received fatal alert: internal_error
21:39:10  
21:39:10  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
21:39:10  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
21:39:10  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:340)
21:39:10  	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
21:39:10  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
21:39:10  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:921)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1012)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:972)
21:39:10  	at CipherTest$Server.handleRequest(CipherTest.java:76)
21:39:10  	at JSSEServer$1.run(JSSEServer.java:71)
21:39:10  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:39:10  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:39:10  	at java.base/java.lang.Thread.run(Thread.java:840)
21:39:10  	at JSSEClient.runTest(JSSEClient.java:61)
21:39:10  	at CipherTest$Client.run(CipherTest.java:249)
21:39:10  	at java.base/java.lang.Thread.run(Thread.java:840)
21:39:10  Caused by: java.security.ProviderException: Could not derive key
21:39:10  	at jdk.crypto.ec/sun.security.ec.NativeECDHKeyAgreement.engineGenerateSecret(NativeECDHKeyAgreement.java:248)
21:39:10  	at jdk.crypto.ec/sun.security.ec.NativeECDHKeyAgreement.engineGenerateSecret(NativeECDHKeyAgreement.java:200)
21:39:10  	at jdk.crypto.ec/sun.security.ec.NativeECDHKeyAgreement.engineGenerateSecret(NativeECDHKeyAgreement.java:265)
21:39:10  	at java.base/javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:660)
21:39:10  	at java.base/sun.security.ssl.KAKeyDerivation.t12DeriveKey(KAKeyDerivation.java:77)
21:39:10  	at java.base/sun.security.ssl.KAKeyDerivation.deriveKey(KAKeyDerivation.java:61)
21:39:10  	at java.base/sun.security.ssl.ECDHClientKeyExchange$ECDHClientKeyExchangeProducer.produce(ECDHClientKeyExchange.java:221)
21:39:10  	at java.base/sun.security.ssl.ClientKeyExchange$ClientKeyExchangeProducer.produce(ClientKeyExchange.java:65)
21:39:10  	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
21:39:10  	at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:182)
21:39:10  	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
21:39:10  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
21:39:10  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
21:39:10  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
21:39:10  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
21:39:10  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
21:39:10  	... 7 more
21:39:10  java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
21:39:10  	at CipherTest.run(CipherTest.java:207)
21:39:10  	at CipherTest.main(CipherTest.java:329)
21:39:10  	at ClientJSSEServerJSSE.main(ClientJSSEServerJSSE.java:42)
21:39:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:39:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:39:10  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:39:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
21:39:10  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:39:10  	at java.base/java.lang.Thread.run(Thread.java:840)
21:39:10  
21:39:10  JavaTest Message: Test threw exception: java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
```

[alon-sh](https://github.com/alon-sh) commented [6 minutes ago](https://github.com/eclipse-openj9/openj9/issues/15171#issuecomment-1191706559)

error looks related to the OpenSSL EC support.

@ZainabF92 please look at this error. You can see NativeECDHKeyAgreement throwing an error in one of the runs. Easiest way to confirm if this is due to your latest changes is to turn off OpenSSL based EC and see if still fails.

**Comment by pshipton** [comment]
@ZainabF92

**Comment by pshipton** [comment]
Another one in [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_8/386) ub20x64rt4-1

Maybe specific to that machine?

**Comment by ZainabF92** [comment]
Same cipher suite as before, but different type:
```
21:39:10  ** Failed TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 in TLSv1.2 mode with RSA client authentication**
21:39:10  Passed TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 in TLSv1.2 mode
```
and now:
```
02:05:41  ** Failed TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 in TLSv1.2 mode**
02:05:41  Passed TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 in TLSv1.2 mode with RSA client authentication
```

**Comment by pshipton** [comment]
Another one in [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_4/1097/) on ub20x64rt4-10 so it's specific to only one machine.

**Comment by pshipton** [comment]
Some other failures I saw: [a](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_4/1115/) (ub20x64rt3-5), [b](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/1346/) (ub20x64rt3-1), [c](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/1257/) (ub20x64rt1-6)

I also tried a grinder on amac, which runs much faster, and the problem reproduced [there](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/1505) too.

**Comment by ZainabF92** [comment]
The failure is due to the public key being `null` when deriving the shared secret in native code (even though a null check is done in Java before the native code is called), which results in a point at infinity in the openssl method `ECDH_compute_key`.

Still investigating why and when this happens.
