### ISSUE TITLE
Windows java/util/Base64/TestEncodingDecodingLength.java OutOfMemoryError: Java heap space - Failed to commit memory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15605]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly/112 - [win2019-x64-3](https://openj9-jenkins.osuosl.org/computer/win2019-x64-3)
Both jdk_util_0 and jdk_util_1
java/util/Base64/TestEncodingDecodingLength.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly/112/openjdk_test_output.tar.gz

```
02:22:43  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Java heap space
02:22:43  REASON: User specified action: run main/othervm -Xms6g -Xmx8g TestEncodingDecodingLength 
02:22:43  TIME:   18.422 seconds
02:22:43  messages:
02:22:43  command: main -Xms6g -Xmx8g TestEncodingDecodingLength
02:22:43  reason: User specified action: run main/othervm -Xms6g -Xmx8g TestEncodingDecodingLength 
02:22:43  Mode: othervm [/othervm specified]
02:22:43  elapsed time (seconds): 18.422
02:22:43  configuration:
02:22:43  STDOUT:
02:22:43  STDERR:
02:22:43  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/07/22 02:22:28 - please wait.
02:22:43  JVMDUMP032I JVM requested Java dump using 'F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16584645843913\jdk_util_0\work\scratch\3\javacore.20220722.022228.13936.0001.txt' in response to an event
02:22:43  JVMDUMP010I Java dump written to F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16584645843913\jdk_util_0\work\scratch\3\javacore.20220722.022228.13936.0001.txt
02:22:43  JVMDUMP032I JVM requested Snap dump using 'F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16584645843913\jdk_util_0\work\scratch\3\Snap.20220722.022228.13936.0002.trc' in response to an event
02:22:43  JVMDUMP010I Snap dump written to F:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16584645843913\jdk_util_0\work\scratch\3\Snap.20220722.022228.13936.0002.trc
02:22:43  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
02:22:43  java.lang.OutOfMemoryError: Java heap space
02:22:43  	at java.base/java.util.Base64$Decoder.decode(Base64.java:565)
02:22:43  	at TestEncodingDecodingLength.main(TestEncodingDecodingLength.java:56)
02:22:43  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
02:22:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
02:22:43  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
02:22:43  	at java.base/java.lang.Thread.run(Thread.java:857)
```

A machine problem, the javacore shows:
`3STHSTTYPE     06:22:28:275880323 GMT j9mm.506 - * Failed to commit memory: address=000000071FFF0000, size=2147483648`

**Comment by pshipton** [comment]
More memory related failures on [win2019-x64-3](https://openj9-jenkins.osuosl.org/computer/win2019-x64-3)
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly/116/
    java/util/Base64/TestEncodingDecodingLength.java.TestEncodingDecodingLength
    java/util/BitSet/BSMethods.java.BSMethods
    java/util/Calendar/BuddhistCalendarTest.java.BuddhistCalendarTest
    java/util/Calendar/CalendarTestScripts/JapaneseTests.java.JapaneseTests

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly/116/openjdk_test_output.tar.gz

@AdamBrousseau @vsebe

**Comment by pshipton** [comment]
More OOMs on the same machine.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/282/

**Comment by pshipton** [comment]
More, same machine.
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_OpenJDK19/10/
    java/math/BigInteger/ExtremeShiftingTests.java.ExtremeShiftingTests
    java/util/Base64/TestEncodingDecodingLength.java.TestEncodingDecodingLength
    java/util/Base64/TestEncodingDecodingLength.java.TestEncodingDecodingLength

**Comment by pshipton** [comment]
Another, also [win2019-x64-3](https://openj9-jenkins.osuosl.org/computer/win2019-x64-3)
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Release/39/
java/util/BitSet/BSMethods.java (jdk_util_0)
```
3STHSTTYPE     13:16:31:434456475 GMT j9mm.506 - * Failed to commit memory: address=00000000A01F0000, size=378732544
```

**Comment by pshipton** [comment]
Another on [win2019-x64-3](https://openj9-jenkins.osuosl.org/computer/win2019-x64-3)
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Release/40
java/util/BitSet/BSMethods.java (jdk_util_0)
```
09:13:54  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata.  200M requested
```
