### ISSUE TITLE
DaaLoadTest net.openj9.test.decimals.TestDecimalData2 OOM

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15607]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/289/)(`ubu22ppclert-3`):
```
openjdk version "1.8.0_342"
IBM Semeru Runtime Open Edition (build 1.8.0_342-b07)
Eclipse OpenJ9 VM (build openj9-0.33.0-rc1a, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20220721_409 (JIT enabled, AOT enabled)
OpenJ9   - 04a55b45b
OMR      - b58aa2708
JCL      - 459493948e based on jdk8u342-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F409%2Fibm-semeru-open-debugimage_ppc64le_linux_8u342b07_openj9-0.33.0-rc1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F409%2Fibm-semeru-open-jdk_ppc64le_linux_8u342b07_openj9-0.33.0-rc1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F409%2Fibm-semeru-open-jre_ppc64le_linux_8u342b07_openj9-0.33.0-rc1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F409%2Fibm-semeru-open-testimage_ppc64le_linux_8u342b07_openj9-0.33.0-rc1a.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.3-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&RELEASE_TAG=v0.33.0-release&OPENJ9_BRANCH=v0.33.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.33.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=310&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=true&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-22T02:30:37.248Z] variation: Mode101
[2022-07-22T02:30:37.248Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs 

[2022-07-22T02:31:00.217Z] DLT 02:30:59.382 - Completed 6.7%. Number of tests started=2210
[2022-07-22T02:31:20.927Z] DLT 02:31:19.341 - Completed 13.3%. Number of tests started=4654 (+2444)
[2022-07-22T02:31:38.238Z] DLT stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/07/22 02:31:36 - please wait.
[2022-07-22T02:31:38.238Z] DLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/core.20220722.023136.681602.0001.dmp' in response to an event
[2022-07-22T02:31:38.238Z] DLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/core.20220722.023136.681602.0001.dmp
[2022-07-22T02:31:38.239Z] DLT stderr JVMDUMP032I JVM requested Heap dump using '/home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/heapdump.20220722.023136.681602.0002.phd' in response to an event
[2022-07-22T02:31:38.239Z] DLT stderr JVMDUMP010I Heap dump written to /home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/heapdump.20220722.023136.681602.0002.phd
[2022-07-22T02:31:38.239Z] DLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/javacore.20220722.023136.681602.0003.txt' in response to an event
[2022-07-22T02:31:38.605Z] STF 02:31:37.718 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/javacore.20220722.023136.681602.0003.txt
[2022-07-22T02:31:38.605Z] STF 02:31:37.718 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/core.20220722.023136.681602.0001.dmp
[2022-07-22T02:31:38.605Z] STF 02:31:37.718 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/aqa-tests/TKG/output_16584479858476/DaaLoadTest_all_special_5m_0/20220722-023037-DaaLoadTest/results/heapdump.20220722.023136.681602.0002.phd
[2022-07-22T02:31:38.998Z] DLT 02:31:37.793 - First failure detected by thread: load-11. Not creating dumps as no dump generation is requested for this load test
[2022-07-22T02:31:38.998Z] DLT 02:31:37.805 - Test failed
[2022-07-22T02:31:38.998Z] DLT   Failure num.  = 1
[2022-07-22T02:31:38.998Z] DLT   Test number   = 14
[2022-07-22T02:31:38.998Z] DLT   Test details  = 'JUnit[net.openj9.test.decimals.TestDecimalData2]'
[2022-07-22T02:31:38.998Z] DLT   Suite number  = 0
[2022-07-22T02:31:38.998Z] DLT   Thread number = 11
[2022-07-22T02:31:38.998Z] DLT >>> Captured test output >>>

[2022-07-22T02:31:38.999Z] DLT testFailure: testOtherConvertes_UDSL(net.openj9.test.decimals.TestDecimalData2): Java heap space
[2022-07-22T02:31:38.999Z] DLT java.lang.OutOfMemoryError: Java heap space
[2022-07-22T02:31:38.999Z] DLT 	at net.openj9.test.arithmetics.TestPerformance.setUpResultSpace(TestPerformance.java:386)
[2022-07-22T02:31:38.999Z] DLT 	at net.openj9.test.arithmetics.TestPerformance.testDiv(TestPerformance.java:166)
[2022-07-22T02:31:38.999Z] DLT 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-07-22T02:31:38.999Z] DLT 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-07-22T02:31:38.999Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2022-07-22T02:31:38.999Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-07-22T02:31:38.999Z] DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-07-22T02:31:38.999Z] DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-07-22T02:31:38.999Z] DLT 	at java.lang.Thread.run(Thread.java:827)
[2022-07-22T02:31:38.999Z] DLT testFinished: testOtherConvertes_UDSL(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testOverflowED2Long(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testOverflowED2Long(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testConvertLongNormals(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testConvertLongNormals(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testBDToPD(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testBDToPD(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testi2PDExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testi2PDExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testConvertIntegerNormals(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testConvertIntegerNormals(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testInteger2ED2Integer(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testInteger2ED2Integer(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testNonExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testNonExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testSmallestLong2ED2Long(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testSmallestLong2ED2Long(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testBiggestInteger2UD2Integer(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testBiggestInteger2UD2Integer(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testConvertBigIntegerExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testConvertBigIntegerExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testOtherConverters(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testOtherConverters(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testConvertIntegerExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testConvertIntegerExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testInteger2ED2IntegerDecreasingPrecision(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testInteger2ED2IntegerDecreasingPrecision(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testStarted : testConvertBigDecimalExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT testFinished: testConvertBigDecimalExceptions(net.openj9.test.decimals.TestDecimalData2)
[2022-07-22T02:31:38.999Z] DLT 
[2022-07-22T02:31:38.999Z] DLT JUnit Test Results for: net.openj9.test.decimals.TestDecimalData2
[2022-07-22T02:31:38.999Z] DLT   Ran    : 31
[2022-07-22T02:31:38.999Z] DLT   Passed : 30
[2022-07-22T02:31:38.999Z] DLT   Failed : 1
[2022-07-22T02:31:38.999Z] DLT   Ignored: 0
[2022-07-22T02:31:38.999Z] DLT   Result : FAILED
[2022-07-22T02:31:38.999Z] DLT Test failed:
[2022-07-22T02:31:38.999Z] DLT java.lang.OutOfMemoryError: Java heap space
[2022-07-22T02:31:38.999Z] DLT 	at net.openj9.test.arithmetics.TestPerformance.setUpResultSpace(TestPerformance.java:386)
[2022-07-22T02:31:38.999Z] DLT 	at net.openj9.test.arithmetics.TestPerformance.testDiv(TestPerformance.java:166)
[2022-07-22T02:31:38.999Z] DLT 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-07-22T02:31:38.999Z] DLT 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-07-22T02:31:38.999Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-07-22T02:31:38.999Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2022-07-22T02:31:38.999Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-07-22T02:31:38.999Z] DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-07-22T02:31:38.999Z] DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-07-22T02:31:38.999Z] DLT 	at java.lang.Thread.run(Thread.java:827)
[2022-07-22T02:31:38.999Z] DLT <<<
[2022-07-22T02:31:38.999Z] DLT 
[2022-07-22T02:31:38.999Z] DLT 02:31:37.805 - Out of memory exception. Aborting test run

[2022-07-22T02:31:41.246Z] DaaLoadTest_all_special_5m_0_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26073/)

**Comment by pshipton** [comment]
[artifact](https://na.artifactory.swg-devops.com/artifactory/sys-rt-generic-local/hyc-runtimes-jenkins.swg-devops.com/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/289/system_test_output.tar.gz)
```
1STGCHTYPE     GC History
3STHSTTYPE     02:31:36:751452781 GMT j9mm.101 -   J9AllocateIndexableObject() returning NULL! 9185370712 bytes requested for object of class 0000737EBC553E00 from memory space 'Flat' id=0000737EBC0D3D50
3STHSTTYPE     02:31:36:751243783 GMT j9mm.134 -   Allocation failure end: newspace=0/0 oldspace=2091652000/2116419584 loa=21165056/21165056
3STHSTTYPE     02:31:36:751237783 GMT j9mm.470 -   Allocation failure cycle end: newspace=0/0 oldspace=2091652000/2116419584 loa=21165056/21165056
3STHSTTYPE     02:31:36:751188784 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=2091652000/2116419584
3STHSTTYPE     02:31:36:751131784 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     02:31:36:750309792 GMT j9mm.137 -   Compact end: bytesmoved=22528832
3STHSTTYPE     02:31:36:703646212 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     02:31:36:703644212 GMT j9mm.57 -   Sweep end
3STHSTTYPE     02:31:36:701650230 GMT j9mm.56 -   Sweep start
```
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "load-11" J9VMThread:0x0000737EBCA36200, omrthread_t:0x0000737EBC9F18E8, java/lang/Thread:0x0000737E3D060CB0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x3D, isDaemon:false)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x0000737E3CEAACF8)
3XMTHREADINFO1            (native thread ID:0xA66BE, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00001020)
3XMTHREADINFO2            (native stack address range from:0x0000737D638D0000, to:0x0000737D63950000, size:0x80000)
3XMCPUTIME               CPU usage total: 28.483683390 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at net/openj9/test/arithmetics/TestPerformance.setUpResultSpace(TestPerformance.java:386(Compiled Code))
4XESTACKTRACE                at net/openj9/test/arithmetics/TestPerformance.testDiv(TestPerformance.java:166(Compiled Code))
4XESTACKTRACE                at sun/reflect/DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Constructor.newInstance(Constructor.java:423(Compiled Code))
4XESTACKTRACE                at org/junit/runners/BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217(Compiled Code))
```
```
    public void setUpResultSpace(int numBits, int sampleSize)
    {
        resultArray = new byte[sampleSize][numBits];   <- line 386
...
    public void testDiv(int sampleSize, int multiplier) throws Exception
    {
        setUpResultSpace(sampleSize, sampleSize);    <- line 166

```

Seems like the stack is missing a frame or two, it doesn't show how testDiv() is called. There is a call from the following method.
```
    public void testIntrinsicPerformance() throws Exception
    {
        int sampleSize = 1000;
        int multiplier = 100;
        try
        {
            {
                testAdd(sampleSize, multiplier);
                testSub(sampleSize, multiplier);
                testMul(sampleSize, multiplier);
                testDiv(sampleSize, multiplier);
```

@0xdaryl I'm tagging this as JIT.
