### ISSUE TITLE
DaaLoadTest_all_special_5m_0_FAILED net.openj9.test.arithmetics.TestPDComparisons - IllegalArgumentException: object is not an instance of declaring class

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15622]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_ppc64le_linux_testList_1/291/)(`ubu22ppclert-3`):
```
openjdk version "1.8.0_342"
IBM Semeru Runtime Open Edition (build 1.8.0_342-b06)
Eclipse OpenJ9 VM (build master-e70b78378, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20220722_411 (JIT enabled, AOT enabled)
OpenJ9   - e70b78378
OMR      - 6061e7ce4
JCL      - 4cb47cd7a based on jdk8u342-b06)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F411%2Fibm-semeru-open-jre_ppc64le_linux_JDK8U_2022-07-23-02-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F411%2Fibm-semeru-open-testimage_ppc64le_linux_JDK8U_2022-07-23-02-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F411%2Fibm-semeru-open-debugimage_ppc64le_linux_JDK8U_2022-07-23-02-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-ppc64le-openj9%2F411%2Fibm-semeru-open-jdk_ppc64le_linux_JDK8U_2022-07-23-02-31.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=312&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-23T05:55:27.653Z] variation: Mode101
[2022-07-23T05:55:27.653Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs 

[2022-07-23T05:56:16.670Z] DLT 05:56:15.920 - Test failed
[2022-07-23T05:56:16.670Z] DLT   Failure num.  = 1
[2022-07-23T05:56:16.670Z] DLT   Test number   = 6
[2022-07-23T05:56:16.670Z] DLT   Test details  = 'JUnit[net.openj9.test.arithmetics.TestPDComparisons]'
[2022-07-23T05:56:16.670Z] DLT   Suite number  = 0
[2022-07-23T05:56:16.670Z] DLT   Thread number = 25
[2022-07-23T05:56:16.670Z] DLT >>> Captured test output >>>

[2022-07-23T05:56:16.671Z] DLT testFailure: testZeroDiffSigns(net.openj9.test.arithmetics.TestPDComparisons): object is not an instance of declaring class
[2022-07-23T05:56:16.671Z] DLT java.lang.IllegalArgumentException: object is not an instance of declaring class
[2022-07-23T05:56:16.671Z] DLT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-07-23T05:56:16.671Z] DLT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-07-23T05:56:16.671Z] DLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-07-23T05:56:16.671Z] DLT 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2022-07-23T05:56:16.671Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2022-07-23T05:56:16.671Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2022-07-23T05:56:16.671Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-07-23T05:56:16.671Z] DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-07-23T05:56:16.671Z] DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-07-23T05:56:16.671Z] DLT 	at java.lang.Thread.run(Thread.java:826)
[2022-07-23T05:56:16.671Z] DLT testFinished: testZeroDiffSigns(net.openj9.test.arithmetics.TestPDComparisons)
[2022-07-23T05:56:16.671Z] DLT testStarted : testGreaterNegatives(net.openj9.test.arithmetics.TestPDComparisons)
[2022-07-23T05:56:16.671Z] DLT testFailure: testGreaterNegatives(net.openj9.test.arithmetics.TestPDComparisons): object is not an instance of declaring class
[2022-07-23T05:56:16.671Z] DLT java.lang.IllegalArgumentException: object is not an instance of declaring class
[2022-07-23T05:56:16.671Z] DLT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-07-23T05:56:16.671Z] DLT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2022-07-23T05:56:16.673Z] DLT JUnit Test Results for: net.openj9.test.arithmetics.TestPDComparisons
[2022-07-23T05:56:16.673Z] DLT   Ran    : 26
[2022-07-23T05:56:16.673Z] DLT   Passed : 16
[2022-07-23T05:56:16.673Z] DLT   Failed : 10
[2022-07-23T05:56:16.673Z] DLT   Ignored: 0
[2022-07-23T05:56:16.673Z] DLT   Result : FAILED
[2022-07-23T05:56:16.673Z] DLT <<<
[2022-07-23T05:56:16.673Z] DLT 

[2022-07-23T05:56:21.617Z] DaaLoadTest_all_special_5m_0_FAILED
```

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/15578
