### ISSUE TITLE
JDK17 Assertion Failed with memoryCorruptionDetected

### ISSUE THREAD

**Issue by lochnagarr** [eclipse-openj9/openj9#15639]
Java -version output
--------------------

openjdk version "17.0.3" 2022-04-19
IBM Semeru Runtime Open Edition 17.0.3.0 (build 17.0.3+7)
Eclipse OpenJ9 VM 17.0.3.0 (build openj9-0.32.0, JRE 17 Linux amd64-64-Bit Compressed References 20220422_184 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - dc07fd49b92 based on jdk-17.0.3+7)

Summary of problem
------------------

When running a buggy classfile generated by a fuzzer, JVM crashes and we get the following message:

```
06:21:46.676 0x21f00 omrport.359    *   ** ASSERTION FAILED ** at ../../../../../../omr/port/common/omrmemtag.c:145: ((memoryCorruptionDetected))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/07/28 14:21:46 - please wait.
JVMDUMP032I JVM requested System dump using '/home/minghai/bug_memory/core.20220728.142146.24281.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/minghai/bug_memory/core.20220728.142146.24281.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/minghai/bug_memory/javacore.20220728.142146.24281.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/minghai/bug_memory/javacore.20220728.142146.24281.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/minghai/bug_memory/Snap.20220728.142146.24281.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/minghai/bug_memory/Snap.20220728.142146.24281.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
```

We have collected the related classfiles and dependencies in bug_memory.zip:
[bug_memory.zip](https://github.com/eclipse-openj9/openj9/files/9206108/bug_memory.zip)
The buggy classfile is in `bug_memory/bug_file`

To reproduce this issue, enter `bug_memory` and run the following command:
```
java -jar ./junit-platform-console-standalone-1.8.2.jar -cp ./bug_file:./util:./test-classes:./classes:./guava-31.0.1-jre.jar:./javax.inject-1.jar:./failureaccess-1.0.1.jar -m com.google.inject.spi.InjectionPointTest#testConstructorInjectionPoint
```
To avoid this issue, run
```
java -jar ./junit-platform-console-standalone-1.8.2.jar -cp ./test-classes:./classes:./guava-31.0.1-jre.jar:./javax.inject-1.jar:./failureaccess-1.0.1.jar -m com.google.inject.spi.InjectionPointTest#testConstructorInjectionPoint
```
Adding `-noverify` will also avoid this issue, but may lead to `Segmentation error vmState=0x00000000`

We also tested this in HotSpot, and the buggy classfile leads to a VerifyError.

Diagnostic files
----------------
[javacore.20220728.135359.622426.0002.txt](https://github.com/eclipse-openj9/openj9/files/9206094/javacore.20220728.135359.622426.0002.txt)
[Snap.20220728.135359.622426.0003.zip](https://github.com/eclipse-openj9/openj9/files/9206093/Snap.20220728.135359.622426.0003.zip)

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@ChengJin01 Can you please take a look at this

**Comment by ChengJin01** [comment]
1) I reproduced the crash in a debug build with backtrace as follows:
```
#36 0x00007ffff75da768 in omrmem_free_memory (portLibrary=0x7ffff7a129d0 <j9portLibrary>, memoryPointer=0x7ffff05d6d30) at ../../omr/port/common/omrmemtag.c:205
#37 0x00007ffff5adfdd0 in releaseVerificationTypeBuffer (stackMapFrame=0x7ffff7a9b7a0, methodInfo=0x7ffff7a9b7e8) at errormessagehelper.c:809
#38 0x00007ffff5add7f8 in generateJ9RtvExceptionDetails (verifyData=0x7ffff00dfb20, initMsgBuffer=0x7ffff7a9b9d8 "\nException Details:\n  Location:\n    com/google/inject/spi/InjectionPoint.forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/Annot"..., msgBufferLength=0x7ffff7a9b980) at errormessageframeworkrtv.c:981
#39 0x00007ffff7895f98 in j9bcv_createVerifyErrorString (portLib=0x7ffff7a129d0 <j9portLibrary>, error=0x7ffff00dfb20) at vrfyhelp.c:832
#40 0x00007ffff770ea58 in performVerification (currentThread=0xc8200, clazz=0x517600) at ClassInitialization.cpp:188
#41 0x00007ffff770fd40 in classInitStateMachine (currentThread=0xc8200, clazz=0x517600, desiredState=J9_CLASS_INIT_INITIALIZED) at ClassInitialization.cpp:495
#42 0x00007ffff770f590 in initializeClass (currentThread=0xc8200, clazz=0x517600) at ClassInitialization.cpp:341
#43 0x00007ffff7827ef4 in resolveClassRef (vmStruct=0xc8200, ramCP=0x4598c0, cpIndex=12, resolveFlags=65) at resolvesupport.cpp:445


(gdb) frame 38
#38 0x00007ffff5add7f8 in generateJ9RtvExceptionDetails (verifyData=0x7ffff00dfb20, initMsgBuffer=0x7ffff7a9b9d8 "\nException Details:\n  Location:\n    com/google/inject/spi/InjectionPoint.forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/Annot"..., msgBufferLength=0x7ffff7a9b980) at errormessageframeworkrtv.c:981
981             releaseVerificationTypeBuffer(&stackMapFrameTarget, &methodInfo);

(gdb) printf  "%s\n",  msgBuf->buffer

Exception Details:
  Location:
    com/google/inject/spi/InjectionPoint.forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/AnnotatedType;[[Ljava/lang/annotation/Annotation;Ljava/util/function/Predicate;)Lcom/google/common/collect/ImmutableList; @905: JBgoto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @905
    flags: { }
    locals: { 'com/google/inject/spi/InjectionPoint', 'com/google/inject/internal/Errors', 'java/lang/reflect/Member', 'java/util/Iterator', '[Ljava/lang/reflect/AnnotatedType;', '[[Ljava/lang/annotation/Annotation;', 'java/util/function/Predicate', integer, integer, 'java/util/ArrayList', 'java/lang/reflect/AnnotatedType', 'com/google/inject/TypeLiteral', integer, '[Ljava/lang/annotation/Annotation;', '[Ljava/lang/annotation/Annotation;', 'com/google/inject/Key', integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, top, integer, integer, integer, integer, integer, integer, integer, integer, integer }
    stack: { }
```
which means the error message was successfully created & printed to the message buffer but the crash occurred when releasing the stackmape frame memory afterwards at 
```
#37 0x00007ffff5adfdd0 in releaseVerificationTypeBuffer
 (stackMapFrame=0x7ffff7a9b7a0, methodInfo=0x7ffff7a9b7e8) at errormessagehelper.c:809 <--------
#38 0x00007ffff5add7f8 in generateJ9RtvExceptionDetails (verifyData=0x7ffff00dfb20, initMsgBuffer=0x7ffff7a9b9d8 "\nException Details:\n  Location:\n    com/google/inject/spi/InjectionPoint.forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/Annot"..., msgBufferLength=0x7ffff7a9b980) at errormessageframeworkrtv.c:981
```
against the code in `releaseVerificationTypeBuffer()` at /runtime/verbose/errormessagehelper.c
```
releaseVerificationTypeBuffer(StackMapFrame* stackMapFrame, MethodContextInfo* methodInfo)
{
	if (NULL != stackMapFrame->entries) {
		PORT_ACCESS_FROM_PORT(methodInfo->portLib);
		j9mem_free_memory(stackMapFrame->entries); <---------
	}
}
```

2) Looking at the error message above:
```
  Reason:
    Current frame's stack size doesn't match stackmap. <------
```
against the code in `generateJ9RtvExceptionDetails()` at /runtime/verbose/errormessageframeworkrtv.c
```
	case BCV_ERR_STACK_SIZE_MISMATCH:
		printMessage(&msgBuf, "Current frame's stack size doesn't match stackmap.");
		printStackFrame = setStackMapFrameWithIndex(verifyData, &methodInfo, &stackMapFrameTarget);
		break;
```
It seems the problem was triggered somewhere in `setStackMapFrameWithIndex()`

3) Further debugging indicates it failed to allocate the stackmap frame due to the unexpected huge requested size:
```
Thread 2 "main" hit Breakpoint 7, allocateMemoryToVerificationTypeBuffer (methodInfo=0x7ffff7a9b7e8, stackMapFrame=0x7ffff7a9b7a0, currentVerificationTypeEntry=0x7ffff05cd010, 
slotCount=18446744073709486134 <---- a huge size was requested when allocating memory for the stackmap frame
) at errormessagehelper.c:200
200                             currentVerificationTypeEntry = NULL; <-------
(gdb) bt
#0  allocateMemoryToVerificationTypeBuffer (methodInfo=0x7ffff7a9b7e8, stackMapFrame=0x7ffff7a9b7a0, currentVerificationTypeEntry=0x7ffff05cd010, slotCount=18446744073709486134) at errormessagehelper.c:200
#1  0x00007ffff5ade2a4 in pushTopTypeToVerificationTypeBuffer (methodInfo=0x7ffff7a9b7e8, stackMapFrame=0x7ffff7a9b7a0, currentVerificationTypeEntry=0x7ffff05cd010, slotCount=18446744073709486134) at errormessagehelper.c:219
#2  0x00007ffff5adf254 in decodeConstuctedStackMapFrameData (stackMapFrame=0x7ffff7a9b7a0, nextStackmapFrame=0x7ffff05f2af8 "\261\003", stackmapFrameIndex=36, methodInfo=0x7ffff7a9b7e8, verifyData=0x7ffff00dfb20) at errormessagehelper.c:558
#3  0x00007ffff5adecd0 in decodeStackmapFrameData (stackMapFrame=0x7ffff7a9b7a0, nextStackmapFrame=0x7ffff05f2900 "\250\003", stackmapFrameIndex=36, methodInfo=0x7ffff7a9b7e8, verifyData=0x7ffff00dfb20) at errormessagehelper.c:423
#4  0x00007ffff5adccfc in setStackMapFrameWithIndex (verifyData=0x7ffff00dfb20, methodInfo=0x7ffff7a9b7e8, targetFrame=0x7ffff7a9b7a0) at errormessageframeworkrtv.c:723
#5  0x00007ffff5add270 in generateJ9RtvExceptionDetails (verifyData=0x7ffff00dfb20, initMsgBuffer=0x7ffff7a9b9d8 "\nException Details:\n  Location:\n    com/google/inject/spi/InjectionPoint.forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/AnnotatedType;[[Ljava/lang/annotation/Annotation;Ljava/util/function/Predicate;)Lcom/google/common/collect/ImmutableList; @905: JBgoto\n  Reason:\n    Current frame's stack size doesn't match stackmap.", msgBufferLength=0x7ffff7a9b980) at errormessageframeworkrtv.c:872
...

(gdb) frame 2
#2  0x00007ffff5adf254 in decodeConstuctedStackMapFrameData (stackMapFrame=0x7ffff7a9b7a0, nextStackmapFrame=0x7ffff05f2af8 "\261\003", stackmapFrameIndex=36, methodInfo=0x7ffff7a9b7e8, verifyData=0x7ffff00dfb20) at errormessagehelper.c:558
558             currentVerificationTypeEntry = pushTopTypeToVerificationTypeBuffer(methodInfo, stackMapFrame, currentVerificationTypeEntry, maxLocals - stackMapFrame->numberOfLocals);
(gdb) p maxLocals
$31 = 53
(gdb) p stackMapFrame->numberOfLocals  <-------------
$32 = 65535
```
which means `stackMapFrame->numberOfLocals` was set to a wrong value in `decodeConstuctedStackMapFrameData` (the class version < 50 in which case the stackmaps are created internally based on the class bytecode)

4) Looking at the code in `decodeConstuctedStackMapFrameData()` at /runtime/verbose/errormessagehelper.c 
```
U_8*
decodeConstuctedStackMapFrameData(StackMapFrame* stackMapFrame, U_8* nextStackmapFrame, I_32 stackmapFrameIndex, MethodContextInfo* methodInfo, J9BytecodeVerificationData* verifyData)
{
	J9BranchTargetStack * targetStackmapFrame = BCV_INDEX_STACK((UDATA)stackmapFrameIndex);
	IDATA stackBaseIndex = targetStackmapFrame->stackBaseIndex; <------- stackBaseIndex is -1
	IDATA stackTopIndex = targetStackmapFrame->stackTopIndex;
	VerificationTypeInfo* currentVerificationTypeEntry = stackMapFrame->entries;
	U_16 maxStack = methodInfo->maxStack;
	U_16 maxLocals = methodInfo->maxLocals;
	IDATA lastIndex = stackBaseIndex - 1; <------- lastIndex  is -2 in such case
	IDATA slot = 0;
	IDATA dataTypeCode = DATATYPE_1_SLOT;
	BOOLEAN nonTopFound = FALSE;

	nextStackmapFrame = (U_8*)BCV_NEXT_STACK(targetStackmapFrame);

	stackMapFrame->bci = (U_16)targetStackmapFrame->pc;

	/* 'locals' on 'Stackmap Frame' */
	stackMapFrame->numberOfLocals = (U_16)(lastIndex + 1); <----- wrongly converted be 65535

(gdb) p  *targetStackmapFrame
$52 = {
  pc = 936,
  uninitializedThis = 0,
  stackBaseIndex = -1, <---------- (this is the default value when creating the stackmaps)
  stackTopIndex = -1,
  stackElements = {0}
}
``` 
which means there is no element of 'locals' and 'stack' in the current stackmap frame in which case the code above didn't handle at this point.

**Comment by ChengJin01** [comment]
Looking at the Verification error message generated by Hotspot as follows:
```
jdk17_hotspot_openjdk/bin/java -jar ./junit-platform-console-standalone-1.8.2.jar -cp ./bug_file:./util:./test-classes:./classes:./guava-31.0.1-jre.jar:./javax.inject-1.jar:./failureaccess-1.0.1.jar -m com.google.inject.spi.InjectionPointTest#testConstructorInjectionPoint

hanks for using JUnit! Support its development at https://junit.org/sponsoring
...
Failures (1):
  JUnit Vintage:InjectionPointTest:testConstructorInjectionPoint
    MethodSource [className = 'com.google.inject.spi.InjectionPointTest', methodName = 'testConstructorInjectionPoint', methodParameterTypes = '']
    => java.lang.VerifyError: Expecting a stackmap frame at branch target 71
Exception Details:
  Location:
    com/google/inject/spi/InjectionPoint.<init>(Lcom/google/inject/TypeLiteral;Ljava/lang/reflect/Field;Z)V @52: aload_1
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 2ab7 0198 2a2c b502 3b2a 2bb5 0283 2a1d
...
    00000c0: b1                                     
  Exception Handler Table:
    bci [52, 68] => handler: 71
    bci [52, 68] => handler: 99

       com.google.inject.spi.InjectionPointTest.testConstructorInjectionPoint(InjectionPointTest.java:64)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```
which shows it captured the error with `com/google/inject/spi/InjectionPoint.<init>` while ours captured the error with `com/google/inject/spi/InjectionPoint.forMember`.  It is likely that there multiple verification errors caused by different methods in the buggy class file but the question is whether `com/google/inject/spi/InjectionPoint.forMember` is the first problematic method captured in our Verififer. 

So there might be two issues with our code:
1) we only need to fix up the issue with the crash if `com/google/inject/spi/InjectionPoint.forMember` is the first problematic method captured in our Verififer.
2) if not the case, then the next step is to figure out whether `com/google/inject/spi/InjectionPoint.<init>` passed without any error.

**Comment by ChengJin01** [comment]
FYI: @DanHeidinga

**Comment by ChengJin01** [comment]
I will be on vacation next week and get back to keep working on this issue.

**Comment by ChengJin01** [comment]
With my fix at https://github.com/ChengJin01/openj9/commit/b557b59c93519c5a5060b2b748d824103c99d3b6, the assertion was resolved and ended up with the expected error message as follows:
```
jdk17_openj9_build/bin/java -jar ./junit-platform-console-standalone-1.8.2.jar -cp ./bug_file:./util:./test-classes:./classes:./guava-31.0.1-jre.jar:./javax.inject-1.jar:./failureaccess-1.0.1.jar -m com.google.inject.spi.InjectionPointTest#testConstructorInjectionPoint

Thanks for using JUnit! Support its development at https://junit.org/sponsoring

?
├─ JUnit Jupiter ?
└─ JUnit Vintage ?
   └─ InjectionPointTest ?
      └─ testConstructorInjectionPoint ? JVMVRFY021 thrown object not throwable; class=com/google/inject/spi/InjectionPoint, method=forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/AnnotatedType;[[Ljava/lang/annotation/Annotation;Ljava/util/function/Predicate;)Lcom/google/common/collect/ImmutableList;, pc=905
               Exception Details:
                 Location:
                   com/google/inject/spi/InjectionPoint.forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/AnnotatedType;[[Ljava/lang/annotation/Annotation;Ljava/util/function/Predicate;)Lcom/google/common/collect/ImmutableList; @905: JBgoto
                 Reason:
                   Current frame's stack size doesn't match stackmap.
                 Current Frame:
                   bci: @905
                   flags: { }
                   locals: { 'com/google/inject/spi/InjectionPoint', 'com/google/inject/internal/Errors', 'java/lang/reflect/Member', 'java/util/Iterator', '[Ljava/lang/reflect/AnnotatedType;', '[[Ljava/lang/annotation/Annotation;', 'java/util/function/Predicate', integer, integer, 'java/util/ArrayList', 'java/lang/reflect/AnnotatedType', 'com/google/inject/TypeLiteral', integer, '[Ljava/lang/annotation/Annotation;', '[Ljava/lang/annotation/Annotation;', 'com/google/inject/Key', integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, top, integer, integer, integer, integer, integer, integer, integer, integer, integer }
                   stack: { }
                 Stackmap Frame (FallBack):
                   bci: @963
                   flags: { }
                   locals: { 'com/google/inject/spi/InjectionPoint', 'com/google/inject/internal/Errors', 'java/lang/reflect/Member', 'java/util/Iterator', '[Ljava/lang/reflect/AnnotatedType;', '[[Ljava/lang/annotation/Annotation;', 'java/util/function/Predicate', integer, integer, 'java/util/ArrayList', top, 'com/google/inject/TypeLiteral', integer, top, top, top, top, top, top, top, top, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, top, integer, integer, integer, integer, integer, integer, integer, integer, integer }
                   stack: { 'com/google/inject/ConfigurationException' }
                 Exception Handler Table:
                   bci [169, 722] => handler: 963
                   bci [169, 722] => handler: 1002

Failures (1):
  JUnit Vintage:InjectionPointTest:testConstructorInjectionPoint
    MethodSource [className = 'com.google.inject.spi.InjectionPointTest', methodName = 'testConstructorInjectionPoint', methodParameterTypes = '']
    => java.lang.VerifyError: JVMVRFY021 thrown object not throwable; class=com/google/inject/spi/InjectionPoint, method=forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/AnnotatedType;[[Ljava/lang/annotation/Annotation;Ljava/util/function/Predicate;)Lcom/google/common/collect/ImmutableList;, pc=905
Exception Details:
  Location:
    com/google/inject/spi/InjectionPoint.forMember(Lcom/google/inject/internal/Errors;Ljava/lang/reflect/Member;Lcom/google/inject/TypeLiteral;[Ljava/lang/reflect/AnnotatedType;[[Ljava/lang/annotation/Annotation;Ljava/util/function/Predicate;)Lcom/google/common/collect/ImmutableList; @905: JBgoto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @905
    flags: { }
    locals: { 'com/google/inject/spi/InjectionPoint', 'com/google/inject/internal/Errors', 'java/lang/reflect/Member', 'java/util/Iterator', '[Ljava/lang/reflect/AnnotatedType;', '[[Ljava/lang/annotation/Annotation;', 'java/util/function/Predicate', integer, integer, 'java/util/ArrayList', 'java/lang/reflect/AnnotatedType', 'com/google/inject/TypeLiteral', integer, '[Ljava/lang/annotation/Annotation;', '[Ljava/lang/annotation/Annotation;', 'com/google/inject/Key', integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, top, integer, integer, integer, integer, integer, integer, integer, integer, integer }
    stack: { }
  Stackmap Frame (FallBack): <-------- in a fallback status
    bci: @963
    flags: { }
    locals: { 'com/google/inject/spi/InjectionPoint', 'com/google/inject/internal/Errors', 'java/lang/reflect/Member', 'java/util/Iterator', '[Ljava/lang/reflect/AnnotatedType;', '[[Ljava/lang/annotation/Annotation;', 'java/util/function/Predicate', integer, integer, 'java/util/ArrayList', top, 'com/google/inject/TypeLiteral', integer, top, top, top, top, top, top, top, top, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, top, integer, integer, integer, integer, integer, integer, integer, integer, integer }
    stack: { 'com/google/inject/ConfigurationException' }
  Exception Handler Table:
    bci [169, 722] => handler: 963
    bci [169, 722] => handler: 1002
       com.google.inject.spi.InjectionPointTest.testConstructorInjectionPoint(InjectionPointTest.java:64)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:568)
       junit.framework.TestCase.runTest(TestCase.java:177)
       junit.framework.TestCase.runBare(TestCase.java:142)
       junit.framework.TestResult$1.protect(TestResult.java:122)
       junit.framework.TestResult.runProtected(TestResult.java:142)
       junit.framework.TestResult.run(TestResult.java:125)
       [...]

Test run finished after 504 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
...
```
which indicates the class (version <= 50) was verified with the older verifier (fallback). So it matches RI's output in the case of non-fallback by specifying `-Xverify:nofallback`:
```
jdk17_openj9/bin/java -Xverify:nofallback <-------
-jar ./junit-platform-console-standalone-1.8.2.jar -cp ./bug_file:./util:./test-classes:./classes:./guava-31.0.1-jre.jar:./javax.inject-1.jar:./failureaccess-1.0.1.jar -m com.google.inject.spi.InjectionPointTest#testConstructorInjectionPoint

Thanks for using JUnit! Support its development at https://junit.org/sponsoring

?
├─ JUnit Jupiter ?
└─ JUnit Vintage ?
   └─ InjectionPointTest ?
      └─ testConstructorInjectionPoint ? JVMVRFY021 thrown object not throwable; class=com/google/inject/spi/InjectionPoint, method=<init>(Lcom/google/inject/TypeLiteral;Ljava/lang/reflect/Field;Z)V, pc=51
               Exception Details:
                 Location:
                   com/google/inject/spi/InjectionPoint.<init>(Lcom/google/inject/TypeLiteral;Ljava/lang/reflect/Field;Z)V @51: JBastore3
                 Reason:
                   A stackmap frame is expected at branch target 71.
                 Exception Handler Table:
                   bci [52, 68] => handler: 71
                   bci [52, 68] => handler: 99

Failures (1):
  JUnit Vintage:InjectionPointTest:testConstructorInjectionPoint
    MethodSource [className = 'com.google.inject.spi.InjectionPointTest', methodName = 'testConstructorInjectionPoint', methodParameterTypes = '']
    => java.lang.VerifyError: JVMVRFY021 thrown object not throwable; class=com/google/inject/spi/InjectionPoint, method=<init>(Lcom/google/inject/TypeLiteral;Ljava/lang/reflect/Field;Z)V, pc=51
Exception Details:
  Location:
    com/google/inject/spi/InjectionPoint.<init>(Lcom/google/inject/TypeLiteral;Ljava/lang/reflect/Field;Z)V @51: JBastore3
  Reason:
    A stackmap frame is expected at branch target 71.
  Exception Handler Table:
    bci [52, 68] => handler: 71
    bci [52, 68] => handler: 99
       com.google.inject.spi.InjectionPointTest.testConstructorInjectionPoint(InjectionPointTest.java:64)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:568)
       junit.framework.TestCase.runTest(TestCase.java:177)
       junit.framework.TestCase.runBare(TestCase.java:142)
       junit.framework.TestResult$1.protect(TestResult.java:122)
       junit.framework.TestResult.runProtected(TestResult.java:142)
       junit.framework.TestResult.run(TestResult.java:125)
       [...]

Test run finished after 738 ms
[         3 containers found      ]
[         0 containers skipped    ]
[         3 containers started    ]
...
[         1 tests failed          ]
```

**Comment by ChengJin01** [comment]
Hi @lochnagarr, please specify `-Xverify:nofallback` to enable the current Verifier in OpenJ9 if you'd like to see the same error message as Hotspot.
