### ISSUE TITLE
testSCCacheManagement_win iterateSharedCacheFunction failed with dir null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15649]
This started occurring when the jenkins clients were updated to start using a cache named `jenkins`, rather than the default named cache. It occurs quite often in the nightly builds. Happens on any version of Java. The failure is in the test native code, but the actual reason for the failure isn't included in the output.

https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.functional_x86-64_windows_Nightly_testList_0/119
testSCCacheManagement_win_0
```
.Running  :testSharedCacheJvmtiAPI  (Test suite : TestOptionsDefault)
Command executed: '"F:/Users/jenkins/workspace/Test_openjdk18_j9_extended.functional_x86-64_windows_Nightly_testList_0/openjdkbinary/j2sdk-image//bin//java"   -Xshareclasses:destroyAll'
vvv STDOUT vvv

^^^ STDOUT ^^^
vvv STDERR vvv

Attempting to destroy all caches in cacheDir C:\Users\jenkins\AppData\Local\javasharedresources\

JVMSHRC241E Error: unable to delete shared class cache file
JVMSHRC336E Port layer error code = -100
JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_LOCAL SERVICE"
JVMSHRC429I Failed to remove older generation of shared class cache "jenkins"

^^^ STDERR ^^^
vvv STACK TRACE vvv
java.lang.Throwable
	at tests.sharedclasses.TestUtils.showOutput(TestUtils.java:786)
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:595)
	at tests.sharedclasses.options.TestSharedCacheJvmtiAPI.main(TestSharedCacheJvmtiAPI.java:63)
	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJvmtiAPI(TestOptionsBase.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at junit.textui.TestRunner.start(TestRunner.java:180)
	at junit.textui.TestRunner.main(TestRunner.java:138)
^^^ STACK TRACE ^^^
2nd last command executed: '"F:/Users/jenkins/workspace/Test_openjdk18_j9_extended.functional_x86-64_windows_Nightly_testList_0/openjdkbinary/j2sdk-image//bin//java"   -Xshareclasses:destroyAll'
vvv 2ND LAST STDOUT vvv

^^^ 2ND LAST STDOUT ^^^
vvv 2ND LAST STDERR vvv

Attempting to destroy all caches in cacheDir C:\Users\jenkins\AppData\Local\javasharedresources\

JVMSHRC241E Error: unable to delete shared class cache file
JVMSHRC336E Port layer error code = -100
JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_LOCAL SERVICE"
JVMSHRC429I Failed to remove older generation of shared class cache "jenkins"

^^^ 2ND LAST STDERR ^^^
iterateSharedCacheFunction failed with dir null
	Last command: "F:/Users/jenkins/workspace/Test_openjdk18_j9_extended.functional_x86-64_windows_Nightly_testList_0/openjdkbinary/j2sdk-image//bin//java"   -Xshareclasses:destroyAll
E
```

Seems to have started on the 18th.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly/312/
Build changes: https://github.com/eclipse-openj9/openj9/compare/2e4e8f96e41...50dc5e987b4

**Comment by pshipton** [comment]
Running a build that should print the native error. 
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/215/

**Comment by pshipton** [comment]
Info about the native error from the grinder.
```
15:01:45  .Running  :testSharedCacheJvmtiAPI  (Test suite : TestOptionsDefault)
15:01:45  	Error: 65   JVMTI_ERROR_INVALID_TYPESTATE
15:01:45  		Field layer of jvmtiSharedCacheInfo is wrong when passing COM_IBM_ITERATE_SHARED_CACHES_VERSION_5 to iterateSharedCacheFunction 
15:01:45  
15:01:45  		Location: null -> [null():0]
15:01:45  
15:01:45  	Error: 65   JVMTI_ERROR_INVALID_TYPESTATE
15:01:45  		Field layer of jvmtiSharedCacheInfo is wrong when passing COM_IBM_ITERATE_SHARED_CACHES_VERSION_5 to iterateSharedCacheFunction 
15:01:45  
15:01:45  		Location: null -> [null():0]
15:01:45  	Error: 113   JVMTI_ERROR_INTERNAL
15:01:45  		iterateSharedCacheFunction: iteration of shared caches failed when passing in COM_IBM_ITERATE_SHARED_CACHES_VERSION_5
15:01:45  
15:01:45  		Location: null -> [null():0]
```

**Comment by pshipton** [comment]
Found the following shared caches
```
-rwx------+ 1 jenkins None 314572800 Aug  3 13:58 'C290M11F1A64P_sharedcc_LOCAL SERVICE_G43L00'
-rwx------+ 1 jenkins None 314572800 Aug 17  2019 'C290M14F1A64P_sharedcc_LOCAL SERVICE_G39'
-rwx------+ 1 jenkins None 314572800 Jul  6 02:54 'C290M20F1A64P_sharedcc_LOCAL SERVICE_G43L00'
-rwx------+ 1 jenkins None 314572800 Jul 23 01:25  C290M4F1A64P_jenkins_G35
```

**Comment by hangshao0** [comment]
Seems that the old caches that do not have "layer" are causing the test to fail.

**Comment by pshipton** [comment]
Yes, I created https://github.com/pshipton/openj9/commit/79f24732acc8475af06053b7ddc659a3196c451a and testing it now.
