### ISSUE TITLE
OpenJDK java/util/concurrent/ConcurrentHashMap/ToArray.java timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15641]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Nightly/113
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/concurrent/ConcurrentHashMap/ToArray.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Nightly/113/openjdk_test_output.tar.gz

```
22:20:17  ACTION: main -- Error. Agent error: java.lang.Exception: Agent 4 timed out with a timeout of 960 seconds; check console log for any additional details
22:20:17  REASON: Assumed action based on file name: run main ToArray 
22:20:17  TIME:   963.935 seconds
22:20:17  messages:
22:20:17  command: main ToArray
22:20:17  reason: Assumed action based on file name: run main ToArray 
22:20:17  Mode: agentvm
22:20:17  Agent id: 4
22:20:17  Timeout refired 960 times
22:20:17  Timeout information:
22:20:17  Running jcmd on process 1605297
22:20:17  Dump written to /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16589719132679/jdk_util_0/work/scratch/0/core.20220728.020742.1605297.0001.dmp
22:20:17  Dump written to /home/jenkins/workspace/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16589719132679/jdk_util_0/work/scratch/0/javacore.20220728.020744.1605297.0002.txt
22:20:17  Running jstack on process 1605297
22:20:17  2022-07-28T02:07:45.508349491
22:20:17  Virtual machine: 1605297 JVM information:
22:20:17  JRE 18 Linux s390x-64-Bit Compressed References 20220727_125 (JIT enabled, AOT enabled)
22:20:17  OpenJ9   - d47d53ff767
22:20:17  OMR      - a7dd4af88d9
22:20:17  JCL      - 0c89bcfb329 based on jdk-18.0.2+9
22:20:17  
22:20:17  "main" prio=5 Id=1 WAITING
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Object.java:219)
22:20:17  	at java.base@18.0.2-internal/java.lang.Thread.join(Thread.java:784)
22:20:17  	at java.base@18.0.2-internal/java.lang.Thread.join(Thread.java:739)
22:20:17  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:198)
22:20:17  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
22:20:17  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
22:20:17  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
22:20:17  
22:20:17  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
22:20:17  
22:20:17  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
22:20:17  
22:20:17  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
22:20:17  
22:20:17  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
22:20:17  
22:20:17  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
22:20:17  
22:20:17  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
22:20:17  
22:20:17  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
22:20:17  
22:20:17  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
22:20:17  
22:20:17  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
22:20:17  
22:20:17  "IProfiler" prio=5 Id=12 RUNNABLE
22:20:17  
22:20:17  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Object.java:219)
22:20:17  	at java.base@18.0.2-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
22:20:17  	at java.base@18.0.2-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
22:20:17  	at java.base@18.0.2-internal/java.lang.Thread.run(Thread.java:857)
22:20:17  	at java.base@18.0.2-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
22:20:17  
22:20:17  "Finalizer thread" prio=5 Id=13 RUNNABLE
22:20:17  
22:20:17  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
22:20:17  
22:20:17  "GC Worker" prio=5 Id=15 RUNNABLE
22:20:17  
22:20:17  "GC Worker" prio=5 Id=16 RUNNABLE
22:20:17  
22:20:17  "GC Worker" prio=5 Id=17 RUNNABLE
22:20:17  
22:20:17  "Attach API wait loop" prio=10 Id=20 RUNNABLE
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
22:20:17  
22:20:17  "pool-1-thread-1" prio=5 Id=21 TIMED_WAITING
22:20:17  	at java.base@18.0.2-internal/jdk.internal.misc.Unsafe.park(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
22:20:17  	at java.base@18.0.2-internal/java.lang.Thread.run(Thread.java:857)
22:20:17  
22:20:17  "ClassByNameCache Reaper" prio=5 Id=26 WAITING
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Object.java:219)
22:20:17  	at java.base@18.0.2-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
22:20:17  	at java.base@18.0.2-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:109)
22:20:17  	at java.base@18.0.2-internal/java.io.ClassByNameCache$Reaper.run(ClassByNameCache.java:232)
22:20:17  	at java.base@18.0.2-internal/java.lang.Thread.run(Thread.java:857)
22:20:17  
22:20:17  "ForkJoinPool.commonPool-worker-1" prio=5 Id=88 WAITING
22:20:17  	at java.base@18.0.2-internal/jdk.internal.misc.Unsafe.park(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
22:20:17  
22:20:17  "ForkJoinPool.commonPool-worker-2" prio=5 Id=89 WAITING
22:20:17  	at java.base@18.0.2-internal/jdk.internal.misc.Unsafe.park(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
22:20:17  
22:20:17  "ForkJoinPool.commonPool-worker-3" prio=5 Id=90 RUNNABLE
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ConcurrentHashMap$Traverser.advance(ConcurrentHashMap.java:3364)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3463)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ConcurrentHashMap$CollectionView.toArray(ConcurrentHashMap.java:4463)
22:20:17  	at ToArray$1.run(ToArray.java:80)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
22:20:17  
22:20:17  "AgentVMThread" prio=5 Id=660 WAITING
22:20:17  	at java.base@18.0.2-internal/jdk.internal.misc.Unsafe.park(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
22:20:17  	at java.base@18.0.2-internal/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
22:20:17  	at java.base@18.0.2-internal/java.util.ArrayList.forEach(ArrayList.java:1511)
22:20:17  	at ToArray.executeTest(ToArray.java:98)
22:20:17  	at ToArray.main(ToArray.java:44)
22:20:17  	at java.base@18.0.2-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:20:17  	at java.base@18.0.2-internal/java.lang.reflect.Method.invoke(Method.java:577)
22:20:17  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
22:20:17  	at java.base@18.0.2-internal/java.lang.Thread.run(Thread.java:857)
22:20:17  
22:20:17  "file lock watchdog" prio=10 Id=662 TIMED_WAITING
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Native Method)
22:20:17  	at java.base@18.0.2-internal/java.lang.Object.wait(Object.java:219)
22:20:17  	at java.base@18.0.2-internal/java.util.TimerThread.mainLoop(Timer.java:563)
22:20:17  	at java.base@18.0.2-internal/java.util.TimerThread.run(Timer.java:516)
22:20:17  
22:20:17  "Attachment portNumber: 35799" prio=10 Id=664 RUNNABLE
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
22:20:17  	at java.base@18.0.2-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
22:20:17  
22:20:17  
22:20:17  --- Timeout information end.
22:20:17  elapsed time (seconds): 963.935
```

Javacore seems to show it's stuck in compiled code
```
3XMTHREADINFO      "ForkJoinPool.commonPool-worker-3" J9VMThread:0x0000000000933900, omrthread_t:0x000003FEF01769D8, java/lang/Thread:0x000000000D450EB0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x5A, isDaemon:true)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x000000000CBE7C70)
3XMTHREADINFO1            (native thread ID:0x18832B, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000001)
3XMTHREADINFO2            (native stack address range from:0x000003FF7DFC0000, to:0x000003FF7E000000, size:0x40000)
3XMCPUTIME               CPU usage total: 935.077938787 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=26340400 (0x191EC30)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/util/concurrent/ConcurrentHashMap$Traverser.advance(ConcurrentHashMap.java:3383(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3463(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ConcurrentHashMap$CollectionView.toArray(ConcurrentHashMap.java:4463(Compiled Code))
4XESTACKTRACE                at ToArray$1.run(ToArray.java:80(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
4XESTACKTRACE                at java/util/concurrent/CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
4XESTACKTRACE                at java/util/concurrent/ForkJoinTask.doExec(ForkJoinTask.java:373(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool.scan(ForkJoinPool.java:1655(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool.runWorker(ForkJoinPool.java:1622)
4XESTACKTRACE                at java/util/concurrent/ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by pshipton** [comment]
@0xdaryl there is a core file, is it worth anyone taking a look?

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/663
jdk_concurrent_1
java/util/concurrent/ConcurrentHashMap/ToArray.java
```
23:00:59  "ForkJoinPool.commonPool-worker-0" Id=159 RUNNABLE
23:00:59  	at java.util.concurrent.ConcurrentHashMap$Traverser.advance(ConcurrentHashMap.java:3337)
23:00:59  	at java.util.concurrent.ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3417)
23:00:59  	at java.util.concurrent.ConcurrentHashMap$CollectionView.toArray(ConcurrentHashMap.java:4415)
23:00:59  	at ToArray$1.run(ToArray.java:78)
23:00:59  	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
23:00:59  	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
23:00:59  	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
23:00:59  	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
23:00:59  	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
23:00:59  	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```
