### ISSUE TITLE
JDK8 jdk_security3_0_FAILED Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: 0xCE534351

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15663]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/75/)(`rhel9x86-rt3-1`):
```
openjdk version "1.8.0_345"
IBM Semeru Runtime Open Edition (build 1.8.0_345-b01)
Eclipse OpenJ9 VM (build openj9-0.33.0-rc1a, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220804_442 (JIT enabled, AOT enabled)
OpenJ9   - 04a55b45b
OMR      - b58aa2708
JCL      - a0f6d36aea based on jdk8u345-b01)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F442%2Fibm-semeru-open-debugimage_x64_linux_8u341b01_openj9-0.33.0-rc1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F442%2Fibm-semeru-open-jdk_x64_linux_8u341b01_openj9-0.33.0-rc1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F442%2Fibm-semeru-open-testimage_x64_linux_8u341b01_openj9-0.33.0-rc1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F442%2Fibm-semeru-open-jre_x64_linux_8u341b01_openj9-0.33.0-rc1a.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.3-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&RELEASE_TAG=v0.33.0-release&OPENJ9_BRANCH=v0.33.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.33.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-08-04T03:13:32.899Z] variation: Mode150
[2022-08-04T03:13:32.899Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-08-04T03:20:47.852Z] TEST: sun/security/pkcs11/Cipher/CancelMultipart.java

[2022-08-04T03:20:47.853Z] STDERR:
[2022-08-04T03:20:47.853Z] java.lang.reflect.InvocationTargetException
[2022-08-04T03:20:47.853Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-08-04T03:20:47.853Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2022-08-04T03:20:47.853Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-08-04T03:20:47.853Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2022-08-04T03:20:47.853Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:108)
[2022-08-04T03:20:47.853Z] 	at PKCS11Test.testNSS(PKCS11Test.java:486)
[2022-08-04T03:20:47.853Z] 	at PKCS11Test.main(PKCS11Test.java:156)
[2022-08-04T03:20:47.853Z] 	at CancelMultipart.main(CancelMultipart.java:113)
[2022-08-04T03:20:47.853Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-08-04T03:20:47.853Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-08-04T03:20:47.853Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-08-04T03:20:47.853Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-08-04T03:20:47.853Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-08-04T03:20:47.853Z] 	at java.lang.Thread.run(Thread.java:827)
[2022-08-04T03:20:47.853Z] Caused by: java.security.ProviderException: Initialization failed
[2022-08-04T03:20:47.853Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:376)
[2022-08-04T03:20:47.853Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
[2022-08-04T03:20:47.853Z] 	... 14 more
[2022-08-04T03:20:47.853Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: 0xCE534351
[2022-08-04T03:20:47.853Z] 	at sun.security.pkcs11.wrapper.PKCS11.C_Initialize(Native Method)
[2022-08-04T03:20:47.853Z] 	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Initialize(PKCS11.java:1627)
[2022-08-04T03:20:47.853Z] 	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:163)
[2022-08-04T03:20:47.853Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:330)
[2022-08-04T03:20:47.853Z] 	... 15 more

....

[2022-08-04T03:50:26.553Z] Test results: passed: 542; failed: 60
[2022-08-04T03:50:26.553Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2022-08-04T03:50:26.553Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_1659578151249/jdk_security3_0/work
[2022-08-04T03:50:26.553Z] Error: Some tests failed or other problems occurred.
[2022-08-04T03:50:26.553Z] 
[2022-08-04T03:50:26.553Z] jdk_security3_0_FAILED
```

[15x internal grinder - jdk_security3_0](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26496/)

**Comment by pshipton** [comment]
This seems like a machine problem.

**Comment by pshipton** [comment]
In the grinder 4 machines passed (cent7x64-1-9, ub18x64rt1-9, ub20x64rt1-4, cent7x64-1-5), one failed rhel9x86-rt1-1. The original failures were on rhel9x86-rt3-1. Maybe related to rhel9?

Seem to be https://bugs.openjdk.org/browse/JDK-8282538 which is fixed in Java 11.0.17+1, 17.0.5+1, 19, i.e. the next set of releases. We have 17.0.5+1 already, but 11.0.17+1 is blocked on https://github.com/eclipse-openj9/openj9/issues/15664

**Comment by JasonFengJ9** [comment]
[A similar internal failure](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_s390x_linux/82/consoleFull) (`rhel9s390xrt-2`) - another `rhel9`

```
openjdk version "1.8.0_352"
IBM Semeru Runtime Open Edition (build 1.8.0_352-b01)
Eclipse OpenJ9 VM (build master-1719d2e01, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20220826_434 (JIT enabled, AOT enabled)
OpenJ9   - 1719d2e01
OMR      - 938f0686f
JCL      - f2a9dfa9c based on jdk8u352-b01)

[2022-08-28T13:13:59.148Z] variation: Mode150
[2022-08-28T13:13:59.148Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-08-28T13:52:52.573Z] TEST: sun/security/tools/keytool/autotest.sh

[2022-08-28T13:52:52.573Z] ERR is:
[2022-08-28T13:52:52.573Z] 
[2022-08-28T13:52:52.573Z] OUT is:
[2022-08-28T13:52:52.573Z] keytool error: java.io.IOException: load failed
[2022-08-28T13:52:52.573Z] 
[2022-08-28T13:52:52.573Z] Exception in thread "main" java.io.IOException: load failed
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:764)
[2022-08-28T13:52:52.573Z] 	at java.security.KeyStore.load(KeyStore.java:1445)
[2022-08-28T13:52:52.573Z] 	at sun.security.tools.keytool.Main.doCommands(Main.java:869)
[2022-08-28T13:52:52.573Z] 	at sun.security.tools.keytool.Main.run(Main.java:378)
[2022-08-28T13:52:52.573Z] 	at sun.security.tools.keytool.Main.main(Main.java:371)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.test(KeyToolTest.java:159)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.test(KeyToolTest.java:127)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.testOK(KeyToolTest.java:182)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.testPKCS11(KeyToolTest.java:525)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.main(KeyToolTest.java:1345)
[2022-08-28T13:52:52.573Z] Caused by: javax.security.auth.login.LoginException
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1466)
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:864)
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:751)
[2022-08-28T13:52:52.573Z] 	... 9 more
[2022-08-28T13:52:52.573Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_TYPE_INVALID
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.wrapper.PKCS11.C_Login(Native Method)
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1450)
[2022-08-28T13:52:52.573Z] 	... 11 more

[2022-08-28T13:52:52.574Z] TEST RESULT: Failed. Execution failed: exit code 1
[2022-08-28T13:52:52.574Z] --------------------------------------------------
[2022-08-28T13:58:35.640Z] Test results: passed: 601; failed: 1
[2022-08-28T13:58:35.640Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16616889022357/jdk_security3_0/report/html/report.html
[2022-08-28T13:58:35.640Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16616889022357/jdk_security3_0/work
[2022-08-28T13:58:35.640Z] Error: Some tests failed or other problems occurred.
[2022-08-28T13:58:35.640Z] 
[2022-08-28T13:58:35.640Z] jdk_security3_0_FAILED
```

**Comment by pshipton** [comment]
We probably need to backport https://bugs.openjdk.org/browse/JDK-8282538 to jdk8.

**Comment by pshipton** [comment]
Seems it should already be backported via https://bugs.openjdk.org/browse/JDK-8290076, but we don't have this change as of 8u352+4

**Comment by pshipton** [comment]
The change is actually in jdk8u352-b01, but this is the build that failed. We should try again on the latest (b05) to see if it's still failing.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/612208ee2ba

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/issues/15902 for https://github.com/eclipse-openj9/openj9/issues/15663#issuecomment-1232188736, closing this one as resolved.

**Comment by JasonFengJ9** [comment]
[JDK8 x86-64_linux 0.41 milestone 1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/148/)(`rhel9x86-svl-rt5-1`)
```
openjdk version "1.8.0_392"
IBM Semeru Runtime Open Edition (build 1.8.0_392-b03)
Eclipse OpenJ9 VM (build v0.41.0-release-87d042a68, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230906_749 (JIT enabled, AOT enabled)
OpenJ9   - 87d042a68
OMR      - fa7b6ddc7
JCL      - 04ddaa8f70 based on jdk8u392-b03)

[2023-09-06T20:49:57.497Z] variation: Mode150
[2023-09-06T20:49:57.497Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-09-06T21:00:47.712Z] TEST: sun/security/pkcs11/Provider/Login.sh

[2023-09-06T21:00:47.712Z] Exception in thread "main" java.lang.reflect.InvocationTargetException
[2023-09-06T21:00:47.712Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2023-09-06T21:00:47.712Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2023-09-06T21:00:47.712Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2023-09-06T21:00:47.712Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2023-09-06T21:00:47.712Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:108)
[2023-09-06T21:00:47.712Z] 	at PKCS11Test.testNSS(PKCS11Test.java:486)
[2023-09-06T21:00:47.712Z] 	at PKCS11Test.main(PKCS11Test.java:156)
[2023-09-06T21:00:47.712Z] 	at PKCS11Test.main(PKCS11Test.java:137)
[2023-09-06T21:00:47.712Z] 	at Login.main(Login.java:39)
[2023-09-06T21:00:47.712Z] Caused by: java.security.ProviderException: Initialization failed
[2023-09-06T21:00:47.712Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:427)
[2023-09-06T21:00:47.712Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:131)
[2023-09-06T21:00:47.712Z] 	... 9 more
[2023-09-06T21:00:47.712Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: 0xCE534351
[2023-09-06T21:00:47.712Z] 	at sun.security.pkcs11.wrapper.PKCS11.C_Initialize(Native Method)
[2023-09-06T21:00:47.712Z] 	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Initialize(PKCS11.java:1693)
[2023-09-06T21:00:47.712Z] 	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:229)
[2023-09-06T21:00:47.712Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:358)
[2023-09-06T21:00:47.712Z] 	... 10 more

[2023-09-06T21:40:06.631Z] jdk_security3_0_FAILED
```
[50x jdk_security3_0 internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34798/)

**Comment by pshipton** [comment]
Failing on rhel9, the grinder failed on rhel9x86-svl-rt4-1. Not an OpenJ9 issue, either JCL or machine setup.

**Comment by JasonFengJ9** [comment]
[JDK8 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_ppc64le_linux_testList_0/11/)(`rhel9lert-2`)
```
openjdk version "1.8.0_412"
IBM Semeru Runtime Open Edition (build 1.8.0_412-b06)
Eclipse OpenJ9 VM (build v0.44.0-release-218cf6016, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20240321_874 (JIT enabled, AOT enabled)
OpenJ9   - 218cf6016
OMR      - 254af5a04
JCL      - 27b33e9312 based on jdk8u412-b06)

[2024-03-21T21:20:18.096Z] variation: Mode150
[2024-03-21T21:20:18.096Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-21T21:25:39.812Z] TEST: sun/security/pkcs11/Provider/Login.sh

[2024-03-21T21:25:39.812Z] STDERR:
[2024-03-21T21:25:39.812Z] Note: /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64le_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/jdk/test/sun/security/pkcs11/Provider/Login.java uses or overrides a deprecated API.
[2024-03-21T21:25:39.812Z] Note: Recompile with -Xlint:deprecation for details.
[2024-03-21T21:25:39.812Z] Note: /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64le_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/jdk/test/sun/security/pkcs11/Provider/../PKCS11Test.java uses unchecked or unsafe operations.
[2024-03-21T21:25:39.812Z] Note: Recompile with -Xlint:unchecked for details.
[2024-03-21T21:25:39.812Z] Exception in thread "main" java.lang.reflect.InvocationTargetException
[2024-03-21T21:25:39.812Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-03-21T21:25:39.812Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-03-21T21:25:39.812Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-03-21T21:25:39.812Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2024-03-21T21:25:39.812Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:108)
[2024-03-21T21:25:39.812Z] 	at PKCS11Test.testNSS(PKCS11Test.java:486)
[2024-03-21T21:25:39.812Z] 	at PKCS11Test.main(PKCS11Test.java:156)
[2024-03-21T21:25:39.812Z] 	at PKCS11Test.main(PKCS11Test.java:137)
[2024-03-21T21:25:39.812Z] 	at Login.main(Login.java:39)
[2024-03-21T21:25:39.812Z] Caused by: java.security.ProviderException: Initialization failed
[2024-03-21T21:25:39.812Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:427)
[2024-03-21T21:25:39.812Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:131)
[2024-03-21T21:25:39.812Z] 	... 9 more
[2024-03-21T21:25:39.812Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: 0xCE534351
[2024-03-21T21:25:39.812Z] 	at sun.security.pkcs11.wrapper.PKCS11.C_Initialize(Native Method)
[2024-03-21T21:25:39.812Z] 	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Initialize(PKCS11.java:1693)
[2024-03-21T21:25:39.812Z] 	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:229)
[2024-03-21T21:25:39.812Z] 	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:358)
[2024-03-21T21:25:39.812Z] 	... 10 more

[2024-03-21T21:25:39.813Z] TEST RESULT: Failed. Execution failed: exit code 1

[2024-03-21T21:42:02.337Z] jdk_security3_0_FAILED
```

**Comment by pshipton** [comment]
@jasonkatonica fyi

**Comment by taoliult** [comment]
At line 486 of PKCS11Test.java, as below:

`[2024-03-21T21:25:39.812Z] 	at PKCS11Test.testNSS(PKCS11Test.java:486)`

```
        String customConfig = System.getProperty("CUSTOM_P11_CONFIG");
        String customConfigName = System.getProperty("CUSTOM_P11_CONFIG_NAME", "p11-nss.txt");
        String p11config = (customConfig != null) ?
                                customConfig :
                                base + SEP + "nss" + SEP + customConfigName;

        System.setProperty("pkcs11test.nss.lib", libfile);
        System.setProperty("pkcs11test.nss.db", dbdir);
        Provider p = getSunPKCS11(p11config);                --- Line 486
```

It tried to initialize the SunPKCS11 using the configure file. If the test failed during FIPS testing, that is expected, because in FIPS mode, SunPKCS11 will be initialized using the FIPS nss.fips.cfg. And it can't be initialized again in the tests. So, the Initialization failed will happen.

If the test failed but not in FIPS testing, does this failure happens all the time, or failed intermittently?

**Comment by pshipton** [comment]
non-FIPS testing. The most recent failure is in a test run that doesn't have any TEST_FLAG set. It's likely intermittent or specific to a machine. @JasonFengJ9 pls run a grinder.

**Comment by JasonFengJ9** [comment]
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39363/)

Passed at `ubu20le-rtp-rt7-1`, `sles15le-svl-rt5-1`, and `sles15le-svl-rt8-1`.
Failed at `rhel8le-svl-rt7-1` and `cent8le-rtp-rt3-1` with a known failure
* https://github.com/eclipse-openj9/openj9/issues/16371

The original error `PKCS11Exception: 0xCE534351` wasn't reproduced.

**Comment by taoliult** [comment]
@JasonFengJ9 Can we close this issue since the latest update said `The original error PKCS11Exception: 0xCE534351 wasn't reproduced`.

**Comment by JasonFengJ9** [comment]
Sure
