### ISSUE TITLE
jdk11 OpenJDK com.sun.javatest.regtest.tool.Version.<init> IllegalArgumentException: 6+1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15664]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK11-Acceptance/47/
This is the acceptance build for 11.0.17+1.
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/fad632c8...b7da914b0a3
All OpenJDK suites are getting the following error, on all platforms but Windows.
```
08:46:24  { itercnt=1; \
08:46:24  	mkdir -p "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../TKG/output_16596171827634/jdk_lang_1"; \
08:46:24  	cd "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../TKG/output_16596171827634/jdk_lang_1"; \
08:46:24  	"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/openjdkbinary/j2sdk-image/bin/java" -Xmx512m -jar "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
08:46:24  	-agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:4  -nativepath:"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/openjdkbinary/openjdk-test-image/jdk/jtreg/native" -vmoptions:"-Xmx512m  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops  " \
08:46:24  	-timeoutHandler:jtreg.openj9.CoreDumpTimeoutHandler -timeoutHandlerDir:"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../TKG/lib/openj9jtregtimeouthandler.jar" \
08:46:24  	-w ""/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../TKG/output_16596171827634/jdk_lang_1"/work" \
08:46:24  	-r ""/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../TKG/output_16596171827634/jdk_lang_1"/report" \
08:46:24  	-jdk:"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/openjdkbinary/j2sdk-image" \
08:46:24  	-exclude:"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../openjdk/openjdk-jdk/test/jdk/ProblemList.txt" \
08:46:24  	-exclude:"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../../jvmtest/openjdk/excludes/ProblemList_openjdk11-openj9.txt" \
08:46:24  	 \
08:46:24  	 \
08:46:24  	"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../openjdk/openjdk-jdk/test/jdk:jdk_lang"; \
08:46:24  	if [ $? -eq 0 ] ; then echo ""; echo "jdk_lang_1""_PASSED"; echo ""; cd /Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/..;  else echo ""; echo "jdk_lang_1""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OpenJDK11/aqa-tests/TKG/../TKG/output_16596171827634/TestTargetResult";
08:46:24  Error: Unexpected exception occurred! java.lang.IllegalArgumentException: 6+1
08:46:24  java.lang.IllegalArgumentException: 6+1
08:46:24  	at com.sun.javatest.regtest.tool.Version.<init>(Version.java:80)
08:46:24  	at com.sun.javatest.regtest.config.TestProperties$Cache$Entry.initAllowSmartActionArgs(TestProperties.java:452)
08:46:24  	at com.sun.javatest.regtest.config.TestProperties$Cache$Entry.<init>(TestProperties.java:262)
08:46:24  	at com.sun.javatest.regtest.config.TestProperties$Cache.getEntryInternal(TestProperties.java:509)
08:46:24  	at com.sun.javatest.regtest.config.TestProperties$Cache.getEntry(TestProperties.java:500)
08:46:24  	at com.sun.javatest.regtest.config.TestProperties.<init>(TestProperties.java:57)
08:46:24  	at com.sun.javatest.regtest.config.RegressionTestSuite.<init>(RegressionTestSuite.java:80)
08:46:24  	at com.sun.javatest.regtest.config.RegressionTestSuite.open(RegressionTestSuite.java:65)
08:46:24  	at com.sun.javatest.regtest.config.TestManager.getTestSuites(TestManager.java:165)
08:46:24  	at com.sun.javatest.regtest.tool.Tool.run(Tool.java:1124)
08:46:24  	at com.sun.javatest.regtest.tool.Tool.run(Tool.java:1075)
08:46:24  	at com.sun.javatest.regtest.tool.Tool.main(Tool.java:147)
08:46:24  	at com.sun.javatest.regtest.Main.main(Main.java:58)
```

**Comment by pshipton** [comment]
@llxia fyi

**Comment by pshipton** [comment]
Seems related to https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/d28af11ed

**Comment by llxia** [comment]
For JDK11, we are using jtreg_5_1_b01
```
08:55:13  getDependentLibs:
08:55:13       [exec] --------------------------------------------
08:55:13       [exec] path is set to /home/****/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OpenJDK11/aqa-tests/TKG/../TKG/lib
08:55:13       [exec] task is set to default
08:55:13       [exec] dependencyList is set to jtreg_5_1_b01,tohandler_simple
08:55:13       [exec] --------------------------------------------
08:55:13       [exec] Starting download third party dependent jars
08:55:13       [exec] --------------------------------------------
08:55:13       [exec] downloading dependent third party jars to /home/****/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OpenJDK11/aqa-tests/TKG/../TKG/lib
08:55:13       [exec] /home/****/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OpenJDK11/aqa-tests/TKG/../TKG/lib/jtreg_5_1_b01.tar.gz exists with correct hash, not downloading
```
