### ISSUE TITLE
security/signature failures - Failed to detect that the JAR file is signed, Null certificate, etc.

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15743]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/348/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly/232/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_Nightly/351/
The failures are not mode specific (fail in both/all modes):
java/util/jar/JarFile/ScanSignedJar.java.ScanSignedJar
```
20:54:26  java.lang.Exception: Failed to detect that the JAR file is signed
20:54:26  	at ScanSignedJar.main(ScanSignedJar.java:63)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:54:26  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:54:26  	at java.lang.reflect.Method.invoke(Method.java:498)
20:54:26  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:54:26  	at java.lang.Thread.run(Thread.java:826)
```
java/util/jar/JarFile/TurkCert.java.TurkCert
```
20:54:26  java.lang.Exception: Null certificate for test.class.
20:54:26  	at TurkCert.main(TurkCert.java:50)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:54:26  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:54:26  	at java.lang.reflect.Method.invoke(Method.java:498)
20:54:26  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:54:26  	at java.lang.Thread.run(Thread.java:826)
```
java/util/jar/JarInputStream/ExtraFileInMetaInf.java.ExtraFileInMetaInf
```
20:54:26  java.lang.SecurityException: System.exit() forbidden by JT Harness
20:54:26  	at com.sun.javatest.regtest.agent.JavaTestSecurityManager.checkExit(JavaTestSecurityManager.java:116)
20:54:26  	at java.lang.Runtime.exit(Runtime.java:107)
20:54:26  	at java.lang.System.exit(System.java:390)
20:54:26  	at sun.security.tools.jarsigner.Main.run(Main.java:296)
20:54:26  	at sun.security.tools.jarsigner.Main.main(Main.java:132)
20:54:26  	at ExtraFileInMetaInf.main(ExtraFileInMetaInf.java:53)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:54:26  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:54:26  	at java.lang.reflect.Method.invoke(Method.java:498)
20:54:26  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:54:26  	at java.lang.Thread.run(Thread.java:826)
```
java/util/jar/JarInputStream/ScanSignedJar.java.ScanSignedJar
```
20:54:26  java.lang.Exception: Count.class should be signed
20:54:26  	at ScanSignedJar.main(ScanSignedJar.java:74)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:54:26  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:54:26  	at java.lang.reflect.Method.invoke(Method.java:498)
20:54:26  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:54:26  	at java.lang.Thread.run(Thread.java:826)
```
java/util/jar/JarInputStream/TestIndexedJarWithBadSignature.java.TestIndexedJarWithBadSignature
```
20:54:26  java.lang.RuntimeException: Test Failed:Security Exception not being thrown
20:54:26  	at TestIndexedJarWithBadSignature.main(TestIndexedJarWithBadSignature.java:49)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:54:26  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:54:26  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:54:26  	at java.lang.reflect.Method.invoke(Method.java:498)
20:54:26  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:54:26  	at java.lang.Thread.run(Thread.java:826)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_aarch64_linux_Nightly/231
SecurityTests_0
```
FAILED: testDefaultTls
...
Caused by: java.security.NoSuchAlgorithmException: X.509 CertificateFactory not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:183)
	... 47 more
```
Plus more.

Changes from the last working build:
https://github.com/eclipse-openj9/openj9/compare/39a41b8ef1c90e4...2e16a404036
https://github.com/eclipse-openj9/openj9-omr/compare/909848f97...5488b832d0a
https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/28c0ddeeca...b8a6f0d039d

**Comment by pshipton** [comment]
I expect this is caused by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/601

@WilburZjh I see there is a `map.clear();` on line 62 in SunEntries.java, which is likely the cause of the problem.

**Comment by WilburZjh** [comment]
> I expect this is caused by [ibmruntimes/openj9-openjdk-jdk8#601](https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/601)
> 
> @WilburZjh I see there is a `map.clear();` on line 62 in SunEntries.java, which is likely the cause of the problem.

I expect that the `map` should be cleared just as the `attrs` is cleared in JDK17.

**Comment by pshipton** [comment]
I don't think so. In jdk17 the attrs is populated and used to add services, the clears and used again to add more services. 
In jdk8 when you clear the map, everything added previously is removed, resulting in the failures seen in this issue. There is no map.clear() in the original jdk8 code.

**Comment by WilburZjh** [comment]
Removed the `map.clear()` from the `SunEntries.java` file in the [PR](https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/605).
