### ISSUE TITLE
aarch64 linux HeapHogLoadTest_5m Method "testMultiCatch" not found, Method "testMultiAndPrecise" not found

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15750]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_aarch64_linux_Nightly_testList_2/257/
HeapHogLoadTest_5m_1 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`
```
HHLT 20:27:40.136 - Completed 80.1%. Number of tests started=566473 (+43375)
HHLT 20:27:46.822 - First failure detected by thread: load-3. Not creating dumps as no dump generation is requested for this load test
HHLT 20:27:46.824 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/gc/heapHog.xml
HHLT 20:27:46.826 - suite.isCreateDump() : false
HHLT 20:27:46.831 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/gc/heapHog.xml
HHLT 20:27:46.831 - suite.isCreateDump() : false
HHLT 20:27:46.832 - Test failed. Details recorded in execution log.
HHLT 20:27:46.833 - Test failed
HHLT   Failure num.  = 1
HHLT   Test number   = 30
HHLT   Test details  = 'JUnit[net.adoptopenjdk.test.lang.java7.ProjectCoin.MultiCatchPreciseRethrow]'
HHLT   Suite number  = 0
HHLT   Thread number = 3
HHLT >>> Captured test output >>>
HHLT testStarted : testPreciseRethrow(net.adoptopenjdk.test.lang.java7.ProjectCoin.MultiCatchPreciseRethrow)
HHLT testFinished: testPreciseRethrow(net.adoptopenjdk.test.lang.java7.ProjectCoin.MultiCatchPreciseRethrow)
HHLT testStarted : testMultiCatch(net.adoptopenjdk.test.math.MathAPITest)
HHLT testFailure: testMultiCatch(net.adoptopenjdk.test.math.MathAPITest): Method "testMultiCatch" not found
HHLT junit.framework.AssertionFailedError: Method "testMultiCatch" not found
HHLT 	at junit.framework.Assert.fail(Assert.java:57)
HHLT 	at junit.framework.TestCase.fail(TestCase.java:227)
HHLT 	at junit.framework.TestCase.runTest(TestCase.java:169)
HHLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
HHLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
HHLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
HHLT 	at junit.framework.TestResult.run(TestResult.java:125)
HHLT 	at junit.framework.TestCase.run(TestCase.java:129)
HHLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
HHLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
HHLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
HHLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
HHLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
HHLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
HHLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
HHLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
HHLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
HHLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
HHLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
HHLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
HHLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
HHLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
HHLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
HHLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
HHLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
HHLT 	at java.base/java.lang.Thread.run(Thread.java:857)
HHLT testFinished: testMultiCatch(net.adoptopenjdk.test.math.MathAPITest)
HHLT testStarted : testMultiAndPrecise(net.adoptopenjdk.test.math.MathAPITest)
HHLT testFailure: testMultiAndPrecise(net.adoptopenjdk.test.math.MathAPITest): Method "testMultiAndPrecise" not found
HHLT junit.framework.AssertionFailedError: Method "testMultiAndPrecise" not found
HHLT 	at junit.framework.Assert.fail(Assert.java:57)
HHLT 	at junit.framework.TestCase.fail(TestCase.java:227)
HHLT 	at junit.framework.TestCase.runTest(TestCase.java:169)
HHLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
HHLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
HHLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
HHLT 	at junit.framework.TestResult.run(TestResult.java:125)
HHLT 	at junit.framework.TestCase.run(TestCase.java:129)
HHLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
HHLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
HHLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
HHLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
HHLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
HHLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
HHLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
HHLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
HHLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
HHLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
HHLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
HHLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
HHLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
HHLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
HHLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
HHLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
HHLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
HHLT 	at java.base/java.lang.Thread.run(Thread.java:857)
HHLT testFinished: testMultiAndPrecise(net.adoptopenjdk.test.math.MathAPITest)
```

**Comment by knn-k** [comment]
Related Issues:

- SEGV with HeapHogLoadTest_5m_0 on AIX and AArch64 macOS: #14713
- SEGV with HeapHogLoadTest_5m_1 on AArch64 macOS: https://github.com/eclipse-openj9/openj9/issues/15170#issuecomment-1238455760

**Comment by knn-k** [comment]
I ran HeapHogLoadTest_5m_1 with JDK 17 40 times on AArch64 Linux, and got no failures.
https://openj9-jenkins.osuosl.org/job/Grinder/1308/

**Comment by knn-k** [comment]
I ran HeapHogLoadTest_5m_1 with JDK 17 40 times on AArch64 Linux again, and got no failures.
https://openj9-jenkins.osuosl.org/job/Grinder/1639/

I think we can close this issue now.
