### ISSUE TITLE
Xdump Feature Request: Dump on Checkpoint / Restore

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#15771]
I've tried adding delay loops in the JIT checkpoint hook in order to generate a javacore. However, this either results in the process ending (after the javacore) or hanging; the outcome depends on if the hook thread has vmaccess or not.

It would be useful to have `checkpoint` and `restore` as events that we can specify to the `-Xdump` option so that the various files can be generated at a well defined point (e.g. ight before we call criu / right after criu has restored us).

**Comment by dsouzai** [comment]
fyi @tajila

**Comment by tajila** [comment]
FYI @keithc-ca

**Comment by keithc-ca** [comment]
Would `"-Xtrace:trigger=method{org/eclipse/openj9/criu/CRIUSupport.checkpointJVM,javadump,javadump}"` not do what you need? (Courtesy of [Xtrace Option Builder](https://www.eclipse.org/openj9/tools/xtrace_option_builder.html).)

**Comment by dsouzai** [comment]
I tried it out, but I see a similar error as when I would add a delay loop in the JIT checkpoint hook:

```
[root@fedora defaultServer]# cat jvm.options 
-Xshareclasses:enableBCI,name=liberty
-Xtrace:trigger=method{org/eclipse/openj9/criu/CRIUSupport.checkpointJVM,javadump,javadump}
```

output:
```
[root@fedora liberty]# numactl --physcpubind=0,1,2,3 --membind=0 /home/dsouzai/myWork/criu/tests/liberty/wlp/bin/server checkpoint defaultServer --at=applications -Dcom.ibm.ws.beta.edition=true

Launching defaultServer (Open Liberty 22.0.0.9/wlp-1.0.68.cl220920220809-1100) on Eclipse OpenJ9 VM, version 11.0.17-internal+0-adhoc..openj9-openjdk-jdk11 (en_CA)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/pingperf/
[AUDIT   ] CWWKZ0001I: Application pingperf started in 0.789 seconds.
[AUDIT   ] CWWKC0451I: A server checkpoint was requested. When the checkpoint completes, the server stops.
JVMDUMP034I User requested Java dump using '/home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/javacore.20220824.102646.337279.0001.txt' through -Xtrace:trigger
JVMDUMP010I Java dump written to /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/javacore.20220824.102646.337279.0001.txt
JVMDUMP034I User requested Java dump using '/home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/javacore.20220824.102647.337279.0002.txt' through -Xtrace:trigger
JVMDUMP010I Java dump written to /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/javacore.20220824.102647.337279.0002.txt
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[ERROR   ] CWWKC0453E: The server checkpoint request failed with the following message: Could not dump the JVM processs, err=-52
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKE0084I: The server defaultServer is stopping because thread Checkpoint failed, exiting... (0000003c) called the method java.lang.System.exit: 
	at java.base/java.lang.System.exit(System.java:485)
	at io.openliberty.checkpoint.internal.CheckpointImpl.lambda$checkpointOrExitOnFailure$1(CheckpointImpl.java:329)
	at java.base/java.lang.Thread.run(Thread.java:839)

TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-2.0, checkpoint-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, jsonp-1.1, servlet-4.0].
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/pingperf/
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 3.138 seconds.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKZ0009I: The application pingperf has stopped successfully.
TRAS3005E: Failed to write messages to the /home/dsouzai/myWork/criu/tests/liberty/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 3.888 seconds.
```

checkpoint.log:
```
Warn  (compel/src/lib/infect.c:127): Unable to interrupt task: 337335 (Operation not permitted)
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337292 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337301 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337303 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337304 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337308 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337309 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337310 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337311 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337313 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337315 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337316 with interrupted system call
Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 337317 with interrupted system call
Error (criu/sk-unix.c:864): unix: External socket is used. Consider using --ext-unix-sk option.
Error (criu/cr-dump.c:2053): Dumping FAILED.
```

**Comment by keithc-ca** [comment]
I see two apparently successful java dumps produced, although I wouldn't have expected to see the second until restore time.
Do those java dumps not give you the information you wanted? I'm not sure extra, more specific triggers will help.

**Comment by dsouzai** [comment]
There's a couple issues with the javacores as they are I would say:

1. They're produced before we enter all the various VM Hooks, so if we do work that we'd want to see in the javacore, there's no way to get that information (for example, if we're doing preemptive compilation or preemptive class loading). 
2. The java process doesn't successfully checkpoint after the javacore, which means the javacore isn't generated on the restore side, so again, if there's some additional work that we'd want to see reflected in the javacore, we're not going to see it.

**Comment by keithc-ca** [comment]
Did you try `"-Xtrace:trigger=tpnid{j9criu.7-8,javadump}"`? Those tracepoint ids correspond to `Trc_CRIU_before_checkpoint`, which occurs immediately before the call to `criu_dump()`, and `Trc_CRIU_after_checkpoint`, which occurs shortly after that.

**Comment by dsouzai** [comment]
Looks like the same problem:
```
Launching defaultServer (Open Liberty 22.0.0.9/wlp-1.0.68.cl220920220809-1100) on Eclipse OpenJ9 VM, version 11.0.17-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxcriuPersonal (en_CA)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/pingperf/
[AUDIT   ] CWWKZ0001I: Application pingperf started in 1.300 seconds.
[AUDIT   ] CWWKC0451I: A server checkpoint was requested. When the checkpoint completes, the server stops.
JVMDUMP034I User requested Java dump using '/opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/javacore.20220824.155128.13006.0001.txt' through -Xtrace:trigger
JVMDUMP010I Java dump written to /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/javacore.20220824.155128.13006.0001.txt
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[ERROR   ] CWWKC0453E: The server checkpoint request failed with the following message: Could not dump the JVM processs, err=-52
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKE0084I: The server defaultServer is stopping because thread Checkpoint failed, exiting... (0000003c) called the method java.lang.System.exit:
        at java.base/java.lang.System.exit(System.java:485)
        at io.openliberty.checkpoint.internal.CheckpointImpl.lambda$checkpointOrExitOnFailure$1(CheckpointImpl.java:329)
        at java.base/java.lang.Thread.run(Thread.java:839)

TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/pingperf/
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKF0012I: The server installed the following features: [cdi-2.0, checkpoint-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, jsonp-1.1, servlet-4.0].
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 12.840 seconds.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKZ0009I: The application pingperf has stopped successfully.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 13.591 seconds.
TRAS3005E: Failed to write messages to the /opt/IBM/openliberty-all-22.0.0.9-cl220920220809-1100/wlp/usr/servers/defaultServer/logs/messages.log file.
```

**Comment by keithc-ca** [comment]
Adding a new place to trigger a javadump, either immediately before or immediately after `j9criu.7` is unlikely to change much. I think we need to understand what's failing before deciding whether new dump events would be helpful.

**Comment by dsouzai** [comment]
Yeah that's sounds good to me, as long as there's a way to successfully generate a javacore on checkpoint/restore without the process ending, doesn't matter if it's using existing -Xtrace options or a new dump event.

**Comment by dsouzai** [comment]
Opened https://github.com/eclipse-openj9/openj9/issues/15776
