### ISSUE TITLE
Initialization error for library j9gc29(2): Failed to instantiate heap.  41306M requested

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15809]
Something is wrong with these machines. They don't have enough memory or swap space.

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/301/ - [win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1)
```
21:31:11  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  35298M requested
21:31:11  Error: Could not create the Java Virtual Machine.
21:31:11  Error: A fatal exception has occurred. Program will exit.
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly_testList_1/352/ - [win2019-x64-2](https://openj9-jenkins.osuosl.org/computer/win2019-x64-2)
```
01:19:11  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41306M requested
01:19:11  Error: Could not create the Java Virtual Machine.
01:19:11  Error: A fatal exception has occurred. Program will exit.
```

@AdamBrousseau @vsebe

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly_testList_1/352/ - win2019-x64-2

**Comment by vsebe** [comment]
The Sanitize-Nodes_windows builds fail on the win2019 machines with `18:50:11  Access is denied.(5)` - https://openj9-jenkins.osuosl.org/view/Infrastructure/job/Sanitize-Nodes_windows/143/console
Granted shutdown privilege to Jenkins user.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/318/
testSoftMxUserScenario_2
```
05:35:59  [SoftmxUserScenarioTest] [INFO] Starting a new JVM using -Xmx = 41306 and -Xsoftmx = 20603
05:35:59  [SoftmxUserScenarioTest] [INFO] Executing cmd : F:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0\openjdkbinary\j2sdk-image/bin/java -cp F:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/aqa-tests///..//jvmtest\TestConfig\resources;F:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/aqa-tests/\TKG\lib\commons-exec.jar;F:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/aqa-tests/\TKG\lib\testng.jar;F:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/aqa-tests/\TKG\lib\jcommander.jar;F:/Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/aqa-tests///..//jvmtest\functional\JLM_Tests\jlm_tests.jar -Xmx41306m -Xsoftmx20603m org.openj9.test.softmx.HelperClass
05:36:03  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41306M requested
05:36:03  Error: Could not create the Java Virtual Machine.
05:36:03  Error: A fatal exception has occurred. Program will exit.
```

**Comment by vsebe** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/318/
testSoftMxUserScenario_2
```
05:36:03  [SoftmxUserScenarioTest] [INFO] Result exit value :  -1
05:36:03  FAILED: testSoftmxUserScenario
05:36:03  java.lang.AssertionError: FAIL: JVM did not start up and run ok when we set a -Xmx larger than (memory available + swap) and then set a softmx 1/2 that value which is less than ( memory available + swap) 
05:36:03  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
05:36:03  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
05:36:03  	at org.openj9.test.softmx.SoftmxUserScenarioTest.testSoftmxUserScenario(SoftmxUserScenarioTest.java:68)
```
duplicate of https://github.com/eclipse-openj9/openj9/issues/11775
Failure noticed on win 2016: https://github.com/eclipse-openj9/openj9/issues/11775#issuecomment-990962745

**Comment by pshipton** [comment]
On [win2019-x64-1](https://openj9-jenkins.osuosl.org/computer/win2019-x64-1)
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Release_testList_1/34
testSoftMxUserScenario_2
```
15:49:16  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41306M requested
```

**Comment by pshipton** [comment]
I'm not sure these are dups of https://github.com/eclipse-openj9/openj9/issues/11775, it doesn't contain enough info. These are always on Windows, and they are always on win2019 machines so far. Possibly insufficient swap space to allocation the 40G heap, probably combined with some process still running that shouldn't be consuming some of the memory.

**Comment by pshipton** [comment]
On [win2019-x64-2](https://openj9-jenkins.osuosl.org/computer/win2019-x64-2)
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_0/320
```
22:12:28  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41306M requested
```

**Comment by pshipton** [comment]
There are other related problems in https://github.com/eclipse-openj9/openj9/issues/15605, but they are all on [win2019-x64-3](https://openj9-jenkins.osuosl.org/computer/win2019-x64-3) which I believe is about to be deleted.

**Comment by vsebe** [comment]
I stopped win updates services.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_x86-64_windows_Nightly_testList_1/31 - [win2019-x64-1](https://openj9-jenkins.osuosl.org/computer/win2019-x64-1)
testSoftMxUserScenario_3
```
02:39:33  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41306M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/373 - [win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1)
testSoftMxUserScenario_3
```
02:56:54  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41058M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_0/429 - [win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1)
```
02:38:45  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41058M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Release_testList_0/44 - [win2019x64-openj9-2](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-2)
testSoftMxUserScenario_0
```
20:46:08  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41058M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_0/440 - [win2019x64-openj9-4](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-4)
testSoftMxUserScenario_1
```
05:00:23  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41058M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_0/450 - [win2012x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2012x64-openj9-1)
testSoftMxUserScenario_3 
```
01:48:16  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41058M requested
```

First time I've seen this not on a win2019 machine.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly_testList_0/477 - [win2019x64-openj9-3](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-3)
testSoftMxUserScenario_2
```
04:55:48  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41058M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/433 - [win2019x64-openj9-3](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-3)
testSoftMxUserScenario_0
```
00:00:48  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  41058M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_1/498
[win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1)
testSoftMxUserScenario_1
```
06:24:27  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  45156M requested
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_extended.functional_x86-64_windows_Nightly_testList_0/45
[win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1)
testSoftMxUserScenario_1
`JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap.  45156M requested`
