### ISSUE TITLE
jdk_security3_1_FAILED sun/security/ssl/SSLEngineImpl/SSLEngineDeadlock.java - Found Deadlock!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15836]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_ppc64le_linux/96/)(`sles15le-rt1-7`):
```
openjdk version "11.0.17" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0-m1 (build 11.0.17+4)
Eclipse OpenJ9 VM 11.0.17.0-m1 (build openj9-0.35.0-m1, JRE 11 Linux ppc64le-64-Bit Compressed References 20220901_484 (JIT enabled, AOT enabled)
OpenJ9   - f8c5cbdeb
OMR      - 938f0686f
JCL      - 4e2342f3c4 based on jdk-11.0.17+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security3_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9%2F484%2Fibm-semeru-open-testimage_ppc64le_linux_11.0.17_4_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9%2F484%2Fibm-semeru-open-debugimage_ppc64le_linux_11.0.17_4_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9%2F484%2Fibm-semeru-open-jdk_ppc64le_linux_11.0.17_4_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9%2F484%2Fibm-semeru-open-jre_ppc64le_linux_11.0.17_4_openj9-0.35.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=v0.35.0-release&amp;OPENJ9_BRANCH=v0.35.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.35.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-09-01T10:58:10.761Z] variation: Mode650
[2022-09-01T10:58:10.761Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-09-01T11:39:06.491Z] TEST: sun/security/ssl/SSLEngineImpl/SSLEngineDeadlock.java

[2022-09-01T11:39:06.493Z] Deadlocked ThreadInfo: "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
[2022-09-01T11:39:06.493Z] 	at java.base@11.0.17/java.lang.Object.wait(Native Method)
[2022-09-01T11:39:06.493Z] 	at java.base@11.0.17/java.lang.Object.wait(Object.java:219)
[2022-09-01T11:39:06.494Z] 	at java.base@11.0.17/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
[2022-09-01T11:39:06.494Z] 	at java.base@11.0.17/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
[2022-09-01T11:39:06.494Z] 	at java.base@11.0.17/java.lang.Thread.run(Thread.java:839)
[2022-09-01T11:39:06.494Z] 	at java.base@11.0.17/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
[2022-09-01T11:39:06.494Z] 
[2022-09-01T11:39:06.494Z] Deadlocked ThreadInfo: "Finalizer thread" prio=5 Id=19 RUNNABLE
[2022-09-01T11:39:06.494Z] 
[2022-09-01T11:39:06.494Z] STDERR:
[2022-09-01T11:39:06.494Z] java.lang.Exception: Found Deadlock!
[2022-09-01T11:39:06.494Z] 	at SSLEngineDeadlock.detectDeadLock(SSLEngineDeadlock.java:378)
[2022-09-01T11:39:06.494Z] 	at SSLEngineDeadlock.main(SSLEngineDeadlock.java:148)
[2022-09-01T11:39:06.494Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-09-01T11:39:06.494Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-09-01T11:39:06.494Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-09-01T11:39:06.494Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-09-01T11:39:06.494Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-01T11:39:06.494Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2022-09-01T11:39:06.494Z] 
[2022-09-01T11:39:06.494Z] JavaTest Message: Test threw exception: java.lang.Exception: Found Deadlock!
[2022-09-01T11:39:06.494Z] JavaTest Message: shutting down test
[2022-09-01T11:39:06.494Z] 
[2022-09-01T11:39:06.494Z] STATUS:Failed.`main' threw exception: java.lang.Exception: Found Deadlock!

[2022-09-01T12:12:07.628Z] jdk_security3_1_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27143/)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0/406/)
```
[2026-01-31T07:13:34.952Z] Running test jdk_security3_0 ...
[2026-01-31T07:13:35.324Z] ===============================================
[2026-01-31T07:13:35.324Z] jdk_security3_0 Start Time: Fri Jan 30 23:13:35 2026 Epoch Time (ms): 1769843615298
[2026-01-31T07:13:35.324Z] variation: Mode150
[2026-01-31T07:13:35.696Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2026-01-31T10:48:40.642Z] TEST: sun/security/ssl/SSLEngineImpl/SSLEngineDeadlock.java

[2026-01-31T10:48:40.643Z] 
[2026-01-31T10:48:40.643Z] TEST RESULT: Error. Program `C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0\jdkbinary\j2sdk-image\bin\java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1037722ms).
```

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0/411/consoleFull)
```
03:19:26  Running test jdk_security3_0 ...
03:19:26  ===============================================
03:19:27  jdk_security3_0 Start Time: Sun Feb  8 00:19:27 2026 Epoch Time (ms): 1770538767544
03:19:27  variation: Mode150
03:19:27  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

06:58:03  TEST: sun/security/ssl/SSLEngineImpl/SSLEngineDeadlock.java

06:58:03  TEST RESULT: Error. Program `C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0\jdkbinary\j2sdk-image\bin\java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1038566ms).
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/58221/) - still in progress, no timeout was reproduced
