### ISSUE TITLE
LambdaLoadTest Method "testLambdasWithMultipleThreads" not found

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15832]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_special.system_aarch64_linux_Personal_testList_1/24
LambdaLoadTest_special_J9_5m_28 `-Xcompressedrefs -Xgcpolicy:gencon -Xshareclasses -Xjit`

```
LT  testStarted : testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
LT  testFailure: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testLambdasWithMultipleThreads" not found
LT  junit.framework.AssertionFailedError: Method "testLambdasWithMultipleThreads" not found
LT  	at junit.framework.Assert.fail(Assert.java:57)
LT  	at junit.framework.TestCase.fail(TestCase.java:227)
LT  	at junit.framework.TestCase.runTest(TestCase.java:169)
LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
LT  	at junit.framework.TestResult.run(TestResult.java:125)
LT  	at junit.framework.TestCase.run(TestCase.java:129)
LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:826)
LT  testFinished: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
```

**Comment by pshipton** [comment]
See also https://github.com/eclipse-openj9/openj9/issues/16032
