### ISSUE TITLE
JDK17 aarch64-64 jdk_text_1_FAILED - OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15859]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/74/)(`cent7-aarch64-3`):
```
openjdk version "17.0.5" 2022-10-18
IBM Semeru Runtime Open Edition 17.0.5.0-m1 (build 17.0.5+5)
Eclipse OpenJ9 VM 17.0.5.0-m1 (build v0.35.0-release-1de4f14ba, JRE 17 Linux aarch64-64-Bit Compressed References 20221018_257 (JIT enabled, AOT enabled)
OpenJ9   - 1de4f14ba
OMR      - 938f0686f
JCL      - 37e17cdb684 based on jdk-17.0.5+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_text_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F257%2Fibm-semeru-open-jdk_aarch64_linux_17.0.5_4_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F257%2Fibm-semeru-open-debugimage_aarch64_linux_17.0.5_4_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F257%2Fibm-semeru-open-testimage_aarch64_linux_17.0.5_4_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F257%2Fibm-semeru-open-jre_aarch64_linux_17.0.5_4_openj9-0.35.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=v0.35.0-release&amp;OPENJ9_BRANCH=v0.35.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.35.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-09-08T09:08:59.857Z] variation: Mode650
[2022-09-08T09:08:59.857Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-09-08T09:13:07.438Z] TEST: java/text/Format/DateFormat/SimpleDateFormatPatternTest.java

[2022-09-08T09:13:07.450Z] ===============================================
[2022-09-08T09:13:07.450Z] java/text/Format/DateFormat/SimpleDateFormatPatternTest.java
[2022-09-08T09:13:07.450Z] Total tests run: 113904, Passes: 113904, Failures: 0, Skips: 0
[2022-09-08T09:13:07.450Z] ===============================================
[2022-09-08T09:13:07.450Z] 
[2022-09-08T09:13:07.450Z] STDERR:
[2022-09-08T09:13:07.450Z] JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/09/08 05:12:08 - please wait.

[2022-09-08T09:13:07.451Z] java.lang.OutOfMemoryError: Java heap space
[2022-09-08T09:13:07.451Z] JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16626168835934/jdk_text_1/work/scratch/0/Snap.20220908.051242.21575.0013.trc
[2022-09-08T09:13:07.451Z] JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[2022-09-08T09:13:07.451Z] 	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:576)
[2022-09-08T09:13:07.451Z] 	at java.base/java.lang.Throwable.printStackTraceHelper(Throwable.java:338)
[2022-09-08T09:13:07.451Z] 	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:318)
[2022-09-08T09:13:07.451Z] 	at org.testng.internal.Utils.buildStackTrace(Utils.java:320)
[2022-09-08T09:13:07.451Z] 	at org.testng.internal.Utils.longStackTrace(Utils.java:303)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLSuiteResultWriter.addTestResultException(XMLSuiteResultWriter.java:304)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLSuiteResultWriter.addTestResult(XMLSuiteResultWriter.java:159)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLSuiteResultWriter.addTestResults(XMLSuiteResultWriter.java:135)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLSuiteResultWriter.writeAllToBuffer(XMLSuiteResultWriter.java:79)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLSuiteResultWriter.writeSuiteResult(XMLSuiteResultWriter.java:54)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLReporter.writeSuiteToBuffer(XMLReporter.java:146)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLReporter.writeSuite(XMLReporter.java:108)
[2022-09-08T09:13:07.451Z] 	at org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:76)
[2022-09-08T09:13:07.451Z] 	at org.testng.TestNG.generateReports(TestNG.java:1099)
[2022-09-08T09:13:07.451Z] 	at org.testng.TestNG.run(TestNG.java:1042)
[2022-09-08T09:13:07.451Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-09-08T09:13:07.451Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-09-08T09:13:07.451Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-09-08T09:13:07.451Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-09-08T09:13:07.451Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-09-08T09:13:07.451Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-09-08T09:13:07.451Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-08T09:13:07.451Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2022-09-08T09:13:07.451Z] 
[2022-09-08T09:13:07.451Z] JavaTest Message: Test threw exception: java.lang.OutOfMemoryError: Java heap space

[2022-09-08T09:13:07.452Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Java heap space
[2022-09-08T09:13:07.452Z] --------------------------------------------------
[2022-09-08T09:13:07.452Z] Test results: passed: 183; failed: 1
[2022-09-08T09:13:14.292Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16626168835934/jdk_text_1/report/html/report.html
[2022-09-08T09:13:14.292Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16626168835934/jdk_text_1/work
[2022-09-08T09:13:14.292Z] Error: Some tests failed or other problems occurred.
[2022-09-08T09:13:14.292Z] 
[2022-09-08T09:13:14.292Z] jdk_text_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27311/)

**Comment by pshipton** [comment]
@dmitripivkine not sure if it's worth looking at this, there are [artifacts](https://na.artifactory.swg-devops.com/artifactory/sys-rt-generic-local/hyc-runtimes-jenkins.swg-devops.com/Test_openjdk17_j9_extended.openjdk_aarch64_linux/74/openjdk_test_output.tar.gz)

**Comment by dmitripivkine** [comment]
top of the report objects in the heap:
```
       instances  total size on heap  class name
         3198859           281499592  java/lang/StackTraceElement
          524796            16793472  java/util/concurrent/ConcurrentLinkedQueue$Node
          251476            12070848  java/util/concurrent/ConcurrentHashMap$Node
          205133             6564256  java/lang/String
          204554            23589328  [B
          178833             8457256  [Ljava/lang/Object;
          115907             3709024  java/util/ArrayList
          115135             5526480  java/util/Locale
          114309             7315776  java/util/HashMap
          113913             1822608  org/testng/internal/annotations/DisabledRetryAnalyzer
          113906             2733744  org/testng/internal/Attributes
          113904            13668480  org/testng/internal/TestResult
          113904             5467392  org/testng/internal/InvokedMethod
           69186            20772504  [J
           68403             1641672  java/lang/Integer
           68142            27226576  [Ljava/lang/StackTraceElement;
           65088             4165632  java/lang/IllegalArgumentException
            6131              294288  java/util/HashMap$Node
            5080              284480  sun/util/locale/provider/LocaleResources$ResourceReference
            4068              292896  java/lang/NullPointerException
            2415              135240  sun/util/locale/LocaleObjectCache$CacheEntry
            2329              111792  java/lang/ref/SoftReference
            2289              476112  java/lang/Class
            1273              123992  [C
            1226               68656  sun/util/locale/BaseLocale
            1207               48280  sun/util/locale/BaseLocale$Key
            1163              120952  java/util/concurrent/ConcurrentHashMap
            1140             4220000  [Ljava/util/concurrent/ConcurrentHashMap$Node;
            1093              101800  [I
            1046               41840  java/lang/ref/ReferenceQueue
            1028             1084344  [Ljava/lang/ref/Reference;
            1023               57288  sun/util/locale/provider/LocaleResources
            1017              268488  java/text/DecimalFormat
            1017              154584  java/text/DecimalFormatSymbols
            1017               65088  java/text/DigitList
             626               35056  sun/util/resources/Bundles$CacheKey
             626               35056  sun/util/resources/Bundles$BundleReference
             447               17528  [Ljava/lang/Class;
             446               20424  [Ljava/lang/String;
             419               10056  java/lang/J9VMInternals$ClassInitializationLock
             399              144232  [Ljava/util/HashMap$Node;
.....
```

**Comment by dmitripivkine** [comment]
java stack
```
> !stack 0xffffb43e6a00
<ffffb43e6a00> 	!j9method 0x0000FFFFB416EC60   java/lang/J9VMInternals.getStackTrace(Ljava/lang/Throwable;Z)[Ljava/lang/StackTraceElement;
<ffffb43e6a00> 	!j9method 0x0000FFFFB41AE540   java/lang/Throwable.getInternalStackTrace()[Ljava/lang/StackTraceElement;
<ffffb43e6a00> 	!j9method 0x0000FFFFB41AE680   java/lang/Throwable.printStackTrace(Ljava/lang/Appendable;[Ljava/lang/StackTraceElement;IZLjava/util/Set;)[Ljava/lang/StackTraceElement;
<ffffb43e6a00> 	!j9method 0x0000FFFFB41AE5A0   java/lang/Throwable.printStackTraceHelper(Ljava/lang/Appendable;)V
<ffffb43e6a00> 	!j9method 0x0000FFFFB41AE580   java/lang/Throwable.printStackTrace(Ljava/io/PrintWriter;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF0003FC78   org/testng/internal/Utils.buildStackTrace(Ljava/lang/Throwable;ZLorg/testng/internal/Utils$StackTraceType;)Ljava/lang/String;
<ffffb43e6a00> 	!j9method 0x0000FFFF0003FC38   org/testng/internal/Utils.longStackTrace(Ljava/lang/Throwable;Z)Ljava/lang/String;
<ffffb43e6a00> 	!j9method 0x0000FFFF002EBE48   org/testng/reporters/XMLSuiteResultWriter.addTestResultException(Lorg/testng/reporters/XMLStringBuffer;Lorg/testng/ITestResult;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF002EBD88   org/testng/reporters/XMLSuiteResultWriter.addTestResult(Lorg/testng/reporters/XMLStringBuffer;Lorg/testng/ITestResult;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF002EBD48   org/testng/reporters/XMLSuiteResultWriter.addTestResults(Lorg/testng/reporters/XMLStringBuffer;Ljava/util/Set;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF002EBCC8   org/testng/reporters/XMLSuiteResultWriter.writeAllToBuffer(Lorg/testng/reporters/XMLStringBuffer;Lorg/testng/ISuiteResult;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF002EBCA8   org/testng/reporters/XMLSuiteResultWriter.writeSuiteResult(Lorg/testng/reporters/XMLStringBuffer;Lorg/testng/ISuiteResult;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF000C48F0   org/testng/reporters/XMLReporter.writeSuiteToBuffer(Lorg/testng/reporters/XMLStringBuffer;Lorg/testng/ISuite;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF000C4890   org/testng/reporters/XMLReporter.writeSuite(Lorg/testng/ISuite;)V
<ffffb43e6a00> 	!j9method 0x0000FFFF000C4810   org/testng/reporters/XMLReporter.generateReport(Ljava/util/List;Ljava/util/List;Ljava/lang/String;)V
<ffffb43e6a00> 	!j9method 0x0000FFFFB43DA1F8   org/testng/TestNG.generateReports(Ljava/util/List;)V
<ffffb43e6a00> 	!j9method 0x0000FFFFB43DA158   org/testng/TestNG.run()V
<ffffb43e6a00> 	!j9method 0x0000FFFFB43D5248   com/sun/javatest/regtest/agent/TestNGRunner.main(Ljava/lang/ClassLoader;[Ljava/lang/String;)V
<ffffb43e6a00> 	!j9method 0x0000FFFFB43D5228   com/sun/javatest/regtest/agent/TestNGRunner.main([Ljava/lang/String;)V
<ffffb43e6a00> 	                        JNI call-in frame
<ffffb43e6a00> 	!j9method 0x0000FFFFB4359D48   jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
<ffffb43e6a00> 	!j9method 0x0000FFFFB4359D08   jdk/internal/reflect/NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
<ffffb43e6a00> 	!j9method 0x0000FFFFB435A068   jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
<ffffb43e6a00> 	!j9method 0x0000FFFFB41A0168   java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
<ffffb43e6a00> 	!j9method 0x0000FFFFB43D44B0   com/sun/javatest/regtest/agent/MainWrapper$MainThread.run()V
<ffffb43e6a00> 	!j9method 0x0000FFFFB41A8710   java/lang/Thread.run()V
<ffffb43e6a00> 	                        JNI call-in frame
<ffffb43e6a00> 	                        Native method frame
```

**Comment by pshipton** [comment]
I wonder if there is some corruption that rather than causing a crash, caused all the StackTraceElement's to be created.
