### ISSUE TITLE
jdk19 testDDRExtJunit_FindExtThread_0 fails

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15850]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_aarch64_linux_Nightly_testList_1/1/
It's failing on all platforms. It's the only test blocking extended.functionality from passing. @tajila fyi.
testDDRExtJunit_FindExtThread_0

```
     [java] [AutoRun] [INFO] Starting testFindstackvalue(j9vm.test.ddrext.junit.TestFindExt)
     [java] [DDRExtTesterBase] [ERROR] '!findstackvalue 0x00000000000615B8' output is empty
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)
  ```

**Comment by JasonFengJ9** [comment]
Also seen at [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.functional_aarch64_linux_testList_0/6/)
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+36 (build 19+36)
Eclipse OpenJ9 VM 19+36 (build master-b8752ec8b, JRE 19 Linux aarch64-64-Bit Compressed References 20220920_38 (JIT enabled, AOT enabled)
OpenJ9   - b8752ec8b
OMR      - 647678f93
JCL      - 034a8c8f12 based on jdk-19+36)

[2022-09-11T02:54:35.795Z] variation: NoOptions
[2022-09-11T02:54:35.795Z] JVM_OPTIONS:  

[2022-09-11T02:54:51.070Z]      [java] [DDRExtTesterBase] [ERROR] '!findstackvalue 0x00000000000615B8' output is empty
[2022-09-11T02:54:51.070Z]      [java] junit.framework.AssertionFailedError
[2022-09-11T02:54:51.070Z]      [java] 	at junit.framework.Assert.fail(Assert.java:48)
[2022-09-11T02:54:51.070Z]      [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
[2022-09-11T02:54:51.070Z]      [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
[2022-09-11T02:54:51.070Z]      [java] 	at j9vm.test.ddrext.junit.TestFindExt.testFindstackvalue(TestFindExt.java:148)

[2022-09-11T02:54:51.916Z] testDDRExtJunit_FindExtThread_0_FAILED
```

**Comment by tajila** [comment]
@mikezhang1234567890 can you please take a look at this?

**Comment by mikezhang1234567890** [comment]
I'll take a look at it.

**Comment by mikezhang1234567890** [comment]
I downloaded the core from one of the failing tests, and the method address that the test checks for isn't in any of the stacks in the core.

The code [here](https://github.com/eclipse-openj9/openj9/blob/ef6948124a16e50c03faa7e69383cb9677bc985d/test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestFindExt.java#L137) specifically asks for the function with signature `java/lang/Thread.sleep(JI)V`. Is there any reason we're asking for that specific method to exist in the stack or can we select any method for this test?

**Comment by pshipton** [comment]
Any method that exists.
