### ISSUE TITLE
aarch64 mac OpenJDK crash vmState=0x00020015

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15868]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_Release/16
jdk_util_1
java/util/ServiceLoader/ReloadTest.java

Seems it crashed after passing the test, maybe related to https://github.com/eclipse-openj9/openj9/issues/14717

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_Release/16/openjdk_test_output.tar.gz

```
06:02:01  STDOUT:
06:02:01  test ReloadTest.testIteratorHasNext(): success
06:02:01  test ReloadTest.testIteratorNext(): success
06:02:01  test ReloadTest.testReload(): success
06:02:01  test ReloadTest.testSpliteratorTryAdvance(): success
06:02:01  test ReloadTest.testStreamFindAny(): success
06:02:01  
06:02:01  ===============================================
06:02:01  java/util/ServiceLoader/ReloadTest.java
06:02:01  Total tests run: 5, Passes: 5, Failures: 0, Skips: 0
06:02:01  ===============================================
06:02:01  
06:02:01  Timeout refired 960 times
06:02:01  STDERR:
06:02:01  STATUS:Passed.
06:02:01  Unhandled exception
06:02:01  Type=Segmentation error vmState=0x00020015
06:02:01  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
06:02:01  Handler1=00000001048257DC Handler2=000000010062EE14 InaccessibleAddress=0000000000080000
06:02:01  x0=0000000000000000 x1=0000000124841758 x2=0000000000000000 x3=0000000000000000
06:02:01  x4=000000016FA73DD0 x5=0000000000000000 x6=0000000000000000 x7=0000000000000000
06:02:01  x8=0000000000080000 x9=000000012487E3D0 x10=0000000000000008 x11=0000000000000001
06:02:01  x12=0000000000000006 x13=0000000000000000 x14=0000000000000000 x15=000000012488A578
06:02:01  x16=0000000188D1E654 x17=00000001F77A1648 x18=00000002E027FF10 x19=000000012487E300
06:02:01  x20=0000000000000064 x21=0000000104AC2A90 x22=0000000000000000 x23=000000012487E464
06:02:01  x24=0000000000000003 x25=00000001005C9E28 x26=000000012487E3C8 x27=0000000000000001
06:02:01  x28=0000000000000000 x29(FP)=000000016FA73DC0 x30(LR)=0000000104CB36B4 x31(SP)=000000016FA73C70
06:02:01  PC=0000000104CB3734 SP=000000016FA73C70
06:02:01  v0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v1 40bb900000000000 (f: 0.000000, d: 7.056000e+03)
06:02:01  v2 0000000000005550 (f: 21840.000000, d: 1.079039e-319)
06:02:01  v3 000000000000000a (f: 10.000000, d: 4.940656e-323)
06:02:01  v4 0000000000000001 (f: 1.000000, d: 4.940656e-324)
06:02:01  v5 0000000000001550 (f: 5456.000000, d: 2.695622e-320)
06:02:01  v6 0000000000000002 (f: 2.000000, d: 9.881313e-324)
06:02:01  v7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v16 bfd0000000000000 (f: 0.000000, d: -2.500000e-01)
06:02:01  v17 3fd54993c2c55555 (f: 3267712256.000000, d: 3.326158e-01)
06:02:01  v18 3f677a86096fcb56 (f: 158321488.000000, d: 2.866041e-03)
06:02:01  v19 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
06:02:01  v20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  v31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
06:02:01  Module=/Users/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_Release/openjdkbinary/j2sdk-image/lib/default/libj9jit29.dylib
06:02:01  Module_base_address=0000000104A60000 Symbol=_ZN25TR_RuntimeAssumptionTable31reclaimMarkedAssumptionsFromRATEi
06:02:01  Symbol_address=0000000104CB3678
06:02:01  Target=2_90_20220910_19 (Mac OS X 11.5.2)
06:02:01  CPU=aarch64 (8 logical CPUs) (0x400000000 RAM)
06:02:01  ----------- Stack Backtrace -----------
06:02:01  ---------------------------------------
```

@knn-k

**Comment by knn-k** [comment]
I see the following in ReloadTest/javacore.20220910.194548.80028.0004.txt.  The main thread is exiting.  A JIT compilation thread is the current thread, and it seems to call `java/lang/ClassLoader.loadClass()` recursively.  The callstack looks similar with that in #15518, but the location of the crash is different. 

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "JIT Compilation Thread-000" J9VMThread:0x0000000124889B00, omrthread_t:0x000000012480C060, java/lang
/Thread:0x000000028011FF90, state:R, prio=10
3XMJAVALTHREAD            (java/lang/Thread getId:0x3, isDaemon:true)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x0000000280067F38)
3XMTHREADINFO1            (native thread ID:0xD73C1AA, native priority:0xB, native policy:UNKNOWN, vmstate:R, vm thread
flags:0x00001060)
3XMTHREADINFO2            (native stack address range from:0x000000016FA64000, to:0x000000016FB67000, size:0x103000)
3XMCPUTIME               CPU usage total: 0.178716000 secs, current category="JIT"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
1INTERNAL                    Unable to obtain lock context information
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java(Compiled Code))
(... lines omitted ...)
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java(Compiled Code))
3XMTHREADINFO3           No native callstack available for this thread
NULL
NULL
NULL
1XMTHDINFO     Thread Details
NULL
3XMTHREADINFO      "main" J9VMThread:0x0000000124872F00, omrthread_t:0x000000012480B650, java/lang/Thread:0x000000028006
C0E0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x0000000280067F38)
3XMTHREADINFO1            (native thread ID:0xD73C159, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000001)
3XMTHREADINFO2            (native stack address range from:0x000000016F9CC000, to:0x000000016FA0F000, size:0x43000)
3XMCPUTIME               CPU usage total: 0.306587000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Shutdown.halt0(Native Method)
4XESTACKTRACE                at java/lang/Shutdown.halt(Shutdown.java:151)
5XESTACKTRACE                   (entered lock: java/lang/Shutdown$Lock@0x0000000280134CD0, entry count: 1)
4XESTACKTRACE                at java/lang/Shutdown.exit(Shutdown.java:174)
5XESTACKTRACE                   (entered lock: java/lang/Shutdown@0x00000002800E2C18, entry count: 1)
4XESTACKTRACE                at java/lang/Runtime.exit(Runtime.java:115)
4XESTACKTRACE                at java/lang/System.exit(System.java:485)
4XESTACKTRACE                at com/sun/javatest/regtest/agent/AStatus.exit(AStatus.java:199)
4XESTACKTRACE                at com/sun/javatest/regtest/agent/MainWrapper.main(MainWrapper.java:84)
3XMTHREADINFO3           No native callstack available for this thread
```

**Comment by knn-k** [comment]
The location of the crash is the following line in `TR_RuntimeAssumptionTable::reclaimMarkedAssumptionsFromRAT(int)`.
https://github.com/eclipse-openj9/openj9/blob/df2f3a3524957ff9e59c6861992f8195beb24aa6/runtime/compiler/runtime/ClassUnloadAssumption.cpp#L433

It tries to access `hashTable->_htSpineArray[i]`, but the pointer `hashTable->_htSpineArray` in `x8` is corrupted.

```
  253724: 9f 03 08 eb   cmp     x28, x8
  253728: a2 07 00 54   b.hs    0x25381c
  25372c: e8 0f 40 f9   ldr     x8, [sp, #24]
  253730: 08 01 40 f9   ldr     x8, [x8]
  253734: 15 79 7c f8   ldr     x21, [x8, x28, lsl #3] <- PC points here; x8=0x080000, x28=0x0
  253738: 55 fe ff b4   cbz     x21, 0x253700 <TR_RuntimeAssumptionTable::reclaimMarkedAssumptionsFromRAT(int)+0x88>
```

**Comment by knn-k** [comment]
PR #15907 should fix this issue.
