### ISSUE TITLE
jdk_security3_0_FAILED javax/net/ssl/ServerName/SSLEngineExplorerMatchedSNI.java - SSLProtocolException: Input record too big

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15862]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_s390x_linux/83/)(`ubu22s390x-rt1-1`):
```
openjdk version "1.8.0_352"
IBM Semeru Runtime Open Edition (build 1.8.0_352-b05)
Eclipse OpenJ9 VM (build v0.35.0-release-7dd982ba7, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20220908_443 (JIT enabled, AOT enabled)
OpenJ9   - 7dd982ba7
OMR      - 938f0686f
JCL      - d0e3108595 based on jdk8u352-b05)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F443%2Fibm-semeru-open-jdk_s390x_linux_8u352b04_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F443%2Fibm-semeru-open-jre_s390x_linux_8u352b04_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F443%2Fibm-semeru-open-debugimage_s390x_linux_8u352b04_openj9-0.35.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F443%2Fibm-semeru-open-testimage_s390x_linux_8u352b04_openj9-0.35.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=v0.35.0-release&amp;OPENJ9_BRANCH=v0.35.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.35.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-09-09T00:22:52.627Z] variation: Mode150
[2022-09-09T00:22:52.627Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-09-09T00:24:21.176Z] TEST: javax/net/ssl/ServerName/SSLEngineExplorerMatchedSNI.java

[2022-09-09T00:24:21.185Z] STDERR:
[2022-09-09T00:24:21.185Z] javax.net.ssl.SSLProtocolException: Input record too big: max = 16709 len = 22945
[2022-09-09T00:24:21.185Z] 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:508)
[2022-09-09T00:24:21.185Z] 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:411)
[2022-09-09T00:24:21.185Z] 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:390)
[2022-09-09T00:24:21.185Z] 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
[2022-09-09T00:24:21.185Z] 	at SSLEngineService.receive(SSLEngineService.java:167)
[2022-09-09T00:24:21.185Z] 	at SSLEngineExplorerMatchedSNI.doServerSide(SSLEngineExplorerMatchedSNI.java:160)
[2022-09-09T00:24:21.185Z] 	at SSLEngineExplorerMatchedSNI.startServer(SSLEngineExplorerMatchedSNI.java:369)
[2022-09-09T00:24:21.185Z] 	at SSLEngineExplorerMatchedSNI.<init>(SSLEngineExplorerMatchedSNI.java:319)
[2022-09-09T00:24:21.185Z] 	at SSLEngineExplorerMatchedSNI.main(SSLEngineExplorerMatchedSNI.java:300)
[2022-09-09T00:24:21.185Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-09-09T00:24:21.185Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-09-09T00:24:21.185Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-09-09T00:24:21.185Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-09-09T00:24:21.185Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-09T00:24:21.185Z] 	at java.lang.Thread.run(Thread.java:826)
[2022-09-09T00:24:21.185Z] 
[2022-09-09T00:24:21.185Z] JavaTest Message: Test threw exception: javax.net.ssl.SSLProtocolException: Input record too big: max = 16709 len = 22945

[2022-09-09T01:18:46.725Z] Test results: passed: 601; failed: 1
[2022-09-09T01:18:46.725Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16626783491180/jdk_security3_0/report/html/report.html
[2022-09-09T01:18:46.725Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16626783491180/jdk_security3_0/work
[2022-09-09T01:18:46.725Z] Error: Some tests failed or other problems occurred.
[2022-09-09T01:18:46.725Z] 
[2022-09-09T01:18:46.725Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27317/)

**Comment by pshipton** [comment]
Try a [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27325/) on 0.33.1

**Comment by pshipton** [comment]
Subset of OpenJDK changes (e361c66..d0e3108), nothing seems obviously related to me:
```
11cd91f951d 8292688: Support Security properties in security.testlibrary.Proc
96bed26602e 8049228: Improve multithreaded scalability of InetAddress cache 7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate
a87e397aae6 8232950: SUNPKCS11 Provider incorrectly check key length for PSS Signatures.
78e6dc24439 8039955: [TESTBUG] jdk/lambda/LambdaTranslationTest1 - java.lang.AssertionError: expected [d:1234.000000] but found [d:1234,000000]
9436b68a1e7 8201793: (ref) Reference object should not support cloning
21f65dd1289 8183107: PKCS11 regression regarding checkKeySize
9376803a7c0 8175797: (ref) Reference::enqueue method should clear the reference object before enqueuing 8178832: (ref) jdk.lang.ref.disableClearBeforeEnqueue property is ignored 8193780: (ref) Remove the undocumented "jdk.lang.ref.disableClearBeforeEnqueue" system property
76ed082a40b 8214427: probable bug in logic of ConcurrentHashMap.addCount()
96f0ca66d50 8288763: Pack200 extraction failure with invalid size
3642cf4da59 8245263: Enable TLSv1.3 by default on JDK 8u for Client roles
b4fa0fcc2ad 8071507: (ref) Clear phantom reference as soft and weak references do 8143847: Remove REF_CLEANER reference category
4db73b9fc11 8287132: Retire Runtime.runFinalizersOnExit so that it always throws UOE
bd987716b92 8194873: right ALT key hotkeys no longer work in Swing components 8155742: [Windows] robot.keyPress(KeyEvent.VK_ALT_GRAPH) throws java.lang.IllegalArgumentException in windows
612208ee2ba 8282538: PKCS11 tests fail on CentOS Stream 9
11cf113b007 8136354: [TEST_BUG] Test  java/awt/image/RescaleOp/RescaleAlphaTest.java with Bad action for script
9caefe574eb 8087283: Add support for the XML Signature here() function to the JDK XPath implementation
bb724a66da3 8260589: Crash in JfrTraceIdLoadBarrier::load(_jclass*)
```

[grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27424/) on xlinux

**Comment by pshipton** [comment]
@joransiu this seems like a JIT issue introduced since the last release.

**Comment by joransiu** [comment]
@r30shah has kindly offered to look into this.

**Comment by pshipton** [comment]
I was able to get the same failure on xlinux, so this is not zlinux specific.

**Comment by r30shah** [comment]
Thanks a lot @pshipton  for checking if the issue is Z specific or not.  While I am checking what causes the failure (I tried running this manually on Ubuntu - 20.04, but can not reproduce in 5 runs),  do you still suspect it is JIT related issue or any OpenJDK change listed in https://github.com/eclipse-openj9/openj9/issues/15862#issuecomment-1244201626 could have caused it?

**Comment by pshipton** [comment]
I'm not familiar with the OpenJDK code to know if one of the changes could be causing this. Maybe @alon-sh would be able to make an assessment. It feels like a JIT issue, but I could be wrong. I'm still running grinders, so far I haven't been able to reproduce outside of OpenJ9 0.35. The "same" OpenJDK code is used for Temurin, and I haven't reproduced it there yet.

**Comment by pshipton** [comment]
Grinder are finished (enough), no new failures on Temurin or 0.33. I'm done running grinders unless there is a suggestion for other options to try.

**Comment by r30shah** [comment]
I  was able to extract out the test to run easily through Java command line. Uploading the test here for reference. 
[reprduceFailure.zip](https://github.com/eclipse-openj9/openj9/files/9559709/reprduceFailure.zip)

Looking at the unit test code, I do not see anything specific that stands out. Exception is thrown at [1] where the packet size exceeds the max buffer size fixed for SSLRecord. 

I am able to get it reproduced with JIT disabled as well.
```
while [ $count -lt 100 ]; do ./jdk8u352-b05/bin/java -Xshareclasses:destroyAll -version ; ./jdk8u352-b05/bin/java  -Djdk.nativeCrypto=false -ea -esa -Xmx512m -XX:+UseCompressedOops -Xint SSLEngineExplorerMatchedSNI example.com "(.*\.)*example\.(com|org)"; count=$((count+1)); done
...
Attempting to destroy all caches in cacheDir /home/jenkins/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
resize destination buffer upto 16709 bytes for BUFFER_OVERFLOW
resize source buffer upto 16709 bytes for BUFFER_UNDERFLOW
Record version: TLSv1.2
Hello version: TLSv1.2
resize destination buffer upto 16709 bytes for BUFFER_OVERFLOW
resize destination buffer upto 16709 bytes for BUFFER_OVERFLOW
resize destination buffer upto 16676 bytes for BUFFER_OVERFLOW
resize source buffer upto 16709 bytes for BUFFER_UNDERFLOW
received 16367 bytes client application data
	comsumed 16405 byes network data
received 16367 bytes client application data
	comsumed 16405 byes network data
received 16367 bytes client application data
	comsumed 16405 byes network data
resize source buffer upto 16709 bytes for BUFFER_UNDERFLOW
received 16367 bytes client application data
	comsumed 16405 byes network data
received 1236 bytes client application data
	comsumed 1274 byes network data
resize destination buffer upto 16709 bytes for BUFFER_OVERFLOW
resize destination buffer upto 16676 bytes for BUFFER_OVERFLOW
received 16367 bytes client application data
	comsumed 16405 byes network data
received 16367 bytes client application data
	comsumed 16405 byes network data
received 16367 bytes client application data
	comsumed 16405 byes network data
received 16367 bytes client application data
	comsumed 16405 byes network data
received 1236 bytes client application data
	comsumed 1274 byes network data

Attempting to destroy all caches in cacheDir /home/jenkins/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
resize destination buffer upto 16709 bytes for BUFFER_OVERFLOW
resize source buffer upto 16709 bytes for BUFFER_UNDERFLOW
Record version: TLSv1.2
Hello version: TLSv1.2
resize destination buffer upto 16709 bytes for BUFFER_OVERFLOW
resize destination buffer upto 16709 bytes for BUFFER_OVERFLOW
resize source buffer upto 16709 bytes for BUFFER_UNDERFLOW
Exception in thread "main" javax.net.ssl.SSLProtocolException: Input record too big: max = 16709 len = 30968
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:508)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:411)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:390)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
	at SSLEngineService.receive(SSLEngineService.java:167)
	at SSLEngineExplorerMatchedSNI.doServerSide(SSLEngineExplorerMatchedSNI.java:160)
	at SSLEngineExplorerMatchedSNI.startServer(SSLEngineExplorerMatchedSNI.java:369)
	at SSLEngineExplorerMatchedSNI.<init>(SSLEngineExplorerMatchedSNI.java:319)
	at SSLEngineExplorerMatchedSNI.main(SSLEngineExplorerMatchedSNI.java:300)
```

As @pshipton  noted in last comment, it does not fail with Temurin or 0.33, it might be OpenJ9 specific. Checking is it passes with 0.33 with the unit test. 

[1]. https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/8e8d4d3ae262f8d653e6068f886fdae18b17e97e/jdk/src/share/classes/sun/security/ssl/SSLEngineImpl.java#L508-L510

**Comment by alon-sh** [comment]
I would say try -Djdk.nativeCrypto=false but that was already tried and still fails so its not the OpenSSL code.

At this point I don't have any further to add except to say that the TLS engine for both OpenJ9 and Temurin is identical.

**Comment by pshipton** [comment]
Both failures reproduce with -Xint -Xshareclasses:none -Xgcpolicy:optthruput or gencon. 

I haven't been able to reproduce it with 0.33.1

I've created new JVMs as follows. Preliminary results indicate something changed in the openjdk code to cause these problems with OpenJ9.
- OpenJ9/OMR 0.33.1 and OpenJDK 0.35 https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_s390x_linux_Personal/428/OpenJ9-JDK8-s390x_linux-20220913-224331.tar.gz - both failures are reproduced
- OpenJ9/OMR 0.35 and OpenJDK 0.33.1 https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_s390x_linux_Personal/429/OpenJ9-JDK8-s390x_linux-20220913-234356.tar.gz - failures not reproduced
- 0.35 with FIPS support reverted https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_s390x_linux_Personal/430/OpenJ9-JDK8-s390x_linux-20220914-015706.tar.gz - both failures reproduced

I'll continue looking for suspect OpenJDK changes to try and isolate which change is causing the failures.

**Comment by pshipton** [comment]
- [8245263: Enable TLSv1.3 by default on JDK 8u for Client roles](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/3642cf4da59f38b11d8a3f14cec574c7eb86f3a8) - 
- no96f0 [8288763: Pack200 extraction failure with invalid size](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/96f0ca66d503f80ee2ffde20ea9448850767ac13) - fails
- no76ed [8214427: probable bug in logic of ConcurrentHashMap.addCount()](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/76ed082a40b780f2dc444cb326c3367e19308cd5) - fails

**Comment by pshipton** [comment]
I created another build where the only change is reverting the change to sun/security/ssl/SSLContextImpl.java from [8245263: Enable TLSv1.3 by default on JDK 8u for Client roles](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/3642cf4da59f38b11d8a3f14cec574c7eb86f3a8) and this seems to fix the problem. Not sure what's wrong with our TLSv1.3 support. I wonder if something we changed to support OpenSSL could have broken it? Backing out the FIPS changes didn't fix it, so those changes are not the issue. I'll see if I can back out OpenSSL support changes to resolve the problem. Otherwise I'm not sure where to go from here. @alon-sh in case you have any ideas.

**Comment by pshipton** [comment]
I can duplicate "Input record too big" failures on xlinux Temurin. This is not an OpenJ9 issue.
```
openjdk version "1.8.0_352-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-beta-202209121816-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.352-b05, mixed mode)
```
