### ISSUE TITLE
RHEL9 dacapo-sunflow_0_FAILED - RuntimeException: Unable to load reference frame!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15878]
[An internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27399/tapResults/)(`rhel9lert-1`)
```
10:41:20  java version "17.0.4.1" 2022-08-12
10:41:20  IBM Semeru Runtime Certified Edition 17.0.4.1 (build 17.0.4.1+1)
10:41:20  Eclipse OpenJ9 VM 17.0.4.1 (build openj9-0.33.1, JRE 17 Linux ppc64le-64-Bit Compressed References 20220811_204 (JIT enabled, AOT enabled)
10:41:20  OpenJ9   - 1d9d16830
10:41:20  OMR      - b58aa2708
10:41:20  JCL      - df9b7169bff based on jdk-17.0.4.1+1)

variation: NoOptions
JVM_OPTIONS:  
Using scaled threading model. 8 processors detected, 8 threads used to drive the workload, in a possible range of [1,256]
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.dacapo.harness.Sunflow.preIteration(Sunflow.java:52)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:171)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at Harness.main(Unknown Source)
Caused by: java.lang.RuntimeException: Unable to load reference frame!
	at org.sunflow.Benchmark.print(Benchmark.java:252)
	at org.sunflow.system.UI.printError(UI.java:63)
	at org.sunflow.Benchmark.<init>(Benchmark.java:99)
	... 14 more

dacapo-sunflow_0_FAILED
```

The `RuntimeException` appears from https://github.com/fpsunflower/sunflow/blob/15fa9c6cc6729934181bb877e67f1d1c13679f89/src/org/sunflow/Benchmark.java#L84-L86
```
        URL imageURL = Benchmark.class.getResource(String.format("/resources/golden_%04X.png", resolution));
        if (imageURL == null)
            UI.printError(Module.BENCH, "Unable to find reference frame!");
```

The test passes at [non-RHEL9 machine - ubu20le-rt1-9](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27413/)

_Originally posted by @JasonFengJ9 in https://github.com/eclipse-openj9/openj9/issues/14948#issuecomment-1244236208_

**Comment by pshipton** [comment]
@llxia this seems it could be a test problem, can somebody from test take the first look?

**Comment by llxia** [comment]
I am not aware of any specific settings needed for this test. In this test, we download dacapo.jar and run `sunflow`:
https://github.com/adoptium/aqa-tests/blob/f6c5451c2d13e3ed3a74f2cf0034fd6f3423a8f4/perf/dacapo/build.xml#L30
https://github.com/adoptium/aqa-tests/blob/f6c5451c2d13e3ed3a74f2cf0034fd6f3423a8f4/perf/dacapo/playlist.xml#L121

Dacapo benchmark is from https://github.com/dacapobench/dacapobench 

```
curl -Lks https://sourceforge.net/projects/dacapobench/files/latest/download -o dacapo.jar
java  -jar "/home/jenkins/workspace/Grinder_testList_0/aqa-tests/TKG/../../jvmtest/perf/dacapo/dacapo.jar" sunflow

**Comment by llxia** [comment]
2 rhel9 ppc64le machines are offline. [Internal infra issue](https://github.ibm.com/runtimes/infrastructure/issues/7252) is opened.

**Comment by pshipton** [comment]
I'm guessing the `resolution` is different on rhel9, and the needed resource `String.format("/resources/golden_%04X.png", resolution)` is not available. Otherwise I don't see why it would fail on rhel9 and not on other platforms.

**Comment by llxia** [comment]
This test only fails with JDK17 on rhel9 ppc64le. It passes with JDK11 on rhel9 ppc64le. And it also passes with both JDK11 and JDK17 on other rehel9 platforms (xlinux and s390). (see [internal issue](https://github.ibm.com/runtimes/backlog/issues/888))

**Comment by llxia** [comment]
Haven't seen this error for a while. Also, the test passed on `rhel9lert-2.hursley.ibm.com` in [Test_openjdk17_j9_extended.perf_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.perf_ppc64le_linux/78/).

Close this issue for now. Please reopen if this occurs again.
