### ISSUE TITLE
IllegalStateException: Could not resolve sufficient generic type information from the given function

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15884]
As reported by Syed, a regression was introduced between jdk8u312 (0.29) and jdk8u322 (0.30). With [0.30](https://github.com/eclipse-openj9/openj9/releases/tag/openj9-0.30.0) the following test case gives an exception, while with 0.29 there is no exception. The regression is also seen between 8.0.7.5 and [8.0.7.6](https://github.ibm.com/runtimes/openj9/releases/tag/Java8_SR7_FP6_20220303_0702_B23850) which narrows the number of changes.

```
Exception in thread "main" java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: Main$$Lambda$3/0x0000000000000000, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
	at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1136)
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1122)
	at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:900)
	at Main.main(Main.java:21)
```

```
import com.googlecode.cqengine.ConcurrentIndexedCollection;
import com.googlecode.cqengine.IndexedCollection;

import static com.googlecode.cqengine.index.navigable.NavigableIndex.onAttribute;
import static com.googlecode.cqengine.query.QueryFactory.attribute;

public class Main {
    static class Something {
        private final String name;

        public Something(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }
    public static void main(String[] args) {
        IndexedCollection<Something> somethings = new ConcurrentIndexedCollection<>();
        somethings.addIndex(onAttribute(attribute("name", Something::getName)));
        //System.out.println(somethings);
    }
}
```

JVMs
https://github.com/ibmruntimes/semeru8-binaries/releases/tag/jdk8u312-b07_openj9-0.29.0
https://github.com/ibmruntimes/semeru8-binaries/releases/tag/jdk8u322-b06_openj9-0.30.0

**Comment by pshipton** [comment]
Required prereq jars are found in /team/pshiptonj92/15884/, or ask me and I can Slack them.

@tobi fyi

**Comment by tajila** [comment]
This issue is most likely caused by the fact that TypeResolver (which cqengine uses) relies on private APIs, https://github.com/jhalterman/typetools/blob/master/src/main/java/net/jodah/typetools/TypeResolver.java

We need to take a look at what its not finding in openj9 and determine if we can make the equivalent available.

**Comment by tajila** [comment]
I believe this commit caused the issue https://github.com/eclipse-openj9/openj9/commit/3037ba8427b2b06021ebb4fecb7b5763ed0208f0

It changes `ConstantPool getConstantPool()` to `ConstantPool getConstantPool(Object internalCP)`

**Comment by tajila** [comment]
@mikezhang1234567890 Can you look at a way to enable `ConstantPool getConstantPool()`

**Comment by mikezhang1234567890** [comment]
Looking into it.

**Comment by mikezhang1234567890** [comment]
It looks like the it's an issue with the `typetools` 0.6.1 library. Updating it to 0.6.3 as found [here](https://search.maven.org/artifact/net.jodah/typetools/0.6.3/bundle) caused no exceptions when running the test file @pshipton attached.

**Comment by tajila** [comment]
@mikezhang1234567890 Yes, but it sounds like the customer is running 0.6.1. 

Im okay saying that the customer should update their dependencies, it is an unsupported API afterall. @pshipton what are your thoughts?
