### ISSUE TITLE
OpenJDK java/util/Properties/StoreDeadlock.java timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15881]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_Nightly/5
jdk_util_0
java/util/Properties/StoreDeadlock.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_Nightly/5/openjdk_test_output.tar.gz
```
23:27:02  ACTION: main -- Error. Agent error: java.lang.Exception: Agent 5 timed out with a timeout of 160 seconds; check console log for any additional details
23:27:02  REASON: User specified action: run main/timeout=20 StoreDeadlock 
23:27:02  TIME:   905.464 seconds
23:27:02  messages:
23:27:02  command: main StoreDeadlock
23:27:02  reason: User specified action: run main/timeout=20 StoreDeadlock 
23:27:02  Mode: agentvm
23:27:02  Agent id: 5
23:27:02  Timeout refired 160 times
23:27:02  Timeout information:
23:27:02  Running jcmd on process 6146
23:27:02  Timeout refired 300 times
23:27:02  Error getting data from 6146: Exception connecting to 6146
23:27:02  Usage : jcmd <vmid> <arguments>
23:27:02  
23:27:02     -J : supply arguments to the Java VM running jcmd
23:27:02     -l : list JVM processes on the local machine
23:27:02     -h : print this help message
23:27:02  
23:27:02     <vmid> : Attach API VM ID as shown in jps or other Attach API-based tools
23:27:02  
23:27:02     arguments:
23:27:02        help : print the list of diagnostic commands
23:27:02        help <command> : print help for the specific command
23:27:02        <command> [command arguments] : command from the list returned by "help"
23:27:02  
23:27:02  list JVM processes on the local machine. Default behavior when no options are specified.
23:27:02  
23:27:02  NOTE: this utility might significantly affect the performance of the target JVM.
23:27:02      The available diagnostic commands are determined by
23:27:02      the target VM and may vary between VMs.
23:27:02  Timeout handler interrupted: 
23:27:02  java.lang.InterruptedException
23:27:02  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1611)
23:27:02  	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:447)
23:27:02  	at jtreg.openj9.CoreDumpTimeoutHandler.runJcmdCommand(CoreDumpTimeoutHandler.java:117)
23:27:02  	at jtreg.openj9.CoreDumpTimeoutHandler.runJcmd(CoreDumpTimeoutHandler.java:137)
23:27:02  	at jtreg.openj9.CoreDumpTimeoutHandler.runActions(CoreDumpTimeoutHandler.java:55)
23:27:02  	at com.sun.javatest.regtest.TimeoutHandler.handleTimeout(TimeoutHandler.java:120)
23:27:02  	at com.sun.javatest.regtest.exec.Agent$5.run(Agent.java:388)
23:27:02  --- Timeout information end.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_Nightly/10

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_Nightly/21/
jdk_util_1
java/util/Properties/StoreDeadlock.java

**Comment by babsingh** [comment]
Closing, the test passes, and the failure was not seen recently. Reopen if the failure is seen again.
