### ISSUE TITLE
sun/security/tools/keytool/autotest.sh zlinux CKR_USER_TYPE_INVALID failure on rhel9

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15902]
Originally reported in https://github.com/eclipse-openj9/openj9/issues/15663#issuecomment-1232188736

[A similar internal failure](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_s390x_linux/82/consoleFull) (`rhel9s390xrt-2`) - another `rhel9`

```
openjdk version "1.8.0_352"
IBM Semeru Runtime Open Edition (build 1.8.0_352-b01)
Eclipse OpenJ9 VM (build master-1719d2e01, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20220826_434 (JIT enabled, AOT enabled)
OpenJ9   - 1719d2e01
OMR      - 938f0686f
JCL      - f2a9dfa9c based on jdk8u352-b01)

[2022-08-28T13:13:59.148Z] variation: Mode150
[2022-08-28T13:13:59.148Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-08-28T13:52:52.573Z] TEST: sun/security/tools/keytool/autotest.sh

[2022-08-28T13:52:52.573Z] ERR is:
[2022-08-28T13:52:52.573Z] 
[2022-08-28T13:52:52.573Z] OUT is:
[2022-08-28T13:52:52.573Z] keytool error: java.io.IOException: load failed
[2022-08-28T13:52:52.573Z] 
[2022-08-28T13:52:52.573Z] Exception in thread "main" java.io.IOException: load failed
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:764)
[2022-08-28T13:52:52.573Z] 	at java.security.KeyStore.load(KeyStore.java:1445)
[2022-08-28T13:52:52.573Z] 	at sun.security.tools.keytool.Main.doCommands(Main.java:869)
[2022-08-28T13:52:52.573Z] 	at sun.security.tools.keytool.Main.run(Main.java:378)
[2022-08-28T13:52:52.573Z] 	at sun.security.tools.keytool.Main.main(Main.java:371)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.test(KeyToolTest.java:159)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.test(KeyToolTest.java:127)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.testOK(KeyToolTest.java:182)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.testPKCS11(KeyToolTest.java:525)
[2022-08-28T13:52:52.573Z] 	at KeyToolTest.main(KeyToolTest.java:1345)
[2022-08-28T13:52:52.573Z] Caused by: javax.security.auth.login.LoginException
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1466)
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:864)
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:751)
[2022-08-28T13:52:52.573Z] 	... 9 more
[2022-08-28T13:52:52.573Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_TYPE_INVALID
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.wrapper.PKCS11.C_Login(Native Method)
[2022-08-28T13:52:52.573Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1450)
[2022-08-28T13:52:52.573Z] 	... 11 more

[2022-08-28T13:52:52.574Z] TEST RESULT: Failed. Execution failed: exit code 1
[2022-08-28T13:52:52.574Z] --------------------------------------------------
[2022-08-28T13:58:35.640Z] Test results: passed: 601; failed: 1
[2022-08-28T13:58:35.640Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16616889022357/jdk_security3_0/report/html/report.html
[2022-08-28T13:58:35.640Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16616889022357/jdk_security3_0/work
[2022-08-28T13:58:35.640Z] Error: Some tests failed or other problems occurred.
[2022-08-28T13:58:35.640Z] 
[2022-08-28T13:58:35.640Z] jdk_security3_0_FAILED
```

**Comment by pshipton** [comment]
Still fails on the test b05.

sun/security/tools/keytool/autotest.sh on rhel9x86-rt2-1 [grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27481/) (head) - still fails, but passed on another machine  (ub18x64rt1-1)

**Comment by pshipton** [comment]
Also on rhel9, head, try [xlinux grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27677) - failed same as above
and [plinux grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27678) - failed same as above

and [temurin xlinux](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27679) - failed same as above

Not an OpenJ9 issue.

**Comment by llxia** [comment]
Just for the record, same failure on rhel9 aarch64 JDK11 ([internal link](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/4/console))

```
00:10:16.763  java version "11.0.19" 2023-04-18
00:10:16.763  IBM Semeru Runtime Certified Edition 11.0.19.0-rc1 (build 11.0.19+7)
00:10:16.763  Eclipse OpenJ9 VM 11.0.19.0-rc1 (build v0.38.0-release-d57d05932, JRE 11 Linux aarch64-64-Bit Compressed References 20230501_301 (JIT enabled, AOT enabled)
00:10:16.763  OpenJ9   - d57d05932
00:10:16.763  OMR      - 855813495
00:10:16.763  JCL      - 1539bdcd45 based on jdk-11.0.19+7)
```
```
2023-05-02T17:19:55.127Z] loadProviderByName: SunPKCS11
[2023-05-02T17:19:55.127Z] keytool error: java.io.IOException: load failed
[2023-05-02T17:19:55.127Z] 
[2023-05-02T17:19:55.127Z] Exception in thread "main" java.io.IOException: load failed
[2023-05-02T17:19:55.127Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:765)
[2023-05-02T17:19:55.127Z] 	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
[2023-05-02T17:19:55.127Z] 	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1010)
[2023-05-02T17:19:55.127Z] 	at java.base/sun.security.tools.keytool.Main.run(Main.java:421)
[2023-05-02T17:19:55.127Z] 	at java.base/sun.security.tools.keytool.Main.main(Main.java:414)
[2023-05-02T17:19:55.127Z] 	at KeyToolTest.test(KeyToolTest.java:174)
[2023-05-02T17:19:55.127Z] 	at KeyToolTest.test(KeyToolTest.java:142)
[2023-05-02T17:19:55.127Z] 	at KeyToolTest.testOK(KeyToolTest.java:197)
[2023-05-02T17:19:55.127Z] 	at KeyToolTest.testPKCS11(KeyToolTest.java:687)
[2023-05-02T17:19:55.127Z] 	at KeyToolTest.main(KeyToolTest.java:1839)
[2023-05-02T17:19:55.127Z] Caused by: javax.security.auth.login.LoginException
[2023-05-02T17:19:55.127Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1616)
[2023-05-02T17:19:55.127Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:865)
[2023-05-02T17:19:55.127Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:752)
[2023-05-02T17:19:55.127Z] 	... 9 more
[2023-05-02T17:19:55.127Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_TYPE_INVALID
[2023-05-02T17:19:55.127Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1600)
[2023-05-02T17:19:55.127Z] 	... 11 more
```

**Comment by JasonFengJ9** [comment]
[JDK8 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_aarch64_linux/153/)(`rhel9-aarch64-3`)
```
openjdk version "1.8.0_392"
IBM Semeru Runtime Open Edition (build 1.8.0_392-b08)
Eclipse OpenJ9 VM (build v0.41.0-release-a803f004b, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20231116_775 (JIT enabled, AOT enabled)
OpenJ9   - a803f004b
OMR      - 5eee6ad9d
JCL      - b73cbdd342 based on jdk8u392-b08)

[2023-11-16T09:33:30.467Z] ERR is:
[2023-11-16T09:33:30.467Z] 
[2023-11-16T09:33:30.467Z] OUT is:
[2023-11-16T09:33:30.467Z] keytool error: java.io.IOException: load failed
[2023-11-16T09:33:30.467Z] 
[2023-11-16T09:33:30.467Z] Exception in thread "main" java.io.IOException: load failed
[2023-11-16T09:33:30.467Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:764)
[2023-11-16T09:33:30.467Z] 	at java.security.KeyStore.load(KeyStore.java:1445)
[2023-11-16T09:33:30.467Z] 	at sun.security.tools.keytool.Main.doCommands(Main.java:869)
[2023-11-16T09:33:30.467Z] 	at sun.security.tools.keytool.Main.run(Main.java:378)
[2023-11-16T09:33:30.467Z] 	at sun.security.tools.keytool.Main.main(Main.java:371)
[2023-11-16T09:33:30.467Z] 	at KeyToolTest.test(KeyToolTest.java:159)
[2023-11-16T09:33:30.467Z] 	at KeyToolTest.test(KeyToolTest.java:127)
[2023-11-16T09:33:30.467Z] 	at KeyToolTest.testOK(KeyToolTest.java:182)
[2023-11-16T09:33:30.467Z] 	at KeyToolTest.testPKCS11(KeyToolTest.java:525)
[2023-11-16T09:33:30.467Z] 	at KeyToolTest.main(KeyToolTest.java:1345)
[2023-11-16T09:33:30.467Z] Caused by: javax.security.auth.login.LoginException
[2023-11-16T09:33:30.467Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1534)
[2023-11-16T09:33:30.467Z] 	at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:864)
[2023-11-16T09:33:30.467Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:751)
[2023-11-16T09:33:30.467Z] 	... 9 more
[2023-11-16T09:33:30.467Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_TYPE_INVALID
[2023-11-16T09:33:30.467Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1518)
[2023-11-16T09:33:30.467Z] 	... 11 more

[2023-11-16T09:47:13.141Z] jdk_security3_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_extended.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_aarch64_linux_testList_0/324/)(`rtj-rhel10aarch64-svl-test-2`)
```
[2025-07-16T22:56:18.653Z] variation: Mode150
[2025-07-16T22:56:18.653Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-07-16T23:14:48.789Z] TEST: sun/security/tools/keytool/autotest.sh

[2025-07-16T23:14:48.790Z] Exception in thread "main" java.io.IOException: load failed
[2025-07-16T23:14:48.791Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:764)
[2025-07-16T23:14:48.791Z] 	at java.security.KeyStore.load(KeyStore.java:1445)
[2025-07-16T23:14:48.791Z] 	at sun.security.tools.keytool.Main.doCommands(Main.java:869)
[2025-07-16T23:14:48.791Z] 	at sun.security.tools.keytool.Main.run(Main.java:378)
[2025-07-16T23:14:48.791Z] 	at sun.security.tools.keytool.Main.main(Main.java:371)
[2025-07-16T23:14:48.791Z] 	at KeyToolTest.test(KeyToolTest.java:159)
[2025-07-16T23:14:48.791Z] 	at KeyToolTest.test(KeyToolTest.java:127)
[2025-07-16T23:14:48.791Z] 	at KeyToolTest.testOK(KeyToolTest.java:182)
[2025-07-16T23:14:48.791Z] 	at KeyToolTest.testPKCS11(KeyToolTest.java:525)
[2025-07-16T23:14:48.791Z] 	at KeyToolTest.main(KeyToolTest.java:1345)
[2025-07-16T23:14:48.791Z] Caused by: javax.security.auth.login.LoginException
[2025-07-16T23:14:48.791Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1539)
[2025-07-16T23:14:48.791Z] 	at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:864)
[2025-07-16T23:14:48.791Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:751)
[2025-07-16T23:14:48.791Z] 	... 9 more
[2025-07-16T23:14:48.791Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_TYPE_INVALID
[2025-07-16T23:14:48.791Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1523)
[2025-07-16T23:14:48.791Z] 	... 11 more

[2025-07-16T23:23:46.188Z] jdk_security3_0_FAILED
```

**Comment by hzongaro** [comment]
Saw an instance of this running an internal personal build:  [openjdk8_j9_extended.openjdk_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux_Personal/148)

```
[2025-10-22T20:47:12.163Z] Test fails for the command ---
[2025-10-22T20:47:12.163Z] keytool -J-Dnss.lib=/usr/lib64/libsoftokn3.so -keystore NONE -storetype PKCS11 -providerName SunPKCS11-nss -providerClass sun.security.pkcs11.SunPKCS11 -providerArg p11-nss.txt -storepass test12 -list
[2025-10-22T20:47:12.163Z] Or its debug version ---
[2025-10-22T20:47:12.163Z] keytool -debug -J-Dnss.lib=/usr/lib64/libsoftokn3.so -keystore NONE -storetype PKCS11 -providerName SunPKCS11-nss -providerClass sun.security.pkcs11.SunPKCS11 -providerArg p11-nss.txt -storepass test12 -list
[2025-10-22T20:47:12.163Z] The command result should be OK, but it's not. Try run the command manually and type these input into it: 
[2025-10-22T20:47:12.163Z] 
[2025-10-22T20:47:12.163Z] ERR is:
[2025-10-22T20:47:12.163Z] 
[2025-10-22T20:47:12.163Z] OUT is:
[2025-10-22T20:47:12.163Z] keytool error: java.io.IOException: load failed
[2025-10-22T20:47:12.163Z] 
[2025-10-22T20:47:12.163Z] Exception in thread "main" java.io.IOException: load failed
[2025-10-22T20:47:12.163Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:764)
[2025-10-22T20:47:12.163Z] 	at java.security.KeyStore.load(KeyStore.java:1445)
[2025-10-22T20:47:12.163Z] 	at sun.security.tools.keytool.Main.doCommands(Main.java:869)
[2025-10-22T20:47:12.163Z] 	at sun.security.tools.keytool.Main.run(Main.java:378)
[2025-10-22T20:47:12.163Z] 	at sun.security.tools.keytool.Main.main(Main.java:371)
[2025-10-22T20:47:12.163Z] 	at KeyToolTest.test(KeyToolTest.java:159)
[2025-10-22T20:47:12.163Z] 	at KeyToolTest.test(KeyToolTest.java:127)
[2025-10-22T20:47:12.163Z] 	at KeyToolTest.testOK(KeyToolTest.java:182)
[2025-10-22T20:47:12.163Z] 	at KeyToolTest.testPKCS11(KeyToolTest.java:525)
[2025-10-22T20:47:12.163Z] 	at KeyToolTest.main(KeyToolTest.java:1345)
[2025-10-22T20:47:12.163Z] Caused by: javax.security.auth.login.LoginException
[2025-10-22T20:47:12.163Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1539)
[2025-10-22T20:47:12.163Z] 	at sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:864)
[2025-10-22T20:47:12.163Z] 	at sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:751)
[2025-10-22T20:47:12.163Z] 	... 9 more
[2025-10-22T20:47:12.163Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_TYPE_INVALID
[2025-10-22T20:47:12.163Z] 	at sun.security.pkcs11.wrapper.PKCS11.C_Login(Native Method)
[2025-10-22T20:47:12.163Z] 	at sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1523)
[2025-10-22T20:47:12.163Z] 	... 11 more
```
