### ISSUE TITLE
testDDRExt_Class_0 failed to detect 32-bit on Windows 32

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15915]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_0/362
testDDRExt_Class_0
```
00:13:22       [java] [DDRExtTesterBase] [INFO] Validation started for : '!dumpramclasslinear 0x22244E00'[DDRExtTesterBase] [ERROR] '!setvm 18446744073709551615' output contains common failure key : DDRInteractiveCommandException
00:13:22       [java] [DDRExtTesterBase] [ERROR] '!setvm 18446744073709551615' output :
00:13:22       [java] Problem running command:
00:13:22       [java] com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: 18446744073709551615 is larger than the max available memory address: 0xFFFFFFFF (4294967295)
00:13:22       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.CommandUtils.parsePointer(CommandUtils.java:74)
00:13:22       [java] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.SetVMCommand.run(SetVMCommand.java:87)
00:13:22       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
00:13:22       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
00:13:22       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:182)
00:13:22       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:361)
00:13:22       [java] [DDRExtTesterBase] [INFO] Validation passed for : '!dumpramclasslinear 0x22244E00'
00:13:22       [java] 	at j9vm.test.ddrext.DDRExtTesterBase.exec(DDRExtTesterBase.java:97)
00:13:22       [java] 	at j9vm.test.ddrext.DDRExtTesterBase.is64BitPlatform(DDRExtTesterBase.java:468)
00:13:22       [java] 	at j9vm.test.ddrext.junit.TestClassExt.testDumpAllSegmentsExt(TestClassExt.java:259)
00:13:22       [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:13:22       [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:13:22       [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:13:22       [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
00:13:22       [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
00:13:22       [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
00:13:22       [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
00:13:22       [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
00:13:22       [java] 	at junit.framework.TestResult.run(TestResult.java:113)
00:13:22       [java] 	at junit.framework.TestCase.run(TestCase.java:124)
00:13:22       [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
00:13:22       [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
00:13:22       [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
00:13:22       [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
00:13:22       [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
00:13:22       [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
00:13:22       [java] 
00:13:22       [java] [DDRExtTesterBase] [ERROR] '!setvm 18446744073709551615' output does not contain success key : segment.+start.+warmAlloc.+coldAlloc.+end.+size.+
00:13:22       [java] [DDRExtTesterBase] [ERROR] '!setvm 18446744073709551615' output :memorySegments - !j9memorysegmentlist 0x710de0
...
00:13:22       [java] junit.framework.AssertionFailedError[AutoRun] [INFO] Finished testDumpAllClassLoadersExt(j9vm.test.ddrext.junit.TestClassExt)
00:13:22       [java] 	at junit.framework.Assert.fail(Assert.java:48)
00:13:22       [java] 
00:13:22       [java] 
00:13:22       [java] [AutoRun] [INFO] ================Test Result for C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_0\aqa-tests\TKG\output_1663385924712\testDDRExt_Class_0\DDREXT.J9CORE.DMP==================	at junit.framework.Assert.assertTrue(Assert.java:20)
00:13:22       [java] [AutoRun] [INFO] Errors:   0 out of 20 test cases.
00:13:22       [java] 
00:13:22       [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
00:13:22       [java] [AutoRun] [INFO] Failures: 1 out of 20 test cases.
00:13:22       [java] [AutoRun] [INFO] Total Error/Failures: 1
00:13:22       [java] 	at j9vm.test.ddrext.junit.TestClassExt.testDumpAllSegmentsExt(TestClassExt.java:266)
```

`output does not contain success key : segment.+start.+warmAlloc.+coldAlloc.+end.+size.+` is the DUMP_ALL_SEGMENTS_64BITCORE_SUCCESS_KEY rather than 32 bit success key. is64BitPlatform() intentionally tries to set a 64 bit value to detect 32 bit.

```
	public boolean is64BitPlatform() {
		String setVMOutput = exec(Constants.SETVM_CMD, new String[] { CommandUtils.UDATA_MAX_64BIT.toString() });
		boolean is64BitPlatform = true;
		/* If it is 32-bit platform, then it will complain about address being too large. */
		if (validate(setVMOutput, "is larger than the max available memory address: 0xFFFFFFFF", null)) {
			is64BitPlatform = false;
		}
		return is64BitPlatform;
	}
```

@keithc-ca fyi
There are no diagnostics / core file captured due to https://github.com/adoptium/aqa-tests/issues/3864#issuecomment-1251062749

**Comment by pshipton** [comment]
Similar [internal failure](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=42937261) on Linux 64-bit 

I think https://github.com/eclipse-openj9/openj9/pull/15890 is affecting the tests.
