### ISSUE TITLE
Loom: timeout in Skynet running compressedrefs

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15938]
See https://github.com/eclipse-openj9/openj9/issues/15152#issuecomment-1251743982

**Comment by babsingh** [comment]
@fengxue-IS Can this be closed since https://github.com/eclipse-openj9/openj9/pull/15965 is merged?

**Comment by fengxue-IS** [comment]
Lets keep this open to track the `-Xcompressedrefs` issue. We can close this once [#15184](https://github.com/eclipse-openj9/openj9/issues/15184) is completed

**Comment by thallium** [comment]
I'm getting timed out with and without JIT enabled
```
"main" prio=5 Id=2 WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.lang.Thread.join(Thread.java:2146)
        at java.base@19-internal/java.lang.Thread.join(Thread.java:2222)
        at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:72)

"Common-Cleaner" prio=8 Id=3 TIMED_WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
        at java.base@19-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
        at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)
        at java.base@19-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)

"GC Worker" prio=5 Id=4 RUNNABLE

"GC Worker" prio=5 Id=5 RUNNABLE

"GC Worker" prio=5 Id=6 RUNNABLE

"GC Worker" prio=5 Id=7 RUNNABLE

"GC Worker" prio=5 Id=8 RUNNABLE

"GC Worker" prio=5 Id=9 RUNNABLE

"GC Worker" prio=5 Id=10 RUNNABLE

"Attach API wait loop" prio=10 Id=13 RUNNABLE
        at java.base@19-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
        at java.base@19-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)

"MainThread" prio=5 Id=15 WAITING
        at java.base@19-internal/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@19-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
        at java.base@19-internal/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3744)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3689)
        at java.base@19-internal/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
        at java.base@19-internal/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
        at app//Skynet$Channel.receive(Skynet.java:110)
        at app//Skynet.skynet(Skynet.java:60)
        at app//Skynet.main(Skynet.java:50)
        at java.base@19-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base@19-internal/java.lang.reflect.Method.invoke(Method.java:578)
        at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
        at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)

"ForkJoinPool-1-worker-5" prio=5 Id=42 RUNNABLE
        at java.base@19-internal/java.lang.VirtualThread.notifyJvmtiUnmountEnd(Native Method)
        at java.base@19-internal/java.lang.VirtualThread.afterTerminate(VirtualThread.java:424)
        at java.base@19-internal/java.lang.VirtualThread.runContinuation(VirtualThread.java:221)
        at java.base@19-internal/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base@19-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
        at java.base@19-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"Finalizer thread" prio=5 Id=13711 RUNNABLE

"file lock watchdog" prio=10 Id=143797 TIMED_WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.util.TimerThread.mainLoop(Timer.java:563)
        at java.base@19-internal/java.util.TimerThread.run(Timer.java:516)

"Attachment portNumber: 42685" prio=10 Id=145433 RUNNABLE
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
        at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
        at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
```

**Comment by fengxue-IS** [comment]
Moving this out of Java19 milestone as compressedrefs work on relocating to above 4G memory space in #15184 isn't blocker for Java 19

**Comment by babsingh** [comment]
Closing since Skynet timeouts are no longer seen. This was resolved by increasing the -Xmx value for the test and the various VM/GC performance optimizations. The remaining performance tasks, which will further proactively mitigate timeouts, have standalone issues; and they can be tracked through the [Java 21 milestone](https://github.com/eclipse-openj9/openj9/milestone/45):
