### ISSUE TITLE
Loom: failure in parking tests

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15940]
```
FAILED	java/lang/Thread/virtual/Parking.java
			Total tests run: 22, Passes: 19, Failures: 2, Skips: 1
			test Parking.testPark11(): failure
				java.lang.RuntimeException: java.lang.AssertionError
					at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:77)
					at java.base/java.lang.VirtualThread.run(VirtualThread.java:292)
					at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:179)
					at java.base/jdk.internal.vm.Continuation.execute(Continuation.java:171)
				Caused by: java.lang.AssertionError
					at java.base/java.lang.VirtualThread.park(VirtualThread.java:509)
					at java.base/java.lang.Access.parkVirtualThread(Access.java:501)
					at java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:54)
					at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:369)
					at Parking.lambda$testPark11$8(Parking.java:193)
					at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:75)
					... 3 more
			test Parking.testPark4(): skip
				org.testng.SkipException: Not implemented
					at Parking.testPark4(Parking.java:87)
			test Parking.testParkNanos11(): failure
				java.lang.IllegalStateException: Continuation is pinned: MONITOR
					at java.base/jdk.internal.vm.Continuation.yield(Continuation.java:230)
					at java.base/java.lang.VirtualThread.yieldContinuation(VirtualThread.java:375)
					at java.base/java.lang.VirtualThread.parkNanos(VirtualThread.java:537)
					at java.base/java.lang.Access.parkVirtualThread(Access.java:509)
					at java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:67)
					at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:408)
					at Parking.lambda$testParkNanos11$20(Parking.java:342)
					at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:75)
					at java.base/java.lang.VirtualThread.run(VirtualThread.java:292)
					at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:179)
					at java.base/jdk.internal.vm.Continuation.execute(Continuation.java:171)
```

**Comment by tajila** [comment]
@fengxue-IS can this be closed now?

**Comment by fengxue-IS** [comment]
yes, closing this as test passes with current master
