### ISSUE TITLE
testClassLoadingDelegation testParallelIncapableDelegation AssertionError: Threads did not deadlock

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15966]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/318
testClassLoadingDelegation_0
```
FAILED: testParallelIncapableDelegation
java.lang.AssertionError: Threads did not deadlock
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/389
testClassLoadingDelegation_0

```
FAILED: testParallelIncapableDelegation
java.lang.AssertionError: Threads did not deadlock
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_s390x_linux_Nightly_testList_1/97
testClassLoadingDelegation_0
```
FAILED: testParallelIncapableDelegation
java.lang.AssertionError: Threads did not deadlock
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/421
testClassLoadingDelegation_0
```
FAILED: testParallelIncapableDelegation
java.lang.AssertionError: Threads did not deadlock
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/457

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/526

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_1/61

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/61
```
FAILED: testDelegatedClassLoading
java.lang.AssertionError: Deadlock detected
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_aot_Personal_testList_0/137

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/511
testClassLoadingDelegation_0
```
FAILED: testParallelIncapableDelegation
java.lang.AssertionError: Threads did not deadlock
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly/17/tapResults/
```
variation: NoOptions
JVM_OPTIONS:

FAILED: testParallelIncapableDelegation
java.lang.AssertionError: Threads did not deadlock
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
testClassLoadingDelegation_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/588/
testClassLoadingDelegation_0
```
FAILED: testParallelIncapableDelegation
java.lang.AssertionError: Threads did not deadlock
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/534

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/30

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/83

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/113/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/162

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/667

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/736

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/743

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/689

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/705

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_extended.functional_s390x_linux_Nightly_testList_0/4

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Release_testList_1/114

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_extended.functional_s390x_linux_Nightly_testList_0/82

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/946

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/963

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_extended.functional_s390x_linux_Nightly_testList_0/82/consoleFull
```
05:25:59  variation: NoOptions
05:25:59  JVM_OPTIONS:  

05:26:05  FAILED: testParallelIncapableDelegation
05:26:05  java.lang.AssertionError: Threads did not deadlock
05:26:05  	at org.testng.Assert.fail(Assert.java:96)
05:26:05  	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
05:26:05  	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
05:26:05  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
05:26:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
05:26:05  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
05:26:05  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
05:26:05  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
05:26:05  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
05:26:05  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
05:26:05  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
05:26:05  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
05:26:05  	at org.testng.TestRunner.run(TestRunner.java:505)
05:26:05  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
05:26:05  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
05:26:05  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
05:26:05  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
05:26:05  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
05:26:05  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
05:26:05  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
05:26:05  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
05:26:05  	at org.testng.TestNG.runSuites(TestNG.java:1049)
05:26:05  	at org.testng.TestNG.run(TestNG.java:1017)
05:26:05  	at org.testng.TestNG.privateMain(TestNG.java:1354)
05:26:05  	at org.testng.TestNG.main(TestNG.java:1323)
05:26:05  
05:26:05  
05:26:05  ===============================================
05:26:05      testClassLoadingDelegation
05:26:05      Tests run: 2, Failures: 1, Skips: 0
05:26:05  ===============================================

05:26:06  testClassLoadingDelegation_0_FAILED
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_extended.functional_s390x_linux_Nightly_testList_0/120/consoleFull
```
04:43:42  Running test testClassLoadingDelegation_0 ...
04:43:42  ===============================================
04:43:42  testClassLoadingDelegation_0 Start Time: Tue Jul 15 08:43:42 2025 Epoch Time (ms): 1752569022733
04:43:42  variation: NoOptions
04:43:42  JVM_OPTIONS:  

04:43:45  FAILED: testParallelIncapableDelegation
04:43:45  java.lang.AssertionError: Threads did not deadlock
04:43:45  	at org.testng.Assert.fail(Assert.java:96)
04:43:45  	at org.openj9.test.delegation.ClassLoadingDelegationTest.runDelegationTest(ClassLoadingDelegationTest.java:101)
04:43:45  	at org.openj9.test.delegation.ClassLoadingDelegationTest.testParallelIncapableDelegation(ClassLoadingDelegationTest.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_extended.functional_s390x_linux_Nightly_testList_1/11
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/559
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/1152
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/621
