### ISSUE TITLE
OpenJDK java/util/logging/TestLoggerBundleSync.java - Test threw exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15972]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly/367
jdk_util_0 
java/util/logging/TestLoggerBundleSync.java

```
23:32:19  STDOUT:
23:32:19  No security
23:32:19  4002 ms elapsed (4000 requested)
23:32:19  Passed: 346 unique loggers created
23:32:19  	 8156 loggers tested by 3 Thread(s),
23:32:19  	 8549 resource bundles set by 3 Thread(s),
23:32:19  	 8592 resource bundle names set by 3 Thread(s),
23:32:19  	 2493 log messages emitted by other GetRB threads were ignored to ensure MT test consistency,
23:32:19  	 ThreadMXBean.findDeadlockedThreads called 34 times by 1 Thread.
23:32:19  
23:32:19  With security
23:32:19  550 ms elapsed (4000 requested)
23:32:19  STDERR:
23:32:19  Sep 26, 2022 11:32:08 PM TestLoggerBundleSync$Stopper run
23:32:19  INFO: 4000ms remaining...
23:32:19  Sep 26, 2022 11:32:09 PM TestLoggerBundleSync$Stopper run
23:32:19  INFO: 2910ms remaining...
23:32:19  Sep 26, 2022 11:32:10 PM TestLoggerBundleSync$Stopper run
23:32:19  INFO: 1875ms remaining...
23:32:19  Sep 26, 2022 11:32:11 PM TestLoggerBundleSync$Stopper run
23:32:19  INFO: 854ms remaining...
23:32:19  Sep 26, 2022 11:32:12 PM TestLoggerBundleSync$Stopper run
23:32:19  INFO: 4000ms remaining...
23:32:19  java.lang.NullPointerException
23:32:19  	at java.base/java.lang.String.startsWith(String.java:2524)
23:32:19  	at java.base/java.lang.String.startsWith(String.java:2508)
23:32:19  	at TestLoggerBundleSync$GetRB.run(TestLoggerBundleSync.java:315)
23:32:19  java.lang.NullPointerException
23:32:19  	at java.base/java.lang.String.startsWith(String.java:2524)
23:32:19  	at java.base/java.lang.String.startsWith(String.java:2508)
23:32:19  	at TestLoggerBundleSync$GetRB.run(TestLoggerBundleSync.java:315)
23:32:19  
23:32:19  JavaTest Message: Test threw exception: java.lang.NullPointerException
23:32:19  JavaTest Message: shutting down test
23:32:19  
23:32:19  STATUS:Failed.`main' threw exception: java.lang.NullPointerException
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/376
jdk_util_0
java/util/logging/TestLoggerBundleSync.java
```
22:37:23  STDOUT:
22:37:23  No security
22:37:23  4015 ms elapsed (4000 requested)
22:37:23  Passed: 29 unique loggers created
22:37:23  	 594 loggers tested by 3 Thread(s),
22:37:23  	 613 resource bundles set by 3 Thread(s),
22:37:23  	 612 resource bundle names set by 3 Thread(s),
22:37:23  	 65 log messages emitted by other GetRB threads were ignored to ensure MT test consistency,
22:37:23  	 ThreadMXBean.findDeadlockedThreads called 31 times by 1 Thread.
22:37:23  
22:37:23  With security
22:37:23  STDERR:
22:37:23  Sep 26, 2022 9:36:55 PM TestLoggerBundleSync$Stopper run
22:37:23  INFO: 4000ms remaining...
22:37:23  Sep 26, 2022 9:36:56 PM TestLoggerBundleSync$Stopper run
22:37:23  INFO: 2907ms remaining...
22:37:23  Sep 26, 2022 9:36:57 PM TestLoggerBundleSync$Stopper run
22:37:23  INFO: 1875ms remaining...
22:37:23  Sep 26, 2022 9:36:58 PM TestLoggerBundleSync$Stopper run
22:37:23  INFO: 844ms remaining...
22:37:23  Sep 26, 2022 9:36:59 PM TestLoggerBundleSync$Stopper run
22:37:23  INFO: 4000ms remaining...
22:37:23  Sep 26, 2022 9:37:00 PM TestLoggerBundleSync$Stopper run
22:37:23  INFO: 2985ms remaining...
22:37:23  00000000001C4C00: Object neither in heap nor stack-allocated in thread Thread-10
22:37:23  00000000001C4C00:	O-Slot=0000005DB0AFF4F0
22:37:23  000000000026F200: Object neither in heap nor stack-allocated in thread Thread-9
22:37:23  000000000026F200:	O-Slot=0000005DB09FF800
22:37:23  000000000026F200:	O-Slot value=0000000000401373
22:37:23  00000000001C4C00:	O-Slot value=0000000000401373
22:37:23  000000000026F200:	PC=00007FFC5BBA0A63
22:37:23  00000000001C4C00:	PC=00007FFC5BBA0A63
22:37:23  000000000026F200:	framesWalked=1
22:37:23  00000000001C4C00:	framesWalked=1
22:37:23  000000000026F200:	arg0EA=0000000000363E20
22:37:23  00000000001C4C00:	arg0EA=00000000002CD730
22:37:23  000000000026F200:	walkSP=0000000000363CE8
22:37:23  00000000001C4C00:	walkSP=00000000002CD5F8
22:37:23  000000000026F200:	literals=0000000000000010
22:37:23  00000000001C4C00:	literals=0000000000000010
22:37:23  00000000001C4C00:	jitInfo=0000005DAF0D3768
22:37:23  000000000026F200:	jitInfo=0000005DAF0D3768
22:37:23  00000000001C4C00:	method=0000000000203E30 (TestLoggerBundleSync$GetRB.run()V) (JIT)
22:37:23  000000000026F200:	method=0000000000203E30 (TestLoggerBundleSync$GetRB.run()V) (JIT)
22:37:23  00000000001C4C00:	stack=00000000002C6700-00000000002CD790
22:37:23  000000000026F200:	stack=000000000035CDF0-0000000000363E80
22:37:23  02:37:00.446 0x1a7700    j9mm.479    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Nightly\openj9\runtime\gc_glue_java\MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))
```

**Comment by pshipton** [comment]
Changes: https://github.com/eclipse-openj9/openj9/compare/2fb03381c44...f1d05969c84

**Comment by pshipton** [comment]
Closing, assuming fixed by https://github.com/eclipse-openj9/openj9/pull/15978
