### ISSUE TITLE
JDK19 serviceability_jvmti_j9_0_FAILED serviceability/jvmti/GetLocalVariable/GetLocalVars.java - RuntimeException: Test GetLocalVars failed with a bad status: 2

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15983]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux/10/)(`rhel9x86-rt2-1`):
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+36 (build 19+36)
Eclipse OpenJ9 VM 19+36 (build master-784820387, JRE 19 Linux amd64-64-Bit Compressed References 20220920_45 (JIT enabled, AOT enabled)
OpenJ9   - 784820387
OMR      - 24b511df5
JCL      - 4efd563f9c based on jdk-19+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-09-24-15-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-09-25T07:43:03.014Z] variation: Mode150
[2022-09-25T07:43:03.014Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-09-25T07:43:52.053Z] TEST: serviceability/jvmti/GetLocalVariable/GetLocalVars.java

[2022-09-25T07:43:52.054Z] STDOUT:
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  test_local_byte: BEGIN
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  GetLocalInt: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  GetLocalInt got value from a local byte as expected
[2022-09-25T07:43:52.054Z]  GetLocalLong: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  FAIL: GetLocalLong failed to return JVMTI_ERROR_INVALID_SLOT for local byte
[2022-09-25T07:43:52.054Z]  GetLocalFloat: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  GetLocalFloat got value from a local byte as expected
[2022-09-25T07:43:52.054Z]  GetLocalDouble: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  FAIL: GetLocalDouble failed to return JVMTI_ERROR_INVALID_SLOT for local byte
[2022-09-25T07:43:52.054Z]  GetLocalObject: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  FAIL: GetLocalObject failed to return JVMTI_ERROR_TYPE_MISMATCH for local byte
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  test_local_byte: END
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  test_local_object: BEGIN
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  GetLocalInt: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  FAIL: GetLocalInt failed to return JVMTI_ERROR_TYPE_MISMATCH for local object
[2022-09-25T07:43:52.054Z]  GetLocalLong: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  FAIL: GetLocalLong failed to return JVMTI_ERROR_TYPE_MISMATCH for local object
[2022-09-25T07:43:52.054Z]  GetLocalFloat: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  FAIL: GetLocalFloat failed to return JVMTI_ERROR_TYPE_MISMATCH for local object
[2022-09-25T07:43:52.054Z]  GetLocalDouble: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  FAIL: GetLocalDouble failed to return JVMTI_ERROR_TYPE_MISMATCH for local object
[2022-09-25T07:43:52.054Z]  GetLocalObject: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  GetLocalObject got value from a local object as expected
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  test_local_object: END
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  test_local_double: BEGIN
[2022-09-25T07:43:52.054Z] 
[2022-09-25T07:43:52.054Z]  GetLocalInt: JVMTI error (0)
[2022-09-25T07:43:52.054Z]  GetLocalInt got value from a local double as expected
[2022-09-25T07:43:52.054Z]  GetLocalLong: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  GetLocalLong got value from a local double as expected
[2022-09-25T07:43:52.055Z]  GetLocalFloat: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  GetLocalFloat got value from a local double as expected
[2022-09-25T07:43:52.055Z]  GetLocalDouble: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  GetLocalDouble got value from a local double as expected
[2022-09-25T07:43:52.055Z]  GetLocalObject: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  FAIL: GetLocalObject failed to return JVMTI_ERROR_TYPE_MISMATCH for local double
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z]  test_local_double: END
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z]  test_local_integer: BEGIN
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z]  GetLocalInt: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  GetLocalInt got value from a local int as expected
[2022-09-25T07:43:52.055Z]  GetLocalFloat: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  GetLocalFloat got value from a local int as expected
[2022-09-25T07:43:52.055Z]  GetLocalObject: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  FAIL: GetLocalObject failed to return JVMTI_ERROR_TYPE_MISMATCH for local double
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z]  test_local_integer: END
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z]  test_local_invalid: BEGIN
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z]  GetLocalInt: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  FAIL: GetLocalInt failed to return JVMTI_ERROR_INVALID_SLOT for local invalid
[2022-09-25T07:43:52.055Z]  GetLocalLong: JVMTI error (35)
[2022-09-25T07:43:52.055Z]  GetLocalLong returned JVMTI_ERROR_INVALID_SLOT for local invalid as expected
[2022-09-25T07:43:52.055Z]  GetLocalFloat: JVMTI error (0)
[2022-09-25T07:43:52.055Z]  FAIL: GetLocalFloat failed to return JVMTI_ERROR_INVALID_SLOT for local invalid
[2022-09-25T07:43:52.055Z]  GetLocalDouble: JVMTI error (35)
[2022-09-25T07:43:52.055Z]  GetLocalDouble returned JVMTI_ERROR_INVALID_SLOT for local invalid as expected
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z]  test_local_invalid: END
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z] STDERR:
[2022-09-25T07:43:52.055Z] java.lang.RuntimeException: Test GetLocalVars failed with a bad status: 2
[2022-09-25T07:43:52.055Z] 	at GetLocalVars.main(GetLocalVars.java:52)
[2022-09-25T07:43:52.055Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-09-25T07:43:52.055Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-09-25T07:43:52.055Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-25T07:43:52.055Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-09-25T07:43:52.055Z] 
[2022-09-25T07:43:52.055Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Test GetLocalVars failed with a bad status: 2

[2022-09-25T07:48:25.964Z] serviceability_jvmti_j9_0_FAILED
```

**Comment by hangshao0** [comment]
Looks like dup of https://github.com/eclipse-openj9/openj9/issues/15920

**Comment by JasonFengJ9** [comment]
Agreed
