### ISSUE TITLE
serviceability_jvmti_j9_0_FAILED - serviceability/jvmti/HiddenClass/P/Q/HiddenClassSigTest.java - RuntimeException: FAIL: failed status from native agent

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15984]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux/10/)(`rhel9x86-rt2-1`):
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+36 (build 19+36)
Eclipse OpenJ9 VM 19+36 (build master-784820387, JRE 19 Linux amd64-64-Bit Compressed References 20220920_45 (JIT enabled, AOT enabled)
OpenJ9   - 784820387
OMR      - 24b511df5
JCL      - 4efd563f9c based on jdk-19+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-09-24-15-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-09-25T07:43:03.014Z] variation: Mode150
[2022-09-25T07:43:03.014Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-09-25T07:43:34.307Z] TEST: serviceability/jvmti/events/VMObjectAlloc/vmobjalloc01/vmobjalloc01.java

03:43:34  STDOUT:
03:43:34  Timeout: 60000 msc
03:43:34  STDERR:
03:43:34  JVMJ9TI064E Agent initialization function Agent_OnLoad failed for library vmobjalloc01, return code -1
03:43:34  JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed

[2022-09-25T07:43:57.506Z] TEST: serviceability/jvmti/HiddenClass/P/Q/HiddenClassSigTest.java

[2022-09-25T07:43:57.508Z] STDOUT:
[2022-09-25T07:43:57.508Z] Agent_OnLoad: started
[2022-09-25T07:43:57.508Z] Agent_OnLoad: finished
[2022-09-25T07:43:57.508Z] VMInit event: SIG_START: LP/Q/HiddenClassSig, SIG_START_LEN: 19
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: started
[2022-09-25T07:43:57.508Z] ClassLoad event: hidden class with sig: LP/Q/HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.508Z] ClassLoad event: hidden class with gsig: <T:Ljava/lang/Object;>Ljava/lang/Object;LP/Q/HCInterf<TT;>;
[2022-09-25T07:43:57.508Z] ClassPrepare event: hidden class with sig: LP/Q/HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.508Z] ClassPrepare event: hidden class with gsig: <T:Ljava/lang/Object;>Ljava/lang/Object;LP/Q/HCInterf<TT;>;
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: hc.hcMethod() returned string: HiddenClassSig: Test generic hidden class
[2022-09-25T07:43:57.508Z] 
[2022-09-25T07:43:57.508Z] ### Testing class: class P.Q.HiddenClassSig/0x0000000000000000
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: isHidden:  true
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: getName:   P.Q.HiddenClassSig/0x0000000000000000
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: typeName:  P.Q.HiddenClassSig/0x0000000000000000
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: toString:  class P.Q.HiddenClassSig/0x0000000000000000
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: toGenStr:  class P.Q.HiddenClassSig/0x0000000000000000<T>
[2022-09-25T07:43:57.508Z] HiddenClassSigTest: elem type: null
[2022-09-25T07:43:57.508Z] 
[2022-09-25T07:43:57.509Z] ### Native agent: check_hidden_class started: class: LP/Q/HiddenClassSig.0x0000000000000000;
[2022-09-25T07:43:57.509Z] check_class_signature: class with sig: LP/Q/HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] check_class_signature: class with gsig: <T:Ljava/lang/Object;>Ljava/lang/Object;LP/Q/HCInterf<TT;>;
[2022-09-25T07:43:57.509Z] check_class_signature: FAIL: Hidden class signature LP/Q/HiddenClassSig/0x0000000000000000; does not match expected: LP/Q/HiddenClassSig.0x0000000000000000;
[2022-09-25T07:43:57.509Z] 
[2022-09-25T07:43:57.509Z] ### Testing class: class [LP.Q.HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: isHidden:  false
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: getName:   [LP.Q.HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: typeName:  P.Q.HiddenClassSig/0x0000000000000000[]
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: toString:  class [LP.Q.HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: toGenStr:  P.Q.HiddenClassSig/0x0000000000000000<T>[]
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: elem type: class P.Q.HiddenClassSig/0x0000000000000000
[2022-09-25T07:43:57.509Z] 
[2022-09-25T07:43:57.509Z] ### Native agent: check_hidden_class_array started: array: [LP/Q/HiddenClassSig.0x0000000000000000;
[2022-09-25T07:43:57.509Z] check_class_signature: class with sig: [LP/Q/HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] check_class_signature: class with gsig: (null)
[2022-09-25T07:43:57.509Z] check_class_signature: FAIL: Hidden class signature [LP/Q/HiddenClassSig/0x0000000000000000; does not match expected: [LP/Q/HiddenClassSig.0x0000000000000000;
[2022-09-25T07:43:57.509Z] 
[2022-09-25T07:43:57.509Z] ### Testing class: class [[LP.Q.HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: isHidden:  false
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: getName:   [[LP.Q.HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: typeName:  P.Q.HiddenClassSig/0x0000000000000000[][]
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: toString:  class [[LP.Q.HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: toGenStr:  P.Q.HiddenClassSig/0x0000000000000000<T>[][]
[2022-09-25T07:43:57.509Z] HiddenClassSigTest: elem type: class [LP.Q.HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] 
[2022-09-25T07:43:57.509Z] ### Native agent: check_hidden_class_array started: array: [[LP/Q/HiddenClassSig.0x0000000000000000;
[2022-09-25T07:43:57.509Z] check_class_signature: class with sig: [[LP/Q/HiddenClassSig/0x0000000000000000;
[2022-09-25T07:43:57.509Z] check_class_signature: class with gsig: (null)
[2022-09-25T07:43:57.509Z] check_class_signature: FAIL: Hidden class signature [[LP/Q/HiddenClassSig/0x0000000000000000; does not match expected: [[LP/Q/HiddenClassSig.0x0000000000000000;
[2022-09-25T07:43:57.509Z] STDERR:
[2022-09-25T07:43:57.509Z] java.lang.RuntimeException: FAIL: failed status from native agent
[2022-09-25T07:43:57.509Z] 	at P.Q.HiddenClassSigTest.main(HiddenClassSigTest.java:247)
[2022-09-25T07:43:57.509Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-09-25T07:43:57.509Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-09-25T07:43:57.509Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-25T07:43:57.509Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-09-25T07:43:57.509Z] 
[2022-09-25T07:43:57.509Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: FAIL: failed status from native agent

[2022-09-25T07:48:25.964Z] serviceability_jvmti_j9_0_FAILED
```

**Comment by hangshao0** [comment]
> Hidden class signature LP/Q/HiddenClassSig/0x0000000000000000; does not match expected: LP/Q/HiddenClassSig.0x0000000000000000;

I believe `jvmtiGetClassSignature()` needs to be updated to covert the last `/` into `.` on hidden/anon classes,

**Comment by babsingh** [comment]
@hangshao0 Did you try the fix; does it work?

**Comment by hangshao0** [comment]
No, I haven't tried. BTW, this is not something new in JDK19. We have the same behavior in JDK17. It failed in JDK19 because we just start running this test from JDK19.

**Comment by hangshao0** [comment]
@ehrenjulzert, can you look at this ? See https://github.com/eclipse-openj9/openj9/issues/15984#issuecomment-1259958165 for the potential fix.

**Comment by ehrenjulzert** [comment]
sure, I can look at this

**Comment by hangshao0** [comment]
You can use 
https://github.com/eclipse-openj9/openj9/blob/16ae18675d476a7577bdcffb7f6a82ae1e0d7230/runtime/oti/j9modifiers_api.h#L60

to check if a class is a hidden or anonymous class.

**Comment by ehrenjulzert** [comment]
It looks like my changes have solved this specific test failure, however there are still 36 tests within `serviceability_jvmti_j9_0` that are failing (None of which were introduced by my fix). Is our goal here just to fix this one test, or to also fix the other 36 failing tests in `serviceability_jvmti_j9_0`?

**Comment by hangshao0** [comment]
> Is our goal here just to fix this one test, or to also fix the other 36 failing tests in serviceability_jvmti_j9_0?

You need to fix this test (`HiddenClassSigTest.java`) tracked by this issue only.

**Comment by babsingh** [comment]
@ehrenjulzert I see the FIX (https://github.com/eclipse-openj9/openj9/pull/16100) was merged. Can you please re-enable the failing test if it was excluded, and close this issue?

I don't see this test disabled in either
- https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk19-openj9.txt; or
- https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk20-openj9.txt.
@JasonFengJ9 Was the test disabled differently?

**Comment by JasonFengJ9** [comment]
> Was the test disabled differently?

@babsingh this test wasn't disabled.

It passed in [latest run](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux/23/consoleFull) as per `aqa-tests/TKG/output_16671496798297/serviceability_jvmti_j9_1/work/serviceability/jvmti/events/VMObjectAlloc/vmobjalloc01/vmobjalloc01.jtr`.

Closing
