### ISSUE TITLE
JDK19 serviceability_jvmti_j9_0_FAILED serviceability/jvmti/VMObjectAlloc/VMObjectAllocTest.java Exception: Number of allocation != 1

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15994]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux/10/)(`rhel9x86-rt2-1`):
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+36 (build 19+36)
Eclipse OpenJ9 VM 19+36 (build master-784820387, JRE 19 Linux amd64-64-Bit Compressed References 20220920_45 (JIT enabled, AOT enabled)
OpenJ9   - 784820387
OMR      - 24b511df5
JCL      - 4efd563f9c based on jdk-19+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-09-24-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F45%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-09-24-15-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-09-25T07:43:03.014Z] variation: Mode150
[2022-09-25T07:43:03.014Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-09-25T07:48:13.524Z] TEST: serviceability/jvmti/VMObjectAlloc/VMObjectAllocTest.java

[2022-09-25T07:48:13.548Z] STDERR:
[2022-09-25T07:48:13.548Z] java.lang.Exception: Number of allocation != 1
[2022-09-25T07:48:13.548Z] 	at VMObjectAllocTest.main(VMObjectAllocTest.java:50)
[2022-09-25T07:48:13.548Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-09-25T07:48:13.548Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-09-25T07:48:13.548Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-25T07:48:13.548Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-09-25T07:48:13.548Z] 
[2022-09-25T07:48:13.548Z] JavaTest Message: Test threw exception: java.lang.Exception: Number of allocation != 1

[2022-09-25T07:48:25.964Z] serviceability_jvmti_j9_0_FAILED
```

**Comment by JasonFengJ9** [comment]
@tajila This test `serviceability/jvmti/VMObjectAlloc/VMObjectAllocTest.java` is available since `JDK18`. Its extension repo hasn't been setup to run `serviceability_jvmti_j9` yet, am going to try it maunally.

**Comment by JasonFengJ9** [comment]
Test JDK18 0.33 w/ [Adoptium testimage](https://github.com/adoptium/temurin18-binaries/releases/download/jdk18u-2022-10-04-01-30-beta/OpenJDK18U-testimage_x64_mac_hotspot_2022-10-03-23-30.tar.gz)
```
"/Users/ivm/ive/semeru/jdk-18.0.2+9/Contents/Home/bin/java" -version
openjdk version "18.0.2" 2022-07-19
IBM Semeru Runtime Open Edition 18.0.2.0 (build 18.0.2+9)
Eclipse OpenJ9 VM 18.0.2.0 (build openj9-0.33.0, JRE 18 Mac OS X amd64-64-Bit Compressed References 20220804_38 (JIT enabled, AOT enabled)
OpenJ9   - 04a55b45b
OMR      - b58aa2708
JCL      - dff9c97e1c7 based on jdk-18.0.2+9)

===============================================
Running test serviceability_jvmti_j9_0 ...
===============================================
serviceability_jvmti_j9_0 Start Time: Wed Oct  5 16:15:25 2022 Epoch Time (ms): 1665000925000
"/Users/ivm/ive/semeru/jdk-18.0.2+9/Contents/Home/bin/java" -Xshareclasses:destroyAll; "/Users/ivm/ive/semeru/jdk-18.0.2+9/Contents/Home/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";

Attempting to destroy all caches in cacheDir /Users/jasonfeng/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_jasonfeng" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC005I No shared class caches available
cache cleanup done
variation: Mode150
JVM_OPTIONS:  -XX:+UseCompressedOops 

TEST: serviceability/jvmti/VMObjectAlloc/VMObjectAllocTest.java

STDERR:
java.lang.Exception: Number of allocation != 1
	at VMObjectAllocTest.main(VMObjectAllocTest.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
	at java.base/java.lang.Thread.run(Thread.java:858)

JavaTest Message: Test threw exception: java.lang.Exception: Number of allocation != 1
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Exception: Number of allocation != 1

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Number of allocation != 1
--------------------------------------------------
Test results: failed: 1
Report written to /Users/ivm/semeru-tests/jdk18-1004/jvmtest/openjdk/report/html/report.html
Results written to /Users/ivm/semeru-tests/jdk18-1004/aqa-tests/TKG/output_16650009243567/serviceability_jvmti_j9_0/work
Error: Some tests failed or other problems occurred.

serviceability_jvmti_j9_0_FAILED
```

This is not a regression introduced by JDK19.

**Comment by tajila** [comment]
@JasonFengJ9  Thanks, Can you take a look at the other xerviceability test failures as well. I'd like to separate them from the jdk19 issues

**Comment by JasonFengJ9** [comment]
Sure, will look into them.
