### ISSUE TITLE
JDK20+ should exclude/modify tests using java.lang.Thread.suspend()/resume() and stop()

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16028]
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/488#issuecomment-1265749227
```
+++ j9vm.test.clinit.BlockDuringClinitTest: +++
command: /root/hostdir/jdknext_openj9_cmk_ppc64le_v09/bin/java  
-Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m    
-classpath /root/hostdir/openj9_tests/openj9/test/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar
:/root/hostdir/openj9_tests/openj9/test/TKG/../TKG/lib/asm-all.jar  j9vm.test.clinit.BlockDuringClinitTest

<clinit> vs. new...
Exception in thread "main" java.lang.UnsupportedOperationException
        at java.base/java.lang.Thread.stop(Thread.java:1647)
        at j9vm.test.clinit.NewDuringClinit.test(NewDuringClinit.java:108)
        at j9vm.test.clinit.BlockDuringClinitTest.run(BlockDuringClinitTest.java:30)
        at j9vm.test.clinit.BlockDuringClinitTest.main(BlockDuringClinitTest.java:44)
```

**Comment by JasonFengJ9** [comment]
Closing as dup of https://github.com/eclipse-openj9/openj9/issues/16213#event-7725489770
