### ISSUE TITLE
Java 19 java/lang/ClassLoader/Assert.java timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16030]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly/19/
jdk_lang_0 
java/lang/ClassLoader/Assert.java

```
22:08:47  ACTION: main -- Error. Program `F:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 964594ms).
22:08:47  REASON: User specified action: run main/othervm Assert 
22:08:47  TIME:   964.61 seconds
22:08:47  messages:
22:08:47  command: main Assert
22:08:47  reason: User specified action: run main/othervm Assert 
22:08:47  Mode: othervm [/othervm specified]
22:08:47  Timeout information:
22:08:47  Running jcmd on process 7452
22:08:47  Dump written to F:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_1664589088580\jdk_lang_0\work\scratch\1\core.20220930.210842.7452.0001.dmp
22:08:47  Dump written to F:\Users\jenkins\workspace\Test_openjdk19_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_1664589088580\jdk_lang_0\work\scratch\1\javacore.20220930.210844.7452.0002.txt
22:08:47  Running jstack on process 7452
22:08:47  2022-09-30T21:08:45.578589400
22:08:47  Virtual machine: 7452 JVM information:
22:08:47  JRE 19 Windows Server 2012 R2 amd64-64-Bit Compressed References 20220930_89 (JIT enabled, AOT enabled)
22:08:47  OpenJ9   - 710fd952924
22:08:47  OMR      - f99c9dd
22:08:47  JCL      - 05db3773ec3 based on jdk-19+36
22:08:47  
22:08:47  "main" prio=5 Id=2 WAITING
22:08:47  	at java.base@19-internal/java.lang.Object.wait(Native Method)
22:08:47  	at java.base@19-internal/java.lang.Object.wait(Object.java:219)
22:08:47  	at java.base@19-internal/java.lang.Thread.join(Thread.java:2146)
22:08:47  	at java.base@19-internal/java.lang.Thread.join(Thread.java:2222)
22:08:47  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
22:08:47  
22:08:47  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
22:08:47  
22:08:47  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
22:08:47  
22:08:47  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
22:08:47  
22:08:47  "JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
22:08:47  
22:08:47  "JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE
22:08:47  
22:08:47  "JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE
22:08:47  
22:08:47  "JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE
22:08:47  
22:08:47  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE
22:08:47  
22:08:47  "JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING
22:08:47  
22:08:47  "IProfiler" prio=5 Id=13 RUNNABLE
22:08:47  
22:08:47  "Common-Cleaner" prio=8 Id=3 TIMED_WAITING
22:08:47  	at java.base@19-internal/java.lang.Object.wait(Native Method)
22:08:47  	at java.base@19-internal/java.lang.Object.wait(Object.java:219)
22:08:47  	at java.base@19-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
22:08:47  	at java.base@19-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
22:08:47  	at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)
22:08:47  	at java.base@19-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
22:08:47  
22:08:47  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
22:08:47  
22:08:47  "GC Worker" prio=5 Id=15 RUNNABLE
22:08:47  
22:08:47  "GC Worker" prio=5 Id=16 RUNNABLE
22:08:47  
22:08:47  "GC Worker" prio=5 Id=17 RUNNABLE
22:08:47  
22:08:47  "GC Worker" prio=5 Id=18 RUNNABLE
22:08:47  
22:08:47  "GC Worker" prio=5 Id=19 RUNNABLE
22:08:47  
22:08:47  "GC Worker" prio=5 Id=20 RUNNABLE
22:08:47  
22:08:47  "GC Worker" prio=5 Id=21 RUNNABLE
22:08:47  
22:08:47  "Attach API wait loop" prio=10 Id=24 RUNNABLE
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
22:08:47  
22:08:47  "Finalizer thread" prio=5 Id=25 RUNNABLE
22:08:47  
22:08:47  "MainThread" prio=5 Id=27 RUNNABLE
22:08:47  	at java.base@19-internal/java.lang.ProcessImpl.waitForInterruptibly(Native Method)
22:08:47  	at java.base@19-internal/java.lang.ProcessImpl.waitFor(ProcessImpl.java:569)
22:08:47  	at app//Assert.main(Assert.java:100)
22:08:47  	at java.base@19-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:08:47  	at java.base@19-internal/java.lang.reflect.Method.invoke(Method.java:578)
22:08:47  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:08:47  	at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)
22:08:47  
22:08:47  "file lock watchdog" prio=10 Id=29 TIMED_WAITING
22:08:47  	at java.base@19-internal/java.lang.Object.wait(Native Method)
22:08:47  	at java.base@19-internal/java.lang.Object.wait(Object.java:219)
22:08:47  	at java.base@19-internal/java.util.TimerThread.mainLoop(Timer.java:563)
22:08:47  	at java.base@19-internal/java.util.TimerThread.run(Timer.java:516)
22:08:47  
22:08:47  "Attachment portNumber: 53739" prio=10 Id=31 RUNNABLE
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
22:08:47  	at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
22:08:47  
22:08:47  
22:08:47  --- Timeout information end.
22:08:47  elapsed time (seconds): 964.61
22:08:47  configuration:
22:08:47  STDOUT:
22:08:47  Timeout refired 960 times
```

**Comment by tajila** [comment]
@hangshao0 please take a look at this

**Comment by hangshao0** [comment]
I will have a look.

**Comment by hangshao0** [comment]
Re-run the test 100 times on the latest Windows nightly build, all passed.

**Comment by hangshao0** [comment]
The test spawn a new Java process and it is waiting for the new Java process to finish. It timeout on the wait. Not sure what happened to the spawned Java process. 

The spawned Java process is running `Assert.class` with an argument, so it is running this piece of code:
https://github.com/hangshao0/openj9-openjdk-jdk19/blob/7a09e8a7a5bef0dcde7080a30b446e428fdc74b7/test/jdk/java/lang/ClassLoader/Assert.java#L124-L129

, which is pretty simple and unlikely to hang.

**Comment by hangshao0** [comment]
Notice the test is using `j.l.Runtime.exec(String)` to spawn the new Java process. However, this method has been deprecated since Java 18 and its Javadoc says `"This method is error-prone and should not be used"`.

**Comment by hangshao0** [comment]
Also looks like https://github.com/eclipse-openj9/openj9/issues/15327, which is on Linux_x86-64 though.
