### ISSUE TITLE
JDK8 aarch64_linux LambdaLoadTest_special_J9_5m_0_FAILED net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16032]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_aarch64_linux_testList_0/306/)(`cent7-aarch64-6`):
```
openjdk version "1.8.0_352"
IBM Semeru Runtime Open Edition (build 1.8.0_352-b06)
Eclipse OpenJ9 VM (build openj9-0.35.0-m2b, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20221002_460 (JIT enabled, AOT enabled)
OpenJ9   - 2e24c0da7
OMR      - 447afc0f0
JCL      - fa9321797d based on jdk8u352-b06)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=LambdaLoadTest_special_J9_5m_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F460%2Fibm-semeru-open-jdk_aarch64_linux_8u352b06_openj9-0.35.0-m2b.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F460%2Fibm-semeru-open-testimage_aarch64_linux_8u352b06_openj9-0.35.0-m2b.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F460%2Fibm-semeru-open-debugimage_aarch64_linux_8u352b06_openj9-0.35.0-m2b.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F460%2Fibm-semeru-open-jre_aarch64_linux_8u352b06_openj9-0.35.0-m2b.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=v0.35.0-release&amp;OPENJ9_BRANCH=v0.35.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.35.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=324&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-10-02T09:31:20.245Z] variation: Mode101
[2022-10-02T09:31:20.245Z] JVM_OPTIONS: -Xdump:system:events=user

[2022-10-02T09:31:48.368Z] LT  05:31:44.806 - Test failed
[2022-10-02T09:31:48.368Z] LT    Failure num.  = 1
[2022-10-02T09:31:48.368Z] LT    Test number   = 5
[2022-10-02T09:31:48.368Z] LT    Test details  = 'JUnit[net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces]'
[2022-10-02T09:31:48.368Z] LT    Suite number  = 0
[2022-10-02T09:31:48.368Z] LT    Thread number = 3
[2022-10-02T09:31:48.368Z] LT  >>> Captured test output >>>
[2022-10-02T09:31:48.368Z] LT  testStarted : testSupplierMotorbike(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
[2022-10-02T09:31:48.368Z] LT  testFinished: testSupplierMotorbike(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
[2022-10-02T09:31:48.368Z] LT  testStarted : testComparatorString(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
[2022-10-02T09:31:48.368Z] LT  testFinished: testComparatorString(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
[2022-10-02T09:31:48.368Z] LT  testStarted : testSupplierPerson(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
[2022-10-02T09:31:48.368Z] LT  testFinished: testSupplierPerson(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces)
[2022-10-02T09:31:48.368Z] LT  testStarted : testSupplierString(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface)
[2022-10-02T09:31:48.368Z] LT  testFailure: testSupplierString(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testSupplierString" not found
[2022-10-02T09:31:48.368Z] LT  junit.framework.AssertionFailedError: Method "testSupplierString" not found
[2022-10-02T09:31:48.368Z] LT  	at junit.framework.Assert.fail(Assert.java:57)
[2022-10-02T09:31:48.368Z] LT  	at junit.framework.TestCase.fail(TestCase.java:227)
[2022-10-02T09:31:48.368Z] LT  	at junit.framework.TestCase.runTest(TestCase.java:169)

[2022-10-02T09:31:48.368Z] LT  testFailure: testFunctionMotorbike(net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface): Method "testFunctionMotorbike" not found
[2022-10-02T09:31:48.368Z] LT  junit.framework.AssertionFailedError: Method "testFunctionMotorbike" not found

[2022-10-02T09:31:48.370Z] LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces
[2022-10-02T09:31:48.370Z] LT    Ran    : 13
[2022-10-02T09:31:48.370Z] LT    Passed : 3
[2022-10-02T09:31:48.370Z] LT    Failed : 10
[2022-10-02T09:31:48.370Z] LT    Ignored: 0
[2022-10-02T09:31:48.370Z] LT    Result : FAILED

[2022-10-02T09:32:06.881Z] LambdaLoadTest_special_J9_5m_0_FAILED
```

[15x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28316) - passed

**Comment by pshipton** [comment]
Seems a dup of https://github.com/eclipse-openj9/openj9/issues/15832

@knn-k fyi

**Comment by pshipton** [comment]
The grinder passing, closing as dup.
