### ISSUE TITLE
JDK19 java/lang/Thread/virtual/stress/PingPong.java failed with JIT enabled

### ISSUE THREAD

**Issue by thallium** [eclipse-openj9/openj9#16047]
```
STDOUT:
1735 1735
1735 1735
1735 1735
1735 1735
1735 1735
1735 1735
STDERR:
19:17:59.416 0x26f700    j9vm.226    *   ** ASSERTION FAILED ** at /root/openj9-openjdk-jdk19/openj9/runtime/vm/ContinuationHelpers.cpp:142: ((currentThread->currentContinuation) != NULL)
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/10/05 12:17:59 - please wait.
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FC37903EF10 Handler2=00007FC378428F40 InaccessibleAddress=0000000000000000
RDI=00007FC2D4000BC0 RSI=00007FC379407740 RAX=0000000000276E18 RBX=0000000000000000
RCX=00007FC3791D41C4 RDX=00000007061FB328 R8=00007FC35137B348 R9=0000000000000001
R10=0000000000000000 R11=00007FC370E4D810 R12=00000000000002E4 R13=0000000000000000
R14=00007FC35137B850 R15=0000000000000000
RIP=00007FC379096A32 GS=0000 FS=0000 RSP=00007FC35137B440
EFlags=0000000000010202 CS=0033 RBP=000000000028A000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
xmm0 0000000000000001 (f: 1.000000, d: 4.940656e-324)
xmm1 00000000000002e4 (f: 740.000000, d: 3.656086e-321)
xmm2 0000000000289c08 (f: 2661384.000000, d: 1.314898e-317)
xmm3 00000000001c2c00 (f: 1846272.000000, d: 9.121796e-318)
xmm4 00007fc3791c3e6a (f: 2031894144.000000, d: 6.940512e-310)
xmm5 00007fc3791c3e7e (f: 2031894144.000000, d: 6.940512e-310)
xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 0000000000000004 (f: 4.000000, d: 1.976263e-323)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/root/openj9-openjdk-jdk19/build/linux-x86_64-server-release/images/jdk/lib/default/libj9vm29.so
Module_base_address=00007FC379000000
Target=2_90_20220930_000000 (Linux 5.15.0-48-generic)
CPU=amd64 (8 logical CPUs) (0x3e8090000 RAM)
----------- Stack Backtrace -----------
JVMDUMP032I JVM requested System dump using '/root/openj9-openjdk-jdk19/jtreg/build/images/JTwork/scratch/core.20221005.121759.725453.0001.dmp' in response to an event
yieldContinuation+0x32 (0x00007FC379096A32 [libj9vm29.so+0x96a32])
_ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x76e4 (0x00007FC37909E694 [libj9vm29.so+0x9e694])
bytecodeLoopCompressed+0xad (0x00007FC379096F9D [libj9vm29.so+0x96f9d])
 (0x00007FC379141742 [libj9vm29.so+0x141742])
---------------------------------------
```

**Comment by babsingh** [comment]
The above is triggered in [yieldContinuation](https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/ContinuationHelpers.cpp#L143). `currentThread->currentContinuation` is expected to be non-null.

Also, observed the assertion in [enterContinuation](https://github.com/eclipse-openj9/openj9/blob/b28092a380bc55418fd8b1816c25dcf8ab13cb00/runtime/vm/ContinuationHelpers.cpp#L98) trigger during local runs. Here, `currentThread->currentContinuation` is expected to be null. `currentThread->currentContinuation` already points to the virtual thread that is being mounted.

**So, it looks like [enterContinuation](https://github.com/eclipse-openj9/openj9/blob/b28092a380bc55418fd8b1816c25dcf8ab13cb00/runtime/vm/ContinuationHelpers.cpp#L98) and [yieldContinuation](https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/ContinuationHelpers.cpp#L143) is being called twice by the same J9VMThread. This triggers the assertions within these functions.**

Java stack:
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/vm/Continuation.enterImpl(Native Method)
4XESTACKTRACE                at jdk/internal/vm/Continuation.run(Continuation.java:199)
4XESTACKTRACE                at java/lang/VirtualThread.runContinuation(VirtualThread.java:218)
```

Native stack:
```
#12 doTracePoint (thr=<optimized out>, modInfo=modInfo@entry=0x7f8aeef08740 <j9vm_UtModuleInfo>, traceId=traceId@entry=4342531, spec=spec@entry=0x7f8aeecd5012 "\377\004\377",
    varArgs=varArgs@entry=0x7f8ac7c763d8) at /root/openj9-openjdk-jdk/openj9/runtime/rastrace/trclog.c:2207
#13 0x00007f8aeda52915 in javaTrace (env=<optimized out>, modInfo=0x7f8aeef08740 <j9vm_UtModuleInfo>, traceId=4342531, spec=0x7f8aeecd5012 "\377\004\377")
    at /root/openj9-openjdk-jdk/openj9/runtime/rastrace/trcengine.c:1306
#14 0x00007f8aeeb976d4 in enterContinuation (currentThread=0x28e500, continuationObject=0xd0233ba0) at /root/openj9-openjdk-jdk/openj9/runtime/vm/ContinuationHelpers.cpp:98
#15 0x00007f8aeeb9f80e in VM_BytecodeInterpreterCompressed::enterContinuationImpl (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /root/openj9-openjdk-jdk/openj9/runtime/vm/BytecodeInterpreter.hpp:5211
#16 VM_BytecodeInterpreterCompressed::run (this=0x7f8ac7c768f0, vmThread=0x0) at /root/openj9-openjdk-jdk/openj9/runtime/vm/BytecodeInterpreter.hpp:10715
#17 0x00007f8aeeb97f9d in bytecodeLoopCompressed (currentThread=<optimized out>) at /root/openj9-openjdk-jdk/openj9/runtime/vm/BytecodeInterpreter.inc:112
#18 0x00007f8aeec42742 in c_cInterpreter () at /root/openj9-openjdk-jdk/build/linux-x86_64-server-release/vm/runtime/vm/xcinterp.s:158
#19 0x00007f8aeeb1d47a in runJavaThread (currentThread=0x0, currentThread@entry=0x28e500) at /root/openj9-openjdk-jdk/openj9/runtime/vm/callin.cpp:682
#20 0x00007f8aeeb96d6d in javaProtectedThreadProc (portLibrary=portLibrary@entry=0x7f8aef358380 <j9portLibrary>, entryarg=entryarg@entry=0x28e500)
    at /root/openj9-openjdk-jdk/openj9/runtime/vm/vmthread.cpp:2093
```

DDR:
```
> !j9vmthread 0x0028e500
J9VMThread at 0x28e500 {
  Fields for J9VMThread:
	0xa8: struct J9Object* threadObject = !j9object 0x00000000D0233AE8 // java/lang/VirtualThread
        ...
	0xa08: struct J9VMContinuation* currentContinuation = !j9vmcontinuation 0x00007F8A6C02E080
	0xa10: UDATA continuationPinCount = 0x0000000000000000 (0)
	0xa18: UDATA ownedMonitorCount = 0x0000000000000000 (0)
	0xa20: UDATA callOutCount = 0x0000000000000000 (0)
	0xa28: struct J9Object* carrierThreadObject = !j9object 0x00000000D0281958 // jdk/internal/misc/CarrierThread
	0xa30: struct J9Object* extentLocalCache = !j9object 0x0000000000000000
}

> !j9object 0xd0233ba0
!J9Object 0x00000000D0233BA0 {
	struct J9Class* clazz = !j9class 0x24C200 // java/lang/VirtualThread$VThreadContinuation
	Object flags = 0x00000000;
	I lockword = 0x00000000 (offset = 0) (java/lang/Object) <hidden>
	J vmRef = 0x00007F8A6C02E080 (offset = 4) (jdk/internal/vm/Continuation)
	Ljdk/internal/vm/ContinuationScope; scope = !fj9object 0xd01d3310 (offset = 12) (jdk/internal/vm/Continuation)
	Ljava/lang/Runnable; runnable = !fj9object 0xd0233bd0 (offset = 16) (jdk/internal/vm/Continuation)
	Ljdk/internal/vm/Continuation; parent = !fj9object 0x0 (offset = 20) (jdk/internal/vm/Continuation)
	Z started = 0x00000001 (offset = 24) (jdk/internal/vm/Continuation)
	Z finished = 0x00000000 (offset = 28) (jdk/internal/vm/Continuation)
	Z isAccessible = 0x00000000 (offset = 32) (jdk/internal/vm/Continuation)
	I continuationLink = 0xD0204830 (offset = 36) (jdk/internal/vm/Continuation) <hidden>
}

> !j9vmcontinuation 0x00007F8A6C02E080
J9VMContinuation at 0x7f8a6c02e080 {
  Fields for J9VMContinuation:
	0x0: UDATA* arg0EA = !j9x 0x000000000028E008
	0x8: UDATA* bytecodes = !j9x 0x0000000000000000
	0x10: UDATA* sp = !j9x 0x000000000028DFE0
	0x18: U8* pc = !j9x 0x0000000000000003
	0x20: struct J9Method* literals = !j9method 0x0000000000000000
	0x28: UDATA* stackOverflowMark = !j9x 0x000000000028DBC0
	0x30: UDATA* stackOverflowMark2 = !j9x 0x000000000028DBC0
	0x38: struct J9JavaStack* stackObject = !j9javastack 0x000000000028B3B8
	0x40: struct J9JITDecompilationInfo* decompilationStack = !j9jitdecompilationinfo 0x0000000000000000
	0x48: UDATA* j2iFrame = !j9x 0x000000000028E0D0
	0x50: struct J9JITGPRSpillArea jitGPRs = !j9jitgprspillarea 0x00007F8A6C02E0D0
	0xd0: struct J9VMEntryLocalStorage* oldEntryLocalStorage = !j9vmentrylocalstorage 0x0000000000000000
}

> !j9object 0x00000000D0233AE8
!J9Object 0x00000000D0233AE8 {
	struct J9Class* clazz = !j9class 0x95900 // java/lang/VirtualThread
	Object flags = 0x00000008;
	I lockword = 0x00000000 (offset = 0) (java/lang/Object) <hidden>
	J eetop = 0x0000000000000000 (offset = 4) (java/lang/Thread)
	J tid = 0x000000000000001C (offset = 12) (java/lang/Thread)
	Ljava/lang/String; name = !fj9object 0xd0015638 (offset = 36) (java/lang/Thread)
	Z interrupted = 0x00000000 (offset = 92) (java/lang/Thread)
	Ljava/lang/ClassLoader; contextClassLoader = !fj9object 0xd0035398 (offset = 40) (java/lang/Thread)
	Ljava/security/AccessControlContext; inheritedAccessControlContext = !fj9object 0xd02043d8 (offset = 44) (java/lang/Thread)
	Ljava/lang/Thread$FieldHolder; holder = !fj9object 0x0 (offset = 48) (java/lang/Thread)
	Ljava/lang/ThreadLocal$ThreadLocalMap; threadLocals = !fj9object 0x0 (offset = 52) (java/lang/Thread)
	Ljava/lang/ThreadLocal$ThreadLocalMap; inheritableThreadLocals = !fj9object 0x0 (offset = 56) (java/lang/Thread)
	Ljava/lang/Object; extentLocalBindings = !fj9object 0x0 (offset = 60) (java/lang/Thread)
	Ljava/lang/Object; interruptLock = !fj9object 0xd0233b90 (offset = 64) (java/lang/Thread)
	Ljava/lang/Object; parkBlocker = !fj9object 0x0 (offset = 68) (java/lang/Thread)
	Lsun/nio/ch/Interruptible; nioBlocker = !fj9object 0x0 (offset = 72) (java/lang/Thread)
	Ljdk/internal/vm/Continuation; cont = !fj9object 0x0 (offset = 76) (java/lang/Thread)
	Ljava/lang/Thread$UncaughtExceptionHandler; uncaughtExceptionHandler = !fj9object 0x0 (offset = 80) (java/lang/Thread)
	J threadLocalRandomSeed = 0x0000000000000000 (offset = 20) (java/lang/Thread)
	I threadLocalRandomProbe = 0x00000000 (offset = 96) (java/lang/Thread)
	I threadLocalRandomSecondarySeed = 0x00000000 (offset = 100) (java/lang/Thread)
	Ljdk/internal/vm/ThreadContainer; container = !fj9object 0xd01f9940 (offset = 84) (java/lang/Thread)
	Ljdk/internal/vm/StackableScope; headStackableScopes = !fj9object 0x0 (offset = 88) (java/lang/Thread)
	Z started = 0x00000000 (offset = 104) (java/lang/Thread)
	Z stopCalled = 0x00000000 (offset = 108) (java/lang/Thread)
	J tls = 0x0000000000000000 (offset = 28) (java/lang/Thread) <hidden>
	Ljava/util/concurrent/Executor; scheduler = !fj9object 0xd01f9b38 (offset = 124) (java/lang/VirtualThread)
	Ljdk/internal/vm/Continuation; cont = !fj9object 0xd0233ba0 (offset = 128) (java/lang/VirtualThread)
	Ljava/lang/Runnable; runContinuation = !fj9object 0xd0233be0 (offset = 132) (java/lang/VirtualThread)
	I state = 0x00000003 (offset = 112) (java/lang/VirtualThread)
	Z parkPermit = 0x00000000 (offset = 152) (java/lang/VirtualThread)
	Ljava/lang/Thread; carrierThread = !fj9object 0xd0281958 (offset = 136) (java/lang/VirtualThread)
	Ljava/util/concurrent/CountDownLatch; termination = !fj9object 0x0 (offset = 140) (java/lang/VirtualThread)
	I isSuspendedByJVMTI = 0x00000000 (offset = 156) (java/lang/VirtualThread) <hidden>
}
```

**Comment by fengxue-IS** [comment]
```
OpenJDK Runtime Environment (build 19-internal-adhoc.root.openj9-openjdk-jdk19)
Eclipse OpenJ9 VM (build cont_i2j-87ad9cf84, JRE 19 Linux amd64-64-Bit Compressed References 20220720_000000 (JIT enabled, AOT enabled)
OpenJ9   - 87ad9cf84
OMR      - 13b523796
JCL      - 9c604b08545 based on jdk-19+36)
Running tests using JTREG control variable 'JAVA_OPTIONS=-Dvm.continuations=true -Xgcpolicy:optthruput'
Test selection 'java/lang/Thread/virtual/stress/PingPong.java', will run:
* jtreg:test/jdk/java/lang/Thread/virtual/stress/PingPong.java

Running test 'jtreg:test/jdk/java/lang/Thread/virtual/stress/PingPong.java'
Passed: java/lang/Thread/virtual/stress/PingPong.java
Test results: passed: 1
```

looks like #16062 is related to this failure

**Comment by fengxue-IS** [comment]
is this test intermittent?

**Comment by thallium** [comment]
On my side it still failed, my jdk info:
```
OpenJDK Runtime Environment (build 19-internal-adhoc..openj9-openjdk-jdk19)
Eclipse OpenJ9 VM (build master-b7f44aa1a, JRE 19 Linux amd64-64-Bit Compressed References 20221006_000000 (JIT enabled, AOT enabled)
OpenJ9   - 7d076b59a
OMR      - 773e9b51a
JCL      - 908867442a7 based on jdk-19+36)
```

**Comment by thallium** [comment]
> @thallium does this still fail?

Passes now
