### ISSUE TITLE
JDK19 java/lang/Thread/virtual/PreviewFeaturesNotEnabled.java failed

### ISSUE THREAD

**Issue by thallium** [eclipse-openj9/openj9#16044]
Failed with and without JIT
```
test PreviewFeaturesNotEnabled.testContinuationInitializer(): failure
java.lang.AssertionError: Expected ExceptionInInitializerError to be thrown, but nothing was thrown
        at org.testng.Assert.expectThrows(Assert.java:1730)
        at PreviewFeaturesNotEnabled.testContinuationInitializer(PreviewFeaturesNotEnabled.java:77)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
        at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
        at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
        at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
        at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
        at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:764)
        at org.testng.TestRunner.run(TestRunner.java:585)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
        at org.testng.SuiteRunner.run(SuiteRunner.java:286)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
        at org.testng.TestNG.runSuites(TestNG.java:1069)
        at org.testng.TestNG.run(TestNG.java:1037)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
        at java.base/java.lang.Thread.run(Thread.java:1573)
test PreviewFeaturesNotEnabled.testIsVirtual(): success
test PreviewFeaturesNotEnabled.testNewVirtualThreadPerTaskExecutor(): success
test PreviewFeaturesNotEnabled.testOfPlatform(): success
test PreviewFeaturesNotEnabled.testOfVirtual(): success
test PreviewFeaturesNotEnabled.testStartVirutalThread(): success
```

**Comment by babsingh** [comment]
The following checks are needed in Continuation.java for the above test to succeed.
```
import jdk.internal.misc.PreviewFeatures;
...
    static {
        ContinuationSupport.ensureSupported();
        PreviewFeatures.ensureEnabled();
    }
```   

@fengxue-IS currently working on this.

**Comment by fengxue-IS** [comment]
per discussion, moving this to backlog as the preview check is not blocking functionality
