### ISSUE TITLE
JDK19 java/lang/Thread/virtual/StackTraces.java#id1 failed

### ISSUE THREAD

**Issue by thallium** [eclipse-openj9/openj9#16045]
Failed with and without JIT
```
STDOUT:
test StackTraces.testStackTrace(): failure
java.lang.RuntimeException: java.lang.AssertionError: expected [true] but found [false]
        at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:77)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:292)
        at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:179)
        at java.base/jdk.internal.vm.Continuation.execute(Continuation.java:171)
Caused by: java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertTrue(Assert.java:45)
        at org.testng.Assert.assertTrue(Assert.java:55)
        at StackTraces.lambda$testStackTrace$0(StackTraces.java:59)
        at jdk.test.lib.thread.VThreadRunner.lambda$run$0(VThreadRunner.java:75)
        ... 3 more
test StackTraces.testStackWalker(): success
```

**Comment by babsingh** [comment]
id1 JVM options: 
```
 * @run testng/othervm --enable-preview -XX:+UnlockDiagnosticVMOptions -XX:+ShowCarrierFrames StackTraces
```

**Comment by fengxue-IS** [comment]
Moving to future milestone as `-XX:+UnlockDiagnosticVMOptions -XX:+ShowCarrierFrames` such XX option is not part of the spec

**Comment by babsingh** [comment]
This feature is for diagnostic purposes. As per https://github.com/eclipse-openj9/openj9/issues/16045#issuecomment-1270492642 and https://github.com/eclipse-openj9/openj9/pull/16724#issuecomment-1503843935, this failure should not block our Java 20.0.2 release. Thus, pushing to the Java 21 milestone.
