### ISSUE TITLE
JDK19 jdk/internal/vm/Continuation/LiveFramesDriver.java failed

### ISSUE THREAD

**Issue by thallium** [eclipse-openj9/openj9#16052]
Failed with and without JIT
```
STDOUT:
^&^ UNMOUNTED
^&^ start
^&^ --==--
STDERR:
java.lang.ClassCastException: java.lang.StackWalker$StackFrameImpl incompatible with java.lang.LiveStackFrame
        at java.base/java.lang.LiveFrames.lambda$testStackWalk$1(LiveFrames.java:96)
        at java.base/java.util.stream.Stream$2.forEachRemaining(Stream.java:1552)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.lang.StackWalker.lambda$forEach$0(StackWalker.java:157)
        at java.base/java.lang.StackWalker.walkImpl(StackWalker.java:212)
        at java.base/java.lang.StackWalker.walkWrapperImpl(Native Method)
        at java.base/java.lang.StackWalker.forEach(StackWalker.java:156)
        at java.base/java.lang.LiveFrames.testStackWalk(LiveFrames.java:92)
        at java.base/java.lang.LiveFrames.test1(LiveFrames.java:59)
        at java.base/java.lang.LiveFrames.main(LiveFrames.java:36)
        at LiveFramesDriver.main(LiveFramesDriver.java:39)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
        at java.base/java.lang.Thread.run(Thread.java:1573)
java.lang.ClassCastException: java.lang.StackWalker$StackFrameImpl incompatible with java.lang.LiveStackFrame
        at java.base/java.lang.LiveFrames.lambda$testStackWalk$1(LiveFrames.java:96)
        at java.base/java.util.stream.Stream$2.forEachRemaining(Stream.java:1552)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.lang.StackWalker.lambda$forEach$0(StackWalker.java:157)
        at java.base/java.lang.StackWalker.walkImpl(StackWalker.java:212)
        at java.base/java.lang.StackWalker.walkWrapperImpl(Native Method)
        at java.base/java.lang.StackWalker.forEach(StackWalker.java:156)
        at java.base/java.lang.LiveFrames.testStackWalk(LiveFrames.java:92)
        at java.base/java.lang.LiveFrames.test1(LiveFrames.java:59)
        at java.base/java.lang.LiveFrames.main(LiveFrames.java:36)
        at LiveFramesDriver.main(LiveFramesDriver.java:39)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
        at java.base/java.lang.Thread.run(Thread.java:1573)

JavaTest Message: Test threw exception: java.lang.ClassCastException: java.lang.StackWalker$StackFrameImpl incompatible with java.lang.LiveStackFrame
JavaTest Message: shutting down test
```

**Comment by fengxue-IS** [comment]
java.lang.LiveStackFrame is non-public class that isn't part of spec, OpenJ9 currently doesn't use/implement this class, moving this out of the Java 19 milestone.
This is not functional requirement and test is testing openjdk specific behaviour
