### ISSUE TITLE
valhalla build error - Cannot invoke "javax.lang.model.element.Element.getKind()" because "elem" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16072]
```
ERROR: Build failed for target 'images' in configuration 'macosx-x86_64-server-release' (exit code 2) 
Stopping sjavac server

=== Output from failing command(s) repeated here ===
* For target jdk_modules_jdk.incubator.vector__the.jdk.incubator.vector_batch:
An exception has occurred in the compiler (20-internal). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
com.sun.tools.javac.util.ClientCodeException: java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.Element.getKind()" because "elem" is null
        at jdk.compiler.interim/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.started(ClientCodeWrapper.java:869)
        at jdk.compiler.interim/com.sun.tools.javac.api.MultiTaskListener.started(MultiTaskListener.java:119)
        at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1310)
        at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:947)
        at jdk.compiler.interim/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler.interim/com.sun.tools.sjavac.comp.SjavacImpl.compile(SjavacImpl.java:117)
        at jdk.compiler.interim/com.sun.tools.sjavac.comp.PooledSjavac.lambda$compile$0(PooledSjavac.java:63)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.Element.getKind()" because "elem" is null
        at jdk.compiler.interim/com.sun.tools.javac.model.JavacTypes.getOverriddenMethods(JavacTypes.java:327)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.Env.setCurrent(Env.java:220)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.Checker.scan(Checker.java:161)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.DocLint$2.visitDecl(DocLint.java:293)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.DocLint$DeclScanner.visitPackage(DocLint.java:409)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.DocLint$DeclScanner.visitPackage(DocLint.java:398)
        at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCPackageDecl.accept(JCTree.java:664)
        at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
        at jdk.compiler.interim/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:150)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.DocLint$DeclScanner.visitCompilationUnit(DocLint.java:442)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.DocLint$DeclScanner.visitCompilationUnit(DocLint.java:398)
        at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:627)
        at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
        at jdk.javadoc.interim/jdk.javadoc.internal.doclint.DocLint$3.started(DocLint.java:304)
        at jdk.compiler.interim/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.started(ClientCodeWrapper.java:865)
        ... 10 more
```

This is after resolve the merging conflict w/ `openj9` branch at `src/java.base/share/classes/jdk/internal/reflect/MethodAccessorGenerator.java` - https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/commit/29ca754340783c2224eca162d9d13da2ad270fbd

The change is at https://github.com/JasonFengJ9/openj9-openjdk-jdk.valuetypes/tree/openj9-merged

FYI @hangshao0

**Comment by hangshao0** [comment]
It is returning NULL from:

https://github.com/JasonFengJ9/openj9-openjdk-jdk.valuetypes/blob/openj9-merged/src/jdk.compiler/share/classes/com/sun/tools/javac/api/JavacTrees.java#L375.

The comment says it returns NULL if the language model element referred to by the leaf node of the given doctree is unknown. 
https://github.com/JasonFengJ9/openj9-openjdk-jdk.valuetypes/blob/29ca754340783c2224eca162d9d13da2ad270fbd/src/jdk.compiler/share/classes/com/sun/source/util/DocTrees.java#L171-L176

Seems the javadoc tool cannot recognize a language model element referenced in the javadoc.

**Comment by JasonFengJ9** [comment]
Resolved in the latest merging.
Closing
