### ISSUE TITLE
mac10-x86-3 failing to upload

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16085]
Removed build label.
@AdamBrousseau @jdekonin 

Many examples starting Friday night, picking one.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/398/
```
21:29:19  Executing command: /bin/sh -c git log --pretty=format:%s -1
21:29:23  [consumer_0] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/398/OpenJ9-JDK11-x86-64_mac-20221010-210856.tar.gz
21:29:28  [consumer_1] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/398/test-images.tar.gz
21:29:34  [consumer_2] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/398/debug-image.tar.gz
[Pipeline] }
[Pipeline] // retry
[Pipeline] echo
21:30:54  Uploading to 'unb'...
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] retry
[Pipeline] {
[Pipeline] artifactoryUpload
21:30:56  Executing command: /bin/sh -c git log --pretty=format:%s -1
[Pipeline] }
21:30:59  ERROR: Execution failed
21:30:59  java.lang.Exception: Error occurred during operation, please refer to logs for more information.
21:30:59  	at org.jfrog.build.extractor.producerConsumer.ProducerConsumerExecutor.start(ProducerConsumerExecutor.java:85)
21:30:59  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:101)
21:30:59  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:166)
21:30:59  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to mac10-x86-3
21:30:59  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
21:30:59  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
21:30:59  		at hudson.remoting.Channel.call(Channel.java:1000)
21:30:59  		at hudson.FilePath.act(FilePath.java:1194)
21:30:59  		at hudson.FilePath.act(FilePath.java:1183)
21:30:59  		at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:56)
21:30:59  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:66)
21:30:59  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:53)
21:30:59  		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:55)
21:30:59  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
21:30:59  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$558/0x0000000000000000.run(Unknown Source)
21:30:59  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
21:30:59  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:30:59  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:30:59  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:30:59  		at java.base/java.lang.Thread.run(Thread.java:836)
21:30:59  Caused: java.lang.RuntimeException: Failed uploading artifacts by spec
21:30:59  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:168)
21:30:59  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:117)
21:30:59  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3502)
21:30:59  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
21:30:59  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
21:30:59  	at hudson.remoting.Request$2.run(Request.java:376)
21:30:59  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
21:30:59  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:30:59  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:30:59  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:30:59  	at java.base/java.lang.Thread.run(Thread.java:840)
21:30:59  Retrying
[Pipeline] {
[Pipeline] sleep
21:30:59  Sleeping for 5 min 0 sec
21:30:59  [consumer_0] Deploying artifact: https://ub18p8art.casa.cs.unb.ca/artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/398/OpenJ9-JDK11-x86-64_mac-20221010-210856.tar.gz
21:30:59  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
21:30:59  Error occurred for request PUT /artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/398/OpenJ9-JDK11-x86-64_mac-20221010-210856.tar.gz;build.parentNumber=1258;build.buildIdentifier=Nightly;build.timestamp=1665446171862;build.name=Build_JDK11_x86-64_mac_Nightly;build.parentName=Pipeline_Build_Test_JDK11_x86-64_mac;build.number=398 HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
21:30:59  [consumer_0] An exception occurred during execution:
21:30:59  java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:30:59  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
21:30:59  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
21:30:59  	at java.base/java.lang.Thread.run(Thread.java:840)
21:30:59  Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:30:59  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
21:30:59  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
21:30:59  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
21:30:59  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
21:30:59  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
21:30:59  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
21:30:59  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
21:30:59  	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
21:30:59  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
21:30:59  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
21:30:59  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
21:30:59  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
21:30:59  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
21:30:59  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
21:30:59  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
21:30:59  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
21:30:59  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
21:30:59  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
21:30:59  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
21:30:59  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
21:30:59  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
21:30:59  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
21:30:59  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
21:30:59  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
21:30:59  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
21:30:59  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
21:30:59  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
21:30:59  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
21:30:59  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:72)
21:30:59  	at org.jfrog.build.client.JFrogHttpClient.sendRequest(JFrogHttpClient.java:133)
21:30:59  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:112)
21:30:59  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
21:30:59  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:262)
21:30:59  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:257)
21:30:59  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
21:30:59  	... 2 more
21:30:59  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:30:59  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
21:30:59  	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
21:30:59  	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
21:30:59  	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
21:30:59  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
21:30:59  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
21:30:59  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
21:30:59  	... 32 more
21:30:59  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:30:59  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
21:30:59  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
21:30:59  	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
21:30:59  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
21:30:59  	... 38 more
```

**Comment by jdekonin** [comment]
Error message on the desktop on update.  Requested reboot which I initiated and now its not coming back online.  I've asked our onsite contact to take a look and see whats wrong.

**Comment by jdekonin** [comment]
mac10-x86-3 is back online. push a personal build at it to retest.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/268/

**Comment by pshipton** [comment]
Still failing. It seems to have some kind of SSL/certificate problem.

**Comment by pshipton** [comment]
Is the machine up to date with OS updates? Perhaps an old certificate expired.

**Comment by jdekonin** [comment]
The cert issue is because default java had changed.  There are setup instructions to work with the UNB artifactory (Thanks for the reminder @AdamBrousseau).  There might have been brew or system updates that caused a problem as well.  I've updated both the system to the latest 10.15.7 level as well as the latest brew package upgrades.

A new personal build verifies the compile and push to UNB artifactory now work.  Ive added the build label back onto the machine.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/269/

https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/ARTIFACTORY.md#configure-unb-nodes-to-accept-self-signed-certificate-upload-only
