### ISSUE TITLE
Results are different when openj9 and hotspot call wait (long time, int frac) in the Object class

### ISSUE THREAD

**Issue by ayuan0828** [eclipse-openj9/openj9#16127]
**Description**:

As shown below, when calling the "wait (long time, int frac)" method with `time=Long.MAX_VALUE` and `frac>0` (for example, "1"), OpenJ9 will not catch `IllegalArgumentException`, which is the output in HotSpot.

**Environment**：

```
Ubuntu 18.04 x86_64
```

**JVM Information**:
jdk8:

```openjdk version "1.8.0_332-internal"
OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_02_17_10_23-b00)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 301202f49f based on jdk8u332-b02)
```

jdk11:

```openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 11 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 24e7209ed4 based on jdk-11.0.15+1)
```

**Testcase**:

```public class Test {
public class WaitTooLong {
    public static void main(String[] args) {
        test(1);
    }
    static void test(int nanos) {
        try {
            WaitTooLong.class.wait(Long.MAX_VALUE, nanos);
        } catch (IllegalMonitorStateException expected) {
        } catch (IllegalArgumentException | InterruptedException unexpected) {
            throw new RuntimeException("Unexpected", unexpected);
        }
    }
}
```

**Output of HotSpot**:

```
Exception in thread "main" java.lang.RuntimeException: Unexpected
	at org.example.WaitTooLong.test(WaitTooLong.java:10)
	at org.example.WaitTooLong.main(WaitTooLong.java:3)
Caused by: java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:460)
	at org.example.WaitTooLong.test(WaitTooLong.java:7)
	... 1 more
```

**Output of OpenJ9**:

```

```

**Comment by tajila** [comment]
We dont seem to detect `J9THREAD_INVALID_ARGUMENT` from the omr call

**Comment by tajila** [comment]
I guess the other problem (perhaps not a real one) is that hotspot throw the IAE before the IMSE. The code in that example is wrong in that it doesnt synchronize on the object before calling wait. So that code has two errors.

**Comment by pshipton** [comment]
Since the OpenJ9 behavior is valid, I'll go ahead and close this.
