### ISSUE TITLE
cent7-x64-5 failed to upload to artifactory, disabled it

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16138]
https://openj9-jenkins.osuosl.org/computer/cent7-x64-5

https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_linux_OMR/244/console
```
16:48:43  [consumer_0] Deploying artifact: https://ub18p8art.casa.cs.unb.ca/artifactory/ci-openj9/Build_JDK17_x86-64_linux_OMR/244/OpenJ9-JDK17-x86-64_linux-20221019-163731.tar.gz
16:48:43  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
16:48:44  Error occurred for request PUT /artifactory/ci-openj9/Build_JDK17_x86-64_linux_OMR/244/OpenJ9-JDK17-x86-64_linux-20221019-163731.tar.gz;build.parentNumber=978;build.buildIdentifier=OMR-Acceptance;build.timestamp=1666208096428;build.name=Build_JDK17_x86-64_linux_OMR;build.parentName=Pipeline_Build_Test_JDK17_x86-64_linux;build.number=244 HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
16:48:44  [consumer_0] An exception occurred during execution:
16:48:44  java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
16:48:44  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
16:48:44  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
16:48:44  	at java.base/java.lang.Thread.run(Thread.java:840)
16:48:44  Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
16:48:44  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
16:48:44  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
16:48:44  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
16:48:44  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
16:48:44  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
16:48:44  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
16:48:44  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
16:48:44  	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
16:48:44  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
16:48:44  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
16:48:44  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
16:48:44  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
16:48:44  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
16:48:44  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
16:48:44  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
16:48:44  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
16:48:44  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
16:48:44  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
16:48:44  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
16:48:44  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
16:48:44  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
16:48:44  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
16:48:44  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
16:48:44  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
16:48:44  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
16:48:44  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
16:48:44  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
16:48:44  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
16:48:44  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:72)
16:48:44  	at org.jfrog.build.client.JFrogHttpClient.sendRequest(JFrogHttpClient.java:133)
16:48:44  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:112)
16:48:44  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
16:48:44  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:262)
16:48:44  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:257)
16:48:44  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
16:48:44  	... 2 more
16:48:44  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
16:48:44  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
16:48:44  	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
16:48:44  	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
16:48:44  	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
16:48:44  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
16:48:44  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
16:48:44  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
16:48:44  	... 32 more
16:48:44  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
16:48:44  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
16:48:44  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
16:48:44  	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
16:48:44  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
16:48:44  	... 38 more
```

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
worker-4 still broken too
https://openj9-jenkins.osuosl.org/job/Cleanup_Artifactory_UNB/526/console

**Comment by AdamBrousseau** [comment]
cent7-x64-5 fixed. Added back in the pool.
worker-4 still having issues. Not sure what is wrong with it.

**Comment by AdamBrousseau** [comment]
I think this can be closed. cent7-5 is back in the pool and worker 4 seems fine.
