### ISSUE TITLE
testContendedClassLoading testDelegatedClassLoading Deadlock detected

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16130]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/389 - [ub20-390-6](https://openj9-jenkins.osuosl.org/computer/ub20-390-6)
testContendedClassLoading_0

FYI https://github.com/eclipse-openj9/openj9/issues/16037 "Linux 390 jenkins system replacement"

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/389/functional_test_output.tar.gz
```
JVMDUMP034I User requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16661473047297/testContendedClassLoading_0/javacore.20221019.043829.2873251.0001.txt' through com.ibm.jvm.Dump.JavaDump
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16661473047297/testContendedClassLoading_0/javacore.20221019.043829.2873251.0001.txt
JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16661473047297/testContendedClassLoading_0/core.20221019.043830.2873251.0002.dmp' through com.ibm.jvm.Dump.SystemDump
JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16661473047297/testContendedClassLoading_0/core.20221019.043830.2873251.0002.dmp
java.lang.LinkageError: A duplicate class definition for j9vm/test/classloader/Empty is found
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:466)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:427)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:379)
	at org.openj9.test.contendedClassLoading.EmptyClassLoader.loadClass(EmptyClassLoader.java:93)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:418)
	at org.openj9.test.contendedClassLoading.LoadingThread.run(LoadingThread.java:45)
PASSED: testDelegatedParallelCapableClassLoading
PASSED: testParallelClassLoading
PASSED: testParallelClassLoadingWithFailure
PASSED: testSequentialClassLoading
PASSED: testDelegatedNonParallelCapableClassLoading
PASSED: testParallelCapableClassLoading
FAILED: testDelegatedClassLoading
java.lang.AssertionError: Deadlock detected
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
```

**Comment by pshipton** [comment]
https://github.com/eclipse-openj9/openj9/issues/15966#issuecomment-1284320553 occurred in the same build, although we've seen this failure before.

**Comment by pshipton** [comment]
@tajila fyi

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/375
testContendedClassLoading_0
```
FAILED: testDelegatedClassLoading
java.lang.AssertionError: Deadlock detected
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_aot_Personal_testList_1/92
testContendedClassLoading_0
```
=== AOT ITERATION 1 ===

TESTING:
...

JVMDUMP034I User requested Java dump using '/home/jenkins/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_aot_Personal_testList_1/aqa-tests/TKG/output_16733504798340/testContendedClassLoading_0_AOT_ITER_1/javacore.20230110.095347.61000.0001.txt' through com.ibm.jvm.Dump.JavaDump
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_aot_Personal_testList_1/aqa-tests/TKG/output_16733504798340/testContendedClassLoading_0_AOT_ITER_1/javacore.20230110.095347.61000.0001.txt
JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_aot_Personal_testList_1/aqa-tests/TKG/output_16733504798340/testContendedClassLoading_0_AOT_ITER_1/core.20230110.095347.61000.0002.dmp' through com.ibm.jvm.Dump.SystemDump
JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_aot_Personal_testList_1/aqa-tests/TKG/output_16733504798340/testContendedClassLoading_0_AOT_ITER_1/core.20230110.095347.61000.0002.dmp
java.lang.LinkageError: A duplicate class definition for j9vm/test/classloader/Empty is found
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:471)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:432)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:384)
	at org.openj9.test.contendedClassLoading.EmptyClassLoader.loadClass(EmptyClassLoader.java:93)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:429)
	at org.openj9.test.contendedClassLoading.LoadingThread.run(LoadingThread.java:45)
PASSED: testDelegatedParallelCapableClassLoading
PASSED: testParallelClassLoading
PASSED: testParallelClassLoadingWithFailure
PASSED: testSequentialClassLoading
PASSED: testDelegatedNonParallelCapableClassLoading
PASSED: testParallelCapableClassLoading
FAILED: testDelegatedClassLoading
java.lang.AssertionError: Deadlock detected
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_extended.functional_s390x_linux_Nightly_testList_0/21
testContendedClassLoading_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk20_j9_extended.functional_s390x_linux_Nightly_testList_0/21/functional_test_output.tar.gz
```
FAILED: testDelegatedClassLoading
java.lang.AssertionError: Deadlock detected
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/504
testContendedClassLoading_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1/504/functional_test_output.tar.gz
```
02:31:47  JVMDUMP034I User requested Java dump using 'C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1\aqa-tests\TKG\output_16868925707613\testContendedClassLoading_0\javacore.20230616.023146.3208.0001.txt' through com.ibm.jvm.Dump.JavaDump
02:31:47  JVMDUMP010I Java dump written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1\aqa-tests\TKG\output_16868925707613\testContendedClassLoading_0\javacore.20230616.023146.3208.0001.txt
02:31:47  JVMDUMP034I User requested System dump using 'C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1\aqa-tests\TKG\output_16868925707613\testContendedClassLoading_0\core.20230616.023146.3208.0002.dmp' through com.ibm.jvm.Dump.SystemDump
02:31:53  JVMDUMP010I System dump written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.functional_x86-64_windows_Nightly_testList_1\aqa-tests\TKG\output_16868925707613\testContendedClassLoading_0\core.20230616.023146.3208.0002.dmp
02:31:55  java.lang.LinkageError: A duplicate class definition for j9vm/test/classloader/Empty is found
02:31:55  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472)
02:31:55  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:433)
02:31:55  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:385)
02:31:55  	at org.openj9.test.contendedClassLoading.EmptyClassLoader.loadClass(EmptyClassLoader.java:93)
02:31:55  	at java.base/java.lang.Class.forNameImpl(Native Method)
02:31:55  	at java.base/java.lang.Class.forName(Class.java:429)
02:31:55  	at org.openj9.test.contendedClassLoading.LoadingThread.run(LoadingThread.java:45)
02:31:55  PASSED: testDelegatedParallelCapableClassLoading
02:31:55  PASSED: testParallelClassLoading
02:31:55  PASSED: testParallelClassLoadingWithFailure
02:31:55  PASSED: testSequentialClassLoading
02:31:55  PASSED: testDelegatedNonParallelCapableClassLoading
02:31:55  PASSED: testParallelCapableClassLoading
02:31:55  FAILED: testDelegatedClassLoading
02:31:55  java.lang.AssertionError: Deadlock detected
02:31:55  	at org.testng.Assert.fail(Assert.java:96)
02:31:55  	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
02:31:55  	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
02:31:55  	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly/19/tapResults/
```
variation: NoOptions
JVM_OPTIONS: 

...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

JVMDUMP034I User requested Java dump using '/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/output_16899763161270/testContendedClassLoading_0/javacore.20230721.234147.875541.0001.txt' through com.ibm.jvm.Dump.JavaDump
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/output_16899763161270/testContendedClassLoading_0/javacore.20230721.234147.875541.0001.txt
JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/output_16899763161270/testContendedClassLoading_0/core.20230721.234147.875541.0002.dmp' through com.ibm.jvm.Dump.SystemDump
JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/output_16899763161270/testContendedClassLoading_0/core.20230721.234147.875541.0002.dmp
java.lang.LinkageError: A duplicate class definition for j9vm/test/classloader/Empty is found
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:474)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:435)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:387)
	at org.openj9.test.contendedClassLoading.EmptyClassLoader.loadClass(EmptyClassLoader.java:93)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forNameHelper(Class.java:454)
	at java.base/java.lang.Class.forName(Class.java:432)
	at org.openj9.test.contendedClassLoading.LoadingThread.run(LoadingThread.java:45)

FAILED: testDelegatedClassLoading
java.lang.AssertionError: Deadlock detected
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    testContendedClassLoading
    Tests run: 7, Failures: 1, Skips: 0
===============================================


===============================================
GeneralTest suite
Total tests run: 7, Failures: 1, Skips: 0
===============================================

-----------------------------------
testContendedClassLoading_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/36

**Comment by JasonFengJ9** [comment]
[JDK21 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.functional_s390x_linux_testList_2/109/)(`rhel7s390x-svl-rt8-1`)
```
java version "21.0.3-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 21.0.3+4-202402241633 (build 21.0.3-beta+4-202402241633)
Eclipse OpenJ9 VM 21.0.3+4-202402241633 (build master-6bdd7e4b0, JRE 21 Linux s390x-64-Bit Compressed References 20240224_112 (JIT enabled, AOT enabled)
OpenJ9   - 6bdd7e4b0
OMR      - b399f9e8c
JCL      - 5e5b133ab based on jdk-21.0.3+4)

[2024-02-24T20:38:05.782Z] variation: NoOptions
[2024-02-24T20:38:05.782Z] JVM_OPTIONS:  

[2024-02-24T20:39:16.224Z] java.lang.LinkageError: A duplicate class definition for j9vm/test/classloader/Empty is found
[2024-02-24T20:39:16.224Z] 	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
[2024-02-24T20:39:16.224Z] 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472)
[2024-02-24T20:39:16.224Z] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:433)
[2024-02-24T20:39:16.224Z] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:385)
[2024-02-24T20:39:16.224Z] 	at org.openj9.test.contendedClassLoading.EmptyClassLoader.loadClass(EmptyClassLoader.java:93)
[2024-02-24T20:39:16.224Z] 	at java.base/java.lang.Class.forNameImpl(Native Method)
[2024-02-24T20:39:16.224Z] 	at java.base/java.lang.Class.forNameHelper(Class.java:454)
[2024-02-24T20:39:16.224Z] 	at java.base/java.lang.Class.forName(Class.java:432)
[2024-02-24T20:39:16.224Z] 	at org.openj9.test.contendedClassLoading.LoadingThread.run(LoadingThread.java:45)

[2024-02-24T20:39:28.409Z] FAILED: testDelegatedClassLoading
[2024-02-24T20:39:28.409Z] java.lang.AssertionError: Deadlock detected
[2024-02-24T20:39:28.409Z] 	at org.testng.Assert.fail(Assert.java:96)
[2024-02-24T20:39:28.409Z] 	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
[2024-02-24T20:39:28.409Z] 	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
[2024-02-24T20:39:28.409Z] 	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
[2024-02-24T20:39:28.409Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

[2024-02-24T20:39:28.409Z] ===============================================
[2024-02-24T20:39:28.409Z]     testContendedClassLoading
[2024-02-24T20:39:28.409Z]     Tests run: 7, Failures: 1, Skips: 0
[2024-02-24T20:39:28.409Z] ===============================================
[2024-02-24T20:39:28.409Z] 
[2024-02-24T20:39:28.409Z] 
[2024-02-24T20:39:28.409Z] ===============================================
[2024-02-24T20:39:28.409Z] GeneralTest suite
[2024-02-24T20:39:28.409Z] Total tests run: 7, Failures: 1, Skips: 0
[2024-02-24T20:39:28.409Z] ===============================================
[2024-02-24T20:39:28.409Z] 
[2024-02-24T20:39:29.619Z] -----------------------------------
[2024-02-24T20:39:29.619Z] testContendedClassLoading_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38156/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Release_testList_1/15
testContendedClassLoading_0
```
10:45:33  FAILED: testDelegatedClassLoading
10:45:33  java.lang.AssertionError: Deadlock detected
10:45:33  	at org.testng.Assert.fail(Assert.java:96)
10:45:33  	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
10:45:33  	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
10:45:33  	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)
```

**Comment by JasonFengJ9** [comment]
[JDK22 x86-64_windows 0.46.1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.functional_x86-64_windows_testList_3/21/)(`win19x86-rtp-rt2-1`)
```
[2024-09-06T23:36:33.530Z] variation: NoOptions
[2024-09-06T23:36:33.943Z] JVM_OPTIONS:  

[2024-09-06T23:37:41.912Z] FAILED: testDelegatedClassLoading
[2024-09-06T23:37:41.912Z] java.lang.AssertionError: Deadlock detected
[2024-09-06T23:37:41.912Z] 	at org.testng.Assert.fail(Assert.java:96)
[2024-09-06T23:37:41.912Z] 	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.checkState(ParallelClassLoadingTests.java:285)
[2024-09-06T23:37:41.912Z] 	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.runMultiThreadClassLoading(ParallelClassLoadingTests.java:259)
[2024-09-06T23:37:41.912Z] 	at org.openj9.test.contendedClassLoading.ParallelClassLoadingTests.testDelegatedClassLoading(ParallelClassLoadingTests.java:111)

[2024-09-06T23:37:41.912Z]     testContendedClassLoading
[2024-09-06T23:37:41.912Z]     Tests run: 7, Failures: 1, Skips: 0
[2024-09-06T23:37:41.912Z] ===============================================

[2024-09-06T23:37:43.326Z] -----------------------------------
[2024-09-06T23:37:43.326Z] testContendedClassLoading_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/43056/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/1016
