### ISSUE TITLE
abbs.5mins.Mode113 AssertionFailedError: 127:127

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16150]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=45357022) [Linux PPC 64bit] 80 Load_Level_2.abbs.5mins.Mode113 - rhel7p7vm30
`IBM_JAVA_OPTIONS = -Xgcpolicy:gencon -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xmn512k -Xnocompressedrefs`

100x grinder passed.

`j> 13:01:07 20221020 13:01:06 Runtime State Reporter IMPORTANT: 42 tests complete, 300 currently running
j> 13:01:12 20221020 13:00:48 <Primary|SimpleDriver|com.ibm.jtc.svt.lambda.TestLambdaMethodReferences.testConstructorReference|254|Default Invocant> ERROR: Test testConstructorReference(com.ibm.jtc.svt.lambda.TestLambdaMethodReferences) failed
j> 13:01:12 Throwable trace:
j> 13:01:12 junit.framework.AssertionFailedError: 127:127
j> 13:01:12 	at junit.framework.Assert.fail(Assert.java:47)
j> 13:01:12 	at junit.framework.Assert.assertTrue(Assert.java:20)
j> 13:01:12 	at com.ibm.jtc.svt.lambda.TestLambdaMethodReferences.testConstructorReference(TestLambdaMethodReferences.java:300)
j> 13:01:12 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
j> 13:01:12 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
j> 13:01:12 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
j> 13:01:12 	at java.lang.reflect.Method.invoke(Method.java:508)
j> 13:01:12 	at junit.framework.TestCase.runTest(TestCase.java:168)
j> 13:01:12 	at junit.framework.TestCase.runBare(TestCase.java:134)
j> 13:01:12 	at junit.framework.TestResult$1.protect(TestResult.java:110)
j> 13:01:12 	at junit.framework.TestResult.runProtected(TestResult.java:128)
j> 13:01:12 	at junit.framework.TestResult.run(TestResult.java:113)
j> 13:01:12 	at junit.framework.TestCase.run(TestCase.java:124)
j> 13:01:12 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
j> 13:01:12 	at junit.framework.TestSuite.run(TestSuite.java:238)
j> 13:01:12 	at com.ibm.jtc.test.jltf.workunitadapters.JUnitWorkUnit.runWork(JUnitWorkUnit.java:370)
j> 13:01:12 	at com.ibm.jtc.test.jltf.threads.WorkUnitRunner.run(WorkUnitRunner.java:113)
j> 13:01:12 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.runWork(PooledRunnable.java:170)
j> 13:01:12 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:136)
j> 13:01:12 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 13:01:12 	at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 13:01:15 20221020 13:01:14 Result Summary ERROR: Primary|SimpleDriver|com.ibm.jtc.svt.lambda.TestLambdaMethodReferences.testConstructorReference|254|Default Invocant reported failed with message: Test testConstructorReference(com.ibm.jtc.svt.lambda.TestLambdaMethodReferences) failed: 
`

Noticed this older closed issue which seems related https://github.com/eclipse-openj9/openj9/issues/11900 . We fixed the test, but probably not this internal one.

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=54240037)
[Linux PPC LE 64bit] 80 Load_Level_2.abbs.5mins.Mode122 - ub20lertp1-10
`IBM_JAVA_OPTIONS = -Xgcpolicy:optavgpause -Xjit:count=0,optlevel=hot,gcOnResolve,rtResolve -Xnocompressedrefs`
```
j> 06:06:50 20230222 06:06:36 <Primary|SimpleDriver|com.ibm.jtc.svt.lambda.TestLambdaMethodReferences.testConstructorReference|943|Default Invocant> ERROR: Test testConstructorReference(com.ibm.jtc.svt.lambda.TestLambdaMethodReferences) failed
j> 06:06:50 Throwable trace:
j> 06:06:50 junit.framework.AssertionFailedError: 219:219
j> 06:06:50 	at junit.framework.Assert.fail(Assert.java:47)
j> 06:06:50 	at junit.framework.Assert.assertTrue(Assert.java:20)
j> 06:06:50 	at com.ibm.jtc.svt.lambda.TestLambdaMethodReferences.testConstructorReference(TestLambdaMethodReferences.java:300)
```

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=85611712) - prhel037
[Linux PPC 64bit] 80 Load_Level_2.abbs.5mins.Mode122
```
j> 19:17:44 20240527 19:17:43 <Primary|SimpleDriver|com.ibm.jtc.svt.lambda.TestLambdaMethodReferences.testConstructorReference|2463|Default Invocant> ERROR: Test testConstructorReference(com.ibm.jtc.svt.lambda.TestLambdaMethodReferences) failed
j> 19:17:44 Throwable trace:
j> 19:17:44 junit.framework.AssertionFailedError: 320:320
j> 19:17:44 	at junit.framework.Assert.fail(Assert.java:47)
j> 19:17:44 	at junit.framework.Assert.assertTrue(Assert.java:20)
j> 19:17:44 	at com.ibm.jtc.svt.lambda.TestLambdaMethodReferences.testConstructorReference(TestLambdaMethodReferences.java:300)
```
