### ISSUE TITLE
JDK8 jdk_security3_0_FAILED - SSLException: Tag mismatch!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16169]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_s390x_linux/90/)(`ubu22s390x-rt4-1`):
```
openjdk version "1.8.0_352"
IBM Semeru Runtime Open Edition (build 1.8.0_352-b08)
Eclipse OpenJ9 VM (build openj9-0.35.0-rc1, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20221020_476 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - c2152d162d based on jdk8u352-b08)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F476%2Fibm-semeru-open-jre_s390x_linux_8u352b08_openj9-0.35.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F476%2Fibm-semeru-open-testimage_s390x_linux_8u352b08_openj9-0.35.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F476%2Fibm-semeru-open-jdk_s390x_linux_8u352b08_openj9-0.35.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-s390x-openj9%2F476%2Fibm-semeru-open-debugimage_s390x_linux_8u352b08_openj9-0.35.0-rc1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.5-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=v0.35.0-release&amp;OPENJ9_BRANCH=v0.35.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.35.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-10-21T01:03:22.749Z] variation: Mode150
[2022-10-21T01:03:22.749Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-10-21T01:05:41.252Z] TEST: javax/net/ssl/ServerName/SSLEngineExplorerMatchedSNI.java

[2022-10-21T01:05:41.254Z] STDERR:
[2022-10-21T01:05:41.254Z] javax.net.ssl.SSLException: Tag mismatch!
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.Alert.createSSLException(Alert.java:133)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:119)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:588)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:544)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:411)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:390)
[2022-10-21T01:05:41.254Z] 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
[2022-10-21T01:05:41.254Z] 	at SSLEngineService.receive(SSLEngineService.java:167)
[2022-10-21T01:05:41.254Z] 	at SSLEngineExplorerMatchedSNI.doServerSide(SSLEngineExplorerMatchedSNI.java:160)
[2022-10-21T01:05:41.254Z] 	at SSLEngineExplorerMatchedSNI.startServer(SSLEngineExplorerMatchedSNI.java:369)
[2022-10-21T01:05:41.254Z] 	at SSLEngineExplorerMatchedSNI.<init>(SSLEngineExplorerMatchedSNI.java:319)
[2022-10-21T01:05:41.254Z] 	at SSLEngineExplorerMatchedSNI.main(SSLEngineExplorerMatchedSNI.java:300)
[2022-10-21T01:05:41.254Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-10-21T01:05:41.254Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-10-21T01:05:41.254Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-10-21T01:05:41.254Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-10-21T01:05:41.254Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-10-21T01:05:41.254Z] 	at java.lang.Thread.run(Thread.java:826)
[2022-10-21T01:05:41.254Z] Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
[2022-10-21T01:05:41.254Z] 	at com.sun.crypto.provider.NativeGaloisCounterMode.decryptFinal(NativeGaloisCounterMode.java:575)
[2022-10-21T01:05:41.254Z] 	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1173)
[2022-10-21T01:05:41.254Z] 	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1110)
[2022-10-21T01:05:41.254Z] 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:998)
[2022-10-21T01:05:41.254Z] 	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
[2022-10-21T01:05:41.254Z] 	at javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
[2022-10-21T01:05:41.254Z] 	at javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
[2022-10-21T01:05:41.254Z] 	at javax.crypto.Cipher.doFinal(Cipher.java:2463)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1880)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160)
[2022-10-21T01:05:41.254Z] 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
[2022-10-21T01:05:41.254Z] 	... 16 more
[2022-10-21T01:05:41.254Z] 
[2022-10-21T01:05:41.254Z] JavaTest Message: Test threw exception: javax.net.ssl.SSLException: Tag mismatch!

[2022-10-21T01:05:41.254Z] TEST RESULT: Failed. Execution failed: `main' threw exception: javax.net.ssl.SSLException: Tag mismatch!
[2022-10-21T01:05:41.254Z] --------------------------------------------------
[2022-10-21T02:07:26.954Z] Test results: passed: 601; failed: 1
[2022-10-21T02:07:26.954Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16663088941238/jdk_security3_0/report/html/report.html
[2022-10-21T02:07:26.954Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16663088941238/jdk_security3_0/work
[2022-10-21T02:07:26.954Z] Error: Some tests failed or other problems occurred.
[2022-10-21T02:07:26.954Z] 
[2022-10-21T02:07:26.954Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28931/) - failed 14/20.

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/15862.
This is an OpenJDK problem.
