### ISSUE TITLE
jdk19 ThreadInterruptImplTest test_interruptDuringRun "interrupt flag should not be set",  JCL_Test test_interrupted "Interrupted returned true for non-interrupted thread"

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16174]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_s390x_linux_Nightly_testList_0/34
ThreadInterruptImplTest_0 
```
FAILED: test_interruptDuringRun
java.lang.AssertionError: interruptDuringRun: interrupt flag should not be set
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.openj9.test.java.lang.Test_Thread.test_interruptDuringRun(Test_Thread.java:115)
```

JCL_Test_0
```
FAILED: test_interrupted
java.lang.AssertionError: Interrupted returned true for non-interrupted thread
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@ead21cb6(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@ead21cb6(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Thread.test_interrupted(Test_Thread.java:508) from jdk.internal.loader.ClassLoaders$AppClassLoader@ead21cb6(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_Nightly_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/24
JCL_Test_0
JCL_Test_2
```
FAILED: test_interrupted
java.lang.AssertionError: Interrupted returned true for non-interrupted thread
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@b121257(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@b121257(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Thread.test_interrupted(Test_Thread.java:508) from jdk.internal.loader.ClassLoaders$AppClassLoader@b121257(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
@tajila fyi. Not sure if these are related to https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/41.

**Comment by tajila** [comment]
10 job grinder https://openj9-jenkins.osuosl.org/job/Grinder/1445/

**Comment by tajila** [comment]
I think there is an issue with the openJDK implementation in that it uses a field in Thread to query the interrupt status, wheres J9 calls in to the JVM to invoke `omrthread_clear_interrupted`.

But the recent changes do not affect this behaviour so Im not sure why this would only start failing now.

**Comment by tajila** [comment]
I havent been able to reproduce it on x86, and the fact that only s390 fails leads me to think this issue is intermittent. 

For some reason the grinder above failed

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_1/34
JCL_Test_none_SCC_1
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/34
JCL_Test_none_SCC_0
```
FAILED: test_interrupted
java.lang.AssertionError: Interrupted returned true for non-interrupted thread
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@5eefb7cd(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@5eefb7cd(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Thread.test_interrupted(Test_Thread.java:508) from jdk.internal.loader.ClassLoaders$AppClassLoader@5eefb7cd(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by tajila** [comment]
Test failed again on s390x
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_s390x_linux_Nightly/36/tapResults/

**Comment by tajila** [comment]
Grinder: https://openj9-jenkins.osuosl.org/job/Grinder/1454/tapResults/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/36
JCL_Test_none_SCC_0 
```
FAILED: test_interrupted
java.lang.AssertionError: Interrupted returned true for non-interrupted thread
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@3f1f8d21(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@3f1f8d21(file:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Thread.test_interrupted(Test_Thread.java:508) from
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_aarch64_linux_Nightly_testList_0/37/
