### ISSUE TITLE
jdk19 OpenJDK java/foreign/LibraryLookupTest.java LibraryLookupTest.testLoadLibrarySharedClosed() and crash

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16175]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_Nightly/32 - [mac12-x86-1](https://openj9-jenkins.osuosl.org/computer/mac12-x86-1)
jdk_foreign_0
java/foreign/LibraryLookupTest.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_Nightly/32/openjdk_test_output.tar.gz
```
23:19:17  test LibraryLookupTest.testLoadLibrarySharedClosed(): failure
23:19:17  java.lang.AssertionError: expected [true] but found [false]
23:19:17  	at org.testng.Assert.fail(Assert.java:99)
23:19:17  	at org.testng.Assert.failNotEquals(Assert.java:1037)
23:19:17  	at org.testng.Assert.assertTrue(Assert.java:45)
23:19:17  	at org.testng.Assert.assertTrue(Assert.java:55)
23:19:17  	at LibraryLookupTest.testLoadLibrarySharedClosed(LibraryLookupTest.java:144)

...

23:19:17  ===============================================
23:19:17  java/foreign/LibraryLookupTest.java
23:19:17  Total tests run: 6, Passes: 5, Failures: 1, Skips: 0
23:19:17  ===============================================
23:19:17  
23:19:17  STDERR:
23:19:17  Unhandled exception
23:19:17  Type=Segmentation error vmState=0x00000000
23:19:17  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
23:19:17  Handler1=000000000C477C60 Handler2=000000000C1D4B20 InaccessibleAddress=000000000C052FA0
23:19:17  RDI=0000000001000801 RSI=00007FA6F30499D8 RAX=0000000000000000 RBX=FFFFFFFFFFFFFF20
23:19:17  RCX=0000000000000010 RDX=0000000000000000 R8=0000700007418780 R9=000000000C13BB3A
23:19:17  R10=0000000000000000 R11=000000000C052FA0 R12=0000000000000000 R13=00007FA6F903AC70
23:19:17  R14=00007000074189A0 R15=0000700007418AF0
23:19:17  RIP=000000000C052FA0 GS=0000 FS=0000 RSP=0000700007418768
23:19:17  RFlags=0000000000010246 CS=002B RBP=0000700007418770 ERR=0C052FA000000014
23:19:17  TRAPNO=000000140000000E CPU=2FA0000000140000 FAULTVADDR=000000000C052FA0
23:19:17  XMM0 000000001ac19b40 (f: 448895808.000000, d: 2.217840e-315)
23:19:17  XMM1 000000003780f1fb (f: 931197440.000000, d: 4.600727e-315)
23:19:17  XMM2 000000005f000000 (f: 1593835520.000000, d: 7.874594e-315)
23:19:17  XMM3 3d53e2d60a22bf19 (f: 170049312.000000, d: 2.825982e-13)
23:19:17  XMM4 3e333c8422f854b0 (f: 586699968.000000, d: 4.478821e-09)
23:19:17  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM6 3fe2555bce98f7cb (f: 3466131456.000000, d: 5.729198e-01)
23:19:17  XMM7 402a56ef8ec924cc (f: 2395546880.000000, d: 1.316980e+01)
23:19:17  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:17  Target=2_90_20221021_99 (Mac OS X 12.1)
23:19:17  CPU=amd64 (12 logical CPUs) (0x400000000 RAM)
23:19:17  ----------- Stack Backtrace -----------
23:19:17  (0x000000000C052FA0 [<unknown>+0x0])
23:19:17  ffi_call_unix64+0x52 (0x000000000C6B03C2 [libj9vm29.dylib+0x2703c2])
23:19:17  ffi_call_int+0x304 (0x000000000C6AFA74 [libj9vm29.dylib+0x26fa74])
23:19:17  _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x1de1f (0x000000000C4ECD3F [libj9vm29.dylib+0xacd3f])
23:19:17  bytecodeLoopCompressed+0xb4 (0x000000000C4CEF14 [libj9vm29.dylib+0x8ef14])
23:19:17  ---------------------------------------
```

**Comment by pshipton** [comment]
grinder https://openj9-jenkins.osuosl.org/job/Grinder/1436/

**Comment by pshipton** [comment]
The grinder failed a number of times in https://openj9-jenkins.osuosl.org/job/Grinder_iteration_0/169 on [mac11-x86-2](https://openj9-jenkins.osuosl.org/computer/mac11-x86-2), passed on the other machines ([mac10-x86-2](https://openj9-jenkins.osuosl.org/computer/mac10-x86-2), [mac10-x86-3](https://openj9-jenkins.osuosl.org/computer/mac10-x86-3), [mac10-x86-4](https://openj9-jenkins.osuosl.org/computer/mac10-x86-4), [mac10-x86-5](https://openj9-jenkins.osuosl.org/computer/mac10-x86-5), .

**Comment by pshipton** [comment]
@tajila @JasonFengJ9

**Comment by JasonFengJ9** [comment]
Will triage

**Comment by JasonFengJ9** [comment]
[200x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/28977/) passed
Launched a grinder on [mac11-x86-2](https://openj9-jenkins.osuosl.org/computer/mac11-x86-2) https://openj9-jenkins.osuosl.org/job/Grinder/1451/

**Comment by ChengJin01** [comment]
Close this issue given the problem can't  be reproduced so far.
