### ISSUE TITLE
When openj9 calls the offsetByCodePoints (int index, int codePointOffset) function with the parameter “- XX:+CompactStrings”, it will get incorrect results.

### ISSUE THREAD

**Issue by ayuan0828** [eclipse-openj9/openj9#16188]
**Description**:

Run the following test case，when the offsetByCodePoints (int index, int codePointOffset) function is called, if the index value obtained is negative, OpenJ9 using the "CompactStrings"parameter will not get the "IndexOutOfBoundsException", just as OpenJ9 without this parameter outputs.

**Environment**：

```
Ubuntu 18.04 x86_64
```

**JVM Information**:
jdk8:

```openjdk version "1.8.0_332-internal"
OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_02_17_10_23-b00)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 301202f49f based on jdk8u332-b02)
```

jdk11:

```openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 11 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 24e7209ed4 based on jdk-11.0.15+1)
```

**Testcase**:

```public class Test {
    public class Test {
    public static void main(String[] args) throws Exception {
        String str = "123";
        System.out.println(str.offsetByCodePoints(0, -1));
    }
}
```

**Output of OpenJ9(with  -XX:+CompactStrings)**:

```
-1
```

**Output of OpenJ9(default)**:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.lang.String.offsetByCodePoints(String.java:4051)
	at Test.main(Test.java:4)
```

**Comment by pshipton** [comment]
@tajila @mikezhang1234567890 fyi

**Comment by mikezhang1234567890** [comment]
Looks like we're missing a bounds check in our implementation of `String`, `StringBuffer`, and `StringBuilder`. 

Will create PR with the fix and updated tests for the failure modes soon.
