### ISSUE TITLE
jdk19 VmArgumentTests testXcheckMemory Target process failed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16192]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_s390x_linux_Nightly_testList_0/27
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_aarch64_linux_Nightly_testList_1/25
VmArgumentTests_0
```
FAILED: testXcheckMemory
java.lang.AssertionError: Target process failed
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.vmArguments.VmArgumentTests.runProcess(VmArgumentTests.java:1633)
	at org.openj9.test.vmArguments.VmArgumentTests.runAndGetArgumentList(VmArgumentTests.java:1593)
	at org.openj9.test.vmArguments.VmArgumentTests.testXcheckMemory(VmArgumentTests.java:303)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_ppc64le_linux_Nightly_testList_1/25
VmArgumentTests_0 
```
FAILED: testMemoryLeaks
java.lang.AssertionError: Target process failed
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.vmArguments.VmArgumentTests.runProcess(VmArgumentTests.java:1633)
	at org.openj9.test.vmArguments.VmArgumentTests.runAndGetArgumentList(VmArgumentTests.java:1593)
	at org.openj9.test.vmArguments.VmArgumentTests.testMemoryLeaks(VmArgumentTests.java:1287)

FAILED: testXcheckMemory
java.lang.AssertionError: Target process failed
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.vmArguments.VmArgumentTests.runProcess(VmArgumentTests.java:1633)
	at org.openj9.test.vmArguments.VmArgumentTests.runAndGetArgumentList(VmArgumentTests.java:1593)
	at org.openj9.test.vmArguments.VmArgumentTests.testXcheckMemory(VmArgumentTests.java:303)
```

**Comment by pshipton** [comment]
Perhaps related to https://github.com/eclipse-openj9/openj9/issues/16191

**Comment by pshipton** [comment]
Changes from last build
https://github.com/eclipse-openj9/openj9/compare/bb7dc4eaba0...1a8e36dcc425

**Comment by pshipton** [comment]
It's possible the problem was introduced in https://github.com/eclipse-openj9/openj9/compare/bb7dc4eaba0...1a8e36dcc425 as there was an alinux only build where this problem was not seen.

https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/184/

**Comment by pshipton** [comment]
Closing assuming fixed by https://github.com/eclipse-openj9/openj9/pull/16195
