### ISSUE TITLE
jdk19 OpenJDK java/lang/reflect/IllegalArgumentsTest.java Cannot invoke "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" because "x" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16204]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64_aix_Nightly/35/
jdk_lang_1
java/lang/reflect/IllegalArgumentsTest.java
```
00:24:37  test IllegalArgumentsTest.nullArguments(): failure
00:24:37  java.lang.reflect.InvocationTargetException
00:24:37  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:77)
00:24:37  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
00:24:37  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
00:24:37  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)
00:24:37  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:24:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
00:24:37  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
00:24:37  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
00:24:37  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
00:24:37  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
00:24:37  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
00:24:37  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
00:24:37  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
00:24:37  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
00:24:37  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
00:24:37  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
00:24:37  	at org.testng.TestRunner.run(TestRunner.java:585)
00:24:37  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
00:24:37  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
00:24:37  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
00:24:37  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
00:24:37  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
00:24:37  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
00:24:37  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
00:24:37  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
00:24:37  	at org.testng.TestNG.runSuites(TestNG.java:1069)
00:24:37  	at org.testng.TestNG.run(TestNG.java:1037)
00:24:37  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:24:37  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:24:37  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:24:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
00:24:37  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:24:37  	at java.base/java.lang.Thread.run(Thread.java:1573)
00:24:37  Caused by: java.lang.NullPointerException: Cannot invoke "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" because "x" is null
00:24:37  	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
00:24:37  	at <unknown class>.<unknown method>(Unknown Source)
00:24:37  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
00:24:37  	... 32 more
```

**Comment by pshipton** [comment]
@tajila @0xdaryl fyi

**Comment by tajila** [comment]
10x grinder, https://openj9-jenkins.osuosl.org/job/Grinder/1494/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_Nightly/44
jdk_lang_1 
java/lang/reflect/IllegalArgumentsTest.java
```
22:45:08  test IllegalArgumentsTest.nullArguments(): failure
22:45:08  java.lang.reflect.InvocationTargetException
22:45:08  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:77)
22:45:08  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
22:45:08  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
22:45:08  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)
22:45:08  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:45:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
22:45:08  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:45:08  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:45:08  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:45:08  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:45:08  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:45:08  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:45:08  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:45:08  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:45:08  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
22:45:08  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
22:45:08  	at org.testng.TestRunner.run(TestRunner.java:585)
22:45:08  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:45:08  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:45:08  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:45:08  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:45:08  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:45:08  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:45:08  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:45:08  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:45:08  	at org.testng.TestNG.runSuites(TestNG.java:1069)
22:45:08  	at org.testng.TestNG.run(TestNG.java:1037)
22:45:08  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:45:08  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:45:08  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:45:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
22:45:08  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:45:08  	at java.base/java.lang.Thread.run(Thread.java:1573)
22:45:08  Caused by: java.lang.NullPointerException: Cannot invoke "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" because "x" is null
22:45:08  	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
22:45:08  	at <unknown class>.<unknown method>(Unknown Source)
22:45:08  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
22:45:08  	... 32 more
```

**Comment by tajila** [comment]
This may be a ojdkmh issue

**Comment by tajila** [comment]
Closing as we havent seen this issue recently
