### ISSUE TITLE
jdk20 Thread.stop(), suspend(), resume() tests failing, due to UnsupportedOperationException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16213]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_mac_Nightly_testList_0/66
JCL_Test
```
FAILED: test_resume
java.lang.UnsupportedOperationException
	at java.base/java.lang.Thread.suspend(Thread.java:1813) from jrt:/java.base
	at org.openj9.test.java.lang.Test_Thread.test_resume(Test_Thread.java:746) from 

FAILED: test_stop
java.lang.UnsupportedOperationException
	at java.base/java.lang.Thread.stop(Thread.java:1650) from jrt:/java.base
	at org.openj9.test.java.lang.Test_Thread.test_stop(Test_Thread.java:977) from 

FAILED: test_stop5
java.lang.AssertionError: Unexpected exception:
	at org.testng.Assert.fail(Assert.java:85) from jdk.internal.loader.ClassLoaders$AppClassLoader@344a0c77(file:/Users/jenkins/workspace/Test_openjdknext_j9_sanity.functional_aarch64_mac_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Thread.test_stop5(Test_Thread.java:1018) from 

FAILED: test_suspend
java.lang.UnsupportedOperationException
	at java.base/java.lang.Thread.suspend(Thread.java:1813) from jrt:/java.base
	at org.openj9.test.java.lang.Test_Thread.test_suspend(Test_Thread.java:1035) from 
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_mac_Nightly_testList_1/66
J9vmTest 

This hangs the test suite.
```
17:00:20  +++ j9vm.test.clinit.BlockDuringClinitTest: +++
17:00:20  Runner couldn't determine underlying architecture. Got OS Arch:aarch64
17:00:20  command: /Users/jenkins/workspace/Test_openjdknext_j9_sanity.functional_aarch64_mac_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m    -classpath /Users/jenkins/workspace/Test_openjdknext_j9_sanity.functional_aarch64_mac_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/Users/jenkins/workspace/Test_openjdknext_j9_sanity.functional_aarch64_mac_Nightly_testList_1/aqa-tests/TKG/../TKG/lib/asm-all.jar  j9vm.test.clinit.BlockDuringClinitTest 
17:00:20  
17:00:20  <clinit> vs. new...
17:00:25  Exception in thread "main" java.lang.UnsupportedOperationException
17:00:25  	at java.base/java.lang.Thread.stop(Thread.java:1650)
17:00:25  	at j9vm.test.clinit.NewDuringClinit.test(NewDuringClinit.java:108)
17:00:25  	at j9vm.test.clinit.BlockDuringClinitTest.run(BlockDuringClinitTest.java:30)
17:00:25  	at j9vm.test.clinit.BlockDuringClinitTest.main(BlockDuringClinitTest.java:44)
```

**Comment by JasonFengJ9** [comment]
Related to https://github.com/eclipse-openj9/openj9/issues/16028
