### ISSUE TITLE
"No route to host" on rh7-390-2

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16224]
Friday night many network related failures occurred on https://openj9-jenkins.osuosl.org/computer/rh7-390-2/
I disabled the machine.

Example, one of many.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_0/396/

```
NLT Caused by: java.net.NoRouteToHostException: No route to host
NLT 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
NLT 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
NLT 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
NLT 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
NLT 	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
NLT 	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
NLT 	... 3 more
```

@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_1/395/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/396/ - this one hung, I assume because of the network problem
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_s390x_linux_Nightly_testList_1/340/

**Comment by pshipton** [comment]
Removed `ci.role.test` label and trying a small grinder https://openj9-jenkins.osuosl.org/job/Grinder/1466

**Comment by pshipton** [comment]
The problem still occurs, the reboot didn't fix it. Did something modify the ip address of the machine (148.100.85.138), or set a firewall so the machine can't connect to itself? Is 148.100.85.138 the expected IP?

**Comment by pshipton** [comment]
New grinder https://openj9-jenkins.osuosl.org/job/Grinder/1468/

**Comment by pshipton** [comment]
Working now, thanks.
