### ISSUE TITLE
JVMTI Serviceability GetThreadInfo/thrinfo01 Fails

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#16226]
`GetThreadInfo/thrinfo01` passes with the RI. This issue is unrelated to virtual threads (Project Loom), and will presumably also be seen with JDK8/11/17.

Related: #16187.

### Issue
For a platform thread, the `thread_group` returned by `jvmtiGetThreadInfo` does not match the expected value. The following check fails:
```
  if (!jni->IsSameObject(thread_group, inf.thread_group)) {
    LOG("Thread %s: invalid thread thread_group\n", expected_info.name);
    result = JNI_FALSE;
  }
```

### Test CMD
```
make test TEST="jtreg:test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadInfo/thrinfo01" JTREG="JAVA_OPTIONS=--enable-preview -Dvm.continuations=true;VERBOSE=all"
```

### Test Output
```
STDOUT:
Checking thread info for
Thread: 0x21dc58, name: main, state(5):  ALIVE RUNNABLE, attrs: kernel
Check completed.
Checking thread info for
Thread: 0x21dc58, name: thread1, state(0): <none>, attrs: kernel daemon
Thread thread1: invalid thread thread_group
Check completed.
STDERR:
java.lang.RuntimeException: Error in checkInfo. See log.
    at thrinfo01.checkInfo(thrinfo01.java:67)
    at thrinfo01.main(thrinfo01.java:80)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:578)
    at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
    at java.base/java.lang.Thread.run(Thread.java:1573)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Error in checkInfo. See log.
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Error in checkInfo. See log.
```

**Comment by babsingh** [comment]
@dipak-bagadiya Try reproducing the above failure in your local workspace using the `Test CMD`. Then, try to find the cause of the failure using the below resources and debugging tools such as `gdb`.
- Failing test code: [GetThreadInfo/thrinfo01/libthrinfo01.cpp#L98-L101](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/110e1e7808efdb0cdd180dfb12a22843777f3d3c/test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadInfo/thrinfo01/libthrinfo01.cpp#L98-L101)
- JVMTI GetThreadInfo Spec: https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html#GetThreadInfo
- OpenJ9's implementation of JVMTI GetThreadInfo: [runtime/jvmti/jvmtiThread.c#L433-L630](https://github.com/eclipse-openj9/openj9/blob/531e952f4f369f69a343fbb1ffe9768a0fbc8763/runtime/jvmti/jvmtiThread.c#L433-L630)

**Comment by babsingh** [comment]
fyi @dipak-bagadiya,
- The reference implementation (RI) uses [java.lang.Thread$FieldHolder.threadStatus](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/720d5357766d6cbb5dda08b469809da633f39129/src/java.base/share/classes/java/lang/Thread.java#L256) to derive a thread's state. For a platform thread, this value is stored in [java.lang.Thread.holder.threadStatus](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/720d5357766d6cbb5dda08b469809da633f39129/src/java.base/share/classes/java/lang/Thread.java#L272).
- @fengxue-IS's solution to use [java.lang.Thread.started](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/720d5357766d6cbb5dda08b469809da633f39129/src/java.base/share/classes/java/lang/Thread.java#L3187-L3188), to determine if a thread has not started, is also a valid solution.
