### ISSUE TITLE
JDK19 jdk_security4_0_FAILED sun/security/krb5/auto/Cleaners.java Exception: Proc abnormal end

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16248]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_ppc64_aix/20/)(`paix910`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-71f768a8b, JRE 19 AIX ppc64-64-Bit Compressed References 20221018_67 (JIT enabled, AOT enabled)
OpenJ9   - 71f768a8b
OMR      - 556374a61
JCL      - 9d79dbc153 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security4_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F67%2Fibm-semeru-open-jdk_ppc64_aix_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F67%2Fibm-semeru-open-jre_ppc64_aix_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F67%2Fibm-semeru-open-debugimage_ppc64_aix_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F67%2Fibm-semeru-open-testimage_ppc64_aix_JDK19U_2022-10-30-16-47.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-10-31T00:13:42.180Z] variation: Mode150
[2022-10-31T00:13:42.180Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-10-31T00:17:45.819Z] TEST: sun/security/krb5/auto/Cleaners.java

[2022-10-31T00:17:45.820Z] STDOUT:
[2022-10-31T00:17:45.820Z] Start KDC on 8816
[2022-10-31T00:17:45.820Z] -----------------------------------------------
[2022-10-31T00:17:45.820Z] >>>>> UDP packet received
[2022-10-31T00:17:45.820Z] REALM:8816> user@REALM sends AS-REQ for krbtgt/REALM@REALM, KDCOptions: FORWARDABLE,
[2022-10-31T00:17:45.820Z] KrbException: Additional pre-authentication required (25)
[2022-10-31T00:17:45.820Z] 	at KDC.processAsReq(KDC.java:1326)
[2022-10-31T00:17:45.820Z] 	at KDC.processMessage(KDC.java:800)
[2022-10-31T00:17:45.820Z] 	at KDC$1.run(KDC.java:1556)
[2022-10-31T00:17:45.820Z]      Error 25 Additional pre-authentication required

[2022-10-31T00:17:45.821Z] STDERR:
[2022-10-31T00:17:45.821Z] java.lang.Exception: Proc abnormal end
[2022-10-31T00:17:45.821Z] 	at jdk.test.lib.process.Proc.readData(Proc.java:377)
[2022-10-31T00:17:45.821Z] 	at Cleaners.main(Cleaners.java:106)
[2022-10-31T00:17:45.821Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-10-31T00:17:45.821Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-10-31T00:17:45.821Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-10-31T00:17:45.821Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-10-31T00:17:45.821Z] 
[2022-10-31T00:17:45.821Z] JavaTest Message: Test threw exception: java.lang.Exception: Proc abnormal end

[2022-10-31T00:17:45.822Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Proc abnormal end
[2022-10-31T00:17:45.822Z] --------------------------------------------------
[2022-10-31T00:27:57.507Z] Test results: passed: 149; failed: 1
[2022-10-31T00:28:06.524Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_16671540984931/jdk_security4_0/report/html/report.html
[2022-10-31T00:28:06.524Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_16671540984931/jdk_security4_0/work
[2022-10-31T00:28:06.524Z] Error: Some tests failed or other problems occurred.
[2022-10-31T00:28:06.864Z] 
[2022-10-31T00:28:06.864Z] jdk_security4_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29198/)

**Comment by pshipton** [comment]
It's a new test in jdk19. It also fails on a Temurin jdk19 nightly build.

**Comment by pshipton** [comment]
I marked it an an OpenJDK problem, although it could also be a machine problem.

**Comment by pshipton** [comment]
The test also fails on OpenJDK at https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_ppc64_aix_testList_0/28/testReport/sun_security_krb5_auto_Cleaners/java/Cleaners/

**Comment by psoujany** [comment]
This test is failing on z/OS with JDK21 and JDK25. Hence, excluding this test on z/OS.
