### ISSUE TITLE
jdk20 java.io.InvalidClassException: filter status: REJECTED

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16253]
https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/174/ extended.functional running on amac
testOpenJ9DiagnosticsMXBean_0 

```
FAILED CONFIGURATION: @AfterClass tearDown
java.lang.NullPointerException: Cannot read the array length because "<local8>" is null
	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.tearDown(TestOpenJ9DiagnosticsMXBean.java:196)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

PASSED: testLocal_resetDumpOptions
PASSED: testLocal_setDumpOptions
PASSED: testLocal_triggerClassicHeapDump
PASSED: testLocal_triggerDump
PASSED: testLocal_triggerDumpToFile
PASSED: testRemote_triggerClassicHeapDump
PASSED: testRemote_triggerDump
PASSED: testRemote_triggerDumpToFile
FAILED: testRemote_resetDumpOptions
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy1/jdk.proxy1.$Proxy6.setDumpOptions(Unknown Source)
	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.resetDumpOptions(TestOpenJ9DiagnosticsMXBean.java:525)
	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testRemote_resetDumpOptions(TestOpenJ9DiagnosticsMXBean.java:350)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.io.InvalidClassException: filter status: REJECTED
	at java.base/java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1556)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2188)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:2044)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2367)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1879)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:620)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:530)
	at java.rmi/java.rmi.MarshalledObject.get(MarshalledObject.java:183)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.unwrap(RMIConnectionImpl.java:1590)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.unwrap(RMIConnectionImpl.java:1632)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.setAttribute(RMIConnectionImpl.java:709)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:166)
	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.setAttribute(RMIConnectionImpl_Stub.java:556)
	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.setAttribute(RMIConnector.java:960)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy$SetHandler.invoke(MXBeanProxy.java:136)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
	at java.management/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
	... 25 more

FAILED: testRemote_setDumpOptions
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy1/jdk.proxy1.$Proxy6.setDumpOptions(Unknown Source)
	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testRemote_setDumpOptions(TestOpenJ9DiagnosticsMXBean.java:382)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.io.InvalidClassException: filter status: REJECTED
	at java.base/java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1556)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2188)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:2044)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2367)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1879)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:620)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:530)
	at java.rmi/java.rmi.MarshalledObject.get(MarshalledObject.java:183)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.unwrap(RMIConnectionImpl.java:1590)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.unwrap(RMIConnectionImpl.java:1632)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.setAttribute(RMIConnectionImpl.java:709)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:166)
	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.setAttribute(RMIConnectionImpl_Stub.java:556)
	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.setAttribute(RMIConnector.java:960)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy$SetHandler.invoke(MXBeanProxy.java:136)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
	at java.management/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
	... 24 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder_testList_1/77 sanity.system on amac
TestJlmRemoteNotifierProxyAuth_1 
```
STF 06:22:28.823 - +------ Step 5 - Wait for the processes to complete
STF 06:22:28.823 - | Wait for processes to meet expectations
STF 06:22:28.823 - |   Processes: [LT, CL]
STF 06:22:28.823 - |
STF 06:22:28.823 - Monitoring processes: CL  LT 
CL  j> 2022/11/03 06:22:29.145 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
CL  j> 2022/11/03 06:22:29.204 Attempting to connect
CL  j> 2022/11/03 06:22:29.320 Monitored VM not ready at Nov 3, 2022, 6:22:29 AM (attempt 1, elapsed 101ms).
CL  j> 2022/11/03 06:22:29.320 Waiting 5 secs and trying again...
CL  j> 2022/11/03 06:22:34.326 Attempting to connect
CL  j> 2022/11/03 06:22:36.536 Connection established!
CL  stderr Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
CL  stderr 	at jdk.proxy1/jdk.proxy1.$Proxy1.setCollectionUsageThreshold(Unknown Source)
CL  stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryNotifier.setServerThresholds(MemoryNotifier.java:119)
CL  stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryNotifier.<init>(MemoryNotifier.java:64)
CL  stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryNotifier.main(MemoryNotifier.java:81)
CL  stderr Caused by: java.io.InvalidClassException: filter status: REJECTED
CL  stderr 	at java.base/java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1556)
CL  stderr 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2188)
CL  stderr 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:2044)
CL  stderr 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2367)
CL  stderr 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1879)
CL  stderr 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:620)
CL  stderr 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:530)
CL  stderr 	at java.rmi/java.rmi.MarshalledObject.get(MarshalledObject.java:183)
CL  stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.lambda$unwrap$0(RMIConnectionImpl.java:1588)
CL  stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
CL  stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.unwrap(RMIConnectionImpl.java:1586)
CL  stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.unwrap(RMIConnectionImpl.java:1632)
CL  stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.setAttribute(RMIConnectionImpl.java:709)
CL  stderr 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
CL  stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
CL  stderr 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
CL  stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
CL  stderr 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
CL  stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
CL  stderr 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
CL  stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
CL  stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
CL  stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
CL  stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
CL  stderr 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
CL  stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
CL  stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
CL  stderr 	at java.base/java.lang.Thread.run(Thread.java:1575)
CL  stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
CL  stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
CL  stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:166)
CL  stderr 	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
CL  stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.setAttribute(RMIConnectionImpl_Stub.java:556)
CL  stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.setAttribute(RMIConnector.java:960)
CL  stderr 	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy$SetHandler.invoke(MXBeanProxy.java:136)
CL  stderr 	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
CL  stderr 	at java.management/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
CL  stderr 	... 4 more
```

**Comment by pshipton** [comment]
The class being rejected is javax.management.Attribute
