### ISSUE TITLE
jdk20 MathLoadTest ComparisonFailure such as expected:<1[.8E+3]> but was:<1[800]>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16254]
https://openj9-jenkins.osuosl.org/job/Grinder_testList_1/77 sanity.system running on amac
MathLoadTest_bigdecimal_CS_5m_0 
```
MLT testFailure: testItem_0659(net.adoptopenjdk.test.bigdecimal.TestSuite010): expected:<1[.8E+3]> but was:<1[800]>
MLT org.junit.ComparisonFailure: expected:<1[.8E+3]> but was:<1[800]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite010.testItem_0659(TestSuite010.java:4571)
```
https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/175
MathLoadTest_bigdecimal_5m_1 
```
MLT testFailure: testItem_0426(net.adoptopenjdk.test.bigdecimal.TestSuite030): expected:<4[E+2]> but was:<4[00]>
MLT org.junit.ComparisonFailure: expected:<4[E+2]> but was:<4[00]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite030.testItem_0426(TestSuite030.java:2999)

MLT testFailure: testItem_0691(net.adoptopenjdk.test.bigdecimal.TestSuite030): expected:<-1[E+19]> but was:<-1[0000000000000000000]>
MLT org.junit.ComparisonFailure: expected:<-1[E+19]> but was:<-1[0000000000000000000]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite030.testItem_0691(TestSuite030.java:4756)
```

**Comment by pshipton** [comment]
Tried MathLoadTest_bigdecimal_5m_1 on xlinux as well, where it also fails.
```
14:27:15  MLT testFailure: testItem_0659(net.adoptopenjdk.test.bigdecimal.TestSuite010): expected:<1[.8E+3]> but was:<1[800]>
14:27:15  MLT org.junit.ComparisonFailure: expected:<1[.8E+3]> but was:<1[800]>
14:27:15  MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
14:27:15  MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
14:27:15  MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite010.testItem_0659(TestSuite010.java:4571)
```

Also tried Hotspot xlinux, which failed
```
MLT testFailure: testItem_0159(net.adoptopenjdk.test.bigdecimal.TestSuite019): expected:<-4[E+1]> but was:<-4[0]>
MLT org.junit.ComparisonFailure: expected:<-4[E+1]> but was:<-4[0]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite019.testItem_0159(TestSuite019.java:1064)
```

Tried Hotspot with -Xint
```
MLT testFailure: testItem_0740(net.adoptopenjdk.test.bigdecimal.TestSuite060): expected:<-3[.59538626972463141629054847463408713596141135051689993197834953606314521560057077521179117265533756343080917907028764928468642653778928365536935093407075033972099821153102564152490980180778657888151737016910267884609166473806445896331617118664246696549595652408289446337476354361838599762500808052368249716736E+616]> but was:<-3[5953862697246314162905484746340871359614113505168999319783495360631452156005707752117911726553375634308091790702876492846864265377892836553693509340707503397209982115310256415249098018077865788815173701691026788460916647380644589633161711866424669654959565240828944633747635436183859976250080805236824971673600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]>
MLT org.junit.ComparisonFailure: expected:<-3[.59538626972463141629054847463408713596141135051689993197834953606314521560057077521179117265533756343080917907028764928468642653778928365536935093407075033972099821153102564152490980180778657888151737016910267884609166473806445896331617118664246696549595652408289446337476354361838599762500808052368249716736E+616]> but was:<-3[5953862697246314162905484746340871359614113505168999319783495360631452156005707752117911726553375634308091790702876492846864265377892836553693509340707503397209982115310256415249098018077865788815173701691026788460916647380644589633161711866424669654959565240828944633747635436183859976250080805236824971673600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite060.testItem_0740(TestSuite060.java:5210)
```

**Comment by pshipton** [comment]
I assume the failures are related to the following change in jdk20. I don't know why the failures seem to happen randomly in different places. @Mesbah-Alam the test needs to be fixed.

Restore Behavior of java.math.BigDecimal.movePointLeft() and movePointRight() on a Zero Argument ([JDK-8289260](https://bugs.openjdk.org/browse/JDK-8289260))
core-libs/java.math
When these methods are invoked with a zero argument on a target with a negative scale, they return a result which is numerically the same as the target, but with a different unscaled value and scale.
In earlier releases, they returned a result with the same unscaled value and scale, which was against the specification.
The behavior is unchanged when the target has a non-negative scale or when the argument is not zero.

**Comment by pshipton** [comment]
Looking at the places which fail, they contains a check for `JavaSpecVersionChecker.isJDK13OrNewer()`.

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
@Mesbah-Alam could you look into this? Thanks

**Comment by Mesbah-Alam** [comment]
These test cases are [auto-generated](https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITestGenerator.java), and it appears some of them (and there are multiple ones based on discussions above) are invalid for JDK20. The validator values  will have to either be manually updated or tests regenerated. I will exclude the MathLoadTest on JDK20 temporarily while we fix this.

**Comment by Mesbah-Alam** [comment]
PR for exclude: https://github.com/adoptium/aqa-tests/pull/4144.
