### ISSUE TITLE
JDK19 (aarch64_mac)  jdk_vector failures - AssertionError: at index #0, input1 = 0.0, input2 = 0.0, mask = false expected [0.0] but found [9.852035E-16]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16278]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_1/53/)(`macaarch64rt1`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-f6c7bee4b, JRE 19 Mac OS X aarch64-64-Bit 20221018_70 (JIT enabled, AOT enabled)
OpenJ9   - f6c7bee4b
OMR      - 357df2f80
JCL      - 110e1e7808 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_vector_float128_j9_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_sanity.openjdk_aarch64_mac&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-aarch64-openj9%2F70%2Fibm-semeru-open-jdk_aarch64_mac_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-aarch64-openj9%2F70%2Fibm-semeru-open-testimage_aarch64_mac_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-aarch64-openj9%2F70%2Fibm-semeru-open-jre_aarch64_mac_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-aarch64-openj9%2F70%2Fibm-semeru-open-debugimage_aarch64_mac_JDK19U_2022-11-05-15-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=55&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-11-05T16:41:39.191Z] variation: -Xjit:{*Float128VectorTests*}(count=1,enforceVectorAPIExpansion),disableAsyncCompilation,disableSuffixLogs,verbose={vectorAPI}
[2022-11-05T16:41:39.191Z] JVM_OPTIONS:  -Xjit:{*Float128VectorTests*}(count=1,enforceVectorAPIExpansion),disableAsyncCompilation,disableSuffixLogs,verbose={vectorAPI} 

[2022-11-05T16:42:55.536Z] TEST: jdk/incubator/vector/Float128VectorTests.java

[2022-11-05T16:42:55.536Z] STDOUT:

[2022-11-05T16:42:55.539Z] test Float128VectorTests.subFloat128VectorTestsBroadcastMaskedSmokeTest(float[-i * 5], float[i * 5], mask[false]): failure
[2022-11-05T16:42:55.539Z] java.lang.AssertionError: at index #0, input1 = 0.0, input2 = 0.0, mask = false expected [0.0] but found [9.852035E-16]
[2022-11-05T16:42:55.539Z] 	at org.testng.Assert.fail(Assert.java:99)
[2022-11-05T16:42:55.539Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2022-11-05T16:42:55.539Z] 	at org.testng.Assert.assertEquals(Assert.java:774)
[2022-11-05T16:42:55.539Z] 	at Float128VectorTests.assertBroadcastArraysEquals(Float128VectorTests.java:456)
[2022-11-05T16:42:55.539Z] 	at Float128VectorTests.assertBroadcastArraysEquals(Float128VectorTests.java:446)
[2022-11-05T16:42:55.539Z] 	at Float128VectorTests.subFloat128VectorTestsBroadcastMaskedSmokeTest(Float128VectorTests.java:1910)
[2022-11-05T16:42:55.539Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-11-05T16:42:55.539Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-11-05T16:42:55.539Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-11-05T16:42:55.539Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-11-05T16:42:55.539Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-11-05T16:42:55.539Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-11-05T16:42:55.539Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-11-05T16:42:55.539Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-11-05T16:42:55.539Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-11-05T16:42:55.539Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-11-05T16:42:55.539Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-11-05T16:42:55.539Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-11-05T16:42:55.539Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-11-05T16:42:55.539Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-11-05T16:42:55.539Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-11-05T16:42:55.539Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-11-05T16:42:55.539Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-11-05T16:42:55.539Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-11-05T16:42:55.539Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-11-05T16:42:55.539Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-11-05T16:42:55.539Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-11-05T16:42:55.539Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)

[2022-11-05T16:42:55.543Z] STDERR:
[2022-11-05T16:42:55.543Z] #INFO:  AOT header validation failed: AsyncCompilation feature mismatch.

[2022-11-05T16:42:55.549Z] #VECTOR API: Vectorized using vstoreiVector128Float in Float128VectorTests.toLongArrayFloat128VectorTestsSmokeTest(Ljava/util/function/IntFunction;)V at scorching
[2022-11-05T16:42:55.549Z] java.lang.Exception: failures: 129
[2022-11-05T16:42:55.549Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2022-11-05T16:42:55.549Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-11-05T16:42:55.549Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-11-05T16:42:55.549Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-11-05T16:42:55.549Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-11-05T16:42:55.549Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-05T16:42:55.549Z] 
[2022-11-05T16:42:55.549Z] JavaTest Message: Test threw exception: java.lang.Exception: failures: 129

[2022-11-05T16:42:55.549Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 129
[2022-11-05T16:42:55.549Z] --------------------------------------------------
[2022-11-05T16:42:55.549Z] Test results: failed: 1
[2022-11-05T16:42:55.549Z] Report written to /Users/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_1/aqa-tests/TKG/output_16676664061341/jdk_vector_float128_j9_0/report/html/report.html
[2022-11-05T16:42:55.549Z] Results written to /Users/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_1/aqa-tests/TKG/output_16676664061341/jdk_vector_float128_j9_0/work
[2022-11-05T16:42:55.549Z] Error: Some tests failed or other problems occurred.
[2022-11-05T16:42:55.549Z] 
[2022-11-05T16:42:55.549Z] jdk_vector_float128_j9_0_FAILED
```

Similar failures at [jdk_vector_short128_j9_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_1/53/), [jdk_vector_long128_j9_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_1/53/), [jdk_vector_double128_j9_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_0/53/), [jdk_vector_byte128_j9_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_0/53/), [jdk_vector_int128_j9_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_testList_0/53/).

fyi @gita-omr

**Comment by pshipton** [comment]
Maybe related to https://github.com/eclipse-openj9/openj9/issues/16255
@knn-k @Akira1Saitoh

**Comment by Akira1Saitoh** [comment]
It seems to be the same issue with #16255. The failure disappears with https://github.com/eclipse/omr/pull/6802 and https://github.com/eclipse/omr/pull/6803.

**Comment by pshipton** [comment]
I'll close it as a dup.
