### ISSUE TITLE
JDK19 AIX serviceability_jvmti_j9_0_FAILED serviceability/jvmti/vthread/VThreadNotifyFramePopTest/VThreadNotifyFramePopTest.java java.lang.UnsupportedOperationException: Unimplemented on AIX

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16279]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_ppc64_aix/21/)(`paix820`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-f6c7bee4b, JRE 19 AIX ppc64-64-Bit Compressed References 20221018_70 (JIT enabled, AOT enabled)
OpenJ9   - f6c7bee4b
OMR      - 357df2f80
JCL      - 110e1e7808 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F70%2Fibm-semeru-open-testimage_ppc64_aix_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F70%2Fibm-semeru-open-jdk_ppc64_aix_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F70%2Fibm-semeru-open-debugimage_ppc64_aix_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-aix-ppc64-openj9%2F70%2Fibm-semeru-open-jre_ppc64_aix_JDK19U_2022-11-05-15-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-11-05T18:35:13.316Z] TEST: serviceability/jvmti/vthread/VThreadNotifyFramePopTest/VThreadNotifyFramePopTest.java

[2022-11-05T18:35:13.318Z] STDERR:
[2022-11-05T18:35:13.318Z] java.lang.UnsupportedOperationException: Unimplemented on AIX
[2022-11-05T18:35:13.318Z] java.lang.UnsupportedOperationException: Unimplemented on AIX
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.PollsetPoller.poll(PollsetPoller.java:60)
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.Poller.poll(Poller.java:363)
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.Poller.pollLoop(Poller.java:270)
[2022-11-05T18:35:13.318Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.PollsetPoller.poll(PollsetPoller.java:60)
[2022-11-05T18:35:13.318Z] java.lang.UnsupportedOperationException: Unimplemented on AIX
[2022-11-05T18:35:13.318Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.Poller.poll(Poller.java:363)
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.Poller.pollLoop(Poller.java:270)
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.PollsetPoller.implRegister(PollsetPoller.java:48)
[2022-11-05T18:35:13.318Z] 	at java.base/sun.nio.ch.Poller.updateLoop(Poller.java:289)
[2022-11-05T18:35:13.318Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-05T18:35:13.318Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-05T18:35:13.318Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
[2022-11-05T18:35:13.318Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)

[2022-11-05T18:35:13.318Z] Test results: passed: 110; failed: 2; error: 1
[2022-11-05T18:35:19.424Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/report/html/report.html
[2022-11-05T18:35:19.425Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_1667671703655/serviceability_jvmti_j9_0/work
[2022-11-05T18:35:19.425Z] Error: Some tests failed or other problems occurred.
[2022-11-05T18:35:19.425Z] 
[2022-11-05T18:35:19.425Z] serviceability_jvmti_j9_0_FAILED
```

Not supported by OpenJ9 yet, will exclude it.

**Comment by fengxue-IS** [comment]
This exception is thrown from OpenJDK JCL code ([src/java.base/aix/classes/sun/nio/ch/PollsetPoller.java](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/aix/classes/sun/nio/ch/PollsetPoller.java)), I suppose RI should have identical behaviour. This can be ignored for now unless we would like to implement OpenJ9's own version of this class

**Comment by babsingh** [comment]
Yes, OpenJ9 has the same behaviour as the RI since they share the same class file. Also, `sun.nio.ch.PollsetPoller` is not covered by the Javadoc. So, we are not obliged to support it. Moving this issue to backlog.

@pshipton Can we permanently exclude this test, and close this issue?

**Comment by pshipton** [comment]
Sure.

**Comment by JasonFengJ9** [comment]
```
[2022-11-10T19:52:10.652Z] TEST: java/nio/channels/vthread/BlockingChannelOps.java#id0

[2022-11-10T20:32:03.992Z] TEST: java/nio/channels/vthread/BlockingChannelOps.java#id1

[2022-11-10T20:32:04.003Z] STDERR:
[2022-11-10T20:32:04.003Z] java.lang.UnsupportedOperationException: Unimplemented on AIX
[2022-11-10T20:32:04.003Z] java.lang.UnsupportedOperationException: Unimplemented on AIX
[2022-11-10T20:32:04.003Z] java.lang.UnsupportedOperationException: Unimplemented on AIX
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.PollsetPoller.implRegister(PollsetPoller.java:48)
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.Poller.updateLoop(Poller.java:289)
[2022-11-10T20:32:04.003Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-10T20:32:04.003Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.PollsetPoller.poll(PollsetPoller.java:60)
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.Poller.poll(Poller.java:363)
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.Poller.pollLoop(Poller.java:270)
[2022-11-10T20:32:04.003Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-10T20:32:04.003Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.PollsetPoller.poll(PollsetPoller.java:60)
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.Poller.poll(Poller.java:363)
[2022-11-10T20:32:04.003Z] 	at java.base/sun.nio.ch.Poller.pollLoop(Poller.java:270)
[2022-11-10T20:32:04.003Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-11-10T20:32:04.003Z] 	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
```

Excluding via https://github.com/adoptium/aqa-tests/pull/4151
