### ISSUE TITLE
JDK19 serviceability_jvmti_j9_0_FAILED serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java Illegal instruction vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16274]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_windows/19/)(`win16x64rt2-6`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-f6c7bee4b, JRE 19 Windows Server 2016 amd64-64-Bit Compressed References 20221018_69 (JIT enabled, AOT enabled)
OpenJ9   - f6c7bee4b
OMR      - 357df2f80
JCL      - 110e1e7808 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F69%2Fibm-semeru-open-jdk_x64_windows_JDK19U_2022-11-05-15-59.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F69%2Fibm-semeru-open-testimage_x64_windows_JDK19U_2022-11-05-15-59.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F69%2Fibm-semeru-open-debugimage_x64_windows_JDK19U_2022-11-05-15-59.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-windows-x64-openj9%2F69%2Fibm-semeru-open-jre_x64_windows_JDK19U_2022-11-05-15-59.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-11-05T18:57:07.277Z] variation: Mode150
[2022-11-05T18:57:08.150Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-11-05T19:05:48.863Z] TEST: serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java

[2022-11-05T19:05:48.866Z] STDERR:
[2022-11-05T19:05:48.866Z] Unhandled exception
[2022-11-05T19:05:48.866Z] Type=Illegal instruction vmState=0x00000000
[2022-11-05T19:05:48.866Z] Windows_ExceptionCode=c000001d J9Generic_Signal=00000010 ExceptionAddress=00007FF7BDE0692D ContextFlags=0010005f
[2022-11-05T19:05:48.866Z] Handler1=00007FFC985EC230 Handler2=00007FFC9A87AA50
[2022-11-05T19:05:48.866Z] RDI=FFFFFFFFDEAE1090 RSI=00000000FFE822D8 RAX=000000000000000E RBX=00000000001D1800
[2022-11-05T19:05:48.866Z] RCX=0000000000094DA0 RDX=0000004CBF07F568 R8=0000000000000000 R9=0000000000000000
[2022-11-05T19:05:48.866Z] R10=0000015BEC088BE0 R11=00007FFC9A872E00 R12=0000000000000058 R13=00007FFC9A62E160
[2022-11-05T19:05:48.866Z] R14=00000000001D6800 R15=0000000000000000
[2022-11-05T19:05:48.866Z] RIP=00007FF7BDE0692D RSP=0000000000286C50 RBP=00000000002A7400 EFLAGS=0000000000010206
[2022-11-05T19:05:48.866Z] FS=0053 ES=002B DS=002B
[2022-11-05T19:05:48.866Z] XMM0 0000000000286c91 (f: 2649233.000000, d: 1.308895e-317)
[2022-11-05T19:05:48.866Z] XMM1 0000000000094ba0 (f: 609184.000000, d: 3.009769e-318)
[2022-11-05T19:05:48.866Z] XMM2 42e3fab2bca47b40 (f: 3164896000.000000, d: 1.757397e+14)
[2022-11-05T19:05:48.866Z] XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] Unhandled exception
[2022-11-05T19:05:48.866Z] Type=Illegal instruction vmState=0x00000000
[2022-11-05T19:05:48.866Z] Windows_ExceptionCode=c000001d J9Generic_Signal=00000010 ExceptionAddress=00007FF7BDE0692D ContextFlags=0010005f
[2022-11-05T19:05:48.866Z] Handler1=00007FFC985EC230 Handler2=00007FFC9A87AA50
[2022-11-05T19:05:48.866Z] RDI=FFFFFFFFE96D5914 RSI=00000000FFE824E8 RAX=000000000000000E RBX=00000000FFDA53D8
[2022-11-05T19:05:48.866Z] RCX=0000000000094DA0 RDX=0000004CBF17F238 R8=0000000000000000 R9=0000000000000001
[2022-11-05T19:05:48.866Z] R10=00000000002B6418 R11=00007FFC97FD2E00 R12=00000000E003ABB8 R13=00000000FFDA53D8
[2022-11-05T19:05:48.866Z] R14=00000000FFDA53D8 R15=0000000000000000
[2022-11-05T19:05:48.866Z] RIP=00007FF7BDE0692D RSP=00000000002CB550 RBP=00000000002AB000 EFLAGS=0000000000010206
[2022-11-05T19:05:48.866Z] FS=0053 ES=002B DS=002B
[2022-11-05T19:05:48.866Z] XMM0 00000000002cb591 (f: 2930065.000000, d: 1.447644e-317)
[2022-11-05T19:05:48.866Z] XMM1 0000000000094ba0 (f: 609184.000000, d: 3.009769e-318)
[2022-11-05T19:05:48.866Z] XMM2 42e3fab2bcb25360 (f: 3165803264.000000, d: 1.757397e+14)
[2022-11-05T19:05:48.866Z] XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.866Z] Module=
[2022-11-05T19:05:48.866Z] Module_base_address=00007FF7BDBF0000 Offset_in_DLL=000000000021692d
[2022-11-05T19:05:48.866Z] 
[2022-11-05T19:05:48.866Z] Compiled_method=java/io/BufferedWriter.min(II)I
[2022-11-05T19:05:48.866Z] Target=2_90_20221018_69 (Windows Server 2016 10.0 build 14393)
[2022-11-05T19:05:48.866Z] CPU=amd64 (8 logical CPUs) (0x3fff78000 RAM)
[2022-11-05T19:05:48.866Z] ----------- Stack Backtrace -----------
[2022-11-05T19:05:48.866Z] Module=
[2022-11-05T19:05:48.866Z] Module_base_address=00007FF7BDBF0000 Offset_in_DLL=000000000021692d
[2022-11-05T19:05:48.866Z] 
[2022-11-05T19:05:48.866Z] Compiled_method=java/io/BufferedWriter.min(II)I
[2022-11-05T19:05:48.866Z] Target=2_90_20221018_69 (Windows Server 2016 10.0 build 14393)
[2022-11-05T19:05:48.866Z] CPU=amd64 (8 logical CPUs) (0x3fff78000 RAM)
[2022-11-05T19:05:48.866Z] ----------- Stack Backtrace -----------
[2022-11-05T19:05:48.866Z] Unhandled exception
[2022-11-05T19:05:48.866Z] Type=Illegal instruction vmState=0x00000000
[2022-11-05T19:05:48.866Z] Windows_ExceptionCode=c000001d J9Generic_Signal=00000010 ExceptionAddress=00007FF7BDE0692D ContextFlags=0010005f
[2022-11-05T19:05:48.866Z] Handler1=00007FFC985EC230 Handler2=00007FFC9A87AA50
[2022-11-05T19:05:48.866Z] RDI=FFFFFFFFDEAC15B0 RSI=00000000FFE823E0 RAX=000000000000000E RBX=00000000001D1800
[2022-11-05T19:05:48.866Z] RCX=0000000000094DA0 RDX=0000004CBF37F138 R8=0000000000000000 R9=0000000000000000
[2022-11-05T19:05:48.866Z] R10=0000015BEC088BE0 R11=00007FFC9A872E00 R12=0000000000000058 R13=00007FFC9A62E160
[2022-11-05T19:05:48.866Z] R14=00000000001D6800 R15=0000000000000000
[2022-11-05T19:05:48.867Z] RIP=00007FF7BDE0692D RSP=00000000002E37F0 RBP=00000000002B2A00 EFLAGS=0000000000010206
[2022-11-05T19:05:48.867Z] FS=0053 ES=002B DS=002B
[2022-11-05T19:05:48.867Z] XMM0 00000000002e3831 (f: 3029041.000000, d: 1.496545e-317)
[2022-11-05T19:05:48.867Z] XMM1 0000000000094ba0 (f: 609184.000000, d: 3.009769e-318)
[2022-11-05T19:05:48.867Z] XMM2 42e3fab2bcac03e0 (f: 3165389824.000000, d: 1.757397e+14)
[2022-11-05T19:05:48.867Z] XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T19:05:48.867Z] Module=
[2022-11-05T19:05:48.867Z] Module_base_address=00007FF7BDBF0000 Offset_in_DLL=000000000021692d
[2022-11-05T19:05:48.867Z] 
[2022-11-05T19:05:48.867Z] Compiled_method=java/io/BufferedWriter.min(II)I
[2022-11-05T19:05:48.867Z] Target=2_90_20221018_69 (Windows Server 2016 10.0 build 14393)
[2022-11-05T19:05:48.867Z] CPU=amd64 (8 logical CPUs) (0x3fff78000 RAM)
[2022-11-05T19:05:48.867Z] ----------- Stack Backtrace -----------
[2022-11-05T19:05:48.867Z] (0x00007FF7BDE0692D)
[2022-11-05T19:05:48.867Z] (0x0000000000000001)
[2022-11-05T19:05:48.867Z] (0x0000000000274810)
[2022-11-05T19:05:48.867Z] (0x0000015BD8DA739F)
[2022-11-05T19:05:48.867Z] (0x00007FF7BDE0692D)
[2022-11-05T19:05:48.867Z] (0x0000000000000001)
[2022-11-05T19:05:48.867Z] (0x0000000000286C88)
[2022-11-05T19:05:48.867Z] (0x0000000000274810)
[2022-11-05T19:05:48.867Z] (0x000003E800000001)
[2022-11-05T19:05:48.867Z] (0x0000015BD8DA739F)
[2022-11-05T19:05:48.867Z] (0x00000000002B6428)
[2022-11-05T19:05:48.867Z] (0x000003E800000001)
[2022-11-05T19:05:48.867Z] Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x56d850 (0x00007FFC943D9240 [j9jit29+0x639240])
[2022-11-05T19:05:48.867Z] (0x00000000FFE6B2D8)
[2022-11-05T19:05:48.867Z] (0x00000000FFDA5118)
[2022-11-05T19:05:48.867Z] (0x000000000025F5E8)
[2022-11-05T19:05:48.867Z] (0x0000015BD8DA36AE)
[2022-11-05T19:05:48.867Z] (0x00000000002CB610)
[2022-11-05T19:05:48.867Z] ---------------------------------------
[2022-11-05T19:05:48.867Z] Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x56d850 (0x00007FFC943D9240 [j9jit29+0x639240])
[2022-11-05T19:05:48.867Z] (0x00000000FFE6B1D8)
[2022-11-05T19:05:48.867Z] (0x00000000FFDA48E8)
[2022-11-05T19:05:48.867Z] (0x000000000025F5E8)
[2022-11-05T19:05:48.867Z] (0x0000015BD8DA36AE)
[2022-11-05T19:05:48.867Z] (0x0000000000286D10)
[2022-11-05T19:05:48.867Z] ---------------------------------------
[2022-11-05T19:05:48.867Z] (0x00007FF7BDE0692D)
[2022-11-05T19:05:48.867Z] (0x0000000000000001)
[2022-11-05T19:05:48.867Z] (0x0000000000274810)
[2022-11-05T19:05:48.867Z] (0x0000015BD8DA739F)
[2022-11-05T19:05:48.867Z] (0x0000000000289CE8)
[2022-11-05T19:05:48.867Z] (0x000003E800000001)
[2022-11-05T19:05:48.867Z] Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x56d850 (0x00007FFC943D9240 [j9jit29+0x639240])
[2022-11-05T19:05:48.867Z] (0x00000000FFE6B258)
[2022-11-05T19:05:48.867Z] (0x00000000FFDA4D00)
[2022-11-05T19:05:48.867Z] (0x000000000025F5E8)
[2022-11-05T19:05:48.867Z] (0x0000015BD8DA36AE)
[2022-11-05T19:05:48.867Z] (0x00000000002E38B0)
[2022-11-05T19:05:48.867Z] ---------------------------------------
[2022-11-05T19:05:48.867Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2022/11/05 12:05:20 - please wait.

[2022-11-05T19:05:48.868Z] TEST RESULT: Failed. Unexpected exit from test [exit code: -1]
[2022-11-05T19:05:48.868Z] --------------------------------------------------
[2022-11-05T19:07:00.187Z] Test results: passed: 112; failed: 1
[2022-11-05T19:07:17.460Z] Report written to C:\Users\jenkins\workspace\Test_openjdk19_j9_extended.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
[2022-11-05T19:07:17.460Z] Results written to C:\Users\jenkins\workspace\Test_openjdk19_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16676742997621\serviceability_jvmti_j9_0\work
[2022-11-05T19:07:17.460Z] Error: Some tests failed or other problems occurred.
[2022-11-05T19:07:17.871Z] 
[2022-11-05T19:07:17.871Z] serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29355/)

**Comment by pshipton** [comment]
@0xdaryl fyi

**Comment by 0xdaryl** [comment]
Sorry, this slipped through the cracks.

@jdmpapin : please investigate this JDK 19 crash.

**Comment by jdmpapin** [comment]
The instruction pointer is 0x7ff7bde0692d, which does not point to the beginning of an instruction, but rather to the middle of the marked instruction within `BufferedWriter.min`:
```
0x7ff7bde06928      mov       rax, rsi
0x7ff7bde0692b      add       rsp, 0x18   <-----------
0x7ff7bde0692f      ret
```
I found no point where we could start decoding earlier instructions and end up falling through to this address, so we probably jumped directly here from somewhere. There are no bad jumps within the compiled method.

The Java stack for the current thread in the javacore looks reasonable:
```
Java callstack:
  at java/io/BufferedWriter.min(BufferedWriter.java(Compiled Code))
  at java/lang/VirtualThread.run(VirtualThread.java:292)
  at java/lang/VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:179)
  at java/lang/VirtualThread$VThreadContinuation$$Lambda$7/0x0000000000000000.run(Bytecode PC:8)
  at jdk/internal/vm/Continuation.execute(Continuation.java:171)
```
However, the stack pointer 0x2cb550 looks suspicious. I don't see any JIT return addresses. At rsp+0x28 we do have the address of `returnFromJIT0`, but as can be seen in the return sequence, we would expect the return address to be at offset +0x18, not +0x28. At rsp+0x18, there is instead a pointer to an object reference.

There are also a few relevant/suspicious values on the stack immediately beyond rsp:
```
rsp-0x10   0x2cb540: 0x00007ff7bde0692d     The bad instruction pointer
rsp-0x08   0x2cb548: 0x00000000002cb552     This is rsp+2
```
Perhaps the current values of rip and/or rsp could have come from here?

In terms of finding out how we reached this state, I've found effectively nothing to go on.

I also ran a new grinder of 200 on the same machine where the original failure occurred, and using the same JDK build. It failed every single repetition of serviceability_jvmti_j9_0. At least, it failed all the repetitions that actually ran, of which there were only 82 because there were enough crashes to fill the disk and bring the grinder to a halt. None of the crashes were due to an illegal instruction though.

Because virtual threads are involved, and this is (AFAICT) specifically a virtual thread test, and the implementation of virtual threads is (almost?) entirely outside of the JIT compiler, I don't particularly expect this to be a JIT bug. Even if it is though, it seems to me that it would be helpful at this point for somebody more familiar with virtual threads to take a look at it first

**Comment by 0xdaryl** [comment]
Unless another crash dump appears that will give us a different perspective on this problem or unless someone with deeper virtual threads experience can reason about what the problem might be given @jdmpapin's analysis above then this won't be fixed for Java 19.  @pshipton @fengxue-IS @tajila

**Comment by pshipton** [comment]
@JasonFengJ9 have you seen any other occurrences of this? Pls keep an eye out. If you haven't seen any I think we should go ahead and close it until it's seen again.

**Comment by JasonFengJ9** [comment]
> If you haven't seen any I think we should go ahead and close it until it's seen again.

Not seen in recent builds.
Closing
