### ISSUE TITLE
ValueTypes: java.lang.VerifyError in ValueTypeTests_1  testFlatLayoutsWithRecursiveLongs

### ISSUE THREAD

**Issue by a7ehuo** [eclipse-openj9/openj9#16292]
After removing `<class name="org.openj9.test.lworld.ValueTypeArrayTests"/>` from `testng.xml`, I'm able to run more Valhalla functional tests. The reason that it has to be removed in order to run more tests is tracked in https://github.com/eclipse-openj9/openj9/issues/16284

`testFlatLayoutsWithRecursiveLongs` in `ValueTypeTests_1` failed due to `"java.lang.VerifyError: JVMVRFY021 thrown object not throwable; class=QuadLong, method=withl(QDoubleLong;)QQuadLong;, pc=2"`

```
1:28:13  Eclipse OpenJ9 VM (build test-fix-field-offset-flattened-arrayelement-bb482f0ec7b, JRE 20 Linux amd64-64-Bit Compressed References 20221108_261 (JIT enabled, AOT enabled)
11:28:13  OpenJ9   - bb482f0ec7b
11:28:13  OMR      - 1c49c4a411f
11:28:13  JCL      - 44115f48aff based on jdk-20+19)
```

```
FAILED: testFlatLayoutsWithRecursiveLongs
java.lang.VerifyError: JVMVRFY021 thrown object not throwable; class=QuadLong, method=withl(QDoubleLong;)QQuadLong;, pc=2
Exception Details:
  Location:
    QuadLong.withl(QDoubleLong;)QQuadLong; @2: JBwithfield
  Reason:
    Type null (current frame, stack[1]) is not assignable to 'QuadLong'
  Current Frame:
    bci: @2
    flags: { }
    locals: { 'QuadLong', 'QDoubleLong;' }
    stack: { 'QuadLong', null }
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1525)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:387)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:375)
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:340)
	at org.openj9.test.lworld.ValueTypeTests.testFlatLayoutsWithRecursiveLongs(ValueTypeTests.java:1725)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by hangshao0** [comment]
This test needs to be re-written as verifier has been enabled in ValueTypeTests.

**Comment by hangshao0** [comment]
This can be closed as https://github.com/eclipse-openj9/openj9/pull/16299 is merged.
