### ISSUE TITLE
JDK11 aarch64_mac TestZone test failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16310]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_aarch64_mac/130/)(`macaarch64rt8`):
```
openjdk version "11.0.17" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Mac OS X aarch64-64-Bit 20221031_177 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_util_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_mac&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=macaarch64rt8.rtp.raleigh.ibm.com&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fhyc-rt-java-delivery-generic-local%2FIBM%2Fjava%2Fsemeru-open%2F11.0%2F11.0.17.0%2Faarch64_mac%2Fibm-semeru-open-jdk_aarch64_mac_11.0.17_8_openj9-0.35.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fhyc-rt-java-delivery-generic-local%2FIBM%2Fjava%2Fsemeru-open%2F11.0%2F11.0.17.0%2Faarch64_mac%2Fibm-semeru-open-testimage_aarch64_mac_11.0.17_8_openj9-0.35.0.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=1&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=48&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-11-10T09:28:41.864Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-11-10T09:28:41.864Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-11-10T09:34:36.639Z] TEST: java/util/TimeZone/AssureTzdataVersion.java

[2022-11-10T09:34:36.639Z] STDERR:
[2022-11-10T09:34:36.639Z] java.lang.RuntimeException: tzdata versions don't match: run-time=2022c, tests=2022e
[2022-11-10T09:34:36.639Z] 	at AssureTzdataVersion.main(AssureTzdataVersion.java:49)
[2022-11-10T09:34:36.639Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-11-10T09:34:36.639Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-11-10T09:34:36.639Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-11-10T09:34:36.639Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-11-10T09:34:36.639Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-11-10T09:34:36.639Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2022-11-10T09:34:36.639Z] 
[2022-11-10T09:34:36.639Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

[2022-11-10T09:34:50.901Z] TEST: sun/util/calendar/zi/TestZoneInfo310.java

[2022-11-10T09:34:50.903Z] STDERR:
[2022-11-10T09:34:50.903Z] javazic: warning: found last rules for Morocco inconsistent.
[2022-11-10T09:34:50.903Z] javazic: warning: found last rules for Morocco inconsistent.
[2022-11-10T09:34:50.903Z] javazic: warning: found last rules for Eire inconsistent.
[2022-11-10T09:34:50.903Z] java.lang.RuntimeException:   FAILED:  aliases don't match
[2022-11-10T09:34:50.903Z] 	at TestZoneInfo310.main(TestZoneInfo310.java:167)
[2022-11-10T09:34:50.903Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-11-10T09:34:50.903Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-11-10T09:34:50.903Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-11-10T09:34:50.903Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-11-10T09:34:50.903Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-11-10T09:34:50.903Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2022-11-10T09:34:50.903Z] 
[2022-11-10T09:34:50.903Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-11-10T09:34:50.903Z] JavaTest Message: shutting down test
[2022-11-10T09:34:50.903Z] 
[2022-11-10T09:34:50.903Z] 
[2022-11-10T09:34:50.903Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: FAILED: aliases don't match
[2022-11-10T09:34:50.903Z] --------------------------------------------------
[2022-11-10T09:35:05.789Z] Test results: passed: 846; failed: 2
[2022-11-10T09:35:08.123Z] Report written to /Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac/aqa-tests/TKG/output_16680722314832/jdk_util_1/report/html/report.html
[2022-11-10T09:35:08.123Z] Results written to /Users/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_mac/aqa-tests/TKG/output_16680722314832/jdk_util_1/work
[2022-11-10T09:35:08.123Z] Error: Some tests failed or other problems occurred.
[2022-11-10T09:35:08.123Z] 
[2022-11-10T09:35:08.123Z] jdk_util_1_FAILED
```
[java/util/TimeZone/AssureTzdataVersion.java internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29480/)
[sun/util/calendar/zi/TestZoneInfo310.java internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29481/)

**Comment by pshipton** [comment]
I suspect this is a mismatch between using the 0.35 JVM to run the latest tests.
