### ISSUE TITLE
Serviceability: Add specific ClassLoader object to Proxy IllegalArgumentException message

### ISSUE THREAD

**Issue by jaridk** [eclipse-openj9/openj9#16320]
For the following exception:
```
Caused by: java.lang.IllegalArgumentException: package.ClassName referenced from a method is not visible from class loader
	at java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858) ~[?:?]
	at java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:681) ~[?:?]
	at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627) ~[?:?]
	at java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:426) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:424) ~[?:?]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006) ~[?:?]
```

It would be useful to know which specific ClassLoader object was the one from which the class was not visible. The type of class loader and object ID, at the very least, are a useful starting point for investigation, and the toString() output from some class loaders provides additional detail that might point directly at the relevant loader.

**Comment by pshipton** [comment]
This is OpenJDK code, you'll have to ask the openjdk.org project.
