### ISSUE TITLE
JCL_Test test_suspend IllegalThreadStateException: Has threads

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16348]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/412
JCL_Test_0
```
FAILED: test_suspend
java.lang.IllegalThreadStateException: Has threads
	at java.base/java.lang.ThreadGroup.destroyImpl(ThreadGroup.java:270) from jrt:/java.base
	at java.base/java.lang.ThreadGroup.destroy(ThreadGroup.java:252) from jrt:/java.base
	at java.base/java.lang.ThreadGroup.destroyImpl(ThreadGroup.java:277) from jrt:/java.base
	at java.base/java.lang.ThreadGroup.destroy(ThreadGroup.java:252) from jrt:/java.base
	at org.openj9.test.java.lang.Test_ThreadGroup.test_suspend(Test_ThreadGroup.java:752) from jdk.internal.loader.ClassLoaders$AppClassLoader@bc936c00(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly/529/tapResults/
```
variation: -XX:RecreateClassfileOnload
JVM_OPTIONS:  -XX:RecreateClassfileOnload 

FAILED: test_suspend
java.lang.IllegalThreadStateException: Has threads
	at java.base/java.lang.ThreadGroup.destroyImpl(ThreadGroup.java:273) from jrt:/java.base
	at java.base/java.lang.ThreadGroup.destroy(ThreadGroup.java:255) from jrt:/java.base
	at java.base/java.lang.ThreadGroup.destroyImpl(ThreadGroup.java:280) from jrt:/java.base
	at java.base/java.lang.ThreadGroup.destroy(ThreadGroup.java:255) from jrt:/java.base
	at org.openj9.test.java.lang.Test_ThreadGroup.test_suspend(Test_ThreadGroup.java:757) from jdk.internal.loader.ClassLoaders$AppClassLoader@3457ced6(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from jrt:/java.base

===============================================
    JCL_TEST_Java-Lang
    Tests run: 348, Failures: 1, Skips: 0
===============================================

===============================================
GeneralTest suite
Total tests run: 643, Failures: 1, Skips: 0
===============================================

-----------------------------------
JCL_Test_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR/482
JCL_Test_SE80_0
```
FAILED: test_suspend
java.lang.IllegalThreadStateException: Has threads
	at java.lang.ThreadGroup.destroyImpl(ThreadGroup.java:270) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR_testList_1/openjdkbinary/j2sdk-image/jre/lib/rt.jar
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:252) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR_testList_1/openjdkbinary/j2sdk-image/jre/lib/rt.jar
	at java.lang.ThreadGroup.destroyImpl(ThreadGroup.java:277) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR_testList_1/openjdkbinary/j2sdk-image/jre/lib/rt.jar
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:252) from /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR_testList_1/openjdkbinary/j2sdk-image/jre/lib/rt.jar
	at org.openj9.test.java.lang.Test_ThreadGroup.test_suspend(Test_ThreadGroup.java:757) from sun.misc.Launcher$AppClassLoader@2ebeac8d(file:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_1/538
JCL_Test_none_SCC_0
```
FAILED: test_resume
java.lang.IllegalThreadStateException: Has threads
	at java.base/java.lang.ThreadGroup.destroyImpl(ThreadGroup.java:273) from jrt:/java.base
	at java.base/java.lang.ThreadGroup.destroy(ThreadGroup.java:255) from jrt:/java.base
	at org.openj9.test.java.lang.Test_ThreadGroup.test_resume(Test_ThreadGroup.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@44eb6e98(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/608
JCL_Test_SE80_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/631
JCL_Test_2

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/747
JCL_Test_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR_testList_1/692
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/1059
