### ISSUE TITLE
OpenJDK java/lang/Runtime/exec/SleepyCat.java Read from closed pipe hangs

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16369]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/46
jdk_lang_0
java/lang/Runtime/exec/SleepyCat.java
```
05:49:39  STDOUT:
05:49:39  Child process has a hidden writable pipe fd for its stdin.
05:49:39  STDERR:
05:49:39  java.lang.Exception: Read from closed pipe hangs
05:49:39  	at SleepyCat.main(SleepyCat.java:158)
05:49:39  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:49:39  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:49:39  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:49:39  	at java.lang.reflect.Method.invoke(Method.java:498)
05:49:39  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
05:49:39  	at java.lang.Thread.run(Thread.java:826)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/74
jdk_lang_0
java/lang/Runtime/exec/SleepyCat.java
```
01:55:19  STDOUT:
01:55:19  Child process has a hidden writable pipe fd for its stdin.
01:55:19  STDERR:
01:55:19  java.lang.Exception: Read from closed pipe hangs
01:55:19  	at SleepyCat.main(SleepyCat.java:158)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/299
jdk_lang_1
java/lang/Runtime/exec/SleepyCat.java
```
11:20:59  STDOUT:
11:20:59  Child process has a hidden writable pipe fd for its stdin.
11:20:59  STDERR:
11:20:59  java.lang.Exception: Read from closed pipe hangs
11:20:59  	at SleepyCat.main(SleepyCat.java:158)
```
