### ISSUE TITLE
MathLoadTest_autosimd_special_5m_27_FAILED IllegalAccessError: invokeinterface of non-public method 'scalarCombine(DD)D' in net/adoptopenjdk/test/autosimd/AutoSIMDTestDouble$7

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16383]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_special.system_aarch64_linux_testList_2/272/)(`cent7-aarch64-3`):
```
java version "17.0.6-beta" 2023-01-17
IBM Semeru Runtime Certified Edition 17.0.6+4-202211290004 (build 17.0.6-beta+4-202211290004)
Eclipse OpenJ9 VM 17.0.6+4-202211290004 (build master-9f404bec6, JRE 17 Linux aarch64-64-Bit Compressed References 20221129_278 (JIT enabled, AOT enabled)
OpenJ9   - 9f404bec6
OMR      - acdbafc4a
JCL      - af194de7fa based on jdk-17.0.6+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=MathLoadTest_autosimd_special_5m_27&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_special.system_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F278%2Fibm-semeru-certified-debugimage_aarch64_linux_JDK17U_2022-11-29-00-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F278%2Fibm-semeru-certified-testimage_aarch64_linux_JDK17U_2022-11-29-00-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F278%2Fibm-semeru-certified-jdk_aarch64_linux_JDK17U_2022-11-29-00-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F278%2Fibm-semeru-certified-jre_aarch64_linux_JDK17U_2022-11-29-00-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=master&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=289&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-11-29T07:18:26.440Z] variation: Mode612-OSRG
[2022-11-29T07:18:26.440Z] JVM_OPTIONS:  -Xcompressedrefs -Xgcpolicy:gencon -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation 

[2022-11-29T07:19:14.256Z] MLT 02:19:13.658 - Starting thread. Suite=0 thread=6
[2022-11-29T07:19:22.598Z] MLT 02:19:21.504 - First failure detected by thread: load-4. Not creating dumps as no dump generation is requested for this load test
[2022-11-29T07:19:22.598Z] MLT 02:19:21.621 - Test failed
[2022-11-29T07:19:22.598Z] MLT   Failure num.  = 1
[2022-11-29T07:19:22.598Z] MLT   Test number   = 17
[2022-11-29T07:19:22.598Z] MLT   Test details  = 'ArbitraryJava[net.adoptopenjdk.test.autosimd.AutoSIMDTestDouble testLincombWithTemp]'
[2022-11-29T07:19:22.598Z] MLT   Suite number  = 0
[2022-11-29T07:19:22.598Z] MLT   Thread number = 4
[2022-11-29T07:19:22.598Z] MLT >>> Captured test output >>>
[2022-11-29T07:19:22.598Z] MLT Test failed:
[2022-11-29T07:19:22.598Z] MLT java.lang.IllegalAccessError: invokeinterface of non-public method 'scalarCombine(DD)D' in net/adoptopenjdk/test/autosimd/AutoSIMDTestDouble$7
[2022-11-29T07:19:22.598Z] MLT 	at net.adoptopenjdk.test.autosimd.AutoSIMDTestDouble.testSimpleBinary(AutoSIMDTestDouble.java:403)
[2022-11-29T07:19:22.598Z] MLT 	at net.adoptopenjdk.test.autosimd.AutoSIMDTestDouble.testLincombWithTemp(AutoSIMDTestDouble.java:297)
[2022-11-29T07:19:22.598Z] MLT 	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
[2022-11-29T07:19:22.598Z] MLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-11-29T07:19:22.598Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-11-29T07:19:22.598Z] MLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
[2022-11-29T07:19:22.598Z] MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2022-11-29T07:19:22.598Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2022-11-29T07:19:22.598Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2022-11-29T07:19:22.598Z] MLT 	at java.base/java.lang.Thread.run(Thread.java:857)
[2022-11-29T07:19:22.598Z] MLT <<<
[2022-11-29T07:19:22.598Z] MLT 
[2022-11-29T07:19:37.109Z] MLT 02:19:35.674 - Completed 7.0%. Number of tests started=217861 (with 1 failure(s))

[2022-11-29T07:24:09.495Z] MathLoadTest_autosimd_special_5m_27_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29861/) - passed

**Comment by JasonFengJ9** [comment]
[JDK17 aarch64_linux 0.40 rc1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_special.system_aarch64_linux_testList_1/399/)(`rhel9-aarch64-2`)
```
[2023-07-22T04:34:13.627Z] variation: Mode103
[2023-07-22T04:34:13.627Z] JVM_OPTIONS:  -Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs 

[2023-07-22T04:35:15.444Z] MLT 00:35:14.082 - First failure detected by thread: load-4. Not creating dumps as no dump generation is requested for this load test
[2023-07-22T04:35:17.509Z] MLT 00:35:16.664 - Test failed
[2023-07-22T04:35:17.509Z] MLT   Failure num.  = 1
[2023-07-22T04:35:17.509Z] MLT   Test number   = 17
[2023-07-22T04:35:17.509Z] MLT   Test details  = 'ArbitraryJava[net.adoptopenjdk.test.autosimd.AutoSIMDTestDouble testLincombWithTemp]'
[2023-07-22T04:35:17.509Z] MLT   Suite number  = 0
[2023-07-22T04:35:17.509Z] MLT   Thread number = 4
[2023-07-22T04:35:17.509Z] MLT >>> Captured test output >>>
[2023-07-22T04:35:17.509Z] MLT Test failed:
[2023-07-22T04:35:17.509Z] MLT java.lang.IllegalAccessError: invokeinterface of non-public method 'scalarCombine(DD)D' in net/adoptopenjdk/test/autosimd/AutoSIMDTestDouble$7
[2023-07-22T04:35:17.509Z] MLT 	at net.adoptopenjdk.test.autosimd.AutoSIMDTestDouble.testSimpleBinary(AutoSIMDTestDouble.java:405)
[2023-07-22T04:35:17.509Z] MLT 	at net.adoptopenjdk.test.autosimd.AutoSIMDTestDouble.testLincombWithTemp(AutoSIMDTestDouble.java:297)
[2023-07-22T04:35:17.509Z] MLT 	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
[2023-07-22T04:35:17.509Z] MLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-22T04:35:17.509Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-07-22T04:35:17.509Z] MLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
[2023-07-22T04:35:17.509Z] MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2023-07-22T04:35:17.509Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2023-07-22T04:35:17.509Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2023-07-22T04:35:17.509Z] MLT 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-07-22T04:35:17.509Z] MLT <<<
[2023-07-22T04:35:17.509Z] MLT 
[2023-07-22T04:35:18.402Z] MLT 00:35:17.693 - Completed 6.8%. Number of tests started=224173 (with 1 failure(s))

[2023-07-22T04:39:54.719Z] STF 00:39:54.390 - =====================   R E S U L T S   =====================
[2023-07-22T04:39:54.719Z] STF 00:39:54.390 - Stage results:
[2023-07-22T04:39:54.719Z] STF 00:39:54.390 -   setUp:     pass
[2023-07-22T04:39:54.719Z] STF 00:39:54.390 -   execute:  *fail*
[2023-07-22T04:39:54.719Z] STF 00:39:54.390 -   teardown:  pass
[2023-07-22T04:39:54.719Z] STF 00:39:54.390 - 
[2023-07-22T04:39:54.719Z] STF 00:39:54.390 - Overall result: **FAILED**
[2023-07-22T04:39:54.719Z] -----------------------------------
[2023-07-22T04:39:54.719Z] MathLoadTest_autosimd_special_5m_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34126/)

**Comment by knn-k** [comment]
The 50x Grinder job above finished successfully.

**Comment by JasonFengJ9** [comment]
Closing as dup of 
* https://github.com/eclipse-openj9/openj9/issues/18001
