### ISSUE TITLE
[FFI/Jtreg] Failure to get the symbol of strcat on AIX

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#16386]
TEST: java/foreign/StdLibTest.java in https://openj9-jenkins.osuosl.org/job/Grinder/1559/consoleText
```
[2022-11-29T23:31:09.376Z] Caused by: java.util.NoSuchElementException: No value present
[2022-11-29T23:31:09.376Z] 	at java.base/java.util.Optional.get(Optional.java:143)
[2022-11-29T23:31:09.376Z] 	at StdLibTest$StdLibHelper.<clinit>(StdLibTest.java:162) <----
```
against the test code at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/75e594014ff5c43054f2fb0fdac8a5e0c71abc11/test/jdk/java/foreign/StdLibTest.java#L162
```
        final static MethodHandle strcat = abi.downcallHandle(
                abi.defaultLookup().lookup("strcat").get(), <------------------------- fail to locate strcat in libc.a
                FunctionDescriptor.of(C_POINTER, C_POINTER, C_POINTER))
                .asType(MethodType.methodType(MemoryAddress.class, MemorySegment.class, MemorySegment.class)); // exact signature match
```
The rest of native funcations as follows in the test suite were successfully located without any issue, in which case the test passed by excluding `strcat`:
``` 
167: final static MethodHandle strcmp = abi.downcallHandle(abi.defaultLookup().lookup("strcmp").get(), 
170: final static MethodHandle puts = abi.downcallHandle(abi.defaultLookup().lookup("puts").get(), 
173: final static MethodHandle strlen = abi.downcallHandle(abi.defaultLookup().lookup("strlen").get(), 
176: final static MethodHandle gmtime = abi.downcallHandle(abi.defaultLookup().lookup("gmtime").get(), 
179: final static MethodHandle qsort = abi.downcallHandle(abi.defaultLookup().lookup("qsort").get(), 
186: final static MethodHandle rand = abi.downcallHandle(abi.defaultLookup().lookup("rand").get(), 
189: final static MethodHandle vprintf = abi.downcallHandle(abi.defaultLookup().lookup("vprintf").get(), 
192: final static Addressable printfAddr = abi.defaultLookup().lookup("printf").get(); 
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
We already resolved the loading issue for the default library (`libc.a`) on AIX in OpenJDK via https://github.com/eclipse-openj9/openj9/issues/13679, in which case the code should work for all native functions in the default library. So it doesn't make sense to me to that it only failed on `strcat` while passed on others.

 @pshipton,  is there any special setting of loading native library specific to `strcat` on AIX or any difference between `strcat` and other native functions in such case from OpenJ9 perspective?

**Comment by pshipton** [comment]
Did you look at the libc library to see if the symbol exists? I tried a small test and it seems the compiler inlines strcat into the program.

**Comment by ChengJin01** [comment]
> Did you look at the libc library?

Here's everything I got via `nm` from `libc.a`
```
/usr/lib/libc.a[shr.o]: strcat.s             f           -
/usr/lib/libc.a[shr.o]: wstrcat              D      516568          12
/usr/lib/libc.a[strcat.o]: .strcat              T           0         312
/usr/lib/libc.a[strcat.o]: TOC                  d         320
/usr/lib/libc.a[strcat.o]: strcat               D         312           8
/usr/lib/libc.a[strcat.o]: strcat.s             f           -
/usr/lib/libc.a[shr.o]: .NCstrcat            T     3476352
/usr/lib/libc.a[shr.o]: .NLstrcat            T     3484544
/usr/lib/libc.a[shr.o]: .strcat              T      522112         312
/usr/lib/libc.a[shr.o]: .wstrcat             T     3526912
/usr/lib/libc.a[shr.o]: /gsaro/ausgsa/projects/a/aix.41/aix71c/7100-05-04_SPGold/src/bos/usr/ccs/lib/libc/NCstrcat.c f           -
/usr/lib/libc.a[shr.o]: /gsaro/ausgsa/projects/a/aix.41/aix71c/7100-05-04_SPGold/src/bos/usr/ccs/lib/libc/NLstrcat.c f           -
/usr/lib/libc.a[shr.o]: /gsaro/ausgsa/projects/a/aix.41/aix71c/7100-05-04_SPGold/src/bos/usr/ccs/lib/libc/wstrcat.c f           -
/usr/lib/libc.a[shr.o]: NCstrcat             D      515164          12
/usr/lib/libc.a[shr.o]: NLstrcat             D      515524          12
/usr/lib/libc.a[shr.o]: strcat.s             f           -
/usr/lib/libc.a[shr.o]: wstrcat              D      516568          12
```

**Comment by ChengJin01** [comment]
It is interesting that the same testworks fine in locating `strcat` on JDK17 at https://openj9-jenkins.osuosl.org/job/Grinder/1554/.

https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/f302c65a5430cacb96400a147256c84071b4b5a5/test/jdk/java/foreign/StdLibTest.java#L160
```
        final static MethodHandle strcat = abi.downcallHandle(LOOKUP.lookup("strcat").get(), <-----
                MethodType.methodType(MemoryAddress.class, MemoryAddress.class, MemoryAddress.class),
                FunctionDescriptor.of(C_POINTER, C_POINTER, C_POINTER));
```
The code in OpenJDK we resolved for the default library loading is pretty much the same for JDK17 (with minor modifications adapted to JD17 APIs with the same underlying native & java code) and JDK19. So it looks weird that it only failed on `strcat` in JDK19.

**Comment by pshipton** [comment]
I can't explain it, we use the same compiler for both versions. The only thing I noticed is that the binary for a test using both strcat and strcmp only has a undefined symbol for strcmp, because strcat is already included. I don't see why this would affect jdk17 and jdk19 differently.

**Comment by ChengJin01** [comment]
There was no changes specific to the native library loading in OpenJDK17 & 18 until OpenJDK19 as I notice a bunch of changes for loading the native library in OpenJDK19, which explains why the test passed on OpenJDK17 & 18 but failed on OpenJDK19.

Given there is no special handling in OpenJ9 at this point, I will need to go through these related code in OpenJDK19 to see whether the problem was triggered by part of these changes.

**Comment by ChengJin01** [comment]
1) Looking at the exported symbols in `libnio.so` on JDK19 as compared to JDK17 given `strcmp` are located in `libnio.so`
JDK19:
```
jdk19/lib/libnio.so:
dump -Tv -X64   libnio.so
                        ***Loader Section***
                        ***Loader Symbol Table Information***
[Index]      Value      Scn     IMEX Sclass   Type           IMPid Name

[0]     0x1100008a8    .data              RW SECdef        [noIMid] __rtinit
[1]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowIOExceptionWithLastError
[2]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowByName
[3]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_GetStringPlatformChars
[4]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ReleaseStringPlatformChars
[5]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowOutOfMemoryError
[6]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowInternalError
[7]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowByNameWithLastError
[8]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_NewObjectByName
[9]     0x00000000    undef      IMP     DS EXTref      libjava.so getErrorString
 <-------------------------------------------------------------------------------- the entry for strcmp is missing
[10]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) access
[11]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) chmod
[12]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) chown
[13]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) close
[14]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) fchmod

```
JDK17:
```
jdk17/lib/libnio.so:
                        ***Loader Section***
                        ***Loader Symbol Table Information***
[Index]      Value      Scn     IMEX Sclass   Type           IMPid Name

[0]     0x110000848    .data              RW SECdef        [noIMid] __rtinit
[1]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowIOExceptionWithLastError
[2]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowByName
[3]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_GetStringPlatformChars
[4]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ReleaseStringPlatformChars
[5]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowOutOfMemoryError
[6]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowInternalError
[7]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_ThrowByNameWithLastError
[8]     0x00000000    undef      IMP     DS EXTref      libjava.so JNU_NewObjectByName
[9]     0x00000000    undef      IMP     DS EXTref      libjava.so getErrorString
[10]    0x00000000    undef      IMP     DS EXTref      libjava.so strcmp <--------------- located in libjava.so
[11]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) access
[12]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) chmod
[13]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) chown
[14]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) close
[15]    0x00000000    undef      IMP     DS EXTref libc.a(shr_64.o) fchmod
```
which indicates `strcmp` is loaded from `libjava.so`

2) Looking at the exported symbols in `libjava.so` on JDK19 as compared to JDK17:
JDK19:
```
libjava.so:
                        ***Loader Section***
                        ***Loader Symbol Table Information***
[Index]      Value      Scn     IMEX Sclass   Type           IMPid Name

[0]     0x110001658    .data              RW SECdef        [noIMid] __rtinit
...
[101]   0x0000de00    undef      IMP     XO EXTref libc.a(shr_64.o) ___strcmp64 <--------
[102]   0x0000f400    undef      IMP     XO EXTref libc.a(shr_64.o) ___memmove64
...
[345]   0x1100026f0    .data      EXP     DS SECdef        [noIMid] Java_java_util_TimeZone_getSystemGMTOffsetID
[346]   0x110002708    .data      EXP     DS SECdef        [noIMid] jio_fprintf
[347]   0x110002720    .data      EXP     DS SECdef        [noIMid] Java_java_io_UnixFileSystem_initIDs
...
[389]   0x110002b10    .data      EXP     DS SECdef        [noIMid] JNU_SetFieldByName
[390]   0x110002b28    .data      EXP     DS SECdef        [noIMid] JNU_GetStaticFieldByName
```
JDK17:
```
libjava.so:

                        ***Loader Section***

                        ***Loader Symbol Table Information***
[Index]      Value      Scn     IMEX Sclass   Type           IMPid Name

[0]     0x110001198    .data              RW SECdef        [noIMid] __rtinit
...
[400]   0x110002758    .data      EXP     DS SECdef        [noIMid] Java_java_io_UnixFileSystem_getNameMax0
[401]   0x110002770    .data      EXP     DS SECdef        [noIMid] strcmp <----------
[402]   0x110002780    .data      EXP     DS SECdef        [noIMid] JNU_CopyObjectArray
...
[93]    0x0000de00    undef      IMP     XO EXTref libc.a(shr_64.o) ___strcmp64 <-----------
[94]    0x0000f400    undef      IMP     XO EXTref libc.a(shr_64.o) ___memmove64
...
[382]   0x1100025b0    .data      EXP     DS SECdef        [noIMid] findJavaTZ_md
[383]   0x1100025c8    .data      EXP     DS SECdef        [noIMid] strcat <---------------------------
[384]   0x1100025d8    .data      EXP     DS SECdef        [noIMid] jio_fprintf
[385]   0x1100025f0    .data      EXP     DS SECdef        [noIMid] Java_java_io_UnixFileSystem_initIDs
...
[443]   0x110002b58    .data      EXP     DS SECdef        [noIMid] JNU_GetFieldByName
[444]   0x110002b70    .data      EXP     DS SECdef        [noIMid] JNU_SetFieldByName
...
[459]   0x1100033e0     .bss      EXP     RW    BSS        [noIMid] parentPathv
[460]   0x1100033e8     .bss      EXP     RW    BSS        [noIMid] raf_fd
```
The comparison above indicates only the mangled name of `strcmp` is located in `libjava.so` of JDK19 while both `strcmp` and `strcat` are located in `libjava.so` of JDK17, which suggests the exported symbols of `libjava.so` was somehow reduced in JDK19.

3) Looking at the load map files of `libnio`:
JDK19:
```
./build/aix-ppc64-server-release/support/native/java.base/libnio/libnio.loadmap

(ld): setopt 64
(ld): halt 4
(ld): setopt noexpall <-------------- Does not export symbols unless you list them in an export file.....
(ld): setopt rtl
(ld): setopt rtllib
(ld): setopt symbolic:1
(ld): setfflag 4
```
in correspondence with the code at 
https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/master/make/autoconf/flags-ldflags.m4#L80
```
  elif test "x$TOOLCHAIN_TYPE" = xxlc; then
    BASIC_LDFLAGS="-b64 -brtl -bnorwexec -bnolibpath -bnoexpall <--------
        -bernotok -btextpsize:64K \
        -bdatapsize:64K -bstackpsize:64K"
```
JD17:
```
./build/aix-ppc64-server-release/support/native/java.base/libnio/libnio.loadmap

(ld): setopt 64
(ld): halt 4
(ld): setopt expall <-------------- Exports all global symbols, except imported symbols.....
(ld): setopt rtl
(ld): setopt rtllib
(ld): setopt symbolic:1
(ld): setfflag 4
(ld): savename /home/jenkins/jchau_ffi/openj9-openjdk-jdk17/build/aix-ppc64-server-release/support/modules_libs/java.base/libnio.so
(ld): filelist 30 1
(ld): setopt noprogram
(ld): noentry
```
in correspondence with the code at https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/master/make/autoconf/flags-ldflags.m4#L86
```
  elif test "x$TOOLCHAIN_TYPE" = xxlc; then
    BASIC_LDFLAGS="-b64 -brtl -bnorwexec -bnolibpath -bexpall <----------
        -bernotok -btextpsize:64K \
        -bdatapsize:64K -bstackpsize:64K"
```
which indicates the compiler option ` -bexpall` on AIX was replaced with `-bnoexpall` since JDK19. So we need to restore the original option given the code with the default library loading is directly forth-ported from JDK17.

With the fix at https://github.com/ChengJin01/openj9-openjdk-jdk19/commit/9eb8225de372240756a8a8f35ac917b9f2e6c444,
The exported symbols of  `libnio.so` & `libjava.so` in JDK19 ended up with the same results as JDK17 (including both `strcmp` and `strcat`) and the failing tests passed as expected:
```
===============================================
test/jdk/java/foreign/StdLibTest.java
Total tests run: 75487, Passes: 75487, Failures: 0, Skips: 0
===============================================
```

**Comment by ChengJin01** [comment]
Close this issue as it was fixed at https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/75.
