### ISSUE TITLE
[FFI/Jtreg] Assert failure after finishing TestUpcall tests on Windows in JDK17

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#16408]
AIX at https://openj9-jenkins.osuosl.org/job/Grinder/1583/consoleText
```
[2022-12-01T21:07:02.861Z] test TestDowncall.testDowncallNoScope(12087, "f20_S_SSS_PFD", NON_VOID, [STRUCT, STRUCT, STRUCT], [POINTER, FLOAT, DOUBLE]): success
[2022-12-01T21:07:02.861Z] 
[2022-12-01T21:07:02.861Z] ===============================================
[2022-12-01T21:07:02.861Z] java/foreign/TestDowncall.java
[2022-12-01T21:07:02.861Z] Total tests run: 1424, Passes: 1424, Failures: 0, Skips: 0
[2022-12-01T21:07:02.861Z] ===============================================
[2022-12-01T21:07:02.861Z] 
[2022-12-01T21:07:02.861Z] STDERR:
[2022-12-01T21:07:02.861Z] WARNING: Using incubator modules: jdk.incubator.foreign
[2022-12-01T21:07:02.861Z] 21:03:28.840 0x30128800 omrport.359    * 
** ASSERTION FAILED ** at /home/jenkins/workspace
/Build_JDK17_ppc64_aix_Nightly/omr/port/common/omrmemtag.c:145: ((memoryCorruptionDetected))

[2022-12-01T21:07:02.861Z] JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/12/01 21:03:28 - please wait.
[2022-12-01T21:07:02.861Z] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16699284688440/jdk_foreign_0/work/scratch/core.20221201.210328.22610362.0001.dmp' in response to an event
[2022-12-01T21:07:02.861Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16699284688440/jdk_foreign_0/work/scratch/core.20221201.210328.22610362.0001.dmp
[2022-12-01T21:07:02.861Z] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16699284688440/jdk_foreign_0/work/scratch/javacore.20221201.210328.22610362.0002.txt' in response to an event
[2022-12-01T21:07:02.861Z] JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16699284688440/jdk_foreign_0/work/scratch/javacore.20221201.210328.22610362.0002.txt
[2022-12-01T21:07:02.861Z] JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16699284688440/jdk_foreign_0/work/scratch/Snap.20221201.210328.22610362.0003.trc' in response to an event
[2022-12-01T21:07:02.861Z] JVMDUMP010I Snap dump written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16699284688440/jdk_foreign_0/work/scratch/Snap.20221201.210328.22610362.0003.trc
[2022-12-01T21:07:02.861Z] JVMDUMP013I Processed dump event "traceassert", detail "".
```
with the dumps at https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Grinder/1583/openjdk_test_output.tar.gz

FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
The problem was also spotted on Windows in upcall at https://openj9-jenkins.osuosl.org/job/Grinder/1582/consoleText
```
[2022-12-01T21:44:21.834Z] test TestUpcall.testUpcallsNoScope(10149, "f16_S_SIF_PII", NON_VOID, [STRUCT, INT, FLOAT], [POINTER, INT, INT]): success
[2022-12-01T21:44:21.834Z] Timeout refired 960 times
[2022-12-01T21:44:21.834Z] STDERR:
[2022-12-01T21:44:21.834Z] WARNING: Using incubator modules: jdk.incubator.foreign
[2022-12-01T21:44:21.834Z] 21:16:02.132 0x129800 omrport.359    * 
** ASSERTION FAILED ** at f:\users\jenkins\workspace\build_jdk17_x86-64_windows_nightly\omr\port\common\omrmemtag.c:145: ((memoryCorruptionDetected))
[2022-12-01T21:44:21.834Z] JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/12/01 16:16:02 - please wait.
[2022-12-01T21:44:21.834Z] JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Grinder\aqa-tests\TKG\output_1669928605988\jdk_foreign_0\work\scratch\1\core.20221201.161602.3836.0001.dmp' in response to an event
[2022-12-01T21:44:21.834Z] JVMDUMP010I System dump written to C:\Users\jenkins\workspace\Grinder\aqa-tests\TKG\output_1669928605988\jdk_foreign_0\work\scratch\1\core.20221201.161602.3836.0001.dmp
[2022-12-01T21:44:21.835Z] JVMDUMP032I JVM requested Java dump using 'C:\Users\jenkins\workspace\Grinder\aqa-tests\TKG\output_1669928605988\jdk_foreign_0\work\scratch\1\javacore.20221201.161602.3836.0002.txt' in response to an event
```
in which there was no failing tests before the assertion failure occurred.

**Comment by ChengJin01** [comment]
The dumps indicate it failed in `Unsafe.freeMemory0`
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "Common-Cleaner" J9VMThread:0x0000000030121300, omrthread_t:0x0000010021FF93
E0, java/lang/Thread:0x00000000E0059A30, state:R, prio=8
3XMJAVALTHREAD            (java/lang/Thread getId:0x2, isDaemon:true)
3XMJAVALTHRCCL            No Java context classloader associated with this thread
3XMTHREADINFO1            (native thread ID:0x15C0007, native priority:0x8, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x0000010022010000, to:0x000001002209A888, size:0x8A888)
3XMCPUTIME               CPU usage total: 2.890657000 secs, user: 0.029137000 secs, system: 2.861520000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/misc/Unsafe.freeMemory0(Native Method) <--------
4XESTACKTRACE                at jdk/internal/misc/Unsafe.freeMemory(Unsafe.java:1438)
4XESTACKTRACE                at jdk/internal/foreign/NativeMemorySegmentImpl$1.cleanup(NativeMemorySegmentImpl.java:115)
4XESTACKTRACE                at jdk/internal/foreign/ResourceScopeImpl$ResourceList.cleanup(ResourceScopeImpl.java:294(Compiled Code))
4XESTACKTRACE                at jdk/internal/foreign/SharedScope$SharedResourceList.cleanup(SharedScope.java:164(Compiled Code))
4XESTACKTRACE                at jdk/internal/foreign/ResourceScopeImpl$ResourceList.run(ResourceScopeImpl.java:288)
4XESTACKTRACE                at jdk/internal/ref/CleanerImpl$PhantomCleanableRef.performCleanup(CleanerImpl.java:178)
4XESTACKTRACE                at jdk/internal/ref/PhantomCleanable.clean(PhantomCleanable.java:133)
4XESTACKTRACE                at jdk/internal/ref/CleanerImpl.run(CleanerImpl.java:142)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:857)
4XESTACKTRACE                at jdk/internal/misc/InnocuousThread.run(InnocuousThread.java:162)
3XMTHREADINFO3           Native callstack:

(dbx)where
... 
IPRA.$unwrapBlockAndCheckTags(??, ??), line 145 in "omrmemtag.c"
omrmem_free_memory(??, ??), line 208 in "omrmemtag.c" <---------
unsafeFreeMemory(??, ??), line 130 in "unsafe_mem.c"
Java_sun_misc_Unsafe_freeMemory(??, ??, ??), line 277 in "sun_misc_Unsafe.cpp"
.() at 0x10010b58f6c
runJavaThread(??), line 682 in "callin.cpp"
```
which we have not yet resolved in https://github.com/eclipse-openj9/openj9/issues/14205.

FYI: @babsingh

**Comment by ChengJin01** [comment]
The failing test passed with PR at https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/160 on AIX (previously 100% reproducible locally) but this fix has nothing to do with the problem on Windows as the alignment setting for `long/pointer` on Windows is kept unchanged in OpenJDK.

**Comment by ChengJin01** [comment]
I just checked the dumps on Windows at https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Grinder/1582/openjdk_test_output.tar.gz by DDR that indicates the problem might be related to JIT:
```
> !threads
        !stack 0x8bb901da00     !j9vmthread 0x8bb901da00        !j9thread 0x8bb82e13f0  tid 0x10f0 (4336) // (main)
...
   -----> !stack 0x8bd6abbb00     !j9vmthread 0x8bd6abbb00        !j9thread 0x8bd69f1498  tid 0x1358 (4952) // (MainThread)

> !stack 0x8bd6abbb00
<8bd6abbb00>    !j9method 0x0000008BC25D9330   java/lang/invoke/MethodType.basicType()Ljava/lang/invoke/MethodType;
Dec 08, 2022 6:55:20 PM com.ibm.j9ddr.vm29.events.DefaultEventListener corruptData
WARNING: CorruptDataException thrown walking stack. walkThread = 0x0000008BD6ABBB00
com.ibm.j9ddr.AddressedCorruptDataException: Invalid JIT return address <--------------
        at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker$JITStackWalker_29_V0.jitWalkStackFrames(JITStackWalker.java:287)
        at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker.jitWalkStackFrames(JITStackWalker.java:101)
        at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:486)
        at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker.walkStackFrames(StackWalker.java:103)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.StackWalkCommand.run(StackWalkCommand.java:139)

```
which is most likely the same issue that we detected on https://github.com/eclipse-openj9/openj9/issues/16387 for `Invalid JIT return address` in upcall tests.

**Comment by ChengJin01** [comment]
Close this issue as duplicate as https://github.com/eclipse-openj9/openj9/issues/16387 for now unless anything else wrong is spotted specific to Windows in the near future.  Otherwise, I don't spot anything wrong by manually run the failing test suite many times on Windows.

**Comment by ChengJin01** [comment]
The Grinders with the latest nightly build indicate the problem with `omrmemtag.c` still exists in JDK17 on Windows (the same place/platform as before) at https://openj9-jenkins.osuosl.org/job/Grinder/1661/:

```
[2022-12-09T20:34:54.355Z] ===============================================
[2022-12-09T20:34:54.355Z] java/foreign/TestUpcall.java
[2022-12-09T20:34:54.355Z] Total tests run: 1424, Passes: 1424, Failures: 0, Skips: 0
[2022-12-09T20:34:54.355Z] ===============================================
[2022-12-09T20:34:54.355Z] 
[2022-12-09T20:34:54.355Z] STDERR:
[2022-12-09T20:34:54.355Z] WARNING: Using incubator modules: jdk.incubator.foreign
[2022-12-09T20:34:54.355Z] 20:34:36.128 0x13c500 omrport.359    *   ** ASSERTION FAILED ** at f:\users\jenkins\workspace\build_jdk17_x86-64_windows_nightly\omr\port\common\omrmemtag.c:145: ((memoryCorruptionDetected))
[2022-12-09T20:34:54.355Z] JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/12/09 14:34:36 - please wait.
```
against the stacktrace in DDR:
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/misc/Unsafe.freeMemory0(Native Method)
4XESTACKTRACE                at jdk/internal/misc/Unsafe.freeMemory(Unsafe.java:1438(Compiled Code))
4XESTACKTRACE                at jdk/internal/foreign/NativeMemorySegmentImpl$1.cleanup(NativeMemorySegmentImpl.java:115(Compiled Code))
4XESTACKTRACE                at jdk/internal/foreign/ResourceScopeImpl$ResourceList.cleanup(ResourceScopeImpl.java:294(Compiled Code))
4XESTACKTRACE                at jdk/internal/foreign/SharedScope$SharedResourceList.cleanup(SharedScope.java:164(Compiled Code))
4XESTACKTRACE                at jdk/internal/foreign/ResourceScopeImpl$ResourceList.run(ResourceScopeImpl.java:288(Compiled Code))
4XESTACKTRACE                at jdk/internal/ref/CleanerImpl$PhantomCleanableRef.performCleanup(CleanerImpl.java:178(Compiled Code))
4XESTACKTRACE                at jdk/internal/ref/PhantomCleanable.clean(PhantomCleanable.java:133(Compiled Code))
4XESTACKTRACE                at jdk/internal/ref/CleanerImpl.run(CleanerImpl.java:142)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:857)
4XESTACKTRACE                at jdk/internal/misc/InnocuousThread.run(InnocuousThread.java:162)
```
which means the problem only occurs when releasing the native memory of arguments allocated in the test suite after finishing all  tests.

**Comment by ChengJin01** [comment]
The problem only occurs in Grinders and is never reproduced locally, which means it is less likely related to any functional related code but something specific to Windows.

**Comment by ChengJin01** [comment]
It turns out the problem was caused by the incorrect test changes at https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/20a6dd8cdd7f643360d3963a7e0b815f41f38a64/test/jdk/java/foreign/CallGeneratorHelper.java#L153
```
        MemoryLayout layout(List<StructFieldType> fields) {
            if (this == STRUCT) {
                long offset = 0L;
                List<MemoryLayout> layouts = new ArrayList<>();
                for (StructFieldType field : fields) {
                    MemoryLayout l = field.layout();
                    /* Follow the calculation of padding in JDK19 which is based on
                     * the alignment of layout rather than the bit size.
                     */
                    long padding = offset % l.bitAlignment(); <-----
                    if (padding != 0) {
                    ....
```
in which case the test code was partially copied from JDK19 at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/84975bef19dceb77173965f3778dea1d98dbe731/test/jdk/java/foreign/CallGeneratorHelper.java#L156 to support the padding of struct arguments.  So the correct way is to backport the whole code in `layout()` to JDK17 given it proves to work for all supported platforms.
