### ISSUE TITLE
[FFI/Jtreg] The type check in VaListTtest failed on AIX and Windows in JDK17

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#16407]
AIX at https://openj9-jenkins.osuosl.org/job/Grinder/1583/consoleText
```
[2022-12-01T21:11:46.175Z] test VaListTest.testBigStruct(VaListTest$$Lambda$75/0x0000000023285198@ada0d83e, com.sun.proxy.jdk.proxy2.$Proxy4@6d10fe5c, jdk.incubator.foreign.GroupLayout@2d3339dc, java.lang.invoke.IndirectVarHandle@3db8627e, java.lang.invoke.IndirectVarHandle@a7317d82): success
[2022-12-01T21:11:46.175Z] test VaListTest.testCopy(VaListTest$$Lambda$68/0x0000000023284700@9ccdde45, b32[abi/kind=INT]): success
[2022-12-01T21:11:46.175Z] test VaListTest.testCopy(VaListTest$$Lambda$69/0x00000000232848c8@47e03657, b32[abi/kind=INT]): success
[2022-12-01T21:11:46.175Z] test VaListTest.testCopy(VaListTest$$Lambda$70/0x0000000023284a40@8fef7e4f, b32[abi/kind=INT]): success
[2022-12-01T21:11:46.175Z] test VaListTest.testCopy(VaListTest$$Lambda$71/0x0000000023284bb8@249efd7f, b32[abi/kind=INT]): success
[2022-12-01T21:11:46.175Z] test VaListTest.testCopy(VaListTest$$Lambda$72/0x0000000023284d30@f3367af2, B32[abi/kind=INT]): success
[2022-12-01T21:11:46.175Z] test VaListTest.testCopy(VaListTest$$Lambda$73/0x0000000023284ea8@c36b6acc, b32[abi/kind=INT]): success
[2022-12-01T21:11:46.175Z] test VaListTest.testCopy(VaListTest$$Lambda$74/0x0000000023285020@7558d37a, B32[abi/kind=INT]): failure
[2022-12-01T21:11:46.175Z] java.lang.IllegalArgumentException: Carrier size mismatch: long != B32[abi/kind=LONG] <------
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.internal.foreign.Utils.checkPrimitiveCarrierCompat(Utils.java:111)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:160)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.lambda$varHandle$2(MemoryLayout.java:491)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.computePathOp(MemoryLayout.java:581)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.varHandle(MemoryLayout.java:491)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.vhPrimitiveOrAddress(SharedUtils.java:511)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.s390x.sysv.TypeClass.classifyVarHandle(TypeClass.java:98)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.s390x.sysv.SysVS390xVaList$Builder.storeArgToMemoryArea(SysVS390xVaList.java:513)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.s390x.sysv.SysVS390xVaList$Builder.build(SysVS390xVaList.java:574)
[2022-12-01T21:11:46.175Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.s390x.sysv.SysVS390xLinker.newVaList(SysVS390xLinker.java:108)
[2022-12-01T21:11:46.175Z] 	at VaListTest.lambda$static$6(VaListTest.java:141)
[2022-12-01T21:11:46.175Z] 	at VaListTest.testCopy(VaListTest.java:682)
```
Windows at at https://openj9-jenkins.osuosl.org/job/Grinder/1583/consoleText
```
[2022-12-01T21:23:57.071Z] test VaListTest.testBigStruct(VaListTest$$Lambda$89/0x0000000071a8d1b8@aa3c0d37, com.sun.proxy.jdk.proxy2.$Proxy4@7c1d1b12, jdk.incubator.foreign.GroupLayout@e12878c1, java.lang.invoke.IndirectVarHandle@b26237c9, java.lang.invoke.IndirectVarHandle@577d21c1): success
[2022-12-01T21:23:57.071Z] test VaListTest.testCopy(VaListTest$$Lambda$82/0x0000000071a8c748@8d9ba9ef, b32[abi/kind=INT]): success
[2022-12-01T21:23:57.071Z] test VaListTest.testCopy(VaListTest$$Lambda$83/0x0000000071a8c8f8@75e8e723, b32[abi/kind=INT]): success
[2022-12-01T21:23:57.071Z] test VaListTest.testCopy(VaListTest$$Lambda$84/0x0000000071a8ca60@900ef13a, b32[abi/kind=INT]): success
[2022-12-01T21:23:57.071Z] test VaListTest.testCopy(VaListTest$$Lambda$85/0x0000000071a8cbd8@4eb8649b, b32[abi/kind=INT]): success
[2022-12-01T21:23:57.071Z] test VaListTest.testCopy(VaListTest$$Lambda$86/0x0000000071a8cd50@7c43cd33, B32[abi/kind=INT]): failure
[2022-12-01T21:23:57.072Z] java.lang.IllegalArgumentException: Carrier size mismatch: long != b32[abi/kind=LONG]
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.Utils.checkPrimitiveCarrierCompat(Utils.java:111)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:160)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.lambda$varHandle$2(MemoryLayout.java:491)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.computePathOp(MemoryLayout.java:581)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.varHandle(MemoryLayout.java:491)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.vhPrimitiveOrAddress(SharedUtils.java:511)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.ppc64.TypeClass.classifyVarHandle(TypeClass.java:72)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.ppc64.aix.AixPPC64VaList$Builder.build(AixPPC64VaList.java:274)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.ppc64.aix.AixPPC64Linker.newVaList(AixPPC64Linker.java:111)
[2022-12-01T21:23:57.072Z] 	at VaListTest.lambda$static$4(VaListTest.java:137)
[2022-12-01T21:23:57.072Z] 	at VaListTest.testCopy(VaListTest.java:682)

[2022-12-01T21:23:57.072Z] test VaListTest.testCopy(VaListTest$$Lambda$87/0x0000000071a8cec8@54cb43e5, b32[abi/kind=INT]): failure
[2022-12-01T21:23:57.072Z] java.lang.IllegalArgumentException: Carrier size mismatch: long != b32[abi/kind=LONG]
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.Utils.checkPrimitiveCarrierCompat(Utils.java:111)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:160)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.lambda$varHandle$2(MemoryLayout.java:491)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.computePathOp(MemoryLayout.java:581)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.varHandle(MemoryLayout.java:491)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.SharedUtils.vhPrimitiveOrAddress(SharedUtils.java:511)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.ppc64.TypeClass.classifyVarHandle(TypeClass.java:72)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.ppc64.sysv.SysVPPC64leVaList$Builder.build(SysVPPC64leVaList.java:274)
[2022-12-01T21:23:57.072Z] 	at jdk.incubator.foreign/jdk.internal.foreign.abi.ppc64.sysv.SysVPPC64leLinker.newVaList(SysVPPC64leLinker.java:108)
[2022-12-01T21:23:57.072Z] 	at VaListTest.lambda$static$5(VaListTest.java:139)
[2022-12-01T21:23:57.072Z] 	at VaListTest.testCopy(VaListTest.java:682)
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
The problematic code is at 
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/ffa38f7d63ee8aa23f68872a0c1a87ec4630dff2/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ppc64/TypeClass.java#L58
and https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/ffa38f7d63ee8aa23f68872a0c1a87ec4630dff2/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/s390x/sysv/TypeClass.java#L98,
in which `C_LONG` (32bit) was wrongly chosen on AIX on Windows given the test suite go through all VaList specific code for type check. To ensure it works correctly, `C_LONG` (32bit on AIX & Windows and 64bit on other platforms) must be replaced with `C_LONG_LONG`(64bit) for the `long` type to pass the type check in code.

I will create a PR in https://github.com/ibmruntimes/openj9-openjdk-jdk17 to resolve this issue.

**Comment by ChengJin01** [comment]
Close this issue as the PR at https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/159 was merged.
