### ISSUE TITLE
[FFI/Jtreg] Assert failure in upcall on AIX in JDK17

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#16409]
There were a bunch of test failures in upcall on AIX at https://openj9-jenkins.osuosl.org/job/Grinder/1583/consoleText. e.g.
```
[2022-12-01T21:08:54.284Z] test TestUpcall.testUpcalls(1479, "f2_V_ISP_DD", VOID, [INT, STRUCT, POINTER], [DOUBLE, DOUBLE]): success
[2022-12-01T21:08:54.284Z] test TestUpcall.testUpcalls(1496, "f2_V_ISP_IDP", VOID, [INT, STRUCT, POINTER], [INT, DOUBLE, POINTER]): success
[2022-12-01T21:08:54.284Z] test TestUpcall.testUpcalls(1513, "f2_V_ISP_FPI", VOID, [INT, STRUCT, POINTER], [FLOAT, POINTER, INT]): failure
[2022-12-01T21:08:54.285Z] java.lang.AssertionError: expected [MemoryAddress{ base: null offset=0x100236446a0 }] but found [MemoryAddress{ base: null offset=0xb765432132cffe85 }]
[2022-12-01T21:08:54.285Z] 	at org.testng.Assert.fail(Assert.java:99)
[2022-12-01T21:08:54.285Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2022-12-01T21:08:54.285Z] 	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
[2022-12-01T21:08:54.285Z] 	at org.testng.Assert.assertEquals(Assert.java:122)
[2022-12-01T21:08:54.285Z] 	at org.testng.Assert.assertEquals(Assert.java:617)
[2022-12-01T21:08:54.285Z] 	at TestUpcall.lambda$makeCallback$6(TestUpcall.java:179)
[2022-12-01T21:08:54.285Z] 	at TestUpcall.lambda$testUpcalls$0(TestUpcall.java:108)
[2022-12-01T21:08:54.285Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-12-01T21:08:54.285Z] 	at TestUpcall.testUpcalls(TestUpcall.java:108)
```
FYI: @tajila, @pshipton, @zl-wang

**Comment by ChengJin01** [comment]
I didn't see any failure in downcall & upcall in JDK19 on AIX given these test suites are totally updated in JDK19. So I suspect there was some issue we never encounter in JDK19 assuming there is no issue with libffi/power (which was replaced with the latest version via https://github.com/eclipse-openj9/openj9/pull/14701).

**Comment by ChengJin01** [comment]
I realized this might be caused by the alignment issue with `long` & `pointer` which was already resolved in JDK19 via https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/44/files but has not yet backported to JDK17. Will be double-check this at first to see whether it works with the same fix. If so, will create a PR for this issue.

**Comment by ChengJin01** [comment]
The downcall & upcall tests (previously 100% reproducible locally) passed without any issue with the fix at https://github.com/ChengJin01/openj9-openjdk-jdk17/commit/630469a30d736de55940252601b09b40cf1d8903.
```
===============================================
test/jdk/java/foreign/TestUpcall.java
Total tests run: 1424, Passes: 1424, Failures: 0, Skips: 0
===============================================

===============================================
test/jdk/java/foreign/TestDowncall.java
Total tests run: 1424, Passes: 1424, Failures: 0, Skips: 0
===============================================
```

**Comment by keithc-ca** [comment]
Fixed via https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/160.
