### ISSUE TITLE
FIPS jdk_security3_0_FAILED NoSuchAlgorithmException: JKS KeyStore not available

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16412]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux_fips/20/)(`rhel8x64-fips2-1`):
```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b05)
Eclipse OpenJ9 VM (build v0.36.0-release-f98e55973, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20221201_534 (JIT enabled, AOT enabled)
OpenJ9   - f98e55973
OMR      - acdbafc4a
JCL      - 497b11fa23 based on jdk8u362-b05)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=FIPS&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F534%2Fibm-semeru-open-testimage_x64_linux_8u362b05_openj9-0.36.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F534%2Fibm-semeru-open-jre_x64_linux_8u362b05_openj9-0.36.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F534%2Fibm-semeru-open-debugimage_x64_linux_8u362b05_openj9-0.36.0-m1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F534%2Fibm-semeru-open-jdk_x64_linux_8u362b05_openj9-0.36.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=v0.36.0-release&amp;OPENJ9_BRANCH=v0.36.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.36.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-12-01T08:28:40.473Z] variation: Mode150
[2022-12-01T08:28:40.473Z] JVM_OPTIONS:  -XX:+UseCompressedOops  -Dsemeru.fips=true

[2022-12-01T08:29:33.102Z] TEST: sun/security/ssl/SSLSessionImpl/InvalidateSession.java

[2022-12-01T08:29:33.102Z] STDERR:
[2022-12-01T08:29:33.102Z] java.security.KeyStoreException: JKS not found
[2022-12-01T08:29:33.102Z] 	at java.security.KeyStore.getInstance(KeyStore.java:851)
[2022-12-01T08:29:33.102Z] 	at SSLContextTemplate.createKeyManager(SSLContextTemplate.java:496)
[2022-12-01T08:29:33.102Z] 	at SSLContextTemplate.createServerKeyManager(SSLContextTemplate.java:87)
[2022-12-01T08:29:33.102Z] 	at SSLContextTemplate.createServerSSLContext(SSLContextTemplate.java:58)
[2022-12-01T08:29:33.102Z] 	at InvalidateSession.sessionTest(InvalidateSession.java:71)
[2022-12-01T08:29:33.102Z] 	at InvalidateSession.main(InvalidateSession.java:54)
[2022-12-01T08:29:33.102Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-12-01T08:29:33.102Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-12-01T08:29:33.102Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-12-01T08:29:33.102Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-12-01T08:29:33.102Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-12-01T08:29:33.102Z] 	at java.lang.Thread.run(Thread.java:826)
[2022-12-01T08:29:33.102Z] Caused by: java.security.NoSuchAlgorithmException: JKS KeyStore not available
[2022-12-01T08:29:33.102Z] 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
[2022-12-01T08:29:33.102Z] 	at java.security.Security.getImpl(Security.java:714)
[2022-12-01T08:29:33.102Z] 	at java.security.KeyStore.getInstance(KeyStore.java:848)
[2022-12-01T08:29:33.102Z] 	... 11 more
[2022-12-01T08:29:33.102Z] 
[2022-12-01T08:29:33.102Z] JavaTest Message: Test threw exception: java.security.KeyStoreException: JKS not found

[2022-12-01T08:34:04.683Z] jdk_security3_0_FAILED
```

**Comment by pshipton** [comment]
I'm not sure why this is marked FIPS. @JasonFengJ9 is this repeatable?

**Comment by pshipton** [comment]
> I'm not sure why this is marked FIPS

I see, it's running FIPS testing on a FIPS machine.

**Comment by JasonFengJ9** [comment]
[10x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29984/)

**Comment by taoliult** [comment]
@JasonFengJ9 
From the issue description, it set "-Dsemeru.fips=true". So I think it run the tests in FIPS mode. And in FIPS mode, currently, FIPS mode doesn't support the JKS keystore. If we see "java.security.KeyStoreException: JKS not found" when running the tests in FIPS mode, that works as design.

**Comment by pshipton** [comment]
@taoliult do tests that fail in this way need to be excluded then?

**Comment by taoliult** [comment]
@pshipton 
Yes, the test is on OpenJDK8 for extended.openjdk, we will add this test case into the OpenJDK8 FIPS exclude list. 

@WilburZjh 
Please help to add this test case into the OpenJDK8 FIPS exclude list.

**Comment by WilburZjh** [comment]
Added, @pshipton please help to approve this [PR](https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/635)
