### ISSUE TITLE
DDR can't read java stacks from core file - Induced OSR resolve not handled yet

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16457]
Trying to read java stacks from the core files in https://github.com/eclipse-openj9/openj9/issues/13477#issuecomment-1346912376 results in the following:
```
com.ibm.j9ddr.CorruptDataException: Induced OSR resolve not handled yet
	at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker$JITStackWalker_29_V0.jitWalkResolveMethodFrame(JITStackWalker.java:471)
	at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker$JITStackWalker_29_V0.walkTransitionFrame(JITStackWalker.java:884)
	at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker$JITStackWalker_29_V0.jitWalkStackFrames(JITStackWalker.java:198)
	at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker.jitWalkStackFrames(JITStackWalker.java:101)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:486)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker.walkStackFrames(StackWalker.java:103)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.StackWalkCommand.run(StackWalkCommand.java:139)
```

@gacholio @tajila are we missing something from the stack walker?

**Comment by pshipton** [comment]
Actually, I guess this is a dup of https://github.com/eclipse-openj9/openj9/issues/16271 ?

**Comment by gacholio** [comment]
As the message says, we never got around to copying this case to DDR. I find it highly unlikely that this is actually an induce OSR frame - there's no GC point between the frame build and tear down, so it's extremely unlikely you could observe the stack in that brief window.

I suppose the stated problem is a hang, so if it's the OSR block that's hanging, you could see this. It's more likely this is just bad root information left over from a successful induced OSR in the past.

**Comment by gacholio** [comment]
> Actually, I guess this is a dup of #16271 ?

I don't think it is.
