### ISSUE TITLE
jdk_container_jdk8_0_FAILED jdk/internal/platform/docker/TestDockerCpuMetrics.java NPE at TestDockerCpuMetrics.main(TestDockerCpuMetrics.java:77)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16462]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_dev.openjdk_aarch64_linux/3/)(`ub18-aarch64-4`):
```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b05)
Eclipse OpenJ9 VM (build master-7cafd4be8, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20221210_513 (JIT enabled, AOT enabled)
OpenJ9   - 7cafd4be8
OMR      - 8ae31402f
JCL      - d9472a844 based on jdk8u362-b05)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_jdk8_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-debugimage_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-jre_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-testimage_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-12-10T07:31:17.409Z] variation: NoOptions
[2022-12-10T07:31:17.409Z] JVM_OPTIONS:  

[2022-12-10T07:44:47.105Z] TEST: jdk/internal/platform/docker/TestDockerCpuMetrics.java

[2022-12-10T07:44:47.107Z] STDERR:
[2022-12-10T07:44:47.107Z] java.lang.NullPointerException
[2022-12-10T07:44:47.107Z] 	at TestDockerCpuMetrics.main(TestDockerCpuMetrics.java:77)
[2022-12-10T07:44:47.107Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-12-10T07:44:47.107Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-12-10T07:44:47.107Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-12-10T07:44:47.107Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-12-10T07:44:47.107Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-12-10T07:44:47.107Z] 	at java.lang.Thread.run(Thread.java:826)
[2022-12-10T07:44:47.107Z] 
[2022-12-10T07:44:47.107Z] JavaTest Message: Test threw exception: java.lang.NullPointerException

jdk_container_jdk8_0_FAILED
```

[100x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30231/)

**Comment by pshipton** [comment]
The test seems bogus as it can only run inside a docker environment. The NPE is caused by jdk.internal.platform.Metrics.systemMetrics() returning null. This is expected unless the JVM is running under docker. The test checks if docker is available on the machine, by running `docker ps`, builds a docker image, runs some tests in the docker image, but then calls `Metrics.systemMetrics()` outside of docker and expect it to be non-null.

@llxia

**Comment by pshipton** [comment]
@JasonFengJ9 I expect this should be excluded everywhere it fails until it's working.

**Comment by JasonFengJ9** [comment]
```
 * @summary Test JDK Metrics class when running inside docker container [1]
```

A docker-enabled machine label is required, this test along with other docker test friends can be excluded if the framework support is going to take a while.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4d70df27c9b0ea8f58f200cf630ca1332d223fa4/jdk/test/jdk/internal/platform/docker/TestDockerCpuMetrics.java#L35

**Comment by llxia** [comment]
`jdk_container_jdk8` is a newly enabled test in `dev.openjdk` (see https://github.com/adoptium/aqa-tests/pull/4147). `dev.openjdk` test build is also nee and it sets to run in the docker environment. (i.e., LABEL_ADDITION=sw.tool.docker).

Since they are new, we do not yet have all the data on all versions/platforms. I do not see any valid Test_openjdk8_j9_dev.openjdk_aarch64_linux test builds at Adoptium. But the same test passed at Adoptium https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_dev.openjdk_s390x_linux/7/

**Comment by llxia** [comment]
I also noticed the pipeline issue on windows as there is no `sw.tool.docker` for windows. The pipeline issue is opened at https://github.com/adoptium/ci-jenkins-pipelines/issues/568

**Comment by JasonFengJ9** [comment]
[JDK17 0.36 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_dev.openjdk_aarch64_linux/5/)(`ub18-aarch64-1`)
```
[2023-01-20T06:19:36.747Z] variation: NoOptions
[2023-01-20T06:19:36.747Z] JVM_OPTIONS: 

[2023-01-20T06:22:28.045Z] TEST: jdk/internal/platform/docker/TestDockerCpuMetrics.java

[2023-01-20T06:22:28.070Z] STDERR:
[2023-01-20T06:22:28.070Z] java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.Metrics.getCpuSetMems()" because the return value of "jdk.internal.platform.Metrics.systemMetrics()" is null
[2023-01-20T06:22:28.070Z] 	at TestDockerCpuMetrics.main(TestDockerCpuMetrics.java:82)
[2023-01-20T06:22:28.070Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-20T06:22:28.070Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-01-20T06:22:28.070Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-20T06:22:28.070Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-01-20T06:22:28.070Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-01-20T06:22:28.070Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-01-20T06:22:28.070Z] 
[2023-01-20T06:22:28.070Z] JavaTest Message: Test threw exception: java.lang.NullPointerException

[2023-01-20T06:22:47.656Z] jdk_container_0_FAILED
```
