### ISSUE TITLE
jdk_container_jdk8_0_FAILED jdk/internal/platform/docker/TestUseContainerSupport.java RuntimeException: 'TEST PASSED!!!' missing from stdout/stderr 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16461]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_dev.openjdk_aarch64_linux/3/)(`ub18-aarch64-4`):
```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b05)
Eclipse OpenJ9 VM (build master-7cafd4be8, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20221210_513 (JIT enabled, AOT enabled)
OpenJ9   - 7cafd4be8
OMR      - 8ae31402f
JCL      - d9472a844 based on jdk8u362-b05)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_jdk8_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-debugimage_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-jre_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-testimage_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F513%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2022-12-10-03-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-12-10T07:31:17.409Z] variation: NoOptions
[2022-12-10T07:31:17.409Z] JVM_OPTIONS:  

[2022-12-10T07:42:19.011Z] TEST: jdk/internal/platform/docker/TestUseContainerSupport.java

[2022-12-10T07:42:19.012Z] STDERR:
[2022-12-10T07:42:19.012Z]  stdout: [-XX:-UseContainerSupport, but got Metrics.systemMetrics() == non-null
[2022-12-10T07:42:19.012Z] TEST FAILED!!!
[2022-12-10T07:42:19.012Z] ];
[2022-12-10T07:42:19.012Z]  stderr: []
[2022-12-10T07:42:19.012Z]  exitValue = 0
[2022-12-10T07:42:19.012Z] 
[2022-12-10T07:42:19.012Z] java.lang.RuntimeException: 'TEST PASSED!!!' missing from stdout/stderr 
[2022-12-10T07:42:19.012Z] 
[2022-12-10T07:42:19.012Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:150)
[2022-12-10T07:42:19.012Z] 	at TestUseContainerSupport.testUseContainerSupport(TestUseContainerSupport.java:68)
[2022-12-10T07:42:19.012Z] 	at TestUseContainerSupport.main(TestUseContainerSupport.java:49)
[2022-12-10T07:42:19.012Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-12-10T07:42:19.012Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-12-10T07:42:19.012Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-12-10T07:42:19.012Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-12-10T07:42:19.012Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-12-10T07:42:19.012Z] 	at java.lang.Thread.run(Thread.java:826)
[2022-12-10T07:42:19.012Z] 
[2022-12-10T07:42:19.012Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

jdk_container_jdk8_0_FAILED
```

[10x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30382/) - all failed

**Comment by pshipton** [comment]
@babsingh this test expects -XX:-UseContainerSupport to affect the behaviour of JVM_IsUseContainerSupport(). 
jdk.internal.platform.Metrics uses jdk.internal.platform.cgroupv1.Metrics which uses a native isUseContainerSupport() that calls JVM_IsUseContainerSupport() to determine if the Metrics instance is null or not.
