### ISSUE TITLE
JDK19 jdk_container_0_FAILED jdk/internal/platform/docker/TestUseContainerSupport.java RuntimeException: 'TEST PASSED!!!' missing from stdout/stderr 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16505]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_dev.openjdk_s390x_linux/6/)(`ub18s390xrt-1-10`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-a2475ea96, JRE 19 Linux s390x-64-Bit Compressed References 20221018_15 (JIT enabled, AOT enabled)
OpenJ9   - a2475ea96
OMR      - 7d8ea8b6b
JCL      - 5168276e58 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-s390x-openj9%2F15%2Fibm-semeru-open-debugimage_s390x_linux_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-s390x-openj9%2F15%2Fibm-semeru-open-jre_s390x_linux_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-s390x-openj9%2F15%2Fibm-semeru-open-testimage_s390x_linux_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-s390x-openj9%2F15%2Fibm-semeru-open-jdk_s390x_linux_JDK19U_2022-12-31-16-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-12-31T18:07:54.094Z] variation: NoOptions
[2022-12-31T18:07:54.094Z] JVM_OPTIONS:  

[2022-12-31T18:12:24.471Z] TEST: jdk/internal/platform/docker/TestUseContainerSupport.java

[2022-12-31T18:12:24.473Z] STDERR:
[2022-12-31T18:12:24.473Z]  stdout: [-XX:-UseContainerSupport, but got Metrics.systemMetrics() == non-null
[2022-12-31T18:12:24.473Z] TEST FAILED!!!
[2022-12-31T18:12:24.473Z] ];
[2022-12-31T18:12:24.473Z]  stderr: []
[2022-12-31T18:12:24.473Z]  exitValue = 0
[2022-12-31T18:12:24.473Z] 
[2022-12-31T18:12:24.473Z] java.lang.RuntimeException: 'TEST PASSED!!!' missing from stdout/stderr 
[2022-12-31T18:12:24.473Z] 
[2022-12-31T18:12:24.473Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
[2022-12-31T18:12:24.473Z] 	at TestUseContainerSupport.testUseContainerSupport(TestUseContainerSupport.java:71)
[2022-12-31T18:12:24.473Z] 	at TestUseContainerSupport.main(TestUseContainerSupport.java:51)
[2022-12-31T18:12:24.473Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-12-31T18:12:24.473Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-12-31T18:12:24.473Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-12-31T18:12:24.473Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2022-12-31T18:12:24.473Z] 
[2022-12-31T18:12:24.473Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-12-31T18:12:24.473Z] JavaTest Message: shutting down test
[2022-12-31T18:12:24.473Z] 
[2022-12-31T18:12:24.473Z] 
[2022-12-31T18:12:24.473Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'TEST PASSED!!!' missing from stdout/stderr
[2022-12-31T18:12:24.473Z] --------------------------------------------------
[2022-12-31T18:12:24.473Z] Test results: passed: 7; failed: 1; error: 1
[2022-12-31T18:12:42.161Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_dev.openjdk_s390x_linux/aqa-tests/TKG/output_16725100736628/jdk_container_0/report/html/report.html
[2022-12-31T18:12:42.161Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_dev.openjdk_s390x_linux/aqa-tests/TKG/output_16725100736628/jdk_container_0/work
[2022-12-31T18:12:42.161Z] Error: Some tests failed or other problems occurred.
[2022-12-31T18:12:42.161Z] -----------------------------------
[2022-12-31T18:12:42.161Z] jdk_container_0_FAILED
```

This is a test added on Dec. 2022, and didn't pass before.

**Comment by pshipton** [comment]
@llxia fyi
@JasonFengJ9 is this test running and passing on other versions?

**Comment by JasonFengJ9** [comment]
> is this test running and passing on other versions?

So far all other `dev.openjdk` containing this test timed out at JDK 8/11/17.

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/16461
