### ISSUE TITLE
cmdLineTester_criu_keepCheckpoint_2_FAILED org.eclipse.openj9.criu.SystemCheckpointException: The JVM attempted to load libcriu.so but was unable to: 1

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16503]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.functional_x86-64_linux_testList_2/77/)(`mwfips1`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-a2475ea96, JRE 19 Linux amd64-64-Bit Compressed References 20221018_15 (JIT enabled, AOT enabled)
OpenJ9   - a2475ea96
OMR      - 7d8ea8b6b
JCL      - 5168276e58 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=cmdLineTester_criu_keepCheckpoint_2&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_sanity.functional_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F15%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F15%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F15%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F15%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-12-31-16-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=77&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-12-31T17:32:13.429Z] variation: -Xjit:count=0
[2022-12-31T17:32:13.429Z] JVM_OPTIONS:  -Xjit:count=0 

[2022-12-31T17:32:29.456Z] Running command: bash /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_x86-64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 " org.openj9.criu.CRIUSimpleTest 1 1 true
[2022-12-31T17:32:29.837Z] Time spent starting: 639 milliseconds
[2022-12-31T17:32:31.662Z] Time spent executing: 2050 milliseconds
[2022-12-31T17:32:31.662Z] Test result: FAILED
[2022-12-31T17:32:31.662Z] Output from test:
[2022-12-31T17:32:31.662Z]  [OUT] start running script
[2022-12-31T17:32:31.662Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2022-12-31T17:32:31.662Z]  [OUT] export LD_BIND_NOT=on
[2022-12-31T17:32:31.662Z]  [OUT] Total checkpoint(s) 1:
[2022-12-31T17:32:31.662Z]  [OUT] Pre-checkpoint
[2022-12-31T17:32:31.662Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Sat Dec 31 12:32:30 EST 2022, System.currentTimeMillis(): 1672507950658, System.nanoTime(): 2678907449743828
[2022-12-31T17:32:31.662Z]  [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: The JVM attempted to load libcriu.so but was unable to: 1
[2022-12-31T17:32:31.662Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
[2022-12-31T17:32:31.662Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:595)
[2022-12-31T17:32:31.662Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:76)
[2022-12-31T17:32:31.662Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:64)
[2022-12-31T17:32:31.662Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:60)
[2022-12-31T17:32:31.662Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:43)
[2022-12-31T17:32:31.662Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:33)
[2022-12-31T17:32:31.662Z]  [OUT] finished script
[2022-12-31T17:32:31.662Z] >> Success condition was not found: [Output match: Killed]
[2022-12-31T17:32:31.662Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2022-12-31T17:32:31.662Z] >> Failure condition was not found: [Output match: Post-checkpoint]
[2022-12-31T17:32:31.662Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2022-12-31T17:32:31.662Z] >> Failure condition was not found: [Output match: Removed testOutput file]
[2022-12-31T17:32:31.662Z] >> Failure condition was not found: [Output match: Operation not permitted]
[2022-12-31T17:32:31.662Z] >> Failure condition was not found: [Output match: ERR]
[2022-12-31T17:32:31.662Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
[2022-12-31T17:32:31.662Z] 
[2022-12-31T17:32:31.662Z] 
[2022-12-31T17:32:31.662Z] ---TEST RESULTS---
[2022-12-31T17:32:31.662Z] Number of PASSED tests: 0 out of 1
[2022-12-31T17:32:31.662Z] Number of FAILED tests: 1 out of 1
[2022-12-31T17:32:31.662Z] 
[2022-12-31T17:32:31.662Z] ---SUMMARY OF FAILED TESTS---
[2022-12-31T17:32:31.662Z] Create Criu Checkpoint Image without Restore
[2022-12-31T17:32:31.662Z] -----------------------------
[2022-12-31T17:32:31.662Z] 
[2022-12-31T17:32:31.662Z] -----------------------------------
[2022-12-31T17:32:31.662Z] cmdLineTester_criu_keepCheckpoint_2_FAILED
```

This seems a test setup issue.

**Comment by llxia** [comment]
I haven't seen this issue occur in the recent JDK19 builds. Should we close this issue?

**Comment by JasonFengJ9** [comment]
This is not a JDK19 specific issue, a similar failure occurred at [JDK17 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_criu_testList_1/118/)(`rh-epyc7302p-1s16c-01`)

**Comment by cjjdespres** [comment]
I think this may also be appearing in the internal JITServer tests, e.g. in [JDK11 x86-86_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/1262/), which has a number of failures that look like this.

**Comment by JasonFengJ9** [comment]
[JDK11 0.38.0 m2 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/448/)(`cent7x64-1-9`)
```
openjdk version "11.0.19" 2023-04-18
IBM Semeru Runtime Open Edition 11.0.19.0-m2 (build 11.0.19+6)
Eclipse OpenJ9 VM 11.0.19.0-m2 (build v0.38.0-release-353bdb06f, JRE 11 Linux amd64-64-Bit Compressed References 20230329_681 (JIT enabled, AOT enabled)
OpenJ9   - 353bdb06f
OMR      - 855813495
JCL      - b04e256c1c based on jdk-11.0.19+6)

[2023-03-29T22:20:02.037Z] variation: -Xjit
[2023-03-29T22:20:02.037Z] JVM_OPTIONS:  -Xjit 

[2023-03-29T22:20:02.037Z] TESTING:
[2023-03-29T22:20:02.455Z] *** Starting test suite: J9 Criu Command-Line Option Tests ***
[2023-03-29T22:20:02.455Z] Testing: Create Criu Checkpoint Image without Restore
[2023-03-29T22:20:02.455Z] Test start time: 2023/03/29 15:20:02 Pacific Standard Time
[2023-03-29T22:20:02.455Z] Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xjit " org.openj9.criu.CRIUSimpleTest 1 1 true
[2023-03-29T22:20:02.455Z] Time spent starting: 41 milliseconds
[2023-03-29T22:20:02.874Z] Time spent executing: 212 milliseconds
[2023-03-29T22:20:02.874Z] Test result: FAILED
[2023-03-29T22:20:02.874Z] Output from test:
[2023-03-29T22:20:02.874Z]  [OUT] start running script
[2023-03-29T22:20:02.874Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2023-03-29T22:20:02.874Z]  [OUT] export LD_BIND_NOT=on
[2023-03-29T22:20:02.874Z]  [OUT] Total checkpoint(s) 1:
[2023-03-29T22:20:02.874Z]  [OUT] Pre-checkpoint
[2023-03-29T22:20:02.874Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Mar 29 15:20:02 PDT 2023, System.currentTimeMillis(): 1680128402388, System.nanoTime(): 1567748673359070
[2023-03-29T22:20:02.874Z]  [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: The JVM attempted to load libcriu.so but was unable to: 1
[2023-03-29T22:20:02.874Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
[2023-03-29T22:20:02.874Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:649)
[2023-03-29T22:20:02.874Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
[2023-03-29T22:20:02.874Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
[2023-03-29T22:20:02.874Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:61)
[2023-03-29T22:20:02.874Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:43)
[2023-03-29T22:20:02.874Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:33)
[2023-03-29T22:20:02.874Z]  [OUT] finished script
[2023-03-29T22:20:02.874Z] >> Success condition was not found: [Output match: Killed]
[2023-03-29T22:20:02.874Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2023-03-29T22:20:02.874Z] >> Failure condition was not found: [Output match: Post-checkpoint]
[2023-03-29T22:20:02.874Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2023-03-29T22:20:02.874Z] >> Failure condition was not found: [Output match: Removed testOutput file]
[2023-03-29T22:20:02.874Z] >> Failure condition was not found: [Output match: Operation not permitted]
[2023-03-29T22:20:02.874Z] >> Failure condition was not found: [Output match: ERR]
[2023-03-29T22:20:02.874Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```
