### ISSUE TITLE
JDK19 jcstress_BoundedSingleTest_0_FAILED NullPointerException: Cannot read field "sync" because "this" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16506]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_dev.system_ppc64_aix_testList_4/4/)(`paix823`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-a2475ea96, JRE 19 AIX ppc64-64-Bit Compressed References 20221018_15 (JIT enabled, AOT enabled)
OpenJ9   - a2475ea96
OMR      - 7d8ea8b6b
JCL      - 5168276e58 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jcstress_BoundedSingleTest_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_dev.system_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-aix-ppc64-openj9%2F15%2Fibm-semeru-open-debugimage_ppc64_aix_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-aix-ppc64-openj9%2F15%2Fibm-semeru-open-jre_ppc64_aix_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-aix-ppc64-openj9%2F15%2Fibm-semeru-open-testimage_ppc64_aix_JDK19U_2022-12-31-16-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-aix-ppc64-openj9%2F15%2Fibm-semeru-open-jdk_ppc64_aix_JDK19U_2022-12-31-16-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=6&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-01-01T02:13:10.943Z] variation: NoOptions
[2023-01-01T02:13:10.943Z] JVM_OPTIONS:  

[2023-01-01T02:16:44.483Z]     Unrecoverable error while running
[2023-01-01T02:16:44.483Z]     java.lang.NullPointerException: Cannot read field "sync" because "this" is null
[2023-01-01T02:16:44.483Z]     	at java.base/java.util.concurrent.CountDownLatch.countDown(CountDownLatch.java:290)
[2023-01-01T02:16:44.483Z]     	at org.openjdk.jcstress.tests.countdownlatch.racy.BoundedSingleTest.actor1(BoundedSingleTest.java:60)
[2023-01-01T02:16:44.483Z]     	at org.openjdk.jcstress.tests.countdownlatch.racy.BoundedSingleTest_jcstress.run_actor1(BoundedSingleTest_jcstress.java:256)
[2023-01-01T02:16:44.483Z]     	at org.openjdk.jcstress.tests.countdownlatch.racy.BoundedSingleTest_jcstress.task_actor1(BoundedSingleTest_jcstress.java:239)
[2023-01-01T02:16:44.483Z]     	at org.openjdk.jcstress.tests.countdownlatch.racy.BoundedSingleTest_jcstress.access$100(BoundedSingleTest_jcstress.java:19)
[2023-01-01T02:16:44.483Z]     	at org.openjdk.jcstress.tests.countdownlatch.racy.BoundedSingleTest_jcstress$6.internalRun(BoundedSingleTest_jcstress.java:156)
[2023-01-01T02:16:44.483Z]     	at org.openjdk.jcstress.infra.runners.CounterThread.run(CounterThread.java:38)

[2023-01-01T02:16:45.162Z] jcstress_BoundedSingleTest_0_FAILED
```

This is a new test added on Dec. 2022, and didn't pass before.

**Comment by pshipton** [comment]
@JasonFengJ9 all the failures seem to be on AIX. Is the test running and passing on other platforms?

**Comment by JasonFengJ9** [comment]
> all the failures seem to be on AIX. Is the test running and passing on other platforms?

Added `AIX` label, the test in question passed in other platforms.

**Comment by pshipton** [comment]
@llxia fyi
@JasonFengJ9 does this pass on OpenJDK?

**Comment by JasonFengJ9** [comment]
> does this pass on OpenJDK?

```
13:07:04  openjdk version "19.0.1-beta" 2022-10-18
13:07:04  OpenJDK Runtime Environment Temurin-19+36-202210180349 (build 19.0.1-beta+36-202210180349)
13:07:04  OpenJDK 64-Bit Server VM Temurin-19+36-202210180349 (build 19.0.1-beta+36-202210180349, mixed mode)
```
[5x grinder w/ RI](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/1902/tapResults/) all passed

Note: this is a temurin build on Oct. 2022, there are no newer nightly builds available.

**Comment by pshipton** [comment]
I was just about to ask for 17 but I see it's been added to the previous comment.

**Comment by pshipton** [comment]
I see 17 Temurin passed as well.

**Comment by pshipton** [comment]
I don't know what component is at fault. @JasonFengJ9 can you try one more on OpenJ9 with -Xint pls.

**Comment by JasonFengJ9** [comment]
[JDK -Xint 10x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30378/console) - all passed

**Comment by 0xdaryl** [comment]
Moving out to 0.40.

@zl-wang : since this issue only appeared on AIX could you assign for investigation please?

**Comment by zl-wang** [comment]
@midronij please take a look ...

**Comment by 0xdaryl** [comment]
Moving to 0.41.

**Comment by hzongaro** [comment]
@midronij, when you have the opportunity, may I ask you to provide an update on the investigation of this problem?  I'll move this to the 0.43 release in the meanwhile.

**Comment by midronij** [comment]
@hzongaro very sorry for the delay. Unfortunately, as I've been occupied with other work, I haven't had much chance to investigate this issue in earnest. If it's alright, I will pick this item back up again as soon as I'm able.

**Comment by zl-wang** [comment]
@bhavanisn please take this over (at lower priority)
