### ISSUE TITLE
JDK8 jcstress_DoubleAtomicityTest_0_FAILED NoSuchMethodError: java/lang/Thread.onSpinWait()V 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16509]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_dev.system_x86-32_windows_testList_1/4/):
```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b07)
Eclipse OpenJ9 VM (build master-a2475ea96, JRE 1.8.0 Windows Server 2016 x86-32-Bit 20221231_542 (JIT enabled, AOT enabled)
OpenJ9   - a2475ea96
OMR      - 7d8ea8b6b
JCL      - 4d70df27c based on jdk8u362-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jcstress_DoubleAtomicityTest_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_dev.system_x86-32_windows&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-32_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F542%2Fibm-semeru-open-jdk_x86-32_windows_JDK8U_2022-12-31-03-30.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F542%2Fibm-semeru-open-testimage_x86-32_windows_JDK8U_2022-12-31-03-30.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F542%2Fibm-semeru-open-jre_x86-32_windows_JDK8U_2022-12-31-03-30.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F542%2Fibm-semeru-open-debugimage_x86-32_windows_JDK8U_2022-12-31-03-30.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=6&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-12-31T06:12:13.459Z] ----- [N/A] Testing Thread.onSpinWait
[2022-12-31T06:12:13.459Z] Exception in thread "main" java.lang.NoSuchMethodError: java/lang/Thread.onSpinWait()V (loaded from C:\Users\jenkins\workspace\Test_openjdk8_j9_dev.system_x86-32_windows_testList_1\openjdkbinary\j2sdk-image\jre\lib\rt.jar by <Bootstrap Loader>) called from class org.openjdk.jcstress.vm.ThreadSpinWaitTestMain (loaded from file:/C:/Users/jenkins/workspace/Test_openjdk8_j9_dev.system_x86-32_windows_testList_1/aqa-tests/TKG/lib/jcstress-tests-all-20220908.jar by sun.misc.Launcher$AppClassLoader@6a1b5439).
[2022-12-31T06:12:13.459Z] 	at org.openjdk.jcstress.vm.ThreadSpinWaitTestMain.main(ThreadSpinWaitTestMain.java:30)

[2022-12-31T06:16:30.745Z] jcstress_DoubleAtomicityTest_0_FAILED
```
This is an invalid test for JDK8 since `java/lang/Thread.onSpinWait()V` was added at Java 9.

**Comment by pshipton** [comment]
@llxia @Mesbah-Alam fyi

**Comment by llxia** [comment]
`NoSuchMethodError` in `Thread.onSpinWait` did not cause the failure in the test target `jcstress_DoubleAtomicityTest_0`. I think the failure is due to `VolatileDoubleAtomicityTest`:

```
 Failed tests: 1 matching test results.

...... [FAILED] o.o.j.t.atomicity.primitives.perbyte.VolatileDoubleAtomicityTest

```

I see the same `NoSuchMethodError` error in Termriu JDK8, but the test target `jcstress_DoubleAtomicityTest` passed.

```
00:50:18.865  ----- [N/A] Testing Thread.onSpinWait
00:50:18.865  Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Thread.onSpinWait()V
00:50:18.865  	at org.openjdk.jcstress.vm.ThreadSpinWaitTestMain.main(ThreadSpinWaitTestMain.java:30)
...
00:50:32.339  jcstress_DoubleAtomicityTest_0_PASSED
```
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_dev.system_x86-32_windows/6/consoleFull

**Comment by pshipton** [comment]
@JasonFengJ9 pls try the test with -Xint so we can assign to JIT or VM.

**Comment by JasonFengJ9** [comment]
[50x grinder -Xint](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30398/console) - all passed
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30397/console) - 40 failed (some still in progress)
Tagging JIT.

**Comment by 0xdaryl** [comment]
As this appears to only affect 32-bit Windows I'll assign to @BradleyWood.  Moving to 0.40, but since this is 32-bit only it is lower priority than other issues.

**Comment by hzongaro** [comment]
I'm going to move this into the Backlog, as it's only affecting 32-bit.
