### ISSUE TITLE
Windows win2019 ClassNotFoundException or file system problem

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16513]
I suspect this is a problem with the new Windows machines rather than a problem with jdk19. @vsebe fyi

https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.system_x86-64_windows_Nightly_testList_0/85 - [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)
MiniMix_5m_0
```
00:38:12  LT  00:38:12.321 - Test failed
00:38:12  LT    Failure num.  = 1
00:38:12  LT    Test number   = 3525
00:38:12  LT    Test details  = 'Mauve[gnu.testlet.java.util.logging.Level.equals]'
00:38:12  LT    Suite number  = 0
00:38:12  LT    Thread number = 0
00:38:12  LT  >>> Captured test output >>>
00:38:12  LT  Test failed:
00:38:12  LT  java.lang.ClassNotFoundException: gnu.testlet.java.util.logging.Level.equals
00:38:12  LT  	at java.base/java.lang.Class.forNameImpl(Native Method)
00:38:12  LT  	at java.base/java.lang.Class.forName(Class.java:374)
00:38:12  LT  	at java.base/java.lang.Class.forName(Class.java:350)
00:38:12  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
00:38:12  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
00:38:12  LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
00:38:12  LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
00:38:12  LT  	at java.base/java.lang.Thread.run(Thread.java:1573)
00:38:12  LT  <<<
```

**Comment by vsebe** [comment]
10 MiniMix_5m_0 [grinder](https://openj9-jenkins.osuosl.org/job/Grinder/1815/) on [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_0/444 - [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)
MiniMix_5m_1 
```
03:30:52  LT  03:30:52.375 - Test failed
03:30:52  LT    Failure num.  = 1
03:30:52  LT    Test number   = 2730
03:30:52  LT    Test details  = 'Mauve[gnu.testlet.java.lang.StringIndexOutOfBoundsException.classInfo.isPrimitive]'
03:30:52  LT    Suite number  = 0
03:30:52  LT    Thread number = 0
03:30:52  LT  >>> Captured test output >>>
03:30:52  LT  Test failed:
03:30:52  LT  java.lang.ClassNotFoundException: gnu.testlet.java.lang.StringIndexOutOfBoundsException.classInfo.isPrimitive
03:30:52  LT  	at java.base/java.lang.Class.forNameImpl(Native Method)
03:30:52  LT  	at java.base/java.lang.Class.forName(Class.java:354)
03:30:52  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
```

**Comment by vsebe** [comment]
10 MiniMix_5m_1 [grinder](https://openj9-jenkins.osuosl.org/job/Grinder/1818/console) on [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_1/442 - [win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1)
testDDRExt_Class_0
```
23:20:39  TESTING:
23:20:40  Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
23:20:40  -----------------------------------
23:20:40  testDDRExt_Class_0_FAILED
```

**Comment by vsebe** [comment]
10 x testDDRExt_Class_0 [grinder](https://openj9-jenkins.osuosl.org/job/Grinder/1889/) on [win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1) - passed

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly_testList_0/409 - [win2019-x64-4a](https://openj9-jenkins.osuosl.org/computer/win2019-x64-4a)
MiniMix_5m_1 
```
23:23:30  LT  java.lang.ClassNotFoundException: gnu.testlet.java.io.InterruptedIOException.classInfo.isSynthetic
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.system_x86-64_windows_Nightly_testList_0/102 - [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)
```
03:09:00  build-java-above-11:
03:09:00      [javac] Compiling 16 source files to C:\Users\****\workspace\Test_openjdk19_j9_sanity.system_x86-64_windows_Nightly_testList_0\aqa-tests\system\aqa-systemtest\openjdk.test.debugging\bin
03:09:02      [javac] error: error reading C:\Users\****\workspace\Test_openjdk19_j9_sanity.system_x86-64_windows_Nightly_testList_0\aqa-tests\systemtest_prereqs\tools\tools.jar; zip END header not found
03:09:02  
03:09:02  BUILD FAILED
```
