### ISSUE TITLE
OpenJDK java/util/Objects/CheckIndex.java Index 0 is out of bounds

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16536]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/241/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK17/399/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/459/
Failing on all platforms on jdk11+, example https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly/341 (output from this below)
java/util/Objects/CheckIndex.java

On jdk19 xlinux, xmac and Windows there are also similar jdk/incubator/vector failures.
jdk/incubator/vector/Byte128VectorTests.java.Byte128VectorTests
jdk/incubator/vector/Byte64VectorTests.java.Byte64VectorTests
jdk/incubator/vector/Float128VectorTests.java.Float128VectorTests
jdk/incubator/vector/Int128VectorTests.java.Int128VectorTests
jdk/incubator/vector/Short128VectorTests.java.Short128VectorTests

```
21:44:44  test CheckIndex.testCheckIndex(0, -1, false): failure
21:44:44  java.lang.AssertionError: Index 0 is out of bounds of [0, -1), but was reported to be within bounds
21:44:44  	at org.testng.Assert.fail(Assert.java:99)
21:44:44  	at CheckIndex.lambda$testCheckIndex$2(CheckIndex.java:107)
21:44:44  	at CheckIndex.testCheckIndex(CheckIndex.java:121)

21:44:44  test CheckIndex.testCheckIndex(0, -2147483647, false): failure
21:44:44  java.lang.AssertionError: Index 0 is out of bounds of [0, -2147483647), but was reported to be within bounds
21:44:44  	at org.testng.Assert.fail(Assert.java:99)
21:44:44  	at CheckIndex.lambda$testCheckIndex$2(CheckIndex.java:107)
21:44:44  	at CheckIndex.testCheckIndex(CheckIndex.java:121)

21:44:44  test CheckIndex.testCheckIndex(0, -2147483648, false): failure
21:44:44  java.lang.AssertionError: Index 0 is out of bounds of [0, -2147483648), but was reported to be within bounds
21:44:44  	at org.testng.Assert.fail(Assert.java:99)
21:44:44  	at CheckIndex.lambda$testCheckIndex$2(CheckIndex.java:107)
21:44:44  	at CheckIndex.testCheckIndex(CheckIndex.java:121)

21:44:44  test CheckIndex.testCheckIndex(1, -1, false): failure
21:44:44  java.lang.AssertionError: Index 1 is out of bounds of [0, -1), but was reported to be within bounds
21:44:44  	at org.testng.Assert.fail(Assert.java:99)
21:44:44  	at CheckIndex.lambda$testCheckIndex$2(CheckIndex.java:107)
21:44:44  	at CheckIndex.testCheckIndex(CheckIndex.java:121)

21:44:44  test CheckIndex.testCheckIndex(1, -2147483647, false): failure
21:44:44  java.lang.AssertionError: Index 1 is out of bounds of [0, -2147483647), but was reported to be within bounds
21:44:44  	at org.testng.Assert.fail(Assert.java:99)
21:44:44  	at CheckIndex.lambda$testCheckIndex$2(CheckIndex.java:107)
21:44:44  	at CheckIndex.testCheckIndex(CheckIndex.java:121)

21:44:44  test CheckIndex.testCheckIndex(1, -2147483648, false): failure
21:44:44  java.lang.AssertionError: Index 1 is out of bounds of [0, -2147483648), but was reported to be within bounds
21:44:44  	at org.testng.Assert.fail(Assert.java:99)
21:44:44  	at CheckIndex.lambda$testCheckIndex$2(CheckIndex.java:107)
21:44:44  	at CheckIndex.testCheckIndex(CheckIndex.java:121)

etc.
```
Changes https://github.com/eclipse-openj9/openj9/compare/1af3bf45572bd...26019dda094

Given the list of changes, this seems to be caused by https://github.com/eclipse-openj9/openj9/pull/16459
@gita-omr @Akira1Saitoh @0xdaryl

**Comment by pshipton** [comment]
This needs to be resolved / backed out today.

**Comment by pshipton** [comment]
Reproduced in a grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1823/
Build with https://github.com/eclipse-openj9/openj9/pull/16459 reverted https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/316/
from https://github.com/pshipton/openj9/commit/42bdf313e42e
Grinder on revert PASSED https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1824/

https://github.com/eclipse-openj9/openj9/pull/16459 is reverted by https://github.com/eclipse-openj9/openj9/pull/16537
