### ISSUE TITLE
jdk_container_jdk8_0_FAILED open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16568]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_dev.openjdk_aarch64_linux/6/)(`cent7-aarch64-5`):
```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b07)
Eclipse OpenJ9 VM (build v0.36.0-release-c5da55ccc, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20230113_538 (JIT enabled, AOT enabled)
OpenJ9   - c5da55ccc
OMR      - 2bb04132e
JCL      - 1a94e3037e based on jdk8u362-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_jdk8_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F538%2Fibm-semeru-open-testimage_aarch64_linux_8u362b07_openj9-0.36.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F538%2Fibm-semeru-open-jre_aarch64_linux_8u362b07_openj9-0.36.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F538%2Fibm-semeru-open-debugimage_aarch64_linux_8u362b07_openj9-0.36.0-m2.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F538%2Fibm-semeru-open-jdk_aarch64_linux_8u362b07_openj9-0.36.0-m2.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.36.0-release&amp;OPENJ9_BRANCH=v0.36.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.36.0-release&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-01-13T19:35:34.535Z] variation: NoOptions
[2023-01-13T19:35:34.535Z] JVM_OPTIONS:  

[2023-01-13T19:35:54.979Z] TEST: jdk/internal/platform/docker/TestDockerMemoryMetrics.java

[2023-01-13T19:35:54.980Z] STDERR:
[2023-01-13T19:35:54.980Z]  stdout: [Sending build context to Docker daemon 835.9 MB

[2023-01-13T19:35:54.980Z] Step 1/4 : FROM registry.access.redhat.com/ubi8/ubi:latest
[2023-01-13T19:35:54.980Z] Trying to pull repository registry.access.redhat.com/ubi8/ubi ... 
[2023-01-13T19:35:54.980Z] ];
[2023-01-13T19:35:54.980Z]  stderr: [open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
[2023-01-13T19:35:54.980Z] ]
[2023-01-13T19:35:54.980Z]  exitValue = 1
[2023-01-13T19:35:54.980Z] 
[2023-01-13T19:35:54.980Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2023-01-13T19:35:54.980Z] 
[2023-01-13T19:35:54.980Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
[2023-01-13T19:35:54.980Z] 	at jdk.test.lib.containers.docker.DockerTestUtils.buildDockerImage(DockerTestUtils.java:173)
[2023-01-13T19:35:54.980Z] 	at jdk.test.lib.containers.docker.DockerTestUtils.buildJdkDockerImage(DockerTestUtils.java:149)
[2023-01-13T19:35:54.980Z] 	at TestDockerMemoryMetrics.main(TestDockerMemoryMetrics.java:50)
[2023-01-13T19:35:54.980Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-13T19:35:54.980Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-13T19:35:54.980Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-13T19:35:54.980Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-01-13T19:35:54.980Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2023-01-13T19:35:54.980Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-01-13T19:35:54.980Z] 
[2023-01-13T19:35:54.980Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

[2023-01-13T19:36:14.291Z] jdk_container_jdk8_0_FAILED
```

**Comment by pshipton** [comment]
@llxia is this a test problem?

**Comment by llxia** [comment]
The test ran to completion with actual test failure on[ Dec 10th](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_dev.openjdk_aarch64_linux/3/console) on ub18-aarch64-4.svl.ibm.com. The test failure is tracked at https://github.com/eclipse-openj9/openj9/issues/16462

Launched Grinder on ub18-aarch64-4.svl.ibm.com: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30487/)

**Comment by llxia** [comment]
The above Grinder passed the `Step 1/4 : FROM registry.access.redhat.com/ubi8/ubi:latest`. It failed later with NullPointerException, which is the same as https://github.com/eclipse-openj9/openj9/issues/16462

**Comment by llxia** [comment]
This problem seems can be resolved by create redhat-uep.pem file on CentOS (see [link](https://github.com/minishift/minishift-centos-iso/issues/251)). I will give it a try.

**Comment by llxia** [comment]
Thanks for @AdamBrousseau 's help. The file is added on all cent aarch64. 
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30491/) on `cent7-aarch64-5.svl.ibm.com` can pull image from redbat registry without problem.
The Grinder failed at later stage with NullPointerException, which is another issue https://github.com/eclipse-openj9/openj9/issues/16462

**Comment by pshipton** [comment]
This can be closed then?

**Comment by llxia** [comment]
Yes, I will close this issue. Please reopen if the problem still occurs.
