### ISSUE TITLE
Jep389Tests_testClinkerFfi_UpCall_0_FAILED UnsupportedOperationException: Invalid alignment requirements for layout B64(elem3)[abi/kind=LONG_LONG,layout/name=elem3]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16561]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_0/305/)(`paix818`):
```
java version "17.0.6-beta" 2023-01-17
IBM Semeru Runtime Certified Edition 17.0.6+9-202301170022 (build 17.0.6-beta+9-202301170022)
Eclipse OpenJ9 VM 17.0.6+9-202301170022 (build master-082682ae5, JRE 17 AIX ppc64-64-Bit Compressed References 20230116_309 (JIT enabled, AOT enabled)
OpenJ9   - 082682ae5
OMR      - ec81a72de
JCL      - a2e3ba1558 based on jdk-17.0.6+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=Jep389Tests_testClinkerFfi_UpCall_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.functional_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F309%2Fibm-semeru-certified-testimage_ppc64_aix_JDK17U_2023-01-17-00-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F309%2Fibm-semeru-certified-debugimage_ppc64_aix_JDK17U_2023-01-17-00-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F309%2Fibm-semeru-certified-jdk_ppc64_aix_JDK17U_2023-01-17-00-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F309%2Fibm-semeru-certified-jre_ppc64_aix_JDK17U_2023-01-17-00-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=334&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-01-17T03:15:03.869Z] variation: --enable-preview
[2023-01-17T03:15:03.869Z] JVM_OPTIONS:  --enable-preview 


[2023-01-17T03:15:09.880Z] FAILED: test_addDoubleAndIntDoubleLongFromStructByUpcallMH
[2023-01-17T03:15:09.880Z] java.lang.UnsupportedOperationException: Invalid alignment requirements for layout B64(elem3)[abi/kind=LONG_LONG,layout/name=elem3]
[2023-01-17T03:15:09.880Z] 	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.checkAlignment(LayoutPath.java:291)
[2023-01-17T03:15:09.880Z] 	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:161)
[2023-01-17T03:15:09.880Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.lambda$varHandle$2(MemoryLayout.java:491)
[2023-01-17T03:15:09.880Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.computePathOp(MemoryLayout.java:581)
[2023-01-17T03:15:09.880Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.varHandle(MemoryLayout.java:491)
[2023-01-17T03:15:09.880Z] 	at org.openj9.test.jep389.upcall.UpcallMHWithMixedSigStruTests.test_addDoubleAndIntDoubleLongFromStructByUpcallMH(UpcallMHWithMixedSigStruTests.java:870)
[2023-01-17T03:15:09.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-17T03:15:09.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-01-17T03:15:09.880Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-17T03:15:09.880Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-01-17T03:15:09.880Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2023-01-17T03:15:09.880Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2023-01-17T03:15:09.880Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2023-01-17T03:15:09.880Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2023-01-17T03:15:09.880Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-01-17T03:15:09.880Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2023-01-17T03:15:09.880Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2023-01-17T03:15:09.880Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2023-01-17T03:15:09.880Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2023-01-17T03:15:09.880Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2023-01-17T03:15:09.880Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-01-17T03:15:09.880Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2023-01-17T03:15:09.880Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2023-01-17T03:15:09.880Z] 
[2023-01-17T03:15:09.880Z] 
[2023-01-17T03:15:09.880Z] ===============================================
[2023-01-17T03:15:09.880Z]     Jep389Tests_testClinkerFfi_UpCall
[2023-01-17T03:15:09.880Z]     Tests run: 207, Failures: 1, Skips: 0
[2023-01-17T03:15:09.880Z] ===============================================
[2023-01-17T03:15:09.880Z] 
[2023-01-17T03:15:09.880Z] 
[2023-01-17T03:15:09.880Z] ===============================================
[2023-01-17T03:15:09.880Z] Java17 test suite
[2023-01-17T03:15:09.880Z] Total tests run: 207, Failures: 1, Skips: 0
[2023-01-17T03:15:09.880Z] ===============================================
[2023-01-17T03:15:09.880Z] 
[2023-01-17T03:15:11.679Z] -----------------------------------
[2023-01-17T03:15:11.679Z] Jep389Tests_testClinkerFfi_UpCall_0_FAILED
[2023-01-17T03:15:11.679Z] -----------------------------------
```

[10x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30466/)

**Comment by pshipton** [comment]
The grinders had some issues, but the failure is not intermittent.
@ChengJin01 pls take a look.

**Comment by ChengJin01** [comment]
This is a test case issue as we should follow the test in JDK19 to have the long type aligned with 32bit to deal with case of `[int, double, long]` at https://github.com/eclipse-openj9/openj9/blob/f0ef7c02d7441433143c20779005df5366bd97cf/test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMHWithMixedSigStruTests.java#L828.

I already fixed this in JDK17 at https://github.com/ChengJin01/openj9/commit/9e844c517b03e287b54fcc733e2098ef93febc95 which works good as expected.
```
...
PASSED: test_addDoubleAndIntDoubleLongFromStructByUpcallMH <----------
...
===============================================
    Jep389Tests_testClinkerFfi_UpCall
    Tests run: 207, Failures: 0, Skips: 0
===============================================

===============================================
Java17 test suite
Total tests run: 207, Failures: 0, Skips: 0
===============================================
```

**Comment by pshipton** [comment]
Another failure 
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR_testList_1/257

**Comment by JasonFengJ9** [comment]
For `0.36` release tracking purpose, this failure occurred at [JDK17 internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_1/308/)(`paix906`) before the test was fixed.
```
java version "17.0.6" 2023-01-17
IBM Semeru Runtime Certified Edition 17.0.6.0-rc1 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0-rc1 (build v0.36.0-release-e68fb241f, JRE 17 AIX ppc64-64-Bit Compressed References 20230117_313 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - e248569a781 based on jdk-17.0.6+10)

[2023-01-20T05:43:47.806Z] variation: --enable-preview
[2023-01-20T05:43:47.806Z] JVM_OPTIONS:  --enable-preview 

[2023-01-20T05:43:50.885Z] FAILED: test_addDoubleAndIntDoubleLongFromStructByUpcallMH
[2023-01-20T05:43:50.885Z] java.lang.UnsupportedOperationException: Invalid alignment requirements for layout B64(elem3)[abi/kind=LONG_LONG,layout/name=elem3]
[2023-01-20T05:43:50.885Z] 	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.checkAlignment(LayoutPath.java:291)
[2023-01-20T05:43:50.885Z] 	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:161)
[2023-01-20T05:43:50.885Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.lambda$varHandle$2(MemoryLayout.java:491)
[2023-01-20T05:43:50.885Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.computePathOp(MemoryLayout.java:581)
[2023-01-20T05:43:50.885Z] 	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.varHandle(MemoryLayout.java:491)
[2023-01-20T05:43:50.885Z] 	at org.openj9.test.jep389.upcall.UpcallMHWithMixedSigStruTests.test_addDoubleAndIntDoubleLongFromStructByUpcallMH(UpcallMHWithMixedSigStruTests.java:870)
[2023-01-20T05:43:50.885Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-20T05:43:50.885Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-01-20T05:43:50.885Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-20T05:43:50.885Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-01-20T05:43:50.885Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2023-01-20T05:43:50.885Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2023-01-20T05:43:50.885Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2023-01-20T05:43:50.885Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2023-01-20T05:43:50.885Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-01-20T05:43:50.885Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2023-01-20T05:43:50.885Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2023-01-20T05:43:50.885Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2023-01-20T05:43:50.885Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2023-01-20T05:43:50.885Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2023-01-20T05:43:50.885Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-01-20T05:43:50.885Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2023-01-20T05:43:50.885Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2023-01-20T05:43:50.885Z] 
[2023-01-20T05:43:50.885Z] 
[2023-01-20T05:43:50.885Z] ===============================================
[2023-01-20T05:43:50.885Z]     Jep389Tests_testClinkerFfi_UpCall
[2023-01-20T05:43:50.885Z]     Tests run: 207, Failures: 1, Skips: 0
[2023-01-20T05:43:50.885Z] ===============================================
[2023-01-20T05:43:50.885Z] 
[2023-01-20T05:43:50.885Z] 
[2023-01-20T05:43:50.885Z] ===============================================
[2023-01-20T05:43:50.885Z] Java17 test suite
[2023-01-20T05:43:50.885Z] Total tests run: 207, Failures: 1, Skips: 0
[2023-01-20T05:43:50.885Z] ===============================================
[2023-01-20T05:43:50.885Z] 
[2023-01-20T05:43:51.628Z] -----------------------------------
[2023-01-20T05:43:51.628Z] Jep389Tests_testClinkerFfi_UpCall_0_FAILED
```
