### ISSUE TITLE
DaaLoadTest_daa1 testConvertBigDecimalNormals Negative length

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16587]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_special.system_aarch64_linux_Release_testList_2/37
DaaLoadTest_daa1_special_5m_1 `-Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_special.system_aarch64_linux_Release_testList_2/37/system_test_output.tar.gz

1.DLT.executionlog.1.ltd
```
testFailure: testConvertBigDecimalNormals(net.openj9.test.decimals.TestDecimalData): Negative length
java.lang.IllegalArgumentException: Negative length
	at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1567)
	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.newArray(StringConcatFactory.java:1633)
	at net.openj9.test.Utils.makeTestNameConverterValue(Utils.java:787)
	at net.openj9.test.decimals.TestDecimalData.testConvertBigDecimalNormals(TestDecimalData.java:6812)
...
testFailure: testNonExceptions(net.openj9.test.decimals.TestDecimalData): Negative length
java.lang.IllegalArgumentException: Negative length
	at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1567)
	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.newArray(StringConcatFactory.java:1633)
	at net.openj9.test.Utils.makeTestNameConverterValue(Utils.java:787)
	at net.openj9.test.decimals.TestDecimalData.testConvertBigDecimalNormals(TestDecimalData.java:6812)
	at net.openj9.test.decimals.TestDecimalData.testNonExceptions(TestDecimalData.java:101)

```

Seems related to https://github.com/eclipse-openj9/openj9/issues/16527

**Comment by pshipton** [comment]
15x x 4 grinder https://openj9-jenkins.osuosl.org/job/Grinder/1836/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_special.system_aarch64_linux_Personal_testList_4/155
DaaLoadTest_daa1_special_5m_4 ` -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs`
```
testFailure: testConvertBigDecimalNormals(net.openj9.test.decimals.TestDecimalData): Negative length
java.lang.IllegalArgumentException: Negative length
	at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1567)
	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.newArray(StringConcatFactory.java:1633)
	at net.openj9.test.Utils.makeTestNameConverterValue(Utils.java:787)
	at net.openj9.test.decimals.TestDecimalData.testConvertBigDecimalNormals(TestDecimalData.java:6812)
```
