### ISSUE TITLE
OMR acceptance SCURLClassLoaderNPTests_0 crash vmState=0x0005ffff

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16589]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_OMR/287
SCURLClassLoaderNPTests_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.functional_aarch64_linux_OMR_testList_0/285/functional_test_output.tar.gz
```
Testing: SignedSealed.BuildInitial1
Test start time: 2023/01/20 19:23:01 Coordinated Universal Time
Running command: sh ./SignedSealed/buildInitial1.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_OMR_testList_0/openjdkbinary/j2sdk-image/bin
Time spent starting: 2 milliseconds
***[TEST INFO 2023/01/20 19:33:02] ProcessKiller detected a timeout after 600000 milliseconds!***
INFO: Cannot find '/usr/bin/gdb' using 'gdb' from the path.
***[TEST INFO 2023/01/20 19:33:02] executing gdb -batch -x /tmp/debugger16960881800363760583.txt sh 1341143***
java.io.IOException: Cannot run program "gdb": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:697)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:646)
	at Test$ProcessKiller.run(Test.java:596)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 6 more
***[TEST INFO 2023/01/20 19:33:02] executing kill -ABRT 1341143***
***[TEST INFO 2023/01/20 19:33:03] kill -ABRT signal sent***
***[TEST INFO 2023/01/20 19:33:03] ABRT completed***
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/signedsealed/A_Data.class(in = 341) (out= 252)(deflated 26%)
 [OUT] adding: jnurlcldr/shared/signedsealed/A_Main.class(in = 1084) (out= 605)(deflated 44%)
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Data.class(in = 316) (out= 228)(deflated 27%)
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Dummy.class(in = 342) (out= 249)(deflated 27%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Data.class(in = 313) (out= 232)(deflated 25%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Dummy.class(in = 336) (out= 247)(deflated 26%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Data.class(in = 316) (out= 228)(deflated 27%)
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Dummy.class(in = 342) (out= 249)(deflated 27%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Data.class(in = 313) (out= 232)(deflated 25%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Dummy.class(in = 336) (out= 247)(deflated 26%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Data.class(in = 316) (out= 228)(deflated 27%)
 [ERR] rm: cannot remove '*.jar': No such file or directory
 [ERR] Unhandled exception
 [ERR] Type=Segmentation error vmState=0x0005ffff
 [ERR] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
 [ERR] Handler1=0000FFFFA4CB1D38 Handler2=0000FFFFA4C28558 InaccessibleAddress=0000000000000018
 [ERR] R0=0000000000000018 R1=0000000000000018 R2=000000000007B058 R3=0000000000000000
 [ERR] R4=00000000000C7D90 R5=0000000000000000 R6=0000FFFFA015FE50 R7=0000FFFF82F12000
 [ERR] R8=000000000FE69050 R9=0000000000000018 R10=003ABF5068DA91D1 R11=0000270122A36879
 [ERR] R12=0000270122A36879 R13=0000000000001448 R14=0000000000000000 R15=0000000000001520
 [ERR] R16=0000FFFFA4BFD118 R17=0000FFFFA53D1AA8 R18=0000000000000000 R19=0000000000029168
 [ERR] R20=0000FFFF8401ABCC R21=0000000000013700 R22=0000FFFFA0024A50 R23=0000000000013700
 [ERR] R24=0000000000000000 R25=0000FFFFA015FE50 R26=0000FFFFA00E0800 R27=0000000000000001
 [ERR] R28=0000000000029168 R29=0000FFFF8400FFF0 R30=0000FFFF9FD80668 R31=0000FFFF8400FFF0
 [ERR] PC=0000FFFF9FD806B4 SP=0000FFFF8400FFF0 PSTATE=0000000060001000
 [ERR] V0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V1 687361682e746365 (f: 779379584.000000, d: 1.414758e+195)
 [ERR] V2 ffe0001fffe0001f (f: 4292870144.000000, d: -8.988740e+307)
 [ERR] V3 9407c4ddf900029e (f: 4177527552.000000, d: -3.530240e-212)
 [ERR] V4 000000000000ffff (f: 65535.000000, d: 3.237859e-319)
 [ERR] V5 0000ffff254590b8 (f: 625316032.000000, d: 1.390653e-309)
 [ERR] V6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V7 4010040140100401 (f: 1074791424.000000, d: 4.003911e+00)
 [ERR] V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V16 5554000000005404 (f: 21508.000000, d: 1.119872e+103)
 [ERR] V17 aaaaaaa000040000 (f: 262144.000000, d: -3.720639e-103)
 [ERR] V18 8020080280200000 (f: 2149580800.000000, d: -4.458850e-308)
 [ERR] V19 0000ffffa4cd1b78 (f: 2764905216.000000, d: 1.390664e-309)
 [ERR] V20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] V31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_OMR_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so
 [ERR] Module_base_address=0000FFFF9F5EA000
 [ERR] 
 [ERR] Method_being_compiled=java/lang/Object.hashCode()I
 [ERR] Target=2_90_20230120_297 (Linux 5.4.0-135-generic)
 [ERR] CPU=aarch64 (8 logical CPUs) (0x1eff6d000 RAM)
 [ERR] ----------- Stack Backtrace -----------
 [ERR] protectedBacktrace+0x18 (0x0000FFFFA4C24CC0 [libj9prt29.so+0x26cc0])
 [ERR] ---------------------------------------
```

OMR change https://github.com/eclipse-openj9/openj9-omr/compare/333650df...12faa3e3006
@hzongaro @0xdaryl is this crash caused by the OMR change?

**Comment by pshipton** [comment]
20x x 3 grinder https://openj9-jenkins.osuosl.org/job/Grinder/1846/
