### ISSUE TITLE
Adopt_J9_FeatureTests_0_FAILED Failed to match CA certs number. expected [138] but found [139]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16592]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk19u/job/jdk19u-mac-aarch64-openj9_SmokeTests/25/):
```
20:26:07  openjdk version "19.0.2" 2023-01-17
20:26:07  IBM Semeru Runtime Open Edition 19.0.2+7 (build 19.0.2+7)
20:26:07  Eclipse OpenJ9 VM 19.0.2+7 (build master-d18a29d0c, JRE 19 Mac OS X aarch64-64-Bit 20230117_27 (JIT enabled, AOT enabled)
20:26:07  OpenJ9   - d18a29d0c
20:26:07  OMR      - 333650df1
20:26:07  JCL      - ac21c1a315 based on jdk-19.0.2+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=%2Ftest%2Ffunctional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-mac-aarch64-openj9%2F27%2Fibm-semeru-open-testimage_aarch64_mac_JDK19U_2023-01-21-17-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-mac-aarch64-openj9%2F27%2Fibm-semeru-open-jdk_aarch64_mac_JDK19U_2023-01-21-17-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-mac-aarch64-openj9%2F27%2Fibm-semeru-open-debugimage_aarch64_mac_JDK19U_2023-01-21-17-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-mac-aarch64-openj9%2F27%2Fibm-semeru-open-jre_aarch64_mac_JDK19U_2023-01-21-17-00.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&JDK_VERSION=19&USER_CREDENTIALS_ID=&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Ftemurin-build&JDK_REPO=&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=ibm&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&TRSS_URL=&BUILD_LIST=functional%2FbuildAndPackage&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=1&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-01-22T01:26:31.240Z] variation: NoOptions
[2023-01-22T01:26:31.240Z] JVM_OPTIONS:  

[2023-01-22T01:26:32.741Z] FAILED: isCertNrMatch
[2023-01-22T01:26:32.741Z] java.lang.AssertionError: Failed to match CA certs number. expected [138] but found [139]
[2023-01-22T01:26:32.741Z] 	at org.testng.Assert.fail(Assert.java:96)
[2023-01-22T01:26:32.741Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2023-01-22T01:26:32.741Z] 	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
[2023-01-22T01:26:32.741Z] 	at org.testng.Assert.assertEquals(Assert.java:118)
[2023-01-22T01:26:32.741Z] 	at org.testng.Assert.assertEquals(Assert.java:652)
[2023-01-22T01:26:32.741Z] 	at net.adoptium.test.VerifyCACertsTest.isCertNrMatch(VerifyCACertsTest.java:78)
[2023-01-22T01:26:32.741Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-01-22T01:26:32.741Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-01-22T01:26:32.741Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2023-01-22T01:26:32.741Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2023-01-22T01:26:32.741Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2023-01-22T01:26:32.741Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2023-01-22T01:26:32.741Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-01-22T01:26:32.741Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2023-01-22T01:26:32.741Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2023-01-22T01:26:32.741Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2023-01-22T01:26:32.741Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2023-01-22T01:26:32.741Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2023-01-22T01:26:32.741Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-01-22T01:26:32.741Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2023-01-22T01:26:32.741Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2023-01-22T01:26:32.741Z] 
[2023-01-22T01:26:32.741Z] 
[2023-01-22T01:26:32.741Z] ===============================================
[2023-01-22T01:26:32.741Z]     CommonFeatureTests
[2023-01-22T01:26:32.741Z]     Tests run: 4, Failures: 1, Skips: 0
[2023-01-22T01:26:32.741Z] ===============================================
[2023-01-22T01:26:32.741Z] 
[2023-01-22T01:26:32.741Z] [CudaEnabledTest] [INFO] Starting test to see if CUDA functionality is enabled in this build.
[2023-01-22T01:26:32.741Z] [CudaEnabledTest] [INFO] Finding a list of all j9prt files in this build.
[2023-01-22T01:26:32.741Z] [CudaEnabledTest] [INFO] j9prt file identified: /Users/jenkins/workspace/build-scripts/jobs/jdk19u/jdk19u-mac-aarch64-openj9_SmokeTests/openjdkbinary/j2sdk-image/Contents/Home/bin/../lib/default/libj9prt29.dylib
[2023-01-22T01:26:32.741Z] [CudaEnabledTest] [INFO] Scanning each j9prt file found to see if it indicates CUDA enablement.
[2023-01-22T01:26:33.113Z] [CudaEnabledTest] [INFO] CUDA-enabled indicator string 'cudart' was not found within this j9prt file: /Users/jenkins/workspace/build-scripts/jobs/jdk19u/jdk19u-mac-aarch64-openj9_SmokeTests/openjdkbinary/j2sdk-image/Contents/Home/bin/../lib/default/libj9prt29.dylib
[2023-01-22T01:26:33.113Z] [CudaEnabledTest] [INFO] j9prt file scanning complete. Assessing results.
[2023-01-22T01:26:33.113Z] [CudaEnabledTest] [INFO] Test complete.
[2023-01-22T01:26:33.113Z] PASSED: testIfCudaIsEnabled
[2023-01-22T01:26:33.113Z] 
[2023-01-22T01:26:33.113Z] ===============================================
[2023-01-22T01:26:33.113Z]     OpenJ9FeatureTests
[2023-01-22T01:26:33.113Z]     Tests run: 1, Failures: 0, Skips: 0
[2023-01-22T01:26:33.113Z] ===============================================
[2023-01-22T01:26:33.113Z] 
[2023-01-22T01:26:33.113Z] 
[2023-01-22T01:26:33.113Z] ===============================================
[2023-01-22T01:26:33.113Z] BuildAndPackagingTests
[2023-01-22T01:26:33.113Z] Total tests run: 5, Failures: 1, Skips: 0
[2023-01-22T01:26:33.113Z] ===============================================
[2023-01-22T01:26:33.113Z] 
[2023-01-22T01:26:33.113Z] -----------------------------------
[2023-01-22T01:26:33.113Z] Adopt_J9_FeatureTests_0_FAILED
```

Last pass
```
00:17:09  openjdk version "19.0.1-beta" 2022-10-18
00:17:09  IBM Semeru Runtime Open Edition 19.0.1+10-202301180034 (build 19.0.1-beta+10-202301180034)
00:17:09  Eclipse OpenJ9 VM 19.0.1+10-202301180034 (build master-04ee39006, JRE 19 Mac OS X aarch64-64-Bit 20230117_24 (JIT enabled, AOT enabled)
00:17:09  OpenJ9   - 04ee39006
00:17:09  OMR      - 333650df1
00:17:09  JCL      - 40656c4641 based on jdk-19.0.1+10)
```
First failure
```
20:45:16  openjdk version "19.0.1-beta" 2022-10-18
20:45:16  IBM Semeru Runtime Open Edition 19.0.1+10-202301190126 (build 19.0.1-beta+10-202301190126)
20:45:16  Eclipse OpenJ9 VM 19.0.1+10-202301190126 (build master-62c6b5b52, JRE 19 Mac OS X aarch64-64-Bit 20230118_25 (JIT enabled, AOT enabled)
20:45:16  OpenJ9   - 62c6b5b52
20:45:16  OMR      - 333650df1
20:45:16  JCL      - 40656c4641 based on jdk-19.0.1+10)
```
This seems a test issue.

FYI @llxia

**Comment by JasonFengJ9** [comment]
[JDK11 0.36 build](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/159/console)
```
00:41:23  java version "11.0.18" 2023-01-17
00:41:23  IBM Semeru Runtime Certified Edition 11.0.18.0-rc1 (build 11.0.18+10)
00:41:23  Eclipse OpenJ9 VM 11.0.18.0-rc1 (build v0.36.0-release-e68fb241f, JRE 11 Linux aarch64-64-Bit Compressed References 20230120_224 (JIT enabled, AOT enabled)
00:41:23  OpenJ9   - e68fb241f
00:41:23  OMR      - f491bbf6f
00:41:23  JCL      - d19b1e858d based on jdk-11.0.18+10)

[2023-01-20T05:42:26.278Z] variation: NoOptions
[2023-01-20T05:42:26.278Z] JVM_OPTIONS:  

[2023-01-20T05:42:29.988Z] FAILED: isCertNrMatch
[2023-01-20T05:42:29.988Z] java.lang.AssertionError: Failed to match CA certs number. expected [138] but found [139]
[2023-01-20T05:42:29.988Z] 	at org.testng.Assert.fail(Assert.java:96)
[2023-01-20T05:42:29.988Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2023-01-20T05:42:29.988Z] 	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
[2023-01-20T05:42:29.988Z] 	at org.testng.Assert.assertEquals(Assert.java:118)
[2023-01-20T05:42:29.988Z] 	at org.testng.Assert.assertEquals(Assert.java:652)
[2023-01-20T05:42:29.988Z] 	at net.adoptium.test.VerifyCACertsTest.isCertNrMatch(VerifyCACertsTest.java:78)
[2023-01-20T05:42:29.988Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-20T05:42:29.988Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-20T05:42:29.988Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-20T05:42:29.988Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-01-20T05:42:29.988Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2023-01-20T05:42:29.988Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2023-01-20T05:42:29.988Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2023-01-20T05:42:29.988Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2023-01-20T05:42:29.988Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-01-20T05:42:29.988Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2023-01-20T05:42:29.988Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2023-01-20T05:42:29.988Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2023-01-20T05:42:29.988Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2023-01-20T05:42:29.988Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2023-01-20T05:42:29.988Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-01-20T05:42:29.988Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2023-01-20T05:42:29.988Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2023-01-20T05:42:29.988Z] 
[2023-01-20T05:42:29.988Z] 
[2023-01-20T05:42:29.988Z] ===============================================
[2023-01-20T05:42:29.988Z]     CommonFeatureTests
[2023-01-20T05:42:29.988Z]     Tests run: 4, Failures: 1, Skips: 0
[2023-01-20T05:42:29.988Z] ===============================================
[2023-01-20T05:42:29.988Z] 
[2023-01-20T05:42:29.988Z] [CudaEnabledTest] [INFO] Starting test to see if CUDA functionality is enabled in this build.
[2023-01-20T05:42:29.988Z] [CudaEnabledTest] [INFO] Finding a list of all j9prt files in this build.
[2023-01-20T05:42:29.988Z] [CudaEnabledTest] [INFO] j9prt file identified: /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so
[2023-01-20T05:42:29.988Z] [CudaEnabledTest] [INFO] Scanning each j9prt file found to see if it indicates CUDA enablement.
[2023-01-20T05:42:30.455Z] [CudaEnabledTest] [INFO] CUDA-enabled indicator string 'cudart' was not found within this j9prt file: /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so
[2023-01-20T05:42:30.455Z] [CudaEnabledTest] [INFO] j9prt file scanning complete. Assessing results.
[2023-01-20T05:42:30.455Z] [CudaEnabledTest] [INFO] Test complete.
[2023-01-20T05:42:30.455Z] PASSED: testIfCudaIsEnabled
[2023-01-20T05:42:30.455Z] 
[2023-01-20T05:42:30.455Z] ===============================================
[2023-01-20T05:42:30.455Z]     OpenJ9FeatureTests
[2023-01-20T05:42:30.455Z]     Tests run: 1, Failures: 0, Skips: 0
[2023-01-20T05:42:30.455Z] ===============================================
[2023-01-20T05:42:30.455Z] 
[2023-01-20T05:42:30.455Z] 
[2023-01-20T05:42:30.455Z] ===============================================
[2023-01-20T05:42:30.455Z] BuildAndPackagingTests
[2023-01-20T05:42:30.455Z] Total tests run: 5, Failures: 1, Skips: 0
[2023-01-20T05:42:30.455Z] ===============================================
[2023-01-20T05:42:30.455Z] 
[2023-01-20T05:42:30.929Z] -----------------------------------
[2023-01-20T05:42:30.929Z] Adopt_J9_FeatureTests_0_FAILED
```

**Comment by smlambert** [comment]
Related: https://github.com/adoptium/temurin-build/issues/3212 / https://github.com/adoptium/temurin-build/pull/3213

**Comment by llxia** [comment]
Thanks @smlambert . I launched [internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30612/) with the latest Adoptium repo.

**Comment by llxia** [comment]
https://github.com/adoptium/temurin-build/pull/3213 is not in https://github.com/ibmruntimes/temurin-build. @AdamBrousseau could you take a look? Thanks

**Comment by AdamBrousseau** [comment]
Our branch for releasing was a few changes behind but I had cherry-picked the certs change. I didn't realize there was a smoke test for it. Cherry-picked the [change](https://github.com/adoptium/temurin-build/pull/3213/commits/c594e61b24a90419bdd418a018d8b7d6756153ef) to our branch. I think this can be closed.
