### ISSUE TITLE
jdk_container_0_FAILED jdk/internal/platform/docker/TestUseContainerSupport.java 'TEST PASSED!!!' missing from stdout/stderr

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16602]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_dev.openjdk_aarch64_linux/5/)(`ub18-aarch64-1`):
```
java version "17.0.6" 2023-01-17
IBM Semeru Runtime Certified Edition 17.0.6.0-rc1 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0-rc1 (build v0.36.0-release-e68fb241f, JRE 17 Linux aarch64-64-Bit Compressed References 20230117_316 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - e248569a781 based on jdk-17.0.6+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F316%2Fibm-semeru-certified-testimage_aarch64_linux_17.0.6.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F316%2Fibm-semeru-certified-jdk_aarch64_linux_17.0.6.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F316%2Fibm-semeru-certified-debugimage_aarch64_linux_17.0.6.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F316%2Fibm-semeru-certified-jre_aarch64_linux_17.0.6.0-rc1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-01-20T06:19:36.747Z] variation: NoOptions
[2023-01-20T06:19:36.747Z] JVM_OPTIONS:  

[2023-01-20T06:22:27.986Z] TEST: jdk/internal/platform/docker/TestUseContainerSupport.java

[2023-01-20T06:22:28.045Z]  stderr: []
[2023-01-20T06:22:28.045Z]  exitValue = 0
[2023-01-20T06:22:28.045Z] 
[2023-01-20T06:22:28.045Z] java.lang.RuntimeException: 'TEST PASSED!!!' missing from stdout/stderr 
[2023-01-20T06:22:28.045Z] 
[2023-01-20T06:22:28.045Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
[2023-01-20T06:22:28.045Z] 	at TestUseContainerSupport.testUseContainerSupport(TestUseContainerSupport.java:71)
[2023-01-20T06:22:28.045Z] 	at TestUseContainerSupport.main(TestUseContainerSupport.java:51)
[2023-01-20T06:22:28.045Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-20T06:22:28.045Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-01-20T06:22:28.045Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-20T06:22:28.045Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-01-20T06:22:28.045Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-01-20T06:22:28.045Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-01-20T06:22:28.045Z] 
[2023-01-20T06:22:28.045Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

[2023-01-20T06:22:47.656Z] jdk_container_0_FAILED
```
Similar issue
* https://github.com/eclipse-openj9/openj9/issues/16461

**Comment by JasonFengJ9** [comment]
[JDK8 aarch64_linux/ 0.36](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_dev.openjdk_aarch64_linux/10/)
```
[2023-01-23T17:54:23.906Z] STDERR:
[2023-01-23T17:54:23.906Z]  stdout: [-XX:-UseContainerSupport, but got Metrics.systemMetrics() == non-null
[2023-01-23T17:54:23.906Z] TEST FAILED!!!
[2023-01-23T17:54:23.906Z] ];
[2023-01-23T17:54:23.906Z]  stderr: []
[2023-01-23T17:54:23.907Z]  exitValue = 0
[2023-01-23T17:54:23.907Z] 
[2023-01-23T17:54:23.907Z] java.lang.RuntimeException: 'TEST PASSED!!!' missing from stdout/stderr 
[2023-01-23T17:54:23.907Z] 
[2023-01-23T17:54:23.907Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:150)
[2023-01-23T17:54:23.907Z] 	at TestUseContainerSupport.testUseContainerSupport(TestUseContainerSupport.java:68)
[2023-01-23T17:54:23.907Z] 	at TestUseContainerSupport.main(TestUseContainerSupport.java:49)
[2023-01-23T17:54:23.907Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-23T17:54:23.907Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-01-23T17:54:23.907Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-23T17:54:23.907Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-01-23T17:54:23.907Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2023-01-23T17:54:23.907Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-01-23T17:54:23.907Z] 
[2023-01-23T17:54:23.907Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
```
