### ISSUE TITLE
jdk19 Jep424Tests_testLinkerFfi_UpCall_0 test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH expected [true] but found [false]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16619]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_x86-64_windows_Nightly_testList_1/101
Jep424Tests_testLinkerFfi_UpCall_0
```
02:22:13  FAILED: test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH
02:22:13  java.lang.AssertionError: expected [true] but found [false]
02:22:13  	at org.testng.Assert.fail(Assert.java:96)
02:22:13  	at org.testng.Assert.failNotEquals(Assert.java:776)
02:22:13  	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
02:22:13  	at org.testng.Assert.assertEquals(Assert.java:118)
02:22:13  	at org.testng.Assert.assertEquals(Assert.java:568)
02:22:13  	at org.testng.Assert.assertEquals(Assert.java:578)
02:22:13  	at org.openj9.test.jep424.upcall.UpcallMHWithStructTests.test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH(UpcallMHWithStructTests.java:271)

02:22:13  FAILED: test_addBoolAndBoolsFromStructWithNestedBoolArray_reverseOrderByUpcallMH
02:22:13  java.lang.AssertionError: expected [true] but found [false]
02:22:13  	at org.testng.Assert.fail(Assert.java:96)
02:22:13  	at org.testng.Assert.failNotEquals(Assert.java:776)
02:22:13  	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
02:22:13  	at org.testng.Assert.assertEquals(Assert.java:118)
02:22:13  	at org.testng.Assert.assertEquals(Assert.java:568)
02:22:13  	at org.testng.Assert.assertEquals(Assert.java:578)
02:22:13  	at org.openj9.test.jep424.upcall.UpcallMHWithStructTests.test_addBoolAndBoolsFromStructWithNestedBoolArray_reverseOrderByUpcallMH(UpcallMHWithStructTests.java:294)

```

**Comment by pshipton** [comment]
@tajila @ChengJin01 fyi

**Comment by ChengJin01** [comment]
Launched Grinders (x50) at https://openj9-jenkins.osuosl.org/job/Grinder/1901/consoleText to see what happened to the test failures.

**Comment by ChengJin01** [comment]
It seems the failure can be reproduced in the Grinders above. So I manually verify the test locally with a couple of printing messages in the java & native test code as follows:

[1] PASSED
```
$ ../jdk19_openj9_ffi_cmk_v09/bin/java  --enable-preview -Djava.library.path=../native-test-libs  --enable-native-access=ALL-UNNAMED -Dforeign.restricted=permit UpcallMHWithStructTests

(UpcallMHWithStructTests.java)
test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: structSegmt.elem0 = false
test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: structSegmt.elem1 = true
test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: structSegmt.elem2 = false

(upcall.c)
addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: arg2.elem1[0] = 0 (false)
addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: arg2.elem1[1] = 1 (true)
addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: arg2.elem2 = 0 (false)

(UpcallMethodHandles.java)
addBoolAndBoolsFromStructWithNestedBoolArray: nestedBoolArrayElem1 = true  <------ wrong
addBoolAndBoolsFromStructWithNestedBoolArray: nestedBoolArrayElem2 = true
addBoolAndBoolsFromStructWithNestedBoolArray: structElem2 = true  <------ wrong

test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: result = true
```

[2]FAILED
```
$ ../jdk19_openj9_ffi_cmk_v09/bin/java  --enable-preview -Djava.library.path=../native-test-libs  --enable-native-access=ALL-UNNAMED -Dforeign.restricted=permit UpcallMHWithStructTests

(UpcallMHWithStructTests.java)
test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: structSegmt.elem0 = false
test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: structSegmt.elem1 = true
test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: structSegmt.elem2 = false

(upcall.c)
addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: arg2.elem1[0] = 0 (false)
addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: arg2.elem1[1] = 1
addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: arg2.elem2 = 0  (false)

(UpcallMethodHandles.java)
addBoolAndBoolsFromStructWithNestedBoolArray: nestedBoolArrayElem1 = false
addBoolAndBoolsFromStructWithNestedBoolArray: nestedBoolArrayElem2 = true
addBoolAndBoolsFromStructWithNestedBoolArray: structElem2 = true <------ wrong

test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH: result = false
```
which means 
1) there is no problem with ffi_call() during the downcall given the values in the native code  `addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH` were correct as compared to the passed-in arguments in `test_addBoolAndBoolsFromStructWithNestedBoolArrayByUpcallMH`.
2) the elements of the nested bool array were always wrong in the upcall method, whether the test passed or not, in which case something wrong happened between the thunk and the dispatcher prior to the upcall.

I will need to debug in the dispatcher to see how the struct value was messed up when returning from `getArgPointer()`.

**Comment by ChengJin01** [comment]
The windbg on Windows shows the test failure was caused by the unexpected struct padding in the test at https://github.com/eclipse-openj9/openj9/blob/b975e8202c2d9d7b709bff8b9140cd98c836f5a3/test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMHWithStructTests.java#L256
[1] with the padding
https://github.com/eclipse-openj9/openj9/blob/9e897d30bbc6593a8b9e682ea997844ea0e7d65a/runtime/vm/UpcallVMHelpers.cpp#L488
```
0:008> dd 4EAEB7EE98 <------ the address of offset
0000004e`aeb7ee98  aeb7eef0 (wrong)
                                  0000004e 00016700 00000000
0000004e`aeb7eea8  6b7124dc 00007ffc 9e6b04e8 00000205
0000004e`aeb7eeb8  4ed465bd 00007ffc 63b9a2a0 00007ffc
```
[2] without the padding
```
0:008> dd C3A747EED8 <------ the address of offset
000000c3`a747eed8  81000100 (correct, 00 for the 1st byte, 01 for the 2nd byte, 00 for the 3rd byte) 
                                  00007ffc f83c0b40 000001d0
000000c3`a747eee8  00000000 00000000 58b80e90 ffffff3c
000000c3`a747eef8  6b7124dc 00007ffc f83c03d8 000001d0
```
As requested by JIT at https://github.com/eclipse-openj9/openj9/pull/15310#discussion_r975307617, all struct padding need to be removed to ensure the correct argument arrangement in upcall on Windows & zLinux. So they are two test case not yet updated accordingly. Will double-check other test cases in upcall to see whether there are still test cases that need to remove the struct padding on Windows & zLinux.
