### ISSUE TITLE
jdk_text_1_FAILED java/text/Collator/Regression.java java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16620]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/93/)(`win16x64rt2-3`):
```
java version "17.0.6" 2023-01-17
IBM Semeru Runtime Certified Edition 17.0.6+10 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6+10 (build master-d18a29d0c, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20230117_316 (JIT enabled, AOT enabled)
OpenJ9   - d18a29d0c
OMR      - 333650df1
JCL      - 83540322d3 based on jdk-17.0.6+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_text_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F316%2Fibm-semeru-certified-jre_x64_windows_JDK17U_2023-01-21-15-31.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F316%2Fibm-semeru-certified-debugimage_x64_windows_JDK17U_2023-01-21-15-31.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F316%2Fibm-semeru-certified-jdk_x64_windows_JDK17U_2023-01-21-15-31.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F316%2Fibm-semeru-certified-testimage_x64_windows_JDK17U_2023-01-21-15-31.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-01-21T22:25:52.840Z] variation: Mode650
[2023-01-21T22:25:53.249Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-01-21T22:27:41.683Z] TEST: java/text/Collator/Regression.java

[2023-01-21T22:27:41.684Z]   Test4171974 Passed
[2023-01-21T22:27:41.684Z]   Test4663220java.lang.IncompatibleClassChangeError
[2023-01-21T22:27:41.684Z] 	at java.base/jdk.internal.icu.impl.ReplaceableUCharacterIterator.previous(ReplaceableUCharacterIterator.java:150)
[2023-01-21T22:27:41.684Z] 	at java.base/jdk.internal.icu.text.UCharacterIterator.previousCodePoint(UCharacterIterator.java:187)
[2023-01-21T22:27:41.684Z] 	at java.base/jdk.internal.icu.text.UCharacterIterator.moveCodePointIndex(UCharacterIterator.java:298)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.icu.text.NormalizerBase.nextNormalize(NormalizerBase.java:752)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.icu.text.NormalizerBase.next(NormalizerBase.java:522)
[2023-01-21T22:27:41.685Z] 	at java.base/java.text.CollationElementIterator.next(CollationElementIterator.java:217)
[2023-01-21T22:27:41.685Z] 	at Regression.Test4663220(Regression.java:868)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-21T22:27:41.685Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-01-21T22:27:41.685Z] 	at IntlTest.run(IntlTest.java:127)
[2023-01-21T22:27:41.685Z] 	at Regression.main(Regression.java:54)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-21T22:27:41.685Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-01-21T22:27:41.685Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-01-21T22:27:41.685Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-01-21T22:27:41.685Z]  {
[2023-01-21T22:27:41.685Z]     Uncaught exception thrown in test method Test4663220
[2023-01-21T22:27:41.685Z] STDERR:
[2023-01-21T22:27:41.685Z] java.lang.RuntimeException: Uncaught exception thrown in test method Test4663220
[2023-01-21T22:27:41.685Z] 	at IntlTest.errImpl(IntlTest.java:204)
[2023-01-21T22:27:41.685Z] 	at IntlTest.errln(IntlTest.java:191)
[2023-01-21T22:27:41.685Z] 	at IntlTest.run(IntlTest.java:133)
[2023-01-21T22:27:41.685Z] 	at Regression.main(Regression.java:54)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-01-21T22:27:41.685Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-01-21T22:27:41.685Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-01-21T22:27:41.685Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-01-21T22:27:41.685Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-01-21T22:27:41.685Z] 
[2023-01-21T22:27:41.685Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2023-01-21T22:27:41.685Z] JavaTest Message: shutting down test
[2023-01-21T22:27:41.685Z] 
[2023-01-21T22:27:41.685Z] 
[2023-01-21T22:27:41.685Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Uncaught exception thrown in test method Test4663220
[2023-01-21T22:27:41.685Z] --------------------------------------------------
[2023-01-21T22:31:38.586Z] Test results: passed: 183; failed: 1
[2023-01-21T22:31:58.940Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16743219513455\jdk_text_1\report\html\report.html
[2023-01-21T22:31:58.940Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16743219513455\jdk_text_1\work
[2023-01-21T22:31:58.940Z] Error: Some tests failed or other problems occurred.
[2023-01-21T22:31:58.940Z] -----------------------------------
[2023-01-21T22:31:58.940Z] jdk_text_1_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30746/)

**Comment by pshipton** [comment]
grinder passed
