### ISSUE TITLE
Scripts not permitted to use staticMethod org.tap4j.consumer.TapConsumerFactory makeTap13YamlConsumer

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16649]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly/403
```
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.tap4j.consumer.TapConsumerFactory makeTap13YamlConsumer
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectStaticMethod(StaticWhitelist.java:243)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onStaticCall(SandboxInterceptor.java:189)
	at org.kohsuke.groovy.sandbox.impl.Checker$2.call(Checker.java:192)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedStaticCall(Checker.java:196)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:103)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at Script1.addFailedTestsGrinderLink(Script1.groovy:1023)
	at Script1.run_parallel_tests(Script1.groovy:1172)
```
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/388/console
```
02:23:26  Exception: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.tap4j.consumer.TapConsumerFactory makeTap13YamlConsumer
```

@AdamBrousseau seeing multiple failures like above. A child job failed a test, it seems jenkins needs an additional permission to handle it now?
@llxia fyi

**Comment by AdamBrousseau** [comment]
Approved

**Comment by pshipton** [comment]
This just exposed the next problem
```
15:12:28  Exception: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method org.tap4j.model.TapElement getDiagnostic
```

**Comment by AdamBrousseau** [comment]
Should be 1 more

**Comment by pshipton** [comment]
`17:24:35  Exception: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods toUnique java.lang.Object[]`

**Comment by AdamBrousseau** [comment]
Done
