### ISSUE TITLE
jdk20 OpenJDK jdk/internal/misc/ThreadFlock/WithScopedValue UnsatisfiedLinkError Thread.scopedValueCache

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16657]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_OpenJDK20/1/
All platforms, not platform specific.
jdk_lang
jdk/internal/misc/ThreadFlock/WithScopedValue.java
```
10:30:29  STDOUT:
10:30:29  test WithScopedValue.testInheritsScopedValue(java.util.concurrent.Executors$DefaultThreadFactory@1442703a): failure
10:30:29  java.lang.UnsatisfiedLinkError: java/lang/Thread.scopedValueCache()[Ljava/lang/Object;
10:30:29  	at java.base/java.lang.Access.scopedValueCache(Access.java:455)
10:30:29  	at jdk.incubator.concurrent/jdk.incubator.concurrent.ScopedValue.scopedValueCache(ScopedValue.java:645)
10:30:29  	at jdk.incubator.concurrent/jdk.incubator.concurrent.ScopedValue$Cache.invalidate(ScopedValue.java:829)
10:30:29  	at jdk.incubator.concurrent/jdk.incubator.concurrent.ScopedValue$Carrier.call(ScopedValue.java:367)
10:30:29  	at jdk.incubator.concurrent/jdk.incubator.concurrent.ScopedValue.where(ScopedValue.java:494)
10:30:29  	at WithScopedValue.testInheritsScopedValue(WithScopedValue.java:63)
```

**Comment by pshipton** [comment]
@tajila fyi
