### ISSUE TITLE
TestFileLocking_FAILED IOException: The file access permissions do not allow the specified action

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16692]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.functional_ppc64_aix_testList_2/395/)(`paix819`):
```
openjdk version "1.8.0_372-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_372-beta-202302072336-b01)
Eclipse OpenJ9 VM (build master-34eacb423, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20230207_577 (JIT enabled, AOT enabled)
OpenJ9   - 34eacb423
OMR      - 706ea4ac5
JCL      - dcf84eb97 based on jdk8u372-b01)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=TestFileLocking_SE80_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_extended.functional_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=3&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F577%2Fibm-semeru-open-testimage_ppc64_aix_JDK8U_2023-02-07-23-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F577%2Fibm-semeru-open-jdk_ppc64_aix_JDK8U_2023-02-07-23-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F577%2Fibm-semeru-open-debugimage_ppc64_aix_JDK8U_2023-02-07-23-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F577%2Fibm-semeru-open-jre_ppc64_aix_JDK8U_2023-02-07-23-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=448&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-02-08T01:29:07.779Z] variation: NoOptions
[2023-02-08T01:29:07.779Z] JVM_OPTIONS:  

[2023-02-08T01:29:09.405Z] java.io.IOException: The file access permissions do not allow the specified action.
[2023-02-08T01:29:09.405Z] 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[2023-02-08T01:29:09.405Z] 	at java.io.File.createNewFile(File.java:1023)
[2023-02-08T01:29:09.405Z] 	at org.openj9.test.fileLock.TestFileLocking.setUp(TestFileLocking.java:87)
[2023-02-08T01:29:09.405Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-02-08T01:29:09.406Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-02-08T01:29:09.406Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-08T01:29:09.406Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-02-08T01:29:09.406Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2023-02-08T01:29:09.406Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2023-02-08T01:29:09.406Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2023-02-08T01:29:09.406Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2023-02-08T01:29:09.406Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2023-02-08T01:29:09.406Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-02-08T01:29:09.406Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2023-02-08T01:29:09.406Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2023-02-08T01:29:09.406Z] [TestFileLocking] [ERROR] error creating lockfile /tmp/lockDir/lockFile
[2023-02-08T01:29:09.406Z] FAILED CONFIGURATION: @BeforeMethod setUp(public void org.openj9.test.fileLock.TestFileLocking.testCB_CB())

[2023-02-08T01:29:09.416Z] ===============================================
[2023-02-08T01:29:09.416Z]     TestFileLocking
[2023-02-08T01:29:09.416Z]     Tests run: 17, Failures: 0, Skips: 17
[2023-02-08T01:29:09.416Z]     Configuration Failures: 1, Skips: 33
[2023-02-08T01:29:09.416Z] ===============================================
[2023-02-08T01:29:09.416Z] 
[2023-02-08T01:29:09.416Z] 
[2023-02-08T01:29:09.416Z] ===============================================
[2023-02-08T01:29:09.416Z] GeneralTest suite
[2023-02-08T01:29:09.416Z] Total tests run: 17, Failures: 0, Skips: 17
[2023-02-08T01:29:09.416Z] Configuration Failures: 1, Skips: 33
[2023-02-08T01:29:09.416Z] ===============================================
[2023-02-08T01:29:09.416Z] 
[2023-02-08T01:29:10.262Z] -----------------------------------
[2023-02-08T01:29:10.262Z] TestFileLocking_SE80_0_FAILED
```

Also seen on [ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_2/410/)
[JDK19](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.functional_ppc64le_linux_testList_1/94/)

**Comment by pshipton** [comment]
Could this be a machine problem? It seem unlikely anything changed in the JVM to cause this.

**Comment by JasonFengJ9** [comment]
[30x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30963/console)
Failures at [paix816](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_5/539/), [paix817](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_6/513/)

Created [an infra issue](https://github.ibm.com/runtimes/infrastructure/issues/7721)

**Comment by pshipton** [comment]
Does it work on the last release? There was an update from jdk8u362-b09 to jdk8u372-b01, although this happened on Jan 31. Has it been failing since then?

https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/jdk8u362-b09...jdk8u372-b01

**Comment by JasonFengJ9** [comment]
A similar failure occurred at [JDK19](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.functional_ppc64le_linux_testList_1/94/). It seems a machine issue instead of a cross Java level update problem.
From the test history, JDK8 passed on [Feb. 4th](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.functional_ppc64_aix_testList_2/393/).

**Comment by pshipton** [comment]
Closing this then.
