### ISSUE TITLE
CryptoTests cryptotest/tests/SignatureTests.java timeout in java.math.BigInteger.implSquareToLen

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16711]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/394/
CryptoTests_0

timeout, no diagnostic files.
```
TEST: cryptotest/tests/SignatureTests.java

133)	SunEC: 	SHA1withECDSA~SHA1withECDSA	 (Signature)

"MainThread" prio=5 Id=22 RUNNABLE
	at java.base@17.0.6-internal/java.math.BigInteger.implSquareToLen(BigInteger.java:2212)
	at java.base@17.0.6-internal/java.math.BigInteger.squareToLen(BigInteger.java:2124)
	at java.base@17.0.6-internal/java.math.BigInteger.implMontgomerySquare(BigInteger.java:2866)
	at java.base@17.0.6-internal/java.math.BigInteger.montgomerySquare(BigInteger.java:2823)
	at java.base@17.0.6-internal/java.math.BigInteger.oddModPow(BigInteger.java:3093)
	at java.base@17.0.6-internal/java.math.BigInteger.modPow(BigInteger.java:2754)
	at java.base@17.0.6-internal/java.math.BigInteger.passesMillerRabin(BigInteger.java:1122)
	at java.base@17.0.6-internal/java.math.BigInteger.primeToCertainty(BigInteger.java:978)
	at java.base@17.0.6-internal/java.math.BitSieve.retrieve(BitSieve.java:203)
	at java.base@17.0.6-internal/java.math.BigInteger.largePrime(BigInteger.java:847)
	at java.base@17.0.6-internal/java.math.BigInteger.probablePrime(BigInteger.java:785)
	at java.base@17.0.6-internal/sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:173)
	at java.base@17.0.6-internal/java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
	at java.base@17.0.6-internal/java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:495)
	at app//cryptotest.utils.KeysNaiveGenerator.getRsaKeyPair(KeysNaiveGenerator.java:165)
	at app//cryptotest.utils.KeysNaiveGenerator.getRsaPrivateKey(KeysNaiveGenerator.java:169)
	at app//cryptotest.tests.SignatureTests.checkAlgorithm(SignatureTests.java:85)
	at app//cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
	at app//cryptotest.tests.SignatureTests.main(SignatureTests.java:68)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/415 - [ub20-390-3](https://openj9-jenkins.osuosl.org/computer/ub20-390-3)
```
cryptotest/tests/SignatureTests.java

72)	SunRsaSign: 	SHA384withRSA~OID.1.2.840.113549.1.1.12	 (Signature)

"MainThread" prio=5 Id=22 RUNNABLE
	at java.base@17.0.6-internal/java.math.BigInteger.implSquareToLen(BigInteger.java:2202)
	at java.base@17.0.6-internal/java.math.BigInteger.squareToLen(BigInteger.java:2124)
	at java.base@17.0.6-internal/java.math.BigInteger.square(BigInteger.java:2093)
	at java.base@17.0.6-internal/java.math.BigInteger.square(BigInteger.java:2076)
	at java.base@17.0.6-internal/java.math.BigInteger.lucasLehmerSequence(BigInteger.java:1070)
	at java.base@17.0.6-internal/java.math.BigInteger.passesLucasLehmer(BigInteger.java:998)
	at java.base@17.0.6-internal/java.math.BigInteger.primeToCertainty(BigInteger.java:978)
	at java.base@17.0.6-internal/java.math.BitSieve.retrieve(BitSieve.java:203)
	at java.base@17.0.6-internal/java.math.BigInteger.largePrime(BigInteger.java:847)
	at java.base@17.0.6-internal/java.math.BigInteger.probablePrime(BigInteger.java:785)
	at java.base@17.0.6-internal/sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:187)
	at java.base@17.0.6-internal/java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:721)
	at java.base@17.0.6-internal/java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:495)
	at app//cryptotest.utils.KeysNaiveGenerator.getRsaKeyPair(KeysNaiveGenerator.java:165)
	at app//cryptotest.utils.KeysNaiveGenerator.getRsaPrivateKey(KeysNaiveGenerator.java:169)
	at app//cryptotest.tests.SignatureTests.checkAlgorithm(SignatureTests.java:85)
	at app//cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
	at app//cryptotest.tests.SignatureTests.main(SignatureTests.java:68)
```

**Comment by pshipton** [comment]
@0xdaryl it seems OpenJ9 is too slow to complete this newly added test. I notice jdk17 implSquareToLen() has an @IntrinsicCandidate annotation, while in jdk11 it's @HotSpotIntrinsicCandidate.

@llxia can we increase the timeout setting for this test?
`timeout set to 120000ms`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_aarch64_linux_Nightly_testList_0/99 - [cent8-aarch64-1](https://openj9-jenkins.osuosl.org/computer/cent8-aarch64-1)
CryptoTests_0
cryptotest/tests/SignatureTests.java
```
34)	SUN: 	SHA3-256withDSA~OID.2.16.840.1.101.3.4.3.6	 (Signature)

"MainThread" prio=5 Id=27 RUNNABLE
	at java.base@19.0.2-internal/java.math.BigInteger.implMulAdd(BigInteger.java:3320)
```

**Comment by pshipton** [comment]
cryptotest/CryptoTest.java is also timing out
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_ppc64_aix_Nightly_testList_1/100

**Comment by pshipton** [comment]
The jdk19 timeouts are also happening on Adoptium builds.

**Comment by llxia** [comment]
I can set ` -timeoutFactor:2` (instead of 1). But I am not sure if it is the best way to do it.
https://openj9-jenkins.osuosl.org/job/Grinder/2022/

**Comment by llxia** [comment]
Increase timeout for CryptoTests: https://github.com/adoptium/aqa-tests/pull/4339

**Comment by 0xdaryl** [comment]
> I notice jdk17 implSquareToLen() has an @IntrinsicCandidate annotation, while in jdk11 it's @HotSpotIntrinsicCandidate.

Interesting.  I believe our intrinsics matching code is only looking for the former, not the latter.  But it is the former that might be the issue in this case.  We'll investigate the timeout, but not for 0.38.

**Comment by 0xdaryl** [comment]
@BradleyWood : please investigate the slowdown here.  I moved this to 0.40.

**Comment by BradleyWood** [comment]
> @0xdaryl it seems OpenJ9 is too slow to complete this newly added test. I notice jdk17 implSquareToLen() has an @IntrinsicCandidate annotation, while in jdk11 it's @HotSpotIntrinsicCandidate.

I don't think `implSquareToLen` intrinsic was ever implemented in OpenJ9 on any platform. I think we should open an issue to implement it, and any other unimplemented intrinsics.

**Comment by hzongaro** [comment]
Reassigning to @jmesyou, as he's working on issue #17778.

I'm not sure whether we need both issues, or if #17778 will act as an epic issue with this as a subtask.  I'll leave it for him to decide.

**Comment by hzongaro** [comment]
I'm assuming this won't be ready for the 0.41 code split, so I'll move it out to 0.43.
