### ISSUE TITLE
JDK8 zOS Assertion failed: false && (_rebuildInitWorkForAdd), file: ./ConcurrentGC.cpp, line: 2345

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16743]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=54028407)(`fyrec60f`):
```
Java(TM) SE Runtime Environment (build 8.0.8.0 - pmz6480sr8-20230208_02(SR8))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20230217_46138 (JIT enabled, AOT enabled)
OpenJ9   - da59d84
OMR      - 6214373
IBM      - 68444b7)
JCL - 20230208_01 based on Oracle jdk8u361-b09
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
p> 20230217-21:56:54 Logging java -Xmx1120M -Xms4M -Xdump:system+java:events=user -Xcompressedrefs -Djdk.crypto.KeyAgreement.legacyKDF=true -Djava.io.tmpdir=/home/j9build/tmp/bld_46138_zos_390-64_cr/bld_46138/harmony.5mins/54028407/JLTF-harmony-mode159-CS-20230217-2156 -Dduration=300 -cp /j9vm/ebcdic/javatest/HEAD_382595/test/SVT/stress/jltf/engine/jltf.core/lib/*:/j9tmp/bld_46138_zos_390-64_cr/bld_46138/harmony.5mins/54028407/JLTF-harmony-mode159-CS-20230217-2156/resources:/j9vm/ebcdic/javatest/HEAD_382595/test/SVT/stress/harmony/harmony.support/lib/*:/j9vm/ebcdic/javatest/HEAD_382595/test/SVT/stress/harmony/lib/* -version output to java_version.txt
p> 20230217-21:56:55 JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
p> 20230217-21:56:56 java version "1.8.0_361"
p> 20230217-21:56:56 Java(TM) SE Runtime Environment (build 8.0.8.0 - pmz6480sr8-20230208_02(SR8))
p> 20230217-21:56:56 IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20230217_46138 (JIT disabled, AOT disabled)
p> 20230217-21:56:56 OpenJ9   - da59d84
p> 20230217-21:56:56 OMR      - 6214373
p> 20230217-21:56:56 IBM      - 68444b7)
p> 20230217-21:56:56 JCL - 20230208_01 based on Oracle jdk8u361-b09
p> 20230217-21:56:56 Assertion failed: false && (_rebuildInitWorkForAdd), file: ./ConcurrentGC.cpp, line: 2345
p> 20230217-21:56:56 CEE5207E The signal SIGABRT was received.
p> 20230217-21:56:57 ERROR: Return code of java -version process was 3
p> 20230217-21:56:57 Test FAILED because:
p> 20230217-21:56:57 * Return code of java -version process was 3
p> 20230217-21:56:57 Test failed or upload forced, uploading result directory to Axxon server
Running compression command: jar cvf /tmp/54028407-results0.jar /home/j9build/tmp/bld_46138_zos_390-64_cr/bld_46138/harmony.5mins/54028407/JLTF-harmony-mode159-CS-20230217-2156
Compression was successful.Attempting to upload compressed file.Upload appears to have been successful.p> 20230217-22:02:10 Upload successful - deleting results directory
p> 20230217-22:02:11 Final result is FAIL
```

Also seen [ [zOS S390 64bit Compressed Pointers] 80 JIT_Sanity.Mauve.5mins.Mode159-CS.1](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=54028404), [[zOS S390 64bit Compressed Pointers] 80 Load_Level_2.abbs.5mins.Mode159-CS.2](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=54028426)

FYI @dmitripivkine

**Comment by pshipton** [comment]
The change was https://github.com/eclipse/omr/pull/6891

**Comment by dmitripivkine** [comment]
The problem exists for all platforms and can be reproduced by 
```
/bluebird/builds/bld_46138/sdk/xa6480/jre/bin/java -Xint -Xgcpolicy:gencon -Xgc:concurrentScavenge -Xmx4m -Xms1M -Xcompressedrefs -verbose:gc  -version
```
C-stack:|
```
#7  0x00007f635968b252 in __assert_fail () from /usr/lib64/libc.so.6
#8  0x00007f63529e4dac in MM_ConcurrentGC::recalculateInitWork(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#9  0x00007f63529d72b1 in MM_ConcurrentGCIncrementalUpdate::tuneToHeap(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#10 0x00007f63529ea2de in MM_ConcurrentGC::heapReconfigured(MM_EnvironmentBase*, HeapReconfigReason, MM_MemorySubSpace*, void*, void*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#11 0x00007f635299b6d4 in MM_PhysicalSubArenaVirtualMemorySemiSpace::tearDown(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#12 0x00007f635299b5f2 in MM_PhysicalSubArenaVirtualMemorySemiSpace::kill(MM_EnvironmentBase*) [clone .localalias.27] ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#13 0x00007f635293fb10 in MM_MemorySubSpace::tearDown(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#14 0x00007f6352a0ed81 in MM_MemorySubSpaceSemiSpace::tearDown(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#15 0x00007f635293fb33 in MM_MemorySubSpace::tearDown(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#16 0x00007f6352939632 in MM_MemorySubSpace::kill(MM_EnvironmentBase*) [clone .localalias.35] ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#17 0x00007f63529455ee in MM_MemorySpace::kill(MM_EnvironmentBase*) [clone .localalias.3] ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#18 0x00007f6352946e4d in MM_Configuration::tearDown(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#19 0x00007f6352946ae2 in MM_Configuration::kill(MM_EnvironmentBase*) ()
   from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#20 0x00007f635286e003 in gcCleanupInitializeDefaults () from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#21 0x00007f6352848c3c in J9VMDllMain () from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9gc29.so
#22 0x00007f6353d14a7b in runShutdownStage.constprop.8 () from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9vm29.so
#23 0x00007f6353d157a7 in freeJavaVM () from /bluebird/builds/bld_46138/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9vm29.so
```
The assertion is triggered because of Concurrent Scavenger cycle still be active during Subspace tear Down. Previous behaviour was kill Scavenger earlier and avoid assertion.

**Comment by dmitripivkine** [comment]
There is the fix https://github.com/eclipse/omr/pull/6900

**Comment by dmitripivkine** [comment]
This problem has been fixed
