### ISSUE TITLE
OpenJDK java/util/Locale/LSRDataTest java/util/Locale/LanguageSubtagRegistryTest

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16746]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/424/ - [win2019x64-openj9-2](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-2)
`JCL      - 77e36f9113f based on jdk-17.0.6+10`
openjdk test SHA `94a11484f02` which is jdk-17.0.7+2

jdk_util_0 & jdk_util_1
java/util/Locale/LSRDataTest.java
```
00:16:47  java.lang.RuntimeException: [FAILED: Ranges at index 1 do not match Expected: range=sgn-rib, weight=1.0, Actual: range=lak, weight=1.0]
00:16:47  	at LSRDataTest.checkEquality(LSRDataTest.java:373)
00:16:47  	at LSRDataTest.main(LSRDataTest.java:77)
```

jdk_util_0 & jdk_util_1
java/util/Locale/LanguageSubtagRegistryTest.java
```
23:47:08    Expected size=129
23:47:08      range=aam, weight=1.0
23:47:08      range=aas, weight=1.0
23:47:08      range=adp, weight=1.0
23:47:08      range=dz, weight=1.0
23:47:08      range=aeb, weight=1.0
23:47:08      range=ar-aeb, weight=1.0
23:47:08      range=ajt, weight=1.0
23:47:08      range=ajs, weight=1.0
23:47:08      range=sgn-ajs, weight=1.0
23:47:08      range=aog, weight=1.0
23:47:08      range=myd, weight=1.0
23:47:08      range=aue, weight=1.0
23:47:08      range=ktz, weight=1.0
23:47:08      range=bcg, weight=1.0
23:47:08      range=bgm, weight=1.0
23:47:08      range=bic, weight=1.0
23:47:08      range=bir, weight=1.0
23:47:08      range=bpp, weight=1.0
23:47:08      range=nxu, weight=1.0
23:47:08      range=cey, weight=1.0
23:47:08      range=cnp, weight=1.0
23:47:08      range=zh-cnp, weight=1.0
23:47:08      range=cqu, weight=1.0
23:47:08      range=quh, weight=1.0
23:47:08      range=csp, weight=1.0
23:47:08      range=zh-csp, weight=1.0
23:47:08      range=csx, weight=1.0
23:47:08      range=sgn-csx, weight=1.0
23:47:08      range=dif, weight=1.0
23:47:08      range=dit, weight=1.0
23:47:08      range=dmw, weight=1.0
23:47:08      range=xrq, weight=1.0
23:47:08      range=dsz, weight=1.0
23:47:08      range=sgn-dsz, weight=1.0
23:47:08      range=ehs, weight=1.0
23:47:08      range=sgn-ehs, weight=1.0
23:47:08      range=ema, weight=1.0
23:47:08      range=uok, weight=1.0
23:47:08      range=en-gb-oed, weight=1.0
23:47:08      range=en-gb-oxendict, weight=1.0
23:47:08      range=gti, weight=1.0
23:47:08      range=nyc, weight=1.0
23:47:08      range=iba, weight=1.0
23:47:08      range=snb, weight=1.0
23:47:08      range=blg, weight=1.0
23:47:08      range=jks, weight=1.0
23:47:08      range=sgn-jks, weight=1.0
23:47:08      range=kdz, weight=1.0
23:47:08      range=ncp, weight=1.0
23:47:08      range=kmb, weight=1.0
23:47:08      range=smd, weight=1.0
23:47:08      range=koj, weight=1.0
23:47:08      range=kwv, weight=1.0
23:47:08      range=kru, weight=1.0
23:47:08      range=kxl, weight=1.0
23:47:08      range=ksp, weight=1.0
23:47:08      range=lak, weight=1.0
23:47:08      range=kwq, weight=1.0
23:47:08      range=yam, weight=1.0
23:47:08      range=kxe, weight=1.0
23:47:08      range=tvd, weight=1.0
23:47:08      range=kzk, weight=1.0
23:47:08      range=gli, weight=1.0
23:47:08      range=drr, weight=1.0
23:47:08      range=lii, weight=1.0
23:47:08      range=raq, weight=1.0
23:47:08      range=lmm, weight=1.0
23:47:08      range=rmx, weight=1.0
23:47:08      range=lsb, weight=1.0
23:47:08      range=sgn-lsb, weight=1.0
23:47:08      range=lsc, weight=1.0
23:47:08      range=sgn-lsc, weight=1.0
23:47:08      range=lsn, weight=1.0
23:47:08      range=sgn-lsn, weight=1.0
23:47:08      range=lsv, weight=1.0
23:47:08      range=sgn-lsv, weight=1.0
23:47:08      range=lsw, weight=1.0
23:47:08      range=sgn-lsw, weight=1.0
23:47:08      range=lvi, weight=1.0
23:47:08      range=mtm, weight=1.0
23:47:08      range=ymt, weight=1.0
23:47:08      range=ngv, weight=1.0
23:47:08      range=nnx, weight=1.0
23:47:08      range=nns, weight=1.0
23:47:08      range=nbr, weight=1.0
23:47:08      range=ola, weight=1.0
23:47:08      range=thw, weight=1.0
23:47:08      range=oyb, weight=1.0
23:47:08      range=thx, weight=1.0
23:47:08      range=skk, weight=1.0
23:47:08      range=jeg, weight=1.0
23:47:08      range=pat, weight=1.0
23:47:08      range=kxr, weight=1.0
23:47:08      range=phr, weight=1.0
23:47:08      range=pmu, weight=1.0
23:47:08      range=pnd, weight=1.0
23:47:08      range=pub, weight=1.0
23:47:08      range=puz, weight=1.0
23:47:08      range=rib, weight=1.0
23:47:08      range=sgn-rib, weight=1.0
23:47:08      range=rnb, weight=1.0
23:47:08      range=sgn-rnb, weight=1.0
23:47:08      range=rsn, weight=1.0
23:47:08      range=sgn-rsn, weight=1.0
23:47:08      range=scv, weight=1.0
23:47:08      range=zir, weight=1.0
23:47:08      range=snz, weight=1.0
23:47:08      range=asd, weight=1.0
23:47:08      range=sqx, weight=1.0
23:47:08      range=sgn-sqx, weight=1.0
23:47:08      range=suj, weight=1.0
23:47:08      range=szy, weight=1.0
23:47:08      range=taj, weight=1.0
23:47:08      range=tsf, weight=1.0
23:47:08      range=tjj, weight=1.0
23:47:08      range=tjp, weight=1.0
23:47:08      range=tvx, weight=1.0
23:47:08      range=uss, weight=1.0
23:47:08      range=uth, weight=1.0
23:47:08      range=ysm, weight=1.0
23:47:08      range=sgn-ysm, weight=1.0
23:47:08      range=wkr, weight=0.9
23:47:08      range=ar-hyw, weight=0.8
23:47:08      range=yug, weight=0.5
23:47:08      range=yuu, weight=0.5
23:47:08      range=gfx, weight=0.4
23:47:08      range=oun, weight=0.4
23:47:08      range=mwj, weight=0.4
23:47:08      range=vaj, weight=0.4
23:47:08    Actual size=118
23:47:08      range=aam, weight=1.0
23:47:08      range=aas, weight=1.0
23:47:08      range=adp, weight=1.0
23:47:08      range=dz, weight=1.0
23:47:08      range=aeb, weight=1.0
23:47:08      range=ar-aeb, weight=1.0
23:47:08      range=ajs, weight=1.0
23:47:08      range=aog, weight=1.0
23:47:08      range=myd, weight=1.0
23:47:08      range=aue, weight=1.0
23:47:08      range=ktz, weight=1.0
23:47:08      range=bcg, weight=1.0
23:47:08      range=bgm, weight=1.0
23:47:08      range=bic, weight=1.0
23:47:08      range=bir, weight=1.0
23:47:08      range=bpp, weight=1.0
23:47:08      range=nxu, weight=1.0
23:47:08      range=cey, weight=1.0
23:47:08      range=cnp, weight=1.0
23:47:08      range=zh-cnp, weight=1.0
23:47:08      range=cqu, weight=1.0
23:47:08      range=quh, weight=1.0
23:47:08      range=csp, weight=1.0
23:47:08      range=zh-csp, weight=1.0
23:47:08      range=csx, weight=1.0
23:47:08      range=sgn-csx, weight=1.0
23:47:08      range=dif, weight=1.0
23:47:08      range=dit, weight=1.0
23:47:08      range=dmw, weight=1.0
23:47:08      range=xrq, weight=1.0
23:47:08      range=dsz, weight=1.0
23:47:08      range=ehs, weight=1.0
23:47:08      range=sgn-ehs, weight=1.0
23:47:08      range=ema, weight=1.0
23:47:08      range=uok, weight=1.0
23:47:08      range=en-gb-oed, weight=1.0
23:47:08      range=en-gb-oxendict, weight=1.0
23:47:08      range=gti, weight=1.0
23:47:08      range=nyc, weight=1.0
23:47:08      range=iba, weight=1.0
23:47:08      range=blg, weight=1.0
23:47:08      range=jks, weight=1.0
23:47:08      range=sgn-jks, weight=1.0
23:47:08      range=kdz, weight=1.0
23:47:08      range=ncp, weight=1.0
23:47:08      range=kmb, weight=1.0
23:47:08      range=koj, weight=1.0
23:47:08      range=kwv, weight=1.0
23:47:08      range=kru, weight=1.0
23:47:08      range=kxl, weight=1.0
23:47:08      range=ksp, weight=1.0
23:47:08      range=kwq, weight=1.0
23:47:08      range=yam, weight=1.0
23:47:08      range=kxe, weight=1.0
23:47:08      range=tvd, weight=1.0
23:47:08      range=kzk, weight=1.0
23:47:08      range=gli, weight=1.0
23:47:08      range=drr, weight=1.0
23:47:08      range=lii, weight=1.0
23:47:08      range=raq, weight=1.0
23:47:08      range=lmm, weight=1.0
23:47:08      range=rmx, weight=1.0
23:47:08      range=lsb, weight=1.0
23:47:08      range=sgn-lsb, weight=1.0
23:47:08      range=lsc, weight=1.0
23:47:08      range=lsn, weight=1.0
23:47:08      range=sgn-lsn, weight=1.0
23:47:08      range=lsv, weight=1.0
23:47:08      range=sgn-lsv, weight=1.0
23:47:08      range=lsw, weight=1.0
23:47:08      range=lvi, weight=1.0
23:47:08      range=mtm, weight=1.0
23:47:08      range=ymt, weight=1.0
23:47:08      range=ngv, weight=1.0
23:47:08      range=nnx, weight=1.0
23:47:08      range=nns, weight=1.0
23:47:08      range=nbr, weight=1.0
23:47:08      range=ola, weight=1.0
23:47:08      range=thw, weight=1.0
23:47:08      range=oyb, weight=1.0
23:47:08      range=thx, weight=1.0
23:47:08      range=skk, weight=1.0
23:47:08      range=jeg, weight=1.0
23:47:08      range=pat, weight=1.0
23:47:08      range=kxr, weight=1.0
23:47:08      range=phr, weight=1.0
23:47:08      range=pmu, weight=1.0
23:47:08      range=pnd, weight=1.0
23:47:08      range=pub, weight=1.0
23:47:08      range=puz, weight=1.0
23:47:08      range=rib, weight=1.0
23:47:08      range=rnb, weight=1.0
23:47:08      range=rsn, weight=1.0
23:47:08      range=scv, weight=1.0
23:47:08      range=zir, weight=1.0
23:47:08      range=snz, weight=1.0
23:47:08      range=asd, weight=1.0
23:47:08      range=sqx, weight=1.0
23:47:08      range=sgn-sqx, weight=1.0
23:47:08      range=suj, weight=1.0
23:47:08      range=szy, weight=1.0
23:47:08      range=taj, weight=1.0
23:47:08      range=tsf, weight=1.0
23:47:08      range=tjj, weight=1.0
23:47:08      range=tjp, weight=1.0
23:47:08      range=tvx, weight=1.0
23:47:08      range=uss, weight=1.0
23:47:08      range=uth, weight=1.0
23:47:08      range=ysm, weight=1.0
23:47:08      range=sgn-ysm, weight=1.0
23:47:08      range=wkr, weight=0.9
23:47:08      range=ar-hyw, weight=0.8
23:47:08      range=yug, weight=0.5
23:47:08      range=yuu, weight=0.5
23:47:08      range=gfx, weight=0.4
23:47:08      range=oun, weight=0.4
23:47:08      range=mwj, weight=0.4
23:47:08      range=vaj, weight=0.4
23:47:08      language parse() test failed.
23:47:08  java.lang.RuntimeException: Failed.
23:47:08  	at LanguageSubtagRegistryTest.main(LanguageSubtagRegistryTest.java:188)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly/463/
jdk_util_0 & jdk_util_1
java/util/Locale/LSRDataTest.java
java/util/Locale/LanguageSubtagRegistryTest.java

**Comment by pshipton** [comment]
Looks like this is caused by a mismatch between the JDK and the test material.
