### ISSUE TITLE
OpenJDK java/lang/annotation/LoaderLeakTest.java hang

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16754]
This is a new test in jdk11. It's failing on most platforms, somewhat intermittently, but fails enough to block jdk11 acceptance of 11.0.19+2.
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK11-Acceptance/72/
java/lang/annotation/LoaderLeakTest.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_OpenJDK11/61/
```
18:49:47  "main" prio=5 Id=1 WAITING
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.waitImpl(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:251)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:219)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.join(Thread.java:766)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.join(Thread.java:721)
18:49:47  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:198)
18:49:47  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
18:49:47  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
18:49:47  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
18:49:47  
18:49:47  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
18:49:47  
18:49:47  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
18:49:47  
18:49:47  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
18:49:47  
18:49:47  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
18:49:47  
18:49:47  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
18:49:47  
18:49:47  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
18:49:47  
18:49:47  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
18:49:47  
18:49:47  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
18:49:47  
18:49:47  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
18:49:47  
18:49:47  "IProfiler" prio=5 Id=12 RUNNABLE
18:49:47  
18:49:47  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.waitImpl(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:251)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:219)
18:49:47  	at java.base@11.0.19-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
18:49:47  
18:49:47  "Concurrent Mark Helper" prio=1 Id=13 RUNNABLE
18:49:47  
18:49:47  "GC Worker" prio=5 Id=14 RUNNABLE
18:49:47  
18:49:47  "GC Worker" prio=5 Id=15 RUNNABLE
18:49:47  
18:49:47  "GC Worker" prio=5 Id=16 RUNNABLE
18:49:47  
18:49:47  "Finalizer thread" prio=5 Id=19 RUNNABLE
18:49:47  
18:49:47  "Attach API wait loop" prio=10 Id=20 RUNNABLE
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
18:49:47  
18:49:47  "pool-1-thread-1" prio=5 Id=21 TIMED_WAITING
18:49:47  	at java.base@11.0.19-internal/jdk.internal.misc.Unsafe.park(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
18:49:47  
18:49:47  "AgentVMThread" prio=5 Id=47 WAITING
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.waitImpl(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:251)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:190)
18:49:47  	at java.base@11.0.19-internal/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
18:49:47  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:416)
18:49:47  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:392)
18:49:47  	at jdk.test.lib.process.ProcessTools.executeCommand(ProcessTools.java:514)
18:49:47  	at LoaderLeakTest.runJavaProcessExpectSuccessExitCode(LoaderLeakTest.java:60)
18:49:47  	at LoaderLeakTest.testWithReadingAnnotations(LoaderLeakTest.java:54)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:49:47  	at java.base@11.0.19-internal/java.lang.reflect.Method.invoke(Method.java:566)
18:49:47  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
18:49:47  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
18:49:47  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
18:49:47  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
18:49:47  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
18:49:47  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
18:49:47  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
18:49:47  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
18:49:47  	at java.base@11.0.19-internal/java.util.ArrayList.forEach(ArrayList.java:1541)
18:49:47  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
18:49:47  	at app//org.testng.TestRunner.run(TestRunner.java:585)
18:49:47  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
18:49:47  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
18:49:47  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
18:49:47  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
18:49:47  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
18:49:47  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
18:49:47  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
18:49:47  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
18:49:47  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
18:49:47  	at app//org.testng.TestNG.run(TestNG.java:1037)
18:49:47  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:49:47  	at java.base@11.0.19-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:49:47  	at java.base@11.0.19-internal/java.lang.reflect.Method.invoke(Method.java:566)
18:49:47  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
18:49:47  
18:49:47  "process reaper" prio=10 Id=48 RUNNABLE
18:49:47  	at java.base@11.0.19-internal/java.lang.ProcessHandleImpl.waitForProcessExit0(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:138)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
18:49:47  
18:49:47  "Thread-0" prio=5 Id=49 RUNNABLE
18:49:47  	at java.base@11.0.19-internal/java.io.FileInputStream.readBytes(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.io.FileInputStream.read(FileInputStream.java:279)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
18:49:47  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@87136170
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
18:49:47  	- locked java.io.BufferedInputStream@e92489fa
18:49:47  	at java.base@11.0.19-internal/java.io.FilterInputStream.read(FilterInputStream.java:107)
18:49:47  	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.FutureTask.run(FutureTask.java:264)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
18:49:47  
18:49:47  "Thread-1" prio=5 Id=50 RUNNABLE
18:49:47  	at java.base@11.0.19-internal/java.io.FileInputStream.readBytes(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.io.FileInputStream.read(FileInputStream.java:279)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
18:49:47  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@5000a5db
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
18:49:47  	at java.base@11.0.19-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
18:49:47  	- locked java.io.BufferedInputStream@7a13162
18:49:47  	at java.base@11.0.19-internal/java.io.FilterInputStream.read(FilterInputStream.java:107)
18:49:47  	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
18:49:47  	at java.base@11.0.19-internal/java.util.concurrent.FutureTask.run(FutureTask.java:264)
18:49:47  	at java.base@11.0.19-internal/java.lang.Thread.run(Thread.java:839)
18:49:47  
18:49:47  "file lock watchdog" prio=10 Id=52 TIMED_WAITING
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.waitImpl(Native Method)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:251)
18:49:47  	at java.base@11.0.19-internal/java.lang.Object.wait(Object.java:219)
18:49:47  	at java.base@11.0.19-internal/java.util.TimerThread.mainLoop(Timer.java:589)
18:49:47  	at java.base@11.0.19-internal/java.util.TimerThread.run(Timer.java:532)
18:49:47  
18:49:47  "Attachment portNumber: 35104" prio=10 Id=54 RUNNABLE
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
18:49:47  	at java.base@11.0.19-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
18:49:47  
18:49:47  
18:49:47  --- Timeout information end.
```

**Comment by pshipton** [comment]
This is a dup of https://github.com/eclipse-openj9/openj9/issues/13201, the test should pass when using `-Xjit:enableAggressiveLiveness`.

Created https://github.com/adoptium/aqa-tests/pull/4357 to exclude it.
