### ISSUE TITLE
JDK21 cmdLineTester_J9securityTests_0_FAILED AccessControlException: K002c

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16777]
Failure link
------------

[From [an internal build]()(``):](https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/138/consoleFull)
```
15:09:20  openjdk version "21-internal" 2023-09-19
15:09:20  OpenJDK Runtime Environment (build 21-internal-adhoc.****.BuildJDKnexts390xlinuxOpenJDK)
15:09:20  Eclipse OpenJ9 VM (build master-f44193e2549, JRE 21 Linux s390x-64-Bit Compressed References 20230224_403 (JIT enabled, AOT enabled)
15:09:20  OpenJ9   - f44193e2549
15:09:20  OMR      - 8d5adac3991
15:09:20  JCL      - 8237a5ec2c1 based on jdk-21+10)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=OpenJDK-Acceptance&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_s390x_linux_OpenJDK%2F403%2FOpenJ9-JDKnext-s390x_linux-20230224-143057.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_s390x_linux_OpenJDK%2F403%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=f44193e2549cfd79771a3873fda2a4b755a22fbd&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9-staging&LABEL_ADDITION=%21sw.os.rhel.8&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=138&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:17:24  variation: NoOptions
15:17:24  JVM_OPTIONS:  

15:17:24   [OUT] Test 2 / 7: Can execute allowed action with AccessControlContext(AccessControlContext, DomainCombiner)
15:17:24   [OUT] GOOD: permitted action is allowed
15:17:24   [ERR] WARNING: A terminally deprecated method in java.lang.System has been called
15:17:24   [ERR] WARNING: System::setSecurityManager has been called by com.ibm.j9.security.TestImplies (file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/jvmtest/functional/cmdLineTests/J9security/j9security.jar)
15:17:24   [ERR] WARNING: Please consider reporting this to the maintainers of com.ibm.j9.security.TestImplies
15:17:24   [ERR] WARNING: System::setSecurityManager will be removed in a future release
15:17:24   [ERR] java.security.AccessControlException: K002c
15:17:24   [ERR] 	at java.base/java.security.AccessController.throwACE(AccessController.java:177)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermission(AccessController.java:386)
15:17:24   [ERR] 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$CustomSecurityManager.checkPermission(TestImplies.java:237)
15:17:24   [ERR] 	at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:376)
15:17:24   [ERR] 	at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:356)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.runTest(TestImplies.java:74)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass$1.run(TestImplies.java:55)
15:17:24   [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.run(TestImplies.java:53)
15:17:24   [ERR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:17:24   [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.runTest(TestImplies.java:285)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.main(TestImplies.java:242)
15:17:24   [ERR] java.security.AccessControlException: K002c
15:17:24   [ERR] 	at java.base/java.security.AccessController.throwACE(AccessController.java:177)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermission(AccessController.java:386)
15:17:24   [ERR] 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$CustomSecurityManager.checkPermission(TestImplies.java:237)
15:17:24   [ERR] 	at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:376)
15:17:24   [ERR] 	at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:356)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.runTest(TestImplies.java:98)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass$1.run(TestImplies.java:55)
15:17:24   [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.run(TestImplies.java:53)
15:17:24   [ERR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:17:24   [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.runTest(TestImplies.java:285)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.main(TestImplies.java:242)
15:17:24   [ERR] java.security.AccessControlException: K002d
15:17:24   [ERR] 	at java.base/java.security.AccessController.throwACE(AccessController.java:174)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:226)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermission(AccessController.java:386)
15:17:24   [ERR] 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$CustomSecurityManager.checkPermission(TestImplies.java:237)
15:17:24   [ERR] 	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1146)
15:17:24   [ERR] 	at java.base/java.lang.System.getProperty(System.java:643)
15:17:24   [ERR] 	at java.base/java.lang.System.getProperty(System.java:626)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass$5.run(TestImplies.java:162)
15:17:24   [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.runTest(TestImplies.java:160)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass$1.run(TestImplies.java:55)
15:17:24   [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.run(TestImplies.java:53)
15:17:24   [ERR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:17:24   [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.runTest(TestImplies.java:285)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.main(TestImplies.java:242)
15:17:24   [ERR] java.security.AccessControlException: K002c
15:17:24   [ERR] 	at java.base/java.security.AccessController.throwACE(AccessController.java:177)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
15:17:24   [ERR] 	at java.base/java.security.AccessController.checkPermission(AccessController.java:386)
15:17:24   [ERR] 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$CustomSecurityManager.checkPermission(TestImplies.java:237)
15:17:24   [ERR] 	at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:376)
15:17:24   [ERR] 	at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:356)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.runTest(TestImplies.java:203)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass$1.run(TestImplies.java:55)
15:17:24   [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies$RestrictedClass.run(TestImplies.java:53)
15:17:24   [ERR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:17:24   [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.runTest(TestImplies.java:285)
15:17:24   [ERR] 	at com.ibm.j9.security.TestImplies.main(TestImplies.java:242)
15:17:24  >> Success condition was not found: [Output match: ALL TESTS COMPLETED AND PASSED]
15:17:24  >> Failure condition was not found: [Output match: Unhandled Exception]
15:17:24  >> Failure condition was not found: [Output match: Processing dump event]
15:17:24  >> Failure condition was found: [Output match: FAILED:]

15:17:25  ---TEST RESULTS---
15:17:26  Number of PASSED tests: 6 out of 7
15:17:26  Number of FAILED tests: 1 out of 7
15:17:26  
15:17:26  ---SUMMARY OF FAILED TESTS---
15:17:26  testJ9Security
15:17:26  -----------------------------
15:17:26  
15:17:26  -----------------------------------
15:17:26  cmdLineTester_J9securityTests_0_FAILED
```

**Comment by pshipton** [comment]
I believe this was resolved.
