### ISSUE TITLE
JDK21 NestAttributeTest_0_FAILED AssertionError: should throw exception on getNestMembers

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16781]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK_testList_0/124/consoleFull
```
15:41:19  openjdk version "21-internal" 2023-09-19
15:41:19  OpenJDK Runtime Environment (build 21-internal-adhoc.****.BuildJDKnextppc64aixOpenJDK)
15:41:19  Eclipse OpenJ9 VM (build master-f44193e2549, JRE 21 AIX ppc64-64-Bit Compressed References 20230224_413 (JIT enabled, AOT enabled)
15:41:19  OpenJ9   - f44193e2549
15:41:19  OMR      - 8d5adac3991
15:41:19  JCL      - 8237a5ec2c1 based on jdk-21+10)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdknext_j9_sanity.functional_ppc64_aix_OpenJDK&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=OpenJDK-Acceptance&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_ppc64_aix_OpenJDK%2F413%2FOpenJ9-JDKnext-ppc64_aix-20230224-192720.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_ppc64_aix_OpenJDK%2F413%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=f44193e2549cfd79771a3873fda2a4b755a22fbd&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9-staging&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=124&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:58:50  variation: NoOptions
15:58:50  JVM_OPTIONS:  

15:58:52  FAILED: testGetNestMembersAPIInValidHost
15:58:52  java.lang.AssertionError: should throw exception on getNestMembers
15:58:52  	at org.testng.Assert.fail(Assert.java:96)
15:58:52  	at org.openj9.test.nestmates.NestAttributeTest.testGetNestMembersAPIInValidHost(NestAttributeTest.java:355)
15:58:52  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:58:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:58:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
15:58:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
15:58:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:58:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:58:52  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
15:58:52  	at org.testng.TestRunner.run(TestRunner.java:505)
15:58:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
15:58:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
15:58:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
15:58:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
15:58:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:58:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
15:58:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
15:58:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
15:58:52  	at org.testng.TestNG.runSuites(TestNG.java:1049)
15:58:52  	at org.testng.TestNG.run(TestNG.java:1017)
15:58:52  	at org.testng.TestNG.privateMain(TestNG.java:1354)
15:58:52  	at org.testng.TestNG.main(TestNG.java:1323)
15:58:52  
15:58:52  FAILED: testGetNestMembersAPIInValidHostWrongPackage
15:58:52  java.lang.AssertionError: should throw exception on getNestMembers
15:58:52  	at org.testng.Assert.fail(Assert.java:96)
15:58:52  	at org.openj9.test.nestmates.NestAttributeTest.testGetNestMembersAPIInValidHostWrongPackage(NestAttributeTest.java:376)
15:58:52  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:58:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:58:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
15:58:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
15:58:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:58:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:58:52  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
15:58:52  	at org.testng.TestRunner.run(TestRunner.java:505)
15:58:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
15:58:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
15:58:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
15:58:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
15:58:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:58:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
15:58:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
15:58:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
15:58:52  	at org.testng.TestNG.runSuites(TestNG.java:1049)
15:58:52  	at org.testng.TestNG.run(TestNG.java:1017)
15:58:52  	at org.testng.TestNG.privateMain(TestNG.java:1354)
15:58:52  	at org.testng.TestNG.main(TestNG.java:1323)
15:58:52  
15:58:52  FAILED: testGetNestMembersAPINestMemberWrongNestHost
15:58:52  java.lang.AssertionError: should throw exception on getNestMembers
15:58:52  	at org.testng.Assert.fail(Assert.java:96)
15:58:52  	at org.openj9.test.nestmates.NestAttributeTest.testGetNestMembersAPINestMemberWrongNestHost(NestAttributeTest.java:416)
15:58:52  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:58:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:58:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
15:58:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
15:58:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:58:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:58:52  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
15:58:52  	at org.testng.TestRunner.run(TestRunner.java:505)
15:58:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
15:58:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
15:58:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
15:58:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
15:58:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:58:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
15:58:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
15:58:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
15:58:52  	at org.testng.TestNG.runSuites(TestNG.java:1049)
15:58:52  	at org.testng.TestNG.run(TestNG.java:1017)
15:58:52  	at org.testng.TestNG.privateMain(TestNG.java:1354)
15:58:52  	at org.testng.TestNG.main(TestNG.java:1323)
15:58:52  
15:58:52  FAILED: testGetNestMembersAPINestMemberWrongPackage
15:58:52  java.lang.AssertionError: should throw exception on getNestMembers
15:58:52  	at org.testng.Assert.fail(Assert.java:96)
15:58:52  	at org.openj9.test.nestmates.NestAttributeTest.testGetNestMembersAPINestMemberWrongPackage(NestAttributeTest.java:397)
15:58:52  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:58:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:58:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
15:58:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
15:58:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
15:58:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:58:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:58:52  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
15:58:52  	at org.testng.TestRunner.run(TestRunner.java:505)
15:58:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
15:58:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
15:58:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
15:58:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
15:58:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:58:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
15:58:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
15:58:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
15:58:52  	at org.testng.TestNG.runSuites(TestNG.java:1049)
15:58:52  	at org.testng.TestNG.run(TestNG.java:1017)
15:58:52  	at org.testng.TestNG.privateMain(TestNG.java:1354)
15:58:52  	at org.testng.TestNG.main(TestNG.java:1323)
15:58:52  
15:58:52  
15:58:52  ===============================================
15:58:52      NestAttributeTest
15:58:52      Tests run: 27, Failures: 4, Skips: 0
15:58:52  ===============================================
15:58:52  
15:58:52  
15:58:52  ===============================================
15:58:52  Java11andUp suite
15:58:52  Total tests run: 27, Failures: 4, Skips: 0
15:58:52  ===============================================
15:58:52  
15:58:52  -----------------------------------
15:58:52  NestAttributeTest_0_FAILED
```

[50x grinder](https://openj9-jenkins.osuosl.org/job/Grinder/2053/) - all failed

Also occurred at other platforms such as https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_windows_OpenJDK_testList_0/127/consoleFull.

**Comment by pshipton** [comment]
This must have been resolved since we no longer see this failure on jdk21.
