### ISSUE TITLE
JDK21 cmdLineTester_DataHelperTests_0_FAILED RuntimeException: storeSharedData('fileone.txt',...) has failed!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16782]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_linux_OpenJDK_testList_1/124/consoleFull
```
15:07:22  openjdk version "21-internal" 2023-09-19
15:07:22  OpenJDK Runtime Environment (build 21-internal-adhoc.****.BuildJDKnextaarch64linuxOpenJDK)
15:07:22  Eclipse OpenJ9 VM (build master-f44193e2549, JRE 21 Linux aarch64-64-Bit Compressed References 20230224_285 (JIT enabled, AOT enabled)
15:07:22  OpenJ9   - f44193e2549
15:07:22  OMR      - 8d5adac3991
15:07:22  JCL      - 8237a5ec2c1 based on jdk-21+10)
```
[Rerun in Grinder]() - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:27:46  variation: Mode110
15:27:46  JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

15:27:48  Testing: simple caching of a resource
15:27:48  Test start time: 2023/02/24 15:27:48 Eastern Standard Time
15:27:48  Running command: "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_aarch64_linux_OpenJDK_testList_1/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:reset,name=testCache -classpath . apitesting.datahelper.DataCachingTest02
15:27:48  Time spent starting: 4 milliseconds
15:27:49  Time spent executing: 778 milliseconds
15:27:49  Test result: FAILED
15:27:49   [OUT] simple data caching test
15:27:49   [OUT] make sure the resource we are testing is not in the cache already
15:27:49   [OUT] load the resource, it should get cached
15:27:49   [OUT] DataCachingClassLoader: Caching the data with token 'fileone.txt'
15:27:49   [ERR] JVMSHRC256I Persistent shared cache "testCache" has been destroyed
15:27:49   [ERR] Exception in thread "main" java.lang.RuntimeException: storeSharedData('fileone.txt',...) has failed!
15:27:49   [ERR] 	at CustomClassloaders.DataCachingClassLoader.getResourceAsStream(DataCachingClassLoader.java:93)
15:27:49   [ERR] 	at apitesting.datahelper.DataCachingTest02.run(DataCachingTest02.java:48)
15:27:49   [ERR] 	at apitesting.datahelper.DataCachingTest02.main(DataCachingTest02.java:34)
15:27:49  >> Success condition was not found: [Output match: test successful]
15:27:49  >> Failure condition was found: [Output match: failed]
15:27:49  >> Failure condition was found: [Output match: exception:]
15:27:49  >> Failure condition was not found: [Output match: Processing dump event]

15:27:57  ---TEST RESULTS---
15:27:57  Number of PASSED tests: 2 out of 10
15:27:57  Number of FAILED tests: 8 out of 10
15:27:57  
15:27:57  ---SUMMARY OF FAILED TESTS---
15:27:57  simple caching of a resource
15:27:57  simple caching of a resource, with security on
15:27:57  simple caching of a resource, with security on but writeonly policy
15:27:57  caching of multiple resources
15:27:57  caching of multiple resources, security on
15:27:57  marking cache entries stale for bytedata resources
15:27:57  more stale marking
15:27:57  using same token for multiple resources
15:27:57  -----------------------------
15:27:57  
15:27:57  -----------------------------------
15:27:57  cmdLineTester_DataHelperTests_0_FAILED
```

[50x grinder](https://openj9-jenkins.osuosl.org/job/Grinder/2054/) - all failed

Also occurred at https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_windows_OpenJDK_testList_1/127/consoleFull
[50x grinder](https://openj9-jenkins.osuosl.org/job/Grinder/2055/) - all failed

**Comment by pshipton** [comment]
This must have been resolved since we no longer see this failure on jdk21.
