### ISSUE TITLE
JDK19 serviceability_jvmti_j9_0_FAILED RuntimeException: ContinuationTest failed: expected no FramePop events!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16792]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux/41/)(`ub20x64rt3-2`):
```
openjdk version "19.0.2" 2023-01-17
IBM Semeru Runtime Open Edition 19.0.2+7 (build 19.0.2+7)
Eclipse OpenJ9 VM 19.0.2+7 (build master-cce33ede0, JRE 19 Linux amd64-64-Bit Compressed References 20230117_51 (JIT enabled, AOT enabled)
OpenJ9   - cce33ede0
OMR      - 19361557f
JCL      - 3c83ead7fc based on jdk-19.0.2+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=serviceability_jvmti_j9_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=3&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F51%2Fibm-semeru-open-jre_x64_linux_JDK19U_2023-02-25-17-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F51%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2023-02-25-17-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F51%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2023-02-25-17-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F51%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2023-02-25-17-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-02-25T17:28:50.979Z] variation: Mode150
[2023-02-25T17:28:50.979Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-02-25T17:34:44.860Z] TEST: serviceability/jvmti/vthread/ContinuationTest/ContinuationTest.java

[2023-02-25T17:34:44.863Z] STDERR:
[2023-02-25T17:34:44.863Z] java.lang.RuntimeException: ContinuationTest failed: expected no FramePop events!
[2023-02-25T17:34:44.863Z] 	at ContinuationTest.main(ContinuationTest.java:59)
[2023-02-25T17:34:44.863Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-02-25T17:34:44.863Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-02-25T17:34:44.863Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-02-25T17:34:44.863Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2023-02-25T17:34:44.863Z] 
[2023-02-25T17:34:44.863Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: ContinuationTest failed: expected no FramePop events!

[2023-02-25T17:34:44.863Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: ContinuationTest failed: expected no FramePop events!
[2023-02-25T17:34:44.863Z] --------------------------------------------------
[2023-02-25T17:34:56.861Z] Test results: passed: 118; failed: 1
[2023-02-25T17:35:06.726Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2023-02-25T17:35:06.726Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16773459782921/serviceability_jvmti_j9_0/work
[2023-02-25T17:35:06.726Z] Error: Some tests failed or other problems occurred.
[2023-02-25T17:35:06.726Z] -----------------------------------
[2023-02-25T17:35:06.726Z] serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31267/)

Also seen at [x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_mac/40/), [s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_s390x_linux/39/)

**Comment by pshipton** [comment]
@JasonFengJ9 the grinder failed to run.

**Comment by pshipton** [comment]
@tajila a new jdk19 issue.

**Comment by tajila** [comment]
@babsingh Please take a look

**Comment by JasonFengJ9** [comment]
> the grinder failed to run.

Failed twice, will give it another try when the infra sso issue is resolved.

**Comment by babsingh** [comment]
ContinuationTest : https://github.com/ibmruntimes/openj9-openjdk-jdk19/tree/openj9/test/hotspot/jtreg/serviceability/jvmti/vthread/ContinuationTest

- The test runs a Continuation on a carrier thread. Currently, this is not supported since Continuation is an internal class and not publicly exposed.
- The test also expects no FramePop events for the Continuation's frames. But there is no formal JVMTI documentation for handling continuations:
    - JVMTI FramePop doc : https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html#FramePop
    - JVMTI NotifyFramePop doc : https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html#NotifyFramePop
- The test is RI specific and does apply to OpenJ9 since OpenJ9 has a different implementation to support Continuations.  

Due to the above reasons, this test should be excluded for OpenJ9.

fyi @fengxue-IS @tajila

**Comment by babsingh** [comment]
Created https://github.com/adoptium/aqa-tests/pull/4380 to permanently disable the test.
