### ISSUE TITLE
DDR !stackslots command is broken at "Pending stack starting at"

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse-openj9/openj9#16804]
DDR `!stackslots` command is broken in:
```
openjdk version "19.0.2-internal" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2-internal-adhoc.jenkins.BuildJDK19x86-64linuxNightly)
Eclipse OpenJ9 VM (build master-9bf20a075d0, JRE 19 Linux amd64-64-Bit Compressed References 20230227_189 (JIT enabled, AOT enabled)
OpenJ9   - 9bf20a075d0
OMR      - 084e87a9289
JCL      - 3c83ead7fc8 based on jdk-19.0.2+7)
```
but works with older version:
```
openjdk version "19.0.1-internal" 2022-10-18
OpenJDK Runtime Environment (build 19.0.1-internal-adhoc.jenkins.BuildJDK19x86-64linuxNightly)
Eclipse OpenJ9 VM (build master-531e952f4f3, JRE 19 Linux amd64-64-Bit Compressed References 20221110_113 (JIT enabled, AOT enabled)
OpenJ9   - 531e952f4f3
OMR      - 0453d02bff7
JCL      - 110e1e7808e based on jdk-19.0.1+10)
```
Output from broken DDR for `!stackslots 0x11ea0500`:
```
<11ea0500> 	Method: java/lang/invoke/DelegatingMethodHandle.makeReinvokerForm(Ljava/lang/invoke/MethodHandle;ILjava/lang/Object;ZLjava/lang/invoke/LambdaForm$NamedFunction;Ljava/lang/invoke/LambdaForm$NamedFunction;)Ljava/lang/invoke/LambdaForm; !j9method 0x0000000011DEAD48
<11ea0500> 	Bytecode index = 303
<11ea0500> 	Using local mapper
<11ea0500> 	Locals starting at 0x0000000011ECB628 for 0x0000000000000014 slots
<11ea0500> 		I-Slot: a0[0x0000000011ECB628] = 0x00000000FFEEC428
<11ea0500> 		I-Slot: a1[0x0000000011ECB620] = 0x0000000000000007
<11ea0500> 		I-Slot: a2[0x0000000011ECB618] = 0x00000000E005D990
<11ea0500> 		I-Slot: a3[0x0000000011ECB610] = 0x0000000000000001
<11ea0500> 		I-Slot: a4[0x0000000011ECB608] = 0x00000000E005F6D8
<11ea0500> 		I-Slot: a5[0x0000000011ECB600] = 0x0000000000000000
<11ea0500> 		O-Slot: t6[0x0000000011ECB5F8] = 0x00000000FFF01978
<11ea0500> 		O-Slot: t7[0x0000000011ECB5F0] = 0x00000000E005C4F0
<11ea0500> 		I-Slot: t8[0x0000000011ECB5E8] = 0x0000000000000000
<11ea0500> 		I-Slot: t9[0x0000000011ECB5E0] = 0x0000000000000000
<11ea0500> 		I-Slot: t10[0x0000000011ECB5D8] = 0x0000000000000000
<11ea0500> 		I-Slot: t11[0x0000000011ECB5D0] = 0x0000000000000000
<11ea0500> 		I-Slot: t12[0x0000000011ECB5C8] = 0x0000000000000001
<11ea0500> 		I-Slot: t13[0x0000000011ECB5C0] = 0x0000000000000003
<11ea0500> 		I-Slot: t14[0x0000000011ECB5B8] = 0x0000000000000005
<11ea0500> 		I-Slot: t15[0x0000000011ECB5B0] = 0x00000000FFFFFFFF
<11ea0500> 		I-Slot: t16[0x0000000011ECB5A8] = 0x0000000000000003
<11ea0500> 		I-Slot: t17[0x0000000011ECB5A0] = 0x0000000000000004
<11ea0500> 		O-Slot: t18[0x0000000011ECB598] = 0x00000000FFF019F0
<11ea0500> 		I-Slot: t19[0x0000000011ECB590] = 0x00000000FFEEC530
Feb 28, 2023 3:29:17 PM com.ibm.j9ddr.vm29.events.DefaultEventListener corruptData
WARNING: CorruptData encountered iterating o-slots. walkThread = 0x0000000011EA0500
com.ibm.j9ddr.CorruptDataException: Operand stack underflow in StackMap
	at com.ibm.j9ddr.vm29.j9.stackmap.StackMap$J9MappingStack.POP(StackMap.java:184)
	at com.ibm.j9ddr.vm29.j9.stackmap.StackMap$StackMap_V1.POP(StackMap.java:733)
	at com.ibm.j9ddr.vm29.j9.stackmap.StackMap$StackMap_V1.mapStack(StackMap.java:569)
	at com.ibm.j9ddr.vm29.j9.stackmap.StackMap$StackMap_V1.j9stackmap_StackBitsForPC(StackMap.java:270)
	at com.ibm.j9ddr.vm29.j9.stackmap.StackMap.j9stackmap_StackBitsForPC(StackMap.java:106)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.getStackMap(StackWalker.java:1025)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkBytecodeFrameSlots(StackWalker.java:924)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkBytecodeFrame(StackWalker.java:1008)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:449)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker.walkStackFrames(StackWalker.java:103)
```
Output from working DDR:
```
<11ea0500> 	Method: java/lang/invoke/DelegatingMethodHandle.makeReinvokerForm(Ljava/lang/invoke/MethodHandle;ILjava/lang/Object;ZLjava/lang/invoke/LambdaForm$NamedFunction;Ljava/lang/invoke/LambdaForm$NamedFunction;)Ljava/lang/invoke/LambdaForm; !j9method 0x0000000011DEAD48
<11ea0500> 	Bytecode index = 303
<11ea0500> 	Using local mapper
<11ea0500> 	Locals starting at 0x0000000011ECB628 for 0x0000000000000014 slots
<11ea0500> 		I-Slot: a0[0x0000000011ECB628] = 0x00000000FFEEC428
<11ea0500> 		I-Slot: a1[0x0000000011ECB620] = 0x0000000000000007
<11ea0500> 		I-Slot: a2[0x0000000011ECB618] = 0x00000000E005D990
<11ea0500> 		I-Slot: a3[0x0000000011ECB610] = 0x0000000000000001
<11ea0500> 		I-Slot: a4[0x0000000011ECB608] = 0x00000000E005F6D8
<11ea0500> 		I-Slot: a5[0x0000000011ECB600] = 0x0000000000000000
<11ea0500> 		O-Slot: t6[0x0000000011ECB5F8] = 0x00000000FFF01978
<11ea0500> 		O-Slot: t7[0x0000000011ECB5F0] = 0x00000000E005C4F0
<11ea0500> 		I-Slot: t8[0x0000000011ECB5E8] = 0x0000000000000000
<11ea0500> 		I-Slot: t9[0x0000000011ECB5E0] = 0x0000000000000000
<11ea0500> 		I-Slot: t10[0x0000000011ECB5D8] = 0x0000000000000000
<11ea0500> 		I-Slot: t11[0x0000000011ECB5D0] = 0x0000000000000000
<11ea0500> 		I-Slot: t12[0x0000000011ECB5C8] = 0x0000000000000001
<11ea0500> 		I-Slot: t13[0x0000000011ECB5C0] = 0x0000000000000003
<11ea0500> 		I-Slot: t14[0x0000000011ECB5B8] = 0x0000000000000005
<11ea0500> 		I-Slot: t15[0x0000000011ECB5B0] = 0x00000000FFFFFFFF
<11ea0500> 		I-Slot: t16[0x0000000011ECB5A8] = 0x0000000000000003
<11ea0500> 		I-Slot: t17[0x0000000011ECB5A0] = 0x0000000000000004
<11ea0500> 		O-Slot: t18[0x0000000011ECB598] = 0x00000000FFF019F0
<11ea0500> 		I-Slot: t19[0x0000000011ECB590] = 0x00000000FFEEC530
<11ea0500> 	Pending stack starting at 0x0000000011ECB570 for UDATA(0x0000000000000003) slots
<11ea0500> 		O-Slot: p0[0x0000000011ECB570] = 0x00000000FFF019F0
<11ea0500> 		I-Slot: p1[0x0000000011ECB568] = 0x0000000000000004
<11ea0500> 		O-Slot: p2[0x0000000011ECB560] = 0x00000000FFF019B0
```
This problem has been discovered during analysing core for https://github.com/eclipse-openj9/openj9/issues/16756
Core is preserved at `/team/dmitri/16756/aqa-tests/TKG/output_16770217291833/serviceability_jvmti_j9_0_ITER_4/work/serviceability/jvmti/vthread/BreakpointInYieldTest/BreakpointInYieldTest/core.20230221.182945.30452.0001.dmp`
This core has been generated by:
```
JAVA VM NAME	- Eclipse OpenJ9 VM
JAVA VM VERSION	- master-042864b42
JAVA SERVICE LEVEL INFO
JRE 19 Mac OS X amd64-64 (build 19.0.2+7)
JAVA VERSION INFO
JRE 19 Mac OS X amd64-64-Bit Compressed References 20230117_46 (JIT enabled, AOT enabled)
OpenJ9   - 042864b42
OMR      - b86560818
JCL      - edc950934d based on jdk-19.0.2+7
```

**Comment by dmitripivkine** [comment]
FYI @keithc-ca

**Comment by keithc-ca** [comment]
Who knows how to tell if the stackmap for that thread is valid, or whether it's malformed and _should_ lead to underflow?
I'm not sure which stack frame leads to the failure. The one before says:
```
> !stackmap  0x00000000387F2BBC 
Searching for PC=947858364 in VM=0x00007FBA78821020...
Found method java/lang/invoke/StringConcatFactory.makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; !j9method 0x0000000011EBDB18
Relative PC = 220
Method index is 1
Using ROM method 0x00000000387F2ACC
```
and the one after says:
```
> !stackmap 0x00007FBA7A0B93AA 
Searching for PC=140438888223658 in VM=0x00007FBA78821020...
Not found
```
"Not found" doesn't sound good.

**Comment by dnakamura** [comment]
I believe I have found the issue. It appears to be a bug in #16411, which causes us to fail when parsing array arguments. Currently working on a patch that also cleans up some other issues in the area.

**Comment by dnakamura** [comment]
see #17278
