### ISSUE TITLE
OpenJDK compile failures and much more

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16802]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK8/513/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/494/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK17/434/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/276/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK20/9/

Example https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly/368/

    java/lang/ref/Basic.java.Basic
    jdk/lambda/FDTest.java.FDTest
    java/util/concurrent/forkjoin/NQueensCS.java.NQueensCS
    java/util/logging/SimpleLogManager.java.SimpleLogManager

java/lang/ref/Basic.java.Basic
```
20:45:58  java.lang.AssertionError: duplicate context value
20:45:58  	at com.sun.tools.javac.util.Context.put(Context.java:141)
20:45:58  	at com.sun.tools.javac.util.Options.<init>(Options.java:61)
20:45:58  	at com.sun.tools.javac.util.Options.instance(Options.java:54)
20:45:58  	at com.sun.tools.javac.code.Lint.<init>(Lint.java:91)
20:45:58  	at com.sun.tools.javac.code.Lint.instance(Lint.java:53)
20:45:58  	at com.sun.tools.javac.util.BaseFileManager.setContext(BaseFileManager.java:81)
20:45:58  	at com.sun.tools.javac.file.JavacFileManager.setContext(JavacFileManager.java:136)
20:45:58  	at com.sun.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:128)
20:45:58  	at com.sun.tools.javac.file.JavacFileManager$1.make(JavacFileManager.java:115)
20:45:58  	at com.sun.tools.javac.file.JavacFileManager$1.make(JavacFileManager.java:113)
20:45:58  	at com.sun.tools.javac.util.Context.get(Context.java:150)
20:45:58  	at com.sun.tools.javac.util.Context.get(Context.java:193)
20:45:58  	at com.sun.tools.javac.main.JavaCompiler.<init>(JavaCompiler.java:342)
20:45:58  	at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:88)
20:45:58  	at com.sun.tools.javac.main.Main.compile(Main.java:485)
20:45:58  	at com.sun.tools.javac.main.Main.compile(Main.java:381)
20:45:58  	at com.sun.tools.javac.main.Main.compile(Main.java:370)
20:45:58  	at com.sun.tools.javac.main.Main.compile(Main.java:361)
20:45:58  	at com.sun.tools.javac.Main.compile(Main.java:74)
20:45:58  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
20:45:58  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:45:58  	at java.lang.reflect.Method.invoke(Method.java:498)
20:45:58  	at com.sun.javatest.regtest.agent.RegressionCompileCommand.run(RegressionCompileCommand.java:189)
20:45:58  	at com.sun.javatest.regtest.agent.CompileActionHelper.runCompile(CompileActionHelper.java:92)
20:45:58  	at com.sun.javatest.regtest.agent.AgentServer.doCompile(AgentServer.java:262)
20:45:58  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:229)
20:45:58  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
20:45:58  
20:45:58  TEST RESULT: Error. compiler crashed (exit code 4)
```

jdk/lambda/FDTest.java.FDTest
```
20:46:51  test FDTest.testOneCase(POSITIVE, CCCpcadcap2ca): failure
20:46:51  java.lang.AssertionError: Error thrown when analyzing the following source:
20:46:51  abstract  class CCCpcadcap2ca extends CCpcadca implements p2 {
20:46:51     public abstract String m();
20:46:51  }
20:46:51  
20:46:51  interface p  {
20:46:51      String m();
20:46:51  }
20:46:51  
20:46:51  interface p2  {
20:46:51      String m();
20:46:51  }
20:46:51  
20:46:51  interface d  {
20:46:51      default String m() { return ""; }
20:46:51  }
20:46:51  
20:46:51  abstract  class CCpcadca extends Cpca implements d {
20:46:51     public abstract String m();
20:46:51  }
20:46:51  
20:46:51  abstract  class Cpca implements p {
20:46:51     public abstract String m();
20:46:51  }
20:46:51  
20:46:51  
20:46:51  	at org.testng.Assert.fail(Assert.java:94)
20:46:51  	at FDTest.run(FDTest.java:134)
20:46:51  	at FDTest.runTest(FDTest.java:111)
20:46:51  	at FDTest.testOneCase(FDTest.java:83)
20:46:51  	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
20:46:51  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:46:51  	at java.lang.reflect.Method.invoke(Method.java:498)
20:46:51  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
20:46:51  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
20:46:51  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
20:46:51  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
20:46:51  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
20:46:51  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
20:46:51  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
20:46:51  	at org.testng.TestRunner.run(TestRunner.java:623)
20:46:51  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
20:46:51  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
20:46:51  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
20:46:51  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
20:46:51  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
20:46:51  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
20:46:51  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
20:46:51  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
20:46:51  	at org.testng.TestNG.run(TestNG.java:1018)
20:46:51  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
20:46:51  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:46:51  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:46:51  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:46:51  	at java.lang.reflect.Method.invoke(Method.java:498)
20:46:51  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:46:51  	at java.lang.Thread.run(Thread.java:826)
```

**Comment by pshipton** [comment]
Changes 
https://github.com/eclipse-openj9/openj9/compare/9bf20a075...04949570046

I suspect https://github.com/eclipse-openj9/openj9/pull/16567

**Comment by pshipton** [comment]
Try some testing with https://github.com/eclipse-openj9/openj9/pull/16567 reverted.

https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_mac_Personal/288/
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2056/
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2057/

**Comment by pshipton** [comment]
The grinders passed so I will revert https://github.com/eclipse-openj9/openj9/pull/16567

**Comment by pshipton** [comment]
Re-running the extended.system failures as well with the revert.
https://openj9-jenkins.osuosl.org/job/Grinder/2058/
