### ISSUE TITLE
JDK8 FIPS TestJlmRemoteMemoryAuth_0_FAILED NoSuchAlgorithmException: JKS KeyStore not available

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16903]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.system_x86-64_linux_fips_testList_0/1/)(`rhel8x64-fips1-1`):
```
openjdk version "1.8.0_372"
IBM Semeru Runtime Open Edition (build 1.8.0_372-b03)
Eclipse OpenJ9 VM (build v0.38.0-release-25af2a240, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230309_612 (JIT enabled, AOT enabled)
OpenJ9   - 25af2a240
OMR      - 008f97b5c
JCL      - a1cfd8750f based on jdk8u372-b03)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=TestJlmRemoteMemoryAuth_0&amp;TEST_FLAG=FIPS&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_sanity.system_x86-64_linux_fips&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=3&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-jre_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-debugimage_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-testimage_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-jdk_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.38.0-release&amp;OPENJ9_BRANCH=v0.38.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.38.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=1&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-03-10T09:45:23.755Z] variation: Mode150
[2023-03-10T09:45:23.755Z] JVM_OPTIONS:  -XX:+UseCompressedOops  -Dsemeru.fips=true

[2023-03-10T09:47:53.462Z] CL1 stderr java.rmi.ConnectIOException: Exception creating connection to: 10.11.115.122; nested exception is: 
[2023-03-10T09:47:53.462Z] CL1 stderr 	java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:635)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at com.sun.proxy.$Proxy0.newClient(Unknown Source)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.doConnect(ServerConnector.java:273)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.getSecureServerConnection(ServerConnector.java:170)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.<init>(ServerConnector.java:82)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.<init>(MemoryProfiler.java:77)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:96)
[2023-03-10T09:47:53.462Z] CL1 stderr Caused by: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:248)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:262)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.rmi.ssl.SslRMIClientSocketFactory.createSocket(SslRMIClientSocketFactory.java:121)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
[2023-03-10T09:47:53.462Z] CL1 stderr 	... 14 more
[2023-03-10T09:47:53.462Z] CL1 stderr Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at java.security.Provider$Service.newInstance(Provider.java:1617)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.rmi.ssl.SslRMIClientSocketFactory.getDefaultClientSocketFactory(SslRMIClientSocketFactory.java:207)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.rmi.ssl.SslRMIClientSocketFactory.createSocket(SslRMIClientSocketFactory.java:117)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.DGCImpl_Stub.dirty(DGCImpl_Stub.java:102)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.DGCClient$EndpointEntry.makeDirtyCall(DGCClient.java:382)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.DGCClient$EndpointEntry.registerRefs(DGCClient.java:324)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.DGCClient.registerRefs(DGCClient.java:160)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.ConnectionInputStream.registerRefs(ConnectionInputStream.java:102)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.StreamRemoteCall.releaseInputStream(StreamRemoteCall.java:175)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.transport.StreamRemoteCall.done(StreamRemoteCall.java:340)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.server.UnicastRef.done(UnicastRef.java:452)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:132)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:218)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.naming.InitialContext.lookup(InitialContext.java:417)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
[2023-03-10T09:47:53.462Z] CL1 stderr 	... 6 more
[2023-03-10T09:47:53.462Z] CL1 stderr Caused by: java.security.KeyStoreException: problem accessing trust store
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:1043)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:1013)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1188)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2023-03-10T09:47:53.462Z] CL1 stderr 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at java.security.Provider$Service.newInstance(Provider.java:1595)
[2023-03-10T09:47:53.463Z] CL1 stderr 	... 32 more
[2023-03-10T09:47:53.463Z] CL1 stderr Caused by: java.security.KeyStoreException: JKS not found
[2023-03-10T09:47:53.463Z] CL1 stderr 	at java.security.KeyStore.getInstance(KeyStore.java:851)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:351)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
[2023-03-10T09:47:53.463Z] CL1 stderr 	... 41 more
[2023-03-10T09:47:53.463Z] CL1 stderr Caused by: java.security.NoSuchAlgorithmException: JKS KeyStore not available
[2023-03-10T09:47:53.463Z] CL1 stderr 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at java.security.Security.getImpl(Security.java:714)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at java.security.KeyStore.getInstance(KeyStore.java:848)
[2023-03-10T09:47:53.463Z] CL1 stderr 	... 45 more
[2023-03-10T09:47:53.463Z] CL1 stderr Exception in thread "main" java.lang.NullPointerException
[2023-03-10T09:47:53.463Z] CL1 stderr 	at com.ibm.java.lang.management.internal.ManagementUtils.isANotificationEmitter(ManagementUtils.java:537)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:289)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.getStatsViaProxy(MemoryProfiler.java:127)
[2023-03-10T09:47:53.463Z] CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:110)
[2023-03-10T09:47:53.463Z] STF 01:47:52.663 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)

[2023-03-10T09:48:04.312Z] STF 01:48:04.261 - Overall result: **FAILED**
[2023-03-10T09:48:04.312Z] -----------------------------------
[2023-03-10T09:48:04.312Z] TestJlmRemoteMemoryAuth_0_FAILED
```

**Comment by jasonkatonica** [comment]
Hello @JasonFengJ9 , When executing with the flag `-Dsemeru.fips=true` set the `Sun` provider, and its associated algorithms, are all currently disabled. This is because the crypto code in `Sun` is not `FIPS` certified. The `JKS` keystore is part of the `Sun` provider so I expect the above stack trace and failure is expected at this point.

@taoliult and @WilburZjh , let us know if you have thoughts otherwise.

**Comment by taoliult** [comment]
@JasonFengJ9 
The failures is due to "Caused by: java.security.NoSuchAlgorithmException: JKS KeyStore not available", it is an expected failure, because currently, the file based keystore is not supported in Semeru FIPS yet. 

@jasonkatonica @WilburZjh FYI.

**Comment by JasonFengJ9** [comment]
@jasonkatonica @taoliult Thanks for the clarification, posted a comment at https://github.com/eclipse-openj9/openj9/issues/16904#issuecomment-1496440539 if there is a list of providers/algorithms not FIPS certificated.

**Comment by pshipton** [comment]
The test can be excluded, see https://github.com/eclipse-openj9/openj9/issues/16904#issuecomment-1496459788

**Comment by paritkum** [comment]
Testcase was excluded for FIPS mode in PR [4576](https://github.com/adoptium/aqa-tests/pull/4576)
