### ISSUE TITLE
JDK8 FIPS javax/net/ssl/ServerName/EndingDotHostname.java NoSuchAlgorithmException: PBEWithSHA1AndDESede AlgorithmParameters not available

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16905]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux_fips/39/)(`rhel8x64-fips3-1`):
```
openjdk version "1.8.0_372"
IBM Semeru Runtime Open Edition (build 1.8.0_372-b03)
Eclipse OpenJ9 VM (build v0.38.0-release-25af2a240, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230309_612 (JIT enabled, AOT enabled)
OpenJ9   - 25af2a240
OMR      - 008f97b5c
JCL      - a1cfd8750f based on jdk8u372-b03)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=FIPS&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=3&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-jre_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-debugimage_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-testimage_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F612%2Fibm-semeru-open-jdk_x64_linux_8u372b03_openj9-0.38.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.38.0-release&amp;OPENJ9_BRANCH=v0.38.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.38.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-03-10T00:24:48.344Z] variation: Mode150
[2023-03-10T00:24:48.344Z] JVM_OPTIONS:  -XX:+UseCompressedOops  -Dsemeru.fips=true

[2023-03-10T00:26:33.418Z] TEST: javax/net/ssl/ServerName/EndingDotHostname.java

[2023-03-10T00:26:33.419Z] STDERR:
[2023-03-10T00:26:33.419Z] java.security.KeyStoreException: Key protection algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithSHA1AndDESede AlgorithmParameters not available
[2023-03-10T00:26:33.419Z] 	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:687)
[2023-03-10T00:26:33.419Z] 	at sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:587)
[2023-03-10T00:26:33.419Z] 	at java.security.KeyStore.setKeyEntry(KeyStore.java:1140)
[2023-03-10T00:26:33.419Z] 	at SSLExampleCert.createSSLContext(SSLExampleCert.java:353)
[2023-03-10T00:26:33.419Z] 	at SSLExampleCert.createServerSSLContext(SSLExampleCert.java:298)
[2023-03-10T00:26:33.419Z] 	at EndingDotHostname.doServerSide(EndingDotHostname.java:133)
[2023-03-10T00:26:33.419Z] 	at EndingDotHostname.lambda$startServer$0(EndingDotHostname.java:112)
[2023-03-10T00:26:33.419Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-03-10T00:26:33.419Z] Caused by: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithSHA1AndDESede AlgorithmParameters not available
[2023-03-10T00:26:33.419Z] 	at sun.security.pkcs12.PKCS12KeyStore.encryptPrivateKey(PKCS12KeyStore.java:918)
[2023-03-10T00:26:33.419Z] 	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:624)
[2023-03-10T00:26:33.419Z] 	... 7 more
[2023-03-10T00:26:33.419Z] Caused by: java.io.IOException: getPBEAlgorithmParameters failed: PBEWithSHA1AndDESede AlgorithmParameters not available
[2023-03-10T00:26:33.419Z] 	at sun.security.pkcs12.PKCS12KeyStore.getPBEAlgorithmParameters(PKCS12KeyStore.java:796)
[2023-03-10T00:26:33.419Z] 	at sun.security.pkcs12.PKCS12KeyStore.encryptPrivateKey(PKCS12KeyStore.java:888)
[2023-03-10T00:26:33.419Z] 	... 8 more
[2023-03-10T00:26:33.419Z] Caused by: java.security.NoSuchAlgorithmException: PBEWithSHA1AndDESede AlgorithmParameters not available
[2023-03-10T00:26:33.419Z] 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
[2023-03-10T00:26:33.419Z] 	at java.security.Security.getImpl(Security.java:714)
[2023-03-10T00:26:33.419Z] 	at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:146)
[2023-03-10T00:26:33.419Z] 	at sun.security.pkcs12.PKCS12KeyStore.getPBEAlgorithmParameters(PKCS12KeyStore.java:792)
[2023-03-10T00:26:33.419Z] 	... 9 more
[2023-03-10T00:26:33.419Z] 
[2023-03-10T00:26:33.419Z] JavaTest Message: Test threw exception: java.security.KeyStoreException: Key protection algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithSHA1AndDESede AlgorithmParameters not available

[2023-03-10T00:31:00.356Z] jdk_security3_0_FAILED
```

**Comment by jasonkatonica** [comment]
Hello @JasonFengJ9  , When executing with the flag `-Dsemeru.fips=true` set the `SunJCE` provider, and its associated cryptograhic algorithms, are all currently disabled. This is because the crypto code in `SunJCE` are not `FIPS` certified. The algorithm `PBEWithSHA1AndDESede` reported above is not a FIPS certified algorithm so this failure can be expected.

**Comment by pshipton** [comment]
@jasonkatonica pls arrange to have tests not applicable to FIPS excluded.

https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/test/ProblemList-fips.txt
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/ProblemList-fips.txt
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9/test/jdk/ProblemList-fips.txt

@llxia I assume adding to this exclude list is appropriate for extended.openjdk tests?
