### ISSUE TITLE
[FFI/Test] A nested case intended for the exception handling code in upcall method

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#16962]
As mentioned at https://github.com/eclipse-openj9/openj9/pull/16932#issuecomment-1476347858, we will add one test case to verify the nested exception case as follows:
```
callout
callin
callout
callin (throws an exception)
```
to ensure the stacking of the jump buffers is working well as expected.

FYI: @gacholio, @tajila, @pshipton

**Comment by ChengJin01** [comment]
Test case is created at https://github.com/ChengJin01/openj9/commit/e305ab8388958a8c2b820cf0ffdf19dff94f090f and verified on `Linux/x86_64` which works good as expected:
```
Exception in thread "main" java.lang.IllegalArgumentException: An exception is thrown from the upcall method
        at UpcallMethodHandles.add2IntStructs_returnStruct_throwException(UpcallMethodHandles.java:1313)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.invokeNative(Native Method)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.runNativeMethod(InternalDowncallHandler.java:539)
        at UpcallMethodHandles.add2IntStructs_returnStruct_nestedUpcall(UpcallMethodHandles.java:1325)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.invokeNative(Native Method)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.runNativeMethod(InternalDowncallHandler.java:539)
        at InvalidUpCallTests.test_nestedUpcall_throwExceptionFromUpcallMethod(InvalidUpCallTests.java:114)
        at InvalidUpCallTests.main(InvalidUpCallTests.java:65)
```
Will run personal builds in JDK17/19/20 (given all changes in JDK20+ were merged earlier today) to ensure there is no issue on all supported platforms.
