### ISSUE TITLE
JDK20 security/infra/java/security/cert/CertPathValidator/certification/ActalisCA.java java.security.cert.CertPathValidatorException: OCSP response error: UNAUTHORIZED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16966]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_aarch64_linux_Personal/1/consoleFull)(`ub18-aarch64-8`):
```
08:57:42  openjdk version "20-internal" 2023-03-21
08:57:42  OpenJDK Runtime Environment (build 20-internal-adhoc.jenkins.BuildJDK20aarch64linuxPersonal)
08:57:42  Eclipse OpenJ9 VM (build master-8cc902bc75f, JRE 20 Linux aarch64-64-Bit Compressed References 20230316_13 (JIT enabled, AOT enabled)
08:57:42  OpenJ9   - 8cc902bc75f
08:57:42  OMR      - 035ec68ec0c
08:57:42  JCL      - 10a35739269 based on jdk-20+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_io_0,jdk_io_1,jdk_other_0,jdk_other_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=3&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK20_aarch64_linux_Personal%2F13%2FOpenJ9-JDK20-aarch64_linux-20230316-081913.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK20_aarch64_linux_Personal%2F13%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=20&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk20.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=8cc902bc75ffa8e24f4beef2a1f8726a383771eb&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=034d4edd4350276a2d01aade526b242fb70f4eee&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
12:02:31  variation: Mode150
12:02:31  JVM_OPTIONS:  -XX:+UseCompressedOops 

12:02:54  TEST: security/infra/java/security/cert/CertPathValidator/certification/ActalisCA.java

12:02:54  certpath: X509CertSelector.match: subject DNs don't match
12:02:54  java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
12:02:54  	at ValidatePathWithParams.validate(ValidatePathWithParams.java:177)
12:02:54  	at ActalisCA.main(ActalisCA.java:221)
12:02:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
12:02:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
12:02:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
12:02:54  	at java.base/java.lang.Thread.run(Thread.java:1639)
12:02:54  Caused by: java.security.cert.CertPathValidatorException: OCSP response error: UNAUTHORIZED
12:02:54  	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
12:02:54  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
12:02:54  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
12:02:54  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
12:02:54  	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
12:02:54  	at ValidatePathWithParams.doCertPathValidate(ValidatePathWithParams.java:288)
12:02:54  	at ValidatePathWithParams.validate(ValidatePathWithParams.java:142)
12:02:54  	... 5 more
12:02:54  Caused by: java.security.cert.CertPathValidatorException: OCSP response error: UNAUTHORIZED
12:02:54  	at java.base/sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:390)
12:02:54  	at java.base/sun.security.provider.certpath.OCSP.check(OCSP.java:137)
12:02:54  	at java.base/sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:780)
12:02:54  	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:369)
12:02:54  	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:343)
12:02:54  	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
12:02:54  	... 11 more
12:02:54  
12:02:54  JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status

12:03:15  Test results: passed: 10; failed: 1
12:03:36  Report written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16789716238872/jdk_security_infra_0/report/html/report.html
12:03:36  Results written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16789716238872/jdk_security_infra_0/work
12:03:36  Error: Some tests failed or other problems occurred.
12:03:36  -----------------------------------
12:03:36  jdk_security_infra_0_FAILED
```

Also appeared in other platforms such as [x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_x86-64_linux_Personal/2/consoleFull) [s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_s390x_linux_Personal/1/consoleFull)

**Comment by pshipton** [comment]
@JasonFengJ9 does it also occur on a similar machine using an Adoptium OpenJDK build?

**Comment by pshipton** [comment]
There are nightly builds, see https://adoptium.net/temurin/nightly/?version=20

**Comment by JasonFengJ9** [comment]
[10x internal grinder in same machine](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31774/)

**Comment by pshipton** [comment]
Adoptium passed. That leaves `-Djdk.nativeCrypto=false` as the next obvious [thing to try](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31793/).

**Comment by pshipton** [comment]
This test and others are excluded for Adoptium builds.
https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk20.txt#L260-L267

The exclude for this test was added by https://github.com/adoptium/aqa-tests/pull/4433

I'm not sure why we

**Comment by pshipton** [comment]
This test does fail on a Adoptium build. https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2260/
```
13:59:24  certpath: connecting to OCSP service at: http://ocsp05.actalis.it/VA/AUTH-ROOT
13:59:24  certpath: OCSP response status: MALFORMED_REQUEST
13:59:24  certpath: X509CertSelector.match(SN: 3e8
13:59:24    Issuer: CN=Hongkong Post Root CA 1, O=Hongkong Post, C=HK
13:59:24    Subject: CN=Hongkong Post Root CA 1, O=Hongkong Post, C=HK)
13:59:24  certpath: X509CertSelector.match: subject DNs don't match
13:59:24  java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
13:59:24  	at ValidatePathWithParams.validate(ValidatePathWithParams.java:177)
13:59:24  	at ActalisCA.main(ActalisCA.java:212)
13:59:24  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
13:59:24  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
13:59:24  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
13:59:24  	at java.base/java.lang.Thread.run(Thread.java:1623)
13:59:24  Caused by: java.security.cert.CertPathValidatorException: OCSP response error: MALFORMED_REQUEST
13:59:24  	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
13:59:24  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
13:59:24  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
13:59:24  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
13:59:24  	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
13:59:24  	at ValidatePathWithParams.doCertPathValidate(ValidatePathWithParams.java:288)
13:59:24  	at ValidatePathWithParams.validate(ValidatePathWithParams.java:142)
13:59:24  	... 5 more
13:59:24  Caused by: java.security.cert.CertPathValidatorException: OCSP response error: MALFORMED_REQUEST
13:59:24  	at java.base/sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:390)
13:59:24  	at java.base/sun.security.provider.certpath.OCSP.check(OCSP.java:137)
13:59:24  	at java.base/sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:780)
13:59:24  	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:369)
13:59:24  	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:343)
13:59:24  	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
13:59:24  	... 11 more
```

**Comment by JasonFengJ9** [comment]
[JDK20 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_aarch64_linux/9/)(`rhel9-aarch64-2`)
```
[2023-05-28T01:33:21.528Z] variation: Mode150
[2023-05-28T01:33:21.528Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-05-28T01:33:40.137Z] TEST: security/infra/java/security/cert/CertPathValidator/certification/AmazonCA.java

[2023-05-28T01:33:40.140Z] certpath: Checking validity of OCSP response on Sat May 27 21:33:38 EDT 2023 with allowed interval between Sat May 27 21:18:38 EDT 2023 and Sat May 27 21:48:38 EDT 2023
[2023-05-28T01:33:40.140Z] java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate
[2023-05-28T01:33:40.140Z] 	at ValidatePathWithParams.validate(ValidatePathWithParams.java:193)
[2023-05-28T01:33:40.140Z] 	at AmazonCA_1.runTest(AmazonCA.java:173)
[2023-05-28T01:33:40.140Z] 	at AmazonCA.main(AmazonCA.java:64)
[2023-05-28T01:33:40.140Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-05-28T01:33:40.140Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-05-28T01:33:40.140Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-05-28T01:33:40.140Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-05-28T01:33:40.140Z] 
[2023-05-28T01:33:40.140Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate

[2023-05-28T01:33:40.140Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate
[2023-05-28T01:33:40.140Z] --------------------------------------------------
[2023-05-28T01:34:30.003Z] Test results: passed: 10; failed: 1
[2023-05-28T01:34:44.388Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16852095089750/jdk_security_infra_0/report/html/report.html
[2023-05-28T01:34:44.388Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16852095089750/jdk_security_infra_0/work
[2023-05-28T01:34:44.388Z] Error: Some tests failed or other problems occurred.
[2023-05-28T01:34:44.388Z] -----------------------------------
[2023-05-28T01:34:44.388Z] jdk_security_infra_0_FAILED
```
