### ISSUE TITLE
jdk20 java/lang/Thread/virtual/ThreadAPI.java IllegalMonitorStateException timeout 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16978]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/18
jdk_lang_0
java/lang/Thread/virtual/ThreadAPI.java#default

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/18/openjdk_test_output.tar.gz
```
00:05:18  ACTION: testng -- Error. Program `C:\Users\jenkins\workspace\Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1055712ms).
00:05:18  REASON: User specified action: run testng ThreadAPI 
00:05:18  TIME:   1055.73 seconds
00:05:18  messages:
00:05:18  command: testng ThreadAPI
00:05:18  reason: User specified action: run testng ThreadAPI 
00:05:18  started: Mon Mar 20 23:47:33 EDT 2023
00:05:18  Mode: othervm [test requires --enable-preview]
00:05:18  Additional options from @modules: --add-modules java.base --add-exports java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
00:05:18  Timeout information:
00:05:18  Running jcmd on process 3512
00:05:18  Dump written to C:\Users\jenkins\workspace\Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16793652123162\jdk_lang_0\work\scratch\0\core.20230321.000402.3512.0001.dmp
00:05:18  Dump written to C:\Users\jenkins\workspace\Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16793652123162\jdk_lang_0\work\scratch\0\javacore.20230321.000443.3512.0002.txt
00:05:18  Running jstack on process 3512
00:05:18  2023-03-21T00:04:44.389997400
00:05:18  Virtual machine: 3512 JVM information:
00:05:18  JRE 20 Windows Server 2012 R2 amd64-64-Bit Compressed References 20230320_19 (JIT enabled, AOT enabled)
00:05:18  OpenJ9   - c03c76e5071
00:05:18  OMR      - 1a20c5d2b24
00:05:18  JCL      - 58986cfd0fe based on jdk-20+36
00:05:18  
00:05:18  "main" prio=5 Id=2 WAITING
00:05:18  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
00:05:18  	at java.base@20-internal/java.lang.Thread.join(Thread.java:2147)
00:05:18  	at java.base@20-internal/java.lang.Thread.join(Thread.java:2223)
00:05:18  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:72)
00:05:18  
00:05:18  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
00:05:18  
00:05:18  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
00:05:18  
00:05:18  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
00:05:18  
00:05:18  "JIT Diagnostic Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
00:05:18  
00:05:18  "JIT-SamplerThread" prio=10 Id=8 TIMED_WAITING
00:05:18  
00:05:18  "IProfiler" prio=5 Id=9 RUNNABLE
00:05:18  
00:05:18  "Common-Cleaner" prio=8 Id=3 TIMED_WAITING
00:05:18  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
00:05:18  	at java.base@20-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
00:05:18  	at java.base@20-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
00:05:18  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
00:05:18  	at java.base@20-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
00:05:18  
00:05:18  "Concurrent Mark Helper" prio=1 Id=10 RUNNABLE
00:05:18  
00:05:18  "Finalizer thread" prio=5 Id=11 RUNNABLE
00:05:18  
00:05:18  "GC Worker" prio=5 Id=12 RUNNABLE
00:05:18  
00:05:18  "GC Worker" prio=5 Id=13 RUNNABLE
00:05:18  
00:05:18  "GC Worker" prio=5 Id=14 RUNNABLE
00:05:18  
00:05:18  "Attach API wait loop" prio=10 Id=17 TIMED_WAITING
00:05:18  	at java.base@20-internal/java.lang.Thread.sleepImpl(Native Method)
00:05:18  	at java.base@20-internal/java.lang.Thread.sleep0(Thread.java:496)
00:05:18  	at java.base@20-internal/java.lang.Thread.sleep(Thread.java:491)
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:142)
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
00:05:18  
00:05:18  "MainThread" prio=5 Id=19 TIMED_WAITING
00:05:18  	at java.base@20-internal/jdk.internal.misc.Unsafe.park(Native Method)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:756)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1126)
00:05:18  	at java.base@20-internal/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
00:05:18  	at java.base@20-internal/java.lang.VirtualThread.joinNanos(VirtualThread.java:815)
00:05:18  	at java.base@20-internal/java.lang.Thread.join(Thread.java:2261)
00:05:18  	at app//jdk.test.lib.thread.VThreadRunner.run(VThreadRunner.java:95)
00:05:18  	at app//jdk.test.lib.thread.VThreadRunner.run(VThreadRunner.java:143)
00:05:18  	at app//ThreadAPI.testJoin34(ThreadAPI.java:785)
00:05:18  	at java.base@20-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:05:18  	at java.base@20-internal/java.lang.reflect.Method.invoke(Method.java:578)
00:05:18  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
00:05:18  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
00:05:18  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
00:05:18  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
00:05:18  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
00:05:18  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
00:05:18  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
00:05:18  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
00:05:18  	at java.base@20-internal/java.util.ArrayList.forEach(ArrayList.java:1511)
00:05:18  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
00:05:18  	at app//org.testng.TestRunner.run(TestRunner.java:585)
00:05:18  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
00:05:18  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
00:05:18  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
00:05:18  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
00:05:18  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
00:05:18  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
00:05:18  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
00:05:18  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
00:05:18  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
00:05:18  	at app//org.testng.TestNG.run(TestNG.java:1037)
00:05:18  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
00:05:18  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
00:05:18  	at java.base@20-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:05:18  	at java.base@20-internal/java.lang.reflect.Method.invoke(Method.java:578)
00:05:18  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
00:05:18  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
00:05:18  
00:05:18  "SeedGenerator Thread" prio=1 Id=20 WAITING
00:05:18  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:192)
00:05:18  	at java.base@20-internal/sun.security.provider.SeedGenerator$ThreadedSeedGenerator.run(SeedGenerator.java:334)
00:05:18  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
00:05:18  
00:05:18  "ForkJoinPool-1-worker-1" prio=5 Id=127 WAITING
00:05:18  	at java.base@20-internal/jdk.internal.vm.Continuation.enterImpl(Native Method)
00:05:18  	at java.base@20-internal/jdk.internal.vm.Continuation.run(Continuation.java:198)
00:05:18  	at java.base@20-internal/java.lang.VirtualThread.runContinuation(VirtualThread.java:221)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
00:05:18  
00:05:18  "ForkJoinPool-1-worker-2" prio=5 Id=128 WAITING
00:05:18  	at java.base@20-internal/jdk.internal.vm.Continuation.enterImpl(Native Method)
00:05:18  	at java.base@20-internal/jdk.internal.vm.Continuation.run(Continuation.java:198)
00:05:18  	at java.base@20-internal/java.lang.VirtualThread.runContinuation(VirtualThread.java:221)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
00:05:18  
00:05:18  "ForkJoinPool-1-worker-3" prio=5 Id=129 WAITING
00:05:18  	at java.base@20-internal/jdk.internal.misc.Unsafe.park(Native Method)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
00:05:18  
00:05:18  "ForkJoinPool-1-worker-4" prio=5 Id=130 WAITING
00:05:18  	at java.base@20-internal/jdk.internal.misc.Unsafe.park(Native Method)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
00:05:18  
00:05:18  "VirtualThread-unparker" prio=5 Id=134 WAITING
00:05:18  	at java.base@20-internal/jdk.internal.misc.Unsafe.park(Native Method)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1718)
00:05:18  	at java.base@20-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1170)
00:05:18  	at java.base@20-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
00:05:18  	at java.base@20-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
00:05:18  	at java.base@20-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
00:05:18  	at java.base@20-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
00:05:18  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
00:05:18  	at java.base@20-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
00:05:18  
00:05:18  "Thread-2" prio=5 Id=205 WAITING
00:05:18  	at java.base@20-internal/jdk.internal.misc.Unsafe.park(Native Method)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
00:05:18  	at java.base@20-internal/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
00:05:18  	at java.base@20-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
00:05:18  	at java.base@20-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1170)
00:05:18  	at java.base@20-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
00:05:18  	at java.base@20-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
00:05:18  	at java.base@20-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
00:05:18  	at java.base@20-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
00:05:18  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
00:05:18  
00:05:18  "file lock watchdog" prio=10 Id=281 TIMED_WAITING
00:05:18  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
00:05:18  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
00:05:18  	at java.base@20-internal/java.util.TimerThread.mainLoop(Timer.java:569)
00:05:18  	at java.base@20-internal/java.util.TimerThread.run(Timer.java:522)
00:05:18  
00:05:18  "Attachment portNumber: 57776" prio=10 Id=284 RUNNABLE
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
00:05:18  	at java.base@20-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
00:05:18  
00:05:18  
00:05:18  --- Timeout information end.
00:05:18  finished: Tue Mar 21 00:05:09 EDT 2023
00:05:18  elapsed time (seconds): 1055.73
00:05:18  configuration:
00:05:18  Boot Layer
00:05:18    add modules: java.base           
00:05:18    add exports: java.base/java.lang ALL-UNNAMED
00:05:18    add opens:   java.base/java.lang ALL-UNNAMED
00:05:18  
00:05:18  STDOUT:
00:05:18  config ThreadAPI.setUp(): success
00:05:18  test ThreadAPI.testContextClassLoader1(): success
00:05:18  test ThreadAPI.testContextClassLoader2(): success
00:05:18  test ThreadAPI.testContextClassLoader3(): success
00:05:18  test ThreadAPI.testContextClassLoader4(): success
00:05:18  test ThreadAPI.testContextClassLoader5(): success
00:05:18  test ThreadAPI.testContextClassLoader6(): success
00:05:18  test ThreadAPI.testCurrentThread1(): success
00:05:18  test ThreadAPI.testCurrentThread2(): success
00:05:18  test ThreadAPI.testCurrentThread3(): success
00:05:18  test ThreadAPI.testEnumerate1(): success
00:05:18  test ThreadAPI.testEnumerate2(): success
00:05:18  test ThreadAPI.testEqualsAndHashCode(): success
00:05:18  test ThreadAPI.testGetAllStackTraces1(): success
00:05:18  test ThreadAPI.testGetAllStackTraces2(): success
00:05:18  test ThreadAPI.testGetStackTrace1(): success
00:05:18  test ThreadAPI.testGetStackTrace2(): success
00:05:18  test ThreadAPI.testGetStackTrace3(): success
00:05:18  test ThreadAPI.testGetStackTrace4(): success
00:05:18  test ThreadAPI.testGetStackTrace5(): success
00:05:18  test ThreadAPI.testGetStackTrace6(): success
00:05:18  test ThreadAPI.testGetState1(): success
00:05:18  test ThreadAPI.testGetState2(): success
00:05:18  test ThreadAPI.testGetState3(): success
00:05:18  test ThreadAPI.testGetState4(): success
00:05:18  test ThreadAPI.testGetState5(): success
00:05:18  test ThreadAPI.testGetState6(): success
00:05:18  test ThreadAPI.testGetState7(): success
00:05:18  test ThreadAPI.testGetState8(): success
00:05:18  test ThreadAPI.testHoldsLock1(): success
00:05:18  test ThreadAPI.testHoldsLock2(): success
00:05:18  test ThreadAPI.testInterrupt1(): success
00:05:18  test ThreadAPI.testInterrupt10(): success
00:05:18  test ThreadAPI.testInterrupt2(): success
00:05:18  test ThreadAPI.testInterrupt3(): success
00:05:18  test ThreadAPI.testInterrupt4(): success
00:05:18  test ThreadAPI.testInterrupt5(): success
00:05:18  test ThreadAPI.testInterrupt6(): success
00:05:18  test ThreadAPI.testInterrupt7(): success
00:05:18  test ThreadAPI.testInterrupt8(): success
00:05:18  test ThreadAPI.testInterrupt9(): success
00:05:18  test ThreadAPI.testIsAlive1(): success
00:05:18  test ThreadAPI.testJoin1(): success
00:05:18  test ThreadAPI.testJoin11(): success
00:05:18  test ThreadAPI.testJoin12(): success
00:05:18  test ThreadAPI.testJoin13(): success
00:05:18  test ThreadAPI.testJoin14(): success
00:05:18  test ThreadAPI.testJoin15(): success
00:05:18  test ThreadAPI.testJoin16(): success
00:05:18  test ThreadAPI.testJoin17(): success
00:05:18  test ThreadAPI.testJoin18(): success
00:05:18  test ThreadAPI.testJoin19(): success
00:05:18  test ThreadAPI.testJoin2(): success
00:05:18  test ThreadAPI.testJoin20(): success
00:05:18  test ThreadAPI.testJoin21(): success
00:05:18  test ThreadAPI.testJoin22(): success
00:05:18  test ThreadAPI.testJoin23(): success
00:05:18  test ThreadAPI.testJoin24(): success
00:05:18  test ThreadAPI.testJoin25(): success
00:05:18  test ThreadAPI.testJoin26(): success
00:05:18  test ThreadAPI.testJoin27(): success
00:05:18  test ThreadAPI.testJoin28(): success
00:05:18  test ThreadAPI.testJoin29(): success
00:05:18  test ThreadAPI.testJoin3(): success
00:05:18  test ThreadAPI.testJoin30(): success
00:05:18  test ThreadAPI.testJoin31(): success
00:05:18  test ThreadAPI.testJoin32(): success
00:05:18  test ThreadAPI.testJoin33(): failure
00:05:18  java.lang.AssertionError: expected [false] but found [true]
00:05:18  	at org.testng.Assert.fail(Assert.java:99)
00:05:18  	at org.testng.Assert.failNotEquals(Assert.java:1037)
00:05:18  	at org.testng.Assert.assertFalse(Assert.java:67)
00:05:18  	at org.testng.Assert.assertFalse(Assert.java:77)
00:05:18  	at ThreadAPI.testJoin33(ThreadAPI.java:770)

00:05:18  STDERR:
00:05:18  Exception in thread "" java.lang.IllegalMonitorStateException
00:05:18  	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:175)
00:05:18  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1059)
00:05:18  	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:494)
00:05:18  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.remove(ScheduledThreadPoolExecutor.java:1063)
00:05:18  	at java.base/java.util.concurrent.ThreadPoolExecutor.remove(ThreadPoolExecutor.java:1777)
00:05:18  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.cancel(ScheduledThreadPoolExecutor.java:293)
00:05:18  	at java.base/java.lang.VirtualThread.cancel(VirtualThread.java:676)
00:05:18  	at java.base/java.lang.VirtualThread.parkNanos(VirtualThread.java:608)
00:05:18  	at java.base/java.lang.Access.parkVirtualThread(Access.java:519)
00:05:18  	at java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:67)
00:05:18  	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:408)
00:05:18  	at ThreadAPI.lambda$testJoin33$37(ThreadAPI.java:765)
00:05:18  	at java.base/java.lang.VirtualThread.run(VirtualThread.java:310)
00:05:18  	at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:182)
00:05:18  	at java.base/jdk.internal.vm.Continuation.enter(Continuation.java:170)
```

Possible dup of https://github.com/eclipse-openj9/openj9/issues/16258
an earlier failure was reported at https://github.com/eclipse-openj9/openj9/issues/16258#issuecomment-1458258769

**Comment by vij-singh** [comment]
@pshipton Does this still occur now that #16258 has been resolved?

**Comment by pshipton** [comment]
I can't be sure, it's intermittent. I'll close it and reopen later if I see it again.
