### ISSUE TITLE
IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16989]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.system_aarch64_linux_Nightly_testList_0/19
LambdaLoadTest_J9_5m_0 `-Xjit -Xgcpolicy:gencon -Xnocompressedrefs`

```
LT  testFailure: testStaticLambda(net.adoptopenjdk.test.lambda.TestLambdaContexts): argument type mismatch
LT  java.lang.IllegalArgumentException: argument type mismatch
LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
LT  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
LT  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
LT  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
LT  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
LT  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
LT  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
LT  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
LT  	at java.base/java.lang.Thread.run(Thread.java:1639)

LT  testFailure: testArrayInitializer(net.adoptopenjdk.test.lambda.TestLambdaContexts): argument type mismatch
LT  java.lang.IllegalArgumentException: argument type mismatch
LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
LT  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
LT  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
LT  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
LT  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
LT  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
LT  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
LT  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
LT  	at java.base/java.lang.Thread.run(Thread.java:1639)

... etc
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_special.system_aarch64_linux_Release_testList_0/6
MathLoadTest_all_special_5m_4 `-Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs`

```
MLT testFailure: testItem_0497(net.adoptopenjdk.test.bigdecimal.TestSuite006): argument type mismatch
MLT java.lang.IllegalArgumentException: argument type mismatch
MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
...
MLT testFailure: testItem_0498(net.adoptopenjdk.test.bigdecimal.TestSuite006): argument type mismatch
MLT java.lang.IllegalArgumentException: argument type mismatch
MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
...
etc.
```

**Comment by pshipton** [comment]
@knn-k fyi

**Comment by knn-k** [comment]
[20x Grinder job](https://openj9-jenkins.osuosl.org/job/Grinder/2554/) for MathLoadTest_all_special_5m_4 did not fail.

**Comment by knn-k** [comment]
[30x Grinder job](https://openj9-jenkins.osuosl.org/job/Grinder/2571/) did not fail.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_special.system_aarch64_linux_Release_testList_4/14
MathLoadTest_all_special_5m_1 `-Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs`
```
11:22:29  MLT testFailure: testItem_0065(net.adoptopenjdk.test.bigdecimal.TestSuite044): argument type mismatch
11:22:29  MLT java.lang.IllegalArgumentException: argument type mismatch
11:22:29  MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
11:22:29  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
11:22:29  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
11:22:29  MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
11:22:29  MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
11:22:29  MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
11:22:29  MLT 	at junit.framework.TestResult.run(TestResult.java:125)
11:22:29  MLT 	at junit.framework.TestCase.run(TestCase.java:129)
11:22:29  MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
11:22:29  MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
11:22:29  MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
```

**Comment by JasonFengJ9** [comment]
[openjdk23_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk23_j9_special.system_aarch64_mac_testList_3/44/)(`macaarch64rt1`)
```
[2024-10-27T08:25:15.918Z] variation: Mode103
[2024-10-27T08:25:15.918Z] JVM_OPTIONS:  -Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs 

[2024-10-27T08:28:08.511Z] MLT testStarted : testItem_0999(net.adoptopenjdk.test.bigdecimal.TestSuite009)
[2024-10-27T08:28:08.511Z] MLT testFailure: testItem_0999(net.adoptopenjdk.test.bigdecimal.TestSuite009): argument type mismatch
[2024-10-27T08:28:08.511Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2024-10-27T08:28:08.511Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
[2024-10-27T08:28:08.511Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestResult.run(TestResult.java:125)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestCase.run(TestCase.java:129)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2024-10-27T08:28:08.511Z] MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2024-10-27T08:28:08.511Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2024-10-27T08:28:08.511Z] MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2024-10-27T08:28:08.511Z] MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2024-10-27T08:28:08.511Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-10-27T08:28:08.511Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-10-27T08:28:08.511Z] MLT 	at java.base/java.lang.Thread.run(Thread.java:1587)
[2024-10-27T08:28:08.511Z] MLT testFinished: testItem_0999(net.adoptopenjdk.test.bigdecimal.TestSuite009)
[2024-10-27T08:28:08.511Z] MLT 
[2024-10-27T08:28:08.511Z] MLT JUnit Test Results for: net.adoptopenjdk.test.bigdecimal.TestSuite009
[2024-10-27T08:28:08.511Z] MLT   Ran    : 923
[2024-10-27T08:28:08.511Z] MLT   Passed : 533
[2024-10-27T08:28:08.511Z] MLT   Failed : 390
[2024-10-27T08:28:08.511Z] MLT   Ignored: 0
[2024-10-27T08:28:08.511Z] MLT   Result : FAILED

[2024-10-27T08:28:09.435Z] MLT 04:28:08.671 - Load test completed
[2024-10-27T08:28:09.435Z] MLT 04:28:08.671 -   Ran     : 12145
[2024-10-27T08:28:09.435Z] MLT 04:28:08.671 -   Passed  : 12133
[2024-10-27T08:28:09.435Z] MLT 04:28:08.671 -   Failed  : 12
[2024-10-27T08:28:09.435Z] MLT 04:28:08.671 -   Result  : FAILED

[2024-10-27T08:28:09.916Z] MathLoadTest_all_special_5m_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44497/)

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.system_aarch64_mac_testList_1/230/)(`macaarch64rt2`)
```
[2024-10-29T19:20:52.281Z] variation: Mode103
[2024-10-29T19:20:52.281Z] JVM_OPTIONS:  -Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs 

[2024-10-29T19:24:49.428Z] MLT testFailure: testItem_0999(net.adoptopenjdk.test.bigdecimal.TestSuite015): argument type mismatch
[2024-10-29T19:24:49.428Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2024-10-29T19:24:49.428Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
[2024-10-29T19:24:49.428Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-10-29T19:24:49.428Z] MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
[2024-10-29T19:24:49.428Z] MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
[2024-10-29T19:24:49.429Z] MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-10-29T19:24:49.429Z] MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-10-29T19:24:49.429Z] MLT 	at junit.framework.TestResult.run(TestResult.java:125)
[2024-10-29T19:24:49.429Z] MLT 	at junit.framework.TestCase.run(TestCase.java:129)
[2024-10-29T19:24:49.429Z] MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2024-10-29T19:24:49.429Z] MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2024-10-29T19:24:49.429Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2024-10-29T19:24:49.429Z] MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2024-10-29T19:24:49.429Z] MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2024-10-29T19:24:49.429Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-10-29T19:24:49.429Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-10-29T19:24:49.430Z] MLT 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-10-29T19:24:49.430Z] MLT testFinished: testItem_0999(net.adoptopenjdk.test.bigdecimal.TestSuite015)
[2024-10-29T19:24:49.430Z] MLT 
[2024-10-29T19:24:49.430Z] MLT JUnit Test Results for: net.adoptopenjdk.test.bigdecimal.TestSuite015
[2024-10-29T19:24:49.430Z] MLT   Ran    : 939
[2024-10-29T19:24:49.430Z] MLT   Passed : 0
[2024-10-29T19:24:49.430Z] MLT   Failed : 939
[2024-10-29T19:24:49.430Z] MLT   Ignored: 0
[2024-10-29T19:24:49.430Z] MLT   Result : FAILED
[2024-10-29T19:24:49.430Z] MLT <<<

[2024-10-29T19:24:50.162Z] MathLoadTest_all_special_5m_1_FAILED
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44570/)

**Comment by JasonFengJ9** [comment]
[openjdk23_j9_special.system_aarch64_mac milestone build 2](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk23_j9_special.system_aarch64_mac_testList_2/77/)(`macaarch64rt1`)
```
[2024-12-24T21:22:54.876Z] variation: Mode110-OSRG
[2024-12-24T21:22:54.876Z] JVM_OPTIONS:  -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation -Xgcpolicy:gencon 

[2024-12-24T21:24:48.571Z] MLT testStarted : testItem_0931(net.adoptopenjdk.test.bigdecimal.TestSuite006)
[2024-12-24T21:24:48.571Z] MLT testFailure: testItem_0931(net.adoptopenjdk.test.bigdecimal.TestSuite006): argument type mismatch
[2024-12-24T21:24:48.571Z] MLT java.lang.IllegalArgumentException: argument type mismatch
[2024-12-24T21:24:48.571Z] MLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:107)
[2024-12-24T21:24:48.571Z] MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestResult.run(TestResult.java:125)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestCase.run(TestCase.java:129)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2024-12-24T21:24:48.571Z] MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2024-12-24T21:24:48.571Z] MLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2024-12-24T21:24:48.572Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2024-12-24T21:24:48.572Z] MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2024-12-24T21:24:48.572Z] MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2024-12-24T21:24:48.572Z] MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2024-12-24T21:24:48.572Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-12-24T21:24:48.572Z] MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-12-24T21:24:48.572Z] MLT 	at java.base/java.lang.Thread.run(Thread.java:1587)

[2024-12-24T21:24:49.452Z] MathLoadTest_all_special_5m_25_FAILED
```
50x grinder - https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/46212/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_special.system_aarch64_mac_Release_testList_4/1/
MathLoadTest_all_special_5m_4

**Comment by knn-k** [comment]
All the failures were reported from jobs with non-compressed refs so far.  That could be a clue.

**Comment by knn-k** [comment]
I ran a Grinder job for 40x MathLoadTest_all_special_5m_4 on AArch64 macOS, but the failure was not reproduced: https://openj9-jenkins.osuosl.org/job/Grinder/4511/
Started one more job.

**Comment by knn-k** [comment]
IllegalArgumentException did not happen in another job.  It failed (1/40) with a SEGV in `OMR::CodeCache::replaceTrampoline()` instead.
https://openj9-jenkins.osuosl.org/job/Grinder/4512/

**Comment by knn-k** [comment]
MathLoadTest_all_special_5m_4 failed with IllegalArgumentException in yet another Grinder job (1/40).
My attempt to dump upon exception seems to have failed.
https://openj9-jenkins.osuosl.org/job/Grinder/4515/

**Comment by knn-k** [comment]
One of the iterations in https://openj9-jenkins.osuosl.org/job/Grinder/4515/ started to fail in net.adoptopenjdk.test.bigdecimal.TestSuite047.testItem_0172, and 705 tests in TestSuite047 failed.
The JIT verbose log shows the following method was compiled between `net/adoptopenjdk/test/bigdecimal/TestSuite047.testItem_0171()V` and `net/adoptopenjdk/test/bigdecimal/TestSuite047.testItem_0172()V`.

```
+ (warm) java/math/BigDecimal.multiplyAndRound(Ljava/math/BigInteger;Ljava/math/BigInteger;ILjava/math/MathContext;)Ljava/math/BigDecimal; @ 0000000111EF945C-0000000111EF95B0 OrdinaryMethod - Q_SZ=6 Q_SZI=6 QW=42 j9m=0000000129737E88 bcsz=11 sync GCR compThreadID=0 CpuLoad=0%(0%avg) JvmCpu=102%
```

**Comment by knn-k** [comment]
Other Grinder jobs showed that the method `java/math/BigDecimal.multiplyAndRound()` was not the trigger of the failures.

- https://openj9-jenkins.osuosl.org/job/Grinder/4536/ - Tests started to fail from TestSuite059.testItem_0032, but `BigDecimal.multiplyAndRound()` was not compiled around that.
- https://openj9-jenkins.osuosl.org/job/Grinder/4532/ - `BigDecimal.multiplyAndRound()` is excluded from JIT compilation, but tests started to fail from TestSuite051.testItem_0035.

**Comment by knn-k** [comment]
MathLoadTest_all_special_5m_4 using a recent nightly build of JDK 21 for AArch64 macOS:
- https://openj9-jenkins.osuosl.org/job/Grinder/4603/ Failed 1/40 with a SEGV in OMR::CodeCache::replaceTrampoline()
- https://openj9-jenkins.osuosl.org/job/Grinder/4604/ Failed 1/40 with a SEGV in OMR::CodeCache::replaceTrampoline()

**Comment by knn-k** [comment]
`entry` is a NULL when the SEGV is thrown in `OMR::CodeCache::replaceTrampoline()` in Grinder 4604 above.  That means `_resolvedMethodHT->findResolvedMethod(method)` returned a NULL.
It looks similar to #12128 and #12120.

There is an assertion that is commented out in `replaceTrampoline()`:
https://github.com/eclipse-omr/omr/blob/b6b39532582507fc55a0aab3bbd5d97498bca5c4/compiler/runtime/OMRCodeCache.cpp#L552
```
// TR_ASSERT(entry);
```

`newTargetPC` passed to `replaceTrampoline()` is 0x1211A306C saved in `x19`, and it points to the following method:
```
start=0x1211a306c  end=0x1211a3118   java/lang/invoke/LambdaForm$MH/0x0000000037c31620::invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_special.system_aarch64_mac_Personal_testList_1/5
DaaLoadTest_all_special_5m_1 `-Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs`
```
23:50:51  DLT java.lang.IllegalArgumentException: argument type mismatch
23:50:51  DLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:108)
23:50:51  DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
23:50:51  DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
23:50:51  DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
23:50:51  DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
23:50:51  DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
23:50:51  DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
23:50:51  DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
```

**Comment by knn-k** [comment]
Grinder job (30x) finished successfully: https://openj9-jenkins.osuosl.org/job/Grinder/4822/

**Comment by knn-k** [comment]
One more 30x Grinder job passed: https://openj9-jenkins.osuosl.org/job/Grinder/4824/

**Comment by hzongaro** [comment]
@nbhuiyan, may I ask you to take a look at this?  It looks like it might be related to Method Handles support, and it might be a duplicate of #15553.
