### ISSUE TITLE
cmdLineTester_criu_nonPortableRestore_5 Envvar test2 timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16980]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_aot_Personal_testList_0/150
cmdLineTester_criu_nonPortableRestore_5 `-Xgcpolicy:gencon -Xgcthreads64 -XX:CheckpointGCThreads=1`
AOT ITERATION 1

```
Testing: Envvar test2
Test start time: 2023/03/21 08:04:38 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_aot_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_aot_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_aot_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xgcpolicy:gencon -Xgcthreads64 -XX:CheckpointGCThreads=1 " org.openj9.criu.EnvVarFileTest EnvVarFileTest2 1
Time spent starting: 1 milliseconds
***[TEST INFO 2023/03/21 08:09:38] ProcessKiller detected a timeout after 300000 milliseconds!***
INFO: Cannot find '/usr/bin/gdb' using 'gdb' from the path.
***[TEST INFO 2023/03/21 08:09:38] executing gdb -batch -x /tmp/debugger8262968094989562924.txt bash 44303***
java.io.IOException: Cannot run program "gdb": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:697)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:646)
	at Test$ProcessKiller.run(Test.java:596)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 6 more
***[TEST INFO 2023/03/21 08:09:38] executing kill -ABRT 44303***
Time spent executing: 300036 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on

***[TEST INFO 2023/03/21 08:09:38] kill -ABRT signal sent***
***[TEST INFO 2023/03/21 08:09:38] ABRT completed***
Output from test:
```

@tajila

**Comment by tajila** [comment]
20 run grinder https://openj9-jenkins.osuosl.org/job/Grinder/2095/

**Comment by tajila** [comment]
This may also be fixed, Im not so certain though

**Comment by pshipton** [comment]
If we can fix the other frequent criu failures, it will be easier to see if issues like this one remain.
