### ISSUE TITLE
[Bug report] memoryPoolMXBean.getUsage will throw exception when gcpolicy is balanced

### ISSUE THREAD

**Issue by xiangtianyu** [eclipse-openj9/openj9#17005]
Java -version output
--------------------
I tried several versions and have the same problem.

```
openjdk version "17.0.4.1-ea" 2022-08-12
IBM Semeru Runtime Open Edition 17.0.4.1 (build 17.0.4.1-ea+1)
Eclipse OpenJ9 VM 17.0.4.1 (build openj9-0.33.1, JRE 17 Mac OS X aarch64-64-Bit 20220811_122 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - 1f4d354e654 based on jdk-17.0.4.1+1)

```
```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b07)
Eclipse OpenJ9 VM (build v0.36.0-release-c5da55ccc, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20230113_599 (JIT enabled, AOT enabled)
OpenJ9   - c5da55ccc
OMR      - 2bb04132e
JCL      - 1a94e3037e based on jdk8u362-b07)
```

Output from `java -version`.
If the shas are not public, include equivalent public shas.

Summary of problem
------------------

```java
public static void main(String[] args) {
    List<MemoryPoolMXBean> memoryPoolMXBeans = ManagementFactory.getMemoryPoolMXBeans();

    for (MemoryPoolMXBean memoryPoolMXBean : memoryPoolMXBeans) {
        memoryPoolMXBean.getUsage();
    }
}
```
It's a simple demo, but if i run it using openj9 and with vm args '-Xgcpolicy:balanced', it will throw exception like this :

```
Exception in thread "main" java.lang.IllegalArgumentException: init argument cannot be less than -1
	at java.lang.management.MemoryUsage.<init>(MemoryUsage.java:94)
	at com.ibm.java.lang.management.internal.MemoryPoolMXBeanImpl.getUsageImpl(Native Method)
	at com.ibm.java.lang.management.internal.MemoryPoolMXBeanImpl.getUsage(MemoryPoolMXBeanImpl.java:235)
	at org.example.openj9.Test.main(Test.java:12)
```

If i use the 'gencon policy', it's ok.

Is this a bug?

**Comment by pshipton** [comment]
@dmitripivkine @LinHu2016 pls take a look.

**Comment by dmitripivkine** [comment]
Thank you for reporting. This is duplicate of https://github.com/eclipse-openj9/openj9/issues/16413
