### ISSUE TITLE
jdk20 ProviderMismatchException when running javac

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17008]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/20/
jdk_lang_1
java/lang/Package/bootclasspath/GetPackageFromBootClassPath.java
```
21:56:50  ACTION: driver -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: compilation fails
21:56:50  REASON: User specified action: run driver GetPackageFromBootClassPath setup 
21:56:50  TIME:   0.76 seconds
21:56:50  messages:
21:56:50  command: driver GetPackageFromBootClassPath setup
21:56:50  reason: User specified action: run driver GetPackageFromBootClassPath setup 
21:56:50  started: Wed Mar 22 21:56:47 EDT 2023
21:56:50  Mode: agentvm
21:56:50  Agent id: 9
21:56:50  finished: Wed Mar 22 21:56:48 EDT 2023
21:56:50  elapsed time (seconds): 0.76
21:56:50  configuration:
21:56:50  Boot Layer
21:56:50    class path: /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar 
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar 
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/junit-platform-console-standalone-1.8.2.jar 
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng-7.3.0.jar 
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/guice-4.2.3.jar 
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander-1.78.jar 
21:56:50    patch:      java.base /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/patches/java.base
21:56:50  
21:56:50  Test Layer
21:56:50    class path: /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/java/lang/Package/bootclasspath/GetPackageFromBootClassPath.d
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Package/bootclasspath
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/test/lib
21:56:50                /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib
21:56:50  
21:56:50  rerun:
21:56:50  cd /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/scratch/0 && \
21:56:50  DISPLAY=:0 \
21:56:50  HOME=/home/jenkins \
21:56:50  LANG=en_US.UTF-8 \
21:56:50  PATH=/bin:/usr/bin:/usr/sbin \
21:56:50      /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
21:56:50          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops' \
21:56:50          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-XX:-UseCompressedOops' \
21:56:50          -Dtest.compiler.opts= \
21:56:50          -Dtest.java.opts= \
21:56:50          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image \
21:56:50          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image \
21:56:50          -Dtest.timeout.factor=8.0 \
21:56:50          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
21:56:50          -Dtest.root=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
21:56:50          -Dtest.name=java/lang/Package/bootclasspath/GetPackageFromBootClassPath.java \
21:56:50          -Dtest.file=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Package/bootclasspath/GetPackageFromBootClassPath.java \
21:56:50          -Dtest.src=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Package/bootclasspath \
21:56:50          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Package/bootclasspath:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib \
21:56:50          -Dtest.classes=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/java/lang/Package/bootclasspath/GetPackageFromBootClassPath.d \
21:56:50          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/java/lang/Package/bootclasspath/GetPackageFromBootClassPath.d:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/test/lib \
21:56:50          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/java/lang/Package/bootclasspath/GetPackageFromBootClassPath.d:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Package/bootclasspath:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/test/lib \
21:56:50          -Dtest.modules=jdk.compiler \
21:56:50          -classpath /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/java/lang/Package/bootclasspath/GetPackageFromBootClassPath.d:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Package/bootclasspath:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16795357794475/jdk_lang_1/work/classes/0/test/lib:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
21:56:50          GetPackageFromBootClassPath setup
21:56:50  STDERR:
21:56:50  An exception has occurred in the compiler (20-internal). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com/) after checking the Bug Database (https://bugs.java.com/) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
21:56:50  java.nio.file.ProviderMismatchException
21:56:50  	at java.base/sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:175)
21:56:50  	at java.base/sun.nio.fs.UnixFileSystemProvider.getFileAttributeView(UnixFileSystemProvider.java:142)
21:56:50  	at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileAttributeView(LinuxFileSystemProvider.java:68)
21:56:50  	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
21:56:50  	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
21:56:50  	at java.base/java.nio.file.Files.readAttributes(Files.java:1848)
21:56:50  	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.maybeReadAttributes(CacheFSInfo.java:110)
21:56:50  	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
21:56:50  	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.getAttributes(CacheFSInfo.java:105)
21:56:50  	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.isFile(CacheFSInfo.java:89)
21:56:50  	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getContainer(JavacFileManager.java:300)
21:56:50  	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForInput(JavacFileManager.java:858)
21:56:50  	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getJavaFileForInput(JavacFileManager.java:832)
21:56:50  	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:285)
21:56:50  	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModuleInfo(ModuleFinder.java:363)
21:56:50  	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findAllModules(ModuleFinder.java:191)
21:56:50  	at jdk.compiler/com.sun.tools.javac.comp.Modules.getUnnamedModuleCompleter(Modules.java:1449)
21:56:50  	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:473)
21:56:50  	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:267)
21:56:50  	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:233)
21:56:50  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1035)
21:56:50  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
21:56:50  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
21:56:50  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
21:56:50  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
21:56:50  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
21:56:50  	at jdk.test.lib.compiler.CompilerUtils.compile(CompilerUtils.java:122)
21:56:50  	at jdk.test.lib.compiler.CompilerUtils.compile(CompilerUtils.java:69)
21:56:50  	at GetPackageFromBootClassPath.setupBootLib(GetPackageFromBootClassPath.java:63)
21:56:50  	at GetPackageFromBootClassPath.main(GetPackageFromBootClassPath.java:44)
21:56:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
21:56:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
21:56:50  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
21:56:50  	at java.base/java.lang.Thread.run(Thread.java:1639)
21:56:50  java.lang.RuntimeException: compilation fails
21:56:50  	at GetPackageFromBootClassPath.setupBootLib(GetPackageFromBootClassPath.java:64)
21:56:50  	at GetPackageFromBootClassPath.main(GetPackageFromBootClassPath.java:44)
21:56:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
21:56:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
21:56:50  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
21:56:50  	at java.base/java.lang.Thread.run(Thread.java:1639)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_s390x_linux_OpenJDK20/3

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_linux_Nightly/66
jdk_lang_j9_0
java/lang/Package/bootclasspath/GetPackageFromBootClassPath.java
```
22:45:42  STDERR:
22:45:42  An exception has occurred in the compiler (20.0.1-internal). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com/) after checking the Bug Database (https://bugs.java.com/) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
22:45:42  java.nio.file.ProviderMismatchException
22:45:42  	at java.base/sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:175)
22:45:42  	at java.base/sun.nio.fs.UnixFileSystemProvider.getFileAttributeView(UnixFileSystemProvider.java:142)
22:45:42  	at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileAttributeView(LinuxFileSystemProvider.java:68)
22:45:42  	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
22:45:42  	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
22:45:42  	at java.base/java.nio.file.Files.readAttributes(Files.java:1848)
22:45:42  	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.maybeReadAttributes(CacheFSInfo.java:110)
22:45:42  	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
22:45:42  	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.getAttributes(CacheFSInfo.java:105)
22:45:42  	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.isFile(CacheFSInfo.java:89)
22:45:42  	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getContainer(JavacFileManager.java:300)
22:45:42  	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForInput(JavacFileManager.java:858)
22:45:42  	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getJavaFileForInput(JavacFileManager.java:832)
22:45:42  	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:285)
22:45:42  	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModuleInfo(ModuleFinder.java:363)
22:45:42  	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findAllModules(ModuleFinder.java:191)
22:45:42  	at jdk.compiler/com.sun.tools.javac.comp.Modules.getUnnamedModuleCompleter(Modules.java:1449)
22:45:42  	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:473)
22:45:42  	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:267)
22:45:42  	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:233)
22:45:42  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1035)
22:45:42  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
22:45:42  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
22:45:42  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
22:45:42  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
22:45:42  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
22:45:42  	at jdk.test.lib.compiler.CompilerUtils.compile(CompilerUtils.java:122)
22:45:42  	at jdk.test.lib.compiler.CompilerUtils.compile(CompilerUtils.java:69)
22:45:42  	at GetPackageFromBootClassPath.setupBootLib(GetPackageFromBootClassPath.java:63)
22:45:42  	at GetPackageFromBootClassPath.main(GetPackageFromBootClassPath.java:44)
22:45:42  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:45:42  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
22:45:42  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
22:45:42  	at java.base/java.lang.Thread.run(Thread.java:1639)
22:45:42  java.lang.RuntimeException: compilation fails
22:45:42  	at GetPackageFromBootClassPath.setupBootLib(GetPackageFromBootClassPath.java:64)
22:45:42  	at GetPackageFromBootClassPath.main(GetPackageFromBootClassPath.java:44)
22:45:42  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:45:42  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
22:45:42  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
22:45:42  	at java.base/java.lang.Thread.run(Thread.java:1639)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_s390x_linux_Release_testList_0/34
jdk_lang_j9_0
ava/lang/Package/bootclasspath/GetPackageFromBootClassPath.java

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.openjdk_s390x_linux_testList_2/256/)
```
[2026-08-19T17:34:09.612Z] Running test jdk_stream_0 ...
[2026-08-19T17:34:09.612Z] ===============================================
[2026-08-19T17:34:09.612Z] jdk_stream_0 Start Time: Wed Aug 19 10:34:09 2026 Epoch Time (ms): 1787160849413
[2026-08-19T17:34:09.612Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2026-08-19T17:34:09.612Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2026-08-19T17:37:08.754Z] TEST: java/util/stream/test/org/openjdk/tests/java/lang/invoke/SerializedLambdaTest.java

[2026-08-19T17:37:08.766Z] STDERR:
[2026-08-19T17:37:08.767Z] An exception has occurred in the compiler (25.0.4.1). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
[2026-08-19T17:37:08.767Z] java.nio.file.ProviderMismatchException
[2026-08-19T17:37:08.767Z] 	at java.base/sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:177)
[2026-08-19T17:37:08.767Z] 	at java.base/sun.nio.fs.UnixFileSystemProvider.exists(UnixFileSystemProvider.java:517)
[2026-08-19T17:37:08.767Z] 	at java.base/java.nio.file.Files.exists(Files.java:2289)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$DirectoryContainer.getFileObject(JavacFileManager.java:531)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForInput(JavacFileManager.java:870)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getJavaFileForInput(JavacFileManager.java:844)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:286)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModuleInfo(ModuleFinder.java:364)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModule(ModuleFinder.java:182)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModule(ModuleFinder.java:169)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:477)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:278)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:239)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1047)
[2026-08-19T17:37:08.767Z] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:941)
[2026-08-19T17:37:08.768Z] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:319)
[2026-08-19T17:37:08.768Z] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
[2026-08-19T17:37:08.768Z] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:66)
[2026-08-19T17:37:08.768Z] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:52)
[2026-08-19T17:37:08.768Z] printing javac parameters to: /tmp/javac.20260819_103653.args
[2026-08-19T17:37:08.768Z] 
[2026-08-19T17:37:08.768Z] TEST RESULT: Error. compiler crashed (exit code 4)
[2026-08-19T17:37:08.768Z] --------------------------------------------------
[2026-08-19T17:43:40.772Z] Test results: passed: 82; error: 1; excluded: 4
```
