### ISSUE TITLE
OpenJ9 can't find natives when launching Reposilite

### ISSUE THREAD

**Issue by kappa-maintainer** [eclipse-openj9/openj9#17019]
Java -version output
--------------------
```openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Linux amd64-64-Bit Compressed References 20230117_397 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```

Summary of problem
------------------

OpenJ9 has error loading libsqlitejdbc.so native library when launching Reposilite under Linux x64.
The native can be loaded normally when using hotsopt, and Reposilite will launch normally.
Other versions of openj9 (including the 36.1 jdk11 and latest ea version of jdk17) have been tested and can reproduce same error.
Two systems have been used when testing: latest Debian unstable and latest Debian testing, both have sqlite3 installed.
The version of Reposilite is 3.4.0, can be downloaded from https://github.com/dzikoysk/reposilite/releases/tag/3.4.0
The recommend command to test is: ```java -jar reposilite-3.4.0-all.jar -wd new```

Diagnostic files
----------------
Here is the console output of launching Reposilite:
```
22:29:02.423 INFO | 
22:29:02.493 INFO | [0;32mReposilite [0m3.4.0
22:29:02.494 INFO | 
22:29:02.494 INFO | --- Environment
22:29:02.527 INFO | Platform: 17.0.6 (Linux :: amd64)
22:29:02.530 INFO | Running as: user
22:29:02.531 INFO | Working directory: /home/user/bin/new
22:29:02.532 INFO | Plugin directory: /home/user/bin/new/plugins
22:29:02.533 INFO | Configuration: /home/user/bin/new/configuration.cdn
22:29:02.534 INFO | Threads: 16 WEB / 8 IO / 1 DB
22:29:02.552 INFO | Loom enabled: false
Failed to load native library:sqlite-3.40.0.0-de037963-60f3-4ab5-886b-cbe43d6a1a5f-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: Failed to load library "/tmp/sqlite-3.40.0.0-de037963-60f3-4ab5-886b-cbe43d6a1a5f-libsqlitejdbc.so"
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:104)
	at org.sqlite.JDBC.connect(JDBC.java:77)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createDataSource(DatabaseConnection.kt:76)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createDataSource$default(DatabaseConnection.kt:75)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.connectWithEmbeddedDatabase(DatabaseConnection.kt:70)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createConnection(DatabaseConnection.kt:47)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:66)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:36)
	at com.reposilite.ReposiliteLauncherKt.createWithParameters(ReposiliteLauncher.kt:41)
	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
22:29:04.326 ERROR | HikariPool-1 - Exception during pool initialization.: java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:104)
	at org.sqlite.JDBC.connect(JDBC.java:77)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createDataSource(DatabaseConnection.kt:76)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createDataSource$default(DatabaseConnection.kt:75)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.connectWithEmbeddedDatabase(DatabaseConnection.kt:70)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createConnection(DatabaseConnection.kt:47)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:66)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:36)
	at com.reposilite.ReposiliteLauncherKt.createWithParameters(ReposiliteLauncher.kt:41)
	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/home/user/bin/openj9/lib/default:/home/user/bin/openj9/lib:/usr/lib64:/usr/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
	... 20 more
Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Error opening connection
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createDataSource(DatabaseConnection.kt:76)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createDataSource$default(DatabaseConnection.kt:75)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.connectWithEmbeddedDatabase(DatabaseConnection.kt:70)
	at com.reposilite.configuration.local.infrastructure.DatabaseConnectionFactory.createConnection(DatabaseConnection.kt:47)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:66)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:36)
	at com.reposilite.ReposiliteLauncherKt.createWithParameters(ReposiliteLauncher.kt:41)
	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
Caused by: java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:104)
	at org.sqlite.JDBC.connect(JDBC.java:77)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 10 more
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/home/user/bin/openj9/lib/default:/home/user/bin/openj9/lib:/usr/lib64:/usr/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
	... 20 more

```

**Comment by pshipton** [comment]
When you run it on jdk11 it shows the problem - `undefined symbol: trunc`.
It's not hard to recreate outside of java.
```
#include <stdio.h>
#include <math.h>
#include <dlfcn.h>

int main(int argc, char **argv) {
	void *handle;
	double d = trunc(2.0);
	printf("%g\n", d);
	handle = dlopen("./libsqlitejdbc.so", RTLD_LAZY);
	if (handle == NULL) {
		printf("dlerror: %s\n", dlerror());
	}
	handle = dlopen("./libsqlitejdbc.so", RTLD_NOW);
	if (handle == NULL) {
                printf("dlerror: %s\n", dlerror());
        }
	return 0;
}
```
`cc -o test -ldl test.c`
`./test`
```
2
dlerror: ./libsqlitejdbc.so: undefined symbol: trunc
dlerror: ./libsqlitejdbc.so: undefined symbol: trunc
```

**Comment by gacholio** [comment]
I wonder if hotspot does lazy symbol resolution by default? Try running with `-XX:+LazySymbolResolution` on the command line.

**Comment by pshipton** [comment]
`-XX:+LazySymbolResolution` is the default according to the doc. Also what I tried in the standalone test case.

**Comment by kappa-maintainer** [comment]
Just tested under Windows and it works fine. It seems to be a Linux exclusive problem
