### ISSUE TITLE
A question about an unstable test case execution output

### ISSUE THREAD

**Issue by YuanWangC** [eclipse-openj9/openj9#17025]
Java -version output
--------------------
```
openjdk version "11.0.19-internal" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19-internal+0-adhoc.root.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-049495700, JRE 11 Linux amd64-64-Bit Compressed References 20230301_000000 (JIT enabled, AOT enabled)
OpenJ9   - 049495700
OMR      - 084e87a92
JCL      - e2754db261 based on jdk-11.0.19+3)
```

Summary of problem
------------------

The output of the following test cases is very strange, sometimes Output1, sometimes Output2, Could you please tell me what is the reason for this?

Test case
------------------
```java
import java.util.*;

public class MyJVMTest{
    void getAll(){
        try{
            Properties p1 = new Properties();
            System.setProperties(p1);
            System.out.println(p1);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public static void main(String[] args){
        for(int i=0;i<3;i++)
           new MyJVMTest().getAll();
    }
}
```
Output1
------------------
```
{}
{}
{}
```
Output2
------------------
```
{}
{}
{}
Exception in thread "Attach API initializer" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:206)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:195)
	at java.base/jdk.internal.jimage.BasicImageReader.<init>(BasicImageReader.java:95)
	at java.base/jdk.internal.jimage.ImageReader$SharedImageReader.<init>(ImageReader.java:224)
	at java.base/jdk.internal.jimage.ImageReader$SharedImageReader.open(ImageReader.java:238)
	at java.base/jdk.internal.jimage.ImageReader.open(ImageReader.java:67)
	at java.base/jdk.internal.jimage.ImageReader.open(ImageReader.java:71)
	at java.base/jdk.internal.jimage.ImageReaderFactory$1.apply(ImageReaderFactory.java:70)
	at java.base/jdk.internal.jimage.ImageReaderFactory$1.apply(ImageReaderFactory.java:67)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713)
	at java.base/jdk.internal.jimage.ImageReaderFactory.get(ImageReaderFactory.java:61)
	at java.base/jdk.internal.jimage.ImageReaderFactory.getImageReader(ImageReaderFactory.java:85)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemImage.<clinit>(SystemModuleFinders.java:383)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.findImageLocation(SystemModuleFinders.java:426)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.read(SystemModuleFinders.java:464)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.open(SystemModuleFinders.java:448)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:434)
	at java.base/jdk.internal.loader.BootLoader.findResourceAsStream(BootLoader.java:146)
	at java.base/java.lang.Module.getResourceAsStream(Module.java:1590)
	at java.base/com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:185)
	at java.base/com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:690)
	at java.base/com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:865)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:859)
	at java.base/java.lang.Thread.uncaughtException(Thread.java:1363)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.System.loadLibrary(System.java:727)
	at java.base/jdk.internal.jimage.NativeImageBuffer$1.run(NativeImageBuffer.java:41)
	at java.base/jdk.internal.jimage.NativeImageBuffer$1.run(NativeImageBuffer.java:39)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:690)
	at java.base/jdk.internal.jimage.NativeImageBuffer.<clinit>(NativeImageBuffer.java:38)
	... 24 more
```

**Comment by pshipton** [comment]
The test case is removing all the system properties, and some things depend on the system properties being set. The exception is coming from AttachAPI trying to load it's library, but finding the "os.name" property is null. It's intermittent because AttachAPI loads in a background thread, which means the timing is variable. Some times it competes before the System properties are removed, and sometimes it doesn't. You can turn off AttachAPI using `-Dcom.ibm.tools.attach.enable=no` avoid the exception and get consistent behaviour.

**Comment by YuanWangC** [comment]
Thanks! I think `Dcom.ibm.tools.attach.enable=no` really works. I'll close this issue.
