### ISSUE TITLE
OpenJDK java/lang/reflect/IllegalArgumentsTest IllegalArgumentsTest.nullArguments() <unknown class>.<unknown method>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17038]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64_aix_Release/5/
jdk_lang_1
java/lang/reflect/IllegalArgumentsTest.java
```
04:49:49  STDOUT:
04:49:49  test IllegalArgumentsTest.illegalArguments(): success
04:49:49  test IllegalArgumentsTest.nullArguments(): failure
04:49:49  java.lang.reflect.InvocationTargetException
04:49:49  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:77)
04:49:49  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
04:49:49  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
04:49:49  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)

04:49:49  Caused by: java.lang.NullPointerException
04:49:49  	at <unknown class>.<unknown method>(Unknown Source)
04:49:49  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
04:49:49  	... 32 more

```

**Comment by pshipton** [comment]
3x x 8 grinder https://openj9-jenkins.osuosl.org/job/Grinder/2117/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/51
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_2/615

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/585/consoleFull
```
19:46:20  Running test jdk_lang_j9_1 ...
19:46:20  ===============================================
19:46:20  jdk_lang_j9_1 Start Time: Tue Mar  3 20:46:18 2026 Epoch Time (ms): 1772585178356
19:46:20  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501 -XXgc:fvtest_forceCopyForwardHybridMarkCompactRatio=10
19:46:20  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -XXgc:fvtest_forceCopyForwardHybridMarkCompactRatio=10 -Xverbosegclog 

20:02:10  TEST: java/lang/reflect/IllegalArgumentsTest.java

20:02:10  test IllegalArgumentsTest.nullArguments(): failure [5962ms]
20:02:10  java.lang.reflect.InvocationTargetException
20:02:10  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)

20:02:10  Caused by: java.lang.NullPointerException
20:02:10  	at <unknown class>.<unknown method>(Unknown Source)
20:02:10  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
20:02:10  	... 32 more
```
