### ISSUE TITLE
OpenJDK java/lang/String/ToLowerCase ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17063]
(Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/484/)
jdk_lang_1
java/lang/String/ToLowerCase.java
The failure didn't repeat in the automatic 3x grinder.
```
[2023-03-29T02:29:30.273Z] STDERR:
[2023-03-29T02:29:30.273Z] java.lang.ArrayIndexOutOfBoundsException
[2023-03-29T02:29:30.273Z] 	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
[2023-03-29T02:29:30.273Z] 	at java.lang.CharacterDataLatin1.toLowerCase(CharacterDataLatin1.java:134)
[2023-03-29T02:29:30.273Z] 	at java.lang.Character.toLowerCase(Character.java:6373)
[2023-03-29T02:29:30.273Z] 	at java.lang.String.toLowerCase(String.java:2785)
[2023-03-29T02:29:30.273Z] 	at java.lang.String.toLowerCaseCore(String.java:2921)
[2023-03-29T02:29:30.273Z] 	at java.lang.String.toLowerCase(String.java:2896)
[2023-03-29T02:29:30.273Z] 	at ToLowerCase.test(ToLowerCase.java:112)
[2023-03-29T02:29:30.273Z] 	at ToLowerCase.main(ToLowerCase.java:44)
```

@joransiu fyi. Not sure if this is zLinux specific or something recently changed in this area.

CharacterDataLatin1
```
    int getProperties(int ch) {
        char offset = (char)ch;
        int props = A[offset]; <- line 72
        return props;
    }

  static final int A[] = new int[256];
```

To get there it went through CharacterData.of() and presumably `ch >>> 8 == 0` was true.
```
    static final CharacterData of(int ch) {
        if (ch >>> 8 == 0) {     // fast-path
            return CharacterDataLatin1.instance;
        } else {
            switch(ch >>> 16) {  //plane 00-16
            case(0):
                return CharacterData00.instance;
            case(1):
                return CharacterData01.instance;
            case(2):
                return CharacterData02.instance;
            case(14):
                return CharacterData0E.instance;
            case(15):   // Private Use
            case(16):   // Private Use
                return CharacterDataPrivateUse.instance;
            default:
                return CharacterDataUndefined.instance;
            }
        }
    }
```

**Comment by joransiu** [comment]
@dchopra001 / @r30shah, can you review?

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8_testList_0/60
jdk_lang_0
java/lang/String/ToLowerCase.java
```
14:29:55  java.lang.ArrayIndexOutOfBoundsException
14:29:55  	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
14:29:55  	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
14:29:55  	at java.lang.Character.getType(Character.java:6978)
14:29:55  	at java.lang.String.isWordStart(String.java:3121)
14:29:55  	at java.lang.String.convertSigma(String.java:3129)
14:29:55  	at java.lang.String.toLowerCaseCore(String.java:2951)
14:29:55  	at java.lang.String.toLowerCase(String.java:2908)
14:29:55  	at ToLowerCase.test(ToLowerCase.java:112)
14:29:55  	at ToLowerCase.main(ToLowerCase.java:49)
```

Likely related to https://github.com/eclipse-openj9/openj9/issues/18669
