### ISSUE TITLE
[JDK20/FFI_Jtreg] Crash detected in LibraryLookupTest

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17062]
The crashed was detected in https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/openj9/test/jdk/java/foreign/LibraryLookupTest.java
```
----------System.out:(3/176)----------
test LibraryLookupTest.testBadLibraryLookupName(): success
test LibraryLookupTest.testBadLibraryLookupPath(): success
test LibraryLookupTest.testLoadLibraryConfined(): success
----------System.err:(56/4957)----------
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FDB487F4760 Handler2=00007FDB485EE400 InaccessibleAddress=00007FDB28001100
RDI=0000003A00000007 RSI=00007FDAE80031B4 RAX=0000000000000000 RBX=00007FDB223DA740
RCX=00007FDB440CFCE0 RDX=00007FDAB800A020 R8=00000000001D1700 R9=00007FDB44019150
R10=0000000000000000 R11=00007FDB28001100 R12=00007FDB223DA4B0 R13=0000000000000000
R14=00000000001D1700 R15=00007FDB48A203E0
RIP=00007FDB28001100 GS=0000 FS=0000 RSP=00007FDB223DA4A8
...
----------- Stack Backtrace -----------
protectedBacktrace+0x16 (0x00007FDB485EA8E6 [libj9prt29.so+0x258e6])
omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
omrintrospect_backtrace_thread_raw+0xbf (0x00007FDB485EADDF [libj9prt29.so+0x25ddf])
omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
omrintrospect_backtrace_thread+0x7e (0x00007FDB485EA77E [libj9prt29.so+0x2577e])
generateDiagnosticFiles+0x8f (0x00007FDB487F427F [libj9vm29.so+0x3e27f])
omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
vmSignalHandler+0x18f (0x00007FDB487F44EF [libj9vm29.so+0x3e4ef])
mainSynchSignalHandler+0x235 (0x00007FDB485EE635 [libj9prt29.so+0x29635])
 (0x00007FDB48ACF420 [libpthread.so.0+0x14420])
```
plus the javacore as follows:
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "MainThread" J9VMThread:0x00000000001D1700, omrthread_t:0x00007FDB44280C10, java/lang/Thread:0x00000000E0151228, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1A, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x00000000E0052FF0)
3XMTHREADINFO1            (native thread ID:0x12A292, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007FDB2235E000, to:0x00007FDB223DE000, size:0x80000)
3XMCPUTIME               CPU usage total: 0.407657394 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=1435016 (0x15E588)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at openj9/internal/foreign/abi/InternalDowncallHandler.invokeNative(Native Method)
4XESTACKTRACE                at openj9/internal/foreign/abi/InternalDowncallHandler.runNativeMethod(InternalDowncallHandler.java:538)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$DMH/0x00000000b80edaf0.invokeSpecial(LambdaForm$DMH)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x00000000b80f1bf0.invoke(LambdaForm$MH)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x00000000b80e8e80.invokeExact_MT(LambdaForm$MH)
4XESTACKTRACE                at LibraryLookupTest.callFunc(LibraryLookupTest.java:90)
4XESTACKTRACE                at LibraryLookupTest.testLoadLibraryConfinedClosed(LibraryLookupTest.java:78)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$DMH/0x00000000b813f860.invokeVirtual(LambdaForm$DMH)
                                           ...
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:1639)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               protectedBacktrace+0x16 (0x00007FDB485EA8E6 [libj9prt29.so+0x258e6])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               omrintrospect_backtrace_thread_raw+0xbf (0x00007FDB485EADDF [libj9prt29.so+0x25ddf])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               omrintrospect_backtrace_thread+0x7e (0x00007FDB485EA77E [libj9prt29.so+0x2577e])
4XENATIVESTACK               setup_native_thread+0x1e3 (0x00007FDB485EB773 [libj9prt29.so+0x26773])
4XENATIVESTACK               omrintrospect_threads_startDo_with_signal+0x44a (0x00007FDB485EC91A [libj9prt29.so+0x2791a])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               _ZN18JavaCoreDumpWriter28writeThreadsWithNativeStacksEv+0x46c (0x00007FDB481849BC [libj9dmp29.so+0x1a9bc])
4XENATIVESTACK               protectedWriteThreadsWithNativeStacks+0x11 (0x00007FDB48185261 [libj9dmp29.so+0x1b261])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               _ZN18JavaCoreDumpWriter18writeThreadSectionEv+0x155 (0x00007FDB481815B5 [libj9dmp29.so+0x175b5])
4XENATIVESTACK               protectedWriteSection+0x21 (0x00007FDB4817C961 [libj9dmp29.so+0x12961])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               _ZN18JavaCoreDumpWriterC2EPKcP16J9RASdumpContextP14J9RASdumpAgent+0x3f7 (0x00007FDB4817D9C7 [libj9dmp29.so+0x139c7])
4XENATIVESTACK               runJavadump+0x20 (0x00007FDB48187E60 [libj9dmp29.so+0x1de60])
4XENATIVESTACK               doJavaDump+0x43 (0x00007FDB4816F643 [libj9dmp29.so+0x5643])
4XENATIVESTACK               protectedDumpFunction+0x19 (0x00007FDB4816EC49 [libj9dmp29.so+0x4c49])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               runDumpFunction+0x64 (0x00007FDB481725E4 [libj9dmp29.so+0x85e4])
4XENATIVESTACK               runDumpAgent+0x163 (0x00007FDB48172773 [libj9dmp29.so+0x8773])
4XENATIVESTACK               triggerDumpAgents+0x614 (0x00007FDB4818A684 [libj9dmp29.so+0x20684])
4XENATIVESTACK               generateDiagnosticFiles+0x162 (0x00007FDB487F4352 [libj9vm29.so+0x3e352])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FDB485EF201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               vmSignalHandler+0x18f (0x00007FDB487F44EF [libj9vm29.so+0x3e4ef])
4XENATIVESTACK               mainSynchSignalHandler+0x235 (0x00007FDB485EE635 [libj9prt29.so+0x29635])
4XENATIVESTACK                (0x00007FDB48ACF420 [libpthread.so.0+0x14420])
```
which passed in JDK19 but failed in JDK20, indicating there might be new changes in JDK20 that need to be addressed separately.

FYI:  @tajila, @pshipton

**Comment by ChengJin01** [comment]
According to the javacore above:
```
4XESTACKTRACE                at LibraryLookupTest.callFunc(LibraryLookupTest.java:90)
4XESTACKTRACE                at LibraryLookupTest.testLoadLibraryConfinedClosed(LibraryLookupTest.java:78)
```
the test crashed at https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/fd8df22bf2c085fc6eb87ec3b6b18f8a4cb7aba6/test/jdk/java/foreign/LibraryLookupTest.java#L78
```
 @Test(expectedExceptions = IllegalStateException.class)
    void testLoadLibraryConfinedClosed() {
        MemorySegment addr;
        try (Arena arena = Arena.openConfined()) {
            addr = loadLibrary(arena.scope());
        }
        callFunc(addr); <----- crash occurred here.
    }
```
The intention of the test case is verify whether the invalid address is captured as `IllegalStateException` after the corresponding scope in closed (in which case the address becomes invalid).

Apparently our code directly did the downcall without the check on the validity of address in JDK20, which should be related to the code at https://github.com/eclipse-openj9/openj9/blob/c797e9f24128b8ec49f770a922e4cedd76914253/jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java#L897

**Comment by ChengJin01** [comment]
Looking at the code of `address()` in JDK20 as compared to JDK19:
[1] JDK20
https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/fd8df22bf2c085fc6eb87ec3b6b18f8a4cb7aba6/src/java.base/share/classes/jdk/internal/foreign/NativeMemorySegmentImpl.java#L61
```
    public long address() {
        return min;
    }
```
[2] JDK19
https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/6e33eff3d0105a864028ec3fd0973267842d1ffb/src/java.base/share/classes/jdk/internal/foreign/NativeMemorySegmentImpl.java#L74
```
    public MemoryAddress address() {
        checkValidState(); <-----
        return MemoryAddress.ofLong(unsafeGetOffset());
    }
```
https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/6e33eff3d0105a864028ec3fd0973267842d1ffb/src/java.base/share/classes/jdk/internal/foreign/AbstractMemorySegmentImpl.java#L351
```
    public void checkValidState() {
        sessionImpl().checkValidState();
    }
```
which means the donwcall address is validated `checkValidState()` on OpenJDK side in JDK19 but removed in JDK20 given `address()` return a long value instead of `MemoryAddress`(removed since JDK20), which explained why no code is required in OpenJ9 to validate the address in JDK19.

That being said, we will need to add on more check on the downcall address in OpenJ9 specific to JDK20 as required in such case.
