### ISSUE TITLE
jdk_rmi_1_FAILED java/rmi/server/RemoteObject/notExtending/NotExtending.java NoSuchObjectException: object not exported

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17079]
Failure link
------------

From [JDK17 x86-64_windows 0.38.0 m2 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_windows/99/)(`win16x64rt-1-9`):
```
openjdk version "17.0.7" 2023-04-18
IBM Semeru Runtime Open Edition 17.0.7.0-m2 (build 17.0.7+5)
Eclipse OpenJ9 VM 17.0.7.0-m2 (build v0.38.0-release-353bdb06f, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20230418_402 (JIT enabled, AOT enabled)
OpenJ9   - 353bdb06f
OMR      - 855813495
JCL      - 267a5a72c4a based on jdk-17.0.7+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_rmi_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F402%2Fibm-semeru-open-jdk_x64_windows_17.0.7_5_openj9-0.38.0-m2.zip+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9%2F402%2Fibm-semeru-open-testimage_x64_windows_17.0.7_5_openj9-0.38.0-m2.zip&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.38.0-release&amp;OPENJ9_BRANCH=v0.38.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.38.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-03-30T04:09:35.550Z] variation: Mode650
[2023-03-30T04:09:36.018Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-03-30T04:12:39.370Z] TEST: java/rmi/server/RemoteObject/notExtending/NotExtending.java

[2023-03-30T04:12:39.371Z] STDERR:
[2023-03-30T04:12:39.371Z] Server exported without invoking hashCode().
[2023-03-30T04:12:39.371Z] server.equals(stub) returns true
[2023-03-30T04:12:39.371Z] stub.equals(server) returns true
[2023-03-30T04:12:39.371Z] java.rmi.NoSuchObjectException: object not exported
[2023-03-30T04:12:39.371Z] 	at java.rmi/sun.rmi.transport.ObjectTable.unexportObject(ObjectTable.java:152)
[2023-03-30T04:12:39.371Z] 	at java.rmi/java.rmi.server.UnicastRemoteObject.unexportObject(UnicastRemoteObject.java:462)
[2023-03-30T04:12:39.371Z] 	at NotExtending.unexport(NotExtending.java:58)
[2023-03-30T04:12:39.371Z] 	at NotExtending.main(NotExtending.java:115)
[2023-03-30T04:12:39.371Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-03-30T04:12:39.371Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-03-30T04:12:39.371Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-03-30T04:12:39.371Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-03-30T04:12:39.371Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-03-30T04:12:39.371Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-03-30T04:12:39.371Z] 
[2023-03-30T04:12:39.371Z] JavaTest Message: Test threw exception: java.rmi.NoSuchObjectException: object not exported

[2023-03-30T04:19:25.384Z] jdk_rmi_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32020/)

**Comment by pshipton** [comment]
Looks like 10x. They all passed on win16x64rt2-4 and all failed on win19x86-rt3-1.

**Comment by pshipton** [comment]
The failures were all in different tests. I can see 25 failures of each, which explains the 50x.

java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.java.UseCustomSocketFactory
- java.rmi.NotBoundException: EchoServer

java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.java.LeaseCheckInterval
- unreferenced() not invoked after 20.0 seconds

**Comment by JasonFengJ9** [comment]
[JDK8 s390x_linux 0.38](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_s390x_linux/124/)(`rhel7s390x-3-2`)
```
[2023-05-04T17:47:36.574Z] variation: Mode650
[2023-05-04T17:47:36.574Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-05-04T17:51:33.887Z] TEST: java/rmi/transport/acceptLoop/CloseServerSocketOnTermination.java

[2023-05-04T17:51:33.888Z] JavaTest Message: Test threw exception: java.rmi.NoSuchObjectException: object not exported
[2023-05-04T17:51:33.888Z] JavaTest Message: shutting down test
[2023-05-04T17:51:33.888Z] 
[2023-05-04T17:51:33.888Z] Exception in thread "RMI TCP Accept-0" STATUS:Failed.`main' threw exception: java.rmi.NoSuchObjectException: object not exported
[2023-05-04T17:51:33.888Z] java.lang.InternalError
[2023-05-04T17:51:33.888Z] 	at CloseServerSocketOnTermination.main(CloseServerSocketOnTermination.java:63)
[2023-05-04T17:51:33.888Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-05-04T17:51:33.888Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-05-04T17:51:33.888Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-05-04T17:51:33.888Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-05-04T17:51:33.888Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-05-04T17:51:33.888Z] 	at java.lang.Thread.run(Thread.java:826)

[2023-05-04T17:51:33.888Z] TEST RESULT: Failed. Execution failed: Execution failed
[2023-05-04T17:51:33.888Z] --------------------------------------------------
[2023-05-04T17:53:00.900Z] Test results: passed: 121; failed: 1
[2023-05-04T17:53:00.900Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16832147509037/jdk_rmi_1/report/html/report.html
[2023-05-04T17:53:00.900Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16832147509037/jdk_rmi_1/work
[2023-05-04T17:53:00.900Z] Error: Some tests failed or other problems occurred.
[2023-05-04T17:53:00.900Z] -----------------------------------
[2023-05-04T17:53:00.900Z] jdk_rmi_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32718/)

**Comment by JasonFengJ9** [comment]
[JDK21 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_2/47/)(`sles15x86-rtp-rt6-1`)
```
[2024-05-11T17:15:23.670Z] variation: Mode650
[2024-05-11T17:15:23.670Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-05-11T17:18:04.724Z] TEST: java/rmi/server/RemoteObject/notExtending/NotExtending.java

[2024-05-11T17:18:04.725Z] STDERR:
[2024-05-11T17:18:04.725Z] Server exported without invoking hashCode().
[2024-05-11T17:18:04.725Z] server.equals(stub) returns true
[2024-05-11T17:18:04.725Z] stub.equals(server) returns true
[2024-05-11T17:18:04.725Z] java.rmi.NoSuchObjectException: object not exported
[2024-05-11T17:18:04.725Z] 	at java.rmi/sun.rmi.transport.ObjectTable.unexportObject(ObjectTable.java:152)
[2024-05-11T17:18:04.725Z] 	at java.rmi/java.rmi.server.UnicastRemoteObject.unexportObject(UnicastRemoteObject.java:460)
[2024-05-11T17:18:04.725Z] 	at NotExtending.unexport(NotExtending.java:58)
[2024-05-11T17:18:04.725Z] 	at NotExtending.main(NotExtending.java:115)
[2024-05-11T17:18:04.725Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-05-11T17:18:04.725Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-05-11T17:18:04.725Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-05-11T17:18:04.725Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-05-11T17:18:04.725Z] 
[2024-05-11T17:18:04.725Z] JavaTest Message: Test threw exception: java.rmi.NoSuchObjectException: object not exported

[2024-05-11T17:19:59.126Z] Test results: passed: 88; failed: 1
[2024-05-11T17:20:07.637Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_2/aqa-tests/TKG/output_17154431943787/jdk_rmi_1/report/html/report.html
[2024-05-11T17:20:07.637Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_2/aqa-tests/TKG/output_17154431943787/jdk_rmi_1/work
[2024-05-11T17:20:07.637Z] Error: Some tests failed or other problems occurred.
[2024-05-11T17:20:07.637Z] -----------------------------------
[2024-05-11T17:20:07.637Z] jdk_rmi_1_FAILED
```

**Comment by taoliult** [comment]
@JasonFengJ9 This appears to be an environment-related issue, and we haven’t seen it occur during recent tests. Do you think we can close this issue for now? We can re-open it if it happens again.

**Comment by JasonFengJ9** [comment]
Not seen in recent builds.
Closing
