### ISSUE TITLE
[JDK20/FFI_Jtreg] Crash detected in StdLibTest

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17078]
The crashed was detected in https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/openj9/test/jdk/java/foreign/StdLibTest.java
```
error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000080
Handler1=00007F80F5B71780 Handler2=00007F80F596B400 InaccessibleAddress=0000000000000000
RDI=00000000001D1800 RSI=00007F809CC60900 RAX=00007F80D6C1BB5D RBX=00000000001D1800
RCX=000000000022D348 RDX=018B415824448948 R8=00007F809CC60480 R9=0000000000000018
R10=0000000000000000 R11=0000000000000000 R12=0000000040000000 R13=0000000000000004
R14=00000000001D1800 R15=00007F80F5D9E3E0
...
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "MainThread" J9VMThread:0x00000000001D1700, omrthread_t:0x00007FA4DC24A350, java/lang/Thread:0x00000000E0120060, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1B, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x00000000E0051210)
3XMTHREADINFO1            (native thread ID:0x12A2ED, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007FA4AA72F000, to:0x00007FA4AA7AF000, size:0x80000)
3XMCPUTIME               CPU usage total: 6.311541707 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=3453552 (0x34B270)
1INTERNAL                    Unable to obtain lock context information
1INTERNAL                    Unable to walk in-flight data on call stack
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               protectedBacktrace+0x16 (0x00007FA4E0AA18E6 [libj9prt29.so+0x258e6])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FA4E0AA6201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               omrintrospect_backtrace_thread_raw+0xbf (0x00007FA4E0AA1DDF [libj9prt29.so+0x25ddf])
4XENATIVESTACK               omrsig_protect+0x2b1 (0x00007FA4E0AA6201 [libj9prt29.so+0x2a201])
4XENATIVESTACK               omrintrospect_backtrace_thread+0x7e (0x00007FA4E0AA177E [libj9prt29.so+0x2577e])
...
4XENATIVESTACK               vmSignalHandler+0x18f (0x00007FA4E0CAB4EF [libj9vm29.so+0x3e4ef])
4XENATIVESTACK               mainSynchSignalHandler+0x235 (0x00007FA4E0AA5635 [libj9prt29.so+0x29635])
4XENATIVESTACK                (0x00007FA4E0F86420 [libpthread.so.0+0x14420])
4XENATIVESTACK               dropPendingSendPushes+0x60 (0x00007FA4E0C9DE70 [libj9vm29.so+0x30e70])
4XENATIVESTACK               prepareForExceptionThrow+0xd (0x00007FA4E0C9DFCD [libj9vm29.so+0x30fcd])
4XENATIVESTACK               _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x8fe (0x00007FA4E0D0698E [libj9vm29.so+0x9998e])
4XENATIVESTACK               bytecodeLoopCompressed+0xb1 (0x00007FA4E0D06081 [libj9vm29.so+0x99081])
4XENATIVESTACK                (0x00007FA4E0DC03A2 [libj9vm29.so+0x1533a2])
```

which passed in JDK19 but failed in JDK20, indicating there might be new changes in JDK20 that need to be addressed separately.

FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
By isolating the failing tests in `StdLibTest`, the test failure were mixed with exceptions which was caused by one of the failing test cases. e.g. `test_strcat`:
```
 69     @Test(dataProvider = "stringPairs")
 70     void test_strcat(String s1, String s2) throws Throwable {
 71         assertEquals(stdLibHelper.strcat(s1, s2), s1 + s2);
 72     }

214         String strcat(String s1, String s2) throws Throwable {
215             try (var arena = Arena.openConfined()) {
216                 MemorySegment buf = arena.allocate(s1.length() + s2.length() + 1);
217                 buf.setUtf8String(0, s1);
218                 MemorySegment other = arena.allocateUtf8String(s2);
219                 return ((MemorySegment)strcat.invokeExact(buf, other)).getUtf8Stri    ng(0); <---- exception occurred here

        final static MethodHandle strcat = abi.downcallHandle(abi.defaultLookup().find("strcat").get(),
                FunctionDescriptor.of(C_POINTER, C_POINTER, C_POINTER));
...
```
with the ouptut in the `StdLibTest.jtr` file
```
test StdLibTest.test_strcat("aaa", "aaa"): failure
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ array: Optional.empty address:140372216270560 limit: 0 }; new offset = 0; new length = 1
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.outOfBoundException(AbstractMemorySegmentImpl.java:371)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:357)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:70)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:124)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:448)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkBounds(AbstractMemorySegmentImpl.java:346)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkAccess(AbstractMemorySegmentImpl.java:311)
        at java.base/java.lang.invoke.VarHandleSegmentAsBytes.checkAddress(VarHandleSegmentAsBytes.java:81)
        at java.base/java.lang.invoke.VarHandleSegmentAsBytes.get(VarHandleSegmentAsBytes.java:108)
        at java.base/java.lang.foreign.MemorySegment.get(MemorySegment.java:1388)
        at java.base/jdk.internal.foreign.abi.SharedUtils.strlen(SharedUtils.java:212)
        at java.base/jdk.internal.foreign.abi.SharedUtils.toJavaStringInternal(SharedUtils.java:203)
        at java.base/java.lang.foreign.MemorySegment.getUtf8String(MemorySegment.java:890) <-----
        at StdLibTest$StdLibHelper.strcat(StdLibTest.java:219) <--------
        at StdLibTest.test_strcat(StdLibTest.java:71)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
...
```
It seems the exception occurred when accessing return address of `strcat` with `getUtf8String()`, which implies that there might be something incorrect in our downcall specific code as to how to deal with the return address for JDK20.

**Comment by ChengJin01** [comment]
With my fix at https://github.com/ChengJin01/openj9/commit/248b0fc4250e141afdd1a8636d55fed62e334703#diff-e2e01e5f1b19239f4e0f58c31a751641196af494d60cce5722d2a503fbb0a084 to handle the passed-in argument in the dispatcher for upcall, the whole test suite passed as expected.
```

===============================================
test/jdk/java/foreign/StdLibTest.java
Total tests run: 75487, Passes: 75487, Failures: 0, Skips: 0
===============================================
```
Will launch personal builds to verify the changes in JDK17/19/20 to ensure everything works well without any issue introduced.
