### ISSUE TITLE
Failure status 500 uploading to artifactory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17070]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly_testList_0/488/console
```
03:03:18  [consumer_0] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly_testList_0/488/testenv.properties
03:08:18  Error occurred for request PUT /artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly_testList_0/488/testenv.properties;build.parentNumber=497;build.timestamp=1680143102030;build.name=sys-rt%2FTest_openjdk11_j9_extended.functional_ppc64le_linux_Nightly_testList_0;build.parentName=Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly;build.number=488 HTTP/1.1: Read timed out.
03:08:19  Attempting retry #1
[Pipeline] }
03:10:10  Failed to upload file
03:10:10  [consumer_0] An exception occurred during execution:
03:10:10  java.lang.RuntimeException: java.io.IOException: JFrog service failed. Received 500: {
03:10:10    "errors" : [ {
03:10:10      "status" : 500,
03:10:10      "message" : ""
03:10:10    } ]
03:10:10  }
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
03:10:10  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
03:10:10  	at java.base/java.lang.Thread.run(Thread.java:840)
03:10:10  Caused by: java.io.IOException: JFrog service failed. Received 500: {
03:10:10    "errors" : [ {
03:10:10      "status" : 500,
03:10:10      "message" : ""
03:10:10    } ]
03:10:10  }
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.throwException(JFrogService.java:49)
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.handleUnsuccessfulResponse(Upload.java:59)
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:121)
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:262)
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:257)
03:10:10  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
03:10:10  	... 2 more
03:10:10  
```

@AdamBrousseau @vsebe

**Comment by AdamBrousseau** [comment]
OSU was having network maintenance past 2 nights and possibly tonight as well. I assume this is because of that.

>Apologies for the late notice, but our network provider LinkOregon has scheduled a multi-day planned outage happening during PDT evenings this week which started last night and going through tonight and tomorrow evening. Many of you likely noticed some disruptions last night due to this.
>
>The following is the announcement we received [1]:
>
>Link Oregon has upgraded firmware on our routing hardware platform. Customers may have experienced a brief service outage when their directly attached router was rebooted. Reboots were sequenced to minimize disruption to customers with redundant connections. To maximize network stability changes will occur over multiple nights during Spring Break.
>
>This was maintenance window 1 of 3. The second activity date is scheduled for Tuesday, March 28, 2023. The third activity date is scheduled for Wednesday , March 29, 2023.
>
>Another outage will likely happen tonight [2] and tomorrow evening [3].
