### ISSUE TITLE
[JDK20/FFI_Jtreg] Exceptions captured in TestPassHeapSegment

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17092]
A couple of exceptions were captured in `TestPassHeapSegment` (introduced in JDK20) as follows:
[1]
```
test TestPassHeapSegment.testNoHeapArgs(): failure
org.testng.TestException:
Method TestPassHeapSegment.testNoHeapArgs()[pri:0, instance:TestPassHeapSegment@cbfbf02] 
        should have thrown an exception of type class java.lang.IllegalArgumentException
        at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
```
against the test code at:
https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/9fcbd19b761da90ae3d1fc9b8692c63e8267d5b7/test/jdk/java/foreign/passheapsegment/TestPassHeapSegment.java#L60
```
   public void testNoHeapArgs() throws Throwable {
        MethodHandle handle = downcallHandle("test_args", FunctionDescriptor.ofVoid(ADDRESS));
        MemorySegment segment = MemorySegment.ofArray(new byte[]{ 0, 1, 2 });
        handle.invoke(segment); // should throw  <----------
    }
```
[2]
```
test TestPassHeapSegment.testNoHeapReturns(true): failure
java.lang.AssertionError: did not expect [0] but found [0]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failEquals(Assert.java:1041)
        at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
        at org.testng.Assert.assertNotEquals(Assert.java:1531)
        at org.testng.Assert.assertNotEquals(Assert.java:1535)
        at UpcallTestHelper.runInNewProcess(UpcallTestHelper.java:72)
        at TestPassHeapSegment.testNoHeapReturns(TestPassHeapSegment.java:58) <----
```
against the test code at:
https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/9fcbd19b761da90ae3d1fc9b8692c63e8267d5b7/test/jdk/java/foreign/passheapsegment/TestPassHeapSegment.java#L65
```
 public void testNoHeapReturns(boolean spec) throws IOException, InterruptedException {
        runInNewProcess(Runner.class, spec).assertStdErrContains("Heap segment not allowed");
    }
    
      public static void main(String[] args) throws Throwable {
            MethodHandle handle = downcallHandle("test_return", FunctionDescriptor.ofVoid(ADDRESS));
            MemorySegment upcallStub = upcallStub(Runner.class, "target", FunctionDescriptor.of(ADDRESS));
            handle.invoke(upcallStub);
        }

        public static MemorySegment target() {
            return MemorySegment.ofArray(new byte[]{ 0, 1, 2 }); // should throw <-------
        }
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
This test suite is used to validate the argument and the return value to prevent the heap segment from being passed through when it comes to the pointer type.

I will close this issue as the related code will be addressed in https://github.com/eclipse-openj9/openj9/issues/16761 given the check on the argument & return value will be shared at Java level.
