### ISSUE TITLE
[JDK20/FFI_Jtreg] WrongMethodTypeException captured in TestCaptureCallState

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17104]
There were a bunch of `WrongMethodTypeException` in this test suite. e.g.
```
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@c7287606): failure
java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(int)void to (MemorySegment,int)Object
        at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:903)
        at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:870)
        at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:542)
        at TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState.java:80)
```
against the test code at https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/9fcbd19b761da90ae3d1fc9b8692c63e8267d5b7/test/jdk/java/foreign/capturecallstate/TestCaptureCallState.java#L87
```
    public void testSavedThreadLocal(SaveValuesCase testCase) throws Throwable {
        Linker.Option.CaptureCallState stl = Linker.Option.captureCallState(testCase.threadLocalName());
        MethodHandle handle = downcallHandle(testCase.nativeTarget(), testCase.nativeDesc(), stl);

        VarHandle errnoHandle = stl.layout().varHandle(groupElement(testCase.threadLocalName()));

        try (Arena arena = Arena.openConfined()) {
            MemorySegment saveSeg = arena.allocate(stl.layout());
            int testValue = 42;
            boolean needsAllocator = testCase.nativeDesc().returnLayout().map(StructLayout.class::isInstance).orElse(false);
            Object result = needsAllocator
                ? handle.invoke(arena, saveSeg, testValue)
                : handle.invoke(saveSeg, testValue); <--------- exception was captured here.
            testCase.resultCheck().accept(result);
            int savedErrno = (int) errnoHandle.get(saveSeg);
            assertEquals(savedErrno, testValue);
        }
    }
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
As explained at https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/foreign/Linker.Option.CaptureCallState.html, `Linker.Option.CaptureCallState` is a new linker option introduced in JDK20 to store the return state after performing the downcall.  Will need to go through our code specific to downcall to figure out how the handle this option in java & native.

**Comment by ChengJin01** [comment]
With my fix at https://github.com/ChengJin01/openj9/commit/2865f3ad86a34676f96d84805676ad9d7410652c, the failing test suite passed as expected (verified on all supported platforms):
```
----------System.out:(15/1134)----------
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@778518f1): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@f7e0fbe7): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@5560bef9): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@d479fce0): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@60d3b1ef): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@6dccc399): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@3a5c4316): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@1ff15b8e): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@1310549b): success

===============================================
test/jdk/java/foreign/capturecallstate/TestCaptureCallState.java
Total tests run: 9, Passes: 9, Failures: 0, Skips: 0
===============================================
```
