### ISSUE TITLE
jdk20 OpenJDK Windows virtual/ThreadAPI IllegalMonitorStateException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17119]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/27 - [win2019-x64-3]
(https://openj9-jenkins.osuosl.org/computer/win2019-x64-3)
jdk_lang_0
java/lang/Thread/virtual/ThreadAPI.java#default

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/27/openjdk_test_output.tar.gz
```
23:50:25  java.lang.IllegalMonitorStateException
23:50:25  	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:175)
23:50:25  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1059)
23:50:25  	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:494)
23:50:25  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.remove(ScheduledThreadPoolExecutor.java:1063)
23:50:25  	at java.base/java.util.concurrent.ThreadPoolExecutor.remove(ThreadPoolExecutor.java:1777)
23:50:25  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.cancel(ScheduledThreadPoolExecutor.java:293)
23:50:25  	at java.base/java.lang.VirtualThread.cancel(VirtualThread.java:677)
23:50:25  	at java.base/java.lang.VirtualThread.parkNanos(VirtualThread.java:609)
23:50:25  	at java.base/java.lang.Access.parkVirtualThread(Access.java:519)
23:50:25  	at java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:67)
23:50:25  	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:267)
23:50:25  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:756)
23:50:25  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1126)
23:50:25  	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
23:50:25  	at java.base/java.lang.VirtualThread.joinNanos(VirtualThread.java:816)
23:50:25  	at java.base/java.lang.Thread.join(Thread.java:2130)
23:50:25  	at ThreadAPI.testJoin7(ThreadAPI.java:428)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/28- [win2012x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2012x64-openj9-1)
java/lang/Thread/virtual/ThreadAPI.java#default

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/28/openjdk_test_output.tar.gz
```
23:50:04  Exception in thread "" java.lang.IllegalMonitorStateException
23:50:04  	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:175)
23:50:04  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1059)
23:50:04  	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:494)
23:50:04  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.remove(ScheduledThreadPoolExecutor.java:1063)
23:50:04  	at java.base/java.util.concurrent.ThreadPoolExecutor.remove(ThreadPoolExecutor.java:1777)
23:50:04  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.cancel(ScheduledThreadPoolExecutor.java:293)
23:50:04  	at java.base/java.lang.VirtualThread.cancel(VirtualThread.java:677)
23:50:04  	at java.base/java.lang.VirtualThread.parkNanos(VirtualThread.java:609)
23:50:04  	at java.base/java.lang.Access.parkVirtualThread(Access.java:519)
23:50:04  	at java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:67)
23:50:04  	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:408)
23:50:04  	at ThreadAPI.lambda$testJoin31$36(ThreadAPI.java:738)
23:50:04  	at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/31
jdk_lang_0

**Comment by tajila** [comment]
This looks a lot like https://github.com/eclipse-openj9/openj9/issues/17120

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/35

**Comment by pshipton** [comment]
Should be fixed by https://github.com/eclipse-openj9/openj9/pull/17182
