### ISSUE TITLE
J9vmTest_1_FAILED j9vm.test.mxbeans.MXBeansGetterSanityTest UnsupportedOperationException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17124]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_sanity.functional_ppc64_aix_testList_0/106/)(`pll011`):
```
openjdk version "19.0.2" 2023-01-17
IBM Semeru Runtime Open Edition 19.0.2+7 (build 19.0.2+7)
Eclipse OpenJ9 VM 19.0.2+7 (build master-ff024fc42, JRE 19 AIX ppc64-64-Bit Compressed References 20230117_79 (JIT enabled, AOT enabled)
OpenJ9   - ff024fc42
OMR      - e6796be5b
JCL      - 889e2e0ea1 based on jdk-19.0.2+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=J9vmTest_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk19_j9_sanity.functional_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-aix-ppc64-openj9%2F79%2Fibm-semeru-open-jdk_ppc64_aix_JDK19U_2023-04-01-16-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-aix-ppc64-openj9%2F79%2Fibm-semeru-open-testimage_ppc64_aix_JDK19U_2023-04-01-16-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=115&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-04-03T03:24:14.856Z] variation: Mode301
[2023-04-03T03:24:14.856Z] JVM_OPTIONS:  -Xgcpolicy:metronome -Xnocompressedrefs 

[2023-04-03T03:27:59.301Z] +++ j9vm.test.mxbeans.MXBeansGetterSanityTest: +++
[2023-04-03T03:27:59.301Z] command: /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_ppc64_aix_testList_0/openjdkbinary/j2sdk-image/bin/java  -Xgcpolicy:metronome -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m  --add-exports=java.management/com.ibm.java.lang.management.internal=ALL-UNNAMED --add-exports=jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED    -classpath /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_ppc64_aix_testList_0/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_ppc64_aix_testList_0/aqa-tests/TKG/../TKG/lib/asm-all.jar  j9vm.test.mxbeans.MXBeansGetterSanityTest 

[2023-04-03T03:27:59.909Z] Calling getCurrentThreadAllocatedBytes on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.909Z] java.lang.reflect.InvocationTargetException
[2023-04-03T03:27:59.909Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[2023-04-03T03:27:59.909Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-03T03:27:59.909Z] 	at j9vm.test.mxbeans.MXBeansGetterSanityTest.testMXBeanGetters(MXBeansGetterSanityTest.java:48)
[2023-04-03T03:27:59.909Z] 	at j9vm.test.mxbeans.MXBeansGetterSanityTest.main(MXBeansGetterSanityTest.java:90)
[2023-04-03T03:27:59.909Z] Caused by: java.lang.UnsupportedOperationException
[2023-04-03T03:27:59.909Z] 	at jdk.management/com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl.getThreadAllocatedBytes(ExtendedThreadMXBeanImpl.java:74)
[2023-04-03T03:27:59.909Z] 	at jdk.management/com.sun.management.ThreadMXBean.getCurrentThreadAllocatedBytes(ThreadMXBean.java:141)
[2023-04-03T03:27:59.909Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-03T03:27:59.909Z] 	... 3 more
[2023-04-03T03:27:59.909Z] Calling getThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.909Z] Calling getCurrentThreadUserTime on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.909Z] Calling getDaemonThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.909Z] Calling getPeakThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.909Z] Calling getAllThreadIds on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.909Z] Calling getCurrentThreadCpuTime on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.910Z] Calling getObjectName on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.910Z] Calling getTotalStartedThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.910Z] Calling getInstance on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.910Z] Calling getInstance on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
[2023-04-03T03:27:59.910Z] --- Test PASSED ---
[2023-04-03T03:27:59.910Z] 
[2023-04-03T03:27:59.910Z] 70 passed / 1 failed
[2023-04-03T03:27:59.910Z] -----------------------------------
[2023-04-03T03:27:59.910Z] J9vmTest_1_FAILED
```

**Comment by pshipton** [comment]
@JasonFengJ9 the test you copied isn't failing, it's j9vm.test.arraylets.ArrayletAllocateTest which is failing. This is another occurrence of https://github.com/eclipse-openj9/openj9/issues/9969
