### ISSUE TITLE
jdk20 OpenJDK jdk/incubator/vector/Byte64VectorTests.java timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17122]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_Nightly/29/
jdk_vector_byte64_j9_0
jdk/incubator/vector/Byte64VectorTests.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_Nightly/29/openjdk_test_output.tar.gz
```
22:57:25  Timeout information:
22:57:25  Running jcmd on process 3794294
22:57:25  Dump written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16807385676475/jdk_vector_byte64_j9_0/work/scratch/0/core.20230406.025649.3794294.0001.dmp
22:57:25  Dump written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16807385676475/jdk_vector_byte64_j9_0/work/scratch/0/javacore.20230406.025713.3794294.0002.txt
22:57:25  Running jstack on process 3794294
22:57:25  2023-04-06T02:57:16.467483903
22:57:25  Virtual machine: 3794294 JVM information:
22:57:25  JRE 20 Linux aarch64-64-Bit Compressed References 20230405_32 (JIT enabled, AOT enabled)
22:57:25  OpenJ9   - c4afb5c59e3
22:57:25  OMR      - 2d7aff0254f
22:57:25  JCL      - 9fcbd19b761 based on jdk-20+36
22:57:25  
22:57:25  "main" prio=5 Id=2 WAITING
22:57:25  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
22:57:25  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
22:57:25  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
22:57:25  	at java.base@20-internal/java.lang.Thread.join(Thread.java:2147)
22:57:25  	at java.base@20-internal/java.lang.Thread.join(Thread.java:2223)
22:57:25  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:72)
22:57:25  
22:57:25  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
22:57:25  
22:57:25  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
22:57:25  
22:57:25  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
22:57:25  
22:57:25  "JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
22:57:25  
22:57:25  "JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE
22:57:25  
22:57:25  "JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE
22:57:25  
22:57:25  "JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE
22:57:25  
22:57:25  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE
22:57:25  
22:57:25  "JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING
22:57:25  
22:57:25  "IProfiler" prio=5 Id=13 RUNNABLE
22:57:25  
22:57:25  "Common-Cleaner" prio=8 Id=3 TIMED_WAITING
22:57:25  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
22:57:25  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
22:57:25  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
22:57:25  	at java.base@20-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
22:57:25  	at java.base@20-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
22:57:25  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
22:57:25  	at java.base@20-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
22:57:25  
22:57:25  "Finalizer thread" prio=5 Id=14 RUNNABLE
22:57:25  
22:57:25  "Concurrent Mark Helper" prio=1 Id=15 RUNNABLE
22:57:25  
22:57:25  "GC Worker" prio=5 Id=16 RUNNABLE
22:57:25  
22:57:25  "GC Worker" prio=5 Id=17 RUNNABLE
22:57:25  
22:57:25  "GC Worker" prio=5 Id=18 RUNNABLE
22:57:25  
22:57:25  "Attach API wait loop" prio=10 Id=21 RUNNABLE
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
22:57:25  
22:57:25  "MainThread" prio=5 Id=23 RUNNABLE
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.AbstractShuffle.intoArray(AbstractShuffle.java:92)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.AbstractShuffle.toArray(AbstractShuffle.java:104)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.AbstractShuffle.toVectorTemplate(AbstractShuffle.java:118)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.Byte64Vector$Byte64Shuffle.lambda$toVector$0(Byte64Vector.java:823)
22:57:25  	at java.base@20-internal/jdk.internal.vm.vector.VectorSupport.shuffleToVector(VectorSupport.java:246)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.Byte64Vector$Byte64Shuffle.toVector(Byte64Vector.java:822)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.Byte64Vector$Byte64Shuffle.toVector(Byte64Vector.java:786)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.AbstractShuffle.checkIndexes(AbstractShuffle.java:126)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.ByteVector.rearrangeTemplate(ByteVector.java:2403)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.Byte64Vector.rearrange(Byte64Vector.java:452)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.Byte64Vector.rearrange(Byte64Vector.java:41)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.ByteVector.sliceTemplate(ByteVector.java:2289)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.ByteVector.unsliceTemplate(ByteVector.java:2352)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.Byte64Vector.unslice(Byte64Vector.java:437)
22:57:25  	at jdk.incubator.vector@20-internal/jdk.incubator.vector.Byte64Vector.unslice(Byte64Vector.java:41)
22:57:25  	at app//Byte64VectorTests.unsliceByte64VectorTestsMasked(Byte64VectorTests.java:4937)
22:57:25  	at java.base@20-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:57:25  	at java.base@20-internal/java.lang.reflect.Method.invoke(Method.java:578)
22:57:25  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:57:25  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:57:25  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:57:25  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:57:25  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:57:25  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:57:25  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:57:25  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:57:25  	at java.base@20-internal/java.util.ArrayList.forEach(ArrayList.java:1511)
22:57:25  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
22:57:25  	at app//org.testng.TestRunner.run(TestRunner.java:585)
22:57:25  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:57:25  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:57:25  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:57:25  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:57:25  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:57:25  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:57:25  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:57:25  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:57:25  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
22:57:25  	at app//org.testng.TestNG.run(TestNG.java:1037)
22:57:25  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
22:57:25  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
22:57:25  	at java.base@20-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:57:25  	at java.base@20-internal/java.lang.reflect.Method.invoke(Method.java:578)
22:57:25  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
22:57:25  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
22:57:25  
22:57:25  "file lock watchdog" prio=10 Id=25 TIMED_WAITING
22:57:25  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
22:57:25  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
22:57:25  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
22:57:25  	at java.base@20-internal/java.util.TimerThread.mainLoop(Timer.java:569)
22:57:25  	at java.base@20-internal/java.util.TimerThread.run(Timer.java:522)
22:57:25  
22:57:25  "Attachment portNumber: 34975" prio=10 Id=30 RUNNABLE
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
22:57:25  	at java.base@20-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
22:57:25  
22:57:25  
22:57:25  --- Timeout information end.
```

@gita-omr

**Comment by pshipton** [comment]
@knn-k

**Comment by knn-k** [comment]
I ran a 20x Grinder job for jdk_vector_byte64_j9_0, and got no failures: https://openj9-jenkins.osuosl.org/job/Grinder/2208/

**Comment by knn-k** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/2213/ did not fail, either.

**Comment by gita-omr** [comment]
@pshipton do you think we can close this one?

**Comment by pshipton** [comment]
Sure, I haven't seen it recently.
