### ISSUE TITLE
JDK21 build failures java.lang.InternalError across platforms

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17121]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_mac_OpenJDK/80/console

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
12:41:28  Optimizing the exploded image
12:41:31  Exception in thread "main" java.lang.InternalError
12:41:31  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:509)
12:41:31  	at java.base/java.lang.Access.defineClass(Access.java:347)
12:41:31  	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2512)
12:41:31  	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2487)
12:41:31  	at java.base/java.lang.invoke.ClassSpecializer$Factory.generateConcreteSpeciesCode(ClassSpecializer.java:577)
12:41:31  	at java.base/java.lang.invoke.ClassSpecializer$Factory.loadSpecies(ClassSpecializer.java:494)
12:41:31  	at java.base/java.lang.invoke.ClassSpecializer.findSpecies(ClassSpecializer.java:197)
12:41:31  	at java.base/java.lang.invoke.BoundMethodHandle$SpeciesData.extendWith(BoundMethodHandle.java:360)
12:41:31  	at java.base/java.lang.invoke.LambdaFormEditor.newSpeciesData(LambdaFormEditor.java:516)
12:41:31  	at java.base/java.lang.invoke.LambdaFormEditor.bindArgumentForm(LambdaFormEditor.java:579)
12:41:31  	at java.base/java.lang.invoke.LambdaFormEditor.bindArgumentL(LambdaFormEditor.java:523)
12:41:31  	at java.base/java.lang.invoke.BoundMethodHandle.bindArgumentL(BoundMethodHandle.java:72)
12:41:31  	at java.base/java.lang.invoke.MethodHandles.insertArguments(MethodHandles.java:5279)
12:41:31  	at java.base/java.lang.runtime.SwitchBootstraps.typeSwitch(SwitchBootstraps.java:130)
12:41:31  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:147)
12:41:31  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
12:41:31  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
12:41:31  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
12:41:31  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:198)
12:41:31  	at java.base/jdk.internal.classfile.impl.ChainedClassBuilder.<init>(ChainedClassBuilder.java:44)
12:41:31  	at java.base/jdk.internal.classfile.impl.TransformImpl$ChainedClassTransform.resolve(TransformImpl.java:94)
12:41:31  	at java.base/jdk.internal.classfile.impl.TransformImpl$ChainedClassTransform.resolve(TransformImpl.java:88)
12:41:31  	at java.base/jdk.internal.classfile.ClassfileBuilder.transform(ClassfileBuilder.java:84)
12:41:31  	at java.base/jdk.internal.classfile.impl.ClassImpl$2.accept(ClassImpl.java:181)
12:41:31  	at java.base/jdk.internal.classfile.impl.ClassImpl$2.accept(ClassImpl.java:176)
12:41:31  	at java.base/jdk.internal.classfile.Classfile.build(Classfile.java:217)
12:41:31  	at java.base/jdk.internal.classfile.impl.ClassImpl.transform(ClassImpl.java:175)
12:41:31  	at java.base/jdk.internal.module.ModuleInfoExtender.toByteArray(ModuleInfoExtender.java:155)
12:41:31  	at java.base/jdk.internal.module.ModuleInfoExtender.write(ModuleInfoExtender.java:144)
12:41:31  	at build.tools.jigsaw.AddPackagesAttribute.addPackagesAttribute(AddPackagesAttribute.java:83)
12:41:31  	at build.tools.jigsaw.AddPackagesAttribute.main(AddPackagesAttribute.java:70)
12:41:31  make[3]: *** [/Users/jenkins/workspace/Build_JDKnext_aarch64_mac_OpenJDK/build/macosx-aarch64-server-release/jdk/_optimize_image_exec.marker] Error 1
12:41:31  make[2]: *** [exploded-image-optimize] Error 2
12:41:31  make[2]: *** Waiting for unfinished jobs....
12:41:56  
12:41:56  ERROR: Build failed for target 'all' in configuration 'macosx-aarch64-server-release' (exit code 2) 
12:41:56  Stopping javac server
```

**Comment by pshipton** [comment]
For the lists of OpenJDK changes see https://github.com/eclipse-openj9/openj9/issues/17115#issue-1655702363 and https://github.com/eclipse-openj9/openj9/issues/17115#issuecomment-1497789922

**Comment by keithc-ca** [comment]
This is due to changes made for 
* [8304846: Provide a shared utility to dump generated classes defined via Lookup API](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/7dc79c2c1838708db518e4fec8ef40d8a2e629d2)

The code now uses a different variant of `JavaLangAccess.defienClass()`. I expect to have a fix shortly.

**Comment by JasonFengJ9** [comment]
Re-assigning since @keithc-ca was working on it.
