### ISSUE TITLE
OpenJDK java/util/concurrent/tck/JSR166TestCase.java junit test failed, unknown test

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17135]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/31
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java

```
02:55:51  Output overflow:
02:55:51  JT Harness has limited the test output to the text
02:55:51  at the beginning and the end, so that you can see how the
02:55:51  test began, and how it completed.
02:55:51  
02:55:51  If you need to see more of the output from the test,
02:55:51  set the system property javatest.maxOutputSize to a higher
02:55:51  value. The current value is 100000

02:55:51  [ JUnit Containers: found 221, started 221, succeeded 185, failed 0, aborted 0, skipped 0]
02:55:51  [ JUnit Tests: found 4084, started 4063, succeeded 4062, failed 1, aborted 0, skipped 0]
02:55:51  
02:55:51  java.lang.Exception: JUnit test failure
02:55:51  	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:150)
02:55:51  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:96)
02:55:51  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:62)
02:55:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
02:55:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
02:55:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
02:55:51  	at java.base/java.lang.Thread.run(Thread.java:1639)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/57/
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java
```
06:34:11  [ JUnit Containers: found 222, started 222, succeeded 186, failed 0, aborted 0, skipped 0]
06:34:11  [ JUnit Tests: found 4087, started 4066, succeeded 4065, failed 1, aborted 0, skipped 0]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/35

**Comment by JasonFengJ9** [comment]
[JDK17 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_1/509/)(`sles12le-svl-rt7-1`)
```
[2024-04-02T01:28:26.379Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2024-04-02T01:28:26.379Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2024-04-02T01:37:10.156Z] TEST: java/util/concurrent/tck/JSR166TestCase.java#others

[2024-04-02T01:37:10.167Z] ...
[2024-04-02T01:37:10.167Z] Output overflow:
[2024-04-02T01:37:10.167Z] JT Harness has limited the test output to the text
[2024-04-02T01:37:10.167Z] at the beginning and the end, so that you can see how the
[2024-04-02T01:37:10.167Z] test began, and how it completed.
[2024-04-02T01:37:10.167Z] 
[2024-04-02T01:37:10.167Z] If you need to see more of the output from the test,
[2024-04-02T01:37:10.167Z] set the system property javatest.maxOutputSize to a higher
[2024-04-02T01:37:10.167Z] value. The current value is 100000
[2024-04-02T01:37:10.167Z] ...

[2024-04-02T01:37:10.170Z] JavaTest Message: JUnit Platform Failure(s): 1
[2024-04-02T01:37:10.170Z] 
[2024-04-02T01:37:10.170Z] [ JUnit Containers: found 218, started 218, succeeded 182, failed 0, aborted 0, skipped 0]
[2024-04-02T01:37:10.170Z] [ JUnit Tests: found 4061, started 4040, succeeded 4039, failed 1, aborted 0, skipped 0]
[2024-04-02T01:37:10.170Z] 
[2024-04-02T01:37:10.170Z] java.lang.Exception: JUnit test failure
[2024-04-02T01:37:10.170Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:149)
[2024-04-02T01:37:10.170Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
[2024-04-02T01:37:10.170Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
[2024-04-02T01:37:10.170Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-04-02T01:37:10.170Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-04-02T01:37:10.170Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-04-02T01:37:10.170Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
[2024-04-02T01:37:10.170Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-04-02T01:37:10.170Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2024-04-02T01:37:10.170Z] 
[2024-04-02T01:37:10.170Z] JavaTest Message: Test threw exception: java.lang.Exception: JUnit test failure

[2024-04-02T01:58:40.079Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Release_testList_0/21
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#forkjoinpool-common-parallelism
```
08:17:40  [ JUnit Containers: found 222, started 222, succeeded 186, failed 0, aborted 0, skipped 0]
08:17:40  [ JUnit Tests: found 4087, started 4066, succeeded 4065, failed 1, aborted 0, skipped 0]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Release_testList_1/26
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#default

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_OpenJDK11_testList_0/18/
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#others

**Comment by cjjdespres** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_jit_Personal_testList_1/398/ - [sles15le-rtp-rt3-1.fyre.ibm.com](https://hyc-runtimes-jenkins.swg-devops.com/computer/sles15le-rtp-rt3-1.fyre.ibm.com) 
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#default

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/318 - [cent9-aarch64-5](https://openj9-jenkins.osuosl.org/computer/cent9-aarch64-5)
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#security-manager

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/307
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#security-manager

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/83
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#forkjoinpool-common-parallelism

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/236
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#others

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/321
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#security-manager

**Comment by pshipton** [comment]
@tajila this started failing every day.

**Comment by tajila** [comment]
@theresa-m Please take a look at this

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_OMR_testList_2/149

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_2/270

**Comment by theresa-m** [comment]
I haven't been able to reproduce this running jdk_util in a grinder and the exception does not give any clues about the failure. I'm adding xdump options to the test commands to try to catch the next one and get more information. These should be reverted when this is resolved.
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/881
https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/226
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/414
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/846

**Comment by pshipton** [comment]
@theresa-m A new failure but I don't see any dumps, the only file collected is verbosegc. The -Xdump option is there but looking again `systhrow` should likely be `throw`.

Some other thoughts:
- looking at https://github.com/eclipse-openj9/openj9/issues/14140, modify the -Xdump comment to catch junit.framework.AssertionFailedError instead of the Exception at the end of the test, which may not help provide much detail about the failure
- perhaps there is an option to override the default behavior where output is removed due to "Output overflow"
- maybe it's worth modifying the test to record what failed and any details (or finding appropriate options), either to be printed at the end, or written to a file

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/131/
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#others
```
    /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/jdkbinary/j2sdk-image/bin/java \\
        -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog' \\
        -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-UseCompressedOops -J-Xverbosegclog' \\
        -Dtest.compiler.opts= \\
        -Dtest.java.opts= \\
        -Dtest.jdk=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/jdkbinary/j2sdk-image \\
        -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/jdkbinary/j2sdk-image \\
        -Dtest.timeout.factor=8.0 \\
        -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/jdkbinary/openjdk-test-image/jdk/jtreg/native \\
        -Dtest.root=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk \\
        -Dtest.name=java/util/concurrent/tck/JSR166TestCase.java#others \\
        -Dtest.file=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/tck/JSR166TestCase.java \\
        -Dtest.src=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/tck \\
        -Dtest.src.path=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/tck \\
        -Dtest.classes=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/TKG/output_17327075386992/jdk_util_1/work/classes/0/java/util/concurrent/tck/JSR166TestCase_others.d \\
        -Dtest.class.path=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/TKG/output_17327075386992/jdk_util_1/work/classes/0/java/util/concurrent/tck/JSR166TestCase_others.d \\
        -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/TKG/output_17327075386992/jdk_util_1/work/classes/0/java/util/concurrent/tck/JSR166TestCase_others.d:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/tck \\
        -Dtest.modules=java.management \\
        --add-modules java.management \\
        -ea \\
        -esa \\
        -Xmx1540m \\
        -Xdump:system:none \\
        -Xdump:heap:none \\
        -Xdump:system:events=gpf+abort+traceassert+corruptcache \\
        -XX:-UseCompressedOops \\
        -Xverbosegclog \\
        -Djava.library.path=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/jdkbinary/openjdk-test-image/jdk/jtreg/native \\
        --add-opens java.base/java.util.concurrent=ALL-UNNAMED \\
        --add-opens java.base/java.lang=ALL-UNNAMED \\
        -Djsr166.testImplementationDetails=true \\
        -Xdump:system+java+snap:events=systhrow,filter=java/lang/Exception,msg_filter=*JUnit* \\
        com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/aqa-tests/TKG/output_17327075386992/jdk_util_1/work/java/util/concurrent/tck/JSR166TestCase_others.d/junit.0.jta java/util/concurrent/tck/JSR166TestCase.java#others JSR166TestCase
result: Failed. Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure
```

**Comment by theresa-m** [comment]
> I haven't been able to reproduce this running jdk_util in a grinder and the exception does not give any clues about the failure. I'm adding xdump options to the test commands to try to catch the next one and get more information. These should be reverted when this is resolved. [ibmruntimes/openj9-openjdk-jdk#881](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/881) [ibmruntimes/openj9-openjdk-jdk23#76](https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/76) [ibmruntimes/openj9-openjdk-jdk21#226](https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/226) [ibmruntimes/openj9-openjdk-jdk17#414](https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/414) [ibmruntimes/openj9-openjdk-jdk11#846](https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/846)

These have been added as well:
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/898
https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/82 
https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/231
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/418
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/850

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OMR_testList_2/200 - [cent9-aarch64-2](https://openj9-jenkins.osuosl.org/computer/cent9-aarch64-2)
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#security-manager

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OMR_testList_2/200/openjdk_test_output.tar.gz

@theresa-m we got diagnostics for an AssertionFailedError, 6 of them.

**Comment by theresa-m** [comment]
The javacore file shows that the failure is due to a timeout in `LockSupportTest.java.testParkNeg_parkUntil` which calls `jdk.internal.misc.Unafe.park()`.

```
"junit/framework/AssertionFailedError" "timed out waiting for thread to terminate, thread=Thread[Thread-361,5,MainThreadGroup], state=TIMED_WAITING" received
```

```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at junit/framework/Assert.fail(Assert.java:57)
4XESTACKTRACE                at junit/framework/TestCase.fail(TestCase.java:223)
4XESTACKTRACE                at JSR166TestCase.threadFail(JSR166TestCase.java:920)
4XESTACKTRACE                at JSR166TestCase.awaitTermination(JSR166TestCase.java:1688)
4XESTACKTRACE                at JSR166TestCase.awaitTermination(JSR166TestCase.java:1702)
4XESTACKTRACE                at LockSupportTest.testParkNeg(LockSupportTest.java:403)
4XESTACKTRACE                at LockSupportTest.testParkNeg_parkUntil(LockSupportTest.java:389)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77(Compiled Code))
4XESTACKTRACE                at jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:575(Compiled Code))
4XESTACKTRACE                at junit/framework/TestCase.runTest(TestCase.java:177(Compiled Code))
4XESTACKTRACE                at JSR166TestCase.runTest(JSR166TestCase.java:419(Compiled Code))
4XESTACKTRACE                at junit/framework/TestCase.runBare(TestCase.java:142(Compiled Code))
4XESTACKTRACE                at JSR166TestCase.runBare(JSR166TestCase.java:410(Compiled Code))
4XESTACKTRACE                at junit/framework/TestResult$1.protect(TestResult.java:122(Compiled Code))
4XESTACKTRACE                at junit/framework/TestResult.runProtected(TestResult.java:142(Compiled Code))
4XESTACKTRACE                at junit/framework/TestResult.run(TestResult.java:125(Compiled Code))
4XESTACKTRACE                at junit/framework/TestCase.run(TestCase.java:130(Compiled Code))
4XESTACKTRACE                at junit/framework/TestSuite.runTest(TestSuite.java:241(Compiled Code))
4XESTACKTRACE                at junit/framework/TestSuite.run(TestSuite.java:236(Compiled Code))
4XESTACKTRACE                at junit/framework/TestSuite.runTest(TestSuite.java:241)
4XESTACKTRACE                at junit/framework/TestSuite.run(TestSuite.java:236)
```

I will continue to investigate what might have caused this.

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_sanity.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_testList_0/270/)(`ubu20le-rtp-rt11-1`)
```
[2024-12-17T18:16:49.552Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2024-12-17T18:16:49.553Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2024-12-17T18:26:01.475Z] TEST: java/util/concurrent/tck/JSR166TestCase.java#security-manager

[2024-12-17T18:26:01.554Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure
[2024-12-17T18:26:01.554Z] --------------------------------------------------
[2024-12-17T18:49:00.383Z] Test results: passed: 949; failed: 1
[2024-12-17T18:49:32.066Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_17344534993180/jdk_util_1/report/html/report.html
[2024-12-17T18:49:32.067Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_17344534993180/jdk_util_1/work
[2024-12-17T18:49:32.067Z] Error: Some tests failed or other problems occurred.
[2024-12-17T18:49:32.067Z] -----------------------------------
[2024-12-17T18:49:32.067Z] jdk_util_1_FAILED
```

**Comment by theresa-m** [comment]
https://github.com/eclipse-openj9/openj9/pull/20802 has been merged. I will leave this issue open for a few weeks to be sure this failure doesn't show up again.

**Comment by theresa-m** [comment]
I'm closing this issue since there haven't been reports of it being seen again.

**Comment by pshipton** [comment]
Another unknown failure, but there are diagnostic files created due to the failure. @theresa-m can you pls take a look.
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/433

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/433/openjdk_test_output.tar.gz

**Comment by theresa-m** [comment]
This failure is due to an unexpected exception in the test framework:
```
06:51:04  JVMDUMP013I Processed dump event "throw", detail "java/lang/Exception".
06:51:04  java.lang.Exception: JUnit test failure
06:51:04  	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:149)
06:51:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
06:51:04  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
06:51:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:51:04  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:51:04  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:51:04  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
06:51:04  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
06:51:04  	at java.base/java.lang.Thread.run(Thread.java:835)
```

Run with jdk:
```
04:32:02  Eclipse OpenJ9 VM (build master-a3f2552b9e3, JRE 11 AIX ppc64-64-Bit Compressed References 20250520_1055 (JIT enabled, AOT enabled)
04:32:02  OpenJ9   - a3f2552b9e3
04:32:02  OMR      - 06d80e2d963
04:32:02  JCL      - 3c02ade4c13 based on jdk-11.0.28+2)
```

javacore.20250520.102309.20316464.0008.txt shows the test fails in `ForkJoinTask8Test.testForkHelpQuiesce`:
```
4XESTACKTRACE                at java/util/concurrent/ForkJoinTask.uncheckedThrow(ForkJoinTask.java:669)
4XESTACKTRACE                at java/util/concurrent/ForkJoinTask.rethrow(ForkJoinTask.java:658)
4XESTACKTRACE                at java/util/concurrent/ForkJoinTask.reportException(ForkJoinTask.java:678)
4XESTACKTRACE                at java/util/concurrent/ForkJoinTask.join(ForkJoinTask.java:722(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ForkJoinPool.invoke(ForkJoinPool.java:2423(Compiled Code))
4XESTACKTRACE                at ForkJoinTask8Test.testInvokeOnPool(ForkJoinTask8Test.java:110)
4XESTACKTRACE                at ForkJoinTask8Test.testForkHelpQuiesce(ForkJoinTask8Test.java:561)
4XESTACKTRACE                at ForkJoinTask8Test.testForkHelpQuiesce(ForkJoinTask8Test.java:547)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/400

Diagnostic files https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/400/openjdk_test_output.tar.gz
