### ISSUE TITLE
OpenJDK BootstrapMethodError Caused by: java.lang.IllegalStateException: Recursive update

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17134]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/456
jdk_lang_0
java/lang/String/concat/WithSecurityManager.java

```
21:12:40  java.lang.BootstrapMethodError: bootstrap method initialization exception
21:12:40  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
21:12:40  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
21:12:40  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
21:12:40  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
21:12:40  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:199)
21:12:40  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
21:12:40  	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1160)
21:12:40  	at java.base/java.lang.System.getProperty(System.java:606)
21:12:40  	at java.base/java.lang.System.getProperty(System.java:589)
21:12:40  	at java.base/sun.security.action.GetPropertyAction.run(GetPropertyAction.java:87)
21:12:40  	at java.base/sun.security.action.GetPropertyAction.run(GetPropertyAction.java:53)
21:12:40  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
21:12:40  	at java.base/jdk.internal.util.random.RandomSupport.secureRandomSeedRequested(RandomSupport.java:759)
21:12:40  	at java.base/jdk.internal.util.random.RandomSupport.<clinit>(RandomSupport.java:765)
21:12:40  	at java.base/java.util.concurrent.ThreadLocalRandom.<clinit>(ThreadLocalRandom.java:399)
21:12:40  	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2589)
21:12:40  	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2339)
21:12:40  	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1080)
21:12:40  	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1546)
21:12:40  	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.add(MethodType.java:1398)
21:12:40  	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:357)
21:12:40  	at java.base/java.lang.invoke.MethodType.insertParameterTypes(MethodType.java:448)
21:12:40  	at java.base/java.lang.invoke.MethodType.invokerType(MethodType.java:696)
21:12:40  	at java.base/java.lang.invoke.DelegatingMethodHandle.makeReinvokerForm(DelegatingMethodHandle.java:142)
21:12:40  	at java.base/java.lang.invoke.DelegatingMethodHandle.makeReinvokerForm(DelegatingMethodHandle.java:116)
21:12:40  	at java.base/java.lang.invoke.BoundMethodHandle.makeReinvoker(BoundMethodHandle.java:131)
21:12:40  	at java.base/java.lang.invoke.DirectMethodHandle.rebind(DirectMethodHandle.java:150)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory$3.apply(StringConcatFactory.java:666)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory$3.apply(StringConcatFactory.java:661)
21:12:40  	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory.mixer(StringConcatFactory.java:639)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:604)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:358)
21:12:40  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
21:12:40  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
21:12:40  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
21:12:40  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
21:12:40  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:199)
21:12:40  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
21:12:40  	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
21:12:40  	at java.base/java.io.File.exists(File.java:829)
21:12:40  	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1394)
21:12:40  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:421)
21:12:40  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:476)
21:12:40  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:971)
21:12:40  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:969)
21:12:40  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
21:12:40  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:982)
21:12:40  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
21:12:40  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
21:12:40  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
21:12:40  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
21:12:40  	at WithSecurityManager.main(WithSecurityManager.java:55)
21:12:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:12:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
21:12:40  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:12:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
21:12:40  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:12:40  	at java.base/java.lang.Thread.run(Thread.java:857)
21:12:40  Caused by: java.lang.invoke.StringConcatException: Generator failed
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:364)
21:12:40  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
21:12:40  	... 58 more
21:12:40  Caused by: java.lang.IllegalStateException: Recursive update
21:12:40  	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1768)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory.mixer(StringConcatFactory.java:639)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:604)
21:12:40  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:358)
21:12:40  	... 59 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_mac_OMR_testList_0/200
jdk_lang_0
java/lang/String/concat/WithSecurityManager.java
