### ISSUE TITLE
jdk_security3_0_FAILED IOException: NSS initialization failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17137]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/112/)(`rhel9lert-2`):
```
java version "17.0.7" 2023-04-18
IBM Semeru Runtime Certified Edition 17.0.7+5 (build 17.0.7+5)
Eclipse OpenJ9 VM 17.0.7+5 (build master-ab86d5ac7, JRE 17 Linux ppc64le-64-Bit Compressed References 20230418_375 (JIT enabled, AOT enabled)
OpenJ9   - ab86d5ac7
OMR      - 2d7aff025
JCL      - c31cbd715b based on jdk-17.0.7+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F375%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK17U_2023-04-08-14-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F375%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK17U_2023-04-08-14-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-04-08T17:01:58.041Z] variation: Mode150
[2023-04-08T17:01:58.041Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-04-08T17:40:55.779Z] TEST: sun/security/pkcs11/Provider/Login.java

[2023-04-08T17:40:55.780Z] STDOUT:
[2023-04-08T17:40:55.780Z] config Login.setUp(): success
[2023-04-08T17:40:55.780Z] Beginning test run Login...
[2023-04-08T17:40:55.780Z] nssLibDir: /usr/lib64/
[2023-04-08T17:40:55.780Z] test Login.testLogin(): failure
[2023-04-08T17:40:55.780Z] java.security.ProviderException: Initialization failed
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:465)
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:144)
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:141)
[2023-04-08T17:40:55.780Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:141)
[2023-04-08T17:40:55.780Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:150)
[2023-04-08T17:40:55.780Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:142)
[2023-04-08T17:40:55.780Z] 	at PKCS11Test.testNSS(PKCS11Test.java:549)
[2023-04-08T17:40:55.780Z] 	at PKCS11Test.main(PKCS11Test.java:210)
[2023-04-08T17:40:55.780Z] 	at Login.testLogin(Login.java:58)
[2023-04-08T17:40:55.780Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-04-08T17:40:55.780Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-04-08T17:40:55.780Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-04-08T17:40:55.780Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2023-04-08T17:40:55.780Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2023-04-08T17:40:55.780Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2023-04-08T17:40:55.780Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2023-04-08T17:40:55.780Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2023-04-08T17:40:55.780Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2023-04-08T17:40:55.780Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2023-04-08T17:40:55.780Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2023-04-08T17:40:55.780Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2023-04-08T17:40:55.780Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2023-04-08T17:40:55.780Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2023-04-08T17:40:55.780Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2023-04-08T17:40:55.780Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2023-04-08T17:40:55.780Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2023-04-08T17:40:55.780Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2023-04-08T17:40:55.780Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2023-04-08T17:40:55.780Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2023-04-08T17:40:55.780Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-04-08T17:40:55.780Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-04-08T17:40:55.780Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-04-08T17:40:55.780Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-04-08T17:40:55.780Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-04-08T17:40:55.780Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-04-08T17:40:55.780Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: 0xCE534351(CKR_NSS_CERTDB_FAILED)
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_Initialize(Native Method)
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Initialize(PKCS11.java:1678)
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:213)
[2023-04-08T17:40:55.780Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:368)
[2023-04-08T17:40:55.780Z] 	... 42 more
[2023-04-08T17:40:55.780Z] 
[2023-04-08T17:40:55.780Z] ===============================================
[2023-04-08T17:40:55.780Z] sun/security/pkcs11/Provider/Login.java
[2023-04-08T17:40:55.780Z] Total tests run: 1, Passes: 0, Failures: 1, Skips: 0

[2023-04-08T17:41:02.701Z] TEST: sun/security/pkcs11/Secmod/AddPrivateKey.java

[2023-04-08T17:41:02.702Z] STDERR:
[2023-04-08T17:41:02.702Z] java.security.ProviderException: Could not initialize NSS
[2023-04-08T17:41:02.702Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:250)
[2023-04-08T17:41:02.702Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:144)
[2023-04-08T17:41:02.702Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:141)
[2023-04-08T17:41:02.702Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
[2023-04-08T17:41:02.702Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:141)
[2023-04-08T17:41:02.702Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:150)
[2023-04-08T17:41:02.702Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:142)
[2023-04-08T17:41:02.702Z] 	at AddPrivateKey.main(AddPrivateKey.java:76)
[2023-04-08T17:41:02.702Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-04-08T17:41:02.702Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-04-08T17:41:02.702Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-04-08T17:41:02.702Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-04-08T17:41:02.702Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-04-08T17:41:02.702Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-04-08T17:41:02.702Z] Caused by: java.io.IOException: NSS initialization failed
[2023-04-08T17:41:02.702Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.Secmod.initialize(Secmod.java:243)
[2023-04-08T17:41:02.702Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:245)
[2023-04-08T17:41:02.702Z] 	... 13 more
[2023-04-08T17:41:02.702Z] 
[2023-04-08T17:41:02.702Z] JavaTest Message: Test threw exception: java.security.ProviderException: Could not initialize NSS

[2023-04-08T18:56:30.730Z] Test results: passed: 823; failed: 6; error: 1
[2023-04-08T18:56:32.333Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_1680967014141/jdk_security3_0/report/html/report.html
[2023-04-08T18:56:32.333Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_1680967014141/jdk_security3_0/work
[2023-04-08T18:56:32.333Z] Error: Some tests failed or other problems occurred.
[2023-04-08T18:56:32.333Z] -----------------------------------
[2023-04-08T18:56:32.333Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32228/)

**Comment by pshipton** [comment]
This seems like a machine problem.
@jasonkatonica fyi

**Comment by JasonFengJ9** [comment]
@taoliult pls see my comments below
> Does the tests failed in FIPS mode or not?

The failed JVM is JDK17 `ppc64le_linux`, does it support FIPS mode? [java.security](https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/7285983e57bfb368fbb87e235acf2dafc600a3ad/src/java.base/share/conf/security/java.security#L85-L148) specifies `linux-x86` only for Java Restricted Security Mode which I assume is required by FIPS.
```
#ifdef linux-x86
#
# Java Restricted Security Mode
```

> If the failures are not in FIPS mode, then maybe an environment issue, rerun the tests to see if the issues are still there.

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32228/) passed in 3 machines, failed at [rhel9lert-1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/2399/console), with another infra error.
Launched another grinder at the same machine [10x grinder at rhel9lert-1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32287/)

> But, the SunPKCS11 can only be initialized once, and in our case, the SunPKCS11 is already initialized in NSS as FIPS mode, so it can not be initialize again by other NSS config files.

Since this is non-FIPS mode run, can the `SunPKCS11` still be initialized by others first, or is there another cause for the initialization failure besides multiple attempts?

**Comment by taoliult** [comment]
@JasonFengJ9 Sorry for replying late.

Right now, Semeru FIPS only support the Redhat linux x86 platform, it doesn't support the ppc64le.

You mentioned, launched another grinder at the same machine and all failed. Does this machine infrastructure/OS is same as the other 3 machines which you mentioned passed?

As I remember when I look at the SunPKCS11 provider, before initializing the nss secmod, it will check if the nss secmod is already initialized or not, if it already initialized, then it won't be initialized again. But in your failed case [rhel9lert-1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/2399/console), I see it failed at:

> 02:37:21  Caused by: java.io.IOException: NSS initialization failed
> 02:37:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.Secmod.initialize(Secmod.java:243)
> 02:37:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:245)
> 02:37:21  	... 13 more

It failed after check the "already initialized", which return false. That mean, the nss secmod is not initialized yet. So, next, it will try to initialize the nss secmod, but failed when initializing. So, the failures is not due to initialize twice. 

So, does the failed machine same as the other 3 passed machines? If there are same, then it should be a kind of machine issue. If there are not same, maybe, you can first try to run the same tests using another machine same as the failed one, to check if it is due to the machine issue or not.

**Comment by JasonFengJ9** [comment]
[JDK20 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_s390x_linux/12/) failed at a different machine `rhel9s390x-svl-rt2-1`.
```
[2023-06-09T23:51:13.185Z] variation: Mode650
[2023-06-09T23:51:13.185Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-06-10T00:27:01.446Z] TEST: sun/security/pkcs11/Secmod/AddPrivateKey.java

[2023-06-10T00:27:01.447Z] STDOUT:
[2023-06-10T00:27:01.447Z] nssLibDir: /usr/lib64/
[2023-06-10T00:27:01.447Z] STDERR:
[2023-06-10T00:27:01.447Z] java.security.ProviderException: Could not initialize NSS
[2023-06-10T00:27:01.447Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:255)
[2023-06-10T00:27:01.447Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:152)
[2023-06-10T00:27:01.447Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:149)
[2023-06-10T00:27:01.447Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
[2023-06-10T00:27:01.447Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:149)
[2023-06-10T00:27:01.447Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:150)
[2023-06-10T00:27:01.447Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:142)
[2023-06-10T00:27:01.447Z] 	at AddPrivateKey.main(AddPrivateKey.java:76)
[2023-06-10T00:27:01.447Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-06-10T00:27:01.447Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-06-10T00:27:01.447Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-06-10T00:27:01.447Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-06-10T00:27:01.447Z] Caused by: java.io.IOException: NSS initialization failed
[2023-06-10T00:27:01.447Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.Secmod.initialize(Secmod.java:243)
[2023-06-10T00:27:01.447Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:250)
[2023-06-10T00:27:01.447Z] 	... 11 more
[2023-06-10T00:27:01.447Z] 
[2023-06-10T00:27:01.447Z] JavaTest Message: Test threw exception: java.security.ProviderException: Could not initialize NSS

[2023-06-10T01:12:56.636Z] jdk_security3_1_FAILED
```

[30x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33362/)

**Comment by JasonFengJ9** [comment]
[JDK17 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_linux_testList_3/2/consoleFull)(`cent9x86-svl-rt2-1`)
https://hyc-runtimes-jenkins.swg-devops.com/computer/cent9x86-svl-rt2-1.fyre.ibm.com

```
23:48:39  openjdk version "17.0.10" 2024-01-16
23:48:39  IBM Semeru Runtime Open Edition 17.0.10.0-m2 (build 17.0.10+6)
23:48:39  Eclipse OpenJ9 VM 17.0.10.0-m2 (build v0.43.0-release-628037b26, JRE 17 Linux amd64-64-Bit Compressed References 20240116_631 (JIT enabled, AOT enabled)
23:48:39  OpenJ9   - 628037b26
23:48:39  OMR      - d810fcb98
23:48:39  JCL      - 6b8a7528cc1 based on jdk-17.0.10+6)

00:33:17  TEST: sun/security/pkcs11/Secmod/TrustAnchors.java

00:33:17  STDERR:
00:33:17  java.security.ProviderException: Could not initialize NSS
00:33:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:257)
00:33:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:151)
00:33:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:148)
00:33:17  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
00:33:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:148)
00:33:17  	at PKCS11Test.getSunPKCS11(PKCS11Test.java:150)
00:33:17  	at PKCS11Test.getSunPKCS11(PKCS11Test.java:142)
00:33:17  	at TrustAnchors.main(TrustAnchors.java:61)
00:33:17  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:33:17  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
00:33:17  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:33:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
00:33:17  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
00:33:17  	at java.base/java.lang.Thread.run(Thread.java:857)
00:33:17  Caused by: java.io.IOException: NSS initialization failed
00:33:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.Secmod.initialize(Secmod.java:243)
00:33:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:252)
00:33:17  	... 13 more
00:33:17  
00:33:17  JavaTest Message: Test threw exception: java.security.ProviderException: Could not initialize NSS

00:33:17  TEST RESULT: Failed. Execution failed: `main' threw exception: java.security.ProviderException: Could not initialize NSS
00:33:17  --------------------------------------------------
01:23:10  Test results: passed: 834; failed: 7; error: 1
01:23:22  Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux_testList_3/aqa-tests/TKG/output_17025293747823/jdk_security3_1/report/html/report.html
01:23:22  Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux_testList_3/aqa-tests/TKG/output_17025293747823/jdk_security3_1/work
01:23:22  Error: Some tests failed or other problems occurred.
01:23:22  -----------------------------------
01:23:22  jdk_security3_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK21 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_s390x_linux/26/)(`rhel9s390x-svl-rt4-1`)
```
openjdk version "21.0.1" 2023-10-17 LTS
IBM Semeru Runtime Open Edition 21.0.1.0-m3 (build 21.0.1+12-LTS)
Eclipse OpenJ9 VM 21.0.1.0-m3 (build v0.42.0-release-69b6ceb69, JRE 21 Linux s390x-64-Bit Compressed References 20231017_74 (JIT enabled, AOT enabled)
OpenJ9   - 69b6ceb69
OMR      - 494d6eb66
JCL      - 5846adac994 based on jdk-21.0.1+12)

[2024-01-05T07:22:13.657Z] variation: Mode150
[2024-01-05T07:22:13.657Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-01-05T07:51:18.721Z] STDERR:
[2024-01-05T07:51:18.721Z] java.security.ProviderException: Could not initialize NSS
[2024-01-05T07:51:18.721Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:262)
[2024-01-05T07:51:18.721Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:159)
[2024-01-05T07:51:18.721Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:156)
[2024-01-05T07:51:18.721Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
[2024-01-05T07:51:18.721Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:156)
[2024-01-05T07:51:18.721Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:154)
[2024-01-05T07:51:18.721Z] 	at PKCS11Test.getSunPKCS11(PKCS11Test.java:146)
[2024-01-05T07:51:18.721Z] 	at TrustAnchors.main(TrustAnchors.java:61)
[2024-01-05T07:51:18.721Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-01-05T07:51:18.721Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-01-05T07:51:18.721Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-01-05T07:51:18.721Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-01-05T07:51:18.721Z] Caused by: java.io.IOException: NSS initialization failed
[2024-01-05T07:51:18.721Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.Secmod.initialize(Secmod.java:243)
[2024-01-05T07:51:18.721Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:257)
[2024-01-05T07:51:18.721Z] 	... 11 more
[2024-01-05T07:51:18.721Z] 
[2024-01-05T07:51:18.721Z] JavaTest Message: Test threw exception: java.security.ProviderException: Could not initialize NSS

[2024-01-05T08:41:04.878Z] Test results: passed: 898; failed: 7; error: 1
[2024-01-05T08:41:37.257Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_17044343482978/jdk_security3_0/report/html/report.html
[2024-01-05T08:41:37.257Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_17044343482978/jdk_security3_0/work
[2024-01-05T08:41:37.257Z] Error: Some tests failed or other problems occurred.
[2024-01-05T08:41:37.772Z] -----------------------------------
[2024-01-05T08:41:37.772Z] jdk_security3_0_FAILED
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37157/)

**Comment by pshipton** [comment]
I'd bet this is a machine setup issue.
