### ISSUE TITLE
OpenJDK java/util/concurrent/CyclicBarrier/Basic.java 3 not equal to 4

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17209]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Release/56
java/util/concurrent/CyclicBarrier/Basic.java
```
20:45:53  STDERR:
20:45:53  java.lang.Throwable
20:45:53  	at java.lang.Thread.dumpStack(Thread.java:496)
20:45:53  	at Basic.fail(Basic.java:407)
20:45:53  	at Basic.fail(Basic.java:408)
20:45:53  	at Basic.equal(Basic.java:413)
20:45:53  	at Basic.testInterrupts(Basic.java:396)
20:45:53  	at Basic.realMain(Basic.java:280)
20:45:53  	at Basic.main(Basic.java:415)
20:45:53  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:45:53  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:45:53  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:45:53  	at java.lang.reflect.Method.invoke(Method.java:498)
20:45:53  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:45:53  	at java.lang.Thread.run(Thread.java:826)
20:45:53  java.lang.AssertionError: Some tests failed
20:45:53  	at Basic.main(Basic.java:417)
20:45:53  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:45:53  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:45:53  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:45:53  	at java.lang.reflect.Method.invoke(Method.java:498)
20:45:53  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:45:53  	at java.lang.Thread.run(Thread.java:826)
20:45:53  
20:45:53  JavaTest Message: Test threw exception: java.lang.AssertionError
20:45:53  JavaTest Message: shutting down test
20:45:53  
20:45:53  STDOUT:
20:45:53  OK!
20:45:53  OK!
20:45:53  OK!
20:45:53  OK!
20:45:53  3 not equal to 4
20:45:53  
20:45:53  Passed = 310, failed = 1
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/207
jdk_util_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_OpenJDK11_testList_0/32

**Comment by hzongaro** [comment]
Except for the [one blip earlier this year](#issuecomment-2671998853), we haven't seen this problem frequently, so I'm going to push this issue out to the "Future" release for now.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OMR_testList_2/451
