### ISSUE TITLE
zlinux JCL_Test_SM_2 -XX:+CompactStrings test_setSecurityManager3 Not found expected error string

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17228]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/60/
JCL_Test_SM_2 `-XX:+CompactStrings`
```
Exception in thread "(unnamed thread)" java/lang/Error: JVM can't set custom SecurityManager due to java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System_SM$TestSecurityManagerNonPublicConstructor.<init>()
	at java/lang/System.initSecurityManager (java.base@17.0.7-internal/System.java:808)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@17.0.7-internal/ClassLoader.java:225)
	at java/lang/Thread.initialize (java.base@17.0.7-internal/Thread.java:441)
	at java/lang/Thread.<init> (java.base@17.0.7-internal/Thread.java:168)
...
FAILED: test_setSecurityManager3
java.lang.AssertionError: Not found expected error string: java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System_SM$TestSecurityManagerNonPublicConstructor.<init>(), but got: 
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.support.Support_Exec.checkStderr(Support_Exec.java:135) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.support.Support_Exec.execJava(Support_Exec.java:83) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.java.lang.Test_System_SM.test_setSecurityManager3(Test_System_SM.java:121) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from jrt:/java.base
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) from jrt:/java.base
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) from jrt:/java.base
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@94ce4fff(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Release_testList_1/aqa-tests/TKG/lib/testng.jar)
```

**Comment by pshipton** [comment]
Ran it again and it passed.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/609
JCL_Test_SM_1 `-XX:RecreateClassfileOnload`
```
FAILED: test_setSecurityManager3
java.lang.AssertionError: Not found expected error string: java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System_SM$TestSecurityManagerNonPublicConstructor.<init>(), but got: 
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@f3609993(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.support.Support_Exec.checkStderr(Support_Exec.java:135) from jdk.internal.loader.ClassLoaders$AppClassLoader@f3609993(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.support.Support_Exec.execJava(Support_Exec.java:83) from jdk.internal.loader.ClassLoaders$AppClassLoader@f3609993(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.java.lang.Test_System_SM.test_setSecurityManager3(Test_System_SM.java:121) from jdk.internal.loader.ClassLoaders$AppClassLoader@f3609993(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/665/
JCL_Test_SM_none_SCC_0
```
Exception in thread "main" java/lang/Error: JVM can't set custom SecurityManager due to java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System_SM$TestSecurityManagerNonPublicConstructor.<init>()
	at java/lang/System.initSecurityManager (java.base@11.0.22-internal/System.java:785)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@11.0.22-internal/ClassLoader.java:223)
	at java/lang/Thread.initialize (java.base@11.0.22-internal/Thread.java:427)
	at java/lang/Thread.<init> (java.base@11.0.22-internal/Thread.java:162)

...
FAILED: test_setSecurityManager3
java.lang.AssertionError: Not found expected error string: java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System_SM$TestSecurityManagerNonPublicConstructor.<init>(), but got: 
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@203ab78d(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.support.Support_Exec.checkStderr(Support_Exec.java:135) from jdk.internal.loader.ClassLoaders$AppClassLoader@203ab78d(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.support.Support_Exec.execJava(Support_Exec.java:83) from jdk.internal.loader.ClassLoaders$AppClassLoader@203ab78d(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at org.openj9.test.java.lang.Test_System_SM.test_setSecurityManager3(Test_System_SM.java:121) from jdk.internal.loader.ClassLoaders$AppClassLoader@203ab78d(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_1/439
JCL_Test_SM_none_SCC_1 
```
08:03:13  FAILED: test_setSecurityManager3
08:03:13  java.lang.AssertionError: Not found expected error string: java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System_SM$TestSecurityManagerNonPublicConstructor.<init>(), but got: 
08:03:13  	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@88088f9e(file:/home/jenkins/testDependency/lib/testng.jar)
08:03:13  	at org.openj9.test.support.Support_Exec.checkStderr(Support_Exec.java:135) from jdk.internal.loader.ClassLoaders$AppClassLoader@88088f9e(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
08:03:13  	at org.openj9.test.support.Support_Exec.execJava(Support_Exec.java:83) from jdk.internal.loader.ClassLoaders$AppClassLoader@88088f9e(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
08:03:13  	at org.openj9.test.java.lang.Test_System_SM.test_setSecurityManager3(Test_System_SM.java:121) from jdk.internal.loader.ClassLoaders$AppClassLoader@88088f9e(file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_1/545

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/1052
JCL_Test_SM_none_SCC_0
```
05:34:23  FAILED: test_setSecurityManager3
05:34:23  java.lang.AssertionError: Not found expected error string: java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System_SM$TestSecurityManagerNonPublicConstructor.<init>(), but got: 
05:34:23  	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@fb99cffe(file:/home/jenkins/testDependency/lib/testng.jar)
05:34:23  	at org.openj9.test.support.Support_Exec.checkStderr(Support_Exec.java:135) from jdk.internal.loader.ClassLoaders$AppClassLoader@fb99cffe(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
05:34:23  	at org.openj9.test.support.Support_Exec.execJava(Support_Exec.java:83) from jdk.internal.loader.ClassLoaders$AppClassLoader@fb99cffe(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
05:34:23  	at org.openj9.test.java.lang.Test_System_SM.test_setSecurityManager3(Test_System_SM.java:121) from jdk.internal.loader.ClassLoaders$AppClassLoader@fb99cffe(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by 0xdaryl** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_1/623/
JCL_Test_SM_none_SCC_1

OMR Acceptance build

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/1082
JCL_Test_SM_none_SCC_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_0/825
