### ISSUE TITLE
OpenJDK java/lang/Thread/virtual/Collectable.java timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17241]
java/lang/Thread/virtual/Collectable.java
```
00:17:34  Timeout information:
00:17:34  Running jcmd on process 5492
00:17:34  Dump written to C:\Users\jenkins\workspace\Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16820440904923\jdk_lang_j9_0\work\scratch\1\core.20230421.001701.5492.0001.dmp
00:17:34  Dump written to C:\Users\jenkins\workspace\Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly\aqa-tests\TKG\output_16820440904923\jdk_lang_j9_0\work\scratch\1\javacore.20230421.001730.5492.0002.txt
00:17:34  Running jstack on process 5492
00:17:34  2023-04-21T00:17:31.156015900
00:17:34  Virtual machine: 5492 JVM information:
00:17:34  JRE 20 Windows Server 2019 amd64-64-Bit 20230420_42 (JIT enabled, AOT enabled)
00:17:34  OpenJ9   - 36c047f9db3
00:17:34  OMR      - 97cf2a6e860
00:17:34  JCL      - 38d10ea9b95 based on jdk-20+36
00:17:34  
00:17:34  "main" prio=5 Id=2 WAITING
00:17:34  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
00:17:34  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
00:17:34  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
00:17:34  	at java.base@20-internal/java.lang.Thread.join(Thread.java:2147)
00:17:34  	at java.base@20-internal/java.lang.Thread.join(Thread.java:2223)
00:17:34  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:72)
00:17:34  
00:17:34  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
00:17:34  
00:17:34  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
00:17:34  
00:17:34  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
00:17:34  
00:17:34  "JIT Diagnostic Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
00:17:34  
00:17:34  "JIT-SamplerThread" prio=10 Id=8 TIMED_WAITING
00:17:34  
00:17:34  "IProfiler" prio=5 Id=9 RUNNABLE
00:17:34  
00:17:34  "Common-Cleaner" prio=8 Id=3 TIMED_WAITING
00:17:34  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
00:17:34  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
00:17:34  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
00:17:34  	at java.base@20-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
00:17:34  	at java.base@20-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
00:17:34  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
00:17:34  	at java.base@20-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
00:17:34  
00:17:34  "Dedicated GC Main" prio=5 Id=10 RUNNABLE
00:17:34  
00:17:34  "GC Worker" prio=5 Id=11 RUNNABLE
00:17:34  
00:17:34  "GC Worker" prio=5 Id=12 RUNNABLE
00:17:34  
00:17:34  "GC Worker" prio=5 Id=13 RUNNABLE
00:17:34  
00:17:34  "Attach API wait loop" prio=10 Id=16 RUNNABLE
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
00:17:34  
00:17:34  "MainThread" prio=5 Id=18 TIMED_WAITING
00:17:34  	at java.base@20-internal/java.lang.Thread.sleepImpl(Native Method)
00:17:34  	at java.base@20-internal/java.lang.Thread.sleep0(Thread.java:496)
00:17:34  	at java.base@20-internal/java.lang.Thread.sleep(Thread.java:491)
00:17:34  	at app//Collectable.waitUntilCleared(Collectable.java:66)
00:17:34  	at app//Collectable.testUnstartedThread(Collectable.java:47)
00:17:34  	at java.base@20-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:17:34  	at java.base@20-internal/java.lang.reflect.Method.invoke(Method.java:578)
00:17:34  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
00:17:34  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
00:17:34  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
00:17:34  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
00:17:34  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
00:17:34  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
00:17:34  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
00:17:34  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
00:17:34  	at java.base@20-internal/java.util.ArrayList.forEach(ArrayList.java:1511)
00:17:34  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
00:17:34  	at app//org.testng.TestRunner.run(TestRunner.java:585)
00:17:34  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
00:17:34  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
00:17:34  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
00:17:34  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
00:17:34  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
00:17:34  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
00:17:34  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
00:17:34  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
00:17:34  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
00:17:34  	at app//org.testng.TestNG.run(TestNG.java:1037)
00:17:34  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
00:17:34  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
00:17:34  	at java.base@20-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:17:34  	at java.base@20-internal/java.lang.reflect.Method.invoke(Method.java:578)
00:17:34  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
00:17:34  	at java.base@20-internal/java.lang.Thread.run(Thread.java:1639)
00:17:34  
00:17:34  "Finalizer thread" prio=5 Id=19 RUNNABLE
00:17:34  
00:17:34  "file lock watchdog" prio=10 Id=24 TIMED_WAITING
00:17:34  	at java.base@20-internal/java.lang.Object.waitImpl(Native Method)
00:17:34  	at java.base@20-internal/java.lang.Object.wait(Object.java:255)
00:17:34  	at java.base@20-internal/java.lang.Object.wait(Object.java:221)
00:17:34  	at java.base@20-internal/java.util.TimerThread.mainLoop(Timer.java:569)
00:17:34  	at java.base@20-internal/java.util.TimerThread.run(Timer.java:522)
00:17:34  
00:17:34  "Attachment portNumber: 53518" prio=10 Id=26 RUNNABLE
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
00:17:34  	at java.base@20-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
00:17:34  
00:17:34  
00:17:34  --- Timeout information end.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_OMR/2
jdk_lang_j9_0

**Comment by babsingh** [comment]
[Collectable.java](https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/openj9/test/jdk/java/lang/Thread/virtual/Collectable.java) verifies that an unstarted virtual thread can be GC'ed. The test timeouts since it is indefinitely stuck in the loop which waits for `WeakReference.get()` to be NULL. The failure is intermittent, and it looks like the GC is unable to collect the unstarted virtual thread.

fyi @LinHu2016 @amicic @dmitripivkine @fengxue-IS @tajila 

```
00:17:34  "MainThread" prio=5 Id=18 TIMED_WAITING
00:17:34  	at java.base@20-internal/java.lang.Thread.sleepImpl(Native Method)
00:17:34  	at java.base@20-internal/java.lang.Thread.sleep0(Thread.java:496)
00:17:34  	at java.base@20-internal/java.lang.Thread.sleep(Thread.java:491)
00:17:34  	at app//Collectable.waitUntilCleared(Collectable.java:66)
00:17:34  	at app//Collectable.testUnstartedThread(Collectable.java:47)
```

**Comment by dmitripivkine** [comment]
Virtual Thread object can't be collected because there is an O-slot in  JIT method ` Collectable.waitUntilCleared(Ljava/lang/ref/WeakReference;)V` (hard root for GC):
```
<1e093868c00> JIT frame: bp = 0x000001E093976B48, pc = 0x00007FFB17F6F65D, unwindSP = 0x000001E093976B10, cp = 0x000001E0939592D0, arg0EA = 0x000001E093976B50, jitInfo = 0x000001E093DE4328
<1e093868c00> 	Method: Collectable.waitUntilCleared(Ljava/lang/ref/WeakReference;)V !j9method 0x000001E093958688
<1e093868c00> 	Bytecode index = 13, inlineDepth = 0, PC offset = 0xFFFFFFFFFFFFAA7D
<1e093868c00> 	stackMap=0x000001E093DE4449, slots=I16(0x0001) parmBaseOffset=I16(0x0008), parmSlots=U16(0x0001), localBaseOffset=I16(0xFFE8)
<1e093868c00> 	Described JIT args starting at 0x000001E093976B50 for U16(0x0001) slots
<1e093868c00> 		O-Slot: : a0[0x000001E093976B50] = 0x00007FF4BF3FBB78
<1e093868c00> 	Described JIT temps starting at 0x000001E093976B30 for IDATA(0x0000000000000003) slots
<1e093868c00> 		O-Slot: : t2[0x000001E093976B30] = 0x00007FF4BF3FB900 <---- // java/lang/VirtualThread
<1e093868c00> 		O-Slot: : t1[0x000001E093976B38] = 0x0000000000000000
<1e093868c00> 		O-Slot: : t0[0x000001E093976B40] = 0x0000000000000000
<1e093868c00> 	JIT-RegisterMap = UDATA(0x0000000000000000)
<1e093868c00> 	JIT-Frame-RegisterMap[0x000001E093976AE8] = UDATA(0x0000000000000001) (jit_rbx)
<1e093868c00> 	JIT-Frame-RegisterMap[0x000001E093976AF0] = UDATA(0x000001E0F41EF380) (jit_r9)
<1e093868c00> I2J values: PC = 0x000001E0939391EE, A0 = 0x000001E093976B88, walkSP = 0x000001E093976B60, literals = 0x000001E093958648, JIT PC = 0x00007FFB2C045780, pcAddress = 0x000000146CBFF978, decomp = 0x0000000000000000

> !fj9object 0x7ff4bf3fb900
!J9Object 0x00007FF4BF3FB900 {
	struct J9Class* clazz = !j9class 0x1E093570600 // java/lang/VirtualThread
	Object flags = 0x0000001A;
	J lockword = 0x0000000000000000 (offset = 0) (java/lang/Object) <hidden>
	J eetop = 0x0000000000000000 (offset = 8) (java/lang/Thread)
	J tid = 0x0000000000000016 (offset = 16) (java/lang/Thread)
	Ljava/lang/String; name = !fj9object 0x7ff4bf634f50 (offset = 40) (java/lang/Thread)
	Z interrupted = 0x00000000 (offset = 152) (java/lang/Thread)
	Ljava/lang/ClassLoader; contextClassLoader = !fj9object 0x7ff4bf49b660 (offset = 48) (java/lang/Thread)
	Ljava/security/AccessControlContext; inheritedAccessControlContext = !fj9object 0x7ff4bf4d1a10 (offset = 56) (java/lang/Thread)
	Ljava/lang/Thread$FieldHolder; holder = !fj9object 0x0 (offset = 64) (java/lang/Thread)
	Ljava/lang/ThreadLocal$ThreadLocalMap; threadLocals = !fj9object 0x0 (offset = 72) (java/lang/Thread)
	Ljava/lang/ThreadLocal$ThreadLocalMap; inheritableThreadLocals = !fj9object 0x7ff4bf3fba00 (offset = 80) (java/lang/Threa

d)
	Ljava/lang/Object; scopedValueBindings = !fj9object 0x7ff4bf674438 (offset = 88) (java/lang/Thread)
	Ljava/lang/Object; interruptLock = !fj9object 0x7ff4bf3fb9f0 (offset = 96) (java/lang/Thread)
	Ljava/lang/Object; parkBlocker = !fj9object 0x0 (offset = 104) (java/lang/Thread)
	Lsun/nio/ch/Interruptible; nioBlocker = !fj9object 0x0 (offset = 112) (java/lang/Thread)
	Ljdk/internal/vm/Continuation; cont = !fj9object 0x0 (offset = 120) (java/lang/Thread)
	Ljava/lang/Thread$UncaughtExceptionHandler; uncaughtExceptionHandler = !fj9object 0x0 (offset = 128) (java/lang/Thread)
	J threadLocalRandomSeed = 0x0000000000000000 (offset = 24) (java/lang/Thread)
	I threadLocalRandomProbe = 0x00000000 (offset = 156) (java/lang/Thread)
	I threadLocalRandomSecondarySeed = 0x00000000 (offset = 160) (java/lang/Thread)
	Ljdk/internal/vm/ThreadContainer; container = !fj9object 0x0 (offset = 136) (java/lang/Thread)
	Ljdk/internal/vm/StackableScope; headStackableScopes = !fj9object 0x0 (offset = 144) (java/lang/Thread)
	Z started = 0x00000000 (offset = 164) (java/lang/Thread)
	J tls = 0x0000000000000000 (offset = 32) (java/lang/Thread) <hidden>
	Ljava/util/concurrent/Executor; scheduler = !fj9object 0x7ff4bf5544b0 (offset = 176) (java/lang/VirtualThread)
	Ljdk/internal/vm/Continuation; cont = !fj9object 0x7ff4bf3fbaf0 (offset = 184) (java/lang/VirtualThread)
	Ljava/lang/Runnable; runContinuation = !fj9object 0x7ff4bf3fbb60 (offset = 192) (java/lang/VirtualThread)
	I state = 0x00000000 (offset = 216) (java/lang/VirtualThread)
	Z parkPermit = 0x00000000 (offset = 220) (java/lang/VirtualThread)
	Ljava/lang/Thread; carrierThread = !fj9object 0x0 (offset = 200) (java/lang/VirtualThread)
	Ljava/util/concurrent/CountDownLatch; termination = !fj9object 0x0 (offset = 208) (java/lang/VirtualThread)
	J inspectorCount = 0x0000000000000000 (offset = 168) (java/lang/VirtualThread) <hidden>
	I isSuspendedByJVMTI = 0x00000000 (offset = 224) (java/lang/VirtualThread) <hidden>
}
```

**Comment by dmitripivkine** [comment]
You can try to run test with `-Xjit:enableAggressiveLiveness` option. It might prevent store of the object pointer in O-slot

**Comment by babsingh** [comment]
No failures seen in a 100x grinder with `-Xjit:enableAggressiveLiveness`: https://openj9-jenkins.osuosl.org/job/Grinder/2349/. @dmitripivkine Will it be possible to pass the test without `-Xjit:enableAggressiveLiveness`?

**Comment by dmitripivkine** [comment]
> No failures seen in a 100x grinder with `-Xjit:enableAggressiveLiveness`: https://openj9-jenkins.osuosl.org/job/Grinder/2349/.
> 
> @dmitripivkine Will it be possible to pass the test without `-Xjit:enableAggressiveLiveness`?

The O-slot pointed to objects expected to be collected prevents successful test pass. This extra O-slot is created a a part of JIT optimization. So, "as-is" test might be completed successfully in Interpreter mode or with JIT optimization disabled by `-Xjit:enableAggressiveLiveness` only.
@0xdaryl FYI

**Comment by 0xdaryl** [comment]
We have seen a number of problems like this before where a test has been crafted to expect certain GC behaviour at points in a method.  In those cases the tests have been considered questionably valid because GC determinacy is not spec'ed behaviour.  Because of this, the JIT takes certain freedoms with it when applying optimizations.  I analyzed one of these problems in greater depth a few years back and wrote up the following then, which still seems relevant to this current problem -> https://github.com/eclipse-openj9/openj9/issues/8897#issuecomment-607897793

Attempts to work around this problem for a particular test or pattern are generally fragile.  The proper "fix" is to run a liveness analysis at lower optimization levels to identify these dead slots.  But we don't run liveness at cold because of the compile-time cost and impact to startup time.  Running with `-Xjit:enableAggressiveLiveness` essentially just adds the liveness pass into the cold strategy.

We may need to add that option to the playlist for this test.

**Comment by babsingh** [comment]
The below PRs will run the `Collectable` test w/ `-Xjit:enableAggressiveLiveness`:
- JDK20: https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/47
- JDK-next: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/601

**Comment by babsingh** [comment]
Closing. The PRs in https://github.com/eclipse-openj9/openj9/issues/17241#issuecomment-1552062370 have been merged.
