### ISSUE TITLE
OpenJDK java/lang/reflect/sealed_classes/SealedClassesReflectionTest NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17254]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_Nightly/458
jdk_lang_j9_0
`-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs`
java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java
```
21:47:53  test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@70990632, 1, [Ljava.lang.String;@888743ca, [Ljava.lang.Class;@f2592a5c, [LSealedClassesReflectionTest$SealedStatus;@f06de4ec): failure
21:47:53  java.lang.NullPointerException
21:47:53  	at java.base/java.lang.Class.forNameImpl(Native Method)
21:47:53  	at java.base/java.lang.Class.getPermittedSubclasses(Class.java:4949)
21:47:53  	at SealedClassesReflectionTest.testSealedReflection(SealedClassesReflectionTest.java:216)
```

**Comment by cjjdespres** [comment]
This has also started showing up on the internal JITServer nightly tests on `ppc64le`, I think, e.g. in `/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_jit_Personal/563`:

```
05:22:29          -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseJITServer -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs' \
05:22:29          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseJITServer -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-Xjit -J-Xgcpolicy:balanced -J-Xnocompressedrefs' \

05:22:29  ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
05:22:29  REASON: User specified action: run testng/othervm --enable-preview SealedClassesReflectionTest 
05:22:29  TIME:   0.533 seconds
05:22:29  messages:
05:22:29  command: testng --enable-preview SealedClassesReflectionTest
05:22:29  reason: User specified action: run testng/othervm --enable-preview SealedClassesReflectionTest 
05:22:29  Mode: othervm [/othervm specified]
05:22:29  elapsed time (seconds): 0.533
05:22:29  configuration:
05:22:29  STDOUT:

05:22:29  test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@d2ff1d62, 1, [Ljava.lang.String;@e59ec3c1, [Ljava.lang.Class;@31b3384a, [LSealedClassesReflectionTest$SealedStatus;@f3b2d0ec): failure
05:22:29  java.lang.NullPointerException
05:22:29  	at java.base/java.lang.Class.forNameImpl(Native Method)
05:22:29  	at java.base/java.lang.Class.getPermittedSubclasses(Class.java:4949)
05:22:29  	at SealedClassesReflectionTest.testSealedReflection(SealedClassesReflectionTest.java:216)
```

**Comment by pshipton** [comment]
This appears to be a bug that only affects the balanced gc policy.

@dmitripivkine @tajila unless you can spot something wrong, I'll see about obtaining a core file for the failure so we can diagnose futher.

https://github.com/eclipse-openj9/openj9/blob/master/runtime/jcl/common/reflecthelp.c#L1993-L2054

**Comment by pshipton** [comment]
No reproductions so perhaps this is a JIT issue and we need to run all jdk_lang_j9 to reproduce it.

**Comment by tajila** [comment]
Ill make a fix

**Comment by pshipton** [comment]
Another failure
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/459

**Comment by pshipton** [comment]
I'll close this assuming fixed and reopen if it's seen again.
