### ISSUE TITLE
mac10-x86-3 ERROR: Cannot delete workspace

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17269]
https://openj9-jenkins.osuosl.org/computer/mac10-x86-3 needs a reboot at least, and perhaps some cleanup.

I've been seeing many failures related to mac10-x86-3. For now I've disabled it.

Some examples:

https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_mac_OpenJDK/440/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/506/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly/454/console

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Rebooted. Nothing in /tmp or WORKSPACE to cleanup. Machine isn't coming back up though. I will follow up with UNB folks.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Personal/497/console
```
13:37:04  ERROR: Cannot delete workspace :Remote call on mac10-x86-3 failed
```

Disabled it again.

**Comment by pshipton** [comment]
It can run some things successfully, but I don't want it randomly failing jobs any more.

https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_extended.system_x86-64_mac_Nightly_testList_0/21

**Comment by AdamBrousseau** [comment]
Try again [![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Pipeline-Build-Test-Personal&build=393)](https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/393/)

**Comment by AdamBrousseau** [comment]
Still failing. Disabled again.

**Comment by pshipton** [comment]
See also https://github.com/eclipse-openj9/openj9/issues/17357

**Comment by AdamBrousseau** [comment]
Machine has been rebuilt. Labels added back.

**Comment by pshipton** [comment]
Disabled it.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/662/
```
21:06:33  Uploading to 'unb'...
[Pipeline] getArtifactoryServer
21:06:32  Executing command: /bin/sh -c git log --pretty=format:%s -1
[Pipeline] newBuildInfo
[Pipeline] echo
21:06:42  buildInfo.name:Build_JDK11_x86-64_mac_Nightly
[Pipeline] retry
[Pipeline] {
[Pipeline] artifactoryUpload
21:06:51  Executing command: /bin/sh -c git log --pretty=format:%s -1
21:06:56  [consumer_0] Deploying artifact: https://ub18p8art.casa.cs.unb.ca/artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/662/OpenJ9-JDK11-x86-64_mac-20231016-201408.tar.gz
[Pipeline] }
21:07:00  ERROR: Execution failed
21:07:00  java.lang.Exception: Error occurred during operation, please refer to logs for more information.
21:07:00  	at org.jfrog.build.extractor.producerConsumer.ProducerConsumerExecutor.start(ProducerConsumerExecutor.java:85)
21:07:00  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:101)
21:07:00  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:166)
21:07:00  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to mac10-x86-3
21:07:00  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
21:07:00  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
21:07:00  		at hudson.remoting.Channel.call(Channel.java:1000)
21:07:00  		at hudson.FilePath.act(FilePath.java:1192)
21:07:00  		at hudson.FilePath.act(FilePath.java:1181)
21:07:00  		at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:56)
21:07:00  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:66)
21:07:00  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:53)
21:07:00  		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:55)
21:07:00  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
21:07:00  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
21:07:00  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:07:00  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:07:00  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:07:00  		at java.base/java.lang.Thread.run(Thread.java:829)
21:07:00  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 3482d81d-18ab-4b89-8562-537e8eae6124
21:07:00  Caused: java.lang.RuntimeException: Failed uploading artifacts by spec
21:07:00  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:168)
21:07:00  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:117)
21:07:00  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
21:07:00  	at app//hudson.remoting.UserRequest.perform(UserRequest.java:211)
21:07:00  	at app//hudson.remoting.UserRequest.perform(UserRequest.java:54)
21:07:00  	at app//hudson.remoting.Request$2.run(Request.java:377)
21:07:00  	at app//hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
21:07:00  	at java.base@11.0.20.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:07:00  	at java.base@11.0.20.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:07:00  	at java.base@11.0.20.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:07:00  	at java.base@11.0.20.1/java.lang.Thread.run(Thread.java:839)
21:07:00  Retrying
[Pipeline] {
[Pipeline] sleep
21:07:01  Sleeping for 5 min 0 sec
21:07:00  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
21:07:00  Error occurred for request PUT /artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/662/OpenJ9-JDK11-x86-64_mac-20231016-201408.tar.gz;build.parentNumber=1942;build.parentName=Pipeline_Build_Test_JDK11_x86-64_mac;build.buildIdentifier=Nightly;build.timestamp=1697500650998;build.name=Build_JDK11_x86-64_mac_Nightly;build.number=662 HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
21:07:00  [consumer_0] An exception occurred during execution:
21:07:00  java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:07:00  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
21:07:00  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
21:07:00  	at java.base/java.lang.Thread.run(Thread.java:839)
21:07:00  Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:07:00  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
21:07:00  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:360)
21:07:00  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
21:07:00  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:298)
21:07:00  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
21:07:00  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
21:07:00  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
21:07:00  	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
21:07:00  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
21:07:00  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
21:07:00  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
21:07:00  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
21:07:00  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1511)
21:07:00  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
21:07:00  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
21:07:00  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
21:07:00  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
21:07:00  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
21:07:00  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
21:07:00  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
21:07:00  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
21:07:00  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
21:07:00  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
21:07:00  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
21:07:00  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
21:07:00  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
21:07:00  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
21:07:00  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
21:07:00  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:76)
21:07:00  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:64)
21:07:00  	at org.jfrog.build.client.JFrogHttpClient.sendRequest(JFrogHttpClient.java:137)
21:07:00  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:112)
21:07:00  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
21:07:00  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:284)
21:07:00  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:279)
21:07:00  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
21:07:00  	... 2 more
21:07:00  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:07:00  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
21:07:00  	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
21:07:00  	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
21:07:00  	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
21:07:00  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
21:07:00  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
21:07:00  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
21:07:00  	... 33 more
21:07:00  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:07:00  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
21:07:00  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127)
21:07:00  	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
21:07:00  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
21:07:00  	... 39 more
21:07:00  
[Pipeline] artifactoryUpload
21:12:06  Executing command: /bin/sh -c git log --pretty=format:%s -1
[Pipeline] }
21:12:12  ERROR: Execution failed
21:12:12  java.lang.Exception: Error occurred during operation, please refer to logs for more information.
21:12:12  	at org.jfrog.build.extractor.producerConsumer.ProducerConsumerExecutor.start(ProducerConsumerExecutor.java:85)
21:12:12  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:101)
21:12:12  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:166)
21:12:12  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to mac10-x86-3
21:12:12  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
21:12:12  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
21:12:12  		at hudson.remoting.Channel.call(Channel.java:1000)
21:12:12  		at hudson.FilePath.act(FilePath.java:1192)
21:12:12  		at hudson.FilePath.act(FilePath.java:1181)
21:12:12  		at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:56)
21:12:12  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:66)
21:12:12  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:53)
21:12:12  		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:55)
21:12:12  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
21:12:12  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
21:12:12  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:12:12  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:12:12  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:12:12  		at java.base/java.lang.Thread.run(Thread.java:829)
21:12:12  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 99058ed8-69df-497f-8388-002d0ad57764
21:12:12  Caused: java.lang.RuntimeException: Failed uploading artifacts by spec
21:12:12  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:168)
21:12:12  	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:117)
21:12:12  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
21:12:12  	at app//hudson.remoting.UserRequest.perform(UserRequest.java:211)
21:12:12  	at app//hudson.remoting.UserRequest.perform(UserRequest.java:54)
21:12:12  	at app//hudson.remoting.Request$2.run(Request.java:377)
21:12:12  	at app//hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
21:12:12  	at java.base@11.0.20.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:12:12  	at java.base@11.0.20.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:12:12  	at java.base@11.0.20.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:12:12  	at java.base@11.0.20.1/java.lang.Thread.run(Thread.java:839)
21:12:12  Retrying
[Pipeline] {
[Pipeline] sleep
21:12:12  Sleeping for 5 min 0 sec
21:12:11  [consumer_0] Deploying artifact: https://ub18p8art.casa.cs.unb.ca/artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/662/OpenJ9-JDK11-x86-64_mac-20231016-201408.tar.gz
21:12:11  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
21:12:11  Error occurred for request PUT /artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/662/OpenJ9-JDK11-x86-64_mac-20231016-201408.tar.gz;build.parentNumber=1942;build.parentName=Pipeline_Build_Test_JDK11_x86-64_mac;build.buildIdentifier=Nightly;build.timestamp=1697500650998;build.name=Build_JDK11_x86-64_mac_Nightly;build.number=662 HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
21:12:11  [consumer_0] An exception occurred during execution:
21:12:11  java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:12:11  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
21:12:11  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
21:12:11  	at java.base/java.lang.Thread.run(Thread.java:839)
21:12:11  Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:12:11  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
21:12:11  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:360)
21:12:11  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
21:12:11  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:298)
21:12:11  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
21:12:11  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
21:12:11  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
21:12:11  	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
21:12:11  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
21:12:11  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
21:12:11  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
21:12:11  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
21:12:11  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1511)
21:12:11  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
21:12:11  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
21:12:11  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
21:12:11  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
21:12:11  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
21:12:11  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
21:12:11  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
21:12:11  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
21:12:11  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
21:12:11  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
21:12:11  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
21:12:11  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
21:12:11  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
21:12:11  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
21:12:11  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
21:12:11  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:76)
21:12:11  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:64)
21:12:11  	at org.jfrog.build.client.JFrogHttpClient.sendRequest(JFrogHttpClient.java:137)
21:12:11  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:112)
21:12:11  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
21:12:11  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:284)
21:12:11  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:279)
21:12:11  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
21:12:11  	... 2 more
21:12:11  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:12:11  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
21:12:11  	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
21:12:11  	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
21:12:11  	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
21:12:11  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
21:12:11  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
21:12:11  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
21:12:11  	... 33 more
21:12:11  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
21:12:11  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
21:12:11  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127)
21:12:11  	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
21:12:11  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
21:12:11  	... 39 more
```

**Comment by mahdipub** [comment]
The problem was because we missed the part mentioned in https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/ARTIFACTORY.md
It have to be resolved now. The job https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/664/console will determine.

**Comment by mahdipub** [comment]
@pshipton seems it is now working.

**Comment by pshipton** [comment]
Thanks.
