### ISSUE TITLE
JDK20 jdk_security4_1_FAILED IOException: Too short

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17268]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_aarch64_mac/4/)(`macaarch64rt5`):
```
openjdk version "20" 2023-03-21
IBM Semeru Runtime Open Edition 20+36 (build 20+36)
Eclipse OpenJ9 VM 20+36 (build master-78a79a0ec, JRE 20 Mac OS X aarch64-64-Bit 20230321_9 (JIT enabled, AOT enabled)
OpenJ9   - 78a79a0ec
OMR      - 97cf2a6e8
JCL      - 38d10ea9b based on jdk-20+36)
```
[Rerun in Grinder]([Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security4_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-mac-aarch64-openj9%2F9%2Fibm-semeru-open-jdk_aarch64_mac_JDK20U_2023-04-24-10-33.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-mac-aarch64-openj9%2F9%2Fibm-semeru-open-testimage_aarch64_mac_JDK20U_2023-04-24-10-33.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=20&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk20&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None)) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-04-24T17:30:33.308Z] variation: Mode650
[2023-04-24T17:30:33.308Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-04-24T17:30:58.495Z] TEST: sun/security/krb5/auto/BasicProc.java

[2023-04-24T17:30:58.497Z] STDERR:
[2023-04-24T17:30:58.497Z] java.lang.Exception: Proc abnormal end
[2023-04-24T17:30:58.497Z] 	at jdk.test.lib.process.Proc.readData(Proc.java:377)
[2023-04-24T17:30:58.497Z] 	at BasicProc.once(BasicProc.java:275)
[2023-04-24T17:30:58.497Z] 	at BasicProc.main(BasicProc.java:146)
[2023-04-24T17:30:58.497Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-24T17:30:58.497Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-24T17:30:58.497Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-04-24T17:30:58.497Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-04-24T17:30:58.497Z] 
[2023-04-24T17:30:58.497Z] JavaTest Message: Test threw exception: java.lang.Exception: Proc abnormal end

[2023-04-24T17:31:03.708Z] TEST: sun/security/krb5/auto/DiffSaltParams.java

[2023-04-24T17:31:03.711Z] STDERR:
[2023-04-24T17:31:03.711Z] javax.security.auth.login.LoginException: Too short
[2023-04-24T17:31:03.711Z] 	at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:789)
[2023-04-24T17:31:03.711Z] 	at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:597)
[2023-04-24T17:31:03.711Z] 	at Context.fromUserPass(Context.java:190)
[2023-04-24T17:31:03.711Z] 	at Context.fromUserPass(Context.java:147)
[2023-04-24T17:31:03.711Z] 	at DiffSaltParams.main(DiffSaltParams.java:48)
[2023-04-24T17:31:03.711Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-24T17:31:03.711Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-24T17:31:03.711Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-04-24T17:31:03.711Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-04-24T17:31:03.711Z] Caused by: java.io.IOException: Too short
[2023-04-24T17:31:03.711Z] 	at java.base/sun.security.util.DerValue.<init>(DerValue.java:364)
[2023-04-24T17:31:03.711Z] 	at java.base/sun.security.util.DerInputStream.getDerValue(DerInputStream.java:110)
[2023-04-24T17:31:03.711Z] 	at java.security.jgss/sun.security.krb5.internal.KRBError.init(KRBError.java:318)
[2023-04-24T17:31:03.711Z] 	at java.security.jgss/sun.security.krb5.internal.KRBError.<init>(KRBError.java:191)
[2023-04-24T17:31:03.711Z] 	at java.security.jgss/sun.security.krb5.KrbAsRep.<init>(KrbAsRep.java:63)
[2023-04-24T17:31:03.711Z] 	at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.send(KrbAsReqBuilder.java:345)
[2023-04-24T17:31:03.711Z] 	at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
[2023-04-24T17:31:03.711Z] 	at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:751)
[2023-04-24T17:31:03.711Z] 	... 8 more
[2023-04-24T17:31:03.711Z] 
[2023-04-24T17:31:03.711Z] JavaTest Message: Test threw exception: javax.security.auth.login.LoginException: Too short

[2023-04-24T17:31:20.264Z] TEST: sun/security/krb5/auto/HttpNegotiateServer.java

[2023-04-24T17:31:20.267Z] java.lang.RuntimeException: Test error
[2023-04-24T17:31:20.267Z] 	at HttpNegotiateServer.main(HttpNegotiateServer.java:246)
[2023-04-24T17:31:20.267Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-24T17:31:20.267Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-24T17:31:20.267Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-04-24T17:31:20.267Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-04-24T17:31:20.267Z] 
[2023-04-24T17:31:20.267Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Test error

[2023-04-24T17:31:20.268Z] TEST: sun/security/krb5/auto/HttpsCB.java
[2023-04-24T17:31:20.270Z] java.lang.RuntimeException: assertEquals: expected false to equal true
[2023-04-24T17:31:20.270Z] 	at jdk.test.lib.Asserts.fail(Asserts.java:594)
[2023-04-24T17:31:20.270Z] 	at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
[2023-04-24T17:31:20.270Z] 	at jdk.test.lib.Asserts.assertEquals(Asserts.java:189)
[2023-04-24T17:31:20.270Z] 	at jdk.test.lib.Asserts.assertEQ(Asserts.java:166)
[2023-04-24T17:31:20.270Z] 	at HttpsCB.main(HttpsCB.java:193)
[2023-04-24T17:31:20.270Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-24T17:31:20.270Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-24T17:31:20.270Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-04-24T17:31:20.270Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-04-24T17:31:20.270Z] 
[2023-04-24T17:31:20.270Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: assertEquals: expected false to equal true

[2023-04-24T17:31:21.569Z] TEST: sun/security/krb5/auto/KdcPolicy.java

[2023-04-24T17:31:21.571Z] --------------- ERROR END ---------------
[2023-04-24T17:31:21.571Z] STDERR:
[2023-04-24T17:31:21.571Z] java.lang.Exception: Does not match. Output is c30000-
[2023-04-24T17:31:21.571Z] 	at KdcPolicy.test(KdcPolicy.java:299)
[2023-04-24T17:31:21.571Z] 	at KdcPolicy.run(KdcPolicy.java:107)
[2023-04-24T17:31:21.571Z] 	at KdcPolicy.main0(KdcPolicy.java:85)
[2023-04-24T17:31:21.571Z] 	at KdcPolicy.main(KdcPolicy.java:58)
[2023-04-24T17:31:21.571Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-24T17:31:21.571Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-24T17:31:21.571Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-04-24T17:31:21.571Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-04-24T17:31:21.571Z] 
[2023-04-24T17:31:21.571Z] JavaTest Message: Test threw exception: java.lang.Exception: Does not match. Output is c30000-

[2023-04-24T17:31:50.050Z] TEST: sun/security/krb5/auto/ReferralsTest.java

[2023-04-24T17:31:50.051Z] JavaTest Message: Test threw exception: javax.security.auth.login.LoginException: Too short

[2023-04-24T17:31:50.051Z] TEST RESULT: Failed. Execution failed: `main' threw exception: javax.security.auth.login.LoginException: Too short
[2023-04-24T17:31:50.051Z] --------------------------------------------------
[2023-04-24T17:32:46.340Z] Test results: passed: 146; failed: 6
[2023-04-24T17:32:46.340Z] Report written to /Users/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_aarch64_mac/aqa-tests/TKG/output_16823545846257/jdk_security4_1/report/html/report.html
[2023-04-24T17:32:46.340Z] Results written to /Users/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_aarch64_mac/aqa-tests/TKG/output_16823545846257/jdk_security4_1/work
[2023-04-24T17:32:46.340Z] Error: Some tests failed or other problems occurred.
[2023-04-24T17:32:46.709Z] -----------------------------------
[2023-04-24T17:32:46.709Z] jdk_security4_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32490/) - all failed

Also seen [JDK20 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_ppc64_aix/3/) [JDK20 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_ppc64le_linux/4/)

**Comment by pshipton** [comment]
Seems like a dup of https://github.com/eclipse-openj9/openj9/issues/17279

**Comment by JasonFengJ9** [comment]
Closing..
