### ISSUE TITLE
JDK20 java/util/concurrent/ExecutorService/CloseTest.java AssertionError: expected [true] but found [false]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17270]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_testList_0/8/)(`paix825`):
```
openjdk version "20" 2023-03-21
IBM Semeru Runtime Open Edition 20+36 (build 20+36)
Eclipse OpenJ9 VM 20+36 (build master-78a79a0ec, JRE 20 AIX ppc64-64-Bit Compressed References 20230321_9 (JIT enabled, AOT enabled)
OpenJ9   - 78a79a0ec
OMR      - 97cf2a6e8
JCL      - 38d10ea9b based on jdk-20+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_util_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk20_j9_sanity.openjdk_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-aix-ppc64-openj9%2F9%2Fibm-semeru-open-jdk_ppc64_aix_JDK20U_2023-04-24-10-33.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-aix-ppc64-openj9%2F9%2Fibm-semeru-open-testimage_ppc64_aix_JDK20U_2023-04-24-10-33.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=20&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk20&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=8&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-04-24T14:55:14.546Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2023-04-24T14:55:14.546Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2023-04-24T15:01:03.256Z] TEST: java/util/concurrent/ExecutorService/CloseTest.java

[2023-04-24T15:01:03.257Z] java.lang.AssertionError: expected [true] but found [false]
[2023-04-24T15:01:03.257Z] 	at org.testng.Assert.fail(Assert.java:99)
[2023-04-24T15:01:03.257Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2023-04-24T15:01:03.257Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2023-04-24T15:01:03.257Z] 	at org.testng.Assert.assertTrue(Assert.java:55)
[2023-04-24T15:01:03.257Z] 	at CloseTest.testShutdownBeforeClose(CloseTest.java:111)

[2023-04-24T15:01:03.257Z] ===============================================
[2023-04-24T15:01:03.257Z] java/util/concurrent/ExecutorService/CloseTest.java
[2023-04-24T15:01:03.257Z] Total tests run: 36, Passes: 35, Failures: 1, Skips: 0

[2023-04-24T15:46:22.895Z] Test results: passed: 924; failed: 1
[2023-04-24T15:46:56.060Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_16823452445650/jdk_util_1/report/html/report.html
[2023-04-24T15:46:56.060Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_16823452445650/jdk_util_1/work
[2023-04-24T15:46:56.060Z] Error: Some tests failed or other problems occurred.
[2023-04-24T15:46:56.060Z] -----------------------------------
[2023-04-24T15:46:56.060Z] jdk_util_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32491/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_OpenJDK21_testList_0/1
jdk_util_1
java/util/concurrent/ExecutorService/CloseTest.java

```
04:18:02  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@4e807370): failure
04:18:02  java.lang.AssertionError: expected [true] but found [false]
04:18:02  	at org.testng.Assert.fail(Assert.java:99)
04:18:02  	at org.testng.Assert.failNotEquals(Assert.java:1037)
04:18:02  	at org.testng.Assert.assertTrue(Assert.java:45)
04:18:02  	at org.testng.Assert.assertTrue(Assert.java:55)
04:18:02  	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/36/
jdk_util_1
java/util/concurrent/ExecutorService/CloseTest.java

```
18:58:44  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@b4ab6f3f): failure
18:58:44  java.lang.AssertionError: expected [true] but found [false]
18:58:44  	at org.testng.Assert.fail(Assert.java:99)
18:58:44  	at org.testng.Assert.failNotEquals(Assert.java:1037)
18:58:44  	at org.testng.Assert.assertTrue(Assert.java:45)
18:58:44  	at org.testng.Assert.assertTrue(Assert.java:55)
18:58:44  	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/54/
java/util/concurrent/ExecutorService/CloseTest.java
```
23:14:00  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@12744b6b): failure
23:14:00  java.lang.AssertionError: expected [true] but found [false]
23:14:00  	at org.testng.Assert.fail(Assert.java:99)
23:14:00  	at org.testng.Assert.failNotEquals(Assert.java:1037)
23:14:00  	at org.testng.Assert.assertTrue(Assert.java:45)
23:14:00  	at org.testng.Assert.assertTrue(Assert.java:55)
23:14:00  	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/118
jdk_util_0
java/util/concurrent/ExecutorService/CloseTest.java
```
19:58:13  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@ccab335a): failure
19:58:13  java.lang.AssertionError: expected [true] but found [false]
19:58:13  	at org.testng.Assert.fail(Assert.java:99)
19:58:13  	at org.testng.Assert.failNotEquals(Assert.java:1037)
19:58:13  	at org.testng.Assert.assertTrue(Assert.java:45)
19:58:13  	at org.testng.Assert.assertTrue(Assert.java:55)
19:58:13  	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/210
jdk_util_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/118
jdk_util_0
java/util/concurrent/ExecutorService/CloseTest.java
```
07:59:11  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@b8052a6): failure
07:59:11  java.lang.AssertionError: expected [true] but found [false]
07:59:11  	at org.testng.Assert.fail(Assert.java:99)
07:59:11  	at org.testng.Assert.failNotEquals(Assert.java:1037)
07:59:11  	at org.testng.Assert.assertTrue(Assert.java:45)
07:59:11  	at org.testng.Assert.assertTrue(Assert.java:55)
07:59:11  	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by JasonFengJ9** [comment]
[JDK21 x86-64_mac 0.46.1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_testList_2/10/)(`mac10x64rt08`)
```
java version "21.0.4" 2024-07-16 LTS
IBM Semeru Runtime Certified Edition 21.0.4.1-rc1 (build 21.0.4+7-LTS)
Eclipse OpenJ9 VM 21.0.4.1-rc1 (build v0.46.1-release-4760d5d320, JRE 21 Mac OS X amd64-64-Bit Compressed References 20240716_252 (JIT enabled, AOT enabled)
OpenJ9   - 4760d5d320
OMR      - 840a9adba
JCL      - 6232a5d28a1 based on jdk-21.0.4+7)

[2024-09-05T15:45:50.548Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2024-09-05T15:45:50.548Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2024-09-05T15:48:12.039Z] TEST: java/util/concurrent/ExecutorService/CloseTest.java

[2024-09-05T15:48:12.040Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@975f41cf): failure
[2024-09-05T15:48:12.040Z] java.lang.AssertionError: expected [true] but found [false]
[2024-09-05T15:48:12.040Z] 	at org.testng.Assert.fail(Assert.java:99)
[2024-09-05T15:48:12.040Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2024-09-05T15:48:12.040Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2024-09-05T15:48:12.040Z] 	at org.testng.Assert.assertTrue(Assert.java:55)
[2024-09-05T15:48:12.040Z] 	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)

[2024-09-05T15:48:12.040Z] java/util/concurrent/ExecutorService/CloseTest.java
[2024-09-05T15:48:12.040Z] Total tests run: 36, Passes: 35, Failures: 1, Skips: 0

[2024-09-05T15:58:01.905Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_1/329/
jdk_util_0
java/util/concurrent/ExecutorService/CloseTest.java
```
21:16:38  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@4b51b629): failure
21:16:38  java.lang.AssertionError: expected [true] but found [false]
21:16:38  	at org.testng.Assert.fail(Assert.java:99)
21:16:38  	at org.testng.Assert.failNotEquals(Assert.java:1037)
21:16:38  	at org.testng.Assert.assertTrue(Assert.java:45)
21:16:38  	at org.testng.Assert.assertTrue(Assert.java:55)
21:16:38  	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/171
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/439
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/480
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OpenJDK21_testList_0/50
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/503
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/575
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/300/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/612
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/624

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_sanity.openjdk_x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_testList_1/427/)
```
[2025-12-06T19:48:13.094Z] Running test jdk_concurrent_0 ...
[2025-12-06T19:48:13.094Z] ===============================================
[2025-12-06T19:48:13.094Z] jdk_concurrent_0 Start Time: Sat Dec  6 14:48:05 2025 Epoch Time (ms): 1765050485682
[2025-12-06T19:48:13.094Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2025-12-06T19:48:13.094Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2025-12-06T19:48:59.199Z] TEST: java/util/concurrent/ExecutorService/CloseTest.java

[2025-12-06T19:48:59.200Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@a47db810): failure
[2025-12-06T19:48:59.200Z] java.lang.AssertionError: expected [true] but found [false]
[2025-12-06T19:48:59.200Z] 	at org.testng.Assert.fail(Assert.java:99)
[2025-12-06T19:48:59.200Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2025-12-06T19:48:59.200Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2025-12-06T19:48:59.200Z] 	at org.testng.Assert.assertTrue(Assert.java:55)
[2025-12-06T19:48:59.200Z] 	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OpenJDK21_testList_2/77

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_sanity.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_testList_1/593/)
```
[2026-03-27T17:26:29.909Z] Running test jdk_collections_0 ...
[2026-03-27T17:26:29.909Z] ===============================================
[2026-03-27T17:26:29.909Z] jdk_collections_0 Start Time: Fri Mar 27 10:26:28 2026 Epoch Time (ms): 1774632388342
[2026-03-27T17:26:29.909Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2026-03-27T17:26:29.909Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2026-03-27T17:30:03.668Z] TEST: java/util/concurrent/ExecutorService/CloseTest.java

[2026-03-27T17:30:03.677Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@e96b4cd0): failure [125ms]
[2026-03-27T17:30:03.677Z] java.lang.AssertionError: expected [true] but found [false]
[2026-03-27T17:30:03.677Z] 	at org.testng.Assert.fail(Assert.java:99)
[2026-03-27T17:30:03.677Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2026-03-27T17:30:03.677Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2026-03-27T17:30:03.677Z] 	at org.testng.Assert.assertTrue(Assert.java:55)
[2026-03-27T17:30:03.677Z] 	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_3/20

**Comment by matthewhall2** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Personal_testList_3/23/
```
[2026-06-15T05:54:52.097Z] ===============================================
[2026-06-15T05:54:52.097Z] Running test jdk_concurrent_0 ...
[2026-06-15T05:54:52.097Z] ===============================================
[2026-06-15T05:54:52.097Z] jdk_concurrent_0 Start Time: Mon Jun 15 05:54:52 2026 Epoch Time (ms): 1781502892033
[2026-06-15T05:54:52.097Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2026-06-15T05:54:52.097Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2026-06-15T05:56:18.307Z] TEST: java/util/concurrent/ExecutorService/CloseTest.java

[2026-06-15T05:56:18.309Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@fa000684): failure [17ms]
[2026-06-15T05:56:18.309Z] java.lang.AssertionError: expected [true] but found [false]
[2026-06-15T05:56:18.309Z] 	at org.testng.Assert.fail(Assert.java:99)
[2026-06-15T05:56:18.309Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2026-06-15T05:56:18.309Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2026-06-15T05:56:18.309Z] 	at org.testng.Assert.assertTrue(Assert.java:55)
[2026-06-15T05:56:18.309Z] 	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
[2026-06-15T05:56:18.309Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2026-06-15T05:56:18.309Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2026-06-15T05:56:18.309Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2026-06-15T05:56:18.310Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[2026-06-15T05:56:18.310Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2026-06-15T05:56:18.310Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2026-06-15T05:56:18.310Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2026-06-15T05:56:18.310Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2026-06-15T05:56:18.310Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2026-06-15T05:56:18.310Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2026-06-15T05:56:18.310Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2026-06-15T05:56:18.310Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2026-06-15T05:56:18.310Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2026-06-15T05:56:18.310Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2026-06-15T05:56:18.310Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2026-06-15T05:56:18.310Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2026-06-15T05:56:18.310Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:107)
[2026-06-15T05:56:18.310Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2026-06-15T05:56:18.310Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2026-06-15T05:56:18.310Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:335)
[2026-06-15T05:56:18.310Z] 	at java.base/java.lang.Thread.run(Thread.java:1600)
```

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_sanity.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_testList_2/347/)
```
[2026-07-07T16:26:35.349Z] Running test jdk_collections_1 ...
[2026-07-07T16:26:35.349Z] ===============================================
[2026-07-07T16:26:35.349Z] jdk_collections_1 Start Time: Tue Jul  7 18:26:33 2026 Epoch Time (ms): 1783441593409
[2026-07-07T16:26:35.349Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650

[2026-07-07T16:30:56.846Z] TEST: java/util/concurrent/ExecutorService/CloseTest.java

[2026-07-07T16:30:56.854Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@9c1de38c): failure [9ms]
[2026-07-07T16:30:56.854Z] java.lang.AssertionError: expected [true] but found [false]
[2026-07-07T16:30:56.854Z] 	at org.testng.Assert.fail(Assert.java:99)
[2026-07-07T16:30:56.854Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2026-07-07T16:30:56.854Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2026-07-07T16:30:56.854Z] 	at org.testng.Assert.assertTrue(Assert.java:55)
[2026-07-07T16:30:56.854Z] 	at CloseTest.testShutdownBeforeClose(CloseTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_Nightly_testList_2/730/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_3/82
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_3/81
