### ISSUE TITLE
Jep442Tests_testLinkerFfi_DownCall and Jep442Tests_testLinkerFfi_UpCall fail against hotspot 

### ISSUE THREAD

**Issue by smlambert** [eclipse-openj9/openj9#17288]
Failure link
------------

Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/adoptium/aqa-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include: 

https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.functional_aarch64_linux/29/

- rerun [link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=testList+TESTLIST=Jep442Tests_testLinkerFfi_DownCall_0,Jep442Tests_testLinkerFfi_UpCall_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): functional
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): Jep442Tests_testLinkerFfi_DownCall and Jep442Tests_testLinkerFfi_UpCall 
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): presumably all
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 

Optional info
-------------

- intermittent failure (yes|no): no
- regression or new test:  new test
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output (captured from console output)
---------------------------------------------
```
Jep442Tests_testLinkerFfi_DownCall_0 Start Time: Tue Apr 25 22:25:28 2023 Epoch Time (ms): 1682461528012
variation: --enable-preview
JVM_OPTIONS:  --enable-preview 

TEST SETUP:
Nothing to be done for setup.

TESTING:
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

org.testng.TestNGException: 
An error occurred while instantiating class org.openj9.test.jep442.downcall.InvalidDownCallTests: no clinkerffitests in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:435)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
	at org.testng.TestClass.getInstances(TestClass.java:95)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:81)
	at org.testng.TestClass.init(TestClass.java:73)
	at org.testng.TestClass.<init>(TestClass.java:38)
	at org.testng.TestRunner.initMethods(TestRunner.java:389)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.UnsatisfiedLinkError: no clinkerffitests in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2449)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:912)
	at java.base/java.lang.System.loadLibrary(System.java:2057)
	at org.openj9.test.jep442.downcall.InvalidDownCallTests.<clinit>(InvalidDownCallTests.java:57)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:547)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:497)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:24)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:423)
	... 21 more
-----------------------------------
Jep442Tests_testLinkerFfi_DownCall_0_FAILED
```

Related to the introduction of new tests via https://github.com/eclipse-openj9/openj9/pull/17188.  We do not build OpenJ9 test natives for hotspot, so any test calling into OpenJ9 natives should be disabled for hotspot.

**Comment by llxia** [comment]
Jep442Tests_testLinkerFfi_DownCall has `<impl>hotspot</impl>` in the playlist.xml. @ChengJin01 Is it intended?

**Comment by ChengJin01** [comment]
> Jep442Tests_testLinkerFfi_DownCall has `<impl>hotspot</impl>` in the playlist.xml. @ChengJin01 Is it intended?

Initially we verified the part of tests in the test suite to see how it works on Hotspot but it should be removed eventually as the test suite is only intended for OpenJ9 (most of tests should work on Hotspot but we handle exceptions/errors with different messages Hotspot in which case it is inappropriate to enable them on Hotspot)
