### ISSUE TITLE
FIPS com/sun/jndi/ldap/LdapCBPropertiesTest.java SSLHandshakeException: no cipher suites in common

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17284]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux_fips/39/)(`rhel8x64-fips2-1`):
```
openjdk version "19.0.2" 2023-01-17
IBM Semeru Runtime Open Edition 19.0.2.0 (build 19.0.2+7)
Eclipse OpenJ9 VM 19.0.2.0 (build openj9-0.37.0, JRE 19 Linux amd64-64-Bit Compressed References 20230117_89 (JIT enabled, AOT enabled)
OpenJ9   - 227d4781d
OMR      - d0b42675f
JCL      - ce73ec79299 based on jdk-19.0.2+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_other_1&amp;TEST_FLAG=FIPS&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F89%2Fibm-semeru-open-jdk_x64_linux_19.0.2_7_openj9-0.37.0.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19u%2Fjdk19u-linux-x64-openj9%2F89%2Fibm-semeru-open-testimage_x64_linux_19.0.2_7_openj9-0.37.0.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=j9.0.37-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.37.0-release&amp;OPENJ9_BRANCH=v0.37.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.37.0-release&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-04-21T18:42:08.373Z] variation: Mode650
[2023-04-21T18:42:08.373Z] JVM_OPTIONS:  -XX:-UseCompressedOops  -Dsemeru.fips=true

[2023-04-21T18:43:19.853Z] TEST: com/sun/jndi/ldap/LdapCBPropertiesTest.java

[2023-04-21T18:43:19.854Z] STDERR:
[2023-04-21T18:43:19.854Z] Apr 21, 2023 11:43:18 AM BaseLdapServer start
[2023-04-21T18:43:19.854Z] INFO: Starting server at port 37,995
[2023-04-21T18:43:19.854Z] Apr 21, 2023 11:43:18 AM BaseLdapServer acceptConnections
[2023-04-21T18:43:19.854Z] INFO: Server is accepting connections at port 37,995
[2023-04-21T18:43:19.854Z] Apr 21, 2023 11:43:18 AM BaseLdapServer acceptConnections
[2023-04-21T18:43:19.854Z] INFO: Accepted new connection at SSLSocket[hostname=127.0.0.1, port=42336, Session(1682102598182|SSL_NULL_WITH_NULL_NULL)]
[2023-04-21T18:43:19.854Z] javax.net.ssl.SSLHandshakeException: no cipher suites in common
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:305)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.ServerHello$T12ServerHelloProducer.chooseCipherSuite(ServerHello.java:471)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.ServerHello$T12ServerHelloProducer.produce(ServerHello.java:297)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:440)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1109)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:842)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:801)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:925)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1016)
[2023-04-21T18:43:19.854Z] 	at java.base/java.io.InputStream.read(InputStream.java:217)
[2023-04-21T18:43:19.854Z] 	at BaseLdapServer.handleConnection(BaseLdapServer.java:142)
[2023-04-21T18:43:19.854Z] 	at BaseLdapServer.lambda$acceptConnections$0(BaseLdapServer.java:99)
[2023-04-21T18:43:19.854Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[2023-04-21T18:43:19.854Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2023-04-21T18:43:19.854Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2023-04-21T18:43:19.854Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2023-04-21T18:43:19.854Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2023-04-21T18:43:19.854Z] Apr 21, 2023 11:43:18 AM BaseLdapServer close
[2023-04-21T18:43:19.854Z] INFO: Stopping server at port 37,995
[2023-04-21T18:43:19.854Z] javax.naming.AuthenticationException: GSSAPI [Root exception is javax.security.sasl.SaslException: TLS Handshake Exception  [Caused by javax.naming.CommunicationException [Root exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure]]]
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.sasl.LdapSasl.saslBind(LdapSasl.java:216)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:240)
[2023-04-21T18:43:19.854Z] Apr 21, 2023 11:43:18 AM BaseLdapServer acceptConnections
[2023-04-21T18:43:19.854Z] INFO: Server stopped accepting connections at port 37,995
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2895)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
[2023-04-21T18:43:19.854Z] 	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
[2023-04-21T18:43:19.854Z] 	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
[2023-04-21T18:43:19.854Z] 	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
[2023-04-21T18:43:19.854Z] 	at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
[2023-04-21T18:43:19.854Z] 	at java.naming/javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:130)
[2023-04-21T18:43:19.854Z] 	at LdapCBPropertiesTest.doClientSide(LdapCBPropertiesTest.java:143)
[2023-04-21T18:43:19.854Z] 	at LdapCBPropertiesTest.<init>(LdapCBPropertiesTest.java:104)
[2023-04-21T18:43:19.854Z] 	at LdapCBPropertiesTest.main(LdapCBPropertiesTest.java:89)
[2023-04-21T18:43:19.854Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-04-21T18:43:19.854Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-04-21T18:43:19.854Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-04-21T18:43:19.854Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)
[2023-04-21T18:43:19.854Z] Caused by: javax.security.sasl.SaslException: TLS Handshake Exception  [Caused by javax.naming.CommunicationException [Root exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure]]
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.Connection.getTlsServerCertificate(Connection.java:1062)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.sasl.LdapSasl.saslBind(LdapSasl.java:144)
[2023-04-21T18:43:19.854Z] 	... 20 more
[2023-04-21T18:43:19.854Z] Caused by: javax.naming.CommunicationException [Root exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure]
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.Connection.cleanup(Connection.java:663)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.Connection.run(Connection.java:1002)
[2023-04-21T18:43:19.854Z] 	... 1 more
[2023-04-21T18:43:19.854Z] Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:286)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:925)
[2023-04-21T18:43:19.854Z] 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1016)
[2023-04-21T18:43:19.854Z] 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:255)
[2023-04-21T18:43:19.854Z] 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:310)
[2023-04-21T18:43:19.854Z] 	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:382)
[2023-04-21T18:43:19.854Z] 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:361)
[2023-04-21T18:43:19.854Z] 	at java.naming/com.sun.jndi.ldap.Connection.run(Connection.java:860)
[2023-04-21T18:43:19.854Z] 	... 1 more
[2023-04-21T18:43:19.854Z] 
[2023-04-21T18:43:19.854Z] JavaTest Message: Test threw exception: javax.naming.AuthenticationException: GSSAPI [Root exception is javax.security.sasl.SaslException: TLS Handshake Exception  [Caused by javax.naming.CommunicationException [Root exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure]]]
[2023-04-21T18:43:19.854Z] JavaTest Message: shutting down test
[2023-04-21T18:43:19.854Z] 
[2023-04-21T18:43:19.854Z] STATUS:Failed.`main' threw exception: javax.naming.AuthenticationException: GSSAPI [Root exception is javax.security.sasl.SaslException: TLS Handshake Exception [Caused by javax.naming.CommunicationException [Root exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure]]]

[2023-04-21T18:46:48.764Z] Test results: passed: 263; failed: 1
[2023-04-21T18:46:52.502Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux_fips/aqa-tests/TKG/output_1682101246613/jdk_other_1/report/html/report.html
[2023-04-21T18:46:52.502Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux_fips/aqa-tests/TKG/output_1682101246613/jdk_other_1/work
[2023-04-21T18:46:52.502Z] Error: Some tests failed or other problems occurred.
[2023-04-21T18:46:52.502Z] -----------------------------------
[2023-04-21T18:46:52.502Z] jdk_other_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32527/) - all failed

**Comment by pshipton** [comment]
FIPS not supported for Java 19.
