### ISSUE TITLE
JDK21 Jep425Tests_testVirtualThread failures

### ISSUE THREAD

**Issue by mikezhang1234567890** [eclipse-openj9/openj9#17280]
Failure link
------------

Build: [JDK21 linux x86-64 nightly](https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDKnext_x86-64_linux_Nightly/80/)

[Internal grinder link](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32521/) - 10x, consistently fails

[Rerun in grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=Jep425Tests_testVirtualThread&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=15&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_x86-64_linux_Nightly%2F80%2FOpenJ9-JDKnext-x86-64_linux-20230424-194901.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_x86-64_linux_Nightly%2F80%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=&USER_CREDENTIALS_ID=&DOCKER_REGISTRY_URL=&ITERATIONS=10&EXIT_FAILURE=false&EXIT_SUCCESS=false&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=main&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&TKG_ITERATIONS=1&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=functional&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&BUILDS_TO_KEEP=100&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=NodesByIterations)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
16:54:35  FAILED: test_RunningVirtualThreadGetStackTrace
16:54:35  java.lang.AssertionError: expected [4] but found [3]
16:54:35  	at org.testng.Assert.fail(Assert.java:96)
16:54:35  	at org.testng.Assert.failNotEquals(Assert.java:776)
16:54:35  	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
16:54:35  	at org.testng.Assert.assertEquals(Assert.java:118)
16:54:35  	at org.testng.Assert.assertEquals(Assert.java:652)
16:54:35  	at org.testng.Assert.assertEquals(Assert.java:662)
16:54:35  	at org.openj9.test.jep425.VirtualThreadTests.test_RunningVirtualThreadGetStackTrace(VirtualThreadTests.java:234)
16:54:35  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
16:54:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
16:54:35  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
16:54:35  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
16:54:35  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
16:54:35  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
16:54:35  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
16:54:35  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
16:54:35  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
16:54:35  	at org.testng.TestRunner.run(TestRunner.java:505)
16:54:35  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
16:54:35  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
16:54:35  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
16:54:35  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
16:54:35  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
16:54:35  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
16:54:35  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
16:54:35  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
16:54:35  	at org.testng.TestNG.runSuites(TestNG.java:1049)
16:54:35  	at org.testng.TestNG.run(TestNG.java:1017)
16:54:35  	at org.testng.TestNG.privateMain(TestNG.java:1354)
16:54:35  	at org.testng.TestNG.main(TestNG.java:1323)
16:54:35  
16:54:35  FAILED: test_YieldedVirtualThreadGetStackTrace
16:54:35  java.lang.AssertionError: Expected 12 frames, got 10
16:54:35  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
16:54:35  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
16:54:35  	at org.openj9.test.jep425.VirtualThreadTests.test_YieldedVirtualThreadGetStackTrace(VirtualThreadTests.java:205)
16:54:35  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
16:54:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
16:54:35  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
16:54:35  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
16:54:35  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
16:54:35  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
16:54:35  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
16:54:35  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
16:54:35  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
16:54:35  	at org.testng.TestRunner.run(TestRunner.java:505)
16:54:35  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
16:54:35  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
16:54:35  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
16:54:35  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
16:54:35  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
16:54:35  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
16:54:35  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
16:54:35  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
16:54:35  	at org.testng.TestNG.runSuites(TestNG.java:1049)
16:54:35  	at org.testng.TestNG.run(TestNG.java:1017)
16:54:35  	at org.testng.TestNG.privateMain(TestNG.java:1354)
16:54:35  	at org.testng.TestNG.main(TestNG.java:1323)
```

fyi @fengxue-IS

**Comment by fengxue-IS** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/1edf1e6ea5b6bcb6a9f2df18d6c98eb4e0a86865 introduced changes to the vthread.run method, which removed the lambda call. will have to investigate more on the additional the missing frame in yielded case, but I assume should be similar problem.

**Comment by thallium** [comment]
> [ibmruntimes/openj9-openjdk-jdk@1edf1e6](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/1edf1e6ea5b6bcb6a9f2df18d6c98eb4e0a86865) introduced changes to the vthread.run method, which removed the lambda call. will have to investigate more on the additional the missing frame in yielded case, but I assume should be similar problem.

@fengxue-IS the additional missing is due to the `@hidden` annotation added to `yieldContinuation`.

**Comment by fengxue-IS** [comment]
@thallium please open a PR to correct the testcase for Java21

**Comment by thallium** [comment]
Test failure of test_jniFromVirtualthread is also observed.

```
FAILED: test_jniFromVirtualthread
java.lang.AssertionError: expected [WAITING] but found [TERMINATED]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:442)
        at org.openj9.test.jep425.VirtualThreadTests.test_jniFromVirtualthread(VirtualThreadTests.java:158)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.testng.TestNG.privateMain(TestNG.java:1354)
        at org.testng.TestNG.main(TestNG.java:1323)
```
