### ISSUE TITLE
cmdLineTester_criu_nonPortableRestoreJDK11Up testThreadPark Error (criu/util.c:457): Can't read link of fd -404

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17296]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/523
cmdLineTester_criu_nonPortableRestoreJDK11Up_2 `-Xjit:count=0 -XX:+CRIURestoreNonPortableMode`
```
Testing: Create CRIU checkpoint image and restore once - testThreadPark
Test start time: 2023/04/26 04:56:09 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 -XX:+CRIURestoreNonPortableMode  -Xtrace:print={j9criu} --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/openj9.internal.criu=ALL-UNNAMED" "org.openj9.criu.JDK11UpTimeoutAdjustmentTest testThreadPark" 1 1 false
Time spent starting: 24 milliseconds
Time spent executing: 37155 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] Start test name: testThreadPark
 [OUT] Before starting testThreadPark, current thread name: main, Wed Apr 26 04:56:18 EDT 2023, System.currentTimeMillis(): 1682499378590, System.nanoTime(): 1682499378585091322
 [OUT] testThreadPark NO C/R before park(), current thread name: main, Wed Apr 26 04:56:22 EDT 2023, System.currentTimeMillis(): 1682499382439, System.nanoTime(): 1682499382434969902
 [OUT] testThreadPark NO C/R after park(), current thread name: main, Wed Apr 26 04:56:33 EDT 2023, System.currentTimeMillis(): 1682499393166, System.nanoTime(): 1682499393161389359
 [OUT] PASSED: expected park time 10000000000 ns, but the actual elapsed time was: 10002333379ns (~10002ms) with startNanoTime = 1682499382440909907ns, and endNanoTime = 1682499392443243286ns, CheckpointRestoreNanoTimeDelta: 0ns (~0ms)
 [OUT] testThreadPark before park(), current thread name: Thread-0, Wed Apr 26 04:56:34 EDT 2023, System.currentTimeMillis(): 1682499394244, System.nanoTime(): 1682499394239233770
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Apr 26 04:56:35 EDT 2023, System.currentTimeMillis(): 1682499395374, System.nanoTime(): 1682499395369814920
 [OUT] 08:56:35.391*0x69800          j9criu.9        > Java_org_eclipse_openj9_criu_CRIUSupport_checkpointJVMImpl
 [OUT] 08:56:35.445 0x69800          j9criu.13       - Before checkpoint, checkpointNanoTimeMonotonic = 1682499395440117500, checkpointNanoUTCTime = 1682499395445808232
 [OUT] 08:56:35.458 0x69800          j9criu.12       - Current syslogOptions: error,vital
 [OUT] 08:56:35.458 0x69800          j9criu.7        - Before checkpoint criu_dump(), j9time_nano_time() returns 1682499395453113672, j9time_current_time_nanos() returns 1682499395458804358
 [OUT] 08:56:35.473 0x69800          j9criu.15       - After checkpoint criu_dump(), j9time_nano_time() returns 1682499395468514716, j9time_current_time_nanos() returns 1682499395474205358
 [OUT] 08:56:35.473 0x69800          j9criu.10       < Java_org_eclipse_openj9_criu_CRIUSupport_checkpointJVMImpl
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:649)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
 [OUT] 	at org.openj9.criu.JDK11UpTimeoutAdjustmentTest.test(JDK11UpTimeoutAdjustmentTest.java:76)
 [OUT] 	at org.openj9.criu.JDK11UpTimeoutAdjustmentTest.main(JDK11UpTimeoutAdjustmentTest.java:39)
 [OUT] testThreadPark after park(), current thread name: Thread-0, Wed Apr 26 04:56:44 EDT 2023, System.currentTimeMillis(): 1682499404244, System.nanoTime(): 1682499404239951264
 [OUT] PASSED: expected park time 10000000000 ns, but the actual elapsed time was: 10000444722ns (~10000ms) with startNanoTime = 1682499394239397642ns, and endNanoTime = 1682499404239842364ns, CheckpointRestoreNanoTimeDelta: 0ns (~0ms)
 [OUT] Removed testOutput file
 [OUT] finished script
 [ERR] Error (criu/util.c:457): Can't read link of fd -404: No such file or directory
 [ERR] Error (criu/protobuf.c:75): Unexpected EOF on (null)
>> Success condition was found: [Output match: PASSED: expected park time]
>> Required condition was not found: [Output match: Killed]
>> Required condition was found: [Output match: Start test name: testThreadPark]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Failure condition was not found: [Output match: FAILED: expected sleep time]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by JasonFengJ9** [comment]
```
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
 [OUT] finished script
 [ERR] Error (criu/util.c:457): Can't read link of fd -404: No such file or directory
 [ERR] Error (criu/protobuf.c:75): Unexpected EOF on (null)
```
Similar with https://github.com/eclipse-openj9/openj9/issues/17295#issuecomment-1524165250, this seems a machine issue, also it occurred in zLinux which is not the 0.38 target platform.

**Comment by ymanton** [comment]
It looks the same, but it has to be a different issue; the issue I've been seeing on PPC is PPC-specific and does not affect s390x.

The relevant part of the error is:

```
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
```

This means that CRIU returned an error on checkpoint. To know why we would need to look at the CRIU logs after increasing verbosity to 4.
