### ISSUE TITLE
cmdLineTester_criu_keepCheckpoint SystemCheckpointException: Could not dump the JVM processes, err=-52

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17295]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/523
cmdLineTester_criu_keepCheckpoint_2 `-Xjit:count=0 `
```
Testing: Create Criu Checkpoint Image without Restore
Test start time: 2023/04/26 04:37:37 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 " org.openj9.criu.CRIUSimpleTest 1 1 true
Time spent starting: 46 milliseconds
Time spent executing: 15494 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] Total checkpoint(s) 1:
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Apr 26 04:37:49 EDT 2023, System.currentTimeMillis(): 1682498269084, System.nanoTime(): 1682498269079537985
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:649)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:61)
 [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:43)
 [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:33)
 [OUT] finished script
>> Success condition was not found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Failure condition was not found: [Output match: Post-checkpoint]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Removed testOutput file]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Failure condition was not found: [Output match: ERR]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by pshipton** [comment]
@tajila @JasonFengJ9

**Comment by JasonFengJ9** [comment]
```
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
```
`Could not dump the JVM processes, err=-52` indicates a machine/setup issue, also it occurred at zLinux which is not the `0.38` target platform.
