### ISSUE TITLE
[JDK20] GetStackTraceNotSuspendedStress Fails

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#17307]
> serviceability/jvmti/stress/StackTrace/NotSuspended/GetStackTraceNotSuspendedStressTest.java 

#16203 has been completed. While enabling `GetStackTraceNotSuspendedStress`, the below error was seen. Fields in a VirtualThread instance are GC'ed while it is being used. The Java object is retained if the GC policy is changed to `-Xgcpolicy:optthruput` or `-Xgcpolicy:none`.

```
make test TEST="jtreg:test/hotspot/jtreg/serviceability/jvmti/stress/StackTrace/NotSuspended" JTREG="JAVA_OPTIONS=--enable-preview -Dvm.continuations=true;VERBOSE=all"

>>>> with default GC policy <<<<

STDOUT:
Agent_OnLoad started
Agent_OnLoad finished
Synchronization point checkStatus(0) called.
Data 0x7f270c0a72c8 0x7f26ec002bc8
Agent: wait for thread to start
Agent: started
STDERR:
java.lang.NullPointerException: Cannot read field "scheduler" because "this" is null
	at java.base/java.lang.VirtualThread.submitRunContinuation(VirtualThread.java:241)
	at java.base/java.lang.VirtualThread.start(VirtualThread.java:535)
	at java.base/java.lang.VirtualThread.start(VirtualThread.java:548)
	at GetStackTraceNotSuspendedStressTest.test1(GetStackTraceNotSuspendedStressTest.java:78)
	at GetStackTraceNotSuspendedStressTest.runTest(GetStackTraceNotSuspendedStressTest.java:89)
	at GetStackTraceNotSuspendedStressTest.main(GetStackTraceNotSuspendedStressTest.java:102)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
	at java.base/java.lang.Thread.run(Thread.java:1639)

JavaTest Message: Test threw exception: java.lang.NullPointerException: Cannot read field "scheduler" because "this" is null
JavaTest Message: shutting down test

>>>> with -Xgcpolicy:optthruput or -Xgcpolicy:none <<<<

STDOUT:
Agent_OnLoad started
Agent_OnLoad finished
Synchronization point checkStatus(0) called.
Data 0x7f2a900946e8 0x7f2a6c0026f8
Agent: wait for thread to start
Agent: started
STDERR:
STATUS:Passed.
```

**Comment by babsingh** [comment]
fyi @LinHu2016 @amicic @dmitripivkine

**Comment by LinHu2016** [comment]
Hi @babsingh, is it intermittent issue or only related with any platforms? I haven't reproduced the issue locally.

**Comment by babsingh** [comment]
@LinHu2016 I am unable to reproduce it after I updated my repos in the morning. Last Friday, I was able to reproduce it consistently. For the time being, I will close this issue. The failing test is being enabled in https://github.com/adoptium/aqa-tests/pull/4554.
