### ISSUE TITLE
JDK20 java/lang/invoke/lambda/LambdaFileEncodingSerialization.java error: error while writing ABC???: bad filename RelativeFile[TestLambdaFileEncodingSerialization$ABC???.class]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17326]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_testList_0/13/)(`rhel9-aarch64-3`):
```
openjdk version "20.0.1-beta" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1+9-202305012346 (build 20.0.1-beta+9-202305012346)
Eclipse OpenJ9 VM 20.0.1+9-202305012346 (build master-d4443d666, JRE 20 Linux aarch64-64-Bit Compressed References 20230501_15 (JIT enabled, AOT enabled)
OpenJ9   - d4443d666
OMR      - 7ddb743ea
JCL      - 346547a86 based on jdk-20.0.1+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_lang_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk20_j9_sanity.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-linux-aarch64-openj9%2F15%2Fibm-semeru-open-jdk_aarch64_linux_JDK20U_2023-05-01-23-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-linux-aarch64-openj9%2F15%2Fibm-semeru-open-testimage_aarch64_linux_JDK20U_2023-05-01-23-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=20&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk20&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=13&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-02T02:16:45.811Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2023-05-02T02:16:45.811Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

[2023-05-02T02:31:36.299Z] TEST: java/lang/invoke/lambda/LambdaFileEncodingSerialization.java

[2023-05-02T02:31:36.300Z] STDERR:
[2023-05-02T02:31:36.300Z] /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java:38: error: error while writing ABC???: bad filename RelativeFile[TestLambdaFileEncodingSerialization$ABC???.class]
[2023-05-02T02:31:36.300Z]         public static class ABC???? implements Serializable {
[2023-05-02T02:31:36.300Z]                       ^
[2023-05-02T02:31:36.300Z] Note: /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java uses unchecked or unsafe operations.
[2023-05-02T02:31:36.300Z] Note: Recompile with -Xlint:unchecked for details.
[2023-05-02T02:31:36.300Z] 1 error
[2023-05-02T02:31:36.300Z] 
[2023-05-02T02:31:36.300Z] java.lang.Exception: failures: 1
[2023-05-02T02:31:36.300Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:95)
[2023-05-02T02:31:36.300Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-05-02T02:31:36.300Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-05-02T02:31:36.300Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-05-02T02:31:36.300Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-05-02T02:31:36.300Z] 
[2023-05-02T02:31:36.300Z] JavaTest Message: Test threw exception: java.lang.Exception
[2023-05-02T02:31:36.300Z] JavaTest Message: shutting down test
[2023-05-02T02:31:36.300Z] 
[2023-05-02T02:31:36.300Z] 
[2023-05-02T02:31:36.300Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2023-05-02T02:31:36.300Z] --------------------------------------------------
[2023-05-02T03:02:08.998Z] Test results: passed: 868; failed: 1
[2023-05-02T03:02:23.345Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_testList_0/aqa-tests/TKG/output_16829938044714/jdk_lang_0/report/html/report.html
[2023-05-02T03:02:23.345Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_testList_0/aqa-tests/TKG/output_16829938044714/jdk_lang_0/work
[2023-05-02T03:02:23.345Z] Error: Some tests failed or other problems occurred.
[2023-05-02T03:02:23.345Z] -----------------------------------
[2023-05-02T03:02:23.345Z] jdk_lang_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32639/)

**Comment by pshipton** [comment]
Failed 1/50

**Comment by knn-k** [comment]
There is a JDK 18 issue with LambdaFileEncodingSerialization.java: #15563.
It was fixed by changing the locale setting to en_US.

**Comment by JasonFengJ9** [comment]
[JDK20 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_testList_0/17/)
```
openjdk version "20.0.1" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1+9 (build 20.0.1+9)
Eclipse OpenJ9 VM 20.0.1+9 (build master-8f80c760e, JRE 20 Linux aarch64-64-Bit Compressed References 20230418_19 (JIT enabled, AOT enabled)
OpenJ9   - 8f80c760e
OMR      - de6212d59
JCL      - 66a4d4869 based on jdk-20.0.1+9)

[2023-05-08T00:17:23.987Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2023-05-08T00:17:23.987Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

[2023-05-08T00:27:58.811Z] TEST: java/lang/invoke/lambda/LambdaFileEncodingSerialization.java

[2023-05-08T00:27:58.815Z] STDERR:
[2023-05-08T00:27:58.815Z] /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java:38: error: error while writing ABC???: bad filename RelativeFile[TestLambdaFileEncodingSerialization$ABC???.class]
[2023-05-08T00:27:58.815Z]         public static class ABC???? implements Serializable {

[2023-05-08T01:01:53.290Z] jdk_lang_0_FAILED
```

**Comment by knn-k** [comment]
I ran LambdaFileEncodingSerialization.java using jdk_custom 50 times, but I was not able to reproduce the failure.  (internal job/Grinder/32770/)
It might require running the whole jdk_lang_0.

**Comment by JasonFengJ9** [comment]
> It might require running the whole jdk_lang_0.

[Initial 50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32639/) runs `jdk_lang_0`.

**Comment by knn-k** [comment]
30x jdk_lang_0 (internal job/Grinder/32781/) did not fail.

**Comment by knn-k** [comment]
Another 30x jdk_lang_0 (internal job/Grinder/32801/) did not fail, either.

**Comment by knn-k** [comment]
Another Grinder (job/Grinder/32847/) shows 100% failure (6 out of 6) on rhel9-aarch64-3.  I stopped the job during the 7th iteration.

```
[2023-05-11T01:53:20.415Z] test LambdaFileEncodingSerialization.testDeserializeLambdaEncoding(): failure
[2023-05-11T01:53:20.415Z] java.lang.AssertionError: Command /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/javac -J-Dfile.encoding=ISO-8859-1 -cp . -d . /home/jenkins/workspace/Grinder/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda/TestLambdaFileEncodingSerialization.java , failed exitCode = 1 expected [true] but found [false]
[2023-05-11T01:53:20.415Z] 	at org.testng.Assert.fail(Assert.java:99)
[2023-05-11T01:53:20.415Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2023-05-11T01:53:20.415Z] 	at org.testng.Assert.assertTrue(Assert.java:45)
[2023-05-11T01:53:20.415Z] 	at LambdaFileEncodingSerialization.testDeserializeLambdaEncoding(LambdaFileEncodingSerialization.java:64)
[2023-05-11T01:53:20.415Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

The original failure in https://github.com/eclipse-openj9/openj9/issues/17326#issue-1694171756 was from the same test machine.
How can I know the locale setting of that machine?

**Comment by knn-k** [comment]
I ran only LambdaFileEncodingSerialization.java in yet another Grinder job (32849) on rhel9-aarch64-3.  100% failure (5 out of 5).  You don't need to run the whole jdk_lang_0.

I have no idea what happened on ub18-aarch64-6.  Grinder job 32639 is no longer visible.

**Comment by pshipton** [comment]
To be clear, I successfully used Machine-Reservation to get on the machine.

**Comment by knn-k** [comment]
Locale settings on ub22-aarch64-2 below.  It is **en_US.UTF-8** instead of **C.UTF-8** on rhel9-aarch64-*:

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
$ locale -a
C
C.utf8
en_US.utf8
ja_JP.utf8
ko_KR.utf8
POSIX
zh_CN.utf8
zh_TW.utf8
```

The previous issue #15563 was closed by updating the locale of the target machine to en_US.
I opened infrastructure/issues/8002 for updating the locale of rhel9-aarch64-*.

**Comment by austin0** [comment]
Machine updated, now running en_US.UTF-8:

```
locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by knn-k** [comment]
I ran Grinder jobs (internal 32896-32899) on rhel9-aarch64-1/2/3/4, and they were all successful.
It is clear that the failures on rhel9-aarch64-* were caused by the C.UTF_8 locale.

**Comment by knn-k** [comment]
10x Grinder job on ub18-aarch64-6.svl.ibm.com (internal 32903) was successful.

**Comment by knn-k** [comment]
Another 10x Grinder job on ub18-aarch64-6 (internal 32909) was successful.

**Comment by knn-k** [comment]
I guess we can close this issue.

**Comment by JasonFengJ9** [comment]
Closing as per https://github.com/eclipse-openj9/openj9/issues/17326#issuecomment-1575825684
