### ISSUE TITLE
Error parsing TAP Stream: Missing TAP Plan.

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17357]
I've been seeing a bunch of these in the builds They cause top level failure, although all the child jobs passed.

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly/534/console
```
05:16:43  Processing '/var/lib/jenkins/jobs/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly/builds/534/tap-master-files/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly_testList_2/524/aqa-tests/TKG/output_1683361853766/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly_testList_2.tap'
05:16:43  Parsing TAP test result [/var/lib/jenkins/jobs/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly/builds/534/tap-master-files/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly_testList_2/524/aqa-tests/TKG/output_1683361853766/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly_testList_2.tap].
05:16:43  org.tap4j.parser.ParserException: Error parsing TAP Stream: Missing TAP Plan.
05:16:43  	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:257)
05:16:43  	at org.tap4j.parser.Tap13Parser.parseFile(Tap13Parser.java:231)
05:16:43  	at org.tap4j.plugin.TapParser.parse(TapParser.java:173)
05:16:43  	at org.tap4j.plugin.TapPublisher.loadResults(TapPublisher.java:572)
05:16:43  	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:444)
05:16:43  	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:403)
05:16:43  	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
05:16:43  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
05:16:43  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
05:16:43  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
05:16:43  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$558/0x0000000000000000.run(Unknown Source)
05:16:43  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
05:16:43  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
05:16:43  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
05:16:43  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
05:16:43  	at java.base/java.lang.Thread.run(Thread.java:836)
05:16:43  Caused by: org.tap4j.parser.ParserException: Missing TAP Plan.
05:16:43  	at org.tap4j.parser.Tap13Parser.onFinish(Tap13Parser.java:429)
05:16:43  	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:255)
05:16:43  	... 15 more
05:16:43  TAP parse errors found in the build. Marking build as UNSTABLE
05:16:43  TAP Reports Processing: FINISH
```

**Comment by pshipton** [comment]
@llxia pls take a look.

**Comment by pshipton** [comment]
Ah good catch, I didn't notice that. 
@AdamBrousseau I think mac10-x86-3 was enabled after the power failure. I think I had it disabled via https://github.com/eclipse-openj9/openj9/issues/17269. I will leave it enabled for now, but if it gets worse or annoying I will disable it again.

**Comment by AdamBrousseau** [comment]
https://github.com/eclipse-openj9/openj9/issues/17269#issuecomment-1538862146
I had tried a compile again. Still failing. Disabled again.
