### ISSUE TITLE
mac10-x86-4 - unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17354]
Disabled it.

https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/546/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/547/
```
02:18:50  [consumer_0] Deploying artifact: https://ub18p8art.casa.cs.unb.ca/artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/547/OpenJ9-JDK11-x86-64_mac-20230505-224012.tar.gz
02:18:50  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
02:18:50  Error occurred for request PUT /artifactory/ci-openj9/Build_JDK11_x86-64_mac_Nightly/547/OpenJ9-JDK11-x86-64_mac-20230505-224012.tar.gz;build.parentNumber=1652;build.buildIdentifier=Nightly;build.timestamp=1683346411426;build.name=Build_JDK11_x86-64_mac_Nightly;build.parentName=Pipeline_Build_Test_JDK11_x86-64_mac;build.number=547 HTTP/1.1: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
02:18:50  [consumer_0] An exception occurred during execution:
02:18:50  java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
02:18:50  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
02:18:50  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
02:18:50  	at java.base/java.lang.Thread.run(Thread.java:839)
02:18:50  Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
02:18:50  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
02:18:50  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
02:18:50  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
02:18:50  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
02:18:50  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
02:18:50  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
02:18:50  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
02:18:50  	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
02:18:50  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
02:18:50  	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
02:18:50  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
02:18:50  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
02:18:50  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
02:18:50  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
02:18:50  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
02:18:50  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
02:18:50  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
02:18:50  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
02:18:50  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
02:18:50  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
02:18:50  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
02:18:50  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
02:18:50  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
02:18:50  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
02:18:50  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
02:18:50  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
02:18:50  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
02:18:50  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
02:18:50  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:72)
02:18:50  	at org.jfrog.build.client.JFrogHttpClient.sendRequest(JFrogHttpClient.java:133)
02:18:50  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:112)
02:18:50  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
02:18:50  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:262)
02:18:50  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:257)
02:18:50  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
02:18:50  	... 2 more
02:18:50  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
02:18:50  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
02:18:50  	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
02:18:50  	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
02:18:50  	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
02:18:50  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
02:18:50  	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
02:18:50  	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
02:18:50  	... 32 more
02:18:50  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
02:18:50  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
02:18:50  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
02:18:50  	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
02:18:50  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
02:18:50  	... 38 more
```

**Comment by AdamBrousseau** [comment]
https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/ARTIFACTORY.md#configure-unb-nodes-to-accept-self-signed-certificate-upload-only
```
sudo /Library/Java/JavaVirtualMachines/ibm-semeru-open-11.jdk/Contents/Home/bin/keytool -import -alias ub18p8art.casa.cs.unb.ca -keystore /Library/Java/JavaVirtualMachines/ibm-semeru-open-11.jdk/Contents/Home/lib/security/cacerts -file public.crt 
```
[![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Build_JDK11_x86-64_mac_Nightly&build=548)](https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/548/)
