### ISSUE TITLE
testGetSizeOfArray failed in Valhalla builds

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#17359]
Failure link
------------
regression introduced: yes 
Failed in internal nightly [build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly/856/tapResults/):
```
java -version
openjdk version "21-internal" 2023-09-19
22:00:12  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
22:00:12  Eclipse OpenJ9 VM (build master-74c54505291, JRE 21 Linux amd64-64-Bit Compressed References 20230504_1033 (JIT enabled, AOT enabled)
22:00:12  OpenJ9   - 74c54505291
22:00:12  OMR      - 5dcc2f28955
22:00:12  JCL      - 004eb7f92c8 based on jdk-21+19)
```

Last passing [build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly/855/) is:
```
java -version
22:12:12  openjdk version "21-internal" 2023-09-19
22:12:12  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
22:12:12  Eclipse OpenJ9 VM (build master-0609eb43a77, JRE 21 Linux amd64-64-Bit Compressed References 20230503_1032 (JIT enabled, AOT enabled)
22:12:12  OpenJ9   - 0609eb43a77
22:12:12  OMR      - 5dcc2f28955
22:12:12  JCL      - 004eb7f92c8 based on jdk-21+19)
```

Optional info
-------------

- intermittent failure: no
OpenJ9 change between the last passing build and first failing build:
https://github.com/eclipse-openj9/openj9/compare/0609eb43a77..74c54505291

Failure output (captured from console output)
---------------------------------------------
```
FAILED: testGetSizeOfArray
java.lang.AssertionError: expected [40] but found [32]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:547)
	at org.testng.Assert.assertEquals(Assert.java:557)
	at org.openj9.test.lworld.ValueTypeUnsafeTests.testGetSizeOfArray(ValueTypeUnsafeTests.java:505)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	...

FAILED: testGetSizeOfArray
java.lang.AssertionError: expected [24] but found [16]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:547)
	at org.testng.Assert.assertEquals(Assert.java:557)
	at org.openj9.test.lworld.ValueTypeUnsafeTests.testGetSizeOfArray(ValueTypeUnsafeTests.java:503)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        ...
```
The test case is: https://github.com/eclipse-openj9/openj9/blob/8f80c760e721f3f55092f67fe296c6d24886e06d/test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java#L500-L507

**Comment by hangshao0** [comment]
Looking at the changes, might be caused by https://github.com/eclipse-openj9/openj9/pull/16420. @VermaSh

**Comment by VermaSh** [comment]
Looking into the failure

**Comment by VermaSh** [comment]
I suspect this is because that PR changed default array header size. Prior to that PR `dataAddr` field was always present but after the PR, the field is enabled only for Balanced GC by default. The size of the field is 8 bytes which aligns with the difference between expected and actual values. We can verify this by running with `-XXgc:disableIndexableDualHeaderShape`. This should enable the field and stop the failures.

Verifying this right now.

**Comment by VermaSh** [comment]
We are failing because new default array header size is less than what it was before https://github.com/eclipse-openj9/openj9/pull/16420 was merged. So, not a real failure; we just need to update the expected array header size values. I have attached console output along with my unit test.

**Compressed Refs**
```
> $failing_build/bin/java -XX:-EnableArrayFlattening \
 --add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
 -Xcompressedrefs \
 -XXgc:enableIndexableDualHeaderShape ValueTypeUnsafeTests
Size: 16 -- (24|40)
Size: 16 -- (24|40)

> $failing_build/bin/java -XX:-EnableArrayFlattening \
 --add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
 -Xcompressedrefs \
 -XXgc:disableIndexableDualHeaderShape ValueTypeUnsafeTests
Size: 24 -- (24|40)
Size: 24 -- (24|40)
```
**Full Refs**
```
> $failing_build/bin/java -XX:-EnableArrayFlattening \
 --add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
 -Xnocompressedrefs \
 -XXgc:enableIndexableDualHeaderShape ValueTypeUnsafeTests
Size: 32 -- (24|40)
Size: 32 -- (24|40)

> $failing_build/bin/java -XX:-EnableArrayFlattening \
 --add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
 -Xnocompressedrefs \
 -XXgc:disableIndexableDualHeaderShape ValueTypeUnsafeTests
Size: 40 -- (24|40)
Size: 40 -- (24|40)
```

<details>
<summary>Unit test</summary>

```java
import jdk.internal.misc.Unsafe;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.InvocationTargetException;

import java.util.List;

/* compile:
 javac --add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
 -XDenablePrimitiveClasses \
 ValueTypeUnsafeTests.java
 */

public class ValueTypeUnsafeTests {

	static primitive class ValueTypeInt {
		ValueTypeInt(int i) { this.i = i; }
		final int i;
	}

	static Unsafe myUnsafe = Unsafe.getUnsafe();
	static boolean isCompressedRefsEnabled = false;
	static boolean isFlatteningEnabled = false;
	static boolean isArrayFlatteningEnabled = false;

	static ValueTypeInt[] vtIntAry;

	static public void testSetUp() throws Throwable {
		isFlatteningEnabled = false;
		isArrayFlatteningEnabled = false;
		isCompressedRefsEnabled = true;
	}

	// array must not be empty
	static private <T> long arrayElementSize(T[] array) {
		// don't simply use getObjectSize(array[0]) - valueHeaderSize(array[0].getClass()) because the amount of memory used to store an object may be different depending on if it is inside an array or not (for instance, when flattening is disabled)
		return (myUnsafe.getObjectSize(array) - myUnsafe.arrayBaseOffset(array.getClass())) / array.length;
	}


	static public void setUp() {
		vtIntAry = new ValueTypeInt[] { new ValueTypeInt(1), new ValueTypeInt(2) };
	}

	static public void testGetSizeOfArray() {
		long size = myUnsafe.getObjectSize(vtIntAry);
		System.out.printf("Size: %d -- (24|40)\n", size);
	}

	static public void main (String[] args) throws Throwable{
	    testSetUp(); setUp();
		testGetSizeOfArray(); testGetSizeOfArray();
	}
}
```

**Comment by VermaSh** [comment]
I have crated PR with the fix https://github.com/eclipse-openj9/openj9/pull/17375. @hangshao0 can you please launch a build to verify? I [tried](https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDKnext_x86-64_linux_valhalla_Personal/293/console) but got boot jdk errors.

**Comment by hangshao0** [comment]
> can you please launch a build to verify? I [tried](https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDKnext_x86-64_linux_valhalla_Personal/293/console) but got boot jdk errors.

https://github.ibm.com/runtimes/tooling/pull/1040 is updating the bootJDK to Java 20. We can get your change in after it is resolved.

**Comment by hangshao0** [comment]
> I [tried](https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDKnext_x86-64_linux_valhalla_Personal/293/console) but got boot jdk errors.

> https://github.ibm.com/runtimes/tooling/pull/1040 is updating the bootJDK to Java 20. 

I see it is merged. I guess you can retry you build. @VermaSh
