### ISSUE TITLE
openj9/runtime/j9vm/j7vmi.c:2733: JVM_DTraceIsSupported: Assertion `!"JVM_DTraceIsSupported() stubbed!"' failed.

### ISSUE THREAD

**Issue by BurryPotter** [eclipse-openj9/openj9#17389]
Java -version output
--------------------

openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b09)
Eclipse OpenJ9 VM (build openj9-0.36.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230206_588 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - eebde685ec based on jdk8u362-b09)

Summary of problem
------------------

Source code `Case.java`
```
import com.sun.tracing.ProviderFactory;
public class Case {
    public static void main(String[] args) {
        ProviderFactory.getDefaultFactory();
    }
}
```
When executing this program with JDK8, j9 will crash, but hotpsot will not. (on both Linux and Windows)

Command and output
----------------

```
> java Case
java: /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/openj9/runtime/j9vm/j7vmi.c:2733: JVM_DTraceIsSupported: Assertion `!"JVM_DTraceIsSupported() stubbed!"' failed.
JVMDUMP039I Processing dump event "abort", detail "" at 2023/05/11 11:45:45 - please wait.
JVMDUMP032I JVM requested System dump using '/home/alex/projects/Cases/target/classes/core.20230511.114545.20.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 53 was not found. Expected to find core file with name "/mnt/wslg/dumps/core.main"
JVMDUMP032I JVM requested Java dump using '/home/alex/projects/Cases/target/classes/javacore.20230511.114545.20.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/alex/projects/Cases/target/classes/javacore.20230511.114545.20.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/alex/projects/Cases/target/classes/Snap.20230511.114545.20.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/alex/projects/Cases/target/classes/Snap.20230511.114545.20.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/alex/projects/Cases/target/classes/jitdump.20230511.114545.20.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'main' thread 0x0000000000021F00
JVMDUMP010I JIT dump written to /home/alex/projects/Cases/target/classes/jitdump.20230511.114545.20.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".
```

Diagnostic files
----------------

stderr output:
```
java: /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/openj9/runtime/j9vm/j7vmi.c:2733: JVM_DTraceIsSupported: Assertion `!"JVM_DTraceIsSupported() stubbed!"' failed.
JVMDUMP039I Processing dump event "abort", detail "" at 2023/05/11 11:45:45 - please wait.
JVMDUMP032I JVM requested System dump using '/home/alex/projects/Cases/target/classes/core.20230511.114545.20.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 53 was not found. Expected to find core file with name "/mnt/wslg/dumps/core.main"
JVMDUMP032I JVM requested Java dump using '/home/alex/projects/Cases/target/classes/javacore.20230511.114545.20.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/alex/projects/Cases/target/classes/javacore.20230511.114545.20.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/alex/projects/Cases/target/classes/Snap.20230511.114545.20.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/alex/projects/Cases/target/classes/Snap.20230511.114545.20.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/alex/projects/Cases/target/classes/jitdump.20230511.114545.20.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'main' thread 0x0000000000021F00
JVMDUMP010I JIT dump written to /home/alex/projects/Cases/target/classes/jitdump.20230511.114545.20.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".
```

javacore, jitdump, snap files:
[diagnostic_files.zip](https://github.com/eclipse-openj9/openj9/files/11451990/diagnostic_files.zip)

**Comment by pshipton** [comment]
We're not planning to support dtrace, but it does make sense to implement the native and return false for isSupported.

```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at sun/tracing/dtrace/JVM.isSupported0(Native Method)
4XESTACKTRACE                at sun/tracing/dtrace/JVM.isSupported(JVM.java:60)
4XESTACKTRACE                at sun/tracing/dtrace/DTraceProviderFactory.isSupported(DTraceProviderFactory.java:151)
4XESTACKTRACE                at com/sun/tracing/ProviderFactory.getDefaultFactory(ProviderFactory.java:86)
4XESTACKTRACE                at Case.main(Case.java:6)
```
