### ISSUE TITLE
OpenJDK 17 jdk_foreign java/foreign/StdLibTest test_vprintf - A NULL memory address is not allowed for pointer

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17400]
Failing on windows, plinux, amac, aix. It doesn't seem intermittent

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/481/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/469/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_Nightly/305
jdk_foreign
java/foreign/StdLibTest.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/467
```
00:41:42  test StdLibTest.test_vprintf([]): failure
00:41:42  java.lang.NullPointerException: A NULL memory address is not allowed for pointer.
00:41:42  	at jdk.incubator.foreign/openj9.internal.foreign.abi.UpcallMHMetaData.getNativeArgRetAddrOfPtr(UpcallMHMetaData.java:103)
00:41:42  	at jdk.incubator.foreign/openj9.internal.foreign.abi.InternalDowncallHandler.memAddrToLongArg(InternalDowncallHandler.java:203)
00:41:42  	at StdLibTest$StdLibHelper.vprintf(StdLibTest.java:338)
00:41:42  	at StdLibTest.test_vprintf(StdLibTest.java:159)
00:41:42  	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
00:41:42  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:41:42  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
00:41:42  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
00:41:42  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
00:41:42  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
00:41:42  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
00:41:42  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
00:41:42  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
00:41:42  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
00:41:42  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
00:41:42  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
00:41:42  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
00:41:42  	at org.testng.TestRunner.run(TestRunner.java:585)
00:41:42  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
00:41:42  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
00:41:42  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
00:41:42  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
00:41:42  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
00:41:42  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
00:41:42  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
00:41:42  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
00:41:42  	at org.testng.TestNG.runSuites(TestNG.java:1069)
00:41:42  	at org.testng.TestNG.run(TestNG.java:1037)
00:41:42  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:41:42  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:41:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:41:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
00:41:42  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:41:42  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
00:41:42  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:41:42  	at java.base/java.lang.Thread.run(Thread.java:857)
```

**Comment by ChengJin01** [comment]
The test failure was triggered by the latest PR at https://github.com/eclipse-openj9/openj9/pull/17308 in handling the invalid argument/return value at https://github.com/eclipse-openj9/openj9/blob/8800e58366d7926c4589e37aa008c529ad43000b/jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java#L145
```
	static long getNativeArgRetAddrOfPtr(MemoryAddress argRetAddrOfPtr) {
		if (argRetAddrOfPtr == MemoryAddress.NULL) {
			throw new NullPointerException("A NULL memory address is not allowed for pointer."); <------
		}

```
It seems that `MemorySegment.NULL`/`MemoryAddress.NULL` comes with a valid native address according to their implementation in OpenJDK in which case a valid native address with zero values is acceptable in native. So I will need to go over the code around there to see whether the null check can be simply removed to pass the test suite or anything else needs to be adjusted for the case.

**Comment by ChengJin01** [comment]
[1] The test failure with `StdLibTest.test_vprintf([])` was also captured with the latest nightly builds on the same platforms above in JDK20. e.g.  https://openj9-jenkins.osuosl.org/job/Grinder/2341/consoleText (`aarch64_mac`)
```
[2023-05-12T13:29:00.524Z] test StdLibTest.test_vprintf([]): failure
[2023-05-12T13:29:00.524Z] java.lang.NullPointerException: A NULL memory segment is not allowed for struct.
[2023-05-12T13:29:00.524Z] 	at java.base/openj9.internal.foreign.abi.UpcallMHMetaData.getNativeArgRetSegment(UpcallMHMetaData.java:110)
[2023-05-12T13:29:00.524Z] 	at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.memSegmtToLongArg(InternalDowncallHandler.java:213)
[2023-05-12T13:29:00.524Z] 	at StdLibTest$StdLibHelper.vprintf(StdLibTest.java:319)
[2023-05-12T13:29:00.524Z] 	at StdLibTest.test_vprintf(StdLibTest.java:156)
```
against the same failing test at https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/ced3ff7a3406af93dcfe40edc7708e78928ce2ab/test/jdk/java/foreign/StdLibTest.java#L319 (JDK20)
```
       final static MethodHandle vprintf = abi.downcallHandle(abi.defaultLookup().find("vprintf").get(),
                FunctionDescriptor.of(C_INT, C_POINTER, C_POINTER));

        int vprintf(String format, List<PrintfArg> args) throws Throwable {
            try (var arena = Arena.openConfined()) {
                MemorySegment formatStr = arena.allocateUtf8String(format);
                VaList vaList = VaList.make(b -> args.forEach(a -> a.accept(b, arena)), arena.scope());
                return (int)vprintf.invokeExact(formatStr, vaList.segment()); <--------
            }
        }
```
in which case the passed-in argument for `vaList.segment()` turns out to be a `MemorySegment.NULL` for the empty valist (`StdLibTest.test_vprintf([])`) based on the printing message in the failing test as follows:
```
vaList.segment() = MemorySegment{ array: Optional.empty address:0 limit: 0 }, address() = 0, byteSize = 0
```

[2] The reason why the test passed on other platforms (e.g. `Linux/x86_64`) is because the `vaList.segment()` on `Linux/x86_64` returned a non-NULL `MemorySegment` for the empty valist while the failing platforms returned a NULL `MemorySegment` due to the different implementation of the empty valist on these platforms which is mapped to the underlying valist structure on these platforms.
e.g.
(1) Linux/x86_64:
https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/openj9/src/java.base/share/classes/jdk/internal/foreign/abi/x64/sysv/SysVVaList.java#L115
```
    private static final VaList EMPTY = new SharedUtils.EmptyVaList(emptyListAddress()); <-----

    private static MemorySegment emptyListAddress() {
        MemorySegment base = MemorySegment.allocateNative(LAYOUT, SegmentScope.global()); <-------
        VH_gp_offset.set(base, MAX_GP_OFFSET);
        VH_fp_offset.set(base, MAX_FP_OFFSET);
        VH_overflow_arg_area.set(base, MemorySegment.NULL);
        VH_reg_save_area.set(base, MemorySegment.NULL);
        return base.asSlice(0, 0); <-------- returns a non-NULL segment for the empty valist
    }
```
(2) Mac/Aarch64:
https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/ced3ff7a3406af93dcfe40edc7708e78928ce2ab/src/java.base/share/classes/jdk/internal/foreign/abi/aarch64/macos/MacOsAArch64VaList.java#L57
```
    private static final VaList EMPTY = new SharedUtils.EmptyVaList(MemorySegment.NULL); <-----
```

[3] As confirmed on the Hotspot, a NULL segment for `pointer` is acceptable in native (e.g. in the case of `vprintf` in which case users take responsible for using the segment correctly in native) while a NULL segment for `struct` should be captured as invalid. So I will need to modify the related code to differentiate them in such case.
