### ISSUE TITLE
Timeouts in sanity tests

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9#17422]
Observed in recent internal nightly JITServer tests, but the failures appear to reproduce fairly easily in Grinder without JITAAS. The tests:

- `jdk_lang_0`
- `jdk_lang_1`
- `jdk_lang_j9_0`
- `jdk_util_0`
- `jdk_util_1`

Console log for one of the failures in [one of the failing runs](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_jit_Personal/671/):

```
 jdk_util_1 Start Time: Tue May 16 03:43:31 2023 Epoch Time (ms): 1684233811162
06:43:31  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
06:43:31  JVM_OPTIONS: -XX:+UseJITServer -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

07:06:44  ACTION: testng -- Error. Agent error: java.lang.Exception: Agent 6 timed out with a timeout of 960 seconds; check console log for any additional details
07:06:44  REASON: User specified action: run testng BasicTest 
07:06:44  TIME:   963.822 seconds
07:06:44  messages:
07:06:44  command: testng BasicTest
07:06:44  reason: User specified action: run testng BasicTest 
07:06:44  Mode: agentvm
07:06:44  Agent id: 6
07:06:44  Timeout refired 960 times
07:06:44  Timeout information:
07:06:44  Running jcmd on process 3419385
07:06:44  Dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Personal/aqa-tests/TKG/output_16842244632593/jdk_util_1/work/scratch/1/core.20230516.040630.3419385.0001.dmp
07:06:44  Dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Personal/aqa-tests/TKG/output_16842244632593/jdk_util_1/work/scratch/1/javacore.20230516.040632.3419385.0002.txt
07:06:44  Running jstack on process 3419385
07:06:44  2023-05-16T04:06:33.119614840
07:06:44  Virtual machine: 3419385 JVM information:
07:06:44  JRE 11 Linux amd64-64-Bit 20230516_1474 (JIT enabled, AOT enabled)
07:06:44  OpenJ9   - b182f7a
07:06:44  OMR      - 779c51b
07:06:44  JCL      - ee54452 based on jdk-11.0.20+2
07:06:44  
07:06:44  "main" prio=5 Id=1 WAITING
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.waitImpl(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:251)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:219)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.join(Thread.java:766)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.join(Thread.java:721)
07:06:44  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:198)
07:06:44  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
07:06:44  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
07:06:44  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
07:06:44  
07:06:44  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
07:06:44  
07:06:44  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
07:06:44  
07:06:44  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
07:06:44  
07:06:44  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
07:06:44  
07:06:44  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
07:06:44  
07:06:44  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
07:06:44  
07:06:44  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
07:06:44  
07:06:44  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
07:06:44  
07:06:44  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
07:06:44  
07:06:44  "IProfiler" prio=5 Id=12 RUNNABLE
07:06:44  
07:06:44  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.waitImpl(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:251)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:219)
07:06:44  	at java.base@11.0.20-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.run(Thread.java:839)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
07:06:44  
07:06:44  "Finalizer thread" prio=5 Id=13 RUNNABLE
07:06:44  
07:06:44  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
07:06:44  
07:06:44  "GC Worker" prio=5 Id=15 RUNNABLE
07:06:44  
07:06:44  "GC Worker" prio=5 Id=16 RUNNABLE
07:06:44  
07:06:44  "GC Worker" prio=5 Id=17 RUNNABLE
07:06:44  
07:06:44  "Attach API wait loop" prio=10 Id=20 RUNNABLE
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
07:06:44  
07:06:44  "pool-1-thread-1" prio=5 Id=21 TIMED_WAITING
07:06:44  	at java.base@11.0.20-internal/jdk.internal.misc.Unsafe.park(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.run(Thread.java:839)
07:06:44  
07:06:44  "ClassByNameCache Reaper" prio=5 Id=41 WAITING
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.waitImpl(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:251)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:219)
07:06:44  	at java.base@11.0.20-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
07:06:44  	at java.base@11.0.20-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:109)
07:06:44  	at java.base@11.0.20-internal/java.io.ClassByNameCache$Reaper.run(ClassByNameCache.java:232)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.run(Thread.java:839)
07:06:44  
07:06:44  "process reaper (pid 3422867)" prio=10 Id=57 RUNNABLE
07:06:44  	at java.base@11.0.20-internal/java.lang.ProcessHandleImpl.waitForProcessExit0(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:141)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.run(Thread.java:839)
07:06:44  
07:06:44  "ForkJoinPool.commonPool-worker-3" prio=5 Id=76 WAITING
07:06:44  	at java.base@11.0.20-internal/jdk.internal.misc.Unsafe.park(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
07:06:44  
07:06:44  "AgentVMThread" prio=5 Id=105 WAITING
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.waitImpl(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:251)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:190)
07:06:44  	at java.base@11.0.20-internal/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
07:06:44  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:424)
07:06:44  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:399)
07:06:44  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:451)
07:06:44  	at jdk.test.lib.process.ProcessTools.executeCommand(ProcessTools.java:499)
07:06:44  	at ModuleTestUtil.runModuleWithCp(ModuleTestUtil.java:171)
07:06:44  	at BasicTest.RunBasicTestWithCp(BasicTest.java:146)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:06:44  	at java.base@11.0.20-internal/java.lang.reflect.Method.invoke(Method.java:566)
07:06:44  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
07:06:44  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
07:06:44  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
07:06:44  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
07:06:44  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
07:06:44  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
07:06:44  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
07:06:44  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
07:06:44  	at java.base@11.0.20-internal/java.util.ArrayList.forEach(ArrayList.java:1541)
07:06:44  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
07:06:44  	at app//org.testng.TestRunner.run(TestRunner.java:585)
07:06:44  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
07:06:44  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
07:06:44  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
07:06:44  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
07:06:44  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
07:06:44  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
07:06:44  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
07:06:44  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
07:06:44  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
07:06:44  	at app//org.testng.TestNG.run(TestNG.java:1037)
07:06:44  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
07:06:44  	at java.base@11.0.20-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:06:44  	at java.base@11.0.20-internal/java.lang.reflect.Method.invoke(Method.java:566)
07:06:44  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.run(Thread.java:839)
07:06:44  
07:06:44  "Thread-20" prio=5 Id=108 RUNNABLE
07:06:44  	at java.base@11.0.20-internal/java.io.FileInputStream.readBytes(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.io.FileInputStream.read(FileInputStream.java:279)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
07:06:44  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@9a252a78
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
07:06:44  	- locked java.io.BufferedInputStream@44b4b6f5
07:06:44  	at java.base@11.0.20-internal/java.io.FilterInputStream.read(FilterInputStream.java:107)
07:06:44  	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.FutureTask.run(FutureTask.java:264)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.run(Thread.java:839)
07:06:44  
07:06:44  "Thread-21" prio=5 Id=109 RUNNABLE
07:06:44  	at java.base@11.0.20-internal/java.io.FileInputStream.readBytes(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.io.FileInputStream.read(FileInputStream.java:279)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
07:06:44  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@16d00270
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
07:06:44  	at java.base@11.0.20-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
07:06:44  	- locked java.io.BufferedInputStream@1e71d891
07:06:44  	at java.base@11.0.20-internal/java.io.FilterInputStream.read(FilterInputStream.java:107)
07:06:44  	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
07:06:44  	at java.base@11.0.20-internal/java.util.concurrent.FutureTask.run(FutureTask.java:264)
07:06:44  	at java.base@11.0.20-internal/java.lang.Thread.run(Thread.java:839)
07:06:44  
07:06:44  "file lock watchdog" prio=10 Id=111 TIMED_WAITING
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.waitImpl(Native Method)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:251)
07:06:44  	at java.base@11.0.20-internal/java.lang.Object.wait(Object.java:219)
07:06:44  	at java.base@11.0.20-internal/java.util.TimerThread.mainLoop(Timer.java:589)
07:06:44  	at java.base@11.0.20-internal/java.util.TimerThread.run(Timer.java:532)
07:06:44  
07:06:44  "Attachment portNumber: 33517" prio=10 Id=113 RUNNABLE
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
07:06:44  	at java.base@11.0.20-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
```

The same failures have also been observed on x86-64.

**Comment by JasonFengJ9** [comment]
FYI 
* https://github.com/eclipse-openj9/openj9/issues/17426
