### ISSUE TITLE
jdk_foreign_1_FAILED test StdLibTest.test_vprintf([]): failure

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17430]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_testList_0/262/)(`macaarch64rt6`):
```
java version "17.0.8" 2023-07-18
IBM Semeru Runtime Certified Edition 17.0.8+2 (build 17.0.8+2)
Eclipse OpenJ9 VM 17.0.8+2 (build master-d41eba984, JRE 17 Mac OS X aarch64-64-Bit 20230718_290 (JIT enabled, AOT enabled)
OpenJ9   - d41eba984
OMR      - 779c51b95
JCL      - 13ec6c2ed2 based on jdk-17.0.8+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_foreign_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_aarch64_mac&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9-IBM%2F290%2Fibm-semeru-certified-jdk_aarch64_mac_JDK17U_2023-05-15-00-17.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9-IBM%2F290%2Fibm-semeru-certified-testimage_aarch64_mac_JDK17U_2023-05-15-00-17.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=272&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-15T12:40:51.721Z] variation: Mode650
[2023-05-15T12:40:51.721Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-05-15T12:41:54.282Z] TEST: java/foreign/StdLibTest.java

[2023-05-15T12:41:54.288Z] test StdLibTest.test_vprintf([]): failure
[2023-05-15T12:41:54.288Z] java.lang.NullPointerException: A NULL memory address is not allowed for pointer.
[2023-05-15T12:41:54.288Z] 	at jdk.incubator.foreign/openj9.internal.foreign.abi.UpcallMHMetaData.getNativeArgRetAddrOfPtr(UpcallMHMetaData.java:103)
[2023-05-15T12:41:54.288Z] 	at jdk.incubator.foreign/openj9.internal.foreign.abi.InternalDowncallHandler.memAddrToLongArg(InternalDowncallHandler.java:203)
[2023-05-15T12:41:54.288Z] 	at StdLibTest$StdLibHelper.vprintf(StdLibTest.java:338)
[2023-05-15T12:41:54.288Z] 	at StdLibTest.test_vprintf(StdLibTest.java:159)

[2023-05-15T12:41:54.293Z] test StdLibTest.test_vprintf([]): failure
[2023-05-15T12:41:54.293Z] java.lang.NullPointerException: A NULL memory address is not allowed for pointer.
[2023-05-15T12:41:54.293Z] 	at jdk.incubator.foreign/openj9.internal.foreign.abi.UpcallMHMetaData.getNativeArgRetAddrOfPtr(UpcallMHMetaData.java:103)
[2023-05-15T12:41:54.293Z] 	at jdk.incubator.foreign/openj9.internal.foreign.abi.InternalDowncallHandler.memAddrToLongArg(InternalDowncallHandler.java:203)
[2023-05-15T12:41:54.293Z] 	at StdLibTest$StdLibHelper.vprintf(StdLibTest.java:338)
[2023-05-15T12:41:54.293Z] 	at StdLibTest.test_vprintf(StdLibTest.java:159)

[2023-05-15T12:43:18.473Z] Test results: passed: 64; failed: 1
[2023-05-15T12:43:22.569Z] Report written to /Users/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_testList_0/aqa-tests/TKG/output_16841538252745/jdk_foreign_1/report/html/report.html
[2023-05-15T12:43:22.569Z] Results written to /Users/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_testList_0/aqa-tests/TKG/output_16841538252745/jdk_foreign_1/work
[2023-05-15T12:43:22.569Z] Error: Some tests failed or other problems occurred.
[2023-05-15T12:43:22.569Z] -----------------------------------
[2023-05-15T12:43:22.569Z] jdk_foreign_1_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33001/) - all failed

**Comment by ChengJin01** [comment]
@JasonFengJ9, the failing message was removed at `https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java` via https://github.com/eclipse-openj9/openj9/pull/17414.

So I am wondering whether you rebased with the latest changes with FFI.

**Comment by ChengJin01** [comment]
`OpenJ9   - d41eba984` indicates the nightly build on `macOS/Aarch64` still stopped at https://github.com/eclipse-openj9/openj9/commit/d41eba9841f42fd40d07decdcf2c49b3887393fd (`Commits on May 12, 2023`) before the fix at https://github.com/eclipse-openj9/openj9/commit/21851c16b7fbe46ecef213c0d2bc9aa80136711c (`Commits on May 15, 2023`) was merged 3 days later.

**Comment by ChengJin01** [comment]
It passed in the latest [internal nightly builds](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_aarch64_mac_testList_0/267/tapTestReport).
