### ISSUE TITLE
GenericSignatureFormatError 

### ISSUE THREAD

**Issue by MurderWind** [eclipse-openj9/openj9#17432]
when i  call method.getParameterAnnotations();  i get stack error like this

2023-05-18 Caused by: java.lang.reflect.GenericSignatureFormatError: Signature Parse error: Expected Field Type Signature
2023-05-18 	Remaining input: catalogId
2023-05-18 	at sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:297) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:485) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:188) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:436) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:241) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:226) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations2(AnnotationParser.java:184) ~[na:1.8.0_292]
2023-05-18 	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations(AnnotationParser.java:161) ~[na:1.8.0_292]
2023-05-18 	at java.lang.reflect.Executable.parseParameterAnnotations(Executable.java:80) ~[na:1.8.0_292]
2023-05-18 	at java.lang.reflect.Executable.sharedGetParameterAnnotations(Executable.java:555) ~[na:1.8.0_292]
2023-05-18 	at java.lang.reflect.Method.getParameterAnnotations(Method.java:639) ~[na:1.8.0_292]

**Comment by JasonFengJ9** [comment]
@MurderWind what's the java level/platform, is there a testcase to share?

**Comment by MurderWind** [comment]
> @MurderWind what's the java level/platform, is there a testcase to share?

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210421_1000 (JIT enabled, AOT enabled)

`@Around("controllerMethodPointcut()") 
    public Object Interceptor(ProceedingJoinPoint pjp) throws Throwable {
        MethodSignature signature = (MethodSignature) pjp.getSignature();
        Method method = signature.getMethod();

        RequestAttributes ra = RequestContextHolder.getRequestAttributes();
        ServletRequestAttributes sra = (ServletRequestAttributes) ra;
        HttpServletRequest request = null;
        if (sra != null) {
            request = sra.getRequest();
        }
        Object result = null;

        Object[] args = pjp.getArgs();
        Object[] argstrans = args.clone();
        if (request != null) {
            Map<String, ?> paramMap = getRequestMap(request.getParameterMap());

            if (paramMap != null && args != null) {
                argstrans = this.parseParamter(paramMap, method, args);
            }

        }

        if (result == null) {

        
            result = pjp.proceed(argstrans);

        }

        return result;
    }

  private Object[] parseParamter(Map<String, ?> paramMap, Method method, Object[] orparam) throws IOException, InstantiationException, IllegalAccessException {
        Annotation[][] methodAnnotations = method.getParameterAnnotations();
       /***   business code ***/

     return null;

}`

**Comment by pshipton** [comment]
@JasonFengJ9 were you able to get the testcase running? It looks to me like there are significant pieces missing that may impact reproducibility. 

@MurderWind have you tried a later build? 0.26 is quite old, there may have been fixes since then. 0.38 is the latest.
