### ISSUE TITLE
[JDK20/FFI_Jtreg] AssertionError captured in TestLayouts on AIX

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17443]
A couple of AssertionError were captured in this failing test suite `TestLayouts ` at https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/963ffe3f346a4c033095bb8df5ff8d8f30636a5d/test/jdk/java/foreign/TestLayouts.java#L180:
```
[2023-05-19T14:08:25.799Z] test TestLayouts.testAlignmentString(D64, 64): failure
[2023-05-19T14:08:25.799Z] java.lang.AssertionError: expected [true] but found [false]
[2023-05-19T14:08:25.799Z] 	at org.testng.Assert.fail(Assert.java:99)
[2023-05-19T14:08:25.799Z] 	at org.testng.Assert.failNotEquals(Assert.java:1037)
[2023-05-19T14:08:25.799Z] 	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
[2023-05-19T14:08:25.799Z] 	at org.testng.Assert.assertEquals(Assert.java:122)
[2023-05-19T14:08:25.799Z] 	at org.testng.Assert.assertEquals(Assert.java:819)
[2023-05-19T14:08:25.799Z] 	at org.testng.Assert.assertEquals(Assert.java:829)
[2023-05-19T14:08:25.799Z] 	at TestLayouts.testAlignmentString(TestLayouts.java:180)
```
against the test case:
```
  public void testAlignmentString(MemoryLayout layout, long bitAlign) {
        long[] alignments = { 8, 16, 32, 64, 128 };
        for (long a : alignments) {
            if (layout.bitAlignment() == layout.bitSize()) {
                assertFalse(layout.toString().contains("%"));
                assertEquals(layout.withBitAlignment(a).toString().contains("%"), a != bitAlign); <--------
            }
        }
    }
```

FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
The test case has nothing to do with the code in downcall & upcall but something related to the `ValueLayout` specific changes in OpenJDK. So I will need to check the related code in OpenJDK to see why it failed in JDK20 while passed in JDK17.

**Comment by ChengJin01** [comment]
[1] Investigation indicates the test failure when checking the symbol `%` which was added to the `JAVA_DOUBLE` layout  in `decorateLayoutString()` by https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/963ffe3f346a4c033095bb8df5ff8d8f30636a5d/src/java.base/share/classes/jdk/internal/foreign/layout/AbstractLayout.java#L138 when generating the layout string via `toString()`:
```
src/java.base/share/classes/jdk/internal/foreign/layout/ValueLayouts.java
        public final String toString() {
            char descriptor = carrier == MemorySegment.class ? 'A' : carrier.descriptorString().charAt(0);
            if (order == ByteOrder.LITTLE_ENDIAN) {
                descriptor = Character.toLowerCase(descriptor);
            }
            return decorateLayoutString(String.format("%s%d", descriptor, bitSize())); <-----
        }

src/java.base/share/classes/jdk/internal/foreign/layout/AbstractLayout.java
 String decorateLayoutString(String s) {
        if (name().isPresent()) {
            s = String.format("%s(%s)", s, name().get());
        }
        if (!hasNaturalAlignment()) {
            s = bitAlignment + "%" + s; <---------
        }
        return s;
    }
```
in which case the related code in JDK17 was totally refactored and replaced with new implementation in JDK20 as for `hasNaturalAlignment()` (introduced in JDK20) that was modified via src/java.base/share/classes/jdk/internal/foreign/layout/ValueLayouts.java to fix the alignment issue with `JAVA_DOUBLE` on AIX.
```
       @Override
        public boolean hasNaturalAlignment() {
            return isAixOS ? ((bitAlignment() % 32) == 0) : super.hasNaturalAlignment(); <------
        }
    }
```
That means `%` is ignored in `JAVA_DOUBLE` when the adjusted alignment is 32, 64, 128 in test case.

Considering that it is pointless to check `%` in `JAVA_DOUBLE` from the OpenJ9/FFI implementation perspective, the check should be skipped in such case on AIX.

**Comment by ChengJin01** [comment]
With the test fix at https://github.com/ChengJin01/openj9-openjdk-jdk20/commit/cba3dedae056b688287e7bd3ff2c278ae46246b6, the test suite passed as expected on AIX.
```
----------System.out:(85/4540)----------
test TestLayouts.testAlignmentString(B8, 8): success
test TestLayouts.testAlignmentString(C16, 16): success
test TestLayouts.testAlignmentString(S16, 16): success
test TestLayouts.testAlignmentString(I32, 32): success
test TestLayouts.testAlignmentString(F32, 32): success
test TestLayouts.testAlignmentString(J64, 64): success
test TestLayouts.testAlignmentString(D64, 64): success <-----------
test TestLayouts.testAlignmentString([4:B8], 8): success
...

===============================================
test/jdk/java/foreign/TestLayouts.java
Total tests run: 79, Passes: 79, Failures: 0, Skips: 0
===============================================

```

**Comment by ChengJin01** [comment]
Close the issue as resolved at https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/49.
