### ISSUE TITLE
jdk_util_1_FAILED java/util/zip/ZipFile/ManyEntries.java invalid entry crc-32 & java/util/zip/TestCRC32.java Calculated checksum result was invalid

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17444]
[JDK20 ppc64le_linux](https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_ppc64le_linux_Nightly/59/consoleFull)
```
22:27:36  ===============================================
22:27:36  Running test jdk_util_1 ...
22:27:36  ===============================================
22:27:36  jdk_util_1 Start Time: Fri May 19 22:27:35 2023 Epoch Time (ms): 1684549655618
22:27:36  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
22:27:36  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

22:44:30  TEST: java/util/zip/ZipFile/ManyEntries.java

22:44:30  STDERR:
22:44:30  java.util.zip.ZipException: invalid entry crc-32 (expected 0x0 but got 0xa0058808)
22:44:30  	at java.base/java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:308)
22:44:30  	at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:201)
22:44:30  	at ManyEntries.test(ManyEntries.java:75)
22:44:30  	at ManyEntries.main(ManyEntries.java:45)
22:44:30  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:44:30  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
22:44:30  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
22:44:30  	at java.base/java.lang.Thread.run(Thread.java:1639)
22:44:30  	Suppressed: java.util.zip.ZipException: invalid entry crc-32 (expected 0x0 but got 0xa0058808)
22:44:30  		at java.base/java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:308)
22:44:30  		at java.base/java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:373)
22:44:30  		at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:244)
22:44:30  		at java.base/java.util.zip.ZipOutputStream.close(ZipOutputStream.java:390)
22:44:30  		at ManyEntries.test(ManyEntries.java:58)
22:44:30  		... 5 more
22:44:30  TEST RESULT: Failed. Execution failed: `main' threw exception: java.util.zip.ZipException: invalid entry crc-32 (expected 0x0 but got 0xa0058808)
22:44:30  --------------------------------------------------
22:46:01  Test results: passed: 920; failed: 1
22:46:04  Report written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16845449823925/jdk_util_1/report/html/report.html
22:46:04  Results written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16845449823925/jdk_util_1/work
22:46:04  Error: Some tests failed or other problems occurred.
22:46:04  -----------------------------------
22:46:04  jdk_util_1_FAILED
```

[JDK20 ppc64le_linux](https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_ppc64le_linux_OMR/8/consoleFull)
```
14:59:55  ===============================================
14:59:55  Running test jdk_util_1 ...
14:59:55  ===============================================
14:59:55  jdk_util_1 Start Time: Fri May 19 15:59:15 2023 Epoch Time (ms): 1684522755376
14:59:55  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
14:59:55  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

15:26:51  TEST: java/util/zip/TestCRC32.java

15:26:51  STDERR:
15:26:51  java.lang.RuntimeException: Calculated checksum result was invalid. Expected cbf43926, but got 0.
15:26:51  	at ChecksumBase.checkChecksum(ChecksumBase.java:92)
15:26:51  	at ChecksumBase.testBytes(ChecksumBase.java:56)
15:26:51  	at ChecksumBase.testAll(ChecksumBase.java:37)
15:26:51  	at TestCRC32.main(TestCRC32.java:37)
15:26:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:26:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:26:51  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
15:26:51  	at java.base/java.lang.Thread.run(Thread.java:1639)
15:26:51  
15:26:51  JavaTest Message: Test threw exception: java.lang.RuntimeException
```

[JDK8 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_testList_1/354/)(`aix823`)
[JDK11 ppc64_aix](https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_OMR/8/consoleFull)
[JDK17 ppc64_aix](https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR/8/consoleFull)

_Originally posted by @JasonFengJ9 in https://github.com/eclipse-openj9/openj9/issues/14948#issuecomment-1555942475_
            
This failure occurred across Java level/platforms abuilds, tentatively set it as a blocker.
JDK8 abuild - https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK8-Acceptance/69/
JDK11 abuild - https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK11-Acceptance/82/
JDK17 abuild - https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK17-Acceptance/66/
JDK20 abuild - https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK20-Acceptance/4/
OMR abuild - https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/520/

**Comment by JasonFengJ9** [comment]
@bhavanisn as per our Slack conversation, pls provide an update on the PR in progress.

**Comment by JasonFengJ9** [comment]
> Hoping to have a PR by tomorrow.

Thanks for the update, is this a straightforward change? I am wondering is it safer to revert the change and allow OMR acceptance build to proceed which blocks `0.40` code split initially targeted on May 19th (now delayed one week).
If we are confident the fix can be reviewed and delivered no later than this Friday, I have no objections.

FYI @zl-wang @0xdaryl
