### ISSUE TITLE
CRIU ppc64le_linux SystemCheckpointException: Could not dump the JVM processes, err=-52

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17457]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_testList_2/450/)(`rhel7lert-11`):
```
java version "11.0.20-beta" 2023-07-18
IBM Semeru Runtime Certified Edition 11.0.20+2-202305232206 (build 11.0.20-beta+2-202305232206)
Eclipse OpenJ9 VM 11.0.20+2-202305232206 (build master-37e239e9e, JRE 11 Linux ppc64le-64-Bit Compressed References 20230523_585 (JIT enabled, AOT enabled)
OpenJ9   - 37e239e9e
OMR      - 779c51b95
JCL      - fd2b7aa3f2 based on jdk-11.0.20+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=cmdLineTester_criu_keepCheckpoint_4&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.functional_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F585%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK11U_2023-05-23-22-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F585%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK11U_2023-05-23-22-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=509&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-23T23:08:00.099Z] variation: -Xint -XX:+CRIURestoreNonPortableMode
[2023-05-23T23:08:00.099Z] JVM_OPTIONS:  -Xint -XX:+CRIURestoreNonPortableMode 

[2023-05-23T23:08:00.099Z] TESTING:
[2023-05-23T23:08:00.587Z] *** Starting test suite: J9 Criu Command-Line Option Tests ***
[2023-05-23T23:08:00.587Z] Testing: Create Criu Checkpoint Image without Restore
[2023-05-23T23:08:01.008Z] Test start time: 2023/05/23 16:08:00 Pacific Standard Time
[2023-05-23T23:08:01.008Z] Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_testList_2/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_testList_2/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_testList_2/openjdkbinary/j2sdk-image/bin/java " -Xint -XX:+CRIURestoreNonPortableMode " org.openj9.criu.CRIUSimpleTest 1 1 true
[2023-05-23T23:08:01.008Z] Time spent starting: 101 milliseconds
[2023-05-23T23:08:01.938Z] Time spent executing: 1034 milliseconds
[2023-05-23T23:08:01.938Z] Test result: FAILED
[2023-05-23T23:08:01.938Z] Output from test:
[2023-05-23T23:08:01.938Z]  [OUT] start running script
[2023-05-23T23:08:01.938Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2023-05-23T23:08:01.938Z]  [OUT] export LD_BIND_NOT=on
[2023-05-23T23:08:01.938Z]  [OUT] Total checkpoint(s) 1:
[2023-05-23T23:08:01.938Z]  [OUT] Pre-checkpoint
[2023-05-23T23:08:01.938Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Tue May 23 16:08:01 PDT 2023, System.currentTimeMillis(): 1684883281144, System.nanoTime(): 840666207826807
[2023-05-23T23:08:01.938Z]  [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
[2023-05-23T23:08:01.938Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
[2023-05-23T23:08:01.938Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:649)
[2023-05-23T23:08:01.938Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
[2023-05-23T23:08:01.938Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
[2023-05-23T23:08:01.938Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:61)
[2023-05-23T23:08:01.938Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:43)
[2023-05-23T23:08:01.938Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:33)
[2023-05-23T23:08:01.938Z]  [OUT] finished script
[2023-05-23T23:08:01.938Z] >> Success condition was not found: [Output match: Killed]
[2023-05-23T23:08:01.938Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2023-05-23T23:08:01.938Z] >> Failure condition was not found: [Output match: Post-checkpoint]
[2023-05-23T23:08:01.938Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2023-05-23T23:08:01.938Z] >> Failure condition was not found: [Output match: Removed testOutput file]
[2023-05-23T23:08:01.938Z] >> Failure condition was not found: [Output match: Operation not permitted]
[2023-05-23T23:08:01.938Z] >> Failure condition was not found: [Output match: ERR]
[2023-05-23T23:08:01.938Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]

[2023-05-23T23:08:01.938Z] Number of PASSED tests: 0 out of 1
[2023-05-23T23:08:01.938Z] Number of FAILED tests: 1 out of 1
[2023-05-23T23:08:01.938Z] 
[2023-05-23T23:08:01.938Z] ---SUMMARY OF FAILED TESTS---
[2023-05-23T23:08:01.938Z] Create Criu Checkpoint Image without Restore
[2023-05-23T23:08:01.938Z] -----------------------------
[2023-05-23T23:08:01.938Z] 
[2023-05-23T23:08:01.938Z] -----------------------------------
[2023-05-23T23:08:01.938Z] cmdLineTester_criu_keepCheckpoint_4_FAILED
```

FYI @tajila

**Comment by JasonFengJ9** [comment]
[JDK11 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/485/)(`rhel8x86-rt1-4`)
```
[2023-05-25T23:11:14.074Z] variation: -Xjit:count=0 -XX:+CRIURestoreNonPortableMode
[2023-05-25T23:11:14.074Z] JVM_OPTIONS:  -Xjit:count=0 -XX:+CRIURestoreNonPortableMode 

[2023-05-25T23:11:14.490Z] TESTING:
[2023-05-25T23:11:14.915Z] *** Starting test suite: J9 Criu Command-Line Option Tests ***
[2023-05-25T23:11:14.915Z] Testing: Create Criu Checkpoint Image without Restore
[2023-05-25T23:11:14.915Z] Test start time: 2023/05/25 16:11:14 Pacific Standard Time
[2023-05-25T23:11:14.915Z] Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 -XX:+CRIURestoreNonPortableMode " org.openj9.criu.CRIUSimpleTest 1 1 true
[2023-05-25T23:11:14.915Z] Time spent starting: 46 milliseconds
[2023-05-25T23:11:35.790Z] Time spent executing: 17688 milliseconds
[2023-05-25T23:11:35.790Z] Test result: FAILED
[2023-05-25T23:11:35.790Z] Output from test:
[2023-05-25T23:11:35.790Z]  [OUT] start running script
[2023-05-25T23:11:35.790Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2023-05-25T23:11:35.790Z]  [OUT] export LD_BIND_NOT=on
[2023-05-25T23:11:35.790Z]  [OUT] Total checkpoint(s) 1:
[2023-05-25T23:11:35.790Z]  [OUT] Pre-checkpoint
[2023-05-25T23:11:35.790Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Thu May 25 16:11:27 PDT 2023, System.currentTimeMillis(): 1685056287455, System.nanoTime(): 3961060131922872
[2023-05-25T23:11:35.790Z]  [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
[2023-05-25T23:11:35.790Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
[2023-05-25T23:11:35.790Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:649)
[2023-05-25T23:11:35.790Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
[2023-05-25T23:11:35.790Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
[2023-05-25T23:11:35.790Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:61)
[2023-05-25T23:11:35.790Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:43)
[2023-05-25T23:11:35.790Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:33)
[2023-05-25T23:11:35.790Z]  [OUT] finished script
[2023-05-25T23:11:35.790Z] >> Success condition was not found: [Output match: Killed]
[2023-05-25T23:11:35.790Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2023-05-25T23:11:35.790Z] >> Failure condition was not found: [Output match: Post-checkpoint]
[2023-05-25T23:11:35.790Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2023-05-25T23:11:35.790Z] >> Failure condition was not found: [Output match: Removed testOutput file]
[2023-05-25T23:11:35.790Z] >> Failure condition was not found: [Output match: Operation not permitted]
[2023-05-25T23:11:35.790Z] >> Failure condition was not found: [Output match: ERR]
[2023-05-25T23:11:35.790Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]

[2023-05-25T23:11:35.790Z] ---TEST RESULTS---
[2023-05-25T23:11:35.790Z] Number of PASSED tests: 0 out of 1
[2023-05-25T23:11:35.790Z] Number of FAILED tests: 1 out of 1
[2023-05-25T23:11:35.790Z] 
[2023-05-25T23:11:35.790Z] ---SUMMARY OF FAILED TESTS---
[2023-05-25T23:11:35.790Z] Create Criu Checkpoint Image without Restore
[2023-05-25T23:11:35.790Z] -----------------------------
[2023-05-25T23:11:35.790Z] 
[2023-05-25T23:11:35.790Z] -----------------------------------
[2023-05-25T23:11:35.790Z] cmdLineTester_criu_keepCheckpoint_5_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/604
cmdLineTester_criu_nonPortableRestore_2
```
Testing: Create and Restore Criu Checkpoint Image once - TestDelayedOperations
Test start time: 2023/09/15 05:34:08 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 -XX:+CRIURestoreNonPortableMode " org.openj9.criu.TestDelayedOperations 1 1 false false
Time spent starting: 3 milliseconds
Time spent executing: 3943 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java -XX:+EnableCRIUSupport  -Xjit:count=0 -XX:+CRIURestoreNonPortableMode  -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar org.openj9.criu.TestDelayedOperations 1 1
 [OUT] currentThread : Thread[Thread-0,5,main] with name : Thread-0, current thread name: Thread-0, Fri Sep 15 05:34:10 EDT 2023, System.currentTimeMillis(): 1694770450669, System.nanoTime(): 11731526788127289
 [OUT] Pre-checkpoint - currentThread : Thread[Thread-0,5,main]
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: Thread-0, Fri Sep 15 05:34:10 EDT 2023, System.currentTimeMillis(): 1694770450817, System.nanoTime(): 11731526936122413
 [OUT] PreCheckpointHook() before threadAwaiting.interrupt() - currentThread : Thread[Thread-0,5,main], current thread name: Thread-0, Fri Sep 15 05:34:10 EDT 2023, System.currentTimeMillis(): 1694770450823, System.nanoTime(): 11731526942790195
 [OUT] PreCheckpointHook() after threadAwaiting.interrupt(), current thread name: Thread-0, Fri Sep 15 05:34:10 EDT 2023, System.currentTimeMillis(): 1694770450824, System.nanoTime(): 11731526943209829
 [OUT] Exception in thread "Thread-0" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:679)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.TestDelayedOperations.lambda$testDelayedThreadInterrupt$0(TestDelayedOperations.java:71)
 [OUT] 	at java.base/java.lang.Thread.run(Thread.java:839)
 [OUT] Error (criu/protobuf.c:72): Unexpected EOF on (empty-image)
 [OUT] Removed test output files
 [OUT] finished script
>> Success condition was not found: [Output match: TestDelayedOperations.testDelayedThreadInterrupt(): PASSED]
>> Required condition was not found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Failure condition was not found: [Output match: TestDelayedOperations.testDelayedThreadInterrupt(): FAILED]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
>> Failure condition was not found: [Output match: User requested Java dump using]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/605 - [ub20p8j91](https://openj9-jenkins.osuosl.org/computer/ub20p8j91)
cmdLineTester_criu_nonPortableRestore_Xtrace_methodtrace_3
```
Testing: Restore trace options test with -Xtrace before checkpoint - 1
Test start time: 2023/09/16 02:48:29 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xgcpolicy:optthruput  -Xtrace:print=mt,methods=org/eclipse/openj9/criu/CRIUSupport.registerRestoreOptionsFile()" org.openj9.criu.OptionsFileTest TraceOptionsTest1 1
Time spent starting: 59 milliseconds
Time spent executing: 2989 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java -XX:+EnableCRIUSupport  -Xgcpolicy:optthruput  -Xtrace:print=mt,methods=org/eclipse/openj9/criu/CRIUSupport.registerRestoreOptionsFile() -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar org.openj9.criu.OptionsFileTest TraceOptionsTest1 1
 [OUT] 06:48:29.651*0xa0700              mt.0        > org/eclipse/openj9/criu/CRIUSupport.registerRestoreOptionsFile(Ljava/nio/file/Path;)Lorg/eclipse/openj9/criu/CRIUSupport; bytecode method, this = 0x81051768
 [OUT] 06:48:29.651 0xa0700              mt.18       - this: org/eclipse/openj9/criu/CRIUSupport@0000000081051768 method arguments: (sun/nio/fs/UnixPath@0000000081048680)
 [OUT] 06:48:29.653 0xa0700              mt.6        < org/eclipse/openj9/criu/CRIUSupport.registerRestoreOptionsFile(Ljava/nio/file/Path;)Lorg/eclipse/openj9/criu/CRIUSupport; bytecode method
 [OUT] 06:48:29.653 0xa0700              mt.28       - return value: org/eclipse/openj9/criu/CRIUSupport@0000000081051768
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Sat Sep 16 02:48:29 EDT 2023, System.currentTimeMillis(): 1694846909685, System.nanoTime(): 11807985804414776
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:679)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.OptionsFileTest.traceOptionsTest1(OptionsFileTest.java:193)
 [OUT] 	at org.openj9.criu.OptionsFileTest.main(OptionsFileTest.java:51)
 [OUT] Error (criu/protobuf.c:72): Unexpected EOF on (empty-image)
 [OUT] Removed test output files
 [OUT] finished script
>> Success condition was not found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Success condition was not found: [Output match: terminateRemainingThreads]
>> Success condition was not found: [Output match: java/lang/System.getProperties()Ljava/util/Properties;]
>> Success condition was not found: [Output match: Post-checkpoint]
>> Success condition was not found: [Output match: User requested Java dump]
>> Failure condition was not found: [Output match: org.eclipse.openj9.criu.JVMRestoreException]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
``

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/545 - [ub18-ppcle-2](https://openj9-jenkins.osuosl.org/computer/ub18-ppcle-2)
```
Testing: Restore trace options test with no trace options specified before checkpoint - 1
Test start time: 2023/09/16 01:18:39 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xgcpolicy:optavgpause " org.openj9.criu.OptionsFileTest TraceOptionsTest1 1
Time spent starting: 3 milliseconds
Time spent executing: 3406 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java -XX:+EnableCRIUSupport  -Xgcpolicy:optavgpause  -cp /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar org.openj9.criu.OptionsFileTest TraceOptionsTest1 1
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Sat Sep 16 01:18:40 EDT 2023, System.currentTimeMillis(): 1694841520092, System.nanoTime(): 11802399624707407
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:680)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.OptionsFileTest.traceOptionsTest1(OptionsFileTest.java:193)
 [OUT] 	at org.openj9.criu.OptionsFileTest.main(OptionsFileTest.java:51)
 [OUT] Error (criu/protobuf.c:72): Unexpected EOF on (empty-image)
 [OUT] Removed test output files
 [OUT] finished script
>> Success condition was not found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Success condition was not found: [Output match: terminateRemainingThreads]
>> Success condition was not found: [Output match: java/lang/System.getProperties()Ljava/util/Properties;]
>> Success condition was not found: [Output match: TEST PASSED]
>> Success condition was not found: [Output match: User requested Java dump]
>> Success condition was not found: [Output match: Post-checkpoint]
>> Failure condition was not found: [Output match: org.eclipse.openj9.criu.JVMRestoreException]
>> Failure condition was not found: [Output match: TEST FAILED]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_aarch64_linux_Nightly_testList_0/358 - [ubu22-aarch64-4](https://openj9-jenkins.osuosl.org/computer/ubu22-aarch64-4)
