### ISSUE TITLE
Mockito fails with "cannot mock" exceptions in OpenJ9 11 and 17

### ISSUE THREAD

**Issue by yogregg** [eclipse-openj9/openj9#17454]
Java -version output
--------------------

openjdk version "11.0.17" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20221031_487 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8)

Summary of problem
------------------

The mockito Java mocking library frequently throws "cannot mock" exceptions when using OpenJ9 that I have not seen on other Java implementations.  This problem happens with at least OpenJ9 11 and 17 and at least on both Windows and Linux.  The Java version output above it just one of many failing versions I've tried.  Here's an example exception:

```
Mockito cannot mock this class: class org.mockito.internal.creation.bytebuddy.AbstractByteBuddyMockMakerTest$SomeClass.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 11
JVM vendor name    : Eclipse OpenJ9
JVM vendor version : openj9-0.35.0
JVM name           : Eclipse OpenJ9 VM
JVM version        : 11.0.17+8
JVM info           : JRE 11 Windows 10 amd64-64-Bit Compressed References 20221031_487 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class org.mockito.internal.creation.bytebuddy.AbstractByteBuddyMockMakerTest$SomeClass]
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.prettifyFailure(InlineDelegateByteBuddyMockMaker.java:441)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:404)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:355)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:334)
	at app//org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at app//org.mockito.internal.creation.AbstractMockMakerTest.should_reset_mock_and_set_new_handler(AbstractMockMakerTest.java:47)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy4.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class org.mockito.internal.creation.bytebuddy.AbstractByteBuddyMockMakerTest$SomeClass]
	at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:298)
	at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
	at app//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:47)
	at app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	at app//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:396)
	... 46 more
Caused by: java.lang.instrument.UnmodifiableClassException
	at java.instrument@11.0.17/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument@11.0.17/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
	... 54 more
```

This is easy to reproduce from publicly available sources, because the mockito library's own unit tests have hundreds of failures of this sort when the tests are run with OpenJ9.  You just have to make a minor modification to mockito's top-level build.gradle, adding lines like this (referring to your own Java location):

```
    tasks.withType(Test) {
        executable = new File("c:/apps/jdk-11.0.17+8-semeru", "bin/java.exe")
    }
```

You can see more details on this including a zip file of mockito's test result reports when it is run this way in https://github.com/mockito/mockito/issues/2995

I'm reporting this here as well because this problem sounds possibly related to https://github.com/eclipse-openj9/openj9/issues/3410  That issue refers to a change made in https://github.com/gacholio/openj9/commit/71bed502d6916bb8920088784577eeac1d230b04 that apparently resolved the problem for some, but I'm still seeing similar failures.  The issue there was that java.lang.Object was not a modifiable class in OpenJ9 (classIsModifiable method in https://github.com/eclipse-openj9/openj9/blob/openj9-0.36.0/runtime/util/hshelp.c), which is consistent with the error stack.  That version is the modified version that apparently helped some people, but it still mentions in its comments that Object can't be modified in "extended HCR mode" (I don't know what that is).

This is getting in the way of testing our product on OpenJ9, which makes it impossible to say to our customers with any confidence that it is safe for them to use OpenJ9. 

What is the source of this problem?  Am I right to suspect that it is related to an ongoing but narrower inability to modify Object?  If so, what is "extended HCR mode" and is there some way to control whether we are using that or not, or is there some other fix or workaround for this?

**Comment by tajila** [comment]
@gacholio can you please take a look at this

**Comment by gacholio** [comment]
The only classes that should be unmodifiable are ones annotated with `@J9UnmodifiableClass` of which there are exactly three: `JITHelpers`, `VarHandleInternal` and `J9VMInternals`.

**Comment by gacholio** [comment]
Can you please try a more modern VM? The stated one is over a year old. The change to use the annotation claims to be 4 years old, so I'm not sure this will actually fix anything, but it's worth a try.

**Comment by yogregg** [comment]
@gacholio I tried running the mockito test suite just now using the latest IBM Semeru Java 17 runtime available at .  This one:

```
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Windows 10 amd64-64-Bit Compressed References 20230117_367 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```

The mockito tests still fail in the same way.  For example, here's one failure message.

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.mockito.internal.creation.bytebuddy.AbstractByteBuddyMockMakerTest$SomeClass.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 17
JVM vendor name    : Eclipse OpenJ9
JVM vendor version : openj9-0.36.0
JVM name           : Eclipse OpenJ9 VM
JVM version        : 17.0.6+10
JVM info           : JRE 17 Windows 10 amd64-64-Bit Compressed References 20230117_367 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.mockito.internal.creation.bytebuddy.AbstractByteBuddyMockMakerTest$SomeClass, class java.lang.Object]
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.prettifyFailure(InlineDelegateByteBuddyMockMaker.java:441)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:404)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:355)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:334)
	at app//org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at app//org.mockito.internal.creation.AbstractMockMakerTest.should_reset_mock_and_set_new_handler(AbstractMockMakerTest.java:47)
	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.mockito.internal.creation.bytebuddy.AbstractByteBuddyMockMakerTest$SomeClass, class java.lang.Object]
	at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:298)
	at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
	at app//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:47)
	at app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	at app//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:396)
	... 46 more
Caused by: java.lang.instrument.UnmodifiableClassException
	at java.instrument@17.0.6/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
	... 54 more
```

Unfortunately the UnmodifiableClassException doesn't say which class was unmodifiable, and it is coming from a method (retransformClasses) that takes a list of classes to transform.  But I strongly suspect it is java.lang.Object.

By the way, if the only unmodifiable classes really are just the three that you mention, then there's an error in the comment on the classIsModifiable method in openj9/runtime/util/hshelp.c, which says:

```
/*
 * Can't replace:
 * - primitive or array classes
 * - J9VMInternals
 * - sun.misc.Unsafe Anonymous classes
 * - Object (in extended HCR mode)
 */
jboolean
classIsModifiable(J9JavaVM * vm, J9Class * clazz)
{
	return !J9ROMCLASS_IS_UNMODIFIABLE(clazz->romClass);
}
```

**Comment by tajila** [comment]
@yogregg I've been able to reproduce this issue with `./gradlew build` is there a way to run a single test?

**Comment by gacholio** [comment]
If you can reproduce this, the next step is to modify a VM to print which class causes the problem. I'll produce a patch and build.

**Comment by yogregg** [comment]
@tajila regarding your question about running a single tests, I've always been a maven user, and never used gradle until my attempts to illustrate this issue using mockito's own tests.  But https://stackoverflow.com/questions/22505533/how-to-run-only-one-unit-test-class-using-gradle and other articles indicate that there's a --tests argument you can use to do that.

I've also learned that gradle does a lot of caching and dependency analysis on what it runs, and that if you rerun "gradlew build" or "gradlew test" when no relevant code has changed, it won't actually rerun the tests, even though it the test reports directory will still contain results.  I've found that "gradlew test --rerun-tasks" forces the tests to rerun, which I found useful in repeatedly running them to try to debug, even when I hadn't changed code.  I don't know if that's how an experienced gradle user would do it, but it seems to work for me.

**Comment by gacholio** [comment]
Patch: https://github.com/eclipse-openj9/openj9/compare/master...gacholio:openj9:unmod

Java 8 internal build: http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=52410

Java11 open build: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/16833/

**Comment by yogregg** [comment]
@gacholio has anyone tried reproducing this with the instrumented internal build yet to verify the unmodifiable class, or made other progress on diagnosing the issue?

**Comment by gacholio** [comment]
Apologies - Tobi has been away and I've been off sick the last couple of days. Hopefully we'll have an update by end of week.

**Comment by tajila** [comment]
@gacholio I tried it again, none of the ` unmodifiable: %.*s` were printed

**Comment by yogregg** [comment]
@gacholio When I was trying to reproduce this originally I was having trouble with getting gradle to actually rerun tests consistently. “gradlew test” didn’t actually rerun even though it appeared to. "gradlew test --rerun-tasks" seemed to do the trick for me. Is it possible that’s behind it appearing to be reproducible at first but not now?

Also so that I can more carefully compare your test results and mine would it be possible for you to attach the contents of mockito's top level build/reports/tests/test directory?  And are you able to reproduce with the publicly available recent Semeru runtime I used?

I am on vacation now and can’t look more carefully at the moment at some way to run just one specific test that I’m seeing this problem on.

**Comment by tajila** [comment]
The test above was run with `./gradlew test --rerun-tasks` so it looks like we still havent reproduced the refinition issue

**Comment by yogregg** [comment]
@tajila I tried running the mockito tests today with the same Windows Semeru 17.0.7+7 version that you used, and I am now seeing results more like yours: some JVM crashes, plus many NullPointerExceptions in ArrayList.  On quite a few tries, the test runs never finished at all (maybe related to the JVM crashes), and even when I did get lucky and have it finish, I didn't get any test results populated into the build/reports/tests/test directory, so I could only see the results from the last few tests that I could still see in my shell window.  So I don't know whether anything is still failing with the UnmodifiableClassException.  I tried again on the same sources (up to date mockito head as of today) with an Oracle Java 17 and only got two test failures, both very different, and I suspect that's just a real failure in the current unreleased mockito sources.

So, while the behavior seems to have changed in newer versions, mockito is still very broken on Semeru Java, and I hope that you can get to the bottom of it.  I gather that the new failure symptoms that you and I are both now seeing are something that you can reproduce.

**Comment by gacholio** [comment]
It might be worth taking the JIT out of the equation with:
```
set OPENJ9_JAVA_OPTIONS=-Xint
```
(or the equivalent on non-windows) before running.

**Comment by gacholio** [comment]
Or not - I still see loads of the same failures running without the JIT.

**Comment by tajila** [comment]
I was able to reproduce the original failures 

```
    Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.mockito.AnnotationsAreCopiedFromMockedTypeTest$OnMethod, class java.lang.Object]
        at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.prettifyFailure(InlineDelegateByteBuddyMockMaker.java:441)
        at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:404)
        at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:355)
        at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:334)
        at app//org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
        at app//org.mockito.internal.util.MockUtil.createMock(MockUtil.java:99)
        at app//org.mockito.internal.MockitoCore.mock(MockitoCore.java:88)
        at app//org.mockito.Mockito.mock(Mockito.java:2102)
        at app//org.mockito.Mockito.mock(Mockito.java:2017)
        at app//org.mockito.AnnotationsAreCopiedFromMockedTypeTest.mock_should_have_annotations_copied_from_mocked_type_on_method_parameters(AnnotationsAreCopiedFromMockedTypeTest.java:56)

        Caused by:
        org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.mockito.AnnotationsAreCopiedFromMockedTypeTest$OnMethod, class java.lang.Object]
            at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:307)
            at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:224)
            at app//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:47)
            at app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
            at app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
            at app//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
            at app//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
            at app//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
            at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:396)
            ... 8 more

            Caused by:
            java.lang.instrument.UnmodifiableClassException
                at java.instrument@17.0.8-internal/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
                at java.instrument@17.0.8-internal/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
                at app//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:290)
                ... 16 more
```
In every case it was `*** retrans - unmodifiable: java/lang/Object ***` that cause the issues

**Comment by tajila** [comment]
I've tracked the code to https://github.com/mockito/mockito/blob/222c14c97bc2ec59ec5e486ddaa6438edded0e5c/src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java#L266 which adds the super class to the list of classes that are retransformed

**Comment by tajila** [comment]
Looking at j/l/Object

```
> !j9romclass 0x00007F7F6CFC0878
J9ROMClass at 0x7f7f6cfc0878 {
  Fields for J9ROMClass:
	0x0: U32 romSize = 0x00000498 (1176)
	0x4: U32 singleScalarStaticCount = 0x00000000 (0)
	0x8: J9SRP(J9UTF8) className = !j9utf8 0x00007F7F6C936498
	0xc: J9SRP(J9UTF8) superclassName = !j9utf8 0x0000000000000000
	0x10: U32 modifiers = 0x00000021 (33)
	0x14: U32 extraModifiers = 0x08E00000 (148897792) //Unmodifiable is set
```

**Comment by tajila** [comment]
I think the culprit is https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/romclasses.c#L157

@gacholio

**Comment by gacholio** [comment]
I'll do some startup debug and see what's happening.

**Comment by gacholio** [comment]
The code appears to be doing what it intends. One side-effect: running `-Xint` is considered to have extensions enabled, so Object is unmodifiable interpreter-only, but should be modifiable if the JIT is enabled (and no debug capabilities have been acquired).

**Comment by gacholio** [comment]
Extensions enabled if `-Xfuture` is not specified and we are running either in `-Xint` mode or JIT in FSD mode.
https://github.com/eclipse-openj9/openj9/blob/83da51b4240c1aaa91ba99408cc0be8f74c41451/runtime/util/extendedHCR.c#L25-L76

**Comment by gacholio** [comment]
It would be better to always mark Object as modifiable, but reject extended changes at HCR time (the extensions enabled but not used case). I'm not immediately sure how difficult this would be in the current framework).

**Comment by gacholio** [comment]
@tajila You've looked into cores - why are we in extended mode (if we are)?

**Comment by gacholio** [comment]
There is also
```
#define J9_EXTENDED_RUNTIME_ENABLE_HCR 0x400
```

**Comment by tajila** [comment]
That core was running with -Xint

**Comment by gacholio** [comment]
I'll prototype the change to disallow extended changes the Object while leaving it generally modifiable.

**Comment by gacholio** [comment]
https://github.com/gacholio/openj9/tree/objectmod

Passes internal testing, but it's worth noting that we do not test the `Object` modification case locally at all.
