### ISSUE TITLE
CRIU zLinux SystemCheckpointException: The JVM attempted to load libcriu.so but was unable to: 1

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17455]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_s390x_linux_testList_1/406/)(`rhel9s390xrt-2`):
```
java version "17.0.8-beta" 2023-07-18
IBM Semeru Runtime Certified Edition 17.0.8+2-202305240519 (build 17.0.8-beta+2-202305240519)
Eclipse OpenJ9 VM 17.0.8+2-202305240519 (build master-37e239e9e, JRE 17 Linux s390x-64-Bit Compressed References 20230523_412 (JIT enabled, AOT enabled)
OpenJ9   - 37e239e9e
OMR      - 779c51b95
JCL      - adfa6c5f0f based on jdk-17.0.8+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=cmdLineTester_criu_keepCheckpoint_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.functional_s390x_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-s390x-openj9-IBM%2F412%2Fibm-semeru-certified-jdk_s390x_linux_JDK17U_2023-05-24-05-13.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-s390x-openj9-IBM%2F412%2Fibm-semeru-certified-testimage_s390x_linux_JDK17U_2023-05-24-05-13.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=427&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-24T06:44:54.784Z] variation: -Xint
[2023-05-24T06:44:54.784Z] JVM_OPTIONS:  -Xint 

[2023-05-24T06:44:54.784Z] TESTING:
[2023-05-24T06:44:55.773Z] *** Starting test suite: J9 Criu Command-Line Option Tests ***
[2023-05-24T06:44:55.773Z] Testing: Create Criu Checkpoint Image without Restore
[2023-05-24T06:44:55.773Z] Test start time: 2023/05/24 07:44:55 Greenwich Mean Time
[2023-05-24T06:44:55.773Z] Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xint " org.openj9.criu.CRIUSimpleTest 1 1 true
[2023-05-24T06:44:55.773Z] Time spent starting: 53 milliseconds
[2023-05-24T06:44:56.711Z] Time spent executing: 1079 milliseconds
[2023-05-24T06:44:56.711Z] Test result: FAILED
[2023-05-24T06:44:56.711Z] Output from test:
[2023-05-24T06:44:56.711Z]  [OUT] start running script
[2023-05-24T06:44:56.711Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2023-05-24T06:44:56.711Z]  [OUT] export LD_BIND_NOT=on
[2023-05-24T06:44:56.711Z]  [OUT] Total checkpoint(s) 1:
[2023-05-24T06:44:56.711Z]  [OUT] Pre-checkpoint
[2023-05-24T06:44:56.711Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed May 24 07:44:55 BST 2023, System.currentTimeMillis(): 1684910695981, System.nanoTime(): 1684910695977370967
[2023-05-24T06:44:56.711Z]  [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: The JVM attempted to load libcriu.so but was unable to: 1
[2023-05-24T06:44:56.711Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
[2023-05-24T06:44:56.711Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:650)
[2023-05-24T06:44:56.711Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
[2023-05-24T06:44:56.711Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
[2023-05-24T06:44:56.711Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:61)
[2023-05-24T06:44:56.712Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:43)
[2023-05-24T06:44:56.712Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:33)
[2023-05-24T06:44:56.712Z]  [OUT] finished script
[2023-05-24T06:44:56.712Z] >> Success condition was not found: [Output match: Killed]
[2023-05-24T06:44:56.712Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2023-05-24T06:44:56.712Z] >> Failure condition was not found: [Output match: Post-checkpoint]
[2023-05-24T06:44:56.712Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2023-05-24T06:44:56.712Z] >> Failure condition was not found: [Output match: Removed testOutput file]
[2023-05-24T06:44:56.712Z] >> Failure condition was not found: [Output match: Operation not permitted]
[2023-05-24T06:44:56.712Z] >> Failure condition was not found: [Output match: ERR]
[2023-05-24T06:44:56.712Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
[2023-05-24T06:44:56.712Z] 
[2023-05-24T06:44:56.712Z] 
[2023-05-24T06:44:56.712Z] ---TEST RESULTS---
[2023-05-24T06:44:56.712Z] Number of PASSED tests: 0 out of 1
[2023-05-24T06:44:56.712Z] Number of FAILED tests: 1 out of 1
[2023-05-24T06:44:56.712Z] 
[2023-05-24T06:44:56.712Z] ---SUMMARY OF FAILED TESTS---
[2023-05-24T06:44:56.712Z] Create Criu Checkpoint Image without Restore
[2023-05-24T06:44:56.712Z] -----------------------------
[2023-05-24T06:44:56.712Z] 
[2023-05-24T06:44:57.728Z] -----------------------------------
[2023-05-24T06:44:57.728Z] cmdLineTester_criu_keepCheckpoint_1_FAILED
```

FYI @tajila

**Comment by JasonFengJ9** [comment]
[JDK17 ppc64le_linux milestone 2](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_rerun/8/)(`prhel248`)
```
openjdk version "17.0.8" 2023-07-18
IBM Semeru Runtime Open Edition 17.0.8.0-m2 (build 17.0.8+6)
Eclipse OpenJ9 VM 17.0.8.0-m2 (build v0.40.0-release-6eed0535c, JRE 17 Linux ppc64le-64-Bit Compressed References 20230718_482 (JIT enabled, AOT enabled)
OpenJ9   - 6eed0535c
OMR      - e80bff83b
JCL      - 7922ffc55ba based on jdk-17.0.8+6)

[2023-06-29T01:26:27.656Z] variation: -Xint -XX:+CRIURestoreNonPortableMode
[2023-06-29T01:26:27.656Z] JVM_OPTIONS:  -Xint -XX:+CRIURestoreNonPortableMode 

[2023-06-29T01:26:29.626Z] *** Starting test suite: J9 Criu Command-Line Option Tests ***
[2023-06-29T01:26:30.044Z] Testing: Create and Restore Criu Checkpoint Image once
[2023-06-29T01:26:32.007Z] Test start time: 2023/06/28 21:26:30 Eastern Standard Time
[2023-06-29T01:26:32.007Z] Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_rerun/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_rerun/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_rerun/openjdkbinary/j2sdk-image/bin/java " -Xint -XX:+CRIURestoreNonPortableMode " org.openj9.criu.CRIUSimpleTest 1 1 false
[2023-06-29T01:26:32.007Z] Time spent starting: 451 milliseconds
[2023-06-29T01:26:38.185Z] Time spent executing: 6070 milliseconds
[2023-06-29T01:26:38.185Z] Test result: FAILED
[2023-06-29T01:26:38.185Z] Output from test:
[2023-06-29T01:26:38.185Z]  [OUT] start running script
[2023-06-29T01:26:38.185Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2023-06-29T01:26:38.185Z]  [OUT] export LD_BIND_NOT=on
[2023-06-29T01:26:38.185Z]  [OUT] /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_rerun/openjdkbinary/j2sdk-image/bin/java -XX:+EnableCRIUSupport  -Xint -XX:+CRIURestoreNonPortableMode  -cp /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_rerun/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar org.openj9.criu.CRIUSimpleTest 1 1
[2023-06-29T01:26:38.185Z]  [OUT] Total checkpoint(s) 1:
[2023-06-29T01:26:38.185Z]  [OUT] Pre-checkpoint
[2023-06-29T01:26:38.186Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Jun 28 21:26:33 EDT 2023, System.currentTimeMillis(): 1688001993574, System.nanoTime(): 1311264296085030
[2023-06-29T01:26:38.186Z]  [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: The JVM attempted to load libcriu.so but was unable to: 1
[2023-06-29T01:26:38.186Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
[2023-06-29T01:26:38.186Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:677)
[2023-06-29T01:26:38.186Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
[2023-06-29T01:26:38.186Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
[2023-06-29T01:26:38.186Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:61)
[2023-06-29T01:26:38.186Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:43)
[2023-06-29T01:26:38.186Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:33)
[2023-06-29T01:26:38.186Z]  [OUT] Removed testOutput file
[2023-06-29T01:26:38.186Z]  [OUT] finished script
[2023-06-29T01:26:38.186Z]  [ERR] Error (criu/util.c:631): exited, status=4
[2023-06-29T01:26:38.186Z]  [ERR] Error (criu/util.c:631): exited, status=4
[2023-06-29T01:26:38.186Z]  [ERR] Warn  (criu/proc_parse.c:960): Write 4294967295 to /proc/self/loginuid failed: Operation not permitted
[2023-06-29T01:26:38.186Z]  [ERR] Warn  (criu/net.c:3175): Unable to get tun network namespace
[2023-06-29T01:26:38.186Z]  [ERR] Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Operation not permitted
[2023-06-29T01:26:38.186Z]  [ERR] Error (criu/net.c:3461): Unable create a network namespace: Operation not permitted
[2023-06-29T01:26:38.186Z]  [ERR] Warn  (criu/net.c:3517): NSID isn't reported for network links
[2023-06-29T01:26:38.186Z]  [ERR] Warn  (criu/net.c:3175): Unable to get socket network namespace
[2023-06-29T01:26:38.186Z]  [ERR] Error (criu/protobuf.c:74): Unexpected EOF on (empty-image)
[2023-06-29T01:26:38.186Z] >> Success condition was not found: [Output match: Killed]
[2023-06-29T01:26:38.186Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2023-06-29T01:26:38.186Z] >> Success condition was not found: [Output match: Post-checkpoint]
[2023-06-29T01:26:38.186Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2023-06-29T01:26:38.186Z] >> Failure condition was found: [Output match: Operation not permitted]
[2023-06-29T01:26:38.186Z] >> Success condition was not found: [Output match: Thread pid mismatch]
[2023-06-29T01:26:38.186Z] >> Success condition was not found: [Output match: do not match expected]
[2023-06-29T01:26:38.186Z] >> Success condition was not found: [Output match: Unable to create a thread:]
[2023-06-29T01:26:38.186Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by tajila** [comment]
Looks like machine issue `The JVM attempted to load libcriu.so but was unable to: 1`
