### ISSUE TITLE
JDK20 jdk_vector_1_FAILED jdk/incubator/vector/Byte64VectorTests.java Exception: failures: 1

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17462]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_x86-64_linux/10/)(`cent9x86-svl-rt2-1`):
```
openjdk version "20.0.1" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1+9 (build 20.0.1+9)
Eclipse OpenJ9 VM 20.0.1+9 (build master-623c7baa4, JRE 20 Linux amd64-64-Bit Compressed References 20230418_35 (JIT enabled, AOT enabled)
OpenJ9   - 623c7baa4
OMR      - 779c51b95
JCL      - a80d1107c based on jdk-20.0.1+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_vector_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-linux-x64-openj9%2F35%2Fibm-semeru-open-jdk_x64_linux_JDK20U_2023-05-27-15-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-linux-x64-openj9%2F35%2Fibm-semeru-open-testimage_x64_linux_JDK20U_2023-05-27-15-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=20&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk20&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-27T23:52:50.874Z] variation: Mode650
[2023-05-27T23:52:50.874Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-05-28T00:03:47.134Z] TEST: jdk/incubator/vector/Byte64VectorTests.java

[2023-05-28T00:03:47.135Z] test Byte64VectorTests.BITWISE_BLENDByte64VectorTests(byte[-i * 5], byte[i + 1], byte[i + 1]): failure
[2023-05-28T00:03:47.135Z] java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
[2023-05-28T00:03:47.135Z] 	at Byte64VectorTests.BITWISE_BLENDByte64VectorTests(Byte64VectorTests.java:4960)
[2023-05-28T00:03:47.135Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-05-28T00:03:47.135Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2023-05-28T00:03:47.135Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2023-05-28T00:03:47.136Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2023-05-28T00:03:47.136Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2023-05-28T00:03:47.136Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2023-05-28T00:03:47.136Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2023-05-28T00:03:47.136Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2023-05-28T00:03:47.136Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2023-05-28T00:03:47.136Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2023-05-28T00:03:47.136Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2023-05-28T00:03:47.136Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2023-05-28T00:03:47.136Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2023-05-28T00:03:47.136Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2023-05-28T00:03:47.136Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2023-05-28T00:03:47.136Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2023-05-28T00:03:47.136Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
[2023-05-28T00:03:47.136Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
[2023-05-28T00:03:47.136Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-05-28T00:03:47.136Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-05-28T00:03:47.136Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-05-28T00:03:47.136Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)

[2023-05-28T00:03:47.140Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 7
[2023-05-28T00:03:47.140Z] --------------------------------------------------
[2023-05-28T00:47:31.964Z] Test results: passed: 71; failed: 1
[2023-05-28T00:47:43.881Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16852023638410/jdk_vector_1/report/html/report.html
[2023-05-28T00:47:43.881Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16852023638410/jdk_vector_1/work
[2023-05-28T00:47:43.881Z] Error: Some tests failed or other problems occurred.
[2023-05-28T00:47:43.881Z] -----------------------------------
[2023-05-28T00:47:43.881Z] jdk_vector_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK20 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_x86-64_linux/13/)(`ubu22x86-rt4-1`)
```
openjdk version "20.0.1" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1.0-rc1 (build 20.0.1+9)
Eclipse OpenJ9 VM 20.0.1.0-rc1 (build v0.39.0-release-088b83604, JRE 20 Linux amd64-64-Bit Compressed References 20230418_46 (JIT enabled, AOT enabled)
OpenJ9   - 088b83604
OMR      - e4f52d2e4
JCL      - a8a96d7eb2c based on jdk-20.0.1+9)

[2023-06-10T02:29:46.110Z] variation: Mode150
[2023-06-10T02:29:46.110Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-06-10T02:39:20.004Z] TEST: jdk/incubator/vector/Byte64VectorTests.java

[2023-06-10T02:39:20.007Z] ...
[2023-06-10T02:39:20.007Z] Output overflow:
[2023-06-10T02:39:20.007Z] JT Harness has limited the test output to the text
[2023-06-10T02:39:20.007Z] at the beginning and the end, so that you can see how the
[2023-06-10T02:39:20.007Z] test began, and how it completed.
[2023-06-10T02:39:20.007Z] 
[2023-06-10T02:39:20.007Z] If you need to see more of the output from the test,
[2023-06-10T02:39:20.007Z] set the system property javatest.maxOutputSize to a higher
[2023-06-10T02:39:20.007Z] value. The current value is 100000
[2023-06-10T02:39:20.007Z] ...

[2023-06-10T02:39:20.010Z] jdk/incubator/vector/Byte64VectorTests.java
[2023-06-10T02:39:20.010Z] Total tests run: 3456, Passes: 3455, Failures: 1, Skips: 0
[2023-06-10T02:39:20.010Z] ===============================================
[2023-06-10T02:39:20.010Z] 
[2023-06-10T02:39:20.010Z] STDERR:
[2023-06-10T02:39:20.010Z] WARNING: Using incubator modules: jdk.incubator.vector
[2023-06-10T02:39:20.010Z] java.lang.Exception: failures: 1
[2023-06-10T02:39:20.010Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:95)
[2023-06-10T02:39:20.010Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
[2023-06-10T02:39:20.010Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-06-10T02:39:20.010Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-06-10T02:39:20.010Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-06-10T02:39:20.010Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-06-10T02:39:20.010Z] 
[2023-06-10T02:39:20.010Z] JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
[2023-06-10T02:39:20.011Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2023-06-10T02:39:20.011Z] --------------------------------------------------
[2023-06-10T03:23:02.029Z] Test results: passed: 71; failed: 1
[2023-06-10T03:23:02.029Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16863392582453/jdk_vector_0/report/html/report.html
[2023-06-10T03:23:02.029Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16863392582453/jdk_vector_0/work
[2023-06-10T03:23:02.029Z] Error: Some tests failed or other problems occurred.
[2023-06-10T03:23:02.029Z] -----------------------------------
[2023-06-10T03:23:02.029Z] jdk_vector_0_FAILED
```

**Comment by pshipton** [comment]
@gita-omr fyi

**Comment by gita-omr** [comment]
@BradleyWood could you please take a look?

**Comment by gita-omr** [comment]
@0xdaryl fyi

**Comment by JasonFengJ9** [comment]
[JDK20 0.40.0 milestone 1 x86-64](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_x86-64_linux/15/)(`sles15x86-rtp-rt3-1`)
```
openjdk version "20.0.1" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.2.0-m1 (build 20.0.1+9)
Eclipse OpenJ9 VM 20.0.2.0-m1 (build v0.40.0-release-71eab61a6, JRE 20 Linux amd64-64-Bit Compressed References 20230418_52 (JIT enabled, AOT enabled)
OpenJ9   - 71eab61a6
OMR      - 7344fbdf5
JCL      - 98dca89ded9 based on jdk-20.0.1+9)

[2023-06-17T04:39:32.160Z] variation: Mode150
[2023-06-17T04:39:32.160Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-06-17T04:44:38.534Z] ===============================================
[2023-06-17T04:44:38.534Z] jdk/incubator/vector/Byte64VectorTests.java
[2023-06-17T04:44:38.534Z] Total tests run: 3456, Passes: 3455, Failures: 1, Skips: 0
[2023-06-17T04:44:38.534Z] ===============================================
[2023-06-17T04:44:38.534Z] 
[2023-06-17T04:44:38.534Z] STDERR:
[2023-06-17T04:44:38.534Z] WARNING: Using incubator modules: jdk.incubator.vector
[2023-06-17T04:44:38.534Z] java.lang.Exception: failures: 1
[2023-06-17T04:44:38.534Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:95)
[2023-06-17T04:44:38.534Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
[2023-06-17T04:44:38.534Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-06-17T04:44:38.534Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-06-17T04:44:38.534Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-06-17T04:44:38.534Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-06-17T04:44:38.534Z] 
[2023-06-17T04:44:38.534Z] JavaTest Message: Test threw exception: java.lang.Exception: failures: 1

[2023-06-17T04:44:38.534Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2023-06-17T04:44:38.534Z] --------------------------------------------------
[2023-06-17T05:08:23.639Z] Test results: passed: 71; failed: 1
[2023-06-17T05:08:33.154Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16869679936058/jdk_vector_0/report/html/report.html
[2023-06-17T05:08:33.154Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16869679936058/jdk_vector_0/work
[2023-06-17T05:08:33.154Z] Error: Some tests failed or other problems occurred.
[2023-06-17T05:08:33.154Z] -----------------------------------
[2023-06-17T05:08:33.154Z] jdk_vector_0_FAILED
```

**Comment by BradleyWood** [comment]
This particular problem occurs when the VectorAPI optimization attempts to scalarize byte element vectors. After scalarization, we see the following tree. The problem occurs because the lshl node is a shift of 0 which does nothing. The result of its child is taken without clobbering it, causing GPR_0336 to be reused. When the result of the operation is being stored back, we see two addresses (load and store) being added together which causes the segmentation fault.

```
 n1551n   (  0)  treetop                                                                           
 n1550n   (  0)    bstorei  <array-shadow>[#226  Shadow] [flags 0x80000601 0x0 ] (cannotOverflow st
 n3752n   (  7)      aladd (in GPR_0336)                                                           
 n153n    (  0)        aload  r<auto slot 4>[#429  Auto] [flags 0x4007 0x0 ]                       
 n3750n   (  0)        ladd (in GPR_0336)                                                          
 n3748n   (  0)          lshl (in GPR_0336)                                                        
 n1271n   (  0)            ==>i2l (in GPR_0336) (highWordZero X>=0 )
 n3749n   (  0)            iconst 0 (X==0 X>=0 X<=0 )                                              
 n3751n   (  0)          lconst 8 (highWordZero X!=0 X>=0 )                                        
 n3763n   (  0)      i2b (in GPR_0368) (lazyClobber )                                              
 n1097n   (  0)        b2i (in GPR_0368) ()                                                        
 n3695n   (  0)          bloadi  <array-shadow>[#226  Shadow] [flags 0x80000601 0x0 ] ()           
 n3684n   (  0)            ==>aladd (in GPR_0336)
```

```asm
 [0x7fffcdaad600]  movsx  GPR_0368, byte ptr [GPR_0336]  
 [0x7fffcdaad720]  add    GPR_0336, 0x00000008   # ADD8RegImm
 [0x7fffcdaad840]  add    GPR_0336, qword ptr [vfp]     # AD
 [0x7fffcdaad8d0]  mov    byte ptr [GPR_0336], GPR_0368     
```
