### ISSUE TITLE
Local build failing with XCode 14.0.3 and above

### ISSUE THREAD

**Issue by theresa-m** [eclipse-openj9/openj9#17493]
OpenJ9 can be built with Xcode 15.0.1 once https://github.com/eclipse-openj9/openj9/pull/18351 is merged
~~Workaround: downgrade to Xcode 14.0.1~~

---
Here's what's been fixed so far:

- adler32.c compiler issues are with a 3rd party library zlib. ~~There's no target date for this fix current~~This is fixed in zlib 1.2.14, issue is tracked https://github.com/madler/zlib/issues/633. ~~The workaround is to add `-Wno-deprecated-non-prototype` to cflags.~~ Fixed by https://github.com/eclipse-openj9/openj9/pull/18137#event-10387701216
- unused variable errors. These are fixed in https://github.com/eclipse-openj9/openj9/pull/17696 and https://github.com/eclipse/omr/pull/7055
- unregognized dwarf tags https://github.com/eclipse/omr/pull/7148
- https://github.com/eclipse-openj9/openj9/pull/18351

**Comment by theresa-m** [comment]
This is a compilation error between zlib and the latest version of Clang in XCode 14.0.3 and up https://github.com/madler/zlib/issues/633

**Comment by theresa-m** [comment]
Adding `-Wno-deprecated-non-prototype` should suppress the issue.

**Comment by theresa-m** [comment]
I'm getting some fixable compiler errors (see linked prs) for unused variables and a segmentation error as well to look into
```
Creating jdk.jconsole.jmod
java.lang.NullPointerException
gmake[3]: *** [CreateJmods.gmk:233: /Users/theresamammarella/github/openj9-openjdk-jdk17/build/macosx-aarch64-server-release/support/images/jmods/_create_jdk.internal.jvmstat.jmod_exec.marker] Error 1
gmake[2]: *** [make/Main.gmk:360: jdk.internal.jvmstat-jmod] Error 2
gmake[2]: *** Waiting for unfinished jobs....
JVMDUMP010I System dump written to /Users/theresamammarella/github/openj9-openjdk-jdk17/make/core.20230628.112446.37771.0001.dmp
JVMDUMP032I JVM requested Java dump using '/Users/theresamammarella/github/openj9-openjdk-jdk17/make/javacore.20230628.112446.37771.0002.txt' in response to an event
JVMDUMP010I Java dump written to /Users/theresamammarella/github/openj9-openjdk-jdk17/make/javacore.20230628.112446.37771.0002.txt
JVMDUMP032I JVM requested Snap dump using '/Users/theresamammarella/github/openj9-openjdk-jdk17/make/Snap.20230628.112446.37771.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /Users/theresamammarella/github/openj9-openjdk-jdk17/make/Snap.20230628.112446.37771.0003.trc
JVMDUMP032I JVM requested JIT dump using '/Users/theresamammarella/github/openj9-openjdk-jdk17/make/jitdump.20230628.112446.37771.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'main' thread 0x000000015205D300
JVMDUMP053I JIT dump is recompiling java/util/HashMap.resize()[Ljava/util/HashMap$Node;
JVMDUMP053I JIT dump is recompiling java/util/HashMap.resize()[Ljava/util/HashMap$Node;
JVMDUMP053I JIT dump is recompiling java/util/HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object;
JVMDUMP053I JIT dump is recompiling java/util/HashSet.add(Ljava/lang/Object;)Z
JVMDUMP053I JIT dump is recompiling java/util/zip/ZipOutputStream.putNextEntry(Ljava/util/zip/ZipEntry;)V
JVMDUMP053I JIT dump is recompiling jdk/tools/jmod/JmodOutputStream.writeEntry(Ljava/io/InputStream;Ljdk/internal/jmod/JmodFile$Section;Ljava/lang/String;)V
JVMDUMP010I JIT dump written to /Users/theresamammarella/github/openj9-openjdk-jdk17/make/jitdump.20230628.112446.37771.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".
gmake[3]: *** [CreateJmods.gmk:233: /Users/theresamammarella/github/openj9-openjdk-jdk17/build/macosx-aarch64-server-release/support/images/jmods/_create_java.xml.jmod_exec.marker] Error 255
gmake[2]: *** [make/Main.gmk:360: java.xml-jmod] Error 2

ERROR: Build failed for target 'all' in configuration 'macosx-aarch64-server-release' (exit code 2) 
Stopping sjavac server
```

**Comment by knn-k** [comment]
Please try the following command line for building.

```
OPENJ9_JAVA_OPTIONS=-Xint make all
```

The `-Xint` option disables the JIT compiler during the build.  If your build failure disappears with the option, it means something was wrong with the JIT compiler.

Note that it takes much longer time in building than without the option.

**Comment by knn-k** [comment]
I used the toolchain of the following version on macOS Ventura, and the Java 11 build failed.

```
% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.HashMap.resize(HashMap.java:705)
	at java.base/java.util.HashMap.putVal(HashMap.java:659)
	at java.base/java.util.HashMap.put(HashMap.java:608)
	at java.base/jdk.internal.module.ModulePath.scanDirectory(ModulePath.java:290)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:232)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
	at java.base/jdk.internal.module.ModulePath.find(ModulePath.java:154)
	at build.tools.jigsaw.AddPackagesAttribute.main(AddPackagesAttribute.java:66)
make[3]: *** [/Users/konno/openj9/openj9-openjdk-jdk11/build/macosx-aarch64-normal-server-release/jdk/_packages_attribute.done] Error 1
```

**Comment by theresa-m** [comment]
Thanks, I rebuilt today and I'm no longer seeing the crash, instead a different (maybe related?) NPE. Perhaps the crash was a configuration issue on my end.

I'm also getting a DDR failure, which I've disabled with `--disable-ddr` for now.
```
Error: /Users/theresamammarella/github/openj9-openjdk-jdk17/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:623 getTypeTag - Getting tag from type die: DW_DLE_DIE_NULL (3)

Error: /Users/theresamammarella/github/openj9-openjdk-jdk17/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:623 getTypeTag - Getting tag from type die: DW_DLE_DIE_NULL (3)

Error: /Users/theresamammarella/github/openj9-openjdk-jdk17/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:862 createNewType - Symbol with name '' has unknown symbol tag: unknown (64176)

Error: /Users/theresamammarella/github/openj9-openjdk-jdk17/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:1565 traverse_cu_in_debug_section - Failed to add type.

Error: /Users/theresamammarella/github/openj9-openjdk-jdk17/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:1596 startScan - Failure scanning /Users/theresamammarella/github/openj9-openjdk-jdk17/build/macosx-aarch64-server-release/vm/runtime/libj9thr29.dylib.dSYM/Contents/Resources/DWARF/libj9thr29.dyl
```

I'm going to create a checklist of all these issues in the description so its easier to keep track of.

**Comment by knn-k** [comment]
I see a different DDR error in building Java 11 with `OPENJ9_JAVA_OPTIONS=-Xint` as shown below.  Building without `OPENJ9_JAVA_OPTIONS=-Xint` is OK.

```
=== Output from failing command(s) repeated here ===
* For target jdk_modules_java.base__the.java.base_batch:
* For target support_ddr_tools__the.BUILD_DDR_TOOLS_batch:
/Users/openj9/openj9-openjdk-jdk11/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/BytecodeGenerator.java:37: error: package jdk.internal.org.objectweb.asm is not visible
import jdk.internal.org.objectweb.asm.AnnotationVisitor;
                                 ^
  (package jdk.internal.org.objectweb.asm is declared in module java.base, which does not export it to the unnamed module)
/Users/openj9/openj9-openjdk-jdk11/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/BytecodeGenerator.java:38: error: package jdk.internal.org.objectweb.asm is not visible
import jdk.internal.org.objectweb.asm.ClassWriter;
                                 ^
  (package jdk.internal.org.objectweb.asm is declared in module java.base, which does not export it to the unnamed module)
/Users/openj9/openj9-openjdk-jdk11/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/BytecodeGenerator.java:39: error: package jdk.internal.org.objectweb.asm is not visible
import jdk.internal.org.objectweb.asm.Label;
                                 ^
  (package jdk.internal.org.objectweb.asm is declared in module java.base, which does not export it to the unnamed module)
/Users/openj9/openj9-openjdk-jdk11/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/BytecodeGenerator.java:40: error: package jdk.internal.org.objectweb.asm is not visible
import jdk.internal.org.objectweb.asm.MethodVisitor;
                                 ^
   ... (rest of output omitted)
```

**Comment by knn-k** [comment]
I opened Issue #17770 for my DDR error with `-Xint`.

**Comment by theresa-m** [comment]
After updated zlib the next error is with dwarf. @keithc-ca can you help with this?
```
Error: /Users/theresamammarella/openj9builds/openj9-openjdk-jdk/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:623 getTypeTag - Getting tag from type die: DW_DLE_DIE_NULL (3)

Error: /Users/theresamammarella/openj9builds/openj9-openjdk-jdk/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:623 getTypeTag - Getting tag from type die: DW_DLE_DIE_NULL (3)

Error: /Users/theresamammarella/openj9builds/openj9-openjdk-jdk/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:623 getTypeTag - Getting tag from type die: DW_DLE_DIE_NULL (3)

Error: /Users/theresamammarella/openj9builds/openj9-openjdk-jdk/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:623 getTypeTag - Getting tag from type die: DW_DLE_DIE_NULL (3)
```

**Comment by keithc-ca** [comment]
Perhaps the output format of `dwarfdump` has changed (again)?

It would be helpful to compare that outputs for a small input (e.g. for `libj9ddr_misc.dylib`) from working and non-working versions of XCode. If you can get that for me, I can have a look (I don't have a mac to be able to do that myself).

**Comment by theresa-m** [comment]
> Perhaps the output format of `dwarfdump` has changed (again)?
> 
> It would be helpful to compare that outputs for a small input (e.g. for `libj9ddr_misc.dylib`) from working and non-working versions of XCode. If you can get that for me, I can have a look (I don't have a mac to be able to do that myself).

Thanks! I'm actually not seeing `libj9ddr_misc.dylib` in my build. I picked `libmanagement_ext.dylib` for the smallest file.

I ran `dwarfdump libmanagement_ext.dylib.dSYM` for these results.

working version (Xcode 14.0.1): [dwarfdump_libmanagement_ext_xcode_14.0.1.txt](https://github.com/eclipse-openj9/openj9/files/12730173/dwarfdump_libmanagement_ext_xcode_14.0.1.txt)

failing version (Xcode 14.3.1): [dwarfdump_libmanagement_ext_xcode_14.3.1.txt](https://github.com/eclipse-openj9/openj9/files/12730441/dwarfdump_libmanagement_ext_xcode_14.3.1.txt)

**Comment by keithc-ca** [comment]
Sorry, I forgot the "29" part of the name, the file of interest is `libj9ddr_misc29.dylib.dSYM`.

**Comment by theresa-m** [comment]
I don't have that one either. In vm/runtime:
```
CMakeFiles				hookgen					libbcuwhite.dylib			libj9vmtest.dylib.dSYM			oti
J9TraceFormat.dat			hookgen.dSYM				libbcuwhite.dylib.dSYM			libj9vrb29.dylib			pltest
Makefile				include					libbcvrelationships.dylib		libj9vrb29.dylib.dSYM			pltest.dSYM
OMRTraceFormat.dat			invtest					libbcvrelationships.dylib.dSYM		libj9zlib29.dylib			port
algotest				invtest.dSYM				libbcvwhite.dylib			libj9zlib29.dylib.dSYM			properties.html
algotest.dSYM				j9cfg.h					libbcvwhite.dylib.dSYM			libjclse29.dylib			propstest
bcutil					j9jit.hdf				libclinkerffitests.dylib		libjclse29.dylib.dSYM			propstest.dSYM
bcverify				j9lib.h					libclinkerffitests.dylib.dSYM		libjcoregen29.dylib			rasdump
cassume					j9mm.hdf				libcuda4j29.dylib			libjcoregen29.dylib.dSYM		rastrace
cfdump					j9version.h				libcuda4j29.dylib.dSYM			libjlmagent29.dylib			redirector
cfdump.dSYM				j9vm					libffi					libjlmagent29.dylib.dSYM		runtimetools
cfdumper				j9vm.hdf				libgptest.dylib				libjniargtests.dylib			shared
cmake_install.cmake			j9vmconstantpool.c			libgptest.dylib.dSYM			libjniargtests.dylib.dSYM		shared_common
codert_vm				j9vmconstantpool.h			libhooktests.dylib			libjsig.dylib				shared_util
compiler				java.properties				libhooktests.dylib.dSYM			libjsig.dylib.dSYM			shrtest
constgen				java_ca.properties			libj9ben.dylib				libjvm.dylib				shrtest.dSYM
constgen.dSYM				java_cs.properties			libj9ben.dylib.dSYM			libjvm.dylib.dSYM			simplepool
copyright.c				java_de.properties			libj9dmp29.dylib			libjvmtitest.dylib			stackmap
ctest					java_es.properties			libj9dmp29.dylib.dSYM			libjvmtitest.dylib.dSYM			sunvmi
ctest.dSYM				java_fr.properties			libj9gc29.dylib				libloadLibraryTest.jnilib		testjep178_dynamic
cuda					java_hu.properties			libj9gc29.dylib.dSYM			libloadLibraryTest.jnilib.dSYM		testjep178_dynamic.dSYM
dbgext					java_it.properties			libj9gcchk29.dylib			libmanagement_ext.dylib			testjep178_static
dyntest					java_ja.properties			libj9gcchk29.dylib.dSYM			libmanagement_ext.dylib.dSYM		testjep178_static.dSYM
dyntest.dSYM				java_ko.properties			libj9hookable29.dylib			libmemorywatcher29.dylib		tests
exelib					java_pl.properties			libj9hookable29.dylib.dSYM		libmemorywatcher29.dylib.dSYM		thread
gc					java_pt_BR.properties			libj9jextract.dylib			libmigration.dylib			thrstatetest
gc_api					java_ru.properties			libj9jextract.dylib.dSYM		libmigration.dylib.dSYM			thrstatetest.dSYM
gc_base					java_sk.properties			libj9jit29.dylib			libomrsig.dylib				tracegen
gc_check				java_sl.properties			libj9jit29.dylib.dSYM			libomrsig.dylib.dSYM			tracegen.dSYM
gc_glue_java				java_tr.properties			libj9jnichk29.dylib			libosmemory29.dylib			tracemerge
gc_modron_standard			java_zh.properties			libj9jnichk29.dylib.dSYM		libosmemory29.dylib.dSYM		tracemerge.dSYM
gc_modron_startup			java_zh_CN.properties			libj9jvmti29.dylib			libsoftmxtest.dylib			tracemerge.stamp
gc_realtime				java_zh_TW.properties			libj9jvmti29.dylib.dSYM			libsoftmxtest.dylib.dSYM		util
gc_rwlocktest				jcl					libj9lazyClassLoad.dylib		libtestjvmtiA.dylib			util_core
gc_rwlocktest.dSYM			jextractnatives				libj9lazyClassLoad.dylib.dSYM		libtestjvmtiA.dylib.dSYM		verbose
gc_stats				jilgen					libj9prt29.dylib			libtestjvmtiB.dylib			verutil
gc_structs				jit_vm					libj9prt29.dylib.dSYM			libtestjvmtiB.dylib.dSYM		vm
gc_tests				jithook.h				libj9shr29.dylib			libtestlibA.dylib			vmLifecycleTests
gc_trace				jithook_internal.h			libj9shr29.dylib.dSYM			libtestlibA.dylib.dSYM			vmLifecycleTests.dSYM
gc_trace_standard			jnichk					libj9thr29.dylib			libtestlibB.dylib			vmchk
gc_trace_vlhgc				jniinv					libj9thr29.dylib.dSYM			libtestlibB.dylib.dSYM			vmhook.h
gc_verbose_handler_realtime		jsigWrapper				libj9thrnumanatives29.dylib		libvmruntimestateagent29.dylib		vmhook_internal.h
gc_verbose_handler_standard_java	jsigjnitest				libj9thrnumanatives29.dylib.dSYM	libvmruntimestateagent29.dylib.dSYM	vmtest
gc_verbose_handler_vlhgc		jsigjnitest.dSYM			libj9thrtestnatives29.dylib		mgmt					vmtest.dSYM
gc_verbose_java				jvmti					libj9thrtestnatives29.dylib.dSYM	mmhook.h				vmzipcachehook.h
gc_verbose_old				lib					libj9trc29.dylib			mmhook_internal.h			vmzipcachehook_internal.h
gc_verbose_old_events			libSharedClassesNativeAgent.dylib	libj9trc29.dylib.dSYM			nativevmargs				zip
gc_vlhgc				libSharedClassesNativeAgent.dylib.dSYM	libj9vm29.dylib				nativevmargs.dSYM			zipCachePool.hdf
gcchk					libanntests.dylib			libj9vm29.dylib.dSYM			nls					zlib
glaunch					libanntests.dylib.dSYM			libj9vmchk29.dylib			nls.stamp
glaunch.dSYM				libballoon29.dylib			libj9vmchk29.dylib.dSYM			omr
hookable				libballoon29.dylib.dSYM			libj9vmtest.dylib			options.default
```

**Comment by theresa-m** [comment]
Just ran it again to make sure and they are showing up now. Not sure what I did there to get the last result.

[dwarfdump_libj9ddr_misc29_xcode_14.3.1.txt](https://github.com/eclipse-openj9/openj9/files/12731417/dwarfdump_libj9ddr_misc29_xcode_14.3.1.txt)
[dwarfdump_libj9ddr_misc29_xcode_14.0.1.txt](https://github.com/eclipse-openj9/openj9/files/12731418/dwarfdump_libj9ddr_misc29_xcode_14.0.1.txt)

**Comment by keithc-ca** [comment]
I had a look at those files, but didn't see anything suspicious. In both files, all lines with `DW_AT_type` make references to identifiers of corresponding `DW_TAG_xxx` lines. They both use the same kinds of tags (some of which are not listed in `DwarfParser.cpp`, but if those were relevant, I would expect both to fail).

I think we'll need to improve the diagnostics of `omr_ddrgen` to provide more context so we can know which DIE has the missing (null) type.

**Comment by keithc-ca** [comment]
@theresa-m Could you try building with https://github.com/keithc-ca/omr/tree/ddr_diag and share the log? Perhaps it will help us pinpoint the larger issue.

**Comment by theresa-m** [comment]
Sorry for the delay, here is the output I got.
[ddr_diag_output.txt.zip](https://github.com/eclipse-openj9/openj9/files/12895066/ddr_diag_output.txt.zip)

**Comment by keithc-ca** [comment]
Could you also share the output of `dwarfdump vm/runtime/libj9thr29.dylib.dSYM/Contents/Resources/DWARF/libj9thr29.dylib`, please? Is anything written to `stderr` as that runs?

**Comment by keithc-ca** [comment]
From the output shared in https://github.com/eclipse-openj9/openj9/issues/17493#issuecomment-1735996914, I found that some elements have types that refer to elements with (currently unrecognized) tags `DW_TAG_reference_type` and `DW_TAG_unspecified_type`.

@theresa-m Could you try building with https://github.com/keithc-ca/omr/tree/dwarf_tag?

**Comment by theresa-m** [comment]
> Could you also share the output of `dwarfdump vm/runtime/libj9thr29.dylib.dSYM/Contents/Resources/DWARF/libj9thr29.dylib`, please? Is anything written to `stderr` as that runs?

Here's the output, building with your other branch now.
[dwarfdump_libj9thr_ddr_diag.txt](https://github.com/eclipse-openj9/openj9/files/12932288/dwarfdump_libj9thr_ddr_diag.txt)

**Comment by theresa-m** [comment]
I'm getting past the dwarfdump error to a new one:
```
Optimizing the exploded image
java.lang.module.FindException: Module jdk.attach not found, required by jdk.jconsole
gmake[3]: *** [ExplodedImageOptimize.gmk:41: /Users/theresamammarella/openj9builds/openj9-openjdk-jdk/build/macosx-aarch64-server-release/jdk/_optimize_image_exec.marker] Error 1
gmake[2]: *** [make/Main.gmk:507: exploded-image-optimize] Error 2
gmake[2]: *** Waiting for unfinished jobs....

ERROR: Build failed for target 'all' in configuration 'macosx-aarch64-server-release' (exit code 2)

=== Output from failing command(s) repeated here ===
* For target jdk__optimize_image_exec:
java.lang.module.FindException: Module jdk.attach not found, required by jdk.jconsole

* All command lines available in /Users/theresamammarella/openj9builds/openj9-openjdk-jdk/build/macosx-aarch64-server-release/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
HELP: Try searching the build log for '] Error'.
HELP: Run 'make doctor' to diagnose build problems.

make[1]: *** [main] Error 2
make: *** [all] Error 2
```

**Comment by keithc-ca** [comment]
There should be more detail about this failure, either in `make-support/failure-logs/*.log` or in `build.log`.

**Comment by theresa-m** [comment]
They don't have more information in this case.

**Comment by theresa-m** [comment]
The recent failure
```
java.lang.NullPointerException: Cannot load from object array because "oldTab" is null
Runtime.exit(1) logging failed: Cannot invoke "java.lang.Module.getClassLoader()" because "this.val$m" is null
```
passes when `-Xint` is applied. Can someone from the JIT team take a look?

**Comment by keithc-ca** [comment]
https://github.com/eclipse/omr/pull/7148 has been merged and my "dwarf_tag" branch has been deleted.

**Comment by hzongaro** [comment]
> The recent failure
> 
> java.lang.NullPointerException: Cannot load from object array because "oldTab" is null
> Runtime.exit(1) logging failed: Cannot invoke "java.lang.Module.getClassLoader()" because "this.val$m" is null
> 
> passes when -Xint is applied. Can someone from the JIT team take a look?

@jmesyou, may I ask you to do an initial triage of this?

**Comment by knn-k** [comment]
I can build both Java 11 and 17 with `OPENJ9_JAVA_OPTIONS="-Xjit:optLevel=cold" make all`.

**Comment by knn-k** [comment]
This issue may be related to the macOS ABI change described in https://github.com/eclipse-openj9/openj9/issues/18336#issuecomment-1776608320.
It can explain why `disableGRA` works -- The JIT assigns the `x18` register less often when `disableGRA` is specified on AArch64.

**Comment by knn-k** [comment]
Just to make sure.
@theresa-m Which version of macOS do you use?
I think it is macOS 13.x because Xcode 14.3.1 requires macOS 13 according to this page: https://developer.apple.com/support/xcode/

**Comment by knn-k** [comment]
@theresa-m Please try applying PR #18351.

**Comment by theresa-m** [comment]
I am on 14.0 now, although was updated recently.

Thanks! I'll try it out this morning.

**Comment by theresa-m** [comment]
Thanks again @knn-k my build passes now with your pull request using XCode 14.3.1

Now to update to 15.0.1 and cross my fingers...

**Comment by theresa-m** [comment]
building with Xcode 15.0.1 (the latest version) is working too. I will close this issue once https://github.com/eclipse-openj9/openj9/pull/18351 is merged

**Comment by theresa-m** [comment]
This issue has been resolved, OpenJ9 now builds with Xcode 15.
