### ISSUE TITLE
java/lang/Thread/virtual/stress/YieldALot timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17499]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_s390x_linux_OMR/15/
jdk_lang_j9_0 
java/lang/Thread/virtual/stress/YieldALot.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk20_j9_sanity.openjdk_s390x_linux_OMR/15/openjdk_test_output.tar.gz
```
09:40:34  Timeout information:
09:40:34  Running jcmd on process 211938
09:40:34  Dump written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_OMR/aqa-tests/TKG/output_16855339803484/jdk_lang_j9_0/work/scratch/0/core.20230531.133957.211938.0001.dmp
09:40:34  Dump written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_OMR/aqa-tests/TKG/output_16855339803484/jdk_lang_j9_0/work/scratch/0/javacore.20230531.134017.211938.0002.txt
09:40:34  Running jstack on process 211938
09:40:34  2023-05-31T13:40:18.236446047
09:40:34  Virtual machine: 211938 JVM information:
09:40:34  JRE 20 Linux s390x-64-Bit 20230531_29 (JIT enabled, AOT enabled)
09:40:34  OpenJ9   - f98cb3128b0
09:40:34  OMR      - 154735ca437
09:40:34  JCL      - a80d1107c64 based on jdk-20.0.1+9
09:40:34  
09:40:34  "main" prio=5 Id=2 WAITING
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.waitImpl(Native Method)
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.wait(Object.java:255)
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.wait(Object.java:221)
09:40:34  	at java.base@20.0.1-internal/java.lang.Thread.join(Thread.java:2147)
09:40:34  	at java.base@20.0.1-internal/java.lang.Thread.join(Thread.java:2223)
09:40:34  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:72)
09:40:34  
09:40:34  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
09:40:34  
09:40:34  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
09:40:34  
09:40:34  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
09:40:34  
09:40:34  "JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
09:40:34  
09:40:34  "JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE
09:40:34  
09:40:34  "JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE
09:40:34  
09:40:34  "JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE
09:40:34  
09:40:34  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE
09:40:34  
09:40:34  "JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING
09:40:34  
09:40:34  "IProfiler" prio=5 Id=13 RUNNABLE
09:40:34  
09:40:34  "Common-Cleaner" prio=8 Id=3 TIMED_WAITING
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.waitImpl(Native Method)
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.wait(Object.java:255)
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.wait(Object.java:221)
09:40:34  	at java.base@20.0.1-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
09:40:34  	at java.base@20.0.1-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
09:40:34  	at java.base@20.0.1-internal/java.lang.Thread.run(Thread.java:1639)
09:40:34  	at java.base@20.0.1-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
09:40:34  
09:40:34  "Dedicated GC Main" prio=5 Id=14 RUNNABLE
09:40:34  
09:40:34  "GC Worker" prio=5 Id=15 RUNNABLE
09:40:34  
09:40:34  "GC Worker" prio=5 Id=16 RUNNABLE
09:40:34  
09:40:34  "GC Worker" prio=5 Id=17 RUNNABLE
09:40:34  
09:40:34  "MainThread" prio=5 Id=21 TIMED_WAITING
09:40:34  	at java.base@20.0.1-internal/jdk.internal.misc.Unsafe.park(Native Method)
09:40:34  	at java.base@20.0.1-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
09:40:34  	at java.base@20.0.1-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:756)
09:40:34  	at java.base@20.0.1-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1126)
09:40:34  	at java.base@20.0.1-internal/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
09:40:34  	at java.base@20.0.1-internal/java.lang.VirtualThread.joinNanos(VirtualThread.java:816)
09:40:34  	at java.base@20.0.1-internal/java.lang.Thread.join(Thread.java:2261)
09:40:34  	at app//YieldALot.main(YieldALot.java:61)
09:40:34  	at java.base@20.0.1-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
09:40:34  	at java.base@20.0.1-internal/java.lang.reflect.Method.invoke(Method.java:578)
09:40:34  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
09:40:34  	at java.base@20.0.1-internal/java.lang.Thread.run(Thread.java:1639)
09:40:34  
09:40:34  "Attach API wait loop" prio=10 Id=22 RUNNABLE
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
09:40:34  
09:40:34  "Finalizer thread" prio=5 Id=28 RUNNABLE
09:40:34  
09:40:34  "file lock watchdog" prio=10 Id=30 TIMED_WAITING
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.waitImpl(Native Method)
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.wait(Object.java:255)
09:40:34  	at java.base@20.0.1-internal/java.lang.Object.wait(Object.java:221)
09:40:34  	at java.base@20.0.1-internal/java.util.TimerThread.mainLoop(Timer.java:599)
09:40:34  	at java.base@20.0.1-internal/java.util.TimerThread.run(Timer.java:542)
09:40:34  
09:40:34  "Attachment portNumber: 46291" prio=10 Id=32 RUNNABLE
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
09:40:34  	at java.base@20.0.1-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
09:40:34  
09:40:34  
09:40:34  --- Timeout information end.
```

**Comment by pshipton** [comment]
Possible dup of https://github.com/eclipse-openj9/openj9/issues/17255

**Comment by r30shah** [comment]
This is definitely a dup of the https://github.com/eclipse-openj9/openj9/issues/17255 as I can get it failed with limiting the JIT compilation to the method that caused the failure in 17255. With the potential fix that I have summarized in https://github.com/eclipse-openj9/openj9/issues/17255#issuecomment-1573104086, the test passes 100% (20/20 so far).

**Comment by pshipton** [comment]
Closing as a dup.
