### ISSUE TITLE
JDK20 jdk_foreign_0_FAILED java/foreign/TestLargeSegmentCopy.java OutOfMemoryError: native memory exhausted

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17506]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.openjdk_s390x_linux_testList_0/36/)(`ub18s390xrt-1-5`):
```
openjdk version "20.0.1-beta" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1+9-202305310828 (build 20.0.1-beta+9-202305310828)
Eclipse OpenJ9 VM 20.0.1+9-202305310828 (build master-f98cb3128, JRE 20 Linux s390x-64-Bit Compressed References 20230531_38 (JIT enabled, AOT enabled)
OpenJ9   - f98cb3128
OMR      - f89af3519
JCL      - a80d1107c based on jdk-20.0.1+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_foreign_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk20_j9_sanity.openjdk_s390x_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-linux-s390x-openj9%2F38%2Fibm-semeru-open-jdk_s390x_linux_JDK20U_2023-05-31-08-23.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-linux-s390x-openj9%2F38%2Fibm-semeru-open-testimage_s390x_linux_JDK20U_2023-05-31-08-23.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=20&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk20&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=36&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-31T10:38:18.715Z] variation: Mode150
[2023-05-31T10:38:18.715Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-05-31T10:40:56.227Z] TEST: java/foreign/TestLargeSegmentCopy.java

[2023-05-31T10:40:56.227Z] STDOUT:
[2023-05-31T10:40:56.227Z] test TestLargeSegmentCopy.testLargeSegmentCopy(): failure
[2023-05-31T10:40:56.227Z] java.lang.OutOfMemoryError: native memory exhausted
[2023-05-31T10:40:56.227Z] 	at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unsafe.java:1280)
[2023-05-31T10:40:56.227Z] 	at java.base/jdk.internal.foreign.NativeMemorySegmentImpl.makeNativeSegment(NativeMemorySegmentImpl.java:116)
[2023-05-31T10:40:56.227Z] 	at java.base/java.lang.foreign.MemorySegment.allocateNative(MemorySegment.java:1251)
[2023-05-31T10:40:56.227Z] 	at TestLargeSegmentCopy.testLargeSegmentCopy(TestLargeSegmentCopy.java:49)
[2023-05-31T10:40:56.227Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-05-31T10:40:56.227Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2023-05-31T10:40:56.227Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2023-05-31T10:40:56.227Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2023-05-31T10:40:56.227Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2023-05-31T10:40:56.227Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2023-05-31T10:40:56.227Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2023-05-31T10:40:56.227Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2023-05-31T10:40:56.227Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2023-05-31T10:40:56.227Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2023-05-31T10:40:56.227Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2023-05-31T10:40:56.227Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2023-05-31T10:40:56.227Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2023-05-31T10:40:56.227Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2023-05-31T10:40:56.227Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2023-05-31T10:40:56.227Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2023-05-31T10:40:56.227Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
[2023-05-31T10:40:56.227Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
[2023-05-31T10:40:56.227Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-05-31T10:40:56.227Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-05-31T10:40:56.227Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-05-31T10:40:56.227Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-05-31T10:40:56.227Z] 
[2023-05-31T10:40:56.227Z] ===============================================
[2023-05-31T10:40:56.227Z] java/foreign/TestLargeSegmentCopy.java
[2023-05-31T10:40:56.227Z] Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
[2023-05-31T10:40:56.227Z] ===============================================
[2023-05-31T10:40:56.227Z] 
[2023-05-31T10:40:56.227Z] STDERR:
[2023-05-31T10:40:56.227Z] JVMDUMP055I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError", exception "native memory exhausted" at 2023/05/31 03:39:52 - please wait.

[2023-05-31T10:43:37.542Z] Test results: passed: 67; failed: 1
[2023-05-31T10:44:27.472Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_16855261297928/jdk_foreign_0/report/html/report.html
[2023-05-31T10:44:27.473Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_16855261297928/jdk_foreign_0/work
[2023-05-31T10:44:27.473Z] Error: Some tests failed or other problems occurred.
[2023-05-31T10:44:27.473Z] -----------------------------------
[2023-05-31T10:44:27.473Z] jdk_foreign_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33158/)

**Comment by pshipton** [comment]
Grinder passed on rhel7s390x-3-6, rhel8s390x-svl-rt4-1
Passed on svlxtor3, ubu20s390x-svl-rt2-1 with a different failure (java/foreign/LibraryLookupTest.java - opened https://github.com/eclipse-openj9/openj9/issues/17524)
Failed 10/10 on ub18s390xrt-1-3. Looking at this machine it doesn't have much memory, < 4GB.
Looking at ub18s390xrt-1-5, it's also described as having 4MB. For comparision, ubu20s390x-svl-rt2-1, rhel7s390x-3-6 have ~8GB, while svlxtor3 has ~16GB. I believe this failure is a machine issue. Closing as an internal problem (opened infra 8053).
```
              total        used        free      shared  buff/cache   available
Mem:        3912712      166276     3592648          32      153788     3659144
Swap:        998396      121732      876664
```
