### ISSUE TITLE
OpenJDK java/util/concurrent/BlockingQueue/OfferDrainToLoops Hung thread: offerer

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17523]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/539
jdk_util_0
java/util/concurrent/BlockingQueue/OfferDrainToLoops.java

```
23:20:17  STDOUT:
23:20:17  LinkedBlockingQueue
23:20:17  LinkedBlockingQueue
23:20:17  LinkedBlockingDeque
23:20:17  LinkedBlockingDeque
23:20:17  ArrayBlockingQueue
23:20:17  LinkedTransferQueue
23:20:17  
23:20:17  Passed = 576791, failed = 1
23:20:17  
23:20:17  STDERR:
23:20:17  Hung thread: offerer
23:20:17  OfferDrainToLoops$1.realRun(OfferDrainToLoops.java:116)
23:20:17  OfferDrainToLoops$1CheckedThread.run(OfferDrainToLoops.java:104)
23:20:17  java.lang.AssertionError: Some tests failed
23:20:17  	at OfferDrainToLoops.instanceMain(OfferDrainToLoops.java:184)
23:20:17  	at OfferDrainToLoops.main(OfferDrainToLoops.java:180)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/340

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/189

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_OMR_testList_3/70
