### ISSUE TITLE
jdk_security_infra_0_FAILED RuntimeException: TEST FAILED: unexpected status of EE certificate

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17552]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/113/)(`ubu20-aarch64-1`):
```
openjdk version "17.0.8" 2023-07-18
IBM Semeru Runtime Open Edition 17.0.8.0-m1 (build 17.0.8+5)
Eclipse OpenJ9 VM 17.0.8.0-m1 (build v0.40.0-release-b9cd65edd, JRE 17 Linux aarch64-64-Bit Compressed References 20230718_458 (JIT enabled, AOT enabled)
OpenJ9   - b9cd65edd
OMR      - 0e572348b
JCL      - 037408d4b91 based on jdk-17.0.8+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security_infra_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F458%2Fibm-semeru-open-jdk_aarch64_linux_17.0.8_5_openj9-0.40.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F458%2Fibm-semeru-open-testimage_aarch64_linux_17.0.8_5_openj9-0.40.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.40.0-release&amp;OPENJ9_BRANCH=v0.40.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.40.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-06-06T19:29:44.549Z] variation: Mode150
[2023-06-06T19:29:44.549Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-06-06T19:30:04.959Z] TEST: security/infra/java/security/cert/CertPathValidator/certification/AmazonCA.java

[2023-06-06T19:30:04.962Z] java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate
[2023-06-06T19:30:04.962Z] 	at ValidatePathWithParams.validate(ValidatePathWithParams.java:193)
[2023-06-06T19:30:04.962Z] 	at AmazonCA_1.runTest(AmazonCA.java:173)
[2023-06-06T19:30:04.962Z] 	at AmazonCA.main(AmazonCA.java:64)
[2023-06-06T19:30:04.962Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-06-06T19:30:04.962Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-06-06T19:30:04.962Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-06-06T19:30:04.962Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-06-06T19:30:04.962Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-06-06T19:30:04.962Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-06-06T19:30:04.962Z] 
[2023-06-06T19:30:04.962Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate

[2023-06-06T19:30:04.962Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate
[2023-06-06T19:30:04.962Z] --------------------------------------------------
[2023-06-06T19:30:40.614Z] Test results: passed: 14; failed: 1
[2023-06-06T19:30:59.364Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16860687733463/jdk_security_infra_0/report/html/report.html
[2023-06-06T19:30:59.364Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16860687733463/jdk_security_infra_0/work
[2023-06-06T19:30:59.364Z] Error: Some tests failed or other problems occurred.
[2023-06-06T19:30:59.364Z] -----------------------------------
[2023-06-06T19:30:59.364Z] jdk_security_infra_0_FAILED
```
[JDK17 hotspot](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33228/)

**Comment by llxia** [comment]
Same issue at Adoptium https://github.com/adoptium/aqa-tests/issues/4680#issuecomment-1644550667
