### ISSUE TITLE
MiniMix_3h -Xgcpolicy:balanced ArrayIndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17575]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_special.system_ppc64_aix_Personal_testList_3/62
MiniMix_3h_0 `-XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced`

```
LT  19:23:36.914 - Completed 31.9%. Number of tests started=921088 (+8896)
LT  19:23:50.315 - Uncaught exception: 
LT  java.lang.ArrayIndexOutOfBoundsException: null
LT  	at net.adoptopenjdk.test.nio2.util.MessageHeader.parse(MessageHeader.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.util.ReceivingMessage.parseAndSetHeader(ReceivingMessage.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.parseBuffer(EchoServer.java:357) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:295) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:275) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:555) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298) ~[?:1.8.0_382-internal]
LT  	at java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:420) ~[?:1.8.0_382-internal]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:198) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:156) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invoke(Invoker.java:185) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.onEvent(UnixAsynchronousServerSocketChannelImpl.java:193) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AixPollPort$EventHandlerTask.run(AixPollPort.java:455) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:1.8.0_382-internal]
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382-internal]
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382-internal]
LT  	at java.lang.Thread.run(Thread.java:826) [?:1.8.0_382-internal]
```

```
LT  20:02:36.967 - Completed 53.5%. Number of tests started=1537993 (+4813)
LT  20:02:53.296 - Uncaught exception: 
LT  java.lang.ArrayIndexOutOfBoundsException: null
LT  	at net.adoptopenjdk.test.nio2.util.MessageHeader.parse(MessageHeader.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.util.ReceivingMessage.parseAndSetHeader(ReceivingMessage.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.parseBuffer(EchoServer.java:357) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:295) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:275) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:555) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298) ~[?:1.8.0_382-internal]
LT  	at java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:420) ~[?:1.8.0_382-internal]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:198) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:156) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invoke(Invoker.java:185) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.onEvent(UnixAsynchronousServerSocketChannelImpl.java:193) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AixPollPort$EventHandlerTask.run(AixPollPort.java:455) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:1.8.0_382-internal]
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382-internal]
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382-internal]
LT  	at java.lang.Thread.run(Thread.java:826) [?:1.8.0_382-internal]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_special.system_ppc64_aix_Release_testList_3/54 - [p8-java1-ibm12](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm12)
MiniMix_3h_0 `-XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced`
```
LT  08:06:26.131 - Completed 31.9%. Number of tests started=875452 (+7302)
LT  08:06:33.679 - Uncaught exception: 
LT  java.lang.ArrayIndexOutOfBoundsException: null
LT  	at net.adoptopenjdk.test.nio2.util.MessageHeader.parse(MessageHeader.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.util.ReceivingMessage.parseAndSetHeader(ReceivingMessage.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.parseBuffer(EchoServer.java:357) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:295) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:275) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:555) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298) ~[?:1.8.0_382-internal]
LT  	at java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:420) ~[?:1.8.0_382-internal]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:198) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:156) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.Invoker.invoke(Invoker.java:185) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.onEvent(UnixAsynchronousServerSocketChannelImpl.java:193) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AixPollPort$EventHandlerTask.run(AixPollPort.java:455) ~[?:1.8.0_382-internal]
LT  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:1.8.0_382-internal]
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382-internal]
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382-internal]
LT  	at java.lang.Thread.run(Thread.java:826) [?:1.8.0_382-internal]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_special.system_ppc64_aix_Personal_testList_4/8/
MiniMix_3h_0
```
LT  java.lang.ArrayIndexOutOfBoundsException: null
LT  	at net.adoptopenjdk.test.nio2.util.MessageHeader.parse(MessageHeader.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.util.ReceivingMessage.parseAndSetHeader(ReceivingMessage.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.parseBuffer(EchoServer.java:357) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:295) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:275) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:160) ~[?:?]
LT  	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:573) ~[?:?]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277) ~[?:?]
LT  	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298) ~[?:?]
LT  	at java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425) ~[?:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:198) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:156) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
LT  	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:160) ~[?:?]
LT  	at sun.nio.ch.Invoker.invoke(Invoker.java:188) ~[?:?]
LT  	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.onEvent(UnixAsynchronousServerSocketChannelImpl.java:194) ~[?:?]
LT  	at sun.nio.ch.AixPollPort$EventHandlerTask.run(AixPollPort.java:437) ~[?:?]
LT  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113) ~[?:?]
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
LT  	at java.lang.Thread.run(Thread.java:1595) [?:?]
```

**Comment by pshipton** [comment]
Try to capture a core file on failure. The test is a 3 hour runs.
https://openj9-jenkins.osuosl.org/job/Grinder/2843/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_ppc64_aix_Release_testList_4/67
MiniMix_3h_0
```
LT  12:58:45.102 - Completed 85.0%. Number of tests started=2390242 (+3757)
LT  12:58:56.644 - Uncaught exception: 
LT  java.lang.ArrayIndexOutOfBoundsException: null
LT  	at net.adoptopenjdk.test.nio2.util.MessageHeader.parse(MessageHeader.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.util.ReceivingMessage.parseAndSetHeader(ReceivingMessage.java:42) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.parseBuffer(EchoServer.java:357) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:295) ~[bin/:?]
LT  	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:275) ~[bin/:?]
LT  	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
LT  	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:447) ~[?:?]
LT  	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:195) ~[?:?]
LT  	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217) ~[?:?]
LT  	at sun.nio.ch.AixPollPort$EventHandlerTask.run(AixPollPort.java:455) ~[?:?]
LT  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113) ~[?:?]
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
LT  	at java.lang.Thread.run(Thread.java:857) [?:?]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_special.system_ppc64_aix_Release_testList_4/77

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_special.system_ppc64_aix_Personal_testList_3/144

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_special.system_ppc64_aix_Personal_testList_3/157

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly_testList_1/1097
MiniMix_10m_1

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly_testList_2/1097
DBBLoadTest_5m_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/1167
MiniMix_extended_3h_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_extended.system_s390x_linux_Nightly_testList_0/64
MiniMix_extended_3h_0
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_extended.system_s390x_linux_Nightly_testList_2/64
MiniMix_extended_3h_1

**Comment by dmitripivkine** [comment]
@r30shah @VermaSh FYI This problem stopped happen after May and now failing in s390. We do not have system core and it is very hard to reproduce.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_ppc64_aix_Nightly_testList_0/1159
MiniMix_extended_3h_0 `-Xjit -Xgcpolicy:balanced -Xnocompressedrefs`
```
04:14:04.616 - Uncaught exception: 
java.lang.ArrayIndexOutOfBoundsException: null
	at net.adoptopenjdk.test.nio2.util.MessageHeader.parse(MessageHeader.java:42) ~[bin/:?]
	at net.adoptopenjdk.test.nio2.util.ReceivingMessage.parseAndSetHeader(ReceivingMessage.java:42) ~[bin/:?]
	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.parseBuffer(EchoServer.java:357) ~[bin/:?]
	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:295) ~[bin/:?]
	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$ServerReadCompletionHandler.completed(EchoServer.java:275) ~[bin/:?]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:160) ~[?:?]
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:573) ~[?:?]
	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276) ~[?:?]
	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297) ~[?:?]
	at java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425) ~[?:?]
	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:198) ~[bin/:?]
	at net.adoptopenjdk.test.nio2.asyncio.server.EchoServer$1.completed(EchoServer.java:156) ~[bin/:?]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:160) ~[?:?]
	at sun.nio.ch.Invoker.invoke(Invoker.java:188) ~[?:?]
	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.onEvent(UnixAsynchronousServerSocketChannelImpl.java:194) ~[?:?]
	at sun.nio.ch.AixPollPort$EventHandlerTask.run(AixPollPort.java:455) ~[?:?]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:854) [?:?]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_special.system_ppc64_aix_Personal_testList_3/130
MiniMix_3h_1 `-Xjit -Xgcpolicy:gencon -Xnocompressedrefs -Xgc:concurrentScavenge`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_special.system_s390x_linux_Personal_testList_4/27
MiniMix_3h_0 `-XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced `
```
00:12:27  LT  java.lang.ArrayIndexOutOfBoundsException: null
00:12:27  LT  	at net.adoptopenjdk.test.nio2.util.MessageHeader.parse(MessageHeader.java:42) ~[bin/:?]
00:12:27  LT  	at net.adoptopenjdk.test.nio2.util.ReceivingMessage.parseAndSetHeader(ReceivingMessage.java:42) ~[bin/:?]
```

**Comment by pshipton** [comment]
https://trssrtp1.fyre.ibm.com/output/test?id=69edb1a0329d7c83d7c9ce9b
```
Test_openjdk11_j9_special.system_s390x_linux #1156
Test_openjdk11_j9_special.system_s390x_linux_testList_1 #11315
```
MiniMix_3h_0

**Comment by pshipton** [comment]
https://trssrtp1.fyre.ibm.com/output/test?id=69ef801a329d7c83d7da4b95
```
Test_openjdk8_j9_special.system_x86-64_linux #1206
Test_openjdk8_j9_special.system_x86-64_linux_testList_0 #1169
```
MiniMix_3h_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_ppc64_aix_Nightly_testList_0/1189
MiniMix_extended_3h_0
-Xjit -Xgcpolicy:balanced -Xnocompressedrefs

**Comment by pshipton** [comment]
```
				String[] keyValue = parts[index].split(":", 2);
				if (keyValue.length != 2) {
					System.err.println("Malformed header line - '" + parts[index] + "'");
				}
				map.put(keyValue[0], keyValue[1]);  <---- line 42
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.system_ppc64_aix_Nightly_testList_3/5

I got the debugging wrong, created https://github.com/adoptium/aqa-systemtest/pull/512

**Comment by keithc-ca** [comment]
The code quoted above should have an `else` (or `continue`) to avoid invalid indexing:
```java
				String[] keyValue = parts[index].split(":", 2);
				if (keyValue.length != 2) {
					System.err.println("Malformed header line - '" + parts[index] + "'");
				} else {
					map.put(keyValue[0], keyValue[1]);
				}
```

**Comment by pshipton** [comment]
I expect it's better to get the exception and have the test fail. The weird thing is there is no "Malformed header line" printed to stderr, yet we get an ArrayIndexOutOfBoundsException running `map.put(keyValue[0], keyValue[1]);`, which is likely a JIT bug. Hopefully the debugging I added in https://github.com/adoptium/aqa-systemtest/pull/512 will provide more info, or I will update it again.

**Comment by keithc-ca** [comment]
Yes, I was also puzzled by the absence of the "Malformed header" message.

Once we understand the root of this issue, the code should probably be fixed. It's not reasonable, in my opinion, to check the length of the array, but not avoid out-of-bounds index use.

**Comment by pshipton** [comment]
I'd have to check the history, but it may be a prior attempt at debugging.

**Comment by keithc-ca** [comment]
That's the way it's always been (at least since 2017-09-11 when the code was first committed).

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_ppc64_aix_Personal_testList_3/220
`java.lang.ArrayIndexOutOfBoundsException: parts[0] '\0\0\0@^B^C' split length 1`

The message is not readable text, in hex: "00 00 00 40 02 03", and isn't split since there is no colon.

**Comment by keithc-ca** [comment]
There's also no `Malformed header line` that should appear when there's no colon. Perhaps JIT is misbehaving?

**Comment by pshipton** [comment]
The stderr output is completely empty, and the stack trace shows up in stdout. I'm not ready to blame JIT for the missing message, I suspect there are multiple processes involved and stderr isn't captured to the file. I created a new PR to print the entire headerString for the next occurrence.

**Comment by keithc-ca** [comment]
Normally stack traces are sent to stderr, so if we see the stack trace, I would assume we're looking at stderr, so we should also see `System.err.println(...)`.

**Comment by keithc-ca** [comment]
The tests log says:
```
[2026-05-24T21:51:38.441Z] STF 21:47:28.169 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk17_j9_special.system_ppc64_aix_Personal_testList_3/aqa-tests/TKG/output_17796509607297/MiniMix_3h_1/20260524-214723-MixedLoadTest/results/1.LT.stderr
[2026-05-24T21:51:38.441Z] STF 21:47:28.169 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk17_j9_special.system_ppc64_aix_Personal_testList_3/aqa-tests/TKG/output_17796509607297/MiniMix_3h_1/20260524-214723-MixedLoadTest/results/1.LT.stdout
```
Are those files available?

**Comment by pshipton** [comment]
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_special.system_ppc64_aix_Personal_testList_3/220/system_test_output.tar.gz

look in `aqa-tests\TKG\output_17796509607297\MiniMix_3h_1\20260524-214723-MixedLoadTest\results\`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.system_ppc64_aix_Nightly_testList_3/20

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_extended.system_ppc64_aix_Nightly_testList_3/20/system_test_output.tar.gz

```
20:56:54  LT  java.lang.ArrayIndexOutOfBoundsException: parts[0] '@' split length 1 [0] '@' header '@
20:56:54  LT  
20:56:54  LT  '
```

**Comment by pshipton** [comment]
I don't see any "Malformed header line" output, but I didn't expect to. I doubt that indicates a JIT issue, I'm guessing it would be explained if we dig more into how the test works with the multiple processes. More interesting to me is where the malformed header content comes from. We'll have to figure out what is the next step for debugging that.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_extended.system_ppc64_aix_Nightly_testList_3/19
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_extended.system_ppc64_aix_Release_testList_3/1
