### ISSUE TITLE
OpenJDK java/security/Signature/TestCloneable NoSuchAlgorithmException: no such algorithm: EdDSA for provider SunEC

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17579]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/569/
All platforms
java/security/Signature/TestCloneable.java
```
00:09:14  Testing EdDSA impl from SunECtest TestCloneable.test("EdDSA", "SunEC"): failure
00:09:14  java.security.NoSuchAlgorithmException: no such algorithm: EdDSA for provider SunEC
00:09:14  	at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:87)
00:09:14  	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
00:09:14  	at java.base/java.security.Signature.getInstance(Signature.java:404)
00:09:14  	at TestCloneable.test(TestCloneable.java:78)
```
```
00:09:14  Testing Ed25519 impl from SunECtest TestCloneable.test("Ed25519", "SunEC"): failure
00:09:14  java.security.NoSuchAlgorithmException: no such algorithm: Ed25519 for provider SunEC
00:09:14  	at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:87)
00:09:14  	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
00:09:14  	at java.base/java.security.Signature.getInstance(Signature.java:404)
00:09:14  	at TestCloneable.test(TestCloneable.java:78)
```
```
00:09:14  Testing Ed448 impl from SunECtest TestCloneable.test("Ed448", "SunEC"): failure
00:09:14  java.security.NoSuchAlgorithmException: no such algorithm: Ed448 for provider SunEC
00:09:14  	at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:87)
00:09:14  	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
00:09:14  	at java.base/java.security.Signature.getInstance(Signature.java:404)
00:09:14  	at TestCloneable.test(TestCloneable.java:78)
```

**Comment by pshipton** [comment]
This must be caused by https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/667
@keithc-ca pls help sort this.

**Comment by keithc-ca** [comment]
I expect that these algorithms should have been excluded as the test was back-ported; they are provided in jdk17, but not in jdk11:
```java
                    if (algo.equalsIgnoreCase("EdDSA")) {
                        return new EdDSASignature();
                    } else if (algo.equalsIgnoreCase("Ed25519")) {
                        return new EdDSASignature.Ed25519();
                    } else if (algo.equalsIgnoreCase("Ed448")) {
                        return new EdDSASignature.Ed448();
                    }
```
See [jdk17/SunEC.java](https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9/src/jdk.crypto.ec/share/classes/sun/security/ec/SunEC.java#L125-L131).

**Comment by keithc-ca** [comment]
See also https://bugs.openjdk.org/browse/JDK-8166597.
