### ISSUE TITLE
jdk_container_0_FAILED jdk/internal/platform/docker/TestDockerMemoryMetrics.java exitValue = 137

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17585]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_dev.openjdk_aarch64_linux/3/)(`cent7-aarch64-3`):
```
openjdk version "11.0.20" 2023-07-18
IBM Semeru Runtime Open Edition 11.0.20.0-m1 (build 11.0.20+5)
Eclipse OpenJ9 VM 11.0.20.0-m1 (build v0.40.0-release-936ec5450, JRE 11 Linux aarch64-64-Bit Compressed References 20230607_706 (JIT enabled, AOT enabled)
OpenJ9   - 936ec5450
OMR      - 0e572348b
JCL      - 3dcd507cc6 based on jdk-11.0.20+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F706%2Fibm-semeru-open-jdk_aarch64_linux_11.0.20_5_openj9-0.40.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F706%2Fibm-semeru-open-testimage_aarch64_linux_11.0.20_5_openj9-0.40.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.40.0-release&amp;OPENJ9_BRANCH=v0.40.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.40.0-release&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-06-07T22:00:49.072Z] variation: NoOptions
[2023-06-07T22:00:49.072Z] JVM_OPTIONS:  

[2023-06-07T22:02:13.616Z] TEST: jdk/internal/platform/docker/TestDockerMemoryMetrics.java

[2023-06-07T22:02:13.618Z] STDERR:
[2023-06-07T22:02:13.618Z]  stdout: [[failcount]
[2023-06-07T22:02:13.618Z] ];
[2023-06-07T22:02:13.618Z]  stderr: []
[2023-06-07T22:02:13.618Z]  exitValue = 137
[2023-06-07T22:02:13.618Z] 
[2023-06-07T22:02:13.618Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2023-06-07T22:02:13.618Z] 
[2023-06-07T22:02:13.618Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2023-06-07T22:02:13.618Z] 	at TestDockerMemoryMetrics.testMemoryFailCount(TestDockerMemoryMetrics.java:119)
[2023-06-07T22:02:13.618Z] 	at TestDockerMemoryMetrics.main(TestDockerMemoryMetrics.java:78)
[2023-06-07T22:02:13.618Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-06-07T22:02:13.618Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-06-07T22:02:13.618Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-06-07T22:02:13.618Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-06-07T22:02:13.618Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-06-07T22:02:13.618Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-06-07T22:02:13.618Z] 
[2023-06-07T22:02:13.618Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2023-06-07T22:02:13.618Z] JavaTest Message: shutting down test
[2023-06-07T22:02:13.618Z] 
[2023-06-07T22:02:13.618Z] 
[2023-06-07T22:02:13.618Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
[2023-06-07T22:02:13.618Z] --------------------------------------------------
[2023-06-07T22:02:25.588Z] Test results: passed: 10; failed: 1
[2023-06-07T22:02:42.998Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_16861752482775/jdk_container_0/report/html/report.html
[2023-06-07T22:02:42.998Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_16861752482775/jdk_container_0/work
[2023-06-07T22:02:42.998Z] Error: Some tests failed or other problems occurred.
[2023-06-07T22:02:42.998Z] -----------------------------------
[2023-06-07T22:02:42.998Z] jdk_container_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33389/)

**Comment by pshipton** [comment]
@llxia pls check if there is a machine problem and if so ensure there is an infra issue created to fix it.

**Comment by pshipton** [comment]
Perhaps related to https://github.com/eclipse-openj9/openj9/issues/16460

**Comment by JasonFengJ9** [comment]
> Perhaps related to https://github.com/eclipse-openj9/openj9/issues/16460

They are the same test, this one has `exitValue = 137`, and the other was `RuntimeException: Kernel Memory limit not equal, expected : [104857600], got : [-1]`.

**Comment by llxia** [comment]
For jdk_container, I am not aware of any special machine requirement other than docker. And both two failed machines have `sw.tool.docker` label.

@sophia-guo do you have any insights?

**Comment by JasonFengJ9** [comment]
[JDK22 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_dev.openjdk_aarch64_linux/3/)(`cent7-aarch64-4`)
```
[2024-03-02T21:16:16.121Z] Full child process STDOUT was saved to docker-stdout-1566.log
[2024-03-02T21:16:16.121Z] STDERR:
[2024-03-02T21:16:16.121Z]  stdout: [[failcount]
[2024-03-02T21:16:16.121Z] ];
[2024-03-02T21:16:16.121Z]  stderr: []
[2024-03-02T21:16:16.121Z]  exitValue = 137
[2024-03-02T21:16:16.121Z] 
[2024-03-02T21:16:16.121Z] java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [137]
[2024-03-02T21:16:16.121Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:513)
[2024-03-02T21:16:16.121Z] 	at TestDockerMemoryMetrics.testMemoryFailCount(TestDockerMemoryMetrics.java:142)
[2024-03-02T21:16:16.121Z] 	at TestDockerMemoryMetrics.main(TestDockerMemoryMetrics.java:78)
[2024-03-02T21:16:16.121Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-02T21:16:16.121Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-02T21:16:16.121Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-03-02T21:16:16.121Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-03-02T21:16:16.121Z] 
[2024-03-02T21:16:16.121Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2024-03-02T21:16:16.121Z] JavaTest Message: shutting down test
[2024-03-02T21:16:16.121Z] 
[2024-03-02T21:16:16.121Z] 
[2024-03-02T21:16:16.121Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [137]
[2024-03-02T21:16:16.121Z] --------------------------------------------------
[2024-03-02T21:16:49.477Z] Test results: passed: 11; failed: 1
[2024-03-02T21:17:23.984Z] Report written to /home/jenkins/workspace/Test_openjdk22_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_1709414018343/jdk_container_0/report/html/report.html
[2024-03-02T21:17:23.984Z] Results written to /home/jenkins/workspace/Test_openjdk22_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_1709414018343/jdk_container_0/work
[2024-03-02T21:17:23.984Z] Error: Some tests failed or other problems occurred.
[2024-03-02T21:17:23.984Z] -----------------------------------
[2024-03-02T21:17:23.984Z] jdk_container_0_FAILED
```
