### ISSUE TITLE
OpenJDK java/security/MessageDigest/TestDigestIOStream OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17591]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_OMR/24
jdk_security1_1
java/security/MessageDigest/TestDigestIOStream.java

Failed to capture diagnostics.
```
06:27:42  java.lang.OutOfMemoryError: Java heap space
06:27:42  	at java.base/java.util.Arrays.copyOf(Arrays.java:3776)
06:27:42  	at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
06:27:42  	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
06:27:42  	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:137)
06:27:42  	at java.base/java.security.DigestOutputStream.write(DigestOutputStream.java:116)
06:27:42  	at TestDigestIOStream.testDigestOnOff(TestDigestIOStream.java:172)
06:27:42  	at TestDigestIOStream.run(TestDigestIOStream.java:89)
06:27:42  	at TestDigestIOStream.main(TestDigestIOStream.java:66)
```

**Comment by keithc-ca** [comment]
Has this been seen on any other platform or version? The only explanations I can think of are that `ByteArrayInputStream.read()` never returns `-1` or the heap is unreasonably small (the largest part of the test reads and write 6250000 bytes).

**Comment by pshipton** [comment]
Not see more than once. If I see it again then I'll add a new comment with the details.
