### ISSUE TITLE
cmdLineTester_criu_nonPortableRestore TestSingleThreadModeRestoreException  JVMRestoreException: Blocking operation is not allowed in CRIU single thread mode

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17599]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/558
cmdLineTester_criu_nonPortableRestore_0

```
Testing: Create and Restore Criu Checkpoint Image once - TestSingleThreadModeRestoreException
Test start time: 2023/06/15 07:15:55 Coordinated Universal Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xjit -XX:+CRIURestoreNonPortableMode " org.openj9.criu.TestSingleThreadModeRestoreException 1 1 false
Time spent starting: 149 milliseconds
Time spent executing: 3796 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] testSingleThreadModeRestoreException() before synchronized on java.lang.Object@6deafdbd, current thread name: main, Thu Jun 15 07:15:56 UTC 2023, System.currentTimeMillis(): 1686813356464, System.nanoTime(): 1686813356460727042
 [OUT] testSingleThreadModeRestoreException() before doCheckpoint(), current thread name: main, Thu Jun 15 07:15:56 UTC 2023, System.currentTimeMillis(): 1686813356596, System.nanoTime(): 1686813356592434267
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: Thread-0, Thu Jun 15 07:15:56 UTC 2023, System.currentTimeMillis(): 1686813356615, System.nanoTime(): 1686813356611816768
 [OUT] JVMJITM044W Some or all compiled code in the code cache invalidated post restore.
 [OUT] Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
 [OUT] 	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:206)
 [OUT] 	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:195)
 [OUT] 	at java.base/java.util.concurrent.ConcurrentSkipListSet.<init>(ConcurrentSkipListSet.java:113)
 [OUT] 	at java.base/java.net.InetAddress.<clinit>(InetAddress.java:788)
 [OUT] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
 [OUT] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1445)
 [OUT] 	at java.base/jdk.internal.misc.SharedSecrets.getJavaNetInetAddressAccess(SharedSecrets.java:170)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.clearInetAddressCache(CRIUSupport.java:623)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI$J9InternalCheckpointHook.runHook(J9InternalCheckpointHookAPI.java:116)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI.runHooks(J9InternalCheckpointHookAPI.java:80)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI.runPostRestoreHooks(J9InternalCheckpointHookAPI.java:97)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:658)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.TestSingleThreadModeRestoreException$1.run(TestSingleThreadModeRestoreException.java:57)
 [OUT] 	at java.base/java.lang.Thread.run(Thread.java:839)
 [OUT] Caused by: org.eclipse.openj9.criu.JVMRestoreException: Blocking operation is not allowed in CRIU single thread mode.
 [OUT] 	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:78)
 [OUT] 	at java.base/java.lang.invoke.MethodHandleCache.processReferenceQueue(MethodHandleCache.java:116)
 [OUT] 	at java.base/java.lang.invoke.MethodHandleCache.addDirectHandle(MethodHandleCache.java:107)
 [OUT] 	at java.base/java.lang.invoke.DirectHandle.addHandleToClassCache(DirectHandle.java:115)
 [OUT] 	at java.base/java.lang.invoke.DirectHandle.<init>(DirectHandle.java:50)
 [OUT] 	at java.base/java.lang.invoke.DirectHandle.<init>(DirectHandle.java:43)
 [OUT] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:648)
 [OUT] 	at java.base/java.lang.invoke.VarHandle.populateMHs(VarHandle.java:949)
 [OUT] 	at java.base/java.lang.invoke.InstanceFieldVarHandle.populateMHs(InstanceFieldVarHandle.java:83)
 [OUT] 	at java.base/java.lang.invoke.InstanceFieldVarHandle.<init>(InstanceFieldVarHandle.java:95)
 [OUT] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVarHandleCommon(MethodHandles.java:1567)
 [OUT] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1540)
 [OUT] 	at java.base/java.util.concurrent.ConcurrentSkipListMap.<clinit>(ConcurrentSkipListMap.java:3405)
 [OUT] 	... 14 more
 [OUT] testSingleThreadModeRestoreException() after doCheckpoint(), current thread name: main, Thu Jun 15 07:15:59 UTC 2023, System.currentTimeMillis(): 1686813359710, System.nanoTime(): 1686813356660968588
 [OUT] testSingleThreadModeRestoreException() after synchronized on java.lang.Object@6deafdbd, current thread name: main, Thu Jun 15 07:15:59 UTC 2023, System.currentTimeMillis(): 1686813359711, System.nanoTime(): 1686813356661486918
 [OUT] Removed testOutput file
 [OUT] finished script
 [ERR] /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 40: 404251 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 $6 > testOutput 2>&1
>> Success condition was not found: [Output match: org.eclipse.openj9.criu.JVMRestoreException: Exception thrown when running user post-restore]
>> Required condition was found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/562
cmdLineTester_criu_nonPortableRestore_Xdump_events_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/562/functional_test_output.tar.gz
```
Testing: Restore dump options test with no dump options specified before checkpoint
Test start time: 2023/06/21 03:13:38 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xjit -XX:+CRIURestoreNonPortableMode  -Xdump:java:events=vmstart" org.openj9.criu.OptionsFileTest DumpOptionsTest 1
Time spent starting: 2 milliseconds
Time spent executing: 3237 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] JVMDUMP039I Processing dump event "vmstart", detail "" at 2023/06/21 03:13:38 - please wait.
 [OUT] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16873270597329/cmdLineTester_criu_nonPortableRestore_Xdump_events_0/javacore.20230621.031338.20910.0001.txt' in response to an event
 [OUT] JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16873270597329/cmdLineTester_criu_nonPortableRestore_Xdump_events_0/javacore.20230621.031338.20910.0001.txt
 [OUT] JVMDUMP013I Processed dump event "vmstart", detail "".
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Jun 21 03:13:39 EDT 2023, System.currentTimeMillis(): 1687331619101, System.nanoTime(): 1687331619097329751
 [OUT] JVMJITM044W Some or all compiled code in the code cache invalidated post restore.
 [OUT] Exception in thread "main" java.lang.ExceptionInInitializerError
 [OUT] 	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:206)
 [OUT] 	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:195)
 [OUT] 	at java.base/java.util.concurrent.ConcurrentSkipListSet.<init>(ConcurrentSkipListSet.java:113)
 [OUT] 	at java.base/java.net.InetAddress.<clinit>(InetAddress.java:788)
 [OUT] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
 [OUT] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1445)
 [OUT] 	at java.base/jdk.internal.misc.SharedSecrets.getJavaNetInetAddressAccess(SharedSecrets.java:170)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.clearInetAddressCache(CRIUSupport.java:623)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI$J9InternalCheckpointHook.runHook(J9InternalCheckpointHookAPI.java:116)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI.runHooks(J9InternalCheckpointHookAPI.java:80)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI.runPostRestoreHooks(J9InternalCheckpointHookAPI.java:97)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:658)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.OptionsFileTest.dumpOptionsTest(OptionsFileTest.java:244)
 [OUT] 	at org.openj9.criu.OptionsFileTest.main(OptionsFileTest.java:60)
 [OUT] Caused by: org.eclipse.openj9.criu.JVMRestoreException: Blocking operation is not allowed in CRIU single thread mode.
 [OUT] 	at java.base/java.lang.ref.Reference.dequeue(Reference.java:205)
 [OUT] 	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:84)
 [OUT] 	at java.base/java.util.WeakHashMap.expungeStaleEntries(WeakHashMap.java:318)
 [OUT] 	at java.base/java.util.WeakHashMap.getTable(WeakHashMap.java:350)
 [OUT] 	at java.base/java.util.WeakHashMap.get(WeakHashMap.java:398)
 [OUT] 	at java.base/java.util.Collections$SynchronizedMap.get(Collections.java:2594)
 [OUT] 	at java.base/java.lang.invoke.HandleCache.getMethodWithSpecialCallerFromPerClassCache(HandleCache.java:153)
 [OUT] 	at java.base/java.lang.invoke.HandleCache.getMethodFromPerClassCache(HandleCache.java:149)
 [OUT] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:645)
 [OUT] 	at java.base/java.lang.invoke.VarHandle.populateMHs(VarHandle.java:949)
 [OUT] 	at java.base/java.lang.invoke.InstanceFieldVarHandle.populateMHs(InstanceFieldVarHandle.java:83)
 [OUT] 	at java.base/java.lang.invoke.InstanceFieldVarHandle.<init>(InstanceFieldVarHandle.java:95)
 [OUT] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVarHandleCommon(MethodHandles.java:1567)
 [OUT] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1540)
 [OUT] 	at java.base/java.util.concurrent.ConcurrentSkipListMap.<clinit>(ConcurrentSkipListMap.java:3405)
 [OUT] 	... 14 more
 [OUT] JVMDUMP039I Processing dump event "vmstop", detail "#0000000000000000" at 2023/06/21 03:13:41 - please wait.
 [OUT] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16873270597329/cmdLineTester_criu_nonPortableRestore_Xdump_events_0/javacore.20230621.031341.20910.0002.txt' in response to an event
 [OUT] JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16873270597329/cmdLineTester_criu_nonPortableRestore_Xdump_events_0/javacore.20230621.031341.20910.0002.txt
 [OUT] JVMDUMP013I Processed dump event "vmstop", detail "#0000000000000000".
 [OUT] Removed test output files
 [OUT] finished script
 [ERR] /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 41: 20910 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 $6 > testOutput 2>&1
>> Success condition was found: [Output match: Killed]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Success condition was found: [Output match: Processing dump event "vmstop"]
>> Success condition was not found: [Output match: Post-checkpoint]
>> Failure condition was found: [Output match: org.eclipse.openj9.criu.JVMRestoreException]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by tajila** [comment]
@JasonFengJ9 This is related to the clear inet changes

**Comment by tajila** [comment]
Actually, I think https://github.com/eclipse-openj9/openj9/pull/17449 will fix this

**Comment by JasonFengJ9** [comment]
https://github.com/eclipse-openj9/openj9/blob/30b42191fed4acbb3894db947c475482544f55fe/jcl/src/java.base/share/classes/java/lang/ref/Reference.java#L254-L256

This failure occurred at the checkpoint thread running restore hooks, and attempting to acquire `this` which was already held by another non-checkpoint thread already halted.
I think this is different from 
* https://github.com/eclipse-openj9/openj9/issues/15806

**Comment by JasonFengJ9** [comment]
```
 [OUT] 	at java.base/java.net.InetAddress.<clinit>(InetAddress.java:788)
 [OUT] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
 [OUT] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1445)
 [OUT] 	at java.base/jdk.internal.misc.SharedSecrets.getJavaNetInetAddressAccess(SharedSecrets.java:170)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.clearInetAddressCache(CRIUSupport.java:623)
```

The restore hook invokes `CRIUSupport.clearInetAddressCache()` even though the class `InetAddress` hasn't been initialized and `SharedSecrets.javaNetInetAddressAccess` is `null`, this is not necessary.
Will open a PR to skip `InetAddress` cache cleanup if it is not initialized.
