### ISSUE TITLE
JCL_Test test_suspend - Failed to resume thread

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17613]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/559
JCL_Test_2 `-XX:+CompactStrings`

```
FAILED: test_suspend
java.lang.AssertionError: Failed to resume thread
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@b092030(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@b092030(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Thread.test_suspend(Test_Thread.java:1074) from jdk.internal.loader.ClassLoaders$AppClassLoader@b092030(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
@dchopra001 fyi, not sure if this is related to `-XX:+CompactStrings` or the recent change.

**Comment by dchopra001** [comment]
Previous grinder passed. Here's a 100x grinder : https://openj9-jenkins.osuosl.org/job/Grinder/2512/

Also a small 10x grinder on the original failing machine: https://openj9-jenkins.osuosl.org/job/Grinder/2513/

**Comment by dchopra001** [comment]
Both grinders passed. Running a final 100x on the original failing machine: https://openj9-jenkins.osuosl.org/job/Grinder/2514/

**Comment by dchopra001** [comment]
All grinders passed. Looks like 220 iterations passed with 110 on the same machine that the original failure occurred on. @pshipton what would be the right way to proceed here? Should we leave this issue open or close and reopen if we encounter a similar issue again?

**Comment by pshipton** [comment]
We'll just keep it open for someone to find more easily, in case it's seen again.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/750
JCL_Test_0
```
FAILED: test_resume
java.lang.AssertionError: Failed to resume thread
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5aecab1(file:/home/jenkins/testDependency/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5aecab1(file:/home/jenkins/testDependency/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Thread.test_resume(Test_Thread.java:733) from jdk.internal.loader.ClassLoaders$AppClassLoader@e5aecab1(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR_testList_1/622
```
13:02:28  FAILED: test_resume
13:02:28  java.lang.AssertionError: Failed to resume thread
13:02:28  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@a430dc78(file:/home/jenkins/testDependency/lib/testng.jar)
13:02:28  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@a430dc78(file:/home/jenkins/testDependency/lib/testng.jar)
13:02:28  	at org.openj9.test.java.lang.Test_Thread.test_resume(Test_Thread.java:733) from
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_1/784
