### ISSUE TITLE
Slow performance writing records to JDBC data source.

### ISSUE THREAD

**Issue by JMarkMurphy** [eclipse-openj9/openj9#17651]
Java -version output
--------------------

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Windows Server 2009 amd64-64-Bit Compressed References 20210421_1045 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)

Summary of problem
------------------

Edition	Windows Server 2022 Datacenter
Version	21H2
Installed on	‎3/‎21/‎2023
OS build	20348.1607

JDBC Driver: jtOpen 9.8

Not sure why java -version reports Windows Server 2009, it is really 2022
Extremely slow performance when inserting data into tables. And, sometimes I get the following error (it might be coincidental):

Jun 23, 2023 1:15:16 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=63649] throws
java.io.IOException: The server sockets created using the LocalRMIServerSocketFactory only accept connections from clients running on the host where the RMI remote objects have been exported.
      at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:114)
      at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
      at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
      at java.lang.Thread.run(Thread.java:750)

Googled the error, the only hit I find is on the OpenJDK Issue Tracker, but it indicates that the issue is with JDK 1.6 and only Ubuntu is affected. I am using neither.

Diagnostic files
----------------
Java emitted no diagnostic files

**Comment by pshipton** [comment]
> Not sure why java -version reports Windows Server 2009, it is really 2022

Support for identifying Windows Server 2022 was added in the 0.31 release.

The 0.26 release is quite old (Apr 2021), pls try the latest to see if the problem still occurs.
