### ISSUE TITLE
[FFI/Jtreg_JDK21] IllegalArgumentException detected in TestNested.java

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17674]
The Jtreg test case ended up with the following errors:
```
test TestNested.testNested(jdk.internal.foreign.layout.UnionLayoutImpl@bf3c7b2a): failure
java.lang.IllegalArgumentException: The padding bits is invalid: x128
        at java.base/openj9.internal.foreign.abi.LayoutStrPreprocessor.getTotalPaddingBytesOfStruct(LayoutStrPreprocessor.java:97)
        at java.base/openj9.internal.foreign.abi.LayoutStrPreprocessor.getSimplifiedLayoutString(LayoutStrPreprocessor.java:70)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.generateAdapter(InternalDowncallHandler.java:328)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.<init>(InternalDowncallHandler.java:317)
        at java.base/jdk.internal.foreign.abi.DowncallLinker.getBoundMethodHandle(DowncallLinker.java:47)
        at java.base/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:137)
        at java.base/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.arrangeDowncall(SysVx64Linker.java:54)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.lambda$downcallHandle$0(AbstractLinker.java:82)
        at java.base/jdk.internal.foreign.abi.SoftReferenceCache$Node.get(SoftReferenceCache.java:52)
        at java.base/jdk.internal.foreign.abi.SoftReferenceCache.get(SoftReferenceCache.java:38)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle(AbstractLinker.java:79)
        at java.base/java.lang.foreign.Linker.downcallHandle(Linker.java:460)
        at NativeTestHelper.downcallHandle(NativeTestHelper.java:163)
        at TestNested.testNested(TestNested.java:66)
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
Looking at the test code at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/nested/TestNested.java and the corresponding native code at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/nested/libNested.c
```
struct S1{ double f0; long long f1; double f2; int f3; };
union U1{ short f0; long long f1; short f2; char f3[4][3]; }; <-----------------
union U17{ char f0; char f1; long long f2; double f3; }; <--------------------
```
which is mixed with `struct` and `union`(which is not yet implemented in OpenJ9).

**Comment by pshipton** [comment]
Once the tests are re-enabled, don't forget to remove the "test excluded" label.

**Comment by pshipton** [comment]
This is waiting for https://github.com/libffi/libffi/pull/805 to merge so we can update to the approved content.

See https://github.com/eclipse-openj9/openj9/pull/18375#issuecomment-1808957660

**Comment by pshipton** [comment]
@ChengJin01 can we close this now the test is unexcluded?

**Comment by ChengJin01** [comment]
https://github.com/libffi/libffi/pull/805 has been merged without any more update as compared to the changes at https://github.com/eclipse-openj9/openj9/pull/18375.
