### ISSUE TITLE
[FFI/Jtreg_JDK21] IndexOutOfBoundsException detected in TestClassLoaderFindNative.java

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17676]
The test suite ended up with the following error:
```
test TestClassLoaderFindNative.testVariableSymbolLookup(): failure
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ heapBase: Optional.empty address:139995130122248 limit: 0 }; new offset = 0; new length = 4
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.outOfBoundException(AbstractMemorySegmentImpl.java:426)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:407)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:69)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:124)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:448)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkBounds(AbstractMemorySegmentImpl.java:396)
        at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkAccess(AbstractMemorySegmentImpl.java:356)
        at java.base/java.lang.invoke.VarHandleSegmentAsInts.checkAddress(VarHandleSegmentAsInts.java:81)
        at java.base/java.lang.invoke.VarHandleSegmentAsInts.get(VarHandleSegmentAsInts.java:108)
        at java.base/java.lang.foreign.MemorySegment.get(MemorySegment.java:1517)
        at TestClassLoaderFindNative.testVariableSymbolLookup(TestClassLoaderFindNative.java:75)
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
Looking at the test code at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/0bf8e32b3c5e101ce38ef51a5fa795ea1d28f5f6/test/jdk/java/foreign/TestClassLoaderFindNative.java#L62
```
    public void testVariableSymbolLookup() {
        MemorySegment segment = SymbolLookup.loaderLookup().find("c").get(); <--------
        /* The variable is 'int c;', so JAVA_INT is a better choice than JAVA_BYTE.
         * See libLookupTest.c.
         */
        assertEquals(segment.get(ValueLayout.JAVA_INT, 0), 42);
    }
```
It turns out `SymbolLookup.loaderLookup().find("c").get()` returns a zero-sized segment for `ADDRESS` as specified in OpenJDK, in which case we have to restore the previous fix for `reinterpret()` the size as mentioned at https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/3#discussion_r1237348625 to ensure the value can be accessed correctly.

**Comment by ChengJin01** [comment]
Close the issue as resolved at https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/11.
