### ISSUE TITLE
JDK21 serviceability_jvmti_j9 a few failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17671]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/1/consoleFull)(`rhel8x86-rtp-rt2-1`):
```
08:24:53  openjdk version "21-internal" 2023-09-19
08:24:53  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21x86-64linuxPersonal)
08:24:53  Eclipse OpenJ9 VM (build master-163a51495d5, JRE 21 Linux amd64-64-Bit Compressed References 20230624_7 (JIT enabled, AOT enabled)
08:24:53  OpenJ9   - 163a51495d5
08:24:53  OMR      - 59b55e30960
08:24:53  JCL      - e76b3946ed5 based on jdk-21+27)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_other_0,jdk_other_1,jdk_security3_0,jdk_security3_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_x86-64_linux_Personal%2F7%2FOpenJ9-JDK21-x86-64_linux-20230624-043005.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_x86-64_linux_Personal%2F7%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=163a51495d5fb2b004ba596846de1738b454bcc2&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
08:27:16  variation: Mode150
08:27:16  JVM_OPTIONS:  -XX:+UseCompressedOops 

08:27:59  TEST: serviceability/jvmti/GetLocalVariable/GetSetLocalUnsuspended.java

08:27:59  STDERR:
08:27:59  
08:27:59  Fatal error: GetLocalInstance

08:27:59  TEST RESULT: Failed. Unexpected exit from test [exit code: 87]


08:30:09  TEST: serviceability/jvmti/vthread/FollowReferences/VThreadStackRefTest.java#no-vmcontinuations

08:30:09  STDERR:
08:30:09  Unhandled exception
08:30:09  Type=Segmentation error vmState=0x00040000
08:30:09  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
08:30:09  Handler1=00007F4C46DB8650 Handler2=00007F4C483DE710 InaccessibleAddress=0000000000000010
08:30:09  RDI=0000000000000000 RSI=000000000000000C RAX=0000000000000000 RBX=00007F4C2441D280
08:30:09  RCX=00007F4BC0047350 RDX=00007F4C2441CDD0 R8=0000000000000030 R9=00007F4C40031080
08:30:09  R10=00007F4C453C25F0 R11=0000000000000001 R12=0000000000000000 R13=0000000000000000
08:30:09  R14=00007F4C2441C1E0 R15=00007F4C40031080
08:30:09  RIP=00007F4C453C33BA GS=0000 FS=0000 RSP=00007F4C2441C1B0
08:30:09  EFlags=0000000000010246 CS=0033 RBP=0000000000245D00 ERR=0000000000000004
08:30:09  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000010
08:30:09  xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:30:09  xmm1 00000000ffef43c0 (f: 4293870592.000000, d: 2.121454e-314)
08:30:09  xmm2 00000000002533d9 (f: 2438105.000000, d: 1.204584e-317)
08:30:09  xmm3 00000000000b53d8 (f: 742360.000000, d: 3.667746e-318)
08:30:09  xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:30:09  xmm5 0000003000000020 (f: 32.000000, d: 1.018558e-312)
08:30:09  xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:30:09  xmm7 0000003000000020 (f: 32.000000, d: 1.018558e-312)
08:30:09  xmm8 0a6425203d206469 (f: 1025533056.000000, d: 1.310212e-258)
08:30:09  xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:30:09  xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:30:09  xmm11 0000015200000151 (f: 337.000000, d: 7.172346e-312)
08:30:09  xmm12 0000013d00000140 (f: 320.000000, d: 6.726727e-312)
08:30:09  xmm13 000001380000013f (f: 319.000000, d: 6.620627e-312)
08:30:09  xmm14 0000000008001800 (f: 134223872.000000, d: 6.631540e-316)
08:30:09  xmm15 000001420000013b (f: 315.000000, d: 6.832826e-312)
08:30:09  Module=/home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/default/libj9jvmti29.so
08:30:09  Module_base_address=00007F4C453AC000
08:30:09  Target=2_90_20230624_7 (Linux 4.18.0-425.19.2.el8_7.x86_64)
08:30:09  CPU=amd64 (4 logical CPUs) (0x1e5342000 RAM)
08:30:09  ----------- Stack Backtrace -----------
08:30:09  followReferencesCallback+0xdca (0x00007F4C453C33BA [libj9jvmti29.so+0x173ba])
08:30:09  _ZN23MM_ReferenceChainWalker6doSlotEPP8J9ObjectllS1_.localalias+0x96 (0x00007F4C4559D246 [libj9gc29.so+0x38246])
08:30:09  walkStackFrames+0x11d0 (0x00007F4C46DFC020 [libj9vm29.so+0x87020])
08:30:09  walkContinuationStackFrames.part.0+0x56 (0x00007F4C46E137D6 [libj9vm29.so+0x9e7d6])
08:30:09  _ZN28GC_VMThreadStackSlotIterator9scanSlotsEP10J9VMThreadP16J9VMContinuationPvPFvP8J9JavaVMPP8J9ObjectS4_P16J9StackWalkStatePKvEbb+0x3e (0x00007F4C455A9CBE [libj9gc29.so+0x44cbe])
08:30:09  _ZN14MM_RootScanner13scanOneThreadEP18MM_EnvironmentBaseP10J9VMThreadPv+0x13a (0x00007F4C455A108A [libj9gc29.so+0x3c08a])
08:30:09  _ZN14MM_RootScanner11scanThreadsEP18MM_EnvironmentBase+0xcf (0x00007F4C4559F94F [libj9gc29.so+0x3a94f])
08:30:09  _ZN14MM_RootScanner12scanAllSlotsEP18MM_EnvironmentBase+0x3a (0x00007F4C455A30CA [libj9gc29.so+0x3e0ca])
08:30:09  j9gc_ext_reachable_objects_do+0x1b9 (0x00007F4C4559F009 [libj9gc29.so+0x3a009])
08:30:09  jvmtiFollowReferences+0x2ab (0x00007F4C453C3F1B [libj9jvmti29.so+0x17f1b])
08:30:09  Java_VThreadStackRefTest_test+0x163 (0x00007F4C4402A723 [libVThreadStackRefTest.so+0x3723])
08:30:09  ffi_call_unix64+0x52 (0x00007F4C46F88DAA [libj9vm29.so+0x213daa])
08:30:09  ffi_call_int+0x1a1 (0x00007F4C46F87F41 [libj9vm29.so+0x212f41])
08:30:09  _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x11925 (0x00007F4C46E25635 [libj9vm29.so+0xb0635])
08:30:09  bytecodeLoopCompressed+0xca (0x00007F4C46E13CFA [libj9vm29.so+0x9ecfa])
08:30:09   (0x00007F4C46F16632 [libj9vm29.so+0x1a1632])
08:30:09  ---------------------------------------
08:30:09  JVMDUMP039I Processing dump event "gpf", detail "" at 2023/06/24 05:30:06 - please wait.

08:30:09  TEST RESULT: Failed. Unexpected exit from test [exit code: 255]


08:30:10  TEST: serviceability/jvmti/vthread/ForceEarlyReturnTest/ForceEarlyReturnTest.java#no-vmcontinuations

08:30:10  STDERR:
08:30:10  java.lang.RuntimeException: ForceEarlyReturnTest failed!
08:30:10  	at ForceEarlyReturnTest.throwFailed(ForceEarlyReturnTest.java:88)
08:30:10  	at ForceEarlyReturnTest.run(ForceEarlyReturnTest.java:120)
08:30:10  	at ForceEarlyReturnTest.main(ForceEarlyReturnTest.java:93)

08:30:10  
08:30:10  JavaTest Message: Test threw exception: java.lang.RuntimeException: ForceEarlyReturnTest failed!

08:30:10  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: ForceEarlyReturnTest failed!

08:30:15  TEST: serviceability/jvmti/vthread/PopFrameTest/PopFrameTest.java#no-vmcontinuations

08:30:15  STDERR:
08:30:15  java.lang.RuntimeException: PopFrameTest failed!
08:30:15  	at PopFrameTest.throwFailed(PopFrameTest.java:81)
08:30:15  	at PopFrameTest.run(PopFrameTest.java:111)
08:30:15  	at PopFrameTest.main(PopFrameTest.java:86)

08:30:15  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: PopFrameTest failed!

08:30:16  TEST: serviceability/jvmti/vthread/PopFrameTest/PopFrameTest.java#platform
08:30:16  STDERR:
08:30:16  
08:30:16  Fatal error: Breakpoint: Failed in PopFrame

08:30:16  TEST RESULT: Failed. Unexpected exit from test [exit code: 87]

08:30:19  TEST: serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java#no-vmcontinuations
08:30:19  STDERR:
08:30:19  java.lang.RuntimeException: StopThreadTest failed!
08:30:19  	at StopThreadTest.throwFailed(StopThreadTest.java:80)
08:30:19  	at StopThreadTest.run(StopThreadTest.java:113)
08:30:19  	at StopThreadTest.main(StopThreadTest.java:85)

08:30:19  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: StopThreadTest failed!

08:30:20  TEST: serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java#platform
08:30:20  TEST RESULT: Failed. Unexpected exit from test [exit code: 87]
08:30:20  --------------------------------------------------
08:30:44  Test results: passed: 118; failed: 7
08:30:53  Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/jvmtest/openjdk/report/html/report.html
08:30:53  Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/aqa-tests/TKG/output_16876095876025/serviceability_jvmti_j9_0/work
08:30:53  Error: Some tests failed or other problems occurred.
08:30:53  -----------------------------------
08:30:53  serviceability_jvmti_j9_0_FAILED
```

**Comment by JasonFengJ9** [comment]
Created separated issues to track potential different root causes as per project loom meeting discussion:
* https://github.com/eclipse-openj9/openj9/issues/17711
* https://github.com/eclipse-openj9/openj9/issues/17712
* https://github.com/eclipse-openj9/openj9/issues/17713
* https://github.com/eclipse-openj9/openj9/issues/17715
* https://github.com/eclipse-openj9/openj9/issues/17716
* https://github.com/eclipse-openj9/openj9/issues/17717
* https://github.com/eclipse-openj9/openj9/issues/17718

**Comment by babsingh** [comment]
Closing since separate issues have been opened for each failure; ref: https://github.com/eclipse-openj9/openj9/issues/17671#issuecomment-1613611779.
