### ISSUE TITLE
xlinux criu failures

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17681]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly_testList_1/545
06:09:01  FAILED test targets:
06:09:01  	cmdLineTester_criu_keepCheckpoint_1 
06:09:01  	cmdLineTester_criu_keepCheckpoint_2 
06:09:01  	cmdLineTester_criu_keepCheckpoint_5 
06:09:01  	cmdLineTester_criu_nonPortableRestore_0 
06:09:01  	cmdLineTester_criu_nonPortableRestore_2 
06:09:01  	cmdLineTester_criu_nonPortableRestore_5 
06:09:01  	cmdLineTester_criu_nonPortableRestore_6 
06:09:01  	cmdLineTester_criu_jitserverPostRestore_0 
06:09:01  	cmdLineTester_criu_jitserverPostRestore_1 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xtrace_tracepoint_0 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xtrace_tracepoint_3 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xtrace_methodtrace_1 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xtrace_methodtrace_4 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xtrace_outputFile_1 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xtrace_outputFile_2 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xdump_events_0 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xdump_events_2 
06:09:01  	cmdLineTester_criu_nonPortableRestore_Xdump_events_3 
06:09:01  	cmdLineTester_criu_nonPortableRestoreJDK11Up_1 
06:09:01  	cmdLineTester_criu_nonPortableRestoreJDK11Up_2 
06:09:01  	cmdLineTester_criu_security_0

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
Running a grinder on the same machine https://openj9-jenkins.osuosl.org/job/Grinder/2534/

**Comment by tajila** [comment]
No failures were seen on JDK17 or JDK20

**Comment by JasonFengJ9** [comment]
```
[OUT] Exception in thread "Thread-0" org.eclipse.openj9.criu.SystemCheckpointException: The JVM attempted to load libcriu.so but was unable to: 1
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:676)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVMNoSetup(CRIUTestUtils.java:105)
 [OUT] 	at org.openj9.criu.TestSingleThreadModeRestoreException$2.run(TestSingleThreadModeRestoreException.java:123)
 [OUT] 	at java.base/java.lang.Thread.run(Thread.java:839)
```
This is a machine setup issue.

```
[OUT] Unhandled exception
 [OUT] Type=Segmentation error vmState=0x00200000
 [OUT] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
 [OUT] Handler1=00007F29D4A99E00 Handler2=00007F29D47EFB50 InaccessibleAddress=0000000000000000
 [OUT] RDI=0000000000000000 RSI=0000000000010000 RAX=0000000000000007 RBX=0000000000262E00
 [OUT] RCX=00007F29D6741EFD RDX=0000000000000007 R8=0000000000000001 R9=00007F29A8C8E2E0
 [OUT] R10=0000000000000004 R11=0000000000000000 R12=00007F29D5D3A420 R13=00007F29A8C8EAB0
 [OUT] R14=00007F29D5D3B520 R15=0000000000000000
 [OUT] RIP=0000000000000000 GS=0000 FS=0000 RSP=00007F29A8C8E988
 [OUT] EFlags=0000000000010202 CS=0033 RBP=00007F29D0012380 ERR=0000000000000014
 [OUT] TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
 [OUT] xmm0 0000000400000002 (f: 2.000000, d: 8.487983e-314)
 [OUT] xmm1 ffffffffffffffff (f: 4294967296.000000, d: -nan)
 [OUT] xmm2 656c36312d667475 (f: 761689216.000000, d: 3.658276e+180)
 [OUT] xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [OUT] xmm4 4040404040404040 (f: 1077952512.000000, d: 3.250196e+01)
 [OUT] xmm5 5b5b5b5b5b5b5b5b (f: 1532713856.000000, d: 1.213625e+132)
 [OUT] xmm6 2020202020202020 (f: 538976256.000000, d: 6.013470e-154)
 [OUT] xmm7 2020000000202020 (f: 2105376.000000, d: 5.966673e-154)
 [OUT] xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [OUT] xmm9 2020000000202020 (f: 2105376.000000, d: 5.966673e-154)
 [OUT] xmm10 ffffffffffffffff (f: 4294967296.000000, d: -nan)
 [OUT] xmm11 ffffffffffffffff (f: 4294967296.000000, d: -nan)
 [OUT] xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [OUT] xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [OUT] xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [OUT] xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [OUT] Target=2_90_20230627_581 (Linux 3.10.0-1127.13.1.el7.x86_64)
 [OUT] CPU=amd64 (4 logical CPUs) (0x1e8cf5000 RAM)
 [OUT] ----------- Stack Backtrace -----------
 [OUT] protectedBacktrace+0x12 (0x00007F29D47EC052 [libj9prt29.so+0x27052])
 [OUT] omrsig_protect+0x1e3 (0x00007F29D47F08B3 [libj9prt29.so+0x2b8b3])
 [OUT] omrintrospect_backtrace_thread_raw+0xba (0x00007F29D47EC54A [libj9prt29.so+0x2754a])
 [OUT] omrsig_protect+0x1e3 (0x00007F29D47F08B3 [libj9prt29.so+0x2b8b3])
 [OUT] omrintrospect_backtrace_thread+0x84 (0x00007F29D47EBEE4 [libj9prt29.so+0x26ee4])
 [OUT] generateDiagnosticFiles+0x84 (0x00007F29D4A99944 [libj9vm29.so+0x44944])
 [OUT] omrsig_protect+0x1e3 (0x00007F29D47F08B3 [libj9prt29.so+0x2b8b3])
 [OUT] vmSignalHandler+0x185 (0x00007F29D4A99BB5 [libj9vm29.so+0x44bb5])
 [OUT] mainSynchSignalHandler+0x22a (0x00007F29D47EFD7A [libj9prt29.so+0x2ad7a])
 [OUT]  (0x00007F29D6742630 [libpthread.so.0+0xf630])
 [OUT] ---------------------------------------
 [OUT] JVMDUMP039I Processing dump event "gpf", detail "" at 2023/06/27 03:35:47 - please wait.
```
GC related?

**Comment by pshipton** [comment]
These are on [cent7-x64-2](https://openj9-jenkins.osuosl.org/computer/cent7-x64-2) for which we already have an issue https://github.com/eclipse-openj9/openj9/issues/17678. Something obviously happened to this machine, I've disabled it.

**Comment by tajila** [comment]
Grinder on different machine (hopefully) - > https://openj9-jenkins.osuosl.org/job/Grinder/2535/
