### ISSUE TITLE
[FFI/Jtreg_JDK21] AssertionError detected in TestAddressDereference.java

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17686]
The test suite ended up with the following errors:
```
test TestAddressDereference.testNativeReturn(1, c16): failure
java.lang.AssertionError: expected [false] but found [true]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertFalse(Assert.java:67)
        at org.testng.Assert.assertFalse(Assert.java:77)
        at TestAddressDereference.testNativeReturn(TestAddressDereference.java:105)
...
test TestAddressDereference.testNativeUpcallArgNeg(1, d64): failure
java.lang.AssertionError: Did not find 'alignment constraint for address' in stderr expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertTrue(Assert.java:45)
        at UpcallTestHelper$Output.assertContains(UpcallTestHelper.java:41)
        at UpcallTestHelper$Output.assertStdErrContains(UpcallTestHelper.java:46)
        at TestAddressDereference.testNativeUpcallArgNeg(TestAddressDereference.java:131)
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
I think the best way to address all invalid cases for downcall  & upcall is to unify the validation methods in java shared d by downcall & upcall with downcall/upcall MH filters (in which case there is no need to do call-ins to capture the exceptions/invalid cases in the dispatcher after the upcall). This also helps extend the validation with more flexibility without modifying the code in the dispatcher.  I will go through the code in downcall/upcall and in the dispatcher to see how to refactor the code around there to cover all cases encountered in downcall & upcall.
