### ISSUE TITLE
classesByName2Test_0_FAILED Target VM failed to initialize due to NPE, ERROR: transport error 202: getaddrinfo: unknown host

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17700]
Failure link
------------

From https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/243/consoleFull (`mac10-x86-1`):
```
15:05:31  openjdk version "11.0.20-internal" 2023-07-18
15:05:31  OpenJDK Runtime Environment (build 11.0.20-internal+0-adhoc.****.BuildJDK11x86-64macNightly)
15:05:31  Eclipse OpenJ9 VM (build master-c6295b81835, JRE 11 Mac OS X amd64-64-Bit Compressed References 20230627_585 (JIT enabled, AOT enabled)
15:05:31  OpenJ9   - c6295b81835
15:05:31  OMR      - 0c448df41bb
15:05:31  JCL      - 89b7f696447 based on jdk-11.0.20+7)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&EXTRA_DOCKER_ARGS=&PLATFORM=x86-64_mac&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=&JENKINS_KEY=&LIGHT_WEIGHT_CHECKOUT=true&ARTIFACTORY_SERVER=ci-eclipse-openj9&USE_JRE=false&KEEP_WORKSPACE=false&JDK_VERSION=11&DOCKER_REGISTRY_URL=&EXIT_FAILURE=false&EXIT_SUCCESS=false&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=enableStrCompF&OPENJ9_SHA=433b1c4afdc2dcd6c5767b942a5420da316b243d&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Fdchopra001%2Fopenj9.git&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&UPSTREAM_TEST_JOB_NUMBER=2550&DOCKERIMAGE_TAG=&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&OPENJDK_SHA=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&JDK_VENDOR=&BUILDS_TO_KEEP=60&TIME_LIMIT=10&PARALLEL=None&TARGET=testList+TESTLIST=classesByName2Test_0,classesByName2Test_0,classesByName2Test_0,classesByName2Test_0,classesByName2Test_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Grinder&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&GENERATE_JOBS=true&KEEP_REPORTDIR=true&RERUN_ITERATIONS=0&LABEL=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK11_x86-64_mac_Nightly%2F585%2FOpenJ9-JDK11-x86-64_mac-20230627-211131.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK11_x86-64_mac_Nightly%2F585%2Ftest-images.tar.gz&DAYS_TO_KEEP=7&ADOPTOPENJDK_BRANCH=master&USER_CREDENTIALS_ID=&ITERATIONS=5&VENDOR_TEST_REPOS=&JCK_GIT_REPO=&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&VENDOR_TEST_SHAS=&TEST_IMAGES_REQUIRED=true&ARTIFACTORY_ROOT_DIR=Test&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TKG_ITERATIONS=1&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=&ADDITIONAL_ARTIFACTS_REQUIRED=&JVM_OPTIONS=) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:09:41  variation: Mode150
15:09:41  JVM_OPTIONS:  -XX:+UseCompressedOops 

15:09:49  TEST: com/sun/jdi/ClassesByName2Test.java

15:09:49  STDERR:
15:09:49  [5ms] run args: [ClassesByName2Targ]
15:09:49  VM initialization failed for: /Users/jenkins/workspace/Grinder_testList_0/openjdkbinary/j2sdk-image/bin/java -classpath /Users/jenkins/workspace/Grinder_testList_0/aqa-tests/TKG/output_16879793804911/classesByName2Test_0/work/classes/0/com/sun/jdi/ClassesByName2Test.d -ea -esa -Xmx512m -XX:+UseCompressedOops -Xdebug -Xrunjdwp:transport=dt_socket,address=mac10-x86-1:57640,suspend=y ClassesByName2Targ
15:09:49  
15:09:49  
15:09:49   Target VM failed to initialize.
15:09:49  java.lang.NullPointerException
15:09:49  	at VMConnection.open(VMConnection.java:157)
15:09:49  	at TestScaffold.connect(TestScaffold.java:636)
15:09:49  	at TestScaffold.startUp(TestScaffold.java:364)
15:09:49  	at TestScaffold.startTo(TestScaffold.java:374)
15:09:49  	at TestScaffold.startToMain(TestScaffold.java:369)
15:09:49  	at ClassesByName2Test.runTests(ClassesByName2Test.java:147)
15:09:49  	at TestScaffold.startTests(TestScaffold.java:431)
15:09:49  	at ClassesByName2Test.main(ClassesByName2Test.java:123)
15:09:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:09:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:09:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:09:49  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:09:49  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
15:09:49  	at java.base/java.lang.Thread.run(Thread.java:839)
15:09:49  
15:09:49  JavaTest Message: Test threw exception: java.lang.NullPointerException
15:09:49  JavaTest Message: shutting down test
15:09:49  
15:09:49  STDOUT:
15:09:49  vmOpts: '-ea -esa -Xmx512m -XX:+UseCompressedOops'
15:09:49  javaOpts: ''
15:09:49  ERROR: transport error 202: getaddrinfo: unknown host
15:09:49  ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
15:09:49  JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:735]
15:09:49  
15:09:49  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.NullPointerException
15:09:49  --------------------------------------------------
15:09:49  Test results: failed: 1
15:09:58  Report written to /Users/jenkins/workspace/Grinder_testList_0/aqa-tests/TKG/output_16879793804911/classesByName2Test_0/report/html/report.html
15:09:58  Results written to /Users/jenkins/workspace/Grinder_testList_0/aqa-tests/TKG/output_16879793804911/classesByName2Test_0/work
15:09:58  Error: Some tests failed or other problems occurred.
15:09:58  -----------------------------------
15:09:58  classesByName2Test_0_FAILED
```

**Comment by pshipton** [comment]
This seems a machine problem. @AdamBrousseau 

I believe this is due to trying to run an extended.openjdk test what we normally don't run, although we should be able to.

**Comment by JasonFengJ9** [comment]
> I believe this is due to trying to run an extended.openjdk test what we normally don't run, although we should be able to.

Correct, this is a personal grinder to verify `-XX:+ CompactStrings` by @dchopra001

**Comment by pshipton** [comment]
`getaddrinfo: unknown host` indicates some sort of host name problem on the machine. The test should be trying to connect to the same machine where it's running.

**Comment by pshipton** [comment]
This demonstrates the problem:
```
mac10-x86-1:~ jenkins$ hostname
mac10-x86-1
mac10-x86-1:~ jenkins$ ping mac10-x86-1
ping: cannot resolve mac10-x86-1: Unknown host
```

**Comment by JasonFengJ9** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_s390x_linux_fips140_2_testList_0/12/
```
[2024-05-17T20:28:45.154Z] variation: Mode150
[2024-05-17T20:28:45.154Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true

[2024-05-17T20:31:13.052Z] TEST: com/sun/jdi/ClassesByName2Test.java

[2024-05-17T20:31:13.053Z] VM initialization failed for: /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_fips140_2_testList_0/jdkbinary/j2sdk-image/bin/java -classpath /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_fips140_2_testList_0/aqa-tests/TKG/output_17159775797792/classesByName2Test_0/work/classes/0/com/sun/jdi/ClassesByName2Test.d -ea -esa -Xmx512m -XX:+UseCompressedOops -Xverbosegclog -Dsemeru.fips=true -Xdebug -Xrunjdwp:transport=dt_socket,address=rhel8s390x-svl-rtfips14-1.fyre.ibm.com:54251,suspend=y ClassesByName2Targ
[2024-05-17T20:31:13.053Z] 
[2024-05-17T20:31:13.053Z] 
[2024-05-17T20:31:13.053Z]  Target VM failed to initialize.
[2024-05-17T20:31:13.053Z] java.lang.NullPointerException
[2024-05-17T20:31:13.053Z] 	at VMConnection.open(VMConnection.java:157)
[2024-05-17T20:31:13.053Z] 	at TestScaffold.connect(TestScaffold.java:636)
[2024-05-17T20:31:13.053Z] 	at TestScaffold.startUp(TestScaffold.java:364)
[2024-05-17T20:31:13.053Z] 	at TestScaffold.startTo(TestScaffold.java:374)
[2024-05-17T20:31:13.053Z] 	at TestScaffold.startToMain(TestScaffold.java:369)
[2024-05-17T20:31:13.053Z] 	at ClassesByName2Test.runTests(ClassesByName2Test.java:147)
[2024-05-17T20:31:13.053Z] 	at TestScaffold.startTests(TestScaffold.java:431)
[2024-05-17T20:31:13.053Z] 	at ClassesByName2Test.main(ClassesByName2Test.java:123)

[2024-05-17T20:31:13.053Z] 
[2024-05-17T20:31:13.053Z] STDOUT:
[2024-05-17T20:31:13.053Z] vmOpts: '-ea -esa -Xmx512m -XX:+UseCompressedOops -Xverbosegclog -Dsemeru.fips=true'
[2024-05-17T20:31:13.053Z] javaOpts: ''
[2024-05-17T20:31:13.053Z] ERROR: transport error 202: connect failed: Connection timed out
[2024-05-17T20:31:13.053Z] ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
[2024-05-17T20:31:13.053Z] JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:745]
[2024-05-17T20:31:13.053Z] 
[2024-05-17T20:31:13.053Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.NullPointerException
[2024-05-17T20:31:13.053Z] --------------------------------------------------
[2024-05-17T20:31:13.053Z] Test results: failed: 1
[2024-05-17T20:31:19.802Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_fips140_2_testList_0/aqa-tests/TKG/output_17159775797792/classesByName2Test_0/report/html/report.html
[2024-05-17T20:31:19.802Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_fips140_2_testList_0/aqa-tests/TKG/output_17159775797792/classesByName2Test_0/work
[2024-05-17T20:31:19.802Z] Error: Some tests failed or other problems occurred.
[2024-05-17T20:31:19.802Z] -----------------------------------
[2024-05-17T20:31:19.802Z] classesByName2Test_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40698/)
