### ISSUE TITLE
test jcstress_BooleanFencedTest_0 UnsupportedOperationException at jdk.management/com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl.getThreadAllocatedBytes(ExtendedThreadMXBeanImpl.java:74)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17728]
ailure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_dev.system_aarch64_linux/2/consoleText)(`ub20-aarch64-6`):
```
23:30:15  openjdk version "11.0.20" 2023-07-18
23:30:15  IBM Semeru Runtime Open Edition 11.0.20.0-m2 (build 11.0.20+7)
23:30:15  Eclipse OpenJ9 VM 11.0.20.0-m2 (build v0.40.0-release-6eed0535c, JRE 11 Linux aarch64-64-Bit Compressed References 20230628_721 (JIT enabled, AOT enabled)
23:30:15  OpenJ9   - 6eed0535c
23:30:15  OMR      - e80bff83b
23:30:15  JCL      - 20e0e53157 based on jdk-11.0.20+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=dev.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=0&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F721%2Fibm-semeru-open-jdk_aarch64_linux_11.0.20_7_openj9-0.40.0-m2.tar.gz&BUILD_IDENTIFIER=&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=11&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&JCK_GIT_BRANCH=main&RELEASE_TAG=v0.40.0-release&OPENJ9_BRANCH=v0.40.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.40.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-06-29T03:35:31.862Z] ===============================================
[2023-06-29T03:35:31.862Z] Running test jcstress_BooleanFencedTest_0 ...
[2023-06-29T03:35:31.862Z] ===============================================
[2023-06-29T03:35:31.862Z] jcstress_BooleanFencedTest_0 Start Time: Wed Jun 28 23:35:31 2023 Epoch Time (ms): 1688009731573
[2023-06-29T03:35:31.862Z] variation: NoOptions
[2023-06-29T03:35:31.862Z] JVM_OPTIONS:  

[2023-06-29T03:35:43.451Z] Exception in thread "main" java.lang.IllegalStateException: @Contended does not seem to work properly
[2023-06-29T03:35:43.451Z] 	at org.openjdk.jcstress.vm.ContendedTestMain.main(ContendedTestMain.java:80)
[2023-06-29T03:35:43.451Z] 
[2023-06-29T03:35:43.451Z] ----- [OK] Unlocking debug information for non-safepoints
[2023-06-29T03:35:43.868Z] ----- [OK] Unlocking C2 local code motion randomizer
[2023-06-29T03:35:43.868Z] ----- [OK] Unlocking C2 global code motion randomizer
[2023-06-29T03:35:44.284Z] ----- [OK] Unlocking C2 iterative global value numbering randomizer
[2023-06-29T03:35:44.704Z] ----- [OK] Unlocking C2 conditional constant propagation randomizer
[2023-06-29T03:35:45.121Z] ----- [OK] Checking if C2 randomizers accept stress seed
[2023-06-29T03:35:45.537Z] ----- [N/A] Testing allocation profiling
[2023-06-29T03:35:45.537Z] Exception in thread "main" java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
[2023-06-29T03:35:45.537Z] 	at org.openjdk.jcstress.vm.AllocProfileSupport.getAllocatedBytes(AllocProfileSupport.java:94)
[2023-06-29T03:35:45.537Z] 	at org.openjdk.jcstress.vm.AllocProfileMain.main(AllocProfileMain.java:38)
[2023-06-29T03:35:45.537Z] Caused by: java.lang.reflect.InvocationTargetException
[2023-06-29T03:35:45.537Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-06-29T03:35:45.537Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-06-29T03:35:45.537Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-06-29T03:35:45.537Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-06-29T03:35:45.537Z] 	at org.openjdk.jcstress.vm.AllocProfileSupport.getAllocatedBytes(AllocProfileSupport.java:92)
[2023-06-29T03:35:45.537Z] 	... 1 more
[2023-06-29T03:35:45.537Z] Caused by: java.lang.UnsupportedOperationException
[2023-06-29T03:35:45.537Z] 	at jdk.management/com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl.getThreadAllocatedBytes(ExtendedThreadMXBeanImpl.java:74)
[2023-06-29T03:35:45.537Z] 	... 6 more

[2023-06-29T04:37:32.106Z] 	at org.openjdk.jcstress.infra.grading.ExceptionReportPrinter.work(ExceptionReportPrinter.java:63)
[2023-06-29T04:37:32.106Z] 	at org.openjdk.jcstress.JCStress.parseResults(JCStress.java:140)
[2023-06-29T04:37:32.106Z] 	at org.openjdk.jcstress.JCStress.run(JCStress.java:107)
[2023-06-29T04:37:32.106Z] 	at org.openjdk.jcstress.Main.main(Main.java:60)
[2023-06-29T04:37:32.106Z] -----------------------------------
[2023-06-29T04:37:32.106Z] jcstress_ReentrantRWLockMutexTests_0_FAILED
```

**Comment by pshipton** [comment]
Seems a problem with the test, OpenJ9 doesn't support getThreadAllocatedBytes() and throwing UnsupportedOperationException is behavior allowed by the spec.

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
dup of https://github.com/eclipse-openj9/openj9/issues/16569
