### ISSUE TITLE
OpenJDK sun/security/krb5/auto/Renewal checkRough Timestamp is actual difference 3554 is not 3600

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17749]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_OMR_testList_2/3
jdk_security4_1
sun/security/krb5/auto/Renewal.java
```
09:36:35  Start KDC on 10600
09:36:35  Callback for name: dummy
09:36:35  Callback for pass: bogus
09:36:35  -----------------------------------------------
09:36:35  >>>>> UDP packet received
09:36:35  RABBIT.HOLE:10600> dummy@RABBIT.HOLE sends AS-REQ for krbtgt/RABBIT.HOLE@RABBIT.HOLE, KDCOptions: 
09:36:35       Return dummy@RABBIT.HOLE ticket for krbtgt/RABBIT.HOLE@RABBIT.HOLE, flags INITIAL
09:36:35  >>>>> UDP request honored
09:36:35  Callback for name: dummy
09:36:35  Callback for pass: bogus
09:36:35  -----------------------------------------------
09:36:35  >>>>> UDP packet received
09:36:35  RABBIT.HOLE:10600> dummy@RABBIT.HOLE sends AS-REQ for krbtgt/RABBIT.HOLE@RABBIT.HOLE, KDCOptions: 
09:36:35       Return dummy@RABBIT.HOLE ticket for krbtgt/RABBIT.HOLE@RABBIT.HOLE, flags INITIAL
09:36:35  >>>>> UDP request honored
09:36:35  Callback for name: dummy
09:36:35  Callback for pass: bogus
09:36:35  -----------------------------------------------
09:36:35  >>>>> UDP packet received
09:36:35  RABBIT.HOLE:10600> dummy@RABBIT.HOLE sends AS-REQ for krbtgt/RABBIT.HOLE@RABBIT.HOLE, KDCOptions: RENEWABLE,
09:36:35       Return dummy@RABBIT.HOLE ticket for krbtgt/RABBIT.HOLE@RABBIT.HOLE, flags RENEWABLE;INITIAL
09:36:35  >>>>> UDP request honored
09:36:35  Callback for name: dummy
09:36:35  Callback for pass: bogus
09:36:35  -----------------------------------------------
09:36:35  >>>>> UDP packet received
09:36:35  RABBIT.HOLE:10600> dummy@RABBIT.HOLE sends AS-REQ for krbtgt/RABBIT.HOLE@RABBIT.HOLE, KDCOptions: RENEWABLE,
09:36:35       Return dummy@RABBIT.HOLE ticket for krbtgt/RABBIT.HOLE@RABBIT.HOLE, flags RENEWABLE;INITIAL
09:36:35  >>>>> UDP request honored
09:36:35  Callback for name: dummy
09:36:35  Callback for pass: bogus
09:36:35  -----------------------------------------------
09:36:35  >>>>> UDP packet received
09:36:35  RABBIT.HOLE:10600> dummy@RABBIT.HOLE sends AS-REQ for krbtgt/RABBIT.HOLE@RABBIT.HOLE, KDCOptions: RENEWABLE,
09:36:35       Return dummy@RABBIT.HOLE ticket for krbtgt/RABBIT.HOLE@RABBIT.HOLE, flags RENEWABLE;INITIAL
09:36:35  >>>>> UDP request honored
09:36:35  -----------------------------------------------
09:36:35  >>>>> UDP packet received
09:36:35  RABBIT.HOLE:10600> dummy@RABBIT.HOLE sends AS-REQ for krbtgt/RABBIT.HOLE@RABBIT.HOLE, KDCOptions: 
09:36:35       Return dummy@RABBIT.HOLE ticket for krbtgt/RABBIT.HOLE@RABBIT.HOLE, flags INITIAL
09:36:35  >>>>> UDP request honored
09:36:35  -----------------------------------------------
09:36:35  >>>>> UDP packet received
09:36:35  RABBIT.HOLE:10600> dummy@RABBIT.HOLE sends AS-REQ for krbtgt/RABBIT.HOLE@RABBIT.HOLE, KDCOptions: RENEWABLE,
09:36:35       Return dummy@RABBIT.HOLE ticket for krbtgt/RABBIT.HOLE@RABBIT.HOLE, flags RENEWABLE;INITIAL
09:36:35  >>>>> UDP request honored
09:36:35  STDERR:
09:36:35  java.lang.Exception: Timestamp is Wed Jul 05 10:35:41 EDT 2023, actual difference 3554 is not 3600
09:36:35  	at Renewal.checkRough(Renewal.java:166)
09:36:35  	at Renewal.checkKinit(Renewal.java:112)
09:36:35  	at Renewal.main(Renewal.java:73)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0/12/consoleFull
```
02:34:02  variation: Mode650
02:34:02  JVM_OPTIONS:  -XX:-UseCompressedOops 

03:04:05  TEST: sun/security/krb5/auto/Renewal.java

03:04:05  STDERR:
03:04:05  java.lang.Exception: Timestamp is Fri Jul 14 04:03:18 EDT 2023, actual difference 3554 is not 3600
03:04:05  	at Renewal.checkRough(Renewal.java:166)
03:04:05  	at Renewal.checkKinit(Renewal.java:112)
03:04:05  	at Renewal.main(Renewal.java:73)
03:04:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:04:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
03:04:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:04:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
03:04:05  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:04:05  	at java.base/java.lang.Thread.run(Thread.java:857)
03:04:05  
03:04:05  JavaTest Message: Test threw exception: java.lang.Exception: Timestamp is Fri Jul 14 04:03:18 EDT 2023, actual difference 3554 is not 3600

03:04:05  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Timestamp is Fri Jul 14 04:03:18 EDT 2023, actual difference 3554 is not 3600
03:04:05  --------------------------------------------------
03:22:40  Test results: passed: 147; failed: 1
03:23:12  Report written to F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_16893049702689\jdk_security4_1\report\html\report.html
03:23:12  Results written to F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_16893049702689\jdk_security4_1\work
03:23:12  Error: Some tests failed or other problems occurred.
03:23:12  -----------------------------------
03:23:12  jdk_security4_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_2/281/consoleFull)(`win11x86-svl-rt5-1`)
```
19:17:54  Running test jdk_security4_1 ...
19:17:54  ===============================================
19:17:55  jdk_security4_1 Start Time: Tue Sep 16 16:17:54 2025 Epoch Time (ms): 1758064674246
19:17:55  variation: Mode650
19:17:57  JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

20:00:40  TEST: sun/security/krb5/auto/Renewal.java

20:00:40  STDERR:
20:00:40  java.lang.Exception: Timestamp is Tue Sep 16 17:59:43 PDT 2025, actual difference 3556 is not 3600
20:00:40  	at Renewal.checkRough(Renewal.java:166)
20:00:40  	at Renewal.checkKinit(Renewal.java:112)
20:00:40  	at Renewal.main(Renewal.java:73)
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_testList_8/24/)
```
[2025-12-07T12:17:58.972Z] Running test jdk_security4_1 ...
[2025-12-07T12:17:59.409Z] ===============================================
[2025-12-07T12:17:59.409Z] jdk_security4_1 Start Time: Sun Dec  7 04:17:59 2025 Epoch Time (ms): 1765109879296
[2025-12-07T12:17:59.877Z] variation: Mode650
[2025-12-07T12:18:00.316Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-12-07T13:01:46.835Z] TEST: sun/security/krb5/auto/Renewal.java

[2025-12-07T13:01:46.836Z] STDERR:
[2025-12-07T13:01:46.836Z] java.lang.Exception: Timestamp is Sun Dec 07 05:31:02 PST 2025, actual difference 1758 is not 1800
[2025-12-07T13:01:46.836Z] 	at Renewal.checkRough(Renewal.java:166)
[2025-12-07T13:01:46.836Z] 	at Renewal.checkKinit(Renewal.java:112)
[2025-12-07T13:01:46.836Z] 	at Renewal.main(Renewal.java:74)
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_8/24/)
```
[2025-12-12T20:15:07.869Z] Running test jdk_security4_1 ...
[2025-12-12T20:15:08.341Z] ===============================================
[2025-12-12T20:15:08.830Z] jdk_security4_1 Start Time: Fri Dec 12 12:15:08 2025 Epoch Time (ms): 1765570508373
[2025-12-12T20:15:08.830Z] variation: Mode650
[2025-12-12T20:15:09.320Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-12-12T20:56:31.773Z] TEST: sun/security/krb5/auto/Renewal.java

[2025-12-12T20:56:31.786Z] STDERR:
[2025-12-12T20:56:31.786Z] java.lang.Exception: Timestamp is Fri Dec 12 13:25:38 PST 2025, actual difference 1759 is not 1800
[2025-12-12T20:56:31.786Z] 	at Renewal.checkRough(Renewal.java:166)
[2025-12-12T20:56:31.786Z] 	at Renewal.checkKinit(Renewal.java:112)
[2025-12-12T20:56:31.786Z] 	at Renewal.main(Renewal.java:75)
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_testList_8/76/)
```
[2026-03-26T17:25:01.126Z] Running test jdk_security4_0 ...
[2026-03-26T17:25:02.381Z] ===============================================
[2026-03-26T17:25:02.381Z] jdk_security4_0 Start Time: Thu Mar 26 10:25:01 2026 Epoch Time (ms): 1774545901782
[2026-03-26T17:25:03.274Z] variation: Mode150
[2026-03-26T17:25:03.274Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2026-03-26T18:16:53.744Z] TEST: sun/security/krb5/auto/Renewal.java

[2026-03-26T18:16:53.760Z] STDERR:
[2026-03-26T18:16:53.760Z] java.lang.Exception: Timestamp is Thu Mar 26 12:16:01 PDT 2026, actual difference 3556 is not 3600
[2026-03-26T18:16:53.760Z] 	at Renewal.checkRough(Renewal.java:166)
[2026-03-26T18:16:53.760Z] 	at Renewal.checkKinit(Renewal.java:112)
[2026-03-26T18:16:53.760Z] 	at Renewal.main(Renewal.java:73)
```
