### ISSUE TITLE
OpenJDK sun/security/krb5/auto/Unreachable - PortUnreachableException not thrown

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17743]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0/3
jdk_security4_0
sun/security/krb5/auto/Unreachable.java
```
06:12:11  java.lang.RuntimeException: PortUnreachableException not thrown.
06:12:11  	at Unreachable.main(Unreachable.java:102)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0/13/consoleFull
```
05:36:12  variation: Mode150
05:36:12  JVM_OPTIONS:  -XX:+UseCompressedOops 

06:31:51  STDERR:
06:31:51  java.lang.RuntimeException: PortUnreachableException not thrown.
06:31:51  	at Unreachable.main(Unreachable.java:102)
06:31:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:31:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:31:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:31:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:31:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:31:51  	at java.base/java.lang.Thread.run(Thread.java:839)
06:31:51  
06:31:51  JavaTest Message: Test threw exception: java.lang.RuntimeException: PortUnreachableException not thrown.

06:36:50  Test results: passed: 140; failed: 1
06:36:53  Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_16894018809879\jdk_security4_0\report\html\report.html
06:36:53  Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_16894018809879\jdk_security4_0\work
06:36:53  Error: Some tests failed or other problems occurred.
06:36:53  -----------------------------------
06:36:53  jdk_security4_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK11 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_1/465/)(`win10x86-svl-rt2-1`)
```
[2024-05-18T04:01:17.419Z] variation: Mode650
[2024-05-18T04:01:18.338Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-05-18T04:49:32.672Z] TEST: sun/security/krb5/auto/Unreachable.java

[2024-05-18T04:49:32.673Z] STDERR:
[2024-05-18T04:49:32.673Z] java.lang.RuntimeException: PortUnreachableException not thrown.
[2024-05-18T04:49:32.673Z] 	at Unreachable.main(Unreachable.java:102)

[2024-05-18T05:00:15.566Z] jdk_security4_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Release_testList_0/52/ - [win2019-x64-3](https://openj9-jenkins.osuosl.org/computer/win2019-x64-3)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_2/281/consoleFull)
```
19:17:54  Running test jdk_security4_1 ...
19:17:54  ===============================================
19:17:55  jdk_security4_1 Start Time: Tue Sep 16 16:17:54 2025 Epoch Time (ms): 1758064674246
19:17:55  variation: Mode650
19:17:57  JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

20:16:51  TEST: sun/security/krb5/auto/Unreachable.java

20:16:51  java.lang.RuntimeException: PortUnreachableException not thrown.
20:16:51  	at Unreachable.main(Unreachable.java:102)
```
