### ISSUE TITLE
testJITServer testServerUnreachableForAWhile - Unable to pause target process, pkill failed or did not match any process

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17745]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_ppc64le_linux_Nightly_testList_0/4/
testJITServer_1
```
FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: Unable to pause target process, pkill failed or did not match any process. expected:<0> but was:<1>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at jit.test.jitserver.JITServerTest.pauseProcessWithCommandLine(JITServerTest.java:394)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:528)
```

**Comment by pshipton** [comment]
@mpirvu fyi

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/765
testJITServer_1
```
21:32:29  FAILED: testServerUnreachableForAWhile
21:32:29  java.lang.AssertionError: Unable to pause target process, pkill failed or did not match any process. expected:<0> but was:<1>
21:32:29  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
21:32:29  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
21:32:29  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
21:32:29  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
21:32:29  	at jit.test.jitserver.JITServerTest.pauseProcessWithCommandLine(JITServerTest.java:395)
21:32:29  	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:529)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/1024/

**Comment by mpirvu** [comment]
I started a 50x grinder on plinux with a nightly build that has the fix from #21682

**Comment by mpirvu** [comment]
The grinder above failed 1/50, but the failure is a timeout, so a different symptom than the one described in this issue:
https://openj9-jenkins.osuosl.org/job/Grinder/4303
```
19:35:00  /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17454509943811/testJITServer_1/testServerGoesDown.client.out
19:35:02  [JITServerTest] [INFO] Waiting for 45000 millis.
19:35:49  [JITServerTest] [INFO] Stopping server...
19:35:49  [JITServerTest] [INFO] Waiting for 45000 millis.
19:36:24  Cancelling nested steps due to timeout
19:36:24  Sending interrupt signal to process
19:36:28  make[4]: *** [autoGen.mk:31: testJITServer_1] Error 143
19:36:28  make[4]: Leaving directory '/home/jenkins/workspace/Grinder/aqa-tests/functional/JIT_Test'
```

**Comment by pshipton** [comment]
I assume it's fixed until it's seen again.
