### ISSUE TITLE
OpenJDK java/security/KeyRep/Serial - SecurityException: PBE test failed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17746]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_OMR_testList_0/3
jdk_security1_1
java/security/KeyRep/Serial.java
```
06:03:26  java.lang.SecurityException: PBE test failed
06:03:26  	at Serial.main(Serial.java:168)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/52
jdk_security1_1
java/security/KeyRep/Serial.java
```
04:46:50  java.lang.SecurityException: DES test failed
04:46:50  	at Serial.checkKey(Serial.java:200)
04:46:50  	at Serial.main(Serial.java:173)
```

**Comment by JasonFengJ9** [comment]
[JDK8 x86-32_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_testList_0/381/)(`win22x86-svl-rt6-1`)
```
openjdk version "1.8.0_392"
IBM Semeru Runtime Open Edition (build 1.8.0_392-b08)
Eclipse OpenJ9 VM (build v0.41.0-release-a803f004b, JRE 1.8.0 Windows Server 2022 x86-32-Bit 20231116_790 (JIT enabled, AOT enabled)
OpenJ9   - a803f004b
OMR      - 5eee6ad9d
JCL      - b73cbdd342 based on jdk8u392-b08)

[2023-11-16T07:25:25.633Z] variation: Mode1000
[2023-11-16T07:25:26.265Z] JVM_OPTIONS:  

[2023-11-16T07:26:31.634Z] TEST: java/security/KeyRep/Serial.java

[2023-11-16T07:26:31.634Z] STDERR:
[2023-11-16T07:26:31.634Z] java.lang.SecurityException: PBE test failed
[2023-11-16T07:26:31.634Z] 	at Serial.main(Serial.java:168)
[2023-11-16T07:26:31.634Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-16T07:26:31.634Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-11-16T07:26:31.634Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-16T07:26:31.634Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-11-16T07:26:31.634Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-11-16T07:26:31.634Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-11-16T07:26:31.634Z] 
[2023-11-16T07:26:31.634Z] JavaTest Message: Test threw exception: java.lang.SecurityException: PBE test failed
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36193/)

**Comment by JasonFengJ9** [comment]
[JDK8 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_testList_1/539/)(`ubu20-aarch64-4`)
```
[2024-03-16T03:31:09.737Z] variation: Mode650
[2024-03-16T03:31:09.737Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-16T03:31:40.494Z] TEST: java/security/KeyRep/Serial.java

[2024-03-16T03:31:40.495Z] STDERR:
[2024-03-16T03:31:40.495Z] java.lang.SecurityException: PBE test failed
[2024-03-16T03:31:40.495Z] 	at Serial.main(Serial.java:168)
[2024-03-16T03:31:40.495Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-03-16T03:31:40.495Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-03-16T03:31:40.495Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-03-16T03:31:40.495Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-03-16T03:31:40.495Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-03-16T03:31:40.495Z] 	at java.lang.Thread.run(Thread.java:826)
[2024-03-16T03:31:40.495Z] 
[2024-03-16T03:31:40.495Z] JavaTest Message: Test threw exception: java.lang.SecurityException: PBE test failed

[2024-03-16T03:34:56.194Z] jdk_security1_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Release_testList_1/14
jdk_security1_1
java/security/KeyRep/Serial.java
```
19:33:05  java.lang.SecurityException: DESede test failed
19:33:05  	at Serial.checkKey(Serial.java:200)
19:33:05  	at Serial.main(Serial.java:174)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/367

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_OpenJDK8_testList_1/27

**Comment by taoliult** [comment]
The test case `java/security/KeyRep/Serial.java.Serial` is quite simple, It simply retrieves a PBEWithMD5AndDES, DES, DESede, etc. key generator from SunJCE, generate the secret key, serialize it and deserialize it, and then compare the deserialized one with the original one.

I rerun this tests serval times using the same build in Grinder, links below, they all look good. I think it just an environment related issue happens intermittently.

https://openj9-jenkins.osuosl.org/job/Grinder/4113/
https://openj9-jenkins.osuosl.org/job/Grinder/4114/
https://openj9-jenkins.osuosl.org/job/Grinder/4115/
https://openj9-jenkins.osuosl.org/job/Grinder/4116/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_Nightly_testList_2/293
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Release_testList_1/33 - 0.51
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/323
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/648

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_sanity.openjdk_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/1169/)
```
[2026-01-26T15:21:03.106Z] Running test jdk_security1_1 ...
[2026-01-26T15:21:03.106Z] ===============================================
[2026-01-26T15:21:03.106Z] jdk_security1_1 Start Time: Mon Jan 26 07:20:57 2026 Epoch Time (ms): 1769440857282
[2026-01-26T15:21:03.106Z] variation: Mode650
[2026-01-26T15:21:03.106Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2026-01-26T15:21:22.031Z] TEST: java/security/KeyRep/Serial.java

[2026-01-26T15:21:22.033Z] java.lang.SecurityException: PBE test failed
[2026-01-26T15:21:22.033Z] 	at Serial.main(Serial.java:168)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Release_testList_0/97/
jdk_security1_0 
java/security/KeyRep/Serial.java
```
19:37:41  java.lang.SecurityException: DES test failed
19:37:41  	at Serial.checkKey(Serial.java:200)
19:37:41  	at Serial.main(Serial.java:173)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_3/35
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/774
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_3/78
