### ISSUE TITLE
threadMXBeanTestSuite2 testSleepingThread expected [PASS] but found [FAIL]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17752]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Release_testList_1/60
threadMXBeanTestSuite2_3 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`
```
FAILED: testSleepingThread
java.lang.AssertionError: expected [PASS] but found [FAIL]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:442)
	at org.openj9.test.java.lang.management.ThreadMXBean.SleepingThread.testSleepingThread(SleepingThread.java:35)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/35 - [rh7-390-4](https://openj9-jenkins.osuosl.org/computer/rh7-390-4)
threadMXBeanTestSuite2_0 `-Xjit -Xgcpolicy:gencon -Xnocompressedrefs `
```
FAILED: testSleepingThread
java.lang.AssertionError: expected [PASS] but found [FAIL]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:442)
	at org.openj9.test.java.lang.management.ThreadMXBean.SleepingThread.testSleepingThread(SleepingThread.java:35)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/655/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_aot_Personal_testList_1/234/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly/754

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Release_testList_1/25

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_extended.functional_s390x_linux_Nightly_testList_1/111

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/403

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/769
threadMXBeanTestSuite2_6 - [ub20-390-1](https://openj9-jenkins.osuosl.org/computer/ub20-390-1)
`-Xjit -Xgcpolicy:gencon -Xnocompressedrefs -XX:+GuardPageOnJavaStack`
```
21:45:00  FAILED: testSleepingThread
21:45:00  java.lang.AssertionError: expected [PASS] but found [FAIL]
21:45:00  	at org.testng.Assert.fail(Assert.java:96)
21:45:00  	at org.testng.Assert.failNotEquals(Assert.java:776)
21:45:00  	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
21:45:00  	at org.testng.Assert.assertEquals(Assert.java:118)
21:45:00  	at org.testng.Assert.assertEquals(Assert.java:442)
21:45:00  	at org.openj9.test.java.lang.management.ThreadMXBean.SleepingThread.testSleepingThread(SleepingThread.java:35)
```
```
	/*
	 * Tests that sleeping thread state is reported as TIMED_WAITING
	 */
	ExitStatus testThread() {
		logger.debug("testThread");
		
		ExitStatus rc = ExitStatus.PASS;
		ThreadMXBean mxb = ManagementFactory.getThreadMXBean();
		
		Thread sleeper = new Thread("sleeper") {
			public void run() {
				try {
					Thread.sleep(5 * 60 * 1000);
				} catch (InterruptedException e) {
				}
			}
		};
		sleeper.start();

		try {
			Thread.sleep(1000);
		} catch (InterruptedException e1) {
			e1.printStackTrace();
		}
		ThreadInfo ti = mxb.getThreadInfo(sleeper.getId(), 8);
		
		if ((ti.getThreadState() != Thread.State.TIMED_WAITING)
			|| (ti.getLockOwnerName() != null) || (ti.getLockName() != null)) {
			printThreadInfo(ti);
			rc = ExitStatus.FAIL;   <------ failure point
		}
		sleeper.interrupt();
		try {
			sleeper.join();
		} catch (InterruptedException e) {
		}
		
		return rc;
	}
}
```
