### ISSUE TITLE
OpenJDK ClassLoader/loadLibraryDeadlock/TestLoadLibraryDeadlock - Unable to load signed jar

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17753]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_Release_testList_0/1/
jdk_lang_0
java/lang/ClassLoader/loadLibraryDeadlock/TestLoadLibraryDeadlock.java
```
18:18:57  COMMAND: /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_Release_testList_0/openjdkbinary/j2sdk-image/bin/jarsigner -keystore keystore.jks -storepass changeit c.jar test
18:18:57  [2023-07-02T22:12:08.735301Z] Gathering output for process 34603268
18:18:57  [2023-07-02T22:12:10.095512Z] Waiting for completion for process 34603268
18:18:57  [2023-07-02T22:12:10.095703Z] Waiting for completion finished for process 34603268
18:18:57  Output and diagnostic info for process 34603268 was saved into 'pid-34603268-output.log'
18:18:57  [2023-07-02T22:12:10.101322Z] Waiting for completion for process 34603268
18:18:57  [2023-07-02T22:12:10.101460Z] Waiting for completion finished for process 34603268
18:18:57  COMMAND: /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_Release_testList_0/openjdkbinary/j2sdk-image/bin/java -cp a.jar:b.jar:c.jar -Djava.library.path=/home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_Release_testList_0/openjdkbinary/openjdk-test-image/jdk/jtreg/native LoadLibraryDeadlock
18:18:57  Native library loaded.Native library loaded.
18:18:57  COMMAND: /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_Release_testList_0/openjdkbinary/j2sdk-image/bin/jcmd 57082210 Thread.print
18:18:57  [2023-07-02T22:12:30.562197Z] Gathering output for process 34603270
18:18:57  [2023-07-02T22:12:31.577123Z] Waiting for completion for process 34603270
18:18:57  [2023-07-02T22:12:31.577241Z] Waiting for completion finished for process 34603270
18:18:57  Output and diagnostic info for process 34603270 was saved into 'pid-34603270-output.log'
18:18:57  Usage : jcmd <vmid> <arguments>
18:18:57  
18:18:57     -J : supply arguments to the Java VM running jcmd
18:18:57     -l : list JVM processes on the local machine
18:18:57     -h : print this help message
18:18:57  
18:18:57     <vmid> : Attach API VM ID as shown in jps or other Attach API-based tools
18:18:57  
18:18:57     arguments:
18:18:57        help : print the list of diagnostic commands
18:18:57        help <command> : print help for the specific command
18:18:57        <command> [command arguments] : command from the list returned by "help"
18:18:57  
18:18:57  list JVM processes on the local machine. Default behavior when no options are specified.
18:18:57  
18:18:57  NOTE: this utility might significantly affect the performance of the target JVM.
18:18:57      The available diagnostic commands are determined by
18:18:57      the target VM and may vary between VMs.
18:18:57  Error getting data from 57082210: Exception connecting to 57082210
18:18:57  STDERR:
18:18:57  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
18:18:57  java.lang.RuntimeException: Unable to load signed jar.: expected true, was false
18:18:57  	at jdk.test.lib.Asserts.fail(Asserts.java:594)
18:18:57  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
18:18:57  	at TestLoadLibraryDeadlock.main(TestLoadLibraryDeadlock.java:233)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/14/
jdk_lang_1
java/lang/ClassLoader/loadLibraryDeadlock/TestLoadLibraryDeadlock.java
```
13:04:55  [2023-08-24T17:04:26.911276562Z] Gathering output for process 3577585
13:04:55  [2023-08-24T17:04:33.471136957Z] Waiting for completion for process 3577585
13:04:55  [2023-08-24T17:04:33.471339645Z] Waiting for completion finished for process 3577585
13:04:55  Output and diagnostic info for process 3577585 was saved into 'pid-3577585-output.log'
13:04:55  [2023-08-24T17:04:33.471796982Z] Waiting for completion for process 3577585
13:04:55  [2023-08-24T17:04:33.471857440Z] Waiting for completion finished for process 3577585
13:04:55  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/openjdkbinary/j2sdk-image/bin/java -cp a.jar:b.jar:c.jar -Djava.library.path=/home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/openjdkbinary/openjdk-test-image/jdk/jtreg/native LoadLibraryDeadlock
13:04:55  
13:04:55  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/openjdkbinary/j2sdk-image/bin/jcmd 3577693 Thread.print
13:04:55  [2023-08-24T17:04:40.853652784Z] Gathering output for process 3577733
13:04:55  [2023-08-24T17:04:45.644725002Z] Waiting for completion for process 3577733
13:04:55  [2023-08-24T17:04:45.644931191Z] Waiting for completion finished for process 3577733
13:04:55  Output and diagnostic info for process 3577733 was saved into 'pid-3577733-output.log'
13:04:55  Usage : jcmd <vmid> <arguments>
13:04:55  
13:04:55     -J : supply arguments to the Java VM running jcmd
13:04:55     -l : list JVM processes on the local machine
13:04:55     -h : print this help message
13:04:55  
13:04:55     <vmid> : Attach API VM ID as shown in jps or other Attach API-based tools
13:04:55  
13:04:55     arguments:
13:04:55        help : print the list of diagnostic commands
13:04:55        help <command> : print help for the specific command
13:04:55        <command> [command arguments] : command from the list returned by "help"
13:04:55  
13:04:55  list JVM processes on the local machine. Default behavior when no options are specified.
13:04:55  
13:04:55  NOTE: this utility might significantly affect the performance of the target JVM.
13:04:55      The available diagnostic commands are determined by
13:04:55      the target VM and may vary between VMs.
13:04:55  Error getting data from 3577693: Exception connecting to 3577693
13:04:55  STDERR:
13:04:55  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
13:04:55  java.lang.RuntimeException: Unable to load native library.: expected true, was false
13:04:55  	at jdk.test.lib.Asserts.fail(Asserts.java:594)
13:04:55  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
13:04:55  	at TestLoadLibraryDeadlock.main(TestLoadLibraryDeadlock.java:229)
13:04:55  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
13:04:55  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
13:04:55  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
13:04:55  	at java.base/java.lang.Thread.run(Thread.java:1595)
13:04:55  
13:04:55  JavaTest Message: Test threw exception: java.lang.RuntimeException: Unable to load native library.: expected true, was false
13:04:55  JavaTest Message: shutting down test
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/196
jdk_lang_1
java/lang/ClassLoader/loadLibraryDeadlock/TestLoadLibraryDeadlock.java
```
18:46:51  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/jdkbinary/j2sdk-image/bin/java -cp a.jar:b.jar:c.jar -Djava.library.path=/home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/jdkbinary/openjdk-test-image/jdk/jtreg/native LoadLibraryDeadlock
18:46:51  
18:46:51  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/jdkbinary/j2sdk-image/bin/jcmd 446965 Thread.print
18:46:51  [2024-04-01T22:46:22.625714069Z] Gathering output for process 446975
18:46:51  [2024-04-01T22:46:38.045448352Z] Waiting for completion for process 446975
18:46:51  [2024-04-01T22:46:38.045713872Z] Waiting for completion finished for process 446975
18:46:51  Output and diagnostic info for process 446975 was saved into 'pid-446975-output.log'
18:46:51  
18:46:51  STDERR:
18:46:51  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
18:46:51  java.lang.RuntimeException: Unable to load native library.: expected true, was false
18:46:51  	at jdk.test.lib.Asserts.fail(Asserts.java:594)
18:46:51  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
18:46:51  	at TestLoadLibraryDeadlock.main(TestLoadLibraryDeadlock.java:229)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/190
jdk_lang_0
java/lang/ClassLoader/loadLibraryDeadlock/TestLoadLibraryDeadlock.java
```
19:19:12  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unable to load native library.: expected true, was false
19:19:12  REASON: User specified action: run main/othervm/native -Xcheck:jni TestLoadLibraryDeadlock 
19:19:12  TIME:   812.579 seconds
19:19:12  messages:
19:19:12  command: main -Xcheck:jni TestLoadLibraryDeadlock
19:19:12  reason: User specified action: run main/othervm/native -Xcheck:jni TestLoadLibraryDeadlock 
19:19:12  started: Fri Apr 26 22:52:30 UTC 2024
19:19:12  Mode: othervm [/othervm specified]
19:19:12  finished: Fri Apr 26 23:06:03 UTC 2024
19:19:12  elapsed time (seconds): 812.579
19:19:12  configuration:
19:19:12  STDOUT:
19:19:12  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/jdkbinary/j2sdk-image/bin/keytool -storepass changeit -keypass changeit -keystore keystore.jks -keyalg rsa -keysize 2048 -genkeypair -alias test -dname CN=test -validity 366
19:19:12  [2024-04-26T22:52:31.963202Z] Gathering output for process 30999036
19:19:12  [2024-04-26T22:52:35.170943Z] Waiting for completion for process 30999036
19:19:12  [2024-04-26T22:52:35.171177Z] Waiting for completion finished for process 30999036
19:19:12  Output and diagnostic info for process 30999036 was saved into 'pid-30999036-output.log'
19:19:12  [2024-04-26T22:52:35.177507Z] Waiting for completion for process 30999036
19:19:12  [2024-04-26T22:52:35.177673Z] Waiting for completion finished for process 30999036
19:19:12  added manifest
19:19:12  adding: LoadLibraryDeadlock.class(in = 650) (out= 430)(deflated 33%)
19:19:12  adding: LoadLibraryDeadlock$1.class(in = 1035) (out= 610)(deflated 41%)
19:19:12  adding: LoadLibraryDeadlock$2.class(in = 881) (out= 549)(deflated 37%)
19:19:12  added manifest
19:19:12  adding: Class1.class(in = 481) (out= 330)(deflated 31%)
19:19:12  added manifest
19:19:12  adding: p/Class2.class(in = 188) (out= 158)(deflated 15%)
19:19:12  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/jdkbinary/j2sdk-image/bin/jarsigner -keystore keystore.jks -storepass changeit c.jar test
19:19:12  [2024-04-26T22:52:35.359237Z] Gathering output for process 30999038
19:19:12  [2024-04-26T22:52:36.812367Z] Waiting for completion for process 30999038
19:19:12  [2024-04-26T22:52:36.812757Z] Waiting for completion finished for process 30999038
19:19:12  Output and diagnostic info for process 30999038 was saved into 'pid-30999038-output.log'
19:19:12  [2024-04-26T22:52:36.813638Z] Waiting for completion for process 30999038
19:19:12  [2024-04-26T22:52:36.813744Z] Waiting for completion finished for process 30999038
19:19:12  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java -cp a.jar:b.jar:c.jar -Djava.library.path=/home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/jdkbinary/openjdk-test-image/jdk/jtreg/native LoadLibraryDeadlock
19:19:12  
19:19:12  COMMAND: /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/jdkbinary/j2sdk-image/bin/jcmd 58065222 Thread.print
19:19:12  [2024-04-26T22:53:36.919221Z] Gathering output for process 61800838
19:19:12  [2024-04-26T23:06:03.080807Z] Waiting for completion for process 61800838
19:19:12  [2024-04-26T23:06:03.081063Z] Waiting for completion finished for process 61800838
19:19:12  Output and diagnostic info for process 61800838 was saved into 'pid-61800838-output.log'
19:19:12  Usage : jcmd <vmid | display name | 0> <arguments>
19:19:12  
19:19:12     -J : supply arguments to the Java VM running jcmd
19:19:12     -l : list JVM processes on the local machine
19:19:12     -h : print this help message
19:19:12  
19:19:12     <vmid> : Attach API VM ID as shown in jcmd or other Attach API-based tools
19:19:12     <display name> : this argument is used to match (either fully or partially) the display name as shown in jcmd or other Attach API-based tools
19:19:12     <0> : the jcmd command will be sent to all Java processes detected by this utility
19:19:12  
19:19:12     arguments:
19:19:12        help : print the list of diagnostic commands
19:19:12        help <command> : print help for the specific command
19:19:12        <command> [command arguments] : command from the list returned by "help"
19:19:12  
19:19:12  list JVM processes on the local machine. Default behavior when no options are specified.
19:19:12  
19:19:12  NOTE: this utility might significantly affect the performance of the target JVM.
19:19:12      The available diagnostic commands are determined by
19:19:12      the target VM and may vary between VMs.
19:19:12  Error getting data from 58065222: Exception connecting to 58065222
19:19:12  STDERR:
19:19:12  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
19:19:12  java.lang.RuntimeException: Unable to load native library.: expected true, was false
19:19:12  	at jdk.test.lib.Asserts.fail(Asserts.java:594)
19:19:12  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
19:19:12  	at TestLoadLibraryDeadlock.main(TestLoadLibraryDeadlock.java:229)
19:19:12  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
19:19:12  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
19:19:12  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
19:19:12  	at java.base/java.lang.Thread.run(Thread.java:1595)
```
