### ISSUE TITLE
mauve Segmentation fault

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17750]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=63460270)
[Linux S390] 80 Load_Level_2.mauve.5mins.Mode103 - lnxec409

80x grinder passed
```
j> 13:11:36 20230706 13:11:36 Thread Control Engine INFO: Starting JobSet Primary
p> 20230706-13:11:49 Dump /tmp/bld_54013/mauve.5mins/63460270/JLTF-mauve-mode103-20230706-1311/core.17268 spotted.
```
```
p> 20230706-13:12:07 <gdb> Core was generated by `/j9vm/ascii/builds/bld_54013/sdk/xz3180/jre/bin/java -Xmx512M -Xms4M -Xnocompre'.
p> 20230706-13:12:07 <gdb> Program terminated with signal 11, Segmentation fault.
p> 20230706-13:12:07 <gdb> #0  0x00000000 in ?? ()
p> 20230706-13:12:07 <gdb> => 0x00000000:	Cannot access memory at address 0x0
p> 20230706-13:12:07 <gdb> 
p> 20230706-13:12:07 <gdb> backtrace:
p> 20230706-13:12:07 <gdb> #0  0x00000000 in ?? ()
p> 20230706-13:12:07 <gdb> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by gacholio** [comment]
Likely a call to 0. Look in the link register and I suspect you'll find it's compiled code (the only place likely to end up with an unpatched call instruction).
