### ISSUE TITLE
NullPointerExceptions seen in SpinedBufferTest

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#17774]
NullPointerExceptions are seen in SpinedBufferTest.
java/util/stream/boottest/java.base/java/util/stream/SpinedBufferTest.java

This failure was first noticed in the JDK11 Linux aarch64 sanity.openjdk PR build for #17732.

This failure is highly intermittent; it happens once in 200 runs

Grinders were run to confirm that this failure didn't happen due to #17732.
- 200x grinder with #17732: https://openj9-jenkins.osuosl.org/job/Grinder/2573
- 300x grinder without #17732: https://openj9-jenkins.osuosl.org/job/Grinder/2574

The failure happened once in both the grinders; this suggests that the failure is unrelated #17732. See https://github.com/eclipse-openj9/openj9/pull/17732#issuecomment-1630037418 for more details.

### Stacktrace

```
06:57:59  STDOUT:
06:57:59  test java.util.stream.SpinedBufferTest.testDoubleSpinedBuffer(): success
06:57:59  test java.util.stream.SpinedBufferTest.testDoubleSpliterator([D@b999a348, OfDouble[length=0, chunks=0][]): success
06:57:59  test java.util.stream.SpinedBufferTest.testDoubleSpliterator([D@d961a48d, java.util.stream.SpinedBuffer$OfDouble@982de11): success
...
06:57:59  ...
06:57:59  Output overflow:
06:57:59  JT Harness has limited the test output to the text
06:57:59  at the beginning and the end, so that you can see how the
06:57:59  test began, and how it completed.
06:57:59  
06:57:59  If you need to see more of the output from the test,
06:57:59  set the system property javatest.maxOutputSize to a higher
06:57:59  value. The current value is 100000
06:57:59  ...
06:57:59 
06:57:59  r.java:174)
06:57:59  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
06:57:59  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
06:57:59  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
06:57:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
06:57:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
06:57:59  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
06:57:59  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
06:57:59  	at org.testng.TestRunner.run(TestRunner.java:585)
06:57:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
06:57:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
06:57:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
06:57:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
06:57:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
06:57:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
06:57:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
06:57:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
06:57:59  	at org.testng.TestNG.runSuites(TestNG.java:1069)
06:57:59  	at org.testng.TestNG.run(TestNG.java:1037)
06:57:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
06:57:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
06:57:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:57:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:57:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:57:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:57:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:57:59  	at java.base/java.lang.Thread.run(Thread.java:839)
06:57:59  test java.util.stream.SpinedBufferTest.testSpliterator([I@962b42dc, java.util.stream.SpinedBuffer@fa27e51e): failure
06:57:59  java.lang.NullPointerException
06:57:59  	at java.base/java.lang.String.charAt(String.java:1319)
06:57:59  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:57:59  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:57:59  	at java.base/java.lang.String.format(String.java:3728)
06:57:59  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:578)
06:57:59  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:529)
06:57:59  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:167)
06:57:59  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:53)
06:57:59  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:48)
06:57:59  	at java.base/java.util.stream.SpinedBufferTest.testSpliterator(SpinedBufferTest.java:92)
06:57:59  	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
06:57:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:57:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:57:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
06:57:59  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
06:57:59  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
06:57:59  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
06:57:59  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
06:57:59  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
06:57:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
06:57:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
06:57:59  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
06:57:59  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
06:57:59  	at org.testng.TestRunner.run(TestRunner.java:585)
06:57:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
06:57:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
06:57:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
06:57:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
06:57:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
06:57:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
06:57:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
06:57:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
06:57:59  	at org.testng.TestNG.runSuites(TestNG.java:1069)
06:57:59  	at org.testng.TestNG.run(TestNG.java:1037)
06:57:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
06:57:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
06:57:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:57:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:57:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:57:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:57:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:57:59  	at java.base/java.lang.Thread.run(Thread.java:839)
06:57:59  test java.util.stream.SpinedBufferTest.testSpliterator([I@e31e2fee, java.util.stream.SpinedBuffer@509e3588): failure
06:57:59  java.lang.NullPointerException
06:57:59  	at java.base/java.lang.String.charAt(String.java:1319)
06:57:59  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:57:59  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:57:59  	at java.base/java.lang.String.format(String.java:3728)
...
06:57:59  test java.util.stream.SpinedBufferTest.testSpliterator([I@e31e2fee, java.util.stream.SpinedBuffer@9c9ca5b5): failure
06:57:59  java.lang.NullPointerException
06:57:59  	at java.base/java.lang.String.charAt(String.java:1319)
06:57:59  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:57:59  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:57:59  	at java.base/java.lang.String.format(String.java:3728)
...
06:57:59  test java.util.stream.SpinedBufferTest.testSpliterator([I@e31e2fee, java.util.stream.SpinedBuffer@8f5432): failure
06:57:59  java.lang.NullPointerException
06:57:59  	at java.base/java.lang.String.charAt(String.java:1319)
06:57:59  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:57:59  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:57:59  	at java.base/java.lang.String.format(String.java:3728)
...
06:57:59  test java.util.stream.SpinedBufferTest.testSpliterator([I@e31e2fee, java.util.stream.SpinedBuffer@be114f3b): failure
06:57:59  java.lang.NullPointerException
06:57:59  	at java.base/java.lang.String.charAt(String.java:1319)
06:57:59  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:57:59  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:57:59  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:57:59  	at java.base/java.lang.String.format(String.java:3728)
...
```

**Comment by pshipton** [comment]
@knn-k fyi, not sure if this is specific to aarch64.

**Comment by knn-k** [comment]
```
java.lang.NullPointerException
	at java.base/java.lang.String.charAt(String.java:1319)
```

The `charAt()` code looks as follows:

```
1318:	public char charAt(int index) {
1319:		if (0 <= index && index < lengthInternal()) {
1320:			// Check if the String is compressed
```

The call to `lengthInternal()` is the only element in L.1319 that could throw NPE.  If that is the case, it may mean `this` was a null.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/26
java_util_0
java/util/stream/boottest/java.base/java/util/stream/SpinedBufferTest.java

https://github.com/eclipse-openj9/openj9/issues/17922 happened in the same run, seems like a dup of this.
```
22:01:11  Output overflow:
22:01:11  JT Harness has limited the test output to the text
22:01:11  at the beginning and the end, so that you can see how the
22:01:11  test began, and how it completed.
22:01:11  
22:01:11  If you need to see more of the output from the test,
22:01:11  set the system property javatest.maxOutputSize to a higher
22:01:11  value. The current value is 100000
22:01:11  ...
22:01:11  
22:01:11  lect.Method.invoke(Method.java:566)
22:01:11  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:01:11  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:01:11  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:01:11  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:01:11  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:01:11  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:01:11  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:01:11  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:01:11  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
22:01:11  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
22:01:11  	at org.testng.TestRunner.run(TestRunner.java:585)
22:01:11  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:01:11  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:01:11  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:01:11  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:01:11  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:01:11  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:01:11  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:01:11  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:01:11  	at org.testng.TestNG.runSuites(TestNG.java:1069)
22:01:11  	at org.testng.TestNG.run(TestNG.java:1037)
22:01:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:01:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:01:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:01:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:01:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:01:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:01:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:01:11  	at java.base/java.lang.Thread.run(Thread.java:839)
22:01:11  test java.util.stream.SpinedBufferTest.testSpliterator([I@15e81408, java.util.stream.SpinedBuffer@fcd206de): failure
22:01:11  java.lang.NullPointerException
22:01:11  	at java.base/java.lang.String.charAt(String.java:1319)
22:01:11  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
22:01:11  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
22:01:11  	at java.base/java.util.Formatter.format(Formatter.java:2655)
22:01:11  	at java.base/java.util.Formatter.format(Formatter.java:2609)
22:01:11  	at java.base/java.lang.String.format(String.java:3728)
22:01:11  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:578)
22:01:11  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:529)
22:01:11  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:167)
22:01:11  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:53)
22:01:11  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:48)
22:01:11  	at java.base/java.util.stream.SpinedBufferTest.testSpliterator(SpinedBufferTest.java:92)
22:01:11  	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
22:01:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:01:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:01:11  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:01:11  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:01:11  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:01:11  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:01:11  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:01:11  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:01:11  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:01:11  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:01:11  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
22:01:11  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
22:01:11  	at org.testng.TestRunner.run(TestRunner.java:585)
22:01:11  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:01:11  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:01:11  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:01:11  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:01:11  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:01:11  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:01:11  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:01:11  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:01:11  	at org.testng.TestNG.runSuites(TestNG.java:1069)
22:01:11  	at org.testng.TestNG.run(TestNG.java:1037)
22:01:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:01:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:01:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:01:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:01:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:01:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:01:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:01:11  	at java.base/java.lang.Thread.run(Thread.java:839)

etc.
'''

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/21

**Comment by knn-k** [comment]
From the job above:

```
[2023-08-24T10:00:12.191Z] TEST: java/util/stream/boottest/java.base/java/util/stream/SpinedBufferTest.java
[2023-08-24T10:00:12.191Z] TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/openjdkbinary/j2sdk-image

[2023-08-24T10:00:12.195Z] test java.util.stream.SpinedBufferTest.testSpliterator([I@54604ca5, java.util.stream.SpinedBuffer@6047c28): failure
[2023-08-24T10:00:12.195Z] java.lang.NullPointerException
[2023-08-24T10:00:12.195Z] 	at java.base/java.lang.String.charAt(String.java:1319)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.Formatter.parse(Formatter.java:2708)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.Formatter.format(Formatter.java:2655)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.Formatter.format(Formatter.java:2609)
[2023-08-24T10:00:12.195Z] 	at java.base/java.lang.String.format(String.java:3728)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:578)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:529)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:167)
[2023-08-24T10:00:12.195Z] 	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:53)
```

**Comment by pshipton** [comment]
Another failure, details in https://github.com/eclipse-openj9/openj9/issues/17922#issuecomment-1710336186

**Comment by pshipton** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Personal_testList_2/24) OMR acceptance

**Comment by knn-k** [comment]
NullPointerException in `String.charAt()` called by `Formatter.checkText()` is the same as #17992, which is caused by generalStoreSinking in JIT optimizer.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/53

**Comment by pshipton** [comment]
Close as a dup of https://github.com/eclipse-openj9/openj9/issues/17922
