### ISSUE TITLE
OpenJDK java/util/stream/StreamLinkTest StackOverflowError java.util.stream.ReferencePipeline$3$1.accept

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17775]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/9
jdk_util_0
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java

Perhaps related to https://github.com/eclipse-openj9/openj9/issues/14649

```
01:05:45  test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("ArrayList.asList:0..1000", java.util.stream.TestData$AbstractTestData$RefTestData@3d8c6d6b): failure
01:05:45  java.lang.AssertionError: 19 failure(s) for test data: RefTestData[ArrayList.asList:0..1000]
01:05:45  1: java.lang.Error: STREAM_TO_PAR_STREAM_COLLECT_TO_LIST: java.lang.StackOverflowError
01:05:45  java.lang.StackOverflowError
01:05:45  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
01:05:45  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
01:05:45  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
01:05:45  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
01:05:45  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
01:05:45  	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
01:05:45  	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
01:05:45  	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
01:05:45  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
01:05:45  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:238)
01:05:45  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
01:05:45  	at java.base/java.util.stream.StreamTestScenario$16.run(StreamTestScenario.java:199)
01:05:45  	at java.base/java.util.stream.StreamTestScenario.run(StreamTestScenario.java:272)
01:05:45  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:404)
01:05:45  	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
01:05:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:05:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
01:05:45  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:05:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
01:05:45  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
01:05:45  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
01:05:45  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
01:05:45  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
01:05:45  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
01:05:45  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
01:05:45  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
01:05:45  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
01:05:45  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
01:05:45  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
01:05:45  	at org.testng.TestRunner.run(TestRunner.java:585)
01:05:45  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
01:05:45  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
01:05:45  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
01:05:45  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
01:05:45  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
01:05:45  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
01:05:45  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
01:05:45  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
01:05:45  	at org.testng.TestNG.runSuites(TestNG.java:1069)
01:05:45  	at org.testng.TestNG.run(TestNG.java:1037)
01:05:45  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
01:05:45  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
01:05:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:05:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
01:05:45  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:05:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
01:05:45  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:05:45  	at java.base/java.lang.Thread.run(Thread.java:857)
01:05:45  Caused by: java.lang.StackOverflowError
01:05:45  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
01:05:45  	at java.base/java.util.st
01:05:45  
01:05:45  ...
01:05:45  Output overflow:
01:05:45  JT Harness has limited the test output to the text
01:05:45  at the beginning and the end, so that you can see how the
01:05:45  test began, and how it completed.
01:05:45  
01:05:45  If you need to see more of the output from the test,
01:05:45  set the system property javatest.maxOutputSize to a higher
01:05:45  value. The current value is 100000
01:05:45  ...
01:05:45  
01:05:45  peline$3$1.accept(ReferencePipeline.java:197)
01:05:45  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
01:05:45  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
...
01:05:45  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
01:05:45  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
01:05:45  	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
01:05:45  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
01:05:45  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
01:05:45  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
01:05:45  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
01:05:45  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
01:05:45  	at java.base/java.util.stream.Nodes$SizedCollectorTask.compute(Nodes.java:1878)
01:05:45  	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
01:05:45  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
01:05:45  	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
01:05:45  	at java.base/java.util.stream.Nodes.collect(Nodes.java:325)
01:05:45  	at java.base/java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:111)
01:05:45  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:583)
01:05:45  	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:265)
01:05:45  	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
01:05:45  	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
01:05:45  	at java.base/java.util.stream.StreamTestScenario$13.run(StreamTestScenario.java:163)
01:05:45  	at java.base/java.util.stream.StreamTestScenario.run(StreamTestScenario.java:272)
01:05:45  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:404)
01:05:45  	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
01:05:45  	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
01:05:45  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:05:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
01:05:45  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
01:05:45  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
01:05:45  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
01:05:45  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
01:05:45  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
01:05:45  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
01:05:45  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
01:05:45  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
01:05:45  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
01:05:45  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
01:05:45  	at org.testng.TestRunner.run(TestRunner.java:585)
01:05:45  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
01:05:45  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
01:05:45  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
01:05:45  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
01:05:45  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
01:05:45  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
01:05:45  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
01:05:45  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
01:05:45  	at org.testng.TestNG.runSuites(TestNG.java:1069)
01:05:45  	at org.testng.TestNG.run(TestNG.java:1037)
01:05:45  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
01:05:45  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
01:05:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:05:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
01:05:45  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:05:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
01:05:45  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:05:45  	at java.base/java.lang.Thread.run(Thread.java:857)

```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/362 - [cent9-ppc64le-7](https://openj9-jenkins.osuosl.org/computer/cent9-ppc64le-7)
jdk_util_0
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
```
20:03:53  test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("LinkedHashSet:0..1000", java.util.stream.TestData$AbstractTestData$RefTestData@825ac130): failure
20:03:53  java.lang.AssertionError: 19 failure(s) for test data: RefTestData[LinkedHashSet:0..1000]
20:03:53  1: java.lang.Error: STREAM_TO_PAR_STREAM_COLLECT_TO_LIST: java.lang.StackOverflowError
20:03:53  java.lang.StackOverflowError
20:03:53  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
20:03:53  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
20:03:53  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
20:03:53  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
...
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_OMR_testList_1/177
jdk_util_0
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
```
06:03:09  test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("ArrayList:0..1000", RefTestData[ArrayList:0..1000]): failure
06:03:09  java.lang.AssertionError: 5 failure(s) for test data: RefTestData[ArrayList:0..1000]
06:03:09  1: java.lang.Error: STREAM_FOR_EACH: java.lang.StackOverflowError
06:03:09  java.lang.StackOverflowError
06:03:09  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
06:03:09  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/273
jdk_util_0
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_OMR_testList_0/198
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/287
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/292
