### ISSUE TITLE
[FFI/Jtreg_JDK21] ArrayIndexOutOfBoundsException detected in TestArrayStructs.java

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17779]
The test suite at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/arraystructs/TestArrayStructs.java ended up with the following error:
```
test TestArrayStructs.testArrayStruct("F1", jdk.internal.foreign.FunctionDescriptorImpl@d29f4c4e, 0, 1): failure
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 372
        at java.base/java.lang.Byte.valueOf(Byte.java:147)
        at java.base/sun.invoke.util.ValueConversions.boxByte(ValueConversions.java:284)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.invokeNative(Native Method)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.runNativeMethod(InternalDowncallHandler.java:571)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at TestArrayStructs.testArrayStruct(TestArrayStructs.java:94)
```

FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
Looking at the test failure at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/73fae096864ca2a8ccd3a27ababa9b35997f7532/test/jdk/java/foreign/arraystructs/TestArrayStructs.java#L94
```
    // Test if structs of various different sizes, including non-powers of two, work correctly
    @Test(dataProvider = "arrayStructs")
    public void testArrayStruct(String functionName, FunctionDescriptor baseDesc, int numPrefixArgs, int numElements) throws Throwable {
....
            MethodHandle downcallHandle = downcallHandle(functionName, downcallDesc);
            Object[] args = new Object[downcallDesc.argumentLayouts().size() + 1]; // +1 for return allocator
            AtomicReference<Object[]> returnBox = new AtomicReference<>(); <------
            int returnIdx = numPrefixArgs;
            int argIdx = 0;
            args[argIdx++] = arena;
            args[argIdx++] = makeArgSaverCB(upcallDesc, arena, returnBox, returnIdx);
            for (TestValue testArg : testArgs) {
                args[argIdx++] = testArg.value();
            }

            MemorySegment returned = (MemorySegment) downcallHandle.invokeWithArguments(args); <--- exception was captured here.
```
which indicated that there might be something wrong with the passed-in or return value in upcall. 
I will need to go through the related code in the dispatcher to see where the exception was triggered.

**Comment by ChengJin01** [comment]
Further investigation in debugging indicates the problem only occurs when boxing the passed-in negative byte/short values to Byte/Short in the upcall method, which means we might need to add extra code when normalizing these values in the upcall dispatcher.  I will double-check the code in there to see how to handle this special case.

**Comment by ChengJin01** [comment]
With my fix at https://github.com/ChengJin01/openj9/commit/f513b8190f2d35c96910931dc7e0f0b0c50517dc#diff-e2e01e5f1b19239f4e0f58c31a751641196af494d60cce5722d2a503fbb0a084, the failing test suite passed as expected:
```
----------System.out:(40/4106)----------
NativeTestHelper::DEFAULT_RANDOM.seed = -1410139183
Re-run with '-DNativeTestHelper.DEFAULT_RANDOM.seed=-1410139183' to reproduce
test TestArrayStructs.testArrayStruct("F1", jdk.internal.foreign.FunctionDescriptorImpl@a0ea1cff, 0, 1): success
test TestArrayStructs.testArrayStruct("F2", jdk.internal.foreign.FunctionDescriptorImpl@3ef91709, 0, 2): success
test TestArrayStructs.testArrayStruct("F3", jdk.internal.foreign.FunctionDescriptorImpl@f215dc8c, 0, 3): success
test TestArrayStructs.testArrayStruct("F4", jdk.internal.foreign.FunctionDescriptorImpl@b220518, 0, 4): success
test TestArrayStructs.testArrayStruct("F5", jdk.internal.foreign.FunctionDescriptorImpl@12a70e5d, 0, 5): success
...
test TestArrayStructs.testArrayStruct("F16_stack", jdk.internal.foreign.FunctionDescriptorImpl@af30509e, 16, 16): success

===============================================
test/jdk/java/foreign/arraystructs/TestArrayStructs.java#interpreted
Total tests run: 32, Passes: 32, Failures: 0, Skips: 0
===============================================
----------System.err:(1/15)----------
STATUS:Passed.
```
Will prepare a few test suites to ensure there is no other issue with negative bytes/shorts introduced in JDK17/20/21+.
