### ISSUE TITLE
JDK21 serviceability/jvmti/vthread/BoundVThreadTest/BoundVThreadTest.java RuntimeException: BoundVThreadTest failed!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17784]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_linux_Personal/6/consoleFull)(`ub20-aarch64-5`):
```
08:14:17  openjdk version "21-internal" 2023-09-19
08:14:17  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21aarch64linuxPersonal)
08:14:17  Eclipse OpenJ9 VM (build master-6bae0289b9e, JRE 21 Linux aarch64-64-Bit Compressed References 20230711_10 (JIT enabled, AOT enabled)
08:14:17  OpenJ9   - 6bae0289b9e
08:14:17  OMR      - bcc94e42952
08:14:17  JCL      - 73fae096864 based on jdk-21+30)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_other_0,jdk_other_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F10%2FOpenJ9-JDK21-aarch64_linux-20230711-073423.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F10%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=6bae0289b9eb7748b84521bfd18d0cecf5c84785&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
08:20:43  variation: Mode650
08:20:43  JVM_OPTIONS:  -XX:-UseCompressedOops 

08:23:39  TEST: serviceability/jvmti/vthread/BoundVThreadTest/BoundVThreadTest.java

08:23:39  STDERR:
08:23:39  java.lang.RuntimeException: BoundVThreadTest failed!
08:23:39  	at BoundVThreadTest.runTest(BoundVThreadTest.java:57)
08:23:39  	at BoundVThreadTest.main(BoundVThreadTest.java:70)
08:23:39  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
08:23:39  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
08:23:39  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
08:23:39  	at java.base/java.lang.Thread.run(Thread.java:1595)
08:23:39  
08:23:39  JavaTest Message: Test threw exception: java.lang.RuntimeException: BoundVThreadTest failed!

08:23:39  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: BoundVThreadTest failed!
08:23:39  --------------------------------------------------
08:24:04  Test results: passed: 117; failed: 1
08:24:19  Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_linux_Personal/jvmtest/openjdk/report/html/report.html
08:24:19  Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_16890777958286/serviceability_jvmti_j9_1/work
08:24:19  Error: Some tests failed or other problems occurred.
08:24:19  -----------------------------------
08:24:19  serviceability_jvmti_j9_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33922/)

**Comment by pshipton** [comment]
In the grinder there are also failures for the following, which I didn't see another open issue for.
serviceability/jvmti/vthread/SuspendResume1/SuspendResume1.java - 1 failure (in [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/2628/))
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java - 2 failures (in [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/2628/) and [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_3/1990/))

**Comment by pshipton** [comment]
@babsingh
