### ISSUE TITLE
JDK 17.0.7+7 crash with `omr\port\common\omrmemtag.c:145: ((memoryCorruptionDetected))`

### ISSUE THREAD

**Issue by BurryPotter** [eclipse-openj9/openj9#17793]
Java -version output
--------------------
> jdk-17.0.7+7_openj9\bin\java -version
openjdk version "17.0.7" 2023-04-18
IBM Semeru Runtime Open Edition 17.0.7.0 (build 17.0.7+7)
Eclipse OpenJ9 VM 17.0.7.0 (build openj9-0.38.0, JRE 17 Windows 11 amd64-64-Bit Compressed References 20230418_439 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 9d7a231edbc based on jdk-17.0.7+7)

> jdk-11.0.19+7_openj9\bin\java -version
openjdk version "11.0.19" 2023-04-18
IBM Semeru Runtime Open Edition 11.0.19.0 (build 11.0.19+7)
Eclipse OpenJ9 VM 11.0.19.0 (build openj9-0.38.0, JRE 11 Windows 11 amd64-64-Bit Compressed References 20230523_646 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 629eb0c22b based on jdk-11.0.19+7)

> jdk8u372-b07_openj9\bin\java -version
openjdk version "1.8.0_372"
IBM Semeru Runtime Open Edition (build 1.8.0_372-b07)
Eclipse OpenJ9 VM (build openj9-0.38.0, JRE 1.8.0 Windows 11 amd64-64-Bit Compressed References 20230518_676 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - dd0ccb1fb5 based on jdk8u372-b07)

Summary of problem
------------------

JDK 17.0.7 crashed when the test programe is executed, but JDK 11.0.19 and JDK8u372 didn't.

Reproduce steps
------------------
1. Copy the source code `Case.java`
```
import java.lang.ref.PhantomReference;

public class Case {
    private static PhantomReference<Object> reference;

    public static void main(String[] var0) throws Exception {
        sumReductionInit(new long[262144], new long[262144], new long[262144]);
    }

    public static void sumReductionInit(long[] l1, long[] l2, long[] l3) {
        reference.get();
    }
}
```
2. compile and run the program with JDK 17.0.7 &  JDK 11.0.19 & JDK8u372 
```
> jdk-17.0.7+7_openj9\bin\java Case
Exception in thread "main" 07:09:11.435 0x21f00 omrport.359    *   ** ASSERTION FAILED ** at c:\workspace\openjdk-build\workspace\build\src\omr\port\common\omrmemtag.c:145: ((memoryCorruptionDetected))

> jdk-11.0.19+7_openj9\bin\java Case
Exception in thread "main" java.lang.NullPointerException
        at Case.sumReductionInit(Case.java:11)
        at Case.main(Case.java:7)

> jdk8u372-b07_openj9\bin\java  Case
Exception in thread "main" java.lang.NullPointerException
        at Case.sumReductionInit(Case.java:11)
        at Case.main(Case.java:7)

```
Diagnostic files
----------------

I upload the javacore, Snap, core files to Google Drive [Diagnostic files](https://drive.google.com/file/d/1ggoPTVvctdOiYz83oRBO6YMue5atuc4N/view?usp=sharing)

**Comment by JasonFengJ9** [comment]
This `memoryCorruptionDetected` assertion occurred at 
https://github.com/eclipse-openj9/openj9/blob/e8bc291edfd92b7dca94d046674a1f4e3b536544/runtime/j9vm/javanextvmi.cpp#L172
There was a memory overrun at `npeMsgData.liveStack` when `VMOPT_XXSHOW_EXTENDED_NPE_MESSAGE` is enabled which is by default since Java 17+.

This issue shares the same root cause as 
* https://github.com/eclipse-openj9/openj9/issues/17247

**Comment by gacholio** [comment]
Closing as duplicate of #17247
