### ISSUE TITLE
FIPS sun/security/krb5/etype/WeakCrypto.java IllegalArgumentException: EncryptionKey: Key bytes cannot be null!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17792]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/59/)(`rhel8x64-fips3-1`):
```
openjdk version "11.0.20" 2023-07-18
IBM Semeru Runtime Open Edition 11.0.20.0-m2 (build 11.0.20+7)
Eclipse OpenJ9 VM 11.0.20.0-m2 (build v0.40.0-release-6eed0535c, JRE 11 Linux amd64-64-Bit Compressed References 20230628_784 (JIT enabled, AOT enabled)
OpenJ9   - 6eed0535c
OMR      - e80bff83b
JCL      - 20e0e53157 based on jdk-11.0.20+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security4_1&amp;TEST_FLAG=FIPS&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9%2F784%2Fibm-semeru-open-jdk_x64_linux_11.0.20_7_openj9-0.40.0-m2.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9%2F784%2Fibm-semeru-open-testimage_x64_linux_11.0.20_7_openj9-0.40.0-m2.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v0.9.8-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=main&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=68&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=48&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-07-12T16:15:01.782Z] variation: Mode650
[2023-07-12T16:15:01.782Z] JVM_OPTIONS:  -XX:-UseCompressedOops  -Dsemeru.fips=true

[2023-07-12T16:15:28.160Z] TEST: sun/security/krb5/etype/WeakCrypto.java

[2023-07-12T16:15:28.161Z] STDERR:
[2023-07-12T16:15:28.161Z] java.lang.IllegalArgumentException: EncryptionKey: Key bytes cannot be null!
[2023-07-12T16:15:28.161Z] 	at java.security.jgss/sun.security.krb5.EncryptionKey.<init>(EncryptionKey.java:208)
[2023-07-12T16:15:28.161Z] 	at java.security.jgss/sun.security.krb5.EncryptionKey.acquireSecretKeys(EncryptionKey.java:186)
[2023-07-12T16:15:28.161Z] 	at WeakCrypto.main(WeakCrypto.java:74)
[2023-07-12T16:15:28.161Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-12T16:15:28.161Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-12T16:15:28.161Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-12T16:15:28.161Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-12T16:15:28.161Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-07-12T16:15:28.161Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-07-12T16:15:28.161Z] 
[2023-07-12T16:15:28.161Z] JavaTest Message: Test threw exception: java.lang.IllegalArgumentException: EncryptionKey: Key bytes cannot be null!

[2023-07-12T16:15:28.162Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.IllegalArgumentException: EncryptionKey: Key bytes cannot be null!
[2023-07-12T16:15:28.162Z] --------------------------------------------------
[2023-07-12T16:15:28.162Z] Test results: passed: 49; failed: 1
[2023-07-12T16:15:42.814Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/aqa-tests/TKG/output_16891780503301/jdk_security4_1/report/html/report.html
[2023-07-12T16:15:42.814Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/aqa-tests/TKG/output_16891780503301/jdk_security4_1/work
[2023-07-12T16:15:42.814Z] Error: Some tests failed or other problems occurred.
[2023-07-12T16:15:42.814Z] -----------------------------------
[2023-07-12T16:15:42.814Z] jdk_security4_1_FAILED

```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33933/) - all failed

**Comment by JasonFengJ9** [comment]
[FIPS JDK11 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/60/)
```
[2023-07-19T21:41:12.359Z] variation: Mode150
[2023-07-19T21:41:12.359Z] JVM_OPTIONS:  -XX:+UseCompressedOops  -Dsemeru.fips=true

[2023-07-19T21:41:36.871Z] TEST: sun/security/krb5/etype/WeakCrypto.java

[2023-07-19T21:41:36.872Z] STDERR:
[2023-07-19T21:41:36.872Z] java.lang.IllegalArgumentException: EncryptionKey: Key bytes cannot be null!
[2023-07-19T21:41:36.872Z] 	at java.security.jgss/sun.security.krb5.EncryptionKey.<init>(EncryptionKey.java:208)
[2023-07-19T21:41:36.872Z] 	at java.security.jgss/sun.security.krb5.EncryptionKey.acquireSecretKeys(EncryptionKey.java:186)
[2023-07-19T21:41:36.872Z] 	at WeakCrypto.main(WeakCrypto.java:74)

[2023-07-19T21:41:36.872Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.IllegalArgumentException: EncryptionKey: Key bytes cannot be null!
[2023-07-19T21:41:36.872Z] --------------------------------------------------
[2023-07-19T21:41:37.435Z] Test results: passed: 49; failed: 1
[2023-07-19T21:41:51.944Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/aqa-tests/TKG/output_1689802042214/jdk_security4_0/report/html/report.html
[2023-07-19T21:41:51.944Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/aqa-tests/TKG/output_1689802042214/jdk_security4_0/work
[2023-07-19T21:41:51.944Z] Error: Some tests failed or other problems occurred.
[2023-07-19T21:41:51.944Z] -----------------------------------
[2023-07-19T21:41:51.944Z] jdk_security4_0_FAILED
```

**Comment by jasonkatonica** [comment]
This seems similar to issue https://github.com/eclipse-openj9/openj9/issues/17792

**Comment by JasonFengJ9** [comment]
[FIPS JDK8 x86-64_linux_fips140_2 0.41 milestone 1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_fips140_2_testList_1/2/)(`rhel8x64-fips5-1`)
```
[2023-09-06T19:40:46.310Z] variation: Mode150
[2023-09-06T19:40:46.310Z] JVM_OPTIONS:  -XX:+UseCompressedOops  -Dsemeru.fips=true

openjdk version "1.8.0_392"
IBM Semeru Runtime Open Edition (build 1.8.0_392-b03)
Eclipse OpenJ9 VM (build v0.41.0-release-87d042a68, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230906_749 (JIT enabled, AOT enabled)
OpenJ9   - 87d042a68
OMR      - fa7b6ddc7
JCL      - 04ddaa8f70 based on jdk8u392-b03)

[2023-09-06T19:40:55.835Z] TEST: sun/security/krb5/etype/WeakCrypto.java

[2023-09-06T19:40:55.835Z] STDERR:
[2023-09-06T19:40:55.835Z] java.lang.IllegalArgumentException: EncryptionKey: Key bytes cannot be null!
[2023-09-06T19:40:55.835Z] 	at sun.security.krb5.EncryptionKey.<init>(EncryptionKey.java:208)
[2023-09-06T19:40:55.835Z] 	at sun.security.krb5.EncryptionKey.acquireSecretKeys(EncryptionKey.java:186)
[2023-09-06T19:40:55.835Z] 	at WeakCrypto.main(WeakCrypto.java:72)
[2023-09-06T19:40:55.835Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-09-06T19:40:55.835Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-09-06T19:40:55.835Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-09-06T19:40:55.835Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-09-06T19:40:55.835Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-09-06T19:40:55.835Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-09-06T19:40:55.835Z] 
[2023-09-06T19:40:55.835Z] JavaTest Message: Test threw exception: java.lang.IllegalArgumentException: EncryptionKey: Key bytes cannot be null!

[2023-09-06T19:41:07.799Z] jdk_security4_0_FAILED
```

**Comment by llxia** [comment]
@jasonkatonica if this is not going to be looked at any time soon, could we temporarily exclude the tests? Thanks

**Comment by JasonFengJ9** [comment]
[FIPS JDK8 x86-64_linux_fips140_2](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_fips140_2_testList_1/11/0)

**Comment by jasonkatonica** [comment]
This issue can be closed since its using the deprecated 140-2 standard and the test is ignored.
