### ISSUE TITLE
envDetect NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17790]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_x86-64_linux_OpenJDK21/4 - [ub16x64j96](https://openj9-jenkins.osuosl.org/computer/ub16x64j96)
```
15:22:47  /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_x86-64_linux_OpenJDK21/openjdkbinary/j2sdk-image/bin/java -cp ./bin/TestKitGen.jar org.openj9.envInfo.EnvDetector
15:22:47  uname -a
15:22:48  bash -c cat /proc/cpuinfo | grep processor | wc -l
15:22:48  uname -m
15:22:48  uname -p
15:22:48  bash -c cat /proc/cpuinfo | grep 'model name' | uniq
15:22:48  uname -s
15:22:48  bash -c ulimit -a
15:22:48  bash -c if grep -sq 'docker\|lxc' /proc/1/cgroup; then echo 'running on docker'; else echo 'not on docker'; fi
15:22:48  bash -c grep '^NAME' /etc/os-release | awk -F'=' ' gsub(/"/,"") { print $2}'
15:22:48  bash -c grep '^VERSION_ID' /etc/os-release | awk -F'=' ' gsub(/"/,"") { print $2}'
15:22:48  bash -c cat /etc/os-release
15:22:48  bash -c ant -version
15:22:48  bash -c make --version
15:22:48  bash -c perl --version
15:22:48  bash -c curl --version | head -n 1 | awk '{ print $2 }'
15:22:48  gcc -dumpversion
15:22:48  bash -c xlC -qversion | grep 'Version' 
15:22:49  bash -c gdb --version | head -1
15:22:49  lldb --version
15:22:49  bash -c ldd --version | head -1
15:22:49  Exception in thread "main" java.lang.NumberFormatException: For input string: ""
15:22:49  	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
15:22:49  	at java.base/java.lang.Integer.parseInt(Integer.java:671)
15:22:49  	at java.base/java.lang.Integer.parseInt(Integer.java:777)
15:22:49  	at org.openj9.envInfo.MachineInfo.versionStr2ArrList(MachineInfo.java:133)
15:22:49  	at org.openj9.envInfo.MachineInfo.validateVersion(MachineInfo.java:148)
15:22:49  	at org.openj9.envInfo.MachineInfo.validateInfo(MachineInfo.java:179)
15:22:49  	at org.openj9.envInfo.MachineInfo.checkInfo(MachineInfo.java:97)
15:22:49  	at org.openj9.envInfo.EnvDetector.parseArgs(EnvDetector.java:33)
15:22:49  	at org.openj9.envInfo.EnvDetector.main(EnvDetector.java:28)
15:22:49  makefile:73: recipe for target 'envDetect' failed
```

Same problem 
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_OpenJDK21/4 - [cent7-x64-4](https://openj9-jenkins.osuosl.org/computer/cent7-x64-4)

Changes from yesterday's build:
https://github.com/adoptium/TKG/compare/f86a77e93be4d7a09004bdca76cac8f43e57d406...e77928f88683e8d15876749e53ea80b10ce5766e
https://github.com/adoptium/aqa-tests/compare/73443d2f8e6de33fc3bc04cf12b5acc7ab9c9b52...5d30587f0ec7ecfd4b9cbda147530bfab3fb3caa

Looks like https://github.com/adoptium/TKG/pull/457 is the cause.
@llxia @renfeiw

**Comment by llxia** [comment]
Close this issue as the PR is reverted and the next build is green.
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_x86-64_linux_OpenJDK21/5/
