### ISSUE TITLE
Investigate behaviour of Thread.stop() on suspended threads

### ISSUE THREAD

**Issue by gacholio** [eclipse-openj9/openj9#17818]
In #17806 we changed the behaviour of JVMTI `StopThread()` to no longer resume a suspended thread. We need to see if a similar change should be made to the java `Thread.stop()` which is implemented seperately.

**Comment by gacholio** [comment]
```
public class StopTest {
	public static void main(String args[]) throws Throwable {
		Thread t = new Thread() {
			public void run() {
				try {
					System.out.println("suspending");
					Thread.currentThread().suspend();
				} catch(Throwable t) {
					t.printStackTrace();
				}
			}
		};
		System.out.println("starting");
		t.start();
		Thread.sleep(5000);
		System.out.println("stopping");
		t.stop();
		Thread.sleep(5000);
		System.out.println("resuming");
		t.join();
	}
}
```

**Comment by gacholio** [comment]
```
j9build@736bb006f300:DOCKER-IMAGE $ jdk1.8.0_381/bin/java StopTest
starting
suspending
stopping
java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:858)
	at StopTest.main(StopTest.java:18)
resumedresuming
j9build@736bb006f300:DOCKER-IMAGE $ jdk1.8.0_381/bin/java StopTest
starting
suspending
stopping
resumed
resuming
j9build@736bb006f300:DOCKER-IMAGE $ jdk1.8.0_381/bin/java StopTest
starting
suspending
stopping
resumedjava.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:858)
	at StopTest.main(StopTest.java:18)

resuming
```
Oracle JDK8 does appear to resume the thread on stop(). The exception appears to be thrown at some random time after the resume.

**Comment by gacholio** [comment]
```
j9build@736bb006f300:DOCKER-IMAGE $ /team/gac/80/bin/java -Xint StopTest
starting
suspending
stopping
java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:1028)
	at StopTest.main(StopTest.java:18)
resuming
```
On J9, we throw the exception immediately.
