### ISSUE TITLE
OpenJDK java/util/stream/boottest/java.base/java/util/stream/SpinedBufferTest.java NPE String.charAt

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17826]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/8/
java/util/stream/boottest/java.base/java/util/stream/SpinedBufferTest.java
```
06:01:48  test java.util.stream.SpinedBufferTest.testLastSplit([I@2cc3c427, java.util.stream.SpinedBuffer@e58abbc
06:01:48  
06:01:48  ...
06:01:48  Output overflow:
06:01:48  JT Harness has limited the test output to the text
06:01:48  at the beginning and the end, so that you can see how the
06:01:48  test began, and how it completed.
06:01:48  
06:01:48  If you need to see more of the output from the test,
06:01:48  set the system property javatest.maxOutputSize to a higher
06:01:48  value. The current value is 100000
06:01:48  ...
06:01:48  
06:01:48  invoke0(Native Method)
06:01:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:01:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:01:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:01:48  	at java.base/java.lang.Thread.run(Thread.java:839)
06:01:48  test java.util.stream.SpinedBufferTest.testSpliterator([I@5d988010, java.util.stream.SpinedBuffer@2602a3f): failure
06:01:48  java.lang.NullPointerException
06:01:48  	at java.base/java.lang.String.charAt(String.java:1319)
06:01:48  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:01:48  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:01:48  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:01:48  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:01:48  	at java.base/java.lang.String.format(String.java:3728)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:578)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:529)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:167)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:53)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:48)
06:01:48  	at java.base/java.util.stream.SpinedBufferTest.testSpliterator(SpinedBufferTest.java:92)
06:01:48  	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
06:01:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:01:48  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
06:01:48  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
06:01:48  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
06:01:48  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
06:01:48  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
06:01:48  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
06:01:48  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
06:01:48  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
06:01:48  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
06:01:48  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
06:01:48  	at org.testng.TestRunner.run(TestRunner.java:585)
06:01:48  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
06:01:48  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
06:01:48  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
06:01:48  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
06:01:48  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
06:01:48  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
06:01:48  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
06:01:48  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
06:01:48  	at org.testng.TestNG.runSuites(TestNG.java:1069)
06:01:48  	at org.testng.TestNG.run(TestNG.java:1037)
06:01:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
06:01:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
06:01:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:01:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:01:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:01:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:01:48  	at java.base/java.lang.Thread.run(Thread.java:839)
06:01:48  test java.util.stream.SpinedBufferTest.testSpliterator([I@5d988010, java.util.stream.SpinedBuffer@2cabb82b): failure
06:01:48  java.lang.NullPointerException
06:01:48  	at java.base/java.lang.String.charAt(String.java:1319)
06:01:48  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:01:48  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:01:48  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:01:48  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:01:48  	at java.base/java.lang.String.format(String.java:3728)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:578)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:529)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:167)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:53)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:48)
06:01:48  	at java.base/java.util.stream.SpinedBufferTest.testSpliterator(SpinedBufferTest.java:92)
06:01:48  	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
06:01:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:01:48  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
06:01:48  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
06:01:48  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
06:01:48  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
06:01:48  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
06:01:48  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
06:01:48  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
06:01:48  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
06:01:48  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
06:01:48  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
06:01:48  	at org.testng.TestRunner.run(TestRunner.java:585)
06:01:48  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
06:01:48  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
06:01:48  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
06:01:48  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
06:01:48  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
06:01:48  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
06:01:48  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
06:01:48  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
06:01:48  	at org.testng.TestNG.runSuites(TestNG.java:1069)
06:01:48  	at org.testng.TestNG.run(TestNG.java:1037)
06:01:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
06:01:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
06:01:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:01:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:01:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:01:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:01:48  	at java.base/java.lang.Thread.run(Thread.java:839)
06:01:48  test java.util.stream.SpinedBufferTest.testSpliterator([I@a2b958cc, java.util.stream.SpinedBuffer@9473d6be): failure
06:01:48  java.lang.NullPointerException
06:01:48  	at java.base/java.lang.String.charAt(String.java:1319)
06:01:48  	at java.base/java.util.Formatter.checkText(Formatter.java:2730)
06:01:48  	at java.base/java.util.Formatter.parse(Formatter.java:2708)
06:01:48  	at java.base/java.util.Formatter.format(Formatter.java:2655)
06:01:48  	at java.base/java.util.Formatter.format(Formatter.java:2609)
06:01:48  	at java.base/java.lang.String.format(String.java:3728)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:578)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSplitUntilNull(SpliteratorTestHelper.java:529)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:167)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:53)
06:01:48  	at java.base/java.util.SpliteratorTestHelper.testSpliterator(SpliteratorTestHelper.java:48)
06:01:48  	at java.base/java.util.stream.SpinedBufferTest.testSpliterator(SpinedBufferTest.java:92)
06:01:48  	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
06:01:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:01:48  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
06:01:48  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
06:01:48  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
06:01:48  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
06:01:48  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
06:01:48  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
06:01:48  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
06:01:48  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
06:01:48  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
06:01:48  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
06:01:48  	at org.testng.TestRunner.run(TestRunner.java:585)
06:01:48  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
06:01:48  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
06:01:48  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
06:01:48  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
06:01:48  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
06:01:48  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
06:01:48  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
06:01:48  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
06:01:48  	at org.testng.TestNG.runSuites(TestNG.java:1069)
06:01:48  	at org.testng.TestNG.run(TestNG.java:1037)
06:01:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
06:01:48  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
06:01:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:01:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:01:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:01:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:01:48  	at java.base/java.lang.Thread.run(Thread.java:839)
```

**Comment by pshipton** [comment]
Dup of https://github.com/eclipse-openj9/openj9/issues/17774
