### ISSUE TITLE
[FFI/Jtreg_JDK21] AssertionError detected in TestTrivialUpcall.java

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17820]
The test suite `TestTrivialUpcall` at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/trivial/TestTrivialUpcall.java ended up with the following error:
```
test TestTrivialUpcall.testUpcallFailure(): failure
java.lang.AssertionError: Did not find 'wrong thread state for upcall' in stdout expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertTrue(Assert.java:45)
        at UpcallTestHelper$Output.assertContains(UpcallTestHelper.java:41)
        at UpcallTestHelper$Output.assertStdOutContains(UpcallTestHelper.java:51)
        at TestTrivialUpcall.testUpcallFailure(TestTrivialUpcall.java:48)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
...
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
Looking at the failure against the test code at 
```
public class TestTrivialUpcall extends UpcallTestHelper {

    @Test
    public void testUpcallFailure() throws IOException, InterruptedException {
        // test to see if we catch a trivial downcall doing an upcall
---->    runInNewProcess(Runner.class, true).assertStdOutContains("wrong thread state for upcall");
-----> the error message was supposed to be captured in the new process running the test.
    }

    public static class Runner extends NativeTestHelper {
        public static void main(String[] args) throws Throwable {
            System.loadLibrary("Trivial");

            MethodHandle mh = downcallHandle("do_upcall", FunctionDescriptor.ofVoid(C_POINTER), 
           Linker.Option.isTrivial()); <---- this is the invalid linker option for upcall
            MemorySegment stub = upcallStub(Runner.class, "target", FunctionDescriptor.ofVoid());
            mh.invokeExact(stub);  <---------- the error message was triggered.
        }

        public static void target() {
            fail("Should not get here"); <------- the upcall method was never called.
        }
    }
}
```
it aims to trigger an error message when doing the upcall with the invalid linker option `Linker.Option.isTrivial()` (only used in downcall) based on the API description at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/src/java.base/share/classes/java/lang/foreign/Linker.java#L752
```
         * A trivial function is a function that has an extremely short running time
         * in all cases (similar to calling an empty function), 
         * and does not call back into Java (e.g. using an upcall stub). <----------
.......
         */
        static Option isTrivial() {
```
That being said, the invalid linker option should be captured prior to the upcall method (e.g. somewhere in the upcall dispatcher) to stop the behavior.

**Comment by ChengJin01** [comment]
The test suites passed with the fix at https://github.com/ChengJin01/openj9/commit/a60408c25700de4d1405e4990d27c7c559c68a88
```
----------System.out:(11/512)----------
NativeTestHelper::DEFAULT_RANDOM.seed = -337437389
Re-run with '-DNativeTestHelper.DEFAULT_RANDOM.seed=-337437389' to reproduce
NativeTestHelper::DEFAULT_RANDOM.seed = 1526801219
Re-run with '-DNativeTestHelper.DEFAULT_RANDOM.seed=1526801219' to reproduce
test TestTrivialUpcall.testUpcallFailure(): success

===============================================
test/jdk/java/foreign/trivial/TestTrivialUpcall.java
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================
```
and 
```
----------System.out:(12/497)----------
NativeTestHelper::DEFAULT_RANDOM.seed = -17147226
Re-run with '-DNativeTestHelper.DEFAULT_RANDOM.seed=-17147226' to reproduce
test TestTrivial.testCaptureErrno(): success
test TestTrivial.testEmpty(): success
test TestTrivial.testIdentity(): success
test TestTrivial.testWithReturnBuffer(): success

===============================================
test/jdk/java/foreign/trivial/TestTrivial.java
Total tests run: 4, Passes: 4, Failures: 0, Skips: 0
===============================================
```
