### ISSUE TITLE
jdk_nio_1_FAILED java/nio/file/FileStore/Basic.java RuntimeException: Assertion failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17837]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_linux/152/)(`rhel9x86-rt1-1`):
```
java version "11.0.20" 2023-07-18
IBM Semeru Runtime Certified Edition 11.0.20.0-rc1 (build 11.0.20+8)
Eclipse OpenJ9 VM 11.0.20.0-rc1 (build v0.40.0-release-b681a676a, JRE 11 Linux amd64-64-Bit Compressed References 20230719_670 (JIT enabled, AOT enabled)
OpenJ9   - b681a676a
OMR      - e80bff83b
JCL      - 89ad412ebb based on jdk-11.0.20+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_nio_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F670%2Fibm-semeru-certified-jdk_x64_linux_11.0.20.0-rc1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F670%2Fibm-semeru-certified-testimage_x64_linux_11.0.20.0-rc1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v0.9.8-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.40.0-release&amp;OPENJ9_BRANCH=v0.40.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.40.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-07-19T19:41:54.013Z] variation: Mode650
[2023-07-19T19:41:54.013Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-07-19T19:56:39.738Z] TEST: java/nio/file/FileStore/Basic.java

[2023-07-19T19:56:39.751Z] STDERR:
[2023-07-19T19:56:39.751Z] java.lang.RuntimeException: Assertion failed
[2023-07-19T19:56:39.751Z] 	at Basic.assertTrue(Basic.java:57)
[2023-07-19T19:56:39.751Z] 	at Basic.doTests(Basic.java:161)
[2023-07-19T19:56:39.751Z] 	at Basic.main(Basic.java:49)
[2023-07-19T19:56:39.751Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-07-19T19:56:39.751Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-07-19T19:56:39.751Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-07-19T19:56:39.751Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-07-19T19:56:39.751Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-07-19T19:56:39.751Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-07-19T19:56:39.751Z] 
[2023-07-19T19:56:39.751Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2023-07-19T19:56:39.751Z] JavaTest Message: shutting down test
[2023-07-19T19:56:39.751Z] 
[2023-07-19T19:56:39.751Z] 
[2023-07-19T19:56:39.751Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Assertion failed
[2023-07-19T19:56:39.751Z] --------------------------------------------------
[2023-07-19T20:13:38.100Z] Test results: passed: 390; failed: 1
[2023-07-19T20:13:38.100Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16897925209163/jdk_nio_1/report/html/report.html
[2023-07-19T20:13:38.100Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16897925209163/jdk_nio_1/work
[2023-07-19T20:13:38.100Z] Error: Some tests failed or other problems occurred.
[2023-07-19T20:13:38.100Z] -----------------------------------
[2023-07-19T20:13:38.100Z] jdk_nio_1_FAILED
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34089/)

**Comment by JasonFengJ9** [comment]
[JDK11 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux/141/)(`rhel9-aarch64-1`)
```
java version "11.0.21" 2023-10-17
IBM Semeru Runtime Certified Edition 11.0.21.0-rc2 (build 11.0.21+9)
Eclipse OpenJ9 VM 11.0.21.0-rc2 (build v0.41.0-release-a803f004b, JRE 11 Linux aarch64-64-Bit Compressed References 20231116_458 (JIT enabled, AOT enabled)
OpenJ9   - a803f004b
OMR      - 5eee6ad9d
JCL      - 6f4cc08025 based on jdk-11.0.21+9)

[2023-11-16T05:29:31.390Z] variation: Mode150
[2023-11-16T05:29:31.390Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-11-16T05:45:15.591Z] TEST: java/nio/file/FileStore/Basic.java

[2023-11-16T05:45:15.593Z] STDERR:
[2023-11-16T05:45:15.593Z] java.lang.RuntimeException: Assertion failed
[2023-11-16T05:45:15.593Z] 	at Basic.assertTrue(Basic.java:57)
[2023-11-16T05:45:15.593Z] 	at Basic.doTests(Basic.java:161)
[2023-11-16T05:45:15.594Z] 	at Basic.main(Basic.java:49)
[2023-11-16T05:45:15.594Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-16T05:45:15.594Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-11-16T05:45:15.594Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-16T05:45:15.594Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-11-16T05:45:15.594Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-11-16T05:45:15.594Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-11-16T05:45:15.594Z] 
[2023-11-16T05:45:15.594Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2023-11-16T05:45:15.594Z] JavaTest Message: shutting down test
[2023-11-16T05:45:15.594Z] 
[2023-11-16T05:45:15.594Z] 
[2023-11-16T05:45:15.594Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Assertion failed
[2023-11-16T05:45:15.594Z] --------------------------------------------------
[2023-11-16T05:59:31.705Z] Test results: passed: 391; failed: 1
[2023-11-16T05:59:44.453Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_17001105225457/jdk_nio_0/report/html/report.html
[2023-11-16T05:59:44.453Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_17001105225457/jdk_nio_0/work
[2023-11-16T05:59:44.454Z] Error: Some tests failed or other problems occurred.
[2023-11-16T05:59:44.892Z] -----------------------------------
[2023-11-16T05:59:44.892Z] jdk_nio_0_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36195/)

**Comment by JasonFengJ9** [comment]
[JDK8 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux_testList_0/9/)(`rhel9x86-svl-rt1-1`)
```
[2024-03-07T00:43:17.879Z] variation: Mode650
[2024-03-07T00:43:17.879Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-07T00:46:00.899Z] TEST: java/nio/file/FileStore/Basic.java

[2024-03-07T00:46:00.900Z] STDERR:
[2024-03-07T00:46:00.900Z] java.lang.RuntimeException: Assertion failed
[2024-03-07T00:46:00.900Z] 	at Basic.assertTrue(Basic.java:55)
[2024-03-07T00:46:00.900Z] 	at Basic.doTests(Basic.java:140)
[2024-03-07T00:46:00.900Z] 	at Basic.main(Basic.java:47)
[2024-03-07T00:46:00.900Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-03-07T00:46:00.900Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-03-07T00:46:00.900Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-03-07T00:46:00.900Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-03-07T00:46:00.900Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2024-03-07T00:46:00.900Z] 	at java.lang.Thread.run(Thread.java:826)
[2024-03-07T00:46:00.900Z] 
[2024-03-07T00:46:00.900Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2024-03-07T00:46:00.900Z] JavaTest Message: shutting down test
[2024-03-07T00:46:00.900Z] 
[2024-03-07T00:46:00.900Z] 
[2024-03-07T00:46:00.900Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Assertion failed
[2024-03-07T00:46:00.900Z] --------------------------------------------------
[2024-03-07T00:47:58.154Z] Test results: passed: 330; failed: 1
[2024-03-07T00:47:58.154Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_17097712209896/jdk_nio_1/report/html/report.html
[2024-03-07T00:47:58.154Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_17097712209896/jdk_nio_1/work
[2024-03-07T00:47:58.154Z] Error: Some tests failed or other problems occurred.
[2024-03-07T00:47:58.154Z] -----------------------------------
[2024-03-07T00:47:58.154Z] jdk_nio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK21 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_1/59/)(`rtj-ubu24le-rtp-test-4dee3-1`)
```
[2024-06-01T16:23:54.099Z] variation: Mode650
[2024-06-01T16:23:54.099Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-06-01T16:27:56.785Z] TEST: java/nio/file/FileStore/Basic.java

[2024-06-01T16:27:56.787Z] STDERR:
[2024-06-01T16:27:56.787Z] java.lang.RuntimeException: Assertion failed
[2024-06-01T16:27:56.787Z] 	at Basic.assertTrue(Basic.java:57)
[2024-06-01T16:27:56.787Z] 	at Basic.doTests(Basic.java:165)
[2024-06-01T16:27:56.787Z] 	at Basic.main(Basic.java:49)
[2024-06-01T16:27:56.787Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-06-01T16:27:56.787Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-06-01T16:27:56.787Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-06-01T16:27:56.787Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-06-01T16:27:56.787Z] 
[2024-06-01T16:27:56.787Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2024-06-01T16:27:56.787Z] JavaTest Message: shutting down test
[2024-06-01T16:27:56.787Z] 
[2024-06-01T16:27:56.787Z] 
[2024-06-01T16:27:56.787Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Assertion failed
[2024-06-01T16:27:56.787Z] --------------------------------------------------
[2024-06-01T16:31:30.923Z] Test results: passed: 407; failed: 1
[2024-06-01T16:31:37.149Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_17172584412517/jdk_nio_1/report/html/report.html
[2024-06-01T16:31:37.149Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_17172584412517/jdk_nio_1/work
[2024-06-01T16:31:37.149Z] Error: Some tests failed or other problems occurred.
[2024-06-01T16:31:37.149Z] -----------------------------------
[2024-06-01T16:31:37.149Z] jdk_nio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK 21 aarch64_linux 0.46.1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_0/110/)(`rtj-ubu24aarch64-svl-test-k2uwp-1`)
```
[2024-09-05T15:58:47.047Z] variation: Mode650
[2024-09-05T15:58:47.047Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-09-05T16:05:16.618Z] TEST: java/nio/file/FileStore/Basic.java

[2024-09-05T16:05:16.620Z] STDERR:
[2024-09-05T16:05:16.620Z] java.lang.RuntimeException: Assertion failed
[2024-09-05T16:05:16.620Z] 	at Basic.assertTrue(Basic.java:57)
[2024-09-05T16:05:16.620Z] 	at Basic.doTests(Basic.java:165)
[2024-09-05T16:05:16.620Z] 	at Basic.main(Basic.java:49)
[2024-09-05T16:05:16.620Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-09-05T16:05:16.620Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-09-05T16:05:16.620Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-09-05T16:05:16.620Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-09-05T16:05:16.620Z] 
[2024-09-05T16:05:16.620Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

[2024-09-05T16:10:54.446Z] jdk_nio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.openjdk_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_linux/488/)
```
[2025-05-29T15:02:58.535Z] variation: Mode150
[2025-05-29T15:02:58.535Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-05-29T15:05:57.562Z] TEST: java/nio/file/FileStore/Basic.java

[2025-05-29T15:05:57.575Z] STDERR:
[2025-05-29T15:05:57.576Z] java.lang.RuntimeException: Assertion failed
[2025-05-29T15:05:57.576Z] 	at Basic.assertTrue(Basic.java:57)
[2025-05-29T15:05:57.576Z] 	at Basic.doTests(Basic.java:165)
[2025-05-29T15:05:57.576Z] 	at Basic.main(Basic.java:49)


[2025-05-29T15:05:57.576Z] --------------------------------------------------
[2025-05-29T15:08:25.658Z] Test results: passed: 388; failed: 2

[2025-05-29T15:08:25.659Z] jdk_nio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_ppc64le_linux_testList_0/517/)
```
[2026-04-11T00:49:55.378Z] Running test jdk_nio_0 ...
[2026-04-11T00:49:55.378Z] ===============================================
[2026-04-11T00:49:55.378Z] jdk_nio_0 Start Time: Fri Apr 10 20:49:53 2026 Epoch Time (ms): 1775868593488
[2026-04-11T00:49:55.378Z] variation: Mode150
[2026-04-11T00:49:55.378Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2026-04-11T00:52:45.366Z] TEST: java/nio/file/FileStore/Basic.java

[2026-04-11T00:52:45.368Z] STDERR:
[2026-04-11T00:52:45.368Z] java.lang.RuntimeException: Assertion failed
[2026-04-11T00:52:45.368Z] 	at Basic.assertTrue(Basic.java:57)
[2026-04-11T00:52:45.368Z] 	at Basic.doTests(Basic.java:165)
[2026-04-11T00:52:45.368Z] 	at Basic.main(Basic.java:49)
```

**Comment by hzongaro** [comment]
Encountered this in a personal build https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_linux_Personal/550/
