### ISSUE TITLE
OpenJDK java/lang/String/concat/WithSecurityManager LinkageError: A duplicate class definition

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17835]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_ppc64le_linux_Release_testList_0/4
jdk_lang_0
java/lang/String/concat/WithSecurityManager.java
```
18:27:12  java.lang.LinkageError: A duplicate class definition for java/lang/invoke/BoundMethodHandle$Species_LLLLLL is found
18:27:12  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:474)
18:27:12  	at java.base/java.lang.Access.defineClass(Access.java:249)
18:27:12  	at java.base/java.lang.invoke.ClassSpecializer$Factory.generateConcreteSpeciesCode(ClassSpecializer.java:594)
18:27:12  	at java.base/java.lang.invoke.ClassSpecializer$Factory.loadSpecies(ClassSpecializer.java:498)
18:27:12  	at java.base/java.lang.invoke.ClassSpecializer.findSpecies(ClassSpecializer.java:201)
18:27:12  	at java.base/java.lang.invoke.BoundMethodHandle$SpeciesData.extendWith(BoundMethodHandle.java:359)
18:27:12  	at java.base/java.lang.invoke.LambdaFormEditor.newSpeciesData(LambdaFormEditor.java:517)
18:27:12  	at java.base/java.lang.invoke.LambdaFormEditor.makeArgumentCombinationForm(LambdaFormEditor.java:889)
18:27:12  	at java.base/java.lang.invoke.LambdaFormEditor.filterArgumentsForm(LambdaFormEditor.java:1072)
18:27:12  	at java.base/java.lang.invoke.MethodHandles.argumentsWithCombiner(MethodHandles.java:6168)
18:27:12  	at java.base/java.lang.invoke.MethodHandles.filterArgumentsWithCombiner(MethodHandles.java:6133)
18:27:12  	at java.base/java.lang.invoke.StringConcatFactory.filterAndFoldInMixers(StringConcatFactory.java:640)
18:27:12  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:577)
18:27:12  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:353)
18:27:12  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
18:27:12  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
18:27:12  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:279)
18:27:12  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:269)
18:27:12  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:198)
18:27:12  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
18:27:12  	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:742)
18:27:12  	at java.base/java.io.File.exists(File.java:831)
18:27:12  	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1412)
18:27:12  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:424)
18:27:12  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:479)
18:27:12  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:971)
18:27:12  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:969)
18:27:12  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
18:27:12  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:982)
18:27:12  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
18:27:12  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
18:27:12  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
18:27:12  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
18:27:12  	at WithSecurityManager.main(WithSecurityManager.java:55)
18:27:12  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:27:12  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
18:27:12  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
18:27:12  	at java.base/java.lang.Thread.run(Thread.java:1639)
```

**Comment by pshipton** [comment]
5x x 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/2597/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_mac_OMR_testList_1/16/
jdk_lang_1
java/lang/String/concat/WithSecurityManager.java
```
11:10:19  java.lang.LinkageError: A duplicate class definition for java/lang/invoke/BoundMethodHandle$Species_LL is found
11:10:19  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472)
11:10:19  	at java.base/java.lang.Access.defineClass(Access.java:241)
11:10:19  	at java.base/java.lang.invoke.ClassSpecializer$Factory.generateConcreteSpeciesCode(ClassSpecializer.java:593)
11:10:19  	at java.base/java.lang.invoke.ClassSpecializer$Factory.loadSpecies(ClassSpecializer.java:497)
11:10:19  	at java.base/java.lang.invoke.ClassSpecializer.findSpecies(ClassSpecializer.java:201)
11:10:19  	at java.base/java.lang.invoke.BoundMethodHandle$SpeciesData.extendWith(BoundMethodHandle.java:370)
11:10:19  	at java.base/java.lang.invoke.LambdaFormEditor.newSpeciesData(LambdaFormEditor.java:466)
11:10:19  	at java.base/java.lang.invoke.LambdaFormEditor.bindArgumentForm(LambdaFormEditor.java:529)
11:10:19  	at java.base/java.lang.invoke.LambdaFormEditor.bindArgumentL(LambdaFormEditor.java:473)
11:10:19  	at java.base/java.lang.invoke.BoundMethodHandle.bindArgumentL(BoundMethodHandle.java:92)
11:10:19  	at java.base/java.lang.invoke.MethodHandles.insertArguments(MethodHandles.java:5183)
11:10:19  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:486)
11:10:19  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:358)
11:10:19  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
11:10:19  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
11:10:19  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
11:10:19  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
11:10:19  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:201)
11:10:19  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:46)
11:10:19  	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
11:10:19  	at java.base/java.io.File.exists(File.java:829)
11:10:19  	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1394)
11:10:19  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:421)
11:10:19  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:476)
11:10:19  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:971)
11:10:19  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:969)
11:10:19  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
11:10:19  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:982)
11:10:19  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
11:10:19  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
11:10:19  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
11:10:19  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1095)
11:10:19  	at WithSecurityManager.main(WithSecurityManager.java:55)
11:10:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:10:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:10:19  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:10:19  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:10:19  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:10:19  	at java.base/java.lang.Thread.run(Thread.java:857)
```

**Comment by JitendraProgrammer** [comment]
Hi @pshipton,

Can i join and contribute something

**Comment by pshipton** [comment]
@JitendraProgrammer see https://github.com/eclipse-openj9/openj9/blob/master/README.md and the following lists.
https://github.com/eclipse-openj9/openj9/labels/good%20first%20issue
https://github.com/eclipse-openj9/openj9/labels/help%20wanted

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/50
jdk_lang_1
java/lang/String/concat/WithSecurityManager.java
```
17:58:13  java.lang.LinkageError: A duplicate class definition for java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLL is found
17:58:13  	at java.base/java.lang.ClassLoader.defineClassImpl1(Native Method)
17:58:13  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:510)
17:58:13  	at java.base/java.lang.Access.defineClass(Access.java:347)
17:58:13  	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2511)
17:58:13  	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2486)
17:58:13  	at java.base/java.lang.invoke.ClassSpecializer$Factory.generateConcreteSpeciesCode(ClassSpecializer.java:580)
17:58:13  	at java.base/java.lang.invoke.ClassSpecializer$Factory.loadSpecies(ClassSpecializer.java:497)
17:58:13  	at java.base/java.lang.invoke.ClassSpecializer.findSpecies(ClassSpecializer.java:200)
17:58:13  	at java.base/java.lang.invoke.BoundMethodHandle$SpeciesData.extendWith(BoundMethodHandle.java:360)
17:58:13  	at java.base/java.lang.invoke.LambdaFormEditor.newSpeciesData(LambdaFormEditor.java:516)
17:58:13  	at java.base/java.lang.invoke.LambdaFormEditor.makeRepeatedFilterForm(LambdaFormEditor.java:759)
17:58:13  	at java.base/java.lang.invoke.LambdaFormEditor.filterRepeatedArgumentForm(LambdaFormEditor.java:737)
17:58:13  	at java.base/java.lang.invoke.MethodHandles.filterRepeatedArgument(MethodHandles.java:5716)
17:58:13  	at java.base/java.lang.invoke.MethodHandles.filterArguments(MethodHandles.java:5697)
17:58:13  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:593)
17:58:13  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:365)
17:58:13  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
17:58:13  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
17:58:13  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
17:58:13  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
17:58:13  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:200)
17:58:13  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
17:58:13  	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:742)
17:58:13  	at java.base/java.io.File.exists(File.java:831)
17:58:13  	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1240)
17:58:13  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:418)
17:58:13  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:473)
17:58:13  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:971)
17:58:13  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:969)
17:58:13  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
17:58:13  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:982)
17:58:13  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
17:58:13  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
17:58:13  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
17:58:13  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
17:58:13  	at WithSecurityManager.main(WithSecurityManager.java:55)
17:58:13  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:58:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
17:58:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
17:58:13  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by JasonFengJ9** [comment]
[JDK21 aarch64_linux](https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/50/)(`cent8-aarch64-2`)
```
[2023-09-06T21:47:54.108Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2023-09-06T21:47:54.108Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

[2023-09-06T21:58:13.055Z] TEST: java/lang/String/concat/WithSecurityManager.java

[2023-09-06T21:58:13.056Z] java.lang.LinkageError: A duplicate class definition for java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLL is found
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.ClassLoader.defineClassImpl1(Native Method)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:510)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.Access.defineClass(Access.java:347)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2511)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2486)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.ClassSpecializer$Factory.generateConcreteSpeciesCode(ClassSpecializer.java:580)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.ClassSpecializer$Factory.loadSpecies(ClassSpecializer.java:497)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.ClassSpecializer.findSpecies(ClassSpecializer.java:200)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.BoundMethodHandle$SpeciesData.extendWith(BoundMethodHandle.java:360)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.LambdaFormEditor.newSpeciesData(LambdaFormEditor.java:516)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.LambdaFormEditor.makeRepeatedFilterForm(LambdaFormEditor.java:759)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.LambdaFormEditor.filterRepeatedArgumentForm(LambdaFormEditor.java:737)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.MethodHandles.filterRepeatedArgument(MethodHandles.java:5716)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.MethodHandles.filterArguments(MethodHandles.java:5697)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:593)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:365)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:200)
[2023-09-06T21:58:13.056Z] 	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:742)
[2023-09-06T21:58:13.056Z] 	at java.base/java.io.File.exists(File.java:831)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1240)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:418)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:473)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:971)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:969)
[2023-09-06T21:58:13.056Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:982)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
[2023-09-06T21:58:13.056Z] 	at WithSecurityManager.main(WithSecurityManager.java:55)
[2023-09-06T21:58:13.056Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-09-06T21:58:13.056Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-09-06T21:58:13.056Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-09-06T21:58:13.056Z] 
[2023-09-06T21:58:13.056Z] JavaTest Message: Test threw exception: java.lang.LinkageError: A duplicate class definition for java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLL is found
[2023-09-06T21:58:13.056Z] JavaTest Message: shutting down test

[2023-09-06T22:03:03.437Z] jdk_lang_1_FAILED
```
[50x internal grinder](https://openj9-jenkins.osuosl.org/job/Grinder/2892/)
