### ISSUE TITLE
threadMXBeanTestSuite2 testDeadlocks threadIds is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17840]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/584
threadMXBeanTestSuite2_0
```
FAILED: testDeadlocks
java.lang.AssertionError: 		FAIL - threadIds is null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.assertNotEquals(Assert.java:1157)
	at org.openj9.test.java.lang.management.ThreadMXBean.Deadlocks.testDeadlocks(Deadlocks.java:98)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/598/
threadMXBeanTestSuite2_3
```
FAILED: testDeadlocks
java.lang.AssertionError: 		FAIL - threadIds is null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.assertNotEquals(Assert.java:1157)
	at org.openj9.test.java.lang.management.ThreadMXBean.Deadlocks.testDeadlocks(Deadlocks.java:98)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/603

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/871

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_extended.functional_aarch64_linux_Nightly_testList_1/20

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/885
