### ISSUE TITLE
JLM_Tests_class_SE80_0 FAILED: testThreadMXBeanProxy AssertionError: expected:<53> but was:<54>

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17866]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly_testList_0/568/consoleFull`win2019-x64-4a`:
```
02:02:34  openjdk version "1.8.0_382-internal"
02:02:34  OpenJDK Runtime Environment (build 1.8.0_382-internal-****_2023_07_26_22_02-b00)
02:02:34  Eclipse OpenJ9 VM (build master-6140e2ff3fe, JRE 1.8.0 Windows Server 2019 amd64-64-Bit Compressed References 20230726_605 (JIT enabled, AOT enabled)
02:02:34  OpenJ9   - 6140e2ff3fe
02:02:34  OMR      - 1dd4e595421
02:02:34  JCL      - 535df28a5e2 based on jdk8u382-b04)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=JLM_Tests_class_SE80_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Nightly&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK8_x86-64_windows_Nightly%2F605%2FOpenJ9-JDK8-x86-64_windows-20230726-220225.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK8_x86-64_windows_Nightly%2F605%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=6140e2ff3fe38897505dcee2a0ddde9ec6e82e03&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=570&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
03:33:24  variation: NoOptions
03:33:25  JVM_OPTIONS:  

03:33:35  FAILED: testThreadMXBeanProxy
03:33:35  java.lang.AssertionError: expected:<53> but was:<54>
03:33:35  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
03:33:35  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
03:33:35  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
03:33:35  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:170)
03:33:35  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:177)
03:33:35  	at org.openj9.test.java.lang.management.TestManagementFactory.testThreadMXBeanProxy(TestManagementFactory.java:1316)
03:33:35  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:33:35  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:33:35  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:33:35  	at java.lang.reflect.Method.invoke(Method.java:498)
03:33:35  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
03:33:35  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
03:33:35  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
03:33:35  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
03:33:35  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
03:33:35  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
03:33:35  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
03:33:35  	at org.testng.TestRunner.run(TestRunner.java:505)
03:33:35  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
03:33:35  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
03:33:35  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
03:33:35  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
03:33:35  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
03:33:35  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
03:33:35  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
03:33:35  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
03:33:35  	at org.testng.TestNG.runSuites(TestNG.java:1049)
03:33:35  	at org.testng.TestNG.run(TestNG.java:1017)
03:33:35  	at org.testng.TestNG.privateMain(TestNG.java:1354)
03:33:35  	at org.testng.TestNG.main(TestNG.java:1323)
03:33:35  
03:33:35  
03:33:35  ===============================================
03:33:35      JLM_Tests_class
03:33:35      Tests run: 66, Failures: 1, Skips: 0
03:33:35  ===============================================
03:33:35  
03:33:35  
03:33:35  ===============================================
03:33:35  JLM_Tests_Suite
03:33:35  Total tests run: 66, Failures: 1, Skips: 0
03:33:35  ===============================================
03:33:35  
03:33:35  -----------------------------------
03:33:35  JLM_Tests_class_SE80_0_FAILED
```

[50x grinder](https://openj9-jenkins.osuosl.org/job/Grinder/2631/)

**Comment by JasonFengJ9** [comment]
[JDK11 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_testList_2/523/)(`win22x86-svl-rt5-1`)
```
[2024-05-16T03:11:25.574Z] variation: NoOptions
[2024-05-16T03:11:25.574Z] JVM_OPTIONS:  

[2024-05-16T03:11:45.599Z] FAILED: testThreadMXBeanProxy
[2024-05-16T03:11:45.599Z] java.lang.AssertionError: expected:<17> but was:<16>
[2024-05-16T03:11:45.599Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2024-05-16T03:11:45.599Z] 	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
[2024-05-16T03:11:45.599Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
[2024-05-16T03:11:45.599Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
[2024-05-16T03:11:45.599Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
[2024-05-16T03:11:45.599Z] 	at org.openj9.test.java.lang.management.TestManagementFactory.testThreadMXBeanProxy(TestManagementFactory.java:1277)

[2024-05-16T03:11:45.599Z] ===============================================
[2024-05-16T03:11:45.599Z]     JLM_Tests_class
[2024-05-16T03:11:45.599Z]     Tests run: 66, Failures: 1, Skips: 0
[2024-05-16T03:11:45.599Z] ===============================================
[2024-05-16T03:11:45.599Z] 
[2024-05-16T03:11:45.599Z] 
[2024-05-16T03:11:45.599Z] ===============================================
[2024-05-16T03:11:45.599Z] JLM_Tests_Suite
[2024-05-16T03:11:45.599Z] Total tests run: 66, Failures: 1, Skips: 0
[2024-05-16T03:11:45.599Z] ===============================================
[2024-05-16T03:11:45.599Z] 
[2024-05-16T03:11:46.487Z] -----------------------------------
[2024-05-16T03:11:46.487Z] JLM_Tests_class_0_FAILED
```
