### ISSUE TITLE
jdk_lang_1_FAILED java/lang/String/concat/WithSecurityManager.java Cannot invoke "java.util.concurrent.atomic.AtomicLong.getAndAdd(long)" because "java.util.concurrent.ThreadLocalRandom.seeder" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17867]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/19/consoleFull `ub16p8j92`:
```
20:35:55  openjdk version "17.0.8-internal" 2023-07-18
20:35:55  OpenJDK Runtime Environment (build 17.0.8-internal+0-adhoc.****.BuildJDK17ppc64lelinuxNightly)
20:35:55  Eclipse OpenJ9 VM (build master-6140e2ff3fe, JRE 17 Linux ppc64le-64-Bit Compressed References 20230726_539 (JIT enabled, AOT enabled)
20:35:55  OpenJ9   - 6140e2ff3fe
20:35:55  OMR      - 1dd4e595421
20:35:55  JCL      - 7511966f525 based on jdk-17.0.8+7)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_lang_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Nightly&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_ppc64le_linux_Nightly%2F539%2FOpenJ9-JDK17-ppc64le_linux-20230726-200608.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_ppc64le_linux_Nightly%2F539%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=6140e2ff3fe38897505dcee2a0ddde9ec6e82e03&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=520&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
20:42:40  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
20:42:40  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

20:53:59  TEST: java/lang/String/concat/WithSecurityManager.java

20:53:59  STDERR:
20:53:59  WARNING: A terminally deprecated method in java.lang.System has been called
20:53:59  WARNING: System::setSecurityManager has been called by WithSecurityManager (file:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/output_16904185585697/jdk_lang_1/work/classes/0/java/lang/String/concat/WithSecurityManager.d/)
20:53:59  WARNING: Please consider reporting this to the maintainers of WithSecurityManager
20:53:59  WARNING: System::setSecurityManager will be removed in a future release
20:53:59  Exception in thread "Attach API wait loop" java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicLong.getAndAdd(long)" because "java.util.concurrent.ThreadLocalRandom.seeder" is null
20:53:59  	at java.base/java.util.concurrent.ThreadLocalRandom.localInit(ThreadLocalRandom.java:172)
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2590)
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2339)
20:53:59  java.lang.ExceptionInInitializerError	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1178)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1107)
20:53:59  	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.expungeStaleElements(MethodType.java:1407)
20:53:59  	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:206)	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(MethodType.java:1366)
20:53:59  
20:53:59  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:195)	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:341)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ThreadLocalRandom.<clinit>(ThreadLocalRandom.java:399)	at java.base/java.lang.invoke.LambdaForm.methodType(LambdaForm.java:625)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2589)	at java.base/java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:220)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2339)	at java.base/java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:227)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1178)	at java.base/java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:108)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1107)	at java.base/java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:129)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.expungeStaleElements(MethodType.java:1407)	at java.base/java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:134)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(MethodType.java:1366)	at java.base/java.lang.invoke.Invokers.basicInvoker(Invokers.java:97)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:341)	at java.base/java.lang.invoke.LambdaForm$NamedFunction.<init>(LambdaForm.java:1105)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodType.methodType(MethodType.java:293)	at java.base/java.lang.invoke.LambdaForm$Name.<init>(LambdaForm.java:1358)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MemberName.getMethodOrFieldType(MemberName.java:120)	at java.base/java.lang.invoke.Invokers.callSiteForm(Invokers.java:606)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MemberName.getInvocationType(MemberName.java:193)	at java.base/java.lang.invoke.Invokers.linkToTargetMethod(Invokers.java:574)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.InvokerBytecodeGenerator.emitStaticInvoke(InvokerBytecodeGenerator.java:1101)	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:288)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.InvokerBytecodeGenerator.addMethod(InvokerBytecodeGenerator.java:903)	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCodeBytes(InvokerBytecodeGenerator.java:794)	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:201)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:752)	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:854)	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1160)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.LambdaForm.prepare(LambdaForm.java:812)	at java.base/java.lang.System.getProperty(System.java:621)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:481)	at java.base/java.lang.System.getProperty(System.java:604)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:56)	at java.base/sun.security.action.GetPropertyAction.run(GetPropertyAction.java:87)
20:53:59  
20:53:59  	at java.lang.invoke.BoundMethodHandle$Species_LLLLLLLLLLLL.<init>(java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLLLLL)	at java.base/sun.security.action.GetPropertyAction.run(GetPropertyAction.java:53)
20:53:59  
20:53:59  	at java.lang.invoke.BoundMethodHandle$Species_LLLLLLLLLLLL.make(java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLLLLL)	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
20:53:59  
20:53:59  	at java.lang.invoke.BoundMethodHandle$Species_LLLLLLLLLLL.copyWithExtendL(java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLLLL)	at java.base/jdk.internal.util.random.RandomSupport.secureRandomSeedRequested(RandomSupport.java:759)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandles.argumentsWithCombiner(MethodHandles.java:6157)	at java.base/jdk.internal.util.random.RandomSupport.<clinit>(RandomSupport.java:765)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandles.filterArgumentsWithCombiner(MethodHandles.java:6114)	at java.base/java.util.concurrent.ThreadLocalRandom.<clinit>(ThreadLocalRandom.java:399)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:597)	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2589)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:358)	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2339)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1178)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1107)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.expungeStaleElements(MethodType.java:1407)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(MethodType.java:1366)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:201)	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:341)
20:53:59  
20:53:59  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)	at java.base/java.lang.invoke.MethodType.methodType(MethodType.java:293)
20:53:59  
20:53:59  	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
20:53:59  	at java.base/java.lang.invoke.MemberName.getMethodOrFieldType(MemberName.java:120)	at java.base/java.io.File.exists(File.java:829)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MemberName.getInvocationType(MemberName.java:193)
20:53:59  	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1394)	at java.base/java.lang.invoke.InvokerBytecodeGenerator.emitStaticInvoke(InvokerBytecodeGenerator.java:1101)
20:53:59  
20:53:59  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:421)
20:53:59  	at java.base/java.lang.invoke.InvokerBytecodeGenerator.addMethod(InvokerBytecodeGenerator.java:903)	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:476)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCodeBytes(InvokerBytecodeGenerator.java:794)
20:53:59  	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:971)
20:53:59  	at java.base/java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:752)	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:969)
20:53:59  
20:53:59  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)	at java.base/java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:854)
20:53:59  
20:53:59  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:982)	at java.base/java.lang.invoke.LambdaForm.prepare(LambdaForm.java:812)
20:53:59  
20:53:59  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)	at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:481)
20:53:59  
20:53:59  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)	at java.base/java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:56)
20:53:59  
20:53:59  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)	at java.lang.invoke.BoundMethodHandle$Species_LLLLLLLLLLLL.<init>(java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLLLLL)
20:53:59  
20:53:59  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1095)	at java.lang.invoke.BoundMethodHandle$Species_LLLLLLLLLLLL.make(java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLLLLL)
20:53:59  
20:53:59  	at WithSecurityManager.main(WithSecurityManager.java:55)	at java.lang.invoke.BoundMethodHandle$Species_LLLLLLLLLLL.copyWithExtendL(java/lang/invoke/BoundMethodHandle$Species_LLLLLLLLLLL)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandles.argumentsWithCombiner(MethodHandles.java:6157)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandles.filterArgumentsWithCombiner(MethodHandles.java:6114)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:597)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:358)	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:144)	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)	at java.base/java.lang.Thread.run(Thread.java:857)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
20:53:59  Caused by: 	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicLong.getAndAdd(long)" because "java.util.concurrent.ThreadLocalRandom.seeder" is null
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:201)
20:53:59  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
20:53:59  	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
20:53:59  	at java.base/java.io.File.exists(File.java:829)
20:53:59  	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1394)
20:53:59  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:421)
20:53:59  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:476)
20:53:59  	at java.base/java.util.concurrent.ThreadLocalRandom.localInit(ThreadLocalRandom.java:172)	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:971)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.fullAddCount(ConcurrentHashMap.java:2590)	at java.base/jdk.internal.loader.BuiltinClassLoader$6.run(BuiltinClassLoader.java:969)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2339)	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1178)	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:982)
20:53:59  
20:53:59  	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1107)
20:53:59  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
20:53:59  	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.expungeStaleElements(MethodType.java:1407)	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(MethodType.java:1366)	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:341)	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1095)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.LambdaForm.methodType(LambdaForm.java:625)	at WithSecurityManager.main(WithSecurityManager.java:55)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:220)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:227)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:108)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:129)	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:134)	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.Invokers.basicInvoker(Invokers.java:97)	at java.base/java.lang.Thread.run(Thread.java:857)
20:53:59  
20:53:59  	at java.base/java.lang.invoke.LambdaForm$NamedFunction.<init>(LambdaForm.java:1105)
20:53:59  	at java.base/java.lang.invoke.LambdaForm$Name.<init>(LambdaForm.java:1358)
20:53:59  	at java.base/java.lang.invoke.Invokers.callSiteForm(Invokers.java:606)
20:53:59  	at java.base/java.lang.invoke.Invokers.linkToTargetMethod(Invokers.java:574)
20:53:59  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:288)
20:53:59  	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
20:53:59  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:201)
20:53:59  	at WithSecurityManager$1.checkPermission(WithSecurityManager.java:49)
20:53:59  	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1160)
20:53:59  	at java.base/java.lang.System.getProperty(System.java:621)
20:53:59  	at java.base/java.lang.System.getProperty(System.java:604)
20:53:59  	at java.base/sun.security.action.GetPropertyAction.run(GetPropertyAction.java:87)
20:53:59  	at java.base/sun.security.action.GetPropertyAction.run(GetPropertyAction.java:53)
20:53:59  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
20:53:59  	at java.base/jdk.internal.util.random.RandomSupport.secureRandomSeedRequested(RandomSupport.java:759)
20:53:59  	at java.base/jdk.internal.util.random.RandomSupport.<clinit>(RandomSupport.java:765)
20:53:59  	... 52 more
20:53:59  
20:53:59  JavaTest Message: Test threw exception: java.lang.ExceptionInInitializerError

20:53:59  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicLong.getAndAdd(long)" because "java.util.concurrent.ThreadLocalRandom.seeder" is null
20:53:59  --------------------------------------------------
20:56:54  Test results: passed: 807; failed: 1
20:57:11  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/output_16904185585697/jdk_lang_1/report/html/report.html
20:57:11  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/aqa-tests/TKG/output_16904185585697/jdk_lang_1/work
20:57:11  Error: Some tests failed or other problems occurred.
20:57:11  -----------------------------------
20:57:11  jdk_lang_1_FAILED
```

[50x grinder](https://openj9-jenkins.osuosl.org/job/Grinder/2632/) - passed

**Comment by pshipton** [comment]
The grinder passed. Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/16609
