### ISSUE TITLE
[FFI/Jtreg_JDK21] AssertionError detected in TestCaptureCallState.java on Windows

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17873]
One of the subtests in `TestCaptureCallState.java` at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/capturecallstate/TestCaptureCallState.java failed with the following errors:
```
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@8260b903): failure
java.lang.AssertionError: expected [42] but found [0]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState.java:85)
```

FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
We used to solve the issue with the returned error code via https://github.com/eclipse-openj9/openj9/pull/17127 but the FFI code at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/src/java.base/share/classes/jdk/internal/foreign/abi/CapturableState.java#L38 has been updated in JDK21 to different Winodws and other platforms as follows:
```
public enum CapturableState {
    GET_LAST_ERROR    ("GetLastError",    JAVA_INT, 1 << 0, Utils.IS_WINDOWS),
    WSA_GET_LAST_ERROR("WSAGetLastError", JAVA_INT, 1 << 1, Utils.IS_WINDOWS),
    ERRNO             ("errno",           JAVA_INT, 1 << 2, true);
```
against the layout ouput & size on Windows:
```
capturedStateLayout = [i4(GetLastError)i4(WSAGetLastError)i4(errno)]
capturedStateLayout.byteSize = 12
```
and Linux:
```
capturedStateLayout = [i4(errno)]
capturedStateLayout.byteSize = 4
```
That being said, the return error segment on Windows become an array of 3 integers (e.g. int err[3]) since JDK21, in which case
`err[0]` should be set to the return value from `GetLastError()`
`err[1]` should be set to the return value from `WSAGetLastError()`
`err[2]` should be set to the predefined `errno`.

I will double-check the related code in OpenJ9 to see how to get this addressed on Windows.

**Comment by ChengJin01** [comment]
I will get back to keep working on this issue later after my vacation next week.

**Comment by ChengJin01** [comment]
With my fix at https://github.com/ChengJin01/openj9/commit/6c9e56aca108a962c473b21c74e8549da7f069b7, it proves to work correctly on Windows as follows:
```
----------System.out:(22/2046)----------
NativeTestHelper::DEFAULT_RANDOM.seed = -796278458
Re-run with '-DNativeTestHelper.DEFAULT_RANDOM.seed=-796278458' to reproduce
test TestCaptureCallState.testInvalidCaptureSegment(jdk.internal.foreign.NativeMemorySegmentImpl@7bc3d799, java.lang.Class@5e294a47, ".*Out of bound access on segment.*"): success
test TestCaptureCallState.testInvalidCaptureSegment(jdk.internal.foreign.NativeMemorySegmentImpl@f37f7532, java.lang.Class@941cce5d, ".*Capture segment is NULL.*"): success
test TestCaptureCallState.testInvalidCaptureSegment(jdk.internal.foreign.NativeMemorySegmentImpl@934cda05, java.lang.Class@941cce5d, ".*Target offset incompatible with alignment constraints.*"): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@fa22fbb5): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@a12b1c76): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@e8eb37eb): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@195efc80): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@e714f833): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@eca14cd5): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@106d2f9e): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@7b6a085f): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@fc1f6436): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@7a6f2c9c): success
test TestCaptureCallState.testSavedThreadLocal(TestCaptureCallState$SaveValuesCase@7dad6369): success

===============================================
test/jdk/java/foreign/capturecallstate/TestCaptureCallState.java
Total tests run: 14, Passes: 14, Failures: 0, Skips: 0
===============================================
```
