### ISSUE TITLE
[Linux PPC LE 64bit Compressed Pointers] 80 Load_Level_2.mauve.5mins.Mode555.4 NPE at java.text.DecimalFormatSymbols.equals(DecimalFormatSymbols.java:596)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17880]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=65052456)(`rhel7lertp1-1`):
```
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pxl6480sr9-20230615_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20230728_55291 (JIT enabled, AOT enabled)
OpenJ9   - a583b4a
OMR      - fe2d517
IBM      - 696e9df)
JCL - 20230608_01 based on Oracle jdk8u381-b06
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
make -f "/bluebird/javatest/HEAD_382595/test/SVT/stress/makefile" SITE=ottawa STREAM=default PLATFORM=linux_ppcle-64_cr JAVA_LANG_LEVEL=80 JVM_VERSION=29 JAVA_VERSION=80 BUILD_ID=55291 JOB_ID=65052456 PLAYLIST_ROOT='/bluebird/javatest/HEAD_382595/test/playlists' JVM_TEST_ROOT='/bluebird/builds/bld_55291/jvmtest' MODULARITY_TEST= JAVASVT_ROOT=/bluebird/javatest/HEAD_382595/javasvt JAVASVT_PREREQS_ROOT=/bluebird/javatest/HEAD_382595/javasvt_prereqs VARIATION=Mode555 _mauve.5mins

j> 05:52:51 20230728 05:52:51 Execution Timer INFO: Execution Timer started
j> 05:52:51 20230728 05:52:51 Thread Control Engine INFO: Starting JobSet Primary
j> 05:52:55 20230728 05:52:55 <Primary|SimpleDriver|gnu.testlet.java.text.DateFormat.Test|916|Default Invocant> ERROR: Exception thrown from arbitrary java method public static void gnu.testlet.SingleTestHarness.main(java.lang.String[]) throws java.lang.Exception
j> 05:52:55 Throwable trace:
j> 05:52:55 java.lang.NullPointerException
j> 05:52:55 	at java.text.DecimalFormatSymbols.equals(DecimalFormatSymbols.java:596)
j> 05:52:55 	at java.text.DecimalFormat.equals(DecimalFormat.java:2782)
j> 05:52:55 	at java.text.DateFormat.equals(DateFormat.java:766)
j> 05:52:55 	at gnu.testlet.java.text.DateFormat.Test.test(Unknown Source)
j> 05:52:55 	at gnu.testlet.SingleTestHarness.main(Unknown Source)
j> 05:52:55 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
j> 05:52:55 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
j> 05:52:55 	at java.lang.reflect.Method.invoke(Method.java:508)
j> 05:52:55 	at com.ibm.jtc.test.jltf.workunitadapters.ArbitraryJavaWorkUnit.runWork(ArbitraryJavaWorkUnit.java:445)
j> 05:52:55 	at com.ibm.jtc.test.jltf.threads.WorkUnitRunner.run(WorkUnitRunner.java:113)
j> 05:52:55 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.runWork(PooledRunnable.java:170)
j> 05:52:55 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:136)
j> 05:52:55 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 05:52:55 	at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
```

[100x internal grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=55298) - passed

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=100932044
[zOS S390 64bit Compressed Pointers] 80 Load_Level_2.mauve.5mins.Mode553
fyrec605
```
j> 13:14:40 20250131 13:14:39 <Primary|SimpleDriver|gnu.testlet.java.text.DateFormat.Test|131|Default Invocant> ERROR: Exception thrown from arbitrary java method public static void gnu.testlet.SingleTestHarness.main(java.lang.String[]) throws java.lang.Exception
j> 13:14:40 Throwable trace:
j> 13:14:40 java.lang.NullPointerException
j> 13:14:40 	at java.text.DecimalFormatSymbols.equals(DecimalFormatSymbols.java:595)
j> 13:14:40 	at java.text.DecimalFormat.equals(DecimalFormat.java:2782)
j> 13:14:40 	at java.text.DateFormat.equals(DateFormat.java:766)
j> 13:14:40 	at gnu.testlet.java.text.DateFormat.Test.test(Unknown Source)
j> 13:14:40 	at gnu.testlet.SingleTestHarness.main(Unknown Source)
```

100x grinder http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=87021

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=119279401 - rtv-rhel9s390x-svl-test-sms02
[Linux S390 64bit Compressed Pointers] 80 Load_Level_2.mauve.5mins.Mode555
`-XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:counts="- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000",gcOnResolve,rtResolve,sampleInterval=2,scorchingSampleThreshold=10000,quickProfile -Xcheck:gc:vmthreads:all:quiet`
