### ISSUE TITLE
OpenJDK java/lang/RuntimeTests/shutdown/Basic timeout FileInputStream.readBytes

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17908]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/24/ - [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3)
jdk_lang_j9_0
java/lang/RuntimeTests/shutdown/Basic.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/24/openjdk_test_output.tar.gz
```
02:12:43  Timeout information:
02:12:43  Running jcmd on process 42790
02:12:43  Dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16909536918924/jdk_lang_j9_0/work/scratch/1/core.20230802.021154.42790.0001.dmp
02:12:43  Dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16909536918924/jdk_lang_j9_0/work/scratch/1/javacore.20230802.021236.42790.0002.txt
02:12:43  Running jstack on process 42790
02:12:43  2023-08-02T02:12:38.306738901
02:12:43  Virtual machine: 42790 JVM information:
02:12:43  JRE 17 Linux s390x-64-Bit 20230801_542 (JIT enabled, AOT enabled)
02:12:43  OpenJ9   - 12a73e99106
02:12:43  OMR      - 43a2b1d3416
02:12:43  JCL      - 31bcd9f4205 based on jdk-17.0.8+7
02:12:43  
02:12:43  "main" prio=5 Id=1 WAITING
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.waitImpl(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:251)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:219)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.join(Thread.java:784)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.join(Thread.java:739)
02:12:43  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:198)
02:12:43  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
02:12:43  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
02:12:43  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
02:12:43  
02:12:43  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
02:12:43  
02:12:43  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
02:12:43  
02:12:43  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
02:12:43  
02:12:43  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
02:12:43  
02:12:43  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
02:12:43  
02:12:43  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
02:12:43  
02:12:43  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
02:12:43  
02:12:43  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
02:12:43  
02:12:43  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
02:12:43  
02:12:43  "IProfiler" prio=5 Id=12 RUNNABLE
02:12:43  
02:12:43  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.waitImpl(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:251)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:219)
02:12:43  	at java.base@17.0.8-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.run(Thread.java:857)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
02:12:43  
02:12:43  "Dedicated GC Main" prio=5 Id=13 RUNNABLE
02:12:43  
02:12:43  "GC Worker" prio=5 Id=14 RUNNABLE
02:12:43  
02:12:43  "GC Worker" prio=5 Id=15 RUNNABLE
02:12:43  
02:12:43  "GC Worker" prio=5 Id=16 RUNNABLE
02:12:43  
02:12:43  "Attach API wait loop" prio=10 Id=19 RUNNABLE
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
02:12:43  
02:12:43  "pool-1-thread-1" prio=5 Id=20 TIMED_WAITING
02:12:43  	at java.base@17.0.8-internal/jdk.internal.misc.Unsafe.park(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.run(Thread.java:857)
02:12:43  
02:12:43  "Finalizer thread" prio=5 Id=21 RUNNABLE
02:12:43  
02:12:43  "process reaper (pid 45796)" prio=10 Id=729 RUNNABLE
02:12:43  	at java.base@17.0.8-internal/java.lang.ProcessHandleImpl.waitForProcessExit0(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:150)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.run(Thread.java:857)
02:12:43  
02:12:43  "AgentVMThread" prio=5 Id=733 WAITING
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.waitImpl(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:251)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:190)
02:12:43  	at java.base@17.0.8-internal/java.lang.ProcessImpl.waitFor(ProcessImpl.java:434)
02:12:43  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:445)
02:12:43  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:417)
02:12:43  	at jdk.test.lib.process.ProcessTools.executeProcess(ProcessTools.java:404)
02:12:43  	at jdk.test.lib.process.ProcessTools.executeTestJvm(ProcessTools.java:384)
02:12:43  	at jdk.test.lib.process.ProcessTools.executeTestJava(ProcessTools.java:393)
02:12:43  	at Basic.test(Basic.java:75)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:12:43  	at java.base@17.0.8-internal/java.lang.reflect.Method.invoke(Method.java:568)
02:12:43  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
02:12:43  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
02:12:43  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
02:12:43  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
02:12:43  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
02:12:43  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
02:12:43  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
02:12:43  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
02:12:43  	at java.base@17.0.8-internal/java.util.ArrayList.forEach(ArrayList.java:1511)
02:12:43  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
02:12:43  	at app//org.testng.TestRunner.run(TestRunner.java:585)
02:12:43  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
02:12:43  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
02:12:43  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
02:12:43  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
02:12:43  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
02:12:43  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
02:12:43  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
02:12:43  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
02:12:43  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
02:12:43  	at app//org.testng.TestNG.run(TestNG.java:1037)
02:12:43  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
02:12:43  	at java.base@17.0.8-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:12:43  	at java.base@17.0.8-internal/java.lang.reflect.Method.invoke(Method.java:568)
02:12:43  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.run(Thread.java:857)
02:12:43  
02:12:43  "Thread-621" prio=5 Id=744 RUNNABLE
02:12:43  	at java.base@17.0.8-internal/java.io.FileInputStream.readBytes(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.io.FileInputStream.read(FileInputStream.java:276)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
02:12:43  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@29842888
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
02:12:43  	- locked java.io.BufferedInputStream@d5d1ebb1
02:12:43  	at java.base@17.0.8-internal/java.io.FilterInputStream.read(FilterInputStream.java:106)
02:12:43  	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.run(Thread.java:857)
02:12:43  
02:12:43  "Thread-622" prio=5 Id=745 RUNNABLE
02:12:43  	at java.base@17.0.8-internal/java.io.FileInputStream.readBytes(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.io.FileInputStream.read(FileInputStream.java:276)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
02:12:43  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@b234d5d3
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
02:12:43  	at java.base@17.0.8-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
02:12:43  	- locked java.io.BufferedInputStream@d4ab0809
02:12:43  	at java.base@17.0.8-internal/java.io.FilterInputStream.read(FilterInputStream.java:106)
02:12:43  	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02:12:43  	at java.base@17.0.8-internal/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:12:43  	at java.base@17.0.8-internal/java.lang.Thread.run(Thread.java:857)
02:12:43  
02:12:43  "file lock watchdog" prio=10 Id=747 TIMED_WAITING
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.waitImpl(Native Method)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:251)
02:12:43  	at java.base@17.0.8-internal/java.lang.Object.wait(Object.java:219)
02:12:43  	at java.base@17.0.8-internal/java.util.TimerThread.mainLoop(Timer.java:599)
02:12:43  	at java.base@17.0.8-internal/java.util.TimerThread.run(Timer.java:542)
02:12:43  
02:12:43  "Attachment portNumber: 46268" prio=10 Id=749 RUNNABLE
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
02:12:43  	at java.base@17.0.8-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
02:12:43  
02:12:43  
02:12:43  --- Timeout information end.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/41 - [ub16x64j96](https://openj9-jenkins.osuosl.org/computer/ub16x64j96)
jdk_lang_1
