### ISSUE TITLE
DaaLoadTest_daa1_special_5m StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17926]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_aarch64_linux_Release_testList_3/59
DaaLoadTest_daa1_special_5m_6 `-Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_special.system_aarch64_linux_Release_testList_3/59/system_test_output.tar.gz
```
DLT 22:13:55.318 - Completed 31.8%. Number of tests started=44 (+5)
DLT 22:13:55.812 - First failure detected by thread: load-3. Not creating dumps as no dump generation is requested for this load test
DLT 22:13:56.036 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa1.xml
DLT 22:13:56.051 - Test failed. Details recorded in execution log.
DLT 22:13:56.129 - Completed 33.7%. Number of tests started=55 (+11) (with 2 failure(s))
DLT 22:13:56.539 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa1.xml
DLT 22:13:56.546 - Test failed. Details recorded in execution log.
DLT 22:13:56.978 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa1.xml
DLT 22:13:56.979 - Test failed. Details recorded in execution log.
DLT 22:13:58.316 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa1.xml
DLT 22:13:58.316 - Test failed. Details recorded in execution log.
DLT 22:13:58.340 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa1.xml
DLT 22:13:58.341 - Test failed. Details recorded in execution log.
DLT 22:13:58.341 - Number of test failures has reached 'AbortAtFailureLimit' (10). Terminating load test
DLT 22:13:58.349 - Thread completed. Suite=0 thread=3
DLT 22:13:58.349 - Thread completed. Suite=0 thread=4
DLT 22:13:58.361 - Thread completed. Suite=0 thread=5
DLT 22:13:58.378 - Thread completed. Suite=0 thread=2
DLT 22:13:58.705 - Thread completed. Suite=0 thread=0
DLT 22:13:58.714 - Thread completed. Suite=0 thread=1
DLT 22:13:58.809 - Load test completed
DLT 22:13:58.809 -   Ran     : 110
DLT 22:13:58.809 -   Passed  : 105
DLT 22:13:58.809 -   Failed  : 10
DLT 22:13:58.809 -   Result  : FAILED
DLT 22:13:58.816 - Note that only the first 1 failures have been reported
STF 22:13:59.416 - **FAILED** Process DLT ended with exit code (1) and not the expected exit code/s (0)
```
```
testFailure: testConvertBigDecimalNormals(net.openj9.test.decimals.TestDecimalData): offset -4, count 110, length 72
java.lang.StringIndexOutOfBoundsException: offset -4, count 110, length 72
	at java.base/java.lang.String.checkBoundsOffCount(String.java:5361)
	at java.base/java.lang.StringUTF16.checkBoundsOffCount(StringUTF16.java:1636)
	at java.base/java.lang.StringUTF16.inflate(StringUTF16.java:1462)
	at java.base/java.lang.StringLatin1.inflate(StringLatin1.java:788)
	at java.base/java.lang.String.getBytes(String.java:5229)
	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:354)
	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:373)
	at net.openj9.test.Utils.makeTestNameConverterValue(Utils.java:787)
	at net.openj9.test.decimals.TestDecimalData.testConvertBigDecimalNormals(TestDecimalData.java:6812)

testFailure: testNonExceptions(net.openj9.test.decimals.TestDecimalData): offset -4, count 112, length 73
java.lang.StringIndexOutOfBoundsException: offset -4, count 112, length 73
	at java.base/java.lang.String.checkBoundsOffCount(String.java:5361)
	at java.base/java.lang.StringUTF16.checkBoundsOffCount(StringUTF16.java:1636)
	at java.base/java.lang.StringUTF16.inflate(StringUTF16.java:1462)
	at java.base/java.lang.StringLatin1.inflate(StringLatin1.java:788)
	at java.base/java.lang.String.getBytes(String.java:5229)
	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:354)
	at java.base/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:373)
	at net.openj9.test.Utils.makeTestNameConverterValue(Utils.java:787)
	at net.openj9.test.decimals.TestDecimalData.testConvertBigDecimalNormals(TestDecimalData.java:6812)
	at net.openj9.test.decimals.TestDecimalData.testNonExceptions(TestDecimalData.java:101)

```

**Comment by pshipton** [comment]
Seems related to https://github.com/eclipse-openj9/openj9/issues/16527
