### ISSUE TITLE
OpenJDK java/lang/Thread/virtual/ThreadAPI.java timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17946]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/7
jdk_lang_1
java/lang/Thread/virtual/ThreadAPI.java#default
```
12:03:44  ACTION: junit -- Error. Agent error: java.lang.Exception: Agent 7 timed out with a timeout of 960 seconds; check console log for any additional details
12:03:44  REASON: User specified action: run junit ThreadAPI 
12:03:44  TIME:   961.164 seconds
12:03:44  messages:
12:03:44  command: junit ThreadAPI
12:03:44  reason: User specified action: run junit ThreadAPI 
12:03:44  started: Sat Aug 12 01:47:29 AEST 2023
12:03:44  Mode: agentvm
12:03:44  Agent id: 7
12:03:44  Additional exports to unnamed modules from @modules: java.base/java.lang
12:03:44  Additional opens to unnamed modules from @modules: java.base/java.lang
12:03:44  Timeout refired 960 times
12:03:44  Timeout information:
12:03:44  Running jcmd on process 56412
12:03:44  Error getting data from 56412: Exception connecting to 56412
12:03:44  Usage : jcmd <vmid> <arguments>
12:03:44  
12:03:44     -J : supply arguments to the Java VM running jcmd
12:03:44     -l : list JVM processes on the local machine
12:03:44     -h : print this help message
12:03:44  
12:03:44     <vmid> : Attach API VM ID as shown in jps or other Attach API-based tools
12:03:44  
12:03:44     arguments:
12:03:44        help : print the list of diagnostic commands
12:03:44        help <command> : print help for the specific command
12:03:44        <command> [command arguments] : command from the list returned by "help"
12:03:44  
12:03:44  list JVM processes on the local machine. Default behavior when no options are specified.
12:03:44  
12:03:44  NOTE: this utility might significantly affect the performance of the target JVM.
12:03:44      The available diagnostic commands are determined by
12:03:44      the target VM and may vary between VMs.
12:03:44  Error getting data from 56412: Exception connecting to 56412
12:03:44  Usage : jcmd <vmid> <arguments>
12:03:44  
12:03:44     -J : supply arguments to the Java VM running jcmd
12:03:44     -l : list JVM processes on the local machine
12:03:44     -h : print this help message
12:03:44  
12:03:44     <vmid> : Attach API VM ID as shown in jps or other Attach API-based tools
12:03:44  
12:03:44     arguments:
12:03:44        help : print the list of diagnostic commands
12:03:44        help <command> : print help for the specific command
12:03:44        <command> [command arguments] : command from the list returned by "help"
12:03:44  
12:03:44  list JVM processes on the local machine. Default behavior when no options are specified.
12:03:44  
12:03:44  NOTE: this utility might significantly affect the performance of the target JVM.
12:03:44      The available diagnostic commands are determined by
12:03:44      the target VM and may vary between VMs.
12:03:44  Running jstack on process 56412
12:03:44  2023-08-12T02:03:30.651505
12:03:44  Error getting data from 56412: Exception connecting to 56412
12:03:44  --- Timeout information end.
12:03:44  finished: Sat Aug 12 02:03:30 AEST 2023
12:03:44  elapsed time (seconds): 961.164
12:03:44  configuration:
12:03:44  Boot Layer
12:03:44    class path: /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/javatest.jar 
12:03:44                /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/jtreg.jar 
12:03:44                /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/junit-platform-console-standalone-1.9.2.jar 
12:03:44                /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/testng-7.3.0.jar 
12:03:44                /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/guice-4.2.3.jar 
12:03:44                /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/jcommander-1.78.jar 
12:03:44    patch:      java.base /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/patches/java.base
12:03:44  
12:03:44  Test Layer
12:03:44    add exports: java.base/java.lang ALL-UNNAMED
12:03:44    add opens:   java.base/java.lang ALL-UNNAMED
12:03:44    class path:  /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/java/lang/Thread/virtual/ThreadAPI_default.d 
12:03:44                 /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Thread/virtual 
12:03:44                 /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/test/lib 
12:03:44                 /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/lib 
12:03:44  
12:03:44  rerun:
12:03:44  cd /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/scratch/1 && \
12:03:44  HOME=/Users/jenkins \
12:03:44  PATH=/bin:/usr/bin:/usr/sbin \
12:03:44      /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/openjdkbinary/j2sdk-image/bin/java \
12:03:44          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops' \
12:03:44          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-XX:-UseCompressedOops' \
12:03:44          -Dtest.compiler.opts= \
12:03:44          -Dtest.java.opts= \
12:03:44          -Dtest.jdk=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/openjdkbinary/j2sdk-image \
12:03:44          -Dcompile.jdk=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/openjdkbinary/j2sdk-image \
12:03:44          -Dtest.timeout.factor=8.0 \
12:03:44          -Dtest.nativepath=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
12:03:44          -Dtest.root=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk \
12:03:44          -Dtest.name=java/lang/Thread/virtual/ThreadAPI.java#default \
12:03:44          -Dtest.file=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Thread/virtual/ThreadAPI.java \
12:03:44          -Dtest.src=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Thread/virtual \
12:03:44          -Dtest.src.path=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Thread/virtual:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/lib \
12:03:44          -Dtest.classes=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/java/lang/Thread/virtual/ThreadAPI_default.d \
12:03:44          -Dtest.class.path=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/java/lang/Thread/virtual/ThreadAPI_default.d:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/test/lib \
12:03:44          -Dtest.class.path.prefix=/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/java/lang/Thread/virtual/ThreadAPI_default.d:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Thread/virtual:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/test/lib \
12:03:44          -Dtest.modules=java.base/java.lang:+open \
12:03:44          -classpath /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/java/lang/Thread/virtual/ThreadAPI_default.d:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Thread/virtual:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work/classes/2/test/lib:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/openjdk/openjdk-jdk/test/lib:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/junit-platform-console-standalone-1.9.2.jar:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/javatest.jar:/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/jvmtest/openjdk/jtreg/lib/jtreg.jar \
12:03:44          com.sun.javatest.regtest.agent.JUnitRunner java/lang/Thread/virtual/ThreadAPI.java#default ThreadAPI
12:03:44  STDERR:
12:03:44  STARTED    ThreadAPI::testStartVirtualThread 'testStartVirtualThread()'
12:03:44  SUCCESSFUL ThreadAPI::testStartVirtualThread 'testStartVirtualThread()'
12:03:44  STARTED    ThreadAPI::testUncaughtExceptionHandler1 'testUncaughtExceptionHandler1()'
12:03:44  SUCCESSFUL ThreadAPI::testUncaughtExceptionHandler1 'testUncaughtExceptionHandler1()'
12:03:44  STARTED    ThreadAPI::testUncaughtExceptionHandler2 'testUncaughtExceptionHandler2()'
12:03:44  SUCCESSFUL ThreadAPI::testUncaughtExceptionHandler2 'testUncaughtExceptionHandler2()'
12:03:44  STARTED    ThreadAPI::testUncaughtExceptionHandler3 'testUncaughtExceptionHandler3()'
12:03:44  Exception in thread "" ThreadAPI$3FooException
12:03:44  	at ThreadAPI.lambda$testUncaughtExceptionHandler3$111(ThreadAPI.java:1596)
12:03:44  	at java.base/java.lang.VirtualThread.run(VirtualThread.java:317)
12:03:44  	at <unknown class>.<unknown method>(Unknown Source)
12:03:44  	at java.base/jdk.internal.vm.Continuation.enter(Continuation.java:177)
12:03:44  SUCCESSFUL ThreadAPI::testUncaughtExceptionHandler3 'testUncaughtExceptionHandler3()'
12:03:44  STARTED    ThreadAPI::testEnumerate1 'testEnumerate1()'
12:03:44  SUCCESSFUL ThreadAPI::testEnumerate1 'testEnumerate1()'
12:03:44  STARTED    ThreadAPI::testEnumerate2 'testEnumerate2()'
12:03:44  SUCCESSFUL ThreadAPI::testEnumerate2 'testEnumerate2()'
12:03:44  STARTED    ThreadAPI::testHoldsLock1 'testHoldsLock1()'
12:03:44  SUCCESSFUL ThreadAPI::testHoldsLock1 'testHoldsLock1()'
12:03:44  STARTED    ThreadAPI::testHoldsLock2 'testHoldsLock2()'
12:03:44  SUCCESSFUL ThreadAPI::testHoldsLock2 'testHoldsLock2()'
12:03:44  STARTED    ThreadAPI::testJoin1 'testJoin1()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin1 'testJoin1()'
12:03:44  STARTED    ThreadAPI::testJoin2 'testJoin2()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin2 'testJoin2()'
12:03:44  STARTED    ThreadAPI::testJoin3 'testJoin3()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin3 'testJoin3()'
12:03:44  STARTED    ThreadAPI::testJoin4 'testJoin4()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin4 'testJoin4()'
12:03:44  STARTED    ThreadAPI::testJoin5 'testJoin5()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin5 'testJoin5()'
12:03:44  STARTED    ThreadAPI::testJoin6 'testJoin6()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin6 'testJoin6()'
12:03:44  STARTED    ThreadAPI::testJoin7 'testJoin7()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin7 'testJoin7()'
12:03:44  STARTED    ThreadAPI::testJoin8 'testJoin8()'
12:03:44  SUCCESSFUL ThreadAPI::testJoin8 'testJoin8()'
12:03:44  STARTED    ThreadAPI::testStop1 'testStop1()'
12:03:44  SUCCESSFUL ThreadAPI::testStop1 'testStop1()'
12:03:44  STARTED    ThreadAPI::testStop2 'testStop2()'
12:03:44  SUCCESSFUL ThreadAPI::testStop2 'testStop2()'
12:03:44  STARTED    ThreadAPI::testRun1 'testRun1()'
12:03:44  SUCCESSFUL ThreadAPI::testRun1 'testRun1()'
12:03:44  STARTED    ThreadAPI::testContextClassLoader1 'testContextClassLoader1()'
12:03:44  SUCCESSFUL ThreadAPI::testContextClassLoader1 'testContextClassLoader1()'
12:03:44  STARTED    ThreadAPI::testContextClassLoader2 'testContextClassLoader2()'
12:03:44  SUCCESSFUL ThreadAPI::testContextClassLoader2 'testContextClassLoader2()'
12:03:44  STARTED    ThreadAPI::testContextClassLoader3 'testContextClassLoader3()'
12:03:44  SUCCESSFUL ThreadAPI::testContextClassLoader3 'testContextClassLoader3()'
12:03:44  STARTED    ThreadAPI::testContextClassLoader4 'testContextClassLoader4()'
12:03:44  SUCCESSFUL ThreadAPI::testContextClassLoader4 'testContextClassLoader4()'
12:03:44  STARTED    ThreadAPI::testContextClassLoader5 'testContextClassLoader5()'
12:03:44  SUCCESSFUL ThreadAPI::testContextClassLoader5 'testContextClassLoader5()'
12:03:44  STARTED    ThreadAPI::testThreadId1 'testThreadId1()'
12:03:44  SUCCESSFUL ThreadAPI::testThreadId1 'testThreadId1()'
12:03:44  STARTED    ThreadAPI::testThreadId2 'testThreadId2()'
12:03:44  SUCCESSFUL ThreadAPI::testThreadId2 'testThreadId2()'
12:03:44  STARTED    ThreadAPI::testSuspend1 'testSuspend1()'
12:03:44  SUCCESSFUL ThreadAPI::testSuspend1 'testSuspend1()'
12:03:44  STARTED    ThreadAPI::testSuspend2 'testSuspend2()'
12:03:44  SUCCESSFUL ThreadAPI::testSuspend2 'testSuspend2()'
12:03:44  STARTED    ThreadAPI::testSetDaemon1 'testSetDaemon1()'
12:03:44  SUCCESSFUL ThreadAPI::testSetDaemon1 'testSetDaemon1()'
12:03:44  STARTED    ThreadAPI::testSetDaemon2 'testSetDaemon2()'
12:03:44  SUCCESSFUL ThreadAPI::testSetDaemon2 'testSetDaemon2()'
12:03:44  STARTED    ThreadAPI::testGetAllStackTraces1 'testGetAllStackTraces1()'
12:03:44  SUCCESSFUL ThreadAPI::testGetAllStackTraces1 'testGetAllStackTraces1()'
12:03:44  STARTED    ThreadAPI::testGetAllStackTraces2 'testGetAllStackTraces2()'
12:03:44  SUCCESSFUL ThreadAPI::testGetAllStackTraces2 'testGetAllStackTraces2()'
12:03:44  STARTED    ThreadAPI::testIsAlive1 'testIsAlive1()'
12:03:44  SUCCESSFUL ThreadAPI::testIsAlive1 'testIsAlive1()'
12:03:44  STARTED    ThreadAPI::testOnSpinWait 'testOnSpinWait()'
12:03:44  SUCCESSFUL ThreadAPI::testOnSpinWait 'testOnSpinWait()'
12:03:44  STARTED    ThreadAPI::testThreadGroup1 'testThreadGroup1()'
12:03:44  SUCCESSFUL ThreadAPI::testThreadGroup1 'testThreadGroup1()'
12:03:44  STARTED    ThreadAPI::testThreadGroup2 'testThreadGroup2()'
12:03:44  SUCCESSFUL ThreadAPI::testThreadGroup2 'testThreadGroup2()'
12:03:44  STARTED    ThreadAPI::testThreadGroup3 'testThreadGroup3()'
12:03:44  SUCCESSFUL ThreadAPI::testThreadGroup3 'testThreadGroup3()'
12:03:44  STARTED    ThreadAPI::testThreadGroup4 'testThreadGroup4()'
12:03:44  SUCCESSFUL ThreadAPI::testThreadGroup4 'testThreadGroup4()'
12:03:44  STARTED    ThreadAPI::testCurrentThread1 'testCurrentThread1()'
12:03:44  SUCCESSFUL ThreadAPI::testCurrentThread1 'testCurrentThread1()'
12:03:44  STARTED    ThreadAPI::testCurrentThread2 'testCurrentThread2()'
12:03:44  SUCCESSFUL ThreadAPI::testCurrentThread2 'testCurrentThread2()'
12:03:44  STARTED    ThreadAPI::testCurrentThread3 'testCurrentThread3()
12:03:44  TEST RESULT: Error. Agent error: java.lang.Exception: Agent 7 timed out with a timeout of 960 seconds; check console log for any additional details
12:03:44  --------------------------------------------------
12:03:44  Test results: passed: 907; error: 1
12:03:44  Report written to /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/report/html/report.html
12:03:44  Results written to /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_OpenJDK21_testList_0/aqa-tests/TKG/output_16917686272024/jdk_lang_1/work
12:03:44  Error: Some tests failed or other problems occurred.
```

**Comment by pshipton** [comment]
3 x 10x grinder of the test https://openj9-jenkins.osuosl.org/job/Grinder/2734/
3x grinder of jdk_lang_1 https://openj9-jenkins.osuosl.org/job/Grinder/2735/

**Comment by JitendraProgrammer** [comment]
Hi @pshipton ,

I am new here, I want to contribute something 
Please suggest me

**Comment by pshipton** [comment]
I haven't seen it.
