### ISSUE TITLE
OpenJDK java/util/zip/DeInflate De/inflater(buffer) failed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17955]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/33 - [ub20-390-5](https://openj9-jenkins.osuosl.org/computer/ub20-390-5)
jdk_util_0
java/util/zip/DeInflate.java

```
...
00:39:45  level:0, strategy: 2, dowrap: true
00:39:45  iteration: 1 input length: 524288
00:39:45  iteration: 2 input length: 228780
00:39:45  iteration: 3 input length: 401917
00:39:45  iteration: 4 input length: 213573
00:39:45  iteration: 5 input length: 21121
00:39:45  level:1, strategy: 0, dowrap: false
00:39:45  iteration: 1 input length: 524288
00:39:45  iteration: 2 input length: 252590
00:39:45  iteration: 3 input length: 40867
00:39:45  iteration: 4 input length: 126504
00:39:45  iteration: 5 input length: 398142
00:39:45  level:1, strategy: 0, dowrap: true
00:39:45  iteration: 1 input length: 524288
00:39:45  iteration: 2 input length: 62455
00:39:45  iteration: 3 input length: 346241
00:39:45  iteration: 4 input length: 480923
00:39:45  iteration: 5 input length: 395160
00:39:45  STDERR:
00:39:45  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@9229aaa6
00:39:45  	at DeInflate.checkByteBuffer(DeInflate.java:99)
00:39:45  	at DeInflate.check(DeInflate.java:209)
00:39:45  	at DeInflate.main(DeInflate.java:324)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/18 - [ub20-390-2](https://openj9-jenkins.osuosl.org/computer/ub20-390-2)
jdk_util_0
java/util/zip/DeInflate.java
```
13:39:33  level:-1, strategy: 0, dowrap: false
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 416359
13:39:33  iteration: 3 input length: 87943
13:39:33  iteration: 4 input length: 443875
13:39:33  iteration: 5 input length: 245328
13:39:33  level:-1, strategy: 0, dowrap: true
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 192412
13:39:33  iteration: 3 input length: 253046
13:39:33  iteration: 4 input length: 362163
13:39:33  iteration: 5 input length: 354226
13:39:33  level:-1, strategy: 1, dowrap: false
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 141286
13:39:33  iteration: 3 input length: 410554
13:39:33  iteration: 4 input length: 495888
13:39:33  iteration: 5 input length: 351132
13:39:33  level:-1, strategy: 1, dowrap: true
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 476994
13:39:33  iteration: 3 input length: 364348
13:39:33  iteration: 4 input length: 298366
13:39:33  iteration: 5 input length: 155648
13:39:33  level:-1, strategy: 2, dowrap: false
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 211494
13:39:33  iteration: 3 input length: 838
13:39:33  iteration: 4 input length: 193020
13:39:33  iteration: 5 input length: 522883
13:39:33  level:-1, strategy: 2, dowrap: true
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 421152
13:39:33  iteration: 3 input length: 519878
13:39:33  iteration: 4 input length: 98627
13:39:33  iteration: 5 input length: 20870
13:39:33  level:0, strategy: 0, dowrap: false
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 262589
13:39:33  iteration: 3 input length: 438535
13:39:33  iteration: 4 input length: 342242
13:39:33  iteration: 5 input length: 410810
13:39:33  level:0, strategy: 0, dowrap: true
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 136830
13:39:33  iteration: 3 input length: 120895
13:39:33  iteration: 4 input length: 366342
13:39:33  iteration: 5 input length: 5792
13:39:33  level:0, strategy: 1, dowrap: false
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 141537
13:39:33  iteration: 3 input length: 347142
13:39:33  iteration: 4 input length: 101806
13:39:33  iteration: 5 input length: 44975
13:39:33  level:0, strategy: 1, dowrap: true
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 492539
13:39:33  iteration: 3 input length: 276609
13:39:33  iteration: 4 input length: 322242
13:39:33  iteration: 5 input length: 249962
13:39:33  level:0, strategy: 2, dowrap: false
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 499042
13:39:33  iteration: 3 input length: 506265
13:39:33  iteration: 4 input length: 463016
13:39:33  iteration: 5 input length: 32475
13:39:33  level:0, strategy: 2, dowrap: true
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 287187
13:39:33  iteration: 3 input length: 445756
13:39:33  iteration: 4 input length: 35923
13:39:33  iteration: 5 input length: 215768
13:39:33  level:1, strategy: 0, dowrap: false
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 117950
13:39:33  iteration: 3 input length: 283338
13:39:33  iteration: 4 input length: 355963
13:39:33  iteration: 5 input length: 265511
13:39:33  level:1, strategy: 0, dowrap: true
13:39:33  iteration: 1 input length: 524288
13:39:33  iteration: 2 input length: 186008
13:39:33  STDERR:
13:39:33  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@a34f51bd
13:39:33  	at DeInflate.checkByteBuffer(DeInflate.java:99)
13:39:33  	at DeInflate.check(DeInflate.java:209)
13:39:33  	at DeInflate.main(DeInflate.java:324)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/54 - [ub20-390-3a](https://openj9-jenkins.osuosl.org/computer/ub20-390-3a)
jdk_util_0
java/util/zip/DeInflate.java
```
05:12:28  level:1, strategy: 0, dowrap: false
05:12:28  m=525312, n=498140, len=524288, eq=false
05:12:28  STDERR:
05:12:28  java.lang.RuntimeException: De/inflater failed:java.util.zip.Deflater@f087caec
05:12:28  	at DeInflate.check(DeInflate.java:84)
05:12:28  	at DeInflate.main(DeInflate.java:132)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/54/ - [ub20-390-5](https://openj9-jenkins.osuosl.org/computer/ub20-390-5)
jdk_util_1
java/util/zip/DeInflate.java
```
04:54:22  level:1, strategy: 0, dowrap: false
04:54:22  m=525312, n=498088, len=524288, eq=false
04:54:22  STDERR:
04:54:22  java.lang.RuntimeException: De/inflater failed:java.util.zip.Deflater@4c62fbe1
04:54:22  	at DeInflate.check(DeInflate.java:84)
04:54:22  	at DeInflate.main(DeInflate.java:132)
```

We may be seeing this on jdk8 now due to https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/692

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Release_testList_0/27
jdk_util_1
java/util/zip/DeInflate.java
```
23:02:02  level:1, strategy: 0, dowrap: true
23:02:02  iteration: 1 input length: 524288
23:02:02  iteration: 2 input length: 339055
23:02:02  iteration: 3 input length: 27420
23:02:02  STDERR:
23:02:02  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@3b0574f0
23:02:02  	at DeInflate.checkByteBuffer(DeInflate.java:99)
23:02:02  	at DeInflate.check(DeInflate.java:209)
23:02:02  	at DeInflate.main(DeInflate.java:324)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/179
jdk_util_1
java/util/zip/DeInflate.java
```
21:56:00  level:5, strategy: 0, dowrap: true
21:56:00  iteration: 1 input length: 524288
21:56:00  STDERR:
21:56:00  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@fb09a5a8
21:56:00  	at DeInflate.checkByteBuffer(DeInflate.java:99)
21:56:00  	at DeInflate.check(DeInflate.java:209)
21:56:00  	at DeInflate.main(DeInflate.java:324)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17_testList_0/29
jdk_util_1
java/util/zip/DeInflate.java
```
04:30:22  level:5, strategy: 0, dowrap: true
04:30:22  iteration: 1 input length: 524288
04:30:22  iteration: 2 input length: 191567
04:30:22  iteration: 3 input length: 159441
04:30:22  iteration: 4 input length: 128712
04:30:22  STDERR:
04:30:22  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@92edad93
04:30:22  	at DeInflate.checkByteBuffer(DeInflate.java:99)
04:30:22  	at DeInflate.check(DeInflate.java:209)
04:30:22  	at DeInflate.main(DeInflate.java:324)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/479 - [rh8-390-1](https://openj9-jenkins.osuosl.org/computer/rh8-390-1)
jdk_util_0
java/util/zip/DeInflate.java
```
22:19:07  level:2, strategy: 0, dowrap: true
22:19:07  iteration: 1 input length: 524288
22:19:07  iteration: 2 input length: 137641
22:19:07  iteration: 3 input length: 92859
22:19:07  iteration: 4 input length: 217890
22:19:07  iteration: 5 input length: 492589
22:19:07  STDERR:
22:19:07  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@85462d82
22:19:07  	at DeInflate.checkByteBuffer(DeInflate.java:99)
22:19:07  	at DeInflate.check(DeInflate.java:209)
22:19:07  	at DeInflate.main(DeInflate.java:324)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_s390x_linux_Release_testList_2/20/consoleFull
```
03:18:25  Running test jdk_util_1 ...
03:18:25  ===============================================
03:18:25  jdk_util_1 Start Time: Fri Aug  8 07:18:23 2025 Epoch Time (ms): 1754637503938
03:18:25  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
03:18:25  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

03:43:42  TEST: java/util/zip/DeInflate.java

03:43:42  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@c95d3369
03:43:42  	at DeInflate.checkByteBuffer(DeInflate.java:99)
03:43:42  	at DeInflate.check(DeInflate.java:209)
03:43:42  	at DeInflate.main(DeInflate.java:324)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_2/308 - [rh8-390-2](https://openj9-jenkins.osuosl.org/computer/rh8-390-2)
jdk_util_1
java/util/zip/DeInflate.java
```
07:19:59  level:4, strategy: 0, dowrap: true
07:19:59  iteration: 1 input length: 524288
07:19:59  iteration: 2 input length: 282272
07:19:59  iteration: 3 input length: 309769
07:19:59  iteration: 4 input length: 498024
07:19:59  STDERR:
07:19:59  java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@d2a7b79a
07:19:59  	at DeInflate.checkByteBuffer(DeInflate.java:99)
07:19:59  	at DeInflate.check(DeInflate.java:209)
07:19:59  	at DeInflate.main(DeInflate.java:324)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/35/ - [ub20-390-4](https://openj9-jenkins.osuosl.org/computer/ub20-390-4)
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/613 - [rh8-390-1](https://openj9-jenkins.osuosl.org/computer/rh8-390-1)
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/626 - [rh8-390-1](https://openj9-jenkins.osuosl.org/computer/rh8-390-1)
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/126 - [rh8-390-2](https://openj9-jenkins.osuosl.org/computer/rh8-390-2)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_3/8 - [rh8-390-1](https://openj9-jenkins.osuosl.org/computer/rh8-390-1)

**Comment by 0xdaryl** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OMR_testList_1/493

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.openjdk_s390x_linux_testList_1/277/)
```
[2026-09-13T00:13:58.647Z] Running test jdk_util_other_0 ...
[2026-09-13T00:13:58.647Z] ===============================================
[2026-09-13T00:13:58.647Z] jdk_util_other_0 Start Time: Sun Sep 13 00:13:51 2026 Epoch Time (ms): 1789258431336
[2026-09-13T00:13:58.647Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2026-09-13T00:13:58.647Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2026-09-13T00:17:03.205Z] TEST: java/util/zip/DeInflate.java

[2026-09-13T00:17:03.207Z] java.lang.RuntimeException: De/inflater(buffer) failed:java.util.zip.Deflater@30e18bb6
[2026-09-13T00:17:03.207Z] 	at DeInflate.checkByteBuffer(DeInflate.java:100)
[2026-09-13T00:17:03.207Z] 	at DeInflate.check(DeInflate.java:210)
[2026-09-13T00:17:03.207Z] 	at DeInflate.main(DeInflate.java:335)
```
