### ISSUE TITLE
[FFI/Jtreg_JDK21] RuntimeException detected in TestHFA.java on pLinux

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17953]
A couple of test failures with similar issue was detected on pLinux in TestHFA.java at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/TestHFA.java.
e.g.
```
test TestHFA.testAddDoubleToStructAfterStructs(): failure
java.lang.RuntimeException: add_double_to_struct_after_structs error
        at TestHFA.testAddDoubleToStructAfterStructs(TestHFA.java:200)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
Looking at the failing test `testAddDoubleToStructAfterStructs`:
```
public static void testAddDoubleToStructAfterStructs() {
        float p0 = 0.0f, p1 = 0.0f;
        try {
            Arena arena = Arena.ofConfined();
            MemorySegment s = arena.allocate(S_FFLayout);
            s.set(FLOAT, 0, 1.0f);
            s.set(FLOAT, 4, 1.0f);
            s = (MemorySegment)mhadd_double_to_struct_after_structs.invokeExact((SegmentAllocator)arena,
                 s, s, s, s, s, s,
                 s, 1.0d);
            p0 = s.get(FLOAT, 0);
            p1 = s.get(FLOAT, 4);
            System.out.println("S_FF(" + p0 + ";" + p1 + ")");
        } catch (Throwable t) {
            t.printStackTrace();
        }
        if (p0 != 2.0f || p1 != 1.0f) throw new RuntimeException("add_double_to_struct_after_structs error"); <------
    }
```
against the native code at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/a5672ac7389c6d2ecf34495a423fe09aedc46341/test/jdk/java/foreign/libTestHFA.c#L62C5-L62C5
```
// Corner case on PPC64le: Pass struct S_FF partially in FP register and in GP register.
// Pass additional double in GP register.
EXPORT struct S_FF add_double_to_struct_after_structs(
  struct S_FF s1, struct S_FF s2, struct S_FF s3, struct S_FF s4, struct S_FF s5, struct S_FF s6,
  struct S_FF s, double f) {
  s.p0 += (float)f;
  return s;
}
```
It looks like the failing tests are intended for pLinux. So I will need to debug the code what was really happened to the tests in native.

**Comment by ChengJin01** [comment]
[1] Debugging in the native code indicates that the issue occur when the size of the passed-in `struct S_FF s` is bigger than the unused Floating Pointer registers in the failing test (note: only f1-f13 are available of use as parameter passing based on the pLinux ABI Specification).  To be specific, the first 6 struct parameters (`s1` to `s6`) occupy `f1`-`f12` FP register (each struct takes 2 FP registers), in which case only `f13` is left to  the 7th struct `struct S_FF s`.
```
Thread 27 "MainThread" hit Breakpoint 1, add_double_to_struct_after_structs (
    s1=..., s2=..., s3=..., s4=..., s5=..., s6=..., s=..., f=1)
    at libTestHFA.c:65
65        s.p0 += (float)f;
(gdb) p s1
$4 = {p0 = 1, p1 = 1}
(gdb) p s2
$5 = {p0 = 1, p1 = 1}
(gdb) p s3
$6 = {p0 = 1, p1 = 1}
(gdb) p s4
$7 = {p0 = 1, p1 = 1}
(gdb) p s5
$8 = {p0 = 1, p1 = 1}
(gdb) p s6
$9 = {p0 = 1, p1 = 1}
(gdb) p s
$10 = {p0 = -1.77340502e+29, p1 = 1}  <------- the 1st float element of s was messed up


(gdb) x/20x  &s1
0x7fffd451a7b8: 0x3f800000 (1)     0x3f800000 (1)      0xf000ce50      0x00007fff
(gdb) x/20x  &s2
0x7fffd451a7b0: 0x3f800000 (1)     0x3f800000 (1)     0x3f800000      0x3f800000
(gdb) x/20x  &s5
0x7fffd451a798: 0x3f800000 (1)     0x3f800000 (1)    0x3f800000      0x3f800000
...
(gdb) x/20x  &s
0x7fffd451a788: 0xf00f4128 (wrong for s.p0)     0x3f800000 (correct for s.p1)      0x3f800000      0x3f800000
```

I also double-checked the parameters passed in the native function prior to the `ffi_call()` in the interpreter at `inlInternalDowncallHandlerInvokeNative ` which shows that the passed-in arguments were correct before invoking the native function via `ffi_call()`:
```
#5  0x00007ffff7799370 in VM_BytecodeInterpreterCompressed::inlInternalDowncallHandlerInvokeNative (this=0x7fffd451b610, _sp=@0x7fffd451b570: 0x2b9b28,
    _pc=@0x7fffd451b578: 0x7 <error: Cannot access memory at address 0x7>)
    at /root/jchau_ffi/openj9-openjdk-jdk21/openj9/runtime/vm/BytecodeInterpreter.hpp:5260
5260                    ffiCallWithSetJmpForUpcall(_currentThread, cif, function, returnStorage, values);

(gdb) p/x  values[0]
$13 = 0x7fff5c1810b0
(gdb) x/50x  0x7fffd451ae20
0x7fffd451ae20: 0x5c1810b0      0x00007fff (1st)      0x5c1810b0      0x00007fff (2nd)
0x7fffd451ae30: 0x5c1810b0      0x00007fff (3rd)      0x5c1810b0      0x00007fff (4th)
0x7fffd451ae40: 0x5c1810b0      0x00007fff (5th)      0x5c1810b0      0x00007fff (6th)
0x7fffd451ae50: 0x5c1810b0      0x00007fff (7th)      0xd451af58      0x00007fff (8th)
0x7fffd451ae60: 0xd451af10      0x00007fff      0x00000001      0x00000000
0x7fffd451ae70: 0x0041b4b8      0x00000000      0x002b4500      0x00000000
0x7fffd451ae80: 0x00000000      0x00000000      0x00000002      0x00000000
0x7fffd451ae90: 0x00000001      0x00000000      0xf00aa0c8      0x00007fff
0x7fffd451aea0: 0xf0016190      0x00007fff      0xd451b578      0x00007fff
0x7fffd451aeb0: 0x5c13c380      0x00007fff      0xf7b52b00      0x00007fff
0x7fffd451aec0: 0x0041b4b8      0x00000000      0x002b9b48      0x00000000
0x7fffd451aed0: 0x00000000      0x00000000      0x00000000      0x00000000
0x7fffd451aee0: 0x5c13c380      0x00007fff

(gdb) x/10x  0x00007fff5c1810b0
0x7fff5c1810b0: 0x3f800000 (1)      0x3f800000 (1)      0xb7654321      0xe82a41e6

```
So the issue was triggered by pLinux specific code in libffi.

[2] According to the example of the parameters passing in the pLinux ABI  Specification (64-Bit ELF V2 ABI Specification December 1, 2020 Revision 1.5)
```
Figure 2.25. Passing Floating-Point Scalars and Homogeneous Floating-Point
Aggregates in FPRs and GPRs without a Parameter Save Area
x = oddity2 (struct two_floats s1, struct two_floats s2,
struct two_floats s3, struct two_floats s4,
struct two_floats s5, struct two_floats s6,
struct two_floats s7, struct two_floats s8)
Parameter Register Offset in parameter save area
s1.a f1 n/a
s1.b f2 n/a
s2.a f3 n/a
s2.b f4 n/a
s3.a f5 n/a
s3.b f6 n/a
s4.a f7 n/a
s4.b f8 n/a
s5.a f9 n/a
s5.b f10 n/a
s6.a f11 n/a
s6.b f12 n/a
s7.a f13 n/a
s7.b - n/a
s7 gpr9 n/a  <------- s7 is copied to the General Purpose registers
s8 gpr10 n/a <-------
```
the rest of structs including `s7` and `s8` should be copied to the unused GP registers (note: only r3-r10 is available for use in terms of the parameter passing) given all f1-f12 FP registers are used up with only one FP registers (`f13`) left.

[3] I tried to debug the pLinux specific code in libffi and hacked the code in the case of `FFI_TYPE_FLOAT` in `ffi_prep_args64()` at https://github.com/eclipse-openj9/openj9/blob/master/runtime/libffi/powerpc/ffi_linux64.c#L699 which seemed working but unfortunately triggered other test failures. 

So the investigation above shows these test failures were triggered by the pLinux specific code in libffi which failed to handle all corner cases correctly as specified in the pLinux ABI specifications and it is mostly likely the problem can be fixed by modifying the existing code in `ffi_prep_args64()` (not too sure whether the related assembly in libffi on pLinux should be adjusted to adapt to changes in `ffi_prep_args64()` ).

**Comment by ChengJin01** [comment]
Given the complexity of the pLinux specific code in libffi (which is out of our control), the failing test suite will be temporarily excluded till an official fix is offered by the libffi developers.

**Comment by ChengJin01** [comment]
https://github.com/libffi/libffi/issues/790 is created to keep track of the progress in libffi.

**Comment by zl-wang** [comment]
that argument of wrong value corresponds to s7.a (passed in both f13 and gpr9 --- partially). I suspected libffi only loads s7.b into gpr9 with s7.a portion left as garbage. It should step back 4-byte and load the full s7 into gpr9.  you can confirm my suspicion by checking the values in f13 and gpr9 at your existing break-point.  gpr9 lower 32bit corresponds to s7.a (due to Little-Endian mode).  i.e.  it might get it wrong because of this corner case of double passing.

you can test another case with native prototype adding a float in the front like:  testNative(float, s1, s2, s3, s4, s5, s6, s7, double), such that there is no double passing ... every argument is either in fpr or in gpr in full.  libffi is likely to get this right.

**Comment by ChengJin01** [comment]
> that argument of wrong value corresponds to s7.a (passed in both f13 and gpr9 --- partially). I suspected libffi only loads s7.b into gpr9 with s7.a portion left as garbage. It should step back 4-byte and load the full s7 into gpr9. you can confirm my suspicion by checking the values in f13 and gpr9 at your existing break-point. gpr9 lower 32bit corresponds to s7.a (due to Little-Endian mode). i.e. it might get it wrong because of this corner case of double passing.

Yes, that's what happened in test as below in debugging:
```
Thread 28 "MainThread" hit Breakpoint 1, add_double_to_struct_after_structs (s1=..., s2=...,
    s3=..., s4=..., s5=..., s6=..., s=..., f=1) at libTestHFA.c:65
65        s.p0 += (float)f;
(gdb) p/x  s
$1 = {p0 = 0x0, p1 = 0x1}
(gdb) p/x  &s
$3 = 0x7fffd40da788
(gdb) x/10x   &s
0x7fffd40da788: 0xf001ca28      0x3f800000      0x3f800000      0x3f800000
0x7fffd40da798: 0x3f800000      0x3f800000      0x3f800000      0x3f800000
0x7fffd40da7a8: 0x3f800000      0x3f800000

(gdb) info all-registers
r0             0x7ffff79f0eb0      140737347784368
r1             0x7fffd40da750      140736751052624
r2             0x7ffff7a86c00      140737348398080
r3             0x7fffd40da910      140736751053072
r4             0x7ffff7f27100      140737353249024
r5             0x7ffff79536b0      140737347139248
r6             0x7fffd40da8c0      140736751052992
r7             0x3f80000000000000  4575657221408423936
r8             0x3f800000f001ca28  4575657225435073064
r9             0x3f800000f001ca28  4575657225435073064 <----------
r10            0x3ff0000000000000  4607182418800017408
...
f0             0.007812501848093234 (raw 0x3f8000003f800000)
f1             1                   (raw 0x3ff0000000000000)
f2             1                   (raw 0x3ff0000000000000)
f3             1                   (raw 0x3ff0000000000000)
f4             1                   (raw 0x3ff0000000000000)
f5             1                   (raw 0x3ff0000000000000)
f6             1                   (raw 0x3ff0000000000000)
f7             1                   (raw 0x3ff0000000000000)
f8             1                   (raw 0x3ff0000000000000)
f9             1                   (raw 0x3ff0000000000000)
f10            1                   (raw 0x3ff0000000000000)
f11            1                   (raw 0x3ff0000000000000)
f12            1                   (raw 0x3ff0000000000000)
f13            1                   (raw 0x3ff0000000000000) <----------
```


> you can test another case with native prototype adding a float in the front like: testNative(float, s1, s2, s3, s4, s5, s6, s7, double), such that there is no double passing ... every argument is either in fpr or in gpr in full. libffi is likely to get this right.

Yes, the test passed by adding a float as the 1st parameter to the test function `add_double_to_struct_after_structs(float, s1, s2, s3, s4, s5, s6, s7, double)`.

**Comment by zl-wang** [comment]
yeah, that just exactly confirmed my suspicion. double-passing is not handled correctly.
`r9             0x3f800000f001ca28`    // the lower 32bit should be 0x3f800000 too, if it is treated correctly

**Comment by DemiMarie** [comment]
I recommend sending a libffi patch.
