### ISSUE TITLE
OpenJDK jdk/internal/misc/ThreadFlock/ThreadFlockTest Duration expected <= 4000ms ==>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17975]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/34/
jdk_lang_0
jdk/internal/misc/ThreadFlock/ThreadFlockTest.java
```
18:41:32  org.opentest4j.AssertionFailedError: Duration 4613ms, expected <= 4000ms ==> expected: <true> but was: <false>
18:41:32  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
18:41:32  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
18:41:32  	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
18:41:32  	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
18:41:32  	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:211)
18:41:32  	at ThreadFlockTest.checkDuration(ThreadFlockTest.java:1088)
18:41:32  	at ThreadFlockTest.testAwaitAllWithTimeout1(ThreadFlockTest.java:429)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/35/
`command: junit -DthreadFactory=platform ThreadFlockTest`
`18:30:04  org.opentest4j.AssertionFailedError: Duration 4893ms, expected <= 4000ms ==> expected: <true> but was: <false>`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/38/
jdk/internal/misc/ThreadFlock/ThreadFlockTest.java#virtual
```
06:24:23  org.opentest4j.AssertionFailedError: Duration 4582ms, expected <= 4000ms ==> expected: <true> but was: <false>
06:24:23  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
06:24:23  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
06:24:23  	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
06:24:23  	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
06:24:23  	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:211)
06:24:23  	at ThreadFlockTest.checkDuration(ThreadFlockTest.java:1088)
06:24:23  	at ThreadFlockTest.testAwaitAllWithTimeout1(ThreadFlockTest.java:429)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/145/
jdk_lang_0
jdk/internal/misc/ThreadFlock/ThreadFlockTest.java#virtual

```
19:36:17  STARTED    ThreadFlockTest::testAwaitAllWithTimeout1 '[1] java.lang.ThreadBuilders$VirtualThreadFactory@520ffb10'
19:36:17  org.opentest4j.AssertionFailedError: Duration 4111ms, expected <= 4000ms ==> expected: <true> but was: <false>
19:36:17  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
19:36:17  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
19:36:17  	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
19:36:17  	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
19:36:17  	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:211)
19:36:17  	at ThreadFlockTest.checkDuration(ThreadFlockTest.java:1088)
19:36:17  	at ThreadFlockTest.testAwaitAllWithTimeout1(ThreadFlockTest.java:429)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/177/
jdk_lang_1
jdk/internal/misc/ThreadFlock/ThreadFlockTest.java
`org.opentest4j.AssertionFailedError: Duration 4987ms, expected <= 4000ms ==> expected: <true> but was: <false>`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/76

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Release_testList_2/46/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/389/
