### ISSUE TITLE
jdk_nio_0_FAILED sun/nio/cs/TestIBMBugs.java java.lang.ArrayIndexOutOfBoundsException at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17995]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/108/)(`win16x64rt-1-2`):
```
openjdk version "1.8.0_392-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_392-beta-202308190240-b01)
Eclipse OpenJ9 VM (build master-b47a6d454, JRE 1.8.0 Windows Server 2016 amd64-64-Bit Compressed References 20230819_749 (JIT enabled, AOT enabled)
OpenJ9   - b47a6d454
OMR      - ac8ca57b0
JCL      - 36ba274cc based on jdk8u392-b01)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_nio_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x64-openj9%2F749%2Fibm-semeru-open-jdk_x64_windows_JDK8U_2023-08-19-02-31.zip+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x64-openj9%2F749%2Fibm-semeru-open-testimage_x64_windows_JDK8U_2023-08-19-02-31.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-08-19T05:14:46.666Z] variation: Mode150
[2023-08-19T05:14:47.057Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-08-19T05:25:43.893Z] TEST: sun/nio/cs/TestIBMBugs.java

[2023-08-19T05:25:43.897Z] STDERR:
[2023-08-19T05:25:43.897Z] java.lang.ArrayIndexOutOfBoundsException
[2023-08-19T05:25:43.897Z] 	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
[2023-08-19T05:25:43.897Z] 	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
[2023-08-19T05:25:43.897Z] 	at java.lang.Character.getType(Character.java:6978)
[2023-08-19T05:25:43.897Z] 	at java.lang.Character.isDefined(Character.java:5758)
[2023-08-19T05:25:43.897Z] 	at java.lang.Character.isDefined(Character.java:5734)
[2023-08-19T05:25:43.897Z] 	at TestIBMBugs.bug6577466(TestIBMBugs.java:168)
[2023-08-19T05:25:43.897Z] 	at TestIBMBugs.main(TestIBMBugs.java:176)
[2023-08-19T05:25:43.897Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-08-19T05:25:43.897Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-08-19T05:25:43.897Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-08-19T05:25:43.897Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-08-19T05:25:43.897Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2023-08-19T05:25:43.897Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-08-19T05:25:43.897Z] 
[2023-08-19T05:25:43.897Z] JavaTest Message: Test threw exception: java.lang.ArrayIndexOutOfBoundsException
[2023-08-19T05:25:43.897Z] JavaTest Message: shutting down test
[2023-08-19T05:25:43.897Z] 
[2023-08-19T05:25:43.897Z] 
[2023-08-19T05:25:43.897Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.ArrayIndexOutOfBoundsException
[2023-08-19T05:25:43.897Z] --------------------------------------------------
[2023-08-19T05:27:08.805Z] Test results: passed: 328; failed: 1
[2023-08-19T05:27:33.292Z] Report written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16924189572306\jdk_nio_0\report\html\report.html
[2023-08-19T05:27:33.292Z] Results written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16924189572306\jdk_nio_0\work
[2023-08-19T05:27:33.292Z] Error: Some tests failed or other problems occurred.
[2023-08-19T05:27:33.292Z] -----------------------------------
[2023-08-19T05:27:33.292Z] jdk_nio_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34415/) - this failure wasn't reproduced.

**Comment by hzongaro** [comment]
Reproduced this in another [50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34980/) run.

**Comment by JasonFengJ9** [comment]
[JDK8 x86-64_windows 0.41 milestone 2](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/116/)(`win11x86-svl-rt3-1`)
```
[2023-10-03T19:33:42.492Z] variation: Mode150
[2023-10-03T19:33:42.492Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-10-03T20:00:42.838Z] TEST: sun/nio/cs/TestIBMBugs.java

[2023-10-03T20:00:42.840Z] STDERR:
[2023-10-03T20:00:42.840Z] java.lang.ArrayIndexOutOfBoundsException
[2023-10-03T20:00:42.840Z] 	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
[2023-10-03T20:00:42.840Z] 	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
[2023-10-03T20:00:42.840Z] 	at java.lang.Character.getType(Character.java:6978)
[2023-10-03T20:00:42.840Z] 	at java.lang.Character.isDefined(Character.java:5758)
[2023-10-03T20:00:42.840Z] 	at java.lang.Character.isDefined(Character.java:5734)
[2023-10-03T20:00:42.840Z] 	at TestIBMBugs.bug6577466(TestIBMBugs.java:168)
[2023-10-03T20:00:42.840Z] 	at TestIBMBugs.main(TestIBMBugs.java:176)
[2023-10-03T20:00:42.840Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-03T20:00:42.840Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-10-03T20:00:42.840Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-03T20:00:42.840Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-10-03T20:00:42.840Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2023-10-03T20:00:42.840Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-10-03T20:00:42.840Z] 
[2023-10-03T20:00:42.840Z] JavaTest Message: Test threw exception: java.lang.ArrayIndexOutOfBoundsException

[2023-10-03T20:02:27.991Z] jdk_nio_0_FAILED
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35345/)

**Comment by JasonFengJ9** [comment]
[JDK8 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/118/)(`win19x86-svl-rt3-1`)
```
openjdk version "1.8.0_392"
IBM Semeru Runtime Open Edition (build 1.8.0_392-b08)
Eclipse OpenJ9 VM (build v0.41.0-release-9c5799b80, JRE 1.8.0 Windows Server 2019 amd64-64-Bit Compressed References 20231018_794 (JIT enabled, AOT enabled)
OpenJ9   - 9c5799b80
OMR      - fa7b6ddc7
JCL      - b73cbdd342 based on jdk8u392-b08)

[2023-10-18T23:40:08.114Z] variation: Mode150
[2023-10-18T23:40:10.312Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-10-19T00:01:58.123Z] TEST: sun/nio/cs/TestIBMBugs.java

[2023-10-19T00:01:58.124Z] STDERR:
[2023-10-19T00:01:58.124Z] java.lang.ArrayIndexOutOfBoundsException
[2023-10-19T00:01:58.124Z] 	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
[2023-10-19T00:01:58.124Z] 	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
[2023-10-19T00:01:58.124Z] 	at java.lang.Character.getType(Character.java:6978)
[2023-10-19T00:01:58.124Z] 	at java.lang.Character.isDefined(Character.java:5758)
[2023-10-19T00:01:58.124Z] 	at java.lang.Character.isDefined(Character.java:5734)
[2023-10-19T00:01:58.124Z] 	at TestIBMBugs.bug6577466(TestIBMBugs.java:168)
[2023-10-19T00:01:58.124Z] 	at TestIBMBugs.main(TestIBMBugs.java:176)
[2023-10-19T00:01:58.124Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-19T00:01:58.124Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-10-19T00:01:58.124Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-19T00:01:58.124Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-10-19T00:01:58.124Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2023-10-19T00:01:58.124Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-10-19T00:01:58.124Z] 
[2023-10-19T00:01:58.124Z] JavaTest Message: Test threw exception: java.lang.ArrayIndexOutOfBoundsException
[2023-10-19T00:01:58.124Z] JavaTest Message: shutting down test
[2023-10-19T00:01:58.124Z] 
[2023-10-19T00:01:58.124Z] 
[2023-10-19T00:01:58.124Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.ArrayIndexOutOfBoundsException
[2023-10-19T00:01:58.124Z] --------------------------------------------------
[2023-10-19T00:03:43.507Z] Test results: passed: 328; failed: 1
[2023-10-19T00:03:57.367Z] Report written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16976676245304\jdk_nio_0\report\html\report.html
[2023-10-19T00:03:57.367Z] Results written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16976676245304\jdk_nio_0\work
[2023-10-19T00:03:57.367Z] Error: Some tests failed or other problems occurred.
[2023-10-19T00:03:57.367Z] -----------------------------------
[2023-10-19T00:03:57.367Z] jdk_nio_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35516/)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_2/211/)
```
[2025-04-04T20:37:29.790Z] variation: Mode150
[2025-04-04T20:37:30.168Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-04-04T22:04:31.873Z] TEST: sun/nio/cs/TestIBMBugs.java

[2025-04-04T22:04:31.886Z] STDERR:
[2025-04-04T22:04:31.886Z] java.lang.ArrayIndexOutOfBoundsException
[2025-04-04T22:04:31.886Z] 	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
[2025-04-04T22:04:31.886Z] 	at java.base/java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:122)
[2025-04-04T22:04:31.886Z] 	at java.base/java.lang.Character.getType(Character.java:10355)
[2025-04-04T22:04:31.886Z] 	at java.base/java.lang.Character.isDefined(Character.java:9126)
[2025-04-04T22:04:31.886Z] 	at java.base/java.lang.Character.isDefined(Character.java:9102)
[2025-04-04T22:04:31.886Z] 	at TestIBMBugs.bug6577466(TestIBMBugs.java:173)
[2025-04-04T22:04:31.886Z] 	at TestIBMBugs.main(TestIBMBugs.java:386)

[2025-04-04T22:09:17.512Z] jdk_nio_0_FAILED
```
