### ISSUE TITLE
jdk_security3_1_FAILED sun/security/ssl/SSLSocketImpl/ClientModeClientAuth.java java.lang.IllegalAccessError: invokeinterface of non-public method 'contains(Ljava/lang/Object;)Z' in java/util/HashSet

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18001]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_mac/77/)(`macaarch64rt2`):
```
java version "17.0.9-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 17.0.9+3-202308191433 (build 17.0.9-beta+3-202308191433)
Eclipse OpenJ9 VM 17.0.9+3-202308191433 (build master-b47a6d454, JRE 17 Mac OS X aarch64-64-Bit 20230819_363 (JIT enabled, AOT enabled)
OpenJ9   - b47a6d454
OMR      - ac8ca57b0
JCL      - 246f13592e based on jdk-17.0.9+3)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9-IBM%2F363%2Fibm-semeru-certified-jdk_aarch64_mac_JDK17U_2023-08-19-14-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-mac-aarch64-openj9-IBM%2F363%2Fibm-semeru-certified-testimage_aarch64_mac_JDK17U_2023-08-19-14-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-08-19T17:18:44.757Z] variation: Mode650
[2023-08-19T17:18:44.757Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-08-19T17:28:20.680Z] TEST: sun/security/ssl/SSLSocketImpl/ClientModeClientAuth.java

[2023-08-19T17:28:20.681Z] STDERR:
[2023-08-19T17:28:20.681Z] java.lang.IllegalAccessError: invokeinterface of non-public method 'contains(Ljava/lang/Object;)Z' in java/util/HashSet
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.util.AlgorithmDecomposer.decompose(AlgorithmDecomposer.java:132)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.SSLAlgorithmDecomposer.decompose(SSLAlgorithmDecomposer.java:276)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.util.AbstractAlgorithmConstraints.checkAlgorithm(AbstractAlgorithmConstraints.java:95)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.util.DisabledAlgorithmConstraints.cachedCheckAlgorithm(DisabledAlgorithmConstraints.java:979)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.util.DisabledAlgorithmConstraints.permits(DisabledAlgorithmConstraints.java:168)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.SSLAlgorithmConstraints.permits(SSLAlgorithmConstraints.java:216)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.HandshakeContext.getActiveProtocols(HandshakeContext.java:279)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:169)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:925)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1016)
[2023-08-19T17:28:20.681Z] 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:976)
[2023-08-19T17:28:20.681Z] 	at ClientModeClientAuth.doClientSide(ClientModeClientAuth.java:155)
[2023-08-19T17:28:20.681Z] 	at ClientModeClientAuth$2.run(ClientModeClientAuth.java:257)
[2023-08-19T17:28:20.682Z] STATUS:Failed.`main' threw exception: java.lang.IllegalAccessError: invokeinterface of non-public method 'contains(Ljava/lang/Object;)Z' in java/util/HashSet

[2023-08-19T17:39:24.697Z] jdk_security3_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34430/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_aarch64_mac_Personal_testList_0/96
MathLoadTest_bigdecimal_special_5m_8 `-Xgcpolicy:gencon -Xshareclasses -Xjit -Xnocompressedrefs`
```
09:01:42  MLT testFailure: null: invokeinterface of non-public method 'next()Ljava/lang/Object;' in java/util/concurrent/CopyOnWriteArrayList$COWIterator
09:01:42  MLT java.lang.IllegalAccessError: invokeinterface of non-public method 'next()Ljava/lang/Object;' in java/util/concurrent/CopyOnWriteArrayList$COWIterator
09:01:42  MLT 	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:70)
09:01:42  MLT 	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
09:01:42  MLT 	at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.endTest(JUnit38ClassRunner.java:33)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_special.system_aarch64_mac_Personal_testList_2/32
LambdaLoadTest_special_J9_5m_2
`-Xgcpolicy:optthruput -Xjit:count=0,optlevel=hot,gcOnResolve,rtResolve -Xnocompressedrefs`
```
12:11:40  LT  testStarted : testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
12:11:40  LT  load-4 MT running with 25 threads
12:11:40  LT  testFailure: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded): invokeinterface of non-public method 'execute(Ljava/util/Stack;)V' in net/adoptopenjdk/test/lambda/TestLambdaMultithreaded$$Lambda/0x00000000115f0db0
12:11:40  LT  java.lang.IllegalAccessError: invokeinterface of non-public method 'execute(Ljava/util/Stack;)V' in net/adoptopenjdk/test/lambda/TestLambdaMultithreaded$$Lambda/0x00000000115f0db0
12:11:40  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.convertFahrenheitToCelsius(TestLambdaMultithreaded.java:426)
12:11:40  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.runConvertFahrenheitToCelsius(TestLambdaMultithreaded.java:408)
12:11:40  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:239)
12:11:40  LT  	at java.base/java.lang.Thread.run(Thread.java:1595)
12:11:40  LT  testFinished: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_special.system_aarch64_mac_testList_3/178/)
```
[2026-05-24T14:29:32.889Z] Running test ParallelStreamsLoadTest_special_J9_7 ...
[2026-05-24T14:29:32.889Z] ===============================================
[2026-05-24T14:29:32.889Z] ParallelStreamsLoadTest_special_J9_7 Start Time: Sun May 24 07:29:30 2026 Epoch Time (ms): 1779632970778
[2026-05-24T14:29:32.889Z] variation: Mode145
[2026-05-24T14:29:32.889Z] JVM_OPTIONS:  -Xgcpolicy:gencon -Xshareclasses -Xjit -Xnocompressedrefs 

[2026-05-24T14:29:43.411Z] LT  testFailure: testShortLines(net.adoptopenjdk.test.streams.TestParallelStreamOperations): null
[2026-05-24T14:29:43.411Z] LT  java.lang.IllegalAccessError
[2026-05-24T14:29:43.411Z] LT  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)

[2026-05-24T14:29:43.411Z] LT  Caused by: java.lang.IllegalAccessError: invokeinterface of non-public method 'accept(Ljava/lang/Object;)V' in java/util/stream/ReferencePipeline$2$1
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:583)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:573)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
[2026-05-24T14:29:43.411Z] LT  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/60283/) - passed

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.system_aarch64_mac_testList_3/663/)
```
[2026-08-30T02:38:10.646Z] Running test DaaLoadTest_daa2_special_5m_3 ...
[2026-08-30T02:38:10.646Z] ===============================================
[2026-08-30T02:38:10.646Z] DaaLoadTest_daa2_special_5m_3 Start Time: Sat Aug 29 22:38:09 2026 Epoch Time (ms): 1788057489331
[2026-08-30T02:38:10.646Z] variation: Mode107
[2026-08-30T02:38:10.646Z] JVM_OPTIONS:  -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0 -Xnocompressedrefs 

[2026-08-30T02:38:27.831Z] DLT 22:38:26.867 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
[2026-08-30T02:38:27.831Z] DLT 22:38:26.912 - Test failed
[2026-08-30T02:38:27.831Z] DLT   Failure num.  = 1
[2026-08-30T02:38:27.831Z] DLT   Test number   = 3
[2026-08-30T02:38:27.831Z] DLT   Test details  = 'JUnit[net.openj9.test.arithmetics.TestArithmeticOperations]'
[2026-08-30T02:38:27.831Z] DLT   Suite number  = 0
[2026-08-30T02:38:27.831Z] DLT   Thread number = 2
[2026-08-30T02:38:27.831Z] DLT >>> Captured test output >>>
[2026-08-30T02:38:27.831Z] DLT Test failed:
[2026-08-30T02:38:27.831Z] DLT java.lang.IllegalAccessError: invokeinterface of non-public method 'next()Ljava/lang/Object;' in java/util/Collections$UnmodifiableCollection$1
[2026-08-30T02:38:27.831Z] DLT 	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
[2026-08-30T02:38:27.831Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:359)
[2026-08-30T02:38:27.831Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2026-08-30T02:38:27.831Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2026-08-30T02:38:27.831Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2026-08-30T02:38:27.831Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2026-08-30T02:38:27.831Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2026-08-30T02:38:27.831Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2026-08-30T02:38:27.831Z] DLT 	at java.base/java.lang.Thread.run(Thread.java:1600)
[2026-08-30T02:38:27.831Z] DLT <<<
```
