### ISSUE TITLE
OpenJDK java/util/Collection/RemoveMicroBenchmark Sum mismatch

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18012]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0/37
jdk_util_0
java/util/Collection/RemoveMicroBenchmark.java
```
23:16:06  java.lang.RuntimeException: Job failed: ConcurrentLinkedDeque descendingIterator().remove
23:16:06  	at RemoveMicroBenchmark$Job.run(RemoveMicroBenchmark.java:83)
23:16:06  	at RemoveMicroBenchmark.time0(RemoveMicroBenchmark.java:155)
23:16:06  	at RemoveMicroBenchmark.time(RemoveMicroBenchmark.java:165)
23:16:06  	at RemoveMicroBenchmark.run(RemoveMicroBenchmark.java:331)
23:16:06  	at RemoveMicroBenchmark.main(RemoveMicroBenchmark.java:257)
23:16:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:16:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
23:16:06  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:16:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
23:16:06  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
23:16:06  	at java.base/java.lang.Thread.run(Thread.java:857)
23:16:06  Caused by: java.lang.AssertionError: Sum mismatch
23:16:06  	at RemoveMicroBenchmark$Check.sum(RemoveMicroBenchmark.java:251)
23:16:06  	at RemoveMicroBenchmark$13.work(RemoveMicroBenchmark.java:494)
23:16:06  	at RemoveMicroBenchmark$Job.run(RemoveMicroBenchmark.java:80)
23:16:06  	... 10 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_1/640
jdk_collections_0
java/util/Collection/RemoveMicroBenchmark.java
```
02:58:06  java.lang.RuntimeException: Job failed: ConcurrentLinkedDeque descendingIterator().remove
02:58:06  	at RemoveMicroBenchmark$Job.run(RemoveMicroBenchmark.java:83)
02:58:06  	at RemoveMicroBenchmark.time0(RemoveMicroBenchmark.java:155)
02:58:06  	at RemoveMicroBenchmark.time(RemoveMicroBenchmark.java:165)
02:58:06  	at RemoveMicroBenchmark.run(RemoveMicroBenchmark.java:331)
02:58:06  	at RemoveMicroBenchmark.main(RemoveMicroBenchmark.java:257)
02:58:06  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
02:58:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
02:58:06  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:335)
02:58:06  	at java.base/java.lang.Thread.run(Thread.java:1600)
02:58:06  Caused by: java.lang.AssertionError: Sum mismatch
02:58:06  	at RemoveMicroBenchmark$Check.sum(RemoveMicroBenchmark.java:251)
02:58:06  	at RemoveMicroBenchmark$13.work(RemoveMicroBenchmark.java:494)
02:58:06  	at RemoveMicroBenchmark$Job.run(RemoveMicroBenchmark.java:80)
02:58:06  	... 8 more
```
