### ISSUE TITLE
JTReg test failure due to java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9#18049]
Failing JTReg testcases:
```
jdk/internal/vm/Continuation/MovingCompWindow.java
serviceability/jvmti/vthread/ToggleNotifyJvmtiTest/ToggleNotifyJvmtiTest.java
```
Error message:
```
java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V
at jdk.test.whitebox.WhiteBox.<clinit>(WhiteBox.java:67)
at ToggleNotifyJvmtiTest.<clinit>(ToggleNotifyJvmtiTest.java:102)
at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:159)
at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
at java.base/java.lang.Thread.run(Thread.java:1595)
```
The WhiteBox class uses VM internal APIs which do not apply to OpenJ9 implementation.

**Comment by babsingh** [comment]
The above stack trace only reflects the issue for `ToggleNotifyJvmtiTest`. We should also add the stack trace for `MovingCompWindow` in the issue description.
