### ISSUE TITLE
JTReg test failure java/lang/Thread/virtual/GetStackTrace.java

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9#18052]
Failure output (captured from console output)
---------------------------------------------
```
[2023-08-29T18:48:18.499Z] STDOUT:
[2023-08-29T18:48:18.499Z] VirtualThread[#49]/waiting@Thread-3
[2023-08-29T18:48:18.499Z] java.base/java.lang.Object.waitImpl(Native Method)
[2023-08-29T18:48:18.499Z] java.base/java.lang.Object.wait(Object.java:255)
[2023-08-29T18:48:18.499Z] java.base/java.lang.Object.wait(Object.java:192)
[2023-08-29T18:48:18.499Z] GetStackTrace.lambda$main$0(GetStackTrace.java:48)
[2023-08-29T18:48:18.499Z] java.base/java.lang.VirtualThread.run(VirtualThread.java:317)
[2023-08-29T18:48:18.499Z] java.base/jdk.internal.vm.Continuation.enter(Continuation.java:177)
[2023-08-29T18:48:18.499Z] STDERR:
[2023-08-29T18:48:18.499Z] java.lang.RuntimeException
[2023-08-29T18:48:18.499Z] 	at GetStackTrace.assertEquals(GetStackTrace.java:127)
[2023-08-29T18:48:18.499Z] 	at GetStackTrace.main(GetStackTrace.java:63)
[2023-08-29T18:48:18.499Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-08-29T18:48:18.499Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-08-29T18:48:18.499Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2023-08-29T18:48:18.499Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by fengxue-IS** [comment]
I looked at the test code and what is being expected, looking at the test comments on assertion code:
> // bottom-most frame of virtual thread should be VirtualThread.run
// top-most frame of carrier thread should be Continuation.run
// bottom-most frame of carrier thread should be Thread.run

This test is expected a stack trace layout in the continuation start phase where intermediate frames are skipped/hidden
Since OpenJ9 have its own impl of Continuation.class, the non-public API naming/wrapper don't exactly match.

I will experiment locally to see if simple `@Hidden` annotation and renaming can match RI's behaviour.

**Comment by babsingh** [comment]
The test needs to be re-enabled before the issue can be closed. @fengxue-IS Can you please re-enable the test?

**Comment by fengxue-IS** [comment]
> The test needs to be re-enabled before the issue can be closed. @fengxue-IS Can you please re-enable the test?

I am verifying the re-enable PR via personal build, will open once build passes
