### ISSUE TITLE
JTReg test failure java/lang/Thread/virtual/CarrierThreadWaits.java

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9#18051]
Failure output (captured from console output)
---------------------------------------------
```
[2023-08-29T18:48:18.496Z] STARTED    CarrierThreadWaits::testCarrierThreadWaiting 'testCarrierThreadWaiting()'
[2023-08-29T18:48:18.496Z] org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
[2023-08-29T18:48:18.496Z] 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
[2023-08-29T18:48:18.496Z] 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
[2023-08-29T18:48:18.496Z] 	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
[2023-08-29T18:48:18.496Z] 	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
[2023-08-29T18:48:18.496Z] 	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
[2023-08-29T18:48:18.496Z] 	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
[2023-08-29T18:48:18.497Z] 	at CarrierThreadWaits.testCarrierThreadWaiting(CarrierThreadWaits.java:85)
[2023-08-29T18:48:18.497Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-08-29T18:48:18.497Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
...
[2023-08-29T18:48:18.497Z] FAILED     CarrierThreadWaits::testCarrierThreadWaiting 'testCarrierThreadWaiting()'
```

**Comment by babsingh** [comment]
The test was re-enabled via https://github.com/adoptium/aqa-tests/pull/4781.
