### ISSUE TITLE
AArch64 Linux JDK11 personal build fails with java.time.DateTimeException

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse-openj9/openj9#18057]
AArch64 Linux JDK11 personal build on internal Jenkins fails with `java.time.DateTimeException`.

https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDK11_aarch64_linux_Personal/552/consoleText
```
[Pipeline] echo
[2023-08-30T07:48:08.030Z] Using OPENJDK_REPO = git@github.com:ibmruntimes/openj9-openjdk-jdk11.git OPENJDK_BRANCH = openj9 OPENJDK_SHA = 07e588c7cb214e6f25d8c777adabf218a5f21a82
[Pipeline] echo
[2023-08-30T07:48:08.069Z] Using OPENJ9_REPO = git@github.com:eclipse/openj9.git OPENJ9_BRANCH = master OPENJ9_SHA = 39071983a8a61155a04e9f922d0c5943c8fc6a3d
[Pipeline] echo
[2023-08-30T07:48:08.072Z] Using OMR_REPO = git@github.com:eclipse/openj9-omr.git OMR_BRANCH = openj9 OMR_SHA = 9659cbcdcef670fda03609c058e5cb04c58c6511
...
[2023-08-30T08:17:03.901Z] Creating images/jmods/java.prefs.jmod
[2023-08-30T08:17:03.901Z] Error: Invalid value for NanoOfDay (valid values 0 - 86399999999999): -679949392276000000
[2023-08-30T08:17:03.901Z] java.time.DateTimeException: Invalid value for NanoOfDay (valid values 0 - 86399999999999): -679949392276000000
[2023-08-30T08:17:03.901Z] 	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
[2023-08-30T08:17:03.901Z] 	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
[2023-08-30T08:17:03.901Z] 	at java.base/java.time.LocalTime.ofNanoOfDay(LocalTime.java:398)
[2023-08-30T08:17:03.901Z] 	at java.base/java.time.LocalDateTime.ofEpochSecond(LocalDateTime.java:423)
[2023-08-30T08:17:03.901Z] 	at java.base/java.time.LocalDateTime.ofInstant(LocalDateTime.java:398)
[2023-08-30T08:17:03.901Z] 	at java.base/java.util.zip.ZipUtils.javaToDosTime(ZipUtils.java:140)
[2023-08-30T08:17:03.901Z] 	at java.base/java.util.zip.ZipUtils.javaToExtendedDosTime(ZipUtils.java:165)
[2023-08-30T08:17:03.901Z] 	at java.base/java.util.zip.ZipEntry.setTime(ZipEntry.java:172)
[2023-08-30T08:17:03.901Z] 	at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:204)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodOutputStream.writeEntry(JmodOutputStream.java:74)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter$3.visitFile(JmodTask.java:790)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter$3.visitFile(JmodTask.java:777)
[2023-08-30T08:17:03.901Z] 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2725)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.processSection(JmodTask.java:776)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.processClasses(JmodTask.java:752)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.write(JmodTask.java:484)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodTask.create(JmodTask.java:438)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.JmodTask.run(JmodTask.java:208)
[2023-08-30T08:17:03.901Z] 	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)
[2023-08-30T08:17:03.901Z] CreateJmods.gmk:222: recipe for target '/home/jenkins/workspace/Build_JDK11_aarch64_linux_Personal/build/linux-aarch64-normal-server-release/images/jmods/java.desktop.jmod' failed
```

**Comment by Akira1Saitoh** [comment]
I can reproduce the problem locally. I got system dumps using xdump options.
```
JVMDUMP055I Processing dump event "throw", detail "java/time/DateTimeException", exception "Invalid value for NanoOfDay (valid v
alues 0 - 86399999999999): -680660136542000000" at 2023/08/30 21:51:19 - please wait.
```
```
jshell> Long.toHexString(-680660136542000000L)
$1 ==> "f68dcf364ca52c80"
```

The argument to `LocalTime.ofNanoOfDay` is wrong.

```
<11200> J2I frame: bp = 0x00000000000FEAD0, sp = 0x00000000000FEA50, pc = 0x0000FFFF497240C4, cp = 0x000000000025BEC0, arg0EA = 
0x00000000000FEAF8, flags = 0x0000000010000000
<11200>         Method: java/time/LocalTime.ofNanoOfDay(J)Ljava/time/LocalTime; !j9method 0x000000000025CB28
<11200>         Bytecode index = 4
<11200>         Using local mapper
<11200>         Locals starting at 0x00000000000FEAF8 for 0x0000000000000005 slots
<11200>                 I-Slot: a0[0x00000000000FEAF8] = 0x0000000000254200
<11200>                 I-Slot: a1[0x00000000000FEAF0] = 0xF68DCF364CA52C80  <--- (-680660136542000000L)
<11200>                 I-Slot: t2[0x00000000000FEAE8] = 0x0000FFFF8045BC14
<11200>                 I-Slot: t3[0x00000000000FEAE0] = 0x0000FFFF8045BC14
<11200>                 I-Slot: t4[0x00000000000FEAD8] = 0x00000000000000A3
<11200>         JIT-J2I-RegisterMap[0x00000000000FEA78] = UDATA(0x00000000FFB31528) (jit_r21)
<11200>         JIT-J2I-RegisterMap[0x00000000000FEA80] = UDATA(0x000000001B4C8680) (jit_r22)
<11200>         JIT-J2I-RegisterMap[0x00000000000FEA88] = UDATA(0x000000003B9ACA00) (jit_r23)
<11200>         JIT-J2I-RegisterMap[0x00000000000FEA90] = UDATA(0x0000000000015180) (jit_r24)
<11200>         JIT-J2I-RegisterMap[0x00000000000FEA98] = UDATA(0x00000000FFB31180) (jit_r25)
<11200>         JIT-J2I-RegisterMap[0x00000000000FEAA0] = UDATA(0x0000000000000001) (jit_r26)
<11200>         JIT-J2I-RegisterMap[0x00000000000FEAA8] = UDATA(0x00000000FFB50590) (jit_r27)
<11200>         JIT-J2I-RegisterMap[0x00000000000FEAB0] = UDATA(0x00000000FFB31280) (jit_r28)
<11200> JIT frame: bp = 0x00000000000FEB58, pc = 0x0000FFFF8045B52C, unwindSP = 0x00000000000FEAF0, cp = 0x0000000000256490, arg0EA = 0x00000000000FEB78, jitInfo = 0x0000FFFF7CB6B5F8
<11200>         Method: java/time/LocalDateTime.ofEpochSecond(JILjava/time/ZoneOffset;)Ljava/time/LocalDateTime; !j9method 0x0000000000257368
<11200>         Bytecode index = 60, inlineDepth = 0, PC offset = 0x00000000000001C4
<11200>         stackMap=0x0000FFFF7CB6B82C, slots=I16(0x0004) parmBaseOffset=I16(0x0008), parmSlots=U16(0x0001), localBaseOffset=I16(0xFFF8)
<11200>         Described JIT args starting at 0x00000000000FEB60 for U16(0x0001) slots
<11200>                 I-Slot: : a0[0x00000000000FEB60] = 0x00000000FFB1C4F8
<11200>         Described JIT temps starting at 0x00000000000FEB50 for IDATA(0x0000000000000001) slots
<11200>                 I-Slot: : t0[0x00000000000FEB50] = 0x0000000000257348
<11200>         JIT-RegisterMap = UDATA(0x0000000000200000)
<11200>                 JIT-RegisterMap-O-Slot[0x00000000000FEA78] = 0x00000000FFB31528 (jit_r21)
<11200>                 JIT-RegisterMap-I-Slot[0x00000000000FEA80] = UDATA(0x000000001B4C8680) (jit_r22)
<11200>                 JIT-RegisterMap-I-Slot[0x00000000000FEA88] = UDATA(0x000000003B9ACA00) (jit_r23)
<11200>                 JIT-RegisterMap-I-Slot[0x00000000000FEA90] = UDATA(0x0000000000015180) (jit_r24)
<11200>                 JIT-RegisterMap-I-Slot[0x00000000000FEA98] = UDATA(0x00000000FFB31180) (jit_r25)
<11200>                 JIT-RegisterMap-I-Slot[0x00000000000FEAA0] = UDATA(0x0000000000000001) (jit_r26)
<11200>                 JIT-RegisterMap-I-Slot[0x00000000000FEAA8] = UDATA(0x00000000FFB50590) (jit_r27)
<11200>                 JIT-RegisterMap-I-Slot[0x00000000000FEAB0] = UDATA(0x00000000FFB31280) (jit_r28)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEB10] = UDATA(0x0000000000058B00) (jit_r21)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEB18] = UDATA(0x00000000000F3000) (jit_r22)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEB20] = UDATA(0x0000000000000039) (jit_r23)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEB28] = UDATA(0x00000000FFFFFFFF) (jit_r24)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEB30] = UDATA(0x00000000FFB31180) (jit_r25)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEB38] = UDATA(0x0000000000000001) (jit_r26)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEAA8] = UDATA(0x00000000FFB50590) (jit_r27)
<11200>         JIT-Frame-RegisterMap[0x00000000000FEAB0] = UDATA(0x00000000FFB31280) (jit_r28)
```

**Comment by Akira1Saitoh** [comment]
The problem is reproducible with below program.
```
import java.time.*;

public class TestLocalDate {

        public static void main(String[] args) throws InterruptedException {
                for (int i = 0; i < 2048; i++) {
                        testLocalDate(i);
                }
                Thread.sleep(20000);
                System.out.println(testLocalDate(1693450615L));
        }

        public static LocalDateTime testLocalDate(long epochSecond) {
                return LocalDateTime.ofEpochSecond(epochSecond, 0, ZoneOffset.ofHours(0));
        }
}

```

**Comment by Akira1Saitoh** [comment]
It seems that `smulh` instruction generated for `lmulh` opcode produces a wrong result.

```
   0xffffdc19d110:      lsr     x14, x11, #63
   0xffffdc19d114:      mov     x4, #0x2957                     // #10583
   0xffffdc19d118:      movk    x4, #0xce51, lsl #16
   0xffffdc19d11c:      movk    x4, #0xc8a0, lsl #32
   0xffffdc19d120:      movk    x4, #0x1845, lsl #48
   0xffffdc19d124:      smulh   x3, x11, x4
=> 0xffffdc19d128:      add     x14, x14, x3, asr #13
(gdb) info reg x11 x4 x3
x11            0x64f00177          1693450615
x4             0x1845c8a0ce512957  1749024623285053783
x3             0x6e820565          1854014821
```

[smulh](https://developer.arm.com/documentation/ddi0596/2020-12/Base-Instructions/SMULH--Signed-Multiply-High-) multiplies two 64-bit register values, and returns upper 64-bit of the result.
In this case, the value in `x3` should be `0x99203ee` instead of `0x6e820565`.

```
jshell> BigInteger a = BigInteger.valueOf(0x64f00177)
a ==> 1693450615

jshell> a
a ==> 1693450615

jshell> BigInteger b = BigInteger.valueOf(0x1845c8a0ce512957L)
b ==> 1749024623285053783

jshell> a.multiply(b).shiftRight(64).toString(16)
$13 ==> "99203ee"
```

According to the manual, bit 10 - 14 of `smulh` instruction should be 1, but it appears that we fail to do so. Possibly this is the reason why the instruction produces the wrong result.
```
(gdb) x/i 0xffffdc19d124
   0xffffdc19d124:      smulh   x3, x11, x4
(gdb) x/x 0xffffdc19d124
0xffffdc19d124: 0x9b440163
```

**Comment by Akira1Saitoh** [comment]
I wrote a simple assembly program to verify my hypothesis.
A correctly encoded `smulh` instruction produces the correct value on our internal development machine.
```
(gdb) x/i $pc
=> 0xaaaaaaaaa7b8 <testDiv+16>: smulh   x1, x0, x1
(gdb) x/x $pc
0xaaaaaaaaa7b8 <testDiv+16>:    0x9b417c01
(gdb) info reg x0 x1
x0             0x64f00177          1693450615
x1             0x1845c8a0ce512957  1749024623285053783
(gdb) stepi
0x0000aaaaaaaaa7bc in testDiv ()
(gdb) info reg x1
x1             0x99203ee           160564206
```

A incorrectly encoded `smulh` instruction produces the wrong value on the same machine.
```
(gdb) x/i $pc
=> 0xaaaaaaaaa7b8 <testDiv+16>: smulh   x1, x0, x1
(gdb) x/x $pc
0xaaaaaaaaa7b8 <testDiv+16>:    0x9b410001
(gdb) info reg x0 x1
x0             0x64f00177          1693450615
x1             0x1845c8a0ce512957  1749024623285053783
(gdb) stepi
0x0000aaaaaaaaa7bc in testDiv ()
(gdb) info reg x1
x1             0x6e820565          1854014821
```

**Comment by Akira1Saitoh** [comment]
I opened https://github.com/eclipse/omr/pull/7104.
