### ISSUE TITLE
JDK jdk_lang_0_FAILED java/lang/ScopedValue/StressStackOverflow.java StressStackOverflow$TestFailureException: Unexpected value for ScopedValue 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18065]
Failure link
------------

From https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/262/consoleFull(`cent8-aarch64-3`):
```
10:23:03  openjdk version "22-internal" 2024-03-19
10:23:03  OpenJDK Runtime Environment (build 22-internal-adhoc.****.BuildJDKnextaarch64linuxPersonal)
10:23:03  Eclipse OpenJ9 VM (build master-080f0db8115, JRE 22 Linux aarch64-64-Bit Compressed References 20230831_72 (JIT enabled, AOT enabled)
10:23:03  OpenJ9   - 080f0db8115
10:23:03  OMR      - 75d233597f4
10:23:03  JCL      - b999c60c064 based on jdk-22+12)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&EXTRA_DOCKER_ARGS=&PLATFORM=aarch64_linux&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=&JENKINS_KEY=&LIGHT_WEIGHT_CHECKOUT=true&ARTIFACTORY_SERVER=ci-eclipse-openj9&USE_JRE=false&KEEP_WORKSPACE=false&JDK_VERSION=next&DOCKER_REGISTRY_URL=&EXIT_FAILURE=false&EXIT_SUCCESS=false&JDK_REPO=https%3A%2F%2Fgithub.com%2Ffengxue-IS%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&JDK_BRANCH=fengxue-IS-patch-1&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&UPSTREAM_TEST_JOB_NUMBER=2862&DOCKERIMAGE_TAG=&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&OPENJDK_SHA=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&JDK_VENDOR=&BUILDS_TO_KEEP=60&TIME_LIMIT=10&PARALLEL=None&TARGET=testList+TESTLIST=jdk_lang_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Grinder&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&GENERATE_JOBS=true&KEEP_REPORTDIR=true&RERUN_ITERATIONS=0&LABEL=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_aarch64_linux_Personal%2F72%2FOpenJ9-JDKnext-aarch64_linux-20230831-133722.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_aarch64_linux_Personal%2F72%2Ftest-images.tar.gz&DAYS_TO_KEEP=7&ADOPTOPENJDK_BRANCH=master&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_REPO=&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&VENDOR_TEST_SHAS=&TEST_IMAGES_REQUIRED=true&ARTIFACTORY_ROOT_DIR=Test&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TKG_ITERATIONS=1&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=&ADDITIONAL_ARTIFACTS_REQUIRED=&JVM_OPTIONS=) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
10:24:44  ===============================================
10:24:44  Running test jdk_lang_0 ...
10:24:44  ===============================================
10:24:44  jdk_lang_0 Start Time: Fri Sep  1 10:24:44 2023 Epoch Time (ms): 1693578284203
10:24:44  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
10:24:44  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

10:33:11  TEST: java/lang/ScopedValue/StressStackOverflow.java#default
10:33:11  STDERR:
10:33:11  StressStackOverflow$TestFailureException: Unexpected value for ScopedValue
10:33:11  	at StressStackOverflow.<clinit>(StressStackOverflow.java:62)
10:33:11  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
10:33:11  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
10:33:11  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
10:33:11  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
10:33:11  	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:154)
10:33:11  	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
10:33:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
10:33:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
10:33:11  	at java.base/java.lang.Thread.run(Thread.java:1582)
10:33:11  	Suppressed: java.util.concurrent.StructureViolationException
10:33:11  		at java.base/jdk.internal.vm.ScopedValueContainer.throwIfFailed(ScopedValueContainer.java:203)
10:33:11  		at java.base/jdk.internal.vm.ScopedValueContainer.doCall(ScopedValueContainer.java:192)
10:33:11  		at java.base/jdk.internal.vm.ScopedValueContainer.call(ScopedValueContainer.java:149)
10:33:11  		at java.base/java.lang.Class$ReflectRef.<init>(Class.java:4064)
10:33:11  		at StressStackOverflow$DeepRecursion.run(StressStackOverflow.java:100)
10:33:11  		at StressStackOverflow.fibonacci_pad1(StressStackOverflow.java:146)
...
10:33:11  	Suppressed: java.util.concurrent.StructureViolationException
10:33:11  		at java.base/jdk.internal.vm.ScopedValueContainer.throwIfFailed(ScopedValueContainer.java:203)
10:33:11  		at java.base/jdk.internal.vm.ScopedValueContainer.runWithoutScope(ScopedValueContainer.java:120)
10:33:11  		at java.base/jdk.internal.vm.ScopedValueContainer.run(ScopedValueContainer.java:98)
10:33:11  		at java.base/java.lang.ScopedValue$Carrier.run(ScopedValue.java:510)
10:33:11  		at StressStackOverflow.run(StressStackOverflow.java:189)
10:33:11  		at StressStackOverflow.main(StressStackOverflow.java:248)
10:33:11  		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
10:33:11  		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
10:33:11  		... 2 more

10:33:11  TEST: java/lang/ScopedValue/StressStackOverflow.java#no-TieredCompilation
10:33:11  STDERR:
10:33:11  StressStackOverflow$TestFailureException: Unexpected value for ScopedValue
10:33:11  	at StressStackOverflow.<clinit>(StressStackOverflow.java:62)
10:33:11  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
10:33:11  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
10:33:11  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
10:33:11  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
10:33:11  	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:154)
10:33:11  	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
10:33:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
10:33:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
10:33:11  	at java.base/java.lang.Thread.run(Thread.java:1582)
10:33:11  	Suppressed: java.util.concurrent.StructureViolationException

10:40:43  TEST: java/lang/ScopedValue/StressStackOverflow.java#no-vmcontinuations
10:40:43  STDERR:
10:40:43  StressStackOverflow$TestFailureException: Unexpected value for ScopedValue
10:40:43  	at StressStackOverflow.<clinit>(StressStackOverflow.java:62)
10:40:43  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
10:40:43  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
10:40:43  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
10:40:43  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
10:40:43  	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:154)
10:40:43  	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
10:40:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
10:40:43  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
10:40:43  	at java.base/java.lang.Thread.run(Thread.java:1582)
10:40:43  	Suppressed: java.util.concurrent.StructureViolationException

10:46:14  TEST: java/lang/ScopedValue/StressStackOverflow.java#TieredStopAtLevel1
10:46:14  STDERR:
10:46:14  StressStackOverflow$TestFailureException: Unexpected value for ScopedValue
10:46:14  	at StressStackOverflow.<clinit>(StressStackOverflow.java:62)
10:46:14  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
10:46:14  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
10:46:14  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
10:46:14  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
10:46:14  	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:154)
10:46:14  	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
10:46:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
10:46:14  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
10:46:14  	at java.base/java.lang.Thread.run(Thread.java:1582)
10:46:14  	Suppressed: java.util.concurrent.StructureViolationException

10:46:14  TEST RESULT: Failed. Unexpected exit from test [exit code: 1]
10:46:14  --------------------------------------------------
10:46:14  Test results: passed: 924; failed: 8
10:46:21  Report written to /home/jenkins/workspace/Grinder_testList_0/aqa-tests/TKG/output_16935782835648/jdk_lang_0/report/html/report.html
10:46:21  Results written to /home/jenkins/workspace/Grinder_testList_0/aqa-tests/TKG/output_16935782835648/jdk_lang_0/work
10:46:21  Error: Some tests failed or other problems occurred.
10:46:21  -----------------------------------
10:46:21  jdk_lang_0_FAILED
```

**Comment by pshipton** [comment]
Can you pls update the exclude for jdk21 so we can accept the level.

**Comment by pshipton** [comment]
We can close this as a dup.

**Comment by pshipton** [comment]
> Can you pls update the exclude for jdk21 so we can accept the level.

and jdk22 so be updated as well.

**Comment by babsingh** [comment]
> Can you pls update the exclude for jdk21 so we can accept the level.

Opened https://github.com/adoptium/aqa-tests/pull/4828 to update the JDK21/22 excludes.
