### ISSUE TITLE
JDK8 ibuild AssertionFailedError: Failed to construct parameter list for command : !stackslots thread,sp,a0,pc,literals,els

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18073]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=67652833)(`aix72p7-02`):
```
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pap6480sr9-20230615_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20230901_57365 (JIT enabled, AOT enabled)
OpenJ9   - ea96716
OMR      - a0097c7
IBM      - 696e9df)
JCL - 20230608_01 based on Oracle jdk8u381-b06
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
     [java] 20230901 23:55:07- Starting testJ9VMThread(j9vm.test.ddrext.junit.TestThread)
     [java] 00011530junit.framework.AssertionFailedError: Failed to construct parameter list for command : !stackslots thread,sp,a0,pc,literals,els
     [java] StackSlots Output being used : 
     [java] <3411e100> *** BEGIN STACK WALK, flags = 00400001 walkThread = 873,586,944 ***
     [java] <3411e100>  ITERATE_O_SLOTS
     [java] <3411e100>  RECORD_BYTECODE_PC_OFFSET
     [java] <3411e100> Initial values: walkSP = 0x3411DF44, PC = 0x00000006, literals = 0x00000000, A0 = 0x3411DFF4, j2iFrame = 0x00000000, decomp = 0x00000000
     [java] <3411e100> JIT JNI call-out frame: bp = 0x3411DF54, sp = 0x3411DF44, pc = 0x00000006, cp = 0x32467230, arg0EA = 0x3411DFF4, flags = 0x20000000
     [java] <3411e100>  Method: java/lang/Thread.sleepImpl(JI)V !j9method 0x32467B44
     [java] <3411e100> JIT frame: bp = 0x3411DFB4, pc = 0x31713EB4, unwindSP = 0x3411DF58, cp = 0x32467230, arg0EA = 0x3411DFC0, jitInfo = 0x322E74F8
     [java] <3411e100>  Method: java/lang/Thread.sleep(JI)V !j9method 0x32467B34
     [java] <3411e100>  Bytecode index = 2, inlineDepth = 0, PC offset = 0x000000B4
     [java] <3411e100>  stackMap=0x322E7581, slots=I16(0x0003) parmBaseOffset=I16(0x0010), parmSlots=U16(0x0000), localBaseOffset=I16(0x0000)
     [java] <3411e100>  Described JIT temps starting at 0x3411DFB4 for IDATA(0x00000000) slots
     [java] <3411e100>  JIT-RegisterMap = UDATA(0x00000000)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF68] = UDATA(0xFFFFFFFF) (jit_r15)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF6C] = UDATA(0x00000000) (jit_r16)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF70] = UDATA(0x00000000) (jit_r17)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF74] = UDATA(0x33FDB2D8) (jit_r18)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF78] = UDATA(0x32F67E60) (jit_r19)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF7C] = UDATA(0x00000000) (jit_r20)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF80] = UDATA(0x00000000) (jit_r21)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF84] = UDATA(0x00000009) (jit_r22)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF88] = UDATA(0xCB16962F) (jit_r23)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF8C] = UDATA(0xF148D990) (jit_r24)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF90] = UDATA(0xF1481C30) (jit_r25)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF94] = UDATA(0x3403C5B0) (jit_r26)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF98] = UDATA(0x3403C768) (jit_r27)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF9C] = UDATA(0x00000000) (jit_r28)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DFA0] = UDATA(0x00001002) (jit_r29)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DFA4] = UDATA(0x00000000) (jit_r30)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DFA8] = UDATA(0x00002710) (jit_r31)
     [java] <3411e100> JIT frame: bp = 0x3411DFD4, pc = 0x31713D10, unwindSP = 0x3411DFB8, cp = 0x32467230, arg0EA = 0x3411DFDC, jitInfo = 0x322E73B8
     [java] <3411e100>  Method: java/lang/Thread.sleep(J)V !j9method 0x32467B24
     [java] <3411e100>  Bytecode index = 2, inlineDepth = 0, PC offset = 0x00000054
     [java] <3411e100>  stackMap=0x322E7441, slots=I16(0x0002) parmBaseOffset=I16(0x000C), parmSlots=U16(0x0000), localBaseOffset=I16(0x0000)
     [java] <3411e100>  Described JIT temps starting at 0x3411DFD4 for IDATA(0x00000000) slots
     [java] <3411e100>  JIT-RegisterMap = UDATA(0x00000000)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF68] = UDATA(0xFFFFFFFF) (jit_r15)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF6C] = UDATA(0x00000000) (jit_r16)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF70] = UDATA(0x00000000) (jit_r17)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF74] = UDATA(0x33FDB2D8) (jit_r18)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF78] = UDATA(0x32F67E60) (jit_r19)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF7C] = UDATA(0x00000000) (jit_r20)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF80] = UDATA(0x00000000) (jit_r21)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF84] = UDATA(0x00000009) (jit_r22)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF88] = UDATA(0xCB16962F) (jit_r23)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF8C] = UDATA(0xF148D990) (jit_r24)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF90] = UDATA(0xF1481C30) (jit_r25)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF94] = UDATA(0x3403C5B0) (jit_r26)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF98] = UDATA(0x3403C768) (jit_r27)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DF9C] = UDATA(0x00000000) (jit_r28)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DFA0] = UDATA(0x00001002) (jit_r29)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DFC4] = UDATA(0xF1497CC8) (jit_r30)
     [java] <3411e100>  JIT-Frame-RegisterMap[0x3411DFC8] = UDATA(0x3411E6A4) (jit_r31)
     [java] <3411e100> I2J values: PC = 0xEE2B95C7, A0 = 0x3411DFF4, walkSP = 0x3411DFE4, literals = 0x32CB9234, JIT PC = 0xD802A208, pcAddress = 0x3403C794, decomp = 0x00000000
     [java] <3411e100> Bytecode frame: bp = 0x3411DFEC, sp = 0x3411DFE4, pc = 0xEE2B95C7, cp = 0x32CB91E0, arg0EA = 0x3411DFF4, flags = 0x00000000
     [java] <3411e100>  Method: com/ibm/dtfj/tck/tests/javaruntime/TestJavaRuntime_getHeapRoots$HeapRootsTestThread.run()V !j9method 0x32CB9234
     [java] <3411e100>  Bytecode index = 3
     [java] <3411e100>  Using local mapper
     [java] <3411e100>  Locals starting at 0x3411DFF4 for 0x00000002 slots
     [java] <3411e100>          I-Slot: a0[0x3411DFF4] = 0xCFF8E850
     [java] <3411e100>          I-Slot: t1[0x3411DFF0] = 0x00000000
     [java] <3411e100> JNI call-in frame: bp = 0x3411E008, sp = 0x3411DFF8, pc = 0xD7D90AB0, cp = 0x00000000, arg0EA = 0x3411E008, flags = 0x00000000
     [java] <3411e100>  New ELS = 0x00000000
     [java] <3411e100> JNI native method frame: bp = 0x3411E01C, sp = 0x3411E00C, pc = 0x00000007, cp = 0x00000000, arg0EA = 0x3411E01C, flags = 0x00000000
     [java] <3411e100> <end of stack>
     [java] <3411e100> *** END STACK WALK (rc = NONE) ***
     [java] 
     [java]     at junit.framework.Assert.fail(Assert.java:47)
     [java]     at j9vm.test.ddrext.junit.TestThread.testStackSlots(TestThread.java:80)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
     [java]     at java.lang.reflect.Method.invoke(Method.java:508)
     [java]     at junit.framework.TestCase.runTest(TestCase.java:154)
     [java]     at junit.framework.TestCase.runBare(TestCase.java:127)
     [java]     at junit.framework.TestResult$1.protect(TestResult.java:106)
     [java]     at junit.framework.TestResult.runProtected(TestResult.java:124)
     [java]     at junit.framework.TestResult.run(TestResult.java:109)
     [java]     at junit.framework.TestCase.run(TestCase.java:118)
     [java]     at junit.framework.TestSuite.runTest(TestSuite.java:208)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:62)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:57)
     [java]     at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:43)
     [java]     at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:262)
     [java]     at j9vm.test.ddrext.AutoRun.main(AutoRun.java:97)
     [java] 62914568295047000185220203600160080940282800000000000108163132680100902600100000000020230901 23:55:07- Validation started for : '!j9vmthread  0x3411e100'
     [java] 20230901 23:55:07- Starting exhaustive DDR structure test for parent command : '!j9vmthread  0x3411e100'
     [java] 20230901 23:55:07- Runing structure test with : !jninativeinterface_ 0xF149A9E8
     [java] 20230901 23:55:07- Structure validation passed
     [java] 20230901 23:55:07- Runing structure test with : !j9javavm 0x301A7DD0
     [java] 105062402162726350680577021637281047327680327681310720429496729520655002621450000008413679208413679368413679528413679683000080940282807262144096324525632451110013107240486934600204815131616320010011234542926111638420481111111111011111111083650000192512429496729508160000000205-1174440014800841367984841368000042949672950001280111010241025620230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9x 0x3411DFF4
     [java] 20230901 23:55:08- Can not validate: '!j9x  0x3411DFF4' output is not a structure
     [java] 20230901 23:55:08- Runing structure test with : !j9object 0x00000000
     [java] 20230901 23:55:08- Can not validate: '!j9object  0x00000000' output is not a structure
     [java] 20230901 23:55:08- Runing structure test with : !j9threadmonitor 0x32D11B78
     [java] 0629145600020230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9javastack 0x3411D020
     [java] 2048020230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9stackelement 0x00000000
     [java] 20230901 23:55:08- '!j9stackelement  0x00000000' output contains <FAULT> references
     [java] 20230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9stackwalkstate 0x3411E298
     [java] 000000000000000020230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9vmentrylocalstorage 0x3403C780
     [java] 20230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9vmgcsublistfragment 0x3411E24C
     [java] 320020230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !mm_gcrememberedsetfragment 0x3411E264
     [java] 0020230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9pool 0x32F58610
     [java] 162244096448214748365020230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9monitorenterrecord 0x00000000
     [java] 20230901 23:55:08- '!j9monitorenterrecord  0x00000000' output contains <FAULT> references
     [java] 20230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9jitdecompilationinfo 0x00000000
     [java] 20230901 23:55:08- '!j9jitdecompilationinfo  0x00000000' output contains <FAULT> references
     [java] 20230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !j9modronthreadlocalheap 0x3411E3FC
     [java] 0409620230901 23:55:08- Structure validation passed
     [java] 20230901 23:55:08- Runing structure test with : !portlibptbuffers_ 0x00000000
     [java] 20230901 23:55:08- '!portlibptbuffers_  0x00000000' is not recognized
     [java] 20230901 23:55:08- Structure validation failed
     [java] 20230901 23:55:08- Unrecognised command: !portlibptbuffers_ 0x00000000
     [java] 20230901 23:57:23- ================Test Result for /tmp/bld_57365/testDDRExtJunit_multiCore/67652833/output/tck/cores/aix_ppc-32.core.b57365.80_29.dmp==================
     [java] 20230901 23:57:23- Errors:   0 out of 89 test cases.
     [java] 20230901 23:57:23- Failures: 1 out of 89 test cases.
     [java] 20230901 23:57:23- testStackSlots(j9vm.test.ddrext.junit.TestThread)
     [java] 20230901 23:57:23- Total Error/Failures: 1

BUILD FAILED
/bluebird/builds/bld_57365/jvmtest/VM/j9vm_SE60/tck_ddrext.xml:575: Java returned: 254
```

This seems a regression.
Pass build 
```
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pap6480sr9-20230615_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20230831_57303 (JIT enabled, AOT enabled)
OpenJ9   - bbd14f6
OMR      - a0097c7
IBM      - 696e9df)
JCL - 20230608_01 based on Oracle jdk8u381-b06
```
Failed build
```
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pap6480sr9-20230615_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20230901_57365 (JIT enabled, AOT enabled)
OpenJ9   - ea96716
OMR      - a0097c7
IBM      - 696e9df)
JCL - 20230608_01 based on Oracle jdk8u381-b06
```
[OpenJ9 build diff](https://github.ibm.com/runtimes/openj9/compare/bbd14f6261c4c9...ea967160602296)
Maybe [Add DDR command continuationstack](https://github.ibm.com/runtimes/openj9/commit/b212f192a9408bac5bfd858a7ff419c6990ff58f)?

**Comment by keithc-ca** [comment]
An internal copy of the test needs to be modified similarly to the change in #18014; an internal issue has been created.
