### ISSUE TITLE
aarch64_linux build test ant task failed with ArrayIndexOutOfBoundsException in some machines

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18082]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/29/console)(`cent7-aarch64-4`):
```
08:27:40  openjdk version "21-internal" 2023-09-19
08:27:40  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21aarch64linuxPersonal)
08:27:40  Eclipse OpenJ9 VM (build master-e57170e15e5, JRE 21 Linux aarch64-64-Bit Compressed References 20230903_60 (JIT enabled, AOT enabled)
08:27:40  OpenJ9   - e57170e15e5
08:27:40  OMR      - 75d233597f4
08:27:40  JCL      - fce06129139 based on jdk-21+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=special.jck&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F60%2FOpenJ9-JDK21-aarch64_linux-20230903-075318.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F60%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=e57170e15e5ecebe01090761972fcadc1d1db28b&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCK21-unzipped.git&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=jck&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
08:30:00  Caught an exception while logging the end of the build.  Exception was:
08:30:00  java.lang.ExceptionInInitializerError
08:30:00  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
08:30:00  	at org.apache.tools.ant.DefaultLogger.formatTime(DefaultLogger.java:304)
08:30:00  	at org.apache.tools.ant.DefaultLogger.buildFinished(DefaultLogger.java:175)
08:30:00  	at org.apache.tools.ant.Project.fireBuildFinished(Project.java:2089)
08:30:00  	at org.apache.tools.ant.Main.runBuild(Main.java:852)
08:30:00  	at org.apache.tools.ant.Main.startAnt(Main.java:223)
08:30:00  	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
08:30:00  	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
08:30:00  Caused by: java.lang.ArrayIndexOutOfBoundsException
08:30:00  	at java.base/sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453)
08:30:00  	at java.base/java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2369)
08:30:00  	at java.base/java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2787)
08:30:00  	at java.base/java.util.Calendar.updateTime(Calendar.java:3427)
08:30:00  	at java.base/java.util.Calendar.getTimeInMillis(Calendar.java:1814)
08:30:00  	at java.base/java.util.Calendar.getTime(Calendar.java:1785)
08:30:00  	at java.base/java.text.SimpleDateFormat.initializeDefaultCentury(SimpleDateFormat.java:905)
08:30:00  	at java.base/java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:670)
08:30:00  	at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:628)
08:30:00  	at org.apache.tools.ant.util.DateUtils.<clinit>(DateUtils.java:72)
08:30:00  	... 7 more
08:30:00  1
08:30:00  compile.mk:45: recipe for target 'compile' failed
```

Similar failure jobs: 
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/28/)(`rhel8-aarch64-2`)
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/27/)(`ub20-aarch64-4`)
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/26/)(`cent7-aarch64-6`)
[JDK17 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/34704/console)(`rhel8-aarch64-1`)

Pass jobs:
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/30/)(`sles15-aarch64-2`)
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/23/)(`ub22-aarch64-5`)
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/21/)(`rhel9-aarch64-1`)

The Ant version is Apache Ant(TM) version 1.10.5 compiled on July 10 2018.
Re-running the job in the same machine seems failed again, so this appears to a machine-related instead of an intermittent issue.

**Comment by pshipton** [comment]
We don't see this on the OpenJ9 machines. The latest build is https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK21_aarch64_linux/139/ and it's fine. 
Since this seems to be an internal machine problem, not sure why it's being tracked here.

**Comment by Akira1Saitoh** [comment]
I think this failure is the same problem as https://github.com/eclipse-openj9/openj9/issues/18057. This build does not include https://github.com/eclipse/omr/pull/7104.
> 08:27:40  OMR      - 75d233597f4

**Comment by JasonFengJ9** [comment]
Latest run [JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.jck_aarch64_linux_Personal/30/)(`sles15-aarch64-2`) did pass
```
20:18:53  openjdk version "21-internal" 2023-09-19
20:18:53  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21aarch64linuxPersonal)
20:18:53  Eclipse OpenJ9 VM (build master-d3388e1662d, JRE 21 Linux aarch64-64-Bit Compressed References 20230905_61 (JIT enabled, AOT enabled)
20:18:53  OpenJ9   - d3388e1662d
20:18:53  OMR      - 873ac5d377a
20:18:53  JCL      - 154f45ddce4 based on jdk-21+35)
```
Will see if it passes in previously failed machines.
