### ISSUE TITLE
JDK21 jdk_security_infra_1_FAILED security/infra/java/security/cert/CertPathValidator/certification/MicrosoftTLS.java CertPathValidatorException: Response is unreliable: its validity interval is out-of-date

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18092]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_mac_Personal/35/consoleFull)(`macaarch64rt8`):
```
04:39:34  openjdk version "21-internal" 2023-09-19
04:39:34  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21aarch64macPersonal)
04:39:34  Eclipse OpenJ9 VM (build master-7599bde8a13, JRE 21 Mac OS X aarch64-64-Bit 20230906_58 (JIT enabled, AOT enabled)
04:39:34  OpenJ9   - 7599bde8a13
04:39:34  OMR      - 873ac5d377a
04:39:34  JCL      - 154f45ddce4 based on jdk-21+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_nio_1,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_mac_Personal%2F58%2FOpenJ9-JDK21-aarch64_mac-20230906-222113.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_mac_Personal%2F58%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=7599bde8a134c25aee722cd5ec66023c91f99631&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
05:08:00  variation: Mode650
05:08:00  JVM_OPTIONS:  -XX:-UseCompressedOops 

05:08:14  TEST: security/infra/java/security/cert/CertPathValidator/certification/MicrosoftTLS.java

05:08:14  certpath: X509CertSelector.match: subject DNs don't match
05:08:14  java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
05:08:14  	at ValidatePathWithParams.validate(ValidatePathWithParams.java:177)
05:08:14  	at MicrosoftRSATLS.runTest(MicrosoftTLS.java:340)
05:08:14  	at MicrosoftTLS.main(MicrosoftTLS.java:58)
05:08:14  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
05:08:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
05:08:14  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
05:08:14  	at java.base/java.lang.Thread.run(Thread.java:1595)
05:08:14  Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
05:08:14  	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
05:08:14  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
05:08:14  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
05:08:14  	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
05:08:14  	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
05:08:14  	at ValidatePathWithParams.doCertPathValidate(ValidatePathWithParams.java:288)
05:08:14  	at ValidatePathWithParams.validate(ValidatePathWithParams.java:142)
05:08:14  	... 6 more
05:08:14  Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
05:08:14  	at java.base/sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:618)
05:08:14  	at java.base/sun.security.provider.certpath.OCSP.check(OCSP.java:141)
05:08:14  	at java.base/sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:780)
05:08:14  	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:369)
05:08:14  	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:343)
05:08:14  	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
05:08:14  	... 12 more
05:08:14  
05:08:14  JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status

05:08:14  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
05:08:14  --------------------------------------------------
05:08:21  Test results: passed: 13; failed: 1
05:08:28  Report written to /Users/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_mac_Personal/aqa-tests/TKG/output_16940760415813/jdk_security_infra_1/report/html/report.html
05:08:28  Results written to /Users/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_mac_Personal/aqa-tests/TKG/output_16940760415813/jdk_security_infra_1/work
05:08:28  Error: Some tests failed or other problems occurred.
05:08:28  -----------------------------------
05:08:28  jdk_security_infra_1_FAILED
```

**Comment by pshipton** [comment]
Is this intermittent, cross platform, does it fail on Hotspot?

**Comment by JasonFengJ9** [comment]
[JDK21 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_mac_Personal/27/consoleFull) also failed, it failed consistently at [a 6x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34758/console), RI failed [a 6x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34763/console) as well.

**Comment by pshipton** [comment]
You could exclude this test on Mac if you like.

**Comment by JasonFengJ9** [comment]
[JDK17 ppc64_aix 0.41 milestone 1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64_aix/131/)(`pll011`)
```
[2023-09-07T08:38:05.620Z] variation: Mode650
[2023-09-07T08:38:05.620Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-09-07T08:39:17.053Z] certpath: X509CertSelector.match: subject DNs don't match
[2023-09-07T08:39:17.053Z] java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
[2023-09-07T08:39:17.053Z] 	at ValidatePathWithParams.validate(ValidatePathWithParams.java:177)
[2023-09-07T08:39:17.053Z] 	at MicrosoftRSATLS.runTest(MicrosoftTLS.java:340)
[2023-09-07T08:39:17.053Z] 	at MicrosoftTLS.main(MicrosoftTLS.java:58)
[2023-09-07T08:39:17.053Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-09-07T08:39:17.053Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-09-07T08:39:17.053Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-09-07T08:39:17.053Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-09-07T08:39:17.053Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-09-07T08:39:17.053Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-09-07T08:39:17.053Z] Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
[2023-09-07T08:39:17.053Z] 	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
[2023-09-07T08:39:17.053Z] 	at ValidatePathWithParams.doCertPathValidate(ValidatePathWithParams.java:288)
[2023-09-07T08:39:17.053Z] 	at ValidatePathWithParams.validate(ValidatePathWithParams.java:142)
[2023-09-07T08:39:17.053Z] 	... 8 more
[2023-09-07T08:39:17.053Z] Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:617)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.OCSP.check(OCSP.java:199)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:785)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:369)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:343)
[2023-09-07T08:39:17.053Z] 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
[2023-09-07T08:39:17.053Z] 	... 14 more
[2023-09-07T08:39:17.053Z] 
[2023-09-07T08:39:17.054Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status

[2023-09-07T08:39:45.219Z] jdk_security_infra_1_FAILED
```

This is an across Java level/platform issue, a JCL extension update is required.
