### ISSUE TITLE
JTReg test failure com/sun/tools/attach/warnings/DynamicLoadWarningTest.java

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9#18125]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/3/

Failure output (captured from console output)
---------------------------------------------
```
[2023-09-12T00:29:35.577Z] [2023-09-12T00:29:33.861043861Z] Waiting for completion for process 2447361
[2023-09-12T00:29:35.577Z] [2023-09-12T00:29:33.861122617Z] Waiting for completion finished for process 2447361
[2023-09-12T00:29:35.577Z] STDERR:
[2023-09-12T00:29:35.577Z] STARTED    DynamicLoadWarningTest::testLoadJavaAgent 'testLoadJavaAgent()'
[2023-09-12T00:29:35.577Z] SUCCESSFUL DynamicLoadWarningTest::testLoadJavaAgent 'testLoadJavaAgent()'
[2023-09-12T00:29:35.577Z] STARTED    DynamicLoadWarningTest::testLoadOneJvmtiAgent '[1] DynamicLoadWarningTest$$Lambda/0x0000000000210c38@504e7665'
[2023-09-12T00:29:35.577Z] SUCCESSFUL DynamicLoadWarningTest::testLoadOneJvmtiAgent '[1] DynamicLoadWarningTest$$Lambda/0x0000000000210c38@504e7665'
[2023-09-12T00:29:35.577Z] STARTED    DynamicLoadWarningTest::testLoadOneJvmtiAgent '[2] DynamicLoadWarningTest$$Lambda/0x0000000000210e28@2f245b38'
[2023-09-12T00:29:35.577Z] SUCCESSFUL DynamicLoadWarningTest::testLoadOneJvmtiAgent '[2] DynamicLoadWarningTest$$Lambda/0x0000000000210e28@2f245b38'
[2023-09-12T00:29:35.577Z] STARTED    DynamicLoadWarningTest::testLoadTwoJvmtiAgents '[1] DynamicLoadWarningTest$$Lambda/0x0000000000210c38@504e7665'
[2023-09-12T00:29:35.577Z] SUCCESSFUL DynamicLoadWarningTest::testLoadTwoJvmtiAgents '[1] DynamicLoadWarningTest$$Lambda/0x0000000000210c38@504e7665'
[2023-09-12T00:29:35.577Z] STARTED    DynamicLoadWarningTest::testLoadTwoJvmtiAgents '[2] DynamicLoadWarningTest$$Lambda/0x0000000000210e28@631a725f'
[2023-09-12T00:29:35.577Z] com.sun.tools.attach.AttachNotSupportedException: target 2447361 not found
[2023-09-12T00:29:35.577Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTargetImpl(OpenJ9VirtualMachine.java:151)
[2023-09-12T00:29:35.577Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.lambda$attachTarget$1(OpenJ9VirtualMachine.java:129)
[2023-09-12T00:29:35.577Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
[2023-09-12T00:29:35.577Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTarget(OpenJ9VirtualMachine.java:131)
[2023-09-12T00:29:35.577Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:65)
[2023-09-12T00:29:35.577Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:47)
[2023-09-12T00:29:35.577Z] 	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
[2023-09-12T00:29:35.577Z] 	at DynamicLoadWarningTest$AppRunner.lambda$run$0(DynamicLoadWarningTest.java:256)
[2023-09-12T00:29:35.577Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-09-12T00:29:35.577Z] org.opentest4j.AssertionFailedError: Attach or action failed, see log for details ==> expected: <true> but was: <false>
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:211)
[2023-09-12T00:29:35.577Z] 	at DynamicLoadWarningTest$AppRunner.run(DynamicLoadWarningTest.java:282)
[2023-09-12T00:29:35.577Z] 	at DynamicLoadWarningTest$AppRunner.stderrShouldContain(DynamicLoadWarningTest.java:299)
[2023-09-12T00:29:35.577Z] 	at DynamicLoadWarningTest.testLoadTwoJvmtiAgents(DynamicLoadWarningTest.java:158)
[2023-09-12T00:29:35.577Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-09-12T00:29:35.577Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-09-12T00:29:35.577Z] 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
[2023-09-12T00:29:35.577Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
[2023-09-12T00:29:35.578Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.578Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
[2023-09-12T00:29:35.578Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
[2023-09-12T00:29:35.578Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
[2023-09-12T00:29:35.578Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
[2023-09-12T00:29:35.578Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:142)
[2023-09-12T00:29:35.578Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:110)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[2023-09-12T00:29:35.578Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[2023-09-12T00:29:35.579Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:110)
[2023-09-12T00:29:35.579Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:44)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2023-09-12T00:29:35.579Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
[2023-09-12T00:29:35.579Z] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
[2023-09-12T00:29:35.579Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:142)
[2023-09-12T00:29:35.579Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
[2023-09-12T00:29:35.579Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
[2023-09-12T00:29:35.579Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-09-12T00:29:35.580Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-09-12T00:29:35.580Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-09-12T00:29:35.580Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-09-12T00:29:35.580Z] FAILED     DynamicLoadWarningTest::testLoadTwoJvmtiAgents '[2] DynamicLoadWarningTest$$Lambda/0x0000000000210e28@631a725f'
```

**Comment by babsingh** [comment]
This seems related to

- https://github.com/eclipse-openj9/openj9/issues/17500

fyi @JasonFengJ9 @tajila @pshipton

**Comment by JasonFengJ9** [comment]
@babsingh The sub-test in question was [dynamically load loadJvmtiAgent1, then dynamically load loadJvmtiAgent2 with jcmd](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/528922c10d7a5f85c061bbd6b945d6412e933283/test/jdk/com/sun/tools/attach/warnings/DynamicLoadWarningTest.java#L155C1-L158)
`[2023-09-12T00:29:35.577Z] com.sun.tools.attach.AttachNotSupportedException: target 2447361 not found`
This seems the target VM instance `2447361` exits before the attached VM attaches it via `jcmd`.
I think the testcase needs to change for consistency. 

Launched a 50x grinder to find out the failure rate - https://openj9-jenkins.osuosl.org/job/Grinder/2885/

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this

**Comment by JasonFengJ9** [comment]
Overview of this test case:
* The [main testcase](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/528922c10d7a5f85c061bbd6b945d6412e933283/test/jdk/com/sun/tools/attach/warnings/DynamicLoadWarningTest.java#L219) runs on its own VM (as attaching VM), starts a thread with a listener socket;
* A target VM [Application](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/528922c10d7a5f85c061bbd6b945d6412e933283/test/jdk/com/sun/tools/attach/warnings/DynamicLoadWarningTest.java#L275C48-L278) is launched with a listener socket port number by current VM;
* The target VM sents its `pid` back to the attaching VM which is used for AttachAPI `vmid`, afterwards it blocks on the socket `read()`, exits if it receives data (`0`) as expected, or anything else unblocking `read()`; 
* The attaching VM issues `VirtualMachine.attach(vmid)` or launches `jcmd` with `vmid` to attach into the target VM, and perform certain actions;
* After the attaching actions are finished successfully, the attaching VM `write(0)` to the target VM via the socket which shutdown the `Application`, and the test checks the process output for failure analysis.

The failure in question occurred when the attaching VM throws `AttachNotSupportedException: target vmid not found` with the `vmid` returned by the target VM. Put a log into the `DynamicLoadWarningTest.java`, and it shows the target VM exits prematurely due to `s.getInputStream().read()` returns `-1`.

This is an intermittent failure and appears the internal grinder has a much lower reproducibility rate than the open ones. I am leaning toward a machine/network issue, next action is to improve the testcase to avoid the target VM premature shutdown.

Removing `vm` component tag, added `test` instead.
