### ISSUE TITLE
OpenJDK java/lang/reflect/IllegalArgumentsTest.java

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18147]
https://openj9-jenkins.osuosl.org/job/Grinder_iteration_0/365
sanity.openjdk
using https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK21_aarch64_linux_Nightly/56/OpenJ9-JDK21-aarch64_linux-20230906-210711.tar.gz
failed 1/50

jdk_lang_1
java/lang/reflect/IllegalArgumentsTest.java
```
12:08:15  test IllegalArgumentsTest.wrongArgumentType(): failure
12:08:15  java.lang.reflect.InvocationTargetException
12:08:15  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
12:08:15  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
12:08:15  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
12:08:15  	at IllegalArgumentsTest.wrongArgumentType(IllegalArgumentsTest.java:49)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/64
java/lang/reflect/IllegalArgumentsTest.java
```
17:51:11  test IllegalArgumentsTest.nullArguments(): failure
17:51:11  java.lang.reflect.InvocationTargetException
17:51:11  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
17:51:11  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
17:51:11  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
17:51:11  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)
17:51:11  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:51:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
17:51:11  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
17:51:11  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
17:51:11  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
17:51:11  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
17:51:11  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
17:51:11  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
17:51:11  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
17:51:11  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
17:51:11  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
17:51:11  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
17:51:11  	at org.testng.TestRunner.run(TestRunner.java:585)
17:51:11  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
17:51:11  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
17:51:11  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
17:51:11  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
17:51:11  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
17:51:11  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
17:51:11  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
17:51:11  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
17:51:11  	at org.testng.TestNG.runSuites(TestNG.java:1069)
17:51:11  	at org.testng.TestNG.run(TestNG.java:1037)
17:51:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
17:51:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
17:51:11  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:51:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
17:51:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
17:51:11  	at java.base/java.lang.Thread.run(Thread.java:1595)
17:51:11  Caused by: java.lang.NullPointerException
17:51:11  	at <unknown class>.<unknown method>(Unknown Source)
17:51:11  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
17:51:11  	... 32 more
```

**Comment by hzongaro** [comment]
Nazim @nbhuiyan, may I ask you to triage this issue?

**Comment by nbhuiyan** [comment]
100X + 100X Grinder running ` java/lang/reflect/IllegalArgumentsTest.java` passed: [aarch64](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35298/), [x86-64](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35299/)

**Comment by pshipton** [comment]
If this can't be reproduced it can move out.

**Comment by JasonFengJ9** [comment]
[JDK21 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_testList_1/134/)(`sles15x86-rtp-rt7-1`)
```
openjdk version "21.0.3" 2024-04-16 LTS
IBM Semeru Runtime Open Edition 21.0.3.0-m3 (build 21.0.3+7-LTS)
Eclipse OpenJ9 VM 21.0.3.0-m3 (build v0.44.0-release-e14f0f01c, JRE 21 Linux amd64-64-Bit Compressed References 20240416_133 (JIT enabled, AOT enabled)
OpenJ9   - e14f0f01c
OMR      - 254af5a04
JCL      - d85f56ae366 based on jdk-21.0.3+7)

[2024-03-25T21:19:22.466Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2024-03-25T21:19:22.466Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-25T21:29:21.998Z] TEST: java/lang/reflect/IllegalArgumentsTest.java

[2024-03-25T21:29:21.998Z] STDOUT:
[2024-03-25T21:29:21.998Z] test IllegalArgumentsTest.illegalArguments(): success
[2024-03-25T21:29:21.998Z] test IllegalArgumentsTest.nullArguments(): failure
[2024-03-25T21:29:21.998Z] java.lang.reflect.InvocationTargetException
[2024-03-25T21:29:21.998Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
[2024-03-25T21:29:21.998Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-25T21:29:21.998Z] 	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:76)
[2024-03-25T21:29:21.998Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-25T21:29:21.998Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-25T21:29:21.998Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2024-03-25T21:29:21.998Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2024-03-25T21:29:21.998Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2024-03-25T21:29:21.998Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2024-03-25T21:29:21.998Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2024-03-25T21:29:21.999Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2024-03-25T21:29:21.999Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2024-03-25T21:29:21.999Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2024-03-25T21:29:21.999Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[2024-03-25T21:29:21.999Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2024-03-25T21:29:21.999Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2024-03-25T21:29:21.999Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2024-03-25T21:29:21.999Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2024-03-25T21:29:21.999Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2024-03-25T21:29:21.999Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2024-03-25T21:29:21.999Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2024-03-25T21:29:21.999Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2024-03-25T21:29:21.999Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2024-03-25T21:29:21.999Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2024-03-25T21:29:21.999Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2024-03-25T21:29:21.999Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2024-03-25T21:29:21.999Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
[2024-03-25T21:29:21.999Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
[2024-03-25T21:29:21.999Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-25T21:29:21.999Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-25T21:29:21.999Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-03-25T21:29:21.999Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-03-25T21:29:21.999Z] Caused by: java.lang.NullPointerException
[2024-03-25T21:29:21.999Z] 	at <unknown class>.<unknown method>(Unknown Source)
[2024-03-25T21:29:21.999Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-25T21:29:21.999Z] 	... 31 more

[2024-03-25T21:36:51.480Z] Test results: passed: 934; failed: 1
[2024-03-25T21:36:55.803Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_17114015614048/jdk_lang_1/report/html/report.html
[2024-03-25T21:36:55.803Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_17114015614048/jdk_lang_1/work
[2024-03-25T21:36:55.803Z] Error: Some tests failed or other problems occurred.
[2024-03-25T21:36:55.803Z] -----------------------------------
[2024-03-25T21:36:55.803Z] jdk_lang_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39254/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/130
jdk_lang_1
java/lang/reflect/IllegalArgumentsTest.java
```
08:20:59  test IllegalArgumentsTest.nullArguments(): failure
08:20:59  java.lang.reflect.InvocationTargetException
08:20:59  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
08:20:59  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
08:20:59  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
08:20:59  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)
08:20:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
08:20:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
08:20:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
08:20:59  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
08:20:59  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
08:20:59  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
08:20:59  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
08:20:59  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
08:20:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
08:20:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
08:20:59  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
08:20:59  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
08:20:59  	at org.testng.TestRunner.run(TestRunner.java:585)
08:20:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
08:20:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
08:20:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
08:20:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
08:20:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
08:20:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
08:20:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
08:20:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
08:20:59  	at org.testng.TestNG.runSuites(TestNG.java:1069)
08:20:59  	at org.testng.TestNG.run(TestNG.java:1037)
08:20:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
08:20:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
08:20:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
08:20:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
08:20:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
08:20:59  	at java.base/java.lang.Thread.run(Thread.java:1595)
08:20:59  Caused by: java.lang.NullPointerException
08:20:59  	at <unknown class>.<unknown method>(Unknown Source)
08:20:59  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
08:20:59  	... 32 more
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.openjdk_x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.openjdk_x86-64_mac_testList_0/4/)
```
[2025-08-26T02:59:24.633Z] Running test jdk_lang_j9_0 ...
[2025-08-26T02:59:24.633Z] ===============================================
[2025-08-26T02:59:24.633Z] jdk_lang_j9_0 Start Time: Mon Aug 25 22:59:23 2025 Epoch Time (ms): 1756177163743
[2025-08-26T02:59:24.633Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
[2025-08-26T02:59:24.633Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -Xverbosegclog 

[2025-08-26T03:05:47.708Z] TEST: java/lang/reflect/IllegalArgumentsTest.java

[2025-08-26T03:05:47.709Z] test IllegalArgumentsTest.nullArguments(): failure [999ms]
[2025-08-26T03:05:47.709Z] java.lang.reflect.InvocationTargetException
[2025-08-26T03:05:47.709Z] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
[2025-08-26T03:05:47.709Z] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2025-08-26T03:05:47.709Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[2025-08-26T03:05:47.709Z] 	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)
[2025-08-26T03:05:47.709Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-08-26T03:05:47.709Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2025-08-26T03:05:47.709Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2025-08-26T03:05:47.709Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
[2025-08-26T03:05:47.709Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2025-08-26T03:05:47.709Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2025-08-26T03:05:47.709Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2025-08-26T03:05:47.709Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2025-08-26T03:05:47.709Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2025-08-26T03:05:47.709Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2025-08-26T03:05:47.709Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2025-08-26T03:05:47.709Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2025-08-26T03:05:47.709Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2025-08-26T03:05:47.709Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2025-08-26T03:05:47.709Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2025-08-26T03:05:47.709Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2025-08-26T03:05:47.709Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:107)
[2025-08-26T03:05:47.709Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:63)
[2025-08-26T03:05:47.709Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-08-26T03:05:47.709Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-08-26T03:05:47.709Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2025-08-26T03:05:47.709Z] 	at java.base/java.lang.Thread.run(Thread.java:1485)
[2025-08-26T03:05:47.709Z] Caused by: java.lang.NullPointerException
[2025-08-26T03:05:47.709Z] 	at <unknown class>.<unknown method>(Unknown Source)
[2025-08-26T03:05:47.709Z] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[2025-08-26T03:05:47.709Z] 	... 32 more
[2025-08-26T03:05:47.709Z] test IllegalArgumentsTest.wrongArgumentType(): success [18401ms]
[2025-08-26T03:05:47.709Z] test IllegalArgumentsTest.wrongReceiver(): success [1008ms]
[2025-08-26T03:05:47.709Z] 
[2025-08-26T03:05:47.709Z] ===============================================
[2025-08-26T03:05:47.709Z] java/lang/reflect/IllegalArgumentsTest.java
[2025-08-26T03:05:47.709Z] Total tests run: 4, Passes: 3, Failures: 1, Skips: 0
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/435/
jdk_lang_1
java/lang/reflect/IllegalArgumentsTest.java
```
07:31:32  test IllegalArgumentsTest.wrongArgumentType(): failure [124ms]
07:31:32  java.lang.reflect.InvocationTargetException
07:31:32  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
07:31:32  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
07:31:32  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
07:31:32  	at IllegalArgumentsTest.wrongArgumentType(IllegalArgumentsTest.java:49)

07:31:32  Caused by: java.lang.ClassCastException: java.lang.Class incompatible with java.lang.Number
07:31:32  	at java.base/sun.invoke.util.ValueConversions.primitiveConversion(ValueConversions.java:247)
07:31:32  	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
07:31:32  	at <unknown class>.<unknown method>(Unknown Source)
07:31:32  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
07:31:32  	... 32 more

```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/676
```
18:14:20  Caused by: java.lang.NullPointerException
18:14:20  	at <unknown class>.<unknown method>(Unknown Source)
18:14:20  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
18:14:20  	... 32 more
```
