### ISSUE TITLE
VirtualThread states changed in jdk22

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#18183]
Failure links
------------

The values were changed in https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ceb174ba8004f6361a307f6d599d786eef9307c7.

* https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_Personal_testList_0/40/consoleText
* https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_Personal_testList_1/40/consoleText

Failure output (captured from console output)
---------------------------------------------

```
[2023-09-22T05:48:47.201Z] FAILED: test_verifyJVMTIMacros
[2023-09-22T05:48:47.201Z] java.lang.AssertionError: JVMTI_VTHREAD_STATE_YIELDING (7) does not match VirtualThread.YIELDING (10)
[2023-09-22T05:48:47.201Z] 	at org.testng.Assert.fail(Assert.java:96)
[2023-09-22T05:48:47.201Z] 	at org.openj9.test.jep425.VirtualThreadTests.test_verifyJVMTIMacros(VirtualThreadTests.java:321)
[2023-09-22T05:48:47.201Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-09-22T05:48:47.201Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by babsingh** [comment]
Fixed via https://github.com/eclipse-openj9/openj9/pull/18421.
