### ISSUE TITLE
OpenJDK java/math/BigInteger/LargeValueExceptions timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18190]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Personal_testList_0/1) OMR acceptance
java/math/BigInteger/LargeValueExceptions.java
```
12:25:42  "MainThread" Id=32 RUNNABLE
12:25:42  	at java.math.BigInteger.exactDivideBy3(BigInteger.java:1895)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1808)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1794)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1797)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1797)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1800)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1800)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1800)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1794)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1794)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1800)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1591)
12:25:42  	at java.math.BigInteger.multiply(BigInteger.java:1495)
12:25:42  	at LargeValueExceptions.multiplyDefiniteOverflow(LargeValueExceptions.java:151)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/320
jdk_math_0
java/math/BigInteger/LargeValueExceptions.java
```
20:01:52  command: testng -Xmx4g LargeValueExceptions
20:01:52  reason: User specified action: run testng/othervm -Xmx4g LargeValueExceptions 
20:01:52  started: Mon Sep 30 23:36:47 UTC 2024
20:01:52  Mode: othervm [/othervm specified]
20:01:52  Timeout information:
20:01:52  Running jcmd on process 3744015
20:01:52  Timeout signalled after 300 seconds
20:01:52  Dump written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/aqa-tests/TKG/output_17277357176376/jdk_math_0/work/scratch/2/core.20240930.235252.3744015.0001.dmp
20:01:52  Timeout handler interrupted: 
20:01:52  java.lang.InterruptedException
20:01:52  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1696)
20:01:52  	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:425)
20:01:52  	at jtreg.openj9.CoreDumpTimeoutHandler.runJcmdCommand(CoreDumpTimeoutHandler.java:117)
20:01:52  	at jtreg.openj9.CoreDumpTimeoutHandler.runJcmd(CoreDumpTimeoutHandler.java:137)
20:01:52  	at jtreg.openj9.CoreDumpTimeoutHandler.runActions(CoreDumpTimeoutHandler.java:55)
20:01:52  	at com.sun.javatest.regtest.TimeoutHandler.handleTimeout(TimeoutHandler.java:132)
20:01:52  	at com.sun.javatest.regtest.exec.ProcessCommand$2.run(ProcessCommand.java:317)
20:01:52  --- Timeout information end.
```

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_sanity.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/1233/)
```
[2026-03-28T11:30:30.489Z] Running test jdk_math_1 ...
[2026-03-28T11:30:30.489Z] ===============================================
[2026-03-28T11:30:30.489Z] jdk_math_1 Start Time: Sat Mar 28 07:30:27 2026 Epoch Time (ms): 1774697427741
[2026-03-28T11:30:30.490Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650

[2026-03-28T11:48:31.322Z] TEST: java/math/BigInteger/LargeValueExceptions.java

[2026-03-28T11:48:31.324Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1029992ms).
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.openjdk_ppc64_aix_testList_4/142/)
```
[2026-04-12T05:53:51.347Z] Running test jdk_math_1 ...
[2026-04-12T05:53:51.347Z] ===============================================
[2026-04-12T05:53:51.347Z] jdk_math_1 Start Time: Sun Apr 12 01:53:50 2026 Epoch Time (ms): 1775973230876
[2026-04-12T05:53:51.347Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2026-04-12T05:53:51.347Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2026-04-12T06:13:01.271Z] TEST: java/math/BigInteger/LargeValueExceptions.java

[2026-04-12T06:13:01.273Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk25_j9_sanity.openjdk_ppc64_aix_testList_4/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1004986ms).
```

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_sanity.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/1298/)
```
[2026-06-22T18:45:43.906Z] Running test jdk_math_0 ...
[2026-06-22T18:45:43.906Z] ===============================================
[2026-06-22T18:45:43.907Z] jdk_math_0 Start Time: Mon Jun 22 14:45:42 2026 Epoch Time (ms): 1782153942754
[2026-06-22T18:45:43.907Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2026-06-22T18:45:43.907Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2026-06-22T19:04:02.535Z] TEST: java/math/BigInteger/LargeValueExceptions.java

[2026-06-22T19:04:02.556Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1047003ms).
[2026-06-22T19:04:02.556Z] --------------------------------------------------
[2026-06-22T19:04:21.519Z] Test results: passed: 38; error: 1
```
