### ISSUE TITLE
JDK21 jdk_rmi_0_FAILED java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java TEST FAILED: remote object garbage collected

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18198]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_s390x_linux/4/)(`ubu20hwes390x-svl-rt2-1`):
```
openjdk version "21" 2023-09-19 LTS
IBM Semeru Runtime Open Edition 21.0.0.0-m0 (build 21+35-LTS)
Eclipse OpenJ9 VM 21.0.0.0-m0 (build master-5756d9048, JRE 21 Linux s390x-64-Bit Compressed References 20230919_44 (JIT enabled, AOT enabled)
OpenJ9   - 5756d9048
OMR      - 1b52192f5
JCL      - 0738d48b5de based on jdk-21+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_rmi_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21%2Fjdk21-linux-s390x-openj9%2F44%2Fibm-semeru-open-jdk_s390x_linux_21_35_openj9-0.42.0-m0.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21%2Fjdk21-linux-s390x-openj9%2F44%2Fibm-semeru-open-testimage_s390x_linux_21_35_openj9-0.42.0-m0.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.42.0-release&amp;OPENJ9_BRANCH=v0.42.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.42.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-09-23T00:04:55.844Z] variation: Mode150
[2023-09-23T00:04:55.844Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-09-23T00:05:23.603Z] TEST: java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java

[2023-09-23T00:05:23.605Z] java.lang.RuntimeException: TEST FAILED: remote object garbage collected
[2023-09-23T00:05:23.605Z] 	at DGCImplInsulation.main(DGCImplInsulation.java:87)
[2023-09-23T00:05:23.605Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-09-23T00:05:23.605Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-09-23T00:05:23.605Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-09-23T00:05:23.605Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)

[2023-09-23T00:05:23.605Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: TEST FAILED: remote object garbage collected
[2023-09-23T00:05:23.605Z] --------------------------------------------------
[2023-09-23T00:10:22.246Z] Test results: passed: 88; failed: 1
[2023-09-23T00:10:32.373Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16954106729841/jdk_rmi_0/report/html/report.html
[2023-09-23T00:10:32.373Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16954106729841/jdk_rmi_0/work
[2023-09-23T00:10:32.373Z] Error: Some tests failed or other problems occurred.
[2023-09-23T00:10:32.373Z] -----------------------------------
[2023-09-23T00:10:32.373Z] jdk_rmi_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35135/)

**Comment by JasonFengJ9** [comment]
[JDK8 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_s390x_linux_testList_1/38/)(`rhel9s390x-svl-rt9-1`)
```
[2024-05-04T04:44:20.049Z] variation: Mode150
[2024-05-04T04:44:20.049Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-05-04T04:46:06.077Z] TEST: java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java

[2024-05-04T04:46:06.077Z] STDERR:
[2024-05-04T04:46:06.077Z] exported remote object; local stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[10.11.61.72:41287](local),objID:[477d3ea5:18f41ec598b:-7fff, 1115181711354182337]]]]
[2024-05-04T04:46:06.077Z] marshalled/unmarshalled stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[10.11.61.72:41287](remote),objID:[477d3ea5:18f41ec598b:-7fff, 1115181711354182337]]]]
[2024-05-04T04:46:06.077Z] java.lang.RuntimeException: TEST FAILED: remote object garbage collected
[2024-05-04T04:46:06.077Z] 	at DGCImplInsulation.main(DGCImplInsulation.java:83)
[2024-05-04T04:46:06.077Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-04T04:46:06.077Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-05-04T04:46:06.077Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-04T04:46:06.077Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-05-04T04:46:06.077Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-05-04T04:46:06.077Z] 	at java.lang.Thread.run(Thread.java:826)
[2024-05-04T04:46:06.077Z] 
[2024-05-04T04:46:06.077Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: remote object garbage collected

[2024-05-04T04:50:51.158Z] jdk_rmi_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40377/)

**Comment by JasonFengJ9** [comment]
[JDK22 s390x_linux_fips140_2](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_s390x_linux_fips140_2_testList_1/12/)(`rhel8s390x-svl-rtfips12-1`)
```
[2024-05-15T04:46:03.805Z] variation: Mode650
[2024-05-15T04:46:03.805Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true

[2024-05-15T04:49:00.282Z] TEST: java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java

[2024-05-15T04:49:00.284Z] STDERR:

[2024-05-15T04:49:00.284Z] exported remote object; local stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[10.11.27.45:36985](local),objID:[-732d94ad:18f7a92ca6d:-7fff, -6413671369654422110]]]]
[2024-05-15T04:49:00.284Z] marshalled/unmarshalled stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[10.11.27.45:36985](remote),objID:[-732d94ad:18f7a92ca6d:-7fff, -6413671369654422110]]]]
[2024-05-15T04:49:00.284Z] java.lang.RuntimeException: TEST FAILED: remote object garbage collected
[2024-05-15T04:49:00.284Z] 	at DGCImplInsulation.main(DGCImplInsulation.java:87)
[2024-05-15T04:49:00.284Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-05-15T04:49:00.284Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-05-15T04:49:00.284Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-05-15T04:49:00.284Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-05-15T04:49:00.284Z] 
[2024-05-15T04:49:00.284Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: remote object garbage collected
```

**Comment by JasonFengJ9** [comment]
[Test_openjdk11_j9_extended.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_s390x_linux/325/) (`rhel8s390x-svl-rt10-1`)
```
[2024-10-05T09:19:04.048Z] Running test jdk_rmi_0 ...
[2024-10-05T09:19:04.048Z] ===============================================
[2024-10-05T09:19:04.048Z] jdk_rmi_0 Start Time: Sat Oct  5 02:19:03 2024 Epoch Time (ms): 1728119943993
[2024-10-05T09:19:04.508Z] variation: Mode150
[2024-10-05T09:19:04.508Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-10-05T09:25:53.956Z] TEST: java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java

[2024-10-05T09:25:53.965Z] STDERR:
[2024-10-05T09:25:53.965Z] exported remote object; local stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[10.11.39.50:36157](local),objID:[-1f7076dd:1925bffe4aa:-7fff, 1673399130429566824]]]]
[2024-10-05T09:25:53.966Z] marshalled/unmarshalled stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[10.11.39.50:36157](remote),objID:[-1f7076dd:1925bffe4aa:-7fff, 1673399130429566824]]]]
[2024-10-05T09:25:53.966Z] java.lang.RuntimeException: TEST FAILED: remote object garbage collected
[2024-10-05T09:25:53.966Z] 	at DGCImplInsulation.main(DGCImplInsulation.java:87)
[2024-10-05T09:25:53.966Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-10-05T09:25:53.966Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-10-05T09:25:53.966Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-10-05T09:25:53.966Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-10-05T09:25:53.966Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-10-05T09:25:53.966Z] 	at java.base/java.lang.Thread.run(Thread.java:839)

[2024-10-05T09:32:23.657Z] jdk_rmi_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_extended.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_4/55/)
```
[2025-05-01T12:54:23.638Z] variation: Mode150
[2025-05-01T12:54:23.638Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-05-01T12:55:28.335Z] TEST: java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java

[2025-05-01T12:55:28.350Z] exported remote object; local stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[9.30.188.33:50458](local),objID:[-eba552e:1968bea454b:-7fff, 7319623599160556951]]]]
[2025-05-01T12:55:28.350Z] marshalled/unmarshalled stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[9.30.188.33:50458](remote),objID:[-eba552e:1968bea454b:-7fff, 7319623599160556951]]]]
[2025-05-01T12:55:28.350Z] java.lang.RuntimeException: TEST FAILED: remote object garbage collected
[2025-05-01T12:55:28.350Z] 	at DGCImplInsulation.main(DGCImplInsulation.java:87)

[2025-05-01T13:18:49.399Z] jdk_rmi_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_extended.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows_testList_2/317/)
```
[2025-09-18T18:06:40.182Z] Running test jdk_rmi_0 ...
[2025-09-18T18:06:41.098Z] ===============================================
[2025-09-18T18:06:41.541Z] jdk_rmi_0 Start Time: Thu Sep 18 11:06:41 2025 Epoch Time (ms): 1758218801586
[2025-09-18T18:06:42.463Z] variation: Mode150
[2025-09-18T18:06:42.902Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-09-18T18:11:31.874Z] TEST: java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java

[2025-09-18T18:11:31.880Z] STDERR:
[2025-09-18T18:11:31.880Z] exported remote object; local stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[9.30.18.110:54846](local),objID:[75574712:1995e05f3f3:-7fff, -76663745055942406]]]]
[2025-09-18T18:11:31.881Z] marshalled/unmarshalled stub: DGCImplInsulation_Stub[UnicastRef [liveRef: [endpoint:[9.30.18.110:54846](remote),objID:[75574712:1995e05f3f3:-7fff, -76663745055942406]]]]
[2025-09-18T18:11:31.881Z] java.lang.RuntimeException: TEST FAILED: remote object garbage collected
[2025-09-18T18:11:31.881Z] 	at DGCImplInsulation.main(DGCImplInsulation.java:83)
```
