### ISSUE TITLE
[JDK11 OJDK-MH] Errors related to java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments

### ISSUE THREAD

**Issue by ThanHenderson** [eclipse-openj9/openj9#18245]
The below failure(s) is(are) only seen when OJDK MHs are enabled in OpenJ9.

### Errors
Test: ```java/lang/invoke/7196190/GetUnsafeTest.java```
```
Failed at GetUnsafeTest.java:88
Failed at GetUnsafeTest.java:89
```
---
Test: ```java/lang/invoke/7196190/ClassForNameTest.java```

```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments(MethodHandleImpl.java:584)
        at ClassForNameTest.main(ClassForNameTest.java:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: java.lang.ClassNotFoundException: ClassForNameTest
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:347)
        ... 13 more
```
___
### How to Run Tests?
```$BUILD_DIR/images/jdk/bin/java -jar $PROJ_ROOT/jtreg/lib/jtreg.jar -va -jdk:$BUILD_DIR/images/jdk <test-path>```

### Steps to build an OpenJ9 JDK11 with OJDK MHs enabled
Refer to #14540

**Comment by ThanHenderson** [comment]
Closed by: #18285
