### ISSUE TITLE
[linux_390] SE80_GIT JLM_Tests_interface_SE80_0 TestMemoryPoolMXBean failed testGetPeakUsage/testGetUsage

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18249]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=69454359)(`rhel7s390x-2-2`):
```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pxz3180sr9-20230901_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux s390-31-Bit 20231006_58790 (JIT enabled, AOT enabled)
OpenJ9   - 1300533
OMR      - 0a46a2a
IBM      - 970f576)
JCL - 20230829_01 based on Oracle jdk8u391-b07
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
FAILED: testGetPeakUsage
java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at org.openj9.test.java.lang.management.TestMemoryPoolMXBean.testGetPeakUsage(TestMemoryPoolMXBean.java:891)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: testGetUsage
java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at org.openj9.test.java.lang.management.TestMemoryPoolMXBean.testGetUsage(TestMemoryPoolMXBean.java:925)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    TestMemoryPoolMXBean
    Tests run: 24, Failures: 2, Skips: 0
===============================================


===============================================
JLM_Tests_Suite
Total tests run: 169, Failures: 2, Skips: 0
===============================================
```

[100x internal grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=58794) - 9/100 failed

**Comment by pshipton** [comment]
Failing on z/OS too http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=69474533

**Comment by pshipton** [comment]
I think we can assume all 32-bit.
xlinux http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=69481694
win http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=69484879

**Comment by mpirvu** [comment]
Allocating a code cache involves the separate tasks:
1. Allocating a segment for the code cache
2. Allocating a TR::CodeCache data structure

The TR::CodeCache includes a pointer to the backing segment.
The segment includes a pointer to the corresponding TR::CodeCache data structure as the very first entry.

When the VM wants to compute code cache occupancy, it will retrieve the TR::CodeCache pointer and from the TR::CodeCache data structure it will read the very first two entries which are `warmCodeAlloc` and `coldColdAlloc`. The difference between these two pointers represents the free space in the code cache.

The two tasks mentioned above are not part of the same critical section. Thus, it is possible for a third party to try to retrieve code cache stats after the segment has been allocated, but before the TR::CodeCache data structure has been allocated (or before the pointer to the TR::CodeCache has been written to the beginning of the segment).
In this case, before https://github.com/eclipse-openj9/openj9/pull/18212, the VM would read a bogus TR::CodeCache pointer and then fetch bogus `warmCodeAlloc` and `coldCodeAlloc` pointers. This can also lead to crashes if the bogus TR::CodeCache pointer cannot be dereferenced (this was reported by a customer).
After https://github.com/eclipse-openj9/openj9/pull/18212, the VM will write a NULL TR::CodeCache pointer at the beginning of the code cache segment until the address of the TR::CodeCache is known. After seeing the NULL value, the code in the test reports a zero code cache utilization tripping the assert.

This problem can only happen only if code cache consolidation is not used. When code cache consolidation is used, the JIT allocates a single code cache segment during bootstrap (the code cache repository) and then carves 2MB code caches as needed. Because this segment is allocated during bootstrap when no Java code runs, the race condition described above cannot happen.
Code cache consolidation is not used on 32-bit platforms or on Z when RMODE64 is not used. This is why these platforms see the test failure.

All in all, after https://github.com/eclipse-openj9/openj9/pull/18212, the assumption that if we have a code cache segment, there must be some used portion, no longer holds true (it wasn't true even before, but we were reading bad occupancy data).

**Comment by pshipton** [comment]
If there are multiple code caches, shouldn't the used parts be added up, resulting in a non-zero size? Do we actually have zero code cache used in the middle of a test? The used size shouldn't be reported as zero due to a timing problem.

**Comment by mpirvu** [comment]
> If there are multiple code caches, shouldn't the used parts be added up, resulting in a non-zero size?

Yes, that is correct, unless this is the very first code cache. I will try to reproduce this locally with some added diagnostics.

> The used size shouldn't be reported as zero due to a timing problem.

If we report the size just before any space in the code cache has been allocated, then reporting 0 is the right thing to do.

I am thinking at the following possible fix:
- When allocating a code cache segment and writing the NULL TR::CodeCache pointer at the beginning of the segment, bump `segment->heapAlloc` to reflect the extra space consumed.
- When Java code reads the occupancy of the code cache, if the TR::CodeCache pointer is NULL, compute the free space as (heapTop - heapAlloc) rather than (heapTop - heapBase). Otherwise, compute the free based on the information in TR::CodeCache

**Comment by mpirvu** [comment]
In `OMR::CodeCache::initialize() there is an early return when trampolines are not used (mainly on 32-bit):
```
   if (!config.trampolineCodeSize())
      {
      // _helperTop is heapTop
      _trampolineBase = _helperTop;
      _helperBase = _helperTop;
      _trampolineReservationMark = _trampolineAllocationMark = _trampolineBase;

      // set the pre loaded per Cache Helper slab
      _CCPreLoadedCodeTop = (uint8_t *)(((size_t)_trampolineBase) & (~config.codeCacheHelperAlignmentMask()));
      _CCPreLoadedCodeBase = _CCPreLoadedCodeTop - config.ccPreLoadedCodeSize();
      TR_ASSERT( (((size_t)_CCPreLoadedCodeBase) & config.codeCacheHelperAlignmentMask()) == 0, "Per-code cache helper sizes do not account for alignment requirements." );
      _coldCodeAlloc = _CCPreLoadedCodeBase;
      _trampolineSyncList = NULL;
      return true;
      }
```
If this return is taken, the code that writes the TR::CodeCache pointer at the beginning of the code cache segment will not be executed. This is a result of https://github.com/eclipse/omr/pull/7129 and requires an OMR change.

**Comment by mpirvu** [comment]
Attempt at a fix here: https://github.com/eclipse/omr/pull/7138

**Comment by pshipton** [comment]
I suspect this failure is related. It seems likely caused by https://github.com/eclipse/omr/pull/7129
We'll see if the OMR update fixes this as well.

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_0/632
testDDRExt_Class_0
```
01:21:02       [java] jit code segments - !j9memorysegmentlist 0x383d08
01:21:02       [java] +--------+--------+--------+--------+--------+--------+
01:21:02       [java] |segment | start  |  warm  |  cold  |  end   |  size  |
01:21:02       [java] +--------+--------+--------+--------+--------+--------+
01:21:02       [java] Problem running command:
01:21:02       [java] com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: com.ibm.j9ddr.NullPointerDereference: Memory Fault reading 0x00000000 : 
01:21:02       [java] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.DumpAllSegmentsCommand.run(DumpAllSegmentsCommand.java:67)
01:21:02       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
01:21:02       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
01:21:02       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:182)
01:21:02       [java] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:361)
01:21:02       [java] 	at j9vm.test.ddrext.DDRExtTesterBase.exec(DDRExtTesterBase.java:97)
01:21:02       [java] 	at j9vm.test.ddrext.junit.TestClassExt.testDumpAllSegmentsExt(TestClassExt.java:256)
```

**Comment by hzongaro** [comment]
Peter @pshipton, Marius @mpirvu, should this issue be closed, moved to the backlog or carried forward to release 0.44?
