### ISSUE TITLE
p8-java1-ibm01, p8-java1-ibm02 Cannot run program "git"

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18247]
https://openj9-jenkins.osuosl.org/computer/p8%2Djava1%2Dibm01/
https://openj9-jenkins.osuosl.org/computer/p8%2Djava1%2Dibm02/

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_1/630/
```
22:08:49  Cloning the remote Git repository
22:08:49  ERROR: Error cloning remote repo 'origin'
22:08:49  hudson.plugins.git.GitException: Could not init /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_1/aqa-tests
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1073)
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:819)
22:08:49  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)
22:08:49  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
22:08:49  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
22:08:49  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
22:08:49  	at hudson.remoting.Request$2.run(Request.java:377)
22:08:49  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
22:08:49  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
22:08:49  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
22:08:49  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
22:08:49  	at java.base/java.lang.Thread.run(Thread.java:840)
22:08:49  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to p8-java1-ibm02
22:08:49  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
22:08:49  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
22:08:49  		at hudson.remoting.Channel.call(Channel.java:1000)
22:08:49  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)
22:08:49  		at jdk.internal.reflect.GeneratedMethodAccessor995.invoke(Unknown Source)
22:08:49  		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:08:49  		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:08:49  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)
22:08:49  		at com.sun.proxy.$Proxy170.execute(Unknown Source)
22:08:49  		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1222)
22:08:49  		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
22:08:49  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
22:08:49  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
22:08:49  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
22:08:49  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
22:08:49  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$558/0x0000000000000000.run(Unknown Source)
22:08:49  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
22:08:49  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
22:08:49  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
22:08:49  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
22:08:49  		at java.base/java.lang.Thread.run(Thread.java:836)
22:08:49  Caused by: hudson.plugins.git.GitException: Error performing git command: git init /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_1/aqa-tests
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2858)
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2762)
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2757)
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2051)
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1071)
22:08:49  	... 11 more
22:08:49  Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_1/aqa-tests"): error=2, No such file or directory
22:08:49  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
22:08:49  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
22:08:49  	at hudson.Proc$LocalProc.<init>(Proc.java:252)
22:08:49  	at hudson.Proc$LocalProc.<init>(Proc.java:221)
22:08:49  	at hudson.Launcher$LocalLauncher.launch(Launcher.java:994)
22:08:49  	at hudson.Launcher$ProcStarter.start(Launcher.java:506)
22:08:49  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2835)
22:08:49  	... 15 more
22:08:49  Caused by: java.io.IOException: error=2, No such file or directory
22:08:49  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
22:08:49  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
22:08:49  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
22:08:49  	... 21 more
```

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by mahdipub** [comment]
@pshipton Build and test nodes removed from both nodes till solving issue.
