### ISSUE TITLE
TestJlmRemoteThreadAuth_1 UnmarshalException

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#18280]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly/546/
TestJlmRemoteThreadAuth_1

```
openjdk version "17.0.9-internal" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9-internal+0-adhoc..BuildJDK17aarch64linuxNightly)
Eclipse OpenJ9 VM (build master-0d83d4d158d, JRE 17 Linux aarch64-64-Bit Compressed References 20231010_565 (JIT enabled, AOT enabled)
OpenJ9   - 0d83d4d158d
OMR      - 83cb59850cf
JCL      - e8b09b9a5bf based on jdk-17.0.9+7)
```

```
CL2 j> 2023/10/11 02:27:01.305 Writing report data ...
STF 02:28:10.476 - **FAILED** Process CL2 has timed out
STF 02:28:10.476 - Collecting dumps for: CL2
STF 02:28:10.476 - Sending SIG 3 to the java process to generate a javacore
STF 02:28:10.477 - Running command: kill -3 1516425
STF 02:28:10.477 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/output_16969831775337/TestJlmRemoteThreadAuth_1/20231011-014812-TestJlmRemoteThreadAuth/results/8.CL2.kill_3.stderr
STF 02:28:10.477 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/output_16969831775337/TestJlmRemoteThreadAuth_1/20231011-014812-TestJlmRemoteThreadAuth/results/8.CL2.kill_3.stdout
STF 02:28:10.479 - Pausing for 30 seconds
STF 02:28:40.479 - Process CL2 (pid 1516425) is no longer running. Abandoning dump collection.
CL2 j> 2023/10/11 02:28:12.880  done.
CL2 j> 2023/10/11 02:28:24.101 Writing report data ...
CL2 j> 2023/10/11 02:28:29.438 Error unmarshaling return header; nested exception is: 
CL2 	java.io.EOFException
CL2 stderr JVMDUMP039I Processing dump event "user", detail "" at 2023/10/11 02:28:10 - please wait.
CL2 stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/output_16969831775337/TestJlmRemoteThreadAuth_1/20231011-014812-TestJlmRemoteThreadAuth/results/core.20231011.022810.1516425.0001.dmp' in response to an event
CL2 stderr java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is: 
CL2 stderr 	java.io.EOFException
CL2 stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:255)
CL2 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:165)
CL2 stderr 	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(RMIConnectionImpl_Stub.java:419)
CL2 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1021)
CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ThreadData.writeData(ThreadData.java:549)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:199)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
CL2 stderr Caused by: java.io.EOFException
CL2 stderr 	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
CL2 stderr 	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268)
CL2 stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:241)
CL2 stderr 	... 7 more
CL2 stderr Exception in thread "main" java.lang.AssertionError: Error unmarshaling return header; nested exception is: 
CL2 stderr 	java.io.EOFException
CL2 stderr 	at org.junit.Assert.fail(Assert.java:88)
CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ThreadData.writeData(ThreadData.java:727)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:199)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
CL2 stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/output_16969831775337/TestJlmRemoteThreadAuth_1/20231011-014812-TestJlmRemoteThreadAuth/results/core.20231011.022810.1516425.0001.dmp
CL2 stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/output_16969831775337/TestJlmRemoteThreadAuth_1/20231011-014812-TestJlmRemoteThreadAuth/results/javacore.20231011.022810.1516425.0002.txt' in response to an event
CL2 stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/output_16969831775337/TestJlmRemoteThreadAuth_1/20231011-014812-TestJlmRemoteThreadAuth/results/javacore.20231011.022810.1516425.0002.txt
CL2 stderr JVMDUMP013I Processed dump event "user", detail "".
STF 02:28:40.483 - Monitoring Report Summary:
STF 02:28:40.483 -   o Process CL2 has timed out
STF 02:28:40.483 -   o Process LT2 ended sucessfully
```

**Comment by pshipton** [comment]
Seems like a network problem.

**Comment by knn-k** [comment]
30x Grinder for TestJlmRemoteThreadAuth_1 finished successfully.  https://openj9-jenkins.osuosl.org/job/Grinder/2969

**Comment by knn-k** [comment]
I see no new failures with this testcase.  Closing.
