### ISSUE TITLE
OpenJDK java/security/Security/SynchronizedAccess Problem cleaning up the following threads

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18298]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/77/
jdk_security1_1
java/security/Security/SynchronizedAccess.java
```
22:03:40  JavaTest Message: Problem cleaning up the following threads:
22:03:40  thread199
22:03:40    at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:927)
22:03:40    at java.lang.ClassLoader.loadClass(ClassLoader.java:902)
22:03:40    at java.lang.ClassLoader.loadClass(ClassLoader.java:885)
22:03:40    at java.security.Provider$Service.getImplClass(Provider.java:1649)
22:03:40    at java.security.Provider$Service.newInstance(Provider.java:1605)
22:03:40    at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
22:03:40    at java.security.Signature.getInstance(Signature.java:271)
22:03:40    at AccessorThread.run(SynchronizedAccess.java:70)

...
<thread199 - thread0 are listed>
```

**Comment by pshipton** [comment]
Check if the problem is intermittent https://openj9-jenkins.osuosl.org/job/Grinder/2978/
