### ISSUE TITLE
JDK22 Jep454Tests_testLinkerFfi_UpCall_0_FAILED  java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(VarHandle,MemorySegment,long,int)void to (VarHandle,MemorySegment,int)void

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18305]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkNext_j9_sanity.functional_x86-64_linux_Personal/454/tapResults/)(`sles15x86-rtp-rt1-1`):
```
23:52:23  openjdk version "22-internal" 2024-03-19
23:52:23  OpenJDK Runtime Environment (build 22-internal-adhoc.jenkins.BuildJDKnextx86-64linuxPersonal)
23:52:23  Eclipse OpenJ9 VM (build jdk22accessV2-44fd90e7507, JRE 22 Linux amd64-64-Bit Compressed References 20231018_1321 (JIT enabled, AOT enabled)
23:52:23  OpenJ9   - 44fd90e7507
23:52:23  OMR      - 03f6b9097ec
23:52:23  JCL      - 26ba2be3e7f based on jdk-22+19)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=sanity.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F1321%2FOpenJ9-JDKnext-x86-64_linux-20231018-200320.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F1321%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=jdk22accessV2&OPENJ9_SHA=44fd90e75076810e4732b317a056f6314214921e&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=6c8872e0463d5d67925d89e5841c3207a6e668d4&JDK_BRANCH=mergestagingV2&LABEL_ADDITION=ci.project.openj9%26%26%21sw.os.cent.6%26%26%21sw.os.rhel.6&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
variation: --enable-preview
JVM_OPTIONS:  --enable-preview 

FAILED: test_heapSegmentForReturnPtr
org.testng.TestException: 
The exception was thrown with the wrong message: expected "Heap segment not allowed.*" but got "cannot convert MethodHandle(VarHandle,MemorySegment,long,int)void to (VarHandle,MemorySegment,int)void"
	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:71)
	at org.testng.internal.Invoker.considerExceptions(Invoker.java:1129)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(VarHandle,MemorySegment,long,int)void to (VarHandle,MemorySegment,int)void
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:903)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:870)
	at org.openj9.test.jep454.upcall.InvalidUpCallTests.test_heapSegmentForReturnPtr(InvalidUpCallTests.java:223)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	... 18 more

===============================================
    Jep454Tests_testLinkerFfi_UpCall
    Tests run: 220, Failures: 96, Skips: 0
===============================================


===============================================
Java22+ test suite
Total tests run: 220, Failures: 96, Skips: 0
===============================================

-----------------------------------
Jep454Tests_testLinkerFfi_UpCall_0_FAILED

===============================================
Java22+ test suite
Total tests run: 341, Failures: 129, Skips: 0
===============================================

-----------------------------------
Jep454Tests_testLinkerFfi_DownCall_0_FAILED
```

FYI @ChengJin01

**Comment by ChengJin01** [comment]
Based on the exception as follows:
```
Caused by: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(VarHandle,MemorySegment,long,int)void
to (VarHandle,MemorySegment,int)void
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:903)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:870)
	at org.openj9.test.jep454.upcall.InvalidUpCallTests.test_heapSegmentForReturnPtr(InvalidUpCallTests.java:223)
```
against the test code at https://github.com/eclipse-openj9/openj9/pull/18296/files#diff-b1726d2fa397683000a1ba64f2dd62610e2cbffc491ddf9bf8d18d72f3a7932eR223
```
intHandle1.set(structSegmt1, 11223344);
```
It looks like there are some unexpected updates in VarHandle/MH APIs in the latest OpenJDK extension in which we might need to update the test accordingly to adapt to these changes.

**Comment by ChengJin01** [comment]
The correct code example is as follows at https://github.com/JasonFengJ9/openj9-openjdk-jdk/blob/6b7a6cdb93b2b32785e482189a17a6b74e597195/src/java.base/share/classes/jdk/internal/foreign/abi/fallback/FFIType.java#L82
```
    private static final VarHandle VH_TYPE = LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    private static final VarHandle VH_ELEMENTS = LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("elements"));

        MemorySegment ffiType = scope.allocate(LAYOUT);
        VH_TYPE.set(ffiType, 0L, LibFallback.structTag()); <------ 0L is the offset  of the variable via VarHandle.
        VH_ELEMENTS.set(ffiType, 0L, elementsSeg); <--------
```
The offset parameter never occurs before JDK21, in which case 0L (by default) needs to be added to all related test case, which should follow the same as https://github.com/JasonFengJ9/openj9-openjdk-jdk/blob/6b7a6cdb93b2b32785e482189a17a6b74e597195/src/java.base/share/classes/java/lang/foreign/MemorySegment.java
e.g.
```
@ForceInline
    default byte get(ValueLayout.OfByte layout, long offset) {
        return (byte) layout.varHandle().get(this, offset); <-------
    }

default void set(ValueLayout.OfByte layout, long offset, byte value) {
        layout.varHandle().set(this, offset, value); <----------
    }
```

**Comment by JasonFengJ9** [comment]
Fixed in https://github.com/eclipse-openj9/openj9/pull/18296
