### ISSUE TITLE
OpenJDK java/lang/Object/InvalidFinalizationOption - "this.this$0.jar" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18329]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/81 - [ub20-390-5](https://openj9-jenkins.osuosl.org/computer/ub20-390-5)
jdk_lang_1
java/lang/Object/InvalidFinalizationOption.java
```
19:08:16  java.lang.NullPointerException: Cannot invoke "java.util.jar.JarFile.getInputStream(java.util.zip.ZipEntry)" because "this.this$0.jar" is null
19:08:16  	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:975)
19:08:16  	at java.base/jdk.internal.loader.Resource.cachedInputStream(Resource.java:99)
19:08:16  	at java.base/jdk.internal.loader.Resource.getByteBuffer(Resource.java:185)
19:08:16  	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:646)
19:08:16  	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1061)
19:08:16  	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1046)
19:08:16  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
19:08:16  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:572)
19:08:16  	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1206)
19:08:16  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1121)
19:08:16  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
19:08:16  	at jdk.test.lib.process.OutputAnalyzer.<init>(OutputAnalyzer.java:66)
19:08:16  	at InvalidFinalizationOption.main(InvalidFinalizationOption.java:53)
```

java/lang/Package/bootclasspath/GetPackageFromBootClassPath.java
```
19:08:16  java.lang.NullPointerException: Cannot read field "jar" because "this.this$0" is null
19:08:16  	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:975)
19:08:16  	at java.base/jdk.internal.loader.Resource.cachedInputStream(Resource.java:99)
19:08:16  	at java.base/jdk.internal.loader.Resource.getByteBuffer(Resource.java:185)
19:08:16  	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:646)
19:08:16  	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1061)
19:08:16  	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1046)
19:08:16  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
19:08:16  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:572)
19:08:16  	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1206)
19:08:16  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1121)
19:08:16  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
19:08:16  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:173)
19:08:16  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:317)
19:08:16  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:242)
19:08:16  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:71)
```

**Comment by pshipton** [comment]
Changes from previous build
https://github.com/eclipse-openj9/openj9/compare/70705baf3c...dc6ce508171

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/102/
java/util/Properties/StoreReproducibilityTest.java
```
19:58:10  java.lang.NullPointerException: Cannot read field "jar" because "this.this$0" is null
19:58:10  	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:975)
19:58:10  	at java.base/jdk.internal.loader.Resource.cachedInputStream(Resource.java:99)
19:58:10  	at java.base/jdk.internal.loader.Resource.getByteBuffer(Resource.java:185)
19:58:10  	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:646)
19:58:10  	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1061)
19:58:10  	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1046)
19:58:10  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
19:58:10  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:572)
19:58:10  	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1206)
19:58:10  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1121)
19:58:10  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
19:58:10  	at StoreReproducibilityTest.testWithoutSecurityManager(StoreReproducibilityTest.java:95)
19:58:10  	at StoreReproducibilityTest.main(StoreReproducibilityTest.java:60)
```
