### ISSUE TITLE
jdk_security3_0_FAILED sun/security/tools/keytool/fakegen/DefaultSignatureAlgorithm.java keytool error: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18320]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_0/6/)(`rhel8-aarch64-3`):
```
java version "11.0.21" 2023-10-17
IBM Semeru Runtime Certified Edition 11.0.21.0 (build 11.0.21+9)
Eclipse OpenJ9 VM 11.0.21.0 (build v0.41.0-release-9c5799b80, JRE 11 Linux aarch64-64-Bit Compressed References 20231018_435 (JIT enabled, AOT enabled)
OpenJ9   - 9c5799b80
OMR      - fa7b6ddc7
JCL      - 6f4cc08025 based on jdk-11.0.21+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F435%2Fibm-semeru-certified-jdk_aarch64_linux_11.0.21.0.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F435%2Fibm-semeru-certified-testimage_aarch64_linux_11.0.21.0.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v0.9.9-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=main&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=136&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=48&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-10-19T19:03:59.884Z] variation: Mode150
[2023-10-19T19:03:59.884Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-10-19T19:39:54.673Z] TEST: sun/security/tools/keytool/fakegen/DefaultSignatureAlgorithm.java

[2023-10-19T19:39:54.679Z] STDERR:
[2023-10-19T19:39:54.679Z]  stdout: [keytool error: java.lang.UnsupportedOperationException
[2023-10-19T19:39:54.679Z] ];
[2023-10-19T19:39:54.679Z]  stderr: []
[2023-10-19T19:39:54.679Z]  exitValue = 1
[2023-10-19T19:39:54.679Z] 
[2023-10-19T19:39:54.679Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2023-10-19T19:39:54.679Z] 
[2023-10-19T19:39:54.679Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2023-10-19T19:39:54.679Z] 	at DefaultSignatureAlgorithm.check(DefaultSignatureAlgorithm.java:79)
[2023-10-19T19:39:54.679Z] 	at DefaultSignatureAlgorithm.main(DefaultSignatureAlgorithm.java:63)
[2023-10-19T19:39:54.679Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-19T19:39:54.679Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-10-19T19:39:54.679Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-19T19:39:54.679Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-10-19T19:39:54.679Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-10-19T19:39:54.679Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-10-19T19:39:54.679Z] 
[2023-10-19T19:39:54.679Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

[2023-10-19T19:39:54.680Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
[2023-10-19T19:39:54.680Z] --------------------------------------------------
[2023-10-19T19:50:43.328Z] Test results: passed: 769; failed: 1
[2023-10-19T19:51:04.217Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_0/aqa-tests/TKG/output_16977422384907/jdk_security3_0/report/html/report.html
[2023-10-19T19:51:04.217Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_0/aqa-tests/TKG/output_16977422384907/jdk_security3_0/work
[2023-10-19T19:51:04.217Z] Error: Some tests failed or other problems occurred.
[2023-10-19T19:51:04.217Z] -----------------------------------
[2023-10-19T19:51:04.217Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35528/)

**Comment by JasonFengJ9** [comment]
[JDK11 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_ppc64le_linux/177/)(`rhel8le-rtp-rt3-1`)
```
java version "11.0.21" 2023-10-17
IBM Semeru Runtime Certified Edition 11.0.21.0-rc2 (build 11.0.21+9)
Eclipse OpenJ9 VM 11.0.21.0-rc2 (build v0.41.0-release-a803f004b, JRE 11 Linux ppc64le-64-Bit Compressed References 20231116_717 (JIT enabled, AOT enabled)
OpenJ9   - a803f004b
OMR      - 5eee6ad9d
JCL      - 6f4cc08025 based on jdk-11.0.21+9)

[2023-11-16T21:42:05.618Z] variation: Mode150
[2023-11-16T21:42:05.618Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-11-16T22:25:10.672Z] TEST: sun/security/tools/keytool/fakegen/DefaultSignatureAlgorithm.java

[2023-11-16T22:25:10.677Z] STDERR:
[2023-11-16T22:25:10.677Z]  stdout: [keytool error: java.lang.UnsupportedOperationException
[2023-11-16T22:25:10.677Z] ];
[2023-11-16T22:25:10.677Z]  stderr: []
[2023-11-16T22:25:10.677Z]  exitValue = 1
[2023-11-16T22:25:10.677Z] 
[2023-11-16T22:25:10.677Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2023-11-16T22:25:10.677Z] 
[2023-11-16T22:25:10.677Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2023-11-16T22:25:10.677Z] 	at DefaultSignatureAlgorithm.check(DefaultSignatureAlgorithm.java:79)
[2023-11-16T22:25:10.677Z] 	at DefaultSignatureAlgorithm.main(DefaultSignatureAlgorithm.java:63)
[2023-11-16T22:25:10.677Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-16T22:25:10.677Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-11-16T22:25:10.677Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-16T22:25:10.677Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-11-16T22:25:10.677Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-11-16T22:25:10.678Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-11-16T22:25:10.678Z] 
[2023-11-16T22:25:10.678Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

[2023-11-16T22:34:25.662Z] jdk_security3_0_FAILED
```
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36197/)

**Comment by JasonFengJ9** [comment]
[JDK11 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_ppc64le_linux_testList_0/6/)(`cent8le-svl-rt8-1`)
```
java version "11.0.23-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 11.0.23+5-202402292307 (build 11.0.23-beta+5-202402292307)
Eclipse OpenJ9 VM 11.0.23+5-202402292307 (build master-2095c8e18, JRE 11 Linux ppc64le-64-Bit Compressed References 20240229_794 (JIT enabled, AOT enabled)
OpenJ9   - 2095c8e18
OMR      - 9235a2ff6
JCL      - 7acd29681d based on jdk-11.0.23+5)

[2024-02-29T23:56:41.758Z] variation: Mode150
[2024-02-29T23:56:41.758Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-01T00:48:45.310Z] TEST: sun/security/tools/keytool/fakegen/DefaultSignatureAlgorithm.java

[2024-03-01T00:48:45.314Z] STDERR:
[2024-03-01T00:48:45.314Z]  stdout: [keytool error: java.lang.UnsupportedOperationException
[2024-03-01T00:48:45.314Z] ];
[2024-03-01T00:48:45.314Z]  stderr: []
[2024-03-01T00:48:45.314Z]  exitValue = 1
[2024-03-01T00:48:45.314Z] 
[2024-03-01T00:48:45.314Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2024-03-01T00:48:45.314Z] 
[2024-03-01T00:48:45.314Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2024-03-01T00:48:45.314Z] 	at DefaultSignatureAlgorithm.check(DefaultSignatureAlgorithm.java:79)
[2024-03-01T00:48:45.314Z] 	at DefaultSignatureAlgorithm.main(DefaultSignatureAlgorithm.java:63)
[2024-03-01T00:48:45.314Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-03-01T00:48:45.314Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-03-01T00:48:45.314Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-03-01T00:48:45.314Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-03-01T00:48:45.314Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-03-01T00:48:45.314Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-03-01T00:48:45.314Z] 
[2024-03-01T00:48:45.314Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38280/)

Also occurred at [JDK11 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_0/6/)(`rhel8s390x-svl-rt7-1`)

**Comment by pshipton** [comment]
@jasonkatonica we need some help to determine what the problem is. If it's a problem with the machines we should get them updated so the test can pass.

**Comment by JasonFengJ9** [comment]
[JDK11 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/11/)(`rhel8-aarch64-5`)
```
openjdk version "11.0.23" 2024-04-16
IBM Semeru Runtime Open Edition 11.0.23.0-m1 (build 11.0.23+6)
Eclipse OpenJ9 VM 11.0.23.0-m1 (build v0.44.0-release-747f86c91, JRE 11 Linux aarch64-64-Bit Compressed References 20240319_907 (JIT enabled, AOT enabled)
OpenJ9   - 747f86c91
OMR      - 254af5a04
JCL      - b59f8e52b5 based on jdk-11.0.23+6)

[2024-03-20T20:33:43.429Z] variation: Mode650
[2024-03-20T20:33:43.429Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-20T20:59:10.750Z] TEST: sun/security/tools/keytool/fakegen/DefaultSignatureAlgorithm.java

[2024-03-20T20:59:10.752Z] STDERR:
[2024-03-20T20:59:10.752Z]  stdout: [keytool error: java.lang.UnsupportedOperationException
[2024-03-20T20:59:10.752Z] ];
[2024-03-20T20:59:10.752Z]  stderr: []
[2024-03-20T20:59:10.752Z]  exitValue = 1
[2024-03-20T20:59:10.752Z] 
[2024-03-20T20:59:10.752Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2024-03-20T20:59:10.752Z] 
[2024-03-20T20:59:10.752Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2024-03-20T20:59:10.752Z] 	at DefaultSignatureAlgorithm.check(DefaultSignatureAlgorithm.java:79)
[2024-03-20T20:59:10.752Z] 	at DefaultSignatureAlgorithm.main(DefaultSignatureAlgorithm.java:63)

[2024-03-20T20:59:10.752Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
[2024-03-20T20:59:10.753Z] --------------------------------------------------
[2024-03-20T21:07:35.009Z] Test results: passed: 764; failed: 1
[2024-03-20T21:07:35.009Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17109657691482/jdk_security3_1/report/html/report.html
[2024-03-20T21:07:35.009Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17109657691482/jdk_security3_1/work
[2024-03-20T21:07:35.009Z] Error: Some tests failed or other problems occurred.
[2024-03-20T21:07:35.009Z] -----------------------------------
[2024-03-20T21:07:35.009Z] jdk_security3_1_FAILED
```

**Comment by JinhangZhang** [comment]
`rhel8-aarch64-3`, `rhel8-aarch64-5`, `rhel8-aarch64-6`, `cent8le-rtp-rt1-1`, `cent8le-svl-rt8-1`, `rhel8le-rtp-rt3-1` and `rhel8s390x-svl-rt7-1` are Redhat machines. The openssl version used in those machines is
`OpenSSL 1.1.1k  FIPS 25 Mar 2021`
This is a FIPS version of openssl.

Normally, when we use keytool to generate keypairs, the native code from openssl will be loaded and used at first. If the native code is not satisfied, then the jave implementation will be used. 

`DefaultSignatureAlgorithm` test run in those Redhat machines, and the openssl used in those machines is a FIPS certified. So, a 192 size of EC key pair generator is not allowed by the native code in FIPS mode, then a Java implementation is used. But in the `DefaultSignatureAlgorithm` test code, there is no implementation of the initialize in the patched [ECKeyPairGenerator.java](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/sun/security/tools/keytool/fakegen/jdk.crypto.ec/sun/security/ec/ECKeyPairGenerator.java#L52) file. Therefore, the test throws an `UnsupportedOperationException` exception. 

I run the `DefaultSignatureAlgorithm` test in my redhat fyre machine with `OpenSSL 1.1.1k`, it passed.

Therefore, this is not a blocking issue, this could be a machine issue.

**Comment by pshipton** [comment]
Created infrastructure/issues/9147

**Comment by keithc-ca** [comment]
> there is no implementation of the initialize in the patched ECKeyPairGenerator.java file

@JinhangZhang Why do you refer to that file as "patched"? The file `test/jdk/sun/security/tools/keytool/fakegen/jdk.crypto.ec/sun/security/ec/ECKeyPairGenerator.java` is identical to upstream (in all versions unless https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/779 is accepted).

Did you mean to refer instead to `src/jdk.crypto.ec/share/classes/sun/security/ec/ECKeyPairGenerator.java`?However, the only change to the latter file is to increase the visibility of `ensureCurveIsSupported(ECParameterSpec)` (by removing the `private` modifier).

**Comment by JinhangZhang** [comment]
[Keytool](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/sun/security/tools/keytool/fakegen/DefaultSignatureAlgorithm.java#L93) command inside DefaultSignatureAlgorithm.java file use `test/jdk/sun/security/tools/keytool/fakegen/jdk.crypto.ec/sun/security/ec/ECKeyPairGenerator.java` as a patch.

> @JinhangZhang Why do you refer to that file as "patched"? The file test/jdk/sun/security/tools/keytool/fakegen/jdk.crypto.ec/sun/security/ec/ECKeyPairGenerator.java is identical to upstream (in all versions unless https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/779 is accepted).
