### ISSUE TITLE
JDK21 jdk_lang_1_FAILED sun/misc/URLClassPath/LargeClasspathWithPkgPrefix.java Exception in thread "main" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18337]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_testList_1/30/)(`ubu22-aarch64-4`):
```
java version "21-beta" 2023-09-19
IBM Semeru Runtime Certified Edition 21+35-202310211503 (build 21-beta+35-202310211503)
Eclipse OpenJ9 VM 21+35-202310211503 (build master-3cad35878, JRE 21 Linux aarch64-64-Bit Compressed References 20231021_17 (JIT enabled, AOT enabled)
OpenJ9   - 3cad35878
OMR      - c23dd83f7
JCL      - 773775ae2 based on jdk-21+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_lang_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_sanity.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-aarch64-openj9-IBM%2F17%2Fibm-semeru-certified-jdk_aarch64_linux_JDK21U_2023-10-21-15-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-aarch64-openj9-IBM%2F17%2Fibm-semeru-certified-testimage_aarch64_linux_JDK21U_2023-10-21-15-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=31&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-10-21T16:31:00.091Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2023-10-21T16:31:00.091Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

[2023-10-21T17:24:12.185Z] TEST: sun/misc/URLClassPath/LargeClasspathWithPkgPrefix.java

[2023-10-21T17:24:12.187Z] STDERR:
[2023-10-21T17:24:12.187Z]  stdout: [];
[2023-10-21T17:24:12.187Z]  stderr: [Error: A JNI error has occurred, please check your installation and try again
[2023-10-21T17:24:12.187Z] Exception in thread "main" java.lang.StackOverflowError
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.util.ArraysSupport.mismatch(ArraysSupport.java:393)
[2023-10-21T17:24:12.187Z] 	at java.base/java.lang.String.startsWith(String.java:3050)
[2023-10-21T17:24:12.187Z] 	at java.base/java.lang.String.startsWith(String.java:3080)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.isBuiltinStreamHandler(URL.java:1856)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.isBuiltinStreamHandler(URL.java:1851)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URLStreamHandler.setURL(URLStreamHandler.java:520)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:326)
[2023-10-21T17:24:12.187Z] 	at java.base/sun.net.www.protocol.file.Handler.parseURL(Handler.java:56)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.<init>(URL.java:801)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.<init>(URL.java:654)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1218)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:418)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:473)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:958)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[2023-10-21T17:24:12.187Z] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.lookupViaProperty(URL.java:1453)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.getURLStreamHandler(URL.java:1622)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.<init>(URL.java:546)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath$JarLoader.newURL(URLClassPath.java:868)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:854)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:622)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:604)
[2023-10-21T17:24:12.187Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:603)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:554)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:417)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:473)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:958)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
[2023-10-21T17:24:12.187Z] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[2023-10-21T17:24:12.187Z] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.lookupViaProperty(URL.java:1453)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.getURLStreamHandler(URL.java:1622)
[2023-10-21T17:24:12.187Z] 	at java.base/java.net.URL.<init>(URL.java:546)

[2023-10-21T17:24:12.199Z] 	at java.base/java.net.URL.<init>(URL.java:546)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath$JarLoader.newURL(URLClassPath.java:868)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:854)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:622)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:604)
[2023-10-21T17:24:12.199Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:603)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:554)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:417)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:473)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:958)
[2023-10-21T17:24:12.199Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
[2023-10-21T17:24:12.200Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
[2023-10-21T17:24:12.200Z] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[2023-10-21T17:24:12.200Z] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
[2023-10-21T17:24:12.200Z] 	at java.base/java.lang.Class.forNameImpl(Native Method)
[2023-10-21T17:24:12.200Z] 	at java.base/java.lang.Class.forNameHelper(Class.java:454)
[2023-10-21T17:24:12.200Z] 	at java.base/java.lang.Class.forName(Class.java:432)
[2023-10-21T17:24:12.200Z] 	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:797)
[2023-10-21T17:24:12.200Z] 	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:692)
[2023-10-21T17:24:12.200Z] ]
[2023-10-21T17:24:12.200Z]  exitValue = 1
[2023-10-21T17:24:12.200Z] 
[2023-10-21T17:24:12.200Z] java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [1]
[2023-10-21T17:24:12.200Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:490)
[2023-10-21T17:24:12.200Z] 	at LargeClasspathWithPkgPrefix.launchApplication(LargeClasspathWithPkgPrefix.java:137)
[2023-10-21T17:24:12.200Z] 	at LargeClasspathWithPkgPrefix.main(LargeClasspathWithPkgPrefix.java:104)
[2023-10-21T17:24:12.200Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-10-21T17:24:12.200Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-10-21T17:24:12.200Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2023-10-21T17:24:12.200Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-10-21T17:24:12.200Z] 
[2023-10-21T17:24:12.200Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2023-10-21T17:24:12.200Z] JavaTest Message: shutting down test
[2023-10-21T17:24:12.200Z] 
[2023-10-21T17:24:12.200Z] 
[2023-10-21T17:24:12.200Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [1]
[2023-10-21T17:24:12.200Z] --------------------------------------------------
[2023-10-21T17:24:16.650Z] Test results: passed: 930; failed: 1
[2023-10-21T17:24:37.737Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_1697905858687/jdk_lang_1/report/html/report.html
[2023-10-21T17:24:37.737Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_1697905858687/jdk_lang_1/work
[2023-10-21T17:24:37.737Z] Error: Some tests failed or other problems occurred.
[2023-10-21T17:24:37.737Z] -----------------------------------
[2023-10-21T17:24:37.737Z] jdk_lang_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35573/)

This build didn't get latest JDK21 tag, it might be a mismatch JCL/VM issue.

**Comment by tajila** [comment]
Could be related to https://github.com/eclipse-openj9/openj9/pull/16662/

**Comment by tajila** [comment]
Grinder with diagnostics https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35715/

**Comment by JasonFengJ9** [comment]
`jdk_lang_1_PASSED` in [latest run w/ jdk-21.0.1+12](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_testList_1/36/consoleFull)
I think this can be closed.
