### ISSUE TITLE
OpenJDK java/lang/ref/PhantomReferentClearing 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18340]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/82/
jdk_lang_0
java/lang/ref/PhantomReferentClearing.java
```
18:53:52  java.lang.RuntimeException: P2 not notified by O2 deletion
18:53:52  	at PhantomReferentClearing.main(PhantomReferentClearing.java:98)
18:53:52  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
18:53:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
18:53:52  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
18:53:52  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by dmitripivkine** [comment]
Looking to the test source code I guess 1s timeout has not been long enough to execute Finalization (and this is s390, it is not a first time). If it is reproducible and somebody helps me to generate system core for this exception we can figure out exact reason.
https://programtalk.com/vs/?source=openjdk/jdk/test/java/lang/ref/PhantomReferentClearing.java

**Comment by dmitripivkine** [comment]
Hm,  https://github.com/eclipse-openj9/openj9/pull/18044 introduced implicit "Run Finalization" to System GC call. So, it should work, probably not a timeout issue.

**Comment by dmitripivkine** [comment]
Another theoretical possibility is reference to O2 might be stored in O-slot for higher level of hotness for JITed method. It keep O2 alive even after `O2 = null;`.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/98
