### ISSUE TITLE
JDK21 JLM_Tests_interface_0_FAILED testThreadAllocationMetricsOnCurrentThread UnsupportedOperationException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18368]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.functional_x86-64_mac_testList_0/42/)(`siakam`):
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202310261403 (build 21.0.1-beta+12-202310261403)
Eclipse OpenJ9 VM 21.0.1+12-202310261403 (build master-66e3fd1da, JRE 21 Mac OS X amd64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
OpenJ9   - 66e3fd1da
OMR      - 071c0c25b
JCL      - c06eaf638 based on jdk-21.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=JLM_Tests_interface_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_sanity.functional_x86-64_mac&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-mac-x64-openj9-IBM%2F22%2Fibm-semeru-certified-jdk_x64_mac_JDK21U_2023-10-26-14-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-mac-x64-openj9-IBM%2F22%2Fibm-semeru-certified-testimage_x64_mac_JDK21U_2023-10-26-14-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21sw.os.mac.10_11&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=43&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-10-26T17:51:46.622Z] variation: NoOptions
[2023-10-26T17:51:46.622Z] JVM_OPTIONS:  

[2023-10-26T17:51:53.497Z] FAILED: testThreadAllocationMetricsOnCurrentThread
[2023-10-26T17:51:53.497Z] java.lang.UnsupportedOperationException
[2023-10-26T17:51:53.497Z] 	at jdk.management/com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl.isThreadAllocatedMemoryEnabled(ExtendedThreadMXBeanImpl.java:150)
[2023-10-26T17:51:53.497Z] 	at org.openj9.test.java.lang.management.TestThreadMXBean.testThreadAllocationMetricsOnCurrentThread(TestThreadMXBean.java:1069)
[2023-10-26T17:51:53.497Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-10-26T17:51:53.497Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-10-26T17:51:53.497Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2023-10-26T17:51:53.497Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2023-10-26T17:51:53.497Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2023-10-26T17:51:53.498Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2023-10-26T17:51:53.498Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-10-26T17:51:53.498Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2023-10-26T17:51:53.498Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2023-10-26T17:51:53.498Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2023-10-26T17:51:53.498Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2023-10-26T17:51:53.498Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2023-10-26T17:51:53.498Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-10-26T17:51:53.498Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2023-10-26T17:51:53.498Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2023-10-26T17:51:53.498Z] 
[2023-10-26T17:51:53.498Z] 
[2023-10-26T17:51:53.498Z] ===============================================
[2023-10-26T17:51:53.498Z]     TestThreadMXBean
[2023-10-26T17:51:53.498Z]     Tests run: 36, Failures: 1, Skips: 0
[2023-10-26T17:51:53.498Z] ===============================================

[2023-10-26T17:51:53.863Z] JLM_Tests_interface_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35697/)

**Comment by pshipton** [comment]
This is a mismatch between the JVM and the tests. Should be resolved in the next test cycle.
