### ISSUE TITLE
JDK21 serviceability_jvmti SuspendResumeAll RuntimeException unexpected status: 2

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#18370]
Failure link
------------

[JDK21 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_mac/11/)(`mac11x64rt04`)
```
10:57:25  java version "21.0.1-beta" 2023-10-17
10:57:25  IBM Semeru Runtime Certified Edition 21.0.1+12-202310261403 (build 21.0.1-beta+12-202310261403)
10:57:25  Eclipse OpenJ9 VM 21.0.1+12-202310261403 (build master-66e3fd1da, JRE 21 Mac OS X amd64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
10:57:25  OpenJ9   - 66e3fd1da
10:57:25  OMR      - 071c0c25b
10:57:25  JCL      - c06eaf638 based on jdk-21.0.1+12)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202310261403 (build 21.0.1-beta+12-202310261403)
Eclipse OpenJ9 VM 21.0.1+12-202310261403 (build master-66e3fd1da, JRE 21 Mac OS X amd64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
OpenJ9   - 66e3fd1da
OMR      - 071c0c25b
JCL      - c06eaf638 based on jdk-21.0.1+12)

[2023-10-26T15:00:50.188Z] variation: Mode650
[2023-10-26T15:00:50.188Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-10-26T15:03:11.620Z] TEST: serviceability/jvmti/vthread/SuspendResumeAll/SuspendResumeAll.java#no-vmcontinuations

[2023-10-26T15:03:11.621Z] STDERR:
[2023-10-26T15:03:11.621Z] java.lang.RuntimeException: FAILED: unexpected status: 2
[2023-10-26T15:03:11.621Z] 	at SuspendResumeAll.main(SuspendResumeAll.java:78)
[2023-10-26T15:03:11.621Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-10-26T15:03:11.621Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-10-26T15:03:11.621Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-10-26T15:03:11.621Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)

[2023-10-26T15:03:30.804Z] serviceability_jvmti_j9_1_FAILED
```

**Comment by babsingh** [comment]
Fixed via
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/59
- https://github.com/eclipse-openj9/openj9/pull/18420
- https://github.com/eclipse-openj9/openj9/pull/18439
- https://github.com/eclipse-openj9/openj9/pull/18421
- https://github.com/eclipse-openj9/openj9/pull/18432
- https://github.com/eclipse-openj9/openj9/pull/18453
