### ISSUE TITLE
jdk17 acceptance OpenJDK java/lang/System/LoggerFinder tests failing with StackOverflowError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18405]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK17-Acceptance/88/ - failing on all platforms

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OpenJDK17_testList_0/9
java/lang/System/LoggerFinder/RecursiveLoading/PlatformRecursiveLoadingTest.java
java/lang/System/LoggerFinder/RecursiveLoading/RecursiveLoadingTest.java
java/lang/System/LoggerFinder/SignedLoggerFinderTest/SignedLoggerFinderTest.java

```
22:48:27  java.lang.StackOverflowError
22:48:27  	at java.base/jdk.internal.misc.VM.isSystemDomainLoader(VM.java:194)
22:48:27  	at java.base/jdk.internal.logger.DefaultLoggerFinder$1.run(DefaultLoggerFinder.java:149)
22:48:27  	at java.base/jdk.internal.logger.DefaultLoggerFinder$1.run(DefaultLoggerFinder.java:144)
22:48:27  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
22:48:27  	at java.base/jdk.internal.logger.DefaultLoggerFinder.isSystem(DefaultLoggerFinder.java:144)
22:48:27  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:434)
22:48:27  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:27  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:27  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:437)
22:48:27  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:27  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
...
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:437)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:369)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:366)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.createLogger(LazyLoggers.java:292)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger.getLogger(BootstrapLogger.java:980)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.wrapped(LazyLoggers.java:179)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.getConcreteLogger(LazyLoggers.java:271)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger.flush(BootstrapLogger.java:550)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger$LogEvent.log(BootstrapLogger.java:530)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger$BootstrapExecutors.flush(BootstrapLogger.java:217)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger.redirectTemporaryLoggers(BootstrapLogger.java:1093)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader.service(LoggerFinderLoader.java:97)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader.getLoggerFinder(LoggerFinderLoader.java:263)
22:48:28  	at java.base/java.lang.System$LoggerFinder.lambda$getLoggerFinder$0(System.java:1390)
22:48:28  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:887)
22:48:28  	at java.base/java.lang.System$LoggerFinder.getLoggerFinder(System.java:1389)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.accessLoggerFinder(LazyLoggers.java:354)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:369)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:366)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.createLogger(LazyLoggers.java:292)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger.getLogger(BootstrapLogger.java:980)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.platform(LazyLoggers.java:211)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerWrapper.platformProxy(LazyLoggers.java:337)
22:48:28  	at java.base/jdk.internal.logger.AbstractLoggerWrapper.log(AbstractLoggerWrapper.java:155)
22:48:28  	at java.base/sun.util.logging.PlatformLogger.info(PlatformLogger.java:417)
22:48:28  	at PlatformRecursiveLoadingTest.main(PlatformRecursiveLoadingTest.java:51)
22:48:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:48:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:48:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:48:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:48:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
22:48:28  	at java.base/java.lang.Thread.run(Thread.java:857)
```

```
22:48:28  java.lang.StackOverflowError
22:48:28  	at java.base/jdk.internal.misc.VM.isSystemDomainLoader(VM.java:194)
22:48:28  	at java.base/jdk.internal.logger.DefaultLoggerFinder$1.run(DefaultLoggerFinder.java:149)
22:48:28  	at java.base/jdk.internal.logger.DefaultLoggerFinder$1.run(DefaultLoggerFinder.java:144)
22:48:28  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
22:48:28  	at java.base/jdk.internal.logger.DefaultLoggerFinder.isSystem(DefaultLoggerFinder.java:144)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:434)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:437)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
...
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:437)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:437)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:369)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:366)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.createLogger(LazyLoggers.java:292)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger.getLogger(BootstrapLogger.java:980)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.wrapped(LazyLoggers.java:179)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.getConcreteLogger(LazyLoggers.java:271)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger.flush(BootstrapLogger.java:550)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger$LogEvent.log(BootstrapLogger.java:530)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger$BootstrapExecutors.flush(BootstrapLogger.java:217)
22:48:28  	at java.base/jdk.internal.logger.BootstrapLogger.redirectTemporaryLoggers(BootstrapLogger.java:1093)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader.service(LoggerFinderLoader.java:97)
22:48:28  	at java.base/jdk.internal.logger.LoggerFinderLoader.getLoggerFinder(LoggerFinderLoader.java:263)
22:48:28  	at java.base/java.lang.System$LoggerFinder.lambda$getLoggerFinder$0(System.java:1390)
22:48:28  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:887)
22:48:28  	at java.base/java.lang.System$LoggerFinder.getLoggerFinder(System.java:1389)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.accessLoggerFinder(LazyLoggers.java:354)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:28  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:437)
22:48:28  	at java.base/java.lang.System.getLogger(System.java:1315)
22:48:28  	at RecursiveLoadingTest.main(RecursiveLoadingTest.java:49)
22:48:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:48:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:48:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:48:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:48:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
22:48:28  	at java.base/java.lang.Thread.run(Thread.java:857)
```

```
22:48:35  Exception in thread "main" java.lang.StackOverflowError
22:48:35  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
22:48:35  	at java.base/jdk.internal.logger.DefaultLoggerFinder.isSystem(DefaultLoggerFinder.java:144)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:434)
22:48:35  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:465)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:435)
22:48:35  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
...
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:465)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:435)
22:48:35  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:465)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:435)
22:48:35  	at java.base/jdk.internal.logger.LoggerFinderLoader$TemporaryLoggerFinder.getLogger(LoggerFinderLoader.java:169)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:369)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers$1.apply(LazyLoggers.java:366)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.createLogger(LazyLoggers.java:292)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger.getLogger(BootstrapLogger.java:980)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.wrapped(LazyLoggers.java:179)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers$LazyLoggerAccessor.getConcreteLogger(LazyLoggers.java:271)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger.flush(BootstrapLogger.java:550)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger$LogEvent.log(BootstrapLogger.java:530)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger$BootstrapExecutors.flush(BootstrapLogger.java:217)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger.redirectTemporaryLoggers(BootstrapLogger.java:1093)
22:48:35  	at java.base/jdk.internal.logger.LoggerFinderLoader.service(LoggerFinderLoader.java:97)
22:48:35  	at java.base/jdk.internal.logger.LoggerFinderLoader.getLoggerFinder(LoggerFinderLoader.java:263)
22:48:35  	at java.base/java.lang.System$LoggerFinder.lambda$getLoggerFinder$0(System.java:1390)
22:48:35  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:887)
22:48:35  	at java.base/java.lang.System$LoggerFinder.getLoggerFinder(System.java:1389)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.accessLoggerFinder(LazyLoggers.java:354)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:410)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:465)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:435)
22:48:35  	at java.base/java.lang.System.getLogger(System.java:1315)
22:48:35  	at java.base/jdk.internal.event.EventHelper.isLoggingSecurity(EventHelper.java:149)
22:48:35  	at java.base/sun.security.jca.JCAUtil.tryCommitCertEvent(JCAUtil.java:104)
22:48:35  	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:356)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.parseSignedData(PKCS7.java:301)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.parse(PKCS7.java:158)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.parse(PKCS7.java:126)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.<init>(PKCS7.java:108)
22:48:35  	at java.base/sun.security.util.SignatureFileVerifier.<init>(SignatureFileVerifier.java:125)
22:48:35  	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:308)
22:48:35  	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:239)
22:48:35  	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:761)
22:48:35  	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:849)
22:48:35  	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:187)
22:48:35  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1186)
22:48:35  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1227)
22:48:35  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1242)
22:48:35  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1292)
22:48:35  	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1328)
22:48:35  	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1412)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger$DetectBackend$1.run(BootstrapLogger.java:908)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger$DetectBackend$1.run(BootstrapLogger.java:902)
22:48:35  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger$DetectBackend.<clinit>(BootstrapLogger.java:902)
22:48:35  	at java.base/jdk.internal.logger.BootstrapLogger.useLazyLoggers(BootstrapLogger.java:952)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:460)
22:48:35  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:435)
22:48:35  	at java.base/java.lang.System.getLogger(System.java:1315)
22:48:35  	at java.base/jdk.internal.event.EventHelper.isLoggingSecurity(EventHelper.java:149)
22:48:35  	at java.base/sun.security.jca.JCAUtil.tryCommitCertEvent(JCAUtil.java:104)
22:48:35  	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:356)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.parseSignedData(PKCS7.java:301)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.parse(PKCS7.java:158)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.parse(PKCS7.java:126)
22:48:35  	at java.base/sun.security.pkcs.PKCS7.<init>(PKCS7.java:108)
22:48:35  	at java.base/sun.security.util.SignatureFileVerifier.<init>(SignatureFileVerifier.java:125)
22:48:35  	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:308)
22:48:35  	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:239)
22:48:35  	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:761)
22:48:35  	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:849)
22:48:35  	at SignedLoggerFinderTest.main(SignedLoggerFinderTest.java:125)
```

**Comment by pshipton** [comment]
Probably related to https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/4e9bd11959e
