### ISSUE TITLE
cent8-aarch64-6 No space left on device

### ISSUE THREAD

**Issue by SajinaKandy** [eclipse-openj9/openj9#18418]
Test Failing with `Exception: java.nio.file.FileSystemException: /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_linux_jit_Personal_testList_1: No space left on device
`
Link: https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_linux_jit_Personal_testList_1/11/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_linux_jit_Personal/11

```
12:20:54  ERROR: Execution failed
12:20:54  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to cent8-aarch64-6
12:20:54  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
12:20:54  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
12:20:54  		at hudson.remoting.Channel.call(Channel.java:1000)
12:20:54  		at hudson.FilePath.act(FilePath.java:1192)
12:20:54  		at hudson.FilePath.act(FilePath.java:1181)
12:20:54  		at hudson.FilePath.mkdirs(FilePath.java:1372)
12:20:54  		at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.setupControlDir(FileMonitoringTask.java:309)
```

```
12:20:54  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 53f44f59-7074-445b-af30-ccb0dc753a90
12:20:54  java.nio.file.FileSystemException: /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_linux_jit_Personal_testList_1: No space left on device
12:20:54  	at java.base@11.0.16.1/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
12:20:54  	at java.base@11.0.16.1/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
12:20:54  	at java.base@11.0.16.1/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
12:20:54  	at java.base@11.0.16.1/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
12:20:54  	at java.base@11.0.16.1/java.nio.file.Files.createDirectory(Files.java:690)
12:20:54  	at java.base@11.0.16.1/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
12:20:54  	at java.base@11.0.16.1/java.nio.file.Files.createDirectories(Files.java:783)
12:20:54  	at hudson.FilePath.mkdirs(FilePath.java:3718)
```

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Grinder workspace was consuming 55G. Cleaned up. Back online.
