### ISSUE TITLE
java/lang/ref/SoftReference/Pin.java "systhrow", detail "java/lang/OutOfMemoryError"

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18429]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_testList_0/48/)(`mac11x64rt04`):
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202311072235 (build 21.0.1-beta+12-202311072235)
Eclipse OpenJ9 VM 21.0.1+12-202311072235 (build master-70f56555a, JRE 21 Mac OS X amd64-64-Bit Compressed References 20231107_30 (JIT enabled, AOT enabled)
OpenJ9   - 70f56555a
OMR      - 2a9a7f4e4
JCL      - aec9b74fc based on jdk-21.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_lang_j9_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_sanity.openjdk_x86-64_mac&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-mac-x64-openj9-IBM%2F30%2Fibm-semeru-certified-jdk_x64_mac_JDK21U_2023-11-07-22-33.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-mac-x64-openj9-IBM%2F30%2Fibm-semeru-certified-testimage_x64_mac_JDK21U_2023-11-07-22-33.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21sw.os.mac.10_11&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=49&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-11-08T00:10:30.980Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
[2023-11-08T00:10:30.980Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 

[2023-11-08T00:15:43.414Z] TEST: java/lang/ref/SoftReference/Pin.java

[2023-11-08T00:15:43.414Z] STDOUT:
[2023-11-08T00:15:43.414Z] STDERR:
[2023-11-08T00:15:43.414Z] Filling array with 128 SoftReferences to blocks of 32768 bytes.
[2023-11-08T00:15:43.414Z] Allowing SoftReferences to be enqueued.
[2023-11-08T00:15:43.414Z] Invoking get() on SoftReferences.
[2023-11-08T00:15:43.414Z] Forcing desperate garbage collection...
[2023-11-08T00:15:43.414Z] JVMDUMP055I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError", exception "Java heap space" at 2023/11/07 19:15:41 - please wait.

[2023-11-08T00:15:43.414Z] JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[2023-11-08T00:15:43.414Z] Exception in thread "Attach API wait loop" java/lang/OutOfMemoryError: Java heap space
[2023-11-08T00:15:43.414Z] 	at java/lang/Throwable.printStackTrace (java.base@21.0.1-beta/Throwable.java:554)
[2023-11-08T00:15:43.414Z] 	at java/lang/Throwable.printStackTraceHelper (java.base@21.0.1-beta/Throwable.java:338)
[2023-11-08T00:15:43.414Z] 	at java/lang/Throwable.printStackTrace (java.base@21.0.1-beta/Throwable.java:307)
[2023-11-08T00:15:43.414Z] 	at java/lang/Throwable.printStackTrace (java.base@21.0.1-beta/Throwable.java:250)
[2023-11-08T00:15:43.414Z] JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_testList_0/aqa-tests/TKG/output_16994022294149/jdk_lang_j9_0/work/scratch/1/Snap.20231107.191541.63241.0004.trc' in response to an event
[2023-11-08T00:15:43.414Z] JVMDUMP010I Snap dump written to {nothing to snap}
[2023-11-08T00:15:43.414Z] JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[2023-11-08T00:15:43.414Z] java.lang.OutOfMemoryError: Java heap space
[2023-11-08T00:15:43.414Z] 	at Pin.main(Pin.java:80)
[2023-11-08T00:15:43.414Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-11-08T00:15:43.414Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-11-08T00:15:43.414Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-11-08T00:15:43.414Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-11-08T00:15:43.414Z] 
[2023-11-08T00:15:43.414Z] JavaTest Message: Test threw exception: java.lang.OutOfMemoryError: Java heap space

[2023-11-08T00:15:43.414Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Java heap space
[2023-11-08T00:15:43.415Z] --------------------------------------------------
[2023-11-08T00:21:50.211Z] Test results: passed: 922; failed: 1
[2023-11-08T00:22:00.906Z] Report written to /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_testList_0/aqa-tests/TKG/output_16994022294149/jdk_lang_j9_0/report/html/report.html
[2023-11-08T00:22:00.906Z] Results written to /Users/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_testList_0/aqa-tests/TKG/output_16994022294149/jdk_lang_j9_0/work
[2023-11-08T00:22:00.906Z] Error: Some tests failed or other problems occurred.
[2023-11-08T00:22:00.906Z] -----------------------------------
[2023-11-08T00:22:00.906Z] jdk_lang_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35928/) - passed

**Comment by dmitripivkine** [comment]
There is no system core stored in results (javacore and snap traces only), so not much I can do.
One observation this test runs with 16m heap. Is it intentional? There are seven (sic!) `-Xmx` options in command line, all of them 512m except most right one 16m.

**Comment by llxia** [comment]
Openjdk has the option set: https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/3dfae786468898b7e68263de89961729443b6aef/test/jdk/java/lang/ref/SoftReference/Pin.java#L27

**Comment by dmitripivkine** [comment]
Looking to the source... I believe OOM has been triggered by line https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/3dfae786468898b7e68263de89961729443b6aef/test/jdk/java/lang/ref/SoftReference/Pin.java#L70
There is output for `Forcing desperate garbage collection...`, so we got so far. Starting line 71 there is `try` and while loop forcing and catching OOM. Or, alternatively, intentional OOM has not been caught.

**Comment by dmitripivkine** [comment]
@tajila Looking to Snap traces I can see many system GC in a raw. Is it possible we are missing to catch OOM?

**Comment by tajila** [comment]
The systhrow OOM event is thrown by the attach API thread. It is a legitimate possibility with this test. The only way to mitigate this is to disable attach API when running this test.

**Comment by dmitripivkine** [comment]
> The systhrow OOM event is thrown by the attach API thread. It is a legitimate possibility with this test. The only way to mitigate this is to disable attach API when running this test.

@pshipton @llxia @JasonFengJ9  There are many tests rely on artificially generated OOM handling. I am not sure about scale of the problem, how often we have it. Is it reasonable to review test base and try to improve builds stability by selectively disable attach API?

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_OpenJDK8_testList_1/12
jdk_lang_j9_0
java/lang/ref/SoftReference/Pin.java
```
04:11:52  Filling array with 128 SoftReferences to blocks of 32768 bytes.
04:11:52  Allowing SoftReferences to be enqueued.
04:11:52  Invoking get() on SoftReferences.
04:11:52  Forcing desperate garbage collection...
04:11:52  JVMDUMP055I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError", exception "Java heap space" at 2024/02/09 09:11:49 - please wait.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_OMR_testList_1/67
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_Nightly_testList_2/7/
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_Nightly_testList_2/20
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_Release_testList_2/10

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_OMR_testList_1/385
