### ISSUE TITLE
JDK21 serviceability/jvmti/vthread/FollowReferences/VThreadStackRefTest.java ERROR class VThreadStackRefTest$VThreadMountedJNIReferenced: ref count = 1 (expected 1), thread id = 0 (expected 27)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18426]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux/14/)(`sles12x86-rtp-rt6-1`):
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202311072239 (build 21.0.1-beta+12-202311072239)
Eclipse OpenJ9 VM 21.0.1+12-202311072239 (build master-70f56555a, JRE 21 Linux amd64-64-Bit Compressed References 20231107_30 (JIT enabled, AOT enabled)
OpenJ9   - 70f56555a
OMR      - 2a9a7f4e4
JCL      - aec9b74fc based on jdk-21.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=serviceability_jvmti_j9_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-x64-openj9-IBM%2F30%2Fibm-semeru-certified-jdk_x64_linux_JDK21U_2023-11-07-22-33.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-x64-openj9-IBM%2F30%2Fibm-semeru-certified-testimage_x64_linux_JDK21U_2023-11-07-22-33.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-11-07T23:30:30.394Z] variation: Mode150
[2023-11-07T23:30:30.394Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-11-07T23:35:32.180Z] TEST: serviceability/jvmti/vthread/FollowReferences/VThreadStackRefTest.java#default

[2023-11-07T23:35:32.181Z] Stack local: index = 0, thread_id = 23
[2023-11-07T23:35:32.181Z]   (0) OK class VThreadStackRefTest$VThreadUnmountedReferenced: ref count = 1 (expected 1), thread id = 23 (expected 23)
[2023-11-07T23:35:32.181Z]   (1) OK class VThreadStackRefTest$VThreadUnmountedJNIReferenced: ref count = 0 (expected 0), thread id = 0 (expected 0)
[2023-11-07T23:35:32.181Z]   (2) OK class VThreadStackRefTest$VThreadMountedReferenced: ref count = 1 (expected 1), thread id = 27 (expected 27)
[2023-11-07T23:35:32.181Z]   (3) ERROR class VThreadStackRefTest$VThreadMountedJNIReferenced: ref count = 1 (expected 1), thread id = 0 (expected 27)
[2023-11-07T23:35:32.181Z]   (4) OK class VThreadStackRefTest$PThreadReferenced: ref count = 1 (expected 1), thread id = 28 (expected 28)
[2023-11-07T23:35:32.181Z]   (5) OK class VThreadStackRefTest$VThreadUnmountedEnded: ref count = 0 (expected 0), thread id = 0 (expected 0)
[2023-11-07T23:35:32.181Z] STDERR:
[2023-11-07T23:35:32.181Z] java.lang.RuntimeException: Test failed
[2023-11-07T23:35:32.181Z] 	at VThreadStackRefTest.main(VThreadStackRefTest.java:192)
[2023-11-07T23:35:32.181Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-11-07T23:35:32.181Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-11-07T23:35:32.181Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-11-07T23:35:32.181Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-11-07T23:35:32.181Z] 
[2023-11-07T23:35:32.181Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed

[2023-11-07T23:35:32.182Z] TEST: serviceability/jvmti/vthread/FollowReferences/VThreadStackRefTest.java#no-vmcontinuations

[2023-11-07T23:35:32.182Z] Stack local: index = 0, thread_id = 23
[2023-11-07T23:35:32.182Z]   (0) OK class VThreadStackRefTest$VThreadUnmountedReferenced: ref count = 1 (expected 1), thread id = 23 (expected 23)
[2023-11-07T23:35:32.182Z]   (1) OK class VThreadStackRefTest$VThreadUnmountedJNIReferenced: ref count = 0 (expected 0), thread id = 0 (expected 0)
[2023-11-07T23:35:32.182Z]   (2) OK class VThreadStackRefTest$VThreadMountedReferenced: ref count = 1 (expected 1), thread id = 29 (expected 29)
[2023-11-07T23:35:32.182Z]   (3) ERROR class VThreadStackRefTest$VThreadMountedJNIReferenced: ref count = 1 (expected 1), thread id = 0 (expected 29)
[2023-11-07T23:35:32.182Z]   (4) OK class VThreadStackRefTest$PThreadReferenced: ref count = 1 (expected 1), thread id = 30 (expected 30)
[2023-11-07T23:35:32.182Z]   (5) OK class VThreadStackRefTest$VThreadUnmountedEnded: ref count = 0 (expected 0), thread id = 0 (expected 0)
[2023-11-07T23:35:32.182Z] STDERR:
[2023-11-07T23:35:32.182Z] java.lang.RuntimeException: Test failed
[2023-11-07T23:35:32.182Z] 	at VThreadStackRefTest.main(VThreadStackRefTest.java:192)
[2023-11-07T23:35:32.182Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-11-07T23:35:32.182Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-11-07T23:35:32.183Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-11-07T23:35:32.183Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-11-07T23:35:32.183Z] 
[2023-11-07T23:35:32.183Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed

[2023-11-07T23:35:32.183Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Test failed
[2023-11-07T23:35:32.183Z] --------------------------------------------------
[2023-11-07T23:36:31.171Z] Test results: passed: 153; failed: 2
[2023-11-07T23:36:34.748Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2023-11-07T23:36:34.748Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16993997562927/serviceability_jvmti_j9_0/work
[2023-11-07T23:36:34.748Z] Error: Some tests failed or other problems occurred.
[2023-11-07T23:36:34.748Z] -----------------------------------
[2023-11-07T23:36:34.748Z] serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35921/)

[JDK21 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/12/)
[JDK21 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_mac/13/)

**Comment by fengxue-IS** [comment]
Cause of this failure is #18394, the code `jvmtiHeapFollowRefs_getStackData` depends on `iteratorData->referrer` to set to proper value in `e->refInfo.jni_local.thread_id`. while the fix in #18394 fixed issue where internal pointer in referrer field may be exposed to user code, it also removed ways to trace back to the thread that hold the JNI local.

This is not a regression but legacy issue with OpenJ9's impl of reference chain walker. moving this issue out of 0.42.
This should be fixed as part of #18416

**Comment by pshipton** [comment]
@fengxue-IS there isn't much point moving it to 0.43, it has almost the same time frame as 0.42. Moving it to 0.44.

**Comment by pshipton** [comment]
@fengxue-IS @babsingh these tests should be excluded so they are not failing in every build.
serviceability/jvmti/vthread/FollowReferences/VThreadStackRefTest.java#default
serviceability/jvmti/vthread/FollowReferences/VThreadStackRefTest.java#no-vmcontinuations

**Comment by babsingh** [comment]
> these tests should be excluded so they are not failing in every build.

Opened https://github.com/adoptium/aqa-tests/pull/4937 to exclude the test.

**Comment by babsingh** [comment]
@fengxue-IS What's the update on https://github.com/eclipse-openj9/openj9/issues/18416? Since this is a legacy issue, it doesn't block the current release. Do you agree on moving this issue to the 0.48 release?

**Comment by fengxue-IS** [comment]
> @fengxue-IS What's the update on #18416? Since this is a legacy issue, it doesn't block the current release. Do you agree on moving this issue to the 0.48 release?

There was a prototype completed #18864, but the initial testing was flaky, so kept deferring until the test becomes stable.
This doesn't affect anything in the current release, I agree we can move it to 0.48
