### ISSUE TITLE
jdk_security_infra_0_FAILED NullPointerException: Cannot invoke "java.security.cert.X509Certificate.getSubjectX500Principal()" because "this.rootCertificate" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18447]
Failure link
------------

From [an internal build]()(`https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/135/`):
```
java version "17.0.10-beta" 2024-01-16
IBM Semeru Runtime Certified Edition 17.0.10+2-202311111534 (build 17.0.10-beta+2-202311111534)
Eclipse OpenJ9 VM 17.0.10+2-202311111534 (build master-f1d8ad75f, JRE 17 Linux aarch64-64-Bit Compressed References 20231111_524 (JIT enabled, AOT enabled)
OpenJ9   - f1d8ad75f
OMR      - 9bc6e08c9
JCL      - eaba573278 based on jdk-17.0.10+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security_infra_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F524%2Fibm-semeru-certified-jdk_aarch64_linux_JDK17U_2023-11-11-15-31.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F524%2Fibm-semeru-certified-testimage_aarch64_linux_JDK17U_2023-11-11-15-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-11-11T19:56:06.157Z] variation: Mode150
[2023-11-11T19:56:06.157Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-11-11T19:56:33.750Z] TEST: security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#affirmtrustnetworkingca

[2023-11-11T19:56:33.752Z] STDERR:
[2023-11-11T19:56:33.752Z] java.lang.NullPointerException: Cannot invoke "java.security.cert.X509Certificate.getSubjectX500Principal()" because "this.rootCertificate" is null
[2023-11-11T19:56:33.752Z] 	at ValidatePathWithURL.<init>(ValidatePathWithURL.java:64)
[2023-11-11T19:56:33.752Z] 	at CAInterop.validate(CAInterop.java:619)
[2023-11-11T19:56:33.752Z] 	at CAInterop.main(CAInterop.java:564)
[2023-11-11T19:56:33.752Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-11T19:56:33.752Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-11-11T19:56:33.752Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-11T19:56:33.752Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-11-11T19:56:33.752Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-11-11T19:56:33.752Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-11-11T19:56:33.752Z] 
[2023-11-11T19:56:33.752Z] JavaTest Message: Test threw exception: java.lang.NullPointerException: Cannot invoke "java.security.cert.X509Certificate.getSubjectX500Principal()" because "this.rootCertificate" is null
[2023-11-11T19:56:33.752Z] JavaTest Message: shutting down test

[2023-11-11T19:57:54.592Z] jdk_security_infra_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36012/) - all failed

[JDK17 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/135/)
[JDK17 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/142/)

[RI JDK17 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36013/) - failed as well

**Comment by JasonFengJ9** [comment]
[JDK11 aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_mac/102/)
```
java version "11.0.22-beta" 2024-01-16
IBM Semeru Runtime Certified Edition 11.0.22+4-202311250206 (build 11.0.22-beta+4-202311250206)
Eclipse OpenJ9 VM 11.0.22+4-202311250206 (build master-e89fd87bb, JRE 11 Mac OS X aarch64-64-Bit 20231124_435 (JIT enabled, AOT enabled)
OpenJ9   - e89fd87bb
OMR      - 8b19b8082
JCL      - 82742a9898 based on jdk-11.0.22+4)

[2023-11-25T02:57:04.848Z] STDERR:
[2023-11-25T02:57:04.848Z] java.lang.NullPointerException
[2023-11-25T02:57:04.848Z] 	at ValidatePathWithURL.<init>(ValidatePathWithURL.java:64)
[2023-11-25T02:57:04.848Z] 	at CAInterop.validate(CAInterop.java:631)
[2023-11-25T02:57:04.848Z] 	at CAInterop.main(CAInterop.java:576)
[2023-11-25T02:57:04.848Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-25T02:57:04.848Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-11-25T02:57:04.848Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-25T02:57:04.848Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2023-11-25T02:57:04.848Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-11-25T02:57:04.848Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-11-25T02:57:04.848Z] 
[2023-11-25T02:57:04.848Z] JavaTest Message: Test threw exception: java.lang.NullPointerException

[2023-11-25T02:57:12.680Z] jdk_security_infra_1_FAILED
```

**Comment by pshipton** [comment]
@KostasTsiounis @jasonkatonica this needs investigation

**Comment by KostasTsiounis** [comment]
The failing test is `CAInterop`, which was introduced as part of [this commit](https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/126f54608883229057a2b4676ca2433b57b37d45). 

Said test substitutes a number of tests that had hard-coded certificates to test. The new test loads the certificates from the `cacerts` file and tries to then retrieve them from the created `KeyStore`.

The certificates examined, and expected to be in the `KeyStore`, are the `OpenJDK` certificates. However, the `Semeru Certified Edition` contains a different set of `Adoptium` certificates derived from `Mozilla` certificates, as @pshipton informed me. So, when the test tries to `cacerts.getCertificate(alias)`, the result is null, leading to the produced `NullPointerException`.

This was verified by substituting the `cacerts` file with one created through an `OpenJ9` build, which led to the test succeeding.

**Comment by KostasTsiounis** [comment]
@pshipton What do you think our next steps should be?

**Comment by pshipton** [comment]
@LongyuZhang @sophia-guo what is Adoptium doing about all these failing security_infra tests?

**Comment by llxia** [comment]
Same failure in jdk_security_infra at Adoptium on Dec 25th, 2023:
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_1/45/tapResults/

From what I can see, the last green extended.openjdk on aarch64_linux was on Sep 1st, 2023: https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/

**Comment by KostasTsiounis** [comment]
@llxia The `CAInterop` test was added on the upstream on September 28, 2023.

**Comment by pshipton** [comment]
This should be resolved via https://github.com/adoptium/aqa-tests/pull/4955, or an OpenJ9 update derived from it.

**Comment by macarte** [comment]
We just tested 21 as we also had this issue.

I don't know the background on why we've been generating the cacerts file and replacing the one thats built by default, however if you run the tests with the default cacert then the tests pass (we confirmed that the alias being searched for is in the default cacert file and not the one generated from the mozilla source

I don't know (again because of the background) which cacert file (if any) would be needed for TCK
