### ISSUE TITLE
OpenJDK java/lang/Thread/virtual/stress/ParkALot.java#id0 timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18444]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/96/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/96/

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/96/openjdk_test_output.tar.gz
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/96/openjdk_test_output.tar.gz

java/lang/Thread/virtual/stress/ParkALot.java#id0
Showing selected threads from the timeout:
```
19:24:15  "ForkJoinPool-1-worker-2" prio=5 Id=31 WAITING
19:24:15  	at java.base@21.0.1-internal/jdk.internal.vm.Continuation.run(Continuation.java:213)
19:24:15  	at java.base@21.0.1-internal/java.lang.VirtualThread.runContinuation(VirtualThread.java:239)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

19:24:15  "ForkJoinPool-1-worker-4" prio=5 Id=33 BLOCKED on java.lang.Object@1cff76f4 owned by "Thread-5" Id=43
19:24:15  	at java.base@21.0.1-internal/java.lang.VirtualThread.unmount(VirtualThread.java:388)
19:24:15  	at java.base@21.0.1-internal/java.lang.VirtualThread.runContinuation(VirtualThread.java:241)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

19:24:15  "ForkJoinPool-1-worker-7" prio=5 Id=40 WAITING
19:24:15  	at java.base@21.0.1-internal/jdk.internal.vm.Continuation.run(Continuation.java:213)
19:24:15  	at java.base@21.0.1-internal/java.lang.VirtualThread.runContinuation(VirtualThread.java:239)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

19:24:15  "Thread-4" prio=5 Id=42 RUNNABLE
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.getStateImpl(Native Method)
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.threadState(Thread.java:2794)
19:24:15  	- locked java.lang.Object@bd52e5b2
19:24:15  	at java.base@21.0.1-internal/java.lang.VirtualThread.threadState(VirtualThread.java:906)
19:24:15  	- locked java.lang.Object@4133e156
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.getState(Thread.java:2778)
19:24:15  	at app//ParkALot.parkALot(ParkALot.java:86)
19:24:15  	at app//ParkALot.lambda$main$0(ParkALot.java:59)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.FutureTask.run(FutureTask.java:317)
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.run(Thread.java:1595)
19:24:15  
19:24:15  "Thread-5" prio=5 Id=43 RUNNABLE
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.getStateImpl(Native Method)
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.threadState(Thread.java:2794)
19:24:15  	- locked java.lang.Object@d6fbbc8d
19:24:15  	at java.base@21.0.1-internal/java.lang.VirtualThread.threadState(VirtualThread.java:906)
19:24:15  	- locked java.lang.Object@1cff76f4
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.getState(Thread.java:2778)
19:24:15  	at app//ParkALot.parkALot(ParkALot.java:86)
19:24:15  	at app//ParkALot.lambda$main$0(ParkALot.java:59)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.FutureTask.run(FutureTask.java:317)
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.run(Thread.java:1595)
19:24:15  
19:24:15  "Thread-6" prio=5 Id=44 RUNNABLE
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.getStateImpl(Native Method)
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.threadState(Thread.java:2794)
19:24:15  	- locked java.lang.Object@5d1d0081
19:24:15  	at java.base@21.0.1-internal/java.lang.VirtualThread.threadState(VirtualThread.java:906)
19:24:15  	- locked java.lang.Object@80b77f44
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.getState(Thread.java:2778)
19:24:15  	at app//ParkALot.parkALot(ParkALot.java:86)
19:24:15  	at app//ParkALot.lambda$main$0(ParkALot.java:59)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
19:24:15  	at java.base@21.0.1-internal/java.util.concurrent.FutureTask.run(FutureTask.java:317)
19:24:15  	at java.base@21.0.1-internal/java.lang.Thread.run(Thread.java:1595)
```

https://github.com/eclipse-openj9/openj9/compare/2dc399ecf92...881ab737394
https://github.com/eclipse-openj9/openj9-omr/compare/2a9a7f4e479...9bc6e08c92f
https://github.com/ibmruntimes/openj9-openjdk-jdk21/compare/f8d29432229...88ac736b09c

**Comment by pshipton** [comment]
@fengxue-IS @babsingh @tajila fyi

**Comment by JasonFengJ9** [comment]
Also observed at internal builds: [JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_testList_1/45/) [JDK21 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_testList_0/51/)

**Comment by babsingh** [comment]
It's a new test introduced in https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/8f677c4d68d34de89d7dd25986fc65ab35f714cd.

It launches num_threads and expects each thread to park 500_000 times. The test just takes a lot of time, which causes the timeout. The test passes in a reasonable time when the number of iterations are reduced to 5_000, which should be sufficient to verify functional behaviour.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_OMR_testList_1/43/

@babsingh are you planning to modify the test to avoid the timeouts in our regular testing?

**Comment by babsingh** [comment]
> are you planning to modify the test to avoid the timeouts in our regular testing?

Yes, opened the below PRs to address the timeout:
- JDK21: https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/60
- JDK-next: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/690

**Comment by babsingh** [comment]
The two PRs, mentioned in https://github.com/eclipse-openj9/openj9/issues/18444#issuecomment-1809178447, have been merged. Closing this issue since the two PRs should resolve this issue.
