### ISSUE TITLE
[win_x86-64_cmprssptrs] SE80_GIT cmdLineTest_J9test_elapsedTime_0 FAILED: testElapsedTime() wait 100ms elapsedNanoTimeInMillis (96ms) should NOT be less than minElapsedNanoTimeInMillis (100ms)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18456]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=71866746)(`win10x64hv4`):
```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pwa6480sr9-20231020_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20231115_60684 (JIT enabled, AOT enabled)
OpenJ9   - 2c09e49
OMR      - 275683f
IBM      - 7394519)
JCL - 20231012_01 based on Oracle jdk8u391-b13
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
*** Starting test suite: Elapsed time measurement ***
Testing: Verify the elapsed time
Test start time: 2023/11/15 12:58:44 Eastern Standard Time
Running command: "w:\builds\bld_60684/sdk/wa6480\bin\java"   -cp "w:\builds\bld_60684/jvmtest/test/SE80\TKG\lib\testng.jar;w:\builds\bld_60684/jvmtest/test/SE80\TKG\lib\jcommander.jar;w:\builds\bld_60684/jvmtest/test/SE80\functional\cmdLineTests\cmdLineTest_J9tests\cmdLineTest_J9tests.jar" ElapsedTime
Time spent starting: 0 milliseconds
Time spent executing: 687 milliseconds
Test result: FAILED
Output from test:
 [OUT] testElapsedTime() wait 100ms checkElapseTime starts, current thread name: main, Wed Nov 15 12:58:45 EST 2023, System.currentTimeMillis() 1700071125124, System.nanoTime() 48178442313900
 [OUT] testElapsedTime() wait 100ms: startMillisTime (1700071124983ms) startNanoTime (48178310655000ns) currentMillisTime (1700071125093ms) currentNanoTime (48178406061500ns) elapsedMillisTime (110ms) elapsedNanoTime (95406500ns)
 [OUT] FAILED: testElapsedTime() wait 100ms elapsedNanoTimeInMillis (96ms) should NOT be less than minElapsedNanoTimeInMillis (100ms)
 [OUT] testElapsedTime() wait 100ms checkElapseTime ends, current thread name: main, Wed Nov 15 12:58:45 EST 2023, System.currentTimeMillis() 1700071125124, System.nanoTime() 48178442924500
 [ERR] Exception in thread "main" java.lang.AssertionError: 
 [ERR] at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
 [ERR] at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
 [ERR] at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
 [ERR] at ElapsedTime.testElapsedTime(ElapsedTime.java:44)
 [ERR] at ElapsedTime.main(ElapsedTime.java:32)
>> Success condition was not found: [Output match: Thread-0]
>> Success condition was not found: [Output match: PASSED: testElapsedTime]
>> Failure condition was found: [Output match: FAILED: testElapsedTime]


---TEST RESULTS---
Number of PASSED tests: 0 out of 1
Number of FAILED tests: 1 out of 1

---SUMMARY OF FAILED TESTS---
Verify the elapsed time
```

[100x internal grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=60694)
[10x internal grinder on same machine](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=60695)

**Comment by pshipton** [comment]
This is failing in every version, Windows 64-bit.

**Comment by JasonFengJ9** [comment]
`Object.wait(timeout)` could be spurious wakeup, will modify the testcae.

**Comment by tajila** [comment]
@JasonFengJ9 Please disable all the failing tests for now.

**Comment by tajila** [comment]
We should probably run the tests in grinders on all platforms before enabling from now

**Comment by pshipton** [comment]
It's just the one test that fails. I've only seen it on Win 64-bit.

**Comment by pshipton** [comment]
Found one on [Win 32-bit](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=71949833)
