### ISSUE TITLE
[win_x86] SE80_GIT cmdLineTest_J9test_elapsedTime_0 FAILED: testElapsedTime() timer delayed 2s elapsedNanoTimeInMillis (1990ms) should NOT be less than minElapsedNanoTimeInMillis (2000ms)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18475]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=72014147)(`win10x64rtp-5-1`):
```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pwi3280sr9-20231020_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows Server 2019 x86-32-Bit 20231117_60790 (JIT enabled, AOT enabled)
OpenJ9   - 799f2ac
OMR      - 5b72530
IBM      - 7394519)
JCL - 20231012_01 based on Oracle jdk8u391-b13
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
*** Starting test suite: Elapsed time measurement ***
Testing: Verify the elapsed time
Test start time: 2023/11/17 06:03:35 Eastern Standard Time
Running command: "w:\builds\bld_60790/sdk/wi3280\bin\java"   -cp "w:\builds\bld_60790/jvmtest/test/SE80\TKG\lib\testng.jar;w:\builds\bld_60790/jvmtest/test/SE80\TKG\lib\jcommander.jar;w:\builds\bld_60790/jvmtest/test/SE80\functional\cmdLineTests\cmdLineTest_J9tests\cmdLineTest_J9tests.jar" ElapsedTime
Time spent starting: 31 milliseconds
Time spent executing: 3406 milliseconds
Test result: FAILED
Output from test:
 [OUT] testElapsedTime() sleep 100ms checkElapseTime starts, current thread name: main, Fri Nov 17 06:03:36 EST 2023, System.currentTimeMillis() 1700219016625, System.nanoTime() 101960152000040
 [OUT] testElapsedTime() sleep 100ms: startMillisTime (1700219016453ms) startNanoTime (101959983631940ns) currentMillisTime (1700219016562ms) currentNanoTime (101960083715350ns) elapsedMillisTime (109ms) elapsedNanoTime (100083410ns)
 [OUT] testElapsedTime() sleep 100ms checkElapseTime ends, current thread name: main, Fri Nov 17 06:03:36 EST 2023, System.currentTimeMillis() 1700219016625, System.nanoTime() 101960152627730
 [OUT] getResultAndCancelTimers before Thread.yield() taskRunning = 2, current thread name: main, Fri Nov 17 06:03:36 EST 2023, System.currentTimeMillis() 1700219016625, System.nanoTime() 101960157575830
 [OUT] testElapsedTime() timer delayed 100ms checkElapseTime starts, current thread name: testElapsedTime() timer delayed 100ms, Fri Nov 17 06:03:36 EST 2023, System.currentTimeMillis() 1700219016734, System.nanoTime() 101960255752310
 [OUT] testElapsedTime() timer delayed 100ms: startMillisTime (1700219016625ms) startNanoTime (101960155440420ns) currentMillisTime (1700219016734ms) currentNanoTime (101960255577340ns) elapsedMillisTime (109ms) elapsedNanoTime (100136920ns)
 [OUT] testElapsedTime() timer delayed 100ms checkElapseTime ends, current thread name: testElapsedTime() timer delayed 100ms, Fri Nov 17 06:03:36 EST 2023, System.currentTimeMillis() 1700219016734, System.nanoTime() 101960256330930
 [OUT] testElapsedTime() timer delayed 2s checkElapseTime starts, current thread name: testElapsedTime() timer delayed 2s, Fri Nov 17 06:03:38 EST 2023, System.currentTimeMillis() 1700219018625, System.nanoTime() 101962146428380
 [OUT] testElapsedTime() timer delayed 2s: startMillisTime (1700219016625ms) startNanoTime (101960157046250ns) currentMillisTime (1700219018625ms) currentNanoTime (101962146232550ns) elapsedMillisTime (2000ms) elapsedNanoTime (1989186300ns)
 [OUT] FAILED: testElapsedTime() timer delayed 2s elapsedNanoTimeInMillis (1990ms) should NOT be less than minElapsedNanoTimeInMillis (2000ms)
 [OUT] testElapsedTime() timer delayed 2s checkElapseTime ends, current thread name: testElapsedTime() timer delayed 2s, Fri Nov 17 06:03:38 EST 2023, System.currentTimeMillis() 1700219018625, System.nanoTime() 101962147972470
 [OUT] getResultAndCancelTimers before timer.cancel(), current thread name: main, Fri Nov 17 06:03:38 EST 2023, System.currentTimeMillis() 1700219018625, System.nanoTime() 101962148382000
 [OUT] TimeTestTask tasksPassed: false, taskStarted: 2, taskExecuted: 2, current thread name: main, Fri Nov 17 06:03:38 EST 2023, System.currentTimeMillis() 1700219018625, System.nanoTime() 101962148982370
 [ERR] Exception in thread "main" java.lang.AssertionError: 
 [ERR] at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
 [ERR] at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
 [ERR] at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
 [ERR] at ElapsedTime.testElapsedTime(ElapsedTime.java:56)
 [ERR] at ElapsedTime.main(ElapsedTime.java:32)
>> Success condition was not found: [Output match: Thread-0]
>> Success condition was not found: [Output match: PASSED: testElapsedTime]
>> Failure condition was found: [Output match: FAILED: testElapsedTime]


---TEST RESULTS---
Number of PASSED tests: 0 out of 1
Number of FAILED tests: 1 out of 1

---SUMMARY OF FAILED TESTS---
Verify the elapsed time
```

[10x internal grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=60794)

**Comment by pshipton** [comment]
cmdLineTest_J9test_elapsedTime fails in every build on 1-3 Win platforms. I set the failures to passed.

**Comment by JasonFengJ9** [comment]
Closing as dup of 
* https://github.com/eclipse-openj9/openj9/issues/18487
