### ISSUE TITLE
jdk_nio_0_FAILED java/nio/channels/Pipe/PipeInterrupt.java java.lang.InterruptedException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18479]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/144/)(`win11x86-svl-rt8-1`):
```
java version "11.0.21" 2023-10-17
IBM Semeru Runtime Certified Edition 11.0.21.0-rc2 (build 11.0.21+9)
Eclipse OpenJ9 VM 11.0.21.0-rc2 (build v0.41.0-release-a803f004b, JRE 11 Windows 11 amd64-64-Bit Compressed References 20231116_698 (JIT enabled, AOT enabled)
OpenJ9   - a803f004b
OMR      - 5eee6ad9d
JCL      - 6f4cc08025 based on jdk-11.0.21+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_nio_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F698%2Fibm-semeru-certified-jdk_x64_windows_11.0.21.0-rc2.zip+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x64-openj9-IBM%2F698%2Fibm-semeru-certified-testimage_x64_windows_11.0.21.0-rc2.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v0.9.9-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.41.0-release&amp;OPENJ9_BRANCH=v0.41.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.41.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-11-16T13:33:00.084Z] variation: Mode150
[2023-11-16T13:33:01.026Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-11-16T13:47:16.172Z] TEST: java/nio/channels/Pipe/PipeInterrupt.java

[2023-11-16T13:47:16.173Z] STDERR:
[2023-11-16T13:47:16.173Z] java.lang.InterruptedException
[2023-11-16T13:47:16.173Z] 	at java.base/java.lang.Object.waitImpl(Native Method)
[2023-11-16T13:47:16.173Z] 	at java.base/java.lang.Object.wait(Object.java:251)
[2023-11-16T13:47:16.173Z] 	at java.base/java.lang.Object.wait(Object.java:219)
[2023-11-16T13:47:16.173Z] 	at java.base/java.lang.Thread.join(Thread.java:766)
[2023-11-16T13:47:16.173Z] 	at java.base/java.lang.Thread.join(Thread.java:721)
[2023-11-16T13:47:16.173Z] 	at PipeInterrupt.test(PipeInterrupt.java:78)
[2023-11-16T13:47:16.173Z] 	at PipeInterrupt.main(PipeInterrupt.java:41)
[2023-11-16T13:47:16.173Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-16T13:47:16.173Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-11-16T13:47:16.173Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-16T13:47:16.173Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-11-16T13:47:16.173Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2023-11-16T13:47:16.173Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2023-11-16T13:47:16.173Z] 
[2023-11-16T13:47:16.173Z] JavaTest Message: Test threw exception: java.lang.InterruptedException
[2023-11-16T13:47:16.173Z] JavaTest Message: shutting down test
[2023-11-16T13:47:16.173Z] 
[2023-11-16T13:47:16.173Z] 
[2023-11-16T13:47:16.173Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.InterruptedException
[2023-11-16T13:47:16.173Z] --------------------------------------------------
[2023-11-16T14:17:25.269Z] Test results: passed: 378; failed: 1
[2023-11-16T14:18:16.009Z] Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_17001335617472\jdk_nio_0\report\html\report.html
[2023-11-16T14:18:16.009Z] Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_17001335617472\jdk_nio_0\work
[2023-11-16T14:18:16.009Z] Error: Some tests failed or other problems occurred.
[2023-11-16T14:18:16.009Z] -----------------------------------
[2023-11-16T14:18:16.009Z] jdk_nio_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36199/)

**Comment by JasonFengJ9** [comment]
[JDK17 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_5/2/)(`win10x86-svl-rt1-1`)
```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0-m1 (build 17.0.10+5)
Eclipse OpenJ9 VM 17.0.10.0-m1 (build v0.43.0-release-9b2a42f8f, JRE 17 Windows 10 amd64-64-Bit Compressed References 20240116_576 (JIT enabled, AOT enabled)
OpenJ9   - 9b2a42f8f
OMR      - d810fcb98
JCL      - 10ccdceee3c based on jdk-17.0.10+5)

[2023-12-02T22:23:14.104Z] variation: Mode650
[2023-12-02T22:23:14.491Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2023-12-02T23:16:45.093Z] TEST: java/nio/channels/Pipe/PipeInterrupt.java

[2023-12-02T23:16:45.095Z] STDERR:
[2023-12-02T23:16:45.095Z] java.lang.InterruptedException
[2023-12-02T23:16:45.095Z] 	at java.base/java.lang.Object.waitImpl(Native Method)
[2023-12-02T23:16:45.095Z] 	at java.base/java.lang.Object.wait(Object.java:251)
[2023-12-02T23:16:45.095Z] 	at java.base/java.lang.Object.wait(Object.java:219)
[2023-12-02T23:16:45.095Z] 	at java.base/java.lang.Thread.join(Thread.java:784)
[2023-12-02T23:16:45.095Z] 	at java.base/java.lang.Thread.join(Thread.java:739)
[2023-12-02T23:16:45.095Z] 	at PipeInterrupt.test(PipeInterrupt.java:78)
[2023-12-02T23:16:45.095Z] 	at PipeInterrupt.main(PipeInterrupt.java:41)

[2023-12-02T23:16:45.095Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.InterruptedException
[2023-12-02T23:16:45.096Z] --------------------------------------------------
[2023-12-03T01:17:09.410Z] Test results: passed: 439; failed: 1
[2023-12-03T01:17:58.848Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_5\aqa-tests\TKG\output_17015556668426\jdk_nio_1\report\html\report.html
[2023-12-03T01:17:58.848Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_extended.openjdk_x86-64_windows_testList_5\aqa-tests\TKG\output_17015556668426\jdk_nio_1\work
[2023-12-03T01:17:58.848Z] Error: Some tests failed or other problems occurred.
[2023-12-03T01:17:58.848Z] -----------------------------------
[2023-12-03T01:17:58.848Z] jdk_nio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK8 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/126/)(`win19x64-fips1-1`)
```
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b04)
Eclipse OpenJ9 VM (build v0.43.0-release-579b3f8e0, JRE 1.8.0 Windows Server 2019 amd64-64-Bit Compressed References 20231204_831 (JIT enabled, AOT enabled)
OpenJ9   - 579b3f8e0
OMR      - d810fcb98
JCL      - 68dbd3149c based on jdk8u402-b04)

[2023-12-05T04:15:45.974Z] TEST: java/nio/channels/Pipe/PipeInterrupt.java

[2023-12-05T04:15:45.976Z] STDERR:
[2023-12-05T04:15:45.976Z] java.lang.InterruptedException
[2023-12-05T04:15:45.976Z] 	at java.lang.Object.waitImpl(Native Method)
[2023-12-05T04:15:45.976Z] 	at java.lang.Object.wait(Object.java:248)
[2023-12-05T04:15:45.976Z] 	at java.lang.Object.wait(Object.java:216)
[2023-12-05T04:15:45.976Z] 	at java.lang.Thread.join(Thread.java:753)
[2023-12-05T04:15:45.976Z] 	at java.lang.Thread.join(Thread.java:708)
[2023-12-05T04:15:45.976Z] 	at PipeInterrupt.test(PipeInterrupt.java:78)
[2023-12-05T04:15:45.976Z] 	at PipeInterrupt.main(PipeInterrupt.java:41)

[2023-12-05T05:09:31.476Z] jdk_nio_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36702/)

**Comment by JasonFengJ9** [comment]
[JDK8 x86-32_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-32_windows/143/)

**Comment by JasonFengJ9** [comment]
[JDK8 x86-32_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-32_windows_testList_2/12/)(`win19x86-svl-rt2-1`)
```
[2024-03-22T02:05:31.314Z] variation: Mode1000
[2024-03-22T02:05:31.314Z] JVM_OPTIONS:  -Xverbosegclog 

[2024-03-22T02:22:57.476Z] TEST: java/nio/channels/Pipe/PipeInterrupt.java

[2024-03-22T02:22:57.477Z] STDERR:
[2024-03-22T02:22:57.477Z] java.lang.InterruptedException
[2024-03-22T02:22:57.477Z] 	at java.lang.Object.waitImpl(Native Method)
[2024-03-22T02:22:57.477Z] 	at java.lang.Object.wait(Object.java:248)
[2024-03-22T02:22:57.477Z] 	at java.lang.Object.wait(Object.java:216)
[2024-03-22T02:22:57.477Z] 	at java.lang.Thread.join(Thread.java:753)
[2024-03-22T02:22:57.477Z] 	at java.lang.Thread.join(Thread.java:708)
[2024-03-22T02:22:57.477Z] 	at PipeInterrupt.test(PipeInterrupt.java:78)
[2024-03-22T02:22:57.477Z] 	at PipeInterrupt.main(PipeInterrupt.java:41)

[2024-03-22T02:22:57.477Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.InterruptedException
[2024-03-22T02:22:57.477Z] --------------------------------------------------
[2024-03-22T03:05:00.532Z] Test results: passed: 327; failed: 1
[2024-03-22T03:05:12.245Z] Report written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows_testList_2\aqa-tests\TKG\output_17110707232673\jdk_nio_2\report\html\report.html
[2024-03-22T03:05:12.245Z] Results written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows_testList_2\aqa-tests\TKG\output_17110707232673\jdk_nio_2\work
[2024-03-22T03:05:12.245Z] Error: Some tests failed or other problems occurred.
[2024-03-22T03:05:12.245Z] -----------------------------------
[2024-03-22T03:05:12.245Z] jdk_nio_2_FAILED
```

@llxia @annaibm could you help to exclude this test for all Java versions on the Windows platform?

**Comment by annaibm** [comment]
PR for excluding `java/nio/channels/Pipe/PipeInterrupt.java` for all Java versions on the Windows platform
[aqa-tests/pull#5182](https://github.com/adoptium/aqa-tests/pull/5182)
