### ISSUE TITLE
FIPS javax/sql/testng/test/rowset/RowSetProviderTests.java RowSetProviderTests should have thrown an exception of type class java.sql.SQLException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18478]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux_fips140_2/16/)(`rhel8x86-svl-rtfips5-1`):
```
openjdk version "1.8.0_392"
IBM Semeru Runtime Open Edition (build 1.8.0_392-b08)
Eclipse OpenJ9 VM (build v0.41.0-release-a803f004b, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20231116_805 (JIT enabled, AOT enabled)
OpenJ9   - a803f004b
OMR      - 5eee6ad9d
JCL      - b73cbdd342 based on jdk8u392-b08)
```
[Rerun in Grinder]([Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_other_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=FIPS140_2&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F805%2Fibm-semeru-open-jdk_x64_linux_8u392b08_openj9-0.41.0-rc2.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F805%2Fibm-semeru-open-testimage_x64_linux_8u392b08_openj9-0.41.0-rc2.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v0.9.9-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.41.0-release&amp;OPENJ9_BRANCH=v0.41.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.41.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None)) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-11-16T08:23:49.314Z] variation: Mode650
[2023-11-16T08:23:49.314Z] JVM_OPTIONS:  -XX:-UseCompressedOops  -Dsemeru.fips=true

[2023-11-16T08:27:53.961Z] TEST: javax/sql/testng/test/rowset/RowSetProviderTests.java

[2023-11-16T08:27:53.962Z] config util.BaseTest.setUpMethod(): success
[2023-11-16T08:27:53.962Z] test test.rowset.RowSetProviderTests.test05(): failure
[2023-11-16T08:27:53.962Z] org.testng.TestException: 
[2023-11-16T08:27:53.962Z] Method RowSetProviderTests.test05()[pri:0, instance:test.rowset.RowSetProviderTests@de4ca1a3] should have thrown an exception of type class java.sql.SQLException
[2023-11-16T08:27:53.962Z] 	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
[2023-11-16T08:27:53.962Z] 	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1384)
[2023-11-16T08:27:53.962Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:677)
[2023-11-16T08:27:53.962Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2023-11-16T08:27:53.962Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2023-11-16T08:27:53.962Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-11-16T08:27:53.962Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2023-11-16T08:27:53.962Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2023-11-16T08:27:53.962Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2023-11-16T08:27:53.962Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2023-11-16T08:27:53.962Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2023-11-16T08:27:53.962Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2023-11-16T08:27:53.962Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2023-11-16T08:27:53.962Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-11-16T08:27:53.962Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2023-11-16T08:27:53.962Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2023-11-16T08:27:53.962Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2023-11-16T08:27:53.962Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2023-11-16T08:27:53.962Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2023-11-16T08:27:53.962Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2023-11-16T08:27:53.962Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-16T08:27:53.962Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-11-16T08:27:53.962Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-16T08:27:53.962Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-11-16T08:27:53.962Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-11-16T08:27:53.962Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-11-16T08:27:53.963Z] config test.rowset.RowSetProviderTests.tearDownMethod(): success
[2023-11-16T08:27:53.963Z] config test.rowset.RowSetProviderTests.tearDownClass(): success
[2023-11-16T08:27:53.963Z] 
[2023-11-16T08:27:53.963Z] ===============================================
[2023-11-16T08:27:53.963Z] javax/sql/testng/test/rowset/RowSetProviderTests.java
[2023-11-16T08:27:53.963Z] Total tests run: 9, Failures: 1, Skips: 0

[2023-11-16T08:38:42.586Z] jdk_other_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36194/)

**Comment by pshipton** [comment]
I'm not sure why this is just being called out now. I checked RC1 and M2 and it was failing there as well. Running a grinder on 0.40 shows it also occurs there.

FYI the failure reproduces when running just the single test.

**Comment by JasonFengJ9** [comment]
Initially, I thought this was another manifestation of 
* https://github.com/eclipse-openj9/openj9/issues/18039

The test in question `RowSetProviderTests` doesn't seem related to NoSuchAlgorithmException/Provider.

@jasonkatonica any insights?

**Comment by KostasTsiounis** [comment]
The test uses a `URLClassLoader` to get the implementation for `RowSetFactory` to be loaded. In this test, the implementation is a non-existing class, namely `invalid.RowSetFactoryImpl`. 

When calling `RowSetProvider.newFactory()` [here](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4b03d7952154c9f4b0dae25bde892165cb90ff80/jdk/test/javax/sql/testng/test/rowset/RowSetProviderTests.java#L153), it originally looks for a system property for available `ClassLoader`, but since one has not been set, it tries to find an instance of the factory through the `loadViaServiceLoader()` method, which can be found [here](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4b03d7952154c9f4b0dae25bde892165cb90ff80/jdk/src/share/classes/javax/sql/rowset/RowSetProvider.java#L270). 

This is turn calls the `ServiceLoader.load()` method and tries to iterate through the result. However, due to the `RestrictedSecurity` code added to check for allowed providers, the variable `pending` is set to an empty iterator [here](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4b03d7952154c9f4b0dae25bde892165cb90ff80/jdk/src/share/classes/java/util/ServiceLoader.java#L381). When a call to `pending.next()` is done [here](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4b03d7952154c9f4b0dae25bde892165cb90ff80/jdk/src/share/classes/java/util/ServiceLoader.java#L384), a `NoSuchElementException` is thrown. This is not the expected `SQLException`, which is why this test fails.

**Comment by JasonFengJ9** [comment]
Okay, this is indeed 
* https://github.com/eclipse-openj9/openj9/issues/18039

Thanks @KostasTsiounis for your quick response and analysis!
