### ISSUE TITLE
JDK21 Jep425Tests_testVirtualThread_0_FAILED NoSuchFieldException: TIMED_PARKING

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18481]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.functional_aarch64_linux_testList_1/49/)(`rhel9-aarch64-8`):
```
openjdk version "21.0.1" 2023-10-17 LTS
IBM Semeru Runtime Open Edition 21.0.1.0-m1 (build 21.0.1+12-LTS)
Eclipse OpenJ9 VM 21.0.1.0-m1 (build v0.42.0-release-df467094a, JRE 21 Linux aarch64-64-Bit Compressed References 20231017_35 (JIT enabled, AOT enabled)
OpenJ9   - df467094a
OMR      - d810fcb98
JCL      - f15a87536b1 based on jdk-21.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=Jep425Tests_testVirtualThread_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_sanity.functional_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-aarch64-openj9%2F35%2Fibm-semeru-open-jdk_aarch64_linux_21.0.1_12_openj9-0.42.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-aarch64-openj9%2F35%2Fibm-semeru-open-testimage_aarch64_linux_21.0.1_12_openj9-0.42.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.42.0-release&amp;OPENJ9_BRANCH=v0.42.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.42.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=50&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-11-16T15:52:40.167Z] variation: --enable-preview -Xgcpolicy:optthruput
[2023-11-16T15:52:40.167Z] JVM_OPTIONS:  --enable-preview -Xgcpolicy:optthruput 

[2023-11-16T15:52:47.763Z] FAILED: test_verifyJVMTIMacros
[2023-11-16T15:52:47.763Z] java.lang.AssertionError: Unexpected exception occured : TIMED_PARKING
[2023-11-16T15:52:47.763Z] 	at org.testng.Assert.fail(Assert.java:85)
[2023-11-16T15:52:47.763Z] 	at org.openj9.test.jep425.VirtualThreadTests.test_verifyJVMTIMacros(VirtualThreadTests.java:350)
[2023-11-16T15:52:47.763Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-11-16T15:52:47.763Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-11-16T15:52:47.763Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2023-11-16T15:52:47.763Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2023-11-16T15:52:47.763Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2023-11-16T15:52:47.763Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2023-11-16T15:52:47.763Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2023-11-16T15:52:47.763Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2023-11-16T15:52:47.763Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2023-11-16T15:52:47.763Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2023-11-16T15:52:47.763Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2023-11-16T15:52:47.763Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2023-11-16T15:52:47.763Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2023-11-16T15:52:47.763Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2023-11-16T15:52:47.763Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2023-11-16T15:52:47.763Z] Caused by: java.lang.NoSuchFieldException: TIMED_PARKING
[2023-11-16T15:52:47.763Z] 	at java.base/java.lang.Class.getDeclaredFieldInternal(Class.java:982)
[2023-11-16T15:52:47.763Z] 	at java.base/java.lang.Class.getDeclaredField(Class.java:957)
[2023-11-16T15:52:47.763Z] 	at org.openj9.test.jep425.VirtualThreadTests.readVirtualThreadStates(VirtualThreadTests.java:259)
[2023-11-16T15:52:47.763Z] 	at org.openj9.test.jep425.VirtualThreadTests.test_verifyJVMTIMacros(VirtualThreadTests.java:320)
[2023-11-16T15:52:47.763Z] 	... 22 more
[2023-11-16T15:52:47.763Z] 
[2023-11-16T15:52:47.763Z] 
[2023-11-16T15:52:47.763Z] ===============================================
[2023-11-16T15:52:47.763Z]     Jep425Tests_testVirtualThread
[2023-11-16T15:52:47.763Z]     Tests run: 7, Failures: 1, Skips: 0
[2023-11-16T15:52:47.763Z] ===============================================
[2023-11-16T15:52:47.763Z] 
[2023-11-16T15:52:47.763Z] 
[2023-11-16T15:52:47.763Z] ===============================================
[2023-11-16T15:52:47.763Z] Java21+ test suite
[2023-11-16T15:52:47.763Z] Total tests run: 7, Failures: 1, Skips: 0
[2023-11-16T15:52:47.763Z] ===============================================
[2023-11-16T15:52:47.763Z] 
[2023-11-16T15:52:48.810Z] -----------------------------------
[2023-11-16T15:52:48.810Z] Jep425Tests_testVirtualThread_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36232/) - all failed

**Comment by babsingh** [comment]
The build uses the [v0.42.0-release](https://github.com/ibmruntimes/openj9-openjdk-jdk21/tree/v0.42.0-release) branch of JDK21 extensions repo. The below backports should fix this failure:
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/72
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/73

**Comment by babsingh** [comment]
Closing since the backport PRs, mentioned in https://github.com/eclipse-openj9/openj9/issues/18481#issuecomment-1819552563, have been merged.
