### ISSUE TITLE
INLs natives do not support method enter/exit events

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18493]
`-Xtrace:print=mt,methods=java/lang/System.currentTimeMillis` doesn't produce any method enter/exit events, similar for other INLs.

A hack might work for temporary debugging purposes.
https://github.com/eclipse-openj9/openj9/blob/d881d0881d39a31d0dfe2c2cc1f077f42af80a32/runtime/vm/BytecodeInterpreter.hpp#L3089-L3096
Change it to:
```
	/* java.lang.System: public static native long currentTimeMillis(); */
	VMINLINE VM_BytecodeAction
	inlSystemCurrentTimeMillis(REGISTER_ARGS_LIST)
	{
		PORT_ACCESS_FROM_JAVAVM(_vm);
		returnDoubleFromINL(REGISTER_ARGS, j9time_current_time_millis(), 0);
#if defined(DO_HOOKS)
		return REPORT_METHOD_ENTER;
#else
		return EXECUTE_BYTECODE;
#endif
	}
```

Discussed with @gacholio, this was by design.

FYI @tajila

**Comment by tajila** [comment]
What is this needed for?

**Comment by JasonFengJ9** [comment]
This was required for the investigation
* https://github.com/eclipse-openj9/openj9/issues/18487

```
 [ERR] 03:38:08.144 0x221df300              mt.5        > java/lang/System.currentTimeMillis()J native static method
 [ERR] testElapsedTime() timer delayed 2s checkElapseTime starts, current thread name: testElapsedTime() timer delayed 2s, Sun Nov 19 19:38:08 PST 2023, System.currentTimeMillis() 1700451488144, System.nanoTime() 593640007550690
 [ERR] testElapsedTime() timer delayed 2s: startMillisTime (1700451486144ms) startNanoTime (593638013786980ns) currentMillisTime (1700451488144ms) currentNanoTime (593640007119350ns) elapsedMillisTime (2000ms) elapsedNanoTime (1993332370ns)
 [ERR] FAILED: testElapsedTime() timer delayed 2s elapsedNanoTimeInMillis (1994ms) should NOT be less than minElapsedNanoTimeInMillis (2000ms)
 [ERR] 03:38:08.144 0x221df300              mt.5        > java/lang/System.currentTimeMillis()J native static method
 [ERR] 03:38:08.144 0x221df300              mt.5        > java/lang/System.currentTimeMillis()J native static method
 [ERR] testElapsedTime() timer delayed 2s checkElapseTime ends, current thread name: testElapsedTime() timer delayed 2s, Sun Nov 19 19:38:08 PST 2023, System.currentTimeMillis() 1700451488144, System.nanoTime() 593640009075530
 [ERR] 03:38:08.144*0x220ba800              mt.5        > java/lang/System.currentTimeMillis()J native static method
 [ERR] 03:38:08.144 0x220ba800              mt.5        > java/lang/System.currentTimeMillis()J native static method
 [ERR] getResultAndCancelTimers before timer.cancel(), current thread name: main, Sun Nov 19 19:38:08 PST 2023, System.currentTimeMillis() 1700451488144, System.nanoTime() 593640010358710
 [ERR] 03:38:08.144 0x220ba800              mt.5        > java/lang/System.currentTimeMillis()J native static method
 [ERR] 03:38:08.144 0x220ba800              mt.5        > java/lang/System.currentTimeMillis()J native static method
 [ERR] TimeTestTask tasksPassed: false, taskStarted: 2, taskExecuted: 2, current thread name: main, Sun Nov 19 19:38:08 PST 2023, System.currentTimeMillis() 1700451488144, System.nanoTime() 593640011505550
 [ERR] Exception in thread "main" java.lang.AssertionError: 
 [ERR] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
 [ERR] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
 [ERR] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
 [ERR] 	at ElapsedTime.testElapsedTime(ElapsedTime.java:56)
 [ERR] 	at ElapsedTime.main(ElapsedTime.java:32)
```

Need find out why the timer time measurement didn't work - https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4b03d7952154c9f4b0dae25bde892165cb90ff80/jdk/src/share/classes/java/util/Timer.java#L545-L560
