### ISSUE TITLE
[FFI/Jtreg_JDK22] TestNGException detected in TestLinker.java

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#18507]
The test suite passed as follows:
```
===============================================
java/foreign/TestLinker.java
Total tests run: 30, Passes: 30, Failures: 0, Skips: 0
===============================================

----------System.err:(3/35)----------

JavaTest Message: Test complete.

result: Passed. Execution successful
```
but still ended up with failure during the initialization of the test code at NativeTestHelper.<clinit>`(NativeTestHelaper.java:147)
` at https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/b128ce7ad379a4c9318402f7b90a2c30df4d0b6e/test/jdk/java/foreign/NativeTestHelper.java#L147
```
    private static final MethodHandle FREE = LINKER.downcallHandle(
            LINKER.defaultLookup().find("free").get(), FunctionDescriptor.ofVoid(C_POINTER));
```
against the output as follows:
```
org.testng.TestNGException: 
An error occurred while instantiating class TestLinker: null
	at org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:123)
	at org.testng.internal.InstanceCreator.createInstance(InstanceCreator.java:79)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:109)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:167)
	at org.testng.TestClass.getInstances(TestClass.java:102)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:82)
	at org.testng.TestClass.init(TestClass.java:74)
	at org.testng.TestClass.<init>(TestClass.java:39)
	at org.testng.TestRunner.initMethods(TestRunner.java:457)
	at org.testng.TestRunner.init(TestRunner.java:336)
	at org.testng.TestRunner.init(TestRunner.java:289)
	at org.testng.TestRunner.<init>(TestRunner.java:180)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1582)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
	at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.generateAdapter(InternalDowncallHandler.java:325)
	at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.<init>(InternalDowncallHandler.java:314)
	at java.base/jdk.internal.foreign.abi.DowncallLinker.getBoundMethodHandle(DowncallLinker.java:47)
	at java.base/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeDowncall(CallArranger.java:139)
	at java.base/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.arrangeDowncall(SysVx64Linker.java:62)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.lambda$downcallHandle0$0(AbstractLinker.java:106)
	at java.base/jdk.internal.foreign.abi.SoftReferenceCache$Node.get(SoftReferenceCache.java:49)
	at java.base/jdk.internal.foreign.abi.SoftReferenceCache.get(SoftReferenceCache.java:38)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle0(AbstractLinker.java:103)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle(AbstractLinker.java:85)
	at NativeTestHelper.<clinit>(NativeTestHelper.java:147)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:173)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:23)
	at org.testng.internal.InstanceCreator.instantiateUsingDefaultConstructor(InstanceCreator.java:193)
	at org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:113)
	... 25 more
Caused by: java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "os.arch" "read")
	at java.base/java.security.AccessController.throwACE(AccessController.java:177)
	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:386)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1146)
	at java.base/java.lang.System.getProperty(System.java:663)
	at java.base/java.lang.System.getProperty(System.java:646)
	at java.base/openj9.internal.foreign.abi.LayoutStrPreprocessor.<clinit>(LayoutStrPreprocessor.java:46)
	... 47 more

JavaTest Message: Test threw exception: org.testng.TestNGException: 
An error occurred while instantiating class TestLinker: null
```

**Comment by ChengJin01** [comment]
FYI:  @TobiAjila, @pshipton

**Comment by ChengJin01** [comment]
Investigation shows the failure was actually triggered by https://github.com/eclipse-openj9/openj9/blob/d5e17dd1ec575cf823795da6121c9812b412b9e0/jcl/src/java.base/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java#L58
against the failure above
```
Caused by: java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "os.arch" "read")
	at java.base/java.security.AccessController.throwACE(AccessController.java:177)
	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:386)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1146)
	at java.base/java.lang.System.getProperty(System.java:663)
	at java.base/java.lang.System.getProperty(System.java:646)
	at java.base/openj9.internal.foreign.abi.LayoutStrPreprocessor.<clinit>(LayoutStrPreprocessor.java:46)
	... 47 more
```
which indicates the system property `os.arch` was not set to the build or overridden by the setting on the command line.

**Comment by ChengJin01** [comment]
Looking at the setting of the test suite on the command line
```
CLASSPATH=/.../aqa-tests_jdk22/TKG/output_17002697263615/jdk_foreign_0/work/classes/1/java/foreign/TestLinker.d:/.../aqa-tests_jdk22/openjdk/openjdk-jdk/test/jdk/java/foreign:/.../jvmtest/openjdk/jtreg/lib/testng-7.3.0.jar:/.../jvmtest/openjdk/jtreg/lib/guice-5.1.0.jar:/.../jvmtest/openjdk/jtreg/lib/jcommander-1.82.jar:/.../jvmtest/openjdk/jtreg/lib/javatest.jar:/.../jvmtest/openjdk/jtreg/lib/jtreg.jar \\
    /.../jdk22_openj9_ffi_cmk_x86_64/bin/java \\
        -Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops' \\
        -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops' \\
        -Dtest.compiler.opts= \\
        -Dtest.java.opts= \\
        -Dtest.jdk=/.../jdk22_openj9_ffi_cmk_x86_64 \\
        -Dcompile.jdk=/.../jdk22_openj9_ffi_cmk_x86_64 \\
        -Dtest.timeout.factor=8.0 \\
        -Dtest.nativepath=/.../aqa-tests_jdk22/openjdkbinary/openjdk-test-image/jdk/jtreg/native \\
        -Dtest.root=/.../aqa-tests_jdk22/openjdk/openjdk-jdk/test/jdk \\
        -Dtest.name=java/foreign/TestLinker.java \\
        -Dtest.file=/.../aqa-tests_jdk22/openjdk/openjdk-jdk/test/jdk/java/foreign/TestLinker.java \\
        -Dtest.src=/.../aqa-tests_jdk22/openjdk/openjdk-jdk/test/jdk/java/foreign \\
        -Dtest.src.path=/.../aqa-tests_jdk22/openjdk/openjdk-jdk/test/jdk/java/foreign \\
        -Dtest.classes=/.../aqa-tests_jdk22/TKG/output_17002697263615/jdk_foreign_0/work/classes/1/java/foreign/TestLinker.d \\
        -Dtest.class.path=/.../aqa-tests_jdk22/TKG/output_17002697263615/jdk_foreign_0/work/classes/1/java/foreign/TestLinker.d \\
        -Dtest.class.path.prefix=/.../aqa-tests_jdk22/TKG/output_17002697263615/jdk_foreign_0/work/classes/1/java/foreign/TestLinker.d:/.../aqa-tests_jdk22/openjdk/openjdk-jdk/test/jdk/java/foreign \\
        -Dtest.modules=java.base/jdk.internal.foreign \\
        -Djava.security.policy==/.../aqa-tests_jdk22/TKG/output_17002697263615/jdk_foreign_0/work/scratch/2/security.policy_new \\ <------
        -Djava.security.manager=default \\ <------
        --add-modules java.base \\
        --add-exports java.base/jdk.internal.foreign=ALL-UNNAMED \\
        -ea \\
        -esa \\
        -Xmx512m \\
        -XX:+UseCompressedOops \\
        -Djava.library.path=/.../aqa-tests_jdk22/openjdkbinary/openjdk-test-image/jdk/jtreg/native \\
        -Djava.security.manager=default \\ <--------
        com.sun.javatest.regtest.agent.MainWrapper /.../aqa-tests_jdk22/TKG/output_17002697263615/jdk_foreign_0/work/java/foreign/TestLinker.d/testng.0.jta java/foreign/TestLinker.java false TestLinker
```
in which case the `java.security.manager` was set to `default` along with the security.policy was replaced with https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/test/jdk/java/foreign/security.policy
```
grant codeBase "file:${test.classes}/*" {
    // Permissions needed to run the test
    permission java.util.PropertyPermission "os.name", "read";
    permission java.util.PropertyPermission "NativeTestHelper.DEFAULT_RANDOM.seed", "read";
    permission java.lang.RuntimePermission "accessClassInPackage.jdk.internal.foreign";
};
```
with `os.arch` missing in the policy.

**Comment by ChengJin01** [comment]
Given the test suite is specific to OpenJ9 rather than Hotspot due to the different implementation, we should change the policy file by adding the `os.arch` permission to ensure it works in OpenJ9.

**Comment by JasonFengJ9** [comment]
jenkins test sanity.openjdk amac jdknext

**Comment by JasonFengJ9** [comment]
Closing via 
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/698
