### ISSUE TITLE
Windows OpenJDK java/util/jar/JarFile/mrjar/TestVersionedStream -  The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18512]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0/92/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly_testList_1/92/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0/100/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_2/100/
java/util/jar/JarFile/mrjar/TestVersionedStream.java

```
02:58:44  config TestVersionedStream.close(): failure
02:58:44  java.io.UncheckedIOException: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  	at TestVersionedStream.lambda$close$3(TestVersionedStream.java:120)
02:58:44  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
02:58:44  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
02:58:44  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
02:58:44  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
02:58:44  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
02:58:44  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
02:58:44  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
02:58:44  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
02:58:44  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
02:58:44  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
02:58:44  	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
02:58:44  	at TestVersionedStream.close(TestVersionedStream.java:112)
02:58:44  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
02:58:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
02:58:44  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
02:58:44  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
02:58:44  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
02:58:44  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
02:58:44  	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
02:58:44  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
02:58:44  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
02:58:44  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
02:58:44  	at org.testng.TestRunner.run(TestRunner.java:585)
02:58:44  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
02:58:44  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
02:58:44  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
02:58:44  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
02:58:44  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
02:58:44  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
02:58:44  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
02:58:44  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
02:58:44  	at org.testng.TestNG.runSuites(TestNG.java:1069)
02:58:44  	at org.testng.TestNG.run(TestNG.java:1037)
02:58:44  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
02:58:44  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
02:58:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
02:58:44  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
02:58:44  	at java.base/java.lang.Thread.run(Thread.java:1595)
02:58:44  Caused by: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
02:58:44  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
02:58:44  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
02:58:44  	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
02:58:44  	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
02:58:44  	at java.base/java.nio.file.Files.delete(Files.java:1152)
02:58:44  	at jdk.test.lib.util.FileUtils.deleteFileWithRetry0(FileUtils.java:115)
02:58:44  	at jdk.test.lib.util.FileUtils.deleteFileIfExistsWithRetry(FileUtils.java:102)
02:58:44  	at TestVersionedStream.lambda$close$3(TestVersionedStream.java:117)
02:58:44  	... 38 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
02:58:44  	Suppressed: java.nio.file.FileSystemException: F:\Users\jenkins\workspace\Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0\aqa-tests\TKG\output_17006109436454\jdk_util_1\work\scratch\1_89\verbosegc.20231122.025757.3428.txt: The process cannot access the file because it is being used by another process
02:58:44  		... 47 more
```

https://github.com/eclipse-openj9/openj9/compare/aa5cf3345...d5e17dd1ec5
https://github.com/adoptium/aqa-tests/compare/ec4ef4a9bd4c3923...48d953f27f73b7b

**Comment by pshipton** [comment]
Testing on the previous night's build still fails.
Backing out the aqa-test changes passes.
https://openj9-jenkins.osuosl.org/job/Grinder/3069/
@llxia fyi

Trying another build with https://github.com/adoptium/aqa-tests/pull/4820 to narrow it down.
https://openj9-jenkins.osuosl.org/job/Grinder/3071/

**Comment by pshipton** [comment]
Actually, looking more closely it's obviously https://github.com/adoptium/aqa-tests/pull/4873 causing the problem.

@dmitripivkine fyi

**Comment by pshipton** [comment]
The test is walking all the files in the current directory and trying to delete them. It can't delete the verbosegc file because the VM has it open. It also means on other platforms the file is unlinked so it won't be available after the testing finishes. I'll modify the test to ignore the verbosegc file.

**Comment by pshipton** [comment]
Fixed via https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/699 and backports.
