### ISSUE TITLE
OpenJDK java/lang/Thread/GenerifyStackTrace - Expected B in frame 3 but got waitForDump

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18521]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/102
java/lang/Thread/GenerifyStackTraces.java
```
18:56:14  java.lang.RuntimeException: Expected B in frame 3 but got waitForDump
18:56:14  	at GenerifyStackTraces.checkStack(GenerifyStackTraces.java:173)
18:56:14  	at GenerifyStackTraces.dumpStacks(GenerifyStackTraces.java:146)
18:56:14  	at GenerifyStackTraces$DumpThread.run(GenerifyStackTraces.java:75)
18:56:14  java.lang.RuntimeException: Test Failed.
18:56:14  	at GenerifyStackTraces.main(GenerifyStackTraces.java:60)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11_testList_1/30/consoleFull - [ub20-390-2](https://openj9-jenkins.osuosl.org/computer/ub20-390-2)
```
03:27:05  openjdk version "11.0.25-internal" 2024-10-15
03:27:05  OpenJDK Runtime Environment (build 11.0.25-internal+0-adhoc.jenkins.BuildJDK11s390xlinuxOpenJDK11)
03:27:05  Eclipse OpenJ9 VM (build master-1d2f429d4ce, JRE 11 Linux s390x-64-Bit Compressed References 20240809_112 (JIT enabled, AOT enabled)
03:27:05  OpenJ9   - 1d2f429d4ce
03:27:05  OMR      - 9ccff3cf2b8
03:27:05  JCL      - 38531173402 based on jdk-11.0.25+2)

03:27:05  ===============================================
03:27:05  Running test jdk_lang_1 ...
03:27:05  ===============================================
03:27:05  jdk_lang_1 Start Time: Fri Aug  9 07:27:05 2024 Epoch Time (ms): 1723188425108
03:27:05  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
03:27:05  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Xverbosegclog 

04:13:39  STDERR:
04:13:39  java.lang.RuntimeException: Expected B in frame 3 but got waitForDump
04:13:39  	at GenerifyStackTraces.checkStack(GenerifyStackTraces.java:173)
04:13:39  	at GenerifyStackTraces.dumpStacks(GenerifyStackTraces.java:146)
04:13:39  	at GenerifyStackTraces$DumpThread.run(GenerifyStackTraces.java:75)

04:13:39  TEST RESULT: Error. Agent error: java.lang.Exception: Agent 23 timed out with a timeout of 960 seconds; check console log for any additional details
04:13:39  --------------------------------------------------
04:13:39  Test results: passed: 738; error: 1
04:14:23  Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11_testList_1/aqa-tests/TKG/output_1723188421223/jdk_lang_1/report/html/report.html
04:14:23  Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11_testList_1/aqa-tests/TKG/output_1723188421223/jdk_lang_1/work
04:14:23  Error: Some tests failed or other problems occurred.
04:14:23  -----------------------------------
04:14:23  jdk_lang_1_FAILED
```
50x grinder - https://openj9-jenkins.osuosl.org/job/Grinder/3760/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11_testList_1/30
jdk_lang_1
java/lang/Thread/GenerifyStackTraces.java
timeout

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11_testList_1/30/openjdk_test_output.tar.gz
```
04:13:39  java.lang.RuntimeException: Expected B in frame 3 but got waitForDump
04:13:39  	at GenerifyStackTraces.checkStack(GenerifyStackTraces.java:173)
04:13:39  	at GenerifyStackTraces.dumpStacks(GenerifyStackTraces.java:146)
04:13:39  	at GenerifyStackTraces$DumpThread.run(GenerifyStackTraces.java:75)
```
