### ISSUE TITLE
OpenJDK java/lang/invoke/lambda/LogGeneratedClassesTest timeout or other

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18556]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/103
jdk_lang_1
java/lang/invoke/lambda/LogGeneratedClassesTest.java
```
21:43:31  Timeout refired 960 times
21:43:31  Timeout information:
21:43:31  Running jcmd on process 3231992
21:43:31  Dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/aqa-tests/TKG/output_17014839509011/jdk_lang_1/work/scratch/0/core.20231201.214315.3231992.0001.dmp
21:43:31  Dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/aqa-tests/TKG/output_17014839509011/jdk_lang_1/work/scratch/0/javacore.20231201.214328.3231992.0002.txt
21:43:31  Running jstack on process 3231992
21:43:31  2023-12-01T21:43:28.981766665
21:43:31  Virtual machine: 3231992 JVM information:
21:43:31  JRE 11 Linux s390x-64-Bit 20231201_685 (JIT enabled, AOT enabled)
21:43:31  OpenJ9   - 244201c2b45
21:43:31  OMR      - 69bd2849661
21:43:31  JCL      - 72e4c5d71e3 based on jdk-11.0.22+5
21:43:31  
21:43:31  "main" prio=5 Id=1 WAITING
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.waitImpl(Native Method)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:251)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:219)
21:43:31  	at java.base@11.0.22-internal/java.lang.Thread.join(Thread.java:766)
21:43:31  	at java.base@11.0.22-internal/java.lang.Thread.join(Thread.java:721)
21:43:31  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:198)
21:43:31  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:306)
21:43:31  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:233)
21:43:31  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:70)
21:43:31  
21:43:31  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
21:43:31  
21:43:31  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
21:43:31  
21:43:31  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
21:43:31  
21:43:31  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
21:43:31  
21:43:31  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
21:43:31  
21:43:31  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
21:43:31  
21:43:31  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
21:43:31  
21:43:31  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
21:43:31  
21:43:31  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
21:43:31  
21:43:31  "IProfiler" prio=5 Id=12 RUNNABLE
21:43:31  
21:43:31  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.waitImpl(Native Method)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:251)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:219)
21:43:31  	at java.base@11.0.22-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
21:43:31  	at java.base@11.0.22-internal/java.lang.Thread.run(Thread.java:839)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
21:43:31  
21:43:31  "Concurrent Mark Helper" prio=1 Id=13 RUNNABLE
21:43:31  
21:43:31  "GC Worker" prio=5 Id=14 RUNNABLE
21:43:31  
21:43:31  "GC Worker" prio=5 Id=15 RUNNABLE
21:43:31  
21:43:31  "GC Worker" prio=5 Id=16 RUNNABLE
21:43:31  
21:43:31  "Finalizer thread" prio=5 Id=17 RUNNABLE
21:43:31  
21:43:31  "Attach API wait loop" prio=10 Id=20 RUNNABLE
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
21:43:31  
21:43:31  "pool-1-thread-1" prio=5 Id=21 TIMED_WAITING
21:43:31  	at java.base@11.0.22-internal/jdk.internal.misc.Unsafe.park(Native Method)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:43:31  	at java.base@11.0.22-internal/java.lang.Thread.run(Thread.java:839)
21:43:31  
21:43:31  "ClassByNameCache Reaper" prio=5 Id=43 WAITING
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.waitImpl(Native Method)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:251)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:219)
21:43:31  	at java.base@11.0.22-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
21:43:31  	at java.base@11.0.22-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:109)
21:43:31  	at java.base@11.0.22-internal/java.io.ClassByNameCache$Reaper.run(ClassByNameCache.java:232)
21:43:31  	at java.base@11.0.22-internal/java.lang.Thread.run(Thread.java:839)
21:43:31  
21:43:31  "process reaper (pid 3237752)" prio=10 Id=139 RUNNABLE
21:43:31  	at java.base@11.0.22-internal/java.lang.ProcessHandleImpl.waitForProcessExit0(Native Method)
21:43:31  	at java.base@11.0.22-internal/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:141)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:43:31  	at java.base@11.0.22-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:43:31  	at java.base@11.0.22-internal/java.lang.Thread.run(Thread.java:839)
21:43:31  
21:43:31  "AgentVMThread" prio=5 Id=311 RUNNABLE
21:43:31  	at java.base@11.0.22-internal/java.io.FileInputStream.readBytes(Native Method)
21:43:31  	at java.base@11.0.22-internal/java.io.FileInputStream.read(FileInputStream.java:279)
21:43:31  	at java.base@11.0.22-internal/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
21:43:31  	at java.base@11.0.22-internal/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
21:43:31  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@18c36758
21:43:31  	at java.base@11.0.22-internal/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
21:43:31  	at java.base@11.0.22-internal/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
21:43:31  	at java.base@11.0.22-internal/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
21:43:31  	- locked java.io.InputStreamReader@a716529
21:43:31  	at java.base@11.0.22-internal/java.io.InputStreamReader.read(InputStreamReader.java:181)
21:43:31  	at java.base@11.0.22-internal/java.io.BufferedReader.fill(BufferedReader.java:161)
21:43:31  	at java.base@11.0.22-internal/java.io.BufferedReader.readLine(BufferedReader.java:326)
21:43:31  	- locked java.io.InputStreamReader@a716529
21:43:31  	at java.base@11.0.22-internal/java.io.BufferedReader.readLine(BufferedReader.java:392)
21:43:31  	at LUtils.doExec(LUtils.java:111)
21:43:31  	at LUtils.doExec(LUtils.java:83)
21:43:31  	at LogGeneratedClassesTest.testDumpDirNotExist(LogGeneratedClassesTest.java:142)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:43:31  	at java.base@11.0.22-internal/java.lang.reflect.Method.invoke(Method.java:572)
21:43:31  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
21:43:31  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
21:43:31  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
21:43:31  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
21:43:31  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
21:43:31  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
21:43:31  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
21:43:31  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
21:43:31  	at java.base@11.0.22-internal/java.util.ArrayList.forEach(ArrayList.java:1541)
21:43:31  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
21:43:31  	at app//org.testng.TestRunner.run(TestRunner.java:585)
21:43:31  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
21:43:31  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
21:43:31  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
21:43:31  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
21:43:31  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
21:43:31  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
21:43:31  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
21:43:31  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
21:43:31  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
21:43:31  	at app//org.testng.TestNG.run(TestNG.java:1037)
21:43:31  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:43:31  	at java.base@11.0.22-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:43:31  	at java.base@11.0.22-internal/java.lang.reflect.Method.invoke(Method.java:572)
21:43:31  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
21:43:31  	at java.base@11.0.22-internal/java.lang.Thread.run(Thread.java:839)
21:43:31  
21:43:31  "file lock watchdog" prio=10 Id=313 TIMED_WAITING
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.waitImpl(Native Method)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:251)
21:43:31  	at java.base@11.0.22-internal/java.lang.Object.wait(Object.java:219)
21:43:31  	at java.base@11.0.22-internal/java.util.TimerThread.mainLoop(Timer.java:592)
21:43:31  	at java.base@11.0.22-internal/java.util.TimerThread.run(Timer.java:533)
21:43:31  
21:43:31  "Attachment portNumber: 36609" prio=10 Id=315 RUNNABLE
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:249)
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:185)
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
21:43:31  	at java.base@11.0.22-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)
21:43:31  
21:43:31  
21:43:31  --- Timeout information end.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/108

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/52/
jdk_lang_1
java/lang/invoke/lambda/LogGeneratedClassesTest.java
```
07:34:12  Unable to visit NotExist/DUMP_LAMBDA_PROXY_CLASS_FILES: java.nio.file.NoSuchFileException: NotExist/DUMP_LAMBDA_PROXY_CLASS_FILES
07:34:12  Unable to visit DUMP_LAMBDA_PROXY_CLASS_FILES: java.nio.file.NoSuchFileException: DUMP_LAMBDA_PROXY_CLASS_FILES
07:34:12  java.lang.Exception: failures: 1
07:34:12  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:104)
07:34:12  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
07:34:12  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
07:34:12  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
07:34:12  	at java.base/java.lang.Thread.run(Thread.java:1595)
07:34:12  
07:34:12  JavaTest Message: Test threw exception: java.lang.Exception
07:34:12  JavaTest Message: shutting down test
07:34:12  
07:34:12  STDOUT:
07:34:12  config LogGeneratedClassesTest.setup(): success
07:34:12  test LogGeneratedClassesTest.testDumpDirIsFile(): failure
07:34:12  java.lang.AssertionError: only show error once expected [1] but found [2]
07:34:12  	at org.testng.Assert.fail(Assert.java:99)
07:34:12  	at org.testng.Assert.failNotEquals(Assert.java:1037)
07:34:12  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
07:34:12  	at org.testng.Assert.assertEquals(Assert.java:122)
07:34:12  	at org.testng.Assert.assertEquals(Assert.java:797)
07:34:12  	at LogGeneratedClassesTest.testDumpDirIsFile(LogGeneratedClassesTest.java:177)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/125

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OMR_testList_1/66 - timeout
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_1/65 - timeout

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/132/ - `only show error once expected [1] but found [2]`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/72/ - timeout

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/129/ - timeout

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/137/ - `expected [1] but found [2]`

This type of failure may be due to the following
```
20:22:06  Unable to visit NotExist/DUMP_LAMBDA_PROXY_CLASS_FILES: java.nio.file.NoSuchFileException: NotExist/DUMP_LAMBDA_PROXY_CLASS_FILES
20:22:06  Unable to visit DUMP_LAMBDA_PROXY_CLASS_FILES: java.nio.file.NoSuchFileException: DUMP_LAMBDA_PROXY_CLASS_FILES
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_1/69/ - timeout

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_0/72/ - timeout

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/137/ - timeout

It continues to occur, I don't think I need to keep logging all the failures.

**Comment by tajila** [comment]
@singh264 Please take a look at this

**Comment by singh264** [comment]
I have been unable to reproduce the timout error in `LogGeneratedClassesTest` locally on a `x86_64 Linux` machine with jdk11, jdk17 and jdk21.

I was able to reproduce the intermittent assert error in [`LogGeneratedClassesTest.testDumpDirIsFile`](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/83ef2a1a0da0367ed362671b1ecc41ab8f6db31d/test/jdk/java/lang/invoke/lambda/LogGeneratedClassesTest.java#L164-L182) locally on a `x86_64 Linux` machine with jdk21: `java.lang.AssertionError: only show error once expected [1] but found [2]`. The test creates a file named `DUMP_LAMBDA_PROXY_CLASS_FILES` (instead of a directory) and checks for an error message `DUMP_LAMBDA_PROXY_CLASS_FILES is not a directory` in the output of the java command in the test. The java command in the test runs `TestLambda` with `-Djdk.invoke.LambdaMetafactory.dumpProxyClassFiles` which results in a request to add the lambda proxy class files in a directory named `DUMP_LAMBDA_PROXY_CLASS_FILES`.

```
package com.example;
public class TestLambda {
    interface I {
        int foo();
    }   
    public static void main(String[] args) { 
        System.setSecurityManager(new SecurityManager()); <-----
        I lam = () -> 10;
        Runnable r = () -> {
            System.out.println("Runnable");
        };
        r.run();
        System.out.println("Finish");
    }
}  
```

```
@Test
public void testDumpDirIsFile() throws IOException {
    Path testDir = Path.of("notDir");
    Path dumpFile = testDir.resolve(DUMP_LAMBDA_PROXY_CLASS_FILES);
    Files.createDirectory(testDir);
    Files.createFile(dumpFile); <-----
    assertTrue(Files.isRegularFile(dumpFile));
    TestResult tr = doExec(JAVA_CMD.getAbsolutePath(),
                           "-cp", "..",
                           "-Duser.dir=" + testDir.toAbsolutePath(),
                           "-Djava.security.manager=allow",
                           "-Djdk.invoke.LambdaMetafactory.dumpProxyClassFiles", <-----
                           "com.example.TestLambda"); <------
    assertEquals(tr.testOutput.stream()
                              .filter(s -> s.contains("DUMP_LAMBDA_PROXY_CLASS_FILES is not a directory"))
                              .count(),
                 1, "only show error once");
    assertTrue(tr.exitValue != 0);
}
```

An output of the java command in the test (when it passes) indicates that the error message is generated in the `main` thread by [`ClassFileDumper.validateDumpDir`](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/83ef2a1a0da0367ed362671b1ecc41ab8f6db31d/src/java.base/share/classes/jdk/internal/util/ClassFileDumper.java#L169) during the initialization of [`SecurityManager`](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/83ef2a1a0da0367ed362671b1ecc41ab8f6db31d/src/java.base/share/classes/java/lang/SecurityManager.java#L1222-L1239).

```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError
        at java.base/java.lang.SecurityManager.addNonExportedPackages(SecurityManager.java:1232)
        at java.base/java.lang.SecurityManager.<clinit>(SecurityManager.java:1223)
        at com.example.TestLambda.main(TestLambda.java:7)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
        at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:331)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
        at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:195)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Path DUMP_LAMBDA_PROXY_CLASS_FILES is not a directory <-----
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:169)
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:157)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
        at java.base/jdk.internal.util.ClassFileDumper.validateDumpDir(ClassFileDumper.java:157)
        at java.base/jdk.internal.util.ClassFileDumper.<init>(ClassFileDumper.java:87)
        at java.base/jdk.internal.util.ClassFileDumper.getInstance(ClassFileDumper.java:66)
        at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<clinit>(InnerClassLambdaMetafactory.java:95)
        ... 9 more
```

An output of the java command in the test (when it fails) indicates that the error message appears twice in two separate threads. In addition to the `main` thread, the error message is generated in the `Attach API initializer` thread during the initialization of [`InternalCRIUSupport`](https://github.com/eclipse-openj9/openj9/blob/c3e516121beb6934dad74b072f7f41eb38783572/jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java#L234-L246).

```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError
        at java.base/java.lang.SecurityManager.addNonExportedPackages(SecurityManager.java:1232)
Exception in thread "Attach API initializer" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: java.lang.invoke.InnerClassLambdaMetafactory (initialization failure)
        at java.base/openj9.internal.criu.InternalCRIUSupport.<clinit>(InternalCRIUSupport.java:215)
        at java.base/java.util.Timer.schedule(Timer.java:214)
        at java.base/openj9.internal.tools.attach.target.FileLock.lockFile(FileLock.java:100)
        at java.base/openj9.internal.tools.attach.target.CommonDirectory.obtainControllerLock(CommonDirectory.java:148)
        at java.base/openj9.internal.tools.attach.target.AttachHandler.createFiles(AttachHandler.java:190)
        at java.base/openj9.internal.tools.attach.target.AttachHandler.initialize(AttachHandler.java:296)
        at java.base/openj9.internal.tools.attach.target.AttachHandler.run(AttachHandler.java:229)
        at java.base/java.lang.SecurityManager.<clinit>(SecurityManager.java:1223)
        at com.example.TestLambda.main(TestLambda.java:7)
Caused by: java.lang.ExceptionInInitializerError                                                              
        at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
        at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:331)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
        at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:195)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Path DUMP_LAMBDA_PROXY_CLASS_FILES is not a directory <-----
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:169)
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:157)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
        at java.base/jdk.internal.util.ClassFileDumper.validateDumpDir(ClassFileDumper.java:157)
        at java.base/jdk.internal.util.ClassFileDumper.<init>(ClassFileDumper.java:87)
        at java.base/jdk.internal.util.ClassFileDumper.getInstance(ClassFileDumper.java:66)
        at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<clinit>(InnerClassLambdaMetafactory.java:95)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: java.lang.invoke.InnerClassLambdaMetafactory (initialization failure)
        at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:146)
        at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:331)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
        at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:195)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError                                                               
        at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
        at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:331)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
        at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:195)
        at java.base/java.lang.SecurityManager.addNonExportedPackages(SecurityManager.java:1232)
        at java.base/java.lang.SecurityManager.<clinit>(SecurityManager.java:1223)
        at com.example.TestLambda.main(TestLambda.java:7)
Caused by: java.lang.IllegalArgumentException: Path DUMP_LAMBDA_PROXY_CLASS_FILES is not a directory <-----
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:169)
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:157)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
        at java.base/jdk.internal.util.ClassFileDumper.validateDumpDir(ClassFileDumper.java:157)
        at java.base/jdk.internal.util.ClassFileDumper.<init>(ClassFileDumper.java:87)
        at java.base/jdk.internal.util.ClassFileDumper.getInstance(ClassFileDumper.java:66)
        at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<clinit>(InnerClassLambdaMetafactory.java:95)
        ... 9 more
```

**Comment by singh264** [comment]
@tajila given the intermittent assert error in `LogGeneratedClassesTest.testDumpDirIsFile`, where the error message appears twice in two separate threads (`main thread` and `Attach API initializer`), and considering that the test does not seem to enable criu support with `-XX:+EnableCRIUSupport`, export criu modules with `--add-exports java.base/openj9.internal.criu=ALL-UNNAMED`, or use any criu features like `InternalCRIUSupport`, I would like to understand:

1. How could criu features be initialized by the `Attach API initializer` thread during the test?
2. Would the expected behaviour be that no criu features are initialized during the test?

**Comment by tajila** [comment]
> How could criu features be initialized by the Attach API initializer thread during the test?

I think thats the key. Why does the application require InternalCRIUSupport. My guess is that it is using some crypto/security APIs. We have a certain set we allow when CRIu is enabled. So its probably checking if criu is enabled. You'd need to find which API is requesting that check.

**Comment by tajila** [comment]
After taking a second look:

```
Exception in thread "Attach API initializer" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: java.lang.invoke.InnerClassLambdaMetafactory (initialization failure)
        at java.base/openj9.internal.criu.InternalCRIUSupport.<clinit>(InternalCRIUSupport.java:215)
        at java.base/java.util.Timer.schedule(Timer.java:214)
```

The following is interesting because InternalCRIUSupport is in java.base so it should be there all the time regardless of the following

> test does not seem to enable criu support with -XX:+EnableCRIUSupport, export criu modules with --add-exports java.base/openj9.internal.criu=ALL-UNNAMED

Do you know what causes the init failure exactly? is it a missing class

**Comment by pshipton** [comment]
Created https://github.com/adoptium/aqa-tests/pull/5047 to exclude the test since it fails too often in the builds.

**Comment by singh264** [comment]
> Do you know what causes the init failure exactly? is it a missing class

The init failure is caused by the absence of [`ClassFileDumper`](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/04179e57eb81a73b69928a58c9c299edc792278d/src/java.base/share/classes/jdk/internal/util/ClassFileDumper.java#L169) which is requested during the initialization of [`InnerClassLambdaMetafactory`](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/04179e57eb81a73b69928a58c9c299edc792278d/src/java.base/share/classes/java/lang/invoke/InnerClassLambdaMetafactory.java#L95) to add the lambda class files in a directory named `DUMP_LAMBDA_PROXY_CLASS_FILES`. The error message `DUMP_LAMBDA_PROXY_CLASS_FILES is not a directory` seems to appear in the `main` thread before the `Attach API initializer` thread.

```
Caused by: java.lang.IllegalArgumentException: Path DUMP_LAMBDA_PROXY_CLASS_FILES is not a directory
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:169)
        at java.base/jdk.internal.util.ClassFileDumper$2.run(ClassFileDumper.java:157)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
        at java.base/jdk.internal.util.ClassFileDumper.validateDumpDir(ClassFileDumper.java:157)
        at java.base/jdk.internal.util.ClassFileDumper.<init>(ClassFileDumper.java:87) <-----
        at java.base/jdk.internal.util.ClassFileDumper.getInstance(ClassFileDumper.java:66)
        at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<clinit>(InnerClassLambdaMetafactory.java:95) <-----
        ... 9 more
```

**Comment by pshipton** [comment]
I assume this can be closed now.
