### ISSUE TITLE
OpenJDK java/security/cert/CertPathValidator/OCSP/OCSPTimeout - found 1 soft fail exceptions

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18567]
java/security/cert/CertPathValidator/OCSP/OCSPTimeout.java
```
18:52:47  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to pass, found 1 soft fail exceptions
18:52:47  REASON: User specified action: run main/othervm -Dcom.sun.security.ocsp.readtimeout=5 OCSPTimeout 1000 true 
18:52:47  TIME:   16.155 seconds
18:52:47  messages:
18:52:47  command: main -Dcom.sun.security.ocsp.readtimeout=5 OCSPTimeout 1000 true
18:52:47  reason: User specified action: run main/othervm -Dcom.sun.security.ocsp.readtimeout=5 OCSPTimeout 1000 true 
18:52:47  started: Mon Dec 04 23:42:34 GMT 2023
18:52:47  Mode: othervm [/othervm specified]
18:52:47  Additional options from @modules: --add-modules java.base --add-exports java.base/sun.security.x509=ALL-UNNAMED --add-exports java.base/sun.security.provider.certpath=ALL-UNNAMED --add-exports java.base/sun.security.util=ALL-UNNAMED
18:52:47  finished: Mon Dec 04 23:42:50 GMT 2023
18:52:47  elapsed time (seconds): 16.155
18:52:47  configuration:
18:52:47  Boot Layer
18:52:47    add modules: java.base                                
18:52:47    add exports: java.base/sun.security.provider.certpath ALL-UNNAMED
18:52:47                 java.base/sun.security.util              ALL-UNNAMED
18:52:47                 java.base/sun.security.x509              ALL-UNNAMED
18:52:47  
18:52:47  STDOUT:
18:52:47  Generated Root CA KeyPair
18:52:47  Generated End Entity KeyPair
18:52:47  Root CA Created:
18:52:47  Issuer: CN=Root CA Cert, O=SomeCompany
18:52:47  Subject: CN=Root CA Cert, O=SomeCompany
18:52:47  Serial: 1
18:52:47  
18:52:47  [MainThread]: nextUpdate set to Tue Dec 05 00:42:36 GMT 2023
18:52:47  [MainThread]: Response Content-Length field disabled
18:52:47  [pool-1-thread-1]: Listening on 0.0.0.0/0.0.0.0:64191
18:52:47  Root OCSP Responder URI is http://localhost:64191/
18:52:47  SSL Certificate Created:
18:52:47  Issuer: CN=Root CA Cert, O=SomeCompany
18:52:47  Subject: CN=SSLCertificate, O=SomeCompany
18:52:47  Serial: 4096
18:52:47  
18:52:47  [MainThread]: Added entry for serial 4096(CERT_STATUS_GOOD)
18:52:47  [MainThread]: OCSP latency set to 1000 milliseconds.
18:52:47  Test case expects to pass
18:52:47  [pool-2-thread-1]: Received incoming HTTP GET from /127.0.0.1:64192
18:52:47  [pool-2-thread-1]: ReqHdr: User-Agent: Java/21.0.1-internal
18:52:47  [pool-2-thread-1]: ReqHdr: Host: localhost:64191
18:52:47  [pool-2-thread-1]: ReqHdr: Accept: */*
18:52:47  [pool-2-thread-1]: ReqHdr: Connection: keep-alive
18:52:47  [pool-2-thread-1]: OCSP Request: Version 1 (0x0)
18:52:47  Request [0]
18:52:47  CertId, Algorithm = SHA-1
18:52:47  	Issuer Name Hash: C8ED9F4E9AC0052A978257C569E6A7C9C45F5CB5
18:52:47  	Issuer Key Hash: CB284341836922895C2A69E78D5BC8EEFE318770
18:52:47  	Serial Number: 4096
18:52:47  
18:52:47  [pool-2-thread-1]: Status for SN 4096: CERT_STATUS_GOOD
18:52:47  STDERR:
18:52:47  java.lang.RuntimeException: Expected to pass, found 1 soft fail exceptions
18:52:47  	at OCSPTimeout.main(OCSPTimeout.java:116)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/133
jdk_security1_1
java/security/cert/CertPathValidator/OCSP/OCSPTimeout.java
```
19:11:19  Generated Root CA KeyPair
19:11:19  Generated End Entity KeyPair
19:11:19  Root CA Created:
19:11:19  Issuer: CN=Root CA Cert, O=SomeCompany
19:11:19  Subject: CN=Root CA Cert, O=SomeCompany
19:11:19  Serial: 1
19:11:19  
19:11:19  [MainThread]: nextUpdate set to Fri Jan 05 01:11:07 UTC 2024
19:11:19  [MainThread]: Response Content-Length field disabled
19:11:19  [pool-1-thread-1]: Listening on 0.0.0.0/0.0.0.0:43023
19:11:19  Root OCSP Responder URI is http://localhost:43023/
19:11:19  SSL Certificate Created:
19:11:19  Issuer: CN=Root CA Cert, O=SomeCompany
19:11:19  Subject: CN=SSLCertificate, O=SomeCompany
19:11:19  Serial: 4096
19:11:19  
19:11:19  [MainThread]: Added entry for serial 4096(CERT_STATUS_GOOD)
19:11:19  [MainThread]: OCSP latency set to 1000 milliseconds.
19:11:19  Test case expects to pass
19:11:19  [pool-2-thread-1]: Received incoming HTTP GET from /127.0.0.1:60550
19:11:19  [pool-2-thread-1]: ReqHdr: User-Agent: Java/21.0.1-internal
19:11:19  [pool-2-thread-1]: ReqHdr: Host: localhost:43023
19:11:19  [pool-2-thread-1]: ReqHdr: Accept: */*
19:11:19  [pool-2-thread-1]: ReqHdr: Connection: keep-alive
19:11:19  [pool-2-thread-1]: OCSP Request: Version 1 (0x0)
19:11:19  Request [0]
19:11:19  CertId, Algorithm = SHA-1
19:11:19  	Issuer Name Hash: C8ED9F4E9AC0052A978257C569E6A7C9C45F5CB5
19:11:19  	Issuer Key Hash: 321275C15191D54911BACA0D43F1D770367CBC80
19:11:19  	Serial Number: 4096
19:11:19  
19:11:19  [pool-2-thread-1]: Status for SN 4096: CERT_STATUS_GOOD
19:11:19  [pool-2-thread-1]: Exception: java.net.SocketException: Broken pipe
19:11:19  	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
19:11:19  	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
19:11:19  	at java.base/sun.nio.ch.NioSocketImpl.tryWrite(NioSocketImpl.java:394)
19:11:19  	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:410)
19:11:19  	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
19:11:19  	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:819)
19:11:19  	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1195)
19:11:19  	at java.base/java.io.OutputStream.write(OutputStream.java:124)
19:11:19  	at sun.security.testlibrary.SimpleOCSPServer$OcspHandler.sendResponse(SimpleOCSPServer.java:829)
19:11:19  	at sun.security.testlibrary.SimpleOCSPServer$OcspHandler.run(SimpleOCSPServer.java:791)
19:11:19  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
19:11:19  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
19:11:19  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
19:11:19  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
19:11:19  	at java.base/java.lang.Thread.run(Thread.java:1595)
19:11:19  STDERR:
19:11:19  java.lang.RuntimeException: Expected to pass, found 1 soft fail exceptions
19:11:19  	at OCSPTimeout.main(OCSPTimeout.java:116)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/130/
jdk_security1_1
java/security/cert/CertPathValidator/OCSP/OCSPTimeout.java

"broken pipe". I think I won't report broken pipe failures any more.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/239
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/449 jdk_security1_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/213
