### ISSUE TITLE
jdk_security3_1_FAILED sun/security/pkcs11/ec/ReadCertificates.java PKCS11Exception: CKR_DATA_LEN_RANGE

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18562]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_s390x_linux/156/)(`rhel8s390x-svl-rt7-1`):
```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0-m1 (build 17.0.10+5)
Eclipse OpenJ9 VM 17.0.10.0-m1 (build v0.43.0-release-9b2a42f8f, JRE 17 Linux s390x-64-Bit Compressed References 20240116_585 (JIT enabled, AOT enabled)
OpenJ9   - 9b2a42f8f
OMR      - d810fcb98
JCL      - 10ccdceee3c based on jdk-17.0.10+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-s390x-openj9%2F585%2Fibm-semeru-open-jdk_s390x_linux_17.0.10_5_openj9-0.43.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-s390x-openj9%2F585%2Fibm-semeru-open-testimage_s390x_linux_17.0.10_5_openj9-0.43.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.43.0-release&amp;OPENJ9_BRANCH=v0.43.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.43.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-12-01T22:24:35.119Z] variation: Mode650
[2023-12-01T22:24:35.119Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2023-12-01T22:38:23.468Z] TEST: sun/security/pkcs11/ec/ReadCertificates.java

[2023-12-01T22:38:23.471Z] STDERR:
[2023-12-01T22:38:23.471Z] WARNING: A terminally deprecated method in java.lang.System has been called
[2023-12-01T22:38:23.471Z] WARNING: System::setSecurityManager has been called by PKCS11Test (file:/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_17014636881420/jdk_security3_1/work/classes/0/sun/security/pkcs11/ec/ReadCertificates.d/)
[2023-12-01T22:38:23.471Z] WARNING: Please consider reporting this to the maintainers of PKCS11Test
[2023-12-01T22:38:23.471Z] WARNING: System::setSecurityManager will be removed in a future release
[2023-12-01T22:38:23.471Z] java.security.ProviderException: cancel failed
[2023-12-01T22:38:23.471Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.cancelOperation(P11Signature.java:346)
[2023-12-01T22:38:23.471Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.reset(P11Signature.java:291)
[2023-12-01T22:38:23.471Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.engineVerify(P11Signature.java:776)
[2023-12-01T22:38:23.471Z] 	at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1435)
[2023-12-01T22:38:23.471Z] 	at java.base/java.security.Signature.verify(Signature.java:789)
[2023-12-01T22:38:23.471Z] 	at java.base/sun.security.x509.X509CertImpl.verify(X509CertImpl.java:445)
[2023-12-01T22:38:23.471Z] 	at java.base/sun.security.x509.X509CertImpl.verify(X509CertImpl.java:384)
[2023-12-01T22:38:23.471Z] 	at ReadCertificates.main(ReadCertificates.java:176)
[2023-12-01T22:38:23.471Z] 	at PKCS11Test.premain(PKCS11Test.java:174)
[2023-12-01T22:38:23.471Z] 	at PKCS11Test.testNSS(PKCS11Test.java:550)
[2023-12-01T22:38:23.471Z] 	at PKCS11Test.main(PKCS11Test.java:210)
[2023-12-01T22:38:23.471Z] 	at ReadCertificates.main(ReadCertificates.java:76)
[2023-12-01T22:38:23.471Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-12-01T22:38:23.471Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-12-01T22:38:23.471Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-12-01T22:38:23.471Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
[2023-12-01T22:38:23.471Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-12-01T22:38:23.471Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-12-01T22:38:23.471Z] Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DATA_LEN_RANGE
[2023-12-01T22:38:23.471Z] 	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.cancelOperation(P11Signature.java:319)
[2023-12-01T22:38:23.471Z] 	... 17 more
[2023-12-01T22:38:23.471Z] 
[2023-12-01T22:38:23.471Z] JavaTest Message: Test threw exception: java.security.ProviderException: cancel failed

[2023-12-01T23:06:32.258Z] jdk_security3_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36542/) - 24/50 failed
[-Xint 50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36632/) - reproduced w/ [-Xint](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/3157/consoleFull)

**Comment by pshipton** [comment]
If user's may be caught out by the difference, doing `Change the SunPKCS11 code to account for CKR_DATA_LEN_RANGE return code too.` seems like the way to proceed.

**Comment by pshipton** [comment]
Moving this forward as it's too late for 0.43.
