### ISSUE TITLE
MauveMultiThrdLoad_special_5m FAILED with ClassNotFoundException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18577]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_x86-64_windows_testList_3/448/)(`win11x86-svl-rt2-1`):
```
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b04)
Eclipse OpenJ9 VM (build v0.43.0-release-579b3f8e0, JRE 1.8.0 Windows 11 amd64-64-Bit Compressed References 20231204_831 (JIT enabled, AOT enabled)
OpenJ9   - 579b3f8e0
OMR      - d810fcb98
JCL      - 68dbd3149c based on jdk8u402-b04)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=MauveMultiThrdLoad_special_5m_6&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_x86-64_windows&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x64-openj9%2F831%2Fibm-semeru-open-jdk_x64_windows_8u402b04_openj9-0.431.0-m1.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.43.0-release&amp;OPENJ9_BRANCH=v0.43.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.43.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=478&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-12-05T06:30:37.746Z] variation: Mode121
[2023-12-05T06:30:38.406Z] JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs 

[2023-12-05T06:31:22.570Z] LT  22:31:22.122 - Test failed
[2023-12-05T06:31:22.570Z] LT    Failure num.  = 1
[2023-12-05T06:31:22.570Z] LT    Test number   = 680
[2023-12-05T06:31:22.570Z] LT    Test details  = 'Mauve[gnu.testlet.java.lang.ClassCastException.classInfo.getInterfaces]'
[2023-12-05T06:31:22.570Z] LT    Suite number  = 0
[2023-12-05T06:31:22.570Z] LT    Thread number = 2
[2023-12-05T06:31:22.570Z] LT  >>> Captured test output >>>
[2023-12-05T06:31:22.571Z] LT  Test failed:
[2023-12-05T06:31:22.571Z] LT  java.lang.ClassNotFoundException: gnu.testlet.java.lang.ClassCastException.classInfo.getInterfaces
[2023-12-05T06:31:22.571Z] LT  	at java.lang.Class.forNameImpl(Native Method)
[2023-12-05T06:31:22.571Z] LT  	at java.lang.Class.forName(Class.java:347)
[2023-12-05T06:31:22.571Z] LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
[2023-12-05T06:31:22.571Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2023-12-05T06:31:22.571Z] LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-12-05T06:31:22.571Z] LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-12-05T06:31:22.571Z] LT  	at java.lang.Thread.run(Thread.java:826)
[2023-12-05T06:31:22.571Z] LT  <<<

[2023-12-05T06:31:23.996Z] MauveMultiThrdLoad_special_5m_6_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36704/) - no failure reproduced

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_special.system_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_x86-64_linux_testList_6/366/)
```
[2025-10-24T21:00:26.855Z] Running test MauveMultiThrdLoad_special_5m_7 ...
[2025-10-24T21:00:26.855Z] ===============================================
[2025-10-24T21:00:26.856Z] MauveMultiThrdLoad_special_5m_7 Start Time: Fri Oct 24 17:00:26 2025 Epoch Time (ms): 1761339626653
[2025-10-24T21:00:26.856Z] variation: Mode122
[2025-10-24T21:00:26.856Z] JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xnocompressedrefs 

[2025-10-24T21:00:38.060Z] LT  >>> Captured test output >>>
[2025-10-24T21:00:38.060Z] LT  Test failed:
[2025-10-24T21:00:38.060Z] LT  java.lang.ClassNotFoundException: gnu.testlet.java.lang.Math.classInfo.getInterfaces
[2025-10-24T21:00:38.060Z] LT  	at java.lang.Class.forNameImpl(Native Method)
[2025-10-24T21:00:38.060Z] LT  	at java.lang.Class.forName(Class.java:336)
[2025-10-24T21:00:38.060Z] LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
[2025-10-24T21:00:38.060Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2025-10-24T21:00:38.060Z] LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-10-24T21:00:38.060Z] LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-10-24T21:00:38.060Z] LT  	at java.lang.Thread.run(Thread.java:822)
[2025-10-24T21:00:38.060Z] LT  <<<
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/55738/) - passed

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_sanity.system_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.system_x86-64_linux_testList_1/50/)
```
[2025-10-28T14:50:24.373Z] Running test MauveMultiThrdLoad_5m_1 ...
[2025-10-28T14:50:24.373Z] ===============================================
[2025-10-28T14:50:24.373Z] MauveMultiThrdLoad_5m_1 Start Time: Tue Oct 28 07:50:22 2025 Epoch Time (ms): 1761663022996
[2025-10-28T14:50:24.373Z] variation: Mode650
[2025-10-28T14:50:24.373Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2025-10-28T14:50:39.351Z] LT  07:50:36.536 - Test failed
[2025-10-28T14:50:39.351Z] LT    Failure num.  = 1
[2025-10-28T14:50:39.351Z] LT    Test number   = 2604
[2025-10-28T14:50:39.351Z] LT    Test details  = 'Mauve[gnu.testlet.java.lang.String.classInfo.getClasses]'
[2025-10-28T14:50:39.351Z] LT    Suite number  = 0
[2025-10-28T14:50:39.351Z] LT    Thread number = 0
[2025-10-28T14:50:39.351Z] LT  >>> Captured test output >>>
[2025-10-28T14:50:39.351Z] LT  Test failed:
[2025-10-28T14:50:39.351Z] LT  java.lang.ClassNotFoundException: gnu.testlet.java.lang.String.classInfo.getClasses
[2025-10-28T14:50:39.351Z] LT  	at java.base/java.lang.Class.forNameImpl(Native Method)
[2025-10-28T14:50:39.351Z] LT  	at java.base/java.lang.Class.forName(Class.java:289)
[2025-10-28T14:50:39.351Z] LT  	at java.base/java.lang.Class.forName(Class.java:277)
[2025-10-28T14:50:39.351Z] LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
[2025-10-28T14:50:39.351Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2025-10-28T14:50:39.351Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[2025-10-28T14:50:39.351Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[2025-10-28T14:50:39.351Z] LT  	at java.base/java.lang.Thread.run(Thread.java:1485)
[2025-10-28T14:50:39.351Z] LT  <<<
```

[openjdk25_j9_sanity.system_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_sanity.system_x86-64_linux_testList_1/50/)
```
[2025-10-28T14:49:23.717Z] Running test MauveSingleThrdLoad_J9_5m_0 ...
[2025-10-28T14:49:23.717Z] ===============================================
[2025-10-28T14:49:23.717Z] MauveSingleThrdLoad_J9_5m_0 Start Time: Tue Oct 28 07:49:23 2025 Epoch Time (ms): 1761662963589
[2025-10-28T14:49:23.717Z] variation: Mode110
[2025-10-28T14:49:23.717Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

[2025-10-28T14:49:41.294Z] LT  07:49:40.253 - Test failed
[2025-10-28T14:49:41.294Z] LT    Failure num.  = 1
[2025-10-28T14:49:41.294Z] LT    Test number   = 1040
[2025-10-28T14:49:41.295Z] LT    Test details  = 'Mauve[gnu.testlet.java.lang.Boolean.classInfo.getAnnotation]'
[2025-10-28T14:49:41.295Z] LT    Suite number  = 0
[2025-10-28T14:49:41.295Z] LT    Thread number = 0
[2025-10-28T14:49:41.295Z] LT  >>> Captured test output >>>
[2025-10-28T14:49:41.295Z] LT  Test failed:
[2025-10-28T14:49:41.295Z] LT  java.lang.ClassNotFoundException: gnu.testlet.java.lang.Boolean.classInfo.getAnnotation
[2025-10-28T14:49:41.295Z] LT  	at java.base/java.lang.Class.forNameImpl(Native Method)
[2025-10-28T14:49:41.295Z] LT  	at java.base/java.lang.Class.forName(Class.java:289)
[2025-10-28T14:49:41.295Z] LT  	at java.base/java.lang.Class.forName(Class.java:277)
[2025-10-28T14:49:41.295Z] LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
[2025-10-28T14:49:41.295Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2025-10-28T14:49:41.295Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[2025-10-28T14:49:41.295Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[2025-10-28T14:49:41.295Z] LT  	at java.base/java.lang.Thread.run(Thread.java:1485)
[2025-10-28T14:49:41.295Z] LT  <<<
```

**Comment by llxia** [comment]
This issue should be fixed as we rolled back to old mauve.jar https://github.com/adoptium/aqa-tests/issues/6659

@LongyuZhang could you run https://hyc-runtimes-jenkins.swg-devops.com/job/Cleanup_Test_Lib/ on the above failed machine?

**Comment by ixlongz** [comment]
The mauve.jar on previous machines have been updated, and the test has passed:
hyc_grinder: 55932  and 55924
