### ISSUE TITLE
jdk_security3_1_FAILED sun/security/ssl/SSLSocketImpl/AsyncSSLSocketClose.java timed out

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18575]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_ppc64_aix/170/)(`paix910`):
```
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b04)
Eclipse OpenJ9 VM (build v0.43.0-release-579b3f8e0, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20231204_806 (JIT enabled, AOT enabled)
OpenJ9   - 579b3f8e0
OMR      - d810fcb98
JCL      - 68dbd3149c based on jdk8u402-b04)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F806%2Fibm-semeru-open-jdk_ppc64_aix_8u402b04_openj9-0.431.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F806%2Fibm-semeru-open-testimage_ppc64_aix_8u402b04_openj9-0.431.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.43.0-release&amp;OPENJ9_BRANCH=v0.43.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.43.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-12-05T01:34:48.591Z] variation: Mode650
[2023-12-05T01:34:48.591Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2023-12-05T02:29:54.565Z] TEST: sun/security/ssl/SSLSocketImpl/AsyncSSLSocketClose.java

[2023-12-05T02:29:54.568Z] STDERR:
[2023-12-05T02:29:54.568Z] JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_17017308206078/jdk_security3_1/work/scratch/core.20231204.202944.6422954.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
[2023-12-05T02:29:54.568Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_17017308206078/jdk_security3_1/work/scratch/core.20231204.202944.6422954.0001.dmp
[2023-12-05T02:29:54.568Z] JVMDUMP034I User requested Java dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_17017308206078/jdk_security3_1/work/scratch/javacore.20231204.202948.6422954.0002.txt' through com.ibm.jvm.Dump.javaDumpToFile
[2023-12-05T02:29:54.568Z] JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_17017308206078/jdk_security3_1/work/scratch/javacore.20231204.202948.6422954.0002.txt

[2023-12-05T02:29:54.569Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 967359ms).
[2023-12-05T02:29:54.569Z] --------------------------------------------------
[2023-12-05T02:48:02.540Z] Test results: passed: 618; error: 1
[2023-12-05T02:48:08.176Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_17017308206078/jdk_security3_1/report/html/report.html
[2023-12-05T02:48:08.176Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_17017308206078/jdk_security3_1/work
[2023-12-05T02:48:08.176Z] Error: Some tests failed or other problems occurred.
[2023-12-05T02:48:08.176Z] -----------------------------------
[2023-12-05T02:48:08.176Z] jdk_security3_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36700/)

**Comment by pshipton** [comment]
There are actually only 6 failures of the same test, 2 each on 3 machines.
Looking at one failure, it looks like a network thing. There is another thread waiting on this one.
```
3XMTHREADINFO      "Thread-1" J9VMThread:0x0000010022BFC600, omrthread_t:0x0000010022B6EFC0, java/lang/Thread:0x0A00000000185F50, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1A, isDaemon:false)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x0A0000000006DBD0)
3XMTHREADINFO1            (native thread ID:0x19E02D7, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x000000a1)
3XMTHREADINFO2            (native stack address range from:0x0000010022B77000, to:0x0000010022BF7888, size:0x80888)
3XMCPUTIME               CPU usage total: 0.063100000 secs, user: 0.060698000 secs, system: 0.002402000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/net/SocketOutputStream.socketWrite0(Native Method)
4XESTACKTRACE                at java/net/SocketOutputStream.socketWrite(SocketOutputStream.java:111(Compiled Code))
4XESTACKTRACE                at java/net/SocketOutputStream.write(SocketOutputStream.java:155(Compiled Code))
4XESTACKTRACE                at sun/security/ssl/SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:319(Compiled Code))
5XESTACKTRACE                   (entered lock: sun/security/ssl/SSLSocketOutputRecord@0x0A000000001A6B90, entry count: 1)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1197)
4XESTACKTRACE                at java/io/OutputStream.write(OutputStream.java:75(Compiled Code))
4XESTACKTRACE                at AsyncSSLSocketClose.run(AsyncSSLSocketClose.java:124)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:826)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               NET_Send+0xe8 (0x090000000715566C [libnet.so+0x966c])
4XENATIVESTACK               Java_java_net_SocketOutputStream_socketWrite0+0x190 (0x0900000007168794 [libnet.so+0x1c794])
```

The other failures are in
javax/net/ssl/SSLEngine/LargePacket.java.LargePacket
javax/net/ssl/ServerName/SSLEngineExplorerWithCli.java.SSLEngineExplorerWithCli
javax/net/ssl/SSLEngine/LargePacket.java.LargePacket
javax/net/ssl/SSLEngine/LargePacket.java.LargePacket

**Comment by JasonFengJ9** [comment]
[JDK8 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/6/)(`paix819`)
```
openjdk version "1.8.0_412-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_412-beta-202403060026-b05)
Eclipse OpenJ9 VM (build master-42ea7f47c, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20240305_875 (JIT enabled, AOT enabled)
OpenJ9   - 42ea7f47c
OMR      - 8bea58e95
JCL      - 16aa7c249 based on jdk8u412-b05)

[2024-03-06T02:13:10.626Z] variation: Mode150
[2024-03-06T02:13:10.626Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-06T03:03:50.634Z] TEST: sun/security/ssl/SSLSocketImpl/AsyncSSLSocketClose.java

[2024-03-06T03:03:50.638Z] 258048 bytes written
[2024-03-06T03:03:50.638Z] 259072 bytes to be written
[2024-03-06T03:03:50.638Z] Timeout refired 960 times
[2024-03-06T03:03:50.638Z] interrupted? java.net.SocketException: There is no process to read data written to a pipe. (Write failed)
[2024-03-06T03:03:50.638Z] ssl socket get closed
[2024-03-06T03:03:50.638Z] STDERR:
[2024-03-06T03:03:50.638Z] JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_17096908675857/jdk_security3_0/work/scratch/core.20240305.220341.15728942.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
[2024-03-06T03:03:50.638Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_17096908675857/jdk_security3_0/work/scratch/core.20240305.220341.15728942.0001.dmp
[2024-03-06T03:03:50.638Z] STATUS:Passed.

[2024-03-06T03:03:50.638Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 966640ms).
[2024-03-06T03:03:50.638Z] --------------------------------------------------
[2024-03-06T03:20:02.718Z] Test results: passed: 620; error: 1
[2024-03-06T03:20:02.718Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_17096908675857/jdk_security3_0/report/html/report.html
[2024-03-06T03:20:02.718Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_17096908675857/jdk_security3_0/work
[2024-03-06T03:20:02.718Z] Error: Some tests failed or other problems occurred.
[2024-03-06T03:20:02.718Z] -----------------------------------
[2024-03-06T03:20:02.718Z] jdk_security3_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK8 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/16/)(`paix906`)
```
[2024-03-21T23:21:22.293Z] variation: Mode150
[2024-03-21T23:21:22.293Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-22T00:35:26.782Z] TEST: sun/security/ssl/SSLSocketImpl/AsyncSSLSocketClose.java

[2024-03-22T00:35:26.784Z] Timeout refired 960 times
[2024-03-22T00:35:26.784Z] interrupted? java.net.SocketException: There is no process to read data written to a pipe. (Write failed)
[2024-03-22T00:35:26.784Z] ssl socket get closed

[2024-03-22T00:35:26.784Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 969146ms).
[2024-03-22T00:35:26.784Z] --------------------------------------------------
[2024-03-22T00:51:44.013Z] Test results: passed: 619; error: 2
[2024-03-22T00:51:53.940Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_17110629593317/jdk_security3_0/report/html/report.html
[2024-03-22T00:51:53.940Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_17110629593317/jdk_security3_0/work
[2024-03-22T00:51:53.940Z] Error: Some tests failed or other problems occurred.
[2024-03-22T00:51:53.940Z] -----------------------------------
[2024-03-22T00:51:53.940Z] jdk_security3_0_FAILED
```

@llxia @annaibm could you please exclude this test for Java 8 AIX?

**Comment by annaibm** [comment]
PR for excluding `sun/security/ssl/SSLSocketImpl/AsyncSSLSocketClose.java` test for JAVA 8 AIX
[aqa-tests/pull#5182](https://github.com/adoptium/aqa-tests/pull/5182)
