### ISSUE TITLE
OpenJ9-17 report BUG! UNCAUGHT EXCEPTION, but 8 and 11 are not reported.

### ISSUE THREAD

**Issue by TheSail28** [eclipse-openj9/openj9#18608]
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Java -version output

```
openjdk version "1.8.0_382"
IBM Semeru Runtime Open Edition (build 1.8.0_382-b05)
Eclipse OpenJ9 VM (build openj9-0.40.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230810_729 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - c4d2c2bafb based on jdk8u382-b05)
```

```
openjdk version "11.0.20.1" 2023-08-24
IBM Semeru Runtime Open Edition 11.0.20.1 (build 11.0.20.1+1)
Eclipse OpenJ9 VM 11.0.20.1 (build openj9-0.40.0, JRE 11 Linux amd64-64-Bit Compressed References 20230824_836 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - 0880e8df04 based on jdk-11.0.20.1+1)
```

```
openjdk version "17.0.8.1" 2023-08-24
IBM Semeru Runtime Open Edition 17.0.8.1 (build 17.0.8.1+1)
Eclipse OpenJ9 VM 17.0.8.1 (build openj9-0.40.0, JRE 17 Linux amd64-64-Bit Compressed References 20230824_549 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - 8ecf238a124 based on jdk-17.0.8.1+1)
```

## Reproduce

```
jdk_linux_8_openj9/bin/java -cp ./lib/groovy-all-2.3.9.jar:./ ysoserial.payloads.Groovy1

jdk_linux_11_openj9/bin/java -cp ./lib/groovy-all-2.3.9.jar:./ ysoserial.payloads.Groovy1

jdk_linux_17_openj9/bin/java -cp ./lib/groovy-all-2.3.9.jar:./ ysoserial.payloads.Groovy1
```

Expected Result

```
---------------jdk_linux_8_openj9---------------
nothing
---------------jdk_linux_11_openj9---------------
nothing
---------------jdk_linux_17_openj9---------------
nothing
```

Actual Result

```
---------------jdk_linux_8_openj9---------------
nothing
---------------jdk_linux_11_openj9---------------
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 to method java.lang.Object.finalize()
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 to method java.lang.Object.clone()
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 to method java.lang.Object.registerNatives()
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
---------------jdk_linux_17_openj9---------------
Exception in thread "main" BUG! UNCAUGHT EXCEPTION: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
	at org.codehaus.groovy.vmplugin.v7.Java7.<clinit>(Java7.java:44)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at org.codehaus.groovy.vmplugin.VMPluginFactory.createPlugin(VMPluginFactory.java:56)
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:37)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:99)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:71)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:61)
	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
	at groovy.lang.Closure.<init>(Closure.java:219)
	at groovy.lang.Closure.<init>(Closure.java:236)
	at groovy.lang.Closure$1.<init>(Closure.java:203)
	at groovy.lang.Closure.<clinit>(Closure.java:203)
	at ysoserial.payloads.Groovy1.getObject(Unknown Source)
	at ysoserial.payloads.Groovy1.getObject(Unknown Source)
	at ysoserial.payloads.util.PayloadRunner$1.call(Unknown Source)
	at ysoserial.payloads.util.PayloadRunner$1.call(Unknown Source)
	at ysoserial.ExecBlockingSecurityManager.wrap(Unknown Source)
	at ysoserial.payloads.util.PayloadRunner.run(Unknown Source)
	at ysoserial.payloads.Groovy1.main(Unknown Source)
Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
	at java.base/java.lang.Class.getConstructor0(Unknown Source)
	at java.base/java.lang.Class.getDeclaredConstructor(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.Java7.<clinit>(Java7.java:42)
	... 25 more
```

## Problem summary

`ysoserial.payloads.Groovy1` calls the `getObject()` method of the class through a series of passes, where OpenJ9-8 reports nothing, OpenJ9-11 reports some WARNING, and OpenJ9-17 throws a exception.

## Attachment

[testcase1.zip](https://github.com/eclipse-openj9/openj9/files/13658018/testcase1.zip)

**Comment by pshipton** [comment]
Hotspot has the same behavior.

**Comment by pshipton** [comment]
The behavior comes from OpenJDK and you should peruse it with the OpenJDK project.
