### ISSUE TITLE
jdk_security3_0_FAILED RuntimeException: No 64-bit serial number, SunCertPathBuilderException: unable to find valid certification path to requested target and others

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18602]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/18/)(`sles12le-svl-rt3-1`):
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202312091615 (build 21.0.1-beta+12-202312091615)
Eclipse OpenJ9 VM 21.0.1+12-202312091615 (build master-bef44f19a, JRE 21 Linux ppc64le-64-Bit Compressed References 20231209_54 (JIT enabled, AOT enabled)
OpenJ9   - bef44f19a
OMR      - 137778af4
JCL      - d8e375524 based on jdk-21.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=1&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F54%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK21U_2023-12-09-16-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F54%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK21U_2023-12-09-16-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-12-09T18:29:12.319Z] variation: Mode150
[2023-12-09T18:29:12.319Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2023-12-09T18:55:24.836Z] TEST: sun/security/pkcs12/SameDN.java
[2023-12-09T18:55:24.839Z] STDERR:
[2023-12-09T18:55:24.839Z] java.lang.Exception: user2 not signed by ca2
[2023-12-09T18:55:24.839Z] 	at SameDN.main(SameDN.java:53)

[2023-12-09T19:26:37.111Z] TEST: sun/security/tools/jarsigner/warnings/ChainNotValidatedTest.java
[2023-12-09T19:26:37.114Z] STDERR:
[2023-12-09T19:26:37.114Z]  stdout: [keytool error: java.security.KeyStoreException: Certificate chain is not valid
[2023-12-09T19:26:37.114Z] ];
[2023-12-09T19:26:37.114Z]  stderr: []
[2023-12-09T19:26:37.114Z]  exitValue = 1
[2023-12-09T19:26:37.114Z] 
[2023-12-09T19:26:37.114Z] java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [1]
[2023-12-09T19:26:37.114Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:490)
[2023-12-09T19:26:37.114Z] 	at Test.issueCert(Test.java:219)
[2023-12-09T19:26:37.114Z] 	at ChainNotValidatedTest.start(ChainNotValidatedTest.java:64)
[2023-12-09T19:26:37.114Z] 	at ChainNotValidatedTest.main(ChainNotValidatedTest.java:43)

[2023-12-09T19:29:18.526Z] TEST: sun/security/tools/jarsigner/CheckSignerCertChain.java
[2023-12-09T19:29:18.528Z] STDERR:
[2023-12-09T19:29:18.528Z]  stdout: [   adding: META-INF/MANIFEST.MF
[2023-12-09T19:29:18.528Z]    adding: META-INF/E1.SF
[2023-12-09T19:29:18.528Z]    adding: META-INF/E1.RSA
[2023-12-09T19:29:18.528Z]   signing: ks
[2023-12-09T19:29:18.528Z] 
[2023-12-09T19:29:18.528Z] >>> Signer
[2023-12-09T19:29:18.528Z]     X.509, CN=E1
[2023-12-09T19:29:18.528Z]     Signature algorithm: SHA384withRSA, 2048-bit key
[2023-12-09T19:29:18.528Z]     [trusted certificate]
[2023-12-09T19:29:18.528Z] 
[2023-12-09T19:29:18.528Z] jar signed.
[2023-12-09T19:29:18.528Z] 
[2023-12-09T19:29:18.528Z] Warning: 
[2023-12-09T19:29:18.528Z] The signer's certificate is self-signed.
[2023-12-09T19:29:18.528Z] ];
[2023-12-09T19:29:18.528Z]  stderr: []
[2023-12-09T19:29:18.528Z]  exitValue = 0
[2023-12-09T19:29:18.528Z] 
[2023-12-09T19:29:18.528Z] java.lang.RuntimeException: 'Signature algorithm: SHA1withRSA (disabled), 2048-bit key' missing from stdout/stderr
[2023-12-09T19:29:18.528Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
[2023-12-09T19:29:18.528Z] 	at CheckSignerCertChain.main(CheckSignerCertChain.java:84)

[2023-12-09T19:32:30.439Z] TEST: sun/security/tools/jarsigner/ConciseJarsigner.java
[2023-12-09T19:32:30.453Z] STDERR:
[2023-12-09T19:32:30.453Z]  stdout: [Command line args: [-debug, -strict, -keystore, ks, -storepass, changeit, a.jar, ee]
[2023-12-09T19:32:30.453Z] jar signed, with signer errors.
[2023-12-09T19:32:30.453Z] 
[2023-12-09T19:32:30.453Z] Error: 
[2023-12-09T19:32:30.453Z] The signer's certificate is self-signed.
[2023-12-09T19:32:30.453Z] ];
[2023-12-09T19:32:30.453Z]  stderr: []
[2023-12-09T19:32:30.453Z]  exitValue = 4
[2023-12-09T19:32:30.453Z] 
[2023-12-09T19:32:30.453Z] java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [4]
[2023-12-09T19:32:30.453Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:490)
[2023-12-09T19:32:30.453Z] 	at ConciseJarsigner.main(ConciseJarsigner.java:267)

[2023-12-09T19:32:30.453Z] TEST: sun/security/tools/jarsigner/EC.java
[2023-12-09T19:32:30.458Z] STDERR:
[2023-12-09T19:32:30.458Z]  stdout: [Command line args: [-keystore, ks, -storepass, changeit, -verify, a.jar, a, -debug, -strict]
[2023-12-09T19:32:30.458Z] jarsigner: java.lang.SecurityException: cannot verify signature block file META-INF/C
[2023-12-09T19:32:30.458Z] ];
[2023-12-09T19:32:30.458Z]  stderr: [java.lang.SecurityException: cannot verify signature block file META-INF/C
[2023-12-09T19:32:30.458Z] 	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:309)
[2023-12-09T19:32:30.458Z] 	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
[2023-12-09T19:32:30.458Z] 	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:320)
[2023-12-09T19:32:30.458Z] 	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:232)
[2023-12-09T19:32:30.458Z] 	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:760)
[2023-12-09T19:32:30.458Z] 	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:858)
[2023-12-09T19:32:30.458Z] 	at jdk.jartool/sun.security.tools.jarsigner.Main.verifyJar(Main.java:750)
[2023-12-09T19:32:30.458Z] 	at jdk.jartool/sun.security.tools.jarsigner.Main.run(Main.java:301)
[2023-12-09T19:32:30.458Z] 	at jdk.jartool/sun.security.tools.jarsigner.Main.main(Main.java:138)
[2023-12-09T19:32:30.458Z] ]
[2023-12-09T19:32:30.458Z]  exitValue = 1
[2023-12-09T19:32:30.458Z] 
[2023-12-09T19:32:30.458Z] java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [1]
[2023-12-09T19:32:30.458Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:490)
[2023-12-09T19:32:30.458Z] 	at EC.main(EC.java:85)

[2023-12-09T19:47:35.860Z] TEST: sun/security/tools/keytool/fakecacerts/TrustedCert.java
[2023-12-09T19:47:35.862Z] STDERR:
[2023-12-09T19:47:35.862Z]  stdout: [keytool error: java.security.KeyStoreException: Certificate chain is not valid
[2023-12-09T19:47:35.862Z] ];
[2023-12-09T19:47:35.862Z]  stderr: []
[2023-12-09T19:47:35.862Z]  exitValue = 1
[2023-12-09T19:47:35.862Z] 
[2023-12-09T19:47:35.862Z] java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [1]
[2023-12-09T19:47:35.862Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:490)
[2023-12-09T19:47:35.862Z] 	at TrustedCert.kt(TrustedCert.java:66)
[2023-12-09T19:47:35.862Z] 	at TrustedCert.main(TrustedCert.java:122)

[2023-12-09T19:49:01.329Z] TEST: sun/security/tools/keytool/CheckCertAKID.java
[2023-12-09T19:49:01.346Z] Exit value: 0
[2023-12-09T19:49:01.346Z] Failed to get AKID extension from the cert
[2023-12-09T19:49:01.346Z] 
[2023-12-09T19:49:01.346Z] TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details

[2023-12-09T19:52:28.385Z] TEST: sun/security/tools/keytool/GenerateAll.java
[2023-12-09T19:52:28.402Z] STDERR:
[2023-12-09T19:52:28.402Z]  stdout: [jarsigner: java.lang.SecurityException: cannot verify signature block file META-INF/EC
[2023-12-09T19:52:28.402Z] ];
[2023-12-09T19:52:28.402Z]  stderr: []
[2023-12-09T19:52:28.402Z]  exitValue = 1
[2023-12-09T19:52:28.402Z] 
[2023-12-09T19:52:28.402Z] java.lang.Exception: failures: 3
[2023-12-09T19:52:28.402Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:104)

[2023-12-09T19:55:09.740Z] TEST: sun/security/tools/keytool/SelfIssued.java
[2023-12-09T19:55:09.742Z]  stderr: []
[2023-12-09T19:55:09.742Z]  exitValue = 0
[2023-12-09T19:55:09.742Z] 
[2023-12-09T19:55:09.742Z] java.lang.RuntimeException: '[3]' missing from stdout/stderr
[2023-12-09T19:55:09.742Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
[2023-12-09T19:55:09.742Z] 	at SelfIssued.main(SelfIssued.java:60)

[2023-12-09T19:56:21.721Z] TEST: sun/security/tools/keytool/Serial64.java
[2023-12-09T19:56:21.728Z] STDERR:
[2023-12-09T19:56:21.728Z] java.lang.RuntimeException: No 64-bit serial number
[2023-12-09T19:56:21.728Z] 	at Serial64.main(Serial64.java:63)
[2023-12-09T19:56:21.728Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-12-09T19:56:21.728Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2023-12-09T19:56:21.728Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2023-12-09T19:56:21.728Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2023-12-09T19:56:21.728Z] 
[2023-12-09T19:56:21.728Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2023-12-09T19:56:21.728Z] JavaTest Message: shutting down test
[2023-12-09T19:56:21.728Z] 
[2023-12-09T19:56:21.728Z] 
[2023-12-09T19:56:21.728Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: No 64-bit serial number
[2023-12-09T19:56:21.728Z] --------------------------------------------------
[2023-12-09T20:00:34.125Z] Test results: passed: 896; failed: 9; error: 1
[2023-12-09T20:00:54.933Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_17021417656002/jdk_security3_0/report/html/report.html
[2023-12-09T20:00:54.934Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_17021417656002/jdk_security3_0/work
[2023-12-09T20:00:54.934Z] Error: Some tests failed or other problems occurred.
[2023-12-09T20:00:54.934Z] -----------------------------------
[2023-12-09T20:00:54.934Z] jdk_security3_0_FAILED
```

[15x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36867/) - all failed

[15x RI jdk_security3_0](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36868/) - 5/15 failed with machine issue `java.io.IOException: NSS initialization failed`.

**Comment by JasonFengJ9** [comment]
[JDK17 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux_testList_2/6/)(`rhel8-aarch64-3`)
```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0-m2 (build 17.0.10+6)
Eclipse OpenJ9 VM 17.0.10.0-m2 (build v0.43.0-release-628037b26, JRE 17 Linux aarch64-64-Bit Compressed References 20240116_585 (JIT enabled, AOT enabled)
OpenJ9   - 628037b26
OMR      - d810fcb98
JCL      - 6b8a7528cc1 based on jdk-17.0.10+6)

[2023-12-14T04:23:10.851Z] variation: Mode150
[2023-12-14T04:23:10.851Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2023-12-14T04:50:35.943Z] TEST: sun/security/tools/jarsigner/warnings/ChainNotValidatedTest.java
[2023-12-14T04:50:35.945Z]  stderr: []
[2023-12-14T04:50:35.945Z]  exitValue = 1
[2023-12-14T04:50:35.945Z] 
[2023-12-14T04:50:35.945Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2023-12-14T04:50:35.945Z] 
[2023-12-14T04:50:35.945Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
[2023-12-14T04:50:35.945Z] 	at Test.issueCert(Test.java:216)
[2023-12-14T04:50:35.945Z] 	at ChainNotValidatedTest.start(ChainNotValidatedTest.java:64)
[2023-12-14T04:50:35.945Z] 	at ChainNotValidatedTest.main(ChainNotValidatedTest.java:43)

[2023-12-14T05:04:59.222Z] TEST: sun/security/validator/certreplace.sh
[2023-12-14T05:04:59.223Z] Exception in thread "main" sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.validator.Validator.validate(Validator.java:231)
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.validator.Validator.validate(Validator.java:207)
[2023-12-14T05:04:59.223Z] 	at CertReplace.main(CertReplace.java:51)
[2023-12-14T05:04:59.223Z] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
[2023-12-14T05:04:59.223Z] 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[2023-12-14T05:04:59.223Z] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[2023-12-14T05:04:59.223Z] 	... 5 more

[2023-12-14T05:04:59.223Z] TEST RESULT: Failed. Execution failed: exit code 1
[2023-12-14T05:04:59.223Z] --------------------------------------------------
[2023-12-14T05:12:09.559Z] Test results: passed: 838; failed: 2
[2023-12-14T05:12:29.276Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux_testList_2/aqa-tests/TKG/output_17025277894493/jdk_security3_0/report/html/report.html
[2023-12-14T05:12:29.276Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux_testList_2/aqa-tests/TKG/output_17025277894493/jdk_security3_0/work
[2023-12-14T05:12:29.276Z] Error: Some tests failed or other problems occurred.
[2023-12-14T05:12:29.276Z] -----------------------------------
[2023-12-14T05:12:29.276Z] jdk_security3_0_FAILED
```

[15x internal grinder aarch64_linux jdk_security3_0](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36936/)
[15x RI aarch64_linux jdk_security3_0](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36937/)

**Comment by pshipton** [comment]
@KostasTsiounis @jasonkatonica this needs investigation

**Comment by pshipton** [comment]
We are running a grinder with -Xint to see if the failures are related to JIT.

**Comment by JasonFengJ9** [comment]
[JDK11 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/7/consoleFull)(`cent7-aarch64-4`)
```
12:32:21  ===============================================
12:32:21  Running test jdk_security3_0 ...
12:32:21  ===============================================
12:32:21  jdk_security3_0 Start Time: Thu Dec 14 12:32:20 2023 Epoch Time (ms): 1702575140706
12:32:21  variation: Mode150
12:32:21  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

12:52:39  TEST: sun/security/tools/jarsigner/warnings/ChainNotValidatedTest.java

12:52:39   stderr: []
12:52:39   exitValue = 1
12:52:39  
12:52:39  java.lang.RuntimeException: Expected to get exit value of [0]
12:52:39  
12:52:39  	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
12:52:39  	at Test.issueCert(Test.java:212)
12:52:39  	at ChainNotValidatedTest.start(ChainNotValidatedTest.java:64)
12:52:39  	at ChainNotValidatedTest.main(ChainNotValidatedTest.java:43)
12:52:39  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:52:39  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:52:39  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:52:39  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
12:52:39  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
12:52:39  	at java.base/java.lang.Thread.run(Thread.java:839)
12:52:39  
12:52:39  JavaTest Message: Test threw exception: java.lang.RuntimeException

13:01:37  TEST: sun/security/validator/certreplace.sh

13:01:37  Exception in thread "main" sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
13:01:37  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
13:01:37  	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
13:01:37  	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
13:01:37  	at java.base/sun.security.validator.Validator.validate(Validator.java:231)
13:01:37  	at java.base/sun.security.validator.Validator.validate(Validator.java:207)
13:01:37  	at CertReplace.main(CertReplace.java:51)
13:01:37  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
13:01:37  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
13:01:37  	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
13:01:37  	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
13:01:37  	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
13:01:37  	... 5 more

13:01:37  TEST RESULT: Failed. Execution failed: exit code 1
13:01:37  --------------------------------------------------
13:06:26  Test results: passed: 768; failed: 2
13:06:38  Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17025751409548/jdk_security3_0/report/html/report.html
13:06:38  Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17025751409548/jdk_security3_0/work
13:06:38  Error: Some tests failed or other problems occurred.
13:06:38  -----------------------------------
13:06:38  jdk_security3_0_FAILED
```
`aarch64_linux jdk_security3_0` [15x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36982/)
`aarch64_linux jdk_security3_0` [RI 15x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/36983/)

**Comment by pshipton** [comment]
This is caused by https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/91

@WilburZjh

**Comment by pshipton** [comment]
The following demonstrates the problem. When you run the below program you get all 0's in the generated byte array:
```
    public static void main(String[] args) throws Exception {
        for (int i = 0; i < 5; ++i) {
            System.out.println(Arrays.toString(new SecureRandom().generateSeed(20)));
        }
    }
```

**Comment by WilburZjh** [comment]
After rerun the failed case based on the fix, they are passed

aarch64_linux

11
[PASS] 20069-11 build with --enable-criu-support https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37150/ (jdk_security_3_0)
20070-11 build without --enable-criu-support https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37151/ (jdk_security_3_0) failed cases are passed. One known issue (https://github.com/eclipse-openj9/openj9/issues/18320)

17
[PASS] 20069-17 build with --enable-criu-support https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37139/ (jdk_security_3_0)
[PASS] 20070-17 build without --enable-criu-support https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37145/ (jdk_security_3_0)

---------

ppc64le_linux

21
[PASS] 20071-21 build with --enable-criu-support https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37138/ (jdk_security_3_0)
[PASS] 20072-21 build without --enable-criu-support https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37147/ (jdk_security_3_0)
