### ISSUE TITLE
cmdLineTester_jvmtitests_nongold re001, crash vmState=0x00000000 jvmtiHookThreadDestroy

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18621]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/120
cmdLineTester_jvmtitests_nongold_7 `-XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/120/functional_test_output.tar.gz - core but no javacore

ResourceExhausted OutOfMemory
```
Testing: re001
Test start time: 2023/12/12 20:29:20 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java"  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump    -agentlib:jvmtitest=test:re001 -Xdisableexcessivegc -Dcom.ibm.tools.attach.enable=no -Dcom.ibm.tools.attach.enable=no -Xdump:none -Xmx128M -cp "/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 3 milliseconds
Time spent executing: 45566 milliseconds
Test result: FAILED
Output from test:
 [OUT] *** Testing [1/2]:	testOutOfMemoryObject
 [ERR] Unhandled exception
 [ERR] Type=Segmentation error vmState=0x00000000
 [ERR] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=3c9d6a70 Signal_Code=00000001
 [ERR] Handler1=000003FF93A49FD8 Handler2=000003FF93931998 InaccessibleAddress=0000000000000000
 [ERR] gpr0=0000000000000000 gpr1=0000000000000020 gpr2=000003FF9418B020 gpr3=0000000000000005
 [ERR] gpr4=000003FF00000000 gpr5=000003FF9418C398 gpr6=000003FF981D0FF0 gpr7=000003FF8BB276B0
 [ERR] gpr8=0000000000000000 gpr9=0000000001B1DC00 gpr10=000003FF8BB702B0 gpr11=000003FF9418C398
 [ERR] gpr12=000003FF98499000 gpr13=00060C5A18F939E8 gpr14=000003FF93801692 gpr15=000003FF9387E320
 [ERR] psw=000003FF8BB2772A mask=0705200180000000 fpc=0008fe00 bea=000003FF8BB276DA
 [ERR] fpr0 42a4437c00000000 (f: 0.000000, d: 1.114004e+13)
 [ERR] fpr1 4040000000000000 (f: 0.000000, d: 3.200000e+01)
 [ERR] fpr2 42c7f70300000000 (f: 0.000000, d: 5.269935e+13)
 [ERR] fpr3 3ba9c5bb00000000 (f: 0.000000, d: 2.728757e-21)
 [ERR] fpr4 3f73333300000000 (f: 0.000000, d: 4.687499e-03)
 [ERR] fpr5 3e9249c900000000 (f: 0.000000, d: 2.725158e-07)
 [ERR] fpr6 42a4437c00000000 (f: 0.000000, d: 1.114004e+13)
 [ERR] fpr7 3e3a343000000000 (f: 0.000000, d: 6.101061e-09)
 [ERR] fpr8 000003ff8bdae6c8 (f: 2346379008.000000, d: 2.171961e-311)
 [ERR] fpr9 000000000b4fdae8 (f: 189782752.000000, d: 9.376514e-316)
 [ERR] fpr10 000003ff140008e0 (f: 335546592.000000, d: 2.170967e-311)
 [ERR] fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] fpr12 00060c5a18a39a3a (f: 413375040.000000, d: 8.411127e-309)
 [ERR] fpr13 000003ff9c858868 (f: 2625996800.000000, d: 2.172099e-311)
 [ERR] fpr14 000003ffd72f6dc4 (f: 3610209792.000000, d: 2.172585e-311)
 [ERR] fpr15 000003ff9c18d7e8 (f: 2618873856.000000, d: 2.172096e-311)
 [ERR] Module=/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9jvmti29.so
 [ERR] Module_base_address=000003FF8BB00000
 [ERR] Target=2_90_20231212_125 (Linux 3.10.0-1160.95.1.el7.s390x)
 [ERR] CPU=s390x (4 logical CPUs) (0x1ec1b1000 RAM)
 [ERR] 
 [ERR] JavaVMInitArgs.nOptions=22:
 [ERR]     -Xoptionsfile=/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/options.default
 [ERR]     -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple
 [ERR]     -XX:+EnsureHashed:java/lang/Class,java/lang/Thread
 [ERR]     -Xjcl:jclse29
 [ERR]     -Dcom.ibm.oti.vm.bootstrap.library.path=/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default:/home/jenkins/workspace/Test_openjdk21_j9_extended.functio
 [ERR] Generated system dump: core.7764
 [ERR] ----------- Stack Backtrace -----------
 [ERR] jvmtiHookThreadDestroy+0x7a (0x000003FF8BB2772A [libj9jvmti29.so+0x2772a])
 [ERR] J9HookDispatch+0x172 (0x000003FF93801692 [libj9hookable29.so+0x1692])
 [ERR] deallocateVMThread+0x3ee (0x000003FF93A61CD6 [libj9vm29.so+0x61cd6])
 [ERR] protectedInternalAttachCurrentThread+0x28c (0x000003FF93A57A0C [libj9vm29.so+0x57a0c])
 [ERR] omrsig_protect+0x3d8 (0x000003FF93932AE8 [libj9prt29.so+0x32ae8])
 [ERR] internalAttachCurrentThread+0x6a (0x000003FF93A57FA2 [libj9vm29.so+0x57fa2])
 [ERR] attachSystemDaemonThread+0x66 (0x000003FF93A586FE [libj9vm29.so+0x586fe])
 [ERR] FinalizeWorkerThreadGlue+0x5e (0x000003FF8BDAEE3E [libj9gc29.so+0x2ee3e])
 [ERR] omrsig_protect+0x3d8 (0x000003FF93932AE8 [libj9prt29.so+0x32ae8])
 [ERR] gpProtectedFinalizeWorkerThread+0x4a (0x000003FF8BDAE712 [libj9gc29.so+0x2e712])
 [ERR] thread_wrapper+0xf6 (0x000003FF93888A46 [libj9thr29.so+0x8a46])
 [ERR] start_thread+0xea (0x000003FF98488312 [libpthread.so.0+0x8312])
 [ERR]  (0x000003FF9830E232 [libc.so.6+0x10e232])
```

**Comment by gacholio** [comment]
This is a failure to attach the finalizer thread (so not likely to occur in real life).

I suspect the issue here is that the `threadObject` field is not initialized in the `J9VMThread`. `destroyThreadData` has likely been inlined into `jvmtiHookThreadDestroy` and it assumes the field is valid.

Adding a NULL check on `threadObject` in `destroyThreadData` will probably fix this.

**Comment by pshipton** [comment]
@TobiAjila @babsingh fyi

**Comment by babsingh** [comment]
Here is the native `stacktrace` from `gdb`:

```
#0  0x000003ff9848d484 in pthread_kill () from /lib64/libpthread.so.0
#1  0x000003ff93930a28 in omrdump_create (portLibrary=0x3ff981d0ff0 <j9portLibrary>, filename=0x3ff9387c400 "", dumpType=<optimized out>, userData=<optimized out>)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/omr/port/unix/omrosdump.c:188
#2  0x000003ff93a49a5c in generateSystemDump (portLibrary=0x3ff981d0ff0 <j9portLibrary>, gpInfo=<optimized out>) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/vm/gphandle.c:904
#3  0x000003ff93a49c22 in generateDiagnosticFiles (portLibrary=portLibrary@entry=0x3ff981d0ff0 <j9portLibrary>, userData=userData@entry=0x3ff9387cc48)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/vm/gphandle.c:1152
#4  0x000003ff93932ae8 in omrsig_protect (portLibrary=0x3ff981d0ff0 <j9portLibrary>, fn=0x3ff93a49ab8 <generateDiagnosticFiles>, fn_arg=0x3ff9387cc48, handler=0x3ff93a49040 <recursiveCrashHandler>, handler_arg=0x3ff9387cc20,
    flags=505, result=0x3ff9387cc18) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/omr/port/unix/omrsignal.c:425
#5  0x000003ff93a49dac in structuredSignalHandler (portLibrary=0x3ff981d0ff0 <j9portLibrary>, gpType=<optimized out>, gpInfo=0x3ff9387dda0, userData=<optimized out>)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/vm/gphandle.c:837
#6  0x000003ff93931bb6 in mainSynchSignalHandler (signal=<optimized out>, sigInfo=0x3ff9387dea0, contextInfo=0x3ff9387df20, breakingEventAddr=<optimized out>)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/omr/port/unix/omrsignal.c:1066
#7  <signal handler called>
#8  0x000003ff8bb2772a in jvmtiHookThreadDestroy (hook=<optimized out>, eventNum=<optimized out>, eventData=<optimized out>, userData=0x3ff9418c398)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/jvmti/jvmtiHook.c:248
#9  0x000003ff93801692 in J9HookDispatch (hookInterface=0x3ff94016de0, taggedEventNum=<optimized out>, eventData=0x3ff9387e568) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/omr/util/hookable/hookable.cpp:235
#10 0x000003ff93a61cd6 in deallocateVMThread (vmThread=vmThread@entry=0x1b1dc00, decrementZombieCount=decrementZombieCount@entry=0, sendThreadDestroyEvent=sendThreadDestroyEvent@entry=1)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/vm/jvmfree.c:230
#11 0x000003ff93a57a0c in protectedInternalAttachCurrentThread (portLibrary=portLibrary@entry=0x3ff981d0ff0 <j9portLibrary>, userData=userData@entry=0x3ff9387e948)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/vm/jniinv.c:737
#12 0x000003ff93932ae8 in omrsig_protect (portLibrary=0x3ff981d0ff0 <j9portLibrary>, fn=0x3ff93a57780 <protectedInternalAttachCurrentThread>, fn_arg=0x3ff9387e948, handler=0x3ff93a49fd8 <structuredSignalHandlerVM>,
    handler_arg=0x3ff94014a60, flags=506, result=0x3ff9387e940) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/omr/port/unix/omrsignal.c:425
#13 0x000003ff93a57fa2 in internalAttachCurrentThread (vm=vm@entry=0x3ff94014a60, p_env=p_env@entry=0x3ff9387eb28, thr_args=thr_args@entry=0x3ff9387ea18, threadType=threadType@entry=18, osThread=osThread@entry=0x3ff14000a20)
    at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/vm/jniinv.c:771
#14 0x000003ff93a586fe in attachSystemDaemonThread (vm=0x3ff94014a60, p_env=0x3ff9387eb28, threadName=0x3ff8bfbddb0 "Finalizer thread") at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/vm/jniinv.c:917
#15 0x000003ff8bdaee3e in FinalizeWorkerThread (arg=0x3ff140008e0) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/gc_base/FinalizerSupport.cpp:462
#16 FinalizeWorkerThreadGlue (portLib=portLib@entry=0x3ff981d0ff0 <j9portLibrary>, userData=userData@entry=0x3ff140008e0) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/gc_base/FinalizerSupport.cpp:777
#17 0x000003ff93932ae8 in omrsig_protect (portLibrary=0x3ff981d0ff0 <j9portLibrary>, fn=0x3ff8bdaede0 <FinalizeWorkerThreadGlue(J9PortLibrary*, void*)>, fn_arg=0x3ff140008e0, handler=0x3ff93a49fd8 <structuredSignalHandlerVM>,
    handler_arg=0x3ff94014a60, flags=506, result=0x3ff9387ee38) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/omr/port/unix/omrsignal.c:425
#18 0x000003ff8bdae712 in gpProtectedFinalizeWorkerThread (entryArg=<optimized out>) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/openj9/runtime/gc_base/FinalizerSupport.cpp:787
#19 0x000003ff93888a46 in thread_wrapper (arg=0x3ff14000a20) at /home/jenkins/workspace/Build_JDK21_s390x_linux_Nightly/omr/thread/common/omrthread.c:1724
#20 0x000003ff98488312 in start_thread () from /lib64/libpthread.so.0
#21 0x000003ff9830e232 in thread_start () from /lib64/libc.so.6
```

It shows that the segfault happened at `jvmtiHook.c:248`, which doesn't seem correct:
https://github.com/eclipse-openj9/openj9/blob/1b60ab8285365dc2d69b56fb3b27828de604d74f/runtime/jvmti/jvmtiHook.c#L248

@gacholio's analysis in https://github.com/eclipse-openj9/openj9/issues/18621#issuecomment-1877599516 is plausible and supported by DDR output:
```
> !j9vmthread 0x1b1dc00 | grep -i threadobject
    0xa8: struct J9Object* threadObject = !j9object 0x0000000000000000
    0xb98: struct J9Object* carrierThreadObject = !j9object 0x0000000000000000

> !j9javavm 0x000003FF94014A60 | grep -i jvmtidata
    0x2378: void* jvmtiData = !j9x 0x000003FF9418B020
```

Opened https://github.com/eclipse-openj9/openj9/pull/18688 to add a `NULL` check on `threadObject` in `destroyThreadData`.
