### ISSUE TITLE
TestGetSystemCpuLoad - unexpected error value expected:<-1.0> but was:<-21.0>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18634]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/675/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/674/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_0/645
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_1/645/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_mac_Nightly_testList_1/397/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_linux_Nightly_testList_1/562
testCpuUtilization_testSingleCpuLoadObject_0
```
FAILED: testSingleCpuLoadObject
java.lang.AssertionError: unexpected error value expected:<-1.0> but was:<-21.0>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:126)
	at org.openj9.test.management.TestGetSystemCpuLoad.validateLoad(TestGetSystemCpuLoad.java:119)
	at org.openj9.test.management.TestGetSystemCpuLoad.testMxBeanImpl(TestGetSystemCpuLoad.java:74)
	at org.openj9.test.management.TestGetSystemCpuLoad.testSingleCpuLoadObject(TestGetSystemCpuLoad.java:50)
```

testCpuUtilization_testMxBean_0
```
FAILED: testMxBean
java.lang.AssertionError: unexpected error value expected:<-1.0> but was:<-21.0>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:126)
	at org.openj9.test.management.TestGetSystemCpuLoad.validateLoad(TestGetSystemCpuLoad.java:119)
	at org.openj9.test.management.TestGetSystemCpuLoad.testMxBeanImpl(TestGetSystemCpuLoad.java:74)
	at org.openj9.test.management.TestGetSystemCpuLoad.testMxBean(TestGetSystemCpuLoad.java:65)
```

**Comment by pshipton** [comment]
Related to https://github.com/eclipse-openj9/openj9/pull/18451
@TobiAjila @thallium 

OMRPORT_ERROR_INSUFFICIENT_DATA is -21

I don't think returning -21 is the expected behavior. I'm going to revert the change to avoid failing builds until it can be fixed.

This is only failing on jdk11 last night because the other build started before the change was merged.

**Comment by pshipton** [comment]
Reverted via https://github.com/eclipse-openj9/openj9/pull/18635

**Comment by thallium** [comment]
I fixed the PR to return -1 if only one data point is recorded.
