### ISSUE TITLE
mauve IllegalMonitorStateException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18645]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=74213619)
[AIX] 70 Load_Level_2.mauve.5mins.Mode121 `-Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs`
aix72p9-01
```
j> 11:00:08 20231218 11:00:07 Runtime State Reporter IMPORTANT: 51343 tests complete, 30 currently running
j> 11:00:34 20231218 11:00:33 PooledRunnable-Thread 37 ERROR: Pooled thread 'Pooled Thread #37 waiting to run gnu.testlet.java.lang.Character.hash' terminated with unexpected exception
j> 11:00:34 Throwable trace:
j> 11:00:34 java.lang.IllegalMonitorStateException
j> 11:00:34     at java.lang.Object.wait(Native Method)
j> 11:00:34     at java.lang.Object.wait(Object.java:172)
j> 11:00:34     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.waitForGo(PooledRunnable.java:147)
j> 11:00:34     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:130)
j> 11:00:34     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 11:00:34     at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 11:00:37 20231218 11:00:37 Runtime State Reporter IMPORTANT: 89731 tests complete, 77 currently running
j> 11:00:39 20231218 11:00:38 PooledRunnable-Thread 133 ERROR: Pooled thread 'Pooled Thread #133 waiting to run gnu.testlet.java.util.AbstractMap.AcuniaAbstractMapTest' terminated with unexpected exception
j> 11:00:39 Throwable trace:
j> 11:00:39 java.lang.IllegalMonitorStateException
j> 11:00:39     at java.lang.Object.wait(Native Method)
j> 11:00:39     at java.lang.Object.wait(Object.java:172)
j> 11:00:39     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.waitForGo(PooledRunnable.java:147)
j> 11:00:39     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:130)
j> 11:00:39     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 11:00:39     at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 11:01:07 20231218 11:01:07 Runtime State Reporter IMPORTANT: 128001 tests complete, 163 currently running
j> 11:01:37 20231218 11:01:37 Runtime State Reporter IMPORTANT: 166292 tests complete, 0 currently running
j> 11:01:55 20231218 11:01:55 PooledRunnable-Thread 232 ERROR: Pooled thread 'Pooled Thread #232 waiting to run gnu.testlet.java.io.Utf8Encoding.ReadReference' terminated with unexpected exception
j> 11:01:55 Throwable trace:
j> 11:01:55 java.lang.IllegalMonitorStateException
j> 11:01:55     at java.lang.Object.wait(Native Method)
j> 11:01:55     at java.lang.Object.wait(Object.java:172)
j> 11:01:55     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.waitForGo(PooledRunnable.java:147)
j> 11:01:55     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:130)
j> 11:01:55     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 11:01:55     at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 11:02:07 20231218 11:02:07 Runtime State Reporter IMPORTANT: 204388 tests complete, 7 currently running
j> 11:02:12 20231218 11:02:11 PooledRunnable-Thread 267 ERROR: Pooled thread 'Pooled Thread #267 waiting to run gnu.testlet.java.lang.System.arraycopy' terminated with unexpected exception
j> 11:02:12 Throwable trace:
j> 11:02:12 java.lang.IllegalMonitorStateException
j> 11:02:12     at java.lang.Object.wait(Native Method)
j> 11:02:12     at java.lang.Object.wait(Object.java:172)
j> 11:02:12     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.waitForGo(PooledRunnable.java:147)
j> 11:02:12     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:130)
j> 11:02:12     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 11:02:12     at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 11:02:37 20231218 11:02:37 Runtime State Reporter IMPORTANT: 241763 tests complete, 237 currently running
j> 11:03:07 20231218 11:03:07 Runtime State Reporter IMPORTANT: 279861 tests complete, 97 currently running
j> 11:03:17 20231218 11:03:16 PooledRunnable-Thread 223 ERROR: Pooled thread 'Pooled Thread #223 waiting to run gnu.testlet.java.io.BufferedReader.SimpleRead' terminated with unexpected exception
j> 11:03:17 Throwable trace:
j> 11:03:17 java.lang.IllegalMonitorStateException
j> 11:03:17     at java.lang.Object.wait(Native Method)
j> 11:03:17     at java.lang.Object.wait(Object.java:172)
j> 11:03:17     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.waitForGo(PooledRunnable.java:147)
j> 11:03:17     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:130)
j> 11:03:17     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 11:03:17     at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 11:03:37 20231218 11:03:37 Runtime State Reporter IMPORTANT: 318071 tests complete, 100 currently running
j> 11:03:43 20231218 11:03:42 PooledRunnable-Thread 14 ERROR: Pooled thread 'Pooled Thread #14 waiting to run gnu.testlet.java.lang.Math.rint' terminated with unexpected exception
j> 11:03:43 Throwable trace:
j> 11:03:43 java.lang.IllegalMonitorStateException
j> 11:03:43     at java.lang.Object.wait(Native Method)
j> 11:03:43     at java.lang.Object.wait(Object.java:172)
j> 11:03:43     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.waitForGo(PooledRunnable.java:147)
j> 11:03:43     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:130)
j> 11:03:43     at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 11:03:43     at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
```

**Comment by pshipton** [comment]
3/100 failures on the previous build without the changes for 150027.
The failures were all on paix801 and 802.

@zl-wang can someone take a look pls, although if Java 7.1 doesn't support Power 9 we could probably ignore it.
