### ISSUE TITLE
cmdLineTester_criu_nonPortableRestore, PropertiesTest3

### ISSUE THREAD

**Issue by singh264** [eclipse-openj9/openj9#18653]
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37029/
cmdLineTester_criu_nonPortableRestore_2
JDK_VERSION = 11

```
[2023-12-19T10:51:02.512Z] Testing: Properties test3
[2023-12-19T10:51:02.512Z] Test start time: 2023/12/19 02:51:02 Pacific Standard Time
[2023-12-19T10:51:02.512Z] Running command: bash /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/bin/java " -XX:+JVMPortableRestoreMode " org.openj9.criu.OptionsFileTest PropertiesTest3 1
[2023-12-19T10:51:02.512Z] Time spent starting: 1 milliseconds
[2023-12-19T10:51:05.284Z] Time spent executing: 2881 milliseconds
[2023-12-19T10:51:05.284Z] Test result: FAILED
[2023-12-19T10:51:05.284Z] Output from test:
[2023-12-19T10:51:05.284Z]  [OUT] start running script
[2023-12-19T10:51:05.284Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2023-12-19T10:51:05.284Z]  [OUT] export LD_BIND_NOT=on
[2023-12-19T10:51:05.284Z]  [OUT] /home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/bin/java -XX:+EnableCRIUSupport  -XX:+JVMPortableRestoreMode  -cp /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar org.openj9.criu.OptionsFileTest PropertiesTest3 1
[2023-12-19T10:51:05.284Z]  [OUT] Pre-checkpoint
[2023-12-19T10:51:05.284Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Tue Dec 19 02:51:02 PST 2023, System.currentTimeMillis(): 1702983062312, System.nanoTime(): 1702982949330847301
[2023-12-19T10:51:05.284Z]  [OUT] JVMJITM044W Some or all compiled code in the code cache invalidated post restore.
[2023-12-19T10:51:05.284Z]  [OUT] Post-checkpoint
[2023-12-19T10:51:05.284Z]  [OUT] Exception in thread "Attach API wait loop" java.lang.NullPointerException
[2023-12-19T10:51:05.285Z]  [OUT] 	at java.base/openj9.internal.tools.attach.target.TargetDirectory.ensureMyAdvertisementExists(TargetDirectory.java:239)
[2023-12-19T10:51:05.285Z]  [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:123)
[2023-12-19T10:51:05.285Z]  [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
[2023-12-19T10:51:05.285Z]  [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:110)
[2023-12-19T10:51:05.285Z]  [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
[2023-12-19T10:51:05.285Z]  [OUT] Removed test output files
[2023-12-19T10:51:05.285Z]  [OUT] finished script
[2023-12-19T10:51:05.285Z]  [ERR] /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 41:  4128 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 $6 > testOutput 2>&1
[2023-12-19T10:51:05.285Z] >> Success condition was found: [Output match: Killed]
[2023-12-19T10:51:05.285Z] >> Failure condition was not found: [Output match: failed properties test]
[2023-12-19T10:51:05.285Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2023-12-19T10:51:05.285Z] >> Success condition was found: [Output match: Post-checkpoint]
[2023-12-19T10:51:05.285Z] >> Failure condition was found: [Output match: java.lang.NullPointerException]
[2023-12-19T10:51:05.285Z] >> Failure condition was not found: [Output match: org.eclipse.openj9.criu.JVMRestoreException]
[2023-12-19T10:51:05.285Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2023-12-19T10:51:05.285Z] >> Failure condition was not found: [Output match: Operation not permitted]
[2023-12-19T10:51:05.285Z] >> Success condition was not found: [Output match: Thread pid mismatch]
[2023-12-19T10:51:05.285Z] >> Success condition was not found: [Output match: do not match expected]
[2023-12-19T10:51:05.285Z] >> Success condition was not found: [Output match: Unable to create a thread:]
[2023-12-19T10:51:05.285Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
[2023-12-19T10:51:05.285Z] >> Failure condition was not found: [Output match: User requested Java dump using]
```

The grinder was started to test the CRIU install on `sles12s390x-svl-rt6-1.fyre.ibm.com` for https://github.ibm.com/runtimes/infrastructure/issues/8729.

**Comment by singh264** [comment]
@tajila a [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37154/) running PropertiesTest3 100 times on 5 s390x linux machines passed.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_OMR_testList_0/60
cmdLineTester_criu_nonPortableRestore_2
```
Testing: Properties test3
Test start time: 2024/01/09 07:28:44 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_OMR_testList_0/jdkbinary/j2sdk-image/bin/java " -XX:+JVMPortableRestoreMode " org.openj9.criu.OptionsFileTest PropertiesTest3 1
Time spent starting: 11 milliseconds
Time spent executing: 4319 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_OMR_testList_0/jdkbinary/j2sdk-image/bin/java -XX:+EnableCRIUSupport  -XX:+JVMPortableRestoreMode  -cp /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar org.openj9.criu.OptionsFileTest PropertiesTest3 1
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Tue Jan 09 07:28:45 EST 2024, System.currentTimeMillis(): 1704803325297, System.nanoTime(): 1704803325295737820
 [OUT] JVMJITM044W Some or all compiled code in the code cache invalidated post restore.
 [OUT] Post-checkpoint
 [OUT] Exception in thread "Attach API wait loop" java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "openj9.internal.tools.attach.target.TargetDirectory.advertisementFileObject" is null
 [OUT] 	at java.base/openj9.internal.tools.attach.target.TargetDirectory.ensureMyAdvertisementExists(TargetDirectory.java:239)
 [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:102)
 [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
 [OUT] Removed test output files
 [OUT] finished script
 [ERR] /home/jenkins/workspace/Test_openjdk21_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 41: 30726 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 $6 > testOutput 2>&1
>> Success condition was found: [Output match: Killed]
>> Failure condition was not found: [Output match: failed properties test]
>> Required condition was found: [Output match: Pre-checkpoint]
>> Success condition was found: [Output match: Post-checkpoint]
>> Failure condition was found: [Output match: java.lang.NullPointerException]
>> Failure condition was not found: [Output match: org.eclipse.openj9.criu.JVMRestoreException]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
>> Failure condition was not found: [Output match: User requested Java dump using]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly_testList_0/2
cmdLineTester_criu_nonPortableRestore_8
```
05:30:01  Testing: Properties test1
05:30:01  Test start time: 2024/02/07 05:30:00 Eastern Standard Time
05:30:01  Running command: bash /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java " -Xgcpolicy:gencon -Xgcthreads1 " org.openj9.criu.OptionsFileTest PropertiesTest1 1
05:30:01  Time spent starting: 1 milliseconds
05:30:02  Time spent executing: 2352 milliseconds
05:30:02  Test result: FAILED
05:30:02  Output from test:
05:30:02   [OUT] start running script
05:30:02   [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
05:30:02   [OUT] export LD_BIND_NOT=on
05:30:02   [OUT] /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java -XX:+EnableCRIUSupport  -Xgcpolicy:gencon -Xgcthreads1  -cp /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar org.openj9.criu.OptionsFileTest PropertiesTest1 1
05:30:02   [OUT] Pre-checkpoint
05:30:02   [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Feb 07 05:30:00 EST 2024, System.currentTimeMillis(): 1707301800643, System.nanoTime(): 1707301800639349676
05:30:02   [OUT] JVMJITM044W Some or all compiled code in the code cache invalidated post restore.
05:30:02   [OUT] Post-checkpoint
05:30:02   [OUT] Exception in thread "Attach API wait loop" java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "openj9.internal.tools.attach.target.TargetDirectory.advertisementFileObject" is null
05:30:02   [OUT] 	at java.base/openj9.internal.tools.attach.target.TargetDirectory.ensureMyAdvertisementExists(TargetDirectory.java:239)
05:30:02   [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:102)
05:30:02   [OUT] 	at java.base/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
05:30:02   [OUT] Removed test output files
05:30:02   [OUT] finished script
05:30:02   [ERR] /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 41: 64138 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 $6 > testOutput 2>&1
05:30:02  >> Success condition was found: [Output match: Killed]
05:30:02  >> Failure condition was not found: [Output match: failed properties test]
05:30:02  >> Required condition was found: [Output match: Pre-checkpoint]
05:30:02  >> Success condition was found: [Output match: Post-checkpoint]
05:30:02  >> Failure condition was found: [Output match: java.lang.NullPointerException]
05:30:02  >> Failure condition was not found: [Output match: org.eclipse.openj9.criu.JVMRestoreException]
05:30:02  >> Failure condition was not found: [Output match: CRIU is not enabled]
05:30:02  >> Failure condition was not found: [Output match: Operation not permitted]
05:30:02  >> Success condition was not found: [Output match: Thread pid mismatch]
05:30:02  >> Success condition was not found: [Output match: do not match expected]
05:30:02  >> Success condition was not found: [Output match: Unable to create a thread:]
05:30:02  >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
05:30:02  >> Failure condition was not found: [Output match: User requested Java dump using]
```

**Comment by singh264** [comment]
How can I know if the issue can be closed as the problem last occurred on Feb 7?
