### ISSUE TITLE
JDK8 [Linux Hammer Compressed Pointers] 80 VM_Extended.testDTFJ.Mode610.1 Failed to find known symbol JNI_CreateJavaVM in any library

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18665]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=74359881)(`sles12x64-1-2`):
```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pxa6480sr9-20231020_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20231219_62628 (JIT enabled, AOT enabled)
OpenJ9   - 4f0f9ce
OMR      - cafed25
IBM      - 7394519)
JCL - 20231012_01 based on Oracle jdk8u391-b13
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
JUnit.summary:
  [summary] Processed 137 test cases
     [echo] Test failure : com.ibm.dtfj.tests.junit.ImageSymbolTest
     [echo] Test case    : testGetKnownSymbol
     [echo] Failure type : junit.framework.AssertionFailedError
     [echo] junit.framework.AssertionFailedError: Failed to find known symbol JNI_CreateJavaVM in any library
     [echo] 	at com.ibm.dtfj.tests.junit.ImageSymbolTest.testGetKnownSymbol(ImageSymbolTest.java:160)
     [echo] 	at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)
     [echo] 
     [echo] Test failure : com.ibm.dtfj.tests.junit.ImageSymbolTest
     [echo] Test case    : testGetKnownSymbol
     [echo] Failure type : junit.framework.AssertionFailedError
     [echo] junit.framework.AssertionFailedError: Failed to find known symbol JNI_CreateJavaVM in any library
     [echo] 	at com.ibm.dtfj.tests.junit.ImageSymbolTest.testGetKnownSymbol(ImageSymbolTest.java:160)
     [echo] 	at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)

BUILD FAILED
/bluebird/builds/bld_62628/jvmtest/VM/dtfj_tck/tck.xml:377: One or more TCK runs failed a junit test
```

[100x internal grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=62652)

**Comment by pshipton** [comment]
This is caused by the change to use gcc 11.2. It's also internal issue 143389. There was a doc update made some time ago which is related, https://github.com/eclipse-openj9/openj9-docs/pull/715.

@keithc-ca fyi, not sure if we can do anything about it.

**Comment by JasonFengJ9** [comment]
[[Linux S390] 80 VM_Extended.testDTFJ.Mode110.1](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=115198913)
```
JUnit.summary:
  [summary] Processed 137 test cases
     [echo] Test failure : com.ibm.dtfj.tests.junit.ImageSymbolTest
     [echo] Test case    : testGetKnownSymbol
     [echo] Failure type : junit.framework.AssertionFailedError
     [echo] junit.framework.AssertionFailedError: Failed to find known symbol JNI_CreateJavaVM in any library
     [echo] 	at com.ibm.dtfj.tests.junit.ImageSymbolTest.testGetKnownSymbol(ImageSymbolTest.java:160)
     [echo] 	at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)
     [echo] 
     [echo] Test failure : com.ibm.dtfj.tests.junit.ImageSymbolTest
     [echo] Test case    : testGetKnownSymbol
     [echo] Failure type : junit.framework.AssertionFailedError
     [echo] junit.framework.AssertionFailedError: Failed to find known symbol JNI_CreateJavaVM in any library
     [echo] 	at com.ibm.dtfj.tests.junit.ImageSymbolTest.testGetKnownSymbol(ImageSymbolTest.java:160)
     [echo] 	at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)

BUILD FAILED
/j9vm/ascii/builds/bld_103933/jvmtest/VM/dtfj_tck/tck.xml:377: One or more TCK runs failed a junit test
```
