### ISSUE TITLE
JDK8 [linux_390] SE80_GIT cmdLineTest_stackSizeInfoTest_0

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18664]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=74364263)(`rhel7s390x-1-4`):
```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pxz3180sr9-20231020_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux s390-31-Bit 20231219_62628 (JIT enabled, AOT enabled)
OpenJ9   - 4f0f9ce
OMR      - cafed25
IBM      - 7394519)
JCL - 20231012_01 based on Oracle jdk8u391-b13
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
Testing: Running threads stack size info test
Test start time: 2023/12/19 19:32:35 Pacific Standard Time
Running command: "/j9vm/ascii/builds/bld_62628/sdk/xz3180/bin/java"   -verbose:stack -cp "/j9vm/ascii/builds/bld_62628/jvmtest/test/SE80/functional/cmdline_options_testresources/cmdlinetestresources.jar" j9vm.test.printstacktest.RunningThreadsStackSizeTest
Time spent starting: 7 milliseconds
Exception in thread "Thread-4" java.lang.StackOverflowError
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3800)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4810)

	at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
	at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4829)
	at java.util.regex.Pattern$Prolog.match(Pattern.java:4766)
	at java.util.regex.Pattern$Slice.match(Pattern.java:3997)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4742)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4593)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3823)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
	at java.util.regex.Pattern$Slice.match(Pattern.java:3997)
	at java.util.regex.Pattern$GroupCurly.match0(Pattern.java:4488)
	at java.util.regex.Pattern$GroupCurly.match(Pattern.java:4430)
	at java.util.regex.Pattern$BnM.match(Pattern.java:5494)
	at java.util.regex.Matcher.search(Matcher.java:1259)
	at java.util.regex.Matcher.find(Matcher.java:648)
	at OutputRegexHelper.ContainsMatches(OutputRegexHelper.java:41)
	at Output.match(Output.java:84)
	at Test$StreamMatcher.run(Test.java:516)
Time spent executing: 530 milliseconds
Test result: FAILED
Output from test:
 [ERR] JVMVERB000I Verbose stack: "Attach API initializer" used 1172/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "Attach API wait loop" used 212/0 bytes on Java/C stacks
 [ERR] JVMVERB027I Verbose stack: Running thread "RunningThread1" is using 160/0 bytes on Java/C stacks
 [ERR] JVMVERB027I Verbose stack: Running thread "RunningThread2" is using 160/0 bytes on Java/C stacks
 [ERR] JVMVERB027I Verbose stack: Running thread "Attach API teardown" is using 772/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "main" used 1560/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-000" used 224/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-006" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-005" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-004" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-003" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-002" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-001" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "Attach API teardown" used 772/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Diagnostic Compilation Thread-007" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "IProfiler" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT-SamplerThread" used 160/0 bytes on Java/C stacks
>> Success condition was not found: [Output match: Verbose stack: Unable to print the stack info for currently running threads]
>> Success condition was not found: [Output match: \[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "RunningThread(1|2)" is using(\n|.)*(\s)+\[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "RunningThread(1|2)" is using]
>> Failure condition was not found: [Output match: Verbose stack: Unable to print the stack info for currently running threads(\n|.)*\[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "(.)*" is using]
>> Failure condition was not found: [Output match: \[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "(.)*" is using(.|\n)*Verbose stack: Unable to print the stack info for currently running threads]
>> Failure condition was not found: [Output match: The thread should not have been interrupted!]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]


---TEST RESULTS---
Number of PASSED tests: 1 out of 2
Number of FAILED tests: 1 out of 2

---SUMMARY OF FAILED TESTS---
Running threads stack size info test

TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAILED test targets:
	cmdLineTest_stackSizeInfoTest_0

TOTAL: 1   EXECUTED: 1   PASSED: 0   FAILED: 1   DISABLED: 0   SKIPPED: 0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

[100x internal grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=62651)

**Comment by pshipton** [comment]
The grinder failed 12/100. This isn't a new failure, looking at the history the oldest one I see is from 2023-08-23.
It passed 300 grinders with -Xint.

**Comment by JasonFengJ9** [comment]
[[aix_ppc] SE80_GIT cmdLineTest_stackSizeInfoTest_0](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=79692130)(`aix72p9-03`)
```
java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pap3280sr9-20240201_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc-32-Bit 20240305_67018 (JIT enabled, AOT enabled)
OpenJ9   - 9a4ec54
OMR      - f9eee63
IBM      - b81b1e2)
JCL - 20231221_01 based on Oracle jdk8u401-b10

variation: NoOptions
JVM_OPTIONS:  

Testing: Running threads stack size info test
Test start time: 2024/03/05 22:49:42 Eastern Standard Time
Running command: "/bluebird/builds/bld_67018/sdk/ap3280/bin/java"   -verbose:stack -cp "/bluebird/builds/bld_67018/jvmtest/test/SE80/functional/cmdline_options_testresources/cmdlinetestresources.jar" j9vm.test.printstacktest.RunningThreadsStackSizeTest
Time spent starting: 20 milliseconds
Exception in thread "Thread-4" java.lang.StackOverflowError
        at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
        at java.util.regex.Pattern$Loop.match(Pattern.java:4810)
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4742)
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4593)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3802)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4629)

        at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
        at java.util.regex.Pattern$Slice.match(Pattern.java:3997)
        at java.util.regex.Pattern$GroupCurly.match0(Pattern.java:4488)
        at java.util.regex.Pattern$GroupCurly.match(Pattern.java:4430)
        at java.util.regex.Pattern$BnM.match(Pattern.java:5494)
        at java.util.regex.Matcher.search(Matcher.java:1259)
        at java.util.regex.Matcher.find(Matcher.java:648)
        at OutputRegexHelper.ContainsMatches(OutputRegexHelper.java:41)
        at Output.match(Output.java:84)
        at Test$StreamMatcher.run(Test.java:516)
Time spent executing: 630 milliseconds
Test result: FAILED
Output from test:
 [ERR] JVMVERB000I Verbose stack: "Attach API initializer" used 1224/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "Attach API wait loop" used 212/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "Attach API teardown" used 432/0 bytes on Java/C stacks
 [ERR] JVMVERB027I Verbose stack: Running thread "RunningThread1" is using 160/0 bytes on Java/C stacks
 [ERR] JVMVERB027I Verbose stack: Running thread "RunningThread2" is using 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "main" used 1648/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-001" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-002" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-000" used 224/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-005" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-004" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-003" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-006" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Diagnostic Compilation Thread-007" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "IProfiler" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT-SamplerThread" used 160/0 bytes on Java/C stacks
>> Success condition was not found: [Output match: Verbose stack: Unable to print the stack info for currently running threads]
>> Success condition was not found: [Output match: \[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "RunningThread(1|2)" is using(\n|.)*(\s)+\[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "RunningThread(1|2)" is using]
>> Failure condition was not found: [Output match: Verbose stack: Unable to print the stack info for currently running threads(\n|.)*\[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "(.)*" is using]
>> Failure condition was not found: [Output match: \[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "(.)*" is using(.|\n)*Verbose stack: Unable to print the stack info for currently running threads]
>> Failure condition was not found: [Output match: The thread should not have been interrupted!]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]


---TEST RESULTS---
Number of PASSED tests: 1 out of 2
Number of FAILED tests: 1 out of 2

---SUMMARY OF FAILED TESTS---
Running threads stack size info test
-----------------------------

Running compression command: jar cvf /tmp/results-796921300.jar .
Compression was successful.Attempting to upload compressed file.Upload appears to have been successful.
cmdLineTest_stackSizeInfoTest_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[[linux_390] SE80_GIT cmdLineTest_stackSizeInfoTest_0](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=81431502)(`rhel7s390x-1-3`)

**Comment by JasonFengJ9** [comment]
[[linux_390] SE80_GIT cmdLineTest_stackSizeInfoTest_0](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=92102266)(`fyrlx806`)
```
===============================================
Running test cmdLineTest_stackSizeInfoTest_0 ...
===============================================
cmdLineTest_stackSizeInfoTest_0 Start Time: Fri Sep 13 19:35:12 2024 Epoch Time (ms): 1726281312888
"/j9vm/ascii/builds/bld_77982/sdk/xz3180/bin/java" -Xshareclasses:destroyAll; "/j9vm/ascii/builds/bld_77982/sdk/xz3180/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
JVMSHRC005I No shared class caches available
JVMSHRC005I No shared class caches available
cache cleanup done
variation: NoOptions
JVM_OPTIONS:  

Testing: Running threads stack size info test
Test start time: 2024/09/13 19:35:13 Pacific Standard Time
Running command: "/j9vm/ascii/builds/bld_77982/sdk/xz3180/bin/java"   -verbose:stack -cp "/j9vm/ascii/builds/bld_77982/jvmtest/test/SE80/functional/cmdline_options_testresources/cmdlinetestresources.jar" j9vm.test.printstacktest.RunningThreadsStackSizeTest
Time spent starting: 2 milliseconds
Exception in thread "Thread-4" java.lang.StackOverflowError
	at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4810)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4742)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4593)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3802)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)

	at java.util.regex.Matcher.search(Matcher.java:1259)
	at java.util.regex.Matcher.find(Matcher.java:648)
	at OutputRegexHelper.ContainsMatches(OutputRegexHelper.java:41)
	at Output.match(Output.java:84)
	at Test$StreamMatcher.run(Test.java:516)
Time spent executing: 322 milliseconds
Test result: FAILED
```

**Comment by JasonFengJ9** [comment]
[[aix_ppc] SE80_GIT cmdLineTest_stackSizeInfoTest_0](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=101600213)
```
java version "1.8.0_431"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pap3280sr9-20241209_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc-32-Bit 20250211_87790 (JIT enabled, AOT enabled)
OpenJ9   - 121939c3f39
OMR      - f11ae7253
IBM      - 8a61f98)

===============================================
Running test cmdLineTest_stackSizeInfoTest_0 ...
===============================================
cmdLineTest_stackSizeInfoTest_0 Start Time: Tue Feb 11 23:57:57 2025 Epoch Time (ms): 1739336277849
"/bluebird/builds/bld_87790/sdk/ap3280/bin/java" -Xshareclasses:destroyAll; "/bluebird/builds/bld_87790/sdk/ap3280/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
JVMSHRC005I No shared class caches available
JVMSHRC005I No shared class caches available
cache cleanup done
variation: NoOptions
JVM_OPTIONS:  

Testing: Running threads stack size info test
Test start time: 2025/02/11 23:57:59 Eastern Standard Time
Running command: "/bluebird/builds/bld_87790/sdk/ap3280/bin/java"   -verbose:stack -cp "/bluebird/builds/bld_87790/jvmtest/test/SE80/functional/cmdline_options_testresources/cmdlinetestresources.jar" j9vm.test.printstacktest.RunningThreadsStackSizeTest
Time spent starting: 23 milliseconds
Exception in thread "Thread-4" java.lang.StackOverflowError
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
        at java.util.regex.Pattern$Loop.match(Pattern.java:4810)
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4742)
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4593)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3802)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4629)

        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
        at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4829)
        at java.util.regex.Pattern$Prolog.match(Pattern.java:4766)
        at java.util.regex.Pattern$Slice.match(Pattern.java:3997)
        at java.util.regex.Pattern$GroupTail.match(Pattern.java:4742)
        at java.util.regex.Pattern$BranchConn.match(Pattern.java:4593)
        at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3823)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4629)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4683)
        at java.util.regex.Pattern$Slice.match(Pattern.java:3997)
        at java.util.regex.Pattern$GroupCurly.match0(Pattern.java:4488)
        at java.util.regex.Pattern$GroupCurly.match(Pattern.java:4430)
        at java.util.regex.Pattern$BnM.match(Pattern.java:5494)
        at java.util.regex.Matcher.search(Matcher.java:1259)
        at java.util.regex.Matcher.find(Matcher.java:648)
        at OutputRegexHelper.ContainsMatches(OutputRegexHelper.java:41)
        at Output.match(Output.java:84)
        at Test$StreamMatcher.run(Test.java:516)
Time spent executing: 909 milliseconds
Test result: FAILED
Output from test:
 [ERR] JVMVERB000I Verbose stack: "Attach API initializer" used 1224/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "Attach API wait loop" used 212/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "Attach API teardown" used 432/0 bytes on Java/C stacks
 [ERR] JVMVERB027I Verbose stack: Running thread "RunningThread1" is using 160/0 bytes on Java/C stacks
 [ERR] JVMVERB027I Verbose stack: Running thread "RunningThread2" is using 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "main" used 1560/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-001" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-002" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-003" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-004" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-005" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-006" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Compilation Thread-000" used 224/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT Diagnostic Compilation Thread-007" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "IProfiler" used 160/0 bytes on Java/C stacks
 [ERR] JVMVERB000I Verbose stack: "JIT-SamplerThread" used 160/0 bytes on Java/C stacks
>> Success condition was not found: [Output match: Verbose stack: Unable to print the stack info for currently running threads]
>> Success condition was not found: [Output match: \[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "RunningThread(1|2)" is using(\n|.)*(\s)+\[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "RunningThread(1|2)" is using]
>> Failure condition was not found: [Output match: Verbose stack: Unable to print the stack info for currently running threads(\n|.)*\[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "(.)*" is using]
>> Failure condition was not found: [Output match: \[ERR\](\s)*JVMVERB027I Verbose stack: Running thread "(.)*" is using(.|\n)*Verbose stack: Unable to print the stack info for currently running threads]
>> Failure condition was not found: [Output match: The thread should not have been interrupted!]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]


---TEST RESULTS---
Number of PASSED tests: 1 out of 2
Number of FAILED tests: 1 out of 2

---SUMMARY OF FAILED TESTS---
Running threads stack size info test
```

[100x grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=87825) - 8/100 failed
