### ISSUE TITLE
OpenJDK java/lang/Character/CharPropTest

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18669]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/116/
jdk_lang_1
java/lang/Character/CharPropTest.java

```
01:45:09  java.lang.ArrayIndexOutOfBoundsException
01:45:09  	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
01:45:09  	at java.base/java.lang.CharacterDataLatin1.isWhitespace(CharacterDataLatin1.java:239)
01:45:09  	at java.base/java.lang.Character.isWhitespace(Character.java:10220)
01:45:09  	at CharPropTest.isWhitespaceTest(CharPropTest.java:144)
01:45:09  	at CharPropTest.testCodePoint(CharPropTest.java:98)
01:45:09  	at CharPropTest.handleOneLine(CharPropTest.java:87)
01:45:09  	at CharPropTest.lambda$main$1(CharPropTest.java:55)
```

**Comment by hzongaro** [comment]
This is almost certainly a duplicate of issue #18102, et al.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_OpenJDK11_testList_0/20
jdk_lang_0 
    java/lang/Character/TestUndefinedIdentifierStartPart.java
```
13:25:16  java.lang.ArrayIndexOutOfBoundsException
13:25:16  	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
13:25:16  	at java.base/java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:122)
13:25:16  	at java.base/java.lang.Character.getType(Character.java:10355)
13:25:16  	at java.base/java.lang.Character.isDefined(Character.java:9126)
13:25:16  	at java.base/java.lang.Character.isDefined(Character.java:9102)
13:25:16  	at TestUndefinedIdentifierStartPart.main(TestUndefinedIdentifierStartPart.java:36)
```
    java/lang/Character/TestUndefinedMirrored.java
```
13:25:17  java.lang.ArrayIndexOutOfBoundsException
13:25:17  	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
13:25:17  	at java.base/java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:122)
13:25:17  	at java.base/java.lang.Character.getType(Character.java:10355)
13:25:17  	at java.base/java.lang.Character.isDefined(Character.java:9126)
13:25:17  	at java.base/java.lang.Character.isDefined(Character.java:9102)
13:25:17  	at TestUndefinedMirrored.main(TestUndefinedMirrored.java:36)
```
    java/lang/Character/TestUndefinedNumeric.java
```
13:25:20  java.lang.ArrayIndexOutOfBoundsException
13:25:20  	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
13:25:20  	at java.base/java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:122)
13:25:20  	at java.base/java.lang.Character.getType(Character.java:10355)
13:25:20  	at java.base/java.lang.Character.isDefined(Character.java:9126)
13:25:20  	at java.base/java.lang.Character.isDefined(Character.java:9102)
13:25:20  	at TestUndefinedNumeric.main(TestUndefinedNumeric.java:36)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8_testList_2/60
jdk_lang_j9_1
java/lang/Character/CheckProp.java
```
14:20:45  java.lang.ArrayIndexOutOfBoundsException
14:20:45  	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
14:20:45  	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
14:20:45  	at java.lang.Character.getType(Character.java:6978)
14:20:45  	at java.lang.Character.isUpperCase(Character.java:5554)
14:20:45  	at CheckProp.main(CheckProp.java:90)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8_testList_0/60
jdk_lang_0
