### ISSUE TITLE
Failure in cent7-ppcle-3 with error hudson.model.Computer$TerminationRequest

### ISSUE THREAD

**Issue by SajinaKandy** [eclipse-openj9/openj9#18677]
Jenkins tests fail on ppc64le_linux with the below error:

```
00:06:50  Running on [cent7-ppcle-3](https://openj9-jenkins.osuosl.org/computer/cent7%2Dppcle%2D3/) in /home/jenkins/workspace/Build_JDK17_ppc64le_linux_jit_Personal
[Pipeline] {
[Pipeline] timeout
00:06:50  Timeout set to expire in 5 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[Pipeline] sh
[Pipeline] // timestamps
[Pipeline] End of Pipeline
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Sun Dec 17 18:50:23 EST 2023 by Thread[Running CpsFlowExecution[Owner[Sanitize-Nodes_plinux/606:Sanitize-Nodes_plinux #606]],5,main] [id=7284]
		at hudson.model.Computer.recordTermination(Computer.java:239)
		at hudson.model.Computer.disconnect(Computer.java:509)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:812)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Link:https://openj9-jenkins.osuosl.org/job/Build_JDK17_ppc64le_linux_jit_Personal/128/console

**Comment by pshipton** [comment]
The build is from Dec 21. There was an issue with the UNB connection that may have caused this, and has since been resolved. Pls try again.
