### ISSUE TITLE
jdk22 MathLoadTest_bigdecimal OutOfMemoryError: too large to fit in a String

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18695]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.system_aarch64_mac_Personal_testList_0/1/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.system_aarch64_mac_Personal_testList_1/1/
MathLoadTest_bigdecimal_5m_1
```
MLT testFailure: testItem_0460(net.adoptopenjdk.test.bigdecimal.TestSuite019): too large to fit in a String
MLT java.lang.OutOfMemoryError: too large to fit in a String
MLT 	at java.base/java.math.BigDecimal.getValueString(BigDecimal.java:3542)
MLT 	at java.base/java.math.BigDecimal.toPlainString(BigDecimal.java:3524)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite019.testItem_0460(TestSuite019.java:3188)
```
MathLoadTest_bigdecimal_CS_5m_0
```
MLT testFailure: testItem_0587(net.adoptopenjdk.test.bigdecimal.TestSuite029): too large to fit in a String
MLT java.lang.OutOfMemoryError: too large to fit in a String
MLT 	at java.base/java.math.BigDecimal.getValueString(BigDecimal.java:3542)
MLT 	at java.base/java.math.BigDecimal.toPlainString(BigDecimal.java:3524)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite029.testItem_0587(TestSuite029.java:4145)

```

**Comment by pshipton** [comment]
More in
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.system_aarch64_mac_Personal_testList_1/1/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.system_aarch64_mac_Personal_testList_2/1/
MathLoadTest_all_5m_1
MiniMix_5m_1
MiniMix_aot_5m_0
MathLoadTest_all_CS_5m_0

**Comment by pshipton** [comment]
Occurs with Hotspot as well, opened https://github.com/adoptium/aqa-systemtest/issues/486

**Comment by pshipton** [comment]
Opened https://github.com/adoptium/aqa-systemtest/pull/487
