### ISSUE TITLE
jdk22 OpenJDK StackWalker/GetCallerClassTest - Got class java.lang.invoke.LambdaForm$MH/0x000000003983da20, but expected class GetCallerClassTest$TopLevelCaller

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18697]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_aarch64_mac_Personal_testList_0/1
jdk_lang
java/lang/StackWalker/GetCallerClassTest.java
```
16:04:08  Unexpected exception:
16:04:08  java.lang.RuntimeException: java.lang.RuntimeException: Got class java.lang.invoke.LambdaForm$MH/0x000000003983da20, but expected class GetCallerClassTest$TopLevelCaller
16:04:08  	at GetCallerClassTest.reflectiveGetCallerClass(GetCallerClassTest.java:135)
16:04:08  	at GetCallerClassTest$TopLevelCaller.run(GetCallerClassTest.java:180)
16:04:08  	at GetCallerClassTest.test(GetCallerClassTest.java:77)
16:04:08  	at GetCallerClassTest.main(GetCallerClassTest.java:71)
16:04:08  	at java.lang.invoke.LambdaForm$DMH/0x000000003983e620.invokeStatic(LambdaForm$DMH)
16:04:08  	at java.lang.invoke.LambdaForm$MH/0x0000000039844220.invoke(LambdaForm$MH)
16:04:08  	at java.lang.invoke.LambdaForm$MH/0x000000003983ac20.invokeExact_MT(LambdaForm$MH)
16:04:08  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
16:04:08  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
16:04:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
16:04:08  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
16:04:08  	at java.base/java.lang.Thread.runWith(Thread.java:1595)
16:04:08  	at java.base/java.lang.Thread.run(Thread.java:1582)
16:04:08  Caused by: java.lang.RuntimeException: Got class java.lang.invoke.LambdaForm$MH/0x000000003983da20, but expected class GetCallerClassTest$TopLevelCaller
16:04:08  	at GetCallerClassTest.assertEquals(GetCallerClassTest.java:162)
16:04:08  	at GetCallerClassTest.reflectiveGetCallerClass(GetCallerClassTest.java:126)
16:04:08  	... 12 more
```

Perhaps related to https://github.com/eclipse-openj9/openj9/issues/18696

**Comment by tajila** [comment]
@fengxue-IS Please take a look at this

**Comment by tajila** [comment]
@fengxue-IS It may be a dup of https://github.com/eclipse-openj9/openj9/issues/18696

**Comment by fengxue-IS** [comment]
in JDK22, this test added the new option `-XX:+ShowHiddenFrames`, this broke the assumption that generated lambda frames would not exist when using `getCallerClass` API. working on a patch to fix this behaviour.

**Comment by fengxue-IS** [comment]
local testing passed for the draft change, running personal build now

#18696 seem to be a different problem specifically related to the newly added `DROP_METHOD_INFO` flag

**Comment by babsingh** [comment]
Reopening ... the excluded test needs to be re-enabled, and the `test excluded` label should be removed.

**Comment by pshipton** [comment]
Created https://github.com/adoptium/aqa-tests/pull/5061 to unexclude the test.
