### ISSUE TITLE
jdk22 OpenJDK MethodHandleProxies/WrapperHiddenClassTest - NoClassDefFoundError: java/util/jdk/MHProxy1/Comparator/0x0000000000000000 (wrong name: jdk/MHProxy1/Comparator)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18701]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_aarch64_mac_Personal_testList_0/1
jdk_lang
java/lang/invoke/MethodHandleProxies/WrapperHiddenClassTest.java
```
16:02:33  STARTED    WrapperHiddenClassTest::testWrapperInstance 'testWrapperInstance()'
16:02:33  java.lang.NoClassDefFoundError: java/util/jdk/MHProxy1/Comparator/0x0000000000000000 (wrong name: jdk/MHProxy1/Comparator)
16:02:33  	at java.base/java.lang.ClassLoader.defineClassImpl1(Native Method)
16:02:33  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:510)
16:02:33  	at java.base/java.lang.Access.defineClass(Access.java:335)
16:02:33  	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2498)
16:02:33  	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClassAsLookup(MethodHandles.java:2477)
16:02:33  	at java.base/java.lang.invoke.MethodHandleProxies.newProxyClass(MethodHandleProxies.java:295)
16:02:33  	at java.base/java.lang.invoke.MethodHandleProxies$1.computeValue(MethodHandleProxies.java:224)
16:02:33  	at java.base/java.lang.invoke.MethodHandleProxies$1.computeValue(MethodHandleProxies.java:221)
16:02:33  	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:235)
16:02:33  	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:217)
16:02:33  	at java.base/java.lang.ClassValue.get(ClassValue.java:123)
16:02:33  	at java.base/java.lang.invoke.MethodHandleProxies.getProxyClass(MethodHandleProxies.java:320)
16:02:33  	at java.base/java.lang.invoke.MethodHandleProxies.asInterfaceInstance(MethodHandleProxies.java:200)
16:02:33  	at WrapperHiddenClassTest.testWrapperInstance(WrapperHiddenClassTest.java:66)
```

**Comment by babsingh** [comment]
Closing ... the above `NoClassDefFoundError` is fixed by https://github.com/eclipse-openj9/openj9/pull/18714.
