### ISSUE TITLE
Mauve ClassNotFoundException: gnu.testlet.java.beans.beancontext.BeanContextServicesSupport.getChildBeanContextServicesListener

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18723]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.system_x86-64_windows_Nightly_testList_1/136
MauveSingleThrdLoad_J9_5m_0
MauveSingleInvocLoad_J9_5m_0
```
22:34:12  LT  java.lang.ClassNotFoundException: gnu.testlet.java.beans.beancontext.BeanContextServicesSupport.getChildBeanContextServicesListener
22:34:12  LT  	at java.base/java.lang.Class.forNameImpl(Native Method)
22:34:12  LT  	at java.base/java.lang.Class.forName(Class.java:374)
22:34:12  LT  	at java.base/java.lang.Class.forName(Class.java:350)
22:34:12  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
22:34:12  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
22:34:12  LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
22:34:12  LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
22:34:12  LT  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment]
Found this old issue which seems related 
https://github.com/eclipse-openj9/openj9/issues/16513

**Comment by pshipton** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.system_x86-64_windows_ojdk292_Personal_testList_0/1) - win11x86-rtp-rt6-1
MiniMix_5m_0
```
LT  Test failed:
LT  java.lang.ClassNotFoundException: gnu.testlet.java.lang.RuntimeException.classInfo.isPrimitive
LT  	at java.lang.Class.forNameImpl(Native Method)
LT  	at java.lang.Class.forName(Class.java:347)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:826)
```
