### ISSUE TITLE
OpenJDK java/util/concurrent/ExecutorService/CloseTest testInterruptDuringClose - CancellationException was thrown

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18772]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Release_testList_1/10/
jdk_util_0
java/util/concurrent/ExecutorService/CloseTest.java
```
18:59:48  test CloseTest.testInterruptDuringClose(java.util.concurrent.ForkJoinPool@ab470dcb): failure
18:59:48  java.lang.AssertionError: Expected ExecutionException to be thrown, but CancellationException was thrown
18:59:48  	at org.testng.Assert.expectThrows(Assert.java:1724)
18:59:48  	at CloseTest.testInterruptDuringClose(CloseTest.java:178)

18:59:48  Caused by: java.util.concurrent.CancellationException
18:59:48  	at java.base/java.util.concurrent.ForkJoinTask.uncheckedThrow(ForkJoinTask.java:602)
18:59:48  	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:582)
18:59:48  	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:993)
18:59:48  	at org.testng.Assert.expectThrows(Assert.java:1714)
18:59:48  	... 29 more

```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/3181/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/215 - [rh7-390-4](https://openj9-jenkins.osuosl.org/computer/rh7-390-4)
jdk_util_0
java/util/concurrent/ExecutorService/CloseTest.java
```
11:53:14  test CloseTest.testInterruptDuringClose(java.util.concurrent.ForkJoinPool@99877a5a): failure
11:53:14  java.lang.AssertionError: Expected ExecutionException to be thrown, but CancellationException was thrown
11:53:14  	at org.testng.Assert.expectThrows(Assert.java:1724)
11:53:14  	at CloseTest.testInterruptDuringClose(CloseTest.java:178)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/637

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/673
jdk_concurrent_1
java/util/concurrent/forkjoin/AsyncShutdownNow.java
```
00:19:15  test AsyncShutdownNow.testTimedFutureGet(java.util.concurrent.ForkJoinPool@5ecc373a): failure
00:19:15  java.util.concurrent.CancellationException
00:19:15  	at java.base/java.util.concurrent.ForkJoinTask.uncheckedThrow(ForkJoinTask.java:626)
00:19:15  	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:606)
00:19:15  	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004)
00:19:15  	at AsyncShutdownNow.testTimedFutureGet(AsyncShutdownNow.java:125)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/723/
jdk_concurrent_1 
java/util/concurrent/ExecutorService/CloseTest.java
```
21:07:42  java.lang.AssertionError: Expected ExecutionException to be thrown, but CancellationException was thrown
21:07:42  	at org.testng.Assert.expectThrows(Assert.java:1724)
21:07:42  	at CloseTest.testInterruptDuringClose(CloseTest.java:178)
...
21:07:42  Caused by: java.util.concurrent.CancellationException
21:07:42  	at java.base/java.util.concurrent.ForkJoinTask.uncheckedThrow(ForkJoinTask.java:602)
21:07:42  	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:582)
21:07:42  	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:993)
21:07:42  	at org.testng.Assert.expectThrows(Assert.java:1714)
21:07:42  	... 29 more
```
