### ISSUE TITLE
OpenJDK java/util/concurrent/ArrayBlockingQueue/WhiteBox - failed to do a "full" gc

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18775]
Failed in OMR acceptance build

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_OMR_testList_2/59
jdk_util_0 
java/util/concurrent/ArrayBlockingQueue/WhiteBox.java
```
11:36:58  test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
11:36:58  java.lang.AssertionError: failed to do a "full" gc
11:36:58  	at WhiteBox.forceFullGc(WhiteBox.java:226)
11:36:58  	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
```

**Comment by pshipton** [comment]
May be caused by https://github.com/eclipse/omr/pull/7216 which is reverted https://github.com/eclipse/omr/pull/7233
