### ISSUE TITLE
OpenJDK java/lang/String/concat/ImplicitStringConcatMany - StackOverflowError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18774]
Failed in OMR acceptance build

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_0/58
jdk_lang_j9_0
java/lang/String/concat/ImplicitStringConcatMany.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_0/58/openjdk_test_output.tar.gz
```
14:50:31  The system is out of resources.
14:50:31  Consult the following stack trace for details.
14:50:31  java.lang.StackOverflowError
14:50:31  	at jdk.compiler/com.sun.tools.javac.util.Name.subName(Name.java:192)
14:50:31  	at jdk.compiler/com.sun.tools.javac.util.Convert.packagePart(Convert.java:374)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Symtab.enterClass(Symtab.java:796)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.enterClass(ClassReader.java:2556)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.classSigToType(ClassReader.java:574)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:506)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToTypes(ClassReader.java:689)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.classSigToType(ClassReader.java:591)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:506)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToTypes(ClassReader.java:689)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.classSigToType(ClassReader.java:591)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:506)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:532)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:456)
14:50:31  	at jdk.compiler/com.sun.tools.javac.util.Name.map(Name.java:250)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.PoolReader.getType(PoolReader.java:192)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader$11.read(ClassReader.java:1021)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readAttrs(ClassReader.java:1433)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readMemberAttrs(ClassReader.java:1423)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:2330)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:2641)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClassBuffer(ClassReader.java:2732)
14:50:31  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2756)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:373)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:302)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:682)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1418)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:1334)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2183)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2159)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1050)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4894)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types.asSuper(Types.java:2156)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2179)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2159)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1050)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4894)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types.asSuper(Types.java:2156)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types.unboxedType(Types.java:4321)
14:50:31  	at jdk.compiler/com.sun.tools.javac.code.Types.unboxedTypeOrType(Types.java:4331)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Operators.unaryPromotion(Operators.java:110)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryNumericOperator.test(Operators.java:497)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryNumericOperator.test(Operators.java:476)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Operators.lambda$resolveBinary$3(Operators.java:164)
14:50:31  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
14:50:31  	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950)
14:50:31  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
14:50:31  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:540)
14:50:31  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:526)
14:50:31  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
14:50:31  	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
14:50:31  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
14:50:31  	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolve(Operators.java:179)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolveBinary(Operators.java:162)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4063)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
14:50:31  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
14:50:31  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
... etc.
```

**Comment by pshipton** [comment]
May be caused by https://github.com/eclipse/omr/pull/7216 which is reverted https://github.com/eclipse/omr/pull/7233

**Comment by pshipton** [comment]
Another one
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_0/63

**Comment by pshipton** [comment]
Not reproduced on the same machine when running the single test (once), or jdk_lang_j9_0 (once).

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/139/ - [p8-java1-ibm11](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm11)
jdk_lang_j9_0
java/lang/String/concat/ImplicitStringConcatManyLongs.java
```
21:04:46  The system is out of resources.
21:04:46  Consult the following stack trace for details.
21:04:46  java.lang.StackOverflowError
21:04:46  	at jdk.compiler/com.sun.tools.javac.util.Name.subName(Name.java:192)
21:04:46  	at jdk.compiler/com.sun.tools.javac.util.Convert.packagePart(Convert.java:374)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Symtab.enterClass(Symtab.java:796)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.enterClass(ClassReader.java:2556)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.classSigToType(ClassReader.java:574)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:506)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToTypes(ClassReader.java:689)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.classSigToType(ClassReader.java:591)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:506)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader$11.read(ClassReader.java:1014)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readAttrs(ClassReader.java:1433)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClassAttrs(ClassReader.java:1447)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:2614)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClassBuffer(ClassReader.java:2732)
21:04:46  	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2756)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:373)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:302)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:682)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1418)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:1334)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2183)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2159)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1050)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4894)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types.asSuper(Types.java:2156)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2179)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types$12.visitClassType(Types.java:2159)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1050)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4894)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types.asSuper(Types.java:2156)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types.unboxedType(Types.java:4321)
21:04:46  	at jdk.compiler/com.sun.tools.javac.code.Types.unboxedTypeOrType(Types.java:4331)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Operators.unaryPromotion(Operators.java:110)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryNumericOperator.test(Operators.java:497)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Operators$BinaryNumericOperator.test(Operators.java:476)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Operators.lambda$resolveBinary$3(Operators.java:164)
21:04:46  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
21:04:46  	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950)
21:04:46  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
21:04:46  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:540)
21:04:46  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:526)
21:04:46  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
21:04:46  	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
21:04:46  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
21:04:46  	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolve(Operators.java:179)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Operators.resolveBinary(Operators.java:162)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4063)
21:04:46  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
21:04:46  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2175)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:662)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:715)
21:04:46  	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBinary(Attr.java:4032)
etc.
```

**Comment by pshipton** [comment]
@mpirvu another possible GRA issue. Presumably we won't see it again now that I've promoted https://github.com/eclipse/omr/pull/7248
