### ISSUE TITLE
Reflection problem with umlaut character, seemingly related to String compression

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#18791]
Consider the following test program:

```
public class Test {
	public static void main(String[] args) throws Exception {
		String umlautA = "ä";
		String methodName = "get" + umlautA;
		Test.class.getDeclaredMethod(methodName);
	}

	public static String getä() {
		return "ä";
	}
}
```

If this is compiled with any IBM Java 8 or Semeru 8 release, and then executed on Semeru 11.0.21.0, it will fail with a NoSuchMethodException when trying to find the getä() method:

```
Exception in thread "main" java.lang.NoSuchMethodException: Test.getä()
        at java.base/java.lang.Class.newNoSuchMethodException(Class.java:649)
        at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1447)
        at java.base/java.lang.Class.getMethodHelper(Class.java:1533)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:1121)
        at Test.main(Test.java:5)
```

Some observations from my own experiments:

- If the program is run on Semeru 11.0.20.0 the failure does not occur

- If the program is run on the latest IBM Java 8 and Semeru 8 releases the failure does not occur

- If the program is compiled with any Semeru 11 release the failure does not occur

- String compression [was enabled by default](https://github.com/eclipse-openj9/openj9/pull/17703) in Semeru 11.0.21.0, and if the program is run on 11.0.21.0 with the option `-XX:+CompactStrings` to disable String compression the failure does not occur

- The way that the `methodName` String is constructed is significant - if the test program is changed to use any of the following alternatives the failure **does not** occur:
    - `String methodName = "getä";`
    - `String methodName = "get" + "ä";`
    - `String methodName = "" + "getä";`

- The bytecode for the String concatenation that's created with Java/Semeru 8's `javac` is quite different to Semeru 11's, which is probably significant:

**Java/Semeru 8:**
```
  public static void main(java.lang.String[]) throws java.lang.Exception;
    Code:
       0: ldc           #2                  // String ä
       2: astore_1
       3: new           #3                  // class java/lang/StringBuilder
       6: dup
       7: invokespecial #4                  // Method java/lang/StringBuilder."<init>":()V
      10: ldc           #5                  // String get
      12: invokevirtual #6                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      15: aload_1
      16: invokevirtual #6                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      19: invokevirtual #7                  // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
      22: astore_2
      23: ldc           #8                  // class Test
      25: aload_2
      26: iconst_0
      27: anewarray     #9                  // class java/lang/Class
      30: invokevirtual #10                 // Method java/lang/Class.getDeclaredMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
      33: pop
      34: return
```

**Semeru 11:**

```
  public static void main(java.lang.String[]) throws java.lang.Exception;
    Code:
       0: ldc           #2                  // String ä
       2: astore_1
       3: aload_1
       4: invokedynamic #3,  0              // InvokeDynamic #0:makeConcatWithConstants:(Ljava/lang/String;)Ljava/lang/String;
       9: astore_2
      10: ldc           #4                  // class Test
      12: aload_2
      13: iconst_0
      14: anewarray     #5                  // class java/lang/Class
      17: invokevirtual #6                  // Method java/lang/Class.getDeclaredMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
      20: pop
      21: return
```

**Comment by r30shah** [comment]
FYI @dchopra001

**Comment by keithc-ca** [comment]
This has nothing to do with reflection; the following says "FAIL" (in Eclipse OpenJ9 VM 17.0.9.0 (build openj9-0.41.0)).
```java
	public static void main(String[] args) {
		String umlautA = "ä";
		String methodName = "get" + umlautA;

		if (umlautA.equals((methodName + umlautA).substring(3))) {
			System.out.println("PASS");
		} else {
			System.out.println("FAIL");
		}
	}
```

**Comment by dchopra001** [comment]
@paulcheeseman Just to confirm, are you running the application as follows:
```
java Test
```

**Comment by dchopra001** [comment]
Just tried, and it does fail with the above command. It fails with the JIT disabled as well:
```
jdk/bin/java -Xint Test2
Exception in thread "main" java.lang.NoSuchMethodException: Test.getä()
	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:660)
	at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1458)
	at java.base/java.lang.Class.getMethodHelper(Class.java:1555)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:1132)
	at Test2.main(Test2.java:5)
```

**Comment by r30shah** [comment]
FYI @TobiAjila

**Comment by keithc-ca** [comment]
There are several places that misuse `J9JAVAARRAYOFBYTE_LOAD()` with neither a cast nor a mask to select the bottom 8 bits.
I think the one that is manifested here is [stringhelpers.cpp:180](https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/stringhelpers.cpp#L180)
```c
			U_16 unicodeChar = (U_16)J9JAVAARRAYOFBYTE_LOAD(vmThread, unicodeBytes, i);
```
should be
```c
			U_16 unicodeChar = (U_8)J9JAVAARRAYOFBYTE_LOAD(vmThread, unicodeBytes, i);
```

**Comment by hangshao0** [comment]
Having talked to @keithc-ca and he will take this issue.
