### ISSUE TITLE
jdk22 serviceability jvmti GetStackTraceAndRetransformTest: UnsatisfiedLinkError WhiteBox

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#18809]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/1
serviceability_jvmti_j9_0
serviceability_jvmti_j9_1
serviceability/jvmti/thread/GetStackTrace/GetStackTraceAndRetransformTest/GetStackTraceAndRetransformTest.java
```
16:30:07  STDERR:
16:30:07  java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V
16:30:07  	at jdk.test.whitebox.WhiteBox.<clinit>(WhiteBox.java:67)
16:30:07  	at GetStackTraceAndRetransformTest.main(GetStackTraceAndRetransformTest.java:76)
16:30:07  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
16:30:07  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
16:30:07  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
16:30:07  	at java.base/java.lang.Thread.run(Thread.java:1582)
16:30:07  
16:30:07  JavaTest Message: Test threw exception: java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V
16:30:07  JavaTest Message: shutting down test
16:30:07  
16:30:07  STATUS:Failed.`main' threw exception: java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V
```

**Comment by babsingh** [comment]
This test should be permanently excluded since OpenJ9 does not support the WhiteBox API.

**Comment by babsingh** [comment]
Closing. Existing excludes are sufficient. https://github.com/adoptium/aqa-tests/pull/5037 is no longer needed since test automation will scan the issues for the **"perm excluded"** label to prevent re-enabling permanently disabled tests.
