### ISSUE TITLE
jdk22 serviceability jvmti FilteredFieldsTest: declaredCount != jvmtiCount: 0 != 1

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#18807]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/1
serviceability_jvmti_j9_0
serviceability_jvmti_j9_1
serviceability/jvmti/GetClassFields/FilteredFields/FilteredFieldsTest.java
```
16:28:25  STDOUT:
16:28:25  Class.getDeclaredFields reported 0 fields:
16:28:25  GetClassFields returned 1 fields:
16:28:25    [0]: constantPoolOop
16:28:25  STDERR:
16:28:25  java.lang.Exception: declaredCount != jvmtiCount: 0 != 1
16:28:25  	at FilteredFieldsTest.main(FilteredFieldsTest.java:57)
16:28:25  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
16:28:25  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
16:28:25  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
16:28:25  	at java.base/java.lang.Thread.run(Thread.java:1582)
16:28:25  
16:28:25  JavaTest Message: Test threw exception: java.lang.Exception: declaredCount != jvmtiCount: 0 != 1
16:28:25  JavaTest Message: shutting down test
16:28:25  
16:28:25  STATUS:Failed.`main' threw exception: java.lang.Exception: declaredCount != jvmtiCount: 0 != 1
```

**Comment by babsingh** [comment]
### Test Source Code
https://github.com/ibmruntimes/openj9-openjdk-jdk22/blob/openj9/test/hotspot/jtreg/serviceability/jvmti/GetClassFields/FilteredFields/FilteredFieldsTest.java

### Test Description
The test verifies that JVMTI `GetClassFields` [1] function filters out fields the same way as `Class.getDeclaredFields()` [2] does.

The field to be filtered is [jdk.internal.reflect.ConstantPool.constantPoolOop](https://github.com/ibmruntimes/openj9-openjdk-jdk22/blob/2a64d9c6fcbc5c102d406ceddd6953f71e9db40c/src/java.base/share/classes/jdk/internal/reflect/ConstantPool.java#L119-L120):
```
  // HotSpot-internal constant pool object (set by the VM, name known to the VM)
  private Object constantPoolOop;
```

As per the JVMTI specification [2], there is no expectation for JVMTI `GetClassFields` to behave similar to `Class.getDeclaredFields`. The JVMTI specification for JVMTI `GetClassFields` only expects **directly declared fields** to be returned. [constantPoolOop](https://github.com/ibmruntimes/openj9-openjdk-jdk22/blob/2a64d9c6fcbc5c102d406ceddd6953f71e9db40c/src/java.base/share/classes/jdk/internal/reflect/ConstantPool.java#L119-L120) is a **directly declared field**, and it is being correctly returned by OpenJ9's implementation of JVMTI `GetClassFields`. 

@tajila Moving this test to the 0.44 release. We can either match the RI or keep the test excluded. I don't see an immediate need to match the RI. My recommendation is to keep the test excluded.

### Java doc and JVMTI specification
[1] JVMTI `GetClassFields`: https://download.java.net/java/early_access/jdk22/docs/specs/jvmti.html#GetClassFields
[2] `Class.getDeclaredFields`: https://download.java.net/java/early_access/jdk22/docs/api/java.base/java/lang/Class.html#getDeclaredFields()

**Comment by babsingh** [comment]
This issue doesn't block the current release. Moving it to the 0.48 release.

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/18807#issuecomment-2133916582: The test has been permanently disabled since it is specific to the RI and not required by the spec.
