### ISSUE TITLE
FIPS CryptoTests_0_FAILED ProviderException: Error in Native ChaCha20Cipher

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18801]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_x86-64_linux_fips140_2_testList_2/24/)(`rhel8x86-rtp-rtfips1-1`):
```
java version "11.0.22" 2024-01-16
IBM Semeru Runtime Certified Edition 11.0.22.0-rc2 (build 11.0.22+7)
Eclipse OpenJ9 VM 11.0.22.0-rc2 (build v0.43.0-release-c08290534, JRE 11 Linux amd64-64-Bit Compressed References 20240123_822 (JIT enabled, AOT enabled)
OpenJ9   - c08290534
OMR      - ea8124dbc
JCL      - 5aff4c614c based on jdk-11.0.22+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=CryptoTests_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=FIPS140_2&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_x86-64_linux_fips140_2&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F822%2Fibm-semeru-certified-jdk_x64_linux_11.0.22.0-rc2.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F822%2Fibm-semeru-certified-testimage_x64_linux_11.0.22.0-rc2.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.0-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.43.0-release&amp;OPENJ9_BRANCH=v0.43.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=v1.0.0-release&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.43.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=25&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-01-23T06:53:13.284Z] variation: NoOptions
[2024-01-23T06:53:13.284Z] JVM_OPTIONS:   -Dsemeru.fips=true

[2024-01-23T06:56:11.586Z] TEST: cryptotest/tests/CipherTests.java

[2024-01-23T06:56:11.588Z] Total checks: 104, failed: 4
[2024-01-23T06:56:11.588Z] 4 Cipher failed
[2024-01-23T06:56:11.588Z] ** failed runs: 4 **
[2024-01-23T06:56:11.588Z] java.lang.Exception: 19)	SunJCE: 	ChaCha20-Poly1305~ChaCha20-Poly1305	 (Cipher)
[2024-01-23T06:56:11.588Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:85)
[2024-01-23T06:56:11.588Z] 	at cryptotest.tests.CipherTests.main(CipherTests.java:69)
[2024-01-23T06:56:11.588Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-23T06:56:11.588Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-23T06:56:11.588Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-23T06:56:11.588Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-01-23T06:56:11.588Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-01-23T06:56:11.588Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-01-23T06:56:11.588Z] Caused by: cryptotest.utils.AlgorithmRunException: java.security.ProviderException: Error in Native ChaCha20Cipher
[2024-01-23T06:56:11.588Z] 	at cryptotest.tests.CipherTests.checkAlgorithm(CipherTests.java:140)
[2024-01-23T06:56:11.588Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
[2024-01-23T06:56:11.588Z] 	... 7 more
[2024-01-23T06:56:11.588Z] Caused by: java.security.ProviderException: Error in Native ChaCha20Cipher
[2024-01-23T06:56:11.588Z] 	at java.base/com.sun.crypto.provider.NativeChaCha20Cipher.init(NativeChaCha20Cipher.java:616)
[2024-01-23T06:56:11.588Z] 	at java.base/com.sun.crypto.provider.NativeChaCha20Cipher.engineInit(NativeChaCha20Cipher.java:361)
[2024-01-23T06:56:11.588Z] 	at java.base/javax.crypto.Cipher.init(Cipher.java:1431)
[2024-01-23T06:56:11.588Z] 	at java.base/javax.crypto.Cipher.init(Cipher.java:1364)
[2024-01-23T06:56:11.588Z] 	at cryptotest.tests.CipherTests.checkAlgorithm(CipherTests.java:125)
[2024-01-23T06:56:11.588Z] 	... 8 more

[2024-01-23T06:56:11.588Z] FAILED: cryptotest.tests.CipherTests
[2024-01-23T06:56:11.588Z] STDERR:
[2024-01-23T06:56:11.588Z] An OpenSSL error occurred
[2024-01-23T06:56:11.588Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T06:56:11.588Z] An OpenSSL error occurred
[2024-01-23T06:56:11.588Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T06:56:11.588Z] An OpenSSL error occurred
[2024-01-23T06:56:11.588Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T06:56:11.588Z] An OpenSSL error occurred
[2024-01-23T06:56:11.588Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T06:56:11.588Z] java.lang.RuntimeException: cryptotest.tests.CipherTests failed with explanantion of 5799 chars long
[2024-01-23T06:56:11.588Z] 	at cryptotest.utils.TestResult.assertItself(TestResult.java:31)
[2024-01-23T06:56:11.588Z] 	at cryptotest.tests.CipherTests.main(CipherTests.java:72)
[2024-01-23T06:56:11.588Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-23T06:56:11.588Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-23T06:56:11.588Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-23T06:56:11.588Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-01-23T06:56:11.588Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-01-23T06:56:11.588Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-01-23T06:56:11.588Z] 
[2024-01-23T06:56:11.588Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: cryptotest.tests.CipherTests failed with explanantion of 5799 chars long

[2024-01-23T07:02:25.400Z] TEST: cryptotest/CryptoTest.java

[2024-01-23T07:02:25.423Z] 4 Cipher failed
[2024-01-23T07:02:25.423Z] ** failed runs: 4 **
[2024-01-23T07:02:25.423Z] java.lang.Exception: 19)	SunJCE: 	ChaCha20-Poly1305~ChaCha20-Poly1305	 (Cipher)
[2024-01-23T07:02:25.423Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:85)
[2024-01-23T07:02:25.424Z] 	at cryptotest.utils.AlgorithmTest.doTest(AlgorithmTest.java:58)
[2024-01-23T07:02:25.424Z] 	at cryptotest.CryptoTest.main(CryptoTest.java:129)
[2024-01-23T07:02:25.424Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-23T07:02:25.424Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-23T07:02:25.424Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-23T07:02:25.424Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-01-23T07:02:25.424Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-01-23T07:02:25.424Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-01-23T07:02:25.424Z] Caused by: cryptotest.utils.AlgorithmRunException: java.security.ProviderException: Error in Native ChaCha20Cipher
[2024-01-23T07:02:25.424Z] 	at cryptotest.tests.CipherTests.checkAlgorithm(CipherTests.java:140)
[2024-01-23T07:02:25.424Z] 	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
[2024-01-23T07:02:25.424Z] 	... 8 more
[2024-01-23T07:02:25.424Z] Caused by: java.security.ProviderException: Error in Native ChaCha20Cipher
[2024-01-23T07:02:25.424Z] 	at java.base/com.sun.crypto.provider.NativeChaCha20Cipher.init(NativeChaCha20Cipher.java:616)
[2024-01-23T07:02:25.424Z] 	at java.base/com.sun.crypto.provider.NativeChaCha20Cipher.engineInit(NativeChaCha20Cipher.java:361)
[2024-01-23T07:02:25.424Z] 	at java.base/javax.crypto.Cipher.init(Cipher.java:1431)
[2024-01-23T07:02:25.424Z] 	at java.base/javax.crypto.Cipher.init(Cipher.java:1364)
[2024-01-23T07:02:25.424Z] 	at cryptotest.tests.CipherTests.checkAlgorithm(CipherTests.java:125)
[2024-01-23T07:02:25.424Z] 	... 9 more

[2024-01-23T07:02:25.424Z] STDERR:
[2024-01-23T07:02:25.424Z] An OpenSSL error occurred
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0609D0C8:digital envelope routines:int_ctx_new:disabled for FIPS
[2024-01-23T07:02:25.424Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T07:02:25.424Z] An OpenSSL error occurred
[2024-01-23T07:02:25.424Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T07:02:25.424Z] An OpenSSL error occurred
[2024-01-23T07:02:25.424Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T07:02:25.424Z] An OpenSSL error occurred
[2024-01-23T07:02:25.424Z] error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
[2024-01-23T07:02:25.424Z] java.lang.RuntimeException: Some tests failed: 1
[2024-01-23T07:02:25.424Z] 	at cryptotest.CryptoTest.main(CryptoTest.java:171)
[2024-01-23T07:02:25.424Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-23T07:02:25.424Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-23T07:02:25.424Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-23T07:02:25.424Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-01-23T07:02:25.424Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-01-23T07:02:25.424Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-01-23T07:02:25.424Z] 
[2024-01-23T07:02:25.424Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Some tests failed: 1

[2024-01-23T07:02:25.425Z] Test results: passed: 30; failed: 2
[2024-01-23T07:02:25.425Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_linux_fips140_2_testList_2/aqa-tests/TKG/output_17059915792414/CryptoTests_0/report/html/report.html
[2024-01-23T07:02:25.425Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_linux_fips140_2_testList_2/aqa-tests/TKG/output_17059915792414/CryptoTests_0/work
[2024-01-23T07:02:25.425Z] Error: Some tests failed or other problems occurred.
[2024-01-23T07:02:25.425Z] -----------------------------------
[2024-01-23T07:02:25.425Z] CryptoTests_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37516/)

**Comment by pshipton** [comment]
Failed every time in the grinder. 
@jasonkatonica is this failure a problem for the 0.43 release?

**Comment by jasonkatonica** [comment]
Hello, from the above output it appears that `openssl` is reporting that the machine, and the openssl library on the machine, is running in FIPS mode. It also reports that an algorithm has been disabled which I assume is CHACHA given the name of the test itself. 
```
error:0607B0C8:digital envelope routines:EVP_CipherInit_ex:disabled for FIPS
```
In the above log the test is using the flag `-Dsemeru.fips=true` to drive down on NSS in FIPS mode. 

The CHACHA algorithm is not fips certified in the [NSS certificate](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4413.pdf) library so I think that this failure is expected behavior and should fail.

**Comment by pshipton** [comment]
@JasonFengJ9 pls request this test excluded.
