### ISSUE TITLE
jdk22 serviceability jvmti HeapDump/VThreadInHeapDump: IOException: Unrecognized magic number: 1208431

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#18811]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/1
serviceability_jvmti_j9_0
serviceability_jvmti_j9_1
serviceability/jvmti/vthread/HeapDump/VThreadInHeapDump.java
```
16:33:35  STDOUT:
16:33:35  Command line: ['/home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/jdkbinary/j2sdk-image/bin/java' '-ea' '-esa' '-Xmx512m' '-XX:+UseCompressedOops' '-Xverbosegclog' '-Djdk.virtualThreadScheduler.parallelism=1' '-Xlog:heapdump' '-cp' '/home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17059588656297/serviceability_jvmti_j9_0/work/classes/0/serviceability/jvmti/vthread/HeapDump/VThreadInHeapDump_default.d:/home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17059588656297/serviceability_jvmti_j9_0/work/classes/0/test/lib' 'VThreadInHeapDumpTarg' 'e9ae1052-7c2f-404d-96a6-b1172bfe116a.lck']
16:33:35  LingeredApp startup took 1132ms
16:33:35  Check for hs_err_pid/core/mdmp files:
16:33:35  None.
16:33:35  [jcmd]:/home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/jdkbinary/j2sdk-image/bin/jcmd 731422 GC.heap_dump /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17059588656297/serviceability_jvmti_j9_0/work/scratch/1/Myheapdump.hprof
16:33:35  [jcmd] Dump written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17059588656297/serviceability_jvmti_j9_0/work/scratch/1/Myheapdump.hprof
16:33:35   LingeredApp stdout: [];
16:33:35   LingeredApp stderr: [JVMJ9VM007W Command-line option unrecognised: -Xlog:heapdump
16:33:35  JVMDUMP034I User requested Heap dump using '/home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17059588656297/serviceability_jvmti_j9_0/work/scratch/1/Myheapdump.hprof' through com.ibm.jvm.Dump.heapDumpToFile
16:33:35  JVMDUMP010I Heap dump written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17059588656297/serviceability_jvmti_j9_0/work/scratch/1/Myheapdump.hprof
16:33:35  ]
16:33:35   LingeredApp exitValue = 0
16:33:35  Reading Myheapdump.hprof...
16:33:35  STDERR:
16:33:35  java.io.IOException: Unrecognized magic number: 1208431
16:33:35  	at jdk.test.lib.hprof.parser.Reader.readFile(Reader.java:129)
16:33:35  	at VThreadInHeapDump.verifyDump(VThreadInHeapDump.java:220)
16:33:35  	at VThreadInHeapDump.main(VThreadInHeapDump.java:178)
16:33:35  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
16:33:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
16:33:35  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
16:33:35  	at java.base/java.lang.Thread.run(Thread.java:1582)
16:33:35  
16:33:35  JavaTest Message: Test threw exception: java.io.IOException
```

**Comment by babsingh** [comment]
The failing test can be excluded since `-Xlog:heapdump` is not supported in OpenJ9.

**Comment by babsingh** [comment]
Closing. Existing excludes are sufficient. https://github.com/adoptium/aqa-tests/pull/5037 is no longer needed since test automation will scan the issues for the **"perm excluded"** label to prevent re-enabling permanently disabled tests.
