### ISSUE TITLE
JDK21 AIX jdk_tools_openj9_DynamicLoadWarningTest_0_FAILED RuntimeException: 'WARNING: A JVM TI agent has been loaded dynamically' found in stderr

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18845]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix/30/)(`paix821`):
```
java version "21.0.2" 2024-01-16 LTS
IBM Semeru Runtime Certified Edition 21.0.2.0-rc3 (build 21.0.2+13-LTS)
Eclipse OpenJ9 VM 21.0.2.0-rc3 (build v0.43.0-release-220e78c65, JRE 21 AIX ppc64-64-Bit Compressed References 20240116_90 (JIT enabled, AOT enabled)
OpenJ9   - 220e78c65
OMR      - ea8124dbc
JCL      - 9ac3d866bce based on jdk-21.0.2+13)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_tools_openj9_DynamicLoadWarningTest_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=1&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-aix-ppc64-openj9-IBM%2F90%2Fibm-semeru-certified-jdk_ppc64_aix_21.0.2.0-rc3.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-aix-ppc64-openj9-IBM%2F90%2Fibm-semeru-certified-testimage_ppc64_aix_21.0.2.0-rc3.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.0-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.43.0-release&amp;OPENJ9_BRANCH=v0.43.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.43.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-01-26T10:27:24.441Z] variation: Mode150
[2024-01-26T10:27:24.441Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-01-26T10:28:15.882Z] TEST: com/sun/tools/attach/warnings/DynamicLoadWarningTest.java

[2024-01-26T10:28:15.886Z] STARTED    DynamicLoadWarningTest::testLoadOneJvmtiAgent '[1] DynamicLoadWarningTest$$Lambda/0x0000000022d96160@61b56689'
[2024-01-26T10:28:15.886Z]  stdout: [];
[2024-01-26T10:28:15.886Z]  stderr: [WARNING: A JVM TI agent has been loaded dynamically ()
[2024-01-26T10:28:15.886Z] WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
[2024-01-26T10:28:15.886Z] WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
[2024-01-26T10:28:15.886Z] WARNING: Dynamic loading of agents will be disallowed by default in a future release
[2024-01-26T10:28:15.886Z] ]
[2024-01-26T10:28:15.886Z]  exitValue = 0
[2024-01-26T10:28:15.886Z] 
[2024-01-26T10:28:15.886Z] java.lang.RuntimeException: 'WARNING: A JVM TI agent has been loaded dynamically' found in stderr
[2024-01-26T10:28:15.886Z] 	at jdk.test.lib.process.OutputAnalyzer.stderrShouldNotContain(OutputAnalyzer.java:320)
[2024-01-26T10:28:15.886Z] 	at DynamicLoadWarningTest$AppRunner.stderrShouldNotContain(DynamicLoadWarningTest.java:313)
[2024-01-26T10:28:15.886Z] 	at DynamicLoadWarningTest.testLoadOneJvmtiAgent(DynamicLoadWarningTest.java:137)
[2024-01-26T10:28:15.886Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-01-26T10:28:15.886Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-01-26T10:28:15.886Z] 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
[2024-01-26T10:28:15.886Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:142)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:110)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:110)
[2024-01-26T10:28:15.887Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:44)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2024-01-26T10:28:15.887Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
[2024-01-26T10:28:15.887Z] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
[2024-01-26T10:28:15.887Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:142)
[2024-01-26T10:28:15.887Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
[2024-01-26T10:28:15.887Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
[2024-01-26T10:28:15.887Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-01-26T10:28:15.887Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-01-26T10:28:15.887Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-01-26T10:28:15.887Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-01-26T10:28:15.887Z] FAILED     DynamicLoadWarningTest::testLoadOneJvmtiAgent '[1] DynamicLoadWarningTest$$Lambda/0x0000000022d96160@61b56689'

[2024-01-26T10:28:29.491Z] jdk_tools_openj9_DynamicLoadWarningTest_0_FAILED
```
3x re-run automatically launched all failed.

There was a test change introduced [8315706: com/sun/tools/attach/warnings/DynamicLoadWarningTest.java real fix for failure on AIX](https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/83fc302832f7d928b49661f78149c78e07a9542f) merged via [Merge master jdk-21.0.2+13 into openj9-staging](https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/bcf26030faac0962701929e93a3d12d64a861335) on Jan. 17th.
It didn't appear in earlier milestone builds.

This is part of [JEP 451: Prepare to Disallow the Dynamic Loading of Agents](https://openjdk.org/jeps/451).
The test in question starts `loadJvmtiAgent1` via the command line, then dynamically loads loadJvmtiAgent1, previously `AIX` platform was excluded because it can't detect if an agent library was previously loaded.

Considering this is a recent test change, tentatively assign it to `0.44` milestone.

FYI @pshipton @tajila

**Comment by JasonFengJ9** [comment]
The [testcase in question](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/054e5152a5936031f52de2f874bed8167f275cb3/test/jdk/com/sun/tools/attach/warnings/DynamicLoadWarningTest.java#L134-L137) first loads the agent library via a command line option `-agentpath:/path/to/agent/libJvmtiAgent1.so`, then loads the same library via `jcmd` `AttachAPI` command `JVMTI.agent_load` using a platform independent name `JvmtiAgent1`.
The test expects that the JVM detects they are the same libraries, and no warning message to be printed because the first loading via a command line option has no warning, and the second loading is for the same library.

The RI `AIX` fix was proposed at https://mail.openjdk.org/pipermail/hotspot-dev/2023-September/078870.html
> The root cause is, that dlopen() on AIX returns different handles every time, even if you load a library twice. There is no official AIX API available to get this information on a different way.
> My proposal is, to use the stat64x API with the fields st_device and st_inode. After a dlopen() the stat64x() API is called additionally to get this information which is then stored parallel to the library handle in the jvmtiAgent. For AIX we then can compare these values instead of the library handle and get the same functionality as on linux.

Another option suggested by `AIX` kernel folks was to use `loadquery()` to retrieve a list of object files loaded before attempting a platform-independent agent library loading, search the library name, if found, check if its path is in `LIBPATH`, if so, the library was already loaded. This check can be added along existing https://github.com/eclipse-openj9/openj9/blob/40a4d38b2e1fd6c7ed134dbd764dc1ad800bb85c/runtime/jvmti/jvmtiStartup.c#L1074-L1082 

@zl-wang is this still the way to pursue comparing with RI usage of `stat64x` API and simulation of `dlopen()` library searching algorithm?

**Comment by zl-wang** [comment]
@JasonFengJ9 the suggestion sounded reasonable to me moving forward.

**Comment by keithc-ca** [comment]
Jenkins compile aix,amac jdk21
