### ISSUE TITLE
JDK21 jdk_security3_0_FAILED sun/security/pkcs11/sslecc/ClientJSSEServerJSSE.java Exception: Test 'Client JSSE - Server JSSE' failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18846]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/30/)(`rhel8le-svl-rt6-1`):
```
java version "21.0.2" 2024-01-16 LTS
IBM Semeru Runtime Certified Edition 21.0.2.0-rc3 (build 21.0.2+13-LTS)
Eclipse OpenJ9 VM 21.0.2.0-rc3 (build v0.43.0-release-220e78c65, JRE 21 Linux ppc64le-64-Bit Compressed References 20240116_89 (JIT enabled, AOT enabled)
OpenJ9   - 220e78c65
OMR      - ea8124dbc
JCL      - 9ac3d866bce based on jdk-21.0.2+13)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=1&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F89%2Fibm-semeru-certified-jdk_ppc64le_linux_21.0.2.0-rc3.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F89%2Fibm-semeru-certified-testimage_ppc64le_linux_21.0.2.0-rc3.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.0-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.43.0-release&amp;OPENJ9_BRANCH=v0.43.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.43.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-01-26T01:56:05.524Z] variation: Mode150
[2024-01-26T01:56:05.524Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-01-26T02:20:59.456Z] TEST: sun/security/pkcs11/sslecc/ClientJSSEServerJSSE.java

[2024-01-26T02:20:59.470Z] STDERR:
[2024-01-26T02:20:59.470Z] WARNING: A terminally deprecated method in java.lang.System has been called
[2024-01-26T02:20:59.470Z] WARNING: System::setSecurityManager has been called by PKCS11Test (file:/home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_17062302419784/jdk_security3_0/work/classes/1/sun/security/pkcs11/sslecc/ClientJSSEServerJSSE.d/)
[2024-01-26T02:20:59.470Z] WARNING: Please consider reporting this to the maintainers of PKCS11Test
[2024-01-26T02:20:59.470Z] WARNING: System::setSecurityManager will be removed in a future release
[2024-01-26T02:20:59.470Z] java.io.IOException: Invalid response: HTTP/1.0 200ÀïF)ç¶
[2024-01-26T02:20:59.470Z] 	at CipherTest$Client.sendRequest(CipherTest.java:281)
[2024-01-26T02:20:59.470Z] 	at JSSEClient.runTest(JSSEClient.java:74)
[2024-01-26T02:20:59.470Z] 	at CipherTest$Client.run(CipherTest.java:252)
[2024-01-26T02:20:59.470Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-01-26T02:20:59.470Z] java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
[2024-01-26T02:20:59.470Z] 	at CipherTest.run(CipherTest.java:209)
[2024-01-26T02:20:59.470Z] 	at CipherTest.main(CipherTest.java:337)
[2024-01-26T02:20:59.470Z] 	at ClientJSSEServerJSSE.main(ClientJSSEServerJSSE.java:67)
[2024-01-26T02:20:59.470Z] 	at PKCS11Test.premain(PKCS11Test.java:870)
[2024-01-26T02:20:59.470Z] 	at PKCS11Test.testNSS(PKCS11Test.java:486)
[2024-01-26T02:20:59.470Z] 	at PKCS11Test.main(PKCS11Test.java:186)
[2024-01-26T02:20:59.470Z] 	at ClientJSSEServerJSSE.main(ClientJSSEServerJSSE.java:57)
[2024-01-26T02:20:59.470Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-01-26T02:20:59.470Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-01-26T02:20:59.470Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-01-26T02:20:59.470Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-01-26T02:20:59.470Z] 
[2024-01-26T02:20:59.470Z] JavaTest Message: Test threw exception: java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***

[2024-01-26T02:20:59.471Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
[2024-01-26T02:20:59.471Z] --------------------------------------------------
[2024-01-26T03:16:26.846Z] Test results: passed: 918; failed: 1
[2024-01-26T03:16:39.328Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_17062302419784/jdk_security3_0/report/html/report.html
[2024-01-26T03:16:39.328Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_17062302419784/jdk_security3_0/work
[2024-01-26T03:16:39.328Z] Error: Some tests failed or other problems occurred.
[2024-01-26T03:16:39.328Z] -----------------------------------
[2024-01-26T03:16:39.328Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37680/)

**Comment by JasonFengJ9** [comment]
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37680/) - 20/50 failed

Reproduced the initial `IOException: Invalid response:`.
```
22:04:08  STDERR:
22:04:08  java.io.IOException: Invalid response: HTPjÜÐ¡O÷³H;
22:04:08  	at CipherTest$Client.sendRequest(CipherTest.java:281)
22:04:08  	at JSSEClient.runTest(JSSEClient.java:74)
22:04:08  	at CipherTest$Client.run(CipherTest.java:252)
22:04:08  	at java.base/java.lang.Thread.run(Thread.java:1595)
22:04:08  java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
22:04:08  	at CipherTest.run(CipherTest.java:209)
22:04:08  	at CipherTest.main(CipherTest.java:337)
22:04:08  	at ClientJSSEServerJSSE.main(ClientJSSEServerJSSE.java:67)
22:04:08  	at PKCS11Test.premain(PKCS11Test.java:870)
22:04:08  	at PKCS11Test.testNSS(PKCS11Test.java:486)
22:04:08  	at PKCS11Test.main(PKCS11Test.java:186)
22:04:08  	at ClientJSSEServerJSSE.main(ClientJSSEServerJSSE.java:57)
22:04:08  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
22:04:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
22:04:08  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
22:04:08  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

Also `PKCS11Exception: CKR_ENCRYPTED_DATA_INVALID`
```
18:48:17  Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ENCRYPTED_DATA_INVALID
18:48:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.implDoFinal(P11AEADCipher.java:770)
18:48:17  	... 15 more
18:48:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.implDoFinal(P11AEADCipher.java:785)
18:48:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.engineDoFinal(P11AEADCipher.java:605)
18:48:17  	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2543)
18:48:17  	at java.base/sun.security.ssl.SSLCipher$T12CC20P1305ReadCipherGenerator$CC20P1305ReadCipher.decrypt(SSLCipher.java:2169)
18:48:17  	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:264)
18:48:17  	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
18:48:17  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
18:48:17  	... 9 more
18:48:17  Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ENCRYPTED_DATA_INVALID
18:48:17  java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
18:48:17  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11AEADCipher.implDoFinal(P11AEADCipher.java:770)
18:48:17  	... 15 more
18:48:17  	at CipherTest.run(CipherTest.java:209)
18:48:17  	at CipherTest.main(CipherTest.java:337)
18:48:17  	at ClientJSSEServerJSSE.main(ClientJSSEServerJSSE.java:67)
18:48:17  	at PKCS11Test.premain(PKCS11Test.java:870)
18:48:17  	at PKCS11Test.testNSS(PKCS11Test.java:486)
18:48:17  	at PKCS11Test.main(PKCS11Test.java:186)
18:48:17  	at ClientJSSEServerJSSE.main(ClientJSSEServerJSSE.java:57)
18:48:17  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
18:48:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
18:48:17  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
18:48:17  	at java.base/java.lang.Thread.run(Thread.java:1595)
18:48:17  
18:48:17  JavaTest Message: Test threw exception: java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
```

`SocketException: Socket is closed`
```
20:14:36  javax.net.ssl|WARNING|A1|Client 2|2024-01-29 17:14:22.713 PST|SSLSocketImpl.java:576|SSLSocket duplex close failed. Debug info only. Exception details: (
20:14:36  "throwable" : {
20:14:36    java.net.SocketException: Socket is closed
20:14:36    	at java.base/java.net.Socket.shutdownInput(Socket.java:1756)
20:14:36    	at java.base/sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:224)
20:14:36    	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:850)
20:14:36    	at java.base/sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(SSLSocketImpl.java:799)
20:14:36    	at java.base/sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:664)
20:14:36    	at java.base/sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:584)
20:14:36    	at JSSEClient.runTest(JSSEClient.java:108)
20:14:36    	at CipherTest$Client.run(CipherTest.java:252)
20:14:36    	at java.base/java.lang.Thread.run(Thread.java:1595)}
20:14:36  
20:14:36  )
20:14:36  java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***
```

[50x grinder w/ RI](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37687/)
