### ISSUE TITLE
DDR !vthreads failed at VirtualThreadsCommand.getName

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse-openj9/openj9#18859]
While I was working on  https://github.com/eclipse-openj9/openj9/issues/18706 I noticed for core https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Release_testList_0/5/openjdk_test_output.tar.gz

An attempt to do `!vthreads` failed half-way with error:
```
> !vthreads
!continuationstack 0x0000000000000000 !j9vmcontinuation 0x0000000000000000 !j9object 0x00007FF4FBA7FD80 (Continuation) !j9object 0x00007FF4FBA7FC80 (VThread) -
.....
!continuationstack 0x0000021d5a2ffdf0 !j9vmcontinuation 0x0000021d5a2ffdf0 !j9object 0x00007FF4F77DA050 (Continuation) !j9object 0x00007FF4F77D9F50 (VThread) -
!continuationstack 0x0000021c8415cdb0 !j9vmcontinuation 0x0000021c8415cdb0 !j9object 0x00007FF4F77DA298 (Continuation) !j9object 0x00007FF4F77DA198 (VThread) -
Problem running command:
com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: com.ibm.j9ddr.NullPointerDereference: Memory Fault reading 0x00000000 :
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.VirtualThreadsCommand.run(VirtualThreadsCommand.java:91)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
	at openj9.dtfj/com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:78)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:258)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:169)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:813)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:767)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:741)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.run(Session.java:665)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: com.ibm.j9ddr.NullPointerDereference: Memory Fault reading 0x00000000 :
	at com.ibm.j9ddr.vm29.pointer.AbstractPointer.getLongAtOffset(AbstractPointer.java:456)
	at com.ibm.j9ddr.vm29.pointer.generated.J9ObjectFullPointer.clazz(Unknown Source)
	at com.ibm.j9ddr.vm29.pointer.helper.J9ObjectHelper.rawClazz(J9ObjectHelper.java:118)
	at com.ibm.j9ddr.vm29.pointer.helper.J9ObjectHelper.clazz(J9ObjectHelper.java:132)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.isIndexable(GCObjectModel_V1.java:209)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.getHeaderSize(GCObjectModel_V1.java:376)
	at com.ibm.j9ddr.vm29.j9.ObjectModel.getHeaderSize(ObjectModel.java:376)
	at com.ibm.j9ddr.vm29.pointer.helper.J9ObjectHelper.getObjectField(J9ObjectHelper.java:403)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.VirtualThreadsCommand.getName(VirtualThreadsCommand.java:76)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.VirtualThreadsCommand.displayVirtualThreads(VirtualThreadsCommand.java:115)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.VirtualThreadsCommand.run(VirtualThreadsCommand.java:88)
	... 19 more
```

**Comment by dmitripivkine** [comment]
FYI @fengxue-IS @babsingh
