### ISSUE TITLE
jdk11 acceptance testGetMBeanInfo expected:<18> but was:<19>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18877]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_OpenJDK11_testList_1/75
JLM_Tests_interface
```
10:22:29  FAILED: testGetMBeanInfo
10:22:29  java.lang.AssertionError: expected:<18> but was:<19>
10:22:29  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
10:22:29  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
10:22:29  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
10:22:29  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
10:22:29  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
10:22:29  	at org.openj9.test.java.lang.management.TestThreadMXBean.testGetMBeanInfo(TestThreadMXBean.java:1587)
```

**Comment by pshipton** [comment]
[ 8304074: [JMX] Add an approximation of total bytes allocated on the Java heap by the JVM](https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/451b18a2358227d7f2eae550e4b1d157dd22391c) added the following.
```
    public default long getTotalThreadAllocatedBytes() {
        if (!isThreadAllocatedMemorySupported()) {
            throw new UnsupportedOperationException(
                "Thread allocated memory measurement is not supported.");
        }
        return -1;
    }
```
