### ISSUE TITLE
jdk22 mac10 UnsatisfiedLinkError: Failed to load library libawt.dylib   Reason: image not found

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18909]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/1/ - [mac10-x86-4](https://openj9-jenkins.osuosl.org/computer/mac10-x86-4)
jdk_lang_0, jdk_lang_j9_0
java/lang/RuntimeTests/loadLibrary/LoadLibraryTest.java
```
21:46:50  java.lang.UnsatisfiedLinkError: Failed to load library ("/Users/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libawt.dylib") dlopen(/Users/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libawt.dylib, 1): Library not loaded: /System/Library/Frameworks/JavaRuntimeSupport.framework/Versions/A/JavaRuntimeSupport   Referenced from: /Users/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libawt.dylib   Reason: image not found
21:46:50  	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
21:46:50  	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:349)
21:46:50  	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:215)
21:46:50  	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:157)
21:46:50  	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:277)
21:46:50  	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:267)
21:46:50  	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
21:46:50  	at java.base/java.lang.System.loadLibrary(System.java:806)
21:46:50  	at Target2.<clinit>(Target2.java:26)
```

Also 

jdk_util_1 with `-XX:-UseCompressedOops`
java/util/ResourceBundle/Bug6299235/Bug6299235Test.java
java/util/ResourceBundle/Control/Bug6530694.java
java/util/logging/TestLoggingWithMainAppContext.java
java/util/logging/TestMainAppContext.java

and in https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/1 - [mac10-x86-2](https://openj9-jenkins.osuosl.org/computer/mac10-x86-2)
jdk_lang_1
java/lang/RuntimeTests/loadLibrary/LoadLibraryTest.java
jdk_security1_0 with `-XX:+UseCompressedOops`
java/security/Security/ClassLoaderDeadlock/ClassLoaderDeadlock.sh

**Comment by pshipton** [comment]
And in functional testing

https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_x86-64_mac_Nightly_testList_0/1
cmdLineTester_callsitedbgddrext_openj9
cmdLineTester_GCCheck

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_x86-64_mac_Nightly_testList_2/2 - [mac10-x86-3](https://openj9-jenkins.osuosl.org/computer/mac10-x86-3)
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_x86-64_mac_Nightly_testList_1/2/ - [mac10-x86-2](https://openj9-jenkins.osuosl.org/computer/mac10-x86-2)

**Comment by pshipton** [comment]
Looks to me that jdk22 no longer support macOS 10. The machines are all 10.15 according to the node labels.
