### ISSUE TITLE
Strings that should be equal are detected as different

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18920]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_1/656
JLM_Tests_class_0
```
00:51:47  FAILED: testThreadMXBeanProxy
00:51:47  java.lang.AssertionError: expected:<"main" prio=5 Id=1 RUNNABLE
00:51:47  > but was:<"main" prio=5 Id=1 RUNNABLE
00:51:47  >
00:51:47  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
00:51:47  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
00:51:47  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
00:51:47  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
00:51:47  	at org.openj9.test.java.lang.management.TestManagementFactory.testThreadMXBeanProxy(TestManagementFactory.java:1304)
```

**Comment by pshipton** [comment]
@r30shah @hzongaro fyi. Not sure if this is a very rare occurrence or related to some recent change. Or even what platforms are affected.

**Comment by hzongaro** [comment]
Looking at [`TestManagementFactory.testThreadMXBeanProxy`](https://github.com/eclipse-openj9/openj9/blob/c102e758c66171c8d4ab08d58fdbd2758c3b5b45/test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestManagementFactory.java#L1304) I think it's actually `ThreadInfo` objects that are being tested for equality rather than Strings.

**Comment by pshipton** [comment]
Ah ok, thanks for checking. The equality check looks at many other fields which aren't reflected in the String output. I'll monitor this and if it occurs again modify the test to provide more info about the failure.

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=83639265)
[linux_390-64_cmprssptrs] SE80_GIT JLM_Tests_class_SE80
```
FAILED: testThreadMXBeanProxy
java.lang.AssertionError: expected:<"main" Id=1 RUNNABLE
> but was:<"main" Id=1 RUNNABLE
>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
	at org.openj9.test.java.lang.management.TestManagementFactory.testThreadMXBeanProxy(TestManagementFactory.java:1304)
```

**Comment by pshipton** [comment]
A new failure occurred with the debug output.
`waitedCount ti1: 0 ti2: 4`

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_sanity.functional_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.functional_aarch64_linux_testList_4/44/)
```
[2025-07-16T19:04:27.641Z] Running test JLM_Tests_class_1 ...
[2025-07-16T19:04:27.641Z] ===============================================
[2025-07-16T19:04:27.641Z] JLM_Tests_class_1 Start Time: Wed Jul 16 15:04:27 2025 Epoch Time (ms): 1752692667317
[2025-07-16T19:04:27.641Z] variation: -XX:+HeapManagementMXBeanCompatibility
[2025-07-16T19:04:27.641Z] JVM_OPTIONS:  -XX:+HeapManagementMXBeanCompatibility 

[2025-07-16T19:04:30.435Z] FAILED: testThreadMXBeanProxy
[2025-07-16T19:04:30.435Z] java.lang.AssertionError: expected:<"main" prio=5 Id=2 RUNNABLE
[2025-07-16T19:04:30.435Z] > but was:<"main" prio=5 Id=2 RUNNABLE
[2025-07-16T19:04:30.435Z] >
[2025-07-16T19:04:30.435Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2025-07-16T19:04:30.435Z] 	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
[2025-07-16T19:04:30.435Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
[2025-07-16T19:04:30.435Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
[2025-07-16T19:04:30.435Z] 	at org.openj9.test.java.lang.management.TestManagementFactory.testThreadMXBeanProxy(TestManagementFactory.java:1335)
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_sanity.functional_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_testList_2_rerun/5/)
```
[2026-07-11T07:32:33.605Z] Running test JLM_Tests_class_1 ...
[2026-07-11T07:32:33.605Z] ===============================================
[2026-07-11T07:32:33.605Z] JLM_Tests_class_1 Start Time: Sat Jul 11 03:32:25 2026 Epoch Time (ms): 1783755145820
[2026-07-11T07:32:33.605Z] variation: -XX:+HeapManagementMXBeanCompatibility
[2026-07-11T07:32:33.605Z] JVM_OPTIONS:  -XX:+HeapManagementMXBeanCompatibility 

[2026-07-11T07:32:33.614Z] FAILED: testThreadMXBeanProxy
[2026-07-11T07:32:33.614Z] java.lang.AssertionError: expected:<"main" prio=5 Id=1 RUNNABLE
[2026-07-11T07:32:33.614Z] > but was:<"main" prio=5 Id=1 RUNNABLE
[2026-07-11T07:32:33.614Z] >
[2026-07-11T07:32:33.614Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2026-07-11T07:32:33.614Z] 	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
[2026-07-11T07:32:33.614Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
[2026-07-11T07:32:33.614Z] 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
[2026-07-11T07:32:33.614Z] 	at org.openj9.test.java.lang.management.TestManagementFactory.testThreadMXBeanProxy(TestManagementFactory.java:1335)
```
