### ISSUE TITLE
jdk22 java/foreign/TestHFA.java testAddDoubleToStructAfterStructs testAddFloatToStructAfterStructs failure

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18944]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/5/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/5
jdk_foreign
java/foreign/TestHFA.java

```
23:07:25  S_FF(1.6745138;1.0)
23:07:25  test TestHFA.testAddDoubleToStructAfterStructs(): failure
23:07:25  java.lang.RuntimeException: add_double_to_struct_after_structs error
23:07:25  	at TestHFA.testAddDoubleToStructAfterStructs(TestHFA.java:193)
...
23:07:25  test TestHFA.testAddFloatToLargeStructAfterStructs(): failure
23:07:25  java.lang.RuntimeException: add_float_to_large_struct_after_structs error
23:07:25  	at TestHFA.testAddFloatToLargeStructAfterStructs(TestHFA.java:223)
...
23:07:25  test TestHFA.testAddFloatToStructAfterStructs(): failure
23:07:25  java.lang.RuntimeException: add_float_to_struct_after_structs error
23:07:25  	at TestHFA.testAddFloatToStructAfterStructs(TestHFA.java:174)
```

@ChengJin01

**Comment by pshipton** [comment]
Perhaps related to https://github.com/eclipse-openj9/openj9/issues/17953

**Comment by ChengJin01** [comment]
> Perhaps related to #17953

If so, we might need to reach out to the Open XL compiler team to see whether they can help to fix the libffi specific issue there.

**Comment by ChengJin01** [comment]
As discussed with @zl-wang offline, the fix won't be ready very soon given it is a corner case on pLinux which should be lower priority even though it is identified as a bug with double-passing in libffi/pLinux at https://github.com/eclipse-openj9/openj9/issues/17953.

**Comment by ChengJin01** [comment]
@pshipton, can we close this issue as duplicate with https://github.com/eclipse-openj9/openj9/issues/17953?

**Comment by pshipton** [comment]
I don''t want to close it since it's there is a test excluded against it, but we can remove it from the Java 22 milestone plan.

**Comment by tajila** [comment]
@zl-wang @ChengJin01 any update on this?

**Comment by ChengJin01** [comment]
As explained at https://github.com/eclipse-openj9/openj9/issues/17953 (the duplicate tests on JDK21), the failure is simply a corner case for double passing in libffi on pLinux which is not in the priority list to be addressed for now.
