### ISSUE TITLE
java/util/concurrent/FutureTask/BlockingTaskExecutor Some tests failed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18956]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OMR_testList_0/80
jdk_util_0
java/util/concurrent/FutureTask/BlockingTaskExecutor.java
```
06:01:17  STDOUT:
06:01:17  ....................................................................................
06:01:17  Passed = 0, failed = 1
06:01:17  
06:01:17  STDERR:
06:01:17  java.lang.Error: Executor termination timed out after 80000 ms
06:01:17  	at BlockingTaskExecutor.test(BlockingTaskExecutor.java:84)
06:01:17  	at BlockingTaskExecutor.realMain(BlockingTaskExecutor.java:52)
06:01:17  	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:172)
06:01:17  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
06:01:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
06:01:17  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
06:01:17  	at java.base/java.lang.Thread.run(Thread.java:1595)
06:01:17  java.lang.AssertionError: Some tests failed
06:01:17  	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:174)
06:01:17  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
06:01:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
06:01:17  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
06:01:17  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by JasonFengJ9** [comment]
[JDK22 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_testList_2/6/)(`sles15-aarch64-6`)
```
[2024-07-26T21:01:05.616Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2024-07-26T21:01:05.616Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2024-07-26T21:08:57.525Z] TEST: java/util/concurrent/FutureTask/BlockingTaskExecutor.java

[2024-07-26T21:08:57.527Z] STDERR:
[2024-07-26T21:08:57.527Z] java.lang.Error: Executor termination timed out after 80000 ms
[2024-07-26T21:08:57.527Z] 	at BlockingTaskExecutor.test(BlockingTaskExecutor.java:84)
[2024-07-26T21:08:57.527Z] 	at BlockingTaskExecutor.realMain(BlockingTaskExecutor.java:52)
[2024-07-26T21:08:57.527Z] 	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:172)
[2024-07-26T21:08:57.527Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-07-26T21:08:57.527Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-07-26T21:08:57.527Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-07-26T21:08:57.527Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-07-26T21:08:57.527Z] java.lang.AssertionError: Some tests failed
[2024-07-26T21:08:57.527Z] 	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:174)
[2024-07-26T21:08:57.527Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-07-26T21:08:57.527Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-07-26T21:08:57.527Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-07-26T21:08:57.527Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-07-26T21:08:57.527Z] 
[2024-07-26T21:08:57.527Z] JavaTest Message: Test threw exception: java.lang.AssertionError
[2024-07-26T21:08:57.527Z] JavaTest Message: shutting down test
[2024-07-26T21:08:57.527Z] 
[2024-07-26T21:08:57.527Z] java.lang.InterruptedException
[2024-07-26T21:08:57.527Z] 	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:471)
[2024-07-26T21:08:57.527Z] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[2024-07-26T21:08:57.527Z] 	at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:252)
[2024-07-26T21:08:57.527Z] 	at BlockingTaskExecutor$1.run(BlockingTaskExecutor.java:69)
[2024-07-26T21:08:57.527Z] 
[2024-07-26T21:08:57.527Z] JavaTest Message: Problem cleaning up the following threads:
[2024-07-26T21:08:57.527Z] pool-137-thread-1
[2024-07-26T21:08:57.527Z]   at java.base/java.lang.Object.waitImpl(Native Method)
[2024-07-26T21:08:57.527Z]   at java.base/java.lang.Object.wait(Object.java:255)
[2024-07-26T21:08:57.527Z]   at java.base/java.lang.Object.wait(Object.java:192)
[2024-07-26T21:08:57.527Z]   at BlockingTaskExecutor$BlockingTask.call(BlockingTaskExecutor.java:146)
[2024-07-26T21:08:57.527Z]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-07-26T21:08:57.527Z]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-07-26T21:08:57.527Z]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-07-26T21:08:57.527Z]   at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-07-26T21:08:57.527Z] 
[2024-07-26T21:08:57.527Z] 
[2024-07-26T21:08:57.527Z] TEST RESULT: Error. Error while cleaning up threads after test
[2024-07-26T21:08:57.527Z] --------------------------------------------------
[2024-07-26T21:25:07.573Z] Test results: passed: 972; error: 1
[2024-07-26T21:25:30.153Z] Report written to /home/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_testList_2/aqa-tests/TKG/output_17220241737133/jdk_util_1/report/html/report.html
[2024-07-26T21:25:30.153Z] Results written to /home/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_testList_2/aqa-tests/TKG/output_17220241737133/jdk_util_1/work
[2024-07-26T21:25:30.153Z] Error: Some tests failed or other problems occurred.
[2024-07-26T21:25:30.153Z] -----------------------------------
[2024-07-26T21:25:30.153Z] jdk_util_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42517/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/307/
jdk_util_1
java/util/concurrent/FutureTask/BlockingTaskExecutor.java
```
02:25:29  java.lang.Error: Executor stuck
02:25:29  	at BlockingTaskExecutor.test(BlockingTaskExecutor.java:75)
02:25:29  	at BlockingTaskExecutor.realMain(BlockingTaskExecutor.java:43)
02:25:29  	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:160)
02:25:29  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:25:29  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:25:29  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:25:29  	at java.lang.reflect.Method.invoke(Method.java:503)
02:25:29  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
02:25:29  	at java.lang.Thread.run(Thread.java:822)
02:25:29  java.lang.AssertionError: Some tests failed
02:25:29  	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:162)
02:25:29  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:25:29  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:25:29  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:25:29  	at java.lang.reflect.Method.invoke(Method.java:503)
02:25:29  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
02:25:29  	at java.lang.Thread.run(Thread.java:822)
02:25:29  
02:25:29  JavaTest Message: Test threw exception: java.lang.AssertionError
02:25:29  JavaTest Message: shutting down test
02:25:29  
02:25:29  java.lang.InterruptedException
02:25:29  	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
02:25:29  	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
02:25:29  	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:244)
02:25:29  	at BlockingTaskExecutor$1.run(BlockingTaskExecutor.java:61)
02:25:29  
02:25:29  JavaTest Message: Problem cleaning up the following threads:
02:25:29  pool-69-thread-2
02:25:29    at java.lang.Object.waitImpl(Native Method)
02:25:29    at java.lang.Object.wait(Object.java:248)
02:25:29    at java.lang.Object.wait(Object.java:187)
02:25:29    at BlockingTaskExecutor$BlockingTask.call(BlockingTaskExecutor.java:134)
02:25:29    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:25:29    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:25:29    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:25:29    at java.lang.Thread.run(Thread.java:822)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8_testList_2/43/
jdk_util_1
```
23:45:03  java.lang.Error: Executor stuck
23:45:03  	at BlockingTaskExecutor.test(BlockingTaskExecutor.java:75)
23:45:03  	at BlockingTaskExecutor.realMain(BlockingTaskExecutor.java:43)
23:45:03  	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:160)
23:45:03  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:45:03  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:45:03  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:45:03  	at java.lang.reflect.Method.invoke(Method.java:503)
23:45:03  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
23:45:03  	at java.lang.Thread.run(Thread.java:822)
23:45:03  java.lang.AssertionError: Some tests failed
23:45:03  	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:162)
```

**Comment by 0xdaryl** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OMR_testList_3/65/consoleText
```
[2026-08-26T10:48:28.886Z] java.lang.Error: Executor termination timed out after 120000 ms
[2026-08-26T10:48:28.886Z] 	at BlockingTaskExecutor.test(BlockingTaskExecutor.java:84)
[2026-08-26T10:48:28.886Z] 	at BlockingTaskExecutor.realMain(BlockingTaskExecutor.java:52)
[2026-08-26T10:48:28.886Z] 	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:172)
[2026-08-26T10:48:28.886Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2026-08-26T10:48:28.886Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2026-08-26T10:48:28.886Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2026-08-26T10:48:28.886Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2026-08-26T10:48:28.886Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:335)
[2026-08-26T10:48:28.886Z] 	at java.base/java.lang.Thread.run(Thread.java:854)
[2026-08-26T10:48:28.886Z] java.lang.AssertionError: Some tests failed
[2026-08-26T10:48:28.886Z] 	at BlockingTaskExecutor.main(BlockingTaskExecutor.java:174)
[2026-08-26T10:48:28.886Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2026-08-26T10:48:28.886Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2026-08-26T10:48:28.886Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2026-08-26T10:48:28.886Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2026-08-26T10:48:28.886Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:335)
[2026-08-26T10:48:28.886Z] 	at java.base/java.lang.Thread.run(Thread.java:854)
```
