### ISSUE TITLE
JDK22 jdk_nio_1_FAILED java/nio/file/Files/CopyMoveVariations.java java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18973]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_ppc64le_linux_Personal/12/consoleFull)(`sles12le-svl-rt4-1`):
```
22:00:51  openjdk version "22-internal" 2024-03-19
22:00:51  OpenJDK Runtime Environment (build 22-internal-adhoc.jenkins.BuildJDK22ppc64lelinuxPersonal)
22:00:51  Eclipse OpenJ9 VM (build master-f524f995be4, JRE 22 Linux ppc64le-64-Bit Compressed References 20240215_20 (JIT enabled, AOT enabled)
22:00:51  OpenJ9   - f524f995be4
22:00:51  OMR      - 0966eb360f6
22:00:51  JCL      - ff0372607f0 based on jdk-22+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_nio_0,jdk_nio_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK22_ppc64le_linux_Personal%2F20%2FOpenJ9-JDK22-ppc64le_linux-20240215-211428.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK22_ppc64le_linux_Personal%2F20%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=22&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk22.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=f524f995be478326febb4b49d2e8d93c92c9b77a&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:55:51  ===============================================
22:55:51  Running test jdk_nio_1 ...
22:55:51  ===============================================
22:55:51  jdk_nio_1 Start Time: Thu Feb 15 19:55:51 2024 Epoch Time (ms): 1708055751179
22:55:51  variation: Mode650
22:55:51  JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

23:02:06  TEST: java/nio/file/Files/CopyMoveVariations.java

23:02:06  STARTED    CopyMoveVariations::move '[1] FILE, ---------, false, false'
23:02:06  java.nio.file.AccessDeniedException: /tmp/file3975141760663777135dat
23:02:06  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
23:02:06  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
23:02:06  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
23:02:06  	at java.base/sun.nio.fs.UnixFileSystem.copyFile(UnixFileSystem.java:658)
23:02:06  	at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:961)
23:02:06  	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
23:02:06  	at java.base/java.nio.file.Files.move(Files.java:1430)
23:02:06  	at CopyMoveVariations.op(CopyMoveVariations.java:195)
23:02:06  	at CopyMoveVariations.move(CopyMoveVariations.java:136)
23:02:06  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

23:02:06  STARTED    CopyMoveVariations::move '[25] DIR, -w--w--w-, false, false'
23:02:06  org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
23:02:06  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
23:02:06  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
23:02:06  	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
23:02:06  	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
23:02:06  	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
23:02:06  	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:180)
23:02:06  	at CopyMoveVariations.op(CopyMoveVariations.java:215)
23:02:06  	at CopyMoveVariations.move(CopyMoveVariations.java:136)
23:02:06  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

23:02:06  JavaTest Message: JUnit Platform Failure(s): 6
23:02:06  
23:02:06  [ JUnit Containers: found 7, started 7, succeeded 7, failed 0, aborted 0, skipped 0]
23:02:06  [ JUnit Tests: found 144, started 144, succeeded 138, failed 6, aborted 0, skipped 0]
23:02:06  
23:02:06  java.lang.Exception: JUnit test failure
23:02:06  	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:149)
23:02:06  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
23:02:06  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
23:02:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
23:02:06  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
23:02:06  	at java.base/java.lang.Thread.run(Thread.java:1582)
23:02:06  
23:02:06  JavaTest Message: Test threw exception: java.lang.Exception
23:02:06  JavaTest Message: shutting down test
23:02:06  
23:02:06  
23:02:06  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure
23:02:06  --------------------------------------------------
23:09:08  Test results: passed: 411; failed: 1
23:09:30  Report written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_ppc64le_linux_Personal/aqa-tests/TKG/output_17080526345888/jdk_nio_1/report/html/report.html
23:09:30  Results written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_ppc64le_linux_Personal/aqa-tests/TKG/output_17080526345888/jdk_nio_1/work
23:09:30  Error: Some tests failed or other problems occurred.
23:09:30  -----------------------------------
23:09:30  jdk_nio_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/37992/)

Also seen at [JDK22 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_s390x_linux_Personal/10/consoleFull) [JDK22 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_x86-64_linux_Personal/31/consoleFull)

**Comment by pshipton** [comment]
The grinder failed 6/100 but no repeats of this failure.
    sun/nio/cs/TestStringCoding.java.TestStringCoding
    java/nio/channels/Selector/Wakeup.java.Wakeup
    sun/nio/cs/FindOneCharEncoderBugs.java.FindOneCharEncoderBugs
    sun/nio/cs/TestStringCoding.java.TestStringCoding
    sun/nio/cs/TestStringCoding.java.TestStringCoding
    sun/nio/cs/TestStringCoding.java.TestStringCoding

**Comment by JasonFengJ9** [comment]
[JDK22 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_aarch64_linux_testList_1/1/)(`cent7-aarch64-4`)
```
[2024-03-02T21:34:15.351Z] variation: Mode150
[2024-03-02T21:34:15.351Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-02T21:40:53.966Z] TEST: java/nio/file/Files/CopyMoveVariations.java

[2024-03-02T21:40:53.968Z] STARTED    CopyMoveVariations::move '[1] FILE, ---------, false, false'
[2024-03-02T21:40:53.968Z] java.nio.file.AccessDeniedException: /tmp/file13672043759154348209dat
[2024-03-02T21:40:53.968Z] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[2024-03-02T21:40:53.968Z] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[2024-03-02T21:40:53.968Z] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[2024-03-02T21:40:53.968Z] 	at java.base/sun.nio.fs.UnixFileSystem.copyFile(UnixFileSystem.java:658)
[2024-03-02T21:40:53.968Z] 	at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:961)
[2024-03-02T21:40:53.968Z] 	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
[2024-03-02T21:40:53.968Z] 	at java.base/java.nio.file.Files.move(Files.java:1430)
[2024-03-02T21:40:53.968Z] 	at CopyMoveVariations.op(CopyMoveVariations.java:195)
[2024-03-02T21:40:53.968Z] 	at CopyMoveVariations.move(CopyMoveVariations.java:136)

[2024-03-02T21:40:53.972Z] [ JUnit Containers: found 7, started 7, succeeded 7, failed 0, aborted 0, skipped 0]
[2024-03-02T21:40:53.972Z] [ JUnit Tests: found 144, started 144, succeeded 138, failed 6, aborted 0, skipped 0]
[2024-03-02T21:40:53.972Z] 
[2024-03-02T21:40:53.972Z] java.lang.Exception: JUnit test failure
[2024-03-02T21:40:53.972Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:149)
[2024-03-02T21:40:53.972Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
[2024-03-02T21:40:53.972Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-02T21:40:53.972Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-02T21:40:53.973Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-03-02T21:40:53.973Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-03-02T21:40:53.973Z] 
[2024-03-02T21:40:53.973Z] JavaTest Message: Test threw exception: java.lang.Exception
[2024-03-02T21:40:53.973Z] JavaTest Message: shutting down test
[2024-03-02T21:40:53.973Z] 
[2024-03-02T21:40:53.973Z] 
[2024-03-02T21:40:53.973Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure
[2024-03-02T21:40:53.973Z] --------------------------------------------------
[2024-03-02T21:46:24.620Z] Test results: passed: 411; failed: 1
[2024-03-02T21:46:39.454Z] Report written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17094144715310/jdk_nio_0/report/html/report.html
[2024-03-02T21:46:39.455Z] Results written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17094144715310/jdk_nio_0/work
[2024-03-02T21:46:39.455Z] Error: Some tests failed or other problems occurred.
[2024-03-02T21:46:39.455Z] -----------------------------------
[2024-03-02T21:46:39.455Z] jdk_nio_0_FAILED
```

**Comment by singh264** [comment]
@tajila @JasonFengJ9 @pshipton I would like to confirm that this issue is addressed by a [fix](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/7ac37aac8e8fa317d23699aa765a42bf68cd3158) in `jdk-next`. Would you like the fix to be backported to `jdk22`?

**Comment by tajila** [comment]
I've have no objection to backporting
