### ISSUE TITLE
OpenJDK java/util/zip/ZipFile/ZipSourceCache AssertionFailedError: expected: <6> but was: <5>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18987]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/12
jdk_util_0
java/util/zip/ZipFile/ZipSourceCache.java
```
02:54:11  STARTED    ZipSourceCache::testKeySourceMapping 'testKeySourceMapping()'
02:54:11  org.opentest4j.AssertionFailedError: expected: <6> but was: <5>
02:54:11  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
02:54:11  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
02:54:11  	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
02:54:11  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
02:54:11  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
02:54:11  	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
02:54:11  	at ZipSourceCache.testKeySourceMapping(ZipSourceCache.java:100)
02:54:11  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
02:54:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
02:54:11  	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
02:54:11  	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
02:54:11  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
02:54:11  	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
02:54:11  	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
02:54:11  	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
02:54:11  	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
02:54:11  	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
02:54:11  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
02:54:11  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
02:54:11  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
02:54:11  	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
02:54:11  	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
02:54:11  	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
02:54:11  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
02:54:11  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
02:54:11  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
02:54:11  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
02:54:11  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
02:54:11  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
02:54:11  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
02:54:11  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
02:54:11  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
02:54:11  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
02:54:11  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
02:54:11  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
02:54:11  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
02:54:11  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
02:54:11  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
02:54:11  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
02:54:11  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
02:54:11  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
02:54:11  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
02:54:11  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
02:54:11  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
02:54:11  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
02:54:11  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
02:54:11  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
02:54:11  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
02:54:11  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
02:54:11  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
02:54:11  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
02:54:11  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
02:54:11  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
02:54:11  	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
02:54:11  	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:142)
02:54:11  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
02:54:11  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
02:54:11  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
02:54:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
02:54:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
02:54:11  	at java.base/java.lang.Thread.run(Thread.java:1582)
02:54:11  FAILED     ZipSourceCache::testKeySourceMapping 'testKeySourceMapping()'
02:54:11  JavaTest Message: JUnit Platform Failure(s): 1
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/25 - [rh8-390-2](https://openj9-jenkins.osuosl.org/computer/rh8-390-2)
jdk_util_0
java/util/zip/ZipFile/ZipSourceCache.java
```
03:24:49  STARTED    ZipSourceCache::testKeySourceMapping 'testKeySourceMapping()'
03:24:49  org.opentest4j.AssertionFailedError: expected: <6> but was: <5>
03:24:49  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
03:24:49  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
03:24:49  	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
03:24:49  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
03:24:49  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
03:24:49  	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
03:24:49  	at ZipSourceCache.testKeySourceMapping(ZipSourceCache.java:100)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/26/ - [rh7-390-4](https://openj9-jenkins.osuosl.org/computer/rh7-390-4)

**Comment by pshipton** [comment]
20x x 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/3374/

**Comment by tajila** [comment]
@JasonFengJ9 Please take a look at this

**Comment by JasonFengJ9** [comment]
RI failed as well [rh7-390-2](https://openj9-jenkins.osuosl.org/computer/rh7-390-2) - https://openj9-jenkins.osuosl.org/job/Grinder_iteration_0/453/consoleFull 
```
17:58:25  openjdk version "22-beta" 2024-03-19
17:58:25  OpenJDK Runtime Environment Temurin-22+36-202402170011 (build 22-beta+36-ea)
17:58:25  OpenJDK 64-Bit Server VM Temurin-22+36-202402170011 (build 22-beta+36-ea, mixed mode, sharing)

19:11:49  variation:  Mode150
19:11:49  JVM_OPTIONS:   -XX:+UseCompressedOops 

19:18:56  TEST: java/util/zip/ZipFile/ZipSourceCache.java

19:18:56  STDERR:
19:18:56  STARTED    ZipSourceCache::testKeySourceMapping 'testKeySourceMapping()'
19:18:56  org.opentest4j.AssertionFailedError: expected: <6> but was: <5>
19:18:56  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
19:18:56  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
19:18:56  	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
19:18:56  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
19:18:56  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
19:18:56  	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
19:18:56  	at ZipSourceCache.testKeySourceMapping(ZipSourceCache.java:100)

19:18:56  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: JUnit test failure
19:18:56  --------------------------------------------------
19:19:07  Test results: passed: 985; failed: 1
19:19:14  Report written to /home/jenkins/workspace/Grinder_iteration_0/aqa-tests/TKG/output_17108899086160/jdk_util_0/report/html/report.html
19:19:14  Results written to /home/jenkins/workspace/Grinder_iteration_0/aqa-tests/TKG/output_17108899086160/jdk_util_0/work
19:19:14  Error: Some tests failed or other problems occurred.
19:19:14  -----------------------------------
19:19:14  jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/38/

**Comment by JasonFengJ9** [comment]
As per the test history - https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_s390x_linux_Nightly/, 1/10 past OpenJ9 builds failed.

[RI JDK22 grinder](https://openj9-jenkins.osuosl.org/job/Grinder/3581/console) - 11/20 failed
```
10:07:54  openjdk version "22.0.1" 2024-04-16
10:07:54  OpenJDK Runtime Environment Temurin-22.0.1.1+1 (build 22.0.1+1)
10:07:54  OpenJDK 64-Bit Server VM Temurin-22.0.1.1+1 (build 22.0.1+1, mixed mode, sharing)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_Release_testList_0/10/
jdk_util_1
java/util/zip/ZipFile/ZipSourceCache.java
```
05:51:24  org.opentest4j.AssertionFailedError: expected: <7> but was: <6>
05:51:24  	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
05:51:24  	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
05:51:24  	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
05:51:24  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
05:51:24  	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
05:51:24  	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
05:51:24  	at ZipSourceCache.testKeySourceMapping(ZipSourceCache.java:102)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_Nightly_testList_0/236
