### ISSUE TITLE
`awk` doesn't exist on Windows

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18998]
https://github.com/eclipse-openj9/openj9/pull/18855 is calling `awk`, but it doesn't exist on Windows and stops functionality tests from building.

@singh264 @TobiAjila 

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_OpenJDK11_testList_0/85
```
04:01:05  BUILD FAILED
04:01:05  F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.functional_x86-64_windows_OpenJDK11_testList_0\aqa-tests\TKG\scripts\build_test.xml:95: The following error occurred while executing this line:
04:01:05  F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.functional_x86-64_windows_OpenJDK11_testList_0\aqa-tests\functional\JLM_Tests\build.xml:162: The following error occurred while executing this line:
04:01:05  F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.functional_x86-64_windows_OpenJDK11_testList_0\aqa-tests\functional\JLM_Tests\build.xml:54: Execute failed: java.io.IOException: Cannot run program "awk" (in directory "F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.functional_x86-64_windows_OpenJDK11_testList_0\aqa-tests\functional\JLM_Tests"): CreateProcess error=2, The system cannot find the file specified
04:01:05  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
04:01:05  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
04:01:05  	at java.base/java.lang.Runtime.exec(Runtime.java:592)
04:01:05  	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
04:01:05  	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
04:01:05  	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
04:01:05  	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
04:01:05  	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
04:01:05  	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
04:01:05  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
04:01:05  	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
04:01:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
04:01:05  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04:01:05  	at org.apache.tools.ant.Task.perform(Task.java:350)
04:01:05  	at java.base/java.util.Vector.forEach(Vector.java:1394)
04:01:05  	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
04:01:05  	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
04:01:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:01:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:01:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
04:01:05  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04:01:05  	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
04:01:05  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
04:01:05  	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
04:01:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
04:01:05  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04:01:05  	at org.apache.tools.ant.Task.perform(Task.java:350)
04:01:05  	at org.apache.tools.ant.Target.execute(Target.java:448)
04:01:05  	at org.apache.tools.ant.Target.performTasks(Target.java:469)
04:01:05  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
04:01:05  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
04:01:05  	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
04:01:05  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
04:01:05  	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
04:01:05  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
04:01:05  	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
04:01:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
04:01:05  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04:01:05  	at org.apache.tools.ant.Task.perform(Task.java:350)
04:01:05  	at java.base/java.util.Vector.forEach(Vector.java:1394)
04:01:05  	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
04:01:05  	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
04:01:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:01:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:01:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
04:01:05  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04:01:05  	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
04:01:05  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
04:01:05  	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
04:01:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
04:01:05  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04:01:05  	at org.apache.tools.ant.Task.perform(Task.java:350)
04:01:05  	at org.apache.tools.ant.Target.execute(Target.java:448)
04:01:05  	at org.apache.tools.ant.Target.performTasks(Target.java:469)
04:01:05  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
04:01:05  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
04:01:05  	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
04:01:05  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
04:01:05  	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:306)
04:01:05  	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:225)
04:01:05  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
04:01:05  	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
04:01:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:01:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
04:01:05  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
04:01:05  	at org.apache.tools.ant.Task.perform(Task.java:350)
04:01:05  	at org.apache.tools.ant.Target.execute(Target.java:448)
04:01:05  	at org.apache.tools.ant.Target.performTasks(Target.java:469)
04:01:05  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
04:01:05  	at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
04:01:05  	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
04:01:05  	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
04:01:05  	at org.apache.tools.ant.Main.runBuild(Main.java:849)
04:01:05  	at org.apache.tools.ant.Main.startAnt(Main.java:228)
04:01:05  	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
04:01:05  	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
04:01:05  Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
04:01:05  	at java.base/java.lang.ProcessImpl.create(Native Method)
04:01:05  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:492)
04:01:05  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:153)
04:01:05  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
04:01:05  	... 81 more
```

**Comment by keithc-ca** [comment]
Why is `awk` not present on test systems? It is used by the build process.

**Comment by singh264** [comment]
> Why is awk not present on test systems? It is used by the build process.

It seems like awk is installed on the windows machines but it is not accessible from the system path.

**Comment by AdamBrousseau** [comment]
`/usr/bin/awk` is there on all the windows machines. I think this is cygwin awk. We've had weird ant windows cygwin path issues before. In this scenario, I believe Jenkins is running pipeline step `sh`, calling ant, which is using `exec` task to call awk. I think the question is what PATH is ant picking up when it is looking for awk.

**Comment by keithc-ca** [comment]
We no longer need `awk`.
