### ISSUE TITLE
gccheck / DDR failures on OMR acceptance

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19021]
https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/653/
Failing on all Linux platforms.

Changes from the Friday night builds indicate the cause is [DDR: support DWARF version 5](https://github.com/eclipse/omr/pull/7272)
https://github.com/eclipse-openj9/openj9/compare/49dff119d36...6bdd7e4b085
https://github.com/eclipse-openj9/openj9-omr/compare/b399f9e8c0f...1f5293c169
@keithc-ca this blocks further OMR acceptance

```
22:15:17  Testing: Run gccheck
22:15:17  Test start time: 2024/02/24 22:15:16 Eastern Standard Time
22:15:17  Running command: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_aarch64_linux_OMR_testList_0/jdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
22:15:17  Time spent starting: 1 milliseconds
22:15:20  Time spent executing: 3399 milliseconds
22:15:20  Test result: FAILED
22:15:20  Output from test:
22:15:20   [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
22:15:20   [OUT] Loading image from DTFJ...
22:15:20   [OUT] 
22:15:20   [OUT] Warning: dump file was produced by a different, possibly incompatible, VM.
22:15:20   [OUT]   core file: (unknown)
22:15:20   [OUT]   this VM:   Eclipse OpenJ9 VM
22:15:20   [OUT] 
22:15:20   [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
22:15:20   [OUT] Available contexts (* = currently selected context) : 
22:15:20   [OUT] 
22:15:20   [OUT] Source : file:///home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_aarch64_linux_OMR_testList_0/aqa-tests/TKG/output_17088308081628/cmdLineTester_GCCheck_0/j9core.dmp
22:15:20   [OUT] 	*0 : PID: 1088035 : JRE 1.8.0 Linux aarch64-64 (build 1.8.0_412-internal-_2024_02_25_00_07-b00) OpenJDK Runtime Environment
22:15:20   [OUT] 
22:15:20   [OUT] > Starting GC Check
22:15:20   [OUT] Checking HEAP...  <gc check (1): from debugger: HEAP: Object ffffa2ae7308: corrupt data exception>
22:15:20   [OUT]   <gc check (1): Corrupt ffffa2ae7308 header: B8051C16 00000000>
22:15:20   [OUT]   <gc check (2): from debugger: HEAP: Object ffffaeab0000: in a new segment, old or remembered bit set>
22:15:20   [OUT]   <gc check (2): Object ffffaeab0000 header: B425CA00 0000FFFF>
22:15:20   [OUT]   <gc check (2): Cannot resolve problem detected on heap, aborting check>
22:15:20   [OUT]   <gc check (2): Previous Object ffffa2ae7260 header: B42C342A 0000FFFF>
22:15:20   [OUT]   <gc check (2): Previous Object ffffa2ae7220 header: B42CCE20 0000FFFF>
22:15:20   [OUT]   <gc check (2): Previous Hole ffffa2ae7218 header: EE8434A7 00000000 B42CCE20 0000FFFF>
22:15:20   [OUT] done (329 ms).
22:15:20   [OUT] Checking CLASS HEAP...  <gc check (3): from debugger: CLASS HEAP: static slot ffff2c0cca00(ffff2c0cc938) -> ffffaeab0548: in a new segment, old or remembered bit set>
22:15:20   [OUT] Problem running command:
22:15:20   [OUT] java.lang.NullPointerException
22:15:20   [OUT] 	at com.ibm.j9ddr.vm29.pointer.PointerPointer.cast(PointerPointer.java:39)
22:15:20   [OUT] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckEngine.checkClassHeap(CheckEngine.java:829)
22:15:20   [OUT] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckClassHeap.check(CheckClassHeap.java:45)
22:15:20   [OUT] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.Check.run(Check.java:55)
22:15:20   [OUT] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckCycle.run(CheckCycle.java:474)
22:15:20   [OUT] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.GCCheckRunner.run(GCCheckRunner.java:59)
22:15:20   [OUT] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.GCCheckCommand.run(GCCheckCommand.java:46)
22:15:20   [OUT] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
22:15:20   [OUT] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
22:15:20   [OUT] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
22:15:20   [OUT] 	at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:78)
22:15:20   [OUT] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
```

**Comment by keithc-ca** [comment]
It seems some values (offsets, sizes) are being sign-extended inappropriately, for example:
```
  Type: GC_FlattenedContiguousArrayIterator
    size is -120; expected 136
    offset of _omrVM is -128; expected 128
```
Hopefully this easy to correct.
