### ISSUE TITLE
OpenJDK java/util/concurrent/ArrayBlockingQueue/WhiteBox - failed to do a "full" gc

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19047]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/18
java/util/concurrent/ArrayBlockingQueue/WhiteBox.java
```
22:37:17  test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
22:37:17  java.lang.AssertionError: failed to do a "full" gc
22:37:17  	at WhiteBox.forceFullGc(WhiteBox.java:226)
22:37:17  	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
```

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by dmitripivkine** [comment]
Test source https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/test/jdk/java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

Weak Reference has not been cleared after three System GC() calls

**Comment by dmitripivkine** [comment]
just BTW test compiles with warnings:
```
22:37:17  /home/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/ArrayBlockingQueue/WhiteBox.java:210: warning: [removal] finalize() in Object has been deprecated and marked for removal
22:37:17              new Object() { protected void finalize() { finalized.countDown(); }},
22:37:17                                            ^
22:37:17  /home/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/ArrayBlockingQueue/WhiteBox.java:218: warning: [removal] runFinalization() in System has been deprecated and marked for removal
22:37:17                      System.runFinalization(); // try to pick up stragglers
22:37:17                            ^
```
I am not sure when deprecated `runFinalization()` is going to be removed.

**Comment by pshipton** [comment]
It's a OpenJDK test, any modification to remove warning should happen at OpenJDK. It's deprecated in jdk22 but it won't be removed in jdk22 since this release is now finalized.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Nightly_testList_2/218
jdk_util_0
java/util/concurrent/ArrayBlockingQueue/WhiteBox.java
```
20:13:21  test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
20:13:21  java.lang.AssertionError: failed to do a "full" gc
20:13:21  	at WhiteBox.forceFullGc(WhiteBox.java:226)
20:13:21  	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
20:13:21  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_aarch64_mac_Nightly_testList_0/109/

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_0/669/)
```
[2025-03-12T20:32:45.324Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2025-03-12T20:32:45.324Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2025-03-12T20:57:25.219Z] TEST: java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

[2025-03-12T20:57:25.239Z] test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
[2025-03-12T20:57:25.239Z] java.lang.AssertionError: failed to do a "full" gc
[2025-03-12T20:57:25.239Z] 	at WhiteBox.forceFullGc(WhiteBox.java:226)
[2025-03-12T20:57:25.239Z] 	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
[2025-03-12T20:57:25.241Z] java/util/concurrent/ArrayBlockingQueue/WhiteBox.java
[2025-03-12T20:57:25.241Z] Total tests run: 14, Passes: 13, Failures: 1, Skips: 0

[2025-03-12T23:15:55.011Z] jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_Release_testList_0/29 - 0.51
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_1/44
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_Nightly_testList_1/85
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_1/359
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Release_testList_1/48

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_sanity.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_1/923/)
```
[2025-12-12T17:47:14.784Z] Running test jdk_concurrent_1 ...
[2025-12-12T17:47:14.784Z] ===============================================
[2025-12-12T17:47:14.784Z] jdk_concurrent_1 Start Time: Fri Dec 12 09:46:58 2025 Epoch Time (ms): 1765561618060
[2025-12-12T17:47:14.784Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2025-12-12T17:47:14.785Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2025-12-12T17:48:13.446Z] TEST: java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

[2025-12-12T17:48:13.452Z] test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
[2025-12-12T17:48:13.452Z] java.lang.AssertionError: failed to do a "full" gc
[2025-12-12T17:48:13.452Z] 	at WhiteBox.forceFullGc(WhiteBox.java:226)
[2025-12-12T17:48:13.452Z] 	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_windows_Nightly_testList_1/106/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly_testList_2/656/

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_OpenJDK11_testList_0/36/consoleFull
```
03:01:16  Running test jdk_concurrent_1 ...
03:01:16  ===============================================
03:01:16  jdk_concurrent_1 Start Time: Sat Feb 28 08:01:15 2026 Epoch Time (ms): 1772265675686
03:01:16  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
03:01:16  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

03:01:53  TEST: java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

03:01:53  test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
03:01:53  java.lang.AssertionError: failed to do a "full" gc
03:01:53  	at WhiteBox.forceFullGc(WhiteBox.java:226)
03:01:53  	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
03:01:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OpenJDK21_testList_2/74/consoleFull
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/161/consoleFull
[openjdk26_j9_sanity.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk26_j9_sanity.openjdk_ppc64le_linux_Personal_testList_2/25/consoleFull)
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_windows_OpenJDK21_testList_0/56/

**Comment by JasonFengJ9** [comment]
[openjdk26_j9_sanity.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk26_j9_sanity.openjdk_ppc64le_linux_testList_3/2/)
```
[2026-03-10T19:16:02.816Z] Running test jdk_concurrent_1 ...
[2026-03-10T19:16:02.816Z] ===============================================
[2026-03-10T19:16:02.816Z] jdk_concurrent_1 Start Time: Tue Mar 10 12:16:01 2026 Epoch Time (ms): 1773170161909
[2026-03-10T19:16:02.816Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2026-03-10T19:16:02.817Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2026-03-10T19:17:00.333Z] TEST: java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

[2026-03-10T19:17:00.345Z] [12:16:53.041] test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure [21241ms]
[2026-03-10T19:17:00.345Z] java.lang.AssertionError: failed to do a "full" gc
[2026-03-10T19:17:00.345Z] 	at WhiteBox.forceFullGc(WhiteBox.java:226)
[2026-03-10T19:17:00.345Z] 	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_sanity.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_1/985/)
```
[2026-03-14T20:30:56.102Z] Running test jdk_concurrent_1 ...
[2026-03-14T20:30:56.102Z] ===============================================
[2026-03-14T20:30:56.102Z] jdk_concurrent_1 Start Time: Sat Mar 14 13:30:55 2026 Epoch Time (ms): 1773520255603
[2026-03-14T20:30:56.102Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2026-03-14T20:30:56.102Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2026-03-14T20:31:45.905Z] TEST: java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

2026-03-14T20:31:45.906Z] test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
[2026-03-14T20:31:45.906Z] java.lang.AssertionError: failed to do a "full" gc
[2026-03-14T20:31:45.906Z] 	at WhiteBox.forceFullGc(WhiteBox.java:226)
[2026-03-14T20:31:45.906Z] 	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/59019/) - failed 1/1/5/1/6 out of 10 each, total 14/50.

**Comment by pshipton** [comment]
There were a few of these but I didn't record them all
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/169
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_OMR_testList_2/330/

**Comment by pshipton** [comment]
Exclude the test on jdk17+
https://github.com/adoptium/aqa-tests/pull/6962

**Comment by pshipton** [comment]
Also fails on jdk11
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/493/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OMR_testList_0/408/

**Comment by pshipton** [comment]
Exclude on jdk11
https://github.com/adoptium/aqa-tests/pull/6986
