### ISSUE TITLE
jdk_security3_0_FAILED sun/security/pkcs11/ec/TestCurves.java Exception: Signature did not verify

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19055]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux_testList_2/6/)(`rhel8x86-svl-rt3-1`):
```
openjdk version "1.8.0_412-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_412-beta-202402292344-b05)
Eclipse OpenJ9 VM (build master-2095c8e18, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240229_884 (JIT enabled, AOT enabled)
OpenJ9   - 2095c8e18
OMR      - 9235a2ff6
JCL      - 16aa7c249 based on jdk8u412-b05)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_extended.openjdk_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F884%2Fibm-semeru-open-jdk_x64_linux_JDK8U_2024-02-29-23-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F884%2Fibm-semeru-open-testimage_x64_linux_JDK8U_2024-02-29-23-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=185&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-01T00:30:07.727Z] variation: Mode150
[2024-03-01T00:30:07.727Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-01T00:33:57.924Z] TEST: sun/security/pkcs11/ec/TestCurves.java

[2024-03-01T00:33:57.925Z] STDERR:
[2024-03-01T00:33:57.925Z] java.lang.Exception: Signature did not verify
[2024-03-01T00:33:57.925Z] 	at TestCurves.testSigning(TestCurves.java:139)
[2024-03-01T00:33:57.925Z] 	at TestCurves.main(TestCurves.java:85)
[2024-03-01T00:33:57.925Z] 	at PKCS11Test.premain(PKCS11Test.java:125)
[2024-03-01T00:33:57.925Z] 	at PKCS11Test.testNSS(PKCS11Test.java:487)
[2024-03-01T00:33:57.925Z] 	at PKCS11Test.main(PKCS11Test.java:156)
[2024-03-01T00:33:57.925Z] 	at TestCurves.main(TestCurves.java:50)
[2024-03-01T00:33:57.925Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-03-01T00:33:57.925Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-03-01T00:33:57.925Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-03-01T00:33:57.925Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-03-01T00:33:57.925Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-03-01T00:33:57.925Z] 	at java.lang.Thread.run(Thread.java:826)
[2024-03-01T00:33:57.925Z] 
[2024-03-01T00:33:57.925Z] JavaTest Message: Test threw exception: java.lang.Exception: Signature did not verify

[2024-03-01T00:33:57.925Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Signature did not verify
[2024-03-01T00:33:57.925Z] --------------------------------------------------
[2024-03-01T00:45:53.135Z] Test results: passed: 610; failed: 1
[2024-03-01T00:46:00.121Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux_testList_2/aqa-tests/TKG/output_17092529332598/jdk_security3_0/report/html/report.html
[2024-03-01T00:46:00.121Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_linux_testList_2/aqa-tests/TKG/output_17092529332598/jdk_security3_0/work
[2024-03-01T00:46:00.121Z] Error: Some tests failed or other problems occurred.
[2024-03-01T00:46:00.121Z] -----------------------------------
[2024-03-01T00:46:00.121Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38279/)

**Comment by pshipton** [comment]
The failures are all on rhel8, rhel9. It passed on cent9. 

@jasonkatonica another failure on rhel8+.

**Comment by pshipton** [comment]
Seems there are a number of jdk_security3 pkcs11 tests that fail on rhel8+. These are from a zlinux jdk11 build on rhel9.

sun/security/pkcs11/KeyStore/ClientAuth.java.ClientAuth
sun/security/pkcs11/KeyStore/SecretKeysBasic.java.SecretKeysBasic
sun/security/pkcs11/Provider/Login.java.Login
sun/security/pkcs11/Secmod/AddPrivateKey.java.AddPrivateKey
sun/security/pkcs11/Secmod/GetPrivateKey.java.GetPrivateKey
sun/security/pkcs11/Secmod/JksSetPrivateKey.java.JksSetPrivateKey
sun/security/pkcs11/Secmod/LoadKeystore.java.LoadKeystore
sun/security/pkcs11/Secmod/TrustAnchors.java.TrustAnchors
sun/security/pkcs11/ec/TestECDH.java.TestECDH
sun/security/pkcs11/ec/TestECDSA.java.TestECDSA

**Comment by JasonFengJ9** [comment]
[JDK17 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_linux_testList_0/10/)(`rhel8x86-svl-rt2-1`)
```
[2024-03-13T23:59:27.025Z] variation: Mode650
[2024-03-13T23:59:27.025Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-14T00:09:39.815Z] TEST: sun/security/pkcs11/ec/TestCurves.java

[2024-03-14T00:09:39.816Z] STDERR:
[2024-03-14T00:09:39.816Z] java.lang.Exception: Signature did not verify
[2024-03-14T00:09:39.816Z] 	at TestCurves.testSigning(TestCurves.java:121)
[2024-03-14T00:09:39.816Z] 	at TestCurves.main(TestCurves.java:83)
[2024-03-14T00:09:39.816Z] 	at PKCS11Test.premain(PKCS11Test.java:805)
[2024-03-14T00:09:39.816Z] 	at PKCS11Test.testNSS(PKCS11Test.java:481)
[2024-03-14T00:09:39.816Z] 	at PKCS11Test.main(PKCS11Test.java:181)
[2024-03-14T00:09:39.816Z] 	at TestCurves.main(TestCurves.java:50)

[2024-03-14T00:09:39.817Z] TEST: sun/security/pkcs11/ec/TestECDSA.java
[2024-03-14T00:09:39.817Z] STDERR:
[2024-03-14T00:09:39.817Z] java.lang.Exception: Sign/verify 3 failed
[2024-03-14T00:09:39.817Z] 	at TestECDSA.testSigning(TestECDSA.java:250)
[2024-03-14T00:09:39.817Z] 	at TestECDSA.test(TestECDSA.java:197)
[2024-03-14T00:09:39.817Z] 	at TestECDSA.main(TestECDSA.java:168)
[2024-03-14T00:09:39.817Z] 	at PKCS11Test.premain(PKCS11Test.java:805)
[2024-03-14T00:09:39.817Z] 	at PKCS11Test.testNSS(PKCS11Test.java:481)
[2024-03-14T00:09:39.817Z] 	at PKCS11Test.main(PKCS11Test.java:181)
[2024-03-14T00:09:39.817Z] 	at TestECDSA.main(TestECDSA.java:119)

[2024-03-14T00:09:39.818Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Sign/verify 3 failed
[2024-03-14T00:09:39.818Z] --------------------------------------------------
[2024-03-14T00:35:03.068Z] Test results: passed: 836; failed: 2
[2024-03-14T00:35:03.482Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_1710374185226/jdk_security3_1/report/html/report.html
[2024-03-14T00:35:03.482Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_1710374185226/jdk_security3_1/work
[2024-03-14T00:35:03.482Z] Error: Some tests failed or other problems occurred.
[2024-03-14T00:35:03.482Z] -----------------------------------
[2024-03-14T00:35:03.482Z] jdk_security3_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK17 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/170/)(`cent8le-rtp-rt4-1`)
```
openjdk version "17.0.11" 2024-04-16
IBM Semeru Runtime Open Edition 17.0.11.0-m1 (build 17.0.11+6)
Eclipse OpenJ9 VM 17.0.11.0-m1 (build v0.44.0-release-747f86c91, JRE 17 Linux ppc64le-64-Bit Compressed References 20240416_684 (JIT enabled, AOT enabled)
OpenJ9   - 747f86c91
OMR      - 254af5a04
JCL      - c86cd885d3f based on jdk-17.0.11+6)

[2024-03-18T20:13:14.388Z] variation: Mode150
[2024-03-18T20:13:14.388Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-18T20:30:07.726Z] TEST: sun/security/pkcs11/ec/TestCurves.java

[2024-03-18T20:30:07.727Z] STDERR:
[2024-03-18T20:30:07.727Z] java.lang.Exception: Signature did not verify
[2024-03-18T20:30:07.727Z] 	at TestCurves.testSigning(TestCurves.java:121)
[2024-03-18T20:30:07.727Z] 	at TestCurves.main(TestCurves.java:85)
[2024-03-18T20:30:07.727Z] 	at PKCS11Test.premain(PKCS11Test.java:805)
[2024-03-18T20:30:07.727Z] 	at PKCS11Test.testNSS(PKCS11Test.java:481)
[2024-03-18T20:30:07.727Z] 	at PKCS11Test.main(PKCS11Test.java:181)
[2024-03-18T20:30:07.727Z] 	at TestCurves.main(TestCurves.java:50)

[2024-03-18T20:30:07.727Z] TEST: sun/security/pkcs11/ec/TestECDSA.java
[2024-03-18T20:30:07.728Z] STDERR:
[2024-03-18T20:30:07.728Z] java.lang.Exception: Sign/verify 3 failed
[2024-03-18T20:30:07.728Z] 	at TestECDSA.testSigning(TestECDSA.java:250)
[2024-03-18T20:30:07.728Z] 	at TestECDSA.test(TestECDSA.java:197)
[2024-03-18T20:30:07.728Z] 	at TestECDSA.main(TestECDSA.java:168)
[2024-03-18T20:30:07.728Z] 	at PKCS11Test.premain(PKCS11Test.java:805)
[2024-03-18T20:30:07.728Z] 	at PKCS11Test.testNSS(PKCS11Test.java:481)
[2024-03-18T20:30:07.728Z] 	at PKCS11Test.main(PKCS11Test.java:181)
[2024-03-18T20:30:07.728Z] 	at TestECDSA.main(TestECDSA.java:119)

[2024-03-18T21:12:19.262Z] Test results: passed: 835; failed: 2
[2024-03-18T21:12:29.516Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_17107901888094/jdk_security3_0/report/html/report.html
[2024-03-18T21:12:29.516Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_17107901888094/jdk_security3_0/work
[2024-03-18T21:12:29.516Z] Error: Some tests failed or other problems occurred.
[2024-03-18T21:12:29.516Z] -----------------------------------
[2024-03-18T21:12:29.516Z] jdk_security3_0_FAILED
```

**Comment by jasonkatonica** [comment]
I was able to recreate this issue using the following simplified test:
```
import java.security.Security;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.NamedParameterSpec;

public class ECDSASignTest {

    static final String PROVIDERNAME = "SunPKCS11-NSS-FIPS";
    //static final String CURVENAME = "secp256r1";
    //static final String CURVENAME = "secp384r1";
    static final String CURVENAME = "secp521r1";

    //static final String SIGNATURE = "SHA1withECDSA";
    //static final String SIGNATURE = "SHA224withECDSA";
    //static final String SIGNATURE = "SHA256withECDSA";
    static final String SIGNATURE = "SHA384withECDSA";
    //static final String SIGNATURE = "SHA512withECDSA";

    static final int ITERATIONS = 1000;

    public static void main(String[] args) throws Exception {
        System.out.println("Running Signature <" + SIGNATURE + "> with curve <" + CURVENAME + ">: ");

        for (int x = 0; x<ITERATIONS; x++) {

            // Generate key pair.
            KeyPairGenerator keyGen = KeyPairGenerator.getInstance("EC", PROVIDERNAME);
            ECGenParameterSpec ecSpec = new ECGenParameterSpec(CURVENAME);
            keyGen.initialize(ecSpec);
            KeyPair keyPair = keyGen.generateKeyPair();
    
            // Sign
            Signature ecdsaSign = Signature.getInstance(SIGNATURE, PROVIDERNAME);
            ecdsaSign.initSign((PrivateKey) keyPair.getPrivate());
            byte[] dataToSign = "somethingtosign".getBytes();
            ecdsaSign.update(dataToSign);
            byte[] signature = ecdsaSign.sign();
    
            // Verify
            Signature ecdsaVerify = Signature.getInstance(SIGNATURE,PROVIDERNAME);
            ecdsaVerify.initVerify((PublicKey) keyPair.getPublic());
            ecdsaVerify.update(dataToSign);
            boolean isVerified = ecdsaVerify.verify(signature);
            if (isVerified == false) {
                throw new Exception("Signature <" + SIGNATURE + "> failed with curve <" + CURVENAME + ">");
            }
            System.out.print(".");
        }
        System.out.println("");
        System.out.println("Test with signature <" + SIGNATURE + "> passed with curve <" + CURVENAME + ">");
    }
}
```
This test seems to fail whenever using the `secp521r1` curve at random, unusually within the first 10 iterations. Other curve names run for the full iteration count of 1000 times, so these other curves besides `secp521r1` do not appear to be a problem.

I have tried this on latest release, and back to Java version `17.0.6+10`, and the behavior remains the same with random failures occurring whenever using the `secp521r1` curve:
```
# java -version
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Linux amd64-64-Bit Compressed References 20230117_397 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```

**Comment by pshipton** [comment]
Not a regression so moving out of the 0.44 milestone plan.
