### ISSUE TITLE
Skynet timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19067]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/73
jdk_lang_1
java/lang/Thread/virtual/stress/Skynet.java#default

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/73/openjdk_test_output.tar.gz
```
12:10:08  Virtual machine: 19661278 JVM information:
12:10:08  JRE 21 AIX ppc64-64-Bit 20240302_93 (JIT enabled, AOT enabled)
12:10:08  OpenJ9   - 5726a9c575d
12:10:08  OMR      - 8bea58e9526
12:10:08  JCL      - e84e685d122 based on jdk-21.0.3+5
12:10:08  
12:10:08  "main" prio=5 Id=2 WAITING
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.waitImpl(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:255)
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:221)
12:10:08  	at java.base@21.0.3-internal/java.lang.Thread.join(Thread.java:2102)
12:10:08  	at java.base@21.0.3-internal/java.lang.Thread.join(Thread.java:2178)
12:10:08  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:85)
12:10:08  
12:10:08  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
12:10:08  
12:10:08  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
12:10:08  
12:10:08  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
12:10:08  
12:10:08  "JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
12:10:08  
12:10:08  "JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE
12:10:08  
12:10:08  "JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE
12:10:08  
12:10:08  "JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE
12:10:08  
12:10:08  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE
12:10:08  
12:10:08  "JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING
12:10:08  
12:10:08  "IProfiler" prio=5 Id=13 RUNNABLE
12:10:08  
12:10:08  "Common-Cleaner" prio=8 Id=3 TIMED_WAITING
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.waitImpl(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:255)
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:221)
12:10:08  	at java.base@21.0.3-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
12:10:08  	at java.base@21.0.3-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
12:10:08  	at java.base@21.0.3-internal/java.lang.Thread.run(Thread.java:1595)
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
12:10:08  
12:10:08  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=15 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=16 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=17 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=18 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=19 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=20 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=21 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=22 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=23 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=24 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=25 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=26 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=27 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=28 RUNNABLE
12:10:08  
12:10:08  "GC Worker" prio=5 Id=29 RUNNABLE
12:10:08  
12:10:08  "Finalizer thread" prio=5 Id=32 RUNNABLE
12:10:08  
12:10:08  "Attach API wait loop" prio=10 Id=33 RUNNABLE
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
12:10:08  
12:10:08  "MainThread" prio=5 Id=34 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:458)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:316)
12:10:08  	at app//Skynet$Channel.receive(Skynet.java:124)
12:10:08  	at app//Skynet.skynet(Skynet.java:74)
12:10:08  	at app//Skynet.main(Skynet.java:64)
12:10:08  	at java.base@21.0.3-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
12:10:08  	at java.base@21.0.3-internal/java.lang.reflect.Method.invoke(Method.java:586)
12:10:08  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
12:10:08  	at java.base@21.0.3-internal/java.lang.Thread.run(Thread.java:1595)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-1" prio=5 Id=36 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-6" prio=5 Id=53 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-5" prio=5 Id=51 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-10" prio=5 Id=72 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-12" prio=5 Id=90 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-11" prio=5 Id=82 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-15" prio=5 Id=97 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "ForkJoinPool-1-worker-16" prio=5 Id=100 WAITING
12:10:08  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1893)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
12:10:08  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
12:10:08  
12:10:08  "file lock watchdog" prio=10 Id=946588 TIMED_WAITING
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.waitImpl(Native Method)
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:255)
12:10:08  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:221)
12:10:08  	at java.base@21.0.3-internal/java.util.TimerThread.mainLoop(Timer.java:570)
12:10:08  	at java.base@21.0.3-internal/java.util.TimerThread.run(Timer.java:523)
12:10:08  
12:10:08  "Attachment portNumber: 44085" prio=10 Id=946590 RUNNABLE
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:249)
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:185)
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
12:10:08  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
12:10:08  
12:10:08  
12:10:08  --- Timeout information end.
```

**Comment by tajila** [comment]
30x Grinder https://openj9-jenkins.osuosl.org/job/Grinder/3365/

**Comment by tajila** [comment]
30x -Xint https://openj9-jenkins.osuosl.org/job/Grinder/3366/

**Comment by tajila** [comment]
All the relevant threads are parked so Im wondering if this issue is like https://github.com/eclipse-openj9/openj9/issues/14752

**Comment by tajila** [comment]
@fengxue-IS @babsingh ^^^

**Comment by fengxue-IS** [comment]
first grinder seem didn't reproduced the error, -Xint 7/30 so far no reproduction. will wait until -Xint grinder finishes to see if this is reproduced

**Comment by tajila** [comment]
10x runs -Xint, https://openj9-jenkins.osuosl.org/job/Grinder/3420/

**Comment by tajila** [comment]
50x -Xjit https://openj9-jenkins.osuosl.org/job/Grinder/3430/
50 -Xint https://openj9-jenkins.osuosl.org/job/Grinder/3431/

**Comment by pshipton** [comment]
Just the original one, otherwise it would be reported in this issue.

**Comment by JasonFengJ9** [comment]
[JDK21 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_testList_1/147/)(`paix823`)
```
openjdk version "21.0.3" 2024-04-16 LTS
IBM Semeru Runtime Open Edition 21.0.3.0-m2 (build 21.0.3+7-LTS)
Eclipse OpenJ9 VM 21.0.3.0-m2 (build v0.44.0-release-8b079b5c1, JRE 21 AIX ppc64-64-Bit Compressed References 20240416_149 (JIT enabled, AOT enabled)
OpenJ9   - 8b079b5c1
OMR      - 254af5a04
JCL      - 5b5adb35189 based on jdk-21.0.3+7)

[2024-04-12T19:00:05.277Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2024-04-12T19:00:05.277Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Xverbosegclog 

[2024-04-12T20:25:21.673Z] TEST: java/lang/Thread/virtual/stress/Skynet.java#default

[2024-04-12T20:25:21.781Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_testList_1/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 2400000ms, elapsed time including timeout handling was 2439849ms).
[2024-04-12T20:25:21.781Z] --------------------------------------------------
[2024-04-12T20:34:49.327Z] Test results: passed: 925; error: 1
[2024-04-12T20:35:47.696Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1712948403191/jdk_lang_1/report/html/report.html
[2024-04-12T20:35:47.696Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_1712948403191/jdk_lang_1/work
[2024-04-12T20:35:47.696Z] Error: Some tests failed or other problems occurred.
[2024-04-12T20:35:47.696Z] -----------------------------------
[2024-04-12T20:35:47.696Z] jdk_lang_1_FAILED
```
50x grinder - https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39856/

**Comment by tajila** [comment]
@fengxue-IS Please take a look

**Comment by fengxue-IS** [comment]
Looking at the core file generated, I didn't see any incorrect vthread/carrier thread so this could just be a very slow run, will have to re-run the testing with more logging to identify the cause of such performance issue.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_1/207
