### ISSUE TITLE
cmdLineTester_criu_keepCheckpoint_0_FAILED Error (criu/proc_parse.c:474): Can't open map_files: Permission denied

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19073]
From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_1/602/)(`sles12x86-rtp-rt5-1`):
```
java version "17.0.11-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 17.0.11+5-202403021534 (build 17.0.11-beta+5-202403021534)
Eclipse OpenJ9 VM 17.0.11+5-202403021534 (build master-5726a9c57, JRE 17 Linux amd64-64-Bit Compressed References 20240302_621 (JIT enabled, AOT enabled)
OpenJ9   - 5726a9c57
OMR      - 53e909c41
JCL      - 8507349ca3 based on jdk-17.0.11+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=cmdLineTester_criu_keepCheckpoint_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.functional_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9-IBM%2F621%2Fibm-semeru-certified-jdk_x64_linux_JDK17U_2024-03-02-15-31.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9-IBM%2F621%2Fibm-semeru-certified-testimage_x64_linux_JDK17U_2024-03-02-15-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28centos6%7C%7Crhel6%29&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=638&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-02T16:37:17.926Z] variation: -Xjit
[2024-03-02T16:37:17.926Z] JVM_OPTIONS:  -Xjit 

[2024-03-02T16:37:18.385Z] TESTING:
[2024-03-02T16:37:18.944Z] *** Starting test suite: J9 Criu Command-Line Option Tests ***
[2024-03-02T16:37:18.944Z] Testing: Create Criu Checkpoint Image without Restore
[2024-03-02T16:37:19.370Z] Test start time: 2024/03/02 08:37:18 Pacific Standard Time
[2024-03-02T16:37:19.370Z] Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_1/jdkbinary/j2sdk-image/bin/java " -Xjit " org.openj9.criu.CRIUSimpleTest 1 1 true true
[2024-03-02T16:37:19.370Z] Time spent starting: 90 milliseconds
[2024-03-02T16:37:21.557Z] Time spent executing: 2138 milliseconds
[2024-03-02T16:37:21.557Z] Test result: FAILED
[2024-03-02T16:37:21.557Z] Output from test:

[2024-03-02T16:37:21.561Z]  [OUT] (00.062494) Error (criu/proc_parse.c:474): Can't open map_files: Permission denied
[2024-03-02T16:37:21.561Z]  [OUT] (00.062514) Error (criu/proc_parse.c:694): Can't open 15971's mapfile link 7f79ec309000: Permission denied
[2024-03-02T16:37:21.561Z]  [OUT] (00.062534) Error (criu/cr-dump.c:1558): Collect mappings (pid: 15971) failed with -1
[2024-03-02T16:37:21.561Z]  [OUT] (00.062739) net: Unlock network
[2024-03-02T16:37:21.561Z]  [OUT] (00.062759) Unfreezing tasks into 1
[2024-03-02T16:37:21.561Z]  [OUT] (00.062769) 	Unseizing 15971 into 1
[2024-03-02T16:37:21.561Z]  [OUT] (00.063324) Error (criu/cr-dump.c:2093): Dumping FAILED.
[2024-03-02T16:37:21.561Z]  [OUT] -------------- End of checkpoint criu.log -------------
[2024-03-02T16:37:21.561Z]  [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
[2024-03-02T16:37:21.561Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:536)
[2024-03-02T16:37:21.561Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:92)
[2024-03-02T16:37:21.561Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:80)
[2024-03-02T16:37:21.561Z]  [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:76)
[2024-03-02T16:37:21.561Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.checkpoints(CRIUSimpleTest.java:59)
[2024-03-02T16:37:21.561Z]  [OUT] 	at org.openj9.criu.CRIUSimpleTest.main(CRIUSimpleTest.java:38)
[2024-03-02T16:37:21.561Z]  [OUT] Caused by: openj9.internal.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
[2024-03-02T16:37:21.561Z]  [OUT] 	at java.base/openj9.internal.criu.InternalCRIUSupport.checkpointJVMImpl(Native Method)
[2024-03-02T16:37:21.561Z]  [OUT] 	at java.base/openj9.internal.criu.InternalCRIUSupport.checkpointJVM(InternalCRIUSupport.java:961)
[2024-03-02T16:37:21.561Z]  [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:530)
[2024-03-02T16:37:21.561Z]  [OUT] 	... 5 more
[2024-03-02T16:37:21.561Z]  [OUT] finished script
[2024-03-02T16:37:21.561Z]  [ERR] cat: criuOutput: No such file or directory
[2024-03-02T16:37:21.561Z] >> Success condition was not found: [Output match: Killed]
[2024-03-02T16:37:21.561Z] >> Required condition was found: [Output match: Pre-checkpoint]
[2024-03-02T16:37:21.561Z] >> Failure condition was not found: [Output match: Post-checkpoint]
[2024-03-02T16:37:21.561Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2024-03-02T16:37:21.561Z] >> Failure condition was not found: [Output match: Removed testOutput file]
[2024-03-02T16:37:21.561Z] >> Failure condition was found: [Output match: Operation not permitted]
[2024-03-02T16:37:21.561Z] >> Failure condition was not found: [Output match: ERR]
[2024-03-02T16:37:21.561Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
[2024-03-02T16:37:21.561Z] >> Failure condition was not found: [Output match: User requested Java dump using]
[2024-03-02T16:37:21.561Z] 
[2024-03-02T16:37:21.561Z] 
[2024-03-02T16:37:21.561Z] ---TEST RESULTS---
[2024-03-02T16:37:21.561Z] Number of PASSED tests: 0 out of 1
[2024-03-02T16:37:21.561Z] Number of FAILED tests: 1 out of 1
[2024-03-02T16:37:21.561Z] 
[2024-03-02T16:37:21.561Z] ---SUMMARY OF FAILED TESTS---
[2024-03-02T16:37:21.561Z] Create Criu Checkpoint Image without Restore
[2024-03-02T16:37:21.561Z] -----------------------------
[2024-03-02T16:37:21.561Z] 
[2024-03-02T16:37:21.561Z] -----------------------------------
[2024-03-02T16:37:21.561Z] cmdLineTester_criu_keepCheckpoint_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38320/)

**Comment by pshipton** [comment]
Seems like a machine problem.

**Comment by cjjdespres** [comment]
Also seen in https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_s390x_linux_jit_Personal_testList_1/945/, on `sles15s390x-svl-rt10-1`, if this is a machine issue.
