### ISSUE TITLE
JDK21 windows-x64 build target support_images_jre__jlink_jre_exec failure java.nio.charset.CoderMalfunctionError: java.lang.NullPointerException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19077]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-windows-x64-openj9-IBM/106/console)(`win2016x64comprt3`):

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
12:40:33  Creating support/demos/image/jfc/TransparentRuler/TransparentRuler.jar
12:48:45  
12:48:45  ERROR: Build failed for targets 'product-images legacy-jre-image test-image debug-image' in configuration 'windows-x86_64-server-release' (exit code 2) 
12:48:46  assertion "bc_ctl.arg_max >= LINE_MAX" failed: file "/usr/src/findutils-4.6.0-1.x86_64/src/findutils-4.6.0/xargs/xargs.c", line 500, function: main
12:48:47  
12:48:47  === Output from failing command(s) repeated here ===
12:48:47  * For target support_images_jre__jlink_jre_exec:
12:48:47  WARNING: Using incubator modules: jdk.incubator.vector
12:48:47  Error: java.lang.NullPointerException
12:48:47  java.nio.charset.CoderMalfunctionError: java.lang.NullPointerException
12:48:47  	at java.base/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:588)
12:48:47  	at java.base/sun.nio.cs.StreamEncoder.flushLeftoverChar(StreamEncoder.java:330)
12:48:47  	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:417)
12:48:47  	at java.base/sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:237)
12:48:47  	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:222)
12:48:47  	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:266)
12:48:47  	at java.base/java.io.BufferedWriter.implClose(BufferedWriter.java:398)
12:48:47  	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:380)
12:48:47  	at jdk.jlink/jdk.tools.jlink.builder.DefaultImageBuilder.writeSymLinkEntry(DefaultImageBuilder.java:480)
12:48:47  	at jdk.jlink/jdk.tools.jlink.builder.DefaultImageBuilder.accept(DefaultImageBuilder.java:440)
12:48:47  	at jdk.jlink/jdk.tools.jlink.builder.DefaultImageBuilder.lambda$storeFiles$1(DefaultImageBuilder.java:193)
12:48:47  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
12:48:47     ... (rest of output omitted)
12:48:47  
12:48:47  * All command lines available in /cygdrive/c/workspace/openjdk-build/workspace/build/src/build/windows-x86_64-server-release/make-support/failure-logs.
```

**Comment by pshipton** [comment]
machine problem related to the assersion in xargs.c?
