### ISSUE TITLE
testJITServer testServerGoesDown The process is still alive after waiting

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19084]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/2 - [ub20-390-1](https://openj9-jenkins.osuosl.org/computer/ub20-390-1)
testJITServer_0
```
19:24:49  [JITServerTest] [INFO] running testServer: INFO and above level logging enabled
19:24:49  [JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=57755, set JITServerTest_SERVER_PORT in your env to override.
19:24:50  [JITServerTest] [INFO] Starting server with command line:
19:24:50  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=57755
19:24:50  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:24:50  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServer.server.out
19:24:58  [JITServerTest] [INFO] Starting client with command line:
19:24:58  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/java -XX:JITServerPort=57755 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../TKG/output_1709502051281/testJITServer_0/client /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_390-64,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all
19:24:58  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:24:58  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServer.client.out
19:24:58  [JITServerTest] [INFO] Waiting for 45000 millis.
19:26:03  [JITServerTest] [INFO] Stopping client...
19:26:14  [JITServerTest] [INFO] Stopping server...
19:26:14  [JITServerTest] [INFO] running testServerSCC: INFO and above level logging enabled
19:26:14  [JITServerTest] [INFO] running testServerComesUpAfterClient: INFO and above level logging enabled
19:26:14  [JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=47138, set JITServerTest_SERVER_PORT in your env to override.
19:26:14  [JITServerTest] [INFO] Starting client with command line:
19:26:14  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/java -XX:JITServerPort=47138 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../TKG/output_1709502051281/testJITServer_0/client /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_390-64,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all
19:26:14  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:26:14  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerComesUpAfterClient.client.out
19:26:15  [JITServerTest] [INFO] Waiting for 45000 millis.
19:27:08  [JITServerTest] [INFO] Starting server with command line:
19:27:08  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=47138
19:27:08  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:27:08  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerComesUpAfterClient.server.out
19:27:09  [JITServerTest] [INFO] Waiting for 45000 millis.
19:28:01  [JITServerTest] [INFO] Stopping client...
19:28:07  [JITServerTest] [INFO] Stopping server...
19:28:07  [JITServerTest] [INFO] running testServerComesUpAfterClientAndGoesDownAgain: INFO and above level logging enabled
19:28:07  [JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=38518, set JITServerTest_SERVER_PORT in your env to override.
19:28:07  [JITServerTest] [INFO] Starting client with command line:
19:28:07  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/java -XX:JITServerPort=38518 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../TKG/output_1709502051281/testJITServer_0/client /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_390-64,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all
19:28:07  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:28:07  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerComesUpAfterClientAndGoesDownAgain.client.out
19:28:09  [JITServerTest] [INFO] Waiting for 45000 millis.
19:29:07  [JITServerTest] [INFO] Starting server with command line:
19:29:07  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=38518
19:29:07  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:29:07  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerComesUpAfterClientAndGoesDownAgain.server.out
19:29:08  [JITServerTest] [INFO] Waiting for 45000 millis.
19:29:52  [JITServerTest] [INFO] Stopping server...
19:29:52  [JITServerTest] [INFO] Waiting for 45000 millis.
19:30:38  [JITServerTest] [INFO] Stopping client...
19:30:38  [JITServerTest] [INFO] running testServerGoesDown: INFO and above level logging enabled
19:30:38  [JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=48819, set JITServerTest_SERVER_PORT in your env to override.
19:30:38  [JITServerTest] [INFO] Starting server with command line:
19:30:38  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=48819
19:30:38  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:30:38  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerGoesDown.server.out
19:30:42  [JITServerTest] [INFO] Starting client with command line:
19:30:42  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/java -XX:JITServerPort=48819 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../TKG/output_1709502051281/testJITServer_0/client /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_390-64,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all
19:30:42  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:30:42  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerGoesDown.client.out
19:30:44  [JITServerTest] [INFO] Waiting for 45000 millis.
19:31:37  [JITServerTest] [INFO] Stopping server...
19:31:37  [JITServerTest] [INFO] Waiting for 45000 millis.
19:32:42  Cannot contact ub20-390-1: java.lang.InterruptedException
19:32:47  [JITServerTest] [INFO] Stopping client...
19:32:48  [JITServerTest] [INFO] Stopping client...
19:33:15  [JITServerTest] [INFO] running testServerGoesDownAnotherComesUp: INFO and above level logging enabled
19:33:15  [JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=36170, set JITServerTest_SERVER_PORT in your env to override.
19:33:16  [JITServerTest] [INFO] Starting server with command line:
19:33:16  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=36170
19:33:16  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:33:16  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerGoesDownAnotherComesUp.server.out
19:33:23  [JITServerTest] [INFO] Starting client with command line:
19:33:23  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/java -XX:JITServerPort=36170 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../TKG/output_1709502051281/testJITServer_0/client /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_390-64,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all
19:33:23  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:33:23  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerGoesDownAnotherComesUp.client.out
19:33:26  [JITServerTest] [INFO] Waiting for 45000 millis.
19:34:20  [JITServerTest] [INFO] Stopping server...
19:34:20  [JITServerTest] [INFO] Waiting for 45000 millis.
19:35:02  [JITServerTest] [INFO] Starting server with command line:
19:35:02  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=36170
19:35:02  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:35:02  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerGoesDownAnotherComesUp.secondServer.out
19:35:04  [JITServerTest] [INFO] Waiting for 45000 millis.
19:36:36  [JITServerTest] [INFO] Stopping client...
19:36:36  [JITServerTest] [INFO] Stopping client...
19:38:20  [JITServerTest] [INFO] running testServerUnreachableForAWhile: INFO and above level logging enabled
19:38:20  [JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=54575, set JITServerTest_SERVER_PORT in your env to override.
19:38:20  [JITServerTest] [INFO] Starting server with command line:
19:38:20  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=54575
19:38:20  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:38:20  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerUnreachableForAWhile.server.out
19:38:20  [JITServerTest] [INFO] Starting client with command line:
19:38:20  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/jdkbinary/j2sdk-image/bin/java -XX:JITServerPort=54575 -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon -cp /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/../../testDependency/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar "-DjarTesterArgs=-loopforever /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/jitt.jar" org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../TKG/output_1709502051281/testJITServer_0/client /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/../../jvmtest/functional/JIT_Test/testng.xml -testnames JarTesterTest -groups level.sanity -excludegroups d.*.linux_390-64,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all
19:38:20  [JITServerTest] [INFO] With stdout/stderr redirected to:
19:38:20  /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_0/aqa-tests/TKG/output_1709502051281/testJITServer_0/testServerUnreachableForAWhile.client.out
19:38:20  [JITServerTest] [INFO] Waiting for 45000 millis.
19:39:06  [JITServerTest] [INFO] Pausing server for 10000 millis.
19:39:11  [JITServerTest] [INFO] Resuming server...
19:39:11  [JITServerTest] [INFO] Waiting for 45000 millis.
19:39:55  [JITServerTest] [INFO] Stopping server...
19:39:55  [JITServerTest] [INFO] Waiting for 45000 millis.
19:40:58  [JITServerTest] [INFO] Stopping client...
19:43:44  PASSED: testServer
19:43:44  PASSED: testServerAOTCache
19:43:44  PASSED: testServerComesUpAfterClient
19:43:45  PASSED: testServerComesUpAfterClientAndGoesDownAgain
19:43:45  FAILED: testServerGoesDown
19:43:45  java.lang.AssertionError: The process is still alive after waiting for 30000ms.
19:43:45  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
19:43:45  	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:347)
19:43:45  	at jit.test.jitserver.JITServerTest.testServerGoesDown(JITServerTest.java:460)
19:43:45  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
19:43:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
19:43:45  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
19:43:45  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
19:43:45  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
19:43:45  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
19:43:45  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
19:43:45  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
19:43:45  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
19:43:45  	at org.testng.TestRunner.run(TestRunner.java:505)
19:43:45  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
19:43:45  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
19:43:45  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
19:43:45  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
19:43:45  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
19:43:45  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
19:43:45  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
19:43:45  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
19:43:45  	at org.testng.TestNG.runSuites(TestNG.java:1049)
19:43:45  	at org.testng.TestNG.run(TestNG.java:1017)
19:43:45  	at org.testng.TestNG.privateMain(TestNG.java:1354)
19:43:45  	at org.testng.TestNG.main(TestNG.java:1323)
19:43:45  
19:43:45  FAILED: testServerGoesDownAnotherComesUp
19:43:45  java.lang.AssertionError: The process is still alive after waiting for 30000ms.
19:43:45  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
19:43:45  	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:347)
19:43:45  	at jit.test.jitserver.JITServerTest.testServerGoesDownAnotherComesUp(JITServerTest.java:501)
etc.
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_s390x_linux_Release_testList_1/2/ - [ub20-390-6](https://openj9-jenkins.osuosl.org/computer/ub20-390-6)
testJITServer_1
testJITServer_2

**Comment by pshipton** [comment]
@mpirvu fyi

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_linux_Nightly_testList_1/666

**Comment by pshipton** [comment]
Seems a dup of https://github.com/eclipse-openj9/openj9/issues/14594
