### ISSUE TITLE
OpenJDK java/util/concurrent/tck/JSR166TestCase security-manager timed out waiting for thread to terminate

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19082]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/23
jdk_util_1 
java/util/concurrent/tck/JSR166TestCase.java#security-manager
```
23:17:04  STARTED    LockSupportTest::testParkNeg_parkUntil 'testParkNeg_parkUntil'
23:17:04  junit.framework.AssertionFailedError: timed out waiting for thread to terminate, thread=Thread[#1086,Thread-361,5,jsr1666TestThreadGroup], state=TIMED_WAITING
23:17:04  ------ stacktrace dump start ------
23:17:04  "main" prio=5 Id=2 WAITING
23:17:04  	at java.base@22-internal/java.lang.Object.waitImpl(Native Method)
23:17:04  	at java.base@22-internal/java.lang.Object.wait(Object.java:255)
23:17:04  	at java.base@22-internal/java.lang.Object.wait(Object.java:221)
23:17:04  	at java.base@22-internal/java.lang.Thread.join(Thread.java:2069)
23:17:04  	at java.base@22-internal/java.lang.Thread.join(Thread.java:2145)
23:17:04  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:85)
23:17:04  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
23:17:04  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
23:17:04  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
23:17:04  "JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
23:17:04  "JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE
23:17:04  "JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE
23:17:04  "JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE
23:17:04  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE
23:17:04  "JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING
23:17:04  "IProfiler" prio=5 Id=13 RUNNABLE
23:17:04  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
23:17:04  "Finalizer thread" prio=5 Id=15 RUNNABLE
23:17:04  "GC Worker" prio=5 Id=16 RUNNABLE
23:17:04  "GC Worker" prio=5 Id=17 RUNNABLE
23:17:04  "GC Worker" prio=5 Id=18 RUNNABLE
23:17:04  "Attach API update file access time" prio=5 Id=21 TIMED_WAITING
23:17:04  	at java.base@22-internal/java.lang.Thread.sleepImpl(Native Method)
23:17:04  	at java.base@22-internal/java.lang.Thread.sleepNanos(Thread.java:498)
23:17:04  	at java.base@22-internal/java.lang.Thread.sleep(Thread.java:529)
23:17:04  	at java.base@22-internal/openj9.internal.tools.attach.target.AttachHandler$1.run(AttachHandler.java:345)
23:17:04  "Attach API wait loop" prio=10 Id=22 RUNNABLE
23:17:04  	at java.base@22-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
23:17:04  	at java.base@22-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
23:17:04  	at java.base@22-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
23:17:04  	at java.base@22-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
23:17:04  "MainThread" prio=5 Id=23 RUNNABLE
23:17:04  	at java.management@22-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
23:17:04  	at java.management@22-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:693)
23:17:04  	at java.management@22-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:675)
23:17:04  	at app//JSR166TestCase.dumpTestThreads(JSR166TestCase.java:1229)
23:17:04  	at app//JSR166TestCase.threadRecordFailure(JSR166TestCase.java:859)
23:17:04  	at app//JSR166TestCase.threadFail(JSR166TestCase.java:933)
23:17:04  	at app//JSR166TestCase.awaitTermination(JSR166TestCase.java:1718)
23:17:04  	at app//JSR166TestCase.awaitTermination(JSR166TestCase.java:1732)
23:17:04  	at app//LockSupportTest.testParkNeg(LockSupportTest.java:403)
23:17:04  	at app//LockSupportTest.testParkNeg_parkUntil(LockSupportTest.java:389)
23:17:04  	at java.base@22-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
23:17:04  	at java.base@22-internal/java.lang.reflect.Method.invoke(Method.java:586)
23:17:04  	at app//junit.framework.TestCase.runTest(TestCase.java:177)
23:17:04  	at app//JSR166TestCase.runTest(JSR166TestCase.java:406)
23:17:04  	at app//junit.framework.TestCase.runBare(TestCase.java:142)
23:17:04  	at app//JSR166TestCase.runBare(JSR166TestCase.java:397)
23:17:04  	at app//junit.framework.TestResult$1.protect(TestResult.java:122)
23:17:04  	at app//junit.framework.TestResult.runProtected(TestResult.java:142)
23:17:04  	at app//junit.framework.TestResult.run(TestResult.java:125)
23:17:04  	at app//junit.framework.TestCase.run(TestCase.java:130)
23:17:04  	at app//junit.framework.TestSuite.runTest(TestSuite.java:241)
23:17:04  	at app//junit.framework.TestSuite.run(TestSuite.java:236)
23:17:04  	at app//junit.framework.TestSuite.runTest(TestSuite.java:241)
23:17:04  	at app//junit.framework.TestSuite.run(TestSuite.java:236)
23:17:04  	at app//org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
23:17:04  	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:137)
23:17:04  	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:115)
23:17:04  	at app//org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
23:17:04  	at app//org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
23:17:04  	at app//org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
23:17:04  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
23:17:04  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
23:17:04  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
23:17:04  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
23:17:04  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
23:17:04  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
23:17:04  	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
23:17:04  	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
23:17:04  	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
23:17:04  	at app//com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:142)
23:17:04  	at app//com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
23:17:04  	at app//com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
23:17:04  	at java.base@22-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
23:17:04  	at java.base@22-internal/java.lang.reflect.Method.invoke(Method.java:586)
23:17:04  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
23:17:04  	at java.base@22-internal/java.lang.Thread.run(Thread.java:1582)
23:17:04  "ClassByNameCache Reaper" prio=5 Id=455 WAITING
23:17:04  	at java.base@22-internal/java.lang.Object.waitImpl(Native Method)
23:17:04  	at java.base@22-internal/java.lang.Object.wait(Object.java:255)
23:17:04  	at java.base@22-internal/java.lang.Object.wait(Object.java:221)
23:17:04  	at java.base@22-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
23:17:04  	at java.base@22-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:109)
23:17:04  	at java.base@22-internal/java.io.ClassByNameCache$Reaper.run(ClassByNameCache.java:232)
23:17:04  	at java.base@22-internal/java.lang.Thread.run(Thread.java:1582)
23:17:04  "Thread-361" prio=5 Id=1086 TIMED_WAITING
23:17:04  	at java.base@22-internal/jdk.internal.misc.Unsafe.park(Native Method)
23:17:04  	at java.base@22-internal/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:449)
23:17:04  	at app//LockSupportTest$ParkMethod$2.park(LockSupportTest.java:78)
23:17:04  	at app//LockSupportTest$8.realRun(LockSupportTest.java:400)
23:17:04  	at app//JSR166TestCase$CheckedRunnable.run(JSR166TestCase.java:1742)
23:17:04  	at java.base@22-internal/java.lang.Thread.run(Thread.java:1582)
23:17:04  ------ stacktrace dump end ------
23:17:04  junit.framework.AssertionFailedError: timed out waiting for thread to terminate, thread=Thread[#1086,Thread-361,5,jsr1666TestThreadGroup], state=TIMED_WAITING
23:17:04  	at junit.framework.Assert.fail(Assert.java:57)
23:17:04  	at junit.framework.TestCase.fail(TestCase.java:223)
23:17:04  	at JSR166TestCase.threadFail(JSR166TestCase.java:931)
23:17:04  	at JSR166TestCase.awaitTermination(JSR166TestCase.java:1718)
23:17:04  	at JSR166TestCase.awaitTermination(JSR166TestCase.java:1732)
23:17:04  	at LockSupportTest.testParkNeg(LockSupportTest.java:403)
23:17:04  	at LockSupportTest.testParkNeg_parkUntil(LockSupportTest.java:389)
```

Perhaps related to https://github.com/eclipse-openj9/openj9/issues/14752

**Comment by JasonFengJ9** [comment]
[JDK23 Milestone 1 build x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk23_j9_sanity.openjdk_x86-64_windows_testList_0/8/consoleFull)(`win10x86-rtp-rt8-1`)
```
23:56:44  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
23:56:44  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

00:47:02  TEST: java/util/concurrent/tck/JSR166TestCase.java#security-manager

00:47:02  ------ stacktrace dump end ------
00:47:02  junit.framework.AssertionFailedError: timed out waiting for thread to terminate, thread=Thread[#1120,Thread-362,5,jsr1666TestThreadGroup], state=TIMED_WAITING
00:47:02  	at junit.framework.Assert.fail(Assert.java:57)
00:47:02  	at junit.framework.TestCase.fail(TestCase.java:223)
00:47:02  	at JSR166TestCase.threadFail(JSR166TestCase.java:931)
00:47:02  	at JSR166TestCase.awaitTermination(JSR166TestCase.java:1718)
00:47:02  	at JSR166TestCase.awaitTermination(JSR166TestCase.java:1732)
00:47:02  	at LockSupportTest.testParkNeg(LockSupportTest.java:403)
00:47:02  	at LockSupportTest.testParkNeg_parkUntil(LockSupportTest.java:389)

00:47:02  FAILED     LockSupportTest::testParkNeg_parkUntil 'testParkNeg_parkUntil'
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42759/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/85
```
03:38:24  STARTED    LockSupportTest::testParkNeg_parkUntilBlocker 'testParkNeg_parkUntilBlocker'
03:38:24  junit.framework.AssertionFailedError: timed out waiting for thread to terminate, thread=Thread[#1117,Thread-365,5,jsr1666TestThreadGroup], state=TIMED_WAITING
03:38:24  ------ stacktrace dump start ------
03:38:24  "main" prio=5 Id=2 WAITING
03:38:24  	at java.base@23.0.1-internal/java.lang.Object.waitImpl(Native Method)
03:38:24  	at java.base@23.0.1-internal/java.lang.Object.wait(Object.java:254)
03:38:24  	at java.base@23.0.1-internal/java.lang.Object.wait(Object.java:221)
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.join(Thread.java:2050)
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.join(Thread.java:2126)
03:38:24  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:85)
03:38:24  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
03:38:24  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
03:38:24  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
03:38:24  "JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
03:38:24  "JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE
03:38:24  "JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE
03:38:24  "JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE
03:38:24  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE
03:38:24  "JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING
03:38:24  "IProfiler" prio=5 Id=13 RUNNABLE
03:38:24  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
03:38:24  "Finalizer thread" prio=5 Id=15 RUNNABLE
03:38:24  "GC Worker" prio=5 Id=16 RUNNABLE
03:38:24  "GC Worker" prio=5 Id=17 RUNNABLE
03:38:24  "GC Worker" prio=5 Id=18 RUNNABLE
03:38:24  "Attach API update file access time" prio=5 Id=21 TIMED_WAITING
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.sleepImpl(Native Method)
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.sleepNanos(Thread.java:503)
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.sleep(Thread.java:534)
03:38:24  	at java.base@23.0.1-internal/openj9.internal.tools.attach.target.AttachHandler$1.run(AttachHandler.java:348)
03:38:24  "Attach API wait loop" prio=10 Id=22 RUNNABLE
03:38:24  	at java.base@23.0.1-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
03:38:24  	at java.base@23.0.1-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
03:38:24  	at java.base@23.0.1-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
03:38:24  	at java.base@23.0.1-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
03:38:24  "MainThread" prio=5 Id=23 RUNNABLE
03:38:24  	at java.management@23.0.1-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
03:38:24  	at java.management@23.0.1-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:693)
03:38:24  	at java.management@23.0.1-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:675)
03:38:24  	at app//JSR166TestCase.dumpTestThreads(JSR166TestCase.java:1229)
03:38:24  	at app//JSR166TestCase.threadRecordFailure(JSR166TestCase.java:859)
03:38:24  	at app//JSR166TestCase.threadFail(JSR166TestCase.java:933)
03:38:24  	at app//JSR166TestCase.awaitTermination(JSR166TestCase.java:1718)
03:38:24  	at app//JSR166TestCase.awaitTermination(JSR166TestCase.java:1732)
03:38:24  	at app//LockSupportTest.testParkNeg(LockSupportTest.java:403)
03:38:24  	at app//LockSupportTest.testParkNeg_parkUntilBlocker(LockSupportTest.java:395)
03:38:24  	at java.base@23.0.1-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
03:38:24  	at java.base@23.0.1-internal/java.lang.reflect.Method.invoke(Method.java:586)
03:38:24  	at app//junit.framework.TestCase.runTest(TestCase.java:177)
03:38:24  	at app//JSR166TestCase.runTest(JSR166TestCase.java:406)
03:38:24  	at app//junit.framework.TestCase.runBare(TestCase.java:142)
03:38:24  	at app//JSR166TestCase.runBare(JSR166TestCase.java:397)
03:38:24  	at app//junit.framework.TestResult$1.protect(TestResult.java:122)
03:38:24  	at app//junit.framework.TestResult.runProtected(TestResult.java:142)
03:38:24  	at app//junit.framework.TestResult.run(TestResult.java:125)
03:38:24  	at app//junit.framework.TestCase.run(TestCase.java:130)
03:38:24  	at app//junit.framework.TestSuite.runTest(TestSuite.java:241)
03:38:24  	at app//junit.framework.TestSuite.run(TestSuite.java:236)
03:38:24  	at app//junit.framework.TestSuite.runTest(TestSuite.java:241)
03:38:24  	at app//junit.framework.TestSuite.run(TestSuite.java:236)
03:38:24  	at app//org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
03:38:24  	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:137)
03:38:24  	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:115)
03:38:24  	at app//org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
03:38:24  	at app//org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
03:38:24  	at app//org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
03:38:24  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
03:38:24  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
03:38:24  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
03:38:24  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
03:38:24  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
03:38:24  	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
03:38:24  	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
03:38:24  	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
03:38:24  	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
03:38:24  	at app//com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:142)
03:38:24  	at app//com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
03:38:24  	at app//com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
03:38:24  	at java.base@23.0.1-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
03:38:24  	at java.base@23.0.1-internal/java.lang.reflect.Method.invoke(Method.java:586)
03:38:24  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.run(Thread.java:1587)
03:38:24  "ClassByNameCache Reaper" prio=5 Id=473 WAITING
03:38:24  	at java.base@23.0.1-internal/java.lang.Object.waitImpl(Native Method)
03:38:24  	at java.base@23.0.1-internal/java.lang.Object.wait(Object.java:254)
03:38:24  	at java.base@23.0.1-internal/java.lang.Object.wait(Object.java:221)
03:38:24  	at java.base@23.0.1-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:140)
03:38:24  	at java.base@23.0.1-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:112)
03:38:24  	at java.base@23.0.1-internal/java.io.ClassByNameCache$Reaper.run(ClassByNameCache.java:232)
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.run(Thread.java:1587)
03:38:24  "Thread-365" prio=5 Id=1117 TIMED_WAITING
03:38:24  	at java.base@23.0.1-internal/jdk.internal.misc.Unsafe.park(Native Method)
03:38:24  	at java.base@23.0.1-internal/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:317)
03:38:24  	at app//LockSupportTest$ParkMethod$5.park(LockSupportTest.java:94)
03:38:24  	at app//LockSupportTest$8.realRun(LockSupportTest.java:400)
03:38:24  	at app//JSR166TestCase$CheckedRunnable.run(JSR166TestCase.java:1742)
03:38:24  	at java.base@23.0.1-internal/java.lang.Thread.run(Thread.java:1587)
03:38:24  ------ stacktrace dump end ------
03:38:24  junit.framework.AssertionFailedError: timed out waiting for thread to terminate, thread=Thread[#1117,Thread-365,5,jsr1666TestThreadGroup], state=TIMED_WAITING
03:38:24  	at junit.framework.Assert.fail(Assert.java:57)
03:38:24  	at junit.framework.TestCase.fail(TestCase.java:223)
03:38:24  	at JSR166TestCase.threadFail(JSR166TestCase.java:931)
03:38:24  	at JSR166TestCase.awaitTermination(JSR166TestCase.java:1718)
03:38:24  	at JSR166TestCase.awaitTermination(JSR166TestCase.java:1732)
03:38:24  	at LockSupportTest.testParkNeg(LockSupportTest.java:403)
03:38:24  	at LockSupportTest.testParkNeg_parkUntilBlocker(LockSupportTest.java:395)
```
