### ISSUE TITLE
JDK22 MBCS_Tests failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19083]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_special.functional_aarch64_linux/3/consoleFull)(`sles15-aarch64-1`):
```
openjdk version "22-beta" 2024-03-19
IBM Semeru Runtime Open Edition 22+36-202403021704 (build 22-beta+36-202403021704)
Eclipse OpenJ9 VM 22+36-202403021704 (build master-5726a9c57, JRE 22 Linux aarch64-64-Bit Compressed References 20240302_12 (JIT enabled, AOT enabled)
OpenJ9   - 5726a9c57
OMR      - 53e909c41
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=MBCS_Tests_codepoint_linux_0,MBCS_Tests_datetime_formatter_0,MBCS_Tests_formatter_zh_TW_linux_0,MBCS_Tests_i18n_ko_KR_linux_0,MBCS_Tests_unicode_linux_0&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=3&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F12%2Fibm-semeru-open-jdk_aarch64_linux_JDK22U_2024-03-02-17-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F12%2Fibm-semeru-open-testimage_aarch64_linux_JDK22U_2024-03-02-17-01.tar.gz&BUILD_IDENTIFIER=&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=22&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk22&JCK_GIT_BRANCH=main&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
16:24:39  variation: NoOptions
16:24:39  JVM_OPTIONS:  

16:24:39  TESTING:
16:24:41  --- Checking /home/jenkins/workspace/Test_openjdk22_j9_special.functional_aarch64_linux/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/codepoint/data/UnicodeData-15.0.0.txt ---
16:24:43  --- Done ---
16:24:45  --- Reading NumValue from /home/jenkins/workspace/Test_openjdk22_j9_special.functional_aarch64_linux/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/codepoint/data/UnicodeData-15.0.0.txt ---
16:24:45  --- Checking /home/jenkins/workspace/Test_openjdk22_j9_special.functional_aarch64_linux/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/codepoint/data/Unihan_IRGSources-15.0.0.txt ---
16:25:00  --- Done ---
16:25:00  Test Failed
16:25:00  -----------------------------------
16:25:00  MBCS_Tests_codepoint_linux_0_FAILED

16:33:43  TESTING:
16:33:45  Checking UnicodeData-15.0.0.txt
16:33:48    Checked 288767 characters
16:33:48  627 characters were not checked
16:33:48  Checking Blocks-15.0.0.txt
16:33:49    Checked 293168 characters
16:33:49    Undefined 4396 characters
16:33:49  Checking Scripts-15.0.0.txt
16:33:51    Checked 149251 characters
16:33:51  Checking PropertyValueAliases
16:33:52    Total 164 enums are defined
16:33:52    Checking PropertyValueAliases-15.0.0.txt
16:33:52    Missing code(expected): Hrkt
16:33:52    Missing value(expected): KATAKANA_OR_HIRAGANA
16:33:52    Checked 165 items
16:33:52  Checking NormalizerTest
16:33:54    Phase1   Inspection times : 114444
16:33:54    Phase1   Test is Passed.
16:33:55    Phase2   Defined Unicode characters : 289394
16:33:55    Phase2   Ignored characters :  17029
16:33:55    Phase2   Test is Passed.
16:33:55  Test Failed
16:33:55  -----------------------------------
16:33:55  MBCS_Tests_unicode_linux_0_FAILED

16:26:42  FAILED: QuarterTest on QuarterTest(FormatTest_zh_tw)
16:26:42  org.junit.ComparisonFailure: expected:<1 01 [第1季] 第1季 1> but was:<1 01 [1] 第1季 1>
16:26:42  	at org.junit.Assert.assertEquals(Assert.java:125)
16:26:42  	at org.junit.Assert.assertEquals(Assert.java:147)
16:26:42  	at FormatTest_zh_tw.QuarterTest(FormatTest_zh_tw.java:129)
16:26:42  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
16:26:42  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
16:26:42  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
16:26:42  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
16:26:42  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
16:26:42  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
16:26:42  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
16:26:42  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
16:26:42  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
16:26:42  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
16:26:42  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
16:26:42  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
16:26:42  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
16:26:42  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
16:26:42  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
16:26:42  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
16:26:42  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
16:26:42  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
16:26:42  	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:82)
16:26:42  	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:70)
16:26:42  	at org.testng.TestRunner$1.run(TestRunner.java:570)
16:26:42  	at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:717)
16:26:42  	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:601)
16:26:42  	at org.testng.TestRunner.run(TestRunner.java:502)
16:26:42  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
16:26:42  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
16:26:42  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
16:26:42  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
16:26:42  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
16:26:42  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
16:26:42  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
16:26:42  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
16:26:42  	at org.testng.TestNG.runSuites(TestNG.java:1049)
16:26:42  	at org.testng.TestNG.run(TestNG.java:1017)
16:26:42  	at org.testng.TestNG.privateMain(TestNG.java:1354)
16:26:42  	at org.testng.TestNG.main(TestNG.java:1323)
16:26:42  
16:26:42  
16:26:42  ===============================================
16:26:42      dateTest11
16:26:42      Tests run: 28, Failures: 1, Skips: 0
16:26:42  ===============================================
16:26:42  
16:26:42  
16:26:42  ===============================================
16:26:42  DateTime
16:26:42  Total tests run: 28, Failures: 1, Skips: 0
16:26:42  ===============================================
16:26:42  
16:26:43  -----------------------------------
16:26:43  MBCS_Tests_datetime_formatter_0_FAILED

16:27:10  TEST SETUP:
16:27:10  JVMSHRC005I No shared class caches available
16:27:10  JVMSHRC005I No shared class caches available
16:27:10  cache cleanup done
16:27:10  
16:27:10  TESTING:
16:27:12  -----------------------------------
16:27:12  MBCS_Tests_formatter_zh_TW_linux_0_FAILED

16:27:18  TESTING:
16:27:18  1..3
16:27:18  # linux_ko_KR.UTF-8
16:27:18  base /home/jenkins/workspace/Test_openjdk22_j9_special.functional_aarch64_linux/jvmtest/functional/MBCS_Tests/i18n/
16:27:21  ok 1 - showlocale test
16:27:21  ok 2 - BreakIteratorTest test
16:27:21  not ok 3 - DateFormatTest
16:27:21  #   Failed test 'DateFormatTest'
16:27:21  #   at /home/jenkins/workspace/Test_openjdk22_j9_special.functional_aarch64_linux/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/i18n/test.pl line 121.
16:27:21  # Looks like you failed 1 test of 3.
16:27:21  -----------------------------------
16:27:21  MBCS_Tests_i18n_ko_KR_linux_0_FAILED

16:33:43  TESTING:
16:33:45  Checking UnicodeData-15.0.0.txt
16:33:48    Checked 288767 characters
16:33:48  627 characters were not checked
16:33:48  Checking Blocks-15.0.0.txt
16:33:49    Checked 293168 characters
16:33:49    Undefined 4396 characters
16:33:49  Checking Scripts-15.0.0.txt
16:33:51    Checked 149251 characters
16:33:51  Checking PropertyValueAliases
16:33:52    Total 164 enums are defined
16:33:52    Checking PropertyValueAliases-15.0.0.txt
16:33:52    Missing code(expected): Hrkt
16:33:52    Missing value(expected): KATAKANA_OR_HIRAGANA
16:33:52    Checked 165 items
16:33:52  Checking NormalizerTest
16:33:54    Phase1   Inspection times : 114444
16:33:54    Phase1   Test is Passed.
16:33:55    Phase2   Defined Unicode characters : 289394
16:33:55    Phase2   Ignored characters :  17029
16:33:55    Phase2   Test is Passed.
16:33:55  Test Failed
16:33:55  -----------------------------------
16:33:55  MBCS_Tests_unicode_linux_0_FAILED

```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38389/) - all failed

**Comment by knn-k** [comment]
I see the same failures on other platforms, such as ppc64le_linux and x86-64_mac.

**Comment by JasonFengJ9** [comment]
> I see the same failures on other platforms, such as ppc64le_linux and x86-64_mac.

Correct, this is an issue across platforms.

**Comment by pshipton** [comment]
Does it also fail on Adoptium?

**Comment by JasonFengJ9** [comment]
[RI JDK22](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38523/console) failed as well.
```
17:31:45  openjdk version "22-beta" 2024-03-19
17:31:45  OpenJDK Runtime Environment Temurin-22+36-202402170010 (build 22-beta+36-ea)
17:31:45  OpenJDK 64-Bit Server VM Temurin-22+36-202402170010 (build 22-beta+36-ea, mixed mode, sharing)
17:31:45  make[2]: Entering directory '/home/jenkins/workspace/Grinder/aqa-tests'

17:31:45  TESTING:
17:31:45  --- Checking /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/codepoint/data/UnicodeData-15.0.0.txt ---
17:31:47  --- Done ---
17:31:47  --- Reading NumValue from /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/codepoint/data/UnicodeData-15.0.0.txt ---
17:31:47  --- Checking /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/codepoint/data/Unihan_IRGSources-15.0.0.txt ---
17:31:53  --- Done ---
17:31:53  Test Failed
17:31:53  -----------------------------------
17:31:53  MBCS_Tests_codepoint_linux_0_FAILED

17:31:53  FAILED: QuarterTest on QuarterTest(FormatTest_zh_tw)
17:31:53  org.junit.ComparisonFailure: expected:<1 01 [第1季] 第1季 1> but was:<1 01 [1] 第1季 1>
17:31:53  	at org.junit.Assert.assertEquals(Assert.java:125)
17:31:53  	at org.junit.Assert.assertEquals(Assert.java:147)
17:31:53  	at FormatTest_zh_tw.QuarterTest(FormatTest_zh_tw.java:129)
17:31:53  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:31:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
17:31:53  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
17:31:53  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
17:31:53  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
17:31:53  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
17:31:53  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
17:31:53  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
17:31:53  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
17:31:53  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
17:31:53  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
17:31:53  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
17:31:53  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
17:31:53  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
17:31:53  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
17:31:53  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
17:31:53  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
17:31:53  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
17:31:53  	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:82)
17:31:53  	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:70)
17:31:53  	at org.testng.TestRunner$1.run(TestRunner.java:570)
17:31:53  	at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:717)
17:31:53  	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:601)
17:31:53  	at org.testng.TestRunner.run(TestRunner.java:502)
17:31:53  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
17:31:53  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
17:31:53  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
17:31:53  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
17:31:53  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
17:31:53  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
17:31:53  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
17:31:53  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
17:31:53  	at org.testng.TestNG.runSuites(TestNG.java:1049)
17:31:53  	at org.testng.TestNG.run(TestNG.java:1017)
17:31:53  	at org.testng.TestNG.privateMain(TestNG.java:1354)
17:31:53  	at org.testng.TestNG.main(TestNG.java:1323)
17:31:53  
17:31:53  
17:31:53  ===============================================
17:31:53      dateTest11
17:31:53      Tests run: 28, Failures: 1, Skips: 0
17:31:53  ===============================================
17:31:53  
17:31:53  
17:31:53  ===============================================
17:31:53  DateTime
17:31:53  Total tests run: 28, Failures: 1, Skips: 0
17:31:53  ===============================================
17:31:53  
17:31:53  -----------------------------------
17:31:53  MBCS_Tests_datetime_formatter_0_FAILED

17:31:53  TEST SETUP:
17:31:53  Nothing to be done for setup.
17:31:53  
17:31:53  TESTING:
17:31:54  -----------------------------------
17:31:54  MBCS_Tests_formatter_zh_TW_linux_0_FAILED

17:31:54  TESTING:
17:31:54  1..3
17:31:54  # linux_ko_KR.UTF-8
17:31:54  base /home/jenkins/workspace/Grinder/jvmtest/functional/MBCS_Tests/i18n/
17:31:54  ok 1 - showlocale test
17:31:54  ok 2 - BreakIteratorTest test
17:31:54  not ok 3 - DateFormatTest
17:31:54  #   Failed test 'DateFormatTest'
17:31:54  #   at /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/i18n/test.pl line 121.
17:31:54  # Looks like you failed 1 test of 3.
17:31:54  -----------------------------------
17:31:54  MBCS_Tests_i18n_ko_KR_linux_0_FAILED

17:31:55  TESTING:
17:31:55  Checking UnicodeData-15.0.0.txt
17:31:56    Checked 288767 characters
17:31:56  627 characters were not checked
17:31:56  Checking Blocks-15.0.0.txt
17:31:56    Checked 293168 characters
17:31:56    Undefined 4396 characters
17:31:56  Checking Scripts-15.0.0.txt
17:31:57    Checked 149251 characters
17:31:57  Checking PropertyValueAliases
17:31:57    Total 164 enums are defined
17:31:57    Checking PropertyValueAliases-15.0.0.txt
17:31:57    Missing code(expected): Hrkt
17:31:57    Missing value(expected): KATAKANA_OR_HIRAGANA
17:31:57    Checked 165 items
17:31:57  Checking NormalizerTest
17:31:58    Phase1   Inspection times : 114444
17:31:58    Phase1   Test is Passed.
17:31:58    Phase2   Defined Unicode characters : 289394
17:31:58    Phase2   Ignored characters :  17029
17:31:58    Phase2   Test is Passed.
17:31:58  Test Failed
17:31:58  -----------------------------------
17:31:58  MBCS_Tests_unicode_linux_0_FAILED
```
This is a JCL issue.

**Comment by smlambert** [comment]
Fixes should be coming in https://github.com/adoptium/aqa-tests/pull/5150

**Comment by tajila** [comment]
The fix is in @JasonFengJ9 Can this be closed

**Comment by JasonFengJ9** [comment]
There are still two failures in [latest JDK22 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_special.functional_aarch64_linux/5/consoleFull)(`rhel8-aarch64-4`)
```
16:01:53  TESTING:
16:01:53  1..3
16:01:53  # linux_ko_KR.UTF-8
16:01:53  base /home/jenkins/workspace/Test_openjdk22_j9_special.functional_aarch64_linux/jvmtest/functional/MBCS_Tests/i18n/
16:01:56  ok 1 - showlocale test
16:01:56  ok 2 - BreakIteratorTest test
16:01:56  not ok 3 - DateFormatTest
16:01:56  #   Failed test 'DateFormatTest'
16:01:56  #   at /home/jenkins/workspace/Test_openjdk22_j9_special.functional_aarch64_linux/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/i18n/test.pl line 121.
16:01:56  # Looks like you failed 1 test of 3.
16:01:56  -----------------------------------
16:01:56  MBCS_Tests_i18n_ko_KR_linux_0_FAILED

16:01:47  TEST SETUP:
16:01:47  JVMSHRC005I No shared class caches available
16:01:47  JVMSHRC005I No shared class caches available
16:01:47  cache cleanup done
16:01:47  
16:01:47  TESTING:
16:01:49  -----------------------------------
16:01:49  MBCS_Tests_formatter_zh_TW_linux_0_FAILED
```
[15x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39195/) - failed

[RI 15x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39196/)  - same failures
```
14:54:41  openjdk version "22" 2024-03-19
14:54:41  OpenJDK Runtime Environment Temurin-22+36 (build 22+36)

14:54:41  ===============================================
14:54:41  Running test MBCS_Tests_formatter_zh_TW_linux_0 ...
14:54:41  ===============================================
14:54:41  MBCS_Tests_formatter_zh_TW_linux_0 Start Time: Mon Mar 25 14:54:41 2024 Epoch Time (ms): 1711392881342
14:54:41  variation: NoOptions
14:54:41  JVM_OPTIONS:  
14:54:41  { \
14:54:41  echo "";	echo "TEST SETUP:"; \
14:54:41  echo "Nothing to be done for setup."; \
14:54:41  mkdir -p "/home/jenkins/workspace/Grinder_iteration_4/aqa-tests/TKG/../TKG/output_1711392881394/MBCS_Tests_formatter_zh_TW_linux_0"; \
14:54:41  cd "/home/jenkins/workspace/Grinder_iteration_4/aqa-tests/TKG/../TKG/output_1711392881394/MBCS_Tests_formatter_zh_TW_linux_0"; \
14:54:41  echo "";	echo "TESTING:"; \
14:54:41  LANG=zh_TW.UTF-8 bash /home/jenkins/workspace/Grinder_iteration_4/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/formatter/test.sh; \
14:54:41  if [ $? -eq 0 ]; then echo "-----------------------------------"; echo "MBCS_Tests_formatter_zh_TW_linux_0""_PASSED"; echo "-----------------------------------"; cd /home/jenkins/workspace/Grinder_iteration_4/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Grinder_iteration_4/aqa-tests/TKG/../TKG/output_1711392881394/MBCS_Tests_formatter_zh_TW_linux_0"; else echo "-----------------------------------"; echo "MBCS_Tests_formatter_zh_TW_linux_0""_FAILED"; echo "-----------------------------------"; fi; \
14:54:41  echo "";	echo "TEST TEARDOWN:"; \
14:54:41  echo "Nothing to be done for teardown."; \
14:54:41   } 2>&1 | tee -a "/home/jenkins/workspace/Grinder_iteration_4/aqa-tests/TKG/../TKG/output_1711392881394/TestTargetResult";
14:54:41  
14:54:41  TEST SETUP:
14:54:41  Nothing to be done for setup.
14:54:41  
14:54:41  TESTING:
14:54:41  -----------------------------------
14:54:41  MBCS_Tests_formatter_zh_TW_linux_0_FAILED

14:54:41  TESTING:
14:54:42  1..3
14:54:42  # linux_ko_KR.UTF-8
14:54:42  base /home/jenkins/workspace/Grinder_iteration_4/jvmtest/functional/MBCS_Tests/i18n/
14:54:42  ok 1 - showlocale test
14:54:42  ok 2 - BreakIteratorTest test
14:54:42  not ok 3 - DateFormatTest
14:54:42  #   Failed test 'DateFormatTest'
14:54:42  #   at /home/jenkins/workspace/Grinder_iteration_4/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/i18n/test.pl line 121.
14:54:42  # Looks like you failed 1 test of 3.
14:54:42  -----------------------------------
14:54:42  MBCS_Tests_i18n_ko_KR_linux_0_FAILED
```

@smlambert any insights?

**Comment by llxia** [comment]
`MBCS_Tests_i18n_ko_KR_linux` should be fixed by PR https://github.com/adoptium/aqa-tests/pull/6651
