### ISSUE TITLE
LambdaLoadTest_special_J9_5m_8_FAILED testCaptureArrayList(net.adoptopenjdk.test.lambda.TestLambdaCapture): java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19105]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_special.system_aarch64_mac_testList_1/116/)(`macaarch64rt4`):
```
java version "21.0.3-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 21.0.3+5-202403070035 (build 21.0.3-beta+5-202403070035)
Eclipse OpenJ9 VM 21.0.3+5-202403070035 (build master-eb552e4d9, JRE 21 Mac OS X aarch64-64-Bit 20240307_118 (JIT enabled, AOT enabled)
OpenJ9   - eb552e4d9
OMR      - b7e442923
JCL      - e9adf19e3 based on jdk-21.0.3+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=LambdaLoadTest_special_J9_5m_8&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_special.system_aarch64_mac&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-mac-aarch64-openj9-IBM%2F118%2Fibm-semeru-certified-jdk_aarch64_mac_JDK21U_2024-03-07-00-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=120&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-07T06:35:32.962Z] variation: Mode145
[2024-03-07T06:35:32.962Z] JVM_OPTIONS:  -Xgcpolicy:gencon -Xshareclasses -Xjit -Xnocompressedrefs 

[2024-03-07T06:39:05.318Z] LT  testFailure: testCaptureArrayList(net.adoptopenjdk.test.lambda.TestLambdaCapture): java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2024-03-07T06:39:05.318Z] LT  java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2024-03-07T06:39:05.318Z] LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:113)
[2024-03-07T06:39:05.318Z] LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestCase.runTest(TestCase.java:176)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestResult.run(TestResult.java:125)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestCase.run(TestCase.java:129)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2024-03-07T06:39:05.318Z] LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
[2024-03-07T06:39:05.318Z] LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2024-03-07T06:39:05.318Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
[2024-03-07T06:39:05.318Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
[2024-03-07T06:39:05.318Z] LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2024-03-07T06:39:05.318Z] LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2024-03-07T06:39:05.318Z] LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2024-03-07T06:39:05.318Z] LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2024-03-07T06:39:05.319Z] LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2024-03-07T06:39:05.319Z] LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2024-03-07T06:39:05.319Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2024-03-07T06:39:05.319Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2024-03-07T06:39:05.319Z] LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2024-03-07T06:39:05.319Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2024-03-07T06:39:05.319Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-03-07T06:39:05.319Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-03-07T06:39:05.319Z] LT  	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-03-07T06:39:05.319Z] LT  Caused by: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2024-03-07T06:39:05.319Z] LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-07T06:39:05.319Z] LT  	... 25 more
[2024-03-07T06:39:05.319Z] LT  testFinished: testCaptureArrayList(net.adoptopenjdk.test.lambda.TestLambdaCapture)
[2024-03-07T06:39:05.319Z] LT  
[2024-03-07T06:39:05.319Z] LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaCapture
[2024-03-07T06:39:05.319Z] LT    Ran    : 5
[2024-03-07T06:39:05.319Z] LT    Passed : 4
[2024-03-07T06:39:05.319Z] LT    Failed : 1
[2024-03-07T06:39:05.319Z] LT    Ignored: 0
[2024-03-07T06:39:05.319Z] LT    Result : FAILED
[2024-03-07T06:39:05.319Z] LT  <<<

[2024-03-07T06:40:46.373Z] LambdaLoadTest_special_J9_5m_8_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38524/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_special.system_aarch64_mac_Release_testList_0/8 - [mac13-aarch64-8](https://openj9-jenkins.osuosl.org/computer/mac13-aarch64-8)
LambdaLoadTest_special_J9_5m_29 `-Xgcpolicy:gencon -Xgc:dynamicBreadthFirstScanOrdering`

```
11:41:41  LT  testFailure: testDoublePredicate(net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces): java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
11:41:41  LT  java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
11:41:41  LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:113)
11:41:41  LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
11:41:41  LT  	at junit.framework.TestCase.runTest(TestCase.java:176)
11:41:41  LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
```

**Comment by JasonFengJ9** [comment]
[JDK23 aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk23_j9_special.system_aarch64_mac_testList_4/6/)(`macaarch64rt2`)
There was a `Segmentation error vmState=0x00000000` following this NPE.
```
openjdk version "23-beta" 2024-09-17
IBM Semeru Runtime Open Edition 23+37-202408220002 (build 23-beta+37-202408220002)
Eclipse OpenJ9 VM 23+37-202408220002 (build master-18eaa15717, JRE 23 Mac OS X aarch64-64-Bit 20240822_19 (JIT enabled, AOT enabled)
OpenJ9   - 18eaa15717
OMR      - e0dde2287
JCL      - 4f8b339af based on jdk-23+37)

[2024-08-22T11:19:12.461Z] variation: Mode145
[2024-08-22T11:19:12.461Z] JVM_OPTIONS:  -Xgcpolicy:gencon -Xshareclasses -Xjit -Xnocompressedrefs 

[2024-08-22T11:21:27.444Z] LT  testFailure: testCaptureArrayList(net.adoptopenjdk.test.lambda.TestLambdaCapture): java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2024-08-22T11:21:27.444Z] LT  java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2024-08-22T11:21:27.444Z] LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:113)
[2024-08-22T11:21:27.444Z] LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestCase.runTest(TestCase.java:176)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestResult.run(TestResult.java:125)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestCase.run(TestCase.java:129)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2024-08-22T11:21:27.444Z] LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2024-08-22T11:21:27.444Z] LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2024-08-22T11:21:27.444Z] LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2024-08-22T11:21:27.444Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2024-08-22T11:21:27.444Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-08-22T11:21:27.444Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-08-22T11:21:27.444Z] LT  	at java.base/java.lang.Thread.run(Thread.java:1587)
[2024-08-22T11:21:27.444Z] LT  Caused by: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2024-08-22T11:21:27.444Z] LT  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-08-22T11:21:27.444Z] LT  	... 25 more
[2024-08-22T11:21:27.444Z] LT  testFinished: testCaptureArrayList(net.adoptopenjdk.test.lambda.TestLambdaCapture)
[2024-08-22T11:21:27.444Z] LT  
[2024-08-22T11:21:27.444Z] LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaCapture
[2024-08-22T11:21:27.444Z] LT    Ran    : 5
[2024-08-22T11:21:27.444Z] LT    Passed : 4
[2024-08-22T11:21:27.444Z] LT    Failed : 1
[2024-08-22T11:21:27.444Z] LT    Ignored: 0
[2024-08-22T11:21:27.444Z] LT    Result : FAILED
[2024-08-22T11:21:27.444Z] LT  <<<
[2024-08-22T11:21:27.444Z] LT  
[2024-08-22T11:21:27.444Z] LT  stderr Unhandled exception
[2024-08-22T11:21:27.444Z] LT  stderr Type=Segmentation error vmState=0x00000000
[2024-08-22T11:21:27.444Z] LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
[2024-08-22T11:21:27.444Z] LT  stderr Handler1=0000000101235264 Handler2=0000000100ECCFE0 InaccessibleAddress=0000000000000018
[2024-08-22T11:21:27.444Z] LT  stderr x0=000000014B940100 x1=000000016FE8A7C8 x2=000000037ADE51C8 x3=0000000158098600
[2024-08-22T11:21:27.444Z] LT  stderr x4=000000016FE8A7D8 x5=000000016FE8A7C0 x6=000000016FE8A7B8 x7=0000000140D6CB00
[2024-08-22T11:21:27.444Z] LT  stderr x8=0000000000000000 x9=0000000000000018 x10=000000016FE8A7C0 x11=000000016FE8A7C8
[2024-08-22T11:21:27.444Z] LT  stderr x12=000000016FE8A7D8 x13=000000016FE8A7B0 x14=00000001012810E4 x15=0000000000000010
[2024-08-22T11:21:27.444Z] LT  stderr x16=000000016FE8A820 x17=00000001E182F738 x18=000000014B810031 x19=0000000040000000
[2024-08-22T11:21:27.444Z] LT  stderr x20=000000028055C2F0 x21=000000016FE8A7B0 x22=00000001118C539C x23=000000016FE8A7C0
[2024-08-22T11:21:27.444Z] LT  stderr x24=000000016FE8A7D8 x25=000000016FE8A7C8 x26=000000016FE8A7C0 x27=000000016FE8A7B8
[2024-08-22T11:21:27.444Z] LT  stderr x28=000000010135ED94 x29(FP)=000000016FE8A7A0 x30(LR)=0000000101280B44 x31(SP)=000000016FE8A2C0
[2024-08-22T11:21:27.444Z] LT  stderr PC=0000000101295BA8 SP=000000016FE8A2C0
[2024-08-22T11:21:27.444Z] LT  stderr v0=0000000390449361 (f: 2420413184.000000, d: 7.561830e-314)
[2024-08-22T11:21:27.444Z] LT  stderr v1=0000000150d0be10 (f: 1355857408.000000, d: 2.791878e-314)
[2024-08-22T11:21:27.444Z] LT  stderr v2=41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
[2024-08-22T11:21:27.444Z] LT  stderr v3=000000014b9f6c20 (f: 1268739072.000000, d: 2.748836e-314)
[2024-08-22T11:21:27.444Z] LT  stderr v4=000000f400000000 (f: 0.000000, d: 5.177670e-312)
[2024-08-22T11:21:27.444Z] LT  stderr v5=00000000000000f0 (f: 240.000000, d: 1.185758e-321)
[2024-08-22T11:21:27.444Z] LT  stderr v6=000000b0000000b0 (f: 176.000000, d: 3.734713e-312)
[2024-08-22T11:21:27.444Z] LT  stderr v7=000000b000000000 (f: 0.000000, d: 3.734713e-312)
[2024-08-22T11:21:27.444Z] LT  stderr v8=000003c10000745f (f: 29791.000000, d: 2.039238e-311)
[2024-08-22T11:21:27.444Z] LT  stderr v9=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v10=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v11=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v12=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v13=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v14=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v15=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v16=bfd0000000000000 (f: 0.000000, d: -2.500000e-01)
[2024-08-22T11:21:27.444Z] LT  stderr v17=3fd5555565555555 (f: 1700091264.000000, d: 3.333333e-01)
[2024-08-22T11:21:27.444Z] LT  stderr v18=be70000008000005 (f: 134217728.000000, d: -5.960465e-08)
[2024-08-22T11:21:27.444Z] LT  stderr v19=3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
[2024-08-22T11:21:27.444Z] LT  stderr v20=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v21=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v22=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v23=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v24=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v25=414baf8000000000 (f: 0.000000, d: 3.628800e+06)
[2024-08-22T11:21:27.444Z] LT  stderr v26=414baf8000000000 (f: 0.000000, d: 3.628800e+06)
[2024-08-22T11:21:27.444Z] LT  stderr v27=4022000000000000 (f: 0.000000, d: 9.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v28=4022000000000000 (f: 0.000000, d: 9.000000e+00)
[2024-08-22T11:21:27.444Z] LT  stderr v29=414baf8000000000 (f: 0.000000, d: 3.628800e+06)
[2024-08-22T11:21:27.444Z] LT  stderr v30=000000037adf00b0 (f: 2061435008.000000, d: 7.384472e-314)
[2024-08-22T11:21:27.444Z] LT  stderr v31=0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
[2024-08-22T11:21:27.444Z] LT  stderr Module=/Users/jenkins/workspace/Test_openjdk23_j9_special.system_aarch64_mac_testList_4/jdkbinary/j2sdk-image/Contents/Home/lib/default/libj9vm29.dylib
[2024-08-22T11:21:27.444Z] LT  stderr Module_base_address=0000000101210000 Symbol=_ZN26VM_BytecodeInterpreterFull3runEP10J9VMThread
[2024-08-22T11:21:27.444Z] LT  stderr Symbol_address=0000000101280B50
[2024-08-22T11:21:27.444Z] LT  stderr Target=2_90_20240822_19 (Mac OS X 14.2.1)
[2024-08-22T11:21:27.444Z] LT  stderr CPU=aarch64 (8 logical CPUs) (0x400000000 RAM)
[2024-08-22T11:21:27.444Z] LT  stderr ----------- Stack Backtrace -----------
[2024-08-22T11:21:27.444Z] LT  stderr ---------------------------------------
[2024-08-22T11:21:27.445Z] LT  stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2024/08/22 07:21:25 - please wait.
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42830/)

**Comment by knn-k** [comment]
The grinder job above was successful, except for the one sub job (https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/3930/) that failed with "macaarch64rt5 was marked offline: Connection was broken".

**Comment by knn-k** [comment]
Similar issues on AArch64 Linux:
- NPE in DirectMethodHandleAccessor.invoke(): #19113
- "argument type mismatch" in DirectMethodHandleAccessor.invoke(): #16989

**Comment by knn-k** [comment]
Call stack of the failure in https://github.com/eclipse-openj9/openj9/issues/19105#issuecomment-2305660963:

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "load-0" J9VMThread:0x000000014B940100, omrthread_t:0x000000013B015A60, java/lang/Thread:0x0000000280424D70, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1C, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x000000028005F828)
3XMTHREADINFO1            (native thread ID:0x26BD62A, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x000000016FE48000, to:0x000000016FE8B000, size:0x43000)
3XMCPUTIME               CPU usage total: 11.887149000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=12288 (0x3000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/invoke/LambdaForm$NFI/0x000000000180d7f0.invoke_LL_L(LambdaForm$NFI)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$DMH/0x000000003b031020.invokeStatic(LambdaForm$DMH(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:1180)
4XESTACKTRACE                at java/lang/invoke/LambdaForm.interpretName(LambdaForm.java:959)
4XESTACKTRACE                at java/lang/invoke/LambdaForm.interpretWithArguments(LambdaForm.java:936)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$LFI/0x000000004af3d810.interpret_L(LambdaForm$LFI)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x000000004b8c6020.invokeExact_MT(LambdaForm$MH(Compiled Code))
4XESTACKTRACE                at jdk/internal/reflect/DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:153(Compiled Code))
4XESTACKTRACE                at jdk/internal/reflect/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:586(Compiled Code))
4XESTACKTRACE                at junit/framework/TestCase.runTest(TestCase.java:176(Compiled Code))
```

**Comment by knn-k** [comment]
Another [50x Grinder job](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42903/) was successful.

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_special.system_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_special.system_aarch64_mac_testList_1/105/)
```
[2025-08-01T06:02:29.011Z] Running test DaaLoadTest_all_special_5m_6 ...
[2025-08-01T06:02:29.011Z] ===============================================
[2025-08-01T06:02:29.011Z] DaaLoadTest_all_special_5m_6 Start Time: Thu Jul 31 23:02:28 2025 Epoch Time (ms): 1754028148956
[2025-08-01T06:02:29.011Z] variation: Mode121
[2025-08-01T06:02:29.889Z] JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs 

[2025-08-01T06:06:27.272Z] DLT testFailure: net.openj9.test.decimals.TestDecimalData: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2025-08-01T06:06:27.272Z] DLT java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2025-08-01T06:06:27.272Z] DLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:114)
[2025-08-01T06:06:27.272Z] DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-08-01T06:06:27.272Z] DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

[2025-08-01T06:06:27.272Z] DLT Caused by: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2025-08-01T06:06:27.272Z] DLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-08-01T06:06:27.272Z] DLT 	... 22 more
[2025-08-01T06:06:27.272Z] DLT testFailure: net.openj9.test.decimals.TestDecimalData: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2025-08-01T06:06:27.272Z] DLT java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2025-08-01T06:06:27.272Z] DLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:114)
[2025-08-01T06:06:27.272Z] DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)

[2025-08-01T06:06:27.272Z] DLT Caused by: java.lang.NullPointerException: Cannot invoke "jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.lang.Object, java.lang.Object[])" because "this" is null
[2025-08-01T06:06:27.272Z] DLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

```
