### ISSUE TITLE
OpenJDK java/util/concurrent/forkjoin/AsyncShutdownNowInvokeAnyRace.testInvokeAny() timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19106]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/124
jdk_util_1
java/util/concurrent/forkjoin/AsyncShutdownNowInvokeAnyRace.java
```
22:23:50  STDERR:
22:23:50  ------ stacktrace dump start ------
22:23:50  "main" prio=5 Id=2 WAITING
22:23:50  	at java.base@21.0.3-internal/java.lang.Object.waitImpl(Native Method)
22:23:50  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:255)
22:23:50  	at java.base@21.0.3-internal/java.lang.Object.wait(Object.java:221)
22:23:50  	at java.base@21.0.3-internal/java.lang.Thread.join(Thread.java:2102)
22:23:50  	at java.base@21.0.3-internal/java.lang.Thread.join(Thread.java:2178)
22:23:50  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:219)
22:23:50  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:317)
22:23:50  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:242)
22:23:50  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:71)
22:23:50  "JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE
22:23:50  "JIT Compilation Thread-001 Suspended" prio=10 Id=5 RUNNABLE
22:23:50  "JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE
22:23:50  "JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE
22:23:50  "JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE
22:23:50  "JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE
22:23:50  "JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE
22:23:50  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE
22:23:50  "JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING
22:23:50  "IProfiler" prio=5 Id=13 RUNNABLE
22:23:50  "Finalizer thread" prio=5 Id=14 RUNNABLE
22:23:50  "Concurrent Mark Helper" prio=1 Id=15 RUNNABLE
22:23:50  "GC Worker" prio=5 Id=16 RUNNABLE
22:23:50  "GC Worker" prio=5 Id=17 RUNNABLE
22:23:50  "GC Worker" prio=5 Id=18 RUNNABLE
22:23:50  "Attach API update file access time" prio=5 Id=21 TIMED_WAITING
22:23:50  	at java.base@21.0.3-internal/java.lang.Thread.sleepImpl(Native Method)
22:23:50  	at java.base@21.0.3-internal/java.lang.Thread.sleep(Thread.java:516)
22:23:50  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.AttachHandler$1.run(AttachHandler.java:348)
22:23:50  "Attach API wait loop" prio=10 Id=22 RUNNABLE
22:23:50  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
22:23:50  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
22:23:50  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
22:23:50  	at java.base@21.0.3-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
22:23:50  "pool-1-thread-1" prio=5 Id=23 TIMED_WAITING
22:23:50  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
22:23:50  	at java.base@21.0.3-internal/java.lang.Thread.run(Thread.java:1595)
22:23:50  "ForkJoinPool.commonPool-worker-1" prio=5 Id=401 WAITING
22:23:50  	at java.base@21.0.3-internal/jdk.internal.misc.Unsafe.park(Native Method)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1099)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
22:23:50  	at AsyncShutdownNowInvokeAnyRace.lambda$testInvokeAny$1(AsyncShutdownNowInvokeAnyRace.java:103)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
22:23:50  "AgentVMThread" prio=5 Id=582 RUNNABLE
22:23:50  	at java.management@21.0.3-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
22:23:50  	at java.management@21.0.3-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:693)
22:23:50  	at java.management@21.0.3-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:675)
22:23:50  	at AsyncShutdownNowInvokeAnyRace.dumpTestThreads(AsyncShutdownNowInvokeAnyRace.java:193)
22:23:50  	at AsyncShutdownNowInvokeAnyRace.testInvokeAny(AsyncShutdownNowInvokeAnyRace.java:125)
22:23:50  	at java.base@21.0.3-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
22:23:50  	at java.base@21.0.3-internal/java.lang.reflect.Method.invoke(Method.java:586)
22:23:50  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:23:50  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:23:50  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:23:50  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:23:50  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:23:50  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:23:50  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:23:50  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:23:50  	at java.base@21.0.3-internal/java.util.ArrayList.forEach(ArrayList.java:1596)
22:23:50  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
22:23:50  	at app//org.testng.TestRunner.run(TestRunner.java:585)
22:23:50  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:23:50  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:23:50  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:23:50  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:23:50  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:23:50  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:23:50  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:23:50  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:23:50  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
22:23:50  	at app//org.testng.TestNG.run(TestNG.java:1037)
22:23:50  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
22:23:50  	at java.base@21.0.3-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
22:23:50  	at java.base@21.0.3-internal/java.lang.reflect.Method.invoke(Method.java:586)
22:23:50  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
22:23:50  	at java.base@21.0.3-internal/java.lang.Thread.run(Thread.java:1595)
22:23:50  "ForkJoinPool-4569-worker-1" prio=5 Id=5150 RUNNABLE
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinPool.registerWorker(ForkJoinPool.java:1607)
22:23:50  	at java.base@21.0.3-internal/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:186)
22:23:50  ------ stacktrace dump end ------
22:23:50  java.lang.Exception: failures: 1
22:23:50  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:104)
22:23:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
22:23:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
22:23:50  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
22:23:50  	at java.base/java.lang.Thread.run(Thread.java:1595)
22:23:50  
22:23:50  JavaTest Message: Test threw exception: java.lang.Exception
22:23:50  JavaTest Message: shutting down test
22:23:50  
22:23:50  STDOUT:
22:23:50  test AsyncShutdownNowInvokeAnyRace.testInvokeAny(): failure
22:23:50  java.lang.AssertionError: invokeAny timed out, nTasks=3 rep=4568 threadsStarted=0
22:23:50  poolAtShutdownNow=null
22:23:50  poolAtTimeout=java.util.concurrent.ForkJoinPool@6622030b[Running, parallelism = 1, size = 1, active = 0, running = 0, steals = 3, tasks = 0, submissions = 0]
22:23:50  queuedTaskCount=0 queuedSubmissionCount=0
22:23:50  	at AsyncShutdownNowInvokeAnyRace.testInvokeAny(AsyncShutdownNowInvokeAnyRace.java:138)
22:23:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
22:23:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
22:23:50  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:23:50  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:23:50  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:23:50  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:23:50  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:23:50  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:23:50  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:23:50  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:23:50  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
22:23:50  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
22:23:50  	at org.testng.TestRunner.run(TestRunner.java:585)
22:23:50  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:23:50  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:23:50  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:23:50  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:23:50  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:23:50  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:23:50  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:23:50  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:23:50  	at org.testng.TestNG.runSuites(TestNG.java:1069)
22:23:50  	at org.testng.TestNG.run(TestNG.java:1037)
22:23:50  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
22:23:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
22:23:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
22:23:50  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
22:23:50  	at java.base/java.lang.Thread.run(Thread.java:1595)
22:23:50  Caused by: java.util.concurrent.TimeoutException
22:23:50  	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:579)
22:23:50  	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1021)
22:23:50  	at java.base/java.util.concurrent.ForkJoinPool.invokeAny(ForkJoinPool.java:3157)
22:23:50  	at AsyncShutdownNowInvokeAnyRace.testInvokeAny(AsyncShutdownNowInvokeAnyRace.java:112)
22:23:50  	... 28 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/40
jdk_util_1
java/util/concurrent/forkjoin/AsyncShutdownNowInvokeAnyRace.jav
```
01:23:56  "pool-1-thread-1" prio=5 Id=23 TIMED_WAITING
01:23:56  	at java.base@22-internal/jdk.internal.misc.Unsafe.park(Native Method)
01:23:56  	at java.base@22-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
01:23:56  	at java.base@22-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
01:23:56  	at java.base@22-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
01:23:56  	at java.base@22-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
01:23:56  	at java.base@22-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
01:23:56  	at java.base@22-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
01:23:56  	at java.base@22-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
01:23:56  	at java.base@22-internal/java.lang.Thread.run(Thread.java:1582)
01:23:56  "ClassByNameCache Reaper" prio=5 Id=26 WAITING
01:23:56  	at java.base@22-internal/java.lang.Object.waitImpl(Native Method)
01:23:56  	at java.base@22-internal/java.lang.Object.wait(Object.java:255)
01:23:56  	at java.base@22-internal/java.lang.Object.wait(Object.java:221)
01:23:56  	at java.base@22-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
01:23:56  	at java.base@22-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:109)
01:23:56  	at java.base@22-internal/java.io.ClassByNameCache$Reaper.run(ClassByNameCache.java:232)
01:23:56  	at java.base@22-internal/java.lang.Thread.run(Thread.java:1582)
01:23:56  "VirtualThread-unparker" prio=5 Id=637 TIMED_WAITING
01:23:56  	at java.base@22-internal/jdk.internal.misc.Unsafe.park(Native Method)
01:23:56  	at java.base@22-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
01:23:56  	at java.base@22-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
01:23:56  	at java.base@22-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
01:23:56  	at java.base@22-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
01:23:56  	at java.base@22-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
01:23:56  	at java.base@22-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
01:23:56  	at java.base@22-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
01:23:56  	at java.base@22-internal/java.lang.Thread.run(Thread.java:1582)
01:23:56  	at java.base@22-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
01:23:56  "AgentVMThread" prio=5 Id=709 RUNNABLE
01:23:56  	at java.management@22-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
01:23:56  	at java.management@22-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:693)
01:23:56  	at java.management@22-internal/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:675)
01:23:56  	at AsyncShutdownNowInvokeAnyRace.dumpTestThreads(AsyncShutdownNowInvokeAnyRace.java:193)
01:23:56  	at AsyncShutdownNowInvokeAnyRace.testInvokeAny(AsyncShutdownNowInvokeAnyRace.java:125)
01:23:56  	at java.base@22-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
01:23:56  	at java.base@22-internal/java.lang.reflect.Method.invoke(Method.java:586)
01:23:56  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
01:23:56  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
01:23:56  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
01:23:56  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
01:23:56  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
01:23:56  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
01:23:56  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
01:23:56  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
01:23:56  	at java.base@22-internal/java.util.ArrayList.forEach(ArrayList.java:1597)
01:23:56  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
01:23:56  	at app//org.testng.TestRunner.run(TestRunner.java:585)
01:23:56  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
01:23:56  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
01:23:56  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
01:23:56  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
01:23:56  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
01:23:56  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
01:23:56  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
01:23:56  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
01:23:56  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
01:23:56  	at app//org.testng.TestNG.run(TestNG.java:1037)
01:23:56  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
01:23:56  	at java.base@22-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
01:23:56  	at java.base@22-internal/java.lang.reflect.Method.invoke(Method.java:586)
01:23:56  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
01:23:56  	at java.base@22-internal/java.lang.Thread.run(Thread.java:1582)
01:23:56  ------ stacktrace dump end ------
01:23:56  java.lang.Exception: failures: 1
01:23:56  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:104)
01:23:56  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
01:23:56  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
01:23:56  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
01:23:56  	at java.base/java.lang.Thread.run(Thread.java:1582)
```

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_sanity.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_sanity.openjdk_s390x_linux_testList_1/14/)
```
[2025-03-17T20:01:08.482Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2025-03-17T20:01:08.482Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops -Xverbosegclog 

[2025-03-17T21:05:23.166Z] TEST: java/util/concurrent/forkjoin/AsyncShutdownNowInvokeAnyRace.java

[2025-03-17T21:05:23.180Z] STDOUT:
[2025-03-17T21:05:23.180Z] test AsyncShutdownNowInvokeAnyRace.testInvokeAny(): failure
[2025-03-17T21:05:23.180Z] java.lang.AssertionError: invokeAny timed out, nTasks=3 rep=4416 threadsStarted=1
[2025-03-17T21:05:23.180Z] poolAtShutdownNow=java.util.concurrent.ForkJoinPool@5282e72b[Running, parallelism = 1, size = 1, active = 1, running = 0, steals = 1, tasks = 0, submissions = 2]
[2025-03-17T21:05:23.180Z] poolAtTimeout=java.util.concurrent.ForkJoinPool@5282e72b[Terminated, parallelism = 1, size = 0, active = 0, running = 0, steals = 1, tasks = 0, submissions = 0]
[2025-03-17T21:05:23.180Z] queuedTaskCount=0 queuedSubmissionCount=0
[2025-03-17T21:05:23.180Z] 	at AsyncShutdownNowInvokeAnyRace.testInvokeAny(AsyncShutdownNowInvokeAnyRace.java:138)
[2025-03-17T21:05:23.180Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-03-17T21:05:23.180Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2025-03-17T21:05:23.180Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2025-03-17T21:05:23.180Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
[2025-03-17T21:05:23.180Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2025-03-17T21:05:23.180Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2025-03-17T21:05:23.180Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2025-03-17T21:05:23.180Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2025-03-17T21:05:23.180Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2025-03-17T21:05:23.180Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2025-03-17T21:05:23.180Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2025-03-17T21:05:23.180Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2025-03-17T21:05:23.180Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2025-03-17T21:05:23.180Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2025-03-17T21:05:23.180Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2025-03-17T21:05:23.181Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2025-03-17T21:05:23.181Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
[2025-03-17T21:05:23.181Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-03-17T21:05:23.181Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-03-17T21:05:23.181Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2025-03-17T21:05:23.181Z] 	at java.base/java.lang.Thread.run(Thread.java:1458)
[2025-03-17T21:05:23.181Z] Caused by: java.util.concurrent.TimeoutException
[2025-03-17T21:05:23.181Z] 	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1045)
[2025-03-17T21:05:23.181Z] 	at java.base/java.util.concurrent.ForkJoinTask$InvokeAnyRoot.invokeAny(ForkJoinTask.java:1799)
[2025-03-17T21:05:23.181Z] 	at java.base/java.util.concurrent.ForkJoinPool.invokeAny(ForkJoinPool.java:3349)
[2025-03-17T21:05:23.181Z] 	at AsyncShutdownNowInvokeAnyRace.testInvokeAny(AsyncShutdownNowInvokeAnyRace.java:112)
[2025-03-17T21:05:23.181Z] 	... 28 more

[2025-03-17T23:14:23.755Z] jdk_util_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/48975/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_1/386
