### ISSUE TITLE
jdk_container_0_FAILED Error: invalid configuration, cannot specify resource limits without cgroups v2 and --cgroup-manager=systemd

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19176]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_dev.openjdk_ppc64le_linux/3/)(`rhel7le-rtp-rt5-1`):
```
java version "17.0.11-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 17.0.11+6-202403161434 (build 17.0.11-beta+6-202403161434)
Eclipse OpenJ9 VM 17.0.11+6-202403161434 (build master-6b03a382a, JRE 17 Linux ppc64le-64-Bit Compressed References 20240316_625 (JIT enabled, AOT enabled)
OpenJ9   - 6b03a382a
OMR      - 1bf2ef421
JCL      - 66cf01060a based on jdk-17.0.11+6)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F625%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK17U_2024-03-16-14-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F625%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK17U_2024-03-16-14-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-16T15:26:00.858Z] variation: NoOptions
[2024-03-16T15:26:00.858Z] JVM_OPTIONS:  -Xverbosegclog 

[2024-03-16T15:29:00.526Z] TEST: jdk/internal/platform/docker/TestDockerMemoryMetrics.java

[2024-03-16T15:29:00.527Z] STDERR:
[2024-03-16T15:29:00.527Z]  stdout: [];
[2024-03-16T15:29:00.527Z]  stderr: [Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[2024-03-16T15:29:00.527Z] Error: invalid configuration, cannot specify resource limits without cgroups v2 and --cgroup-manager=systemd
[2024-03-16T15:29:00.527Z] ]
[2024-03-16T15:29:00.527Z]  exitValue = 125

[2024-03-16T15:31:41.650Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
[2024-03-16T15:31:41.650Z] --------------------------------------------------
[2024-03-16T15:31:47.353Z] Test results: passed: 7; failed: 5
[2024-03-16T15:32:48.978Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_dev.openjdk_ppc64le_linux/aqa-tests/TKG/output_17106027597481/jdk_container_0/report/html/report.html
[2024-03-16T15:32:48.978Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_dev.openjdk_ppc64le_linux/aqa-tests/TKG/output_17106027597481/jdk_container_0/work
[2024-03-16T15:32:48.978Z] Error: Some tests failed or other problems occurred.
[2024-03-16T15:32:48.978Z] -----------------------------------
[2024-03-16T15:32:48.978Z] jdk_container_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38872/)

**Comment by pshipton** [comment]
The testing passed on sles12le-rtp-rt1-1 and ubu20le-rtp-rt1-1. Failed on rhel7 machines (rhel7le-svl-rt5-1, rhel7le-svl-rt6-1, rhel7le-svl-rt7-1).

@llxia is this a test configuration error, should it avoid running on rhel7?

**Comment by llxia** [comment]
> is this a test configuration error, should it avoid running on rhel7?

I am not aware of such a requirement for jdk_container. 
The test also failed on xlinux rhel7: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38921/console
```
00:02:34.960  Exception in thread "main" java.lang.RuntimeException: Test failed! getFreeSwapSpaceSize returns -131072
00:02:34.960  	at GetFreeSwapSpaceSize.main(GetFreeSwapSpaceSize.java:54)
00:02:34.960  ];
00:02:34.960   stderr: []
00:02:34.960   exitValue = 1
00:02:34.960  
00:02:34.960  java.lang.RuntimeException: Expected to get exit value of [0]
00:02:34.960  
00:02:34.960  	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
00:02:34.960  	at TestGetFreeSwapSpaceSize.testGetFreeSwapSpaceSize(TestGetFreeSwapSpaceSize.java:72)
00:02:34.960  	at TestGetFreeSwapSpaceSize.main(TestGetFreeSwapSpaceSize.java:49)
00:02:34.960  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:02:34.960  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
00:02:34.960  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:02:34.960  	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
00:02:34.960  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
00:02:34.960  	at java.base/java.lang.Thread.run(Thread.java:857)
00:02:34.960  
00:02:34.960  JavaTest Message: Test threw exception: java.lang.RuntimeException
00:02:34.960  JavaTest Message: shutting down test
00:02:34.960  
00:02:34.960  
00:02:34.960  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
00:02:34.960  --------------------------------------------------
00:03:25.499  Test results: passed: 11; failed: 1
```
Unfortunately, Adoptium does not have rhel on plinux. They only have centos and ubuntu: https://ci.adoptium.net/job/Test_openjdk17_hs_dev.openjdk_ppc64le_linux/

@annaibm could you add a temporary exclude on rhel7 for now? See example: https://github.com/adoptium/TKG/blob/0c5e49d22d17f1b91e0cc054b6b8cd047497d1ac/examples/platformRequirements/playlist.xml#L100

**Comment by llxia** [comment]
Similar error on [cent8x86-svl-rt8-1.fyre.ibm.com](https://hyc-runtimes-jenkins.swg-devops.com/computer/cent8x86-svl-rt8-1.fyre.ibm.com):
[Grinder link](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39155/
)
```
08:41:06  openjdk version "17.0.11-internal" 2024-04-16
08:41:06  OpenJDK Runtime Environment (build 17.0.11-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxNightly)
08:41:06  Eclipse OpenJ9 VM (build master-a3f25b1faf5, JRE 17 Linux amd64-64-Bit Compressed References 20240322_708 (JIT enabled, AOT enabled)
08:41:06  OpenJ9   - a3f25b1faf5
08:41:06  OMR      - cbfcf7d9444
08:41:06  JCL      - ea48af27e19 based on jdk-17.0.11+7)
08:41:06  ];
08:41:06   stderr: [Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
08:41:06  Resource limits are not supported and ignored on cgroups V1 rootless systems
08:41:06  ]
08:41:06   exitValue = 0
08:41:06  
08:41:06  java.lang.RuntimeException: 'Memory Limit: 300.00M' missing from stdout/stderr 
08:41:06  
08:41:06  	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
08:41:06  	at TestDockerBasic.testXshowSettingsSystem(TestDockerBasic.java:71)
08:41:06  	at TestDockerBasic.main(TestDockerBasic.java:50)
08:41:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:41:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
08:41:06  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:41:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
08:41:06  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
08:41:06  	at java.base/java.lang.Thread.run(Thread.java:857)
08:41:06  
08:41:06  JavaTest Message: Test threw exception: java.lang.RuntimeException
08:41:06  JavaTest Message: shutting down test
08:41:06  
08:41:06  
08:41:06  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Memory Limit: 300.00M' missing from stdout/stderr
08:41:06  --------------------------------------------------
08:41:06  TEST: jdk/internal/platform/docker/TestDockerMemoryMetrics.java
```

**Comment by annaibm** [comment]
List of subtests with errors:
1.jdk/internal/platform/docker/TestDockerBasic.java.TestDockerBasic
```
openjdk version "17.0.11-internal" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxNightly)
Eclipse OpenJ9 VM (build master-a3f25b1faf5, JRE 17 Linux amd64-64-Bit Compressed References 20240322_708 (JIT enabled, AOT enabled)
OpenJ9   - a3f25b1faf5
OMR      - cbfcf7d9444
JCL      - ea48af27e19 based on jdk-17.0.11+7)
];
 stderr: [Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Resource limits are not supported and ignored on cgroups V1 rootless systems
]
 exitValue = 0

java.lang.RuntimeException: 'Memory Limit: 300.00M' missing from stdout/stderr 

	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
	at TestDockerBasic.testXshowSettingsSystem(TestDockerBasic.java:71)
	at TestDockerBasic.main(TestDockerBasic.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
	at java.base/java.lang.Thread.run(Thread.java:857)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test
```
2. jdk/internal/platform/docker/TestDockerMemoryMetrics.java.TestDockerMemoryMetrics
```
stdout: [[memory, 200m]
Exception in thread "main" java.lang.RuntimeException: Memory limit not equal, expected : [209715200], got : [-1]
	at MetricsMemoryTester.testMemoryLimit(MetricsMemoryTester.java:60)
	at MetricsMemoryTester.main(MetricsMemoryTester.java:37)
];
 stderr: [Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Resource limits are not supported and ignored on cgroups V1 rootless systems
]
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
	at TestDockerMemoryMetrics.testMemoryLimit(TestDockerMemoryMetrics.java:106)
	at TestDockerMemoryMetrics.testMemoryLimit(TestDockerMemoryMetrics.java:90)
	at TestDockerMemoryMetrics.main(TestDockerMemoryMetrics.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
	at java.base/java.lang.Thread.run(Thread.java:857)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test
```
3.[jdk/internal/platform/docker/TestGetFreeSwapSpaceSize.java.TestGetFreeSwapSpaceSize
```
Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]    
```
4.[jdk/internal/platform/docker/TestLimitsUpdating.java.TestLimitsUpdating
```
Execution failed: `main' threw exception: java.lang.RuntimeException: 'Runtime.availableProcessors: 2' missing from stdout/stderr 
```
5. jdk/internal/platform/docker/TestPidsLimit.java.TestPidsLimit 
```
Execution failed: `main' threw exception: java.lang.RuntimeException: assertEquals: expected Unlimited to equal 1000    
```

**Comment by llxia** [comment]
subtests are excluded via https://github.com/adoptium/aqa-tests/pull/5162
