### ISSUE TITLE
jdk_container_0_FAILED jdk/internal/platform/docker/TestLimitsUpdating.java OCI runtime error: the requested cgroup controller `cpu` is not available

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19174]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_dev.openjdk_aarch64_linux/18/)(`ubu22-aarch64-5`):
```
java version "17.0.11-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 17.0.11+6-202403161434 (build 17.0.11-beta+6-202403161434)
Eclipse OpenJ9 VM 17.0.11+6-202403161434 (build master-6b03a382a, JRE 17 Linux aarch64-64-Bit Compressed References 20240316_617 (JIT enabled, AOT enabled)
OpenJ9   - 6b03a382a
OMR      - 1bf2ef421
JCL      - 66cf01060a based on jdk-17.0.11+6)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F617%2Fibm-semeru-certified-jdk_aarch64_linux_JDK17U_2024-03-16-14-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9-IBM%2F617%2Fibm-semeru-certified-testimage_aarch64_linux_JDK17U_2024-03-16-14-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-16T15:25:28.903Z] variation: NoOptions
[2024-03-16T15:25:28.903Z] JVM_OPTIONS:  -Xverbosegclog 


[2024-03-16T15:42:18.022Z] TEST: jdk/internal/platform/docker/TestLimitsUpdating.java

[2024-03-16T15:42:18.024Z] [STDERR]
[2024-03-16T15:42:18.024Z] Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[2024-03-16T15:42:18.024Z] Error: OCI runtime error: the requested cgroup controller `cpu` is not available

[2024-03-16T15:42:18.054Z] STDERR:
[2024-03-16T15:42:18.054Z]  stdout: [];
[2024-03-16T15:42:18.054Z]  stderr: [Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[2024-03-16T15:42:18.054Z] Error: OCI runtime error: the requested cgroup controller `cpu` is not available
[2024-03-16T15:42:18.054Z] ]
[2024-03-16T15:42:18.054Z]  exitValue = 126
[2024-03-16T15:42:18.054Z] 
[2024-03-16T15:42:18.054Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2024-03-16T15:42:18.054Z] 
[2024-03-16T15:42:18.054Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:489)
[2024-03-16T15:42:18.054Z] 	at TestLimitsUpdating$1.run(TestLimitsUpdating.java:95)
[2024-03-16T15:42:18.054Z] 
[2024-03-16T15:42:18.054Z] TEST RESULT: Error. Agent error: java.lang.Exception: Agent 10 timed out with a timeout of 960 seconds; check console log for any additional details
[2024-03-16T15:42:18.054Z] --------------------------------------------------
[2024-03-16T15:42:18.054Z] Test results: passed: 10; failed: 1; error: 1
[2024-03-16T15:42:39.676Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_17106027283814/jdk_container_0/report/html/report.html
[2024-03-16T15:42:39.676Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_17106027283814/jdk_container_0/work
[2024-03-16T15:42:39.676Z] Error: Some tests failed or other problems occurred.
[2024-03-16T15:42:39.676Z] -----------------------------------
[2024-03-16T15:42:39.676Z] jdk_container_0_FAILED

```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38871/)

**Comment by pshipton** [comment]
The grinder ran on ubu20-aarch64-3, cent7-aarch64-1, cent7-aarch64-3, cent7-aarch64-5, cent7-aarch64-6, I notice the absence of Ubuntu 22, which is where the original failure occurred.
