### ISSUE TITLE
JDK24 serviceability_jvmti_j9_1_FAILED serviceability/jvmti/vthread/VThreadEventTest/VThreadEventTest.java FAILED: event count is wrong

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19191]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_aarch64_linux_rerun/3/)(`rhel9-aarch64-2`):
```
openjdk version "22-beta" 2024-03-19
IBM Semeru Runtime Open Edition 22+36-202403161604 (build 22-beta+36-202403161604)
Eclipse OpenJ9 VM 22+36-202403161604 (build master-6b03a382a, JRE 22 Linux aarch64-64-Bit Compressed References 20240316_22 (JIT enabled, AOT enabled)
OpenJ9   - 6b03a382a
OMR      - 1bf2ef421
JCL      - 86491e07d based on jdk-22+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=serviceability_jvmti_j9_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F22%2Fibm-semeru-open-jdk_aarch64_linux_JDK22U_2024-03-16-16-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F22%2Fibm-semeru-open-testimage_aarch64_linux_JDK22U_2024-03-16-16-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=22&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=3&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk22&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-17T01:00:41.805Z] variation: Mode650
[2024-03-17T01:00:41.805Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-17T01:05:58.192Z] TEST: serviceability/jvmti/vthread/VThreadEventTest/VThreadEventTest.java

[2024-03-17T01:05:58.193Z] Agent_OnAttach started
[2024-03-17T01:05:58.193Z] vthread events enabled
[2024-03-17T01:05:58.193Z] ThreadEnd cnt: 18 (expected: 18)
[2024-03-17T01:05:58.193Z] ThreadMount cnt: 14 (expected: 14)
[2024-03-17T01:05:58.193Z] ThreadUnmount cnt: 21 (expected: 22)
[2024-03-17T01:05:58.193Z] FAILED: unexpected count of ThreadUnmount events
[2024-03-17T01:05:58.193Z] STDERR:
[2024-03-17T01:05:58.193Z] java.lang.RuntimeException: FAILED: event count is wrong
[2024-03-17T01:05:58.193Z] 	at VThreadEventTest.main(VThreadEventTest.java:210)
[2024-03-17T01:05:58.193Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-17T01:05:58.193Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-17T01:05:58.193Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-03-17T01:05:58.193Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-03-17T01:05:58.193Z] 
[2024-03-17T01:05:58.193Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: FAILED: event count is wrong

[2024-03-17T01:05:58.193Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: FAILED: event count is wrong
[2024-03-17T01:05:58.193Z] --------------------------------------------------
[2024-03-17T01:06:00.448Z] Test results: passed: 158; failed: 1
[2024-03-17T01:06:17.612Z] Report written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_rerun/jvmtest/openjdk/report/html/report.html
[2024-03-17T01:06:17.612Z] Results written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_rerun/aqa-tests/TKG/output_17106372406082/serviceability_jvmti_j9_1/work
[2024-03-17T01:06:17.612Z] Error: Some tests failed or other problems occurred.
[2024-03-17T01:06:17.612Z] -----------------------------------
[2024-03-17T01:06:17.612Z] serviceability_jvmti_j9_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38923/) - https://github.com/eclipse-openj9/openj9/issues/19191#issuecomment-2009455554

**Comment by pshipton** [comment]
Grinder passed on rhel9-aarch64-2, rhel9-aarch64-5.

2 failures on ubu22-aarch64-5
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#no-vmcontinuations

4 failures on ubu22-aarch64-2
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#no-vmcontinuations

1 failures on sles15-aarch64-4
serviceability/jvmti/vthread/SuspendResumeAll/SuspendResumeAll.java#no-vmcontinuations

Since this failure is not reproduced, removing from the milestone plan.

**Comment by JasonFengJ9** [comment]
[JDK22 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_x86-64_linux_testList_1/38/)(`rhel9x86-rtp-rt5-1`)
```
[2024-04-26T01:23:55.334Z] variation: Mode650
[2024-04-26T01:23:55.334Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-04-26T01:28:13.136Z] TEST: serviceability/jvmti/vthread/VThreadEventTest/VThreadEventTest.java

[2024-04-26T01:28:13.136Z] Agent_OnAttach started
[2024-04-26T01:28:13.136Z] vthread events enabled
[2024-04-26T01:28:13.136Z] ThreadEnd cnt: 18 (expected: 18)
[2024-04-26T01:28:13.136Z] ThreadMount cnt: 14 (expected: 14)
[2024-04-26T01:28:13.136Z] ThreadUnmount cnt: 21 (expected: 22)
[2024-04-26T01:28:13.136Z] FAILED: unexpected count of ThreadUnmount events
[2024-04-26T01:28:13.136Z] STDERR:
[2024-04-26T01:28:13.136Z] java.lang.RuntimeException: FAILED: event count is wrong
[2024-04-26T01:28:13.136Z] 	at VThreadEventTest.main(VThreadEventTest.java:210)
[2024-04-26T01:28:13.136Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-04-26T01:28:13.136Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-04-26T01:28:13.136Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-04-26T01:28:13.136Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-04-26T01:28:13.136Z] 
[2024-04-26T01:28:13.136Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: FAILED: event count is wrong

[2024-04-26T01:28:13.137Z] --------------------------------------------------
[2024-04-26T01:28:15.166Z] Test results: passed: 158; failed: 1
[2024-04-26T01:28:28.345Z] Report written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_x86-64_linux_testList_1/jvmtest/openjdk/report/html/report.html
[2024-04-26T01:28:28.345Z] Results written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_17140946335637/serviceability_jvmti_j9_1/work
[2024-04-26T01:28:28.345Z] Error: Some tests failed or other problems occurred.
[2024-04-26T01:28:30.134Z] -----------------------------------
[2024-04-26T01:28:30.134Z] serviceability_jvmti_j9_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdknext_j9_extended.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/32/consoleFull)
```
22:46:48  TEST: serviceability/jvmti/vthread/VThreadEventTest/VThreadEventTest.java

22:46:48  FAILED: unexpected count of VirtualThreadUnmount events
22:46:48  STDERR:
22:46:48  java.lang.RuntimeException: FAILED: event count is wrong
22:46:48  	at VThreadEventTest.main(VThreadEventTest.java:148)
```

**Comment by babsingh** [comment]
Closing, this issue is fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/938 and https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/22, which have been merged.
