### ISSUE TITLE
testSCCMLTests1_openj9_0_FAILED Cannot remove shared cache "ShareClassesCMLTests" as there are JVMs still attached to the cache

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19199]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/612/)(`ubu24x86-beta-svl-rt2-1`):
```
java version "17.0.11-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 17.0.11+6-202403192324 (build 17.0.11-beta+6-202403192324)
Eclipse OpenJ9 VM 17.0.11+6-202403192324 (build master-7c9937b26, JRE 17 Linux amd64-64-Bit Compressed References 20240319_633 (JIT enabled, AOT enabled)
OpenJ9   - 7c9937b26
OMR      - 1bf2ef421
JCL      - db5ba535ed based on jdk-17.0.11+6)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=testSCCMLTests1_openj9_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.functional_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9-IBM%2F633%2Fibm-semeru-certified-jdk_x64_linux_JDK17U_2024-03-19-23-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-x64-openj9-IBM%2F633%2Fibm-semeru-certified-testimage_x64_linux_JDK17U_2024-03-19-23-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28centos6%7C%7Crhel6%29&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=648&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-20T00:55:01.093Z] Testing: Start: Cleanup: nonpersistent
[2024-03-20T00:55:01.093Z] Test start time: 2024/03/19 17:55:00 Pacific Standard Time
[2024-03-20T00:55:01.093Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent,destroy
[2024-03-20T00:55:01.093Z] Time spent starting: 2 milliseconds
[2024-03-20T00:55:01.093Z] Time spent executing: 129 milliseconds
[2024-03-20T00:55:01.093Z] Test result: FAILED
[2024-03-20T00:55:01.093Z]  [ERR] JVMSHRC012I Cannot remove shared cache "ShareClassesCMLTests" as there are JVMs still attached to the cache
[2024-03-20T00:55:01.093Z]  [ERR] JVMSHRC430I Failed to remove current generation of shared class cache "ShareClassesCMLTests"
[2024-03-20T00:55:01.093Z] >> Success condition was not found: [Output match: has been destroyed]
[2024-03-20T00:55:01.093Z] >> Success condition was not found: [Output match: is destroyed]
[2024-03-20T00:55:01.093Z] >> Success condition was not found: [Output match: Cache does not exist]
[2024-03-20T00:55:01.093Z] >> Failure condition was not found: [Output match: Unhandled Exception]
[2024-03-20T00:55:01.093Z] >> Failure condition was not found: [Output match: Exception:]
[2024-03-20T00:55:01.093Z] >> Failure condition was not found: [Output match: corrupt]
[2024-03-20T00:55:01.093Z] >> Failure condition was not found: [Output match: Processing dump event]

[2024-03-20T00:55:08.296Z] Testing: Test 26: CMVC 168131 : Create a non persistent cache
[2024-03-20T00:55:08.296Z] Test start time: 2024/03/19 17:55:08 Pacific Standard Time
[2024-03-20T00:55:08.296Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent -version
[2024-03-20T00:55:08.296Z] Time spent starting: 2 milliseconds
[2024-03-20T00:55:09.804Z] Time spent executing: 1325 milliseconds
[2024-03-20T00:55:09.804Z] Test result: FAILED
[2024-03-20T00:55:09.804Z]  [ERR] JVMSHRC508E Acquired a different semaphore than previously used with this cache. old semid=426018, new semid=426036
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP039I Processing dump event "corruptcache", detail "" at 2024/03/19 17:55:08 - please wait.
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/output_17108935549255/testSCCMLTests1_openj9_0/core.20240319.175508.2947772.0001.dmp' in response to an event
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/output_17108935549255/testSCCMLTests1_openj9_0/core.20240319.175508.2947772.0001.dmp
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/output_17108935549255/testSCCMLTests1_openj9_0/javacore.20240319.175508.2947772.0002.txt' in response to an event
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/output_17108935549255/testSCCMLTests1_openj9_0/javacore.20240319.175508.2947772.0002.txt
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/output_17108935549255/testSCCMLTests1_openj9_0/Snap.20240319.175508.2947772.0003.trc' in response to an event
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_testList_2/aqa-tests/TKG/output_17108935549255/testSCCMLTests1_openj9_0/Snap.20240319.175508.2947772.0003.trc
[2024-03-20T00:55:09.804Z]  [ERR] JVMDUMP013I Processed dump event "corruptcache", detail "".
[2024-03-20T00:55:09.804Z]  [ERR] JVMSHRC442E Shared cache "ShareClassesCMLTests" is corrupt. Corruption code is -19. Corrupt value is 0x0000000000068034. No new JVMs will be allowed to connect to the cache.
[2024-03-20T00:55:09.804Z]  [ERR]  	Existing JVMs can continue to function, but cannot update the cache.
[2024-03-20T00:55:09.804Z]  [ERR] JVMSHRC012I Cannot remove shared cache "ShareClassesCMLTests" as there are JVMs still attached to the cache
[2024-03-20T00:55:09.804Z]  [ERR] JVMSHRC840E Failed to start up the shared cache.
[2024-03-20T00:55:09.804Z]  [ERR] JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
[2024-03-20T00:55:09.804Z]  [ERR] Error: Could not create the Java Virtual Machine.
[2024-03-20T00:55:09.804Z]  [ERR] Error: A fatal exception has occurred. Program will exit.
[2024-03-20T00:55:09.804Z] >> Success condition was not found: [Output match: (java|openjdk|semeru) version]
[2024-03-20T00:55:09.804Z] >> Failure condition was not found: [Output match: Unhandled Exception]
[2024-03-20T00:55:09.804Z] >> Failure condition was not found: [Output match: Exception:]
[2024-03-20T00:55:09.804Z] >> Failure condition was found: [Output match: corrupt]
[2024-03-20T00:55:09.804Z] >> Failure condition was found: [Output match: Processing dump event]

[2024-03-20T00:55:27.874Z] com.oti.j9.exclude.XMLException: null(1492):C1 : Character data ended prematurely
[2024-03-20T00:55:27.874Z] 	at com.oti.j9.exclude.XMLParser.parseError(XMLParser.java:56)
[2024-03-20T00:55:27.874Z] 	at com.oti.j9.exclude.XMLParser._scan_cdata_or_eof(XMLParser.java:242)
[2024-03-20T00:55:27.874Z] 	at com.oti.j9.exclude.XMLParser.parseXML(XMLParser.java:444)
[2024-03-20T00:55:27.874Z] 	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:470)
[2024-03-20T00:55:27.874Z] 	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)
[2024-03-20T00:55:27.874Z] 	at TestConfigParser.runTests(TestConfigParser.java:78)
[2024-03-20T00:55:27.874Z] 	at MainTester.main(MainTester.java:106)
[2024-03-20T00:55:27.874Z] 
[2024-03-20T00:55:27.874Z] ---TEST RESULTS---
[2024-03-20T00:55:27.874Z] Number of PASSED tests: 81 out of 90
[2024-03-20T00:55:27.874Z] Number of FAILED tests: 9 out of 90
[2024-03-20T00:55:27.874Z] 
[2024-03-20T00:55:27.874Z] ---SUMMARY OF FAILED TESTS---
[2024-03-20T00:55:27.874Z] Start: Cleanup: nonpersistent
[2024-03-20T00:55:27.874Z] Test 26: CMVC 168131 : Create a non persistent cache
[2024-03-20T00:55:27.874Z] Test 28: CMVC 168131 : Re-create by failing buildid match
[2024-03-20T00:55:27.874Z] Test 30: CMVC 168131 : Cleanup
[2024-03-20T00:55:27.874Z] Test 31: CMVC 168131 : Create a non persistent cache
[2024-03-20T00:55:27.874Z] Test 32: CMVC 168131 : Ensure cache size is 32 MB
[2024-03-20T00:55:27.874Z] Test 33: CMVC 168131 : Re-create by failing buildid match
[2024-03-20T00:55:27.874Z] Test 34: CMVC 168131 : Ensure cache size is still 32 MB
[2024-03-20T00:55:27.874Z] Test 35: CMVC 168131 : Cleanup
[2024-03-20T00:55:27.874Z] -----------------------------
[2024-03-20T00:55:27.874Z] 
[2024-03-20T00:55:27.874Z] -----------------------------------
[2024-03-20T00:55:27.874Z] testSCCMLTests1_openj9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38967/)

**Comment by pshipton** [comment]
Failed 100% on ubu24x86-beta-svl-rt1-1, passed on other machines (ubu22x86-svl-rt3-1, ubu22x86-svl-rt8-1, rhel7x86-rtp-rt2-1, cent8x86-rtp-rt3-1).
@hangshao0 pls take a look.

**Comment by hangshao0** [comment]
`
[2024-03-20T00:55:01.093Z]  [ERR] JVMSHRC012I Cannot remove shared cache "ShareClassesCMLTests" as there are JVMs still attached to the cache`

This means number of attached process to the shared memory is not 0.

Tries a simple command 3 times, seems that `cacheInfo->nattach` value is garbage value (8717, 9215, 9696).

```
jenkins@ubu24x86-beta-svl-rt2-1:~/workspace$ java -Xtrace:print={j9shr.2317,j9prt.1052,j9prt.56-60} -Xshareclasses:nonpersistent,name=Cache0 -version
16:17:56.412*0x17000           j9prt.56       > j9shmem_stat entered, name = C290M11F1A64_memory_Cache0_G43L00
16:17:56.412 0x17000           j9prt.60       < j9shmem_stat exit - return success
16:17:56.413 0x17000           j9prt.56       > j9shmem_stat entered, name = C290M11F1A64_memory_Cache0_G43L00
16:17:56.413 0x17000           j9prt.60       < j9shmem_stat exit - return success
16:17:56.415 0x17000           j9shr.2317     < SH_OSCachesysv::getCacheStatsHelper: Exit. cacheInfo->name is Cache0, cacheInfo->os_shmid is 655627, cacheInfo->lastattach is 1711037876000, cacheInfo->lastdetach is 1711037874000, cacheInfo->nattach is 8717
...
jenkins@ubu24x86-beta-svl-rt2-1:~/workspace$ java -Xtrace:print={j9shr.2317,j9prt.1052,j9prt.56-60} -Xshareclasses:nonpersistent,name=Cache0 -version
16:17:58.419*0x17000           j9prt.56       > j9shmem_stat entered, name = C290M11F1A64_memory_Cache0_G43L00
16:17:58.419 0x17000           j9prt.60       < j9shmem_stat exit - return success
16:17:58.419 0x17000           j9prt.56       > j9shmem_stat entered, name = C290M11F1A64_memory_Cache0_G43L00
16:17:58.419 0x17000           j9prt.60       < j9shmem_stat exit - return success
16:17:58.421 0x17000           j9shr.2317     < SH_OSCachesysv::getCacheStatsHelper: Exit. cacheInfo->name is Cache0, cacheInfo->os_shmid is 655627, cacheInfo->lastattach is 1711037878000, cacheInfo->lastdetach is 1711037876000, cacheInfo->nattach is 9215
....
jenkins@ubu24x86-beta-svl-rt2-1:~/workspace$ java -Xtrace:print={j9shr.2317,j9prt.1052,j9prt.56-60} -Xshareclasses:nonpersistent,name=Cache0 -version
16:18:58.938*0x17000           j9prt.56       > j9shmem_stat entered, name = C290M11F1A64_memory_Cache0_G43L00
16:18:58.938 0x17000           j9prt.60       < j9shmem_stat exit - return success
16:18:58.939 0x17000           j9prt.56       > j9shmem_stat entered, name = C290M11F1A64_memory_Cache0_G43L00
16:18:58.939 0x17000           j9prt.60       < j9shmem_stat exit - return success
16:18:58.941 0x17000           j9shr.2317     < SH_OSCachesysv::getCacheStatsHelper: Exit. cacheInfo->name is Cache0, cacheInfo->os_shmid is 655627, cacheInfo->lastattach is 1711037938000, cacheInfo->lastdetach is 1711037878000, cacheInfo->nattach is 9696
```

While, on another machine,  `cacheInfo->nattach` is consistent.

**Comment by pshipton** [comment]
We need to figure out what's wrong with Ubuntu 24_04, or this particular machine. It's still in beta, but we're getting close to the release date.
- are configuration changes required?
- are code changes required to support Ubuntu 24_04?
- is it no longer possible to support Ubuntu 24_04 for non-persistent caches?

I didn't check what build we have installed, but [here](https://cdimage.ubuntu.com/daily-live/current/) I see a daily build.

**Comment by hangshao0** [comment]
Using ipcs, I see the `nattch` of the shared memory is 12116, even when there is no java process attached to it.

```
key        shmid      owner      perms      bytes      nattch     status
0x6100771b 655627     jenkins    600        314572800  12116
```
Then I run a simple command:
`java -Xtrace:print={j9shr.2317,j9prt.56,j9prt.57-60} -Xshareclasses:nonpersistent,name=Cache0 -version`
After it finished, ipsc shows the `nattch` becomes 12742
```
key        shmid      owner      perms      bytes      nattch     status
0x6100771b 655627     jenkins    600        314572800  12742
```

I tried using `ipcrm -m` to remove the shared memory, but it cannot be removed. I guess it is because nattch > 0. It is marked as `dest`, which means it will be deleted when all processes attached to it terminated. 

```
------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status
0x00000000 655627     jenkins    600        314572800  12742      dest
```
It looks to me the `nattch` reported by the OS is incorrect. It is hard for me to believe there is 12742 process attached to this shared memory. 

There are over 200 shared memory segments that are marked 'dest', but not deleted on this machine.

**Comment by pshipton** [comment]
Added a note to infrastructure/issues/8836

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_sanity.functional_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_testList_5/194/)(`rtj-rhel10le-rtp-test-dni04`)
```
[2026-06-18T15:53:30.069Z] Running test testSCCMLTests1_openj9_0 ...
[2026-06-18T15:53:30.069Z] ===============================================
[2026-06-18T15:53:30.069Z] testSCCMLTests1_openj9_0 Start Time: Thu Jun 18 11:53:25 2026 Epoch Time (ms): 1781798005505
[2026-06-18T15:53:30.069Z] variation: Mode110
[2026-06-18T15:53:30.070Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

[2026-06-18T15:53:35.517Z] Testing: Test 30: CMVC 168131 : Cleanup
[2026-06-18T15:53:35.517Z] Test start time: 2026/06/18 11:53:31 Eastern Standard Time
[2026-06-18T15:53:35.520Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_testList_5/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent,destroy
[2026-06-18T15:53:35.520Z] Time spent starting: 1 milliseconds
[2026-06-18T15:53:35.520Z] Time spent executing: 27 milliseconds
[2026-06-18T15:53:35.520Z] Test result: FAILED
[2026-06-18T15:53:35.520Z]  [ERR] JVMSHRC012I Cannot remove shared cache "ShareClassesCMLTests" as there are JVMs still attached to the cache
[2026-06-18T15:53:35.520Z]  [ERR] JVMSHRC430I Failed to remove current generation of shared class cache "ShareClassesCMLTests"

[2026-06-18T15:53:44.291Z] Number of FAILED tests: 4 out of 114
[2026-06-18T15:53:44.291Z] 
[2026-06-18T15:53:44.291Z] ---SUMMARY OF FAILED TESTS---
[2026-06-18T15:53:44.291Z] Test 30: CMVC 168131 : Cleanup
[2026-06-18T15:53:44.291Z] Test 32: CMVC 168131 : Ensure cache size is 32 MB
[2026-06-18T15:53:44.291Z] Test 34: CMVC 168131 : Ensure cache size is still 32 MB
[2026-06-18T15:53:44.291Z] Test 35: CMVC 168131 : Cleanup
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/60855/) - passed

**Comment by hangshao0** [comment]
For https://github.com/eclipse-openj9/openj9/issues/19199#issuecomment-4772173063

The previous command is running 
`[2026-06-18T15:53:35.516Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_testList_5/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent,testBadBuildId -version`

If I run (my jdk is java 11, but the result on jdk 17 is the same)
```
java -Xshareclasses:name=test,nonpersistent -verbose:init -version
...
Running initialization stage VM_INITIALIZATION_COMPLETE
        for library j9jit29...
                completed with rc=0 in 109692 nano sec.
        for library j9bcv29...
                completed with rc=0 in 420 nano sec.
        for library j9gc29...
                completed with rc=0 in 815 nano sec.
        for library j9dyn29...
                completed with rc=0 in 348 nano sec.
        for library j9vrb29...
                completed with rc=0 in 1271 nano sec.
        for library j9dmp29...
                completed with rc=0 in 3803 nano sec.
        for library j9trc29...
                completed with rc=0 in 78239 nano sec.
        for library j9shr29...
                completed with rc=0 in 390 nano sec.
        for library j9jvmti29...
                completed with rc=0 in 1863 nano sec.
        for library jclse29...
                completed with rc=0 in 1501 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 54 nano sec.
        for library VMInitStages...
                completed with rc=0 in 388 nano sec.
        for library threadInitStages...
                completed with rc=0 in 56 nano sec.

Checking results for stage VM_INITIALIZATION_COMPLETE
openjdk version "11.0.32-internal" 2026-07-21
OpenJDK Runtime Environment (build 11.0.32-internal+0-adhoc.hangshao.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build 11.0.32-internal+0-adhoc.hangshao.openj9-openjdk-jdk11-master-27c6817179, JRE 11 Linux amd64-64-Bit Compressed References 20260622_000000 (JIT enabled, AOT enabled)
OpenJ9   - 6874da7665
OMR      - a39ef2b2c
JCL      - 89d5355c21 based on jdk-11.0.32+6)

Running shutdown stage JVM_EXIT_STAGE...
        for library j9jvmti29...
                completed with rc=0 in 4283 nano sec.
        for library j9jit29...
                completed with rc=0 in 138317 nano sec.
        for library j9bcv29...
                completed with rc=0 in 410 nano sec.
        for library j9gc29...
                completed with rc=0 in 616 nano sec.
        for library j9dyn29...
                completed with rc=0 in 126 nano sec.
        for library j9vrb29...
                completed with rc=0 in 13447 nano sec.
        for library j9dmp29...
                completed with rc=0 in 594 nano sec.
        for library j9trc29...
                completed with rc=0 in 12375 nano sec.
        for library j9shr29...
                completed with rc=0 in 900640 nano sec.
        for library jclse29...
                completed with rc=0 in 410 nano sec.
        for library zeroInitStages...
                completed with rc=0 in 321 nano sec.
        for library VMInitStages...
                completed with rc=0 in 350 nano sec.
        for library threadInitStages...
                completed with rc=0 in 29 nano sec.
```
So the last stage is `JVM_EXIT_STAGE`, we never reach https://github.com/eclipse-openj9/openj9/blob/a327f43816b64330ae839e1478768246b5efc789/runtime/shared/shrclssup.c#L498-L501
where the attach count is decremented.

**Comment by hangshao0** [comment]
> So the last stage is JVM_EXIT_STAGE

Moving `j9shr_shutdown()` does not work. There could still be class loading happening in the `JVM_EXIT_STAGE`, calling `j9shr_shutdown()` in this stage leads to various crashes in the class loading code path.

**Comment by hangshao0** [comment]
There is a broader issue in Java 11+ shutdown:

```
java -verbose:shutdown -Xtrace:print={j9vm.393} -version
openjdk version "11.0.32-internal" 2026-07-21
OpenJDK Runtime Environment (build 11.0.32-internal+0-adhoc.hangshao.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build 11.0.32-internal+0-adhoc.hangshao.openj9-openjdk-jdk11-master-27c6817179, JRE 11 Linux amd64-64-Bit Compressed References 20260622_000000 (JIT enabled, AOT enabled)
OpenJ9   - 6874da7665
OMR      - a39ef2b2c
JCL      - 89d5355c21 based on jdk-11.0.32+6)
Thread "Common-Cleaner" is still alive after running the shutdown hooks.
15:18:38.173*0x21f00            j9vm.393    * - protectedDestroyJavaVM terminateRemainingThreads failed
```

There is a "Common-Cleaner" thread which is created and set as daemon by JCL https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/4448d7a9923461868721f0725b39b54fca1a6f41/src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java#L117

`terminateRemainingThreads()` does not terminate daemon threads. If there is one, this function will have a non-zero return value. 


So the caller will run exit stage and then return without calling `freeJavaVM()` https://github.com/eclipse-openj9/openj9/blob/f8b93be2561ec5e221bbe1ad6f8e3dd1c3108848/runtime/vm/jniinv.c#L413

(`INTERPRETER_SHUTDOWN, LIBRARIES_ONUNLOAD`, `HEAP_STRUCTURES_FREED`, and `GC_SHUTDOWN_COMPLETE` are triggered by `freeJavaVM()`. Java 8 does not have the daemon "Common-Cleaner" thread.)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.functional_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_testList_2/1097/consoleFull)
```
12:04:23  Running test testSCCMLTests6_1 ...
12:04:23  ===============================================
12:04:23  testSCCMLTests6_1 Start Time: Mon Jul 13 12:04:23 2026 Epoch Time (ms): 1783958663010
12:04:23  variation: Mode610
12:04:23  JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 

12:04:34  Testing: Test 207 cleanup: destroy non-persistent cache
12:04:34  Test start time: 2026/07/13 12:04:33 Eastern Standard Time
12:04:34  Running command: "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64le_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent,destroy
12:04:34  Time spent starting: 1 milliseconds
12:04:34  Time spent executing: 25 milliseconds
12:04:34  Test result: FAILED
12:04:34   [ERR] JVMSHRC012I Cannot remove shared cache "ShareClassesCMLTests" as there are JVMs still attached to the cache
12:04:34   [ERR] JVMSHRC430I Failed to remove current generation of shared class cache "ShareClassesCMLTests"
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64le_linux_Nightly_testList_0/1185
testSCCMLTests6_1
```
20:20:54  Testing: Test 207 cleanup: destroy non-persistent cache
20:20:54  Test start time: 2026/09/22 00:20:54 Coordinated Universal Time
20:20:54  Running command: "/home/jenkins/workspace/Test_openjdk17_j9_extended.functional_ppc64le_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent,destroy
20:20:54  Time spent starting: 2 milliseconds
20:20:54  Time spent executing: 20 milliseconds
20:20:54  Test result: FAILED
20:20:54   [ERR] JVMSHRC012I Cannot remove shared cache "ShareClassesCMLTests" as there are JVMs still attached to the cache
20:20:54   [ERR] JVMSHRC430I Failed to remove current generation of shared class cache "ShareClassesCMLTests"
20:20:54  >> Success condition was not found: [Output match: has been destroyed]
20:20:54  >> Success condition was not found: [Output match: is destroyed]
20:20:54  >> Success condition was not found: [Output match: Cache does not exist]
20:20:54  >> Failure condition was not found: [Output match: Unhandled Exception]
20:20:54  >> Failure condition was not found: [Output match: Exception:]
20:20:54  >> Failure condition was not found: [Output match: corrupt]
20:20:54  >> Failure condition was not found: [Output match: Processing dump event]
```
