### ISSUE TITLE
JDK22 openJcePlusTests_0_FAILED Running gcm_oneReadByteCorrupt test Fail. No exception thrown.

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19205]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.functional_s390x_linux_testList_0/15/)(`rhel8s390x-svl-rt9-1`):
```
openjdk version "22-beta" 2024-03-19
IBM Semeru Runtime Open Edition 22+36-202403200230 (build 22-beta+36-202403200230)
Eclipse OpenJ9 VM 22+36-202403200230 (build master-7c9937b26, JRE 22 Linux s390x-64-Bit Compressed References 20240320_23 (JIT enabled, AOT enabled)
OpenJ9   - 7c9937b26
OMR      - 1bf2ef421
JCL      - 4803bcabd based on jdk-22+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=openJcePlusTests_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk22_j9_extended.functional_s390x_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-s390x-openj9%2F23%2Fibm-semeru-open-jdk_s390x_linux_JDK22U_2024-03-20-00-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-s390x-openj9%2F23%2Fibm-semeru-open-testimage_s390x_linux_JDK22U_2024-03-20-00-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=22&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk22&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=15&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-20T04:09:23.342Z] variation: NoOptions
[2024-03-20T04:09:23.342Z] JVM_OPTIONS:  

[2024-03-20T04:09:23.343Z] TESTING:
[2024-03-20T04:09:25.309Z] Buildfile: /home/jenkins/workspace/Test_openjdk22_j9_extended.functional_s390x_linux_testList_0/jvmtest/functional/OpenJcePlusTests/test.xml

[2024-03-20T04:24:16.798Z]      [test]     [junit] Running gcm_oneReadByteCorrupt test
[2024-03-20T04:24:16.798Z]      [test]     [junit]   Fail. No exception thrown.

[2024-03-20T04:40:39.436Z]      [test]     [junit] Result(should be false): false
[2024-03-20T04:45:09.006Z]      [test]     [junit] Tests run: 1705, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2,082.67 sec
[2024-03-20T04:45:09.006Z]      [test] 
[2024-03-20T04:45:09.006Z]      [test] BUILD FAILED
[2024-03-20T04:45:09.006Z]      [test] /home/jenkins/workspace/Test_openjdk22_j9_extended.functional_s390x_linux_testList_0/jvmtest/functional/OpenJcePlusTests/test.xml:44: Test ibm.jceplus.junit.TestAll failed
[2024-03-20T04:45:09.006Z]      [test] 
[2024-03-20T04:45:09.006Z]      [test] Total time: 35 minutes 34 seconds
[2024-03-20T04:45:09.006Z] 
[2024-03-20T04:45:09.006Z] BUILD FAILED
[2024-03-20T04:45:09.006Z] /home/jenkins/workspace/Test_openjdk22_j9_extended.functional_s390x_linux_testList_0/jvmtest/functional/OpenJcePlusTests/test.xml:33: Java returned: 1
[2024-03-20T04:45:09.006Z] 
[2024-03-20T04:45:09.006Z] Total time: 35 minutes 37 seconds
[2024-03-20T04:45:09.006Z] -----------------------------------
[2024-03-20T04:45:09.006Z] openJcePlusTests_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38987/)

**Comment by pshipton** [comment]
Grinder succeeded 10/10 on ubu22s390x-svl-rt9-1, ubu22s390x-svl-rt4-1.

Failed 1/10 on ubu22s390x-svl-rt5-1
Failed 1/10 on rhel9s390x-svl-rt3-1
Failed 1/10 on ubu22s390x-rt-1

I noticed the following in the output, but it doesn't cause any failure as the passing runs have it too. I'm not sure what the cause of the `Errors: 1` is. I've tried searching the output for different things, but didn't find anything.
```
20:07:43       [test]     [junit] Running gcm_oneReadByteCorrupt test
20:07:43       [test]     [junit]   Fail. No exception thrown.
```

@jasonkatonica pls take a look.

**Comment by pshipton** [comment]
The failures aren't in the 0.44 builds but I assume openJcePlus is the same. Added to the 0.44 milestone for now.

**Comment by KostasTsiounis** [comment]
> Grinder succeeded 10/10 on ubu22s390x-svl-rt9-1, ubu22s390x-svl-rt4-1.
> 
> Failed 1/10 on ubu22s390x-svl-rt5-1 Failed 1/10 on rhel9s390x-svl-rt3-1 Failed 1/10 on ubu22s390x-rt-1
> 
> The following is in the output, but it doesn't cause any failure as the passing runs have it too. I'm not sure what the cause of the `Errors: 1` is. I've tried searching the output for different things, but didn't find anything.
> 
> ```
> 20:07:43       [test]     [junit] Running gcm_oneReadByteCorrupt test
> 20:07:43       [test]     [junit]   Fail. No exception thrown.
> ```
> 
> @jasonkatonica pls take a look.

The thing that is stated here as a failure is not actually was is causing this intermittent failure. This is a test that needs to be amended, as it is not actually testing what we mean it to, which is the reason why it is only printing this message, instead of throwing an exception. An issue has been opened on our end to fix that.

The issue that is actually causing these failures is: 
```
java.security.spec.InvalidKeySpecException: Inappropriate key specification: Failed to create XEC private key
	at openjceplus/com.ibm.crypto.plus.provider.XDHKeyFactory.engineGeneratePrivate(XDHKeyFactory.java:112)
	at java.base/java.security.KeyFactory.generatePrivate(KeyFactory.java:383)
	at ibm.jceplus.junit.base.BaseTestXDH.runBasicTest(BaseTestXDH.java:246)
	at ibm.jceplus.junit.base.BaseTestXDH.runBasicTests(BaseTestXDH.java:208)
	at ibm.jceplus.junit.base.BaseTestXDH.testXDH_runBasicTests(BaseTestXDH.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

We have noticed that happening intermittently throughout our runs and have opened up an issue (see https://github.ibm.com/runtimes/jit-crypto/issues/386) to figure it out and resolve it.

**Comment by KostasTsiounis** [comment]
I don't think this is a stop ship issue at the moment. What do you think @jasonkatonica ?

**Comment by pshipton** [comment]
Removed it from the milestone plan.

**Comment by jasonkatonica** [comment]
> I don't think this is a stop ship issue at the moment. What do you think @jasonkatonica ?

Agreed, I dont believe this is a stop ship issue at this time.

**Comment by JasonFengJ9** [comment]
[JDK11 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_x86-64_windows_testList_0/509/)(`win19x86-svl-rt5-1`)
```
openjdk version "11.0.23" 2024-04-16
IBM Semeru Runtime Open Edition 11.0.23.0-m2 (build 11.0.23+7)
Eclipse OpenJ9 VM 11.0.23.0-m2 (build v0.44.0-release-8b079b5c1, JRE 11 Windows Server 2019 amd64-64-Bit Compressed References 20240411_884 (JIT enabled, AOT enabled)
OpenJ9   - 8b079b5c1
OMR      - 254af5a04
JCL      - 0f9c69e64d based on jdk-11.0.23+7)

[2024-04-11T21:02:02.977Z]      [test]     [junit] Running gcm_oneReadByteCorrupt test
[2024-04-11T21:02:02.977Z]      [test]     [junit]   Fail. No exception thrown.

[2024-04-11T21:20:21.799Z]      [test]     [junit] Tests run: 1698, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1,213.262 sec
[2024-04-11T21:20:21.799Z]      [test] 
[2024-04-11T21:20:21.799Z]      [test] BUILD FAILED
[2024-04-11T21:20:21.799Z]      [test] C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.functional_x86-64_windows_testList_0\jvmtest\functional\OpenJcePlusTests\test.xml:44: Test ibm.jceplus.junit.TestAll failed
[2024-04-11T21:20:21.799Z]      [test] 
[2024-04-11T21:20:21.799Z]      [test] Total time: 21 minutes 37 seconds
[2024-04-11T21:20:21.799Z] 
[2024-04-11T21:20:21.799Z] BUILD FAILED
[2024-04-11T21:20:21.799Z] C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.functional_x86-64_windows_testList_0\jvmtest\functional\OpenJcePlusTests\test.xml:33: Java returned: 1
[2024-04-11T21:20:21.799Z] 
[2024-04-11T21:20:21.799Z] Total time: 21 minutes 41 seconds
[2024-04-11T21:20:21.799Z] -----------------------------------
[2024-04-11T21:20:21.799Z] openJcePlusTests_0_FAILED
```

**Comment by pshipton** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.functional_x86-64_windows_testList_1/549/

**Comment by JasonFengJ9** [comment]
[JDK11 ppc64_aix_fips140_3_openjceplusfips](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_ppc64_aix_fips140_3_openjceplusfips/5/)(`p10aix134`)
```
[2024-10-05T04:09:16.634Z] variation: NoOptions
[2024-10-05T04:09:16.634Z] JVM_OPTIONS:   -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS

[2024-10-05T04:39:45.897Z] [ERROR] Errors: 
[2024-10-05T04:39:45.897Z] [ERROR]   TestXDH>BaseTestXDH.testXDH_runBasicTests:60->BaseTestXDH.runBasicTests:211->BaseTestXDH.runBasicTest:246 � InvalidKeySpec Inappropriate key specification: Failed to create XEC private key

[2024-10-05T04:39:45.897Z] openJcePlusTests_0_FAILED
```

**Comment by jasonkatonica** [comment]
We have addressed the issue stated above :
```
20:07:43       [test]     [junit] Running gcm_oneReadByteCorrupt test
20:07:43       [test]     [junit]   Fail. No exception thrown.
```
with a test case update in various OpenJCEPlus releases. [This PR](https://github.com/IBM/OpenJCEPlus/pull/227) is the updates made to the main branch such that we no longer see this error message or the word fail among other improvements made to this specific test.

The intermittant failure with the following:
```
TestXDH>BaseTestXDH.testXDH_runBasicTests:60->BaseTestXDH.runBasicTests:211->BaseTestXDH.runBasicTest:246 � InvalidKeySpec Inappropriate key specification: Failed to create XEC private key
```
was also fixed with a OpenJCEPlus update. There was a provider encoding parsing error that was fixed with [this PR](https://github.com/IBM/OpenJCEPlus/pull/269), once merged we expect that this failure would also be resolved.

**Comment by pshipton** [comment]
@jasonkatonica just a reminder there is a `test excluded` label so after the fixes are merged and before this is closed the test needs to be unexcluded.

**Comment by jasonkatonica** [comment]
OK makes sense there is a `test excluded` tag. I hadnt noticed it before. 

In this particular case the various tests reported above were never excluded from running. One of the test failures was very intermittent when it failed ( `BaseTestXDH` ) the other test ( message `Fail. No exception thrown.` ) never really failed, it just did not look correct in the log. So at this point there is no additional updates required to unexclude the tests.
