### ISSUE TITLE
Can't build Windows

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19210]
https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_windows_Nightly/725
https://openj9-jenkins.osuosl.org/job/Build_JDK22_x86-64_windows_Nightly/40
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_windows_OpenJDK11/107
https://openj9-jenkins.osuosl.org/job/Build_JDK21_x86-64_windows_OpenJDK21/21/

https://openj9-jenkins.osuosl.org/job/Build_JDK21_x86-64_windows_Nightly/200
```
18:17:34  Writing generated classes to f:/users/jenkins/workspace/build_jdk21_x86-64_windows_nightly/build/windows-x86_64-server-release/support/gensrc/openj9.dtfj/com/ibm/j9ddr/vm29/pointer/generated
18:17:34  Exception in thread "main" java.lang.IllegalArgumentException: The structure [J9BuildFlags] was not found
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.StructureReader.getConstants(StructureReader.java:536)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.StructureReader.getConstantValue(StructureReader.java:1141)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.StructureReader.getBuildFlagValue(StructureReader.java:1152)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.StructureReader.getAliasVersion(StructureReader.java:452)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.StructureReader.applyAliases(StructureReader.java:222)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.StructureReader.<init>(StructureReader.java:120)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.tools.ClassGenerator.readBlob(ClassGenerator.java:93)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.tools.ClassGenerator.run(ClassGenerator.java:174)
18:17:34  	at openj9.dtfj/com.ibm.j9ddr.tools.ClassGenerator.main(ClassGenerator.java:79)
18:17:34  Writing generated classes to f:/users/jenkins/workspace/build_jdk21_x86-64_windows_nightly/build/windows-x86_64-server-release/support/gensrc/openj9.dtfj/com/ibm/j9ddr/vm29/structure
18:17:34  make[4]: *** [/cygdrive/f/users/jenkins/workspace/build_jdk21_x86-64_windows_nightly/closed/DDR.gmk:116: /cygdrive/f/users/jenkins/workspace/build_jdk21_x86-64_windows_nightly/build/windows-x86_64-server-release/support/ddr/classes.done] Error 1
```

**Comment by pshipton** [comment]
Changes from previous build
https://github.com/eclipse-openj9/openj9/compare/3b697e1318...f2c434f2126
https://github.com/eclipse-openj9/openj9-omr/compare/1bf2ef421caa...73f2f2035d3

**Comment by keithc-ca** [comment]
I suspect this class of error is significant:
```
[2024-03-21T10:40:47.666Z] omrddr/__/build/windows-x86_64-normal-server-release/vm/runtime/omr/omrcfg.stub.h(3): fatal error C1083: Cannot open include file: '/cygdrive/f/users/jenkins/workspace/build_jdk11_x86-64_windows_openjdk11/build/windows-x86_64-normal-server-release/vm/runtime/omr/omrcfg.h': No such file or directory
```
I see the same in a local build.
