### ISSUE TITLE
jdk_io_1_FAILED java/io/Serializable/subclassGC/SubclassGC.java java.lang.Error

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19246]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_2/11/)(`rhel7le-rtp-rt3-1`):
```
java version "21.0.3-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 21.0.3+7-202403280004 (build 21.0.3-beta+7-202403280004)
Eclipse OpenJ9 VM 21.0.3+7-202403280004 (build master-87d656319, JRE 21 Linux ppc64le-64-Bit Compressed References 20240328_133 (JIT enabled, AOT enabled)
OpenJ9   - 87d656319
OMR      - 6391cf4bb
JCL      - 29b3f94dd based on jdk-21.0.3+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_io_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_extended.openjdk_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F133%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK21U_2024-03-27-23-31.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F133%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK21U_2024-03-27-23-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=45&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-28T01:02:40.892Z] variation: Mode650
[2024-03-28T01:02:40.892Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-28T01:06:37.993Z] TEST: java/io/Serializable/subclassGC/SubclassGC.java

[2024-03-28T01:06:37.994Z] STDERR:
[2024-03-28T01:06:37.994Z] Start Garbage Collection right now
[2024-03-28T01:06:37.994Z] java.lang.Error
[2024-03-28T01:06:37.994Z] 	at SubclassGC.main(SubclassGC.java:82)
[2024-03-28T01:06:37.994Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-03-28T01:06:37.994Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-03-28T01:06:37.994Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-03-28T01:06:37.994Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-03-28T01:06:37.994Z] 
[2024-03-28T01:06:37.994Z] JavaTest Message: Test threw exception: java.lang.Error

[2024-03-28T01:07:25.148Z] jdk_io_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39334/) - https://github.com/eclipse-openj9/openj9/issues/19246#issuecomment-2028515579

Also seen [JDK22 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_ppc64le_linux_testList_2/15/)(`rhel8le-rtp-rt8-1`), [JDK22 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_s390x_linux_testList_0/13/)(`sles15s390x-svl-rt8-1`)

**Comment by pshipton** [comment]
Grinder passed on rhel7le-svl-rt6-1, rhel7le-rtp-rt7-1, ubu20le-svl-rt4-1, ubu20le-svl-rt5-1.
Failed 1/10 on rhel8le-svl-rt7-1.

The test is waiting for 1000ms after a System.gc() for a weak reference to be added to the ReferenceQueue, but it timed out.

@dmitripivkine fyi

**Comment by dmitripivkine** [comment]
I guess it might be another manifestation of https://github.com/eclipse-openj9/openj9/issues/9651, object pointer is stored in the hard root. Currently there is no results stored for this exception, so nothing to look at.
@pshipton would you please help with command line to get a system core?

**Comment by dmitripivkine** [comment]
There were no weak references enqueued for last GC. However there has been number of references enqueued before:
```
  <references type="weak" candidates="66" cleared="10" enqueued="10" />
  <references type="weak" candidates="105" cleared="15" enqueued="15" />
  <references type="weak" candidates="162" cleared="24" enqueued="24" />
  <references type="weak" candidates="114" cleared="18" enqueued="18" />
  <references type="weak" candidates="113" cleared="27" enqueued="27" />
  <references type="weak" candidates="136" cleared="42" enqueued="42" />
  <references type="weak" candidates="250" cleared="2" enqueued="2" />
  <references type="weak" candidates="248" cleared="0" enqueued="0" />
```

**Comment by pshipton** [comment]
Probably the easiest approach is do modify the test to call com.ibm.jvm.Dump.SystemDump() when it fails.

**Comment by JasonFengJ9** [comment]
Also seen at [JDK22 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_aarch64_linux_testList_2/16/)(`cent7-aarch64-1`)
```
[2024-04-02T04:00:45.002Z] variation: Mode650
[2024-04-02T04:00:45.002Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-04-02T04:03:49.830Z] TEST: java/io/Serializable/subclassGC/SubclassGC.java

[2024-04-02T04:03:49.831Z] Start Garbage Collection right now
[2024-04-02T04:03:49.831Z] java.lang.Error
[2024-04-02T04:03:49.831Z] 	at SubclassGC.main(SubclassGC.java:82)
[2024-04-02T04:03:49.831Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-04-02T04:03:49.831Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-04-02T04:03:49.831Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-04-02T04:03:49.831Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-04-02T04:03:49.831Z] 
[2024-04-02T04:03:49.831Z] JavaTest Message: Test threw exception: java.lang.Error

[2024-04-02T04:04:12.969Z] jdk_io_1_FAILED
```

**Comment by pshipton** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_x86-64_windows/29/)
0.45 RC1

**Comment by pshipton** [comment]
See if the failure can be duplicated running only the individual test.
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40130/

**Comment by pshipton** [comment]
@dmitripivkine there is a system dump to look at.

https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_8/691
https://na.artifactory.swg-devops.com/artifactory/sys-rt-generic-local/hyc-runtimes-jenkins.swg-devops.com/Grinder_iteration_8/691/openjdk_test_output.tar.gz

**Comment by dmitripivkine** [comment]
I noticed that `java/lang/invoke/MemberName` objects (we added Finalization processing to recently) have pointer back to class object. It means class can't be unloaded until all of such objects are processed in Finalization. This test calls `System.gc()` once. It might be not enough to reach the point when class can be unloaded. So, at least we should try to call `System.gc()` twice (or even more times) and see if this problem goes away.

**Comment by pshipton** [comment]
Trying a grinder with two calls to System.gc()
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_8/692/

**Comment by keithc-ca** [comment]
Is the plan that the changes above will be reverted when we have the solution anticipated in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/759#discussion_r1537643091?

**Comment by pshipton** [comment]
Yes, we can do that, if we remember to do so.

**Comment by pshipton** [comment]
I can keep this open and assigned to the latest milestone as a reminder.

**Comment by dmitripivkine** [comment]
There is nothing to do with this item until new implementation for handling `java/lang/invoke/MemberName` objects is in place. Moving to the next milestone.
