### ISSUE TITLE
JDK22 jdk_lang_1_FAILED java/lang/ClassLoader/Assert.java timed out

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19253]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_testList_1/18/)(`sles15-aarch64-4`):
```
openjdk version "22" 2024-03-19
IBM Semeru Runtime Open Edition 22.0.1.0-m1 (build 22+36)
Eclipse OpenJ9 VM 22.0.1.0-m1 (build v0.45.0-release-a39ab2281, JRE 22 Linux aarch64-64-Bit Compressed References 20240319_32 (JIT enabled, AOT enabled)
OpenJ9   - a39ab2281
OMR      - 254af5a04
JCL      - 74f10f62339 based on jdk-22+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_lang_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk22_j9_sanity.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F32%2Fibm-semeru-open-jdk_aarch64_linux_22_36_openj9-0.45.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F32%2Fibm-semeru-open-testimage_aarch64_linux_22_36_openj9-0.45.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=22&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk22&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.45.0-release&amp;OPENJ9_BRANCH=v0.45.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.45.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=18&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-03-28T16:23:12.436Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2024-03-28T16:23:12.436Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Xverbosegclog 

[2024-03-28T16:58:53.706Z] TEST: java/lang/ClassLoader/Assert.java

[2024-03-28T16:58:53.713Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_testList_1/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1013174ms).
[2024-03-28T16:58:53.713Z] --------------------------------------------------
[2024-03-28T19:45:24.611Z] Test results: passed: 934; error: 1
[2024-03-28T19:45:38.881Z] Report written to /home/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17116429422129/jdk_lang_1/report/html/report.html
[2024-03-28T19:45:38.881Z] Results written to /home/jenkins/workspace/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_testList_1/aqa-tests/TKG/output_17116429422129/jdk_lang_1/work
[2024-03-28T19:45:38.881Z] Error: Some tests failed or other problems occurred.
[2024-03-28T19:45:38.881Z] -----------------------------------
[2024-03-28T19:45:38.881Z] jdk_lang_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39355/)

**Comment by pshipton** [comment]
The grinder passed on ubu20-aarch64-3, ubu20-aarch64-5, ubu22-aarch64-1, rhel9-aarch64-2.
It's timing out in all iterations on sles15-aarch64-5, and hasn't completed yet. It seems an OS specific issue.

I see the following in the timeout info
```
05:38:56  "Thread-123" prio=5 Id=154 RUNNABLE
05:38:56  	at java.base@22/java.io.FileInputStream.readBytes(Native Method)
05:38:56  	at java.base@22/java.io.FileInputStream.read(FileInputStream.java:287)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read1(BufferedInputStream.java:345)
05:38:56  	at java.base@22/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read(BufferedInputStream.java:405)
05:38:56  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@652e2da
05:38:56  	at java.base@22/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
05:38:56  	at java.base@22/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
05:38:56  	at java.base@22/java.io.FilterInputStream.read(FilterInputStream.java:95)
05:38:56  	at app//jdk.test.lib.process.StreamPumper.run(StreamPumper.java:111)
05:38:56  	at java.base@22/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
05:38:56  	at java.base@22/java.util.concurrent.FutureTask.run(FutureTask.java:317)
05:38:56  	at java.base@22/java.lang.Thread.run(Thread.java:1582)
05:38:56  
05:38:56  "Thread-124" prio=5 Id=155 RUNNABLE
05:38:56  	at java.base@22/java.io.FileInputStream.readBytes(Native Method)
05:38:56  	at java.base@22/java.io.FileInputStream.read(FileInputStream.java:287)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read1(BufferedInputStream.java:345)
05:38:56  	at java.base@22/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read(BufferedInputStream.java:405)
05:38:56  	- locked java.lang.ProcessImpl$ProcessPipeInputStream@e83ab12d
05:38:56  	at java.base@22/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
05:38:56  	at java.base@22/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
05:38:56  	at java.base@22/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
05:38:56  	at java.base@22/java.io.FilterInputStream.read(FilterInputStream.java:95)
05:38:56  	at app//jdk.test.lib.process.StreamPumper.run(StreamPumper.java:111)
05:38:56  	at java.base@22/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
05:38:56  	at java.base@22/java.util.concurrent.FutureTask.run(FutureTask.java:317)
05:38:56  	at java.base@22/java.lang.Thread.run(Thread.java:1582)
```

**Comment by pshipton** [comment]
Testing jdk21 on sles15 via [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39367)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/185/

**Comment by pshipton** [comment]
10x x 5 grinder of the single test on cent8 machines https://openj9-jenkins.osuosl.org/job/Grinder/3437/

**Comment by pshipton** [comment]
It seems some machines are very slow.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_linux_OMR_testList_0/461
This started at 05:42 and is still running, not finished, at 14:45.
Looking at history, a reasonable time to complete is 2:20
There is barely any CPU being used on the machine. Perhaps a disk issue. 
@AdamBrousseau any ideas?

**Comment by AdamBrousseau** [comment]
The 6x ub20 aarch64 machines at OSU [1] are very slow compared to the 12x (cent8/ub20/ub22) from Equinix [2]
So that doesn't explain why you're seeing slowness on the equinix ones. I'm not aware of any changes to those recently. I rebooted all the Equinix ones. See if that helps at all.

[1] https://openj9-jenkins.osuosl.org/label/sw.os.linux&&hw.arch.aarch64&&ci.geo.osu/
[2] https://openj9-jenkins.osuosl.org/label/sw.os.linux&&hw.arch.aarch64&&ci.geo.equinix/

**Comment by pshipton** [comment]
I have grinder pending on cent8-aarch64-1, but it's disabled pending reboot.

**Comment by pshipton** [comment]
The Assert.java test still timed out running on [cent8-aarch64-5](https://openj9-jenkins.osuosl.org/computer/cent8-aarch64-5).
https://openj9-jenkins.osuosl.org/job/Grinder/3444/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/107/ - [cent8-aarch64-4](https://openj9-jenkins.osuosl.org/computer/cent8-aarch64-4)

**Comment by pshipton** [comment]
The OpenJ9 machine problem appears to be a [network issue](https://github.ibm.com/runtimes/infrastructure/issues/9172) with the machines, causing the JVM to start slowly (15s).
