### ISSUE TITLE
CryptoTests_0_FAILED Error:  cryptotest/CryptoTest.java

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19264]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.functional_ppc64le_linux_testList_2/560/)(`sles15le-svl-rt4-1`):
```
java version "17.0.11-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 17.0.11+7-202404012339 (build 17.0.11-beta+7-202404012339)
Eclipse OpenJ9 VM 17.0.11+7-202404012339 (build master-7e6038dbc, JRE 17 Linux ppc64le-64-Bit Compressed References 20240401_636 (JIT enabled, AOT enabled)
OpenJ9   - 7e6038dbc
OMR      - 6391cf4bb
JCL      - bcab50b2f3 based on jdk-17.0.11+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=CryptoTests_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_extended.functional_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F636%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK17U_2024-04-01-23-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F636%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK17U_2024-04-01-23-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=576&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-04-02T00:35:23.966Z] variation: NoOptions
[2024-04-02T00:35:23.966Z] JVM_OPTIONS:  

[2024-04-02T00:59:24.120Z] Error:  cryptotest/CryptoTest.java
[2024-04-02T00:59:24.120Z] Test results: passed: 31; error: 1
[2024-04-02T00:59:24.120Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_ppc64le_linux_testList_2/aqa-tests/functional/security/Crypto/CryptoTest/test.1712018123/jdk/JTreport/html/report.html
[2024-04-02T00:59:24.120Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_ppc64le_linux_testList_2/aqa-tests/functional/security/Crypto/CryptoTest/test.1712018123/jdk/JTwork
[2024-04-02T00:59:24.120Z] Error: Some tests failed or other problems occurred.
[2024-04-02T00:59:24.120Z] ~/workspace/Test_openjdk17_j9_extended.functional_ppc64le_linux_testList_2/aqa-tests/TKG/output_17120181222757/CryptoTests_0
[2024-04-02T00:59:24.120Z] renamed '/home/jenkins/workspace/Test_openjdk17_j9_extended.functional_ppc64le_linux_testList_2/aqa-tests/functional/security/Crypto/CryptoTest/test.1712018123.tar.gz' -> './test.1712018123.tar.gz'
[2024-04-02T00:59:24.120Z] -----------------------------------
[2024-04-02T00:59:24.120Z] CryptoTests_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39408/) - 23/50 failed

[JDK11 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_testList_0/647/)(`sles15le-rtp-rt4-1`)

**Comment by pshipton** [comment]
The grinder passed on pll021, rhel9lert-1.
Failed 7/10 on rhel7le-rtp-rt2-1, 7/10 on rhel7le-svl-rt3-1, 9/10 on sles15le-svl-rt8-1.
There was a 3x re-run which passed on p10sles02.

Looking at the two original failures, they are time outs.
```
"MainThread" prio=5 Id=22 RUNNABLE
	at java.base@17.0.11-beta/java.math.BigInteger.implMulAdd(BigInteger.java:3202)
	at java.base@17.0.11-beta/java.math.BigInteger.mulAdd(BigInteger.java:3171)
	at java.base@17.0.11-beta/java.math.BigInteger.implSquareToLen(BigInteger.java:2204)
	at java.base@17.0.11-beta/java.math.BigInteger.squareToLen(BigInteger.java:2124)
	at java.base@17.0.11-beta/java.math.BigInteger.implMontgomerySquare(BigInteger.java:2866)
	at java.base@17.0.11-beta/java.math.BigInteger.montgomerySquare(BigInteger.java:2823)
	at java.base@17.0.11-beta/java.math.BigInteger.oddModPow(BigInteger.java:3093)
	at java.base@17.0.11-beta/java.math.BigInteger.modPow(BigInteger.java:2754)
	at java.base@17.0.11-beta/java.math.BigInteger.passesMillerRabin(BigInteger.java:1122)
	at java.base@17.0.11-beta/java.math.BigInteger.primeToCertainty(BigInteger.java:978)
	at java.base@17.0.11-beta/java.math.BitSieve.retrieve(BitSieve.java:203)
	at java.base@17.0.11-beta/java.math.BigInteger.largePrime(BigInteger.java:847)
	at java.base@17.0.11-beta/java.math.BigInteger.probablePrime(BigInteger.java:785)
	at java.base@17.0.11-beta/sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:173)
	at java.base@17.0.11-beta/java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
	at java.base@17.0.11-beta/java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:495)
	at app//cryptotest.utils.KeysNaiveGenerator.getRsaKeyPair(KeysNaiveGenerator.java:165)
	at app//cryptotest.utils.KeysNaiveGenerator.getRsaPrivateKey(KeysNaiveGenerator.java:169)
	at app//cryptotest.tests.SignatureTests.checkAlgorithm(SignatureTests.java:89)
	at app//cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
	at app//cryptotest.utils.AlgorithmTest.doTest(AlgorithmTest.java:58)
	at app//cryptotest.CryptoTest.main(CryptoTest.java:128)
```
```
"MainThread" prio=5 Id=23 RUNNABLE
	at java.base@11.0.23-beta/java.math.BigInteger.montReduce(BigInteger.java:3112)
	at java.base@11.0.23-beta/java.math.BigInteger.implMontgomerySquare(BigInteger.java:2856)
	at java.base@11.0.23-beta/java.math.BigInteger.montgomerySquare(BigInteger.java:2812)
	at java.base@11.0.23-beta/java.math.BigInteger.oddModPow(BigInteger.java:3082)
	at java.base@11.0.23-beta/java.math.BigInteger.modPow(BigInteger.java:2743)
	at java.base@11.0.23-beta/java.math.BigInteger.passesMillerRabin(BigInteger.java:1104)
	at java.base@11.0.23-beta/java.math.BigInteger.primeToCertainty(BigInteger.java:960)
	at java.base@11.0.23-beta/java.math.BitSieve.retrieve(BitSieve.java:203)
	at java.base@11.0.23-beta/java.math.BigInteger.largePrime(BigInteger.java:829)
	at java.base@11.0.23-beta/java.math.BigInteger.probablePrime(BigInteger.java:767)
	at java.base@11.0.23-beta/sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:144)
	at java.base@11.0.23-beta/java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:722)
	at java.base@11.0.23-beta/java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:495)
	at app//cryptotest.tests.KeyPairGeneratorTests.checkAlgorithm(KeyPairGeneratorTests.java:85)
	at app//cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:79)
	at app//cryptotest.utils.AlgorithmTest.doTest(AlgorithmTest.java:58)
	at app//cryptotest.CryptoTest.main(CryptoTest.java:128)
```

@llxia can you pls increase the timeout for this test.

**Comment by pshipton** [comment]
@jasonkatonica fyi in case there is something to do re accelerating the operations better.

**Comment by llxia** [comment]
The tests are from https://github.com/rh-openjdk/CryptoTest. We can try to submit a PR for a timeout increase.

@annaibm could you try to increase timeout at https://github.com/rh-openjdk/CryptoTest/blob/master/cryptotest/CryptoTest.java#L96? Say `1200`. Run a Grinder with the above machines with 50x iterations. If the Grinder passes, then we can submit a PR at https://github.com/rh-openjdk/CryptoTest. 
Note: you will need to update https://github.com/adoptium/aqa-tests/blob/master/functional/security/Crypto/build.xml#L47 to point to your repo and branch for testing the PR.

**Comment by annaibm** [comment]
@llxia it appears that the timeout increase to `1200` was not sufficient to prevent test failures in m/c -[sles15le-svl-rt8-1.fyre.ibm.com](http://sles15le-svl-rt8-1.fyre.ibm.com/), 
 [https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/3952](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39525/) , Getting  failed test for `cryptotest/CryptoTest.java` for one of the iteration. 
``` Passed: cryptotest/tests/TrustManagerFactoryTests.java
06:43:34  Passed: cryptotest/tests/XMLSignatureFactoryTests.java
07:03:46  Error:  cryptotest/CryptoTest.java
07:03:46  Test results: passed: 31; error: 1
07:03:46  Report written to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712658277/jdk/JTreport/html/report.html
07:03:46  Results written to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712658277/jdk/JTwork
07:03:46  Error: Some tests failed or other problems occurred.
07:03:46  ~/workspace/Grinder/aqa-tests/TKG/output_17126582766856/CryptoTests_0
07:03:46  renamed '/home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712658277.tar.gz' -> './test.1712658277.tar.gz'
07:03:46  -----------------------------------
07:03:46  CryptoTests_0_FAILED
07:03:46  -----------------------------------
07:03:46  
07:03:46  TEST TEARDOWN:
```

I will try to increase the timeout to `1800` and run for above machines.

**Comment by llxia** [comment]
Thanks @annaibm . PR https://github.com/rh-openjdk/CryptoTest/pull/66 is merged. Timeout is set to 1800.
Close the issue. Please reopen if the problem occurs again.
