### ISSUE TITLE
JCL_Test test_isAlive AssertionError: Started thread returned false

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19265]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/755
JCL_Test_0
```
23:44:18  FAILED: test_isAlive
23:44:18  java.lang.AssertionError: Started thread returned false
23:44:18  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@468859b5(file:/home/jenkins/testDependency/lib/testng.jar)
23:44:18  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@468859b5(file:/home/jenkins/testDependency/lib/testng.jar)
23:44:18  	at org.openj9.test.java.lang.Test_Thread.test_isAlive(Test_Thread.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@468859b5(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/1036/
