### ISSUE TITLE
jdk_nio_0_FAILED java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java test InheritedChannelTest.test("StateTest", [StateTest]): failure

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19283]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1/22/)(`sles15-aarch64-4`):
```
java version "11.0.23-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 11.0.23+7-202404060114 (build 11.0.23-beta+7)
Eclipse OpenJ9 VM 11.0.23+7-202404060114 (build master-d1a1a70e5, JRE 11 Linux aarch64-64-Bit Compressed References 20240406_560 (JIT enabled, AOT enabled)
OpenJ9   - d1a1a70e5
OMR      - 8037ccd04
JCL      - 1b6c09aa97 based on jdk-11.0.23+7)
```
**[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_nio_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F560%2Fibm-semeru-certified-jdk_aarch64_linux_JDK11U_2024-04-06-01-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F560%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2024-04-06-01-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=174&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None)** - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-04-06T02:24:17.480Z] variation: Mode150
[2024-04-06T02:24:17.480Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-04-06T03:03:13.095Z] TEST: java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java

[2024-04-06T03:03:13.096Z] test InheritedChannelTest.test("StateTest", [StateTest]): failure
[2024-04-06T03:03:13.096Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2024-04-06T03:03:13.096Z] 
[2024-04-06T03:03:13.096Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2024-04-06T03:03:13.096Z] 	at InheritedChannelTest.test(InheritedChannelTest.java:117)

[2024-04-06T03:03:13.097Z] java.lang.Exception: failures: 5
[2024-04-06T03:03:13.097Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2024-04-06T03:03:13.097Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2024-04-06T03:03:13.097Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-04-06T03:03:13.097Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-04-06T03:03:13.097Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-04-06T03:03:13.097Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-04-06T03:03:13.097Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-04-06T03:03:13.097Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-04-06T03:03:13.097Z] 
[2024-04-06T03:03:13.097Z] JavaTest Message: Test threw exception: java.lang.Exception: failures: 5

[2024-04-06T03:19:05.465Z] jdk_nio_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39555/)

**Comment by pshipton** [comment]
Does the RI also fail on the problem machine?

**Comment by JasonFengJ9** [comment]
[RI 3x grinder at sles15-aarch64-3](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39574/) failed with `RuntimeException: Expected message not received`. No failure at `java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java`.

[RI 100x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39576/consoleFull) - 2 failures `ConnectException: Connection refused`.

This seems a network sensitive test.

**Comment by pshipton** [comment]
I also find the following in the original failure output.
```
23:03:13  Exception in thread "main" java.io.IOException: Timed out waiting for service to report test result
23:03:13  	at StateTest.waitForTestResult(StateTest.java:83)
23:03:13  	at StateTest.main(StateTest.java:168)

23:03:13  Bad response or premature EOF, bytes read: 
23:03:13  java.lang.RuntimeException: Bad response or premature EOF from service
23:03:13  Exception in thread "main" java.lang.RuntimeException: Test failed - see log for details
23:03:13  	at EchoTest.main(EchoTest.java:181)

23:03:13  Exception in thread "main" java.lang.RuntimeException: Timed out waiting for connection to close
23:03:13  	at CloseTest.main(CloseTest.java:85)
```

**Comment by JasonFengJ9** [comment]
[openjdk17_j9_extended.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_s390x_linux_testList_0/288/)
```
[2025-06-23T22:10:53.187Z] variation: Mode150
[2025-06-23T22:10:53.187Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-06-23T22:20:36.869Z] TEST: java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java

[2025-06-23T22:20:36.884Z] Bad response or premature EOF, bytes read: 
[2025-06-23T22:20:36.884Z] java.lang.RuntimeException: Bad response or premature EOF from service
[2025-06-23T22:20:36.884Z] Exception in thread "main" java.lang.RuntimeException: Test failed - see log for details
[2025-06-23T22:20:36.884Z] 	at EchoTest.main(EchoTest.java:181)
[2025-06-23T22:20:36.884Z] 
[2025-06-23T22:20:36.884Z] test InheritedChannelTest.test("EchoTest", [EchoTest]): failure
[2025-06-23T22:20:36.884Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2025-06-23T22:20:36.884Z] 
[2025-06-23T22:20:36.884Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:504)
[2025-06-23T22:20:36.884Z] 	at InheritedChannelTest.test(InheritedChannelTest.java:123)

[2025-06-23T22:27:33.180Z] Test results: passed: 441; failed: 1

[2025-06-23T22:27:38.973Z] jdk_nio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_0/421/)
```
[2026-02-08T04:15:20.002Z] Running test jdk_nio_1 ...
[2026-02-08T04:15:20.002Z] ===============================================
[2026-02-08T04:15:20.002Z] jdk_nio_1 Start Time: Sat Feb  7 20:15:16 2026 Epoch Time (ms): 1770524116136
[2026-02-08T04:15:20.002Z] variation: Mode650
[2026-02-08T04:15:20.002Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2026-02-08T04:23:05.045Z] TEST: java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java

[2026-02-08T04:23:05.061Z] test InheritedChannelTest.test("EchoTest", [EchoTest]): failure
[2026-02-08T04:23:05.061Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2026-02-08T04:23:05.061Z] 
[2026-02-08T04:23:05.061Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2026-02-08T04:23:05.061Z] 	at InheritedChannelTest.test(InheritedChannelTest.java:117)
```

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_1/479/)
```
[2026-06-17T15:46:10.231Z] Running test jdk_nio_0 ...
[2026-06-17T15:46:10.231Z] ===============================================
[2026-06-17T15:46:10.231Z] jdk_nio_0 Start Time: Wed Jun 17 15:46:10 2026 Epoch Time (ms): 1781711170035
[2026-06-17T15:46:13.901Z] variation: Mode150
[2026-06-17T15:46:13.901Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2026-06-17T15:55:47.766Z] TEST: java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java

[2026-06-17T15:55:47.782Z] [2026-06-17T15:54:41.959255440Z] Waiting for completion for process 1045871
[2026-06-17T15:55:47.782Z] [2026-06-17T15:54:41.959758670Z] Waiting for completion finished for process 1045871
[2026-06-17T15:55:47.782Z] test InheritedChannelTest.test("CloseTest", [CloseTest]): success
[2026-06-17T15:55:47.782Z] LD_LIBRARY_PATH=/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_1/jdkbinary/openjdk-test-image/jdk/jtreg/native
[2026-06-17T15:55:47.782Z] Command line: [/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_1/jdkbinary/j2sdk-image/bin/java -ea -esa -Xmx512m -XX:+UseCompressedOops -Xverbosegclog --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED StateTest -Djava.security.manager -Djava.security.policy=/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/channels/spi/SelectorProvider/inheritedChannel/java.policy.pass]
[2026-06-17T15:55:47.782Z] [2026-06-17T15:54:41.987377518Z] Gathering output for process 1046002
[2026-06-17T15:55:47.782Z] Exception in thread "main" java.io.IOException: Timed out waiting for service to report test result
[2026-06-17T15:55:47.782Z] 	at StateTest.waitForTestResult(StateTest.java:83)
[2026-06-17T15:55:47.782Z] 	at StateTest.main(StateTest.java:168)
[2026-06-17T15:55:47.782Z] 
[2026-06-17T15:55:47.782Z] [2026-06-17T15:55:24.079712091Z] Waiting for completion for process 1046002
[2026-06-17T15:55:47.783Z] [2026-06-17T15:55:24.080423819Z] Waiting for completion finished for process 1046002
[2026-06-17T15:55:47.783Z] [2026-06-17T15:55:24.080723227Z] Waiting for completion for process 1046002
[2026-06-17T15:55:47.783Z] [2026-06-17T15:55:24.080950371Z] Waiting for completion finished for process 1046002
[2026-06-17T15:55:47.783Z] test InheritedChannelTest.test("StateTest run with /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/channels/spi/SelectorProvider/inheritedChannel/java.policy.pass", java.util.ImmutableCollections$ListN@cfaa3e61): failure
[2026-06-17T15:55:47.783Z] java.lang.RuntimeException: Expected to get exit value of [0]
[2026-06-17T15:55:47.783Z] 
[2026-06-17T15:55:47.783Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
[2026-06-17T15:55:47.783Z] 	at InheritedChannelTest.test(InheritedChannelTest.java:117)
```
