### ISSUE TITLE
jdk8 functional tests fail to build UnsatisfiedLinkError jdk/crypto/jniprovider/NativeCrypto.isMD5Available()Z

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19289]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_aarch64_linux_Personal/175/console
```
15:20:54  BUILD FAILED
15:20:54  /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_aarch64_linux_Personal/aqa-tests/TKG/scripts/build_tools.xml:58: The following error occurred while executing this line:
15:20:54  /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_aarch64_linux_Personal/aqa-tests/TKG/scripts/build_tools.xml:37: java.lang.UnsatisfiedLinkError: jdk/crypto/jniprovider/NativeCrypto.isMD5Available()Z
15:20:54  	at sun.security.provider.SunEntries.putEntries(SunEntries.java:252)
15:20:54  	at sun.security.provider.Sun.<init>(Sun.java:56)
15:20:54  	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
15:20:54  	at java.lang.Class.newInstance(Class.java:2130)
15:20:54  	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:234)
15:20:54  	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:219)
15:20:54  	at java.security.AccessController.doPrivileged(AccessController.java:690)
15:20:54  	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:219)
15:20:54  	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:200)
15:20:54  	at sun.security.jca.ProviderList.getProvider(ProviderList.java:257)
15:20:54  	at sun.security.jca.ProviderList$3.get(ProviderList.java:172)
15:20:54  	at sun.security.jca.ProviderList$3.get(ProviderList.java:167)
15:20:54  	at java.util.AbstractList$Itr.next(AbstractList.java:358)
15:20:54  	at java.security.SecureRandom.getPrngAlgorithm(SecureRandom.java:574)
15:20:54  	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:208)
15:20:54  	at java.security.SecureRandom.<init>(SecureRandom.java:170)
15:20:54  	at java.io.File$TempDirectory.<clinit>(File.java:1940)
15:20:54  	at java.io.File.createTempFile(File.java:2049)
15:20:54  	at org.apache.tools.ant.util.FileUtils.createTempFile(FileUtils.java:950)
15:20:54  	at org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter.executeExternalCompile(DefaultCompilerAdapter.java:547)
15:20:54  	at org.apache.tools.ant.taskdefs.compilers.JavacExternal.execute(JavacExternal.java:63)
15:20:54  	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1404)
15:20:54  	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1133)
15:20:54  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
15:20:54  	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
15:20:54  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:20:54  	at java.lang.reflect.Method.invoke(Method.java:503)
15:20:54  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
15:20:54  	at org.apache.tools.ant.Task.perform(Task.java:350)
15:20:54  	at org.apache.tools.ant.Target.execute(Target.java:449)
15:20:54  	at org.apache.tools.ant.Target.performTasks(Target.java:470)
15:20:54  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
15:20:54  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
15:20:54  	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
15:20:54  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
15:20:54  	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
15:20:54  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
15:20:54  	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
15:20:54  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:20:54  	at java.lang.reflect.Method.invoke(Method.java:503)
15:20:54  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
15:20:54  	at org.apache.tools.ant.Task.perform(Task.java:350)
15:20:54  	at org.apache.tools.ant.Target.execute(Target.java:449)
15:20:54  	at org.apache.tools.ant.Target.performTasks(Target.java:470)
15:20:54  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
15:20:54  	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
15:20:54  	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
15:20:54  	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
15:20:54  	at org.apache.tools.ant.Main.runBuild(Main.java:834)
15:20:54  	at org.apache.tools.ant.Main.startAnt(Main.java:223)
15:20:54  	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
15:20:54  	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
15:20:54  
15:20:54  Total time: 2 seconds
15:20:54  1
15:20:54  make: *** [makefile:105: compileTools] Error 1
```

**Comment by KostasTsiounis** [comment]
I forgot to update [this](https://github.com/KostasTsiounis/openj9-openjdk-jdk8/blob/openj9/closed/make/mapfiles/libjncrypto/mapfile-vers) file. It is jdk8 specific. Will open a PR for that.
