### ISSUE TITLE
jdk23 View-LE-OnHeap, View-BE-OnHeap IllegalStateException: Atomic access not supported for heap buffer

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19300]
jdk23 testing on amac
```
17:09:02  openjdk version "23-internal" 2024-09-17
17:09:02  OpenJDK Runtime Environment (build 23-internal-adhoc.****.BuildJDKnextaarch64macPersonal)
17:09:02  Eclipse OpenJ9 VM (build master-b2db2045aa4, JRE 23 Mac OS X aarch64-64-Bit 20240411_113 (JIT enabled, AOT enabled)
17:09:02  OpenJ9   - b2db2045aa4
17:09:02  OMR      - 0e07ad19c1f
17:09:02  JCL      - 7ac6a9b5b39 based on jdk-23+17)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_extended.functional_aarch64_mac_Personal_testList_1/2
View-LE-OnHeap_0
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_extended.functional_aarch64_mac_Personal_testList_0/2
View-BE-OnHeap_0

```
17:11:39  FAILED: testChar
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsChars$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsChars.java:189)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsChars$ByteBufferHandle.getOpaque(VarHandleByteArrayAsChars.java:261)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testChar(ByteBufferViewVarHandleTests.java:84)

17:11:39  FAILED: testDouble
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsDoubles$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsDoubles.java:197)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsDoubles$ByteBufferHandle.getOpaque(VarHandleByteArrayAsDoubles.java:270)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testDouble(ByteBufferViewVarHandleTests.java:286)

17:11:39  FAILED: testFloat
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsFloats$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsFloats.java:197)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsFloats$ByteBufferHandle.getOpaque(VarHandleByteArrayAsFloats.java:270)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testFloat(ByteBufferViewVarHandleTests.java:529)

17:11:39  FAILED: testInt
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsInts.java:189)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ByteBufferHandle.getOpaque(VarHandleByteArrayAsInts.java:261)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testInt(ByteBufferViewVarHandleTests.java:772)

17:11:39  FAILED: testIntNonZeroIndex
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsInts.java:189)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ByteBufferHandle.getOpaque(VarHandleByteArrayAsInts.java:261)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testIntNonZeroIndex(ByteBufferViewVarHandleTests.java:998)

17:11:39  FAILED: testLong
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsLongs$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsLongs.java:189)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsLongs$ByteBufferHandle.getOpaque(VarHandleByteArrayAsLongs.java:261)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testLong(ByteBufferViewVarHandleTests.java:1208)

17:11:39  FAILED: testReadOnlyByteBuffer
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsInts.java:189)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ByteBufferHandle.getVolatile(VarHandleByteArrayAsInts.java:221)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testReadOnlyByteBuffer(ByteBufferViewVarHandleTests.java:1747)

17:11:39  FAILED: testShort
17:11:39  java.lang.IllegalStateException: Atomic access not supported for heap buffer
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsShorts$ByteBufferHandle.checkNullHeapBase(VarHandleByteArrayAsShorts.java:189)
17:11:39  	at java.base/java.lang.invoke.VarHandleByteArrayAsShorts$ByteBufferHandle.getOpaque(VarHandleByteArrayAsShorts.java:261)
17:11:39  	at org.openj9.test.varhandle.ByteBufferViewVarHandleTests.testShort(ByteBufferViewVarHandleTests.java:1435)

17:11:39  FAILED: testChar
17:11:39  java.lang.UnsupportedOperationException: getOpaque
17:11:39  	at java.base/java.lang.invoke.VarHandle.getMethodHandleUncached(VarHandle.java:2249)
17:11:39  	at java.base/java.lang.invoke.VarHandle.getMethodHandle(VarHandle.java:2227)
17:11:39  	at org.openj9.test.varhandle.ByteArrayViewVarHandleTests.testChar(ByteArrayViewVarHandleTests.java:75)

etc.
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by babsingh** [comment]
The implementation has changed. The alignment requirements have been changed in JDK23+. We will need to update the tests to match the new implementation. See https://bugs.openjdk.org/browse/JDK-8318966 for more details about the changes.
