### ISSUE TITLE
jdk23 VarHandle testIsAccessModeSupportedCharByteArrayViewBE expected [true] but found [false]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19302]
jdk23 testing on amac
```
17:09:02  openjdk version "23-internal" 2024-09-17
17:09:02  OpenJDK Runtime Environment (build 23-internal-adhoc.****.BuildJDKnextaarch64macPersonal)
17:09:02  Eclipse OpenJ9 VM (build master-b2db2045aa4, JRE 23 Mac OS X aarch64-64-Bit 20240411_113 (JIT enabled, AOT enabled)
17:09:02  OpenJ9   - b2db2045aa4
17:09:02  OMR      - 0e07ad19c1f
17:09:02  JCL      - 7ac6a9b5b39 based on jdk-23+17)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_extended.functional_aarch64_mac_Personal_testList_1/2
VarHandle_0
```
17:29:12  FAILED: testIsAccessModeSupportedCharByteArrayViewBE
17:29:12  java.lang.AssertionError: expected [true] but found [false]
17:29:12  	at org.testng.Assert.fail(Assert.java:96)
17:29:12  	at org.testng.Assert.failNotEquals(Assert.java:776)
17:29:12  	at org.testng.Assert.assertTrue(Assert.java:44)
17:29:12  	at org.testng.Assert.assertTrue(Assert.java:54)
17:29:12  	at org.openj9.test.varhandle.VarHandleUtilTests.isAccessModeSupported_ByteView(VarHandleUtilTests.java:614)
17:29:12  	at org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedCharByteArrayViewBE(VarHandleUtilTests.java:721)

17:29:12  FAILED: testIsAccessModeSupportedCharByteArrayViewLE
17:29:12  java.lang.AssertionError: expected [true] but found [false]
17:29:12  	at org.testng.Assert.fail(Assert.java:96)
17:29:12  	at org.testng.Assert.failNotEquals(Assert.java:776)
17:29:12  	at org.testng.Assert.assertTrue(Assert.java:44)
17:29:12  	at org.testng.Assert.assertTrue(Assert.java:54)
17:29:12  	at org.openj9.test.varhandle.VarHandleUtilTests.isAccessModeSupported_ByteView(VarHandleUtilTests.java:614)
17:29:12  	at org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedCharByteArrayViewLE(VarHandleUtilTests.java:727)

17:29:12  FAILED: testIsAccessModeSupportedDoubleByteArrayViewLE
17:29:12  java.lang.AssertionError: expected [true] but found [false]
17:29:12  	at org.testng.Assert.fail(Assert.java:96)
17:29:12  	at org.testng.Assert.failNotEquals(Assert.java:776)
17:29:12  	at org.testng.Assert.assertTrue(Assert.java:44)
17:29:12  	at org.testng.Assert.assertTrue(Assert.java:54)
17:29:12  	at org.openj9.test.varhandle.VarHandleUtilTests.isAccessModeSupported_FloatingPointView(VarHandleUtilTests.java:580)
17:29:12  	at org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedDoubleByteArrayViewLE(VarHandleUtilTests.java:769)

etc.
```

**Comment by pshipton** [comment]
@tajila fyi
