### ISSUE TITLE
testOpenJ9DiagnosticsMXBean testRemote_resetDumpOptions UndeclaredThrowableException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19315]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_ppc64_aix_Nightly_testList_0/183
testOpenJ9DiagnosticsMXBean_0
```
20:23:33  FAILED: testRemote_resetDumpOptions
20:23:33  java.lang.reflect.UndeclaredThrowableException
20:23:33  	at jdk.proxy1/jdk.proxy1.$Proxy6.setDumpOptions(Unknown Source)
20:23:33  	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.resetDumpOptions(TestOpenJ9DiagnosticsMXBean.java:527)
20:23:33  	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testRemote_resetDumpOptions(TestOpenJ9DiagnosticsMXBean.java:352)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_ppc64_aix_Nightly_testList_0/318

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_ppc64_aix_Nightly_testList_0/725
testOpenJ9DiagnosticsMXBean_0

```
21:26:40  FAILED: testRemote_resetDumpOptions
21:26:40  java.lang.reflect.UndeclaredThrowableException
21:26:40  	at jdk.proxy1/jdk.proxy1.$Proxy6.setDumpOptions(Unknown Source)
21:26:40  	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.resetDumpOptions(TestOpenJ9DiagnosticsMXBean.java:507)
21:26:40  	at org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testRemote_resetDumpOptions(TestOpenJ9DiagnosticsMXBean.java:332)
21:26:40  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
21:26:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
21:26:40  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
21:26:40  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
21:26:40  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
21:26:40  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
21:26:40  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
21:26:40  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
21:26:40  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
21:26:40  	at org.testng.TestRunner.run(TestRunner.java:505)
21:26:40  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
21:26:40  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
21:26:40  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
21:26:40  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
21:26:40  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
21:26:40  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
21:26:40  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
21:26:40  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
21:26:40  	at org.testng.TestNG.runSuites(TestNG.java:1049)
21:26:40  	at org.testng.TestNG.run(TestNG.java:1017)
21:26:40  	at org.testng.TestNG.privateMain(TestNG.java:1354)
21:26:40  	at org.testng.TestNG.main(TestNG.java:1323)
21:26:40  Caused by: java.rmi.NoSuchObjectException: no such object in table
21:26:40  	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
21:26:40  	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
21:26:40  	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:166)
21:26:40  	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.setAttribute(RMIConnectionImpl_Stub.java:556)
21:26:40  	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.setAttribute(RMIConnector.java:961)
21:26:40  	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy$SetHandler.invoke(MXBeanProxy.java:136)
21:26:40  	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
21:26:40  	at java.management/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
21:26:40  	... 25 more
```
