### ISSUE TITLE
jcmd and late attach don't work with java under Windows Services

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#19322]
Java -version output
--------------------

```
openjdk version "21.0.2" 2024-01-16 LTS
IBM Semeru Runtime Open Edition 21.0.2.0 (build 21.0.2+13-LTS)
Eclipse OpenJ9 VM 21.0.2.0 (build openj9-0.43.0, JRE 21 Windows 11 amd64-64-Bit Compressed References 20240116_95 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 78c4500a434 based on jdk-21.0.2+13)
```

Summary of problem
------------------

The inability to run jcmd and late attach is observed both with WebSphere traditional and WebSphere Liberty which use different mechanisms to create Windows Services, so I'm guessing it's not related to those mechanisms directly (note: Liberty uses [Apache commons daemon](https://commons.apache.org/proper/commons-daemon/procrun.html) prunsrv.exe). The command prompt running jcmd is started as Administrator. In the example below, the Liberty-generated Windows Service launches Liberty under javaw.exe but the WAS traditional-generated Windows Service launches WebSphere traditional under java.exe.

Steps to reproduce:

1. Download <https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/24.0.0.2/openliberty-24.0.0.2.zip>
1. Extract
1. Open command prompt as Administrator
1. Add Semeru to PATH; for example:
   ```
   set PATH=C:\work\semeru\21.0.2.0\jdk-21.0.2+13\bin;%PATH%
   ```
1. Change directory to the extracted directory of Liberty
1. Create the test Liberty server:
   ```
   wlp\bin\server create server1
   ```
1. Append a line to `wlp\usr\servers\server1\server.env` to specify Semeru in the `JAVA_HOME` environment variable; for example:
   ```
   JAVA_HOME=C:\work\semeru\21.0.2.0\jdk-21.0.2+13
   ```
1. Create the Windows Service for the Liberty server:
   ```
   wlp\bin\server registerWinService server1
   ```
1. Start the Windows Service:
   ```
   wlp\bin\server startWinService server1
   ```
1. Find the process ID of the javaw.exe for the Liberty server underneath the Windows Service:
   ```
   wmic process where 'commandline like "%server1%"' get caption,processid | findstr javaw
   ```
    For example:
    ```
    javaw.exe    4584
    ```
1. Run jmcd with the list option and observe the PID from the previous command is not listed (I think what's listed is jcmd itself); for example:
   ```
   jcmd -l
   26248 <no information available>
   ```

The issue is also observed with late attach:

1. Download [IBM Runtime Diagnostic Code Injection for the Java Platform (Java Surgery)](https://www.ibm.com/support/pages/ibm-runtime-diagnostic-code-injection-java-platform-java-surgery)
1. Run the `JavaDump` command on the process ID from above and it is not accessible to late attach:
   ```
   >java -jar surgery.jar -pid 4584 -command JavaDump
   IBM Runtime Diagnostic Code Injection for the Java Platform (RDCI)
   Version 1.1.20220516 (kevin.grigorenko@us.ibm.com)
   Surgery: Attaching to 4584
   Could not attach to 4584
   Surgery: Error: java.lang.reflect.InvocationTargetException
   com.ibm.rdci.surgery.client.AttachException: java.lang.reflect.InvocationTargetException
           at com.ibm.rdci.surgery.client.BaseAttacher.attach(BaseAttacher.java:50)
           at com.ibm.rdci.surgery.client.Client.attach(Client.java:127)
           at com.ibm.rdci.surgery.client.Client.main(Client.java:98)
   Caused by: java.lang.reflect.InvocationTargetException
           at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
           at java.base/java.lang.reflect.Method.invoke(Method.java:586)
           at com.ibm.rdci.surgery.client.BaseAttacher.attach(BaseAttacher.java:48)
           ... 2 more
   Caused by: com.sun.tools.attach.AttachNotSupportedException: target 4584 not found
           at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTargetImpl(OpenJ9VirtualMachine.java:151)
           at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.lambda$attachTarget$1(OpenJ9VirtualMachine.java:129)
           at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
           at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTarget(OpenJ9VirtualMachine.java:131)
           at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:65)
           at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:47)
           at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
           at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
           ... 4 more
   Surgery: Finished
   ```

**Comment by pshipton** [comment]
Attach only works from the same user. If you want to attach to the Windows service, you need to be logged in/running as the Windows service.

**Comment by pshipton** [comment]
@JasonFengJ9 @tajila fyi

**Comment by kgibm** [comment]
Thanks. Confirmed it works to use a technique such as the third party `psexec.exe` to start a command prompt as the Local System Account (`SYSTEM`) which is the user running the Windows Service and then `jcmd` works:

```
>wmic process where 'commandline like "%server1%"' get caption,processid | findstr javaw
javaw.exe    27516
>psexec -i -s cmd.exe
>set PATH=C:\work\semeru\21.0.2.0\jdk-21.0.2+13\bin;%PATH%
>jcmd -l
27516 C:\work\liberty\openliberty\24.0.0.2\all\openliberty-24.0.0.2\wlp\bin\tools\ws-server.jar --batch-file start server1
8740 <no information available>
>jcmd 27516 Dump.java
Dump written to C:\work\liberty\openliberty\24.0.0.2\all\openliberty-24.0.0.2\wlp\usr\servers\server1\javacore.20240415.103832.27516.0001.txt
```

It would be nice if jcmd and late attach supported the `Administrator` user as I don't find any simple techniques to execute commands as `SYSTEM` without the third party `psexec.exe`, though I don't know if there's something in the Windows security architecture about isolating the `Administrator` and `SYSTEM` users. Intuitively, I would expect `Administrator` to have the capability to perform jcmd commands.

**Comment by JasonFengJ9** [comment]
> Attach only works from the same user. If you want to attach to the Windows service, you need to be logged in/running as the Windows service.

Investigating a workaround to allow `Administrator` to attach less privileged users via [-Dcom.ibm.tools.attach.directory=<directory_name>](https://eclipse.dev/openj9/docs/dcomibmtoolsattachdirectory/).

**Comment by kgibm** [comment]
> Investigating a workaround to allow `Administrator` to attach less privileged users via [-Dcom.ibm.tools.attach.directory=<directory_name>](https://eclipse.dev/openj9/docs/dcomibmtoolsattachdirectory/).

Thanks Jason. It would be nice if this didn't require setting a non-default option and restarting the JVM, but if that is the only reasonable way to achieve this, then that would be understandable.

**Comment by JasonFengJ9** [comment]
>> Investigating a workaround to allow Administrator to attach less privileged users via [-Dcom.ibm.tools.attach.directory=<directory_name>](https://eclipse.dev/openj9/docs/dcomibmtoolsattachdirectory/).

> Thanks Jason. It would be nice if this didn't require setting a non-default option and restarting the JVM, but if that is the only reasonable way to achieve this, then that would be understandable.

Hi @kgibm 
[A common directory](https://eclipse.dev/openj9/docs/dcomibmtoolsattachdirectory/) is for Attach API working files used for interprocess communication during attaching.
By default on Windows systems, the Attach API uses the system temporary directory, which is typically `C:\Users\<USERNAME>\AppData\Local\Temp`, more details at https://eclipse.dev/openj9/docs/attachapi/.
Hence different users can't communicate each other with default common directories.

From a quick experiment in a fyre image, [-Dcom.ibm.tools.attach.directory=<directory_name>](https://eclipse.dev/openj9/docs/dcomibmtoolsattachdirectory/) doesn't allow `Administrator` to attach less privileged users out-of-box, a further investigation is still required.
