### ISSUE TITLE
OpenJ9-JDK17 mockito test failed on s390x_zos platform

### ISSUE THREAD

**Issue by sophiaxu0424** [eclipse-openj9/openj9#19331]
Failure link
------------

Public link to the failing test: **Grinder**: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39771/consoleFull

- BUILD_LIST:functional 
- test target: MockitoMockTest
- OS/architecture: s390x_zos
- sdk source: https://na-public.artifactory.swg-devops.com/artifactory/hyc-rt-java-delivery-generic-local/ibm/semeru-certified/17.0/17.0.9/s390x_zos/OpenJ9-JDK17-s390x_zos-20231109-105916.pax https://na-public.artifactory.swg-devops.com/artifactory/hyc-rt-java-delivery-generic-local/ibm/semeru-certified/17.0/17.0.9/s390x_zos/test-images.tar.gz
- public build SHAs (i.e. java -version output)
```
java version "17.0.9" 2023-10-17
10:17:24  IBM Semeru Runtime Certified Edition for z/OS 17.0.9.0 (build 17.0.9+9)
10:17:24  IBM J9 VM 17.0.9.0 (build ibm-jdk17-zOS-17.0.9-ec096f58390, JRE 17 z/OS s390x-64-Bit Compressed References 20231109_47 (JIT enabled, AOT enabled)
10:17:24  OpenJ9   - ec096f58390
10:17:24  OMR      - 8b64d40aba6
10:17:24  IBM      - 970f576
10:17:24  JCL      - 30d13b11a3f based on jdk-17.0.9+9)
```

Optional info
-------------
will test on jdk8 and 11 as well, post the grinder links when available.

- intermittent failure (yes|no): 
- regression or new test:  
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output (captured from console output)
---------------------------------------------
Include test case name, stack trace output.  If test fails with a crash, please include a link to the artifacts (xxxx_test_output.tar.gz) as they include the core/dmp files.  Artifacts are either stored as an attachment to the CI server job itself or as a link from the job to an Artifactory location.
```
10:20:24  TESTING:
10:20:25  Call Mockito.mock(ArrayList.class)
10:20:30  Exception in thread "main" java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
10:20:30  	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:84)
10:20:30  	at jdk.proxy2/jdk.proxy2.$Proxy3.isTypeMockable(Unknown Source)
10:20:30  	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:78)
10:20:30  	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
10:20:30  	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:274)
10:20:30  	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:235)
10:20:30  	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:86)
10:20:30  	at org.mockito.Mockito.mock(Mockito.java:2104)
10:20:30  	at org.mockito.Mockito.mock(Mockito.java:2019)
10:20:30  	at test.java.MockitoMockTest.main(MockitoMockTest.java:9)
10:20:30  Caused by: java.lang.IllegalStateException: Internal problem occurred, please report it. Mockito is unable to load the default implementation of class that is a part of Mockito distribution. Failed to load interface org.mockito.plugins.MockMaker
10:20:30  	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:105)
10:20:30  	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.getDefaultPlugin(DefaultMockitoPlugins.java:79)
10:20:30  	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:75)
10:20:30  	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:50)
10:20:30  	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:27)
10:20:30  	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:22)
10:20:30  	at org.mockito.internal.MockitoCore.<clinit>(MockitoCore.java:73)
10:20:30  	at org.mockito.Mockito.<clinit>(Mockito.java:1683)
10:20:30  	... 1 more
10:20:30  Caused by: java.lang.reflect.InvocationTargetException
10:20:30  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:20:30  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
10:20:30  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:20:30  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
10:20:30  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
10:20:30  	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:103)
10:20:30  	... 8 more
10:20:30  Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
10:20:30  Could not initialize inline Byte Buddy mock maker.
10:20:30  	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:260)
10:20:30  	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:23)
10:20:30  	... 14 more
10:20:30  Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process
10:20:30  	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:706)
10:20:30  	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:636)
10:20:30  	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:616)
10:20:30  	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:568)
10:20:30  	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:545)
10:20:30  	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<clinit>(InlineDelegateByteBuddyMockMaker.java:133)
10:20:30  	... 15 more
10:20:30  
10:20:30  It appears as if your JDK does not supply a working agent attachment mechanism.
```

**Comment by pshipton** [comment]
This should be reported to IBM, not OpenJ9. 

Attach API is disabled by default on z/OS. Run with `-Dcom.ibm.tools.attach.enable=yes`
