### ISSUE TITLE
MessageDigest/TestDigestIOStream ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19339]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_OMR_testList_1/109
jdk_security1_1
java/security/MessageDigest/TestDigestIOStream.java
```
07:09:57  STDOUT:
07:09:57  testDigestOnOff failed at:SHA-224/BUFFER_READ/6250000 with unexpected exception
07:09:57  STDERR:
07:09:57  java.lang.ArrayIndexOutOfBoundsException
07:09:57  	at java.io.ByteArrayInputStream.read(ByteArrayInputStream.java:194)
07:09:57  	at java.security.DigestInputStream.read(DigestInputStream.java:161)
07:09:57  	at TestDigestIOStream.testDigestOnOff(TestDigestIOStream.java:155)
07:09:57  	at TestDigestIOStream.run(TestDigestIOStream.java:85)
07:09:57  	at TestDigestIOStream.main(TestDigestIOStream.java:61)
```

**Comment by pshipton** [comment]
10x x 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/3483/
