### ISSUE TITLE
jdk_vector_0_FAILED jdk/incubator/vector/Float64VectorTests.java NullPointerException: Cannot throw exception

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19333]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_aarch64_linux_testList_2/25/)(`rhel8-aarch64-6`):
```
openjdk version "22-beta" 2024-03-19
IBM Semeru Runtime Open Edition 22+36-202404170030 (build 22-beta+36-202404170030)
Eclipse OpenJ9 VM 22+36-202404170030 (build master-f1565c18f, JRE 22 Linux aarch64-64-Bit Compressed References 20240417_46 (JIT enabled, AOT enabled)
OpenJ9   - f1565c18f
OMR      - 2f492f4e3
JCL      - ed6803212 based on jdk-22+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_vector_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk22_j9_extended.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F46%2Fibm-semeru-open-jdk_aarch64_linux_JDK22U_2024-04-17-00-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-aarch64-openj9%2F46%2Fibm-semeru-open-testimage_aarch64_linux_JDK22U_2024-04-17-00-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=22&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk22&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=27&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-04-17T05:06:45.930Z] variation: Mode150
[2024-04-17T05:06:45.930Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-04-17T05:39:02.581Z] TEST: jdk/incubator/vector/Float64VectorTests.java

[2024-04-17T05:39:02.587Z] test Float64VectorTests.unsliceUnaryFloat64VectorTests(float[cornerCaseValue(i)]): failure
[2024-04-17T05:39:02.587Z] java.lang.NullPointerException: Cannot throw exception
[2024-04-17T05:39:02.587Z] 	at java.base/jdk.internal.vm.vector.VectorSupport.shuffleToVector(VectorSupport.java:262)
[2024-04-17T05:39:02.587Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector$Float64Shuffle.toVector(Float64Vector.java:810)
[2024-04-17T05:39:02.587Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector$Float64Shuffle.toVector(Float64Vector.java:774)
[2024-04-17T05:39:02.587Z] 	at jdk.incubator.vector/jdk.incubator.vector.FloatVector.unsliceTemplate(FloatVector.java:2232)
[2024-04-17T05:39:02.587Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector.unslice(Float64Vector.java:432)
[2024-04-17T05:39:02.587Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector.unslice(Float64Vector.java:41)
[2024-04-17T05:39:02.587Z] 	at Float64VectorTests.unsliceUnaryFloat64VectorTests(Float64VectorTests.java:3657)
[2024-04-17T05:39:02.587Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-04-17T05:39:02.587Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2024-04-17T05:39:02.587Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2024-04-17T05:39:02.587Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
[2024-04-17T05:39:02.587Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2024-04-17T05:39:02.587Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2024-04-17T05:39:02.587Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2024-04-17T05:39:02.587Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2024-04-17T05:39:02.587Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2024-04-17T05:39:02.587Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2024-04-17T05:39:02.587Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2024-04-17T05:39:02.587Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2024-04-17T05:39:02.587Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2024-04-17T05:39:02.587Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2024-04-17T05:39:02.587Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2024-04-17T05:39:02.587Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2024-04-17T05:39:02.587Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
[2024-04-17T05:39:02.587Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
[2024-04-17T05:39:02.587Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-04-17T05:39:02.587Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-04-17T05:39:02.587Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-04-17T05:39:02.587Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)

[2024-04-17T05:39:02.587Z] 
[2024-04-17T05:39:02.587Z] ===============================================
[2024-04-17T05:39:02.587Z] jdk/incubator/vector/Float64VectorTests.java
[2024-04-17T05:39:02.587Z] Total tests run: 3211, Passes: 3203, Failures: 8, Skips: 0
[2024-04-17T05:39:02.587Z] ===============================================
[2024-04-17T05:39:02.587Z] 
[2024-04-17T05:39:02.587Z] STDERR:
[2024-04-17T05:39:02.587Z] WARNING: Using incubator modules: jdk.incubator.vector
[2024-04-17T05:39:02.587Z] java.lang.Exception: failures: 8
[2024-04-17T05:39:02.587Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:104)
[2024-04-17T05:39:02.587Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
[2024-04-17T05:39:02.587Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-04-17T05:39:02.587Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-04-17T05:39:02.587Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-04-17T05:39:02.587Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-04-17T05:39:02.587Z] 
[2024-04-17T05:39:02.587Z] JavaTest Message: Test threw exception: java.lang.Exception: failures: 8

[2024-04-17T06:34:54.390Z] Test results: passed: 72; failed: 1
[2024-04-17T06:34:59.357Z] Report written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_testList_2/aqa-tests/TKG/output_17133259812212/jdk_vector_0/report/html/report.html
[2024-04-17T06:34:59.357Z] Results written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_aarch64_linux_testList_2/aqa-tests/TKG/output_17133259812212/jdk_vector_0/work
[2024-04-17T06:34:59.357Z] Error: Some tests failed or other problems occurred.
[2024-04-17T06:34:59.357Z] -----------------------------------
[2024-04-17T06:34:59.357Z] jdk_vector_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39914/) - passed

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_extended.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_extended.openjdk_aarch64_linux_testList_1/85/)
```
[2025-07-23T08:07:28.941Z] variation: Mode650
[2025-07-23T08:07:28.941Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-07-23T08:55:14.493Z] TEST: jdk/incubator/vector/Float64VectorTests.java

[2025-07-23T08:55:14.497Z] test Float64VectorTests.unsliceUnaryFloat64VectorTests(float[i + 1]): failure
[2025-07-23T08:55:14.497Z] java.lang.NullPointerException: Cannot throw exception because the return value of "java.lang.Class.newInternalError(java.lang.Exception)" is null
[2025-07-23T08:55:14.497Z] 	at java.base/java.lang.Class.copyFields(Class.java:4297)
[2025-07-23T08:55:14.497Z] 	at java.base/java.lang.Class.lookupCachedFields(Class.java:4311)
[2025-07-23T08:55:14.497Z] 	at java.base/java.lang.Class.getDeclaredFields(Class.java:838)
[2025-07-23T08:55:14.497Z] 	at java.base/jdk.internal.vm.vector.VectorSupport.isNonCapturingLambda(VectorSupport.java:788)
[2025-07-23T08:55:14.497Z] 	at java.base/jdk.internal.vm.vector.VectorSupport.shuffleToVector(VectorSupport.java:269)
[2025-07-23T08:55:14.497Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector$Float64Shuffle.toVector(Float64Vector.java:817)
[2025-07-23T08:55:14.497Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector$Float64Shuffle.toVector(Float64Vector.java:781)
[2025-07-23T08:55:14.497Z] 	at jdk.incubator.vector/jdk.incubator.vector.FloatVector.unsliceTemplate(FloatVector.java:2245)
[2025-07-23T08:55:14.497Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector.unslice(Float64Vector.java:432)
[2025-07-23T08:55:14.497Z] 	at jdk.incubator.vector/jdk.incubator.vector.Float64Vector.unslice(Float64Vector.java:41)
[2025-07-23T08:55:14.497Z] 	at Float64VectorTests.unsliceUnaryFloat64VectorTests(Float64VectorTests.java:3667)
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/53212/) - in progress, 6 failures were reproduced so far

**Comment by vij-singh** [comment]
@gita-omr @BradleyWood @knn-k This has landed in the Java 24 and therefore is very urgent. Could someone have a look ASAP please?

**Comment by pshipton** [comment]
Java 24 might be the wrong milestone, if the failure only occurs in the head stream and not in the 0.54 branches.

**Comment by pshipton** [comment]
0.54 grinder https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/53268/ - the failure is recreated
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/5963/consoleFull

**Comment by pshipton** [comment]
Tested JVM is post 0.54 split
```
04:05:34  Eclipse OpenJ9 VM 24.0.2+12-202507230004 (build master-219a4ac9d1, JRE 24 Linux aarch64-64-Bit Compressed References 20250723_109 (JIT enabled, AOT enabled)
04:05:34  OpenJ9   - 219a4ac9d1
04:05:34  OMR      - b1c9a2579
04:05:34  JCL      - ca85d36ef based on jdk-24.0.2+12)
```

0.54 split 
openj9 - f6940e28fa869
omr - f3fe0c11425

Newer changes in the head stream.
https://github.com/eclipse-openj9/openj9/compare/f6940e28fa869...219a4ac9d1
https://github.com/eclipse-openj9/openj9-omr/compare/b1c9a2579...f3fe0c11425

~https://github.com/eclipse-openj9/openj9/pull/15695 was added, which is likely the cause.
It's also attributed to https://github.com/eclipse-openj9/openj9/issues/22286~

**Comment by vij-singh** [comment]
@gita-omr @BradleyWood  Ok, we'll need to fix this in the 0.54 (Java 24) split
@pshipton Could you add the JIT label please?

**Comment by BradleyWood** [comment]
Sorry, I don't follow. #15695 is not in 0.54, and I don't understand what it has to do with this issue, its an arrch64 issue?

**Comment by pshipton** [comment]
Right sorry, I missed the failure was on aarch64, so https://github.com/eclipse-openj9/openj9/pull/15695 can't be the cause. In this case, it seems likely a problem in 0.54 that should be resolved. To confirm via the grinder in https://github.com/eclipse-openj9/openj9/issues/19333#issuecomment-3114312175

**Comment by pshipton** [comment]
The grinder confirmed the failures is in the 0.54 stream.

**Comment by knn-k** [comment]
There is an issue #20389 with JDK 21/23/24 on AArch64 Linux and on x86 Linux that has been assigned to @BradleyWood.
It is similar to https://github.com/eclipse-openj9/openj9/issues/19333#issuecomment-3110600479: NPE "Cannot throw exception  because the return value ..." at `java.base/java.lang.Class.copyFields()`.

I guess we need to recognize the two patterns: NPE at `VectorSupport.shuffleToVector()` and NPE at `Class.copyFields()`.  Maybe they are related each other, though.

**Comment by pshipton** [comment]
Since https://github.com/eclipse-openj9/openj9/issues/19333#issuecomment-3110600479 seems a dup of https://github.com/eclipse-openj9/openj9/issues/20389 and it's a long standing issue, I'll move this out of the 0.54 milestone.
