### ISSUE TITLE
jdk/internal/vm/Continuation/OSRTest UnsatisfiedLinkError WhiteBox.registerNatives

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19357]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Nightly_testList_0/1
jdk_lang
jdk/internal/vm/Continuation/OSRTest.java
```
22:36:52  java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V
22:36:52  	at jdk.test.whitebox.WhiteBox.<clinit>(WhiteBox.java:67)
22:36:52  	at OSRTest.<clinit>(OSRTest.java:52)
```

**Comment by pshipton** [comment]
@babsingh I assume this should be a perm exclude?

**Comment by babsingh** [comment]
> I assume this should be a perm exclude?

Correct, the test checks an internal RI feature which is implemented differently in OpenJ9. 

The test has been disabled through: https://github.com/adoptium/aqa-tests/pull/5257. Added the `perm excluded` label, and closing the issue.
