### ISSUE TITLE
cmdLineTester_decompilationTests_nongold decomp002 timeout TR_IProfiler::stopIProfilerThread

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19356]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/765 - [rh7-390-2](https://openj9-jenkins.osuosl.org/computer/rh7-390-2)
cmdLineTester_decompilationTests_nongold_3

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/765/functional_test_output.tar.gz
```
01:09:27  Testing: decomp002
01:09:27  Test start time: 2024/04/20 01:09:26 Eastern Standard Time
01:09:27  Running command: "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump -Xgcthreads1  -Xdump:system:events=abort  -agentlib:jvmtitest=test:decomp002 -cp "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
01:09:27  Time spent starting: 1 milliseconds
01:19:36  ***[TEST INFO 2024/04/20 01:19:26] ProcessKiller detected a timeout after 600000 milliseconds!***
01:19:36  ***[TEST INFO 2024/04/20 01:19:26] executing /usr/bin/gdb -batch -x /tmp/debugger7825586593676401300.txt /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java 46913***
01:19:36  GDB OUT [Thread debugging using libthread_db enabled]
01:19:36  GDB OUT Using host libthread_db library "/lib64/libthread_db.so.1".
01:19:36  GDB OUT 0x000003ff7e4093e4 in pthread_join () from /lib64/libpthread.so.0
01:19:36  GDB OUT From                To                  Syms Read   Shared Object Library
01:19:36  GDB OUT 0x000003ff7e482318  0x000003ff7e490678  Yes (*)     /lib64/libz.so.1
01:19:36  GDB OUT 0x000003ff7e405c00  0x000003ff7e412320  Yes (*)     /lib64/libpthread.so.0
01:19:36  GDB OUT 0x000003ff7e382ef0  0x000003ff7e38cda8  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/../lib/jli/libjli.so
01:19:36  GDB OUT 0x000003ff7e300ef0  0x000003ff7e301bb8  Yes (*)     /lib64/libdl.so.2
01:19:36  GDB OUT 0x000003ff7e122270  0x000003ff7e25e038  Yes (*)     /lib64/libc.so.6
01:19:36  GDB OUT 0x000003ff7e580cf0  0x000003ff7e59cf60  Yes (*)     /lib/ld64.so.1
01:19:36  GDB OUT 0x000003ff7e505360  0x000003ff7e50d858  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/server/libjvm.so
01:19:36  GDB OUT 0x000003ff7e088368  0x000003ff7e0b7f98  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libjvm.so
01:19:36  GDB OUT 0x000003ff7dee8e30  0x000003ff7df75178  Yes (*)     /lib64/libstdc++.so.6
01:19:36  GDB OUT 0x000003ff7dd858b8  0x000003ff7ddd4e28  Yes (*)     /lib64/libm.so.6
01:19:36  GDB OUT 0x000003ff7dd024b8  0x000003ff7dd0cca8  Yes (*)     /lib64/libgcc_s.so.1
01:19:36  GDB OUT 0x000003ff7e000a18  0x000003ff7e0014c0  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libomrsig.so
01:19:36  GDB OUT 0x000003ff7da1c8e8  0x000003ff7dc7c358  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
01:19:36  GDB OUT 0x000003ff7d90c4a0  0x000003ff7d962548  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9prt29.so
01:19:36  GDB OUT 0x000003ff7d884fc0  0x000003ff7d8929b0  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9thr29.so
01:19:36  GDB OUT 0x000003ff7d800c50  0x000003ff7d803db8  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9hookable29.so
01:19:36  GDB OUT 0x000003ff7d781048  0x000003ff7d78ff98  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9zlib29.so
01:19:36  GDB OUT 0x000003ff7d682560  0x000003ff7d685d08  Yes (*)     /lib64/librt.so.1
01:19:36  GDB OUT 0x000003ff7d504d10  0x000003ff7d537a20  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9dmp29.so
01:19:36  GDB OUT 0x000003ff7d4836b0  0x000003ff7d4a58b0  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9trc29.so
01:19:36  GDB OUT 0x000003ff7d3822c0  0x000003ff7d38a840  Yes (*)     /lib64/libnss_files.so.2
01:19:36  GDB OUT 0x000003ff7c4feb40  0x000003ff7d04fc28  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9jit29.so
01:19:36  GDB OUT 0x000003ff7c12a930  0x000003ff7c33d060  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9gc29.so
01:19:36  GDB OUT 0x000003ff7198f888  0x000003ff71a0c998  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9vrb29.so
01:19:36  GDB OUT 0x000003ff71886f50  0x000003ff71905ec0  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9shr29.so
01:19:36  GDB OUT 0x000003ff7c085a08  0x000003ff7c0d3008  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9jvmti29.so
01:19:36  GDB OUT 0x000003ff717914f0  0x000003ff717ef2b8  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libjclse29.so
01:19:36  GDB OUT 0x000003ff6f101198  0x000003ff6f104df8  Yes (*)     /lib64/libnss_dns.so.2
01:19:36  GDB OUT 0x000003ff6f083cd8  0x000003ff6f093c68  Yes (*)     /lib64/libresolv.so.2
01:19:36  GDB OUT 0x000003ff6f002028  0x000003ff6f00b158  Yes (*)     /lib64/libnss_myhostname.so.2
01:19:36  GDB OUT 0x000003ff6ef81688  0x000003ff6ef835e8  Yes (*)     /lib64/libcap.so.2
01:19:36  GDB OUT 0x000003ff6ef0a7d0  0x000003ff6ef46878  Yes (*)     /lib64/libdw.so.1
01:19:36  GDB OUT 0x000003ff6ee81638  0x000003ff6ee838f8  Yes (*)     /lib64/libattr.so.1
01:19:36  GDB OUT 0x000003ff6ee03340  0x000003ff6ee16a58  Yes (*)     /lib64/libelf.so.1
01:19:36  GDB OUT 0x000003ff6ed83690  0x000003ff6ed9d3b8  Yes (*)     /lib64/liblzma.so.5
01:19:36  GDB OUT 0x000003ff6ed01a08  0x000003ff6ed11028  Yes (*)     /lib64/libbz2.so.1
01:19:36  GDB OUT 0x000003ff6f183668  0x000003ff6f197758  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libjimage.so
01:19:36  GDB OUT 0x000003ff37f89000  0x000003ff37fa7ef8  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/openjdk-test-image/openj9/libjvmtitest.so
01:19:36  GDB OUT 0x000003ff37f09a68  0x000003ff37f19f00  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libjava.so
01:19:36  GDB OUT 0x000003ff37e846a0  0x000003ff37e8b378  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libverify.so
01:19:36  GDB OUT 0x000003ff37e025a8  0x000003ff37e06968  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libzip.so
01:19:36  GDB OUT 0x000003ff37b87530  0x000003ff37b8f340  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libnio.so
01:19:36  GDB OUT 0x000003ff37b04dc0  0x000003ff37b13980  Yes (*)     /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/libnet.so
01:19:36  GDB OUT 0x000003ff37880798  0x000003ff37882760  Yes (*)     /usr/lib64/gconv/UTF8_UTF16_Z9.so
01:19:36  GDB OUT (*): Shared library is missing debugging information.
01:19:36  GDB OUT r0             0x0	0
01:19:36  GDB OUT r1             0x3ff7e5f49e0	4395871717856
01:19:36  GDB OUT r2             0xfffffffffffffe00	18446744073709551104
01:19:36  GDB OUT r3             0x0	0
01:19:36  GDB OUT r4             0xb745	46917
01:19:36  GDB OUT r5             0x0	0
01:19:36  GDB OUT r6             0x1	1
01:19:36  GDB OUT r7             0x40000	262144
01:19:36  GDB OUT r8             0x3ffcf7f5738	4397232772920
01:19:36  GDB OUT r9             0x3ffcf7f5800	4397232773120
01:19:36  GDB OUT r10            0x3ff7e5f4d30	4395871718704
01:19:36  GDB OUT r11            0x3ff7e5f6700	4395871725312
01:19:36  GDB OUT r12            0x3ff7e5a4f58	4395871391576
01:19:36  GDB OUT r13            0x3ff7e5f4910	4395871717648
01:19:36  GDB OUT r14            0x3ff7e40939e	4395869705118
01:19:36  GDB OUT r15            0x3ffcf7f5698	4397232772760
01:19:36  GDB OUT pc             0x3ff7e4093e4	0x3ff7e4093e4 <pthread_join+164>
01:19:36  GDB OUT cc             0x2	2
01:19:36  GDB OUT   Id   Target Id         Frame 
01:19:36  GDB OUT   25   Thread 0x3ff7e5f4910 (LWP 46917) "main" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   24   Thread 0x3ff7e4ff910 (LWP 46918) "Signal Reporter" 0x000003ff7e40e854 in do_futex_wait () from /lib64/libpthread.so.0
01:19:36  GDB OUT   23   Thread 0x3ff7e2ff910 (LWP 46927) "JIT Sampler" 0x000003ff7e40c6f6 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   22   Thread 0x3ff7e4be910 (LWP 46928) "JIT IProfiler" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   21   Thread 0x3ff7e07f910 (LWP 46929) "Common-Cleaner" 0x000003ff7e40c6f6 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   20   Thread 0x3ff7de7f910 (LWP 46930) "Finalizer main" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   19   Thread 0x3ff7dd7f910 (LWP 46931) "Concurrent Mark" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   18   Thread 0x3ff7d9ff910 (LWP 46935) "Thread-0" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   17   Thread 0x3ff7d77f910 (LWP 46936) "Thread-1" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   16   Thread 0x3ff7d6ff910 (LWP 46937) "Thread-2" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   15   Thread 0x3ff7d5c3910 (LWP 46938) "Thread-3" 0x000003ff7e1ef932 in sched_yield () from /lib64/libc.so.6
01:19:36  GDB OUT   14   Thread 0x3ff7d4ff910 (LWP 46939) "Thread-4" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   13   Thread 0x3ff7d37f910 (LWP 46940) "Thread-5" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   12   Thread 0x3ff7c07f910 (LWP 46941) "Thread-6" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   11   Thread 0x3ff7197f910 (LWP 46942) "Thread-7" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   10   Thread 0x3ff7187f910 (LWP 46943) "Thread-8" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   9    Thread 0x3ff6f17f910 (LWP 46944) "Thread-9" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   8    Thread 0x3ff6f0ff910 (LWP 46945) "Thread-10" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   7    Thread 0x3ff6f07f910 (LWP 46946) "Thread-11" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   6    Thread 0x3ff6efff910 (LWP 46947) "Thread-12" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   5    Thread 0x3ff6eeff910 (LWP 46948) "Thread-13" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   4    Thread 0x3ff6ee7f910 (LWP 46949) "Thread-14" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT   3    Thread 0x3ff6edff910 (LWP 46950) "Thread-15" 0x000003ff7e1ef932 in sched_yield () from /lib64/libc.so.6
01:19:36  GDB OUT   2    Thread 0x3ff6ed7f910 (LWP 46951) "Finalizer threa" 0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT * 1    Thread 0x3ff7e5f6700 (LWP 46913) "java" 0x000003ff7e4093e4 in pthread_join () from /lib64/libpthread.so.0
01:19:36  GDB OUT 
01:19:36  GDB OUT Thread 25 (Thread 0x3ff7e5f4910 (LWP 46917)):
01:19:36  GDB OUT #0  0x000003ff7e40c3b2 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #1  0x000003ff7d8862e4 in monitor_enter_three_tier.constprop.0 () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9thr29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #2  0x000003ff7c943588 in TR_IProfiler::stopIProfilerThread() () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9jit29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #3  0x000003ff7c5ad63a in JitShutdown () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9jit29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #4  0x000003ff7c59dc20 in J9VMDllMain () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9jit29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #5  0x000003ff7da63616 in runShutdownStage.constprop.0 () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #6  0x000003ff7da6afcc in exitJavaVM () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #7  0x000003ff717eb686 in JVM_Halt_Impl () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libjclse29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #8  0x000003ff7dc72bc4 in ffi_call_SYSV () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #9  0x000003ff7dc7261a in ffi_call () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
01:19:36  GDB OUT No symbol table info available.
01:19:36  GDB OUT #10 0x000003ff7db1ccf2 in VM_DebugBytecodeInterpreterCompressed::run(J9VMThread*) () from /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
```

**Comment by pshipton** [comment]
@hzongaro fyi
