### ISSUE TITLE
abbs hang Waiting on com/ibm/jtc/test/jltf/threads/pooling/ThreadPoo

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19422]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=83938559)
[zOS S390] 80 Load_Level_2.abbs.5mins.Mode109 `-Xgcpolicy:gencon -Xint -Xnocompressedrefs`
fyrec50v

```
j> 13:37:54 20240430 13:37:53 Thread Control Engine INFO: Delinquent JobSet Primary still has 1 threads running.
j> 13:38:05 20240430 13:38:05 Runtime State Reporter IMPORTANT: 4494 tests complete, 1 currently running
```
```
1XMTHDINFO     Thread Details
NULL
3XMTHREADINFO      "main" J9VMThread:0x3B836100, omrthread_t:0x19C6D310, java/lang/Thread:0x1AF25928, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x19826800, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000101)
3XMCPUTIME               CPU usage total: 2.258000000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: java/lang/Thread@0x1B18D608 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.waitImpl(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:248)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:216)
4XESTACKTRACE                at java/lang/Thread.join(Thread.java:752)
4XESTACKTRACE                at java/lang/Thread.join(Thread.java:707)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/ThreadControlEngine.runWork(ThreadControlEngine.java:454)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/Launcher.runTest(Launcher.java:506)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/Launcher.launch(Launcher.java:227)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/Launcher.main(Launcher.java:164)
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "Concurrent Mark Helper" J9VMThread:0x3BBD3400, omrthread_t:0x19C6DA3C, java/lang/Thread:0x1AF4DAD8, state:R, prio=1
3XMJAVALTHREAD            (java/lang/Thread getId:0x2, isDaemon:true)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x19828800, native priority:0x0, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000001)
3XMCPUTIME               CPU usage total: 0.369000000 secs, current category="GC"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           No Java callstack associated with this thread
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "Finalizer thread" J9VMThread:0x3BBDCF00, omrthread_t:0x19C6DCA0, java/lang/Thread:0x1AF4DB70, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x3, isDaemon:true)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x19829000, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000001)
3XMCPUTIME               CPU usage total: 0.148000000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           No Java callstack associated with this thread
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "GC Worker" J9VMThread:0x3BBE4900, omrthread_t:0x19C6DF04, java/lang/Thread:0x1AF4DC08, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x4, isDaemon:true)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x1982A000, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000001)
3XMCPUTIME               CPU usage total: 11.420000000 secs, current category="GC"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           No Java callstack associated with this thread
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "ConfigurationReporter Writer Thread" J9VMThread:0x3C483400, omrthread_t:0x3C479C34, java/lang/Thread:0x1B18D590, state:CW, prio=10
3XMJAVALTHREAD            (java/lang/Thread getId:0x8, isDaemon:true)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x1982B000, native priority:0xA, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00080101)
3XMCPUTIME               CPU usage total: 1.125000000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: java/util/ArrayList@0x1B16C368 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.waitImpl(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:248)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:216)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/ConfigurationReporter$WriterLogic.getNextConfiguration(ConfigurationReporter.java:237)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/ConfigurationReporter$WriterLogic.doLoop(ConfigurationReporter.java:175)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/ConfigurationReporter$WriterLogic.run(ConfigurationReporter.java:168)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:825)
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "Thread Control Engine" J9VMThread:0x3C3AA100, omrthread_t:0x3C479E98, java/lang/Thread:0x1B18D608, state:CW, prio=6
3XMJAVALTHREAD            (java/lang/Thread getId:0x9, isDaemon:false)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x1982B800, native priority:0x6, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000401)
3XMCPUTIME               CPU usage total: 4.736000000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=430000 (0x68FB0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.sleepImpl(Native Method)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:977)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:960)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/ThreadControlEngine$ActionCommand.snooze(ThreadControlEngine.java:384)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/ThreadControlEngine$ActionCommand.run(ThreadControlEngine.java:201)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/LoggedRunnableWrapper.run(LoggedRunnableWrapper.java:40)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:825)
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "Thread-0" J9VMThread:0x43325F00, omrthread_t:0x4330D874, java/lang/Thread:0x1AFEE6E0, state:CW, prio=6
3XMJAVALTHREAD            (java/lang/Thread getId:0x6, isDaemon:false)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x198FB000, native priority:0x6, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00080101)
3XMCPUTIME               CPU usage total: 0.044000000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: com/ibm/jtc/test/jltf/RuntimeStatusReporter@0x1AFEE4D8 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=12288 (0x3000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.waitImpl(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:248)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:216)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/RuntimeStatusReporter$Reporter.run(RuntimeStatusReporter.java:108)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/LoggedRunnableWrapper.run(LoggedRunnableWrapper.java:40)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:825)
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "ClassCache Reaper" J9VMThread:0x435FC300, omrthread_t:0x440A639C, java/lang/Thread:0x1B6139B0, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x211, isDaemon:true)
3XMJAVALTHRCCL            No Java context classloader associated with this thread
3XMTHREADINFO1            (native thread ID:0x19900800, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000101)
3XMCPUTIME               CPU usage total: 0.167000000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: java/lang/ref/ReferenceQueue@0x1B60F5D8 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.waitImpl(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:248)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:216)
4XESTACKTRACE                at java/lang/ref/ReferenceQueue.remove(ReferenceQueue.java:137)
4XESTACKTRACE                at java/lang/ref/ReferenceQueue.remove(ReferenceQueue.java:109)
4XESTACKTRACE                at java/io/ClassCache$Reaper.run(ClassCache.java:222)
3XMTHREADINFO3           No native callstack available on this platform
NULL
3XMTHREADINFO      "Thread-455" J9VMThread:0x45F7B900, omrthread_t:0x435EFC84, java/lang/Thread:0x1CFCA448, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x3CE, isDaemon:false)
3XMJAVALTHRCCL            sun/misc/Launcher$AppClassLoader(0x1AF24BD0)
3XMTHREADINFO1            (native thread ID:0x198FC000, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000101)
3XMCPUTIME               CPU usage total: 0.817000000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: com/ibm/jtc/test/jltf/threads/pooling/ThreadPool@0x1B16B9D8 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.waitImpl(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:248)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:187)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/pooling/ThreadPool.getEntryBlocking(ThreadPool.java:370)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/pooling/ThreadPool.getEntryBlocking(ThreadPool.java:350)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/pooling/ThreadPool.shrinkPool(ThreadPool.java:315)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/pooling/ThreadPool.drainPool(ThreadPool.java:344)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/pooling/ThreadPool.access$000(ThreadPool.java:81)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/pooling/ThreadPool$1.run(ThreadPool.java:596)
4XESTACKTRACE                at com/ibm/jtc/test/jltf/threads/LoggedRunnableWrapper.run(LoggedRunnableWrapper.java:40)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:825)
3XMTHREADINFO3           No native callstack available on this platform
```

Thread-455 is `Waiting on: com/ibm/jtc/test/jltf/threads/pooling/ThreadPool@0x1B16B9D8 Owned by: <unowned>`
```
2LKMONINUSE      sys_mon_t:0x3D0F10E4 infl_mon_t: 0x3D0F1120:
3LKMONOBJECT       com/ibm/jtc/test/jltf/threads/pooling/ThreadPool@0x1B16B9D8: <unowned>
3LKNOTIFYQ            Waiting to be notified:
3LKWAITNOTIFY            "Thread-455" (J9VMThread:0x45F7B900)
```

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=85825623) - fyrec60i
[zOS S390 64bit Compressed Pointers] 80 Load_Level_2.abbs.5mins.Mode555
`-XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:counts="- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000",gcOnResolve,rtResolve,sampleInterval=2,scorchingSampleThreshold=10000,quickProfile -Xcheck:gc:vmthreads:all:quiet`
