### ISSUE TITLE
jdk_lang_0_FAILED jdk/lambda/vm/InterfaceAccessFlagsTest.java RuntimeException: IOException encountered during compilation

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19430]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_testList_0/595/)(`paix911`):
```
openjdk version "1.8.0_412-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_412-beta-202404302327-b08)
Eclipse OpenJ9 VM (build master-190a224a7, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20240430_918 (JIT enabled, AOT enabled)
OpenJ9   - 190a224a7
OMR      - 33a1542b9
JCL      - 915713102 based on jdk8u412-b08)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_lang_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_sanity.openjdk_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F918%2Fibm-semeru-open-jdk_ppc64_aix_JDK8U_2024-04-30-22-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-openj9%2F918%2Fibm-semeru-open-testimage_ppc64_aix_JDK8U_2024-04-30-22-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=750&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-05-01T01:23:42.027Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2024-05-01T01:23:42.027Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Xverbosegclog 

[2024-05-01T01:31:25.440Z] TEST: jdk/lambda/vm/InterfaceAccessFlagsTest.java

[2024-05-01T01:31:25.441Z] config separate.TestHarness.reset(): success
[2024-05-01T01:31:25.441Z] test vm.InterfaceAccessFlagsTest.testStaticMethodCall(): failure
[2024-05-01T01:31:25.441Z] java.lang.RuntimeException: IOException encountered during compilation
[2024-05-01T01:31:25.441Z] 	at separate.Compiler.compileOne(Compiler.java:191)
[2024-05-01T01:31:25.441Z] 	at separate.Compiler.compileHierarchy(Compiler.java:135)
[2024-05-01T01:31:25.441Z] 	at separate.Compiler.compile(Compiler.java:111)
[2024-05-01T01:31:25.441Z] 	at vm.InterfaceAccessFlagsTest.testMethodCallWithFlag(InterfaceAccessFlagsTest.java:56)
[2024-05-01T01:31:25.441Z] 	at vm.InterfaceAccessFlagsTest.testStaticMethodCall(InterfaceAccessFlagsTest.java:81)
[2024-05-01T01:31:25.441Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-01T01:31:25.441Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-05-01T01:31:25.441Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-01T01:31:25.441Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-05-01T01:31:25.441Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2024-05-01T01:31:25.441Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2024-05-01T01:31:25.441Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2024-05-01T01:31:25.441Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2024-05-01T01:31:25.441Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2024-05-01T01:31:25.441Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2024-05-01T01:31:25.441Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2024-05-01T01:31:25.441Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2024-05-01T01:31:25.441Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2024-05-01T01:31:25.441Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2024-05-01T01:31:25.441Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2024-05-01T01:31:25.441Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2024-05-01T01:31:25.441Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2024-05-01T01:31:25.441Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2024-05-01T01:31:25.441Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2024-05-01T01:31:25.441Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2024-05-01T01:31:25.441Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2024-05-01T01:31:25.441Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2024-05-01T01:31:25.441Z] 	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
[2024-05-01T01:31:25.441Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-01T01:31:25.441Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-05-01T01:31:25.441Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2024-05-01T01:31:25.441Z] 	at java.lang.Thread.run(Thread.java:826)
[2024-05-01T01:31:25.441Z] Test InterfaceAccessFlagsTest.testStaticMethodCall FAILED
[2024-05-01T01:31:25.441Z] config separate.TestHarness.printError(org.testng.internal.TestResult@c604f159): success
[2024-05-01T01:31:25.441Z] config separate.TestHarness.reset(): success
[2024-05-01T01:31:25.441Z] 
[2024-05-01T01:31:25.441Z] ===============================================
[2024-05-01T01:31:25.441Z] jdk/lambda/vm/InterfaceAccessFlagsTest.java
[2024-05-01T01:31:25.441Z] Total tests run: 3, Failures: 3, Skips: 0

[2024-05-01T01:33:12.598Z] jdk_lang_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40242/) - all failed on paix911, passed on paix816, paix817, paix819, paix907.

**Comment by pshipton** [comment]
Opened infrastructure/issues/9284
