### ISSUE TITLE
jdk_security3_0_FAILED sun/security/ec/TestEC.java ProviderException: Could not convert keys to native format

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19479]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_aarch64_linux_testList_0/48/)(`rhel8-aarch64-2`):
```
openjdk version "1.8.0_422-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_422-beta-202405092304-b01)
Eclipse OpenJ9 VM (build master-d9a1f142cc, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20240509_912 (JIT enabled, AOT enabled)
OpenJ9   - d9a1f142cc
OMR      - 9a431c440
JCL      - 4cadd3252 based on jdk8u422-b01)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_extended.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F912%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2024-05-09-22-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F912%2Fibm-semeru-open-testimage_aarch64_linux_JDK8U_2024-05-09-22-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=215&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-05-10T00:17:59.590Z] variation: Mode150
[2024-05-10T00:17:59.590Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-05-10T00:22:58.832Z] TEST: sun/security/ec/TestEC.java

[2024-05-10T00:22:58.832Z] STDERR:
[2024-05-10T00:22:58.832Z] java.security.ProviderException: Could not convert keys to native format
[2024-05-10T00:22:58.832Z] 	at sun.security.ec.NativeECDSASignature.engineVerify(NativeECDSASignature.java:437)
[2024-05-10T00:22:58.832Z] 	at java.security.Signature$Delegate.engineVerify(Signature.java:1392)
[2024-05-10T00:22:58.832Z] 	at java.security.Signature.verify(Signature.java:769)
[2024-05-10T00:22:58.832Z] 	at TestECDSA.verify(TestECDSA.java:97)
[2024-05-10T00:22:58.833Z] 	at TestECDSA.test(TestECDSA.java:182)
[2024-05-10T00:22:58.833Z] 	at TestECDSA.main(TestECDSA.java:155)
[2024-05-10T00:22:58.833Z] 	at TestEC.main0(TestEC.java:92)
[2024-05-10T00:22:58.833Z] 	at TestEC.main(TestEC.java:70)
[2024-05-10T00:22:58.833Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-10T00:22:58.833Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-05-10T00:22:58.833Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-10T00:22:58.833Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-05-10T00:22:58.833Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-05-10T00:22:58.833Z] 	at java.lang.Thread.run(Thread.java:826)
[2024-05-10T00:22:58.833Z] 
[2024-05-10T00:22:58.833Z] JavaTest Message: Test threw exception: java.security.ProviderException: Could not convert keys to native format

[2024-05-10T00:44:33.615Z] Test results: passed: 610; failed: 1
[2024-05-10T00:44:37.041Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux_testList_0/aqa-tests/TKG/output_17153001803196/jdk_security3_0/report/html/report.html
[2024-05-10T00:44:37.041Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_aarch64_linux_testList_0/aqa-tests/TKG/output_17153001803196/jdk_security3_0/work
[2024-05-10T00:44:37.041Z] Error: Some tests failed or other problems occurred.
[2024-05-10T00:44:37.041Z] -----------------------------------
[2024-05-10T00:44:37.041Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40515/) - all failed

[JDK8 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_ppc64le_linux_testList_0/48/)(`rtj-rhel8le-rtp-test-qywpx-1`)
```
[2024-05-09T23:46:01.643Z] variation: Mode150
[2024-05-09T23:46:01.643Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 
[2024-05-09T23:51:51.679Z] TEST: sun/security/ec/TestEC.java
[2024-05-09T23:51:51.681Z] STDERR:
[2024-05-09T23:51:51.681Z] java.security.ProviderException: Keys could not be converted to native OpenSSL format
[2024-05-09T23:51:51.681Z] 	at sun.security.ec.NativeECDSASignature.engineSign(NativeECDSASignature.java:403)
[2024-05-09T23:51:51.681Z] 	at java.security.Signature$Delegate.engineSign(Signature.java:1380)
[2024-05-09T23:51:51.681Z] 	at java.security.Signature.sign(Signature.java:696)
[2024-05-09T23:51:51.681Z] 	at TestCurves.testSigning(TestCurves.java:132)
[2024-05-09T23:51:51.681Z] 	at TestCurves.main(TestCurves.java:85)
[2024-05-09T23:51:51.681Z] 	at TestEC.main0(TestEC.java:93)
[2024-05-09T23:51:51.681Z] 	at TestEC.main(TestEC.java:70)
```

**Comment by pshipton** [comment]
@jasonkatonica can someone take a look pls.

**Comment by pshipton** [comment]
Related to https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/752 I assume.
@KostasTsiounis

**Comment by KostasTsiounis** [comment]
Does it just present itself on `RHEL` and `Java8`, or has it been seen elsewhere?

**Comment by JasonFengJ9** [comment]
> has it been seen elsewhere?

Yes, it is also seen at
[JDK8 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_4/2773/console)(`sles15-aarch64-6`)
[JDK11 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_2/51/)(`rhel9-aarch64-2`)

**Comment by JasonFengJ9** [comment]
> Question is, have you seen that failure before?
java.lang.Exception: *** Test 'Client JSSE - Server JSSE' failed ***

@KostasTsiounis It appears a known failure
* https://github.com/eclipse-openj9/openj9/issues/18846

RI failed this test as well.

**Comment by KostasTsiounis** [comment]
@JasonFengJ9 This should be fixed now after:
- OpenJDK11:		https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/783
- OpenJDK8:		https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/755

**Comment by JasonFengJ9** [comment]
Not seen in the latest nightly builds.

Closing..
