### ISSUE TITLE
testSCCMLTests1_openj9_0_FAILED Required condition was not found

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19480]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/510/)(`ubu22-aarch64-2`):
```
java version "11.0.24-beta" 2024-07-16
IBM Semeru Runtime Certified Edition 11.0.24+2-202405092210 (build 11.0.24-beta+2)
Eclipse OpenJ9 VM 11.0.24+2-202405092210 (build master-7487893149, JRE 11 Linux aarch64-64-Bit Compressed References 20240509_588 (JIT enabled, AOT enabled)
OpenJ9   - 7487893149
OMR      - 1bcf96982
JCL      - 765bbe3498 based on jdk-11.0.24+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=testSCCMLTests1_openj9_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.functional_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F588%2Fibm-semeru-certified-jdk_aarch64_linux_JDK11U_2024-05-09-22-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F588%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2024-05-09-22-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=617&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-05-10T00:38:21.163Z] variation: Mode110
[2024-05-10T00:38:21.163Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

[2024-05-10T00:39:03.515Z] Testing: Test 69-b: Make sure CustomClassLoader (not using SCC Java API) stored classes in SCC as orphan
[2024-05-10T00:39:03.515Z] Test start time: 2024/05/10 00:39:01 Coordinated Universal Time
[2024-05-10T00:39:03.515Z] Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=ShareClassesCMLTests,printStats=romclass+orphan
[2024-05-10T00:39:03.515Z] Time spent starting: 1 milliseconds
[2024-05-10T00:39:03.515Z] Time spent executing: 102 milliseconds
[2024-05-10T00:39:03.515Z] Test result: FAILED
[2024-05-10T00:39:07.874Z] >> Required condition was not found: [Output match: ORPHAN: org/openj9/test/classtests/UnsafeBootClass]
[2024-05-10T00:39:07.874Z] >> Required condition was not found: [Output match: ORPHAN: org/openj9/test/classtests/AnonClassAndUnsafeClassTest]

[2024-05-10T00:39:07.874Z] Testing: Test 69-c: Make sure orpahn classes from CustomClassLoader are re-used via compareROMClassForEquality when -XX:+ShareOrphans specified
[2024-05-10T00:39:07.874Z] Test start time: 2024/05/10 00:39:07 Coordinated Universal Time
[2024-05-10T00:39:07.874Z] Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=ShareClassesCMLTests -XX:-ShareOrphans -XX:+ShareOrphans -Xtrace:print={j9bcu.270} -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/utils/utils.jar org.openj9.test.classtests.ShareOrphanTest
[2024-05-10T00:39:07.874Z] Time spent starting: 1 milliseconds
[2024-05-10T00:39:08.879Z] Time spent executing: 498 milliseconds
[2024-05-10T00:39:08.879Z] Test result: FAILED
[2024-05-10T00:39:08.879Z] >> Required condition was not found: [Output match: compareROMClassForEquality returns 1 for class name 'org/openj9/test/classtests/UnsafeBootClass']
[2024-05-10T00:39:08.879Z] >> Required condition was not found: [Output match: compareROMClassForEquality returns 1 for class name 'org/openj9/test/classtests/AnonClassAndUnsafeClassTest']

[2024-05-10T00:39:11.111Z] Testing: Test 70-c: Make sure ShareOrphanTest classes are stored as orphans and Hanoi classes are stored as romclasses
[2024-05-10T00:39:11.111Z] Test start time: 2024/05/10 00:39:10 Coordinated Universal Time
[2024-05-10T00:39:11.111Z] Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:printStats=romclass+orphan
[2024-05-10T00:39:11.111Z] Time spent starting: 1 milliseconds
[2024-05-10T00:39:11.111Z] Time spent executing: 106 milliseconds
[2024-05-10T00:39:11.111Z] Test result: FAILED
[2024-05-10T00:39:15.283Z] >> Required condition was not found: [Output match: ORPHAN: org/openj9/test/classtests/UnsafeBootClass]
[2024-05-10T00:39:15.283Z] >> Required condition was not found: [Output match: ORPHAN: org/openj9/test/classtests/AnonClassAndUnsafeClassTest]
[2024-05-10T00:39:15.283Z] >> Required condition was not found: [Output match: ROMCLASS: org/openj9/test/ivj/]

[2024-05-10T00:39:15.283Z] Testing: Test 70-d: Do not specify -Xshareclasses. Make sure orpahn classes from CustomClassLoader are re-used via compareROMClassForEquality when -XX:+ShareOrphans specified
[2024-05-10T00:39:15.283Z] Test start time: 2024/05/10 00:39:14 Coordinated Universal Time
[2024-05-10T00:39:15.283Z] Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -XX:-ShareOrphans -XX:+ShareOrphans -Xtrace:print={j9bcu.270} -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/utils/utils.jar org.openj9.test.classtests.ShareOrphanTest
[2024-05-10T00:39:15.283Z] Time spent starting: 1 milliseconds
[2024-05-10T00:39:15.283Z] Time spent executing: 316 milliseconds
[2024-05-10T00:39:15.283Z] Test result: FAILED
[2024-05-10T00:39:15.283Z] >> Required condition was not found: [Output match: compareROMClassForEquality returns 1 for class name 'org/openj9/test/classtests/UnsafeBootClass']
[2024-05-10T00:39:15.283Z] >> Required condition was not found: [Output match: compareROMClassForEquality returns 1 for class name 'org/openj9/test/classtests/AnonClassAndUnsafeClassTest']

[2024-05-10T00:39:16.470Z] Testing: Test 70-g: Make sure -XX:+ShareOrphans automatically turned on -Xshareclasses so that application classes are loaded from the shared cache
[2024-05-10T00:39:16.470Z] Test start time: 2024/05/10 00:39:15 Coordinated Universal Time
[2024-05-10T00:39:16.470Z] Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -XX:-ShareOrphans -XX:+ShareOrphans -Xtrace:print={j9jcl.273} -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/utils/utils.jar org.openj9.test.ivj.Hanoi 2
[2024-05-10T00:39:16.470Z] Time spent starting: 3 milliseconds
[2024-05-10T00:39:16.470Z] Time spent executing: 279 milliseconds
[2024-05-10T00:39:16.470Z] Test result: FAILED
[2024-05-10T00:39:16.470Z] >> Required condition was not found: [Output match: JCL: SharedClassURLClasspathHelperImpl findSharedClassImpl:]

[2024-05-10T00:39:16.470Z] com.oti.j9.exclude.XMLException: null(1730):C1 : Character data ended prematurely
[2024-05-10T00:39:16.470Z] 	at com.oti.j9.exclude.XMLParser.parseError(XMLParser.java:56)
[2024-05-10T00:39:16.470Z] 	at com.oti.j9.exclude.XMLParser._scan_cdata_or_eof(XMLParser.java:242)
[2024-05-10T00:39:16.470Z] 	at com.oti.j9.exclude.XMLParser.parseXML(XMLParser.java:444)
[2024-05-10T00:39:16.470Z] 	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:470)
[2024-05-10T00:39:16.470Z] 	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)
[2024-05-10T00:39:16.470Z] 	at TestConfigParser.runTests(TestConfigParser.java:78)
[2024-05-10T00:39:16.470Z] 	at MainTester.main(MainTester.java:106)
[2024-05-10T00:39:16.470Z] 
[2024-05-10T00:39:16.470Z] ---TEST RESULTS---
[2024-05-10T00:39:16.470Z] Number of PASSED tests: 103 out of 108
[2024-05-10T00:39:16.470Z] Number of FAILED tests: 5 out of 108
[2024-05-10T00:39:16.470Z] 
[2024-05-10T00:39:16.470Z] ---SUMMARY OF FAILED TESTS---
[2024-05-10T00:39:16.470Z] Test 69-b: Make sure CustomClassLoader (not using SCC Java API) stored classes in SCC as orphan
[2024-05-10T00:39:16.470Z] Test 69-c: Make sure orpahn classes from CustomClassLoader are re-used via compareROMClassForEquality when -XX:+ShareOrphans specified
[2024-05-10T00:39:16.470Z] Test 70-c: Make sure ShareOrphanTest classes are stored as orphans and Hanoi classes are stored as romclasses
[2024-05-10T00:39:16.470Z] Test 70-d: Do not specify -Xshareclasses. Make sure orpahn classes from CustomClassLoader are re-used via compareROMClassForEquality when -XX:+ShareOrphans specified
[2024-05-10T00:39:16.470Z] Test 70-g: Make sure -XX:+ShareOrphans automatically turned on -Xshareclasses so that application classes are loaded from the shared cache
[2024-05-10T00:39:16.470Z] -----------------------------
[2024-05-10T00:39:16.470Z] 
[2024-05-10T00:39:16.470Z] -----------------------------------
[2024-05-10T00:39:16.470Z] testSCCMLTests1_openj9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40516/) - all failed

**Comment by pshipton** [comment]
@hangshao0 pls take a look.

**Comment by pshipton** [comment]
The open tests are passing.
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Nightly/674/

**Comment by hangshao0** [comment]
From the failed link: https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/510/consoleFull

```
19:29:04  Run /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_2/jdkbinary/j2sdk-image/bin/java -version
19:29:04  =JAVA VERSION OUTPUT BEGIN=
19:29:05  java version "11.0.24-beta" 2024-07-16
19:29:05  IBM Semeru Runtime Certified Edition 11.0.24+2-202405092210 (build 11.0.24-beta+2)
19:29:05  Eclipse OpenJ9 VM 11.0.24+2-202405092210 (build master-7487893149, JRE 11 Linux aarch64-64-Bit Compressed References 20240509_588 (JIT enabled, AOT enabled)
19:29:05  OpenJ9   - 7487893149
19:29:05  OMR      - 1bcf96982
19:29:05  JCL      - 765bbe3498 based on jdk-11.0.24+2)
```

Is the above java -version correct ? 

The OpenJ9 sha is this[ commit](https://github.ibm.com/runtimes/openj9/commit/74878931493e81abd35da8b3240c30ecf5a6b3ed). My [change](https://github.ibm.com/runtimes/openj9/commit/d9a1f142cc06b05de6d5c295dea3502dc3e72ed8) is merged after this that. 

Also my changed added 2 new trace points. But running the above build with these 2 trace points gives me error:

```
java -Xtrace:print={j9bcu.275-276} -version
JVMTRCE003E Error processing trace option, detail: Unable to set tracepoint 275 in j9bcu - tracepoint id out of range
JVMTRCE011W Module not configured for trace: j9bcu
java version "11.0.24-beta" 2024-07-16
IBM Semeru Runtime Certified Edition 11.0.24+2-202405092210 (build 11.0.24-beta+2)
Eclipse OpenJ9 VM 11.0.24+2-202405092210 (build master-7487893149, JRE 11 Linux aarch64-64-Bit Compressed References 20240509_588 (JIT enabled, AOT enabled)
OpenJ9   - 7487893149
OMR      - 1bcf96982
JCL      - 765bbe3498 based on jdk-11.0.24+2)
```
Looks like the JDK being tested does not have my change.

**Comment by pshipton** [comment]
We'll just close this then. The internal testing doesn't make sure the JVM aligns with the tests.
