### ISSUE TITLE
OpenJDK javax/imageio/plugins/jpeg/JPEGsNotAcceleratedTest The application does not have desktop access

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19527]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_windows_testList_0/48)
jdk_imageio
javax/imageio/plugins/jpeg/JPEGsNotAcceleratedTest.java
```
java.awt.HeadlessException: 
The application does not have desktop access,
but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:164)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at JPEGsNotAcceleratedTest.main(JPEGsNotAcceleratedTest.java:307)
```

**Comment by pshipton** [comment]
Excluding via https://github.com/adoptium/aqa-tests/pull/5344
