### ISSUE TITLE
testJITServer_1_FAILED testServerGoesDown AssertionError: Failed to properly start server, it terminated prematurely with exit value: 1

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19526]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_fips140_2_testList_0/39/)(`rhel8x86-rtp-rtfips3-1`):
```
java version "17.0.11" 2024-04-16
IBM Semeru Runtime Certified Edition 17.0.11.0-rc3 (build 17.0.11+9)
Eclipse OpenJ9 VM 17.0.11.0-rc3 (build v0.44.0-release-b0699311c7, JRE 17 Linux amd64-64-Bit Compressed References 20240416_680 (JIT enabled, AOT enabled)
OpenJ9   - b0699311c7
OMR      - 254af5a04
JCL      - b522ac89460 based on jdk-17.0.11+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=testJITServer_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=FIPS140_2&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.functional_x86-64_linux_fips140_2&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=jck&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fhyc-runtimes-jenkins.swg-devops.com%2Fjob%2Fbuild-scripts%2Fjob%2Fopenjdk17-pipeline-IBM%2F742%2Fartifact%2Ftarget%2Flinux%2Fx64%2Fopenj9%2F*.tar.gz%2F*zip*%2Fopenj9.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Fjck.git&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=main&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=main&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=40&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=f3b78d91-4db0-4a87-b4d8-32164430cfdc&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;separator-87e3a7db-4843-4907-ad26-40f469fe3204=&amp;TIME_LIMIT=72&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-05-18T15:27:13.840Z] variation: Mode610 -Xshareclasses:none -Xjit:optLevel=hot
[2024-05-18T15:27:13.840Z] JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:none -Xjit:optLevel=hot  -Dsemeru.fips=true

[2024-05-18T15:37:27.490Z] FAILED: testServerGoesDown
[2024-05-18T15:37:27.490Z] java.lang.AssertionError: Failed to properly start server, it terminated prematurely with exit value: 1
[2024-05-18T15:37:27.490Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2024-05-18T15:37:27.490Z] 	at jit.test.jitserver.JITServerTest.startProcess(JITServerTest.java:382)
[2024-05-18T15:37:27.490Z] 	at jit.test.jitserver.JITServerTest.testServerGoesDown(JITServerTest.java:444)
[2024-05-18T15:37:27.490Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-18T15:37:27.490Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-05-18T15:37:27.490Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-18T15:37:27.490Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
[2024-05-18T15:37:27.490Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2024-05-18T15:37:27.490Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2024-05-18T15:37:27.490Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2024-05-18T15:37:27.490Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2024-05-18T15:37:27.490Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2024-05-18T15:37:27.490Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2024-05-18T15:37:27.490Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2024-05-18T15:37:27.490Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2024-05-18T15:37:27.490Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2024-05-18T15:37:27.490Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2024-05-18T15:37:27.490Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2024-05-18T15:37:27.490Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2024-05-18T15:37:27.490Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2024-05-18T15:37:27.490Z] 
[2024-05-18T15:37:27.490Z] 
[2024-05-18T15:37:27.490Z] ===============================================
[2024-05-18T15:37:27.490Z]     JITServerTest
[2024-05-18T15:37:27.490Z]     Tests run: 7, Failures: 1, Skips: 0
[2024-05-18T15:37:27.490Z] ===============================================
[2024-05-18T15:37:27.490Z] 
[2024-05-18T15:37:27.490Z] 
[2024-05-18T15:37:27.490Z] ===============================================
[2024-05-18T15:37:27.490Z] JIT_Test suite
[2024-05-18T15:37:27.490Z] Total tests run: 7, Failures: 1, Skips: 0
[2024-05-18T15:37:27.490Z] ===============================================
[2024-05-18T15:37:27.490Z] 
[2024-05-18T15:37:27.490Z] -----------------------------------
[2024-05-18T15:37:27.490Z] testJITServer_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40715/)

**Comment by cjjdespres** [comment]
From the log:

```
        [JITServerTest] [INFO] running testServerGoesDown: INFO and above level logging enabled
        [JITServerTest] [INFO] Chose random port for server: -XX:JITServerPort=48853, set JITServerTest_SERVER_PORT in your env to override.
        [JITServerTest] [INFO] Starting server with command line:
        /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_fips140_2_testList_0/jdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=48853 -XX:-JITServerHealthProbes
        [JITServerTest] [INFO] With stdout/stderr redirected to:
        /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_fips140_2_testList_0/aqa-tests/TKG/output_17160393718515/testJITServer_1/testServerGoesDown.server.out
        Failed to properly start server, it terminated prematurely with exit value: 1
        Dumping the contents of log file: /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_fips140_2_testList_0/aqa-tests/TKG/output_17160393718515/testJITServer_1/testServerGoesDown.server.out
        ////////////////////////////////////////////////////////////////////////
        //// can't bind server address: Address already in use
        //// Failed to open server socket on port 48853
        ////////////////////////////////////////////////////////////////////////
```

So this looks like a duplicate of https://github.com/eclipse-openj9/openj9/issues/14706

**Comment by JasonFengJ9** [comment]
Closing as dup of 
* https://github.com/eclipse-openj9/openj9/issues/14706
