### ISSUE TITLE
OpenJDK sun/security/mscapi/NonAsciiAlias jdk.crypto.mscapi KeyStoreException: error 5, Access is denied.

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19528]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_windows_testList_1/48)
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_windows_testList_1/48)
jdk_security3
sun/security/mscapi/NonAsciiAlias.java
```
java.security.KeyStoreException: error 5, Access is denied.

	at jdk.crypto.mscapi/sun.security.mscapi.CKeyStore.storePrivateKey(Native Method)
	at jdk.crypto.mscapi/sun.security.mscapi.CKeyStore$KeyEntry.setRSAPrivateKey(CKeyStore.java:153)
	at jdk.crypto.mscapi/sun.security.mscapi.CKeyStore.engineSetKeyEntry(CKeyStore.java:431)
	at jdk.crypto.mscapi/sun.security.mscapi.CKeyStore$MY.engineSetKeyEntry(CKeyStore.java:60)
	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1192)
	at NonAsciiAlias.main(NonAsciiAlias.java:49)
```

**Comment by pshipton** [comment]
Excluding via https://github.com/adoptium/aqa-tests/pull/5344
