### ISSUE TITLE
SharedClasses.SCM01.SingleCL UnsupportedClassVersionError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19582]
Also SharedClasses.SCM23.SingleCL, SharedClasses.SCM01.MultiCL, SharedClasses.SCM23.MultiCL, SharedClasses.SCM01.MultiThreadMultiCL.

https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK22-with-System/79/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK17/761/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/818/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK8/841/

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_aarch64_linux_Nightly_testList_1/684/

61.0 is jdk17.
```
[2024-05-30T02:04:59.620Z] SCL3 stderr Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 61.0 of class=net/openj9/sc/classes/Test_Init, the maximum supported major version is 52.0; offset=6
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.lang.ClassLoader.defineClassImpl(Native Method)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:399)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.lang.ClassLoader.defineClass(ClassLoader.java:360)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.security.AccessController.doPrivileged(AccessController.java:782)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:959)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.lang.ClassLoader.loadClass(ClassLoader.java:904)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at java.lang.ClassLoader.loadClass(ClassLoader.java:887)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at net.openj9.test.sc.LoaderSlave.run(LoaderSlave.java:77)
[2024-05-30T02:04:59.620Z] SCL3 stderr 	at net.openj9.test.sc.LoaderSlave.main(LoaderSlave.java:52)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.system_aarch64_linux_Nightly_testList_0/78

67.0 is jdk23
```
```

Changes from the previous working build
https://github.com/eclipse-openj9/openj9/compare/7c623220d1...b9fd76df770
https://github.com/adoptium/aqa-tests/compare/42609ec5c70...a4ef8f2aff2860
https://github.com/adoptium/TKG/compare/3ed8f8b66bc...b9e1d278d2e
https://github.com/adoptium/STF/compare/f8d647e99075...f40f3ca179d2

**Comment by llxia** [comment]
- SharedClasses.SCM01.SingleCL passed on [cent8-aarch64-1](https://openj9-jenkins.osuosl.org/computer/cent8-aarch64-1): https://openj9-jenkins.osuosl.org/job/Grinder/3638/consoleFull
- SharedClasses.SCM01.SingleCL failed on [ub20-aarch64-osu-1](https://openj9-jenkins.osuosl.org/computer/ub20-aarch64-osu-1): https://openj9-jenkins.osuosl.org/job/Grinder/3639/consoleFull

getDependencies section looks the same.
```
00:00:30.452  downloading https://openj9-jenkins.osuosl.org//job/systemtest.getDependency/lastSuccessfulBuild/artifact/systemtest_prereqs/log4j/log4j-core.jar
00:00:30.709  --> file downloaded to /home/jenkins/workspace/Grinder/../../testDependency/system_lib/log4j/log4j-core.jar
00:00:30.709  Checksum verification skipped for /home/jenkins/workspace/Grinder/../../testDependency/system_lib/log4j/log4j-core.jar
...
00:01:03.887  downloading https://openj9-jenkins.osuosl.org//job/systemtest.getDependency/lastSuccessfulBuild/artifact/systemtest_prereqs/log4j/log4j-api.jar
00:01:04.359  --> file downloaded to /home/jenkins/workspace/Grinder/../../testDependency/system_lib/log4j/log4j-api.jar
00:01:04.359  Checksum verification skipped for /home/jenkins/workspace/Grinder/../../testDependency/system_lib/log4j/log4j-api.jar
...
00:00:33.510  downloading https://openj9-jenkins.osuosl.org//job/systemtest.getDependency/lastSuccessfulBuild/artifact/systemtest_prereqs/junit/junit.jar
00:00:33.510  --> file downloaded to /home/jenkins/workspace/Grinder/../../testDependency/system_lib/junit/junit.jar
00:00:33.510  Checksum verification skipped for /home/jenkins/workspace/Grinder/../../testDependency/system_lib/junit/junit.jar
```

```
00:04:09.878  GEN   /home/jenkins/testDependency/system_lib/log4j/log4j-api.jar
00:04:09.878  GEN   /home/jenkins/testDependency/system_lib/log4j/log4j-core.jar
00:04:09.878  GEN   /home/jenkins/testDependency/system_lib/junit/junit.jar
...
```

**Comment by llxia** [comment]
Tested with ADOPTOPENJDK_BRANCH: 42609ec5c70, STF: f8d647e99075 and TKG: 3ed8f8b66bc
https://openj9-jenkins.osuosl.org/job/Grinder/3642/ passed on[ub20-aarch64-osu-1](https://openj9-jenkins.osuosl.org/computer/ub20-aarch64-osu-1): https://openj9-jenkins.osuosl.org/job/Grinder/3642/

**Comment by llxia** [comment]
Fix: we need to redirect SharedClasses tests to generate related classes under workspace dir, not `system_lib`.
https://github.com/eclipse-aqavit/openj9-systemtest/blob/0cc1cdb8e33b41de4478f8f07d53a461905e5f49/openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java#L193

@annaibm please take care of this. We need to ensure that `getPrereqRoots()` is not used anywhere other than getting 3rd party jars. Thanks

**Comment by pshipton** [comment]
Any update on this? It seems to still be occurring.
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.system_ppc64le_linux_testList_1/241

**Comment by llxia** [comment]
In [build 142](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.system_ppc64le_linux_testList_1/241), it looks like the jar got removed between the check and copy. And from the job history, only 1 out of 10 failed. Build 241 is the only failure. 

@annaibm Please try to see if you can reproduce this.
