### ISSUE TITLE
jdk_util_0_FAILED java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java PAR_STREAM_SPLITERATOR_FOREACH: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19589]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_0/553/)(`rtj-ubu24le-rtp-test-uz130-1`):
```
java version "17.0.12-beta" 2024-07-16
IBM Semeru Runtime Certified Edition 17.0.12+4-202405292330 (build 17.0.12-beta+4-202405292330)
Eclipse OpenJ9 VM 17.0.12+4-202405292330 (build master-b9fd76df77, JRE 17 Linux ppc64le-64-Bit Compressed References 20240529_683 (JIT enabled, AOT enabled)
OpenJ9   - b9fd76df77
OMR      - 5c74758cf
JCL      - a734653882 based on jdk-17.0.12+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_util_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F683%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK17U_2024-05-29-23-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F683%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK17U_2024-05-29-23-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=654&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-05-30T01:06:56.298Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2024-05-30T01:06:56.298Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2024-05-30T01:12:46.835Z] TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java

[2024-05-30T01:12:46.837Z] config java.util.stream.LoggingTestCase.before(): success
[2024-05-30T01:12:46.837Z] test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("SpinedBuffer:0..1000", java.util.stream.TestData$AbstractTestData$RefTestData@b81cd631): failure
[2024-05-30T01:12:46.837Z] java.lang.AssertionError: 2 failure(s) for test data: RefTestData[SpinedBuffer:0..1000]
[2024-05-30T01:12:46.837Z] 1: java.lang.Error: PAR_STREAM_SPLITERATOR_FOREACH: java.lang.StackOverflowError
[2024-05-30T01:12:46.837Z] java.lang.StackOverflowError
[2024-05-30T01:12:46.837Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-05-30T01:12:46.837Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

[2024-05-30T01:12:46.838Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.stream.Nodes$SizedCollectorTask.compute(Nodes.java:1878)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2024-05-30T01:12:46.838Z] --
[2024-05-30T01:12:46.838Z] 	at org.testng.Assert.fail(Assert.java:99)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:444)
[2024-05-30T01:12:46.838Z] 	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
[2024-05-30T01:12:46.838Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-30T01:12:46.838Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-05-30T01:12:46.838Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-30T01:12:46.838Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2024-05-30T01:12:46.838Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2024-05-30T01:12:46.838Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2024-05-30T01:12:46.838Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2024-05-30T01:12:46.838Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2024-05-30T01:12:46.838Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2024-05-30T01:12:46.838Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2024-05-30T01:12:46.838Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2024-05-30T01:12:46.838Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2024-05-30T01:12:46.838Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2024-05-30T01:12:46.838Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2024-05-30T01:12:46.838Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2024-05-30T01:12:46.838Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2024-05-30T01:12:46.838Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2024-05-30T01:12:46.838Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2024-05-30T01:12:46.838Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
[2024-05-30T01:12:46.838Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
[2024-05-30T01:12:46.838Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-05-30T01:12:46.838Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-05-30T01:12:46.838Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-05-30T01:12:46.838Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
[2024-05-30T01:12:46.838Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-05-30T01:12:46.838Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2024-05-30T01:12:46.838Z] config java.util.stream.LoggingTestCase.after(org.testng.internal.TestResult@deac44b5): success

[2024-05-30T01:12:46.840Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2024-05-30T01:12:46.840Z] --------------------------------------------------
[2024-05-30T01:17:35.734Z] Test results: passed: 903; failed: 1
[2024-05-30T01:17:46.819Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_17170299314963/jdk_util_0/report/html/report.html
[2024-05-30T01:17:46.819Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_17170299314963/jdk_util_0/work
[2024-05-30T01:17:46.819Z] Error: Some tests failed or other problems occurred.
[2024-05-30T01:17:46.819Z] -----------------------------------
[2024-05-30T01:17:46.819Z] jdk_util_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41011/)

There was a similar failure at a different platform
* https://github.com/eclipse-openj9/openj9/issues/13652

**Comment by pshipton** [comment]
The same or similar failure occurred, but the subset isn't recorded due to Output overflow.

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/451
jdk_util_1
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
`at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_OMR_testList_1/181
jdk_util_0
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
```
06:01:17  test org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams("HashSet:0..1000", RefTestData[HashSet:0..1000]): failure
06:01:17  java.lang.AssertionError: 9 failure(s) for test data: RefTestData[HashSet:0..1000]
06:01:17  1: java.lang.Error: PAR_STREAM_TO_STREAM_COLLECT_TO_LIST: java.lang.StackOverflowError
06:01:17  java.lang.StackOverflowError
06:01:17  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
06:01:17  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
06:01:17  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
06:01:17  	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
06:01:17  	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
06:01:17  	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
06:01:17  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
06:01:17  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:238)
06:01:17  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
06:01:17  	at java.base/java.util.stream.StreamTestScenario$17.run(StreamTestScenario.java:208)
06:01:17  	at java.base/java.util.stream.StreamTestScenario.run(StreamTestScenario.java:272)
06:01:17  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:404)
06:01:17  	at org.openjdk.tests.java.util.stream.StreamLinkTest.testManyStreams(StreamLinkTest.java:56)
06:01:17  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
06:01:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
06:01:17  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
06:01:17  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
06:01:17  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
06:01:17  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
06:01:17  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
06:01:17  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
06:01:17  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
06:01:17  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
06:01:17  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
06:01:17  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
06:01:17  	at org.testng.TestRunner.run(TestRunner.java:585)
06:01:17  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
06:01:17  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
06:01:17  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
06:01:17  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
06:01:17  	at
06:01:17  
06:01:17  ...
06:01:17  Output overflow:
```
