### ISSUE TITLE
OpenJDK java/util/Arrays/ArrayObjectMethods not equal

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19591]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_0/119 - [ub20-390-4](https://openj9-jenkins.osuosl.org/computer/ub20-390-4)
jdk_util_1
java/util/Arrays/ArrayObjectMethods.java
```
09:05:07  STDERR:
09:05:07  233952633 not equal to -1333340807
09:05:07  java.lang.Exception: Stack trace
09:05:07  	at java.base/java.lang.Thread.dumpStack(Thread.java:2233)
09:05:07  	at ArrayObjectMethods.fail(ArrayObjectMethods.java:178)
09:05:07  	at ArrayObjectMethods.fail(ArrayObjectMethods.java:179)
09:05:07  	at ArrayObjectMethods.equal(ArrayObjectMethods.java:184)
09:05:07  	at ArrayObjectMethods.test(ArrayObjectMethods.java:109)
09:05:07  	at ArrayObjectMethods.instanceMain(ArrayObjectMethods.java:188)
09:05:07  	at ArrayObjectMethods.main(ArrayObjectMethods.java:186)
```

**Comment by pshipton** [comment]
Perhaps related to https://github.com/eclipse-openj9/openj9/issues/19590

**Comment by pshipton** [comment]
Closing as a dup.
