### ISSUE TITLE
OpenJDK java/util/Arrays/HashCode short[] 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19590]
java/util/Arrays/HashCode.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/235/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/235/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/82/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/82/
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/23/
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/23/

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_0/119 - [ub20-390-4](https://openj9-jenkins.osuosl.org/computer/ub20-390-4)
```
09:05:39  STDOUT:
09:05:39  byte[] tests passed
09:05:39  short[] "[67, 39, -61, -87, 116, 97, 105, 116, 32, 108, 101, 32, 109, 101, 105, 108, 108, 101, 117, 114, 32, 100, 101, 115, 32, 116, 101, 109, 112, 115, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 101, 32, 112, 105, 114, 101, 32, 100, 101, 115, 32, 116, 101, 109, 112, 115, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -94, 103, 101, 32, 100, 101, 32, 108, 97, 32, 115, 97, 103, 101, 115, 115, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -94, 103, 101, 32, 100, 101, 32, 108, 97, 32, 102, 111, 108, 105, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -87, 112, 111, 113, 117, 101, 32, 100, 101, 32, 108, 97, 32, 99, 114, 111, 121, 97, 110, 99, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -87, 112, 111, 113, 117, 101, 32, 100, 101, 32, 108, 39, 105, 110, 99, 114, -61, -87, 100, 117, 108, 105, 116, -61, -87, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 97, 32, 115, 97, 105, 115, 111, 110, 32, 100, 101, 32, 108, 97, 32, 76, 117, 109, 105, -61, -88, 114, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 67, 39, -61, -87, 116, 97, 105, 116, 32, 108, 97, 32, 115, 97, 105, 115, 111, 110, 32, 100, 101, 115, 32, 84, -61, -87, 110, -61, -88, 98, 114, 101, 115, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 101, 32, 112, 114, 105, 110, 116, 101, 109, 112, 115, 32, 100, 101, 32, 108, 39, 101, 115, 112, 111, 105, 114, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, 104, 105, 118, 101, 114, 32, 100, 117, 32, 100, -61, -87, 115, 101, 115, 112, 111, 105, 114, 44, 32, 110, 111, 117, 115, 32, 97, 118, 105, 111, 110, 115, 32, 116, 111, 117, 116, 32, 100, 101, 118, 97, 110, 116, 32, 110, 111, 117, 115, 44, 32, 110, 111, 117, 115, 32, 110, 39, 97, 118, 105, 111, 110, 115, 32, 114, 105, 101, 110, 32, 100, 101, 118, 97, 110, 116, 32, 110, 111, 117, 115, 44, 32, 110, 111, 117, 115, 32, 97, 108, 108, 105, 111, 110, 115, 32, 116, 111, 117, 115, 32, 100, 105, 114, 101, 99, 116, 101, 109, 101, 110, 116, 32, 97, 117, 32, 67, 105, 101, 108, 44, 32, 110, 111, 117, 115, 32, 97, 108, 108, 105, 111, 110, 115, 32, 116, 111, 117, 115, 32, 100, 105, 114, 101, 99, 116, 101, 109, 101, 110, 116, 32, 100, 97, 110, 115, 32, 108, 39, 97, 117, 116, 114, 101, 32, 115, 101, 110, 115, 32, 98, 114, 101, 102, 44, 32, 108, 97, 32, 112, -61, -87, 114, 105, 111, 100, 101, 32, 114, 101, 115, 115, 101, 109, 98, 108, 97, 105, 116, 32, 116, 101, 108, 108, 101, 109, 101, 110, 116, 32, -61, -96, 32, 108, 97, 32, 112, -61, -87, 114, 105, 111, 100, 101, 32, 97, 99, 116, 117, 101, 108, 108, 101, 44, 32, 113, 117, 101, 32, 99, 101, 114, 116, 97, 105, 110, 101, 115, 32, 100, 101, 32, 115, 101, 115, 32, 97, 117, 116, 111, 114, 105, 116, -61, -87, 115, 32, 108, 101, 115, 32, 112, 108, 117, 115, 32, 98, 114, 117, 121, 97, 110, 116, 101, 115, 32, 111, 110, 116, 32, 105, 110, 115, 105, 115, 116, -61, -87, 32, 112, 111, 117, 114, 32, 113, 117, 39, 101, 108, 108, 101, 32, 115, 111, 105, 116, 32, 114, 101, -61, -89, 117, 101, 44, 32, 112, 111, 117, 114, 32, 108, 101, 32, 98, 105, 101, 110, 32, 111, 117, 32, 112, 111, 117, 114, 32, 108, 101, 32, 109, 97, 108, 44, 32, 97, 117, 32, 100, 101, 103, 114, -61, -87, 32, 115, 117, 112, 101, 114, 108, 97, 116, 105, 102, 32, 100, 101, 32, 108, 97, 32, 99, 111, 109, 112, 97, 114, 97, 105, 115, 111, 110, 32, 115, 101, 117, 108, 101, 109, 101, 110, 116, 46, 32, 45, 45, 32, 67, 104, 97, 114, 108, 101, 115, 32, 68, 105, 99, 107, 101, 110, 115, 44, 32, 84, 97, 108, 101, 32, 111, 102, 32, 84, 119, 111, 32, 67, 105, 116, 105, 101, 115, 32, 40, 105, 110, 32, 70, 114, 101, 110, 99, 104, 41]":  e = -1357593156, hashCode = 584369596, repetition = 0
09:05:39  int[] tests passed
09:05:39  char[] tests passed
09:05:39  STDERR:
09:05:39  java.lang.RuntimeException: Some tests failed
09:05:39  	at HashCode.main(HashCode.java:170)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_OMR_testList_1/119/ - [ub20-390-1](https://openj9-jenkins.osuosl.org/computer/ub20-390-1)
```
08:59:37  byte[] tests passed
08:59:37  short[] "[67, 39, -61, -87, 116, 97, 105, 116, 32, 108, 101, 32, 109, 101, 105, 108, 108, 101, 117, 114, 32, 100, 101, 115, 32, 116, 101, 109, 112, 115, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 101, 32, 112, 105, 114, 101, 32, 100, 101, 115, 32, 116, 101, 109, 112, 115, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -94, 103, 101, 32, 100, 101, 32, 108, 97, 32, 115, 97, 103, 101, 115, 115, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -94, 103, 101, 32, 100, 101, 32, 108, 97, 32, 102, 111, 108, 105, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -87, 112, 111, 113, 117, 101, 32, 100, 101, 32, 108, 97, 32, 99, 114, 111, 121, 97, 110, 99, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, -61, -87, 112, 111, 113, 117, 101, 32, 100, 101, 32, 108, 39, 105, 110, 99, 114, -61, -87, 100, 117, 108, 105, 116, -61, -87, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 97, 32, 115, 97, 105, 115, 111, 110, 32, 100, 101, 32, 108, 97, 32, 76, 117, 109, 105, -61, -88, 114, 101, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 67, 39, -61, -87, 116, 97, 105, 116, 32, 108, 97, 32, 115, 97, 105, 115, 111, 110, 32, 100, 101, 115, 32, 84, -61, -87, 110, -61, -88, 98, 114, 101, 115, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 101, 32, 112, 114, 105, 110, 116, 101, 109, 112, 115, 32, 100, 101, 32, 108, 39, 101, 115, 112, 111, 105, 114, 44, 32, 99, 39, -61, -87, 116, 97, 105, 116, 32, 108, 39, 104, 105, 118, 101, 114, 32, 100, 117, 32, 100, -61, -87, 115, 101, 115, 112, 111, 105, 114, 44, 32, 110, 111, 117, 115, 32, 97, 118, 105, 111, 110, 115, 32, 116, 111, 117, 116, 32, 100, 101, 118, 97, 110, 116, 32, 110, 111, 117, 115, 44, 32, 110, 111, 117, 115, 32, 110, 39, 97, 118, 105, 111, 110, 115, 32, 114, 105, 101, 110, 32, 100, 101, 118, 97, 110, 116, 32, 110, 111, 117, 115, 44, 32, 110, 111, 117, 115, 32, 97, 108, 108, 105, 111, 110, 115, 32, 116, 111, 117, 115, 32, 100, 105, 114, 101, 99, 116, 101, 109, 101, 110, 116, 32, 97, 117, 32, 67, 105, 101, 108, 44, 32, 110, 111, 117, 115, 32, 97, 108, 108, 105, 111, 110, 115, 32, 116, 111, 117, 115, 32, 100, 105, 114, 101, 99, 116, 101, 109, 101, 110, 116, 32, 100, 97, 110, 115, 32, 108, 39, 97, 117, 116, 114, 101, 32, 115, 101, 110, 115, 32, 98, 114, 101, 102, 44, 32, 108, 97, 32, 112, -61, -87, 114, 105, 111, 100, 101, 32, 114, 101, 115, 115, 101, 109, 98, 108, 97, 105, 116, 32, 116, 101, 108, 108, 101, 109, 101, 110, 116, 32, -61, -96, 32, 108, 97, 32, 112, -61, -87, 114, 105, 111, 100, 101, 32, 97, 99, 116, 117, 101, 108, 108, 101, 44, 32, 113, 117, 101, 32, 99, 101, 114, 116, 97, 105, 110, 101, 115, 32, 100, 101, 32, 115, 101, 115, 32, 97, 117, 116, 111, 114, 105, 116, -61, -87, 115, 32, 108, 101, 115, 32, 112, 108, 117, 115, 32, 98, 114, 117, 121, 97, 110, 116, 101, 115, 32, 111, 110, 116, 32, 105, 110, 115, 105, 115, 116, -61, -87, 32, 112, 111, 117, 114, 32, 113, 117, 39, 101, 108, 108, 101, 32, 115, 111, 105, 116, 32, 114, 101, -61, -89, 117, 101, 44, 32, 112, 111, 117, 114, 32, 108, 101, 32, 98, 105, 101, 110, 32, 111, 117, 32, 112, 111, 117, 114, 32, 108, 101, 32, 109, 97, 108, 44, 32, 97, 117, 32, 100, 101, 103, 114, -61, -87, 32, 115, 117, 112, 101, 114, 108, 97, 116, 105, 102, 32, 100, 101, 32, 108, 97, 32, 99, 111, 109, 112, 97, 114, 97, 105, 115, 111, 110, 32, 115, 101, 117, 108, 101, 109, 101, 110, 116, 46, 32, 45, 45, 32, 67, 104, 97, 114, 108, 101, 115, 32, 68, 105, 99, 107, 101, 110, 115, 44, 32, 84, 97, 108, 101, 32, 111, 102, 32, 84, 119, 111, 32, 67, 105, 116, 105, 101, 115, 32, 40, 105, 110, 32, 70, 114, 101, 110, 99, 104, 41]":  e = -1357593156, hashCode = 584369596, repetition = 0
08:59:37  int[] tests passed
08:59:37  char[] tests passed
08:59:37  STDERR:
08:59:37  java.lang.RuntimeException: Some tests failed
08:59:37  	at HashCode.main(HashCode.java:170)
```

Changes from last working build
https://github.com/eclipse-openj9/openj9/compare/b9fd76df...ff7726e0f2d
https://github.com/eclipse-openj9/openj9-omr/compare/5c74758cf6...6463b763550
https://github.com/ibmruntimes/openj9-openjdk-jdk21/compare/ae45e557a...a79fd69b866 but it also failed in jdk22, jdk23

**Comment by pshipton** [comment]
25x x 3 grinder on the failed test https://openj9-jenkins.osuosl.org/job/Grinder/3645/

**Comment by pshipton** [comment]
https://github.com/eclipse-openj9/openj9/issues/19591 may be a dup.

@Spencer-Comin @r30shah seems this is likely caused by https://github.com/eclipse-openj9/openj9/pull/19455

Unless you have a quick fix, I'm thinking we should back it out to avoid the failures in the builds.

**Comment by pshipton** [comment]
Closing https://github.com/eclipse-openj9/openj9/issues/19591 as a dup.

java/util/Arrays/ArrayObjectMethods.java
```
09:05:07  STDERR:
09:05:07  233952633 not equal to -1333340807
09:05:07  java.lang.Exception: Stack trace
09:05:07  	at java.base/java.lang.Thread.dumpStack(Thread.java:2233)
09:05:07  	at ArrayObjectMethods.fail(ArrayObjectMethods.java:178)
09:05:07  	at ArrayObjectMethods.fail(ArrayObjectMethods.java:179)
09:05:07  	at ArrayObjectMethods.equal(ArrayObjectMethods.java:184)
09:05:07  	at ArrayObjectMethods.test(ArrayObjectMethods.java:109)
09:05:07  	at ArrayObjectMethods.instanceMain(ArrayObjectMethods.java:188)
09:05:07  	at ArrayObjectMethods.main(ArrayObjectMethods.java:186)
```

**Comment by r30shah** [comment]
Given the error, I suspect we would have quick fix. Though @Spencer-Comin  let's take a quick look at the failure.
I agree with @pshipton for reverting the change if we cannot fix it quickly.
