### ISSUE TITLE
jdk_security3_0_FAILED sun/security/ssl/SSLEngineImpl/SSLEngineBadBufferArrayAccess.java Exception: Client: Data length error

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19682]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_s390x_linux_testList_2/58/)(`rhel9s390xrt-2`):
```
openjdk version "22.0.1-beta" 2024-04-16
IBM Semeru Runtime Open Edition 22.0.1+8-202406110016 (build 22.0.1-beta+8-202406110016)
Eclipse OpenJ9 VM 22.0.1+8-202406110016 (build master-bc7affe3fe, JRE 22 Linux s390x-64-Bit Compressed References 20240611_87 (JIT enabled, AOT enabled)
OpenJ9   - bc7affe3fe
OMR      - 361c9df88
JCL      - ae28e24bf based on jdk-22.0.1+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk22_j9_extended.openjdk_s390x_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-s390x-openj9%2F87%2Fibm-semeru-open-jdk_s390x_linux_JDK22U_2024-06-11-00-02.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-linux-s390x-openj9%2F87%2Fibm-semeru-open-testimage_s390x_linux_JDK22U_2024-06-11-00-02.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=22&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk22&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=60&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-06-11T01:52:53.395Z] variation: Mode150
[2024-06-11T01:52:53.395Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-06-11T03:01:41.020Z] TEST: sun/security/ssl/SSLEngineImpl/SSLEngineBadBufferArrayAccess.java

[2024-06-11T03:01:41.025Z] server wrap: OK/NOT_HANDSHAKING, 29/69 bytes
[2024-06-11T03:01:41.025Z] Server died ...
[2024-06-11T03:01:41.025Z] java.lang.Exception: Client: Data length error - IF THIS FAILS, PLEASE REPORT THIS TO THE SECURITY TEAM.  WE HAVE BEEN UNABLE TO RELIABLY DUPLICATE.
[2024-06-11T03:01:41.025Z] 	at SSLEngineBadBufferArrayAccess.runServerApplication(SSLEngineBadBufferArrayAccess.java:369)
[2024-06-11T03:01:41.025Z] 	at SSLEngineBadBufferArrayAccess.runTest(SSLEngineBadBufferArrayAccess.java:247)
[2024-06-11T03:01:41.025Z] 	at SSLEngineBadBufferArrayAccess.main(SSLEngineBadBufferArrayAccess.java:162)
[2024-06-11T03:01:41.025Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-06-11T03:01:41.025Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-06-11T03:01:41.025Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-06-11T03:01:41.025Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-06-11T03:01:41.025Z] Client read 29 bytes. Waiting for 29 from server.
[2024-06-11T03:01:41.025Z] Read everything we're going to, I guess.
[2024-06-11T03:01:41.025Z] STDERR:
[2024-06-11T03:01:41.025Z] java.lang.RuntimeException: Test failed
[2024-06-11T03:01:41.025Z] 	at SSLEngineBadBufferArrayAccess.runTest(SSLEngineBadBufferArrayAccess.java:270)
[2024-06-11T03:01:41.025Z] 	at SSLEngineBadBufferArrayAccess.main(SSLEngineBadBufferArrayAccess.java:162)
[2024-06-11T03:01:41.025Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-06-11T03:01:41.025Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-06-11T03:01:41.025Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-06-11T03:01:41.025Z] 	at java.base/java.lang.Thread.run(Thread.java:1582)
[2024-06-11T03:01:41.025Z] 
[2024-06-11T03:01:41.025Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed

[2024-06-11T04:02:18.181Z] jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41321/)

Occurred before at https://github.com/eclipse-openj9/openj9/issues/12696#issuecomment-1998577000

**Comment by pshipton** [comment]
Failed on
