### ISSUE TITLE
jdk_lang_VarHandleTest_j9_1_FAILED java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java AssertionError: No throwable thrown. Expected class java.nio.ReadOnlyBufferException expected object to not be null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19713]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_1/596/)(`paix907`):
```
java version "17.0.12-beta" 2024-07-16
IBM Semeru Runtime Certified Edition 17.0.12+5-202406132307 (build 17.0.12-beta+5-202406132307)
Eclipse OpenJ9 VM 17.0.12+5-202406132307 (build master-73b7a28e31, JRE 17 AIX ppc64-64-Bit Compressed References 20240613_683 (JIT enabled, AOT enabled)
OpenJ9   - 73b7a28e31
OMR      - 407c2ab2b
JCL      - a14c792864 based on jdk-17.0.12+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_lang_VarHandleTest_j9_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F683%2Fibm-semeru-certified-jdk_ppc64_aix_JDK17U_2024-06-13-23-02.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F683%2Fibm-semeru-certified-testimage_ppc64_aix_JDK17U_2024-06-13-23-02.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=690&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-06-14T02:02:21.261Z] variation: -Xjit:enableAggressiveLiveness -XX:-JITServerTechPreviewMessage -Xjit:scratchSpaceFactorWhenJSR292Workload=1 Mode650
[2024-06-14T02:02:21.261Z] JVM_OPTIONS:  -Xjit:enableAggressiveLiveness -XX:-JITServerTechPreviewMessage -Xjit:scratchSpaceFactorWhenJSR292Workload=1 -XX:-UseCompressedOops -Xverbosegclog 

[2024-06-14T02:04:36.729Z] TEST: java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java

[2024-06-14T02:04:36.732Z] test VarHandleTestByteArrayAsChar.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> java.nio.HeapByteBufferR[pos=0 lim=32 cap=32] [ALIGNED, BIG_ENDIAN, READ_ONLY] unsupported", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@2245f975): failure
[2024-06-14T02:04:36.732Z] java.lang.AssertionError: No throwable thrown. Expected class java.nio.ReadOnlyBufferException expected object to not be null
[2024-06-14T02:04:36.732Z] 	at org.testng.Assert.fail(Assert.java:99)
[2024-06-14T02:04:36.732Z] 	at org.testng.Assert.assertNotNull(Assert.java:942)
[2024-06-14T02:04:36.732Z] 	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:147)
[2024-06-14T02:04:36.732Z] 	at VarHandleBaseTest.checkROBE(VarHandleBaseTest.java:65)
[2024-06-14T02:04:36.732Z] 	at VarHandleTestByteArrayAsChar.testArrayUnsupported(VarHandleTestByteArrayAsChar.java:421)
[2024-06-14T02:04:36.732Z] 	at VarHandleTestByteArrayAsChar.lambda$accessTestCaseProvider$14(VarHandleTestByteArrayAsChar.java:205)
[2024-06-14T02:04:36.732Z] 	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
[2024-06-14T02:04:36.732Z] 	at VarHandleTestByteArrayAsChar.testAccess(VarHandleTestByteArrayAsChar.java:229)
[2024-06-14T02:04:36.732Z] 	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[2024-06-14T02:04:36.732Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-06-14T02:04:36.732Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2024-06-14T02:04:36.732Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2024-06-14T02:04:36.732Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2024-06-14T02:04:36.732Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2024-06-14T02:04:36.732Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2024-06-14T02:04:36.732Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2024-06-14T02:04:36.732Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2024-06-14T02:04:36.732Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2024-06-14T02:04:36.732Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2024-06-14T02:04:36.732Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2024-06-14T02:04:36.732Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2024-06-14T02:04:36.732Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2024-06-14T02:04:36.732Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2024-06-14T02:04:36.733Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2024-06-14T02:04:36.733Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2024-06-14T02:04:36.733Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
[2024-06-14T02:04:36.733Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
[2024-06-14T02:04:36.733Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-06-14T02:04:36.733Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-06-14T02:04:36.733Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-06-14T02:04:36.733Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2024-06-14T02:04:36.733Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-06-14T02:04:36.733Z] 	at java.base/java.lang.Thread.run(Thread.java:857)

[2024-06-14T02:05:02.726Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 12
[2024-06-14T02:05:02.726Z] --------------------------------------------------
[2024-06-14T02:07:23.104Z] Test results: passed: 32; failed: 6
[2024-06-14T02:07:23.104Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_17183283467821/jdk_lang_VarHandleTest_j9_1/report/html/report.html
[2024-06-14T02:07:23.104Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_1/aqa-tests/TKG/output_17183283467821/jdk_lang_VarHandleTest_j9_1/work
[2024-06-14T02:07:23.104Z] Error: Some tests failed or other problems occurred.
[2024-06-14T02:07:23.104Z] -----------------------------------
[2024-06-14T02:07:23.104Z] jdk_lang_VarHandleTest_j9_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41382/)

**Comment by pshipton** [comment]
Dup of https://github.com/eclipse-openj9/openj9/issues/19693
