### ISSUE TITLE
jdk_lang_1_FAILED java/lang/ProcessBuilder/PipelineLeaksFD.java AssertionError: More or fewer pipes than expected

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19728]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_0/564/)(`ubu22lert-2`):
```
java version "17.0.12-beta" 2024-07-16
IBM Semeru Runtime Certified Edition 17.0.12+5-202406172320 (build 17.0.12-beta+5-202406172320)
Eclipse OpenJ9 VM 17.0.12+5-202406172320 (build master-b679b57d60, JRE 17 Linux ppc64le-64-Bit Compressed References 20240617_695 (JIT enabled, AOT enabled)
OpenJ9   - b679b57d60
OMR      - 4c74f944f
JCL      - 287bf24b16 based on jdk-17.0.12+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_lang_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=3&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F695%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK17U_2024-06-17-23-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F695%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK17U_2024-06-17-23-01.tar.gz&BUILD_IDENTIFIER=&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=17&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&JCK_GIT_BRANCH=main&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=666&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-06-18T00:39:36.248Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2024-06-18T00:39:36.248Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Xverbosegclog 

[2024-06-18T00:47:44.293Z] TEST: java/lang/ProcessBuilder/PipelineLeaksFD.java

[2024-06-18T00:47:44.295Z] STDOUT:
[2024-06-18T00:47:44.295Z] test PipelineLeaksFD.checkForLeaks(java.util.ImmutableCollections$List12@a4761f24): success
[2024-06-18T00:47:44.295Z] test PipelineLeaksFD.checkForLeaks(java.util.ImmutableCollections$List12@c448fd74): success
[2024-06-18T00:47:44.295Z] Missing from pipesAfter: [0]
[2024-06-18T00:47:44.295Z] Extra pipes in pipesAfter: [1]
[2024-06-18T00:47:44.295Z] /proc/2865212/fd/22 : pipe:[1925053]
[2024-06-18T00:47:44.295Z] test PipelineLeaksFD.checkForLeaks(java.util.ImmutableCollections$ListN@b49d4289): failure
[2024-06-18T00:47:44.295Z] java.lang.AssertionError: More or fewer pipes than expected
[2024-06-18T00:47:44.295Z] 	at org.testng.Assert.fail(Assert.java:99)
[2024-06-18T00:47:44.295Z] 	at PipelineLeaksFD.checkForLeaks(PipelineLeaksFD.java:103)
[2024-06-18T00:47:44.295Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-06-18T00:47:44.295Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-06-18T00:47:44.295Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-06-18T00:47:44.295Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2024-06-18T00:47:44.295Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2024-06-18T00:47:44.295Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2024-06-18T00:47:44.295Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2024-06-18T00:47:44.295Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2024-06-18T00:47:44.295Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2024-06-18T00:47:44.296Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2024-06-18T00:47:44.296Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2024-06-18T00:47:44.296Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2024-06-18T00:47:44.296Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2024-06-18T00:47:44.296Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2024-06-18T00:47:44.296Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2024-06-18T00:47:44.296Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2024-06-18T00:47:44.296Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2024-06-18T00:47:44.296Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2024-06-18T00:47:44.296Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
[2024-06-18T00:47:44.296Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
[2024-06-18T00:47:44.296Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-06-18T00:47:44.296Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-06-18T00:47:44.296Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-06-18T00:47:44.296Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2024-06-18T00:47:44.296Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-06-18T00:47:44.296Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2024-06-18T00:47:44.296Z] 
[2024-06-18T00:47:44.296Z] ===============================================
[2024-06-18T00:47:44.296Z] java/lang/ProcessBuilder/PipelineLeaksFD.java
[2024-06-18T00:47:44.296Z] Total tests run: 3, Passes: 2, Failures: 1, Skips: 0
[2024-06-18T00:47:44.296Z] ===============================================

[2024-06-18T00:47:44.298Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2024-06-18T00:47:44.298Z] --------------------------------------------------
[2024-06-18T00:53:42.346Z] Test results: passed: 816; failed: 1
[2024-06-18T00:53:46.382Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_1718670333464/jdk_lang_1/report/html/report.html
[2024-06-18T00:53:46.382Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_testList_0/aqa-tests/TKG/output_1718670333464/jdk_lang_1/work
[2024-06-18T00:53:46.382Z] Error: Some tests failed or other problems occurred.
[2024-06-18T00:53:46.382Z] -----------------------------------
[2024-06-18T00:53:46.382Z] jdk_lang_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41440/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_0/133 - [ub20-390-4](https://openj9-jenkins.osuosl.org/computer/ub20-390-4)
jdk_lang_0
java/lang/ProcessBuilder/PipelineLeaksFD.java
```
05:58:08  Missing from pipesAfter: [0]
05:58:08  Extra pipes in pipesAfter: [1]
05:58:08  /proc/1089110/fd/25 : pipe:[37001382]
05:58:08  test PipelineLeaksFD.checkForLeaks(java.util.ImmutableCollections$List12@1d33a02f): failure
05:58:08  java.lang.AssertionError: More or fewer pipes than expected
05:58:08  	at org.testng.Assert.fail(Assert.java:99)
05:58:08  	at PipelineLeaksFD.checkForLeaks(PipelineLeaksFD.java:103)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_0/134/

**Comment by pshipton** [comment]
There are quite a few failures in the nightly builds since the test was unexcluded.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17_testList_0/26/

**Comment by pshipton** [comment]
3 x 25x grinder individual test on the build from the 17th or 18th didn't fail.
https://openj9-jenkins.osuosl.org/job/Build_JDK17_s390x_linux_Nightly/769/
https://openj9-jenkins.osuosl.org/job/Build_JDK17_s390x_linux_Nightly/770/

**Comment by pshipton** [comment]
Created https://github.com/adoptium/aqa-tests/pull/5419 to exclude the test on zlinux for jdk17. I ran OpenJ9 grinders on jdk21 - jdk23 and didn't get any failures.
