### ISSUE TITLE
OpenJDK java/lang/ProcessHandle/InfoTest reported cputime less than expected

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19757]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_OpenJDK23_testList_0/2
jdk_lang_j9_0
java/lang/ProcessHandle/InfoTest.java
```
09:27:42   info: [user: Optional[jenkins], cmdLine: /home/jenkins/workspace/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_OpenJDK23_te, startTime: Optional[2024-06-21T13:13:02Z], totalTime: Optional[PT0.115588531S]]
09:27:42  test InfoTest.test1(): failure
09:27:42  java.lang.AssertionError: reported cputime less than expected: PT0.2S, actual: Optional[PT0.115588531S]
09:27:42  	at org.testng.Assert.fail(Assert.java:99)
09:27:42  	at InfoTest.test1(InfoTest.java:110)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_OpenJDK23_testList_0/3/consoleFull
```
16:32:30  ===============================================
16:32:30  Running test jdk_lang_j9_0 ...
16:32:30  ===============================================
16:32:30  jdk_lang_j9_0 Start Time: Tue Jul 16 20:17:46 2024 Epoch Time (ms): 1721161066364
16:32:30  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
16:32:30  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -Xverbosegclog 

16:56:22  TEST: java/lang/ProcessHandle/InfoTest.java

16:56:22  STDOUT:
16:56:22  Note: when run in samevm mode the cputime of the test runner is included.
16:56:22   info: [user: Optional[jenkins], cmdLine: /home/jenkins/workspace/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_OpenJDK23_te, startTime: Optional[2024-07-16T20:41:13Z], totalTime: Optional[PT0.017475546S]]
16:56:22  test InfoTest.test1(): failure
16:56:22  java.lang.AssertionError: reported cputime less than expected: PT0.2S, actual: Optional[PT0.017475546S]
16:56:22  	at org.testng.Assert.fail(Assert.java:99)
16:56:22  	at InfoTest.test1(InfoTest.java:110)
16:56:22  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

17:29:40  jdk_lang_j9_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_OpenJDK23_testList_0/7
jdk_lang_0 
java/lang/ProcessHandle/InfoTest.java
```
08:50:28   info: [user: Optional[jenkins], cmdLine: /home/jenkins/workspace/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_OpenJDK23_te, startTime: Optional[2024-08-02T12:34:46Z], totalTime: Optional[PT0.030383531S]]
08:50:28  test InfoTest.test1(): failure
08:50:28  java.lang.AssertionError: reported cputime less than expected: PT0.2S, actual: Optional[PT0.030383531S]
08:50:28  	at org.testng.Assert.fail(Assert.java:99)
08:50:28  	at InfoTest.test1(InfoTest.java:110)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OpenJDK21_testList_0/25/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_OMR_testList_0/113

**Comment by pshipton** [comment]
Also in the jdk23 release build.
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_Release_testList_0/2/
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_Release_testList_1/2/

**Comment by pshipton** [comment]
Seems related to https://bugs.java.com/bugdatabase/view_bug?bug_id=8211847. It's supposed to be fixed in 21.0.5 and 23+, but doesn't appear to be.

**Comment by pshipton** [comment]
Exclude the test https://github.com/adoptium/aqa-tests/pull/5501

**Comment by JasonFengJ9** [comment]
[JDK23 Milestone 1 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk23_j9_sanity.openjdk_ppc64_aix_testList_1/5/)
```
[2024-08-14T13:42:25.626Z] TEST: java/lang/ProcessHandle/InfoTest.java

[2024-08-14T13:42:25.628Z] test InfoTest.test1(): failure
[2024-08-14T13:42:25.628Z] java.lang.AssertionError: reported cputime less than expected: PT0.2S, actual: Optional[PT0.010468375S]
[2024-08-14T13:42:25.628Z] 	at org.testng.Assert.fail(Assert.java:99)
[2024-08-14T13:42:25.628Z] 	at InfoTest.test1(InfoTest.java:110)

[2024-08-14T14:10:21.127Z] jdk_lang_1_FAILED
```
