### ISSUE TITLE
OpenJDK java/foreign/SafeFunctionAccessTest ClassNotFoundException: org.testng.thread.IExecutorFactory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19766]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/1
jdk_foreign_1
java/foreign/SafeFunctionAccessTest.java
```
02:43:06  STDERR:
02:43:06  java.lang.NoClassDefFoundError: org.testng.thread.IExecutorFactory
02:43:06  	at org.testng.TestNG.init(TestNG.java:220)
02:43:06  	at org.testng.TestNG.<init>(TestNG.java:213)
02:43:06  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:92)
02:43:06  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
02:43:06  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
02:43:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
02:43:06  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
02:43:06  	at java.base/java.lang.Thread.run(Thread.java:1587)
02:43:06  Caused by: java.lang.ClassNotFoundException: org.testng.thread.IExecutorFactory
02:43:06  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:827)
02:43:06  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
02:43:06  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1099)
02:43:06  	... 8 more
```

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_extended.openjdk_x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_extended.openjdk_x86-64_mac_testList_0/86/)
```
[2025-08-09T03:45:36.545Z] Running test jdk_nio_0 ...
[2025-08-09T03:45:36.545Z] ===============================================
[2025-08-09T03:45:36.545Z] jdk_nio_0 Start Time: Fri Aug  8 23:45:36 2025 Epoch Time (ms): 1754711136046
[2025-08-09T03:45:36.545Z] variation: Mode150
[2025-08-09T03:45:36.545Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-08-09T03:47:00.050Z] TEST: java/nio/channels/DatagramChannel/AfterDisconnect.java

[2025-08-09T03:47:00.056Z] ===============================================
[2025-08-09T03:47:00.056Z] java/nio/channels/DatagramChannel/AfterDisconnect.java
[2025-08-09T03:47:00.056Z] Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
[2025-08-09T03:47:00.056Z] ===============================================
[2025-08-09T03:47:00.056Z] 
[2025-08-09T03:47:00.056Z] STDERR:
[2025-08-09T03:47:00.056Z] STATUS:Passed.

[2025-08-09T03:47:00.065Z] STDERR:
[2025-08-09T03:47:00.065Z] java.lang.NoClassDefFoundError: org.testng.thread.IExecutorFactory
[2025-08-09T03:47:00.065Z] 	at org.testng.TestNG.init(TestNG.java:220)
[2025-08-09T03:47:00.065Z] 	at org.testng.TestNG.<init>(TestNG.java:213)
[2025-08-09T03:47:00.065Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:92)
[2025-08-09T03:47:00.065Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
[2025-08-09T03:47:00.065Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-08-09T03:47:00.065Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-08-09T03:47:00.065Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2025-08-09T03:47:00.065Z] 	at java.base/java.lang.Thread.run(Thread.java:1458)
[2025-08-09T03:47:00.065Z] Caused by: java.lang.ClassNotFoundException: org.testng.thread.IExecutorFactory
[2025-08-09T03:47:00.065Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:754)
[2025-08-09T03:47:00.065Z] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1042)
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/53750/) - passed
