### ISSUE TITLE
MBCS_Tests_charsets ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19839]
https://trssrtp1.fyre.ibm.com/output/test?id=668adfa66b34225c2bd9dbbd
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_special.functional_s390x_linux_testList_0/4/ - svlxtor3
MBCS_Tests_charsets_0
```
[2024-07-06T16:49:03.370Z] x-MacRomania
[2024-07-06T16:49:03.370Z] [\x00-\xFF]
[2024-07-06T16:49:03.370Z] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
[2024-07-06T16:49:03.370Z] 	at java.base/java.lang.StringLatin1.toUpperCase(StringLatin1.java:625)
[2024-07-06T16:49:03.370Z] 	at java.base/java.lang.String.toUpperCase(String.java:4543)
[2024-07-06T16:49:03.370Z] 	at java.base/java.util.Formatter$FormatSpecifier.toUpperCaseWithLocale(Formatter.java:3195)
[2024-07-06T16:49:03.370Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3415)
[2024-07-06T16:49:03.370Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3368)
[2024-07-06T16:49:03.370Z] 	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3066)
[2024-07-06T16:49:03.370Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3027)
[2024-07-06T16:49:03.370Z] 	at java.base/java.util.Formatter.format(Formatter.java:2797)
[2024-07-06T16:49:03.370Z] 	at java.base/java.util.Formatter.format(Formatter.java:2734)
[2024-07-06T16:49:03.370Z] 	at java.base/java.lang.String.format(String.java:5214)
[2024-07-06T16:49:03.370Z] 	at CharsetsTest.decode_data(CharsetsTest.java:192)
[2024-07-06T16:49:03.370Z] 	at CharsetsTest.charset_test(CharsetsTest.java:277)
[2024-07-06T16:49:03.370Z] 	at CharsetsTest.main(CharsetsTest.java:290)
```

Also failed in the rerun on sles15s390x-svl-rt3-1
https://trssrtp1.fyre.ibm.com/output/test?id=668adfae6b34225c2bd9dd41
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_special.functional_s390x_linux_rerun/7/
```
[2024-07-06T17:25:48.456Z] JIS_X0212-1990
[2024-07-06T17:25:48.456Z] [\x22-\x6D][\x21-\x7E]
[2024-07-06T17:25:48.456Z] Exception in thread "main" java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException
[2024-07-06T17:25:48.456Z] 	at CharsetsTest.encode_data(CharsetsTest.java:237)
[2024-07-06T17:25:48.456Z] 	at CharsetsTest.charset_test(CharsetsTest.java:280)
[2024-07-06T17:25:48.456Z] 	at CharsetsTest.main(CharsetsTest.java:290)
```
https://trssrtp1.fyre.ibm.com/output/test?id=668adfae6b34225c2bd9dd44
```
[2024-07-06T17:29:30.933Z] x-IBM922
[2024-07-06T17:29:30.933Z] [\x00-\xFF]
[2024-07-06T17:29:30.933Z] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
[2024-07-06T17:29:30.933Z] 	at java.base/java.lang.StringLatin1.toUpperCase(StringLatin1.java:625)
[2024-07-06T17:29:30.933Z] 	at java.base/java.lang.String.toUpperCase(String.java:4543)
[2024-07-06T17:29:30.933Z] 	at java.base/java.util.Formatter$FormatSpecifier.toUpperCaseWithLocale(Formatter.java:3195)
[2024-07-06T17:29:30.933Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3415)
[2024-07-06T17:29:30.933Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3368)
[2024-07-06T17:29:30.933Z] 	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3066)
[2024-07-06T17:29:30.933Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3027)
[2024-07-06T17:29:30.933Z] 	at java.base/java.util.Formatter.format(Formatter.java:2797)
[2024-07-06T17:29:30.933Z] 	at java.base/java.util.Formatter.format(Formatter.java:2734)
[2024-07-06T17:29:30.933Z] 	at java.base/java.lang.String.format(String.java:5214)
[2024-07-06T17:29:30.933Z] 	at CharsetsTest.decode_data(CharsetsTest.java:192)
[2024-07-06T17:29:30.933Z] 	at CharsetsTest.charset_test(CharsetsTest.java:277)
[2024-07-06T17:29:30.933Z] 	at CharsetsTest.main(CharsetsTest.java:290)
```

Last passing (but it's intermittent)
```
14:10:39  IBM Semeru Runtime Open Edition 22.0.1+8-202406291603 (build 22.0.1-beta+8-202406291603)
14:10:39  Eclipse OpenJ9 VM 22.0.1+8-202406291603 (build master-c05e25e984, JRE 22 Linux s390x-64-Bit Compressed References 20240629_2 (JIT enabled, AOT enabled)
14:10:39  OpenJ9   - c05e25e984
14:10:39  OMR      - 47a9d248d
14:10:39  JCL      - dd7696c12 based on jdk-22.0.1+8)
```
Failed in
```
12:44:35  IBM Semeru Runtime Open Edition 22.0.1+8-202407061603 (build 22.0.1-beta+8-202407061603)
12:44:35  Eclipse OpenJ9 VM 22.0.1+8-202407061603 (build master-d946965c3a, JRE 22 Linux s390x-64-Bit Compressed References 20240706_7 (JIT enabled, AOT enabled)
12:44:35  OpenJ9   - d946965c3a
12:44:35  OMR      - 38148eaaf
12:44:35  JCL      - dd7696c12 based on jdk-22.0.1+8)
```

5x x 5 grinder https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41989

**Comment by pshipton** [comment]
@hzongaro fyi

**Comment by hzongaro** [comment]
@Spencer-Comin, may I ask you to take a look at this?  We have had several very similar problems reported over the past few years that look very much like they could all be slightly different variations of one bug:

- #18669
- #18102
- #17995
- #17063
- #15171
- #14405
- #11799

I did some investigation under issue #18102, but wasn't able to resolve the problem.  I had promised an update in that issue that I never posted.  I'll pull together what I had, and add it there.

**Comment by hzongaro** [comment]
Note that although this failure occurred on zLinux, the various instances have occurred on a variety of platforms.

**Comment by JasonFengJ9** [comment]
[JDK23 Milestone 1 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk23_j9_special.functional_s390x_linux_testList_1/1/)(`sles12s390x-svl-rt5-1`)
```
openjdk version "23" 2024-09-17
IBM Semeru Runtime Open Edition 23.0.0.0-m1 (build 23+36)
Eclipse OpenJ9 VM 23.0.0.0-m1 (build v0.47.0-release-24752b0cab, JRE 23 Linux s390x-64-Bit Compressed References 20240917_11 (JIT enabled, AOT enabled)
OpenJ9   - 24752b0cab
OMR      - 5e425ebfc
JCL      - 7ddc19f4c87 based on jdk-23+36)

[2024-08-14T13:37:12.401Z] variation: NoOptions
[2024-08-14T13:37:12.401Z] JVM_OPTIONS:  

[2024-08-14T13:37:21.467Z] IBM500
[2024-08-14T13:37:21.467Z] [\x00-\xFF]
[2024-08-14T13:37:21.467Z] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
[2024-08-14T13:37:21.467Z] 	at java.base/java.lang.StringLatin1.toUpperCase(StringLatin1.java:617)
[2024-08-14T13:37:21.467Z] 	at java.base/java.lang.String.toUpperCase(String.java:4592)
[2024-08-14T13:37:21.467Z] 	at java.base/java.util.Formatter$FormatSpecifier.toUpperCaseWithLocale(Formatter.java:3371)
[2024-08-14T13:37:21.467Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3591)
[2024-08-14T13:37:21.467Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3544)
[2024-08-14T13:37:21.467Z] 	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3242)
[2024-08-14T13:37:21.467Z] 	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3203)
[2024-08-14T13:37:21.467Z] 	at java.base/java.util.Formatter.format(Formatter.java:2801)
[2024-08-14T13:37:21.467Z] 	at java.base/java.util.Formatter.format(Formatter.java:2738)
[2024-08-14T13:37:21.467Z] 	at java.base/java.lang.String.format(String.java:5263)
[2024-08-14T13:37:21.467Z] 	at CharsetsTest.decode_data(CharsetsTest.java:192)
[2024-08-14T13:37:21.468Z] 	at CharsetsTest.charset_test(CharsetsTest.java:277)
[2024-08-14T13:37:21.468Z] 	at CharsetsTest.main(CharsetsTest.java:290)
[2024-08-14T13:37:21.468Z] -----------------------------------
[2024-08-14T13:37:21.468Z] MBCS_Tests_charsets_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42744/)

**Comment by hzongaro** [comment]
Moving this to the "Future" release for now
