### ISSUE TITLE
jdk_lang_j9_0 failure due to java.lang.NullPointerException

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9#19890]
Failure link
------------

https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal/1071/

Optional info
-------------

Seen in the JITServer nightly tests, but a [100x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42190/) without JITServer had 1/100 failures, so it's not JITServer-specific.

Failure output (captured from console output)
---------------------------------------------

Failing components and version info:

```
# DETECTED_JAVA_VERSION=openjdk version "11.0.24-internal" 2024-07-16
# OpenJDK Runtime Environment (build 11.0.24-internal+0-adhoc..BuildJDK11s390xlinuxjitPersonal)
# Eclipse OpenJ9 VM (build master-b2674c2d743, JRE 11 Linux s390x-64-Bit Compressed References 20240719_1493 (JIT enabled, AOT enabled)
# OpenJ9   - b2674c2d743
# OMR      - de311dd2b79
# JCL      - 3024b8f619b based on jdk-11.0.24+7)
# DETECTED_RELEASE_INFO=IMPLEMENTOR="Eclipse OpenJ9"
# JAVA_RUNTIME_VERSION="11.0.24-internal+0-adhoc..BuildJDK11s390xlinuxjitPersonal"
# JAVA_VERSION="11.0.24"
# JAVA_VERSION_DATE="2024-07-16"

not ok 1 - jdk_lang_j9_0
  ---
    output:
      |
        Failed test cases: 
        TEST: java/lang/Character/UnicodeCasingTest.java
        TEST: java/lang/Class/forName/modules/TestDriver.java
        TEST: java/lang/Class/getFields/Sanity.java
        TEST: java/lang/Class/getPackageName/Basic.java
        TEST: java/lang/Class/getResource/ResourcesTest.java
        TEST: java/lang/Class/GetPackageTest.java
        TEST: java/lang/ClassLoader/getResource/modules/ResourcesTest.java
        TEST: java/lang/ClassLoader/getResource/GetResource.java
        TEST: java/lang/invoke/condy/BootstrapMethodJumboArgsTest.java
        TEST: java/lang/invoke/condy/CondyBSMInvocation.java
        TEST: java/lang/invoke/condy/CondyBSMValidationTest.java
        TEST: java/lang/invoke/condy/CondyInterfaceWithOverpassMethods.java
        TEST: java/lang/invoke/condy/CondyNameValidationTest.java
        TEST: java/lang/invoke/condy/CondyNestedTest.java
        TEST: java/lang/invoke/condy/CondyRepeatFailedResolution.java
        TEST: java/lang/invoke/condy/CondyReturnPrimitiveTest.java
        TEST: java/lang/invoke/condy/CondyStaticArgumentsTest.java
        TEST: java/lang/invoke/condy/CondyWrongType.java
        TEST: java/lang/invoke/condy/ConstantBootstrapsTest.java
        TEST: java/lang/invoke/lambda/LambdaConstructorMethodHandleUnbox.java
        TEST: java/lang/invoke/lambda/LogGeneratedClassesTest.java
        TEST: java/lang/invoke/VarHandles/VarHandleMethodReferenceTest.java
        Test results: passed: 716; failed: 22
```

Console log for `java/lang/Character/UnicodeCasingTest.java` (all the backtraces appear to be the same):

```
[2024-07-19T07:58:20.313Z] rerun:
[2024-07-19T07:58:20.313Z] cd /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/TKG/output_17213758572170/jdk_lang_j9_0/work/scratch/1 && \
[2024-07-19T07:58:20.313Z] DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus \
[2024-07-19T07:58:20.313Z] DISPLAY=:0 \
[2024-07-19T07:58:20.313Z] HOME=/home/jenkins \
[2024-07-19T07:58:20.313Z] LANG=C.UTF-8 \
[2024-07-19T07:58:20.313Z] PATH=/bin:/usr/bin:/usr/sbin \
[2024-07-19T07:58:20.313Z] XDG_RUNTIME_DIR=/run/user/1000 \
[2024-07-19T07:58:20.313Z] XDG_SESSION_CLASS=user \
[2024-07-19T07:58:20.313Z] XDG_SESSION_ID=1357 \
[2024-07-19T07:58:20.313Z] XDG_SESSION_TYPE=tty \
[2024-07-19T07:58:20.313Z]     /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/jdkbinary/j2sdk-image/bin/java \
[2024-07-19T07:58:20.313Z]         -Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseJITServer -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -Xverbosegclog' \
[2024-07-19T07:58:20.313Z]         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseJITServer -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-Xjit -J-Xgcpolicy:balanced -J-Xnocompressedrefs -J-Xverbosegclog' \
[2024-07-19T07:58:20.313Z]         -Dtest.compiler.opts= \
[2024-07-19T07:58:20.313Z]         -Dtest.java.opts= \
[2024-07-19T07:58:20.313Z]         -Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/jdkbinary/j2sdk-image \
[2024-07-19T07:58:20.313Z]         -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/jdkbinary/j2sdk-image \
[2024-07-19T07:58:20.313Z]         -Dtest.timeout.factor=8.0 \
[2024-07-19T07:58:20.313Z]         -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/jdkbinary/openjdk-test-image/jdk/jtreg/native \
[2024-07-19T07:58:20.313Z]         -Dtest.root=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk \
[2024-07-19T07:58:20.313Z]         -Dtest.name=java/lang/Character/UnicodeCasingTest.java \
[2024-07-19T07:58:20.313Z]         -Dtest.file=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Character/UnicodeCasingTest.java \
[2024-07-19T07:58:20.313Z]         -Dtest.src=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Character \
[2024-07-19T07:58:20.313Z]         -Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Character \
[2024-07-19T07:58:20.313Z]         -Dtest.classes=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/TKG/output_17213758572170/jdk_lang_j9_0/work/classes/1/java/lang/Character/UnicodeCasingTest.d \
[2024-07-19T07:58:20.313Z]         -Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/TKG/output_17213758572170/jdk_lang_j9_0/work/classes/1/java/lang/Character/UnicodeCasingTest.d \
[2024-07-19T07:58:20.313Z]         -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/TKG/output_17213758572170/jdk_lang_j9_0/work/classes/1/java/lang/Character/UnicodeCasingTest.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Character \
[2024-07-19T07:58:20.313Z]         -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/TKG/output_17213758572170/jdk_lang_j9_0/work/classes/1/java/lang/Character/UnicodeCasingTest.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Character:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_jit_Personal_testList_0/jvmtest/openjdk/jtreg/lib/jtreg.jar \
[2024-07-19T07:58:20.313Z]         UnicodeCasingTest
[2024-07-19T07:58:20.313Z] STDOUT:
[2024-07-19T07:58:20.313Z] Testing on az locale....
[2024-07-19T07:58:20.313Z] STDERR:
[2024-07-19T07:58:20.313Z] java.lang.NullPointerException
[2024-07-19T07:58:20.314Z] 	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4062)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:452)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.Integer.parseInt(Integer.java:662)
[2024-07-19T07:58:20.314Z] 	at UnicodeCasingTest.convert(UnicodeCasingTest.java:170)
[2024-07-19T07:58:20.314Z] 	at UnicodeCasingTest.test(UnicodeCasingTest.java:112)
[2024-07-19T07:58:20.314Z] 	at UnicodeCasingTest.test(UnicodeCasingTest.java:80)
[2024-07-19T07:58:20.314Z] 	at UnicodeCasingTest.main(UnicodeCasingTest.java:54)
[2024-07-19T07:58:20.314Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-07-19T07:58:20.314Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-07-19T07:58:20.314Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-07-19T07:58:20.314Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-07-19T07:58:20.314Z] java.lang.RuntimeException: UnicodeCasingTest failed.
[2024-07-19T07:58:20.314Z] 	at UnicodeCasingTest.test(UnicodeCasingTest.java:103)
[2024-07-19T07:58:20.314Z] 	at UnicodeCasingTest.main(UnicodeCasingTest.java:54)
[2024-07-19T07:58:20.314Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-07-19T07:58:20.314Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-07-19T07:58:20.314Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-07-19T07:58:20.314Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-07-19T07:58:20.314Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
```

Note that the typical backtrace in the failing components from the non-JITServer grinder above is a little different, but seems to be compatible:

```
[2024-07-19T22:06:24.561Z] STDERR:
[2024-07-19T22:06:24.561Z] java.lang.NullPointerException
[2024-07-19T22:06:24.561Z] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[2024-07-19T22:06:24.561Z] 	at java.base/java.lang.Integer.parseInt(Integer.java:662)
[2024-07-19T22:06:24.561Z] 	at UnicodeCasingTest.convert(UnicodeCasingTest.java:170)
[2024-07-19T22:06:24.561Z] 	at UnicodeCasingTest.test(UnicodeCasingTest.java:112)
[2024-07-19T22:06:24.561Z] 	at UnicodeCasingTest.test(UnicodeCasingTest.java:80)
[2024-07-19T22:06:24.561Z] 	at UnicodeCasingTest.main(UnicodeCasingTest.java:54)
[2024-07-19T22:06:24.561Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-07-19T22:06:24.561Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-07-19T22:06:24.561Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-07-19T22:06:24.561Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-07-19T22:06:24.561Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-07-19T22:06:24.561Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-07-19T22:06:24.561Z] java.lang.RuntimeException: UnicodeCasingTest failed.
[2024-07-19T22:06:24.561Z] 	at UnicodeCasingTest.test(UnicodeCasingTest.java:103)
[2024-07-19T22:06:24.561Z] 	at UnicodeCasingTest.main(UnicodeCasingTest.java:54)
[2024-07-19T22:06:24.561Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-07-19T22:06:24.561Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-07-19T22:06:24.561Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-07-19T22:06:24.561Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[2024-07-19T22:06:24.561Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-07-19T22:06:24.561Z] 	at java.base/java.lang.Thread.run(Thread.java:839)
[2024-07-19T22:06:24.561Z] 
[2024-07-19T22:06:24.561Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2024-07-19T22:06:24.561Z] JavaTest Message: shutting down test
[2024-07-19T22:06:24.561Z] 
[2024-07-19T22:06:24.561Z] 
[2024-07-19T22:06:24.561Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: UnicodeCasingTest failed.
```

**Comment by pshipton** [comment]
Guessing JIT given the intermittent nature. Given the failure rate I don't expect anyone to look at it, unless there is some reason to bump up the priority.
