### ISSUE TITLE
80 FVT_Serviceability.trace.verbosegc_finalizers.Mode103.1 org.xml.sax.SAXParseException: cvc-complex-type.3.2.2: Attribute 'id' is not allowed to appear in element 'cpu-util'

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19955]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=89648370)(`aix72p9-06`):
```
java version "1.8.0_421"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pap6480sr9-20240624_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit 20240731_75514 (JIT enabled, AOT enabled)
OpenJ9   - c5feabd1eae
OMR      - 3baeead
IBM      - dd9cff8)
JCL - 20240618_01 based on Oracle jdk8u421-b09
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
>> 2024 Thu Aug 1 00:09:53 20240801 00:09:51- Tests which threw Exceptions (Error Tests):
>> 2024 Thu Aug 1 00:09:53 20240801 00:09:51- * - testLogfileMatchesSchema(tests.com.ibm.jtc.vgcvalidate.VerboseGcLogValidation)
>> 2024 Thu Aug 1 00:09:53 20240801 00:09:51- org.xml.sax.SAXParseException: cvc-complex-type.3.2.2: Attribute 'id' is not allowed to appear in element 'cpu-util'.
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.impl.xs.XMLSchemaValidator.processAttributes(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.jaxp.validation.DOMValidatorHelper.beginNode(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at javax.xml.validation.Validator.validate(Unknown Source)
>> 2024 Thu Aug 1 00:09:53      at tests.com.ibm.jtc.vgcvalidate.VerboseGcLogValidation.testLogfileMatchesSchema(VerboseGcLogValidation.java:177)
>> 2024 Thu Aug 1 00:09:53      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>> 2024 Thu Aug 1 00:09:53      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
>> 2024 Thu Aug 1 00:09:53      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
>> 2024 Thu Aug 1 00:09:53      at com.ibm.jtc.junit.VerboseTestRunner.runTest(VerboseTestRunner.java:135)
>> 2024 Thu Aug 1 00:09:53      at com.ibm.jtc.junit.VerboseTestRunner.main(VerboseTestRunner.java:71)
>> 2024 Thu Aug 1 00:09:53 
>> 2024 Thu Aug 1 00:09:53 20240801 00:09:51- 
>> 2024 Thu Aug 1 00:09:53 20240801 00:09:51- JUnit Runner Shows Test Failed
>> 2024 Thu Aug 1 00:09:53 Copying the schema from the SDK to the results directory
>> 2024 Thu Aug 1 00:09:53 Copying the vgclog XML file to the current results directory
>> 2024 Thu Aug 1 00:09:53 10 pending-finalizer tags scanned, 5 error(s) found
>> 2024 Thu Aug 1 00:09:53 Number of Errors = 5
>> 2024 Thu Aug 1 00:09:53 Trace Verbose GC check pending finalizers test failed...
>> 2024 Thu Aug 1 00:09:53 VGC LOG ERROR: Axxon_junit.pl return code was non-zero
>> 2024 Thu Aug 1 00:09:53 VGC LOG ERROR: JUnit verification script did not report success, message was : TEST SUMMARY - TEST FAILED
>> 2024 Thu Aug 1 00:09:53 VGC LOG ERROR: There were problems encountered during the verbose GC log validation
>> 2024 Thu Aug 1 00:09:53 VGC LOG ERROR: 0 JUnit tests failed
>> 2024 Thu Aug 1 00:09:53 VGC LOG ERROR: 1 JUnit tests had errors


>> 2024 Thu Aug 1 00:09:53 *************************************************
>> 2024 Thu Aug 1 00:09:53 Trace Test Result Summary:
>> 2024 Thu Aug 1 00:09:53  Trace Verbose GC check pending finalizers FAILED
>> 2024 Thu Aug 1 00:09:53 *************************************************


**************************************************************************
>> 2024 Thu Aug 1 00:09:53 Axxon_trace.pl TEST SUMMARY - ALL TESTS FAILED
```

It seems related to
* ~https://github.com/eclipse/omr/pull/7424~
* https://github.com/eclipse/omr/pull/7420

FYI @keithc-ca @amicic

**Comment by amicic** [comment]
This has my introduction of cpu-util, but not the fix from @keithc-ca 

OMR (internal) diff: https://github.ibm.com/runtimes/openj9-omr/compare/cdb95afd0b529d...3baeeadb3735a6

**Comment by JasonFengJ9** [comment]
I see, it was
* https://github.com/eclipse/omr/pull/7420

**Comment by keithc-ca** [comment]
This should be fixed by https://github.com/eclipse/omr/pull/7429.
