### ISSUE TITLE
cmdLineTester_jfr FileNotFoundException jfr.xml 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19950]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_x86-64_linux_Nightly_testList_1/83/ - [cent7-x64-6](https://openj9-jenkins.osuosl.org/computer/cent7-x64-6)
cmdLineTester_jfr_0
```
05:43:51  TESTING:
05:43:51  java.io.FileNotFoundException: /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jfr/jfr.xml (No such file or directory)
05:43:51  	at java.base/java.io.FileInputStream.open0(Native Method)
05:43:51  	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
05:43:51  	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
05:43:51  	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
05:43:51  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:455)
05:43:51  	at TestConfigParser.runTests(TestConfigParser.java:78)
05:43:51  	at MainTester.main(MainTester.java:106)
05:43:51  java.lang.NullPointerException
05:43:51  	at java.base/java.io.Reader.<init>(Reader.java:168)
05:43:51  	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:88)
05:43:51  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:468)
05:43:51  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)
05:43:51  	at TestConfigParser.runTests(TestConfigParser.java:78)
05:43:51  	at MainTester.main(MainTester.java:106)
05:43:51  Exception in thread "main" java.lang.NullPointerException: Cannot invoke "TestSuite.printResults()" because "suite" is null
05:43:51  	at MainTester.main(MainTester.java:107)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_x86-64_linux_Nightly_testList_0/182 - [cent7-x64-1](https://openj9-jenkins.osuosl.org/computer/cent7-x64-1)

@llxia any ideas what is going wrong?
@TobiAjila fyi

**Comment by keithc-ca** [comment]
Perhaps `build.xml` needs more general name patterns; that is
```
		<copy todir="${DEST}">
			<fileset dir="${src}/../">
				<filename name="metadata.blob" />
				<filename name="*.mk" />
				<filename name="*.xml" />
			</fileset>
		</copy>
```
should be?
```
		<copy todir="${DEST}">
			<fileset dir="${src}/../">
				<filename name="**/metadata.blob" />
				<filename name="**/*.mk" />
				<filename name="**/*.xml" />
			</fileset>
		</copy>
```

**Comment by tajila** [comment]
@thallium Can you try the sugestion above

**Comment by thallium** [comment]
> Can you try the sugestion above

No that didn't work, maybe we need to revert back to `<fileset dir="${src}/../" includes="*.xml,*.mk,metadata.blob" />`.

**Comment by keithc-ca** [comment]
The documentation at https://ant.apache.org/manual/Types/fileset.html suggests that my suggestion should be equivalent to
```
		<copy todir="${DEST}">
			<fileset dir="${src}/../">
				<include name="**/metadata.blob" />
				<include name="**/*.mk" />
				<include name="**/*.xml" />
			</fileset>
		</copy>
```
which _does_ work.

**Comment by thallium** [comment]
Can confirm that using `include` tag works.

**Comment by keithc-ca** [comment]
I also note that there are no files matching the `*.mk` pattern so that could be removed.

**Comment by thallium** [comment]
Opened PR: https://github.com/eclipse-openj9/openj9/pull/19957
