### ISSUE TITLE
jdk/internal/vm/Continuation/OSRTest needs WhiteBox natives

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19961]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OpenJDK21_testList_0/25/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OpenJDK21_testList_1/25/
jdk/internal/vm/Continuation/OSRTest.java
```
10:35:09  java.lang.UnsatisfiedLinkError: jdk/test/whitebox/WhiteBox.registerNatives()V
10:35:09  	at jdk.test.whitebox.WhiteBox.<clinit>(WhiteBox.java:67)
10:35:09  	at OSRTest.<clinit>(OSRTest.java:52)
10:35:09  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
10:35:09  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
10:35:09  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
10:35:09  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
10:35:09  	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:159)
10:35:09  	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:732)
10:35:09  	at java.base/java.lang.reflect.Method.invoke(Method.java:583)
10:35:09  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
10:35:09  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment]
Similar to https://github.com/eclipse-openj9/openj9/issues/19357
