### ISSUE TITLE
jdk_util_0_FAILED java/util/concurrent/ExecutorService/CloseTest.java IllegalStateException 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19979]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_testList_0/203/)(`rhel9s390x-svl-rt5-1`):
```
java version "21.0.5-beta" 2024-10-15
IBM Semeru Runtime Certified Edition 21.0.5+1-202408060004 (build 21.0.5-beta+1-202408060004)
Eclipse OpenJ9 VM 21.0.5+1-202408060004 (build master-27dac39d2c, JRE 21 Linux s390x-64-Bit Compressed References 20240806_245 (JIT enabled, AOT enabled)
OpenJ9   - 27dac39d2c
OMR      - 9ccff3cf2
JCL      - fbac205a7 based on jdk-21.0.5+1)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_util_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_sanity.openjdk_s390x_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-s390x-openj9-IBM%2F245%2Fibm-semeru-certified-jdk_s390x_linux_JDK21U_2024-08-05-23-31.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-s390x-openj9-IBM%2F245%2Fibm-semeru-certified-testimage_s390x_linux_JDK21U_2024-08-05-23-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=213&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-08-06T02:17:43.541Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2024-08-06T02:17:43.541Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2024-08-06T02:23:02.633Z] TEST: java/util/concurrent/ExecutorService/CloseTest.java

[2024-08-06T02:23:02.636Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@6de31b7): failure
[2024-08-06T02:23:02.636Z] java.lang.IllegalStateException
[2024-08-06T02:23:02.636Z] 	at java.base/java.util.concurrent.ForkJoinTask.resultNow(ForkJoinTask.java:898)
[2024-08-06T02:23:02.636Z] 	at CloseTest.testShutdownBeforeClose(CloseTest.java:112)
[2024-08-06T02:23:02.636Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-08-06T02:23:02.636Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2024-08-06T02:23:02.636Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2024-08-06T02:23:02.636Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[2024-08-06T02:23:02.636Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2024-08-06T02:23:02.636Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2024-08-06T02:23:02.636Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2024-08-06T02:23:02.636Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2024-08-06T02:23:02.636Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2024-08-06T02:23:02.636Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2024-08-06T02:23:02.636Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2024-08-06T02:23:02.636Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2024-08-06T02:23:02.636Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2024-08-06T02:23:02.636Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2024-08-06T02:23:02.636Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2024-08-06T02:23:02.636Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2024-08-06T02:23:02.636Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
[2024-08-06T02:23:02.636Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-08-06T02:23:02.636Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-08-06T02:23:02.636Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-08-06T02:23:02.636Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-08-06T02:23:02.636Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ThreadPoolExecutor@f215d6ee): success
[2024-08-06T02:23:02.636Z] test CloseTest.testShutdownBeforeClose(java.util.concurrent.ThreadPoolExecutor@57d1ffd6): success

[2024-08-06T02:23:02.637Z] test CloseTest.testTerminateBeforeClose(java.util.concurrent.ThreadPerTaskExecutor@54b35164): success
[2024-08-06T02:23:02.637Z] test CloseTest.testTerminateBeforeClose(java.util.concurrent.ThreadPerTaskExecutor@d58c8e4a): success
[2024-08-06T02:23:02.637Z] 
[2024-08-06T02:23:02.637Z] ===============================================
[2024-08-06T02:23:02.637Z] java/util/concurrent/ExecutorService/CloseTest.java
[2024-08-06T02:23:02.637Z] Total tests run: 36, Passes: 35, Failures: 1, Skips: 0
[2024-08-06T02:23:02.637Z] ===============================================
[2024-08-06T02:23:02.637Z] 
[2024-08-06T02:23:02.637Z] STDERR:
[2024-08-06T02:23:02.637Z] java.lang.Exception: failures: 1
[2024-08-06T02:23:02.637Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:104)
[2024-08-06T02:23:02.637Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-08-06T02:23:02.637Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-08-06T02:23:02.637Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-08-06T02:23:02.637Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-08-06T02:23:02.637Z] 
[2024-08-06T02:23:02.637Z] JavaTest Message: Test threw exception: java.lang.Exception
[2024-08-06T02:23:02.637Z] JavaTest Message: shutting down test
[2024-08-06T02:23:02.637Z] 
[2024-08-06T02:23:02.637Z] 
[2024-08-06T02:23:02.637Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2024-08-06T02:23:02.637Z] --------------------------------------------------
[2024-08-06T02:44:07.747Z] Test results: passed: 950; failed: 1
[2024-08-06T02:44:23.123Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_17229050895965/jdk_util_0/report/html/report.html
[2024-08-06T02:44:23.123Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_17229050895965/jdk_util_0/work
[2024-08-06T02:44:23.123Z] Error: Some tests failed or other problems occurred.
[2024-08-06T02:44:23.123Z] -----------------------------------
[2024-08-06T02:44:23.123Z] jdk_util_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42636/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_OMR_testList_2/270
jdk_util_1
java/util/concurrent/ExecutorService/CloseTest.jav
```
06:43:19  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@d16ec4f7): failure
06:43:19  java.lang.IllegalStateException
06:43:19  	at java.base/java.util.concurrent.ForkJoinTask.resultNow(ForkJoinTask.java:898)
06:43:19  	at CloseTest.testShutdownBeforeClose(CloseTest.java:112)
```
