### ISSUE TITLE
Jep442Tests_testLinkerFfi_DownCall FAILED: test_addBoolStruct1AndNestedBoolArrayStruct2WithXor_returnStruct2_dupStruct

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20087]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.functional_ppc64_aix_testList_1/220/)(`paix906`):
```
java version "21.0.5-beta" 2024-10-15
IBM Semeru Runtime Certified Edition 21.0.5+4-202408290026 (build 21.0.5-beta+4-202408290026)
Eclipse OpenJ9 VM 21.0.5+4-202408290026 (build master-41d13b1de3, JRE 21 AIX ppc64-64-Bit Compressed References 20240829_246 (JIT enabled, AOT enabled)
OpenJ9   - 41d13b1de3
OMR      - 6dc282ee5
JCL      - 405d32414 based on jdk-21.0.5+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=Jep442Tests_testLinkerFfi_DownCall_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_sanity.functional_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-aix-ppc64-openj9-IBM%2F246%2Fibm-semeru-certified-jdk_ppc64_aix_JDK21U_2024-08-28-23-31.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-aix-ppc64-openj9-IBM%2F246%2Fibm-semeru-certified-testimage_ppc64_aix_JDK21U_2024-08-28-23-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=240&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-08-29T04:45:27.817Z] variation: --enable-preview
[2024-08-29T04:45:27.817Z] JVM_OPTIONS:  --enable-preview 

[2024-08-29T04:45:33.953Z] FAILED: test_addBoolStruct1AndNestedBoolArrayStruct2WithXor_returnStruct2_dupStruct
[2024-08-29T04:45:33.953Z] java.util.NoSuchElementException: No value present
[2024-08-29T04:45:33.953Z] 	at java.base/java.util.Optional.get(Optional.java:143)
[2024-08-29T04:45:33.953Z] 	at org.openj9.test.jep442.downcall.DuplicateStructTests.test_addBoolStruct1AndNestedBoolArrayStruct2WithXor_returnStruct2_dupStruct(DuplicateStructTests.java:227)
[2024-08-29T04:45:33.953Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-08-29T04:45:33.953Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-08-29T04:45:33.953Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2024-08-29T04:45:33.953Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2024-08-29T04:45:33.953Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2024-08-29T04:45:33.953Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2024-08-29T04:45:33.953Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2024-08-29T04:45:33.953Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2024-08-29T04:45:33.953Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2024-08-29T04:45:33.953Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2024-08-29T04:45:33.953Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2024-08-29T04:45:33.953Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2024-08-29T04:45:33.953Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2024-08-29T04:45:33.953Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2024-08-29T04:45:33.953Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2024-08-29T04:45:33.953Z] 
[2024-08-29T04:45:33.953Z] 
[2024-08-29T04:45:33.953Z] ===============================================
[2024-08-29T04:45:33.953Z]     Jep442Tests_testLinkerFfi_DownCall
[2024-08-29T04:45:33.953Z]     Tests run: 595, Failures: 1, Skips: 0
[2024-08-29T04:45:33.953Z] ===============================================
[2024-08-29T04:45:33.953Z] 
[2024-08-29T04:45:33.953Z] 
[2024-08-29T04:45:33.953Z] ===============================================
[2024-08-29T04:45:33.953Z] Java21 only test suite
[2024-08-29T04:45:33.953Z] Total tests run: 595, Failures: 1, Skips: 0
[2024-08-29T04:45:33.953Z] ===============================================
[2024-08-29T04:45:33.953Z] 
[2024-08-29T04:45:34.710Z] 
[2024-08-29T04:45:34.710Z] 15 + 27 = 42
[2024-08-29T04:45:34.710Z] 
[2024-08-29T04:45:34.710Z] 15 + 27 = 42
[2024-08-29T04:45:34.710Z] 
[2024-08-29T04:45:34.710Z] 15 + 27 = 42
[2024-08-29T04:45:34.710Z] 
[2024-08-29T04:45:34.710Z] 15 + 27 = 42
[2024-08-29T04:45:34.710Z] -----------------------------------
[2024-08-29T04:45:34.710Z] Jep442Tests_testLinkerFfi_DownCall_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42945/) - all failed

This is different from 
* https://github.com/eclipse-openj9/openj9/issues/20048

**Comment by ChengJin01** [comment]
The [internal JDK & test-images ](https://na-public.artifactory.swg-devops.com/ui/native/sys-rt-generic-local/hyc-runtimes-jenkins.swg-devops.com/build-scripts/jobs/jdk21u/jdk21u-aix-ppc64-openj9-IBM/246/)
```
JDK 2024-08-28 21:35:51 -0400 255.4 MB
test-image 2024-08-28 21:36:05 -0400  60.9 MB
```
were generated at 21:36 yesterday before the changes at https://github.com/eclipse-openj9/openj9/pull/20080 which is merged at `20:56`.

**Comment by ChengJin01** [comment]
@JasonFengJ9 & @pshipton, please wait to let the Jenkins job pick up the latest nightly build generated today to verify the test.

**Comment by JasonFengJ9** [comment]
Passed [an internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/4425/console) with latest nightly build.

Closing
