### ISSUE TITLE
OpenJDK java/lang/invoke/RicochetTest arrays first differed at element

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20095]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Release_testList_0/52
jdk_lang_0
java/lang/invoke/RicochetTest.java
```
18:53:33  STARTED    test.java.lang.invoke.RicochetTest::testByteSpreads 'testByteSpreads'
18:53:33  arrays first differed at element [0]; expected:<11> but was:<0>
18:53:33  	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)
18:53:33  	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
18:53:33  	at org.junit.Assert.internalArrayEquals(Assert.java:534)
18:53:33  	at org.junit.Assert.assertArrayEquals(Assert.java:343)
18:53:33  	at org.junit.Assert.assertArrayEquals(Assert.java:354)
18:53:33  	at test.java.lang.invoke.RicochetTest.testByteSpreads(RicochetTest.java:194)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/418 - [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3)
jdk_lang_j9_1
java/lang/invoke/RicochetTest.java
```
06:02:50  STARTED    test.java.lang.invoke.RicochetTest::testByteSpreads 'testByteSpreads'
06:02:50  arrays first differed at element [0]; expected:<11> but was:<0>
06:02:50  	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)
06:02:50  	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
06:02:50  	at org.junit.Assert.internalArrayEquals(Assert.java:534)
06:02:50  	at org.junit.Assert.assertArrayEquals(Assert.java:343)
06:02:50  	at org.junit.Assert.assertArrayEquals(Assert.java:354)
06:02:50  	at test.java.lang.invoke.RicochetTest.testByteSpreads(RicochetTest.java:194)
```
