### ISSUE TITLE
OpenJDK java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20106]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/268 - [p8-java1-ibm04](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm04)
jdk_lang_VarHandleTest_j9_1
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java

```
00:52:03  test VarHandleTestByteArrayAsChar.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@5892e82c): failure
00:52:03  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -1. Expected class java.lang.NullPointerException expected [true] but found [false]
00:52:03  	at org.testng.Assert.fail(Assert.java:99)
00:52:03  	at org.testng.Assert.failNotEquals(Assert.java:1037)
00:52:03  	at org.testng.Assert.assertTrue(Assert.java:45)
00:52:03  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
00:52:03  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
00:52:03  	at VarHandleTestByteArrayAsChar.testArrayNPE(VarHandleTestByteArrayAsChar.java:247)
00:52:03  	at VarHandleTestByteArrayAsChar.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsChar.java:175)
00:52:03  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
00:52:03  	at VarHandleTestByteArrayAsChar.testAccess(VarHandleTestByteArrayAsChar.java:229)

...

00:52:03  test VarHandleTestByteArrayAsChar.testAccess(" VarHandle [ALIGNED, LITTLE_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@ad7b28f4): failure
00:52:03  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -1. Expected class java.lang.NullPointerException expected [true] but found [false]
00:52:03  	at org.testng.Assert.fail(Assert.java:99)
00:52:03  	at org.testng.Assert.failNotEquals(Assert.java:1037)
00:52:03  	at org.testng.Assert.assertTrue(Assert.java:45)
00:52:03  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
00:52:03  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
00:52:03  	at VarHandleTestByteArrayAsChar.testArrayNPE(VarHandleTestByteArrayAsChar.java:247)
00:52:03  	at VarHandleTestByteArrayAsChar.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsChar.java:175)
00:52:03  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
00:52:03  	at VarHandleTestByteArrayAsChar.testAccess(VarHandleTestByteArrayAsChar.java:229)

```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/295
jdk_lang_VarHandleTest_j9_1
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java
```
22:40:45  test VarHandleTestByteArrayAsChar.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@91879ac8): failure
22:40:45  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -1. Expected class java.lang.NullPointerException expected [true] but found [false]
22:40:45  	at org.testng.Assert.fail(Assert.java:99)
22:40:45  	at org.testng.Assert.failNotEquals(Assert.java:1037)
22:40:45  	at org.testng.Assert.assertTrue(Assert.java:45)
22:40:45  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
22:40:45  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
22:40:45  	at VarHandleTestByteArrayAsChar.testArrayNPE(VarHandleTestByteArrayAsChar.java:247)
22:40:45  	at VarHandleTestByteArrayAsChar.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsChar.java:175)
22:40:45  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
22:40:45  	at VarHandleTestByteArrayAsChar.testAccess(VarHandleTestByteArrayAsChar.java:229)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/317/
jdk_lang_VarHandleTest_j9_1
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsDouble.java
```
22:54:39  test VarHandleTestByteArrayAsDouble.testAccess(" VarHandle [ALIGNED, LITTLE_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@65b6167b): failure
22:54:39  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -7. Expected class java.lang.NullPointerException expected [true] but found [false]
22:54:39  	at org.testng.Assert.fail(Assert.java:99)
22:54:39  	at org.testng.Assert.failNotEquals(Assert.java:1037)
22:54:39  	at org.testng.Assert.assertTrue(Assert.java:45)
22:54:39  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
22:54:39  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
22:54:39  	at VarHandleTestByteArrayAsDouble.testArrayNPE(VarHandleTestByteArrayAsDouble.java:247)
22:54:39  	at VarHandleTestByteArrayAsDouble.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsDouble.java:175)
```

**Comment by hzongaro** [comment]
I've had no luck reproducing this in grinder runs.  I even tried rebuilding with source from around 2024-11-04, as a couple of the failures were seen around that point.  I will push this out to the Future release, as I had [previously done with issue #21515](https://github.com/eclipse-openj9/openj9/issues/21515#issuecomment-2894438552), which might be a duplicate.  If the problem occurs again, we can resume investigating.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_1/522
jdk_lang_VarHandleTest_j9_0
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java
```
23:32:17  test VarHandleTestByteArrayAsChar.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@3b76da3e): failure
23:32:17  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -1. Expected class java.lang.NullPointerException expected [true] but found [false]
23:32:17  	at org.testng.Assert.fail(Assert.java:99)
23:32:17  	at org.testng.Assert.failNotEquals(Assert.java:1037)
23:32:17  	at org.testng.Assert.assertTrue(Assert.java:45)
23:32:17  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
23:32:17  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
23:32:17  	at VarHandleTestByteArrayAsChar.testArrayNPE(VarHandleTestByteArrayAsChar.java:247)
23:32:17  	at VarHandleTestByteArrayAsChar.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsChar.java:175)
23:32:17  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
23:32:17  	at VarHandleTestByteArrayAsChar.testAccess(VarHandleTestByteArrayAsChar.java:229)
```

**Comment by hzongaro** [comment]
See details of investigation in duplicate defect #21515.[1,2]

[1] https://github.com/eclipse-openj9/openj9/issues/21515#issuecomment-3260220576
[2] https://github.com/eclipse-openj9/openj9/issues/21515#issuecomment-3266102082

**Comment by hzongaro** [comment]
I haven't had a chance to attend to review comments for the pull request that should fix this problem yet.  As the M2 build for the 0.56 release is planned soon, I'll move this out to 0.57.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/308
jdk_lang_VarHandleTest_j9_0
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsLong.java

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/360
jdk_lang_VarHandleTest_j9_0
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsDouble.java
```
10:21:06  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -7. Expected class java.lang.NullPointerException expected [true] but found [false]
10:21:06  	at org.testng.Assert.fail(Assert.java:99)
10:21:06  	at org.testng.Assert.failNotEquals(Assert.java:1037)
10:21:06  	at org.testng.Assert.assertTrue(Assert.java:45)
10:21:06  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
10:21:06  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
10:21:06  	at VarHandleTestByteArrayAsDouble.testArrayNPE(VarHandleTestByteArrayAsDouble.java:247)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_1/697
jdk_lang_VarHandleTest_j9_0
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsLong.java
```
23:15:16  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -7. Expected class java.lang.NullPointerException expected [true] but found [false]
23:15:16  	at org.testng.Assert.fail(Assert.java:99)
23:15:16  	at org.testng.Assert.failNotEquals(Assert.java:1037)
23:15:16  	at org.testng.Assert.assertTrue(Assert.java:45)
23:15:16  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
23:15:16  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
23:15:16  	at VarHandleTestByteArrayAsLong.testArrayNPE(VarHandleTestByteArrayAsLong.java:247)
```
