### ISSUE TITLE
jdk_lang_j9_0 java/lang/System/LoggerFinder/SignedLoggerFinderTest/SignedLoggerFinderTest.java Failed. Unexpected exit from test [exit code: 143]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20125]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_testList_2/37/)(`sles12le-rtp-rt5-1`):
```
java version "11.0.24" 2024-07-16
IBM Semeru Runtime Certified Edition 11.0.24.1 (build 11.0.24+8)
Eclipse OpenJ9 VM 11.0.24.1 (build v0.46.1-release-4760d5d320, JRE 11 Linux ppc64le-64-Bit Compressed References 20240904_938 (JIT enabled, AOT enabled)
OpenJ9   - 4760d5d320
OMR      - 840a9adba
JCL      - f612edf7e4 based on jdk-11.0.24+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_lang_j9_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=9f50c848-8764-440d-b95a-1d295c21713e&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.openjdk_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=functional%2Cjck%2Copenjdk&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fhyc-runtimes-jenkins.swg-devops.com%2Fjob%2Fbuild-scripts%2Fjob%2Fopenjdk11-pipeline-IBM%2F892%2Fartifact%2Ftarget%2Flinux%2Fppc64le%2Fopenj9%2F*.tar.gz%2F*zip*%2Fopenj9.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git%2Cgit%40github.ibm.com%3Aruntimes%2Fosb-tests.git&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=main&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master%2Cmain%2Cibm_tlda&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=821&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=f3b78d91-4db0-4a87-b4d8-32164430cfdc&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;separator-87e3a7db-4843-4907-ad26-40f469fe3204=&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-09-05T13:55:24.552Z] Running test jdk_lang_j9_0 ...

[2024-09-05T13:55:24.552Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
[2024-09-05T13:55:24.552Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -Xverbosegclog 

[2024-09-05T15:03:19.678Z] TEST: java/lang/System/LoggerFinder/SignedLoggerFinderTest/SignedLoggerFinderTest.java

[2024-09-05T15:03:19.680Z] TEST RESULT: Failed. Unexpected exit from test [exit code: 143]
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/43009/)

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/585/
jdk_lang_j9_0
java/lang/System/LoggerFinder/SignedLoggerFinderTest/SignedLoggerFinderTest.java
```
21:20:35  TEST LOGGER: Runtime.exit() called with status: 97
21:20:35  STDERR:
21:20:35   stdout: [multi thread load sleep value: 39
21:20:35  Logger finder service load sleep value: 691
21:20:35  TEST LOGGER: [SHA384withRSA, 38:8b:6c:57:dd:dc:61:99, CN=sample, CN=sample, RSA, 3072, 1421787896, Wed Oct 08 01:20:06 UTC 2025, Tue Jan 06 01:20:06 UTC 2026]
21:20:35  TEST LOGGER: [SHA384withRSA, 38:8b:6c:57:dd:dc:61:99, CN=sample, CN=sample, RSA, 3072, 1421787896, Wed Oct 08 01:20:06 UTC 2025, Tue Jan 06 01:20:06 UTC 2026]
21:20:35  TEST LOGGER: [SHA384withRSA, 38:8b:6c:57:dd:dc:61:99, CN=sample, CN=sample, RSA, 3072, 1421787896, Wed Oct 08 01:20:06 UTC 2025, Tue Jan 06 01:20:06 UTC 2026]
21:20:35  System.getLoggerFinder type: loggerfinder.SimpleLoggerFinder
21:20:35  TEST LOGGER: [test_2, test]
21:20:35  System.getLogger type: loggerfinder.SimpleLoggerFinder$SimpleLogger
21:20:35  ];
21:20:35   stderr: [URLClassPath.getResource("SignedLoggerFinderTest.class")

...

21:20:35  java.lang.RuntimeException: Unexpected fail.
21:20:35  	at SignedLoggerFinderTest.launchTest(SignedLoggerFinderTest.java:218)
21:20:35  	at SignedLoggerFinderTest.main(SignedLoggerFinderTest.java:104)
21:20:35  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
21:20:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
21:20:35  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
21:20:35  	at java.base/java.lang.Thread.run(Thread.java:1595)
21:20:35  Caused by: java.lang.RuntimeException: 'TEST LOGGER: [test_1, test]' missing from stdout/stderr
21:20:35  	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:238)
21:20:35  	at SignedLoggerFinderTest.launchTest(SignedLoggerFinderTest.java:204)
21:20:35  	... 5 more
```
