### ISSUE TITLE
jdk_lang_VarHandleTest_j9_1_FAILED java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -3

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20156]
From https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Release_testList_2/45/consoleFull
```
07:07:48  openjdk version "17.0.13-internal" 2024-10-15
07:07:48  OpenJDK Runtime Environment (build 17.0.13-internal+0-adhoc.****.BuildJDK17ppc64aixRelease)
07:07:48  Eclipse OpenJ9 VM (build v0.48.0-release-f9be5355254, JRE 17 AIX ppc64-64-Bit Compressed References 20240907_128 (JIT enabled, AOT enabled)
07:07:48  OpenJ9   - f9be5355254
07:07:48  OMR      - cfe6789bfa8
07:07:48  JCL      - 0ce0af44811 based on jdk-17.0.13+6)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_lang_VarHandleTest_j9_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Release&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Release&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_ppc64_aix_Release%2F128%2FOpenJ9-JDK17-ppc64_aix-20240907-232552.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_ppc64_aix_Release%2F128%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.4-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=v0.48.0-release&OPENJ9_SHA=f9be5355254563f935b8aabcdfbe800e561cd20c&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.48.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=109&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
07:09:02  ===============================================
07:09:02  Running test jdk_lang_VarHandleTest_j9_1 ...
07:09:02  ===============================================
07:09:02  jdk_lang_VarHandleTest_j9_1 Start Time: Sun Sep  8 10:52:58 2024 Epoch Time (ms): 1725792778116
07:09:02  variation: -Xjit:enableAggressiveLiveness -XX:-JITServerTechPreviewMessage -Xjit:scratchSpaceFactorWhenJSR292Workload=1 Mode650
07:09:02  JVM_OPTIONS:  -Xjit:enableAggressiveLiveness -XX:-JITServerTechPreviewMessage -Xjit:scratchSpaceFactorWhenJSR292Workload=1 -XX:-UseCompressedOops -Xverbosegclog 

07:12:19  TEST: java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java

07:12:19  test VarHandleTestByteArrayAsInt.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@601e8d54): failure
07:12:19  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -3. Expected class java.lang.NullPointerException expected [true] but found [false]
07:12:19  	at org.testng.Assert.fail(Assert.java:99)
07:12:19  	at org.testng.Assert.failNotEquals(Assert.java:1037)
07:12:19  	at org.testng.Assert.assertTrue(Assert.java:45)
07:12:19  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
07:12:19  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
07:12:19  	at VarHandleTestByteArrayAsInt.testArrayNPE(VarHandleTestByteArrayAsInt.java:247)
07:12:19  	at VarHandleTestByteArrayAsInt.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsInt.java:175)
07:12:19  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
07:12:19  	at VarHandleTestByteArrayAsInt.testAccess(VarHandleTestByteArrayAsInt.java:229)

07:12:19  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
07:12:19  --------------------------------------------------
07:14:55  Test results: passed: 37; failed: 1
07:15:02  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Release_testList_2/aqa-tests/TKG/output_17257927499229/jdk_lang_VarHandleTest_j9_1/report/html/report.html
07:15:02  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Release_testList_2/aqa-tests/TKG/output_17257927499229/jdk_lang_VarHandleTest_j9_1/work
07:15:02  Error: Some tests failed or other problems occurred.
07:15:02  -----------------------------------
07:15:02  jdk_lang_VarHandleTest_j9_1_FAILED
```

50x grinder - https://openj9-jenkins.osuosl.org/job/Grinder/3833/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_1/314
jdk_lang_VarHandleTest_j9_0
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java
```
23:27:49  test VarHandleTestByteArrayAsInt.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@73e19708): failure
23:27:49  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -3. Expected class java.lang.NullPointerException expected [true] but found [false]
23:27:49  	at org.testng.Assert.fail(Assert.java:99)
23:27:49  	at org.testng.Assert.failNotEquals(Assert.java:1037)
23:27:49  	at org.testng.Assert.assertTrue(Assert.java:45)
23:27:49  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
23:27:49  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
23:27:49  	at VarHandleTestByteArrayAsInt.testArrayNPE(VarHandleTestByteArrayAsInt.java:247)
23:27:49  	at VarHandleTestByteArrayAsInt.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsInt.java:175)
23:27:49  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
23:27:49  	at VarHandleTestByteArrayAsInt.testAccess(VarHandleTestByteArrayAsInt.java:229)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_1/483
jdk_lang_VarHandleTest_j9_1
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java
```
00:59:46  test VarHandleTestByteArrayAsInt.testAccess(" VarHandle [ALIGNED, LITTLE_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@e1d20a38): failure
00:59:46  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -3. Expected class java.lang.NullPointerException expected [true] but found [false]
00:59:46  	at org.testng.Assert.fail(Assert.java:99)
00:59:46  	at org.testng.Assert.failNotEquals(Assert.java:1037)
00:59:46  	at org.testng.Assert.assertTrue(Assert.java:45)
00:59:46  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
00:59:46  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
00:59:46  	at VarHandleTestByteArrayAsInt.testArrayNPE(VarHandleTestByteArrayAsInt.java:259)
00:59:46  	at VarHandleTestByteArrayAsInt.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsInt.java:175)
00:59:46  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
00:59:46  	at VarHandleTestByteArrayAsInt.testAccess(VarHandleTestByteArrayAsInt.java:229)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/293
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/366

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/380
jdk_lang_VarHandleTest_j9_1 
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java
```
07:03:03  test VarHandleTestByteArrayAsInt.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@de60d036): failure
07:03:03  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -3. Expected class java.lang.NullPointerException expected [true] but found [false]
07:03:03  	at org.testng.Assert.fail(Assert.java:99)
07:03:03  	at org.testng.Assert.failNotEquals(Assert.java:1037)
07:03:03  	at org.testng.Assert.assertTrue(Assert.java:45)
07:03:03  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
07:03:03  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
07:03:03  	at VarHandleTestByteArrayAsInt.testArrayNPE(VarHandleTestByteArrayAsInt.java:247)
07:03:03  	at VarHandleTestByteArrayAsInt.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsInt.java:175)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly_testList_3/11
jdk_lang_VarHandleTest_j9_1
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java
```
21:42:53  test VarHandleTestByteArrayAsInt.testAccess(" VarHandle [ALIGNED, LITTLE_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@e42ba3f5): failure [3ms]
21:42:53  java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -3. Expected class java.lang.NullPointerException expected [true] but found [false]
21:42:53  	at org.testng.Assert.fail(Assert.java:99)
21:42:53  	at org.testng.Assert.failNotEquals(Assert.java:1037)
21:42:53  	at org.testng.Assert.assertTrue(Assert.java:45)
21:42:53  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:148)
21:42:53  	at VarHandleBaseTest.checkNPE(VarHandleBaseTest.java:129)
21:42:53  	at VarHandleTestByteArrayAsInt.testArrayNPE(VarHandleTestByteArrayAsInt.java:247)
21:42:53  	at VarHandleTestByteArrayAsInt.lambda$accessTestCaseProvider$7(VarHandleTestByteArrayAsInt.java:175)
21:42:53  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
21:42:53  	at VarHandleTestByteArrayAsInt.testAccess(VarHandleTestByteArrayAsInt.java:229)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/388

**Comment by 0xdaryl** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_OMR_testList_1/418

```
[2026-07-14T12:19:38.581Z] test VarHandleTestByteArrayAsInt.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, BIG_ENDIAN, READ_WRITE] null array", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@94a904fc): failure [6ms]
[2026-07-14T12:19:38.581Z] java.lang.AssertionError: Incorrect throwable thrown, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length -3. Expected class java.lang.NullPointerException expected [true] but found [false]
```
