### ISSUE TITLE
IllegalStateException: Flight Recorder is not supported on this VM

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20166]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/208
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/208

java/lang/Thread/virtual/JfrEvents.java
java/lang/Thread/ThreadSleepEvent.java

```
20:11:23  java.lang.IllegalStateException: Flight Recorder is not supported on this VM
20:11:23  	at jdk.jfr/jdk.jfr.internal.JVMSupport.ensureWithIllegalStateException(JVMSupport.java:77)
20:11:23  	at jdk.jfr/jdk.jfr.FlightRecorder.getFlightRecorder(FlightRecorder.java:168)
20:11:23  	at jdk.jfr/jdk.jfr.Recording.<init>(Recording.java:107)
20:11:23  	at jdk.jfr/jdk.jfr.Recording.<init>(Recording.java:131)
20:11:23  	at JfrEvents.testVirtualThreadSubmitFailed(JfrEvents.java:198)
```

**Comment by pshipton** [comment]
@tajila

**Comment by tajila** [comment]
@thallium Can you please open excludes for these tests

**Comment by thallium** [comment]
Opened PR https://github.com/adoptium/aqa-tests/pull/5608

**Comment by pshipton** [comment]
The tests are failing in jdk23 0.48 testing.
Created https://github.com/adoptium/aqa-tests/pull/5704 against v1.0.4 for the 0.48 release.

**Comment by JasonFengJ9** [comment]
Run disabled the test with [the latest build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49695/consoleFull)
```
02:38:43  openjdk version "24-internal" 2025-03-18
02:38:43  OpenJDK Runtime Environment (build 24-internal-adhoc.jenkins.BuildJDK24aarch64linuxPersonal)
02:38:43  Eclipse OpenJ9 VM (build master-5981f9b4b09, JRE 24 Linux aarch64-64-Bit Compressed References 20250416_41 (JIT enabled, AOT enabled)
02:38:43  OpenJ9   - 5981f9b4b09
02:38:43  OMR      - 91436501b49
02:38:43  JCL      - 6d3cea7c4a9 based on jdk-24+36)

02:40:09  Running test jdk_lang_0 ...
02:40:09  ===============================================
02:40:09  jdk_lang_0 Start Time: Thu Apr 17 06:40:09 2025 Epoch Time (ms): 1744872009527
02:40:09  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
02:40:09  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Xverbosegclog 

03:00:39  TEST: java/lang/Thread/virtual/JfrEvents.java

03:00:39  STARTED    JfrEvents::testVirtualThreadSubmitFailed 'testVirtualThreadSubmitFailed()'
03:00:39  java.lang.IllegalStateException: Flight Recorder is not supported on this VM
03:00:39  	at jdk.jfr/jdk.jfr.internal.JVMSupport.ensureWithIllegalStateException(JVMSupport.java:90)
03:00:39  	at jdk.jfr/jdk.jfr.FlightRecorder.getFlightRecorder(FlightRecorder.java:161)
03:00:39  	at jdk.jfr/jdk.jfr.Recording.<init>(Recording.java:105)
03:00:39  	at jdk.jfr/jdk.jfr.Recording.<init>(Recording.java:126)
03:00:39  	at JfrEvents.testVirtualThreadSubmitFailed(JfrEvents.java:362)
03:00:39  	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
03:00:39  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
03:00:39  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
03:00:39  FAILED     JfrEvents::testVirtualThreadSubmitFailed 'testVirtualThreadSubmitFailed()'
```
