### ISSUE TITLE
java.lang.LinkageError: loading constraint violation in ValueTypeTests

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#20189]
Failed in Valhalla nightly [build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_0/1186/consoleFull):

```
21:56:22  FAILED: testDefaultValues
21:56:22  java.lang.IllegalAccessException: no such method: Triangle2D.makeDefaultValue()Triangle2D/invokeStatic
21:56:22  	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:930)
21:56:22  	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1013)
21:56:22  	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3761)
21:56:22  	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2654)
21:56:22  	at org.openj9.test.lworld.ValueTypeTests.testDefaultValues(ValueTypeTests.java:1832)
21:56:22  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
21:56:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:579)
21:56:22  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
21:56:22  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
21:56:22  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
21:56:22  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
21:56:22  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
21:56:22  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
21:56:22  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
21:56:22  	at org.testng.TestRunner.run(TestRunner.java:505)
21:56:22  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
21:56:22  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
21:56:22  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
21:56:22  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
21:56:22  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
21:56:22  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
21:56:22  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
21:56:22  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
21:56:22  	at org.testng.TestNG.runSuites(TestNG.java:1049)
21:56:22  	at org.testng.TestNG.run(TestNG.java:1017)
21:56:22  	at org.testng.TestNG.privateMain(TestNG.java:1354)
21:56:22  	at org.testng.TestNG.main(TestNG.java:1323)
21:56:22  Caused by: java.lang.LinkageError: loading constraint violation when resolving method "Triangle2D.makeDefaultValue()LTriangle2D;" : loader "jdk/internal/loader/ClassLoaders$AppClassLoader@a1eb1792" of class "org/openj9/test/lworld/ValueTypeTests" and loader "org/openj9/test/lworld/ValueTypeGenerator@176a3bf" of class "Triangle2D" have different types for the method signature
21:56:22  	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
21:56:22  	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:981)
21:56:22  	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1010)
21:56:22  	... 25 more
```

This failure is intermittent.

50x [grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/43397/) all passed.

**Comment by hangshao0** [comment]
FYI @theresa-m

**Comment by hangshao0** [comment]
Failed again [here](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_0/1199/consoleFull):

```
21:53:25  FAILED: testDefaultValues
21:53:25  java.lang.IllegalAccessException: no such method: Triangle2D.makeDefaultValue()Triangle2D/invokeStatic
21:53:25  	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:930)
21:53:25  	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1013)
21:53:25  	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3761)
21:53:25  	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2654)
21:53:25  	at org.openj9.test.lworld.ValueTypeTests.testDefaultValues(ValueTypeTests.java:1832)
21:53:25  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
21:53:25  	at java.base/java.lang.reflect.Method.invoke(Method.java:579)
21:53:25  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
21:53:25  	at java.base/java.lang.ThreadLocal$ThreadLocalMap.set(ThreadLocal.java:545)
21:53:25  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
21:53:25  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
21:53:25  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
21:53:25  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
21:53:25  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
21:53:25  	at org.testng.TestRunner.run(TestRunner.java:505)
21:53:25  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
21:53:25  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
21:53:25  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
21:53:25  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
21:53:25  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
21:53:25  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
21:53:25  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
21:53:25  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
21:53:25  	at org.testng.TestNG.runSuites(TestNG.java:1049)
21:53:25  	at org.testng.TestNG.run(TestNG.java:1017)
21:53:25  	at org.testng.TestNG.privateMain(TestNG.java:1354)
21:53:25  	at org.testng.TestNG.main(TestNG.java:1323)
21:53:25  Caused by: java.lang.LinkageError: loading constraint violation when resolving method "Triangle2D.makeDefaultValue()LTriangle2D;" : loader "jdk/internal/loader/ClassLoaders$AppClassLoader@4868a333" of class "org/openj9/test/lworld/ValueTypeTests" and loader "org/openj9/test/lworld/ValueTypeGenerator@314cb77" of class "Triangle2D" have different types for the method signature
21:53:25  	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
21:53:25  	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:981)
21:53:25  	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1010)
21:53:25  	... 25 more
```

**Comment by theresa-m** [comment]
Could this be similar to https://github.com/eclipse-openj9/openj9/issues/11924 ? @babsingh

**Comment by babsingh** [comment]
No, they aren't similar. The old one failed consistently and a fix was pushed for it. This one is intermittent, and two different method signatures are found for `Triangle2D.makeDefaultValue()LTriangle2D` at some point. Further investigation will be needed to figure out why two different method signatures are intermittently found. This might be related SCC/AOT.

**Comment by a7ehuo** [comment]
I just ran into this issue in an internal [Test_openjdkvalhalla_j9_sanity.functional_x86-64_linux_valhalla](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkvalhalla_j9_sanity.functional_x86-64_linux_valhalla_Personal_testList_1/193/consoleText). 

I tried to run `ValueTypeTests_2` locally `80x`, all passed. 

```
2024-10-22T14:40:05.031Z] FAILED: testDefaultValues
[2024-10-22T14:40:05.031Z] java.lang.IllegalAccessException: no such method: Triangle2D.makeDefaultValue()Triangle2D/invokeStatic
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:930)
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1013)
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3761)
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2654)
[2024-10-22T14:40:05.031Z] 	at org.openj9.test.lworld.ValueTypeTests.testDefaultValues(ValueTypeTests.java:1832)
[2024-10-22T14:40:05.031Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:579)
[2024-10-22T14:40:05.031Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2024-10-22T14:40:05.031Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2024-10-22T14:40:05.031Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2024-10-22T14:40:05.031Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2024-10-22T14:40:05.031Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2024-10-22T14:40:05.031Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2024-10-22T14:40:05.031Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2024-10-22T14:40:05.031Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2024-10-22T14:40:05.031Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2024-10-22T14:40:05.031Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2024-10-22T14:40:05.031Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2024-10-22T14:40:05.031Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2024-10-22T14:40:05.031Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2024-10-22T14:40:05.031Z] Caused by: java.lang.LinkageError: loading constraint violation when resolving method "Triangle2D.makeDefaultValue()LTriangle2D;" : loader "jdk/internal/loader/ClassLoaders$AppClassLoader@d07921a6" of class "org/openj9/test/lworld/ValueTypeTests" and loader "org/openj9/test/lworld/ValueTypeGenerator@7fc9ddc" of class "Triangle2D" have different types for the method signature
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:981)
[2024-10-22T14:40:05.031Z] 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1010)
[2024-10-22T14:40:05.031Z] 	... 25 more
```

**Comment by a7ehuo** [comment]
Hit is failure again with internal test: [Test_openjdkValhalla_j9_sanity.functional_aarch64_linux_valhalla](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_sanity.functional_aarch64_linux_valhalla_Personal_testList_1/36/consoleText)
```
2024-10-28T20:00:47.979Z] FAILED: testDefaultValues
[2024-10-28T20:00:47.979Z] java.lang.IllegalAccessException: no such method: Triangle2D.makeDefaultValue()Triangle2D/invokeStatic
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:930)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1013)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3761)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2654)
[2024-10-28T20:00:47.979Z] 	at org.openj9.test.lworld.ValueTypeTests.testDefaultValues(ValueTypeTests.java:1832)
[2024-10-28T20:00:47.979Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:579)
[2024-10-28T20:00:47.979Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2024-10-28T20:00:47.979Z] 	at <unknown class>.<unknown method>(Unknown Source)
[2024-10-28T20:00:47.979Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2024-10-28T20:00:47.979Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2024-10-28T20:00:47.979Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2024-10-28T20:00:47.979Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2024-10-28T20:00:47.979Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2024-10-28T20:00:47.979Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2024-10-28T20:00:47.979Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2024-10-28T20:00:47.979Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2024-10-28T20:00:47.979Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2024-10-28T20:00:47.979Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2024-10-28T20:00:47.979Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2024-10-28T20:00:47.979Z] Caused by: java.lang.LinkageError: loading constraint violation when resolving method "Triangle2D.makeDefaultValue()LTriangle2D;" : loader "jdk/internal/loader/ClassLoaders$AppClassLoader@a95f0f8" of class "org/openj9/test/lworld/ValueTypeTests" and loader "org/openj9/test/lworld/ValueTypeGenerator@80c34a7" of class "Triangle2D" have different types for the method signature
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:981)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1010)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3761)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2654)
[2024-10-28T20:00:47.979Z] 	at org.openj9.test.lworld.ValueTypeTests.testDefaultValues(ValueTypeTests.java:1832)
[2024-10-28T20:00:47.979Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-10-28T20:00:47.979Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:579)
[2024-10-28T20:00:47.979Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2024-10-28T20:00:47.979Z] 	at <unknown class>.<unknown method>(Unknown Source)
[2024-10-28T20:00:47.979Z] 	... 18 more
[2024-10-28T20:00:47.979Z] 
[2024-10-28T20:00:47.979Z] 
[2024-10-28T20:00:47.979Z] ===============================================
[2024-10-28T20:00:47.979Z]     ValueTypeTests
[2024-10-28T20:00:47.979Z]     Tests run: 139, Failures: 1, Skips: 0
[2024-10-28T20:00:47.979Z] ===============================================
[2024-10-28T20:00:47.979Z] 
[2024-10-28T20:00:47.979Z] 
[2024-10-28T20:00:47.979Z] ===============================================
[2024-10-28T20:00:47.979Z] Valhalla suite
[2024-10-28T20:00:47.979Z] Total tests run: 139, Failures: 1, Skips: 0
[2024-10-28T20:00:47.979Z] ===============================================
[2024-10-28T20:00:47.979Z] 
[2024-10-28T20:00:54.129Z] -----------------------------------
[2024-10-28T20:00:54.129Z] ValueTypeTestsJIT_5_FAILED
[2024-10-28T20:00:54.129Z] -----------------------------------
[2024-10-28T20:00:54.129Z] 
```

**Comment by hangshao0** [comment]
```
02:55:57.615640499  0x00007fdaf00c3c00 j9bcverify(j9vm).40 Event       Allocated new class loading constraint 0x7fdaf0439c90 for AssortedValueWithLongAlignment in 0x7fdaf009b420
02:55:57.615761602  0x00007fdaf00c3c00 j9bcverify(j9vm).40 Event       Allocated new class loading constraint 0x7fdaf0439cd8 for AssortedRefWithLongAlignment in 0x7fdaf009b420
02:55:57.615803302  0x00007fdaf00c3c00 j9bcverify(j9vm).107 Entry      >j9bcv_verifyBytecodes - AssortedRefWithLongAlignment 
02:55:57.615851317  0x00007fdaf00c3c00 j9bcverify(j9vm).111 Exit       <j9bcv_verifyBytecodes - returning 0
02:55:57.616175828  0x00007fdaf00c3c00 j9bcverify(j9vm).40 Event       Allocated new class loading constraint 0x7fdaf0439c48 for FlattenedLine2D in 0x7fdaf009b420
02:55:57.616237511  0x00007fdaf00c3c00 j9vm.408            Event       processMethod: class loader constraint violated when resolving a class in the signature for method (0x7fdaf0abd040) in loader(0x7fdaf009b420) and loader(0x7fdaf009b538)
02:55:57.616807498  0x00007fdaf00c3c00 j9vm.302            Entry      >setCurrentExceptionUTF exceptionNumber=47 detailUTF=loading constraint violation when resolving method "Triangle2D.makeDefaultValue()LTriangle2D;" : loader "jdk/internal/loader/ClassLoaders$AppClassLoader@25329361" of class "org/openj9/test/lworld/ValueTypeTests" and loader "org/openj9/test/lworld/ValueTypeGenerator@bac7be23" of class "Triangle2D" have different types for the method signature
02:55:57.616814491  0x00007fdaf00c3c00 j9vm.294            Entry      >setCurrentException index=47 constructorIndex=0 detailMessage=0x7fdaefe51500
02:55:57.616816373  0x00007fdaf00c3c00 j9vm.10             Entry      >internalSendExceptionConstructor
02:55:57.616821522  0x00007fdaf00c3c00 j9vm.682            Entry      >WalkStackFrames - walkThread=0x7fdaf00c3c00 flags=0x1c0c0100 sp=0x7fdaf0228150 a0=0x7fdaf0228178 pc=0x3 literals=0x0 els=0x7fdaf8011a70 j2i=0x0
02:55:57.616829442  0x00007fdaf00c3c00 j9vm.683            Exit       <WalkStackFrames - walkThread=0x7fdaf00c3c00, rc=0
02:55:57.616831035  0x00007fdaf00c3c00 j9vm.11             Exit       <internalSendExceptionConstructor
```

The tracepoint j9vm.40 shows the name is "FlattenedLine2D", however the name in the classloading constraint `0x7fdaf0439c48` is "Triangle2D;":
```
!J9ClassLoadingConstraint 0x7fdaf0439c48
J9ClassLoadingConstraint at 0x7fdaf0439c48 {
  Fields for J9ClassLoadingConstraint:
        0x0: struct J9ClassLoader* classLoader = !j9classloader 0x00007FDAF009B420
        0x8: U8* name = !j9x 0x00007FDAF8012045 // "Triangle2D;"
        0x10: UDATA nameLength = 0x000000000000000F (15)
        0x18: struct J9Class* clazz = !j9class 0x00007FDAF0A62C00 // FlattenedLine2D
        0x20: struct J9ClassLoadingConstraint* linkNext = !j9classloadingconstraint 0x00007FDAF0439C48
        0x28: struct J9ClassLoadingConstraint* linkPrevious = !j9classloadingconstraint 0x00007FDAF0439C48
        0x30: UDATA freeName = 0x0000000000000000 (0)
}
```
The nameLength 15 matches the size of "FlattenedLine2D" and the J9Class is also "FlattenedLine2D". So I believe `0x8: U8* name = !j9x 0x00007FDAF8012045 // "Triangle2D;"` is wrong.

The corresponding code is here:

 https://github.com/eclipse-openj9/openj9/blob/2bfcbe8d588f6872904e29a899442222998bfa6f/runtime/bcverify/clconstraints.c#L226-L251

**Comment by theresa-m** [comment]
@hangshao0 the call to `registerClassLoadingConstraint` I see in java_lang_invoke_MethodHandleNatives.cpp is already setting copyName to true through the last argument. Is there another case I'm missing?

https://github.com/eclipse-openj9/openj9/blob/81bdf47395389b14c4e3ceb975ad48c67d59c16e/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp#L1319

**Comment by hangshao0** [comment]
>  Is there another case I'm missing?

There is another case to resolve a method, the call stack is:
```
Java_java_lang_invoke_MethodHandleNatives_resolve()
lookupMethod()
javaLookupMethodImpl()
processMethod()
j9bcv_checkClassLoadingConstraintsForSignature()
j9bcv_checkClassLoadingConstraintForName()
```

**Comment by theresa-m** [comment]
I opened https://github.com/eclipse-openj9/openj9/pull/20700 as a fix for this. The changes from https://github.com/eclipse-openj9/openj9/pull/20429 should be reverted before closing this issue but I suggest keeping this open for a while to confirm the error is truly gone.
