### ISSUE TITLE
Value Types: java.lang.ArrayStoreException with null-restricted array with -Xint

### ISSUE THREAD

**Issue by a7ehuo** [eclipse-openj9/openj9#20223]
I'm running the following test with the latest `openj9-openjdk-jdk.valuetypes` with `-Xint`

```java
public class TestNullRestrictedArray {

	public static int ARRAY_SIZE = 100;

	static private void test1(int x) {
	   SomeValueClass1[] array1 = (SomeValueClass1[])ValueClass.newArrayInstance(NullRestrictedCheckedType.of(SomeValueClass1.class), ARRAY_SIZE);
	   SomeValueClass1[] array2 = new SomeValueClass1[ARRAY_SIZE];

		for (int i=0; i < ARRAY_SIZE; i++) {
			array1[i] = new SomeValueClass1(i*x);
			array2[i] = new SomeValueClass1(i*x);
		}

		System.arraycopy(array2, 0, array1, 0, ARRAY_SIZE);
	}

	static private void test2(int x) {
	   SomeValueClass1[] array1 = (SomeValueClass1[])ValueClass.newArrayInstance(NullRestrictedCheckedType.of(SomeValueClass1.class), ARRAY_SIZE);
	   SomeValueClass1[] array2 = new SomeValueClass1[ARRAY_SIZE];

		for (int i=0; i < ARRAY_SIZE; i++) {
			array1[i] = new SomeValueClass1(i*x);
			array2[i] = new SomeValueClass1(i*x);
		}

		System.arraycopy(array1, 0, array2, 0, ARRAY_SIZE);
	}

   public static void main(String[] args) {
     test1(1);
     test2(1);
   }
}
```

` java.lang.ArrayStoreException` happens with both `test1` and `test2`. These two tests copy between a null-restricted array and a regular array with array flattening enabled. 

```
java --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.value=ALL-UNNAMED --add-exports java.base/jdk.internal.vm.annotation=ALL-UNNAMED --enable-preview -XX:ValueTypeFlatteningThreshold=99999 -XX:+EnableArrayFlattening -Xint TestNullRestrictedArray 
Exception in thread "main" java.lang.ArrayStoreException
	at java.base/java.lang.System.arraycopy(Native Method)
	at TestNullRestrictedArray.test1(TestNullRestrictedArray.java:32)
	at TestNullRestrictedArray.main(TestNullRestrictedArray.java:54)
```

```
java --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.value=ALL-UNNAMED --add-exports java.base/jdk.internal.vm.annotation=ALL-UNNAMED --enable-preview -XX:ValueTypeFlatteningThreshold=99999 -XX:+EnableArrayFlattening -Xint TestNullRestrictedArray 
Exception in thread "main" java.lang.ArrayStoreException
	at java.base/java.lang.System.arraycopy(Native Method)
	at TestNullRestrictedArray.test2(TestNullRestrictedArray.java:46)
	at TestNullRestrictedArray.main(TestNullRestrictedArray.java:56)
```

**Comment by a7ehuo** [comment]
@hangshao0 @theresa-m If I'm not mistaken, I'm under the impression that null restricted array should work with the latest code with the interpreter. Could you take a look? Thank you! 

@hzongaro fyi

**Comment by hangshao0** [comment]
Once fixed, the test cases here should be added into https://github.com/eclipse-openj9/openj9/blob/master/test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeSystemArraycopyTests.java.

**Comment by hzongaro** [comment]
In testing OpenJ9 pull request #20291 and OMR pull request eclipse/omr#7477, I removed the [`<disables>` element from `test/functional/Valhalla/playlist.xml` for `ValueTypeArrayTestsJIT`](https://github.com/eclipse-openj9/openj9/blob/ea25376c8b630f8abe5be1ecd4f86b8501c72e63/test/functional/Valhalla/playlist.xml#L138-L142).  I encountered a failure with `_ValueTypeArrayTestsJIT_3` that I was able to reproduce with this reduced test:

```
import jdk.internal.vm.annotation.ImplicitlyConstructible;

public class Foo {
        private Foo() {}
  
        interface SomeInterface1WithSingleImplementer {}
  
        @ImplicitlyConstructible
        static value class SomePrimitiveClassImplIf implements SomeInterface1WithSingleImplementer {
                public int d;
                public long l;
  
                SomePrimitiveClassImplIf(int val1, long val2) {
                        this.d = val1;
                        this.l = val2;
                }
        }
  
        static class SomeClassHolder {
                public static int ARRAY_LENGTH = 10;
                public SomeInterface1WithSingleImplementer[] data_1;
  
                SomeClassHolder() {
                        data_1 = new SomePrimitiveClassImplIf[ARRAY_LENGTH];
                        for (int i = 0; i < ARRAY_LENGTH; i++) {
                                data_1[i] = new SomePrimitiveClassImplIf((int)i, (long)i);
                        }
                }
        }
  
        public static final void main(String[] args) {
                SomeClassHolder h = new SomeClassHolder();
                h = new SomeClassHolder();
                for (int i = 0; i < SomeClassHolder.ARRAY_LENGTH; i++) {
                        System.out.println(h.data_1[i] == new SomePrimitiveClassImplIf((int)i, (long)i));
                        System.out.println(Integer.toHexString(((SomePrimitiveClassImplIf) h.data_1[i]).d));
                        System.out.println(Long.toHexString(((SomePrimitiveClassImplIf) h.data_1[i]).l));
                }
        }
}
```

```
$ java --enable-preview --add-exports java.base/jdk.internal.vm.annotation=ALL-UNNAMED -Xjit:count=1,disableAsyncCompilation,optLevel=cold,{Foo?SomeClassHolder*}\(traceFull,log=/tmp/holder.log\) -XX:ValueTypeFlatteningThreshold=99999 -XX:+EnableArrayFlattening -cp /tmp Foo
```

The output that results begins

```
false
ffea2150
ffea2170ffea2160
false
ffea2190
ffea21b0ffea21a0
false
ffea21d0
ffea21e0
false
0 
0 
...
```
but the expected output was:
```
true
0
0
true
1
1
true
2
2
true
3 
3 
true
4 
4 
...
```

What I was wondering was, is the array that's stored in `data_1` being flattened even though it's not non-nullable?  I believe the JIT-compiled code for the `SomeClassHolder` constructor is storing references to the value instances it's constructing into the `SomePrimitiveClassImplIf` array that it's creating, but it looks like the JVM thinks the array is flattened.

If so, is the array expected to be flattened?  If it's not expected, is that another instance of the problem that @a7ehuo reported above, or is this a distinct problem, in which case I will open a separate issue?

**Comment by a7ehuo** [comment]
@hzongaro Does the above issue happen with https://github.com/eclipse-openj9/openj9/pull/20250 and also my change https://github.com/eclipse/omr/pull/7452 and https://github.com/eclipse-openj9/openj9/pull/20112?

**Comment by hangshao0** [comment]
Re https://github.com/eclipse-openj9/openj9/issues/20223#issuecomment-2389726220

It looks like the same problem https://github.com/eclipse-openj9/openj9/pull/20250 is addressing.
