### ISSUE TITLE
Crash in j9shr_shutdown

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#20227]
```
Testing: Sealed.failure2
Test start time: 2024/09/24 13:19:05 Eastern Standard Time
Running command: w:\builds\bld_78538/sdk/wi3280\jre\bin\java.exe  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs    -Xshareclasses:persistent,controlDir=.,name=SignedSealed3 -Xscmx5M -cp .\SignedSealed\B2.jar;.\SignedSealed\AB.jar jnurlcldr.shared.signedsealed.A_Main
Time spent starting: 16 milliseconds
Time spent executing: 1938 milliseconds
Test result: FAILED
 [OUT] Result=3
 [ERR] Exception in thread "main" java.lang.SecurityException: sealing violation: package jnurlcldr.shared.signedsealed is sealed
 [ERR] 	at java.net.URLClassLoader.getAndVerifyPackage(URLClassLoader.java:635)
 [ERR] 	at java.net.URLClassLoader.definePackageInternal(URLClassLoader.java:655)
 [ERR] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:690)
 [ERR] 	at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
 [ERR] 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1187)
 [ERR] 	at java.security.AccessController.doPrivileged(AccessController.java:782)
 [ERR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:605)
 [ERR] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:950)
 [ERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:895)
 [ERR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:353)
 [ERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:878)
 [ERR] 	at jnurlcldr.shared.signedsealed.B_Dummy.getResult(B_Dummy.java:26)
 [ERR] 	at jnurlcldr.shared.signedsealed.A_Data.getResult(A_Data.java:26)
 [ERR] 	at jnurlcldr.shared.signedsealed.A_Main.main(A_Main.java:31)
 [ERR] Unhandled exception
 [ERR] Type=Segmentation error vmState=0x00000000
 [ERR] J9Generic_Signal_Number=00000004 ExceptionCode=c0000005 ExceptionAddress=71E04A5A ContextFlags=0001007f
 [ERR] Handler1=7536FB50 Handler2=75517CA0 InaccessibleWriteAddress=22B6DB60
 [ERR] EDI=01400648 ESI=225E0F38 EAX=22B6DA30 EBX=22AB12D0
 [ERR] ECX=FFFFFFFF EDX=0110C000
 [ERR] EIP=71E04A5A ESP=01B7F000 EBP=22D99F28 EFLAGS=00210246
 [ERR] GS=002B FS=0053 ES=002B DS=002B
 [ERR] Module=w:\builds\bld_78538\sdk\wi3280\jre\bin\default\j9shr29.dll
 [ERR] Module_base_address=71E00000 Offset_in_DLL=00004a5a
 [ERR] Target=2_90_20240923_78538 (Windows 10 10.0 build 19045)
 [ERR] CPU=x86 (4 logical CPUs) (0x1fff78000 RAM)
 [ERR] ----------- Stack Backtrace -----------
 [ERR] j9shr_shutdown+0x28a (shrinit.cpp:4337, 0x71E04A5A [j9shr29+0x4a5a])
 [ERR] J9VMDllMain+0x96a (shrclssup.c:505, 0x71E0196A [j9shr29+0x196a])
 [ERR] runShutdownStageJvmtiFirst+0x176 (jvminit.c:4412, 0x753884F6 [j9vm29+0x984f6])
 [ERR] freeJavaVM+0x462 (jvminit.c:797, 0x7537F3D2 [j9vm29+0x8f3d2])
 [ERR] protectedDestroyJavaVM+0x410 (jniinv.c:486, 0x7537B050 [j9vm29+0x8b050])
 [ERR] omrsig_protect+0x4f (omrsignal.c:166, 0x75518CEF [j9prt29+0x18cef])
 [ERR] DestroyJavaVM+0x240 (jniinv.c:549, 0x75379F10 [j9vm29+0x89f10])
 [ERR] DestroyJavaVM+0x1c (jvm.c:846, 0x7558ACEC [jvm+0xacec])
 [ERR] (0x00F62679 [java+0x2679])
 [ERR] RtlAllocateHeap+0x2ecb (0x77B68DBB [ntdll+0x48dbb])
 [ERR] (0x00F7826C [java+0x1826c])
 [ERR] BaseThreadInitThunk+0x19 (0x7775FCC9 [KERNEL32+0x1fcc9])
 [ERR] RtlGetAppContainerNamedObjectPath+0x11e (0x77B880CE [ntdll+0x680ce])
 [ERR] RtlGetAppContainerNamedObjectPath+0xee (0x77B8809E [ntdll+0x6809e])
 [ERR] ---------------------------------------
 [ERR] JVMDUMP039I Processing dump event "gpf", detail "" at 2024/09/24 13:19:07 - please wait.
 [ERR] JVMDUMP013I Processed dump event "gpf", detail "".
>> Success condition was found: [Output match: SecurityException]
>> Failure condition was found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Error:]
```

http://vmfarm.rtp.raleigh.ibm.com/old/build_info.php?build_id=78590

**Comment by tajila** [comment]
@hangshao0 Please take a look

**Comment by pshipton** [comment]
The JVM was built yesterday so it will be missing https://github.com/eclipse-openj9/openj9/pull/20196
