### ISSUE TITLE
OpenJDK java/util/Arrays/Sorting Array is not sorted

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20234]
jdk_util_0
java/util/Arrays/Sorting.java

```
07:16:33  Array is not sorted at 1400-th position: 1453.0 and 1402.0
07:16:33  
07:16:33  java.lang.RuntimeException: Test failed
07:16:33  	at Sorting.fail(Sorting.java:644)
07:16:33  	at Sorting.checkSorted(Sorting.java:892)
07:16:33  	at Sorting.checkSorted(Sorting.java:841)
07:16:33  	at Sorting.checkWithCheckSum(Sorting.java:638)
07:16:33  	at Sorting.testWithCheckSum(Sorting.java:438)
07:16:33  	at Sorting.testBasic(Sorting.java:109)
07:16:33  	at Sorting.testCore(Sorting.java:122)
07:16:33  	at Sorting.testAll(Sorting.java:140)
07:16:33  	at Sorting.testAll(Sorting.java:135)
07:16:33  	at Sorting.main(Sorting.java:85)
```

**Comment by pshipton** [comment]
250 iterations of the single test didn't recreate it.
Try to recreate running java_util in 6x x 3 grinder https://openj9-jenkins.osuosl.org/job/Grinder/3837/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_mac_Nightly_testList_2/89 - [mac13-x86-5](https://openj9-jenkins.osuosl.org/computer/mac13-x86-5)
jdk_util_1
java/util/Arrays/Sorting.java
`Array is not sorted at 6801-th position: 979306791 and 748985027`
