### ISSUE TITLE
cmdLineTester_criu_jitserverAcrossCheckpoint FileNotFoundException criu_jitserverAcrossCheckpoint.xml NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20243]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_aarch64_linux_Nightly_testList_1/762/
cmdLineTester_criu_jitserverAcrossCheckpoint_0
```
3:55:25  TESTING:
23:55:25  java.io.FileNotFoundException: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_aarch64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml (No such file or directory)
23:55:25  	at java.io.FileInputStream.open0(Native Method)
23:55:25  	at java.io.FileInputStream.open(FileInputStream.java:195)
23:55:25  	at java.io.FileInputStream.<init>(FileInputStream.java:138)
23:55:25  	at java.io.FileInputStream.<init>(FileInputStream.java:93)
23:55:25  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:455)
23:55:25  	at TestConfigParser.runTests(TestConfigParser.java:78)
23:55:25  	at MainTester.main(MainTester.java:106)
23:55:25  java.lang.NullPointerException
23:55:25  	at java.io.Reader.<init>(Reader.java:78)
23:55:25  	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
23:55:25  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:468)
23:55:25  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)
23:55:25  	at TestConfigParser.runTests(TestConfigParser.java:78)
23:55:25  	at MainTester.main(MainTester.java:106)
23:55:25  Exception in thread "main" java.lang.NullPointerException
23:55:25  	at MainTester.main(MainTester.java:107)
```

https://github.com/eclipse-openj9/openj9/compare/16ab797349b...ecab2f6c958
https://github.com/eclipse-openj9/openj9-omr/compare/611c142075f...9b3e65e264a

**Comment by pshipton** [comment]
Caused by https://github.com/eclipse-openj9/openj9/pull/20215
@annaibm @llxia

**Comment by pshipton** [comment]
Looking at https://trssrtp1.fyre.ibm.com/resultSummary?parentId=66f33e8380d85c3dab390bfb it's failing on a bunch of platforms, looks like all Linux.

**Comment by llxia** [comment]
> looks like all Linux.

yes, cmdLineTester_criu_jitserverAcrossCheckpoint only runs on linux.

I forgot that CRIU is not enabled on JDK8. @annaibm Please add the following to the test.
```
		<versions>
			<version>11+</version>
		</versions>
```

**Comment by llxia** [comment]
PR is delivered. Close this issue
