### ISSUE TITLE
DaaLoadTest_daa1 testIntrinsicPerformance addPackedDecimal: arrays first differed at element

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20258]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_special.system_ppc64le_linux_Release_testList_2/71
DaaLoadTest_daa1_special_5m_8 `-Xgcpolicy:gencon -Xshareclasses -Xjit -Xnocompressedrefs`
```
22:48:54  DLT testFailure: testIntrinsicPerformance(net.openj9.test.arithmetics.TestPerformance): addPackedDecimal: arrays first differed at element [6]; expected:<-111> but was:<36>
22:48:54  DLT addPackedDecimal: arrays first differed at element [6]; expected:<-111> but was:<36>
22:48:54  DLT 	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
22:48:54  DLT 	at org.junit.Assert.internalArrayEquals(Assert.java:532)
22:48:54  DLT 	at org.junit.Assert.assertArrayEquals(Assert.java:341)
22:48:54  DLT 	at net.openj9.test.arithmetics.TestPerformance.verify(TestPerformance.java:465)
22:48:54  DLT 	at net.openj9.test.arithmetics.TestPerformance.testAdd(TestPerformance.java:119)
22:48:54  DLT 	at net.openj9.test.arithmetics.TestPerformance.testIntrinsicPerformance(TestPerformance.java:76)
```

**Comment by pshipton** [comment]
12x x 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/3853/

**Comment by pshipton** [comment]
@hzongaro pls check if this needs to be resolved in 0.48 or moved out.

**Comment by hzongaro** [comment]
@dylanjtuttle, may I ask you to take a look at this?  It might be good to determine when this problem first appeared, as well as figuring out what might be going wrong.

**Comment by hzongaro** [comment]
@dylanjtuttle - FYI that @IBMJimmyk is also looking at https://github.com/eclipse-openj9/openj9/issues/20263#issuecomment-2386426060.  There are failures for this test with several distinct symptoms.  It's not clear whether they represent one problem or many.

**Comment by dylanjtuttle** [comment]
So far I've only been able to reproduce the failure in #20263. I am running the test on ppc64le Ubuntu 20.04 on JDK 11. I will continue trying, and may try Ubuntu 22 if I continue to have problems.

**Comment by pshipton** [comment]
FYI the original failure was found on the 0.48 build.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_ppc64le_linux_Personal_testList_4/93 - [ubu22-ppc64le-2](https://openj9-jenkins.osuosl.org/computer/ubu22-ppc64le-2)
DaaLoadTest_daa1_special_5m_9 `-Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs`
```
10:13:59  DLT testFailure: testIntrinsicPerformance(net.openj9.test.arithmetics.TestPerformance): Array access index out of bounds. convertIntegerToPackedDecimal is trying to access packedDecimal[0] to packedDecimal[5],  but valid indices are from 0 to -1.
10:13:59  DLT java.lang.ArrayIndexOutOfBoundsException: Array access index out of bounds. convertIntegerToPackedDecimal is trying to access packedDecimal[0] to packedDecimal[5],  but valid indices are from 0 to -1.
10:13:59  DLT 	at openj9.dataaccess/com.ibm.dataaccess.DecimalData.convertIntegerToPackedDecimal(DecimalData.java:277)
10:13:59  DLT 	at net.openj9.test.PDMoveShifts.TestShiftsAndConvert.testShiftRight(TestShiftsAndConvert.java:3307)
10:13:59  DLT 	at net.openj9.test.PDMoveShifts.TestShiftsAndConvert.testShiftRightLowerDstPrec(TestShiftsAndConvert.java:3360)
```

**Comment by dylanjtuttle** [comment]
I've run nearly 100 iterations of `DaaLoadTest_daa1_special_5m_8` on Grinder with the 0.48 build on ppc64le, but I still can't seem to reproduce this failure. It's clearly possible, as shown by the links provided by Peter, so I need to figure out what I'm doing wrong. I want to try to and track down which commit is responsible for introducing the failure, but obviously I need to find a way to reproduce it with enough regularity that I would be able to tell at what commit it started appearing.

Given my lack of progress on this issue so far, it might be best to move this back to the 0.49 release.

**Comment by vij-singh** [comment]
Given the other DAA on P issues have been resolved (like #20263), does this one still occur or has it been resolved now?

**Comment by dylanjtuttle** [comment]
I've got a final Grinder run going atm with the new changes, I'll report the results back here when done.

**Comment by dylanjtuttle** [comment]
After some difficulties that required re-running the last grinder build, I can confirm that this symptom did not appear in [500 iterations](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44261/). Oddly enough, I did get one instance of the segmentation error failure, which I thought wouldn't have been possible. The SDK used for the Grinder run was created with [this](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/24415/) job, which used the head of the 0.48 branches for OpenJ9 and OMR, so as long as the changes which fixed the other symptoms made it into the 0.48 branches by 10:24 AM EST on October 15th, they should have been included in this Grinder run.

**Comment by hzongaro** [comment]
Assuming we haven't seen any recent instances of this problem, I'm going to move this to the "Future" release.  We can move to back to a planned release if the problem recurs.
