### ISSUE TITLE
J9vmTest threadinterrupt.scenario3bTest wait should have been interrupted

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20269]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/889 - [rh7-390-4](https://openj9-jenkins.osuosl.org/computer/rh7-390-4)
J9vmTest_3
```
00:26:09  +++ j9vm.test.threadinterrupt.scenario3bTest: +++
00:26:09  command: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/bin/java  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m -Xbootclasspath:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/jre/lib/s390x/default/jclSC180/vm.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/jre/lib/se-service.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/jre/lib/rt.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/jre/lib/resources.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/jre/lib/jsse.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/jre/lib/charsets.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/jre/lib/jce.jar -classpath /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/../../testDependency/lib/asm-all.jar j9vm.test.threadinterrupt.scenario3bTest 
00:26:09  
00:26:11  Exception in thread "main" java.lang.Error: wait should have been interrupted
00:26:11  	at j9vm.test.threadinterrupt.scenario3bTest.Run(scenario3bTest.java:43)
00:26:11  	at j9vm.test.threadinterrupt.scenario3bTest.main(scenario3bTest.java:27)
00:26:11  main  waiting
00:26:11  main  done waiting
00:26:11  inter syncing on a
00:26:11  inter synced on a
00:26:11  inter interrupting main
00:26:11  inter done interrupting main
00:26:11  inter sleeping for 5 seconds
00:26:17  inter releasing a
00:26:17  inter released a
00:26:17  non-zero exit value: 1
00:26:17  *** Test FAILED *** (j9vm.test.threadinterrupt.scenario3bTest)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_1/67
J9vmTest_0
```
06:37:05  +++ j9vm.test.threadinterrupt.scenario3bTest: +++
06:37:05  command: /home/jenkins/workspace/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_1/jdkbinary/j2sdk-image/bin/java  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m -classpath /home/jenkins/workspace/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk24_j9_sanity.functional_s390x_linux_Nightly_testList_1/../../testDependency/lib/asm-all.jar j9vm.test.threadinterrupt.scenario3bTest 
06:37:05  
06:37:06  main  waiting
06:37:06  main  done waiting
06:37:06  Exception in thread "main" java.lang.Error: wait should have been interrupted
06:37:06  	at j9vm.test.threadinterrupt.scenario3bTest.Run(scenario3bTest.java:43)
06:37:06  	at j9vm.test.threadinterrupt.scenario3bTest.main(scenario3bTest.java:27)
06:37:07  inter syncing on a
06:37:07  inter synced on a
06:37:07  inter interrupting main
06:37:07  inter done interrupting main
06:37:07  inter sleeping for 5 seconds
06:37:12  inter releasing a
06:37:12  inter released a
06:37:12  non-zero exit value: 1
06:37:12  *** Test FAILED *** (j9vm.test.threadinterrupt.scenario3bTest)
```
