### ISSUE TITLE
DaaLoadTest net.openj9.test.binaryData.TestByteArray2Integer java.lang.ClassCastException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20261]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_ppc64le_linux_Release_testList_4/70/
DaaLoadTest_all_special_5m_8 `-Xgcpolicy:gencon -Xshareclasses -Xjit -Xnocompressedrefs`
```
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSixHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@f84eb804
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSixHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@e631dcfa
00:59:51  DLT 	FAILURE: testMinimumBoundaryValueValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@d4079723
00:59:51  DLT 	FAILURE: testMinimumBoundaryValueValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@15a56355
00:59:51  DLT 	FAILURE: testMaxValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@c50df5cd
00:59:51  DLT 	FAILURE: testMaxValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@18332933
00:59:51  DLT 	FAILURE: testRandomIntegerSixHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@ce31741b
00:59:51  DLT 	FAILURE: testRandomIntegerSixHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@c570826f
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerFiveDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@3e584dba
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerFiveDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@df11e999
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerEightHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@b78e4507
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerEightHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@19acdf3
00:59:51  DLT 	FAILURE: testRandomIntegerWithFourHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@2ef754c1
00:59:51  DLT 	FAILURE: testRandomIntegerWithFourHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@273434b0
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithOneHexDigitValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@fd9fa057
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithOneHexDigitValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@6885508c
00:59:51  DLT 	FAILURE: testMinimumBoundaryValue(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@e8a26633
00:59:51  DLT 	FAILURE: testMinimumBoundaryValue(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@cc9ee58a
00:59:51  DLT 	FAILURE: testAIOBLittleEndian1(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@ae4052f4
00:59:51  DLT 	FAILURE: testAIOBLittleEndian1(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@86cd621e
00:59:51  DLT 	FAILURE: testAIOBLittleEndian2(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@54d986a8
00:59:51  DLT 	FAILURE: testAIOBLittleEndian2(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@fc0e0579
00:59:51  DLT 	FAILURE: testRandomIntegerSevenHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@52dcbf8
00:59:51  DLT 	FAILURE: testRandomIntegerSevenHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@395cf26f
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithFourHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@f82f70d9
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithFourHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@73189647
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithTwoHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@39cd5142
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithTwoHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@745f43b9
00:59:51  DLT 	FAILURE: testRandomIntegerWithFourHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@8553af58
00:59:51  DLT 	FAILURE: testRandomIntegerWithFourHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@aab1e05e
00:59:51  DLT 	FAILURE: testInvalidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@bca30f68
00:59:51  DLT 	FAILURE: testInvalidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@9d35b513
00:59:51  DLT 	FAILURE: testRandomIntegerWithThreeHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@6b9b7697
00:59:51  DLT 	FAILURE: testRandomIntegerWithThreeHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@5952eabe
00:59:51  DLT 	FAILURE: testMaximumBoundaryValue(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@737aab66
00:59:51  DLT 	FAILURE: testMaximumBoundaryValue(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@558a91f5
00:59:51  DLT 	FAILURE: testRandomIntegerSevenHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@7ea085f7
00:59:51  DLT 	FAILURE: testRandomIntegerSevenHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@4101485c
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSixHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@44bdbe0a
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSixHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@2df478cf
00:59:51  DLT 	FAILURE: testNullByteArray(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@c20fdefc
00:59:51  DLT 	FAILURE: testNullByteArray(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@5e928a2c
00:59:51  DLT 	FAILURE: testRandomIntegerWithTwoHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@13292f8d
00:59:51  DLT 	FAILURE: testRandomIntegerWithTwoHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@e2a6fbd5
00:59:51  DLT 	FAILURE: testMaximumBoundaryValueValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@27b4e6d
00:59:51  DLT 	FAILURE: testMaximumBoundaryValueValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@472305cc
00:59:51  DLT 	FAILURE: testRandomIntegerFiveDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@c5f9baab
00:59:51  DLT 	FAILURE: testRandomIntegerFiveDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@c8a7f7eb
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithThreeHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@a768f8ac
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithThreeHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@c1efa1cb
00:59:51  DLT 	FAILURE: testZeroValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@558a49ea
00:59:51  DLT 	FAILURE: testZeroValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@415d6619
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSevenHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@5bfc767f
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSevenHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@a0adf68c
00:59:51  DLT 	FAILURE: testRandomIntegerEightHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@c93d1d09
00:59:51  DLT 	FAILURE: testRandomIntegerEightHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@f8950d9
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithFourHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@167b57c8
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerWithFourHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@809a1f1f
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSevenHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@432d37ab
00:59:51  DLT 	FAILURE: testRandomNegativeIntegerSevenHexDigits(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@580571ac
00:59:51  DLT 	FAILURE: testRandomIntegerEightHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@5ed2a158
00:59:51  DLT 	FAILURE: testRandomIntegerEightHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Integer) - java.lang.ClassCastException@473c31d1
```

**Comment by pshipton** [comment]
12x x 5 grinder https://openj9-jenkins.osuosl.org/job/Grinder/3855/

**Comment by pshipton** [comment]
The grinder for https://github.com/eclipse-openj9/openj9/issues/20258 also shows the following.

https://openj9-jenkins.osuosl.org/job/Grinder_iteration_2/493/
```
11:49:26  DLT testStarted : testCheckExternalDecimal31Digits(net.openj9.test.arithmetics.TestValidityChecking)
11:49:26  DLT Test failed:
11:49:26  DLT java.lang.ClassCastException: net.openj9.test.arithmetics.TestValidityChecking incompatible with java.math.BigInteger
11:49:26  DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
11:49:26  DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:49:26  DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:49:26  DLT 	at java.base/java.lang.Thread.run(Thread.java:839)
```

https://openj9-jenkins.osuosl.org/job/Grinder_iteration_4/375
```
11:16:16  DLT testFailure: testCheckingPerformance(net.openj9.test.arithmetics.TestValidityChecking): object is not an instance of declaring class
11:16:16  DLT java.lang.IllegalArgumentException: object is not an instance of declaring class
11:16:16  DLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:16:16  DLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:16:16  DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:16:16  DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
```

**Comment by pshipton** [comment]
The grinder for https://github.com/eclipse-openj9/openj9/issues/20260 shows the following.

https://openj9-jenkins.osuosl.org/job/Grinder_iteration_1/539
```
11:33:58  DLT testFailure: longPerformanceTest(net.openj9.test.PD2Primitive.TestPD2Primitives2PD): java.lang.ClassCastException@3857bb54
11:33:58  DLT java.lang.IllegalArgumentException: java.lang.ClassCastException@3857bb54
11:33:58  DLT 	at jdk.internal.reflect.GeneratedMethodAccessor1653.invoke(Unknown Source)
11:33:58  DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:33:58  DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
```

**Comment by pshipton** [comment]
@hzongaro pls take a look.

**Comment by pshipton** [comment]
The grinder from https://github.com/eclipse-openj9/openj9/issues/20261

https://openj9-jenkins.osuosl.org/job/Grinder_iteration_0/539 - [ubu22-ppc64le-3](https://openj9-jenkins.osuosl.org/computer/ubu22-ppc64le-3)
```
11:24:31  DLT 	FAILURE: testRandomNegativeLongFourteenHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@2a024961
11:24:31  DLT 	FAILURE: testRandomNegativeLongFourteenHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@3231d3f9
11:24:31  DLT 	FAILURE: testBoundaries(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@8445c32c
11:24:31  DLT 	FAILURE: testBoundaries(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@4fd82d28
11:24:31  DLT 	FAILURE: testRandomNegativeLongFiveHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@233bf59d
11:24:31  DLT 	FAILURE: testRandomNegativeLongFiveHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@cd7d9e38
11:24:31  DLT 	FAILURE: testRandomNegativeLongFourHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@41bc7c3b
11:24:31  DLT 	FAILURE: testRandomNegativeLongFourHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@22140760
11:24:31  DLT 	FAILURE: testRandomNegativeLongThirteenHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@54245694
11:24:31  DLT 	FAILURE: testRandomNegativeLongThirteenHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@f92d3786
11:24:31  DLT 	FAILURE: testRandomNegativeLongEightHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@4893b7b9
11:24:31  DLT 	FAILURE: testRandomNegativeLongEightHexDigitsValidOffset(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@5ec15f21
11:24:31  DLT 	FAILURE: testRandomLongFifteenHexDigits(net.openj9.test.binaryData.TestByteArray2Long) - java.lang.ClassCastException@25f142e0
... etc
```
12:07:32  DLT 	FAILURE: illegalArgumentTests(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsTrailingOffsetSize6(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsLeadingOffsetSize6(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testRandomNumber(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsLeadingOffsetSize17(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsLeadingOffsetSize31(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsTrailing(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsTrailingOffset(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsLeadingOffset(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
12:07:32  DLT 	FAILURE: testValidSignsLeading(net.openj9.test.decimals.TestUD2PD) - object is not an instance of declaring class
```

https://openj9-jenkins.osuosl.org/job/Grinder_iteration_1/540 - [cent9-ppc64le-2](https://openj9-jenkins.osuosl.org/computer/cent9-ppc64le-2)
```
11:04:26  DLT java.lang.IllegalArgumentException: object is not an instance of declaring class
11:04:26  DLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:04:26  DLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:04:26  DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:04:26  DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
```

**Comment by hzongaro** [comment]
@ishitaR88, @zl-wang, this looks like it might be the same problem as #19884, or related to it

**Comment by zl-wang** [comment]
i will suggest locking onto the case whose failure can be recreated more regularly.

**Comment by pshipton** [comment]
New 0.48 grinder 12x x 5 https://openj9-jenkins.osuosl.org/job/Grinder/3862/

Includes https://github.com/eclipse-openj9/openj9/pull/20271

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_ppc64le_linux_Personal_testList_4/93 - [ubu22-ppc64le-2](https://openj9-jenkins.osuosl.org/computer/ubu22-ppc64le-2)
DaaLoadTest_daa2_special_5m_9 `-Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs`
```
10:39:46  DLT testFailure: testInvalidOffset(net.openj9.test.binaryData.TestDouble2ByteArray): java.lang.ClassCastException@852dff24
10:39:46  DLT java.lang.IllegalArgumentException: java.lang.ClassCastException@852dff24
10:39:46  DLT 	at jdk.internal.reflect.GeneratedMethodAccessor2906.invoke(Unknown Source)
10:39:46  DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:39:46  DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)

```

**Comment by rmnattas** [comment]
Suggesting moving to 0.49 or closing until seen again. 
Couldn't confirm if this is a duplicate of #20263 without recent cores and not being able to reproduce. 
Given that this happens on P10 too, there's a good chance it's a duplicate as P10 mainly uses ConstantSnippet instead of pTOC, and the fix for #20263 fixed patching ConstantSnippets.

**Comment by pshipton** [comment]
Running a grinder with the fix.
https://openj9-jenkins.osuosl.org/job/Grinder/3891/

**Comment by pshipton** [comment]
The grinder passed, where the same grinder failed (https://github.com/eclipse-openj9/openj9/issues/20261#issuecomment-2388772611) without the fix.
