### ISSUE TITLE
OpenJDK sun/misc/FloatingDecimal/TestFloatingDecimal OutOfMemoryError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20282]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/321/
jdk_lang_j9_0
sun/misc/FloatingDecimal/TestFloatingDecimal.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/321/openjdk_test_output.tar.gz
```
00:51:05  java.lang.OutOfMemoryError: Java heap space
00:51:05  	at sun.misc.FDBigInteger.leftShift(FDBigInteger.java:476)
00:51:05  	at sun.misc.FDBigInteger.valueOfPow52(FDBigInteger.java:267)
00:51:05  	at sun.misc.FloatingDecimal$BinaryToASCIIBuffer.dtoa(FloatingDecimal.java:717)
00:51:05  	at sun.misc.FloatingDecimal$BinaryToASCIIBuffer.access$100(FloatingDecimal.java:259)
00:51:05  	at sun.misc.FloatingDecimal.getBinaryToASCIIConverter(FloatingDecimal.java:1785)
00:51:05  	at sun.misc.FloatingDecimal.getBinaryToASCIIConverter(FloatingDecimal.java:1738)
00:51:05  	at sun.misc.FloatingDecimal.toJavaFormatString(FloatingDecimal.java:70)
00:51:05  	at TestFloatingDecimal.testToJavaFormatStringDoubleRandom(TestFloatingDecimal.java:242)
00:51:05  	at TestFloatingDecimal.testToJavaFormatStringDouble(TestFloatingDecimal.java:253)
00:51:05  	at TestFloatingDecimal.testToJavaFormatString(TestFloatingDecimal.java:308)
00:51:05  	at TestFloatingDecimal.main(TestFloatingDecimal.java:319)
```

**Comment by pshipton** [comment]
@dmitripivkine fyi
