### ISSUE TITLE
testRASAPI com.ibm.jvm.ras.tests.DumpAPITriggerTests failed  expected:<7> but was:<6>

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20293]
**Failure link**
---
From internal [Test_openjdk11_j9_extended.functional_aarch64_linux_testList_1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_1/593/) (ubu20-aarch64-3)

```**Java Version**
java version "11.0.25-beta" 2024-10-15
IBM Semeru Runtime Certified Edition 11.0.25+7-202410022208 (build 11.0.25-beta+7)
Eclipse OpenJ9 VM 11.0.25+7-202410022208 (build master-ea25376c8b, JRE 11 Linux aarch64-64-Bit Compressed References 20241002_701 (JIT enabled, AOT enabled)
OpenJ9   - ea25376c8b
OMR      - fa23d1b84
JCL      - ef8422167b based on jdk-11.0.25+7)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=testRASAPI_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F701%2Fibm-semeru-certified-jdk_aarch64_linux_JDK11U_2024-10-02-22-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F701%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2024-10-02-22-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F701%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2024-10-02-22-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=665&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-10-03T00:35:21.853Z] variation: NoOptions
[2024-10-03T00:35:21.853Z] JVM_OPTIONS:  

[2024-10-03T00:36:04.718Z]      [test]     [junit] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.17 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] 
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpNullOpts took 0.05 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpEmptyOpts took 0.038 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpJavaNoOpts took 1.111 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpSystemNoOpts took 4.247 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpHeapNoOpts took 1.479 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpSnapNoOpts took 0.194 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpConsoleNoOpts took 0.069 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpStackNoOpts took 0.066 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpSilentNoOpts took 0.058 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpBadAgentNoOpts took 0.108 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpJavaToFile took 0.149 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] Testcase: testTriggerDumpSystemToFile took 4.579 sec
[2024-10-03T00:36:04.718Z]      [test]     [junit] 	FAILED
[2024-10-03T00:36:04.718Z]      [test]     [junit] Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_1/jvmtest/functional/RasapiTest , found:[junit4.jar, system.testTriggerDumpSystemToFile.1727915751217.dmp, junitvmwatcher3227523197465511864.properties, com.ibm.jvm.ras.tests.jar, test.xml, junit1764461848182658063.properties] expected:<7> but was:<6>
[2024-10-03T00:36:04.718Z]      [test]     [junit] junit.framework.AssertionFailedError: Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_1/jvmtest/functional/RasapiTest , found:[junit4.jar, system.testTriggerDumpSystemToFile.1727915751217.dmp, junitvmwatcher3227523197465511864.properties, com.ibm.jvm.ras.tests.jar, test.xml, junit1764461848182658063.properties] expected:<7> but was:<6>
[2024-10-03T00:36:04.718Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpX(DumpAPITriggerTests.java:309)
[2024-10-03T00:36:04.718Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpWithFile(DumpAPITriggerTests.java:262)
[2024-10-03T00:36:04.718Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.testTriggerDumpSystemToFile(DumpAPITriggerTests.java:138)
[2024-10-03T00:36:04.718Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-10-03T00:36:04.718Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-10-03T00:36:04.718Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-10-03T00:36:04.718Z]      [test]     [junit] 
[2024-10-03T00:36:04.718Z]      [test] 
[2024-10-03T00:36:04.718Z]      [test] BUILD FAILED
[2024-10-03T00:36:04.718Z]      [test] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_1/jvmtest/functional/RasapiTest/test.xml:78: Test com.ibm.jvm.ras.tests.DumpAPITriggerTests failed
[2024-10-03T00:36:04.718Z]      [test] 
[2024-10-03T00:36:04.718Z]      [test] Total time: 39 seconds
[2024-10-03T00:36:04.718Z] 
[2024-10-03T00:36:04.718Z] BUILD FAILED
[2024-10-03T00:36:04.718Z] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_1/jvmtest/functional/RasapiTest/test.xml:50: Java returned: 1
[2024-10-03T00:36:04.718Z] 
[2024-10-03T00:36:04.718Z] Total time: 42 seconds
[2024-10-03T00:36:04.718Z] -----------------------------------
[2024-10-03T00:36:04.718Z] testRASAPI_0_FAILED
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/43802/)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.functional_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/747/)(`sles15s390x-svl-rt1-1`)
```
java version "11.0.25" 2024-10-15
IBM Semeru Runtime Certified Edition 11.0.25.0-rc1 (build 11.0.25+9)
Eclipse OpenJ9 VM 11.0.25.0-rc1 (build v0.48.0-release-1d5831436e, JRE 11 Linux s390x-64-Bit Compressed References 20241025_963 (JIT enabled, AOT enabled)
OpenJ9   - 1d5831436e
OMR      - d10a4d553
JCL      - 4668c27671 based on jdk-11.0.25+9)

[2024-10-26T15:29:28.155Z] variation: NoOptions
[2024-10-26T15:29:28.155Z] JVM_OPTIONS:  

[2024-10-26T15:30:02.845Z]      [test]     [junit] Testcase: testTriggerDumpHeapToFile took 0.885 sec
[2024-10-26T15:30:02.845Z]      [test]     [junit] 	FAILED
[2024-10-26T15:30:02.845Z]      [test]     [junit] Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher15751971357405294801.properties, junit4098161205989465199.properties, heap.testTriggerDumpHeapToFile.1729956590421.phd] expected:<7> but was:<6>
[2024-10-26T15:30:02.845Z]      [test]     [junit] junit.framework.AssertionFailedError: Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher15751971357405294801.properties, junit4098161205989465199.properties, heap.testTriggerDumpHeapToFile.1729956590421.phd] expected:<7> but was:<6>
[2024-10-26T15:30:02.845Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpX(DumpAPITriggerTests.java:309)
[2024-10-26T15:30:02.846Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpWithFile(DumpAPITriggerTests.java:262)
[2024-10-26T15:30:02.846Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.testTriggerDumpHeapToFile(DumpAPITriggerTests.java:142)
[2024-10-26T15:30:02.846Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-10-26T15:30:02.846Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-10-26T15:30:02.846Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-10-26T15:30:02.846Z]      [test]     [junit] 
[2024-10-26T15:30:02.846Z]      [test]     [junit] JVMDUMP010I Heap dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest/heap.testTriggerDumpHeapToFile.1729956590421.phd
[2024-10-26T15:30:02.846Z]      [test] 
[2024-10-26T15:30:02.846Z]      [test] BUILD FAILED
[2024-10-26T15:30:02.846Z]      [test] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest/test.xml:78: Test com.ibm.jvm.ras.tests.DumpAPITriggerTests failed
[2024-10-26T15:30:02.846Z]      [test] 
[2024-10-26T15:30:02.846Z]      [test] Total time: 32 seconds
[2024-10-26T15:30:02.846Z] 
[2024-10-26T15:30:02.846Z] BUILD FAILED
[2024-10-26T15:30:02.846Z] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest/test.xml:50: Java returned: 1
[2024-10-26T15:30:02.846Z] 
[2024-10-26T15:30:02.846Z] Total time: 34 seconds
[2024-10-26T15:30:02.846Z] -----------------------------------
[2024-10-26T15:30:02.846Z] testRASAPI_0_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44469/)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.functional_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/874/)
```
[2025-05-01T04:43:24.382Z] variation: NoOptions
[2025-05-01T04:43:24.382Z] JVM_OPTIONS:  

[2025-05-01T04:43:55.204Z]      [test]     [junit] Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher15548961858368890306.properties, junit5780772484584665776.properties, Snap.20250430.214354.707986.0004.trc, omrvmem_000707986_qejh63] expected:<6> but was:<7>
[2025-05-01T04:43:55.204Z]      [test]     [junit] junit.framework.AssertionFailedError: Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher15548961858368890306.properties, junit5780772484584665776.properties, Snap.20250430.214354.707986.0004.trc, omrvmem_000707986_qejh63] expected:<6> but was:<7>
[2025-05-01T04:43:55.204Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpX(DumpAPITriggerTests.java:309)
[2025-05-01T04:43:55.204Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpNoOpts(DumpAPITriggerTests.java:249)
[2025-05-01T04:43:55.204Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.testTriggerDumpSnapNoOpts(DumpAPITriggerTests.java:100)
[2025-05-01T04:43:55.204Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-01T04:43:55.204Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-01T04:43:55.204Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-01T04:43:55.204Z]      [test]     [junit] 
[2025-05-01T04:43:55.204Z]      [test]     [junit] JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest/Snap.20250430.214354.707986.0004.trc
[2025-05-01T04:43:55.204Z]      [test] 
[2025-05-01T04:43:55.204Z]      [test] BUILD FAILED
[2025-05-01T04:43:55.204Z]      [test] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest/test.xml:78: Test com.ibm.jvm.ras.tests.DumpAPITriggerTests failed
[2025-05-01T04:43:55.204Z]      [test] 
[2025-05-01T04:43:55.204Z]      [test] Total time: 28 seconds
[2025-05-01T04:43:55.204Z] 
[2025-05-01T04:43:55.204Z] BUILD FAILED
[2025-05-01T04:43:55.204Z] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/jvmtest/functional/RasapiTest/test.xml:50: Java returned: 1
[2025-05-01T04:43:55.204Z] 
[2025-05-01T04:43:55.204Z] Total time: 30 seconds
[2025-05-01T04:43:55.204Z] -----------------------------------
[2025-05-01T04:43:55.204Z] testRASAPI_0_FAILED
```
