### ISSUE TITLE
harmony testGolden javax.security.auth.callback.serialization.PasswordCallbackTest ComparisonFailure: null expected:<[abc]> but was:<[   ]>

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20307]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=93510358)
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112 `-Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs`
fyrec50y

Failed 1/30 in a grinder (fyrec50z)

```
j> 15:03:40 20241004 15:03:40 <Primary|SimpleDriver|org.apache.harmony.auth.tests.javax.security.auth.callback.serialization.PasswordCallbackTest|3288|Default Invocant> ERROR: Test testGolden(org.apache.harmony.auth.tests.javax.security.auth.callback.serialization.PasswordCallbackTest) failed
j> 15:03:40 Throwable trace:
j> 15:03:40 junit.framework.ComparisonFailure: null expected:<[abc]> but was:<[   ]>
j> 15:03:40 	at junit.framework.Assert.assertEquals(Assert.java:81)
j> 15:03:40 	at junit.framework.Assert.assertEquals(Assert.java:87)
j> 15:03:40 	at org.apache.harmony.auth.tests.javax.security.auth.callback.serialization.PasswordCallbackTest.assertDeserialized(PasswordCallbackTest.java:51)
j> 15:03:40 	at org.apache.harmony.testframework.serialization.SerializationTest.verifyGolden(SerializationTest.java:519)
j> 15:03:40 	at org.apache.harmony.testframework.serialization.SerializationTest.verifyGolden(SerializationTest.java:492)
j> 15:03:40 	at org.apache.harmony.testframework.serialization.SerializationTest.testGolden(SerializationTest.java:147)
```

**Comment by pshipton** [comment]
@hzongaro @r30shah fyi. I haven't seen this failure before (although I don't always do the best job of triaging harmony failures since there are a bunch of machine issues).

**Comment by r30shah** [comment]
I see this one failing 1/50 times (build_info.php?build_id=79356), need to investigate this (May be 31-bit z/OS issue only??)

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=93793696)
[zOS S390 64bit Compressed Pointers] 80 Load_Level_2.harmony.5mins.Mode610 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`
fyrec510

**Comment by pshipton** [comment]
It's not 32-bit only and it failed without -Xjit:count=0 so I've added it to the next milestone.

**Comment by r30shah** [comment]
Thanks Peter for sharing, I think this will help nailing down the cause. @matthewhall2  Let's look into this together.

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=93902947)
[zOS S390 64bit Compressed Pointers] 80 Load_Level_2.harmony.5mins.Mode610
fyrec60h

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=94183709)
[Linux S390 64bit] 80 Load_Level_2.harmony.5mins.Mode109

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=94626873)
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode187

**Comment by pshipton** [comment]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=95786743)
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode187

**Comment by r30shah** [comment]
Looking into this, given the assertion failure, to effectively investigate, I need to reproduce this reliably. I did picked up the last failing build from previous comment and launched [grinder of 100x](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=81474)
I can not reproduce this in 100x. Rerunning the s390x Linux with latest build 100x [internal link ](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=81474). This one does not fail as well. I will check if I can reproduce this on specific set of machines (Though I checked couple of last reported failures - I see the grinder did launch some jobs on those machines so that seems unlikely).

**Comment by pshipton** [comment]
It does fail in the builds fairly frequently. If it can't be reproduced via grinder, is there anything that can be done to the test to gather more information when it does fail?

**Comment by r30shah** [comment]
> It does fail in the builds fairly frequently. If it can't be reproduced via grinder, is there anything that can be done to the test to gather more information when it does fail?

I am looking into that direction. In past, I have dealt with such intermittent issue by changing the test to invoke a debug agent that can keep running the test to help identify the method causing the issue.

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=96186470
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112

**Comment by pshipton** [comment]
I haven't seen this in a couple of weeks, removing the blocker label.

**Comment by hzongaro** [comment]
@r30shah, are you still looking at this one for 0.49, or should it move out to 0.51?

**Comment by r30shah** [comment]
Hi @hzongaro  I am looking into this but given the low failure rate, couldn't get much update. I am going to work on this with changing the test to trigger agent for more debugging, we can move it to 0.51.

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=100359145

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=100922439
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112
fyrec605

**Comment by hzongaro** [comment]
@r30shah, do you think you'll be able to fix this for 0.51 or should we move it out to the 0.52 release?

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=102173341
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112
fyrec605

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=102425918
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112
fyrec516

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=103887101
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112
fyrec20a

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=104472372

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=104984016 - rtv-rhel8le-rtp-test-cyodd-1
[Linux PPC LE 64bit] 80 Load_Level_2.harmony.5mins.Mode187
`-Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs`
```
j> 12:22:21 20250404 12:22:21 <Primary|SimpleDriver|org.apache.harmony.auth.tests.javax.security.auth.callback.serialization.PasswordCallbackTest|113|Default Invocant> ERROR: Test testSelf(org.apache.harmony.auth.tests.javax.security.auth.callback.serialization.PasswordCallbackTest) failed
j> 12:22:21 Throwable trace:
j> 12:22:21 junit.framework.ComparisonFailure: null expected:<[abc]> but was:<[   ]>
j> 12:22:21 	at junit.framework.Assert.assertEquals(Assert.java:81)
j> 12:22:21 	at junit.framework.Assert.assertEquals(Assert.java:87)
j> 12:22:21 	at org.apache.harmony.auth.tests.javax.security.auth.callback.serialization.PasswordCallbackTest.assertDeserialized(PasswordCallbackTest.java:51)
j> 12:22:21 	at org.apache.harmony.testframework.serialization.SerializationTest.verifySelf(SerializationTest.java:556)
j> 12:22:21 	at org.apache.harmony.testframework.serialization.SerializationTest.verifySelf(SerializationTest.java:594)
j> 12:22:21 	at org.apache.harmony.testframework.serialization.SerializationTest.testSelf(SerializationTest.java:134)
```

**Comment by pshipton** [comment]
@hzongaro interesting there has been a failure on non-Z (Linux PPC LE) for the first time.

**Comment by hzongaro** [comment]
No luck reproducing the Linux PPC LE failure in [25x](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=91738) or [100x](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=91741) internal grinder runs

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=106487748
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=106840414
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=107450206
[AIX64 Compressed Pointers] 80 Load_Level_2.harmony.5mins.Mode610

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=110433743
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=110846733
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode112

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=113333272
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode187

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=113383021
[zOS S390 64bit Compressed Pointers] 80 Load_Level_2.harmony.5mins.Mode610

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=113528860
[Linux S390] 80 Load_Level_2.harmony.5mins.Mode110

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=114819824
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode110

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=116214667
[Linux S390 64bit] 80 Load_Level_2.harmony.5mins.Mode110

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=122642135
[Linux S390] 80 Load_Level_2.harmony.5mins.Mode187

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=124335299
[Linux IA32] 80 Load_Level_2.harmony.5mins.Mode110

http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=125599490
[zOS S390] 80 Load_Level_2.harmony.5mins.Mode187

**Comment by pshipton** [comment]
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=127470425
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=131121171 [Linux IA32] Aug 10
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=132839511 [Linux Hammer Compressed Pointers] Sep 15
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=133149222 [zOS S390] Sep 22
