### ISSUE TITLE
CryptoTests_jtreg timeout RSAKeyPairGenerator.generateKeyPair

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20309]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/822
CryptoTests_jtreg_0
```
03:26:24  ACTION: main -- Error. Program `/home/jenkins/workspace/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 3600000ms, elapsed time including timeout handling was 3603604ms).
03:26:24  REASON: User specified action: run main/othervm/timeout=1800 cryptotest.CryptoTest 
03:26:24  TIME:   3603.63 seconds
03:26:24  messages:
03:26:24  command: main cryptotest.CryptoTest
03:26:24  reason: User specified action: run main/othervm/timeout=1800 cryptotest.CryptoTest 
03:26:24  started: Sat Oct 05 06:26:11 UTC 2024
03:26:24  Mode: othervm [/othervm specified]
03:26:24  Additional options from @modules: --add-modules java.base,java.security.jgss,java.smartcardio,java.xml.crypto --add-opens java.base/java.security=ALL-UNNAMED --add-exports java.base/com.sun.crypto.provider=ALL-UNNAMED --add-exports java.base/sun.security.internal.spec=ALL-UNNAMED --add-exports java.base/sun.security.ssl=ALL-UNNAMED --add-exports java.base/sun.security.x509=ALL-UNNAMED --add-exports java.security.jgss/sun.security.jgss=ALL-UNNAMED --add-exports java.security.jgss/sun.security.jgss.krb5=ALL-UNNAMED --add-exports java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-exports java.smartcardio/javax.smartcardio=ALL-UNNAMED --add-exports java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED
03:26:24  Timeout information:
03:26:24  Running jstack on process 3923583
03:26:24  2024-10-05T07:26:12.440153954
03:26:24  Virtual machine: 3923583 JVM information:
03:26:24  JRE 17 Linux s390x-64-Bit Compressed References 20241004_845 (JIT enabled, AOT enabled)
03:26:24  OpenJ9   - 845b1ce4245
03:26:24  OMR      - 56a6b834485
03:26:24  JCL      - 8e2f05376ed based on jdk-17.0.13+10
03:26:24  
03:26:24  "main" prio=5 Id=1 WAITING
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.waitImpl(Native Method)
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.wait(Object.java:251)
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.wait(Object.java:219)
03:26:24  	at java.base@17.0.13-internal/java.lang.Thread.join(Thread.java:784)
03:26:24  	at java.base@17.0.13-internal/java.lang.Thread.join(Thread.java:739)
03:26:24  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:85)
03:26:24  
03:26:24  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
03:26:24  
03:26:24  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
03:26:24  
03:26:24  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
03:26:24  
03:26:24  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
03:26:24  
03:26:24  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
03:26:24  
03:26:24  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
03:26:24  
03:26:24  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
03:26:24  
03:26:24  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
03:26:24  
03:26:24  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
03:26:24  
03:26:24  "IProfiler" prio=5 Id=12 RUNNABLE
03:26:24  
03:26:24  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.waitImpl(Native Method)
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.wait(Object.java:251)
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.wait(Object.java:219)
03:26:24  	at java.base@17.0.13-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:140)
03:26:24  	at java.base@17.0.13-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
03:26:24  	at java.base@17.0.13-internal/java.lang.Thread.run(Thread.java:857)
03:26:24  	at java.base@17.0.13-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
03:26:24  
03:26:24  "Finalizer thread" prio=5 Id=13 RUNNABLE
03:26:24  
03:26:24  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
03:26:24  
03:26:24  "GC Worker" prio=5 Id=15 RUNNABLE
03:26:24  
03:26:24  "GC Worker" prio=5 Id=16 RUNNABLE
03:26:24  
03:26:24  "GC Worker" prio=5 Id=17 RUNNABLE
03:26:24  
03:26:24  "Attach API update file access time" prio=5 Id=20 TIMED_WAITING
03:26:24  	at java.base@17.0.13-internal/java.lang.Thread.sleepImpl(Native Method)
03:26:24  	at java.base@17.0.13-internal/java.lang.Thread.sleep(Thread.java:1009)
03:26:24  	at java.base@17.0.13-internal/java.lang.Thread.sleep(Thread.java:992)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.AttachHandler$1.run(AttachHandler.java:348)
03:26:24  
03:26:24  "Attach API wait loop" prio=10 Id=21 RUNNABLE
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:264)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)
03:26:24  
03:26:24  "MainThread" prio=5 Id=22 RUNNABLE
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.implMultiplyToLen(BigInteger.java:1780)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.multiplyToLen(BigInteger.java:1758)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.implMontgomeryMultiply(BigInteger.java:2860)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.montgomeryMultiply(BigInteger.java:2812)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.oddModPow(BigInteger.java:3081)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.modPow(BigInteger.java:2754)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.passesMillerRabin(BigInteger.java:1122)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.primeToCertainty(BigInteger.java:978)
03:26:24  	at java.base@17.0.13-internal/java.math.BitSieve.retrieve(BitSieve.java:203)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.largePrime(BigInteger.java:855)
03:26:24  	at java.base@17.0.13-internal/java.math.BigInteger.probablePrime(BigInteger.java:785)
03:26:24  	at java.base@17.0.13-internal/sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:187)
03:26:24  	at java.base@17.0.13-internal/java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
03:26:24  	at java.base@17.0.13-internal/java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:495)
03:26:24  	at app//cryptotest.utils.KeysNaiveGenerator.getRsaKeyPair(KeysNaiveGenerator.java:165)
03:26:24  	at app//cryptotest.utils.KeysNaiveGenerator.getRsaPrivateKey(KeysNaiveGenerator.java:169)
03:26:24  	at app//cryptotest.tests.SignatureTests.checkAlgorithm(SignatureTests.java:89)
03:26:24  	at app//cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:96)
03:26:24  	at app//cryptotest.utils.AlgorithmTest.doTest(AlgorithmTest.java:65)
03:26:24  	at app//cryptotest.CryptoTest.main(CryptoTest.java:130)
03:26:24  	at java.base@17.0.13-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:26:24  	at java.base@17.0.13-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
03:26:24  	at java.base@17.0.13-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:26:24  	at java.base@17.0.13-internal/java.lang.reflect.Method.invoke(Method.java:575)
03:26:24  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
03:26:24  	at java.base@17.0.13-internal/java.lang.Thread.run(Thread.java:857)
03:26:24  
03:26:24  "file lock watchdog" prio=10 Id=25 TIMED_WAITING
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.waitImpl(Native Method)
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.wait(Object.java:251)
03:26:24  	at java.base@17.0.13-internal/java.lang.Object.wait(Object.java:219)
03:26:24  	at java.base@17.0.13-internal/java.util.TimerThread.mainLoop(Timer.java:602)
03:26:24  	at java.base@17.0.13-internal/java.util.TimerThread.run(Timer.java:543)
03:26:24  
03:26:24  "Attachment portNumber: 37011" prio=10 Id=27 RUNNABLE
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:249)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:185)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:252)
03:26:24  	at java.base@17.0.13-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:162)
03:26:24  
03:26:24  
03:26:24  --- Timeout information end.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Release_testList_1/120 - 0.49 build
CryptoTests_jtreg_0
```
23:14:34  "MainThread" Id=21 RUNNABLE
23:14:34  	at java.math.BigInteger.multiplyToLen(BigInteger.java:1682)
23:14:34  	at java.math.BigInteger.implMontgomeryMultiply(BigInteger.java:2710)
23:14:34  	at java.math.BigInteger.montgomeryMultiply(BigInteger.java:2663)
23:14:34  	at java.math.BigInteger.oddModPow(BigInteger.java:2930)
23:14:34  	at java.math.BigInteger.modPow(BigInteger.java:2605)
23:14:34  	at java.math.BigInteger.passesMillerRabin(BigInteger.java:1038)
23:14:34  	at java.math.BigInteger.primeToCertainty(BigInteger.java:894)
23:14:34  	at java.math.BitSieve.retrieve(BitSieve.java:203)
23:14:34  	at java.math.BigInteger.largePrime(BigInteger.java:771)
23:14:34  	at java.math.BigInteger.probablePrime(BigInteger.java:701)
23:14:34  	at sun.security.rsa.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:137)
23:14:34  	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703)
23:14:34  	at java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:470)
23:14:34  	at cryptotest.utils.KeysNaiveGenerator.getRsaKeyPair(KeysNaiveGenerator.java:165)
23:14:34  	at cryptotest.utils.KeysNaiveGenerator.getRsaPrivateKey(KeysNaiveGenerator.java:169)
23:14:34  	at cryptotest.tests.SignatureTests.checkAlgorithm(SignatureTests.java:89)
23:14:34  	at cryptotest.utils.AlgorithmTest.mainLoop(AlgorithmTest.java:96)
23:14:34  	at cryptotest.utils.AlgorithmTest.doTest(AlgorithmTest.java:65)
23:14:34  	at cryptotest.CryptoTest.main(CryptoTest.java:130)
```

**Comment by pshipton** [comment]
See also https://github.com/eclipse-openj9/openj9/issues/20986
