### ISSUE TITLE
openJcePlusTests_0_FAILED IllegalStateException: Cipher not initialized & Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20326]
**Failure link**
---
From internal [0.48 milestone 1 build Test_openjdk21_j9_extended.functional_s390x_linux_fips140_3_openjceplusfips](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.functional_s390x_linux_fips140_3_openjceplusfips/6/) (`rtj-ubu24s390x-svl-test-oklad-1`)

```**Java Version**
openjdk version "21.0.5" 2024-10-15 LTS
IBM Semeru Runtime Open Edition 21.0.5.0-m1 (build 21.0.5+9-LTS)
Eclipse OpenJ9 VM 21.0.5.0-m1 (build v0.48.0-release-8899b66789, JRE 21 Linux s390x-64-Bit Compressed References 20241015_275 (JIT enabled, AOT enabled)
OpenJ9   - 8899b66789
OMR      - f8f0d789a
JCL      - f8f9184c30f based on jdk-21.0.5+9)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=openJcePlusTests_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=9f50c848-8764-440d-b95a-1d295c21713e&amp;TEST_FLAG=FIPS140_3_OpenJCEPlusFIPS&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;LABEL=&amp;JCK_VERSION=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fhyc-runtimes-jenkins.swg-devops.com%2Fjob%2Fbuild-scripts%2Fjob%2Fopenjdk21-pipeline%2F353%2Fartifact%2Ftarget%2Flinux%2Fs390x%2Fopenj9%2F*.tar.gz%2F*zip*%2Fopenj9.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.4-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;BUILD_TYPE=release&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=docker-na.artifactory.swg-devops.com%2Fsys-rt-docker-local&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JCK_GIT_BRANCH=main&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;CONFIG_JSON=%5B%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22NONE%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22aarch64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22aarch64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_2%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS.FIPS140-3%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%0A%5D&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=120&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=f3b78d91-4db0-4a87-b4d8-32164430cfdc&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional%2FOpenJcePlusTests%2Cfunctional%2Fsecurity&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;separator-87e3a7db-4843-4907-ad26-40f469fe3204=&amp;TIME_LIMIT=36&amp;JVM_OPTIONS=&amp;PARALLEL=Dynamic) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-10-08T16:42:41.882Z] Running test openJcePlusTests_0 ...
[2024-10-08T16:42:41.882Z] ===============================================
[2024-10-08T16:42:41.882Z] openJcePlusTests_0 Start Time: Tue Oct  8 09:42:41 2024 Epoch Time (ms): 1728405761141
[2024-10-08T16:42:41.882Z] variation: NoOptions
[2024-10-08T16:42:41.882Z] JVM_OPTIONS:   -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS

[2024-10-08T17:19:17.441Z] Test calling: ibm.jceplus.junit.openjceplus.multithread.TestAES_128
[2024-10-08T17:19:17.441Z] executing testAES_128
[2024-10-08T17:19:17.441Z] executing testAES_128
[2024-10-08T17:19:17.441Z] executing testAES_128
[2024-10-08T17:19:17.441Z] executing testAES_128
[2024-10-08T17:19:17.442Z] executing testAES_128
[2024-10-08T17:19:17.442Z] executing testAES_128
[2024-10-08T17:19:17.442Z] executing testAES_128
[2024-10-08T17:19:17.442Z] executing testAES_128
[2024-10-08T17:19:17.442Z] executing testAES_128
[2024-10-08T17:19:17.442Z] executing testAES_128
[2024-10-08T17:19:24.110Z] java.lang.IllegalStateException: Cipher not initialized
[2024-10-08T17:19:24.110Z] 	at java.base/javax.crypto.Cipher.checkCipherState(Cipher.java:1826)
[2024-10-08T17:19:24.110Z] 	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2236)
[2024-10-08T17:19:24.110Z] 	at ibm.jceplus.junit.base.BaseTestAES.testAESBadPaddingDecrypt(BaseTestAES.java:444)
[2024-10-08T17:19:24.110Z] 	at 

[2024-10-08T17:19:24.111Z] junit.framework.AssertionFailedError: Decrypted text does not match expected, msglen=63
[2024-10-08T17:19:24.111Z] 	at junit.framework.Assert.fail(Assert.java:57)
[2024-10-08T17:19:24.111Z] 	at junit.framework.Assert.assertTrue(Assert.java:22)
[2024-10-08T17:19:24.111Z] 	at junit.framework.TestCase.assertTrue(TestCase.java:192)
[2024-10-08T17:19:24.111Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecryptUpdateCopySafe(BaseTestAES.java:1168)
[2024-10-08T17:19:24.111Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:875)
[2024-10-08T17:19:24.111Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:835)
[2024-10-08T17:19:24.111Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:821)
[2024-10-08T17:19:24.111Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:813)
[2024-10-08T17:19:24.111Z] 	at ibm.jceplus.junit.base.BaseTestAES.testAES_CFB_PKCS5Padding(BaseTestAES.java:195)

[2024-10-08T17:19:24.122Z] Unhandled exception
[2024-10-08T17:19:24.122Z] Type=Segmentation error vmState=0x00000000
[2024-10-08T17:19:24.122Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
[2024-10-08T17:19:24.122Z] Handler1=000003FFB1146658 Handler2=000003FFB1031A60 InaccessibleAddress=00000000950D7000
[2024-10-08T17:19:24.122Z] gpr0=0000000000000019 gpr1=00000000950D7920 gpr2=0000000000000000 gpr3=00000000950D7900
[2024-10-08T17:19:24.122Z] gpr4=000003FF00000003 gpr5=0000000000A6C480 gpr6=000000008477C6D8 gpr7=000003FFAC01E2D0
[2024-10-08T17:19:24.122Z] gpr8=000000000096E800 gpr9=0000000000000000 gpr10=000000008477C6D8 gpr11=000003FFAC05B3C0
[2024-10-08T17:19:24.122Z] gpr12=009914000000000C gpr13=000000000096E800 gpr14=000003FFABA17EB0 gpr15=000003FFB1E75078
[2024-10-08T17:19:24.122Z] psw=000003FFB117BD4C mask=0705100180000000 fpc=0008ff00 bea=000003FFB117C19A
[2024-10-08T17:19:24.122Z] fpr0=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-10-08T17:19:24.122Z] fpr1=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-10-08T17:19:24.123Z] fpr2=000003ffb1e768c0 (f: 2984732928.000000, d: 2.172276e-311)
[2024-10-08T17:19:24.123Z] fpr3=bfe017a6b8de75af (f: 3101586944.000000, d: -5.028871e-01)
[2024-10-08T17:19:24.123Z] fpr4=49923dd0a0000000 (f: 2684354560.000000, d: 2.603509e+46)
[2024-10-08T17:19:24.123Z] fpr5=3f1367135154ab8f (f: 1364503424.000000, d: 7.401519e-05)
[2024-10-08T17:19:24.123Z] fpr6=0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2024-10-08T17:19:24.123Z] fpr7=402351bb262d8e49 (f: 640519744.000000, d: 9.659631e+00)
[2024-10-08T17:19:24.123Z] fpr8=00000000009484a0 (f: 9733280.000000, d: 4.808879e-317)
[2024-10-08T17:19:24.123Z] fpr9=000003ffbbde6d90 (f: 3151916544.000000, d: 2.172359e-311)
[2024-10-08T17:19:24.123Z] fpr10=00000000009489b8 (f: 9734584.000000, d: 4.809524e-317)
[2024-10-08T17:19:24.123Z] fpr11=000003ffbc1f5198 (f: 3156169216.000000, d: 2.172361e-311)
[2024-10-08T17:19:24.123Z] fpr12=000623f9d62224be (f: 3592561920.000000, d: 8.539459e-309)
[2024-10-08T17:19:24.123Z] fpr13=000003ffb559c508 (f: 3042559232.000000, d: 2.172305e-311)
[2024-10-08T17:19:24.123Z] fpr14=000003ffb1e768c0 (f: 2984732928.000000, d: 2.172276e-311)
[2024-10-08T17:19:24.123Z] fpr15=000003ffb55c08e8 (f: 3042707712.000000, d: 2.172305e-311)
[2024-10-08T17:19:24.123Z] Module=/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_fips140_3_openjceplusfips/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
[2024-10-08T17:19:24.123Z] Module_base_address=000003FFB1100000
[2024-10-08T17:19:24.123Z] Target=2_90_20241015_275 (Linux 6.8.0-45-generic)
[2024-10-08T17:19:24.123Z] CPU=s390x (4 logical CPUs) (0x1f579f000 RAM)
[2024-10-08T17:19:24.123Z] ----------- Stack Backtrace -----------
[2024-10-08T17:19:24.123Z] objectMonitorEnterNonBlocking+0x214 (0x000003FFB117BD4C [libj9vm29.so+0x7bd4c])
[2024-10-08T17:19:24.123Z] fast_jitMonitorEntry+0x28 (0x000003FFABA17EB0 [libj9jit29.so+0xc17eb0])
[2024-10-08T17:19:24.123Z] jitMonitorEntry+0x20 (0x000003FFABA2B8D8 [libj9jit29.so+0xc2b8d8])
[2024-10-08T17:19:24.123Z] ---------------------------------------
[2024-10-08T17:19:24.123Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2024/10/08 10:19:22 - please wait.

[2024-10-08T17:19:24.124Z] java.security.ProviderException: Failure in engineDoFinal
[2024-10-08T17:19:24.124Z] 	at openjceplus/com.ibm.crypto.plus.provider.OpenJCEPlus.providerException(OpenJCEPlus.java:1027)
[2024-10-08T17:19:24.124Z] 	at openjceplus/com.ibm.crypto.plus.provider.AESCipher.engineDoFinal(AESCipher.java:86)
[2024-10-08T17:19:24.124Z] 	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2244)
[2024-10-08T17:19:24.125Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecryptReuseObject(BaseTestAES.java:1055)
[2024-10-08T17:19:24.125Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:871)
[2024-10-08T17:19:24.125Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:843)
[2024-10-08T17:19:24.125Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:821)
[2024-10-08T17:19:24.125Z] 	at ibm.jceplus.junit.base.BaseTestAES.encryptDecrypt(BaseTestAES.java:813)
[2024-10-08T17:19:24.125Z] 	at ibm.jceplus.junit.base.BaseTestAES.testAES_CBC_PKCS5Padding(BaseTestAES.java:155)
[2024-10-08T17:19:24.125Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-10-08T17:19:24.125Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-10-08T17:19:24.125Z] 	at junit.framework.TestCase.runTest(TestCase.java:177)
[2024-10-08T17:19:24.125Z] 	at junit.framework.TestCase.runBare(TestCase.java:142)
[2024-10-08T17:19:24.126Z] 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-10-08T17:19:24.126Z] 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-10-08T17:19:24.126Z] 	at junit.framework.TestResult.run(TestResult.java:125)
[2024-10-08T17:19:24.126Z] 	at junit.framework.TestCase.run(TestCase.java:130)
[2024-10-08T17:19:24.126Z] 	at junit.framework.TestSuite.runTest(TestSuite.java:241)
[2024-10-08T17:19:24.126Z] 	at junit.framework.TestSuite.run(TestSuite.java:236)
[2024-10-08T17:19:24.126Z] 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
[2024-10-08T17:19:24.126Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2024-10-08T17:19:24.126Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2024-10-08T17:19:24.126Z] 	at ibm.jceplus.junit.TestMultithread$2.call(TestMultithread.java:148)
[2024-10-08T17:19:24.126Z] 	at ibm.jceplus.junit.TestMultithread$2.call(TestMultithread.java:146)
[2024-10-08T17:19:24.126Z] 	at ibm.jceplus.junit.TestMultithread$1.run(TestMultithread.java:100)
[2024-10-08T17:19:24.126Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2024-10-08T17:19:24.126Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-10-08T17:19:24.126Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-10-08T17:19:24.126Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-10-08T17:19:24.126Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-10-08T17:19:24.126Z] Caused by: java.security.ProviderException: Failure in engineDoFinal
[2024-10-08T17:19:24.126Z] 	at openjceplus/com.ibm.crypto.plus.provider.OpenJCEPlus.providerException(OpenJCEPlus.java:1027)
[2024-10-08T17:19:24.126Z] 	at openjceplus/com.ibm.crypto.plus.provider.AESCipher.engineDoFinal(AESCipher.java:165)
[2024-10-08T17:19:24.126Z] 	at openjceplus/com.ibm.crypto.plus.provider.AESCipher.engineDoFinal(AESCipher.java:63)
[2024-10-08T17:19:24.126Z] 	... 28 more
[2024-10-08T17:19:24.126Z] Caused by: java.lang.ArrayIndexOutOfBoundsException
[2024-10-08T17:19:24.126Z] 	at java.base/java.lang.IndexOutOfBoundsException.<init>(IndexOutOfBoundsException.java:55)
[2024-10-08T17:19:24.126Z] 	at java.base/java.lang.ArrayIndexOutOfBoundsException.<init>(ArrayIndexOutOfBoundsException.java:53)
[2024-10-08T17:19:24.126Z] 	at openjceplus/com.ibm.crypto.plus.provider.AESCipher.unpad(AESCipher.java:557)
[2024-10-08T17:19:24.126Z] 	at openjceplus/com.ibm.crypto.plus.provider.AESCipher.engineDoFinal(AESCipher.java:135)

[2024-10-08T17:19:42.194Z] [ERROR] Crashed tests:
[2024-10-08T17:19:42.194Z] [ERROR] ibm.jceplus.junit.TestMultithread
[2024-10-08T17:19:42.194Z] [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[2024-10-08T17:19:42.195Z] [ERROR] Command was /bin/sh -c cd '/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_fips140_3_openjceplusfips/aqa-tests/TKG/../TKG/output_17284057609404/openJcePlusTests_0' && '/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_fips140_3_openjceplusfips/jdkbinary/j2sdk-image/bin/java' '--add-exports' 'openjceplus/com.ibm.crypto.plus.provider.ock=ALL-UNNAMED' '--add-exports' 'java.base/sun.security.util=ALL-UNNAMED' '-jar' '/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_fips140_3_openjceplusfips/aqa-tests/TKG/output_17284057609404/openJcePlusTests_0/target/surefire/surefirebooter-20241008094326392_3.jar' '/home/jenkins/workspace/Test_openjdk21_j9_extended.functional_s390x_linux_fips140_3_openjceplusfips/aqa-tests/TKG/output_17284057609404/openJcePlusTests_0/target/surefire' '2024-10-08T09-43-25_774-jvmRun1' 'surefire-20241008094326392_1tmp' 'surefire_0-20241008094326392_2tmp'
[2024-10-08T17:19:42.195Z] [ERROR] Error occurred in starting fork, check output in log
[2024-10-08T17:19:42.195Z] [ERROR] Process Exit Code: 255
[2024-10-08T17:19:42.195Z] [ERROR] Crashed tests:
[2024-10-08T17:19:42.195Z] [ERROR] ibm.jceplus.junit.TestMultithread

[2024-10-08T17:19:42.197Z] openJcePlusTests_0_FAILED
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44024/)

FYI @jasonkatonica

**Comment by jasonkatonica** [comment]
Hi @JasonFengJ9 We ( @KostasTsiounis ) recently made updates to the multithreaded tests to become thread safe. This update is not in this release so for the time being we can ignore any multi-threaded test failures. This update was made with https://github.com/IBM/OpenJCEPlus/pull/207

**Comment by jasonkatonica** [comment]
As per the above updates to multithreaded tests this issue should be resolved in the .49 release of Semeru. Closing this issue until further failures are found in the multithreaded tests running on the .49 level or higher of code.
