### ISSUE TITLE
Using zlibNX may cause ClassNotFoundException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20324]
Experienced the following problem on AIX 7.3 P10, which is configured to support zlibNX, and Semeru will use it be default. Disable using `-XX:-UseZlibNX` and it no longer occurs.
```
00:52:14  /home/jenkins/workspace/Test_openjdk23_j9_sanity.jck_ppc64_aix/jdkbinary/j2sdk-image/bin/java -cp ./bin/TestKitGen.jar org.openj9.envInfo.EnvDetector
00:52:14  Exception in thread "main" java.lang.NoClassDefFoundError: org.openj9.envInfo.MachineInfo
00:52:14  	at org.openj9.envInfo.EnvDetector.parseArgs(EnvDetector.java:32)
00:52:14  	at org.openj9.envInfo.EnvDetector.main(EnvDetector.java:28)
00:52:14  Caused by: java.lang.ClassNotFoundException: org.openj9.envInfo.MachineInfo
00:52:14  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:827)
00:52:14  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
00:52:14  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1099)
00:52:14  	... 2 more
```

Trying to look at the class with `javap` you get `unexpected end of file while reading org.openj9.envInfo.MachineInfo`.

jdk11, 17 are fine, this particular problem only occurs with jdk21, 23.

**Comment by pshipton** [comment]
There is an AIX ifix related to case TS017146010 which is supposed to fix it. Until the fix is part of a service pack, disable zlibNX by default. The command line option can still be used to enable it.

https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/858
https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/55
https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/209
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/396
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/823
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/768

Created doc issue 
https://github.com/eclipse-openj9/openj9-docs/issues/1426

**Comment by pshipton** [comment]
Although the default has been changed, we can keep this open until there is an AIX update with the fix and the default to enabled zlibNX restored.

**Comment by paulcheeseman** [comment]
This is the AIX APAR.

https://www.ibm.com/support/docview.wss?uid=isg1IJ52189

I believe the fix is available.

**Comment by pshipton** [comment]
The link I have to the AIX ifix for case TS017146010 shows it's expired.

**Comment by pshipton** [comment]
On a related topic, Paul mentioned that zlibNX may allocate over 100x more memory than the standard zlib library for every Inflater.

AIX said:
> The benefit of using zlibNX and accelerators depends on the type of the work load. zlibNX performs better when the size of the data set is huge.

**Comment by paulcheeseman** [comment]
Regarding zlibNX's memory usage, here's an example from a WebSphere Liberty environment. This information is based on aggregated AIX [debug malloc](https://www.ibm.com/docs/en/aix/7.3?topic=subsystem-debug-malloc-tool) data gathered after Liberty startup. The only difference between these runs was having zlibNX disabled/enabled.

**Standard zlib (`-XX:-UseZlibNX`)**

```
0.91 MB (133 allocations):
        0x0900000000055920 malloc_common_debugging
        0x0900000008724818 zcalloc
        0x0900000008729670 inflateInit2_
        0x0900000013a5c104 Java_java_util_zip_Inflater_init
```

**zlibNX (`-XX:+UseZlibNX`)**

```
104.25 MB (139 allocations):
        0x0900000000234eec malloc_common_debugging
        0x0900000001659b78 zcalloc
        0x090000000165f4b0 inflateInit2_
        0x090000000fbe5104 Java_java_util_zip_Inflater_init

17.38 MB (139 allocations):
        0x0900000000234eec malloc_common_debugging
        0x0900000001659b78 zcalloc
        0x090000000165f408 inflateInit2_
        0x090000000fbe5104 Java_java_util_zip_Inflater_init

0.96 MB (139 allocations):
        0x0900000000234eec malloc_common_debugging
        0x0900000001659b78 zcalloc
        0x090000000165f0e4 inflateInit2_
        0x090000000fbe5104 Java_java_util_zip_Inflater_init
```

So that's ~7KB per Inflater for standard zlib vs ~900KB for zlibNX.

The AIX team are actively working on reducing the footprint, but zlibNX will always use more memory than standard zlib.

This increase in footprint becomes significant when lots of Inflaters are opened simultaneously, for example during Liberty startup. In the environment this data was taken from, the brief spike in Inflaters during startup led to a footprint increase of several hundred MB when zlibNX was enabled (which persists after the allocations are freed unless [`MALLOCOPTIONS=disclaim`](https://www.ibm.com/docs/en/aix/7.3?topic=subsystem-malloc-disclaim) is set), and startup also took longer (44.4 seconds vs 28.8 seconds).
