### ISSUE TITLE
Build failed due to RejectedExecutionException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20338]
https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_linux_Nightly/344
```
18:03:50  [stderr] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@ee2dca7b[Not completed, task = javacserver.server.CompilerThreadPool$$Lambda/0x000000002c279b58@8ccf687f] rejected from java.util.concurrent.ThreadPoolExecutor@1dcee916[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 10]
18:03:50  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
18:03:50  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
18:03:50  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
18:03:50  [stderr] 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
18:03:50  [stderr] 	at javacserver.server.CompilerThreadPool.dispatchCompilation(CompilerThreadPool.java:49)
18:03:50  [stderr] 	at javacserver.server.Server.handleRequest(Server.java:211)
18:03:50  [stderr] 	at javacserver.server.Server.lambda$start$1(Server.java:173)
18:03:50  [stderr] 	at java.base/java.lang.Thread.run(Thread.java:1595)
18:03:50  CompileDemos.gmk:160: recipe for target '/home/jenkins/workspace/Build_JDK21_aarch64_linux_Nightly/build/linux-aarch64-server-release/support/demos/classes/jfc/CodePointIM/_the.BUILD_DEMO_CodePointIM_batch' failed
18:03:50  gmake[3]: *** [/home/jenkins/workspace/Build_JDK21_aarch64_linux_Nightly/build/linux-aarch64-server-release/support/demos/classes/jfc/CodePointIM/_the.BUILD_DEMO_CodePointIM_batch] Error 1
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_linux_Personal/444/consoleFull
```
15:00:35  ERROR: Build failed for target 'all' in configuration 'linux-aarch64-server-release' (exit code 2) 
15:00:35  
15:00:35  === Output from failing command(s) repeated here ===
15:00:35  * For target buildtools_tools_jigsaw_classes__the.BUILD_JIGSAW_TOOLS_batch:
15:00:35  [stderr] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6af42aba[Not completed, task = javacserver.server.CompilerThreadPool$$Lambda/0x0000000018251f10@99c81b05] rejected from java.util.concurrent.ThreadPoolExecutor@eeeffb29[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]
15:00:35  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
15:00:35  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
15:00:35  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
15:00:35  [stderr] 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
15:00:35  [stderr] 	at javacserver.server.CompilerThreadPool.dispatchCompilation(CompilerThreadPool.java:49)
15:00:35  [stderr] 	at javacserver.server.Server.handleRequest(Server.java:211)
15:00:35  [stderr] 	at javacserver.server.Server.lambda$start$1(Server.java:173)
15:00:35  [stderr] 	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_linux_Personal/536/consoleFull
```
16:44:18  === Output from failing command(s) repeated here ===
16:44:18  * For target support_demos_classes_jfc_CodePointIM__the.BUILD_DEMO_CodePointIM_batch:
16:44:18  [stderr] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@69cccf93[Not completed, task = javacserver.server.CompilerThreadPool$$Lambda/0x0000000000000000@7170e6c5] rejected from java.util.concurrent.ThreadPoolExecutor@524cf1d4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 10]
16:44:18  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
16:44:18  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
16:44:18  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
16:44:18  [stderr] 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
16:44:18  [stderr] 	at javacserver.server.CompilerThreadPool.dispatchCompilation(CompilerThreadPool.java:49)
16:44:18  [stderr] 	at javacserver.server.Server.handleRequest(Server.java:211)
16:44:18  [stderr] 	at javacserver.server.Server.lambda$start$1(Server.java:173)
16:44:18  [stderr] 	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK21_x86-64_linux_Nightly/559/
https://openj9-jenkins.osuosl.org/job/Build_JDK21_s390x_linux_OMR/378
