### ISSUE TITLE
OpenJDK java/util/concurrent/ConcurrentQueues/OfferRemoveLoops Some tests failed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20340]
0.48 testing
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Release_testList_2/21
java/util/concurrent/ConcurrentQueues/OfferRemoveLoops.java
```
06:01:44  STDERR:
06:01:44  LinkedBlockingQueue
06:01:44  LinkedBlockingQueue
06:01:44  LinkedBlockingDeque
06:01:44  LinkedBlockingDeque
06:01:44  Hung thread: scanner
06:01:44  java.base/jdk.internal.misc.Unsafe.park(Native Method)
06:01:44  java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
06:01:44  java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
06:01:44  java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
06:01:44  java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
06:01:44  java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
06:01:44  java.base/java.util.concurrent.LinkedBlockingDeque$AbstractItr.next(LinkedBlockingDeque.java:1091)
06:01:44  OfferRemoveLoops.checkNotContainsNull(OfferRemoveLoops.java:58)
06:01:44  OfferRemoveLoops$3.realRun(OfferRemoveLoops.java:148)
06:01:44  OfferRemoveLoops$1CheckedThread.run(OfferRemoveLoops.java:106)
06:01:44  ArrayBlockingQueue
06:01:44  PriorityBlockingQueue
06:01:44  ConcurrentLinkedDeque
06:01:44  ConcurrentLinkedQueue
06:01:44  LinkedTransferQueue
06:01:44  java.lang.AssertionError: Some tests failed
06:01:44  	at OfferRemoveLoops.instanceMain(OfferRemoveLoops.java:187)
06:01:44  	at OfferRemoveLoops.main(OfferRemoveLoops.java:183)
06:01:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:01:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:01:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:01:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
06:01:44  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
06:01:44  	at java.base/java.lang.Thread.run(Thread.java:839)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/340
Hung thread: offerer

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_OMR_testList_0/409
Hung thread: offerer
