### ISSUE TITLE
jdk24 java.lang.AssertionError: sun.security.util.ResourcesMgr (PD)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20351]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Personal_testList_0/6
jdk_lang
java/lang/Class/ProtectionDomainRace.java
```
14:43:27  java.lang.AssertionError: sun.security.util.ResourcesMgr (PD)
14:43:27  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.checkInjectedInvoker(MethodHandleImpl.java:1219)
14:43:27  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.makeInjectedInvoker(MethodHandleImpl.java:1120)
14:43:27  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1127)
14:43:27  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1124)
14:43:27  	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:235)
14:43:27  	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:217)
14:43:27  	at java.base/java.lang.ClassValue.get(ClassValue.java:123)
14:43:27  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.bindCallerWithInjectedInvoker(MethodHandleImpl.java:1099)
14:43:27  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.bindCaller(MethodHandleImpl.java:1087)
14:43:27  	at java.base/java.lang.invoke.MethodHandleImpl.bindCaller(MethodHandleImpl.java:1040)
14:43:27  	at java.base/java.lang.invoke.MethodHandles$Lookup.maybeBindCaller(MethodHandles.java:4134)
14:43:27  	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:4118)
14:43:27  	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:4062)
14:43:27  	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodForConstant(MethodHandles.java:4311)
14:43:27  	at java.base/java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:4259)
14:43:27  	at java.base/java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:634)
14:43:27  	at java.base/java.lang.invoke.MethodHandleResolver.sendResolveMethodHandle(MethodHandleResolver.java:297)
14:43:27  	at java.base/java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
14:43:27  	at java.base/java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:412)
14:43:27  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:186)
14:43:27  	at java.base/sun.security.util.ResourcesMgr.getBundle(ResourcesMgr.java:54)
14:43:27  	at java.base/sun.security.util.ResourcesMgr.getString(ResourcesMgr.java:40)
14:43:27  	at java.base/javax.security.auth.Subject.doAs(Subject.java:517)
14:43:27  	at ProtectionDomainRace.lambda$main$1(ProtectionDomainRace.java:66)
14:43:27  	at java.base/java.lang.Thread.run(Thread.java:1588)
```

**Comment by pshipton** [comment]
Temporarily exclude it via https://github.com/adoptium/aqa-tests/pull/5922

**Comment by keithc-ca** [comment]
This problem can still occur; see https://github.com/eclipse-openj9/openj9/pull/21073#pullrequestreview-2598751649.
