### ISSUE TITLE
jdk24 java/foreign/largestub/TestLargeStub IllegalArgumentException array length is not legal for long[] or double[]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20355]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Personal_testList_1/6
jdk_foreign_1
java/foreign/largestub/TestLargeStub.java
```
14:45:40  STARTED    TestLargeStub::testUpcall '[1] i4, 1'
14:45:40  java.lang.IllegalArgumentException: array length is not legal for long[] or double[]: 250
14:45:40  	at java.base/java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:182)
14:45:40  	at java.base/java.lang.invoke.MethodHandle.spreadArrayChecks(MethodHandle.java:1175)
14:45:40  	at java.base/java.lang.invoke.MethodHandle.asCollectorChecks(MethodHandle.java:1357)
14:45:40  	at java.base/java.lang.invoke.MethodHandle.asCollector(MethodHandle.java:1343)
14:45:40  	at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.permuteMH(InternalDowncallHandler.java:502)
14:45:40  	at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.getBoundMethodHandle(InternalDowncallHandler.java:476)
14:45:40  	at java.base/jdk.internal.foreign.abi.DowncallLinker.getBoundMethodHandle(DowncallLinker.java:47)
14:45:40  	at java.base/jdk.internal.foreign.abi.aarch64.CallArranger.arrangeDowncall(CallArranger.java:192)
14:45:40  	at java.base/jdk.internal.foreign.abi.aarch64.macos.MacOsAArch64Linker.arrangeDowncall(MacOsAArch64Linker.java:64)
14:45:40  	at java.base/jdk.internal.foreign.abi.AbstractLinker.lambda$downcallHandle0$0(AbstractLinker.java:115)
14:45:40  	at java.base/jdk.internal.foreign.abi.SoftReferenceCache$Node.get(SoftReferenceCache.java:49)
14:45:40  	at java.base/jdk.internal.foreign.abi.SoftReferenceCache.get(SoftReferenceCache.java:38)
14:45:40  	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle0(AbstractLinker.java:112)
14:45:40  	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle(AbstractLinker.java:101)
14:45:40  	at TestLargeStub.testUpcall(TestLargeStub.java:79)
14:45:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:579)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:186)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:186)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:186)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:807)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:583)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:573)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:270)
14:45:40  	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
14:45:40  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:583)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:573)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:270)
14:45:40  	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
14:45:40  	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
14:45:40  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:583)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:573)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
14:45:40  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
14:45:40  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:270)
14:45:40  	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
14:45:40  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
14:45:40  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
14:45:40  FAILED     TestLargeStub::testUpcall '[1] i4, 1'
```

**Comment by tajila** [comment]
@babsingh Please take a look

**Comment by keithc-ca** [comment]
> The current downcall mechanism is quite general as that was the simplest way to implement it for all possible types. We pass the args via JNI so we need to use an array to capture the args or else we need infinite natives for the infinite combinations of params. We had to convert the params to long because its the largest common type for all primitives.

Our mapping from multiple parameters to a single (or a small number of) arrays should allow for more parameters, not less. What am I missing?

**Comment by babsingh** [comment]
> What am I missing?

[MethodHandle.asCollector](https://docs.oracle.com/en/java/javase/21/docs//api/java.base/java/lang/invoke/MethodHandle.html#asCollector(int,java.lang.Class,int)) enforces the following rule from [JVM Spec 4.3.3 - Method Descriptors](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.3.3): `The number of parameter slots required by the method's descriptor must be less than 256`.

Since we are converting the arguments to an array of `long`s using [MethodHandle.asCollector](https://github.com/eclipse-openj9/openj9/blob/d471e57505e0ee65cf9fc6b5b0b5f7e88f201cc4/jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java#L643), the maximum number of elements that can be collected is 128, because each `long` occupies 2 slots, and the total number of slots must be less than 256.

**Comment by babsingh** [comment]
Closing since the PRs in https://github.com/eclipse-openj9/openj9/issues/20355#issuecomment-2575851451 have been merged.
