### ISSUE TITLE
harmony ChoiceCallbackTest testChoiceCallback_01 testMutable AssertionFailedError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20405]
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=94517975)
[Win64 Hammer Compressed Pointers] 80 Load_Level_2.harmony.5mins.Mode610
`-Xcompressedrefs -Xjit -Xgcpolicy:gencon`
win10x64cudavm1

30x grinder, only failed on the same machine

```
j> 17:54:23 20241023 17:54:22 <PrimarySimpleDriverorg.apache.harmony.auth.tests.javax.security.auth.callback.ChoiceCallbackTest216Defaul
t Invocant> ERROR: Test testChoiceCallback_01(org.apache.harmony.auth.tests.javax.security.auth.callback.ChoiceCallbackTest) failed
j> 17:54:23 Throwable trace:
j> 17:54:23 junit.framework.AssertionFailedError: expected:<[Ljava.lang.String;@3f95ad85> but was:<[Ljava.lang.String;@34e3327a>
j> 17:54:23     at junit.framework.Assert.fail(Assert.java:47)
j> 17:54:23     at junit.framework.Assert.failNotEquals(Assert.java:283)
j> 17:54:23     at junit.framework.Assert.assertEquals(Assert.java:64)
j> 17:54:23     at junit.framework.Assert.assertEquals(Assert.java:71)
j> 17:54:23     at org.apache.harmony.auth.tests.javax.security.auth.callback.ChoiceCallbackTest.testChoiceCallback_01(ChoiceCallbackTest.ja
```
```
j> 17:54:23 20241023 17:54:22 <PrimarySimpleDriverorg.apache.harmony.auth.tests.javax.security.auth.callback.ChoiceCallbackTest216Defaul
t Invocant> ERROR: Test testMutable(org.apache.harmony.auth.tests.javax.security.auth.callback.ChoiceCallbackTest) failed
j> 17:54:23 Throwable trace:
j> 17:54:23 junit.framework.AssertionFailedError: null
j> 17:54:23     at junit.framework.Assert.fail(Assert.java:47)
j> 17:54:23     at junit.framework.Assert.assertTrue(Assert.java:20)
j> 17:54:23     at junit.framework.Assert.assertFalse(Assert.java:34)
j> 17:54:23     at junit.framework.Assert.assertFalse(Assert.java:41)
j> 17:54:23     at org.apache.harmony.auth.tests.javax.security.auth.callback.ChoiceCallbackTest.testMutable(ChoiceCallbackTest.java:138)   
```

**Comment by pshipton** [comment]
This is internal issue 150715. The test should be excluded on every Windows machine. This machine is out of date.
