### ISSUE TITLE
UnsafeCopyMemoryTest throws exception when off-heap enabled

### ISSUE THREAD

**Issue by LinHu2016** [eclipse-openj9/openj9#20451]
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.functional_x86-64_linux_Personal_testList_0/558/consoleText

- test category,: sanity.functional
 
- test target name: J9vmTest_4
- OS/architecture):  all platforms

Optional info
-------------

- intermittent failure (yes|no):  No
- regression or new test:  only fail with new option "-XXgc:enableVirtualLargeObjectHeap"

Failure output (captured from console output)
```
[2024-09-25T19:20:28.338Z] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
[2024-09-25T19:20:28.338Z] 	at java.base/java.lang.reflect.Array.getByte(Array.java:122)
[2024-09-25T19:20:28.338Z] 	at java.base/java.lang.reflect.Array.getShort(Array.java:303)
[2024-09-25T19:20:28.339Z] 	at java.base/java.lang.reflect.Array.getInt(Array.java:219)
[2024-09-25T19:20:28.339Z] 	at java.base/java.lang.reflect.Array.getLong(Array.java:280)
[2024-09-25T19:20:28.339Z] 	at j9vm.test.unsafe.UnsafeCopyMemoryTest.testEqualRawMemoryAndArray(UnsafeCopyMemoryTest.java:272)
[2024-09-25T19:20:28.339Z] 	at j9vm.test.unsafe.UnsafeCopyMemoryTest.testCopyLargeArrayIntoRawMemory(UnsafeCopyMemoryTest.java:403)
[2024-09-25T19:20:28.339Z] 	at j9vm.test.unsafe.UnsafeCopyMemoryTest.main(UnsafeCopyMemoryTest.java:455)
[2024-09-25T19:20:28.339Z] non-zero exit value: 1
[2024-09-25T19:20:28.339Z] *** Test FAILED *** (j9vm.test.unsafe.UnsafeCopyMemoryTest)

```

**Comment by LinHu2016** [comment]
fix: https://github.com/eclipse-openj9/openj9/pull/20339
