### ISSUE TITLE
ValueTypes: JNIIsSameObject value types support

### ISSUE THREAD

**Issue by theresa-m** [eclipse-openj9/openj9#20512]
Test: runtime/valhalla/inlinetypes/TestJNIIsSameObject.java

```
java.lang.RuntimeException: assertTrue: expected true, was false
	at jdk.test.lib.Asserts.fail(Asserts.java:691)
	at jdk.test.lib.Asserts.assertTrue(Asserts.java:543)
	at jdk.test.lib.Asserts.assertTrue(Asserts.java:529)
	at TestJNIIsSameObject.main(TestJNIIsSameObject.java:62)
```

Related: https://github.com/eclipse-openj9/openj9/issues/13182

**Comment by theresa-m** [comment]
This was resolved by https://github.com/eclipse-openj9/openj9/pull/23817
