### ISSUE TITLE
jdk24 java/foreign/TestMappedHandshake AssertionError: expected [true] but found [false]

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#20527]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Personal_testList_2/4
jdk_foreign_1
java/foreign/TestMappedHandshake.java

```
10:05:43  test TestMappedHandshake.testHandshake(): failure
10:05:43  java.lang.AssertionError: expected [true] but found [false]
10:05:43  	at org.testng.Assert.fail(Assert.java:99)
10:05:43  	at org.testng.Assert.failNotEquals(Assert.java:1037)
10:05:43  	at org.testng.Assert.assertTrue(Assert.java:45)
10:05:43  	at org.testng.Assert.assertTrue(Assert.java:55)
10:05:43  	at TestMappedHandshake.testHandshake(TestMappedHandshake.java:90)
10:05:43  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:05:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:573)
10:05:43  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
10:05:43  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
10:05:43  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
10:05:43  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
10:05:43  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
10:05:43  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
10:05:43  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
10:05:43  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
10:05:43  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
10:05:43  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
10:05:43  	at org.testng.TestRunner.run(TestRunner.java:585)
10:05:43  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
10:05:43  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
10:05:43  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
10:05:43  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
10:05:43  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
10:05:43  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
10:05:43  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
10:05:43  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
10:05:43  	at org.testng.TestNG.runSuites(TestNG.java:1069)
10:05:43  	at org.testng.TestNG.run(TestNG.java:1037)
10:05:43  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
10:05:43  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
10:05:43  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:05:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:573)
10:05:43  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
10:05:43  	at java.base/java.lang.Thread.run(Thread.java:1588)
```

**Comment by babsingh** [comment]
Ran a 25x grinder: https://openj9-jenkins.osuosl.org/job/Grinder/3964. The test didn't fail in the grinder, indicating that the failure might be intermittent.

**Comment by babsingh** [comment]
Ran a 200x grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/46971. The failure couldn't be reproduced. Closing, please reopen if the failure is seen again.

**Comment by pshipton** [comment]
Another one, reopening.
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/20

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk24_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/22/ - [ubu24-aarch64-4](https://openj9-jenkins.osuosl.org/computer/ubu24-aarch64-4)

**Comment by babsingh** [comment]
This failure is also observed with the RI. For more details, see https://bugs.openjdk.org/browse/JDK-8348578. The issue is believed to be related to the test case, specifically the code snippet below.

An initial suggestion was to increase the timeout before termination (`MAX_EXECUTOR_WAIT_SECONDS`), as the current timeout may be insufficient on slower machines. However, it was decided to gather more data before implementing a fix. The RI will eventually address the issue.

In the meantime, these failures can be ignored, and the test does not need to be excluded since the failure is highly intermittent. This issue does not block JDK 24 and has been deferred to the next release.

```
TestMappedHandshake.testHandshake(TestMappedHandshake.java:90):
    assertTrue(accessExecutor.awaitTermination(MAX_EXECUTOR_WAIT_SECONDS, TimeUnit.SECONDS));
```

**Comment by pshipton** [comment]
@babsingh pls exclude the test anyway, there were 3 failures of this yesterday.

**Comment by babsingh** [comment]
Opened https://github.com/adoptium/aqa-tests/pull/5983 to exclude the test.
