### ISSUE TITLE
jdk_container_0_FAILED jdk/internal/platform/docker/TestSystemMetrics.java Test failed for - unified:io.stat->rios/wios: , expected [2], got [8]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20538]
**Failure link**
---
From internal [Test_openjdk11_j9_dev.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_dev.openjdk_aarch64_linux/35/) (ubu22-aarch64-4)

```**Java Version**
java version "11.0.25-beta" 2024-10-15
IBM Semeru Runtime Certified Edition 11.0.25+9-202411020107 (build 11.0.25-beta+9)
Eclipse OpenJ9 VM 11.0.25+9-202411020107 (build master-5439dcfe42, JRE 11 Linux aarch64-64-Bit Compressed References 20241102_726 (JIT enabled, AOT enabled)
OpenJ9   - 5439dcfe42
OMR      - 2c5b8df92
JCL      - e1067b53f3 based on jdk-11.0.25+9)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_container_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F726%2Fibm-semeru-certified-jdk_aarch64_linux_JDK11U_2024-11-02-01-00.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F726%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2024-11-02-01-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=sw.tool.docker&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=120&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=Dynamic) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-11-02T02:05:30.272Z] variation: NoOptions
[2024-11-02T02:05:30.272Z] JVM_OPTIONS:  -Xverbosegclog 

[2024-11-02T02:06:14.682Z] TEST: jdk/internal/platform/docker/TestSystemMetrics.java

[2024-11-02T02:06:14.696Z] STDERR:
[2024-11-02T02:06:14.696Z]  stdout: [inContainer = true
[2024-11-02T02:06:14.696Z] Exception in thread "main" java.lang.RuntimeException: Test failed for - unified:io.stat->rios/wios: , expected [2], got [8]
[2024-11-02T02:06:14.696Z] 	at jdk.test.lib.containers.cgroup.CgroupMetricsTester.fail(CgroupMetricsTester.java:71)
[2024-11-02T02:06:14.696Z] 	at jdk.test.lib.containers.cgroup.MetricsTesterCgroupV2.fail(MetricsTesterCgroupV2.java:147)
[2024-11-02T02:06:14.696Z] 	at jdk.test.lib.containers.cgroup.MetricsTesterCgroupV2.testIOStat(MetricsTesterCgroupV2.java:451)
[2024-11-02T02:06:14.696Z] 	at jdk.test.lib.containers.cgroup.MetricsTesterCgroupV2.testMisc(MetricsTesterCgroupV2.java:443)
[2024-11-02T02:06:14.697Z] 	at jdk.test.lib.containers.cgroup.MetricsTester.testAll(MetricsTester.java:71)
[2024-11-02T02:06:14.697Z] 	at jdk.test.lib.containers.cgroup.MetricsTester.main(MetricsTester.java:89)
[2024-11-02T02:06:14.697Z] ];
[2024-11-02T02:06:14.697Z]  stderr: []
[2024-11-02T02:06:14.697Z]  exitValue = 1

[2024-11-02T02:06:14.697Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
[2024-11-02T02:06:14.697Z] --------------------------------------------------
[2024-11-02T02:06:14.697Z] Test results: passed: 6; failed: 1
[2024-11-02T02:06:29.250Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_17305131295540/jdk_container_0/report/html/report.html
[2024-11-02T02:06:29.250Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_dev.openjdk_aarch64_linux/aqa-tests/TKG/output_17305131295540/jdk_container_0/work
[2024-11-02T02:06:29.250Z] Error: Some tests failed or other problems occurred.
[2024-11-02T02:06:29.250Z] -----------------------------------
[2024-11-02T02:06:29.250Z] jdk_container_0_FAILED
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44775/) - 5/50 failed

**Comment by babsingh** [comment]
This issue is no longer observed. No failures were encountered in a 50x Grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/46835. Closing this issue. Please reopen it if the problem reoccurs.
