### ISSUE TITLE
JDK24 serviceability_jvmti_j9_0_FAILED serviceability/jvmti/vthread/CheckHiddenFrames/CheckHiddenFrames.java RuntimeException: CheckHiddenFrames failed!

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20541]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/29/consoleFull)(`ubu22-aarch64-5`):
```
16:23:10  openjdk version "24-internal" 2025-03-18
16:23:10  OpenJDK Runtime Environment (build 24-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
16:23:10  Eclipse OpenJ9 VM (build master-24c86c0ca8b, JRE 24 Linux aarch64-64-Bit Compressed References 20241106_129 (JIT enabled, AOT enabled)
16:23:10  OpenJ9   - 24c86c0ca8b
16:23:10  OMR      - 6fa180614ec
16:23:10  JCL      - 5a723c02858 based on jdk-24+22)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_security3_0,jdk_security3_1,jdk_vector_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F129%2FOpenJ9-JDKnext-aarch64_linux-20241106-200425.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F129%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=24c86c0ca8be30ff27498847e2e4608a7f2d8c49&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
16:24:37  ===============================================
16:24:37  Running test serviceability_jvmti_j9_0 ...
16:24:37  ===============================================
16:24:37  serviceability_jvmti_j9_0 Start Time: Wed Nov  6 21:24:36 2024 Epoch Time (ms): 1730928276459
16:24:37  variation: Mode150
16:24:37  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

16:28:27  TEST: serviceability/jvmti/vthread/CheckHiddenFrames/CheckHiddenFrames.java

16:28:27  Failed: GetStackTrace returned info for frame expected to be hidden: frame[0]=yield0
16:28:27  Failed: GetStackTrace returned info for frame expected to be hidden: frame[1]=yield
16:28:27  STDERR:
16:28:27  java.lang.RuntimeException: CheckHiddenFrames failed!
16:28:27  	at CheckHiddenFrames.main(CheckHiddenFrames.java:47)
16:28:27  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
16:28:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:573)
16:28:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
16:28:27  	at java.base/java.lang.Thread.run(Thread.java:1588)
16:28:27  
16:28:27  JavaTest Message: Test threw exception: java.lang.RuntimeException: CheckHiddenFrames failed!

16:29:36  serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44777/) - all failed

**Comment by thallium** [comment]
I'll look into this.

**Comment by thallium** [comment]
The author of the test [stated](https://github.com/openjdk/jdk/pull/21397#issuecomment-2398025342) that the `yield()` and `yield0()` should also have the `@JvmtiMountTransition` annotation thus will not appear in the JVMTI stacktrace. Do we want to match the behaviour as well?

**Comment by tajila** [comment]
> The author of the test https://github.com/openjdk/jdk/pull/21397#issuecomment-2398025342 that the yield() and yield0() should also have the @JvmtiMountTransition annotation thus will not appear in the JVMTI stacktrace. Do we want to match the behaviour as well?

Yes please add that

**Comment by thallium** [comment]
@babsingh we also need to skip JvmtiMountTransition frames in `jvmtiGetFrameLocation()`. Can I just use `jvmtiInternalGetStackTraceIterator` as frame walk function?

**Comment by babsingh** [comment]
`genericFrameIterator` skips `JvmtiMountTransition` frames and is more lightweight than `jvmtiInternalGetStackTraceIterator`. Can you use `genericFrameIterator` instead?

**Comment by thallium** [comment]
Yeah for sure, I didn't notice `genericFrameIterator`.

**Comment by thallium** [comment]
Actually we might have to change the stack walker code. The current problem is that decrementing `walkState->skipCount` and incrementing `walkState->framesWalked` happens before calling `frameWalkFunction` therefore walking a `JvmtiMountTransition` frame will still result in `walkState->skipCount`  and `walkState->framesWalked` being changes. So I think handling of `JvmtiMountTransition` frames should be in the stack walker code rather than in `frameWalkFunction`. Does this sound good to you @gacholio?

**Comment by gacholio** [comment]
> Does this sound good

Definitely not. Can you please point me at the iterator code?

**Comment by thallium** [comment]
https://github.com/eclipse-openj9/openj9/blob/master/runtime/jvmti/jvmtiHelpers.cpp#L2089 If we don't want to modify stack walker code, I think we will need to call stack walker twice to skip the correct number of frames.

**Comment by gacholio** [comment]
Can you please summarize the issue as you see it and the 2 walk solution you are proposing?

**Comment by thallium** [comment]
The issue is that frames with `JvmtiMountTransition` annotation need to be skipped in JVMTI stacktrace. Currently JVMTI `GetFrameLocation(..., jint depth, ...)` will not return correct frame if there is any `JvmtiMountTransition` frame in the stack. This is because the implementation of `GetFrameLocation` sets `walkState.skipCount = depth` therefore `JvmtiMountTransition` frames will be skipped and exhaust `walkState.skipCount`.

A solution I can think of without modifying stack walker code is to firstly walk the stack with `genericFrameIterator` to get the number of `JvmtiMountTransition` frames and add it to `walkState.skipCount` for the second walk.

**Comment by gacholio** [comment]
I haven't looked at this in detail, but above you mention the issue that counts are adjusted before the callback fires. Can you use this knowledge in the callback? If you really know what you're doing, you could adjust the count values in the callback, though this would generally be discouraged.

Niote that skipCount applies only to the top frames on the stack, so I doubt it could be used to skip transition frames that I assume aren't necessarily all on top of stack.

**Comment by gacholio** [comment]
I don't understand why it would be difficult to skip the marked frames.

**Comment by thallium** [comment]
> but above you mention the issue that counts are adjusted before the callback fires

This is only part of the problem. The bigger issue is that if `walkState.skipCount` is specified by user we will get incorrect result. For example, let's say the current stack looks like:
```
Transition Frame
Frame 1
Frame 2
Frame 3
```

If the skip count is set to 2, we will get Frame 2 as result but the expected frame is Frame 3. I don't think we can do anything in the callback to account for this because the Transition Frame is simply skipped without calling the callback. So we either have to do a first walk to know the number of transition frames and add it to the skip count of the second walk (assuming transition frames are always on the top of the stack, @babsingh can you confirm?), or handle transition frames in stack walker.

**Comment by gacholio** [comment]
Ah, so you think the skipping should only take unmarked frames into account. The callback will not fire for skipped frames, so I begin to see the issue.

**Comment by gacholio** [comment]
In general, skipCount is used to remove implementation-specific frames from consideration during stack walks (for example, skipping the top frame which is the native implementing whatever is doing the walking).
