### ISSUE TITLE
InternalError: SIGBUS trying to run test

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20540]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/60 - [mac12-x86-1](https://jdk_lang_1
openj9-jenkins.osuosl.org/computer/mac12-x86-1)
java/lang/invoke/MethodHandles/TestTableSwitch.java
```
03:33:35  java.lang.InternalError: SIGBUS
03:33:35  	at java.base/java.lang.String.indexOf(String.java)
03:33:35  	at java.base/sun.net.www.protocol.jar.Handler.parseURL(Handler.java:138)
03:33:35  	at java.base/java.net.URL.<init>(URL.java:801)
03:33:35  	at java.base/java.net.URL.<init>(URL.java:654)
03:33:35  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.checkResource(URLClassPath.java:946)
03:33:35  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getResource(URLClassPath.java:1010)
03:33:35  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:418)
03:33:35  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:958)
03:33:35  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
03:33:35  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
03:33:35  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
03:33:35  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1099)
03:33:35  	at org.testng.internal.Invoker.<init>(Invoker.java:42)
03:33:35  	at org.testng.TestRunner.init(TestRunner.java:276)
03:33:35  	at org.testng.TestRunner.<init>(TestRunner.java:180)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/90 - [mac12-x86-1](https://openj9-jenkins.osuosl.org/computer/mac12-x86-1)
jdk_lang_1
java/lang/StackWalker/SanityTest.java
```
04:19:58  org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
04:19:58  	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
04:19:58  	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
04:19:58  	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
04:19:58  	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
04:19:58  	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
04:19:58  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
04:19:58  	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
04:19:58  	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:142)
04:19:58  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
04:19:58  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
04:19:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
04:19:58  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
04:19:58  	at java.base/java.lang.Thread.run(Thread.java:1587)
04:19:58  Caused by: java.lang.InternalError: SIGBUS
04:19:58  	at java.base/java.lang.String.indexOf(String.java)
04:19:58  	at java.base/sun.net.www.protocol.jar.Handler.parseURL(Handler.java:138)
04:19:58  	at java.base/java.net.URL.<init>(URL.java:801)
04:19:58  	at java.base/java.net.URL.<init>(URL.java:654)
04:19:58  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.checkResource(URLClassPath.java:946)
04:19:58  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getResource(URLClassPath.java:1010)
04:19:58  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:418)
04:19:58  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:958)
04:19:58  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
04:19:58  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
04:19:58  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
04:19:58  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1098)
04:19:58  	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.<clinit>(DiscoverySelectorResolver.java:35)
04:19:58  	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
04:19:58  	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
04:19:58  	... 12 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_mac_Release_testList_2/13
jdk_util_1
java/util/logging/LogRecordThreadIdTest.java
```
00:26:08  java.lang.InternalError: SIGBUS
00:26:08  	at java.base/java.lang.StringLatin1.indexOf(StringLatin1.java)
00:26:08  	at java.base/java.lang.String.indexOf(String.java:3308)
00:26:08  	at java.base/sun.net.www.protocol.jar.Handler.parseURL(Handler.java:140)
00:26:08  	at java.base/java.net.URL.<init>(URL.java:764)
00:26:08  	at java.base/java.net.URL.<init>(URL.java:630)
00:26:08  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.createResource(URLClassPath.java:826)
00:26:08  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getResource(URLClassPath.java:887)
00:26:08  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:432)
00:26:08  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:876)
00:26:08  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:794)
00:26:08  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:752)
00:26:08  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1042)
00:26:08  	at org.testng.internal.Systematiser.getComparator(Systematiser.java:65)
00:26:08  	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
00:26:08  	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
00:26:08  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
00:26:08  	at org.testng.TestNG.runSuites(TestNG.java:1069)
00:26:08  	at org.testng.TestNG.run(TestNG.java:1037)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk25_j9_sanity.openjdk_x86-64_mac_Release_testList_2/47 - [mac15-x86-2](https://openj9-jenkins.osuosl.org/computer/mac15-x86-2)
jdk_util_other_1
java/util/prefs/SerializeExceptions.java
```
11:23:52  java.lang.InternalError: SIGBUS
11:23:52  	at java.base/java.lang.StringLatin1.indexOf(StringLatin1.java)
11:23:52  	at java.base/java.lang.String.indexOf(String.java:3308)
11:23:52  	at java.base/sun.net.www.protocol.jar.Handler.parseURL(Handler.java:140)
11:23:52  	at java.base/java.net.URL.<init>(URL.java:764)
11:23:52  	at java.base/java.net.URL.<init>(URL.java:630)
11:23:52  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.createResource(URLClassPath.java:826)
11:23:52  	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getResource(URLClassPath.java:887)
11:23:52  	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:432)
11:23:52  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:876)
11:23:52  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:794)
11:23:52  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:752)
11:23:52  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1053)
11:23:52  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:305)
```
