### ISSUE TITLE
JCL_Test_0 failed in VT standard build

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#20576]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_linux_vt_standard_Personal_testList_0/15/

```
15:12:30  FAILED: test_getModifiers_classTypes
15:12:30  java.lang.AssertionError: One or more tests failed:
15:12:30  Incorrect modifiers for SyntheticClass. Expected <4129>, Actual <4097>.
15:12:30  
15:12:30  	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.openj9.test.java.lang.Test_Class.test_getModifiers_classTypes(Test_Class.java:1043) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_aarch64_linux_vt_standard_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
15:12:30  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) from jrt:/java.base
15:12:30  	at java.base/java.lang.reflect.Method.invoke(Method.java:573) from jrt:/java.base
15:12:30  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
15:12:30  	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@12441d7a(file:/home/jenkins/testDependency/lib/testng.jar)
```

**Comment by hangshao0** [comment]
The test needs to be updated. I will create a PR for that.
