### ISSUE TITLE
Jep397Tests_testSubClassOfSealedSuperFromDifferentPackageInSameUnamedModule_0 failed in VT_standard build

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#20575]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_linux_vt_standard_Personal_testList_0/15/

```
15:10:50  FAILED: test_subClassInTheDifferentPackageFromSealedSuperClass
15:10:50  org.testng.TestException: 
15:10:50  Expected exception of type class java.lang.IncompatibleClassChangeError but got java.lang.UnsupportedClassVersionError: JVMCFRE201E version 68.65535 of class org/openj9/test/util/VersionCheck is a preview version but preview is not enabled, please enable it with --enable-preview; offset=6
15:10:50  	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
15:10:50  	at org.testng.internal.Invoker.considerExceptions(Invoker.java:1129)
15:10:50  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
15:10:50  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
15:10:50  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
15:10:50  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:10:50  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:10:50  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
15:10:50  	at org.testng.TestRunner.run(TestRunner.java:505)
15:10:50  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
15:10:50  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
15:10:50  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
15:10:50  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
15:10:50  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:10:50  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
15:10:50  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
15:10:50  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
15:10:50  	at org.testng.TestNG.runSuites(TestNG.java:1049)
15:10:50  	at org.testng.TestNG.run(TestNG.java:1017)
15:10:50  	at org.testng.TestNG.privateMain(TestNG.java:1354)
15:10:50  	at org.testng.TestNG.main(TestNG.java:1323)
15:10:50  Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE201E version 68.65535 of class org/openj9/test/util/VersionCheck is a preview version but preview is not enabled, please enable it with --enable-preview; offset=6
15:10:50  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
15:10:50  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472)
15:10:50  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:433)
15:10:50  	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
15:10:50  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
15:10:50  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1101)
15:10:50  	at org.openj9.test.utilities.SealedClassGenerator.<clinit>(SealedClassGenerator.java:31)
15:10:50  	at org.openj9.test.java.lang.Test_SubClass.test_subClassInTheDifferentPackageFromSealedSuperClass(Test_SubClass.java:46)
15:10:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:10:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:573)
15:10:50  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
15:10:50  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
15:10:50  	... 18 more
15:10:50  
15:10:50  FAILED: test_subClassInTheDifferentPackageFromSealedSuperInterface
15:10:50  org.testng.TestException: 
15:10:50  Expected exception of type class java.lang.IncompatibleClassChangeError but got java.lang.NoClassDefFoundError: org.openj9.test.utilities.SealedClassGenerator (initialization failure)
15:10:50  	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
15:10:50  	at org.testng.internal.Invoker.considerExceptions(Invoker.java:1129)
15:10:50  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
15:10:50  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
15:10:50  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
15:10:50  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:10:50  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:10:50  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
15:10:50  	at org.testng.TestRunner.run(TestRunner.java:505)
15:10:50  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
15:10:50  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
15:10:50  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
15:10:50  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
15:10:50  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:10:50  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
15:10:50  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
15:10:50  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
15:10:50  	at org.testng.TestNG.runSuites(TestNG.java:1049)
15:10:50  	at org.testng.TestNG.run(TestNG.java:1017)
15:10:50  	at org.testng.TestNG.privateMain(TestNG.java:1354)
15:10:50  	at org.testng.TestNG.main(TestNG.java:1323)
15:10:50  Caused by: java.lang.NoClassDefFoundError: org.openj9.test.utilities.SealedClassGenerator (initialization failure)
15:10:50  	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:149)
15:10:50  	at org.openj9.test.java.lang.Test_SubClass.test_subClassInTheDifferentPackageFromSealedSuperInterface(Test_SubClass.java:54)
15:10:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
15:10:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:573)
15:10:50  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
15:10:50  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
15:10:50  	... 18 more
15:10:50  Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE201E version 68.65535 of class org/openj9/test/util/VersionCheck is a preview version but preview is not enabled, please enable it with --enable-preview; offset=6
15:10:50  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
15:10:50  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472)
15:10:50  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:433)
15:10:50  	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
15:10:50  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
15:10:50  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
15:10:50  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1101)
15:10:50  	at org.openj9.test.utilities.SealedClassGenerator.<clinit>(SealedClassGenerator.java:31)
15:10:50  	at org.openj9.test.java.lang.Test_SubClass.test_subClassInTheDifferentPackageFromSealedSuperClass(Test_SubClass.java:46)
15:10:50  	... 22 more
15:10:50  
15:10:50  
15:10:50  ===============================================
15:10:50      Jep397Tests_testSubClassOfSealedSuperFromDifferentPackageInSameUnamedModule
15:10:50      Tests run: 2, Failures: 2, Skips: 0
15:10:50  ===============================================
```

**Comment by hangshao0** [comment]
Test `Jep397Tests_testSubClassOfSealedSuperFromDifferentModule_0` also failed the same way.
