### ISSUE TITLE
Re-enable openjdk test - jdk_jmx

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#20587]
jdk_jmx got excluded as part of the general exclude a while back via https://github.com/eclipse-openj9/openj9/issues/10757.

https://github.com/adoptium/aqa-tests/blob/a498becc695f7bdeaa7c4b3752c827e65aa7e123/openjdk/playlist.xml#L1620

My [limited testing](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44882/) on JDK11 xlinux passed 244 testes and 4 failed. We should look into re-enabling this test.

```
# TESTCASES RESULTS SUMMARY: passed: 244; failed: 3; error: 1; skipped: 0 
1..1
not ok 1 - jdk_jmx_0
  ---
    output:
      |
        Failed test cases: 
        TEST: javax/management/MBeanServer/OldMBeanServerTest.java
        TEST: javax/management/mxbean/LeakTest.java
        TEST: javax/management/remote/mandatory/notif/ListenerScaleTest.java
        TEST: javax/management/security/HashedPasswordFileTest.java
        Test results: passed: 244; failed: 3; error: 1
    duration_ms: 368171
  ...
```

**Comment by llxia** [comment]
For `Error evaluating expression: invalid boolean value: `null' for expression `vm.opt.final.ClassUnloading'`,  https://github.com/fengxue-IS/openj9-openjdk-jdk11/blob/openj9/closed/test/jtreg-ext/requires/OpenJ9PropsExt.java will be updated. Similar to https://github.com/fengxue-IS/openj9-openjdk-jdk19/blob/openj9/closed/test/jtreg-ext/requires/OpenJ9PropsExt.java#L55C13-L55C61

**Comment by llxia** [comment]
@pshipton, could you look at the other 3 test failures in [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44882/testReport/)? They look like real failures to me.
`jdk_jmx` passed in hotspot: https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2/28/testReport/

> TEST: javax/management/MBeanServer/OldMBeanServerTest.java

```
testPlatformMBeanServer: got exception javax.management.AttributeNotFoundException
javax.management.AttributeNotFoundException: Write-only attribute: DumpOptions
	at java.management/com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:81)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
	at java.management/javax.management.StandardMBean.getAttribute(StandardMBean.java:372)
	at OldMBeanServerTest$OldMBeanServer.getAttribute(OldMBeanServerTest.java:610)
	at OldMBeanServerTest.printAttrs(OldMBeanServerTest.java:358)
	at OldMBeanServerTest.testPlatformMBeanServer(OldMBeanServerTest.java:340)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
	at OldMBeanServerTest.runTests(OldMBeanServerTest.java:189)
	at OldMBeanServerTest.main(OldMBeanServerTest.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:835)
```
     
> TEST: javax/management/remote/mandatory/notif/ListenerScaleTest.java

```
java.lang.NullPointerException
	at jdk.test.lib.Platform.isDebugBuild(Platform.java:185)
	at ListenerScaleTest.main(ListenerScaleTest.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:835)

JavaTest Message: Test threw exception: java.lang.NullPointerException
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.NullPointerException
```

> TEST: javax/management/security/HashedPasswordFileTest.java

```
Execution failed: `main' threw exception: java.lang.Exception: failures: 2    

```

**Comment by llxia** [comment]
> TEST: javax/management/remote/mandatory/notif/ListenerScaleTest.java

may relate to https://github.com/eclipse-openj9/openj9/issues/20534.

Since the fix was delivered 3 days ago, [rerun with the latest SDK](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44956/console)

**Comment by pshipton** [comment]
Re https://github.com/eclipse-openj9/openj9/issues/20587#issuecomment-2473844071, added the missing `vm.opt.final.ClassUnloading` flag for jdk11 & 17.

**Comment by pshipton** [comment]
HashedPasswordFileTest.java needs to be excluded for OpenJ9. OpenJ9 doesn't implement Perf.
```
16:34:26  [TestApp] Exception in thread "main" java.lang.UnsupportedOperationException
16:34:26  [TestApp] 	at java.base/jdk.internal.perf.Perf.attach(Native Method)
16:34:26  [TestApp] 	at java.base/jdk.internal.perf.Perf.attachImpl(Perf.java:272)
16:34:26  [TestApp] 	at java.base/jdk.internal.perf.Perf.attach(Perf.java:202)
16:34:26  [TestApp] 	at jdk.management.agent/jdk.internal.agent.ConnectorAddressLink.importRemoteFrom(ConnectorAddressLink.java:203)
16:34:26  [TestApp] 	at TestApp.main(HashedPasswordFileTest.java:503)
```

**Comment by pshipton** [comment]
The second PR
https://github.com/eclipse-openj9/openj9/pull/20605

**Comment by pshipton** [comment]
Opened https://github.com/eclipse-openj9/openj9/issues/20607 for the next failure. If you want to enable jdk_jmx, pls exclude javax/management/MBeanServer/OldMBeanServerTest.java on the jfr platforms (currently alinux, xlinux) until it's fixed.

**Comment by pshipton** [comment]
Setting `jfr.unsupported.vm` to `true` was done via https://github.com/eclipse-openj9/openj9/pull/20631

**Comment by llxia** [comment]
I ran the test on all platforms with the latest JDK11. All passed except windows:

```
00:03:12.576  openjdk version "11.0.25-internal" 2024-10-15
00:03:12.576  OpenJDK Runtime Environment (build 11.0.25-internal+0-adhoc.jenkins.buildjdk11x86-64windowsnightly)
00:03:12.576  Eclipse OpenJ9 VM (build master-2583a83f213, JRE 11 Windows Server 2019 amd64-64-Bit Compressed References 20241113_908 (JIT enabled, AOT enabled)
00:03:12.576  OpenJ9   - 2583a83f213
00:03:12.576  OMR      - 3da49aa3aae
00:03:12.576  JCL      - 3ba776f9840 based on jdk-11.0.25+9)
```

[Parent job](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45414/)
[Windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45422/testReport/) - Noticed `
javax.management.AttributeNotFoundException: Write-only attribute: DumpOptions` error on Windows

@pshipton could you take a look?

**Comment by pshipton** [comment]
I think your Windows build is too old. The fix is merged on the 20th.  https://github.com/eclipse-openj9/openj9/pull/20604

**Comment by pshipton** [comment]
If this is an external OpenJ9 build, we lost all the Windows build machines some time ago, there are no recent Windows builds.
