### ISSUE TITLE
jfr.FlightRecorderMXBean.getEventTypes Could not access event handler

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20607]
Related to https://github.com/eclipse-openj9/openj9/issues/20587
jdk_jmx
javax/management/MBeanServer/OldMBeanServerTest.java
```
jdk.management.jfr:type=FlightRecorder:
  Configurations = [Ljavax.management.openmbean.CompositeData;@597096d8
testPlatformMBeanServer: got exception java.lang.InternalError
java.lang.InternalError: Could not access event handler
        at jdk.jfr/jdk.jfr.internal.Utils.getHandler(Utils.java:323)
        at jdk.jfr/jdk.jfr.internal.MetadataRepository.getHandler(MetadataRepository.java:171)
        at jdk.jfr/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:132)
        at jdk.jfr/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:127)
        at jdk.jfr/jdk.jfr.internal.SecuritySupport.lambda$registerEvent$2(SecuritySupport.java:284)
        at jdk.jfr/jdk.jfr.internal.SecuritySupport$2.run(SecuritySupport.java:210)
        at jdk.jfr/jdk.jfr.internal.SecuritySupport$2.run(SecuritySupport.java:207)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:886)
        at jdk.jfr/jdk.jfr.internal.SecuritySupport.doPrivileged(SecuritySupport.java:207)
        at jdk.jfr/jdk.jfr.internal.SecuritySupport.registerEvent(SecuritySupport.java:284)
        at jdk.jfr/jdk.jfr.internal.instrument.JDKEvents.initialize(JDKEvents.java:110)
        at jdk.jfr/jdk.jfr.internal.management.ManagementSupport.getEventTypes(ManagementSupport.java:77)
        at jdk.management.jfr/jdk.management.jfr.FlightRecorderMXBeanImpl$1.run(FlightRecorderMXBeanImpl.java:190)
        at jdk.management.jfr/jdk.management.jfr.FlightRecorderMXBeanImpl$1.run(FlightRecorderMXBeanImpl.java:187)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:886)
        at jdk.management.jfr/jdk.management.jfr.FlightRecorderMXBeanImpl.getEventTypes(FlightRecorderMXBeanImpl.java:187)
```

**Comment by pshipton** [comment]
@tajila pls take a look. We are looking to enable jdk_jmx tests and this will be the remaining failure. We can exclude the test until it's fixed.

**Comment by pshipton** [comment]
Could you fix the FlightRecorderMXBean and Impl to remove the methods that don't work? Presumably some of it works since it's been added, or the whole thing could be removed..

**Comment by tajila** [comment]
I think we can disable it by setting `-Djfr.unsupported.vm=true`. Il try it with one of the tests

**Comment by tajila** [comment]
Is `javax/management/MBeanServer/OldMBeanServerTest.java` the right test? I didnt see the JFR failure above

**Comment by pshipton** [comment]
Yes it is. Are you running on a JVM with jfr enabled? I was running on jdk11, if that matters.

**Comment by pshipton** [comment]
I can still recreate the failure, and I confirm that with `-Djfr.unsupported.vm=true` the test passes.

**Comment by tajila** [comment]
> I can still recreate the failure, and I confirm that with -Djfr.unsupported.vm=true the test passes.

Okay, thanks for confirming
