### ISSUE TITLE
cmdLineTester_criu_nonPortableRestore_jdk_crac failed in VT_standard build

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#20627]
Failed in an internal [build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/224/tapResults/):

```
Testing: jdk.crac - jcmd request checkpoint via JDK.checkpoint
Test start time: 2024/11/18 09:02:54 Pacific Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/cracScript.sh /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/jdkbinary/j2sdk-image/bin/java " -Xgcpolicy:optthruput  --add-exports=java.base/openj9.internal.criu=ALL-UNNAMED -XX:CRaCCheckpointTo=./cpData" /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/../../testDependency/lib/jcommander.jar org.openj9.criu.TestJDKCRAC JDK.checkpoint 1 false false
Time spent starting: 6 milliseconds
Time spent executing: 4049 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/jdkbinary/j2sdk-image/bin/java  -Xgcpolicy:optthruput  --add-exports=java.base/openj9.internal.criu=ALL-UNNAMED -XX:CRaCCheckpointTo=./cpData -cp /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criu.jar:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/../../testDependency/lib/testng.jar:/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_1/../../testDependency/lib/jcommander.jar org.openj9.criu.TestJDKCRAC JDK.checkpoint 1
 [OUT] Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE201E version 68.65535 of class org/openj9/test/util/StringUtilities is a preview version but preview is not enabled, please enable it with --enable-preview; offset=6
 [OUT] 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472)
 [OUT] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:433)
 [OUT] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
 [OUT] 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
 [OUT] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
 [OUT] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
 [OUT] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
 [OUT] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
 [OUT] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1101)
 [OUT] 	at org.openj9.criu.TestJDKCRAC.testJcmdCheckpoint(TestJDKCRAC.java:105)
 [OUT] 	at org.openj9.criu.TestJDKCRAC.main(TestJDKCRAC.java:68)
 [OUT] initiate restore
 [OUT] Removed test output files
 [OUT] finished script
>> Success condition was not found: [Output match: JVM checkpoint requested]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
>> Failure condition was not found: [Output match: User requested Java dump using]
>> Failure condition was not found: [Output match: AOT load and compilation disabled post restore]
```

**Comment by hangshao0** [comment]
Similar to https://github.com/eclipse-openj9/openj9/issues/20575.
