### ISSUE TITLE
serviceability_jvmti_j9_0 FAILED serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java 'OutOfMemoryError' missing from stdout/stderr

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20676]
**Failure link**
---
From internal [Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_1/137/) (rtj-rhel8le-rtp-test-8kd6c-1)

```**Java Version**
java version "21.0.6-beta" 2025-01-21
IBM Semeru Runtime Certified Edition 21.0.6+4-202411231604 (build 21.0.6-beta+4-202411231604)
Eclipse OpenJ9 VM 21.0.6+4-202411231604 (build master-3da9d2f0ba, JRE 21 Linux ppc64le-64-Bit Compressed References 20241123_312 (JIT enabled, AOT enabled)
OpenJ9   - 3da9d2f0ba
OMR      - 32ef86c51
JCL      - 8967a7c62 based on jdk-21.0.6+4)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=serviceability_jvmti_j9_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_extended.openjdk_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F312%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK21U_2024-11-23-16-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F312%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK21U_2024-11-23-16-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=172&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-11-23T17:10:20.104Z] variation: Mode150
[2024-11-23T17:10:20.104Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-11-23T17:11:54.865Z] TEST: serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java

[2024-11-23T17:11:54.866Z]  exitValue = 134
[2024-11-23T17:11:54.866Z] 
[2024-11-23T17:11:54.866Z] java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2024-11-23T17:11:54.866Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:231)
[2024-11-23T17:11:54.866Z] 	at TestUnloadedClass.main(TestUnloadedClass.java:53)
[2024-11-23T17:11:54.866Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-11-23T17:11:54.866Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-11-23T17:11:54.866Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-11-23T17:11:54.866Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-11-23T17:11:54.866Z] 
[2024-11-23T17:11:54.866Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2024-11-23T17:11:54.866Z] JavaTest Message: shutting down test
[2024-11-23T17:11:54.866Z] 
[2024-11-23T17:11:54.866Z] 
[2024-11-23T17:11:54.866Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2024-11-23T17:11:54.866Z] --------------------------------------------------
[2024-11-23T17:15:50.137Z] Test results: passed: 156; failed: 1
[2024-11-23T17:16:09.439Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_1/jvmtest/openjdk/report/html/report.html
[2024-11-23T17:16:09.439Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_testList_1/aqa-tests/TKG/output_17323818186962/serviceability_jvmti_j9_0/work
[2024-11-23T17:16:09.439Z] Error: Some tests failed or other problems occurred.
[2024-11-23T17:16:09.439Z] -----------------------------------
[2024-11-23T17:16:09.439Z] serviceability_jvmti_j9_0_FAILED
```
The existing code 134 means a SIGABRT signal.

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45172/)

**Comment by pshipton** [comment]
@dmitripivkine pls take a look.

**Comment by dmitripivkine** [comment]
An assertion occur an attempt to scan JNI Local References `!J9Pool 0x00007FFF2C008C60` `!J9JNIReferenceFrame 0x00007FFF2C008A18` for `!j9vmthread 0x00273d00`.
Problematic slot:
```
> !walkj9pool 0x00007FFF2C008C60 | grep -i 7FFF2C397618
	[17]	=	0x00007FFF2C397618

0x7FFF2C3975F0 :  00000000fd0ed650 00000000fd0e44a0 [ P........D...... ]
0x7FFF2C397600 :  00000000fffffed0 00000000fd1a4938 [ ........8I...... ]
0x7FFF2C397610 :  00000000fd0f3ee0 ffffffffffffffff [ .>.............. ] <-----
```
There are ~200000 elements in this pool and most of them (if not all) are class objects for `MyClass` class for various class loaders.
Taking to consideration class object for unloaded class is replaced to `0xffffffffffffffff` I have a hypothesis there is a time hole when newly created class was unloaded just before it's class object was added to JNI Local References pool.
@pshipton @TobiAjila

**Comment by dmitripivkine** [comment]
I do see class unloading but not last but previous Global GC. So next one should discover the problem but it wasn't. It means theory with just created class unloaded might not fit. Any way,  somehow we got class object from unloaded class `0xffffffffffffffff` in JNI Local References pool.

**Comment by dmitripivkine** [comment]
> I do see class unloading but not last but previous Global GC. So next one should discover the problem but it wasn't. It means theory with just created class unloaded might not fit. Any way, somehow we got class object from unloaded class `0xffffffffffffffff` in JNI Local References pool.

There are lot of failures in the grinder. I did check a few of them. The problem is the same, 0xffffffffffffffff in JNI Local References pool. Looks like previous GC doing class unloading and current one (Global or Local) crashed. I can not find another case where there is one extra GC survived between class unloading and crash. I guess it is possible if this middle GC happened before JNI Local Ref is added to the pool. 

Also noticed (not sure is it related) there is warning for very last (crashed) GC in verbose log:
```
<warning details="slow exclusive request due to Exclusive Access" threadname="Thread-0" timems="821" />
```

**Comment by pshipton** [comment]
@tajila this needs some attention.

**Comment by tajila** [comment]
@hangshao0 Please take a look

**Comment by hangshao0** [comment]
@fengxue-IS will look at this.

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_extended.openjdk_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_1/139/)
```
[2024-12-07T17:14:18.303Z] variation: Mode650
[2024-12-07T17:14:18.303Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-12-07T17:15:20.280Z] TEST: serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java

[2024-12-07T17:15:20.284Z]  stderr: [JVMDUMP039I Processing dump event "abort", detail "" at 2024/12/07 09:15:08 - please wait.
[2024-12-07T17:15:20.284Z] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_1733590483306/serviceability_jvmti_j9_1/work/scratch/0/core.20241207.091508.28139.0001.dmp' in response to an event
[2024-12-07T17:15:20.284Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_1733590483306/serviceability_jvmti_j9_1/work/scratch/0/core.20241207.091508.28139.0001.dmp
[2024-12-07T17:15:20.284Z] Thread 00007F1294003D00 structures scan: slot 00007F12940967B8 has bad value FFFFFFFFFFFFFFFF, iterator state 2
[2024-12-07T17:15:20.284Z] java: /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-linux-x64-openj9-IBM/workspace/build/src/openj9/runtime/gc_glue_java/ScavengerRootScanner.hpp:123: virtual void MM_ScavengerRootScanner::doVMThreadSlot(J9Object**, GC_VMThreadIterator*): Assertion `0' failed.
[2024-12-07T17:15:20.284Z] ]
[2024-12-07T17:15:20.284Z]  exitValue = 134
[2024-12-07T17:15:20.284Z] 
[2024-12-07T17:15:20.284Z] java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2024-12-07T17:15:20.284Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:231)
[2024-12-07T17:15:20.284Z] 	at TestUnloadedClass.main(TestUnloadedClass.java:53)
[2024-12-07T17:15:20.284Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-12-07T17:15:20.284Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-12-07T17:15:20.284Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-12-07T17:15:20.284Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-12-07T17:15:20.284Z] 
[2024-12-07T17:15:20.284Z] JavaTest Message: Test threw exception: java.lang.RuntimeException

[2024-12-07T17:18:01.040Z] serviceability_jvmti_j9_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_extended.openjdk_aarch64_linux 0.49 milestone 2](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_3/47/)(`rtj-ubu24aarch64-svl-test-e58xx-1`)
```
[2024-12-17T18:47:16.239Z] variation: Mode150
[2024-12-17T18:47:16.239Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-12-17T18:48:59.123Z] TEST: serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java

[2024-12-17T18:48:59.142Z]  stderr: [JVMDUMP039I Processing dump event "abort", detail "" at 2024/12/17 18:48:43 - please wait.
[2024-12-17T18:48:59.142Z] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_3/aqa-tests/TKG/output_17344612336542/serviceability_jvmti_j9_0/work/scratch/0/core.20241217.184843.1046272.0001.dmp' in response to an event
[2024-12-17T18:48:59.142Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_3/aqa-tests/TKG/output_17344612336542/serviceability_jvmti_j9_0/work/scratch/0/core.20241217.184843.1046272.0001.dmp
[2024-12-17T18:48:59.142Z] Thread 00000000001B1300 structures scan: slot 0000EC2C2456FE40 has bad value FFFFFFFFFFFFFFFF, iterator state 2
[2024-12-17T18:48:59.142Z] java: /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-linux-aarch64-openj9/workspace/build/src/openj9/runtime/gc_glue_java/ScavengerRootScanner.hpp:123: virtual void MM_ScavengerRootScanner::doVMThreadSlot(J9Object**, GC_VMThreadIterator*): Assertion `0' failed.
[2024-12-17T18:48:59.142Z] ]
[2024-12-17T18:48:59.142Z]  exitValue = 134
[2024-12-17T18:48:59.142Z] 
[2024-12-17T18:48:59.142Z] java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2024-12-17T18:48:59.142Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:231)
[2024-12-17T18:48:59.142Z] 	at TestUnloadedClass.main(TestUnloadedClass.java:53)
[2024-12-17T18:48:59.143Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-12-17T18:48:59.143Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-12-17T18:48:59.143Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-12-17T18:48:59.143Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-12-17T18:48:59.143Z] 
[2024-12-17T18:48:59.143Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2024-12-17T18:48:59.143Z] JavaTest Message: shutting down test
[2024-12-17T18:48:59.143Z] 
[2024-12-17T18:48:59.143Z] 
[2024-12-17T18:48:59.143Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2024-12-17T18:48:59.143Z] --------------------------------------------------
[2024-12-17T18:52:46.022Z] Test results: passed: 156; failed: 1
[2024-12-17T18:53:03.857Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_3/jvmtest/openjdk/report/html/report.html
[2024-12-17T18:53:03.858Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_3/aqa-tests/TKG/output_17344612336542/serviceability_jvmti_j9_0/work
[2024-12-17T18:53:03.858Z] Error: Some tests failed or other problems occurred.
[2024-12-17T18:53:03.858Z] -----------------------------------
[2024-12-17T18:53:03.858Z] serviceability_jvmti_j9_0_FAILED
```

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45996/)

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_extended.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_0/174/)
```
[2025-01-29T15:46:37.720Z] variation: Mode650
[2025-01-29T15:46:37.720Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-01-29T15:47:59.232Z] TEST: serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java

[2025-01-29T15:47:59.247Z] java: /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-linux-aarch64-openj9-IBM/workspace/build/src/openj9/runtime/gc_glue_java/MarkingSchemeRootMarker.cpp:64: virtual void MM_MarkingSchemeRootMarker::doVMThreadSlot(J9Object**, GC_VMThreadIterator*): Assertion `false && (vmthreaditerator_state_monitor_records == vmThreadIterator->getState())' failed.
[2025-01-29T15:47:59.247Z] ]
[2025-01-29T15:47:59.247Z]  exitValue = 134

[2025-01-29T15:51:26.831Z] serviceability_jvmti_j9_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_extended.openjdk_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_1/188/)
```
[2025-02-22T16:45:39.597Z] variation: Mode150
[2025-02-22T16:45:39.597Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-02-22T16:46:40.793Z] TEST: serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java

[2025-02-22T16:46:40.794Z]  stderr: [JVMDUMP039I Processing dump event "abort", detail "" at 2025/02/22 08:46:32 - please wait.
[2025-02-22T16:46:40.794Z] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_17402427386826/serviceability_jvmti_j9_0/work/scratch/2/core.20250222.084632.2934916.0001.dmp' in response to an event
[2025-02-22T16:46:40.794Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_testList_1/aqa-tests/TKG/output_17402427386826/serviceability_jvmti_j9_0/work/scratch/2/core.20250222.084632.2934916.0001.dmp
[2025-02-22T16:46:40.794Z] Thread 00000000001C6B00 structures scan: slot 00007F19CD0BFC30 has bad value FFFFFFFFFFFFFFFF, iterator state 2
[2025-02-22T16:46:40.794Z] java: /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-linux-x64-openj9-IBM/workspace/build/src/openj9/runtime/gc_glue_java/ScavengerRootScanner.hpp:123: virtual void MM_ScavengerRootScanner::doVMThreadSlot(J9Object**, GC_VMThreadIterator*): Assertion `0' failed.
[2025-02-22T16:46:40.794Z] ]
[2025-02-22T16:46:40.794Z]  exitValue = 134
[2025-02-22T16:46:40.794Z] 
[2025-02-22T16:46:40.794Z] java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2025-02-22T16:46:40.794Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:231)
[2025-02-22T16:46:40.794Z] 	at TestUnloadedClass.main(TestUnloadedClass.java:53)
[2025-02-22T16:46:40.794Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2025-02-22T16:46:40.794Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2025-02-22T16:46:40.794Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2025-02-22T16:46:40.794Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2025-02-22T16:46:40.794Z] 
[2025-02-22T16:46:40.794Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2025-02-22T16:46:40.794Z] --------------------------------------------------
[2025-02-22T16:49:13.811Z] Test results: passed: 159; failed: 1

[2025-02-22T16:49:26.347Z] -----------------------------------
[2025-02-22T16:49:26.347Z] serviceability_jvmti_j9_0_FAILED
```

**Comment by matthewhall2** [comment]
[openjdk21_j9_extended.openjdk_s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/233/)

```
18:10:50  variation: Mode650
18:10:50  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog

18:14:22  TEST: serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java

18:27:28   stderr: [JVMDUMP039I Processing dump event "abort", detail "" at 2025/02/28 15:26:55 - please wait.
18:27:28  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/aqa-tests/TKG/output_17407842474563/serviceability_jvmti_j9_1/work/scratch/0/core.20250228.152655.1706402.0001.dmp' in response to an event
18:27:28  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/aqa-tests/TKG/output_17407842474563/serviceability_jvmti_j9_1/work/scratch/0/core.20250228.152655.1706402.0001.dmp
18:27:28  java: /home/jenkins/workspace/Build_JDK21_s390x_linux_Personal/openj9/runtime/gc_glue_java/MarkingSchemeRootMarker.cpp:64: virtual void MM_MarkingSchemeRootMarker::doVMThreadSlot(J9Object**, GC_VMThreadIterator*): Assertion `false && (vmthreaditerator_state_monitor_records == vmThreadIterator->getState())' failed.
18:27:28  ]
18:27:28   exitValue = 134
18:27:28  
18:27:28  java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
18:27:28  	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:231)
18:27:28  	at TestUnloadedClass.main(TestUnloadedClass.java:53)
18:27:28  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
18:27:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
18:27:28  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
18:27:28  	at java.base/java.lang.Thread.run(Thread.java:1595)
18:27:28  
18:27:28  JavaTest Message: Test threw exception: java.lang.RuntimeException
18:27:28  JavaTest Message: shutting down test
18:27:28  
18:27:28  
18:27:28  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
```

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_extended.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_extended.openjdk_aarch64_linux_testList_4/12/)
```
[2025-03-17T16:42:32.828Z] variation: Mode150
[2025-03-17T16:42:32.828Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-03-17T16:44:39.784Z] TEST: serviceability/jvmti/GetMethodDeclaringClass/TestUnloadedClass.java

[2025-03-17T16:44:39.796Z]  stderr: [JVMDUMP039I Processing dump event "abort", detail "" at 2025/03/17 12:44:27 - please wait.
[2025-03-17T16:44:39.796Z] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk24_j9_extended.openjdk_aarch64_linux_testList_4/aqa-tests/TKG/output_17422297497760/serviceability_jvmti_j9_0/work/scratch/0/core.20250317.124427.2858873.0001.dmp' in response to an event
[2025-03-17T16:44:39.796Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk24_j9_extended.openjdk_aarch64_linux_testList_4/aqa-tests/TKG/output_17422297497760/serviceability_jvmti_j9_0/work/scratch/0/core.20250317.124427.2858873.0001.dmp
[2025-03-17T16:44:39.796Z] Thread 0000000000230D00 structures scan: slot 0000FFFF048AB6A0 has bad value FFFFFFFFFFFFFFFF, iterator state 2
[2025-03-17T16:44:39.796Z] java: /home/jenkins/workspace/build-scripts/jobs/jdk24/jdk24-linux-aarch64-openj9/workspace/build/src/openj9/runtime/gc_glue_java/ScavengerRootScanner.hpp:123: virtual void MM_ScavengerRootScanner::doVMThreadSlot(J9Object**, GC_VMThreadIterator*): Assertion `0' failed.
[2025-03-17T16:44:39.796Z] ]
[2025-03-17T16:44:39.796Z]  exitValue = 134
[2025-03-17T16:44:39.796Z] 
[2025-03-17T16:44:39.796Z] java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
[2025-03-17T16:44:39.796Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:253)

[2025-03-17T16:44:39.796Z] --------------------------------------------------
[2025-03-17T16:49:01.067Z] Test results: passed: 166; failed: 1

[2025-03-17T16:49:14.805Z] -----------------------------------
[2025-03-17T16:49:14.805Z] serviceability_jvmti_j9_0_FAILED
```

**Comment by VermaSh** [comment]
Seeing same failure in my zLinux personal [build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/49111/consoleFull)
```
11:30:41  java.lang.RuntimeException: 'OutOfMemoryError' missing from stdout/stderr
11:30:41  	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:231)
11:30:41  	at TestUnloadedClass.main(TestUnloadedClass.java:53)
11:30:41  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
11:30:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
11:30:41  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
11:30:41  	at java.base/java.lang.Thread.run(Thread.java:1595)
11:30:41  
11:30:41  JavaTest Message: Test threw exception: java.lang.RuntimeException
11:30:41  JavaTest Message: shutting down test
```
