### ISSUE TITLE
OpenJDK java/lang/reflect/IllegalArgumentsTest NullPointerException: Cannot invoke "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" because "x" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20683]
\https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/258
jdk_lang_1
java/lang/reflect/IllegalArgumentsTest.java
```
19:37:50  test IllegalArgumentsTest.nullArguments(): failure
19:37:50  java.lang.reflect.InvocationTargetException
19:37:50  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
19:37:50  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
19:37:50  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
19:37:50  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)
19:37:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
19:37:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
19:37:50  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
19:37:50  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
19:37:50  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
19:37:50  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
19:37:50  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
19:37:50  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
19:37:50  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
19:37:50  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
19:37:50  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
19:37:50  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
19:37:50  	at org.testng.TestRunner.run(TestRunner.java:585)
19:37:50  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
19:37:50  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
19:37:50  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
19:37:50  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
19:37:50  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
19:37:50  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
19:37:50  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
19:37:50  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
19:37:50  	at org.testng.TestNG.runSuites(TestNG.java:1069)
19:37:50  	at org.testng.TestNG.run(TestNG.java:1037)
19:37:50  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
19:37:50  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
19:37:50  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
19:37:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
19:37:50  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
19:37:50  	at java.base/java.lang.Thread.run(Thread.java:1595)
19:37:50  Caused by: java.lang.NullPointerException: Cannot invoke "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" because "x" is null
19:37:50  	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
19:37:50  	at <unknown class>.<unknown method>(Unknown Source)
19:37:50  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
19:37:50  	... 32 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/328
jdk_lang_j9_0
java/lang/reflect/IllegalArgumentsTest.java
```
18:29:05  test IllegalArgumentsTest.nullArguments(): failure
18:29:05  java.lang.reflect.InvocationTargetException
18:29:05  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
18:29:05  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
18:29:05  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
18:29:05  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:68)
18:29:05  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
18:29:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
18:29:05  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
18:29:05  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
18:29:05  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
18:29:05  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
18:29:05  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
18:29:05  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
18:29:05  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
18:29:05  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
18:29:05  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
18:29:05  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
18:29:05  	at org.testng.TestRunner.run(TestRunner.java:585)
18:29:05  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
18:29:05  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
18:29:05  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
18:29:05  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
18:29:05  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
18:29:05  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
18:29:05  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
18:29:05  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
18:29:05  	at org.testng.TestNG.runSuites(TestNG.java:1069)
18:29:05  	at org.testng.TestNG.run(TestNG.java:1037)
18:29:05  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
18:29:05  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
18:29:05  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
18:29:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
18:29:05  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
18:29:05  	at java.base/java.lang.Thread.run(Thread.java:1595)
18:29:05  Caused by: java.lang.NullPointerException
18:29:05  	at <unknown class>.<unknown method>(Unknown Source)
18:29:05  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
18:29:05  	... 32 more
```

**Comment by pshipton** [comment]
Failed in a grinder for https://github.com/eclipse-openj9/openj9/issues/21619 on jdk21 xlinux.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_OMR_testList_0/253

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_Nightly_testList_1/492
jdk_lang_1
java/lang/reflect/IllegalArgumentsTest.java
```
18:13:06  Caused by: java.lang.NullPointerException: Cannot invoke "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" because "x" is null
18:13:06  	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
18:13:06  	at <unknown class>.<unknown method>(Unknown Source)
18:13:06  	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
18:13:06  	... 32 more
```

**Comment by JasonFengJ9** [comment]
[openjdk21_j9_sanity.openjdk_x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_x86-64_mac_testList_0/422/)
```
[2025-10-18T19:14:08.281Z] Running test jdk_lang_0 ...
[2025-10-18T19:14:08.281Z] ===============================================
[2025-10-18T19:14:08.281Z] jdk_lang_0 Start Time: Sat Oct 18 15:14:07 2025 Epoch Time (ms): 1760814847685
[2025-10-18T19:14:08.281Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
[2025-10-18T19:14:08.281Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Xverbosegclog 

[2025-10-18T19:19:29.062Z] TEST: java/lang/reflect/IllegalArgumentsTest.java

[2025-10-18T19:19:29.063Z] Caused by: java.lang.NullPointerException: Cannot invoke "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" because "x" is null
[2025-10-18T19:19:29.063Z] 	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
[2025-10-18T19:19:29.063Z] 	at <unknown class>.<unknown method>(Unknown Source)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk27_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/20
jdk_lang_j9_0
java/lang/reflect/IllegalArgumentsTest.java
```
01:03:03  java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, java.lang.Object, boolean)" is null
01:03:03  	at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
01:03:03  	at <unknown class>.<unknown method>(Unknown Source)
01:03:03  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
01:03:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:589)
01:03:03  	at IllegalArgumentsTest.nullArguments(IllegalArgumentsTest.java:78)
```
