### ISSUE TITLE
JDK24 java/io/ByteArrayOutputStream/WriteToReleasesCarrier.java timed out

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20709]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/32/consoleFull)(`sles15-aarch64-5`):
```
22:41:25  openjdk version "24-internal" 2025-03-18
22:41:25  OpenJDK Runtime Environment (build 24-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
22:41:25  Eclipse OpenJ9 VM (build master-4ee9b77dbbd, JRE 24 Linux aarch64-64-Bit Compressed References 20241128_142 (JIT enabled, AOT enabled)
22:41:25  OpenJ9   - 4ee9b77dbbd
22:41:25  OMR      - 494474f6819
22:41:25  JCL      - 91383efdb6c based on jdk-24+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_io_0,jdk_io_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2FOpenJ9-JDKnext-aarch64_linux-20241128-015723.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=4ee9b77dbbdc1508639551e13bbffe7a455b5c10&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:52:18  ===============================================
22:52:18  Running test jdk_io_0 ...
22:52:18  ===============================================
22:52:18  jdk_io_0 Start Time: Thu Nov 28 03:52:17 2024 Epoch Time (ms): 1732765937365
22:52:18  variation: Mode150
22:52:18  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

23:09:19  TEST: java/io/ByteArrayOutputStream/WriteToReleasesCarrier.java

23:09:19  TEST RESULT: Error. Agent error: java.lang.Exception: Agent 4 timed out with a timeout of 960 seconds; check console log for any additional details
23:09:19  --------------------------------------------------
23:09:19  Test results: passed: 417; error: 1
23:09:29  Error: Some tests failed or other problems occurred.
23:09:29  -----------------------------------
23:09:29  jdk_io_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45242/) - all failed with timed out

**Comment by babsingh** [comment]
The test times out due to the lack of VirtualThread (VT) pinning support. Once OpenJ9 implements VT pinning, the top two methods in the stack trace below (`unblockVirtualThreads` and `takeVirtualThreadListToUnblock`) should function correctly, resolving the issue.

```
"VirtualThread-unblocker" prio=5 Id=28 RUNNABLE
	at java.base@24-internal/java.lang.VirtualThread.takeVirtualThreadListToUnblock(Native Method)
	at java.base@24-internal/java.lang.VirtualThread.unblockVirtualThreads(VirtualThread.java:1498)
	at java.base@24-internal/java.lang.Thread.run(Thread.java:1458)
	at java.base@24-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:148)
```

Assigning it to @fengxue-IS since it is related to the VT pinning support.

**Comment by babsingh** [comment]
This test passes with the base VM changes for JEP 491: https://github.com/eclipse-openj9/openj9/pull/21273 and https://github.com/eclipse-openj9/openj9/pull/21292. The test was run with `-Xint -Xgcpolicy:nogc -XX:+YieldPinnedVirtualThreads`. However, this issue cannot be closed yet, as the GC and VM-JIT coordination changes for JEP 491 are still in progress.

**Comment by babsingh** [comment]
fyi @tajila @fengxue-IS

**Comment by babsingh** [comment]
Closing, this issue is resolved with the latest changes for JEP491, which have been merged.
