### ISSUE TITLE
JDK24 serviceability/jvmti/RedefineClasses/RedefineVerifyError.java ClassFormatError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20708]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/32/consoleFull)(`sles15-aarch64-5`):
```
22:41:25  openjdk version "24-internal" 2025-03-18
22:41:25  OpenJDK Runtime Environment (build 24-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
22:41:25  Eclipse OpenJ9 VM (build master-4ee9b77dbbd, JRE 24 Linux aarch64-64-Bit Compressed References 20241128_142 (JIT enabled, AOT enabled)
22:41:25  OpenJ9   - 4ee9b77dbbd
22:41:25  OMR      - 494474f6819
22:41:25  JCL      - 91383efdb6c based on jdk-24+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_io_0,jdk_io_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2FOpenJ9-JDKnext-aarch64_linux-20241128-015723.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=4ee9b77dbbdc1508639551e13bbffe7a455b5c10&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:43:00  ===============================================
22:43:00  Running test serviceability_jvmti_j9_0 ...
22:43:00  ===============================================
22:43:00  serviceability_jvmti_j9_0 Start Time: Thu Nov 28 03:42:59 2024 Epoch Time (ms): 1732765379926
22:43:00  variation: Mode150
22:43:00  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

22:44:45  TEST: serviceability/jvmti/RedefineClasses/RedefineVerifyError.java

22:44:45  STDERR:
22:44:45  JVMJ9VM007W Command-line option unrecognised: -Xlog:class+init,exceptions
22:44:45  java.lang.ClassFormatError
22:44:45  	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
22:44:45  	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:247)
22:44:45  	at RedefineClassHelper.redefineClass(RedefineClassHelper.java:61)
22:44:45  	at RedefineVerifyError.main(RedefineVerifyError.java:93)
22:44:45  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:44:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
22:44:45  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
22:44:45  	at java.base/java.lang.Thread.run(Thread.java:1458)
22:44:45  
22:44:45  JavaTest Message: Test threw exception: java.lang.ClassFormatError

22:47:19  serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45241/)

**Comment by tajila** [comment]
@theresa-m Please take a look at this

**Comment by babsingh** [comment]
@theresa-m `-Xlog:class+init,exceptions` (cmdline option) is not supported by OpenJ9. Such tests in the past have been permanently disabled.

**Comment by babsingh** [comment]
I just remembered another observation. Earlier this year, while investigating this issue, I noticed that the same error occurs even after removing the `-Xlog:class+init,exceptions` command-line option from **line 38** in the test. The test dynamically generates a class with two improperly implemented `<init>` methods and expects the JVM to throw a `VerifyError` during redefinition (**lines 91–98**). However, OpenJ9 throws a `ClassFormatError` instead.

`ClassFormatError` is incorrect in this scenario because the bytecodes are well-formed. The improperly implemented constructors constitute verification violations, which should result in a `VerifyError` according to the JVM specification. I believe OpenJ9 needs to be fixed to handle this scenario appropriately.

Here is the test case for reference: https://github.com/ibmruntimes/openj9-openjdk-jdk24/blob/openj9/test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineVerifyError.java

**Comment by theresa-m** [comment]
The behavior of OpenJ9 seems correct to me. The test modifies `java/lang/VerifyError` so that there is no code attribute in the `<init>` methods.

According to prior specs in `4.7.3 The Code Attribute`:
```
If the method is either native or abstract, and is not a class or interface
initialization method, then its method_info structure must not have a Code attribute
in its attributes table. Otherwise, its method_info structure must have exactly
one Code attribute in its attributes table.
```
also
`The value of code_length must be greater than zero`

**Comment by theresa-m** [comment]
The behavior of OpenJ9 seems correct to me. The test modifies java/lang/VerifyError so that there is no code attribute in the <init> methods.
According to prior specs in `4.7.3 The Code Attribute`:
```
If the method is either native or abstract, and is not a class or interface
initialization method, then its method_info structure must not have a Code attribute
in its attributes table. Otherwise, its method_info structure must have exactly
one Code attribute in its attributes table.
```
also
`The value of code_length must be greater than zero`

**Comment by babsingh** [comment]
@theresa-m Your logic seems sound. Based on your reference to JVM spec §4.7.3, ClassFormatError is the correct error.

@pshipton Does the following plan look good to you?
- Reach out to the test author in https://github.com/openjdk/jdk/pull/22116, sharing details from https://github.com/eclipse-openj9/openj9/issues/20708#issuecomment-2625653383 to request a fix.
- Exclude the test on our end while we wait for the upstream fix.
- Keep this issue open and defer it to the next release until the test is fixed.
- Close this issue once the test is fixed upstream.

**Comment by pshipton** [comment]
Sounds good.

**Comment by theresa-m** [comment]
I took another look at this https://github.com/openjdk/jdk/pull/22116#issuecomment-2640709606. I still think its true that the code attribute does not exist in the redefined method. I tried loading a similar class with `Class.forName(,false,)` and both OpenJDK and OpenJ9 throw a ClassFormatError due to a missing code attribute.

I think both implementations can be correct responses since its not specified in https://docs.oracle.com/en/java/javase/24/docs/specs/jvmti.html#RedefineClasses which error should come first.

The purpose of this test is to validate that the verifier is called during class redefinition for classes on the boot class path. I think the best solution is to modify the test so the redefined class is valid with malformed bytecodes so OpenJ9 will throw a VerifyError.

Please let me know if you agree @babsingh

**Comment by babsingh** [comment]
I agree with your conclusion, since the current redefined class lacks a proper `Code` attribute (or has `code_length == 0`), a `ClassFormatError` is a valid outcome, and the spec does not mandate which error must be thrown first in this scenario. So both implementations are compliant.

To ensure consistent behavior across JVMs and to better align the test with its intent (i.e., to validate that the verifier is triggered during class redefinition on the boot class path), I agree that the best solution is to modify the test so that the redefined class is structurally valid but contains malformed bytecode that fails verification.

I tried the following fix to do exactly that; it inserts a `nop` instruction and a corresponding `visitMaxs` call in each constructor to ensure `code_length > 0`, avoiding `ClassFormatError`, while still triggering a `VerifyError` due to improper control flow:
```
diff --git a/test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineVerifyError.java b/test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineVerifyError.java
index ea511c05b59..2978d062e23 100644
--- a/test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineVerifyError.java
+++ b/test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineVerifyError.java
@@ -72,12 +72,16 @@ public static byte[] dump () throws Exception {
         {
             methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
             methodVisitor.visitCode();
+            methodVisitor.visitInsn(NOP);
+            methodVisitor.visitMaxs(1, 1);
             methodVisitor.visitEnd();
         }

         {
             methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "<init>", "(Ljava/lang/String;)V", null, null);
             methodVisitor.visitCode();
+            methodVisitor.visitInsn(NOP);
+            methodVisitor.visitMaxs(2, 2);
             classWriter.visitEnd();
         }
```
The above fix works and OpenJ9 throws a `VerifyError`, making the test portable across implementations.

In https://github.com/openjdk/jdk/pull/22116#issuecomment-2640709606, the author suggested the above fix.
@theresa-m, could you check with the author to see if they are willing to incorporate this fix into OpenJDK? If not, we can proceed with applying it in our extension repos.

I have also updated the labels to indicate that this is a test-related issue.

**Comment by pshipton** [comment]
@theresa-m is there any update on this?

**Comment by theresa-m** [comment]
There was no response on the issue about modifying the test upstream. Can you follow up @offamitkumar ?
