### ISSUE TITLE
JDK24 java/lang/Thread/virtual tests IllegalArgumentException: OpenJ9 doesn't support the API

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20706]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Personal_testList_1/27/consoleFull)(`ubu22-aarch64-2`):
```
00:07:31  openjdk version "24-internal" 2025-03-18
00:07:31  OpenJDK Runtime Environment (build 24-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
00:07:31  Eclipse OpenJ9 VM (build master-4ee9b77dbbd, JRE 24 Linux aarch64-64-Bit Compressed References 20241128_142 (JIT enabled, AOT enabled)
00:07:31  OpenJ9   - 4ee9b77dbbd
00:07:31  OMR      - 494474f6819
00:07:31  JCL      - 91383efdb6c based on jdk-24+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_lang_1,jdk_foreign_0&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Personal&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2FOpenJ9-JDKnext-aarch64_linux-20241128-015723.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=4ee9b77dbbdc1508639551e13bbffe7a455b5c10&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=43&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
00:09:01  ===============================================
00:09:01  Running test jdk_lang_1 ...
00:09:01  ===============================================
00:09:01  jdk_lang_1 Start Time: Thu Nov 28 05:09:00 2024 Epoch Time (ms): 1732770540869
00:09:01  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
00:09:01  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Xverbosegclog 

01:19:58  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#default

01:19:58  STARTED    MonitorEnterExit::testReleaseWhenBlocked 'testReleaseWhenBlocked()'
01:19:58  org.junit.jupiter.engine.execution.ConditionEvaluationException: Failed to evaluate condition [org.junit.jupiter.api.condition.DisabledIfCondition]: OpenJ9 doesn't support the API i.e. the VM option might exist, but OpenJ9 can't retrieve it
01:19:58  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
01:19:58  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
01:19:58  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:305)
01:19:58  	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
01:19:58  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
01:19:58  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:601)
01:19:58  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:587)
01:19:58  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:573)
01:19:58  	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
01:19:58  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:270)
01:19:58  	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:687)
01:19:58  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
01:19:58  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
01:19:58  Caused by: java.lang.IllegalArgumentException: OpenJ9 doesn't support the API i.e. the VM option might exist, but OpenJ9 can't retrieve it
01:19:58  	at jdk.management/com.sun.management.internal.ExtendedHotSpotDiagnostic.getVMOption(ExtendedHotSpotDiagnostic.java:79)
01:19:58  	at LockingMode.isLegacy(LockingMode.java:35)
01:19:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
01:19:58  	at java.base/java.util.Optional.map(Optional.java:260)
01:19:58  	... 13 more
01:19:58  FAILED     MonitorEnterExit::testReleaseWhenBlocked 'testReleaseWhenBlocked()'

01:20:06  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#LM_LEGACY

01:20:09  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#LM_LIGHTWEIGHT

01:20:59  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#Xcomp-LM_LEGACY

01:21:05  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#Xcomp-LM_LIGHTWEIGHT

01:21:55  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#Xcomp-noTieredCompilation-LM_LEGACY

01:21:59  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#Xcomp-noTieredCompilation-LM_LIGHTWEIGHT

01:22:59  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#Xcomp-TieredStopAtLevel1-LM_LEGACY

01:23:02  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#Xcomp-TieredStopAtLevel1-LM_LIGHTWEIGHT

01:23:05  TEST: java/lang/Thread/virtual/MonitorEnterExit.java#Xint-LM_LEGACY

...



01:44:37  jdk_lang_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45335/) - all failed

**Comment by pshipton** [comment]
java/lang/Thread/virtual/MonitorWaitNotify.java#LM_LEGACY.MonitorWaitNotify_LM_LEGACY
java/lang/Thread/virtual/MonitorWaitNotify.java#LM_LIGHTWEIGHT.MonitorWaitNotify_LM_LIGHTWEIGHT
java/lang/Thread/virtual/MonitorWaitNotify.java#Xcomp-LM_LEGACY.MonitorWaitNotify_Xcomp-LM_LEGACY
java/lang/Thread/virtual/MonitorWaitNotify.java#Xcomp-LM_LIGHTWEIGHT.MonitorWaitNotify_Xcomp-LM_LIGHTWEIGHT
java/lang/Thread/virtual/MonitorWaitNotify.java#Xcomp-TieredStopAtLevel1-LM_LEGACY.MonitorWaitNotify_Xcomp-TieredStopAtLevel1-LM_LEGACY
java/lang/Thread/virtual/MonitorWaitNotify.java#Xcomp-TieredStopAtLevel1-LM_LIGHTWEIGHT.MonitorWaitNotify_Xcomp-TieredStopAtLevel1-LM_LIGHTWEIGHT
java/lang/Thread/virtual/MonitorWaitNotify.java#Xcomp-noTieredCompilation-LM_LEGACY.MonitorWaitNotify_Xcomp-noTieredCompilation-LM_LEGACY
java/lang/Thread/virtual/MonitorWaitNotify.java#Xcomp-noTieredCompilation-LM_LIGHTWEIGHT.MonitorWaitNotify_Xcomp-noTieredCompilation-LM_LIGHTWEIGHT
java/lang/Thread/virtual/MonitorWaitNotify.java#Xint-LM_LEGACY.MonitorWaitNotify_Xint-LM_LEGACY
java/lang/Thread/virtual/MonitorWaitNotify.java#Xint-LM_LIGHTWEIGHT.MonitorWaitNotify_Xint-LM_LIGHTWEIGHT
java/lang/Thread/virtual/MonitorWaitNotify.java#default.MonitorWaitNotify_default

**Comment by pshipton** [comment]
java/lang/Thread/virtual/Parking.java#Xcomp-noTieredCompilation.Parking_Xcomp-noTieredCompilation
java/lang/Thread/virtual/Parking.java#Xcomp.Parking_Xcomp
java/lang/Thread/virtual/Parking.java#Xint.Parking_Xint
java/lang/Thread/virtual/Parking.java#default.Parking_default

**Comment by pshipton** [comment]
java/lang/Thread/virtual/ThreadAPI.java#default.ThreadAPI_default
    java/lang/Thread/virtual/ThreadAPI.java#no-vmcontinuations.ThreadAPI_no-vmcontinuations

**Comment by pshipton** [comment]
I will modify `at LockingMode.isLegacy(LockingMode.java:35)`

**Comment by pshipton** [comment]
I tried setting legacy locking to false, but all the testing timed out.
https://openj9-jenkins.osuosl.org/job/Grinder/4074/

I'll try a run with it set to true.

**Comment by pshipton** [comment]
Grinder with legacy locking set to true.
https://openj9-jenkins.osuosl.org/job/Grinder/4075/

**Comment by tajila** [comment]
I think we should be using `LockingMode.isLegacy() == true` until JEP 491 is merged.

**Comment by pshipton** [comment]
It's better now using true, opened https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/14

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_extended.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_extended.openjdk_aarch64_linux/1/)
```
[2025-02-22T21:13:56.557Z] variation: Mode150
[2025-02-22T21:13:56.557Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2025-02-22T21:18:50.940Z] TEST: serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java#default

[2025-02-22T21:18:50.941Z] STDERR:
[2025-02-22T21:18:50.941Z] java.lang.IllegalArgumentException: OpenJ9 doesn't support the API i.e. the VM option might exist, but OpenJ9 can't retrieve it
[2025-02-22T21:18:50.941Z] 	at jdk.management/com.sun.management.internal.ExtendedHotSpotDiagnostic.getVMOption(ExtendedHotSpotDiagnostic.java:79)
[2025-02-22T21:18:50.941Z] 	at StopThreadTest.preemptableVirtualThread(StopThreadTest.java:281)
[2025-02-22T21:18:50.941Z] 	at StopThreadTest.run(StopThreadTest.java:131)
[2025-02-22T21:18:50.941Z] 	at StopThreadTest.main(StopThreadTest.java:94)
[2025-02-22T21:18:50.941Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-02-22T21:18:50.941Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
[2025-02-22T21:18:50.941Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2025-02-22T21:18:50.941Z] 	at java.base/java.lang.Thread.run(Thread.java:1458)
[2025-02-22T21:18:50.941Z] 
[2025-02-22T21:18:50.941Z] JavaTest Message: Test threw exception: java.lang.IllegalArgumentException: OpenJ9 doesn't support the API i.e. the VM option might exist, but OpenJ9 can't retrieve it

```

**Comment by pshipton** [comment]
Created https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/31

**Comment by keithc-ca** [comment]
This should be kept open until https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/14 and https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/31 are reverted. If some other outcome is desired, that should be propagated to the head stream.

**Comment by keithc-ca** [comment]
The head stream seems to be suffering the same symptoms; see https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK21_s390x_linux/1381. Perhaps we want to apply https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/14 and https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/31 to jdknext?

**Comment by pshipton** [comment]
Created https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/975

**Comment by keithc-ca** [comment]
Should this be closed now that https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/975 is merged or should the test changes eventually be reverted?

**Comment by pshipton** [comment]
We need this open for tracking. We wouldn't revert the changes, the setting should change from true to false, and ideally we'd query some OpenJ9 option to get the proper setting.

**Comment by JasonFengJ9** [comment]
Run disabled the test with [a recent build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50208/consoleFull).
**Note:** this build does NOT have https://github.com/eclipse-openj9/openj9/pull/21774 

```
18:10:41  openjdk version "24.0.1-internal" 2025-04-15
18:10:41  OpenJDK Runtime Environment (build 24.0.1-internal-adhoc.jenkins.BuildJDK24x86-64linuxPersonal)
18:10:41  Eclipse OpenJ9 VM (build master-e6f2be7e590, JRE 24 Linux amd64-64-Bit Compressed References 20250507_203 (JIT enabled, AOT enabled)
18:10:41  OpenJ9   - e6f2be7e590
18:10:41  OMR      - 31a1e555d49
18:10:41  JCL      - ea18cde9d73 based on jdk-24.0.1+9)

18:11:44  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
18:11:44  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops -Xverbosegclog 

18:39:28  TEST: java/lang/Thread/virtual/MonitorWaitNotify.java#Xcomp-LM_LEGACY

18:39:28  STARTED    MonitorWaitNotify::testInterruptWait '[1] 0'
18:39:28  Unhandled exception
18:39:28  Type=Segmentation error vmState=0x00000000
18:39:28  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000080
18:39:28  Handler1=00007F0AEC52DC10 Handler2=00007F0AEC4853C0 InaccessibleAddress=0000000000000000
18:39:28  RDI=0000000000000000 RSI=A37536DAC823DEB4 RAX=0000000000000001 RBX=00000000004E8300
18:39:28  RCX=5C8B4830244C8B4C RDX=FFC358C483482820 R8=0000000000000001 R9=00000000004EBA80
18:39:28  R10=00000000004EBA88 R11=00007F0AECADF480 R12=00007F0A6AF2669A R13=000000001C0C0100
18:39:28  R14=00007F0AEC7487E0 R15=0000000000000000
18:39:28  RIP=00007F0AEC573389 GS=0000 FS=0000 RSP=00007F0AD868C980
18:39:28  EFlags=0000000000010297 CS=0033 RBP=00000000004E8000 ERR=0000000000000000
18:39:28  TRAPNO=000000000000000D OLDMASK=0000000000000000 CR2=0000000000000000

18:39:28  Module=/home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/lib/default/libj9vm29.so
18:39:28  Module_base_address=00007F0AEC4ED000
18:39:28  Target=2_90_20250507_203 (Linux 5.15.0-139-generic)
18:39:28  CPU=amd64 (4 logical CPUs) (0x1f0184000 RAM)
18:39:28  ----------- Stack Backtrace -----------
18:39:28  walkStackFrames+0x909 (0x00007F0AEC573389 [libj9vm29.so+0x86389])
18:39:28  _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0xb439 (0x00007F0AEC5AE9E9 [libj9vm29.so+0xc19e9])
18:39:28  bytecodeLoopCompressed+0xca (0x00007F0AEC5A351A [libj9vm29.so+0xb651a])
18:39:28   (0x00007F0AEC6747C2 [libj9vm29.so+0x1877c2])
18:39:28  ---------------------------------------
18:39:28  JVMDUMP039I Processing dump event "gpf", detail "" at 2025/05/07 23:39:24 - please wait.


18:55:32  jdk_lang_0_FAILED
```

**Comment by tajila** [comment]
@JasonFengJ9 Can you please add a `boolean com.ibm.oti.vm.VM::isYieldBlockedVirtualThreads()` API which can then be used in the testing code to query the locking mode.
