### ISSUE TITLE
JDK24 java/lang/Class/ProtectionDomainRace.java AssertionError: sun.security.util.ResourcesMgr (PD)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20704]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Personal_testList_1/27/consoleFull)(`ubu22-aarch64-2`):
```
00:07:31  openjdk version "24-internal" 2025-03-18
00:07:31  OpenJDK Runtime Environment (build 24-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
00:07:31  Eclipse OpenJ9 VM (build master-4ee9b77dbbd, JRE 24 Linux aarch64-64-Bit Compressed References 20241128_142 (JIT enabled, AOT enabled)
00:07:31  OpenJ9   - 4ee9b77dbbd
00:07:31  OMR      - 494474f6819
00:07:31  JCL      - 91383efdb6c based on jdk-24+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_lang_1,jdk_foreign_0&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Personal&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2FOpenJ9-JDKnext-aarch64_linux-20241128-015723.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F142%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=4ee9b77dbbdc1508639551e13bbffe7a455b5c10&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=43&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
00:09:01  ===============================================
00:09:01  Running test jdk_lang_1 ...
00:09:01  ===============================================
00:09:01  jdk_lang_1 Start Time: Thu Nov 28 05:09:00 2024 Epoch Time (ms): 1732770540869
00:09:01  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
00:09:01  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Xverbosegclog 

00:11:17  TEST: java/lang/Class/ProtectionDomainRace.java

00:11:17  STDERR:
00:11:17  java.lang.AssertionError: sun.security.util.ResourcesMgr (PD)
00:11:17  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.checkInjectedInvoker(MethodHandleImpl.java:1217)
00:11:17  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.makeInjectedInvoker(MethodHandleImpl.java:1119)
00:11:17  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1126)
00:11:17  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1123)
00:11:17  	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:237)
00:11:17  	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:219)
00:11:17  	at java.base/java.lang.ClassValue.get(ClassValue.java:125)
00:11:17  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.bindCallerWithInjectedInvoker(MethodHandleImpl.java:1098)
00:11:17  	at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.bindCaller(MethodHandleImpl.java:1086)
00:11:17  	at java.base/java.lang.invoke.MethodHandleImpl.bindCaller(MethodHandleImpl.java:1039)
00:11:17  	at java.base/java.lang.invoke.MethodHandles$Lookup.maybeBindCaller(MethodHandles.java:3910)
00:11:17  	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:3894)
00:11:17  	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethod(MethodHandles.java:3837)
00:11:17  	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodForConstant(MethodHandles.java:4051)
00:11:17  	at java.base/java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:4004)
00:11:17  	at java.base/java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:636)
00:11:17  	at java.base/java.lang.invoke.MethodHandleResolver.sendResolveMethodHandle(MethodHandleResolver.java:297)
00:11:17  	at java.base/java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
00:11:17  	at java.base/java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:412)
00:11:17  	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:186)
00:11:17  	at java.base/sun.security.util.ResourcesMgr.getBundle(ResourcesMgr.java:54)
00:11:17  	at java.base/sun.security.util.ResourcesMgr.getString(ResourcesMgr.java:40)
00:11:17  	at java.base/javax.security.auth.Subject.doAs(Subject.java:389)
00:11:17  	at ProtectionDomainRace.lambda$main$1(ProtectionDomainRace.java:66)
00:11:17  	at java.base/java.lang.Thread.run(Thread.java:1458)
00:11:17  
00:11:17  JavaTest Message: Test threw exception: java.lang.AssertionError: sun.security.util.ResourcesMgr (PD)

01:44:37  jdk_lang_1_FAILED
```
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45335/) - 35/47 failed

**Comment by pshipton** [comment]
Dup of https://github.com/eclipse-openj9/openj9/issues/20351
