### ISSUE TITLE
DDR:j9class-> descriptionPtr should be treated as unsigned

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse-openj9/openj9#20758]
DDR: In the case of high bit happen to be set for `descriptionPtr` in `j9class` an error occur:
```
com.ibm.j9ddr.InvalidDataTypeException: U64 contains value larger than Long.MAX_VALUE
        at com.ibm.j9ddr.vm29.types.U64.longValue(U64.java:115)
        at com.ibm.j9ddr.vm29.j9.gc.GCMixedObjectIterator_V1.initializeDescriptionArray(GCMixedObjectIterator_V1.java:110)
```

**Comment by dmitripivkine** [comment]
There is a bug in this code:

`tempDescription` can not be used as long because highest bit in descriptionPtr location for indirect case can be used. It should be treated as UDATA.

https://github.com/eclipse-openj9/openj9/blob/7aa9aa4664d22045dcfa9fd5c2d3c1fc1fc45cb6/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCMixedObjectIterator_V1.java#L97..#L126

**Comment by dmitripivkine** [comment]
@keithc-ca Would you please advise what is the best way to fix this problem? Current type of `tempDescription` is `long` but highest bit can be set, so it should be treated as `UDATA`.  And it requires to change type of the first parameter in `initializeDescriptionArray()`. I am not sure what is the best "java style" fix should be.

**Comment by keithc-ca** [comment]
I'll have a look.

**Comment by keithc-ca** [comment]
It should use `UDATA` instead of `long`. I'll put a fix together.

**Comment by dmitripivkine** [comment]
Thank you very much!
