### ISSUE TITLE
jdk_jmx_0 FAILED in javax/management/MBeanServer/OldMBeanServerTest.java got exception javax.management.InstanceNotFoundException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20777]
**Failure link**
---
From internal [Test_openjdk8_j9_extended.openjdk_aarch64_linux_testList_1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_aarch64_linux_testList_1/166/) (ubu22-aarch64-14)

```**Java Version**
openjdk version "1.8.0_442-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_442-beta-202412052334-b04)
Eclipse OpenJ9 VM (build master-3f7abb5f83, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20241205_1061 (JIT enabled, AOT enabled)
OpenJ9   - 3f7abb5f83
OMR      - b893b2be2
JCL      - 608c7b0e0 based on jdk8u442-b04)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_jmx_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_extended.openjdk_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F1061%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2024-12-05-23-30.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F1061%2Fibm-semeru-open-testimage_aarch64_linux_JDK8U_2024-12-05-23-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=339&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-12-06T02:26:28.993Z] variation: Mode150
[2024-12-06T02:26:28.993Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-12-06T02:27:32.249Z] TEST: javax/management/MBeanServer/OldMBeanServerTest.java

[2024-12-06T02:27:32.250Z] testPlatformMBeanServer: got exception javax.management.InstanceNotFoundException
[2024-12-06T02:27:32.250Z] javax.management.InstanceNotFoundException: java.lang:type=Memory
[2024-12-06T02:27:32.250Z] 	at OldMBeanServerTest$OldMBeanServer.getMBean(OldMBeanServerTest.java:1005)
[2024-12-06T02:27:32.250Z] 	at OldMBeanServerTest$OldMBeanServer.invoke(OldMBeanServerTest.java:631)
[2024-12-06T02:27:32.250Z] 	at OldMBeanServerTest.testPlatformMBeanServer(OldMBeanServerTest.java:339)

[2024-12-06T02:27:32.250Z] STDERR:
[2024-12-06T02:27:32.250Z] java.lang.Exception: TEST FAILED: testPlatformMBeanServer: got exception javax.management.InstanceNotFoundException
[2024-12-06T02:27:32.250Z] 	at OldMBeanServerTest.main(OldMBeanServerTest.java:143)
[2024-12-06T02:27:32.250Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-12-06T02:27:32.250Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-12-06T02:27:32.250Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-12-06T02:27:32.250Z] 	at java.lang.reflect.Method.invoke(Method.java:503)
[2024-12-06T02:27:32.250Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2024-12-06T02:27:32.250Z] 	at java.lang.Thread.run(Thread.java:822)

[2024-12-06T02:33:35.045Z] jdk_jmx_0_FAILED
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45641/) - all failed

**Comment by pshipton** [comment]
@JasonFengJ9 is this cross platform or single platform? You may want to exclude the failing test until we can look at it.

@tajila this test was recently enabled. We need to determine if the failure can be fixed, or if the test should be excluded.

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_extended.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_ppc64le_linux_testList_1/179/)
[openjdk8_j9_extended.openjdk_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/377/)
The failure is cross-platform, only in Java 8.

**Comment by hangshao0** [comment]
> @fengxue-IS , could you look at if this is something we should fix in OpenJ9, or we should permanently exclude the test.

Jack is working on virtual thread now. @theresa-m Could you look at this ?

**Comment by theresa-m** [comment]
I think this is failing due to an error in OpenJ9. The test class mentions it is checking that a custom MBeanServer aligns with JMX 1.2 specification. I'm not sure which part it is referencing however I did find in the [ManagementFactory javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/management/ManagementFactory.html) that a JVM always has an instance of MemoryMXBean which is the missing mbean thats causing the error.

I'm still investigating why this isn't being added properly for j9 for this scenario.

**Comment by theresa-m** [comment]
I confirmed that J9 does try to add these mbeans but `registerMBean` silently fails during a call to `standardToDynamic` when the test tries to convert them to DynamicMBean type. In OpenJDK the default management interface beans are always created as DynamicMBean type and in J9 they are not. I don't see any documentation to suggest that they should be, I think this test can be excluded permanently.

**Comment by pshipton** [comment]
The behavior of OpenJDK and the test suggest that they should be DynamicMBean type. Is there a problem changing OpenJ9 to do that?

**Comment by keithc-ca** [comment]
Should this now be closed as fixed since #21954 is merged and the test has been re-enabled?

**Comment by JasonFengJ9** [comment]
Closing as per https://github.com/eclipse-openj9/openj9/issues/20777#issuecomment-3008650112
