### ISSUE TITLE
jdk_security3_0 FAILED sun/security/provider/all/Deterministic.java RuntimeException: assertEqualsByteArray

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20787]
**Failure link**
---
From internal [Test_openjdk21_j9_extended.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_0](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_0/6/) (win22x86-svl-rt3-1)

```**Java Version**
java version "21.0.6-beta" 2025-01-21
IBM Semeru Runtime Certified Edition 21.0.6+6-202412071610 (build 21.0.6-beta+6-202412071610)
Eclipse OpenJ9 VM 21.0.6+6-202412071610 (build master-501751012f, JRE 21 Windows Server 2022 amd64-64-Bit Compressed References 20241207_325 (JIT enabled, AOT enabled)
OpenJ9   - 501751012f
OMR      - b893b2be2
JCL      - 71fff4eae based on jdk-21.0.6+6)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security3_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=FIPS140_3_OpenJCEPlusFIPS&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_extended.openjdk_x86-64_windows_fips140_3_openjceplusfips&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-windows-x64-openj9-IBM%2F325%2Fibm-semeru-certified-jdk_x64_windows_JDK21U_2024-12-07-16-01.zip+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-windows-x64-openj9-IBM%2F325%2Fibm-semeru-certified-testimage_x64_windows_JDK21U_2024-12-07-16-01.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=7&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-12-07T22:22:06.073Z] variation: Mode150
[2024-12-07T22:22:06.073Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS

[2024-12-07T22:51:48.931Z] TEST: sun/security/provider/all/Deterministic.java

[2024-12-07T22:51:48.931Z] STDERR:
[2024-12-07T22:51:48.931Z] java.lang.RuntimeException: assertEqualsByteArray: expected 91b83fbe5141df6bff3d7d7c31ce3d5b39d055ee83c21c74403103948db01243b7bdfa35f0469564622db238486f2e4df131f78c1ec3a2fb7963e31acddd8153 to equal 4b9906c9d4fca25cc6b0edb92c3ffabb9e8e96e80600567dcfd0f47da376ad753377da2eb16d7e25a2c729b77a277b4b860fe925ca3eed30baa84bbd0a06ad5f
[2024-12-07T22:51:48.931Z] 	at jdk.test.lib.Asserts.fail(Asserts.java:694)
[2024-12-07T22:51:48.931Z] 	at jdk.test.lib.Asserts.assertEqualsByteArray(Asserts.java:276)
[2024-12-07T22:51:48.931Z] 	at jdk.test.lib.Asserts.assertEqualsByteArray(Asserts.java:248)
[2024-12-07T22:51:48.931Z] 	at Deterministic.testKeyGenerator(Deterministic.java:230)
[2024-12-07T22:51:48.931Z] 	at Deterministic.main(Deterministic.java:72)
[2024-12-07T22:51:48.931Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-12-07T22:51:48.931Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-12-07T22:51:48.931Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-12-07T22:51:48.931Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)

[2024-12-08T00:05:27.335Z] Test results: passed: 458; failed: 1
[2024-12-08T00:05:44.251Z] Report written to C:\Users\jenkins\workspace\Test_openjdk21_j9_extended.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_0\aqa-tests\TKG\output_17336101155242\jdk_security3_0\report\html\report.html
[2024-12-08T00:05:44.251Z] Results written to C:\Users\jenkins\workspace\Test_openjdk21_j9_extended.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_0\aqa-tests\TKG\output_17336101155242\jdk_security3_0\work
[2024-12-08T00:05:44.251Z] Error: Some tests failed or other problems occurred.
[2024-12-08T00:05:44.251Z] -----------------------------------
[2024-12-08T00:05:44.251Z] jdk_security3_0_FAILED
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45761/) - all failed for finished grinder runs

FYI @jasonkatonica

**Comment by jasonkatonica** [comment]
This test has been added to the [21 ](https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/241) and [24](https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/9) and [next](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/915) excludes list for FIPS strict and weak profiles. I believe that this issue can be closed.
