### ISSUE TITLE
openJcePlusTests_0 FAILED OCKException: ICC_RSA_generate_key() failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20789]
**Failure link**
---
From internal [Test_openjdk21_j9_extended.functional_ppc64le_linux_fips140_3_openjceplusfips](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.functional_ppc64le_linux_fips140_3_openjceplusfips/9/) (sles15le-svl-rt1-1)

```**Java Version**
java version "21.0.6-beta" 2025-01-21
IBM Semeru Runtime Certified Edition 21.0.6+6-202412071603 (build 21.0.6-beta+6-202412071603)
Eclipse OpenJ9 VM 21.0.6+6-202412071603 (build master-501751012f, JRE 21 Linux ppc64le-64-Bit Compressed References 20241207_322 (JIT enabled, AOT enabled)
OpenJ9   - 501751012f
OMR      - b893b2be2
JCL      - 71fff4eae based on jdk-21.0.6+6)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=openJcePlusTests_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=FIPS140_3_OpenJCEPlusFIPS&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F322%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK21U_2024-12-07-16-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F322%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK21U_2024-12-07-16-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-ppc64le-openj9-IBM%2F322%2Fibm-semeru-certified-testimage_ppc64le_linux_JDK21U_2024-12-07-16-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=120&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional%2FOpenJcePlusTests%2Cfunctional%2Fsecurity&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=Dynamic) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-12-07T17:04:22.435Z] variation: NoOptions
[2024-12-07T17:04:22.435Z] JVM_OPTIONS:   -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS

[2024-12-07T17:47:49.402Z] executing testRSA_2048
[2024-12-07T17:50:44.637Z] java.security.ProviderException: Failure in generateKeyPair
[2024-12-07T17:50:44.638Z] 	at openjceplus/com.ibm.crypto.plus.provider.OpenJCEPlusFIPS.providerException(OpenJCEPlusFIPS.java:850)
[2024-12-07T17:50:44.638Z] 	at openjceplus/com.ibm.crypto.plus.provider.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:125)
[2024-12-07T17:50:44.638Z] 	at openjceplus/com.ibm.crypto.plus.provider.RSAKeyPairGenerator$Legacy.generateKeyPair(RSAKeyPairGenerator.java:129)
[2024-12-07T17:50:44.638Z] 	at java.base/java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:722)
[2024-12-07T17:50:44.638Z] 	at ibm.jceplus.junit.base.BaseTestRSA.setUp(BaseTestRSA.java:89)
[2024-12-07T17:50:44.638Z] 	at junit.framework.TestCase.runBare(TestCase.java:140)
[2024-12-07T17:50:44.638Z] 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2024-12-07T17:50:44.638Z] 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2024-12-07T17:50:44.638Z] 	at junit.framework.TestResult.run(TestResult.java:125)
[2024-12-07T17:50:44.638Z] 	at junit.framework.TestCase.run(TestCase.java:130)
[2024-12-07T17:50:44.638Z] 	at junit.framework.TestSuite.runTest(TestSuite.java:241)
[2024-12-07T17:50:44.638Z] 	at junit.framework.TestSuite.run(TestSuite.java:236)
[2024-12-07T17:50:44.638Z] Caused by: com.ibm.crypto.plus.provider.ock.OCKException: ICC_RSA_generate_key() failed
[2024-12-07T17:50:44.638Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.RSAKey.generateKeyPair(RSAKey.java:41)
[2024-12-07T17:50:44.638Z] 	at openjceplus/com.ibm.crypto.plus.provider.RSAKeyPairGenerator.generateKeyPair(RSAKeyPairGenerator.java:119)
[2024-12-07T17:50:44.638Z] 	... 10 more

[2024-12-07T18:36:32.978Z] openJcePlusTests_0_FAILED
```

FYI @jasonkatonica

**Comment by JinhangZhang** [comment]
Hi, after rerunning 250x, 500x iterations, we could not encounter the failure.

FYI @jasonkatonica
