### ISSUE TITLE
OpenJDK Package/PackageFromManifest UncheckedIOException NoSuchFileException omrvmem_

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20782]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OMR_testList_0/192
jdk_lang_0
java/lang/Package/PackageFromManifest.java
```
20:21:08  java.io.UncheckedIOException: java.nio.file.NoSuchFileException: ./omrvmem_002594318_Ej4ECJ
20:21:08  	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
20:21:08  	at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
20:21:08  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
20:21:08  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
20:21:08  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
20:21:08  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
20:21:08  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
20:21:08  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
20:21:08  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
20:21:08  	at jdk.test.lib.compiler.CompilerUtils.compile(CompilerUtils.java:110)
20:21:08  	at jdk.test.lib.compiler.CompilerUtils.compile(CompilerUtils.java:69)
20:21:08  	at PackageFromManifest.createTestClass(PackageFromManifest.java:149)
20:21:08  	at PackageFromManifest.setup(PackageFromManifest.java:264)
20:21:08  	at PackageFromManifest.main(PackageFromManifest.java:120)
20:21:08  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:21:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
20:21:08  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
20:21:08  	at java.base/java.lang.Thread.run(Thread.java:1595)
20:21:08  Caused by: java.nio.file.NoSuchFileException: ./omrvmem_002594318_Ej4ECJ
20:21:08  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
20:21:08  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
20:21:08  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
20:21:08  	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
20:21:08  	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
20:21:08  	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
20:21:08  	at java.base/java.nio.file.Files.readAttributes(Files.java:1854)
20:21:08  	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
20:21:08  	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
20:21:08  	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
20:21:08  	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)
20:21:08  	... 17 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/396
`Caused by: java.nio.file.NoSuchFileException: ./omrvmem_003871063_KBIHTZ`

**Comment by pshipton** [comment]
@mpirvu does this file seem familiar to you?

**Comment by mpirvu** [comment]
These look similar to the hidden files used as a backing for data structures that we want to disclaim. However, java code should not ask about them.

**Comment by pshipton** [comment]
If it's a hidden file on Linux, I think it needs to start with `.`.

**Comment by mpirvu** [comment]
On mys system those backing files appear as
`/opt/IBM/OL-24.0.0.2/liberty/usr/servers/acmeairee8/omrvmem_000219066_Ig4oyo (deleted)`

**Comment by pshipton** [comment]
I guess sometimes they get created in an unexpected place?

**Comment by mpirvu** [comment]
50x grinder of the failing test on the same machine: https://openj9-jenkins.osuosl.org/job/Grinder/4101/
All tests have passed.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OMR_testList_2/228 - [cent9-aarch64-3](https://openj9-jenkins.osuosl.org/computer/cent9-aarch64-3)
jdk_lang_j9_1
java/lang/Package/PackageFromManifest.java
`java.nio.file.NoSuchFileException: ./omrvmem_002333373_NKTUOu`

**Comment by hzongaro** [comment]
Moving this out to the 0.52 release.

**Comment by pshipton** [comment]
@mpirvu fyi there are a number of failures related to omrvmem files. Some I found.

https://github.com/eclipse-openj9/openj9/issues/21049
https://github.com/eclipse-openj9/openj9/issues/20293
https://github.com/eclipse-openj9/openj9/issues/11800

**Comment by mpirvu** [comment]
I looked at the mentioned issues.
In #20293 and #11800 the test fails because if finds the `omrvmem_` file and it was not expected to see it. These file can be created at different points during JVM lifetime and as such I regard this as a shortcoming of the test and not as a true failure.
For #21049 it's the opposite, the test complains that the `omrvmem_` file has gone away. I'll look more into this case

**Comment by mpirvu** [comment]
The test fails when executing:
```
        List<Path> sources
            = Files.find(source, (recurse ? Integer.MAX_VALUE : 1),
                (file, attrs) -> (file.toString().endsWith(".java")))
                .collect(Collectors.toList());
```
The omr code creates a temporary file and immediately unlinks it from the file system:
```
		        snprintf(filename, sizeof(filename), "omrvmem_%09d_XXXXXX", getpid());
			fd = mkostemp(filename, 0);
			if (OMRPORT_INVALID_FD != fd) {
				unlink(filename);
```
After the unlink, the file will continue to exist on disk until the JVM terminates.
Immediately after `mkostemp` the file can be seen in the current directory, but no so after `unlink`. Thus, there is a very short window of time when the file is visible.
I am guessing that the Java code mentioned above finds the `omrvmem` file and expects it to find it again when is doing the processing.

**Comment by mpirvu** [comment]
I am planning to implement the following change:
1. Change the default storage directory from the current directory to /tmp
2. If /tmp is mounted on tmpfs, ramfs (both of which use memory) or nfs (latency is unpredictable) then attempt to disclaim on swap
3. If swap is also not available, disable disclaiming

**Comment by hzongaro** [comment]
@mpirvu, can this issue be closed now that #22246 has been merged, or do you think there is something more that needs to be done - for instance, changing the way the test works?

**Comment by mpirvu** [comment]
This issue can be closed now as fixed by #22246
