### ISSUE TITLE
jdk_security1_0 FAILED java/security/Security/ConfigFileTest.java RuntimeException: OpenJCEPlusFIPS is not present in the java.security file.

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20788]
**Failure link**
---
From internal [Test_openjdk21_j9_sanity.openjdk_x86-64_linux_fips140_3_openjceplusfips](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_fips140_3_openjceplusfips/16/) (rtj-rhel9x86-rtp-test-3lkaa-1)

```**Java Version**
java version "21.0.6-beta" 2025-01-21
IBM Semeru Runtime Certified Edition 21.0.6+6-202412071603 (build 21.0.6-beta+6-202412071603)
Eclipse OpenJ9 VM 21.0.6+6-202412071603 (build master-501751012f, JRE 21 Linux amd64-64-Bit Compressed References 20241207_325 (JIT enabled, AOT enabled)
OpenJ9   - 501751012f
OMR      - b893b2be2
JCL      - 71fff4eae based on jdk-21.0.6+6)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security1_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=FIPS140_3_OpenJCEPlusFIPS&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-x64-openj9-IBM%2F325%2Fibm-semeru-certified-jdk_x64_linux_JDK21U_2024-12-07-16-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-x64-openj9-IBM%2F325%2Fibm-semeru-certified-testimage_x64_linux_JDK21U_2024-12-07-16-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=120&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=Dynamic) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-12-07T16:53:27.767Z] variation: Mode150
[2024-12-07T16:53:27.767Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS

[2024-12-07T16:56:53.945Z] TEST: java/security/Security/ConfigFileTest.java

[2024-12-07T16:56:53.949Z]  stderr: [properties: java.security
[2024-12-07T16:56:53.949Z] properties: overriding other security properties files!
[2024-12-07T16:56:53.949Z] properties: java.security
[2024-12-07T16:56:53.949Z] properties: Initial security property: security.provider.1=sun.security.provider.Sun
[2024-12-07T16:56:53.949Z] properties: Initial security property: security.provider.2=SunRsaSign
[2024-12-07T16:56:53.949Z] properties: Initial security property: security.provider.3=sun.security.ssl.SunJSSE
[2024-12-07T16:56:53.949Z] properties: Initial security property: security.provider.4=com.sun.crypto.provider.SunJCE
[2024-12-07T16:56:53.949Z] properties: Initial security property: security.provider.5=SunJGSS
[2024-12-07T16:56:53.949Z] properties: Initial security property: security.provider.6=SunSASL
[2024-12-07T16:56:53.949Z] semerufips: Restricted security mode is being enabled...
[2024-12-07T16:56:53.949Z] semerufips: Profile specified without version (i.e., <profile>): OpenJCEPlusFIPS
[2024-12-07T16:56:53.949Z] java.lang.RuntimeException: OpenJCEPlusFIPS is not present in the java.security file.
[2024-12-07T16:56:53.949Z] 	at java.base/openj9.internal.security.RestrictedSecurity.printStackTraceAndExit(RestrictedSecurity.java:663)
[2024-12-07T16:56:53.949Z] 	at java.base/openj9.internal.security.RestrictedSecurity.getProfileID(RestrictedSecurity.java:369)
[2024-12-07T16:56:53.949Z] 	at java.base/openj9.internal.security.RestrictedSecurity.configure(RestrictedSecurity.java:476)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.Security.initialize(Security.java:146)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.Security.lambda$static$0(Security.java:96)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:695)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.Security.<clinit>(Security.java:95)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:43)
[2024-12-07T16:56:53.949Z] 	at java.base/java.io.FilePermission.init(FilePermission.java:319)
[2024-12-07T16:56:53.949Z] 	at java.base/java.io.FilePermission.<init>(FilePermission.java:490)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.net.www.protocol.file.FileURLConnection.getPermission(FileURLConnection.java:217)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.security.util.LazyCodeSourcePermissionCollection.ensureAdded(LazyCodeSourcePermissionCollection.java:69)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.security.util.LazyCodeSourcePermissionCollection.toString(LazyCodeSourcePermissionCollection.java:115)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.String.valueOf(String.java:5237)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.ProtectionDomain.toString(ProtectionDomain.java:434)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.String.valueOf(String.java:5237)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.SecureClassLoader$1.apply(SecureClassLoader.java:231)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.SecureClassLoader$1.apply(SecureClassLoader.java:222)
[2024-12-07T16:56:53.949Z] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.SecureClassLoader.getProtectionDomain(SecureClassLoader.java:222)
[2024-12-07T16:56:53.949Z] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[2024-12-07T16:56:53.949Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
[2024-12-07T16:56:53.949Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
[2024-12-07T16:56:53.949Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
[2024-12-07T16:56:53.949Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
[2024-12-07T16:56:53.949Z] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1103)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.Class.forNameImpl(Native Method)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.Class.forNameHelper(Class.java:452)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.Class.forName(Class.java:430)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:811)
[2024-12-07T16:56:53.949Z] 	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:706)
[2024-12-07T16:56:53.949Z] ]
[2024-12-07T16:56:53.949Z]  exitValue = 1
[2024-12-07T16:56:53.949Z] 
[2024-12-07T16:56:53.949Z] java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [1]
[2024-12-07T16:56:53.949Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:500)
[2024-12-07T16:56:53.949Z] 	at ConfigFileTest.exerciseSecurity(ConfigFileTest.java:137)
[2024-12-07T16:56:53.949Z] 	at ConfigFileTest.main(ConfigFileTest.java:99)
[2024-12-07T16:56:53.949Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-12-07T16:56:53.949Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
[2024-12-07T16:56:53.949Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)
[2024-12-07T16:56:53.949Z] 
[2024-12-07T16:56:53.949Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2024-12-07T16:56:53.949Z] JavaTest Message: shutting down test
[2024-12-07T16:56:53.949Z] 
[2024-12-07T16:56:53.949Z] 
[2024-12-07T16:56:53.949Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0], exit value is: [1]
[2024-12-07T16:56:53.949Z] --------------------------------------------------
[2024-12-07T16:56:55.849Z] Test results: passed: 118; failed: 1
[2024-12-07T16:57:19.556Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_fips140_3_openjceplusfips/aqa-tests/TKG/output_17335904065439/jdk_security1_0/report/html/report.html
[2024-12-07T16:57:19.556Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_fips140_3_openjceplusfips/aqa-tests/TKG/output_17335904065439/jdk_security1_0/work
[2024-12-07T16:57:19.556Z] Error: Some tests failed or other problems occurred.
[2024-12-07T16:57:19.556Z] -----------------------------------
[2024-12-07T16:57:19.556Z] jdk_security1_0_FAILED
```

[5x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45762/)

FYI @jasonkatonica

**Comment by KostasTsiounis** [comment]
This test is using random java.security files in the test [on this line](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/28763cfc02c044c01a686199c9c4f4a8cae54503/test/jdk/java/security/Security/ConfigFileTest.java#L95), most likely they do not contain a profile. 

The test was recently updated. In the past, the flags passed weren't utilized, but that changed with [this](https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/c3b5705a8b2fa11355cabb273511b754df07fe4f) commit. After that, the FIPS flag are honoured and RestrictedSecurity tries to find an `OpenJCEPlusFIPS` profile and fails.

This test should probably be excluded, as trying different `java.security` files that don't contain the FIPS profiles is not applicable.

**Comment by JasonFengJ9** [comment]
Excluded by
* https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/241

**Comment by JasonFengJ9** [comment]
Occurred at [openjdk17_j9_sanity.openjdk_ppc64le_linux_fips140_3_openjceplusfips](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_fips140_3_openjceplusfips/34/)
```
[2025-02-15T16:41:26.509Z] variation: Mode150
[2025-02-15T16:41:26.509Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS

[2025-02-15T16:45:20.527Z] TEST: java/security/Security/ConfigFileTest.java

[2025-02-15T16:45:20.528Z] STDERR:
[2025-02-15T16:45:20.528Z]  stdout: [];
[2025-02-15T16:45:20.528Z]  stderr: [properties: java.security
[2025-02-15T16:45:20.528Z] properties: overriding other security properties files!
[2025-02-15T16:45:20.528Z] properties: java.security
[2025-02-15T16:45:20.528Z] properties: Initial security property: security.provider.1=sun.security.provider.Sun
[2025-02-15T16:45:20.528Z] properties: Initial security property: security.provider.2=SunRsaSign
[2025-02-15T16:45:20.528Z] properties: Initial security property: security.provider.3=sun.security.ssl.SunJSSE
[2025-02-15T16:45:20.528Z] properties: Initial security property: security.provider.4=com.sun.crypto.provider.SunJCE
[2025-02-15T16:45:20.528Z] properties: Initial security property: security.provider.5=SunJGSS
[2025-02-15T16:45:20.528Z] properties: Initial security property: security.provider.6=SunSASL
[2025-02-15T16:45:20.528Z] semerufips: Restricted security mode is being enabled...
[2025-02-15T16:45:20.528Z] semerufips: Profile specified without version (i.e., <profile>): OpenJCEPlusFIPS
[2025-02-15T16:45:20.528Z] java.lang.RuntimeException: OpenJCEPlusFIPS is not present in the java.security file.
[2025-02-15T16:45:20.528Z] 	at java.base/openj9.internal.security.RestrictedSecurity.printStackTraceAndExit(RestrictedSecurity.java:663)
[2025-02-15T16:45:20.528Z] 	at java.base/openj9.internal.security.RestrictedSecurity.getProfileID(RestrictedSecurity.java:369)
[2025-02-15T16:45:20.528Z] 	at java.base/openj9.internal.security.RestrictedSecurity.configure(RestrictedSecurity.java:476)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.Security.initialize(Security.java:147)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.Security$1.run(Security.java:96)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.Security$1.run(Security.java:94)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:695)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.Security.<clinit>(Security.java:94)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:45)
[2025-02-15T16:45:20.528Z] 	at java.base/java.io.FilePermission.init(FilePermission.java:319)
[2025-02-15T16:45:20.528Z] 	at java.base/java.io.FilePermission.<init>(FilePermission.java:490)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.net.www.protocol.file.FileURLConnection.getPermission(FileURLConnection.java:226)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.security.util.LazyCodeSourcePermissionCollection.ensureAdded(LazyCodeSourcePermissionCollection.java:69)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.security.util.LazyCodeSourcePermissionCollection.toString(LazyCodeSourcePermissionCollection.java:115)
[2025-02-15T16:45:20.528Z] 	at java.base/java.lang.String.valueOf(String.java:4992)
[2025-02-15T16:45:20.528Z] 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.ProtectionDomain.toString(ProtectionDomain.java:429)
[2025-02-15T16:45:20.528Z] 	at java.base/java.lang.String.valueOf(String.java:4992)
[2025-02-15T16:45:20.528Z] 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.SecureClassLoader$1.apply(SecureClassLoader.java:230)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.SecureClassLoader$1.apply(SecureClassLoader.java:222)
[2025-02-15T16:45:20.528Z] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.SecureClassLoader.getProtectionDomain(SecureClassLoader.java:222)
[2025-02-15T16:45:20.528Z] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[2025-02-15T16:45:20.528Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1174)
[2025-02-15T16:45:20.528Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:961)
[2025-02-15T16:45:20.528Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:867)
[2025-02-15T16:45:20.528Z] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
[2025-02-15T16:45:20.528Z] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[2025-02-15T16:45:20.528Z] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
[2025-02-15T16:45:20.528Z] 	at java.base/java.lang.Class.forNameImpl(Native Method)
[2025-02-15T16:45:20.528Z] 	at java.base/java.lang.Class.forName(Class.java:428)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:808)
[2025-02-15T16:45:20.528Z] 	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:703)
[2025-02-15T16:45:20.528Z] ]
[2025-02-15T16:45:20.528Z]  exitValue = 1

[2025-02-15T16:45:56.109Z] -----------------------------------
[2025-02-15T16:45:56.109Z] jdk_security1_0_FAILED
```

**Comment by pshipton** [comment]
@jasonkatonica seems it needs to be excluded for 17 as well, and perhaps other versions.

**Comment by jasonkatonica** [comment]
This test is already on the ignore list for Java 21 and higher releases. I am unsure why the excludes list is not being applied here on Java 21 as we expect. Perhaps an older excludes list is being used somehow?

The exclusions for strict and weak profiles for FIPS 140-3 can be found at:

https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/ProblemList-FIPS140_3_OpenJCEPlusFIPS.FIPS140-3.txt#L235

https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt#L229

As for backporting, yes I believe that this same test is present on earlier releases. It needs to be excluded on 17 and on 11. 

I opened two PRs on those releases.

Java 11 => https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/867
Java 17 => https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/437

**Comment by JasonFengJ9** [comment]
> This test is already on the ignore list for Java 21 and higher releases. I am unsure why the excludes list is not being applied here on Java 21 as we expect. Perhaps an older excludes list is being used somehow?

The latest occurrence was on JDK17 - https://github.com/eclipse-openj9/openj9/issues/20788#issuecomment-2667107426

JDK 11/17 exclude PRs are merged now.

**Comment by jasonkatonica** [comment]
> The latest occurrence was on JDK17

Ok that explains it since we were not excluding the test on 17.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OpenJDK11_testList_0/73 - 11.0.32+1 acceptance build
jdk_security1
java/security/Security/ConfigFileTest.java
```
16:50:20  ProviderConfig: Loading legacy provider: OpenJCEPlus
16:50:20  ProviderConfig: Error loading legacy provider OpenJCEPlus
16:50:20  java.lang.ClassNotFoundException: OpenJCEPlus
16:50:20  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
16:50:20  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
16:50:20  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1085)
16:50:20  	at java.base/sun.security.jca.ProviderConfig$ProviderLoader.legacyLoad(ProviderConfig.java:409)
16:50:20  	at java.base/sun.security.jca.ProviderConfig$ProviderLoader.load(ProviderConfig.java:386)
16:50:20  	at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:264)
16:50:20  	at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:258)
16:50:20  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:699)
16:50:20  	at java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:258)
16:50:20  	at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:238)
16:50:20  	at java.base/sun.security.jca.ProviderList.loadAll(ProviderList.java:344)
16:50:20  	at java.base/sun.security.jca.ProviderList.removeInvalid(ProviderList.java:361)
16:50:20  	at java.base/sun.security.jca.Providers.getFullProviderList(Providers.java:201)
16:50:20  	at java.base/java.security.Security.getProviders(Security.java:521)
16:50:20  	at ConfigFileTest.main(ConfigFileTest.java:62)
16:50:20  ProviderConfig: Error loading provider OpenJCEPlus
```

~@jasonkatonica I assume the test needs to be excluded on jdk11 as well?~
I think this failure is different, I've created https://github.com/eclipse-openj9/openj9/issues/23925
