### ISSUE TITLE
jdk_restricted_security_0 FAILED openj9/internal/security/TestProviders.java RuntimeException: The order numbers of providers in profile RestrictedSecurity.Test-Profile.Extended_2 (or a base profile) are not consecutive

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20808]
**Failure link**
---
From internal [Test_openjdk11_j9_special.openjdk_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_special.openjdk_aarch64_linux/47/) (sles15-aarch64-2)

```**Java Version**
java version "11.0.26-beta" 2025-01-21
IBM Semeru Runtime Certified Edition 11.0.26+3-202412070209 (build 11.0.26-beta+3)
Eclipse OpenJ9 VM 11.0.26+3-202412070209 (build master-81ab91c3b3, JRE 11 Linux aarch64-64-Bit Compressed References 20241207_752 (JIT enabled, AOT enabled)
OpenJ9   - 81ab91c3b3
OMR      - b893b2be2
JCL      - 0ee1c65d17 based on jdk-11.0.26+3)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_restricted_security_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=openjdk&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F752%2Fibm-semeru-certified-jdk_aarch64_linux_JDK11U_2024-12-07-02-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F752%2Fibm-semeru-certified-jre_aarch64_linux_JDK11U_2024-12-07-02-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F752%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2024-12-07-02-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Fosb-tests.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=ibm_tlda&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=120&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=Dynamic) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-12-07T03:44:04.661Z] variation: NoOptions
[2024-12-07T03:44:04.661Z] JVM_OPTIONS:  -Xverbosegclog 

[2024-12-07T03:44:26.184Z] TEST: openj9/internal/security/TestProviders.java

[2024-12-07T03:44:26.185Z] STDERR:
[2024-12-07T03:44:26.185Z] STARTED    TestProviders::shouldContain_expectedExitValue0 '[1] TestBase.Version, /home/jenkins/workspace/Test_openjdk11_j9_special.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/closed/test/jdk/openj9/internal/security/provider-java.security, (?s)(?=.*Sun)(?=.*\bSunJCE\b)(?=.*SunJSSE)'
[2024-12-07T03:44:26.185Z]  stdout: [Provider Name: SUN
[2024-12-07T03:44:26.185Z] Provider Version: 11
[2024-12-07T03:44:26.185Z] Provider Name: SunJCE
[2024-12-07T03:44:26.185Z] Provider Version: 11
[2024-12-07T03:44:26.185Z] ];
[2024-12-07T03:44:26.185Z]  stderr: []
[2024-12-07T03:44:26.185Z]  exitValue = 0
[2024-12-07T03:44:26.185Z] 
[2024-12-07T03:44:26.185Z]  stdout: [Provider Name: SUN
[2024-12-07T03:44:26.185Z] Provider Version: 11
[2024-12-07T03:44:26.185Z] Provider Name: SunJCE
[2024-12-07T03:44:26.185Z] Provider Version: 11
[2024-12-07T03:44:26.185Z] ];
[2024-12-07T03:44:26.185Z]  stderr: []
[2024-12-07T03:44:26.185Z]  exitValue = 0
[2024-12-07T03:44:26.185Z] 
[2024-12-07T03:44:26.185Z] java.lang.RuntimeException: '(?s)(?=.*Sun)(?=.*\bSunJCE\b)(?=.*SunJSSE)' missing from stdout/stderr 
[2024-12-07T03:44:26.185Z] 
[2024-12-07T03:44:26.185Z] 	at jdk.test.lib.process.OutputAnalyzer.shouldMatch(OutputAnalyzer.java:282)
[2024-12-07T03:44:26.185Z] 	at TestProviders.shouldContain_expectedExitValue0(TestProviders.java:133)

....

[2024-12-07T03:44:26.190Z] STARTED    TestProviders::shouldContain_expectedExitValue1 '[3] Test-Profile.Extended_2, /home/jenkins/workspace/Test_openjdk11_j9_special.openjdk_aarch64_linux/aqa-tests/openjdk/openjdk-jdk/closed/test/jdk/openj9/internal/security/provider-java.security, The order numbers of providers in profile RestrictedSecurity.Test-Profile.Extended_2 \(or a base profile\) are not consecutive.'
[2024-12-07T03:44:26.190Z]  stdout: [];
[2024-12-07T03:44:26.190Z]  stderr: [java.lang.RuntimeException: The order numbers of providers in profile RestrictedSecurity.Test-Profile.Extended_2 (or a base profile) are not consecutive.
[2024-12-07T03:44:26.190Z] 	at java.base/openj9.internal.security.RestrictedSecurity.printStackTraceAndExit(RestrictedSecurity.java:665)
[2024-12-07T03:44:26.190Z] 	at java.base/openj9.internal.security.RestrictedSecurity$ProfileParser.checkProfileCheck(RestrictedSecurity.java:1807)
[2024-12-07T03:44:26.190Z] 	at java.base/openj9.internal.security.RestrictedSecurity$ProfileParser.<init>(RestrictedSecurity.java:1037)
[2024-12-07T03:44:26.190Z] 	at java.base/openj9.internal.security.RestrictedSecurity.configure(RestrictedSecurity.java:482)
[2024-12-07T03:44:26.190Z] 	at java.base/java.security.Security.initialize(Security.java:128)
[2024-12-07T03:44:26.190Z] 	at java.base/java.security.Security$1.run(Security.java:91)
[2024-12-07T03:44:26.190Z] 	at java.base/java.security.Security$1.run(Security.java:89)
[2024-12-07T03:44:26.190Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:693)
[2024-12-07T03:44:26.190Z] 	at java.base/java.security.Security.<clinit>(Security.java:89)
[2024-12-07T03:44:26.190Z] 	at TestProviders.main(TestProviders.java:151)
[2024-12-07T03:44:26.190Z] ]
[2024-12-07T03:44:26.190Z]  exitValue = 1

[2024-12-07T03:44:29.044Z] -----------------------------------
[2024-12-07T03:44:29.044Z] jdk_restricted_security_0_FAILED

```

FYI @jasonkatonica

**Comment by JasonFengJ9** [comment]
Sure, closing.
