### ISSUE TITLE
zlinux OpenJDK jdk_lang_j9_0 NullPointerException at java.base/java.lang.Integer.parseInt(Integer.java)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20852]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly_testList_2/371/
jdk_lang_j9_0
02:58:15  	TEST: java/lang/Character/UnicodeCasingTest.java
```
02:34:49  java.lang.NullPointerException
02:34:49  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:34:49  	at UnicodeCasingTest.convert(UnicodeCasingTest.java:170)
02:34:49  	at UnicodeCasingTest.test(UnicodeCasingTest.java:112)
02:34:49  	at UnicodeCasingTest.test(UnicodeCasingTest.java:80)
02:34:49  	at UnicodeCasingTest.main(UnicodeCasingTest.java:54)
```
02:58:15          TEST: java/lang/ClassLoader/getResource/modules/ResourcesTest.java
```
02:34:52  java.lang.NullPointerException
02:34:52  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:34:52  	at java.base/java.lang.Integer.parseInt(Integer.java:770)
02:34:52  	at org.testng.reporters.XMLReporterConfig$StackTraceLevels.parse(XMLReporterConfig.java:250)
02:34:52  	at org.testng.reporters.XMLReporterConfig.<init>(XMLReporterConfig.java:96)
02:34:52  	at org.testng.reporters.XMLReporter.<init>(XMLReporter.java:26)
```
02:58:15          TEST: java/lang/ClassLoader/getResource/GetResource.java
```
02:34:52  java.lang.NullPointerException
02:34:52  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:34:52  	at java.base/java.lang.Integer.parseInt(Integer.java:770)
02:34:52  	at org.testng.reporters.XMLReporterConfig$StackTraceLevels.parse(XMLReporterConfig.java:250)
02:34:52  	at org.testng.reporters.XMLReporterConfig.<init>(XMLReporterConfig.java:96)
02:34:52  	at org.testng.reporters.XMLReporter.<init>(XMLReporter.java:26)
```
02:58:15          TEST: java/lang/Integer/Decode.java
```
02:35:04  java.lang.NullPointerException
02:35:04  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:35:04  	at java.base/java.lang.Integer.valueOf(Integer.java:957)
02:35:04  	at java.base/java.lang.Integer.decode(Integer.java:1428)
02:35:04  	at Decode.check(Decode.java:48)
02:35:04  	at Decode.main(Decode.java:62)
```
02:58:15          TEST: java/lang/Integer/ParsingTest.java
```
02:35:04  java.lang.NullPointerException
02:35:04  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:35:04  	at java.base/java.lang.Integer.parseInt(Integer.java:770)
02:35:04  	at ParsingTest.check(ParsingTest.java:114)
02:35:04  	at ParsingTest.main(ParsingTest.java:56)
```
02:58:15          TEST: java/lang/Integer/Unsigned.java
```
02:35:04  java.lang.NullPointerException
02:35:04  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:35:04  	at java.base/java.lang.Integer.parseUnsignedInt(Integer.java:832)
02:35:04  	at Unsigned.testRoundtrip(Unsigned.java:54)
02:35:04  	at Unsigned.main(Unsigned.java:34)
```
02:58:15          TEST: java/lang/invoke/condy/BootstrapMethodJumboArgsTest.java
```
02:35:09  java.lang.NullPointerException
02:35:09  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:35:09  	at java.base/java.lang.Integer.parseInt(Integer.java:770)
02:35:09  	at org.testng.reporters.XMLReporterConfig$StackTraceLevels.parse(XMLReporterConfig.java:250)
02:35:09  	at org.testng.reporters.XMLReporterConfig.<init>(XMLReporterConfig.java:96)
02:35:09  	at org.testng.reporters.XMLReporter.<init>(XMLReporter.java:26)
```
02:58:15          TEST: java/lang/invoke/condy/CondyBSMInvocation.java
```
02:35:09  java.lang.NullPointerException
02:35:09  	at java.base/java.lang.Integer.parseInt(Integer.java)
02:35:09  	at java.base/java.lang.Integer.parseInt(Integer.java:770)
02:35:09  	at org.testng.reporters.XMLReporterConfig$StackTraceLevels.parse(XMLReporterConfig.java:250)
02:35:09  	at org.testng.reporters.XMLReporterConfig.<init>(XMLReporterConfig.java:96)
02:35:09  	at org.testng.reporters.XMLReporter.<init>(XMLReporter.java:26)
```
02:58:15          TEST: java/lang/invoke/condy/CondyBSMValidationTest.java
02:58:15          TEST: java/lang/invoke/condy/CondyInterfaceWithOverpassMethods.java
02:58:15          TEST: java/lang/invoke/condy/CondyNameValidationTest.java
02:58:15          TEST: java/lang/invoke/condy/CondyRepeatFailedResolution.java
02:58:15          TEST: java/lang/invoke/condy/CondyReturnPrimitiveTest.java
02:58:15          TEST: java/lang/invoke/condy/CondyWrongType.java
02:58:15          TEST: java/lang/invoke/condy/ConstantBootstrapsTest.java

**Comment by pshipton** [comment]
Rerun in grinder passed
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/4037/ - [rh8-390-1](https://openj9-jenkins.osuosl.org/computer/rh8-390-1)

5x x 5 grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/4038/

**Comment by pshipton** [comment]
@hzongaro fyi

**Comment by pshipton** [comment]
Seems a dup of https://github.com/eclipse-openj9/openj9/issues/19890, for which there was a new occurrence.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Release_testList_2/27 - 0.49

**Comment by hzongaro** [comment]
As I mentioned [above](https://github.com/eclipse-openj9/openj9/issues/20852#issuecomment-2551999063), I suspect this is another instance of #17515.

Running `jdk_lang_j9_0` in a 5x30 [internal grinder run without the fix](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/46976) for #17515 resulted in 3/150 failures; two failures were due to issue #17323, while the third was due to this issue.  A second [internal grinder run with the fix](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/46977) resulted in 2/150 failures, both due to issue #17323.

Those obviously aren't conclusive results.  I will just keep this issue open for the next few weeks to see whether there is any reoccurrence.

**Comment by hzongaro** [comment]
Although the symptom and affected test differ from those reported in #17515, the underlying cause of the problem appears to be the same. Closing as a duplicate.
