### ISSUE TITLE
jdk_security3_1 FAILED sun/security/ssl/X509TrustManagerImpl/distrust/Entrust.java DerInputStream.getLength(): lengthTag=109, too big

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20856]
**Failure link**
---
From internal [Test_openjdk17_j9_extended.openjdk_ppc64_aix_fips140_3_openjceplusfips.fips140-3_testList_0](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64_aix_fips140_3_openjceplusfips.fips140-3_testList_0/3/) (p10aix134)

```**Java Version**
openjdk version "17.0.14" 2025-01-21
IBM Semeru Runtime Open Edition 17.0.14.0-m2 (build 17.0.14+6)
Eclipse OpenJ9 VM 17.0.14.0-m2 (build v0.49.0-release-f4d977c71b, JRE 17 AIX ppc64-64-Bit Compressed References 20250121_867 (JIT enabled, AOT enabled)
OpenJ9   - f4d977c71b
OMR      - e49875871
JCL      - f2d3af9195a based on jdk-17.0.14+6)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=jdk_security3_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=9f50c848-8764-440d-b95a-1d295c21713e&amp;TEST_FLAG=FIPS140_3_OpenJCEPlusFIPS.FIPS140-3&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_extended.openjdk_ppc64_aix_fips140_3_openjceplusfips.fips140-3&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;LABEL=&amp;JCK_VERSION=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fui%2Fnative%2Fhyc-rt-java-delivery-generic-local%2FIBM%2Fjava%2Fsemeru-open%2F17.0%2F17.0.14.0%2Fm2%2F&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.5-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;BUILD_TYPE=release&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=docker-na.artifactory.swg-devops.com%2Fsys-rt-docker-local&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JCK_GIT_BRANCH=main&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=%21sw.os.mac.10&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=3&amp;CONFIG_JSON=%5B%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22NONE%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22x86-64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_2%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFips140_2TestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFips140_2TestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFips140_2TestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS.FIPS140-3%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%0A%5D&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;OPENJDK_SHA=&amp;RERUN_FAILURE=true&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;separator-87e3a7db-4843-4907-ad26-40f469fe3204=&amp;TIME_LIMIT=12&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-12-15T22:58:15.917Z] variation: Mode650
[2024-12-15T22:58:15.917Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS.FIPS140-3

[2024-12-15T23:04:39.057Z] TEST: sun/security/ssl/X509TrustManagerImpl/distrust/Entrust.java

[2024-12-15T23:04:39.068Z] STDERR:
[2024-12-15T23:04:39.068Z] java.security.KeyStoreException: problem accessing trust store
[2024-12-15T23:04:39.068Z] 	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
[2024-12-15T23:04:39.068Z] 	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282)
[2024-12-15T23:04:39.068Z] 	at Distrust.getTMF(Distrust.java:90)
[2024-12-15T23:04:39.068Z] 	at Entrust.main(Entrust.java:61)
[2024-12-15T23:04:39.068Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-12-15T23:04:39.069Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-12-15T23:04:39.069Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-12-15T23:04:39.069Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
[2024-12-15T23:04:39.069Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2024-12-15T23:04:39.069Z] 	at java.base/java.lang.Thread.run(Thread.java:853)
[2024-12-15T23:04:39.069Z] Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
[2024-12-15T23:04:39.069Z] 	at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:251)
[2024-12-15T23:04:39.069Z] 	at java.base/sun.security.util.DerValue.<init>(DerValue.java:444)
[2024-12-15T23:04:39.069Z] 	at java.base/sun.security.util.DerValue.<init>(DerValue.java:487)
[2024-12-15T23:04:39.069Z] 	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2012)
[2024-12-15T23:04:39.069Z] 	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
[2024-12-15T23:04:39.069Z] 	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:390)
[2024-12-15T23:04:39.070Z] 	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:336)
[2024-12-15T23:04:39.070Z] 	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:57)
[2024-12-15T23:04:39.070Z] 	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
[2024-12-15T23:04:39.070Z] 	... 9 more
[2024-12-15T23:04:39.070Z] 
[2024-12-15T23:04:39.070Z] JavaTest Message: Test threw exception: java.security.KeyStoreException: problem accessing trust store
```

[5x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45981/)

FYI @jasonkatonica

**Comment by jasonkatonica** [comment]
I was able to recreate this issue on an older 17.0.3:
```
# java -version
openjdk version "17.0.13" 2024-10-15
IBM Semeru Runtime Open Edition 17.0.13.11 (build 17.0.13+11)
Eclipse OpenJ9 VM 17.0.13.11 (build openj9-0.48.0, JRE 17 Linux amd64-64-Bit Compressed References 20241015_886 (JIT enabled, AOT enabled)
OpenJ9   - 1d5831436e
OMR      - d10a4d553
JCL      - d17dd58f8d7 based on jdk-17.0.13+11)
```
I was using this simplified test:
```
import java.io.File;
import java.time.*;
import java.util.*;
import javax.net.ssl.*;
import java.security.KeyStore;

public class TestLoad {

    public static void main(String[] args) throws Exception {
        TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX");
        tmf.init((KeyStore) null);
        System.out.println("Loaded default TrustManagerFactory factory keystore.");
    }
}
```
I could recreate the same issue with similar command line arguments using strict fips mode:
```
# java -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS.FIPS140-3 TestLoad.java
Exception in thread "main" java.security.KeyStoreException: problem accessing trust store
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282)
	at TestLoad.main(TestLoad.java:11)
Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:251)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:444)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:487)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2012)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:390)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:336)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:57)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282)
	at TestLoad.main(TestLoad.java:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:419)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
```
I then could "fix" the issue by adding the PKCS12 keystore back into the allowable list of algorithms using this profile to extend the strict fips profile:
```
# cat profile.pkcs12.java.security
RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3-withPKCS12.desc.name = OpenJCEPlusFIPS Cryptographic Module FIPS 140-3 with PKCS12 Support
RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3-withPKCS12.extends = RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3
RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3-withPKCS12.jce.provider.2 = sun.security.provider.Sun [+ \
  {KeyStore, PKCS12, *}]
RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3-withPKCS12.jce.provider.4 = com.sun.crypto.provider.SunJCE [ \
  {AlgorithmParameters, PBES2, *}, \
  {AlgorithmParameters, PBEWithHmacSHA256AndAES_256, *}, \
  {SecretKeyFactory, PBEWithMD5AndDES, *}, \
  {Cipher, PBEWithHmacSHA256AndAES_256, *}, \
  {Mac, HmacPBESHA256, *}]
```
This fixed the test allowing it to run without error:
```
# java -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS.FIPS140-3-withPKCS12 -Djava.security.properties=./profile.pkcs12.java.security TestLoad.java
Loaded default TrustManagerFactory factory keystore.
```

I don't believe that this issue is a blocker for .49 at the moment for a few reasons:

1. We have a workaround if a user runs into this. Almost all users of TLS configure PKCS12 files which we document in our documentation for FIPS 140-3 so the workaround would involve typical configuration used anyway ( making it less likely a user would run into this in strict fips mode ).
1.  I think we should provide a better error message for this error as seen someplace since it wont make much sense to users if they encounter this. However users will still fail here anyway until they configure / allow PKCS12 files even if we provide a better error message.
1. This behavior / failure has been present in previous releases. This new test however did expose the confusing stack trace.
