### ISSUE TITLE
dacapo-h2_0 FAILED Caused by: java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20858]
**Failure link**
---
From internal [Test_openjdk21_j9_sanity.perf_aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.perf_aarch64_linux/248/) (ubu22-aarch64-14)

```**Java Version**
openjdk version "21.0.6" 2025-01-21 LTS
IBM Semeru Runtime Open Edition 21.0.6.0-m2 (build 21.0.6+6-LTS)
Eclipse OpenJ9 VM 21.0.6.0-m2 (build v0.49.0-release-f4d977c71b, JRE 21 Linux aarch64-64-Bit Compressed References 20250121_328 (JIT enabled, AOT enabled)
OpenJ9   - f4d977c71b
OMR      - e49875871
JCL      - fadf18bf93f based on jdk-21.0.6+6)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=dacapo-h2_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=9f50c848-8764-440d-b95a-1d295c21713e&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;LABEL=&amp;JCK_VERSION=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fui%2Fnative%2Fhyc-rt-java-delivery-generic-local%2FIBM%2Fjava%2Fsemeru-open%2F21.0%2F21.0.6.0%2Fm2%2F&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.5-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;BUILD_TYPE=release&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=docker-na.artifactory.swg-devops.com%2Fsys-rt-docker-local&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JCK_GIT_BRANCH=main&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;CONFIG_JSON=%5B%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22NONE%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22aarch64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22aarch64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_2%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFips140_2TestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFips140_2TestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFips140_2TestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS.FIPS140-3%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%0A%5D&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=120&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;OPENJDK_SHA=&amp;RERUN_FAILURE=true&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=perf&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;separator-87e3a7db-4843-4907-ad26-40f469fe3204=&amp;TIME_LIMIT=12&amp;JVM_OPTIONS=&amp;PARALLEL=Dynamic) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-12-17T16:36:36.778Z] variation: NoOptions
[2024-12-17T16:36:36.778Z] JVM_OPTIONS:  

[2024-12-17T16:36:36.789Z] TESTING:
[2024-12-17T16:36:36.789Z] Using scaled threading model. 8 processors detected, 8 threads used to drive the workload, in a possible range of [1,4000]
[2024-12-17T16:36:54.278Z] java.lang.reflect.InvocationTargetException
[2024-12-17T16:36:54.278Z] java.lang.reflect.InvocationTargetException
[2024-12-17T16:36:54.278Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[2024-12-17T16:36:54.278Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-12-17T16:36:54.278Z] 	at org.dacapo.harness.H2.preIteration(H2.java:88)
[2024-12-17T16:36:54.278Z] 	at org.dacapo.harness.Benchmark.run(Benchmark.java:171)
[2024-12-17T16:36:54.278Z] 	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
[2024-12-17T16:36:54.278Z] 	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
[2024-12-17T16:36:54.278Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-12-17T16:36:54.278Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
[2024-12-17T16:36:54.278Z] 	at Harness.main(Unknown Source)
[2024-12-17T16:36:54.278Z] Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalArgumentException: bound must be positive"; SQL statement:
[2024-12-17T16:36:54.278Z] 
[2024-12-17T16:36:54.278Z] ALTER TABLE ORDERLINE ADD CONSTRAINT
[2024-12-17T16:36:54.278Z]     OL_S_FK FOREIGN KEY (OL_SUPPLY_W_ID, OL_I_ID) REFERENCES STOCK [50000-123]
[2024-12-17T16:36:54.278Z] 	at org.h2.message.Message.getSQLException(Message.java:111)
[2024-12-17T16:36:54.278Z] 	at org.h2.message.Message.convert(Message.java:288)
[2024-12-17T16:36:54.278Z] 	at org.h2.table.TableData.addRowsToIndex(TableData.java:334)
[2024-12-17T16:36:54.278Z] 	at org.h2.table.TableData.addIndex(TableData.java:245)
[2024-12-17T16:36:54.278Z] 	at org.h2.command.ddl.AlterTableAddConstraint.createIndex(AlterTableAddConstraint.java:275)
[2024-12-17T16:36:54.279Z] 	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:203)
[2024-12-17T16:36:54.279Z] 	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:89)
[2024-12-17T16:36:54.279Z] 	at org.h2.command.CommandContainer.update(CommandContainer.java:72)
[2024-12-17T16:36:54.279Z] 	at org.h2.command.Command.executeUpdate(Command.java:209)
[2024-12-17T16:36:54.279Z] 	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:162)
[2024-12-17T16:36:54.279Z] 	at org.h2.tools.RunScript.process(RunScript.java:166)
[2024-12-17T16:36:54.279Z] 	at org.h2.tools.RunScript.execute(RunScript.java:154)
[2024-12-17T16:36:54.279Z] 	at org.dacapo.h2.TPCC.runScript(Unknown Source)
[2024-12-17T16:36:54.279Z] 	at org.dacapo.h2.TPCC.runScript(Unknown Source)
[2024-12-17T16:36:54.279Z] 	at org.dacapo.h2.TPCC.runScript(Unknown Source)
[2024-12-17T16:36:54.279Z] 	at org.dacapo.h2.TPCC.createConstraints(Unknown Source)
[2024-12-17T16:36:54.279Z] 	at org.dacapo.h2.TPCC.preIterationMemoryDB(Unknown Source)
[2024-12-17T16:36:54.279Z] 	at org.dacapo.h2.TPCC.preIteration(Unknown Source)
[2024-12-17T16:36:54.279Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-12-17T16:36:54.279Z] 	... 8 more
[2024-12-17T16:36:54.279Z] Caused by: java.lang.IllegalArgumentException: bound must be positive
[2024-12-17T16:36:54.279Z] 	at java.base/java.util.Random.nextInt(Random.java:557)
[2024-12-17T16:36:54.279Z] 	at org.h2.util.RandomUtils.nextInt(RandomUtils.java:206)
[2024-12-17T16:36:54.279Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:300)
[2024-12-17T16:36:54.279Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.279Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.279Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.280Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.280Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.280Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.280Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.280Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:327)
[2024-12-17T16:36:54.280Z] 	at org.h2.util.ObjectArray.sort(ObjectArray.java:286)
[2024-12-17T16:36:54.280Z] 	at org.h2.table.TableData.addRowsToIndex(TableData.java:324)
[2024-12-17T16:36:54.280Z] 	... 24 more
[2024-12-17T16:36:54.280Z] -----------------------------------
[2024-12-17T16:36:54.280Z] dacapo-h2_0_FAILED
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/45995/)

**Comment by pshipton** [comment]
Different test, but also Random.nextInt().

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_0/1119
MiniMix_extended_3h_0 `-Xjit -Xgcpolicy:balanced -Xnocompressedrefs`
```
02:20:20  LT  testFailure: testStress(net.adoptopenjdk.test.concurrent.jsr166y.ThreadLocalRandomTest): bound must be positive
02:20:20  LT  java.lang.IllegalArgumentException: bound must be positive
02:20:20  LT  	at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:310)
02:20:20  LT  	at net.adoptopenjdk.test.concurrent.jsr166y.ThreadLocalRandomTest.testStress(ThreadLocalRandomTest.java:90)
02:20:20  LT  	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
```
