### ISSUE TITLE
Test-extended.functional-JDK11-linux_390-64_cmprssptrs VmArgumentTests_0 testMemoryLeaks

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#4426]
This occurred testing the 0.12 release branch.

https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-linux_390-64_cmprssptrs/147
```
FAILED: testMemoryLeaks
java.lang.AssertionError: -Xcheck:memory failed: stderr = WARNING: 4443 unfreed blocks remaining at shutdown!
WARNING: 0 blocks were ignored per ignoredCallsite parameter
WARNING: only 32 most recent leaked blocks will be described
port_shutdown_library describing block at 000003FF700137F0 (header at 000003FF700135F0):
Wrapped block size is 2640, allocation number is 7818
Block was allocated by StringTable.cpp:88
First 32 bytes:
000003FF700137F0: 00 00 00 00 00 00 00 08 00 00 01 08 00 00 01 94  ................
000003FF70013800: 00 00 00 00 00 00 00 00 00 00 00 00 13 FF 4F 88  ..............O.
port_shutdown_library describing block at 00000000870F1CD8 (header at 00000000870F1AD8):
Wrapped block size is 32768, allocation number is 7812
Block was allocated by segment.c:233
First 32 bytes:
00000000870F1CD0: -  -  -  -  -  -  -  -  00 00 00 00 87 0F 92 00          ........
00000000870F1CE0: 00 00 00 00 86 EA 6C 00 00 00 00 00 87 09 03 00  ......l.........
00000000870F1CF0: 00 00 00 00 86 EA 6C 00                          ......l.
port_shutdown_library describing block at 00000000870E9328 (header at 00000000870E9128):
Wrapped block size is 1032, allocation number is 7792
Block was allocated by segment.c:233
First 32 bytes:
00000000870E9320: -  -  -  -  -  -  -  -  00 00 00 00 87 0E 94 00          ........
00000000870E9330: E7 E7 87 0E 93 28 E7 E7 E7 E7 87 0E 93 28 E7 E7  .....(.......(..
00000000870E9340: E7 E7 87 0E 93 28 E7 E7                          .....(..
port_shutdown_library describing block at 000003FF60004B00 (header at 000003FF60004900):
Wrapped block size is 1104, allocation number is 7788
Block was allocated by segment.c:238
First 32 bytes:
000003FF60004B00: 00 00 04 50 00 00 00 00 00 00 01 E0 00 00 02 1A  ...P............
000003FF60004B10: 00 00 10 30 0A 84 08 00 00 00 00 01 00 00 01 10  ...0............
port_shutdown_library describing block at 000003FF70013390 (header at 000003FF70013190):
Wrapped block size is 16, allocation number is 7786
Block was allocated by jnicsup.cpp:1937
First 16 bytes:
000003FF70013390: 00 00 03 FF A0 A9 BC F8 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 0000000086F62300 (header at 0000000086F62100):
Wrapped block size is 1000, allocation number is 7784
Block was allocated by segment.c:233
First 32 bytes:
0000000086F62300: 00 00 00 00 86 F6 24 00 E7 E7 86 F6 23 00 E7 E7  ......$.....#...
0000000086F62310: E7 E7 86 F6 23 00 E7 E7 E7 E7 86 F6 23 00 E7 E7  ....#.......#...
port_shutdown_library describing block at 000003FF70012780 (header at 000003FF70012580):
Wrapped block size is 1992, allocation number is 7783
Block was allocated by segment.c:427
First 32 bytes:
000003FF70012780: 00 00 00 00 00 00 00 04 00 00 00 40 00 00 03 3C  ...........@...<
000003FF70012790: 00 00 00 00 00 00 00 00 00 00 00 00 30 A8 AC 88  ............0...
port_shutdown_library describing block at 000003FF70012000 (header at 000003FF70011E00):
Wrapped block size is 816, allocation number is 7779
Block was allocated by segment.c:238
First 32 bytes:
000003FF70012000: 00 00 03 30 00 00 00 00 00 00 01 40 00 00 01 9C  ...0.......@....
000003FF70012010: 00 00 10 30 08 84 08 00 00 00 00 01 00 00 00 CC  ...0............
port_shutdown_library describing block at 000003FF70011B50 (header at 000003FF70011950):
Wrapped block size is 94, allocation number is 7778
Block was allocated by ROMClassBuilder.cpp:299
First 32 bytes:
000003FF70011B50: 6A 64 6B 2F 69 6E 74 65 72 6E 61 6C 2F 72 65 66  jdk/internal/ref
000003FF70011B60: 2F 43 6C 65 61 6E 65 72 53 68 75 74 64 6F 77 6E  /CleanerShutdown
port_shutdown_library describing block at 000003FF7000FDB0 (header at 000003FF7000FBB0):
Wrapped block size is 6488, allocation number is 7773
Block was allocated by StringTable.cpp:88
First 32 bytes:
000003FF7000FDB0: 00 00 00 00 00 00 00 00 00 00 03 FF A0 28 C0 80  .............(..
000003FF7000FDC0: 00 00 03 FF 84 00 7F D0 00 00 03 FF A0 28 D3 60  .............(.`
port_shutdown_library describing block at 000003FF60004650 (header at 000003FF60004450):
Wrapped block size is 104, allocation number is 7767
Block was allocated by jnicsup.cpp:1937
First 32 bytes:
000003FF60004650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000003FF60004660: 00 00 00 00 00 00 00 00 00 00 03 FF A0 A9 BC D0  ................
port_shutdown_library describing block at 000003FF600041A0 (header at 000003FF60003FA0):
Wrapped block size is 104, allocation number is 7766
Block was allocated by jnicsup.cpp:1937
First 32 bytes:
000003FF600041A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000003FF600041B0: 00 00 00 00 00 00 00 00 00 00 03 FF A0 A9 BC A8  ................
port_shutdown_library describing block at 000003FF60003CF0 (header at 000003FF60003AF0):
Wrapped block size is 104, allocation number is 7765
Block was allocated by jnicsup.cpp:1937
First 32 bytes:
000003FF60003CF0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000003FF60003D00: 00 00 00 00 00 00 00 00 00 00 03 FF A0 A9 BC 80  ................
port_shutdown_library describing block at 000003FF60001840 (header at 000003FF60001640):
Wrapped block size is 8296, allocation number is 7760
Block was allocated by trclog.c:1022
First 32 bytes:
000003FF60001840: 55 54 54 42 00 00 20 68 00 00 00 05 00 00 00 00  UTTB.. h........
000003FF60001850: 00 00 03 FF 74 00 18 40 E7 E7 60 00 18 40 E7 E7  ....t..@..`..@..
port_shutdown_library describing block at 000003FF74001840 (header at 000003FF74001640):
Wrapped block size is 8296, allocation number is 7757
Block was allocated by trclog.c:1022
First 32 bytes:
000003FF74001840: 55 54 54 42 00 00 20 68 00 00 00 05 00 00 00 00  UTTB.. h........
000003FF74001850: 00 00 03 FF 6C 00 18 40 E7 E7 74 00 18 40 E7 E7  ....l..@..t..@..
port_shutdown_library describing block at 000003FF6C001840 (header at 000003FF6C001640):
Wrapped block size is 8296, allocation number is 7756
Block was allocated by trclog.c:1022
First 32 bytes:
000003FF6C001840: 55 54 54 42 00 00 20 68 00 00 00 05 00 00 00 00  UTTB.. h........
000003FF6C001850: 00 00 03 FF 70 00 18 60 E7 E7 6C 00 18 40 E7 E7  ....p..`..l..@..
port_shutdown_library describing block at 000003FF68001840 (header at 000003FF68001640):
Wrapped block size is 8296, allocation number is 7753
Block was allocated by trclog.c:1022
First 32 bytes:
000003FF68001840: 55 54 54 42 00 00 20 68 00 00 00 05 00 00 00 00  UTTB.. h........
000003FF68001850: 00 00 03 FF 84 00 18 40 E7 E7 68 00 18 40 E7 E7  .......@..h..@..
port_shutdown_library describing block at 000003FFA0ADBA60 (header at 000003FFA0ADB860):
Wrapped block size is 16, allocation number is 7732
Block was allocated by vmthread.c:138
First 16 bytes:
000003FFA0ADBA60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00000000870EAF80 (header at 00000000870EAD80):
Wrapped block size is 3200, allocation number is 7731
Block was allocated by vmthread.c:121
First 32 bytes:
00000000870EAF80: E7 E7 87 0E AF 80 E7 E7 E7 E7 87 0E AF 80 E7 E7  ................
00000000870EAF90: E7 E7 87 0E AF 80 E7 E7 E7 E7 87 0E AF 80 E7 E7  ................
port_shutdown_library describing block at 000003FFA0AD3F90 (header at 000003FFA0AD3D90):
Wrapped block size is 16, allocation number is 7716
Block was allocated by vmthread.c:138
First 16 bytes:
000003FFA0AD3F90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00000000870E8258 (header at 00000000870E8058):
Wrapped block size is 3200, allocation number is 7715
Block was allocated by vmthread.c:121
First 32 bytes:
00000000870E8250: -  -  -  -  -  -  -  -  E7 E7 87 0E 82 58 E7 E7          .....X..
00000000870E8260: E7 E7 87 0E 82 58 E7 E7 E7 E7 87 0E 82 58 E7 E7  .....X.......X..
00000000870E8270: E7 E7 87 0E 82 58 E7 E7                          .....X..
port_shutdown_library describing block at 000003FFA0ACB4B0 (header at 000003FFA0ACB2B0):
Wrapped block size is 16, allocation number is 7700
Block was allocated by vmthread.c:138
First 16 bytes:
000003FFA0ACB4B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 0000000086F61230 (header at 0000000086F61030):
Wrapped block size is 3200, allocation number is 7699
Block was allocated by vmthread.c:121
First 32 bytes:
0000000086F61230: E7 E7 86 F6 12 30 E7 E7 E7 E7 86 F6 12 30 E7 E7  .....0.......0..
0000000086F61240: E7 E7 86 F6 12 30 E7 E7 E7 E7 86 F6 12 30 E7 E7  .....0.......0..
port_shutdown_library describing block at 000003FFA0202060 (header at 000003FFA0201E60):
Wrapped block size is 16, allocation number is 7684
Block was allocated by vmthread.c:138
First 16 bytes:
000003FFA0202060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 0000000086F60160 (header at 0000000086F5FF60):
Wrapped block size is 3200, allocation number is 7683
Block was allocated by vmthread.c:121
First 32 bytes:
0000000086F60160: E7 E7 86 F6 01 60 E7 E7 E7 E7 86 F6 01 60 E7 E7  .....`.......`..
0000000086F60170: E7 E7 86 F6 01 60 E7 E7 E7 E7 86 F6 01 60 E7 E7  .....`.......`..
port_shutdown_library describing block at 000003FFA022BE50 (header at 000003FFA022BC50):
Wrapped block size is 82, allocation number is 7672
Block was allocated by stringhelpers.cpp:335
First 32 bytes:
000003FFA022BE50: 44 65 73 74 72 6F 79 4A 61 76 61 56 4D 20 68 65  DestroyJavaVM he
000003FFA022BE60: 6C 70 65 72 20 74 68 72 65 61 64 00 BE 50 E7 E7  lper thread..P..
port_shutdown_library describing block at 000003FFA018C820 (header at 000003FFA018C620):
Wrapped block size is 12, allocation number is 7671
Block was allocated by trcmain.c:1007
First 12 bytes:
000003FFA018C820: 4A 56 4D 56 4D 55 54 30 30 31 20 00              JVMVMUT001 .
port_shutdown_library describing block at 000003FFA097F2C0 (header at 000003FFA097F0C0):
Wrapped block size is 88, allocation number is 7670
Block was allocated by trcmain.c:997
First 32 bytes:
000003FFA097F2C0: 55 54 54 44 00 00 00 58 00 00 00 05 00 00 00 00  UTTD...X........
000003FFA097F2D0: 00 00 00 00 86 EA 59 00 00 00 03 FF A0 00 7A 30  ......Y.......z0
port_shutdown_library describing block at 000003FFA000D530 (header at 000003FFA000D330):
Wrapped block size is 104, allocation number is 7663
Block was allocated by ../../omr/port/common/omrtlshelpers.c:65
First 32 bytes:
000003FFA000D530: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000003FFA000D540: 00 00 00 02 FF FF FF 94 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 000003FFA01ED6A0 (header at 000003FFA01ED4A0):
Wrapped block size is 352, allocation number is 7661
Block was allocated by TLHAllocationInterface.cpp:57
First 32 bytes:
000003FFA01ED6A0: 00 00 00 00 00 00 01 50 00 00 00 00 D6 A0 E7 E7  .......P........
000003FFA01ED6B0: 00 00 03 FF 9F 6F 00 D8 00 00 03 FF 9F 68 65 B0  .....o.......he.
port_shutdown_library describing block at 000003FFA018C220 (header at 000003FFA018C020):
Wrapped block size is 88, allocation number is 7660
Block was allocated by OwnableSynchronizerObjectBufferStandard.cpp:47
First 32 bytes:
000003FFA018C220: 00 00 00 00 00 00 00 48 00 00 00 00 C2 20 E7 E7  .......H..... ..
000003FFA018C230: 00 00 03 FF 9F 6F 28 68 00 00 03 FF 9F 69 87 90  .....o(h.....i..
port_shutdown_library describing block at 000003FFA01F2BC0 (header at 000003FFA01F29C0):
Wrapped block size is 88, allocation number is 7659
Block was allocated by UnfinalizedObjectBufferStandard.cpp:47
First 32 bytes:
000003FFA01F2BC0: 00 00 00 00 00 00 00 48 00 00 00 00 2B C0 E7 E7  .......H....+...
000003FFA01F2BD0: 00 00 03 FF 9F 6F 2C B8 00 00 03 FF 9F 69 92 D8  .....o,......i..
Memory checker statistics:
Total blocks allocated = 7893 ( = most recent allocationNumber)
Total blocks freed = 3450
Total bytes allocated = 16931858
Total bytes freed = 2736649
Total unknown blocks ignored = 0
High water blocks allocated = 4646
High water bytes allocated = 14520606
Largest block ever allocated = size 833616, allocation number 315
Failed allocation attempts = 0
4443 allocated blocks totaling 14195209 bytes were not freed before shutdown!

	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.vmArguments.VmArgumentTests.testMemoryLeaks(VmArgumentTests.java:1264)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
5x grinder https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/240/

**Comment by pshipton** [comment]
Grinder passed, removing from 0.12 milestone plan.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-linux_390-64_cmprssptrs/192

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/18
```
FAILED: testMemoryLeaks
java.lang.AssertionError: -Xcheck:memory failed: stderr = WARNING: 4412 unfreed blocks remaining at shutdown!
WARNING: 0 blocks were ignored per ignoredCallsite parameter
WARNING: only 32 most recent leaked blocks will be described
port_shutdown_library describing block at 00007FF54400C820 (header at 00007FF54400C620):
Wrapped block size is 1040, allocation number is 7749
Block was allocated by segment.c:235
First 32 bytes:
00007FF54400C820: 00 C9 00 44 F5 7F 00 00 E7 E7 20 C8 00 44 E7 E7  ...D...... ..D..
00007FF54400C830: E7 E7 20 C8 00 44 E7 E7 E7 E7 20 C8 00 44 E7 E7  .. ..D.... ..D..
port_shutdown_library describing block at 00007FF54400BF80 (header at 00007FF54400BD80):
Wrapped block size is 1104, allocation number is 7745
Block was allocated by segment.c:238
First 32 bytes:
00007FF54400BF80: 50 04 00 00 00 00 00 00 E0 01 00 00 1A 02 00 00  P...............
00007FF54400BF90: 30 10 00 00 00 08 C4 0A 01 00 00 00 10 01 00 00  0...............
port_shutdown_library describing block at 00007FF540001840 (header at 00007FF540001640):
Wrapped block size is 8296, allocation number is 7741
Block was allocated by trclog.c:1022
First 32 bytes:
00007FF540001840: 55 54 54 42 68 20 00 00 05 00 00 00 00 00 00 00  UTTBh ..........
00007FF540001850: 40 18 00 54 F5 7F 00 00 E7 E7 40 18 00 40 E7 E7  @..T......@..@..
port_shutdown_library describing block at 00007FF6FCCDCEE0 (header at 00007FF6FCCDCCE0):
Wrapped block size is 3000, allocation number is 7720
Block was allocated by vmthread.c:123
First 32 bytes:
00007FF6FCCDCEE0: E7 E7 E0 CE CD FC E7 E7 E7 E7 E0 CE CD FC E7 E7  ................
00007FF6FCCDCEF0: E7 E7 E0 CE CD FC E7 E7 E7 E7 E0 CE CD FC E7 E7  ................
port_shutdown_library describing block at 00007FF550025AD0 (header at 00007FF5500258D0):
Wrapped block size is 32768, allocation number is 7717
Block was allocated by segment.c:235
First 32 bytes:
00007FF550025AD0: 00 C1 02 50 F5 7F 00 00 01 00 00 00 00 00 00 00  ...P............
00007FF550025AE0: 00 64 02 50 F5 7F 00 00 A0 73 CA FC F6 7F 00 00  .d.P.....s......
port_shutdown_library describing block at 00007FF53C001840 (header at 00007FF53C001640):
Wrapped block size is 8296, allocation number is 7712
Block was allocated by trclog.c:1022
First 32 bytes:
00007FF53C001840: 55 54 54 42 68 20 00 00 05 00 00 00 00 00 00 00  UTTBh ..........
00007FF53C001850: 40 18 00 40 F5 7F 00 00 E7 E7 40 18 00 3C E7 E7  @..@......@..<..
port_shutdown_library describing block at 00007FF6FCCD27F0 (header at 00007FF6FCCD25F0):
Wrapped block size is 3000, allocation number is 7696
Block was allocated by vmthread.c:123
First 32 bytes:
00007FF6FCCD27F0: E7 E7 F0 27 CD FC E7 E7 E7 E7 F0 27 CD FC E7 E7  ...'.......'....
00007FF6FCCD2800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00007FF548001840 (header at 00007FF548001640):
Wrapped block size is 8296, allocation number is 7687
Block was allocated by trclog.c:1022
First 32 bytes:
00007FF548001840: 55 54 54 42 68 20 00 00 05 00 00 00 00 00 00 00  UTTBh ..........
00007FF548001850: 60 18 00 50 F5 7F 00 00 E7 E7 40 18 00 48 E7 E7  `..P......@..H..
port_shutdown_library describing block at 00007FF6FCCC6CC0 (header at 00007FF6FCCC6AC0):
Wrapped block size is 3000, allocation number is 7671
Block was allocated by vmthread.c:123
First 32 bytes:
00007FF6FCCC6CC0: E7 E7 C0 6C CC FC E7 E7 E7 E7 C0 6C CC FC E7 E7  ...l.......l....
00007FF6FCCC6CD0: E7 E7 C0 6C CC FC E7 E7 E7 E7 C0 6C CC FC E7 E7  ...l.......l....
port_shutdown_library describing block at 00007FF544004650 (header at 00007FF544004450):
Wrapped block size is 104, allocation number is 7668
Block was allocated by jnicsup.cpp:1941
First 32 bytes:
00007FF544004650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00007FF544004660: 00 00 00 00 00 00 00 00 90 74 C7 FC F6 7F 00 00  .........t......
port_shutdown_library describing block at 00007FF5440041A0 (header at 00007FF544003FA0):
Wrapped block size is 104, allocation number is 7667
Block was allocated by jnicsup.cpp:1941
First 32 bytes:
00007FF5440041A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00007FF5440041B0: 00 00 00 00 00 00 00 00 68 74 C7 FC F6 7F 00 00  ........ht......
port_shutdown_library describing block at 00007FF544003CF0 (header at 00007FF544003AF0):
Wrapped block size is 104, allocation number is 7666
Block was allocated by jnicsup.cpp:1941
First 32 bytes:
00007FF544003CF0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00007FF544003D00: 00 00 00 00 00 00 00 00 40 74 C7 FC F6 7F 00 00  ........@t......
port_shutdown_library describing block at 00007FF544001840 (header at 00007FF544001640):
Wrapped block size is 8296, allocation number is 7664
Block was allocated by trclog.c:1022
First 32 bytes:
00007FF544001840: 55 54 54 42 68 20 00 00 05 00 00 00 00 00 00 00  UTTBh ..........
00007FF544001850: 40 18 00 3C F5 7F 00 00 E7 E7 40 18 00 44 E7 E7  @..<......@..D..
port_shutdown_library describing block at 00007FF6FC4D95F0 (header at 00007FF6FC4D93F0):
Wrapped block size is 3000, allocation number is 7647
Block was allocated by vmthread.c:123
First 32 bytes:
00007FF6FC4D95F0: E7 E7 F0 95 4D FC E7 E7 E7 E7 F0 95 4D FC E7 E7  ....M.......M...
00007FF6FC4D9600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00007FF550024760 (header at 00007FF550024560):
Wrapped block size is 2640, allocation number is 7639
Block was allocated by StringTable.cpp:88
First 32 bytes:
00007FF550024760: 09 00 00 00 00 00 00 00 98 00 00 00 34 01 00 00  ............4...
00007FF550024770: 00 00 00 00 00 00 00 00 B8 5C 01 04 00 00 00 00  .........\......
port_shutdown_library describing block at 00007FF5500229C0 (header at 00007FF5500227C0):
Wrapped block size is 6488, allocation number is 7632
Block was allocated by StringTable.cpp:88
First 32 bytes:
00007FF5500229C0: 00 00 00 00 00 00 00 00 60 F0 4C FC F6 7F 00 00  ........`.L.....
00007FF5500229D0: 20 9C 03 54 F5 7F 00 00 F0 8D 4D FC F6 7F 00 00   ..T......M.....
port_shutdown_library describing block at 00007FF6FC235A50 (header at 00007FF6FC235850):
Wrapped block size is 82, allocation number is 7626
Block was allocated by stringhelpers.cpp:335
First 32 bytes:
00007FF6FC235A50: 44 65 73 74 72 6F 79 4A 61 76 61 56 4D 20 68 65  DestroyJavaVM he
00007FF6FC235A60: 6C 70 65 72 20 74 68 72 65 61 64 00 23 FC E7 E7  lper thread.#...
port_shutdown_library describing block at 00007FF6FC18FC30 (header at 00007FF6FC18FA30):
Wrapped block size is 12, allocation number is 7625
Block was allocated by trcmain.c:1007
First 12 bytes:
00007FF6FC18FC30: 4A 56 4D 56 4D 55 54 30 30 31 20 00              JVMVMUT001 .
port_shutdown_library describing block at 00007FF6FC4D44B0 (header at 00007FF6FC4D42B0):
Wrapped block size is 88, allocation number is 7624
Block was allocated by trcmain.c:997
First 32 bytes:
00007FF6FC4D44B0: 55 54 54 44 58 00 00 00 05 00 00 00 00 00 00 00  UTTDX...........
00007FF6FC4D44C0: 00 EC 1E FC F6 7F 00 00 30 72 00 FC F6 7F 00 00  ........0r......
port_shutdown_library describing block at 00007FF6FC04F550 (header at 00007FF6FC04F350):
Wrapped block size is 104, allocation number is 7617
Block was allocated by ../../omr/port/common/omrtlshelpers.c:65
First 32 bytes:
00007FF6FC04F550: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00007FF6FC04F560: 02 00 00 00 94 FF FF FF 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00007FF6FC1F4AD0 (header at 00007FF6FC1F48D0):
Wrapped block size is 352, allocation number is 7615
Block was allocated by TLHAllocationInterface.cpp:57
First 32 bytes:
00007FF6FC1F4AD0: 50 01 00 00 00 00 00 00 00 00 00 00 1F FC E7 E7  P...............
00007FF6FC1F4AE0: 78 57 58 FB F6 7F 00 00 D0 2C 31 FB F6 7F 00 00  xWX......,1.....
port_shutdown_library describing block at 00007FF6FC18F630 (header at 00007FF6FC18F430):
Wrapped block size is 88, allocation number is 7614
Block was allocated by OwnableSynchronizerObjectBufferStandard.cpp:47
First 32 bytes:
00007FF6FC18F630: 48 00 00 00 00 00 00 00 00 00 00 00 18 FC E7 E7  H...............
00007FF6FC18F640: E0 7E 58 FB F6 7F 00 00 40 64 32 FB F6 7F 00 00  .~X.....@d2.....
port_shutdown_library describing block at 00007FF6FC1F9FE0 (header at 00007FF6FC1F9DE0):
Wrapped block size is 88, allocation number is 7613
Block was allocated by UnfinalizedObjectBufferStandard.cpp:47
First 32 bytes:
00007FF6FC1F9FE0: 48 00 00 00 00 00 00 00 00 00 00 00 1F FC E7 E7  H...............
00007FF6FC1F9FF0: 10 89 58 FB F6 7F 00 00 40 72 32 FB F6 7F 00 00  ..X.....@r2.....
port_shutdown_library describing block at 00007FF6FC1F3ED0 (header at 00007FF6FC1F3CD0):
Wrapped block size is 88, allocation number is 7612
Block was allocated by ReferenceObjectBufferStandard.cpp:46
First 32 bytes:
00007FF6FC1F3ED0: 48 00 00 00 00 00 00 00 00 00 00 00 1F FC E7 E7  H...............
00007FF6FC1F3EE0: 10 83 58 FB F6 7F 00 00 40 67 32 FB F6 7F 00 00  ..X.....@g2.....
port_shutdown_library describing block at 00007FF6FC1F44D0 (header at 00007FF6FC1F42D0):
Wrapped block size is 88, allocation number is 7611
Block was allocated by LargeObjectAllocateStats.cpp:85
First 32 bytes:
00007FF6FC1F44D0: 48 00 00 00 00 00 00 00 00 00 00 00 1F FC E7 E7  H...............
00007FF6FC1F44E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00007FF6FC2A4A70 (header at 00007FF6FC2A4870):
Wrapped block size is 976, allocation number is 7610
Block was allocated by LargeObjectAllocateStats.cpp:60
First 32 bytes:
00007FF6FC2A4A70: C0 03 00 00 00 00 00 00 00 00 00 00 2A FC E7 E7  ............*...
00007FF6FC2A4A80: E7 E7 70 4A 2A FC E7 E7 E7 E7 70 4A 2A FC E7 E7  ..pJ*.....pJ*...
port_shutdown_library describing block at 00007FF6FC0D16C0 (header at 00007FF6FC0D14C0):
Wrapped block size is 1008, allocation number is 7609
Block was allocated by LargeObjectAllocateStats.cpp:54
First 32 bytes:
00007FF6FC0D16C0: E0 03 00 00 00 00 00 00 00 00 00 00 0D FC E7 E7  ................
00007FF6FC0D16D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00007FF6FC3E35A0 (header at 00007FF6FC3E33A0):
Wrapped block size is 1008, allocation number is 7608
Block was allocated by LargeObjectAllocateStats.cpp:46
First 32 bytes:
00007FF6FC3E35A0: E0 03 00 00 00 00 00 00 00 00 00 00 3E FC E7 E7  ............>...
00007FF6FC3E35B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00007FF6FC2A2620 (header at 00007FF6FC2A2420):
Wrapped block size is 8192, allocation number is 7607
Block was allocated by ConfigurationStandard.cpp:273
First 32 bytes:
00007FF6FC2A2620: 01 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00  ........@.......
00007FF6FC2A2630: 00 00 00 00 00 00 00 00 B8 31 2D 00 00 00 00 00  .........1-.....
port_shutdown_library describing block at 00007FF6FC0D0270 (header at 00007FF6FC0D0070):
Wrapped block size is 4096, allocation number is 7606
Block was allocated by vmthread.c:228
First 32 bytes:
00007FF6FC0D0270: 00 00 00 00 00 00 00 00 48 00 00 00 44 00 00 00  ........H...D...
00007FF6FC0D0280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
port_shutdown_library describing block at 00007FF6FC23C7F0 (header at 00007FF6FC23C5F0):
Wrapped block size is 24, allocation number is 7605
Block was allocated by vmthread.c:228
First 24 bytes:
00007FF6FC23C7F0: 00 00 00 00 00 00 00 00 78 3A E9 FF FF FF FF FF  ........x:......
00007FF6FC23C800: 70 3A E9 FF FF FF FF FF                          p:......
port_shutdown_library describing block at 00007FF6FC1EFD10 (header at 00007FF6FC1EFB10):
Wrapped block size is 72, allocation number is 7604
Block was allocated by vmthread.c:228
First 32 bytes:
00007FF6FC1EFD10: 28 00 00 00 00 00 00 00 64 00 00 00 00 00 00 00  (.......d.......
00007FF6FC1EFD20: 00 10 00 00 00 00 00 00 C8 CA 04 00 00 00 00 00  ................
Memory checker statistics:
Total blocks allocated = 7836 ( = most recent allocationNumber)
Total blocks freed = 3424
Total bytes allocated = 27237191
Total bytes freed = 2840408
Total unknown blocks ignored = 0
High water blocks allocated = 4624
High water bytes allocated = 24793810
Largest block ever allocated = size 2571672, allocation number 313
Failed allocation attempts = 0
4412 allocated blocks totaling 24396783 bytes were not freed before shutdown!
```

**Comment by JasonFengJ9** [comment]
Occurred at `JDK12` as well, https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_extended.functional_s390x_linux_Nightly/36/tapResults/.

**Comment by pshipton** [comment]
The problem happens occasionally, I've stopped recording the failures.

**Comment by JasonFengJ9** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_extended.functional_s390x_linux_Nightly/53/tapResults/

This is same as https://github.com/eclipse/openj9/issues/4426, one is `zLinux`, the other is `AIX`.

**Comment by JasonFengJ9** [comment]
One more in `mac` at https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/40/tapResults/
```
FAILED: testMemoryLeaks
java.lang.AssertionError: -Xcheck:memory failed: stderr = WARNING: 4537 unfreed blocks remaining at shutdown!
WARNING: 0 blocks were ignored per ignoredCallsite parameter
WARNING: only 32 most recent leaked blocks will be described
port_shutdown_library describing block at 000000000AACA400 (header at 000000000AACA200):
Wrapped block size is 32768, allocation number is 6585
Block was allocated by segment.c:233
First 32 bytes:
000000000AACA400: 00 DA AC 0A 00 00 00 00 00 00 00 00 00 00 00 00  ................
000000000AACA410: EC D9 98 23 00 00 00 00 70 AA AC 0A 00 00 00 00  ...#....p.......
port_shutdown_library describing block at 00007FAAA9BC0E20 (header at 00007FAAA9BC0C20):
Wrapped block size is 2640, allocation number is 6574
Block was allocated by KeyHashTable.c:549
```

**Comment by pshipton** [comment]
This failure happens intermittently, I don't bother reporting it every time.

**Comment by pshipton** [comment]
This seems obsolete.
