### ISSUE TITLE
Crash in NativeCrypto.DigestUpdate (openssl native)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#4530]
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/crypto/jniprovider/NativeCrypto.DigestUpdate(Native Method)
4XESTACKTRACE                at sun/security/provider/NativeDigest.engineUpdate(NativeDigest.java:103)
4XESTACKTRACE                at java/security/MessageDigest$Delegate.engineUpdate(MessageDigest.java:613)
4XESTACKTRACE                at java/security/MessageDigest.update(MessageDigest.java:355)
4XESTACKTRACE                at com/sun/crypto/provider/HmacCore.engineUpdate(HmacCore.java:180)
4XESTACKTRACE                at javax/crypto/Mac.update(Mac.java:505)
4XESTACKTRACE                at sun/security/ssl/Authenticator$MacImpl.compute(Authenticator.java:510)
4XESTACKTRACE                at sun/security/ssl/Authenticator$TLS10Mac.compute(Authenticator.java:581)
4XESTACKTRACE                at sun/security/ssl/Authenticator$MAC.compute(Authenticator.java:444)
4XESTACKTRACE                at sun/security/ssl/SSLCipher.addMac(SSLCipher.java:2089)
4XESTACKTRACE                at sun/security/ssl/SSLCipher$T11BlockWriteCipherGenerator$BlockWriteCipher.encrypt(SSLCipher.java:1449)
4XESTACKTRACE                at sun/security/ssl/OutputRecord.t10Encrypt(OutputRecord.java:462)
4XESTACKTRACE                at sun/security/ssl/OutputRecord.encrypt(OutputRecord.java:394)
4XESTACKTRACE                at sun/security/ssl/SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:78)
5XESTACKTRACE                   (entered lock: sun/security/ssl/SSLSocketOutputRecord@0x00000000C0C0EDE8, entry count: 2)
4XESTACKTRACE                at sun/security/ssl/TransportContext.warning(TransportContext.java:243)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:553)
5XESTACKTRACE                   (entered lock: sun/security/ssl/SSLSocketOutputRecord@0x00000000C0C0EDE8, entry count: 1)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.close(SSLSocketImpl.java:479)
4XESTACKTRACE                at sun/security/ssl/BaseSSLSocketImpl.finalize(BaseSSLSocketImpl.java:275)
4XESTACKTRACE                at java/lang/J9VMInternals.runFinalize(J9VMInternals.java:328)
```

**Comment by pshipton** [comment]
The workaround for this is to disable the openssl digest support.
`-Djdk.nativeDigest=false`

**Comment by ibm-rtvs** [comment]
I'm seeing this as a regression in: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b03)
Eclipse OpenJ9 VM (build openj9-0.14.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190417_286 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5590c4f818 based on jdk8u212-b03)

using the docker image: adoptopenjdk/openjdk8-openj9

**Comment by pshipton** [comment]
@ashbm5 can you please investigate https://github.com/eclipse/openj9/issues/4530#issuecomment-487534024

@ibm-rtvs can you please open a new issue. Until we have one, I'll reopen this one as a reminder.

**Comment by pshipton** [comment]
@vij-singh fyi

**Comment by ashbm5** [comment]
@pshipton are there instructions how can this issue be reproduced? stacktrace? the test put in place to check for this issue is passing

**Comment by pshipton** [comment]
In the absence of a test case, or contact with @ibm-rtvs to get more information, there isn't much we can do.

**Comment by pshipton** [comment]
Perhaps not the same, but we do have https://github.com/eclipse/openj9/issues/5611 opened.

**Comment by pshipton** [comment]
Note the crash occurred from the "Finalizer thread".

**Comment by pshipton** [comment]
Native stack is
```
#12 <signal handler called>
#13 0x0000000000000025 in ?? ()
#14 0x00007fae3c90adaf in Java_jdk_crypto_jniprovider_NativeCrypto_DigestUpdate ()
   from /root/jdk8u212-b03/jre/lib/amd64/libjncrypto.so
```
@ashbm5

**Comment by ashbm5** [comment]
@pshipton looks like the same issue as #5611

**Comment by pshipton** [comment]
The MessageDigest native crypto has been disabled in the 0.14.2 release branches.
ibmruntimes/openj9-openjdk-jdk8#299
ibmruntimes/openj9-openjdk-jdk11#171

**Comment by pshipton** [comment]
MessageDigest native crypto has been disabled in master.
ibmruntimes/openj9-openjdk-jdk8#318
ibmruntimes/openj9-openjdk-jdk11#190
ibmruntimes/openj9-openjdk-jdk12#59
