### ISSUE TITLE
testJITServer failures

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#9792]
These failures occurred on linux_xl in the OMR acceptance build. Not sure if we just got unlucky or there are new problems. I'm going to promote OMR acceptance anyway, I don't believe the failures are caused by OMR changes.

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_OMR_testList_1/9
ub16x64j97
testJITServer_0 - //// can't bind server address: Address already in use
testJITServer_1
`java.lang.IllegalThreadStateException: process hasn't exited`

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OMR_testList_1/9
cent6-x64-1
testJITServer_0
//// Caused by: java.lang.NullPointerException
//// 	at java.base/java.lang.StringCoding.encode(StringCoding.java)

**Comment by pshipton** [comment]
@mpirvu

**Comment by mpirvu** [comment]
Since a good chunk of the JITServer failures happen with XL builds I am strongly considering disabling JITServer for XL until we figure out the problem.

**Comment by pshipton** [comment]
This one isn't XL
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_1/9

**Comment by a7ehuo** [comment]
A quick glance at the [console log](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_1/9/consoleText), I found something interesting regarding to the failure of `can't bind server address: Address already in use` with `testJITServer_0`.  There is no `Stopping server..` in between two server start [1]. I guess that's why the second and the subsequent server start failed. When I run `testJITServer_0` locally [2], there is `Stopping server..`. I'll look at the test script next. 

[2]
```
[2020-06-04T05:28:03.333Z] [JITServerTest] [INFO] Starting server with command line:
[2020-06-04T05:28:03.333Z] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=47856
...
[2020-06-04T05:28:06.223Z] [JITServerTest] [INFO] Starting client with command line:
...
[2020-06-04T05:28:06.223Z] [JITServerTest] [INFO] With stdout/stderr redirected to:
...
[2020-06-04T05:28:08.499Z] [JITServerTest] [INFO] Waiting for 45000 millis.
[2020-06-04T05:29:01.263Z] [JITServerTest] [INFO] Stopping client...
[2020-06-04T05:29:01.263Z] [JITServerTest] [INFO] running testServerComesUpAfterClient: INFO and above level logging enabled
[2020-06-04T05:29:01.263Z] [JITServerTest] [INFO] Starting client with command line:
...
[2020-06-04T05:29:01.263Z] [JITServerTest] [INFO] With stdout/stderr redirected to:
...
[2020-06-04T05:29:01.263Z] [JITServerTest] [INFO] Waiting for 45000 millis.
[2020-06-04T05:29:47.434Z] [JITServerTest] [INFO] Starting server with command line:
[2020-06-04T05:29:47.434Z] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=47856
````

[2]
```
[JITServerTest] [INFO] Starting server with command line:
[JITServerTest] [INFO] Starting client with command line:
[JITServerTest] [INFO] Waiting for 45000 millis.
[JITServerTest] [INFO] Stopping client...
[JITServerTest] [INFO] Stopping server...
[JITServerTest] [INFO] running testServerComesUpAfterClient: INFO and above level logging enabled
[JITServerTest] [INFO] Starting client with command line:
[JITServerTest] [INFO] Waiting for 45000 millis.
[JITServerTest] [INFO] Starting server with command line:
```

**Comment by a7ehuo** [comment]
Thanks @ymanton for pointing out more details about this test as below.
The sequence of failures is 
- `testServer()` starts
    - Tries to kill the Client thread at the end of the test case `testServer()`.
    - `IllegalThreadStateException` is thrown by `exitValue()` when the client thread is not terminated yet in `destroyAndCheckProcess(client, clientBuilder)` [1].
    - Because of the exception during terminating the client, terminating the server thread is likely not executed properly and no logs are out put. 
- `testServerComesUpAfterClient()` starts
    - Tries to start the server at the same port but the server started by `testServer()` is still running.

One change that could be done is to add more delays if the thread is still alive.
https://github.com/eclipse/openj9/blob/ab7f03ab6faa069307a3ddedf09ac26f79b9702c/test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java#L129-L133
==>
```java
     p.destroy();
     int waitCount=0;
     while (p.isAlive() && (waitCount <= 3)) {
         Thread.sleep(PROCESS_DESTROY_WAIT_TIME_MS);
         waitCount++;
     }
     final int exitValue = p.exitValue();
```
[1]
```
FAILED: testServer
[2020-06-04T05:30:35.087Z] java.lang.IllegalThreadStateException: process hasn't exited
[2020-06-04T05:30:35.087Z] 	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:421)
[2020-06-04T05:30:35.087Z] 	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:133)
[2020-06-04T05:30:35.087Z] 	at jit.test.jitserver.JITServerTest.testServer(JITServerTest.java:202)
...
```

**Comment by dmitry-ten** [comment]
These failures haven't occurred in a long time, since we pushed some bug fixes.
@mpirvu this issue can now be closed.

**Comment by mpirvu** [comment]
Will re-open if we see it again.
